### ISSUE TITLE
Review Azure.Security.KeyVault.Secrets.AspNetCore.DataProtection extension methods

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#10003]
Per @tg-msft comments on the original PR:

> I guess there's no meaningful case where this would ever be a public access blob, right? That's the only other case where the Sas would be null with a shared key.

> Would it actually be nicer to throw if there's no Sas and make users supply the DefaultAzureCredential themselves in the other overload that takes a token credential? I don't have a good feel for how much magic is the right amount of magic in the ASP.NET world.

> I find it a little confusing that we've got helpers for Sas/TokenCredential but not SharedKeyCredential/ConnectionString. I get that users could instantiate it themselves and pass a BlobClient in to the other overload, but I'm not sure it will be as obvious to others. I'm guessing this is a design decision to guide people toward better auth choices? I think it's fine to Preview but would be worth looking to see if people struggle here.

**Comment by blueww** [comment]
Please add "client" tag, as this is not for storage management plan.

**Comment by pakrym** [comment]
This was done.
