### ISSUE TITLE
[Question] formrecognizer is still using v1.0-preview

### ISSUE THREAD

**Issue by miflamashood** [Azure/azure-sdk-for-net#10002]
Hi,

I note that formrecognizer is still using v1.0-preview, any plans to move to 2.0?

**Comment by jsquire** [comment]
//cc: @annelo-msft

**Comment by mayurid** [comment]
Hi @miflamashood : Thanks for the feedback. We are working on the new API which will be targeting 2.0 and  will be releasing it soon. We will keep you posted on the exact date.

**Comment by kinelski** [comment]
Hello, @miflamashood. The new package that targets the v2.0-preview API had its first preview released today. Our [README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/README.md) contains detailed information on how to get started in case you feel interested.

Let us know if you have any concerns.
