### ISSUE TITLE
System.ObjectDisposedException: Cannot access a disposed object.

### ISSUE THREAD

**Issue by StevenDevooght** [Azure/azure-sdk-for-net#10007]
**Describe the bug**
We are using a MessageReceiver to process messages on an Azure service bus queue. 99% of the time everything works as expected. But every now and then the following exceptions occurs when we call PeekAsync() on the MessageReceiver:
_Object name: 'sasl10293166'. ---> System.ObjectDisposedException: Cannot access a disposed object._
The problem is that after the exception is thrown our process hangs and we have to manually restart the process.

**Expected behavior**

1. Ideally a workaround or fix so the exception is not thrown
2. Not end up in a blocked state.

**Actual behavior (include Exception or Stack Trace)**
Our process hangs forever. Manually killing the process is the only solution we have at the moment.

**To Reproduce**
We have not managed to reproduce this issue ourselves. It happens randomly. Maybe related to a network glitch?

**Environment:**
- Microsoft.Azure.ServiceBus 4.1.1
- Windows Server 2012 R2 Standard (.NET Framework 4.7.2)

**Comment by jsquire** [comment]
//cc: @nemakam

**Comment by nemakam** [comment]
@StevenDevooght , quick question regarding "hang" - Can you check if it auto-mitigates after 60 seconds (which is the default timeout for a lot of operations)?
Also, what is "hang" here? Is there an operation which doesn't timeout and is being operated on forever? Or that you don't receive any message after this even though you are calling Receive/PeekAsync?
Or Is there a path in your code which hangs when you get an ObjectDisposedException?

**Comment by nemakam** [comment]
You could try taking a dump of your application and see what is the operation that it is "hung" on. If its a service bus SDK operation, then could you share the stack trace?

**Comment by StevenDevooght** [comment]
@nemakam We have a job system (windows service) using Quartz.NET where we are using the MessageReceiver to pull messages from our Azure queues. If the above error occurs the job never finishes (also not after 60 seconds). The windows service can only be stopped by killing the process. So after the error occurs something is preventing it to stop gracefully.

I did not mention this in the initial issue, but due to technical limitations we are calling PeekAsync in a synchronous way.
`_messageReceiver.PeekAsync().GetAwaiter().GetResult()`
So at the moment we think that a deadlock is causing our issue...

**Comment by nemakam** [comment]
I would still think its best if you can capture a dump and analyze the stack trace when the system gets hung

**Comment by StevenDevooght** [comment]
We have a .dmp file of the hanging process. But for some reason I cannot load the symbols for _Microsoft.Azure.ServiceBus_ & _Microsoft.Azure.Amqp_. _Microsoft.ApplicationInsights_ loads fine...

The Nuget.org symbol server should suffice?

**Comment by nemakam** [comment]
@StevenDevooght, thanks for opening it up as a new issue #10262 so that it can be tracked there.

**Comment by StevenDevooght** [comment]
We managed to get a stacktrace of the hanging process.


`System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    Microsoft.Azure.Amqp.AsyncResult.End[[System.__Canon, mscorlib]](System.IAsyncResult)    Microsoft.Azure.Amqp.AmqpObject+OpenAsyncResult.End(System.IAsyncResult)    Microsoft.Azure.Amqp.AmqpObject.EndOpen(System.IAsyncResult)    System.Threading.Tasks.TaskFactory`1[[System.Threading.Tasks.VoidTaskResult, mscorlib]].FromAsyncCoreLogic(System.IAsyncResult, System.Func`2<System.IAsyncResult,System.Threading.Tasks.VoidTaskResult>, System.Action`1<System.IAsyncResult>, System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, Boolean)    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.ServiceBus.ServiceBusConnection+<CreateConnectionAsync>d__45.MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1+<OnCreateAsync>d__6[[System.__Canon, mscorlib]].MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.Amqp.Singleton`1+<GetOrCreateAsync>d__13[[System.__Canon, mscorlib]].MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.Amqp.Singleton`1+<GetOrCreateAsync>d__13[[System.__Canon, mscorlib]].MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator+<CreateAndOpenAmqpLinkAsync>d__11.MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.ServiceBus.Core.MessageReceiver+<CreateRequestResponseLinkAsync>d__102.MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1+<OnCreateAsync>d__6[[System.__Canon, mscorlib]].MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.Amqp.Singleton`1+<GetOrCreateAsync>d__13[[System.__Canon, mscorlib]].MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.Amqp.Singleton`1+<GetOrCreateAsync>d__13[[System.__Canon, mscorlib]].MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.ServiceBus.Core.MessageReceiver+<ExecuteRequestResponseAsync>d__84.MoveNext()    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)    Microsoft.Azure.ServiceBus.Core.MessageReceiver+<OnPeekAsync>d__87.MoveNext()`

**Comment by nemakam** [comment]
How many connections do you have to ServiceBus from this machine?
Based on stack trace it looks like it is not able to create a connection. 
Is this on Azure? What kind of service is this? Lot of different services have upper bound on how many outbound connections are allowed. Could you check that for your service

**Comment by StevenDevooght** [comment]
The system we have in place is a windows service using Quartz.net jobs for processing work. We only have 8 jobs that process ServiceBus queues. So the maxmium number of concurrent connections to ServiceBus is only 8. Every 5 seconds a job runs opens up a connection to the queue (using MessageReceiver) and processes the messages. If processing is done, we close the MessageReceiver. The windows service is **not** hosted on azure, but on a on premise server.

There are no errors in the windows event viewer. I suspect that when the connections are exausted there would be an entry for this issue...

If the connections are the issue, it's still strange that the process hangs

**Comment by nemakam** [comment]
How often do you see this?
Do you see any other patterns emerge? for example, after x minutes/messages you run into this. Or are there any other exceptions around this time? 
When one connection is stuck, why are other connections also stuck?

**Comment by StevenDevooght** [comment]
There is no real pattern for the issue. Sometimes we don't have it for weeks. Sometimes we have it multiple times per week. We have 8 jobs that process Azure service bus queue messages. Every 5 seconds we check if there are messages on the queue using the peek functionality. This means we open & close 96  `MessageReceivers` per minute.

We noticed that we have 100+ TIME_WAIT connections to azure
`TCP    192.168.0.175:63971    51.144.124.255:5671    TIME_WAIT`

This behavior can be reproduced using the following snippet.

```
using Microsoft.Azure.ServiceBus.Core;
using System;
using System.Threading;

namespace AzureServiceBus
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Azure ServiceBus Test Started!");

            while (true)
            {
                Execute();
                Thread.Sleep(5000);
            }
        }

        private static void Execute()
        {
            MessageReceiver messageReceiver = null;
            try
            {
                messageReceiver = new MessageReceiver("Endpoint=amqps://infohos-integration.servicebus.windows.net;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=G6yTx+aaJzIm6js79E+fGw9Be5mZm1gT8RGdhqJdNr4=", "integrationtestsmessagebroker");
                var result = messageReceiver.PeekAsync().GetAwaiter().GetResult();
            }
            finally
            {
                if (messageReceiver != null)
                {
                    messageReceiver.CloseAsync().GetAwaiter().GetResult();
                }
            }
        }

    }
}

```

**Comment by nemakam** [comment]
96 connections per minute doesn't sound healthy to me. I'd really recommend you to see if you are able to reuse your MessageReceiver objects. Even if the link is closed, the link is automatically re-established within the SDK. 
Given that you have 96 connections per minute. 100+ TIME_WAIT does sound in-line to expectations. 
Are you able to consistently repro using this repro code?
Also, I still think this is deadlock issue. If it were one connection which was stuck, I'd say there's a bug in the code. But if all of them (which are independent) stop working, given mixed usage of async-and-sync code, then I'd think its out of scope of the SDK. Let me know if you disagree.

**Comment by StevenDevooght** [comment]
It is only one connection which is stuck. If a connection is stuck that specific job keeps hanging, but the other jobs keep doing their work. So only 1 queue is not processed anymore. The other queues are processed normally...

**Comment by nemakam** [comment]
Oh. Okay
> The problem is that after the exception is thrown our process hangs and we have to manually restart the process.

This sentence made me assume the whole process hangs and nothing proceeds ahead.

**Comment by StevenDevooght** [comment]
> I'd really recommend you to see if you are able to reuse your MessageReceiver objects. Even if the link is closed, the link is automatically re-established within the SDK.

Can you clarify what closing the link means? If you try to reuse a closed MessageReceiver you get:
`ServiceBusConnection has already been closed. Please create a new instance.`

The [official examples](https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.Azure.ServiceBus/ReceiveLoop/Program.cs) also close & recreate the MessageReceiver every run.

**Comment by nemakam** [comment]
Once you call `Receiver.CloseAsync()`, you cannot reuse it.
By "closing the link" I mean, that if there was an intermittent communication issue / network issue, it would automatically try to connect again. 
Receiver objects are ideally supposed to be long running. Its best to reuse it. 

And in the example above, we create the receiver object. Try receiving all messages with that receiver, and then close only when we are closing the whole console application.

**Comment by jsquire** [comment]
//cc: @jfggdl
