### ISSUE TITLE
x-opt-scheduled-enqueue-time using AmqpLite

### ISSUE THREAD

**Issue by ctrlaltdan** [Azure/azure-sdk-for-net#10016]
Hey, I'm interested in using the Azure Service Bus scheduled enqueue time feature through Azure's AmqpLite package.

From reading the source code I can see this should only require a message header of `x-opt-scheduled-enqueue-time` be added to the message however this doesn't appear to delay the enqueue time.

https://github.com/Azure/azure-sdk-for-net/blob/4bab05144ce647cc9e704d46d3763de5f9681ee0/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Amqp/AmqpMessageConverter.cs#L21

Would the team be able to give any additional insight into the configuration of the message, or perhaps the queue to enable me to use this feature outside of the `Microsoft.Azure.ServiceBus` library?

**Comment by nemakam** [comment]
@ctrlaltdan ,
You're on the right path. I would recommend you to try that again as there isn't any other magic sauce that I can think of that's required to get Scheduled Messages working.
Another think you might want to double check on would be the encoding for the timestamp itself. 

And for my understanding, is there a particular reason why you're using AmqpLite over the official ASB SDK?

**Comment by nemakam** [comment]
And of course, needless to say, make sure you're adding that property to `MessageAnnotations` and not the other property bags

**Comment by ctrlaltdan** [comment]
Hey @nemakam, thanks for your reply.

I have gone through the implementation with a fine toothed comb. The following is the output from my testing between the ServiceBus package and the Amqp package.

*Microsoft.Azure.ServiceBus*

```
var body = ...
var manifest = ...
var time = DateTime.UtcNow.Add(TimeSpan.FromSeconds(60));

var queueClient = new QueueClient(..., ...);

var message = new Microsoft.Azure.ServiceBus.Message(body)
{
    CorrelationId = body.CorrelationId,
    Label = manifest
};

await queueClient.ScheduleMessageAsync(message, time);
```

Outputs the following in ServiceBusExplorer:

![image](https://user-images.githubusercontent.com/1093690/74836131-ae7c7780-5316-11ea-913e-35c629d53674.png)

*AMQPNetLite.Core*

```
var body = ...
var manifest = ...
var time = DateTime.UtcNow.Add(TimeSpan.FromSeconds(60));

var message = new Amqp.Message(body)
{
    Properties = new Properties
    {
        MessageId = Guid.NewGuid().ToString("N"),
        CreationTime = DateTime.UtcNow,
        Subject = manifest,
        CorrelationId = contract.CorrelationId
    },
    MessageAnnotations = new MessageAnnotations(),
    DeliveryAnnotations = new DeliveryAnnotations(),
    ApplicationProperties = new ApplicationProperties()
};

message.MessageAnnotations.Map.Add("x-opt-scheduled-enqueue-time", time);

await _senderLink.SendAsync(message);
```

Outputs:

![image](https://user-images.githubusercontent.com/1093690/74836415-48dcbb00-5317-11ea-85e3-a2f6de49d125.png)

As you can see the only differences are the missing `ScheduledEnqueueTimeUtc`. You made reference to use the correct encoding for the timestamp. Is there a required format for the DateTime value? From what I can see in the Azure.Amqp and AmqpLite packages, DateTime values are serialized internally?

Any help would be greatly appreciated.

**Comment by nemakam** [comment]
Could you try with some time beyond 60 seconds (just to make sure we are weeding out common problems with clock skews etc). Maybe schedule it for over a day's delay.

**Comment by nemakam** [comment]
Could you try with some time beyond 60 seconds (just to make sure we are weeding out common problems with clock skews etc). Maybe schedule it for over a day's delay.
