### ISSUE TITLE
[EventHubs] Some unit tests are flaky or fail constantly

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#10015]
### Summary

Four of the Event Processor Client tests are not working as expected: one of them is already tracked by #9228, while the other three are tracked by this issue.

- `PartitionClosingAsyncIsCalledWithOwnershipLostReasonWhenStoppingTheFailedProcessor` is flaky. Sometimes the test hangs for indefinite time until it gets canceled. Sometimes it works. The flakiness is believed to have been introduced after the creation of the `PartitionLoadBalancer` class.
- `PartitionClosingAsyncTokenIsCanceledWhenStopProcessingAsyncIsCalled` always fails. Reason is unknown.
- `ProcessErrorAsyncIsTriggeredWithCorrectArgumentsWhenOwnershipClaimFails` always fails, but the cause is known.

https://github.com/Azure/azure-sdk-for-net/blob/1408ad9db2579f2943043549c6af70b98f9eb7fe/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L949-L957

The Event Processor Client cannot figure out which partition failed during the `RunLoadBalancingAsync` call and it's passing a `null` to `ProcessErrorEventArgs` instead of passing the partition id. Ownership claim failure is the only load balancing scenario in which a partition id is expected (`null` should be kept for other types of failure).

### Goal

- Make the necessary changes to the client to make the tests pass reliably without flakiness. The tests themselves could be the real problem, so changes to the tests might also be necessary.
- Remove the `Ignore` attribute from the aforementioned tests.
- Assert that no other tests fail because of the changes.

**Comment by christothes** [comment]
@kinelski Please assign this one to me.

**Comment by pakrym** [comment]
PartitionClosingAsyncIsCalledWithOwnershipLostReasonWhenStoppingTheFailedProcessor is back. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=279006&view=ms.vss-test-web.build-test-results-tab&runId=9291444&resultId=101890&paneView=debug


```
Stop reason in '0' is incorrect.

Expected: Shutdown

But was: OwnershipLost


Stack trace
   at Azure.Messaging.EventHubs.Tests.EventProcessorClientTests.PartitionClosingAsyncIsCalledWithOwnershipLostReasonWhenStoppingTheFailedProcessor() in D:\a\1\s\sdk\eventhub\Azure.Messaging.EventHubs.Processor\tests\Processor\EventProcessorClientTests.cs:line 1833

```

**Comment by jsquire** [comment]
//cc: @kinelski - Do you mind taking a look and if we need to, flagging this one?

**Comment by pakrym** [comment]
PartitionClosingAsyncIsCalledWithOwnershipLostReasonWhenStoppingTheFailedProcessor failed in todays nightly run again.

**Comment by kinelski** [comment]
We'll use #10067 to track Track Two flaky tests, so I'll be closing this issue. `PartitionClosingAsyncIsCalledWithOwnershipLostReasonWhenStoppingTheFailedProcessor` has been added to the list.

**Comment by pakrym** [comment]
Can we disable it? It has been failing fairly consistently.

**Comment by jsquire** [comment]
Looks like that disable was included in #10320

**Comment by christothes** [comment]
How do the nightly runs differ from CI? `PartitionClosingAsyncIsCalledWithOwnershipLostReasonWhenStoppingTheFailedProcessor` still seemed to be passing consistently there and locally. 

(I'm not sure if this is expected, but I don't seem to have access to any of the nightly build results)

**Comment by jsquire** [comment]
In theory, no... the CI and nightly runs are the same for unit tests.  The nightly runs include the live tests as well and, as a result, have a much higher potential for intermittent delays due to longer-running operations , availability in the thread pool, and general wonkiness around ARM calls.

Consequently, we seem to find tests with timing sensitivity during nightly runs moreso than CI or local runs where the time variance isn't as dramatic.
