### ISSUE TITLE
[Sample Request] Bing Spellcheck  in "LUIS V3 prediction endpoint with SDK"

### ISSUE THREAD

**Issue by kesavanpurushothaman** [Azure/azure-sdk-for-net#10013]
**Query/Question**
We are planning to use **Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime** Version 3.0 SDK for our ChatBot. Can you please provide a sample on how to add Bing Spell Check Key in this SDK?

**Environment:**
 - Microsoft.Azure.CognitiveServices.Language.LUIS.Runtime Version 3.0
 - DOTNETCORE 2.1

**Comment by rvanmaanen** [comment]
Hi, could you please followup on this? Currently also running into this. Had a working application but really having issues getting things to work. Even with the v2 endpoint btw. Thought I was doing something wrong, but even from here it isnt working: https://westeurope.dev.cognitive.microsoft.com/docs/services/5819c76f40a6350ce09de1ac/operations/5819c77140a63516d81aee78/console

**Comment by JimSuplizio** [comment]
Hi @kesavanpurushothaman, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
