### ISSUE TITLE
Create a shared implementation of Blob/DataLake parallel upload

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#10026]
The addition of DataLakePartitionedUploader duplicates a lot of complicated logic.  It would be great to have a shared implementation of upload so any future performance work benefits both.  See the discussion at https://github.com/Azure/azure-sdk-for-net/pull/9681#discussion_r374215886 for more detail.

**Comment by JimSuplizio** [comment]
Hi @tg-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
