### ISSUE TITLE
[FEATURE REQ] Allow deletion of specific snapshot with DeleteBlob()

### ISSUE THREAD

**Issue by mjiderhamn** [Azure/azure-sdk-for-net#10023]
**Library or service name.**
`Azure.Storage.Blobs`
 
**Is your feature request related to a problem? Please describe.**
Previous versions of the SDK allowed setting the `snapshot` request header for [Delete Blob](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-blob), by calling `Delete()` on an `ICloudBlob` with `IsSnapshot == true`.

Although `BlobRestClient.Blob.DeleteAsync` in [`Generated/BlobRestClient.cs`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Generated/BlobRestClient.cs) take a `string snapshot` parameter, there is no way to pass this to the `BlobBaseClient.Delete*()` methods.

Please re-add this feature in the v12 SDK.

**Comment by jsquire** [comment]
//cc: @tg-msft

**Comment by tg-msft** [comment]
In the v12 SDK, you should be able to achieve this via `await blob.WithSnapshot(id).DeleteAsync(...)`.
