### ISSUE TITLE
How to access Azure ADF without using client secret key

### ISSUE THREAD

**Issue by mymatrixpixel** [Azure/azure-sdk-for-net#10021]
**How to access Azure ADF -pipeline by using OAUTH2 authentication.**

Is it possible to get access token without client secret key?. if answer is no? is there any other mechanism to get access token?

How to generate client secret key based  on client id/aplication id/tenant id in C# Code?

Tools am using latest version of VS 2019,MSAL.NET  .NET Core console app template.

Am anticipating complete C# working  code to get accesstoken by using OAUTH2/ OpenID connect to ADF.

Note: I already referred to MSDocs. Am expecting code.

**Comment by jongio** [comment]
1. The Management Plane SDKs do not yet support the new Azure.Identity.InteractiveBrowserCredential - that is coming soon. https://docs.microsoft.com/en-us/dotnet/api/azure.identity.interactivebrowsercredential?view=azure-dotnet

2. I created a sample for you using the `DefaultAzureMgmtCredential` adapter class that can be used in the meantime.
 
https://github.com/jongio/azidext/blob/master/net/JonGallant.Azure.Identity.Extensions.Tests/Mgmt/InteractiveBrowserTests.cs

By passing (true) to the DefaultAzureMgmtCredential class, you are telling it to use the InteractiveBrowserCredential.  Which will open a browser and prompt the user to enter their credentials and return an Oauth token.

3. You can copy the following code files in that repo to your project to use it.  
https://github.com/jongio/azidext/blob/master/net/JonGallant.Azure.Identity.Extensions/DefaultAzureCredentialTokenProvider.cs
https://github.com/jongio/azidext/blob/master/net/JonGallant.Azure.Identity.Extensions/DefaultAzureMgmtCredential.cs

4. You can combine DefaultAzureMgmtCredential with this code sample: 

```
var client = new DataFactoryManagementClient(new DefaultAzureMgmtCredential(true)) {
    SubscriptionId = subscriptionId };
```

And the follow along this tutorial for further ADF needs

https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-dot-net#create-a-data-factory-client

I may be slow to respond to further questions as I'm out of the office this week.

Jon

**Comment by mymatrixpixel** [comment]
Hi Jon,
Again , I need to depend on SDK's approach(my team didn't accept it). It may be  change in future. So am looking for solution in pure OAUTH2 and Opened Id connect C# complete code implementation. As per requirement I don't want to have user interactive authentication to get access token. Kindly do the needful.

**Comment by mymatrixpixel** [comment]
Just got an update , web application is registered into azure app service (from this to authenticate the ADF pipeline). Service to service.

**Comment by jongio** [comment]
This is a great resource to help you decide what auth flow to use: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows

Since this is service to service you’ll want to consider use client credentials with a service principal: https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#client-credentials

This doc shows the code for using that with ADF
https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-dot-net#create-a-data-factory-client

**Comment by jongio** [comment]
Getting back to your original question: I don't think there's a way to generate the secret and I don't think there's a way to do service to service without having a secret.

It would be great if you could provide more context into the application architecture and requirements so we can help you further.

**Comment by mymatrixpixel** [comment]
We have a web app which is hosted in azure app service. When user clicks on a button it will invoke a web API (this API ) will invoke Azure ADF pipeline ( in the web API I will get table name along with data) I want to copy data from source( SQL server to azure table storage) destination. I want to dynamically pass the table name and creation(if table exists I want to update if not insert the  data into azure table storage ). Thats it. Can you give sample C# code by using OAUth2 including client secret. I will try it or else service principle code.

**Comment by jongio** [comment]
@mymatrixpixel - The following code from this article should be exactly what you need to authenticate with a client secret.

https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-dot-net#create-a-data-factory-client

```
// Authenticate and create a data factory management client
var context = new AuthenticationContext("https://login.windows.net/" + tenantID);
ClientCredential cc = new ClientCredential(applicationId, authenticationKey);
AuthenticationResult result = context.AcquireTokenAsync(
    "https://management.azure.com/", cc).Result;
ServiceClientCredentials cred = new TokenCredentials(result.AccessToken);
var client = new DataFactoryManagementClient(cred) {
    SubscriptionId = subscriptionId };
```

Can you go through that article and LMK if it's not what you are looking for?

**Comment by mymatrixpixel** [comment]
@jongio I already have the above code. Am asking pure OAUTH2 code implementation, in above code where is the Oauth2 token provider endpoint. Whatever you are referring to me. I already gone through it. Am expecting some dynamic code to pass table names and parameters to achieve my requirements.

**Comment by jongio** [comment]
The AuthenticationContext object accepts the Oauth endpoint.

This is helpful in understanding how the identity platform works:
https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-scenarios

This sample shows you how to run a pipeline:
https://docs.microsoft.com/en-us/azure/data-factory/quickstart-create-data-factory-dot-net#create-a-pipeline-run

I haven't tried it, but I assume you could pass the table named in the `parameters` parameter of the CreateRunWithHttpMessageAsync() call.

**Comment by mymatrixpixel** [comment]
Ok Thanks for the info. I will try and let you know.

**Comment by mymatrixpixel** [comment]
@jongio Can you say, how to read the service principle key and Id from azure.(best approach)

**Comment by jongio** [comment]
One approach is to store them in environment variables.

You generate by using the portal or cli. LMK if you need help with that.

**Comment by jongio** [comment]
@mymatrixpixel - Did you get it working?

**Comment by mymatrixpixel** [comment]
I don't know how to create environment variabkes. Can you give sample or step by step creation. So that I can read it in C# code. Based on each region I will read from environment variable. Can you give sample complete C# code?

**Comment by jongio** [comment]
I typically store my env variables in a .env file and then use the DotNetEnv package to load that file with Env.Load method.  That will automatically put the values in your .env file in your environment and then you read them with Environment.GetEnvironmentVariable methods.

You can also set via command line.  This article has a good example on how to set an env variable with psh or bash.
https://techcommunity.microsoft.com/t5/azure-sdk/authentication-and-the-azure-sdk/ba-p/1191313

**Comment by jongio** [comment]
@mymatrixpixel - Are you set now?

**Comment by mymatrixpixel** [comment]
@jongio we have registered client secrets into key vault. But when I read getaccount is always coming as null. Can you share sample of how to read keyvault by using MSAL . My doubt is redirect uri. I followed msdn docs snippets already but no luck.

**Comment by jongio** [comment]
You'll find a lot of KeyVault secret samples here: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Secrets - that should get you what you need.

**Comment by mymatrixpixel** [comment]
@jongio first we need to get access token(OAUTH2) to authenticate KeyVault right. And then only we will retrieve the key. I just tried it with postman and it's working fine. When I try with MSAL.Net am facing an issue.

**Comment by jongio** [comment]
What's the issue?

**Comment by mymatrixpixel** [comment]
@jongio  IpublicClientApplication am following this snippet . Here app.GetaccountAsync() is coming as null.

**Comment by jongio** [comment]
Can you please provide more of your code than that?  I need more context.  How you are constructing the Credential class, what APIs you are calling, etc.

**Comment by mymatrixpixel** [comment]
Please refer this. Am using this mehod only
https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.clientapplicationbase.acquiretokensilentasync?view=azure-dotnet#Microsoft_Identity_Client_ClientApplicationBase_AcquireTokenSilentAsync_System_Collections_Generic_IEnumerable_System_String__Microsoft_Identity_Client_IAccount_

**Comment by jongio** [comment]
Those APIs are marked as obsolete:

![image](https://user-images.githubusercontent.com/2163001/76122732-9e69c680-5fab-11ea-91e2-d77cffcc0708.png)


The comment says to use AquireTokenSilent instead.    Try that.

For more assistance, we're going to need more context, for example, what is the exact code that you are running before you call this? What is the host? console, webapp, etc. and also what error messages are you getting.

**Comment by mymatrixpixel** [comment]
@jongio  I want to get access token to authenticate Azure Key vault. Please refer below code.
1. Once i get the access token i want to retrive secret keys. and then i want to get accesstoken to authenticate Datafactory. I'm trying to use MSAL.NET instead of ADAL as per microsoft recommendations. Can you revamp the code and provide a better snippets.
class Program{
public IPublicClientApplication Publiclientaplication {get;set;}

string clientid="someid";
string tenantid="sometenantid";
string redirecturi ="https://login.microsoftonline.com/common/oauth2/nativeclient"; //Am not sure what to pass here. since grab it from MSDOCS.
string authority="https://login.microsoftonline.com/tenantid/oauth2/v2.0/token";
//constructor
public Program(){
var clientApplication = PublicClientApplicationBuilder.Create(clientid)
                                     .WithAuthority(authority,tenantid)
                                     .WithRedirectUri(redirecturi)
                                     .Build();
PublicClientApplication = clientApplication;
}

static async Task Main(string[] args)
{
    var   scope= new [] {"https://vault.azure.net/.default"};
    var accounts = await PublicClientApplication.GetAccountAsync(); //Coming as null
var firstaccount = accouts.FirstOrDefault();
var authorizationResult = await PublicClientApplication.AcquireTokenSilent(scope,firstaccount).ExecuteAsync();
Console.WriteLine(authorizationResult.AccessToken);
}
}

**Comment by mymatrixpixel** [comment]
> Please refer this. Am using this mehod only
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.clientapplicationbase.acquiretokensilentasync?view=azure-dotnet#Microsoft_Identity_Client_ClientApplicationBase_AcquireTokenSilentAsync_System_Collections_Generic_IEnumerable_System_String__Microsoft_Identity_Client_IAccount_

I wrongly sent .

**Comment by mymatrixpixel** [comment]
> I typically store my env variables in a .env file and then use the DotNetEnv package to load that file with Env.Load method. That will automatically put the values in your .env file in your environment and then you read them with Environment.GetEnvironmentVariable methods.
> 
> You can also set via command line. This article has a good example on how to set an env variable with psh or bash.
> https://techcommunity.microsoft.com/t5/azure-sdk/authentication-and-the-azure-sdk/ba-p/1191313

I tried to create .env file , but VS2019 isn't able to recognize the file type.

**Comment by mymatrixpixel** [comment]
@jongio Do you have any update on this?

**Comment by jongio** [comment]
Just coded with @mymatrixpixel for the last 4.5 hours and got what he needed with this: https://gist.github.com/jongio/d3682511f715ada6681363a0fe7ad8ee

(Minus the upsert functionality, which he will refer to this: https://www.taygan.co/blog/2018/04/20/upsert-to-azure-sql-db-with-azure-data-factory)

**Comment by jongio** [comment]
Closing as we have unblocked this specific request and the original submitter will file a new GH issue for new problems he encounters.
