### ISSUE TITLE
[BUG] SecretClient.GetPropertiesOfSecrets() returns deleted secrets

### ISSUE THREAD

**Issue by andersborum** [Azure/azure-sdk-for-net#10043]
**Describe the bug**
We're using the `Azure.Security.KeyVault.Certificates` v4.0.0 SDK to retrieve secrets from Azure Key Vault and find deleted **managed** secrets in the result. The `SecretProperties` class doesn't provide any properties that relate to the deletion status of the secret.

Also, we find it **quite** confusing that the `SecretClient.GetPropertiesOfSecrets()` API considers certificate entries as **managed** secrets; it isn't obvious from the documentation either and caught us off guard.

**Expected behavior**
We're expecting the `SecretClient.GetPropertiesOfSecrets()` API to return a list of secrets (managed and unmanaged) **without** deleted entries; alternatively, the `SecretProperties` class sould provide properties that relate to the deletion status of the secret.

**Actual behavior (include Exception or Stack Trace)**
Deleted entries are included in the result.

**To Reproduce**
Create and soft delete a managed certificate in Azure Key Vault, then run the following code snippet:
```
var client = new SecretClient(vaultUri, new ClientSecretCredential(tenantID, clientID, clientSecret));
var properties = client.GetPropertiesOfSecrets(token).OrderBy(p => p.Name).ToList();
```

**Environment:**
 - Azure.Security.KeyVault.Certificates v4.0.0 
 - Windows 10, Azure AppService
 - Visual Studio 16.4.5, .NET 4.7.2

**Comment by jsquire** [comment]
//cc: @heaths

**Comment by andersborum** [comment]
The certificate was deleted about 2 weeks ago. I am aware of the delay from soft deleting a secret to the Key Vault actually physically deleting the entry (90 days rention I believe as per the documentation).

The issue is really not the soft delete feature (which is fine), but the fact that I'm getting deleted entries in results where none was expected (or even meta data to inform about the status of the deletion).

Also, I don't fully understand your question regarding "Do you have any suggestions how we might clarify this better", as the issue doesn't originate from lifetime management, but the fact that there's no way to distinguish between soft deleted or normal entries.

Please elaborate.

**Comment by heaths** [comment]
You said,
> Also, we find it quite confusing that the SecretClient.GetPropertiesOfSecrets() API considers certificate entries as managed secrets; it isn't obvious from the documentation either and caught us off guard.

I pointed out what the documentation says about what the `Managed` property means and am asking what is not clear about that so we might consider a change to the documentation.

`Managed == true` just means that the key or secret is backing a certificate. It has nothing directly to do with deleted secrets, though deleting a certificate in a soft delete-enabled vault will also put its managed keys and secrets in a deleted state.

As for the problem with deleted secrets, I see that when a certificate is deleted its keys and secrets are not. @RandalliLama can your team look into this service-side?

**Comment by RandalliLama** [comment]
@heaths unfortunately that is known issue that is in our backlog to fix.

**Comment by andersborum** [comment]
@heaths agree on the `Managed == true` expectation as that's also what I learned from the docs (which is fine and dandy).

@RandalliLama any chance you could provide an ETA on the fix?

**Comment by sebansal** [comment]
@heaths This is tracked by bug 5281498.

**Comment by sebansal** [comment]
@AshokCMSFT team is working on it.

**Comment by andersborum** [comment]
What's the status on this bug report? Is it really the ambition by the team to ask the community to spend time reporting bug and then ignore said bugs for 8 - 9 months?

**Comment by AshokCMSFT** [comment]
This issue is being worked on. The plan is to fix it early next year.

**Comment by sebansal** [comment]
Tracked internally Bug 2036293

**Comment by sebansal** [comment]
akv engineering team will triage

**Comment by sebansal** [comment]
Solution is deployed.
