### ISSUE TITLE
[BUG] Docs - /sample directory's .csproj file is missing description

### ISSUE THREAD

**Issue by diberry** [Azure/azure-sdk-for-net#10060]
**Describe the bug**
The sample .csproj doesn't have a description. The description needs to include the text, sample code, and links to acom, conceptual docs and ref docs. 

**Expected behavior**
The expected behavior is that a developer doesn't have to do anything more than the sample which they aren't so generally the SDKs don't have any descriptive text or links that a customer needs. 

**Actual behavior (include Exception or Stack Trace)**
.NET NuGet package pages don't information a customer needs to be successful. 

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Search through the repo for the description field in the csproj files
2. Most of the description fields are release notes. 

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by AlexGhiondea** [comment]
@diberry I am not sure what we should do here -- are you saying that we should add a different description in the package file for the samples?

**Comment by diberry** [comment]
@AlexGhiondea Which file in the /samples directory do you think has the description info that appears on the NuGet package page? 

I have a [PR](https://github.com/Azure/azure-sdk-for-net/pull/10061/files) to fix a file that does not have the description.

**Comment by AlexGhiondea** [comment]
@diberry the PR you mention is for a sample project that we don't release on NuGet.

**Comment by AlexGhiondea** [comment]
For the shipping packages we autogenerate the NuGet package description before we publish to NuGet.

**Comment by diberry** [comment]
@AlexGhiondea Yes, I've worked with @weshaggard regarding getting the product information onto the NuGet package page. Most Azure SDK package pages have no information relevant to the SDK. A customer would have to download the SDK, then return the browser and search for relevant product information, conceptual docs, or reference docs. I would like to fix that. Can you suggest a different method to getting the information into the package page for Azure SDKs?

**Comment by diberry** [comment]
@AlexGhiondea What is the forcing function to ensure the information is in each .csproj for each SDK?
