### ISSUE TITLE
[EventHubs] Event Processor tests failing during nightly runs (Track Two)

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#10067]
# Summary

Some tests have recently begun experiencing failures during nightly runs, some intermittently and some constantly. Example failures can be found in the nightly results from February 20, which can be found [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=265684&view=ms.vss-test-web.build-test-results-tab) and [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=265638&view=ms.vss-test-web.build-test-results-tab). Some failures can be found [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=266692&view=ms.vss-test-web.build-test-results-tab), [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=267229&view=ms.vss-test-web.build-test-results-tab) and [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=279006&view=ms.vss-test-web.build-test-results-tab&runId=9291444&resultId=101890&paneView=debug) as well. These tests are:

- [ ] PartitionClosingAsyncIsCalledWithOwnershipLostReasonWhenStoppingTheFailedProcessor
- [ ] PartitionClosingAsyncIsCalledWithShutdownReasonWhenStoppingTheProcessor
- [ ] PartitionInitializingAsyncTokenIsCanceledWhenStopProcessingAsyncIsCalled
- [ ] ProcessErrorAsyncIsNotTriggeredWhenRelinquishingOwnershipFails
- [ ] ProcessErrorAsyncIsNotTriggeredWhenUpdateCheckpointFails
- [ ] ProcessErrorAsyncIsTriggeredWithCorrectArgumentsWhenOwnershipRenewalFails
- [ ] ProcessorDoesNotProcessCheckpointedEventsAgain
- [ ] ProcessorStopsProcessingPartitionItDoesNotOwnAnymore
- [ ] RunPartitionProcessingAsyncAddsAttributesToLinkedActivities
- [ ] RunPartitionProcessingAsyncCreatesScopeForEventProcessing
- [ ] StopProcessingAsyncStopsProcessingForEveryPartition
- [ ] UpdateCheckpointAsyncCreatesScope

# Scope of Work

- Analyze the test(s) to understand the point of non-determinism and decide on an approach to stabilize for nightly runs.

- Refactor the tests as needed to ensure that the results are deterministic and consistently pass.

# Out of Scope

- Changes or refactoring in other areas.

# Success Criteria

- The test(s) discussed in the summary have been refactored and no longer cause failures during nightly runs.

- The changes did not cause regressions elsewhere; nightly test runs pass consistently and reliably with deterministic results.

**Comment by jsquire** [comment]
There were some `TaskCompletionSource` instances not being created with the expected set of options which I cleaned up in another workstream.   We may want to try re-enabling and running these in the engineering environment using a feature branch to see if that helped.

//cc: @kinelski

**Comment by jsquire** [comment]
The recent overhaul of the `EventProcessorClient` has resolved this; the tests mentioned in this issue have either been made deterministic or have been obviated by the use of `EventProcessor<T>` as a base class.
