### ISSUE TITLE
Ability to stop processing messages in QueueClient

### ISSUE THREAD

**Issue by ShaneCourtrille** [Azure/azure-sdk-for-net#10071]
**Library or service name.**
Microsoft.ServiceBus.Messaging
 
**Is your feature request related to a problem? Please describe.**
This is related to #1768.  We are using the QueueClient to process messages and I'm trying to come up with a graceful way to shutdown when our service is told to stop.  

To start with we're using OnMessage with MaxConcurrentCalls > 1.  When we get a message we run the processing of it inside a database transaction.  The problem I've ran into is that there doesn't seem to be any good way to stop processing that doesn't risk a database transaction commit AND the message being put back on the queue due to a failed message.complete.

Things I've tried so far..

1. Call client.Close();  - Won't work because the message can't be completed.
2. Set the Queue to ReceiveDisabled - won't work because the message can't be completed.
3. Considered passing the cancellationToken further into the process but this isn't a guarantee as your cancellationToken could be fine when you commit your db transaction but by the time the code gets back out (extremely short time I know but still) the client has been closed.

What would be really great is if I could in some way tell the client to stop processing new messages and close AFTER the current messages were completed.  

Or is there some other way of doing this that I (after many hours of Google searching) am unaware of?

**Comment by nemakam** [comment]
@ShaneCourtrille, this is equivalent of pausing the message pump, which is currently not possible. There's a new library being worked on right now for Service Bus, which will take care of this feature request.
Also, even without "closing" the pump, you can run into this scenario where you finish committing the message in your DB and the complete() fails. I would assume you'd have to take care of this anyway.

**Comment by NiklasArbin** [comment]
Would you accept a pull request for this?

- MessageHandlerOptions could add a non breaking property for suppling a cancellation token, which would default to .None

- The token would be passed into the MessageReceivePump and the receive loop would be cancelled if the token is cancelled.

**Comment by nemakam** [comment]
@NiklasArbin, feel free to raise a PR for this. 
Instead of a cancellation token, you could also consider exposing a new method called "PauseHandler" that can pause the pump when needed

**Comment by ShaneCourtrille** [comment]
Service Bus Track 2 Processors will be able to resolve our issue as per #10933 so I'm closing this.
