### ISSUE TITLE
Migrate internal-only guidance to our public guidance docs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#10072]
This link is mentioned in our Coding Guidelines in OneNote

_Originally posted by @AlexanderSher in https://github.com/Azure/azure-sdk-for-net/pull/10065_

**Comment by pallavit** [comment]
@heaths can this be closed?

**Comment by heaths** [comment]
There are already plans in place to do much of this anyway, and given I'm not even sure exactly which documentation I'm talking about (I think this was supposed to be more timely, but I should've been more specific), sure.
