### ISSUE TITLE
[QUESTION] Can Microsoft.Azure.EventHubs.ServiceFabricProcessor be safely use? 

### ISSUE THREAD

**Issue by darthkurak** [Azure/azure-sdk-for-net#10088]
**Query/Question**
I found out something like Microsoft.Azure.EventHubs.ServiceFabricProcessor. But it seems, that documentation around it has gone, and only nuget package and source code remains.
Can I safely use it?
Any documentation anywhere?

**Comment by jsquire** [comment]
//cc: @jamesbirdsall

**Comment by darthkurak** [comment]
Any update? :)

**Comment by JamesBirdsall** [comment]
ServiceFabricProcessor is still officially in preview, and there are some known issues and API changes we would like to make before it goes GA. That said, some customers are using it, and if someone using it hits a stopper, we will fix it with priority.
