### ISSUE TITLE
AdditionalUnattendContent missing from Models.ConfigurationSet

### ISSUE THREAD

**Issue by blumu** [Azure/azure-sdk-for-net#1009]
The model ConfigurationSet is missing property AdditionalUnattendContent used to configure OOBE. So it's not possible to use Management.Compute to create an Azure VM with AutoLogon or FirstLogonCommands. 
For reference see REST API doc at https://msdn.microsoft.com/en-us/library/azure/jj157186.aspx

**Comment by shahabhijeet** [comment]
@blumu if this is still an issue, can you open a new issue in order to track it.

**Comment by blumu** [comment]
This bug was filed before ARM went GA. I confirm that the `AdditionalUnattendContent` field is now exposed in the ARM SDK under `WindowsConfiguration`: 

https://github.com/Azure/azure-sdk-for-net/blob/4e2ab34f565507f4dcf2b6f0fa57407fb0fa5c61/src/SDKs/Compute/Management.Compute/Generated/Models/AdditionalUnattendContent.cs

https://github.com/Azure/azure-sdk-for-net/blob/4e2ab34f565507f4dcf2b6f0fa57407fb0fa5c61/src/SDKs/Compute/Management.Compute/Generated/Models/WindowsConfiguration.cs
