### ISSUE TITLE
Cached KeyVault Configuration Provider not failing when invalid credentials presented

### ISSUE THREAD

**Issue by bryanhunwardsen** [Azure/azure-sdk-for-net#10107]
using Microsoft.Extensions.Configuration
in conjunction with
ConfigurationBuilder().AddAzureKeyVault()
causes a security issue.

Steps to reproduce:
IConfiguration c1 =  ConfigurationBuilder().AddAzureKeyVault(ValidConnectionString, ValidClientID,ValidClientSecret).Build();
Console.WriteLine(c1[ValidSecretKey]); //Produces Expected Secret Value

//immediately followed by...

IConfiguration c2 =  ConfigurationBuilder().AddAzureKeyVault(ValidConnectionString, ValidClientID,**INVALIDClientSecret**).Build(); //This seems to be likely using a static/cached KeyVault IConfigurationProvider and is not producing expected ADAL exception for bad password 
Console.WriteLine(c2[ValidSecretKey]); //Invalid KV credentials now have access to Secrets it should not have access to. This presents as a security issue! This behavior is exhibited for anything running under the same process.

Expected Behavior:

- Once the initial IConfiguration leaves scope, it should be garbage collected completely with no reuse of any static or cached internal objects/data.
- Explicitly creating a second IConfiguration instance using any connection difference (target Vault or Authentication Credential part) should not re-use any static or cached portion of an existing bound configuration under different credentials.
- In both cases, when requesting ConfigurationBuilder().AddAzureKeyVault(ValidConnectionString, ValidClientID,**INVALIDClientSecret**).Build(); should produce an ADAL exception(bad password), just as if it was called first in the above sample.

Searching the documentation I do not see any published way to overcome this issue.

**Comment by jsquire** [comment]
@heaths:  Would you be so kind as to help route this to the best contact?

**Comment by AlexGhiondea** [comment]
@pakrym can you take a look?

**Comment by bryanhunwardsen** [comment]
We are experiencing this as a security issue, how far down in the queue is this?

**Comment by AlexGhiondea** [comment]
@bryanhunwardsen apologies for the delay. @pakrym can you please take a look at this first thing in the morning?

**Comment by AlexGhiondea** [comment]
@bryanhunwardsen I wanted to drop a quick note letting you know that we are still looking into this issue. Appreciate the patience!

**Comment by AlexGhiondea** [comment]
@bryanhunwardsen thank you for your patience. 

Depending on how your application is setup and its requirements, you might be able to clear the cache to avoid running into this problem. 
The cache is accessible [here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/af10dd15cdb082bc3dbe14b0c2c6d81f6ca5b541/src/Microsoft.IdentityModel.Clients.ActiveDirectory/TokenCache.cs#L105) and it has a `Clear` method.

Hopefully this helps.

**Comment by pakrym** [comment]
Closing, please reopen if you have more questions.
