### ISSUE TITLE
Readme fix

### ISSUE THREAD

**Issue by archelan** [Azure/azure-sdk-for-net#1010]
https://github.com/Azure/azure-sdk-for-net#visual-studio
Change "WindowsAzureCommonLibraries.sln" and "WindowsAzureManagementLibraries.sln" to "AzureCommonLibraries.sln" and "AzureManagementLibraries.sln"

**Comment by markcowl** [comment]
@archelan Thanks for pointing this out.  Can you submit a PR with this change?

**Comment by matt-gibbs** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-net/pull/1028
