### ISSUE TITLE
[BUG] EventHub Processor Host is not redistributing leases on partitions, leaving many leases, sometimes half, unprocessed for several days at a time or longer

### ISSUE THREAD

**Issue by ththiem** [Azure/azure-sdk-for-net#10108]
**Describe the bug**
Our nodes in production are not leasing out every partition, and leaving data unprocessed indefinitely. We have 8 instances running across 8 VM's managed by Service Fabric. Each of them are microservices running the latest version of the SDK (4.1.0) and for whatever reason they simply do not obtain leases on all available partitions. 

**Expected behavior**
All 32 partitions should be loadbalanced out to every processor such that no partition is left unprocessed for extended periods of time, or indefinitely.

**Actual behavior (include Exception or Stack Trace)**
Half the partitions are untouched. There's no error or log, the ProcessortHost simply never attempts to obtain leases for half the partitions.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Unknown, the behavior is erratic and only in production. Spinning a single EventProcessorHost on my local machine it can acquire the leases to all 16 of the other partitions that are being ignored and nothing attempts to take the lease from them, and disconnecting the client from all 16 leaves them there without any of the other processors attempting to read them.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.EventHubs.Processor 4.1.0
 - Hosting platform or OS and .NET runtime version (.Net Core 3.0 services running on Windows Service Fabric Clusters]

We're at a loss of how to even troubleshoot this since this is supposed to be automatic behavior of the SDK/EventHub itself but that has not been the case.

**Comment by ththiem** [comment]
We're simply instantiating the hosts like the samples demonstrate:
`try
            {
                var eventHubClient = EventHubClient.CreateFromConnectionString(eventHubConnectionString);

                eventProcessorHost = new EventProcessorHost(
                                                            eventHubName,
                                                            consumerGroupName,
                                                            eventHubConnectionString,
                                                            storageAccountConnectionString,
                                                            leaseContainerNameString)
                {
                    PartitionManagerOptions = new PartitionManagerOptions
                    {
                        RenewInterval = TimeSpan.FromSeconds(10), // Default is 10 seconds
                        LeaseDuration = TimeSpan.FromSeconds(30) // Default value is 30 seconds
                    }
                };
                var eventProcessorOptions = new EventProcessorOptions
                {
                    InvokeProcessorAfterReceiveTimeout = true,
                    MaxBatchSize = 100,
                    PrefetchCount = 200,
                };

				await eventProcessorHost.RegisterEventProcessorFactoryAsync(new EventProcessorFactory<MyEventProcessor>("testString"), eventProcessorOptions);
			}`

**Comment by serkantkaraca** [comment]
Can you use Azure Storage Explorer and check lease states?

**Comment by ththiem** [comment]
> 
> 
> Can you use Azure Storage Explorer and check lease states?

They're available

**Comment by serkantkaraca** [comment]
Can you check partition count of the eventhub on the portal?

**Comment by ththiem** [comment]
> 
> 
> Can you check partition count of the eventhub on the Azure Portal?

It's 32, like I described above.
![image](https://user-images.githubusercontent.com/15839533/75082957-05c34900-54cb-11ea-916a-193de21bd2df.png)

**Comment by ththiem** [comment]
It is not taking leases on the first X number of partitions, it's picking at random. 
![image](https://user-images.githubusercontent.com/15839533/75083046-808c6400-54cb-11ea-91bf-b2a256cc4b27.png)

**Comment by serkantkaraca** [comment]
Do you have active traffic on the entity?

**Comment by serkantkaraca** [comment]
And what is your entity name?

**Comment by ththiem** [comment]
> 
> 
> Do you have active traffic on the entity?

Yes, a lot of traffic. I can see entries being enqueued in the partitions through Service Bus Explorer. The partitions have significant incoming bytes per second and 0 outgoing, and the Last Enqueued Time is long after the last modified on the leases.
![image](https://user-images.githubusercontent.com/15839533/75083255-af570a00-54cc-11ea-91c4-4c2879cdd5da.png)

> 
> 
> And what is your entity name?

Which name exactly are you referring to?

**Comment by serkantkaraca** [comment]
eventHubName

**Comment by ththiem** [comment]
> 
> 
> eventHubName

rt01eventhubnamespace/rt01voice

**Comment by serkantkaraca** [comment]
Can you collect client traces on one of the VMs with PerfView for couple minutes?

Instructions on PerfView tool - https://github.com/jonwagner/EventSourceProxy/wiki/Using-PerfView-for-ETW-Tracing

Please collect provider "Microsoft-Azure-EventHubs-Processor"

**Comment by ththiem** [comment]
I'll see if I have access to the VM's directly, I'll have to get back to you on that a bit later.

**Comment by ththiem** [comment]
@serkantkaraca Apologies for the delay, had to get back on this once I was in the office again.

So I was able to log into one of the node VMs are poked around in there. Unfortunately PerfView did not work, it just kept saying "Error: Could not find provider name 'Microsoft-Azure-EventHubs-Processor'."

Either way, accessing the VM directly did give me another idea to try, as I saw that despite the eventhub processor services being up and running on the VM and showing as active and healthy in both task manager and the Service Fabric Explorer UI, they were consistently at 0% CPU and they were doing nothing. Upon restarting the node I was on via the Service Fabric Explorer, the eventhub processors both starting running again and acquired leases to the other 16 missing partitions that hadn't been processed since last week (the checkpoints in blob storage were days behind at this point).

I don't really understand what happened or why/how the services were in such a state that they were doing absolutely nothing but were still holding onto leases for those missing partitions? It doesn't make any sense to me how eventhub can get into such a state that it allows a service to pretend to acquire leases but never actually lease anything and not allow other active processors to acquire leases on those partitions either. 

The only clue I have that could have perhaps lead to this scenario were issues with the actual checkpointing calls to blob storage, where I saw lots of difference connectivity issues more than a week ago (on the 15th/16th) but then no logs since. Either way, I would never have expected an entire VM set to get into such a state as to drop partitions entirely, even if some event processor hosts apparently weren't running/behaving properly, and not leasing either.

I will continue to monitor the clusters and make some slight adjustments/improvement in our logging to see if we missed something, but upon restarting all 8 nodes on the cluster I see all 32 partitions are now being read from.

**Comment by serkantkaraca** [comment]
I have a theory however need to check couple things first. I will update you ASAP.

**Comment by serkantkaraca** [comment]
When did you restart idle VMs in UTC?

**Comment by ththiem** [comment]
> 
> 
> When did you restart idle VMs in UTC?

At  **2020-02-24T22:11:33.433Z**

**Comment by serkantkaraca** [comment]
OK, I can confirm consumers recovered at the same time you pointed. Basically new receivers connected when you restarted the hosts. 

Are you able to view per VM consumer data from the incident time window? Is it like some VMs completely stop receiving?

**Comment by ththiem** [comment]
I couldn't say. There was no indication that I could find that the services were stopped, as far as I could tell they were registered and actively running in task manager and service fabric was reporting they were healthy and running. But they were not doing anything that I could tell, neither receiving events nor actively processing, leasing, checkpointing, anything. 

When I restarted a single node of the cluster (of 8 VMs) it kickstarted the host and acquired all 16 missing leases on the same host, which my understanding is that given 8 VMs the leases should be evenly distributed to each VM, each one only receiving 4. Cross-checking this with our app insights logs I could see that 7 of the 8 VMs had simply "stopped" logging and were no longer processing from eventhub, but there's no log of any service failure or host failure or anything going down. The nodes didn't stop at the same time either, they stopped responding/receiving at these times:

2/15/2020 5:15:07PM node 4
2/15/2020 8:07:39PM node 5
2/16/2020 3:24:50AM node 3
2/16/2020 5:36:16AM node 7
2/16/2020 3:44:47PM node 1
2/17/2020 1:36:01AM node 0
2/18/2020 7:13:13PM node 2

And then stayed that way until I restarted them.

**Comment by ththiem** [comment]
I found that our other cluster is in the same state, rt02. Only 1 of the 8 nodes is running.

**Comment by serkantkaraca** [comment]
I think you are hitting a known issue and fix is already merged - https://github.com/Azure/azure-sdk-for-net/pull/10019

**Comment by ththiem** [comment]
We confirmed with @serkantkaraca that the issue is indeed a deadlock in azure storage on attempting to read the lease files from storage, as noted in the know issue & fix linked above. I will go ahead and close this issue now that we are aware of it and will await the fix to be released through a new version of the library.
