### ISSUE TITLE
BeginCreatingDeploymentAsync fails with default setting of ProvisionGuestAgent

### ISSUE THREAD

**Issue by StanislawSwierc** [Azure/azure-sdk-for-net#1011]
I run into some issues with the BeginCreatingDeploymentAsync when I tried to create deployment using default setting for the ProvisionGuestAgent which is false. The following configuration fails with the error "*BadRequest: In order to use extension reference, ProvisionGuestAgent must be set during virtual machine provisioning.*"

    var deployment = new VirtualMachineCreateDeploymentParameters
    {
        DeploymentSlot = deploymentSlot,
        Label = label,
        Name = name,
        Roles = new List<Role>()
        {
            new Role
            {
                ConfigurationSets = configurationSets,
                Label = roleLabel,
                OSVirtualHardDisk = new OSVirtualHardDisk
                {
                    Name = hardDiskName,
                    MediaLink = hardDiskUri,
                    OperatingSystem = "Windows",
                    SourceImageName = imageName,
                },
                RoleName = roleName,
                RoleSize = roleSize,
                RoleType = "PersistentVMRole",
            }
        },
    };

I discovered that it is due to the `ResourceExtensionReferences` being initialized to an empty list. Because the property is not null the request will include an empty Xml element for `<ResourceExtensionReferences/>` which is enough to mark the request as invalid.

The workaround is to set `ResourceExtensionReferences` to null when you set `ProvisionGuestAgent` to false. It is not intuitive.

    var deployment = new VirtualMachineCreateDeploymentParameters
    {
        DeploymentSlot = deploymentSlot,
        Label = label,
        Name = name,
        Roles = new List<Role>()
        {
            new Role
            {
                ConfigurationSets = configurationSets,
                Label = roleLabel,
                OSVirtualHardDisk = new OSVirtualHardDisk
                {
                    Name = hardDiskName,
                    MediaLink = hardDiskUri,
                    OperatingSystem = "Windows",
                    SourceImageName = imageName,
                },
                RoleName = roleName,
                RoleSize = roleSize,
                RoleType = "PersistentVMRole",

                // Workaround starts here
                ProvisionGuestAgent = false,
                ResourceExtensionReferences = null,
            }
        },
    };

Please update the request serialization code and make it skip `<ResourceExtensionReferences/>` element if the collection is null or empty.

**Comment by markcowl** [comment]
Thanks for the feedback.  Routing this issue to the appropriate team.

**Comment by markcowl** [comment]
testing.

**Comment by markcowl** [comment]
testing

**Comment by singhkay** [comment]
From our dev @huangpf 
By design, the field 'ResourceExtensionReferences' is designed to be 'LazyInitialized', which means, if this code is not referred or 'touched' anywhere (like in Debug mode), it would be null.

If it's accessed somewhere, it would be empty list, for example, the following line will make it an empty list:

Console.WriteLine(role.ResourceExtensionReferences);
