### ISSUE TITLE
Where did CloudConfigurationManager go?

### ISSUE THREAD

**Issue by collinstevens** [Azure/azure-sdk-for-net#10126]
**Query/Question**
The [Microsoft.Azure.ConfigurationManager NuGet package's](https://www.nuget.org/packages/Microsoft.Azure.ConfigurationManager/) source repository links back to this repository, but the classes within it are not located in this repository.

I'm specifically looking for `Microsoft.Azure.CloudConfigurationManager` which used to exist in this repository as of [v2.1.0.4](https://github.com/Azure/azure-sdk-for-net/blob/v2.1.0.4/libraries/src/Configuration/CloudConfigurationManager.cs).

**Comment by jsquire** [comment]
Hi Collin,

We're sorry that you're having difficulties and appreciate you reaching out to let us know.  I can't claim to be familiar with the `Microsoft.Azure.ConfigurationManager` package, but from its description, it sounds like [Azure.Data.AppConfiguration](https://www.nuget.org/packages/Azure.Data.AppConfiguration/) _([source](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/appconfiguration/Azure.Data.AppConfiguration))_ may be a replacement for it.

@AlexGhiondea may have more insight to offer.

**Comment by collinstevens** [comment]
@jsquire I don't think this is the same thing from looking at the source. The **Azure.Data.AppConfiguration** package doesn't seem to support configuration from a `Web.config` or an `appsettings.json`. The `Microsoft.Azure.ConfigurationManager` package says it is a replacement for the previous package `Microsoft.WindowsAzure.ConfigurationManager`.

**Comment by AlexGhiondea** [comment]
@maggiepint can you help route this question?

**Comment by JohnFF** [comment]
Microsoft.Azure.ConfigurationManager did not work for me but System.ConfigurationManager does: recommended.

**Comment by kentahikaru** [comment]
I am also curious where is the source code for Microsoft.Azure.ConfigurationManager.
Any updates on that ?

**Comment by AlexGhiondea** [comment]
@weshaggard any idea how we can find this?

**Comment by weshaggard** [comment]
Looking through https://github.com/Azure/azure-sdk-for-net/issues/6677 it doesn't look like the source was ever in the main branch but instead it was in another branch https://github.com/Azure/azure-sdk-for-net/tree/AzureConfigMgr. However that branch looks to have been removed at some point as well but I was lucky enough to find it in a fork https://github.com/erich-wang/azure-sdk-for-net/tree/AzureConfigMgr if the code is interesting enough we could bring it back into the main repo from there.

**Comment by AlexGhiondea** [comment]
@weshaggard I wonder if we do need to bring it over since we have shipped a library based on that code...  @erich-wang thoughts?

**Comment by AlexGhiondea** [comment]
@ArthurMa1978 is looking into moving the code back to this repo (in a branch).

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/azure-sdk-for-net/tree/AzureConfigMgr the code is back

**Comment by weshaggard** [comment]
@ArthurMa1978 if this needs to remain around then it is probably worth adding a release tag for it in case we end up cleaning up these older branches.
