### ISSUE TITLE
Is QueueClient.CreateAsync supposed to throw if the queue already exists?

### ISSUE THREAD

**Issue by collinstevens** [Azure/azure-sdk-for-net#10125]
**Query/Question**
Is QueueClient.CreateAsync supposed to throw if the queue already exists?

The [sample](https://github.com/Azure/azure-sdk-for-net/blob/6125c01902f61a21ea0e843931df038efe52d393/sdk/storage/Azure.Storage.Queues/samples/Sample01b_HelloWorldAsync.cs#L196-L209) shows it catching an exception contained an error code  aptly named `QueueErrorCode.QueueAlreadyExists`. Yet, when running locally, an exception isn't thrown.

On the first call, the queue is created and the response is a 201. On the second call, it's idempotent and returns a 204. 

I don't want to introduce extra handling for this if it isn't necessary, but I also don't want this to break without taking a major version update.

**Environment:**
Azure.Storage.Queues12.2.0

.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
//cc: @tg-msft

**Comment by wantedfast** [comment]
QueueClient.CreateAsync() calls the [Create Queue](https://docs.microsoft.com/en-us/rest/api/storageservices/create-queue4). 


Hi @collinstevens ,

Please find clarification in [remarks section](https://docs.microsoft.com/en-us/rest/api/storageservices/create-queue4#remarks).  

When a queue with the specified name already exists, the Queue service checks the metadata associated with the existing queue. If the existing metadata is identical to the metadata specified on the Create Queue request, status code 204 (No Content) is returned. If the existing metadata does not match the metadata provided with the Create Queue request, the operation fails and status code 409 (Conflict) is returned. Clients can take advantage of this behavior to avoid an additional call to check whether a named queue already exists. 

 

You have called create twice with same information. Hence it is normal that you got a 204 without errors in the second time.  

@jongio

**Comment by collinstevens** [comment]
@wantedfast thank you, this clears it up. I was only looking at the API client documentation, not the REST API itself.
