### ISSUE TITLE
[BUG] Clean up NuGet Packages and de-list some publically

### ISSUE THREAD

**Issue by timheuer** [Azure/azure-sdk-for-net#10142]
**Describe the bug**
When searching for 'storage' in NuGet, I'm getting multiple packages and the titles aren't enough to tell me what one is correct.  

**Expected behavior**
There should be a clear winner of what Azure SDK package to use for Storage.  Today there is not.  For ones that are not being updated anymore, delist them (not remove, but delist) so that customers aren't guided toward old ones.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
![image](https://user-images.githubusercontent.com/4821/75270058-c50b4e80-57ae-11ea-9fb1-bdd770e56523.png)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Open NuGet Package Manager
2. Search 'storage'

**Comment by jsquire** [comment]
@AlexGhiondea:  Not quite sure what the appropriate triage path/routing for this would be.   Would you be so kind as to assist?

**Comment by tg-msft** [comment]
Alex owns this and has been doing as much as possible without additional changes from NuGet (i.e., if you click any of those old packages like [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage) you'll see a blurb like:

> Development on this library has shifted focus to the Azure Unified SDK. You can find more information here. These packages can be found below:
> 
> Azure.Storage.Blobs
> Azure.Storage.Queues
> Azure.Storage.Blobs.Batch
> Azure.Storage.Files.Shares
> **It is recommended that you move to the new package.**

**Comment by jongio** [comment]
@AlexGhiondea This was brought up on twitter: https://twitter.com/devlead/status/1313121287200481285

Looking at this screen shot
1. The first message is an old deprecated message, which can be confusing.  It's not until you look below that do you see the latest guidance.

![image](https://user-images.githubusercontent.com/2163001/95100445-f0abcb00-06e5-11eb-939b-60e49599661c.png)

It would be great to get the messaging cleaned up.  Is there a way to manually override what is in the Nuget page? So we don't have to release a package.

**Comment by jasonshave** [comment]
I have the same ask. @jsquire and @AlexGhiondea was there ever resolution to this?

**Comment by lfraleigh** [comment]
It looks to me like the changes were already made.  What else is needed?

![image](https://user-images.githubusercontent.com/76703586/180024078-9635498c-28e2-4a40-9eb1-82b4ece9a590.png)

**Comment by scottaddie** [comment]
@timheuer It appears as though the search popularity has already been transferred to our "Track 2" Azure.Storage.Blobs package. Additionally, some recent UI changes in the NuGet Package Manager experience make it more obvious which package to use. For example:

![image](https://user-images.githubusercontent.com/10702007/180348354-6a69be03-8352-40dd-9fe3-43cfe499dbe4.png)

Is this issue safe to close now?

**Comment by timheuer** [comment]
Lgtm

-th
________________________________
