### ISSUE TITLE
ManagementClient - Check if a rule exists on subscription 

### ISSUE THREAD

**Issue by tpar** [Azure/azure-sdk-for-net#10149]
# Description

In service bus SDK, it would be nice to have a method, that would check if a named rule exists on the a service bus topic. There are rules which include `GetRuleAsync`, `UpdateRuleAsync` and `UpdateRuleAsync`. 

## Actual Behavior
1. To programmatically create/update/delete a subscription rule the relevant SDK methods are to be used. However, if the rule does not exist, the SDK raises `MessagingEntityNotFoundException`. 

To check if a rule exists, a check as below needs to be done by an developer. 

```
private static async Task<bool> RuleExistsAsync(
            ManagementClient managementClient, 
            string topicPath, 
            string subscriptionName, 
            string ruleName)
        {
            // There is no method in the SDK to check if a particular rule exists.
            try
            {
                if (await managementClient.GetRuleAsync
                    (topicPath, subscriptionName, ruleName) != null)
                {
                    return false;
                }
            }
            catch (MessagingEntityNotFoundException){}

            return true;
        }
```

## Proposed Behavior
1. Expose a method in the `ManagementClient` named `RuleExistsAsync`, similar to `TopicExistsAsync` or `SubscriptionExistsAsync`.

**Comment by nemakam** [comment]
@tpar, thanks for the suggestion. If this was implemented on the client, it would look exactly like the code you mentioned. For now, please continue using it that way.
We have a new library in pipeline for Azure Service Bus, and we will evaluate this for the new library/. FYI @jsquire  @JoshLove-msft

**Comment by ramya-rao-a** [comment]
@tpar In the new Azure.Messaging.ServiceBus package, you can use the [ServiceBusAdministrationClient.RuleExists](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient.ruleexistsasync?view=azure-dotnet) method for this purpose.
