### ISSUE TITLE
Add message batch

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#10153]
Java is using a MessageBatch which adds the ability to see what message overflows the batch when trying to send messages.
We should do the same for .NET.
See EH EventDataBatch.

**Comment by SeanFeldman** [comment]
EventHubs [`EventDataBatch`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventDataBatch.cs).

This would provide the [safe batching feature](https://github.com/Azure/azure-sdk-for-net/issues/8440) asked for in Track 1.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/10305

**Comment by kdr213** [comment]
@ShivangiReja  it seems this missed release 4.1.3. When is the next release scheduled for Service Bus sdk? Is there a preview version we can use?

**Comment by JoshLove-msft** [comment]
This work item was for the new Track 2 library - https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.0.0-preview.3
