### ISSUE TITLE
Add Identifier property mirroring EH

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#10158]
Add an Identifier property to clients that is a GUID. See how it is generated in EH.
Update ExceptionReceivedEventArgs ctor param to be called identifier, rather than clientId.

**Comment by SeanFeldman** [comment]
> See how it is generated in EH.

Link?

**Comment by JoshLove-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L428
