### ISSUE TITLE
Update methods that return IEnumerable to instead return IReadOnlyList

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#10155]
Receive/ReceiveDeferred/Peek/Complete methods
Send is different as that should use a MessageBatch and is being tracked in a separate issue.

**Comment by SeanFeldman** [comment]
Can I suggest to cross-reference issues when mentioning another work item? 
In this case, MessageBatch is https://github.com/Azure/azure-sdk-for-net/issues/10155

**Comment by JoshLove-msft** [comment]
One potential issue with using IReadOnlyList is that we couldn't take the return as input to a different method that is expecting an IList. For instance, if you want to complete all the messages that you received, and the Complete method took an IList, this wouldn't work. For this reason, it may be better to just use IList or ICollection.

**Comment by SeanFeldman** [comment]
Would [`ImmutableList<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablelist-1?view=netcore-3.1) help?

**Comment by JoshLove-msft** [comment]
@SeanFeldman thanks for that idea. Since customers might end up wanting to remove messages from the received message list, we figured it was better to just stick with IList.

> Would [`ImmutableList<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutablelist-1?view=netcore-3.1) help?

**Comment by JoshLove-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/10235
