### ISSUE TITLE
[QUERY] Azure Storage Tables

### ISSUE THREAD

**Issue by dansiegel** [Azure/azure-sdk-for-net#10176]
**Query/Question**

If I'm using the Tables in Azure Storage what's currently the correct SDK package for connecting and working with those tables so that we can read/write?

**Environment:**
 - Name and version of the Library package used: that's the question
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .net core 3.1 / xamarin
 - IDE and version : n/a

**Comment by jsquire** [comment]
//cc: @pakrym, @AlexGhiondea

**Comment by wantedfast** [comment]
Hi @dansiegel ,

https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-develop-table-dotnet 



 



Code snippet for inserting. 
```
try 
{ 
    // Create the InsertOrReplace table operation 
    TableOperation insertOrMergeOperation = TableOperation.InsertOrMerge(<CustomerEntity>); 
    // Execute the operation. 
    TableResult result = await table.ExecuteAsync(insertOrMergeOperation); 
    CustomerEntity insertedCustomer = result.Result as CustomerEntity; 
 // Get the request units consumed by the current operation. RequestCharge of a TableResult is only applied to Azure Cosmos DB 

    if (result.RequestCharge.HasValue) 
    { 
        Console.WriteLine("Request Charge of InsertOrMerge Operation: " + result.RequestCharge); 
    } 
    return insertedCustomer; 
} 
catch (StorageException e) 
{ 
    Console.WriteLine(e.Message); 
    Console.ReadLine(); 
    throw; 
} 
```

Code snippet for Retrieving.  
```
try 
{ 
    TableOperation retrieveOperation = TableOperation.Retrieve<CustomerEntity>(<partitionKey>, <rowKey>); 
    TableResult result = await table.ExecuteAsync(retrieveOperation); 
    CustomerEntity customer = result.Result as CustomerEntity; 

    if (customer != null) 
    { 
        //handle entity code. 
    } 

    // Get the request units consumed by the current operation. RequestCharge of a TableResult is only applied to Azure CosmoS DB  

    if (result.RequestCharge.HasValue) 
    { 
        Console.WriteLine("Request Charge of Retrieve Operation: " + result.RequestCharge); 
    } 

    return customer; 
} 
catch (StorageException e) 
{ 
    Console.WriteLine(e.Message); 
    Console.ReadLine(); 
    throw; 
} 
```

Please let me know if further help is needed.

@jongio

**Comment by wantedfast** [comment]
Hi @dansiegel 
How is this issue going? Feel free to let us know if further help is needed.

**Comment by loic-sharma** [comment]
Will there be an `Azure.Storage.Tables` package, similar to `Azure.Storage.Blobs` and `Azure.Storage.Queues`

**Comment by mayurid** [comment]
We are working on a new Tables offering which will align to the same guidelines and principles that the mentioned Blobs library. The work is in progress and we can provide a more concrete timeline in a few weeks.

**Comment by kieronlanning** [comment]
@mayurid Is there a timeline on the new package? Thanks!

**Comment by kieronlanning** [comment]
@mayurid Hey, is there a timeline for this work?

**Comment by joelverhagen** [comment]
I have found that Azure.Data.Tables is pre-release on NuGet.org: https://www.nuget.org/packages/Azure.Data.Tables/. I haven't tried moving my code to it yet but it looks promising from the README 😄.

**Comment by pakrym** [comment]
cc @christothes
