### ISSUE TITLE
[Storage][Blobs] Investigate making the default initial blob download size smaller.

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#10208]
https://github.com/Azure/azure-sdk-for-net/pull/10099

Downloads of > 256 MB are split into an initial download of 256 MB, followed by downloads of 4 MB.  Investigate the pref implications of lowing this initial download threshold.

**Comment by JimSuplizio** [comment]
Hi @seanmcc-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
