### ISSUE TITLE
[Azure.Core Shared] ContentTypeUtilities recognizing other JSON variants

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#10216]
We should make the [ContentTypeUtilities](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/ContentTypeUtilities.cs) a little more robust to recognize other JSON variants like:

>        "Content-Type": "application/json; odata.metadata=minimal; odata.streaming=true",

**Comment by pakrym** [comment]
Done
