### ISSUE TITLE
[FEATURE REQ] Service Bus managed identity authentication in the development environment

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#10219]
Authenticate the user in the development environment

**Library or service name.**

Microsoft.Azure.ServiceBus
 
**Is your feature request related to a problem? Please describe.**

When developing with Azure Service Bus and using Managed Identity, it is not possible to run and test the test without some workarounds. Adding support for local development via providing AAD information with the environment variables. Ideally, similar to what the rest of the [Azure SDK is doing](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi#authenticate-the-user-in-the-development-environment).

**Comment by jsquire** [comment]
//cc: @nemakam, @serkantkaraca

**Comment by nemakam** [comment]
@serkantkaraca , Could you provide your insights into this?

**Comment by serkantkaraca** [comment]
What is the issue here? Local development workarounds should just work fine with current API.

**Comment by SeanFeldman** [comment]
@serkantkaraca, so using these environment variables would work? https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi#authenticate-the-user-in-the-development-environment

**Comment by serkantkaraca** [comment]
Should work as they claim since it is the identity client reading the env-variables. Have you tried that?

> The Azure Identity client library reads values from three environment variables at runtime to authenticate the service principal. The following table describes the value to set for each environment variable.

**Comment by SeanFeldman** [comment]
Yes, I've tried it using the following:

1. Under `App Registrations` created an app with a secret.
1. Under the namespace's IAM assigned `Azure Service Bus Data Owner` to the App
1. Filled out environment variables as per [documentation](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi#authenticate-the-user-in-the-development-environment)
1. Used Managed Identity connection string (`"Endpoint=sb://<namespace>.servicebus.windows.net/;Authentication=Managed Identity"`)

And this results in an exception:
```
Microsoft.Azure.ServiceBus.UnauthorizedException: Authorization failed for specified action: Manage,EntityWrite. TrackingId:7f251310-7053-4961-8fc5-a7f91f32eb00_G48, SystemTracker:spike-mi6.servicebus.windows.net:bundle-1, Timestamp:2020-02-29T05:48:39
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.SendHttpRequest(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.PutEntity(String path, String requestBody, Boolean isUpdate, String forwardTo, String fwdDeadLetterTo, CancellationToken cancellationToken)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.CreateTopicAsync(TopicDescription topicDescription, CancellationToken cancellationToken)
```

**Comment by serkantkaraca** [comment]
I think MSI library it is falling back to user account instead of environment variables set identity. Can you try acquiring a token with below code and parse it on jwt.io?

`            AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider();
            string accessToken = azureServiceTokenProvider.GetAccessTokenAsync("https://servicebus.azure.net/").GetAwaiter().GetResult();
            Console.WriteLine(accessToken);`

**Comment by SeanFeldman** [comment]
The access token is parsed successfully. 
@serkantkaraca perhaps I should share the parsed results privately? I can send you the access token or parsed info if you ping me at feldman dot sean at gmail.

**Comment by serkantkaraca** [comment]
Actually, you don't need to share it. Access token tells what secure identity it belongs to via 'oid' in the payload section. You can also check if user name or email is in the payload. If so, then it is obviously a user access token.

**Comment by SeanFeldman** [comment]
The username/payload is not in the payload.
`tid` (tenant ID) is the right value.
`oid` is a GUID. Can you suggest where to look for that GUID?

**Comment by serkantkaraca** [comment]
Compare Oid to "Object Id" on the AAD App page. If both same then there might be an issue with the role assignment.

**Comment by SeanFeldman** [comment]
@serkantkaraca the "oid" from the token and the one on the AAD App page do not match.

**Comment by serkantkaraca** [comment]
Run Get-AzureRmRoleAssignment for the oid in the token. See if you can see the assignment in the cmdlet result.

https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/get-azurermroleassignment?view=azurermps-6.13.0

**Comment by SeanFeldman** [comment]
Running with the `oid` from the token returns nothing.

**Comment by serkantkaraca** [comment]
Get-AzureRmRoleAssignment is subscription aware. Did you select the correct subscription first?

**Comment by SeanFeldman** [comment]
Yes. I've used `(Get-AzureRmContext).Subscription` to verify that.
Also, if I run `Get-AzureRmRoleAssignment`, I can see all the role assignments. Including my App, but its `ObjectId` GUID is not matching the one from the access token `oid`.

**Comment by SeanFeldman** [comment]
When inspecting the token generated on a VM that has MSI enabled, `oid` is indeed matching VM's application ObjectID.

**Comment by serkantkaraca** [comment]
I think I pointed the wrong "object id". On IAM blade, click on the app name. It will open app properties page and you will see correct object id there as below.

![image](https://user-images.githubusercontent.com/16924470/75750617-77747180-5cd9-11ea-9f88-64a3ef430b37.png)

**Comment by SeanFeldman** [comment]
Yeah, I've checked that as well. From SB namespace --> Access Control (IAM) --> Role Assignments (tab) --> selected my app with "Azure Service Bus Data Owner" role --> the ObjectID it has is not matching the `oid` from the token when running locally.

**Comment by SeanFeldman** [comment]
![image](https://user-images.githubusercontent.com/1309622/75752243-8e20c580-5ce5-11ea-89c2-8725f73d0b59.png)

The value is missing from the token `oid`.

**Comment by serkantkaraca** [comment]
Seems we were on wrong SDK doc. Just realized this is the correct one - https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#running-the-application-using-a-service-principal
![image](https://user-images.githubusercontent.com/16924470/75806787-2d22dd00-5d39-11ea-81d8-8a6163fe0399.png)

**Comment by SeanFeldman** [comment]
@serkantkaraca that's it! Let me try and make sense out of this.

- There's `Azure.Identity` client library that uses the 3 [environment variables](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-msi#set-environment-variables) (`AZURE_CLIENT_ID`, `AZURE_TENANT_ID`, and `AZURE_CLIENT_SECRET`) that is used by the Azure SDK new client versions.
- And there's a `Microsoft.Azure.Services.AppAuthentication` that is using a single environment variable `AzureServicesAuthConnectionString`. This package is used by the current Service Bus client.
- The documentation for `AzureServicesAuthConnectionString` is under KeyVault though (don't recall seeing it under Service Bus).

Then

1. Why the two methods of authentication?
1. How to identify what authentication client library to use with what version of a service SDK?

**Comment by serkantkaraca** [comment]
Azure.Identity is the most recent auth library and it covers the MSI API as well. Track-1 should also move to Azure.Identity however current implementation is on Microsoft.Azure.Services.AppAuthentication. 

You can look at the dependency section on Nuget package page to tell which library is being used. https://www.nuget.org/packages/Microsoft.Azure.ServiceBus

**Comment by SeanFeldman** [comment]
Thank you so much for your help.

- `Azure.Identity` supersedes `Microsoft.Azure.Services.AppAuthentication` ✔
- Track-1 SDKs will move to use `Azure.Identity` ✔️ 
- Identification if via dependencies ✔

The only question I have is about documentation. It seems to be very random and spread unevenly among various services. Is there a source that would cover this in detail and be cross-service/SDK?

**Comment by serkantkaraca** [comment]
For the time being, we don't have any doc on improving debugging experience. I will take a note for this to follow up with doc team.

**Comment by SeanFeldman** [comment]
Thank you, @serkantkaraca.
I'll close this issue as you've helped to resolve it.
Looking forward to seeing a better documentation 🙂
