### ISSUE TITLE
[FEATURE REQ] Azure.Identity - Support KnownAuthorities like Python SDK

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#10228]
Azure.Identity

It would be great if we provided a "KnownAuthorities" concept, like we have in the Python SDK.
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/azure/identity/_constants.py

Right now, in .NET, devs have to provide the url for the environment they are targetting `https://login.microsoftonline.us` for Gov, for example.

With Python
```python
credential = DefaultAzureCredential(authority=KnownAuthorities.AZURE_GOVERNMENT)
```

With .NET
```csharp
var options = new DefaultAzureCredentialOptions { AuthorityHost = new Uri("https://login.microsoftonline.us/") };
var client = new KeyClient(new Uri(keyVaultUrl), new DefaultAzureCredential(options));
```

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by jongio** [comment]
Thank you @schaabs
