### ISSUE TITLE
Add document for MSI with Key Vault and update README

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#10221]
The quick start should be simple, so we may want to keep using the env vars for service principals in the README. However, we should bluntly call out that it's not recommended and point people to how to use MSI with Key Vault. We may be able to point them here for general concepts: https://docs.microsoft.com/azure/active-directory/managed-identities-azure-resources/overview#how-does-the-managed-identities-for-azure-resources-work

**Comment by heaths** [comment]
@schaabs we had talked offline about you (or someone) writing general MSI guidance perhaps for the Identity package I could link to. Is that scheduled for any particular milestone?

**Comment by schaabs** [comment]
It's scheduled for the May milestone as well. For authentication the the Key Vault README should mainly reference using the `DefaultAzureCredential`. As far as documenting managed identity any Key Vault docs should focus on setting up permissions, since this is specific to Key Vault.

**Comment by heaths** [comment]
@adrianhall @jongio might this also make a good blog post idea - using Managed Identity and `DefaultAzureCredential` whenever possible for ease and security? I'd still update the Key Vault docs across languages, but might be good to emphasize in our blog as well.

**Comment by heaths** [comment]
Given this has been punted along for a while, moving to backlog as a lower priority.

**Comment by pallavit** [comment]
> @schaabs we had talked offline about you (or someone) writing general MSI guidance perhaps for the Identity package I could link to. Is that scheduled for any particular milestone?

Is this link available so we could refer it into the KV readme?

**Comment by pallavit** [comment]
@heaths I see us using DefaultAzureCredential in the KV readme's which I think is consistent across all SDKs. Is this an older bug where we perhaps used MSI?

**Comment by heaths** [comment]
DAC is used to authenticate clients or services, yes. I'm not suggesting we change that. The documentation is how to set up managed identity across services to Key VAult. It's what lets DAC work efficiently in prod (using MSI credentials) or dev.

**Comment by pallavit** [comment]
@heaths do you still see value in adding documentation here? I have not seen any customer feedback here but marking this as MQ so we get a chance to address this. Feel free to close the issue if you feel otherwise.

**Comment by heaths** [comment]
I did update the READMEs a while back to [add](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/README.md#:~:text=Additionally%2C%20we%20recommend%20using%20a%20managed%20identity%20for%20authentication%20in%20production%20environments.):

> Additionally, we recommend using a managed identity for authentication in production environments.

I think this is probably good enough for now. Plenty of documentation on how to enable that.
