### ISSUE TITLE
We need a sample that shows usage of MaximumTransferLength and MaximumConcurrency 

### ISSUE THREAD

**Issue by amishra-dev** [Azure/azure-sdk-for-net#10224]
We are getting asks to set the block size and a sample will help reduce the friction customers face for looking up a sample

**Comment by JimSuplizio** [comment]
Hi @amishra-dev, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
