### ISSUE TITLE
[Question] Service Fabric Processor

### ISSUE THREAD

**Issue by MarkoatPriva** [Azure/azure-sdk-for-net#10231]
Hi,

The Service Fabric Processor is still in preview, will there be a final release this year?

Marko

**Comment by jsquire** [comment]
//cc: @JamesBirdsall

**Comment by samuelkoppes** [comment]
We are investigating this issue, and will report back with a status by 11/4/2020.

**Comment by kasun04** [comment]
The Microsoft.Azure.EventHubs.ServiceFabricProcessor package is in preview and there are no plans for a stable release. This package will soon be deprecated and therefore we won't be taking any changes.
