### ISSUE TITLE
Service Bus: Expose DispositionStatus on the Message class

### ISSUE THREAD

**Issue by GrimGadget** [Azure/azure-sdk-for-net#10241]
Service Bus: Microsoft.Azure.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
In the older BrokeredMessage version of the Service Bus SDK, the BrokeredMessage exposed the State/Status of the message.  This allowed Peeking of messages in a queue/subscription specifically for the purpose of locating messages that had been previously deferred and then orphaned.

Since the new version of the ServiceBus library does not expose the DispositionStatus in the message properties, it is no longer possible to effectively find and resolve deferred messages that have been orphaned in the queue/subscription.

Note that we are well aware that this is not a preferred scenario, but sometimes stuff breaks and you have to fix it as best you can.  The absence of the DispositionStatus has taken what should have been a 30-minute LinqPad fix and and turned it into an all-day affair for multiple engineers.

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @ShivangiReja

**Comment by nemakam** [comment]
@GrimGadget THanks for raising this. We will add it to our backlog and track it. However, there is no planned ETA as of now.

**Comment by JoshLove-msft** [comment]
@nemakam should this issue be tracked in the service bus repo if it requires service work? Or is it just Amqp library work?

**Comment by ramya-rao-a** [comment]
Thanks for reporting @GrimGadget 
There is definitely interest in this feature as seen in another issue we got, see https://github.com/Azure/azure-sdk-for-net/issues/14205

The message state feature is not available in the AMQP implementation for Service Bus.
The older `WindowsAzure.ServiceBus` package used a different protocol and so was able to support this feature.

For the newer SDKs to support this, the service has to support this feature first.
https://github.com/Azure/azure-service-bus/issues is the repo where the service team takes in feature requests.

Related issues there are https://github.com/Azure/azure-service-bus/issues/442 and https://github.com/Azure/azure-service-bus/issues/95. Please participate in these issues to get input from the service team.

Closing this issue as there are no planned next steps from the SDK perspective.
