### ISSUE TITLE
[BUG] Azure KeyVault: Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''.

### ISSUE THREAD

**Issue by jublair** [Azure/azure-sdk-for-net#10248]
**Describe the bug**
I've been experiencing issues with acquiring an Azure Authentication token in Visual Studio 2019. While I appear to be able to acquire tokens for other services (e.g. ADLS) with no issue, Azure Key Vault fails to correctly utilise a token provided using `ServiceClientCredentials`.

I have attempted to authenticate using both Azure CLI and the Visual Studio built-in authentication mechanism, but both return the same exception.

**Expected behavior**
Key Vault client will authenticate successfully using client credentials.

**Actual behavior (include Exception or Stack Trace)**
```
[3/2/2020 10:24:26 PM] Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired.
[3/2/2020 10:24:26 PM] Exception for Visual Studio token provider Microsoft.Asal.TokenService.exe : Token response is not in the expected format. Exception Message: Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''.
[3/2/2020 10:24:26 PM] Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. Token response is not in the expected format. Exception Message: Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''.
[3/2/2020 10:24:26 PM] .
```

**To Reproduce**
Attempt to acquire an `AzureServiceTokenProvider` while debugging in Visual Studio 2019.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] Microsoft.Azure.KeyVault v3.0.5
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Core 2.2
 - IDE and version : Visual Studio 16.4.5

**Comment by jublair** [comment]
I've only encountered this issue while remoting into my workstation via RDP, not sure if it's a red herring but just in case that info is useful...

**Comment by heaths** [comment]
I see that MSAL is failing to parse a document. If this only happens when you RDP in, I wonder if the path is resolved differently. Could you run [procmon](https://docs.microsoft.com/sysinternals/downloads/procmon) and see where it's looking in both cases?

Another option is to upgrade to Azure.Security.KeyVault.* version 4. These are our new libraries under active development that are faster with fewer allocations, more extensible (logging, HTTP pipeline, etc.), and easier authentication. In this case, however, we don't *yet* have VS authentication but that is coming very soon.

We're only making critical fixes to Microsoft.Azure.* package where Azure.* packages exist, though it seems in this case if this is an MSAL bug we'd need to get a fix and take a new version if that is indeed the case.

**Comment by jublair** [comment]
Thanks for taking this up @heaths! I think the paths are being resolved correctly here - the MSAL path (%LOCALAPPDATA%\Local\.IdentityService\msal.cache) appears to be valid on RDP when checking with procmon.

I could try the new SDK - do you reckon it would address this particular issue?

**Comment by jublair** [comment]
Okay - I tried using the new KeyVault SDK and authenticated using Azure CLI az login` (is this supported?) and received the following exception instead:

```
Service request failed.
Status: 400 (Bad Request)

Content:
<!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre></code>

                  </td>
               </tr>
            </table>

            <br>

    </body>
</html>


Headers:
Cache-Control: private
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Strict-Transport-Security: max-age=31536000;includeSubDomains
X-Content-Type-Options: nosniff
Date: Tue, 03 Mar 2020 01:57:26 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 3420
```

Looks like a generic 5xx response, despite the 400 response code. I'll try using a service principal as well, but perhaps a more informative exception would be helpful here.

**Comment by jublair** [comment]
Nevermind - I tried using the recommendation of an AAD application, but received the same result.

**Comment by heaths** [comment]
Azure.Security.KeyVault will support `az login` and VS very soon. We'll have news to share shortly. I will have to track down owners for ASAL as this seems to be a problem with their library.

**Comment by jublair** [comment]
Sounds good. I think this has something to do with my connection to my work environment. If it helps, here's how I'm connected:

Home PC (not domain-joined to MSFT) > Hyper-V VM (MSFTVPN connected) > RDP to work computer (in REDMOND domain)

**Comment by heaths** [comment]
@nonik0 could you have a look, please? Looks like ASAL is having problems parsing a file when a user is RDP'd into a session.

**Comment by jublair** [comment]
@heaths @nonik0 I've done some further investigation, and have the following useful info:

* I went into the office today and tested my code on my desktop (without RDP/VMs) and encountered the same issue. So I doubt that RDP is actually the culprit here.
* This issue only appears to be affecting my local environment; the same binaries deployed to Azure work with no issue.
* I tried running my code on a different machine (my laptop) and encountered the same issue.
* I only started encountering this issue recently, despite making no code changes to our key vault client since the issues began.

This is starting to look more like a service error, rather than a client error. Thoughts?

**Comment by heaths** [comment]
The client is trying to get cached access tokens before it can authenticate to the service. I'm wondering if maybe Visual Studio took an update and broke the format that this version of ASAL is expecting. Does `az login` work for you instead?

**Comment by jublair** [comment]
`az login` doesn't appear to work here, unfortunately - the same error is returned, which is somewhat suspect as the access tokens in this instance would be different, right?

I'm wondering if the `Internal Service Error` message I'm receiving on the new Key Vault client is the underlying issue, and ASAL is just failing to parse the page as it is invalid JSON/XML.

**Comment by heaths** [comment]
From your original stack,
```
[3/2/2020 10:24:26 PM] Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired.
[3/2/2020 10:24:26 PM] Exception for Visual Studio token provider Microsoft.Asal.TokenService.exe : Token response is not in the expected format. Exception Message: Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''.
```

Are you getting a different stack now?

It seems like it's having problems parsing a file (likely XML; I really don't know, though). I know, conceptually, there are a cache of files that contain access tokens we try to reuse to send to services. Apart from that, @nonik0 would need to take a look.

**Comment by jublair** [comment]
The original stack is what appears on `Microsoft.Azure.KeyVault`, and the internal service error I'm referring to [here](https://github.com/Azure/azure-sdk-for-net/issues/10248#issuecomment-593727508) appears on `Azure.Security.KeyVault`.

**Comment by heaths** [comment]
I did mention above that,
> In this case, however, we don't yet have VS authentication but that is coming very soon.

So no authentication credential is sent for Azure.* yet, but will be very soon.

**Comment by jublair** [comment]
That's true, though [I did attempt to use AAD application authentication](https://github.com/Azure/azure-sdk-for-net/issues/10248#issuecomment-593729754) and received the same result:

```
    "AZURE_CLIENT_ID": "812xxx",
    "AZURE_CLIENT_SECRET": "xxx",
    "AZURE_TENANT_ID": "72fxxx"
```

**Comment by heaths** [comment]
Without sample code, it's hard to say. Did you use a `DefaultAzureCredential` and were those environment variables set such that the process picked them up. If you set them on your machine but without restarting VS (if you're debugging/testing your app), they won't get used. We use service principals in our live tests every night, as well as ad-hoc testing.

But that result page you got doesn't look right either. What are you passing for the vault URI?

**Comment by jublair** [comment]
I tried using `DefaultAzureCredential`, and I believe so - I'm using the same mechanism provided by `local.settings.json` that works fine for other environment variables and picks up the latest values on each run. 

The key vault URL I'm testing on is: `https://InsertVaultNameHere.vault.azure.net`

**Comment by heaths** [comment]
I'll need to see more: either a sample projects, or you can contact me internally with project details. You could also enable tracing, which in Azure with Application Monitoring enabled should be automatic; otherwise, see https://heaths.dev/azure/2020/02/04/trace-azure-sdk-for-net.html.

**Comment by jublair** [comment]
Okay, I found out why the odd `Internal Server Error` response was being received - I hadn't updated `GetSecretAsync` from the old interface of `(string vaultBaseUrl, string secretName)` to `(string name, string version)`. Perhaps there was a parsing error with the inputs here - some user validation might make sense here on the client end to make code upgrades from the old library to the new one smoother. 

The environment credentials seem to work on the new SDK after all, which is good to know! Where can I track the use of Azure CLI/Visual Studio authentication being made public, by the way?

**Comment by varunsh-msft** [comment]
@jublair , I tried this using Microsoft.Azure.KeyVault v 3.0.5, Microsoft.Azure.Services.AppAuthentication v 1.4.0, Visual Studio 16.4.5 and it worked fine for me. 

Could it be a transient issue? Can you try again? 

This is the code I used:
var azureServiceTokenProvider1 = new AzureServiceTokenProvider("RunAs=Developer; DeveloperTool=VisualStudio");
            var kv = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider1.KeyVaultTokenCallback));
            Console.WriteLine(await kv.GetSecretAsync("https://myvault.vault.azure.net/secrets/mysecret/8bfe9cbc568b49988155969ba628a800"));

**Comment by heaths** [comment]
You might track it through https://github.com/Azure/azure-sdk-for-net/issues/8934; otherwise, @schaabs, do you have an epic tracking this?

**Comment by jublair** [comment]
Thanks for the help folks! Turns out this was a transient issue with (perhaps) AAD issuing bad tokens. Either way, the issue appears to have subsided, so I'll close out this issue and monitor the provided issue to track when Azure CLI will be available on the new package.
