### ISSUE TITLE
[FEATURE REQ]: Make DefaultAzureCredential support tenants where a trust has been created.

### ISSUE THREAD

**Issue by CKHere** [Azure/azure-sdk-for-net#10259]
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
I have a problem when I try to use my VS2019 credentials through the DefaultAzureCredential for local SSO during develop. The problem is that we have two tenants: one Enterprise tenant, where all our corporate users are stored, and another tenant we use for developing solutions in Azure. The two tenants has a trust, so I can use my enterprise credentials in the other tenant. My users in the two tenants:

Tenant ID: 1aaaea9d-df...
![Tennant_with_trust](https://user-images.githubusercontent.com/4884144/75770973-521f4c00-5d49-11ea-99bf-b68d0a0812b7.png)

Tenant ID: 1e2ad6d6-27...
![Tennant_enterprise](https://user-images.githubusercontent.com/4884144/75770999-5b101d80-5d49-11ea-8200-b40143c02ef9.png)

When I log into VS2019, it looks like this:
![VS2019_login](https://user-images.githubusercontent.com/4884144/75771012-62cfc200-5d49-11ea-852b-eb4567245fad.png)

I haven't been able to force it to use the tenant: 1aaaea9d-df... where all our ressources are placed. I have tried to write something like:
cpj_kmd_dk@otherdomain.dk and otherdomain.dk\cpj@kmd.dk (only the second option allows me to login, but I think it just redirects me to the regular domain, which issues the Token).

I set the local.settings.json as this.
![local settings json](https://user-images.githubusercontent.com/4884144/75772181-bb07c380-5d4b-11ea-96f1-4d0e1da80dba.png)

This gives me the following exception, where you can see that it only finds the token from my enterprise domain. If I had a separate login to my secondary tenant, then I guess it would have worked. 

```
Azure.Identity.AuthenticationFailedException: The DefaultAzureCredential failed to retrieve a token from the included credentials.
  EnvironmentCredential is unavailable Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  AZURE_TENANT_ID AZURE_USERNAME ].
  ManagedIdentityCredential is unavailable No managed identity endpoint found..
  SharedTokenCacheCredential is unavailable No account matching the specified username: CPJ@kmd.dk tenantId: 1aaaea9d-df... was found in the cache. To authenticate with the SharedTokenCacheCredential, login an account through developer tooling supporting Azure single sign on. [ {username: CPJ@kmd.dk tenantId: 1e2ad6d6-27...} ].
See inner exception for more detail.
 ---> System.AggregateException: The DefaultAzureCredential failed to retrieve a token from the included credentials. (Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  AZURE_TENANT_ID AZURE_USERNAME ]) (No managed identity endpoint found.) (No account matching the specified username: CPJ@kmd.dk tenantId: 1aaaea9d-df... was found in the cache. To authenticate with the SharedTokenCacheCredential, login an account through developer tooling supporting Azure single sign on. [ {username: CPJ@kmd.dk tenantId: 1e2ad6d6-27...} ])
 ---> Azure.Identity.CredentialUnavailableException: Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  AZURE_TENANT_ID AZURE_USERNAME ]
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) Azure.Identity.CredentialUnavailableException: No managed identity endpoint found.<---

 ---> (Inner Exception #2) Azure.Identity.CredentialUnavailableException: No account matching the specified username: CPJ@kmd.dk tenantId: 1aaaea9d-df... was found in the cache. To authenticate with the SharedTokenCacheCredential, login an account through developer tooling supporting Azure single sign on. [ {username: CPJ@kmd.dk tenantId: 1e2ad6d6-27...} ]<---

   --- End of inner exception stack trace ---
   at AzureManagedIdentityTest.AzTest.Test() in C:\DIMA_WORK\_Misc\src\AzureManagedIdentityTest\AzureManagedIdentityTest\AzTest.cs:line 70
   at AzureManagedIdentityTest.AzureTest.Run(HttpRequest req, ILogger log) in C:\DIMA_WORK\_Misc\src\AzureManagedIdentityTest\AzureManagedIdentityTest\Function1.cs:line 51
```

If I don't set the AZURE_TENANT_ID in the local.settings.json, it tries to use the stored token, however, as this token comes from my enterprise tenant the issuer validation fails:

```
Azure.RequestFailedException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:b0940b68-501e-00fd-6650-f15152000000
Time:2020-03-03T11:41:34.6324867Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)

ErrorCode: AuthenticationFailed

Additional Information:
AuthenticationErrorDetail: Issuer validation failed. Issuer did not match.

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: b0940b68-501e-00fd-6650-f15152000000
x-ms-error-code: AuthenticationFailed
Date: Tue, 03 Mar 2020 11:41:33 GMT
Content-Length: 422
Content-Type: application/xml
   at AzureManagedIdentityTest.AzTest.Test() in C:\DIMA_WORK\_Misc\src\AzureManagedIdentityTest\AzureManagedIdentityTest\AzTest.cs:line 70
   at AzureManagedIdentityTest.AzureTest.Run(HttpRequest req, ILogger log) in C:\DIMA_WORK\_Misc\src\AzureManagedIdentityTest\AzureManagedIdentityTest\Function1.cs:line 51
```

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by jongio** [comment]
@schaabs - Can you please review this one?  Thanks, Jon

**Comment by schaabs** [comment]
@CKHere in our last preview release, [1.2.0-preview.2](https://www.nuget.org/packages/Azure.Identity/1.2.0-preview.2), we added the `VisualStudioCredential` to the `DefaultAzureCredential` authentication flow, which I believe should fix this scenario of signing into a guest tenant when authenticating in VS. If you log into VS with the desired account, and then specify the tenant you wish to authenticate in either via the AZURE_TENANT_ID environment variable or the `VisualStudioTenantId` property on `DefaultAzureCredentialOptions` this will authenticate the account to the desired tenant. Please try it out and file issues if you have any feedback. Also feel free to reopen this issue if you find the addition of the `VisualStudioCredential` doesn't actually unblock your scenario.
