### ISSUE TITLE
[QUERY] PostgreSQL - how to retrieve server information?

### ISSUE THREAD

**Issue by rsantosdev** [Azure/azure-sdk-for-net#10253]
**Query/Question**
Using the Microsoft.Azure.Management.Fluent I can query the available metrics for a given PG Server.
Researching more I found Microsoft.Azure.Management.PostgreSQL pacakge, but I couldn't find any information on how to use it to query PG Server information on azure.
So my question is: How can I query server information with the resource id?

**Environment:**
 - Name and version of the Library package used: 
   Microsoft.Azure.Management.Fluent 1.31.1
   Microsoft.Azure.Management.PostgreSQL 0.9.0-preview

**Comment by jsquire** [comment]
//cc: @yaohaizh

**Comment by yaohaizh** [comment]
@dingmeng-xue the packaged use is not-fluent SDK.

**Comment by rsantosdev** [comment]
I figured it out. In summary, you need to create a TokenCredential object to authenticate the PG client and query information. Follow there's the code I used:
```
            var context = new AuthenticationContext($"https://login.microsoftonline.com/{tenantId}");
            var cc = new ClientCredential("clientId", "clientSecret");
            var result = await context.AcquireTokenAsync("https://management.azure.com/", cc);
            var tokenCredential = new TokenCredentials(result.AccessToken);

            var client = new PostgreSQLManagementClient(tokenCredential)
            {
                SubscriptionId = "subscriptionId"
            };

            var pgServer = await client.Servers.GetAsync("resourceGroup", "serverName");
```
