### ISSUE TITLE
[BUG] CognitiveServices TextAnalytics DetectLanguage has an invalid default as country hint

### ISSUE THREAD

**Issue by DiegoFaFe** [Azure/azure-sdk-for-net#10268]
**Describe the bug**
DetectLanguageAsync defaults countryHint to "en" which is not a valid ISO 3166-1 alpha-2 code
![image](https://user-images.githubusercontent.com/11487214/75803815-52d2d500-5d7f-11ea-985d-7be25f9ab1ee.png)

**Expected behavior**
Should default to a valid country code like "gb" or "us"

**Actual behavior (include Exception or Stack Trace)**
Returns an error as the country code is invalid

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Call DetectLanguageAsync with just the input text

**Environment:**
 - Name and version of the Library package used: 
**Microsoft.Azure.CognitiveServices.Language.TextAnalytics 4.0.0**

**Comment by maririos** [comment]
Hi @DiegoFaFe .

What version of the library are you using?
We did notice that bug and was [fixed](https://github.com/Azure/azure-sdk-for-net/commit/3ac3a798aa5ad392f7b6bcb46b09fdb91bf9d59e) in preview.2 . See package [here](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Language.TextAnalytics/4.1.0-preview.2).

I would like to encourage you to take a look at the new client library for Text Analytics under namespace [Azure.AI.TextAnalytics](https://www.nuget.org/packages/Azure.AI.TextAnalytics/1.0.0-preview.2). This new library targets the latest version of the service ([3.0-preview](https://docs.microsoft.com/en-us/azure/cognitive-services/Text-Analytics/quickstarts/text-analytics-sdk?pivots=programming-language-csharp&tabs=version-3#language-detection)) which includes new and improved functionalities.

**Comment by DiegoFaFe** [comment]
Hi @maririos , I was using the latest stable 4.0.0, if that's already solved then I can close the issue :) Just a quick question before closing it though, Is there any ETA for the stable release?

**Comment by maririos** [comment]
Release for Text Analytics 3.0 for service and client library Azure.AI.TextAnalytics 1.0.0 is expected around April-May.
Next week we are going to be releasing Azure.AI.TextAnalytics1.0.0.preview.3.0 in case you want to start trying it :)

**Comment by DiegoFaFe** [comment]
Thanks @maririos I'll give it a go, I'm closing this issue as its resolved on the preview package
