### ISSUE TITLE
[BUG] ICheckpointMananger is misspelled in Service Fabric Processor

### ISSUE THREAD

**Issue by pingzing** [Azure/azure-sdk-for-net#10260]
**Describe the bug**

I genuinely am not sure whether or not this is actually a _bug_ per se, but it did just cause me several minutes of confusion and frustration. I'm also not sure if it's fixable without breaking changes.

The `ICheckpointMananger` interface is misspelled. There is an extra `n`: ICheckpointMana**n**ger

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.EventHubs.ServiceFabricProcessor, v0.5.4.0

**Comment by jsquire** [comment]
//cc: @JamesBirdsall

**Comment by JamesBirdsall** [comment]
Argh.
At least it's still preview, so we can fix that.

**Comment by samuelkoppes** [comment]
We are investigating the status of this fix, and will report back with an update by 11/4/2020.

**Comment by kasun04** [comment]
The Microsoft.Azure.EventHubs.ServiceFabricProcessor package is in preview and there are no plans for a stable release. This package will soon be deprecated and therefore we won't be taking any changes.
