### ISSUE TITLE
[BUG] Cognitiveservices LUIS Authoring updating app version settings throws exception on response status code 201

### ISSUE THREAD

**Issue by fkuehnSAG** [Azure/azure-sdk-for-net#10298]
When calling LuisAuthoringClient.Settings.UpdateWithHttpMessagesAsync() it throws the following Exception: Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring.Models.ErrorResponseException: Operation returned an invalid status code 'Created'

The automatic generated code in Settings.cs just throws this exception when the status code of the response is not 200, but the api currently returns 201.

Note: The api documentation is also wrong at this point. See: https://westus.dev.cognitive.microsoft.com/docs/services/5890b47c39e2bb17b84a55ff/operations/versions-update-application-version-settings

**Comment by jsquire** [comment]
//cc: @maririos

**Comment by maririos** [comment]
Thanks @fkuehnSAG . What version of the client library are you using?

@ChrisHMSFT could you help reroute to the appropriate team?

**Comment by fkuehnSAG** [comment]
@maririos i am using version 3.1.0 of Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring

**Comment by maririos** [comment]
@ChrisHMSFT could you help reroute to the appropriate team?

**Comment by maririos** [comment]
@a-noyass or @nourhanFarid do you have context here?

**Comment by ChrisHMSFT** [comment]
@kayousef  can you help take a look. thanks!

**Comment by kayousef** [comment]
@fkuehnSAG the bug should be fixed in the latest SDK version. Can you update and confirm?

**Comment by fkuehnSAG** [comment]
@kayousef I tested again and it is working as expected 👍 
Thank you!

**Comment by kayousef** [comment]
Thanks @fkuehnSAG for reporting back. Glad to help :)
