### ISSUE TITLE
[BUG] UnsupportedHttpVerb code returned with SendMessageAsync method of QueueClient

### ISSUE THREAD

**Issue by Asier-Villanueva** [Azure/azure-sdk-for-net#10299]
**Describe the bug**
UnsupportedHttpVerb code returned with SendMessageAsync method of QueueClient
The code has been working fine til few hours ago

**Expected behavior**
Queue message creation

**Actual behavior (include Exception or Stack Trace)**
An AzureRequestFailedException:

> The resource doesn't support specified Http Verb.
> RequestId:57b7f149-2003-0040-153f-f27920000000
> Time:2020-03-04T16:10:26.7503611Z
> Status: 405 (The resource doesn't support specified Http Verb.)
> ErrorCode: UnsupportedHttpVerb
> 
> Headers:
> Server: Microsoft-HTTPAPI/2.0
> x-ms-request-id: 57b7f149-2003-0040-153f-f27920000000
> x-ms-error-code: UnsupportedHttpVerb
> Date: Wed, 04 Mar 2020 16:10:26 GMT
> Allow: REDACTED
> Content-Length: 237
> Content-Type: application/xml

StackTrace:

>    at Azure.Storage.Queues.QueueRestClient.Messages.EnqueueAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)

**To Reproduce**

1. Create a QueueClient
`            var queueServiceClient = new QueueServiceClient(options.ConnectionString);
            _queueClient = queueServiceClient.GetQueueClient(options.QueueName);`
2.Try to send base64 encoded message
`            string json = JsonConvert.SerializeObject(message);
            var b64Message = Convert.ToBase64String(Encoding.UTF8.GetBytes(json));
            SendReceipt sendReceipt = (await _queueClient.SendMessageAsync(b64Message));
`

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Queues 12.2.0 

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 
client app is a .NET Core 2.2 Console Application
Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64

 - IDE and version : Microsoft Visual Studio 2019 Version 16.4.5

**Comment by jsquire** [comment]
//cc: @tg-msft

**Comment by tg-msft** [comment]
If it was working fine until a few hours ago, is there any chance someone changed [the CORS rules of your storage account](https://docs.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services#enabling-cors-for-azure-storage)?

**Comment by amishra-dev** [comment]
Thanks Ted, Jesse. 
@jaschrep-msft lets sync about this at standup and followup

**Comment by Asier-Villanueva** [comment]
> If it was working fine until a few hours ago, is there any chance someone changed [the CORS rules of your storage account](https://docs.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services#enabling-cors-for-azure-storage)?

No, no change.

**Comment by Asier-Villanueva** [comment]
Sorry, an error in my code.
A change caused the parameter _queueName_ to be _null_ when creating the _QueueClient_
`_queueClient = queueServiceClient.GetQueueClient(null);`

Returned error has confused me.

Sorry and thanks for all.
