### ISSUE TITLE
[QUERY]How update .net core azure cli environment?

### ISSUE THREAD

**Issue by sergiosolorzano** [Azure/azure-sdk-for-net#10295]
**Query/Question**
How can we help?
how install .net core in azure cli share folder. Please refer to the explanation in my question posted in stackoverflow: https://stackoverflow.com/questions/60514333/how-install-net-core-in-azure-cli-share-folder
**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
.net core 2.2.402
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
PS /> dotnet --list-sdks
1.0.1 [/usr/share/dotnet/sdk]
2.2.402 [/usr/share/dotnet/sdk]
PS /> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.402
 Commit:    c7f2f96116

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.402/

Host (useful for support):
  Version: 2.2.8
  Commit:  b9aa1abc51

.NET Core SDKs installed:
  1.0.1 [/usr/share/dotnet/sdk]
  2.2.402 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
 - IDE and version : [e.g. Visual Studio 16.3]
Azure cli in this case but VS is 16.4.5

**Comment by jsquire** [comment]
@AlexGhiondea:  Could you assist in routing this, please?

**Comment by AlexGhiondea** [comment]
@erich-wang is this something you can help with?

**Comment by isra-fel** [comment]
Hi @sergiosolorzano if my understanding is right, you are trying to install dotnet core 3.0 on cloud shell.
I'm not sure if there's a way to do that... looping in the cloud shell team

**Comment by maertendMSFT** [comment]
Please follow .net's documentation for updating versions.  This will be a local update to your cloud shell image.  A cloud shell update is in the works for specific tooling, no ETA to share at the moment

**Comment by maertendMSFT** [comment]
The Cloud Shell tools image is now open-source, if you would like to contribute this change to our dockerfile (https://github.com/Azure/CloudShell/blob/master/linux/base.Dockerfile), a PR would be reviewed.

**Comment by maertendMSFT** [comment]
@sergiosolorzano, does this resolve your issue?  If so, please close.
