### ISSUE TITLE
[BUG] Error Code not present on failed InsertBatchAsync

### ISSUE THREAD

**Issue by jepetty** [Azure/azure-sdk-for-net#10314]
**Bug description**
We're seeing some calls to `InsertBatchAsync` fail with exception 
> Microsoft.WindowsAzure.Storage.StorageException: Element 0 in the batch returned an unexpected response code.

The problem is that we can't filter on that exception, because the ErrorCode is empty in the RequestInformation: 
>Request Information
RequestID:dab463cd-3002-0025-5d8a-f22ce5000000
RequestDate:Thu, 05 Mar 2020 01:04:57 GMT
StatusMessage:The server is busy.
ErrorCode:
ErrorMessage:The server is busy.
RequestId:dab463cd-3002-0025-5d8a-f22ce5000000
Time:2020-03-05T01:04:57.9464481Z

**Expected behavior**
I would expect the ErrorCode to be "ServerBusy" so that we can use it to filter on the actual exception received from the server.

**To Reproduce**
Calling
```
CloudTable.ExecuteBatchAsync(...)
```
to a busy server will result in this error with an empty ErrorCode

**Comment by amishra-dev** [comment]
@jepetty I am assuming that you are using V11 .NET library? That is the track 1 library, would you consider moving to our latest library? 
Here is the blob library https://www.nuget.org/packages/Azure.Storage.Blobs/
Here is the batch library https://www.nuget.org/packages/Azure.Storage.Blobs.Batch/ 

Feel free to use this thread to discuss migration.
Meanwhile @seanmcc-msft can you please look at why Jessica is hitting this error in track1?

**Comment by amnguye** [comment]
100% this is Track1 but the Track1 Tables SDK

Table support has moved to the CosmosDB NuGet package. Please follow up there.

https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table
