### ISSUE TITLE
[BUG] EH SDK: Enqueued Time on root activity, not on the links

### ISSUE THREAD

**Issue by Dmitry-Matveev** [Azure/azure-sdk-for-net#10324]
**Describe the bug**
[This recent PR](https://github.com/Azure/azure-sdk-for-net/pull/10227/files) has added attribute "x-opt-enqueued-time" to the Diagnostic Scope activity.
While debugging this new behavior with new version of Application Insights SDK that reads this attribute, I noticed that there is disconnect between the two SDKs on the expected attribute location:
- AI SDK [looks through the links](https://github.com/microsoft/ApplicationInsights-dotnet/blob/502f001c59f104f2a81bc002b48b909fa57e98ef/WEB/Src/DependencyCollector/Shared/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L149-L151) of the [Activity in Diagnostic Source event](https://github.com/microsoft/ApplicationInsights-dotnet/blob/502f001c59f104f2a81bc002b48b909fa57e98ef/WEB/Src/DependencyCollector/Shared/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L67);
- EH SDK [stores that time in the tags of the main Activity](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L730) instead.

Side note: AI SDK reads ["enqueueTime"](https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/Shared/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L181) attribute while value is posted to ["x-opt-enqueued-time"](https://github.com/Azure/azure-sdk-for-net/blob/eea84100459b1b97547c3a556fc7491f78afafcb/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Diagnostics/DiagnosticProperty.cs#L25) attribute, one of the SDKs would need to fix that too (I guess, AI?).

**Expected behavior**
I had a conversation with original developer on AI SDK side and the expected behavior seem to be to store enqueued time in the links of the activity because it's the way to post that time for each separate message. (+ Both SDKs should agree on the attribute name :) )

**Actual behavior (include Exception or Stack Trace)**
EH SDK stores enqueued time on the main Activity propagated with DS event.

**To Reproduce**
- Debug [LineCounter](https://github.com/pakrym/LineCounter) application (make sure both projects are marked as startup). 
- Ensure latest AI SDK is installed (or build from local source)
- Ensure latest EH SDK is installed (or build from local source)
- Set BP on [AI reading EH DS event](https://github.com/microsoft/ApplicationInsights-dotnet/blob/502f001c59f104f2a81bc002b48b909fa57e98ef/WEB/Src/DependencyCollector/Shared/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L67), check that root Activity has tag, not linked activities.

**Environment:**
 - Latest master from source, EH SDK, commit 257703eb88ce733d0d8cbbd22c66339794fa8350.
 - Win10, .NET Core 3.0
 - Visual Studio 16.4.5

**Comment by Dmitry-Matveev** [comment]
@kinelski , not sure what's the right approach here, I touched base with @lmolkova and her expectation was to have enqueued time on links rather than main activity. I do lack context of the feature, though, I simply debugged the behavior to help one of the internal teams who tried this new feature out - let me know what you think.

**Comment by lmolkova** [comment]
Here is the spec https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#processing-messages

I confirm that each linked activity should have enqueued time in case there is more than one message in the batch.

**Comment by kinelski** [comment]
Hello, @Dmitry-Matveev. That was definitely a mistake on my part. Thanks for pointing it out!

I have just opened a PR that will allow us to add attributes to linked activities (#10368). Once that's merged, I'll get the Event Hubs SDK fixed.

**Comment by kinelski** [comment]
@Dmitry-Matveev Issue should be fixed now. I moved the attribute to the links and renamed it to `enqueuedTime`. Let us know if you find any more issues. Thank you again!

**Comment by TimothyMothra** [comment]
@kinelski I see that this fix is assigned to an April deliverable.
Will you have a beta build between now and then that we could use to test with?
No rush :)

**Comment by jsquire** [comment]
@TimothyMothra:  There won't be an official preview build released between now and April, but you're welcome to use a nightly development feed package for testing.   Feel free to ping @kinelski or myself if you'd like a hand setting that up.

**Comment by TimothyMothra** [comment]
Thanks!
@OsvaldoRosado, please see above. :)

**Comment by Dmitry-Matveev** [comment]
@kinelski /@jsquire , thanks a lot! Super-quick turn-around, you're awesome! @OsvaldoRosado will give it a shot and we'll let you know if anything strange is afoot :)

**Comment by Dmitry-Matveev** [comment]
@kinelski , our team tried the fix out - the value is propagated successfully now.
However, we noticed that there is one more subtle difference from the spec - EH SDK uses `ToUnixTimeSeconds()` but should be using `ToUnixTimeMilliseconds()` as per [this spec](https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#processing-messages). Therefore, our current numbers are off by ~ 50 years :)

Could you please update this as well?

**Comment by jsquire** [comment]
I just made the change locally and will let it ride along with my next PR, expected in the next day or so.    Once that gets merged in, I'll ping this issue to let folks know it can be tested.

**Comment by jsquire** [comment]
This change is included in #10575.   I'll drop an update when that merges.   Apologies for the delay.

**Comment by jsquire** [comment]
#10575 has been merged and the requested change should appear in the dev package feed starting tomorrow.  I'm going to close this out to mark the change complete.   Please feel free to re-open if it isn't working as expected.
