### ISSUE TITLE
Auto-detect content-type in streams

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10329]
StartExtractForm, ExtractReceipt, and StartExtractLayout all require a FormContentType to be passed in to indicate whether the stream contains a JPG, PNG, etc.  We should auto-detect this and possibly allow clients to override (although decide based on our implementation whether they need to do this at all).

The python team is looking at putting this autodetection into their code generator.  We should leverage their knowledge in developing a solution for .NET.

**Comment by annelo-msft** [comment]
If there is no need for users to specify ContentType once this is implemented, remove ContentType enum from the FR public API.

**Comment by maririos** [comment]
FYI on how Java is approaching this issue: https://github.com/Azure/azure-sdk-for-java/pull/9953#event-3212634088
