### ISSUE TITLE
[BUG] Different casing/value on Location property in different packages

### ISSUE THREAD

**Issue by dhvik** [Azure/azure-sdk-for-net#10343]
**Description**
When retrieving resources using Management API:s and checking the Location property, the result is different between packages which makes comparison difficult.

For example, if I retrieve a storage account using Microsoft.Azure.Management.Storage v14.5.0

```
StorageManagementClient storageManagementClient = ...;
var accounts = await storageManagementClient.StorageAccounts
  .ListByResourceGroupWithHttpMessagesAsync(resourceGroupName);
foreach (var account in accounts.Body)
{
  Console.WriteLine(account.Location);
}
```
the location is "**westeurope**"

If I then use Microsoft.Azure.Management.Media v2.0.4...
```
AzureMediaServicesClient mediaServiceClient = ...;
mediaServiceClient.SubscriptionId = subscriptionId;
var mediaService = await mediaServiceClient.Mediaservices.GetAsync(resourceGroupName, accountName);
Console.WriteLine(mediaService.Location);
```
the location is "**West Europe**"

**Expected behavior**
I expect the property value to be consistent across management packages

**Environment:**
 - Microsoft.Azure.Management.Storage v14.5.0
 - Microsoft.Azure.Management.Media v2.0.4
 - .net framework 4.6.2
 - Visual Studio 16.4.3

**Comment by jsquire** [comment]
//cc: @erich-wang

**Comment by blueww** [comment]
For storage SDK we just report what returns from server, so this looks like the server return from storage and Media are different.

**Comment by allenjzhang** [comment]
Assign to AMS team.

**Comment by giakas** [comment]
SDK returns this data from the services. 
Spoke to the ARM team regarding this, and the only requirement they have is that, all services should take any casing(with/without spaces) in the request body, and no requirement on which casing should be in the response body. 

[https://github.com/Azure/azure-resource-manager-rpc/blob/d8e13741d0ff55b776f33dc8471c71a2944a8096/v1.0/common-api-contracts.md#system-metadata-for-all-azure-resources](https://github.com/Azure/azure-resource-manager-rpc/blob/d8e13741d0ff55b776f33dc8471c71a2944a8096/v1.0/common-api-contracts.md#system-metadata-for-all-azure-resources)

and unfortunately based on this documentation, many teams including our team has gone with display name (capitals and spaces). Don't think there is a way to move all the teams to converge on the same casing, as it will be a breaking change. 

Unfortunately user's will have to convert to small casing while comparing.
