### ISSUE TITLE
Assess performance of BoundingBox implementation

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10358]
Currently using System.Linq to cast collection to an array to be able to index into it.  If we can pass in an IList<float> we can index directly.  Ideally, we should remove calls to System.Linq.

**Comment by annelo-msft** [comment]
Related to https://github.com/Azure/azure-sdk-for-net/issues/10360

**Comment by kinelski** [comment]
Fixed by #13551.
