### ISSUE TITLE
Add support for Lines to ResolveTextReference

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10364]
ExtractedField.ResolveTextReference() currently [only returns RawExtractedWord](https://github.com/Azure/azure-sdk-for-net/blob/5111925a4021ef5ee498bcf5fddf4a16c4e2da62/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ExtractedField.cs#L86) objects.  It should determine from the reference whether it's gotten a line or a word and return the correct type.

**Comment by annelo-msft** [comment]
@ctstone Would you share a JSON document with us that has lines instead of words in the element references?

**Comment by ctstone** [comment]
I have not come across one in the wild. For unsupervised we use only Word.

**Comment by annelo-msft** [comment]
Completed in https://github.com/Azure/azure-sdk-for-net/pull/11318
