### ISSUE TITLE
Decide whether we want to make optional reference types nullable

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10361]
For example, in ExtractedField, [LabelOutline ](https://github.com/Azure/azure-sdk-for-net/blob/5111925a4021ef5ee498bcf5fddf4a16c4e2da62/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ExtractedField.cs#L49) is an optional parameter.  However, since it is a reference type, we can't mark it as nullable.

It sounds like the .NET team has considered this and decided to postpone using nullable reference types, which is a new feature in C#.  

Consider whether or not we want to indicate to users that reference type fields are optional in some other way.

See also:
https://github.com/Azure/azure-sdk-for-net/blob/ce046949f17fc4ceeab5c87beb4750047b983565/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ExtractedReceipt.cs#L26

**Comment by annelo-msft** [comment]
@tg-msft Does storage handle this?

**Comment by tg-msft** [comment]
Mainly via documentation in Storage and Search.  Some validation occasionally.  We're not using nullable references yet.

**Comment by annelo-msft** [comment]
Can you explain the choice not to use nullable refernces?  I just want to understand so I can explain it to others if it comes up.

**Comment by tg-msft** [comment]
No good reason, unfortunately.  It would have been a nontrivial amount of work and we had a tight schedule.  At this point, I'd consider the recommendation to be "wait until the new generator does most of it for you and then light the rest of your client up."

**Comment by annelo-msft** [comment]
@pakrym is this on the timeline for codegen at all?

**Comment by pakrym** [comment]
Pretty far down the line considering we didn't even do it for hand-written libraries.

**Comment by annelo-msft** [comment]
We will not address this, given precedent for .NET SDKs.
