### ISSUE TITLE
[Validations:] Add validation when setting FormType on Form

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10377]
See: https://github.com/Azure/azure-sdk-for-net/blob/5111925a4021ef5ee498bcf5fddf4a16c4e2da62/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ExtractedForm.cs#L133

We will need to understand whether it is possible that multiple pages in a page result could have different clusterIds.  If so, we will need to handle this correctly in SetLearnedFormType().

Get service team input on whether this is possible.

**Comment by annelo-msft** [comment]
@ctstone  Could you help us answer this from the service side?

**Comment by ctstone** [comment]
Each item in the `pageResult` array is a separate page with a unique page number. Is that what you are referring to?

**Comment by annelo-msft** [comment]
I misstated my question.  I meant could different pages in the same form have different clusterIds?

**Comment by ctstone** [comment]
Unsupervised clusters each page of a file independently. The reason we decided to go with page-level clustering is that most of the documents we received from customers were either single-page files or multi-page files where each page was a new form instance. We only had a handful of cases where an invoice was spanning more than a page.

In the future we may allow user to specify the per-page or per-document.

**Comment by annelo-msft** [comment]
Per Chris, one page is considered one form for unsupervised, so this won't be necessary.
