### ISSUE TITLE
[QUERY] Replacement for Microsoft.Azure.EventHubs.Processor?

### ISSUE THREAD

**Issue by SteffenMangold** [Azure/azure-sdk-for-net#10404]
**Query/Question**
Is **Azure.Messaging.EventHubs.Processor** a replacement for **Microsoft.Azure.EventHubs.Processor**?
Do we need to switch?
Is there an update stop on **Azure.Messaging.EventHubs.Processor**?
Is this library in conflict with **Microsoft.Azure.Storage.Common**?

Now there are 3 versions, this is really confusing and not written somewhere.
**Microsoft.Azure.ServiceBus.EventProcessorHost
Azure.Messaging.EventHubs.Processor
Microsoft.Azure.EventHubs.Processor**

What is the right library to use in Net Core 3.1.1?

**Comment by jsquire** [comment]
Hi @SteffenMangold.   To answer your questions in order:

- Yes,  `Azure.Messaging.EventHubs.Processor` is intended as a replacement for the `Microsoft.Azure.EventHubs.Processor` package as part of the efforts to offer a more consistent, cohesive, and idiomatic developer experience across the Azure SDKs as a whole.   

- There is no immediate need to switch; the `Microsoft.Azure.EventHubs` family of packages will continue to be supported and receive bug fixes and critical updates for the foreseeable future; unfortunately, I don't have definitive date that I can share but discussions were using a timeline of several years.  At some point, they will stop receiving new features and enhancements.  Unfortunately, once again, I don't have a firm timeline.

- The `Azure.Messaging.EventHubs.Processor` package has a dependency on the `Azure.Storage.Blobs` library as its interface to durable storage for checkpointing and load balancing.

For new development, we would recommend using the `Azure.Messaging.EventHubs` series of packages for Event Hubs and the `Azure.[[ AREA ]]` packages for other services.   If you're interested in some of the benefits and the differences between packages, you may want to review our [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md).  You may also be interested in the [Azure SDK design guidelines](https://azure.github.io/azure-sdk/general_introduction.html) and [.NET-specific guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html) for more context around the current direction, goals, and reasons why new client libraries are being created.

**Comment by jsquire** [comment]
I looks like discussion has tapered off, so I'm going to close this out.  Please feel free to reopen if there are additional questions or further discussion needed.

**Comment by SteffenMangold** [comment]
I looked now deeper into some of the new libraries. I hope it's ok to give you some feedback.

`EventProcessorClient` based on events now look really sad. :(
What happens to `IEventProcessor` that was really a great pattern, especially when pairing it with `BackgroundService` fro `IHostedService`. Basis processor class handling checkpoint automatically, DPI ect... all really not easy to handle with the event-driven pattern.

The `IEventProcessor` was really a good way. Kinda disappointed. :(

**Comment by SteffenMangold** [comment]
@jsquire please take a look at this really great way of using `IConfiguration`, `IOption` and DPI (for example in ASP.Core together with `IEventProcessor`. That way of reusable abstraction would be not possible with the event base pattern from the new library.  :(

### Basic event processor handling checkpoint handling
```c#
/// <summary>
/// Basic <see cref="IEventProcessor"/> implementation including defautl event logging and checkpoint behavior.
/// </summary>
public abstract class BaseEventProcessor : IEventProcessor
{
	readonly TimeSpan DefaultCheckpointInterval = TimeSpan.FromMinutes(1);
	readonly TimeSpan DefaultPartitionSequenceDifferenceMetricInterval = TimeSpan.FromMinutes(1);

	readonly TimeSpan _checkpointInterval;

	Stopwatch _checkpointStopWatch;

	/// <inheritdoc />
	public BaseEventProcessor(TimeSpan? checkpointInterval = null)
	{
		_checkpointInterval = checkpointInterval ?? DefaultCheckpointInterval;
	}

	/// <inheritdoc />
	public virtual Task ProcessErrorAsync(PartitionContext context, Exception error)
	{
		Requires.NotNull(context, nameof(context));
		Requires.NotNull(error, nameof(error));

		return Task.CompletedTask;
	}

	/// <inheritdoc />
	public virtual async Task CloseAsync(PartitionContext context, CloseReason reason)
	{
		Requires.NotNull(context, nameof(context));
		if (reason == CloseReason.Shutdown)
		{
			await context.CheckpointAsync();
		}
	}

	/// <inheritdoc />
	public virtual Task OpenAsync(PartitionContext context)
	{
		Requires.NotNull(context, nameof(context));

		_checkpointStopWatch = new Stopwatch();
		_checkpointStopWatch.Start();

		return Task.CompletedTask;
	}

	/// <inheritdoc />
	public virtual async Task ProcessEventsAsync(PartitionContext context, IEnumerable<EventData> messages)
	{
		Requires.NotNull(messages, nameof(messages));
		Requires.NotNull(context, nameof(context));

		if (messages.Count() > 0 && _checkpointStopWatch.Elapsed >= _checkpointInterval)
		{
			await context.CheckpointAsync();
			_checkpointStopWatch.Restart();
		}
	}
}
```

### Specific implementation of a custom event processor using DPI
```c#
/// <summary>
/// A class to process events from one partition of one Event Hub.
/// </summary>
public class EventProcessor : BaseEventProcessor, IEventProcessor
{
	readonly JsonMessageSerializer _serializer;

	/// <summary>
	/// Creates a new instance of <see cref="EventProcessor"/>.
	/// </summary>
	/// <param name="logger">Represents a type used to perform logging.</param>
	/// <param name="cloudBlobRawFileFactory">Factory for IRawFiles based on BlobCloud</param>
	/// <param name="serializer">Json serializer</param>
	/// <param name="signatureValidator">Signature validator</param>
	/// <param name="dataHandlerFactory"></param>
	public EventProcessor(ILoggerFactory loggerFactory, JsonMessageSerializer serializer)
	{
		_serializer = serializer;
	}

	/// <inheritdoc/>
	public override async Task ProcessEventsAsync(PartitionContext context, IEnumerable<EventData> messages)
	{
		
		// process messages...

		await base.ProcessEventsAsync(context, messages);
	}
}
```

### A background service abstraction to host custom event prozessor
```c#
public class EventProcessorService<TEventProcessor> : BackgroundService where TEventProcessor : IEventProcessor
{
	readonly IServiceProvider _serviceProvider;
	readonly ILogger _logger;
	readonly EventProcessorHost _eventProcessorHost;
	readonly EventProcessorOptions _eventProcessorOptions;

	public EventProcessorService(IServiceProvider serviceProvider
		, ILogger<EventProcessorService<TEventProcessor>> logger
		, IOptions<EventProcessorServiceOptions<TEventProcessor>> options)
	{
		Requires.NotNull(options, nameof(options));

		_serviceProvider = serviceProvider;
		_logger = logger;

		_eventProcessorHost = new EventProcessorHost(
			hostName: options.Value.HostName,
			eventHubPath: options.Value.EventHubPath,
			consumerGroupName: options.Value.ConsumerGroupName,
			eventHubConnectionString: options.Value.EventHubConnectionString,
			storageConnectionString: options.Value.StorageConnectionString,
			storageBlobPrefix: options.Value.StorageBlobPrefix,
			leaseContainerName: options.Value.LeaseContainerName)
		{
			PartitionManagerOptions = options.Value.PartitionManagerOptions
		};

		_eventProcessorOptions = options.Value.EventProcessorOptions ?? new EventProcessorOptions();
		_eventProcessorOptions.SetExceptionHandler(eventArgs =>
		{
			_logger.LogError(eventArgs.Exception, $"Error on event processor '{eventArgs.Hostname}' partition '{eventArgs.PartitionId}'.");
		});
	}

	protected override async Task ExecuteAsync(CancellationToken stoppingToken)
	{
		var eventProcessorFactory = ActivatorUtilities.CreateInstance<EventProcessorFactory<TEventProcessor>>(_serviceProvider);
		await _eventProcessorHost.RegisterEventProcessorFactoryAsync(eventProcessorFactory, _eventProcessorOptions);

		_logger.LogInformation($"Event processor host now listening to [{_eventProcessorHost.EndpointAddress}{_eventProcessorHost.EventHubPath}] as '{_eventProcessorHost.ConsumerGroupName}' consumer");

		stoppingToken.WaitHandle.WaitOne();

		await _eventProcessorHost.UnregisterEventProcessorAsync();
		_logger.LogInformation($"Event processor host unregistered");
	}
}
```

### Example of using it in ASP.Core
```c#
.ConfigureServices((hostContext, services) =>
{
	var jsonSerializerSettings = new JsonSerializerSettings
	{
		Converters = new List<JsonConverter> { new RoundingConverter(3) },
		ContractResolver = new DataEventContractResolver()
	};
	services.AddSingleton(Newtonsoft.Json.JsonSerializer.CreateDefault(jsonSerializerSettings));
	

	services.Configure<EventProcessorServiceOptions<EventProcessor>>(config =>
	{
		config.HostName = Guid.NewGuid().ToString();
		config.EventHubPath = hostContext.Configuration["EventProcessor:EventHubPath"];
		config.ConsumerGroupName = hostContext.Configuration["EventProcessor:ConsumerGroupName"];
		config.EventHubConnectionString = hostContext.Configuration["ConnectionStrings:EventHub"];
		config.StorageConnectionString = hostContext.Configuration["ConnectionStrings:EventHubLeases"];
		config.LeaseContainerName = hostContext.Configuration["EventProcessor:LeaseContainerName"];
		config.EventProcessorOptions = new EventProcessorOptions
		{
			PrefetchCount = 250,
			MaxBatchSize = 100,
			InitialOffsetProvider = (partitionId) => EventPosition.FromEnqueuedTime(DateTime.UtcNow),
			InvokeProcessorAfterReceiveTimeout = true,
			ReceiveTimeout = TimeSpan.FromSeconds(30),
			EnableReceiverRuntimeMetric = true
		};
		config.PartitionManagerOptions = new PartitionManagerOptions
		{
			RenewInterval = TimeSpan.FromSeconds(10),
			LeaseDuration = TimeSpan.FromSeconds(60)
		};
	});

	services.AddHostedService<EventProcessorService<EventProcessor>>();
})
```

**Comment by jsquire** [comment]
Hi Seffen.  We're sorry to hear that you're disappointed.  As mentioned, the `EventProcessorClieent` is intended to be a drop-in replacement for the legacy `Microsoft.Azure.EventHubs.Processor` package while offering an experience familiar to that of the `EventHubConsumerClient`.   We believe this provides a natural step-up experience that addresses the production needs of a large segment of Event Hubs users.

At the same time, we also recognize that there are those who have specialized needs for whom a guided experience is not ideal.  To address those scenarios, the `EventProcessor<TPartition>` provides the basis for an event processor that provides the core functionality for load balancing and partition management without the opinionated layer, allowing extenders to control storage operations and to access the event batches read from the service in raw form.

From your feedback, I would speculate that you may prefer to start with the `EventProcessor<T>`, which was just released to preview, and extend it to better align with your scenarios.   For more context and detail, you may want to take a look at the [Event Processor Design](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/design/event-processor%7BT%7D-proposal.md) and, possibly, take a peek at the [`EventProcessorClient` source](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs) as a reference for building a custom processor layer.
