### ISSUE TITLE
[Tests:] Add test project/coverage to FormRecognizer solution

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10409]
Add test coverage for main scenarios:

- [x] ExtractReceipt
- [x] ExtractReceiptUri
- [x] ExtractLayout
- [x] ExtractLayoutUri
- [x] GetCustomModelsSummary
- [x] GetCustomModels
- [x] TrainCustomModel
- [x] ExtractCustomModelStream
- [x] ExtractCustomModelUri
- [x] ExtractCustomModelPlusOcrData
- [x] TrainCustomLabeledModel
- [x] ExtractCustomLabeledModel
- [x] ExtractCustomLabeledModelUri
- [x] ExtractCustomLabeledModelPlusOcrData
- [x] DeleteCustomModel

**Comment by maririos** [comment]
working on remaining test

**Comment by maririos** [comment]
Methods related to ExtractCustomLabeledModel have been added.
Will work on the remaining tomorrow

**Comment by maririos** [comment]
add delete model after creation

**Comment by maririos** [comment]
PR https://github.com/Azure/azure-sdk-for-net/pull/11481

**Comment by annelo-msft** [comment]
Excited to see all those boxes checked - awesome work, @maririos!!
