### ISSUE TITLE
Expose StorageConnectionString

### ISSUE THREAD

**Issue by MarcoScabbiolo** [Azure/azure-sdk-for-net#10416]
**Library or service name: `Azure.Storage.Common`**
 
**Is your feature request related to a problem? Please describe.**
When creating a SAS (without Active Directory) for a blob the account key is needed to create a `StorageSharedKeyCredential`. Most likely the account key will be retrieved from a connection string, and the SDK already has the means to parse this connections string and retrieve the `AccountKey` in `sdk/storage/Azure.Storage.Common/src/Shared/StorageConnectionString.cs`. The problem is this class is internal.

Can the class `StorageConnectionString` be exposed?

**Comment by brettcoburn** [comment]
Also need this, for the exact same reason. The AzureWebJobsStorage environment variable provides a connection string, but no account name or key.

As a workaround, it is possible to create an instance of CloudStorageAccount (from v11) to extract the connection string. The "Credentials" property contains a StorageCredentials object which has both an AccountName and an ExportKey() method.
