### ISSUE TITLE
[BUG][Storage][DataLake] Renaming directory where destination exists and has a file fails.

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#10425]
{"error":{"code":"DirectoryNotEmpty","message":"The recursive query parameter value must be true to delete a non-empty directory.\nRequestId:27edf887-201f-007f-5522-f6b0c4000000\nTime:2020-03-09T14:51:42.5358162Z"}}

Repo:
```
        [Test]
        public async Task RenameAsync_DestExistsAndHasFile()
        {
            await using DisposingFileSystem test = await GetNewFileSystem();

            // Arrange
            DataLakeDirectoryClient sourceDirectory = await test.FileSystem.CreateDirectoryAsync(GetNewDirectoryName());
            string destDirectoryName = GetNewDirectoryName();
            DataLakeDirectoryClient destDirectory = await test.FileSystem.CreateDirectoryAsync(destDirectoryName);
            await destDirectory.CreateFileAsync(GetNewFileName());

            // Act
            await sourceDirectory.RenameAsync(destinationPath: destDirectoryName);

            // Assert
            Response<PathProperties> response = await destDirectory.GetPropertiesAsync();
        }
```

**Comment by JimSuplizio** [comment]
Hi @seanmcc-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
