### ISSUE TITLE
ProjectReferences may break recorded tests when clients upgrade to new ServiceVersions

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#10432]
Based on [guidance from the arch board](https://github.com/Azure/azure-sdk/issues/1043), clients should default to the latest service version - even for service previews in preview package versions. However, when we convert PackageReferences to ProjectReferences, [this can cause test recordings to fail if](https://github.com/Azure/azure-sdk-for-net/pull/10395) clients and/or tests using other clients aren't passing an explicit service version to the appropriate client options.

To clarify, if, say, Identity SDK uses a ProjectReference to Key Vault SDK while Key Vault SDK is targeting a new service version that may not be available in all public clouds that Identity SDK may test, errors occur with live tests. Identity SDK recorded tests will also fail if they instrument a Key Vault SDK client because the recordings were likely on the last released service API version and not whatever Key Vault SDK may be working on currently.

**Comment by weshaggard** [comment]
While this might show its head with ProjectReferences and recordings right now as we chatted this is a larger potential issue were we need to be able to configure our client libraries and/or test environments align on the service version they are testing. We also end to determine if we want to or should be testing multiple service versions.

**Comment by heaths** [comment]
We may need to parameterize the api-version for recordings somehow - a mapping of sorts that works with the record look-up.

/cc @pakrym

**Comment by weshaggard** [comment]
FYI @JimSuplizio a scenario that you may need to support with the recording framework.
