### ISSUE TITLE
[CodeGen] Incorporate CodeGen fix for Pageables

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10457]
https://github.com/Azure/autorest.csharp/issues/474

Specifically in CustomFormClient.GetModels()

**Comment by kinelski** [comment]
Fixed in Core (empty string check below). There are no changes needed on the Form Recognizer side.
https://github.com/Azure/azure-sdk-for-net/blob/e241ebec248e50b67521134ac747b18ef7914533/sdk/core/Azure.Core/src/Shared/AutoRest/PageableHelpers.cs#L81
