### ISSUE TITLE
[BUG] Azure.Storage throws InvalidOperationException creating a container with error "Response was not set, make sure SendAsync was called"

### ISSUE THREAD

**Issue by drwill-ms** [Azure/azure-sdk-for-net#10476]
**Describe the bug**

I'm using the .NET Azure.Storage.Blobs SDK v12.3.0 to create a container and then do some other stuff. It works when I debug, but fails if I just let the test run.

**Expected behavior**

Does not fail or error is actionable. This sounds like an internal error, though.

**Actual behavior (include Exception or Stack Trace)**

Message: 
    Test method Microsoft.Azure.Devices.E2ETests.RegistryManagerImportDevicesTests.RegistryManager_ImportDevices threw exception: 
    System.InvalidOperationException: Response was not set, make sure SendAsync was called
  Stack Trace: 
    HttpMessage.get_Response()
    TypedFetchProperty`2.Fetch(Object obj)
    TransformSpec.Morph(Object obj)
    FilterAndTransform.Morph(Object args)
    <.ctor>b__2(KeyValuePair`2 evnt)
    CallbackObserver`1.OnNext(T value)
    DiagnosticListener.Write(String name, Object value)
    DiagnosticSource.StartActivity(Activity activity, Object args)
    RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
    BufferResponsePolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
    LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
    LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
    HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
    HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
    RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
    RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
    HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
    HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
    Container.CreateAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, PublicAccessType access, String version, Nullable`1 timeout, IDictionary`2 metadata, String requestId, String defaultEncryptionScope, Nullable`1 denyEncryptionScopeOverride, Boolean async, String operationName, CancellationToken cancellationToken)
    BlobContainerClient.CreateInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken, String operationName)
    BlobContainerClient.CreateAsync(PublicAccessType publicAccessType, IDictionary`2 metadata, CancellationToken cancellationToken)
    BlobServiceClient.CreateBlobContainerAsync(String blobContainerName, PublicAccessType publicAccessType, IDictionary`2 metadata, CancellationToken cancellationToken)

**To Reproduce**

I'm writing an integration test for Azure IoT Hub service SDK. I need to create a container and produce a SAS URI to pass to IoT hub to run a job. I've created this class to create the container, give me a SAS URI, and clean up on `Dispose()`.

```c#
using System;
using System.Threading.Tasks;
using Azure;
using Azure.Storage;
using Azure.Storage.Blobs;
using Azure.Storage.Sas;

namespace Microsoft.Azure.Devices.E2ETests.Config
{
    /// <summary>
    /// Creates a storage container for your use for the lifetime of this class
    /// </summary>
    public class StorageContainer : IDisposable
    {
        private bool _disposed = false;
        private BlobServiceClient _blobServiceClient;

        public string ContainerName { get; }
        public Uri SasUri { get; private set; }
        public BlobContainerClient BlobContainerClient { get; private set; }

        private StorageContainer(string containerName)
        {
            if (string.IsNullOrWhiteSpace(containerName))
            {
                containerName = Guid.NewGuid().ToString();
            }

            ContainerName = containerName;
        }

        public static async Task<StorageContainer> GetInstanceAsync(string containerName = null)
        {
            var sc = new StorageContainer(containerName);
            await sc.InitializeAsync().ConfigureAwait(false);
            return sc;
        }

        public void UpdateSasUri(DateTimeOffset? expiresOn = null)
        {
            var constraints = new AccountSasBuilder
            {
                Services = AccountSasServices.Blobs,
                ResourceTypes = AccountSasResourceTypes.Service | AccountSasResourceTypes.Object,
                StartsOn = DateTimeOffset.UtcNow,
                ExpiresOn = expiresOn ?? DateTimeOffset.UtcNow.AddHours(1),
                Protocol = SasProtocol.Https,
            };
            constraints.SetPermissions(AccountSasPermissions.All);

            var credential = new StorageSharedKeyCredential(Configuration.Storage.Name, Configuration.Storage.Key);

            var sasUri = new UriBuilder(BlobContainerClient.Uri)
            {
                Query = constraints.ToSasQueryParameters(credential).ToString(),
            };
            SasUri = sasUri.Uri;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        protected virtual void Dispose(bool disposing)
        {
            if (_disposed)
            {
                return;
            }

            if (disposing
                && _blobServiceClient != null)
            {
                if (!string.IsNullOrWhiteSpace(ContainerName))
                {
                    BlobContainerClient.Delete();
                }

                BlobContainerClient = null;
                _blobServiceClient = null;
            }

            _disposed = true;
        }

        private async Task InitializeAsync()
        {
            _blobServiceClient = new BlobServiceClient(Configuration.Storage.ConnectionString);

            Response<BlobContainerClient> result = await _blobServiceClient
                .CreateBlobContainerAsync(ContainerName)
                .ConfigureAwait(false);
            BlobContainerClient = result.Value;

            UpdateSasUri();
        }
    }
}
```

**Environment:**

 - Azure.Storage.Blobs 12.3.0
 - Windows 10, netcoreapp2.1
 - VS2019 16.4.5

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.803 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pakrym** [comment]
Is there anything special about your enviroment? It seems that diagnostic source event source is on judging by the stack trace.

**Comment by drwill-ms** [comment]
When running tests, we have an EventListener running with a filter on for the following types:

- DotNetty-Default*
- Microsoft-Azure-*

**Comment by pakrym** [comment]
I think you end up enabling the https://github.com/dotnet/runtime/blob/master/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs#L148

And DiagnosticSourceEventSource is pulling on the Response property of HttpMessage that doesn't have a valid value at that moment and the getter throws.

**Comment by drwill-ms** [comment]
When I disable our EventListener, the bug does not reproduce, so that is good as a temporary work around.

I'm not clear if this is a bug in storage or in System.Diagnostics. What do you think is the long-term solution?

**Comment by pakrym** [comment]
What event listener does is pulling on random properties of objects it finds in diagnostic source parameters, I don't think it's generally safe.

I'm not sure if DiagnosticSourceEventSource has a way to opt out some DiagnosticSources or object properties but that may be a more long-term solution.

**Comment by pakrym** [comment]
I think this would end up being a dotnet core fix.

**Comment by pakrym** [comment]
Fixed in https://github.com/dotnet/runtime/pull/49567

**Comment by fakhrulhilal** [comment]
> When I disable our EventListener, the bug does not reproduce, so that is good as a temporary work around.
> 
> I'm not clear if this is a bug in storage or in System.Diagnostics. What do you think is the long-term solution?

Can you tell me how to disable EventListener. I have same problem too with .NET core 3.1. Upgrading is not an option at the moment.
