### ISSUE TITLE
Clients should not implement IAsyncDisposable

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#10472]
We expect the clients to be long-lived and we want to avoid having VS encourage users to create them in Using blocks.
We should still leave in the DisposeAsync method in case we change our mind in the future. We can remove the CloseAsync methods.

**Comment by pakrym** [comment]
This would make them not play nicely with things like dependency injection containers.

**Comment by JoshLove-msft** [comment]
Thanks, that is a great point. @nemakam @KrzysztofCwalina I wonder if this concern is enough to cause us to rethink this approach. Also, curious if there is BCL guidance around whether IDisposable should be avoided for types that are singletons?

**Comment by KrzysztofCwalina** [comment]
@pakrym, can you elaborate? Which containers support this interface? When do they call it? What happens if they don't dispose?

Also, does static analysis in VS flags all IAsyncDisposalbes that are not wrapped transitively, just like it does for IDisposable?

**Comment by pakrym** [comment]
> @pakrym, can you elaborate? Which containers support this interface? When do they call it? What happens if they don't dispose?

ASP.NET Core DI supports both IDisposable and IAsyncDisposable, it disposes instances created by the container when container itself is being disposed or the child scope is disposed for scoped services. 

> Also, does static analysis in VS flags all IAsyncDisposalbes that are not wrapped transitively, just like it does for IDisposable?

I've never seen a rule like this even for IDisposable if you are not using StyleCop/FxCop.

**Comment by KrzysztofCwalina** [comment]
@pakrym, in this case I think we should implement the interface on clients. @JoshLove-msft, do you remember who raised this concern originally?

**Comment by pakrym** [comment]
> @pakrym, in this case I think we should implement the interface on clients. @JoshLove-msft, do you remember who raised this concern originally?

I don't care as much about http-based clients because they mostly reuse the same underlying HttpClient, but in case of SB every client creates a bunch of it's own resources.

**Comment by JoshLove-msft** [comment]
Yes, I believe it was @nemakam that raised the concern.

**Comment by nemakam** [comment]
This could be stylecCopy/FxCop + Resharper issue. But it might still have some impact.
But if this causes issues with DI containers, then I'd agree the lesser of the two evils would be to add the interface back. 

Do we know if there's any other way to work with DI containers to mitigate this problem?

**Comment by pakrym** [comment]
We've never got a request to support duck typing Disposable-like types when working on Microsoft.Extensions.DependencyInjection but I think it would take very long time to get covered in popular DI containers.
