### ISSUE TITLE
[Documentation:] Complete FormRecognizer README

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10483]
Updated Description:
- [ ] Check that links are working
- [x] Add section header for Package Installation
- [x] Add Troubleshooting section
- [x] Add Next Steps Section
- [ ] Complete list of links at the top
- [x] Reduce to one training sample
--

Was:

Fill out remaining required sections.

Add concepts for:
- OCR Results/TextElements
- Confidence
- Bounding Box

Update receipt sample such that return result is called `receiptCollection`.

Call out `GetFieldValues` in a sample.

Compare/contrast `LayoutClient` and `CustomModelClient`

Call out where models are already trained and don't need to train a model to use them.

**Comment by annelo-msft** [comment]
Priority: initial draft before UX study

**Comment by maririos** [comment]
Sections to add:
- Install package with version
- Troubleshooting
- Next steps (links to samples)

**Comment by annelo-msft** [comment]
Update to description: 

> Call out `GetFieldValues` in a sample.
> Compare/contrast `LayoutClient` and `CustomModelClient`
 
`GetFieldValues` is no longer there, but `Fields.TryGetValues()` should be illustrated in a sample.
`LayoutClient` and `CustomModelClient` are now both on `FormRecognizerClient` - instead of compare/contrast these clients, compare/contrast `StartRecognizeContent` with `StartRecognizeCustomForm` -- the latter adds a layer of semantic information over OCR.

**Comment by maririos** [comment]
@annelo-msft do you know if the any of the other languages already has a complete Readme we can use as a base?

**Comment by iscai-msft** [comment]
Python's is decently fleshed out: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/README.md

**Comment by annelo-msft** [comment]
@mayurid @czubair
