### ISSUE TITLE
Set Confidence to 1.0 when the service does not return it.

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10490]
From the APIView:

ctstone1 day ago
Getting 0 confidence on table cells, but this should be null since it is not returned by Layout.

**Comment by annelo-msft** [comment]
Prioritize for UX study

**Comment by annelo-msft** [comment]
@ctstone, it looks like table cell confidence is a required field in the swagger file, so it wouldn't make sense that it would be nullable.  Can you help me understand this better?

**Comment by ctstone** [comment]
Yep, you're right. Confidence is a required field. I'll try to find out why this isn't being returned from Layout.

**Comment by annelo-msft** [comment]
Action pending resolution on Teams thread:
https://teams.microsoft.com/l/message/19:88f2d9dea2344075b5d4bc34d82a3d1c@thread.skype/1586389362256?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1586389362256&teamName=Azure%20SDK&channelName=Service%20-%20Form%20Recognizer&createdTime=1586389362256

@bojunehsu

**Comment by annelo-msft** [comment]
Per #10378, we will set Confidence to 1.0 when the service does not return it.

**Comment by maririos** [comment]
Ensure we do this through the API
