### ISSUE TITLE
Microsoft.Azure.Management.EventHub to support Data Lake capture description

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-sdk-for-net#10509]
Library: Microsoft.Azure.Management.EventHub

Current Event Hubs management library supports Azure Storage only as capture destination. Please consider to support for Azure Data Lake as well.

See ARM template here - https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-resource-manager-namespace-event-hub-enable-capture#resources-to-deploy-for-azure-data-lake-store-as-destination

**Comment by vamathan** [comment]
Hi Azure EventHub Management Team,
 
Please let know the ETA on this, if possible.

Found Related Issues in Github, raised by others :
1.	https://github.com/Azure/azure-rest-api-specs/issues/2255 on azure rest api eventhub
2.	https://github.com/Azure/azure-sdk-for-python/issues/7231 on azure sdk for python

**Comment by nickzhums** [comment]
@vamathan Looks like the properties are not present in the swagger, please use this issue to track the swagger change:
https://github.com/Azure/azure-rest-api-specs/issues/2255

**Comment by samuelkoppes** [comment]
Capture now supports Azure Data Lakes as a destination.
