### ISSUE TITLE
[BUG] Cannot send to ServiceBus Queue in state ReceiveDisabled

### ISSUE THREAD

**Issue by sebader** [Azure/azure-sdk-for-net#10535]
**Describe the bug**
From this [SO ](https://stackoverflow.com/questions/60634913/microsoft-azure-servicebus-messagingentitydisabledexception-receivedisabled)question.

When you set a ServiceBus queue to `ReceiveDisabled` you cannot send messages to it using the .NET SDK. You get the error

> Microsoft.Azure.ServiceBus.MessagingEntityDisabledException: 'Messaging entity 'sb://xxx.servicebus.windows.net/xxxx' is currently disabled. 

If you put it to `SendDisabled` you get the correct error:

> Microsoft.Azure.ServiceBus.MessagingEntityDisabledException: 'Messaging entity 'xxxxx:Queue:demofunctionqueue' is currently disabled for Send operations. 

**Expected behavior**
In state `ReceiveDisabled` you should still be able to send messages as stated [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.entitystatus?view=azure-dotnet)

**Actual behavior (include Exception or Stack Trace)**
See above.

**Interesting fact: In ServiceBusExplorer I still can send a message in state ReceiveDisabled. <s>So there might be a SDK issue here rather than an issue in SB itself.</s>**

**//Edit: It also works correctly when I use the REST API (using Postman) and SAS token.**

**To Reproduce**
````
            var cs = "Endpoint=sb://...";
            var queueName = "demofunctionqueue";

            var serviceBusManagementClient = new ManagementClient(cs);
            var queues = await serviceBusManagementClient.GetQueuesAsync();
            foreach (var queueItem in queues)
            {
                Console.WriteLine($"Disabling {queueItem.Path}");
                queueItem.Status = EntityStatus.ReceiveDisabled;
                await serviceBusManagementClient.UpdateQueueAsync(queueItem);
            } 

            var messageSender = new MessageSender(cs, queueName);
            var message = new Message(Encoding.UTF8.GetBytes("hello"));
            await messageSender.SendAsync(message);
````

**Environment:**
 - .NET Core 3.1
- Microsoft.Azure.ServiceBus 4.1.2

**Comment by SeanFeldman** [comment]
Isn't this a broker issue, i.e. https://github.com/Azure/azure-service-bus/

**Comment by sebader** [comment]
I haven’t tried any other SDK, but since plain http is working correctly, it might be, yes. 
Is there an easy way to move an issue to a different repo?

**Comment by nemakam** [comment]
Yeah we will have to evaluate if its a client side issue or backend. Thanks for reporting this. We will investigate and get back to you..

**Comment by sebader** [comment]
Any update on this? Thanks!

**Comment by yvgopal** [comment]
This is service bug. Just fixed. It will be rolled out to production over the next month. We have reduced the frequency of deployments during this COVID-19 lockdown.

**Comment by Magnus12** [comment]
@yvgopal  By service bug do you mean that we need to update the client library or not? And in that case which client and version will the fix be in?

**Comment by SeanFeldman** [comment]
@Magnus12 I think what it means is that there shouldn't be any client change. The broker/back-end/service-side is patched and the client SDK will just work.
