### ISSUE TITLE
[Samples] Provide samples for using table cells in a common UI framework

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10537]
## Summary

Given the design of a table indexer (for https://github.com/azure/azure-sdk-for-net/issues/9975), we'll want to provide a sample showing how it should be used, which illustrates any semantics that are not intuitive.

**Comment by maririos** [comment]
Because this depends on design, we decided to close this issue and whenever the feature is implemented consider adding a sample
