### ISSUE TITLE
[BUG]DefaultAzureCredentials is not working

### ISSUE THREAD

**Issue by mymatrixpixel** [Azure/azure-sdk-for-net#10543]
Hi Team,

I ave environment variables updated in my Azure VM and have it in .env file along with project.

if i try to access Azure key vault by using below code and keep getting invalid request.

var secretclient = new SecretClient(
new Uri("keyvaulturl"),  
new DefaultAzureCredentials()
};

var clientid = await secretclient.GetSecretAsync("someid); //here am keep getting unauthorized- 401 error.

Please let me know, what i am doing wrong.

Thanks

**Comment by mymatrixpixel** [comment]
@jongio Can you help?

**Comment by jongio** [comment]
Did you give the SP perms to keyvault?

https://docs.microsoft.com/en-us/azure/key-vault/key-vault-manage-with-cli2#authorizing-an-application-to-use-a-key-or-secret

**Comment by mymatrixpixel** [comment]
Yes, I have access.  One more point- i have logged in with different mail id in VS2019. But i whever if i access #ADF i use different mail id and password. So here is my uestion DefaultAzureCredentials will take it from environment system variables or .env file?

**Comment by jongio** [comment]
In order to use .env values you have to load the file with DotNetEnv or similar package. 

DAC will use env vars, then managed identity, then VS. 

If you have multiple accounts then you can set the AZURE_USERNAME env var to the desired account.

**Comment by mymatrixpixel** [comment]
I already set the username and password in my VM system variables, but still am facing issue.

**Comment by mymatrixpixel** [comment]
service request failed.
status :401 (unauthorized)
message : AKV10032 : invalid issuer.

**Comment by jongio** [comment]
Please try setting the tenant id in AZURE_TENANT_ID that the keyvault is in versus the tenant Id that the SP is in.

**Comment by mymatrixpixel** [comment]
@jongio I have fixed the issue. azure key vault is mapped into different tenant I'd. Now am all set and verified its working as expected
