### ISSUE TITLE
[BUG] Tags can't be set on ImportCertificateOptions 

### ISSUE THREAD

**Issue by mark-szabo** [Azure/azure-sdk-for-net#10580]
**Describe the bug**
The Tags property is read-only on ImportCertificateOptions, although it should not be.

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/ImportCertificateOptions.cs

**Expected behavior**
Tags can be set.

**Actual behavior (include Exception or Stack Trace)**
Tags can't be set.
`Property or indexer 'ImportCertificateOptions.Tags' cannot be assigned to -- it is read only`

**To Reproduce**
```csharp
var options = new ImportCertificateOptions(certificateName, x509CertificateWithPrivateKey.Export(X509ContentType.Pfx));
options.Tags = new Dictionary<string, string>
    {
        { "Hostname", record.Hostname }
    };
```

**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Certificates 4.0.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c
```
 - IDE and version : Visual Studio 16.4.6

**Comment by wantedfast** [comment]
Hi @mark-szabo ,
, 
Yes, Tags is a read only properly. But it can be changed in this way:
```
ImportCertificateOptions options = new ImportCertificateOptions(<CertificateName>,<CertificateBytes>);
options.Tags.Add("Hostname",record.Hostname);
```

Please feel free to reach us if if you need more than this. 
@jongio

**Comment by mark-szabo** [comment]
Hi @wantedfast, ahh, I see.

Can you please add something like this to the documentation of the `ImportCertificateOptions` class?

```csharp
/// <example>
/// var options = new ImportCertificateOptions(name, certificate);
/// options.Tags.Add("MyTag", tagValue);
/// </example>
```

**Comment by jongio** [comment]
@heaths - Can you have a look and determine if this is something we want to add to docs?

**Comment by heaths** [comment]
We can add examples, yes. Some of our samples show the collection initialization pattern below.

Ideally, you can use collection initialization that calls `Add` for you in a syntax you were using originally - just don't instantiate the object.

```csharp
var options = new ImportCertificateOptions(certificateName, x509CertificateWithPrivateKey.Export(X509ContentType.Pfx))
{
  Tags =
    {
        { "Hostname", record.Hostname }
    }
};
```

In general, collection / dictionary properties aren't settable, following .NET guidelines. Settable often implies they can be null vs. just empty, which starts creating all sorts of branches in code.

**Comment by heaths** [comment]
As for where to put this, maybe call it out better in the samples. This applies to *all* our collection properties.

**Comment by mark-szabo** [comment]
@heaths I'd add it to the XML comments, that's where I search for usage info. Or that can be only me, I don't know. 🤷‍♂️🙂
