### ISSUE TITLE
Azure.Search: Ensure input and output document order is in sync while batching

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#10593]
We need to add (performant) checks that the document order is maintained so customers can just index into the results safely.

**Comment by AlexGhiondea** [comment]
Do we know if this is supported by the service already (ie. is there already an expectation that the documents will come out in the same order?)

**Comment by brjohnstmsft** [comment]
@AlexGhiondea It may work by accident, but it's not part of our public contract so there's no guarantee.

**Comment by tg-msft** [comment]
Moving to the backlog because we don't have enough information today to determine the "key" column of a document.  We _might_ at some point in the future when we add FieldBuilder.  Until then folks will have to map `string Key` to their documents by hand if they want to be paranoid about response ordering.

**Comment by AlexGhiondea** [comment]
Closing for now.
