### ISSUE TITLE
Unify on Azure.Core spatial types

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#10592]
We need a set of common spatial types in Azure.Core.  Cosmos has started adding its own for Track 2.  Search and Tables Track 1 used https://www.nuget.org/packages/Microsoft.Spatial/.

I'd advocate for lifting what Cosmos has into the next release of Azure.Core if everyone agrees.

**Comment by tg-msft** [comment]
FYI:
- @mayurid and @KrzysztofCwalina for Cosmos
- @pakrym for Tables
- @heaths and @brjohnstmsft for Search on .NET
- @sima-zhu for Search on Java

**Comment by pakrym** [comment]
A prototype of spatial type is in API review https://apiview.dev/Assemblies/Review/3f640270a7de4d8e99a5543bf4257e4f

**Comment by heaths** [comment]
Thanks. I left a few comments.

**Comment by pakrym** [comment]
Types are merged to a new Azure.Core.Experimental project.

**Comment by heaths** [comment]
What's the expected timeframe for types to move from Core.Experimental to Core? Search is nearing GA, so before then?

**Comment by pakrym** [comment]
Yes, but we should validate if it fits all search/cosmos scenarios first.

**Comment by tg-msft** [comment]
We've shipped this in Search so I'm removing it from our epic.  Feel free to close the issue unless you want it for tracking.

**Comment by pakrym** [comment]
Keeping this for tracking, will close when types ship in Azure.Core.
