### ISSUE TITLE
Resource Manager - ResourceOperations.List - paging/nextLink bug

### ISSUE THREAD

**Issue by divyakgupta** [Azure/azure-sdk-for-net#1059]
The response from the ResourceOperations.List method is supposed to include the nextLink to get the next page of results. This value is always null, because the code is looking at "$odata.NextLink" to get the nextLink string, but it's actually sent as "nextLink". Paging for resources is essentially broken in ResourceManagementClient due to this issue. (Probably applies to other List operations like ResourceGroups, etc. as well)

**Comment by ravbhatnagar** [comment]
Please let us know if this is still an issue. This should already be fixed.
