### ISSUE TITLE
Azure.Search: Determine the correct approach for nested SearchErrors

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#10598]
The swagger includes nested errors as details and we should determine how we want to expose them.

**Comment by tg-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/src/Utilities/ClientDiagnostics.ExtractFailureContent.cs#L52

and 

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/search/data-plane/Azure.Search/preview/2019-05-06-preview/searchindex.json#L1377

**Comment by tg-msft** [comment]
The service is working these out now.  We'll probably have to put this in `additionalInfo` but will circle back in a preview or two.

**Comment by Mohit-Chakraborty** [comment]
Example of an error that triggers this assert -
```
{
"error":
{
  "code":"InvalidRequestParameter",
  "message":"Failed to parse query string at line 1, column 8. See https://aka.ms/azure-search-full-query for supported syntax.",
  "details":
    [
    {"code":"InvalidSearchSyntax",
     "message":"Failed to parse query string at line 1, column 8. See https://aka.ms/azure-search-full-query for supported syntax."
    }
    ]
}
}
```

**Comment by Mohit-Chakraborty** [comment]
This is also causing the same 8 test failures in Search weekly tests where the tests expects a particular exception to be thrown but the assert fires instead.
Here is [a sample run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=809143&view=logs&j=68082d65-ebf7-5f3f-494d-d3fd09e80dd6&t=6f6444ca-c101-5878-5224-de85502bb056).

**Comment by AlexGhiondea** [comment]
@Mohit-Chakraborty anything else left for us to do here?

**Comment by Mohit-Chakraborty** [comment]
I see there has been a reformatting of code and we have removed the custom code in favor of using the common impl from `Azure.Core`.
The assert calling out the problem [does not exist](https://github.com/Azure/azure-sdk-for-net/blob/7aa2ff58616865a4431f2046a42e29eaf3448aeb/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs#L45) in this version.

I thought we still need a way to agree on how to surface nested errors. I will follow-up on it.

**Comment by pallavit** [comment]
@ShivangiReja I believe we can close this issue as not planned. Please feel free to open if you feel otherwise. /cc: @tg-msft as FYI.
