### ISSUE TITLE
Azure.Search: Fix IndexDocuments merge with static documents test from Track 1

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#10602]
This is the only disabled test from the Track 1 suite relative to Preview 1 features.

**Comment by tg-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Microsoft.Azure.Search/tests/Tests/IndexingTests.cs#L846

**Comment by tg-msft** [comment]
Track 1 isn't serializing nulls to the wire based on serializer settings.  We can revisit this once we add that level of serialization option customization in Track 2.

**Comment by AlexGhiondea** [comment]
@tg-msft can this be closed now?

**Comment by tg-msft** [comment]
No, we've still got a bunch of commented out Track 1 tests that were never fixed after we started properly supporting ObjectSerializer.

**Comment by pallavit** [comment]
@tg-msft can this be closed now considering track1 SDK has been deprecated.

**Comment by tg-msft** [comment]
No, this is about adding Track 1 test cases to Track 2.  See https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/tests/DocumentOperations/IndexingTests.cs#L1014

**Comment by pallavit** [comment]
@ShivangiReja I am closing this issue as not planned given our priorities, feel free to reopen if you feel otherwise.
/cc: @tg-msft as FYI
