### ISSUE TITLE
WindowsAzure.Storage.Table expects OData 5.6.2 - error when using 5.6.3

### ISSUE THREAD

**Issue by dcinzona** [Azure/azure-sdk-for-net#1061]
We have a project that requires OData 5.6.3 and azure table storage.  Whenever we try to call methods against ATS, we get the following error: 
`Microsoft.WindowsAzure.Storage.StorageException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.2.0, Culture=neutral`
Our project references 5.6.3 and the nuget package for Azure Storage states >= 5.6.2 (so we assume 5.6.3 should work). 

Any idea as to why theres an error and why the table client is expecting 5.6.2?

**Comment by brondavies** [comment]
:+1:

**Comment by brondavies** [comment]
The pre-release nuget package for WindowsAzure.Storage that supports OData > 5.6.2 also cannot install if 5.6.3 is referenced 
```
PM> Install-Package WindowsAzure.Storage -Version 4.3.2-preview -Pre
Attempting to resolve dependency 'Microsoft.Data.OData (≥ 5.6.2)'.
Attempting to resolve dependency 'System.Spatial (= 5.6.3)'.
Attempting to resolve dependency 'Microsoft.Data.Edm (= 5.6.3)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 5.0.8)'.
Attempting to resolve dependency 'Microsoft.Data.Services.Client (≥ 5.6.2)'.
Attempting to resolve dependency 'Microsoft.Data.OData (= 5.6.2)'.
Install-Package : Already referencing a newer version of 'Microsoft.Data.OData'.
```

**Comment by veena-udayabhanu** [comment]
Sorry for the late response. Azure Storage SDK has been moved to - https://github.com/Azure/azure-storage-net/ and we regularly monitor that repository for issues. Please report new issues on that repository going forward. Regarding this issue, how did you install the Storage SDK? If you installed it from Nuget, then Nuget should have already taken care of adding the required binding redirects. Can you please confirm that these exist in your application config? Thank you!

**Comment by dcinzona** [comment]
This has been resolved for me.  Closing the issue

**Comment by rshirani** [comment]
Hi guys, I hit this issue. I am also in a situation that I do not want to use assembly binding. My question is why having storage sdk 4.3 does not work with Microsoft.Data.OData 5.6.2.0. 

[Exception: Microsoft.WindowsAzure.Storage.StorageException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 

In https://www.nuget.org/packages/WindowsAzure.Storage/4.3.0, it mentions Microsoft.Data.OData (>= 5.6.2). 

Why does not this work for me?
