### ISSUE TITLE
Expose AnalyzeResult Errors

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10625]
Per [internal Teams discussion](https://teams.microsoft.com/l/message/19:88f2d9dea2344075b5d4bc34d82a3d1c@thread.skype/1586796047400?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1586796047400&teamName=Azure%20SDK&channelName=Service%20-%20Form%20Recognizer&createdTime=1586796047400), we'll throw RequestFailedException when errors come back in AnalyzeResult.Errors for Preview 1 and re-evaluate based on further information from the service team about errors and the documents that generate them, as well as customer feedback.

**Comment by annelo-msft** [comment]
@ctstone , @bojunehsu , @maririos

**Comment by bojunehsu** [comment]
When users analyzes a multi-page PDF, it is possible that only 1 page failed.  In such case, I believe the current behavior is to return the results for the remaining pages and add an error message for the page that failed.  If we throw, the user loses the ability to examine the rest of the processed results.  Since I believe we currently bill customers in this case, it would be even more frustrating not to be able to access any of the results.  @ctstone Can you please correct any of my misunderstanding?

**Comment by maririos** [comment]
FYI @kristapratico

**Comment by kristapratico** [comment]
@bojunehsu could we possibly get a sample form like you described that would generate a page-based error and return the successfully processed results? This would really help us design how to expose errors for the SDKs.

**Comment by bojunehsu** [comment]
[ErrorPdf.pdf](https://github.com/Azure/azure-sdk-for-net/files/4490639/ErrorPdf.pdf)
Untested, but this file should trigger the error conditions described above.  Specifically, the first page is okay, but the second page has dimension outside the supported range.  Even if it doesn't trigger errors today, we may modify the implementation to behave that way in the future.

**Comment by annelo-msft** [comment]
For Preview 1, we will throw an exception when LRO.Status == failed, and if LRO.Status == succeeded, return AnalyzeResult equivalent with no errors on it.  Per discussions with the service team, we are not currently aware of any cases when the LRO.Status is succeeded and AnalyzeResult.Errors is populated with values.

Thanks to everyone who contributed to this investigation!  @kristapratico, @ctstone, @bojunehsu

**Comment by kinelski** [comment]
Fixed by #11460.
