### ISSUE TITLE
[BUG] Memory Leaking When SDK Combined With Application Insights

### ISSUE THREAD

**Issue by speedy-ms** [Azure/azure-sdk-for-net#10626]
**Describe the bug**
When using the **Azure.Storage.Queues** (v 12.3.0) NuGet package in combination with **Microsoft.ApplicationInsights.AspNetCore** (v 2.13.1) in a .Net core 3.1 application that is constantly polling queues for new messages, we find that the number of objects built up in memory is steadily increasing, specifically:

`Microsoft.ApplicationInsights.DependencyCollector.Implementation.AzureSdkDiagnosticsEventHandler` - creating about 5000 objects a minute and the garbage collector is not disposing them.

**Expected behavior**
That the AI objects would be cleaned up by the GC

**Actual behavior (include Exception or Stack Trace)**
Eventually the app will start throwing OutOfMemoryExceptions.

**To Reproduce**

1. Have the following in your app startup:

```csharp
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddApplicationInsightsTelemetry();
        }
```
2. Add a hosted service:
```csharp

            var host = new WebHostBuilder()
                .UseKestrel()
                .ConfigureServices(c => c.AddHostedService<QueueWorker>())
```
3. Have the worker constantly new up a `QueueClient` to check for queue messages.

**Environment:**
 - Azure.Storage.Queues 12.3.0
 - .NET runtime version 3.1.101
 - IDE and version : Visual Studio Professional v 16.4.5

**Comment by seanmcc-msft** [comment]
For step 3, why not have the worker re-use the same QueueClient?  The clients are thread-safe.

**Comment by speedy-ms** [comment]
That has proven to be the workaround we have gone with - storing any queue clients that we have created in a static dictionary that remains for the lifetime of the app (we have a web app that uses this shared code and would be newing up the clients pretty heavily to create queue messages).

I will leave it open and for others to decide if this is a bug that needs fixing or if it was simply of a case of us "using it wrong" in which case it can be closed.

**Comment by Petermarcu** [comment]
We're tracking getting this documented for all clients in this issue. https://github.com/Azure/azure-sdk-for-net/issues/8941.

**Comment by jesuissur** [comment]
Hi there

We understand the recommended way is to use a single client though isn't still a bug having a memory leak because many clients are created?

In our specific case, we created a lot of clients for an hour or so at night and the memory is never release even days after.

We will use a single client in the future, so thanks to @speedy-ms 

Thanks
Phil
