### ISSUE TITLE
[QUERY] Getting the error "The type or namespace name 'Identity' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?)"

### ISSUE THREAD

**Issue by jpsaikia** [Azure/azure-sdk-for-net#10630]
**Query/Question**
Getting the error "The type or namespace name 'Identity' does not exist in the namespace 'Microsoft.Azure' (are you missing an assembly reference?)". 

**Environment:**
 - Azure.Identity [1.1.1]
 - Azure.Messaging.EventHubs [5.0.1]
 - Azure.Security.KeyVault.Secrets [4.0.2]
 - Project TargetFramework - netstandard2.1
 - IDE VS2019 (16.4.6)

**Other notes**
If I remove the package "Azure.Messaging.EventHubs", the types are recognized. 
Drilled down to the dependencies for the EventHubs package and saw that it has a dependency on Microsoft.Azure.Amqp [2.4.2] . If I remove EventHubs package and directly refer this Amqp package, the same issue happens.
Actually after adding the Amqp package, the project can find only Azure.Amqp namespace. It cannot find any other namespace under Azure.

Is there any conflict with the package versions?
 
**Packages**
![image](https://user-images.githubusercontent.com/3803609/76758809-7c90f080-67b0-11ea-8d37-19834ede5a12.png)

**Error**
![image](https://user-images.githubusercontent.com/3803609/76758990-c8dc3080-67b0-11ea-8435-17d47463749e.png)

**Comment by jsquire** [comment]
Hi @jpsaikia.  We're sorry that you're experiencing difficulties and appreciate you reaching out to let us know.  Unfortunately, I'm not able to reproduce the behavior that you're describing.   I've tried skeleton projects for a class library (netstandard2.1), a command line application (netcoreapp2.1), and an ASP.NET core application (netcoreapp2.1) with references to the Azure client libraries that you detailed.  In each case, I'm able to create a `SecresClient` and `EventHubProducerClient` using the `DefaultAzureCredential` and compile without issue.   _(I have not yet worked in the third party dependencies from your screenshot)_

Is there any there any other context that you're able to provide that may help us be able to reproduce, or would you be willing to share a sample project that suffers from this behavior?

//cc: @AlexGhiondea, @schaabs, @heaths

**Comment by jsquire** [comment]
I've Incorporated the non-SDK dependencies that appear in the screenshot, absent the `Validation` item, and was able to compile the class library and console application projects without issue.   

```xml
 <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.1.1" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.0.1" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.0.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.1.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.0.601" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```

The ASP.NET Core application has two version conflicts with the `Microsoft.Extension.Options` package:

```
Version conflict detected for Microsoft.Extensions.DependencyInjection.Abstractions. Install/reference Microsoft.Extensions.DependencyInjection.Abstractions 3.1.2 directly to project WebApplication1 to resolve this issue. 
 WebApplication1 -> Microsoft.Extensions.Options 3.1.2 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 3.1.2) 
 WebApplication1 -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.1.1 && < 2.2.0).
```
```
Version conflict detected for Microsoft.Extensions.Primitives. Install/reference Microsoft.Extensions.Primitives 3.1.2 directly to project WebApplication1 to resolve this issue. 
 WebApplication1 -> Microsoft.Extensions.Options 3.1.2 -> Microsoft.Extensions.Primitives (>= 3.1.2) 
 WebApplication1 -> Microsoft.AspNetCore.App 2.1.1 -> Microsoft.Extensions.Primitives (>= 2.1.1 && < 2.2.0).
```

Once I added the recommended packages, I was able to compile, albeit with dependency warnings.

```xml
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.1.1" />
    <PackageReference Include="Azure.Messaging.EventHubs" Version="5.0.1" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.2" />
    <PackageReference Include="Microsoft.Extensions.Primitives" Version="3.1.2" />
    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.1.2" />
    <PackageReference Include="StackExchange.Redis" Version="2.0.601" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
```

**Comment by jpsaikia** [comment]
I tried with a skeleton solution\project and strangely it worked. I suppose something to do with VS. or cache.

**Comment by jpsaikia** [comment]
Alright. Looks like found the issue. This was for a MS LOB application.
Repro step - 
Include nuget - Microsoft.Azure.Amqp
Edit the namespace as Microsoft.xxxx.xxxx [Microsoft as the namespace first part]

**Comment by heaths** [comment]
What do you mean, "Edit the namespace as ..."? Can you clarify?

But it sounds like perhaps a dependency wasn't declared in a package and should've been, hence missing an assembly that declares a particular namespace (or perhaps more than 1 assembly).

**Comment by jsquire** [comment]
I'm not sure that I'm following your repro steps properly.   I've removed the Event Hubs package, which has a dependency on the `Microsoft.Azure.Amqp` package and changed it out for a direct reference to `Microsoft.Azure.Amqp` and am still able to browse the namespace of `Azure.Identity` and `Azure.Security.Keyvault` without issue in Intellisense as well as compile.

May I ask what your `using` directives look like?  I wonder if there's an alias that is potentially confusing things.   I've tried adding the AMQP namespaces as well as a top-level alias _(both at the beginning and end of the `using` declarations)_ and am not able to trigger the behavior:

```csharp
using System;
using Azure.Identity;
using Azure.Security.KeyVault.Secrets;
using Microsoft.Azure;
using Microsoft.Azure.Amqp;

using Azure = Microsoft.Azure;
```

**Comment by jpsaikia** [comment]
Here is the project configuration to repro - 

![image](https://user-images.githubusercontent.com/3803609/76821170-2618c600-6833-11ea-97e5-fbb26170a032.png)

This works fine with namespace "TestProject" -
![image](https://user-images.githubusercontent.com/3803609/76821233-56606480-6833-11ea-96e2-b67704ac44c3.png)

If I change the namespace to "Microsoft.TestProject", types under Azure are not recognized -
![image](https://user-images.githubusercontent.com/3803609/76821340-b0612a00-6833-11ea-97aa-a00ee875c49d.png)

**Comment by jsquire** [comment]
> If I change the namespace to "Microsoft.TestProject", types under Azure are not recognized -

Thank you for the additional context, @jpsaikia.  With that, I think the mystery is solved.  Because you're using `Microsoft` as a root to your namespace, it would appear that Visual Studio is scoping the intellisense lookup to that.  Since including `Microsoft.Azure.Amqp` into the mix defines an `Azure` namespace under your `Microsoft` root, VS is making the assumption that your references to `Azure` also start at that root unless you explicitly request that it start at a higher level by qualifying with `global::`.

Unfortunately, this is a tooling issue and not something that client libraries can influence, as far as I'm aware.

**Comment by jpsaikia** [comment]
Right. Most likely tools issue. Will check with the team.

**Comment by chlahav** [comment]
Another solution for this is to move the usings to be outside of the namespace section.
This way it will start the lookup the the global level by default and not inside the current namespace.
```cs
using Azure.Identity;

namespace Microsoft.TestObject
{
    ...
```

**Comment by srungta** [comment]
@chlahav I faced a similar issue today and your suggestion solved my error.
Do you know what difference does it make to keep the using inside and outside namespaces?
