### ISSUE TITLE
Need to update version of NETFramework references assemblies

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#10638]
https://github.com/Azure/azure-sdk-for-net/search?q=ReferenceAssemblies&unscoped_q=ReferenceAssemblies

You should update the version to 1.0.0 to fix the errors like:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2110,5): Warning MSB3245: Could not resolve this reference. Could not locate the assembly "System.Runtime". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
```

Example failing build https://dev.azure.com/azure-sdk/internal/_build/results?buildId=299596&view=logs&j=f4a2bb40-7e70-5f50-d570-7d7c5c8ca123&t=5f2c46ea-2ba4-5250-6248-51f1edb0a119

**Comment by ahamad-MS** [comment]
@isra-fel  .. This is blocking publishing any new nuget. Please treat this issue with highest priority

**Comment by isra-fel** [comment]
Thanks for the suggestion Wes! I'll submit a PR later
