### ISSUE TITLE
Make source parameter to StartTraining methods a URI instead of a string

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10643]
This should take a SAS URI to storage container holding training files.

Also: find a more descriptive name than `source`

Consider an overload that handles local filepaths for Docker containers.

**Comment by maririos** [comment]
>This should take a SAS URI to storage container holding training files.
Also: find a more descriptive name than source

Addressed in PR: https://github.com/Azure/azure-sdk-for-net/pull/11159

>Consider an overload that handles local filepaths for Docker containers.

Created separate issue: https://github.com/Azure/azure-sdk-for-net/issues/11229
