### ISSUE TITLE
Update list of allowed headers and parameters for Search

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#10647]
We need to update our list of headers and parameters we log. Note that `$select` is being discussed. We'll keep it for now.

**Allowed headers posted in Team channel:**
Accept
Access-Control-Allow-Credentials
Access-Control-Allow-Headers
Access-Control-Allow-Methods
Access-Control-Allow-Origin
Access-Control-Expose-Headers
Access-Control-Max-Age
Access-Control-Request-Headers
Access-Control-Request-Method
client-request-id (I suggest we ignore this and only offer x-ms-client-request-id as an option)
Content-Type
elapsed-time
If-Match
If-None-Match
Location
OData-MaxVersion
OData-Version
Origin
Prefer
request-id
return-client-request-id (prefer x-ms-return-client-request-id over this, once it's supported in a month or so)
throttle-reason
User-Agent
x-ms-client-request-id (prefer this over client-request-id)
x-ms-return-client-request-id (not supported yet; will be in a month or so)

_Originally posted by @sima-zhu in https://github.com/Azure/azure-sdk-for-java/issues/8686#issuecomment-598893765_

**Comment by tg-msft** [comment]
I think we've got all of these between https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search/src/SearchClientOptions.cs#L97 and https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/DiagnosticsOptions.cs#L24.

**Comment by heaths** [comment]
Yeah - most of them we have. There were a couple we didn't, including 1 or 2 that are coming soon but may as well add now. I just figured I'd post the whole list, sans "api-key" that shouldn't have been in the original list.

**Comment by heaths** [comment]
The only ones we were missing are added by Core, so .NET SDK is good here.
