### ISSUE TITLE
[BUG] DefaultAzureCredential cluttering log with errors

### ISSUE THREAD

**Issue by sebader** [Azure/azure-sdk-for-net#10659]
**Describe the bug**
I'm using this to access a blob container
`_blobContainerClient = new BlobContainerClient(new Uri(containerUrl), new DefaultAzureCredential());`

This is running in a container on AKS with Pod Identity - so ManagedIdentityCredential should be the one that is used. 

However, since this is only [second in the list,](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) the attempt to use EnvironmentCredential obviously fails. So far, so good. The issue is that it is not failing silently to the next one but instead cluttering my log (which I'm sending to Application Insights):

![image](https://user-images.githubusercontent.com/11445087/76864203-04cece80-6861-11ea-80bf-cc49dfc11962.png)

(disregard the 404 error for the blob. I'm checking if the blob does exist or not, so the 404 there is expected)

**Expected behavior**
When using DefaultAzureCredential I would expect that all options are silently being tried in their order. Only if all fail, I'd expect an exception to be thrown.

**Actual behavior (include Exception or Stack Trace)**
Error: 

> Azure.Identity.CredentialUnavailableException: EnvironmentCredential authentication unavailable. Environment variables are not fully configured. 

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Use DefaultAzureCredential() with a method that is not the first one in the list (EnvironmentCredential )

**Environment:**
 - Name and version of the Library package used: Azure.Identity 1.2.0-preview.1
 - Hosting platform or OS and .NET runtime version: .NET Core 3.1 in Linux Container on AKS
 - IDE and version : VS 16.4.6

Also a general question: If I know that I will be using Managed Identity, is it best practice to use that specifically instead of the DefaultCredential?

**Comment by schaabs** [comment]
@sebader Thanks for filing this issue. I'm looking into it now. I agree that the `DefaultAzureCredential` should not be logging errors for its normal operation, and I'm investigating how we can best fix this. It should be the case that this error will only be logged the first time the credential is used to authenticate. All subsequent calls to authenticate with the credential should only log output of the credential which was ultimately chosen to authenticate.

As to your second question, the `DefaultAzureCredential` is intended to be used in applications which ultimately are deployed to a Managed Identity enabled environment. The goal of the `DefaultAzureCredential` is to provide a credential type which will work both in a deployed environment and when executing in a local development environment. Some applications may opt to use the more specific `ManagedIdentityCredential` to explicitly limit how the application authenticates when it is deployed. However, if you opt to do this in your application, it will require code changes to debug, or some sort of configuration to switch the credential type which is used based on the environment.

**Comment by sebader** [comment]
That’s for looking into it!
Even for the first call I would argue it shouldn’t log an error - a warning at best I’d say because technically it still wouldn’t be an error. All is working as expected when using the DefaultCredential. 
Or what would be your reason to treat the first call as an error?

**Comment by pakrym** [comment]
@lmolkova do you have any recommended patterns for cases like this?

**Comment by lmolkova** [comment]
@sebader as a short-term mitigation strategy, filter out the dependency using [TelemetryProcessor](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#filtering).

Can you also share what would be the best option for you:
- never trace  EnvironmentCredential .GetToken call
- trace it but do not consider it an error
- something else?

In the long term, from the instrumentation side, what we can do better is to somehow know that EnvironmentCredential.GetToken is called from the SDK and traced on higher level already so we can 
- skip instrumentation and report nothing for this call
or
- report it without indicating error status.

**Comment by sebader** [comment]
@lmolkova I would opt for the second one, "trace it but do not consider it an error". It might be helpful for the developer to understand whats happening when using DefaultCredentials - vs. for instance ManagedIdentityCredential directly. So showing all the calls in the order as they are attempted, makes sense to me.

**Comment by pakrym** [comment]
I think "report it without indicating error status" is the right way to go too. Client invocation would throw if auth fails anyway and we can register error there.
