### ISSUE TITLE
[BUG] CloudException is thrown with status code 200 when using SqlManagementClient.Databases.CreateOrUpdateAsync(...)

### ISSUE THREAD

**Issue by geukhan** [Azure/azure-sdk-for-net#10655]
**Description/To Reproduce**
1. Get database properties from azure, keep it in memory as a backup.
2. Move the database out of standard elastic pool to premium standalone within same database server.
3. Try to copy the database to another server, but stop it because it took too long.
4. Revert database to original settings using ``SqlManagementClient.Databases.CreateOrUpdateAsync(...)`` and passing original database properties received from the 1st step.
5. Request throws ``CloudException`` with message ``The operation could not be completed because the read scale value specified is not supported for a 'Standard' database.``. The response object in the ``CloudException`` returns status code 200.
6. Repeat steps 4 and 5 with retry logic.

Eventually, the code exhausts all the retries and fails, however in Azure everything seems to have worked fine and the database is in its original state.

**Expected behavior**
``CloudException`` should not be thrown for status code 200.

**Actual behavior (include Exception or Stack Trace)**
``CloudException`` is thrown with status code 200 and message  ``The operation could not be completed because the read scale value specified is not supported for a 'Standard' database.``. Operation seems to be successful when checked on azure portal.

**Environment:**
 - Name and version of the Library package used: ``<PackageReference Include="Microsoft.Azure.Management.Sql" Version="1.19.0-preview" />``
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows Server 2016 DataCenter - Service Fabric 7.0.470.9590 - net472

**Comment by jsquire** [comment]
@erich-wang: Would you be so kind as to help route this?

**Comment by MladjoA** [comment]
@jsquire Jesse, this issue doesn't seem to be related to SQL Managed Instance, but rather SQL DB.
Can you please review and update labels? Thanks!
