### ISSUE TITLE
Event Hub tests preventing net-core-ci pipeline from succeeding

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10650]
https://github.com/Azure/azure-sdk-for-net/pull/10562/checks?check_run_id=512203761

![image](https://user-images.githubusercontent.com/21269347/76810599-e064ea80-67ab-11ea-9082-ae0d893ad40e.png)

**Comment by annelo-msft** [comment]
@jsquire @AlexGhiondea

**Comment by jsquire** [comment]
Well.... that's new.   Looking into it.

**Comment by jsquire** [comment]
FYI:  https://github.com/Azure/azure-sdk-for-net/pull/10658

That'll quiet things down while I investigate.   Apologies for the inconvenience.

**Comment by jsquire** [comment]
PR has merged;  these tests are now ignored pending some tuning.

**Comment by annelo-msft** [comment]
Thanks, Jesse!
