### ISSUE TITLE
&lt;Ask&gt; Need help to mock GetConfigurationSettings

### ISSUE THREAD

**Issue by zhenlan** [Azure/azure-sdk-for-net#10662]
@swasun99 commented on [Wed Mar 04 2020](https://github.com/Azure/AppConfiguration/issues/290)

Am trying to mock ConfigurationClient GetConfigurationSettings method using Moq. I see the sample has mocks for GetConfigurationSetting and SetConfigurationSetting but the GetConfigurationSettings method returns a Pageable<ConfigurationSetting> which is an abstract class. Is there any way to mock it using Moq?

---

@zhenlan commented on [Thu Mar 05 2020](https://github.com/Azure/AppConfiguration/issues/290#issuecomment-595380072)

@AlexGhiondea can anyone suggest?

---

@zhenlan commented on [Mon Mar 09 2020](https://github.com/Azure/AppConfiguration/issues/290#issuecomment-596863675)

Add @AlexanderSher 

---

@abhilasharora commented on [Mon Mar 09 2020](https://github.com/Azure/AppConfiguration/issues/290#issuecomment-596870213)

@swasun99 For the abstract class `Azure.Pageable<T>`, you can create your own mock implementation, or use the following sample class in your code.

``` csharp
class MockPageable : Pageable<ConfigurationSetting>
{
    private readonly List<ConfigurationSetting> _collection;

    public MockPageable(List<ConfigurationSetting> collection)
    {
        _collection = collection;
    }

    public override IEnumerable<Page<ConfigurationSetting>> AsPages(string continuationToken = null, int? pageSizeHint = null)
    {
        yield return Page<ConfigurationSetting>.FromValues(_collection, null, new Mock<Response>().Object);
    }
}
```

You can then use this class to set up mock for the `GetConfigurationSettings` method.

``` csharp
var testSettings = new List<ConfigurationSetting> { new ConfigurationSetting("testKey", "testValue") };
var mockClient = new Mock<ConfigurationClient>(MockBehavior.Strict, TestHelpers.CreateMockEndpointString());

mockClient.Setup(c => c.GetConfigurationSettings(It.IsAny<SettingSelector>(), It.IsAny<CancellationToken>()))
    .Returns(new MockPageable(testSettings));
```

---

@abhilasharora commented on [Mon Mar 09 2020](https://github.com/Azure/AppConfiguration/issues/290#issuecomment-596870761)

@AlexanderSher It might be useful to add the above code sample to the documentation [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/samples/Sample7_MockClient.md).

**Comment by AlexanderSher** [comment]
@pakrym , do you think we should add this to the mocking example in [Azure.Core](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Mocking.md)?

**Comment by pakrym** [comment]
Yeah, mocking pageable is tricky, having an example is nice.

**Comment by AlexanderSher** [comment]
CLosing via https://github.com/Azure/azure-sdk-for-net/pull/15384
