### ISSUE TITLE
[Flaky test] CreatePartitionProcessorProcessingTaskWrapsAnOperationCanceledExceptionAndConsidersItFatal

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#10669]
```
The wrapped exception should have been surfaced by the task.

Expected: instance of <System.Threading.Tasks.TaskCanceledException> and property InnerException equal to <System.OperationCanceledException: STAHP!>

But was: null
```

**Comment by jsquire** [comment]
Opened #10679 to ignore the offender, pending investigation and a fix.

**Comment by jsquire** [comment]
[CI Failure Example](https://dev.azure.com/azure-sdk/public/_build/results?buildId=310082&view=ms.vss-test-web.build-test-results-tab&runId=9629198&resultId=102855&paneView=debug)

**Comment by jsquire** [comment]
#10679 has merged and this test is now disabled.
