### ISSUE TITLE
CloudException vs HttpStatusCode.NotFound/etc.

### ISSUE THREAD

**Issue by Brad-Christie** [Azure/azure-sdk-for-net#1068]
Maybe I'm being daft here, but is there a reason why the library throws a CloudException and doesn't just return the associated StatusCode? It seems odd that I would have to encapsulate these calls in try/catch (which is arguably an expensive proposition) when a StatusCode result should be sufficient? Case in point:

```
using (var client = CloudContext.Clients.CreateWebSiteManagementClient(credentials))
{
    var parameters = new WebSiteGetParameters { PropertiesToInclude = new List<String>() };
    var response = await client.WebSites.GetAsync(webSpace.Name, webSiteName, parameters);
    // I should be able to check against response.StatusCode and not wrap this
    // in a try...catch
}
```

REST APIs are supposed to return 404, 200, etc. codes. It looks like you purposely throw an exception when anything but an OK response comes back, and I'd just like to know if there's a reason for it?

**Comment by DaveVdE** [comment]
I agree, was looking to open this as issue as well today, but found it was already here.

**Comment by DaveVdE** [comment]
It's as if it's generated like that, but I can't find any source for this Hyak generator that seems to be in use.

**Comment by shahabhijeet** [comment]
@Brad-Christie please open a new issue, if the problem still exists.
