### ISSUE TITLE
Write mock tests for concurrency issue in ChallengeBasedAuthenticationPolicy

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#10691]
We should use `MockTransport`s to mock various concurrency scenarios for the fix made in PR #10673. We'll need to synchronize certain responses to simulate lag in concurrent calls.

Scenarios include, but are not limited to:

1. Single-threaded call
1. Simultaneous multi-threaded calls like in https://gist.github.com/heaths/87b6a2da1b9cdd5c88fe6c3dedb28216#file-program-cs
1. Offset multi-threaded calls
1. As a pivot, calls where the tenant (scope) change for the vault URI

/cc @schaabs if he has any more scenarios to add.

**Comment by schaabs** [comment]
Also we should add tests for the service continually sending 401s so we ensure we don't get stuck in a loop that doesn't return to the client.

**Comment by heaths** [comment]
This was resolved with #10804
