### ISSUE TITLE
WebSiteOperationsExtensions.GetUsageMetrics error when using Basic service plan

### ISSUE THREAD

**Issue by teslavitas** [Azure/azure-sdk-for-net#1069]
I am getting "Must specify valid information for parsing in the string." Error when I am trying to obtain usage metrics. If I change service plan to "Shared" I am getting another error that is described here: https://github.com/Azure/azure-sdk-for-net/issues/904 
webSpaceName and webSiteName parameters that I specify correctly work with other API methods.

**Comment by kumarbalriya** [comment]
I came across the same issue. This method is working for website having app service plan as "H1 free" not in "S1 Standard app service plan". 

Please suggest how to get rid of this issue in "S1 Standard service plan".

**Comment by siganakis** [comment]
I too am getting the same error, in a premium plan.

**Comment by orlandow** [comment]
Any updates or workarounds?

**Comment by reecezimm** [comment]
Bumping this. Any updates, this is an important call for website metrics?

**Comment by shahabhijeet** [comment]
@teslavitas can you open a new issue if this problem still persists.
