### ISSUE TITLE
Azure.Identity DefaultAzureCredential and ManagedIdentityCredential does not work with Azure Web App Managed Identity

### ISSUE THREAD

**Issue by Daniel-Krzyczkowski** [Azure/azure-sdk-for-net#10738]
**Describe the bug**
I created the sample with Azure.Identity and Azure.Security.KeyVault.Secrets packages to retrieve secrets from the Azure Key Vault. I wanted to test DefaultAzureCredential and ManagedIdentityCredential credentials options with Managed Identity.
I created Azure Web App and enabled System Assigned Managed Identity. Then in the Key Vault I added Access Policy to enable this web app GET and LIST secrets.

**Expected behavior**
Azure Web App should retrieve secret from the Azure Key Vault using Azure.Security.KeyVault.Secrets with DefaultAzureCredential and ManagedIdentityCredential.

**Actual behavior (include Exception or Stack Trace)**
It looks like Azure Web App cannot retrieve secrets from the Azure Key Vault. I tried both credential options: DefaultAzureCredential and ManagedIdentityCredential together with System Assigned Managed Identity in the Azure Web App but no positive result.

I also connected Azure Application Insights to see what happened and there is only one exception but I suppose it is related with inability to retrieve the secret:
System.Text.Json.JsonException:
A possible object cycle was detected which is not supported. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32.

**To Reproduce**
You can use my sample ASP .NET Core application:
https://github.com/Daniel-Krzyczkowski/AzureDeveloperTemplates/tree/master/src/azure-key-vault-sdk-asp-net-core-template

1. Create Azure Web App
2. Enable System Assigned Managed Identity
3. Create Azure Key Vault
4. Add secret
5. Add Access Policy to enable GET and LIST permissions for secrets for the above Managed Identity
6. Open ServiceCollectionExtensions class located in the Extensions folder inside AzureDeveloperTemplates.KeyVaultSdk.WebAPI project.
7. Try to use DefaultAzureCredential:
            var secretClient = new SecretClient(new Uri(keyVaultUrl), new DefaultAzureCredential());
8. Try to use DefaultAzureCredential:
            var secretClient = new SecretClient(new Uri(keyVaultUrl), new ManagedIdentityCredential("system-assigned-managed-identity-object-id"));
9. Deploy App to Azure Web App

**Environment:**
 Azure Web App hosted on the Windows App Service Plan S1. ASP .NET Core 3.0 runtime stack.
Application created with ASP .NET Core 3.1 in Visual Studio 2019 on the Windows machine.
Libraries used:
1. Azure.Identity version 1.11
2. Azure.Security.KeyVault.Secrets version 4.0.2

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by AlexGhiondea** [comment]
@Daniel-Krzyczkowski I see that you are using a slightly older version of the extensions library.

Can you update to the [new one](https://github.com/Azure/azure-sdk-for-net/blob/31efa80ce402e5f97ef3e474a43d97f58f33d64f/sdk/extensions/Azure.Extensions.Configuration.Secrets/README.md) and try this scenario again?

**Comment by Daniel-Krzyczkowski** [comment]
Of course, thank you, I am testing this right now.

**Comment by Daniel-Krzyczkowski** [comment]
@AlexGhiondea Thank you for the hint, now it works.
However right now I am a bit confused. :)
I was convinced that using Azure.Identity package together with Azure.Security.KeyVault.Secrets package it enough and we can access the Key Vault secrets automatically.

This is the code I used before:

`  
string keyVaultUrl = configuration["KeyVaultSettings:Url"];
`
`  
var secretClient = new SecretClient(new Uri(keyVaultUrl), new DefaultAzureCredential());
`

I thought that if I register SecretClient instance in the DI container I will be able to access the secrets. I also see in the [link](https://github.com/Azure/azure-sdk-for-net/blob/31efa80ce402e5f97ef3e474a43d97f58f33d64f/sdk/extensions/Azure.Extensions.Configuration.Secrets/README.md) you sent that the name is "Azure Storage Blob Key Store" but we do not use Azure Blob Storage anywhere.
Could you please clarify?  I would be grateful.

**Comment by Daniel-Krzyczkowski** [comment]
@AlexGhiondea, @jsquire Could you please provide any updates/answer? I would be really grateful to understand these different approaches. I also found [this repo with Microsoft.Extensions.Azure package](https://github.com/Azure/azure-sdk-for-net/blob/64463f361c3dfeb8f96bb1d335710b383424bdb6/sdk/core/Microsoft.Extensions.Azure/README.md) and see that it can be also used to access Key Vault credentials.

**Comment by schaabs** [comment]
@pakrym can you comment on the different approaches to Key Vault integration with ASP.NET Core.

**Comment by pakrym** [comment]
The https://github.com/Azure/azure-sdk-for-net/blob/31efa80ce402e5f97ef3e474a43d97f58f33d64f/sdk/extensions/Azure.Extensions.Configuration.Secrets/README.md is a correct one but the title of the page is wrong and I'll fix it.

Currently there are two ways to consume KV Secrets in ASP.NET Core:
1. Using Microsoft.Extensions.Azure to register SecretClient with DI, resolving it and calling SecretClient methods - prefer it if you application requires to know about and deal with specifics of KeyVault Secret service. For example you want to set, delete, lock secrets, etc.
2. Using Azure.Extensions.Configuration.Secrets package if the only thing you need is an IConfiguration integration.

**Comment by Daniel-Krzyczkowski** [comment]
@schaabs, @pakrym Thank you so much for explanation, all clear now.

**Comment by jongio** [comment]
@Daniel-Krzyczkowski - Does it work with these suggestions?  All clear to close?

**Comment by Daniel-Krzyczkowski** [comment]
@jongio Thank you, yes, this one can be closed.

**Comment by jongio** [comment]
Thanks Daniel.
