### ISSUE TITLE
Add support of setting non-ASCll metadata for blob client

### ISSUE THREAD

**Issue by XuGuang-Yao** [Azure/azure-sdk-for-net#10741]
Only ASCII chars are supported when setting blob metadata. But we can set non-ASCII in the Azure portal directly.
![image](https://user-images.githubusercontent.com/53599438/77154411-985d0500-6ad6-11ea-97f8-5e8f788da2d0.png)

**Library or service name.**

Azure.Storage.Blobs 12.4.0 
 
**Is your feature request related to a problem? Please describe.**

Write metadata to a blob containing a non-ASCII character (such as "ñ").

            var client = new BlobContainerClient(connectionString, "test");
            var blobClient = client.GetBlobClient("test.jpg");

            var metadata = new Dictionary<string, string>();
            metadata.Add("Test", "ñ"); // The notorious ñ.

            blobClient.SetMetadata(metadata);
     
Error occurs when setting metadata by calling SetMetadata for BlobClient
RequestFailedException: Request headers must contain only ASCII characters.

**Comment by XuGuang-Yao** [comment]
This is related to #10629.

**Comment by kasobol-msft** [comment]
@XuGuang-Yao Please see the answer in https://github.com/Azure/azure-sdk-for-net/issues/10629 .
