### ISSUE TITLE
KeyVault Secrets SDK throws AuthenticationFailedException forcing additional dependency on Azure.Identity

### ISSUE THREAD

**Issue by abhilasharora** [Azure/azure-sdk-for-net#10759]
**Bug Description**
`Azure.Security.KeyVault.Secrets.SecretClient` throws `Azure.Identity.AuthenticationFailedException` in case the `Azure.Core.TokenCredential` passed to it could not be used. For example, when a user tries to fetch a secret from the key vault using `DefaultAzureCredential` but an approprite credential as described [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/README.md#defaultazurecredential) could not be found, then `Azure.Identity.AuthenticationFailedException` is thrown.

Since the exception `AuthenticationFailedException` belongs to the `Azure.Identity` package, consumers of the `Azure.Security.KeyVault.Secrets` package are unable to handle it the right way without adding an explicit dependency on the `Azure.Identity` package.

**Expected behavior**
When the input `TokenCredential` could not be used for authentication, `Azure.Security.KeyVault.Secrets` throws an exception that does not require an explicitly dependency on another package that is not one of its dependencies, so it could be handled by the consumers.

**Actual behavior (include Exception or Stack Trace)**
When the input `TokenCredential` could not be used for authentication, `Azure.Security.KeyVault.Secrets` throws `AuthenticationFailedException` exception that requires a dependency on `Azure.Identity` package to be able to handle it the right way.

**Exception**
```` csharp
Azure.Identity.AuthenticationFailedException: The DefaultAzureCredential failed to retrieve a token from the included credentials.
EnvironmentCredential is unavailable.
Environment variables not fully configured.
AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD.
Currently set variables [  ].
ManagedIdentityCredential is unavailable No managed identity endpoint found..
SharedTokenCacheCredential is unavailable Token acquisition failed for user . To fix, re-authenticate through developer tooling supporting Azure single sign on.
````

**Stack Trace**
```` csharp
DefaultAzureCredential.GetTokenAsync(Boolean isAsync, TokenRequestContext requestContext, CancellationToken cancellationToken)
DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
ChallengeBasedAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, Boolean async)
ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpMessage message, ReadOnlyMemory pipeline, Boolean async)
RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory pipeline, Boolean async)
RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory pipeline, Boolean async)
HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory pipeline)
HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory pipeline)
HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func resultFactory, CancellationToken cancellationToken, String[] path)
SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
````

**Environment:**
.NET Standard 2.0 Class Library
Azure.Security.KeyVault.Secrets 4.0.1

**Comment by heaths** [comment]
Scanning the source for all our services, the only place where an `AuthenticationFailedException` is even instantiated is in Azure.Identity, which means you already would have had to include Azure.Identity to use any code like `DefaultAzureCredential` that throws `AuthenticationFailedException`. Could you clarify how you're getting this exception without already having a dependency on Azure.Identity?

**Comment by abhilasharora** [comment]
The configuration provider `Microsoft.Extensions.Configuration.AzureAppConfiguration` for Azure App Configuration allows users to connect to configuration store using `TokenCredential`. It does not have a dependency on `Azure.Identity`, so we don't have a good way to handle this exception. When the configuration provider tries to use the key vault SDK, it throws the `AuthenticationFailedException` and breaks the `TryRefreshAsync` method contract since it is not expected to throw this exception.

I believe the right fix is to update the key vault SDK to not assume that the clients will have a reference to the `Azure.Identity` package, and it might require changes to the `Azure.Identity` package too.

**Comment by heaths** [comment]
The Key Vault SDK is not throwing this exception nor does it have a dependency on Azure.Identity. If a customer uses Azure.Identity to, for example, use a `DefaultAzureCredential` for authentication, it is throwing the exception.

We could, however, consider moving this exception to Azure.Core, on which all Azure.* packages depend. We can't take a direct dependency on Azure.Identity.

/cc @schaabs

**Comment by pakrym** [comment]
This is a good one, without AuthenticationFailedException being in Core library authors can't handle authentication exceptions.

We should consider using TypeForwarding and moving the exception to azure.core

**Comment by KrzysztofCwalina** [comment]
I agree we should move AuthenticationFailedException to Azure.Core.

**Comment by pakrym** [comment]
Test program:

``` C#
try
{
    await new DefaultAzureCredential().GetTokenAsync(default);
}
catch (AuthenticationFailedException)
{
}
```

# Migration scenario

## New Azure.Core, old Identity

```xml
<PackageReference Include="Azure.Identity" Version="1.2.3" />
<PackageReference Include="Azure.Core" Version="1.6.0-alpha.20201009.1" />
```

```
error CS0433: The type 'AuthenticationFailedException' exists in both 'Azure.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' and 'Azure.Identity, Version=1.2.3.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' [D:\temp\afe\afe.csproj]
```

### Workaround

```xml
<PackageReference Include="Azure.Identity" Version="1.2.3" Aliases="identity" />
<PackageReference Include="Azure.Core" Version="1.6.0-alpha.20201009.1" />
```

``` C#
extern alias identity;
using identity::Azure.Identity;

try
{
    await new DefaultAzureCredential().GetTokenAsync(default);
}
catch (AuthenticationFailedException)
{
}
```

or update to the new identity


## Old Azure.Core, new Identity

Not possible, identity takes a dependency on a new Azure.Core

## New Azure.Core, new Identity

All good, `AuthenticationFailedException` resolved to the one inside Azure.Core.

**Comment by schaabs** [comment]
Since most applications will not be referencing core directly the scenarios where users will need to upgrade will likely be more subtle. For instance, an application might have the following dependencies.
```xml
<PackageReference Include="Azure.Identity" Version="1.2.3" />
<PackageReference Include="Azure.Storage.Blobs" Version="12.6.0" />
```
This works because `Azure.Storage.Blobs` depends on an eariler version of `Azure.Core`.

However, they could upgrade this to a later version of `Azure.Storage.Blobs` and start getting an compiler error without changing their code.
```xml
<PackageReference Include="Azure.Identity" Version="1.2.3" />
<PackageReference Include="Azure.Storage.Blobs" Version="12.7.0" />
```
```
error CS0433: The type 'AuthenticationFailedException' exists in both 'Azure.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' and 'Azure.Identity, Version=1.2.3.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' [D:\temp\afe\afe.csproj]
```
Or, they might just add another package from the SDK which depends on a later version of `Azure.Core` and start getting an compiler error without changing their code.

```xml
<PackageReference Include="Azure.Identity" Version="1.2.3" />
<PackageReference Include="Azure.Storage.Blobs" Version="12.6.0" />
<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.0.0" />
```
```
error CS0433: The type 'AuthenticationFailedException' exists in both 'Azure.Core, Version=1.6.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' and 'Azure.Identity, Version=1.2.3.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' [D:\temp\afe\afe.csproj]
```

**Comment by heaths** [comment]
That's unfortunate, but with some SEO would could add those to a troubleshooting doc on docs.microsoft.com (indexing of GitHub docs in repos doesn't seem very high in rankings). They should index fairly well if we still want to move forward.

**Comment by pakrym** [comment]
Moving to Identity as we seem to be converging on inheriting from the https://docs.microsoft.com/en-us/dotnet/api/system.security.authentication.authenticationexception?view=net-5.0

**Comment by pakrym** [comment]
No, we haven't fixed this yet.

**Comment by pallavit** [comment]
@christothes based on the last conversation on this thread we intended to solve it in Azure.Identity, wanted to check if my understanding is correct. Also, have we already fixed it?

**Comment by christothes** [comment]
That's correct, but we have not fixed this yet. With how long it's been around, we haven't heard much customer feedback on this. I think we should consider closing this until we get additional feedback.

**Comment by pallavit** [comment]
Sounds good. I will close this as not planned for now.
