### ISSUE TITLE
Unable to add Microsoft.WindowsAzure.Management.Libraries to Windows Phone Universal App

### ISSUE THREAD

**Issue by f-aa** [Azure/azure-sdk-for-net#1075]
When I try to install the Libraries package it gives me an error saying Microsoft.WindowsAzure.Management.Compute is not compatible.

Here are the steps I took to reproduce in a blank project called AzureTestApp.

Create new blank Universal App project.

    Install-Package Microsoft.WindowsAzure.Management.Libraries -Prerelease

This installs it into the Windows 8.1 project just fine. I then run this command:

    Install-Package Microsoft.WindowsAzure.Management.Libraries -Prerelease -ProjectName AzureTestApp.WindowsPhone

This gives the following output:

    PM> Install-Package Microsoft.WindowsAzure.Management.Libraries -Prerelease -ProjectName AzureTestApp.WindowsPhone
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Common (= 1.3.0 && < 2.0)'.
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Common.Dependencies (= 1.1.0)'.
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Management (= 2.0.0)'.
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Management.Compute (= 5.0.0)'.
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Management.MediaServices (= 2.0.0)'.
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Management.Monitoring (= 1.0.0)'.
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Management.Network (= 3.0.0)'.
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Management.Scheduler (= 3.0.0)'.
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Management.Sql (= 3.0.0)'.
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Management.Storage (= 3.0.0)'.
    Attempting to resolve dependency 'Microsoft.WindowsAzure.Management.WebSites (= 3.0.0)'.
    'Microsoft.WindowsAzure.Management.Libraries 2.0.0' already installed.
    Adding 'Microsoft.WindowsAzure.Common.Dependencies 1.1.0' to AzureTestApp.WindowsPhone.
    Successfully added 'Microsoft.WindowsAzure.Common.Dependencies 1.1.0' to AzureTestApp.WindowsPhone.
    Adding 'Microsoft.WindowsAzure.Common 1.3.0' to AzureTestApp.WindowsPhone.
    Successfully added 'Microsoft.WindowsAzure.Common 1.3.0' to AzureTestApp.WindowsPhone.
    Adding 'Microsoft.WindowsAzure.Management 2.0.0' to AzureTestApp.WindowsPhone.
    Successfully added 'Microsoft.WindowsAzure.Management 2.0.0' to AzureTestApp.WindowsPhone.
    Adding 'Microsoft.WindowsAzure.Management.Compute 5.0.0' to AzureTestApp.WindowsPhone.
    Install-Package : Could not install package 'Microsoft.WindowsAzure.Management.Compute 5.0.0'. You are trying to install this package into a project that targets 'WindowsPhoneApp,Version=v8.1', but the package does not contain 
    any assembly references or content files that are compatible with that framework. For more information, contact the package author.
    At line:1 char:1
    + Install-Package Microsoft.WindowsAzure.Management.Libraries -Prerelease -Project ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
        + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

If I add all the packages manually it works.

**Comment by singhkay** [comment]
@f-aa Can you try this with the newer http://www.nuget.org/packages/Microsoft.Azure.Management.Compute/11.0.0-prerelease ARM stack based libraries?
