### ISSUE TITLE
[Feature Request] Deserialize message sent from WindowsAzure.ServiceBus (Track Zero)

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#10788]
We might want to add an API, sample, or document explaining how to deserialize a message sent from `WindowsAzure.ServiceBus` (the "Track 0" SDK).  To run the following repro, create a .NET Framework console app (not .NET Core) and add package references to `WindowsAzure.ServiceBus`  (Track 0) and `Azure.Messaging.ServiceBus` (Track 2).

```C#
// Send from WindowsAzure.ServiceBus (Track 0)
var factory1 = MessagingFactory.CreateFromConnectionString(connectionString);
var client1 = factory1.CreateQueueClient("test");
client1.Send(new BrokeredMessage("WindowsAzure.ServiceBus"));

// Receive from Azure.Messaging.ServiceBus (Track 2)
var client2 = new ServiceBusClient(connectionString);
var receiver2 = client2.GetReceiver("test");
var message2 = await receiver2.ReceiveAsync();

var body2Bytes = message2.Body.ToArray();

var invalidBody2 = Encoding.UTF8.GetString(body2Bytes);
Console.WriteLine(invalidBody2);
// @strin3http://schemas.microsoft.com/2003/10/Serialization/?WindowsAzure.ServiceBus

var validBody2 = Deserialize<string>(body2Bytes);
Console.WriteLine(validBody2);
// WindowsAzure.ServiceBus

await receiver2.CompleteAsync(message2);

public static T Deserialize<T>(byte[] data)
{
    var serializer = new DataContractSerializer(typeof(T));
    using (var stream = new MemoryStream(data))
    using (var reader = XmlDictionaryReader.CreateBinaryReader(stream, XmlDictionaryReaderQuotas.Max))
    {
        return (T)serializer.ReadObject(reader);
    }
}
```

**Comment by jsquire** [comment]
Minor note:  `WindowsAzure.ServiceBus` is the Track Zero client.    `Microsoft.Azure.ServiceBus` is the Track One client.    Our approach to date has been to provide a migration guide for moving from T1 => T2.    I don't know how much value there would be in the efforts to bridge from T0 => T2

**Comment by jsquire** [comment]
The other thing that I'd like to mention is that the client libraries for T1 and T2  are intentionally agnostic to the body of messages, treating them only as a blob of bytes.   Were we do decide that it makes sense to demonstrate this, a sample would be the appropriate vector unless the architect board changes its stance from the conversations in the Event Hubs design on whether we should consider string-based helpers for bodies.  At that point @KrzysztofCwalina had registered his preference as not doing so.

**Comment by mikeharder** [comment]
@jsquire: For context, I ran into this issue because the DevOps task [PublishToAzureServiceBus](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-to-azure-service-bus?view=azure-devops) publishes messages using the Track 0 format.

**Comment by jsquire** [comment]
Thanks, @mikeharder. That's helpful context for prioritization.  If we're seeing mainstream cases like this, it definitely sounds like we should cover it in a sample.

**Comment by jsquire** [comment]
For more context, it appears that this issue exists in the track one library as well, where it is worked around by use of two types in the `Extensions` namespace, one of which provides a special serializer and the other which offers an extension method to the message object.   These can be seen in the following locations:

- [Serializer](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Extensions/DataContractBinarySerializer.cs)
- [Message Extension](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Extensions/MessageInterOpExtensions.cs)

**Comment by JoshLove-msft** [comment]
We have a sample for this now - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample08_Interop.md
