### ISSUE TITLE
ServiceBusProcessor: AutoComplete has race condition with StopProcessingAsync

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#10797]
The `ServiceBusProcessor.AutoComplete` feature has a race condition with the `StopProcessingAsync()` method.  The following code does **not** cause the message to be completed:

```c#
var client = new ServiceBusClient(connectionString);
var processor = client.GetProcessor("test", new ServiceBusProcessorOptions
{
    AutoComplete = true
});

var tcs = new TaskCompletionSource<bool>();
processor.ProcessMessageAsync += async args =>
{
    var message = args.Message;
    Console.WriteLine(Encoding.UTF8.GetString(message.Body.ToArray()));
    tcs.SetResult(true);
};

processor.ProcessErrorAsync += args => throw args.Exception;

await processor.StartProcessingAsync();
await tcs.Task;
await processor.StopProcessingAsync();
```

I believe the issue is a race condition where my app code is calling `StopProcessingAsync()` immediately after `tcs.SetResult(true)` is called inside the event handler, which causes the processor to stop before it has completed the message.

I think the best fix would be for `StopProcessingAsync()` to wait for any pending completions, since from the app code perspective the message is complete.

Another option would be for the processor (or message) to expose some way for app code to know when the message has been auto-completed. 

Without one of these changes, I don't think it's possible to use `AutoComplete` in a reliable way, since app code doesn't know when it's safe to call `StopProcessingAsync()`.

**Comment by JoshLove-msft** [comment]
Agree that StopProcessing should allow for in flight message processing to complete. Under the hood, it is actually already doing this, but the cancellation token that we use to signal that the processing should be stopped is threaded through to the Complete call used during autocompletion. A simple fix would be to not propagate this token through for the complete call.

**Comment by JoshLove-msft** [comment]
This was fixed.
