### ISSUE TITLE
[FEATURE REQ] Page<T> and Response<T> should implement or inherit from a common ancestor

### ISSUE THREAD

**Issue by ylibrach** [Azure/azure-sdk-for-net#10793]
**Library or service name.**
What library or service is this request related to? Azure.Core
 
**Is your feature request related to a problem? Please describe.**
Currently, `Page<T>` is a basic class that has no inheritance or implementation chain. However, it is in fact very similar to a `Response<T>` - it is a page of results that come down through a `Response`. Accordingly, both types have the `GetRawResponse()` method. Therefore, there should be some common ancestor between the two so that methods can accept an argument that matches either of these types. Currently, there is no clean way of achieving this behavior.

**Comment by jsquire** [comment]
//cc: @pakrym, @KrzysztofCwalina

**Comment by pakrym** [comment]
What would be an example of a method you would accept the common type into?

**Comment by ylibrach** [comment]
We have an "observer" method that receives the responses for all Cosmos DB requests, and updates Prometheus metrics based on the request charge for that response.

**Comment by pakrym** [comment]
But you can achieve the same thing by having a method that takes `Response` and calling `.GetRawResponse()` on pageable when needed.

**Comment by ylibrach** [comment]
Sorry, I probably should have elaborated a bit more - this method takes in the delegate of the asynchronous task to be executed (eg, `Func<Context, CancellationToken, Task<T>> where T : Azure.Response<R>`). It then executes that delegate, monitors it, and records Prometheus metrics accordingly (along with some other operations). So, this method doesn't know what exact return type it's working with - whether it is a `Page`, or an `ItemResponse`, or a `StoredProcedureResponse`, etc. All it needs to know is that the return type has a raw `Response` object on it that it can use to get the request charge. It then records that, and passes the result up the chain.

**Comment by pakrym** [comment]
So would adding a couple overloads for this method that know how to inspect [Async]Pageable help? E.g. `Func<Context, CancellationToken, Task<T>> where T : Azure.Pageable<R>` and another that takes `Func<Context, CancellationToken, Task<T>> where T : Azure.AsyncPageable<R>`

**Comment by KrzysztofCwalina** [comment]
`Page<T>` has a 'IReadOnlyList<T> Values { get; }' property. `Response<T>` has a 'T Value { get; }' property. If `Page<T>` inherits from `Response<T>`, what would the `Value` property return when called on `Page<int>`?, i.e. which `int` would it return?

**Comment by ylibrach** [comment]
I'm proposing that `Page<T>` and `Response<T>` implement/inherit a common ancestor, and not that `Page<T>` inherit `Response<T>`. 

One possible solution is to introduce something like an `IResponseEnvelope` interface that has a `GetRawResponse()` method on it, and have `Page<T>` and `Response<T>` both implement that interface.

**Comment by KrzysztofCwalina** [comment]
> 'm proposing that Page<T> and Response<T> implement/inherit a common ancestor, and not that Page<T> inherit from Response<T>.

Ah, sorry, I missed that.

**Comment by pakrym** [comment]
Don't think the use case is common enough to motivate adding this feature.
