### ISSUE TITLE
Form Recognizer: Move to standardized Cognitive Filter semantics

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#10801]
Dependent on #10800

**Comment by pallavit** [comment]
@annelo-msft we may need your help to understand this more.
/cc: @kinelski

**Comment by annelo-msft** [comment]
I believe this was in reference to standardizing the client APIs around:

- [TrainSourceFilter](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/FormRecognizer/stable/v2.1/FormRecognizer.json#L1244-L1260) FormRecognizer REST API
- [DocumentFilter](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/TranslatorText/stable/v1.1/TranslatorBatch.json#L903-L917) in the Translator Text API
