### ISSUE TITLE
[Discussion] Service Bus - Track 2 - Connection Strings

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#10824]
_The intent of this issue is to solicit feedback from the community in advance of the GA of the next major version of the Service Bus library (which will follow several Preview releases).
As a reference, the .NET Azure SDK guidelines can be found here: https://azure.github.io/azure-sdk/dotnet_introduction.html
Terminology:
Track 0 refers to the [WindowsAzure.ServiceBus library](https://www.nuget.org/packages/WindowsAzure.ServiceBus/)
Track 1 refers to the [Microsoft.Azure.ServiceBus library](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/)
Track 2 refers to the new library, Azure.Messaging.ServiceBus, we are working on releasing._

In the previous version of the library, the connection string could be used to specify things like OperationTimeout and Transport type. The way that these options are added to the string is through the use of the [ServiceBusConnectionStringBuilder ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/ServiceBusConnectionStringBuilder.cs).

Our philosophy for connection strings for the Track 2 libraries can be found [here](https://azure.github.io/azure-sdk/general_design.html):

> Client libraries may support providing credential data via a connection string **ONLY IF** the service provides a connection string to users via the portal or other tooling. Connection strings are generally good for getting started as they are easily integrated into an application by copy/paste from the portal. However, connection strings are considered a lesser form of authentication because the credentials cannot be rotated within a running process.

> **DO NOT** support constructing a service client with a connection string unless such connection string is available within tooling (for copy/paste operations
> 

In our new library, the TransportType and OperationTimeout can be specified within the options that are passed when creating a new client instance. As such, we are proposing that support for including the TransportType and OperationTimeout within the connection string should not be included. This would also mean that there is no need to expose the ServiceBusConnectionStringBuilder.

```c#
var client = new ServiceBusClient(connectionString, new ServiceBusClientOptions
{
    TransportType = ServiceBusTransportType.AmqpWebSockets,
    RetryOptions = new ServiceBusRetryOptions
    {
        TryTimeout = TimeSpan.FromSeconds(30)
    }
});
```

**Comment by JoshLove-msft** [comment]
Adding some community members who have recently submitted issues/PRs for Service Bus 😃

/cc @nemakam @SeanFeldman @Einarsson @brandondahler @broloaugh @ankrause @GrimGadget @ShaneCourtrille @Pucmaster @Bnjmn83

**Comment by SeanFeldman** [comment]
It reminds me of a joke.
- Dad, dad, why the sun rises in the east and sets down in the west?
- Son, does it work?
- Yes, dad.
- Then don't touch it.

> In the previous version of the library, the connection string could be used to specify things like OperationTimeout and Transport type.

I'm somewhat confused by this question. Are you saying that because the portal does not generate a connection string with TransportType and OperationTimeout arguments by default, those should not be accepted/exposed via the `ServiceBusConnectionStringBuilder`?

If so, then it's a false direction. `Authentication` is not generated in the portal. Does that mean it should not be supported either?

**Comment by SeanFeldman** [comment]
Regarding the philosophy

> However, connection strings are considered a lesser form of authentication because the credentials cannot be rotated within a running process.

With storage tables, you cannot have anything else other than a connection string or a SAS token. Can't rotate within a running process. Same with CosmosDB data operations.

Philosophy has a weight but the real world dictates reality. Connection strings will be lesser of an authentication method when the alternatives become available for **absolutely all services**. Until that happens, the philosophy is as good as the ten commandments. Thousands of years old great recommendations and yet still not practiced by all.

**Comment by JoshLove-msft** [comment]
> It reminds me of a joke.
> 
> - Dad, dad, why the sun rises in the east and sets down in the west?
> - Son, does it work?
> - Yes, dad.
> - Then don't touch it.
> 
> > In the previous version of the library, the connection string could be used to specify things like OperationTimeout and Transport type.
> 
> I'm somewhat confused by this question. Are you saying that because the portal does not generate a connection string with TransportType and OperationTimeout arguments by default, those should not be accepted/exposed via the `ServiceBusConnectionStringBuilder`?
> 
> If so, then it's a false direction. `Authentication` is not generated in the portal. Does that mean it should not be supported either?

I think the difference is that Connection strings are generated in the portal, but the Track 1 library extended it to include other options. Our guidelines basically say, "Only support the connection string that can be generated from the portal". The additional options added in Track 1 can still be added in the options type.

**Comment by SeanFeldman** [comment]
My counter would be that you can consider the portal emitting anything that is not a default. Defaults are simply omitted.

Also, portal is not the authoritative source. It goes with the lowest common denominator. I would have a hard time to tell my customers that they need to recompile the code to switch from a non Managed Identity connection to MI-based one.

**Comment by danielmarbach** [comment]
From my perspective what has been outlined here resonates very well with me in general. I do agree that the connection string is in the authority of the service and the client SDK should only support a connection string as it is known to the service. That also simplifies cross language support in the SDK. If customers want to have a client specific extended connection string it is trivial to build a connection string builder leveraging the built-in dotnet types and then map it to the option creation.

**Comment by JoshLove-msft** [comment]
Thanks for all of the discussion, closing as there is no further action item here.
