### ISSUE TITLE
[Discussion] Service Bus - New Version - Message Structure

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#10826]
The intent of this issue is to solicit feedback from the community in advance of the GA of the next version of the Service Bus Track 2 library (which will follow several Preview releases).
As a reference, the .NET Azure SDK guidelines can be found here: https://azure.github.io/azure-sdk/dotnet_introduction.html

In the previous versions of the Service Bus library, there was a single type for both sending and receiving messages. There are a couple downsides to this to go with the obvious upside of its simplicity:
1. System level properties would appear on the message that a user is constructing for sending. Although these properties are read-only, it adds some cognitive overhead to reasoning about the type.
2. When receiving a message, any of the settable properties can still be set. However, setting these properties doesn't actually do anything even after settling the message. For instance a user might think that doing something like the below might actually change the messageId, which it wouldn't. This concern is more pronounced with our proposed addition of overloads for settlement methods taking a message (it could be argued if the settlement only accepts a lock token, then no one would think that changing any of the other properties would affect the settlement).
```c#
var message = await receiver.ReceiveAsync();
message.MessageId = "newMessageId";
// in the new version, we are offering overloads for settlement methods
// that take a message in addition to the ones that take a lock token
await receiver.AbandonAsync(message);
```

In order to address these two issues, we are proposing having two separate types for messages:
- A ServiceBusMessage which is what a user would create for sending. 
- A ServiceBusReceivedMessage which is what a user would get back when receiving a message.

Intially, we thought that ServiceBusReceivedMessage could derive from ServiceBusMessage, but the issue we ran into there was needing to somehow still make the received message properties read-only (we could do runtime validation or use "new" keyword), in addition to wanting to make it super clear to users that re-sending a message that has system properties set on it, will not end up having those same system properties set once it is processed by the service (these system properties would be thrown out before sending).

So our updated proposal is to not have ServiceBusReceivedMessage derive from ServiceBusMessage. This allows us to keep ServiceBusReceivedMessage immutable. It also means we don't have to worry about a user sending a received message. In order to support re-sending a received message we offer a static factory method.
```c#
foreach (ServiceBusReceivedMessage msg in receivedMessages)
{
    ServiceBusMessage sendableMessage = ServiceBusMessage.CreateFrom(receivedMessage);
    await sender.SendAsync(sendableMessage);
}
```
The downside to breaking the hierarchy is that code that could be written to process a message in some way that should be agnostic to whether the message was sent or received, would now have to be duplicated somewhat. We would like to see what the community thinks about this tradeoff.

**Comment by richardpark-msft** [comment]
Just for clarity in the example - it'd be good to change `msg` to `receivedMessage`

**Comment by richardpark-msft** [comment]
Another option is to have a base class that both ServiceBusMessage and ServiceBusReceivedMessage derived from, so at least the common properties can still be accessed.

We would just never accept the base class as parameters to these methods (ie, only the leaf classes get used for parameters)

**Comment by JoshLove-msft** [comment]
> Another option is to have a base class that both ServiceBusMessage and ServiceBusReceivedMessage derived from, so at least the common properties can still be accessed.
> 
> We would just never accept the base class as parameters to these methods (ie, only the leaf classes get used for parameters)

Yes, if we needed to we could add this in the future, but would prefer to avoid it if possible.

**Comment by JoshLove-msft** [comment]
See https://github.com/Azure/azure-sdk-for-net/issues/10829
