### ISSUE TITLE
Get extension libraries API reviewed 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#10839]
## Azure.Extensions.Configuration.Secrets:

https://apiview.dev/Assemblies/Review/219c02a8859145d099b452c108a4f65c

## Azure.AspNetCore.DataProtection.Blobs:

https://apiview.dev/Assemblies/Review/319f08f2dd7047bca764b421826763a8

## Azure.AspNetCore.DataProtection.Keys:

https://apiview.dev/Assemblies/Review/cbd5253252a04aaea102c60cc46f4c79

**Comment by KrzysztofCwalina** [comment]
I would just put all the APIs in one namespace: Azure.Extensions.AspNet
