### ISSUE TITLE
[BUG] Event Grid not publishing updated package

### ISSUE THREAD

**Issue by josiahvinson** [Azure/azure-sdk-for-net#10849]
**Describe the bug**
I've installed the latest version 3.2.0 of [Microsoft.Azure.EventGrid](https://www.nuget.org/packages/Microsoft.Azure.EventGrid/3.2.0) from nuget.org. The publish date is almost a year old. Data Lake v2 has introduced new fields in the `StorageBlobCreatedEventData` model that aren't present in the package.

**Expected behavior**
Specifically, I expect `ContentOffset` to be present in the package, since it's [in the repo](https://github.com/Azure/azure-sdk-for-net/blob/c530a249ee92cee2be108162e6392aa1a4b04838/sdk/eventgrid/Microsoft.Azure.EventGrid/src/Generated/Models/StorageBlobCreatedEventData.cs#L131) but it's not there. 
I would expect either a more updated package, either stable or the prerelease version referenced in the assembly.

**Actual behavior (include Exception or Stack Trace)**
The `StorageBlobCreatedEventData` class in the package doesn't have this field
![eventgridsdk](https://user-images.githubusercontent.com/57727190/77596095-3d515680-6eb8-11ea-88a7-14481db2eb54.PNG)

**To Reproduce**
Download the package.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.EventGrid 3.2.0 

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.1.511 [C:\Program Files\dotnet\sdk]
  2.1.512 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 - IDE and version : Visual Studio Enterprise Version 16.4.6

**Comment by ahamad-MS** [comment]
Thanks for reaching out. We have this task in our backlog and will address this appropriately. thanks.

**Comment by SeanFeldman** [comment]
@ahamad-MS @jfggdl, could you please leave the customer reported issue opened until it's resolved or point to the service-specific public issue to subscribe to and track the progress? Thank you.

**Comment by JoshLove-msft** [comment]
The updated `StorageBlobCreatedEventData` model is available in the new [EventGrid SDK](https://www.nuget.org/packages/Azure.Messaging.EventGrid/4.0.0-beta.2) that is currently in beta.

**Comment by ahamad-MS** [comment]
@josiahvinson   .. The issue is resolved in the newest SDK version. Can you please move to the new SDK and verify that. 

Feel free to close the issue if there is no more issues.

thanks

**Comment by josiahvinson** [comment]
It works, thanks!
