### ISSUE TITLE
Combined index and search swaggers

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#10874]
We should combine index and search swaggers, or at least refactor SearchError and any other common types into a referenced shared file. This is causing us to implement workarounds to rename one when generating source.

Setting this tentatively for the Preview 3 release, depending on when Search service plans to GA their currently preview (i.e. we should do this before they GA).

/cc @brjohnstmsft @tg-msft

**Comment by brjohnstmsft** [comment]
@heaths The Swaggers are pretty big to begin with. Keeping them separate makes maintenance easier.

Also, something to consider is that we may want to have different resources use different API versions at some point (something I believe some other Azure services do). I'm not sure how that fits into the single-file versus multi-file choice, but it's something to keep in mind.

**Comment by heaths** [comment]
Thanks for the heads up. @tg-msft had brought it up, but if there's no desire to combine them we can close this.

**Comment by AlexGhiondea** [comment]
Closing this for now.

**Comment by tg-msft** [comment]
Then we'll need to either see if AutoRest allows multiple remote swaggers now or update https://github.com/Azure/azure-sdk-for-net/blob/master/eng/CodeGeneration.targets to allow multiple AutoRest literate READMEs in one library.  We need to remove https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/generate.ps1 at some point.

**Comment by tg-msft** [comment]
(Filed https://github.com/Azure/azure-sdk-for-net/issues/11478 to track.)
