### ISSUE TITLE
WebSites.CreateOrUpdateAsync with slotName other than null breaks

### ISSUE THREAD

**Issue by Sam7** [Azure/azure-sdk-for-net#1088]
Creating a new website doesn't work as soon as a slotName other than `null` is defined
This affects the method `CreateOrUpdateAsync` in class `Microsoft.Azure.Management.WebSites.WebSiteOperations.WebSites`

### Exception details: ###

-----------------------
    System.AggregateException: One or more errors occurred. ---> Hyak.Common.CloudException: MismatchingResourceName: The provided resource name 'SomeAppName' did not match the name in the Url 'SomeAppName/AutoSwapSlot'.

       at Microsoft.Azure.Management.WebSites.WebSiteOperations.<CreateOrUpdateAsync>d__28.MoveNext()

       --- End of inner exception stack trace ---

       at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

       at Test.AzureManager.AsyncHelper.TryGetResult[T](Task`1 task, ILoggingProvider loggingProvider, String taskName) in c:\\code\\Test.AzureManager\\AsyncHelper.cs:line 30

    ---> (Inner Exception #0) Hyak.Common.CloudException: MismatchingResourceName: The provided resource name 'SomeAppName' did not match the name in the Url 'SomeAppName/AutoSwapSlot'.

       at Microsoft.Azure.Management.WebSites.WebSiteOperations.<CreateOrUpdateAsync>d__28.MoveNext()<---

Powershell seems to have the same problem: http://stackoverflow.com/questions/29772458/error-creating-web-app-slot-with-azure-powershell-cmdlet

**Comment by NaveenGoli** [comment]
PowerShell fix will be coming in the next release..

**Comment by NaveenGoli** [comment]
try the following..

            string webSiteSlotName = webSiteName;
            if (string.IsNullOrEmpty(slotName) == false)
            {
                webSiteSlotName = string.Concat(webSiteName, "/", slotName);

            }
           
            var createdWebSite = WrappedWebsitesClient.WebSites.CreateOrUpdate(
                        resourceGroupName, webSiteName, slotName,
                        new WebSiteCreateOrUpdateParameters
                        {
                            WebSite = new WebSiteBase
                            {
                                Name = webSiteSlotName,
                                Location = location,
                                Properties = new WebSiteBaseProperties(webHostingPlan)
                            }
                        });

**Comment by Sam7** [comment]
Thanks that's a good workaround
