### ISSUE TITLE
[FEATURE REQ] Add GetPathClient(path)

### ISSUE THREAD

**Issue by khshah3** [Azure/azure-sdk-for-net#10882]
[Azure.Storage.Files.DataLake]

An access pattern we often run into is that given a path fetch/do something and we don't care about whether its a file/directory. (i.e DataLakePathClient is enough to execute). For example, with DeleteIfExists. It would be invaluable for us to how unit-test friendly way to access the path client.

i.e. GetPathClient(path). 

This would simplify the access pattern.

**Comment by seanmcc-msft** [comment]
```FileSystemClient.GetPathClient()```
