### ISSUE TITLE
Task extensions synchronously complete ValueTasks

### ISSUE THREAD

**Issue by juunas11** [Azure/azure-sdk-for-net#10904]
In the Core project [TaskExtensions](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs), `GetAwaiter().GetResult()` is called on ValueTasks. According to this [article by Stephen Cleary](https://blog.stephencleary.com/2020/03/valuetask.html):

> However, this will not work for value tasks. You simply cannot block on value tasks. If you must block (again, this is never ideal), then you’ll need to convert the value task to a reference task by calling AsTask, and then block on that reference task.

So the extensions may work but are dependent on undefined behaviour. `AsTask()` should be called on the ValueTask first before consuming it synchronously.

**Comment by AlexGhiondea** [comment]
@AlexanderSher could you take a look here?
