### ISSUE TITLE
[BUG] Issuer provider is case sensitive for method CreateIssuerAsync().

### ISSUE THREAD

**Issue by wantedfast** [Azure/azure-sdk-for-net#10910]
**Description**
Tried to create a issuer with ProviderName "SslAdmin" failed while create it with name "SSLAdmin" success.
Is this expected result ?

Create Code
```
string providerName = "SslAdmin";
var issuer = new CertificateIssuer("test",providerName);
await client.CreateIssuerAsync(issuer); // Azure.RequestFailedException: 'Service request failed.
Status: 400 (Bad Request).

string correctProviderName = "SSLAdmin";
var correctIssuer = new CertificateIssuer("test", correctProvderName);
await client.CreateIssuerAsync(correctIssuer); // This would be success with Provder "SSLAdmin";
```

Get provider name of isuer from pre create issuer by portal. 
```
await foreach (var item in client.GetPropertiesOfIssuersAsync())
{
 Console.WriteLine(item.Provider); // The return value is "SslAdmin"
}
```

**Note:** 
From above code. Can see the return value of Provider is "SslAdmin". But If your create a new issuer with ProviderName "SslAdmin" with code will throw an exception.

**Comment by heaths** [comment]
Did you already create "SSLAdmin" and then try to create "SslAdmin"? It's not clear from the repo. I doubt the service is case-sensitive, too. /cc @schaabs @RandalliLama

**Comment by wantedfast** [comment]
Issuer provider is not case senstive after I checked it today. Seems I made some wired mistake in my past tests.
