### ISSUE TITLE
[QUERY] Setting LastModified and/or ETag on Directories in DataLake

### ISSUE THREAD

**Issue by Tornhoof** [Azure/azure-sdk-for-net#10919]
**Query/Question**
Is it possible to set a custom Last-Modified Date and/or ETag on a directory?
Motivation:
I want to synchronize a rather large and deeply nested directory structure from a local directory to Azure Data Lake and can't store metadata locally. This operation is then done incrementally e.g. nightly.
So the idea is that I either store a custom value (like the biggest last modified date of all elements (recursively) in a local directory) as a property on the directory in the datalake and than compare it against the local directory date to skip all the unmodified data.
The obvious choices in http headers would be last-modified and/or etag, but as far as I see I can't set them manually via the Api.  (I'm perfectly fine writing my own code to set it during/after creation, so if the basic REST API supports that, that would be fine.)

An alternative would be to use custom metadata and store it on the server, but that would require more calls to Azure (as ETag/LastModified is returned directly in ``GetPathsAsync()`` and as I'm talking quite a lot directories, that would mean quite a lot extra calls just to get one metadata).

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] Azure.Storage.Files.DataLake 12.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 
.NET Core SDK (gemäß "global.json"):
 Version:   5.0.100-alpha1-015757
 Commit:    f5d3c3dd00
- IDE and version : [e.g. Visual Studio 16.3] Visual Studio 16.5

**Comment by amishra-dev** [comment]
@amnguye to answer

**Comment by amnguye** [comment]
Hi,

Our REST API does not allow to change the Last Modified Date or ETag on Directories or Paths.

https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update

**Comment by Tornhoof** [comment]
Thank you for your answer.
