### ISSUE TITLE
Add response or response headers to RequestFailedException

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#10922]

**Comment by MiYanni** [comment]
You get something like this in Message. Would be nice to have the information as separate properties (Content and Headers) for easy parsing/identification of the issue.
```
Service request failed.
Status: 501 (Not Implemented)

Content:
123

Headers:
X-Powered-By: REDACTED
Vary: REDACTED
Access-Control-Allow-Credentials: REDACTED
Access-Control-Expose-Headers: REDACTED
ETag: W/"3-QL0AFWMIX8NRZTKeof9cXsvbvu8"
Date: Wed, 15 Apr 2020 21:42:30 GMT
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Content-Length: 3

```

**Comment by drwill-ms** [comment]
Another example for 429 is the retry-after header

**Comment by stewartadam** [comment]
+1 it's not clear what the expected template for responses is, and if we can count on it always being in the format above. The SDK should be exposing these fields to callers to prevent ugly regex hacks that are prone to breaking.

**Comment by heaths** [comment]
> +1 it's not clear what the expected template for responses is, and if we can count on it always being in the format above. The SDK should be exposing these fields to callers to prevent ugly regex hacks that are prone to breaking.

It's worth asking why this information is needed, though. We [recommend against](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#:~:text=Do%20not%20use%20this%20mechanism%20to%20provide%20information%20developers) using it for branching in code because the data is guaranteed to be compatible.

**Comment by stewartadam** [comment]
429 was the big one, as services often include a retry-after header that must be parsed and presently is inaccessible.

**Comment by JoshLove-msft** [comment]
> 429 was the big one, as services often include a retry-after header that must be parsed and presently is inaccessible.

This should already be handled by the [RetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs#L303).
