### ISSUE TITLE
[BUG] Sample app doesn't build, doesn't run - missing pieces?

### ISSUE THREAD

**Issue by rgamage** [Azure/azure-sdk-for-net#10935]
**Describe the bug**
Opening Azure.Messaging.EventHubs.Samples.csproj with VS 2019, when trying to build, output says "0 succeeded, 0 failed, 1 up-to-date", but there are no /bin or /obj directories created, unable to run the project with F5, error message that the /bin/.../...exe file does not exist.

**Expected behavior**
Open in VS 2019, build and run successfully with no errors or changes to the code.

**Actual behavior (include Exception or Stack Trace)**
See above description.  Other observations: The .csproj file mentioned above references another .csproj file, like this:

```
<ProjectReference Include="..\src\Azure.Messaging.EventHubs.csproj" />
```
But that file is not included with this .zip archive.
Another observation, the targeted framework version has this line:
```
    <TargetFrameworks>$(RequiredTargetFrameworks)</TargetFrameworks>
```
I'm not sure where this variable is supposed to come from in a local dev environment like this.  It is not in an Azure Dev Ops environment where that kind of variable would make sense.

```
(1850,5): Error: The referenced project '..\src\Azure.Messaging.EventHubs.csproj' does not exist.
C:\Program Files\dotnet\sdk\3.1.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(93,5): Error: The TargetFramework value '' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.  Download .zip file of code
2.  Unzip code, open in VS 2019, 16.5.1
3.  Press F5 to build and run

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10, VS 2019, 16.5.1
.NET Core SDK 3.1.200

**Comment by AlexGhiondea** [comment]
@rgamage thanks for reporting this -- can you share where you downloaded the zip file from?

Have you tried cloning/forking this repo and opening the project from it?

**Comment by rgamage** [comment]
I just created a second issue - identifying where the poorly-packaged zip
is coming from:

https://github.com/Azure/azure-sdk-for-net/issues/10937

**Comment by AlexGhiondea** [comment]
Thank you -- should we close then one of the issues?

**Comment by rgamage** [comment]
Yes, I think so.  Sorry I didn't initially understand the issue.  The way
GitHub works makes it very difficult to download a sub-set of a large repo
like this.  I imagine many new devs just want to download a working sample
solution, not the entire SDK...

Randy

**Comment by AlexGhiondea** [comment]
Indeed -- we are working on ways to make that better.

In the mean time, the easiest way to get started is to follow these samples (https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs/samples) which is the same page you linked to originally.

You would need to download the sample you are interested in and the `infrastructure` folder.

/cc @jsquire and @kinelski as well.

@rgamage if you don't mind, I'll go ahead and close issue #10937

**Comment by rgamage** [comment]
Thanks for your quick response and advice.  However, I want to caution you
against giving exactly this advice.  If I follow your instructions, I end
up wasting a couple hours trying to figure out what is wrong.  That folder
you mention does not have all the necessary code, and neither does the .zip
file referenced in my second Issue.  You also need
../src/Asure.Messaging.EventHubs.csproj, which contains a lot of code and
is a dependency of the Samples app.  Extracting the files needed to have a
working solution takes a LOT of time, and is a real pain in the ass right
now.  This should not be so difficult.  We need a Git close link, so we can
Clone and GO!

Randy

**Comment by AlexGhiondea** [comment]
@rgamage thanks for the feedback. 

I was trying to provide with a solution that does not require you to clone the entire repo. 

The easiest way to get started (today) is to close the entire repo and start from there. I agree that that is not necessarily the best solution and we are working on options that will allow you to clone and go.

Would you mind sharing more about what you are looking to get started with so we can help?

**Comment by rgamage** [comment]
Yes, would be glad to share.  My company (TechnipFmc) is launching a
project to connect our ROV  (sub-sea) vehicle's telemetry data to our
customers, by using Azure IoT Cloud platform.  We are all (devs) just
learning about the IoT technology.  We have a sample temperature simulator
device sending data to an IoT Edge device, per quickstart guides, and now
we want to see how we can read this data and display it in a .NET web app.
I'm a Blazor developer so am hoping to avoid Javascript, that's why I went
looking for a .NET C# way to read data from the EventHub.

I was looking for the simplest way to read data from our new test hub.  I
got the sample working, by cloning the entire repo and running that sample
solution.  Now I'm trying to create my own bare bones console app to do a
similar thing, but just reading new temperature data.  I'm finding that the
project Azure.Messaging.EventHubs has a LOT of code in it, seems like all
that should be in a Nuget somewhere we can just reference - do we really
need all this code added to every client that wants to read some data?
(UPDATE - I see now there is a Nuget that looks like it could replace this
code: https://www.nuget.org/packages/Azure.Messaging.EventHubs/5.0.1)

Eventually we will want to push the data to a web UI for real time data
display, so I am imagining adding a SignalR hub in Azure and connecting it
to the EventHub, and receiving data in our web app over SignalR.  Does this
sound like a good approach, or is there a better way?  It seems like the
sample code needs to poll in a loop that periodically locks the thread, etc.

Thanks for your time,
Randy

**Comment by jsquire** [comment]
@AlexGhiondea:  If you'd be so kind, please leave #10037 open; I'd like to use it to pursue discussion of the tool that does the export to the Docs site.

**Comment by jsquire** [comment]
Hi @rgamage. We're sorry that you're experiencing difficulties; your expectations around the published .zip file are definitely reasonable.   I've started some conversation in #10037 to discuss an approach to fixing this.

In the meantime, looking at the zip file, I believe that there are two changes you could make for it to run stand-alone, both of which you identified:

- Line 6 would change to a specific framework, such as:  `<TargetFrameworks>netcoreapp2.1</TargetFrameworks>`
- Line 20 would change to a package reference:  `<PackageReference Include="Azure.Messaging.EventHubs" Version="5.0.1" />`

If you decide to go down that path and run into further troubles, please let me know and I'd be happy to help get things running.

**Comment by rgamage** [comment]
Thanks for your help, yes that seems like that would work.  By now I've
created my own new solution, and added the files I need manually from the
repo, and added a ref to the nuget you mentioned.  Some other feedback -
the Sample 9, reading only new events, is a great use case (I want to
display new data as it comes in, etc.), but the sample is really confusing
to read through.  I have no idea what it's doing or why it was designed
that way.  Why not start reader first on one thread, then start publishing
new data on another thread, to demo the function?  It seems set up
backwards, starts by publishing only two data items, then quickly tries to
catch those as new data - weird to me.  Even simpler would be for this
sample to only read.  Just assume the user will direct it to an event hub
that is already issuing new data.  Also the default tutorials create IoT
hubs that are not publicly writable, so even Sample 5 fails, which from its
title should only read data, but actually tries to publish data first, and
fails for me due to these permissions.  Keep the samples simple.

Randy

Randy

**Comment by jsquire** [comment]
Hi Randy,

Thank you for the feedback.  In the basic samples, such as Sample 5, we use a simple approach of publishing events and then reading back a set number from the beginning of the partition.  You may or may not see the events that you just published, but it isn't important.  Our goal for that sample is to demonstrate the basic flow of reading.

The purpose of Sample 9, as you can guess from its title, is to demonstrate a technique for ensuring that you read only the events that you've just published.  Because Event Hubs is a persistent stream from which events are not removed after being read, we're unable to take a simple approach of sending some events and then point the consumer/processor at the beginning of the stream and read because we cannot be sure exactly what is a partition.   If you ran other samples, there would be an unknown number of events already in the partition.  Likewise, you'd see the same when the running the  same multiple times.   

There are two mainstream techniques to starting in a known state, both with complexity trade-offs to consider.  The one that we're demonstrating is positioning the consumer at the end of the stream and having it continue to attempt to read while publish events that it can see.  Lines 43 - 62 attempt to describe the technique and detail the approach.   If you're finding that doesn't meet that goal, we'd be very interested in your thoughts around how to improve that.

With respect to permissions and IoT Hub, our samples are written to run against Event Hubs and require permission to read and write.  We strongly advise using the resource that our ARM template _(deployable directly from the [Samples page](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs/samples))_ generates, which ensures that the expected resources exist and permissions are applied.

Because IoT Hub is an independent service and not part of Event Hubs, the Event Hubs client library does not have special insight or awareness of it.  At this point in time, it isn't a goal to cover IoT Hub scenarios in the Event Hubs samples; those would be better aligned with the IoT Hub client libraries.

**Comment by rgamage** [comment]
Thanks for this information, all makes sense, except the part about
EventHubs vs. IoT Hubs.  The difference in these is confusing, as I read
the docs it seems like an IoT Hub implements an EventHub-compatible
endpoint by default. If you google "azure iot hub read messages" as I did
yesterday, the first 3-4 articles explain about EventHub messaging, as
the (apparently) recommended way to talk to IoT hubs.  Articles like:

https://devblogs.microsoft.com/iotdev/read-azure-iot-hub-device-to-cloud-messages-from-the-built-in-and-custom-endpoints/
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-builtin

From this research, I was assuming I was going down the most direct path to
get device data from our IoT hub.  Now you mentioned there is an IoT Client
library, I looked for it here:
https://azure.github.io/azure-sdk/releases/latest/index.html#net-packages
I couldn't find anything on this page of Azure SDK libs referencing IoT
Client.  After more searching maybe you're referring to
Microsoft.Azure.Devices?  That looks like a lighter weight method of
getting device data.  Should this library appear on the page with all the
other Azure libs?

Sorry for the long-winded back and forth on this topic, but I'm hoping to
give you a window into one hapless developer's journey into a new space.
I've been doing this for 20 years, and always seem to struggle when moving
to a new technology.  Good docs are hard, I understand, and I think the MS
team is doing a fantastic job, especially these last few years.

Randy

**Comment by jsquire** [comment]
Apologies for the confusion, and thank you for the kind words.   Your perspective and feedback is very much appreciated; we'll definitely be sharing your thoughts with folks working on the higher level documentation and cross-service scenarios as well as the individual client library teams.

To try and clarify what I was attempting to describe, in a nutshell, the IoT Hub service and Event Hubs service are independent Azure offerings.   When an IoT Hub is provisioned,  it creates a set of Event Hubs namespaces that the IoT Hub service owns and uses for devices.  You're certainly welcome to use those Event Hub instances with the Event Hubs client library, but our sample scenarios aren't based around the specifics of how IoT Hub works - they're focused on the core Event Hubs operations.

**Comment by jsquire** [comment]
It seems as if the conversation has completed; I'm going to close this out, but please feel free to reopen if you would like to resume discussion.
