### ISSUE TITLE
How to Export Azure SQL DB and Upload it into Azure Blob storage

### ISSUE THREAD

**Issue by mymatrixpixel** [Azure/azure-sdk-for-net#10931]
Hi Team,
I want to take azure SQL database full backup and upload it into azure blob storage.

Do we have any direct c# method to upload directly into azure blob storage(container).

Since we have ExportBacpac method in Microsoft.sqlserver.DacFx - version (150.4573.2).

Also, Am using Azure.Storage.Blobs 12.4 version library. Always getting error "unable to read daa from the transport connection. The I/O operation has been aborted because of either a thread exit or an application host".

Do we have any efficient way to upload into azure blob storage?

**Comment by mymatrixpixel** [comment]
@tg-msft  can you help?

**Comment by amishra-dev** [comment]
Can you please share logs of the output you got?
Have you tried just downloading the data and just uploading it with the sdk?

**Comment by mymatrixpixel** [comment]
1. Exporting SQL DB as .bacpac file.
2. Uploadig it into blob storage.

Error : unable to read daa from the transport connection. The I/O operation has been aborted because of either a thread exit or an application host.

Is there any way directly uploading it into blob storage by using C# code. Also, I referred Microsoft.Azure.Management.Sql nuget library . It has the feasability. But this package is in preview.

**Comment by mymatrixpixel** [comment]
Team,

Can you share sample code to export(full Backup) a azure SQL DB to blob storage and import (Restore) using "Microsoft.Azure.Management.Sql".

**Comment by amishra-dev** [comment]
@mymatrixpixel that is not a sample, it will be a solution. Can you please share what you have and we can suggest tweaks that can help. 
Our samples are shared here. https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs/samples

**Comment by mymatrixpixel** [comment]
@amishra-dev  I have already referred that github link. Also you kept that examples in "sample" folder. 

var client = new SQL management client(serviceclientcredentials, new loghandler()).

1. In the above statement how to get serviceclientcredentials (here I don't have clientid and client secret, and tenentid). To get the information ,do we need to register or any other way is there?.
2. loghandler(implementation code ) only am looking. Rest of the solution I already completed.

Thanks.

**Comment by amishra-dev** [comment]
To get the clientid, client secret and tenant id, you need to register an application with Azure AD, the steps are here https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal

I am not aware of how the SQL management client works, so i can't help you there, sorry.

**Comment by mymatrixpixel** [comment]
No issues. Thanks.
