### ISSUE TITLE
v2.6 fails a debug session if no Local ServiceConfiguration is present

### ISSUE THREAD

**Issue by djfr** [Azure/azure-sdk-for-net#1094]
We had an issue where after we migrated to 2.6 from 2.5 we were getting:
2>unable to get setting value
2>Parameter name: profileNameError: Cancelled

When starting a debug session. Our continuous deployment pipeline where we package through MSBuild with /t:Publish and deploy with PowerShell was working fine.

This was because we don't have neither a Local or Cloud profile in the project. We use a profile per solution configuration that matches the name of the solution configuration. So our "Local" profile is named "Debug".

We use the "TargetProfile" element for each configuration to specify the right service configuration.

Once a local profile was created from a copy of the Debug profile, everything worked fine.

**Comment by shahabhijeet** [comment]
@djfr please open a new issue if the problem still exists/repros.
