### ISSUE TITLE
Update Azure.Identity readme

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#10957]
- [ ] Update type references to point to reference docs on docs.microsoft.com
- [ ] Add exception handling sample to troubleshooting section
- [ ] Add enable logging to troubleshooting section

**Comment by logiclabs** [comment]
Any chance of adding documentation to cover developer scenarios and what is/isn't supported  currently?  I realize it's in flux, but there is almost no documentation on SharedTokenCache, AzCli or VisualStudio credential use in DefaultAzureCredential.

Mainly looking at an explanation of why the VS auth integration doesn't work, and ways around it (I've finally managed to use the latest beta with az-cli to give an option of using dev credentials, but it's been painful finding the info)

**Comment by christothes** [comment]
This appears to be complete
