### ISSUE TITLE
[FEATURE REQ] Add developer setting to generate API listings and update snippets on build

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#10998]
Everybody always forgets to run https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Export-API.ps1 and https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Update-Snippets.ps1 before they submit their PRs.  I've suggested git hooks as a workaround, but it would also be nice to add a setting that does both of these steps automatically when we build.  It could be defaulted to an env var like `AZURE_DEV_BUILD_ARTIFACTS` so interested parties could amortize the time spent updating PRs with API listings across every single build they do from here on out.

**Comment by tg-msft** [comment]
//fyi @pakrym @chidozieononiwu @annelo-msft @kasobol-msft @seanmcc-msft if you want to add any thoughts

**Comment by seanmcc-msft** [comment]
Please add this.  It's really non-fun waiting for CI for 10 minutes, just to fail the analyze step over Export-API.ps1.

**Comment by pakrym** [comment]
This might slow down inner dev loop (change-build-test) a lot.

**Comment by tg-msft** [comment]
> This might slow down inner dev loop (change-build-test) a lot.

Yep - that's why I think we should make it optional.  We could also consider providing default implementations of commit hooks for people use, but I think mirroring what we do for ApiCompat on build already will be less difficult for folks to make use of this.

**Comment by kasobol-msft** [comment]
Would it be possible to have these scripts run in single csproj scope to speed up inner dev lopp?

**Comment by pakrym** [comment]
Yes, but even then build time would be up at least 2x

**Comment by tg-msft** [comment]
> Yes, but even then build time would be up at least 2x

"at least 2x" feels like a stretch from what I've seen.  These complete pretty quickly when you run them on single projects.

**Comment by tg-msft** [comment]
Huh.  I guess time just passes quicker when you get old and anything less than a minute feels fast enough.  :smile:

**Comment by kasobol-msft** [comment]
Fast enough for me. I'll take that instead of minutes of waiting at PR!

**Comment by kurtzeborn** [comment]
@chidozieononiwu git hooks aren't as reliable as we'd like to see for something like this, so let's implement the env var suggestion @tg-msft made `AZURE_DEV_BUILD_ARTIFACTS`.

**Comment by weshaggard** [comment]
I don't like git hooks as they are not reliable as has already been stated. I could get behind a msbuild property (i.e. `dotnet build /p:UpdateSource=true`) that people could pass to the build that would run these extra steps which would potentially modify the source in the repo.

**Comment by chidozieononiwu** [comment]
Please see updated contributing docs for how to use these settings https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md#updating-source-on-build
