### ISSUE TITLE
[BUG] Service Bus raises an incorrect exception for  legal values of ForwardTo 

### ISSUE THREAD

**Issue by redtaped** [Azure/azure-sdk-for-net#11009]
**Describe the bug**
Receiving an erroneous error "{0} exceeds the '260' character limit. (Parameter 'ForwardTo')" when setting ForwardTo to a value less than 260 characters, but which would exceed it when the base path is prepended.

**Expected behavior**
The maximum name supported is 260 characters, but that should exclude the base path.

**Actual behavior (include Exception or Stack Trace)**
Microsoft.Azure.ServiceBus.ServiceBusException: 'Entity path 'sb://sanitized-base-east-us-sanitized.servicebus.windows.net/integration-test-pc-name-lt-azureservicebusamqpconnection-sanitized.messagequeue.client.tests.integration.chain.provisionflowconsumer-sanitized.messagequeue.client.tests.integration.chain.request.sqlservermessage' exceeds the '260' character limit. (Parameter 'ForwardTo')'

In this situation, the base path is appended by the framework by the following code located in [_SubscriptionDescriptionExtensions.cs_](https://github.com/Azure/azure-sdk-for-net/blob/7aa408bfc14350aa9f390b682d515f6cd25daa3e/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Management/SubscriptionDescriptionExtensions.cs)

`description.ForwardTo = NormalizeForwardToAddress(description.ForwardTo, baseAddress);`

The setter of ForwardTo then runs validation which causes the exception to be thrown.

**To Reproduce**
```
var description = new SubscriptionDescription(topicName, subscriptionName)
{
    ForwardTo = queueName,  
    // where queuename is less than 260 characters EXCLUDING the base address
    // sanitized code
};

if (await _managementClient.SubscriptionExistsAsync(description.TopicPath, description.SubscriptionName))
{
    // sanitized code
}
```

**Environment:**
Microsoft.Azure.ServiceBus v4.1.2

.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

**Comment by nemakam** [comment]
@redtaped , thanks for raising this issue. We will work on this fix. Meanwhile, if you are blocked, feel free to raise a PR.

**Comment by redtaped** [comment]
> @redtaped , thanks for raising this issue. We will work on this fix. Meanwhile, if you are blocked, feel free to raise a PR.

PR submitted, but I do not have access to link to the issue.
https://github.com/Azure/azure-sdk-for-net/pull/11059

**Comment by nemakam** [comment]
Fixed in #11059

**Comment by nemakam** [comment]
`ForwardDeadLetterTo` should also have been updated. Forgot about that. And also, this needs to be updated in `QueeuDescription` as wel.

**Comment by redtaped** [comment]
> 
> 
> `ForwardDeadLetterTo` should also have been updated. Forgot about that. And also, this needs to be updated in `QueeuDescription` as wel.

Thank you @nemakam, I've created a new pull request to address these remaining issues by refactoring the code and adding some additional unit tests.  #11098

**Comment by nemakam** [comment]
@redtaped , thank you for getting back with another PR. Really appreciate it!
