### ISSUE TITLE
[FEATURE REQ] Make deps.json file available for consumption by PowerShell team

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#11008]
Upload the deps.json file from the build next to our dependency reports so they can easily be pulled by the PowerShell team.

Upload Folder should be https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-net/dependencies/

**Comment by weshaggard** [comment]
After my recent changes to apicompat https://github.com/Azure/azure-sdk-for-net/pull/12703 the solution put in https://github.com/Azure/azure-sdk-for-net/pull/11818 no longer works.

FYI @heaths

**Comment by weshaggard** [comment]
Part of this work was completed with https://github.com/Azure/azure-sdk-for-net/pull/13053. However I think we still have some more work to do and should merge this in with the analyze dependency step so we can also check the dependencies against powershell dependencies.

**Comment by weshaggard** [comment]
Fixed with https://github.com/Azure/azure-sdk-for-net/pull/13656.
