### ISSUE TITLE
[BUG] An attempt to append file, while specifying zero content causes the client lib to fail in parsing server's error code

### ISSUE THREAD

**Issue by levroz** [Azure/azure-sdk-for-net#11002]
**Describe the bug**
A call to DataLakeFileClient.AppenAsync() with zero-length content fails on the server side (which is kind of expected) with HTTP 400. But the client library fails to parse the response. As a result, System.Text.Json.JsonException is being thrown to the caller instead of the expected RequestFailedException. 

**Expected behavior**
An exception of type RequestFailedException with the details of the server-side error should be thrown.

**Actual behavior (include Exception or Stack Trace)**
And exception of System.Text.Json.JsonException is being thrown instead.

**To Reproduce**
1. Create an instance of DataLakeFileClient and authenticate.
2. Try to append a BLOB/file by calling to AppenAsync() ,while providing a zero-size stream.
3. The server-side fill return 400, but the client side will fail to parse the server's response

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.2.0
 - Hosting platform or OS and .NET runtime version: 

.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

 - IDE and version : VS 2019
[File append operation - client side exception.txt](https://github.com/Azure/azure-sdk-for-net/files/4423371/File.append.operation.-.client.side.exception.txt)
[File append operation - Fiddler call.txt](https://github.com/Azure/azure-sdk-for-net/files/4423372/File.append.operation.-.Fiddler.call.txt)

**Comment by Tornhoof** [comment]
Same as #9489
