### ISSUE TITLE
Automate C# generator update

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#11019]
My usual steps:
1. Update versions in https://github.com/Azure/azure-sdk-for-net/blob/master/eng/CodeGeneration.targets#L4-L6 

Most often I update the _AutoRestCSharpVersion, other two are updated more rarely.

2. Run `dotnet msbuild /t:GenerateCode .\eng\service.proj`

3. Fix issues - because how much the generator churns right now there is always something to fix but I expect the need to go down when it gets more stable. This obviously would have to be done by a person by pushing commits into the auto PR.

**Comment by weshaggard** [comment]
Do you always take the latest version from https://github.com/Azure/autorest.csharp/releases and https://github.com/Azure/autorest/releases?

**Comment by pakrym** [comment]
I try to keep them in sync with https://github.com/Azure/autorest.csharp/blob/feature/v3/readme.md#L18 and https://github.com/Azure/autorest.csharp/blob/feature/v3/package.json#L6 but they don't change often so might not need automation.

**Comment by pakrym** [comment]
Done
