### ISSUE TITLE
[FormRecognizer] Remove ForwardsClientCalls attributes from client methods

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#11023]
## Summary

The `ForwardsClientCalls` attribute has been added to client methods so they don't need diagnostics validation during test runs.

https://github.com/Azure/azure-sdk-for-net/blob/37ee6871f795b76157ec66edab2e9ddca705e6a9/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ReceiptClient.cs#L62

The diagnostics validation needs to be skipped because the Code Generator is not setting scope names correctly (see: [#575](https://github.com/Azure/autorest.csharp/issues/575)), so tests are expected to fail.

## Goals

- Coordinate with CodeGen to have proper scope names being generated. This may need changes on our side as well.
- Remove all `ForwardsClientCalls` attributes from the client code.
- Make sure unit tests still pass consistently.
- Remove `ForwardsClientCallsAttribute.cs` from the project file as it won't be needed anymore.

https://github.com/Azure/azure-sdk-for-net/blob/37ee6871f795b76157ec66edab2e9ddca705e6a9/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Azure.AI.FormRecognizer.csproj#L28

**Comment by annelo-msft** [comment]
@kinelski, I believe this is complete - can you confirm and close if so?

**Comment by maririos** [comment]
we haven't removed it. See => https://github.com/Azure/azure-sdk-for-net/blob/5ab80ac686b2db2be33d3b4aa4aba72b255f4f67/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormTrainingClient.cs#L100
Also, with latest changes to codegen, looks like now we do need to remove it.

See PR https://github.com/Azure/azure-sdk-for-net/pull/11860

**Comment by kinelski** [comment]
Increasing estimate since we'll need to add diagnostics scopes ourselves, including for LROs, and perform validation on them.
