### ISSUE TITLE
[FEATURE REQ] Support for parsing Content-Range headers

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-net#11038]
Looking to either extend Azure.HttpRange, or introduce new struct HttpContentRange, that provides an object model of the well-known Content-Range HTTP header.

In the context of the needs of Azure.Storage to parse this header, the storage service returns the full `<unit> <range-start>-<range-end>/<size>`, and we make use of both the range and total size for decision-making in high-level features.

**Library or service name.**
Azure.Core
 
**Is your feature request related to a problem? Please describe.**
It can be important in many scenarios to know the exact range of the original data a response is streaming. This header is how that is communicated, and those who need to know that are forced to parse the header themselves. This could be centralized code for all SDKs to have access to.

**Comment by tg-msft** [comment]
The [Range header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) supports these syntax forms:

```http
<unit>=<range-start>-
<unit>=<range-start>-<range-end>
<unit>=<range-start>-<range-end>, <range-start>-<range-end>
<unit>=<range-start>-<range-end>, <range-start>-<range-end>, <range-start>-<range-end>
<unit>=-<suffix-length>
```

Our [HttpRange](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/HttpRange.cs#L15) allows two fixed unit syntax forms today for the Range header:

```http
bytes=<range-start>-<range-end>
bytes=<range-start>-
```

The [Content-Range header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range) supports three syntax forms:

```http
<unit> <range-start>-<range-end>/<size>
<unit> <range-start>-<range-end>/*
<unit> */<size>
```

It looks like we'll need a separate `HttpContentRange` struct type to support these.  


@jaschrep-msft - Can you update the bug to include which of the syntax forms you'll require to implement your scenarios?  I imagine we'll fix `<unit>` to `bytes` for example, but we also might not implement `<size>` yet if you only need support for `bytes <range-start>-<range-end>/*`, etc.

@pakrym - FYI that this will be coming to Azure.Core at some point

**Comment by jaschrep-msft** [comment]
@tg-msft I updated the description to say that Storage needs the full `<unit> <range-start>-<range-end>/<size>`. I have not observed the service to ever return a unit other than bytes, but I do not see this guarantee in the REST API documentation.

**Comment by tg-msft** [comment]
Given the latest direction, is this still needed in Azure.Core or can we close the issue?
