### ISSUE TITLE
EventProcessorClient: CreateConnection() Exception not surfaced

### ISSUE THREAD

**Issue by serpentfabric** [Azure/azure-sdk-for-net#11032]
### Describe the bug

When a user calls StartProcessing() then that function subsequently makes the following call to [CreateConnection](https://github.com/Azure/azure-sdk-for-net/blob/cd3429fae25091f71b4d8571d964b0303571486e/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor%7BTPartition%7D.cs#L566). That call, despite not being enclosed in a try catch, can and will throw an exception and when it is it seems:

- processing never starts
- no error is raised
- there's no indication of a problem
- the application using the client has no way to know a fatal error occurred, if, say, events are seldomly received.

### Expected behavior
A fatal error, that can't be automatically or eventually recovered, should be surfaced immediately upon death

### Actual behavior (include Exception or Stack Trace)
The offending call is [started here](https://github.com/Azure/azure-sdk-for-net/blob/cd3429fae25091f71b4d8571d964b0303571486e/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor%7BTPartition%7D.cs#L696) and, if either [StopProcessing() or Dispose()](https://github.com/Azure/azure-sdk-for-net/blob/cd3429fae25091f71b4d8571d964b0303571486e/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor%7BTPartition%7D.cs#L1383) is called then it will surface to the user, far too late.

### To Reproduce
The aforementioned exception was thrown in my case [here](https://github.com/Azure/azure-sdk-for-net/blob/cd3429fae25091f71b4d8571d964b0303571486e/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubConnection.cs#L153), when eventHubName wasn't specified using [this constructor](https://github.com/Azure/azure-sdk-for-net/blob/cd3429fae25091f71b4d8571d964b0303571486e/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L309)

### Environment:
```
<PackageReference Include="Azure.Messaging.EventHubs" Version="5.0.1" />
<PackageReference Include="Azure.Messaging.EventHubs.Processor" Version="5.0.1" />
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  2.2.207 [c:\Program Files\dotnet\sdk]
  3.1.100 [c:\Program Files\dotnet\sdk]
  3.1.102 [c:\Program Files\dotnet\sdk]
  3.1.200 [c:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.14 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.14 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [c:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.14 [c:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [c:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [c:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [c:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [c:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [c:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.2 [c:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by jsquire** [comment]
Hi @serpentfabric.   We're sorry that you're experiencing difficulties and appreciate you reaching out to let us know.  The scenario that you've identified was indeed a bug in the processor; the connection should have been created within a try/catch that surfaced any issues to the error handler.

I'm happy to report that this was something that had been identified and has since been fixed.  The next release of the processor contains the fix, along with other fortifications around resilience and error visibility.  It is expected to be released to preview shortly.
