### ISSUE TITLE
Namespace 'Azure.Management.Storage' shouldn't contain public types. Use one of the following pre-approved namespace groups (https://azure.github.io/azure-sdk/registered_namespaces.html)

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#11041]

**Comment by blueww** [comment]
@erich-wang 
Would you please give more details for this request?
For the 4 storage namespace from your linked doc, they are all for dataplane, not for management plane. So change dataplane and management plane SDK use same namespace might it's difficult to write code. And there are no proper namespace for the management plane object like storage account.

Besides that, change namespace is a breaking change. We need enough business justification to do it.

```
azure.storage.blobs | Azure Storage
azure.storage.files.shares | Azure Storage
azure.storage.files.datalake | Azure Storage
azure.storage.queues | Azure Storage
```

**Comment by blueww** [comment]
As discussed with @erich-wang , this is for Track2, and I could safely ignore the issue.
Unassign myself.

**Comment by erich-wang** [comment]
namespace was registered
