### ISSUE TITLE
[BUG] Azure.Core: RawRequestUriBuild failed to set port when not specified in host

### ISSUE THREAD

**Issue by allenjzhang** [Azure/azure-sdk-for-net#11051]
**Describe the bug**
With generated XXRestClient code, if host does not contain port number, the generated Uri has port as 0 which would not work.
`            var uri = new RawRequestUriBuilder();
            uri.AppendRaw(host, false);
            uri.AppendPath("/subscriptions/", false);
            uri.AppendPath(subscriptionId, true);
            ...
            request.Uri = uri;
`

**Expected behavior**
With host = "https://management.azure.com"
request.Uri should be just https://management.azure.com/subscriptions/

**Actual behavior (include Exception or Stack Trace)**
`request.Uri = "https://management.azure.com**:0**/subscriptions/"; // This does not work.`

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.  Use autorest code gen a management plane swagger
2. You will see following gets generated:
`        internal DashboardsClient(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, string subscriptionId, string host = "https://management.azure.com", string apiVersion = "2019-01-01-preview")
        {
            RestClient = new DashboardsRestClient(clientDiagnostics, pipeline, subscriptionId, host, apiVersion);
            this.clientDiagnostics = clientDiagnostics;
            this.pipeline = pipeline;
        }
`
3. This does not work. Changing host= "https://management.azure.com:443" works.

Looking at the code, either should default the port be set in RawWritingPosition.schema or in host where separator not detected.

**Environment:**
 - Azure.Core 1.1.0

**Comment by pakrym** [comment]
Closing this as I think it was resolved by rebasing on the newer generator version.
