### ISSUE TITLE
[FEATURE REQ] Expose StorageSharedKeyCredential from BlobServiceClient

### ISSUE THREAD

**Issue by mwikstrom** [Azure/azure-sdk-for-net#11055]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
We initialize blob service client instances from a connection string with account key.

We need to use sas tokens to copy blobs within the storage account. For this we need access to the account key. 

We want to avoid passing around both a `BlobServiceClient` and a `StorageSharedKeyCredential` - it should be enough to just have a `BlobServiceClient` since it indeed have the account key under the hood.

This feature request is that `BlobServiceClient` expose a property that returns the underlying `StorageSharedKeyCredential` when its `AuthenticationPolicy` is a `StorageSharedKeyPipelinePolicy` and otherwise a null reference.

This would simplify the scenario when the client is used to upload blobs/blocks "from uri" in the same storage account.

For reference; we are currently using the following reflection hack to achieve the functionality that this request is about:

```c#
internal static StorageSharedKeyCredential? TryGetSharedKeyCredentialUsingReflection(
    this BlobServiceClient client)
{
    var policyProperty = typeof(BlobServiceClient).GetProperty(
        "AuthenticationPolicy",
        BindingFlags.Instance | BindingFlags.NonPublic);

    if (policyProperty is null)
    {
        return null;
    }

    var policy = policyProperty.GetValue(client);

    if (policy is null)
    {
        return null;
    }

    var policyType = policy.GetType();
    var credentialsField = policyType.GetField(
        "_credentials",
        BindingFlags.Instance | BindingFlags.NonPublic);

    if (credentialsField is null)
    {
        return null;
    }

    return credentialsField.GetValue(policy) as StorageSharedKeyCredential;
}
```

**Comment by kurtzeborn** [comment]
CC: @amishra-dev @jaschrep-msft

**Comment by amishra-dev** [comment]
@mwikstrom we are refactoring SAS and will have an update for you when we get closer to private preview. we do appreciate your feedback and please let us know if you have any other suggestions for us.

**Comment by mwikstrom** [comment]
Thank you @amishra-dev! Will you post the update here in this github issue, and can you share an approximate date when this might be available?

**Comment by amnguye** [comment]
Hi,
We added the capability to avoid passing around the Shared Key Credentials, and to generate the SAS from the client. So when you initialize your client you should be able to call `GenerateSas(BlobSasBuilder)` or `GenerateSas(permissions, expiresOn)` and it will create a SAS based on the connection string / shared key credentials you passed to the client when you initialized it.

See PR 15972
