### ISSUE TITLE
[QUERY]  In Microsoft.Azure.ServiceBus how do we perform OnMessageAsync and OnCloseSessionAsync 

### ISSUE THREAD

**Issue by pvreddy37** [Azure/azure-sdk-for-net#11061]
hi People. Just need your help and assistance on the below questions.
Earlier we are using session queues with Microsoft.ServiceBus.Messaging with below approach

**Current Appracoh:**
creating a queue client and we are registering to RegisterSessionHandlerFactory( with a call back and Session handler)
We are inherting IMessageSessionAsyncHandler and overriding OnMessageAsync,OnCloseSessionAsync to handle messages and closing functionality of sessions.
we mainly depend on these member functions (OnMessageAsync,OnCloseSessionAsync ) to write our logic.

Current Problem : we are planning to migrate to use Microsoft.Azure.ServiceBus. and we didn't find an equivalent class or interface with which we can implement and override (OnMessageAsync,OnCloseSessionAsync ) and write our functionality

Note: We have implemented above mentioned current approach in continuous Web job. where we have callback which creates a factory method on each webjob instance

Is there any solution for this . or any other alternative. Thanks in advance

**Comment by pvreddy37** [comment]
I See that we can use RegisterSessionHandler for OnMessageAsync. 

But I didn't find an equivalent of OnCloseSessionAsync 

OnCloseSessionAsync  we have a use case that we notify the Listeners of the queue . And after notifying them they are suppose to take some action.

**Comment by nemakam** [comment]
@pvreddy37, Thanks for raising the issue. 
Unfortunately, this feature isn't present in the `Microsoft.Azure.ServiceBus` library. 
I'm going to mark this issue as a "FeatureRequest".
There's a new library that is being built right now and we will try to incorporate this into that library.

@jsquire @JoshLove-msft , FYI.

**Comment by nemakam** [comment]
There is no easy way to work around this. One hack you could try is poll on the session object for `MessageSession.IsClosedOrClosing`. If this is true, then call your handler. There is no inbuilt event that is raised when this happens, so you might have to implement a polling method to do the same.

**Comment by JoshLove-msft** [comment]
Hi @pvreddy37, can you elaborate on the action that the queue listener needs to take once the session is closed? Is the intent to track the number of sessions processed or is it a time-sensitive action that needs to happen precisely when we have stopped processing messages from a particular session?

**Comment by pvreddy37** [comment]
Hi @JoshLove-msft  :  It is a time sensitive action that we need to take when we have stopped processing messages from a particular session. . Basically we configure MessageWaitTimeout = 3 minutes in SessionHandlerOptions() and if there is no message for 3 minutes we notify other users to take action.

**Comment by jsquire** [comment]
This appears to have been resolved; the forthcoming `Azure.Messaging.ServiceBus` library now includes the requested event and discussion here seems to have concluded.    I'm going to close this out; @pvreddy37, please feel free to reopen if you believe there is further discussion needed.
