### ISSUE TITLE
Event Processor Load Balancer: Allow for relinquishing a single partition

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#11078]
# Summary

When load balancing claims a partition for a given `EventProcessor<T>` instance, it will continue to hold ownership until the partition is stolen by another instance or the current processor is stopped.  If there is an issue with the partition and the processor is unable to make forward progress, there is no way for the processor to surrender ownership and request that it not claim that partition again immediately.

The load balancer should offer a sibling to its `RelinquishOwnershipAsync` method, allowing surrender of a single partition. a configurable window of time in which it should not be claimed if unowned, and a configurable window of time in which it should not be stolen.   

# Scope of Work

- Add a new method on the `PartitionLoadBalancer` to allow for relinquishing ownership of a single partition and ignoring the ability to claim/steal it as detailed in the summary.

- Implement the feature, integrating the intervals for "do not claim if unowned" and "do not steal if owned" into the decision-making process for the load balancing algorithm.

- Incorporate the new API into the main processing loop of the `EventProcessor<T>` as an alternative to restarting processing for a faulted task.  _(see [PerformLoadBalancingAsync](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor%7BTPartition%7D.cs#L1254))_   

# Example Skeleton

_Note: This skeleton is intended for illustration only; actual implementation needs may require changes._

```csharp
public virtual async Task RelinquishOwnershipAsync(string partitionId,
                                                   TimeSpan doNotClaimIfUnownedInterval = TimeSpan.Minutes(1),
                                                   TimeSpan doNotStealIfOwnedInterval = TimeSpan.FromMinutes(5),
                                                   CancellationToken cancellationToken = CancellationToken.None)     
{
}
```

# Success Criteria

- The API surface needed to support the "surrender partition" feature has been implemented, and the associated types preserve their current API with no breaking changes.

- The main processing loop of the `EventProcessor<T>` no longer automatically restarts faulted partition processing tasks; instead, the associated partition is surrendered.  The processor preserves the current public API with no changes.

- The tests necessary for its validation have been created or adjusted and pass reliably; tests that do not focus on the extension points have been removed and no base functionality is included.

- The existing live test suite continues to produce deterministic results and pass reliably.

**Comment by JimSuplizio** [comment]
Hi @jsquire, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
