### ISSUE TITLE
[BUG] Investigate Missing Source Link & Untracked Sources Issues

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#11090]
- Investigate why Source Link entry in signed nuget package (When viewed with the package explorer) shows up as `Missing Symbols` for dev builds, but show up as `Contains Untracked Sources (obj)` for non-dev (Manual) builds. Also what part of the signing process affect the symbols.

- In this [ServiceBus build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=278328&view=artifacts&type=publishedArtifacts) why did Azure.Messaging.ServiceBus have missing symbols while Microsoft.Azure.ServiceBus symbols are not missing.

- Investigate the issues of untracked sources. How does it relate to [This PR](https://github.com/Azure/azure-sdk-for-net/pull/9755)

**Comment by heaths** [comment]
According to the tool tips over the warning and error icons:
1. **Source Link**: we should either add `<EmbedUntrackedSources>true</EmbedUntrackedSources>` to our project or use the workaround in dotnet/sourcelink#572. Given we use Source Link already, I thought, I'm not sure why we're getting this. Maybe it's just precautionary to make sure packages are built with full sources either way?
2. **Deterministic (dll/exe)**: if we're using the .NET 2.1.300 SDK or newer, we should add `<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>` to our project.
3. **Compiler Flags**: seems to indicate we should use the .NET 3.1 compiler targeting netstandard2.0.

**Comment by chidozieononiwu** [comment]
Closing this since all the info is here https://github.com/Azure/azure-sdk-for-net/issues/12995
Will continue to use https://github.com/Azure/azure-sdk-for-net/issues/12995 to track the issue till its all resolved.
Thanks @heaths
