### ISSUE TITLE
HDInsight: JobDetails have incorrect StatusCode values when getting job using JobClient

### ISSUE THREAD

**Issue by paragneve** [Azure/azure-sdk-for-net#1111]
Hi,

I am using HDInsight .NET SDK for submitting Hive jobs to the cluster and I noticed that the JobDetails object have incorrect values when we get a job using JobClient(jobId).

For instance, I noticed that JobDetails object of a job which was "Failed" will have StatusCode value as "Completed".
See code snippet below:

jobDetails = await jobClient.GetJobAsync(jobId);
Console.Writeline(jobDetails.StatusCode);

This bug was about to go in our production environment and would have resulted in incorrect calculations which are very business critical. Can you please look into this issue.

Thanks,
Parag

**Comment by shahabhijeet** [comment]
@paragneve please open a new issue if the problem still exists/repros.
