### ISSUE TITLE
Make USReceiptType a simple enum

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11119]
Confirm with service team that USReceiptType should not be a Flags enum, and if not, update it.

Described in comment on APIView rev 47:

> [Flags]
>    public enum USReceiptType {

bojunehsu3 hours ago
ReceiptType is not a bit flag.

annelo-msft1 minute ago
I did this because Cha had pointed out a receipt could be both a CreditCard receipt and an Itemized receipt. Is the service not planning to return multiple values?

**Comment by maririos** [comment]
Does this type change need to happen for Preview 1? are other languages making the change too?

**Comment by annelo-msft** [comment]
We just need to remove the [Flags] attribute from the enum.  I'm not sure other languages have this concept.
