### ISSUE TITLE
Add extension methods for each LRO type to OperationExtensions

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11117]
We currently have a single extension method for retrieving the result directly from an LRO, without having to use more complicated LRO patterns:

`public static ValueTask<Response<IReadOnlyList<RecognizedReceipt>>> WaitForCompletionAsync(this Task<RecognizeReceiptsOperation> operation, CancellationToken cancellationToken = default);`

See [this thread](https://github.com/Azure/azure-sdk-for-net-pr/pull/981/files#r399869464) for discussion.

We will add one such extension method for each of the LRO methods in both FormRecognizerClient and FormTrainingClient.

**Comment by maririos** [comment]
See file https://github.com/annelo-msft/azure-sdk-for-net/blob/db94c229fd9da844a674ee2b69633454fbf0ed56/sdk/formrecognizer/Azure.AI.FormRecognizer/src/OperationExtensions.cs in PR https://github.com/Azure/azure-sdk-for-net/pull/11048

**Comment by AlexanderSher** [comment]
Can we extract a base interface, implement it in every operation, and have only one extension method?

**Comment by AlexanderSher** [comment]
Something like:
```cs
public static async ValueTask<Response<T>> WaitForCompletionAsync<T>(this Task<Operation<T>> operation, CancellationToken cancellationToken = default)
{
    Operation<T> o = await operation.ConfigureAwait(false);
    return await o.WaitForCompletionAsync(cancellationToken).ConfigureAwait(false);
}

public static async ValueTask<Response<T>> WaitForCompletionAsync<T>(this Task<Operation<T>> operation, TimeSpan pollingInterval, CancellationToken cancellationToken = default)
{
    Operation<T> o = await operation.ConfigureAwait(false);
    return await o.WaitForCompletionAsync(pollingInterval, cancellationToken).ConfigureAwait(false);
}
```

**Comment by annelo-msft** [comment]
Per discussion with @mayurid, addressed for Preview 1 with https://github.com/Azure/azure-sdk-for-net/pull/11444 and moving to Preview 3 to do final implementation.

**Comment by annelo-msft** [comment]
@AlexanderSher, I was unable to make this work when I tried it recently, because the compiler doesn't use the `where` clause to use type resolution, and so it could not figure out the return type from the LRO -- the `T` in `Response<T>` in your example.  We can reopen this is you can provide a working implementation.

**Comment by AlexanderSher** [comment]
@annelo-msft , what code have you tried to make work? Is it this one: https://github.com/Azure/azure-sdk-for-net/pull/11359 ?
