### ISSUE TITLE
Rename FormField.FieldLabel to FormField.LabelText

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11122]
This will indicate that ValueText and LabelText are the same type.

Described in APIView, rev 47:

>         public FieldText ValueText { get; }

kristapratico21 hours ago

Python has a concern with the property name ValueText. This may communicate to users that the type is a string, not a complex object. Suggestions for rename: ValueData or ValueDetails. If this naming change is made, also suggest renaming FieldLabel to FieldData or FieldDetails

annelo-msft21 hours ago
Since .NET has an implicit cast of FieldText to string, this may be less of an issue for us to keep it called xxText. I'm a little concerned about calling it xxDetails when the text value is in there and for unsupervised is the one place you can get the field label text. I'd suggest diverging across .NET/Python for Preview 1, and then we can review with the arch board to see if there's an opportunity to align here.

You make a good point about consistent naming, though. I'd like to consider changing the .NET property FieldLabel to be consistent with ValueText, so here I'd propose renaming it to LabelText for .NET for preview 1. @bojunehsu , do you have any concerns about this?

annelo-msft20 hours ago
Here is my proposed update for .NET:

```
   public class FormField {
        public float? Confidence { get; }
        public string Name { get; }
        public FieldText LabelText { get; }
        public FieldText ValueText { get; }
        public FieldValue Value { get; }
   }
```

**Comment by annelo-msft** [comment]
@kristapratico @bojunehsu

**Comment by annelo-msft** [comment]
Make the change to FormField<T> as well to keep them consistent.

**Comment by maririos** [comment]
Are all languages doing this for Preview 1?

**Comment by annelo-msft** [comment]
Python and JS will diverge here, .NET and Java will do this.  We'll get customer and arch board feedback after preview 1 releases.
