### ISSUE TITLE
[BUG] BlobBaseClient.DownloadAsync will hang indefinitely when the server stops sending response data

### ISSUE THREAD

**Issue by kylewilt-conf** [Azure/azure-sdk-for-net#11125]
**Describe the bug**
If you intentionally emulate/create a service failure such that the server side stops sending data while a receive operation is pending in the BlobBaseClient.DownloadAsync code path, it will hang indefinitely regardless of timeout and retry configuration.

As part of my research I found there are two areas in the code base that can be changed to fix it. **I have local changes that more or less resolve the issue although there are some downsides.** 

First the Azure.Core.Pipeline.RetriableStream.RetriableStreamImpl class leaks all of its streams, therefore the caller cannot even eagerly dispose the underlying network connection if they wanted to work around this by implementing a timeout outside.

Second the Azure.Core.Pipeline.ReadTimeoutStream class can be modified to reasonably efficiently trigger a real abort based on the cancellation token provided by the caller in its ReadAsync method implementation.

The downside to this approach (which may not be avoidable) is that this does seem to effectively cancel the I/O but it puts the socket into a FIN_WAIT2 state or potentially a FIN_WAIT1 state depending on how "down" the server actually is. In a scenario where the server is completely gone a FIN_WAIT1 is set and this times out fairly quickly causing the network resources to be reclaimed. FIN_WAIT2 waits several minutes by default in windows but it's also in a scenario where the server actually is responding at the TCP/IP stack level just not at the application level. Both are valid failed state scenarios in practice I believe. I'm not sure if there's another option to deal with this cleanup more forcefully or not but that's what I've found at this point. If there is a way it'd have to be provided by the ServicePoint and/or Socket classes in the .NET Framework itself.

I also tried playing with the ServicePointManager.SetTcpKeepAlive but it didn't seem to have any effect. I didn't spend a lot of time on this as it seemed an in appropriate solution that has too broad of an effect even if it did work.

**Expected behavior**
Minimally the built in retry/timeout mechanism (which is 10 minutes by default) should kick in and abort the request. It should also work correctly for client provided cancellation tokens.

**Actual behavior (include Exception or Stack Trace)**
Effectively the System.IO.Stream.ReadAsync method ends up being called which only checks the cancellation token before issuing the receive via BeginRead in the derived implementation. After that point the I/O request is queued on the IOCP and never returns.

**To Reproduce**
1. Create a BlobClient and point it at a dummy blob url that would match your own machine name for the host.
2. Create a small http listener server and hard code a response that is just enough to get past the initial read logic (I used fiddler to get this).
3. Have the client attempt to download the blob.
4. Have the server do nothing after sending the initial data block but do not let it exit (or windows will cleanup the network connection).

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.4.0
 - Hosting platform or OS and .NET runtime version: Windows 10 .NET Framework 4.8
 - IDE and version : Visual Studio 16.4.5

**Comment by jsquire** [comment]
//cc: @pakrym

**Comment by amishra-dev** [comment]
@tg-msft / @kasobol-msft can you guys comment on this. the suggestions seems to be about changes in the core sdk.

**Comment by kasobol-msft** [comment]
@amishra-dev sounds right by looking at the codebase.
Also `RetriableStreamImpl` doesn't seem to be disposing old stream when retry happens.

**Comment by kylewilt-conf** [comment]
@kasobol-msft  Yeah in my local changes that's one of the things I fixed.

**Comment by kylewilt-conf** [comment]
In addition, it's holding onto the initial stream just to support grabbing the length field (as far as I can tell). In my local changes I left that alone with some extra code but I wasn't sure if there was a better way to deal with that since I didn't know enough about the context. To me ideally it'd be either passed as an argument directly assuming the calling context might have that info in a safe way. Otherwise the original connection has to hang around until all the retries stop...

**Comment by tg-msft** [comment]
+@pakrym and @mikeharder who have spent a lot of time on this

**Comment by pakrym** [comment]
> First the Azure.Core.Pipeline.RetriableStream.RetriableStreamImpl class leaks all of its streams, therefore the caller cannot even eagerly dispose the underlying network connection if they wanted to work around this by implementing a timeout outside.

Good point.

> Second the Azure.Core.Pipeline.ReadTimeoutStream class can be modified to reasonably efficiently trigger a real abort based on the cancellation token provided by the caller in its ReadAsync method implementation.

Do you mean by disposing the underlying stream in the cancellation token callback?

If you already have a fix what do you think about opening a PR and we can look through the fix there?

**Comment by kylewilt-conf** [comment]
> > First the Azure.Core.Pipeline.RetriableStream.RetriableStreamImpl class leaks all of its streams, therefore the caller cannot even eagerly dispose the underlying network connection if they wanted to work around this by implementing a timeout outside.
> 
> Good point.
> 
> > Second the Azure.Core.Pipeline.ReadTimeoutStream class can be modified to reasonably efficiently trigger a real abort based on the cancellation token provided by the caller in its ReadAsync method implementation.
> 
> Do you mean by disposing the underlying stream in the cancellation token callback?
> 

Yes, unless there’s a better mechanism available. 

> If you already have a fix what do you think about opening a PR and we can look through the fix there?

I considered doing a pull request but I have a lot of other work to do and meeting all of the prerequisites and using the latest branch are going to take a fair amount of time. The first time I tried to build latest it had breaking changes in it before I made any myself. I ended up going back to the 12.4 release code base in a local branch to make my changes. I am more than happy to send the raw files I modified along.

Also I had outstanding questions around the retriable stream implementation, in particular whether or not the length property could be passed in when needed to avoid keeping the original stream alive longer than necessary in a retry scenario. It seems to me that certain failures may prevent the length property from working after a retry anyway if the original stream ended up in a truly faulted state.
