### ISSUE TITLE
[FEATURE REQ] Allow BlockList (and other Blob Models) to be set non-internally

### ISSUE THREAD

**Issue by wesyao** [Azure/azure-sdk-for-net#11130]
Hello Folks! I've spent quite a bit of time trying to write valuable unit tests and mocking out Azure.Blob calls and I'm having a difficult time working around the SDK and testing values. Here is a scenario that best illustrates what I am trying to do and I think this would apply across many of the Blob Models.

#### Source
```
var response = await blockBlobClient.GetBlockListAsync(BlockListTypes.Uncommitted);
var uncomittedBlocks = response.Value.UncommittedBlocks;
var blockList = uncomittedBlocks.Select((block) => block.Name).ToList();
await blockBlobClient.CommitBlockListAsync(blockList);
return blockBlobClient.Uri.AbsoluteUri;
```

#### Test (using xunit)
```
var MockBlockList = new Mock<BlockList>();
// I want to create a MockBlockList with test values or set Uncommitted Blocks here
sm.BlockBlobClient.Setup(m => m.GetBlockListAsync(It.IsAny<BlockListTypes>(),default, default, default))
    .ReturnsAsync(Azure.Response.FromValue<BlockList>(MockBlockList.Object, null));
await sm.storeDataSection(mockDataSection);

sm.BlockBlobClient.Verify(x => x.StageBlockAsync(mockBlockId, It.IsAny<MemoryStream>(), default, default, default, default));
sm.BlockBlobClient.Verify(x => x.GetBlockListAsync(BlockListTypes.Uncommitted, default, default, default));
sm.BlockBlobClient.Verify(x => x.CommitBlockListAsync(It.IsAny<IEnumerable<string>>(), default, default, default, default, default));
```
In the `source`, I am trying to commit a set of blocks that are already staged, but uncommitted.
In the `test`, I am trying to spy on `GetBlockListAsync` to return a mocked `BlockList`, then use this list to verify my `CommitBlockListAsync` call.

However, based on the [BlockList Model](https://github.com/Azure/azure-sdk-for-net/blob/640488d315d106404bd33dfff38130a5b92ba01d/sdk/storage/Azure.Storage.Blobs/src/Models/BlockList.cs), all the setters are internal. This makes mocking out these calls extremely difficult.

Also, given the stateful nature of the clients, we cannot take advantage of Dependency Injection to mock out these clients. So we now have to create Fakes that extend BlockClient, but without the ability to Mock out the Models, these fakes are limited as well.

```
// stateful & harder to test
new BlobContainerClient(connStr, containerName).CreateIfNotExistsAsync()

// stateless
new BlobContainerClient(connStr).CreateIfNotExsistsAsync(containerName)
```
**Library or service name.**
What library or service is this request related to? Azure.Storage.Blobs

**Comment by seanmcc-msft** [comment]
Hi @wesyao, 

You can create Blob models for mocking with the Azure.Storage.Models.BlobModelFactory static methods.  In this case, BlobModelFactory.BlobList().

To mock a BlobContainerClient, I'd recommend a mocking framework like [MOQ](https://github.com/Moq/moq4/wiki/Quickstart).  You don't have to use the actual constructors to create client:

```Mock<BlobContainerClient> client = new Mock<BlobContainer>();```
