### ISSUE TITLE
Add proxy configuration documentation

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#11132]
> Customers are asking for guidance on using Azure Tools with proxies, specifically (1) How to configure Azure Tools to use an authenticating proxy using NTLM or Kerberos authentication; (2) How to add custom trusted CA certificates to allow communication through an SSL-intercepting proxy.  We should expect that other financial institutions will have similar questiosn about our tools.  Do we have any specific guidance and documentation on how to configure Azure tools based on Azure.Core to work through such proxies, on each of the major platforms?

**Comment by jsquire** [comment]
Moving to the backlog milestone, as the assigned milestone has passed.  Please feel free to update should this work be scheduled.

**Comment by grayjeremy** [comment]
I'm having this problem with DefaultAzureCredential getting blocked by a network device...I've found a bunch of calls, but a list of white-listable items (for each type of authentication) would be nice and speed up lots of projects.  

some of the urls I've found
api.vstsusers.visualstudio.com, app.vssps.visualstudio.com,az700632.vo.msecnd.net,signlr-prod.core.vsengsaas.visualstudio.com

**Comment by stewartadam** [comment]
> (2) How to add custom trusted CA certificates to allow communication through an SSL-intercepting proxy.

+1 to this. I can't use mitmproxy with the C# SDK (for Azure Digital Twins) to debug requests because it claims "UntrustedRoot" on MacOS, despite the mitmproxy self-signed root certificate being trusted in my keychain.

**Comment by annelo-msft** [comment]
Proxy samples are available here:
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy
- https://learn.microsoft.com/en-us/dotnet/azure/sdk/azure-sdk-configure-proxy?tabs=cmd

If further samples are needed, we can reopen the issue.
