### ISSUE TITLE
V12 SDK deprecation impact

### ISSUE THREAD

**Issue by Petermarcu** [Azure/azure-sdk-for-net#11158]
@rohitgkr commented on [Sat Mar 07 2020](https://github.com/Azure/azure-storage-net/issues/972)

### Which service(blob, file, queue, table) does this issue concern?
Blob/BlockBlobClient/BlobContainerClient

### Which version of the SDK was used?
Azure.Storage.Blobs V12.3.0
With APIs such as BlobRequestOptions & CloudBlockBlob being deprecated in V12 SDK I couldn't find any documentation indicating their replacement in the current storage SDK. 
1. What is the default retry policy in V12 SDK?
2. Is there a way to specify parallelism in threads for upload as BlobRequestOptions is not available in BlobContainerClient or in BlockBlobClient?
3. Is the expectation for the caller to call  BlockBlobClient.StageBlockAsync from thread pool threads or TPL thread delegates? This is unlike the previous SDK implementation where the SDK used threads specified inside BlobRequestOptions to automatically manage block blob upload parallelism. 
Thanks.

---

@rohitgkr commented on [Sun Mar 08 2020](https://github.com/Azure/azure-storage-net/issues/972#issuecomment-596179017)

i've looked into the SDK source & inferred the following. Please comment with any additions or corrections.
- BlockBlobClient could be used directly but threads & parallelism must be managed by the end user.
- BlobClient orchestrates threads via StorageTransferOptions passed in during Upload*
- Staged uploads for over 265MB content and single upload upto 256MB
- By default (across various classes & parameters) the end state is =>
Retry policy : Exponential backoff upto 5 attempts, 1min max delay (overridden via BlobClientOptions)
Concurrency : 5,
Upload chunk size : 256MB
Download chunk size : 256 MB
Block blob size : 4MB or 8MB if not specified, if specified => max 100MB
Max blocks : 50K
HttpClient timeout : 100secs  (change  via BlobClientOptions.Transport)
HttpClientHandler.MaxRequestContentBufferSize : 0. This is irrelevant as .NET Core now uses SocketsHttpHandler & SDK StorageTransferOptions can be used for single & block size spec.

**Comment by amishra-dev** [comment]
@seanmcc-msft this issue got moved from the earlier repo, can you respond here as well as the old repo.

**Comment by amishra-dev** [comment]
@rishabpoh your PR for migration guide addresses most of these, can you please incorporate the questions being ask here?

**Comment by amishra-dev** [comment]
We are working on a doc with migration steps. Here is the PR for it. https://github.com/Azure/azure-sdk-for-net/pull/13159 
@rishabpoh please make sure this PR gets merged soon.

**Comment by CoenraadS** [comment]
In the v11 library, it was often recommended to do something like:

  BlobRequestOptions options = new BlobRequestOptions
            {
                DisableContentMD5Validation = true,
                StoreBlobContentMD5 = false
            };

To improve performance when uploading many small files, is such a trick available in v12?

**Comment by rishabpoh** [comment]
Here is the migration guide for the Azure Storage .NET Blob v12 library: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md

**Comment by CoenraadS** [comment]
Thanks for the link, but the migration guide does not mention BlobRequestOptions

**Comment by amishra-dev** [comment]
@CoenraadS is there a specific Request option you are looking for a mapping for?

**Comment by CoenraadS** [comment]
> 
> 
> In the v11 library, it was often recommended to do something like:
> 
> BlobRequestOptions options = new BlobRequestOptions
> {
> DisableContentMD5Validation = true,
> StoreBlobContentMD5 = false
> };
> 
> To improve performance when uploading many small files, is such a trick available in v12?

However I have since changed jobs, so this question can be closed since I'm no longer interested. Maybe other people will have similar question though.

**Comment by amishra-dev** [comment]
Sounds fair @CoenraadS 
@jaschrep-msft James can you please add this to the migration guide and then close this bug

**Comment by raiajithkumarr** [comment]
Hi  @amishra-dev & @jaschrep-msft ,
Could you please provide updated migration guide with the sample for below question in v12 which is already mentioned in Earlier post.

 BlobRequestOptions options = new BlobRequestOptions
            {
                DisableContentMD5Validation = true,
                StoreBlobContentMD5 = false
            };

**Comment by jaschrep-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/17759

**Comment by prachita-mane** [comment]
How do you create a blob on a specific access tier in the CreateAsync method of PageBlobClient like in v11?

```
[Microsoft.Azure.Storage.DoesServiceRequest]
public virtual System.Threading.Tasks.Task CreateAsync (long size, **Microsoft.Azure.Storage.Blob.PremiumPageBlobTier? premiumPageBlobTier,** Microsoft.Azure.Storage.AccessCondition accessCondition, Microsoft.Azure.Storage.Blob.BlobRequestOptions options, Microsoft.Azure.Storage.OperationContext operationContext, System.Threading.CancellationToken cancellationToken);
```

**Comment by jaschrep-msft** [comment]
@prachita-mane This is not currently exposed in V12. I encourage you to file a feature request.
