### ISSUE TITLE
TopicDescription/QueueDescription.AvailabilityStatus in not in Microsoft.Azure.ServiceBus for netstandard

### ISSUE THREAD

**Issue by redtaped** [Azure/azure-sdk-for-net#11169]
**Query/Question**
I'm migrating to the new Microsoft.Azure.ServiceBus namespaces for netstandard support, but cannot find an equivalent to the Microsoft.ServiceBus.Messaging version of TopicDescription.AvailabilityStatus or QueueDescription.AvailabilityStatus.

The notes say this "Gets the status of the availability of this instance.". 

We were previously using this after creating a topic or queue to ensure that it is finished and ready.

`queueDescription.AvailabilityStatus == EntityAvailabilityStatus.Available &&
 queueDescription.Status == EntityStatus.Active`

Is there a more appropriate way to accomplish this when running CreateQueueAsync or CreateTopicAsync using a ManagementClient?

**Environment:**
- Microsoft.Azure.ServiceBus.Management
- Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

**Comment by nemakam** [comment]
> We were previously using this after creating a topic or queue to ensure that it is finished and ready.

What do you mean by this? When the `CreateTopic` / `CreateQueue` call returns, that essentially means the entity is already ready. Do you find your `if` condition ever returning false?
This was never implemented in this library because there weren't enough usage of this feature. 
I've marked this as a feature-request. In case you have a valid use-case, you could also feel free to raise a PR here to unblock yourself.

**Comment by redtaped** [comment]
We were having issues in the past where it would still be creating after the CreateTopic / CreateQueue call finished. This didn't happen consistently, but would occur when we had many consumers. @nemakam, perhaps this was a known bug with the old SDK or REST APIs that has since been resolved? If so, that was the only use case and a feature would not be required.

**Comment by axisc** [comment]
@redtaped the management calls happen over REST and are synchronous, so it should not happen that the call returned but the entity was not available.

If you see this issue persist, please open a support ticket so that we can investigate internally.
