### ISSUE TITLE
Readme content of Azure Key Vault Secrets is unclear and inconsistencey

### ISSUE THREAD

**Issue by wantedfast** [Azure/azure-sdk-for-net#11193]
1
Section [Link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/samples/Sample2_BackupAndRestore.md#backing-up-a-secret)
![image](https://user-images.githubusercontent.com/25993729/78874248-ad4a0a00-7a7e-11ea-877d-c06afec398dd.png)

Comments: Correct it as **secret**

2
Section [Link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/samples/Sample3_GetSecrets.md#creating-a-secretclient)
![image](https://user-images.githubusercontent.com/25993729/78874517-1762af00-7a7f-11ea-9340-b905a0370565.png)

Comments: This link goes to Azure Identity Readme, But I think it should go to [DefaultAzureCredential ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/README.md#defaultazurecredential)section directly.

3
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Secrets#install-the-package)
![image](https://user-images.githubusercontent.com/25993729/78874811-8b04bc00-7a7f-11ea-9753-f222a81e0b0c.png)

Comments: Correct it as **Install the Azure Key Vault Secrets client library for .NET with NuGet:**

4
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys#authenticate-the-client)
![image](https://user-images.githubusercontent.com/25993729/78882841-42530000-7a8b-11ea-89f0-e788ab050689.png)

Comments: Consider to remove 'provider' word. TokenCredential isn't inherit from a Provider Interface. Remove provider might more accurate

5
Section [Link](url)
![image](https://user-images.githubusercontent.com/25993729/78876186-880acb00-7a81-11ea-9313-24845f53e082.png)

![image](https://user-images.githubusercontent.com/25993729/78876198-8e00ac00-7a81-11ea-999b-962edb078e97.png)

Comments: Inconsistency between "Azure Key Vault" and "Key Vault". Consider using "Azure Key Vault" in all .md files?

**Comment by jongio** [comment]
I agree with suggestions.  Please do a PR.  Thank you.  @tzhanl

**Comment by wantedfast** [comment]
Created a new PR #11267 to address this issue.
