### ISSUE TITLE
[FEATURE REQ] A way to manage retry frequency at service bus side.

### ISSUE THREAD

**Issue by Sandeep321** [Azure/azure-sdk-for-net#11192]
**Library or service name.**
Microsoft.Azure.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
Problem: As of today, when a subscription client is connected to the Azure Service bus instance, the time interval between the message retries is not uniform and its random. Also, it doesn't look like we can control that from service bus instance settings. So, how do I make sure that when a message processing fails, the next retry is delayed by a certain time frame instead of a random one?

We would like to have such a mechanism built-in from service bus side. Also, in case it is possible from the client-side, is there a reference/link which you can point to?

There is a similar issue opened, but I just wanted this to be more specific.
https://github.com/Azure/azure-sdk-for-net/issues/9473

**Comment by nemakam** [comment]
@Sandeep321 , Since this is the same ask as the #9473, we can track this feature request in the other issue. 
For now, you could also consider completing the message and sending a scheduled message within a transaction.
