### ISSUE TITLE
Smoke tests skip tests based on command line parameters

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#11212]
In some cases it might be useful to skip certain tests but still run all other smoke tests. Rather than modifying code, specifying a list of tests to exclude would help achieve this.

We also need to find a way to condition the ARM template as well. No need to allocate resources for skipped tests.

**Comment by jsquire** [comment]
This is no longer relevant with the overhaul of the smoke tests approach.
