### ISSUE TITLE
Readme content of Azure Key Vault Certificates is unclear and inconsistencey

### ISSUE THREAD

**Issue by wantedfast** [Azure/azure-sdk-for-net#11226]
### 1
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Certificates#azure-key-vault-certificate-client-library-for-net)
![image](https://user-images.githubusercontent.com/25993729/78977383-a12b7e80-7b4a-11ea-8cbe-e90eb646a460.png)
![image](https://user-images.githubusercontent.com/25993729/78977584-ed76be80-7b4a-11ea-8188-60a4782bb806.png)

Comments: first `certificate ` -> **certificates**, second `certificates ` -> **certificate**, thrid `Certificate ` -> **certificate**

### 2
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Certificates#createget-credentials)
![image](https://user-images.githubusercontent.com/25993729/78977735-36c70e00-7b4b-11ea-9667-9ca07ea26f52.png)

Comments: Correct it as **certificate**

### 3
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Certificates#create-a-certificate)
![image](https://user-images.githubusercontent.com/25993729/78977848-6bd36080-7b4b-11ea-9fd8-521d8f5b9016.png)

Comments: Correct it as **certificate**

### 4
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Certificates#retrieve-a-certificate)
![image](https://user-images.githubusercontent.com/25993729/78977971-97eee180-7b4b-11ea-9e93-51ce3fb64902.png)

Comments: Content description method and code method do not match. Correct it as `GetCertificate`, `GetCertificateVersion`

**Comment by jongio** [comment]
1. 
Comments: first certificate -> certificates, second certificates -> certificates, thrid Certificate -> certificate

"second" is okay as certificate

Please PR.

**Comment by wantedfast** [comment]
Created a new PR #11268 to address this issue.
