### ISSUE TITLE
Readme content of Azure Key Vault Keys is unclear and inconsistencey

### ISSUE THREAD

**Issue by wantedfast** [Azure/azure-sdk-for-net#11225]
### 1
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys#examples)
![image](https://user-images.githubusercontent.com/25993729/78974656-0ed4ac00-7b45-11ea-81c7-ae82dbdf4253.png)

Comments: Inconsistency between keys readme and another two services([Secrets Sample Link](https://github.com/Azure/azure-sdk-for-net/tree/Azure.Security.KeyVault.Secrets_4.0.3/sdk/keyvault/Azure.Security.KeyVault.Secrets#examples) and [Certificates Sample Link](https://github.com/Azure/azure-sdk-for-net/tree/Azure.Security.KeyVault.Secrets_4.0.3/sdk/keyvault/Azure.Security.KeyVault.Certificates#examples)) readme. Suggest change all as `the client created above`.

### 2
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys#list-keys)
![image](https://user-images.githubusercontent.com/25993729/78975288-60316b00-7b46-11ea-8250-74e5d2b51b4b.png)

Comments: This part of content is not correct. Also to keep consistency, use the secrets readme [template](https://github.com/Azure/azure-sdk-for-net/tree/Azure.Security.KeyVault.Secrets_4.0.3/sdk/keyvault/Azure.Security.KeyVault.Secrets#list-secrets)
Correct it as below:
_This example lists all the keys in the specified Azure Key Vault. The value is not returned when listing all keys. You will need to call KeyClient.GetKey to retrieve the value._

### 3
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Keys#delete-a-key-asynchronously)
![image](https://user-images.githubusercontent.com/25993729/78975644-17c67d00-7b47-11ea-94e0-04611e13cf50.png)

Commets: Code inaccurate, should use async method regarding the sample content description. Correct code like below:
```
DeleteKeyOperation operation = await client.StartDeleteKeyAsync("key-name");
await client.PurgeDeletedKeyAsync("key-name");
```
### 4
Section [Link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/samples/Sample4_EncryptDecrypt.md#decrypting-a-key)
![image](https://user-images.githubusercontent.com/25993729/78976017-f023e480-7b47-11ea-9d02-270bbdcd0842.png)

Comments: Missing '.' at end of the word

### 5
Section [Link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/samples/Sample6_WrapUnwrap.md#creating-a-key)
![image](https://user-images.githubusercontent.com/25993729/78976990-ed29f380-7b49-11ea-86ad-84084c931816.png)

Comments: Missing '.' at end of the word

**Comment by jongio** [comment]
Please PR.  Thank you.

**Comment by wantedfast** [comment]
Create a New PR #11265  to track this issue,
