### ISSUE TITLE
Blueprint module does not accept ResourceGroup.Name values with long computed expressions

### ISSUE THREAD

**Issue by wasabii** [Azure/azure-sdk-for-net#11257]
**Describe the bug**
Receiving a validation error through the `Az.BluePrint` powershell module regarding the importing of a Blueprint with a computed `ResourceGroup.name` value. The error indicates only 90 characters are supported in the resource group name. However, this is not actually true as the value allows `[]` expansion values exceeding 90 characters.

**Expected behavior**
The computable value should be accepted.

**Actual behavior (include Exception or Stack Trace)**
`Import-AzBlueprintWithArtifact : 'Name' exceeds maximum length of '90'.`

**To Reproduce**

```json
    "resourceGroups": {
            "ApplicationResourceGroup": {
                "location": "[parameters('l')]",
                "name": "[concat(parameters('u'),'-',parameters('e'),'-',parameters('d'),'-',parameters('a'),'-rg')]"
            }
        }
```

Attempt to import the Blueprint, and receive the error.

**Comment by wasabii** [comment]
#https://github.com/Azure/azure-powershell/issues/11552

**Comment by wasabii** [comment]
Azure/azure-sdk-for-net#11257

**Comment by wasabii** [comment]
The error is in `blueprint/Microsoft.Azure.Management.Blueprint/src/Generated/Models/ResourceGroupDefinition.cs:Validate`. I would love to fix it, but since the file is generated, I'm not sure of the best way to approach it. I do not know how it was generated, or what the proper procedure to override it is.

**Comment by alex-frankel** [comment]
closing this issue as it is not related to the SDK

**Comment by ScottMetzel** [comment]
I'm running into the same issue while running Az.Blueprint module version 0.2.13. I didn't try every older version of the module/cmdlet, but I did install these older versions and ran into the same problem with each attempt:

- 0.2.10
- 0.2.6
- 0.2.0

The cmdlet doesn't exist in versions 0.1.1 nor 0.1.0, so, no point in trying them ☹️

**Comment by alex-frankel** [comment]
This is an issue with our APIs, not with the SDK. With the planned changes to move blueprint definitions to [template specs](https://youtu.be/UaVCNpD3pvg?t=718), this is not likely something we are going to fix. We just announced templateSpecs at build, so details are a bit scarce, but we should have more info to share in 1-2 months.

**Comment by ScottMetzel** [comment]
Thanks for the information @alex-frankel; I caught that announcement and look forward to template specs!

As a workaround, I simply shortened some parameter names to get the string value of the function at or below 90 characters in length.. works fine otherwise.
