### ISSUE TITLE
[FEATURE REQ] Image upload and download to azure blob storage by .NET Core Web API

### ISSUE THREAD

**Issue by ParthiKarnan** [Azure/azure-sdk-for-net#11254]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
Azure.Storage.Blobs 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? 
I want to upload / download image to blob storage from .NET Core Web API.

**What problem is it solving?**
I have micro-services projects where I need to upload avatar URL for each users one of the services. 
It got resolved the proper way implementation and everyone aware the right way to upload / download images into azure blob.

**What I did and facing?**
Here is my case, I want to upload and download images from API with three different dimensional into azure blob storage. I have implemented the same by using Block Blobs type via .NET Core 2.2 Web API. Inside the API I have written three logic that are, 

1. Uploading original size of the image which is below 8 MB. 
2. Converting the original images sizes into three different sizes according to my business use cases. 
3. After storing the images into blob I'll save the avatar URL into azure SQL database for the retrial purpose.

According to the implementation, the written API gives response as averagely 1.32 ms when the users concurrently access the API.

The API deployed azure web app's instances are crashed frequently, I suspect the image upload API may cause this issue or Am I follow the right way to upload images by using API.

I need an experts inputs and if any best practices that following for image upload and download with azure blob storage.

Kind regards,
Parthiban.

**Comment by amishra-dev** [comment]
Hi @ParthiKarnan,
Can you please share the logs from the crash?

**Comment by amishra-dev** [comment]
Please reactivate when you have the logs. Thanks

**Comment by ParthiKarnan** [comment]
@amishra-dev - I resolved the issue. Thanks for the support. 
Here is the [https://github.com/ParthiKarnan/azure-cloud-image-processing](url) repository that I have found the solution. Sorry for the delayed response.
