### ISSUE TITLE
Can't create web space with the WebSites management library

### ISSUE THREAD

**Issue by djfr** [Azure/azure-sdk-for-net#1126]
Currently there is no way to create a web space.
Trying to create a web hosting plan on a geo region that there is no web space for returns an exception.

This forces web site creation to have a manual step, to create a dummy web site in the target geo region through the portal, so that the web space is created by the normal and then the automation steps against that geo region can be run.

**Comment by shahabhijeet** [comment]
@djfr please open a new issue if the problem still exists/repros.
