### ISSUE TITLE
Consider Key Vault tests with and without soft delete enabled

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#11283]
Related to bug #11258 and its fix in PR #11282, we should consider creating soft delete-enabled and -disabled vaults against which tests are run. Some tests would need to be updated (e.g. don't assert `RecoveryId` is null) or excluded when soft delete is disabled entirely, like tests that exercise recovery. This includes cleanup logic that assumes soft delete is enabled in order to purge resources. We could take whether to test soft delete-enabled or -disabled as a fixture parameter, similar to service versions or async.

**Comment by pallavit** [comment]
@heaths is this still valid?

**Comment by heaths** [comment]
No, since it's no longer possible to create new vaults without soft delete.
