### ISSUE TITLE
[BUG] Azure EventHub client no longer throws when a too large message is added to a batch (3.0.0 to 4.2.0)

### ISSUE THREAD

**Issue by erick-thompson** [Azure/azure-sdk-for-net#11289]
**Describe the bug**
In the .NET SDK version 3.0.0 of Microsoft.Azure.EventHubs if a single event that was too large was added to an EventDataBatch the MessageSizeExceededException was immediately thrown. In 4.2.0, the event is not thrown until the batch is sent.

The problem here is that I want to abort the process before I send anything to the event hub. The number of messages can be fairly large, and we want to send the entire set as an atomic unit. So any errors that can be detected before hitting the Event Hub API should be found. If there is an alternate way of checking for EventData size problems that would also be ok. 

**Expected behavior**
The EventDataBatch should throw _or_ there should be a method to check if a given EventData is too large.

**Actual behavior (include Exception or Stack Trace)**
The actual behavior is that the MessageSizeExceededException is thrown when the batch is sent to the service.

**To Reproduce**
In a project with 3.0.0, create a huge EventData and add it to a EventDataBatch. In 4.2.0, do the same.

**Environment:**
.NET Core 3.1 ASP.NET service.

**Comment by serkantkaraca** [comment]
Thanks for reporting this. I am planning to provide a better API experience in the next release.

**Comment by erick-thompson** [comment]
Thanks @serkantkaraca! Is there some way to replicate the old behavior? I'm trying to ensure that all n messages are small enough to fit into an EventData? I don't see any verification methods anywhere.

**Comment by serkantkaraca** [comment]
Unfortunately the first message in the batch is never checked for oversize. I don't see any other way of detecting this before actual SendAsync call fails.

**Comment by erick-thompson** [comment]
Thanks for letting me know. Will this thread be updated when the issue is fixed?

**Comment by serkantkaraca** [comment]
We track all open issues. This one has no exception. I will keep the thread active until fix is checked in.

**Comment by serkantkaraca** [comment]
Fix merged.

**Comment by serkantkaraca** [comment]
Fix merged.
