### ISSUE TITLE
[Event Hubs Client] README link to identity setup script is incorrect

### ISSUE THREAD

**Issue by wantedfast** [Azure/azure-sdk-for-net#11300]
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs#getting-started)
![image](https://user-images.githubusercontent.com/25993729/79203579-d1865c00-7e6d-11ea-8afe-fbf6495da7a7.png)

Comments: Correct it as this [link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/assets/identity-samples-azure-setup.ps1).

**Comment by jsquire** [comment]
Thanks, @wantedfast!   Looks like this link didn't get updated after some asset refactoring.   I'll get that patched up.

**Comment by serkantkaraca** [comment]
PR https://github.com/Azure/azure-sdk-for-net/pull/11303

**Comment by wantedfast** [comment]
Thanks! Close this issue since PR merged.

**Comment by jsquire** [comment]
Reopening;  the PR that Serkant put out was for another issue and unintentionally commented here.   I haven't put out a fix for this yet.
