### ISSUE TITLE
[BUG] AnalyzeImageInStreamAsync closes input stream

### ISSUE THREAD

**Issue by olavt** [Azure/azure-sdk-for-net#11301]
I would like to do the following:

            using (System.IO.MemoryStream imageStream = new System.IO.MemoryStream())
            {
                imagesToAnalyzeImageRepository.DownloadFileToStream(imagePath, imageStream);

                // Creating a list that defines the features to be extracted from the image.
                    List<VisualFeatureTypes> features = new List<VisualFeatureTypes>()
                {
                    VisualFeatureTypes.Adult,
                    VisualFeatureTypes.Brands,
                    VisualFeatureTypes.Color,
                    VisualFeatureTypes.Categories,
                    VisualFeatureTypes.Description,
                    VisualFeatureTypes.Faces,
                    VisualFeatureTypes.ImageType,
                    VisualFeatureTypes.Objects,
                    VisualFeatureTypes.Tags,
                };
                ImageAnalysis analysisResults= await computerVisionClient.AnalyzeImageInStreamAsync(imageStream, features);
                <Want to call other APIs to analyze the image here>
            }

The problem is the the call to AnalyzeImageInStreamAsync closes the stream, so I would get an exception if I try to call for instance the Face APIs on the stream.

Why does the AnalyzeImageInStreamAsync close the stream? I think that is a huge side-effect for a call, which would only need to read from the stream. I think it should be left to the caller to close the stream.

**Comment by SaurabhSharma-MSFT** [comment]
@olavt Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .
