### ISSUE TITLE
[BUG] Microsoft.Azure.EventHubs.Processor 4.2.0 uses WindowsAzure.Storage 

### ISSUE THREAD

**Issue by SanderSade** [Azure/azure-sdk-for-net#11302]
Microsoft.Azure.EventHubs.Processor 4.2.0 depends on WindowsAzure.Storage, while 4.0.0 & 4.1.0 use Microsoft.Azure.Storage.Blob. 

If switching to the older library was intentional it should be described as a breaking change. I have a feeling, though, that the switch was accidental and a quickfix should be released.

**Comment by jsquire** [comment]
@serkantkaraca is the authoritative answer here, but I believe this was an intentional change detailed in #10265

**Comment by serkantkaraca** [comment]
Change was intentional due to issues with WindowsAzure.Storage. I will update the release doc. Thx.

**Comment by SanderSade** [comment]
> Change was intentional due to issues with WindowsAzure.Storage

Issues with Microsoft.Azure.Storage.Blob or WindowsAzure.Storage - and what were they?

**Comment by serkantkaraca** [comment]
> > Change was intentional due to issues with WindowsAzure.Storage
> 
> Issues with Microsoft.Azure.Storage.Blob or WindowsAzure.Storage?

Sorry for confusion. Just corrected my post.

**Comment by serkantkaraca** [comment]
Release doc updated with breaking change notice - https://github.com/Azure/azure-sdk-for-net/pull/11303

**Comment by SanderSade** [comment]
Thank you! Closing this issue
