### ISSUE TITLE
[FormRecognizer] Stop defaulting to PDF when content type detection is in place

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#11313]
## Summary

Current implementations of `StartRecognizeContent` and `StartRecognizeContentAsync` in `FormRecognizerClient` assume content type to be PDF.

https://github.com/Azure/azure-sdk-for-net/blob/0a70b67b9cbe9166080a2217f84d6c09af18818a/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient.cs#L61

https://github.com/Azure/azure-sdk-for-net/blob/0a70b67b9cbe9166080a2217f84d6c09af18818a/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient.cs#L83

Once #10329 is solved, we must make use of the content type detection and stop assuming PDF.

## Goals

- Stop passing `ContentType.Pdf` to the called methods and start passing the auto-detected content type.
- Make sure unit tests still pass consistently.

**Comment by annelo-msft** [comment]
Also for RecognizeCustomForm methods that take a stream.
