### ISSUE TITLE
[FEATURE REQ] Azure.Storage.Blobs - Expose DevelopmentStorageAccount equivalent

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-sdk-for-net#11329]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

Previous versions of the SDK exposed out a convenience reference which was useful for local development and integration tests via the following command `CloudStorageAccount.DevelopmentStorageAccount`

It would be great if the v12 SDK exposed out something similar instead of peopling having to move back to magic strings. This appears to still be referenced inside [`StorageConnectionString`](https://github.com/Azure/azure-sdk-for-net/blob/3065b59a09795d9bf14064c921e80784d34bd63e/sdk/storage/Azure.Storage.Common/src/Shared/StorageConnectionString.cs#L138) however, this class is currently marked as `internal`

**Comment by amishra-dev** [comment]
Hi @wahyuen 
Thanks for the report, we would like to gather further feedback before enabling this back. Meanwhile have you considered [Azurite](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite)?

**Comment by wahyuen** [comment]
Not at this stage, we are still assessing the viability to upgrade to v12 of the Storage SDK and how this affects our currently development environment and release pipelines.

**Comment by amishra-dev** [comment]
Ok, let me check with the team and get back to you tomorrow.

**Comment by SeanFeldman** [comment]
Whenever SDK was redesigned, this should be included. Development account is widely used for local automated verifications and having it as a constant exposed by the SDK was there for a very long time. Please add it and don't force customers to redefine what the SDK should be exposing.

**Comment by JimSuplizio** [comment]
Hi @wahyuen, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
