### ISSUE TITLE
[Azure Core] Readme content and sample code of Azure Core is incorrect

### ISSUE THREAD

**Issue by wantedfast** [Azure/azure-sdk-for-net#11331]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core#consuming-service-methods-returning-asyncpageablet)
![image](https://user-images.githubusercontent.com/25993729/79320369-5049ca80-7f3c-11ea-8d28-bba5e179d5ac.png)

Comments: Variable name not suitable, change it to `allSecrets` might be good for here.

2.
Section [Link ](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core#consuming-long-running-operations-using-operationt)
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core#consuming-long-running-operations-using-operationt

Comments: Should use async method here.
```
await client.StartDeleteSecretAsync("SecretName");
```

3.
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core#troubleshooting)
![image](https://user-images.githubusercontent.com/25993729/79320748-dd8d1f00-7f3c-11ea-9122-12203fdc5ff1.png)

Comments: Link not found, correct it to [this](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#distributed-tracing).

4.
Section [Link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/LongRunningOperations.md#manually-updating-the-status)
![image](https://user-images.githubusercontent.com/25993729/79320967-36f54e00-7f3d-11ea-9f83-94c3d244bee7.png)

Comments: Should use async method here.
```
await client.StartDeleteSecretAsync("SecretName");
```

5,
Section [Link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Pipeline.md#adding-custom-policy-to-the-pipeline)
![image](https://user-images.githubusercontent.com/25993729/79321031-4e343b80-7f3d-11ea-8f75-9ad1af3a2399.png)

Comments: Link not found, correct it to [this](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md#configuring-retry-options) ?

**Comment by jongio** [comment]
1. allSecretProperties

Please PR.
