### ISSUE TITLE
[QUERY] What is the best way to upload a blob when you don't want to have to buffer the data ahead of time?

### ISSUE THREAD

**Issue by kylewilt-conf** [Azure/azure-sdk-for-net#11336]
**Query/Question**
How would I go about uploading a blob without inversion of control (having to pass a live stream into the existing Upload methods). Not all scenarios/apis/designs allow for this to work smoothly. Often times you want to write to the stream directly and retain control of the flow. I would expect the underlying implementation to buffer as appropriate and send over the network as it goes along. This feature existed in prior incarnations of the library but I can't seem to find an equivalent in the 12.4 library.

It's straightforward to implement the inversion of control version on top of the non inverting one but the opposite is not true, at least I haven't thought of a reasonable solution yet.

I can imagine a tricky way to write a custom stream that would block reads on pending writes using multiple threads or possibly doing callback based approaches. Neither of which is appetizing for my scenario and still affects either the shape of my apis or the performance of them. It's certainly not idiomatic to try to have it work that way minimally. 

**Environment:**
 - Azure.Storage.Blobs 12.4

**Comment by kylewilt-conf** [comment]
I have thought of an approach to implement a custom stream using a channel (albeit with some extra overhead) that would more or less work properly assuming the upload operation uses the tpl properly.

**Comment by amishra-dev** [comment]
@kasobol-msft this is a broader architectural question, can you please respond.

**Comment by seanmcc-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-net/issues/9607

**Comment by kylewilt-conf** [comment]
Ah great thanks, I didn't find that one in my initial search for this issue. Any ETA on the OpenWrite functionality? We'll have to work around with an arguably inefficient custom stream in the meantime...

**Comment by seanmcc-msft** [comment]
ETA is to be determined, our team is currently working on adding new features for the next Storage service version.

I'm going to close this issue, but please feel free to follow the discussion on https://github.com/Azure/azure-sdk-for-net/issues/9607.

**Comment by kasobol-msft** [comment]
@kylewilt-conf One option to consider or workaround is Pipes. I got a working example.:
```            
            BlobClient blob = // blob client;
            byte[] data = //some data;

            // create pipe
            AnonymousPipeServerStream pipeServer = new AnonymousPipeServerStream(PipeDirection.Out);
            AnonymousPipeClientStream pipeClient =
              new AnonymousPipeClientStream(PipeDirection.In, pipeServer.GetClientHandleAsString());

            // write to pipe in separate thread
            new Thread(new ThreadStart(() =>
            {
                Thread.Sleep(3000);
                foreach (byte b in data)
                {
                    pipeServer.WriteByte(b);
                }

                pipeServer.Close();
            })).Start();

           // this waits util data is available in pipe and does the buffering internally.
            await blob.UploadAsync(pipeClient);
```

References:
https://docs.microsoft.com/en-us/dotnet/standard/io/how-to-use-anonymous-pipes-for-local-interprocess-communication
https://codingcanvas.com/using-anonymous-pipes-for-inter-and-intra-process-communication/

**Comment by kylewilt-conf** [comment]
Thanks for the suggestion. I want to avoid explicitly having two threads running at once for a blob upload (this is intended to be running in a service context and every thread/CPU counts). Presumably with TPL I can achieve that for the most part but I'd have to look at the guts of those classes to see if it would make sense rather than using the channel approach I was originally thinking of using. 

Either way I need to hand back a live stream instance that can be written to by the caller's own logic as that is the contract we must provide. In this case it'll have to have a live waiting upload operation inside of it until we get a proper writable stream.

**Comment by kylewilt-conf** [comment]
I looked at the anonymous pipe streams and they are an interesting piece of functionality however I'd rather avoid OS involvement since this doesn't need to cross process boundaries. Also, they don't appear to support using proper async I/O (they effectively block a thread pool thread on a ReadFile or WriteFile call) however the NamedPipeClientStream and NamedPipeServerStream classes do appear to support proper async I/O.
