### ISSUE TITLE
[QUERY]How to set server timeout for request to Azure Storage Server

### ISSUE THREAD

**Issue by EmmaZhu** [Azure/azure-sdk-for-net#11333]
**Query/Question**
I've read the code and see that in each generated request interface, timeout can be set. For example:
`public static async System.Threading.Tasks.ValueTask<Azure.Response> SetPropertiesAsync(
                Azure.Core.Pipeline.ClientDiagnostics clientDiagnostics,
                Azure.Core.Pipeline.HttpPipeline pipeline,
                System.Uri resourceUri,
                Azure.Storage.Blobs.Models.BlobServiceProperties blobServiceProperties,
                string version,
                int? timeout = default,
                string requestId = default,
                bool async = true,
                string operationName = "ServiceClient.SetProperties",
                System.Threading.CancellationToken cancellationToken = default)`

I didn't find interface for us user to set the timeout when invoking interfaces in the libraries.
Is there any way to set the timeout value?

**Environment:**
 - Name and version of the Library package used:  Azure.Storage.Blobs 12.4.1 
 - Hosting platform or OS and .NET runtime version:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.200\

Host (useful for support):
  Version: 3.1.2
  Commit:  916b5cba26

.NET Core SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]

 - IDE and version : 
      Visual Studio 16.5

**Comment by amishra-dev** [comment]
@seanmcc-msft can you please answer Emma's question.

**Comment by seanmcc-msft** [comment]
Here is an example of how to set the server-side timeout:

```
using Azure.Core;
using Azure.Core.Pipeline;
using Azure.Storage.Blobs;
using System;
using System.Threading.Tasks;

namespace ConsoleApp5
{
    public class TimeoutPolicy : HttpPipelineSynchronousPolicy
    {
        private int _timeout;

        public TimeoutPolicy(int timeout)
        {
            _timeout = timeout;
        }

        public override void OnSendingRequest(HttpMessage message)
        {
            message.Request.Uri.AppendQuery("timeout", _timeout.ToString());
        }
    }

    class Program
    {
        static string connectionString = "";

        static async Task Main(string[] args)
        {
            BlobClientOptions blobClientOptions = new BlobClientOptions();
            blobClientOptions.AddPolicy(new TimeoutPolicy(10), Azure.Core.HttpPipelinePosition.PerCall);
            BlobContainerClient blobContainer = new BlobContainerClient(connectionString, "mycontainer5", blobClientOptions);

            await blobContainer.CreateAsync();

            await blobContainer.DeleteAsync();
        }
    }
}
```

**Comment by EmmaZhu** [comment]
Thanks Sean for the example.
