### ISSUE TITLE
Microsoft.Azure.EventHubs and CancellationTokens

### ISSUE THREAD

**Issue by operationslazlo326** [Azure/azure-sdk-for-net#11340]
Has the team responsible for the Microsoft.Azure.EventHubs NuGet package ever heard of CancellationTokens?

Pretty much unforgivable in 2020 for async methods not to support them.

**Comment by serkantkaraca** [comment]
Microsoft.Azure.EventHubs is the legacy SDK and we are not making any API changes recently.

Please feel free to provide your feedback for https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs
