### ISSUE TITLE
Consider exposing a SessionCompleted event in Processor

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11349]
This would allow users to specify an event handler that will be called when the processor finishes processing each session (i.e. when a receive call times out for a particular session), which would offer more fine grained control in terms of doing other operations with a session that the processor doesn't expose. For instance, if they want to receive deferred messages from a given session, they could use the SessionCompleted event as a cue to know that they can now create a receiver scoped to this session, as the session lock should be available.

See https://github.com/Azure/azure-sdk-for-net/issues/11061

**Comment by SeanFeldman** [comment]
Technically, a session that timed out does not necessarily end and messages for that session ID can arrive much later. Therefore, would the name `SessionCompleted` accurately the intent?

**Comment by JoshLove-msft** [comment]
Yeah I suppose `SessionLockReleased` would be more technically accurate, but it doesn't convey the "why" of why the session lock is being released. Maybe `ProcessSessionCompleted` or `ProcessSessionEnd`?

**Comment by SeanFeldman** [comment]
`ProcessSessionCompleted ` and `ProcessSessionEnd` both sound as if the session was done.

What is really happening? Session processing timeouts as there are no new messages for a given session, right? So perhaps that should be the event name foundation. Not the "processor" or "completion/ending". Justin thinking out loud.

**Comment by SeanFeldman** [comment]
`SessionTimedOut`?

**Comment by JoshLove-msft** [comment]
Well, we do want to have a start event to go along with the end one. So using SessionTimedOut would be a bit awkward there, as it isn't obvious what the start event would be named.

**Comment by SeanFeldman** [comment]
That was just a name candidate. As long as the event conveys what happened rather than give a wrong impression, it's good. The challenge I had with `SessionCompleted` is that a session is never completed if yet another message with the same session ID arrives.
