### ISSUE TITLE
Consider removing "name" suffix from Create* method parameters on ServiceBusClient

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11354]
For our methods, CreateProcessor, CreateSender, CreateReceiver, etc, we have parameters like "queueName", "queueOrTopicName", etc. We should consider removing the "Name" suffix as it is debatable as to whether this adds any clarification to the usage, and may just be increasing the parameter name length with no added benefit.

Example:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Client/ServiceBusClient.cs#L198

**Comment by SeanFeldman** [comment]
Queue, topic, or subscription refers to the entities with multiple properties. Name is just one of the properties.

**Comment by danielmarbach** [comment]
I think even here a dedicated value type struct that represents a queue or a topic could be helpful. It also addresses the ambiguity of queueOrTopic overloads

**Comment by SeanFeldman** [comment]
> I think even here a dedicated value type struct that represents a queue or a topic could be helpful.

Do you want to sketch what would it look like?

**Comment by SeanFeldman** [comment]
After giving it more thought, I tend to thing a dedicated value type struct would substitute one issue with another. And that is replacing issue of a longer parameter name with an issue of more code to write just to pass in the name/path.

**Comment by JoshLove-msft** [comment]
Agreed, the original idea was to simply drop the "name" suffix, but I tend to think this would open us up to ambiguity, especially in regards to whether it should just be queue name or namespace + queue name, or something else.

**Comment by danielmarbach** [comment]
Totally fine with this. I never struggled with using those methods. The struct/value type proposal was more a brain storming kind of input rather than a strong opinion. So close?
