### ISSUE TITLE
Consider hiding lock renewal operations from Processor args

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11351]
In the ServiceBusProcessor/ServiceBusSessionProcessor, we supply the user event handler with args that provide access to settlement and lock renewal methods for the underlying receiver. Since the processor already supports auto-lock renewal, we should consider removing these methods from the event args.
[ProcessMessageEventArgs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessMessageEventArgs.cs#L131)
[ProcessSessionMessageEventArgs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessSessionMessageEventArgs.cs#L105)

**Comment by SeanFeldman** [comment]
Makes sense. Still, would rather see a `client` property on the `ProcessMessageEventArgs`.
