### ISSUE TITLE
Unable to activate website autoswap config to production

### ISSUE THREAD

**Issue by Sam7** [Azure/azure-sdk-for-net#1136]
I'm trying to define a deployment slot to autoswap with production.
Since the production deployment slot name is null
I have to set `WebSiteUpdateConfigurationDetails.AutoSwapSlotName` to `null`
Which doesn't activate autoswap. A new property is required to activate AutoSwap.

**Comment by shahabhijeet** [comment]
@Sam7 please open a new issue if the problem still exists/repros.
