### ISSUE TITLE
[BUG] Use of Azure.Identity.ManagedIdentityCredential fails when the thread culture is not en-US

### ISSUE THREAD

**Issue by fairwater** [Azure/azure-sdk-for-net#11372]
**Describe the bug**
The issue reported [here](https://github.com/Azure/azure-sdk-for-net/issues/5976) also applies to the use of the Azure.Identity.ManagedIdentityCredential.

Using Azure.Identity NuGet package v1.1.1

I have an Azure App Service (.Net Framework 4.7.2) with the following in the web.config:
`<globalization culture="en-GB" uiCulture="en-GB"/>`

When I use the ManagedIdentityCredential, in my case to connect to the Azure App Configuration at [mypath].azconfig.io, the connection fails with the exception below.

I basically cloned the code for ManagedIdentityClient and ManagedIdentityCredential so I could add some specific logging, and determined that the error was thrown from this section of the Deserialize function:

`                if (!DateTimeOffset.TryParse(expiresOnProp.Value.GetString(), out expiresOn))
                {
                    throw new AuthenticationFailedException(AuthenticationResponseInvalidFormatError);
                }`

My logging showed that the value of expiresOnProp was "4/17/2020 10:59:22 AM +00:00"

**Exception or Stack Trace**
Azure.Identity.AuthenticationFailedException: Invalid response, the authentication response was not in the expected format.
   at Azure.Identity.ManagedIdentityClient.Deserialize(JsonElement json)
   at Azure.Identity.ManagedIdentityClient.<DeserializeAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.ManagedIdentityClient.<AuthenticateAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.ManagedIdentityCredential.<GetTokenImplAsync>d__11.MoveNext()

When I removed the "globalization" element from my web config, the code worked correctly.

However, I do not wish to do so, as our app relies on the culture to correctly format a lot of information and we risk errors and confusing our customers if we do so.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report

[x] Bug Description Added
[x] Repro Steps Added

**Comment by schaabs** [comment]
@fairwater thank you for filling this issue. We are currently working on a fix for this issue. I'll add more information once we have an better idea when a release with the fix will be available.

**Comment by schaabs** [comment]
This issue was fixed with PR https://github.com/Azure/azure-sdk-for-net/pull/11563 and was released in our 1.2.0-preview.3 release a few days ago. Please give it a try and feel free to reopen the issue if the fix doesn't address your issue. 

This round of previews is set to GA sometime this summer, but if there is an critical need for a GA fix sooner we could possibly release a patch fix to 1.1.1, just let us know.
