### ISSUE TITLE
Create a utility to demonstrate migration of legacy checkpoints for use with the EventProcessorClient

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#11373]
# Summary

In order to align with the goal of supporting cross-language checkpoints and a more efficient means of tracking partition ownership, the `EventProcessorClient` does not consider or apply checkpoints created with the legacy `Microsoft.Azure.EventHubs.Processor` family of types.   This is a potential area of confusion and an opportunity to provide a migration utility to improve the migration experience.

# Scope of Work

- Create a stand-alone utility for the `Azure.Messaging.EventHubs.Processor` package that reads legacy checkpoint data from the default Azure Storage Blobs provider and migrates it to the format used by the `EventProcessorClient`.

- Determine if the utility is better included as a sample in the Event Hubs area of the repository, part of the cross-service samples, or another area is preferred for small utility items.   Once a decision is made, ensure the utility is hosted and discoverable.

- Update the Event Hubs migration guide to reference the utility to assist in the migration process.

# Success Criteria

- A stand-alone utility exists which can read checkpoint data emitted by the legacy `EventProcessorHost` when using the default Azure Storage Blobs provider and migrate it to a new Blob container in the correct format to be used by the `EventProcessorClient`.

# Related Items

-  Update the migration guide to document that processor checkpoints from legacy versions are not applied ([#11374](https://github.com/Azure/azure-sdk-for-net/issues/11374))

**Comment by jsquire** [comment]
Potentially invalidated by #17474.   Moving to the backlog until the path forward is chosen.

**Comment by jsquire** [comment]
@ramya-rao-a: Have any decisions been made on this?

**Comment by ramya-rao-a** [comment]
Given that we have the code required to do the migration documented in our Migration Guide at [Migrating EventProcessorHost checkpoints](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md#migrating-eventprocessorhost-checkpoints), we no longer need the utility tool requested in this issue
