### ISSUE TITLE
Azure.Security.KeyVault for storage accounts

### ISSUE THREAD

**Issue by festivus** [Azure/azure-sdk-for-net#11377]
The Microsoft.Azure.KeyVault library has support for interacting with managed storage accounts. When I go to use this package I see that it says it's been replaced by new Azure SDKs but I don't see a new SDK that deals with storage accounts in KeyVault. What am I supposed to use to deal with managed storage accounts in keyvault?

**Comment by heaths** [comment]
That functionality was added to Key Vault before Storage supported AAD / RBAC protection, which the Storage team recommends. As such, we have no plans to bring that functionality to the new Azure.Security.KeyVault packages. If you cannot use AAD / RBAC for Storage, you can use the older Microsoft.Azure.KeyVault package but do not there are some limitations to managing Storage accounts this way, it's not as secure, and keys should be rotated periodically making this harder to manage as well.

**Comment by festivus** [comment]
@heaths Storage does NOT support AAD/RBAC for Table storage, which is what managed storage accounts deals with.

**Comment by tg-msft** [comment]
Correct, Storage doesn't support AAD for either Tables or Files.
