### ISSUE TITLE
Exception responses with Azure.Management.ContainerRegistry-5.0.0-Preview changed

### ISSUE THREAD

**Issue by launchpad15** [Azure/azure-sdk-for-net#11382]
With the 4.0.0 version of the ContainerRegistry, the CancelAsync API used to return the following message when querying an invalid buildId
          **Resource with id '{acrBuildId}' is not found"** 

But with with 5.0.0-Preview it is throwing 
           **Operation returned an invalid status code 'NotFound"**

Can this be looked at? the "NotFound" is a very generic message and a more detailed message like the one in 4.0.0 is super useful that does not break backward compat for clients that are heavily relying on these messages that are thrown from ACR.

**Comment by isra-fel** [comment]
Steve or Yugang, could you share your insights on this issue? Thanks
cc @northtyphoon @ankurkhemani

**Comment by yugangw-msft** [comment]
@northtyphoon, please take a look. This is on tasks

**Comment by northtyphoon** [comment]
@launchpad15 as we talked offline, Task API has switched to ErrorResponseException. Please use ErrorResponseException.Body.Error.Message to get the error.

https://www.nuget.org/packages/Microsoft.Azure.Management.ContainerRegistry/5.0.0-preview
