### ISSUE TITLE
[BUG]Microsoft.Azure.ServiceBus.RunOperation has unused collection of exceptions

### ISSUE THREAD

**Issue by jbrezina** [Azure/azure-sdk-for-net#11402]
In Microsoft.Azure.ServiceBus.RunOperation there is defined a list of exceptions which is never used.
https://github.com/Azure/azure-sdk-for-net/blob/599133b04a9f62b776beda43413a450fa3884296/sdk/servicebus/Microsoft.Azure.ServiceBus/src/RetryPolicy.cs#L62

**Comment by nemakam** [comment]
@jbrezina , Thanks for reporting this. 
Yes, looks like it is indeed unused. Is this causing any issues right now?

**Comment by jbrezina** [comment]
If the exception list was not meant for anything I don't think it causes any problems. I was just looking for exceptions which are thrown in functions using this code and noticed it.

**Comment by nemakam** [comment]
@jbrezina, got it. Thanks. Initially, the plan was to return all the exceptions that happened back to the customer. But then it doesn't make sense to pass the exception if ultimately retry did fix it. So instead, the exceptions are just logged right now. We will just have to clean up this variable. I'm not sure if when will we end up prioritizing on this task given the impact being too low. Feel free to raise a PR on this if needed. :)

**Comment by axisc** [comment]
@jbrezina, We will proceed to close this issue. There is a new SDK that is being developed and the changes on the older SDK (Microsoft.Azure.ServiceBus) are limited to bug fixes or features (on a case by case basis). Since this is not breaking any specific scenarios, cleaning it up is a feature change that we will defer.
