### ISSUE TITLE
[CodeGen] Move to .NET Code Gen LROs

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11417]
## Summary

Per @pakrym, the C# code generator creates `Operation<T>` subclasses automatically from swagger files.  We'll want to understand the output and whether it can be used for the LROs in the FormRecognizer library.

## Goals

- Understand the LRO output from code generator
- Determine whether existing FR LRO functionality can be implemented with only small changes to this output
- If code gen LRO code can be used for FR, implement this
- If code gen LRO code differs too much from the FR functionality, we should keep the hand-written Operation<T> classes and close this issue.

**Comment by annelo-msft** [comment]
Do these together: https://github.com/azure/azure-sdk-for-net/issues/11484

**Comment by pakrym** [comment]
I think this is not valid anymore, when we moved to only generate rest clients for data-plane we stopped generating operations as well.
