### ISSUE TITLE
Handling Blob MetaData

### ISSUE THREAD

**Issue by MohammedTawfik** [Azure/azure-sdk-for-net#11432]
**Query/Question**
i have two questions regarding blob metadata : 
1. How i can set the blob metadata when i upload it using blobclient.upload
2. How i can delete certain entry from blob metdata 

**Environment:**
 - Name and version of the Library package used:  Azure.Storage.Blobs 12.2.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.0.100\

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33
 - IDE and version : Visual Studio 2019 (16.3.10)

**Comment by blueww** [comment]
@AlexGhiondea 
Please add "Client" tag besides "Storage" tag.
This is a dataplane issue.
We use "Storage"+"Client" to identify Storage dataplane issue.
We use "Storage" tag only to identify Storage management plane issue.

**Comment by amishra-dev** [comment]
No worries @AlexGhiondea, i will take this. Thanks @blueww

**Comment by amnguye** [comment]
Hello I've provided some example snippets below.

1) Setting metadata through upload
```
BlockBlobClient blob = container.GetBlockBlobClient("blob_name");
Metadata metadata = BuildMetadata();

using (var stream = new MemoryStream(data))
            {
                await blob.UploadAsync(
                    content: stream,
                    metadata: metadata);
            }
```

2) How i can delete certain entry from blob metdata
There's not a way to do this through the REST API call without providing all the other metadata headers that you don't want to remove.
https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata#request-headers
See: x-ms-meta-name:value

**Comment by seanmcc-msft** [comment]
Hi @MohammedTawfik,

To remove a metadata entry from a blob, call ```BlobClient.GetPropertiesAsync()```.  The blob's metadata will be ```Response.Value.Metadata```.  Remove the metadata entry in question, and call ```BlobClient.SetMetadataAsync()``` with the metadata.

-Sean
