### ISSUE TITLE
EventHubProducerClient (Azure.Messaging.EventHubs) doesn't correctly protect against oversized batches

### ISSUE THREAD

**Issue by OperatorOverload** [Azure/azure-sdk-for-net#11434]
**Describe the bug**
I was working on upgrading from the legacy (V4) version of the library to the new Azure.Messaging.EventHubs v5 library, and noticed that the documentation here (https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md) claims that the new design of the library means that the TryAdd will automatically fail if the batch size is too large.  This is a nice improvement, so I assumed it worked as I refactored my code to run against v5.  My testing is done against a Basic pricing tier instance, and at first execution I immediately got an error about the size of the batch as follows:

I suspect the issue here is that the library is not factoring in the overhead required to actually send the batch, which my experience puts at 6-8% 

**Expected behavior**
The library should adjust its sizing behavior to account for overhead to ensure that it can actually send the amount of data it plans to send.

**Actual behavior (include Exception or Stack Trace)**
When submitting the first batch after TryAdd fails, I receive the following:
Unhandled exception. Azure.Messaging.EventHubs.EventHubsException: The message (id:64727435, size:430284 bytes) is larger than is currently allowed (262144 bytes). (client)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(Func`1 messageFactory, String partitionKey, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(Func`1 messageFactory, String partitionKey, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(EventDataBatch eventBatch, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.SendAsync(EventDataBatch eventBatch, CancellationToken cancellationToken)
... [my code paths redacted]

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a batch using the standard parameters (using CreateBatchAsync());
2. Add Limit minus a few bytes to the batch (so for Standard tier, a couple bytes short of 1MB, for Basic tier, a a couple bytes short of 256KB).
3. Attempt to send batch, error appears.

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.0.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET Core SDK (reflecting any global.json):
 Version:   3.1.100
 Commit:    cd82f021f4

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db
 - IDE and version : [e.g. Visual Studio 16.3]
Visual Studio Enterprise 16.4.2

**Comment by OperatorOverload** [comment]
Believe this one will likely start with @jsquire

**Comment by OperatorOverload** [comment]
Actually, after further testing, I need to expand the scope of this report.  I changed my testing Event Hub tier to Standard, and queued up a few MB of events to be transferred.  At first run, I got the following: 

`The message (id:20974680, size:1111395 bytes) is larger than is currently allowed (1046528 bytes). (client) | Azure.Messaging.EventHubs.EventHubsException`

So in this case it looks like it's failing in either case (Basic or Standard) if you push it all the way to the limit.  Is it possible that the checks in TryAdd are not including some buffer space for the message metadata overhead?  The previous documentation talked about that, and my own internal testing previously indicated that reserving ~10% of the size for overhead would always be enough (actual numbers seem to be between 5-8%.

Also possible I'm missing something here since I had ported my code over from the prior version, but any ideas would be appreciated.  For now I've re-implemented my own size limit checks and will just stick with those.

**Comment by OperatorOverload** [comment]
Ok, some additional feedback here, it looks like this was ultimately a race condition in my own code where I missed awaiting an Async task and thus the TryAdd and SendBatch were being called many times over in certain cases.  However, that would seem to still point to an issue with the thread safety around TryAdd, the code in there seems to imply that it's thread safe, but my experience indicates otherwise at least in terms of testing for space in the batch before adding.  Might be worth looking into

**Comment by jsquire** [comment]
Hi @OperatorOverload.   We're sorry that you're having difficulties and appreciate you reaching out to let us know.  You're correct in that the `EventDataBatch` in v5.0.1 was intentionally not thread-safe, leaving any synchronization to callers but not explicitly documenting that.

The good news is that this was something that we had recently revisited and made the decision to hold the responsibility for being thread-safe within the batch.  #11203 included those changes and will appear in our next release.

**Comment by jsquire** [comment]
Discussion seems to have concluded, so I'm going to close this out.   Please feel free to reopen if the is additional feedback that you'd like to discuss for this topic.

**Comment by OperatorOverload** [comment]
Agreed @jsquire, my issues were all related to concurrency, I've implemented my own protection for now, but glad the library will get it moving forward.
