### ISSUE TITLE
Should BeginCreateOrUpdate be removed from the SQL Databases Operations?

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/azure-sdk-for-net#11449]
Should **BeginCreateOrUpdate** / **BeginCreateOrUpdateAsync**be removed from the SQL Databases Operations?
`var operationResponse = await client.Databases.BeginCreateOrUpdate(resourceGroupName, sqlServerName, sqlDatabaseName, createOrUpdateParameters);`

https://github.com/Azure/azure-sdk-for-net/blob/dc23a39caf37d07f02512540d20c29866ff83759/sdk/sqlmanagement/Microsoft.Azure.Management.SqlManagement/src/Generated/DatabasesOperationsExtensions.cs#L1018

`operationResponse is null;`

I assume `BeginCreateOrUpdateWithHttpMessagesAsync` is supported?
Could poll using the response Id?
Should we be using `CreateOrUpdate` instead?

Versions c# :
microsoft.azure.management.sql\1.33.0-preview\lib\net452\
microsoft.rest.clientruntime\2.3.20\lib\net452\

**Comment by markcowl** [comment]
@mikeblakeuk  This is a standard pattern in azure .net sdk operations. The Begin* methods are meant to start off a long-running operation.  You would need to poll for completion afterward.  If you do not want to do your own polling, you should use CreateOrUpdateAsync.
