### ISSUE TITLE
Support SubjectName/Issuer (SNI) certificate authentication for Service Principals

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#11447]

**Comment by joshfree** [comment]
Moving this to the Iron semester

**Comment by joshfree** [comment]
Related: https://github.com/AzureAD/microsoft-authentication-library-for-python/issues/60

**Comment by schaabs** [comment]
Completed by https://github.com/Azure/azure-sdk-for-net/pull/14636
