### ISSUE TITLE
Document code generation process

### ISSUE THREAD

**Issue by mj1856** [Azure/azure-sdk-for-net#1144]
A large amount of code in this project is marked as "Generated", but there's nothing in the project readme that explains how the code is generated.

- What is it generated *from*?  Where are the templates?
- What tool is used to generate it?

If I find a bug in one of the generated files, clearly it's not appropriate to send a pull request for those directly.  Instead, one would expect to make the correction in the corresponding template.

Please explain this clearly in the project readme.  Thanks.

**Comment by matt-gibbs** [comment]
@mj1856 Will do.
The "Generated" code was produced with an "old" version of our code generator that isn't public. It wasn't using templates.
We are just finishing some changes to finish open sourcing the new version of the generator at https://github.com/azure/autorest 
Today, it only has the client runtime pieces. The generator itself will be added in a few weeks. Saw the Twitter conversation about constructing URLs. The new version is better:
![image](https://cloud.githubusercontent.com/assets/6565986/7926630/53765026-088a-11e5-8526-5faacca71ca6.png)
The  new version should let us get rid of the unnecessary check against the queryParameters.Count too.

**Comment by matt-gibbs** [comment]
Readme updated to direct generated code issues to the AutoRest project.  Code-generators being added to AutoRest project next week.

**Comment by mj1856** [comment]
Thanks!

**Comment by mj1856** [comment]
Except the link to autorest is broken.  I think just a typo in the markdown.
