### ISSUE TITLE
[Design] Consider taking Guid for modelId instead of string

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11452]
A concern was raised by @pakrym that we enforce a guid format without requiring a Guid type in RecognizeCustomForm methods.

In the SDK, we prefer Uri to string, and Timespan to int timeInSeconds, etc.

Keeping it as a string provides some flexibility to support additional modelId formats in the future.  Consider whether this flexibility could be provided as additive changes in future library versions.

Related to https://github.com/Azure/azure-sdk-for-net/issues/10930

**Comment by annelo-msft** [comment]
@kinelski

**Comment by maririos** [comment]
After discussing this with sdk and service team, the decision was to leave it as string and ensure the sdk validates that we can convert the string into a GUID

**Comment by maririos** [comment]
We already do validation for it thanks to https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ClientCommon.cs#L18

so we are good. Closing
