### ISSUE TITLE
[FEATURE REQ]  AuthorizationManagementClient sample

### ISSUE THREAD

**Issue by bachoang** [Azure/azure-sdk-for-net#11463]
**Query/Question**
How can we help?
There is documentation for this class here:  https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.graph.rbac.fluent.authorizationmanagementclient?view=azure-dotnet
Please provide a sample for how to use this class

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by isra-fel** [comment]
@weidongxu-microsoft  Hi Weidong, could you help on this issue? Thanks

**Comment by weidongxu-microsoft** [comment]
@bachoang 

This class is not intended to be used directly (well, you can, but it could be a bit complicated).

The class that actually send the REST API is its properties, e.g. [RoleAssignments](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.graph.rbac.fluent.iroleassignmentsoperations?view=azure-dotnet), [RoleDefinitions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.graph.rbac.fluent.iroledefinitionsoperations?view=azure-dotnet)

Here is a few samples using graphrabc on Fluent .NET SDK (the preferred usage).
https://github.com/Azure/azure-libraries-for-net/tree/master/Samples/GraphRbac

Let us know if you need sample on any specific area.

**Comment by bachoang** [comment]
Thanks @weidongxu-microsoft for the hint.  I was able to figure out the problem based on the sample code you pointed out.  The scenario I want to achieve is to create an App Role Assignment to assign an AAD Group Storage Blob Data Reader role to a particular Azure Storage Blob container.  There is no sample for this scenario.  I looked at the Azure Storage samples repository.  They don't address Blob container either and the DefaultBuiltIn Role Defintion object does not the above role ID.  It would be good if you can document which class is meant to be used directly and which class is not.  There is no sample link to each class and their methods which make it hard for developers to figure out how to use the API correctly.

**Comment by weidongxu-microsoft** [comment]
For Fluent SDK, the entry point usually is `IAzure` as globally for all services, or `FooManager` for foo service (in this case, `GraphRbacManager` https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.graph.rbac.fluent.graphrbacmanager?view=azure-dotnet)

The entry point could be simpler in future track2 SDKs. But it might still take a few months.
