### ISSUE TITLE
Remove Search code generation script

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#11478]
We need to remove https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/generate.ps1.

We should see if AutoRest allows multiple remote swaggers now or update https://github.com/Azure/azure-sdk-for-net/blob/master/eng/CodeGeneration.targets to allow multiple AutoRest literate READMEs in one library.

**Comment by AlexGhiondea** [comment]
This is done.
