### ISSUE TITLE
[Design] [FormRecognizer] Handle operation failed status consistently across Recognize and Train LROs

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#11473]
## Summary

When a training operation fails, no exception is thrown. The developer needs to manually check their model status and errors to assert it has succeeded before actually making use of the model.

```cs
var op = await trainingClient.StartTrainingAsync(...); // POST request succeeds
await op.WaitForCompletionAsync(); // GET request succeeds and returns a failed operation

// op.Value.Status must be checked.
```

Getting no exceptions could be misinterpreted as a sign that the training operation has succeeded.

However, throwing an exception in case of failure could be risky as well. It could give the developer the impression that the whole operation has failed and that no model has been created. They should be able to immediately retrieve the model id and delete it if desired. The current implementation allows that.

## Goals

- Discuss with the team what the expected behavior should be.
- If necessary, update the client code so it can behave as expected.
- Create tests to validate the chosen approach.
- Make sure existing tests still pass reliably.

**Comment by annelo-msft** [comment]
In addition:
- Handle `RecognizeReceipt` and `RecognizeContent` LROs the same way as `RecognizeCustomForms` (per https://github.com/azure/azure-sdk-for-net/issues/11474)
- Ensure we're consistent across the LROs regarding the exception we throw when the operation fails
- Ensure we're consistent across the LROs regarding how we return `Value` when the operation failed (per https://github.com/azure/azure-sdk-for-net/issues/10392, https://github.com/azure/azure-sdk-for-net/issues/11466)

**Comment by annelo-msft** [comment]
@kristapratico  working on this on the Python side: https://github.com/Azure/azure-sdk-for-python/issues/11323
