### ISSUE TITLE
Storage: Add `Authenticate the Client` to all Storage READMEs

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#11492]
We have a new requirement to add an `Authenticate the Client` subsection under our `Getting Started` heading that gives users the a super quick copy/paste snippet they can use as a jumping off point.  We need to add these to the following Storage READMEs:

/sdk/storage/Azure.Storage.Blobs/README.md
/sdk/storage/Azure.Storage.Blobs.Batch/README.md
/sdk/storage/Azure.Storage.Blobs.Cryptography/README.md
/sdk/storage/Azure.Storage.Common/README.md
/sdk/storage/Azure.Storage.Files.DataLake/README.md
/sdk/storage/Azure.Storage.Files.Shares/README.md
/sdk/storage/Azure.Storage.Queues/README.md

See https://github.com/Azure/azure-sdk-for-net/pull/11413 for more details.

**Comment by jsquire** [comment]
Closing, as these sections now exist and are validated as part of CI runs.  Please feel free to reopen if further discussion is needed.
