### ISSUE TITLE
Assembly version conflicts with NuGet?

### ISSUE THREAD

**Issue by rogerguess** [Azure/azure-sdk-for-net#1149]
I installed via nuget, and the client is not matching:

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>CSC : error CS1705: Assembly 'Microsoft.WindowsAzure.Management.HDInsight' with identity 'Microsoft.WindowsAzure.Management.HDInsight, Version=1.5.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.Hadoop.Client, Version=1.5.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.Hadoop.Client' with identity 'Microsoft.Hadoop.Client, Version=0.10.0.80, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
1>c:\users\rguess\documents\visual studio 2015\Projects\HDIMon\HDIMon\Program.cs(33,22,33,45): error CS1705: Assembly 'Microsoft.WindowsAzure.Management.HDInsight' with identity 'Microsoft.WindowsAzure.Management.HDInsight, Version=1.5.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' uses 'Microsoft.Hadoop.Client, Version=1.5.8.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'Microsoft.Hadoop.Client' with identity 'Microsoft.Hadoop.Client, Version=0.10.0.80, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

**Comment by shefaliv** [comment]
Hi Roger,
I’m on the HDInsight team and saw the issue on Github. Can you please try removing the current NuGet packages and downloading the latest NuGet packages (version 1.5.9 of Microsoft.Hadoop.Client and 1.5.9 of Microsoft.WindowsAzure.Management.HDInsight). Please shoot me an email if this doesn't work!

**Comment by shefaliv** [comment]
Can you please try removing the current NuGet packages and downloading the latest NuGet packages (version 1.5.9 of Microsoft.Hadoop.Client and 1.5.9 of Microsoft.WindowsAzure.Management.HDInsight). Please shoot me an email if this doesn't work!

**Comment by rogerguess** [comment]
I should have a chance to try later today. Thank you.

On Tue, Jun 9, 2015 at 12:40 PM, shefaliv <notifications@github.com> wrote:

> Hi Roger,
> I’m on the HDInsight team and saw the issue on Github. Can you please try
> removing the current NuGet packages and downloading the latest NuGet
> packages (version 1.5.9 of Microsoft.Hadoop.Client and 1.5.9 of
> Microsoft.WindowsAzure.Management.HDInsight). Please shoot me an email if
> this doesn't work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Azure/azure-sdk-for-net/issues/1149#issuecomment-110443129>
> .
>



-- 
Thanks,
Roger

**Comment by rogerguess** [comment]
Those newer versions 1.5.9 are not showing up in nuget.

**Comment by shefaliv** [comment]
Not sure why the cache isn't refreshing in the manager. Can you try the install command shown here to install it? https://www.nuget.org/packages/Microsoft.WindowsAzure.Management.HDInsight/

**Comment by shahabhijeet** [comment]
@rogerguess please open a new issue if the problem still exists/repros.
