### ISSUE TITLE
[FormRecognizer] Parse operation IDs with regex

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#11505]
## Summary

The implementation of the Operation constructors uses some magic numbers when parsing the operation ID.

### Operations to address
- [ ] `CopyModelOperation`
- [ ] `RecognizeContentOperation`
- [ ] `RecognizeCustomFormsOperation`
- [ ] `RecognizeReceiptsOperation`
- [ ] `RecognizeIdDocumentsOperation`
- [ ] `TrainingOperation`
- [ ] `AnalyzeDocumentOperation`
- [ ] `ClassifyDocumentOperation`

### Internal constructor
https://github.com/Azure/azure-sdk-for-net/blob/e32b2e7f7fab4d7209da788250caa2c145b23c66/sdk/formrecognizer/Azure.AI.FormRecognizer/src/RecognizeCustomFormsOperation.cs#L78-L83

The `internal` constructor takes a parameter called `operationLocation`, which is returned from the service and is expected to look like:
```
{endpoint}/formrecognizer/{version}/custom/models/{modelId}/analyzeresults/{resultId}
```

### Public constructor
https://github.com/Azure/azure-sdk-for-net/blob/e32b2e7f7fab4d7209da788250caa2c145b23c66/sdk/formrecognizer/Azure.AI.FormRecognizer/src/RecognizeCustomFormsOperation.cs#L102-L112

The `public` constructor, on the other hand, takes a parameter called `operationId`, which is given by the developer and is expected to be a substring of the aforementioned `operationLocation`:
```
{modelId}/analyzeresults/{resultId}
```

## Goals
- Stop using magic numbers and correctly parse the arguments using regex, handling format errors.
- Make sure we support parsing model IDs with characters `_`, `~`, and `.`. These characters are allowed when naming a custom model.
- Include new tests to verify proper behavior.
- Make sure existing tests still pass reliably.

The following file can be used as a reference:
https://github.com/Azure/azure-sdk-for-net/blob/80a63242c93cbbff1ee525248cbd94d89ed72345/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormField.cs#L90-L91

Related: #10385

**Comment by maririos** [comment]
@kinelski  is this for P3? or should we put it in the backlog epic

**Comment by kinelski** [comment]
@maririos I wouldn't say it's a high-priority issue, since it just changes the behavior internally. @annelo-msft is keeping track of what issues we want closed for P3.

**Comment by maririos** [comment]
Thanks Caio. I put the issue in the backlog epic. In general, it is better if we don't have issues floating around without an epic.

**Comment by annelo-msft** [comment]
Closed https://github.com/Azure/azure-sdk-for-net/issues/10385 and added full list of operations to this issue.

**Comment by suhas92** [comment]
@annelo-msft As TA is also using the LRO pattern and will require to parse out the operation location id. Referring to this Issue in the SDK code.

**Comment by maririos** [comment]
This parsing is specific to FR. If you need it for TA, then you can do Regex in TA

**Comment by maririos** [comment]
By changing the parsing, the errors might change too, so we need to be careful here to not introduce breaking changes.
Will wait first on the outcome of https://github.com/Azure/azure-sdk-for-net/issues/17383 before working on this to make sure we have the coverage

**Comment by pallavit** [comment]
@kinelski is this still valid, can it be closed?

**Comment by pallavit** [comment]
Is this a change to the implementation or a feature request?

**Comment by kinelski** [comment]
> Is this a change to the implementation or a feature request?

It's a change to the implementation to improve code readability.

**Comment by pallavit** [comment]
Given the change to document intelligence @kinelski do you still think this is something we should continue to track? Do you see us prioritizing this work any time soon?
