### ISSUE TITLE
[BUG] Unable to use interactive login from VSCode Dev Container

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-sdk-for-net#11509]
x-post from [this stackoverflow question](https://stackoverflow.com/questions/61093766/interactive-login-with-azure-sdks-from-w-in-vscode-devcontainer)

**Describe the bug**

When using devcontainers on a project where we are relying on MSIs for app-to-app communication, we are utilizing `DefaultAzureCredential` as the class to load either from the local developer's machine or, on Azure, the MSI of the running service. In order to get this working, I found we needed to add the `includeInteractiveCredentials: true` parameter to the constructor. This results in an actual browser window getting popped from when the code is hit (pretty cool, honestly). If we didn't have this parameter set, it wasn't picking up any user creds to access the resources.

The problem we're having is when we load our solution **in its devcontainer**, the browser login that would normally pop at debug time to pull the local user's credentials isn't allowed to start up. Instead we are met with the following error:

> Azure.Identity: DefaultAzureCredential authentication failed. InteractiveBrowserCredential authentication failed. Microsoft.Identity.Client: Unable to open a web page using xdg-open. See inner exception for details. Possible causes for this error are: xdg-open is not installed or it cannot find a way to open an url - make sure you can open a web page by invoking from a terminal: xdg-open https://www.bing.com . System.Diagnostics.Process: No such file or directory.

We then added `xdg-utils` to our `apt-get` call in our Dockerfile but now we are met with

```
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 870: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'https://login.microsoftonline.com/...'
```

I've gone so far as clicking the link/pasting it in to my host OS browser, logging in, then looking at the port that's attempted for callback (e.g. `localhost:44663`) and immediately doing a "forward port" from the VSCode command pallet but this also failed saying the state object doesn't match.

Additionally, doing an `az login` w/in the container doesn't alleviate the issue.

How are we supposed to use local Azure credentials from within a Dev Container? Keep in mind we'd like to avoid having to create a Service Principal *in Azure* just to get *local* development working.

**Expected behavior**

Interactive login could simply use Device Code flow instead of trying to pop a browser and it'd work fine everywhere. Regardless, I expect to be able to use my user credentials to log in to Azure from w/in a VS Code dev container.

**Actual behavior (include Exception or Stack Trace)**

See above

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

https://github.com/brandonh-msft/functions-storage-managed-identity#how-we-obtain-local-user-and-azure-msi-credentials-within-the-function

**Environment:**
 - Name and version of the Library package used
   - Azure.Identity 1.1.1
   - Azure.Storage.Blobs 12.4.1

 - Hosting platform or OS and .NET runtime version
   - Windows 10, netcore 3.1

 - IDE and version
    - VSCode latest

## Other information

For those wondering, the error we get without setting interactive=true is

> An exception of type 'Azure.Identity.CredentialUnavailableException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'DefaultAzureCredential failed to retrieve a token from the included credentials. EnvironmentCredential authentication unavailable. Environment variables are not fully configured. ManagedIdentityCredential authentication unavailable, no managed identity endpoint found. SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.'

**Comment by schaabs** [comment]
@brandonh-msft Thanks for filing this issue. I'll need to investigate if there is another way we could launch the browser process in this case. 

However, since you mentioned you're able to run az login in the dev container, you could try the latest Azure.Identity preview [1.2.0-preview.2](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/CHANGELOG.md#120-preview2). In this preview we have updated the DefaultAzureCredential so that it can authenticate through the Azure CLI, as well the Azure Account VS Code plugin. I'm not 100% sure the latter will work from a dev container, but if you are running the Azure CLI in the dev container it should work.

**Comment by brandonh-msft** [comment]
I'll give this a try ASAP

**Comment by brandonh-msft** [comment]
No dice. Using the sample I linked here's the error I get w/ the new nupkg:

> Azure.Identity: DefaultAzureCredential authentication failed. Azure.Identity: VisualStudioCodeCredential authentication failed. Azure.Identity: Unable to load shared library 'libsecret-1.so.0' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibsecret-1.so.0: cannot open shared object file: No such file or directory.

**Comment by brandonh-msft** [comment]
I then added `libsecret-1-0` to my devcontainer's dockerfile and tried again:

> Azure.Identity: DefaultAzureCredential authentication failed. Azure.Identity: VisualStudioCodeCredential authentication failed. Azure.Identity: An error was encountered while reading secret from keyring, domain:'140', code:'0', message:'Cannot autolaunch D-Bus without X11 $DISPLAY'.

**Comment by brandonh-msft** [comment]
I pushed this work to [a new branch on my sample](https://github.com/brandonh-msft/functions-storage-managed-identity/tree/identity-prerelease-nupkg)

**Comment by schaabs** [comment]
It looks like you're running into an issue where the `VisualStudioCodeCredential` is failing in a way which is failing authentication where it should be raising a `CredentialUnavailableException` so that the `DefaultAzureCredential` authentication flow can continue to the `AzureCliCredential`. @AlexanderSher can we file an issue to raise `CredentialUnavailableException` in the case that libsecret is not available or the d-bus daemon is not running.

@brandonh-msft you should be able to get passed this issue by disabling the `VisualStudioCodeCredential` via the `DefaultAzureCredentialOptions` like so:

~~~c#
var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { DisableVisualStudioCodeCredential = true });
~~~

**Comment by schaabs** [comment]
@brandohn-msft I don't see anyway we can actually launch a browser in this scenario as the container doesn't have a browser installed, or a UI stack for that matter. It's possible that VS Code could add a different mechanism for authenticating in a Dev Container as it is able to communicate with the container via SSH. However, unfortunately it seems the `InteractiveBrowserCredential` is not supported from inside a container. If you disagree please feel free to reopen the issue.

Also, please let me know if you're still having trouble getting authentication working via the Azure CLI. I think this is the most viable work around in this case.

**Comment by brandonh-msft** [comment]
@schaabs :

> @brandonh-msft you should be able to get passed this issue by disabling the `VisualStudioCodeCredential` via the `DefaultAzureCredentialOptions` like so:

Thanks I'll try this in the linked sample and report back.

> @brandohn-msft I don't see anyway we can actually launch a browser in this scenario as the container doesn't have a browser installed, or a UI stack for that matter.

Yeah this is why I suggested having it use Device Code flow as its "interactive" implementation instead of trying to pop a browser.

> Also, please let me know if you're still having trouble getting authentication working via the Azure CLI. I think this is the most viable work around in this case.

Not sure what you mean by this - I did do `az login` in the course of testing the new Preview SDK....

**Comment by brandonh-msft** [comment]
> by disabling the `VisualStudioCodeCredential` via the `DefaultAzureCredentialOptions` like so:
> 
> ```cs
> var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { DisableVisualStudioCodeCredential = true });
> ```

in case anybody else comes across this item, the code is:

```csharp
new DefaultAzureCredential(new DefaultAzureCredentialOptions { ExcludeVisualStudioCodeCredential = true })
```

**Comment by schaabs** [comment]
@brandonh-msft 
> Yeah this is why I suggested having it use Device Code flow as its "interactive" implementation instead of trying to pop a browser.

This is an interesting suggestion that I missed this on the first read-through of this issue. 

The only problem I forsee with this is that currently the `DeviceCodeCredential` doesn't do any interaction on it's own, and relies on the developer to provide a callback which will display the device code to the user. It's possible that if we were to add this to the end of the `DefaultAzureCredential` authentication flow, we could provide a default implementation of this callback that displays the device code to the console. My concern with this would be if the app didn't have a console which is visible to the user, the application would appear to hang until the timeout of the device code is reached. 

Another possibility is that we could allow the user to specify this callback as an option when creating the `DefaultAzureCredential`, and only fallback to the `DeviceCodeCredential` if this callback has been specified. This unfortunately makes this behavior not exactly default. What are your thoughts on this?

>  Also, please let me know if you're still having trouble getting authentication working via the Azure CLI. I think this is the most viable work around in this case.
>  Not sure what you mean by this - I did do az login in the course of testing the new Preview SDK....

I meant let me know if authentication through the Azure CLI is still not working once you disable the `VisualStudioCodeCredential` to work around the issue you hit with libsecret not running inside the container. Thank you for adding the correct code snippet.

**Comment by brandonh-msft** [comment]
Good news! I added the `ExcludeVisualStudioCodeCredential = true` option to the `DefaultAzureCredential` ctor and it worked perfectly. I event hit a resource in a different tenant than my default one without issue. So it seems adding that exception will solve the issue we're having and fall back to the creds pulled by `az login` - should we keep this issue open to cover that work?

Regarding the option for Device Code, while I'm not an expert, it seems that the current way of popping a browser to auth also has some sort of callback, does it not? Would it not be similar to this?
If port mapping, etc. are of concern we have the ability to forward ports from the host to the devcontainer using the `forwardPorts` specification of `devcontainer.json` (in fact we do this to enable debugging of Azure Functions while w/in the dev container).
