### ISSUE TITLE
.NET SDKs to access file share with File Service SAS Token

### ISSUE THREAD

**Issue by arde0708** [Azure/azure-sdk-for-net#11519]
**Query/Question**
I am reaching out in regards to few doubts about accessing File Share using SAS Token via the .NET SDK's. I have a **File Service SAS Token**(not the Connection String of the Storage Account). Using that, I am trying to do the following using .NET SDK's 
1.	Fetch the properties of storage account. I see there is a REST API( Ref #1 )  endpoint for that which uses only the storage account name ,subscription ID and Resource group, but looking for the equivalent .NET API. 
2.	I have been able to access file share using the File Share SAS Token. However, once I have the reference to the file share, I am unable to see the quota on that. From the portal, I see the allotted storage is 100 GiB. But, the value I see in `share.Properties.Quota = null`. 

Code :
```
CloudFileShare share = cloudBlobClient.GetShareReference("exporttemplate"); // File share name : "exporttemplate"
CloudFileDirectory rootDir = share.GetRootDirectoryReference(); // No errors here
CloudFileDirectory sampleDir = rootDir.GetDirectoryReference("Exported416"); // No errors here either. Directory name = "Exported416"
```

However, the below check fails saying `"You-are-not-authorized-to-perform-this-operation"`. My understanding is that since my SAS is a File Service SAS Token, I should be able to access/run anything that is part of the fileshare.      
 ```
          if (share.Exists()){
          }
```

For the first question above 1): I am specifically looking for the following properties of the Storage account and was wondering if there are any alternatives to fetch those properties given that I would have only the File Share SAS Token.
a. Checking the Storage Account existence 
b. Perform SAS Token validation
c. Checking Storage Account configuration : type : PFS, General Purpose V2
d. Quota : enough space exists for the files I am about to copy over to the directory in the file share.
e. Checking whether the storage the is some particular VNET( the same one as my source server which hosts a MySQL instance)

Ref #1:
https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/getproperties

**Environment:**
 
SAS Token was valid at the time of running this.

My SAS generation settings:
![image](https://user-images.githubusercontent.com/63367896/80055453-88ba4d00-84d6-11ea-9a19-bfd535d206f0.png)

- Microsoft.Azure.Storage.Common, Version=11.1.3.0
-  Microsoft.Azure.Management.Storage, Version=15.1.0
-  Microsoft.Azure.Storage.File, Version= 11.1.3

 - Hosting OS : Windows 
 -  .NET runtime version 4.7.2
 -  IDE and version :  Visual Studio 2017

**Comment by amishra-dev** [comment]
This was resolved over email a few days back, please let me know if you need further assistance.
Here is the link https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.Shares/samples/Sample02_Auth.cs#L98

**Comment by amishra-dev** [comment]
Please reactivate if this is still open.
