### ISSUE TITLE
[QUERY] Stack trace logging

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-net#11511]
**Query/Question**

As per the [logging](https://github.com/Azure/azure-sdk/blob/master/docs/general/implementation.md#logging) design guideline, logging of stack trace should be done only for  specific log levels, verbose as per general guideline but languages may have different name for this level.

Opening this issue as a question to confirm that we're not logging sensitive stack trace unless user requested it by setting appropriate level.

**Comment by pakrym** [comment]
We are not logging stack trace explicitly in .NET at any level. EventSource has it's own infrastructure to provide stack trace information to consumers that require it.

**Comment by anuchandy** [comment]
Thanks, @pakrym so SDK don't deal with it, but delegate to EventSource and ES take care of /controls any security aspect of trace, I assume that's the idiomatic model in the .NET world. Feel free to close this if there is no further action needed in the SDK side.
