### ISSUE TITLE
[BUG] "Operation decrypt is not permitted on this key" using the new SDK

### ISSUE THREAD

**Issue by clairernovotny** [Azure/azure-sdk-for-net#11518]
**Describe the bug**
In the new Key Vault SDK, I'm getting a "Operation decrypt is not permitted on this key." error when I call Decrypt on a certificate in key vault using a Service Principal. The same service principal using the older SDK works and can perform the decrypt operation.

**Expected behavior**
What is the expected behavior?
Decrypt should work.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
```
   System.Security.Cryptography.CryptographicException : Error calling Key Vault
    ---- Azure.RequestFailedException : Service request failed.
    Status: 403 (Forbidden)
    
    Content:
    {"error":{"code":"Forbidden","message":"Operation decrypt is not permitted on this key.","innererror":{"code":"KeyOperationForbidden"}}}
    
    Headers:
    Pragma: no-cache
    x-ms-keyvault-region: REDACTED
    x-ms-request-id: REDACTED
    x-ms-keyvault-service-version: REDACTED
    x-ms-keyvault-network-info: REDACTED
    Strict-Transport-Security: REDACTED
    X-Content-Type-Options: REDACTED
    Cache-Control: no-cache
    Date: Wed, 22 Apr 2020 23:24:37 GMT
    Server: Microsoft-IIS/10.0
    X-AspNet-Version: REDACTED
    X-Powered-By: REDACTED
    Content-Length: 136
    Content-Type: application/json; charset=utf-8
    Expires: -1
    
  Stack Trace: 
    RSAKeyVault.Decrypt(Byte[] data, RSAEncryptionPadding padding) line 91
    <ShouldRoundTripEncryptAndDecryptWithCertificate>d__8.MoveNext() line 126
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    ----- Inner Stack Trace -----
    KeyVaultPipeline.SendRequest(Request request, CancellationToken cancellationToken)
    KeyVaultPipeline.SendRequest[TContent,TResult](RequestMethod method, TContent content, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
    RemoteCryptographyClient.Decrypt(EncryptionAlgorithm algorithm, Byte[] ciphertext, CancellationToken cancellationToken)
    CryptographyClient.Decrypt(EncryptionAlgorithm algorithm, Byte[] ciphertext, CancellationToken cancellationToken)
    KeyVaultContext.DecryptData(Byte[] cipherText, RSAEncryptionPadding padding) line 84
    RSAKeyVault.Decrypt(Byte[] data, RSAEncryptionPadding padding) line 87
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

clone `https://github.com/novotnyllc/RSAKeyVaultProvider`
checkout the `update-to-latest-sdk`

You should be able to repro by dropping a file called `azure-creds.json` in the test project private directory with the following

```json
{
  "clientId": "",
  "clientSecret": "",
  "tenantId": "" ,
  "azureKeyVaultUrl": "https://<insert vault name>.vault.azure.net/",
  "azureKeyVaultCertificateName": "TestCert",
  "azureKeyVaultKeyName": "TestKey"
}
```

You should have a certificate named TestCert and a key called TestKey. The service principal should have Decrypt,Sign permissions on the keys and Get on the certificate.

Run the unit tests.

If you switch to `master` and run the same tests, it'll work.

**Environment:**
 - Azure.Security.KeyVault.Keys 4.0.3
 - 5.0.0-preview.2.20160.6 
 - IDE and version : VS 16.7 Int Preview latest

**Comment by clairernovotny** [comment]
Found the issue - in the tests, it was using a key-only in master and a certificate and key in the branch.

**Comment by heaths** [comment]
To note, by default keys created with certifications only have Key Encipherment and Digital Signature usage flags. You can add Data Encipherment to add encrypt and decrypt permissions to the managed key.
