### ISSUE TITLE
[Documentation] Move aka.ms links to new azsdk scheme

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11516]
Guidance provided by @jongio in internal [Teams post](https://teams.microsoft.com/l/message/19:f6d52ac6465c40ea80dc86b8be3825aa@thread.skype/1587665449274?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1575426306557&teamName=Azure%20SDK&channelName=General&createdTime=1587665449274)

These will be updated to the pattern: "azsdk/{lang}/docs/ref/{service}"

**Comment by annelo-msft** [comment]
@kristapratico, @jeremymeng, @samvaity

**Comment by jeremymeng** [comment]
I suppose this would be for all our libraries, not just cognitive service ones.
