### ISSUE TITLE
[Test] Provide Model Factory per .NET Mocking Guidelines

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11529]
https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking

✅ DO provide factory or builder for constructing model graphs returned from virtual service methods.

Model types shouldn’t have public constructors. Instances of the model are typically returned from the client library, and are not constructed by the consumer of the library. Mock implementations need to create instances of model types. Implement a static class called <service>ModelFactory in the same namespace as the model types.

**Comment by maririos** [comment]
FYI https://github.com/Azure/azure-sdk-for-net/pull/12626
