### ISSUE TITLE
Remove protected constructors from LROs

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11528]
Guidelines are unclear regarding whether protected constructors are required for non-client types like subclasses of Operation<T>: https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking

Confirm that this guideline refers only to client classes, and if so, remove them from LROs:

✅ DO provide protected parameterless constructor for mocking.

**Comment by kinelski** [comment]
We decided on removing the protected constructors for Preview 3. Opened #12401 to keep track of the issue.
