### ISSUE TITLE
Emphasize that a ServiceBusSender can be used to send to both session and non-session entities

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11553]
In UX studies, when users were asked to send session messages, they would often be drawn to the CreateSessionProcessor method since this has Session in the name, and it isn't obvious what a Processor would do. We can alleviate this somewhat by making it clear in the ServiceBusSender docs that it can be used for session entities. We can also try to emphasize in the Processor docs that this is used for receiving messages, not sending messages, and mention that it uses ServiceBusReceivers or ServiceBusSessionReceivers (for ServiceBusSessionProcessor) under the hood.

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/11592
