### ISSUE TITLE
[Design Discussion] Should the Event Processor Client Support Creating Checkpoints for Arbitrary Events?

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#11566]
# Summary

The current design of the `EventProcessorClient` invokes an event handler to process data read from the Event Hubs service.  Part of the arguments associated with that event handler is a method for creating/updating a checkpoint based on the `EventData` instance associated with the event arguments.  This method takes no parameters and relies on the implicit context when called.   It us not able to be used to manipulate checkpoint data for events other than the one associated with the arguments.

At present, no other means of creating/updating a checkpoint are surfaced as part of the `EventProcessorClient` API.  This provides some difficulty for scenarios in which applications would prefer to create a checkpoint "after every XX number of events or YY amount of time has passed", which is not an uncommon use case.

# Scope of Discussion

- Should the `EventProcessorClient` support a method to create/update checkpoints based on an arbitrary event?

- Would such a method be more usable if it accepted the required data as individual arguments, an or an [`EventProcessorCheckpoint`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessorCheckpoint.cs) and offset value, or an [`EventProcessorCheckpoint`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessorCheckpoint.cs) and  [`EventData`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/EventData.cs) instance?

- Is there another potential design for enabling the scenario that should be considered?

# Out of Scope

- General changes to the `EventProcessorClient` unrelated to the theme of creating/updating checkpoints.

# Concept Illustration

```csharp
public class EventProcessorClient
{
    // This form assumes the context for the Event Hub and consumer group are sourced from the
    // EventProcessorClient and not provided individually.

    public async Task<EventHubCheckpoint> UpdateCheckpointAsync(
          string partitionId,
          long offset,
          CancellationToken cancellationToken = default);
}
```

```csharp
var storageClient = new BlobContainerClient(<< ARGS >>);
var processor = new EventProcessorClient(storageClient, "<< CONSUMER GROUP >>", "<< CONNECTION STRING >>");

// Create a checkpoint for partition "0" using offset 12345
await processor.UpdateCheckpoint("0", 12345);
```

# Considerations

- The current model requires that the arguments passed to the event handler be cached for the event/partition combination that a checkpoint would be desired for.   This is often something that is set on each invocation of the event handler.   When the threshold for checkpointing is reached the cached arguments are referenced and the method is called.

- The proposed concept would not remove the burden of having to track and cache information; it would, however, reduce the set of information being tracked to just the partition identifier and the offset of the desired event.

**Comment by INNVTV** [comment]
In your proposed solution above. How would I get the offsets? Would the burden be on the developer to track this? Why not store the array of partitions and the current offsets of each within the processor so that I can make a call based on latest offset for each partition.

```
foreach(var parition in processor.Partitions)
{
     await processor.UpdateCheckpoints(partition.Id, partition.currentOffsett)
}
```

Even better would be a single call that runs through the array of partitions and checkpoints on the latest offset for each under the hood in one fell swoop:

`await processor.UpdateAllCheckpoints()`

**Comment by jsquire** [comment]
> In your proposed solution above. How would I get the offsets? Would the burden be on the developer to track this? Why not store the array of partitions and the current offsets of each within the processor so that I can make a call based on latest offset for each partition.

That's an interesting thought.  That would also give us a query point to answer the question "what partitions are owned by the processor?"    I wonder if we would want to track the event or just the offset.   Something like:

```csharp
public class EventProcessorClient
{
    public EventProcessorClientPartition OwnedPartitions  { get; }
}
```

```csharp

// As suggested
public class EventProcesorClientPartition
{
    public string PartitionId { get; }
    public long LastProcessedEventOffset { get; }
}

// Alternative thought
public class EventProcesorClientPartition
{
    public string PartitionId { get; }
    public EventData LastProcessedEvent { get; }
}
```

**Comment by INNVTV** [comment]
Both are nice options. Does EventData store offset? I don't see it in the current library. Maybe something like this:

```
public class EventProcesorClientPartition
{
    public string PartitionId { get; }
    public long LastProcessedEventOffset { get; }
    public EventData LastProcessedEvent { get; }
}
```
Still thinking this would be a nice addition:

`await processor.UpdateCheckpoints()`

...Or on client options:

`var clientOptions = new EventProcessorClientOptions { CheckpointFrequency= TimeSpan.FromMinutes(5) };`

**Comment by INNVTV** [comment]
EventProcessorClientOptions.CheckpointFrequency would also ensure that developers don't/can't overdo the check pointing

**Comment by jsquire** [comment]
> Even better would be a single call that runs through the array of partitions and checkpoints on the latest offset for each under the hood in one fell swoop:
> 
> `await processor.UpdateCheckpoints()`

To me, this feels a bit too implicit to be intuitive.  The strong association between the partition context and updating a checkpoint has the intention of keeping the concept of a checkpoint and the event that it represents local to one another.  I'm not sure that I see enough value in the convenience of calling this method rather than writing a loop that would justify the added complexity and potential confusion for those new to the library.

> 
> Note the use of plural to differentiate from the per partition call. You would also have to document the fact that this should be called as part of a delay wrapped around the event processing so it does not overwhelm the checkpoint mechanism. Or perhaps another option would be to have a property on client options:
> 
> `var clientOptions = new EventProcessorClientOptions { CheckpointFrequency= TimeSpan.FromMinutes(5) };`
> 
> And with that the check pointing is managed for you.

That would certainly cover the use case that you were describing well.  The downside there is that it is pretty specific to one checkpointing strategy that doesn't really offer the ability to extend with additional criteria for other scenarios.  It also adds another mechanic that isn't overly friendly to the "Hello World" cases, making the barrier of entry to using the library a bit higher.  

Checkpointing is a strange balance for managing your tolerance for reprocessing things that you've seen if you crash and "lose checkpoint data" versus not writing a checkpoint to avoid the potential performance cost and keep a higher throughput.  There are quite a few different strategies and techniques that I've come across in real-world use.  

We would strongly need to consider how wide spread the timing-based checkpointing approach is across the developers using the library.  Anecdotally, it comes up occasionally, usually in a strange corner case of a more advanced workload where the timing component is part of the decision rather than the primary criteria.  The majority that I've come across have been based on using some number of events processed as a threshold; the cost of reprocessing a set of events often is cheap enough that it doesn't warrant the trade-off for a more complex strategy.   

Once we get into that territory, I wonder if moving to a custom processor built on `EventProcessor<TPartition>` would be a more natural fit.  Being closer to the metal and having more control over the flow without having to fight the API surface should make it easier to write and plug in a checkpoint manager that meets the specific application needs.

I'm certainly open to the idea, but I can see getting quite a lot of friction from our architecture board without a solid justification demonstrating a wide need across different customer segments.

**Comment by jsquire** [comment]
> Both are nice options. Does EventData store offset? I don't see it in the current library. 

Yup, its [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/EventData.cs#L107) and guaranteed to be set for an event read from the service.

**Comment by INNVTV** [comment]
> Yup, its here and guaranteed to be set for an event read from the service.

Nice. Thank you. This is slightly off topic and may justify a new discussion: Is there an option (or one in the pipeline) to allows for a check pointing mechanism outside of Azure Blobs? For example a scenario where I only want a dependency on Azure for EventHubs but not for Storage. If I have processors running on prem and will be check pointing offsets to a local text file for example?

**Comment by ellismg** [comment]
> This is slightly off topic and may justify a new discussion: Is there an option (or one in the pipeline) that allows for a check pointing mechanism outside of Azure Blobs? For example a scenario where I only want a dependency on Azure for EventHubs but not for Storage. If I have processors running on prem and will be check pointing offsets to a local text file for example?

We do have `EventProcessor<T>`, which we've released in preview, which allows you to control checkpointing/what partitions are assigned to which processors).  You can see the [design document](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/design/event-processor%7BT%7D-proposal.md) or [the implementation](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor%7BTPartition%7D.cs).  Note this is in the `Azure.Messaging.EventHubs` library, not `Azure.Messaging.EventHubs.Processor`.

The current `EventProcessorClient` has been rebuilt atop this platform, so that may guide you in building you own.

Do you think that would fit your needs, @INNVTV?

**Comment by jsquire** [comment]
> Nice. Thank you. This is slightly off topic and may justify a new discussion: Is there an option (or one in the pipeline) that allows for a check pointing mechanism outside of Azure Blobs? For example a scenario where I only want a dependency on Azure for EventHubs but not for Storage. If I have processors running on prem and will be check pointing offsets to a local text file for example?

Matt beat me to it, but I echo his recommendation.  The `EventProcessor<TPartition>` fills a similar role as the `EventProcessorClient`, with cooperative load balancing and resiliency as its core features but offering native batch processing, extension points for using different storage providers, and with a less opinionated API.   The caveat is that this comes in the form of an abstract base, which needs to be extended and the core “handler” activities implemented via override.  More on the design and philosophy behind this can be found [[here]](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/design/event-processor%7BT%7D-proposal.md).

Generally speaking, `EventProcessorClient` was designed to provide a familiar API to that of the `EventHubConsumerClient` and offer an intuitive "step-up" experience for developers exploring Event Hubs as they move towards production scenarios.   For a large portion of our library users, that covers their needs well.   There's definitely a point, however, where your application requires more control to handle higher throughput or specialized needs that aren't shared by a large group - that's where the `EventProcessor<TPartition>` is intended to help.

**Comment by INNVTV** [comment]
Thanks @jsquire and @ellismg - I'll look into the `EventProcessor<TPartition>` preview and see if it gives me that added control I was looking for!

**Comment by jsquire** [comment]
Closing this issue out, as discussion seems to have stalled.   In the short term, we won't be planning to make this change, but are open to considering it if the community finds a need.
