### ISSUE TITLE
FieldBuilder.BuildForType<T>() is returning a fixed size collection

### ISSUE THREAD

**Issue by mhintzke** [Azure/azure-sdk-for-net#11584]
The [changes made here](https://github.com/Azure/azure-sdk-for-net/pull/6833/files) 9 month ago introduced a change whereby the collection of `Field` objects used to be an actual `List<Field>` that was returned and projected as an `IList<Field>` to what is now an Array.

The line below shows that `.ToArray()` was used when returning the collection of `Field` objects which doesn't allow modifying the data structure at runtime.  We use dynamic properties on our Index schema so that when we call `.Add(field)` our runtime fails with a `NotSupportedException: Collection was of a fixed size`

https://github.com/Azure/azure-sdk-for-net/blob/310292aefae646c4eb36c8a14c1b39e47420aad5/sdk/search/Microsoft.Azure.Search.Service/src/Customizations/Indexes/FieldBuilder/FieldBuilder.cs#L239

I believe simply changing `ToArray()` to `ToList()` would solve this problem. Going to follow up with a PR.

**Comment by mhintzke** [comment]
Fixed this in PR #11585

**Comment by brjohnstmsft** [comment]
FYI @heaths  -- Per this feedback, we should ensure that the list returned by `SearchFieldBuilder` should be mutable. Assigning this issue to you. The aforementioned PR is for the Track 1 SDK, which we are no longer releasing.

**Comment by heaths** [comment]
Sounds reasonable. Tracked as part of #11166
