### ISSUE TITLE
Decide whether we should make all Create* methods async

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11589]
Currently, only the CreateSessionReceiverAsync method is async. This is async as we establish the session link in this method. Without establishing this session link, we are not able to establish a session lock up front, leaving several properties of the receiver in an uninitalized state. If we established the link lazily (by doing it on first service operation) we might be unable to actually lock the session that is requested (in case of a named session being passed). In the case of no session being passed, we would be spreading the blast radius of TimeoutExceptions that could arise due to the queue not having any messages to all service operations. 
This is discussed in https://github.com/Azure/azure-sdk-for-js/issues/8299

It is also mentioned in https://github.com/Azure/azure-sdk-for-net/issues/10821

The decision that was reached in the JS issue was to make all of the create methods async. 
Not only does this make things consistent, it also adds a few benefits such as surfacing link creation errors up front, and avoiding adding extra performance cost of sending/receiving for the first time.

There are a couple downsides with this approach for .NET:
- unable to inject the sender/receiver without using sync over async in ASP.NET (currently this is limited to session receiver)
- the ServiceBusProcessor is an abstraction around a set of receivers that allows using an event based model for processing received messages. We don't actually establish any receiver links until processor.StartProcessingAsync() is called. As such, there isn't really much async work we would want to do when constructing a Processor. One idea mentioned by @richardpark-msft was that we could at least open the connection without actually establishing any links.

**Comment by SeanFeldman** [comment]
@JoshLove-msft  `CreateSessionReceiverAsync` is not the only async method from the Create family. There's also `CreateBatchAsync`. Both are async for the reason elaborated above - a link to the broker is required. Contrasted with JS SDK user request, did you see the same request from the .NET SDK users?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft `CreateSessionReceiverAsync` is not the only async method from the Create family. There's also `CreateBatchAsync`. Both are async for the reason elaborated above - a link to the broker is required. Contrasted with JS SDK user request, did you see the same request from the .NET SDK users?

We were limiting the Create family to methods on the ServiceBusClient, but it is a good point about CreateBatchAsync. No we haven't heard any requests from users yet. We are trying to determine whether this inconsistency will throw users off.

**Comment by SeanFeldman** [comment]
I can provide feedback on how we use the client and we have a mixed usage, creating clients in constructors/non-async paths as well as on async paths. Personally, I would not want to see a method sufficed `Async` if it's not async in its nature. 

As for the drawback of the initial performance hit on the first usage of the clients - it depends. For systems where continuous message processing is taking place that has no significant impact. For reactive applications, that's a different scenario. But even then, there's a cold startup that is usually dealt with a prewarmed instance or a premium tier that has an instance running 24/7.

**Comment by JoshLove-msft** [comment]
Thanks for the feedback. I am inclined to agree that we shouldn't attempt to coerce what should be a sync method into async just for the sake of consistency.

**Comment by danielmarbach** [comment]
What if you look at it from the perspective of the evolvability? From an async method implementation perspective it is totally valid to be purely sync while for a sync version you can't really call async stuff underneath without getting into huge troubles. So under that light I can see how you take a stance at aligning the creation methods to be async and then for the currently sync implemente ones return `Task.CompletedTask`. If you do that in case you need to initialize IO bound resources in later releases of the client you can actually evolve those methods without doing breaking changes.

For me the primary argument here should not necessarily be consistency across creation methods but the question whether the creation method ever needs to be IO bound or could/should be IO bound in the near future. If that is the case it should return `Task` or `ValueTask`.

**Comment by JoshLove-msft** [comment]
I'm not sure how likely it is that something would change to force our hand so that we can't give you back a receiver/sender without doing some IO operation. I would think this could happen if new features from the service necessitated it. @nemakam thoughts?

**Comment by JoshLove-msft** [comment]
We discussed with @nemakam offline and he was in agreement with the approach of leaving everything that can be sync as sync. This opens up DI for those types. The only type that would have async creation is the ServiceBusSessionReceiver. This seems like it would be less commonly used in DI anyway as it will only ever be scoped to a single session anyway, so it would seem more like something that would need to be created dynamically (of course, there would be cases where it might be useful when dealing with known named sessions).
