### ISSUE TITLE
armClient.Resources.CreateOrUpdate() throws NullReferenceException

### ISSUE THREAD

**Issue by grant-d** [Azure/azure-sdk-for-net#1159]
The call below actually succeeds (it creates the DB) but throws a CloudException in Hyak.
Using Hyak 1.02

System.NullReferenceException occurred
Message: Exception thrown: 'System.NullReferenceException' in Hyak.Common.dll
Additional information: Object reference not set to an instance of an object.

Here's the error message from the CloudException:
{"operation":"CREATE DATABASE","startTime":"\/Date(1434138694311)\/"}

The stack trace shows a call to .ParseJson() or similar.

Here's the repro:

           var armClient = new ResourceManagementClient(azureCreds);

            var id = new ResourceIdentity()
            {
                ResourceProviderApiVersion = armClient.ApiVersion,
                ResourceProviderNamespace = "Microsoft.Sql",
                ResourceName = "<database name>",
                ResourceType = "databases",
                ParentResourcePath = $"servers/<server name>"
            };

            var prp = new
            {
                edition = "Standard",
                collation = this.Collation,
                maxSizeBytes = ((long)10 * 1024 * 1024 * 1024).ToString(), // Numeric literals result in BadRequest
                requestedServiceObjectiveId = "<ServiceObjectiveId>"
            };
            var json = JsonConvert.SerializeObject(prp, Formatting.Indented);

            var rsc = new GenericResource(this.Location)
            {
                Properties = json
            };

            // Throws here, but actually succeeds on the Azure side
            var rsp = armClient.Resources.CreateOrUpdate(this.ResourceGroupName, id, rsc);

**Comment by grant-d** [comment]
I just found the same behavior when trying to resize an existing database. When making a similar call to above, but this time using a different 'maxSizeBytes' value, the call fails client-side with the following, even though it succeeds on Azure.

{"operation":"AlterDatabaseOperation","startTime":"\/Date(1435174974927+0000)\/"}

**Comment by stankovski** [comment]
@akromm please review

**Comment by akromm** [comment]
@stankovski This is because the API we have is Async and returns 202 ACCEPTED with a location header set.  If I remember correctly we had a bug previously in our client where Null ref would get thrown but that was fixed in our specs.  Does the generic resource APIs handle the 202 async pattern?

**Comment by ravbhatnagar** [comment]
Please let us know if this is still an issue.
