### ISSUE TITLE
Search: Rename/customize IndexBatch rather than completely rewrite it

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#11593]
With the [recent changes](https://github.com/Azure/azure-sdk-for-net/pull/11562) I've made to add the Accept header, they did not affect the batch operations because it created an `HttpMessage` outside the generated operations, i.e. it duplicated code to which the generator was not privy.

Rather than do that and for long-term maintainability, we should see if we can rename and customize the existing `IndexBatch` class which has the same structure. The code generation is much more robust than it was when these classes were written and should allow us to just call the `DocumentRestClient.CreateIndexRequest` method directory, which returns the `HttpMessage` in the same way that was duplicated, sans the missing "Accept" header and the different-but-similar model.

**Comment by tg-msft** [comment]
Unfortunately this still doesn't work.  We need to have an async code path for serialization via ObjectSerializer and it would require hacks that copied to an intermediate buffer to get this working with the generated method.
