### ISSUE TITLE
[FEATURE REQ] BlobClient is not possible to be mocked

### ISSUE THREAD

**Issue by bartoszropski** [Azure/azure-sdk-for-net#11614]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
Guys in era where ASP.Net Core ships testing packages with in memory server, where you can run and validate your service in memory, where unit and integration testing has been commonly adopted principles of high product quality, I was hoping new Azure.Core SDKs would be bringing the best patterns developers should follow.
Few hours with BlobClient proved that for the newest SDK, to work with blobs, I need a wrapper, with contract changes, to be able to mock this functionality in my tests.
I haven't seen abstract class not interface BlobClient extends/implements, but virtual methods brought my hope back shortly, which was then crushed by the fact that publicly exposed return value contract class BlobDownloadInfo has no public constructor and there is no way how I can mock DownloadAsync call, to simulate a response from Azure.

I'd appreciate some work on that, please. Having a need to create facade for the library shipped in 2020, not some old code from the past, feels just horrible

**Comment by bartoszropski** [comment]
I found https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobsmodelfactory.blobdownloadinfo?view=azure-dotnet

**Comment by jchannon** [comment]
How does BlobDownloadInfo translate to BlobClient?
