### ISSUE TITLE
Is Microsoft Avro a general purpose Avro library?

### ISSUE THREAD

**Issue by karldodd** [Azure/azure-sdk-for-net#1163]
Hi,

We are evaluating C# Avro libraries in order to serialize .net objects into avro format. Is Microsoft Avro library designed to be an Azure-Only/HDInsight-only? Or is it a general purpose lib for any Hadoop compatible systems? Thanks.

Btw, we can find little documentations about the lib except this one: https://azure.microsoft.com/en-gb/documentation/articles/hdinsight-dotnet-avro-serialization/ . But important things like release notes and roadmaps are missing.

Kind regards,
Karl

**Comment by matt-gibbs** [comment]
The codeplex site has additional documentation https://hadoopsdk.codeplex.com/wikipage?title=Avro%20Library
It is an implementation of the Apache avro definition. It does not include RPC support. 
The codeplex site is probably the better place to post specific questions or report issues.

**Comment by riccardone** [comment]
Can you please point me to the latest source code Microsoft.Hadoop.Avro version="1.5.6"?
