### ISSUE TITLE
Avoid rethrowing exception with throw ex syntax when exception unchanged

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11639]
In our RetryPolicy exception handling, and other exception handling in AmqpSender/AmqpReceiver, we attempt to translate the exception that was thrown using AmqpExceptionHelper.TranslateException. If the exception we are translating is not in the our list of expected exceptions, we don't end up doing anything to it, but we return it as is to the caller. In such cases, we should rethrow the exception using `throw` instead of `throw ex`, in order to retain the stack trace of the exception. I wouldn't expect anything coming back from the AMQP layer to fall into this category, but bugs in the client code could trigger this scenario and using the correct throw syntax will make it easier to find the bug.

**Comment by danielmarbach** [comment]
To me it looks like the code is written under the assumption that the translation helper always returns an specific translated exception, an aggregate exception or the actual exception in case it wasn't translated. The upper layers rely on that so maybe it is best to leave the translation helper as is but then introduce something like

```
                            if (activeEx.Equals(ex))
                            {
                                throw;
                            }
                            throw activeEx;
```

at the call site?

**Comment by danielmarbach** [comment]
It seems that we have to usages:

```
throw AmqpExceptionHelper.TranslateException
```

and

```
Exception exception = AmqpExceptionHelper.TranslateException();
// do something with it but do not rethrow
```

and

```
Exception exception = AmqpExceptionHelper.TranslateException();
// do something with it in some cases and in other cases rethrow
```

**Comment by JoshLove-msft** [comment]
I like the TranslateOrRethrow idea. This should be the simplest way to do what we want without needing to modify all of the call sites.

**Comment by danielmarbach** [comment]
@JoshLove-msft I sent in a draft PR for this, https://github.com/Azure/azure-sdk-for-net/pull/11679

I realized the only true way to achieve this is by actually switching everything to `ExceptionDispatchInfo`. The ugly part is the non-reachable `throw` statement to make the compiler happy.
