### ISSUE TITLE
Investigate enabling request body matching in CertificateTests

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#11634]
Currently there is a part of request that changes every time:
```
System.InvalidOperationException : Unable to find a record for the request POST https://heathskv.vault.azure.net/certificates//1442592363/import?api-version=7.1-preview
Header differences:
Body differences:
Request and response bodies do not match at index 141:
     request: "gQInrFyDDX+drkCAggAgIIECDizLZe"
     record:  "gQInrFyDDX\u002BdrkCAggAgIIECD"
```

**Comment by pakrym** [comment]
cc @heaths

**Comment by heaths** [comment]
At first glance of the [PR](https://github.com/Azure/azure-sdk-for-net/pull/11624), we'll need to ignore certain content which means understanding structure. I wonder if that's something we could instead put into the base matcher as optional behavior. It will probably be common enough.

**Comment by heaths** [comment]
I don't believe the pay-off here is worth the cost. This has been open a while and the live tests have been run many times since then. If you disagree on the resolution, we can discuss and re-evaluate.
