### ISSUE TITLE
Change from static factory method to constructor for copying received message

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11633]
Currently we have the ServiceBusMessage.CreateFrom method that can be used to create a new sendable message from a ServiceBusReceivedMessage. From our UX studies, we found that no users were able to discover this on their own. Most looked for a constructor, and then a few also looked for methods on the received message instance. We should consider using a constructor instead for discoverability.
This is also discussed in https://github.com/Azure/azure-sdk-for-net/issues/10829.

**Comment by danielmarbach** [comment]
I gave this a stab. See https://github.com/Azure/azure-sdk-for-net/pull/11641
