### ISSUE TITLE
Hostname check in KeyVaultClient for AppAuthentication does not scale

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#11646]
The hostname check below does not scale as new Azure regions are created:

https://github.com/Azure/azure-sdk-for-net/blob/f5afa9aa8840f2a14ef47a9dbfe569247d3ffa93/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/Clients/KeyVault/KeyVaultClient.cs#L131-L132

The check shouldn't be necessary as long as HTTPS is enforced, for which the .NET HttpClient will correctly validate. A customer is getting an exception in a new region not supported.

At the same time, I encourage you to take a look at using our new `SecretClient` in the Azure.Security.KeyVault.Secrets package, with source in this same repo at sdk/keyvault/Azure.Security.KeyVault.Secrets. These new packages are where we're focusing attention and provide more flexible and performant authentication, pipelining, and logging.

/cc @nonik0

**Comment by yungezz** [comment]
hi @xccc-msft could you pls have a look? thanks

**Comment by xccc-msft** [comment]
@yungezz This is not the dependency used in our library.

**Comment by nonik0** [comment]
@heaths Thanks for point this out--I am not so sure about removing the hostname check. Currently reviewing the security implications and options and can update this thread soon.

**Comment by allenjzhang** [comment]
@heaths, we are working on track 2 SDK. Track 1 large scale changes will be limited to security fixes.
