### ISSUE TITLE
[FEATURE REQ] - Azure Keyvault AddAzureKeyVault.ReloadInterval needs to raise an Event

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/azure-sdk-for-net#11671]
**Library or service name.**
Microsoft.Extensions.Configuration.AzureKeyVault
 
**Is your feature request related to a problem? Please describe.**
Recently the ReloadInterval property was added which is great, but it doesn't go far enough because we have no way of knowing that it occured and respond and update the strongly bound configuration singletons etc in our DI.

What feature would you like to get added? What problem is it solving?

Please add an event to the AddAzureKeyVault method that allows us to specify a function/lambda that can reload these singletons as a result of a reload from Azure.

**Comment by pakrym** [comment]
Secret configuration provider already fires configuration system reload token: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationProvider.cs#L141

You can use https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfiguration.getreloadtoken?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Configuration_IConfiguration_GetReloadToken to retrieve the reload token. 

An article about using change tokens https://docs.microsoft.com/en-us/aspnet/core/fundamentals/change-tokens?view=aspnetcore-3.1

**Comment by JohnGalt1717** [comment]
Thanks. Bizzarely complex, but it works! Thanks!

**Comment by JohnGalt1717** [comment]
Here's my complete implementation:

```
		public static void ApplyKeyVaultToConfig(IConfigurationBuilder config)
		{
			var builtConfig = config.Build();
			var connectionStrings = ConnectionStrings.GetSettings(builtConfig);
			if (connectionStrings.AzureKeyVault == null)
				return;


			var client = connectionStrings.AzureKeyVault.GetSecretClient();

			var options = new AzureKeyVaultConfigurationOptions
			{
				ReloadInterval = TimeSpan.FromMinutes(5),
			};

			//HACK: This is here until microsoft gives us a better way to make sure that Azure Keyvault doesn't override environment variables etc.
			var tKeyVaultSource = options.GetType().Assembly.GetType("Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationSource")!;

			var source = Activator.CreateInstance(tKeyVaultSource, new object[] { client, options }) as IConfigurationSource;

			config.Sources.Insert(0, source);
		}

```

ReloadInterval =  is the key to it just doing it automatically from what I can tell. In the past I had to do WAY more work to get it to reload using the old library.

**Comment by ezgambac** [comment]
Why are these needed?

var tKeyVaultSource = options.GetType().Assembly.GetType("Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationSource")!;

var source = Activator.CreateInstance(tKeyVaultSource, new object[] { client, options }) as IConfigurationSource;

config.Sources.Insert(0, source);

**Comment by JohnGalt1717** [comment]
That puts Azure Keyvault first instead of last in the order of configuration providers because literally everything else should come after it for overriding your keyvault.  If you don't do this, then command line, environment variables and even .config files will be ignored.

Typically you'll want to have specific settings in environment variables in docker as an example that override certain values per environment.

**Comment by ezgambac** [comment]
Thanks @JohnGalt1717 !
