### ISSUE TITLE
[Test] [FormRecognizer] Tests: sanitize request body and enable body matching

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#11680]
When calling `StartTraining` in `FormRecognizerTrainingClient`, the Blob Container SAS URL is passed to the service in the HTTP request body. For this reason, we're skipping body recording in lots of tests:
https://github.com/Azure/azure-sdk-for-net/blob/babee31b3151e4512ac5a77a55c426c136335fbb/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormTrainingClient/FormTrainingClientLiveTests.cs#L62-L66

In order to improve validation in our tests, once we sanitize the request body, removing only the SAS URL, we should enable body matching as well:
https://github.com/Azure/azure-sdk-for-net/blob/babee31b3151e4512ac5a77a55c426c136335fbb/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/Infrastructure/FormRecognizerRecordMatcher.cs#L10-L19

**Comment by maririos** [comment]
@kinelski could you provide more information about what from the request body we will need to sanitize?

**Comment by kinelski** [comment]
@maririos I have updated the description. Left it empty because I intended to work on that ASAP, but other work took precedence.

**Comment by maririos** [comment]
ohh cool thank you!
`JsonPathSanitizers` should help us here. https://github.com/Azure/azure-sdk-for-net/blob/master/doc/dev/Track2TestFramework.md#sanitizing

Let me know if you have questions or if I can help with it
