### ISSUE TITLE
[Design] Consider naming of ContentType enum

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11686]
There are a few goals:

- Consistency across languages (or understand why we diverge)
- Does a ContentType type go in Azure.Core? (.NET doesn't currently have one)
- Should FR library use a ContentType from Azure.Core, even though FR only supports a subset of possible HTTP content types, or does it make sense to have an extensible enum/enum to enumerate just the content types that FR supports.

Notes:

ContentType enum - is there overlap with ContentType in other libraries?

Python, Java have FormContentType. 
In Python can also pass in a ContentType string 

.NET to follow up with KC re: services taking content type, common master list in Azure.Core?  Use an extensible enum to pass a string but indicate which values are supported by the service?

**Comment by maririos** [comment]
Proposed changes:
- renaming it to FormContentType 
  - Pros:
    - the service only supports certain types so we show the user what they can use
    - Name avoids collision with otherl ibraries  ContentType 
  - Cons:
    - User will need to learn how to manage content-type per library case
- See if this is an opportunity to create a type in Azure.Core that all libraries can use. Doing a quick search I see that KeyVault, AppConfig, Storage, Core, will benefit.
  - Pros: 
    - One unified way across libraries
  - Cons:
    - will need to update previous libraries that already ship 
    - There are going to be types that not all the libraries will use. How to tell the user which ones will work? docs?

**Comment by maririos** [comment]
after internal discussion, decision was to go with renaming to `FormContentType`
