### ISSUE TITLE
[Design] Follow precedent for PageRange in .NET

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11682]
See corresponding issue: https://github.com/Azure/azure-sdk-for-python/issues/11130

In the design differences meeting, we thought that Storage might have set a precedent on PageRange naming and that we should reconsider naming this FormPageRange in FormRecognizer.

Looking at storage, we do have a PageRange model: https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/azure/storage/blob/_models.py#L860
Except this PageRange is talking more about page blobs and byte ranges rather than actual form page ranges. 

Therefore, we will rename this model `FormPageRange`, especially since this name helps avoid type name clash.

**Comment by annelo-msft** [comment]
I had a quick look at this - Storage on .NET also has a PageRange class, with Start.

**Comment by annelo-msft** [comment]
@kristapratico, did we close the decision on this?  Can you share what it was?

**Comment by kristapratico** [comment]
Hey I edited the description of this issue with the decision. We will rename PageRange to FormPageRange.

**Comment by maririos** [comment]
This was already the case in .NET https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormPageRange.cs so closing issue
