### ISSUE TITLE
CreateOrUpdateAsync in Microsoft.Azure.Management.ApiManagement.ApisOperations Deletes Operations when Updating API

### ISSUE THREAD

**Issue by dtessier82** [Azure/azure-sdk-for-net#1169]
Operations associated to an API are deleted when updating via CreateOrUpdateAsync in Microsoft.Azure.Management.ApiManagement.ApisOperations.

**Comment by ailn** [comment]
Hello @dtessier82 . This is a known issue but anyway thanks for reporting it. It's actually not an SDK issue but REST API. I hope the fix will be ready in couple of weeks. As a workaround you can use PatchAsync method.

**Comment by shahabhijeet** [comment]
@dtessier82 please open a new issue if the problem still exists/repros.
