### ISSUE TITLE
[QUERY]  the remote certificate is invalid according to the validation procedure

### ISSUE THREAD

**Issue by vscodewinodws** [Azure/azure-sdk-for-net#11701]
**Query/Question**
How can we help?

i want to pass httpclienthandler to by pass ssl erros on my cent os machine , i am aware this is not correct way to make it run but on my cent os server it has issue or miss configuration by communicating any azure rest api it shows below exception 

**_the remote certificate is invalid according to the validation procedure_**

i am clearly aware that this is ssl certificate issue on the server i have and on other machines i have azure api works fine but i want to by pass ssl check using 

httpClientHandler.ServerCertificateCustomValidationCallback = HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

so i can make it run on the server having issue .

is there any way i can pass httpClientHandler with HttpClientHandler.DangerousAcceptAnyServerCertificateValidator property so all call azure calls will ignore ssl errors ?

**Environment:**
    cent os 7 , .NET core 3.1]
    IDE and version : [e.g. Visual Studio 16.4]

**Comment by jsquire** [comment]
Hi @vscodewinodws.  We're sorry that you're experiencing difficulties and appreciate you reaching out to let us know.  I'm having a bit of trouble understanding your end-to-end scenario - specifically, I'm not sure if you're attempting to invoke a REST endpoint directly or using on of our SDKs.

Would you be so kind as to confirm that you're using one of the Azure client libraries and are looking for a way to them to influence the certificate validation?  Any additional context on which Azure services you're interacting with would also be helpful.

**Comment by pakrym** [comment]
[This example](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy) while talking about proxies shows how to use a custom handler instance.

**Comment by vscodewinodws** [comment]
@pakrym i seen link you share but i am unsure at where we can attach it , for eg i have below code which gets azure object, docs stated that it should be in retry policy so i unsure about it  can you help a bit here ?

Azure.Configure()
                            .WithLogLevel(HttpLoggingDelegatingHandler.Level.BodyAndHeaders)
                            .Authenticate(InitAzureAppCrdentials(clientId, clientSecret, tenantId))
                            .WithSubscription(Subsciption);

**Comment by vscodewinodws** [comment]
@pakrym i found that httpClientHandler client handler is get only property in rest client , i am not using rest client and all available methods does not seems me to allow my httpClientHandler as argument what can ne done here ?

**Comment by pakrym** [comment]
My bad, I presumed you are using another set of client libraries. 

After reading the code at https://github.com/Azure/azure-libraries-for-net I'm not sure how to replace or configure the root HTTP client handler 

cc @weidongxu-microsoft @xccc-msft @ChenTanyi

**Comment by vscodewinodws** [comment]
i am still looking for a way to pass custom httpClientHandler for information only now , since i found that cent os machin had issue with the ssl certificate 

and i resolved using below link if anybody needs in future 

https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md#ssl-certificate-resolution-with-snap-installs

**Comment by allenjzhang** [comment]
@vscodewinodws , Looks like you are using .NET fluent libraries. Can you list the name of the library package you are referring?

**Comment by markcowl** [comment]
HttpClientHandler is unfortunately not settable in the fluent API from p[ublic API.  You can set the default value (which will be used by http client handlers by default) on some platforms using ```ServicePointManager.RemoteCertificateValidationCallback```.

If you use the low-level SDKs, the root handler is generally settable in the client contructors, for example: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/compute/Microsoft.Azure.Management.Compute/src/Generated/ComputeManagementClient.cs#L374

**Comment by vscodewinodws** [comment]
although it was not issue of azure sdk nor .net core (below link says for some linux distro ), i think there should be a way to pass custom http handler as argument as optional argument  ?

https://github.com/dotnet/core/blob/master/Documentation/linux-setup.md#ssl-certificate-resolution-with-snap-installs



closing issue since it was platform dependent thing but i still recommend to pass custom http handler along with dependent object can help many others as well.


thanks.
