### ISSUE TITLE
Consider moving Statistics from TextAnalyticsResult to atomic types

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11717]
If we adopt the current [Warnings proposal](https://apiview.dev/Assemblies/Review/b196a5e53fa2441f92e3b1accefa35e7?diffRevisionId=b1c3d139b81a4763995f3a4e491178fa), we'll be putting document-level warnings on the atomic types, so that they come back in the single-input methods.  Consider moving Statistics to the atomic types as well, so that they'll be accessible from single-input methods as well.  We may decided this doesn't make sense.

**Comment by maririos** [comment]
The problem with adding statistics here, i that for single operations we don't have a way to set `IncludeStatistics= true` as we don't pass `TextAnalyticsRequestOptions` to them for simplicity
