### ISSUE TITLE
[QUERY] Is there a way to add ACL settings for a single Blob?

### ISSUE THREAD

**Issue by escobar5** [Azure/azure-sdk-for-net#11714]
**Query/Question**
I see I can set ACL settings per Container, is there a way to add ACL settings per Blob so I can have private and public Blobs in the same container?

**Comment by amnguye** [comment]
Hi,

Through the REST API there is not a way to add ACLs per blob.
https://docs.microsoft.com/en-us/rest/api/storageservices/operations-on-blobs
