### ISSUE TITLE
[QUERY] How to configure IComputerVisionClient using ASP.NET Core dependency injection

### ISSUE THREAD

**Issue by danielbecroft** [Azure/azure-sdk-for-net#11725]
I'm having trouble trying to wire up the `IComputerVIsionClient`/`ComputerVisionClient` service up through ASP.NET Core in the Dependency injection. Previously, I'd written a wrapper using `HttpClient`, and so was doing:

```c#
services.AddHttpClient<IAzureComputerVIsionClient,AzureComputerVisionClient>(c =>
{
    c.BaseAddress = "";
    c.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", configuration.GetValue<string>("AzureComputerVisionApiKey"));
});
```

I'm switching across to using the default packages now, so I don't have to maintain the HTTP requests and URLs. I don't know how to write up the client in DI.

Do I need to use `.AddHttpClient<,>()`? How do I get the `ApiKeyServiceClientCredentials` in to the service?

**Comment by jsquire** [comment]
//cc: @pakrym

**Comment by pakrym** [comment]
How about the following:

``` C#
services.AddSingleton(provider => {
    var configuration = provider.GetService<IConfiguration>();
    var key = configuration.GetValue<string>("AzureComputerVisionApiKey");
    return new ComputerVisionClient(new ApiKeyServiceClientCredentials(key))
});
```

**Comment by danielbecroft** [comment]
Great thanks @pakrym. That works a treat.
(I'm still getting my heading around the use of passing a method/statement block into a function :-/)
