### ISSUE TITLE
Sql DacOperations.ImportAsync does not include ServiceObjective

### ISSUE THREAD

**Issue by ldemidov** [Azure/azure-sdk-for-net#1172]
The ServiceObjective parameter is not available for the ImportAsync method.  The REST api does support it as written here:
https://msdn.microsoft.com/en-us/library/azure/dn781284.aspx?f=255&MSPPError=-2147217396

Would be easy enough to add it to the ServiceManagement/Sql/SqlManagement/Generated/DacOperations.cs file, but this looks like auto-generated code and I don't know the right process to update it.

Would really appreciate a fix for this since we're using these API's to restore databases pretty often as part of our automated QA process.  Thanks!

**Comment by akromm** [comment]
Issue with loading/using certificates, not with SQL.

**Comment by akromm** [comment]
The [ImportRequestParameters](https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Sql/SqlManagement/Generated/Models/ImportRequestParameters.cs)now has the serviceObjectiveName parameter.
