### ISSUE TITLE
[BUG] msbuild /t:GenerateCode fails when your username has a space in it.

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk-for-net#11745]
Running `msbuild /t:GenerateCode` to generate code for a client library using AutoRest fails on windows when your username has a space in it.  This appears to be related to how `npx` interacts with NPM when the cache directory includes a space in it. By default, the cache directory is `%AppData%\npm-cache` on Windows, so I suspect this will hit anyone who has a space in their username.

When trying to run the target, `npx` will fail, with an `EPERM` error like this:

```
Task "Exec"
  npx autorest@https://github.com/Azure/autorest/releases/download/autorest-3.0.6221/autorest-3.0.6221.tgz --version=3.0.6280 C:\dd\azure\azure-sdk-for-net\sdk\template\Azure.Template\src/autorest.md  --use=https://github.com/Azure/autorest.csharp/releases/download/3.0.0-dev.20200415.7/autorest-csharp-v3-3.0.0-dev.20200415.7.tgz --output-folder=C:\dd\azure\azure-sdk-for-net\sdk\template\Azure.Template\src --title=Azure.Template --namespace=Azure.Template --shared-source-folder=C:\dd\azure\azure-sdk-for-net\eng\../sdk/core/Azure.Core/src/Shared/ --verbose
EXEC : error : EPERM: operation not permitted, mkdir 'C:\Users\Matt' [C:\dd\azure\azure-sdk-for-net\sdk\template\Azure.Template\src\Azure.Template.csproj]
  command not found: autorest
C:\dd\azure\azure-sdk-for-net\eng\CodeGeneration.targets(24,5): error MSB3073: The command "npx autorest@https://github.com/Azure/autorest/releases/download/autorest-3.0.6221/autorest-3.0.6221.tgz --version=3.0.6280 C:\dd\azure\azure-sdk-for-net\sdk\template\Azure.Template\src/autorest.md  --use=https://github.com/Azure/autorest.csharp/releases/download/3.0.0-dev.20200415.7/autorest-csharp-v3-3.0.0-dev.20200415.7.tgz --output-folder=C:\dd\azure\azure-sdk-for-net\sdk\template\Azure.Template\src --title=Azure.Template --namespace=Azure.Template --shared-source-folder=C:\dd\azure\azure-sdk-for-net\eng\../sdk/core/Azure.Core/src/Shared/ --verbose" exited with code 1. [C:\dd\azure\azure-sdk-for-net\sdk\template\Azure.Template\src\Azure.Template.csproj]
Done executing task "Exec" -- FAILED.
```

To work around this issue, you can explicitly set your cache location using `npm`, to include a path that uses the corresponding 8.3 short file name:

```
> npm config set cache "C:\Users\MATTG~1.ELL\AppData\Roaming\npm-cache" --global
```

Alternately, we could change our invocation of the `npx` to set the `NPM_CONFIG_CACHE` environment variable to something like `$(TEMP)/npm-cache` (perhaps scoped to the case where you're on windows and `%AppData%` contains a space?).  It appears that when your username contains a space, `%TEMP%` uses the 8.3 version of your username.

**Comment by pakrym** [comment]
Original issue https://github.com/zkat/npx/issues/100
