### ISSUE TITLE
[BUG] NullReferenceException at Microsoft.Azure.Search.Serialization.SearchContinuationTokenConverter.ReadJson

### ISSUE THREAD

**Issue by CSorel-Catalyte** [Azure/azure-sdk-for-net#11742]
**Describe the bug**
When deserializing `DocumentSearchResult<T>` where ContinuationToken is null, I receive a nullreference exception.

**Expected behavior**
It should handle null continuation tokens without error.

**Actual behavior (include Exception or Stack Trace)**

> Object reference not set to an instance of an object.
>    at Microsoft.Azure.Search.Serialization.SearchContinuationTokenConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
>    at Newtonsoft.Json.Linq.JToken.ToObject[T]()
>    at CommonUtilities.API.SearchApiHelper.<GetResultsForAllBySearchString>d__0.MoveNext() in redacted\SearchApiHelper.cs:line 66

Looking at [https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Microsoft.Azure.Search.Data/src/Customizations/Serialization/SearchContinuationTokenConverter.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Microsoft.Azure.Search.Data/src/Customizations/Serialization/SearchContinuationTokenConverter.cs)

I'm guessing it fails on: Payload payload = serializer.Deserialize<Payload>(reader);

**To Reproduce**

Application consists of 3 components:

- Azure Search Service
- A .NetCore WebAPI calling the search service via the Azure Search SDK and returning a JSON result of type `DocumentSearchResult<SearchIndexerContent>`
- A helper class that deserializes the json and returns it to the caller

The call to the search service works correctly and the api returns a well-formatted json string. The error occurs in the helper when deserializing at: `DocumentSearchResult<SearchIndexerContent> result = JsonConvert.DeserializeObject<DocumentSearchResult<SearchIndexerContent>>(resultStr, jsonSerializerSettings);`

JSON String that fails:

`"{\"continuationToken\":null,\"count\":20,\"coverage\":null,\"facets\":null,\"results\":[{\"document\":{\"id\":\"AP_3266450\",\"slug\":null,\"category\":null,\"sourceSystemId\":\"3266450\",\"author\":\"someone@somewhere.io\",\"jaArea\":null,\"jaContentTag\":\"Tag1\",\"documentSourceSystem\":\"SomeSource1\",\"documentUrl\":\"http://somewhere.somehow/3266450\",\"contentType\":\"Page\",\"description\":\"<html><head><title>Lorem Ipsum</title></head><body><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tempus vel ante non eleifend. Sed lobortis lobortis rutrum. Pellentesque euismod malesuada tincidunt. Aliquam erat v\",\"body\":\"<html><head><title>Lorem Ipsum</title></head><body><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tempus vel ante non eleifend. Sed lobortis lobortis rutrum. Pellentesque euismod malesuada tincidunt. Aliquam erat volutpat. Mauris eu turpis id augue varius pellentesque vitae eget nisl. Curabitur rutrum mattis massa, quis aliquam arcu aliquam eget. Donec tempor nunc ut tortor dignissim placerat. Curabitur mollis nulla quis justo maximus faucibus. Nunc iaculis dolor ac turpis egestas condimentum. Aliquam convallis turpis eu orci aliquet, sit amet euismod leo elementum. Duis vehicula massa arcu, a porttitor nisl vehicula interdum.</p><p>Ut commodo lorem in lacinia egestas.Integer blandit lacus et lacus aliquet placerat ut ut magna.Vivamus ultricies tellus quis vulputate aliquet. Cras et ex eu mi scelerisque tempor id vitae mauris. Etiam ut dolor non nulla feugiat elementum.Vestibulum quis vehicula risus. Curabitur dictum nisi sed neque luctus vestibulum.Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.Sed laoreet dolor ut justo ullamcorper tempor.Cras tellus lorem, finibus ac mollis non, pretium sit amet magna.</p></body></html>\",\"title\":\"Page #3266450\",\"dateCreated\":\"2020-04-29T15:46:22.077+00:00\",\"dateModified\":\"2020-04-29T15:46:22.077+00:00\",\"language\":\"English\",\"keywords\":[\"Lorem\",\"Ipsum\",\"1\",\"Test\"],\"tags\":null,\"program\":\"AccessPoint\",\"pillar\":\"Career Readiness\",\"topic\":\"Topic 1\",\"competency\":\"Competency 1\"},\"score\":1,\"highlights\":null}]}"`

Example Code:

Call to Search service:
```
        public static async Task<DocumentSearchResult<T>> GetDocuments<T>(ISearchIndexClient indexClient, SearchParameters parameters, string query) where T : ISearchIndexerContent
        {

            DocumentSearchResult<T> results;

            results = await indexClient.Documents.SearchAsync<T>(query, parameters);
            return results;

        }
```

API:

```
        [HttpGet]
        public async Task<ActionResult> GetResultsForAllBySearchString(string SearchText)
        {

            SearchIndexClient _searchClient = SearchHelper.CreateSearchIndexClient(_searchConfig.DefaultIndexName, _searchConfig.SearchServiceName, _searchConfig.QueryApiKey);
            var parameters =
                new SearchParameters()
                {
                    Select = SelectFields,
                    SearchMode = SearchMode.All,
                    IncludeTotalResultCount = true
                };
            var results = await SearchHelper.GetDocuments<SearchIndexerContent>(_searchClient, parameters, SearchText);
            return Ok(results);
        }
```

Helper
```
var request = new HttpRequestMessage(HttpMethod.Get, $"/api/Search?SearchText={SearchText}");
var client = clientFactory.CreateClient(clientName);
var response = await client.SendAsync(request);
string resultStr = await response.Content.ReadAsStringAsync();            
JsonSerializerSettings jsonSerializerSettings = new JsonSerializerSettings();
jsonSerializerSettings.NullValueHandling = Newtonsoft.Json.NullValueHandling.Include;
jsonSerializerSettings.TypeNameHandling = TypeNameHandling.Objects;
jsonSerializerSettings.DefaultValueHandling = DefaultValueHandling.IgnoreAndPopulate;
 
DefaultContractResolver contractResolver = new DefaultContractResolver
{
     NamingStrategy = new CamelCaseNamingStrategy()
                 
};
jsonSerializerSettings.ContractResolver = contractResolver;
DocumentSearchResult<SearchIndexerContent> result = JsonConvert.DeserializeObject<DocumentSearchResult<SearchIndexerContent>>(resultStr, jsonSerializerSettings);

```

**Environment:**
Assemblies:
 - Microsoft.Azure.Search 10.1.0
- Newtonsoft.Json, 12.0.0.0

Runtime:
Project Target: netcoreapp3.1

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  1.1.11 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.603 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 - IDE and version : Microsoft Visual Studio Enterprise 2019 Version 16.5.4

**Comment by brjohnstmsft** [comment]
@CSorel-Catalyte Thanks for the detailed description of the problem. It seems you're re-using SDK model types for your own Web API. The custom converters used by the SDK weren't designed with this scenario in mind.

In general it's a good idea to control your own API contracts. That way, if SDK model types change, your API doesn't necessarily have to change.

We're currently working on a completely new version of the .NET client library for Azure Cognitive Search (currently available in preview [here](https://www.nuget.org/packages/Azure.Search.Documents)). In that version, serialization works a lot differently (using `System.Text.Json` instead of JSON.NET), as does the way continuation tokens work. For this reason, we aren't maintaining the `Microsoft.Azure.Search` package anymore. Your best bet for a quick workaround would be to take the JSON converter code from that library and tweak it for your own scenario. That said, in the long run, I would still recommend having your own API contracts and not relying on the ones defined in Azure client libraries.

**Comment by CSorel-Catalyte** [comment]
Thanks! Creating new contracts for something that we are using exactly as they come felt like unnecessary work, but it's probably the path of least resistance.
