### ISSUE TITLE
Azure SDK v2.6 Install - Microsoft.WindowsAzure.ServiceRuntime Removed From GAC

### ISSUE THREAD

**Issue by configdude** [Azure/azure-sdk-for-net#1175]
On multiple machines (Server 2008 R2 and Server 2012R2) had Azure SDK v2.3, 2.4 & 2.5 side by side.  When installing v2.6 with web platform installer Microsoft.WindowsAzure.ServiceRuntime v2.3 was removed from the GAC, causing VS projects still using v2.3 to no longer compile.

**Comment by shahabhijeet** [comment]
@configdude please open a new issue if the problem still exists/repros.
