### ISSUE TITLE
Design for allowing the `EventData` body to be created and retrieved as a string

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#11753]
# Summary

The body of an event is currently represented by a read-only set of bytes in memory and accessible only in this form.  In order to offer greater convenience for transporting types that have been serialized to a string format (JSON, XML), and improved interoperability with other client libraries that prefer to operate on string data, it would be helpful to expose the `EventData.Body` as a string during creation and when accessing the data.

# Scope of Work

- Create an informal design proposal that highlights the set of potential options under consideration; cover the simple case where `string` is treated as a special primitive as well as the case where `string` is considered part of an `EventData<TBody>` design that makes use of a custom body serializer.

- Discuss the design for members and naming with the .NET architect and the feature team; adjusting as needed to reach consensus and sign-off.

# Out of Scope

- Implementation of the design; this will be covered under a dedicated workstream.

# Success Criteria

- The design proposal has been created and shared with the feature team and the .NET language architect.

- The design has reached general consensus within the feature team.

- The .NET language architect has approved the design and any resulting API changes.

# Primitive Case Design Thoughts

- Overload the constructor for `EventData` with a form that takes a `string` body and assumes UTF-8 encoding.  This constructor assumes responsibility for converting the string to `ReadOnlyMemory<byte>`.

- Overload the constructor for `EventData` with a form that takes a `string` body and `System.Text.Encoding` instance.  This constructor assumes responsibility for converting the string to `ReadOnlyMemory<byte>`.

- Introduce a `BodyAsString` method that takes no parameters and assumes UTF-8 encoding.  This method assumes responsibility for converting the event body to a `string`.

- Introduce a `BodyAsString` overload that takes a `System.Text.Encoding` parameter.  This method assumes responsibility for converting the event body to a `string`.

```csharp
public class EventData 
{
    // New constructors
    public EventData(string eventBody);
    public EventData(string eventBody, Encoding bodyEncoding);

    // New Members
    public string BodyAsString { get; }
    public string GetBodyAsString(Encoding bodyEncoding);

    // Existing constructors
    public EventData(ReadOnlyMemory<byte> eventBody);

    protected EventData(
        ReadOnlyMemory<byte> eventBody, 
        IDictionary<string, object> properties = null, 
        IReadOnlyDictionary<string, object> systemProperties = null, 
        long? sequenceNumber = default, 
        long? offset = default, 
        DateTimeOffset? enqueuedTime = default, 
        string partitionKey = null);
    
    // Existing members
    public ReadOnlyMemory<byte> Body { get; }
    public Stream BodyAsStream { get; }
    public DateTimeOffset EnqueuedTime { get; }
    public long Offset { get; }
    public string PartitionKey { get; }
    public IDictionary<string, object> Properties { get; }
    public long SequenceNumber { get; }
    public IReadOnlyDictionary<string, object> SystemProperties { get; }
}
```
# Related Items and References

- [Service Bus] Design and implement message body as string ([#11809](https://github.com/Azure/azure-sdk-for-net/issues/11809))

**Comment by pakrym** [comment]
This looks like something that can be related to Service Registry requirement to serialize strongly typed objects.

If we even invent EventData<T> and EventBatch<T> for those cases we might reuse it for the case where T is a string.

cc @KrzysztofCwalina

**Comment by jsquire** [comment]
Agreed.   That's something that has to be balanced, as well as considered against the existing `BodyAsStream` member.    For context, this came out of a conversation with @KrzysztofCwalina and @JoshLove-msft regarding the same feature within Service Bus, which will also be a case where we'll want to plug in serialization support.

**Comment by JoshLove-msft** [comment]
> Agreed. That's something that has to be balanced, as well as considered against the existing `BodyAsStream` member. For context, this came out of a conversation with @KrzysztofCwalina and @JoshLove-msft regarding the same feature within Service Bus, which will also be a case where we'll want to plug in serialization support.

Would we still want to expose `BodyAsString` as a convenience if even if there was generic support, or does the generic parameter become required in which case it would be redundant?
In ServiceBus, we don't have the `BodyAsStream` member.

**Comment by jsquire** [comment]
I can see it either way, honestly.   String is primitive enough that I can see it as complimentary to a full-on object serializer and part of me thinks that it would be strange to have a full serializer abstraction to just do `string => byte[]` serialization.    However, I can also see the case for one consistent method for translation that doesn't care what the surrounding context is.

I'd like to think on it a bit and come up with some API shapes/examples for discussion and see where we stand.

**Comment by JoshLove-msft** [comment]
```c#
public string BodyAsString { get; }
public string GetBodyAsString(Encoding bodyEncoding);
```
Not sure how I feel about this asymmetry, though I do see it lines up with the existing BodyAsStream. My concern is that the ability to pass in encoding may not be fully discoverable. 

What about having an optional parameter:
```c#
public string GetBodyAsString(Encoding encoding = default);
public EventData(string eventBody, Encoding encoding = default);
```

**Comment by jsquire** [comment]
> Not sure how I feel about this asymmetry, though I do see it lines up with the existing BodyAsStream. My concern is that the ability to pass in encoding may not be fully discoverable.

I know exactly how I feel bout it...  I hate it.   But, there's already a `BodyAsStream` property in Event Hubs which gives us an imbalance whichever way we go.   Service Bus still has the flexibility to go with only methods, which is much cleaner once we start talking parameters.

This problem does go if we consider making this `EventData<T>` where T is `string` and have some kind of serializer in place to do the byte translation, which maps back to Pavel's thought.
