### ISSUE TITLE
[QUERY] Blob streams without holding data in memory?

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-sdk-for-net#11759]
**Query/Question**
I'm looking for a bit of clarification on the download functionality of blob storage.

Am I right in understanding that once `blobClient.DownloadAsync()` is called, the file is downloaded to memory?  Or when I get a stream, am I only being given a metadata object that has yet to pull any bytes over?

Is there a way to work with the blob APIs without being forced to hold bytes in memory?

**Comment by amnguye** [comment]
Hi,

Thanks for you question! If you call DownloadAsync, it does return the stream that holds memory of the blob you are attempting to download. 

What's your scenario or what are you trying to achieve with not yet downloading the blob but calling it ahead of time?

**Comment by seanmcc-msft** [comment]
Hi @atrauzzi , when you download a blob, the entire content (or partial content if you do a ranged download) are downloaded into memory.  We're planning to add Open Read and Open Write in the near feature, to address this limitation.  See https://github.com/Azure/azure-sdk-for-net/issues/9607.
