### ISSUE TITLE
Sample for demonstrating the use of `AzureEventSourceListener` with Event Hubs logging

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#11763]
# Summary

The Event Hubs client library is instrumented using the .NET [`EventSource`](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.tracing.eventsource?view=netcore-3.1) mechanism for logging.  When instrumenting or diagnosing issues with applications that consume the library, it is often helpful to have access to the Event Hubs logs.

Though `EventSource` instrumentation is a common building block for .NET, many applications choose to make use of other logging frameworks which operate differently.  As a result, the approach needed for capturing  `EventSource`-based information is not a well-understood sequence of events and would benefit from illustration.

Because all of the Azure client libraries for .NET are built to the same logging standard, the `Azure.Core` library offers an [`AzureEventSourceListener`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Diagnostics/AzureEventSourceListener.cs) to assist with isolating, capturing, and processing logs from the Azure client libraries.  It would be helpful to demonstrate use of the [`AzureEventSourceListener`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Diagnostics/AzureEventSourceListener.cs) with the Event Hubs client library to assist those interested in capturing logged information.

# Scope of Work

- Create a sample that illustrates use of the `AzureEventSourceListener` with the Event Hubs client library, capturing and using the Event Hubs logs.

- Ensure that the sample demonstrates filtering the captured information to just that of Event Hubs while discussing that the default is to hook all of the Azure client libraries.

# Success Criteria

- The sample odetailed by the scope has been created and integrated with the existing Event Hubs client samples.

- Any refactoring or adjustments required for the sample have been made to infrastructure code.

- The sample is recognized by the existing test suite's smoke test and the tests continue to produce deterministic results and pass reliably.

**Comment by h0s** [comment]
@jsquire  i will be happy to help in this , 
i started a sample based on the information you provided(thank you). 
can i please get your feedback for this draft pull request #15971 ? i will add readme file otherwise are there any comments ?
did i need to add more event filtering to show the event we can catch using AzureEventSourceListener ?
or i need to do more actions with the EventHubs ?

**Comment by andreyshihov** [comment]
Hi @jsquire,
If I could, I'd like to try to help with this one. 
I looked at #15971 and see it's unfinished. Perhaps I could continue its progress?
I also looked at [https://github.com/Azure/azure-sdk-for-net/tree/main/samples/iothub-connect-to-eventhubs](How to request the IoT Hub built-in Event Hubs-compatible endpoint connection string) as an example. Is this how it should be structured when ready to be merged to main?
Cheers

**Comment by andreyshihov** [comment]
Hi @jsquire 

I have added a new snippet in #23445. Is it going in the right direction?

**Comment by jsquire** [comment]
Hi @andreyshihov.   Apologies for the slow reply and thanks very much for your interest in helping to improve the Azure SDK experience; I'll take a look at the PR now.

**Comment by andreyshihov** [comment]
> Hi @andreyshihov. Apologies for the slow reply and thanks very much for your interest in helping to improve the Azure SDK experience; I'll take a look at the PR now.

Here's a new PR #23495
