### ISSUE TITLE
[QUERY] Storage - ContentDisposition headers

### ISSUE THREAD

**Issue by klinki** [Azure/azure-sdk-for-net#11770]
**Query/Question**
Hello, 
I need to set `Content-Disposition` headers to rename downloaded file.

I found on [StackOverflow](https://stackoverflow.com/questions/54207583/azure-blob-storage-v2-does-not-deliver-content-disposition-header-any-more/61597377#61597377)  that I need to set also the `SharedAccessBlobPolicy`. 

I'm quite confused about that, in [MSDN documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.sharedaccessblobpolicy?view=azure-dotnet-legacy&viewFallbackFrom=azure-dotnet)  `SharedAccessBlobPolicy`  is marked as part of legacy API.

Is there any replacement in new API?

Also, is it required to use or is there any other way to rename downloaded file without `Content-Disposition` or `SharedAccessBlobPolicy` ? 

I was able to generate shared access signature manually in Azure portal and when I use it, `Content-Disposition` gets passed sucessfully. But I couldn't find any way how to generate it on container level? Or is it always requried to do it on blob level? Also, is it possible to set infinite expiry date?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.4.1] 
 - Hosting platform: Azure AppService
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by markcowl** [comment]
@klinki Thanks for your question, we will get back to you shortly with a detailed response.

**Comment by seanmcc-msft** [comment]
Hi @klinki , are you trying to rename an existing Blob in Storage, or just set its Content-Disposition header?  To set Content-Disposition:
```
Response<BlobProperties> propertiesResponse = await blobClient.GetPropertiesAsync();
propertiesResponse.Value.ContentDisposition = "your content disposition";
await blobClient.SetHttpsHeadersAsync(propertiesResponse.Value);
```

**Comment by klinki** [comment]
@seanmcc-msft Hello, I'm trying to set its Content-Disposition header. I tried to do it for new blobs with following code:

```csharp
            var blob = blobContainerClient.GetBlobClient(fileName);
            var contentDisposition = $"attachment;filename=custom-file-name.zip";
            
            var headers = new BlobHttpHeaders
            {
                ContentType = "application/octet-stream",
                ContentDisposition = contentDisposition
            };
           
            var uploadedFile = await blob.UploadAsync(data, headers);
```

It seems to be working, problem is header is not used until I add shared access signature to the request URL.

So, for example, URL like this:
`https://xxxxxx.blob.core.windows.net/path/on/storage/file.zip`

doesn't work, but this one:
`https://xxxxxx.blob.core.windows.net/path/on/storage/file.zip?sp=r&st=2020-05-05T20:40:50Z&se=2020-05-05T21:40:50Z&spr=https&sv=2019-10-10&sr=b&sig=some-generated-sig-from-azure` 

works and properly sends the Content-Disposition header.

**Comment by seanmcc-msft** [comment]
Oh!  When building your SAS, set ```BlobSasBuilder.ContentDisposition```

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Sas/BlobSasBuilder.cs#L122

**Comment by klinki** [comment]
But is SAS really needed? Ideally, I'd like to have it working without SAS.

Dealing with SAS brings lot of problems to our use case. We have hundreds of files on blob storage. We made a some mistakes in our file naming and to improve the user experience we would like to rename the downloaded files. Simplest solution seems to be to set `Content-Disposition` header. All the URLs we already have will be still working without any change.

But, if we cannot achieve that without SAS, we would have to create HTTP server (now we don't need that and we have just simple CNAME DNS record to provide "our" URLs) which would read the path for all file download requests, then we would have to add some database with file name and SAS token pairs and read the SAS token for requested file from database. All those SAS tokens would be readonly anyway and we would set their expiry date to maximum we can set, because we don't really care about them, they are just an obstacle for us. Container owning those files has public access level set to `container` anyway.

Is it possible to generate single SAS token on container level? In that case we could skip all the hussle with database and just add single container level SAS token to all requests.



To be honest, it doesn't make much sense to me. You can download the file in both cases anyway, so I don't understand why `Content-Disposition` header requires SAS, since it doesn't really provide any additional security or any other benefit.

I understand SAS tokens might be useful to provide some specific permissions, sure, that might be good in that case. But in this case, it doesn't change anything, any permissions, doesn't provide any additional security, basically has no effect, except allowing the `Content-Disposition` header to be used.

**Comment by seanmcc-msft** [comment]
You don't need to use SAS to set the Content-Disposition stored on each blob, you can get and set HttpHeaders on each blob as I described above.  I only mentioned SAS because it sounded like you wanted to use SAS.  You could also use Shared Key auth or OAuth.

It is possible to create a container-level SAS.  In the BlobSasBuilder, set BlobContainerName and make sure not to set BlobName.

Here's a docs about how SAS works in the service - https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas

**Comment by klinki** [comment]
> 
> 
> You don't need to use SAS to set the Content-Disposition stored on each blob, you can get and set HttpHeaders on each blob as I described above. I only mentioned SAS because it sounded like you wanted to use SAS. You could also use Shared Key auth or OAuth.

Sorry, maybe I didn't describe the problem properly. I know how and I'm able to correcly set the `Content-Disposition` header.  Problem I have is this header is not used if I don't add SAS token to the GET request when downloading a file from the storage.

When I make GET request without passing SAS, it will have following headers:
```
HTTP/1.1 200 OK
Content-Length: 110243840
Content-Type: application/octet-stream
Content-MD5: fao6708h6f9oc1b+3UU+FQ==
Last-Modified: Mon, 04 May 2020 17:16:53 GMT
ETag: 0x8D7F04EF09A8B50
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 6005ad94-201e-012f-38c6-232a81000000
x-ms-version: 2009-09-19
x-ms-meta-ContentDisposition: attachment;filename=custom-file-name.zip
x-ms-meta-SomeProperty: JustTest
x-ms-lease-status: unlocked
x-ms-blob-type: BlockBlob
Date: Wed, 06 May 2020 16:52:42 GMT
```

and the same request when passing SAS token in URL has following headers:
```
HTTP/1.1 200 OK
Content-Length: 110243840
Content-Type: application/octet-stream
Content-MD5: fao6708h6f9oc1b+3UU+FQ==
Last-Modified: Mon, 04 May 2020 17:16:53 GMT
Accept-Ranges: bytes
ETag: "0x8D7F04EF09A8B50"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: e866c783-f01e-0162-03c7-23ec63000000
x-ms-version: 2019-10-10
x-ms-meta-ContentDisposition: attachment;filename=custom-file-name.zip
x-ms-meta-SomeProperty: JustTest
x-ms-creation-time: Mon, 04 May 2020 17:16:53 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
Content-Disposition: attachment;filename=custom-file-name.zip
x-ms-server-encrypted: true
Date: Wed, 06 May 2020 16:54:32 GMT
```

So I guess SAS token is required for GET request to have `Content-Disposition` headers properly set.

> 
> It is possible to create a container-level SAS. In the BlobSasBuilder, set BlobContainerName and make sure not to set BlobName.
> 
> Here's a docs about how SAS works in the service - https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas

This is great news! Thanks, I will use that.

**Comment by seanmcc-msft** [comment]
> x-ms-meta-ContentDisposition: attachment;filename=custom-file-name.zip

You set "ContentDisposition" as metadata, not the BlobHttpHeaders.ContentDisposition.

**Comment by klinki** [comment]
> 
> You set "ContentDisposition" as metadata, not the BlobHttpHeaders.ContentDisposition.
> 

I'm confused. Shouldn't this code

```csharp
var blob = blobContainerClient.GetBlobClient(fileName);
var contentDisposition = $"attachment;filename=custom-file-name.zip";
            
var headers = new BlobHttpHeaders
{
   ContentType = "application/octet-stream",
   ContentDisposition = contentDisposition
};
           
var uploadedFile = await blob.UploadAsync(data, headers);
```

do the same thing as the code you mentioned:

> ```
> Response<BlobProperties> propertiesResponse = await blobClient.GetPropertiesAsync();
> propertiesResponse.Value.ContentDisposition = "your content disposition";
> await blobClient.SetHttpsHeadersAsync(propertiesResponse.Value);
> ```

just for the newly uploaded files? I can use your snippet for updating already existing files. But for new files, it should do the same thing, right?


> 
> The content Content-Disposition you set will be present as a response header for the get request for the download. You don't need SAS for Content-Disposition to be returned as a response header, the issue is setting it correctly.


```csharp
Response<BlobDownloadInfo> downloadResponse = await blobClient.Download();
```
But this downloads the file right away using the azure SDK. What if I want to download the file by using its URL (like this one: `https://xxxxxx.blob.core.windows.net/path/on/storage/file.zip`) from web browser?

**Comment by klinki** [comment]
Ah, I think I can see the source of confusion now. I've been experimenting a lot with setting the `BlobHttpHeaders` and also the metadata. I managed to get the `Content-Disposition` header being sent to the browser using URL (but only with SAS token) which is what I wanted to achieve. 

I believed I did it by using `BlobHttpHeaders` but the truth is I did it by setting the metadata.

So to update existing files, I have to do this:

```csharp
var newFileName = "some-file.zip";
var contentDisposition = $"attachment;filename={newFileName}";

var metadata = new System.Collections.Generic.Dictionary<string, string>
{
     ["ContentDisposition"] = contentDisposition
};

await blob.SetMetadataAsync(metadata);
```

this sets the `ContentDisposition` as metadata and when I want it to propagate to GET request in browser, I have to pass the SAS token. Right?

**Comment by klinki** [comment]
I experimented little bit with setting metadata and setting headers. On the previous test file I had set both metadata and headers, so that might be the reason why headers are so confusing.

Now I cleared all the metadata and kept only headers set.

These are headers for request without SAS token (URL looks like: `https://xxxxxx.blob.core.windows.net/path/on/storage/file.zip` )
```
HTTP/1.1 200 OK
Content-Length: 110243840
Content-Type: application/octet-stream
Last-Modified: Thu, 07 May 2020 09:08:52 GMT
ETag: 0x8D7F26643045C06
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 23716504-a01e-00df-804f-24bcba000000
x-ms-version: 2009-09-19
x-ms-lease-status: unlocked
x-ms-blob-type: BlockBlob
Date: Thu, 07 May 2020 09:09:33 GMT
```

These are headers with SAS token (luckily I have been able to generate the container level token): 
URL looks like: `https://xxxxxx.blob.core.windows.net/path/on/storage/file.zip?sp=r&st=2020-05-05T20:40:50Z&se=2020-05-05T21:40:50Z&spr=https&sv=2019-10-10&sr=b&sig=some-generated-sig-from-azure`

```
HTTP/1.1 200 OK
Content-Length: 110243840
Content-Type: application/octet-stream
Last-Modified: Thu, 07 May 2020 09:08:52 GMT
Accept-Ranges: bytes
ETag: "0x8D7F26643045C06"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 64a34a71-a01e-00d4-784f-24a4ce000000
x-ms-version: 2019-10-10
x-ms-creation-time: Mon, 04 May 2020 17:16:53 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
Content-Disposition: attachment;filename=test-rename-only-headers.msi
x-ms-server-encrypted: true
Date: Thu, 07 May 2020 09:12:17 GMT
```

**Comment by seanmcc-msft** [comment]
> I'm confused. Shouldn't this code
```
var blob = blobContainerClient.GetBlobClient(fileName);
var contentDisposition = $"attachment;filename=custom-file-name.zip";
            
var headers = new BlobHttpHeaders
{
   ContentType = "application/octet-stream",
   ContentDisposition = contentDisposition
};
           
var uploadedFile = await blob.UploadAsync(data, headers);
```

Yes, that is correct.  This code snippet will set the ContentType and ContentDisposition on the blob.

> But this downloads the file right away using the azure SDK. What if I want to download the file by using its URL (like this one: https://xxxxxx.blob.core.windows.net/path/on/storage/file.zip) from web browser?

To be clear, setting ContentDisposition on a blob doesn't actually rename it.  If you want to physically rename a blob in Storage, you need to re-upload it under the desired path.

Assuming https://xxxxxx.blob.core.windows.net/path/on/storage/file.zip is the actual URL of the blob and you want to download it in the browser, you have 2 options.  You can set the container where the blob live's access policy to public, or you can use a SAS URL.  Otherwise, the web browser won't be able to access the blob.

**Comment by jesong** [comment]
Does that mean Content-Disposition will only be in response header when SAS token provided? Is there any official claim of this behavior?
