### ISSUE TITLE
NullReferenceException when trying to initialize an instance of ComputeManagementClient with an HttpClient

### ISSUE THREAD

**Issue by matt-gibbs** [Azure/azure-sdk-for-net#1177]
C# issue filed in the Java repo
Copied over here.
https://github.com/Azure/azure-sdk-for-java/issues/479

using (var messageHandler =  new HttpClientHandler {ClientCertificateOptions = ClientCertificateOption.Automatic })
using (var httpClient = new HttpClient(messageHandler ))
{
    httpClient.DefaultRequestHeaders.Add("User-Agent", new []{"Microsoft.WindowsAzure.Management.Compute.ComputeManagementClient/12.0.0.0"});
    using (var cmc = new Microsoft.WindowsAzure.Management.Compute.ComputeManagementClient( credentials, httpClient)){
    }
}

**Comment by stankovski** [comment]
@matt-gibbs this has been resolved in the latest version of Azure Client Runtime (https://github.com/Azure/autorest)
