### ISSUE TITLE
[QUERY] ServiceBusReceivedMessage

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#11782]
**Query/Question**
1. Is `ServiceBusReceivedMessage` supposed to be immutable?
1. How a custom testing code that requires `ServiceBusReceivedMessage` would obtain the object w/o reflection?

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.ServiceBus/7.0.0-preview.2
 - Hosting platform or OS and .NET runtime version Windows 10 .NET / Framework 4.8 / Core 3.1
 - IDE and version : Visual Studio 2019

**Comment by SeanFeldman** [comment]
cc @JoshLove-msft

**Comment by JoshLove-msft** [comment]
Yes, it should be immutable for production purposes. We will need to expose a factory class/method for testing purposes.

**Comment by SeanFeldman** [comment]
>We will need to expose a factory class/method for testing purposes.

Any samples I can follow to find a proper implementation?

**Comment by JoshLove-msft** [comment]
> > We will need to expose a factory class/method for testing purposes.
> 
> Any samples I can follow to find a proper implementation?

Here is an example from Storage that we would likely use for reference:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Models/BlobsModelFactory.cs

**Comment by SeanFeldman** [comment]
> Yes, it should be immutable for production purposes.

The `ServiceBusReceivedMessage.Properties` cannot be a `IDictionary` as it will allow to mutable the collection.

https://github.com/Azure/azure-sdk-for-net/blob/d558a4abda10223148c7a3297c6bf017ba764efb/sdk/servicebus/Azure.Messaging.ServiceBus/src/ServiceBusReceivedMessage.cs#L156

**Comment by JoshLove-msft** [comment]
> > Yes, it should be immutable for production purposes.
> 
> The `ServiceBusReceivedMessage.Properties` cannot be a `IDictionary` as it will allow to mutable the collection.
> 
> https://github.com/Azure/azure-sdk-for-net/blob/d558a4abda10223148c7a3297c6bf017ba764efb/sdk/servicebus/Azure.Messaging.ServiceBus/src/ServiceBusReceivedMessage.cs#L156

Good catch - we can probably change to ImmutableDictionary.

**Comment by SeanFeldman** [comment]
That means `AmqpMessageConverter` should not be accessing the `Property` field to assign values.

**Comment by SeanFeldman** [comment]
> Good catch - we can probably change to ImmutableDictionary.

It doesn't seem to support [.NET Framework](https://docs.microsoft.com/en-us/dotnet/api/system.collections.immutable.immutabledictionary-2) though.

**Comment by SeanFeldman** [comment]
@JoshLove-msft `System.Collections.Immutable` would need to be referenced from the SB project or `Packages.Data.props`?

**Comment by JoshLove-msft** [comment]
Both, you will be prevented from referencing a specific version in the csproj file, so the version would go in Packages.Data.props.

**Comment by SeanFeldman** [comment]
Sent a PR. Most likely will need to be adjusted.

**Comment by bjuris** [comment]
Took me a while to find the factory, it also had intellisense disabled on the methods, thought I shared a code snippet on this issue if someone else like me googles their way here :smiley:
`var msg = ServiceBusModelFactory.ServiceBusReceivedMessage(body: xx)`

**Comment by SeanFeldman** [comment]
I’ve provided the feedback to the team to cover the testing aspect for the track 2 SDK in the upgrade guide. Too bad it’s not linked to or included in the [repo’s `readme.md`](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Azure.Messaging.ServiceBus).

@jsquire or @jongio, do you think that could be done?

**Comment by SeanFeldman** [comment]
Thank you, @JoshLove-msft.

> For reference, the README does link to the migration guide - [`master`/sdk/servicebus/Azure.Messaging.ServiceBus#azure-service-bus-client-library-for-net](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Azure.Messaging.ServiceBus#azure-service-bus-client-library-for-net) (see the link at the bottom of this section)

It does but the migration guide doesn't have anything on testing and model factories.

**Comment by JoshLove-msft** [comment]
> Thank you, @JoshLove-msft.
> 
> > For reference, the README does link to the migration guide - [`master`/sdk/servicebus/Azure.Messaging.ServiceBus#azure-service-bus-client-library-for-net](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Azure.Messaging.ServiceBus#azure-service-bus-client-library-for-net) (see the link at the bottom of this section)
> 
> It does but the migration guide doesn't have anything on testing and model factories.

Yep, that is what we will be working on this month - cleaning up the migration guide and adding missing details such as the model factories.

**Comment by jsquire** [comment]
We should also consider putting out samples focused on testing and illustrating mocking for major types.   I'll open a separate issue to track that.
