### ISSUE TITLE
Form Recognizer: Preview 3 Renames

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11784]
- [x] trainingFiles param -> trainingFilesUri
- [x] useLabels -> useTrainingLabels
- [x] Error.Code -> Error.ErrorCode

**Comment by maririos** [comment]
@annelo-msft I see some things are checked in the description of the issue but I don't see the changes in Master.
Is there a PR I am missing? or are u currently working on it?

**Comment by kinelski** [comment]
@maririos They're updated in local changes in a branch of mine. I haven't assigned the issue to me because I'm not sure what to do with the first item, and wanted to make it available for other people to grab it.

**Comment by maririos** [comment]
There is an issue for that => https://github.com/Azure/azure-sdk-for-net/issues/11930

So if you want just remove the point from here and assigned the issue to you so once your PR is merged we can close it here
