### ISSUE TITLE
Form Recognizer: Rename GetModelInfos() to GetCustomModels()

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11786]
Was: **Form Recognizer: Update naming for ModelInfo/AccountProperties**

Decision was only to rename GetModelInfos to GetCustomModels, as shown in: https://github.com/Azure/azure-sdk-for-net/pull/11792

**Comment by annelo-msft** [comment]
@samvaity , @kristapratico , did we decide to keep these names the way they are?

**Comment by kristapratico** [comment]
My understanding was that we'd keep GetAccountProperties the way it is and change GetModelInfos -> GetCustomModels
