### ISSUE TITLE
[Samples] [FormRecognizer] Create sample to illustrate how to extract TextContent

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#11783]
Create a sample to show users how to extract `TextContent` information. For instance, in a table cell:
```cs
foreach (FormContent content in cell.TextContent)
{
   if (content is FormWord) // do something.
   else if (content is FormLine) // do something else.
}
```

**Comment by annelo-msft** [comment]
@kinelski , do users need to differentiate between these two cases?  Couldn't they treat it as the base `FormContent` type in most expected use cases?

Since the service down't currently support returning `FormLine` for form content, I'll add this to our backlog for now.
