### ISSUE TITLE
KV live tests fail in environments where premium KV SKUs are not available

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#11795]
While failure of the specific tests is expected in environments that use premium features it might make sense for us to skip tests that require premium SKUs if a premium SKU is not available. 

Sample run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=364186&view=results

**Comment by heaths** [comment]
We will consider it but will need to somehow know when we were handed a URL to a standard SKU.
