### ISSUE TITLE
Add a static factory class/method to create ServiceBusReceivedMessage for testing purposes

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11794]
We don't expose a public ctor as this is an output type.

[Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking)

[Example](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Models/BlobsModelFactory.cs) from Storage

**Comment by SeanFeldman** [comment]
I would add another angle - a concept of a plugin pipeline that was added to Track1.
On the outgoing pipeline, it's a `ServiceBusMessage` all the way. On the incoming pipeline, it's `ServiceBusReceivedMessage` that needs to be manipulated or re-constructed.

**Comment by SeanFeldman** [comment]
I've raised an issue https://github.com/Azure/azure-sdk-for-net/issues/11986.
