### ISSUE TITLE
[BUG] No documentation in Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by vanillajonathan** [Azure/azure-sdk-for-net#11798]
**Describe the bug**
In Visual Studio I see no XML documentation in the Microsoft.Azure.ServiceBus package.

**Expected behavior**
Visual Studio is supposed to show documentation for the classes and methods and such.

**Actual behavior (include Exception or Stack Trace)**
No documentation is presented.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Write `new SubscriptionClient("", "", "");`
2. Then press the <kbd>F12</kbd> key on the `SubscriptionClient`.

**Environment:**
 - Microsoft.Azure.ServiceBus 4.1.3
 - Windows 10, .NET Core 3.1.3 (3.1.201)
 - IDE and version : Visual Studio 16.5.4

P.S. Online documentation is missing too. https://docs.microsoft.com/en-us/dotnet/api/overview/azure/servicebus/client
The Chinese site have docs though. https://docs.azure.cn/zh-cn/dotnet/api/overview/servicebus/client

**Comment by axisc** [comment]
Our documentation pipelines had an issue at the time and have been fixed. Can you check and let us know if you still see the issue?

Thanks

**Comment by vanillajonathan** [comment]
@axisc I can confirm the issue is still present on the online documentation. [Take a look yourself](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/servicebus/client) and you see the documentation is still missing.

The issue is present in version [Microsoft.Azure.ServiceBus 4.1.3](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/4.1.3) released 2 months ago. Since there have been no new NuGet release since then I am unable to confirm whether this issue has been resolved.

**Comment by axisc** [comment]
@vanillajonathan Thanks for bringing this to our attention, I'll follow up with the team.

**Comment by vanillajonathan** [comment]
@axisc Any follow up?

**Comment by axisc** [comment]
@vanillajonathan  published v4.1.4 now. Can you try again?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus?view=azure-dotnet is currently showing the docs (unless I'm missing something).

**Comment by vanillajonathan** [comment]
@asics, No the documentation website still only includes the classes, methods and such but without the description for each member. Compare the English docs website to the Chinese docs website and you will see that the Chinese is much more comprehensive and includes documentation for each member.

**Comment by vanillajonathan** [comment]
@jsquire ping!

**Comment by jsquire** [comment]
Hi @vanillajonathan.  Unfortunately, in this case I'm only the first-level triage and don't have insight.   I'll need to defer to @axisc and @shankarsama for the current state and better context.

**Comment by jsquire** [comment]
//cc: @scbedd

**Comment by danieljurek** [comment]
This is an issue with the `.csproj` file. It is missing the `<DocumentationFile>` property. For example:

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Microsoft.Azure.EventHubs.ServiceFabricProcessor/src/Microsoft.Azure.EventHubs.ServiceFabricProcessor.csproj#L7

For projects starting with `Azure.___` (i.e. "client" libraries as classified by the build) the `<DocumentationFile>` is added for free. In the case of libraries starting with `Microsoft.___` ("data" libraries as classified by the build) the `<DocumentationFile>` directive needs to be manually specified. 

@JoshLove-msft @jsquire

**Comment by ramya-rao-a** [comment]
The necessary work was done in https://github.com/Azure/azure-sdk-for-net/pull/23824

@shankarsama When you release the next update for Microsoft.Azure.ServiceBus, the docs should be appearing as expected.
