### ISSUE TITLE
Could we use customized AES-CTR mode to replace the original AES-CBC encryption mode 

### ISSUE THREAD

**Issue by jeffhli** [Azure/azure-sdk-for-net#11796]
**Azure.Storage.Blobs.Cryptography**
 
**We want to use a customized AES-CTR encryption algorithm to replace the original AES-CBC encryption algorithm. But the original BlobEncryptionPolicy's method is not virtual. Is there any plan to expose the method to virtual?**

**Comment by jaschrep-msft** [comment]
The current plan for this package is scoped to parity with previous SDK versions. This is limited to AES-CBC.

**Comment by jeffhli** [comment]
Then how can we encrypt/decrypt using AES-CTR?

**Comment by jaschrep-msft** [comment]
Looking again at your original description, It seems as if you're using a version older than v12 (which is not actually in this specific repository). We do not plan to add any new features to these older versions. My above comment assumed you were using a v12 library, given the repo we are in, where we are in the process of porting this functionality over.

The above comment still stands though, that even in v12 we have no current plans to support beyond AES-CBC.
