### ISSUE TITLE
Add support for certificate thumbprint to EnvironmentCredential and ClientCertificateCredential

### ISSUE THREAD

**Issue by ericmbowden** [Azure/azure-sdk-for-net#11804]
This request relates to the Azure.Idenity library.
 
I'm trying to retrofit a .net 4.7.1 web application, hosted in IIS on-prem, to use AzureKeyVaultConfigBuilder, to retrieve connection strings from Azure Key Vault.  

The AzureKeyVaultConfigBuilder only supports the EnvironmentCredential (via the DefaultAzureCredential).  This is working fine, in developer environments, using Visual Studio credentials.

For non-developer environments, I would like to use certificate authentication, by specifying a certificate thumbprint and providing the application pool account with read access to the private key.

I was surprised to see that the EnvironmentCredential has recently been updated to allow specifying a certificate credential, but it was implemented to require the path to the certificate, pem or pfx?

I may be misunderstanding something here.  The usual path for client certificate authentication is to put the cert (w/private key) into the cert store and then specify the thumbprint as a configuration for the app to retrieve the appropriate certificate.  I could use a file path, as is supported, and restrict access to that path to the app pool account, but that seems like a non-standard approach.

My request is to add support for certificate thumbprint as a configuration setting for the EnvironmentCredential.

**Comment by schaabs** [comment]
@ericmbowden thanks for filing this issue. Currently we don't support specifying the thumbprint of a certificate in the certificate store. This is functionality we want to add to the Azure.Identity library, but as this only works on windows we prioritized specifying the certificate path ahead of it. I don't have an ETA at this time of when certificate  thumbprint support will be added. I'll update this issue once we've done our next round of planning.

**Comment by ericmbowden** [comment]
Thanks @schaabs

For other windows users, thought I'd share a few tips wrt using the AZURE_CLIENT_CERTIFICATE_PATH option.
- Since the current implementation does not support specifying a certificate password, you will need to secure the private key in the pfx using a service identity.  This an an option provided, if you are creating the pfx as an export from the certificate store.
- I had to follow the steps in this [Microsoft support article](https://support.microsoft.com/nl-be/help/278381/default-permissions-for-the-machinekeys-folders), granting access for Everyone to the machine keys folder.  Without this, the X509Certificate2 constructor which the ClientCertificateCredential is using, would only succeed if the process was running as administrator (_Run as administrator_).  I was led to this article by [this post](https://github.com/Microsoft/dotnet-framework-early-access/issues/25).  I have had to grant the Everyone group access to the Machine Keys folder, as suggested in the prior KB article and post, a few times in the past, so this solution wasn't completely foreign, but it's not clear to me why this exception is necessary (but afaik, that's a topic for another team).
- I was able to understand the issue I was having by creating a quick console/test app which exercised the X509Certificate2 constructor, in the same was as the ClientCertificateCredential does.  This is a useful debug step, if other Windows users find that the AZURE_CLIENT_CERTIFICATE_PATH option is not working.

**Comment by ericsampson** [comment]
@schaabs it would be great for Azure.Identity to have the ability to use the thumbprint of a certificate in the certificate store.

We were going to migrate some of our onprem apps from AppAuthentication to Azure.Identity, but the extra work that @ericmbowden described (thanks!) means that we probably won't migration until a thumbprint is supported. 

Thanks!

**Comment by schaabs** [comment]
We are still discussing adding support for certificate thumbprint support, and as such I still don't have an ETA on this. However, in the meantime I added this [sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/samples/ClientCertificateCredentialSamples.md#loading-certificates-from-an-x509store) to demonstrate how application code could fetch the certificate from the store itself.

**Comment by ericsampson** [comment]
Thanks @schaabs , our team definitely still has interest in this feature. The workarounds are fine, but it would be nice to have a seamless migration to Azure.Identity.

cc @matthewsteeples in case you're still interested in making a PR based on [your earlier comment](https://github.com/Azure/azure-sdk-for-net/issues/18090#issuecomment-763982559)
