### ISSUE TITLE
[QUERY] [ServiceBus] Analog of the NoMatchingSubscriptionException ?

### ISSUE THREAD

**Issue by ig-sinicyn** [Azure/azure-sdk-for-net#11802]
We're trying to port our existing code to the .net core and we're stuck with detecting routing failures on topicClient.Send() calls.

By default the SendAsync() method does not throw exception if there is no subscription the message can be delivered to.
Also, there is no `TopicDescriptor.EnableFilteringMessagesBeforePublishing` property.

Is the functionality missing or can it be enabled somehow?

**Environment:**
 - net core 3.1; Microsoft.Azure.ServiceBus v4.1.3.
 - Azure ServiceBus Standard subscription.

**Comment by ig-sinicyn** [comment]
Up?

**Comment by axisc** [comment]
@ig-sinicyn Thanks for raising this issue.

For high-throughput scenarios, we realized that having this exception would be less actionable since the queueing is not an interactive system.

We're considering instead to have a dead letter entity for a topic where messages land up when no subscription filter is met. Would that be something that would work for you?

**Comment by SeanFeldman** [comment]
@axisc, I'm assuming you're referring to the [fall-through subscription / catch-all](https://github.com/Azure/azure-service-bus/issues/277)? If yes, probably good to link to the issue to let @ig-sinicyn read through and see if it's what he needs.

**Comment by ig-sinicyn** [comment]
@axisc, @SeanFeldman thanks for the answer!

The #277 is a good workaround for us and I've upped it a few days ago:)

**Comment by ig-sinicyn** [comment]
up again:)

**Comment by axisc** [comment]
@ig-sinicyn thanks, noted! No timelines to share yet but it's on our backlog.

**Comment by ramya-rao-a** [comment]
Thanks for the discussion here folks!

We will be closing this issue as there are no planned next steps from the SDK perspective regarding this. The issue https://github.com/Azure/azure-service-bus/issues/277 tracks the requested feature. Please continue the discussion there for further input from the Azure Service Bus team.

Furthermore, please note that a newer package [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus) is available as of November 2020. While the older packages `WindowsAzure.ServiceBus` and `Microsoft.Azure.ServiceBus` will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the migration guide at https://aka.ms/azsdk/net/migrate/sb for more details.
