### ISSUE TITLE
[Question] WebApp SDK - configure storage account

### ISSUE THREAD

**Issue by tony6636** [Azure/azure-sdk-for-net#11812]
Hi, I'm exploring the SDK docs, and I cannot find - is it possible to transform the following bash command to be used with the SDK (myWebApp.Update()....):

> az webapp config storage-account add \
>     --resource-group <some_rg> \
>     --name <some_service_name> \
>     --custom-id GrafanaData \
>     --storage-type AzureBlob \
>     --share-name <some_share_name> \
>     --account-name <some_name> \
>     --access-key <some_key> \
>     --mount-path <some_path> \
> --output none

I was investigating the source code, and I found the class 

> AzureStorageInfoValue 

which contains the same properties as the bash command. The dependencies chain looks like this:

> AzureStoragePropertyDictionaryResourceInner (ctor)
> UpdateAzureStorageAccountsSlotWithHttpMessagesAsync
> UpdateAzureStorageAccountsSlotAsync

and the last method is not being used anywhere.

**Setup**
Version of the Library used (.Net Core 3.1): 
 - Microsoft.Azure.Management.Fluent v1.32.0
 - Microsoft.Azure.Management.ResourceManager.Fluent v1.32.0
 - WindowsAzure.Storage v9.3.3

**Comment by isra-fel** [comment]
@Kotasudhakarreddy Hi Kota, could you share some insights or loop in someone else. Thanks.
