### ISSUE TITLE
[BUG] Move Variable from Pipeline UI to Yml Definition

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#11811]
**Describe the bug**
The variable BuildConfiguration is set in the [mgmt pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=533&_a=summary). We should move the variable into the Yml definition instead.

We should also move [mgmt global variables](https://github.com/Azure/azure-sdk-for-net/blob/8c4c2a3310f6b011c36093cc0882ecbc834be1c3/eng/pipelines/mgmt.yml#L143-L149) inside of the [globals.yml](https://github.com/Azure/azure-sdk-for-net/blob/8c4c2a3310f6b011c36093cc0882ecbc834be1c3/eng/pipelines/templates/variables/globals.yml) template

**Comment by allenjzhang** [comment]
BTW, Track2 mgmt SDK will be unified with data-plane CI. So if this is nice to have, we may want to postpone it.

**Comment by weshaggard** [comment]
Yeah I suspect that the value isn't really here for the track 1 libraries so lets just close this until we find there is enough value to do so.
