### ISSUE TITLE
Unlist old extension packages

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#11823]
https://www.nuget.org/packages/Azure.AspNetCore.DataProtection.Blobs 
https://www.nuget.org/packages/Azure.AspNetCore.DataProtection.Keys
https://www.nuget.org/packages/Azure.Extensions.Configuration.Secrets

**Comment by pakrym** [comment]
Bringing back from backlog. We need to do this, shouldn't take too long.

**Comment by AlexGhiondea** [comment]
Done.
