### ISSUE TITLE
[FEATURE REQ] Support nullable reference types in ConnectionString

### ISSUE THREAD

**Issue by Reza1024** [Azure/azure-sdk-for-net#11830]
**Azure.Core**
 
**Is your feature request related to a problem? Please describe.**
The code generated by autorest handles nullable ref type (technically it disable it, but still the nullable could be set to true in the csproj. But importing from Azure.Core/src/Shared/ConnectionString breaks as it is not explicitly disabled and it has an issue
```C#
public string GetNonRequired(string keyword) =>
    _pairs.TryGetValue(keyword, out var value) ? value : null;
```
should become
```C#
public string? GetNonRequired(string keyword) =>
    _pairs.TryGetValue(keyword, out var value) ? value : null;
```
or the nullable should be disabled for the file.
```C#
#nullable disable
```
More than happy to send a PR for it.

**Comment by pakrym** [comment]
Would be happy to take a pull request.
