### ISSUE TITLE
A better solution to coonfig "build configuration" on mgmt pipelines

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-sdk-for-net#11842]
Per #11702 suggests, it's better to define build configuration in a global yaml file.

This might be useful:  https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables

**Comment by jsquire** [comment]
Given the age, I'm going to close this out as stale.   It looks like neither of the management pipelines has variables defined and the global set is referenced in the templates.  Please feel free to reopen if this is still needed.
