### ISSUE TITLE
[QUERY]Configuring WinRM using Fluent API

### ISSUE THREAD

**Issue by vasingh2011** [Azure/azure-sdk-for-net#11852]
**Query/Question**
I am working of a C# code wherein i want to create an Azure VM, configure WinRM and then execute some scripts in the VM. I am using Fluent API for this.

I am able to create the VM but i am not able to configure WinRM in this VM from C# code as i dont see any method in Fluent API. Generally, the WinRM configuration is present inside the OS Profile settings in Arm Template. Can you help me with the solution for this.

**Environment:**
 - Name and version of the Library package used: Fluent Library 1.33 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Dot Net 4.6.2 on Windows 10
- IDE and version : Visual Studio 2017

**Comment by AlexGhiondea** [comment]
@vasingh2011 can you share the actual package name you are using?
