### ISSUE TITLE
Cognitive: Exposing Model-Version in SDKs

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11863]
Develop guidance on this with the arch board.

Consider Cognitive REST API guidelines.

**Comment by pallavit** [comment]
@annelo-msft can this be closed?

**Comment by annelo-msft** [comment]
Ideally we would determine whether the service teams are still considering versioning models and letting users pin to a specific model version.  Although if it isn't exposed in their REST APIs at this point, they may not have pursued this initiative.
