### ISSUE TITLE
Implement the management client

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#11878]
After we get the API shape vetted in https://github.com/Azure/azure-sdk-for-net/issues/11817, implement the client for Track 2.

**Comment by SeanFeldman** [comment]
`ServiceBusManagementClient` was implemented, no?

Similar comment to https://github.com/Azure/azure-sdk-for-net/issues/12092#issuecomment-641538461. It's a public repository. Having some context helps. 🙂

**Comment by JoshLove-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/12484
