### ISSUE TITLE
[dotenv] Move the samples' sample.env to use the parent sample.env

### ISSUE THREAD

**Issue by sadasant** [Azure/azure-sdk-for-net#11877]
Hi! Should we only have a sample.env at the root level of each project? Right now we have three, one at that level, another one at the JavaScript samples level, and another one at the TypeScript samples level.

**Comment by jsquire** [comment]
@sadasant:  Did you mean to add this to the .NET repo?

**Comment by sadasant** [comment]
Issue moved to [Azure/azure-sdk-for-js #8800](https://github.com/Azure/azure-sdk-for-js/issues/8800) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sadasant** [comment]
Thank you, @jsquire !
