### ISSUE TITLE
get virtual machines Resource health and health history 

### ISSUE THREAD

**Issue by vscodewinodws** [Azure/azure-sdk-for-net#11904]
**Query/Question**
How can we help?

i want to get virtual machines Resource health and health history from sdk using my c# code but seems there is no way to get it so if i am missing something please guide how to do it.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.Fluent 1.31.1 i am on this version but i can upgrade it if needed.
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): windows 10 with .net core 3.1
 - IDE and version : Visual Studio 16.4

**Comment by isra-fel** [comment]
Hello VM team, could you share your thoughts? Thanks.

**Comment by vscodewinodws** [comment]
if method is not available in sdk i am also open to access using rest api , but from docs i am also not able to find that , i am not sure that api ( either sdk method, prop / azure rest api ) exist or not ?

**Comment by Drewm3** [comment]
Moving this over to the Resource Health team to answer the question.

**Comment by stephbaron** [comment]
This is not available today, the only way to retrieve this is to call the Resource Health ARM APIs: https://docs.microsoft.com/en-us/rest/api/resourcehealth/

**Comment by vscodewinodws** [comment]
yes i seems able to find it over the internet but thanks for sharing,  i used those rest api and i was able to retrieve Health history but the api is not showing any data for the status unknown , apart from it i am able to get all those , can you suggest to  get unknow as well ?

**Comment by stephbaron** [comment]
unknown means that the system has not received a signal from the resource, and therefore there isn't any data to show. Unknown should still come back in the API responses (history). In some cases, such as when a machine has been deallocated, the API (current) will return the last transition, for example: 

AvailabilityStatuses (history):

"properties": {
                "availabilityState": "Unknown",
                "title": "Unknown",
                "summary": "We are currently unable to determine the health of this virtual machine.",
                "reasonType": "",
                "occuredTime": "2020-05-12T14:39:36.7872765Z",
                "reasonChronicity": "Transient",
                "reportedTime": "2020-05-12T14:39:36.7872765Z"
            }

AvailabilityStatus/current (current):

    "properties": {
        "availabilityState": "Unavailable",
        "title": "Stopped and deallocating",
        "summary": "This virtual machine is stopping and deallocating as requested by an authorized user or process.",
        "reasonType": "Customer Initiated",
        "occuredTime": "2020-05-12T14:40:51.4036325Z",
        "reasonChronicity": "Transient",
        "reportedTime": "2020-05-12T14:40:51.4036325Z"
    }

**Comment by vscodewinodws** [comment]
you are correct but api response for me does not shows the data  back

**Comment by KranthiPakala-MSFT** [comment]
@stephbaron Following up to see if there is any update on the following query. Thank you
