### ISSUE TITLE
[FEATURE REQ] SendAsync methods should take a CancellationToken

### ISSUE THREAD

**Issue by pseabury** [Azure/azure-sdk-for-net#11901]
**Microsoft.Azure.ServiceBus.QueueClient**
**Microsoft.Azure.ServiceBus.TopicClient**

The SendAsync(...) methods of these classes should follow the async pattern and take a CancellationToken as is typical.

**Comment by axisc** [comment]
@pseabury thanks for opening this issue. We've tagged this as a feature request and will put it on the backlog. no ETA for now.

**Comment by axisc** [comment]
This is better served as a feature request for the new SDK.

Assigning to @JoshLove-msft to consider enabling this feature in upcoming Track 2 SDK. Feel free to reach out to @shankarsama and me to discuss.

**Comment by axisc** [comment]
@JoshLove-msft, checking in to see if you had a chance to review this ask. Please update the status here when you make a call on it.

**Comment by JoshLove-msft** [comment]
[SendAsync](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusSender.cs#L166) as well as all other service methods take a cancellation token in the new library.

**Comment by pseabury** [comment]
> [SendAsync](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusSender.cs#L166) as well as all other service methods take a cancellation token in the new library.

@JoshLove-msft - Which release did this make it in to?

**Comment by JoshLove-msft** [comment]
@pseabury this is in our the new library that is currently in Preview - https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.0.0-preview.8

**Comment by pseabury** [comment]
So will this make it in to the Microsoft.Azure.ServiceBus 5.0+ versions of the ServiceBus libraries?

**Comment by JoshLove-msft** [comment]
I will have to defer to @axisc on that.
