### ISSUE TITLE
[QUERY] Azure.Identity: Default Azure Credential is not authorized

### ISSUE THREAD

**Issue by miflamashood** [Azure/azure-sdk-for-net#11900]
**Query/Question**
I'm trying to access my blob container and perform operations on it using the Default Azure Credential, but I run into the following exception. Any ideas as to why I encounter this error?

` public BlobContainerClient GetBlobContainerClient(IContainerDetails containerDetails)
        {
                      return new BlobContainerClient(GetBlobContainerUri(containerDetails), new DefaultAzureCredential());
        }
    `

`  private static Uri GetBlobContainerUri(IContainerDetails containerDetails)
        {
            return new Uri($"https://{containerDetails.StorageAccount}.blob.core.windows.net/{containerDetails.ContainerName}");
        }`

> {"SharedTokenCacheCredential authentication failed."}
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233088
    HelpLink: null
    InnerException: {"A configuration issue is preventing authentication - check the error message from the server for details.You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS70002: The client does not exist or is not enabled for consumers. If you are the application developer, configure a new application through the App Registrations in the Azure Portal at https://go.microsoft.com/fwlink/?linkid=2083908.\r\nTrace ID: c699a1e0-cda9-4299-b143-4088817da200\r\nCorrelation ID: 29cf4c5b-19a5-4408-8357-ec81e219d8f7\r\nTimestamp: 2020-05-07 10:25:28Z"}
    Message: "SharedTokenCacheCredential authentication failed."
    Source: "Azure.Identity"
    StackTrace: "   at Azure.Identity.SharedTokenCacheCredential.<GetTokenImplAsync>d__16.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()\r\n   at Azure.Identity.SharedTokenCacheCredential.<GetTokenAsync>d__15.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at Azure.Identity.DefaultAzureCredential.<GetTokenFromSourcesAsync>d__12.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runti
me.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at System.Threading.Tasks.ValueTask`1.get_Result()\r\n   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()\r\n   at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__11.MoveNext()"
    TargetSite: {Void MoveNext()}

**Environment:**
 -  Azure.Storage.Blobs 12.4.1
 - Windows 10 .NET Standard 2.1
 -  Visual Studio 16.5.4

**Comment by Jawvig** [comment]
This behaviour happens with both Azure.Identity v1.2.0-preview.3 and -preview.2
(I'm working with Mifla on this)

**Comment by Jawvig** [comment]
Extra info on this issue: The correct account was in the accounts list in Visual Studio 2019. The account is a Microsoft Identity that has is a Guest on the correct AAD. The error persisted when we removed and added the account from the Visual Studio account list. Then, with the account still present in Visual Studio, we ran `az login` with that account, but got the same error.
Visual Studio Code is not installed. None of the environment variables needed by https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet were set.

**Comment by schaabs** [comment]
@Jawvig, thanks for filing this issue. Based off the error message it seem the problem here is with the client id Azure.Identity is using in the case of the `DefaultAzureCredential`. 

> Original exception: AADSTS70002: The client does not exist or is not enabled for consumers

Currently the library is using the Azure CLI's client id. When you say that you get the same error when running `az login` do you mean that the `az login` command itself is failing with that error? Because based off the error message above that's what I would expect, that somehow the Azure CLI is not enabled for your tenant.

**Comment by Jawvig** [comment]
No, `az login` ran fine and normally. It was when running code (via launching it in the debugger from Visual studio) that the same error occurred.

**Comment by Jawvig** [comment]
Could it be connected with the fact that Mifla is using a guest account (a Microsoft account) for logging in rather than an account native to the AAD?

**Comment by Jawvig** [comment]
So we had a second person getting exactly the same error. The solution was to shift both of them from using AAD guest accounts to having an account on the subscription's tenant. Are guest accounts supposed to work?

**Comment by AlexGhiondea** [comment]
@Jawvig I have reactivated this issue. 

@schaabs do you have an answer here?

**Comment by schaabs** [comment]
@Jawvig, sorry for the delayed response. A couple of thoughts. 

First, since you're trying to authenticate a guest account you'll need to specify the tenant id when using the `DefaultAzureCredential` you can either specify this by setting the `AZURE_TENANT_ID` environment variable, or setting the `SharedTokenCacheTenantId` and `VisualStudioTenantId` properties on `DefaultAzureCredentialOptions`. If you use the options you'll need to specify both properties.

Second is the account your trying to authenticate an organization account or a personal account (personal would be @hotmail.com, @live.com, @outlook.com). We have seen some odd behavior with personal accounts so it's possible we have a latent bug in this area.

**Comment by Jawvig** [comment]
No worries, @schaabs . The accounts were Microsoft Accounts (personal) - though one was based on a gmail.com address and the other yahoo.com. Probably the AZURE_TENANT_ID environment variable would have sorted this out.  As I mentioned earlier, I've created non-guest accounts for them now and everything is fine. I'm happy to close it as we hadn't explicitly specified the tenant Id, though obviously there's a chance that wasn't the problem. If it was the issue, it would be nice if the error message could suggest this as a fix.

**Comment by AlexGhiondea** [comment]
Thank you @Jawvig. Let's close this for now -- if you run into this (or any other issues) please file an new issue and we will take a look!
