### ISSUE TITLE
Implement receiver redirect support

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#11902]
# Summary

The Event Hubs service supports redirects for AMQP receiver links in order to provide a direct connection to a partition node rather than routing through the gateway.  When the redirect is opted-into,  upon creation of a receiver link, the Event Hubs service will respond with an `amqp:link:redirect` error if it also supports redirects. The error details contains the information needed to create a new connection to the service.

The main benefit of receiver redirect is it allows a more direct connection to the host actually sending events to the client which should reduce latency.

# Scope of Work

- Implement the design for supporting receiver redirects.

# Success Criteria

- The design has been implemented and the targeted clients are able to opt-in to the receiver redirect.

- The tests necessary for its validation have been created or adjusted and pass reliably; tests that do not focus on the extension points have been removed and no base functionality is included.

- The existing live test suite continues to produce deterministic results and pass reliably.

# Related Issues and References

- Design for receiver redirect support ([#10588](https://github.com/Azure/azure-sdk-for-net/issues/10588))

**Comment by JimSuplizio** [comment]
Hi @jsquire, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
