### ISSUE TITLE
[Design] Form Recognizer: Decide on Naming for Model LastModified field

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11913]
Q: For management APIs "LastModified" is actually "LastUpdated" in the swagger

This was trying to be consistent with other SDKs
FOLLOW-UP: Investigate the correct nomenclature

See details in: https://github.com/Azure/azure-sdk/issues/962#issuecomment-625307676

Meeting chat from arch board review contains further details.

Goal:
- Find a name that indicates model is immutable
- Standardize across languages

**Comment by maririos** [comment]
Note that what the values represent is:
>CreatedDateTime is when the training request was received. LastUpdatedDateTime is when the training completed. I like to have both values so I can see how long training took

According to that, we are going to do the following renamings:
- `CreatedOn` -> `RequestedOn`
- `LastModified` -> `CompletedOn`
