### ISSUE TITLE
Is there a way to enable AHUB on a SqlVirtualMachine using .NET SDK?

### ISSUE THREAD

**Issue by mirandavj** [Azure/azure-sdk-for-net#11920]
I have an azure function that enables AHUB on regular Virtual Machines. However , now i need to apply this to SqlVirtualMachines but i don't see any Library to manage SqlVirtualMachines in the API Reference nor any example of how to work with SqlVirtualMachines using .Net SDK.

I'm currently using fluent libraries to manage Virtual Machines
Microsoft.Azure.Management.Fluent(1.33.0)
.Net Core
Microsoft Visual Studio Enterprise 2019 Version 16.5.3

```csharp
Azure.IAuthenticated authenticatedClient = Azure.Authenticate(restClient, tenantId);
JObject eventJson = JObject.Parse(myQueueItem);
string subscriptionId = Convert.ToString(eventJson["data"]["subscriptionId"]);
string virtualMachineResourceId = Convert.ToString(eventJson["data"]["resourceUri"]);
IAzure environment = authenticatedClient.WithSubscription(subscriptionId);               
// Get the virtual machine
IVirtualMachine virtualMachine = environment.VirtualMachines.GetById(virtualMachineResourceId);
virtualMachine.Update().WithLicenseType("Windows_Server");
virtualMachine.Update().Apply();
```

Is there a way to do this but with SqlVirtualMachines?

**Comment by isra-fel** [comment]
@weidongxu-microsoft Hello Weidong could you please help answer this? Thanks.

**Comment by weidongxu-microsoft** [comment]
@mirandavj 
Fluent .NET SDK does not support SqlVirtualMachine.
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/sqlvirtualmachine/resource-manager

@isra-fel 
Do you know other .NET SDK support it?

**Comment by isra-fel** [comment]
Hi @mirandavj , you can try our .NET SDK here: https://www.nuget.org/packages/Microsoft.Azure.Management.SqlVirtualMachine/

**Comment by mirandavj** [comment]
I have tried using the .NET SDK @isra-fel recommended , i was able to list and get the Sql Virtual Machines but when i try to update i don't see any parameter or option to update Lycense type.

```csharp
// Create SQL Virtual Machine Management Client
SqlVirtualMachineManagementClient sqlVirtualMachineManagementClient = new SqlVirtualMachineManagementClient(customAzureCredentials);
sqlVirtualMachineManagementClient.SubscriptionId = SubscriptionId;

// List Sql Vms
IEnumerable<SqlVirtualMachineModel> sqlVirtualMachines = sqlVirtualMachineManagementClient.SqlVirtualMachines.List();

// UPDATE!!!!
foreach (SqlVirtualMachineModel sqlVm in sqlVirtualMachines) 
{
SqlVirtualMachineUpdate parameters = new SqlVirtualMachineUpdate();
sqlVirtualMachineManagementClient.SqlVirtualMachines.Update(ResourceGroupName,sqlVirtualMachine.Name,parameters);       
                  
}
```

As far as i can see SqlVirtualMachineUpdate only contains a tags property.

Would be good if there was any documentation for this specific Library.

**Comment by isra-fel** [comment]
Thanks for pointing that out Vinicio! I've opened #12274 to our SQL VM team about the missing doc. You can track the progress there if interested. 😁
