### ISSUE TITLE
Form Recognizer: Consider renaming TrainingFileFilter to TrainModelOptions

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#11930]
Java is doing this currently.

However, if we introduced `TrainModelOptions` and put `TrainingFileFilter` in it, we would probably also want to move `useTrainingLabels` param into it.  We should keep `useTrainingLabel` as a parameter to the method, since it significantly changes the functionality of the method.  

Goal: make a decision and align across languages.

**Comment by kinelski** [comment]
Conclusion after discussing with other languages: the `TrainingFileFilter` name will be kept, but the `filter` parameter in `StartTraining` will be renamed to `trainingFileFilter`.
