### ISSUE TITLE
[BUG]WorkflowRunActions only returns 30 actions max

### ISSUE THREAD

**Issue by penggaolai** [Azure/azure-sdk-for-net#11932]
We have a logic app that contains over 100 actions. But I run following snippet, it only returns me 30 actions.

        var actions = _client.WorkflowRunActions
             .List(resourceGroup, logicApp, workflowRun.Name)
             .OrderBy(x => x.StartTime);

For all logic apps that contains less than 30 actions, it works fine. Are there any settings that control this limitation?

**Comment by lilyjma** [comment]
@Azure/azure-logicapps-team please take a look

**Comment by joechung-msft** [comment]
@penggaolai there is a `ListNext` method to follow the continuation (_nextLink_) returned by the `List` method so you can get more run actions. The `ListNext` can also return a continuation (_nextLink_) so you might need to call it more than once.

Reference
[Azure SDK for .NET documentation](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Microsoft.Azure.Management.Logic/4.1.0/api/Microsoft.Azure.Management.Logic/Microsoft.Azure.Management.Logic.WorkflowRunActionsOperationsExtensions.html#Microsoft_Azure_Management_Logic_WorkflowRunActionsOperationsExtensions_ListNext_Microsoft_Azure_Management_Logic_IWorkflowRunActionsOperations_System_String_)

**Comment by lilyjma** [comment]
Hi, this issue seems to be resolved, so I'm closing it now. If you have more questions, please reopen. Thanks!
