### ISSUE TITLE
Test for diagnostic scope doesn't seem to fail if there is no diagnostic scope

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#11966]
When PR #11860 was created, it effectively removed `DiagnosticScope`s from Search, since we were calling into the *RestClient classes directly, bypassing the *Client classes that were generated. Since creating `DiagnosticScope`s was moved up from *RestClient to *Client classes, there should've been a failure in the tests for `DiagnosticScope`. I know, at least, then they fail when the scope name doesn't match the method name (sans "Async") because, when refactoring Key Vault toward the end before release, I forgot to change it in a couple places. But, seemingly, if there's no scope, the tests don't fail and probably should so we can catch cases like this where there is no more distributed tracing for this or any other reason.

**Comment by pakrym** [comment]
This is for the case where the method is marked with `[ForwardsClientsCalls]`, pretty sure it works without.

**Comment by heaths** [comment]
Shouldn't the test still make sure that there is a scope defined and not just trust the attribute?

**Comment by pakrym** [comment]
Yes, that's the bug, it should verify that there is a scope but ignore the name.

I think it seems the Azure.Core HTTP scope and figure that's enough.
