### ISSUE TITLE
Find a way to properly write logs when needing to debug Search live runs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#11969]
PR #11942 makes a test pass if the document count if >= 10, even though it should only ever be 10. There's no reason the resource should be shared, though it seems like that's the problem. But to properly debug this, we need to conditionally attach logs to even successful tests so we can see what else is creating the same container or index.

The `AZURE_SEARCH_TEST_VERBOSE` environment variable is not being passed through to the template, so the code to read that isn't working. I even tried passing it via the `EnvVars` template parameter to no avail.

Instead, maybe use `$SYSTEM_DEBUG`, if indeed that is the right environment variable for the built-in `System.Debug` that gets defined when you turn on diagnostics (what we want anyway, so less variables to maintain).

When done, revert the changes to `SearchServiceClientTests.CreateAzureBlobIndexer` and use just `Assert.AreEqual` so, when it fails, we can finally determine why.

**Comment by pakrym** [comment]
Filed https://github.com/Azure/azure-sdk-for-net/issues/11981

**Comment by heaths** [comment]
@pakrym if you're open to always logging, at least for now I'd rather just take the verbose check out. I emailed a contact about why the environment variable is not being defined as documented (in numerous places). This would be enough to at least figure out - if anything - what else is created the same resource that is returning the wrong count.
