### ISSUE TITLE
Azure Tables Sprint 2

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#11962]

**Comment by fabiomaulo** [comment]
Guys you are wonderful!! please put something on nuget about this package... I can't live we the brothel generated by the abandonment of tables from storage-team and from cosmos-team. I'm happy to see you working on tables again and I hope to see table-storage as first-class-citizen again.

**Comment by maririos** [comment]
Thank you so much @fabiomaulo . We are working on the first preview of the Azure.Tables library. Once we have a package ready, we will post it in nuget :)
We welcome all the feedback you have from this work.

**Comment by fabiomaulo** [comment]
@maririos if you guys need two hands, and another brain, to work on this package in this phase, let me know, I will be happy to help during the quarantine.

**Comment by maririos** [comment]
FYI @meanjeekim  and @christothes

**Comment by christothes** [comment]
@fabiomaulo - Thanks for your interest in the track 2 Table client! In case you hadn't already found it, the code in progress can be found [here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/tables/Azure.Data.Tables). 

For starters, we'd appreciate any feedback you may have about the latest client shape. I'd be interested in your perspective a someone familiar with the current clients. If you have any specific areas you'd be interested in contributing, I'll stay on the lookout for some opportunities to put together some "up for grabs" Issues.

**Comment by fabiomaulo** [comment]
I´m familiar with Table clients since 2009 or 2010 (Azure CTP).
I´m not so afraid about breaking changes especially now where the Storage-SDK was itself a monster breaking change leaving the Table storage abandoned.
I´ll check the code and I´ll try to send you something somewhere in public and with some comment about "use it as you want license". Please send me a source header-comment that let you use whichever part of the source as you want (I know something about MS politic about this matter).

**Comment by christothes** [comment]
@fabiomaulo If you want to play around with some ideas, the easiest path would be to create a fork. All the files in the repo should have the default header we use. Ex: [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L1-L2 )

I'd also recommend taking a look through [CONTRIBUTING.md](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md) 

Feel free to reach out by creating an issue if you'd like to discuss something or get some feedback before investing time in a PR.
