### ISSUE TITLE
[Azure Core] Readme content and sample code of Azure Core is incorrect

### ISSUE THREAD

**Issue by XuGuang-Yao** [Azure/azure-sdk-for-net#11972]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core#azure-core-shared-client-library-for-net)

> ![image](https://user-images.githubusercontent.com/53599438/81460743-dd014480-91d9-11ea-93ae-452639a6136d.png)

Comment: Link is useless, we should change it to [https://azure.github.io/azure-sdk-for-net/core.html](https://azure.github.io/azure-sdk-for-net/core.html)

**Comment by pakrym** [comment]
Thank you for the report. We would happily take a PR with a fix.
