### ISSUE TITLE
Hyak.Common.CloudException

### ISSUE THREAD

**Issue by riccardobecker** [Azure/azure-sdk-for-net#1197]
Hi there,

i've upgraded the Service Management Libraries to the latest versions. Creating a SB namespace used to work before by using CertificateCloudCredential but now it suddenly fails by throwing and 
Hyak.Common.CloudException (ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription.).

I am running this piece of code in a worker role locally and it used to work before but for some reason the sbClient.Namespaces.Create(serviceBusNamespaceName, "West Europe") throws this Hyak.Common.CloudException.

Did anyone experience that before??

regards

**Comment by markcowl** [comment]
@riccardobecker Thank you for the report, we will take a look and get back to you.

Meanwhile, can you provide any information on the messages going back and forth between the client and server?  You can use one of the published libraries for tracing: 
http://www.nuget.org/packages/Microsoft.WindowsAzure.Common.Tracing.Etw/
http://www.nuget.org/packages/Microsoft.WindowsAzure.Common.Tracing.Log4Net/

**Comment by riccardobecker** [comment]
Mark, I had some old assembly references flying around. Fixed it by now.
