### ISSUE TITLE
ComputeManagementClient fails to find VM

### ISSUE THREAD

**Issue by pjirsa** [Azure/azure-sdk-for-net#1198]
I have a VM in my azure subscription that is listed as ResourceType=Microsoft.ClassicCompute/virtualMachines. I can see this resource when calling ResourceManagementClient.ListAll. But, when I pass the ResourceGroupName and VM name to ComputeManagementClient.Get, it fails to find the VM. Is there a way to get the details for this VM without going back to the v1 SDK?

**Comment by markcowl** [comment]
@pjirsa Unfortunately, you will only be able to manage this VM right now using the old (RDFE) compute library.  Routing this to the appropriate folkjs so they see the feedback.

**Comment by shahabhijeet** [comment]
@pjirsa please open a new issue if the problem still exists/repros.
