### ISSUE TITLE
Make ErrorCode an extensible enum

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#11990]
Swagger definition for ErrorCode: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/FormRecognizer/preview/v2.0/FormRecognizer.json#L1135

**Comment by maririos** [comment]
@annelo-msft  this issue was marked as priority 3 in API View, so not sure if it is going in Preview 3 or later, so it is now in the Backlog epic.
Feel free to move it to whatever epic makes more sense

**Comment by annelo-msft** [comment]
I'm hesitant to do this now for FR, because their error codes are still numbers.

**Comment by maririos** [comment]
From the service team, the ErrorCode might change to just text for a later bump release (like 3.x) but not for 2.x versions.
One option for us here is to rename `ErrorCode` to something like `ErrorCodeId` or similar and when the service makes the change, then use the name `ErrorCode` for that enum

**Comment by maririos** [comment]
Decision is to leave the type as string. Enum vs extensible enum was in conversation but landed on string following what other libraries in .NET are doing and with [`RequestFailedException`](https://github.com/Azure/azure-sdk-for-net/blob/3edb484a64afc93d6dc9be9d0947bbaad49f9763/sdk/core/Azure.Core/src/RequestFailedException.cs#L25) which has `ErrorCode` as string.
