### ISSUE TITLE
Access DNS

### ISSUE THREAD

**Issue by gregorypilar** [Azure/azure-sdk-for-net#1200]
Hi, I'm trying to access the dns feature through the api  but im getting this error

An exception of type 'Hyak.Common.CloudException' occurred in Microsoft.Threading.Tasks.dll but was not handled in user code

Additional information: AuthorizationFailed: The client 'bc0524ef-7afc-4b78-9497-a266473de305' with object id 'bc0524ef-7afc-4b78-9497-a266473de305' does not have authorization to perform action 'Microsoft.Network/dnszones/read' over scope '/subscriptions/2dbfb480-6eff-4e5d-bc94-53cb6afaa4fc/resourceGroups/RGNSolvexDNS/providers/Microsoft.Network'.

Im using this code to get the authentication token 

   var authenticationContext = new AuthenticationContext(string.Format(ConfigurationManager.AppSettings["login"], ConfigurationManager.AppSettings["tenantId"]),false);
            // Config for OAuth client credentials 
            var clientCred = new ClientCredential(ConfigurationManager.AppSettings["clientId"], ConfigurationManager.AppSettings["clientSecret"].ToSecureString());
            var authenticationResult =  authenticationContext.AcquireToken(ConfigurationManager.AppSettings["apiEndpoint"],clientCred);
            
            string token = authenticationResult.AccessToken;
           
            return token;

any ideas?

**Comment by GarethBradshawMSFT** [comment]
Does authenticationResult.AccessToken contain a value (it should be a long string of characters and numbers) and does authenticationResult.AccessTokenType contain the value "Bearer"?  You should also check the ExpiresOn field and the UserInfo to make sure that's correct.

Gareth

**Comment by markcowl** [comment]
@gregorypilar There are several things that could be the issue - it could be that the credentials you are using have not been granted access to that resource group or resource (through RBAC), it could be that the token you have acquired is not for the tenant containing the subscription you are using.

Given this particular message, this seems like an actual authorization issue for that resource.

For common authentication patterns, I suggestusing the common.authentication library here:http://www.nuget.org/packages/Microsoft.Azure.Common.Authentication/1.0.26-preview


here is a sample using the library:
```
using Microsoft.Azure.Common.Authentication;
    using Microsoft.Azure.Common.Authentication.Factories;
    using Microsoft.Azure.Common.Authentication.Models;
    using Microsoft.Azure.Management.Resources;
    using Microsoft.Azure.Management.Resources.Models;
    using System;
    class Program
    {
        public static void Main(string[] args)
        {
            string tenantId = args[1];
            var subscriptionId = args[0];
            AuthenticationFactory factory = new AuthenticationFactory();
            var token = factory.Authenticate(new AzureAccount { Type = AzureAccount.AccountType.User }, AzureEnvironment.PublicEnvironments[EnvironmentName.AzureCloud],
                tenantId, null, ShowDialog.Auto);
            AccessTokenCredential creds = new AccessTokenCredential(new Guid(subscriptionId), token);
...
```

You can then use the AccessTokenCredential (which will auto-renew in your code.  There is a similar account type for service principal.

To debug issues, consider using one of the published tracing libraries for the sdk:
http://www.nuget.org/packages/Microsoft.WindowsAzure.Common.Tracing.Etw/
http://www.nuget.org/packages/Microsoft.WindowsAzure.Common.Tracing.Log4Net/

This will enable you to capture client/server trafficx, information messages, and the like.  If you are still having issues, message logs would be extremelty helpful to us in diagnosing your issue.

**Comment by gregorypilar** [comment]
Thanks @markcowl  that solve the problem :+1:
