### ISSUE TITLE
[QUERY] Service Bus SDK: How to identify Deferred messages from Peeking results?

### ISSUE THREAD

**Issue by kenans** [Azure/azure-sdk-for-net#12012]
I'm using the `Microsoft.Azure.ServiceBus` package to access Azure Service Bus and I'm using the version `4.1.3`.

Due to the fact that the [`Microsoft.Azure.ServiceBus.Message`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Message.cs) class doesn't have `State` available in the `SystemProperties` (as opposed to the `BrokeredMessage` class in the old `WindowsAzure.ServiceBus` package), I wonder how to identify Deferred messages from the message browsing results using methods like `PeekAsync`? 

Note I've seen some duplicate issues/requests being reported and open on the old archived repo, like [this](https://github.com/Azure/azure-service-bus-dotnet/issues/343) and [this](https://github.com/Azure/azure-service-bus-dotnet/issues/414). I also noticed the team was planning to [put `State` property back to the latest Service Bus SDK](https://github.com/Azure/azure-sdk-for-net/issues/9886). But is there a plan to add the `State` to the message model or is there a work around for the current `Microsoft.Azure.ServiceBus` SDK?

**Comment by axisc** [comment]
@kenans Are you seeing deferred messages when browsing. That should not be the case. Deferred messages must show up only when received with the specific sequence number.

**Comment by kenans** [comment]
@axisc Thank you for the response!

I understand that we can use the `SequenceNumber` to track the `Deferred` messages. But in our use case, the app is monitoring the Service Bus queue by browsing all the existing messages and acting based on the message type (Active/Deferred/Scheduled).

I did some tests and I think we can use `ScheduledEnqueueTimeUtc` to tell if the message is Schduled type.

Doing the same tests on the Deferred message, unfortunately I wasn't able to find a pattern. That's actually why I'm opening the issue and ask the question.

**Comment by axisc** [comment]
@kenans curious as to how you are browsing deferred and scheduled messages together. Could you share the code snippet?

**Comment by axisc** [comment]
@kenans  closing this issue for now. Please feel free to open a new one if this is still an open question.

From the perspective of identifying deferred messages, the only way is to store the sequence numbers of the messages that were deferred and checking against that list.
