### ISSUE TITLE
[QUERY] What is the relation between Azure.Identity and Azure.Services.AppAuthentication libs?

### ISSUE THREAD

**Issue by csadam** [Azure/azure-sdk-for-net#12016]
**Query/Question**
It looks like both the [Azure.Identity](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity) and [Azure.Services.AppAuthentication](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/mgmtcommon/AppAuthentication) libraries are for the same thing, getting access tokens.

What is the difference between the two?  

I'd like to use either one for a web application with Managed Identity to access SQL server. It looks like both of them can do it. Which one should I choose and why?

**Comment by schaabs** [comment]
@csadam Thanks for your question. Azure.Identity is a newer authentication library meant to simplify authentication in a new wave of Azure SDK libraries we are currently in the process of creating and releasing. A full list of libraries which support authenticating directly through Azure.Identity can be found [here](https://azure.github.io/azure-sdk/releases/latest/dotnet.html), although this list is rapidly growing. 

As to your specific question as to which you should use for access to Azure hosted SQL Server instances, here you are going to still need to use Azure.Services.AppAuthentication for the time being as Azure.Identity doesn't currently support SQL authentication. This is a work item on our backlog, https://github.com/Azure/azure-sdk-for-net/issues/12145, which we currently currently have planned for the early fall of this year. 

Hopefully this answers your question, if you need more information or have followup questions please feel free to reopen this issue or file a new issue.
