### ISSUE TITLE
Marking a series of service bus messages as START and END of a sequence

### ISSUE THREAD

**Issue by Sandeep321** [Azure/azure-sdk-for-net#12010]
**Query/Question**
Problem Statement: I am publishing a series of messages to a service bus topic. Let's say I have messages 1 to 100. They are all different messages in themselves but they are part of a series. I know we can set that series by using sessions(same session id for all those messages). But is there a way to say that message 1 is the start of that series and 100 is End of that series. 
Adding custom sequence numbers will allow me to achieve the same behavior but is there something which service bus provides to achieve that kind of sequencing?

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ServiceBus 4.1.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):  Azure AppService - .Net Core 3.1
 - IDE and version: Visual Studio 16.5.4

**Comment by axisc** [comment]
@Sandeep321 I'm afraid not. However, the messages are ordered on arrival into Service Bus.

With sessions, as long as you send sequentially and receive one at a time, the order should be maintained. Additional header properties could be maintained to surface that information but I wonder what value it will provide over the order guarantee that is explicitly provided by Sessions.

Let me know if you have any follow up questions.

**Comment by Sandeep321** [comment]
@axisc Thanks for your reply.
We want to take a specific action on the last message of a particular session. We don't want to take the same action on all messages before the last one arrives. So, we would need to know that yes this message is the last one from the session.

Consider this, I receive messages for 10 different countries, I would want to compile information for all 10 countries and send a single notification for all of them. So, I can't send the notification until I receive messages for all 10 countries. I would need to know which message is last among those 10.

**Comment by SeanFeldman** [comment]
@Sandeep321, if you require all 10 messages to be received prior to taking any action and the last message should be a marker message, sessions are what you need. When you receive messages in a session, you can have a session state which could store the information from the previous 9 messages until the last, 10th, is processed.

**Comment by axisc** [comment]
@Sandeep321 

@SeanFeldman  is right and that is a good solution. hope that answers your question.

Closing this issue for now, please feel free to reopen if required.

**Comment by Sandeep321** [comment]
Hi @SeanFeldman and @axisc Don't we have sessions support for Topics(not Queues) in Standard and Premium tiers. I do not see any option to enable it while creating the topics. Am I missing something?. I see the option when creating Queue though.
 
![image](https://user-images.githubusercontent.com/6442549/98540125-7279b000-22b3-11eb-9b02-03ce88521798.png)

**Comment by SeanFeldman** [comment]
@Sandeep321, try [Service Bus Explorer](https://github.com/paolosalvatori/ServiceBusExplorer/releases/latest).

**Comment by Sandeep321** [comment]
@SeanFeldman 
I have that and I don't see any such option there as well.
![image](https://user-images.githubusercontent.com/6442549/98630945-45c0a980-2342-11eb-8840-90c7de4adffb.png)

**Comment by SeanFeldman** [comment]
Look at subscriptions. Receive operations with sessions are only possible on the entities that can be used to receive messages (queues and subscriptions).
