### ISSUE TITLE
Azure Search unit tests fail when using a different time zone

### ISSUE THREAD

**Issue by amang2205** [Azure/azure-sdk-for-net#1202]
When using a different time zone, 3 unit tests fail, namely:
- CanWriteLocalDateTime: as it turns out, the expected and actual values are different, more specifically rather than returning "2000-01-01R00:00:00-02:00", the test returns "2000-01-01T00:00:00+02:00". The fun though is that the actual value is correct and the different comes from the expected value being hardcoded to contain a negative offset; in other words, the code returns a correct result but the test
- DynamicDocumentDateTimesRoundTripAsUtc: The expected value is 1/1/2000 12:00:00 AM +02:00, but it returns 1/1/2000 8:00:00 AM +00:00, which basically means a 10 hours time difference
- StaticallyTypedDateTimesRoundTripAsUtc: The test's expected value is 12/31/1999 10:00:00 PM (no time offset information), whilst the actual returned value is 1/1/2000 8:00:00 AM. Looking closely at the time difference, the actual difference is yet again of 10 hours, considering the two DateTime values are part of the same time zone

**Comment by brjohnstmsft** [comment]
The failures were observed when the tests were run in the UTC+02:00 time zone, making it likely that the tests are specific to UTC-08:00 (that's a 10 hour difference). I'll investigate.

**Comment by markcowl** [comment]
Assigning to the appropriate internal team

**Comment by brjohnstmsft** [comment]
This has now been fixed.
