### ISSUE TITLE
[BUG] VisualStudioAccessTokenProvider fails with an exception with no detail if so valid token provider paths are provided.

### ISSUE THREAD

**Issue by veleek** [Azure/azure-sdk-for-net#12035]
**Describe the bug**
If the path in `tokenprovider.json` points to a file that doesn't exist, using `VisualStudioAccessTokenProvider` will fail with an exception with no error detail about why.

In [`GetProcessStartInfos@VisualStudioAccessTokenProvider.cs:67`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/TokenProviders/VisualStudioAccessTokenProvider.cs#L67), if the TokenProvider Path points no a non-existent file, it assumes it's been uninstalled and skips it.  If you only have one entry and it's misconfigured, then this returns an empty `processStartInfos` list.  Then because there are no processes, it skips over to the error handling which thrown an exception with no detail.

**Expected behavior**
If using the `VisualStudioAccessTokenProvider` and there are no valid token providers found, the error message should indicate that so the configuration can be fixed.

In my case, I believe this occurred due to an update to VisualStudio preview version moved this file but didn't update the configuration.  Manually updating the path to the appropriate value allowed it to succeed as expected.

**Actual behavior (include Exception or Stack Trace)**
An exception with the message "Tried to get token using Visual Studio. Access token could not be acquired." is returned with no additional detail.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Update `tokenprovider.json` (at `C:\Users\<username>\AppData\Local\.IdentityService\AzureServiceAuth\tokenprovider.json`) so that the path points to a non-existent file.
2. Create an `AzureServiceTokenProvider` using connection string `RunAs=Developer; DeveloperTool=VisualStudio`.  
3. Attempt to get a token (I used the KeyVaultClient to do so).

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Serivecs.AppAuthentication 1.4.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8
 - IDE and version : N/A

**Comment by isra-fel** [comment]
Thank you for the feedback, we'll see what we can do to improve.

**Comment by nonik0** [comment]
@veleek Sorry for delay in response, but thank you for pointing this out. I am working on this right now, so there will be a fix for this in the next release with a better error message.

**Comment by veleek** [comment]
Thanks @nonik0!

**Comment by anaismiller** [comment]
This have been resolved in the AppAuth 1.6 release
