### ISSUE TITLE
[FEATURE REQ] Add Microsoft.Extensions.Logging.AzureEventHub

### ISSUE THREAD

**Issue by ericstj** [Azure/azure-sdk-for-net#12033]
Moved from https://github.com/dotnet/extensions/issues/1771 opened by @jamesharling

### Is your feature request related to a problem? Please describe.
This is simply an additional logger provider for a popular choice of logging sink.

### Describe the solution you'd like
I would like to be able to pump events raised through `ILogger<T>` to an additional logger provider, that sends the events to an Azure Event Hubs instance.

### Describe alternatives you've considered
There are no alternatives within the M.E.L. ecosystem.

### Additional context
The format of these events should be customizable, but a default formatter shall be provided.

Proposed implementation: https://github.com/dotnet/extensions/pull/1772

cc @pakrym @maryamariyan

**Comment by pakrym** [comment]
Copying my answer from another thread:

> Maybe. We would have to figure out how popular EventHubs are as the log destination.
> Considering that this is the first request of it's kind I'm slightly reluctant to ship a first party implementation just yet.

**Comment by pakrym** [comment]
We haven't gotten more requests for this feature. I don't think we are going to ship it.
