### ISSUE TITLE
[Task] Cleanup code logic in test framework for track 1 back compatibility

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#12041]
This task should be done after finishing track 2 migration, the code in test framework are:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.TestFramework/src/RecordMatcher.cs#L72
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.TestFramework/src/RecordEntry.cs#L21

and related tests code in all projects.

**Comment by allenjzhang** [comment]
AB#4035

**Comment by JimSuplizio** [comment]
Hi @erich-wang, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
