### ISSUE TITLE
[QUERY] GetUserDelegationKeyAsync() authentication failure for Service Client created using connection string

### ISSUE THREAD

**Issue by thargy** [Azure/azure-sdk-for-net#12052]
**Query/Question**
I am writing a Blazor WASM App and using Azure AD B2C to authenticate.  I wish to give each authenticated user access to their own blob container (based on their UserID).  I have successfully authenticated users and can connect to blob storage using a connection string, from the server layer.

However, when I run the following
```chsarp
                key = await _blobServiceClient.GetUserDelegationKeyAsync(
                        DateTimeOffset.UtcNow,
                        DateTimeOffset.UtcNow.AddDays(1),
                        cancellationToken)
                    .ConfigureAwait(false);
```

I get the following error message:
```
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:952e0446-c01e-000d-1131-299d64000000
Time:2020-05-13T14:19:19.3831245Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 952e0446-c01e-000d-1131-299d64000000
x-ms-client-request-id: a3a45f58-0d85-43a1-bf1d-80c01b945d77
x-ms-version: 2019-07-07
x-ms-error-code: AuthenticationFailed
Date: Wed, 13 May 2020 14:19:18 GMT
Content-Length: 421
Content-Type: application/xml
```

Using Fiddler 4, I can see the authorisation appears in the outgoing header, and the same `_blobServiceClient` can successfully be used to create/list containers and get properties etc. so I'm confident the connection string is good.

I've spent a couple of days but hit a dead end.  I've read there's a difference between an account connection (which is presumably what the connection string gives me?) but suggestions to call `GetClient` are deprecated, and instead, the closest I can see is `_blobServiceClient.GetBlobContainerClient()` which returns a `BlobContainerClient` which does not expose `GetUserDelegationKeyAsync()`.

The plan is to pass the `key` to a `BlobSasBuilder` to grant read-only access to the user's container so that the Blazor WASM client can retrieve resources directly.  Whilst writes will stream through the server layer for validation, throttling, etc.  However, I can't get that far as I can't get the `UserDelegationKey`.

The examples show the creation of a new `BlobServiceClient` each time, without using a connection string and instead use a `DefaultAzureCredential`.  I don't want to use that approach if I can avoid it because setting up a user with global access seems like a lot of extra work compared to just using the connection string.  However, is that the recommended approach, and is `GetUserDelegationKeyAsync` not allowed when you are authenticating with the connection string (in which case the error message could do with being a touch more informative as I can't find anywhere that states that is the case).

I am slowly grasping the concepts but many examples show deprecated code and the whole things seems fiendishly overcomplicated for what should be a relatively simple task - providing a read-only URI to an authenticated user's personal container that prevents write access or access to other containers.  (I also will provide a URI to a read-only global container for all users).

Any help would be appreciated, and apologies if I'm obviously doing something dumb.

**Environment:**
 - Azure.Storage.Blobs 12.4.2
 - Visual Studio 16.5.3
 - Host
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by seanmcc-msft** [comment]
Hi @thargy,

The [Get User Delegation Key Rest API](https://docs.microsoft.com/en-us/rest/api/storageservices/get-user-delegation-key#request-headers) only supports AAD authentication.

Could you post your Get User Delegation Key request from Fiddler?

-Sean

**Comment by thargy** [comment]
Hi @seanmcc-msft,

Here's the request (I've obfuscated the actual authorization value though it changes each time):

```
POST https://autofitmeinstorage.blob.core.windows.net/?restype=service&comp=userdelegationkey HTTP/1.1
Host: autofitmeinstorage.blob.core.windows.net
x-ms-version: 2019-07-07
x-ms-client-request-id: 7ac4ffe1-9441-42c0-acba-09781a27cf92
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.4.2 (.NET Core 3.1.3; Microsoft Windows 10.0.18363)
x-ms-date: Wed, 13 May 2020 21:56:47 GMT
Authorization: SharedKey autofitmeinstorage:CDo****************************************=
Request-Id: |81538a6a-49e2cdcac9e655e4.2.
Content-Type: application/xml
Content-Length: 91

<KeyInfo><Start>2020-05-13T21:56:47Z</Start><Expiry>2020-05-14T21:56:47Z</Expiry></KeyInfo>
```

And the response
```
HTTP/1.1 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Content-Length: 421
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 7f1ab7f2-f01e-004a-6371-29420f000000
x-ms-client-request-id: 7ac4ffe1-9441-42c0-acba-09781a27cf92
x-ms-version: 2019-07-07
x-ms-error-code: AuthenticationFailed
Date: Wed, 13 May 2020 21:57:03 GMT

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:7f1ab7f2-f01e-004a-6371-29420f000000
Time:2020-05-13T21:57:04.0579406Z</Message><AuthenticationErrorDetail>Only authentication scheme Bearer is supported</AuthenticationErrorDetail></Error>
```

So does that mean when the `BlobServiceClient` is created with a connection string, there is no way to get a time-bound, container-restricted, read-only URL to supply the Client for direct access?  

What is the suggested alternative, as I don't really want to create a user for every B2C customer and set up their permissions as that sounds onerous, and I don't want the load of read-requests coming through the Server?  Is it best to create a user for the application with full access to the store, and use that to create the service, how do you go about that, is there a tutorial to have the service run as that user?

**Comment by seanmcc-msft** [comment]
Hi @thargy, Get User Delegation Key doesn't work with connection string or Shared Key auth, which explains why you are getting a 403.

If you'd like to create a read-only, time-bounds and container-restricted URL, I'd recommend regular SAS.

```
using Azure.Storage;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Specialized;
using Azure.Storage.Sas;
using System;
using System.Net;
using System.Threading.Tasks;

namespace ConsoleApp3
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string accountName = "";
            string accountKey = "";
            Uri serviceUri = new Uri("");
            StorageSharedKeyCredential sharedKeyCredential = new StorageSharedKeyCredential(accountName, accountKey);
            BlobServiceClient blobServiceClient = new BlobServiceClient(serviceUri, sharedKeyCredential);
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient("mycontainer998");
            PageBlobClient pageBlobClient = containerClient.GetPageBlobClient("mypageblob");
            try
            {
                await containerClient.CreateAsync();
                await pageBlobClient.CreateAsync(1024);

                BlobSasBuilder blobSasBuilder = new BlobSasBuilder()
                {
                    BlobContainerName = containerClient.Name,
                    StartsOn = DateTimeOffset.UtcNow.AddMinutes(-5),
                    ExpiresOn = DateTimeOffset.UtcNow.AddDays(1),
                    IPRange = new SasIPRange(IPAddress.None, IPAddress.None),
                    Protocol = SasProtocol.None
                };
                blobSasBuilder.SetPermissions(BlobSasPermissions.Read);
                BlobUriBuilder sasUriBuilder = new BlobUriBuilder(containerClient.Uri)
                {
                    Query = blobSasBuilder.ToSasQueryParameters(sharedKeyCredential).ToString()
                };

                // Now we have the container SAS Uri we can use to contruct blob client for blobs in the container.
                Uri containerSasUri = sasUriBuilder.ToUri();

                BlobUriBuilder blobUriBuilder = new BlobUriBuilder(containerSasUri)
                {
                    BlobName = pageBlobClient.Name
                };

                PageBlobClient sasPageBlob = new PageBlobClient(blobUriBuilder.ToUri());

                await sasPageBlob.GetPropertiesAsync();
            }
            finally
            {
                await containerClient.DeleteAsync();
            }
        }
    }
}
```

**Comment by thargy** [comment]
Thank you @seanmcc-msft, I'll give that a go when I get back to that area of functionality.
