### ISSUE TITLE
[BUG] DbContext Disposing when MessageSender.SendAsync is called with await

### ISSUE THREAD

**Issue by davemanton** [Azure/azure-sdk-for-net#12050]
**Describe the bug**
Please provide the description of issue you're seeing.

We are trying to use Azure ServiceBus to send messages to other systems.  We have a system where to ensure delivery we save the message in a database table and if it's sent successfully we add a flag to confirm sending into that table.  If unsuccessful another system cleans it up later.

When messages are being sent using the MessageSender.SendAsync method which we have awaited we are finding that our DbContext is disposed of immediately after the message sending meaning we are unable to confirm the message has been sent and save into the database.

**Expected behavior**
What is the expected behavior?

MessageSender.SendAsync(string message) should return when awaited and allow continued execution without disposal of any of dependency injected resources, particularly DbContext

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
When the request is made through MessageSender.SendAsync and is awaited, we find the DbContext is disposed before the end of the request.  This means we cannot use it to save a confirmation that the message was sent.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

We create a message sender using the following code

```
public IMessageSender CreateMessageSender(string topicPath)
        {
            var name = _serviceBusConnectionStringProvider.ReadOnlyConnectionString + topicPath;

            if (_activeMessageSenders.ContainsKey(name)) return _activeMessageSenders[name];

            var messageSender = new MessageSender(_serviceBusConnectionStringProvider.ReadOnlyConnectionString, topicPath);

            _activeMessageSenders.TryAdd(name, messageSender);

            return _activeMessageSenders[name];
        }
```

This is being consumed by the following method which sends the message

```
public async Task<bool> Send(OutboxMessage outboxMessage)
        {
            if (outboxMessage == null)
                throw new ArgumentNullException(nameof(outboxMessage), "OutboxMessage cannot be null");

            try
            {
                var serviceBusMessage = new Message(Encoding.UTF8.GetBytes(outboxMessage.Body));

                var client = _serviceBusFactory.CreateMessageSender(outboxMessage.Topic);
                
                await client.SendAsync(serviceBusMessage);
                
                return true;

            }
            catch (Exception exception)
            {
                _telemetryClient.TrackException(exception.InnerException);
                return false;
            }
        }
```

There is further code which is used to save the confirmation of a message which waits for this to return true in the normal fashion.

Nothing is caught in the exception, however the dbcontext immediately disposes after the client.SendAsync method completes.  We have confirmed this by adding a dispose method to our dbcontext and we see the breakpoint hit in debug mode as soon as the client.sendasync method is called.

This bug is intermittent but happens with relative regularity.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]
Using Microsoft.Azure.ServiceBus Version 4.0.0
.net core 3.0
This happens when working locally on windows 10 professional machines or hosted in an azure windows app service

**Comment by nemakam** [comment]
@davemanton - Is there a repro that you could provide that has DBContext? How does DBContext and MessageSender relate to each other?

**Comment by axisc** [comment]
@davemanton  - Is this still an issue? 
please reopen (or reference this issue in a new one) when you have the repro.
