### ISSUE TITLE
[BUG] Handle 504 Gateway Timeout with status polling for long-running operation

### ISSUE THREAD

**Issue by xccc-msft** [Azure/azure-sdk-for-net#12065]
**Describe the bug**
The customer used Fluent SDK to export their sql database. The `exportTo` operation is long-running. When polling the status, they got 504 response from ARM. Inside the http client, it threw TaskCanceledException when catching 504.

**Expected behavior**
The ClientRuntime should have a scenario to handle 504 during status polling, e.g. verify if the failure comes from polling by request URI and retry the polling as the operation is running on the server already. 

**Actual behavior (include Exception or Stack Trace)**
No retry happened, it just threw the exception.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. To execute a long-running operation like `exportTo`.
2. Mock 504 response during status polling using tool like Fiddler.

**Environment:**
Microsoft.Rest.ClientRuntime: 3.3.18

**Comment by xccc-msft** [comment]
As discussed with Alex, they will not make any changes on ClientRuntime at this point. They would plan to support this in new Azure.Core library.

For now, the workaround could be:
```
ISqlManager sqlManager = SqlManager.Configure()
                    .WithRetryPolicy(new RetryPolicy(new HttpStatusCodeErrorDetectionStrategy(), retryCount))
                    .Authenticate(credentials, credentials.DefaultSubscriptionId);
```
The value of `retryCount` would determine how many times to retry when getting invalid response like 504. In another word, the polling could be resumed once the `retryCount` is large enough.

**Comment by AlexGhiondea** [comment]
Thanks @xccc-msft for the workaround! Closing the issue for now.
