### ISSUE TITLE
Azure QnA maker fails to create a knowledge base by raising ExtractionFailure error code

### ISSUE THREAD

**Issue by Arash-Sabet** [Azure/azure-sdk-for-net#12075]
**Describe the bug**
Azure QnA Maker SDK fails to create knowledgebase from a URL powered by an Azure Http-Triggered function while the function is publicly available and it only accepts GET requests. The response of the function is a pure string return by "**return new OkObjectResult(responseString)**"

**Expected behavior**
Knowledgebase should be created from the given URL.

**Actual behavior (include Exception or Stack Trace)**
The following error message is produced:

> Unsupported / Invalid url(s). Failed to extract Q&A from the source

**To Reproduce**
Run the following code snippet in a console application:

```
var createKbDto = new CreateKbDTO
        {
            Name = request.Name,
            QnaList = new List<QnADTO>(),
            Urls = new List<string>
            {        "https://caccea77.ngrok.io/api/jobdescription/facade/2034/43D672205B3106BE3273C60FE423C632"
            }
        };

        var createKb = await client.Knowledgebase.CreateAsync(createKbDto);
        var createdOp = await MonitorOperationAsync(client, createKb);
        return GetKbId(createdOp);
```
**Environment:**
 - Microsoft.Azure.CognitiveServices.Knowledge.QnAMaker" Version="1.1.0" 
 - IDE and version : Visual Studio 16.5.4
- Environment:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100-rc1-014190 [C:\Program Files\dotnet\sdk]
  3.1.100-preview3-014645 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0-rc1.19457.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0-preview3.19555.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0-rc1-19456-20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0-preview3.19553.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by Arash-Sabet** [comment]
@dfulcer 
Hi Dean,
To be able to reproduce the problem please feed the following URL to QnAMaker's SDK:

https://caccea77.ngrok.io/api/jobdescription/facade/2034/43D672205B3106BE3273C60FE423C632

Feeding this URL to QnAMaker portal results in the same error message too:

> Unsupported / Invalid url(s). Failed to extract Q&A from the source

Does the web content produced by the URL above lack anything that QnAMaker expects it? What causes QnAMaker to reject the content?

/cc @milad-simcoeai @miladghafoori

**Comment by Arash-Sabet** [comment]
@dfulcer @jsquire 

Any updates on this ticket? The application insights is quite silent in terms of logging what goes wrong.


/cc @milad-simcoeai

**Comment by jsquire** [comment]
I am just the source of initial triage in this case.  Unfortunately, that means that I don't have any insight to offer.

**Comment by Arash-Sabet** [comment]
@jsquire just wondering, who's the lead on QnA Maker to have them engaged a quickly as possible? It's a showstopper and I'm sure there are or will be other folks experiencing the same problem.

**Comment by jsquire** [comment]
With regret, I do not know.  This is not a library which the Azure SDK team owns at this point.  The QnA Maker service team will need to assist, but beyond that I don't have insight.  Each Azure service team has their own triage process once an issue has been identified and tagged.  In this case, it would appear that they've identified @dfulcer as the point of contact.

If this is a show stopping issue, I'd recommend opening an [Azure support ticket](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-troubleshooting-support-howto).  That will be a more formal and expedient route for support with a proper escalation path.  That would ensure that someone is actively working to engage the proper folks for attention.

My apologies that I don't have a better answer for you.

**Comment by rokulka** [comment]
This thread has came to the team now :(
This is related to the QnAMaker extraction logic, not specific to SDK. As per the error, the provided URL content didn't support our extraction standard to generate any QnAs. However, I see that the provided URL doesn’t exist anymore. Please close the thread if it's too late, or share a valid URL so that we can investigate. Thanks!
