### ISSUE TITLE
[Design] Consider removing default value for useTrainingLabels parameter

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#12079]
From arch board notes:

Could useTrainingLabels be made a required field, rather than optional with default:false?

FOLLOW-UP with service team on what is consistent with REST, expected customer behavior, etc

**Comment by jeremymeng** [comment]
Per discussion in internal Teams channel we will make `useTrainingLabels` parameter required for preview.3

**Comment by maririos** [comment]
Thanks for the update Jeremy!
