### ISSUE TITLE
Create automation connection fails with bad request exception.

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#1208]
I have using the ConnectionOperationsExtensions.CreateAsync method to create a new connection in an Azure Automation account. I am supplying all of the required values for the ConnectionCreateParameters parameter including the dictionary of connection field values.

The method invariably fails with a BadRequest exception with the message "Argument 'ConnectionFieldDefinitionData.Value' cannot be empty".

**Comment by markcowl** [comment]
@davecader Thank you for the report, assigning to the automation team to investigate

**Comment by shahabhijeet** [comment]
@davecader please open a new issue if the problem still exists/repros.
