### ISSUE TITLE
[FEATURE REQ] Make ClientCertificateCredential disposable and dispose of the underlying X509Certificate2

### ISSUE THREAD

**Issue by ohadschn** [Azure/azure-sdk-for-net#12080]
**Library or service name.**
`Azure.Identity`
 
**Is your feature request related to a problem? Please describe.**
`ClientCertificateCredential` accepts a `X509Certificate2` and keeps it as an internal property: 
https://github.com/Azure/azure-sdk-for-net/blob/727ab08412e60394b6fea8b13cac47d83aca1f3b/sdk/identity/Azure.Identity/src/ClientCertificateCredential.cs#L33

However `X509Certificate2` and `ClientCertificateCredential`, which burdens the developer with having to dispose of one object only when they're done using another.

Making `ClientCertificateCredential` disposable, allowing the developer to dispose of the underlying `X509Certificate2` would prevent the need to construct custom holder objects.

**Comment by schaabs** [comment]
@ohadschn Thanks for the feedback, and for creating this issue. We'll investigate the impact making `ClientCertificateCredential` disposable, and update the issue once we have an idea of how and when we'll address this.

**Comment by christothes** [comment]
After some discussion (see the linked PR), we are not planning to implement this feature. The primary reason is that X509Certificate2 resources will be released when its finalizer runs. In addition, this change would require adding the `IDisposable` interface to a number of other credential classes which may use the `ClientCertificateCredential` under the covers.

Please feel free to comment if this is not an acceptable solution for your scenario.

**Comment by ohadschn** [comment]
Relying on the finalizer is problematic because you don't know when it will get called. Even if we assume it will take place by process shutdown so no actual leak takes place, we don't what would happen during program execution. One can easily show a scenario where you use a cert, then try and use the cert again right after and fail because it wasn't released (at least I'm assuming that can happen when you try to use the same cert twice like that).

For sure it's not the end of the world for us to wrap it under an `IDisposable` of our own, but what's the problem with adding 
`IDisposable` to other classes? They'd have a pretty simple `IDisposable` implementation that simply delegates the call to the underlying credentials. Worst case, users don't wrap their usage under `using` and things remain the same as they are today, it's not like it's a breaking change...

**Comment by christothes** [comment]
@ohadschn - Thanks for the feedback. If we were to make this change, the disposal would only happen when the certificate was loaded by file path.
https://github.com/Azure/azure-sdk-for-net/blob/e542d6b5208be52dc27005ccfa030dc8f247b755/sdk/identity/Azure.Identity/src/ClientCertificateCredential.cs#L54

If it was supplied directly, we'd assume that the caller owns the lifetime of the object.
https://github.com/Azure/azure-sdk-for-net/blob/e542d6b5208be52dc27005ccfa030dc8f247b755/sdk/identity/Azure.Identity/src/ClientCertificateCredential.cs#L88

Considering there is minimal risk of a resource leak and full control of the certificate disposal is possible by supplying it directly via the constructor, we'll err on the side of no change for now.

**Comment by ohadschn** [comment]
Actually my initial feature request was for the case where the certificate was supplied directly in the ctor. We have code that looks like this, and I imagine many others do:
```cs
ClientCertificateCredential GetCredential()
{
   var cert = new X509Certificate2("MyCertPath");
   return new ClientCertificateCredential("myTenantId", "myClientId", cert);

   //or equivalently:
   return new ClientCertificateCredential("myTenantId", "myClientId", "MyCertPath");
}
```

The point is, I assume in the vast majority of the cases, the caller just wants the creds and they don't care about the `X509Certificate2` - only reason the latter exists is because `ClientCertificateCredential` needs it.

In such a case, as in the method above, I don't want to manage two separate classes and make sure that whenever I dispose of one I remember to dispose of the other.

To that end, we created an IDisposable wrapper class on top of `ClientCertificateCredential`, so it's not the end of the world, just nice if it was built in the infra.

As for allowing the case of the caller managing the cert, you could have a flag that designates ownership (similar to `disposeHandler` in the `HttpClient` ctor), which can default to the current behavior (i.e. `false`). I concede that might add a bit of complication, so in the end it's up to you to consider the tradeoff.
