### ISSUE TITLE
[text analytics] test issues

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-net#12081]
- [ ] only checking whether passing in null for docs to detect language fails ([ex1](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/tests/TextAnalyticsClientTests.cs#L56), [ex2](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/tests/TextAnalyticsClientTests.cs#L78)

**Comment by maririos** [comment]
wow. Thanks Isa!!!!
