### ISSUE TITLE
[BUG] very slow with ExistsAsync()/Exists/UploadBlobAsync/UploadBlob 

### ISSUE THREAD

**Issue by vnguyenau** [Azure/azure-sdk-for-net#12095]
Intermittent slow (19 seconds to 1.7 mins) with simple check existed
var existing = blobContainerClient.ExistsAsync().ConfigureAwait(false).GetAwaiter().GetResult();
I tested with ExistsAsync, Exist with container and blob. All happens the same. Even UploadBlob and UploadBlobAsync etc.
Example : 
The message send from application at 2020-05-15T05:32:07.5983188Z
In storage log  at 2020-05-15T05:33:50.3999176Z
There is a gap 05:32:07.5983188Z and 05:33:50.3999176Z

Log from storage
1.0;2020-05-15T05:33:50.3999176Z;GetContainerProperties;Success;200;2;2;authenticated;stagingcallnca;stagingcallnca;blob;"https://stagingcallnca.blob.core.windows.net:443/clientdata?restype=container";"/stagingcallnca/clientdata";c6450079-301e-000e-317a-2adaaa000000;0;123.208.53.121:1805;2019-07-07;509;0;438;0;0;;;"&quot;0x8D7EA6EBF41C380&quot;";Monday, 27-Apr-20 05:49:27 GMT;;"azsdk-net-Storage.Blobs/12.4.2 (.NET Core 3.1.4; Microsoft Windows 10.0.18363)";;"3df732b3-5dde-4412-82b2-38642cfb61c9"

![slow1](https://user-images.githubusercontent.com/63837604/82019709-11d63580-96cb-11ea-8234-fda9e33640fc.jpg)

**Expected behavior**
I expect it very fast as normal but it took 19 seconds.

**Actual behavior (include Exception or Stack Trace)**
- just very slow with Azure.Storage.Blobs 12.4.2
- failed with Microsoft.Azure.Storage.Blob
- I did pcap capture and see a lots TCP re-tranmission between my ip address and blob ip address. At the end it has a RST TCP.
**To Reproduce**
hit the api method every 5 seconds for 1-2 hours then the issue will happens 1-2 time each hours and very randomly.
**Environment:**
Azure.Storage.Blobs 12.4.2 (take long time)and even with Microsoft.Azure.Storage.Blob (show failed error)
 - .NET Core 3.1 Kubernetes Linux 
-  Also Run with Visual Studio 2019 windows 10.

**Code **
This is the code run as API async method
try
            {
                var blobContainerClient = new BlobContainerClient(conn, containerName);
                var existing = blobContainerClient.ExistsAsync().ConfigureAwait(false).GetAwaiter().GetResult();
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

**Comment by amnguye** [comment]
Hi,

Thanks for submitting this issue. Could you enable verbose logging on the sdk?

https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging

**Comment by vnguyenau** [comment]
Console log highlight :  See more details in attachment
[11:05:27:829][Informational] Request [adc00c07-eca3-4287-8af3-5218009ff1ea] 
[11:05:49:548][Informational] Response [adc00c07-eca3-4287-8af3-5218009ff1ea] 200 OK (21.7s)
Log from Azure storage blob log :
1.0;2020-05-19T01:07:10.5383377Z;GetContainerProperties;Success;200;1;1;authenticated;stagingcallnsg;stagingcallnsg;blob;"https://stagingcallnsg.blob.core.windows.net:443/clientdata?restype=container";"/stagingcallnsg/clientdata";faeedb2d-301e-0034-5979-2d7604000000;0;123.208.53.39:3299;2019-07-07;509;0;438;0;0;;;"&quot;0x8D7F6FE3286CFDD&quot;";Wednesday, 13-May-20 05:26:32 GMT;;"azsdk-net-Storage.Blobs/12.4.2 (.NET Core 3.1.4; Microsoft Windows 10.0.18363)";;"adc00c07-eca3-4287-8af3-5218009ff1ea"


![Capture](https://user-images.githubusercontent.com/63837604/82279217-51549880-99cf-11ea-9ef9-5e280e3a85e9.JPG)
[sdklog.txt](https://github.com/Azure/azure-sdk-for-net/files/4647952/sdklog.txt)

**Comment by vnguyenau** [comment]
Also my application made request cross region. I don't see the issue when made blob request in same region. I don't know if it is an issue.

**Comment by amnguye** [comment]
Hi,

I should have been more specific. Could you enable logging with the SDK, i.e.
```
using AzureEventSourceListener listener = new AzureEventSourceListener((e, message) =>
    {
        // Only log messages from Azure-Core event source
        if (e.EventSource.Name == "Azure-Core")
        {
            Console.WriteLine($"{DateTime.Now} {message}");
        }
    },
    level: EventLevel.Verbose);
```
around your main application the upload is happening. It would be good to see in the log the fast transactions and the slower transactions, to see if this is an SDK issue.

However by the service logs you are providing, it seems like the question you have isn't related to the SDK, am I correct?

**Comment by amnguye** [comment]
Looks like this a service storage side question due to the screenshots and not an SDK issue. The request made into a region could be the reason why it's slower than in the same region.

**Comment by vnguyenau** [comment]
The issue intermittent I could not tell because of SDK or because of Azure Storage service.

**Comment by amnguye** [comment]
Using your second screenshot as an example. Your concern in the 21.7 seconds right? This monitor you are using is tracking how long it takes the transaction is taking since the request got to storage and when it left with a response (end to end transaction). So it spends 21.7 in the service.

This isn't tracking how long it is taking with the SDK. So based on your logs, it looks like the source of the delay is in the service.

Unfortunately this is not the place an issue against the service. I will update this issue with where to submit your issue/question about the intermittent delay in the service.

Thanks for your patience.

**Comment by vnguyenau** [comment]
Thank you for quick response. I think you are right. 
Actually the blob SDK completed its task by sent out the request and created log and no latency in this phase. The delay should be something with Blob service or before it reaches the Blob service. However, blob storage log shows the time it process which is very low latency(few milliseconds). Also there is no latency when request at same region. Therefore the networking issue with cross region should be the thing.

**Comment by amnguye** [comment]
Hi,

Sorry for the delay. What are the regions you are sending the request to and from?

Looks like this is not a service bug.

And from what you said about the network delay

> I did pcap capture and see a lots TCP re-tranmission between my ip address and blob ip address. At the end it has a RST TCP.

The SDK and storage service cannot perform consistently with network delays between ip addresses, so this might be as expected with the re-tranmission between ip addresses.

**Comment by vnguyenau** [comment]
I am sending request from AU to SG,CA,US,BR. They all have same issue. The Azure networking and Blob Storage team said it is an expected behaviour and advise to use private endpoint.  
Thanks for your help. I think we an close the ticket here :)
