### ISSUE TITLE
[BUG] Event Hub Processor Host through Azure Function Extension starves two partitions regularly

### ISSUE THREAD

**Issue by icecog** [Azure/azure-sdk-for-net#12096]
**Describe the bug**
I'm using the Event hub trigger in Azure functions and I'm seeing some partitions getting starved of consumption.
A lease is set up on a partition, and then nothing happens until that lease expires at which point a new consumer will setup the lease and start consuming the data. This can take up to an hour to happen.

**Expected behavior**
I expect all partitions to get the same amount of love, give or take the configuration on the Processor Host.

**Actual behavior (include Exception or Stack Trace)**
The problem is that the Azure function consistently starves 2 partitions, a lease is taken and then they are just left there until the lease breaks (an hour or something later).
Then two other partitioned are left to be starved. 
Whenever I redeploy the function it grabs all of them, but then soon starts to ignore two of them.
It takes about 2 minutes for this problem to start.

I'm running an Azure function (v3 - project config below) that gets data from an event hub with 16 partitions. This is running on a App Service Plan with around 11 nodes (plenty of CPU to spare), but I've upped the node count to 16 now, with no difference in behavior.

I've redeployed the function in question, I've messed with every (the 3) setting in the host.json, I've even cycled the machines on the app service plan (set scale to 1 and then to 11 again).  I've even tested creating a new consumer group, but the problem persists.

I have a second function that doesn't show this issue to the same degree but even though I've tried my best to make them operate the same the issue remains in this function. 
So my guess is that there is something in the extension that's causing this - but maybe you guys see something else. 

Blow are pictures of the the event hub checkpoints as well as what the graph of delay from message enqueued on the event hub looks like.

![partition_checkpoints_startup](https://user-images.githubusercontent.com/6333083/82012396-1e7d6e00-9678-11ea-9f1c-9f159b5f3adb.png)
![partition_checkpoints_starvation_starting](https://user-images.githubusercontent.com/6333083/82012403-23422200-9678-11ea-9cc1-a41d9e47550a.png)
![partition_checkpoints_starvation](https://user-images.githubusercontent.com/6333083/82012410-263d1280-9678-11ea-9a05-90ed03c5b4ef.png)
![event_processing_delays (seconds)](https://user-images.githubusercontent.com/6333083/82012415-289f6c80-9678-11ea-81e8-9ac10abb624b.png)
(Y-axis in seconds)
```
var lastTimestamp = (DateTime)eventStream.Last().SystemProperties["x-opt-enqueued-time"];
var lastDelay = DateTime.UtcNow - lastTimestamp;
```

**To Reproduce**

I'm running the following (with some internal packages removed)

```<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GeoCoordinate.NetCore" Version="1.0.0.1" />
    <PackageReference Include="GeoLibrary" Version="1.1.0" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.14.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.1.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.7" />
    <PackageReference Include="TaskTupleAwaiter" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\PublishProfiles\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Service\Service.csproj" />
  </ItemGroup>
</Project>
```

And here is the host.json config
```
{
  "extensions": {
    "eventHubs": {
      "batchCheckpointFrequency": 1,
      "eventProcessorOptions": {
        "maxBatchSize": 64,
        "prefetchCount": 256
      }
    }
  },
  "version": "2.0"
}
```

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.EventHub.Processor Version 3.0.0 via Microsoft.Azure.Extensions.EventHub V 4.1.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure Function V3 running on windows, Runtime version : 3.0.13353.0, .Net Core 3.0
 - IDE and version : Visual Studio Version 16.5.4

Here is a link to the bug I've reported with azure-functions-eventhubs-extension:
[Issue 63](https://github.com/Azure/azure-functions-eventhubs-extension/issues/63)

**Comment by icecog** [comment]
It turns out it was the damned staging slot that was taking up the partition leases, I'm not sure how I'll solve it, but first step is to avoid using a arm template from 2015 to provision it...
Even after removing the slot in its entirety the problem persisted for a little bit - or it may have been my imagination. But eventually the production slot started firing on all cylinders.

**Comment by jsquire** [comment]
//cc: @serkantkaraca, @JamesBirdsall, @ellismg

**Comment by AlexGhiondea** [comment]
@icecog it sounds like this is not longer an issue.

**Comment by icecog** [comment]
Does it sound like it?
I only raised it in 2020.
No idea, no longer work with Event Hub.

**Comment by serkantkaraca** [comment]
@icecog this sounds like a Storage Gen2 lease management issue. Let us know if you still want to investigate.

**Comment by icecog** [comment]
As this doesn't affect me any more I can't really decide that. So I'll leave it to you guys as experts in the system

**Comment by serkantkaraca** [comment]
Your configuration is pretty standard and I don't think the issue is related to SDKs being used or the host configuration. 

Any chance your storage account may have been enabled with hierarchical namespaces, aka., Storage Gen2?

**Comment by icecog** [comment]
Since creating this is ticket I've left the company where that issue arose, so what information I have is already in the ticket above, I can't really be more helpful than that.

If that's not enough information to go on then the only option is to close this ticket. 
Feel free to do as you see fit
