### ISSUE TITLE
Uri.AbsoluteUri should be used instead of Uri.ToString()

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#12102]
There are multiple customer-reported issues where the root cause is incorrect usage of `Uri.ToString()`:

* #11564
* #12069

The problem is `Uri.ToString()` **un-escapes** the URL, so `http://foo.com/image%201.jpg` is converted to `http://foo.com/image 01.jpg` which is no longer a valid URL.  The API `Uri.AbsoluteUri` should be used instead.

All instances of `Uri.ToString()` in our codebase should be reviewed, and most or all should be convered to `Uri.AbsoluteUri`.  `Uri.ToString()` should only be used to intentionally un-escape a URL, which should be rare.  Even if a URL were included in an error message, I think the escaped URL would be preferred.

I recommend adding an analyzer rule to prevent calls to `Uri.ToString()`, using `Microsoft.CodeAnalysis.BannedApiAnalyzers`.

One complication is relative URIs, where `Uri.AbsoluteUri` throws.  If we need to get an escaped representation of a relative URI, we can use `Uri.EscapeUriString(relativeUri.ToString())`.

**Comment by kasobol-msft** [comment]
I also found plenty of this in https://github.com/Azure/azure-sdk-for-net/pull/21424 where issue got discovered initially.

**Comment by kasobol-msft** [comment]
Given how tempting ToString() is and how easy it is to get it wrong I suggest to prioritize this work.

**Comment by pakrym** [comment]
I started a branch https://github.com/Azure/azure-sdk-for-net/compare/main...pakrym%3Apakrym%2FBanned-apis?expand=1

**Comment by kasobol-msft** [comment]
@pakrym can this be done service by service? to avoid big revolution.

**Comment by kasobol-msft** [comment]
i.e. if you can set this up targeting just one of the packages or services I'd be happy to take over adopting this for storage.

**Comment by pakrym** [comment]
Yes if you change 
```
    <PackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" PrivateAssets="All" />
```
to
```
    <PackageReference Condition="'$(EnableBannedApiAnalyzers)' == 'true'" Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" PrivateAssets="All" />
```

And set BannedApiAnalyzers to true in storage it'll be scoped.

**Comment by pakrym** [comment]
I'll look into merging that PR today.
