### ISSUE TITLE
Remove BCL Dependency

### ISSUE THREAD

**Issue by jabeerni** [Azure/azure-sdk-for-net#1212]
Would it be possible to remove the dependency on BCL? The Azure SDK 2.4 has a bug in it which loses the web.configs if built with BCL. Since 4.5 apps don't need BCL, it would be great not to take this dependency.

**Comment by azurecompliance4** [comment]
We are in the process of migrating to the [AutoRest](https://github.com/azure/autorest) generator. The BCL dependency will only be pulled in with the downlevel NuGet packages.
