### ISSUE TITLE
[BUG] building a project using Azure devops and deploy it to azure App service results in error at Azure.Core.Pipeline related to storage sdk

### ISSUE THREAD

**Issue by MegoCs** [Azure/azure-sdk-for-net#12127]
**Describe the bug**
out of nowhere, and everything is fine. we started to have 403 from storage logs in application insights when we call our APIS to upload a file to blob storage using old storage SDK Windows .storage without making any change.
we didn't get a real answer to why does that happen. some people mentioned updated headers related to azure AI and exclude storage domain from tracked dependencies and the config was actually excluding storage dependency. and that 403 occurred suddenly with a rate of 60% of requests gets 403.
we decided to update the SDK we are using to the latest storage SDK 12.4.2.0, the change worked just fine. at our machine we are using .Net Framework 4.7.2 for class libraries and web APIS.
publishing the APIs project to azure app service also worked fine.
running it through azure DevOps and release we started to observe a new kind of exception at application insights related to Azure.Core 

> System.IO.FileLoadException

```
System.AggregateException:
System.IO.FileLoadException:
   at System.Threading.Tasks.ValueTask.ThrowIfCompletedUnsuccessfully (System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted (Azure.Core, Version=1.2.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
   at Azure.Core.Pipeline.RequestActivityPolicy+<ProcessAsync>d__9.MoveNext (Azure.Core, Version=1.2.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
```
```
failed methods:
Azure.Core.Pipeline.TaskExtensions.EnsureCompleted
Azure.Core.Pipeline.ResponseBodyPolicy.Process |  
Azure.Core.Pipeline.RequestActivityPolicy.Process |  
Azure.Core.Pipeline.HttpClientTransport.Process |  

```
all of these methods are failing right now on azure app service while working on my local machine
the exception message is 

> Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) 

[Application Insights logs ](https://1drv.ms/u/s!AgZuXstcH8UK5X0kkpNwlcOi6g27?e=R4sIfD)

**Expected behavior**
calling an azure SDK functions works just fine

**Actual behavior (include Exception or Stack Trace)**
calling any API that uses Storage SDK v 12.4 results in an error with file not found

**To Reproduce**

1. add azure storage SDK to .net API project. 
2. use azure DevOps to publish the app to azure app service.
3. call any API that uploads a file to blob

**Environment:**
 - Azure.Storage.Blobs 12.4.2.0 
 - Hosting platform Azure AppService .NET Framework 4.7
 - IDE and version : Visual Studio 16.5.4

**Comment by MegoCs** [comment]
just opened in a wrong repo

**Comment by jsquire** [comment]
//cc: @pakrym

**Comment by pakrym** [comment]
Seems something in you dependency graph is downgrading the `System.Runtime.CompilerServices.Unsafe` assembly version (this is a somewhat popular problem https://nickcraver.com/blog/2020/02/11/binding-redirects/)

What other packages do you depend on outside Azure SDKs?

**Comment by MegoCs** [comment]
actually I fixed it by manually updating
System.Runtime.CompilerServices.Unsafe to the latest version at
the class library and web API project.
that solved my problem
