### ISSUE TITLE
Flaky build: Failed while installing version: 3.1.100 at path:

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#12120]
```
Detecting OS platform to find correct download package for the OS.
/home/vsts/work/_tasks/UseDotNet_b0ce7256-7898-45d3-9cb5-176b752bfea6/2.169.1/externals/get-os-distro.sh
Primary:linux-x64
Legacy:ubuntu.18.04-x64
Detected platform (Primary): linux-x64
Detected platform (Legacy): ubuntu.18.04-x64
Downloading: https://download.visualstudio.microsoft.com/download/pr/d731f991-8e68-4c7c-8ea0-fad5605b077a/49497b5420eecbd905158d86d738af64/dotnet-sdk-3.1.100-linux-x64.tar.gz
##[error]Failed while installing version: 3.1.100 at path: /opt/hostedtoolcache/dotnet with error: Could not download installation package from this URL: https://download.visualstudio.microsoft.com/download/pr/d731f991-8e68-4c7c-8ea0-fad5605b077a/49497b5420eecbd905158d86d738af64/dotnet-sdk-3.1.100-linux-x64.tar.gz Error: Error: certificate has expired
Finishing: Use .NET Core sdk 3.1.100

```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=394547&view=logs&jobId=b08a78d6-c9ce-53c1-53b1-9a5d436f78f6&j=b08a78d6-c9ce-53c1-53b1-9a5d436f78f6&t=05d13a84-370b-58cf-019b-9a3a12c3c6fe

cc @weshaggard @chidozieononiwu

**Comment by weshaggard** [comment]
We have an issue filed for this in the DevOps task https://github.com/microsoft/azure-pipelines-tasks/issues/12613.

**Comment by weshaggard** [comment]
@chidozieononiwu lets see what options we have to potentially by-pass this task and setup the correct version on the path, or maybe we can just rely on the global.json configuration to pick the correct version (assuming it is already on the image).

**Comment by chidozieononiwu** [comment]
Yes we can specify sdk version in globals.json. I don't think we need to use any of the net Core Installer tasks as the version are already installed on the agents. Here is a job I ran without using them https://dev.azure.com/azure-sdk/internal/_build/results?buildId=509589&view=results
I wonder if we also have to set `RuntimeFrameworkVersion` property explicitly.

**Comment by weshaggard** [comment]
I think we still need to set the RuntimeFrameworkVersion as I don't think we can easily control that with global.json.

Can you also do a test that verifies if the version of the SDK we specify in global.json isn't on the machine that it fails correctly?

**Comment by chidozieononiwu** [comment]
Yes, it will throw an error if the correct sdk version is not found. 
`A compatible installed .NET Core SDK for global.json version [3.1.301] from [C:\Git\azure-sdk-for-net\global.json] was not found`

**Comment by weshaggard** [comment]
As for whether or not the task caches the tools I found https://github.com/microsoft/azure-pipelines-tasks/issues/10405 which states it does cache the tools but only if they were downloaded from that task. It currently does not locate and use any pre-installed tools on the image.
