### ISSUE TITLE
[QUERY] StorageCredentials replacement

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#12132]
**Query/Question**

Storage SDK v11 had [`StorageCredentials`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.auth.storagecredentials?view=azure-dotnet) that could work with SAS key, storage key/value and tokens (`TokenCredentials`). What's the equivalent replacement?

With SDK v12, I either have to explicitly call constructors with `StorageSharedKeyCredential` or `TokenCredential`.

**Comment by amnguye** [comment]
Hi,

You would have to explicitly call the constructors depending on the way you want to authenticate to your storage account, there's currently no equivalent replacement.

@seanmcc-msft Correct me if I'm wrong about this.

**Comment by SeanFeldman** [comment]
After looking a bit more into what this means, I have to admit that the decision not to provide an abstraction to encapsulate Storage credential in v12 the way it was done before has an impact on what end-users have to handle. With `StorageCredentials` it was possible to handle security and construct clients/objects necessary for work by customers providing a connection string, SAS Uri, key Name/Value pair, or Managed Identity. Now, I need to keep and managed these 4 options.

**Comment by SeanFeldman** [comment]
The migration from v11 to v12 is somewhat confusing. Authentication implementation has changed substantially. A migration guide could have helped. The issue is raised here: https://github.com/Azure/azure-sdk-for-net/issues/12106
