### ISSUE TITLE
[FEATURE REQ] Support sendX5c in ClientCertificateCredential to allow SubjectName+issuer validation

### ISSUE THREAD

**Issue by ohadschn** [Azure/azure-sdk-for-net#12130]
**Library or service name.**
`Azure.Identity`
 
**Is your feature request related to a problem? Please describe.**
When requesting a token via `AuthenticationContext.AcquireTokenAsync` (in the `Microsoft.IdentityModel.Clients.ActiveDirectory` assembly), there are [overloads that accept the sendX5c parameter](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.authenticationcontext.acquiretokenasync?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_AuthenticationContext_AcquireTokenAsync_System_String_Microsoft_IdentityModel_Clients_ActiveDirectory_IClientAssertionCertificate_System_Boolean_): 

> This parameter enables application developers to achieve easy certificates roll-over in Azure AD: setting this parameter to true will send the public certificate to Azure AD along with the token request, so that Azure AD can use it to validate the subject name based on a trusted issuer policy. This saves the application admin from the need to explicitly manage the certificate rollover (either via portal or powershell/CLI operation)

This is critical for auto rotation scenarios, where you have your cert auto-renewed in KeyVault and you want your certs to maintain their access to their AAD apps following such renewals.

There is currently no way that I can tell so specify this parameter in `Azure.Identity`'s `ClientCertificateCredential`, forcing users to drop to the lower `AuthenticationContext` level.

**Comment by schaabs** [comment]
@ohadschn Thanks for filling this issue. Adding support for SubjectName / Issuer authentication with the `ClientCertificateCredential` is currently on our backlog. While support for this did not make it into our current round of previews for the Azure.Identity library, I expect this will be one of the first features we work on after we GA what is currently in preview. I hope to have at least a preview of SubjectName / Issuer support ealry this fall. I'll update this issue once we have more information available.

**Comment by asranja** [comment]
@schaabs Is there a way we can create AzureCredentials from an access token ? If it was possible, we could fetch the access token using ADAL (sending sendX5c:true) and use it to create the credentials.

**Comment by JackXuCN** [comment]
Use the solution here before Azure.Identity support SendX5c [https://github.com/Azure/azure-sdk-for-net/issues/12864#issuecomment-669291729](url)

**Comment by schaabs** [comment]
This has been implemented in #14636, and is available in [1.3.0-beta.1](https://www.nuget.org/packages/Azure.Identity/1.3.0-beta.1) or later. The feature is still in preview so if you have any feedback on its usability please open an issue and let us know.
