### ISSUE TITLE
[FormRecognizer] Tests: insufficient test files for multipage testing

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#12139]
## Summary

Currently, the custom form recognition treats a multipage file as a single form with multiple pages when using a model trained with labels. We cannot properly test the service behavior because we don't have enough multipage forms for training a model to be used for testing.

Forms that we currently have permission to post publicly on Github:

  | Receipt | Layout (sample should contain tables) | Training | Analyze
-- | -- | -- | -- | --
Uri example | https://raw.githubusercontent.com/Azure-Samples/cognitive-services-REST-api-samples/master/curl/form-recognizer/contoso-allinone.jpg |   |   |  
pdf example |   | https://github.com/Azure-Samples/cognitive-services-REST-api-samples/blob/master/curl/form-recognizer/sample_data.zip additional samples | https://github.com/Azure-Samples/cognitive-services-REST-api-samples/blob/master/curl/form-recognizer/sample_data.zip additional samples | https://github.com/Azure-Samples/cognitive-services-REST-api-samples/blob/master/curl/form-recognizer/sample_data.zip  additional samples
png example | https://github.com/Azure-Samples/cognitive-services-REST-api-samples/blob/master/curl/form-recognizer/contoso-receipt.png |   |   |  
jpeg example | https://raw.githubusercontent.com/Azure-Samples/cognitive-services-REST-api-samples/master/curl/form-recognizer/contoso-allinone.jpg | link | link | link
tiff example |   |   |   |  
Multipage example |   |   |   |  
Multipage example with multiple forms |   |   |   |  

## Goals

- Acquire at least 5 multipage forms to be used for testing. These forms will be used to train a model with labels, so it's necessary that different pages do not contain the same labels.
- Update the `StartRecognizeCustomFormsWithLabelsCanParseMultipagedForms` test to make use of the new files.

**Comment by annelo-msft** [comment]
@kinelski, do we have the forms we need to do this now?

**Comment by kinelski** [comment]
> 
> 
> @kinelski, do we have the forms we need to do this now?

Yes, we do! Closing this issue.
