### ISSUE TITLE
[QUERY] Storage troubleshooting - documentation for blob error codes

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#12134]
**Query/Question**
Storage Blob SDK v12 has a somewhat [hidden documentation](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Storage.Blobs/12.4.2/api/index.html#troubleshooting) that briefly mentions a couple of error codes but there's no documentation on all of those error codes. There's a [generated code file](https://github.com/Azure/azure-sdk-for-net/blob/bafbed759f9dd3ca1f5ef0e7edcac5bf0c00a4c4/sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs#L354-L469) but it would be nice to have proper documentation for those.

**Comment by amnguye** [comment]
Blob Service Error Codes are not managed by the SDK.

Here's the documentation of the blob service error codes that the service returns.

https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes

Here's the main page of error codes.
https://docs.microsoft.com/en-us/rest/api/storageservices/status-and-error-codes2

**Comment by SeanFeldman** [comment]
@amnguye, do you think it would be possible to link the article to the first link you've provided? It will be very helpful to find out about the rest of the `BlobErrorCode`s the service provides by following it.
Thank you.

**Comment by amnguye** [comment]
Actually the documentation already has the link to the ErrorCodes. If you click on `BlobErrorCode`s. :)

**Comment by SeanFeldman** [comment]
I did not even notice it was a link as it's styled as code and no link style is only applied to the 's'.
Great.
