### ISSUE TITLE
[FormRecognizer] Tests: Come up with a plan for live testing

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#12138]
## Description

Currently, live tests in the `FormRecognizer.Tests` project do not follow a pattern. Some of them test multiple results returned by the service:

https://github.com/Azure/azure-sdk-for-net/blob/33791358e574f5d66e495487b130da4db3c99ff9/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/FormRecognizerClientLiveTests.cs#L84-L87

Some do basic sanity checks on the values returned:

https://github.com/Azure/azure-sdk-for-net/blob/33791358e574f5d66e495487b130da4db3c99ff9/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/FormRecognizerClientLiveTests.cs#L650-L656

Tests are starting to get messy and fixing them in the future may be time consuming, specially because we'll have way more tests later. The question is: what should we be testing?

- If we test the values returned by the service:
  - Can we build a good test infrastructure to avoid repeating lots of code?
  - What's going to happen when the service version changes and we start to get different values?

- If we simply verify that everything is being populated, but ignore the values:
  - How can we make sure we are populating the properties correctly (mock tests?).

- If we do both:
  - In which tests one approach is preferred to the other?

**Comment by annelo-msft** [comment]
Can this be addressed as part of this https://github.com/azure/azure-sdk-for-net/issues/11882 and this  https://github.com/azure/azure-sdk-for-net/issues/12438?

**Comment by kinelski** [comment]
> 
> 
> Can this be addressed as part of this #11882 and this #12438?

Just closed #11882 since we already have a list of scenarios that languages can contribute to.

#12438 requires us to add new test scenarios, and maybe update a few of them to align with other languages.

#12138 implies changes to our testing infrastructure, and updates in existing tests (probably making them simpler and uniform).

I prefer keeping them separate since they have different goals.

**Comment by kinelski** [comment]
Our current testing infrastructure has been able to handle Form Recognizer scenarios fairly well. I see no reason to change our strategy at this moment. Closing this issue.
