### ISSUE TITLE
Azure.Identity add support for Azure SQL client authentication

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#12145]
Currently Azure.Services.AppAuthentication has support for authenticating Azure SQL clients through the [SqlAppAuthenticationProvider](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/SqlAppAuthenticationProvider.cs). Azure Identity needs to provide a similar provider to allow people to authenticate SQL clients using the `ManagedIdentityCredential` or `DefaultAzureCredential`. This needs to be designed and implemented.

**Comment by jvanitallie** [comment]
Is there any update to this?  Not having an MSAL (Azure.Identity) provider for SqlAppAuthenticationProvider is gating our ability to move completely away from ADAL which has now been officially announced as end of life.

**Comment by christothes** [comment]
related to #14122

**Comment by PaulVrugt** [comment]
So any plans to implement this?

**Comment by christothes** [comment]
> So any plans to implement this?

It is on our backlog, but we don't currently have a committed date. We'll use interest in this issue as a gauge for prioritization.

**Comment by PaulVrugt** [comment]
I might be missing something, but if this is not supported yet, how does anyone using managed identity to access SQL server move away from the appauthentication package? It would seem this is a big hiatus in azure.identity

**Comment by Frankd4** [comment]
Any update on this ?

Microsoft.Azure.Services.AppAuthentication is no longer recommended to use with new Azure SDK. It is replaced with new Azure Identity client library available for .NET, Java, TypeScript and Python and should be used for all new development. Information about how to migrate to Azure Identitycan be found here: AppAuthentication to Azure.Identity Migration Guidance.

**Comment by christothes** [comment]
`Microsoft.Data.SqlClient` recently added support for a connection string option that will use `DefaultAzureCredential` under the covers - Details here: 

https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15#using-active-directory-default-authentication
