### ISSUE TITLE
[FormRecognizer] Tests: FormTrainingClient live tests not deleting trained models

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#12140]
## Description

Tests in `FormTrainingClientLiveTests` are not deleting the models trained for testing upon completion. The `DisposableTrainedModel` class is used for this purpose in `FormRecognizerClientLiveTests`.

Edit: some tests in `OperationsLiveTests` have the same issue.

Should we do the same in the `FormTrainingClient` live tests? Or would it be better to NOT wrap the `StartTraining` call in a separate class, making it an explicit call and relying on `try/finally` blocks to delete the models? The later would make sense in methods whose sole objective is testing the `StartTraining` method, while the former would be used in methods where training is only one of the steps of the test.

**Comment by pallavit** [comment]
@kinelski is this still valid, can it be closed?

**Comment by kinelski** [comment]
> @kinelski is this still valid, can it be closed?

It's still valid.
