### ISSUE TITLE
[BUG] Azure.RequestFailedException at Azure.Storage.Blobs.BlobRestClient+Blob.SetMetadataAsync_CreateResponse

### ISSUE THREAD

**Issue by MegoCs** [Azure/azure-sdk-for-net#12186]
**Describe the bug**
using blob.SetMetadata(metadata) method results in Exception regarding request authentication 
here is the message from azure application insights 

> outerMessage : 
> Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
> RequestId:1debae58-c01e-0027-2ee5-2d9dee000000
> Time:2020-05-19T13:57:51.2195041Z
> Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
> ErrorCode: AuthenticationFailed

**Expected behavior**
What is the expected behavior?
setting meta data to blob file after uploading it.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
results in request authentication problems at 

problemId | Azure.RequestFailedException at Azure.Storage.Blobs.BlobRestClient+Blob.SetMetadataAsync_CreateResponse
type | Azure.RequestFailedException
assembly | Azure.Storage.Blobs, Version=12.4.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8
method | Azure.Storage.Blobs.BlobRestClient+Blob.SetMetadataAsync_CreateResponse
outerType | Azure.RequestFailedException
outerAssembly | Azure.Storage.Blobs, Version=12.4.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8
outerMethod | Azure.Storage.Blobs.BlobRestClient+Blob.SetMetadataAsync_CreateResponse

> Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
> RequestId:1debae58-c01e-0027-2ee5-2d9dee000000
> Time:2020-05-19T13:57:51.2195041Z
> Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
> ErrorCode: AuthenticationFailed
> 
> Headers:
> x-ms-request-id: 1debae58-c01e-0027-2ee5-2d9dee000000
> x-ms-error-code: AuthenticationFailed
> Date: Tue, 19 May 2020 13:57:50 GMT
> Server: Microsoft-HTTPAPI/2.0
> Content-Length: 932
> Content-Type: application/xml

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
```
            BlobContainerClient container = new BlobContainerClient(storageConnection, containerName);

            await container.CreateIfNotExistsAsync();

            string fileGuid = Guid.NewGuid().ToString();
            string uploadfileName = $"{fileName}_{fileGuid}.{fileExtension}";

            BlobClient blob = container.GetBlobClient(uploadfileName);

            BlobHttpHeaders blobHttpHeaders = new BlobHttpHeaders()
            {
                ContentType = contentType
            };

            await blob.UploadAsync(stream, blobHttpHeaders);

            if (metadata != null)
                blob.SetMetadata(metadata);

            return uploadfileName;
```

**Environment:**
 -Azure.Storage.Blobs, Version=12.4.2.0
 -Azure App service with .Net 4.7.2

**Comment by tg-msft** [comment]
What do your metadata keys look like?  Are they [valid C# identifier names](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/lexical-structure#identifiers)?  From [the REST API docs](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata#request-headers):

> x-ms-meta-name:value
> 
> Optional. Sets a name-value pair for the blob.
> 
> Each call to this operation replaces all existing metadata attached to the blob. To remove all metadata from the blob, call this operation with no metadata headers.
> 
> Note that beginning with version 2009-09-19, metadata names must adhere to the naming rules for C# identifiers.

We use them when constructing the [shared key Authorization header](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/src/Shared/StorageSharedKeyPipelinePolicy.cs#L93) which is why you might be getting this error.

(Also - your `blob.SetMetadata(metadata);` should probably be `await blob.SetMetadataAsync(metadata);`)

**Comment by MegoCs** [comment]
@tg-msft  here is my meta data
```
var metadata = new Dictionary<string, string>() {
    { "DocumentDate","2/24/2020 12:00:00 AM"},
    { "DocumentReference","SD-0000000004"},
 };
```
I think SetMetadata at the end is a wrapper for the async one so I think it`s not the problem here!

**Comment by MegoCs** [comment]
now I have even removed the metadata section and just used the uploadasync still got 

> Azure.Storage.Blobs.BlobRestClient+BlockBlob.UploadAsync_CreateResponse

```
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:22975fc3-901e-0157-2e13-2fda14000000
Time:2020-05-21T01:57:10.1714929Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed

Headers:
x-ms-request-id: 22975fc3-901e-0157-2e13-2fda14000000
x-ms-error-code: AuthenticationFailed
Date: Thu, 21 May 2020 01:57:09 GMT
Server: Microsoft-HTTPAPI/2.0
Content-Length: 988
Content-Type: application/xml
```
 and this doesn't happen all the time it happens **occasionally** and logged to application insights .
some people mentioned that u need to check dependencies tracking in application insights config and I did. and found that the storage is already under the untracked hosts.

```
      <ExcludeComponentCorrelationHttpHeadersOnDomains>
        <!-- 
        Requests to the following hostnames will not be modified by adding correlation headers.         
        Add entries here to exclude additional hostnames.
        NOTE: this configuration will be lost upon NuGet upgrade.
        -->
        <Add>core.windows.net</Add>
        <Add>core.chinacloudapi.cn</Add>
        <Add>core.cloudapi.de</Add>
        <Add>core.usgovcloudapi.net</Add>
      </ExcludeComponentCorrelationHttpHeadersOnDomains>
```

**Comment by MegoCs** [comment]
@pakrym @jsquire issue [12127](https://github.com/Azure/azure-sdk-for-net/issues/12127) still related !

**Comment by tg-msft** [comment]
How are you authenticating?  Does your connection string use a shared key, AAD, or SAS?  We might need folks on the service side to weigh in here.

**Comment by MegoCs** [comment]
@tg-msft no I am not using SAS I am using the storage account connection directly

**Comment by MegoCs** [comment]
@tg-msft also I think this issue might be related to how azure application insights handles the requests to the storage. despite the storage host, 

> core.windows.net

 is already under the ExcludeComponentCorrelationHttpHeadersOnDomains

**Comment by MegoCs** [comment]
any update regarding this BUG this is weird !! 
for now, i am using workaround to try make the same request again till success using retry policy.

```
 var retryPolicy = Policy
                             .Handle<Exception>()
                            .RetryForeverAsync();

await retryPolicy.ExecuteAsync(async () =>
     {
        await blob.UploadAsync(stream, blobHttpHeaders);
     });     
```
this workaround makes it obvious, that it`s related to application insights

**Comment by kasobol-msft** [comment]
This might be related https://github.com/microsoft/ApplicationInsights-dotnet/issues/1406

**Comment by kasobol-msft** [comment]
@MegoCs Please open support ticket through Azure Portal to further investigate how Application Insights are impacting requests to Storage.

**Comment by TonyGrayCanada** [comment]
I have this problem as well - all attempts to write metadata get 
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed
even though the same BlobClient was able to access and read the blob contents.

**Comment by TonyGrayCanada** [comment]
You can ignore my previous comment.  My problem was that I hadn't encoded the _value_ of a metadata entry with base64 or url encoding, and it contained characters that wrecked the header.

A version of the BlobClient that did this for you would certainly help avoid misleading errors, since getting this wrong gave AuthenticationFailed, probably because the authentication header was wrecked by the illegal contents of the metadata header.
