### ISSUE TITLE
[Pending service change] Change CopyAuthorization.ExpiresOn from long to DateTimeOffset

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12181]
The service currently has a bug where the return value can't be parsed into a DateTimeOffset.
Once they fixed it, we need to update our type from long -> DateTimeOffset

**Comment by annelo-msft** [comment]
@maririos, do we know if they will fix this before code complete for this preview?  If not, we need to decide if this is a release-blocker.

@mayurid
