### ISSUE TITLE
Convert EventGrid tests to Track2

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-for-net#12194]
Currently, EventGrid tests are written in a legacy fasion, see [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventgrid/azure-eventgrid/tests/test_azure_eventgrid.py).

As part of modernizing EventGrid for Track2, we must utilize the proper test harness as seen [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/storage/azure-storage-blob/tests/test_append_blob.py)

This will broadly involve:
- Writing a preparer for the EventGrid resource as seen [here](https://github.com/Azure/azure-sdk-for-python/blob/2598959164c9d1e87f20060e8ca76ec563d180d6/sdk/storage/azure-storage-blob/tests/_shared/testcase.py#L82)
- Utilize the preparer on the Event grid tests mentioned above, adjusting credentials to properly thread through.
- Adjusting the wrapper class to StorageTestCase as seen [here](https://github.com/Azure/azure-sdk-for-python/blob/2598959164c9d1e87f20060e8ca76ec563d180d6/sdk/storage/azure-storage-blob/tests/test_append_blob.py#L38)
- Generate new recordings, and validate that tests still run properly in both live and recorded mode

**Comment by JoshLove-msft** [comment]
Looks like this was added to the wrong repo.
