### ISSUE TITLE
Azure Storage: Make CRC computation code public so that clients can use it

### ISSUE THREAD

**Issue by amishra-dev** [Azure/azure-sdk-for-net#12198]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
Azure storage uses a custom polynomial, customer find it very difficult to calculate CRC on their own. Since the SDK will have a functioning CRC implementation, we should consider making it public.

**Comment by jaschrep-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/23056
