### ISSUE TITLE
 FaceClient throws APIErrorException 'BadRequest' in v2.5.0-preview1

### ISSUE THREAD

**Issue by frank-ozgul** [Azure/azure-sdk-for-net#12196]
The following code, using Microsoft.Azure.CognitiveServices.Vision.Face v2.5.0-preview1, throws Microsoft.Azure.CognitiveServices.Vision.Face.Models.APIErrorException:BadRequest
 
 string endPoint = "https://microservicesfaceapi.cognitiveservices.azure.com";
 IFaceClient client = Authenticate(endPoint, SUBSCRIPTION_KEY);
 string imageUrl =   "H:\\\facesimage.jpg";
The exception occurs when calling the api on the client object. 
 IList<DetectedFace> faces = await client.Face.DetectWithUrlAsync(imageUrl, true, false, null);

The endpoint is what has been given to me and taken from the overview page of the azure portal group I have created with the name of "microservicesfaceapi". 

********************************************
Further to the trial above, I have tried the same code with another image but this time  the image   had an internet url addres; such as "https://xxx.yyy/1.png". The code then worked. Why is the method not able to get the local image and turn  it into byte arrays behind the scenes.?

Yet another trial but this time with Stream method: it also failed:
I have read the image from the root dir and saved it into a MemoryStream object first  using the System.Drawing.Common library's Image object.

 Image img = Image.FromFile("people_with_phones.png");
 MemoryStream ms = new MemoryStream();
 img.Save(ms, System.Drawing.Imaging.ImageFormat.Png);
//MemoryStream object is not null. 
 IList<DetectedFace> faces = await client.Face.DetectWithStreamAsync(ms, true, false, null);

When I used FileStream instead  of MemoryStream object, however, it worked.

**Comment by Mhsoun** [comment]
@msftbot are you still routing this to the appropriate team since may
