### ISSUE TITLE
[Tests] Add ability to sanitize Json bodies

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12193]
Why:
We need to do this change in order to enable test recordings for Copy feature again.

Context: 
Currently, the tests for Copy feature are disabled because when generating the recordings, the access token that is in the body of the CopyAuthorization request gets saved.
See PR https://github.com/Azure/azure-sdk-for-net/pull/12182

Proposal:
Talked to @pakrym about this and his proposal is to add a type (`JsonRecordSanitizer`) to the TestFramework that will allow to specify what json nodes to be sanitized.
In order to do that, we could use Json path expressions.

**Comment by annelo-msft** [comment]
@maririos, could you update this issue with a description of why we need this for FR?

**Comment by maririos** [comment]
updated
