### ISSUE TITLE
[BUG] Management library for Event Hubs should use the correct name of the service

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#12208]
# Summary 

The track two management library for the Event Hubs is currently using an incorrect naming scheme for its assets.  This does not reflect the name of the associated service, `Azure Event Hubs`, which is a branding concern for the product.   This also leaves it inconsistent when compared to the naming of the client libraries for Event Hubs for both tracks [one](https://www.nuget.org/packages/Microsoft.Azure.EventHubs/) and [two](https://www.nuget.org/packages/Azure.Messaging.EventHubs) and the [Event Hubs product documentation](https://docs.microsoft.com/en-us/azure/event-hubs/).

# Expected

- The naming scheme should match the name of the Azure service, for example: `Azure.Management.EventHubs`
- The repository assets, root namespace, and associated packages should consistently use `Event Hubs` as the product name.

# Actual

- The naming scheme incorrectly references `Event Hub` as the product name.
- The repository assets, root namespace, and related items do not reflect the correct product name.

**Comment by erich-wang** [comment]
@jsquire , thanks for reporting the issue. Is there any general guideline for the service name used in namespace? For example, Event Hubs is brand/service name while Microsoft.EventHub is the resource provider name, does it mean service name is preferred in namespace?

**Comment by jsquire** [comment]
> @jsquire , thanks for reporting the issue. Is there any general guideline for the service name used in namespace? For example, Event Hubs is brand/service name while Microsoft.EventHub is the resource provider name, does it mean service name is preferred in namespace?

I would, personally, think that it should align with the name of the product/service and associated data plane libraries.   I know, in this case, that is the preference of the Event Hubs service team as well.   @AlexGhiondea and @KrzysztofCwalina would be the authoritative voices for generalized guidance.

**Comment by erich-wang** [comment]
@jsquire, close the issue as the name was updated to EventHubs and change has been merged into master.
