### ISSUE TITLE
[BUG] Azure Data Explorer: CreateOrUpdateAsync fails with "Could not parse database access mode"

### ISSUE THREAD

**Issue by MaStr11** [Azure/azure-sdk-for-net#12203]
**Describe the bug**

Creating a database via `KustoManagementClient.Databases.CreateOrUpdateAsync` failes with 
`Microsoft.Rest.Azure.CloudException : Could not parse database access mode`.

**Expected behavior**
Kusto database gets created without error.

**Actual behavior (include Exception or Stack Trace)**
An exception is raised:
`Microsoft.Rest.Azure.CloudException : Could not parse database access mode`.

**To Reproduce**
1. Make sure the database does not exists
2. Run the following code (`resourceGroupName` and `clusterName` need to exist).
```CS
            var client = new KustoManagementClient(...);
            var database = await client.Databases.CreateOrUpdateAsync("resourceGroupName",
                "clusterName", "databaseName", new Database()
                {
                    Location = "westeurope",
                });
```

**Environment:**
 - Microsoft.Azure.Management.Kusto 5.0.0
 - Azure Data Explorer or Windows 10 .NET Core 3.1
 - IDE and version : Visual Studio 16.4

**Root cause**
The `Database` type contains a property `kind`. This property is serialized into the body of the request (https://docs.microsoft.com/en-US/rest/api/azurerekusto/databases/createorupdate). 
```json
{
  "kind": "Database",
  "location": "westeurope"
}
```
The property seems to be interpreted as `DATABASE KIND` and seems to expect something like `read-write` (The [REST documentation](https://docs.microsoft.com/en-US/rest/api/azurerekusto/databases/createorupdate) does not state the `kind` property, though):

![image](https://user-images.githubusercontent.com/24472128/82448573-2e4ae700-9aaa-11ea-9d7d-82fb0cf822b5.png)

**Workaround:**
Create a DelegatingHandler and intercept the request. Remove the `kind` property from the body:
```CS
        class TestHandler : DelegatingHandler
        {
            protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                if (request.Content is StringContent sc)
                {
                    var originalContent = JObject.Parse(await sc.ReadAsStringAsync());
                    if (originalContent["kind"]?.Type == JTokenType.String && (string)originalContent["kind"]! == "Database")
                    {
                        originalContent["properties"] = JObject.FromObject(new
                        {
                            hotCachePeriod = "P31D",
                            softDeletePeriod = (string)null!
                        });
                        originalContent.Remove("kind");
                        var newContent = originalContent.ToString();
                        request.Content = new StringContent(newContent, Encoding.UTF8, MediaTypeNames.Application.Json);
                    }
                }
                return await base.SendAsync(request, cancellationToken).ConfigureAwait(false);
            }
        }

        using var client = new KustoManagementClient(credentials, new TestHandler());
```

**Comment by isra-fel** [comment]
Thanks for you feedback!
Hello Ravit could you give us some insights? Thank you!

**Comment by radennis** [comment]
Please try to use this code to create the database:
`var database = managementClient.Databases.CreateOrUpdate(resourceGroup, clusterName, databaseName, new ReadWriteDatabase(location, softDeletePeriod: softDeletePeriod, hotCachePeriod: hotCachePeriod)) as ReadWriteDatabase;`

see more information here: https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-csharp#create-the-database-in-the-azure-data-explorer-cluster

**Comment by MaStr11** [comment]
@radennis Thanks. It works like a charm. While it is documented how to do it right, I would suggest making the Database class abstract and/or improve the XmlDocs for `CreateOrUpdateAsync`.

https://github.com/Azure/azure-sdk-for-net/blob/f3ae7f10ee0d16364713cb1500c74e175cb25570/sdk/kusto/Microsoft.Azure.Management.Kusto/src/Generated/DatabasesOperationsExtensions.cs#L173-L175

```CS
            /// <param name='parameters'>
            /// The database parameters supplied to the CreateOrUpdate operation.
            /// Pass either a ReadOnlyFollowingDatabase or a ReadWriteDatabase.
            /// </param>
```

**Comment by radennis** [comment]
@docohe to consider this change to make customer's lives easier.

**Comment by KranthiPakala-MSFT** [comment]
@ilayrn , @orhasban , @astauben - Following up to see if there is any update on this issue? - Thank you

**Comment by navba-MSFT** [comment]
@MaStr11 Apologies for the late reply. We are looking into this issue and we will update this thread once we have more details on this.
@ilayrn, @orhasban, @astauben Could you please provide an update on this issue ? Awaiting your reply.

**Comment by docohe** [comment]
Those files are auto generated, we cannot change the description AFAIK. @orhasban FYI.
