### ISSUE TITLE
[Track 2 SDK] Reconcile and consolidate test framework  

### ISSUE THREAD

**Issue by allenjzhang** [Azure/azure-sdk-for-net#12209]
Based on feedback, we should come back revisit the test framework and see if any consolidation and refactoring is needed.

Backlog:
1. move test helper projects from sdk/testcommon to common/
2. Rename common/Azure.Graph.Rbac

**Comment by jsquire** [comment]
Given the age of this and the shift to the track 2 packages, closing this out as stale.  Please feel free to reopen if this is still needed.
