### ISSUE TITLE
Azure.Management.KeyVault tests are failing

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#12211]
The recent check-in with https://github.com/Azure/azure-sdk-for-net/pull/12039 broke live test runs. See https://dev.azure.com/azure-sdk/internal/_build/results?buildId=398184 - mostly `NullReferenceException`s on linux and mac.

**Comment by pakrym** [comment]
Not only live, recorded runs fail as well: 
![image](https://user-images.githubusercontent.com/1697911/82685435-0de56e80-9c09-11ea-96e2-49e140d6f672.png)

```
System.InvalidOperationException : Unable to find a record for the request GET https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.KeyVault?api-version=2019-10-01

Uri doesn't match:

request https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.KeyVault?api-version=2019-10-01

record https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.KeyVault?api-version=2017-05-10

Header differences:

Body differences:

```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=400667&view=ms.vss-test-web.build-test-results-tab&runId=11100994&resultId=104307&paneView=debug

This needs to be fixed ASAP.

**Comment by heaths** [comment]
When this is fixed, delete the file added by https://github.com/Azure/azure-sdk-for-net/pull/12291 (assuming no other changes).

**Comment by heaths** [comment]
/cc @allenjzhang 

This is also failing recorded tests, which prevents the generator from being able to successfully test and merge changes into our repo.

**Comment by erich-wang** [comment]
I'm investigating the issue. It is weird that the log shows record with api-version 2019-10-01 but I could not any record with api-version `2019-10-01` in record files.
```
Uri doesn't match:

request https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.KeyVault?api-version=2019-10-01

record https://management.azure.com/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/providers/Microsoft.KeyVault?api-version=2017-05-10
```

**Comment by heaths** [comment]
General guidelines require that API versions are specified, if not by the user, we need to hardcode them for first versions of clients (typically not done in .NET, though; see our data-plane clients for examples). I'm not sure why a new version was picked up, but it could also be caused by updates in Azure/azure-rest-api-specs to the service readme.md file. You may need to re-record, but I'd check out the history in that repo for Key Vault first.
