### ISSUE TITLE
MessageReceiver PeekAsync(maxMessages) - How to retrieve a lot of messages efficiently

### ISSUE THREAD

**Issue by clouddna-au** [Azure/azure-sdk-for-net#12226]
**Query/Question**
I have been trying to find a way to download all my messages from the deadletter queue, so they can be interrogated client side.
1. Make use of  PeekAsync providing a maxMessage count. This works ok but suddenly when the count of messages increased over for example 100 of so, it is not returning all the messages anymore. It is really fast to retrieve, sub seconds
```
var deadletterReceiver = new MessageReceiver(_serviceBusOptions.Endpoint, EntityNameHelper.FormatDeadLetterPath(queueName),
             ReceiveMode.PeekLock);
           
            // receive a message
            var messages = await deadletterReceiver.PeekAsync(maxMessageCount: (int)deadcount);
            if (messages != null)
            {
                // var tokens = messages.Select(m => m.SystemProperties.LockToken);
                return messages.Select(message => new DeadLetterDto()
                {
                    QueueName = queueName,
                    DeadletterQueueName = EntityNameHelper.FormatDeadLetterPath(queueName),
                    Body = Encoding.UTF8.GetString(message.Body),
                    MessageId = message.MessageId,
                    DeliveryCount = message.SystemProperties.DeliveryCount + 1,
                    EnqueueTime = message.SystemProperties.EnqueuedTimeUtc,
                    UserProperties = message.UserProperties,
                    Seq = message.SystemProperties.SequenceNumber,
                    Size = message.Size
                });
            }
```
2. Try and make use of `RegisterMessageHandler` on MessageReceiver. It seems to work really well with concurrent calls but I have no way of knowing when it is finished, as all examples basically only cancel the Task from the method after a specific time. 
```
public Task getMessages(string queueName)
        {
            var doneReceiving = new TaskCompletionSource<bool>();

            var client = new MessageReceiver(_serviceBusOptions.Endpoint, EntityNameHelper.FormatDeadLetterPath(queueName));

            client.RegisterMessageHandler(
                    async (message, token) =>
                    {
                        _deadLetterMessages.Add(new DeadLetterDto()
                        {
                            QueueName = queueName,
                            DeadletterQueueName = EntityNameHelper.FormatDeadLetterPath(queueName),
                            Body = Encoding.UTF8.GetString(message.Body),
                            MessageId = message.MessageId,
                            DeliveryCount = message.SystemProperties.DeliveryCount + 1,
                            EnqueueTime = message.SystemProperties.EnqueuedTimeUtc,
                            UserProperties = message.UserProperties,
                            Seq = message.SystemProperties.SequenceNumber,
                            Size = message.Size
                        });
                    },
                    new MessageHandlerOptions((async args => Console.WriteLine(args.Exception)))
                    {
                        MaxConcurrentCalls = 50,
                        AutoComplete = false
                    });
            return doneReceiving.Task;
        }
```
3. Make use of normal PeekAsync for each message with a while loop, but it is really slow on hundreds of messages
```
public async Task<IEnumerable<DeadLetterDto>> getMessages(string queueName)
        {
            var deadletterReceiver = new MessageReceiver(_serviceBusOptions.Endpoint,
            EntityNameHelper.FormatDeadLetterPath(queueName));

            while (true)
            {
                await maxConcurrentCallsSemaphoreSlim.WaitAsync().ConfigureAwait(false);
                var message = await deadletterReceiver.PeekAsync().ConfigureAwait(false);
                if (message == null)
                {
                    break;
                }
                _deadLetterMessages.Add(new DeadLetterDto()
                {
                    QueueName = queueName,
                    DeadletterQueueName = EntityNameHelper.FormatDeadLetterPath(queueName),
                    Body = Encoding.UTF8.GetString(message.Body),
                    MessageId = message.MessageId,
                    DeliveryCount = message.SystemProperties.DeliveryCount + 1,
                    EnqueueTime = message.SystemProperties.EnqueuedTimeUtc,
                    UserProperties = message.UserProperties,
                    Seq = message.SystemProperties.SequenceNumber,
                    Size = message.Size
                });
            }
            return _deadLetterMessages;
        }
```

So my questions are:
1. Whats the best way to efficiently retrieve all message from the queue?
2. If I use RegisterMessageHandler, how can I know that its done to return all the message to my website? What am I missing, or is that its intend?
3. I tried mimiking the messagepump with a semiphoreslim, but I have to set the semiphoreslim(maxdeadlettercount), which didn't provide any concurrent calls like with RegisterMessageHandler.

Thanks for info in advance

**Environment:**
 - Microsoft.Azure.ServiceBus 4.1.1
 - Dotnet Core 3.1
 - VsCode

**Comment by nemakam** [comment]
@clouddna-au 
Could you explain your scenario? 
1. RegisterMessageHandler keeps getting messages from the queue. If you know how many messages you are expecting from the queue, you can cancel the handler after processing them. There is no "end" for a queue as new messages can be added anytime. The common way of how this is tackled is using time-gap. If you didn't receive any message for say 1 minute, then you could assume that all the messages are retrieved. 
This is asssuming you do not know the count of msgs already. 
2. Peek and Receive are different operations. Peek only peeks, and doesn't delete the messages from the queue. In a Receive operation, if you did a PeekLock, then you can `Complete` the message, which is essentially deleting the message from the queue. Are you looking to peek / receive the message?

**Comment by nemakam** [comment]
If you want to use PeekAsync(100), the "100" here is "maxCount".. i.e., upto 100 msgs can be received. If you did not receive 100 msgs, it is expected that you call PeekAsync() again with the remaining count. i.e., lets say after the first call you retrieved 65 msgs, you will end up calling PeekAsync(35) again till you retrieve all the 100 msgs.

**Comment by nemakam** [comment]
I'm going to close this. Let me know if your question is not answered.
