### ISSUE TITLE
use "normalized" name for location in ARM responses

### ISSUE THREAD

**Issue by matt-gibbs** [Azure/azure-sdk-for-net#1223]
Azure locations can be specified without regard to case and with embedded spaces:
"West US" or "west us" or "westus"
Some of the REST APIs return the friendly version: "West US"
Others return the "normalized" version: "westus"

The result is that comparing locations of resources requires client-side code to normalize all location strings before comparing them. 
Have all the Azure REST APIs use a single format to eliminate the confusing need for special casing location names client-side.

**Comment by ravbhatnagar** [comment]
Should already be addressed. PLease let us know if this still is an issue.
