### ISSUE TITLE
[QUERY] Blob Geo-Redundant Failover

### ISSUE THREAD

**Issue by rtrainer** [Azure/azure-sdk-for-net#12237]
**Query/Question**
The previous version (v11) of the storage SDK had an OperationContext that allowed the developer to determine if the primary region had failed and switch read requests to the secondary region. How is this handled in the new SDK (v12)? I see the use of pipelines for things but I can't find anything that would allow me to detect a failover

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blob v12

**Comment by amnguye** [comment]
Hi,

Just to clarify, what you're looking for is a way to look at the logging requests? You can enable some logging by creating a source listener

https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging

Please let me know if I missed the mark on your query.

**Comment by rtrainer** [comment]
I am looking for something like this article that shows how to determine when there is a failure of the primary and how to switch to the secondary region.

https://docs.microsoft.com/en-us/azure/storage/blobs/storage-create-geo-redundant-storage?tabs=dotnet#understand-the-sample-code

**Comment by amnguye** [comment]
Hi,

Ah I see, sorry for the earlier miscommunication.

You can find the Blob Geo Redundant Replication Status in the 'BlobServiceStatistics.BlobGeoReplicationStatus' after you calling GetStatistics on a ServiceClient.

```
            BlobServiceClient service = InstrumentClient(
                new BlobServiceClient(
                    new Uri(TestConfigDefault.BlobServiceSecondaryEndpoint),
                    GetNewSharedKeyCredentials(),
                    GetOptions()));

            // Act
            Response<BlobServiceStatistics> response = await service.GetStatisticsAsync();

            if (response.Value.GeoReplication.Status == BlobGeoReplicationStatus.Live)
            {
                //failover
            }

```

Sorry if any of this is unclear. Please try something like this out and let me know if there's any other information you may need.

**Comment by rtrainer** [comment]
The model changed from using events and this call would be done before each upload or in the case of a retry after an exception is thrown.

**Comment by amnguye** [comment]
Hi,

I was wondering what the question is here.

> The model changed from using events and this call would be done before each upload or in the case of a retry after an exception is thrown.

Did you want more help on your scenario on how to detect failover?

**Comment by rtrainer** [comment]
Is what I stated correct?

**Comment by amnguye** [comment]
Hi,

If there are no further questions please reactivate. If you do reactivate could you provide a snippet of what you're attempting to do from the old library and maybe I can better help you migrate to the new library with what you're doing.

I did answer your question on how to accomplish what you wanted from the article to see if you the secondary is available to failover.  Looking through this sample that you are referring to
https://github.com/Azure-Samples/storage-dotnet-circuit-breaker-ha-ra-grs/blob/master/storage-dotnet-circuit-breaker-ha-ra-grs/Program.cs
It doesn't look like this sample from the old library answers your question either.
