### ISSUE TITLE
Add doc comment examples for Azure.Core types to improve online documentation

### ISSUE THREAD

**Issue by drwill-ms** [Azure/azure-sdk-for-net#12242]
Azure.Core

Could we get doc comment examples for Azure.Core types, for instance how to use the ClientOptions properly?
 
e.g. for HttpPipelineTransport https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/ClientOptions.cs#L29, put in https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md#user-provided-httpclient-instance

 Online docs are lean: https://docs.microsoft.com/en-us/dotnet/api/azure.core.clientoptions.transport?view=azure-dotnet

**Comment by pallavit** [comment]
We now have a documentation in Azure.Core samples for how to use ClientOptions, please feel free to reopen if you feel otherwise.
