### ISSUE TITLE
[QUERY] EventGrid manage samples are outdates

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#12246]
**Query/Question**

The [samples for EventGrid](https://github.com/Azure-Samples/event-grid-dotnet-publish-consume-events) are outdated, using Microsoft.Azure.Management.EventGrid version 2.0.0-preview (current version is 5.0.0). 

Would it be possible to update the sample or point to the up-to-date documentation/samples?

**Comment by isra-fel** [comment]
Hi Javier would you consider the request? Thanks

**Comment by SeanFeldman** [comment]
@ahamad-MS samples help potential users/ customers with service evaluation. It's in EG's service interests to have samples updates and not keep it in the backlog.
Whenever there are changes (and there **are**), samples should be updated.

**Comment by SeanFeldman** [comment]
Potential customers are evaluating a product based on the samples they get to experiment with and the experience they go through. If the samples are A) outdated, B) require customers to spend time to get those to work, C) do not reflect/hide features available with the service and D) give an impression of stale/abandoned code; it's not a good first impression.

**Comment by SeanFeldman** [comment]
This is [an example](https://stackoverflow.com/questions/62879395/how-to-publish-event-hub-events-to-event-grid-topic-with-azure-sdk/62881018) of what I've described above. See this comment specifically:

![image](https://user-images.githubusercontent.com/1309622/87447872-50e41280-c5b8-11ea-8aa2-ed429b469684.png)

**Comment by JoshLove-msft** [comment]
Providing a link to the new Event Grid SDK [Readme](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventgrid/Azure.Messaging.EventGrid) which contains samples.

**Comment by jfggdl** [comment]
We still have this work item in our backlog. We will get to it according its priority. I hope the latest sample provided by Josh helped. Thanks Josh.
