### ISSUE TITLE
Please add Power BI to Microsoft.Azure.Management.StreamAnalytics.Models

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/azure-sdk-for-net#1224]
As the Streaming Analytics NuGet package is in Preview, please add PowerBI as an Output Source.
Thanks

**Comment by markcowl** [comment]
@mikeblakeuk Thank you for the feedback.  Assigning to the appropriate team for investigation.

**Comment by atpham256** [comment]
We currently do not support PowerBI as an Output Source via the SDK or PowerShell. We only expose it through the Portal due to the authentication requirements associated with the Output Source.
