### ISSUE TITLE
CryptographicException Additional information: The system cannot find the file specified

### ISSUE THREAD

**Issue by levalencia** [Azure/azure-sdk-for-net#1225]
I want to create a sql azure DB by code, when I tried I get this error.

http://stackoverflow.com/questions/31250132/cryptographicexception-additional-information-the-system-cannot-find-the-file-s

The code is based on this article
https://code.msdn.microsoft.com/windowsazure/How-to-create-a-Azure-SQL-5157ce03

**Comment by akromm** [comment]
Issue with loading/using certificates not with SQL.

**Comment by shahabhijeet** [comment]
@levalencia please open a new issue if the problem still exists/repros.
