### ISSUE TITLE
[QUERY] MFA Exception when accessing AzureKeyVault

### ISSUE THREAD

**Issue by Kees8** [Azure/azure-sdk-for-net#12260]
**Query/Question**
I’m using Microsoft.Azure.KeyVault to get secrets in a LOB native application. A security group has been given permission to access secrets, and the application has not had a problem getting secrets until recently. Since this is a native application, this ensures only members of our relatively small team can access secrets, and there is no sensitive information in source.  

A subset of my users have recently been required to use MFA (presumably because they now work remotely). That fails because the method GetSecretAsync uses AAD integrated auth which doesn’t support MFA. The exception is: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'AzureKeyVault'

Is there a workaround for this issue? Can I use universal or interactive authentication (methods that support MFA) to get secrets?

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Keyvault 3.0.4
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Framework 4.8
 - IDE and version : Visual Studio Enterprise 2019 - Version 16.5.5

**Comment by heaths** [comment]
Are you able to migrate to our Azure.Security.KeyVault.Secrets package? Along with Azure.Identity, we've made a number of improvements including for authentication. Using a `DefaultAzureCredential`, for example, with Azure.Identity 1.2.0-preview.4 or newer, your developers can not only sign in with Visual Studio or the Azure CLI, but if you enable the interactive browser credential (not something you want to do in production, so condition it's enablement just in case previous authentication methods fail for whatever reason) that should support MFA.

Example:
```csharp
var credential = new DefaultAzureCredential(includeInteractiveCredentials: Environment.GetEnvironmentVariable("PRODUCTION") != null);
var client = new SecretClient(new Uri("https://my-vault.vault.azure.net"), credential);
```

To support Microsoft.Azure.KeyVault, you're callback that actually does the authentication could support other workflows like device authentication as documented in <https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows>.
