### ISSUE TITLE
[BUG] No reference document published for Microsoft.Azure.Management.SqlVirtualMachine

### ISSUE THREAD

**Issue by isra-fel** [Azure/azure-sdk-for-net#12274]
**Describe the bug**
`Microsoft.Azure.Management.SqlVirtualMachine` [has GAed](https://www.nuget.org/packages/Microsoft.Azure.Management.SqlVirtualMachine/) for months but the reference doc hasn't been published.
Please follow the instruction here to publish it: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/adx_netsdk_process.md#documentation

Thank you

**Comment by ranishan** [comment]
Created item to publish reference docs
 https://ceapex.visualstudio.com/Onboarding/_workitems/edit/227529

**Comment by ranishan** [comment]
@isra-fel Can we close this issue. We have released the documents:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.sqlvirtualmachine?view=azure-dotnet

**Comment by isra-fel** [comment]
Sure thing. Thanks!
