### ISSUE TITLE
write azure sdk logs to console , events log or any other way to get sdk logs 

### ISSUE THREAD

**Issue by vscodewinodws** [Azure/azure-sdk-for-net#12283]
**Query/Question**
i want to log everything sdk is doing behind the method call.

i know this functionality exist, it has pr and issue as well and it has documentation for it 

https://github.com/Azure/azure-sdk-for-net/issues/7556 

https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging

but using console or event logs i tried but sdk is not showing me any log in console or events (one  more question in Linux where events will be stored  ?)

i tried as per docs but found it's not giving expected output it so any one can help me here .

fyi i have already updated all nugets .

**Environment:**
windows 10
 - Hosting platform or OS and .NET runtime version dotnet core 3.1

 - IDE and version : Visual Studio 16.6

**Comment by jsquire** [comment]
Hi @vscodewinodws.  We're sorry that you're encountering difficulties and appreciate you reaching out to let us know.  Unfortunately, without more information, there's not much help that we can offer.  

The Azure SDK libraries use the Event Tracing for Windows (ETW) framework for logging, which is intended to be used with a trace listener to collect the logs and act on them.   For example, a tool such as [PerView](http://www.microsoft.com/en-us/download/details.aspx?id=28567) or [Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-trace-logs#use-etw-events).

The article that you linked to discusses using the `AzureEventSourceListener to listen to the logs emitted by the Azure SDK client libraries, which would typically be the recommended approach.  Doing so will allow you to receive log output and redirect to the console or however you would prefer to capture or surface them.

You mention that you tried to match the pattern from the article, but are not seeing logs.  Can you help us to understand what your scenario is, what your code looks like, and which Azure client libraries you're working with?

**Comment by pakrym** [comment]
We also have information at https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md but I'm not sure if it would add to what you already know.

You have to put 
`using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();` before making client calls and not dispose the listener during the entire application lifetime, `Program.Main` is a good place to put it.

**Comment by vscodewinodws** [comment]
i tried but not working can you provide small app ?

**Comment by pakrym** [comment]
```
using System;
using Azure.Core.Diagnostics;
using System.Diagnostics.Tracing;
using Azure.Storage.Blobs;
namespace azurelogs
{
    class Program
    {
        static void Main(string[] args)
        {
            using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Verbose);
            new BlobClient(new Uri("https://pakrym0test0storage.blob.core.windows.net/myblobcontainer/10k.bin")).Download();
        }
    }
}

```

**Comment by vscodewinodws** [comment]
your example is perfectly working and showing the expected output , but in my case i am doing various vm operations ( nuget are already updated and have latest libs) but when i put the same code it does not shows the log info , i am doing various operations e.g start  , restart , stop , deallocate etc .

so any guess what is wrong here , even i tried to place the code inside the restart (restart async) method but it did not shown any log , if you need i can share code example.

**Comment by jsquire** [comment]
Hi @vscodewinodws.   There's not much that we're able to tell you about what may be wrong in your code without seeing your code.  If you'd like to put together a short snippet that you can share as part of this discussion, that would help us to better understand what issues you may be running into.

**Comment by vscodewinodws** [comment]
yes sure will share example soon

**Comment by vscodewinodws** [comment]
please find my below code that does not logs to console 


using System;
using Azure.Core.Diagnostics;
using System.Diagnostics.Tracing;
using Azure.Storage.Blobs;
using Microsoft.Azure.Management.ResourceManager.Fluent;
using Microsoft.Azure.Management.ResourceManager.Fluent.Authentication;
using Microsoft.Azure.Management.ResourceManager.Fluent.Core;
using System.Diagnostics.CodeAnalysis;
using Microsoft.Azure.Management.Fluent;
using Microsoft.Azure.Management.Compute.Fluent;
using Microsoft.Azure.Management.AppService.Fluent;
using System.Threading.Tasks;

namespace azurelogs
{
    class Program
    {
        public async static Task Main(string[] args)
        {
            using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Verbose);


            VirtualMachineData virtualMachineData = new VirtualMachineData("myresourcegroup", "myresourcename", "my client id", "my client password", "tenantid", "subscription");

            var res = await virtualMachineData.RestartVirtualMachineAsync();

            Console.WriteLine(res);


            Console.ReadLine();

        }
    }


    public class AzureData
    {

        [NotNull]
        protected IAzure AzureObj { get; private set; }



        public AzureData(string clientId, string clientSecret, string tenantId, string subscription)
        {
            if (string.IsNullOrEmpty(clientId) || string.IsNullOrWhiteSpace(clientId))
            {
                throw new ArgumentException("arg was null", nameof(clientId));
            }

            if (string.IsNullOrEmpty(clientSecret) || string.IsNullOrWhiteSpace(clientSecret))
            {
                throw new ArgumentException("arg was null", nameof(clientSecret));
            }

            if (string.IsNullOrEmpty(tenantId) || string.IsNullOrWhiteSpace(tenantId))
            {
                throw new ArgumentException("arg was null", nameof(tenantId));
            }

            if (string.IsNullOrEmpty(subscription) || string.IsNullOrWhiteSpace(subscription))
            {
                throw new ArgumentException("arg was null", nameof(subscription));
            }

            InitAzureObj(subscription, clientId, clientSecret, tenantId);


        }



        public void InitAzureObj(string Subsciption, string clientId, string clientSecret, string tenantId)
        {
            if (string.IsNullOrEmpty(Subsciption))
            {
                throw new ArgumentException("arg was null", nameof(Subsciption));
            }

            if (string.IsNullOrEmpty(clientId))
            {
                throw new ArgumentException("arg was null", nameof(clientId));
            }

            if (string.IsNullOrEmpty(clientSecret))
            {
                throw new ArgumentException("arg was null", nameof(clientSecret));
            }

            if (string.IsNullOrEmpty(tenantId))
            {
                throw new ArgumentException("arg was null", nameof(tenantId));
            }

            try
            {


                if (string.IsNullOrEmpty(Subsciption) || string.IsNullOrWhiteSpace(Subsciption))
                {
                    throw new ArgumentNullException($"Azure subscription was null , value {Subsciption}");
                }


                AzureObj = Microsoft.Azure.Management.Fluent.Azure
                           .Configure()
                           .WithLogLevel(HttpLoggingDelegatingHandler.Level.BodyAndHeaders)
                           .Authenticate(InitAzureAppCrdentials(clientId, clientSecret, tenantId))
                           .WithSubscription(Subsciption);




            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }



        private AzureCredentials InitAzureAppCrdentials(string ClientId, string ClientSecret, string TenantId)
        {
            if (string.IsNullOrEmpty(ClientId))
            {
                throw new ArgumentException("arg was null", nameof(ClientId));
            }

            if (string.IsNullOrEmpty(ClientSecret))
            {
                throw new ArgumentException("arg was null", nameof(ClientSecret));
            }

            if (string.IsNullOrEmpty(TenantId))
            {
                throw new ArgumentException("arg was null", nameof(TenantId));
            }

            try
            {
                var x = SdkContext.AzureCredentialsFactory.FromServicePrincipal(ClientId, ClientSecret, TenantId, AzureEnvironment.AzureGlobalCloud);


                return x;


            }
            catch (Exception ex)
            {


                Console.WriteLine(ex);

                return null;
            }
        }

    }



    public class VirtualMachineData : AzureData
    {
        [DisallowNull]
        private string ResourceName { get; }

        [DisallowNull]
        private string ResourceGroupName { get; }

        private IVirtualMachines AzureVM { get; }


        public async Task<bool> RestartVirtualMachineAsync()
        {
            try
            {
                if (string.IsNullOrEmpty(ResourceGroupName) || string.IsNullOrWhiteSpace(ResourceGroupName))
                {
                    throw new ArgumentException("arg was null", nameof(ResourceGroupName));
                }

                if (string.IsNullOrEmpty(ResourceName) || string.IsNullOrWhiteSpace(ResourceName))
                {
                    throw new ArgumentException("arg was null", nameof(ResourceName));
                }



                var vmid = await AzureVM.GetByResourceGroupAsync(ResourceGroupName, ResourceName).ConfigureAwait(false);


                if (vmid != null)
                {



                    await vmid.RestartAsync().ConfigureAwait(false);



                    return true;
                }
                else
                {


                    return false;
                }




            }
            catch (Exception ex)
            {
                return false;

            }
        }


        public VirtualMachineData(string? resourcegroup, string? resourcename, string clinetid, string clientsecret, string tenantid, string subscription) : base(clinetid, clientsecret, tenantid, subscription)
        {

            ResourceGroupName = resourcegroup;

            ResourceName = resourcename;

            AzureVM = AzureObj.VirtualMachines;

        }


    }
}

**Comment by jsquire** [comment]
Hi @vscodewinodws.   Thank you for sharing the snippet.  I think that clarifies the scenario and the disconnect.  You're using the management libraries, which are not yet conformant to the new Azure SDK guidelines and approach.  As a result, the diagnostics and logging that Pavel and I have been discussing would not work with them.  Apologies for the confusion.

Unfortunately, there isn't much insight that we can help with around the Fluent Management SDK.  I'm going to loop in @erich-wang and ask that he help route you to the right person to help with this.

**Comment by erich-wang** [comment]
Please try https://www.nuget.org/packages/Azure.ResourceManager.Compute/1.0.0-preview.1, thanks.
