### ISSUE TITLE
[BUG] Azure Service Bus not accepting messages for +-5 seconds and this every 5 minutes  

### ISSUE THREAD

**Issue by jay1891** [Azure/azure-sdk-for-net#12289]
**Describe the bug**
Exact every 5 minutes Service bus topics are not accepting our messages, at 1 of our service bus namespaces and this for 5 seconds. We can stop our servers and applications, and start them again, but the 5 minute interval remains at the same time. Which is an indication for us that the service bus server is blocking at a fixed interval. We see the messages being passed to the .NET client SDK, and it looks like the service bus server sees them, but is not passing them immediately to its topic subscriptions. The tasks of the .NET client SDK method calls keep waiting, till after 5 seconds the messages are delivered to the subscriptions.  If we halt our application at 2th second of 5, then we see the messages arriving in our subscription 3 seconds later at the 5th second. In the rest of the 5 minutes the messages are passed in milliseconds to the receiver of a subscription. Because we need close to realtime data, these 5 seconds are problematic.

What could cause this 5 second blocking?

**To Reproduce**
We use "await this.TopicClient.SendAsync(message);"

**Environment:**
 - Microsoft.Azure.ServiceBus 4.1.2
 - .NET core 3.1
 - Visual studio 16.5.54

**Comment by nemakam** [comment]
@jay1891, I am not sure I understand the problem completely. Are you saying every 5 minutes the SendAsync() operation takes over 5 seconds?
This doesn't look like any SDK side issue and we may have to investigate your scenario separately. Could you please open a support ticket through the Azure portal with the appropriate repro so that this can be investigated further?

**Comment by jay1891** [comment]
@nemakam Last week a support ticket was created and the MS engineering team identified the problem. In the following weeks they will deploy a fix.

**Comment by jay1891** [comment]
@nemakam, if it could be helpful, the support ticket has id 120051422001928
