### ISSUE TITLE
[QUERY] How to authenticate to management.azure.com with DefaultAzureCredential()

### ISSUE THREAD

**Issue by mariojsnunes** [Azure/azure-sdk-for-net#12290]
**Query/Question**
What's the best way to authenticate to the azure management api? I'm trying to add custom domains via code.

Before it worked well with 
```
AzureServiceTokenProvider azureTokenProvider = new AzureServiceTokenProvider();
 string token = await azureTokenProvider.GetAccessTokenAsync("https://management.azure.com", tenantId);
```

But now, I'm migrating to the new API and I'm getting "The access token is invalid." error message. 

```
var credential = new DefaultAzureCredential();

var token = credential.GetToken(
           new Azure.Core.TokenRequestContext(
                    new[] { $"https://management.azure.com/.default" }));
```

Also tried with the tenantId instead of .default, but it returns
 Unable to get access token.  'AADSTS500011: The resource principal named https://management.azure.com/tenantId was not found in the tenant named...

**Edit:** I should also mention that I am authenticating to KeyVault with no problem using DefaultAzureCredential() and SecretClient()

Any advice?

**Environment:**
 - Name and version of the Library package used: [Azure.Identity 1.2.0-preview.3]
 - Hosting platform or OS and .NET runtime version: Linux App Service, .Net Core 3.1
 - IDE and version: Visual Studio 2019

Thanks!

**Comment by AlexGhiondea** [comment]
@schaabs can you take a look? Is this supported by `DefaultAzureCredential`?

**Comment by schaabs** [comment]
@mariojsnunes  Thank you for reaching out with this question. We are currenlty working on new versions of our management libraries which will work directly with the `TokenCredential` abstraction and the implementations in the Azure.Identity library. In the meantime @jongio has also provided some samples which demonstrate using the `DefaultAzureCredential` with our older libraries. For instance here is a sample which wraps the `DefaultAzureCredential` in the `ITokenProvider` interface so it can be used in all the contexts you were using `AzureServiceTokenProvider` before.

**Comment by jongio** [comment]
@mariojsnunes - Are you wanting to use Azure.Identity with management plane libs or do you want to use on its own? What do you mean by add custom domains?

Here's the repo with all the samples that adapt the Resource Management SDKs with the new Azure.Identity https://github.com/jongio/azidext

**Comment by jongio** [comment]
I have many tests here https://github.com/jongio/azidext/tree/master/net/Azure.Identity.Extensions.Tests/Mgmt

I'm using the same scope that you ref above.

Can you share the API that you are calling with that token?

**Comment by mariojsnunes** [comment]
I was trying to call the API for updating the custom domains of an Azure App Service.

This is the code I tried and couldn't put it to work:

```
var credential = new DefaultAzureCredential();

var token = credential.GetToken(
    new Azure.Core.TokenRequestContext(
        new[] { $"https://management.azure.com/{tenantId}" }));

using (HttpClient client = new HttpClient())
{
    client.DefaultRequestHeaders.Add("Authorization", "Bearer " + token);
    var baseUrl = new Uri($"https://management.azure.com/");
    var requestURl = baseUrl + $"subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{siteName}/hostNameBindings/{hostName}?api-version=2019-08-01";

    client.GetAsync(requestURl)
}
```

My guess is that I needed to use a client like on your samples:
`var client = new ResourceManagementClient(new AzureIdentityCredentialAdapter());`
But I didn't find the one to use, and thought wasn't implemented yet, so I tried calling the rest API manually.

**Comment by jongio** [comment]
Yes, try to do with the AzureIdentityCredentialAdapter and LMK if it works.  If not, let's pair on it when you have some time.

**Comment by jongio** [comment]
@mariojsnunes - Did you get this working?
