### ISSUE TITLE
Find a way to avoid merging some Search models

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#12303]
While the purpose of https://github.com/Azure/azure-sdk-for-net/pull/12302 was to get the public APIs set, we should find a way to implement #12150 to instead not merge types using the generator, which does not support this feature and has no plans to. The public API cannot change, but the implementation may.

At first thought, wrapping types and taking over serialization like I do for `KeywordTokenizer` - but with different types nested therein (or maybe just for the V1 to roundtrip) could work.

**Comment by heaths** [comment]
Moving out of GA as any solution will require significant testing. The public API still wouldn't change.

**Comment by AlexGhiondea** [comment]
Closing this for now.
