### ISSUE TITLE
[Pending service change] [FormRecognizer] Tests: enable ignored tests once service-side issues are fixed

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#12319]
Service-side issues are preventing us from enabling some of the Form Recognizer tests. This work item keeps track of those so we can re-enable them once the corresponding issues are fixed.

**Service issues:**
**1.** Service returns "Unsupported media type" error when multipage form is sent via GitHub URI.
**2. (SOLVED)** Custom form recognition without labels does not return information about blank page.
**3. (SOLVED)** Custom form recognition with labels returns wrong error when an invalid URL is passed to it (expected: 3003, actual: 3014).
**4. (SOLVED)** Service returns 500 response when passing non-existing model ID to `StartCopyModel`.
**5. (FIXED ON SDK SIDE)** Service can return text angle between 180 and 360 in custom form recognition without labels.

Tests to enable:
- [x] `StartRecognizeCustomFormsWithoutLabelsCanParseMultipageForm (true)` (blocked by 5).
- [ ] `StartRecognizeCustomFormsWithoutLabelsCanParseMultipageForm (false)` (blocked by 1, 5).
- [x] `StartRecognizeCustomFormsWithoutLabelsCanParseMultipageFormWithBlankPage (true)` (blocked by 2).
- [ ] `StartRecognizeCustomFormsWithoutLabelsCanParseMultipageFormWithBlankPage (false)` (blocked by 1, 2).
- [x] `StartRecognizeCustomFormsFromUriThrowsForNonExistingContent (true)` (blocked by 3).
- [x] `CopyModelError`; disabled per service team's request (blocked by 4).

**Comment by maririos** [comment]
Validate and follow up again during MQ

**Comment by maririos** [comment]
Still not fixed. Will ping the service about it.
Removing MQ milestone

**Comment by kinelski** [comment]
Reopening this as we still need to re-enable these tests.

**Comment by kinelski** [comment]
It's been 3 years since this issue has been opened and the bug was never fixed on the service side. For this reason, we'll update the tests on our side to reflect the current service behavior:
- `StartRecognizeCustomFormsWithoutLabelsCanParseMultipageForm` will expect an exception.
- `StartRecognizeCustomFormsWithoutLabelsCanParseMultipageFormWithBlankPage` will be deleted since it would be just validating the same exception returned in the first item.
