### ISSUE TITLE
[FormRecognizer] Update Integer properties in generated code if default changes to Int64

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#12321]
## Summary

Blocked by: Azure/autorest.csharp#744

Currently there's an open discussion about defaulting swagger `Integer` types to `long` in generated code (linked above).

## Required changes

In case `int` types are maintained as default, no action is required.

In case the default changes to `long`, changes will be needed in the Form Recognizer SDK in order to [keep them as int](https://github.com/Azure/autorest.csharp#change-a-model-property-type), unless the service team states otherwise.

`FieldValue_internal.ValueInteger` should be kept an `Int64` (#12021).

**Comment by annelo-msft** [comment]
@kinelski , I believe we made the fix for this already, but can you confirm what action is needed and if we can put this back on the backlog?

**Comment by kinelski** [comment]
We have closed a similar issue: #12021.

This one depends on the outcome of CodeGen's discussion (linked in the description). If they decide to keep `int` as the default integer type, it can be closed with no action.

**Comment by kinelski** [comment]
From https://github.com/Azure/autorest.modelerfour/issues/288:
> I just read back over the initial conversation that @pakrym linked in the issue description. It sounds like there isn't anything actionable to do in AutoRest/Modelerfour at this moment, correct?

> @johanste's proposal was mainly to add a linting rule (which @lmazuel filed a request for) and gradually get all service Swaggers to explicitly specify the format for each usage of integer. I got the impression that we want to hold off on making int64 the default for now since that might be an unexpected change for service teams (and SDK library users).

The discussion is being held off, so we have no actionable items on the Form Recognizer SDK side. Going through the integers we get back from the service, we are already doing the right thing:

Values handled as 64-bit integers in the SDK:
- **CopyAuthorizationResult.expirationDateTimeTicks:** marked as `int64` in the swagger.
- **FieldValue.valueInteger:** handled as a 64-bit integer as requested by the service team.

Any reasonable model limit could fit into 4 bytes, so these are handled as 32-bit in the SDK:
- **Models.count**
- **Models.limit**

Forms are not expected to have more than 2147483647 pages as well, so these are 32-bit:
- **TrainingDocumentInfo.pages:** marked as `int32` in the swagger.
- **PageResult.page:** marked as `int32` in the swagger.
- **ReadResult.page**
- **FieldValue.page**
- **DocumentResult.pageRange.items**

We don't expect huge tables either, so these are 32-bit:
- **DataTable.rows**
- **DataTable.columns**
- **DataTableCell.rowIndex**
- **DataTableCell.columnIndex**
- **DataTableCell.rowSpan**
- **DataTableCell.columnSpan**

Other 32-bit values:
- **PageResult.clusterId:** marked as `int32` in the swagger.
