### ISSUE TITLE
[BUG] Outdated net452 imports

### ISSUE THREAD

**Issue by ndrwrbgs** [Azure/azure-sdk-for-net#12327]
**Describe the bug**
https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.Authentication/2.4.0
.NETFramework 4.5.2
Microsoft.IdentityModel.Clients.ActiveDirectory (= 2.28.3)

.NETFramework 4.6.1
Microsoft.IdentityModel.Clients.ActiveDirectory (>= 4.3.0 && < 6.0.0)

**Expected behavior**
This looks _very_ fishy. On 452 we rquire EXACTLY version 2.28.3, but on 461 we don't even ALLOW versions until 2 major versions later? I imagine something didn't get updated somewhere along the line.

**Comment by yungezz** [comment]
hi @xccc-msft is this updated already?

**Comment by xccc-msft** [comment]
@ndrwrbgs It looks #12897 was to relax upped bound. Are you still facing this issue? If so, we could ask help from ClientRuntime team to confirm. Thanks.

**Comment by ndrwrbgs** [comment]
The change didn't affect the package version I spoke of but the other
packages I referenced as additional data. Please see the issue section in
the template.

.NETFramework 4.5.2
Microsoft.IdentityModel.Clients.ActiveDirectory (= 2.28.3)

**Comment by ndrwrbgs** [comment]
![image](https://user-images.githubusercontent.com/10776890/135666058-2d3bee92-6c5d-4625-9910-0dfd82c0d6b6.png)

**Comment by AlexGhiondea** [comment]
I looked into this and there are limitations to the ADAL support that are preventing us from changing the dependencies on .NET 4.5.2. I don't have more context than a [comment in the project file](https://github.com/Azure/azure-sdk-for-net/blob/0b5e5c39831dae4fef35b0a01c2fb2fff5ce7c8c/sdk/mgmtcommon/Auth/Az.Auth/Az.Authentication/Microsoft.Rest.ClientRuntime.Azure.Authentication.csproj#L27) but that is enough to give me pause about expanding this range.

Please also consider that [.NET 4.5.2 will be retired](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework#:~:text=Microsoft%20.NET%20Framework%20follows%20the%20Component%20Lifecycle%20Policy.,certificates.%20This%20algorithm%20is%20no%20longer%20deemed%20secure.) in April 2022 (alongside .NET 4.6 and .NET 4.6.1).
