### ISSUE TITLE
Azure.Management.KeyVault.KeyVaultManagementClientOptions does not follow guidelines

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#12332]
ClientOptions classes should have a `ServiceVersion`, according to https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-versioning. This appears to be some of the reason that tests are failing, as noted in #12211 

/cc @allenjzhang @pakrym @MiYanni @KrzysztofCwalina

**Comment by erich-wang** [comment]
@heaths , having no ServiceVesrion is known issue for mgmt plane as the different entity clients may use different API versions within same RP, current workaround is to disable the warning AZC0008 in project, we plan to address it after public preview.

I doubt it has something to do with #12211, will discuss detail in #12211.

**Comment by allenjzhang** [comment]
Added to backlog AB#4034

**Comment by jsquire** [comment]
Given the age of this and the shift to the track 2 packages, closing this out as stale.  Please feel free to reopen if this is still needed.
