### ISSUE TITLE
[QUERY] Decoupling Authentication / Clients

### ISSUE THREAD

**Issue by jackj93** [Azure/azure-sdk-for-net#12339]
**Query/Question**
Hi guys, I'm trying to use the new `SecretClient` instead of the older `KeyVaultClient` but found out my use case is not yet supported.
To authenticate against KeyVault I used to pass in an access token into the constructor using the older [TokenCredential](https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.tokencredentials.-ctor?view=azure-dotnet#Microsoft_Rest_TokenCredentials__ctor_System_String_) ctor.
The newer `Azure.Core.TokenCredential` does not such operation.

I had extra logic outside of the client related to caching the access token so that I don't always have to go to AAD to acquire the token. Would I have to write my own implementation of the new `TokenCredential` to support my scenario? or is there existing functionality that I'm missing.

Thanks,
Jack

**Comment by AlexGhiondea** [comment]
@jackj93 do you happen to have a code sample of how you are trying to use the `SecretClient`?

**Comment by schaabs** [comment]
@jackj93 The `SecretClient` will take care of caching the tokens it retrieves, and only refresh them as needed. You should be able to use any `TokenCredential` implementation from the [Azure.Identity](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity) library without having to cache or access tokens yourself. I'm not sure what authentication mechanism you are currently using, but most are supported in the Azure.Identity library, if you have questions or run into problems I'd be happy to help.
