### ISSUE TITLE
[QUERY] Create ipv6 public ip adress

### ISSUE THREAD

**Issue by aL3891** [Azure/azure-sdk-for-net#12343]
I'm trying to create a public ipv6 ip address but i can't find a way to specify the ip version, this is what i have 

            var publicIPAddress = azure.PublicIPAddresses
                .Define(basename + "ip")
                .WithRegion(region)
                .WithExistingResourceGroup(resourceGroupName)
                .WithSku(PublicIPSkuType.Standard).WithLeafDomainLabel("test").
                .Create();

Are ipv6 addresses not supported? is there another (f.e. non fluent) way to create it in code?

**Comment by isra-fel** [comment]
@weidongxu-microsoft could you help answer this question? Thanks

**Comment by weidongxu-microsoft** [comment]
@aL3891

Workaround

```
            var publicIPAddress = azure.PublicIPAddresses
                .Define(basename + "ip")
                .WithRegion(region)
                .WithExistingResourceGroup(resourceGroupName)
                .WithSku(PublicIPSkuType.Standard).WithLeafDomainLabel("test");
            (publicIPAddress as IPublicIPAddress).Inner.PublicIPAddressVersion = Microsoft.Azure.Management.Network.Fluent.Models.IPVersion.IPv6;
            publicIPAddress.Create();
```

**Comment by aL3891** [comment]
i see thanks, i guess fluent methods for this are planned? i've ran into some other places where i've needed to fall back on the "inner" versions in the process of setting up a ipv4/ipv6 network, are you taking contributions for fluent configuration methods like this?

**Comment by weidongxu-microsoft** [comment]
Yes. We do take contributions.

You can try it. It is a bit complicated. If you having trouble, let us know.

Interface (you can do similar to `WithStaticIP`)
https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Network/Domain/PublicIpAddress/Definition/IDefinition.cs#L66-L101

Implementation
https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Network/Domain/InterfaceImpl/PublicIpAddressImpl.cs#L252-L255
https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Network/PublicIPAddressImpl.cs#L104-L109

**Comment by aL3891** [comment]
thanks, i'll check it out :)
