### ISSUE TITLE
MetricsClient opens new socket on every request, starving ephemeral ports when doing lots of request to the API

### ISSUE THREAD

**Issue by FreekPaans** [Azure/azure-sdk-for-net#1234]
Hi all,

I use MetricsClient to fetch metrics about my cloud sevices (VMs and web/worker roles). When I'm doing a lot of calls, I've found that there are a lot of sockets open to management.core.windows.net. I've debugged this to the point where I found that every call to the API opens a new ConnectionGroup in the ServicePoint for management.core.windows.net, this causes the connections not being reused but still staying open for (a default of) 100 seconds before they are closed. This can become a problem   fast if you're doing lots of calls in a resource-constrained environment (such as WAWS). 

My current workaround is setting ServicePointManager.MaxServicePointIdleTime to a lower value than 100 seconds, but I don't really like that since it's a global setting and 100 seconds is probably a sane default for other use cases.

Any advice?

Cheers,

-Freek

**Comment by markcowl** [comment]
@FreekPaans Thank you for the feedback.  Assigning to the service team to investigate.

**Comment by FreekPaans** [comment]
Thank you. I should add that this doesn't happen if you reuse the MetricsClient instance, only if you create a new one for every request. Either way, the connections are not cleaned up if you dispose the MetricsClient.

**Comment by asheniam** [comment]
Apologies for the delayed response.  We are planning a broad set of changes in the metrics area to greatly improve the consumption of metrics data.  These changes will go live in the next few months

**Comment by shahabhijeet** [comment]
@FreekPaans please open a new issue if the problem still exists/repros.
