### ISSUE TITLE
Service Bus OnMessage Abandon - ObjectDisposedException

### ISSUE THREAD

**Issue by kspearrin** [Azure/azure-sdk-for-net#1236]
I am using the following code:

    var options = new OnMessageOptions
    {
        AutoComplete = false,
        MaxConcurrentCalls = 1
    };

    m_client.OnMessage( async ( message ) =>
    {
        try
        {
            // await something
            
            message.Complete();
        }
        catch
        {
            message.Abandon();
        }
    }, options );

NOTE: `m_client` is a `SubscriptionClient`.

Whenever `message.Abandon()` is called I get an `ObjectDisposedException` for the `message`:

>An unhandled exception of type 'System.ObjectDisposedException' occurred in mscorlib.dll
>
>Additional information: BrokeredMessage has been disposed.

According to the [docs](https://msdn.microsoft.com/en-us/library/dn130197.aspx), I should be able to do this if I have `AutoComplete = false` for my `OnMessageOptions`.

> If you instantiate the message pump with the AutoComplete property set to true, then during the OnMessage callback you should not perform any disposition operations (for example, Abandon, Complete, Deadletter, etc.) on the message.

`message.Complete()` executes just fine.

NOTE: This is using the `Windows.ServiceBus` package version 2.7.3.

**Comment by kspearrin** [comment]
It seems that switching to `OnMessageAsync()` solved the problems:

    var options = new OnMessageOptions
    {
        AutoComplete = false,
        MaxConcurrentCalls = 1
    };

    m_client.OnMessageAsync( async ( message ) =>
    {
        try
        {
            // await something

            message.CompleteAsync();
        }
        catch
        {
            message.Abandon();
        }
    }, options );

**Comment by markcowl** [comment]
@djrosanova Dan, can you take a look at this?  Closing because the isue seems to be resolved for this customer, and the servicebus dll source code is not in this repository.
