### ISSUE TITLE
Release Azure Cognitive Search 11.1-preview1

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#12372]
### Features
- [ ] FieldBuilder 
- [ ] Spatial types

#### Skillsets

- [ ] Add constructor overloads/initializers/builders to better identify required and optional input and output fields in addition to the model types and their parameters (inputs and outputs).
- [ ] Discuss builders for common skillsets if we can identify them (e.g. automatically generate and hook up output fields of one skill as inputs to another, etc.).

**Comment by tg-msft** [comment]
We've released and everything in the milestone is closed.
