### ISSUE TITLE
[FEATURE REQ] EventHub Emulator

### ISSUE THREAD

**Issue by GeeWee** [Azure/azure-sdk-for-net#12388]
**Library or service name.**
Azure EventHubs
 
**Is your feature request related to a problem? Please describe.**
To run the development locally, it would be wonderful to have the ability to run EventHubs on the developer machine. This request is the same as #7172 which was seemingly closed by accident.

**Comment by serkantkaraca** [comment]
Feel free to provide your support and feedback at https://feedback.azure.com/forums/911458-event-hubs/suggestions/37028737-emulator

**Comment by GeeWee** [comment]
I've upvoted at the link - and if that's the only place where you take this kind of feedback, I guess this can be closed.

**Comment by jsquire** [comment]
@serkantkaraca:  Should this be closed out, or would you like to track it on the backlog as an open feature request?

**Comment by serkantkaraca** [comment]
@jsquire We already have a feature request tracking emulator ask. I believe there is no reason keep this open.

https://feedback.azure.com/forums/911458-event-hubs/suggestions/37028737-emulator

**Comment by jsquire** [comment]
Closing this out, as the Event Hubs team is tracking it elsewhere.

**Comment by drdamour** [comment]
love that we closed stuff cause it was on feedback.azure.com and now that site is dead...wait i do NOT love that

**Comment by miso-ms** [comment]
@jsquire @serkantkaraca: Where is this being tracked? The feedback.azure.com link above seems outdated and this is a valuable feature for our automatic test pipeline.

**Comment by AndersSpringborg** [comment]
Are there any updates on an emulator? Some docker image? 👷🏼 😄
