### ISSUE TITLE
[QUERY] [Storage] How to get SecondaryUri of a blob in v12 API?

### ISSUE THREAD

**Issue by larskn** [Azure/azure-sdk-for-net#12413]
**Query/Question**
With the v11 API we could use `CloudBlob.StorageUri.SecondaryUr`i to retrieve a blob's secondaryUri. The new BlobClient only has the `Uri `property, but not `StorageUri`. How can the SecondaryUri be retrieved?

**Environment:**
 - Azure.Storage.Blobs 12.4.2
 - NET Core SDK 3.1.300, Windows 10 x64
 - Visual Studio 16.6.1

**Comment by jaschrep-msft** [comment]
Hi @larskn. There is currently no mechanism to check the secondary URI of a client once created. What are you attempting to do? Perhaps the library offers another solution to your initial problem.

**Comment by amnguye** [comment]
Hi, please reactivate if there's a follow up to this question. 
> What are you attempting to do?
