### ISSUE TITLE
Tables: Cosmos Tables / Storage Tables protocol discrepancies

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#12426]
# Summary
This is a running list of discovered undocumented differences between the storage and cosmos table REST API implementations.

### Formatting of double typed entity properties
Given a double value with no decimal, such as 1, storage sends the value as "1.0" whereas Cosmos sends it as "1". The storage response format ensures that the type can always be implicitly determined but the Cosmos format does not. This caused a boxed casting exception here - the implicit cast resolves the problem.

Note this can still cause some type ambiguity when dealing with dictionary<string, object> entities.

**Comment by pakrym** [comment]
+ Different query languages

**Comment by christothes** [comment]
dupe of #13552
