### ISSUE TITLE
[Test] Implement tests to achieve test parity

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#12438]
Implement specific tests we don't have, which were identified as part of https://github.com/azure/azure-sdk-for-net/issues/11882

**Comment by maririos** [comment]
Is there a list for the missing tests?

**Comment by annelo-msft** [comment]
@kinelski, could you link to the list of tests you identified as part of #11882?

**Comment by kinelski** [comment]
> 
> 
> Is there a list for the missing tests?

The "list" is the cross-language spreadsheet we have in Teams.

**Comment by annelo-msft** [comment]
Would it be possible to include a link to that here for out team to reference?

**Comment by kinelski** [comment]
> 
> 
> Would it be possible to include a link to that here for out team to reference?

Here it is: https://microsoft.sharepoint.com/:x:/t/AzureDeveloperExperience/ERwfsXEb42RJt1WPS1bBUwUBnvwdAtJPAGDhekRAxwoCIw

**Comment by kinelski** [comment]
Most scenarios have been addressed. Follow-up: #12962.
