### ISSUE TITLE
Getting an error --The api-version query parameter (?api-version=) is required for all requests--while querying with NetworkManagementClient

### ISSUE THREAD

**Issue by ganeshpande** [Azure/azure-sdk-for-net#1243]
I am consuming the NetworkManagementClient class as shown below and getting the error:
  "The api-version query parameter (?api-version=) is required for all requests."
Am I missing anything here? Can someone please help?

var subscriptionCloudCredentials = new TokenCloudCredentials( mySubscriptionId, myAuthToken);
var networkManagementClient = new NetworkManagementClient(subscriptionCloudCredentials, new Uri(myBaseuri));

var networkListResponse = networkManagementClient.Networks.List();

**Comment by ganeshpande** [comment]
This issue was opened in error. I was using different base URI which caused the error.

**Comment by stevenke** [comment]
@ganeshpande can you please elaborate on your answer.  I'm running into a similar situation now (trying to work with Azure Gov) so I need to specify a different base URI.  Is something else require when doing this?
