### ISSUE TITLE
[FEATURE REQUEST] Add StorageTransferOptions overload to BlobClient.Upload

### ISSUE THREAD

**Issue by smithago** [Azure/azure-sdk-for-net#12445]
**Describe the bug**
Is there are option to specify DefaultRequestOptions.ParallelOperationThreadCount or
blobClient.DefaultRequestOptions.ServerTimeout in the new 12XX SDK?

I am assuming this is automatically handled but wanted to confirm. Is there a documentation to help migrate from the older to newer SDK?

Also, NameValidator.ValidateBlobName could not be found in the new SDK.

**Environment:**
 Azure.Storage.Blobs 12.4.3]

**Comment by amnguye** [comment]
Hi,

To specify the thread count like in v11 (e.g. `DefaultRequestOptions.ParallelOperationThreadCount`), when calling `DownloadToAsync` make a `StorageTransferOptions` and pass it to the method `DownloadToAsync`. You can specify the `ParallelOperationThreadCount` by specifying in `StroageTransferOptions.MaximumConcurrency`

For Example:
```
using (FileStream file = File.OpenWrite(path))
                {
                    await downloadingBlob.DownloadToAsync(
                        file,
                        transferOptions: transferOptions);
                }
```

@seanmcc-msft  Do you know where or if we still allow the serverTimeout to be set? Also I don't think we have a `BlobNameValidator` in the V12 library. Can you confirm this?

I think we are currently working on a migration guide (@rishabpoh). For now we have our QuickStart Guide for V12
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet

**Comment by smithago** [comment]
thanks @amnguye. @seanmcc-msft   any updates on the other 2 questions?

**Comment by smithago** [comment]
StorageTransferOptions is not allowed has an input for UploadAsync() internally it is setting it to default before calling the ParallelUploaded. Can we expose this param to the called in UploadAync() also.

**Comment by amnguye** [comment]
Hi,

I did a look around, we don't have an equivalent for `BlobNameValidator` currently. Also looks like we also don't allow the `serverTimeout` to be set. Sorry for the inconvenience.

Looks like the `StorageTransferOptions` is already allowed as a parameter for `UploadAsync` for `BlobClient`

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L648

**Comment by smithago** [comment]
Thanks for the reply @amnguye. I am using BlockBlobClient.UploadAsync()  https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs#L459 
I don't see an option to pass it in. PartitionedUploader initializing it to default.

**Comment by amnguye** [comment]
Ah! Thanks for the clarification. You're right we don't expose it for `BlockBlobClient.UploadAsync`.

For now a mitigation for this is to use the regular `BlobClient` to upload. `BlobClient` will also upload a Block Blob. Sorry for the inconvenience.

Let me add label this issue as a feature request, and also retitle this issue to something more appropriate with the ask.

@seanmcc-msft Is this a doable thing, since we already do it for `BlobClient.Download` ?

**Comment by seanmcc-msft** [comment]
Here is an example of setting server-side timeouts:

```
    public class TimeoutPolicy : HttpPipelineSynchronousPolicy
    {
        private int _timeout;

        public TimeoutPolicy(int timeout)
        {
            _timeout = timeout;
        }

        public override void OnSendingRequest(HttpMessage message)
        {
            message.Request.Uri.AppendQuery("timeout", _timeout.ToString());
        }
    }

    class Program
    {
        static string connectionString = "";

        static async Task Main(string[] args)
        {
            BlobClientOptions blobClientOptions = new BlobClientOptions();
            blobClientOptions.AddPolicy(new TimeoutPolicy(10), Azure.Core.HttpPipelinePosition.PerCall);
            BlobContainerClient blobContainer = new BlobContainerClient(connectionString, "mycontainer5", blobClientOptions);

            await blobContainer.CreateAsync();

            await blobContainer.DeleteAsync();
        }
    }
```
@amnguye is the issue that `StorageTransferOptions` is missing from `BlockBlobClient.Upload()`?  I think the new title might be wrong.

**Comment by seanmcc-msft** [comment]
This has been addressed in the STG 73 branch, which we are planning to release next week:

- https://github.com/Azure/azure-sdk-for-net/blob/feature/storage/stg73base/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs#L420
- https://github.com/Azure/azure-sdk-for-net/blob/feature/storage/stg73base/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs#L468
- https://github.com/Azure/azure-sdk-for-net/blob/feature/storage/stg73base/sdk/storage/Azure.Storage.Blobs/src/Models/BlobUploadOptions.cs#L41
