### ISSUE TITLE
Change in recorded responses makes diff'ing session records extremely difficult

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#12455]
The fix for bug #12158 in PR #12190 ends up putting response bodies all on one line, which makes diff'ing session records for expected changes practically impossible. Wouldn't a better approach be to fix the `RecordMatcher` to handle newlines correctly? What makes DigitalTwins different? In neither Key Vault or Search I've seen this problem, so maybe something specific with DigitalTwins they need to handle, like I had to for sanitizing Search bodies for Storage keys?

/cc @tg-msft @AlexGhiondea

**Comment by pakrym** [comment]
We switched to only storing formatted body JSON if we can read it back into the exactly the same value as the original body. 

Otherwise the test framework would end up modifying the body value that has all sorts of consequences that are impossible to fix with a RecordMatcher change only.

**Comment by heaths** [comment]
Since Search's responses were stringified now, why were they working otherwise? Is this just about newlines within the body causing issues? Could those be encoded specifically to avoid the original issue while maintaining diff'ability?

**Comment by heaths** [comment]
Discussing this offline, we found that in *RecordEntry.cs* in or around line 194 where `memoryStream.ToArray()` is compared byte-for-byte with `requestBody`, the etag is encoded differently, as shown below:

![image](https://user-images.githubusercontent.com/1532486/83678705-015eff80-a593-11ea-9ea7-04b22e1d2429.png)

This falls through to encoding the whole thing as a string and writing as-is.
