### ISSUE TITLE
SearchResources do not clean up indexers or data source connections

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#12457]
Need to extend the clean up mechanics of SearchResources to also delete indexers and data source connections, but in a deterministic and consistent order (so don't `Task.WhenAll` everything). One idea would be similar to what Key Vault does and register not resources (like Key Vault), but delegates that capture the client and resource to clean up in a fixed stack order. Create the resource, register it with `SearchResources` to clean up (an internal stack of `Action`s, for example, and combine that deterministically with deleting other Search resources.

/cc @tg-msft

**Comment by heaths** [comment]
We should also evaluate whether we're cleaning up all indexes in all successful and failed cases. We've had a number of live runs where, for example, we went over requests/time and then many other tests reported we were over our quota.

**Comment by AlexGhiondea** [comment]
@Mohit-Chakraborty is this still an issue?

**Comment by Mohit-Chakraborty** [comment]
I will take a look. Assigning to myself to investigate.

**Comment by pallavit** [comment]
@ShivangiReja could you please investigate if this is still an issue?

**Comment by JimSuplizio** [comment]
Hi @heaths, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
