### ISSUE TITLE
ServiceBusQueueClient the cancellation token is not signalled when processing exceeds MaxAutoRenewDuration

### ISSUE THREAD

**Issue by dazinator** [Azure/azure-sdk-for-net#12461]
**Describe the bug**

When using `ServiceBusQueueClient` to listen / process messages from a queue,

```

 _client.RegisterMessageHandler(async (message, token) =>
{
  // do work here
}

```

The message handler delegate is invoked to process the incoming message and it is supplied with a cancellation token `token` in the above sample.

This cancellation token should be signalled when processing of the message needs to be cancelled. It is particularly useful to long running processing tasks that don't want to process longer than they need to.

However this cancellation token is not signalled in a scenario I expected it to be.

Given:
- The queue has a `LockDuration` of 1 minutes.
- `MessageHandlerOptions` has `MaxAutoRenewDuration` set to 2 minutes:

```csharp
 var messageHandlerOptions = new MessageHandlerOptions(async (args) => await onException(args.Exception))
            {                         
                MaxConcurrentCalls = 1,
                AutoComplete = false,
                MaxAutoRenewDuration = TimeSpan.FromMinutes(2),      
            };
```
And you then process the recevied message for 1 hour:

```
_client.RegisterMessageHandler(async (message, token) =>
            {
              Task.Delay(TimeSpan.FromHour(1), token);
               message.CompleteAsync();
            }, messageHandlerOptions);
```

The cancellation token is not signalled after 2 minutes. The processing is allowed to continue for the full hour. When CompleteAsync() is called after the hour has elapsed, at that point you get an exception about the lock having expired. This is incredibly wasteful given we knew the lock will have expired after 2 minutes we should have signalled cancellation.

**Expected behavior**

I think it would make sense for cancellation to be made pessimistic based on `MaxAutoRenewDuration` - if we know the processing time has exceeded the lock duration, and `MaxAutoRenewDuration`, then the lock should be considered expired, and at that point cancellation could be signalled. If you wanted to add on a buffer (e.g MaxAutoRenewDuration  + LockDuration) before signalling cancellation then that would still be preferable to not cancelling it all, and letting it fully process before throwing an exception.

**Actual behavior (include Exception or Stack Trace)**
Handler is allowed to run for great lengths of time even though the lock expired hours ago. 

**To Reproduce**

**Environment:**
 -     `<PackageReference Include="Microsoft.Azure.ServiceBus" Version="4.1.3" />`
 - 
> .NET SDK (reflecting any global.json):
 Version:   5.0.100-preview.4.20258.7
 Commit:    65f0fc2cad

 - IDE and version : Microsoft Visual Studio Community 2019 Preview

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @MiYanni

**Comment by nemakam** [comment]
@dazinator , that is an interesting expectation, but that is not designed that way. The cancellation token is cancelled only when the queueClient is closed.
But to think of it, I don't know if its perfect to have that design. Think of this scenario:
AutoComplete = false.
Handler = 
```
async()
{
    msg.complete();
    task.delay(1 hour);
}
```
In this case, though auto renew stopped after 2 mins, it should be fine as you do not plan to complete the message beyond that.

**Comment by nemakam** [comment]
Going to close this issue as by-design

**Comment by dazinator** [comment]
@nemakam 
Thanks for response.
I am surprised that its acceptable to you, to allow processing to continue even when there is no chance of lock renewal and you know there will eventually be an error on CompleteAsync() of the message. Why let processing reach that point if you could signal that fact earlier? It just seems wasteful no? Is it by design to be wasteful?

In the example you responded with there are several points:

1. Why would the cancellation token be needed after CompleteAsync() is called? Arent you done with the message at that point? In which case nothing after CompleteAsync (i.e your example task.delay) would benefit by using the cancellation token and it shouldn't require it.

2. If not satisfied with above, then provide a seperate cancellation token on the message itself to indicate auto lock renew expiry. Or don't, and join the current cancellation token source (that represents the client connection) to another cancellation token source that represents message auto lock renew expiry, and dont signal the latter after CompleteAsync() is called. 

I guess there are multiple ways to deal with this, I've added by own code for this, but I'm just surprised that's it by design to be so wasteful!

**Comment by nemakam** [comment]
Wow, lets take it slowly. 
In "your" use-case it makes sense. But doesn't mean it applies to every use-case.
Let's say a machine wants to shut down. That's the only time we expect that queueClient.Close() is called. If you want to do a clean shut down and want to stop the handler, that's when the cancellation token is used. You may have completed the message on the broker, but doesn't mean you are done processing it. Again, "you" may be done, but not necessarily every one. 
And its not super simple to change the SDK and go ship a new one with a new design which may help a couple of customers. Doing this becomes a breaking change. And I generally expect customers to have auto-renewal going on for longer than the duration of the handler. Its in-general not best practice to have such a design to not account for longer running handlers in your "auto-renewal" calculation. 
And again, if you really want to fit it to your use-case, then you can always create your own cancellation token since you already know how long the auto renewal is going to happen.

**Comment by dazinator** [comment]
> And its not super simple to change the SDK and go ship a new one with a new design which may help a couple of customers.

I'm not daft, I promise. I'm not advocating this. I'm advocating a more widley applicable feaure. I'll elaborate further below on the scenario.

> Doing this becomes a breaking change

Doing what precisely? Whether its a breaking change depends on how its implemented. I made some suggestions above, one of which wasn't really breaking as it would be adding a new property to message to allow the handler to opt in to detecting when the lock was lost.

> You may have completed the message on the broker, but doesn't mean you are done processing it. Again, "you" may be done, but not necessarily every one.

If the cancellation token was only signaled due to lock lost prior to CompleteAsync() being called, then in the normal successful lock aquisition case nothing changes. The breaking change in this scenario would be a potential graceful exit rather than a lock lost exception which is a behavioural breaking change but that could be solved by enabling this behavioral change to be opted into via a boolean setting on message handler options alongside the max auto renew lock timespan setting itself. Or perhaps forget all that and just adding a new way to detect lock expiry prior to message completion would be best seperate from the current cancellation token? I can keep supplying plenty of ideas for implementations but I guess they are likely not needed.

> And I generally expect customers to have auto-renewal going on for longer than the duration of the handler. Its in-general not best practice to have such a design to not account for longer running handlers in your "auto-renewal" calculation.

In the general case I agree with you that message processing shouldn't exceed the auto renewal duration. If it did your system wouldn't work so this is more of a requirement really. Its the exceptional cases when it does exceed the auto renewal duration where the problem comes and this is the crux of issue that lead me here. Exceptional cases such as storage or network performing slower or a sudden unexpected load (perhaps a load tester went crazy). This can happen from time to time. Transient problems with dns or other things that clear after a time. These types of ,"outages" or "degradations" are not so easy to predict and not even desirable to take account of when calculating a max lock renewal time because they are not normal day to day events and shouldnt really happen but in real systems, the occasionally do. Even Azure goes down sometimes. The funny thing is, when a resource such as network or storage is underperforming this is precisely the time you dont want to be using it unnecessarily, and sadly this is precisely the time where the current behaviour of this sdk results in more usage than necessary not less like in this following scenario:

1. Job in normal case takes 1 hour to process message. Processing depends on external resource such as storage.
2. We calculate 2 hours for auto renew. We've added some leeway based on our best "guess" of how it could fluctuate in normal system day to day usage. When things are working and no outages, 100% of messages processed within this time.
3. The job runs fine until one day the storage has an issue and is performing slowly. The message processing takes 3 hours today instead of 1 hour.

In this scenario what do you see:

 - The job lost the lock after 2 hours and it wasn't renewed. Yet it continued to process for a further hour whilst storage was slow, accessing storage all the while. 
 - As the lock was lost at 2 hours, the message is available on the queue again. If you have another concurrent reader it will pick it up and that means you now have 2 jobs running and double the load on storage for an hour, two jobs processing the same message the first that can't be completed because the lock was returned both accessing the resource under strain.

Now suppose its not just one job thats impacted by storage issue today, but its 10.. Making the load on an already under performing resource even greater adding to the problem. This in turn means the duplicate job instances now take 4 hours to run instead of 3. You can see how such a situation is undesirable or could escalate or make the issue worse.

Yet if we had a way to detect when the lock expired and was not renewed after 2 hours, we could:

1. Have this job abandon the message and cancel the processing when it lost the lock prior to calling completeasync.
2. Yes another reader can now pick up the message but atleast we terminated processing of the first reader so it won't be needlessly processing adding additional strain at a time we least desire it.

> And again, if you really want to fit it to your use-case, then you can always create your own cancellation token since you already know how long the auto renewal is going to happen.

As per my previous comment this is what I have already done. However you (the sdk) knows more about auto renewal and lock acquisition  process than me. Perhaps there is a new setting in future that I am not aware of. Its in the best position to signal me when the lock has expired and the message can no longer be completed.

If you aren't interested in this then fair enough, but I don't think my concerns or my request is based on any special requirement if the requirement is simply to avoid unnecessary message processing, a lot of customers might want that.

**Comment by nemakam** [comment]
Thanks for the detailed response and I appreciate it. I do agree with the use-case. 

The dismissal earlier was not about the use-case but for the change going forward since I was hoping that it is an easy change that can be done by the SDK user. 

But given the current situation (and future plans for the service), I think it might be in good interest to have this support on the SDK itself. I will reopen this issue and place it as a feature-request. There is no ETA I could provide on this right now. 
If you are interested, please do raise a PR on this.

**Comment by nemakam** [comment]
If the token is strictly based on `MaxAutoRenewDuration`, then I'm still not very sure it is worth it. But things might get more interesting if we can trigger the cancellationToken if the link is closed and we will never be able to complete the message even though auto-renew duration isn't reached. Essentially, if the SDK knows that this message can never be completed, then we could trigger the cancellation.

**Comment by axisc** [comment]
This is better served as a feature request for the new SDK.

Assigning to @JoshLove-msft to consider enabling this feature in upcoming Track 2 SDK. Feel free to reach out to @shankarsama and me to discuss.

**Comment by jsquire** [comment]
@JoshLove-msft, @ramya-rao-a:  Do we have a decision on whether this request is something that we'd like to include,  or is this still under consideration?

**Comment by JoshLove-msft** [comment]
I am hesitant to cancel the cancellationToken when the lock is no longer being autorenewed. For one thing, the message may still be locked for an additional lockduration, so operations would continue to work but we would be signalling that they wouldn't. I can see the value in introducing another cancellationToken that is specific to auto lock renewal though.

**Comment by dazinator** [comment]
I currently create my own linked cancellation token to cover this case incorporating MaxAutoLockRenewalDuration plus lock duration. This is the token I think would be useful for the client to supply out of the box - as a seperate token I agree makes sense. message.LockedUntilTimeUTC isn't that useful on its own because locks can be auto renewed.
