### ISSUE TITLE
[Errors] Improve error messages where service message is unclear

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#12478]
Case | Error Message | Suggested Improvement
-- | -- | --
Pass   useTrainingLabels=true when no labels are in blob storage | {                   code:   '2100',                   message:   "Can't find any OCR files for training."               } | [Teams Discussion](https://teams.microsoft.com/dl/launcher/launcher.html?url=%2f_%23%2fl%2fmessage%2f19%3a88f2d9dea2344075b5d4bc34d82a3d1c%40thread.skype%2f1590517765400%3ftenantId%3d72f988bf-86f1-41af-91ab-2d7cd011db47%26groupId%3d3e17dcb0-4257-4a30-b843-77f47f1d4121%26parentMessageId%3d1589497190310%26teamName%3dAzure%2520SDK%26channelName%3dService%2520-%2520Form%2520Recognizer%26createdTime%3d1590517765400&type=message&deeplinkId=21bc841d-5312-4459-9cfa-b48ed14cb662&directDl=true&msLaunch=true&enableMobilePage=true&suppressPrompt=true)
Pass local   filepath to RecognizeXxFromUri method | Status:   400 (Bad Request) Content:   {"error":{"code":"1003","message":"Parameter   'Source' is not a valid Uri."}}    From   <https://stackoverflow.com/questions/62043368/startrecognizecustomformsfromuri-returns-parameter-source-is-not-a-valid-uri> | See [Teams Discussion](https://teams.microsoft.com/l/message/19:88f2d9dea2344075b5d4bc34d82a3d1c@thread.skype/1590592997083?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1590586870985&teamName=Azure%20SDK&channelName=Service%20-%20Form%20Recognizer&createdTime=1590592997083)
Make sure that GetModelIdAsync returns a sensible error in the event that an account limit is exceeded (issue #11462) | -- Need to check | -- |

Another one to look at https://github.com/Azure/azure-sdk-for-net/issues/12813

**Comment by maririos** [comment]
> Pass useTrainingLabels=true when no labels are in blob storage

Issue https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/7310258 filed for service team to improve the message.

> Pass local filepath to RecognizeXxFromUri method

Pinged service team to see if they can improve the error mesage.

> Make sure that GetModelIdAsync returns a sensible error in the event that an account limit is exceeded

Error message is enough.
`{"error":{"code":"1014","message":"The model count for the subscription has exceeded limit. Delete old models before creating new ones."}}`

**Comment by maririos** [comment]
>Pass local filepath to RecognizeXxFromUri method

Issue https://msazure.visualstudio.com/DefaultCollection/Cognitive%20Services/_workitems/edit/7587655/

> AAD Token against a region endpoint.

Following up on issue #12813
