### ISSUE TITLE
[text analytics] update readme

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-net#12472]
- [ ] Consider adding a key concept on DocumentErrorHandling (python's is [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/textanalytics/azure-ai-textanalytics/README.md#document-error-handling), but .net's would tell the user to check the .errors of batch)
- [x] Make sample links in readme absolute, not relative. This is potentially causing problems when being uploaded to docs.microsoft.com

cc @czubair

**Comment by maririos** [comment]
Thank you so much Izzy!

**Comment by maririos** [comment]
>Consider adding a key concept on DocumentErrorHandling (python's is here, but .net's would tell the user to check the .errors of batch)

Because errors work different if it is a single vs batch method, we included the error information in the later. https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/textanalytics/Azure.AI.TextAnalytics#return-value-collection
