### ISSUE TITLE
Folders with space in name are packed as %20 in the Cloud Service Package

### ISSUE THREAD

**Issue by astaykov** [Azure/azure-sdk-for-net#1251]
Using SDK 2.2, 2.5 or 2.6 (do not have other versions to confirm), with either Web or Worker roles, if I have a folder name that contains spaces, those are wrongly encoded into %20 when the cloud service package is created.
The problem is illustrated here:
![cloudservice_issue](https://cloud.githubusercontent.com/assets/1152756/8639738/ecb2fe9c-28e2-11e5-9cdc-a203b9cb1bfe.png)

**Comment by markcowl** [comment]
@astaykov This repo is for azure management sdks - the visual studio tooling is managed elsewhere.  Can you please raise this issue in the appropriate forum?
