### ISSUE TITLE
[BUG]Application Insights Dependency Logging setting incorrect parentId for Blob storage calls from Storage SDK

### ISSUE THREAD

**Issue by jegour** [Azure/azure-sdk-for-net#12511]
**Describe the bug**
Using Azure.Storage.Blobs v12.4.3, Application Insights Distributed Tracing functionality doesn't seem to be working correctly. The operation_ParentId value for the dependency log statements for each blob call is not populated correctly. It does not correlate to the id value for the Request it's being called from. In fact, multiple calls from the same parent Request don't even have the same value of the parent id. This is breaking properly placing the operations in the trace. In fact, in Application Insights timeline view they just show up at the bottom.

This dependency logging worked correctly with the legacy v11 of the SDK. It was when we upgraded from that to v12.4.3 that we started seeing issues.

**Expected behavior**
The operation_ParentId value logged for blob calls through the Storage SDK should match the "id" value logged for the Request the blob call is coming from. 

**Actual behavior (include Exception or Stack Trace)**
The operation_ParentId value is not the same as the id of the parent Request. It's not even consistent for all calls from the same Request.

**To Reproduce**
1. Make a call to a blob store using the Storage SDK from a system using Application Insights telemetry. BlockBlobClient.UploadAsync is a method you could call.
2. Check the Application Insights Request and Dependency logs for an operation calling this. The dependency blob calls will have the correct operation_Id but incorrect operation_ParentId.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.4.3 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure Service Fabric using Windows 10 OS with Asp.Net Core 3.1 runtime.
 - IDE and version : Visual Studio 16.6.0

**Comment by amnguye** [comment]
Hi,

Just to clarify Parent id of Application Insights is the equivalent to the request id(x-ms-request-id) of the request to storage? Also another clarification when you mean multiple requests from the same parent id, do you mean when you do a large Upload or Download, and there's multiple requests that need to go to storage, you're saying that they should all have the same parent id?

Does this only happen for Upload or Download? (if so I suspect it might be expected behavior due to parallel upload/download)

**Comment by jegour** [comment]
The Parent Id is not equivalent to the request to storage. That is would be the id of the "dependency" log. The parent id is equivalent to the request id of the request from which the request to storage was made. To help clarify, if I have controller that makes a call to the blob storage using the blob client SDK, the parent id would be the request id of the request to the controller. 

In terms of multiple requests, what I mean would be a situation where I check for existence of the blob first (which manifests as a HEAD operation) and then actually upload to the blob (which manifests as a PUT operation). As both were triggered from the same Controller call (i.e. same request) they should have the same parent id. 

I have also confirmed it happens for both upload and download. 

Just to clarify too, the description I gave above about how I expect the parent id to work is how it worked in version 11.

**Comment by amnguye** [comment]
Hi,

I can see why you think the Azure Blob Storage Client SDK would be the cause to this problem, due to upgrading from v11 to v12 not having the same results in Application Insights. However in the Azure Storage Client libraries, **we don't have any control over setting the parent id in Application Insights.** This is starting to sound more and more like Application Insights has not adapted to the v12 library.

**Comment by jegour** [comment]
Ok so who would I submit the bug too then?

**Comment by amnguye** [comment]
Hi,

Sorry I deleted my previous message when I should have just editted it.

I can see why this looks like a regression bug against v12, when v11 was giving you the parent id you were expecting. However Azure Blob Storage Client SDK does not set the parent id in Application Insights. It also does not have access to the controller that makes the call to Blob Storage.

So when making multiple requests, on our side we have a request id (x-ms-request-id) returned for each request from the service. We don't set any parent id. It sounds like the Controller Call in Application Insights is not setting the parent id as you expect to be. However the SDK does not have any way of telling Application Insights on how it should set the Parent ID.

Sorry if I miss the point on this bug. However this is sounding like a bug against Application Insights not correctly setting the parent id

**Comment by jegour** [comment]
The confusion for me is it rooted specifically in the new SDK. So clearly something changed that would need to be communicated from storage SDK to the Application Insights team. I worry if I just file a bug to Application Insights they're goin to tell me that I need to talk to storage SDK since updating the SDK caused it.

**Comment by amnguye** [comment]
Waiting on resolution from https://github.com/microsoft/ApplicationInsights-dotnet/issues/1915

Please reactivate if there's a bug on the sdk storage side.
