### ISSUE TITLE
[BUG] DownloadAsync on a Blob with HttpRange of 0- doesn't forward header to azure which causes the client to download the whole file

### ISSUE THREAD

**Issue by watermelonpizza** [Azure/azure-sdk-for-net#12545]
**Describe the bug**
When calling `DownloadAsync` on a `BlobClient` passing through a `HttpRange` of `0` offset and `null` length (the default request a browser will make on initial contact) causes the range or `x-ms-range` header to be ignored and will cause the consumer of the DownloadAsync call to download the entire file with a response of 200 OK instead of 206 Partial Content.

**Expected behavior**
The DownloadAsync call to add the x-ms-range header to the request to the blob store if the HttpRange value is passed through.

**Actual behavior (include Exception or Stack Trace)**
Context: I have an application that streams a blob through to a browser however I cannot get it to work with video/audio etc. files as the range headers aren't being passed through.

Sample request of DownloadAsync with HttpRange of 0- 

Note: no Range or x-ms-range header
```
GET http://127.0.0.1:10000/devstoreaccount1/honeydew/98kc9.mp4 HTTP/1.1
Host: 127.0.0.1:10000
x-ms-version: 2019-07-07
x-ms-client-request-id: 65c0fe59-febf-4759-936e-a6362d7e2a09
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.4.2 (.NET Core 3.1.4; Microsoft Windows 10.0.18363)
x-ms-date: Fri, 05 Jun 2020 11:37:19 GMT
Authorization: SharedKey devstoreaccount1:W+L0g2wGQ66mpDs4m+YKhAlyLjidZvh+ZydcFdXBtu0=
Request-Id: |fd915bac-4a5a37da2d0003bf.
```
*Returned*
```
HTTP/1.1 200 OK
Content-Length: 179529263
Content-Type: video/mp4
Last-Modified: Fri, 05 Jun 2020 11:12:20 GMT
Accept-Ranges: bytes
ETag: "0x8D8094150CD20F0"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 7a7feb9c-17ec-407f-b001-b0a4e256a725
x-ms-version: 2019-07-07
x-ms-tag-count: 0
x-ms-creation-time: Fri, 05 Jun 2020 11:11:15 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
x-ms-server-encrypted: true
Date: Fri, 05 Jun 2020 11:37:25 GMT
```

*Browser initiated request to my dotnet application*
```
GET https://localhost:5001/r/98kc9 HTTP/1.1
Host: localhost:5001
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.13 Safari/537.36 Edg/84.0.522.5
Accept: */*
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: video
Referer: https://localhost:5001/98kc9
Accept-Language: en-AU,en;q=0.9
Range: bytes=0-
```
Note the range request the browser make. This isn't passing down to the azure storage even if I pass in a valid HttpRange class.

*Non 0- range request (working normally)*
```
GET http://127.0.0.1:10000/devstoreaccount1/honeydew/98kc9.mp4 HTTP/1.1
Host: 127.0.0.1:10000
x-ms-version: 2019-07-07
x-ms-range: bytes=178421760-
x-ms-client-request-id: 13331eb8-8232-453e-a661-b35b249612b1
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.4.2 (.NET Core 3.1.4; Microsoft Windows 10.0.18363)
x-ms-date: Fri, 05 Jun 2020 11:37:59 GMT
Authorization: SharedKey devstoreaccount1:aopgcw/YaP0oSlKIdCDwwCnNHxH1Rm5/SPU+wXYchrY=
Request-Id: |fd915baf-4a5a37da2d0003bf.
```

The response from azure
```
HTTP/1.1 206 Partial Content
Content-Length: 1107503
Content-Type: video/mp4
Content-Range: bytes 178421760-179529262/179529263
Last-Modified: Fri, 05 Jun 2020 11:12:20 GMT
Accept-Ranges: bytes
ETag: "0x8D8094150CD20F0"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 133902ee-c244-4c38-a322-a62a18bc9d9e
x-ms-version: 2019-07-07
x-ms-tag-count: 0
x-ms-creation-time: Fri, 05 Jun 2020 11:11:15 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
x-ms-server-encrypted: true
Date: Fri, 05 Jun 2020 11:38:00 GMT
```

*Browser initiated request*
```
GET https://localhost:5001/r/98kc9 HTTP/1.1
Host: localhost:5001
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.13 Safari/537.36 Edg/84.0.522.5
Accept: */*
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: no-cors
Sec-Fetch-Dest: video
Referer: https://localhost:5001/98kc9
Accept-Language: en-AU,en;q=0.9
Range: bytes=178421760-
```

Note the range header is not a default(HttpRange) which I am assuming is why it's sending it correctly this time

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a blob client pointing to a file in azure blob storage
2. call the blob client DownloadAsync method. e.g. `await blob.DownloadAsync(new HttpRange(0, null), cancellationToken: cancellationToken)`
3. Monitor the http made by the library (I used Fiddler to monitor http requests on my machine)

**Environment:**
 - Azure.Storage.Blobs 12.4.2
- dotnet info 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
 - Visual Studio 16.6

**Comment by amnguye** [comment]
@kasobol-msft Could you take a look at this?

**Comment by kasobol-msft** [comment]
@watermelonpizza I'm not sure what you're trying to achieve by sending `0-` range as it by definition means "send me all bytes from position 0 to the end of the blob" (that's the reason we treat this equally with range not being specified at all).

Consider the following samples with and without `0-` range:

![image](https://user-images.githubusercontent.com/61715331/84201687-e7269500-aa5c-11ea-9691-91ea1645f691.png)

![image](https://user-images.githubusercontent.com/61715331/84202137-0ae9db00-aa5d-11ea-9e54-5a8849183bdb.png)

**Comment by watermelonpizza** [comment]
@kasobol-msft Hmm I guess the upstream server being the azure blobs response difference between the 200 OK and 206 Partial Content would be one of the differences I was expecting. 
For example, I was using the azure store response code as the code I would return back to the client `Response.StatusCode = response.GetRawResponse().Status`
(upstream and client being `browser (client) <-> my app <-> azure blobs`

Right now I am hard coding the response StatusCode to 206 if the client range header exists, but I guess it's no big deal. Also due to my lack of understanding on range headers I've thought about this more and this may not be an issue as much as I thought ^.^

I should be setting a maximum range allowed upstream to azure from my app so that large files stream down in smaller chunks and thus will be a quicker response back to the client with say a < 10MB range instead of `0-`. I.e. the browser will say give me everything then my app will cap that range request down to some determined size like 10MB back to the azure blob and forward only that 10MB back to the browser which should then request the next 10MB of data.

So I guess we can close this issue if you agree here unless the StatusCode issue might be a change to change?

thanks 🙂

**Comment by seanmcc-msft** [comment]
@watermelonpizza, I'm going to close this issue.  Please feel free to reopen if you have any more questions.
