### ISSUE TITLE
Add an auto updated list of latest package versions for ApiCompat

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#12546]
Currently we run ApiCompat against packages listed in https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Packages.Data.props

Because this list is also used for dependency version management in the repo it forces us to lift dependencies of shipping package just to be able to run ApiCompat against them.

It's also very easy to forget that this version needs updating after shipping.

This should be easily integrateable into update version script we have right now.

@weshaggard @chidozieononiwu

**Comment by weshaggard** [comment]
I'll take a look at adding this as part of our package index updating.
