### ISSUE TITLE
Add CI validation to ensure sample links use absolute links

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#12559]
Sample readme pages defined in the repo get uploaded to the docs sample site. However the corresponding sample md files are not uploaded to the docs site. Thus using relative links results in broken links on the docs site:
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azuresecuritykeyvaultkeys-samples/
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azurestoragecommon-samples/
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azurestorageblobs-samples/
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azurestoragequeues-samples/
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azurestoragefilesshares-samples/
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azure-app-configuration-client-sdk-samples/
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azuremessagingservicebus-samples/
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azurecore-samples/

It would be great if we have a CI step that enforces absolute links in these sample readme files.

**Comment by sima-zhu** [comment]
The issue has been addressed. Closed it
