### ISSUE TITLE
[FEATURE REQ] provide defaults for BlobsModelFactory.BlobItemProperties accessTierInfered

### ISSUE THREAD

**Issue by henriblMSFT** [Azure/azure-sdk-for-net#12586]
**Library or service name.**
What library or service is this request related to? Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
accessTierInfered doesn't have a default value and always need to be specified in unit tests
What feature would you like to get added? What problem is it solving?
provide default values to make unit tests cleaner.

```csharp
BlobsModelFactory.BlobItemProperties(true, contentLength: 100);
```
would become
```csharp
BlobsModelFactory.BlobItemProperties(contentLength: 100);
```

**Comment by seanmcc-msft** [comment]
Hi @henriblMSFT, we'll work on getting a fix out soon.

**Comment by seanmcc-msft** [comment]
This may require a generator change, making accessTierInfered in the swagger readme switches the type from a bool to a bool?, which I believe is breaking.

**Comment by seanmcc-msft** [comment]
This support was added - https://github.com/Azure/azure-sdk-for-net/blob/c027985bed0680e5af986e05c5e48fc74053af5d/sdk/storage/Azure.Storage.Blobs/src/Models/BlobsModelFactory.cs#L170

**Comment by seanmcc-msft** [comment]
This is a simple fix, we should address this.

**Comment by JimSuplizio** [comment]
Hi @henriblMSFT, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
