### ISSUE TITLE
[BUG] Azure.Storage.File.Shares: ClearRange may be causing issues with Word files

### ISSUE THREAD

**Issue by Oredna** [Azure/azure-sdk-for-net#12589]
**Describe the bug**
When using the  Azure.Storage.Files.Shares i try to get file from cloud, then ClearRange(), and UploadRange(). After that the file won't open in Microsoft Word. But when I use Create() first, then use ClearRange() and UploadRange(), the file functions normaly. So the bug is only for files uploaded to the Azure Storage manualy. If i do it tru the library it works fine. I have to Download the file to stream, then delete it, create blank file and populated with UploadRange().

**Expected behavior**
I don't know if UploadRange() and ClearRange() are limited to only files created with Create(), but I don't think this is the case.

**Actual behavior (include Exception or Stack Trace)**
Update the file, and to be able to open it with word after that.

**To Reproduce**
```
using (MemoryStream stream = new MemoryStream(data))
        {
            //file.ClearRange(new Azure.HttpRange(0, stream.Length));
            file.Delete();
            file.Create(stream.Length);
            file.UploadRange(new Azure.HttpRange(0, stream.Length),stream);
            stream.Dispose();
        }
```
If i use the ClearRange it make the file unusible.

**Environment:**
Azure.Storage.Files.Shares 12.2.2.
Windows
Visual Studio 16..0.30114.105

**Comment by amnguye** [comment]
Hi,

Sorry for the late reply. I don't think I was able to repro you exact problem however I was running into a problem where when I tried to upload range after, and it has having trouble uploading there. However they error was a "The request body did not contain the specified number of bytes. Got 0, expected 20,379", which I will need more time to investigate.

Is it possible if you could provide me a sample word doc you were running? Also could you enable logging(https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging) or provide a fiddler trace of what's happening. I find it odd that you have different behavior between the sdk and the portal.

**Comment by Oredna** [comment]
Yes I think the problems have something in common. I will make a simple app, so I don't have to send the hole app. And I will enable logging. I will try to get it tomorrow. Where do I have to upload it, is one drive or repo here ok?

**Comment by seanmcc-msft** [comment]
Why are you calling `ClearRange()` before deleting the file?  I'd recommend just deleting the file and then recreating it.

**Comment by Oredna** [comment]
Because I want to update the whole file. I don't what to search or and fined the changes. It can be done as i showed that you can save the new content in a stream delete file, crete it and populated. But that call for deleting and creating. I dont what do delete the file. I want to "clean it" then populated with the new memory stream. The delete way is just bypassing. I want this to happen - get new stream, clear range of a file, then upload range - 2 functions. That way I get not functioning file. So if i want to update it, now I have to - delete it, then create, then upload the range - 3 functions. Maybe I am using them the wrong way?

**Comment by seanmcc-msft** [comment]
Hi @Oredna, I believe the issue is the HttpRange you are passing into `ClearRange()`.  You need to make sure you are clearing the entire file, previously you could have written data past the index of your new stream length.

I think the solution is to call `file.GetProperties()` to determine the file length, and then use the file length to build the HttpRange:

```
// Get File properties
Response<ShareFileProperties> propertiesResponse = await file.GetPropertiesAsync();

// Clear range
await file.ClearRangeAsync(new HttpRange(0, propertiesResponse.Value.ContentLength));

byte[] newData = new byte[] { 0, 1, 0, 1, 0, 1, 0, 1 };
using Stream newStream = new MemoryStream(newData);

// Upload new data
await file.UploadRangeAsync(new HttpRange(0, newStream.Length), newStream);
```

Here's the full sample I wrote to test:

```
using Azure;
using Azure.Storage.Files.Shares;
using Azure.Storage.Files.Shares.Models;
using NUnit.Framework;
using System;
using System.IO;
using System.Threading.Tasks;

namespace ConsoleApp6
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string connectionString = "";
            ShareClient share = new ShareClient(connectionString, "myshare5");
            try
            {
                // Create share
                await share.CreateAsync();
                ShareFileClient file = share.GetRootDirectoryClient().GetFileClient("myfile");

                // Create file
                await file.CreateAsync(maxSize: 1024);

                // Upload inital data that we will overwrite 
                byte[] initalData = new byte[] { 1, 0, 1, 0, 1, 0, 1, 0 };
                using Stream initalStream = new MemoryStream(initalData);
                await file.UploadRangeAsync(new HttpRange(0, initalStream.Length), initalStream);

                // Relavent code snippet.  Everything before this was setup.
                // Get File properties
                Response<ShareFileProperties> propertiesResponse = await file.GetPropertiesAsync();

                // Clear range
                await file.ClearRangeAsync(new HttpRange(0, propertiesResponse.Value.ContentLength));

                byte[] newData = new byte[] { 0, 1, 0, 1, 0, 1, 0, 1 };
                using Stream newStream = new MemoryStream(newData);

                // Upload new data
                await file.UploadRangeAsync(new HttpRange(0, newStream.Length), newStream);

                // Download the file
                Response<ShareFileDownloadInfo> downloadResponse = await file.DownloadAsync();
                byte[] actualData = new byte[newData.Length];
                await downloadResponse.Value.Content.ReadAsync(actualData, 0, actualData.Length);

                // Assert data equality
                Assert.AreEqual(actualData, newData);
            }
            finally
            {
                await share.DeleteAsync();
            }
        }
    }
}

```

**Comment by Oredna** [comment]
@seanmcc-msft I didn't receive the notification for your replay. I will try tomorrow and give a feedback.

**Comment by Oredna** [comment]
I didnt manage to make it work. And it doesnt matter. I spent so much time doing it. Not it gives error on 
 Response<ShareFileProperties> propertiesResponse = await file.GetPropertiesAsync();

`blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Default constructor not found for type Azure.Storage.Files.Shares.ShareFileClient
System.MissingMethodException: Default constructor not found for type Azure.Storage.Files.Shares.ShareFileClient`

I will just use the method with delete and create. Blazor wasm have some problems as shown here https://github.com/dotnet/aspnetcore/issues/22298

I will close the issue
