### ISSUE TITLE
Broken link in Configuration README

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#12588]
In https://github.com/Azure/azure-sdk-for-net/blob/Azure.Extensions.AspNetCore.Configuration.Secrets_1.0.0/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/README.md, the link under "Next Steps" to https://github.com/Azure/azure-sdk-for-net/blob/Azure.Extensions.AspNetCore.Configuration.Secrets_1.0.0/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/aspnetcore_configuration_doc is broken (404).

**Comment by pakrym** [comment]
Fixed
