### ISSUE TITLE
[FEATURE REQ] Expose the corresponding <Url> on BlobItem

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [Azure/azure-sdk-for-net#12582]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
When enumerating blobs in a container, the XML response actually contains the blob URI [from what I gather](https://docs.microsoft.com/en-us/rest/api/storageservices/enumerating-blob-resources). But the BlobItem does not contain that property.

So, the only way (?) to generate the blob Url is to do something like `new Uri(container.Uri, $"{container.Name}/{blob.Name}")`. If this is correct, we should have a new property representing `<Url>` on BlobItem (can't find the source for that class in src/Models even though it's supposed to be originating from that folder).

~~As a side note, how to create or get a BlobItem by its Url?~~ nevermind, it's `container.GetBlobClient(value)`

**Comment by amnguye** [comment]
Hi,

Yes, there isn't a way to get the `Uri` from a `BlobItem`. Can I ask what you are trying to achieve from this? Are you trying to easily make a `BlobClient` after making a `GetBlobs(...)` call on a Container? Is the `container.GetBlobClient(blobName)` insufficient? What is needed by getting the Uri?

Maybe a current mitigation for this can be
```
blobname = 
BlobClient blob = container.GetBlobClient(blobName);
Uri uri = blob.Uri
```

**Comment by bjorn-ali-goransson** [comment]
It's not insufficient per se, it just feels like the long way around something that is indeed returned in a single request. Right now, generating the URLs for 20 or so blobs takes more than a second 😱

The purpose for me doing this is to do an image selector like this for my CMS. It's working, it just feels way too slow.

![image](https://user-images.githubusercontent.com/668160/84197025-80779a80-aaa1-11ea-84b0-29f2815653fe.png)

**Comment by bjorn-ali-goransson** [comment]
Wait! scratch the time aspect of my message. I was confusing it with getting the content length of a blob. Sorry!
