### ISSUE TITLE
[QUERY] BlobServiceClient.GetUserDelegationKeyAsync throw "The value for one of the XML nodes is not in the correct format." error 

### ISSUE THREAD

**Issue by Marimoiro** [Azure/azure-sdk-for-net#12595]
**Query/Question**

Our below code throw "The value for one of the XML nodes is not in the correct format." error 

```
            TokenCredential credential =
                new ClientSecretCredential(
                    cliendId,
                    talentId,
                    secret,
                    new TokenCredentialOptions()
                );

            var cre = new DefaultAzureCredential();
            // Create a new Blob service client with Azure AD credentials.
            BlobServiceClient blobServiceClient = new BlobServiceClient(new Uri(blobEndpoint),
                cre);

            // throw!! 
            UserDelegationKey key = await blobServiceClient.GetUserDelegationKeyAsync(DateTimeOffset.UtcNow,
                DateTimeOffset.UtcNow.AddDays(7));

```

![image](https://user-images.githubusercontent.com/5342721/83995638-e3c7d680-a994-11ea-8adf-21fa600966f2.png)

I can understand an authentication error, but I can't imagine any reason for an XML error.
What could it be?

I think I'm done configuring the application and setting up the roles.

**Environment:**
 - Name and version of the Library package used:
![image](https://user-images.githubusercontent.com/5342721/83995674-01953b80-a995-11ea-9870-bbcf0f51a833.png)

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):  Version:   3.1.300
 Commit:    b2475c1295

ランタイム環境:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.300\

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

 - IDE and version : Microsoft Visual Studio Community 2019
Version 16.6.0

**Comment by amnguye** [comment]
Hi,

What credential type did you enable? (https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet). So I can better reproduce your error.

Tagging Azure.Identity to help see what could be the cause why they we're failing to get the authentication key

**Comment by Marimoiro** [comment]
I tried TokenCredential  & DefaultCreential ( generated from TokenCredential parameters).
![image](https://user-images.githubusercontent.com/5342721/84861799-d4d7d700-b0ac-11ea-8762-5e7a52b8bd94.png)

Is it your required answers?

**Comment by amnguye** [comment]
Hi,

The following credential types if enabled will be tried, in order when using DefaultAzureCredential.

EnvironmentCredential
ManagedIdentityCredential
SharedTokenCacheCredential
InteractiveBrowserCredential

Which one did you use?

**Comment by schaabs** [comment]
@amnguye I'm not sure how this would be an identity issue. The error seems to indicate that it's an issue with the format of the request. The request that is failing would come after authentication is complete.

**Comment by amnguye** [comment]
Ah okay, I will take off the Azure.Identity label then. Thanks for your help @schaabs !

**Comment by seanmcc-msft** [comment]
@Marimoiro, I believe this is being caused by the way you are initializing your `BlobServiceClient`.

Here is an example of getting and using a User Delegation Key:

```
using Azure.Core;
using Azure.Storage.Blobs;
using System;
using System.Threading.Tasks;
using Azure.Identity;
using Azure.Storage.Sas;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;
using System.IO;

namespace ConsoleApp10
{
    public class Program
    {
        static readonly string TenantId = "";
        static readonly string AppId = "";
        static readonly string Secret = "";
        static readonly Uri AuthEndpoint = new Uri("https://login.microsoftonline.com/");
        static readonly string ContainerName = "";
        static readonly string AccountName = "";
        static readonly Uri BlobUri = new Uri($"https://{AccountName}.blob.core.windows.net");

        public static async Task Main(string[] args)
        {
            BlobServiceClient blobServiceClient = new BlobServiceClient(BlobUri, BuildTokenCredential());
            BlobContainerClient tokenContainer = blobServiceClient.GetBlobContainerClient(ContainerName);
            try
            {
                await tokenContainer.CreateAsync();

                UserDelegationKey userDelegationKey = await blobServiceClient.GetUserDelegationKeyAsync(
                    // 5 min in the past, to account for possible clock skew.
                    startsOn: DateTimeOffset.UtcNow.AddMinutes(-5),
                    expiresOn: DateTimeOffset.UtcNow.AddDays(1));

                BlobUriBuilder blobUriBuilder = new BlobUriBuilder(tokenContainer.Uri)
                {
                    Sas = GenerateSas(userDelegationKey)
                };

                BlobContainerClient sasContainer = new BlobContainerClient(blobUriBuilder.ToUri());

                BlockBlobClient blockBlobClient = sasContainer.GetBlockBlobClient("myBlockBlob");
                byte[] data = GetRandomBuffer(1024);
                using Stream stream = new MemoryStream(data);

                await blockBlobClient.UploadAsync(stream);
            }
            finally
            {
                await tokenContainer.DeleteAsync();
            }
        }

        public static BlobSasQueryParameters GenerateSas(UserDelegationKey userDelegationKey)
        {
            BlobSasBuilder blobSasBuilder = new BlobSasBuilder
            {
                BlobContainerName = ContainerName,
                // Don't need Resource
                // 5 min in the past, to account for possible clock skew.
                StartsOn = DateTimeOffset.UtcNow.AddMinutes(-5),
                ExpiresOn = DateTimeOffset.UtcNow.AddDays(1)
            };
            // Same as "racwdl"
            blobSasBuilder.SetPermissions(
                BlobContainerSasPermissions.Read
                | BlobContainerSasPermissions.Add
                | BlobContainerSasPermissions.Create
                | BlobContainerSasPermissions.Write
                | BlobContainerSasPermissions.Delete
                | BlobContainerSasPermissions.List);

            return blobSasBuilder.ToSasQueryParameters(userDelegationKey, AccountName);
        }

        public static TokenCredential BuildTokenCredential()
            => new ClientSecretCredential(
                TenantId,
                AppId,
                Secret,
                new TokenCredentialOptions() { AuthorityHost = AuthEndpoint });

        public static byte[] GetRandomBuffer(long size)
        {
            Random random = new Random(Environment.TickCount);
            var buffer = new byte[size];
            random.NextBytes(buffer);
            return buffer;
        }
    }
}
```

**Comment by Marimoiro** [comment]
@seanmcc-msft Thank you. for your sample!
I can create myBlockBlob. THANK YOU!

**Comment by seanmcc-msft** [comment]
@Marimoiro, glad to help!
