### ISSUE TITLE
Skip.Test pipeline setting doesn't work correctly

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#12600]
If `Skip.Test` is set on the pipeline test run would only be skipped for that individual PR CI run but tests would still try to run as part of `core - CI` runs.

If there are breaking tests they would fail in `core - CI` runs and not in individual service runs.

**Comment by weshaggard** [comment]
@chidozieononiwu why did you set Skip.Test in https://dev.azure.com/azure-sdk/public/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=1578&view=Tab_History? That should never be used to disable tests, it is only used for testing pipeline changes.

**Comment by chidozieononiwu** [comment]
I added that to unblock a preview release of the synapse library. The build was failing because they did not have any tests and their service was purely code generated. It was supposed to be temporary. I will go ahead and undo that.

**Comment by weshaggard** [comment]
Skip.Test has been removed from the synapse pipelines and we should not use that variable for disabling tests as @pakrym states that will just cause issues in other places like the core pipeline. We should disable the tests in the projects themselves not in the pipeline.
