### ISSUE TITLE
[BUG] Azure.Storage.Blobs.Models.AccountKind missing BlockBlobStorage

### ISSUE THREAD

**Issue by marcre** [Azure/azure-sdk-for-net#12623]
**Describe the bug**

The AccountKind enum is missing BlockBlobStorage.  If you do GetAccountInfo with a block blob account it throws an exception

**Expected behavior**

Return the correct account type

**Actual behavior (include Exception or Stack Trace)**

Throws an exception rather than report correct account kind

**To Reproduce**

 var blobServiceClient = new BlobServiceClient(<connection string to block blob storage account>);
// Next line throws 
var accountInfo = blobServiceClient.GetAccountInfo();

**Environment:**
AzureStorage.Blobs 12.4.3 - verified that the enum value is still missing in master

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/api/Azure.Storage.Blobs.netstandard2.0.cs

**Comment by seanmcc-msft** [comment]
Hi @marcre, I can repo the issue, and we'll work on getting a fix out soon.
