### ISSUE TITLE
Update dependency to latest version of AMQP

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#12624]
Particularly after the fix to https://github.com/Azure/azure-sdk-for-net/issues/11399 is released, but even aside from that we should try to update to the [current](https://www.nuget.org/packages/Microsoft.Azure.Amqp/) version.

**Comment by JoshLove-msft** [comment]
This would need to be done in tandem with EH since the versions are defined repo-wide. @jsquire should we do the bump for this release or wait until the timer fixes are in?

**Comment by jsquire** [comment]
I've no objection to doing it now and then again once the timer fix is in.   Event Hubs has a preview release pending for this milestone, so it's a pretty good time to make the change without impacting a GA.
