### ISSUE TITLE
 [Azure.Core] Readme content and sample code of Azure.Core is incorrect

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#12649]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/Azure.Core_1.2.2/sdk/core/Azure.Core#reporting-errors-requestfailedexception)
![image](https://user-images.githubusercontent.com/65581162/84121849-39ba7e00-aa6a-11ea-87b7-a8f038491724.png)

  Suggestion: We should change it to 'and'

2.
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/Azure.Core_1.2.2/sdk/core/Azure.Core#contributing)
![image](https://user-images.githubusercontent.com/65581162/84122303-cf560d80-aa6a-11ea-8d7c-0c6835250eb4.png)

1.Reason: Microsoft Open Source Code of Conduct  link is wrong 
 
Suggestion: We should change it to https://opensource.microsoft.com/codeofconduct/ 

2.Reason:Conduct FAQ should be a hyperlink
 
Suggestion:We should add hyperlink for Conduct FAQ  
https://opensource.microsoft.com/codeofconduct/faq/

**Comment by v-xuto** [comment]
@jongio , for notification.
