### ISSUE TITLE
Discussion: runtime package dependency for autorest

### ISSUE THREAD

**Issue by tonytang-microsoft-com** [Azure/azure-sdk-for-net#1264]
Hi,

I'm working on AutoRest branch, which currently have Microsoft.Rest.ClientRuntime.1.0.3 and Microsoft.Rest.ClientRuntime.Azure.1.0.12 hard coded in tools\references.net45.props.

I want my sdk to use a higher version (latest one)  runtime, however if I leverage Library.Settings.targets, the lower version shown above  will be added as a reference automatically.

My question is what is our strategy on managing runtime package dependencies for autorest?  Do we enforce all autorest sdk to depend on the same version of runtime, or do we allow each sdk to depend on different version?

If we enforce a single runtime version, how we are going to solve the issue if there's any breaking changes on the runtime versions? Who is going to ensure the runtime version is always latest?

If we allow each sdk to have different dependencies, it would be great if the autorest.exe could display what versions of each package that should be used. It would also be great if each sdk could still leverage Library.Settings.targets for common tasks like copying binaries and such.

**Comment by yugangw-msft** [comment]
we will allow each sdk lib to sue different runtime package. Check out my PR
