### ISSUE TITLE
[Azure.Extensions.AspNetCore.DataProtection.Blobs] Readme content and sample code of Azure.Extensions.AspNetCore.DataProtection.Blobs is incorrect

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#12646]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Blobs#next-steps)
![image](https://user-images.githubusercontent.com/65581162/84124486-dfbbb780-aa6d-11ea-8ea9-e81f3beab8f3.png)

Reason:  Link is useless.

**Comment by pakrym** [comment]
Disagree with the uselessness of the link, it gives some context on the system this package integrates with.

**Comment by tzhanl** [comment]
@pakrym we meant the link is not available.
