### ISSUE TITLE
[FEATURE REQ] How can I check valid azure credentials

### ISSUE THREAD

**Issue by chnyda** [Azure/azure-sdk-for-net#12645]
I have following code which I am getting virtual machines.

```
`public async Task<bool> AzureChecker(string clientId, string clientSecret, string tenantId, string subscriptionId, string location)
        {
            try
            {
                var credentials = new AzureCredentialsFactory().FromServicePrincipal(clientId, clientSecret, tenantId,
                    AzureEnvironment.AzureGlobalCloud); 
                Azure.Configure().Authenticate(credentials);
                ComputeManagementClient client = new ComputeManagementClient(credentials)
                {
                    SubscriptionId = subscriptionId
                };
                var vmSizes = await client.VirtualMachineSizes.ListAsync(location);
                if (vmSizes != null)
                    return true;
            }
            catch (Exception)
            {
                return false;
            }

            return false;
        }`
```

I have also checker method which I would like check when creating azure credentials for my db, is it good credentials or not. I have to use only tenantId, subscriptionId, clientId, clientSecret (or one of them), no url or something else. In above case if I try bad credentials (for ex: test for every field) it will success anyway, cause it is not null, I can not find any method which I need to check for ex: status code from server is it ok or not.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls have a look? thanks.

**Comment by xccc-msft** [comment]
@chnyda According to your code snippet, I think you are using [Fluent .NET SDK](https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/) as you are using `Azure.configure()`.

Please check below for setting up a working client.
```csharp
var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal("clientId", "clientSecret", "tenantId", AzureEnvironment.AzureGlobalCloud);

var azure = Microsoft.Azure.Management.Fluent.Azure.Configure()
                    .Authenticate(credentials)
                    .WithDefaultSubscription();

var vms = azure.VirtualMachines.List();
```
For more details, please check the [AUTH.md](https://github.com/Azure/azure-libraries-for-net/blob/master/AUTH.md).

**Comment by kibernetik542** [comment]
@xccc-msft actually with getting vm-s we have no issue, I would just check is credentials are true or not, not get vm-s (above is just example for getting vms). With new created account it is possible null or empty vms as well, we would like to show users is there credentials are good or not. Regards Arzu.

**Comment by xccc-msft** [comment]
@kibernetik542 Okay I got the query. I don't think we have such API to just render a credential validation task for now.

cc: @nickzhums for further investigation/discussion on this.

**Comment by yungezz** [comment]
@chnyda  the development focus shifted to the next generation of Azure SDKs. For .NET, the packages are currently in preview state and we are actively working on making it production ready. For packages that follow the new Azure SDK standard, you can visit this link : https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

That said, .NET Fluent is on the path to deprecation (although it might not happen soon), we are in a low maintenance mode. Let us know if further questions, thanks!
