### ISSUE TITLE
[BUG] foreach Azure.Pageable<BlobItem> then throw System.FormatException

### ISSUE THREAD

**Issue by pintse** [Azure/azure-sdk-for-net#12643]
**Describe the bug**
Please provide the description of issue you're seeing.

I refer to the [tutorial ](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet#list-the-blobs-in-a-container) to write the code to upload blob to iot edge mcr.microsoft.com/azure-blob-storage:latest module and to list the blob in the container.
```
Console.WriteLine("Listing blobs...");

// List all blobs in the container
await foreach (BlobItem blobItem in containerClient.GetBlobsAsync())
{
    Console.WriteLine("\t" + blobItem.Name);
}
```

It throws the "Unhandled exception. System.FormatException: String '' was not recognized as a valid DateTime." 

**Expected behavior**
I think it can get blob list smooth.

**Actual behavior (include Exception or Stack Trace)**
Unhandled exception. System.FormatException: String '' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)
   at System.DateTimeOffset.Parse(String input, IFormatProvider formatProvider, DateTimeStyles styles)
   at System.DateTimeOffset.Parse(String input, IFormatProvider formatProvider)
   at Azure.Storage.Blobs.Models.BlobItemProperties.FromXml(XElement element)
   at Azure.Storage.Blobs.Models.BlobItem.FromXml(XElement element)
   at Azure.Storage.Blobs.Models.BlobsFlatSegment.<>c.<FromXml>b__30_0(XElement e)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Azure.Storage.Blobs.Models.BlobsFlatSegment.FromXml(XElement element)
   at Azure.Storage.Blobs.BlobRestClient.Container.ListBlobsFlatSegmentAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Container.ListBlobsFlatSegmentAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, String prefix, String marker, Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker, BlobTraits traits, BlobStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.GetEnumerator()+MoveNext()
   at BlobStorageV12.Program.Main(String[] args) in D:\projects\code\dotNetCore\VSCode\BlobQuickstartV12_Git\BlobQuickstartV12\Program.cs:line 38
   at BlobStorageV12.Program.<Main>(String[] args)

**To Reproduce**
```
            BlobServiceClient blobServiceClient = new BlobServiceClient (connectionString);
            string containerName = "customer01";
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);
            string localPath = "./data/";
            string fileName = "quickstart" + Guid.NewGuid ().ToString () + ".txt";
            string localFilePath = Path.Combine (localPath, fileName);

            // Write text to the file
            await File.WriteAllTextAsync (localFilePath, "Hello, blob storage!");

            // Get a reference to a blob
            BlobClient blobClient = containerClient.GetBlobClient (fileName);

            Console.WriteLine ("Uploading to Blob storage as blob:\n\t {0}\n", blobClient.Uri);

            // Open the file and upload its data
            using FileStream uploadFileStream = File.OpenRead (localFilePath);
            await blobClient.UploadAsync (uploadFileStream, true);
            uploadFileStream.Close ();

            Console.WriteLine ("Listing blobs...");

            // List all blobs in the container
            await
            foreach (BlobItem blobItem in containerClient.GetBlobsAsync ()) {
                Console.WriteLine ("\t" + blobItem.Name);
            }
```

**Environment:**
 - Azure.Storage.Blobs 12.4.4 
 - mcr.microsoft.com/azure-blob-storage:latest on Azure Ubuntu VM
 - the code run on Windows 10
 - VS Code 1.45.1
 - .NET Core SDK :
 Version:   3.1.100
 Commit:    cd82f021f4

 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.100\

Host (useful for support):
  Version: 3.1.0
  Commit:  65f04fb6db

.NET Core SDKs installed:
  2.1.508 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by pintse** [comment]
I also post the issue in the [StackOverflow](https://stackoverflow.com/questions/62282020/foreach-azure-pageableblobitem-then-throw-system-formatexception)

**Comment by pintse** [comment]
This an XML from GetBlobs() caught through fiddler. The "Creation-Time" is null.

```
<?xml version="1.0" encoding="UTF-8"?>
<EnumerationResults ServiceEndpoint="http://my edge device storage url " ContainerName="blobfromappa1f9e394-5bd2-4110-b9c5-9396b4a7477b">
   <Blobs>
      <Blob>
         <Name>myFile8eba48b8-475a-4f32-a8a4-c6866cacd703.txt</Name>
         <Properties>
            <Creation-Time />
            <Last-Modified>Wed, 10 Jun 2020 01:51:53 GMT</Last-Modified>
            <Etag>0x8D80CE0D98F7DF6</Etag>
            <Content-Length>14</Content-Length>
            <Content-Type>application/octet-stream</Content-Type>
            <Content-Encoding />
            <Content-Language />
            <Content-MD5>76PGAUTjS5+W39/uoprDKg==</Content-MD5>
            <Cache-Control />
            <Content-Disposition />
            <BlobType>BlockBlob</BlobType>
            <LeaseStatus>unlocked</LeaseStatus>
            <LeaseState>available</LeaseState>
            <ServerEncrypted>false</ServerEncrypted>
            <TagCount>0</TagCount>
         </Properties>
      </Blob>
   </Blobs>
   <NextMarker />
</EnumerationResults>
```

**Comment by pintse** [comment]
I had tried Azure.Storage.Blobs 12.4.2. It also gots the exception. If the storage is in the cloud(storage account) not on the edge(module), the SDKs both run well.

**Comment by gmantri** [comment]
Copying my answer from [StackOverflow](https://stackoverflow.com/questions/62282020/foreach-azure-pageableblobitem-then-throw-system-formatexception/62296957#62296957).

---

Reading the documentation about it [`here`][1], basically the issue is that IoT edge uses blob storage modules that are consistent with REST API version 2017-04-17.

> Blob storage modules on IoT Edge use the Azure Storage SDKs, and are
> consistent with the 2017-04-17 version of the Azure Storage API for
> block blob endpoints.

Considering this, you will need to use a SDK version that targets REST API version 2017-04-17. According to this [`link`][2], that SDK version would be `8.2`. You can install that version from here: https://www.nuget.org/packages/WindowsAzure.Storage/8.2.0


  [1]: https://docs.microsoft.com/en-us/azure/iot-edge/how-to-store-data-blob#supported-storage-operations
  [2]: https://docs.microsoft.com/en-us/rest/api/storageservices/protocol-version-support-for-.net-client-library-versions

**Comment by pintse** [comment]
Copying my comment from StackOverflow.
-----------------------------------------------

Thanks @gmantri  for your answer! I use "WindowsAzure.Storage" v8.2.0 or v9.3.3 and rewrite the code for using the SDK. It can add a blob and list blobs inside the container well.
