### ISSUE TITLE
Review FormRecognizer API Updates for .NET with Arch Board

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#12654]
APIs that changed between P2 and P3 can be seen here:

https://apiview.dev/Assemblies/Review/cf2c57b3d4c44ef08c2e8284f7441a2d?diffRevisionId=7b88eaab713441088064a69b39977518#Azure.AI.FormRecognizer.Models.RecognizeReceiptsOperation

Arch board issue is here:
https://github.com/Azure/azure-sdk/issues/1409

**Comment by maririos** [comment]
Email to .NET architect and deputy architect requesting feedback sent
