### ISSUE TITLE
[Design] Consider a new options design

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#12701]
## Summary

[Java's guidelines](https://azure.github.io/azure-sdk/java_design.html#service-method-parameters) contain the following item, which is not present in .NET's:

> DO NOT introduce method overloads that take a subset of the parameters as well as the options parameter. Option parameters must be the only argument to a method, apart from the Context type, which must continue to be outside the options type.

In case we decide to incorporate it into .NET's, we may need to update the `FormRecognizerClient` service methods:
https://github.com/Azure/azure-sdk-for-net/blob/7505a33db8e32d8eb2756782be327c352509fc6e/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient.cs#L172

## Goals
- [x] Write a proposed design and discuss with the team whether we want to incorporate these changes or not.
- [x] Java has similar changes on their SDK. Consider waiting for feedback before actually updating the .NET design (#12476, #12477).
- [x] Present proposed changes in the Arch Board review.
- [x] Incorporate accepted changes.

**Comment by annelo-msft** [comment]
@kinelski , will this issue be closed with PR #12836 ?

**Comment by kinelski** [comment]
> 
> 
> @kinelski , will this issue be closed with PR #12836 ?

This issue has no relation to #12836. That PR removes the `RecognizedReceipt` and `RecognizedReceiptsCollection` types, and adds back `FormField{T}`.

**Comment by maririos** [comment]
From ApiView => https://apiview.dev/Assemblies/Review/cf2c57b3d4c44ef08c2e8284f7441a2d?diffRevisionId=7b88eaab713441088064a69b39977518#Azure.AI.FormRecognizer.Models.RecognizeReceiptsOperation

- should Form and FormUrl be nullable?
or
- should Form and FormUrl be private/internal?

**Comment by kinelski** [comment]
Closing it. Java will follow the current .NET design.
