### ISSUE TITLE
Bounding boxes values are not present when serializing the object to a json format.

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12721]
Using Form Recognizer Preview.3 , when calling, for example, `StartRecognizeCustomForms` although the returned object `RecognizedFormCollection` contains values in the `BoundingBox` property, when serializing it, it returns `{}`.

![image](https://user-images.githubusercontent.com/9868623/84437008-339edb80-abe9-11ea-97b5-e9eda58f2609.png)

Json string:
```
{
   "FormType":"form-0",
   "PageRange":{
      "FirstPageNumber":1,
      "LastPageNumber":1
   },
   "Fields":{
      "field-0":{
         "Name":"field-0",
         "LabelText":{
            "TextContent":[],
            "BoundingBox":{},
            "PageNumber":1,
            "Text":"Hero Limited"
         },
        ...
```

**Comment by maririos** [comment]
I took a look at this issue and `JsonSerializer` only parses public properties. Looking at BoundingBox:
```
public readonly struct BoundingBox
{
  internal PointF[] Points { get; }
  public PointF this[int index] { get; }
}
```

We provide the user a way to access the data, but not a property per se that JsonSerializer can understand.

@annelo-msft could you help me understand this type more with the following questions?
- How are we expecting the user to consume the BoundingBox type?
  - Why we are hiding the `Points` property from the user?
  - Will over writing the `ToString()` method makes sense?
- Is it expected that the size will always be 4? (I saw KC comment in the [APIView ](https://apiview.dev/Assemblies/Review/cf2c57b3d4c44ef08c2e8284f7441a2d#Azure.AI.FormRecognizer.Models.BoundingBox)about adding a `Count` property).

**Comment by annelo-msft** [comment]
**How are we expecting the user to consume the BoundingBox type?**

The idea is that they would be able to write something like:

```C#
FormLine line = page.Lines[i];
PointF upperLeft = line.BoundingBox[0];
PointF upperRight = line.BoundingBox[1];
PointF lowerRight = line.BoundingBox[2];
PointF lowerLeft = line.BoundingBox[3];
```

**Why we are hiding the `Points` property from the user?**

We had originally exposed it, but Krzysztof suggested it was more idiomatic to add an indexer to the class.  Having both would be redundant.

**Will over writing the `ToString()` method makes sense?**

I'd avoid doing this unless we have a very clear set of requirements about how customers would use this.

**Is it expected that the size will always be 4? (I saw KC comment in the APIView about adding a Count property).**

Yes.  We've had several discussions about strongly-typing the points on the box (i.e. UpperLeft, LowerRight, etc), but wanted to leave this open to support an arbitrarily sized bounding polygon for flexibility in the future.

**Comment by maririos** [comment]
Thanks Anne.
- Consumption: Looks like we need to show in a sample how to consume a BoundingBox (created issue https://github.com/Azure/azure-sdk-for-net/issues/12782)
- Count: thanks to your explanation, and to help the user navigate the indexer, we should add the `Count` property

As to answer the original request of being able to see the values of BoundingBox when serializing a response, seems like by design this is not supported and if a user wants it, they could implement a [custom converter](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to)

**Comment by annelo-msft** [comment]
@maririos can this be closed?
