### ISSUE TITLE
Consider using JsonPathSanitizers for sanitizing secrets in request/response body

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12747]
Consider changing the logic from https://github.com/Azure/azure-sdk-for-net/blob/b9bd85cb2591f7c3f3c054f33f158e758056f1d3/sdk/storage/Azure.Storage.Common/tests/Shared/StorageRecordedTestSanitizer.cs#L59
to use `JsonPathSanitizers`.
More information: https://github.com/Azure/azure-sdk-for-net/blob/master/doc/dev/Track2TestFramework.md#sanitizing

**Comment by maririos** [comment]
FYI @tg-msft

**Comment by JimSuplizio** [comment]
Hi @maririos, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
