### ISSUE TITLE
Consider using JsonPathSanitizers for sanitizing secrets in request/response body

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12746]
Consider changing the logic from https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/tests/Utilities/SearchRecordedTestSanitizer.cs
to use `JsonPathSanitizers`.
More information: https://github.com/Azure/azure-sdk-for-net/blob/master/doc/dev/Track2TestFramework.md#sanitizing

**Comment by maririos** [comment]
FYI @tg-msft  and @heaths

**Comment by pallavit** [comment]
Closing this issue as the file does not exist anymore and it is an extremely old issue.
