### ISSUE TITLE
Rename whitelist to allowList in Azure.ResourceManager.Network

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12754]
References in:
- UpgradeLog.htm
- api\Azure.ResourceManager.Network.netstandard2.0.cs
- src\Generated\Models\FirewallPolicy.cs
- src\Generated\Models\FirewallPolicy.Serialization.cs
- src\Generated\Models\FirewallPolicyThreatIntelWhitelist.cs
- src\Generated\Models\FirewallPolicyThreatIntelWhitelist.Serialization.cs
- src\Generated\Models\FirewallPolicy.cs

**Comment by timMSFT** [comment]
@maririos - We have updated the portal with changes as requested ("Allow List"). Ongoing investigation and implementation to update our SDKs and associated documentation.

**Comment by maririos** [comment]
Thanks for the update!

**Comment by lilyjma** [comment]
@maririos: Is it okay to close the issue? Seems like the service team is looking into it.
