### ISSUE TITLE
Rename whitelist to allowList in testcommon/Azure.Management.Network.2020_04

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12757]
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/testcommon/Azure.Management.Network.2020_04/api/Azure.Management.Network.netstandard2.0.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/testcommon/Azure.Management.Network.2020_04/src/Generated/Models/FirewallPolicy.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/testcommon/Azure.Management.Network.2020_04/src/Generated/Models/FirewallPolicy.Serialization.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/testcommon/Azure.Management.Network.2020_04/src/Generated/Models/FirewallPolicyThreatIntelWhitelist.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/testcommon/Azure.Management.Network.2020_04/src/Generated/Models/FirewallPolicyThreatIntelWhitelist.Serialization.cs

**Comment by timMSFT** [comment]
@maririos - We have updated the portal with changes as requested ("Allow List"). Ongoing investigation and implementation to update our SDKs and associated documentation.

**Comment by maririos** [comment]
Thanks for the update!
