### ISSUE TITLE
Rename whitelist to allowList in Microsoft.Azure.Management.SecurityCenter

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12756]
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/Generated/AdaptiveApplicationControlsOperations.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/Generated/AdaptiveApplicationControlsOperationsExtensions.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/Generated/IAdaptiveApplicationControlsOperations.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/Generated/Models/AppWhitelistingGroup.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/Generated/Models/AppWhitelistingGroups.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/Generated/Models/AppWhitelistingIssueSummary.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/Generated/Models/PathRecommendation.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/tests/AdaptiveApplicationControls/AdaptiveApplicationControlsTests.cs

**Comment by isra-fel** [comment]
Not sure if "Security" is the right tag here... also + @taklei just in case. Thanks

**Comment by ronari2** [comment]
Thank you Mariana. We are working to fix it

**Comment by AddySanto** [comment]
This appears to have been completed.  

https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/Generated/Models/AppWhitelistingGroup.cs  returns 404, the updated content is under https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/securitycenter/Microsoft.Azure.Management.SecurityCenter/src/Generated/Models/AdaptiveApplicationControlGroup.cs
