### ISSUE TITLE
Rename whitelist to allowList in Microsoft.Azure.Management.Network

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12755]
Files:
- src\Generated\Models\FirewallPolicy.cs
- src\Generated\Models\FirewallPolicyThreatIntelWhitelist.cs

**Comment by timMSFT** [comment]
@maririos - We have updated the portal with changes as requested ("Allow List"). Ongoing investigation and implementation to update our SDKs and associated documentation.

**Comment by maririos** [comment]
Thanks for the update!
