### ISSUE TITLE
Rename whitelist to allowList in Microsoft.Azure.Management.WebSites

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12758]
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/websites/Microsoft.Azure.Management.WebSites/src/Generated/Models/AppServiceEnvironment.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/websites/Microsoft.Azure.Management.WebSites/src/Generated/Models/AppServiceEnvironmentPatchResource.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/websites/Microsoft.Azure.Management.WebSites/src/Generated/Models/AppServiceEnvironmentResource.cs
- https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/websites/Microsoft.Azure.Management.WebSites/src/Generated/Models/PushSettings.cs

**Comment by isra-fel** [comment]
+ @shubDhond Hi, could you take this work item or assign it to someone else? Thanks

**Comment by ArthurMa1978** [comment]
As Track 1 is deprecating that will not release any new libs, but need do this feature for the new Track 2.
Close this issue and open a new one for Track 2 https://github.com/Azure/azure-sdk-for-net/issues/33379.
