### ISSUE TITLE
Rename blacklist to blocklist in Vision.ContentModerator

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12752]
References have been found in:
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/cognitiveservices/Vision.ContentModerator/src/Generated/ITextModeration.cs
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/cognitiveservices/Vision.ContentModerator/src/Generated/TextModeration.cs
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/cognitiveservices/Vision.ContentModerator/src/Generated/TextModerationExtensions.cs

**Comment by JimSuplizio** [comment]
Hi @maririos, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
