### ISSUE TITLE
CloudConfigurationManager.GetSetting returns null after updating to Azure Tools 2.7 and Microsoft Azure Configuration Manager 3.1.0

### ISSUE THREAD

**Issue by tsunami-kevin** [Azure/azure-sdk-for-net#1276]
I have a cloud service with a web role and some worker roles that was previously working fine using Azure Tools 2.5 and Microsoft Azure Configuration Manager 2.0.3. After updating to Azure Tools 2.7 and Microsoft Azure Configuration Manager 3.1.0 and updating the namespace change (Microsoft.WindowsAzure -> Microsoft.Azure) the CloudConfigurationManager.GetSetting always returns null.

**Comment by markcowl** [comment]
@tsunami-kevin Thank you for the report.  Assignign to the appropriate team for resolution.

**Comment by wiltodelta** [comment]
+1

**Comment by maartenba** [comment]
Having the exact same issue with Azure Tools 2.7 and 3.1.0. Spent a few hours downgrading version by version and deploying, and found all versions down to 2.0.3 having a similar issue where they would not read the value from the role's settings and instead fall back to the Web/App.config value.

Works fine in the development emulator but not on Azure.

**Comment by tsunami-kevin** [comment]
I was able to get it to work by reverting back to my changeset prior to the upgrade and then upgrade each package one by one. It also involved editing the csproj and package files to make sure the version and reference hintpaths were correct.

**Comment by andreabeggiato-geekcups** [comment]
Why every time I try to update to a newer Azure SDK/tool thing stop working? The only solution for the moment is to downgrade?

**Comment by maxg7** [comment]
+1

**Comment by xerxesb85** [comment]
+1 when I upgraded from 2.3 to 2.7. It looks like my startup project was changed from my azure project to the webrole. Changing the startup project for the solution back to the Azure project fixed my CloudConfigurationManager issue. Hope this helps.

**Comment by markcowl** [comment]
### Cost: 2 (time boxed)

**Comment by kirthik** [comment]
Closing it since this is an Azure Tools issue.
