### ISSUE TITLE
[QUERY] Plans to include LocationMode options in v12 Storage.Blob SDK

### ISSUE THREAD

**Issue by jegour** [Azure/azure-sdk-for-net#12785]
**Query/Question**
How can we help?

Are there plans to include the LocationMode option in the Storage.Blob SDK v12, including all options that are currently supported in v11. I know there is currently the GeoRedundantSecondaryUri property on BlobClientOptions. However, this is both cumbersome to use (you now have to provide a Uri that the client used to be able to download directly from the storage account), and doesn't give the full range of options. In fact, our team is currently using the SecondaryThenPrimary option for nodes in the same region as the secondary to avoid cross region reads. Not having this option is a blocker for us migrating to v12.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.4.3
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8] Windows 10 .NET Core 3.1
 - IDE and version : [e.g. Visual Studio 16.3] Visual Studio 16.6

**Comment by seanmcc-msft** [comment]
Hi @jegour, I think this is something we could look into.

@tg-msft, what are your thoughts on added something like [LocationMode](https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/RetryPolicies/LocationMode.cs) and SecondaryUri as properties to our clients?

**Comment by jaschrep-msft** [comment]
Consolidating issue clones. This issue is being tracked in #21445. Closing this issue.
