### ISSUE TITLE
[QUERY] Azure.Storage.Blobs: How to generate SAS URL for a blob when using storage emulator

### ISSUE THREAD

**Issue by yasufs** [Azure/azure-sdk-for-net#12790]
**Query/Question**
How do I generate a SAS URL for a blob when using the storage emulator (UseDevelopmentStorage=true)?
When using a real storage account, I can use `BlobSasBuilder` + `StorageSharedKeyCredential`, but I couldn't find a good way to get a `StorageSharedKeyCredential` to use with the storage emulator.
I know there is a well-known account name & key for the emulator, but it would be really ugly to have to hardcode these into the application code. I think these are exist as constants in the SDK, but hidden inside internal classes.

**Environment:**
 - Azure.Storage.Blobs 12.4.4
 - Windows 10 .NET Core 3.1
 - Visual Studio 16.6.2

**Comment by amnguye** [comment]
Hi,

Are you asking for us to expose these [credentials](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#authorize-with-shared-key-credentials)?

Unfortunately I don't think we can expose these constants. Sorry for the inconvenience.

Please reactivate if I missed the mark on answering your question.

**Comment by yasufs** [comment]
With the old `Microsoft.WindowsAzure.Storage` SDK I could do something like:
```
var account = CloudStorageAccount.Parse("UseDevelopmentStorage=true");
var sasQueryString = account.CreateCloudBlobClient()
                            .GetContainerReference(container)
                            .GetBlockBlobReference(blob)
                            .GetSharedAccessSignature(policy);
```
to get a SAS token for a blob. I was just wondering what is the recommended way to do this with the latest `Azure.Storage.Blobs` SDK.
If there is simply no way to do it without hardcoding, then you can just tell me that and I'll go ahead with the hardcoding.

It would nice to have a nicer way to do that though... for example, if #12414 is addressed then that would solve my issue.
