### ISSUE TITLE
Need info on retirement date of Azure SDKs

### ISSUE THREAD

**Issue by DivyeshTikmani-MSFT** [Azure/azure-sdk-for-net#12808]
Below are libraries used in our Production Environment. Do we have retirement date available for it.
For example, for cosmos db SQL API, 1.x versions, August 30 is retirement date and calls to service will be rejected after it.
 -WindowsAzure.Storage version=8.1.1
 -Microsoft.NET.Sdk.Functions (1.0.13)
 -WindowsAzure.ServiceBus 5.0.0

These libraries are used in Function Apps Runtime version 1.0.13

**Comment by jsquire** [comment]
//cc: @axisc, @seanmcc-msft

**Comment by amishra-dev** [comment]
For storage libraries we have no planned retirement date. The service will not reject the requests. But we will not be adding any new features. Only data corruption and security bugs will be addressed. Here is the support statement: https://github.com/Azure/azure-storage-net#support-statement

**Comment by amishra-dev** [comment]
@tg-msft can you please take the questions for the non-storage services here?

**Comment by axisc** [comment]
we haven't planned a retirement for the Windows.Azure.ServiceBus 5.0.0 SDK yet. Any plans will go through the official decommission channels with sufficient heads up for migration.

**Comment by tg-msft** [comment]
Assigning to @fabiocav for an answer about the roadmap of `Microsoft.NET.Sdk.Functions` v1.0.13
