### ISSUE TITLE
[FEATURE REQ] CognitiveServices should provide a better error message when trying to use AAD Token against a region endpoint.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#12813]
Cognitive Services only allows AAD Tokens on endpoints that have custom domains.  Right now, if you try to use the TokenCredential client overload against a region endpoint you get this error:

`{"error":{"code":"BadRequest","message": "Please provide an authentication key."}}`

It would be great if we could improve that error message to indicate that the user is trying to use AAD against a region endpoint and that they should use a custom subdomain instead.

azsdke2e

**Comment by maririos** [comment]
@ctstone is this something the service can detect and change?

**Comment by ctstone** [comment]
@maririos, it's not something the FR team controls, but I'll try to find the right team to address this.

**Comment by maririos** [comment]
Thank you!!

**Comment by jongio** [comment]
@ctstone - Any update on this?  Do we know who owns it?

**Comment by ctstone** [comment]
@jongio, Cognitive Services Platform Team has opened an internal issue to track this.

**Comment by maririos** [comment]
@ctstone do you know if they've set a priority/estimated date for it's resolution?

**Comment by maririos** [comment]
ping @ctstone

**Comment by ctstone** [comment]
hi @maririos, sorry for the late reply. This change is complete. If it's not rolled out to all regions, it should be soon.

The new response body is:

```json
{
  "error": {
    "code": "BadRequest",
    "message": "Please provide a custom subdomain for token authentication, otherwise API key is required. (Please see https://aka.ms/cogsvc-authenticatewithtoken)"
  }
}
```

**Comment by jongio** [comment]
Very cool!  Thanks @ctstone for getting this done and thanks @maririos for all the follow ups!
