### ISSUE TITLE
Add a README to Azure.Template

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#12818]
The existing README is a README template -- we should add one in the sdk\template directory to describe what's in Azure.Template and how to extend it to build out a service library.

**Comment by jsquire** [comment]
Closing; Azure Template has a read me.

**Comment by jsquire** [comment]
Reopening;  I misunderstood the proposed content.  This does not exist currently.

**Comment by pallavit** [comment]
Given we expect all SDKs to be starting with DPG onboarding guide, do we see value in adding the following content
/cc: @jsquire , @annelo-msft

**Comment by annelo-msft** [comment]
See https://github.com/Azure/azure-sdk-for-net/issues/12903#issuecomment-1599012716

I still feel it would be good to at least link to other docs from the template directory, but I'm also happy to defer to whomever feels most strongly about this.

**Comment by pallavit** [comment]
Given some of the onboarding is aspirational at this point, let's keep this tracking for now. As we see more of it come to light we can make the call at the time.

**Comment by pallavit** [comment]
Given where we are with onboarding experience I believe this issue can be closed. I have not seen any new SDKs being created via the template as we did earlier in quite some time. 

/cc: @jsquire , @annelo-msft - if you feel strongly about it please feel free to reopen.

**Comment by annelo-msft** [comment]
I'm fine with closing this if we have a good holistic solution to onboarding and a different approach works better for the e2e

**Comment by jsquire** [comment]
I can't say whether or not the template is still being used as a reference point, but the structure is definitely still being used for new libraries.  I have no issue closing this out, however.
