### ISSUE TITLE
Separate PooledMemoryStream and PartitionedUploader functionality

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-net#12820]
`PooledMemoryStream` is now more general purpose in the Storage library internals. Pull out non-general-purpose functionality and create subclasses and/or decorators as necessary.

**Comment by JimSuplizio** [comment]
Hi @jaschrep-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
