### ISSUE TITLE
[Bug]  regression of “Azure.storage.Blobs” 12.4.0->12.4.4 , BlobClient Name is encoded with one new BlobClient API

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#12837]
**Describe the bug**
For following API of create BlobClient:
```c#
BlobClient.BlobClient(string connectionString, string blobContainerName, string blobName);
```
-12.4.0: the "Name" of created BlobClient is not encoded (input blobName "aa/bb", get "aa/bb")
-12.4.4: the "Name" of created BlobClient is encoded  (input blobName "aa/bb", get "aa%2Fbb")

**Expected behavior**
the "Name" of created BlobClient should not be encoded

**Actual behavior (include Exception or Stack Trace)**
-12.4.4: the "Name" of created BlobClient is encoded
 (input blobName "aa/bb", get "aa%2Fbb")

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. create BlobClient with the following API, and BlobName "aa/bb", 
`BlobClient.BlobClient(string connectionString, string blobContainerName, string blobName);`

- in 12.4.0, the "Name" of created BlobClient is not encoded
- in 12.4.4, the "Name" of created BlobClient is encoded

2.create BlobClient with the following API, and BlobName "aa/bb", 
`BlobContainerClient.GetBlobClient(string blobName);`

- in 12.4.0, the "Name" of created BlobClient is not encoded
- in 12.4.4, the "Name" of created BlobClient is not encoded

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
“Azure.storage.Blobs” 12.4.4
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by amnguye** [comment]
Related to 12738. Talked about this offline. We look to ensure the regression and fix is in soon. Thanks!

**Comment by blueww** [comment]
@amnguye 
Thanks for the update!
Please add enough test cases to cover special char (especially "/", "%") in each API that related with Item name.
