### ISSUE TITLE
preserve case of dictionary keys on serialization

### ISSUE THREAD

**Issue by bgold09** [Azure/azure-sdk-for-net#1287]
For Data Factory model types, any property type of IDictionary<string, T> should preserve the case of the string keys on serialization. 

For instance, if the dictionary is initialized as 
{
  "Key1" : "property1"
}

then it should be serialized as the same.

**Comment by bgold09** [comment]
Does anyone know why the CI bot unassigned this issue? This was a useful tracking mechanism for me.

**Comment by devigned** [comment]
Hmm... Idk, but will look into it.
