### ISSUE TITLE
Make DataFactoryManagementClient.Deserialization/SerializationSettings static

### ISSUE THREAD

**Issue by protointent** [Azure/azure-sdk-for-net#12877]
We have scenarios in which we need to serialize/deserialize json fragments that represent Data Factory entities. We need to do this WITHOUT connecting to a data factory.

Today we have to COPY definition of settings and maintain them on our side. 

Looking at the source code, these are static in nature, unless some extra customization is in custom init method. Even then, maybe a base setting could be made available in a new API surface.

Scenarios
- Deserialize linkedservice that is passed as parameter by data factory to batch as part of Custom activity execution
- Serialize/Deserialize json files used for XXX-AzDataFactoryYYY comandlets that are used to deploy data factory artifacts.

The two properties in question:
- https://github.com/Azure/azure-sdk-for-net/blob/cb5fe97536f138e944e2700b3a1a40e089bad1c6/sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/Generated/DataFactoryManagementClient.cs#L38
- https://github.com/Azure/azure-sdk-for-net/blob/cb5fe97536f138e944e2700b3a1a40e089bad1c6/sdk/datafactory/Microsoft.Azure.Management.DataFactory/src/Generated/DataFactoryManagementClient.cs#L43

**Comment by isra-fel** [comment]
Thanks for reporting the feature request! We will evaluate it.

**Comment by erich-wang** [comment]
As we're moving to track 2 mgmt sdk, this feature request is related to generator for track 1 and there's workaround for this issue, so close this feature request, thanks.
