### ISSUE TITLE
[QUERY] BlobContainerPermissions equivalent in Storage v12

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#12893]
**Query/Question**

[`BlobContainerPermissions`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobcontainerpermissions?view=azure-dotnet-legacy) is removed. What's the equivalent in Storage v12?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by seanmcc-msft** [comment]
The equivalent in V12 is Azure.Storage.Blobs.Models.BlobAccessPolicy.  Here's an example of how to set access policies on a container in V12:
```
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ConsoleApp5
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string connectionString = "";
            BlobContainerClient containerClient = new BlobContainerClient(connectionString, "mycontainer345234");
            try
            {
                await containerClient.CreateAsync();
                List<BlobSignedIdentifier> signedIdentifiers = new List<BlobSignedIdentifier>
                {
                    new BlobSignedIdentifier
                    {
                        Id = "mysignedidentifier",
                        AccessPolicy = new BlobAccessPolicy
                        {
                           StartsOn = DateTimeOffset.UtcNow.AddHours(-1),
                           ExpiresOn = DateTimeOffset.UtcNow.AddHours(1),
                           Permissions = "rw"
                        }
                    }
                };
                await containerClient.SetAccessPolicyAsync(permissions: signedIdentifiers);
            }
            finally
            {
                await containerClient.DeleteAsync();
            }
        }
    }
}

```

**Comment by SeanFeldman** [comment]
`BlobContainerPermissions` --> `BlobAccessPolicy`
This really should be documented in a migration guide.

**Comment by seanmcc-msft** [comment]
We'll consider that.  I'm going to close this issue, please re-open if you have further questions.

**Comment by SeanFeldman** [comment]
Thank you @seanmcc-msft for answering my questions.

> We'll consider that.

It's already a request: https://github.com/Azure/azure-sdk-for-net/issues/12106
