### ISSUE TITLE
[QUERY] CloudStorageAccount equivalent in Storage v12

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#12892]
**Query/Question**

With Storage v11 there was a [`CloudStorageAccount` type](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.cloudstorageaccount?view=azure-dotnet) that could be constructed by parsing a connection string, SAS Uri, or taking an instance of `StorageCredentials`. In addition to that, `CloudStorageAccount` would be able to return a `StorageCredentials` object, allowing a common way of generating storage credentials from one of the provided options above.

With v12 this doesn't seem to be possible anymore. What the equivalent and where can I find some examples?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by seanmcc-msft** [comment]
V12 doesn't have the equivalent of a `CloudStorageAccount`.

Here's our authentication samples for blob - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/samples/Sample02_Auth.cs

**Comment by SeanFeldman** [comment]
@seanmcc-msft, thank you. The issue is not how to authenticate but how to get the parts from the authentication information. For example, `CloudStorageAccount` had a [`BlobEndpoint` property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.cloudstorageaccount.blobendpoint?view=azure-dotnet). What would be the way to get this information in v12?

**Comment by seanmcc-msft** [comment]
`BlobServiceClient.Uri` is probably the closes equivalent.  It will give you your primary blob endpoint.

**Comment by SeanFeldman** [comment]
The transition from v11 to v12 is a very poor experience 🙁
I realize it's not always possible to obsolete with errors, things should be documented and a [migration guide](https://github.com/Azure/azure-sdk-for-net/issues/12106) created to answer these sorts of questions.

Thank you for your help, @seanmcc-msft.

**Comment by amishra-dev** [comment]
Thanks for the feedback @SeanFeldman. We are working on the migration guide.

**Comment by tonygomez** [comment]
I was looking for the parse method found on CloudStorageAccount

use case:
I have a connection string to up/download files
I need the account name and key to create a sas token

I now need three connection string properties? connection string, account name, and key? Yes, I could create my own connection string build or parser but it would be nice to have this util in the sdk.  Maybe I am missing something in in the api?

**Comment by denniselit** [comment]
> I was looking for the parse method found on CloudStorageAccount
> 
> use case:
> I have a connection string to up/download files
> I need the account name and key to create a sas token
> 
> I now need three app setting properties? connection string, account name, and key? Yes, I could create my own connection string build or parser but it would be nice to have this util in the sdk. Maybe I am missing something in in the api?

Could someone answer this? @SeanFeldman you maybe?

**Comment by SeanFeldman** [comment]
Sorry mate, I have given up on this one. @azure-sdk has decided to enforce the model where the user code has to decide what authentication mode is used and call the appropriate API, unlike the approach taken with `CloudStorageAccount` in the past.

**Comment by RobertoPrevato** [comment]
I resigned to using a simple regular expression to obtain account key and name from the connection string, example:

```cs
try
{
    var matches = Regex.Matches(connectionString, @"([^=]+)=([^\;]+);?");
    var parts = matches.ToDictionary(value => value.Groups[1].ToString(), value => value.Groups[2].ToString());

    var key = parts["AccountKey"];
    var name = parts["AccountName"];
}
catch (KeyNotFoundException)
{
    throw new ArgumentException("Invalid connection string");
}
```

**Comment by kzu** [comment]
I just brought it back and now everything is 💯 : https://www.nuget.org/packages/Devlooped.CloudStorageAccount
