### ISSUE TITLE
[FEATURE REQUEST] Equivalent to StorageCredentials.IsSAS in Storage v12

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#12891]
**Query/Question**

I'm looking for an equivalent to Storage v11 in v12.

With v12, when creating a `BlobContainerClient`, I can pass in either a `StorageSharedKeyCredentials`,  a connection/SAS string, or a `TokenCredential`. 

In v11, when passing a connection/SAS and constructing a [`StorageCredentials`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.auth.storagecredentials?view=azure-dotnet) object, there was an `IsSAS` property that could differentiate between a connection string and a SAS string. With v12 it seems as this option was lost and the code has to explicitly distinguish between a connection string vs SAS Uri. Also, there's no way to 

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by seanmcc-msft** [comment]
V12 doesn't have a `StorageCredentials` class, we have [`StorageSharedKeyCredential`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/src/StorageSharedKeyCredential.cs) for shared key and connection string, [`TokenCredential`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/TokenCredential.cs) for Oauth, and no auth class for SAS, since we consider it part of the URI.

Which scenario you are running into issues with?

**Comment by SeanFeldman** [comment]
When using a connection string, I want to be able to identify a SAS based authentication. This was done OOTB by `StorageCredentials` in v11.

**Comment by seanmcc-msft** [comment]
What do you mean by "identify a SAS based authentication"?

**Comment by SeanFeldman** [comment]
A URI could be with or w/o a SAS token. What's the option to verify the query string of the URI is a valid SAS token with v12?

**Comment by SeanFeldman** [comment]
@seanmcc-msft, some of this could be addressed by fixing #11590 which would provide an option to parse a connection string and get all the parts. I'm surprised to see connection string parsing to construct a domain object was removed in v12. All the properties/parts are still valid as the service side did not change. SAS tokens, endpoints, endpoint suffixes, etc are still the same concepts.

**Comment by greatvovan** [comment]
@seanmcc-msft when using [Integrated Windows Authentication](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-authentication-flows#integrated-windows-authentication-iwa) which of TokenCredential's [descendants](https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet) should I use? Cannot figure out...

`AcquireTokenByIntegratedWindowsAuth()` already [returns](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.publicclientapplication.acquiretokenbyintegratedwindowsauth?view=azure-dotnet) a [token](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.authenticationresult?view=azure-dotnet) as a property of `AuthenticationResult` instance. `TokenCredential` with its `GetToken()` seems redundant.

If I got the token using `AcquireTokenByIntegratedWindowsAuth()` I need to supply it somehow to `BlobContainerClient`, or alternatively I need a `TokenCredential` instance that would acquire a token for me.

Please suggest.

**Comment by JimSuplizio** [comment]
Hi @SeanFeldman, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
