### ISSUE TITLE
[QUERY] Storage BlobContainerPermissions.SharedAccessPolicies in v12

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#12894]
**Query/Question**

In Storage v11 I was able to retrieve all container permissions, find/set/update [`SharedAccessPolicies`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobcontainerpermissions.sharedaccesspolicies?view=azure-dotnet-legacy) programmatically. What's the equivalent in v12?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by seanmcc-msft** [comment]
You can retrieve container permissions with `containerClient.GetAccesPolicyAsync()`

Here's an example of setting container permissions:
```
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace ConsoleApp5
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string connectionString = "";
            BlobContainerClient containerClient = new BlobContainerClient(connectionString, "mycontainer345234");
            try
            {
                await containerClient.CreateAsync();
                List<BlobSignedIdentifier> signedIdentifiers = new List<BlobSignedIdentifier>
                {
                    new BlobSignedIdentifier
                    {
                        Id = "mysignedidentifier",
                        AccessPolicy = new BlobAccessPolicy
                        {
                            StartsOn = DateTimeOffset.UtcNow.AddHours(-1),
                            ExpiresOn = DateTimeOffset.UtcNow.AddHours(1),
                            Permissions = "rw"
                        }
                    }
                };
                await containerClient.SetAccessPolicyAsync(permissions: signedIdentifiers);
            }
            finally
            {
                await containerClient.DeleteAsync();
            }
        }
    }
}
```

**Comment by SeanFeldman** [comment]
Thank you. One downside of the new API is that `Permissions` is not a string whereas in the v11 API it was an enum. 

`Permissions = SharedAccessBlobPermissions.Add | SharedAccessBlobPermissions.Create | SharedAccessBlobPermissions.Read | SharedAccessBlobPermissions.Write`

vs 

`Permissions = "acrw"`

Looking at the XML doco

> the permissions for the acl policy

The least that could be done is mentioned what the string values should be.

**Comment by seanmcc-msft** [comment]
You can also call `BlobSasBuilder.SetPermissions(string rawPermissions, bool normalize)` if you don't want to deal with the enum.  I'd recommend the overload with normalize, because the permission order matters, and this overload will put the permissions in the correct order for you.
