### ISSUE TITLE
Log warning if ReceiveMessages message count exceeds PrefetchCount when Prefetch > 0

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#12908]
If using `ReceiveMessages` and a `PrefetchCount` value greater than 0, the maximum number of messages that would get returned is equal to the `PrefetchCount` value. As such, it might make sense to prevent users from setting the `maxMessages` to be more than `PrefetchCount` when `PrefetchCount` is greater than 0.

This wouldn't apply to `ReceiveDeferredMessages` or `PeekMessages` as these operations use the management link and do not respect Prefetch.

This code shows that link credits can not be increased when using Prefetch:
https://github.com/Azure/azure-amqp/blob/061a523b0a26ba9fe098c855ec10b1897d98ff6f/src/ReceivingAmqpLink.cs#L263

**Comment by SeanFeldman** [comment]
Let's say the prefetch count is configured through a setting and the number of messages to retrieve is set dynamically. How the prevention would work? I would not want this to throw. Logging a warning would be OK.

**Comment by JoshLove-msft** [comment]
Yeah, I thought about this more and think throwing would be too extreme. I think we can at least log a warning.

**Comment by SeanFeldman** [comment]
Logging would be fine. Throwing wouldn't.

Similar to a message that was prefetched and going into processing after it's lock has expired. Should it be prevented from processing? It would be nice but then there's a risk of clock skew between the broker and the processing endpoint. What if that time gap would be enough to process a message and we'd skip the processing, eventually causing the message to end up in a DLQ for no good reason. Again, logging to verify settings would be appropriate. Taking action not so much.

**Comment by JoshLove-msft** [comment]
Closing as we are not planning to expose PrefetchCount - https://github.com/Azure/azure-sdk-for-net/issues/13077

**Comment by JoshLove-msft** [comment]
Reopening as we will leave PrefetchCount public!
