### ISSUE TITLE
[FEATURE REQ] Add version as an attribute the diagnostic activity for the Key Vault operations

### ISSUE THREAD

**Issue by stainlessfawn** [Azure/azure-sdk-for-net#12907]
**Library or service name.**
What library or service is this request related to?
```Azure.Security.KeyVault.Certificates```
```Azure.Security.KeyVault.Keys```
```Azure.Security.KeyVault.Secrets```
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
All of the clients accept a version parameter when getting the Certificate/Key/Secret. The ```Activity``` that is created in the client includes the corresponding name of the Certificate/Key/Secret. This feature would add the version to the ```Activity``` in order record diagnostic information to know the version that was accessed.

This is important to address because it provides additional insight through monitoring to provide evidence a service is retrieving an expected version, especially in scenarios where there is dynamic configuration that affects the service behavior during runtime.

The proposed change would add the following line to the appropriate methods in the clients.
```scope.AddAttribute("version", version);```

**Comment by heaths** [comment]
@pakrym is this something we should do in Azure.Core for all libraries instead? We could get and cache the assembly version.

**Comment by pakrym** [comment]
Yes, this seems to be a universally applicable feature.

**Comment by stainlessfawn** [comment]
@heaths & @pakrym The ask is not on the assembly version; it is for the key/secret/certificate version associated with the specific object that is stored in Key Vault.

For example, it would be including the ```version``` parameter.
```
public virtual async Task<Response<KeyVaultCertificate>> GetCertificateVersionAsync(string certificateName, string version, CancellationToken cancellationToken = default)
```

**Comment by heaths** [comment]
Thanks for the clarification. Would you expect it to be assigned from the retrieved version if no version was specified (in which case we get the latest)? @pakrym, can attributes (tags) be added after a scope (activity) is started?

**Comment by pakrym** [comment]
>  @pakrym, can attributes (tags) be added after a scope (activity) is started?

Yes.

**Comment by stainlessfawn** [comment]
That's a good question; I was originally thinking the parameter could be implied if no version was specified.

After thinking about it a bit, I think it would be best to have both the requested (in case the requested version isn't found or an exception is thrown, the ```Activity``` would still contains the information to know what was requested) and the retrieved version.

**Comment by heaths** [comment]
We'll do this in time for our next GA, but only for request parameters. Our Python and JS SDKs already do this by way of logging all request parameters, but tracing response parameters and/or headers more than we do already is out of goal.
