### ISSUE TITLE
Contributing | Add clear instructions to fork and clone the repo

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#12903]
To set our contributors up for success, we should have clear instructions for getting started in our Contributing.md.

Forking and cloning the `azure-sdk-for-net` repo is currently described at a high level in the [Standard Process](https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md#standard-process) section.  It is part of instructions that are specific to management plane libraries.

Let's lift this section to apply to both management and data plane libraries, and make the instructions more explicit.

**Comment by annelo-msft** [comment]
We'll want to include: how to create an upstream and what it means. For those not used to working in a fork (as opposed to using a central repository and working in it directly), it may not be apparent. (thanks for clarification @jsquire )

**Comment by pallavit** [comment]
Given DPG documentation especially around onboarding\automation do we still see us adding additional information to contribution.md /cc: @jsquire , @annelo-msft

**Comment by annelo-msft** [comment]
@pallavit, I don't have a strong feeling on this.  Ideally we would user-test our repo per documentation and getting started to see if people can be successful with it.  I believe it is standard on GH to start with readme.md and contributing.md as the point of entry.

**Comment by jsquire** [comment]
@pallavit:  Yes.  I don't think we want to assume that every potential community contributor is reading the extensive DPG documentation that is mostly aimed at service partners.   Let's please leave this open.

**Comment by pallavit** [comment]
@jsquire do you think community contributors have faced challenges from our current documentation? I know you interact with them the most so I wanted to ask that question from you. I do think our contribution guides can benefit from a lift but I am not sure if management plane\data plane and other teams follow the same PR via fork approach. 

/cc: @annelo-msft as FYI.

**Comment by annelo-msft** [comment]
I think the Contributing.md has changed a lot since this issue was filed in 2020.  I know there is some variation in how folks follow the fork-and-clone guidance that we might want to drive consistency around, but I don't know that it's a result of insufficient documentation.

**Comment by jsquire** [comment]
@pallavit: The feedback that I've historically gotten was that folks were unfamiliar with the fork+pull request flow and were unable to create branches or work against main.  

Looking at the guide, I'm seeing a clear directive to fork the repository in the [Prerequisites](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#prerequisites) section, along with linked help for doing so.   I think we can close this.
