### ISSUE TITLE
[QUERY] Key Vault ASP.NET Extensions Usage

### ISSUE THREAD

**Issue by graphicsxp** [Azure/azure-sdk-for-net#12913]
**Query/Question**
Is there an equivalent to Microsoft.Extensions.Configuration.AzureKeyVault  ? 

With SDK 4, I configure my keyvault like this :

            return Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((context, config) =>
                {
                    var azureCredentialOptions = new DefaultAzureCredentialOptions();
                   
                    var credential = new DefaultAzureCredential(azureCredentialOptions);
                    var secretClient = new SecretClient(new System.Uri("https://mykv.vault.azure.net/"), credential);
                    var secret = secretClient.GetSecret("StorageConnectionString");

                   //THE FOLLOWING DOES NOT TAKE A SecretClient. How do I do that now ?
                   // config.AddAzureKeyVault()              
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
        }

**Comment by pakrym** [comment]
Hello @graphicsxp,

You don't need to pass the secret client to `AddAzureKeyVault`, you can use the following syntax instead:

```
config.AddAzureKeyVault(new System.Uri("https://mykv.vault.azure.net/"), credential);
```

This would register key vault secret provider with Configuration system and you'll be able to retrieve values from IConfiguration instance later.

See https://github.com/Azure/azure-sdk-for-net/blob/cd0ffd399220e33893bc12ead70360e4da93cd62/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/README.md#examples for an example.

**Comment by heaths** [comment]
Thanks, @pakrym. @graphicsxp, please let us know if this solves your problem or if more help is required, or feel free to close the issue yourself if it does.

**Comment by graphicsxp** [comment]
This so cool, exactly what I was looking for but I didn't know about that package.
