### ISSUE TITLE
[BUG]System.Drawing.Image.FromStream(Stream stream) throwing “Parameter is not valid” Exception for the PNG Image BlobReadStream (Stream returned by CloudBlobBlock.OpenRead() method) over 10MB

### ISSUE THREAD

**Issue by vijiniro** [Azure/azure-sdk-for-net#12923]
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
Microsoft.Azure.Storage.Blob 11.1.7 and 11.0.0

### Which platform are you using? (ex: .NET Core 2.1)
netstandard2.0;net471;net48

### What problem was encountered?
System.Drawing.Image.FromStream(Stream stream) throwing “Parameter is not valid” Exception for the PNG Image BlobReadStream (Stream returned by CloudBlobBlock.OpenRead() method) over 10MB

### How can we reproduce the problem in the simplest way?

    class Program
    {   
        static void Main(string[] args)
        {
            var blobClient = CloudStorageAccount
                .Parse(ConfigurationManager.ConnectionStrings["blobStorageConnStr"].ConnectionString).CreateCloudBlobClient();

            var container = blobClient.GetContainerReference("blobcontainer");
            container.CreateIfNotExists();

            var fileName = "LargePNGImage30MB.png";
            var blobName = "LargePNGImage30MB.png";

            // Upload the image to blob storage
            var blob = container.GetBlockBlobReference(blobName);
            using (var fileStream = File.OpenRead(fileName))
            {
                blob.UploadFromStream(fileStream);
            }

            // Open the blob as stream and load as image
            using (var blobStream = blob.OpenRead())
            {
                var memoryStream = new MemoryStream();
                blobStream.CopyTo(memoryStream);

                var imageFromMemoryStream = Image.FromStream(memoryStream);
                imageFromMemoryStream.Save("ImageFromMemoryStream.png");         

                var image = Image.FromStream(blobStream);   // failed here
                image.Save("ImageFromBlobStream.png");      
            }

            Console.WriteLine("Done.");
        }
        
    }

### Have you found a mitigation/solution?
Copying the stream to a MemoryStream can work without this issue

                var memoryStream = new MemoryStream();
                blobStream.CopyTo(memoryStream);

                var imageFromMemoryStream = Image.FromStream(memoryStream);
                imageFromMemoryStream.Save("ImageFromMemoryStream.png"); 

in v11 repo
https://github.com/Azure/azure-storage-net/issues/1005

**Comment by amnguye** [comment]
Hi,

As you know and noted, this is a v11 issue. Since this is a duplicated from another repo and not relevant to this repository, I will close this issue. However after a quick glance at this issue, it looks like `Image.FromStream` is doing something we are not expecting them to do with the stream or the stream wasn't ended properly.

I apologize for the inconvenience. Open Read is in the process of being added into V12, and will hopefully not have this issue. (#9607)
