### ISSUE TITLE
[BUG] Retrieving multiple secrets asynchronously from Key Vault using SecretClient fails with 401

### ISSUE THREAD

**Issue by lordbrehaut** [Azure/azure-sdk-for-net#12938]
**Describe the bug**
When using the SecretClient in Azure.Security.KeyVault.Secrets if multiple asynchronous calls are made using GetSecretAsync and then awaited with Task.WhenAll() then the calls fail with an unauthorized error as the bearer token is not attached correctly.

**Expected behavior**
Multiple GetSecretAsync calls should be made asynchronously with each secret returned once that task is awaited

**Actual behavior (include Exception or Stack Trace)**
The following exception throws:
Unhandled exception. Azure.RequestFailedException: Service request failed.
Status: 401 (Unauthorized)

Content:
{"error":{"code":"Unauthorized","message":"Request is missing a Bearer or PoP token."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
WWW-Authenticate: REDACTED
x-ms-keyvault-region: eastus
x-ms-request-id: REDACTED
x-ms-keyvault-service-version: 1.1.6.0
x-ms-keyvault-network-info: conn_type=Ipv4;addr=143.115.155.173;act_addr_fam=InterNetwork;
X-AspNet-Version: REDACTED
X-Powered-By: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Mon, 22 Jun 2020 23:09:47 GMT
Content-Length: 87
Content-Type: application/json; charset=utf-8
Expires: -1

   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
   at VaultTest.Program.Main(String[] args)
   at VaultTest.Program.<Main>(String[] args)

**To Reproduce**
1. Create a new SecretClient using DefaultAzureCredentials
2. Make multiple calls to GetSecretAsync without awaiting
3. Await all using Task.WhenAll()
4. Get value from first task using await
5. Observe exception
`var secretClient = new SecretClient(new Uri("https://samplevault.vault.azure.net/"), new DefaultAzureCredential());
var secretTask = secretClient.GetSecretAsync("Secret");
var secretTask1 = secretClient.GetSecretAsync("Secret1");
var secretTask2 = secretClient.GetSecretAsync("Secret2");
var secretTask3 = secretClient.GetSecretAsync("Secret3");
await Task.WhenAll(secretTask, secretTask1, secretTask2, secretTask3);
Console.WriteLine(await secretTask);`

**Environment:**
 - Name and version of the Library package used: Azure.Identity 1.1.1, Azure.Security.KeyVault.Secrets 4.0.3
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Core 3.1
 - IDE and version : Visual Studio 16.5.4

**Comment by heaths** [comment]
Seems like #10673 did not fix this issue, though we were unable to repro after that fix. As a workaround you can synchronize code fetching secrets, as the rate limit is also fairly low (10/second at this time).

**Comment by Petermarcu** [comment]
@heaths should this be marked as a bug rather than question at this point?

**Comment by heaths** [comment]
I've tried to reproduce this with version 4.1.0 (contains the same fix as 4.0.3 did) and cannot reproduce it with several variations of https://gist.github.com/heaths/87b6a2da1b9cdd5c88fe6c3dedb28216. Not all variations were committed, but even just running `Task.Run(() => _client.GetSecretAsync(...))` yielded no failures.

Can you attempt to reproduce this with version 4.1.0?

**Comment by lordbrehaut** [comment]
I've retested this using 4.1.0 and it's fixed the previous issue we were having. Thanks for the help!
