### ISSUE TITLE
[BUG] Cannot record test cases with special characters in the name

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#12932]
Example - https://github.com/Azure/azure-sdk-for-net/pull/12896/files#diff-e152777102db76590298fbda43777754R2099

**Comment by seanmcc-msft** [comment]
Related - https://github.com/Azure/azure-sdk-for-net/pull/12896

**Comment by pakrym** [comment]
@JoshLove-msft can you please take a look?

**Comment by JoshLove-msft** [comment]
@seanmcc-msft in the comments of the example you mention it says this:
> // Test framework doesn't allow recorded tests with connection string because the word 'Sanitized' is not base-64 encoded,
        // so we can't pass connection string validation

My understanding here is that what is happening is the recording files are not able to be saved because the file path contains invalid characters. I'm not sure how this relates to 'Sanitized' not being base-64 encoded. Is the comment referring to a different issue?

**Comment by seanmcc-msft** [comment]
> @seanmcc-msft in the comments of the example you mention it says this:
> 
> > // Test framework doesn't allow recorded tests with connection string because the word 'Sanitized' is not base-64 encoded,
> > // so we can't pass connection string validation
> 
> My understanding here is that what is happening is the recording files are not able to be saved because the file path contains invalid characters. I'm not sure how this relates to 'Sanitized' not being base-64 encoded. Is the comment referring to a different issue?

That comment is related to a [separate issue](https://github.com/Azure/azure-sdk-for-net/issues/12933), that appeared before this one, and I didn't update the comment.  

Not being able to save the test files because their path contains invalid characters is also blocking recording that test.

**Comment by seanmcc-msft** [comment]
@JoshLove-msft, I'm not sure if this change is functioning correctly on Mac and Linux - https://github.com/Azure/azure-sdk-for-net/pull/13083
