### ISSUE TITLE
[BUG] Cannot record tests involving connection strings

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#12933]
Example - https://github.com/Azure/azure-sdk-for-net/pull/12896/files#diff-e152777102db76590298fbda43777754R2097

**Comment by seanmcc-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-net/pull/12896

**Comment by pakrym** [comment]
You can replace parts of connection string with base64 encoded value instead of "Sanitized". See  https://github.com/Azure/azure-sdk-for-net/blob/3add32f61e45e8d5ab3953812edc10b2d4befad5/sdk/iot/Azure.Iot.Hub.Service/tests/TestConnectionStringSanitizer.cs#L18-L25

**Comment by pakrym** [comment]
Please reopen if the provided solution doesn't work.

**Comment by seanmcc-msft** [comment]
Solution worked.  Thanks for the help.
