### ISSUE TITLE
Issue with GetUsageMetricsAsync in WebSiteOperations

### ISSUE THREAD

**Issue by omerlh** [Azure/azure-sdk-for-net#1294]
Hey
I tried to use this instead of pulling the metrics with the metrics client. Look like it has some bug (or problem with our environment), because for all the sites and all the metrics it return SiteMode as null, which fails the parsing. For example:

``` xml
- <Usage>
  <ComputeMode>Dedicated</ComputeMode> 
  <CurrentValue>0</CurrentValue> 
  <DisplayName>Local bytes written</DisplayName> 
  <Limit>-1</Limit> 
  <Name>LocalBytesWritten</Name> 
  <NextResetTime>2015-07-27T00:00:00</NextResetTime> 
  <ResourceName>LocalBytesWritten</ResourceName> 
  <SiteMode i:nil="true" /> 
  <Unit>Bytes</Unit> 
  </Usage>
```

Also, it look like this API return less data then the metrics client. I would like to know what is the different between this API and mMetricsClient.MetricDefinitions.ListAsync (except for the additional calculating of the raw data).
Thanks,
Omer

**Comment by markcowl** [comment]
@omerlh Thank you for the report.  Assignign to the appropriate team for resolution.

**Comment by omerlh** [comment]
Thank you!

**Comment by Hijdra** [comment]
Hi,

Has this issue been addressed? I am probably getting the same issue.
Using: Microsoft.WindowsAzure.Management.Websites v4.4.2-prerelease

Piece of the exception:
```cs
[ArgumentException: Must specify valid information for parsing in the string.]
   System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult) +12122250
   System.Enum.Parse(Type enumType, String value, Boolean ignoreCase) +78
   Microsoft.WindowsAzure.Management.WebSites.<GetUsageMetricsAsync>d__160.MoveNext() +3447
```
Greetings,
Mark Hijdra

**Comment by omerlh** [comment]
Nope

**Comment by shahabhijeet** [comment]
@omerlh please open a new issue if the problem still exists/repros.
