### ISSUE TITLE
Create README for Azure.Core.TestFramework

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#12959]
It would be great to provide a README for the Core Test Framework, similar to the one for [Core](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core) that goes through key concepts with samples.

https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core.TestFramework

**Comment by pakrym** [comment]
We should move https://github.com/Azure/azure-sdk-for-net/blob/master/doc/dev/Track2TestFramework.md to test framework directory and check that it's up-to-date.
