### ISSUE TITLE
track2 control plane tests only run against async methods, but IsAsync reports true and false

### ISSUE THREAD

**Issue by drwill-ms** [Azure/azure-sdk-for-net#12956]
I set a breakpoint in the async and sync equivalent methods in a client.

Then I debug a test that hits that method, and examine IsAsync in both cases. The test will run twice and IsAsync will report true in one case, and false in the other, however in both cases only the Async method breakpoint gets hit.

**Comment by pakrym** [comment]
It's a bug in https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.TestFramework/src/InstrumentClientInterceptor.cs#L9 that doesn't recognize the we management client pattern where sub-clients are properties and not methods with `Get***Client()` name.
