### ISSUE TITLE
[KeyVault] Implement Security Domain functionality

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#12950]
Swagger can be found here: 
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.2-preview/securitydomain.json

**Comment by heaths** [comment]
We will not be implementing Security Domains in the SDKs, according to the services team. This will be done in the Azure CLI only.
