### ISSUE TITLE
[Storage][DataLake] DataLakeFileClient -- MaxUploadBytes does not have an accurate name nor documentation 

### ISSUE THREAD

**Issue by davidOSUL** [Azure/azure-sdk-for-net#12969]
Right now DataLakeFileClient has a property "MaxUploadBytes" which states that it 

"Gets the maximum number of bytes that can be sent in a call to Azure.Storage.Files.DataLake.DataLakeFileClient.UploadAsync"

however, the limit described in this property seems to be actually referring to the maximum for Append, not Upload. I think the name of this property should change to MaxAppendBytes, and the docs should be updated to clarify that it is the maximum for Append/AppendAsync.

**Comment by LeaShallev** [comment]
Do you have any answer about it?

**Comment by sumantmehtams** [comment]
Adding @rahuldutta90 to confirm whether this property relates to append or upload.

**Comment by rahuldutta90** [comment]
@sumantmehtams this is gen2 not gen1

**Comment by sumantmehtams** [comment]
Adding @seanmcc-msft to take a look

**Comment by seanmcc-msft** [comment]
Hi @davidOSUL,

We probably cannot change the property name, as we are not allowed to have breaking changes.  We could definitely improve the documentation.

-Sean

**Comment by amishra-dev** [comment]
We can't make this change without making a breaking change. But we should change the function comments to reflect that. @seanmcc-msft

**Comment by amnguye** [comment]
Updated documentation in PR #18277 so that `MaxUploadBytes` details what it actually does.
