### ISSUE TITLE
Event Hubs: AAD Auth failure when testing against other clouds

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#12964]
We're seeing errors when running Event Hubs tests in other clouds.

US Gov cloud -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=434809&view=ms.vss-test-web.build-test-results-tab&runId=11589224&paneView=debug&resultId=101656

```
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException : AADSTS900382: Confidential Client is not supported in Cross Cloud request.
```

Azure China Cloud -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=434809&view=ms.vss-test-web.build-test-results-tab&runId=11589228&paneView=debug&resultId=101607 

```
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException : AADSTS90002: Tenant '3d0a72e2-8b06-4528-98df-1391c6f12c11' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.
```

In both cases it looks like we're authenticating against a hardcoded authority host: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.EventHubs/tests/Infrastructure/EventHubScope.cs#L277

Also looks like other hosts are hardcoded in that file as well. 

Recommendations: 

* Read the authority host from `AZURE_AUTHORITY_HOST` and other host names from environment variables 
* Read other host names from environment variables and use test-resources.json and `ArmTemplateParameters` to set those values
  * SERVICE_MANAGEMENT_URL
  * STORAGE_ENDPOINT_SUFFIX

**Comment by jongio** [comment]
While we are at it, we should change the next line of code that uses the hard coded mgmt endpoint. https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.EventHubs/tests/Infrastructure/EventHubScope.cs#L278

**Comment by jsquire** [comment]
Note to self:  this will impact both Track 1 and 2 of both Event Hubs and Service Bus
