### ISSUE TITLE
In unsupervised recognize sample, show how to search for a certain field name in the dict

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#12960]

**Comment by assafi** [comment]
@maririos / @kaerm Is this mislabeled? I think it's FR not TA.

**Comment by kaerm** [comment]
Thanks @assafi !

**Comment by maririos** [comment]
My bad. TA in my ❤

**Comment by maririos** [comment]
Not sure why you moved this one as it already has a PR open for it (was also in the Dev column)
