### ISSUE TITLE
Improve timeout exception message/docs

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#12975]
> @kasobol-msft 
> The other piece of feedback I was getting is that our error messaging around timeouts/retires is that some customers don’t realize which settings they should be tweaking if they see them, so they end up reaching out to us. So maybe we should create some page/readme explaining the knobs and their relation and then include link to it in the error messages coming from networking stack.

**Comment by kasobol-msft** [comment]
We should also account for cases where customer is observing high latencies for some percentage of requests (presumably caused by request queuing on small connection pool). This is usually the case on .NET FX with default settings.
