### ISSUE TITLE
AuthorizationPermissionMismatch for Container-level SAS Token with Write permission.

### ISSUE THREAD

**Issue by stack247** [Azure/azure-sdk-for-net#12986]
**Describe the bug**
When creating container-level SAS token (with write permission), I'm not able to write (or upload file) to the container.
I follow the instruction laid out here: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-user-delegation-sas-create-dotnet
NuGet package: Azure.Storage.Blobs v12.4.4

**Expected behavior**
I should be able to write (or upload) any file to the container.

**Actual behavior (include Exception or Stack Trace)**
I was able to generate the SAS token successfully. It looks something like:
https://account-name.blob.core.windows.net/container?skoid=64534a334-3523-42fe-bca2-324234xva&sktid=233425-232-a83b4ca1-65654e8b5ea85&skt=2020-06-24T14%3A48%3A08Z&ske=2020-07-01T14%3A48%3A08Z&sks=b&skv=2019-07-07&sv=2019-07-07&st=2020-06-24T14%3A48%3A11Z&se=2020-06-25T14%3A48%3A11Z&sr=c&sp=rcwl&sig=s%4Bf3jOo7vcxGGV9Kd%2FGy%2B6Uv4v3PofWcqtXGMLgooc8%3D

However, when I use that SAS token to programmatically write file (or use it in Azure Storage Explorer with SAS URI), I get an error.
I was able to read and list in Azure Storage Explorer, but not upload.
The error on Azure Storage Explorer:
```json
{
  "message": "\"UnexpectedCancel\""
}
```

The error when I tried to write it programmatically:
```
Client-Request-ID=06a3ad4a-b62b-11ea-a374-00155df89395 Retry policy did not allow for a retry: Server-Timestamp=Wed, 24 Jun 2020 14:57:29 GMT, Server-Request-ID=fd38a7d5-801e-00f6-5937-4a1c39000000, HTTP status code=403, Exception=This request is not authorized to perform this operation using this permission. ErrorCode: AuthorizationPermissionMismatch<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.RequestId:fd38a7d5-801e-00f6-5937-4a1c39000000Time:2020-06-24T14:57:29.9676908Z</Message></Error>.
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Add the following code.
```csharp
public async Task<string> GenerateLogContainerSasUrlAsync()
{
	var blobClient = GetBlobServiceClient();
	var key = await blobClient.GetUserDelegationKeyAsync(DateTimeOffset.UtcNow,
														 DateTimeOffset.UtcNow.AddDays(7));

	// Create a SAS token that's valid for one hour.
	var sasBuilder = new Azure.Storage.Sas.BlobSasBuilder()
	{
		BlobContainerName = containerName,
		Resource = "c",
		//Protocol = Azure.Storage.Sas.SasProtocol.Https,
		StartsOn = DateTimeOffset.UtcNow,
		ExpiresOn = DateTimeOffset.UtcNow.AddDays(1)
	};

	// Specify read permissions for the SAS.
	//sasBuilder.SetPermissions(BlobContainerSasPermissions.Write);
	sasBuilder.SetPermissions("racwdl");

	// Use the key to get the SAS token.
	string sasToken = sasBuilder.ToSasQueryParameters(key, storageAccountName).ToString();

	// Construct the full URI, including the SAS token.
	var fullUri = new UriBuilder()
	{
		Scheme = "https",
		Host = $"{storageAccountName}.blob.core.windows.net",
		Path = $"{containerName}",
		Query = sasToken
	};

	return fullUri.ToString();
}

protected Azure.Storage.Blobs.BlobServiceClient GetBlobServiceClient()
{
	var serviceClient = new Azure.Storage.Blobs.BlobServiceClient(new Uri(accountEndpoint), new Azure.Identity.DefaultAzureCredential(includeInteractiveCredentials: true));

	return serviceClient;
}
```

2. Change the variables below and call the method:
```csharp
var storageAccountName = "account-name";
var accountEndpoint = $"https://{storageAccountName}.blob.core.windows.net";
var containerName = "container-name";
var res = await GenerateLogContainerSasUrlAsync();
res.Dump("SAS Token");
```

3. Use the SAS token in Azure Storage Explorer.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs v12.4.4
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
      in cloud: Azure Batch
      in local: Windows 10 .NET Framework 4.7.2
          .Net core: SDKs: 3.1.301 [C:\Program Files\dotnet\sdk]
          .NET Core runtimes installed:
            Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
            Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
            Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
            Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
            Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
            Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 - IDE and version : [e.g. Visual Studio 16.3]
    Visual Studio Code
    LinqPad Script 5.

**Comment by seanmcc-msft** [comment]
Hi @stack247, unfortunately I'm not able to reproduce.  I think the issue may be the permissions of the user, group, or service principal that was used to generate the user delegation SAS.

Here is the sample I wrote attempting to reproduce:
```
using Azure.Core;
using Azure.Storage.Blobs;
using System;
using System.Threading.Tasks;
using Azure.Identity;
using Azure.Storage.Sas;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;
using System.IO;

namespace ConsoleApp10
{
    public class Program
    {
        static readonly string TenantId = "";
        static readonly string AppId = "";
        static readonly string Secret = "";
        static readonly Uri AuthEndpoint = new Uri("https://login.microsoftonline.com/");
        static readonly Uri BlobUri = new Uri("");
        static readonly string ContainerName = "";
        static readonly string AccountName = "";

        public static async Task Main(string[] args)
        {
            BlobServiceClient blobServiceClient = new BlobServiceClient(BlobUri, BuildTokenCredential());
            BlobContainerClient tokenContainer = blobServiceClient.GetBlobContainerClient(ContainerName);
            try
            {
                await tokenContainer.CreateAsync();

                UserDelegationKey userDelegationKey = await blobServiceClient.GetUserDelegationKeyAsync(
                    // 5 min in the past, to account for possible clock skew.
                    startsOn: DateTimeOffset.UtcNow.AddMinutes(-5),
                    expiresOn: DateTimeOffset.UtcNow.AddDays(1));

                BlobUriBuilder blobUriBuilder = new BlobUriBuilder(tokenContainer.Uri)
                {
                    Sas = GenerateSas(userDelegationKey)
                };

                BlobContainerClient sasContainer = new BlobContainerClient(blobUriBuilder.ToUri());

                BlockBlobClient blockBlobClient = sasContainer.GetBlockBlobClient("myBlockBlob");
                byte[] data = GetRandomBuffer(1024);
                using Stream stream = new MemoryStream(data);

                await blockBlobClient.UploadAsync(stream);
            }
            finally
            {
                await tokenContainer.DeleteAsync();
            }
        }

        public static BlobSasQueryParameters GenerateSas(UserDelegationKey userDelegationKey)
        {
            BlobSasBuilder blobSasBuilder = new BlobSasBuilder
            {
                BlobContainerName = ContainerName,
                // Don't need Resource
                // 5 min in the past, to account for possible clock skew.
                StartsOn = DateTimeOffset.UtcNow.AddMinutes(-5),
                ExpiresOn = DateTimeOffset.UtcNow.AddDays(1)
            };
            // Same as "racwdl"
            blobSasBuilder.SetPermissions(
                BlobContainerSasPermissions.Read
                | BlobContainerSasPermissions.Add
                | BlobContainerSasPermissions.Create
                | BlobContainerSasPermissions.Write
                | BlobContainerSasPermissions.Delete
                | BlobContainerSasPermissions.List);

            return blobSasBuilder.ToSasQueryParameters(userDelegationKey, AccountName);
        }

        public static TokenCredential BuildTokenCredential()
            => new ClientSecretCredential(
                TenantId,
                AppId,
                Secret,
                new TokenCredentialOptions() { AuthorityHost = AuthEndpoint });

        public static byte[] GetRandomBuffer(long size)
        {
            Random random = new Random(Environment.TickCount);
            var buffer = new byte[size];
            random.NextBytes(buffer);
            return buffer;
        }
    }
}

```

**Comment by stack247** [comment]
Hi @seanmcc-msft thanks for trying this out.

I notice you use service principal (using app id and secret) to get user delegation. I was able to do it successfully with same approach.
However, what I'm trying to do is using MSI for the app that we are deploying. So, we don't have app id and secrets. the App is automatically registered in AAD and we just grant access for that app to the Azure Storage.

Do you mind pasting here the generated SAS token, with masked data. I want to try to compare the SAS token format.

Thanks.

**Comment by seanmcc-msft** [comment]
```
skoid=c4f48289-bb84-4086-b250-6f94a8f64cee
&sktid=72f988bf-86f1-41af-91ab-2d7cd011db47
&skt=2020-06-25T23%3A03%3A00Z
&ske=2020-06-26T23%3A08%3A00Z
&sks=b
&skv=2019-07-07
&sv=2019-07-07
&st=2020-06-25T23%3A03%3A13Z
&se=2020-06-26T23%3A08%3A13Z
&sr=c
&sp=racwdl
&sig=[redacted]
```

Added new lines for readability.

**Comment by amnguye** [comment]
Hi please reactivate if this is still an issue, or if there's an update to this bug. Thanks
