### ISSUE TITLE
[BUG] Creating a DataLake file within a subdirectory truncates the initial directory

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#12987]
**Describe the bug**
When you create a directory, then a subdirectory, then a file within that subdirectory. The uri truncates the initial directory.

e.g.
directory/subdirectory/file becomes subdirectory/file

The file gets created without the initial directory in the path.

**Expected behavior**
Should create the file in the initial directory path

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
```
[Test]
        public async Task CreateSubDirectoryAndFileAsync()
        {
            await using DisposingFileSystem test = await GetNewFileSystem();
            DataLakeDirectoryClient directory = await test.FileSystem.CreateDirectoryAsync(GetNewDirectoryName());

            // Arrange
            string directoryName = GetNewDirectoryName();
            string fileName = GetNewFileName();

            // Act
            DataLakeDirectoryClient subdirectory = await directory.CreateSubDirectoryAsync(directoryName);
            DataLakeFileClient file = await subdirectory.CreateFileAsync(fileName);

            // Assert
            Assert.AreEqual(file.BlobUri.AbsoluteUri, subdirectory.BlobUri.AbsoluteUri + '/' + fileName);
        }
```

**Comment by seanmcc-msft** [comment]
Hi @amnguye, thanks for the detailed example.  I can repo, and we will have a bug fix soon!
