### ISSUE TITLE
NuGet packages lack a few "Health" features in NuGet Package Explorer

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#12995]
@clairernovotny's [NuGet Package Explorer](https://github.com/NuGetPackageExplorer/NuGetPackageExplorer) shows a number of "Health" indicators which we fail to pass (using a recent Azure.Search.Documents 1.0.0-preview.4 package):

According to the tool tips over the warning and error icons:
- [x] **Source Link**: we should either add `<EmbedUntrackedSources>true</EmbedUntrackedSources>` to our project or use the workaround in dotnet/sourcelink#572. Given we use Source Link already, I thought, I'm not sure why we're getting this. Maybe it's just precautionary to make sure packages are built with full sources either way?
- [x]  **Deterministic (dll/exe)**: if we're using the .NET 2.1.300 SDK or newer, we should add `<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>` to our project.
- [x]  **Compiler Flags**: seems to indicate we should use the .NET 3.1 compiler targeting netstandard2.0.

**Comment by heaths** [comment]
To clarify, I'm concerned about what downstream effect the failures of these health checks could have on developers.

**Comment by heaths** [comment]
Duplicate of #11090

**Comment by heaths** [comment]
Upon further discussion, this is not a complete dup so reopening.

**Comment by chidozieononiwu** [comment]
Fixed with https://github.com/Azure/azure-sdk-for-net/pull/13020
