### ISSUE TITLE
[Tests] Update resource group region

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#13001]
Form Recognizer's `test-resources.json` specifies that our resource must be created in a specific region (currently `canada-central`), which we are already doing, but the resource group is still created in the default region. Per eng sys' recommendation, the suggested approach is making the region default to `resourceGroup().location` and specify the desired RG location in the yaml template.

**Comment by maririos** [comment]
FYI service team asked us to stay in `canada-central` for now.

**Comment by kinelski** [comment]
> 
> 
> FYI service team asked us to stay in `canada-central` for now.

Thanks for the info. This issue is more about changing the way we set the region (according to eng sys' recommendation) than about the region itself. I'll update its name.

**Comment by maririos** [comment]
Hmmm is https://github.com/Azure/azure-sdk-for-net/issues/17486 a dup of this issue?

**Comment by kinelski** [comment]
After discussing offline, we came to the conclusion that fixing https://github.com/Azure/azure-sdk-for-net/issues/17486 will solve this issue, so closing it.
