### ISSUE TITLE
[Azure Functions Extension] ServiceBus startup is very slow

### ISSUE THREAD

**Issue by a-vishar** [Azure/azure-sdk-for-net#13010]
**Query/Question**
In my startup class I create a new `TopicClient` which is a static to send messages to a topic.  This is within an Azure Function which does not have a significant load (many cold starts).  When sending a message for the first time, there is a >1 second delay compared to the second message.  Ideally, I would like to warm up the connection during Function startup so that users are less likely to see this delay.  

Is there a way to open the connection without sending a dummy message to the topic?

**Environment:**
 - Microsoft.Azure.ServiceBus 4.1.3
 - Windows Azure Function
 - Visual Studio 16.6.1

**Comment by AlexGhiondea** [comment]
@a-vishar please consider using the latest version of the libraries for Service Bus.
