### ISSUE TITLE
[FEATURE REQ] Add dogfood Environment as a Test Resource Target

### ISSUE THREAD

**Issue by turalf** [Azure/azure-sdk-for-net#13028]
**Describe the bug**
When trying to create test resources using this script `.\eng\common\TestResources\New-TestResources.ps1` on Azure, only environments that are supported are following.
'AzureCloud', 'AzureUSGovernment', 'AzureChinaCloud'

The validation list does not support dogfood environment. 

**Expected behavior**
It would be good to have dogfood supprot as well. 

**Actual behavior (include Exception or Stack Trace)**
When Environment parameter with the value `dogfood` is added to the script, script returns exception of not supported

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
Run the command below with Environment parameter equal to `dogfood`

`.\eng\common\TestResources\New-TestResources.cmd -TenantId <tenantid> -BaseName <username> -ServiceDirectory <serviceName> -TestApplicationId <testAppId> -Location <region> -environment dogfood -ProvisionerApplicationId <appId> -ProvisionerApplicationSecret <appSecret> -SubscriptionId  <subscriptionid>`

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10
 - IDE and version : powershell command line

**Comment by danieljurek** [comment]
Repo: -pr
Branch: feature/communication

**Comment by danieljurek** [comment]
PR open: https://github.com/Azure/azure-sdk-for-net-pr/pull/1214/files

**Comment by damirault** [comment]
PRs allowing this have been merged.
