### ISSUE TITLE
Symantec WSS Agent Proxy not working with new SDK package

### ISSUE THREAD

**Issue by alessandromoura** [Azure/azure-sdk-for-net#13037]
**Describe the bug**
Proxy credentials not being provided with Symantec WSS Agent

**Expected behavior**
The same behavior for the new Azure SDKs packages as we had with the old ones.

**Actual behavior (include Exception or Stack Trace)**
Not being authenticated in the proxy

**To Reproduce**
1. Have a machine that works in a environment with Symantec WSS Proxy
2. Use the Azure.Security.KeyVault.Keys package;
3. Create the following code
```csharp
var credential = new ClientSecretCredential(_tenantId, _clientId, _clientSecret);
var client = new KeyClient(_keyVaultUri, credential);
var key = client.GetSecretAsync(secretName)
```
4. The code above return 403 from the proxy as it does not provide the username that is trying to pass through the proxy

5. The code below works fine through the proxy
```csharp
//working code with previous package (Microsoft.Azure.KeyVautl - latest version)
var token = new AzureServiceTokenProvider("RunAs=App;AppId=1234;TenantId=1234.onmicrosoft.com;AppKey=5678");
var kv = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(token.KeyVaultTokenCallback));
var key = await kv.GetKeyAsync("https://kv1234.vault.azure.net/", "my-key").ConfigureAwait(false);
```

6. To be able to pass through the proxy, this is the code that I needed to do. I want to understand why one package works and not the other
```csharp
HttpClient httpClient = new HttpClient(_httpClientHandler);
TokenCredentialOptions tokenOptions = new TokenCredentialOptions
{
    Transport = new HttpClientTransport(httpClient)
};
var credential = new ClientSecretCredential(_tenantId, _clientId, _clientSecret, tokenOptions);

KeyClientOptions keyOptions = new KeyClientOptions
{
    Transport = new HttpClientTransport(httpClient)
};
return new KeyClient(_keyVaultUri, credential, keyOptions);
```

**Environment:**
 - Azure.Security.KeyVault.Keys (4.0.3.0)
 - Windows 10, .Net Framework 4.6.1, .Net Standard 2.0 running in IIS
 - Visual Studio 16.5.4

**Comment by heaths** [comment]
Our Azure.* packages do reuse the same `HttpClient` by default is no transport is specified, which the older Microsoft.Azure.* should do as well. To diagnose further, please describe what your `_httpClientHandler` in your same code is doing, and generate tracing in both the failure and success case per our [README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/README.md#troubleshooting). Secure information is obfuscated by default, so it should be safe to share but please review it to make sure.

/cc @pakrym @schaabs 

Just a tip: you can put code samples in code fences in GitHub issues (markdown in general) along with an optional language code to make it easier to read:

````
```csharp
var credential = new ClientSecretCredential(...);
// ...
```
````

Still, thank you for the code samples and it helps us troubleshoot your issue!

**Comment by alessandromoura** [comment]
Hi @heaths. Thanks for having a look at this.

I just updated the issue with the code fences. 

A few more information on this. In my scenario I have a WebApi library using .Net Framework 4.6.1 that is consuming another library using .Net Standard 2.0 which is the one trying to use the Azure.* SDK. 

The code of the proxy is as below:
```csharp
var httpHandler = new HttpClientHandler();
WebProxy proxy = new WebProxy(proxyUrl, false);
proxy.UseDefaultCredentials = true;
httpHandler.Proxy = proxy;
httpHandler.UseProxy = true;
```

Error diagnostics:
Azure.RequestFailedException: Service request failed.
	Status: 403 (Forbidden)
Content: [Company's proxy error html page]

Headers:\r\n
	Pragma: no-cache\r\n
	Connection: Keep-Alive\r\n
	Cache-Control: no-cache\r\n
	Content-Length: 15821\r\n
	Content-Type: text/html; charset=utf-8\r\n\r\n   
	
	at Azure.Security.KeyVault.KeyVaultPipeline.<SendRequestAsync>d__27.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
	at Azure.Security.KeyVault.KeyVaultPipeline.<SendRequestAsync>d__21`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
	at Azure.Security.KeyVault.Keys.KeyClient.<GetKeyAsync>d__18.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
	at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   
	at ASB.Digital.Security.AzureKeyVault.AzureKeyVaultHelper.<GetKeyAsync>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   
	at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   
	at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   
	at Company.API.Library.DataAccess.Types.Class.<Method>d__5.MoveNext() in C:\\Repos\\Company\\Company.API.Library\\Company.API.Library\\DataAccess\\Types\\Class.cs:line 90"

Success diagnostics:
{StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: <null>, Headers:
{
  Pragma: no-cache
  x-ms-keyvault-region: australiaeast
  x-ms-request-id: 5a84852b-6ae5-4960-94c5-ece496cea6c0
  x-ms-keyvault-service-version: 1.1.6.0
  x-ms-keyvault-network-info: conn_type=Ipv4;addr=140.168.254.36;act_addr_fam=InterNetwork;
  Strict-Transport-Security: max-age=31536000;includeSubDomains
  X-Content-Type-Options: nosniff
  Cache-Control: no-cache
  Date: Fri, 26 Jun 2020 21:46:54 GMT
  X-AspNet-Version: 4.0.30319
  X-Powered-By: ASP.NET
}}
    ClientRequestId: "d924c717-a035-4c32-9d90-cb847adcebdc"
    ContentStream: {System.IO.MemoryStream}
    Headers: {Azure.Core.ResponseHeaders}
    ReasonPhrase: "OK"
    Status: 200

**Comment by heaths** [comment]
In Azure.*, we only create a proxy by default if any of the environment variables are set according to how they are to be used:
```csharp
        private const string EnvAllProxyUC = "ALL_PROXY";
        private const string EnvAllProxyLC = "all_proxy";
        private const string EnvHttpProxyLC = "http_proxy";
        private const string EnvHttpProxyUC = "HTTP_PROXY";
        private const string EnvHttpsProxyLC = "https_proxy";
        private const string EnvHttpsProxyUC = "HTTPS_PROXY";
        private const string EnvNoProxyLC = "no_proxy";
        private const string EnvNoProxyUC = "NO_PROXY";
        private const string EnvCGI = "GATEWAY_INTERFACE"; // Running in a CGI environment.
```

If those aren't set, having to set your own `HttpClient` with proxy information makes sense.

In Microsoft.Azure.* using an `AzureServiceTokenProvider`, proxy support appears to be provided by ADAL. If you [set the `HTTP_PROXY` and/or `HTTPS_PROXY` environment variables](https://docs.cloudfoundry.org/cf-cli/http-proxy.html#:~:text=The%20https_proxy%20environment%20variable%20holds%20the%20hostname%20or,depends%20on%20your%20operating%20system.%20Format%20of%20https_proxy), does the code work correctly without having to set a proxy?
