### ISSUE TITLE
Generate models and initial client for Event Grid

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#13045]
Using the swagger from Matt's fork, let's get an initial generation of the SDK checked in. We can add a minimal convenience layer to verify that we are able to connect to the service.

**Comment by SeanFeldman** [comment]
@JoshLove-msft, do you mind to provide a link to the branch? Thank you.

**Comment by JoshLove-msft** [comment]
This is in progress, but will be checked into master.

**Comment by kerri-lee** [comment]
Fixed in #13097
