### ISSUE TITLE
how to set a custom WebProxy in QueueClient and/or ServiceBusConnection using Microsoft.Azure.ServiceBus SDK

### ISSUE THREAD

**Issue by alcidesfmelof** [Azure/azure-sdk-for-net#13040]
How can I set the WebProxy in order to specify my Proxy address in **Microsoft.Azure.ServiceBus**? 
Trying this for a day  but there is not clear documentation of how to do it.

What goes after? Cant see how to set a custon WebProxy Object.

```
queueClient = new QueueClient(ServiceBusConnectionString, QueueName);
queueClient.ServiceBusConnection.TransportType = TransportType.AmqpWebSockets;

````

I manage to make it work in **Azure.Messaging.ServiceBus**, but this is a preview version and I wanna use an stable library.
 

```
var options = new ServiceBusClientOptions
            {
                TransportType = ServiceBusTransportType.AmqpWebSockets,
                RetryOptions = new ServiceBusRetryOptions()
                {
                    Mode = ServiceBusRetryMode.Exponential,
                    CustomRetryPolicy = new MyRetryPolicy(),
                },
                Proxy = new WebProxy("http://<proxyserver>:<port>", false)
                {
                    UseDefaultCredentials = true
                }
            };
        

await using var client = new ServiceBusClient(ServiceBusConnectionString, options);
```

I saw the suggestion from @ErikMogensen, but it doesnt say where to set this new WebProxy Object? I guess is in 'ServiceBusConnection' but I cant see where.

```
WebProxy proxyObject = new WebProxy(
    "http://<proxyserver>:<proxyport>", 
    true, 
    new string[] { "somemachine" }, 
    new NetworkCredential("<user>", "<password>"));
WebRequest.DefaultWebProxy = proxyObject;

```

_Originally posted by @ErikMogensen in https://github.com/Azure/azure-service-bus-dotnet/issues/436#issuecomment-474975162_

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @MiYanni

**Comment by axisc** [comment]
@alcidesfmelof 
So the solution that Erik mentioned will work
```
WebProxy proxyObject = new WebProxy(
    "http://<proxyserver>:<proxyport>", 
    true, 
    new string[] { "somemachine" }, 
    new NetworkCredential("<user>", "<password>"));
WebRequest.DefaultWebProxy = proxyObject;
```

The WebRequest.DefaultWebProxy is utilized in the Service Bus Connection [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/ServiceBusConnection.cs#L318)
