### ISSUE TITLE
ImportCertificate : Update appropriate client behavior, documentation, or samples relating to required policy properties

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#13043]
We are working with the service team to determine what the correct behavior for specification of `ImportCertificateOptions` should be on requests to `ImportCertificate`. The SDK was operating under the assumption that `ContentType` could be inferred based on the certificate content. However, the policy seems to expect a `ContentType` to always be set as it will not be inferred from the certificate content.

Related to #11669

**Comment by heaths** [comment]
The Key Vault team has updated the documentation appropriately: https://github.com/Azure/azure-rest-api-specs/blob/14fb40342c19f8b483e132038f8424ee62b745d9/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.1/certificates.json#L1845

In our `ImportCertificateOptions`, we already document this:

```csharp
        /// <param name="certificate">The PFX or ASCII PEM formatted value of the certificate containing both the X.509 certificates and the private key.</param>
```

The corresponding property is similar:

```csharp
        /// <summary>
        /// Gets the PFX or PEM formatted value of the certificate containing both the X.509 certificates and the private key.
        /// </summary>
        public byte[] Certificate { get; }
```

When serializing, we handle encoding accordingly:

```csharp
            if (Certificate != null)
            {
                if (Policy != null && Policy.ContentType == CertificateContentType.Pem)
                {
                    string value = Encoding.ASCII.GetString(Certificate);
                    json.WriteString(s_valuePropertyNameBytes, value);
                }
                else
                {
                    json.WriteBase64String(s_valuePropertyNameBytes, Certificate);
                }
            }
```

@christothes @jlichwa @RandalliLama do we feel this is sufficient to close out this issue?
