### ISSUE TITLE
[BUG] Custom dimensions are never deserialized from response (Microsoft.Azure.ApplicationInsights.Query)

### ISSUE THREAD

**Issue by older** [Azure/azure-sdk-for-net#13042]
Application Insights events can contain custom dimensions as described in [the documentation](https://dev.applicationinsights.io/documentation/Using-the-API/Events) so when they are present (as in all logging from Azure Functions, ASP.NET Core apps etc.) data client should return this data in the response.

[Generated model](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/applicationinsights/Microsoft.Azure.ApplicationInsights.Query/src/Generated/Models/EventsResultDataCustomDimensions.cs) does not provide any way to store de-serialized custom dimensions values, so the values are never available in C# response object.

It should be easy to reproduce in unit test by replacing `\"customDimensions\": null` with `\"customDimensions\": { \"key\": \"value\" }` in [session record file](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/applicationinsights/Microsoft.Azure.ApplicationInsights.Query/tests/SessionRecords/TraceEventsTests/GetTraceEvents.json) and verifying value of [CustomDimensions property](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/applicationinsights/Microsoft.Azure.ApplicationInsights.Query/src/Generated/Models/EventsResultData.cs#L91) in the response.

This can be fixed by adding customized partial implementation of `EventsResultDataCustomDimensions` [class](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/applicationinsights/Microsoft.Azure.ApplicationInsights.Query/src/Customized/Models):
```csharp
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Azure.ApplicationInsights.Query.Models
{
    public partial class EventsResultDataCustomDimensions
    {
#pragma warning disable CS0649 // Field is never assigned to, and will always have its default value
        [JsonExtensionData]
        private IDictionary<string, JToken> _customDimensionsValues;
#pragma warning restore CS0649 // Field is never assigned to, and will always have its default value

        public IEnumerable<string> Keys => _customDimensionsValues?.Keys;

        public bool TryGetValue(string key, out string value)
        {
            if (_customDimensionsValues != null && _customDimensionsValues.TryGetValue(key, out var jToken))
            {
                value = jToken?.ToString();
                return true;
            }
            value = null;
            return false;
        }
    }
}
```

 - Name and version of the Library package used: Microsoft.Azure.ApplicationInsights.Query 0.9.0-preview

**Comment by older** [comment]
Hi @jsquire 

Could we get some response from the team responsible for this library? 
There's now pull request which fixes this, but still no indication anyone has looked at this...

**Comment by jsquire** [comment]
Hi @older.   I'm sorry that there has been no response here.   Unfortunately, in this case I'm only acting as the first line triage and don't have insight into the library or its workstreams.

@geneh, @lmolkova - Would either of you be able to help connect with the right folks to assist here?

**Comment by older** [comment]
@AlexGhiondea thanks for pushing this!
Do you know when new (maybe still preview) version of[ Microsoft.Azure.ApplicationInsights.Query NuGet package](https://www.nuget.org/packages/Microsoft.Azure.ApplicationInsights.Query/) with this fix can be expected?

**Comment by geneh** [comment]
@older The package with this fix has been published. Thanks for the contribution!
