### ISSUE TITLE
[BUG] ShareFileClient used with read-only SAS, on operations like Upload should throw an authorization error

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#13060]
**Describe the bug**
When create a ShareFileClient with a SAS key which has only read permission, write operation like Upload returns null. I believe it should fail with authorization error.

**Expected behavior**
What is the expected behavior?
It should fail with a 403 error

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Upload returns null (more information needed here)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create ShareFileClient with a read only permission
2. Attempt to upload

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Files.Shares 12.2.3

**Comment by amnguye** [comment]
I tried reproducing the problem you are running into but a **code snippet** would better help understand the issue you are running into when given a SAS key and attempting to upload. Are you creating the sas using the SDK, or are you generating it somewhere else?

**Comment by Alanddq** [comment]
@amnguye 
Generate sas key via SDK, here is an example

            ShareFileClient file = ...

            var builder = new ShareSasBuilder
            {
                ShareName = shareName,
                Resource = "f",
                FilePath = file.Path,
                ExpiresOn = DateTimeOffset.UtcNow.AddMinutes(1)
            };

            builder.SetPermissions(ShareFileSasPermissions.Read);

            var sasUri = new UriBuilder(file.Uri)
            {
                Query = builder.ToSasQueryParameters(sharedKeyCred).ToString()
            };

            ShareFileClient sfc = new ShareFileClient(new Uri(sasUri.ToString()));

            var res = await sfc.UploadAsync(new MemoryStream(Encoding.UTF8.GetBytes("a"))); // should throw but nothing happen
  
            var resValue = res.Value;  //this throws System.NullReferenceException

**Comment by amnguye** [comment]
Thanks for the code snippet I was able to reproduce your issue.

For now, at least for this instance, a workaround is to use `UploadRangeAsync`

Here's a code snippet
```
            ShareFileClient fileClient = ...

            await fileClient.CreateAsync(Constants.KB);
            ShareSasBuilder sasBuilder = new ShareSasBuilder
            {
                ShareName = shareName,
                Resource = "f",
                FilePath = fileClient.Path,
                ExpiresOn = DateTimeOffset.UtcNow.AddMinutes(1)
            };
            sasBuilder.SetPermissions(ShareFileSasPermissions.Read);
            UriBuilder sasUri = new UriBuilder(fileClient.Uri)
            {
                Query = sasBuilder.ToSasQueryParameters(
                    new StorageSharedKeyCredential(
                        TestConfigDefault.AccountName,
                        TestConfigDefault.AccountKey)).ToString()
            };

            ShareFileClient readOnlyClient = new ShareFileClient(new Uri(sasUri.ToString()));

            var data = GetRandomBuffer(Constants.KB);
            Response<ShareFileUploadInfo> response;
            using (var stream = new MemoryStream(data))
            {
                **response = await readOnlyClient.UploadRangeAsync(
                    range: new HttpRange(0, Constants.KB),
                    content: stream);** // 403 auth error
            }
            var resValue = response.Value;
```
