### ISSUE TITLE
Port storage accounts to US Gov and other cloud for live test

### ISSUE THREAD

**Issue by XuGuang-Yao** [Azure/azure-sdk-for-net#13110]
The azure-sdk-for-net\sdk\formrecognizer\test-resources.json uses a predifined storage account(**azuresdktrainingdata**) to test. But the storage accout is only avaiable in subscription '2cd617ea-1866-46b1-90e3-fffb087ebf9b' in AzureCloud which means it is impossible for US Gov or China Cloud to access. 
![image](https://user-images.githubusercontent.com/53599438/86089158-4a469d00-bada-11ea-9011-328bb38efd89.png)

So we need to create a storage account with same structure as azuresdktrainingdata, but in US Gov Cloud. It will be used to test Form Recognizer service in US Gov Cloud.

**Comment by tzhanl** [comment]
@jongio for notification.

**Comment by danieljurek** [comment]
Resources are copied to storage accounts for China and US Gov clouds: 

China Cloud: https://portal.azure.cn/?whr=azure.com#@mcdevops.partner.onmschina.cn/resource/subscriptions/44b2f395-b47b-462a-9a40-6ec719b6b910/resourceGroups/TrainingData/providers/Microsoft.Storage/storageAccounts/azuresdktrainingdata/overview

US Gov: https://portal.azure.us/#@fairfaxdevops.onmicrosoft.com/resource/subscriptions/4ad9eeaf-9573-4288-8357-1445436f34cd/resourceGroups/TrainingData/providers/Microsoft.Storage/storageAccounts/azuresdktrainingdata/overview

The storage account names happen to be identical to the storage accounts in the public cloud so I think the only parameter that needs updating in `ArmTemplateParameters` is `trainingDataResourceId`... the value should be something like: 

```
 [resourceId('<subscription_id>', 'TrainingData', 'Microsoft.Storage/storageAccounts', parameters('trainingDataAccount'))]
```

**Comment by maririos** [comment]
dup of https://github.com/Azure/azure-sdk-for-net/issues/18522
