### ISSUE TITLE
[TextAnalytics] Rest API version 3.0 is not supported in China Cloud

### ISSUE THREAD

**Issue by XuGuang-Yao** [Azure/azure-sdk-for-net#13111]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

When we test TextAnalytics service in Azure China cloud. All failed tests return 404 'The requested resource is not found'.

This is because TextAnalytics SDK is hard coded to use 3.0 Rest API, but Azure China TextAnalytics service only supports Rest API 2.1, 3.0 is not supported.

Request Uri send by test is https://<ServiceName>.cognitiveservices.azure.com/text/analytics/v3.0/languages which's version is higher than the China cloud 's REST API version https://<ServiceName>.cognitiveservices.azure.com/text/analytics/v2.1/languages.
 
The request version has been defined as v3.0 in azure-sdk-for-net/sdk/textanalytics/Azure.AI.TextAnalytics/src/TextAnalyticsClientOptions.cs.
 
```csharp
internal string GetVersionString()
{
    switch (Version)
    {
        case ServiceVersion.V3_0:
            return "v3.0";
 
        default:
            throw new ArgumentException($"Version {Version.ToString()} not supported.");
    }
}
```

**Comment by maririos** [comment]
@XuGuang-Yao is your request that Azure China Cloud should accept newer service versions? or that the SDK should support lover versions?
Note that if you mean the later, the Azure.AI.TextAnalytics package is intended to support v3.0 and forward. For lower versions, use [Microsoft.Azure.CognitiveServices.Language.TextAnalytics](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Language.TextAnalytics/) package.

**Comment by XuGuang-Yao** [comment]
@maririos - Here is the background:
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

Based on that, we don't think it is an option to switch live tests of Azure.AI.TextAnalytics to use Microsoft.Azure.CognitiveServices.Language.TextAnalytics package.

If Azure.AI.TextAnalytics not support lower versions, but Azure China Cloud not update to latest version. This would end up that Azure.AI.TextAnalytics not work with Azure China Cloud.

**Comment by maririos** [comment]
Thanks for the context @XuGuang-Yao .

@assafi do you know how/if TA v3.0 is going to be enable in other clouds, like Azure China Cloud?

**Comment by assafi** [comment]
Sorry for the late response. China clusters should become online very soon. China East 2 is ready but China North 2 is still pending.
I sent the platform team a note and should have an ETA soon.
USGov clusters are already available.

**Comment by danieljurek** [comment]
@tzhanl -- Please try the pipeline again and let us know if it's passing or failing.

**Comment by tzhanl** [comment]
3.0 still not supported in China Cloud.

**Comment by maririos** [comment]
FYI Disabled from CI for now

**Comment by jongio** [comment]
@v-xuto - Can you please re-run to see if it still fails?

**Comment by zedy-wj** [comment]
@jongio - It still fails when running in Azure China Cloud.

**Comment by zedy-wj** [comment]
This issue has not recurred, we will close this issue, thanks all!
