### ISSUE TITLE
EventProcessorClient throws NullReferenceException when using IoT Hub connectionstring

### ISSUE THREAD

**Issue by Kolky** [Azure/azure-sdk-for-net#13131]
**Library or service name.**
Azure.Messaging.EventHubs.Processor.EventProcessorClient
 
**Is your feature request related to a problem? Please describe.**
I was trying to create an EventProcessorClient that I wanted to connect to my IoT Hub; but by accident I used the wrong connection-string. The one from the "Shared access policies" instead of the "Event Hub compatible endpoint". Instead of giving a meaningful error it threw a NullReferenceException probably on [this line](
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor%7BTPartition%7D.cs#L305) (the stack-trace pointed me in that direction), because the wrong Connectionstring doesn't have an endpoint in it.

Would be smart to first check if the parsing was correct before continueing.

_(My first issue here; is this enough details, and is it a feature or rather a bug?)_

**Comment by jsquire** [comment]
Hi @Kolky.   Thank you for reaching out and we regret that you're running into difficulties.  That's definitely not the experience that we'd like to present for this scenario.  

Your analysis is spot-on; by the time we hit the line of code that you identified, the connection string should have already been validated by the `EventHubConnection`.  It seems as if we overlooked a case in that [validation](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubConnection.cs#L502).  

I'll take a look at fixing that up.  I'll grab a connection string from IoT Hub to start, but to be sure that we've got the right scenario covered, it would be helpful if you could share the connection string that triggered the behavior for you, with any shared key information redacted, of course.  I'm specifically interested in the format of the `EndPoint` token or, if I understood what you're describing, confirmation that there was none present.

> (My first issue here; is this enough details, and is it a feature or rather a bug?)

We definitely appreciate that you took the time to open your first issue to help us improve the Event Hubs experience.  To answer your questions: 

- The detail was at a good level, I was able to follow what you were describing.  That you were kind enough to look at the code and offer analysis of where the exception was triggered is above-and-beyond, and helpful.    

- As for feature or bug, it's probably closer to a bug in this case.  Our goal is to make sure that we present clear and helpful error information and, in this case, we failed that goal.

**Comment by Kolky** [comment]
Great to hear that it is being looked after. My connection string looks like this;

> HostName=xx.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=hash

**Comment by jsquire** [comment]
Fixed by #13288
