### ISSUE TITLE
Search: support serialized continuation tokens

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#13150]
Support saving and serializing continuation tokens so we can pause and resume searches.  We're removing the `new SearchOptions(continuationToken)` in the short term while we decide on the correct path forward and general pattern for `AsyncPageable`.

This was originally filed as #10600, we looked at this in #13014, and worked around it with #13149.

**Comment by AlexGhiondea** [comment]
Related to #10600

**Comment by AlexGhiondea** [comment]
@tg-msft can we close this now?

**Comment by tg-msft** [comment]
No, this still hasn't been fixed.  Leave it assigned to me though because this took a ton of discussion to agree on a solution and I've got all the relevant context.

**Comment by pallavit** [comment]
Given where we are @tg-msft do you see us implementing this any time soon? If not, I would rather close this as not planned. 
@ShivangiReja I think while working on a recent bugfix - I believe .NET continuation token was done differently than from the rest of the languages. It may be a good idea to reconcile between the 2 and see which would be a more robust implementation.

I believe other languages chose to populate continuation token from the service response while we do it manually and it may be more prudent to do the same (if there is no extra benefit we get from our implementation).

**Comment by ShivangiReja** [comment]
>@ShivangiReja I think while working on a recent bugfix - I believe .NET continuation token was done differently than from the rest of the languages. It may be a good idea to reconcile between the 2 and see which would be a more robust implementation.

@pallavit - That was different issue related to `SearchOptions`.

**Comment by ShivangiReja** [comment]
Closing this issue as "not planned" due to current priorities, and no users have requested this feature.
