### ISSUE TITLE
[BUG] [Storage Client] PageBlobClient.GetManagedDiskPageRangesDiff() may misuse “snapshot=” 2 times in the request Uri

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#13151]
**Describe the bug**

Send request with API PageBlobClient.GetManagedDiskPageRangesDiff() , See the “snapshot=” specify 2 times in the request Uri.
But per [rest doc](https://docs.microsoft.com/en-us/rest/api/storageservices/get-page-ranges), the Uri should contain “snapshot=<DateTime>” and “prevsnapshot=<DateTime>”.

And don't find Unit test for this API.

**Expected behavior**

The request generated is correct and align with rest doc

**Actual behavior (include Exception or Stack Trace)**

The Uri seems not correct.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Run `PageBlobClient.GetManagedDiskPageRangesDiff(null, PrevSnapshotTimeString, PrevBlobsnapshotUri)`
2. Get request Uri like following (“snapshot=” specify 2 times in the Uri): 
>> GET https://xxx.blob.core.windows.net/xxx/page?snapshot=2020-07-01T07:49:40.8325043Z&sv=2019-02-02&ss=b&srt=sc&se=2020-07-01T08%3A50%3A51Z&sp=rl&sig=xxx&comp=pagelist&snapshot=2020-07-01T07%3A49%3A46.6857304%2B00%3A00

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.4.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by sachin-laddha** [comment]
any update on this issue?

**Comment by sachin-laddha** [comment]
I tried the sample application but getting failure while executing API "GetManagedDiskPageRangesDiffAsync"


tep into: Stepping over non-user code 'ConsoleApplication2.Program.CopyChangesSinceLastSnapshotToBaseBlob'
Step into: Stepping over non-user code 'ConsoleApplication2.Program.<CopyChangesSinceLastSnapshotToBaseBlob>d__3..ctor'
The thread 0x1d28 has exited with code 0 (0x0).
Exception thrown: 'Azure.RequestFailedException' in mscorlib.dll
Exception thrown: 'Azure.RequestFailedException' in mscorlib.dll
An exception of type 'Azure.RequestFailedException' occurred in mscorlib.dll but was not handled in user code
The previous snapshot url must be a snapshot of the target blob.
RequestId:87bcc880-001e-002f-114b-542f5f000000
Time:2020-07-07T10:42:51.6615347Z
Status: 400 (The previous snapshot url must be a snapshot of the target blob.)
ErrorCode: PreviousSnapshotUrlResourceMismatch

Headers:
x-ms-error-code: PreviousSnapshotUrlResourceMismatch
x-ms-request-id: 87bcc880-001e-002f-114b-542f5f000000
x-ms-version: 2019-07-07
x-ms-client-request-id: af81cb1c-1490-48ef-9a94-4912ede439c6
Date: Tue, 07 Jul 2020 10:42:50 GMT
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
Content-Length: 269
Content-Type: application/xml

An unhandled exception of type 'Azure.RequestFailedException' occurred in mscorlib.dll
The previous snapshot url must be a snapshot of the target blob.
RequestId:87bcc880-001e-002f-114b-542f5f000000
Time:2020-07-07T10:42:51.6615347Z
Status: 400 (The previous snapshot url must be a snapshot of the target blob.)
ErrorCode: PreviousSnapshotUrlResourceMismatch

Headers:
x-ms-error-code: PreviousSnapshotUrlResourceMismatch
x-ms-request-id: 87bcc880-001e-002f-114b-542f5f000000
x-ms-version: 2019-07-07
x-ms-client-request-id: af81cb1c-1490-48ef-9a94-4912ede439c6
Date: Tue, 07 Jul 2020 10:42:50 GMT
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
Content-Length: 269
Content-Type: application/xml

The program '[11160] ConsoleApplication2.exe' has exited with code 0 (0x0).



Can someone please help with this issue

**Comment by ramankumarlive** [comment]
did u use incremental snapshots of the same managed disk as mentioned in the sample?

**Comment by sachin-laddha** [comment]
yes... its incremental snapshot of the same managed disk

**Comment by sachin-laddha** [comment]
Can you please help out with this issue. Why the API with error "The previous snapshot url must be a snapshot of the target blob".

**Comment by sachin-laddha** [comment]
getManagedDiskPageRangesDiff API fails if the previous snapshot is "full" and the current snapshot is "incremental"? Is this API supposed to return page difference between a full and incremental snapshot? if not, which API can be used to get the page difference between a full and incremental snapshot.

**Comment by ramankumarlive** [comment]
Differential capability works only for **incremental** snapshots. It does NOT work for full snapshots. Please note that the first incremental snapshot is full under the hood and subsequent incremental snapshot occupy delta changes. Please read about it here: https://azure.microsoft.com/en-us/blog/announcing-general-availability-of-incremental-snapshots-of-managed-disks/

**Comment by sachin-laddha** [comment]
ok.. thanks for confirming. 
I thought that the API would return the page difference between a "full" and "incremental" snapshot.

**Comment by seanmcc-msft** [comment]
I'm not able to repo in our unit tests:  https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/PageBlobClientTests.cs#L1375.

Here is the request from Fiddler:
```
GET http://md-58xxscnapsn4prde16j.blob.preprod.core.windows.net/test-container-42d310fe-e4ae-46de-827e-76a3a088d232/test-blob-9d5cc965-2eda-4cb1-87f0-abfdb43084fc?comp=pagelist&snapshot=2020-07-13T19%3A49%3A36.5849973Z HTTP/1.1
x-ms-version: 2019-07-07
x-ms-previous-snapshot-url: http://md-58xxscnapsn4prde16j.blob.preprod.core.windows.net/test-container-42d310fe-e4ae-46de-827e-76a3a088d232/test-blob-9d5cc965-2eda-4cb1-87f0-abfdb43084fc?snapshot=2020-07-13T19:49:36.4649117Z
x-ms-range: bytes=0-4095
x-ms-client-request-id: 758da43a-65cf-45fc-a9aa-9f8b68d61bd6
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.5.0-dev.20200713.1 (.NET Core 4.6.28801.04; Microsoft Windows 10.0.18362 )
x-ms-date: Mon, 13 Jul 2020 19:49:35 GMT
Authorization: SharedKey md-58xxscnapsn4prde16j:+rmejv3bt3LCQGwadqYWZt9UzqvrohSFDqvJ65FkGos=
traceparent: 00-4f6e4173d6a3e840b44334e6d0339165-115b624a7fc7c341-00
Host: md-58xxscnapsn4prde16j.blob.preprod.core.windows.net
```

Note that there is a single snapshot query parameter.  

I believe issue was caused in the repo by manually adding the snapshot to the URI twice.

**Comment by blueww** [comment]
@seanmcc-msft 
Thanks for the reply!

I think the issue might cause:
I use a  PageBlobClient which created with snapshot Uri, and also added the parameter "snapshot" as the page blob snapshot time, so the “snapshot=” specify 2 times in the Uri.
Would you please confirm if this usage is the cause of the issue? 
If so, we might should clarify it clearly in the [doc](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.pageblobclient.getmanageddiskpagerangesdiffasync?view=azure-dotnet) that if the PageBlobClient is on a snapshot, should not specify parameter "snapshot" again.

@sachin-laddha Not sure if your issue is resolved. Would you please raise if any thing still need Sean's help?

**Comment by ramankumarlive** [comment]
@blueww The issue should be closed as the function was incorrectly used for getting diffs between a full snapshot (a page blob under the hood) and an incremental snapshot (a page blob snapshot on a different blob). 

Again the two times Snapshot issue can be caused when one of the parameters is set as empty string instead of null. I faced the same issue and fixed it a while ago. Please see the PR below with the fix. 

https://github.com/Azure-Samples/managed-disks-dotnet-backup-with-incremental-snapshots/commit/05c0049b9830c8e231727f37425babd20a80ee7c
