### ISSUE TITLE
Search: Add JsonConverters for Microsoft.Spatial

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#13165]
Let's investigate releasing a support package for Track 1 customers that enables them to keep using Microsoft.Spatial types with our Track 2 library by providing JsonConverters.  We should look at whether we can support both System.Text.Json and Json.NET (as separate packages).

We can start with the existing Track 1 converters at https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Microsoft.Azure.Search.Data/src/Customizations/Serialization/GeoJsonPointConverter.cs.  Most of the work will be deciding on a strategy for releasing targeted support packages like this.

**Comment by pakrym** [comment]
Should this be search specific?

**Comment by tg-msft** [comment]
I'm not sure yet - this is more of a placeholder than a plan.  If it's a lot of work to do this for ALL of Microsoft.Spatial, then we'll probably only light up the parts we need for Search and maybe Cosmos.  We also need to reach out to the OData folks who own Microsoft.Spatial with a heads up and see if there's an opportunity to collaborate.
