### ISSUE TITLE
[FEATURE REQ]

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk-for-net#13183]
**Library or service name.**
App configuration
 
**Is your feature request related to a problem? Please describe.**
Recording feature request following customer call 7/2/2020 with "@mymatrixpixel"

- Need a way to delete all the keys at the portal or through C# (global checkbox to select all the keys)
- Need a way to search by value
- Need performance improvement: "azure app configuration is too slow, always loading more keys "
- File export should have an option to export key, value, start and end date

**Comment by mymatrixpixel** [comment]
@elraikhm Can you give any update on this.

**Comment by lisaguthrie** [comment]
Deleting all keys: We are working on the ability to do this in the portal.

Searching by value: This is something we could consider. Can you share a use case where you'd want to use this functionality, so we can understand better? One quick way to do this today is to use the "Show values" button in the portal to view all values, then use the browser's Find feature to search for a particular value. 

Performance improvements: Is this in the portal? Or when loading configuration in your application?

File export: The current export does keys and values, and allows you to specify a point in time that you want to export from (e.g. you could export all the keys/values that were present as of last Tuesday). Is there additional functionality that you're looking for?

**Comment by mymatrixpixel** [comment]
@lisaguthrie Search by Value should be in Azure portal. Browser search won't work. If we have huge appsettings.

Performance Issue in Azure portal. If we search for key and configuration page is loading too slow. Can we have grid paging based on lable filter to see. 

Also, azure key vault as reference values are not showing.

Thanks.

**Comment by AlexanderSher** [comment]
@mymatrixpixel , Azure portal isn't part of SDK. All portal-related feature requests should be created in https://github.com/Azure/AppConfiguration/ repo, e.g.:

- Deleting all keys: https://github.com/Azure/AppConfiguration/issues/48
- File export: https://github.com/Azure/AppConfiguration/issues/192

Can you please create individual feature requests for any improvements you would like to have on the portal?

**Comment by mymatrixpixel** [comment]
Ok thanks. @AlexanderSher
