### ISSUE TITLE
MSI when local debugging gives token from wrong issuer

### ISSUE THREAD

**Issue by Crossbow78** [Azure/azure-sdk-for-net#13202]
**Situation**
My Azure Function app is enumerating key vaults in a subscription using MSI. Here's the code fragment that configures the Azure [Key Vault management client](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.keyvault.keyvaultmanagementclient?view=azure-dotnet):
```csharp
            builder.Services.AddSingleton<IKeyVaultManagementClient>(provider =>
                new KeyVaultManagementClient(new TokenCredentials(new AppAuthenticationTokenProvider()))
                {
                    SubscriptionId = "XXX-XXX-XXX-XXX",
                });
```
When this is deployed to Azure, I can grant the function app's MSI access to the key vaults it's allowed to find, and it will work perfectly fine.

Now I'm running the app locally, where I have configured my Microsoft Live account in Visual Studio (who is also subscription owner for the specified subscription above). When running my function app locally, it receives a token from issuer `https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/` (does this GUID represent some generic Live tenant?). The following error is the result:
> _The access token is from the wrong issuer 'https://sts.windows.net/f8cdef31-a31e-4b4a-93e4-5f571e91255a/'. It must match the tenant 'https://sts.windows.net/XXX-XXX-XXX-XXX/' associated with this subscription. Please use the authority (URL) 'https://sts.windows.net/XXX-XXX-XXX-XXX/' to get the token._

**Questions**
1. Can I configure a 'trust' or 'whitelist' somewhere in my Azure AD for this specific issuer?
2. Otherwise, am I forced to refactor the above code and explicitly specify a tenant id? It feels clunky and requires unnecessary configuration.

**Environment**
* Windows 10 Pro x64
* Visual Studio 2019 16.6.2
* .NET Core 3.1

**Comment by TechWatching** [comment]
@Crossbow78 Have you tried to set AZURE_TENANT_ID in your launchsettings.json and use DefaultAzureCredential ?It should work both locally and in Azure with Managed Identity.

**Comment by Crossbow78** [comment]
I forgot to mention that `AppAuthenticationTokenProvider` is a custom implementation of ITokenProvider:
```csharp
    internal class AppAuthenticationTokenProvider : ITokenProvider
    {
        private readonly AzureServiceTokenProvider _tokenProvider = new AzureServiceTokenProvider();
        public async Task<AuthenticationHeaderValue> GetAuthenticationHeaderAsync(CancellationToken cancellationToken)
        {
            var accessToken = await _tokenProvider.GetAccessTokenAsync("https://management.azure.com/", cancellationToken: cancellationToken);
            return new AuthenticationHeaderValue("Bearer", accessToken);
        }
    }
```

I've already set the AZURE_TENANT_ID, but how exactly would I use `DefaultAzureCredential` with this `KeyVaultManagementClient`?

**Comment by erich-wang** [comment]
@Crossbow78, could you please try to specify tenantId in _tokenProvider.GetAccessTokenAsync(xxx) ?

**Comment by Crossbow78** [comment]
> @Crossbow78, could you please try to specify tenantId in _tokenProvider.GetAccessTokenAsync(xxx) ?

Ah, yeah, that works.

But would you agree that we shouldn't include an explicit TenantId in configuration only because the local environment needs it?

**Comment by erich-wang** [comment]
I agree. You may use preprocessor directive to include tenantId only in local environment.

**Comment by erich-wang** [comment]
Close the issue since no further action needed, thanks.
