### ISSUE TITLE
[BUG] Overwrite is not the default for Azure Data Lake Gen2 path that already exists; documentation states otherwise.

### ISSUE THREAD

**Issue by PeterDowdy** [Azure/azure-sdk-for-net#13214]
**Describe the bug**
Calling UploadAsync on an Azure Data Lake Gen2 file to a path that already exists throws an error, when the documentation states that it should overwrite the file. The documentation states that overwrite is the default behaviour: https://github.com/Azure/azure-sdk-for-net/blob/Azure.Storage.Files.DataLake_12.2.2/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileClient.cs#L2863
But overwrite is not the default behaviour; it must be passed explicitly: https://github.com/Azure/azure-sdk-for-net/blob/Azure.Storage.Files.DataLake_12.2.2/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileClient.cs#L2885

It seems like a really easy fix, although it's not clear if the documentation or the code should be fixed.

**Expected behavior**
Calling UploadAsync on an Azure Data Lake Gen2 file to a path that already exists overwrites the file.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Calling UploadAsync on an Azure Data Lake Gen2 file to a path that already exists fails with a 409, unless the overwrite: true positional argument is passed.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a file.
2. Create a FileClient.
3. Upload anything to that file.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Files.DataLake 12.2.2
 - Hosting platform or OS and .NET runtime version: Windows 10, .NET Core 3.1
 - IDE and version : VS Code

**Comment by amnguye** [comment]
Resolved in this PR https://github.com/Azure/azure-sdk-for-net/pull/13343
