### ISSUE TITLE
[FEATURE REQ] Azure Data Lake Gen2 DirectoryClient list paths in directory

### ISSUE THREAD

**Issue by PeterDowdy** [Azure/azure-sdk-for-net#13216]
**Library or service name.**
Azure.Storage.Files.DataLake
 
**Is your feature request related to a problem? Please describe.**
The DirectoryClient can manipulate files within a directory, but has no way to list those files. Since FilesystemClient already supports this, it's possible by creating a FilesystemClient and looking up that path, but it seems awkward. I'd like the ability to page through blobs in a directory, with optional recursion. It seems like it should be straightforward to copy from FileSystemClient, since the base class of DirectoryClient has access to DataLakeRestClient.

**Comment by amnguye** [comment]
Hi,

This is an interesting feature request. We will take it into consideration and update this thread if there's any update to this request.

Thanks for your input!
