### ISSUE TITLE
[BUG] BlobBaseClient.WithVersion()  will encode blob name

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#13222]
**Describe the bug**
In the just released Azure.Storage.Blobs 12.5.0-preview.5, the BlobBaseClient.WithVersion() not work well.

If the Blob Client has blob name include any special char like “/”, the char will be encoded after run BlobBaseClient.WithVersion().

I believe BlobBaseClient.WithSnapshot() should have same problem.
This issue also happen on class inherit from BlobBaseClient, like BlockBlobClient.WithVersion().

**Expected behavior**
the blob name should not be encoded after run BlobBaseClient.WithVersion() 

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
![image](https://user-images.githubusercontent.com/6926193/86487535-f0233180-bd90-11ea-9b2b-474dbbfc2481.png)

**To Reproduce**
1. Create a blobbaseclient with base blob Uri, the blob name contains "/", like "dir1/blob1"
2. run blobbaseclient.WithVersion(versionId) , the blob name encoded to "dir1%2Fblob1"

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.5.0-preview.5] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by blueww** [comment]
@AlexGhiondea
Would you please also add "Client" tag for the issue that's on storage dataplane?
As we will monitor the SRP storage issues: with "Storage" but not with "Client" tag.
As this issue is for dataplane, would you mind to add "Client" tag, so our monitor won't report it.

**Comment by seanmcc-msft** [comment]
I have a PR out to fix this issue - https://github.com/Azure/azure-sdk-for-net/pull/13334
