### ISSUE TITLE
Storage recordings broken by recent identity update

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#13236]
Because some of the storage tests recorded Azure.Identity calls they were broken by a recent behavior change of some of the credential types.

https://dev.azure.com/azure-sdk/public/_build/results?buildId=446484&view=ms.vss-test-web.build-test-results-tab&runId=11747526&resultId=113758&paneView=debug

We need to remove instrumenting from credential options.

**Comment by pakrym** [comment]
Was workaround by https://github.com/Azure/azure-sdk-for-net/pull/13213

**Comment by tg-msft** [comment]
fyi @seanmcc-msft

**Comment by seanmcc-msft** [comment]
@pakrym @tg-msft, do we have a plan for this one?  I'd like to revert https://github.com/Azure/azure-sdk-for-net/pull/13213 sometime in the next few weeks.

**Comment by tg-msft** [comment]
Yes, we need to stop recording Azure.Identity traffic and switch to using something like https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.TestFramework/src/TestEnvironment.cs#L253 instead.

I asked @JoshLove-msft to take a look at it.  If he can't get it done this week, I'll fix it on Monday.

**Comment by seanmcc-msft** [comment]
@tg-msft, @JoshLove-msft, did we also revert Ted's workaround from Thursday?

**Comment by JoshLove-msft** [comment]
> @tg-msft, @JoshLove-msft, did we also revert Ted's workaround from Thursday?

Yep
