### ISSUE TITLE
[Bug] PrivateEndpoints.DeleteAsync throws NullReferenceException

### ISSUE THREAD

**Issue by FluxBoson** [Azure/azure-sdk-for-net#13255]
**Describe the bug**
When calling into this method, it throws a NullReferenceException, while polling for the deletion of the private endpoint. The call actually succeeds with no error, but if you watch for this exception, it hits twice before the call finishes.

Microsoft.Azure.Management.Network.NetworkManagementClient.PrivateEndpoints.DeleteAsync

Using 20.0.2-preview:
```
<PackageReference Include="Microsoft.Azure.Management.Network" Version="20.0.2-preview" />
```

_**Exception or Stack Trace**_
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Rest.ClientRuntime.Azure
  StackTrace:
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.DeserializeToObject[TDeserializedBodyType](Func`1 deserializDelegate)

Steps to reproduce behavior:

- Attempt to delete private endpoint with DeleteAsync extension method. 

_**Code Snippet**_
```
var networkClient = await azureClientFactory.CreateNetworkClient(subscriptionId);

await networkClient.PrivateEndpoints.DeleteAsync(resourceGroupName, privateEndpointName);
```
**Expected behavior**
Task completes without any exception thrown

**Setup (please complete the following information):**
- OS: Windows 10
- IDE: Visual Studio Enterprise 2019 Version 16.5.4
- 20.0.2-preview

**Information Checklist**

- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Additional context**
The exception seems to be effectively the same as found here: #9770 , with a different initiate call but same failure of the internal polling call.

**Comment by erich-wang** [comment]
@FluxBoson , could you please provide the complete code for us to reproduce the issue?

**Comment by AyzaLeX** [comment]
I have same issue and I found reason for it: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/mgmtcommon/ClientRuntime.Azure/ClientRuntime.Azure/LRO/LROPollState.cs 

sometimes azure api can return response with no body, so method private TDeserializedBodyType DeserializeToObject<TDeserializedBodyType>(Func<JObject> deserializDelegate) will be called with 'null' value as parameter and will throw NRE on .ToObject() call

![изображение](https://user-images.githubusercontent.com/36474033/109310065-1ed8a580-7855-11eb-92a4-d2906130dce0.png)

**Comment by AlexGhiondea** [comment]
@AyzaLeX could you try the latest version of the library and see if this continues to repro?

**Comment by AlexGhiondea** [comment]
@AyzaLeX there is an updated version of Microsoft.Azure.Management.Network and I was wondering if that version might have addressed this.
