### ISSUE TITLE
[BUG] blob snapshot SAS generated from UserDelegationKey seems not work

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#13269]
**Describe the bug**
Generated a blob snapshot SAS (sr=bs) with UserDelegationKey (has "skoid=" and "sktid="), try to get blob properties with the SAS, server return 403.
Seems not a regression, this issue also repro on Track1 SDK.

Is there any Unit test for this. Would like to check if my way to use SDK is correct or not.

I tested  base blob and blob version with same way to generate SAS, they all work, only blob snapshot not work
C++ SDK generated blob snapshot SAS from UserDelegationKey  also works.

**Expected behavior**
Server should success.

**Actual behavior (include Exception or Stack Trace)**
server return 403

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create Blob snapshot SAS from UserDelegationKey  with Track2 SDK 
2. get blob properties with the SAS, Server will return 403

SAS URI:

> https://xxx.blob.core.windows.net/weitest/dir1/blob1?skoid=xxx&sktid=***&skt=2020-07-07T09%3A04%3A43Z&ske=2020-07-13T09%3A04%3A43Z&sks=b&skv=2019-12-12&sv=2019-12-12&st=2020-07-07T09%3A04%3A43Z&se=2020-07-13T09%3A04%3A43Z&sr=bs&sp=rw&sig=xxx&api-version=2019-02-02&snapshot=2020-07-06T09%3A35%3A03.3210307Z

Get Error:

> <Error>
> <Code>AuthenticationFailed</Code>
> <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:37738a64-801e-009e-2c40-54e5ff000000 Time:2020-07-07T09:25:11.7340960Z</Message>
> <AuthenticationErrorDetail>Signature did not match. String to sign used was rw 2020-07-07T09:04:43Z 2020-07-13T09:04:43Z /blob/xxx/weitest/dir1/blob1 xxx xxx 2020-07-07T09:04:43Z 2020-07-13T09:04:43Z b 2019-12-12 2019-12-12 bs 2020-07-06T09:35:03.3210307Z </AuthenticationErrorDetail>
> </Error>

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.4.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by seanmcc-msft** [comment]
@blueww, could you post a code snippet showing how you generated the user delegation blob snapshot sas?

**Comment by blueww** [comment]
@seanmcc-msft 
I have tried again after modify the code structure of SAS generation in Powershell, the SAS works now.
There might be some issue on my code side, or the server has some temperate issue. 

Anyway, I can't repro it now.
So close this issue.
