### ISSUE TITLE
[FEATURE REQ] Enable application insights end to end tracing for Event Grid

### ISSUE THREAD

**Issue by Expecho** [Azure/azure-sdk-for-net#13272]
**Library or service name.**
Microsoft.Azure.EventGrid
 
**Is your feature request related to a problem? Please describe.**
When using the SDK to send events and receive them (using Azure Functions for example) correlation data is not send which results in [Application Insights](https://docs.microsoft.com/en-us/azure/azure-monitor/app/app-insights-overview) not being able to correlate the event sending with the event handling.

I would like to see something similar as done with the [Azure Service Bus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing#service-bus-net-client-autotracing).

Currently it is very hard to get end-to-end tracing when Event Grid is involved.

**References**
https://github.com/microsoft/ApplicationInsights-dotnet/issues/1427
https://feedback.azure.com/forums/909934-azure-event-grid/suggestions/33306310-header-pass-through
https://feedback.azure.com/forums/357324-azure-monitor-application-insights/suggestions/40586104-support-for-correlated-tracing-through-event-grid

**Comment by jsquire** [comment]
//fyi:  @ellismg, @JoshLove-msft

**Comment by ahamad-MS** [comment]
Copied the same answer from issue #13575 

We are adding distributed tracing and OpenTelemetry support for CloudEvent 1.0 in our Data plane SDKs which we are currently working on (No final ETA yet). We will follow the approach documented here for CloudEvent 1.0: https://github.com/cloudevents/spec/blob/master/extensions/distributed-tracing.md

We are still in discussion on how to support that in the SDK for event grid event schema. This will require modifying the current event grid schema to include new properties for tracing. Again, no commitment on this work or ETA yet.

Will you be able to use CloudEvent initially? Does this answer your question/request?

**Comment by ahamad-MS** [comment]
@Expecho  Please feel free to close one of the two issues and keep the other one for tracking since both are about the same support/ask. thanks

**Comment by jfggdl** [comment]
@Expecho, in a week or so we are going to be releasing a new SDK preview version that provides distributed tracing support. Please note that this support is not offered in the current version of the SDKs (Microsoft.Azure.EventGrid which is the one that you are using), but for the new version currently in preview (Azure.Messaging.EventGrid). Please try it and let us know if you still have unmet requirements. This is the link to Azure SDKs. Just enter Event Grid in the search field:   https://azure.github.io/azure-sdk/

**Comment by Expecho** [comment]
I suppose I have to wait for an update of the `Microsoft.Azure.WebJobs.Extensions.Event` package, otherwise my azure function won;t be able to use the new `Azure.Messaging.EventGrid` package. Are there plans to create a preview of `Microsoft.Azure.WebJobs.Extensions.Event` that references he new `Azure.Messaging.EventGrid` package?

**Comment by JoshLove-msft** [comment]
> I suppose I have to wait for an update of the `Microsoft.Azure.WebJobs.Extensions.Event` package, otherwise my azure function won;t be able to use the new `Azure.Messaging.EventGrid` package. Are there plans to create a preview of `Microsoft.Azure.WebJobs.Extensions.Event` that references the new `Azure.Messaging.EventGrid` package?

Yes, there are plans to release a preview of the extensions package that references the new EventGrid library. @pakrym may have more details on this.

> And does the new package provide tracing for the event grid event schema as well, or is the CloudEvent schema the only supported schema? Looking at the [source](https://github.com/Azure/azure-sdk-for-net/tree/Azure.Messaging.EventGrid_4.0.0-beta.4/sdk/eventgrid/Azure.Messaging.EventGrid/tests/SessionRecords/EventGridClientLiveTests) I suspect only CloudEvent is supported for the end to end tracing. Correct? If so, the bad thing is that Event Grid triggered Azure Functions [only support the Event Grid Event schema](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid):

Tracing is supported for both EventGrid events and CloudEvents. I will clarify this in our README.

**Comment by JoshLove-msft** [comment]
Closing as this is enabled in the new library.

**Comment by Expecho** [comment]
@pakrym, since this issue is closed and cannot be used to track the outstanding work, do you have an issue number I can subscribe to so I know when I can actually update my solutions to use end-to-end tracing?

**Comment by Expecho** [comment]
> Closing as this is enabled in the new library.

I feel this might be a bit premature. The new library is still in preview, aslo there is no azure function integration yet we can use.

**Comment by pakrym** [comment]
@JoshLove-msft let's keep this open to verify the tracking E2E.

**Comment by JoshLove-msft** [comment]
> One last question: in #13575 the last comment says:
> 
> > We are still in discussion on how to support that in the SDK for event grid event schema. This will require modifying the current event grid schema to include new properties for tracing. Again, no commitment on this work or ETA yet.
> 
> It this still being discussed or is support for event grid event schema definitely dropped for the future? For now I have a workaround [here](https://github.com/Expecho/EventGrid-End-to-End-tracing) but it requires quit a lot of overhead code.

Adding @ahamad-MS to see if he has any updates on this piece.

**Comment by kevinp** [comment]
We too are very interested in getting end-to-end tracing working with Event Grid and Azure Functions (nodejs in our case).  Would it be possible to provide an update here @ahamad-MS?  We need to make a decision whether we manually implement the tracing as the workaround above demonstrates, or await a native solution.  The latter would be much preferred ;)

**Comment by ahamad-MS** [comment]
@jfggdl .. Can you please help answering this feature request for @kevinp .. I am not sure if this in plan for next semester or not.

@kevinp .. Can you please add this feature request to user voice too (in addition to this request here).

**Comment by SaurabhSharma-MSFT** [comment]
@jfggdl Can you please help on this.
@kevinp Were you able to add this feature to uservoice earlier ?

**Comment by JoshLove-msft** [comment]
This should not have been closed.

**Comment by UsmanMohammad** [comment]
Just wondering if there has been any progress on this? 

The combination of tracing and cloud events between event grid and azure functions is finnicky

We are seeing quite a gap as[ the documentation also says](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/messaging.eventgrid-readme#distributed-tracing):

> The Event Grid library supports distributing tracing out of the box. In order to adhere to the CloudEvents specification's guidance on distributing tracing, the library will set the traceparent and tracestate on the ExtensionAttributes of a CloudEvent when distributed tracing is enabled.

However we've not been able to see that working, in addition to noticing that eventgrid is ignoring `traceparent` header in the outgoing request.

There also seems to be a disconnect with the functions sdk and the event grid service. The functions sdk supports event grid trigger with cloud event schema, however event grid itself only sends EventGrid schema events to functions.

Is there a working roadmap for when these quirks will be ironed out?

**Comment by navba-MSFT** [comment]
@Expecho @UsmanMohammad Apologies for the late reply. We are looking into this and we will provide an update once we have more details on this.

@JoshLove-msft @jfggdl Could you please provide an update on this github thread ? Awaiting your reply.

**Comment by lmolkova** [comment]
I believe this was addressed in [Microsoft.Azure.WebJobs.Extensions.EventGrid](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/) package version 3.1.0 for Event Grid trigger with CloudEvents.

Here's the blog with more information and customizations for EventGrid schema or  HTTP hook: 
 https://devblogs.microsoft.com/azure-sdk/distributed-tracing-with-azure-functions-event-grid-triggers/
