### ISSUE TITLE
[BUG] Microsoft.Azure.Graph.RBAC.IDomainOperations.ListAsync odataQuery param is wrong type

### ISSUE THREAD

**Issue by colbylwilliams** [Azure/azure-sdk-for-net#13274]
**Describe the bug**

[`IDomainsOperations`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/graphrbac/Microsoft.Azure.Graph.RBAC/src/Generated/IDomainsOperations.cs) _(thus [`DomainsOperations`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/graphrbac/Microsoft.Azure.Graph.RBAC/src/Generated/DomainsOperations.cs) and [`DomainsOperationsExtensions`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/graphrbac/Microsoft.Azure.Graph.RBAC/src/Generated/DomainsOperationsExtensions.cs))_ `ListWithHttpMessagesAsync` (and `ListAsync`) methods take a `odataQuery` parameter of type `ODataQuery<User>`, but it should be of type `ODataQuery<Domain>`:

```csharp
Task<AzureOperationResponse<IEnumerable<Domain>>> ListWithHttpMessagesAsync(ODataQuery<User> odataQuery = default(ODataQuery<User>), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
```

**Expected behavior**

The `odataQuery` parameter in [`ListWithHttpMessagesAsync`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/graphrbac/Microsoft.Azure.Graph.RBAC/src/Generated/IDomainsOperations.cs#L48) (and [`ListAsync`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/graphrbac/Microsoft.Azure.Graph.RBAC/src/Generated/DomainsOperationsExtensions.cs#L53-L59)) should be of type `ODataQuery<Domain>`:

```csharp
Task<AzureOperationResponse<IEnumerable<Domain>>> ListWithHttpMessagesAsync(ODataQuery<User> odataQuery = default(ODataQuery<Domain>), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));
```

**Actual behavior (include Exception or Stack Trace)**

The `odataQuery` parameter in [`ListWithHttpMessagesAsync`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/graphrbac/Microsoft.Azure.Graph.RBAC/src/Generated/IDomainsOperations.cs#L48) (and [`ListAsync`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/graphrbac/Microsoft.Azure.Graph.RBAC/src/Generated/DomainsOperationsExtensions.cs#L53-L59)) is the incorrect type: `ODataQuery<User>`

**Environment:**

 - Name and version of the Library package used: **Microsoft.Azure.Management.Graph.RBAC.Fluent 1.33.0**
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6
```
 - IDE and version : **Visual Studio Code 1.46.1**

**Comment by jsquire** [comment]
since this was filed, the `Microsoft.Azure.Graph.RBAC` library was formally retired and is no longer maintained.   Closing this out.
