### ISSUE TITLE
[BUG] Documentation for the Upload/UploadAsync methods don't describe overwrite behavior

### ISSUE THREAD

**Issue by normesta** [Azure/azure-sdk-for-net#13278]
**Describe the bug**
This bug is reported by a customer in this Github issue - [https://github.com/MicrosoftDocs/azure-docs/issues/57729](https://github.com/MicrosoftDocs/azure-docs/issues/57729). The text is: ---- Hi, the documentation for DataLakeFileClient here: [link](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakefileclient.uploadasync?view=azure-dotnet)
states in several places that "If the file already exists, its content will be overwritten." However, in my experience using this API, it seems it will actually will throw an error if it already exists, unless you use the version of the method with the overwrite flag, which must be explicitly set to true. Not sure if this is a doc issue or a bug, but thought I'd bring up here just in case.
Also, there is a typo with "overwritten"

**Expected behavior**
Unsure.

**Actual behavior (include Exception or Stack Trace)**
An error appears on overwrite when the file already exists.

**To Reproduce**
Use the Upload/UploadAsync methods without setting the overwrite flag to true.

**Environment:**
Unsure

**Comment by amishra-dev** [comment]
Thanks for passing this along @normesta 
My understanding is that this documentation is generated from the code comments, so once we fix that and publish to nuget we should be good? Or are there more steps to this?

**Comment by amnguye** [comment]
The `Upload`\`UploadAsync` has a parameter for `overwrite`. We default to fault for that value so the file doesn't get overwritten by the default behavior of the rest api which is to overwrite the existing file.

I will look to updating all the comments where we have mistakenly put that we will overwrite if the file already exists, when the SDK defaults to not overwriting.

**Comment by amnguye** [comment]
Since we have multiple `Upload` and `UploadAsync` methods, it looks like when the user passes a `DataLakeRequestConditions` we do not default to not overwritting. Will follow up with what we decide to do for this.
