### ISSUE TITLE
[BUG] Create a blob SAS with "rwxft", it does not work on download blob

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#13302]
**Describe the bug**
Create a blob SAS with "rwxft" permission on 12.5.0-preview.5, the SAS URi fail to download the blob.
But the SAS create with permission "rwx", "rwt", "rwf" in same way all works.

**Expected behavior**
Blob SAS can download the blob correctly.

**Actual behavior (include Exception or Stack Trace)**

```
<Error>
<Code>AuthenticationFailed</Code>
<Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:cc2d072a-e01e-00ea-0905-55d10f000000 Time:2020-07-08T08:52:17.0676265Z</Message>
<AuthenticationErrorDetail>Signature fields not well formed.</AuthenticationErrorDetail>
</Error>
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a blob SAS with "rwxft" (permission is set with BlobSasBuilder.SetPermissions(string rawPermissions))
2. Try to create blob with SAS Uri , and failed as error above. The sample SAS Uri is: 
> https://xxx.blob.core.windows.net/weitest/dir1/blob1?sv=2019-12-12&se=2020-07-08T09%3A52%3A10Z&sr=b&sp=rwxft&sig=xxx

Besides that, SAS create with permission "rwx", "rwt", "rwf" in same way all works, sample sas Uri as following:

> https://xxx.blob.core.windows.net/weitest/dir1/blob1?sv=2019-12-12&se=2020-07-08T09%3A55%3A28Z&sr=b&sp=rwx&sig=xxx
> https://xxx.blob.core.windows.net/weitest/dir1/blob1?sv=2019-12-12&se=2020-07-08T09%3A55%3A46Z&sr=b&sp=rwt&sig=xxx
> https://xxx.blob.core.windows.net/weitest/dir1/blob1?sv=2019-12-12&se=2020-07-08T08%3A26%3A45Z&sr=b&sp=rwf&sig=xxx

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.5.0-preview.5] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by seanmcc-msft** [comment]
'f' is not a valid blob SAS permission.  'f' only applies to Account SAS.

**Comment by blueww** [comment]
@seanmcc-msft 
Thanks for the reply!

Is there any function in track2 XSCL can convert the raw permission string to Blob/ContainerSasPermissions, like “SharedAccessBlobPolicy.PermissionsFromString()” Track1?

We need this since powershell cmdlet input permission as raw permission string (change it is breaking and not allowed until major release), so we need write code to convert it to Blob/ContainerSasPermissions  make sure the permission in right order(like use “SharedAccessBlobPolicy.PermissionsFromString()” in Track1), then create SAS.

If no such function, do you have a recommended way to convert it?
