### ISSUE TITLE
[BUG] DefaultAzureCredential GetTokenAsync throws errors locally

### ISSUE THREAD

**Issue by adiun** [Azure/azure-sdk-for-net#13309]
**Describe the bug**
When trying to use DefaultAzureCredential GetTokenAsync in VS Code, this fails with a number of token providers:
- The new VS Code provider on 1.2.0-preview.3+ throws with an error saying the user is not signed in with Azure (even after Sign Out + Sign In)
- Azure CLI provider times out
- Interactive Browser fails with AADSTS650057
- SharedTokenCredential fails

The only one that works is the Environment Variables provider but this is not an ideal experience (if you're running an C# test + Codelens that relies on DefaultAzureCredential you have to ensure that the environment vars are set and relaunch VSCode)

**Expected behavior**
This should work at least with the VS Code provider, signed into Azure.

**Actual behavior (include Exception or Stack Trace)**

Interactive browser error:
```
Authentication failed. You can return to the application. Feel free to close this browser tab.
Error details: error invalid_client error_description: AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). Resource value from request: https://daxteamsdev-adi-sidecar.azurewebsites.net. Resource app ID: a0ba30a6-b8af-4939-a9cb-2c93ed57892b. List of valid resources from app registration: . Trace ID: 45ea2e00-52cf-4427-a718-9c92620d0600 Correlation ID: dbc261a8-e9c3-4ae2-b42e-43439a7f9586 Timestamp: 2020-07-08 15:18:32Z
```

There are other errors with VS Code and Azure CLI providers. Let me know if you'd like me to post these errors but this should be straightforward to reproduce.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Add Azure.Identity 1.1.1+ to a .NET Core test project
2. In the test, use DefaultAzureCredential:

```csharp
var azureCredential = new DefaultAzureCredential(new DefaultAzureCredentialOptions() { ExcludeSharedTokenCacheCredential = true });
var accessToken = await azureCredential.GetTokenAsync(new TokenRequestContext(new string[] { "https://some/appiduri/.default" })).ConfigureAwait(false);
```

3. Debug the test via `Debug Test` codelens on the test method itself

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0]:
   * Azure.Identity 1.1.1
   * Azure.Identity 1.2.0-preview.3
   * Azure.Identity 1.2.0-preview.4

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]

.NET Core SDK (reflecting any global.json):
 Version:   3.1.201     
 Commit:    b1768b4ae7  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.18363
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

 - IDE and version : [e.g. Visual Studio 16.3]

Version: 1.46.1 (user setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by schaabs** [comment]
@adiun Thanks for filing this issue. Based off your the code in your repro, I think the problem may be the the scope you are trying to obtain a token for. In your test, you're requesting a token with the scope "https://some/appiduri/.default", but this is not a valid scope. 

~~~c#
var accessToken = await azureCredential.GetTokenAsync(new TokenRequestContext(new string[] { "https://some/appiduri/.default" })).ConfigureAwait(false);
~~~

This seems to be consistent with the error message your getting.

> AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration.

Scopes are per-registered with AAD by the azure resources they provide authorization to, and cannot be arbitrary strings. For instance the default scope for the Key Vault service in azure public cloud is "https://vault.azure.net/.default", and ARM is "https://management.core.windows.net/.default" 

Can you confirm this is in fact the scope you were using when you originally encountered this error? Also can you give some detail on your scenario? Generally users should not need to call `GetTokenAsync` directly. Rather they just instantiate the credential and give it to a client which will internally handle getting tokens for the appropriate scope for the service calls it is making.

**Comment by adiun** [comment]
Thanks @schaabs for the fast response. We want an MSI-enabled Azure App Service app "A" to call another AAD EasyAuth-enabled app "B" in the tenant. So I want to use the MSI in App "A" to get an access token that can be attached to the `Authorization` header of an HTTP request that calls into App "B".

My `some/appiduri/.default` was a bad example - I was trying to imply we're using [this pattern](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-v1-app-scopes#scopes-to-request-access-to-all-the-permissions-of-a-v10-application). Also mentioned [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#get-a-token). Basically the App ID URI + `/.default`. 

This is actually working pretty well with `DefaultAzureCredential` currently:
1. In Azure, App "A" uses App "B"'s resource: the App ID URI + `/.default` with `GetTokenAsync` which automatically uses the MSI provider. Works great.
2. We have unit tests that need to call into App "B". We use `DefaultAzureCredential` with the env var provider - we set `AZURE_CLIENT_ID`, etc. and use the same resource (App ID URI + `/.default`) with `GetTokenAsync` and this works fine too. 

Now for (2), a better way to do this is if you're in VS Code and running the unit test, I'd hope `DefaultAzureCredential` uses the VSCode credentials to get an access token, so we don't have to setup the env vars.

**Comment by schaabs** [comment]
> Now for (2), a better way to do this is if you're in VS Code and running the unit test, I'd hope DefaultAzureCredential uses the VSCode credentials to get an access token, so we don't have to setup the env vars.

In our latest preview we have added the `VisualStudioCodeCredential` to the `DefaultAzureCredential` authentication flow so if no environment variables are specified and managed identity is not available it should fall back to authenticating with the identity signed into the VSCode Azure Account extension. The complete `DefaultAzureCredential` authentication flow in our latest preview is as follows.

`EnvironmentCredential` -> `ManagedIdentityCredential` -> `SharedTokenCacheCredential` -> `VisualStudioCredential` -> `VisualStudioCodeCredential` -> `AzureCliCredential`

Since it seems you've worked through your issue here, I'm closing the issue. If you're still having problem please feel free to reopen the issue. Also if you have any issues or feedback authnenticating via VS Code locally using our preview please open a new issue to let us know.

**Comment by adiun** [comment]
Hi @schaabs this issue is actually regarding the preview VisualStudioCodeCredential - it doesn't work even after signing out and signing in. Agreed that the VisualStudioCodeCredential is what we want! In theory it's a much better experience than env vars.

from original issue:
> The new VS Code provider on 1.2.0-preview.3+ throws with an error saying the user is not signed in with Azure (even after Sign Out + Sign In)
> Expected behavior
> This should work at least with the VS Code provider, signed into Azure.

I can reopen a new issue but it'll be pretty much the same details/repro.
