### ISSUE TITLE
[BUG] the SasPermissions definition seems not correct in Azure.Storage.Blobs 12.5.0-preview.5

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#13301]
**Describe the bug**
In Azure.Storage.Blobs 12.5.0-preview.5, we find the definition of permission as following.
- BlobAccountSasPermissions：	racwdl
- BlobContainerSasPermissions	racwdxlt
- BlobSasPermissions：		racwdxt
- BlobVersionSasPermissions:	x
- SnapshotSasPermissions: 	rwd

But this is not correct：
- BlobAccountSasPermissions should contain BlobContainerSasPermissions, as the Account sas can be used to execute container level operation.
- Blobversion support read, BlobVersionSasPermissions should contain “r”

**Expected behavior**
BlobAccountSasPermissions should contain BlobContainerSasPermissions
BlobVersionSasPermissions should contain “r” (please check if other permission missing on blob version).

**Actual behavior (include Exception or Stack Trace)**
BlobAccountSasPermissions missing "xt" in BlobContainerSasPermissions, 
BlobVersionSasPermissions missing “r”

**To Reproduce**
See description

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.5.0-preview.5] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by JimSuplizio** [comment]
Hi @blueww, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
