### ISSUE TITLE
[BUG] Regression in BlobClient.DeleteIfExistsAsync, BlobClient.ExistsAsync and BlobContainerClient.ExistsAsync

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#13312]
**Describe the bug**
If the container does not exist when using `BlobClient.DeleteIfExistsAsync`, `BlobClient.ExistsAsync` and `BlobContainerClient.ExistsAsync`

in **v11**
An exception will not be thrown because the methods will catch the exception for them (ContainerNotFound)

in **v12**
An exception is thrown

**Expected behavior**
What is the expected behavior?
It should catch the exception if the container does not exist.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Throws a ContainerNotFound

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
Use `BlobClient.DeleteIfExistsAsync`, `BlobClient.ExistsAsync` and `BlobContainerClient.ExistsAsync` on a container that does not exist.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.4.2 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): all
 - IDE and version : n/a

**Comment by seanmcc-msft** [comment]
@amnguye, don't we return true or false if the Blob or Container exists or doesn't exist?  Also, I think the purpose of these methods is to save the customer from having to catch an exception.  I'm not sure that this is a regression.
