### ISSUE TITLE
Should we be able to deploy the Azure Security Center ARM template to enroll in ASC?

### ISSUE THREAD

**Issue by 1RedOne** [Azure/azure-sdk-for-net#13318]
**Query/Question**
Hi!  I'm using IAzure.Deployments to deploy a lot of ARM Templates for something I'm working on using the AzureSDK.  I've got an ARM Template that should enroll me in Azure Security Center, but this is done **[at the subscription level](https://techcommunity.microsoft.com/t5/azure-security-center/managing-security-center-at-scale-using-arm-templates-and-azure/ba-p/327761)**.  

Unless I'm missing something, it looks like the IAzure.Deployments options are either `WithNewResourceGroup()` or `WithExistingResourceGroup()`, niether of which are pertinent to this ARM Template.

Is IAzure.Deployments the way I should be doing this?

**Environment:**
 - `using Microsoft.Azure.Management.ResourceManager.Fluent`
- Dotnet - Version: 3.1.5
 - Visual Studio 2019

**Comment by isra-fel** [comment]
Hi @weidongxu-microsoft are you able to help? Thanks

**Comment by weidongxu-microsoft** [comment]
@1RedOne This feature is not integrated with fluent interface. You would have to use the raw REST APIs.

Please try this:
`IAzure.Deployments.Inner.CreateOrUpdateAtSubscriptionScopeAsync`
