### ISSUE TITLE
Enable spatial types support in Search

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#13319]
Once the Azure Core change (#10592) is merged, we need to re-enabled the APIs in Search to support it.

**Comment by heaths** [comment]
When we do this, we could remove the proxy classes for Microsoft.Spatial and instead use adapters to create GeoJson types. This would not only reduce the amount of code to maintain, but also remove the intentional duplication in `SpatialFormatter` to improve perf (no reason to allocate extra).

**Comment by AlexGhiondea** [comment]
This is done now.
