### ISSUE TITLE
[QUERY] I am getting 404 Resource not found exception while I am using Form recognizer trainingClient.StartTrainingAsync() method.

### ISSUE THREAD

**Issue by Vuharish** [Azure/azure-sdk-for-net#13339]
**Query/Question**
I am getting 404 Resource not found exception while I am using Form recognizer trainingClient.StartTrainingAsync() method.

**Environment:**
 - visual stuido 2019
- .net core 3.1

public static async Task<string> TrainModel(FormTrainingClient trainingClient, string trainingDataUrl)
        {
            try
            {
                Uri uri = new Uri(trainingDataUrl);
                CustomFormModel model = 
                    await trainingClient.StartTrainingAsync(uri, useLabels: false).WaitForCompletionAsync(); --  getting error here

trainingDataUrl - is my SAS blob URL.
trainingclient  - is var trainingClient = new FormTrainingClient(new Uri(endpoint), credential);

endpoint - my azure form recognizer endpoint
https://xxxxxxxxxxx.cognitiveservices.azure.com/formrecognizer/v2.0-preview/custom/models
credential - var credential = new AzureKeyCredential(apiKey);
apikey - key I took from the from recognizer service.

I tried in postman everything is working fine. but from console application it throws error. 

I am new to Form Recognizer. Pls help me with the issue.

**Comment by maririos** [comment]
Thanks @Vuharish . Which version from the client library are you using?

**Comment by Vuharish** [comment]
I have downloaded the package through this command.

Azure.AI.FormRecognizer --version 1.0.0-preview.1.

I tried using the second key instead of first key . It was working fine. Not sure what was the issue. 

Thanks for the help Maririos.

**Comment by Vuharish** [comment]
After using the second key I was able to hit the StartTrainingAsync method. Thanks
