### ISSUE TITLE
[BUG][Storage][DataLake] DataLakeDirectoryClient and DataLakeFileClient Exists()/ExistsAsync() give unexpected result

### ISSUE THREAD

**Issue by davidOSUL** [Azure/azure-sdk-for-net#13330]
**Describe the bug**
DataLakeDirectoryClient.Exists() and DataLakeFileClient.Exists() always return true when the path exists, regardless of the type of the path. I'm not sure if this is intended behavior, but if it is, it seems counterintuitive to what I would expect those methods to do. 
**Expected behavior**
When a file of the same name exists, DataLakeDirectoryClient.Exists() should return false, since it is not a directory of that name that exists, but a file. Similarly when a directory of the same name exists, DataLakeFileClient.Exists() should return false, since it is not a file of that name that exists, but a directory. 

**Actual behavior (include Exception or Stack Trace)**
DataLakeDirectoryClient will return true when a file of the same path exists, even though no such directory exists.
DataLakeFileClient will return true when a directory of the same path exists, even though no such file exists. 

**To Reproduce**
The following test shows this issue with DataLakeDirectoryClient. The final Assert will fail even though we'd expect it to succeed:
```csharp
[TestMethod]
        public void TestDirectoryClientExists()
        {
            const string newFile = "newFile.txt";
            DataLakeFileSystemClient fileSystemClient = this.GetFileSystemClient();
 
            // nothing initially.
            Assert.AreEqual(0, fileSystemClient.GetPaths().ToList().Count);
 
            // create a new file and assert we created it succesfully
            fileSystemClient.CreateFile(newFile);
            Assert.IsTrue(fileSystemClient.GetFileClient(newFile).Exists());
 
            // Assert that directory of name newFile does not exist.
            // We'd expect this Assert to pass, but it fails.
            Assert.IsFalse(fileSystemClient.GetDirectoryClient(newFile).Exists());
        }
```
You can make a duplicate test but swapping DataLakeFileClient/DataLakeDirectoryClient to get the same result but for DataLakeFileClient. 

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Files.DataLake 12.2.2
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET Core 3.1.301
 - IDE and version : Visual Studio 2019 16.6

**Comment by amnguye** [comment]
Hi,

I don't think this is a bug we can fix and could be a slight breaking change as well. We can have other people thinking the other way around, that they want to be able to see if that Path exists before creating anything there (e.g. Not wanting to creating a file with the same name as a directory and vice versa). Also if we change how this behaves, we will have customers coming back saying that the DatalakeFileClient.Exists() on a path that is a directory is coming back false, and will attempt to make a file over that path and get an error for attempting to do so.

A way to get around this, with making only one request to the service to check for existence and checking if it's a directory or file, is to make a GetProperties call on the path.
```
try
{
      Response<PathProperties> response = await directory.GetPropertiesAsync();
      if(response.Value.IsDirectory)
      {
            //it's a directory
      }
      else
      {
            //it's a file
      }
}
catch (RequestFailedException storageRequestFailedException)
when (storageRequestFailedException.ErrorCode == BlobErrorCode.BlobNotFound) // "BlobNotFound"
{
     // Path (file or directory) does not exist at all
}
```

Sorry for the inconvenience. I hope this workaround helps.
