### ISSUE TITLE
Azure.Data.AppConfiguration- AddSecretclient

### ISSUE THREAD

**Issue by mymatrixpixel** [Azure/azure-sdk-for-net#13342]
Hi Team,

How to read key vault information from Azure App Configuration.

Since we referred Key vault as a reference into Azure app configuration.( Have Lable). 

I want to read this Secret key and value form Azure App configuretion. In a my C# Library.

Please refer following code.

Var configCient = new ConfigureClient(connectionstring);

configCient.AddSecretClient();// how to add secretclient. And retrieve the secrets using C# Code. 

Note: Sample code is much appreciated instead of Docs. I have already referred MSDocs. But no luck.

Thanks.

**Comment by jsquire** [comment]
Hi @mymatrixpixel.  Thank you for reaching out and we regret that you're experiencing difficulties.  

You may want to take a look at the [[samples]](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/appconfiguration/Azure.Data.AppConfiguration/samples) for the AppConfiguration client library.  The basic operations for creating and reading secrets are demonstrated in the the first sample, [Sample1_HelloWorl](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/samples/Sample1_HelloWorld.md), and the samples that follow build on that knowledge to illustrate more involved scenarios.  I hope that helps to get you started and to unblock you.

**Comment by mymatrixpixel** [comment]
@jsquire  I have already referred it also those samples are only about CRUD. My question is how to use Secretclient in ConfigureClient. AddSecretClient is a extension method. Please provide sample for that.

**Comment by jsquire** [comment]
On that, I'll have to defer to the team working on AppConfig.  I've tagged this up to bring it to their attention; someone better able to assist should be taking a look in the near future.

**Comment by mymatrixpixel** [comment]
@jsquire Thanks.Since  It's a blocker. Please expedite.

**Comment by maririos** [comment]
@AlexanderSher could you please take a look?

**Comment by mymatrixpixel** [comment]
Do you have any update?

**Comment by jsquire** [comment]
Respectfully, @mymatrixpixel, these issues are not intended to provide critical support.   We strive to assist the best that we're able and as quickly, but you may see some latency in response when the individuals with expertise for a given library are engaged elsewhere.

If this is a critical blocking issue for you, I'd recommend that you open a [support ticket](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) with Azure.  That will give you access to a dedicated support team better able to assist with critical issues.

**Comment by mymatrixpixel** [comment]
Ok.i got your point will wait. No issues.

**Comment by AlexanderSher** [comment]
@mymatrixpixel , we don't provide support for KeyVault references out of the box. Here is the code you can use:

```cs
public async Task<string> GetSecretValueAsync(string key, TokenCredential credential, CancellationToken cancellationToken) {
    ConfigurationClient configurationClient = new ConfigurationClient(endpoint, credential);
    ConfigurationSetting setting = await configurationClient.GetConfigurationSettingAsync(key, cancellationToken);
    string secretUriString = JsonDocument.Parse(setting.Value).RootElement.GetProperty("uri").GetString();
    Uri secretUri = new Uri(r, UriKind.Absolute);

    string secretName = secretUri.Segments.ElementAtOrDefault(2).TrimEnd('/');
    string secretVersion = secretUri.Segments.ElementAtOrDefault(3).TrimEnd('/');
    string keyVaultId = secretUri.Host;

    var client = new SecretClient(new Uri(secretUri.GetLeftPart(UriPartial.Authority)), credential);
    KeyVaultSecret secret = await client.GetSecretAsync(secretName, secretVersion, cancellationToken).ConfigureAwait(false);
    return secret?.Value;
}
```
Any of the service calls can produce exceptions, `setting.Value` isn't guaranteed to have correct JSON object in it. `ConfigurationClient` and `SecretClient` can be cached for better performance.

**Comment by mymatrixpixel** [comment]
@AlexanderSher Thanks much for the code snippets. I will try and let you know. Also , I just want to understand (how setting.Value will break) service inconsistency or Json parse may break ( if there is new version)? . Can you give some info.

**Comment by AlexanderSher** [comment]
`setting.Value` isn't secured from being overridden. One of the things you can check is `ConfigurationSetting.ContentType`, which should be `application/vnd.microsoft.appconfig.keyvaultref+json`. Format for JSON today is simply `{"uri"="<secret uri>"}`, but AFAIK, there is no official document that describes it.

**Comment by mymatrixpixel** [comment]
@AlexanderSher  if we added a key as a Key  Vault reference in azure app Configuration. We can't able see the Key Vault secret Value in azure portal. Instead it showing as KeyVault Uri. Is there any additional permissons need to set in key vault or azure app configuration?

**Comment by AlexanderSher** [comment]
> Thanks much for the code snippets. I will try and let you know.

@mymatrixpixel Did snippet help you solve your problem?

**Comment by mymatrixpixel** [comment]
Yeah code snippet gave a idea Thank you @AlexanderSher
