### ISSUE TITLE
[Discussion] Service Bus - Track 2 - Management client - RuntimeProperties flattening

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#13353]
_The intent of this issue is to solicit feedback from the community in advance of the GA of the next major version of the Service Bus library (which will follow several Preview releases).
As a reference, the .NET Azure SDK guidelines can be found here: https://azure.github.io/azure-sdk/dotnet_introduction.html
Terminology:
Track 0 refers to the [WindowsAzure.ServiceBus library](https://www.nuget.org/packages/WindowsAzure.ServiceBus/)
Track 1 refers to the [Microsoft.Azure.ServiceBus library](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/)
Track 2 refers to the new library, [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/), we are working on releasing._

In the Track 1 Management API, the *RuntimeInfo types contain a nested [MessageCountDetails](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Management/MessageCountDetails.cs) type. This adds what feels like an unnecessary layer of indirection to what is already a fairly small type. We are proposing eliminating this type and lifting its properties directly onto the *RuntimeProperties (this rename was proposed in https://github.com/Azure/azure-sdk-for-net-pr/issues/1181) types. We would also rename the `MessageCount` property to `TotalMessageCount`:

Before:
```c#
public class QueueRuntimeInfo
    {
        public string Name { get; }
        public long MessageCount { get; }
        public MessageCountDetails MessageCountDetails { get; }
        public long SizeInBytes { get; }
        public DateTimeOffset CreatedAt { get; }
        public DateTimeOffset UpdatedAt { get; }
        public DateTimeOffset AccessedAt { get; }
    }

public class MessageCountDetails
    {
        public long ActiveMessageCount { get; }
        public long DeadLetterMessageCount { get; }
        public long ScheduledMessageCount { get; }
        public long TransferMessageCount { get; }
        public long TransferDeadLetterMessageCount { get; }
    }
```
After:
```c#
public class QueueRuntimeProperties
    {
        public string Name { get; }
        public long TotalMessageCount { get; }
        public long ActiveMessageCount { get; }
        public long DeadLetterMessageCount { get; }
        public long ScheduledMessageCount { get; }
        public long TransferMessageCount { get; }
        public long TransferDeadLetterMessageCount { get; }
        public long SizeInBytes { get; }
        public DateTimeOffset CreatedAt { get; }
        public DateTimeOffset UpdatedAt { get; }
        public DateTimeOffset AccessedAt { get; }
    }
```

**Comment by SeanFeldman** [comment]
From a consumer point of view, flattening `QueueRuntimeInfo` is not an issue.
`MessageCount` to `TotalMessageCount` renaming is good.
The `SizeInBytes` property, wish it was a value object where the size could be returned in KB, MB, or GB. When a normal queue load is measured in MB, the size in KB requires continuous math in user code rather than just have it in the unit of measure that makes more schemes to the customer use cases and workloads.

**Comment by JoshLove-msft** [comment]
> From a consumer point of view, flattening `QueueRuntimeInfo` is not an issue.
> `MessageCount` to `TotalMessageCount` renaming is good.
> The `SizeInBytes` property, wish it was a value object where the size could be returned in KB, MB, or GB. When a normal queue load is measured in MB, the size in KB requires continuous math in user code rather than just have it in the unit of measure that makes more schemes to the customer use cases and workloads.
> 
> BTW, I'm assuming you'll have a similar type for Subscriptions? I.e. `SubscriptionRuntimeProperties`. It wasn't mentioned so want to make sure it's not overlooked.

Interesting, are you saying have some sort of struct that would contain properties for the size in each of the mentioned units? Size in bytes allows us to give full precision whereas if we were to introduce the other units as you mention, we would probably need to represent these as floats or doubles rather than long.

**Comment by JoshLove-msft** [comment]
> BTW, I'm assuming you'll have a similar type for Subscriptions? I.e. `SubscriptionRuntimeProperties`. It wasn't mentioned so want to make sure it's not overlooked.

Yep, thanks for calling that out. This change will also apply to `SubscriptionRuntimeProperties`.

**Comment by SeanFeldman** [comment]
> Interesting, are you saying have some sort of struct that would contain properties for the size in each of the mentioned units? 

Correct, Josh.

> Size in bytes allows us to give full precision whereas if we were to introduce the other units as you mention, we would probably need to represent these as floats or doubles rather than long.

I'm not convinced floats and doubles are not necessary IMO. The precision you're talking about for MB/GB units is not needed. When it comes to the size from the runtime information, it's usually **not** intended for monitoring and frequent calls with accurate information per second. It's intended for general/overview information and the size can be read in bytes, MB, and GB. I would expect the user code to adapt to what's needed. My personal response would be "use Azure Monitor if you need accurate metric", for general size, use runtime info and based on the scenario, use Byte, MB, or GB equivalent.

**Comment by JoshLove-msft** [comment]
> I'm not convinced floats and doubles are not necessary IMO. The precision you're talking about for MB/GB units is not needed. When it comes to the size from the runtime information, it's usually not intended for monitoring and frequent calls with accurate information per second. It's intended for general/overview information and the size can be read in bytes, MB, and GB. I would expect the user code to adapt to what's needed. My personal response would be "use Azure Monitor if you need accurate metric", for general size, use runtime info and based on the scenario, use Byte, MB, or GB equivalent.

So the service simply returns bytes. I understand your point about this not always being the desired unit, but I'm not sure I understand where the inconvenience would be with converting this to the desired units within applications. 
If there is a particular unit that is much more commonly used than bytes, I would say we go with that one and leave the others off. I do worry about truncating data though as I'm sure there is a use case out there where someone is looking for the exact amount, and it is hard to justify not including this when the REST API itself does. I can also chat about this with the PG to see if they have thoughts on this issue.

**Comment by SeanFeldman** [comment]
Bytes is the most accurate unit. Customers that have hundreds of MBs or GBs of messages don't care about that aspect.

👍 talking to the PG.

To recap - Bytes is the value the broker provides. Providing the value in MB/GB would be nice.

**Comment by JoshLove-msft** [comment]
> Bytes is the most accurate unit. Customers that have hundreds of MBs or GBs of messages don't care about that aspect.
> 
> 👍 talking to the PG.
> 
> To recap - Bytes is the value the broker provides. Providing the value in MB/GB would be nice.

We landed on leaving it in bytes as that is what the service returns, and it gives the users flexibility to translate it however they see fit.

**Comment by JoshLove-msft** [comment]
Closing as this has been merged in https://github.com/Azure/azure-sdk-for-net/pull/13590
