### ISSUE TITLE
[Azure Search]Error occurs deploying test-resources.json in China and US Gov cloud

### ISSUE THREAD

**Issue by XuGuang-Yao** [Azure/azure-sdk-for-net#13354]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

In US Gov and China, deploy resource fails with error `'apiProperties {"statisticsEnabled": false} is invalid'`.Please refer to this [pipelie ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=452585&view=results)for more details.

```
"Message": The given apiProperties {"statisticsEnabled": false} is invalid.
 
Validation errors: Property 'statisticsEnabled' has not been defined and the schema does not allow additional properties. Path 'apiProperties.statisticsEnabled'
```

After investigation, we found that neither US Gov nor China cloud support setting apiProperties in cognitive services. Below are arm templates in portal:

**China Cloud:**
> 
> ![image](https://user-images.githubusercontent.com/53599438/87111604-54b42400-c29c-11ea-9f5c-078843403738.png)

**US Gov cloud:**
>
>![image](https://user-images.githubusercontent.com/53599438/87111937-37338a00-c29d-11ea-8fa8-ca807a5f9b6b.png)

> 
**Azure Cloud:**
> 
>![image](https://user-images.githubusercontent.com/53599438/87112032-73ff8100-c29d-11ea-91d3-c08461c8241c.png)

The apiProperties has been defined in [test-resources.json](https://github.com/Azure/azure-sdk-for-net/blob/da4b7b41c29eac9d0a85980ff5bebd2bb61583ba/sdk/search/test-resources.json#L108).

**Comment by tzhanl** [comment]
@jongio @danieljurek for notification.

**Comment by danieljurek** [comment]
One way we've dealt with this kind of situation in the past is to use an ARM template parameter to define how this property is constructed. 

An example is here: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/test-resources.json#L53

The way we do this is: 
1. Define a parameter (in the example case `enableMultipleRegions`) 
2. Define possible values of an object as variables (`singleRegionConfiguration` and `multiRegionConfiguration`) 
3. Use the value of the the parameter to decide the value of the object that gets inserted into the resource (the conditions on line 53) 

... This effectively makes that configuration an `ArmTemplateParameter` which can be specified in the matrix. 

It has the effect of making our templates more flexible but we definitely trade off the ability to easily reason about what's happening in a template when we do this.

**Comment by heaths** [comment]
@tg-msft, since this is just disabling statistics (off hand, not even sure what that means since we have tests for getting statistics), think we can just remove this property?

**Comment by tg-msft** [comment]
[Apparently it's for Bing Search only](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.cognitiveservices.models.cognitiveservicesaccountapiproperties.statisticsenabled?view=azure-dotnet#Microsoft_Azure_Management_CognitiveServices_Models_CognitiveServicesAccountApiProperties_StatisticsEnabled), which we're not using.  Let's just remove it.
