### ISSUE TITLE
[Storage]Error occurs deploying test-resources.json in China and US Gov cloud

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-net#13363]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

In US Gov and China, deploy resource fails with error `Versioning is not supported for the account`.Please refer to this [pipelie ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=452419&view=results)for more details.

  `Versioning is not supported for the account`
 
After investigation, we found that neither US Gov nor China cloud support setting Versioning in storage account. Below are data protection in portal:

US Gov & China Cloud:

![image](https://user-images.githubusercontent.com/53427149/87112734-2c79f480-c29f-11ea-84be-a1f8c83786d5.png)

Azure Cloud:

![image](https://user-images.githubusercontent.com/53427149/87112755-3d2a6a80-c29f-11ea-8314-a5190299a517.png)

The Version enable setting has been defined in [test-resources.json](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/test-resources.json) at row 101.

**Comment by tzhanl** [comment]
@jongio @danieljurek for notification.

**Comment by yzheng-msft** [comment]
Versioning is a preview feature. Please see this documentation link https://docs.microsoft.com/en-us/azure/storage/blobs/versioning-overview for details on preview and how to opt-into it.

**Comment by jongio** [comment]
@v-xuto - Can you please follow up on this?

**Comment by zedy-wj** [comment]
@jongio This issue was solved, please close it.
