### ISSUE TITLE
[BUG] VM Extension information not published by 

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-net#13378]
**Describe the bug**
SDK call is not returning all expected data when calling `virtualmachine.listasync()`.

**Expected behavior**
Info about extensions is retrieved as part of the `Inner` property.

**Actual behavior (include Exception or Stack Trace)**
`Inner.Resources` only has partial data (only the extension ID, no name, type, etc).
We are now instead using the `instanceView` to get some of the desired data.

**To Reproduce**

```
using Microsoft.Azure.Management.Compute.Fluent;

var vms = (await azure.VirtualMachines.ListAsync()).ToList();
                foreach (var vm in vms)
                    {
                        var extensions = vm.Inner.Resources;
                        if (extensions.Any(e => e.VirtualMachineExtensionType != "IaaSAntimalware"))
                        {
                        }
                     }
```

**Environment:**
<PackageReference Include="Microsoft.Azure.Management.Compute.Fluent" Version="1.34.0" />

**Comment by isra-fel** [comment]
Hi @davidobrien1985 thanks for reporting! Could you share the library versions you are using?

@weidongxu-microsoft could you help on this issue? Thanks

**Comment by davidobrien1985** [comment]
@isra-fel 
We were using this
```
<PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.34.0"/>
<PackageReference Include="Microsoft.Azure.Management.Compute.Fluent" Version="1.34.0"/>
```

**Comment by weidongxu-microsoft** [comment]
@davidobrien1985

This is the current service behavior. `List` is to list all virtual machines, potentially hundreds of them. It is not economic to return every details on it. Hence the details in only returned when one get the `InstanceView` on a particular virtual machine.
