### ISSUE TITLE
[Discussion] Service Bus - Track 2 - Management client - ETag support for updating

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-sdk-for-net#13388]
_The intent of this issue is to solicit feedback from the community in advance of the GA of the next major version of the Service Bus library (which will follow several Preview releases).\
As a reference, the .NET Azure SDK guidelines can be found here: https://azure.github.io/azure-sdk/dotnet_introduction.html\
Terminology:\
Track 0 refers to the [WindowsAzure.ServiceBus library](https://www.nuget.org/packages/WindowsAzure.ServiceBus/)\
Track 1 refers to the [Microsoft.Azure.ServiceBus library](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/)\
Track 2 refers to the new library, [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/), we are working on releasing._

### Summary
In the Track 1 [ManagementClient](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Management/ManagementClient.cs), the update operations (`UpdateQueueAsync`, `UpdateTopicAsync`, `UpdateSubscriptionAsync`, `UpdateRuleAsync`) simply did a PUT request with the supplied data. This did not check against the pre-existing data for the entity. Instead, it would simply replace it with the new information blindly, and have no awareness if the entity was updated since the last time you acquired information from it.

For Track 2, we want to use [ETags for optimistic concurrency](https://sookocheff.com/post/api/optimistic-locking-in-a-rest-api/) in our update scenarios. This allows updates to those entities to only be committed when using the latest version of that entity. Meaning, if the ETag you send in your update operation matches the ETag for that entity on the server, the server will recognize the request and make the desired changes. Otherwise, the changes are rejected and an error is returned.

Using ETags matches the design for updating in ARM, Azure Resource Manager. This makes updates more consistent and disallows concurrent updates to 'squash' each other. Because of this change, we need to make changes on how updating entities works from an API perspective.

### Changes
For ETag-based updates to work, this means entities (`Queue`, `Topic`, `Subscription`, `Rule`) would need to have an ETag be provided as part of their update parameters. Instead of forcing users to handle this themselves, we would keep ETag as something private in the properties of those entities. Because of this, creation would require a different model, `Create[Entity]Options`, which does not contain an ETag. You can see information on this change here: https://github.com/Azure/azure-sdk-for-net/issues/13352

For update, we would take the model returned from a GET request in the form of `[Entity]Properties`. This model would contain the private ETag field. Thus, you would need to do a GET prior to an update. For example:
```C#
QueueProperties queue = await client.GetQueueAsync("queueName");
queue.DefaultMessageTimeToLive = TimeSpan.FromMinutes(5);
await client.UpdateQueueAsync(queue);
```

This allows for the most consistent update experience and doesn't require users of the SDK to be aware of the ETag mechanics. The primary drawback is the required GET prior to updating. But, we believe being consistent in our update mechanics across SDKs is worth it.

Additionally, `[Entity]Properties` would no longer have a publically exposed constructor. This type is only created as part of a create or get operation. In Track 1, using the entity's constructor could create an entity where some (or all) of the properties do not align with the current entity on the server. Thus, sending this entity to an update operation would cause properties, in which the developer did not intend to change, to be replaced with values in this constructed entity. In Track 2 with the hidden ETag and removing the ability to construct the entity ad-hoc, this will no longer be an issue. Since the constructor is no longer public, for testing purposes, we'll make a factory method to allow the type to be created.

**Comment by SeanFeldman** [comment]
The proposed change sounds like a good improvement to the management client.

I have the following questions:

1. When an attempt to update an entity is made with a stale ETag, I'm assuming the management client will throw an exception. What that exception/API will look like?
1. What consideration is made for the testing purposes if `[entity]Properties cannot be constructed by the user code?

**Comment by MiYanni** [comment]
@SeanFeldman Here's what we got for ya:

1. We've had a bunch of discussion internally around this already. We are verifying with the service what information would be returned when this situation happens. If the message is not sufficient to be actionable by the developer, we'd likely catch and rethrow, adding sufficient information. We'd want to make sure the developer knows why it failed and what they can do after it fails for this situation.
2. This situation is similar to what was recently added for `ServiceBusReceivedMessage`: https://github.com/Azure/azure-sdk-for-net/issues/11794. We can simply made a factory method to allow the type to be created, with the intent that the method is only for testing purposes.

**Comment by SeanFeldman** [comment]
> 1\. We've had a bunch of discussion internally around this already. We are verifying with the service what information would be returned when this situation happens. If the message is not sufficient to be actionable by the developer, we'd likely catch and rethrow, adding sufficient information. We'd want to make sure the developer knows why it failed and what they can do after it fails for this situation.

👍 

> 2\. This situation is similar to what was recently added for `ServiceBusReceivedMessage`: #11794. We can simply make a factory method to allow the type to be created, with the intent that the method is only for testing purposes.

That would be good to have in place along with the addition. May I suggest to add that to the issue description under the Changes section? Externals such as collaborators and community folks not always follow all SDK issues to know what can or cannot be done. Appreciated.

**Comment by danielmarbach** [comment]
> We've had a bunch of discussion internally around this already. We are verifying with the service what information would be returned when this situation happens. If the message is not sufficient to be actionable by the developer, we'd likely catch and rethrow, adding sufficient information. We'd want to make sure the developer knows why it failed and what they can do after it fails for this situation.

What is the model that you are planning to go for? Will it be a general-purpose exception with just the message indicating what went wrong or will the exception contain specific codes that indicate the type of failure that occurred? Will the exception also tell what has changed between the last update? Are you considering adding retry policy support first win scenarios or will that be something that the customer has to deal with?

**Comment by MiYanni** [comment]
@danielmarbach We've actually decided to not implement ETag support from this proposal. So, the information from this discussion will no longer apply. ETags only only work for Topics/Queues and do not function for Rules/Subscriptions. However, we will make the SDK so that we could add ETag support in the future as an opt-in kind of mechanism, such as a method overload, if they are implemented for Rules/Subscriptions. For Exceptions, we are sticking with the current design in Track 2 using ServiceBusException with a FailureReason.

**Comment by SeanFeldman** [comment]
@MiYanni, track 2 `ServiceBusException` didn't expose `FailureReason` as a type. This is a good addition to avoid reliance on exceptions message content.
