### ISSUE TITLE
[BUG] Uri Escaped characters when grabbing DirectoryClient.Uri

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#13391]
**Describe the bug**
When grabbing the `Uri` from a `ShareDirectoryClient` special characters remain encoded, when they should not be encoded (escaped). This also happens at `ShareDirectoryClient.Uri.ToString()` when this is supposed to give a value of unescaped characters.

This might be a regression due to our attempt to fix Uri Encoding issues elsewhere due to it not happening before Azure.Storage.Files.Shares 12.3.0-preview.1

**Expected behavior**
What is the expected behavior?
When calling `ShareDirectoryClient.Uri` the value should not be escaped. 

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
The characters are escaped

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
```
        public async Task GetSubdirectoryAsync_NonAsciiName()
        {
            await using DisposingDirectory test = await GetTestDirectoryAsync();
            ShareDirectoryClient dir = test.Directory;
            string name = "@1$2&3";

            ShareDirectoryClient subdir = InstrumentClient(dir.GetSubdirectoryClient(name));

            Assert.AreEqual(subdir.Uri.ToString(), dir.Uri.ToString() + "/" + name);
        }
```
**Environment:**
 - Name and version of the Library package used: Azure.Storage.Files.Shares 12.3.0-preview.1

**Comment by seanmcc-msft** [comment]
@amnguye, I'm not sure this is bug.

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
