### ISSUE TITLE
[BUG] StorageTransferOptions.MaximumTransferLength when MaximumTransferSize > Int32.MaxValue

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#13394]
If `StorageTransferOptions.MaximumTransferSize > Int32.MaxValue`, then `StorageTransferOptions.MaximumTransferLength` currently returns an overflow value:

```C#
var o = new StorageTransferOptions()
{
    MaximumTransferSize = Int64.MaxValue - 10
};
Console.WriteLine(o.MaximumTransferSize);   // 9223372036854775797
Console.WriteLine(o.MaximumTransferLength); // -11
```

Would it be better to instead return `Int32.MaxValue` if `MaximumTransferSize > Int32.MaxValue`?  Replace this:

https://github.com/Azure/azure-sdk-for-net/blob/4894d7525c2c30909ded889faf82152949104f5c/sdk/storage/Azure.Storage.Common/src/StorageTransferOptions.cs#L20-L24

with:

```C#
public int? MaximumTransferLength
{
    get => MaximumTransferSize > Int32.MaxValue ? Int32.MaxValue : (int?)MaximumTransferSize;
    set => MaximumTransferSize = value;
}
```

**Comment by JimSuplizio** [comment]
Hi @mikeharder, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
