### ISSUE TITLE
[FEATURE REQ] Add TableEndpoint to ICosmosDBAccount

### ISSUE THREAD

**Issue by aelij** [Azure/azure-sdk-for-net#13400]
**Library or service name.**
Microsoft.Azure.Management.CosmosDB.Fluent 
 
**Is your feature request related to a problem? Please describe.**
The above property is missing even though it appears when querying the account using az cli.

**Comment by isra-fel** [comment]
@weidongxu-microsoft  could you help @aelij ? Thanks

**Comment by weidongxu-microsoft** [comment]
new features will be in track2 SDKs https://azure.github.io/azure-sdk/releases/2020-07/dotnet.html#new-management-libraries

**Comment by jsquire** [comment]
Per comment from @weidongxu-microsoft, it appears that this is not a feature that will be added to the fluent library.  Closing out this issue; please feel free to reopen if you would like to discuss further.

**Comment by aelij** [comment]
@jsquire Then can we please keep it open to make sure it'll be in the new SDK?

**Comment by jsquire** [comment]
@allenjzhang, @weidongxu-microsoft:  Would you please be so kind as to address the request to reopen for tracking?   I don't have insight on whether this is being tracked elsewhere or whether you'd prefer to clone into a new issue that is specific to the non-fluent SDK.

**Comment by weidongxu-microsoft** [comment]
Sure, I will keep it open.

The baseline of the next-gen .NET SDK will be generated directly from cosmos spec, it should not miss anything that in the spec.

**Comment by weidongxu-microsoft** [comment]
I don't see any table endpoint in spec https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-09-01/cosmos-db.json

**Comment by weidongxu-microsoft** [comment]
@aelij 
I've involved cosmos team.

@wmengmsft, @MehaKaushik, @shurd
It appears that `tableEndpoint` property is missing in cosmos spec. Would you take a look?
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-09-01/cosmos-db.json#L5989
We see `documentEndpoint` here, but no `tableEndpoint`.

**Comment by MehaKaushik** [comment]
Hi @weidongxu-microsoft this is right, currently our service doesn't have the support for tableEndpoint. I am marking this as feature-request and we will take this up. I will update here once I have any timelines.

**Comment by weidongxu-microsoft** [comment]
New SDK at https://aka.ms/azsdk/dotnet/mgmt
