### ISSUE TITLE
[FEATURE REQ] Support convert raw permission string to XSCL defined permission object (e.g. Blob/ContainerSasPermissions)

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#13406]
**Library or service name.**

Azure.Storage.Blobs 12.5.0-preview.5
 
**Is your feature request related to a problem? Please describe.**

suggest to add a function in track2 XSCL can convert the raw permission string to Blob/ContainerSasPermissions, like “SharedAccessBlobPolicy.PermissionsFromString()” Track1.
We need this since powershell cmdlet input permission as raw permission string (change it is breaking and not allowed until major release), so we need write code to convert it to Blob/ContainerSasPermissions to make sure the permission in right order(like use “SharedAccessBlobPolicy.PermissionsFromString()” in Track1), then create SAS.
             
 If no such function now, do you have a recommended way to convert it?

**Comment by seanmcc-msft** [comment]
Should be fixed with  https://github.com/Azure/azure-sdk-for-net/pull/13433

**Comment by jsquire** [comment]
Per comment from @seanmcc-msft , this is believed to have been addressed.  Closing out the issue; please feel free to reopen if you believe further discussion is needed.
