### ISSUE TITLE
[BUG] Typo in property name on IVirtualMachineScaleSet

### ISSUE THREAD

**Issue by WhitWaldo** [Azure/azure-sdk-for-net#13410]
**Describe the bug**
There's a typo on the property name on IVirtualMachineScaleSet. It's written as "UpgradeModel" and should instead be "UpgradeMode" to reflect enum type it's describing (called UpgradeMode).

**Expected behavior**
The property should be called "UpgradeMode".

**Actual behavior (include Exception or Stack Trace)**
The property shows as "UpgradeModel".

**Environment:**
Microsoft.Azure.Management.Conpute.Fluent - 1.34.0
Windows 1010.0.19041
.NET Core SDK 3.1.301
Visual Studio Pro 16.6.3

**Comment by isra-fel** [comment]
Hi @weidongxu-microsoft  could you take a look? Thanks

**Comment by isra-fel** [comment]
P.S. The property was spelled correctly in the swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json#L9106

**Comment by weidongxu-microsoft** [comment]
We will add `UpgradeMode` property, but due to backward compatibility will only mark `UpgradeModel` as deprecated.
