### ISSUE TITLE
[BUG] DownloadTo should throw when used with an ETag

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#13414]
Consider the following track 1 code sample:

``` C#
            var accessCondition = (latestCachedData != null)
                ? AccessCondition.GenerateIfNoneMatchCondition(latestCachedData.ETag)
                : null;
            try
            {
                using (var memoryStream = new MemoryStream())
                {
                    await blobRef.DownloadToStreamAsync(
                        target: memoryStream,
                        accessCondition: accessCondition,
                        options: null,
                        operationContext: null);
                }
            }
            catch (StorageException ex) when (ex.RequestInformation.HttpStatusCode == 304)
            {
                // 304 Not Modified
                // Thrown when we already have the latest cached data.
            }
            catch (StorageException ex) when (ex.RequestInformation.HttpStatusCode == 404)
            {
                // 404 Not Found
                // Thrown when no file exists in storage.
            }

```

When ported to track 2:

``` C#

            var requestCondition = (latestCachedData != null)
                ? new BlobRequestConditions() { IfNoneMatch = latestCachedData.ETag }
                : null;

            try
            {
                using (var memoryStream = new MemoryStream())
                {
                    var response = await _blobClient.DownloadToAsync(
                        destination: memoryStream,
                        conditions: requestCondition).ConfigureAwait(false);
                }
            }
            catch (RequestFailedException ex) when (ex.Status == 304) // <- This would never get hit
            {
                // 304 Not Modified
                // Thrown when we already have the latest cached data.
            }
            catch (RequestFailedException ex) when (ex.Status == 404)
            {
                // 404 Not Found
                // Thrown when no file exists in storage.
            }

```

# Expected

`DownloadToAsync` throwing an exception when condition is not met.

# Actual

`DownloadToAsync` silently returns without downloading any data forcing a pattern where some return codes are checked using exception handler and others using the response object.

It also created a hard to debug issues because execution continues using an empty stream and the failure happens in an unrelated code that makes it not obvious what went wrong.

**Comment by tg-msft** [comment]
>  forcing a pattern where some return codes are checked using exception handler and others using the response object.

That's the pattern for all conditional responses.  3XXs have to be checked and 4XX/5XXs will throw.  [The General Guidelines say](https://azure.github.io/azure-sdk/general_design.html#conditional-requests):

> YOU SHOULD NOT throw an error when a 304 Not Modified response is received from the service, unless such errors are idiomatic to the language.

Our `Response<T>` will throw if you access `.Value` with a 3XX without checking, but we only return a raw `Response` from `DownloadTo`.  Maybe we should be more aggressive about throwing from convenience methods that a 304 prevents from being convenient.

It would be a breaking change to just throw for 304 at https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/PartitionedDownloader.cs#L121.  Maybe we can brainstorm a way to make that happen without breaking (i.e., a new optional param that defaults to `true` and an `[EditorBrowsable(Never)]` on the old API that forwards with a value of `false`)?

**Comment by pakrym** [comment]
> Maybe we can brainstorm a way to make that happen without breaking (i.e., a new optional param that defaults to true and an [EditorBrowsable(Never)] on the old API that forwards with a value of false)?

Unfortunately, I wasn't able to come up with anything good. I would wait and see if any more customers are hitting this issue.

**Comment by JimSuplizio** [comment]
Hi @pakrym, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
