### ISSUE TITLE
[QUERY] Preview DNS package

### ISSUE THREAD

**Issue by WhitWaldo** [Azure/azure-sdk-for-net#13422]
**Query/Question**
Presently, there's a preview available for [Azure.ResourceManager.Compute](https://github.com/Azure/azure-sdk-for-net/tree/Azure.ResourceManager.Compute_1.0.0-preview.1/sdk/compute) intended to be the next take on working with VM and VMSS resources. There isn't yet a new preview available for [Azure.ResourceManager.Dns](https://github.com/Azure/azure-sdk-for-net/tree/Azure.ResourceManager.Compute_1.0.0-preview.1/sdk/dns) despite being included on [this list](https://azure.github.io/azure-sdk/releases/latest/#dotnet). 

Is there any timeline on producing the DNS package?

Unfortunately, I'm in a sticky spot of having to use the new preview bits to modify VM profiles since that wasn't available in prior non-preview releases and using the older tooling to manage DNS. It's getting a little hairy having two separate takes on Azure resource management in the same package and I'd like to simplify things.

Thanks!

**Environment:**
Windows 1010.0.19041
.NET Core SDK 3.1.301
Visual Studio Pro 16.6.3

**Comment by Petermarcu** [comment]
Thanks for reporting the issue. I've added the right labels to route it to the right people.

**Comment by erich-wang** [comment]
cc @nickzhums to evaluate the timeline for Azure.ResourceManager.Dns

**Comment by nickzhums** [comment]
@WhitWaldo Hi Whit, thanks for submitting the request. We will discuss this internally and let you know

**Comment by nickzhums** [comment]
@WhitWaldo we decided to add DNS to our next wave of package list, which is probably going to be public previewed in Sep/Oct timeframe.

**Comment by SaurabhSharma-MSFT** [comment]
@WhitWaldo Following up again to know if we can close this issue.

**Comment by nickzhums** [comment]
FYI package is here: https://www.nuget.org/packages/Azure.ResourceManager.Dns/1.0.0-preview.1

**Comment by WhitWaldo** [comment]
I'm looking forward to circling back to implementing this. Yes, this can be closed. Thank you!
