### ISSUE TITLE
[BUG] SQL extendedAuditingSettings not available 

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-net#13438]
**Describe the bug**
Unable to query a SQL server's `extendedAuditingSettings` to get info about this state here:
![image](https://user-images.githubusercontent.com/8554521/87387099-57d54a00-c5e5-11ea-907f-4a64271884b2.png)

**Expected behavior**
Via PowerShell I can do `Get-AzSqlServerAudit -resourcegroupname <> -servername <> -debug` and that shows me that it's querying `/subscriptions/{subscriptionId}/providers/Microsoft.Sql/servers/{serverName}/extendedAuditingSettings/default?api-version=2019-06-01`.

**Actual behavior (include Exception or Stack Trace)**
I can't find the `extendedAuditingSettings` anywhere in the documentation.

**Comment by erich-wang** [comment]
Could Sql team take a look whether the requested API exists in swagger api?
