### ISSUE TITLE
KeyVault Create Key API Fails on keyType "octet sequence"

### ISSUE THREAD

**Issue by adescre** [Azure/azure-sdk-for-net#13437]
**Describe the bug**
This code:
```csharp
KeyClient client = new KeyClient(new Uri("https://vaultname.vault.azure.net/"), new DefaultAzureCredential());
client.CreateKey("aestestkey", KeyType.Oct);
```

Fails with a 400, and the following payload:
```json
{
    "error": {
        "code": "BadParameter",
        "message": "Invalid kty value: oct",
        "innererror": {
            "code": "KeyTypeNotSupported"
        }
    }
}
```

Since `KeyType.Oct` is an enum, the value should be supported.

**Expected behavior**
The call should return a successful response with a KeyVaultKey object.
The value is also document on the [REST API documentation](https://docs.microsoft.com/en-us/rest/api/keyvault/createkey/createkey#jsonwebkeytype)

**Actual behavior (include Exception or Stack Trace)**
Request:
```
POST https://vaultname.vault.azure.net/keys/aestestkey/create?api-version=7.0 HTTP/1.1
Host: vaultname.vault.azure.net
Accept: application/json
Authorization: Bearer <token>
Content-Type: application/json
Content-Length: 13

{"kty":"oct"}
```

Response:
```
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 112
Content-Type: application/json; charset=utf-8

{"error":{"code":"BadParameter","message":"Invalid kty value: oct","innererror":{"code":"KeyTypeNotSupported"}}}
```

**To Reproduce**
See the code snippet above.

**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Keys 4.0.4
 - Hosting platform or OS and .NET runtime version: 
> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.301
>  Commit:    7feb845744
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.20166
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.301\
> 
> Host (useful for support):
>   Version: 3.1.5
>   Commit:  65cd789777
> 
> .NET Core SDKs installed:
>   3.1.301 [C:\Program Files\dotnet\sdk]

 - IDE and version : Visual Studio 16.6.3

**Comment by heaths** [comment]
This does appear to be [declared](https://docs.microsoft.com/rest/api/keyvault/createkey/createkey#jsonwebkeytype) - and, thus, supported by the SDK - earlier than intended to be supported. We cannot remove it (breaking change) and it will be supported eventually with a new preview of the service. We will discuss what to do in the meantime.

**Comment by adescre** [comment]
Thanks for the update @heaths. Any ETA you can provide?

**Comment by heaths** [comment]
No ETA. It's not supported right now, and anything we might do would only be a documentation change.

**Comment by sirimantraore** [comment]
I have the same error on the sdk java. Have you a fix for this error please ?

**Comment by heaths** [comment]
Managed HSM has been announced, which supports both "oct" and "oct-hsm". We are working on preview versions of the SDK to use both of these, and the same APIs for Key Vault can be used for Managed HSM. Please try https://www.nuget.org/packages/Azure.Security.KeyVault.Keys/4.2.0-beta.1 or newer against [Managed HSM](https://azure.microsoft.com/services/azure-dedicated-hsm) and file any new issues you find with the new SDK.
