### ISSUE TITLE
Avoid reparsing Json when integrating JsonObjectSerializer with generated layer

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#13440]
The code generator doesn't support serializing any old `object` to Json. In order to build this support into the Event Grid SDK, we needed to wrap our payload in an internal class that implements `IUtf8JsonSerializable`. In our `Write` method we end up needing to serialize object to Json stream, and then parse back to JsonDocument. Ideally, we could avoid doing this duplicate work. Also, we should look into whether it is possible to move this [type](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/EventGridSerializer.cs) into shared source that can be used by other libraries.
```c#
public void Write(Utf8JsonWriter writer)
        {
            var stream = new MemoryStream();
            _serializer.Serialize(stream, _customEvent, _customEvent.GetType(), _cancellationToken);
            stream.Seek(0, SeekOrigin.Begin);
            JsonDocument.Parse(stream).WriteTo(writer);
        }
```

**Comment by pakrym** [comment]
.NET 6 WriteRawValue would help here.
