### ISSUE TITLE
Implement ToString

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#13448]
Implement ToString in the TA library as an exercise of [ToString guidelines](https://github.com/Azure/azure-sdk-for-net/issues/12831).

**Comment by maririos** [comment]
1st draft proposal https://github.com/Azure/azure-sdk-for-net/pull/15708

**Comment by pallavit** [comment]
@joseharriaga I believe this can be closed given TA is transitioning anyway. Please reopen if you think otherwise.
