### ISSUE TITLE
[BUG] Run BlockBlobClient.QueryAsync() on a big csv file, then write the output stream to a file fail.

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#13441]
**Describe the bug**
Run BlockBlobClient.QueryAsync() on a big csv file (~230MB), then write the output stream to a file fail with  "Destination array was not long enough. Check the destination index, length, and the array's lower bounds."

And it seems the “ProgressHandler” won’t be called until the request finish, and start to read from output stream. I expect it will be invoke on download the result from server. Any comments?

**Expected behavior**
write the stream to a local file should success.

**Actual behavior (include Exception or Stack Trace)**
Failed with
```
System.ArgumentException: Destination array was not long enough. Check the destination index, length, and the array's lower bounds.
Parameter name: destinationArray
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at Azure.Storage.Blobs.BlobQuickQueryStream.ReadInternal(Boolean async, Byte[] buffer, Int32 offset, Int32 count)
   at Azure.Storage.Blobs.BlobQuickQueryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)
   at testTracking.Program.Main(String[] args) in C:\Users\weiwei\source\repos\testTracking\testTracking\Program.cs:line 74
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Following is my repro program, I will share my test csv file Uri by mail.
The failure is on line `reader.CopyTo(fs); `

```
           string bloburi = "https://xxx.blob.core.windows.net/weiqatest/testcsv.csv?sv=2019-12-12&se=2020-12-29T16%3A00%3A00Z&sr=b&sp=r&sig=xxx";
           BlockBlobClient blob = new BlockBlobClient(new Uri(bloburi), new BlobClientOptions());
            
            // prepare query Option
            IProgress<long> progressHandler = new Progress<long>((finishedBytes) =>
            {
                Console.WriteLine(finishedBytes);
            });
            BlobQueryOptions queryOption = new BlobQueryOptions
            {
                InputTextConfiguration = new BlobQueryCsvTextConfiguration() { HasHeaders = true },
                OutputTextConfiguration = new BlobQueryCsvTextConfiguration() { HasHeaders = true },
                ProgressHandler = progressHandler
            };

            string query = "SELECT * FROM BlobStorage WHERE _1 LIKE '1%%'";
            Task<Response<BlobDownloadInfo>>  task =blob.QueryAsync(query, queryOption);
            task.Wait();

            var reader = task.Result.Value.Content;
            FileStream fs = File.Create(@"C:\temp\QA_result.csv");
            reader.CopyTo(fs); 
            fs.Close();
           reader.Close();

```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.4.0] 
Azure.Storage.Blobs/12.5.0-preview.5
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by seanmcc-msft** [comment]
@blueww, unfortunately I am not able to repo.

```
using Azure;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;
using System;
using System.IO;
using System.Threading.Tasks;

namespace ConsoleApp16
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string bloburi = " https://xxx.blob.core.windows.net/weiqatest/testcsv.csv?sv=2019-12-12&se=2020-12-29T16%3A00%3A00Z&sr=b&sp=r&sig=yyy";
            BlockBlobClient blob = new BlockBlobClient(new Uri(bloburi), new BlobClientOptions());

            // prepare query Option
            IProgress<long> progressHandler = new Progress<long>((finishedBytes) =>
            {
                Console.WriteLine(finishedBytes);
            });
            BlobQueryOptions queryOption = new BlobQueryOptions
            {
                InputTextConfiguration = new BlobQueryCsvTextConfiguration() { HasHeaders = true },
                OutputTextConfiguration = new BlobQueryCsvTextConfiguration() { HasHeaders = true },
                ProgressHandler = progressHandler
            };

            string query = "SELECT * FROM BlobStorage WHERE _1 LIKE '1%%'";

            Response<BlobDownloadInfo> response = await blob.QueryAsync(query, queryOption);

            var reader = response.Value.Content;
            FileStream fs = File.Create(@"C:\temp\QA_result.csv");
            reader.CopyTo(fs);
            fs.Close();
            reader.Close();
        }
    }
}

```

**Comment by seanmcc-msft** [comment]
> And it seems the “ProgressHandler” won’t be called until the request finish, and start to read from output stream. I expect it will be invoke on download the result from server. Any comments?

This is by design.  The ProgressHandler is used to report progress events in the data stream.

**Comment by blueww** [comment]
@seankane-msft 
Thanks for the explain!

For ProgressHandler, it's used to show progress to customer. So we might should use it on the item which will use most time.
In Query(), per my test, normally the time mostly be used on network request than write to local disk, so can we use ProgressHandler for progress of the network request instead of disk write, so customer can get the really progress of whole Query process. Or the customer will see the progress keeps 0% for a long time, then go to 100% very quickly. 

Is there anything blocks we use the network request progress in ProgressHandler?  As I see, in other API like BlobClient.Upload(), the ProgressHandlerwork can show the correct progress.

**Comment by seanmcc-msft** [comment]
The functionality of ProgressHandler is different for Query by design.  This was specifically specified by the Quick Query backend team.

**Comment by blueww** [comment]
@seanmcc-msft 
Thanks for the quick fix!
For the progress handler, as it can't show the real progress of the query, I will not use it to show the progress bar in PSH, to avoid misleading user.
