### ISSUE TITLE
Onboard Schema Registry service

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#13471]
Schema Registry is a new service that is currently in private preview.
This issue is to track work to onboard the SDK for this service.
This work is planned for the August milestone and does not involve shipping the package which will be done in the September milestone.

- decide package name
- auto generate the package using the latest code generator on the [swagger](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/schemaregistry/azure-data-schemaregistry/swagger/swagger.json) 
- set up CI 

For reference, please see the [Java SDK for Schema Registry](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/schemaregistry/azure-data-schemaregistry)

**Comment by jsquire** [comment]
@AlexGhiondea:  Would you be so kind as to help route?  I'm not sure if the final decision was to treat this as part of Core or consider it a separate service offering.

**Comment by ramya-rao-a** [comment]
Please wait until the swagger makes it to the https://github.com/Azure/azure-rest-api-specs/ repo. I'll post an update here when it does

**Comment by MiYanni** [comment]
Missing descriptions for these properties:
![image](https://user-images.githubusercontent.com/17788297/88238761-65b74a80-cc37-11ea-8240-2fb707f92727.png)

**Comment by MiYanni** [comment]
Created WIP PR for this SDK. It is building, but no client surface is fleshed out. https://github.com/Azure/azure-sdk-for-net/pull/13657

**Comment by ramya-rao-a** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/10220 is the link to the PR adding the swagger to the rest-api-specs repo. Please update the WIP PR to see if there are any issues

**Comment by MiYanni** [comment]
Initial generation and investigation complete. After discussion with Pavel, package(s) and names will be figured out after we have initial implementation complete.
