### ISSUE TITLE
Add support for sync HttpWebRequest-based transport on .NET Framework

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#13477]

**Comment by weshaggard** [comment]
Can I ask what prompted this issue? Are we hitting issues with our normal HttpClient code paths?

**Comment by pakrym** [comment]
We were planning to add support for fully sync pipeline for a long time. Sync HttpClient is coming in 5.0 preview 8 and for .NET Framework it can be achieved using HttpWebRequest, in addition it avoids the overhead of wrapping HttpWebRequest into HttpClient.
