### ISSUE TITLE
[BUG] Request sent from OperationalInsightsDataClient doesn't have header

### ISSUE THREAD

**Issue by VeryEarly** [Azure/azure-sdk-for-net#13472]
**Describe the bug**
Request sent from OperationalInsightsDataClient doesn't have header.

**Expected behavior**
What is the expected behavior?

OperationalInsightsDataClient.preferences.Wait should be in the header if passed in.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

Empty header in request

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Using Azure-Powershell which referenced Microsoft.Azure.OperationalInsights-0.10.0-preview
1. `$workspace = Get-AzOperationalInsightsWorkspace -ResourceGroupName $rgname -Name $name`
2. `Invoke-AzOperationalInsightsQuery -WorkspaceId $workspace.CustomerId -Query $query -Wait 10 -debug`

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.OperationalInsights-0.10.0-preview
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by geneh** [comment]
The prefer header is actually sent when -Wait flag is passed in as described above. It has been verified in the service logs:
`Request.preferHeader`: `response-v1=true,wait=10`

For some reason when running with the debug flag the header is not printed in the console, which is confusing:
```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://api.loganalytics.io/v1/workspaces/<redacted>/query

Headers:

Body:
{
  "query": "union * | limit 1"
}


DEBUG: ============================ HTTP RESPONSE ============================
```
