### ISSUE TITLE
[QUERY] How to add library to a DatabricksNotebookActivity Class in DataFactory?

### ISSUE THREAD

**Issue by brandonwatts** [Azure/azure-sdk-for-net#13480]
**Query/Question**
I am trying to add a library to my Databricks Notebook in Data Factory using the C# SDK and the [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.databricksnotebookactivity.libraries?view=azure-dotnet#Microsoft_Azure_Management_DataFactory_Models_DatabricksNotebookActivity_Libraries) say that the field is of type ```IList<IDictionary<String,Object>>``` but when I try to use this in my code the library types are being created but the package and coordinated are empty in the deployed data factory. Is my object not correct? I am just not sure the best way to use the library property on the DatabricksNotebookActivity and couldn't find sample code anywhere. This is currently how I am doing it:

```
new DatabricksNotebookActivity(
                "<name>",
                "<notebook path>",
                linkedServiceName: "<databricks linked service name>" ,
                dependsOn: <previous activity>,
                libraries: new List<IDictionary<string, object>>
                {
                    new Dictionary<string, object>
                    {
                        {"pypi", new {package = "azure-cosmos"}}
                    },
                    new Dictionary<string, object>
                    {
                        {"maven", new {coordinates = "com.microsoft.azure:azure-cosmosdb-spark_2.4.0_2.11:2.0.3"}}
                    }
                }
            );
```
Here is what it looks like in the deployed data factory:
![Screen Shot 2020-07-15 at 2 24 53 PM](https://user-images.githubusercontent.com/9054331/87581634-43598600-c6a7-11ea-937d-d09a42d4a056.png)

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.DataFactory 4.5.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 

.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.101/

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  3.1.101 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

 - IDE and version : Jetbrains Rider 2020.1.3

**Comment by erich-wang** [comment]
Could data bricks team take a look?

**Comment by brandonwatts** [comment]
Any update on this?

**Comment by brandonwatts** [comment]
Just closing the loop this was solved by a member of my team. The solution is to explicitly wrap the value in a Dictionary. 

```C#
new DatabricksNotebookActivity(
                "<name>",
                "<notebook path>",
                linkedServiceName: "<databricks linked service name>" ,
                dependsOn: <previous activity>,
                libraries: new List<IDictionary<string, object>>
                {
                    new Dictionary<string, object>
                    {
                        {"pypi", new Dictionary<string,object> {{"package", "azure-cosmos" } } }
                    },
                    new Dictionary<string, object>
                    {
                        {"maven", new Dictionary<string,object> {{ "coordinates", "com.microsoft.azure:azure-cosmosdb-spark_2.4.0_2.11:2.0.3" } } }
                    },
                }
            );
```
