### ISSUE TITLE
Update AppAuthentication Package to point people to Azure.Identity

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#13491]
Tracking 

**Problem**
It's not clear to customers searching nuget.org for Azure Identity if they should use AppAuthentication or Azure.Identity

**Details**
https://twitter.com/mderriey/status/1281708180225921024?s=20
> It seems that Azure.Identity and Microsoft​.Azure​​.Services.AppAuthentication serve the same purpose, and are both actively worked on.
> 
> Is there guidance as to which one should be used going forward? #azure #dotnetcore 
> 

The AppAuthentication nuget package points to https://docs.microsoft.com/en-us/azure/key-vault/general/service-to-service-authentication, which gives customers a warning

![image](https://user-images.githubusercontent.com/1302850/87620047-6baaaa00-c6d2-11ea-96a2-ce06a95633bd.png)

Which points here: https://docs.microsoft.com/en-us/azure/key-vault/general/authentication

Which has Azure.Identity mentioned at the bottom of the page.  

If customers read all of this, then they can end up correctly using Azure.Identity.  But many people won't follow this rabbit hole all the way down.

**Proposal**

Mark AppAuthentication deprecated and update the .nuspec file to include a new description which links directly to the Azure.Identity nuget package.

**Comment by schaabs** [comment]
We are moving out marking the AppAuthentication deprecated this until we have ARM libraries which support authenticating with Azure.Identity.

**Comment by pallavit** [comment]
Given AppAuthentication package has been deprecated can this be closed? @scottaddie , @schaabs
