### ISSUE TITLE
[FEATURE REQ] Add ResourceId to Azure.ResourceManager.Resources

### ISSUE THREAD

**Issue by aelij** [Azure/azure-sdk-for-net#13496]
**Library or service name.**
Azure.ResourceManager.Resources/1.0.0-preview.1
 
**Is your feature request related to a problem? Please describe.**
The previous SDK has a `ResourceId` class which can be used to parse hierarchical ARM IDs. There's no equivalent to this in the new SDK, and even though it may not be needed with the new client API, it's very convenient to have.

**Comment by erich-wang** [comment]
This is feature request, cc @allenjzhang to take a look.

**Comment by allenjzhang** [comment]
Thank you for the feedback. We are looking into supporting this.

**Comment by aelij** [comment]
Now available as `ResourceIdentifier`
