### ISSUE TITLE
Azure.Search.Documents Readme issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#13502]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/search/Azure.Search.Documents#use-searchdocument-like-a-dictionary-for-search-results)
![image](https://user-images.githubusercontent.com/65581162/87650560-6a39ba00-c784-11ea-8944-f58d4e679bb7.png)

Reason:
System.Collection.Generic.KeyNotFoundException: 
Could not find a member called 'hotelId' and 'hotelName' in the document.

Suggestion:
Update to:
```
string id = (string)doc["HotelId"];
string name = (string)doc["HotelName"];
```

**Comment by Tianyun-G** [comment]
@jongio for notification.

**Comment by tg-msft** [comment]
We need to switch to using the official data set.  Assigning to myself.

**Comment by heaths** [comment]
@tg-msft seems the sample method doesn't actually run, which is probably how this was missed:
```csharp
#if EXPERIMENTAL_DYNAMIC
        [Test]
#endif
        [SyncOnly]
        public async Task CreateAndQuery()
        {
            // ...

            #region Snippet:Azure_Search_Tests_Samples_Readme_Dict
            SearchResults<SearchDocument> response = client.Search<SearchDocument>("luxury");
            foreach (SearchResult<SearchDocument> result in response.GetResults())
            {
                SearchDocument doc = result.Document;
                string id = (string)doc["hotelId"];
                string name = (string)doc["hotelName"];
                Console.WriteLine("{id}: {name}");
            }
            #endregion Snippet:Azure_Search_Tests_Samples_Readme_Dict

            // ...
        }
```

**Comment by heaths** [comment]
@Tianyun-G are you using the official hotels example which uses PascalCase for fields? Our tests use our own set that use camelCase currently.

**Comment by tg-msft** [comment]
The test wouldn't have caught this.  They're using the public data set which has PascalCased field names.

**Comment by Tianyun-G** [comment]
@heaths - Yes, I do use the [official hotels](https://docs.microsoft.com/en-us/azure/search/search-create-service-portal) which's fields are named as PascalCase. This is why the code throw the System.Collection.Generic.KeyNotFoundException.

**Comment by tg-msft** [comment]
I fixed the text in the README, but I'm leaving this open to properly fix so we're actually running against the same data as a new search index created with the portal.

**Comment by jongio** [comment]
@tg-msft  - We are looking to close out old manual test pass issues.  Is this something we can close now or can we create a PR so we can close it?

**Comment by Tianyun-G** [comment]
@jsquire , @tg-msft Can you see if we can close this one as well?

**Comment by heaths** [comment]
@tg-msft wasn't this one already fixed by this?
https://github.com/Azure/azure-sdk-for-net/blob/1db9bf16f1cce271ea2b2a4b6fb0d3e8df1d753f/sdk/search/Azure.Search.Documents/tests/Samples/Readme.cs#L83-L89

**Comment by tg-msft** [comment]
We patched it with that snippet hack, but we should still fix the root of the issue by switching to the official data set that customers get in the Portal.  We're going to keep having problems/subtle differences until we do, so I think the bug should stay open.

**Comment by AlexGhiondea** [comment]
@tg-msft @Mohit-Chakraborty is this still an issue? What would it take to move to the official data set?

**Comment by tg-msft** [comment]
Yes, unfortunately.  To fix this correctly we'd want to snag the official dataset and pull it into an index (either manually or by setting up an indexer).

**Comment by jongio** [comment]
@tg-msft - Do we have a different issue to track moving to the official dataset?  Is that something you want to do yourself or something we can help with?

**Comment by tg-msft** [comment]
This is the issue tracking it at this point.  We can rename if required.   I think it's going to take a little creativity to make this work, but it hasn't been a high enough priority yet.

**Comment by v-xuto** [comment]
@tg-msft How is the current progress of this issue? Has it been fixed?

**Comment by v-xuto** [comment]
@tg-msft How is the current progress of this issue? Has it been fixed?

**Comment by pallavit** [comment]
@ShivangiReja can we please follow-up here?

**Comment by ShivangiReja** [comment]
@pallavit we still have the snippet [hack](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/tests/Samples/Readme.cs#L84-L90) as we use camel casing for field names in the SDK and public data set uses [PascalCasing](https://github.com/Azure-Samples/azure-search-sample-data/blob/master/hotels/Hotels_IndexDefinition.JSON). We need to fix the root of the issue by switching to the official data set that customers get in the [Portal](https://learn.microsoft.com/en-us/azure/search/search-get-started-portal#create-index).
