### ISSUE TITLE
Service Bus Readme issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#13503]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Azure.Messaging.ServiceBus#using-the-processor):
![image](https://user-images.githubusercontent.com/65581162/87649594-137fb080-c783-11ea-8a8a-f2bc1431ac9b.png)

Reason:
'ProcessMessageEventArgs' does not contain a definition for 'CompleteMessageAsync'.

Suggestion: 
Update `CompleteMessageAsync`  to `CompleteAsync`.

**Comment by Tianyun-G** [comment]
@jongio for notification.

**Comment by JoshLove-msft** [comment]
ProcessMessageEventArgs does have a CompleteMessageAsync parameter - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessMessageEventArgs.cs#L67

**Comment by MiYanni** [comment]
@Tianyun-G The method was changed from `CompleteAsync` to `CompleteMessageAsync` in the latest preview package, 7.0.0-preview.4. The docs here represent the latest changes in the currently released preview package.
https://www.nuget.org/packages/Azure.Messaging.ServiceBus/

The information about this change is listed in our changelog for preview.4: https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.0.0-preview.4/sdk/servicebus/Azure.Messaging.ServiceBus/CHANGELOG.md#breaking-changes

**Comment by Tianyun-G** [comment]
@MiYanni - Yes, the method has been changed to `CompleteMessageAsync`  in 7.0.0-preview.4. But I am testing the readme file against dev packages which are stored in https://azuresdkartifacts.blob.core.windows.net/azure-sdk-for-net/index.json. It seems that the dev package hasn't been updated to the newest one yet. The latest dev package is 7.0.0-dev.20200624.1 and method in this version is still called `CompleteAsync`.

**Comment by MiYanni** [comment]
@Tianyun-G After some investigation, this is related to the engineering system. It seems every package feed in that container stopped as of June 24th (I checked 3 different SDKs). I'll assign it to them and they should be able to fix the feeds.

**Comment by jsquire** [comment]
//cc: @weshaggard

**Comment by weshaggard** [comment]
We are no longer using that dev feed we have updated it to use an Azure DevOps feed see the updated instructions at https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md#dev-feed.

**Comment by Tianyun-G** [comment]
Close as it is no problem in latest version.
