### ISSUE TITLE
[FEATURE REQ] Add a CheckNameAvailability feature for Failover Group 

### ISSUE THREAD

**Issue by rfabro** [Azure/azure-sdk-for-net#13518]
**Library or service name.**
Microsoft.Azure.Management.Sql.Fluent
 
**Is your feature request related to a problem? Please describe.**
The Azure SDK and Azure REST api does not have a feature that checks the name of a failovergroup if it is already taken, and it should have since failovergroup names are globally unique.

**Comment by jsquire** [comment]
Since this was filed, the `Microsoft.Azure.Management.Sql.Fluent` library has been deprecated and is currently only receiving critical security fixes.   Closing this out.
