### ISSUE TITLE
Update generator version in all projects

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#13511]
# Data-plane

- [x] `digitaltwins/Azure.DigitalTwins.Core/src/Azure.DigitalTwins.Core.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13517
- [x] `eventgrid/Azure.Messaging.EventGrid/src/Azure.Messaging.EventGrid.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13528
- [x] `formrecognizer/Azure.AI.FormRecognizer/src/Azure.AI.FormRecognizer.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13551
- [x] `iot/Azure.Iot.Hub.Service/src/Azure.Iot.Hub.Service.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13558
- [x] `keyvault/Azure.Security.KeyVault.Administration/src/Azure.Security.KeyVault.Administration.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13522
- [x] `search/Azure.Search.Documents/src/Azure.Search.Documents.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13530
- [x] `synapse/Azure.Analytics.Synapse.AccessControl/src/Azure.Analytics.Synapse.AccessControl.csproj`- https://github.com/Azure/azure-sdk-for-net/pull/13516
- [x] `synapse/Azure.Analytics.Synapse.Artifacts/src/Azure.Analytics.Synapse.Artifacts.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13516
- [x] `synapse/Azure.Analytics.Synapse.Spark/src/Azure.Analytics.Synapse.Spark.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13516
- [x] `tables/Azure.Data.Tables/src/Azure.Data.Tables.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13513

# Management-plane

- [x] `appconfiguration/Azure.ResourceManager.AppConfiguration/src/Azure.ResourceManager.AppConfiguration.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13525
- [x] `compute/Azure.ResourceManager.Compute/src/Azure.ResourceManager.Compute.csproj` -https://github.com/Azure/azure-sdk-for-net/pull/13525
- [x] `digitaltwins/Azure.ResourceManager.DigitalTwins/src/Azure.ResourceManager.DigitalTwins.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13517
- [x] `eventhub/Azure.ResourceManager.EventHubs/src/Azure.ResourceManager.EventHubs.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13585
- [x] `keyvault/Azure.ResourceManager.KeyVault/src/Azure.ResourceManager.KeyVault.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13522
- [x] `network/Azure.ResourceManager.Network/src/Azure.ResourceManager.Network.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13584
- [x] `resources/Azure.ResourceManager.Resources/src/Azure.ResourceManager.Resources.csproj` -https://github.com/Azure/azure-sdk-for-net/pull/13580
- [x] `storage/Azure.ResourceManager.Storage/src/Azure.ResourceManager.Storage.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13582
- [x] `testcommon/Azure.Graph.Rbac/src/Azure.Graph.Rbac.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13525
- [x] `testcommon/Azure.Management.Compute.2019_12/src/Azure.Management.Compute.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13525
- [x] `testcommon/Azure.Management.Network.2020_04/src/Azure.Management.Network.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13525
- [x] `testcommon/Azure.Management.Resources.2017_05/src/Azure.Management.Resources.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13525
- [x] `testcommon/Azure.Management.Storage.2019_06/src/Azure.Management.Storage.csproj` - https://github.com/Azure/azure-sdk-for-net/pull/13525

Do https://github.com/Azure/azure-sdk-for-net/issues/13506 afterwards.

**Comment by jsquire** [comment]
Closing this out, as all child items are checked and the related issue is closed.
