### ISSUE TITLE
[BUG] Recording framework isn't correctly recording Content-Length of Head response

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#13510]
In [this test](https://github.com/Azure/azure-sdk-for-net/pull/12400/files?file-filters%5B%5D=.cs#diff-7f7fefef0eb98fcf1b3e66bc27fd93faR1075), the 2nd to last call is GetProperties().  Its response is supposed to contain the header "Content-Length=1024" (this is what happens in live mode).  Unfortunately, it is being [recorded as 0](https://github.com/Azure/azure-sdk-for-net/pull/12400/files?file-filters%5B%5D=.json#diff-1c90591f6e2c53c82c658a767548af18).  (Line 2292, GitHub won't load the link I tried to create to that specific line.)

I believe this is because the response doesn't have a body, and the recording framework is setting Content-Length = 0 base on the body length, ignoring the actual header.

**Comment by JoshLove-msft** [comment]
I just tested this locally and the recording didn't include the HEAD request with the Content-Length of 0. Playback worked fine after re-recording. Is it possible there was a server issue? Can you try to re-record?

**Comment by seanmcc-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/13917

**Comment by kasobol-msft** [comment]
I'm still hitting this issue.

What I can see during recording:
![image](https://user-images.githubusercontent.com/61715331/92156169-71249680-eddd-11ea-8bee-a2cfe5793eb7.png)

What recording has:
![image](https://user-images.githubusercontent.com/61715331/92156247-8e596500-eddd-11ea-90c9-b46aff50d14c.png)

**Comment by JoshLove-msft** [comment]
@kasobol-msft can you point me to the specific test?

**Comment by kasobol-msft** [comment]
@JoshLove-msft https://github.com/Azure/azure-sdk-for-net/blob/69cf78fe042c0beb578e0fa43e12e5877536a640/sdk/storage/Azure.Storage.Blobs/tests/BlobBaseClientTests.cs#L927-L947 that one or any other with this issue link in the comment.
