### ISSUE TITLE
[BUG] Getting TlsVersionNotPermitted when trying to batch delete files in Azure Blob Storage using Azure.Storage.Blobs.Batch

### ISSUE THREAD

**Issue by sunero4** [Azure/azure-sdk-for-net#13524]
**Describe the bug**
When using the latest version of the NuGet package Azure.Storage.Blob.Batch (version 12.2.1), when trying to perform a batch delete of files in a blob storage container, the call throws an exception with error code "TlsVersionNotPermitted". This error code is not documented here: https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes
The error is consistent across the storage accounts on both our staging and production environments at work, and the error also persists both when trying to perform the delete from a local developer machine and from the SF cluster where our application runs. 
However, when I tried running my minimal example, the batch delete actually worked the first time around, with Minimum TLS Version = 1.0 set in the storage account properties. However, if I switch to 1.2 it does not work, and even if I switch back to 1.0 it still does not work, so I do not believe none of the computers I have tried this on are capable of TLS 1.2. I have also tried doing this: https://stackoverflow.com/a/45383835/7230001 , but that makes no difference.

**Expected behavior**
The batch delete should delete the files with the requested names.

**Actual behavior (include Exception or Stack Trace)**
I made a minimal example to reproduce the error. Example code is shown further below. This is the exception thrown:
```
3 batch operation(s) failed. (The TLS version of the connection is not permitted on this storage account.
RequestId:8fc4254d-101e-000b-67ad-5b3b1f1e6e38
Time:2020-07-16T20:12:21.7804602Z
Status: 400 (The TLS version of the connection is not permitted on this storage account.)
ErrorCode: TlsVersionNotPermitted

Headers:
x-ms-error-code: TlsVersionNotPermitted
x-ms-request-id: 8fc4254d-101e-000b-67ad-5b3b1f1e6e38
x-ms-version: 2019-07-07
x-ms-client-request-id: 88594368-699e-496f-a36a-e07597298b48
Content-Length: 267
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0
) (The TLS version of the connection is not permitted on this storage account.
RequestId:8fc4254d-101e-000b-67ad-5b3b1f1e6e39
Time:2020-07-16T20:12:21.7804602Z
Status: 400 (The TLS version of the connection is not permitted on this storage account.)
ErrorCode: TlsVersionNotPermitted

Headers:
x-ms-error-code: TlsVersionNotPermitted
x-ms-request-id: 8fc4254d-101e-000b-67ad-5b3b1f1e6e39
x-ms-version: 2019-07-07
x-ms-client-request-id: bfb09b14-f359-446d-bbfd-149e47222662
Content-Length: 267
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0
) (The TLS version of the connection is not permitted on this storage account.
RequestId:8fc4254d-101e-000b-67ad-5b3b1f1e6e3a
Time:2020-07-16T20:12:21.7804602Z
Status: 400 (The TLS version of the connection is not permitted on this storage account.)
ErrorCode: TlsVersionNotPermitted

Headers:
x-ms-error-code: TlsVersionNotPermitted
x-ms-request-id: 8fc4254d-101e-000b-67ad-5b3b1f1e6e3a
x-ms-version: 2019-07-07
x-ms-client-request-id: 1c3052aa-1f5f-4663-af05-713582c8a5d2
Content-Length: 267
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0
)
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a storage account. 
2. Create a container in the storage account and upload any number of files to it.
3. Run code like the following example:
```
    class Program
    {
        static async Task Main(string[] args)
        {
            var containerName = "your_container_name";            
            var connectionString = "your_connection_string";

            var blobServiceClient = new BlobServiceClient(connectionString);
            var blobContainerClient = blobServiceClient.GetBlobContainerClient(containerName);

            var batchClient = blobServiceClient.GetBlobBatchClient();

            var fileNames = new[] { "filename1", "filename2", "filename3" };

            var uris = fileNames.Select(f => blobContainerClient.GetBlockBlobClient(f).Uri);

            await batchClient.DeleteBlobsAsync(uris);
        }
    }
```
4. If the batch delete actually succeeds the first time around, try switching the minimum tls version of the storage account and it should break for good.

**Environment:**
- Name and version of the library package: 
1. Azure.Storage.Blobs 12.4.4
2. Azure.Storage.Blobs.Batch 12.2.1

 - Hosting platform or OS and .NET runtime version (output from dotnet --info):
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777

 - IDE and version:
Visual Studio 2019, 16.6.3

**Comment by amishra-dev** [comment]
We acknowledge that this is a bug on the service, we are working on fixing it. There are 2 workarounds available 
1. Use Http for now while we fix the bug
2. Fire off the request one at a time while we fix the bug.

We do apologize for the inconvenience and will update here when the fix is rolled out on the service.

**Comment by amishra-dev** [comment]
@sunero4 can you send me your account name so that i can keep track?

**Comment by sunero4** [comment]
> @sunero4 can you send me your account name so that i can keep track?

Which account name are you thinking of? My Azure Account? :)

**Comment by amishra-dev** [comment]
> > @sunero4 can you send me your account name so that i can keep track?
> 
> Which account name are you thinking of? My Azure Account? :)

@sunero4 i meant the storage account name :) If you can send me that, i can keep track of when the fix reaches that storage stamp and let you know that you could try again. Thanks

**Comment by sunero4** [comment]
> @sunero4 i meant the storage account name :) If you can send me that, i can keep track of when the fix reaches that storage stamp and let you know that you could try again. Thanks

Oh, I created a storage account to go with the minimal example so I just deleted it after I was finished with testing this. But I'll stay subscribed to this issue :)

**Comment by neistow** [comment]
I'm having the same issue

**Comment by mars-boy** [comment]
Any update on this one. I am still having the issue.

**Comment by amishra-dev** [comment]
This should have been fixed by now. please reactivate if not
