### ISSUE TITLE
[QUERY] Event Hubs: Are diagnostic events being logged?

### ISSUE THREAD

**Issue by SumantaKar** [Azure/azure-sdk-for-net#13542]
**Query/Question**
How can we help?

In the older version of the EventHub SDK (Microsoft.Azure.EventHubs -Version 4.2.0) I see that it raises Diagnostics Events with name "Send.Start" and "Receive.Start" which one can subscribe to and perform some actions. However with the Azure.Messaging.EventHub version I do not see any such diagnostic events being raised. Are there any plans to implement something similar in the newer version of the SDK ? If yes, any timelines ? 

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs -Version 5.1.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Eventhub .Net Core 3.1
 - IDE and version : Visual Studio 2019

**Comment by jsquire** [comment]
Hi @SumantaKar.  Thank you for reaching out and we regret that you're experiencing difficulties.

The good news is that all of the new wave of SDKs, including Event Hubs, are fully instrumented for EventSource-based logs as well as distributed tracing.  You can hook into these using any EventSourceListener that you’d like.  If you’re only interested in the Azure events, the Azure.Core package has an AzureEventSourceListener available that can be used.   More information can be found [in this sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md).

Event Hubs follows the pattern of Start/Error/Complete for its operations at the level of the public API as well as the internal primitives that perform the work.  If you’re looking for a sample of the events that get logged, you can take a peek at the [EventHubsEventSource](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Diagnostics/EventHubsEventSource.cs).

**Comment by jsquire** [comment]
As this was also opened for discussion via email, and I believe that thread resolved the question, I'm going to close this out.   Please feel free to reopen if you feel there is further discussion.
