### ISSUE TITLE
ServiceBus: Remove line breaks in markdown

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-sdk-for-net#13550]
Some of our markdown documents have line breaks. They are not necessary for markdown because of workwrap mechanics of markdown renderers. See comment here: https://github.com/Azure/azure-sdk-for-net/pull/13537/files/9aa47b23f7d3b41d7cdb8a46033d4360d5b4c8ba#diff-e36ac6529b4db622a88ab1e3cd8f8825

**Comment by AlexGhiondea** [comment]
@MiYanni can you take this one?
