### ISSUE TITLE
[DOCS] Remarks have strange formatting in API docs for keyclient.getkeyasync

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#13567]
See https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.keyclient.getkeyasync?view=azure-dotnet#remarks

Page source has it split into paragraphs:

![image](https://user-images.githubusercontent.com/1697911/87863446-dd236c00-c90f-11ea-98d9-c59a10c6b591.png)

cc @scbedd

**Comment by scbedd** [comment]
Will get an issue filed with the docs team. Thanks @pakrym

**Comment by scbedd** [comment]
It looks to me like the docs system is parsing a newline in the `remarks` xml comment as a "new" comment. Here's another example:

[Source](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyClient.cs#L304)
[Rendered](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.keyclient.updatekeypropertiesasync?view=azure-dotnet)

Here is the [issue](https://ceapex.visualstudio.com/Engineering/_workitems/edit/270402)

**Comment by heaths** [comment]
Should we remove the Client label then? Seems there's nothing for me to fix since it's a docs publishing issue. I mean, I could stop using new lines, but that's merely a work around. I know @tg-msft likes to keep lines in Search (and probably Storage) to under 80 chars because...emacs (or just limited GitHub PR widths, but I still blame emacs).

**Comment by heaths** [comment]
@scbedd when will the bug be fixed? It's not feasible to change every doc in the repo with this problem. For now, marking as, effectively, external since this does not affect only Key Vault.

**Comment by kurtzeborn** [comment]
@scbedd I'm not sure we need to keep this open if there's an issue in the docs team's tracking system already.  Up to you whether we close it.  If it's helpful to keep it around so we don't forget it, feel free to leave it open.

**Comment by jsquire** [comment]
Confirming as fixed by the linked PR.
