### ISSUE TITLE
[FEATURE REQ] Bulk upload / List of files upload

### ISSUE THREAD

**Issue by tsafadi** [Azure/azure-sdk-for-net#13572]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
Uploading multiple files at once/ bulk uploading.

I want to upload a list of files. Unfortunately this extremly slow if I do this in a loop. I would like to see a bulk upload operation where I can pass a list of files as a parameter.

**Current scenario:**
```
public UploadFiles(List<IFormFile> files)
{
    // Create the blob client.
    BlobClient blobClient = new BlobClient(blobUri, storageCredentials);
    // Upload each file
    foreach(IFormFile file in files) {
        await blobClient.UploadAsync(file.OpenReadStream());
    }
}
```
_This is extremly slow. It takes about 30 seconds for 20 images._

**Ideal scenario:**
```
// #1
public UploadFiles(List<IFormFile> files)
{
    // Create the blob client.
    BlobClient blobClient = new BlobClient(blobUri, storageCredentials);
    await blobClient.UploadAsync(files);
}

// #2
public UploadFiles(List<byte[]> files)
{
    // Create the blob client.
    BlobClient blobClient = new BlobClient(blobUri, storageCredentials);
    await blobClient.UploadAsync(files);
}

// #3
public UploadFiles(List<Stream> files)
{
    // Create the blob client.
    BlobClient blobClient = new BlobClient(blobUri, storageCredentials);
    await blobClient.UploadAsync(files);
}
```

**Comment by amnguye** [comment]
Hi! Thanks for your suggestion, we will look into this convenience method/overload. If we look to do something like this, we might have like a warning if they define something in the upload options that it will apply to all the upload calls.

**Comment by seanmcc-msft** [comment]
Hi @tsafadi, this feature request would require rest API changes.  If we were to implement these convenience methods today, it won't be any faster, since we'd be doing the same implementation with a loop under the covers.  It is unlikely the rest APIs will be updated to include this feature in the near future.
