### ISSUE TITLE
Calling WithHandlers using more than 2 handlers disposes handlers immediately

### ISSUE THREAD

**Issue by kiwidev** [Azure/azure-sdk-for-net#1357]
Calling .WithHandlers(handlers) with more than 2 handlers (when using TokenCloudCredentials) causes them to be immediately disposed and then throw errors on use.

A workaround is to use .WithHandler multiple times (as the intermediate Clients are not disposed).

Test cases:

    public class HttpClientHandlerDisposingTests
    {
        [Fact]
        public void CreatingAClientShouldntDisposeHandlers()
        {
            // This could be any client which inherits from ServiceClient
            var client = new AuthorizationManagementClient(new TokenCloudCredentials("abc"));
            
            int disposedCount = 0;

            var handlers = Enumerable.Range(0, 5).Select(_ => new DisposableHandler(() => disposedCount++));

            client.WithHandlers(handlers);

            // Failing test. This is returning handlerCount - 2
            Assert.Equal(0, disposedCount);
        }

        [Fact]
        public void CreatingAClientWithCustomCredentialsShouldntDisposeHandlers()
        {
            var client = new AuthorizationManagementClient(new CustomTokenCloudCredentials("abc"));

            int disposedCount = 0;

            var handlers = Enumerable.Range(0, 5).Select(_ => new DisposableHandler(() => disposedCount++));

            client.WithHandlers(handlers);

            // Passing test due to custom cloud credentials workaround
            Assert.Equal(0, disposedCount);
        }

        // Workaround. Calling AddHandlerToPipeline prevents this behavior from occurring
        public class CustomTokenCloudCredentials : TokenCloudCredentials
        {
            public CustomTokenCloudCredentials(string token)
                : base(token)
            {

            }

            public override void InitializeServiceClient<T>(ServiceClient<T> client)
            {
                client.AddHandlerToPipeline(new DummyHandler());
                base.InitializeServiceClient(client);
            }
        }

        public class DummyHandler : DelegatingHandler
        {
        }

        public class DisposableHandler : DelegatingHandler
        {
            private readonly Action onDisposeAction;

            public DisposableHandler(Action onDisposeAction)
            {
                this.onDisposeAction = onDisposeAction;
            }

            protected override void Dispose(bool disposing)
            {
                base.Dispose(disposing);
                if (this.onDisposeAction != null)
                {
                    this.onDisposeAction();
                }
            }
        }
    }

**Comment by markcowl** [comment]
@kiwidev Thanks for the report.  We will take a look.

**Comment by markcowl** [comment]
@kwidev The new generated code no longer has this issue, please update to using the latest client.
