### ISSUE TITLE
[FEATURE REQ] Need more expressive documentation for what param to use for GetById

### ISSUE THREAD

**Issue by 1RedOne** [Azure/azure-sdk-for-net#13579]
**Library or service name.**
Azure.Deployments
 
**Is your feature request related to a problem? Please describe.**
I am experimenting with an app to retrieve info on Azure Deployments using the Fluent API.  The API Docs are confusing me a bit, it looks like Deployments has `SupportsGettingById` but I can't determine which field to provide as the id.  If I provide the IDeployment.Inner.Id field, which looks like this

*"//subscriptions//meowmeowmeow//resourceGroups//catcatcat//providers//Microsoft.Resources//deployments//someTest123"*

I get the error that this is not a valid deployment id.  It also doesn't accept `IDeployment.CorrelationId`.  What id does the `Deployments.GetById()` method want?

**Comment by AlexGhiondea** [comment]
@1RedOne thanks for opening this issue. Could you share more about the package you are using to help better triage this issue?

Thank you!

**Comment by 1RedOne** [comment]
I found my error, I was passing in my ARM Id as a string, escaping the `/` characters, which `GetById()` didn't like.  

When I used unescaped front-slashes, get by Id worked as expected.
