### ISSUE TITLE
[FEATURE REQ] Cognitive Speech: Azure Maps search results emprovement and Speech, to engage Api

### ISSUE THREAD

**Issue by gabser10** [Azure/azure-sdk-for-net#13593]
AzureMaps 
**Predictive Query prediction is missing addresses**
Asking for some addresses the related address is missing some address
https://atlas.microsoft.com/search/address/json?subscription-key=XXXXXXXXX&api-version=1.0&query=via%20aurelia%20km%2013%20roma&countrySet=IT&&typeahead=true&language=%22it-IT%22
query | Result with maximum score  (FreeFormAddress property in address object obrained by maps)
-- | --
Via Aurelia chilometro/i /km 13 Roma | "Via Roma, 13, 17053 Laigueglia"
Via Antonio Marani 24 La   Spezia | "Via   Antonio Marani, 19123 La Spezia"(missing civic)
viale xxi aprile roma | "Via 25 Aprile, 22020 Pigra"
Viale 21 Aprile Roma | "Viale 21 Aprile, 21, 00162 Roma"
via xx settembre roma |"Viale 20 Settembre, 41049 Sassuolo"
Via 20 settembre roma | Via 20 Settembre, 20, 00187 Roma (adding civic)
via  san pio decimo roma | Traversa   Quinta Via San Pio Decimo, 89013 Gioia Tauro

**Speech request to engage api** 
results are frequently wrong Using Cognitive Speech recognition to recognize italian address (and proper name) ..
predictions rarely improve with wrong query generated from speech recognizer, 
I'd need specifically for speaked address recognition api. 

Thank you

**Comment by oscholz** [comment]
We've passed this on to the owner of our Italian model, and that person will be looking into this, and comment here.

**Comment by fezuo** [comment]
For Cognitive Speech recognition request, tested with those AzureMaps query samples + clear speech, and recognition accuracy looks good. Could you let us know if there are some bug samples related to "results are frequently wrong Using Cognitive Speech recognition to recognize italian address" ?

**Comment by gabser10** [comment]
All the query in table are wrong.
query | Result with maximum score  (FreeFormAddress property in address object obrained by maps)
-- | --
Via Aurelia chilometro/i /km 13 Roma | "Via Roma, 13, 17053 Laigueglia"
Via Antonio Marani 24 La   Spezia | "Via   Antonio Marani, 19123 La Spezia"(missing civic)
viale xxi aprile roma | "Via 25 Aprile, 22020 Pigra"
Viale 21 Aprile Roma | "Viale 21 Aprile, 21, 00162 Roma"
via xx settembre roma |"Viale 20 Settembre, 41049 Sassuolo" 
Via 20 settembre roma | Via 20 Settembre, 20, 00187 Roma (adding civic)
via  san pio decimo roma | Traversa   Quinta Via San Pio Decimo, 89013 Gioia Tauro

**Comment by fezuo** [comment]
As we tested Cognitive Speech Recognition request on above samples, with clear it-IT speech input got correct speech to text recognition result. To investigate your issue, could you share one or two speech samples so we can reproduce this issue?

**Comment by gabser10** [comment]
In the above examples are represented azure maps errors. In particular with the queries we obtain the right column result but is always wrong. I’ll attach Some audio with cognitive speech errors also.

**Comment by fezuo** [comment]
Thanks for clarification, please also let us know which one of AzureMaps Search error or Cognitive Speech Recognition errors is more critical to your usage.

**Comment by gabser10** [comment]
Our customers need to query for pratically all addresses in Italy in predctive mode (wiht typehad parameter setted to true). All the examples present in table are needed. 
The examples have in common Caesar's Numbers or Proper Name of people. The example "Via Antonio Marani 24 La Spezia" is particular also because we never obtain civic number in result.
With Google Maps we obtain radically better results.

**Comment by fezuo** [comment]
I can help on Cognitive Service Speech to Text part. To improve entity name recognition, one suggestion is to use Custom Speech, it allows to upload batch of entity names such as street name, and improve recognition accuracy towards those names. Another ways is to improve the base model with specific common entity names, after the gap is identified. In addition, speech to text is enhancing it-IT entity names recognition and new model version will be updated by Dec.

**Comment by gabser10** [comment]
Thank you @fezuo, we know Custom Speech and could be usefull but very wasteful if we needs to train the model with all italian addresses. December could be very late for un update because the customer needs. is there no way of joining  Cognitive Speech and Azure Maps models?

Could  be added The missing addresses in Azure Maps? And could this service enhance predictions in results?

**Comment by fezuo** [comment]
@gabser10 Thanks for the feedbacks. Our team can help to improve speech to text part. We need to verify and reproduce your issues in details. We only see special street name like "Via XX Settembre Roma" got issues in display format, that convert "XX" into 20 which seems wrong. We can correct this display format issue in short term. For other cases, please provide us expected speech recognition display results and audio sample if possible. The Italian model already support all common address, so we need to understand where is the gap. For prediction enhancement , do you mean speech to text recognition result or AzureMaps searching/ranking ?

**Comment by gabser10** [comment]
Thank you @fezuo I'll retrieve soon the audio needed to evidence Speech Problems, but The examples in table are relative to AzureMaps searching/ranking problems.
query | Result with maximum score  (FreeFormAddress property in address object obrained by maps)
-- | --
Via Aurelia chilometro/i /km 13 Roma | "Via Roma, 13, 17053 Laigueglia" | WRONG CITY AND CIVIC
Via Antonio Marani 24 La   Spezia | "Via   Antonio Marani, 19123 La Spezia" | missing civic number
viale xxi aprile roma | "Via 25 Aprile, 22020 Pigra" | WRONG CITY 
Viale 21 Aprile Roma | "Viale 21 Aprile, 21, 00162 Roma" | ADDING WRONG CIVIC NUMBER
via xx settembre roma |"Viale 20 Settembre, 41049 Sassuolo" | WRONG CITY
Via 20 settembre roma | Via 20 Settembre, 20, 00187 Roma | Adding wrong civic number
via  san pio decimo roma | Traversa   Quinta Via San Pio Decimo, 89013 Gioia Tauro | Wrong city wrong street
