### ISSUE TITLE
Enable ContinuousIntegrationBuild  in CI builds

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#13608]
NugetPackageExplorer reports our packages as non-deterministic:

![image](https://user-images.githubusercontent.com/1697911/88075219-56e47100-cb2d-11ea-9609-696bc130fd43.png)

Compare to System.Text.Json:

![image](https://user-images.githubusercontent.com/1697911/88075451-a9259200-cb2d-11ea-9475-2b4a79578492.png)

@weshaggard do we want to do something here?

**Comment by weshaggard** [comment]
This was recently done with PR https://github.com/Azure/azure-sdk-for-net/pull/13057. If you feel like we missed something let me know.

**Comment by pakrym** [comment]
Yes, this is from today's build:

![image](https://user-images.githubusercontent.com/1697911/88102382-51e6e800-cb54-11ea-8a53-76eeced9e50d.png)

**Comment by weshaggard** [comment]
@chidozieononiwu can you please have a look?

**Comment by chidozieononiwu** [comment]
This is now resolved for all track 2 packages.

**Comment by pakrym** [comment]
This is today's build of Azure.Core from our feed:

![image](https://user-images.githubusercontent.com/1697911/126677302-f451e276-03b3-4c11-97f0-e386b4e5e546.png)

**Comment by chidozieononiwu** [comment]
<img width="260" alt="Azure Core" src="https://user-images.githubusercontent.com/31145988/126682301-1af9ad3e-ed37-495f-9878-dfd635f07e60.PNG">

The checks are all green as at when the package is generated as an artifact. Missing symbols is expected since we don't publish symbols after publishing to the devOps feed. Am not sure why the other two check go red after publishing.

**Comment by chidozieononiwu** [comment]
Actually all the red checks are a result of the missing symbols. @weshaggard Should we publish symbols after publishing dev builds.

**Comment by weshaggard** [comment]
At this point I don't know if there is any great reason to publish symbols for our daily builds, but I'm not opposed to if we think they might be useful. I wouldn't do it just to please NugetPackageExplorer though.

**Comment by chidozieononiwu** [comment]
Closing this since wwe are not going to be publishing symbols for dev build, unless there is another specific reason for it.
