### ISSUE TITLE
[FEATURE REQ] Allow creating management clients without specifying the subscription in advance

### ISSUE THREAD

**Issue by aelij** [Azure/azure-sdk-for-net#13604]
**Library or service name.**
Azure.ResourceManager.Resources/1.0.0-preview.1 (and others)
 
**Is your feature request related to a problem? Please describe.**
Currently the subscription ID must be specified when creating the client. This poses an issue when attempting to cache the client's instance. Since the client also holds the pipeline token cache, it is imperative not to create a new one every time. This forces a pattern of saving the clients in a dictionary with the subscription used as a key, which is wasteful.

I propose to allow creating a client without specifying the subscription ID, and add a `WithSubscriptionId` method, which creates **a new instance** with the same pipeline.

```cs
var client = GetSharedClient().WithSubscriptionId("...");
```

**Comment by isra-fel** [comment]
Thanks for your feedback. Loop in @erich-wang

**Comment by allenjzhang** [comment]
@aelij Thanks for submitting the feature request. Does you scenario mostly work across multiple Subscriptions? 

We are looking at the API surfaces changes where there is desire to simplify the amount of data/parameter needed for each calls. But that would run opposite of your proposal where Subid needs to be specified before or on the calls. If we were to change to setting via a property, then it may not be obvious to new users to set that required field for subsequent calls.  

Your thoughts on that?

**Comment by aelij** [comment]
Yes, I'm authoring an RP, so each request can come from a different subscription.

How about leaving the current parameter, but also adding the `WithSubscriptionId` method that allows mutating it (by creating a new instance with the same pipeline). This way I can just use any subid string for the shared instance.

**Comment by allenjzhang** [comment]
Thanks for your input. Backlog added

AB#3926

**Comment by aelij** [comment]
This is now possible using `ArmClient`.
