### ISSUE TITLE
[FEATURE REQ] Allow specifying the auth scope for management libraries

### ISSUE THREAD

**Issue by aelij** [Azure/azure-sdk-for-net#13603]
**Library or service name.**
Azure.ResourceManager.Resources/1.0.0-preview.1 (and probably all management libraries) 
 
**Is your feature request related to a problem? Please describe.**
In the previous SDK, we could use `AzureEnvironment` to set a different URI for the HTTP requests and the authentication audience. In the new SDK, you can only specify a single URI, which then derives the scope by concatenating the URI with `/.default`. For most environments this is not a problem, but Dogfood uses different URIs for HTTP endpoint and scope. So please add an option to specify the scope separately.

**Comment by isra-fel** [comment]
Thanks for the feedback. Loop in @erich-wang

**Comment by allenjzhang** [comment]
Thank you for your input. Backlog added.

AB#4034

**Comment by aelij** [comment]
Another compelling use case for this is using a region-specific ARM endpoint, such as https://westeurope.management.azure.com.

**Comment by abatishchev** [comment]
Yes, please! I cannot start using AutoRest generated client because I want to test it in Azure Dogfood and currently it's impossible to do.

**Comment by abatishchev** [comment]
I would propose to add to the constrictor of each client parameter `string scope` which defaults to the already existing `endpoint` if is null.

**Comment by jiasli** [comment]
I have provided more details of this issue, as well as the Python SDK implementation in https://github.com/Azure/autorest.csharp/issues/972.

**Comment by aelij** [comment]
Now available in `ArmClientOptions.Scope`
