### ISSUE TITLE
[QUERY] Example of how to do a subscription level ARM Deployment?

### ISSUE THREAD

**Issue by 1RedOne** [Azure/azure-sdk-for-net#13609]
**Query/Question**
Hi, I'm working on a project and need to deploy a Subscription level ARM Template.  This doesn't seem possible with `using Microsoft.Azure.Management.Fluent.IAzure.Deployments` but a promising method is available under [Microsoft.Azure.Management.ResourceManager.IDeploymentsOperations](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.ideploymentsoperations?view=azure-dotnet) which has this method of `BeginCreateorUpdateAtSubscriptionScope()`.

Only question is how do I new up an `IDeploymentsOperations` object to do this?  I've looked at the docs but they seem focused on the new Fluent API and don't cover how to do this scenario. 

**Environment:**
 - Microsoft.Azure.Management.ResourceManager bv3.7.3-preview
 - Azure App Service
 - Visual Studio 2019

**Comment by 1RedOne** [comment]
I found that you can new up a `ResourceManagementClient` object like so:

```
private ResourceManagementClient GetResourceManagementClient()
        {
            var credentials = SdkContext.AzureCredentialsFactory
                .FromServicePrincipal(clientId,clientSecret,tenantId,
                    AzureEnvironment.AzureGlobalCloud);
            
            var client = RestClient
                .Configure()
                .WithEnvironment(AzureEnvironment.AzureGlobalCloud)
                .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                .WithCredentials(credentials)
                .Build();

            return new ResourceManagementClient(client);
        }```

An this object exposes `IDeploymentsOperations` via its `Deployments` member.  The only question is how to go about actually calling the method of `Deployments.BeginCreateOrUpdateAtSubscriptionScopeAsync()`

My internal ID is **St**ephen **Owen** @msft if you want to chat.

**Comment by isra-fel** [comment]
Hi @weidongxu-microsoft  can you help? Can we just use the inner .NET SDK to do that?

Thanks

**Comment by weidongxu-microsoft** [comment]
@1RedOne 

THe REST API can be accessed from `IAzure` as well, sample code:
`azure.Deployments.Inner.CreateOrUpdateAtSubscriptionScopeAsync`

**Comment by 1RedOne** [comment]
Hi Wei, thanks for the reply!  Could you give me a minimal viable demo?  I am struggling with the syntax of making a deployment using `azure.Deployments.Inner.CreateOrUpdateAtSubscriptionScopeAsync`, but that seems to be perfect for my scenario!

**Comment by HarveyLink** [comment]
Hi @1RedOne , I think this test may do the demo's job:
https://github.com/Azure/azure-sdk-for-net/blob/eba3aca4a884fa072624e235811e3d835edba751/sdk/resources/Microsoft.Azure.Management.Resource/tests/ScenarioTests/DeploymentTests.ScenarioTests.cs#L548

**Comment by weidongxu-microsoft** [comment]
@1RedOne 

Here is sample code to create resource group

```
            String templateJson = @"{
  ""$schema"": ""https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#"",
  ""contentVersion"": ""1.0.0.0"",
  ""parameters"": {
    ""rgName"": {
      ""type"": ""string"",
      ""defaultValue"": ""rg-weidxu""
    },
    ""rgLocation"": {
      ""type"": ""string"",
      ""defaultValue"": ""westus""
    }
  },
  ""variables"": { },
  ""resources"": [
    {
      ""type"": ""Microsoft.Resources/resourceGroups"",
      ""apiVersion"": ""2019-10-01"",
      ""name"": ""[parameters('rgName')]"",
      ""location"": ""[parameters('rgLocation')]"",
      ""properties"": { }
    }
  ],
  ""outputs"": { }
}";

            Microsoft.Azure.Management.ResourceManager.Fluent.Models.DeploymentInner deploymentParam = new Microsoft.Azure.Management.ResourceManager.Fluent.Models.DeploymentInner()
            {
                Location = "westus",
                Properties = new DeploymentProperties()
                {
                    Mode = DeploymentMode.Incremental,
                    Template = Newtonsoft.Json.JsonConvert.DeserializeObject(templateJson),
                    Parameters = Newtonsoft.Json.JsonConvert.DeserializeObject("{}")
                }
            };
            DeploymentExtendedInner deployment = azure.Deployments.Inner.CreateOrUpdateAtSubscriptionScopeAsync("dpA", deploymentParam).Result;
```

Reference doc https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-subscription

**Comment by 1RedOne** [comment]
That worked great, thank you.  If I may suggest, this would make a fine addition to the docs pages to show this sample.
