### ISSUE TITLE
Swagger follow-up: nullable notations

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#13615]
Some inconsistencies between the swagger file and the actual service responses were spotted in recent Core changes. The ['Add nullable annotations' section](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/autorest.md#add-nullable-annotations) and its transforms should be completely removed from `autorest.md` once corresponding `x-nullable` properties are properly added to the swagger file.

Required work:
- [ ] Find out which scenarios trigger the swagger file inconsistencies.
- [ ] Communicate the findings to the service team. Decide which ones should be updated in the swagger, and which ones need an update on the service side.
- [ ] Make sure that the expected changes are applied to the swagger file and to the service and update the client as required.
- [ ] Remove the `x-nullable` transforms from `autorest.md`.
- [ ] Make sure that tests still pass consistently.

**Comment by jsquire** [comment]
@kinelski: This seems like it may be stale.   Can you confirm whether or not this is still needed and close if not?

**Comment by kinelski** [comment]
The swagger is still inconsistent. Honestly I don't think these will ever be fixed, but it doesn't really matter for the SDK since we have the `autorest.md` workaround. REST API users could be unhappy about it, but I'm not aware of any negative feedback.
