### ISSUE TITLE
AzureBlobXmlRepository never updates the blob if the blob is empty

### ISSUE THREAD

**Issue by ChadNedzlek** [Azure/azure-sdk-for-net#13616]
**Describe the bug**
If you configure data protection with PersistKeysToAzureBlobStorage, and point it to a blob that isn't valid XML (for example, is empty, because you had to create the blob to make a valid SAS token for it), the data protection layer will throw a bunch of exceptions and never actually persist the keys.

https://github.com/Azure/azure-sdk-for-net/blob/a3b6a5ff0f73177571aeaf5670f5fbe753d942fb/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Blobs/src/AzureBlobXmlRepository.cs#L194-L197

I can understand that if the document is somehow malformed, maybe overwriting it is dangerous, but empty should be safe, and it's difficult to create a secure URI without having to create the empty blob to get the SAS token from.

**Expected behavior**
The blob should be updated to include the target xml.

**Actual behavior (include Exception or Stack Trace)**
The blob is never updated, and XmlException is thrown every time it tries.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.  Create an empty blob, and get a SAS uri to it.
2.  Pass that uri to PersistKeysToAzureBlobStorage

**Environment:**
 - Name and version of the Library package used: Microsoft.AspNetCore.DataProtection.AzureStorage (though the code has been moved here, and the code here has the same behavior)
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows Server 2019

**Comment by amnguye** [comment]
I think this might have gotten mistriaged, this is not related to the `Azure.Storage.Blobs` library because we don't have any method related to AzureBlobXmlRepository.

I'm going to assign it to the ASP.NET extensions and see if they can help.

If it is an actually related to the `Azure.Storage.Blobs` library please reassign back with labels `storage` and `client`, along with a snippet of code that's being used and the version of Azure.Storage.Blobs that's being used. Thanks!

**Comment by ChadNedzlek** [comment]
It's still a pretty big problem... it took one our sites our for days as we tried to figure out why none of the authentication worked.

**Comment by pakrym** [comment]
I'm sorry this fell through the cracks, I'll take a look.
