### ISSUE TITLE
[FEATURE REQ] Consider adding a lock in BearerTokenAuthenticationPolicy

### ISSUE THREAD

**Issue by aelij** [Azure/azure-sdk-for-net#13610]
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
When a pipeline is called concurrently, `BearerTokenAuthenticationPolicy` unnecessarily attempts to fetch multiple tokens for the same scope, one of which will be saved in the policy's cache. Consider adding a lock (e.g. a `SemaphoreSlim`) which would allow only a single request to go through.

**Comment by AlexGhiondea** [comment]
@AlexanderSher could you take a look here?

**Comment by AlexanderSher** [comment]
Issue is fixed Azure.Core 1.4.1
