### ISSUE TITLE
Add support for .NET 5's System.Text.Json to JsonObjectSerializer

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#13627]
Per offline discussion, I will simplify the code for now, open an issue for tracking support for STJ in .NET 5, and add a comment to the code referencing the issue / summary.

See https://github.com/dotnet/runtime/blob/dc8b6f90/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs#L147-L155 for implementation.

_Originally posted by @heaths in https://github.com/Azure/azure-sdk-for-net/pull/13527/files_

**Comment by jsquire** [comment]
@heaths:  Can you give this a look and determine if it's still needed now that .NET 5 has gone out of support?

**Comment by heaths** [comment]
net5.0 has gone out of support, but this was meant more as >= net5.0 where fields became serializable. So, yes, IMO this is still needed. That said, we've had no feedback of which I'm aware so maybe we close it till we do. @tg-msft?

**Comment by pallavit** [comment]
Given our stance on MRW is this still something we see us doing?
/cc: @heaths , @jsquire , @m-nash

**Comment by heaths** [comment]
At this point, may as well close it. We can always revisit it later, but it's been over 3 years.
