### ISSUE TITLE
[QUERY] Azure Storage Blobs: Extreme long time to upload

### ISSUE THREAD

**Issue by larini** [Azure/azure-sdk-for-net#13638]
Hi, using code bellow I got two cases this month that takes more than 70 seconds to respond:

    blockBlob.Properties.ContentType = 'application/pdf';
    await blockBlob.UploadFromStreamAsync(fileData);

These pdf files are very small, about 11KB.

99,9% of cases are good.

How can I inspect what is going on?

**Comment by amnguye** [comment]
Hi,

You can take advantage of using Azure Monitor on your storage dashboard to look at the odd requests that are taking too long.
https://azure.microsoft.com/en-us/services/monitor/

If you happen to catch the slow uploads within a day and you have the logs, you can open a support ticket with Azure. By providing the logs and request-ids, we can get to the bottom on the service side to see if the slow down is on our side.

I hope this answers your question.

**Comment by larini** [comment]
I will give it a try.
