### ISSUE TITLE
Search SDK: Allow additional methods to control serialization of custom types

### ISSUE THREAD

**Issue by NickMoores** [Azure/azure-sdk-for-net#1363]
Hello,

I would be quite keen to see clients of the Search SDK allowed access to some of the JSON serialization settings, particularly the IContractResolver being used.

I am creating some extensions that, using the Search SDK, allow attributes to be defined on class properties, which can then be used to build an index definition dynamically and create it in Azure Search (similar to Entity Framework's code first table creation).  Instances of the same class can then also be used as type arguments to the IDocumentOperations.IndexAsync<T> method.  My biggest annoyance so far is that I can control the index field names when serialized for index creation using my own custom attribute (IndexFieldAttribute(Name="")), but in order to control how instances of the class are serialized for indexing I have to add a JsonPropertyAttribute as well.  This results in my properties looking like this:

```C#
[IndexField("AltTitle", FieldProperties.Retrievable, Order = 1)]
[JsonProperty("AltTitle")]
public string AlternativeTitle { get; set; }
```

Ideally, I'd like to keep my IndexFieldAttribute and drop JsonPropertyAttribute, whilst providing a custom IContractResolver to the Search SDK which will control serialization of objects.

Perhaps I'm missing an alternative method to accomplish this, in which case feel free to shoot this down. :-)

**Comment by brjohnstmsft** [comment]
Hi Nick,
I'm working on a fairly substantial update to the Search SDK right now, and many of the improvements should make working with model classes much easier. I'll make sure your scenario is covered.

Also, in the longer term I'd like to see us add the ability to create index definitions from model types as part of the SDK itself. That might be an area where we'd like to accept contributions from the community.

**Comment by brjohnstmsft** [comment]
Some related issues that I'm also looking to address in the big update I'm working on: https://github.com/Azure/azure-sdk-for-net/issues/1259
https://github.com/Azure/azure-sdk-for-net/issues/1063

**Comment by NickMoores** [comment]
Very cool - thanks!  I'll keep an eye on updates.

**Comment by brjohnstmsft** [comment]
I've added support for custom `IContractResolvers`. It will ship with the next version of the SDK (1.0.0-preview), most likely in a few weeks.

**Comment by brjohnstmsft** [comment]
FYI, the fix is now available in the latest version of the SDK [on NuGet](http://www.nuget.org/packages/Microsoft.Azure.Search).
