### ISSUE TITLE
Azure.Storage.Blobs.ChangeFeed Readme issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#13633]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs.ChangeFeed#azure-storage-blobs-change-feed-client-library-for-net)
![image](https://user-images.githubusercontent.com/65581162/88142644-6f858180-cc28-11ea-92b8-bca2640c0bc5.png)

Reason:
Link is not available.
Suggestion:
Change the hyperlink of `Source code` to https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs.ChangeFeed/src

~~2.~~
~~Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs.ChangeFeed#troubleshooting)~~
![image](https://user-images.githubusercontent.com/65581162/88142711-904dd700-cc28-11ea-9f42-1e12a4f26076.png)

~~Reason:~~
~~There is a redundant space.~~
~~Suggestion:~~
~~Change it to `ErrorCodes`~~

3.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs.ChangeFeed#next-steps)
![image](https://user-images.githubusercontent.com/65581162/88140610-a063b780-cc24-11ea-954e-c8ea758fadbe.png)

Reason:
This link is not available, because opening this link corresponds to Sample02_Auth.cs, but there is currently no sample in the samples folder.

**Comment by v-xuto** [comment]
@jongio for notification.

**Comment by tg-msft** [comment]
Editing out the error code feedback.  `ErrorCode` is a property name/type suffix and we want that `formatted as code` without the 's'.

**Comment by Tianyun-G** [comment]
@tg-msft  -  About the error code question, we should change it to  `ErrorCode` , `ErrorCodes` or something else?

**Comment by tg-msft** [comment]
I think we use `ErrorCode`s, like it is now.  The formatting is trying to help make it clear that `RequestFailedException` has an `ErrorCode` property with values that people should check.

**Comment by Tianyun-G** [comment]
PR merged.
