### ISSUE TITLE
Azure.Storage.Files.DataLake Readme and Sample issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#13634]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/blob/1c2ee747d1def9a6d5f270f97e76f292681dd366/sdk/storage/Azure.Storage.Files.DataLake/samples/Sample01a_HelloWorld.cs#L262)
![image](https://user-images.githubusercontent.com/65581162/88142235-baeb6000-cc27-11ea-8c5f-7e3a8eaa637f.png)

Reason:
'Azure.RequestFailedException : The specified path already exists ' was thrown in line 262.

Suggestion:
The file has been created by file.create(), it is better to add  an argument  overwrite : true when calling upload();
```
file.Upload(File.OpenRead(sampleFileContent),true);
```
~~2.~~
~~Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Files.DataLake#troubleshooting)
![image](https://user-images.githubusercontent.com/65581162/88142505-3220f400-cc28-11ea-96c4-598a7481bc70.png)~~

~~Reason:~~
~~There is a redundant space.~~
~~Suggestion:~~
~~Change it to `ErrorCodes`.~~

**Comment by v-xuto** [comment]
@jongio for notification.

**Comment by tg-msft** [comment]
Editing out the error code feedback.  `ErrorCode` is a property name/type suffix and we want that `formatted as code` without the 's'.

**Comment by Tianyun-G** [comment]
PR merged.
