### ISSUE TITLE
Add Azure.Storage.Blobs unit test to validate https://aka.ms/bloburl

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#13636]
~~1.~~
~~Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs#troubleshooting)\
![image](https://user-images.githubusercontent.com/65581162/88141752-c9854780-cc26-11ea-912a-55c800345c83.png)~~

~~Reason:~~
~~There is a redundant space.~~
~~Suggestion:~~
~~Change it to `ErrorCodes`~~

2.
Section [link1](https://github.com/Azure/azure-sdk-for-net/blob/1c2ee747d1def9a6d5f270f97e76f292681dd366/sdk/storage/Azure.Storage.Blobs/samples/Sample01b_HelloWorldAsync.cs#L120) and [link2](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/samples/Sample01a_HelloWorld.cs#L119)
![image](https://user-images.githubusercontent.com/65581162/88142062-6b0c9900-cc27-11ea-8ccd-e959dd319980.png)

Suggestion:

There are some points need to be updated about this sample.

1. Use a placeholder like `<Blob Sas Uri>` instead of `https://aka.ms/bloburl`. 
2. This sample downloads jpg file but the `CreateTempPath()` returns a txt file by default.

**Comment by v-xuto** [comment]
@jongio for notification.

**Comment by tg-msft** [comment]
Editing out the error code feedback.  `ErrorCode` is a property name/type suffix and we want that `formatted as code` without the 's'.

I'll restore `https://aka.ms/bloburl`.  The `CreateTempPath` part should be fine because we overwrite the file.

**Comment by tg-msft** [comment]
I've restored https://aka.ms/bloburl and worked with EngSys to make sure it's never deleted again.  Leaving the bug open to either make sure our sample tests run live or we add a unit test that specifically tries downloading `https://aka.ms/bloburl` to ensure it doesn't disappear again.  Removing blocking-release labels.

**Comment by jongio** [comment]
@tg-msft Can you see if we can close this one as well?

**Comment by Tianyun-G** [comment]
@jsquire, @tg-msft  Can you see if we can close this one as well?

**Comment by tg-msft** [comment]
Yes - this has been added to the tests that power our samples.
