### ISSUE TITLE
Remove AspNetCore from Azure.Extensions.AspNetCore.Configuration.Secrets

### ISSUE THREAD

**Issue by krispenner** [Azure/azure-sdk-for-net#13650]
Microsoft.Extensions.* are used for all .NET platforms, not just ASP.NET Core.
There should be no dependencies on ASP.NET Core at all so why have the name in the package, assembly and namespace?
Before you launch this as a final product I recommend you fix the name.
There is nothing stopping anyone from using this package in a non ASP.NET Core project as it has nothing to do with ASP.NET Core. Please correct me if I'm wrong.

I believe you should just mimic the dotnet team's naming and go with `Azure.Extensions.Configuration.Secrets`, the inclusion of AspNetCore seems like an oversight. I will use this in a Console application and the AspNetCore in the name made me think it wouldn't be compatible when in fact it was just incorrect naming. I think you will confuse many others.

I'm not sure if this is a bug or maybe a feature request instead.

**Comment by krispenner** [comment]
Interestingly I see the changelog shows it was originally named correctly as `Azure.Extensions.Configuration.Secrets` but on May 5th it was renamed to `Azure.Extensions.AspNetCore.Configuration.Secrets`. I'd be very interested in hearing your reasons for the rename and if there is any way you would re-consider. Again I think this will confuse developers who are not building ASP.NET Core applications.

**Comment by pakrym** [comment]
Your argument is exactly what initially motivated the `Azure.Extensions.Configuration.Secrets` name. But then we realized that we are going to have Azure-specific extensions for things that are not in `Microsoft.Extensions` namespace, for example Azure.Functions bindings and we possibly would need to be consistent across languages too.

So the short answer is that `Azure.Extensions` part is the package name is not a reference to `Microsoft.Extensions` but a root namespace for Azure-specific extensions for all kinds of things and `AspNetCore` happens to be the name of the group for "things related to ASP.NET Core".

BTW there is a precedent on dotnet's side too: microsoft.aspnetcore.dataprotection is not exactly AspNetCore specific but kept the name.

**Comment by krispenner** [comment]
@pakrym Thanks for your response, a couple additional comments I'd like to say are:

1. The ASP.NET Core team is removing AspNetCore name from some packages/namespaces where they don't actually depend on ASP.NET Core or have become generic. They only used that namespace originally because it was the ASP.NET Core team that developed them. One example is [AspNetCore.Hosting to Extensions.Hosting](https://stackoverflow.com/questions/50847635/namespace-aspnetcore-hosting-vs-extensions-hosting).
1. I don't personally see an issue in sharing the `Extensions` namespace with both `Microsoft.Extensions` dependent packages and Azure defined extensions. If you feel must have a name separation, maybe start something new, like `Azure.Extensions.DotNet.Configuration.Secrets` at least that's more clearer in my opinion, but I'd still prefer the namespace was just shared.

Like I said, you will confuse others that this is AspNetCore specific when it is not, why follow a bad precedent set by previous bad examples? You might regret this later and I think fixing it now when it's only a few months old with 4,000 downloads it better than next year.

I'll close this but hope you still reconsider :)

**Comment by BrianVallelunga** [comment]
I just came to add this issue as well and am disappointed to see it is closed. It is very confusing that this has AspNetCore in the name. I'm not using it for anything Asp.Net Core related and it doesn't make sense to have that there. It's a very useful library though and I've moved all of my connection strings into KeyVault with it. Please reconsider opening this. It's not like packages haven't been renamed before and it still has a relatively small number of downloads on Nuget. You can always add a deprecation notice with the new package name.
