### ISSUE TITLE
[Form Recognizer] HardCoded region causes failure in other clouds

### ISSUE THREAD

**Issue by XuGuang-Yao** [Azure/azure-sdk-for-net#13669]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

The [`StartCopyModelFailsWithWrongRegion` ](https://github.com/Azure/azure-sdk-for-net/blob/315ae970ad2523df4e241137095993d9620683a8/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormTrainingClient/FormTrainingClientLiveTests.cs#L264) test case requires a region, which is different from the region where the form recognizer service is located, but it has been hardcoded. The region is only available in azure cloud. When running the test in other clouds, no results or exceptions are returned. It just keeps running for a very long time which causes the pipeline job canceled.

![image](https://user-images.githubusercontent.com/53599438/88268902-b8f7ce80-cd05-11ea-91ff-1b04c861d0e2.png)

**Comment by tzhanl** [comment]
@jongio @danieljurek for notification.

**Comment by jsquire** [comment]
@tzhanl:  If you'd be so kind, please ensure the `needs-triage` label remains in place so that I can ensure that the right folks are looped in for awareness.

**Comment by annelo-msft** [comment]
@kinelski @maririos @AlexGhiondea @mayurid  FYI

**Comment by XuGuang-Yao** [comment]
@maririos - Thank you for your fix. But the issue still persists. Set regoin to `usgovarizona ` and run the test against US gov cloud, region `westcentralus ` will be picked. 

`var wrongRegion = TestEnvironment.TargetResourceRegion == "westcentralus" ? "eastus2" : "westcentralus";`

The `westcentralus `doesn't exist in US gov cloud so the copy oparetion will continuous run wihout any result returned. Test is stuck in `WaitForCompletionAsync`. Hence ,only change the error code couldn't fix the issue.

`RequestFailedException ex = Assert.ThrowsAsync<RequestFailedException>(async () => await operation.WaitForCompletionAsync(PollingInterval));`

**Comment by maririos** [comment]
Thanks for the update. Please know that the purpose of the test is to try to copy a model to a region that the client doesn't have access to, so even if `westcentralus` is picked, that shouldn't affect it.
We changed the test because the service updated the error codes.

As for the problem you are seeing, @ctstone looks like this is a service issue. Could you confirm?

**Comment by ctstone** [comment]
@XuGuang-Yao, I don't think cross-cloud copy is supported by Cognitive Services. Do you see expected results if you copy between `usgovvirginia` and `usgovarizona`?

The service should be returning _something_ though. I'll investigate this on our side.

**Comment by XuGuang-Yao** [comment]
@ctstone, Thank you for the updates. The form recognizer service is located in `usgovvirginia `and I use the `usgovarizona `as wrong region to run this test. The result is as following. 
```
Message: 
      Expected string length 18 but was 21. Strings differ at index 0.
      Expected: "AuthorizationError"
      But was:  "ResourceResolverError"
```
This error is caused by updated error code doesn't work as expected, but the copy process does have the result returned.

@maririos , Could you please help to check why the `AuthorizationError `doesn't work?

**Comment by maririos** [comment]
@XuGuang-Yao `AuthorizationError` is the error code we are getting from the service when we test to copy a model from a region we don't have access to (at least when using `westcentralus`, `westus2`, and `eastus2`

@ctstone could the service have a different version in `usgovvirginia` and therefore error codes are different?

**Comment by jongio** [comment]
Could we get an update on this issue please?  Thank you.

**Comment by maririos** [comment]
@XuGuang-Yao the service has been doing some deployment updates. Could you give it a try again and let us know if the error code is still different than the one we get with Public Azure?

**Comment by jongio** [comment]
Heads up @v-xuto

**Comment by zedy-wj** [comment]
@maririos `StartCopyModelFailsWithWrongRegion()` test can pass in Public, it also looks good between region `usgovvirginia` and `usgovarizona` in UsGov. But the value of `wrongRegion` was hardcoded here : 
`var wrongRegion = TestEnvironment.TargetResourceRegion == "westcentralus" ? "eastus2" : "westcentralus";`,
when run the test against UsGov cloud, it will causes the pipeline timesout.

**Comment by jongio** [comment]
@maririos - Thoughts on what to do for this?

**Comment by maririos** [comment]
I guess the service still has that bug. 
I saw that @zedy-wj provided a solution for this issue in https://github.com/Azure/azure-sdk-for-net/pull/20970 which looks good.

**Comment by jongio** [comment]
I think what @zedy-wj is saying is that we expect an error if it is the wrong region, but it is timing out instead.

Is that correct?

**Comment by zedy-wj** [comment]
@jongio - Yes, for example, if the cloud was set with `UsGov` and we chose a region in `Public` for variable `wrongRegion`, it would cause timing out. So we could not hardcode the variable `wrongRegion` , we should set different regions in different clouds.

**Comment by jongio** [comment]
@zedy-wj - Can this be fixed if we update the test to allow different regions or is this due to the client not allowing different regions?  If we can simply update the test, then let's do that.  Thanks, Jon

**Comment by zedy-wj** [comment]
@jongio - The PR #22267 can fix this issue.
