### ISSUE TITLE
Azure Identity Iron Semester for .NET

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#13684]
The Azure Identity library provides Azure Active Directory token authentication support across the Azure SDK. It provides a set of TokenCredential implementations which can be used to construct Azure SDK clients which support AAD token authentication.

This issue tracks the new features, reliability improvements, and the release of minor updates to Azure.Identity for .NET during September - December 2020

**Comment by jsquire** [comment]
Closing, as all associated issues were either closed or had been moved to the backlog milestone.
