### ISSUE TITLE
Incorrect file versioning (2.3.18.0) for Microsoft.Rest.ClientRuntime (2.3.19) breaks patching of this binary in scenarios relying on MSP patching

### ISSUE THREAD

**Issue by Manishd79** [Azure/azure-sdk-for-net#13692]
**Describe the bug**
Azure File Sync (AFS) team have an on-premise agent which does have Microsoft.Rest.ClientRuntime.dll and agent is serviced via msp/Microsoft Update which require **REINSTALLMODE=omus** option for patching/updating the old binaries. The **Microsoft.Rest.ClientRuntime (v2.3.19)** package has the **Microsoft.Rest.ClientRuntime.dll (v2.3.18.0)** which seems to be mismatching for the package. And this mismatch in binary versioning impact any patching (.msp) scenario which typically run with option **REINSTALLMODE=omus** and [here ](https://documentation.help/Windows-Installer/reinstallmode.htm) is complete details of the switches. 

**Expected behavior**
Package and files in the package should have same versioning scheme to make it consistent, easier to find out what package version/file version used. In addition, this will unblock the issue of **non-patching of this binary from a .msp with default option**

**Actual behavior (include Exception or Stack Trace)**
Due to file versioning as v2.3.18.0, any older file with same versioning would not get patched automatically by msp process. Azure File Sync team relies on msp/Microsoft Update for offering the servicing updates for its agent. 

**To Reproduce**
Screenshot is attached of the binary where one can see that file version is 2.3.18 while the product version is 2.3.19
![image](https://user-images.githubusercontent.com/10888146/88337233-36621580-cceb-11ea-924a-2a42ea6016c5.png)

**Environment:**
 - **<package id="Microsoft.Rest.ClientRuntime" version="2.3.19" />**

**Comment by AlexGhiondea** [comment]
@pakrym @ShivangiReja I think we should look at this and see if we can publish a new version with the updated file versions.

**Comment by pakrym** [comment]
I've checked the latest version and it doesn't have this problem.

![image](https://user-images.githubusercontent.com/1697911/88349118-096e2c80-cd04-11ea-8768-d7ab3ef5cbdb.png)

@Manishd79 what is your suggestion as to what we can do here?

**Comment by Manishd79** [comment]
@pakrym that will help. Thanks much for the update.
