### ISSUE TITLE
JsonObjectSerialize should ignore any BOM when deserializing

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#13698]
Follow up to the above comment https://github.com/Azure/azure-sdk-for-net/pull/13527#discussion_r456734973

The following code snippet won't work when the stream starts with a UTF-8 BOM.

https://github.com/Azure/azure-sdk-for-net/blob/61241787da85546516933d4321f1c9a963e63658/sdk/core/Azure.Core.Experimental/src/Serialization/JsonObjectSerializer.cs#L52-L54

The synchronous, `JsonSerializer.Deserialize` method that accepts a `ReadOnlySpan<byte>` expects only valid JSON data (without any trivia or artifacts). The BOM is considered invalid JSON and will fail.

The async, stream accepting API explicitly skips the BOM for you (to support things like file stream). For this workaround, you would have to explicitly skip the BOM yourself.

https://github.com/dotnet/runtime/blob/e87fbd1030b472b4bc44c375434da65611aa4df0/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.Stream.cs#L159-L164

```C#
var utf8 = new byte[5] {0xEF, 0xBB, 0xBF, (byte)'{', (byte)'}'};
object obj = JsonSerializer.Deserialize<object>(utf8);

/*
Unhandled exception. System.Text.Json.JsonException: '0xEF' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: '0xEF' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
*/
```

This is why I asked if accepting input streams that could contain a BOM is important to support here.

There is an existing request to add the sync stream-accepting APIs to S.T.J, but until then, you'd need to address it yourself as a workaround:
https://github.com/dotnet/runtime/issues/1574

As an aside, we can avoid the extra allocation and `.ToArray()` call in that method, if performance is important, if the stream is seek-able and we have access to `ArrayBufferWriter<T>`, i.e. running on core (which should be true in most cases):
https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraybufferwriter-1?view=netcore-3.1
```C#
public static object Deserialize(Stream stream, Type returnType)
{
  if (stream.CanSeek)
  {
    int dataLength = (int)stream.Length;
    var abw = new ArrayBufferWriter<byte>(dataLength);
    Span<byte> span = abw.GetSpan(dataLength);
    
    while(true)
    {
      int bytesWritten = stream.Read(span);
      if (bytesWritten == 0) break;
      abw.Advance(bytesWritten);
      span = span.Slice(bytesWritten);
    }

    ReadOnlySpan<byte> written = abw.WrittenSpan;
    int start = 0;
    // TODO: if first byte is start of utf-8 bom, check the next 3 bytes, and then skip them.
    written = written.Slice(start);

    return JsonSerializer.Deserialize(written, returnType);
  }

  using var memoryStream = new MemoryStream();
  stream.CopyTo(memoryStream);
   // TODO: if first byte is start of utf-8 bom, check the next 3 bytes, and then skip them.
  return JsonSerializer.Deserialize(memoryStream.ToArray(), returnType);
}
```

_Originally posted by @ahsonkhan in https://github.com/Azure/azure-sdk-for-net/pull/13527#issuecomment-662161699_

**Comment by pakrym** [comment]
I don't think we ever expect service responses to start with BOM. Closing until proven wrong.
