### ISSUE TITLE
Memory allocations in BinaryEncoder

### ISSUE THREAD

**Issue by althomps** [Azure/azure-sdk-for-net#1370]
Hello,

I'm memory profiling Avro serializer, and for types that contain a string, it's allocating memory in every call to Serialize() -- with a call to Encoding.UTF8.GetBytes() in Encode(string).  Is this something you would consider addressing?

Thanks

**Comment by shahabhijeet** [comment]
@althomps please open a new issue if the problem still exists/repros.
