### ISSUE TITLE
[BUG] ListEdgeNodes on CdnProfiles throws an Exception

### ISSUE THREAD

**Issue by rjregenold** [Azure/azure-sdk-for-net#13714]
**Describe the bug**

I am trying to use the SDK to get the list of IP addresses for CDN edge nodes. I created a service principal using the following Azure CLI command:

```
az ad sp create-for-rbac --sdk-auth
```

My code looks like this:

```
var creds = SdkContext
    .AzureCredentialsFactory
    .FromServicePrincipal(
        "[client-id]", 
        "[client-secret]", 
        "[tenant-id]", 
        AzureEnvironment.AzureGlobalCloud);
            
var azure = Azure
    .Configure()
    .Authenticate(creds)
    .WithDefaultSubscription();
        
var edgeNodes = azure.CdnProfiles.ListEdgeNodes();

// ... do other things
```

When I call this method, I get an `ErrorResponseException` with a message of `Operation returned an invalid status code 'Forbidden'`. I can call all the other methods on the `CdnProfiles` object without any issue. Also, my service principal is a `Contributor` on the subscription, so should have access.

I noticed that using the following code works:

```
async Task Main()
{
    var clientId = "[client-id]";
    var clientSecret = "[client-secret]";
    var tenantId = "[tenant-id]";
    var tenantDomainName = "[tenant-domain-name]";
    var subscriptionId = "[subscription-id]";
    var authority = $"https://login.microsoftonline.com/{tenantId}/{tenantDomainName}";

    var authResult = await GetAccessTokenAsync(clientId, clientSecret, authority);

    var cdn = new CdnManagementClient(new TokenCredentials(authResult.AccessToken))
        { SubscriptionId = subscriptionId };

    var edgeNodes = await cdn.EdgeNodes.ListAsync();
}

private static Task<AuthenticationResult> GetAccessTokenAsync(string clientId, string clientSecret, string authority)
{
    var authContext = new AuthenticationContext(authority);
    var credential = new ClientCredential(clientId, clientSecret);
    return authContext.AcquireTokenAsync("https://management.core.windows.net/", credential);
}
```

I asked a question about this [on stackoverflow](https://stackoverflow.com/questions/63063127/what-permission-is-required-to-access-the-listedgenodes-operation-in-the-azure-r).

**Expected behavior**
I should receive a list of edge nodes from the API.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
I get an `ErrorResponseException` with the following message:

```

{"error":{"code":"AuthorizationFailed","message":"The client '7400aa2d-3213-41d7-a52d-586dd7d46360' with object id '7400aa2d-3213-41d7-a52d-586dd7d46360' does not have authorization to perform action 'Microsoft.Cdn/EdgeNodeInners/read' over scope '/providers/Microsoft.Cdn' or the scope is invalid. If access was recently granted, please refresh your credentials."}} | {"error":{"code":"AuthorizationFailed","message":"The client '7400aa2d-3213-41d7-a52d-586dd7d46360' with object id '7400aa2d-3213-41d7-a52d-586dd7d46360' does not have authorization to perform action 'Microsoft.Cdn/EdgeNodeInners/read' over scope '/providers/Microsoft.Cdn' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
-- | --
{"error":{"code":"AuthorizationFailed","message":"The client '7400aa2d-3213-41d7-a52d-586dd7d46360' with object id '7400aa2d-3213-41d7-a52d-586dd7d46360' does not have authorization to perform action 'Microsoft.Cdn/EdgeNodeInners/read' over scope '/providers/Microsoft.Cdn' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Run the code above.

**Environment:**
 - Name and version of the Library package used: `Microsoft.Azure.Management.CDN 4.40` and `Microsoft.Azure.Management.Fluent 1.34.0`
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 ASP.NET Core 3.1
 - IDE and version : LINQPad

**Comment by jsquire** [comment]
Tagging and routing to the team best positioned to assist.

**Comment by isra-fel** [comment]
@weidongxu-microsoft for help, thanks

**Comment by weidongxu-microsoft** [comment]
@rjregenold Thanks for reporting. This seems a pretty crazy bug.
