### ISSUE TITLE
Expose an API interface to retrieve Tenant ID given a KeyVault Key URI

### ISSUE THREAD

**Issue by kr-santosh** [Azure/azure-sdk-for-net#13713]
**Library or service name.**

Azure.Security.KeyVault
 
**Is your feature request related to a problem? Please describe.**

We had a request regarding this particular use case and we were wondering if an API can be exposed by Azure Key Vault SDK team wherein provided a Key Vault Key URI  we can retrieve the Tenant ID.
This would be extremely useful  in using Key Vault SDK in a multi-tenant model, not requiring an user of CosmosDB SDK to deal with that . Currently CosmosDB is working on client side encryption support and relies on Key Vault for securely storing and retrieving data encryption keys.

**Comment by jsquire** [comment]
Tagging and routing to the team member best positioned to assist.

**Comment by heaths** [comment]
@schaabs is this something that should be exposed more generally, perhaps as part of identity?

For Key Vault, a workaround exists to add a policy that processes the 401 challenge response to parse out the `authorization` value of the challenge response. There is no API for Key Vault that would otherwise get the tenant for a vault URI.

**Comment by heaths** [comment]
@kr-santosh is the goal here to support multi-tenant authentication, or do you really just need to get the tenant ID?

If the former, this may be a duplication of #22607 (I realize your issue is older, but we already have more information available in the new one).

/cc @schaabs @christothes

**Comment by heaths** [comment]
Confirmed offline that this is a duplicate of #22607 and will track the feature request there.

**Comment by heaths** [comment]
Sorry, I linked the wrong bug. I meant this was a duplicate of #18359.
