### ISSUE TITLE
CodeGeneration.targets flags github PR links as GithubUrlsWithoutHash

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#13753]
[example](https://dev.azure.com/azure-sdk/public/_build/results?buildId=473767&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=e75da802-0139-5977-bd1e-91175bec9059&l=38)

`D:\a\1\s\eng\CodeGeneration.targets(38,5): error : Following GitHub URLs do not contain commit hash: https://github.com/Azure/azure-rest-api-specs/pull/10262 please use permalinks for code generation inputs (see https://help.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files)  [D:\a\1\s\sdk\keyvault\Azure.Security.KeyVault.Administration\src\Azure.Security.KeyVault.Administration.csproj]`

**Comment by pakrym** [comment]
I think this is correct. We want a link pointing to a specific version of the file even if it's part of the RP.
