### ISSUE TITLE
[Design] Apply discussed design changes for consistency with other languages

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#13756]
## Summary

Inconsistencies with other languages were found, and renames must be done to address them. Some items still need discussion.

## Updates

- [x] In `FormRecognizerClient.RecognizeCustomForms`, parameters `formFileUri` and `formFileStream` should be renamed to `formUri` and `form`, respectively.
- [x] In `TrainingDocumentInfo`, rename `DocumentName` to `Name`.
- [x] In `TrainingFileFilter`, rename `IncludeSubFolders` to `IncludeSubfolders`.
- [x] In `CustomFormModelStatus`, rename `Training` to `Creating`.
- [x] In `FieldValueType`, rename `Integer` to `Int64`.

## Open discussions

- [x] In `CopyAuthorization`, members `AccessToken`, `ResourceId` and `ResourceRegion` are internal, but in Java they're public. Find out what's the desired approach here. Follow-up: #13857.
- [x] In `CustomFormModelStatus`, in other languages the member `Training` is called `Creating`. Find out why this decision was made and rename it, if necessary. Edit: if we wanted to keep the `Training` status, a `Copying` status would need to be added as well. However, when calling `GetCustomModel` or `GetCustomModels`, there's no way of differentiating between training and copying, since the service returns `creating` in both scenarios. We'll rename it and keep consistency with other languages here.
- [x] In `FieldValue`, consider renaming `AsInt64` to `AsLong` to match Java's API. Edit: we'll keep it as `AsInt64` since it follows [pre-existing .NET BCL nomenclature](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement.getint64?view=netcore-3.1).
- [x] In `FieldValueType`, consider renaming `Integer` to `Long` to match Java's API. Edit: we'll rename it to `Int64` to match the `AsInt64` method.
- [x] Service-returned floating point numbers have 64-bit precision in Java, while we have only 32-bit precision in .NET. Find out why there's a difference and whether we need to change this or not. Edit: service team confirmed that 32-bit is enough. No changes needed.
- [x] In `FormRecognizerError`, find out why we decided to call the error code `ErrorCode`, as other languages name it `Code`. We're likely to keep it as it is. Edit: we renamed it to `ErrorCode` for consistency with the Text Analytics library in .NET. We'll keep it like this in Form Recognizer.

**Comment by maririos** [comment]
>FormRecognizerError, find out why we decided to call the error code ErrorCode

The reason why TA went with `ErrorCode` is also because of [`RequestFailedException`](https://github.com/Azure/azure-sdk-for-net/blob/3edb484a64afc93d6dc9be9d0947bbaad49f9763/sdk/core/Azure.Core/src/RequestFailedException.cs#L25).
