### ISSUE TITLE
[QUERY] Azure.Messaging.ServiceBus connection limits and session receiving/processing question

### ISSUE THREAD

**Issue by chris-skuvault** [Azure/azure-sdk-for-net#13787]
**Query/Question**
How can we help?

From the documentation https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas it says the "Number of concurrent connections on a namespace" is 5000. In looking through the implementation in Azure.Messaging.ServiceBus codebase it seems like a single `ServiceBusClient` will reuse a single connection but I'm not entirely sure. 

Does `ServiceBusClient` use the same connection throughout its lifetime or does a connection get spun up per receiver or per concurrent receivers when using a processor? Can one connection have 5000 concurrent receive request operations on a topic subscription?  I'm trying to understand the relationship between the client and the connection quota.

**Environment:**
 - Azure.Messaging.ServiceBus preview-4
 - .net core 3.1

**Comment by JoshLove-msft** [comment]
Hi @chris-skuvault, thanks for raising this question. Any receivers/senders created off a single `ServiceBusClient` will indeed [share ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Client/ServiceBusClient.cs#L16)the same connection.

**Comment by chris-skuvault** [comment]
Hi @JoshLove-msft,

Thanks for the quick response. That clears up my misunderstanding. I appreciate it!
