### ISSUE TITLE
[FEATURE REQ] Add support for receiving message by sequence number

### ISSUE THREAD

**Issue by mrwatts** [Azure/azure-sdk-for-net#13799]
The Microsoft.Azure.ServiceBus.Core MessageReceiver class does not support receiving a message by it's sequence number. In the old library (WindowsAzure.ServiceBus / Microsoft.ServiceBus.Messaging) it did. [docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.messagereceiver.receive?view=azure-dotnet)

What I want to do, is Peek at the messages as they come by, and take the one I am interested in. Using ReceiveAsync to accomplish this, is not an option, as that won't work when the Queue is monitored by multiple processes: the lock is retained after I have received a message I am not interested in, even though I have already read the next one, which causes concurrency and throughput issues. Abandoning the messages I am not interested in, is not an option, as I just get fed the same messages over and over again).

With the old library, this scenario was possible, as I could Peek the messages and then Receive the message I want using ReceiveAsync(Int64 sequenceNumber). With the new one, it is not, because once I have found the message I want using PeekAsync, there is no way to process that message. I cannot Receive it, I cannot Complete it, so there is no way for me to remove it from the queue. 

The only option I have is let everything Deadletter and clean up the deadletter queue periodically, but that is completely wrong for obvious reasons.

**Comment by jsquire** [comment]
Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//fyi:  @JoshLove-msft, @MiYanni, @richardpark-msft, @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@axisc, Is receiving message by sequence number when the message is not a deferred message supported by Service Bus?

**Comment by SeanFeldman** [comment]
@mrwatts the method you're looking for provided by `ServiceBusReceiver` and is named `ReceiveDeferredMessageAsync(long)`.

**Comment by mrwatts** [comment]
> @mrwatts the method you're looking for is provided by `ServiceBusReceiver` and is named `ReceiveDeferredMessageAsync(long)`.

No, that only receives deferred messages. If you attempt to fetch a message that is not deferred, it will throw an exception.

**Comment by SeanFeldman** [comment]
Track 1 had `MessageReceiver.PeekBySequenceNumberAsync()`. There was no option to receive using a sequence number.
Track 0 supported receiving by sequence number but I only used it with deferred messages. Was it working with non-deferred messages as well?

**Comment by axisc** [comment]
@mrwatts Thanks for sharing the details on the issue.

While the earlier library supported it, I feel that the scenario violates the concept of server/sender side cursor (and also the FIFO concept of a queue). Peek and Receive should always give you the first message on the queue which is not locked by competing consumers.

The way to sidestep this is with deferred messages, which essentially hands over the cursor to the client/receiver to decide when it wants to process the message. As it stands, deferral and then receiving is a more deterministic solution to avoid the problem that you have described.

hope this helps, do let us know if you have any follow up questions.

**Comment by mrwatts** [comment]
@axisc My use case is multiple, unconnected processes handling the same queue, where every message can only be handled by one specific process. Your suggestion is to defer the message (I assume I would have a separate process that handles all the messages as they come in and does nothing but defer them) and then have another process pick up that deferred message.

I don't see how that could work reliably. The only way to do it would be to have the other process Peek at the messages, and when it finds the message it should handle, do a wild shot at receiving it as deferred message (not knowing if the message has already been deferred by the deferral process, the Message object itself does not hold any information on its deferred state). If that causes an exception, wait a second and try again, hoping it will be deferred then. That is about as nondeterministic as it gets and relying on exceptions for process flow.

The only deterministic way would be to pass the sequence number from the deferring process to the other. But when I find a neat solution for that, I have essentially done what I tried to accomplish in the first place and deferring becomes redundant: I might as well pass the whole message and not just the sequence number.

Another way I can think of, is by adding subscriptions to a Topic at runtime (with a filter) and removing them when they are no longer needed. But that feels really resource intensive and requires a lot of management.

I can understand your position that "cherry-picking" messages violates the concept of server side cursor. But that was the solution I could come up with, with the tools at hand (in the old library).

However, I think that being able to pass a filter when receiving messages, based on properties like CorrelationId, would be a valuable addition. The underlying principles then still apply: 

> Peek and Receive should always give you the first message on the queue which is not locked by competing consumers _[and match the supplied filter]._

At the moment I am using a Storage Table in my project, besides the Service Bus, to achieve what I need, but I would much rather have a pure Service Bus solution.

**Comment by axisc** [comment]
@mrwatts Topic-Subscription could help simplify if your receivers know exactly what messages it needs to process (and you can draw out a criteria for a filter from that).

If you really need a way of querying a durable data store then Service Bus is not the best solution. The flow is somewhat possible with deferred messages, but it is an add-on feature for an incremental workflow and not the default flow (which is simply send and receive).

I understand the older library allowed this which may be adding to the confusion, but I think you may have better design by changing this.

Filtering when receiving messages (if implemented) is going to give bad performance because you have to scan the whole queue to identify the first message that satisfies the condition. Topic-Subscription with filters is a much better idea here.

**Comment by mrwatts** [comment]
@axisc I replied to your suggestion on #14202 . Will close this thread, as there is no need to discuss the same solution on two threads.
