### ISSUE TITLE
[BUG] Forbidden from Keyvault for reading secrets when using User Assigned Managed identity (along with system assigned identity)

### ISSUE THREAD

**Issue by manums** [Azure/azure-sdk-for-net#13808]
An user assigned identity is assigned to azure function . This identity has access to keyvault with read and list permissions to secrets. This user assigned identity is used *only* to get access to some shared resources like this Keyvault

- Azure function also has system assigned identity which provides access to other resources.
- If I provide access to system assigned identity to keyvault with read,list secret and remove user assigned identity (from azure function) then azure functions (using system assigned identity) is able to pull secrets from keyvault as expected

**Expected behavior**
Read secrets from keyvault using User managed identity as MSI.

**Actual behavior (include Exception or Stack Trace)**
Forbidden while reading secret.

`Details = Microsoft.Azure.KeyVault.Models.KeyVaultErrorException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion, Dictionary"2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String secretIdentifier, CancellationToken cancellationToken)
`

**To Reproduce**
Code snippet:
```cs
var azureServiceTokenProvider = new AzureServiceTokenProvider();
keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));
SecretBundle secretBundle = await keyVaultClient.GetSecretAsync(secretId).ConfigureAwait(false);
return secretBundle.Value;
```

**Environment:**
 - Name and version of the Library package used: **Microsoft.Azure.KeyVault 3.0.4**
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): **Azure Function App - Windows - 64 bit**
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by AlexGhiondea** [comment]
@heaths @christothes could one of you take a look?

**Comment by heaths** [comment]
Are you able to upgrade to Azure.Security.KeyVault.Secrets (V4)? Support for Managed Identity - authentication in general - is much easier, boiling down to:

```csharp
var credentials = new DefaultAzureCredential(); // from Azure.Identity package
var client = new SecretClient(new Uri("your vault"), credentials);
KeyVaultSecret secret = client.GetSecretAsync("my-secret");
```

`DefaultAzureCredential` also has the advantage of supporting developer workflows, so you don't have to change your code from testing locally or debugging, to production.

Otherwise, if you must keep using Microsoft.Azure.KeyVault, see https://docs.microsoft.com/azure/key-vault/general/service-to-service-authentication#running-the-application-using-managed-identity-or-user-assigned-identity for using user-assigned identities.

Let me know if that doesn't work if you have more questions.

**Comment by manums** [comment]
Function is able to access keyvault secret with `AzureServicesAuthConnectionString` environment variable set to `RunAs=App;AppId={ClientId of user-assigned identity}`. 

Thanks @heaths  for pointing me to that. 

Can you confirm if azure function has:

- Multiple user assigned managed identities assigned?

- Both System assigned identity and user assigned identity assigned.

**Comment by heaths** [comment]
Yes, Functions should support both. See https://docs.microsoft.com/azure/app-service/overview-managed-identity?tabs=dotnet for more information. If you have Functions questions beyond that, you may find better support contacting the Functions team. I can help with Key Vault issues, but don't know a lot about Functions beyond the public documentation.

**Comment by manums** [comment]
@heaths is there a way to use more than one user assigned managed identity in one azure function app. What should appid to set for environment variable `AzureServicesAuthConnectionString` - RunAs=App;AppId={ClientId of user-assigned identity}?

**Comment by heaths** [comment]
The client ID is the GUID assigned to your managed identity, which you can find in the Azure Portal for your managed identity as "Client ID".

You can get this in the Azure CLI if you know your identity name and resource group, e.g.:
```bash
 az identity show -n myid --resource-group rg-mygroup --query clientId
```

Where `myid` is your managed identity name, and `rg-mygroup` is your resource group name.

**Comment by manums** [comment]
My question is more about which app to set (in case of multiple user assigned managed identities) as AppId for `AzureServicesAuthConnectionString` environment variable. 

I have both clientIds for both user assigned managed identities that are assigned to the function app where one provides access one shared keyvault and other provides access to some other keyvault owned by some other team(in different RG and subscription).

**Comment by heaths** [comment]
That's probably best answered by the Azure Functions team. Perhaps an environment variable can't be used, but I can't tell you for sure. I recommend contacting them internally since I see you're part of the Microsoft org.

**Comment by manums** [comment]
**This bug needs to be reopened. Issue mentioned is still present**. To explain in detail:

a. Function app is assigned with system assigned identity (appId = firstGuid) that gives access to KV - A to read secrets
b. Function app also has user assigned managed identity (appId =secondGuid) that gives access to KV - B to read secrets.
c. Function configuration is updated with new environment variable with value like below:
`AzureServicesAuthConnectionString`=`RunAs=App;AppId=secondGuid`
![image](https://user-images.githubusercontent.com/3592179/89490181-1574d800-d761-11ea-846a-9c967be38793.png)


Added a function with console output to test above scenario. Function now can only access KV - B not KV - A.

> Trying to fetch KV- B secret - https://KVB.vault.azure.net/secrets/exampleSecret
> Success getting https://KVB.azure.net/secrets/dfp-config-access-appsecret. Result = -/KPmasked
> Trying to fetch merchant KV- A - https://KVA.vault.azure.net/secrets/exampleSecret
 _Error getting Merchant KV- A secret - Operation returned an invalid status code 'Forbidden'_

**Comment by heaths** [comment]
Because you configured the environment variable to use the user assigned managed identity. It's working as designed. You are trying to use two different identities simultaneously, but the environment variable can only contain a reference to one. If that's even possible to run as two different identities, you'll need to work with the Azure Functions team for how that should be specified. It's not a bug in the SDK, but it working exactly as configured.

**Comment by manums** [comment]
I got answer from azure functions team that we need to explicit while new'ing AzureServiceTokenProvider with connection string of identity that we want to use to read secret or access keyvault.

Thanks for your answers, Heath.
