### ISSUE TITLE
Adding a hybrid connection object to a web app or a function app

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-sdk-for-net#13818]
**Query/Question**

Hello colleagues, I was trying to find a way to add a hybrid connection object, created for an Azure Relay to an existing Web App or Function app, but did not find a way for doing it through SDK. Could you kindly point me out to sample code or an existing class within SDK that is able to do it?

Thanks

**Comment by jsquire** [comment]
Tagging and routing to the team member best able to assist.

**Comment by isra-fel** [comment]
@allenjzhang  could you take this issue? Thanks

**Comment by eosfor** [comment]
Any updates on the topic, please?

**Comment by m-nash** [comment]
I believe you are looking for
        public async Task<AzureOperationResponse<HybridConnection>> UpdateHybridConnectionWithHttpMessagesAsync(string resourceGroupName, string name, string namespaceName, string relayName, HybridConnection connectionEnvelope, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken))

which is found under WebSiteManagementClient->WebApps found in this SDK https://www.nuget.org/packages/Microsoft.Azure.Management.WebSites/

**Comment by allenjzhang** [comment]
If the proposed API does not work for you. please reopen the issue. Thanks again for posting questions here.
