### ISSUE TITLE
Avro Serializer does not support IEnumerable<string>

### ISSUE THREAD

**Issue by haltunbay** [Azure/azure-sdk-for-net#1382]
I have a simple class that has a field type of IEnumerable<string>.  While trying to serialize it with reflection I got SerializationException with message "Could not find any matching known type for ..."

Class to serialize

```
[DataContract]
public class MyClass
{
    [DataMember]
    public string Field1;

    [DataMember]
    //public string[] Array1; This works
    public IEnumerable<string> Array1; //this doesn't
}
```

The line causes exception 

```
    [TestMethod]
    public void CreateSerializerTest()
    {
        var serializer = AvroSerializer.Create<MyClass>(settings);
    }
```

**Comment by shahabhijeet** [comment]
@haltunbay please open a new issue if the problem still exists/repros.
