### ISSUE TITLE
[FEATURE REQ][Azure.Identity] AuthenticationRecord should expose its constructor as public

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#13828]
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
AuthenticationRecord should expose its constructor below as public:
```csharp
        internal AuthenticationRecord(string username, string authority, string homeAccountId, string tenantId, string clientId)
```
In current Azure PowerShell, some properties in AuthenticationRecord is already persisted in context file with its own structure, so Azure.Identity should allow partners to chose their own way import/export AuthenticationRecord.

**Comment by schaabs** [comment]
As we discussed offline we won't be adding a public constructor on `AuthenticationRecord` to avoid obscuring the intended usage.  As a workaround you can use the `IdentityModelFactory` if you need to construct this type. We are adding `IdentityModelFactory` for mocking purposes in #14769.

**Comment by pakrym** [comment]
This doesn't seem to be a mocking purpose though.
