### ISSUE TITLE
[FEATURE REQ] Make it possible to use sharedaccesssignature without providing a connection string

### ISSUE THREAD

**Issue by esbenbach** [Azure/azure-sdk-for-net#13830]
**Azure.Messaging.ServiceBus (Track2)**
 
**Is your feature request related to a problem? Please describe.**
I have some code that uses the old (Track 0) service bus SDK and in the process of trying to replace it with Track2 I have found no way to create a SharedAccessSignatureToken because all the stuff is internal. I can presumable provide all the details as a connection string, but since I have the various values as separate parameters, it feels silly to build a connectionstring, to have the SDK deconstruct again.

In Track0 i could do something like:
```
var tokenProvider = TokenProvider.CreateSharedAccessSignatureTokenProvider("keyname","mykey");
```

Don't know what the best approach would be but possibly just making some of the existing token/credential classes public would do the trick, since there is already a `ServiceBusClient` ctor that takes a TokenCredential instance.

**Comment by jsquire** [comment]
Hi @esbenbach.   Thank you for reaching out and sharing your feedback.  Support for SAS tokens is something that we're still considering designs for across the Azure Messaging clients.  

If you're willing to share some further detail, we'd be very interested in better understanding your scenario.  Outside of the efficiency consideration, are there any other factors that would lead you to prefer the use of a dedicated token-type over a connection string?  

To help illustrate, the two different patterns would likely look similar to:

```csharp
var timeToLive = TimeSpan.FromHours(4);
var token = new ServiceBusSharedAccessTokenCredential("keyName", "keyValue", timeToLive);

await using var client = new ServiceBusClient("<< FULLY QUALIFIED NAMESPACE>>", token);
// ...
```

```csharp
var timeToLive = TimeSpan.FromHours(4);

var connectionString = new ServiceBusConnectionStringBuilder("<< FULLY QUALIFIED NAMESPACE >>")
  .WithSharedAccessSignature("keyName", "keyValue", timeToLive)
  .Build();

await using var client = new ServiceBusClient(connectionString, token);
// ...
```

**Comment by esbenbach** [comment]
Well it is mostly the efficiency and the cosmetic, i really dont get the need for a connectingstring unless it actually allows some underlying protocolhandler to do the work. It seems to me like a remnant, sort of like "ohh well this is how we used to do it with sql, lets do it here as well" (this is probably ignorance on my part on how thing actually work).


The other thing is that there is already an option for providing a token, its just only possible to create them if I am the library(internal classes) or if i use a service/user principal (Azure.Identity) - it seems odd to not allow any type of token regardless of how it is obtained.

**Comment by jsquire** [comment]
Well.... the bot seems to have messed up here, as this isn't a PR.   Removing the label so that this remains active for tracking until we can confirm the SAS credential work has been completed.

**Comment by JoshLove-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/19785
