### ISSUE TITLE
AuthenticationFailed: The JWT token does not contain expected audience uri 'https://management.core.windows.net/'.

### ISSUE THREAD

**Issue by ganeshpande** [Azure/azure-sdk-for-net#1385]
I am getting the following error while trying to list Virtual Networks using client authenticated using Token creds. Shouldn't the NetworkManagementClient class be setting the base URI properly?
In the code I can see that, it is set to 'https://management.core.windows.net' and not 'https://management.core.windows.net/' 

Is the '/' at the end causing the issue? 

Microsoft.WindowsAzure.CloudException: AuthenticationFailed: The JWT token does not contain expected audience uri 'https://management.core.windows.net/'.
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.WindowsAzure.NetworkOperationsExtensions.List(INetworkOperations operations)

**Comment by devigned** [comment]
Yes, the / is causing the issue.

**Comment by devigned** [comment]
I don't think that is the issue. I think the issue is the token you are getting from Azure Active Directory. In the AcquireToken method, you are specifying an audience, which is not http...mangement...net/. You must specify that audience when acquiring a token to be used with the management libs.

**Comment by devigned** [comment]
Also see: http://www.dushyantgill.com/blog/2015/05/23/developers-guide-to-auth-with-azure-resource-manager-api/. It provides a great in-depth look at authentication using AAD and ADAL.

**Comment by devigned** [comment]
If you would like some guidance on how to get a token with the appropriate audience, please provide your code sample minus the sensitive parts.
