### ISSUE TITLE
[BUG] SearchOptions.Select is readonly

### ISSUE THREAD

**Issue by rosponda57** [Azure/azure-sdk-for-net#13875]
The property Select  in SearchOptions is readonly , so we cant set the fields we want to retrieve

I was expecting that this property would let us to set the list of fields we want to retrieve:

                 SearchOptions parameters =
                new SearchOptions()
                {
                    Select = new List<string>() { "field1", "field2" }, 
                     ............
                };

I'm using Azure.Search.Documents v.11.0.0

**Comment by jsquire** [comment]
Tagging and routing to the team member best able to assist.

**Comment by tg-msft** [comment]
[We have a guideline to not provide settable collection properties.](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values)  You can use C#'s list initializer syntax to achieve the same thing:

```C#
SearchOptions options = new SearchOptions() { Select = { "field1", "field2" } };
```

**Comment by rosponda57** [comment]
Ok, thank's for the solution.


How about runtime, and adding a dynamic list of fields to Select?  (e.g. user chooses fileds to select)
What would be the best solution?

**Comment by tg-msft** [comment]
The suggestion from the above guideline suggest using `IList<string>.Add`:

> Users can replace the contents of the collection by clearing the collection first and then adding the new contents. If replacing the whole collection is a common scenario, consider providing the AddRange method on the collection.

**Comment by xavierjohn** [comment]
In this case, there should be a constructor that takes the select parameter. Right now, the usage is confusing.
