### ISSUE TITLE
[QUERY] Example of the right way to get an IResourceManagementClient using non-fluent API.

### ISSUE THREAD

**Issue by 1RedOne** [Azure/azure-sdk-for-net#13876]
**Query/Question**
I see there is an `IResourceManagementClient` which I would like to use because passing this in with DI will be much easier to test than trying to mock `ResourceManagementClient` itself.  I can't find a lot of examples on using `Microsoft.Azure.Management.ResourceManager` so I'm asking here.

What's the proper way to get this interface to use instead of the concrete class?

Here's how I new up the class itself today.

```
 protected virtual ResourceManagementClient GetAzureResourceManagementClient(string token, string subID)
        {
            var tokenCred = new TokenCredentials(token);                        
            var credentials = new AzureCredentials(tokenCred, null, null, this.azureEnvironment); ;
            var resourceClient = new ResourceManagementClient(credentials)
            {
                SubscriptionId = subID
            };
            return resourceClient;
        }
```

If it's really easy, please be gentle with me, since I thought the syntax for getting an IAzure interface was kind of complex, like this.

```
protected virtual IAzure GetAzureAuthenticationClient(string token, string subID)
        {
            var tokenCred = new TokenCredentials(token);            
            var credentials = new AzureCredentials(tokenCred, null, null, this.azureEnvironment);

            return Azure.Configure().Authenticate(credentials).WithSubscription(subID);
        }
```

**Environment:**
- Microsoft.Azure.Management.ResourceManager bv3.7.3-preview
- Azure App Service
- Visual Studio 2019

**Comment by jsquire** [comment]
Tagging and routing to the team member best able to assist.

**Comment by isra-fel** [comment]
@1RedOne Hi, we generate an interface `I*ManagementClient` and a concreate class `*ManagementClient` which implements the interface for every SDK. The only way to use the interface is to instanciate the concreate class -- you are doing the right thing.

As of mocking, all I can think of is to write your own `Mock*Client implements I*Client` . Never saw anyone did that before :(

**Comment by 1RedOne** [comment]
Closed!  I wrote the tests using this approach, Mock*Client implements
I*Client and it worked perfectly.
