### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ShreyasRmsft** [Azure/azure-sdk-for-net#13879]
**Describe the bug**
There are times when a [azure vm linux run command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest) execution gets hung and remains in this state indefinitely and we are unable to queue new run commands on that VM. The 90 minute timeout mentioned in the docs does not kick in. Stopping and starting the VM also does not allow queueing a new run command. 

One simple way to repro this is to restart the walinuxagent process while a run command script is executing. This is not the only reason why it's gotten hung though, it has happened a few times arbitrarily but restarting the walinuxagent is one definitive way to repro this issues.

**Expected behavior**
There should be a server side timeout for the run command if the walinuxagent never reports back the status of the runcommand due to various reasons such as systems restarts etc.

**Actual behavior (include Exception or Stack Trace)**
The previous command remains in progress indefinitely and we are unable to queue new commands even after the 90 min timeout described in the docs

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. One simple way to repro this is to restart the walinuxagent process while a run command script is executing.

**Environment:**
 - Name and version of the Library package used: https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest
 - Hosting platform or OS: Azure Linux VM, Debian.

**Comment by jsquire** [comment]
Hi @ShreyasRmsft.   Unless I misunderstand the context, it appears that your feedback is related to the Azure CLI and not one of the .NET Azure client libraries.  The CLI is not part of this repository;  you may want to consider opening an issue in the [CLI repository](https://github.com/Azure/azure-cli/issues) to ensure that the right folks are able to assist.

I'm going to close this out, but please feel free to reopen if you believe that there's further discussion needed.
