### ISSUE TITLE
Show other than "null" for SecretString parameters when listing Graphs for LiveVideoAnalytics.Edge

### ISSUE THREAD

**Issue by luisgizirian** [Azure/azure-sdk-for-net#13882]
**Describe the bug**
When getting data from `GraphInstanceList`, show other legend than "null" for those parameters that are defined as SecretString at the topology level.

As a dev, if I see `null` somewhere unexpected, my sweating begins :)

**Expected behavior**
<secure/hidden-string> or whatever.

**Actual behavior (include Exception or Stack Trace)**
```
[Edited...]
{
  "Value": [
    {
      "Name": "Sample-Graph-1",
      "ApiVersion": null,
      "SystemData": {
        "CreatedAt": "2020-07-31T16:42:05.766+00:00",
        "LastModifiedAt": "2020-07-31T16:42:05.766+00:00"
      },
      "Properties": {
        "Description": "Sample graph description",
        "TopologyName": "SomeTopologyName",
        "Parameters": [
          {
            "Name": "rtspPassword",
            **"Value": null**
          }
        ],
        "State": 2
      }
    }
  ],
  "ContinuationToken": null
}
```

**Comment by jsquire** [comment]
Tagging and routing to the team best able to assist.

**Comment by luisgizirian** [comment]
Closing as it doesn't belong here. Sorry about the confusion.
