### ISSUE TITLE
Inconsistencies with TimeSpan and "PT" nomenclature within LiveVideoAnalytics.Edge

### ISSUE THREAD

**Issue by luisgizirian** [Azure/azure-sdk-for-net#13883]
**Describe the bug**
Most properties (from `MediaGraph*` classes), expect the nomenclature (i.e "PT30S", for 30 seconds) as a string. Found that `MediaGraphAssetSink.SegmentLength` expects a TimeSpan instead. It does work, but feels like an inconsistency.

**Comment by jsquire** [comment]
Tagging and routing to the team best able to assist.

**Comment by luisgizirian** [comment]
Closing as it doesn't belong here. My apologies.
