### ISSUE TITLE
[BUG] Inconsistency between BlobServiceClient and BlobContainerClient Connection String Parsing

### ISSUE THREAD

**Issue by m-russ** [Azure/azure-sdk-for-net#13880]
**Describe the bug**
Using the Azurite Storage emulator Docker Image  with connection string: ```DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azure-storage-emulator:10000/devstoreaccount1;``` 

This works fine with the BlobServiceClient, but drops the account name when passed into BlobContainerClient.

BlobServiceClient: (works)
```new BlobServiceClient(this.azureStorageConnctionString);```
Route:
```PUT /devstoreaccount1/{containerName}/{fileName}```

BlobContainerClient: (does not work)
```new BlobContainerClient(this.azureStorageConnctionString, file.ContainerName);```
Route:
```GET /{containerName}/{fileName}```

**Expected behavior**
What is the expected behavior?

BlobContainerClient will keep the storage account name at the end of the route specified in the connection string, like BlobServiceClient does.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

BlobContainerClient drops the account name off the route resulting in 400 response from emulator.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Run Azurite Storage Emulator Docker Image
2. Connect to Container using Azure.Storage.Blobs 12.4.4 with BlobServiceClient and BlobContainerClient using connection string specified above or here : https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?toc=/azure/storage/blobs/toc.json#authorization-for-tools-and-sdks
3. Observe difference in request routes through each of the clients.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

Docker Compose: 3.4
Azure.Storage.Blobs: 12.4.4
HostApplication: .Net Core 2.2
HostImage: mcr.microsoft.com/dotnet/core/aspnet:2.2
AzuriteImage: mcr.microsoft.com/azure-storage/azurite:latest

**Comment by jsquire** [comment]
Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
This looks like a bug, and I think might be a duplicate. I will mark this as a bug for now and we will look to get this fixed soon thanks!

**Comment by xiafu-msft** [comment]
Hi @m-russ 
it looks like @amnguye has fixed the issue, can you please use the recently released sdk and check again

**Comment by amnguye** [comment]
Issue seems resolved. Please reply if the issue persists and we will reoopen.
