### ISSUE TITLE
[FEATURE REQ] Support Multiple API Versions in a Single SDK

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-sdk-for-net#13884]
**Library or service name.**
AzureStack
 
**Is your feature request related to a problem? Please describe.**
In Azure Stack Hub, we try to have a consistent developer experience similar to Azure. This includes having Profile support on each of the SDKs so that they can enable the hybrid solution. A Profile is used to represent a set of Namespaces and their API versions. It is a representation of us as an Azure Platform declaring a set of APIs to be supported across all our clouds. This will allow users to select a Profile to use for Azure as well as select another Profile to use with Azure Stack. Currently, some of our SDK’s have a single package that has all of the API-versions in there. We need there to be a multi-api package that allows for developers to target different clouds to enable hybrid consistency. Multi-API version SDKs allows for developers to target both Azure and Azure Stack Hub, which enables our hybrid cloud platform story. These SDKs are used by some of our biggest customers, such as Siemens, Pivotal, and EY. 

Currently in .Net , for azure stack customers , the sdl team have generated a single API versioned package having the namespace as the profile name 
https://www.nuget.org/packages?q=hybrid_2019_03_01
This alleviates the pain of dependency mismatch across different RP packages, but developing a hybrid app is still a pain.

The profile map for azure stack is maintained here in the specs repo https://aka.ms/2019profile

The Python SDK for the azurestack supported RPs are truly multi-api versioned, i.e single package supports multiple api versions. The CLI is a great example of a hybrid app built on top of multi versioned python SDK.

**Comment by allenjzhang** [comment]
@bganapa , thank you for your feedback. One thing to keep in mind is languages like C# and Java are static type langauges.  Unlike Python, it is much harder to maintain different schemas and yet maintain a single model types without having to hand craft the types and API surfaces. Having said that, we are looking into the multi-api support for C# to see how we can best support it. Issues linked to our backlog. Will reopen once we have results.

AB#3922.
