### ISSUE TITLE
[BUG] Azure Service Bus Queue (RegisterMessageHandler) not working on .NET 5.0 Preview 7

### ISSUE THREAD

**Issue by steven1152** [Azure/azure-sdk-for-net#13899]
**Describe the bug**
An exception is thrown repeatedly on exceptionReceivedHandler after calling queueClient.RegisterMessageHandler when running .Net 5.0.
The exact same project runs fine on .Net Core 3.1.

**Expected behavior**
No exception thrown

**Actual behavior (include Exception or Stack Trace)**
Following exception is thrown repeatedly
```
Message handler encountered an exception System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass64_0.<<ReceiveAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.<MessagePumpTaskAsync>b__11_0().
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Using Visual Studio 16.7.0 Preview 6.0 with .NET SDK 5.0.100-preview.7 installed, follow the instructions from [Receive messages from the queue](https://docs.microsoft.com/en-ca/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues#receive-messages-from-the-queue)
2. Make sure the target framework for the project is net5.0
3. Make sure that the ConnectionString and QueueName constants are valid (The queue does not need to contain any messages)
4. Start Debugging

**Environment:**
Microsoft.Azure.ServiceBus 4.1.3
Visual Studio 16.7.0 Preview 6.0
.NET SDK 5.0.100-preview.7.20366.6

**Comment by jsquire** [comment]
Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @MiYanni

**Comment by brenwebber** [comment]
Experiencing the exact same issue. Switching project from 3.1 to 5 (with no other changes) starts generating this error. All our services use Service Bus, so this is a blocker to us trying 5 atm.

Subscribed.

**Comment by mehalick** [comment]
I'm having the same issue trying to send a message with `MessageSender.SendAsync(message)`, also using Microsoft.Azure.ServiceBus 4.1.3 and .NET SDK 5.0.100-preview.7.20366.6.

The same code works as expected in .NET Core 3.1.

**Comment by brianleemoore** [comment]
Debugging the issue using symbols from Microsoft Symbol Server and attempting to send a message using a .net 5.0 console application and Microsoft.Azure

**Comment by jsquire** [comment]
//cc:  @xinchen10  for expertise on the `Microsoft.Azure.Amqp` library,  and @sjkwak for awareness.

**Comment by jsquire** [comment]
#14068 seems like it may be the same underlying cause.

**Comment by natelaff** [comment]
Dead on previewing .NET 5 preview 8 because of this as well. First project I converted hit this.

**Comment by frankbuckley** [comment]
Are there plans to release a fixed package soon?

**Comment by frankbuckley** [comment]
Workaround: TransportType=AmqpWebSockets

**Comment by steven1152** [comment]
Installing version 2.4.6 of Microsoft.Azure.Amqp fixed the issue on my side

**Comment by steven1152** [comment]
The version 5.0.0 of Microsoft.Azure.ServiceBus available on Nuget uses the fixed version of Microsoft.Azure.Amqp.
I believe this issue can now be closed.

**Comment by devedse** [comment]
I just recently installed package version 5.2.0:
![image](https://user-images.githubusercontent.com/2350015/103913310-b0a31c80-5108-11eb-8de7-431ac3605150.png)

However I'm still running into this issue with the following code:
```
            var producer = new EventHubProducerClient(ConfigStuff.connectionString, ConfigStuff.eventHubName);
            var partitions = await producer.GetPartitionIdsAsync();
```
