### ISSUE TITLE
[FEATURE REQ] ScoringStatistics and Features Mode

### ISSUE THREAD

**Issue by paragagrawal11** [Azure/azure-sdk-for-net#13910]
Support for ScoringStatistics=Global and Features Score released in the new API in C# SDK
https://docs.microsoft.com/en-us/azure/search/index-similarity-and-scoring#:~:text=see%20Scoring%20Profiles.-,Scoring%20statistics%20and%20sticky%20sessions,the%20data%20within%20a%20shard.

**Comment by jsquire** [comment]
Tagging and routing to the team members best able to assist.

**Comment by heesunlee9** [comment]
Which support do you need? What is your specific question? Do you want updated documentation?

**Comment by heaths** [comment]
Thank you for the suggestion. We'll consider this for a future release.

**Comment by tg-msft** [comment]
Once https://github.com/Azure/azure-rest-api-specs/pull/10350 is merged, we should be able to add these to our client library.

**Comment by TravisTroyer** [comment]
Any news on this issue?

**Comment by heaths** [comment]
`SearchOptions.ScoringStatistics` and `SearchOptions.SsssionId` have been added to https://www.nuget.org/packages/Azure.Search.Documents/11.2.0-beta.1 and you can try them out now.

@paragagrawal11 could you clarify what "Features Score" means? @brjohnstmsft any ideas? I don't see anything obvious in the linked doc, nor am I aware of any features that correspond to that.

**Comment by brjohnstmsft** [comment]
Paging @shmed

**Comment by TravisTroyer** [comment]
I just noticed the original link is specifically anchored to the similarity and scoring section, but that page also has a section on the **featuresMode** parameter, which is what I'm specifically looking to utilize:

https://docs.microsoft.com/en-us/azure/search/index-similarity-and-scoring#featuresmode-parameter-preview

>Search Documents requests have a new featuresMode parameter that can provide additional detail about relevance at the field level. Whereas the @searchScore is calculated for the document all-up (how relevant is this document in the context of this query), through featuresMode you can get information about individual fields, as expressed in a @search.features structure. The structure contains all fields used in the query (either specific fields through searchFields in a query, or all fields attributed as searchable in an index). For each field, you get the following values:
Number of unique tokens found in the field
Similarity score, or a measure of how similar the content of the field is, relative to the query term
Term frequency, or the number of times the query term was found in the field

**Comment by shmed** [comment]
We originally added the new FeaturesMode flag to the API Specs, but then removed it when we decided not to GA the feature in 2020-06-30 API. The feature is only available in 2019-05-06-preview and 2020-06-30-preview API, which, as far as I know, don't have SDK support yet.

**Comment by heaths** [comment]
That is correct. Only 2020-06-30 GA (-preview will use a different date once a GA date is set) is targeted by the SDK currently. We will eventually have a beta release for future service previews. As such, I'm closing this since the other half of the feature has shipped and we'll pick up any future changes during source generation.
