### ISSUE TITLE
How to check the detail of status of container instance after creating

### ISSUE THREAD

**Issue by mjaow** [Azure/azure-sdk-for-net#13918]
**Query/Question**

Recently I found many container instances were not accessible after creating it.  It last for 30min and than we stop the task

However , we have no idea what's going on? How can I get the container instance status ( or event, or debug information) for it?

https://docs.microsoft.com/en-us/azure/container-instances/container-instances-get-logs#get-diagnostic-events
the docs says cli `az container show --resource-group myResourceGroup --name mycontainer` can query the events, how can I do that in .NET sdk?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by amnguye** [comment]
To view container logs, you have to use the storage management plane SDK instead
https://www.nuget.org/packages/Microsoft.Azure.Management.ContainerInstance/

I will relabel this issue with Mgmt, so it gets routed and gets the proper attention. Please relabel with client and storage if this is a Azure.Storage.Blobs issue.

**Comment by mjaow** [comment]
no need, already done

**Comment by ThorstenHans** [comment]
can someone elaborate on this one? The list of Events on an instance of `ContainerGroupImpl` queried by fluent Management SDK is empty. 

I cant find any documentation on how to get events from a ContainerGroup
