### ISSUE TITLE
Transient TaskCanceledException in management libraries.

### ISSUE THREAD

**Issue by alexstoddard** [Azure/azure-sdk-for-net#1398]
We have been using the management libraries in the development of an IaaS automation solution. Through experience and documentation we have learned which exceptions are transient and which are fatal. In most cases, exceptions are specific enough. Some go so far as to indicate exactly when an operation can be retried. Recently in QA we observed an exception sourcing from the management libraries which we had not seen before: *TaskCanceledException*. 

I have looked at the available documentation and found no guidance on what to do in response to this exception. We noticed that they were clustered and occurred at a time when Azure was observed to be slow in responding. An initial theory was that these exceptions were simply manifestations of timeout.

To verify this, I inspected the management libraries. They internally use an HttpClient for requests, and the timeout is configured in the default constructor of the *ComputeManagementLibrary* like so:

```C#
public ComputeManagementClient()
{
    ...
    this.HttpClient.Timeout = TimeSpan.FromSeconds(300);
}
```

Which is then used in scenarios like this:

```C#
namespace Microsoft.WindowsAzure.Management.Compute
{
    internal partial class HostedServiceOperations : IServiceOperations<ComputeManagementClient>, IHostedServiceOperations
    {
        public async Task<HostedServiceListResponse> ListAsync(CancellationToken cancellationToken)
        {
            ...
            if (shouldTrace)
            {
                TracingAdapter.SendRequest(invocationId, httpRequest);
            }
            cancellationToken.ThrowIfCancellationRequested();
            httpResponse = await this.Client.HttpClient.SendAsync(httpRequest, cancellationToken).ConfigureAwait(false);
            ...
        }
    }
}
```

There seems to be some [confusion](https://social.msdn.microsoft.com/Forums/en-US/d8d87789-0ac9-4294-84a0-91c9fa27e353/bug-in-httpclientgetasync-should-throw-webexception-not-taskcanceledexception?forum=netfxnetcom) about whether the *HttpClient* will throw a *TaskCanceledException* on timeout, though anecdotally it seems that it does. The fact that the management libraries use HttpClient internally is something of an implementation detail, and the possibility that an undocumented behavior of the client is bubbling out would seem to be problematic.

Reproducing the issue is complicated by the fact that it is quite rare, but I have found that if you initialize the client with an impossibly short timeout, you get the same characteristic *TaskCanceledException*.

Given that the management libraries intend to distinguish transient conditions from fatal ones, should the exception be caught and re-framed to better reflect the root cause?

**Comment by devigned** [comment]
Great catch, and excellent write up. We'll investigate and see if we can repro.

**Comment by markcowl** [comment]
@alexstoddard This was fixed in the latest version of Hyak Common - please repopen the issue if you see a recurrence.
