### ISSUE TITLE
[BUG] DataLakeFileSystemClient.GetDirectoryClient(string.Empty).Path is "" on "12.3.0-preview.1", and "/" on other version

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#13996]
**Describe the bug**
Run following code , the 'rootDirPath' value will change on different "Azure.Storage.Files.DataLake" version:
```
string rootDirPath = new DataLakeFileSystemClient(new Uri("https://accoutname.blob.core.windows.net/filesystem1/"))
                .GetDirectoryClient(string.Empty).Path;
```
- 12.0.0, 12.2.2: "/"
- 12.3.0-preview.1: ""
- 12.3.0-preview.2: "/"

It seems a regression on "12.3.0-preview.1" , and fixed on "12.3.0-preview.2".

As PSH depends on this value to decide if a DataLakeDirectoryClient object is root directory, the regression on "12.3.0-preview.1" takes the PSH issue https://github.com/Azure/azure-powershell/issues/12553

To avoid this kind of issue happen in Powershell again, would you please help to confirm:

-  What's the value of DataLakeDirectoryClient.Path on a root directory (Or what's the best way to decide if a DataLakeDirectoryClient object point to root directory)

**Expected behavior**
The 'rootDirPath' value should always be "/"

**Actual behavior (include Exception or Stack Trace)**
The 'rootDirPath' value is "" on "12.3.0-preview.1", and "/" on other version

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Run the above code.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Files.DataLake 12.3.0-preview.1] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by blueww** [comment]
Would you please help to confirm:

- What's the value of DataLakeDirectoryClient.Path on a root directory (Or what's the best way to decide if a DataLakeDirectoryClient object point to root directory)

**Comment by seanmcc-msft** [comment]
Path is set to "/" by design.   `DataLakeFileSystemClient.GetDirectoryClient(string.Empty)` refers to the file system's root directory, who's path is "/".

**Comment by blueww** [comment]
@seanmcc-msft 
Thanks for the confirmation!
Would you please kindly point out the test case to validate the Path is "/" on the root directory, to avoid this kind regression happen again？
