### ISSUE TITLE
[FEATURE REQ] Support Batch Read/Write for Azure.Storage.Blobs.Batch

### ISSUE THREAD

**Issue by LukeBolly** [Azure/azure-sdk-for-net#13990]
**Library or service name.**
Azure.Storage.Blobs.Batch
 
**Is your feature request related to a problem? Please describe.**
Batch support for read and write operations would reduce network load for applications which service multiple files at once. Currently the API only supports one file per request, which can cause needlessly chatty applications.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Right now the Blobs Batch REST API is limited to SetBlobTier and DeleteBlob
https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch#:~:text=The%20Blob%20Batch%20operation%20allows,each%20subrequest%20in%20the%20batch.

I will add on the feature request tag, and we will look to routing this feature request to the correc team.

**Comment by amnguye** [comment]
Since this is a request on the service and not on the SDK, we will close this for now and if the service adds on this feature onto Blob Batch we will look to add it to the SDK.
