### ISSUE TITLE
Update Analyzers for .NET projects

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#13998]
I added a namespace to the list of allowed namespaces, for projects that participants of the Azure SDK Training series will create.

See: https://github.com/Azure/azure-sdk-tools/pull/729

We'll need to apply these to all .NET projects in the repo (Azure.Template at a minimum) so that they take effect on training projects.

**Comment by AlexanderSher** [comment]
Currently analyzers package is newer than required.

**Comment by annelo-msft** [comment]
@AlexanderSher I'm still seeing this error:

![image](https://user-images.githubusercontent.com/21269347/90180992-9b49e200-dd64-11ea-88c1-704868b8ab3a.png)

Even though I updated the analyzer in this PR: https://github.com/Azure/azure-sdk-tools/pull/729

What makes you think the current analyzers package is up to date?
