### ISSUE TITLE
[QUERY] Method to retrieve DeploymentOperations info for a Subscription scope deployment?

### ISSUE THREAD

**Issue by 1RedOne** [Azure/azure-sdk-for-net#13991]
**Query/Question**
Hi!  I am looking for a sample or pointer to reretrieving a DeploymentOperation (list of the deployed resources) for a SubscriptionScope deployment.  I'm doing a deployment using the 

```
var deployment = azure.Deployments.Inner.BeginCreateOrUpdateAtSubscriptionScopeAsync("myCoolDeploymentName", deploymentParam).Result;
var deploymentInfo = await azure.Deployments.Inner.GetAtSubscriptionScopeWithHttpMessagesAsync(deployment.Name);            
```

The deployment works but I can't find how to retrieve the list of deployed resources using the SDK (I need to not use preview bits).

Thanks for any pointers.

**Environment:**
* Microsoft.Azure.Management.Fluent, V 1.34.0
* Azure App Service
* Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help on this? thanks

**Comment by 1RedOne** [comment]
Figured it out,

```
 var deployments = client.DeploymentOperations.ListAtSubscriptionScopeAsync("Automanage-DefaultResourceGroup-EAP-centraluseuap-Backup").Result;
           
```
