### ISSUE TITLE
Stress and Stability Testing

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#14000]
# Summary

In order to ensure that the Event Hubs client libraries perform consistently within customer expectations and standards established by the general availability release, periodic runs through the sustained exiting stress test harness should be performed.  Data gathered as part of the previews should be used to adapt or extend scenarios and ensure that the sustained runs are focused on the right criteria and metrics.  The results of the runs should be used to drive any necessary work to ensure that future previews and general releases meet the desired quality and performance bars.

# Scope of Work

- Revisit the patterns used within the stress harness to ensure they are consistent with the current library API surface and the recommended usage scenarios.  Any gaps or adjustments identified should be addressed.

- Perform as many runs as possible using a 72 hour target; during at least one of these runs, there should be efforts made to introduce transient issues around network connectivity as a means of ensuring the client library recovers as expected.

- The correctness and resilience of the client library should be monitored and validated; any defects uncovered should be addressed within the time box allotted for this work or a new issue should be created to track it.

# Success Criteria

- The stress harness is an accurate representation of real-world usage scenarios for the Event Hubs client library.

- At least two stress runs of 72 hours or more have been performed, with the client correctness and resiliency validated.

- Any defects uncovered by stress testing have been corrected and have test coverage, time permitting.  For those unable to be addressed in the time box allotted, a new issue should be created and its priority determined and recorded.

- The tests necessary for to validate any changes made have been created or existing tests have been adjusted and pass reliably.

- The existing suite of tests continues to produce deterministic results and pass reliably.

**Comment by KPixel** [comment]
Hi
What's the outcome of this issue? I don't see any reference to what closed it.

**Comment by jsquire** [comment]
Hi @KPixel.  This was closed because the work it was tracking has been completed.   Success criteria can be found in the description of the issue.   Was there something specific that you were interested in on this topic?

**Comment by KPixel** [comment]
I mean that I don't see any pull request / commit referencing it.

I am interested in studying how you implemented this stress testing.

**Comment by jsquire** [comment]
Unfortunately, the stress framework that we're leveraging at the moment is a an internal system that is not available publicly.   For what it's worth, an updated  and open source framework for stress and performance testing across the Azure SDKs is on the roadmap though I do not have visibility into it's scheduling.   The closest tracking issue that I can find is in the main [Azure SDK repository](https://github.com/Azure/azure-sdk), [#227](https://github.com/Azure/azure-sdk/issues/227), though that appears to have been repurposed a few times.    

Commenting there would likely be the most effective venue to offer feedback or ask questions.

**Comment by KPixel** [comment]
Thank you for the information.
I will subscribe to that issue.
