### ISSUE TITLE
Consider removing EntityNameFormatter

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#14008]
FormatTransferDeadletterQueue can be built into the CreateDeadLetterReceiver method by adding an optional param.

**Comment by SeanFeldman** [comment]
Transactional dead-letter queue name should be considered as well.

**Comment by JoshLove-msft** [comment]
> Transactional dead-letter queue name should be considered as well.

Do you mean the transfer dead letter queue? That's what I was referring to when mentioning the `FormatTransferDeadletterQueue` method in the issue description.

**Comment by SeanFeldman** [comment]
Yes, indeed.

**Comment by JoshLove-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/14692
