### ISSUE TITLE
Update package description for Microsoft.Azure.ServiceBus library

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#14004]
# Summary

The current package description for `Microsoft.Azure.ServiceBus` on [NuGet](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/) begins with the text "This is the next generation Azure Service Bus .NET Standard client library..." which helped to differentiate it from its predecessor.   

Once the `Azure.Messaging.ServiceBus` library is released for GA, it will be the recommended version for developers to choose.  The phrase `next generation` used for `Microsoft.Azure.ServiceBus` will then no longer be accurate and is likely to cause confusion for developers browsing NuGet.  

# Scope of Work

- Update the package description for `Microsoft.Azure.ServiceBus` defined in its `.csproj` file to update the text.  Recommended would be to change `next generation` to `legacy` - which aligns with the terminology agreed upon with the Azure Messaging team when discussing the Event Hubs GA.

# Success Criteria

- The package description for the `Microsoft.Azure.ServiceBus` package has been updated in the repository.

# Out of Scope

- Releasing the `Microsoft.Azure.ServiceBus` library;  the package description does not warrant a dedicated release.

**Comment by JoshLove-msft** [comment]
This was fixed in https://github.com/Azure/azure-sdk-for-net/pull/20402
