### ISSUE TITLE
Changelog entry check fail very late

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14041]
Instead of failing during build the check fails during package publish.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=486378&view=logs&j=9ad38fe2-79d5-526b-2a81-c8fed88974e0&t=546b959d-e62a-5ea3-552a-1e5f62f3e99d

cc @chidozieononiwu @weshaggard 
![image](https://user-images.githubusercontent.com/1697911/89655287-bc02cb00-d87e-11ea-98ff-f731b014fd24.png)

**Comment by pakrym** [comment]
After thinking about this it can't be done earlier.

**Comment by weshaggard** [comment]
Exactly because we don't know which set of packages we plan to release.
