### ISSUE TITLE
[QUERY] Is Azure.Data.AppConfiguration supposed to replace Microsoft.Azure.AppConfiguration.AspNetCore?

### ISSUE THREAD

**Issue by pschaeflein** [Azure/azure-sdk-for-net#14055]
**Query/Question**
I see that Azure.Data.AppConfiguration contains a ConfigurationClient that can read/write entries in AppConfiguration. However, it does not have the IConfiguration provider class/methods I would expect to plug into an ASPNET Core application.

**Environment:**
 - Azure.Data.AppConfiguration 1.0.1 
 - DotNet 3.1 / AzureAppService 
 - Visual Studio 16.6.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
No, the Azure.Data.AppConfiguration is a pure service client and the Microsoft.Azure.AppConfiguration.AspNetCore is an ASP.NET Core integration layer that builds on top of Azure.Data.AppConfiguration library. They both would exist.
