### ISSUE TITLE
Binary Data UX Study

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#14052]
Tracks the work that goes into preparing for UX study.

**Comment by SeanFeldman** [comment]
Could you please provide the details of the customer segments? I.e. what percentage are .NET existing Track 0/1 users, how many are novice users w/o previous ASB experience, etc. Thank you.

**Comment by JoshLove-msft** [comment]
There were 5 participants, all experienced with Azure, Service Bus SDK, and Blob Storage SDK, with 4+ years of .Net experience

**Comment by JoshLove-msft** [comment]
UX study was completed, we got a lot of positive feedback, and have made some changes based on the study in https://github.com/Azure/azure-sdk-for-net/pull/14500
