### ISSUE TITLE
Documentation for QueueServiceClient needs to have an example using SAS Uris

### ISSUE THREAD

**Issue by joebeernink** [Azure/azure-sdk-for-net#14056]
The documentation for QueueServiceClient needs to have an example using SAS Uris. Older methods used to take the SAS token as a separate parameter. It's not intuitively obvious to devs migrating from old versions to new versions that the SAS token needs to be appended to the Uri passed in to the constructor now.

**Comment by jongio** [comment]
The Uri example here: https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueserviceclient.-ctor?view=azure-dotnet#Azure_Storage_Queues_QueueServiceClient__ctor_System_Uri_Azure_Storage_Queues_QueueClientOptions_

Only have the service uri. Let's add a Sas example and maybe update the description to be super clear that you can pass a Uri with sas.

**Comment by jsquire** [comment]
Hi @joebeernink.  Thank you for your feedback and sorry to hear that you're running into difficulties.  I'm tagging this up and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
We can resolve this, it is a simple fix.

**Comment by JimSuplizio** [comment]
Hi @joebeernink, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
