### ISSUE TITLE
TestResources tenantId requirement

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#14069]
The [README](https://github.com/Azure/azure-sdk-for-net/blob/master/eng/common/TestResources/README.md) for TestResources has this snippet:
```powershell
Connect-AzAccount -Subscription 'YOUR SUBSCRIPTION ID'
$sp = New-AzADServicePrincipal -Role Owner
eng\common\TestResources\New-TestResources.ps1 `
  -BaseName 'myusername' `
  -ServiceDirectory 'search' `
  -TestApplicationId $sp.ApplicationId `
  -TestApplicationSecret (ConvertFrom-SecureString $sp.Secret -AsPlainText)
```
Running this snippet will not work as is since the user will be prompted to enter the `tenantId`, since the test-resources.json requires it (it appears that all test-resources.json files require tenantId even if they are not using it). If the user tries to include the tenantId as an argument, then they are prompted to include the `ProvisionerApplicationId`, due to these parameters being in the same parameter set. It doesn't seem like `tenantId` is actually needed when not specifying `ProvisionerApplicationId`. It is computed from the context for the [output](https://github.com/Azure/azure-sdk-for-net/blob/master/eng/common/TestResources/New-TestResources.ps1#L317), and it seems like this can be done as well for the value that is passed to test-resources.json. 

To sum it up - is it possible to just pass the context.Tenant.Id to the test-resources.json script so that users will not be prompted for it unless they are also including `ProvisionerApplicationId`?

**Comment by heaths** [comment]
I use this snippet all the time for Key Vault and Search. Never once prompted for tenant ID. test-resources.json can hardcode a default, which is what I did for Key Vault and Search both. Ideally, we want customers to have to pass fewer arguments.

**Comment by JoshLove-msft** [comment]
> I use this snippet all the time for Key Vault and Search. Never once prompted for tenant ID. test-resources.json can hardcode a default, which is what I did for Key Vault and Search both. Ideally, we want customers to have to pass fewer arguments.

What default value would you hard-code? My understanding is that the New-TestResources script will always have access to the tenantId from the context, so I don't see a need to hardcode a default if we can update the script to use the context.Tenant.Id.

**Comment by JoshLove-msft** [comment]
Moving to tools repo - https://github.com/Azure/azure-sdk-tools/issues/861
