### ISSUE TITLE
[QUERY] Sample for client side encryption?

### ISSUE THREAD

**Issue by ahofman** [Azure/azure-sdk-for-net#14071]
**Query/Question**
Hi there, 
I am trying to use the new client side encryption for blob storage. A working code sample would be very helpful in getting started. Is there a working code sample you can point me toward?

I'm mostly interested in some examples of configuring a `ClientSideEncryptionOptions`  : 

```
var options = new Azure.Storage.ClientSideEncryptionOptions(Azure.Storage.ClientSideEncryptionVersion.V1_0);
            options.KeyEncryptionKey = ? // I need a key from KeyVault - is there an easy out of the box way to wire this up?
            options.KeyResolver = ? // I just need one that talks directly to KeyVault - is there an out of the box thing I can use?
            options.KeyWrapAlgorithm = ? // Can I use the algorithms defined in https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.webkey.jsonwebkeysignaturealgorithm?view=azure-dotnet-legacy ?
```

Thanks in advance!

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.5.0-preview.6 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.302\

Host (useful for support):
  Version: 3.1.6
  Commit:  3acd9b0cd1

 - IDE and version : Visual Studio 16.6.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Thanks for the feedback! We will definitely look to add a sample for Client Side Encryption for Queues.

To upload, you would only need the `options.KeyEncryptionKey` and `options.Algorithms`. Sorry there's no "out of the box solution" that I know of for this. The Key you would have to retrieve from Key Vault and the algorithm you decide on depends on the data you are trying to encrypt.  I would follow one of the tutorials on how to create one. I've linked one below
https://docs.microsoft.com/en-us/azure/storage/common/storage-encryption-keys-powershell?toc=/azure/storage/blobs/toc.json

Here's a quick sample I whipped up.
```
                 QueueClient queue = new QueueClient(queueUri, new ClientSideEncryptionOptions(ClientSideEncryptionVersion.V1_0)
                 {
                         KeyEncryptionKey = s_mockKey,
                         KeyWrapAlgorithm = s_algorithmName
                 });
                 // upload with encryption
                await queue.SendMessageAsync(message1, cancellationToken: s_cancellationToken); // invokes key wrap first time

                // download and update message
                var messageToUpdate = (await queue.ReceiveMessagesAsync(cancellationToken: s_cancellationToken)).Value[0];
                await queue.UpdateMessageAsync(messageToUpdate.MessageId, messageToUpdate.PopReceipt, message2, cancellationToken: s_cancellationToken); // invokes key unwrap first time and key wrap second time

                // download with decryption
                var receivedMessages = (await queue.ReceiveMessagesAsync(cancellationToken: s_cancellationToken)).Value; // invokes key unwrap second time
                Assert.AreEqual(1, receivedMessages.Length);
                var downloadedMessage = receivedMessages[0].MessageText;
```

Let's leave this issue open for now until we create the sample for Queue Client Side Encryption.

**Comment by ahofman** [comment]
Thanks @amnguye ! I'm specifically interested in Blobs rather than Queue storage. It's my understanding I need the `KeyResolver` to be set to be able to download encrypted content - can you provide any quick guidance for that please? Much appreciated!

**Comment by amnguye** [comment]
Definitely my bad! Sorry I somehow misread Query as Queue.

Yes, you do need a KeyResolver to download encrypted content. The KeyResolver you pass will depend on how you encrypted the content in the first place. So depending on the Key you chose in Key Vault to encrypt your data with, you will need to provide a key resolver that resolves to the right key (the key you encrypted with) or the key itself.

Here's a short sample of that
e.g.
```
ClientSideEncryptionOptions options1 = new ClientSideEncryptionOptions(ClientSideEncryptionVersion.V1_0)
{
     KeyResolver = GetKeyResolver()
};
BlobClient blobClient = new BlobClient(
                connectionString,
                containerName,
                blobName).WithClientSideEncryptionOptions(options1);
blobClient.DownloadTo(downloadFilePath);
```

**Comment by ahofman** [comment]
Thanks @amnguye - is there any out-of-the-box implementation of a key resolver that I can use to talk directly to key vault? I am guessing the answer for now is no, I just want to be sure before I go ahead and try to roll my own.

**Comment by amnguye** [comment]
Sorry I don't think there is. Let me know on this thread if you need any help.

**Comment by ahofman** [comment]
No problem! I have fallen back to using the old blob client library for now because it has the tight integration with KeyVault out of the box that I'm looking for. Thanks for your help :)

**Comment by amnguye** [comment]
Hi. If you could be so kind, could you link me the "tight integration with KeyVault out of the box" you are looking for? I under the impression when you said "out of the box" you meant that I provide you a sample Key Vault Key, Resolver just to see if it works. I just want to be on the same page that way I can provide you the information you need in case I did not provide it for you to switch to this library.

**Comment by ahofman** [comment]
I'm referring to the out of the box `KeyVaultKeyResolver` that I can use with the old library. Details on this can be found here: 
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-encrypt-decrypt-blobs-key-vault

**Comment by lcitton** [comment]
I fully agree with ohofman, we definitely need something similar to the old BlobEncryptionPolicy to proivide client side encryption.

**Comment by amnguye** [comment]
Hi, I don't think thats what ahofman ask was. His ask was for a sample of the v12 way to provide client side encryption, not to redo client side encryption the way the v11 library has it.

Also ahofman, we currently have an "out of the box solution" in the works, which is similar to the link. I was under the impression you were looking for a runnable sample without having to create a Key in KeyVault. You still have to provide your own encryption key, or resolver (Respectively) in order to encrypt and decrypt your blobs in the link you provided. I was wondering what you actually mean by "out of the box" solution, so we can better tailor our samples to your scenario.

**Comment by lcitton** [comment]
Hi Amanda, 
I may have misundertood ahofman request... But I still think we miss a way to encrypt/decrypt blobs client-side, able to cope with files already encrypted and stored in blobs.

Another question : we have a legacy project running in framework 4.8 and I cannot find the "WithClientSideEncryptionOptions' method mentioned in your snippet. Is it reserved to .net core library ?

**Comment by amnguye** [comment]
@jaschrep-msft For the clientside encryption design question

As for the WithClientSideEncryptionOptions, I believe this is in preview. What version are you using? I believe we released it in 12.5.0.preview.1+

**Comment by lcitton** [comment]
We are currently using 12.5.1.0 version for .net framework 4.8. It is not present in the 12.6.0 release either.

**Comment by jaschrep-msft** [comment]
Apologies for just now replying.

The API surface changed over the course of the previews. `WithClientSideEncryptionOptions` did not make it into the final release. There is currently a tracked documentation gap for discovering the API released in 12.6.0, but the API docs are still available. The hook for attaching [client side encryption options](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.clientsideencryptionoptions?view=azure-dotnet) is in an extension of BlobClientOptions, found [here](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.specializedblobclientoptions?view=azure-dotnet). The options class should be very similar to the collection you're used to in v11.

Regarding already existing keyvault implementations, those were never a part of the storage library in v11 or v12. Keyvault publishes packages that fit the interfaces we incorporate into storage libraries, and you can use them as your providers. Their implementations are [`CryptographyClient`](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.cryptography.cryptographyclient?view=azure-dotnet) and [`KeyResolver`](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.cryptography.keyresolver?view=azure-dotnet).

**Comment by lcitton** [comment]
Thanks a lot for the link to the extension of BlobClientOptions.

First tests I have made let me think that it works perfectly :-)

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
