### ISSUE TITLE
[FEATURE REQ] Enable a way to Unregister Message Handler 

### ISSUE THREAD

**Issue by DorothySun216** [Azure/azure-sdk-for-net#14077]
**Library or service name.**
What library or service is this request related to? 
First we need it in Microsoft.Azure.ServiceBus, then we hope to apply to all service bus SDKs.
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
Azure function team requested this feature.

We hope to gather more opinions on whether we want a Force Unregister (abort inflight receives) or a Soft Unregister (customer may experience a buffer until the handler is actually unregistered. ) My thought currently is for choosing the Soft Unregister since if customer wants a more destructive way, they can achieve it by closing down the receiver. But also understand that Soft Unregister might need some clarification in documentation to avoid customer confusion.

**Comment by JoshLove-msft** [comment]
This feature is available in Track 2 in the ServiceBusProcessor with the [StopProcessingAsync](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs#L555) method.

**Comment by DorothySun216** [comment]
@JoshLove-msft Thanks for this info but I think we want to also enable it in our SDKs since current customers who haven't used Track 2 need this feature as well.

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft Thanks for this info but I think we want to also enable it in our SDKs since current customers who haven't used Track 2 need this feature as well.

Sure, just wanted to provide that info 😃

**Comment by axisc** [comment]
This issue is unnecessary - closing it because this discussion will be managed on the PR where the feature ask is coded.
