### ISSUE TITLE
[text analytics] add bing ID property for LinkedEntity

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-net#14091]

**Comment by maririos** [comment]
Blocked until service adds property to swagger

**Comment by maririos** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/10440.
Why have a separate property and not use `LinkedEntity.Id`?

**Comment by maririos** [comment]
BingId is used to find the entity in the Microsoft graph using the Bing Entity Search (BES) AP
It is for more advanced users

**Comment by maririos** [comment]
Because of how specific it is, I'm proposing going with `BingSearchAPIID` instead of `BingID` to make sure the user knows that this is not for everyone and that it is "complicated" enough that unless they need it, they shouldn't care

**Comment by maririos** [comment]
There are more Bing APIs https://docs.microsoft.com/en-us/azure/cognitive-services/bing-web-search/bing-api-comparison?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fcognitive-services%2Fbing-autosuggest%2Ftoc.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json 
which makes us more convinced that being specific about the name of the service is the way to go
