### ISSUE TITLE
[Flaky Test] Microsoft.Azure.ServiceBus.UnitTests.QueueSessionTests.AcceptSessionThrowsSessionCannotBeLockedException

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#14113]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=490068&view=ms.vss-test-web.build-test-results-tab&runId=12522322&resultId=100486&paneView=debug

**Comment by jsquire** [comment]
Closing; this is regarding T1 tests.
