### ISSUE TITLE
[BUG] Reference docs for preview packages appearing under the "latest" moniker

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#14114]
Below is a screenshot from https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus?view=azure-dotnet is the link to the reference docs for the Track 1 Service Bus package.

<img width="320" alt="Screen Shot 2020-08-10 at 7 14 00 PM" src="https://user-images.githubusercontent.com/16890566/89849585-ab33ad00-db3d-11ea-9125-c205d0ded623.png">

In this TOC, you can see `Azure.Messaging.ServiceBus` and `Azure.Messaging.ServiceBus.Management` which are from the newer Track 2 Service Bus package which is currently in preview.

The reference docs for the preview packages should not be appearing under the "latest" moniker.

cc @scbedd

**Comment by scbedd** [comment]
Yeah. Technically not a "bug". It's a factor of how the repo is built. I filed an [issue](https://ceapex.visualstudio.com/Engineering/_queries/edit/267447/?triage=true) a couple weeks ago to get some help getting the `JoinToCPlugin` configured.

If it were a simple ToC rework I'd absolutely resolve this immediately.

**Comment by danieljurek** [comment]
There may be a couple ways to "monikerize" the .net docs repo. I'll have to do some research.

**Comment by ramya-rao-a** [comment]
It has been over a year since the issue was logged and the preview packages in question are no longer in preview. Am ok if we close this issue

**Comment by kurtzeborn** [comment]
Obsolete.  We've implemented monikerization in .NET since this was opened.
