### ISSUE TITLE
[QUERY] use arm token to genarate IAzure

### ISSUE THREAD

**Issue by Emma0727** [Azure/azure-sdk-for-net#14121]
**Query/Question**
How can we help?
Recently our scenario is that we got an arm token(on hehalf of user token), and we use the following code to generate IAzure. 
```
                var tokenCredentials = new TokenCredentials(armToken);
                var azure = Azure
                    .Configure()
                    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                    .Authenticate(new AzureCredentials(
                        **tokenCredentials,
                        tokenCredentials,**
                        organizationId,
                        AzureEnvironment.AzureGlobalCloud))
                    .WithSubscription(subscriptionId);
```

We use this IAzure to do role assignment like following code:
```
                        azure 
                        .AccessManagement
                        .RoleAssignments
                        .Define(SdkContext.RandomGuid())
                        .ForObjectId(firstPartyServicePrincipalId)
                        .WithBuiltInRole(BuiltInRole.Owner)
                        .WithResourceGroupScope(resourceGroup)
                        .Create();
```

My code can be work now. But we have a concern about the code as we only used arm token to generate IAzure without graph token here. Not sure if this is a bug in SDK. We are afraid someday if SDK updated， these code can not work well any more. Is there any suggestion for me to make my code stronger? Is there any public method to use only with arm token??

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.mangement.fluent 1.34.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Emma0727** [comment]
any update?

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help on this? thanks

**Comment by xccc-msft** [comment]
@Emma0727 We do not have plan to update this part of code in our SDK now.  Add `Azure.Identity` so the identity team can help answer if any future plan to change it. Thanks.

**Comment by christothes** [comment]
This doesn't appear to be related to the Azure.Identity client library. @xccc-msft - could you clarify how we can help here?

**Comment by xccc-msft** [comment]
@christothes The client runtime authentication library should be in maintenance mode. For the concern from @Emma0727, it would better to learn the plan of Azure.Identity and adopt to new SDK later.

**Comment by weidongxu-microsoft** [comment]
New SDK at https://aka.ms/azsdk/dotnet/mgmt
