### ISSUE TITLE
DefaultAzureCredential, AppAuthentication and user defined managed identity

### ISSUE THREAD

**Issue by PaulVrugt** [Azure/azure-sdk-for-net#14122]
**Query/Question**
We're using a user defined managed identity to authenticate different azure services from our app service. We are using the `AppAuthentication` package to support `Active directory interactive` authentication to Azure SQL. After a long time of fiddling, we found out we need to use the `AzureServicesAuthConnectionString` environment variable to let the `AppAuthentication` package know what user defined managed identity to use (we're still in the dark as why it is possible to determine multiple user defined managed identities, but that is a query for another day). 

Now we used to use the `Microsoft.Azure.KeyVault` package to access the keyvault, and this package played nice with the `AppAuthentication` package. We got secrets from the KeyVault with code like this:

```
var tokenProvider = new AzureServiceTokenProvider();
using (var kvc = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(tokenProvider.KeyVaultTokenCallback)))
{
  return await kvc.GetSecretAsync(keyValueUrl, "ASecret")).Value;
}
```

Since this nuget package is deprecated, we moved to `Azure.Security.KeyVault.Secrets`. However, this new package doesn't seem to have any integration with the `AppAuthentication` package. Apparently we need to use the `DefaultAzureCredential` class as authentication. The code we currently use is:
```
SecretClientOptions options = new SecretClientOptions()
{
  Retry = {
    Delay= TimeSpan.FromSeconds(2),
    MaxDelay = TimeSpan.FromSeconds(16),
    MaxRetries = 5,
    Mode = RetryMode.Exponential
  }
};
var client = new SecretClient(AzureKeyVaultUrl, new DefaultAzureCredential(), options);
var keyVaultSecret = client.GetSecret(name, version).Value;
return keyVaultSecret.Value;
```

However, this seems to require me to set the `AZURE_CLIENT_ID` environment variable to determine the identity to use. By using this new package, do we really need to store the used identity in both the `AzureServicesAuthConnectionString` and `AZURE_CLIENT_ID`? We don't want to store the same settings in multiple places. Is there a better way to do this?

**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Secrets 4.0.3, Microsoft.Azure.Services.AppAuthentication 5.0.0
 - Hosting platform: Azure AppService
 - IDE and version : Visual Studio 16.7 (not relevant)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
The `DefaultAzureCredential` tries a series of different authentication methods in [order](https://github.com/Azure/azure-sdk-for-net/blob/3b184d4574b9d7759861fe9628ff04d8692b5727/sdk/identity/Azure.Identity/src/DefaultAzureCredential.cs#L18-L24). @schaabs would they have to write their own credential to use the connection string, or is there some easier way?

**Comment by PaulVrugt** [comment]
If I'm required to write my own credential to accomplish the same, it would be a significant step back from the old package. I think the better solution would be to make the new `Azure.Security.KeyVault.Secrets` package play nice with `AppAuthentication` to restore compatibility.

Even better would be to make setting a user defined managed identity an an app service similar to enabling a system assigned managed identity (without having to set extra environment variables to specify WHICH user defined managed identity to use), but I don't think this last part is something that can be accomplished in the SDK.

**Comment by schaabs** [comment]
@PaulVrugt Thanks for reporting this issue, and sorry for the inconvenience here. We are currently in a state of transition with the Azure SDK. The `AppAuthentication` library is being deprecated and replaced with the `Azure.Identity` library, but we're in the process of transitioning all the SDK libraries. We have plans to support Azure SQL AAD authentication via `Azure.Identity` later this year, but it's not currently available. 

In the meantime we have created some sample extension libraries that demonstrate how to use `Azure.Identity` in libraries which currently only support legacy forms of authentication. It should be possible to use the `DefaultAzureCredential` to authenticate both clients, with a bit of temporary code. If you can give me a bit more information about how your creating your `SqlClient` and how your using the `AppAuthentication` library to authenticate the client, I should be able to point you at a sample that uses the `Azure.Identity` to authenticate the client.

**Comment by PaulVrugt** [comment]
@schaabs 

For authentication with sql server we used the [this doc](https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-connect-msi).

so we added a `SqlAuthenticationProviders` section to the web.config, and our connection string uses `active directory interactive` authentication.

To configure what user defined managed principal is used, we used the `AzureServicesAuthConnectionString` app setting, and set it to `RunAs=App;AppId=<client id of identity>`

we we followed [this acticle](https://www.rickvandenbosch.net/blog/managed-identity-part-ii/) which perfectly decribed how to use the appauthentication package to authenticate with different services using a managed principal. It would be very helpful if microsoft had a doc with a similar description using the new Azure SDK.

The only problem we now have, is that we need to specify the user defined managed principal in multiple places, because the `defaultazurecredential` doesn't look at the `AzureServicesAuthConnectionString` setting, and the `AppAuthentication` package doesn't look at the `AZURE_CLIENT_ID` setting

**Comment by Jawvig** [comment]
Would it be possible for `DefaultAzureCredential` constructor with no arguments to use the single User Assigned Managed Identity if there is only one assigned? This would bypass the need for setting the `AZURE_CLIENT_ID` environment variable (something I didn't know was a possibility until I read this thread) or passing the client id in via the `DefaultAzureCredentialOptions.ManagedIdentityClientId` in the `DefaultAzureCredential` constructor? 

The latter mechanism is the one the docs led me to believe we should do, which has led to a lot of complexity in the code and putting the client id into a configuration setting anyway. Docs reference: https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#specifying-a-user-assigned-managed-identity-with-the-defaultazurecredential

**Comment by Jawvig** [comment]
Just a follow up on my last comment:  `new DefaultAzureCredential()` work within an Azure Function with a single managed identity even with `AZURE_CLIENT_ID` set. When this is set, the error "Environment variables are not fully configured" is received, indicating that it's trying to use the `EnvironmentCredential` rather than the `ManagedIdentityCredential` under the covers. The only solution I've found is to use some custom environment variable to hold the ClientId of the Managed Identity and use the existence of that variable to work out which of the `DefaultAzureCredential` constructor overloads to use.

**Comment by christothes** [comment]
Closing this issue since we are tracking support for SQL auth in #12145
