### ISSUE TITLE
Azure SDK NuGet package not compatible with Universal App (win10 UWP)

### ISSUE THREAD

**Issue by NNM11** [Azure/azure-sdk-for-net#1413]
I try to create a C# Universal EventHub client app / an IoT Core Background App.   When I use the NuGet manager to install the Azure Service Bus package (version 3.1) to the project, the tool returned error Incompatible.

Is the Azure SDK supported Universal (Win 10 UWP) apps anytime soon?   

Thx,

**Comment by devigned** [comment]
This is in our backlog and we are working towards this in an upcoming release.

**Comment by BrianVallelunga** [comment]
Will this include .NET CoreCLR support as well?

**Comment by devigned** [comment]
Yes, this will include CoreCLR support.

@NNM11 I may have misspoke about the Azure Service Bus package as it's not one of the libraries in this repository. @djrosanova might be able to comment on ServiceBus specifically.

**Comment by dls314** [comment]
@devigned and @djrosanova, I started looking for a WindowsAzure.ServiceBus project and got hopeful when I found this repository. Is there one somewhere?

**Comment by amigup** [comment]
Has the support of Azure Service Bus Relay released for UWP app?

**Comment by xied75** [comment]
:+1: why is this issue not even assigned a Milestone?

**Comment by markcowl** [comment]
@devigned Please assign to milestone appropriately for the priority of UWP 10

**Comment by boblautenbach** [comment]
Any new updates on support for IoT Core ?

**Comment by xied75** [comment]
Hi, Team,

I can see that we now support .net standard 1.5, which is exactly one level up from supporting UWP according to the matrix here:
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

Is there any specific reason for doing this? Or is that we are going to have a new UWP version coming soon?

**Comment by devigned** [comment]
@xied75 many of the projects support .net standard 1.1 and 1.5. This is no indication of any future product release or change.

**Comment by xied75** [comment]
Hi @devigned 

That's not what I mean. On the home page https://github.com/Azure/azure-sdk-for-net, you have words saying

> Target Frameworks:

> .NET Framework 4.5
> Netstandard 1.5, based on the NetCore framework

So I thought everything here are now supporting netstandard 1.5, which is 0.1 bigger than what is needed for UWP, given the support for netstandard is new, I was wondering why you deliberately chosen 1.5 other than 1.4, and I thought you must have a good reason to do so, therefore I just guessed that there might be a new UWP version (newer than 10.0) which will align with 1.5.

**Comment by markcowl** [comment]
@aaronroney We need a PM assessment of how important UWP10 is and what we need to do to support it beyong having a netstandard 1.1 library

**Comment by aaronroney** [comment]
Will do, though I could run some tests to see how well generating a 1.4 netstandard library would work.

**Comment by twitchax** [comment]
@fearthecowboy is doing some preliminary investigation into targeting the lowest feasible netstandard version.  At present, 1.4 is the likeliest candidate.

**Comment by twitchax** [comment]
The .NET client libraries for Azure will be transitioning to .NET Standard 1.3 by mid-February.

[.NET Standard](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) 1.3 will support UWP 10.0+, so support for these application types should be implicit in our coming transition.

This transition is already underway, so this fix is approved for the current milestone.

**Comment by twitchax** [comment]
Assigned to @fearthecowboy for follow up and closing.

**Comment by markcowl** [comment]
Update - this is in progress as we speak and should be finished by 4/14: https://github.com/Azure/azure-sdk-for-net/issues/2815

**Comment by markcowl** [comment]
@shahabhijeet  Assignign to you so you cna close this when the VS2017 refactor is done.

**Comment by markcowl** [comment]
We don't own the azure servicebus package.  However, our management packages now support netstandard 1.4, which is compatible with UWP.
