### ISSUE TITLE
Expose public APIs to create ResponseFailedException

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#14142]
Today, to create ResponseFailedException that follows our guidelines requires shared source, i.e. for all practical purposes requires being in the mono repo. This makes it's impractical to use Azure.Core outside of our repo and the exception creation guidelines are very complex. 

We should design and expose public APIs to format the exception.

**Comment by pakrym** [comment]
We have a ctor that takes `Response` now.
