### ISSUE TITLE
[BUG] ChangeFeed, change GUID to string type

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#14149]
On the service, clientRequestId and other values are typed string and not GUID even though they should be in a GUID format. Changing to string will match the service type and have less restriction (side note clientRequestId should be optional)

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
