### ISSUE TITLE
[BUG] setting Storage Account Network DefaultAction not working

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-net#14169]
**Describe the bug**
Trying to set the Storage Account Firewall 
![image](https://user-images.githubusercontent.com/8554521/89984181-4c487200-dcbc-11ea-8e37-6f5350f3c502.png)

From "all networks" to "selected networks".
Equivalent `az` command would be 

```
az storage account update --name <storageaccount> --resource-group <rgName> --default-action Deny
```

**Expected behavior**
should change the value

**Actual behavior (include Exception or Stack Trace)**
nothing happens

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```
public static async Task RunAsync(IAzure azure, ILogger log)
        {
            var storageAccount = await azure.StorageAccounts.GetByIdAsync(ResourceId);
            storageAccount.Inner.NetworkRuleSet.DefaultAction = Microsoft.Azure.Management.Storage.Fluent.Models.DefaultAction.Deny;
            await storageAccount.Update().ApplyAsync();
        }
```

**Environment:**
 - Name and version of the Library package used: 
`<PackageReference Include="Microsoft.Azure.Management.Storage.Fluent" Version="1.34.0" />`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by davidobrien1985** [comment]
@allenjzhang do you already have an idea what is happening here?

**Comment by davidobrien1985** [comment]
@jsquire @allenjzhang any update on this please?

**Comment by jsquire** [comment]
Hi @davidobrien1985.   Unfortunately, I'm just first-line triage in this case and don't have visibility.  @m-nash or @markcowl - would you be able to assist with an update?

**Comment by davidobrien1985** [comment]
@m-nash @markcowl do you have an update for us?

**Comment by davidobrien1985** [comment]
@jsquire is there any way you can get anyone to help us here?

**Comment by jsquire** [comment]
Hi @davidobrien1985.   I'm sorry that  this has been lagging and we haven't been able to get you assistance.   

@AlexGhiondea, @lilyjma:  Can you help route and escalate?

**Comment by blueww** [comment]
@davidobrien1985 

It seems your problem is for [Microsoft.Azure.Management.Storage.Fluent](https://www.nuget.org/packages/Microsoft.Azure.Management.Storage.Fluent/).
If so, would you please raise your issue on correct project site: https://github.com/Azure/azure-libraries-for-net , then related team will come to help you.

SDK [Microsoft.Azure.Management.Storage](https://www.nuget.org/packages/Microsoft.Azure.Management.Storage/) is released from this repo, and it also support networkrule defaultaction. 
You can see how to update it with [Microsoft.Azure.Management.Storage](https://www.nuget.org/packages/Microsoft.Azure.Management.Storage/) SDK in https://github.com/Azure/azure-sdk-for-net/blob/693071ce198861750993f30da84400b40b159447/sdk/storage/Azure.ResourceManager.Storage/tests/Tests/StorageAccountTests.cs#L1192

**Comment by yungezz** [comment]
add @xccc-msft to help on this

**Comment by xccc-msft** [comment]
@davidobrien1985 For StorageAccount, the way you tried would not work. You need to try with below to update the property:
```csharp
StorageAccountUpdateParameters updateParameters = new StorageAccountUpdateParameters();
updateParameters.NetworkRuleSet.DefaultAction = Microsoft.Azure.Management.Storage.Fluent.Models.DefaultAction.Deny;
await storageManager.Inner.StorageAccounts.UpdateAsync("rgName", "saName", updateParameters, cancellationToken);
```

**Comment by davidobrien1985** [comment]
@ftd-xccc-mdy @blueww sorry for the super long delay. We finally managed to get back to this.

It's a bit unclear to me how to initialise the `storageManager` client which seems to require `ServiceClientCredentials` and won't take `Azure.Core.TokenCredential` or `Microsoft.Identity.Client`.

Can you elaborate on this and is this from the `Microsoft.Azure.Management.Storage;` package?

**Comment by blueww** [comment]
@davidobrien1985 
For the "storageManager" you refer, is it's from code shared from @ftd-xccc-mdy , if so it's from Microsoft.Azure.Management.Storage.Fluent package and @ftd-xccc-mdy should know more about it.

BTW, for  Microsoft.Azure.Management.Storage package, you can see how to use it (include how to input credential) from https://azure.microsoft.com/da-dk/resources/samples/storage-dotnet-resource-provider-getting-started/

**Comment by weidongxu-microsoft** [comment]
New SDFK at https://aka.ms/azsdk/dotnet/mgmt
