### ISSUE TITLE
What is the difference between DataLakeFileClient.Delete and DataLakeFileClient.DeleteIfExists

### ISSUE THREAD

**Issue by LeaShallev** [Azure/azure-sdk-for-net#14167]
Hi,
I'm using Azure.Storage.Files.DataLake .NET SDK (V12.2.2) with Visual Studio 2019.
I don't understand the diffference between the Delete and the DeleteIfExists methods for DataLakeFileClient except to the different return values for each of them.
I expect DeleteIfExists to delete the file if it exists and return true, and when the file doesn't exist to return false. Rather, both methods raise an exception when the file does't exist.
Can you please clarify this issue?
Thanks,
Lea.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by LeaShallev** [comment]
Hi @jsquire ,
Any update about it?

**Comment by jsquire** [comment]
Hi @LeaShallev.   Unfortunately, I don't have visibility once the initial triage is done.  This area is owned by the Storage team who have their own process around triage and support.   It looks as if @sumantmehtams would be the most likely individual to help understand the current status.

**Comment by sumantmehtams** [comment]
Adding @seanmcc-msft  to take a look.

**Comment by seanmcc-msft** [comment]
Hi @LeaShallev,

`DataLakeFileClient.Delete()` will throw an exception if the file doesn't exist, where `DataLakeFileClient.DeleteIfExists()` is supposed to return false.

Can you provide a code snippet for when you are seeing `DataLakeFileClient.DeleteIfExists()` throw an exception?

We have unit test coverage for these cases:

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.DataLake/tests/FileClientTests.cs#L390

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.DataLake/tests/FileClientTests.cs#L406

-Sean

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
