### ISSUE TITLE
[Azure Tables]Run tests against other clouds failed in Playback mode

### ISSUE THREAD

**Issue by XuGuang-Yao** [Azure/azure-sdk-for-net#14170]
We are running live tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

Currently, the test mode is set to `Playback` in [sdk/tables/Azure.Data.Tables/tests/TableClientQueryableLiveTests.cs](https://github.com/Azure/azure-sdk-for-net/blob/c3392eb75c1c95972aa87c312c9b895502f7e0c5/sdk/tables/Azure.Data.Tables/tests/TableClientQueryableLiveTests.cs#L24) .(BTW,changed by PR #13824) 

![image](https://user-images.githubusercontent.com/53599438/89983686-96c0f300-dcaa-11ea-85cf-8d0a90d79c20.png)

But the record json files are based on Azure Cloud, service endpoint's suffix is `table.cosmos.azure.com` or `table.core.windows.net`. This will casue match error happen when run the test cases in other clouds.

```
Message: 
    System.InvalidOperationException : Unable to find a record for the request POST https://<servicename>.table.cosmos.azure.us/Tables?$format=application%2Fjson%3Bodata%3Dfullmetadata
    Uri doesn't match:
        request <https://<servicename>.table.cosmos.azure.us/Tables?$format=application%2Fjson%3Bodata%3Dfullmetadata>
        record  <https://<servicename>.table.cosmos.azure.com/Tables?$format=application%2Fjson%3Bodata%3Dfullmetadata>
    Header differences:
    Body differences:
    
  Stack Trace: 
    RecordMatcher.FindMatch(RecordEntry request, IList`1 entries) line 125
    RecordSession.Lookup(RecordEntry requestEntry, RecordMatcher matcher, RecordedTestSanitizer sanitizer) line 88
    PlaybackTransport.Process(HttpMessage message) line 54
```
@jongio @danieljurek for notification.

**Comment by jongio** [comment]
@christothes

**Comment by christothes** [comment]
This will be resolved when https://github.com/Azure/azure-sdk-for-net/pull/14105 merges.

**Comment by jsquire** [comment]
Fixed by #14105

**Comment by christothes** [comment]
@XuGuang-Yao please validate that the current master branch resolves this issue.

**Comment by XuGuang-Yao** [comment]
@christothes Thank you for your help. The issue is resolved.
