### ISSUE TITLE
Can we make recording test mode switching easier

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14176]
Environment variable requires a restart
Changing the source is cumbersome and leads to people checking in the test mode.

What about allowing a `testmode.txt` file in the test project directory that would control test mode and not require VS restart?

cc @JoshLove-msft @christothes

**Comment by christothes** [comment]
I'd suggest we make it something like `testconfig.json` to allow for expansion of configuration options. But perhaps it's not good thing to encourage more general use cases.

**Comment by pakrym** [comment]
>But perhaps it's not good thing to encourage more general use cases.

That's exactly what I was thinking too, we have test environment for other stuff.

**Comment by JoshLove-msft** [comment]
> > But perhaps it's not good thing to encourage more general use cases.
> 
> That's exactly what I was thinking too, we have test environment for other stuff.

And I assume we just add this to the gitignore?

**Comment by pakrym** [comment]
>And I assume we just add this to the gitignore?

Yup

**Comment by pakrym** [comment]
cc @drwill-ms, you might be interested

**Comment by JoshLove-msft** [comment]
> > And I assume we just add this to the gitignore?
> 
> Yup

Makes sense to me. Would we remove the ctor overloads that take a RecordedTestMode? What about AZURE_TEST_MODE variable?

**Comment by pakrym** [comment]
> Would we remove the ctor overloads that take a RecordedTestMode?

I think they would be worth removing.

> What about AZURE_TEST_MODE variable?

Keep it, it overrides the file, same as with test resources.

**Comment by drwill-ms** [comment]
We made something like this for Azure.DigitalTwins.Core tests. Having it supported natively would be great.

I'd suggest considering leaving the ctor option in, and adding an enum value of Default or EnvironmentDecides. When I'm coding, I like to stay in code, but once I have code set up for everyone to use, and I've recorded output, then I want the code to indicate that.

**Comment by christothes** [comment]
Is this still an issue now that we have the `[RecordedTest]` attribute? (details [here](https://github.com/Azure/azure-sdk-for-net/blob/c5245ca2b8977ff0c206a2f654a377b6dce5fccd/sdk/core/Azure.Core.TestFramework/README.md#recorded-tests))

**Comment by pakrym** [comment]
I think it still is, what if you explicitly want to re-record everything?

**Comment by christothes** [comment]
> I think it still is, what if you explicitly want to re-record everything?

You could delete all existing recordings before running the tests to accomplish that.

**Comment by pakrym** [comment]
You also need to clean the project output.

**Comment by christothes** [comment]
> You also need to clean the project output.

True, but no code or config changes are required.

**Comment by drwill-ms** [comment]
We often want to run our tests live from our dev workstations, and not necessarily re-record. I might be debugging or something. Please don't make me do a bunch of filesystem tasks. I just want a simple, local, temporary way to switch my test mode.

**Comment by christothes** [comment]
Would it be sufficient if the existing ctor controls went unchanged, but that if we're running on a pipeline (`TF_BUILD == true`) that we override the mode sent to the ctor with the `AZURE_TEST_MODE` environment variable value? 

This has the following benefits:
- Inadvertently checking in the test mode has no side effects to CI
- No behavior or code changes required by anyone used to the current model

Concerns:
- Doesn't improve the ease of locally setting the mode (is this really a problem if checking in the change has no side effects?)

**Comment by pakrym** [comment]
I was thinking about a VS extension that just switches the environment variable for you.

**Comment by christothes** [comment]
What about for devs that use the command line or VSCode to run tests?

**Comment by pakrym** [comment]
We can add a command line parameter for the command line ones. Not sure what we can do with VS code.

**Comment by pakrym** [comment]
We've added the switch to https://github.com/Azure/azure-sdk-for-net/blob/main/eng/nunit.runsettings#L18 and another test to disable auto-rerecording. Please reopen if you have more improvement ideas.

**Comment by heaths** [comment]
> I was thinking about a VS extension that just switches the environment variable for you.

Likely wouldn't be enough. VS starts a lot of subprocesses - even for language and build services - and all those would have to be restarted, and restarting some of those would likely crash VS. Much the same for VSCode. Just best to avoid environment variables.
