### ISSUE TITLE
[QUERY] Querying Log Analytics Workspaces

### ISSUE THREAD

**Issue by chris5287** [Azure/azure-sdk-for-net#14180]
Is there a NuGet package for querying Log Analytics workspaces

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by shemers** [comment]
Hi @chris5287 
is [this](https://www.nuget.org/packages/Microsoft.Azure.OperationalInsights/) what you are looking for?

**Comment by chris5287** [comment]
[Microsoft.Azure.OperationalInsights](https://www.nuget.org/packages/Microsoft.Azure.OperationalInsights/) works well, just wondered if its going to get any ❤ as its been a preview release since 2018?

**Comment by shemers** [comment]
Hi @chris5287 
We have released a new SDK https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/stable/2020-08-01
