### ISSUE TITLE
Can't install Azure.Security.KeyVault.Secrets for NET Framework 4.6

### ISSUE THREAD

**Issue by youn123** [Azure/azure-sdk-for-net#14183]
**Query/Question**
Trying to install package `Azure.Security.KeyVault.Secrets 4.1.0`. Getting the following error:

```
Install-Package : Could not install package 'Azure.Security.KeyVault.Secrets 4.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

**Environment:**
 - `Azure.Security.KeyVault.Secrets 4.1.0`
 - Windows 10 .NET Framework 4.6
 - Visual Studio 16.8.0 Preview

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Azure.* packages target `netstandard2.0`, which is (mostly) equivalent to .NET Framework 4.6.1, or the TFM `net461`. See <https://docs.microsoft.com/dotnet/standard/net-standard#net-implementation-support> for more information.

You might consider upgrading your project to a newer version of .NET Framework. See <https://dotnet.microsoft.com/platform/support/policy/dotnet-framework> for the support lifecycle policy and information. Depending on what Windows OS versions you support, a newer version may be installed.
