### ISSUE TITLE
[FEATURE REQ]Add message state to Microsoft.Azure.ServiceBus.Message

### ISSUE THREAD

**Issue by Hwcverweij** [Azure/azure-sdk-for-net#14205]
**Library or service name.**
Library: Microsoft.Azure.ServiceBus
Class: Message
 
**Ability to get the message state (Active, Deferred or Schedules).**
The track 0 `Microsoft.Servicebus.Messaging.BrokeredMessage` has a `MessageState`. When moving to `Microsoft.Azure.ServiceBus.Message` it is not possible anymore to get the state. 

I don't know the rationale behind this decision or wherever this was just missed out by mistake. But it would be great if I can get somehow the state of the message.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by jsquire** [comment]
//cc: @ramya-rao-a, @richardpark-msft

**Comment by martyt** [comment]
Is there any update on this request? 

This seems like a pretty big hole in the current implementation -- specifically, it precludes searching for deferred messages for which the SequenceNumber may have been lost and is in direct conflict with recommended practices in the latest documentation: https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-browsing

**Comment by ramya-rao-a** [comment]
@axisc From what I recall, the message state feature is not something that is available in the AMQP implementation for Service Bus. Can you confirm?

**Comment by ramya-rao-a** [comment]
The message state feature is not available in the AMQP implementation for Service Bus.
The older `WindowsAzure.ServiceBus` used a different protocol and so was able to support this feature.

For the newer SDKs to support this, the service has to support this feature first.
https://github.com/Azure/azure-service-bus/issues is the repo where the service team takes in feature requests.

Related issues there are https://github.com/Azure/azure-service-bus/issues/442 and https://github.com/Azure/azure-service-bus/issues/95. Please participate in these issues to get input from the service team.

Closing this issue as there are no planned next steps from the SDK perspective.
