### ISSUE TITLE
[FEATURE REQ][Storage] Ability to receive ONE message from Queue

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#14211]
**Library or service name.**
Azure.Storage.Queues
 
**Is your feature request related to a problem? Please describe.**

I'm working with codebase written against V11 storage SDK, migrating to V12. There's a lot of code that tries to peek or receive just one message from the queue. The APIs available on `QueueClient` make this task kind of cumbersome, i.e. a lot of :
`(await _queue.ReceiveMessagesAsync(1)).Value.FirstOrDefault();`

Can we add APIs like `queue.ReceiveMessageAsync()` ?? And similar for Peek ?

**Comment by kasobol-msft** [comment]
@tg-msft Do you think it's a reasonable ask?

**Comment by tg-msft** [comment]
I think that makes a lot of sense.  We originally didn't for the sake of simplicity, but I've seen more and more folks having a bad time with this.  Let's just make sure we're aligned with what ServiceBus is doing too.  @JoshLove-msft - is SB adding an overload to return single messages?

**Comment by JoshLove-msft** [comment]
> I think that makes a lot of sense. We originally didn't for the sake of simplicity, but I've seen more and more folks having a bad time with this. Let's just make sure we're aligned with what ServiceBus is doing too. @JoshLove-msft - is SB adding an overload to return single messages?

Yes, SB has methods to receive a single message, a list of messages, or an IAsyncEnumerable of messages.

**Comment by tg-msft** [comment]
And it looks like ServiceBus is also calling it `ReceiveMessage` and `ReceiveMessages` per https://apiview.dev/Assemblies/Review/b5d7e3304000449c859c2016f718db52#Azure.Messaging.ServiceBus.ServiceBusReceiver.  

This plan sounds good to me.
