### ISSUE TITLE
[FEATURE REQ] AzureEventSourceListener should provide DisableAllEventSources to unsubscribe all EventSource 

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#14230]
`**Library` or service name.**
What library or service is this request related to? 
Azure.Core
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
AzureEventSourceListener enables some EventSources internally but does not expose these subscribed EventSources instances, so I have no way to pass in EventSource instance if want to disable all EventSources by calling DisableEventSources(EventSource). Expect provide one method DisableAllEventSources, otherwise I have to rewrite my own EventListener.

**Comment by pakrym** [comment]
AzureEventSourceListener is disposable, disposing it would unsubscribe from all the listeners.

**Comment by erich-wang** [comment]
I thought Dispose(), but I have concern whether it would cause ObjectDisposedException.
