### ISSUE TITLE
[BUG] ResourceGroupsOperations.CheckExistence returns Response instead of Response<bool>

### ISSUE THREAD

**Issue by AtOMiCNebula** [Azure/azure-sdk-for-net#14235]
**Describe the bug**
While taking a look at what it'd take to port from `Microsoft.Azure.Management.ResourceManager.Fluent` to `Azure.ResourceManager.Resources`, I noticed that the `ResourceGroupsOperations.CheckExistence`/`.CheckExistenceAsync` functions return `Response`, unlike the old SDK's version of the functions, which [returned `Response<bool>`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.iresourcegroupsoperations.checkexistencewithhttpmessagesasync?view=azure-dotnet).  I reverse engineered the code for the implementation, and it looks like the bool value returned is based on a [http status code check](https://github.com/Azure/azure-libraries-for-net/blob/07ece241182fea976cfbcd0882f3dc122e9baa1c/src/ResourceManagement/ResourceManager/Generated/ResourceGroupsOperations.cs#L222).  Any change the new libraries could be updated accordingly as well? :smile:

**Expected behavior**
New `ResourceGroupsOperations.CheckExistence`/`.CheckExistenceAsync` has similar return object semantics as prior SDK.

**Actual behavior (include Exception or Stack Trace)**
Raw (non-generic) `Response` is returned from API.

**To Reproduce**
```csharp
// Would be nice if the next line did not yield a compiler error :)
if (await resourceGroupsClient.CheckExistenceAsync("foo"))
{
    // ...
}
```

**Environment:**
 - Name and version of the Library package used: Azure.ResourceManager.Resources 1.0.0-preview.1 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET Core 3.1
 - IDE and version : Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AtOMiCNebula** [comment]
Abandoned my PR, as this will be addressed by https://github.com/Azure/autorest.csharp/pull/926 (which is a smarter approach than mine).  Now I wait for that SDK update to get picked up.  But, yay!! :smile:

**Comment by allenjzhang** [comment]
Thank you for the report. While the generated source code has been [updated](https://github.com/Azure/azure-sdk-for-net/blob/44425daf92f8d3e16c32763429f1925e9a825c0e/sdk/resources/Azure.ResourceManager.Resources/src/Generated/ResourceGroupsOperations.cs#L43), This change has not been released. We are currently working on an overall management plane API redesign and will release new preview libraries in the near future that would contain this change.  Thank you for your patience.
