### ISSUE TITLE
Receiving  WrappedStorageException and it is internal

### ISSUE THREAD

**Issue by fabiomaulo** [Azure/azure-sdk-for-net#1424]
For tests scope I'm using this code
    public static async Task< bool > ExistFile(string storageConnectionString, Uri blobName)
    {
        var account = CloudStorageAccount.Parse(storageConnectionString);
        var blobclient = account.CreateCloudBlobClient();
        var fullUri = blobclient.BaseUri.CombineRelative(blobName);
        try
        {
         var bref = await blobclient.GetBlobReferenceFromServerAsync(fullUri);
        }
        catch (StorageException e) when (e.RequestInformation.HttpStatusCode == (int)HttpStatusCode.NotFound)
        {
        return false;
        }
        return true;
    }

Instead the StorageException, when the blob does not exists, I'm receiving WrappedStorageException that is SDK internal so I can't manage it.

**Comment by devigned** [comment]
Thank you for reporting and we're sorry you ran into this. The Storage team has been alerted.

**Comment by mirobers** [comment]
This issue has been resolved long ago, but missed closing it because it's not in the azure-storage-net repo. Feel free to report further issues with the storage client in azure-storage-net. Thanks!
