### ISSUE TITLE
[FEATURE REQ] Support nullable for ManagementRecordedTestBase

### ISSUE THREAD

**Issue by memontic-ms** [Azure/azure-sdk-for-net#14253]
**Azure.ResourceManager.TestFramework**
 
**Is your feature request related to a problem? Please describe.**
ManagementRecordedTestBase cannot be used from a project with nullable enabled.

24  Error	CS8618	Non-nullable property 'CleanupPolicy' is uninitialized. Consider declaring the property as nullable.
28  Error	CS8618	Non-nullable property 'CleanupPolicy' is uninitialized. Consider declaring the property as nullable.
32  Error	CS8714	The type 'T' cannot be used as type parameter 'T' in the generic type or method 'Operation<T>'. Nullability of type argument 'T' doesn't match 'notnull' constraint.

**Comment by jsquire** [comment]
//cc: @pakrym, for awareness.

**Comment by jsquire** [comment]
@markcowl:  I believe that you intended to address this to @memontic-ms, as the author of this issue.
