### ISSUE TITLE
Remove azsdk-net- from User-Agent when the namespace is not in Azure.*

### ISSUE THREAD

**Issue by adrianhall** [Azure/azure-sdk-for-net#14250]
**Library or service name.**
What library or service is this request related to? **Azure.Core**
 
**Is your feature request related to a problem? Please describe.**

When using the Azure.Core library for a non-track-2 library (e.g. Microsoft.Zumo - the rewrite of the Azure Mobile Apps library), the User-Agent is set up as something like "azsdk-net-Microsoft.Zumo.MobileData/5.0.0-preview.1".  The azsdk-net- is not appropriate here since it's not an Azure track-2 library, even though it is using Azure.Core.

Minimally, I would expect the default user agent to drop the azsdk-net-, or exclude the telemetry policy.

Ideally, I'd be able to specify my own equivalent for azsdk-net-Microsoft.Zumo.MobileData so I don't have to exclude the telemetry policy.

**Comment by pakrym** [comment]
We haven't had more requests for this feature.
