### ISSUE TITLE
[QUERY] `Azure.Security.KeyVault.Keys  CryptographyModelFactory seems to be in a wrong namespace

### ISSUE THREAD

**Issue by erichillah** [Azure/azure-sdk-for-net#14259]
**Query/Question**
CryptographyModelFactory is under `Azure.Security.KeyVault.Keys` namespace while being in the `Azure.Security.KeyVault.Keys/src/Cryptography/` folder. Shouldn't the correct namespace be `Azure.Security.KeyVault.Keys.Cryptography` ?  Seems like it is also the only class using that namespace in the  Cryptography folder.

````c#
namespace Azure.Security.KeyVault.Keys
{
    /// <summary>
    /// Model factory that enables mocking for the Key Vault Cryptography library.
    /// </summary>
    public static class CryptographyModelFactory
    {
````
**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Keys v4.1.0-preview.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): NA
 - IDE and version :NA

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Thank you for finding this issue. It is an unfortunate mistake but moving it would be a breaking change and we feel copying it is not worth the increased assembly size or possible UX issues in the future.
