### ISSUE TITLE
[QUERY] looking for a sample on how to create private endpoint 

### ISSUE THREAD

**Issue by digeler** [Azure/azure-sdk-for-net#14265]
**Query/Question**
How can we help?
am looking for a sample to implement private endpoint  : 
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.network.fluent.iprivateendpointsoperations?view=azure-dotnet
https://docs.microsoft.com/en-us/azure/event-hubs/private-link-service

can you share a sample on how to create it using code.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help on sample? thanks

**Comment by xccc-msft** [comment]
@digeler You may use below entry points to create private endpoints and private link services:
```csharp
// private endpoint
networkManager.Inner.PrivateEndpoints.CreateOrUpdateAsync
// private link service
networkManager.Inner.PrivateLinkServices.CreateOrUpdateAsync
```

**Comment by lilyjma** [comment]
@digeler - did the response above answer your question?

**Comment by weidongxu-microsoft** [comment]
New SDK will be on https://aka.ms/azsdk/dotnet/mgmt
