### ISSUE TITLE
[BUG]Method not found: 'Void Microsoft.Azure.KeyVault.KeyVaultClient..ctor(Microsoft.Rest.ServiceClientCredentials, System.Net.Http.DelegatingHandler[])'

### ISSUE THREAD

**Issue by sribs** [Azure/azure-sdk-for-net#14299]
**Describe the bug**
```
Method not found: 'Void Microsoft.Azure.KeyVault.KeyVaultClient..ctor(Microsoft.Rest.ServiceClientCredentials, System.Net.Http.DelegatingHandler[])' 
```
This happens only when the following assembly is added to web.config and this is happening with the latest version ``` Microsoft.Azure.Keyvault```
``` xml
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.3" newVersion="4.1.1.3" />
      </dependentAssembly>
```

If this is removed from web.config, then constructor along with params is recognized and this is 

**Expected behavior**
Regardless of the xml if added or not added, it needs to recognize the constructor

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

``` Method not found: 'Void Microsoft.Azure.KeyVault.KeyVaultClient..ctor(Microsoft.Rest.ServiceClientCredentials, System.Net.Http.DelegatingHandler[])'```

**Environment:**
 - Name and version of the Library package used: ``` Microsoft.Azure.Keyvault, version=3.0.5```
- Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET framework ```4.6.2```
 - IDE and version : Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by heaths** [comment]
Redirecting the binding of System.Net.Http would not remove a method from our assembly. More likely the type definition of `DelegatingHandler` doesn't match. Could you provide the full exception message including stack trace?
