### ISSUE TITLE
Unlist packages with a TaskExtension bug

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14349]
- [x] https://www.nuget.org/packages/Azure.Core/1.4.0
- [x] https://www.nuget.org/packages/Azure.Core.Experimental/0.1.0-preview.3
- [x] https://www.nuget.org/packages/Azure.Identity/1.2.0
- [x] https://www.nuget.org/packages/Azure.AI.FormRecognizer/3.0.0-preview.1
- [x] https://www.nuget.org/packages/Azure.Analytics.Synapse.Artifacts/1.0.0-preview.2
- [x] https://www.nuget.org/packages/Azure.Search.Documents/11.1.0
- [x] https://www.nuget.org/packages/Azure.Storage.Blobs.ChangeFeed/12.0.0-preview.3
- [x] https://www.nuget.org/packages/Azure.Storage.Blobs.Batch/12.3.0
- [x] https://www.nuget.org/packages/Azure.Storage.Blobs/12.5.0
- [x] https://www.nuget.org/packages/Azure.Storage.Common/12.5.1
- [x] https://www.nuget.org/packages/Azure.Storage.Files.DataLake/12.3.0
- [x] https://www.nuget.org/packages/Azure.Storage.Files.Shares/12.3.0
- [x] https://www.nuget.org/packages/Azure.Storage.Queues/12.4.0
- [x] https://www.nuget.org/packages/Azure.Messaging.EventHubs/5.2.0-preview.2
- [x] https://www.nuget.org/packages/Azure.Messaging.EventHubs.Processor/5.2.0-preview.2
- [x] https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.0.0-preview.5

**Comment by AlexGhiondea** [comment]
Done.
