### ISSUE TITLE
[Azure Tables]Can't pick up correct value from environment variable

### ISSUE THREAD

**Issue by XuGuang-Yao** [Azure/azure-sdk-for-net#14367]
We are running live tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

Add `TABLES_STORAGE_ENDPOINT_SUFFIX` with appropriate value into tests.yml then the test cases can acquire it from environment for different clouds live tests.
![image](https://user-images.githubusercontent.com/53599438/90599339-40623000-e227-11ea-9e60-f4959c2e1354.png)

But all tests about storage table fails with below error:
```
System.AggregateException : Retry failed after 4 tries.
----> Azure.RequestFailedException : An error occurred while sending the request.
----> Azure.RequestFailedException : An error occurred while sending the request.
----> Azure.RequestFailedException : An error occurred while sending the request.
----> Azure.RequestFailedException : An error occurred while sending the request.
----> System.Net.Http.HttpRequestException : An error occurred while sending the request.
----> System.Net.WebException : The remote name could not be resolved: 't4113ac42c20b44c5prim.core.windows.net'
----> System.Net.Http.HttpRequestException : An error occurred while sending the request.
----> System.Net.WebException : The remote name could not be resolved: 't4113ac42c20b44c5prim.core.windows.net'
----> System.Net.Http.HttpRequestException : An error occurred while sending the request.
----> System.Net.WebException : The remote name could not be resolved: 't4113ac42c20b44c5prim.core.windows.net'
----> System.Net.Http.HttpRequestException : An error occurred while sending the request.
----> System.Net.WebException : The remote name could not be resolved: 't4113ac42c20b44c5prim.core.windows.net'
```
The storage uri = TABLES_STORAGE_ACCOUNT_NAME + TABLES_STORAGE_ENDPOINT_SUFFIX

Expected value:

> t4113ac42c20b44c5prim.**table**.core.windows.net 

Actual value (table is missing):

> t4113ac42c20b44c5prim.core.windows.net

But the cosmos table tests don't have this issue. (BTW, it uses `TABLES_COSMOS_ENDPOINT_SUFFIX` as service suffix)

@jongio @danieljurek for notification.

**Comment by tzhanl** [comment]
@danieljurek can you review this issue?

**Comment by jsquire** [comment]
//fyi - @christothes

**Comment by christothes** [comment]
Please try with the following env variables:
[STORAGE_ENDPOINT_SUFFIX](https://github.com/Azure/azure-sdk-for-net/blob/aec86f6742b73deb307f15390500771dbe13c5e2/sdk/core/Azure.Core.TestFramework/src/TestEnvironment.cs#L122)
[COSMOS_TABLES_ENDPOINT_SUFFIX](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/TablesTestEnvironment.cs#L21)

**Comment by XuGuang-Yao** [comment]
@christothes - Yes, it works. Thanks for your update.
