### ISSUE TITLE
[QUERY] How can I define API permissions for an application in order to sign in a user and read its profile?

### ISSUE THREAD

**Issue by Rookian** [Azure/azure-sdk-for-net#14372]
**Query/Question**
I created an application and a corresponding service principal. Now I would like to define permissions in order to sign in a user and read its profile (Azure Active Directory Graph (1) | User.Read)

How can I define API permissions for an application?

**Environment:**
 - Microsoft.Azure.Management.Fluent 1.34.0
 - Microsoft.Azure.Management.ResourceManager.Fluent 1.34.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by yungezz** [comment]
hi @xccc-msft could  you pls help on this? thanks

**Comment by xccc-msft** [comment]
@Rookian You may try with below:
```csharp
ApplicationCreateParameters createParameters = new ApplicationCreateParameters();
createParameters.AppPermissions = new List<string>();
createParameters.AppPermissions.Add("app-permission1");
createParameters.AppPermissions.Add("app-permission2");
// set other required properties...
await manager.Applications.Inner.CreateAsync(createParameters);
```
