### ISSUE TITLE
SearchIndexClient.Documents.Index() method - properties set to default value are being saved as null instead of their actual value

### ISSUE THREAD

**Issue by SylviaJ** [Azure/azure-sdk-for-net#1437]
I am using the SDK to upload or merge documents but there seems to be a bug with the json serialization that sets properties with their default value to null instead of using the default value.

My Code: 

    SearchIndexClient indexClient = SearchClient.Indexes.GetClient(index.IndexName);
    var actions = docsToUpload.Select(doc => IndexAction.Create(IndexActionType.MergeOrUpload, doc));
    var indexBatch = IndexBatch.Create(actions);
    indexClient.Documents.Index(indexBatch);

My docsToUpload are of a class type.
For example

    public class MyClass {
        public string DocumentId { get; set; }
        public bool IsArchived { get; set; }
        public int OrderBy { get; set; }
    }

I find that any instances where the IsArchived is set to false and/or the OrderBy is set to 0 (i.e. their default values), these values in the search index are being set to null, instead of to False or to 0.

I think that it has something to do with the serialization of the classes to JSON.
This is because I tried uploading my documents directly using the REST API instead of using the SDK, doing my own serialization using the following and the documents uploaded with the correct values in for the IsArchived and OrderBy. 
Note that used the 'https://azure.microsoft.com/en-gb/documentation/articles/search-get-started-dotnet/' tutorial to write my code.

    private void UpdateDataDirectly<T>(AzureSearchIndex index, params T[] documents) where T : class
        {
            Uri azureServiceUri = new Uri("https://" + AzureSearchSettings.AzureServiceName + ".search.windows.net");
            HttpClient httpClient = new HttpClient();
            httpClient.DefaultRequestHeaders.Add("api-key", AzureSearchSettings.AzureServiceApiKey);

            // create request string
            string indexPath = "indexes/" + index.IndexName + "/docs/index";
            Uri uri = new Uri(azureServiceUri, indexPath);

            string json = "{ \"value\": [";
            foreach (var doc in documents)
            {
                string docJson = AzureSearchHelper.SerializeJson(doc);
                docJson = docJson.TrimStart('{');
                docJson = "{ \"@search.action\": \"mergeOrUpload\", " + docJson;
                json += docJson + ", ";
            }
            json = json.TrimEnd(' ', ',');
            json += " ]}";

            HttpResponseMessage response = AzureSearchHelper.SendSearchRequest(httpClient, HttpMethod.Post, uri, json);
            
        }

Code from the helper class (from the tutorial)

        static AzureSearchHelper()
        {
            _jsonSettings = new JsonSerializerSettings
            {
                Formatting = Formatting.None, // for readability use Indented, change to None for compactness
                //ContractResolver = new CamelCasePropertyNamesContractResolver(),
                DateTimeZoneHandling = DateTimeZoneHandling.Utc
            };

            _jsonSettings.Converters.Add(new StringEnumConverter());
        }

        /// <summary>
        /// Serializes the json to a string.
        /// </summary>
        /// <param name="value">The value.</param>
        /// <returns></returns>
        public static string SerializeJson(object value)
        {
            return JsonConvert.SerializeObject(value, _jsonSettings);
        }

This is a problem because when you then search for a document and it tries to serialise back to the 'MyClass' object it gets an Invalid Cast Exception 'Null object cannot be converted to a value type.'

**Comment by brjohnstmsft** [comment]
This is a known issue, tracked here: https://github.com/Azure/azure-sdk-for-net/issues/1063

You'll need to use nullable types in your model class:

    public class MyClass {
        public string DocumentId { get; set; }
        public bool? IsArchived { get; set; }
        public int? OrderBy { get; set; }
    }
