### ISSUE TITLE
Move ChallengeBasedAuthenticationPolicy to Azure.Core

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#14389]
Copying much of the existing BearerTokenAuthenticationPolicy but instead parsing out the `WWW-Authentication` response header to issue a challenge, move the ChallengeBasedAuthenticationPolicy from Key Vault shared source to Azure.Core and make it public.

Relates to #12938, though I was unable to repro that with the change I already made in PR #10673.

**Comment by heaths** [comment]
@schaabs do you already have another bug tracking this?

**Comment by christothes** [comment]
After https://github.com/Azure/azure-sdk-for-net/pull/18368 merges, I have a branch that refactors `ChallengeBasedAuthenticationPolicy` with the new `BearerTokenChallengeAuthenticationPolicy` as its base. Key Vault's requirements for handling the challenge is still specific enough that I think it should remain there.

**Comment by heaths** [comment]
Already done.
