### ISSUE TITLE
Migrate storage to use Multipart in Core

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#14388]
see https://github.com/Azure/azure-sdk-for-net/pull/14275

**Comment by JimSuplizio** [comment]
Hi @christothes, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
