### ISSUE TITLE
[BUG] sourceUriBuilder.DirectoryOrFilePath is not escaped when building renameSource URL

### ISSUE THREAD

**Issue by Sense545** [Azure/azure-sdk-for-net#14402]
**Describe the bug**
Trying to rename a path containing spaces results in "The source URI is invalid." error from server.

Apparently the same exact bug was reported and fixed in the Java SDK in March:
https://github.com/Azure/azure-sdk-for-java/issues/8761
https://github.com/Azure/azure-sdk-for-java/pull/8887/files#diff-0fc00850cd2388279fd01c5f427d6cfcR506

Probably just need ```sourceUriBuilder.DirectoryOrFilePath.EscapePath()``` here.
https://github.com/Azure/azure-sdk-for-net/blob/8451bb74b48e6a2e20379c34cfc3683e37161947/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakePathClient.cs#L1607

**Expected behavior**
No error from server and rename being successful.

**Actual behavior (include Exception or Stack Trace)**
Error from server "The source URI is invalid"

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. var sourceFileClient = dataLakeFileSystemClient.GetFileClient("some file with spaces.txt");
2. await sourceFileClient.RenameAsync("new file name.txt");

**Environment:**
- Azure.Storage.Files.DataLake 12.3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by sumantmehtams** [comment]
Adding @seanmcc-msft to take a look.

**Comment by seanmcc-msft** [comment]
Hi @Sense545, thanks for reporting this.

I have fixed this issue with https://github.com/Azure/azure-sdk-for-net/pull/15106.

-Sean
