### ISSUE TITLE
[BUG] BlockBlobClient.OpenRead and then CopyTo takes 3-4 minutes to copy 4MB of data

### ISSUE THREAD

**Issue by AshishAgMS** [Azure/azure-sdk-for-net#14404]
**Describe the bug**
Stream created from BlockBlobClient.OpenRead and then CopyTo memoryStream takes 3-4 minutes to copy 4MB of data wherea BlockBlobClient.DownloadTo memoryStream takes less than 1 second.

**Expected behavior**
CopyTo should have same performance as DownloadTo when destination stream is memory stream.

**Actual behavior (include Exception or Stack Trace)**
CopyTo API copies few bytes at a time to memory stream. Tried options like stream.Read to 4MB buffer and it just copies 3412 bytes at a time.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Change connectionString, containerName and blobName for a sample file
2. 
           var memoryStream = new MemoryStream();
            var connectionString = "";
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
            string containerName = "mycontainer";
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);
            var blobName = "PerfTest.txt";
            BlockBlobClient blockBlobClient = containerClient.GetBlockBlobClient(blobName);
            
            using(var blobStream = blockBlobClient.OpenRead())
            {
                blobStream.CopyTo(memoryStream);
            }

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.5.1] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [.net Core 3.1]
 - IDE and version : [Visual Studio 16.7.2]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @AshishAgMS, I can repo this, look like we have a bug:

```
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Specialized;
using NUnit.Framework;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ConsoleApp35
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string connectionString = "";
            BlobServiceClient serviceClient = new BlobServiceClient(connectionString);
            BlobContainerClient container = serviceClient.GetBlobContainerClient("sdfsdfsdfsd2");
            try
            {
                await container.CreateAsync();
                BlockBlobClient blockBlob = container.GetBlockBlobClient("myblob");
                byte[] data = GetRandomBuffer(4 * 1024 * 1024);
                Stream uploadStream = new MemoryStream(data);
                await blockBlob.UploadAsync(uploadStream);

                MemoryStream stream = new MemoryStream();

                using Stream blobStream = await blockBlob.OpenReadAsync();
                await blobStream.CopyToAsync(stream);

                AssertSequenceEqual(data, stream.ToArray());
            }
            finally
            {
                await container.DeleteAsync();
            }
        }

        public static byte[] GetRandomBuffer(long size)
        {
            Random random = new Random(Environment.TickCount);
            var buffer = new byte[size];
            random.NextBytes(buffer);
            return buffer;
        }

        public static void AssertSequenceEqual<T>(IEnumerable<T> expected, IEnumerable<T> actual)
        {
            Assert.AreEqual(expected.Count(), actual.Count(), "Actual sequence length does not match expected sequence length");
            (int index, T expected, T actual)[] firstErrors = expected.Zip(actual, (e, a) => (expected: e, actual: a)).Select((x, i) => (index: i, x.expected, x.actual)).Where(x => !x.expected.Equals(x.actual)).Take(5).ToArray();
            Assert.IsFalse(firstErrors.Any(), $"Actual sequence does not match expected sequence at locations\n{string.Join("\n", firstErrors.Select(e => $"{e.index} => expected = {e.expected}, actual = {e.actual}"))}");
        }
    }
}
```

In Fiddler:
```
GET https://seandevtest.blob.core.windows.net/sdfsdfsdfsd2/myblob HTTP/1.1
Host: seandevtest.blob.core.windows.net
x-ms-version: 2019-12-12
x-ms-range: bytes=0-4194303
...

HTTP/1.1 206 Partial Content
Content-Length: 4194304
...

GET https://seandevtest.blob.core.windows.net/sdfsdfsdfsd2/myblob HTTP/1.1
Host: seandevtest.blob.core.windows.net
x-ms-version: 2019-12-12
x-ms-range: bytes=16355-4210658
...

HTTP/1.1 206 Partial Content
Content-Length: 4177949
...

GET https://seandevtest.blob.core.windows.net/sdfsdfsdfsd2/myblob HTTP/1.1
Host: seandevtest.blob.core.windows.net
x-ms-version: 2019-12-12
x-ms-range: bytes=32710-4227013
...

HTTP/1.1 206 Partial Content
Content-Length: 4161594
...
```

I'll work on fixing this next week.

**Comment by seanmcc-msft** [comment]
Resolved with https://github.com/Azure/azure-sdk-for-net/pull/14511.
