### ISSUE TITLE
[BUG] ChainedTokenCredential throws an exception when VisualStudioCodeCredential is present 

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-sdk-for-net#14408]
**Describe the bug**
When the VisualStudioCodeCredential is present, the ChainedTokenCredential throws an exception when running in production (Azure), i.e outside the local dev environment.

**Expected behavior**
Rather than iterate through the defined TokenCredential options, the code throws an exception as soon as it encounters the VisualStudioCodeCredentials which fails to retrieve the credential since it's not present outside the dev environment

**Actual behavior (include Exception or Stack Trace)**
The code throws an exception:
```
Error: Azure.Identity.AuthenticationFailedException: The ChainedTokenCredential failed due 
to an unhandled exception: VisualStudioCodeCredential authentication failed: The operation 
completed successfully.
```

**To Reproduce**
Create an application that uses Azure.Identity and Azure Blob Storage SDKs and deploy this code to Azure

1. Add VisualStudioCodeCredential to the ChainedTokenCredential options
2. Deploy the code to Azure WebApps
3. Exception happens during authenticaiton

**Environment:**
- Azure.Identity 1.2.1 
- Azure Web Apps running on Windows, .NET Core 3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
