### ISSUE TITLE
Smoke tests should use current dev feed

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#14418]
See `azure-sdk-for-net` in https://github.com/Azure/azure-sdk-for-net/blob/master/NuGet.Config

**Comment by weshaggard** [comment]
Related to https://github.com/Azure/azure-sdk-for-net/pull/14847.

Note that currently our smoke tests are using old packages to validate not only are they using the old dev feed but they are still using "dev*" instead of the newer "alpha*" packages.

**Comment by weshaggard** [comment]
@benbp didn't you fix this when you did your smoketest work for .NET?

**Comment by benbp** [comment]
@weshaggard Yeah net smoke tests use the dev feed. Closing.
