### ISSUE TITLE
ComputeManagementClient Authentication with Certificate

### ISSUE THREAD

**Issue by tonithenhausen** [Azure/azure-sdk-for-net#1442]
Hi, I am using the latest stable 9.0 release of the `ComputeManagementClient` with a management certificate from a publish-settings file. 

I get a `CloudException` AuthenticationFailed: The 'Authorization' header is not present or provided in an invalid format. The same certificate works for the `StorageManagementClient`.

```C#
var managementCertificate = new X509Certificate2(Convert.FromBase64String(ManagementCertificate));
var creds = new CertificateCloudCredentials(SubscriptionId, managementCertificate);
var computeManagementClient = new ComputeManagementClient(creds);
computeManagementClient.VirtualMachines.ListAll(new ListParameters())
```

**Comment by mayurid** [comment]
@tonithenhausen : Only ASM client works with Certs. It looks like you are using this ARM client which uses AAD auth and hence it needs an Authorization header.

**Comment by tonithenhausen** [comment]
Is it possible to request an AAD OAUTH authorization token with a management certificate? Using AAD does not seem to be a solution for me as it requires a user to login with their organizational account or microsoft account.

**Comment by DaveVdE** [comment]
IIRC you can set up an application in AAD to have permissions, and the application uses a key to authenticate requests. Cumbersome, but I guess it could work.

**Comment by tonithenhausen** [comment]
You can use OAuth with Azure AD Applications to authenticate against Azure Resource Manager, but you cannot use Azure Service Management (old APIs), because these APIs must be authenticated with  user's OAuth credentials (and not with application OAuth creds).

**Comment by DaveVdE** [comment]
I thought the issue was you couldn't use management certificates because you're using the ARM API?

**Comment by tonithenhausen** [comment]
Sorry for the confusion. Actually, I need to use both APIs (ARM and Service Management) with the same credentials. As far as I know, certificates can only be used with Service Management and Azure AD Application OAuth (as you suggested) only with ARM. But there is no credential for both APIs except user's credentials aquired through interactive sign in (like Powershell Azure Tools does it).

**Comment by DaveVdE** [comment]
Yeah, it's a mess.
