### ISSUE TITLE
[FEATURE REQ]Azure.Identity should expose trace from MSAL library

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#14450]
**Library or service name.**
What library or service is this request related to? 
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

MSAL library allows customers to enable MSAL related traces by using PublicClientApplicationBuilder.WithLogging(...), Azure.Identity should expose such trace functionality.
```
(False) MSAL 4.16.1.0 MSAL.NetCore Microsoft Windows 10.0.19041 [08/21/2020 03:24:12 - 9eff121e-7beb-44fc-883b-4bebcff84296] Resolving authority endpoints... Already resolved? - FALSE
(False) MSAL 4.16.1.0 MSAL.NetCore Microsoft Windows 10.0.19041 [08/21/2020 03:28:41 - 9eff121e-7beb-44fc-883b-4bebcff84296] Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: authorization_pending
HTTP StatusCode 400
CorrelationId 9eff121e-7beb-44fc-883b-4bebcff84296
```

**Comment by ayeltsov** [comment]
Came here today to log this same issue.

I was considering migrating portion of the code off direct MSAL calls to higher level Azure.Identity, but found that it hides MSAL logging
