### ISSUE TITLE
Improve error messaging for invalid headers

### ISSUE THREAD

**Issue by InteXX** [Azure/azure-sdk-for-net#14469]
**Library or service name**
Azure.Storage.Blobs
 
**Description**
When an `InvalidHeaderValue` exception is thrown, information as to the header and its invalid value could be included in the exception (apparently it was, in past versions of the SDK). This would assist developers with troubleshooting and would make situations [like this](https://github.com/Azure/azure-sdk-for-net/issues/14257) less likely to occur.

**Comment by seanmcc-msft** [comment]
The SDK is returning the error messages provided by the service, so unfortunately, this would require backend API changes.  It is unlikely this could be done in the near future, as the backend teams are heads down working on the next service versions.

**Comment by InteXX** [comment]
I'm not sure I follow you.

Isn't it just a matter of parsing the error message as provided by the service and adding a couple of parameters and properties to the exception? This sounds like something that could be done pretty easily.

**Comment by seanmcc-msft** [comment]
The service doesn't tell us which header is invalid.

**Comment by InteXX** [comment]
Here's the response:

```
HTTP/1.1 400 The value for one of the HTTP headers is not in the correct format.
Server: Azurite-Blob/3.7.0
x-ms-error-code: InvalidHeaderValue
x-ms-request-id: 4dd5dd89-fc23-49fb-af73-0c5e10cc9d57
content-type: application/xml
Date: Thu, 20 Aug 2020 15:22:52 GMT
Connection: keep-alive
Transfer-Encoding: chunked

160
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>InvalidHeaderValue</Code>
  <Message>The value for one of the HTTP headers is not in the correct format.
RequestId:4dd5dd89-fc23-49fb-af73-0c5e10cc9d57
Time:2020-08-20T15:22:52.508Z</Message>
  <HeaderName>x-ms-version</HeaderName>
  <HeaderValue>2019-12-12</HeaderValue>
</Error>
0
```

Can't the header name and value be parsed from that?

**Comment by seanmcc-msft** [comment]
My bad, we'll look into this.

**Comment by InteXX** [comment]
Thanks :-)

**Comment by tg-msft** [comment]
We do [parse those into `RequestFailedException.AdditionalInformation` today.](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/StorageRequestFailedException.cs#L38)

I thought that was [displayed by default?](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs#L115)  If it's not, we should fix that.  If it's not discoverable enough, we should consider post facto client-side validation to make it clearer.
