### ISSUE TITLE
[QUERY] Dealing with BlockBlobClient Max Upload Size and Max Stage Size

### ISSUE THREAD

**Issue by willyt150** [Azure/azure-sdk-for-net#14480]
**Query/Question**
Currently I'm running against the emulator (Windows Azure Storage Emulator 5.10.0.0 command line tool)
1. How do I determine what the **correct** maximum upload size (for `BlockBlobClient.UploadAsync`) is? I compared the size of my file (`717227096`) against `BlockBlobClient.BlockBlobMaxUploadBlobLongBytes` and it's smaller than that number (`5242880000`), but then when I execute `BlockBlobClient.UploadAsync` I receive the following error:

```
The request body is too large and exceeds the maximum permissible limit.
RequestId:d63f0cd7-c03b-4e30-86ff-aabdadea9371
Time:2020-08-22T01:30:00.4497802Z
Status: 413 (The request body is too large and exceeds the maximum permissible limit.)
ErrorCode: RequestBodyTooLarge
```

2. How do I determine what the **correct** maximum Stage block size (for `BlockBlobClient.StageBlockAsync`) is? I created a stream with a buffer size using `BlockBlobClient.BlockBlobMaxUploadBlobLongBytes` (`4194304000`), which is also bigger than the size of my file (`717227096`) and I receive the same error as in #1:

3. I read in this issue [V12 SDK deprecation impact](https://github.com/Azure/azure-sdk-for-net/issues/11158) that there is supposedly a way to increase the Block blob size, but I have not been able to find where in the documentation to specify this, could you point me to that please?

Thanks,
willy150

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.5.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  1.0.0-preview2-003131 [C:\Program Files\dotnet\sdk]
  1.0.0 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.507 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.512 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.106 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 - IDE and version : Visual Studio 16.7.2

**Comment by pharring** [comment]
@pakrym I have hit this error when I upgraded my service (you know the one) to consume Azure.Storage.Blobs 12.5.1
We started seeing a new unit test failure (413, as above) because it can no longer upload a large blob to the emulator.

On investigation, this regressed in Azure.Storage.Blobs between 12.5.0-preview.4 and 12.5.0-preview.5 (and persisted in preview.6 and 12.5.1 stable)

**Comment by pakrym** [comment]
cc @seanmcc-msft @kasobol-msft 

It seems this is a 12.5.0 regression with partner impact.

**Comment by pharring** [comment]
This appears to be a result of changing Constants.Blob.Block.MaxUploadBytes from 256MB to 5000MB.
As a workaround, if you know you're dealing with the emulator, then you can set the InitialTransferSize in TransferOptions to 256MB and pass that in the BlobUploadOptions to UploadAsync.

**Comment by jaschrep-msft** [comment]
The storage emulator isn't actively supported anymore, and as such does not receive upgrades to APIs made on the storage service. 12.5.0 added support for the new service version which upped the maximum size for several upload operations. The SDK changes, including updating the "max size" properties on clients, were introduced in preview 5, which corresponds to the finding from @pharring that this begins in preview 5. 

The property actually adjusts itself based on the service version the client targets. pre 2019-12-12 uses the old value of 256MB and later uses the new 5000MB. So targeting an earlier service version (and the emulator doesn't truly support later ones anyway) will actually give you values that the emulator works with.

**Comment by jaschrep-msft** [comment]
Rereading the initial post, it looks like you're looking for max sizes for stage block. You'd want `BlockBlobMaxStageBlockLongBytes`. Those values are pre 2019-12-12 = 100MB and post = 4000MB.

**Comment by amishra-dev** [comment]
@willyt150 Travis, we already have a replacement for Storage Emulator. Its called Azurite and we would highly encourage you to move to it. @vinjiang (Vincent) and I can help you with any porting help you might need.

**Comment by pharring** [comment]
@jaschrep-msft setting the blob client did **NOT** fix the problem.
I tried `BlobClientOptions.ServiceVersion.V2019_02_02` and `BlobClientOptions.ServiceVersion.V2019_07_07` and they both failed with the same error.
I think the problem (bug?) is that PartitionedUploader doesn't look at the limits set in the client. It reads the constants directly.

**Comment by jaschrep-msft** [comment]
@pharring  Ah I see. If the user weren't actually setting their transfer settings based on what their clients specify as max values, our defaults assume latest service version limits. Or are you saying you're setting your transfer settings based on client property values and still hitting this? Your text seems to indicate you're setting values yourself but the code you link to says you're relying on defaults.

Regardless, the line you link to does strike me as incorrect. I'll file an issue for that.

**Comment by pharring** [comment]
@jaschrep-msft 
When I hit the bug (413 from the emulator when uploading more than 256MB), all I did was upgrade to the latest Azure.Storage.Blobs nuget (12.5.1).
I was using the default BlobServiceClient constructor (which, I assume, chooses the latest service version) and the default BlobUploadOptions which has the default TransferOptions.
I only started playing with the TransferOptions when I started looking for a workaround.
I only started playing with the BlobServiceClient version when you said (above) that it would work (it didn't).

**Comment by willyt150** [comment]
@amishra-dev Ashish, thank you for answering my next question before I asked :) To make sure I'd be going down the correct path is this it? https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite

I mentioned this tool to my coworkers to see if anyone had experience with it and they mentioned that the last time they looked at it, earlier this year, that it didn't support Table storage. Is this still the case?


> Rereading the initial post, it looks like you're looking for max sizes for stage block. You'd want `BlockBlobMaxStageBlockLongBytes`. Those values are pre 2019-12-12 = 100MB and post = 4000MB.
@jaschrep-msft James, you are correct I did a copy and paste error when writing my initial post, when attempting to Stage blocks I was correctly using the `BlockBlobMaxStageBlockLongBytes`

I have tried what was suggested, setting the version to 2019-07-07, and it did correctly change the BlobClient's `BlockBlobMaxStageBlockLongBytes` & `BlockBlobMaxUploadBlobLongBytes` to work with the Storage Emulator. So thank you very very much! For now I've just added an if ConnectionString contains "UseDevelopmentStorage=true" then use the 2019-07-07 version.

**Comment by amishra-dev** [comment]
@willyt150 Azurite does support table storage https://github.com/Azure/Azurite/tree/legacy-master

**Comment by XiaoningLiu** [comment]
Legacy Azurite V2 supports blob/queue and table.
Azurite V3 Table is under development and accepting open source contribution, check latest progress here. 
https://github.com/Azure/Azurite/wiki/Azurite-V3-Table 
https://github.com/Azure/Azurite/projects/2

**Comment by willyt150** [comment]
Thanks @amishra-dev and @XiaoningLiu! Am I correct in understanding that Azurite legacy doesn't support the latest storage APIs either? Looks like the most recent non-readme commit was 12 months ago, so well before the 2019-12-12 service version

If that's the case then I'll just stick with the storage emulator for now. I need table storage support and if I'm having to specify an older service version when creating my clients regardless of the tool then I'll stick with what I've got working.

Thanks again.

**Comment by amishra-dev** [comment]
Thanks, we are planning to support tables soon in the latest azurite, please watch that repo for the update.
