### ISSUE TITLE
JsonObjectSerializer - Improve exception when deserialization fails

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#14487]
The exception message coming from JsonSerializer is not easy to decipher.

**Comment by JoshLove-msft** [comment]
Or should we push to get the JsonException message updated?

**Comment by pakrym** [comment]
We should at least try to get it updated if you think it can be better.

**Comment by pakrym** [comment]
Closing, please reopen if still an issue.

**Comment by pakrym** [comment]
Closing, please reopen if still an issue.
