### ISSUE TITLE
Namespecing problems: Microsoft.WindowsAzure.Common vs Microsoft.Azure.Common

### ISSUE THREAD

**Issue by trailmax** [Azure/azure-sdk-for-net#1449]
I'm not sure if you guys know about this, but I have not found an issue regarding this.

There is are 2 sets of nuget packages _Microsoft.**Windows**Azure.Common_ and another _Microsoft.Azure.Common_. And this is causing some issues with namespaces. 

Packages to work with Scheduler, Sql, Storage depend on _Microsoft.Azure.Common_.
At the same time package _Microsoft.WindowsAzure.Management.WebSites_ depends on _Microsoft.**Windows**Azure.Common_

And given that these classes differ by namespaces (but I presume the contents are the same), this is causing a major headaches as in compiler errors: 

> cannot convert from SubscriptionCloudCredentials to SubscriptionCloudCredentials

It would be great if there was no discrepancy on the namespacing.

**Comment by mayurid** [comment]
@trailmax: There is a difference in the 2 nuget packages. The WindowsAzure namespace contains all the ServiceManagement packages while the Azure namespace contains the Resource Management packages. They may have classes of same name but are nor designed to work together.

/cc: @jianghaolu
