### ISSUE TITLE
Remove settlement overloads taking a lock token

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#14493]
Creating new issue to track the suggestion to remove the message settlement overloads that take lock tokens - https://github.com/Azure/azure-sdk-for-net/issues/10852#issuecomment-679859788

**Comment by SeanFeldman** [comment]
Please provide descriptions. Thank you.

**Comment by ramya-rao-a** [comment]
cc @clemensv and @axisc for further clarification if needed
