### ISSUE TITLE
Remove public ctors for QueueProperties/RuleProperties and add model factories instead

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#14501]
Also add model factories for SubscriptionProperties/TopicProperties and all of the runtime property models.

**Comment by SeanFeldman** [comment]
What would be the obvious benefit of a factory over constructors?

**Comment by JoshLove-msft** [comment]
These are meant to be output only types. The factories would be provided to support mocking.

**Comment by akScript** [comment]
does this mean in order to do a UpdateRuleAsync you have to call GetRuleAsync first to get the RuleProperties object?
