### ISSUE TITLE
Consider updating Get/SetSessionState to use BinaryData

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#14502]
Currently these methods use a byte array. Using BinaryData would provide the same conveniences that we get with the ServiceBusMessage Body property - the ability to create using a string, a stream, or from a serializable rich model type.

**Comment by MiYanni** [comment]
@JoshLove-msft Currently, `BinaryData` has no implicit operator to `byte[]`, so the changes don't work. It has an implicit operator to `ReadOnlyMemory<byte>`, but C# doesn't have like a 'transitive implicitness'. We would have to add an explicit implicit `byte[]` operator.

**Comment by JoshLove-msft** [comment]
Why do we need an implicit operator to byte? Can't we just do date.ToBytes() and use the implicit cast between ROM and bytes?
