### ISSUE TITLE
[QUERY] Nat Gateways for .net SDK

### ISSUE THREAD

**Issue by pengfm** [Azure/azure-sdk-for-net#14527]
Is there a NAT gateway SDK for Azure .net for SDK?

**Environment:**
 - Name and version of the Library package used: [Microsoft.Azure.Management.Network.Fluent, Version=1.0.0.66]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help?

**Comment by xccc-msft** [comment]
@pengfm Are you looking for `networkManager.VirtualNetworkGateways` or `networkManager.LocalNetworkGateways` in [Microsoft.Azure.Management.Network.Fluent]?
