### ISSUE TITLE
[BUG] Azure.Tables Throws Exception when TableEntity contains enum

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#14523]
I'm calling UpsertEntityAsync with a class that has an enum property.

```
[JsonPropertyName("type")]
public ImageType Type { get; set; } = ImageType.New;
```

Getting this error:

```
An exception of type 'System.NotSupportedException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Not supported type Lib.ImageType'
```

Do we support Enum properties?

If yes, how.

If no, what is the workaround?

azsdke2e

@christothes

**Comment by christothes** [comment]
Looks like this is being thrown [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/AutoRest/Utf8JsonWriterExtensions.cs#L110).  Investigating the right approach to support enum values and how this would work cross language.
