### ISSUE TITLE
Incorrect key vault name check?

### ISSUE THREAD

**Issue by BrianSakhai** [Azure/azure-sdk-for-net#1453]
The resolver expects the key vault name to end in "vault.net". Is this correct? I have used the vault URI as the vault name which ends in ".vault.azure.net".

https://github.com/Azure/azure-sdk-for-net/blob/master/src/KeyVault/Microsoft.Azure.KeyVault.Extensions/KeyVaultKeyResolver.cs#L125-126

**Comment by herveyw** [comment]
This check could be more specific but would break for non-production test environments.

**Comment by herveyw** [comment]
@BrianSakhai: I take my last comment back, this check needs to be fixed.

**Comment by pomortaz** [comment]
This issue is fixed in this commit: https://github.com/Azure/azure-sdk-for-net/commit/083412cf356ac9b9e0c38f257c4c464bb0f5bf3c
