### ISSUE TITLE
[Storage Blob]Some Implementations in track1 doesn't exist in track2, or have a different implementation

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-net#14536]
Sample URL: https://github.com/Azure-Samples/storage-blob-dotnet-getting-started
Some Implementations in track1 doesn't exist in track2 in this sample, Details in the following table.
Service | Implementation   with Track1 | Implementation   with Track2
-- | -- | --
Storage blob | Line#130~131 [Link](https://github.com/Azure-Samples/storage-blob-dotnet-getting-started/blob/master/BlobStorage/Advanced.cs#L130)    // Create a buffer manager for the Blob   service client. The buffer manager enables the Blob service client to     // re-use an existing buffer across   multiple operations.               blobClient.BufferManager = new   WCFBufferManagerAdapter(                 BufferManager.CreateBufferManager(32 * 1024, 256 * 1024), 256 * 1024); | No method.
Storage blob | Line#502~504  [Link](https://github.com/Azure-Samples/storage-blob-dotnet-getting-started/blob/master/BlobStorage/Advanced.cs#L502)    Console.WriteLine("Base URI: {0}",   blobClient.BaseUri);     Console.WriteLine("Primary URI:   {0}", blobClient.StorageUri.PrimaryUri);     Console.WriteLine("Secondary URI:   {0}", blobClient.StorageUri.SecondaryUri); | No method to get   PrimaryUri and  SecondaryUri   Only:   blobServiceClient.Uri
Storage blob | Line#876~912  [Link](https://github.com/Azure-Samples/storage-blob-dotnet-getting-started/blob/master/BlobStorage/Advanced.cs#L876)   // Generate an ad-hoc SAS URI for the   container with write and list permissions.               string adHocContainerSAS =   GetContainerSasUri(container); | No method
Storage blob | Line#388~394   [Link](https://github.com/Azure-Samples/storage-blob-dotnet-getting-started/blob/master/BlobStorage/Advanced.cs#L392)  // List containers   beginning with the specified prefix, returning segments of 5 results each.     // Note that passing in null for the   maxResults parameter returns the maximum number of results (up to 5000).    // Requesting the container's metadata as   part of the listing operation populates the metadata,     // so it's not necessary to call   FetchAttributes() to read the metadata.                       resultSegment = await   blobClient.ListContainersSegmentedAsync(                       prefix,   ContainerListingDetails.Metadata, 5, continuationToken, null, null); | No method, only   list container.
Storage blob | Line#469~482   [Link](https://github.com/Azure-Samples/storage-blob-dotnet-getting-started/blob/master/BlobStorage/Advanced.cs#L471)    ///Lists blobs beginning with the specified   prefix, which must include the container name.     // The prefix is required when listing   blobs from the service client. The prefix must include     // the container name.                       resultSegment = await   blobClient.ListBlobsSegmentedAsync(prefix, continuationToken);                       foreach (var blob in   resultSegment.Results)                       {                             Console.WriteLine("\tBlob:" + blob.Uri);                       } | No method, only   list blob.
Storage blob | Line#1071~1076  [Link](https://github.com/Azure-Samples/storage-blob-dotnet-getting-started/blob/master/BlobStorage/Advanced.cs#L1072)  // If the blob is   a snapshot, write out snapshot properties.               if (blob.IsSnapshot)               {                   Console.WriteLine("\t   SnapshotTime: {0}", blob.SnapshotTime);                   Console.WriteLine("\t   SnapshotQualifiedUri: {0}", blob.SnapshotQualifiedUri);               } | No method about Snapshot
Storage blob | Line#1091  [Link](https://github.com/Azure-Samples/storage-blob-dotnet-getting-started/blob/master/BlobStorage/Advanced.cs#L1091)   Console.WriteLine("\t   ContentMD5: {0}", blob.Properties.ContentMD5); | No method to get ContentMD5
Storage blob | Line#1450~1451 [Link](https://github.com/Azure-Samples/storage-blob-dotnet-getting-started/blob/master/BlobStorage/Advanced.cs#L1451)   // Construct the   virtual directory name, which becomes part of the blob name.                       virtualDirName +=   string.Format("level{0}{1}", i,   blobServiceClient.DefaultDelimiter); | No method to get DefaultDelimiter

@jongio @tg-msft

**Comment by tg-msft** [comment]
Thanks for the help migrating!

-  For buffer management, Track 2 uses [`ArrayBool<byte>.Shared`](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.arraypool-1.shared?view=netcore-3.1#System_Buffers_ArrayPool_1_Shared).  I don't see us making that configurable until we find a customer scenario that requires it.
- There's unfortunately not a great way to reliably get Primary/Secondary URIs in the case of vanity domains.  We make customers set it themselves via [`BlobClientOptions.GeoRedundantSecondaryUri `](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobClientOptions.cs#L80).  We could maybe file a bug to add some "best guess" methods to `BlobUriBuilder`, but the best workaround for now would be something like:
    ```C#
    Uri primary = new Uri("https://myacctname.blob.core.windows.net/");
    BlobUriBuilder builder = new BlobUriBuilder(primary);
    builder.Host = builder.Host.Insert(builder.Host.IndexOf('.'), "-secondary");
    Uri secondary = builder.ToUri();
    ```
- Getting a container SAS is supported by `BlobSasBuilder` today.  Just set the `BlobContainerName` property and proceed as normal.
    ```C#
    BlobSasBuilder sasBuilder = new BlobSasBuilder();
    sasBuilder.BlobContainerName = "mycontainer";
    sasBuilder.SetPermissions(BlobContainerSasPermissions.List | BlobContainerSasPermissions.Write);
    sasBuilder.ExpiresOn = DateTimeOffset.UtcNow.AddHours(1);
    BlobUriBuilder uriBuilder = new BlobUriBuilder(blobUri);
    uriBuilder.Sas = sasBuilder.ToSasQueryParameters(sharedKey);
    Uri sasUri = uriBuilder.ToUri();
     ```
    - In the next couple of months we're hoping to add convenience APIs that should make this a little easier like:
        ```C#
        var builder = containerClient.GetSasBuilder(
            permissions: BlobContainerSasPermissions.List | BlobContainerSasPermissions.Write,
            expiresOn: DateTimeOffset.UtcNow.AddHours(1));
        // Set any other SAS options...
        var sasUri = containerClient.GenerateSasUri(builder);
        ```
-  List containers beginning with the specified prefix 5 at a time and fetch metadata too:
    ```C#
    BlobServiceClient serviceClient = ...;
    IAsyncEnumerable<Page<BlobContainerItem>> pages =
        serviceClient
        .GetBlobContainersAsync(
            traits: BlobContainerTraits.Metadata,
            prefix: "images-")
        .AsPages(pageSizeHint: 5);
    await foreach (Page<BlobContainerItem> page in pages)
    {
        foreach (BlobContainerItem container in page.Values)
        {
            Console.WriteLine(container.Name);
            foreach (KeyValuePair<string, string> pair in container.Properties.Metadata)
            {
                Console.WriteLine($"    {pair.Key}: {pair.Value}");
            }
        }
    }
    ```
- Listing blobs by prefix works just like the above sample code
- We don't have explicit methods for testing if something's a snapshot.  We also treat snapshots as opaque strings on advice from the Arch Board.  Please note there's also `BlobBaseClient.WithSnapshot(string snapshot)` to turn any random client into one pointing at a snapshot.  The best way to check if something's a snapshot today is:
    ```C#
    BlobClient blob = null;
    BlobUriBuilder builder = new BlobUriBuilder(blob.Uri);
    if (builder.Snapshot != null)
    {
        Console.WriteLine($"Snapshot: {builder.Snapshot}");
    }
    ```
- We're future proofing hashing to support multiple algorithms so it's currently:
    ```C#
    BlobDownloadInfo download = ...;
    // Someday: Console.WriteLine($"Algorithm: {download.ContentHashAlgorithm}");
    Console.WriteLine($"Hash: {download.ContentHash}"); // Just MD5 today
    ```
- There's no `DefaultDelimiter` for virtual directories because they're a synthetic concept and we're not adding those to Track 2.  You can just use the Track 1 constant value directly in the sample code.

I didn't compile or run any of these code samples so they might be a little off, but ping me if you run into more trouble.

**Comment by Luyunmt** [comment]
Thank you for your help. Now I know how to check if something's a snapshot, but is there a method to get SnapshotTime or SnapshotQualifiedUri in track2?
![image](https://user-images.githubusercontent.com/53427149/92544721-25606a00-f281-11ea-8ff0-385b2077efbb.png)

**Comment by tg-msft** [comment]
It's just using `BlobUriBuilder.Snapshot`.  Here's equivalent example code:

```C#
BlobClient blob = ...;
BlobUriBuilder builder = new BlobUriBuilder(blob.Uri);
if (builder.Snapshot != null)
{
    Console.WriteLine($"Snapshot Time: {builder.Snapshot}");
    Console.WriteLine($"Snapshot URI: {blob.Uri}");
}
```

**Comment by Luyunmt** [comment]
Thank you for your help. Is there a method to get blob StreamWriteSizeInBytes in track2?
The follow code is track1. 
![image](https://user-images.githubusercontent.com/53427149/92691042-8a48bc80-f374-11ea-8199-097e849527a2.png)

**Comment by tg-msft** [comment]
I'm not super familiar with that property, but according to [the docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblockblob.streamwritesizeinbytes?view=azure-dotnet-legacy) the closest thing we have is [StorageTransferOptions.MaximumTransferSize](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.storagetransferoptions.maximumtransfersize?view=azure-dotnet#Azure_Storage_StorageTransferOptions_MaximumTransferSize) and it's only an option that you pass into `Upload` yourself.

We don't have a notion of virtual directories in Track 2 because that's a synthetic concept.  You can check if an item is a prefix though.  Here's sample code to recursively enumerate everything in a container starting with a given prefix and return only the "directories":

```C#
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;

namespace ConsoleApp46
{
    public static class Program
    {
        private const string ConnectionString = "...";

        public static async Task Main()
        {
            BlobContainerClient container = new BlobContainerClient(ConnectionString, "clouddrive");
            await container.CreateIfNotExistsAsync();
            Func<string, Task> CreateVirtualFile = async path =>
                await container.GetBlobClient(path).UploadAsync(
                    new MemoryStream(Encoding.UTF8.GetBytes("Hello, world")),
                    overwrite: true);
            await CreateVirtualFile("toplevel.txt");
            await CreateVirtualFile("/foo/bar/baz/qux.txt");
            await CreateVirtualFile("/foo/bar/baz/quux.txt");
            await CreateVirtualFile("/azure/storage/blobs/demo.txt");
            await CreateVirtualFile("/azure/storage/queues/demo.txt");
            await CreateVirtualFile("/azure/storage/files/demo.txt");
            await CreateVirtualFile("/azure/storage/datalake/demo.txt");

            Console.WriteLine("Storage folders:");
            await foreach (string folder in GetVirtualFoldersAsync(container, "/azure/storage/"))
            {
                Console.WriteLine($"    {folder}");
            }

            Console.WriteLine("\nAll folders:");
            await foreach (string folder in GetVirtualFoldersAsync(container))
            {
                Console.WriteLine($"    {folder}");
            }

        }

        public static async IAsyncEnumerable<string> GetVirtualFoldersAsync(BlobContainerClient container, string root = "/")
        {
            Queue<string> remainingFolders = new Queue<string>();
            remainingFolders.Enqueue(root);
            while (remainingFolders.Count > 0)
            {
                string path = remainingFolders.Dequeue();
                await foreach (BlobHierarchyItem blob in container.GetBlobsByHierarchyAsync(prefix: path, delimiter: "/"))
                {
                    if (blob.IsPrefix)
                    {
                        yield return blob.Prefix;
                        remainingFolders.Enqueue(blob.Prefix);
                    }
                }
            }
        }
    }
}
```

**Comment by Luyunmt** [comment]
Thank you for you help. As follow now I can't find methos to manage contaner lease,  is there a method to do it?
![image](https://user-images.githubusercontent.com/53427149/92857551-6db98c80-f427-11ea-8d83-ab5f33fdfef0.png)
![image](https://user-images.githubusercontent.com/53427149/92857760-bffaad80-f427-11ea-9dfe-70970fac37d9.png)

**Comment by tg-msft** [comment]
If you add the `.Specialized` namespace, you'll find a `GetBlobLeaseClient` extension method on containers and blobs which provides all the lease operations.
