### ISSUE TITLE
Update generator version & rerecord tests for synapse

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14544]
Because the live test pipelines were unavailable at the time of https://github.com/Azure/azure-sdk-for-net/pull/14407 the following projects were pinned to an old C# generator version.

To unpin remove `<TemporaryUsePreviousGeneratorVersion>true</TemporaryUsePreviousGeneratorVersion>`, run `dotnet msbuild /t:GenerateCode` and re-record tests.

- [ ] sdk\synapse\Azure.Analytics.Synapse.AccessControl\src\Azure.Analytics.Synapse.AccessControl.csproj
- [ ] sdk\synapse\Azure.Analytics.Synapse.Artifacts\src\Azure.Analytics.Synapse.Artifacts.csproj
- [ ] sdk\synapse\Azure.Analytics.Synapse.Spark\src\Azure.Analytics.Synapse.Spark.csproj

cc @tg-msft

**Comment by idear1203** [comment]
@pakrym Thanks for reaching out. @wonner could you please help with this with high priority?

**Comment by pakrym** [comment]
Would be nice to add the live test pipeline as well.

**Comment by idear1203** [comment]
Yes. We have prepared some test cases for pipeline, triggers, notebooks, etc. Will send out PR soon.

**Comment by tg-msft** [comment]
I think you both might be talking about different things?  @pakrym is talking about a DevOps pipeline configured to run Synapse tests against live Azure services and it sounds more like @idear1203 is talking about adding test cases for Synapse pipelines.  I'll follow up over email.
