### ISSUE TITLE
Update generator version & rerecord tests for management projects

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14543]
Because the live test pipelines were unavailable at the time of https://github.com/Azure/azure-sdk-for-net/pull/14407 the following projects were pinned to an old C# generator version.

To unpin remove `<TemporaryUsePreviousGeneratorVersion>true</TemporaryUsePreviousGeneratorVersion>`, run `dotnet msbuild /t:GenerateCode` and re-record tests.

- [ ] sdk\appconfiguration\Azure.ResourceManager.AppConfiguration\src\Azure.ResourceManager.AppConfiguration.csproj
- [ ] sdk\compute\Azure.ResourceManager.Compute\src\Azure.ResourceManager.Compute.csproj
- [ ] sdk\digitaltwins\Azure.ResourceManager.DigitalTwins\src\Azure.ResourceManager.DigitalTwins.csproj
- [ ] sdk\dns\Azure.ResourceManager.Dns\src\Azure.ResourceManager.Dns.csproj
- [ ] sdk\eventhub\Azure.ResourceManager.EventHubs\src\Azure.ResourceManager.EventHubs.csproj
- [ ] sdk\keyvault\Azure.ResourceManager.KeyVault\src\Azure.ResourceManager.KeyVault.csproj
- [ ] sdk\network\Azure.ResourceManager.Network\src\Azure.ResourceManager.Network.csproj
- [ ] sdk\resources\Azure.ResourceManager.Resources\src\Azure.ResourceManager.Resources.csproj
- [ ] sdk\sqlmanagement\Azure.ResourceManager.Sql\src\Azure.ResourceManager.Sql.csproj
- [ ] sdk\storage\Azure.ResourceManager.Storage\src\Azure.ResourceManager.Storage.csproj
- [ ] sdk\storage\Azure.ResourceManager.Storage\tests\Azure.ResourceManager.Storage.Tests.csproj
- [ ] sdk\testcommon\Azure.Management.Compute.2019_12\src\Azure.Management.Compute.csproj
- [ ] sdk\testcommon\Azure.Management.Network.2020_04\src\Azure.Management.Network.csproj
- [ ] sdk\testcommon\Azure.Management.Resources.2017_05\src\Azure.Management.Resources.csproj
- [ ] sdk\testcommon\Azure.Management.Storage.2019_06\src\Azure.Management.Storage.csproj
- [ ] sdk\cosmosdb\Azure.ResourceManager.CosmosDB\src\Azure.ResourceManager.CosmosDB.csproj

**Comment by jsquire** [comment]
Given the age of this and the shift to the track 2 packages, closing this out as stale.  Please feel free to reopen if this is still needed.
