### ISSUE TITLE
[Azure.Identity] EnvironmentCredential evaluation order in documentation does not match code

### ISSUE THREAD

**Issue by jamesbr-ashn** [Azure/azure-sdk-for-net#14551]
Within the documentation, the order is Secret -> Certificate -> Password. Within EnvironmentCredential.cs, the process is:
```
if (clientSecret != null)  {...}
else if (username != null && password != null)  {...}
else if (clientCertificatePath != null)   {...}
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by schaabs** [comment]
@jamesbr-ashn Thanks for bringing this discrepancy to our attention. We will update the documentation to properly reflect the behavior. Just to clarify, you are referring to the reference documentation for the `EnvironmentCredential` class correct?

**Comment by jamesbr-ashn** [comment]
You are correct @schaabs. I found the order wasn't processing as described in your documentation.

**Comment by christothes** [comment]
This appears to be resolved.
