### ISSUE TITLE
KeyVault tests take long in playback

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14557]
```
  √ DeleteRsaHsmKey [22s 475ms]
  √ DeleteEcHsmKey [18s 73ms]
  √ GetDeletedRsaHsmKey [14s 24ms]
  √ RecoverDeletedEcHsmKey [28s 676ms]
```

cc @heaths

**Comment by heaths** [comment]
We have some mandatory waits for anything deletion-related (can take a while to actually delete on the backend), so some of these may not be skipping the duration that for playback.

**Comment by heaths** [comment]
I was running into this while fixing another bug, so I fixed it now (it was as I thought about the polling interval).
