### ISSUE TITLE
[QUERY] Where's the v5 equivalent to EventHubTrigger for Azure Functions?

### ISSUE THREAD

**Issue by willyt150** [Azure/azure-sdk-for-net#14566]
**Query/Question**
Sorry if I'm asking in the wrong location.

All the documentation for Azure Functions (and the Visual Studio Template) use the Microsoft.Azure.WebJobs.Extensions.EventHubs nuget package to setup an EventHubTrigger, but that's using the Microsoft.Azure.EventHubs nuget package.

Is there a new sdk that contains the EventHubTrigger?

Thanks!

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.1.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure V3 Function
 - IDE and version : Visual Studio 16.7.2

**Comment by jsquire** [comment]
Hi @willyt150.  The triggers and bindings for Azure Functions take a dependency on the client libraries for other services - meaning, that the Event Hubs library wouldn't offer any constructs specific to the Functions environment, rather the `EventHubTrigger` would need to make the decision to consume v5.x of the Event Hubs client.  

To my knowledge, the Functions bindings have not yet been updated to the new line of Azure SDKs.   @pakrym may have some additional insight that he's able to provide from discussion with the Azure Functions team.

**Comment by willyt150** [comment]
Ok thanks @jsquire! One more question, do you happen to know if there are any issues using the 5.1 Event Hubs library to send event data and the old library and a function trigger/binding to read the data? I'm asking because we've run into issues with the v12 Storage Queues library and the v11 function trigger where the message had to be base64 encoded before it was sent otherwise the function trigger would blow up.

And I guess I'll be sticking with the old libraries for now then because of my functions.

**Comment by jsquire** [comment]
> do you happen to know if there are any issues using the 5.1 Event Hubs library to send event data and the old library and a function trigger/binding to read the data? 

I do; You should be able to cross the v4 and v5 versions of Event Hubs when publishing and consuming without issue.  The event message formats are compatible between them.

**Comment by pakrym** [comment]
Yes, we are working on a new set of WebJobs extensions based on the new libraries. Unfortunately, it's a bit early for me to be able to name exact dates but it's coming.

**Comment by willyt150** [comment]
alright, hopefully that will come sooner rather than later :) (as with all things programming)

Thank you for answering my question.

**Comment by deyanp** [comment]
> Yes, we are working on a new set of WebJobs extensions based on the new libraries. Unfortunately, it's a bit early for me to be able to name exact dates but it's coming.


@pakrym have you finished this?

**Comment by jsquire** [comment]
Hi @deyanp.  The first beta for the updated bindings is available on [NuGet](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs/5.0.0-beta.1).   We do not yet have a date to share for when these may reach GA status.

**Comment by deyanp** [comment]
Thanks, @jsquire, I migrated to it today (separate branch), however wondering how stable this beta 1 is - any idea? When do you think we can have sth stable - in a week, month or more? 

Worried about checkpoint migration ... would require downtime etc ..
