### ISSUE TITLE
[FEATURE REQ] Computer Vision - v3 Read API Suggestions

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-sdk-for-net#14599]
**Library or service name.**
What library or service is this request related to? Cognitive Services - Computer Vision
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

The current v6.0.0-preview.1 SDK and documentation proposes customers to begin migrating off the soon deprecated v2 endpoints. As part of attempting to integrate the new v3 APIs via the SDK we have noticed the following areas which might make lives of other developers in this area easier.

 - Make available SDK method to extract the `operationId` when performing a `ReadAsync` call. Users will commonly have to reuse the `operationId` in order to obtain the actual result later, currently this is only exposed out as part of the `ReadHeaders` object which only has an `OperationLocation` value which is the full URI. Users are then left to perform string manipulation in order to extract the `operationId` for future operations

- Amend or add overload to `GetReadResultAsync(Guid operationId)` to accept a string `operationId` instead. Given users can only receive this as a `string` from the previous above extraction method, having to then pass it in with `Guid.Parse(operationId)` is just another hoop to jump through in order to use the API

- Provide supported language `enum` for the `Read` API, similar to `OcrLanguages`. It appears that the `OcrLanguages` enum is the list of supported languages for the legacy `OCR` endpoint, it would be great to have an equivalent for the v3 version

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by wahyuen** [comment]
bump

**Comment by JimSuplizio** [comment]
Hi @wahyuen, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
