### ISSUE TITLE
[BUG] Computer Vision - v3 Read API - Language Field missing

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-sdk-for-net#14600]
**Describe the bug**
The new v3 Read API has a `language` field per `line` that is returned in the `ReadResult`, however, this value is always `null`

**Expected behavior**
What is the expected behavior?
`language` to be populated with the detected language of the text that was read

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Value is always `null`

**To Reproduce**
```json
{
    "version": "3.0.0",
    "readResults": [
        {
            "page": 1,
            "language": "en",
            "angle": -0.6079,
            "width": 3000.0,
            "height": 4000.0,
            "unit": "pixel",
            "lines": [
                {
                    "language": null,  <<< this is always null
                    "boundingBox": [
                        1705.0,
                        1963.0,
                        1853.0,
                        1962.0,
                        1853.0,
                        1992.0,
                        1705.0,
                        1993.0
                    ],
                    "text": "dvg.com.au",
                    "words": [
                        {
                            "boundingBox": [
                                1713.0,
                                1964.0,
                                1844.0,
                                1962.0,
                                1844.0,
                                1993.0,
                                1713.0,
                                1993.0
                            ],
                            "text": "dvg.com.au",
                            "confidence": 0.933
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.CognitiveServices.Vision.ComputerVision 6.0.0-preview.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8] Windows 10 .NET Core SDK 3.1.401
 - IDE and version : [e.g. Visual Studio 16.3] Visual Studio 16.7.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by wahyuen** [comment]
bump

**Comment by JimSuplizio** [comment]
Hi @wahyuen, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
