### ISSUE TITLE
Form Recognizer GetCustomModel(); sdk error -> Azure.RequestFailedException: 'The Form Recognizer API version used to create the model and the current API version used for GET model are incompatible. Status: 400 (Bad Request) ErrorCode: 1027

### ISSUE THREAD

**Issue by sachinpatel248** [Azure/azure-sdk-for-net#14607]
### Query/Question
Using form Recognizer's labelling tool https://fott-preview.azurewebsites.net/ on **v2.1 public preview** I have trained a Custom model with labels. But not able to fetch available models & custom model using  (trainingClient.GetCustomModels(); & trainingClient.GetCustomModel()) using C# SDK 
Though I'm able to fetch using API

### Using SDK - Azure.AI.FormRecognizer v3.0.0: Model is not fetched
**Status - Error:** Azure.RequestFailedException: 'The Form Recognizer API version used to create the model and the current API version used for GET model are incompatible. Status: 400 (Bad Request) ErrorCode: 1027

``` C#
        static public FormTrainingClient AuthenticateTrainingClient()
        {
            string endpoint = "<End_Point>";
            string apiKey = "<Key>";
            var credential = new AzureKeyCredential(apiKey);
            var trainingClient = new FormTrainingClient(new Uri(endpoint), credential);
            return trainingClient;
        }

        static public void GetModelusingSDK()
        {
            FormTrainingClient trainingClient = AuthenticateTrainingClient();

            string modelId = "<Model_ID>";
            
            CustomFormModel model = trainingClient.GetCustomModel(modelId);
        }
```

### Using API with same form recognizer credentials
**Status:  Successful**
``` C#
        static async Task GetModelusingAPIAsync()
        {
            string endpoint = "<End_Point>";
            string apiKey = "<Key>";
            string modelId = "<Model_ID>";

            var client = new HttpClient();
            var queryString = HttpUtility.ParseQueryString(string.Empty);

            client.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", apiKey);

            queryString["op"] = "full";
            var uri = endpoint + "formrecognizer/v2.1-preview.1/custom/models/" + modelId + "/?" + queryString;

            var response = await client.GetAsync(uri);
            string responseBody = await response.Content.ReadAsStringAsync();
        }
```

**Also when calling list models using SDK - Models are not fetched BUT calling API serves the need**
``` C#
Pageable<CustomFormModelInfo> models = trainingClient.GetCustomModels();
```

## Am I missing something here?

**Environment:**
 - Name and version of the Library package used: 
   **Azure.AI.FormRecognizer v3.0.0** 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
   **1. Windows 10
   2. Dot Net core 3.1**
 - IDE and version: 
   **Microsoft Visual Studio Enterprise 2019 Version 16.6.5**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Thanks @jsquire .

@sachinpatel248 when you say "Using API " you mean using directly the REST API? (looks like it but want to confirm).
Currently the 3.0.0 SDK only supports v2.0 of the service, which is why you won't be able to retrieve models created in later version.
We are working on 3.1-beta.1 which will start supporting v2.1-preview service version but estimated release date is mid October.

If you don't need the new functionalities that are supported in v2.1-preview, I would recommend training your models using labeling tool with v2.0 so then you can use the v3.0.0 SDK

FYI @ctstone

**Comment by sachinpatel248** [comment]
Thanks, @maririos

Yes, your assumption is correct I did mean REST API when said "using API".
And thanks very much for clarifications & planned release date for a newer version of SDK.

**Comment by maririos** [comment]
Sure. We will post more information in this issue: https://github.com/Azure/azure-sdk-for-net/issues/14675 so you can follow the progress of the work/features/release for 3.1-beta.1
