### ISSUE TITLE
[BUG] PageBlobWriteStream advances stream position twice during write

### ISSUE THREAD

**Issue by andreaskoepf** [Azure/azure-sdk-for-net#14606]
**Describe the bug**
When a write-stream for a `CloudPageBlob` is created with `OpenWrite()` and data is written to the `StorageWriteStream` the stream's position is internally incremented twice. The two additions happen: 1. in the base class `StorageWriterStream` [here](https://github.com/Azure/azure-sdk-for-net/blob/322f6952e4946229949bd3375f5eb6120895fd2f/sdk/storage/Azure.Storage.Common/src/Shared/StorageWriteStream.cs#L169) and in 2. the derived `PageBlobWriteStream` [here](https://github.com/Azure/azure-sdk-for-net/blob/322f6952e4946229949bd3375f5eb6120895fd2f/sdk/storage/Azure.Storage.Blobs/src/PageBlobWriteStream.cs#L89).

**Expected behavior**
The number of bytes written should be added only to the stream position 1x and not 2x for each write.

What is the actual behavior?
The reported stream position after a write is too high (the offset is added twice, see source code references above).

**To Reproduce**
1. Create a `PageBlobWriteStream` object via `CloudPageBlob.OpenWrite()`
2. Read stream's `Position` property
3. Write 512 bytes of data into the stream
4. Read stream's `Position` property again and observe that it now is 1024 higher than before

**Environment:**
 - Azure.Storage.Blobs 12.5.1 
 - Windows 10, Microsoft.NETCore.App 3.1.7
 - VS 2019 v16.7.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Note that this is for the V11 library.

**Comment by andreaskoepf** [comment]
@seanmcc-msft You mean V12, don't you? At least the versions of `Azure.Storage.Blobs` and `Azure.Storage.Common` that I used to reproduce the bug locally both were `12.5.1` and the source files to which I refer are both part of a commit that was merged 16 days ago.

**Comment by seanmcc-msft** [comment]
Yes this is V12, I was confused by the references to `CloudPageBlob`, which is a class from V11, and not present in V12.

**Comment by andreaskoepf** [comment]
@seanmcc-msft sorry for the confusion, I was indeed porting/updating old code to the new sdk. I should have written `PageBlobClient` of course and not `CloudPageBlob`...
