### ISSUE TITLE
Unable to add SSL Bindings to Websites

### ISSUE THREAD

**Issue by trailmax** [Azure/azure-sdk-for-net#1461]
I'm using nuget `Microsoft.WindowsAzure.Management.WebSites 4.4.2-prerelease` version to add new web-site SSL bindings. 

Here is how the code looks:

```
var updateParameters = new WebSiteUpdateParameters()
{
    HostNameSslStates = new List<WebSiteUpdateParameters.WebSiteHostNameSslState>()
    {
        new WebSiteUpdateParameters.WebSiteHostNameSslState()
        {
            ToUpdate = true,
            Name = "mysubdomain.mydomain.com",
            SslState = WebSiteSslState.SniEnabled,
            Thumbprint = "blbhbblblblblblblbMyCertTHUMBPRINT",
        },
    },
};
var updateResult = await client.WebSites.UpdateAsync("Default-NorthEuropewebspace", sitename, updateParameters);
```

But after adding the cert I can't see the cert added to the site in the portal: 

![No SSL Binding added](http://i.stack.imgur.com/6hlw1.png)

And when I look on `updateResult.WebSite` values returned, I see the 

```
"hostNameSslStates": [
  {
    "name": "mysubdomain.mydomain.com",
    "sslState": 0,
    "ipBasedSslResult": null,
    "virtualIP": null,
    "thumbprint": null,
    "toUpdate": null,
    "toUpdateIpBasedSsl": null,
    "ipBasedSslState": 0,
    "hostType": 0
  },
  ......
```

No thumbprint, and sslStage is 0, but should be 1. For the same site I can add SSL binding in portal.azure.com without a problem. Or if using resources.azure.com, I can compose a PUT request to the site consisting of the `hostNameSslStates` (and few other parameters), and the SSL binding comes up. So the API works fine, it is the C# libraries are missing something.

(also asked the question on Stack: http://stackoverflow.com/q/32849003/809357 but no answers, presuming this is a bug)

**Comment by dlurton** [comment]
I am also experiencing the same issue.

				var wsup = new WebSiteUpdateParameters
				{
					HostNames = new List<string> { info.AzureFqdn, info.PublicFqdn },
					HostNameSslStates = new List<WebSiteUpdateParameters.WebSiteHostNameSslState>
					{
                        new WebSiteUpdateParameters.WebSiteHostNameSslState
						{
							Name = info.PublicFqdn,
							SslState = WebSiteSslState.SniEnabled,
							Thumbprint = info.SslCertificateThumbprint,
							ToUpdate = true
						}
					}
				};

				var response = _client.WebSites.Update(info.AzureRegion.WebSpace, info.AzureHostName, wsup);

response.WebSite.HostNameSslStates is populated for <mysite>.azurewebsites.net, <mysite>.scm.azurewebsites.net, and <mysite fqdn>, but all three have a WebSiteSsslState of Disabled.

**Comment by shahabhijeet** [comment]
@trailmax please open a new issue if the problem still exists/repros.
