### ISSUE TITLE
Support Environment Variable "AZURE_LOG_LEVEL"

### ISSUE THREAD

**Issue by tzhanl** [Azure/azure-sdk-for-net#14655]
Based on the environment variables identified in https://github.com/Azure/azure-sdk/blob/master/_includes/tables/environment_variables.md. Adding support for Environment Variable "AZURE_LOG_LEVEL".

@jongio for notification.

**Comment by v-xuto** [comment]
@AlexGhiondea for notification.

**Comment by AlexGhiondea** [comment]
@tzhanl Could you explain what this issue is about? I am not sure who/what should support that env var...

**Comment by v-xuto** [comment]
@AlexGhiondea Adding support for Environment Variable "AZURE_LOG_LEVEL". 
@jongio Do you have anything to add?

**Comment by AlexGhiondea** [comment]
@v-xuto it is unclear to me where should we add support for that variable.

**Comment by jongio** [comment]
This is an env var defined in the list of valid env vars, but not implemented in code.  I suggest having a dev take a look https://github.com/Azure/azure-sdk/blob/main/_includes/tables/environment_variables.md

**Comment by pakrym** [comment]
In .NET subscriber to logging events defines a level at which to listen. We didn't find a great use case for a global `AZURE_LOG_LEVEL` switch. And never heard customers asking for one.

**Comment by jongio** [comment]
Should we remove from env var support or clarify in the env var doc that it isn't supported by .NET

**Comment by annelo-msft** [comment]
Per prior comment, we plan to use build-in EventSource APIs/ILogger config to control logging level.
