### ISSUE TITLE
Support Environment Variable "AZURE_SUBSCRIPTION_ID"

### ISSUE THREAD

**Issue by cxznmhdcxz** [Azure/azure-sdk-for-net#14668]
According to environment variables listed in https://github.com/Azure/azure-sdk/blob/master/_includes/tables/environment_variables.md

Add support for environment variable "AZURE_SUBSCRIPTION_ID"

@jongio

**Comment by v-xuto** [comment]
@AlexGhiondea for notification.

**Comment by annelo-msft** [comment]
Closing as out of date.  If this is still needed, please reopen the issue.
