### ISSUE TITLE
Form Recognizer 3.1-beta.1

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#14675]

**Comment by a-bartkus** [comment]
Hi, do you have an updated estimate on when this feature will be released?
From linked issue: "We are working on 3.1-beta.1 which will start supporting v2.1-preview service version but estimated release date is mid October."

**Comment by maririos** [comment]
Hi @a-bartkus . Yes. We are going to release the 3.1-beta.1 package either at the end of this week or middle of next one. It will include support for service version 2.1-preview.1 and 2.1-preview.2.
When the release is done I will update this issue.

**Comment by maririos** [comment]
Package 3.1.0-beta.1 has been released https://www.nuget.org/packages/Azure.AI.FormRecognizer/3.1.0-beta.1
