### ISSUE TITLE
[BUG] [SDK Author] Recording tests leaves me with a single .ctor.json file

### ISSUE THREAD

**Issue by TylerLeonhardt** [Azure/azure-sdk-for-net#14685]
**Describe the bug**

I'm trying to record tests for [an updated HybridCompute SDK](https://github.com/TylerLeonhardt/azure-sdk-for-net/tree/update-hybrid-compute). When I run them using:

```powershell
$env:TEST_CSM_ORGID_AUTHENTICATION = 'SubscriptionId=<SUBID>;AADTenant=<TENANTID>;Environment=Prod;HttpRecorderMode=Record;ServicePrincipal=<APPID>;ServicePrincipalSecret=<SECRET>;'
$env:AZURE_TEST_MODE = 'Record'
dotnet test
```

**Expected behavior**
after running this, I expect to see a json file for every test like the instructions say

**Actual behavior (include Exception or Stack Trace)**
I see a single file per test file:
![image](https://user-images.githubusercontent.com/2644648/91618139-747fd400-e93e-11ea-82e0-483fb73cc550.png)
and
![image](https://user-images.githubusercontent.com/2644648/91618158-7d70a580-e93e-11ea-8219-1c101ec9f7e1.png)

inside of these these files there are entries:
![image](https://user-images.githubusercontent.com/2644648/91618212-a85af980-e93e-11ea-830c-339a52e965dd.png)

but I'm afraid that only contains the entries of the last test or something...

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. checkout my branch in my fork
2. run the commands above

**Environment:**
 - Name and version of the Library package used: N/A
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    5b6f5e5005

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.401\

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  2.1.803 [C:\Program Files\dotnet\sdk]
  2.1.805 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3] N/A

**Comment by JoshLove-msft** [comment]
@TylerLeonhardt, just so I can make sure we are on the same page, are you trying to integrate your tests with the Track 2 [Test Framework](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core.TestFramework)? Are you working on a new Track 2 management library?

**Comment by TylerLeonhardt** [comment]
@JoshLove-msft I don't really know what Track 2 is. I'm just trying to update the tests for my updated generation of the HybridCompute module:
https://github.com/TylerLeonhardt/azure-sdk-for-net/tree/update-hybrid-compute/sdk/hybridcompute/Microsoft.Azure.Management.HybridCompute/tests

I followed this guide:
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=sdk-generation-from-updated-spec

Track 2 looks fairly different than the tests I wrote and am wondering why that is...

**Comment by TylerLeonhardt** [comment]
This is apparently happening because it matters where the `MockContext.Start(GetType().FullName);` is called. It has to be called in the method that will be the name of the file it would seem. I abstracted it out to be in the ctor of my tests and that caused this behavior. It seems like this should actually look up until it finds a method with a `Fact` attribute instead of just looking up one in the stack trace.

**Comment by JoshLove-msft** [comment]
@TylerLeonhardt since you've found a workaround and we are focused primarily on enhancements for the [Track 2 Test Framework](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core.TestFramework), I will close out this issue. Let us know if there is anything else we can help with.
