### ISSUE TITLE
Add EnableExpress to admin client

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#14694]
See JS issue for background on this feature - https://github.com/Azure/azure-sdk-for-js/issues/10893
We would want to include this new property in [CreateQueueOptions](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Management/CreateQueueOptions.cs)/[QueueProperties](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Management/QueueProperties.cs)/[CreateTopicOptions](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Management/CreateTopicOptions.cs)/[TopicProperties](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Management/TopicProperties.cs).
We should check whether or not this property can be set on an existing entity by testing it out (this will guide whether the property is read-only on the Properties types listed above).

**Comment by JimSuplizio** [comment]
Hi @JoshLove-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
