### ISSUE TITLE
[QUERY] Accessing QueueMessage.MessageText as byte array

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#14705]
**Query/Question**

In `WindowsAzure.Storage` SDK, `CloudQueueMessage`  payload could be accessed as an array of bytes using `.AsBytes`.
With `Azure.Storage.Queues` the only option to access the payload is as text using `MessageText`. 

How to access message payload as a byte array?

**Update**: The support for byte array was in SDK v11 and the change was in v12, dropping the support for `byte[]`.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.*

**Comment by jsquire** [comment]
Hi Sean.  Thanks for your feedback.  Tagging and routing to the team best able to assist.

**Comment by tg-msft** [comment]
+@kasobol-msft who is thinking about this.

**Comment by kasobol-msft** [comment]
@SeanFeldman V11 is automatically encoding byte[] to base64 string which is then send over the wire. Currently the equivalent in V12 would be to Base64 encode byte[] before calling SDK.
However, as @tg-msft said, we're working on handling this case in V12 SDK. This will come in one of our future releases.

**Comment by SeanFeldman** [comment]
@kasobol-msft, is the plan and decision documented anywhere? I'd like to see the proposed change. Thank you.

**Comment by seanmcc-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/14476

**Comment by kasobol-msft** [comment]
This has been addressed in https://github.com/Azure/azure-sdk-for-net/pull/16689 along with base64 option and available in https://www.nuget.org/packages/Azure.Storage.Queues/12.5.0
