### ISSUE TITLE
[BUG] PartitionedUploader default transfer settings are pulled from constants instead of injected clients

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-net#14724]
**Describe the bug**
As discussed in https://github.com/Azure/azure-sdk-for-net/issues/14480, `PartitionedUploader` relies directly on constants for default transfer settings, including for max Put Blob and max Put Block size. If a user tries to upload from a client configured to a service version pre 2019-12-12, these values will be incorrect, and the uploader may push data too large for the service version to handle. This results in the service rejecting the request and the SDK surfacing a 4XX error code. Additionally, these constants are specifically block blob limits, and may not always be applicable for Data Lake and File Share code that goes through this class.

**Expected behavior**
PartitionedUploader should use limits defined by the client that is injected.

**To Reproduce**
Upload data larger than 256 MB against a service version earlier than 2019-12-12

**Potential Solution**
Expand injected `Behaviors` struct to contain the limits for one-shot and chunked uploads, letting clients pass their own values in as determined by their versioned properties rather than constants. PartitionedUploader should obey these injected values instead of constants.

**Comment by JimSuplizio** [comment]
Hi @jaschrep-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
