### ISSUE TITLE
[BUG] Microsoft.Azure.EventHubs releasing the lease before IEventProcessor.CloseAsync is called.

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-sdk-for-net#14732]
**Describe the bug**
Clients cannot checkpoint anymore in the IEventProcessor.CloseAsync since lease would be already released.

**Expected behavior**
Lease should be available to persist latest position on the partition.

**Actual behavior (include Exception or Stack Trace)**
Checkpoint call in CloseAsync throws LeaseLostException

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.EventHubs 4.3.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): All
 - IDE and version : All

**Comment by jsquire** [comment]
Given the age of this issue and the referenced PR being merged, I'm going to close this out as stale.   Please feel free to reopen if still needed.
