### ISSUE TITLE
[FEATURE REQ] Create CDN profile with standard microsoft SKU

### ISSUE THREAD

**Issue by hund030** [Azure/azure-sdk-for-net#14749]
**Library or service name.**
What library or service is this request related to? [Microsoft.Azure.Management.Cdn.Fluent] 
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
I want to create a CDN profile with standard microsoft SKU. I can do this on Azure Portal while SDK for .NET doesn't provide such a method, as the [document](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.cdn.fluent.cdnprofile.definition.iwithsku?view=azure-dotnet) shows.
For what purpose you don't provide such a method like `WithStandardMicrosoftSku()`? Or is there any way to create a CDN profile with standard microsoft sku?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls check is this supported already? thanks

**Comment by xccc-msft** [comment]
@hund030 It looks [Azure/azure-libraries-for-net#1163](https://github.com/Azure/azure-libraries-for-net/pull/1163) is what you are looking for. It's available since v1.36.0. Thanks.

**Comment by hund030** [comment]
@xccc-msft It is! Thank you for updates!
