### ISSUE TITLE
[BUG] ListResourceUsage throws an exception on CdnProfiles

### ISSUE THREAD

**Issue by hund030** [Azure/azure-sdk-for-net#14742]
**Describe the bug**
I am trying using dotnet sdk manage my CDN profiles and endpoints, I know that a subscription can have no more than 25 CDN profiles and I want to get this number with sdk api, instead of hard coding `25` in my program.

My code looks like this:
```
 var creds = new AzureCredentialsFactory().FromServicePrincipal(client, secret, tenantId, AzureEnvironment.AzureGlobalCloud);
 var azure = Microsoft.Azure.Management.Fluent.Azure.Authenticate(creds)
                .WithDefaultSubscription();
 var usage = azure.CdnProfiles.ListResourceUsage();
```

When I call [`ListResourceUsage()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.cdn.fluent.icdnprofiles.listresourceusage?view=azure-dotnet), it throws an `ErrorResponseException` with message `Operation returned an invalid status code 'NotFound'`. I can call other method on CdnProfiles without any issue. Besides, I notice the [`ListResourceUsage()`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.cdn.fluent.icdnprofile.listresourceusage?view=azure-dotnet) doesn't work on CdnProfile neither.

**Expected behavior**
I expect `ListResourceUsage()` returns a `IEnumerable<ResourceUsage>` object as the document says so.

**Actual behavior (include Exception or Stack Trace)**
The trace look like this:
```
Microsoft.Azure.Management.Cdn.Fluent.Models.ErrorResponseException: Operation returned an invalid status code 'NotFound'
   at Microsoft.Azure.Management.Cdn.Fluent.ResourceUsageInnerOperations.ListWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Cdn.Fluent.ResourceUsageInnerOperationsExtensions.ListAsync(IResourceUsageInnerOperations operations, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.Cdn.Fluent.CdnProfilesImpl.ListResourceUsage()
   at Microsoft.Azure.Management.Cdn.Fluent.CdnProfilesImpl.Microsoft.Azure.Management.Cdn.Fluent.ICdnProfiles.ListResourceUsage()
```
**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Run the code above.

**Environment:**
 - Name and version of the Library package used: [Microsoft.Azure.Management.Cdn.Fluent 1.34.0] and [Microsoft.Azure.Management.Fluent 1.34.0]
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [Windows 10 ASP.NET Core 3.1.401]
 - IDE and version : [Visual Studio 16.7.1]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
add @xccc-msft to help

**Comment by xccc-msft** [comment]
@hund030 I'm unable to reproduce this. For me, the `listResourceUsage` works. Are you still facing the same issue? If so, can you please try to capture the request/response by tool like Fiddler.

**Comment by hund030** [comment]
@xccc-msft I update my `Microsoft.Azure.Management.Fluent` package from v1.34.0 to latest v1.36.1, then it works.
Thanks for updates!
