### ISSUE TITLE
[BUG] When blob contains no metadata then BlobItem.Metadata is null even if BlobTraits.Metadata was specified

### ISSUE THREAD

**Issue by romisak** [Azure/azure-sdk-for-net#14750]
**Describe the bug**
When blob contains no metadata then BlobItem.Metadata is null even if BlobTraits.Metadata was specified for versions 12.5.1 or 12.6.0

**Expected behavior**
Metadata should be a dictionary with no items

**Actual behavior (include Exception or Stack Trace)**
Metadata is null

**To Reproduce**

            string connectionString = "";
            string containerName = "test-container";
            string blobName1 = "blob1";
            string blobName2 = "blob2";
            Dictionary<string, string> metadata1 = new Dictionary<string, string> { { "key", "value" } };
            Dictionary<string, string> metadata2 = new Dictionary<string, string> { };

            BlobContainerClient blobContainerClient = new BlobContainerClient(connectionString, containerName);
            blobContainerClient.CreateIfNotExists();

            BlockBlobClient blobClient1 = new BlockBlobClient(connectionString, containerName, blobName1);
            using (MemoryStream memoryStream1 = new MemoryStream(Encoding.ASCII.GetBytes("test")))
                blobClient1.Upload(memoryStream1, null, metadata1);

            BlockBlobClient blobClient2 = new BlockBlobClient(connectionString, containerName, blobName2);
            using (MemoryStream memoryStream2 = new MemoryStream(Encoding.ASCII.GetBytes("test")))
                blobClient2.Upload(memoryStream2, null, metadata2);

            Pageable<BlobItem> blobs = blobContainerClient.GetBlobs(BlobTraits.Metadata);
            BlobItem blob1 = blobs.FirstOrDefault(item => item.Name == blobName1);
            BlobItem blob2 = blobs.FirstOrDefault(item => item.Name == blobName2);

            // blob1.Metadata.Count is 1
            Console.WriteLine(blob1.Metadata?.Count);
            // blob2.Metadata.Count is 0 for Azure.Storage.Blobs version="12.4.4"
            // blob2.Metadata is null for Azure.Storage.Blobs version="12.5.1"
            Console.WriteLine(blob2.Metadata?.Count);

**Environment:**
- Worked as expected for Azure.Storage.Blobs version="12.4.4"
- Returns null for Azure.Storage.Blobs version="12.5.1"

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @romisak, thanks for the detailed bug report.  I'll look into getting this fixed in our next release.

-Sean
