### ISSUE TITLE
Add a CloudQueueMessage.Clone() API

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-sdk-for-net#14755]
**Azure.Storage.Queues**

*Note: This is an older issue that we just realized wasn't being tracked anywhere. We have [a workaround where we use reflection to manage this](https://github.com/Azure/azure-webjobs-sdk/pull/1141/files), but ideally we'd be able to remove that in the future.*

I'm from the Azure Functions team -- we’ve got some built-in functionality that will move a queue message to a ‘poison’ queue if we fail to process it 5 times. [A change back in 8.x](https://github.com/Azure/azure-storage-net/commit/0ae8c2fd5abe6e2a533b5326c7f8f3623ca41d2a) broke that because the Id changes once we insert it into the ‘poison’ queue. I gave a brief explanation here: https://github.com/Azure/azure-webjobs-sdk/issues/985#issuecomment-278434400

It would have been easy enough for us to just fix this poison-queue behavior (a customer did it himself in that issue if you read further), but it gets more complicated when I try to make a more comprehensive fix. The problems:
-	Since we pass this CloudQueueMessage to someone running their own code in a number of places, we cannot guarantee that they won’t insert it into another queue (thus changing these properties).
-	I could hold onto the PopReceipt and Id internally, but we still run into the issue that the CloudQueueMessage itself may have changed these values. So I could pass the original Id and PopReceipt separately to each of our APIs, but that makes for a fairly confusing experience.
-	I was hoping to have a way to clone a CloudQueueMessage but that doesn’t look to be possible without using reflection. If I could do this, I could keep one version ‘clean’ internally while I pass a clone to each of the customer’s methods.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi, I see that this is the [old library](https://github.com/Azure/azure-storage-net) because you're citing CloudQueueMessage.

Have you tried using the new library v12 (Azure.Storage.Queues)?  I saw you put the package name at the top but cited CloudQueueMessage which is from v11 and older. Or have we not fixed this in the v12 library?

If you need help upgrading to the v12 library please feel free to reach out.

**Comment by JimSuplizio** [comment]
Hi @brettsam, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
