### ISSUE TITLE
[QUERY] Microsoft.Azure.ServiceBus: Is there any way via Peek to determine if a message is received/locked?

### ISSUE THREAD

**Issue by josh-endries** [Azure/azure-sdk-for-net#14752]
During a Peek operation, which the [docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-browsing) describe as "typically for diagnostic and debugging purposes" (and I agree), there doesn't seem to be any way to tell if a message is currently being processed (is received/locked).

While holding a message via PeekLock in another script, every message I peek has IsReceived=True, even if it hasn't actually been "received". If this is supposed to mean received by my MessageReceiver, if a message returns from Peek(), of course it's been received, so this seems useless? The DeliveryCount is also zero for every message, _even if the message was delivered to, "received" by, and is currently locked by my other script_. Both of these feel like bugs to me. The lock info is also unavailable, of course, so that's at least three aspects of Message that seem to be just wrong. I don't really understand why the lock info can't be represented when peeking; surely the system knows if a message is locked and the timing around it.

Is there any way to determine if a peeked message is actually received (locked via PeekLock)? I would expect messages received via ReceiveAndDelete to not show up at all in a Peek. I feel like this is pretty basic and useful knowledge to know about a queue, but it doesn't seem to be implemented, documented, or intuitive. Maybe it exists but I just can't find it or figure it out...

This is using the Microsoft.Azure.ServiceBus library. I know there are at least three or four official ASB client libraries out there... If this information is available in another library, please let me know, and I will happily abandon this one.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @MiYanni

**Comment by josh-endries** [comment]
I just tried what I think is the newest version of this lib, Azure.Messaging.ServiceBus (v7? preview), but it exhibits the same behavior described above, at least in the simple `ServiceBusReceiver.PeekMessagesAsync` case. Doh.

**Comment by axisc** [comment]
@josh-endries PeekLock is a "ReceiveMode" i.e. it is to be used when you call Receive. Peeking just gives the first (or first few) messages on the queue itself.
If you peek lock, then you are actually receiving the message 'temporarily'. 

The delivery count is incremented when the message is locked and then the lock is given up by 'abandon' or when the lock times out.

Could you elaborate a bit more on what the goal is? In applications with sizeable throughput peeking to identify in-flight messages won't scale well, so most customers would rely on client side tracing to see what is going on under the hood.

**Comment by josh-endries** [comment]
Yep, I understand the difference. I had one script PeekLocking and another one Peeking, which is when I noticed there were no differences between locked and unlocked messages.

The goal is to understand what is in the queue, primarily for troubleshooting. Unfortunately it's becoming clear that ASB doesn't really have a way to do this, even with typical changing-while-enumerating sort of caveats.

Peek is problematic for several reasons, but most importantly in this case it can't identify in-flight messages _at all_, from what I see in practice, regardless of scale. There's no other way to look into an ASB queue AFAIK, so effectively there is no reliable way to troubleshoot when using ASB.

It sounds like I will have to make my own tracking mechanism, which of course is more work/maintenance, and more likely to get out of sync than the system doing it on its own. If that's just how it is, that's fine, it's just unexpected, disappointing and means the TCO of ASB is higher in practice than on the surface.

Anyway, I feel like the answer to my question is "no", so I'll close this and move on.
