### ISSUE TITLE
Key Vault Live tests failing in Azure China Cloud

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#14788]
During a live test pass against sovereign clouds the vendor team discovered a failure in Key Vault 

```json
{"error":{"code":"BadParameter","message":"The specified version (7.1) is not recognized. Consider using the latest supported version (2016-10-01)."}}
```

Failure information here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=517428&view=ms.vss-test-web.build-test-results-tab&runId=13010616&resultId=100044&paneView=debug

**Comment by AlexGhiondea** [comment]
@danieljurek I believe this is a known issue and will continue to happen while the deployments are rolled out to different clouds.

**Comment by heaths** [comment]
@RandalliLama why is the error string recommend an extremely old version? The sovereign clouds should at least support 7.0, right? If not, the track 2 SDKs only support 7.0 and newer. This will be a problem otherwise.

**Comment by heaths** [comment]
@AlexGhiondea: @sadasant, @danieljurek, and I worked on a solution that just has to be implemented. 7.1 may be far behind, especially for Azure Stacks (though, I don't think we test on that).

**Comment by tzhanl** [comment]
@danieljurek  keyvault can pass in Azure China now. this issue can be closed.

**Comment by heaths** [comment]
Thanks for letting us know.
