### ISSUE TITLE
Key Vault Live tests failing in US Gov Cloud

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#14789]
During a live test pass against sovereign clouds the vendor team discovered a failure in Key Vault live tests

```json
{"error":{"code":"BadParameter","message":"The specified version (7.1) is not recognized. Consider using the latest supported version (2016-10-01)."}}
```

Test information here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=517428&view=ms.vss-test-web.build-test-results-tab&runId=13010614&resultId=100086&paneView=debug

**Comment by heaths** [comment]
@RandalliLama why is the error string recommend an extremely old version? The sovereign clouds should at least support 7.0, right?

**Comment by tzhanl** [comment]
@danieljurek keyvault can pass in US Gov now. this issue can be closed.
