### ISSUE TITLE
[BUG]Update Link Verification Check

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#14807]
**Describe the bug**
[verify-links.yml](https://github.com/Azure/azure-sdk-for-net/blob/master/eng/common/pipelines/templates/steps/verify-links.yml) needs some fine tuning.

**Expected behavior**
Catch only broken links

**Actual behavior (include Exception or Stack Trace)**
Returns some false positives.
https://contoso.azureedge.net/urlsigning/test?expires=2145916800&amp;keyid:key1&amp;signature=iTsrLX9rVAIJkSahBA_j5o9Azf5-j331ohxDR1Gx2js=
http://logging.apache.org/log4net/release/config-examples.html

**To Reproduce**
Remove links from [ignore-links.txt](https://github.com/Azure/azure-sdk-for-net/blob/master/eng/ignore-links.txt). Run the [verify-links.ps1](https://github.com/Azure/azure-sdk-for-net/blob/master/eng/common/scripts/Verify-Links.ps1)

**Comment by sima-zhu** [comment]
http://logging.apache.org/log4net/release/config-examples.html
is not broken link.
Will verify: https://contoso.azureedge.net/urlsigning/test?expires=2145916800&amp;keyid:key1&amp;signature=iTsrLX9rVAIJkSahBA_j5o9Azf5-j331ohxDR1Gx2js=

**Comment by sima-zhu** [comment]
@chidozieononiwu Is below link suppose to be valid? There is `expire` token in url. I checked the script, it return 404 back
(https://contoso.azureedge.net/urlsigning/test?expires=2145916800&amp;keyid:key1&amp;signature=iTsrLX9rVAIJkSahBA_j5o9Azf5-j331ohxDR1Gx2js=)

**Comment by sima-zhu** [comment]
![image](https://user-images.githubusercontent.com/48036328/92262742-6d058100-ee90-11ea-9b3e-6dedc9286526.png)

**Comment by sima-zhu** [comment]
Closed the issue as it is not a problem anymore
