### ISSUE TITLE
SNI cert support for Azure Identity in Sovereign Clouds (Azure China Cloud, Azure US Government Cloud)

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#14809]
* Is SNI supported? 
* What tooling is required to set up those live tests?

**Comment by jongio** [comment]
1. Do we have tests for Public? If not, plans to?
2. Can we run those same test on sovereign clouds.

**Comment by kurtzeborn** [comment]
Not sure what work this is tracking if any at this point.  Closing.
