### ISSUE TITLE
ResourceManagerClient.Resources.DeleteAsync throws cloudexception

### ISSUE THREAD

**Issue by dejimarquis** [Azure/azure-sdk-for-net#14828]
**Query/Question**

Every time we try to delete a resource using the resource we a get a cloud exception message saying "Long running operation failed with status "Not Found"" and body saying "ParentResourceNotFound"

As a work around we catch the exception and make a get a call to verify the instance was deleted. How do I fix this?

![Annotation 2020-09-02 154644](https://user-images.githubusercontent.com/16407679/92044742-bf7d5b00-ed33-11ea-847b-2ff53046e93d.png)

**Environment:**
 - Name and version of the Library package used:  Microsoft.Azure.Management.ResourceManager.Fluent, Version=1.0.0.64

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
hi @xccc-msft could  you pls help on this? thanks.

**Comment by xccc-msft** [comment]
@dejimarquis Could you please share which type of resource you were trying to delete? Thanks.

**Comment by dejimarquis** [comment]
@xccc-msft The resource type being deleted is Microsoft.DigitaltTwins

**Comment by xccc-msft** [comment]
@dejimarquis Can you please share an example of resource id? Thanks.

**Comment by yungezz** [comment]
hi @dejimarquis could you pls share resource id for investigation? thanks
