### ISSUE TITLE
EditorConfig suggestions

### ISSUE THREAD

**Issue by j82w** [Azure/azure-sdk-for-net#14849]
This is a proposal to change the editor config to make the code more readable for developers. 

1. Change all suggestions/warnings to errors or silent. Having it as a suggestion or warning results in inconsistent code, and causes unnecessary comments and debates on PRs. The rule should either be important enough to enforce or should be ignored. Having the rule be the middle ground hurts the development process rather than help.
2. Require ["this." whenever possible](https://github.com/Azure/azure-sdk-for-net/blob/49081317e57fa4b44ac64dce9598e08a6460c9a3/.editorconfig#L36). Having "this." lets developers easily know if it is a class variable vs parameter vs local variable vs static field which saves them from needing to go to definition to figure it out.
3. csharp_style_var_when_type_is_apparent should be enabled. It's the VS default and makes code easier to read.
4. It would be great if there was a reason added when the vs default is not being followed.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by KrzysztofCwalina** [comment]
These are good suggestions. @AlexGhiondea, we should consider them for the next MQ.

**Comment by jsquire** [comment]
Given the age of this issue and that the current conventions are established for a large number of developers working in this repository, I'm going to close this as stale.
