### ISSUE TITLE
Async/sync tests should be distinguishable in TestExplorer

### ISSUE THREAD

**Issue by drwill-ms** [Azure/azure-sdk-for-net#14852]
For every test I have in a track2 library, they show up twice (one for sync and one for async), but I cannot distinguish between the two. Maybe I'm missing something.

![image](https://user-images.githubusercontent.com/14119884/85085429-ac270e80-b18c-11ea-9d5d-617b39e1d131.png)

**Comment by JoshLove-msft** [comment]
This does not seem to be an issue anymore. The tests are distinguishable based on the async parameter.
