### ISSUE TITLE
[BUG] BlobClient outbound port exhaustion

### ISSUE THREAD

**Issue by arynaq** [Azure/azure-sdk-for-net#14850]
**Describe the bug**
I cannot find any clear documentation on how the SDK uses connections towards `blob.core.windows.net` but it is clear that there is no upper bound or re-use. I have some types in our app that have scoped lifetime on `BlobContainerClient` and frequent requests are made towards the scoped instance to download blobs via `BlobContainerClient::GetBlobClient`.

But it seems each client creates a new connection, so if I am to download 1000 blobs at the same time I DDoS my appservice. I understand that for optimal performance (in terms of download/upload) it makes sense to get a new connection but is there no way to control the number of connections created from the container client (or otherwise)?

**Expected behavior**
[0,N] Tasks executing blob download should not try to create more TCP connections than is passed into the transport of the BlobContainerClient, cloud environments have limited resources and port exhaustion on blob download causes cascading failures everywhere else. 

**Actual behavior (include Exception or Stack Trace)**
Port exhaustion

**Comment by arynaq** [comment]
Looking into the code, I see that there is a static shared instance of `HttpClientTransport` being passed into the `BlobContainerClient` which means the same HttpClient is shared regardless of what DI lifetime I have on my services, how is it then possible for the `BlobClient` to create a new connection when the shared client is created by this

```c#
private static HttpClient CreateDefaultClient()
    {
      HttpClientHandler httpClientHandler = new HttpClientHandler();
      IWebProxy proxy;
      if (HttpEnvironmentProxy.TryCreate(out proxy))
        httpClientHandler.Proxy = proxy;
      return new HttpClient((HttpMessageHandler) httpClientHandler);
    }
```

Where is the new connection being created exactly?
![image](https://user-images.githubusercontent.com/2905228/92126377-629ba680-ee00-11ea-9677-b534b0aaf15e.png)
These are all towards 20.38.109.132:443 which happens to be blob storage.

**Comment by arynaq** [comment]
For reference, this is the implementation, it is the Get call that is causing connection exhaustion
```C#
public class BlobCache<T> : IColdCache<T>
    {
        private readonly BlobContainerClient _blobContainerClient;
        public string Container { get; }

        [Obsolete("Please use RBAC and TokenCredential constructor instead. Connection strings are evil.")]
        public BlobCache(string storageConnectionString, string containerName)
        {
            _blobContainerClient = new BlobContainerClient(storageConnectionString, containerName);
            Container = containerName;
        }

        public BlobCache(string storageAccountName, string containerName, TokenCredential credential)
        {
            var containerUri = new Uri($"https://{storageAccountName}.blob.core.windows.net/{containerName}");
            _blobContainerClient = new BlobContainerClient(containerUri, credential);
            Container = containerName;
        }

        public async Task<T> Get(string key)
        {
            try
            {
                var blob = _blobContainerClient.GetBlobClient(key);
                if (!await blob.ExistsAsync())
                {
                    return default;
                }

                using (Stream s = (await blob.DownloadAsync()).Value.Content)
                using (StreamReader sr = new StreamReader(s))
                using (JsonReader reader = new JsonTextReader(sr))
                {
                    var serializer = new JsonSerializer();
                    return serializer.Deserialize<T>(reader);
                }
            }
            catch (Exception ex)
            {
                throw new Exception($"Cannot load {key} from blob cache: {ex.Message}", ex);
            }
        }
}
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by kasobol-msft** [comment]
@arynaq The SDK follows [.NET Core default](https://docs.microsoft.com/en-gb/archive/blogs/timomta/controlling-the-number-of-outgoing-connections-from-httpclient-net-core-or-full-framework) here.
I agree that [the sample for HttpClientTransport](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md) isn't easily discoverable and it's not that obvious to connect it with BlobClientOptions. We'll work on that.
