### ISSUE TITLE
[BUG] BlobClient Uri now returns url encoding paths

### ISSUE THREAD

**Issue by Assassinbeast** [Azure/azure-sdk-for-net#14857]
Hi, in the old version of Azure.Storage.Blobs (12.4.4 and down), the BlobClient.Uri returns a uri without the path encoded, but the new versions (12.5.1 and up), returns uri with path as encoded characters.

Example: below is the old versions 12.4.4
![image](https://user-images.githubusercontent.com/6762656/92152601-3e9d8c80-ee23-11ea-9b0f-d50a92443fff.png)

And below here is new version 12.5.1
![image](https://user-images.githubusercontent.com/6762656/92152617-452c0400-ee23-11ea-9dd3-4799df4f8bc8.png)

I can download the "foo.txt" file whether i download it from "/devstoreaccount1/scratch/hello/foo.txt" or "/devstoreaccount1/scratch/hello%2Ffoo.txt"

But the problem right now is the name of the file will be different.

I'm using a third-party service, that will for example download a file from my blobstorage, and save the file in their own system as "foo.txt", but if i use the new version, the third-party service will name the file "hello2Ffoo.txt" which is not what i wanted.

This means the fix to my problem is that i either have to manually replace all "%2F" to "/" or use the old 12.4.4 version.

In my example, i'm using Storage with localhost emulator, but the same thing happens if i used Storage on Azure.

I dont see anywhere in the release notes that made this change.
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md

So was this intended or is it a bug?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
This is by design, we got a lot of complaints about the previous behavior.  The storage service considers encoded and unencoded paths to be the same.

**Comment by Assassinbeast** [comment]
@seanmcc-msft Okay, so this case is closed now, right?
