### ISSUE TITLE
Error message is unclear when there is more than one User assigned MI

### ISSUE THREAD

**Issue by kaerm** [Azure/azure-sdk-for-net#14851]
When there is more than one user assigned MI the error coming from Azure.Identity only says 
`The ChainedTokenCredential failed to retrieve a token from the included credentials.` 
It would be great if the error could be more descriptive to make it easier to debug 

azsdke2e

**Comment by christothes** [comment]
Hi @kaerm - Thanks for the feedback! Could you describe a configuration example that reproduces this error?

**Comment by kaerm** [comment]
No clue at this point - this was 6 months ago

**Comment by jongio** [comment]
I'm going to try to repro.  Will re-open if I can.

I believe this happens when you have more than one user assigned managed identity assigned to a resource and then try to use one of them without specifying a client id.
