### ISSUE TITLE
[BUG] Azure.Identity DeaultAzureCredential reading from an unexpected AD tenant

### ISSUE THREAD

**Issue by SOFSPEEL** [Azure/azure-sdk-for-net#14867]
**Describe the bug**
On the following code:
```
 var configurationRoot = configurationBuilder
                .AddAzureAppConfiguration(options =>
                {
                    var credential = new DefaultAzureCredential();
                    options
                    .Connect(new Uri(appConfigEndpoint), credential);

                    if (connectToKeyVault)
                    {
                        options.ConfigureKeyVault(kv =>
                        {
                            kv.SetCredential(credential);
                        });
                    }
                  
                   
                ).Build();
```

**Expected behavior**
To be able to connect

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

Getting the following exception:

`{"Service request failed.\r\nStatus: 401 (Unauthorized)\r\n\r\nHeaders:\r\nServer: openresty/1.15.8.3\r\nDate: Thu, 03 Sep 2020 19:52:42 GMT\r\nConnection: keep-alive\r\nWWW-Authenticate: HMAC-SHA256,Bearer error=\"invalid_token\", error_description=\"The access token is from the wrong issuer. It must match the AD tenant associated with the subscription, to which the configuration store belongs. If you just transferred your subscription and see this error message, please try back later.\"\r\nx-ms-request-id: 551a2e10-ef8b-4967-b8a1-51f13aea435f\r\nx-ms-client-request-id: 5bf5a03c-21f6-46a6-90ca-8605ddc5d832\r\nx-ms-correlation-request-id: 551a2e10-ef8b-4967-b8a1-51f13aea435f\r\nAccess-Control-Allow-Origin: *\r\nAccess-Control-Allow-Credentials: true\r\nAccess-Control-Expose-Headers: DNT, X-CustomHeader, Keep-Alive, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Authorization, x-ms-client-request-id, x-ms-useragent, x-ms-content-sha256, x-ms-date, host, Accept, Accept-Datetime, Date, If-Match, If-None-Match, Sync-Token, x-ms-return-client-request-id, ETag, Last-Modified, Link, Memento-Datetime, retry-after-ms, x-ms-request-id, WWW-Authenticate\r\nStrict-Transport-Security: max-age=15724800; includeSubDomains\r\nContent-Length: 0\r\n"}`

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Run function app locally via vs.net, note that the connection works when running in Azure environment.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Identity 1.22.0] 
 - Function app .net core 3.1 running locally in VS.NET 2019

Note that tools>options>Azure Service Authentication>Account Selection is logged into an account that has App Configuration Data Reader role to Azure App Config.

Note too that at one point I was able to connect locally, but it stopped working even though there were no changes to account for the "The access token is from the wrong issuer" issue.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by schaabs** [comment]
@SOFSPEEL Thanks for filing this issue, sorry you're running into this trouble authenticating locally. Does the account that you've logged into have access to multiple tenants? If so you'll need to set `SharedTokenCacheTenantId`, and `VisualStudioTenantId` options in `DefaultAzureCredentialOptions` to the appropriate tenant when constructing the `DefaultAzureCrendential`. Also can you verify that the account you've logged into is in the same tenant as the app config resource you're trying to access.
