### ISSUE TITLE
build a azure .net for coreclr

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-sdk-for-net#1486]
please provide a coreclr build of the azure sdk for .net to allow cross platform asp.net web application to use azure services with little or no code change; ideally a solution where dependency injection of the implementation of the appropriate clr/coreclr dll would be good.

**Comment by mayurid** [comment]
@grahamehorner : We are already working on this. You can look at the following branch for the latest: https://github.com/Azure/azure-sdk-for-net/tree/AutoRest and watch this space for updates.

/cc : @jianghaolu @stankovski
