### ISSUE TITLE
[Azure.Core] Test Environment Exception When Optional Environment Variable Not Set

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#14869]
# Observed Behavior

The [`TestEnvironment::GetRecordedOptionalVariable`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.TestFramework/src/TestEnvironment.cs#L171) method reads the value of the environment variable, which may be `null` when not defined.   That value is then passed into the `RecordedVariableOptions` when specified which attempts to parse the value using the [`ConnectionString`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/ConnectionString.cs) type, causing an exception when validated due to the connection string value itself being null.  

This was observed in the Service Bus library, when it's [`ServiceBusTestEnvironment::OverrideServiceBusConnectionString`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Infrastructure/ServiceBusTestEnvironment.cs#L109) is not set.

# Expected Behavior

- Optional environment variables do not need to be set and do not result in an exception when `null`.
- Using `GetRecordedOptionalVariable` with an optional environment variable is safe.

# Implementation Thoughts

It looks as if the most appropriate place to adjust behavior would either be within the `TestEnvironment`, where null or empty values are not passed to the `RecordedVariableOptions` or within the options, adding a null or empty check before processing the connection string.  I'm not sure of the intent for having overrides or extensions to `RecordedVariableOptions` where it may be desirable to invoke regardless of value.

**Comment by jsquire** [comment]
@pakrym:  If you can help me understand a bit more about the intention of `RecordedVariableOptions`,  I'm happy to make the fix.

**Comment by pakrym** [comment]
The intent of `RecordedVariableOptions` is for consumers to be able to describe what secrets are inside the value of the variable so we can sanitize them before storing it.

In this case skipping the entire code-path when no variable exists seems the right thing to do.

**Comment by jsquire** [comment]
Fixed By #14906
