### ISSUE TITLE
Avro serializer fails to deserialize a Dictionary<TKey, TValue> with more then 1026 KeyValuePairs.

### ISSUE THREAD

**Issue by YuvalItzchakov** [Azure/azure-sdk-for-net#1487]
Here is a minimal, complete reproduce of the problem:

```
void Main()
{
    Dictionary<int, int> dsi = new Dictionary<int, int>();
    for (int i = 0; i < 1027; i++)
    {
     dsi.Add(i, i);
    }

    var serializer = AvroSerializer.Create<Dictionary<int, int>>();
    var ms = new MemoryStream();
    serializer.Serialize(ms, dsi);
    ms.Seek(0, SeekOrigin.Begin);
    var result = serializer.Deserialize(ms);
}
```

Basically, when the dictionary has more than 1024 values, we get a SerializationException with the error message:

"Invalid integer value in the input stream."

When trying to deserialize the stream. I'm assuming this has something to do with the memory optimization performed by the EnumerableSerializer.

**Comment by shahabhijeet** [comment]
@YuvalItzchakov please open a new issue if the problem still exists/repros.
