### ISSUE TITLE
[FEATURE REQ] Add CidrBlock logic to Azure SDK

### ISSUE THREAD

**Issue by scottgorlick** [Azure/azure-sdk-for-net#14883]
**Library or service name.**
What library or service is this request related to? Azure Networking as well as any other service that uses CIDR notation for ACLs.
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
I have an object that I use to provision Address space across multiple resources by doing CIDR logic on top of System.Net.IPAddress class and the use of a couple new structs (IP4Numeric and IP6Numeric) to be able to do the arithmetic on the data.  Code is "complete" for my use cases, unit tests are in place for "happy-path" and some failure conditions.

dotnet rejected the feature, but I'm sure this logic will be very useful for Azure implementations.

dotnet Issue:
https://github.com/dotnet/runtime/issues/36428 

note... i've added these two methods to CidrBlockExtensions since that issue was created:
public static CidrBlock NextBlock(this CidrBlock cidrBlock;
public static IEnumerable<CidrBlock> Subnet(this CidrBlock cidrBlock, int howMany)

an example use of this for the use case where I have a "cloud data center" and I want to cut it up into subnets per resource group... then i can cut that up into VNets and Subnets.

Resource Group -> VNet subnetting (sorry for the overloading of term, but the VNet is a subnet of the overall data center supernet):

``` C#
            var rgAddressSpace = new Dictionary<string, CidrBlock>(StringComparer.OrdinalIgnoreCase);
            List<string> resourceGroupNames = GetResourceGroupNames();
            var subnets = (supernetAddressSpace?.Subnet(resourceGroupNames.Count) ?? Enumerable.Empty<CidrBlock>()).ToList();
            for(int i = 0; i < resourceGroupNames.Count; i++)
            {
                var rgName = resourceGroupNames[i];
                var subnet = subnets[i];
                rgAddressSpace.Add(rgName, subnet);
            }
```

Subnetting the VNET into the ISubnet address space(s).

``` C#
            var subnetAddressSpaces = vnetAddressSpace.Subnet(subnetCount).ToList();
            var vnetName = GetResourceNameByGroupNameAndSuffix(resourceGroup.Name, VnetResourceSuffix);
            var subnets = Enumerable.Range(1, subnetCount) // ordinal based... make sure to subtract by one in the value selector in .ToDictionary
                .Select(i => Tuple.Create(i, GetResourceNameByGroupNameAndSuffix(resourceGroup.Name, SubnetSuffix, i)))
                .ToDictionary(t => t.Item2,
                             (t =>
                             {
                                 var name = t.Item2;
                                 var i = t.Item1 - 1;
                                 var subnetSpace = subnetAddressSpaces.ElementAt<CidrBlock>(i);
                                 _logger.LogDebug($"Will provision {name} with address space {subnetSpace}");
                                 return subnetSpace.ToString();
                             }));
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
This sounds like useful helper methods for CIDR scenarios. Assigning to Azure Network team for feedback.

**Comment by allegradomel** [comment]
This is interesting - bringing to PM team for discussion

**Comment by scottgorlick** [comment]
was awaiting feedback from PM Team if this was interesting or not... I can execute a PR, but I'm going to limit it to just adding the classes to your library unless the PM team decides they would like this change.
