### ISSUE TITLE
Does Azure.Storage.Blobs.BlobClient support TLS 1.2? If so, how do I turn it on?

### ISSUE THREAD

**Issue by MikeYeager** [Azure/azure-sdk-for-net#14891]
**Query/Question**
Does Azure.Storage.Blobs.BlobClient support TLS 1.2? If so, how do I turn it on?

**Environment:**
 - Azure.Storage.Blobs 12.6.0 
 - Windows 10 .NET Framework 4.7.2
 - Visual Studio 16.7.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
TLS is set through the storage account. You can set it through the portal on your storage account > configuration > Minimum TLS Version

**Comment by MikeYeager** [comment]
That's exactly what I did, but as soon as I did, I could no longer connect with the BlobClient. I had to turn it back down to TLS 1.0 in order to connect. My question is about eh client, not the Azure service. Thank you.

**Comment by amnguye** [comment]
Sorry for the misunderstanding.

Hopefully this code snippet can help
```
public static async Task ConfigureTls12()
{
    // Enable TLS 1.2 before connecting to Azure Storage
    System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;

    // Add your connection string here.
    string connectionString = "";

    // Create a new container with Shared Key authorization.
    BlobContainerClient containerClient = new BlobContainerClient(connectionString, "sample-container");
    await containerClient.CreateIfNotExistsAsync();
}
```

**Comment by MikeYeager** [comment]
Thanks Amanda. I thought it would be a setting in the client. I didn’t realize it was set across .NET. I will try this.

Mike

**Comment by MikeYeager** [comment]
It works perfectly. Apparently, that setting is for the entire app domain.

Thank you!
Mike

**Comment by amnguye** [comment]
Thanks for the follow up! Feel free to open a new issue if any other issues occur.

**Comment by Zeeshan0107** [comment]
It works perfectly. Thanks
