### ISSUE TITLE
[FEATURE REQ] Make GetBlockBlobClient mockable

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#14905]
Can't mock BlobContainerClient.GetBlockBlobClient / BlobContainerClient.GetPageBlobClient / BlobContainerClient.GetAppendBlobClient with Moq. These are all extension methods, hence not mockable. Could they be moved to BlobContainerClient as members?

For somebody who's entry point to hierarchy is  BlobContainerClient this means his code isn't unit testable - they have to write higher level tests either interacting with emulator or real account.

**Comment by kasobol-msft** [comment]
@tg-msft @seanmcc-msft do you think this is feasible ?

**Comment by seanmcc-msft** [comment]
IIRC, `GetBlockBlobClient()` is an extension method.  I'm not sure if extensions methods can be virtual.  If not, I'm not sure how to make `GetBlockBlobClient()` mockable.  @tg-msft, any ideas?

**Comment by seanmcc-msft** [comment]
> > IIRC, `GetBlockBlobClient()` is an extension method. I'm not sure if extensions methods can be virtual. If not, I'm not sure how to make `GetBlockBlobClient()` mockable. @tg-msft, any ideas?
> 
> Yeah. Therefore, I'd convert these extensions to member methods (assuming it's not a breaking change).

I believe they are extension methods so they can live in the .Specialized namespace, so I think this would be a breaking change.

**Comment by tg-msft** [comment]
We spent a LOT of time debating and crafting the progressive disclosure experience around specialized blob types and this is one of those cases where I don't think changing from extension methods would be worth it.  Revisiting that compromise would probably involve getting a lot of people in a room.  :smile:

Mocking GetBlockBlobClient doesn't enable much that customers couldn't do by just instantiating a new BlockBlobClient themselves.  I guess I could imagine somebody trying to setup a hierarchy of mocks, but it starts to feel more like fakes at that point. 

If there's a strong need, I think the best approach would be to create `protected internal virtual Get*Client` methods on BlobContainerClient that the extensions just forward into.   Then you could still mock a hierarchy of clients without changing the progressive disclosure pattern.  We'd just need to do a bit of testing and make sure it doesn't cause any problems with overload resolution when compiling our libraries.

**Comment by kasobol-msft** [comment]
Yes. I was indeed setting up a hierarchy. The entry point in the logic was BlobContainerClient (what could be injected) and blob names were resolved programatically. All was great until I started hitting code paths using specialized clients. Moq gave up and I had to switch to Azurite to avoid talking to real back end. The other option was to wrap BlockBlobClient creation with some custom factory or other mockable thing. But I feel this would bring too much complication.
These specialized client extensions really stand out from the crowd. Rest of our APIs is easily mockable, we even have a analyzer making sure they are.
I'll try the suggestion. I bet there are more mocks fans around.

**Comment by kasobol-msft** [comment]
Fixed with PR above. Usage pattern:
```
            // Arrange
            string blobName = "test";
            string leaseId = "test";
            Mock<BlobContainerClient> containerClientMock = new Mock<BlobContainerClient>();
            Mock<BlockBlobClient> blockBlobClientMock = new Mock<BlockBlobClient>();
            Mock<AppendBlobClient> appendBlobClientMock = new Mock<AppendBlobClient>();
            Mock<PageBlobClient> pageBlobClientMock = new Mock<PageBlobClient>();
            Mock<BlobLeaseClient> blobLeaseClientMock = new Mock<BlobLeaseClient>();
            containerClientMock.Protected().Setup<BlockBlobClient>("GetBlockBlobClientCore", blobName).Returns(blockBlobClientMock.Object);
            containerClientMock.Protected().Setup<AppendBlobClient>("GetAppendBlobClientCore", blobName).Returns(appendBlobClientMock.Object);
            containerClientMock.Protected().Setup<PageBlobClient>("GetPageBlobClientCore", blobName).Returns(pageBlobClientMock.Object);
            containerClientMock.Protected().Setup<BlobLeaseClient>("GetBlobLeaseClientCore", leaseId ).Returns(blobLeaseClientMock.Object);

            // Act
            var blockBlobClient = containerClientMock.Object.GetBlockBlobClient(blobName);
            var appendBlobClient = containerClientMock.Object.GetAppendBlobClient(blobName);
            var pageBlobClient = containerClientMock.Object.GetPageBlobClient(blobName);
            var blobLeaseClient = containerClientMock.Object.GetBlobLeaseClient(leaseId );

            // Assert
            Assert.IsNotNull(blockBlobClient);
            Assert.AreSame(blockBlobClientMock.Object, blockBlobClient);
            Assert.IsNotNull(appendBlobClient);
            Assert.AreSame(appendBlobClientMock.Object, appendBlobClient);
            Assert.IsNotNull(pageBlobClient);
            Assert.AreSame(pageBlobClientMock.Object, pageBlobClient);
            Assert.IsNotNull(blobLeaseClient);
            Assert.AreSame(blobLeaseClientMock.Object, blobLeaseClient);
```
