### ISSUE TITLE
[FEATURE REQ] Public constructors on Operation types for testability

### ISSUE THREAD

**Issue by riezebosch** [Azure/azure-sdk-for-net#14901]
**Library or service name.**
Azure.ResourceManager.Storage
 
**Is your feature request related to a problem? Please describe.**
```cs
[Fact]
public async Task Solve()
{
    var operations = Substitute.For<StorageAccountsOperations>();
    operations
        .StartCreateAsync("rg", Arg.Any<string>(), Arg.Any<StorageAccountCreateParameters>())
        .Returns(new StorageAccountsCreateOperation(null, null, null, null)); // <-- [CS1729] 'StorageAccountsCreateOperation' does not contain a constructor that takes 4 arguments
    
    var storage = Substitute.For<StorageManagementClient>();
    storage.StorageAccounts.Returns(operations);

    var operation = await _storage.StorageAccounts.StartCreateAsync(_rg, $"sa{DateTime.Now.Ticks}",
        new StorageAccountCreateParameters(new Sku(SkuName.StandardLRS), Kind.Storage, _location));

    await operation.WaitForCompletionAsync();
}
```

Would be really happy to turn my integration tests into unit tests but that's not impossible while these constructor(s) are internal.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by riezebosch** [comment]
The same applies for example on the `ResourceGroupsOperations` that is returned by `ResourcesManagementClient`. 

```
public virtual async Task<ResourceGroupsDeleteOperation> StartDeleteAsync(string resourceGroupName, CancellationToken cancellationToken = default)
```

The method is `virtual` so I _can_ override it with a mock, but then the return type `ResourceGroupsDeleteOperation` only has an internal constructor so I'm not able instantiate it or create a derived type.

Would be great if the method would use a the base class or interface for its return type.

**Comment by jhested** [comment]
I think it's the same issue as described here https://github.com/Azure/azure-sdk-for-net/issues/15639.

It would also follow the guidelines described here https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking

**Comment by riezebosch** [comment]
Sure, but mine was first 😛  Thanks for the heads-up on the mocking guidelines, wouldn't have found it myself but still doesn't seem to be in place for the aforementioned operations.

**Comment by jhested** [comment]
I really think this is something that needs to be addressed. It makes testing very difficult. I can do a pull request if you like, but isn't this something that should be done by autorest?

**Comment by ArthurMa1978** [comment]
We're working on the [model factory](https://github.com/Azure/autorest.csharp/issues/2112) that will provide the mocking test for all models.
