### ISSUE TITLE
Don't find URL for download Azure emulator 4.2

### ISSUE THREAD

**Issue by khanhvuNOIS** [Azure/azure-sdk-for-net#1491]
http://download.microsoft.com/download/0/F/E/0FE64840-9806-4D3C-9C11-84B743162618/MicrosoftAzureStorageEmulator.msi
I tried with link from Microsoft but actually i just got 4.1 version. Can someone give me version 4.2?

**Comment by mayurid** [comment]
@khanhvuNOIS : the 4.2 download can be found at https://azure.microsoft.com/en-us/downloads/ 
 
/cc: @perrysk-msft
