### ISSUE TITLE
[FEATURE REQ][Storage] Create Docs explaining how to configure connection pool for Storage

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#14929]
Our customers who are hitting issues with connection pool default settings are having hard time discover where to configure it.
We should come up with sample and/or doc page explaining that explicitly in Storage context.

The page should briefly explain or link to docs explaining difference between .NET FX and .NET Core.

References:
https://github.com/Azure/azure-sdk-for-net/issues/14850
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md
https://docs.microsoft.com/en-gb/archive/blogs/timomta/controlling-the-number-of-outgoing-connections-from-httpclient-net-core-or-full-framework
https://github.com/Azure/azure-sdk-for-net/issues/9087

**Comment by kasobol-msft** [comment]
related: https://github.com/Azure/azure-sdk-for-net/issues/12975

**Comment by JimSuplizio** [comment]
Hi @kasobol-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
