### ISSUE TITLE
Why are the methods all synchronous?

### ISSUE THREAD

**Issue by plettb** [Azure/azure-sdk-for-net#14920]
**Query/Question**
I assume this topic has been discussed at length, but I wasn't able to find anything, so if there's an existing thread about this, please feel free to direct me to it.

I'm very curious why all of the methods are synchronous, especially some of the long-running ones.  For example, why would "SqlElasticPool.AddNewDatabase" not be asynchronous?

**Environment:**
 - Microsoft.Azure.Management.Sql.Fluent 1.34.0 (1.0.0.66)

**Comment by yungezz** [comment]
add @xccc-msft  to help

**Comment by xccc-msft** [comment]
@plettb Thanks for opening this. You may use below instead:
```csharp
await sqlServerManager.SqlServers.Databases
                .Define(databaseName)
                .WithExistingSqlServer(sqlElasticPool.resourceGroupName, sqlElasticPool.sqlServerName, sqlElasticPool.sqlServerLocation)
                .WithExistingElasticPool(sqlElasticPool)
                .CreateAsync();
```

cc: @nickzhums 
We may consider to support async methods for this in new .NET SDK.

**Comment by lilyjma** [comment]
@plettb - did the response above help answer your question?
