### ISSUE TITLE
Add option for remote VNET peer name

### ISSUE THREAD

**Issue by anktsrkr** [Azure/azure-sdk-for-net#14936]
**Library or service name.**
What library or service is this request related to?
 _Microsoft.Azure.Management.Network.Fluent_ 
 
**Is your feature request related to a problem? Please describe.**
No way to define name of the peering from remote virtual network using Azure Management API

**Actual Result**

While running below code it is establishing the peer with random name at remote vnet end.
```
hubVNet.Peerings
                .Define("hub-to-spoke1-peering")
                .WithRemoteNetwork(spoke1VNet.Id)
                .Create();
```
![image](https://user-images.githubusercontent.com/5505886/92297201-680d0400-ef5a-11ea-905c-757bc2189e7b.png)

**Expected Result**
While defining ` .Define("hub-to-spoke1-peering")` is showing this value as source VNet peer name. 
User should be able to define the peer name for remote VNet as well.

Or, Management API should also work as az cli i.e it should not auto establish the peering between two VNet, while using` az network vnet peering create -g "sandbox" -n "spoke1-to-hub-peering" --vnet-name "spoke1-vnet" --remote-vnet "/subscriptions/xxx/resourceGroups/sandbox/providers/Microsoft.Network/virtualNetworks/hub-vnet" --allow-vnet-access` it only initiate the peer request from source vnet and to establish the connection user needs to create another peering from destination.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by anktsrkr** [comment]
Hi @allenjzhang any update on this?

**Comment by yungezz** [comment]
add @xccc-msft to help

**Comment by xccc-msft** [comment]
@anktsrkr It looks this is the [line](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Network/NetworkPeeringImpl.cs#L312) we define a random remote peer name internally. If you want to have your own value for the name, you may want to consider taking the whole block code for resource creation now.

cc: @nickzhums 
We may consider to improve this in new .NET SDK.

**Comment by lilyjma** [comment]
@anktsrkr  - I'm assuming this issue has been resolved. Tagging it as so. Please feel free to let us know otherwise.
