### ISSUE TITLE
DistributedTracing in EventGrid

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-net#14930]
Track2 SDK will auto-populate W3C headers traceparent/tracestate. However, in the case of EventGrid this is not enough:

- If the request content-type is Cloudevent and tracestate/traceparent are not populated in the event
- Then we want to copy the traceparent/tracestate into the CloudEvent extensions

Suggestion of implementation is a policy that would go after the DistributedTracing policy (otherwise we don't yet have the traceparent/tracestate values), but free to each dev to figure this out.

**Comment by JoshLove-msft** [comment]
Reopening this until we get confirmation that the approach used in .NET is okay.

**Comment by JoshLove-msft** [comment]
We ended up fixing this to make the cloud event extensions match the HTTP traceparent/tracestate.
