### ISSUE TITLE
[FEATURE REQ] Move IUtf8JsonSerializable into Azure.Core and make it public

### ISSUE THREAD

**Issue by aelij** [Azure/azure-sdk-for-net#14940]
**Library or service name.**
All 
 
**Is your feature request related to a problem? Please describe.**
Each library has its own instance of `IUtf8JsonSerializable` and it's internal. So if we wanted to serialize objects ourselves we would not be able to.

One use case for this is generating a deployment template JSON from ARM entities.

**Comment by pakrym** [comment]
Are these entities spread across libraries?

**Comment by aelij** [comment]
Yes, for example:

* `Azure.ResourceManager.Storage.Models.StorageAccount` in `Azure.ResourceManager.Storage`
* `Azure.ResourceManager.KeyVault.Models.VaultAccessPolicyParameters` in `Azure.ResourceManager.KeyVault`

**Comment by aelij** [comment]
Another compelling use case for exposing this interface - using an undocumented property by inheriting from a model and reimplementing `IUtf8JsonSerializable`.

**Comment by EugenPavlenko** [comment]
As a side affect of not accessability  of `IUtf8JsonSerializable` we can't  use ```CustomScriptExtension``` because construct a proper object  ```VirtualMachineScaleSetExtension```
If users use an anonymous type or my custom class for property `Settings` of `VirtualMachineScaleSetExtension`, they receive `System.NotSupportedException`.

**Comment by KrzysztofCwalina** [comment]
+ @ellismg 

I think it would be great to have a plan for how models would integrate with protocol method APIs. Today, to pass a model to a protocol methods, we are telling users to use RequestContent.Create(object). This is an OK solution, but an interface like IUtf8JsonSerializable would be more efficient as the implementation would use a writes and not a serializer. Similarly on the output side, it would be good to have an abstraction that allows avoiding serailization.

**Comment by pakrym** [comment]
We already have a way to opt into generating a converter for each model that calls into `IUtf8JsonSerializable` implementation. 


https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventgrid/Azure.Messaging.EventGrid/src/Generated/Models/AcsChatMessageReceivedEventData.Serialization.cs#L15

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventgrid/Azure.Messaging.EventGrid/src/Generated/Models/AcsChatMessageReceivedEventData.Serialization.cs#L106-L116

**Comment by annelo-msft** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-net/issues/25045
