### ISSUE TITLE
[DEMO BUG] Missing BlobBatchClient Members

### ISSUE THREAD

**Issue by LanceMcCarthy** [Azure/azure-sdk-for-net#14949]
**Describe the bug**

The following screenshot explains it better than a text description:

![image](https://user-images.githubusercontent.com/3520532/92403296-26698e00-f0ff-11ea-856b-a6b346c0a827.png)

**Expected behavior**

Using v 12.6 version of the .NET SDK should provide the same functionality described in the official .NET SDK examples. 

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs.Batch/samples/Sample03b_BatchingAsync.cs

**Actual behavior (include Exception or Stack Trace)**

Missing methods

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a new .NET Standard Class Library (2.0+)
2. Try to implement the code shown in the above linked demo

**Environment:**
 - Azure.Storage.Blobs 12.6
 - find the exact project setup here [LanceMcCarthy/Flusher](https://github.com/LanceMcCarthy/Flusher) (so to `src/Flusher.Common` project)
 - Visual Studio 16.7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

It would also be helpful to provide what version of `Azure.Storage.Blobs.Batch` you are using since you are looking to use our `BlobBatchClient`. I opened up our samples and they run fine with the current version (12.3.1)

**Comment by LanceMcCarthy** [comment]
The current release is v12.6.0, the demos are out of date in that aspect. I've also found some weird syntax and object usage through the examples that only make sense on 12.3.

So, this is more than just  incremental update quirks, there are some breaking changes that the demos should address as they're directly linked to from the v12 documentation.



You can find all up to the minute accurate repro info here https://github.com/LanceMcCarthy/Flusher 

- [Relevant Code](https://github.com/LanceMcCarthy/Flusher/blob/master/src/Flusher.Common/Services/AzureStorageService.cs)
- [relevant Csproj](https://github.com/LanceMcCarthy/Flusher/blob/master/src/Flusher.Common/Flusher.Common.csproj)

**Comment by amnguye** [comment]
The current release for `Azure.Storage.Blobs.Batch` is 12.3.1.
https://www.nuget.org/packages/Azure.Storage.Blobs.Batch/

I think the version you are referring to is `Azure.Storage.Blobs` which is on version 12.6.0

Taking a quick skim at your .csproj file, you don't have the `Azure.Storage.Blobs.Batch` package installed. Please install this package in order to make `BlobBatchClient`. Thanks

**Comment by LanceMcCarthy** [comment]
Bingo!

I ended up in this repo via link from the other Azure.Storage.Blob demos, so I had no idea I was redirected to other samples that required an additional nuget package 🤦‍♂️ 

Then, I guess my only feedback is to add a comment to the using statement about the NuGet package dependency... because of the shared namespace with other NuGet packages, you have no information on how to resolve the BlobBatchClient otherwise (folks do not typically clone this entire repo,  or dig around csproj when there is already an assumption you have installed the blob package)

**Comment by amnguye** [comment]
Thanks for the feedback! I'm glad you were able to build and resolve your issue.
