### ISSUE TITLE
Fetch facets only once when using Azure Search paging

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/azure-sdk-for-net#14953]
**Library or service name.**
Azure.Search.Documents 11.1.1
 
**Is your feature request related to a problem? Please describe.**

I have code similar to the following:
```csharp
var client = new SearchClient(....);
var response = client.Search<SearchDocument>("*", new SearchOptions {Facets = {"name"}).Value;
var facets = response.Facets;
var results = response.GetResults().ToList();
```

If `results` requires multiple pages, the REST call made for each page still contains `facets` in its request body, and thus `@search.facets` in its response body. Only the first call should need to do that, as the facets shouldn't change during paging.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by tg-msft** [comment]
The correct design per the service team is to never modify the continuation token returned by https://docs.microsoft.com/en-us/rest/api/searchservice/search-documents, which includes the facets.  They can technically change and you can manually iterate by page if you want access to the latest facet values.
