### ISSUE TITLE
[Azure Identity] VSCodeCredential Tests without settings can't run in sovereign cloud.

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-net#14951]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

Some [Tests](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/tests/VisualStudioCodeCredentialLiveTests.cs#L45) about authenticating with Vs code Credential with no settings file failed in  US Gov and  Azure China Cloud. 
Because in azure sdk, environment name is "Azure" while there is no settings file. This leads to only pass in azure cloud. 

![image](https://user-images.githubusercontent.com/53427149/92427081-22e90c00-f1be-11ea-8163-33e8be4cb317.png)

While running in other clouds, got following error:

 Error message:
Azure.Identity.CredentialUnavailableException : VisualStudioCodeCredential authentication unavailable. Token acquisition failed. Ensure that you have authenticated in VSCode Azure Account. ----> Microsoft.Identity.Client.MsalUiRequiredException : AADSTS90051: Invalid Delegation Token. Invalid national Cloud ID (2) is specified. Trace ID: 6f9abbdb-07ee-448e-90e3-092e08c16200 Correlation ID: 4b648ac6-6536-40bf-9709-1133b69d5189 Timestamp: 2020-09-04 08:21:27Z
@jongio @danieljurek

**Comment by danieljurek** [comment]
Re-adding the needs-triage label, it looks like msftbot removed this label and this issue may not have been assigned.

**Comment by christothes** [comment]
Hi @Luyunmt If you set the appropriate settings property in a `settings.json` file, does it work as expected?
