### ISSUE TITLE
ComputeManagementClient.VirtualMachines.GetWithInstanceViewAsync missing

### ISSUE THREAD

**Issue by ezwebs** [Azure/azure-sdk-for-net#1495]
Upgraded to the 10.0.0.0 pre-release. Was using the GetWithInstanceViewAsync method in the previous version in order to get the powerstate of a vm, e.g. "vm running". This method has now disappeared. Are there plans to bring it back or is there now a different way of getting the vm powerstate?

**Comment by shahabhijeet** [comment]
@ezwebs please open a new issue if the problem still exists/repros.
