### ISSUE TITLE
[QUERY]

### ISSUE THREAD

**Issue by Ekaterina543** [Azure/azure-sdk-for-net#14957]
**Query/Question**
How can we help?sekretd

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by Ekaterina543** [comment]
> **Query/Question**
> How can we help?sekretd
> 
> **Environment:**
>  - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
>  - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework

**Comment by jsquire** [comment]
Closing, as this appears to be a mistaken submission.  Please feel free to reopen if you believe that further discussion is needed.
