### ISSUE TITLE
Allow .NET PR build pipeline to run Analyze in-parallel with tests

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-sdk-for-net#14970]
Currently, the Analyze step runs after all tests steps have passed. I'm told that this was for a reason where it would download the package and use it. But now, it does build and run the generation steps so there is potential to parallelize it. So, the ask is to have Analyze run in-parallel with the Test steps. Basically, it would go: Build -> [Everything else in parallel].

**Comment by weshaggard** [comment]
@pakrym does the code generation steps now always build all the packages? If so perhaps we can start doing this step in parallel and not wait to download the packages.

**Comment by pakrym** [comment]
Code generation step doesn't build packages but Export-API does build dlls.

**Comment by kurtzeborn** [comment]
@pakrym, @weshaggard mentioned you have a PR for this already.
