### ISSUE TITLE
Storage SDK follow up from ICM incident

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-for-net#14984]
The incident has been mitigated, but there is a request for further investigation into a possible issue with the storage SDK.  Here's a link to the ICM incident containing the details: https://portal.microsofticm.com/imp/v3/incidents/details/195994550/home

@amishra-dev would you assign as appropriate.

CC: @tg-msft, @seanmcc-msft

**Comment by jsquire** [comment]
This is now a 3-year old IcM ticket.   I do not believe follow-up is relevant any longer.
