### ISSUE TITLE
[Event Hubs Client] All Tests fail while authrityhost from  environment  doesn't end with "/"

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-net#15009]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.
Based on following [code](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Testing/LiveResourceManager.cs#L90), all clouds' authorityhost must  end with "/". But the authrityhost from environment can end with "/" or not. And in pipline variable only US GOV end with "/".
This leads to all tests fail. 

![image](https://user-images.githubusercontent.com/53427149/92563944-f65eee00-f2aa-11ea-8e91-83609cda8f40.png)

Now pipline variable :
aad-azure-sdk-test-authority-uri : https://login.microsoftonline.com
aad-azure-sdk-test-authority-uri-cn : https://login.chinacloudapi.cn
aad-azure-sdk-test-authority-uri-gov : https://login.microsoftonline.com/
@jongio @danieljurek

**Comment by jsquire** [comment]
Fixed by: #15532 15532
