### ISSUE TITLE
[BUG/QUESTION] Where is NameValidator?

### ISSUE THREAD

**Issue by hansmbakker** [Azure/azure-sdk-for-net#15016]
**Query/Question**
`Microsoft.Azure.Storage.Common` had the useful [`NameValidator` class](https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/NameValidator.cs). I can't find the same functionality in the new `Azure.Storage` client library.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs, major version 12

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
We currently don't support it in v12. This issue is a duplicate of issue https://github.com/Azure/azure-sdk-for-net/issues/9611
