### ISSUE TITLE
[QUERY] While performing online migration getting status code ‘Running’ only, when we will get status ‘completed’

### ISSUE THREAD

**Issue by click2cloud-shailesh** [Azure/azure-sdk-for-net#15017]
**Query/Question**

Hello there,
We are trying to perform MySQL to Azure MySQL online database migration using Azure .net SDK. The migration activity seems to be working fine. However, we do not see any change in the status field. The only status update provided is that migration is still 'Running'. Is there a way to mark the status of the migration as 'Completed' from 'Running' once the migration is complete.
Appreciate your help in the context.
Thank you

**Environment:**
 - azure .net SDK 
 - IDE and version : [e.g. Visual Studio 2019]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ajlam** [comment]
@click2cloud-shailesh - can you confirm if you are using the Azure Database Migration Service?

**Comment by click2cloud-shailesh** [comment]
Yes, using the Azure Database Migration Service.

**Comment by ajlam** [comment]
@click2cloud-shailesh - thanks for confirming. I've just routed the issue to our DMS team :)

**Comment by radjaram** [comment]
Hi @click2cloud-shailesh , Thanks for the question. Migration to MySQL is only currently supported in "Online" mode which will continue to return RUNNING status until the rows are copied over. Once the copy is done, the Database Level results for the task output should return SyncDatabaseMigrationReportingState as READYTOCOMPLETE. Here's the link: https://docs.microsoft.com/en-us/rest/api/datamigration/tasks/createorupdate#syncdatabasemigrationreportingstate 
Once it returns READYTOCOMPLETE, you need to issue a command to complete the migration. Reference: https://docs.microsoft.com/en-us/rest/api/datamigration/tasks/createorupdate#migratesynccompletecommandinput
Please let us know if we can help further. Thanks.
