### ISSUE TITLE
Reduce to only one label in App Configuration

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/azure-sdk-for-net#15033]
Right now we have both `AzConfig` and `App Configuration` labels, we should have only one, and it has to be synced with other languages.

**Comment by AlexanderSher** [comment]
FYI: @AlexanderSher @annelo-msft @AlexGhiondea @richardpark-msft

**Comment by jsquire** [comment]
@AlexGhiondea, @lilyjma:  Would you please advise to the label that you'd prefer?

**Comment by AlexGhiondea** [comment]
I have resolved this across all the repos.
