### ISSUE TITLE
"SharedTokenCacheCredential authentication failed: Persistence check failed" when using Azure App Service

### ISSUE THREAD

**Issue by luckerby** [Azure/azure-sdk-for-net#15036]
I'm trying to use an ASP.NET Core app to obtain a user delegation SAS token. I'm using the standard Visual Studio ASP.NET Core web app template, which comes complete with cloud authentication.

The relevant code for `OnGet`, based on the sample [here](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-user-delegation-sas-create-dotnet), is below:
```
public void OnGet()
{
     string accountName = "storage-account-name";

     // Construct the blob endpoint from the account name.
     string blobEndpoint = string.Format("https://{0}.blob.core.windows.net", accountName);

     // Create a new Blob service client with Azure AD credentials.  
     var defaultCreds = new SharedTokenCacheCredential();
     BlobServiceClient blobClient = new BlobServiceClient(new Uri(blobEndpoint),
                                                                    defaultCreds);

     // Get a user delegation key for the Blob service that's valid for seven days.
     // You can use the key to generate any number of shared access signatures over the lifetime of the key.
     UserDelegationKey key = blobClient.GetUserDelegationKey(DateTimeOffset.UtcNow,
                                                                                DateTimeOffset.UtcNow.AddDays(7));
     ......
}
```

The problem I'm running into is that despite the fact that this runs just fine locally - under Visual Studio's own IIS Express instance - things break apart when publishing to an Azure App Service, as follows:

```
CryptographicException: The data protection operation was unsuccessful. This may have been caused by not having the user profile loaded for the current thread's user context, which may be the case when the thread is impersonating.
System.Security.Cryptography.ProtectedData.ProtectOrUnprotect(byte[] inputData, byte[] optionalEntropy, DataProtectionScope scope, bool protect)

MsalCachePersistenceException: Persistence check failed. Inspect inner exception for details
Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.VerifyPersistence()

AuthenticationFailedException: SharedTokenCacheCredential authentication failed: Persistence check failed. Inspect inner exception for details
Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
```

For the first exception, I do remeber running into a similar message for ASP.NET on .NET Framework, which was solved by loading the user's profile in the host process. For ASP.NET Core web apps hosted in Azure, the solution seems to be to create a `WEBSITE_LOAD_USER_PROFILE` application setting and set it to `1`.  Yet this doesn't work, and the exception changes to:
```
CredentialUnavailableException: SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
```

I know it's the `GetUserDelegationKey` method that triggers the exceptions, however I can't figure out what's missing in order to make this work on an App Service, similar to how it behaves locally.

I know I can probably use `DefaultAzureCredential` and set environment variables that provide service credentials, as described [here](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet), but I wanted to go the route of the user delegation SAS tokens.

A note: I simply used non-async methods just for extra troubleshooting, but the async `GetUserDelegationKeyAsync` behaves just the same.

**Environment:**
 - Azure.Identity v1.2.2, Azure.Storage.Blobs 12.6.0 
 - .NET Core 3.1.0 for the local host / Azure AppService
 -  Visual Studio 16.5.0 Preview 2.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by schaabs** [comment]
@luckerby Thanks for reaching out with this question. 

Looking at your code you're using the `SharedTokenCacheCredential` directly. 
```c#
     // Create a new Blob service client with Azure AD credentials.  
     var defaultCreds = new SharedTokenCacheCredential();
     BlobServiceClient blobClient = new BlobServiceClient(new Uri(blobEndpoint),defaultCreds);
```
I wouldn't expect that the `SharedTokenCacheCredential` will work when deployed to an App Service as there would likely be no cache on disk, and the error you're getting from `GetUserDelegationKey` is caused by this. As you posited in your question you could use the `DefaultAzureCredential` to create the `BlobServiceClient`.
```c#
     var defaultCreds = new DefaultAzureCredential();
     BlobServiceClient blobClient = new BlobServiceClient(new Uri(blobEndpoint),defaultCreds);
```
 If you choose to use `DefaultAzureCredential` you could authenticate when deployed either by supplying service principal credentials though the environment, or I alternatively would suggest enabling managed identity on the App Service. When running locally the `DefaultAzureCredential` will fallback to using the `SharedTokenCacheCredential` so your experience there should be the same. More information on using the `DefaultAzureCredential` can be found in the Azure.Identity [README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/README.md#defaultazurecredential).

I hope this answers your question. If not, or if you're still experiencing issues please feel free to reopen the issue or reach out to me.

**Comment by luckerby** [comment]
Thanks, @schaabs. I eventually got around it by using a service SAS token. I would've liked using the user delegation SAS one because there wouldn't have been any "super" credential to store anywhere - access would have been granted by the user tokens themselves.

I think my mistake was thinking that the store `SharedTokenCacheCredential` checks against is some cached repository of tokens used by clients that were "seen" so far, as opposed to the local cache of that specific machine. In other words, I was expecting it to work server-side, but it looks to be designed for the client-side part.
