### ISSUE TITLE
Partial events deserialize but don't return data.

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#15062]
```
EventGridEvent.Parse(@"{""data"":""""}").Single().GetData<string>();
```

Would fail with the argument null exception during GetData call

Related to: https://github.com/Azure/azure-sdk-for-net/pull/15058
cc @ellismg

**Comment by ellismg** [comment]
FWIW, @JoshLove-msft, In JavaScript land, we throw an error in our parser if the data is malformed (i.e. there are JSON errors) or any required fields of the event type are missing (or are of the wrong type)).
