### ISSUE TITLE
Allow status of backup and restore operations to be queried

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#15067]
To facilitate long-running backup and restore operations, provide idiomatic APIs to query status. This may be on the `KeyVaultBackupClient` directly, or on public operation classes.

**Comment by christothes** [comment]
The possible statuses are `InProgress`, `Succeeded`, and `Failed`. IMO, The idiomatic mechanism to query status of an operation utilizing the standard set of properties is as follows:
- Evaluate the `HasCompleted` property of the operation
  - If true
    - Status = `Succeeded`: evaluating the `Value` property returns the result of the operation
    - Status = `Failed`: evaluating the `Value` property throws
  - If false
       - Status = `InProgress`
- Operation started in some other context
  - Hydrate the operation, given the `Id` of a previously started operation with [this ctor](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Administration/src/BackupOperation.cs#L34)
  - rules above apply

@heaths Were you thinking we should extend the operation classes to represent status more explicitly?

**Comment by heaths** [comment]
I should've been more clear. We need to expose a way to get the long-running `Operation<T>` classes after the fact, e.g. if the application was shut down but later restarted and needed to query status. The `CertificateOperation` in Certificates allows this via a constructor, taking the `CertificateClient` and certificate name. Something like that could be an option here as well.

**Comment by christothes** [comment]
> I should've been more clear. We need to expose a way to get the long-running `Operation<T>` classes after the fact, e.g. if the application was shut down but later restarted and needed to query status. The `CertificateOperation` in Certificates allows this via a constructor, taking the `CertificateClient` and certificate name. Something like that could be an option here as well.

Perhaps I am missing something, but don't we have that [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Administration/src/BackupOperation.cs#L34)?

**Comment by heaths** [comment]
Maybe this didn't need opened then when I was doing all the langs - might've just been in err. However, those parameters need to flip. Client should go first, but I already opened a bug on that: #15065. Please make sure the restore operation is comparable.
