### ISSUE TITLE
No way to deserialize a single event without allocating and discarding an array

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#15063]
The EventGrid WebJobs extension supports the ability to return a single event from function as a string or JsonElement, currently, we have to use `EventGridEvent.Parse` and then always discard the array. Would be nice if we had an `EventGridEvent.ParseSingle` method.

Related: https://github.com/Azure/azure-sdk-for-net/pull/15058

cc @ellismg

**Comment by JoshLove-msft** [comment]
This is now fixed as there is an EventGridEvent.Parse method.
