### ISSUE TITLE
[BUG] BlobUriBuilder URL encodes slashes in blob names

### ISSUE THREAD

**Issue by veleek** [Azure/azure-sdk-for-net#15064]
**Describe the bug**
When working with blobs with slashes in the name the slashes get URL encoded by BlobUriBuilder which makes the URLs parse incorrectly later when trying to extract path segments.

**Expected behavior**
Slashes should not be encoded by BlobUriBuilder.
```csharp
var container = blobClient.GetBlobContainerClient("animals");
var blob = container.GetBlobClient("mammals/cat.png");
var blobUri = blob.Uri;

blobUri == "https://storageaccount.blob.core.windows.net/animals/mammals/cat.png"
```

**Actual behavior (include Exception or Stack Trace)**
Slashes are encoded by BlobUriBuilder

```csharp
blobUri == "https://storageaccount.blob.core.windows.net/animals/mammals%2fcat.png"
```

**To Reproduce**
See expected behavior.

**Environment:**
 - Name and version of the Library package used: <PackageReference Include="Azure.Storage.Blobs" Version="12.6.0" />
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Core App
 - IDE and version : Visual Studio 16.8.0 preview 2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
This is by design, the service considers `mammals/cat.png` and `mammals%2fcat.png` to be the same blob.  I recommend using the `Name` property instead of `Uri` if you would like to later extract path segments.

**Comment by veleek** [comment]
@seanmcc-msft - The URI is passed back to the client who doesn't have a blob object.  They just have the full URL that they need to parse.  Trying to ensure that they're only URL decoding the appropriate portions is difficult while still maintaining parsebility.   For example:

```
var x = HttpUtility.UrlEncode("toys/ball?.jpg").Dump();
var u = "https://storage/things/" + x;
// x == https://storage/things/toys%2fball%3f.jpg
new Uri(u).Segments ==> 
   things/
   toys%2fball%3f.jpg

new Uri(HttpUtility.UrlDecode(u).Dump()).Segments.Dump();
   things/
   toys/
   ball
```

Should I selectively URL decode slashes on the client to extract the folder names?  I feel like this is a change from older client behavior.

**Comment by seanmcc-msft** [comment]
We've had a lot of trouble with not URL encoding blob names:
- https://github.com/Azure/azure-sdk-for-net/issues/12738
- https://github.com/Azure/azure-sdk-for-net/issues/12019
- https://github.com/Azure/azure-sdk-for-net/issues/11368
- https://github.com/Azure/azure-sdk-for-net/issues/10272
- https://github.com/Azure/azure-sdk-for-net/issues/7720

I recommend decoding the URI, or splitting on "%2f".

-Sean

**Comment by veleek** [comment]
Okay, thank you for the clarification and references @seanmcc-msft.  I'll look for an appropriate solution!

**Comment by mgroetan** [comment]
> This is by design, the service considers `mammals/cat.png` and `mammals%2fcat.png` to be the same blob. I recommend using the `Name` property instead of `Uri` if you would like to later extract path segments.

To my experience, this behaviour was recently changed in the 12.**9.0** version, no longer escaping the slashes.

This [change](https://github.com/Azure/azure-sdk-for-net/pull/21424/files/2fec800816c5cc044c38958b7288ec02afb50a9a#diff-9d1e90f229d4b52f7bbfb4cde696b8d81c0f37170b34dd5beea293583d81688b) seems to be the one:
![image](https://user-images.githubusercontent.com/9464822/123291187-2dd51900-d512-11eb-8173-556e192e6229.png)

Was this intentional, or should we expect it to be reverted at some point, as it seems to contradict your "by design" statements...?

**Comment by seanmcc-msft** [comment]
@amnguye @kasobol-msft, we need to look into this.  @mgroetan brings up a good point.

**Comment by kasobol-msft** [comment]
@mgroetan The change is intentional and was part of larger internal refactoring. Service doesn't distinguish `/` from `%2f` but considering multiple asks to not encode `/` we decided to change it. As @seanmcc-msft  mentioned we recommend to use `BlobName` rather than `Uri` for parsing purposes.

**Comment by adamcastle** [comment]
> This is by design, the service considers `mammals/cat.png` and `mammals%2fcat.png` to be the same blob. I recommend using the `Name` property instead of `Uri` if you would like to later extract path segments.

HI,
Are you able to supply some sample code of what you mean? I just cannot get this to work.
Thanks and Regards,
Adam.

**Comment by vrozovmicrosoft** [comment]
12.9.0 version fixes the behavior for '/' encoding, but not for other characters (e.g. '+').
In SDK 11, none of special characters was encoded.
So now, the behavior is even more inconsistent: some character are encoded and some are not.
Can this be aligned?

**Comment by chuanqisun** [comment]
Looks like 12.14 is changing the `/` encoding further. See details in [#30271](https://github.com/Azure/azure-sdk-for-net/pull/30271) and release note: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md#12140-2022-10-12

Based on my observation, as of 12.14, the entire filename, including `/` is not encoded.
