### ISSUE TITLE
StartRecognizeCustomFormsWithoutLabels different behavior btw 2.0 and 2.1-preview.1

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#15075]
Test [`StartRecognizeCustomFormsWithoutLabels`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/FormRecognizerClientLiveTests.cs#L983) started failing when updating our code base to target 2.1-preview.1. This is a new error that we didn't see in the previous testing we did.
The model is not returning the field "Hero Limited" for v2.1-preview.1 although it was returning it for v2.0.

Service team has been contacted. The purpose of this issue is to track progress for the issue

**Comment by maririos** [comment]
Tracking https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/8495101

**Comment by kinelski** [comment]
The original behavior is very unlikely to be restored at this point since version 2.1 is already out. Closing this as there's nothing else to do on the SDK side.
