### ISSUE TITLE
Error in Setting up Hive and Oozie Metastore using _hdiManagementClient.Clusters.Create method

### ISSUE THREAD

**Issue by musazaidi** [Azure/azure-sdk-for-net#1507]
When you pass in Hive and Oozie Metastore information to ClusterCreateParamters objects it always complain about not able to connect to the Azure SQL Server. I have verified the SQL Server credentials and the flag on the server to allow access to Azure services. I am able to create HdInsight server attaching it to Azure Sql Server for metastor using portal but not using the Azure SDK.

Are we storing the connection string for the hive configs in the Ambari Server log table.

```
        var parameters = new ClusterCreateParameters
        {
            ClusterSizeInNodes = NewClusterNumNodes,
            Location = NewClusterLocation,
            ClusterType = NewClusterType,
            OSType = NewClusterOSType,
            Version = NewClusterVersion,

            DefaultStorageAccountName = ExistingStorageName,
            DefaultStorageAccountKey = ExistingStorageKey,
            DefaultStorageContainer = ExistingContainer,

            UserName = NewClusterUsername,
            Password = NewClusterPassword,
            SshUserName = SSHUserName,
            SshPassword = SSHPassword,

            HiveMetastore = new Metastore(AzureSqlServerName, "hive", AzureSqlUserName, AzureSqlPassword),
            OozieMetastore = new Metastore(AzureSqlServerName, "oozie", AzureSqlUserName, AzureSqlPassword)
        };
```

**Comment by musazaidi** [comment]
You will get the error below:

DeploymentDocument 'AmbariConfiguration_1_7' failed the validation. Error: 'Cannot connect to Hive metastore using user provided connection string'

**Comment by cindygross** [comment]
Try adding a firewall exception rule for the metastore/SQL server (it's at the server level, not the database).

**Comment by musazaidi** [comment]
At the server level access from other Azure services is enabled.

**Comment by matthieuklotz** [comment]
Hi,
I have the same issue with Powershell (Latest release).
@musazaidi , since your last comment, have you resolved your issue ? And if its the case, how ?

**Comment by Estebanhuerta11** [comment]
Hi,
I have the same problem in azure templates.
@musazaidi Have you resolved your issue?

**Comment by musazaidi** [comment]
nope

**Comment by mariomh** [comment]
I get this issue as well - anyone solved it?

**Comment by joelhulen** [comment]
Ambari requires the fully qualified SQL Server name, including `.database.windows.net`. Just make sure `.database.windows.net` is appended to the end of the `AzureSqlServerName` value.

**Comment by AbhiMadav** [comment]
Running into this when using the ARM deployment. Is there any change in the connection string that needs to be done?

**Comment by joelhulen** [comment]
@AbhiMadav Did you set the SQL server and database database as a dependency for your cluster in the ARM template? This ensures the database has been provisioned and is ready before the cluster has been created. Also, did you use the fully qualified SQL Server name?

For example:

```json
      "dependsOn": [
        "[resourceId('Microsoft.Storage/storageAccounts', variables('clusterAttachedStorageName'))]",
        "[resourceId('Microsoft.Sql/servers', variables('serverName'))]",
        "[resourceId('Microsoft.Sql/servers/databases', variables('serverName'), variables('dataBaseName'))]",
        "[concat('Microsoft.Network/virtualNetworks/',variables('clusterVNetName'))]"
      ],
```

Also, what do your `hive-site` and `hive-env` parameters look like? Should be something similar to this:

```json
"hive-site": {
    "javax.jdo.option.ConnectionDriverName": "com.microsoft.sqlserver.jdbc.SQLServerDriver",
    "javax.jdo.option.ConnectionURL": "[concat('jdbc:sqlserver://',variables('serverName'),'.database.windows.net',';database=',variables('dataBaseName'),';encrypt=true;trustServerCertificate=true;create=false;loginTimeout=300')]",
    "javax.jdo.option.ConnectionUserName": "[parameters('databaseAdminUsername')]",
    "javax.jdo.option.ConnectionPassword": "[parameters('databaseAdminPassword')]"
},
"hive-env": {
    "hive_database": "Existing MSSQL Server database with SQL authentication",
    "hive_database_name": "[concat(variables('dataBaseName'), copyIndex())]",
    "hive_database_type": "mssql",
    "hive_existing_mssql_server_database": "[concat(variables('dataBaseName'), copyIndex())]",
    "hive_existing_mssql_server_host": "[concat(variables('serverName'),'.database.windows.net')]",
    "hive_hostname": "[concat(variables('serverName'),'.database.windows.net')]"
}
```

**Comment by AbhiMadav** [comment]
Hey @joelhulen,

Thanks for the reply. I am trying to setup the new cluster using an existing metastore SQL server db and therefore skipped the 'dependsOn' property in the template. 

My `hive-site` & `hive-env` configurations look similar to the one specified by you. The connection URL specified is fully qualified.  

`"hive-site": {
              "javax.jdo.option.ConnectionPassword": "[parameters('hiveMetaDbPassword')]",
              "javax.jdo.option.ConnectionURL": "jdbc:sqlserver://<server_name>;database=<database_name>;encrypt=true;trustServerCertificate=true;create=false;loginTimeout=300",
              "javax.jdo.option.ConnectionUserName": "[parameters('hiveMetaDbUserName')]",
              "javax.jdo.option.ConnectionDriverName": "com.microsoft.sqlserver.jdbc.SQLServerDriver"
            },
            "hive-env": {
              "hive_existing_mssql_server_database": "[parameters('hiveMetastoreDatabaseName')]",
              "hive_existing_mssql_server_host": "[parameters('hiveSqlServerName')]",
              "hive_hostname": "[parameters('hiveSqlServerName')]",
              "hive_database": "Existing MSSQL Server database with SQL authentication",
              "hive_database_name": "[parameters('hiveMetastoreDatabaseName')]",
              "hive_database_type": "mssql"
            }`

**Comment by AbhiMadav** [comment]
Got it working. I was trying with the same deployment name and the cluster name for multiple times and changing those worked. I am guessing there is some king of caching for the deployments which couldn't reflect the latest state.

**Comment by Bizz247** [comment]
Yeah so I found out this issue for me was caused by not having the right encoding on the JSON file that’s being uploaded. PowerShell uses ucs-2 by default.. if you choose utf8 on -encoding it will actually encode to utf8bom.. 

PowerShell 6 has a “new” encoding that’s called utf8nobom which will ACTUALLY our-file to regular utf-8.. when in doubt validate with notepad++ !!
