### ISSUE TITLE
[WebJobs] Follow up on EventGrid event serialization and formats in the extension

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#15070]
See the following comments from initial PR:

https://github.com/Azure/azure-sdk-for-net/pull/15058#discussion_r486619847

https://github.com/Azure/azure-sdk-for-net/pull/15058#discussion_r486623256

https://github.com/Azure/azure-sdk-for-net/pull/15058#discussion_r486627669

**Comment by JoshLove-msft** [comment]
Issues are all addressed.
