### ISSUE TITLE
DataProtection for Azure & legacy ASP.NET

### ISSUE THREAD

**Issue by yahorsi** [Azure/azure-sdk-for-net#15095]
Hi Guys,

We're gradually migrating solution from the legacy ASP.NET to the .NET Core and at the same time going to deploy on Azure. We need to share the auth cookie between ASP.NET and ASP.NET Core solution. Once legacy and core sites could be deployed on the different machines we need somehow to share data protection key. There are a number of built-in providers for .NET Core but we were unable to find one for the legacy ASP.NET. DataProvider we're looking for should be able to store keys in the blob storage.  Are there DataProvider available in the SDK that can be used?

Thanks
Regards

**Comment by jsquire** [comment]
Hi @yahorsi.   Apologies if I'm misunderstanding your question, but it does not appear to be related to one of the Azure client libraries, but rather to the ASP.NET platform.  Unfortunately, that is not something that we can assist with.  I'd recommend asking your question in the [ASP.NET](https://github.com/dotnet/aspnetcore/issues) repository, where folks would be better able to help.

I'm going to close this out, but please feel free to reopen if I'm overlooking something or you'd like to discuss further.
