### ISSUE TITLE
[BUG][Face] OperationStatus does not deserialize correctly due to JSON property name mismatches

### ISSUE THREAD

**Issue by v-jaswel** [Azure/azure-sdk-for-net#15120]
**Describe the bug**
When I call SnapshotOperations.GetOperationStatusAsync, the server response is not deserialized into an OperationStatus object correctly. Opening the OperationStatus object in Quick View shows:

```
-		operationStatus	{Microsoft.Azure.CognitiveServices.Vision.Face.Models.OperationStatus}	Microsoft.Azure.CognitiveServices.Vision.Face.Models.OperationStatus
+		CreatedTime	{1/1/0001 12:00:00 AM}	System.DateTime
		LastActionTime	null	System.DateTime?
		Message	null	string
		ResourceLocation	null	string
		Status	Succeeded	Microsoft.Azure.CognitiveServices.Vision.Face.Models.OperationStatusType
```

Note the ResourceLocation property value is null, which means I can't get the ID of the snapshot I just took.

**Expected behavior**

The OperationStatus.ResourceLocation property should have a non-null value, for example:

```
-		operationStatus	{Microsoft.Azure.CognitiveServices.Vision.Face.Models.OperationStatus}	Microsoft.Azure.CognitiveServices.Vision.Face.Models.OperationStatus
+		CreatedTime	{1/1/0001 12:00:00 AM}	System.DateTime
		LastActionTime	null	System.DateTime?
		Message	null	string
		ResourceLocation	"/snapshots/4dea7d1e-4519-4b03-9a23-b7114a5ca060"	string
		Status	Succeeded	Microsoft.Azure.CognitiveServices.Vision.Face.Models.OperationStatusType

```

**Actual behavior (include Exception or Stack Trace)**
There is no exception.

This bug happens because the JsonProperty names for the OperationStatus properties do not match the names of the corresponding fields in the serialized JSON object in the body of the HTTP server response.

For example, the OperationStatus.ResourceLocation has a JsonProperty name of "ResourceLocation". See:
https://github.com/Azure/azure-sdk-for-net/blob/ad80cd5c1732de3700fffd501dfedfc911ea69b1/sdk/cognitiveservices/Vision.Face/src/Generated/Models/OperationStatus.cs#L117

However, in the response returned by the server, the corresponding field is "location", not "resourceLocation":
```
{
  "status": "succeeded",
  "createdDateTime": "2020-09-11T19:41:07.2046017+00:00",
  "location": "/snapshots/e7bde61d-63ef-4c40-9e4f-08ec38bd576e"
}
```

You can verify this by using API testing consoles, e.g.:
https://westcentralus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/snapshot-take/console
https://westcentralus.dev.cognitive.microsoft.com/docs/services/563879b61984550e40cbbe8d/operations/operationstatus-get/console
An example operation ID is 5f0ddbe6-82fd-4ae9-a04c-6805c433cf28, though I don't know if that will work for you.

The OperationStatus.ResourceLocation property should have a property name of "location":
```
[JsonProperty(PropertyName = "location")]
public string ResourceLocation { get; set; }
```

I verified this as follows.
1. Clone the Azure SDK for .NET.
1. Edit OperationStatus.cs as described just previously.
1. Recompile Microsoft.Azure.CognitiveServices.Vision.Face.dll.
1. Insert the recompiled Microsoft.Azure.CognitiveServices.Vision.Face.dll into my project in place of the version provided by NuGet.
1. Run my project. The relevant code snippet follows.
1. The OperationStatus.ResourceLocation property has a non-null value.

```
string ENDPOINT = "YOUR FACE ENDPOINT HERE";
string SUBSCRIPTION_KEY = "YOUR FACE SUBSCRIPTION KEY HERE";
string personGroupId = "A VALID PERSON GROUP ID HERE";

IFaceClient client = Authenticate(ENDPOINT, SUBSCRIPTION_KEY);
var takeSnapshotResult = await clientSource.Snapshot.TakeAsync(SnapshotObjectType.PersonGroup, personGroupId, new Guid?[] { SUBSCRIPTION_KEY });
var operationId = Guid.Parse(takeSnapshotResult.OperationLocation.Split('/')[2]);
OperationStatus operationStatus = null;
do
{
	Thread.Sleep(TimeSpan.FromMilliseconds(1000));
	operationStatus = await clientSource.Snapshot.GetOperationStatusAsync(operationId);
}
while (operationStatus.Status != OperationStatusType.Succeeded && operationStatus.Status != OperationStatusType.Failed);
var snapshotId = Guid.Parse(operationStatus.ResourceLocation.Split('/')[2]);
```

NOTES:

- Other OperationStatus properties have mismatched JsonProperty names as well.
For instance, the CreatedTime property has JsonProperty name "createdTime", but the corresponding field in the HTTP server response is "createdDateTime". As a result, the OperationStatus.CreatedTime property ends up with a value of `{1/1/0001 12:00:00 AM}`.

- According to Github, OperationStatus.cs has not changed since at least May 2019:
https://github.com/Azure/azure-sdk-for-net/commits/master/sdk/cognitiveservices/Vision.Face/src/Generated/Models/OperationStatus.cs
Therefore, this issue presumably results from changes made to the Face service rather than to the SDK.

**To Reproduce**
See previous item.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
Microsoft.Azure.CognitiveServices.Vision.Face v2.6.0-preview.1

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
Windows 10 Enterprise 1909

Output of `dotnet --info`:
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.402\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.1.700 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

 - IDE and version : [e.g. Visual Studio 16.3]
Microsoft Visual Studio Community 2019
Version 16.7.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by v-jaswel** [comment]
Per sbowles, this is going to be fixed on the server side and not the SDK side. Therefore I am closing.
