### ISSUE TITLE
[BUG]  Microsoft.Azure.KeyVault.Core dependencies on install differs greatly between 3.0.3 and 3.0.5 

### ISSUE THREAD

**Issue by StingyJack** [Azure/azure-sdk-for-net#15124]
**Describe the bug**
If I install v 3.0.3 of this package, the only dependency i get a license agreement for is the one I'm installing. 
![image](https://user-images.githubusercontent.com/15381181/93000104-0c132400-f4f4-11ea-8270-dc4a11511a0c.png)

However if I take the v 3.0.5 package, that license agreement is incredibly large (> 30+ item)
![image](https://user-images.githubusercontent.com/15381181/93000225-e9cdd600-f4f4-11ea-847e-b33d2d23ab0c.png)

**Expected behavior**
I expect  that a patch version of any package stay fairly true to the dependency footprint of the base package for that major.minor.

I realize that this package has been superseded by something else, but the expectation is the same for any package you make. That large of a dependency change would be considered a breaking change from a deployment footprint perspective. All of those other dependencies introduce even more complexity and could introduce other side effects.

I'm taking the 3.0.3 version. Please try to constrain changes with patch version increments.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by heaths** [comment]
Thank you for your feedback. Given this package has already shipped and has since been superseded, there is nothing more to do since changing the target version in a subsequent orange would also be breaking. Should we need to make a critical fix to the package on the future, we will be careful to avoiding taking new dependencies, unless fixing said critical vulnerability requires doing so, as can often be the case with many dependencies (note: the newer packages have fewer dependencies).

**Comment by StingyJack** [comment]
@heaths - another perspective on this to consider when versioning would be to avoid upgrading a major version of a dependency. If someone happens to use a dependency your package uses in their project in addition to your package, you can leave them stuck by fixing a bug they need fixed in a patch version of your package and requiring a higher major (breaking) version of that shared dependency that breaks their project. 

The right course of action is one that doesn't leave others stuck. What do you think you would have done differently in this case?
