### ISSUE TITLE
[BUG] Can't send complex object as data in EventGridEvent

### ISSUE THREAD

**Issue by Sarah-Aly** [Azure/azure-sdk-for-net#15137]
**Describe the bug**
Trying the new Event Grid SDK, sending data as a string in the event, serialized successfully, But trying to send a complex object as the data in the event, I get empty data in the consumer

**Expected behavior**
Be able to send complex objects as data in EventGridEvent

**Actual behavior (include Exception or Stack Trace)**
complex object data is not serialized correctly & we get empty data in the consumer (event grid trigger azure function)
![image](https://user-images.githubusercontent.com/26885551/93126545-537aeb00-f681-11ea-8e37-891f07b7a767.png)

**To Reproduce**
```csharp
    class data
    {
        string name;
        string value;
        public data(string name, string value)
        {
            this.name = name;
            this.value = value;
        }
    }

    class Program
    {
        static Uri endpoint = new Uri("<EG-TOPIC-ENDPOINT>");
        static AzureKeyCredential azureKey = new AzureKeyCredential("<AEG-SAS-KEY>");
        static void Main(string[] args)
        {
            EventGridPublisherClient eventGridPublisherClient = new EventGridPublisherClient(endpoint, azureKey);
            var events = new List<EventGridEvent>();
            // this sends empty data
            events.Add(new EventGridEvent(new data("test3", "event grid schema"), "subject 3", "eventType 3", "1.0"));
            // this sends correct data
            events.Add(new EventGridEvent("ping pong", "subject 4", "eventType 4", "1.0"));
            eventGridPublisherClient.SendEvents(events);
        }
    }
```

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventGrid -Version 4.0.0-beta.1

**Comment by jsquire** [comment]
Hi @Sarah-Aly.   Thank you for your feedback;  tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
@Sarah-Aly, it looks like the issue is that your type is using fields rather than properties.
Also the properties would need to be public for serialization to work with the default serializer - System.Text.Json.
See https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to#serialization-behavior for current behavior.


It looks like in .NET 5.0, field support is being added https://github.com/dotnet/runtime/issues/41313

**Comment by JoshLove-msft** [comment]
We should update the documentation to make it clear what the default constraints w.r.t. serialization are.

**Comment by Sarah-Aly** [comment]
This works. Thanks @JoshLove-msft.
Closing the issue.
