### ISSUE TITLE
[BUG] Azure Search Monitoring Logs Displaying Encoded Entries

### ISSUE THREAD

**Issue by ParableGrant** [Azure/azure-sdk-for-net#15146]
When viewing azure search queries in Azure Cognitive Search Monitoring Operation Logs, our search service is displaying certain operation Query.Search data in Query_s encoded and unreadable. Specifically the &search, &scoringProfile and &facets.

We expect the output of the logs to be readable where we could observe entered entries and facets.

An example of actual output is this:
Query_s: '?api-version=2020-06-30&searchMode=Any&search=\<NieQminDE4Gg\>'

where it should read:
Query_s: '?api-version=2020-06-30&searchMode=Any&search=12345'

We are using Azure.Search.Documents 11.1.1 but have seen the same behavior on Azure.Search.Documents 11.0.0. 
We are running searchIndexClient.SearchAsync('12345') and observe this behavior but also experience it on more complex queries. 
Terms entered using the api or search explorer do not seem to be displayed encoded, only using the sdk.

Using Azure.Search.Documents 11.+, ASP.NET CORE 3, Visual Studio 16.7.2 and Azure Cognitive Search Monitoring Operation Logs

**Comment by ParableGrant** [comment]
encoded query term seems to have been removed on post
FIX:
An example of actual output is this:

> Query_s:  '?api-version=2020-06-30&searchMode=Any&search=<NieQminDE4Gg>'

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AlexGhiondea** [comment]
@ParableGrant apologies for the late reply. Is this still something you are experiencing?

**Comment by dporterf** [comment]
The issue has been resolved.  @ParableGrant is a prior employee.  Thank you for the follow up.  You may close this.

**Comment by dporterf** [comment]
No longer an issue.  Please close.
