### ISSUE TITLE
Expose the select query option for GetEntity method to allow more efficient existence checks 

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#15144]
`GetEntity` / `GetEntityAsync` currently does not expose the `select` query options, which allows a more efficient check for an entity's existence.

**Comment by kieronlanning** [comment]
Thanks for creating this @christothes. We have an event store built on top of table storage where we check for an aggregate's existence (latest stream version) using the previous `Retrieve` operation asking only for the `PartitionKey` column. It's a quick means of knowing if an entity exists or not.

We also use this facility ad-hoc in other areas too, but this is a key part of the event store API we have.

**Comment by christothes** [comment]
Thanks for sharing the scenario, @kieronlanning. Just so I can understand the full context, what possible follow up actions result from a successful or unsuccessful existence check? For example, would you ever use it like a `CreateEntityIfNotExists`? Would you ever need to fetch the full entity after confirming it exists? Would an entity ever need to be deleted if it exists?

**Comment by kieronlanning** [comment]
@christothes All of the above.

I guess these would sum the scenarios up:
> Exists check. Just want to know if it's there, no further action.
> Create if not exists.
> Delete if exists.

**Comment by kieronlanning** [comment]
@christothes Damn. That was quick! Thanks...! Any idea when the next release will be?

**Comment by christothes** [comment]
>  Any idea when the next release will be?

We release on a monthly cadence, so 3.0.0-beta.2 should be published around the first week of October. As a side note, you can download the [nightly dev feed package ](https://dev.azure.com/azure-sdk/public/_packaging?_a=package&feed=azure-sdk-for-net&package=Azure.Data.Tables&protocolType=NuGet)if you ever want to try something out prior to release. This change will publish tonight.
