### ISSUE TITLE
Cannot specify an infinite time to live on QueueClient.SendMessageAsync [BUG]

### ISSUE THREAD

**Issue by srulandhs** [Azure/azure-sdk-for-net#15158]
**Describe the bug**
When using QueueClient.SendMessageAsync, there is a parm `TimeSpan? timeToLive`. The documentation for the REST API  (PutMessage) indicated that a -1 should be sent for an infinite ttl. I do not see a way to do this use the `timeToLive` parameter.

Sending in null, according to the documentation, defaults to 7 days/whatever the account has configured as a default.
Sending in TimeSpan.MaxValue (which worked in the 9.x versions, but not the 12.x version) generates an error: `InvalidQueryParameterValue`

**Expected behavior**
TimeSpan.MaxValue seems like the appropriate value to send. It would be backwards compatible.

Also, the code needs to account for any possible TimeSpan that exceeds the size of `(int)TimeSpan.TotalSeconds` since this is the true max ttl value the interface can support.

The online documentation also needs to be updated to indicate these behaviors.

**Actual behavior (include Exception or Stack Trace)**
Azure.RequestFailedException: Value for one of the query parameters specified in the request URI is invalid. RequestId:1be4f2bb-3003-0138-2a60-8be3e8000000 Time:2020-09-15T13:03:55.5491349Z Status: 400 (Value for one of the query parameters specified in the request URI is invalid.) ErrorCode: InvalidQueryParameterValue Additional Information: QueryParameterName: messagettl QueryParameterValue: -2147483648 Reason: Value must be greater than or equal to 1, or -1 to indicate an infinite TTL. Headers: Server: Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0 x-ms-request-id: 1be4f2bb-3003-0138-2a60-8be3e8000000 x-ms-version: 2018-11-09 x-ms-error-code: InvalidQueryParameterValue Date: Tue, 15 Sep 2020 13:03:55 GMT Content-Length: 471 Content-Type: application/xml
System.AggregateException: One or more errors occurred. (Value for one of the query parameters specified in the request URI is invalid.
RequestId:1be4f2bb-3003-0138-2a60-8be3e8000000
Time:2020-09-15T13:03:55.5491349Z
Status: 400 (Value for one of the query parameters specified in the request URI is invalid.)
ErrorCode: InvalidQueryParameterValue
Additional Information:
QueryParameterName: messagettl
QueryParameterValue: -2147483648
Reason: Value must be greater than or equal to 1, or -1 to indicate an infinite TTL.
Headers:
Server: Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 1be4f2bb-3003-0138-2a60-8be3e8000000
x-ms-version: 2018-11-09
x-ms-error-code: InvalidQueryParameterValue
Date: Tue, 15 Sep 2020 13:03:55 GMT
Content-Length: 471
Content-Type: application/xml
) ---> Azure.RequestFailedException: Value for one of the query parameters specified in the request URI is invalid.
RequestId:1be4f2bb-3003-0138-2a60-8be3e8000000
Time:2020-09-15T13:03:55.5491349Z
Status: 400 (Value for one of the query parameters specified in the request URI is invalid.)
ErrorCode: InvalidQueryParameterValue
Additional Information:
QueryParameterName: messagettl
QueryParameterValue: -2147483648
Reason: Value must be greater than or equal to 1, or -1 to indicate an infinite TTL.
Headers:
Server: Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 1be4f2bb-3003-0138-2a60-8be3e8000000
x-ms-version: 2018-11-09
x-ms-error-code: InvalidQueryParameterValue
Date: Tue, 15 Sep 2020 13:03:55 GMT
Content-Length: 471
Content-Type: application/xml
at Azure.Storage.Queues.QueueRestClient.Messages.EnqueueAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
at Azure.Storage.Queues.QueueRestClient.Messages.EnqueueAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, QueueSendMessage message, String version, Nullable`1 visibilitytimeout, Nullable`1 messageTimeToLive, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
at Azure.Storage.Queues.QueueClient.SendMessageInternal(String messageText, Nullable`1 visibilityTimeout, Nullable`1 timeToLive, Boolean async, CancellationToken cancellationToken)
at Azure.Storage.Queues.QueueClient.SendMessageAsync(String messageText, Nullable`1 visibilityTimeout, Nullable`1 timeToLive, CancellationToken cancellationToken)

**To Reproduce**
Call `QueueClient.SendMessageAsync` using a timeToLive = TimeSpan.MaxValue

**Environment:**
 - Azure.Storage.Queues 12.4.1
- Dotnet --version: core 3.1.102

**Comment by amnguye** [comment]
To specify -1 as the infinite time to live, you can use this test.

```
[Test]
        public async Task SendMessageAsync_InfiniteTimeToLive()
        {
            // Arrange
            await using DisposingQueue test = await GetTestQueueAsync();

            // Act
            Response<SendReceipt> response = await test.Queue.SendMessageAsync(
                messageText: GetNewString(),
                timeToLive: new TimeSpan(0,0,-1));

            // Assert
            Assert.NotNull(response.Value);
        }
````

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
