### ISSUE TITLE
Language detector throw when CountryHint is "en"

### ISSUE THREAD

**Issue by dunalduck0** [Azure/azure-sdk-for-net#15163]
I am using Azure.AI.TextAnalytics v5.0.0

When I set CountryHint to be "en", I am getting the error below; if I change to other values like "es" or "fr", my code works fine. I guess it's probably because the default Country code is "en" and thus the code doesn't allow me to use "en" as CountryHint anymore. But it's very odd to see an exception. I don't think it's necessary to throw at all in such cases.

**Unhandled Exception: Azure.RequestFailedException: Country hint is not valid. Please specify an ISO 3166-1 alpha-2 two letter country code.**
Status: 200 (OK)
ErrorCode: InvalidCountryHint

Content:

Headers:
Transfer-Encoding: chunked
x-envoy-upstream-service-time: REDACTED
apim-request-id: REDACTED
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
x-content-type-options: REDACTED
Content-Type: application/json; charset=utf-8
Date: Tue, 15 Sep 2020 17:07:05 GMT

   at Azure.AI.TextAnalytics.TextAnalyticsClient.DetectLanguage(String document, String countryHint, CancellationToken cancellationToken)

**Comment by maririos** [comment]
Thanks @dunalduck0 .

`CountryHint` is a 2-letter country/region code following ISO 3166-1 alpha-2. So `en` is not recognized as a country, and `es` stands for `Spain` and `fr` for `France`.

The [default value](https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.TextAnalytics_5.0.0/sdk/textanalytics/Azure.AI.TextAnalytics/src/TextAnalyticsClientOptions.cs#L43) for `CountryHint` is `us`.

Let me know if this helps!

**Comment by maririos** [comment]
Hi @dunalduck0 .
Curious if you get the information you needed or you still have more questions

**Comment by dunalduck0** [comment]
> Hi @dunalduck0 .
> Curious if you get the information you needed or you still have more questions

Thank you Maririos for follow-up. Yes, your previous answer cleared my question. Sorry that I overlooked the difference between country code and language code.

**Comment by maririos** [comment]
No worries. Happy to help.

**Comment by IntegerMan** [comment]
If anyone else bumps into this issue and thinks it should be reopened, you are likely on the wrong NuGet package as I was.

I encountered this on v4.0.0 of Microsoft.Azure.CognitiveServices.Language.TextAnalytics. I should have been using the latest Azure.AI.TextAnalytics package instead (note: the API does change somewhat).

However, using 4.0.0 you can work around the issue by setting `countryHint: "US"` or `countryHint: null`.
