### ISSUE TITLE
Migrate Blobs and Queues Function extension to Track 2

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#15171]
This tracks the work to migrate the code to the main repo as well as move to the Track 2 code
- [x] Blobs
  - [x] Code ported to Track 2
  - [x] Code merged into central repo
- [x] Queues
  - [x] Code ported to Track 2
  - [x] Code merged into central repo
- [x] Split the code into two separate packages

**Comment by kasobol-msft** [comment]
Preview with this is out.
