### ISSUE TITLE
Migrate Event Hubs Function extension to Track 2

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#15173]
This tracks the work to migrate the code to the main repo as well as move to the Track 2 code
 - [x] Code ported to Track 2
 - [x] Code merged into central repo

**Comment by drdamour** [comment]
be nice to make room for managed identity in this migration, or at least not disclude it.  cf https://feedback.azure.com/forums/355860-azure-functions/suggestions/37907848-support-for-azure-managed-service-identities-in-ev
