### ISSUE TITLE
ConfigurationSets are null when I retrive the Azure VM password via Management Library API

### ISSUE THREAD

**Issue by JamborGit** [Azure/azure-sdk-for-net#1517]
I try to use Azure Management Library API to read Virtual Machine information, the following is my code.
  var vmClient = CloudContext.Clients.CreateComputeManagementClient(cer);
  var mymachine=    vmClient.VirtualMachines.Get("javmtest", "javmtest", "javmtest");
We can find AdminPassword in ConfigurationSets: https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.management.compute.models.configurationset_members(v=azure.11).aspx, However the AdminPassword and AdminUserName in ConfigurationSets are always null, I couldn't get this infoformation, Can we get the Azure VM AdminPassword via Management Library API?

**Comment by singhkay** [comment]
Admin password is not returned from the platform
