### ISSUE TITLE
CloudConfigurationManager - refresh appSettings on demand

### ISSUE THREAD

**Issue by MarkDaviesAP** [Azure/azure-sdk-for-net#1519]
//ignore this - I misunderstood how this is working (returning a cached object).  I'll investigate why my settings are not reloading through GetValue first.

Is it possible to have an optional setting on the GetSetting methond to force a refresh of config settings?  (Is this needed?)

My scenario:  
I have a couple of settings that I need to update at runtime.

The settings are in "appSettings" of Web.config in a hosted webapp.  CloudConfigurationManager nicely loads those when they are not in the azure configuration settings.  

Unfortunately the following code below in the CloudConfigurationManager causes settings to be loaded only once.  It would be nice to be able to tell to re-load.

We are not using WebApps configuration from the console (would this even matter?).

I know other parts of the app could be out of date as a result of this (and no event to hook).

 ```c#
internal static AzureApplicationSettings AppSettings
   { 
             get 
             { 
                 if (_appSettings == null)   //causes read-once.
                 { 
                     lock (_lock) 
                     { 
                         if (_appSettings == null) 
                         { 
                             _appSettings = new AzureApplicationSettings(); 
                         } 
                     } 
                 } 
 
 
                 return _appSettings; 
             } 
    } 
```
Thanks, Mark.

**Comment by hovsepm** [comment]
Closed according to @MarkDaviesAP comment "Ignore this"....
