### ISSUE TITLE
[QUERY] Recommeded way to use KeyVaultClient dispose method

### ISSUE THREAD

**Issue by rashigoyal** [Azure/azure-sdk-for-net#15204]
**Query/Question**
We have been using KeyVaultClient for fetching secrets and certificates from keyvault. The query is for the dispose method and the right way to use it, do you expect the consumers to call dispose, since you implement IDisposable.
Also, is singleton a recommended pattern or an instance per request recommended.

**Environment:**
 - .Net 3.0.0 version of Microsoft.Azure.KeyVault 
 - Azure Service Fabric Application
 - Visual Studio

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by heaths** [comment]
.NET guidelines recommend always calling `Dispose` for `IDisposable` objects. You can use the `using` keyword to make this easy. If the object is alive for the entire lifetime of your app, calling `Dispose` should not be necessary, however.

Please note, though, we will be deprecating `KeyVaultClient` and the `Microsoft.Azure.KeyVault` package. We recommend that yo upgrade to `Azure.Security.KeyVault.Secrets`, `Azure.Security.KeyVault.Keys`, and/or `Azure.Security.KeyVault.Certificates`. Not only are these easier to use and extend, but allocate less memory, have sync and async methods (async is generally recommended), consistent authentication across all Azure.* packages, and more. Check out https://aka.ms/azsdk/intro and https://aka.ms/azsdk/valueprop for more information.

Does that answer your question sufficiently?

**Comment by rashigoyal** [comment]
Thank you for your response, I was interested in knowing the httpclient handling internally if you can share, do you close the connections only on dispose or are there other triggers as well.
Asking because we see socket port exhaustion exceptions, and were wondering if not calling dispose on the KeyVaultClient could be a cause for it.

Another query is today we have a new KeyVaultClient created for each request we send to keyvault.
Sample code:
					KeyVaultClient kv = new KeyVaultClient(authenticationCallback);
					var secret = await kv.GetSecretAsync(kVBaseURI, secretName).ConfigureAwait(false);
Would you recommend to move it to singleton instance for optimization of connections or KeyVaultClient handling is irrespective of the pattern we choose??

**Comment by heaths** [comment]
If we create the `HttpClient` ourselves, yes, it's disposed; however, this doesn't necessarily reduce the connection pooling issues as sharing an `HttpClient` does, which our newer libraries do by default. You can pass your own `HttpClient` into `KeyVaultClient` instances and manage the lifetime yourself, in which case we do not dispose it. Sharing an `HttpClient` yourself is really the only effective way to mitigate the connection pooling issue. Again, that is the default behavior in `Azure.Security.KeyVault.*` packages.

With either the older or newer clients, a singleton is usually sufficient. We don't store a lot of state, but the pipeline we create can be computationally expensive if creating new clients in quick succession.

**Comment by rashigoyal** [comment]
1) Do you dispose httpclient only if we explicitly call dispose or do you do it otherwise also?
2) If we don't use singleton pattern, do you still internally reuse the httpclients by factory mechanisms or is it recreated for each request?

**Comment by heaths** [comment]
1. We only dispose `HttpClient` instances we create when you call `Dispose` on the clients. If you pass one in, we do not dispose it.
2. A new `HttpClient` is created by default for each instance of a client you create.
3. There should be no leaks with fully managed memory. Even if you don't dispose, objects will be finalized eventually.

The point I was making about is that we do share a single `HttpClient` in Azure.* packages, and Microsoft.Azure.KeyVault* packages will be deprecated soon. The new ones are faster, allocate less, are more extensible, easier to diagnose (better logging), and more.

**Comment by rashigoyal** [comment]
Thanks for your response. Few queries on the new SDK migration:
1) Do you have any sample code which we can refer to since the recommendation is to maintain our own pool?
2) What is the benefit of clients maintaining their own pool? Is it to share the same pool across multiple azure components that we may connect to?
3) Is their any pain points seen from other customer experiences?

**Comment by heaths** [comment]
The new SDKs already share a connection pool. The only reason you might want to maintain your own is if you want to share that same `HttpClient` with other RESTful clients (not just Azure SDK).

For Key Vault, we have migration guides I just published - which also cover this topic:

* https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Secrets/MigrationGuide.md
* https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Keys/MigrationGuide.md
* https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Certificates/MigrationGuide.md
