### ISSUE TITLE
[ASP.NET Extensions] What is the Data Lake Storage equivalent of AddBlobServiceClient?

### ISSUE THREAD

**Issue by sonic1981** [Azure/azure-sdk-for-net#15202]
**Query/Question**
I currently inject various clients into my Azure function using:

```c#
private static void addAzureClients(IFunctionsHostBuilder builder)
    {
        builder.Services.AddAzureClients(builder =>
        {

            builder.AddSecretClient(new Uri(Environment.GetEnvironmentVariable("KeyVaultUrl")));

            builder.AddBlobServiceClient(Environment.GetEnvironmentVariable("ProcessStorageConnectionString"))
                .WithName("ProcessBlobStorage");

            builder.AddQueueServiceClient(Environment.GetEnvironmentVariable("ProcessStorageConnectionString"))
                .WithName("ProcessQueueStorage");

            builder.UseCredential(new DefaultAzureCredential());
        });
    }
```

I now need to access a Data Lake Storage (gen 2) instance. But there doesn't seem to be any equivalent method (like `AddBlobServiceClient`) to inject the relevant client?

**Environment:**
 - Azure.Storage.Files.DataLake 12.4.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
I took a look and don't think there are any. Marking as a bug.

**Comment by seanmcc-msft** [comment]
@pakrym, where in the codebase does `AddBlobServiceClient` live?

**Comment by pakrym** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/0acf2f02c648407da123a3a3b9a352041f7ddd4d/sdk/storage/Azure.Storage.Blobs/src/BlobClientBuilderExtensions.cs

**Comment by seanmcc-msft** [comment]
Created a PR to address this.  Note that the `DataLake*Clients` don't have constructors that take connection string.
