### ISSUE TITLE
[FEATURE REQ] Make ArrayPool<byte> instance used by PartitionedUploader publicly configurable

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-net#15214]
**Library or service name.**
Azure.Storage.*
 
**Is your feature request related to a problem? Please describe.**
While `PartitionedUploader`'s constructor accepts an `ArrayPool<byte>` instance, public APIs do not allow customers to provide their own instance, forcing the default of `ArrayPool<byte>.Shared`. This forces the user to rely on the `Shared` pool's array lifetime management implemented by their .NET platform, which isn't always tailored to a user's needs and can cause poor performance. Users should have a means to provide an `ArrayPool<byte>` to have greater control over array lifetimes in the pool.

**Comment by kasobol-msft** [comment]
This ask has been analyzed by our team. The usage patterns indicate that customers who provide custom pool (into previous versions of the SDK) effectively achieved throttling/rate limiting by creating contention point inside SDK logic. We suggest users to wrap external throttling policy/rate limiter around calls to Storage SDK to achieve the same, then fine tune that throttling.
