### ISSUE TITLE
[FEATURE REQ] Publish KeyVault tag changes to Event Grid

### ISSUE THREAD

**Issue by dajoo75** [Azure/azure-sdk-for-net#15225]
**Library or service name.**
Azure Key Vault
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

We would like an event when tags are changed for secrets in key vault e.g. Microsoft.KeyVault.SecretTagModified. 

We're currently using Azure Key Vault as an Event Grid source to listen for changes in secrets and wanted to use tags also when we noticed that changes in tags does not generate an event. We will try and work around this but it would have been very useful if an event had already existed.

https://docs.microsoft.com/en-us/azure/event-grid/event-schema-key-vault

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by sebansal** [comment]
We have recorded the request and will consider during our next planning phase. 
For feature requests, feedback etc, you can submit and vote here https://feedback.azure.com/forums/906355-azure-key-vault

Internally trackable workitem 8650723
