### ISSUE TITLE
Core test pipeline failing without a visible error

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#15231]
This happens pretty consistently in nighly runs:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=541642&view=logs&j=1e00682f-6081-5348-8da2-7d601664b2e3&t=4f3e1a81-cacf-5ad2-6e75-5049507bfdad

**Comment by heaths** [comment]
This appears to be caused by https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#1-vstest-stops-process-execution-earlydotnet-test. I will address in #14427.
