### ISSUE TITLE
Why does the DataLakeServiceClient not support connection strings when all other clients do?

### ISSUE THREAD

**Issue by sonic1981** [Azure/azure-sdk-for-net#15259]
**Describe the bug**
The overloads for the [`DataLakeServiceClient`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeserviceclient?view=azure-dotnet) does not have an overload that accepts a connection string.

All the other clients (.e.g. [`BlobContainerClient`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.-ctor?view=azure-dotnet#Azure_Storage_Blobs_BlobContainerClient__ctor_System_String_System_String_)) do have a connection string overload.

**Expected behavior**
Expose an overload for the `DataLakeServiceClient` constructor that accepts a connection string.

**Actual behavior (include Exception or Stack Trace)**
You currently only have the option of using a URI. This requires the setting up of additional IAM permissions and is inconsistent with the other providers.

**Environment:**
 - Azure.Storage.Files.DataLake, Version=12.4.0.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by sonic1981** [comment]
This is tagged incorrectly @jsquire I'm referring to Data Lake Storage Gen **2** not Gen **1** :)

**Comment by jsquire** [comment]
Thanks, @sonic1981.   My mistake during selection; the good news is that it routes to the same team.   :smile:

**Comment by Marusyk** [comment]
any updates?

**Comment by lawrencegripper** [comment]
Would it be possible to make the [StorageConnectionString](
https://github.com/Azure/azure-sdk-for-net/blob/93c1e88373b3d886f7da683765f57d81a8b1f805/sdk/storage/Azure.Storage.Common/src/Shared/StorageConnectionString.cs#L366) public, this way users could pull in `Azure.Storage.Common` and call 

```
public static StorageConnectionString Parse(string connectionString)
```

Then pass the required results to the DataLakeClient?

**Comment by sonic1981** [comment]
This still hasn't been looked at by anyone

**Comment by JimSuplizio** [comment]
Hi @sonic1981, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
