### ISSUE TITLE
Consider using the built in nuget feature for managing centralized versioning

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#15252]
See https://github.com/NuGet/Home/wiki/Centrally-managing-NuGet-package-versions.

We should investigate switching to this model over the MSBuild extension we currently have checked in for managing centralized package versioning https://github.com/Azure/azure-sdk-for-net/tree/master/eng/Microsoft.Build.CentralPackageVersions.

**Comment by kurtzeborn** [comment]
This something, language-specific, that the libraries team should look at and prioritize.  If there's any help needed from the Central EngSys team, please reach out to @chidozieononiwu and/or @weshaggard.
