### ISSUE TITLE
DefaultAzureCredential should be able to access IConfiguration

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-sdk-for-net#15260]
**Library or service name.**
What library or service is this request related to? Azure.Identity 
 
**Is your feature request related to a problem? Please describe.**

What feature would you like to get added? 

`DefaultAzureCredential()` can get credentials from `IConfiguration`

What problem is it solving?

I easily spent several hours trying to figure out why authentication wasn't working. Even though the documentation clearly said it uses "environment variables", I somehow assumed that I could just add the values in `appsettings.json` or `secrets.json` and it would just work. But, of course, it didn't.

It would be great if `DefaultAzureCredential()` could read from `IConfiguration` as this is a well established construct that devs are used to.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Please take a look at https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/extensions/Microsoft.Extensions.Azure/README.md 

Microsoft.Extensions.Azure is an Extensions integration package that supports things like registering clients with DI or loading credentials from IConfiguration.

You can use a global `builder.ConfigureDefaults` call to configure TokenCredentials for all the clients or a `WithCredential` call to change it for a particular registration.

**Comment by schaabs** [comment]
@MisinformedDNA does the library @pakrym mentioned meet your needs? Any deeper integration with with `IConfiguration` would need to be added to this library rather than Azure.Identity, since Azure.Identity cannot take a dependency on Microsoft.Extensions.Configuration. I'm closing this issue, but if you find it doesn't meet your needs, please file a feature request to add support for your scenario in Microsoft.Extentions.Azure.

**Comment by CodeFontana** [comment]
I know this is years later, but I found this GitHub issue looking for the same feature, and can confirm that the provided link resolved the problem--

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/extensions/Microsoft.Extensions.Azure/README.md

Appreciate everyone's help.
