### ISSUE TITLE
Inconsistent user-agent header from Azure.Core

### ISSUE THREAD

**Issue by abhilasharora** [Azure/azure-sdk-for-net#15270]
**Problem**
In our NuGet package `Microsoft.Extensions.Configuration.AzureAppConfiguration`, we use `Azure.Data.AppConfiguration` package from the SDK. We use a per-call `HttpPipelinePolicy` to add a user-agent header with the version details for our NuGet package, and we rely on the telemetry policy in `Azure.Core` to add the version details for the SDK package to the user-agent header. This issue is to report the anomaly we observed in the separator used to combine multiple values for the user-agent header in the SDK.

**Expected Behavior**
The telemetry policy in `Azure.Core` combines the multiple user-agent header values with a space (' ') as the separator.

**Actual Behavior**
We notice both space (' ') and comma (',') being used as a separator. Could this be a difference in `Azure.Core` implementation for `.NET Standard` and `.NET Framework`?

![image](https://user-images.githubusercontent.com/47916289/93656343-7ccbac00-f9de-11ea-9625-b3101add9919.png)

**Comment by pakrym** [comment]
Azure.Core doesn't do header combining, it's done by the underlying HttpClient implementation which might be different based on the OS.

I recommend changing the https://github.com/Azure/AppConfiguration-DotnetProvider/blob/9743885074bba9fe1c1be9802a53afa04947f992/src/Microsoft.Extensions.Configuration.AzureAppConfiguration/UserAgentHeaderPolicy.cs to be a per call policy that would retrieve the current value and prepend the additional information in a consistent manner.

**Comment by abhilasharora** [comment]
@pakrym Thanks for your response. Our user agent header policy is already a per-call policy. Such policies run before the telemetry policy in `Azure.Core`, so the current value of `User-Agent` header is missing when this policy runs. Could the telemetry policy in `Azure.Core` append to the existing `User-Agent` header value, instead of adding another header value?

**Comment by pakrym** [comment]
Sorry, I meant per-retry. That way you would have access to the entire value.

We typically don't advise client authors to prepend anything to User-Agent in the policy and use ApplicationId from diagnostic options instead (https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/DiagnosticsOptions.cs#L93).

**Comment by abhilasharora** [comment]
We previously had a per-retry policy that would prepend the version to the user agent value set by the SDK. However, we moved to per-call policy after we noticed the retry logs had the version information prepended more than once, and we wanted to avoid parsing the string to see if the version information was already present.

We could use the `ApplicationId` in `DiagnosticsOptions`. However, it is limited to 24 characters, and wouldn't fit our version information. I do see that we also have a `DefaultApplicationId`, which seems to be missing this check. Is there a reason for restricting `MaxApplicationIdLength` to 24, and keeping it private?

**Comment by abhilasharora** [comment]
@pakrym Any update here? Also, is there a tracking bug on the HttpClient implementation that is causing the difference in this behavior for different platforms?

**Comment by jimmyca15** [comment]
Ping since I'm hitting this as well. `ApplicationId` appears to be the promoted way to add specialized information to the user agent, yet the 25 max character length restriction is blocking me here. Is there a reason for such a restriction?

**Comment by pakrym** [comment]
The 25 character limit is part of the general guidance: https://azure.github.io/azure-sdk/general_azurecore.html#azurecore-http-telemetry-appid-length
