### ISSUE TITLE
[FEATURE REQ] Add support for custom HttpClient

### ISSUE THREAD

**Issue by efonsecab** [Azure/azure-sdk-for-net#15276]
**Library or service name.**
Azure.AI.TextAnalytics
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
Like in many other .NET Core SDKs including many of Azure SDKs, I would like the ability to use a
specified HttpClient received in the TextAnalyticsClient constructors.
This facilitates intercepting requests in order to add custom code for instrumentation

**Comment by jsquire** [comment]
//cc: @maririos

**Comment by jsquire** [comment]
Hi @efonsecab.  Thank you for your feedback and we regret that you're experiencing difficulties.  Unless I misunderstand, you're looking to use an `HttpClient` instance that your application owns with the `TextAnalyticsClient`, which I'm happy to say is already supported.  To do so, you'll want to set the `Transport` property of the `TextAnalyticsClientOptions` using your `HttpClient`, and example of which can be found [in this sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md).

I'll defer to @pakrym for additional thoughts or further guidance on tuning the pipeline used by the client.

**Comment by efonsecab** [comment]
> Hi @efonsecab. Thank you for your feedback and we regret that you're experiencing difficulties. Unless I misunderstand, you're looking to use an `HttpClient` instance that your application owns with the `TextAnalyticsClient`, which I'm happy to say is already supported. To do so, you'll want to set the `Transport` property of the `TextAnalyticsClientOptions` using your `HttpClient`, and example of which can be found [in this sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md).
> 
> I'll defer to @pakrym for additional thoughts or further guidance on tuning the pipeline used by the client.

Thanks, that's exactly what I needed, was a little bit lost since is not standards as with other SDKs when you pass the http in the class constructor
