### ISSUE TITLE
[QUERY] Retrieving a status of a current deployment, from a Web API

### ISSUE THREAD

**Issue by Mimetis** [Azure/azure-sdk-for-net#15275]
**Query/Question**

Using `StartCreateOrUpdateAsync` allows us to launch a resource creation:

``` cs
var rawResult = await resourceClient.Resources.StartCreateOrUpdateAsync( rgName, ...[PARAMETERS]);
```

From that `rawResult` we can have a progression of the current resource deployment:

``` cs
var update = await rawResult.UpdateStatusAsync().ConfigureAwait(false);
Debug.WriteLine("Update from rawResult");
Debug.WriteLine(update.Status);
Debug.WriteLine(update.ReasonPhrase);
Debug.WriteLine(update.ContentStream == null ? "" : new StreamReader(update.ContentStream).ReadToEnd());
```
And it's working perfectly fine, unless we lose the `ResourcesCreateOrUpdateOperation` instance.

For instance in a web application, if we want to *trace* a deployment execution, we should rely on a web api,  and AJAX calls, or kind of, to provide a feedback to users.

I need to retrieve an in progress deployment, and get the status of this deployment.
I've tried with `GetAsync`

``` cs
var res = await resourceClient.Resources.GetAsync(rgName, "Microsoft.Databricks", "", 
                                   "workspaces", databricksName, "2018-04-01").ConfigureAwait(false);

```

But unfortunately, I don't get the current status of the deployment

How can we get an in progress deployment, using simple parameters (like resource name, resource id and so on) and not relying on an existing `ResourcesCreateOrUpdateOperation` that we may have lost at some point ?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nisha-bhatia** [comment]
Thank you for your question. Re-routing to team member.

**Comment by allenjzhang** [comment]
Looking at the [swagger for the response of this operation](https://github.com/Azure/azure-rest-api-specs/blob/aa19725fe79aea2a9dc580f3c66f77f89cc34563/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L3163), it does not contain any information that is identifiable for follow up query. 

Assigning to ARM team to see if there are any `provisionstate` that can be retrieved for a given resource.
