### ISSUE TITLE
[BUG] F# Option and ValueOption types are treated as complex types

### ISSUE THREAD

**Issue by xperiandri** [Azure/azure-sdk-for-net#15274]
**Describe the bug**
`FieldBuilder` treats F# `Option` and `ValueOption` types as complex types

**Expected behavior**
`FieldBuilder` gets underlying generic type

**Actual behavior (include Exception or Stack Trace)**
`FieldBuilder` gets `Option` or `ValueOption` type

**To Reproduce**
1. Create model with F# `Option` and `ValueOption` fields
2. Add `FSharp.Text.Json` to serializer settings
3. Use `FieldBuilder` on the model

**Environment:**
 - `<PackageReference Include="Azure.Search.Documents" Version="11.1.1" />`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by tg-msft** [comment]
This is interesting to consider alongside changes to support Microsoft.Spatial.

**Comment by heaths** [comment]
Adding @brjohnstmsft. Did this occur in Microsoft.Azure.Search 10.0 as well, or is this a change in behavior from the older package?

**Comment by xperiandri** [comment]
I have never used version 10.
But it is used in https://github.com/ssiltanen/Fasaani
@ssiltanen could you join the discussion?

**Comment by xperiandri** [comment]
For now, my workaround is:
``` F#
let private optonTypeFields = Set.ofSeq <| seq {
    "tag"
    "isValueNone"
    "isValueSome"
    "item"
    "value"
    "isNone"
    "isSome"
}

let rec replaceOption (fields : IList<SearchField>) =
    let unwrapOption (field : SearchField) =
        let fields = field.Fields |> Seq.map (fun f -> f.Name) |> Set.ofSeq
        if (Set.intersect optonTypeFields fields).Count = optonTypeFields.Count
        then
            let wrappedField = field.Fields |> Seq.find (fun f -> f.Name = "value")
            let field' =
                SearchField
                    (field.Name, wrappedField.Type,
                     AnalyzerName = field.AnalyzerName,
                     IndexAnalyzerName = field.IndexAnalyzerName,
                     SearchAnalyzerName = field.SearchAnalyzerName,
                     IsFacetable = field.IsFacetable,
                     IsFilterable = field.IsFilterable,
                     IsSearchable = field.IsSearchable,
                     IsSortable = field.IsSortable,
                     IsHidden = field.IsHidden,
                     IsKey = field.IsKey)
            wrappedField.Fields |> Seq.iter field'.Fields.Add
            wrappedField.SynonymMapNames |> Seq.iter field'.SynonymMapNames.Add
            Some field'
        else
            None

    fields
    |> Seq.choose (fun f -> f |> unwrapOption |> Option.map (fun f' -> f, f'))
    |> Seq.toList
    |> Seq.iter (fun (f, f') ->
                    fields.Remove f |> ignore
                    fields.Add f')
    fields
    |> Seq.iter (fun f -> replaceOption f.Fields)
```

Which is pretty verbose as I have no clue of which type the field was created.
So that it would be extremely helpful to have this extra property in `SearchField` class.

**Comment by heaths** [comment]
The current v11 implementation is mostly copied from the v10 implementation, with a few changes to accommodate design and type differences. @brjohnstmsft would this have worked as desired in v10 (since you're also an F# dev)?

**Comment by heaths** [comment]
Looking into this more, these are separate types and would require specific handling, but could not be a type reference (would require taking a dependency on F# binaries). This is something we can consider, and any PRs are appreciated.

**Comment by xperiandri** [comment]
Well, Newtonsoft.JSON does that without the dependency. We can try that way too

**Comment by heaths** [comment]
The dependency can be avoided by supporting the type via string name, yes, but that is something that would have to be implemented specifically in the `FieldBuilder` as well as anywhere else we deserialize. We do have a preview version of Newtonsoft.Json de/serialization support for Azure.* packages you can try here: https://www.nuget.org/packages/Microsoft.Azure.Core.NewtonsoftJson/1.0.0-preview.1

**Comment by xperiandri** [comment]
Deserialization is not a big deal. I use `FSharp.Text.Json` which covers F# types

**Comment by brjohnstmsft** [comment]
@heaths We never tested this scenario with the previous library. I speculate that perhaps our F# customers at the time weren't using `FieldBuilder`.

It would be great to better support F# scenarios out of the box across the Azure .NET SDK. If this problem exists for Search, it likely exists for other services too. Is there an opportunity to address this more broadly (e.g. -- in the codegen for serialization/deserialization logic)?

**Comment by heaths** [comment]
It would help to know exactly what the expected behavior is. As they are now, to .NET these are just complex types. E.g. should we treat it as a reference- or value-based `Nullable<T>`? Why isn't `Nullable<T>` sufficient? The generated code is still based on .NET types in the BCL, e.g. `Nullable<T>`. While `FieldBuilder` could perhaps provide late-bound checks for `Option` or `ValueOption`, what does that even mean in general? I don't think we couldn't use them in generated code directly since that introduces new dependencies.

/cc @pakrym

**Comment by brjohnstmsft** [comment]
Ideal behaviour would be (@xperiandri please correct me if I'm wrong): If you have a model type in F# with Option fields, they're treated exactly the same as nullable fields in a C# model class.

For example, this record type:

```fsharp
type Hotel = { HotelName : string option }
```

Would be treated exactly the same as this C# class:

```csharp
class Hotel
{
    public string HotelName { get; set; }
}
```

`FieldBuilder` would map the type to `Edm.String`, and JSON serialization would serialize `None` to JSON `null` and vice-versa.

Perhaps a more interesting question is what the behaviour should be for F# fields/properties that aren't optional, since null is disallowed by default in F#. Technically all types in Azure Cognitive Search are nullable (except for collections, which can only be empty, not null).

**Comment by isaacabraham** [comment]
In the past in these situations, I've simply accepted this and not used `Option<'T>` on any types used by e.g. Azure Search etc.. It would be nice if the SDK did support Options (as I imagine it does for Nullable<'T>), but I would ask where will it end?

In my (somewhat limited) experience, you normally go from some rich F# type to a flattened, simpler class that's compatible with the Search (or other) SDK.

The general behaviour I've seen for F# and C# class library interop is to *not* implicitly convert between None and null (although it would be lovely if that were the case).

**Comment by xperiandri** [comment]
@isaacabraham I don't do that. I use F# domain model types as is.
Adding `FSharp.Text.Json` and `Dahomey.Json` is sufficient to handle major cases to put something like this straight into Azure Cosmos DB and get it back
``` F#
[<Struct>]
type DomainID<'t> = private DomainID of Guid

[<Struct>]
type ValidString<'t> = private ValidString of string

/// User
and Uzanto =
    { [<JsonPropertyName("id")>]
      ID : UzantoID
      [<JsonPropertyName("facebookId")>]
      FacebookID : UzantoFacebookID
      PhoneHash : PhoneHash voption
      AvatarURL : UzantoImageUrl voption
      Gender : Gender voption
      Birthday : Birthday voption
      Grupoj : GrupoID HashSet
      Bibliotekoj : Biblioteko list
      [<JsonPropertyName("preferredTags")>]
      PreferredTagIDs : RegistriTagID HashSet
      [<JsonPropertyName("profiledRegistrij")>]
      ProfiledRegistriIDs: RegistriID HashSet
      CreatedAt : DateTime }
and UzantoID = DomainID<Uzanto>
and UzantoImageUrl = Url<Uzanto ImageUrl>
and FacebookID = interface end // fsharplint:disable-line InterfaceNames
//[<Struct>]
and UzantoFacebookID = ValidString<FacebookID> //private FacebookID of string
```

But for Azure Search because of usage of `FieldBuilder` which does not allow to specify destination type via attribute I had to do that workaround and also implement
``` F#
        let rec applyOverrides (fields : IList<SearchField>) =
            let fieldsMap = fields.ToImmutableDictionary (fun f -> f.Name)
            fieldOverrides
            |> Map.toSeq
            |> Seq.iter (fun (name, field) ->
                match fieldsMap.TryGetValue name with
                | false, _ -> ()
                | true, value -> if fields.Remove(value) then fields.Add field)
            fields
            |> Seq.iter (fun f -> applyOverrides f.Fields)
```
that replaces `GeoJSON` type with `GeographyPoint`
``` F#
let private fieldsOverrides : Map<string, SearchField> =
    seq {
        "location", SearchField("location",
                                SearchFieldDataType.GeographyPoint,
                                IsSortable   = Nullable true,
                                IsFilterable = Nullable true)
    }
    |> Map.ofSeq
```

**Comment by xperiandri** [comment]
So that for me serialization is not an issue at all
``` F#
let serializerOptions =
    let options = JsonSerializerOptions(PropertyNamingPolicy = JsonNamingPolicy.CamelCase)
    let converters = options.Converters
    converters.Add (JsonStringEnumConverter ())
    // HACK: Used to overriede incorrect behavior of Dahomey
    // https://github.com/dahomey-technologies/Dahomey.Json/issues/51
    converters.Add (UriConverter ())
    converters.Add (CultureInfoConverter ())
    converters.Add (RegistriCodeConverter ())
    converters.Add (MemberDataCollectionConverter ())
    converters.Add (MesagoConverter ())
    converters.Add (
        JsonFSharpConverter(
            JsonUnionEncoding.InternalTag ||| JsonUnionEncoding.NamedFields
            ||| JsonUnionEncoding.UnwrapSingleCaseUnions
            ||| JsonUnionEncoding.UnwrapRecordCases
            ||| JsonUnionEncoding.UnwrapOption, UnionTag))
    options.SetupExtensions() |> ignore // Use Dahomey.Json
    let registry = options.GetObjectMappingRegistry()
    registry.Register<RegistriTag>(
        fun objectMapping ->
            objectMapping.AutoMap() |> ignore
            let idMapping = (objectMapping.MemberMappings |> Seq.find (fun m -> m.MemberName = "id")) :?> MemberMapping<RegistriTag>
            idMapping.SetConverter(RegistriTagIDConverter()) |> ignore)
    options
```
I just pass `SearchClientOptions` with `JsonSerializerOptions` and it works perfect.

**But the issue is the Search schema generation from a model.**

**Comment by xperiandri** [comment]
@brjohnstmsft, yes. As F# avoids nulls, then `FSharp.Text.Json` treats null as incorrect value for the type not wrapped into `Option<T>` or `ValueOption<T>`

**Comment by heaths** [comment]
So if we were to use lazy binding (as a string) for `Option` and `ValueOption` types in `FieldBuilder`, that should be sufficient at a minimum?

**Comment by xperiandri** [comment]
No, you need to just extract an  underlying type the same as with  `Nullable`. `Option` must be transparent to `FieldBuilder`

**Comment by xperiandri** [comment]
Also as you can see from my example, it is common practice in F# to use single case discriminated unions like `ValidString` which is just a wrapper of a single value. It would be nice if `FieldBuilder` could unpack that as well.

**Comment by xperiandri** [comment]
I will have a look into it the next week
