### ISSUE TITLE
How can I create an active ADF schedule trigger using the .NET SDK with an Azure Function?

### ISSUE THREAD

**Issue by mallecespedes** [Azure/azure-sdk-for-net#15292]
**Query/Question**
How can I create an active ADF schedule trigger using the .NET SDK inside an Azure Function? I already managed to create the trigger but the status is "Stopped". I need the trigger to be running as soon as it is created.

Documentation used: `https://docs.microsoft.com/en-us/azure/data-factory/how-to-create-schedule-trigger#net-sdk`

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.DataFactory v4.11.0, Microsoft.Azure.Management.ResourceManager v3.10.0-preview, Microsoft.IdentityModel.Clients.ActiveDirectory v5.2.8
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure Function App, .NET Framework
 - IDE and version : Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
