### ISSUE TITLE
[FEATURE REQ] Microsoft.Azure.Management.Logic - Client doesn't have input to take user or managed identity

### ISSUE THREAD

**Issue by sindhurirayavaram** [Azure/azure-sdk-for-net#15298]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
 - Microsoft.Azure.Management.Logic Version: 4.1.0, Azure Logic apps
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
- We need to create a logic app workflow with user managed identity
- The present nuget package doesn't have the provision to give identity parameter for logic apps workflow creation.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ecfan** [comment]
@Azure/azure-logicapps-team: Any response to this feedback about managed identities?

**Comment by AlexGhiondea** [comment]
Ping @Azure/azure-logicapps-team.

**Comment by jsquire** [comment]
Since this was created, the `Microsoft.Azure.Management.Logic` package has been deprecated and is scheduled for retirement.  It is currently receiving only critical security fixes.
