### ISSUE TITLE
Azure.Security.KeyVault.Administration Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#15306]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/Azure.Security.KeyVault.Administration#contributing)

![image](https://user-images.githubusercontent.com/65581162/93749871-3d46cf00-fc2d-11ea-990b-c2326386679f.png)

Suggestion: 
1.Update to   `https://cla.microsoft.com` .

2.Update to    `[Microsoft Open Source Code of Conduct][code_of_conduct] `.

3.Add    `[coc_faq]: https://opensource.microsoft.com/codeofconduct/faq/ `.

4.Update to   `opencode@microsoft.com `.

@jongio for notification.

**Comment by heaths** [comment]
Resolved by PR #15720

**Comment by Tianyun-G** [comment]
@heaths - This PR #15720  resolved `Azure.Security.KeyVault.Keys` issue but not `Azure.Security.KeyVault.Administration` Readme issues #15306. So we should reopen this issue.

**Comment by heaths** [comment]
That PR changed .Administration as well: https://github.com/Azure/azure-sdk-for-net/pull/15720/files#diff-38d081175459e2bc24160047f4061d161cd27d840ac763b00f76ff7c6331ecbb

If you still see issues, can you describe them specifically?

**Comment by Tianyun-G** [comment]
@heaths - The issues in the picture haven't been resolved #15306 . 
![image](https://user-images.githubusercontent.com/65581162/95805475-11a09b80-0d38-11eb-8b7f-f01a8490b4b7.png)

**Comment by heaths** [comment]
Does this render correctly? The source markdown shouldn't matter.
