### ISSUE TITLE
Azure.Messaging.EventHubs.Processor Readme issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#15308]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor#azure-event-hubs-event-processor-client-library-for-net)
![image](https://user-images.githubusercontent.com/65581162/93750162-a0d0fc80-fc2d-11ea-985d-9500f7bb1cdc.png)

Suggestion: 
Update link to  https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src  
 
@jongio for notification.

**Comment by jsquire** [comment]
Fixed by #15365
