### ISSUE TITLE
Azure.Data.Tables Readme issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#15307]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/tables/Azure.Data.Tables#creating-a-cosmos-db)

![image](https://user-images.githubusercontent.com/65581162/93837965-a58fc200-fcba-11ea-9ef4-8dd25554abca.png)

Reason: 
Azure Cosmos DB database with Azure Table API specified.

Suggestion: 
 Update  to 
 ```
az cosmosdb create --name MyCosmosDBDatabaseAccount --capabilities EnableTable --resource-group MyResourceGroup --subscription MySubscription 
```

@jongio for notification.

**Comment by christothes** [comment]
Thank you, @Tianyun-G !
