### ISSUE TITLE
Azure.Messaging.EventHubs Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#15303]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs#azure-event-hubs-client-library-for-net)

![image](https://user-images.githubusercontent.com/65581162/93747859-e7245c80-fc29-11ea-8831-63d93029a230.png)

Suggestion: 
Update link to  https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs/src 

2.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs#publish-events-to-an-event-hub)

![image](https://user-images.githubusercontent.com/65581162/93839319-2c469e00-fcbf-11ea-9897-8eb8d692e941.png)

Reason: 
`producerClient`  is not defined.

Suggestion: 
Update `producer` to `producerClient`.

3.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs#prerequisites)

![image](https://user-images.githubusercontent.com/65581162/93748529-05d72300-fc2b-11ea-93c7-9b14ea9dbb44.png)

Suggestion:  
Remove  extra `script`.

@jongio for notification.

**Comment by jsquire** [comment]
Fixed by: #15336
