### ISSUE TITLE
[BUG] Azure Servicebus 4.1.1 Compile time warnings due to conflicting System.IdentityModel.Tokens.Jwt

### ISSUE THREAD

**Issue by ssa3512** [Azure/azure-sdk-for-net#15326]
**Describe the bug**
I am using the Microsoft.Azure.ServiceBus library (v4.1.1) via webjobs/functions triggers extension package. My application references the System.IdentityModel.Tokens.Jwt package version 6.7.1, but Microsoft.Azure.ServiceBus only supports outdated version range >=5.4.0 && < 6.0.0

**Expected behavior**
Microsoft.Azure.ServiceBus supports current version of IdentityModel.Jwt package

**Actual behavior (include Exception or Stack Trace)**
Forced to manually install System.IdentityModel.Tokens.Jwt into top level functions project to prevent package downgrade. Get compiler warnings due to package version mismatch

![image](https://user-images.githubusercontent.com/1991399/93894881-3a93ba80-fcbd-11ea-804b-0d46c4c6d4f8.png)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create library using System.IdentityModel.Tokens.Jwt 6.7.1
2. Create azure functions app with service bus trigger
3. Reference library from (1) with functions app
4. Compile warnings

**Environment:**
 - Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.1.2
 - Microsoft.Azure.ServiceBus 4.1.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 
>.NET Core SDK (reflecting any global.json):
> Version:   3.1.301
> Commit:    7feb845744
>
>Runtime Environment:
> OS Name:     Windows
> OS Version:  10.0.19041
> OS Platform: Windows
> RID:         win10-x64
> Base Path:   C:\Program Files\dotnet\sdk\3.1.301\
 - IDE and version : VS 16.8 preview 3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ssa3512** [comment]
Thanks :) I was digging at this some more and it looks like this issue was resolved for the Microsoft.Azure.ServiceBus library with #10885 (released in v4.1.3) but the Microsoft.Azure.WebJobs.Extensions.ServiceBus package is referencing 4.1.1. If this isn't the right place to report please let me know.

**Comment by axisc** [comment]
@ssa3512 that would be with the Webjobs team, @jsquire - can you help route it?

**Comment by ssa3512** [comment]
It looks like this was resolved as of Microsoft.Azure.WebJobs.Extensions.ServiceBus v4.2.0 released the day after I opened this issue...
