### ISSUE TITLE
[QUERY] Does the App Authentication library support .NET Core (for requesting SQL Database) ?

### ISSUE THREAD

**Issue by TechWatching** [Azure/azure-sdk-for-net#15324]
**Query/Question**
In .NET Framework, I am using [App Authentication library](https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication/1.5.0) with Microsoft.Data.SqlClient Active Directory Interactive authentication mode to authenticate and query an Azure SQL Database without any code change as described in this [blog post](https://azure.microsoft.com/en-ca/blog/securing-azure-sql-databases-with-managed-identities-just-got-easier/). 

Active Directory Interactive authentication mode is now available for .NET Core in Microsoft.Data.SqlClient but I don't know what is the support of App Authentication library for .NET Core. It there a mechanism similar to what is done in .NET Framework to make authentication work simply by setting some configuration and a connection string with "Authentication=Active Directory Interactive" instead of having to manually retrieve the access token and setting it in the SqlConnection.

See related issue  #https://github.com/dotnet/SqlClient/issues/735

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Services.AppAuthentication 1.5.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Core 3.1.402
 - IDE and version : Visual Studio 16.7.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nonik0** [comment]
@TechWatching Unfortunately, we do not yet support the SqlAppAuthenticationProvider scenario for .NET Core. We have a [feature request](https://github.com/Azure/azure-sdk-for-net/issues/8789) for this but at this time I can't give a timeline for when this will be available.
