### ISSUE TITLE
Unable to download a snapshot of an append blob in v12 

### ISSUE THREAD

**Issue by colbroth** [Azure/azure-sdk-for-net#15349]
**Is your feature request related to a problem? Please describe.**
Problem:
Having trouble downloading an actively updating append blob using v12 library. I am in the process of updating our code to v12. In v11, I used the approach recommended here "https://github.com/Azure/azure-storage-js/wiki/Read-an-Actively-Updating-Append-Blob". This approach recommended create a snapshot and download the snapshot. This worked well in the v11 code but I can't seem to download the snapshot in v12 code

Environment:
C# 
netstandard 2.1
nuget  Azure.Storage.Blobs Version="12.6.0"

Code:
string filePath = "archivedata_appendblob/2020/9/element.json";
snapshotBlob = await blobClient.CreateSnapshotAsync();
filePath = $"{filePath}?snapshot={Uri.EscapeDataString(snapshotBlob.Value.Snapshot)}";
blobClient = Container.GetAppendBlobClient(filePath);
var respSnap = await blobClient.DownloadAsync();

The DownloadAsync throws an exception. I see the snapshot using the Microsoft Azure Storage Explorer (the filePath in my code also matches the value returned from "Copy Url" option in storage explorer. 
The filePath variable above resolves to 
archivedata_appendblob/2020/9/element/string/element.json?snapshot=2020-09-22T14%3A48%3A07.0220120Z

I am unsure how to update this code to be able to download the snapshot.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Could you send the StackTrace and be a bit more specific on what exception is being thrown when attempting to download the append blob?

**Comment by seanmcc-msft** [comment]
Here is a code snippet showing how to create and download a snapshot for an Append Blob:
```
using Azure;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;
using System;
using System.IO;
using System.Threading.Tasks;

namespace CreateAndDownloadBlobSnapshot
{
    class Program
    {
        public async static Task Main(string[] args)
        {
            string connectionString = "";
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
            BlobContainerClient blobContainerClient = blobServiceClient.GetBlobContainerClient("testtesttest123");
            try
            {
                // Create Container
                await blobContainerClient.CreateAsync();
                AppendBlobClient appendBlobClient = blobContainerClient.GetAppendBlobClient("myAppendBlob");

                // Create Append Blob
                await appendBlobClient.CreateAsync();

                byte[] data = GetRandomBuffer(1024);
                Stream stream = new MemoryStream(data);

                // Append some data
                await appendBlobClient.AppendBlockAsync(stream);

                // Create a snapshot
                Response<BlobSnapshotInfo> snapshotResponse = await appendBlobClient.CreateSnapshotAsync();

                // Create new AppendBlobClient for the snapshot
                AppendBlobClient snapshotAppendBlobClient = appendBlobClient.WithSnapshot(snapshotResponse.Value.Snapshot);

                // Download snapshot
                await snapshotAppendBlobClient.DownloadAsync();
            }
            finally
            {
                await blobContainerClient.DeleteAsync();
            }
        }

        public static byte[] GetRandomBuffer(long size)
        {
            Random random = new Random(Environment.TickCount);
            var buffer = new byte[size];
            random.NextBytes(buffer);
            return buffer;
        }
    }
}

```

**Comment by colbroth** [comment]
Thank you. I used this code snippet and was able to download the snapshot. I was missing " .WithSnapshot " when creating the snapshot client. Is there a git repo containing examples with this code snippet?

**Comment by seanmcc-msft** [comment]
We may have a similar code snippet in https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs/samples
