### ISSUE TITLE
[BUG] Docs need to follow azure service naming guidelines.

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#15376]
Doc: 
https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Storage.Blobs/12.6.0/api/index.html#prerequisites

Uses this:
```bash
az storage account create --name MyStorageAccount --resource-group MyResourceGroup --location westus --sku Standard_LRS
```

--name must be lowercase.

You get this error:
```
MyStorageAccount is not a valid storage account name. Storage account name must be between 3 and 24 characters in length and use numbers and lower-case letters only.
```

Let's scrub docs to ensure we follow the az rules wrt to naming.

**Comment by JimSuplizio** [comment]
Hi @jongio, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
