### ISSUE TITLE
Support custom serialization for table entities

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#15383]
# Summary
Currently table entity serialization is not customizable and relies on reflection for custom entity types. We'd like to integrate with `ObjectSerializer` to provide a standard and customizable serialization story for entities. 

Tables serialization will require customization to accommodate OData annotations and transformation to/from the expected wire format of `Dictionary<string, object>`.

# Scope of Work
Investigate and implement an approach to serialization that incorporates `ObjectSerializer` and removes the need for reflection over custom entity type properties.

# References
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Serialization/ObjectSerializer.cs
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to

**Comment by christothes** [comment]
The closer I've gotten to implementing this change the more I question it. Essentially, to implement support for `ObjectSerializer` we'd have to the following:
**Serialization**
- serialize from `T` to a stream
- read the stream and re-serialize each property as a dictionary property to a new stream
- serialize odata annotation properties for required types to the new stream while preserving any property renaming

**De-Serialization**
- de-serialize json to dictionary
- serialize dictionary to `T` shaped json
- de-serialize json to `T`

Alternatively we could expose a `Func<T, IDictionary<string, object>` and  `Func<IDictionary<string, object>, T` on a new interface allowing developers to supply a custom conversion of `T` to `IDictionary<string, object>` and vice versa, which the client does under the covers already with its own implementation.

I'll leave this issue in the backlog for now to gauge customer interest in such an extensibility point.

**Comment by tcc-sejohnson** [comment]
Just wanted to voice my support for this. Whenever working with Azure Table Entities, I find myself creating one class implementing `ITableEntity` and another class, a superset of the `ITableEntity` class, with `ToTableEntity` and `FromTableEntity` methods, which I then use before saving or after retrieving entities. 

The resolution requested in #19782 would pretty well fulfill all of my needs, but for a complete implementation, we definitely need this.

**Comment by andrew-hampton** [comment]
Adding a +1 to this. I was looking to upgrade our project to using the Azure.Data.Tables package moving from the Microsoft.Azure.Cosmos.Table package. Previously we had custom serialization and deserialization logic by implementing the ReadEntity and WriteEntity methods that were previously included on the ITableEntity interface. This allowed us to ignore properties on the class as well as do things like split values between multiple columns if it was a particularly large field. It doesn't appear that the new library has the fine grained control over this that would allow us to migrate to using it

**Comment by christothes** [comment]
@andrew-hampton We do support ignoring of properties via the `[IgnoreDataMember]` attribute. I think you should be able to accomplish your scenario with the new client.

**Comment by pooventhan** [comment]
+1 on this.

Our current project (references deprecated WindowsAzure.Storage package) contains an entity class as per below:

```c#
public class CustomEntity : TableEntity
{
	public string CreatedBy { get; set; }
	
	[IgnoreProperty]
	public CustomSubEntity1 CustomSubEntity1 { get; set; }

	[IgnoreProperty]
	public List<CustomSubEntity2> CustomSubEntity2 { get; set; }

	public override void ReadEntity(IDictionary<string, EntityProperty> properties, OperationContext operationContext)
	{
		// Custom deserialization implementation for CustomSubEntity1
		
		// Custom deserialization implementation for CustomSubEntity2
	}
	
	public override IDictionary<string, EntityProperty> WriteEntity(OperationContext operationContext)
	{
		// Custom serialization implementation for CustomSubEntity1
		
		// Custom serialization implementation for CustomSubEntity2

	}
}
```
Understood that we could replace `IgnoreProperty` attribute with `IgnoreDataMember` when upgrading to Azure.Data.Tables package. But, how could we get around for the custom ReadEntity and WriteEntity implementation?

**Comment by christothes** [comment]
@pooventhan Could you describe your specific scenario that requires Read/Write entity customization?

**Comment by andrew-hampton** [comment]
Following back up on this, I believe I may be able to accomplish my scenarios by having a translation layer between my entities and TableEntity and utilizing the Dictionary<string, object> that it provides to implement my own serialization/deserialization. I haven't had an opportunity to fully vet this approach though. Thanks @christothes

**Comment by tcc-sejohnson** [comment]
@pooventhan 

Having used the previous library and this one, I liked the ability to implement custom serialization logic. Not being able to in this library isn't my favorite. I've found two methods to get around it:

1. Add a constructor to your "domain" object
2. Add a helper method to your POCO

Both of the above involve making POCOs of your Azure Tables attributes that _exactly_ match the table spec. So if you had your object, under situation 1, your solution would look like:

```csharp
public class CustomEntityPOCO : TableEntity
{
	public string CreatedBy { get; set; }
	
	public string CustomSubEntity1 { get; set; }

	public string CustomSubEntity2 { get; set; }

	// This is assuming you're storing CustomSubEntity1 and 2 in a single json-encoded column or something
	// if that's not the case, that's fine -- just make a property for each column.
}

public class CustomEntity {
	public string CreatedBy { get; set; }
	
	public CustomSubEntity1 CustomSubEntity1 { get; set; }

	public List<CustomSubEntity2> CustomSubEntity2 { get; set; }

	public CustomEntity(CustomEntityPOCO poco) {
		this.CreatedBy = poco.CreatedBy;
		this.CustomSubEntity1 = CustomEntity.ParseSubEntity1(poco);
		this.CustomSubEntity2 = CustomEntity.ParseSubEntity2(poco);
	}

	private static CustomSubEntity1 ParseSubEntity1(CustomEntityPOCO poco) {
		// Implementation
	}

	private static CustomSubEntity2 ParseSubEntity2(CustomEntityPOCO poco) {
		// Implementation
	}
}
```

I don't _love_ this solution because it forces `CustomEntity` to have an explicit dependency on the Table service.

Solution 2 would look like:

```csharp
public class CustomEntityPOCO : TableEntity
{
	public string CreatedBy { get; set; }
	
	public string CustomSubEntity1 { get; set; }

	public string CustomSubEntity2 { get; set; }

	public CustomEntity ToCustomEntity() {
		// Implementation
}

public class CustomEntity {
	public string CreatedBy { get; set; }
	
	public CustomSubEntity1 CustomSubEntity1 { get; set; }

	public List<CustomSubEntity2> CustomSubEntity2 { get; set; }
}
```

Then, to use your table poco after retrieving it:
```csharp
var customEntity = customEntityPoco.ToCustomEntity();
```

I find that customEntityPoco.ToCustomEntity() is the closest I can get to the old pattern. I kinda like it, too, because you can then declare an interface called `CustomEntityLike` with one method, `ToCustomEntity`, which you can then use as an argument to other functions, removing your main code's dependency on Azure Tables completely.

That being said... I still wish I could declare custom serialization/deserialization for stuff like this.

**Comment by pooventhan** [comment]
@tcc-sejohnson Thank you very much for your suggestions! Appreciate it. I prefer solution 2 as well - it is much cleaner. :grinning:

@christothes We're storing JSON encoded values in few columns. Hence, the need for read/write customization.

**Comment by christothes** [comment]
> @christothes We're storing JSON encoded values in few columns. Hence, the need for read/write customization.

Could you elaborate on why this requires custom serialization?

**Comment by allxiao** [comment]
We are working on migrating our WindowsAzure.Storage libraries to Azure.Data.Tables. However, we found there is no support for the `ReadEntity` / `WriteEntity` hook, and there is no official recommended way how we can achieve similar functionality in the new library.

With `ReadEntity` / `WriteEntity` hook, it's easy to inject custom serialization logic around entity read / write. We use this to convert custom types from / to JSON string stored in table columns. We also use this to handle the schema change and ensure smooth transition from old schema to new schema. We only need to care about the properties that do need special handling. Those primitive typed properties will be handled by the default logic. It's pretty handy to implement custom logic there, and make some generic solution with the help of custom attributes.

The current library doesn't offer such kind of flexibility. Solution 2 provided by @tcc-sejohnson works. However, we need to implement two nearly identical model classes, and we need to make sure the two classes and the `ToCustomEntity()` and `ToPOCO()` implementation are all in-sync, which is time consuming and error prone, especially when the entity includes a lot of properties.

**Comment by tcc-sejohnson** [comment]
> We are working on migrating our WindowsAzure.Storage libraries to Azure.Data.Tables. However, we found there is no support for the `ReadEntity` / `WriteEntity` hook, and there is no official recommended way how we can achieve similar functionality in the new library.
> 
> With `ReadEntity` / `WriteEntity` hook, it's easy to inject custom serialization logic around entity read / write. We use this to convert custom types from / to JSON string stored in table columns. We also use this to handle the schema change and ensure smooth transition from old schema to new schema. We only need to care about the properties that do need special handling. Those primitive typed properties will be handled by the default logic. It's pretty handy to implement custom logic there, and make some generic solution with the help of custom attributes.
> 
> The current library doesn't offer such kind of flexibility. Solution 2 provided by @tcc-sejohnson works. However, we need to implement two nearly identical model classes, and we need to make sure the two classes and the `ToCustomEntity()` and `ToPOCO()` implementation are all in-sync, which is time consuming and error prone, especially when the entity includes a lot of properties.

FYI - If you implement ToPOCO as a constructor on your POCO object instead, it's more or less the same as the old ReadEntity/WriteEntity bindings. So essentially:

```csharp
public class CustomEntityPOCO : TableEntity
{
  public CustomEntityPOCO(CustomEntity entity) { ... }

	public string CreatedBy { get; set; }
	
	public string CustomSubEntity1 { get; set; }

	public string CustomSubEntity2 { get; set; }

	public CustomEntity ToCustomEntity() {
		// Implementation
}
```

This is really the same as the old way was as far as maintenance goes, except that it requires slightly more work upfront to create the POCO entity. You're still only managing your serialization/deserialization in one place: the POCO class. This also aligns with DI best practices -- your domain object (`CustomEntity`) doesn't have to know about Azure Tables at all.

**Comment by allxiao** [comment]
I'm not sure if I get the point. To my understanding, the work now at least doubles, rather than "requires slightly more work".

Before:

```csharp
// 1 time across the project, or probably multiple projects by sharing this in library
public abstract class CompoundEntity : TableEntity {
    public override IDictionary<string, EntityProperty> WriteEntity(OperationContext operationContext)
    {
        var result = base.WriteEntity(operationContext);
        // additional property cache can be built to improve performance
        var jsonProperties = GetType()
            .GetProperties(BindingFlags.Instance | BindingFlags.Public)
            .Where(p => p.GetCustomAttribute(typeof(CustomPropertyAttribute)) != null);
        foreach (var prop in jsonProperties)
        {
            result[prop.Name] = new EntityProperty(JsonConvert.SerializeObject(prop.GetValue(this)));
        }

        return result;
    }

   // similar ReadEntity implementation
}

// Add CustomProperty attribute to the property that needs special care.
// One time for each property that needs conversion.
// No change to the supported property type
public class MyEntity : CompoundEntity
{
    public string PropertyOne { get; set; }

    [CustomProperty]
    public CustomType PropertyTwo { get; set; }
}
```

With the POCO and domain object split, I need to write a specialized POCO object for each of the domain object. This will repeat the entity property 4 times.

```csharp
public class MyEntity
{
    public string PropertyOne { get; set; }
    public CustomType PropertyTwo { get; set; } // 1
}

public class MyEntityPoco : ITableEntity
{
    public MyEntityPoco(MyEntity entity)
    {
        // key assignments ignored

        PropertyOne = entity.PropertyOne;
        PropertyTwo = JsonConvert.SerializeObject(entity.PropertyTwo); // 2
    }

    public string PartitionKey { get; set; }
    public string RowKey { get; set; }
    public DateTimeOffset? Timestamp { get; set; }
    public ETag ETag { get; set; }

    public string PropertyOne { get; set; }
    public string PropertyTwo { get; set; }  // 3

    public MyEntity ToDomainEntity()
    {
        return new MyEntity
        {
            PropertyOne = PropertyOne,
            PropertyTwo = JsonConvert.DeserializeObject<CustomType>(PropertyTwo), // 4
        };
    }
}
```

If I wire up similar reflection solution, I still need to repeat each properties in two places.

```csharp
public class MyEntity
{
    public string PropertyOne { get; set; }
    [CustomProperty]
    public CustomType PropertyTwo { get; set; }  // 1
}

internal static class CompoundEntity
{
    internal static readonly ConcurrentDictionary<Type, Dictionary<string, PropertyInfo>> PropertiesCache = new();
}

public abstract class CompoundEntity<T> where T : new()
{
    public CompoundEntity(T entity)
    {
        var thisProperties = CompoundEntity.PropertiesCache.GetOrAdd(GetType(), t =>
        {
            return t.GetProperties(BindingFlags.Instance | BindingFlags.Public).ToDictionary(p => p.Name, p => p);
        });
        var properties = entity.GetType().GetProperties(BindingFlags.Instance | BindingFlags.Public);
        foreach (var prop in properties)
        {
            if (prop.GetCustomAttribute(typeof(CustomPropertyAttribute)) == null)
            {
                thisProperties[prop.Name].SetValue(this, prop.GetValue(entity));
            }
            else
            {
                thisProperties[prop.Name].SetValue(this, JsonConvert.SerializeObject(prop.GetValue(entity)));
            }
        }
    }

    public T ToDomainEntity()
    {
        // similar logic as in the constructor
        return default;
    }
}

public class MyEntityPoco : CompoundEntity<MyEntity>, ITableEntity
{
    public MyEntityPoco(MyEntity entity) : base(entity)
    {
        // key assignments ignored
    }

    public string PartitionKey { get; set; }
    public string RowKey { get; set; }
    public DateTimeOffset? Timestamp { get; set; }
    public ETag ETag { get; set; }

    public string PropertyOne { get; set; }
    public string PropertyTwo { get; set; }   // 2
}
```

This also introduce some complexity when we 1) retrieve the entity, 2) convert to domain object, 3) operate on domain object, 4) save back and step 3 consists of multiple calls. We need to pass the key and etag all along step 3 to step 4. 

I understand that in design patterns domain object should only care about the domain business and ignore the persistent layer. However, if we are not going to change the underlying storage, and we duplicate the POCO and domain object mainly to resolve the limitation in the storage library, we may need further consider if this design is good for the project development and later maintenance.

It may be better that the storage / persistent library is neutral to the application level design by providing flexibility on extending the persistence behavior, rather than enforcing on a given design pattern. An example is the JSON library like Newtonsoft.Json. By default it provides serialization / deserialization support for basic types. You can also add custom `JsonConverter` to classes, properties, fields or globally to customize the serialization / deserialization behavior in a declarative way. Only certain attributes need to be attached, no serialization / deserialization logic needs to be added to the domain object.

**Comment by longtimedeveloper** [comment]
@christothes are you all making any progress on adding the `[IgnoreProperty]` attribute?  We have to use workarounds out here in the world until this missed feature gets added in.

Greatly appreciate your time and consideration.

**Comment by christothes** [comment]
Hi @longtimedeveloper - I'm not aware of any plans to add support for the `[IgnoreProperty]` attribute. As mentioned earlier in this issue, we do support `[IgnoreDataMember]`.

**Comment by longtimedeveloper** [comment]
@christothes I'm was just testing after re-reading this thread.  Thank you!!  Apologies for randomizing you.

**Comment by longtimedeveloper** [comment]
@christothes here is my real-world usage of the `IgnoreDataMember` attribute.  For my table storage `PartitionKey` and `RowKey` I add an ignored property that has a friendly name to gets and sets these.  Make my code easier to read and maintain.  Notice, event the name of the property has the property it wraps.

Best regards, Karl

```
    /// <summary>
    /// GeneratedTokenPartitionKey, gets and sets the PartitionKey
    /// </summary>
    [IgnoreDataMember]
    public String GeneratedTokenPartitionKey {
      get { return this.PartitionKey; }
      set { this.PartitionKey = value; }
    }

    /// <summary>
    /// Generated Token
    /// </summary>
    public String PartitionKey { get; set; }
```

**Comment by smartouss** [comment]
Adding custom serializer completely will be great, like replacing System.Text.Json with newtonsoft, i'm moving from old apis to new ones and i was using Newtonsoft and now System.Text.Json and Utf8JsonWriterExtensions giving me hard time, it's not forgiving (forcing specify DatetimeKind everywhere) and a lot of unsupported exceptions, also i was disappointed with this new api as its very hard to make it work with dynamic objects unless i force my models depend on ITableEntity
