### ISSUE TITLE
Retrieving subscriptions fails for some users

### ISSUE THREAD

**Issue by sandercox** [Azure/azure-sdk-for-net#1539]
I'm using the Azure SDK to retrieve subscriptions and access Azure DNS records in a GUI application. http://github.com/sandercox/AzureDNSManager for some users the retrieval process of the subscriptions seem to fail but to the best of my knowledge this code should have worked.

I setup an AzureContext class with empty credentials and use it to authenticate:
```c#
AzureSession.AuthenticationFactory.Authenticate(_azureContext.Account, _azureContext.Environment, "common", null, Microsoft.Azure.Common.Authentication.ShowDialog.Auto);
```

After my user is authenticated (this part seems to work correctly) trying to retrieve a list of subscriptions returns an empty list for some (_subscriptions.Count = 0):
```c#
            try
            {
                _subscriptionClient = AzureSession.ClientFactory.CreateClient<SubscriptionClient>(_azureContext, AzureEnvironment.Endpoint.ResourceManager);
                _subscriptions = _subscriptionClient.Subscriptions.List().Subscriptions;
                if (_subscriptions?.Count >= 1)
                {
                    ActiveSubscription = _subscriptions[0].SubscriptionId;
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: " + ex.Message);
            }
```

Am I missing something trivial here?

**Comment by hovsepm** [comment]
Could you provide traffic logs? I don't see any issue with the code

**Comment by sandercox** [comment]
How do I turn on traffic logs?

**Comment by hovsepm** [comment]
@sandercox e.g. Fiddler tool can capture traffic logs.

**Comment by kirthik** [comment]
Closing this since there hasn't been a response for 6 months now and we could not repro the issue. If you are still seeing this problem, please open a new issue with traffic logs.
