### ISSUE TITLE
[QUERY] Azure.Storage.Blobs - How are md5 hash's handled?

### ISSUE THREAD

**Issue by chris-skuvault** [Azure/azure-sdk-for-net#15398]
**Query/Question**
How are md5 hash's handled withing the library? I see that when I upload to the blob it computes a hash because I see it when I download the blob from storage. Does the library handle comparing the hash to verify the payload or is that something the caller needs to do themselves by md5 hashing the payload after downloading and comparing with the ContentHash received from the download result? I didn't see much or any documentation on this. In the tests files for the SDK itself it looks like it is manually done.

**Environment:**
 - Azure.Storage.Blobs latestStable

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Just to be clear, is your question, does the SDK calculate it's own MD5 hash and compare it to the `Content-MD5` hash that the storage service returns back in the response headers when you go to download the blob?
Then no, the SDK does not calculate it's own md5 hash and compares it against the one the service returns back. You as the caller will have to calculate the md5 hash and compare it.

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
