### ISSUE TITLE
Sample for DataLake Recursive Acl

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#15409]
We should include a sample on how to use `PathClient.SetAccessControlRecursive` along with `Update` and `Remove`. This will also include how to use the progress handler, options, and how to handle exception handling.

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
