### ISSUE TITLE
Review Distributed Tracing features in the new Service Bus library

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#15410]
When we were working on Azure.Messaging.EventHubs and Azure.Messaging.EventHubs.Processor packages, we had a definite set of requirements of how each send request and the different modes of receiving events did tracing. Service Bus is in a similar boat as Event Hubs in terms of tracing needs with the addition of a whole new set of methods for peek, receiving deferred messages, sending scheduled messages etc.

This issue is to review how much of what we did in Event Hubs can be ported over to Service Bus and figure out the gaps.

**Comment by JoshLove-msft** [comment]
Reviewed with Azure Monitor team.
PR - https://github.com/Azure/azure-sdk-for-net/pull/16840
