### ISSUE TITLE
Add extension methods to convert between GeoJson and Microsoft.Spatial

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#15432]
In the same package as #15431 (Microsoft.Azure.Core.Spatial), add extension methods to convert between GeoJson types and Microsoft.Spatial types since we can't implement cast operators on either.

This will allow `SearchDocument.GetPoint` and `SearchDocument.GetPointCollection` to work.

*Note: the `RootNamespace` of that package should be changed to just `Azure.Core` so we can have both `Serialization` and `GeoJson` sub-namespaces using default behavior in VS.*

**Comment by AlexGhiondea** [comment]
Closing for now.
