### ISSUE TITLE
[BUG]  "FilesystemNotFound" and "FilesystemBeingDeleted" ErrorCodes are not available as a constans

### ISSUE THREAD

**Issue by YevgenBorodkin** [Azure/azure-sdk-for-net#15441]
I cannot find a public constant for FilesystemNotFound and FilesystemBeingDeleted ErrorCodes and I have to use magic strings. 
` try
            {
            }
            catch (RequestFailedException e) when ( e.ErrorCode == "FilesystemNotFound" || e.ErrorCode == "FilesystemBeingDeleted")
            {
...
            }
`

**Expected behavior**
FilesystemNotFound and FilesystemBeingDeleted should be public constants

**Comment by jsquire** [comment]
Hi @YevgenBorodkin.  Thank you for your feedback.  Would you be so kind as to help me understand the context of what library you are working with so that I can enlist the right folks to assist?

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement and it is not clear what SDK this is in reference to.   Please feel free to reopen with additional context if you would like to pursue this feedback.
