### ISSUE TITLE
Nightly packages are not publishing

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-net#15442]
According to this pipeline step:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=551020&view=logs&j=b1e79959-24d8-5aa9-2799-72d40c3e051b&t=4b34df18-a0a9-5141-3485-374c7e76236f&l=2

The package ```Microsoft.Azure.ApplicationInsights.Query.0.9.0-alpha.20200924.1``` should have been published to the public ```azure-sdk-for-net``` feed, however it isn't there. Is this a bug with our logic, or is there a bug with the ```NuGetCommand``` task.

**Comment by mitchdenny** [comment]
Turns out it is a sorting issue. Disregard.

**Comment by jsquire** [comment]
@mitchdenny;  Does that mean that this issue can be closed out?   Please advise.

**Comment by mitchdenny** [comment]
Yep. Sorry I thought I closed it.
