### ISSUE TITLE
[FEATURE REQ] AzureKeyVaultConfigurationSource should not create a new config provider during Build

### ISSUE THREAD

**Issue by irontoby** [Azure/azure-sdk-for-net#15459]
In `Azure.Extensions.AspNetCore.Configuration.Secrets`, a new `AzureKeyVaultConfigurationProvider` is [created in the `AzureKeyVaultConfigurationSource.Build` method](https://github.com/Azure/azure-sdk-for-net/blob/a3b6a5ff0f73177571aeaf5670f5fbe753d942fb/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationSource.cs#L21):

```csharp
public IConfigurationProvider Build(IConfigurationBuilder builder)
{
    return new AzureKeyVaultConfigurationProvider(_options.Client, _options.Manager, _options.ReloadInterval);
}
```

The problem with this is that, while configuring my ASP.NET Core app, I need to build the ConfigurationBuilder multiple times. This is because our KeyVault settings are set in environment variables + appsettings.json, and our Azure App Configuration connection string is stored in KeyVault.

So basically I need to:
```csharp
Host.CreateDefaultBuilder()
    .ConfigureAppConfiguration(configBuilder =>
    {
        var config = configBuilder.Build(); // load KeyVault settings from default config locations
        var keyVaultOpt = config.GetSection("KeyVault").Get<KeyVaultOptions>();

        var cred = new ClientSecretCredential(keyVaultOpt.TenantId, keyVaultOpt.ApplicationId, keyVaultOpt.Secret);
        configBuilder.AddAzureKeyVault(new Uri(keyVaultOpt.Url), cred);

        config = configBuilder.Build(); // load AppConfig settings from KeyVault
        var appConfigOpt = config.GetSection("AppConfig").Get<AppConfigOptions>();

        configBuilder.AddAzureAppConfiguration(appConfigOpt.ConnectionString);
    });
```

However since `AzureKeyVaultConfigurationSource` creates a new `AzureKeyVaultConfigurationProvider`, two separate providers will be created: once during my second `configBuilder.Build()`, and once when the app builds it for the final time. That means that my KeyVault secrets are loaded twice, causing unnecessary delays during startup.

If instead, `AzureKeyVaultConfigurationSource` used a `Lazy<T>` and only created it once:
```csharp
internal class AzureKeyVaultConfigurationSource : IConfigurationSource
{
    private readonly AzureKeyVaultConfigurationOptions _options;
    private readonly Lazy<AzureKeyVaultConfigurationProvider> _providerLazy;

    public AzureKeyVaultConfigurationSource(AzureKeyVaultConfigurationOptions options)
    {
        _options = options;
        _providerLazy = new Lazy<AzureKeyVaultConfigurationProvider>(() =>
            new AzureKeyVaultConfigurationProvider(_options.Client, _options.Manager, _options.ReloadInterval));
    }

    /// <inheritdoc />
    public IConfigurationProvider Build(IConfigurationBuilder builder)
    {
        return _providerLazy.Value;
    }
}
```

Then the provider wouldn't be re-created and (as far as I can tell) the secrets are loaded only once.

I'm open to other suggestions on how to better accomplish this; I realize that building the `ConfigurationBuilder` multiple times isn't the standard practice, but I feel like storing the App Config connection string in Key Vault has to be a somewhat common practice so maybe there's a better way?

It would also be very helpful if `AzureKeyVaultConfigurationProvider` (and `AzureKeyVaultConfigurationSource` for that matter) were `public` instead of `internal` so I could accomplish this within my app, if there is a reason this request can't implemented.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
This seems like a feature request for Microsoft.Extensions.Configuration to support chained providers that depend on each other.

If you create a new configuration builder for AzureKeyVault and then add the resulting `IConfiguration` instance into the original `configBuilder` using https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.chainedbuilderextensions.addconfiguration?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Configuration_ChainedBuilderExtensions_AddConfiguration_Microsoft_Extensions_Configuration_IConfigurationBuilder_Microsoft_Extensions_Configuration_IConfiguration_ you would end up with only a single `AzureKeyVaultConfigurationSource` instance in you app.

**Comment by irontoby** [comment]
@pakrym thanks for the suggestion; I hadn't come across the Chained Configuration builder/provider before so I'll look more into this. The documentation seems very light for those but I'll see if I can get it working w/o building twice.

**Comment by pakrym** [comment]
Sorry for the late response, but why wouldn't it allow the reload?

**Comment by irontoby** [comment]
@pakrym the initial proposal would support reloading because the individual providers are still used. I've spent some time trying out `ChainedBuilderExtensions` / `ChainedBuilderProvider` and it won't work because the configuration is copied to the provider only once at startup.

Does Microsoft have any recommendations/best practices for using both KeyVault and App Configuration providers together in this manner?

If you could make `AzureKeyVaultConfigurationProvider` `public` instead of `internal`, then I could at least create a custom version of `AzureKeyVaultConfigurationSource` which didn't recreate a provider each time `Build` is called.

**Comment by irontoby** [comment]
@pakrym do you think it would be possible to make `AzureKeyVaultConfigurationProvider` `public` instead of `internal`? Being able to derive from this provider would allow me to customize this behavior and avoid loading the secrets twice.
