### ISSUE TITLE
[EventHubs] Update sample template, contributing guide, and readme for Schema Registry usage scenario

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-sdk-for-net#15463]
Based on: https://github.com/Azure/azure-sdk-for-net/pull/15433

The PR added support for using Schema Registry via ObjectSerializer in BinaryData. The samples infrastructure was updated to work with this kind of workflow. However, all the related documents were not updated to detail this scenario. This issue is to update those related documents.

**Comment by jsquire** [comment]
Closing this out;  the service team has clarified that Schema Registry is intended to be a stand-alone offering but that its form and timing are unclear.  Samples for its use would belong in the cross-service samples area and not be exclusive to Event Hubs.   Once we begin planning for Schema Registry, we'll be sure to include samples as part of the needed efforts and determine what form they should take.
