### ISSUE TITLE
EventGridEvent ctor parameters are ordered inconsistently from other SDK languages

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#15476]
The Event Grid C# SDK's EventGridEvent public constructor has its parameters ordered differently from other language SDKs.  We should probably address this inconsistency in an upcoming beta release:

[EventGridEvent.cs#L26](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/EventGridEvent.cs#L26)
```cs
public EventGridEvent(object data, string subject, string eventType, string dataVersion)
````
[EventGridEvent.java#L51](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/eventgrid/azure-messaging-eventgrid/src/main/java/com/azure/messaging/eventgrid/EventGridEvent.java#L51)
```cs
public EventGridEvent(String subject, String eventType, Object data, String dataVersion) {
```

https://docs.microsoft.com/en-us/azure/event-grid/event-schema#event-properties
JSON schema ordering: subject, eventType, [data], [dataVersion]

**Comment by ellismg** [comment]
@JoshLove-msft 

For JavaScript, we don't actually have an `EventGridEvent` or `CloudEvent` type that you construct.  Instead, we have defined an interface that says what required and optional properties an object must have to be passed to our `sendEvent` method.  Developers can construct such objects that fit that interface however they see fit, including using the object literal notation, i.e.:

```js
sendEvent({ data: {}, subject: "some subject", eventType: "sample", dataVersion: "1.0");
```

In this case, the order of the keys in the object is uninteresting, the above is identical to:

```js
sendEvent(subject: "some subject", eventType: "sample", { data: {}, dataVersion: "1.0");
```

**Comment by JoshLove-msft** [comment]
@rakshith91 I assume Python is similar to JS here?

**Comment by rakshith91** [comment]
@JoshLove-msft Python with it's `kwargs` has this:

`EventGridEvent( subject, event_type, **kwargs)`

**Comment by JoshLove-msft** [comment]
We will update to move the `data` parameter right before the `dataVersion` parameter. This will also make things more consistent with the `CloudEvent` ctor.

**Comment by rakshith91** [comment]
@JoshLove-msft 
It was discussed in the cross language consistency meeting to use this order - 
```
def __init__(self, data, subject, event_type, data_version, **kwargs):
```

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft
> It was discussed in the cross language consistency meeting to use this order -
> 
> ```
> def __init__(self, data, subject, event_type, data_version, **kwargs):
> ```

I think this was before @YijunXieMS pointed out the inconsistency between the CloudEvent and EventGridEvent ctors. Can we discuss again tomorrow?

**Comment by rakshith91** [comment]
makes sense - agree with the inconsistency in both the Events - sure
