### ISSUE TITLE
[BUG] Microsoft.Azure.Management.ResourceGraph version 2.0.0 doesn't allow to change ApiVersion

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-sdk-for-net#15480]
**Describe the bug**

Microsoft.Azure.Management.ResourceGraph.ResourceGraphClient doesn't allow to set `ApiVersion` to another version, such as preview.

**Expected behavior**

Property `ApiVersion` is either has public setter or is settable via constructor.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

Value `2019-04-01` is hardcoded.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. `var client = new ResourceGraphClient(httpClient, fase);`
2. `client.ApiVersion = "xyz"; // doesn't compile`

**Environment:**
 - Microsoft.Azure.Management.ResourceGraph version 2.0.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by abatishchev** [comment]
@jsquire ping on this issue, please

**Comment by jsquire** [comment]
Unfortunately, I am only the first-line triage in this case and have no insight.    @allenjzhang (assigned) would be the best point of contact to understand the current status.

**Comment by markcowl** [comment]
@abatishchev This is by design.  Track 1 SDKs are linked to a specific api contract, so api-version is not settable.  In Track 2 SDKs, we plan to ebnable setting api-version to an earlier, known api-version, but there are no plans to allow arbitrary api-version settings.
