### ISSUE TITLE
Spatial type converters should read and write all properties

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#15483]
As we write more support for converting spatial types, we should support reading and writing full type information like the "crs". We may not need them in all use cases (like Search), but if people are using those types for other use, full fidelity may be important to avoid any data loss. For example, if they are storing "crs" and we fail to read and/or write it, there will be data loss.

**Comment by jsquire** [comment]
If one of you fine folks would be so kind as to triage with an estimate, it would be greatly appreciated.

**Comment by heaths** [comment]
Shouldn't take long if we can do most of that in shared code, e.g. base class.

**Comment by heaths** [comment]
@jsquire @AlexGhiondea do we have to estimate things on the backlog? We usually open tracking issues on the backlog so we don't spend time investigating just yet. Seems a bit premature.

**Comment by jsquire** [comment]
I'll defer to @AlexGhiondea as the authoritative voice, but I believe that unestimated backlog items were being flagged as invalid by the reports.

**Comment by jsquire** [comment]
@heaths:  I just scanned the source for the validation reports and I don't see a check for estimate.   I stand corrected; please feel free to ignore me.   I'll untag things.

**Comment by pallavit** [comment]
@jsquire do we have plans to do this anymore? /cc: @heaths 
_As we right more support for converting spatial types, we should support reading and writing full type information like the "crs"._

**Comment by jsquire** [comment]
@pallavit: Unknown.  This was not something that seems to have had a lot of momentum around it, and I don't have enough insight to understand the cost/benefit.   It seems @heaths may be better positioned to offer thoughts.

**Comment by heaths** [comment]
There's not been a need / feedback to be able to write these, and reading and writing back out unknown properties for portability has already been discussed e.g., `JsonExtensionDataAttribute`. But with our focus on `BinaryData`, I don't know if it's a priority anymore. Thoughts? /cc @annelo-msft @KrzysztofCwalina @tg-msft @m-nash

**Comment by annelo-msft** [comment]
Is this something we would want to address with the new reader/writer interfaces shipping soon in System.ClientModel?  If we could pop up a level and identify the end-scenario that motivated originally filing this issue, we might be better able to evaluate if this would be a good candidate for implementing e.g. IPersistableModel and getting the reading/writing of properties handled for free as part of that.

**Comment by heaths** [comment]
The original intent was to support round-tripping not just the spatial types (this bug), but all our models - for customer serialization, not wire formats since we know if a model is read-only or read-write. I could swear I opened or at least commented on an old issue about that but couldn't find it yesterday.

Unless you or @m-nash are aware of an existing issue about this, I can open a separate one and, if you agree, close this one in favor of that more general tracking issue. I don't feel it's worth doing for spatial types alone as we've had no customer feedback about this AFAIK.

**Comment by pallavit** [comment]
Given our reader/writer interfaces in ClientModel are meant to solve the following - _intent was to support round-tripping not just the spatial types (this bug), but all our models - for customer serialization, not wire formats since we know if a model is read-only or read-write._  I don't think we need a follow-up bug either here.

I vote for closing the issue. Please let me know if anyone disagrees.
