### ISSUE TITLE
Support ordering of pipeline policies

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#15516]
Currently there is no way to add library specific policies at a certain spot in the pipeline. We also can't pass the entire pipeline in as many of the default policies are internal to Azure.Core. This may be needed for CloudEvents in order to populate the event attributes with the TraceParent from the Http Request.
https://github.com/Azure/azure-sdk-for-net/issues/14930

**Comment by pakrym** [comment]
We've implemented the feature without requiring this change.

**Comment by JoshLove-msft** [comment]
Reopening as we want to confirm with the service team that the current approach in Event Grid is okay.

**Comment by JoshLove-msft** [comment]
Can this be investigated for March?

**Comment by JoshLove-msft** [comment]
ping

**Comment by JoshLove-msft** [comment]
Closing as this was implemented by making the data derive from RequestContent - https://github.com/Azure/azure-sdk-for-net/pull/18959
