### ISSUE TITLE
NamespaceOperations.UpdateAuthorizationRule not including SecondaryKey

### ISSUE THREAD

**Issue by morandy** [Azure/azure-sdk-for-net#1553]
When trying to use `NamespaceOperations.UpdateAuthorizationRule` to update a `ServiceBusSharedAccessAuthorizationRule`, it does not handle the `SecondaryKey`. 

The response then comes back with its `SecondaryKey` set to `NULL` -- and causes the secondary key to be lost, as can be seen on the management portal:

    manage.windowsazure.com/@USERNAME#Workspaces/ServiceBusExtension/Namespace/QUEUENAME

Ideally, the fix to this would be to add to `NamespaceOperations.UpdateAuthorizationRule` a section in order to handle the `SecondaryKey` : 

	if (rule.SecondaryKey != null)
	{
		XElement secondaryKeyElement = new XElement(XName.Get("SecondaryKey", "http://schemas.microsoft.com/netservices/2010/10/servicebus/connect"));
		secondaryKeyElement.Value = rule.SecondaryKey;
		sharedAccessAuthorizationRuleElement.Add(secondaryKeyElement);
	}

Thank you,
Andy M.

**Comment by hovsepm** [comment]
Published. Please use Microsoft.WindowsAzure.Management.ServiceBus version 0.18.0-preview
