### ISSUE TITLE
[EventHub] How to force the EventProcessorClient to receive messages from every partition

### ISSUE THREAD

**Issue by evgkar** [Azure/azure-sdk-for-net#15556]
**Query/Question**
I have an Event Hub with 2 partitions. The problem is that the EventProcessorClient when started is listening to only one partition. Is there an option to specify the partition to the client? Or maybe tell it to read messages from all partition? Or maybe some different approach could be used.

There's a code of a sample program to consume data:

```cs
using System;
using System.Text;
using System.Threading.Tasks;
using Azure.Storage.Blobs;
using Azure.Messaging.EventHubs;
using Azure.Messaging.EventHubs.Consumer;
using Azure.Messaging.EventHubs.Processor;

namespace EventHubReader
{
    class Program
    {
        static async Task Main()
        {
            var eventHubConnectionString = "event-hub-connection-string";
            var storageConnectionString = "storage-connection-string";

            var eventHubName = "eventhubname";
            var storageContainerName = "storagecontainername";

            var client = new EventProcessorClient(
                new BlobContainerClient(storageConnectionString, storageContainerName),
                EventHubConsumerClient.DefaultConsumerGroupName,
                eventHubConnectionString,
                eventHubName);

            client.ProcessEventAsync += OnProcessEventAsync;
            client.ProcessErrorAsync += OnProcessErrorAsync;
            client.PartitionInitializingAsync += args =>
            {
                Console.WriteLine($"Initializing partition '{args.PartitionId}'");
                return Task.CompletedTask;
            };

            await client.StartProcessingAsync();
            Console.ReadKey();
        }

        private static Task OnProcessEventAsync(ProcessEventArgs arg)
        {
            if (!arg.HasEvent)
            {
                Console.WriteLine($"{nameof(OnProcessEventAsync)} was called without event");
                return Task.CompletedTask;
            }

            arg.UpdateCheckpointAsync();
            var message = Encoding.Default.GetString(arg.Data.Body.ToArray());
            Console.WriteLine($"[Thread: {Environment.CurrentManagedThreadId}; Partition: {arg.Partition.PartitionId}] [{DateTimeOffset.Now}] Checkpoint updated for '{message}'");
            return Task.CompletedTask;
        }

        private static Task OnProcessErrorAsync(ProcessErrorEventArgs arg)
        {
            Console.WriteLine($"[{DateTimeOffset.Now}] Error: {arg.Exception}");
            return Task.CompletedTask;
        }
    }
}
```

As I've mentioned, it starts to listen to only one of two partitions. I've added the second EventProcessorClient and interestingly sometimes it worked well :) I have no idea how they negotiate not to listen to the same partition.

**Environment:**
 - Packages: Azure.Messaging.EventHubs 5.2.0, Azure.Messaging.EventHubs.Processor 5.2.0
 - OS: Windows 10 Pro Version 2004, 
 - Framework: .Net Framework 4.7.2
 - IDE: Visual Studio Professional 2019 Version 16.7.2

**Comment by jsquire** [comment]
Hi @evgkar.  Thank you for reaching out, and we regret that you're experiencing difficulties.   I appreciate the detailed code snippet; that's very helpful to set the context for discussion.   

When a single `EventProcessorClient` is used for an Event Hub, it will always take take ownership of all available partitions.  Because it is not aware that it is the only processor, it will still assume that it is load balancing and take ownership in cycles, to ensure that it does not unnecessarily battle other processors.  By default, a load balancing cycle runs every 10 seconds.  With two partitions, allowing for startup overhead,  you should see the processor hit a balanced state in roughly 30-45 seconds.  

There's a few things that we can consider to dig in and troubleshoot, but I'd like to start with the basics to try and rule them out.  Can you help me understand why you don't believe that your processor has ownership of both partitions?  Is it safe to assume that you're keying on the console logging from the initialization handler?   Some things that would be helpful to understand:

- How long was the processor running before you made the observation?

- How long between runs have to waited to make the observations?

- Are you sure that events have been published to both partitions?

- Are you sure that there are no other readers active for the default consumer group?  This may not be a processor, it could be an `EventHubConsumerClient` in some configurations.

- Do you see a different partition selected each time or are you consistently seeing the same partition trigger your initialize?

> I have no idea how they negotiate not to listen to the same partition.

When multiple `EventProcessorClients` are configured to read from the same Event Hub and Consumer Group pair, they coordinate via Blob Storage in a competing consumer fashion.

**Comment by evgkar** [comment]
@jsquire thank you very much for such a detailed response. Seems that It was my issue and another consumer on a remote machine (which I completely forgot) was reading another partition :) I've reproduced this experiment several times and it gives me a predictable result even with one `EventProcessorClient`. Here's the sample log of the message consumer program:
```
[08.10.2020 18:56:46 +03:00] Initializing partition '0'
[08.10.2020 18:57:05 +03:00] Initializing partition '1'
[Thread: 3; Partition: 0] [08.10.2020 18:57:20 +03:00] Checkpoint updated for 'First event: a12026bc-6b25-4eab-95d7-14e8fe0c2ab8'
[Thread: 3; Partition: 0] [08.10.2020 18:57:20 +03:00] Checkpoint updated for 'Second event: 898648a2-ee84-44ba-80e6-ed446d048fd7'
[Thread: 3; Partition: 0] [08.10.2020 18:57:20 +03:00] Checkpoint updated for 'Third event: 5c6ee728-9aa6-4d62-9a6a-984498b1b1fd'
[Thread: 3; Partition: 1] [08.10.2020 18:57:21 +03:00] Checkpoint updated for 'First event: b40b5ec4-856c-4014-b2d5-d20b6972ae0c'
[Thread: 3; Partition: 1] [08.10.2020 18:57:21 +03:00] Checkpoint updated for 'Second event: ac1917c4-e708-4395-a283-aa7641fee48f'
[Thread: 3; Partition: 1] [08.10.2020 18:57:21 +03:00] Checkpoint updated for 'Third event: 665bd400-5e25-4f50-94d3-f951edad82ba'
[Thread: 3; Partition: 1] [08.10.2020 18:57:23 +03:00] Checkpoint updated for 'First event: a504ca85-2777-4e77-a2c8-91e1d8fe4ddb'
[Thread: 3; Partition: 1] [08.10.2020 18:57:23 +03:00] Checkpoint updated for 'Second event: 731cc50c-712f-41a6-ba17-bd8d972f7f10'
[Thread: 3; Partition: 1] [08.10.2020 18:57:23 +03:00] Checkpoint updated for 'Third event: cd9500cb-5881-41bf-9690-3a067938577a'
[Thread: 12; Partition: 0] [08.10.2020 18:57:24 +03:00] Checkpoint updated for 'First event: f61f1170-c823-4d92-9b85-24f66c36dc8d'
[Thread: 12; Partition: 0] [08.10.2020 18:57:24 +03:00] Checkpoint updated for 'Second event: aa05ce02-4778-449c-8fbf-acbf0af5c044'
[Thread: 12; Partition: 0] [08.10.2020 18:57:24 +03:00] Checkpoint updated for 'Third event: 4f858554-d02e-4857-864f-af251aa13bfa'
[Thread: 3; Partition: 1] [08.10.2020 18:57:26 +03:00] Checkpoint updated for 'First event: bcfed5c4-7239-4eda-9bb9-9207d9cf87be'
[Thread: 3; Partition: 1] [08.10.2020 18:57:26 +03:00] Checkpoint updated for 'Second event: d4e75100-39ad-456c-b2ac-4eea298ee07f'
[Thread: 3; Partition: 1] [08.10.2020 18:57:26 +03:00] Checkpoint updated for 'Third event: 2f259b69-4c9d-4f5d-acd2-95ffcd74d8f4'
[Thread: 3; Partition: 0] [08.10.2020 18:57:27 +03:00] Checkpoint updated for 'First event: 200732e3-37d5-46ee-ba0c-c6fec36ae74f'
[Thread: 3; Partition: 0] [08.10.2020 18:57:27 +03:00] Checkpoint updated for 'Second event: 5329c42e-3a96-4e53-be47-386e5fad35be'
[Thread: 3; Partition: 0] [08.10.2020 18:57:27 +03:00] Checkpoint updated for 'Third event: c9a728e2-aba6-4b4e-bc33-477e2f918bd0'
[Thread: 4; Partition: 1] [08.10.2020 18:57:28 +03:00] Checkpoint updated for 'First event: 9fe22e6a-3d3e-4e56-bb2c-ca1d9ab554b8'
[Thread: 4; Partition: 1] [08.10.2020 18:57:28 +03:00] Checkpoint updated for 'Second event: 908af5a5-4bba-435c-8f90-0ac86f884e22'
[Thread: 4; Partition: 1] [08.10.2020 18:57:28 +03:00] Checkpoint updated for 'Third event: 4c828e64-0432-445e-8730-7275af6f7dc7'
[Thread: 3; Partition: 1] [08.10.2020 18:57:30 +03:00] Checkpoint updated for 'First event: 75ea0463-a90d-4072-a3a9-db2c3e6e37f3'
[Thread: 3; Partition: 1] [08.10.2020 18:57:30 +03:00] Checkpoint updated for 'Second event: 6e96899d-030c-41db-96ed-65c25cf8c02a'
[Thread: 3; Partition: 1] [08.10.2020 18:57:30 +03:00] Checkpoint updated for 'Third event: c28375a9-fa27-45ed-bcf2-64800c29b97f'
[Thread: 4; Partition: 1] [08.10.2020 18:57:31 +03:00] Checkpoint updated for 'First event: d95b8d0e-d1cb-4cb6-aba2-c1f6cde79e4d'
[Thread: 4; Partition: 1] [08.10.2020 18:57:31 +03:00] Checkpoint updated for 'Second event: 1b8d567e-09b3-4d1f-bab4-8754bc5926ed'
[Thread: 4; Partition: 1] [08.10.2020 18:57:31 +03:00] Checkpoint updated for 'Third event: 20aaf5aa-16ec-4b11-aa8b-3efb9217f877'
[Thread: 3; Partition: 1] [08.10.2020 18:57:32 +03:00] Checkpoint updated for 'First event: 24a16c9b-293b-4d3c-9246-395fe5d59bcd'
[Thread: 3; Partition: 1] [08.10.2020 18:57:32 +03:00] Checkpoint updated for 'Second event: 95b7baa7-3f16-4e32-9894-87f7fc1c6e68'
[Thread: 3; Partition: 1] [08.10.2020 18:57:32 +03:00] Checkpoint updated for 'Third event: 6244dd4c-3caf-4d43-9a89-dd7049fcbc52'
[Thread: 9; Partition: 0] [08.10.2020 18:57:34 +03:00] Checkpoint updated for 'First event: c669b027-09cc-4c94-8141-b83a26c23516'
[Thread: 9; Partition: 0] [08.10.2020 18:57:34 +03:00] Checkpoint updated for 'Second event: 8a1d1b62-0aaf-4be5-8ce7-088e3f4421dc'
[Thread: 9; Partition: 0] [08.10.2020 18:57:34 +03:00] Checkpoint updated for 'Third event: 81cb1031-f0bb-432e-baef-30463b00e7db'
[Thread: 9; Partition: 0] [08.10.2020 18:57:35 +03:00] Checkpoint updated for 'First event: 727f75de-275b-409e-9241-d4ab50b24ad5'
[Thread: 9; Partition: 0] [08.10.2020 18:57:35 +03:00] Checkpoint updated for 'Second event: c9c52ee4-3ea5-4002-9534-a326e3413635'
[Thread: 9; Partition: 0] [08.10.2020 18:57:35 +03:00] Checkpoint updated for 'Third event: fccba642-5c22-4140-80d4-a2b5ecb8d02b'
[Thread: 3; Partition: 0] [08.10.2020 18:57:37 +03:00] Checkpoint updated for 'First event: 488d271a-b994-4eab-9f91-208ad0dfe737'
[Thread: 3; Partition: 0] [08.10.2020 18:57:37 +03:00] Checkpoint updated for 'Second event: b41cf951-28eb-4e7a-afab-568f75548086'
[Thread: 3; Partition: 0] [08.10.2020 18:57:37 +03:00] Checkpoint updated for 'Third event: 4eba1d7d-41f4-4d9b-8609-1077443191f0'
```
So it seems to me that only one client is enough to process several partitions simultaneously. Am I right? Or if let's say I'd decide to wait in the `OnProcessEventAsync` event handler when a message from `partition 0` was received, would it continue receiving messages from the `partition 1`? Or it's better to use so many `EventProcessorClients` as many partitions I have?
Thanks!

**Comment by jsquire** [comment]
Hi @evgkar.   It's a bit difficult to give general advice around the number of processor clients without a much deeper understanding of the application scenarios and the eventing patterns.    I'm happy to help as I'm able, but we may need to dig into more detail.

Generally speaking, it's appropriate to use a single processor if your application is satisfied by the amount of throughput;  the closer to a 1:1 ratio between processors and partitions, the less work each processor will have to do and that may (or may not) improve throughput in your scenario - but it would likely be a trade-off with additional cost for hosting.   At a high level, if you're not seeing resource contention at the CPU, network, or storage levels on your host machine and the throughput is reasonable,  you're probably just fine.

With respect to your event handler, the guarantee is that the processor will call it once per-partition concurrently.   So, if you have 4 partitions, your handler can be invoked 4 times concurrently - once for each partition.   However, to ensure that the order of events is preserved, the processor will wait for the handler to complete before dispatching another event for a partition.   So, if your handler for partition "0" takes 30 seconds,  you won't see another event for partition "0" until after that time.

**Comment by evgkar** [comment]
Hi @jsquire. Thanks for your comments. 
I'll try to describe my scenario (and try to simplify it as well). 

1. Let's say every message has a `Subject` and `Timestamp` (some time in the future) fields. 
2. The `Timestamp` of the next message in a sequence is greater, comparing to the previous one.
3. The component which sends messages to the Event Hub looks at the subject and makes a decision basing on its value to which partition should this message be sent. It adds `Subject` and `Timestamp` to the `EventData.Properties` collection.
4. It creates a batch of messages and sends it to the Event Hub.
5. The receiver (based on the `EventProcessorClient`) is waiting for messages. When the event handler is invoked it looks at the `Timestamp` value: if the current time is less than the timestamp's value, then it waits for this delta.

> but it would likely be a trade-off with additional cost for hosting

Is that because of several threads processing concurrently processing the data?

> So, if your handler for partition "0" takes 30 seconds, you won't see another event for partition "0" until after that time.

Sounds good - that's the desired behaviour :)

**Comment by jsquire** [comment]
I'd be very, very careful when considering timestamps as any type of decision criteria; even a single machine can have issues with clock skew.   In this case you're describing at least two machines, which increases the risk.  Adding more processors here would further increase that risk.   

>>  but it would likely be a trade-off with additional cost for hosting

> Is that because of several threads processing concurrently processing the data?

In this case, I'm thinking in terms of additional machines to host.  The processor runs most of its work in the background using the .NET thread pool and uses a dedicated connection for each partition that it owns.   If you're network-bound, using more processors wouldn't provide any benefit.  If you're CPU-bound, using more processors on the same machine would be likely to increase contention and cause more context switches.  Without profiling, it's not possible to say for sure, but I suspect that you would see lower throughput in that case.

**Comment by evgkar** [comment]
@jsquire thank you for the very useful information that you've provided!
