### ISSUE TITLE
[FEATURE REQ] App Insights / Log Analytics SDK major version

### ISSUE THREAD

**Issue by BastienPerdriau** [Azure/azure-sdk-for-net#15558]
**Library or service name.**
[Microsoft.Azure.ApplicationInsights](https://www.nuget.org/packages/Microsoft.Azure.ApplicationInsights)
[Microsoft.Azure.OperationalInsights](https://www.nuget.org/packages/Microsoft.Azure.OperationalInsights)
 
**Is your feature request related to a problem? Please describe.**
Is it planned to release a major version for these packages ?

We have a good use of these but because of only having preview versions, it is a mess for our internal library versioning.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//cc: @nonik0

**Comment by BastienPerdriau** [comment]
Hi @jsquire @nonik0 , do you have any news ?
I also saw that there was a Microsoft.Azure.ApplicationInsights.Query package with maybe some updates, and maybe an upcoming major version (with preview at least).
Didn't see anything about new package (or version) for Microsoft.Azure.OperationalInsights package.

If needed, I could see to submit a PR for these versions ?

**Comment by jsquire** [comment]
@geneh - Do you have any insight that you can share?

**Comment by geneh** [comment]
[Microsoft.Azure.ApplicationInsights.Query](https://www.nuget.org/packages/Microsoft.Azure.ApplicationInsights.Query) should be used instead of Microsoft.Azure.ApplicationInsights which is going to be deprecated.
There is no plan to release 1.x versions but non-preview versions can be released, for example 0.9.1. Would that help?

**Comment by BastienPerdriau** [comment]
Non-preview releases would be great yes !

Is there any plan concerning Microsoft.Azure.OperationalInsights package to have a non-preview release ?

**Comment by geneh** [comment]
> Is there any plan concerning Microsoft.Azure.OperationalInsights package to have a non-preview release ?

Yes, non-preview versions are going to be released for both.

**Comment by BastienPerdriau** [comment]
Well, that's good news !

May I ask if there is an ETA ?
