### ISSUE TITLE
Add Start/Stop/properties.PowerState to ManagedClusters

### ISSUE THREAD

**Issue by mwhouser** [Azure/azure-sdk-for-net#15559]
**Library or service name:**

Microsoft.Azure.Management.ContainerService
 
**Description:**

The API docs for ManagedClusters include the following:

* starting: https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/start
* stopping: https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/stop
* a `properties.PowerState` property, indicating the running/stopped state of the cluster: https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/get#managedcluster

Please add methods to start & stop clusters, and add and populate the `properties.PowerState` property in the `Microsoft.Azure.Management.ContainerService.Models.ManagedCluster` class.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mwhouser** [comment]
Just wondering if this will see the light of day anytime soon. I would really like to be able to start & stop AKS clusters via SDK.
