### ISSUE TITLE
[BUG] GetBlobs() with Tags

### ISSUE THREAD

**Issue by jascunce** [Azure/azure-sdk-for-net#15560]
Trying to use container.GetBlobs(traits: BlobTraits.Tags) returns an exception with ErrorCode "InvalidQueryParameterValue" and the following message:

`"Value for one of the query parameters specified in the request URI is invalid.\nRequestId:d34072b8-b01e-00b8-773e-972530000000\nTime:2020-09-30T15:27:25.1832677Z\r\nStatus: 400 (Value for one of the query parameters specified in the request URI is invalid.)\r\nErrorCode: InvalidQueryParameterValue\r\n\r\nHeaders:\r\nServer: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: d34072b8-b01e-00b8-773e-972530000000\r\nx-ms-client-request-id: bdde9af4-d616-40f1-b6a1-f0a13c7e341c\r\nx-ms-version: 2019-12-12\r\nx-ms-error-code: InvalidQueryParameterValue\r\nDate: Wed, 30 Sep 2020 15:27:24 GMT\r\nContent-Length: 415\r\nContent-Type: application/xml\r\n
`
Using container.GetBlobs() in the same piece of code works, but you get the Tags as an null Dictionary.

**To Reproduce**

1. await foreach (BlobItem blob in container.GetBlobsAsync(traits: BlobTraits.Tags)) Returns Exception.
2. await foreach (BlobItem blob in container.GetBlobsAsync()) Works as expected.

````
public async List<BlobItem> Search(string input)
        {
            BlobContainerClient container = new BlobContainerClient(_conString, input);
            BlobFiles results = new List<BlobItem>;
            try
            {
                if (container.Exists())
                {
                    await foreach (BlobItem blob in container.GetBlobsAsync(traits: BlobTraits.Tags))
                    {
                        results.Add(bf);
                    }
                }
                return results;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return results;
            }
        }
````

**Environment:**
 - Azure.Storage.Blobs 12.6.0
 - IIS Express, .NET Core 3.1
 - Visual Studio Community 2019 16.7.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

I was unable to reproduce your error with the snippet you provided. I also tried a variation but I was not able to get the error you are seeing. If possible could you either get the request trace on what you are sending to the service(i.e. Fiddler trace)
or could you enable logging and send us the logs for this error (https://docs.microsoft.com/en-us/dotnet/azure/logging)?
 i.e. add this early in Main method:
```
            using AzureEventSourceListener listener = new AzureEventSourceListener((e, message) =>
            {
                // Only log messages from Azure-Core event source
                if (e.EventSource.Name == "Azure-Core")
                {
                    File.AppendAllText("C:\\log.txt", $"{DateTime.Now} {message}");
                }
            },
             level: EventLevel.Verbose);
```
This will generate C:\log.txt file. Then please send us the log.

**Comment by seanmcc-msft** [comment]
Hi @jascunce,

What region is your storage account located in?  I believe the issue is that Blob Tags is only available as a public preview in Canada Central, Canada East, France Central, and France South.  https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal#regional-availability-and-storage-account-support

If you would like to use Blob Tags, please create a storage account in one of those regions, and follow the directions in that document to enable Blob Tags for your Azure subscription.  This feature will GA in all regions sometime in the next few months.

-Sean

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
