### ISSUE TITLE
Emit more actionable information in exceptions messages during deserialization

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#15589]
Recently I [fixed](#15240) a [bug](#15108) in Search since swagger wasn't authored properly with `x-nullable: true`. But the exception message wasn't helpful:

> An unhandled exception of type 'System.ArgumentNullException' occurred in System.Private.CoreLib.dll: 'Value cannot be null.'
at Azure.Search.Documents.Indexes.Models.EntityRecognitionSkillLanguage..ctor(String value) at Azure.Search.Documents.Indexes.Models.EntityRecognitionSkill.DeserializeEntityRecognitionSkill(JsonElement element) at Azure.Search.Documents.Indexes.Models.SearchIndexerSkill.DeserializeSearchIndexerSkill(JsonElement element) at Azure.Search.Documents.Indexes.Models.SearchIndexerSkillset.DeserializeSearchIndexerSkillset(JsonElement element) at Azure.Search.Documents.SkillsetsRestClient.Create(SearchIndexerSkillset skillset, CancellationToken cancellationToken) at Azure.Search.Documents.Indexes.SearchIndexerClient.CreateSkillset(SearchIndexerSkillset skillset, CancellationToken cancellationToken)

Instead of just allowing exceptions during deserialization to fall through, perhaps we should catch them and throw a more useful exception along with the current JSONPath, ideally (like exceptions from `System.Text.Json.JsonConverter<T>`), and the original exception as an `InnerException`. We could even include the original exception message, but the idea being any exception during deserialization currently may not make it obvious to the user there was something wrong with the data. In this case, the `ArgumentException` is mentioning a parameter that probably has nothing to do with the code the called.

**Comment by pakrym** [comment]
Is the new exception more actionable for customers?

**Comment by heaths** [comment]
Perhaps "actionable" isn't exactly the right word here, but "informative". If we do calculate the JSONPath for example, we can at least tell them what data is corrupt or unexpected rather than something like an `ArgumentException` that is specific to internal implementation they wouldn't even know about. So rather than "Value cannot be null" (what value?), it could say something like (off the cuff) "JSON value $.values[42].prop1 cannot be null". At least this way they know what is corrupt / unexpected, and we have an easier time figuring out that the handler for "prop1" might have a bug.

**Comment by pakrym** [comment]
I don't see how we would implement that. This exception is not thrown by deserializer itself but from model constructor that doesn't know anything about serialization. At the same time, deserializer doesn't know why the model construction failed.

**Comment by heaths** [comment]
It doesn't have to. Any exception thrown while deserializing could be wrapped and rethrown as an inner exception. Any exception during deserialization impacts deserialization, of course, so it seems completely acceptable that it's a problem with deserialization, albeit indirectly. A more informative error message would better help diagnose the issue.

**Comment by pakrym** [comment]
I was talking about this example: `JSON value $.values[42].prop1 cannot be null`

**Comment by heaths** [comment]
As I mentioned, that was off the cuff. It certainly could be better. But even that does a better job at referencing *which* data is bad/unexpected.

**Comment by pakrym** [comment]
How would the deserializer know why the model is throwing?

**Comment by heaths** [comment]
It doesn't need to know why. At an abstract level, an error still occurred while deserializing, so it's a deserialization error. Wrap the exception as an inner exception and throw a deserialization error.

**Comment by AlexGhiondea** [comment]
This is a nice to have, but we don't have a good way to do it. Closing for now.
