### ISSUE TITLE
Enable SDK Automation for new code generator

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#15585]
The SDK Automation spec can be found at https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/sdkautomation/sdk_customization.md. 

- [x] Add [automation configuration](https://github.com/Azure/azure-rest-api-specs/blob/master/specificationRepositoryConfiguration.json) for new code generator in the specs repo 
- [x] Add new swagger_to_sdk configuration file in the language repo
- [x] Add generate script (./eng/scripts/generate_sdk) that will implement the [sdk automations spec](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/sdkautomation/sdk_customization.md).

**Comment by PhoenixHe-msft** [comment]
Hi @weshaggard @pakrym any update on this workitem? I'll make SDK Automation available on test env early next week.

**Comment by ShivangiReja** [comment]
Track-2 SDK automation is enabled for c#. For more details check- https://github.com/Azure/azure-sdk-for-net/pull/17193

**Comment by ShivangiReja** [comment]
>Add automation configuration for new code generator in the specs repo

[Here](https://github.com/Azure/azure-rest-api-specs/pull/12169/files) we have added automation configuration in `Azure/azure-rest-api-specs` repo.

**Comment by weshaggard** [comment]
@ShivangiReja have any serviced enabled the new generation in the specs repo? I'd like to make sure we have some documentation to point folks at that want to enable that automation and if we don't already we should have an issue (or set of issues) tracking enabling this for those servcies.

cc @AlexGhiondea

**Comment by ShivangiReja** [comment]
I'm planning to enable track-2 sdk automation for all the services. If the service is new or the sdk doesn't exists in azure-sdk-for-net repo, it won't affect anything. It will only generate code for existing swagger updates.

**Comment by PhoenixHe-msft** [comment]
Basically, you need to add "azure-sdk-for-net-track2" under the swagger-to-sdk section for all the readme.md. Do you think you want to have an option in sdk automation to enable it for all the readme.md?

**Comment by ShivangiReja** [comment]
>Basically, you need to add "azure-sdk-for-net-track2" under the swagger-to-sdk section for all the readme.md

Yes, we need to add "azure-sdk-for-net-track2" in all the readme.md files in order to enable track-2 SDK automation.

>Do you think you want to have an option in sdk automation to enable it for all the readme.md?

That would be great but how are you planning to provide that option?

**Comment by weshaggard** [comment]
@ShivangiReja do you have an issue tracking that work that I can reference? If not can you please create one and we can discuss that plan there?

Also before we start putting the name "azure-sdk-for-net-track2" in a bunch of readme's I'd like to explore a couple options for renaming that first. I left some a comment at https://github.com/Azure/azure-rest-api-specs/pull/12169/files#r558531220.

**Comment by ShivangiReja** [comment]
@weshaggard Created an issue [here](https://github.com/Azure/azure-sdk-for-net/issues/18012) to track this.
