### ISSUE TITLE
Event Hubs:  Reformat Migration Guide

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#15586]
# Summary

The Event Hubs migration guide was written to be a launching point to guide developers familiar with the legacy client library to the equivalent API and patterns of the modern library.  While the content has well received, the format has proven to harm readability and cause difficulty in finding the appropriate content.   When developing the Service Bus migration guide, an alternate format was introduced, which addressed many of the pain points from the Event Hubs efforts.

# Scope of Work

- Revise the format of the Event Hubs migration guide, using the Service Bus migration guide as an example while retaining (or making minor improvements to) the quality of the content.

# Success Criteria

-  The Event Hubs migration guide has been reformatted, using the Service Bus guide as a target.   Where reasonable, the Event Hubs and Service Bus migration guides in .NET should align in format, organization, and categories of content.

- The revisions have been shared within the Event Hubs feature team for feedback;  any tweaks or iterations to the design have been captured and the guide has been updated.

# References

- [Event Hubs Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md)
- [Service Bus Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md)

**Comment by ramya-rao-a** [comment]
Please use the template in this [PR that adds the migration guide to our policies](https://github.com/Azure/azure-sdk/pull/2132)
