### ISSUE TITLE
SearchIndexClient.GetIndexNames throws

### ISSUE THREAD

**Issue by bleroy** [Azure/azure-sdk-for-net#15590]
**Describe the bug**
Calling `SearchIndexClient.GetIndexNames` throws an `ArgumentNullException` with the message "Fields cannot be null. To clear values, call Clear. (Parameter 'value')".

**Expected behavior**
The method should return the list of index names.

**Actual behavior (include Exception or Stack Trace)**
Calling `SearchIndexClient.GetIndexNames` throws an `ArgumentNullException` with the message "Fields cannot be null. To clear values, call Clear. (Parameter 'value')".

The reason this is happening is that `GetIndexNames` calls `IndexesClient.List` with `Constants.NameKey`, which results in a JSON document missing all properties except for the name of the index. Attempting to deserialize this then fails because `fields` are required, and are missing (despite definitely existing on the actual indexes) in the JSON getting passed in.

The implementation of `GetIndexNames` and `GetIndexNamesAsync` should either use a different new method on the `IndexerRestClient` that doesn't attempt to deserialize indexes but just extracts the name that are needed, or should Constants.All before it does the deserialization like `GetIndexes` does.

**Workaround**
Use `SearchIndexClient.GetIndexes(serviceName, credentials).Select(idx => idx.Name)` instead.

**To Reproduce**
Call `SearchIndexClient.GetIndexNames`.

**Environment:**
 - Name and version of the Library package used: Azure.Search.Documents 11.1.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET Core 3.1
 - IDE and version : Visual Studio 16.8.0 Preview 3.2

**Comment by heaths** [comment]
Since we're close to code complete and I have another issue I'm working on, I'm moving this to November. If we need this for October 6th, please let me know ASAP.
