### ISSUE TITLE
[BUG] IVirtualMachineScaleSetVMsOperations.ListAsync doesn't allow expands, but REST API does

### ISSUE THREAD

**Issue by j-rewerts** [Azure/azure-sdk-for-net#15597]
Apologies if this is a feature request and not a bug. Just thought it may have been an oversight.

Using the REST API, it's possible to supply expands to Virtual Machine Scale Set VMs - List ([link](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachinescalesetvms/list)). The dotnet SDK only allows for filter (using ODataQuery) and select ([link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.virtualmachinescalesetvmsoperationsextensions.list?view=azure-dotnet#parameters)). Also related, but the select lists instanceView as the only valid option, but instanceView needs to be expanded, which isn't possible when using ListAsync.

**Environment:**
Microsoft.Azure.Management.Compute Version="38.0.0"
Dotnet Core 3.1.301

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Drewm3** [comment]
@jaylabell, could you please work with @bilaakpan-ms to determine if this request can be done by the compute .NET SDK team, or if this is something that needs support from the general Azure .NET SDK team to support. Also, please update the flag on this to clarify if this is a bug or if this is a feature request.

**Comment by jaylabell** [comment]
This bug has been added to our backlog, and will pick up soon when we have more bandwidth. More updates soon to come!
