### ISSUE TITLE
[BUG] Add(Blob/File)ServiceClient() is exposed on all types

### ISSUE THREAD

**Issue by frankhaugen** [Azure/azure-sdk-for-net#15608]
**Describe the bug**
Regardless of type, the Add(Blob/File)ServiceClient() is exposed:
![image](https://user-images.githubusercontent.com/13543585/94784303-4161b200-03ce-11eb-81d9-3df586167b4c.png)

**Expected behavior**
Only available for sensible types

**Actual behavior (include Exception or Stack Trace)**
Available for any type

**To Reproduce**
1. Have only the following packages added to a project:
![image](https://user-images.githubusercontent.com/13543585/94784563-a1f0ef00-03ce-11eb-9b34-365e1ebc3e3d.png)
2. Go to any place in a method the write "new List<string>()."
3. Hit your hotkey for exposing intellisense if it's not showing automagically
4. Start typing "Add" and see that intellisense shows the "Add(Blob/File)ServiceClient()" in the list of suggestions

**Environment:**
| Libraries | OS | .net | IDE |
| --- | --- | --- | --- |
| Azure.Storage.Blobs 12.4.0, Azure.Storage.Files.Shares 12.4.0 | Windows 10 | Core 3.1/standard 2.1 | Visual Studio 16.7.3 |

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Duplicate: https://github.com/dotnet/roslyn/issues/39689

**Comment by frankhaugen** [comment]
@pakrym now that the 'duplicate' is closed as 'by design', this is then a valid issue

**Comment by jsquire** [comment]
@pakrym:  Given the resolution of the duplicate, I'm in agreement with @frankhaugen that we should reevaluate.  Reopening for consideration.

**Comment by frankhaugen** [comment]
@pakrym I believe the issue is that "TClient" has no constraints here, (https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core/src/Extensions):

```C#
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

namespace Azure.Core.Extensions
{
#pragma warning disable CA1040 // Avoid empty interfaces
    /// <summary>
    /// Marks the type exposing client registration options for clients registered with <see cref="IAzureClientFactoryBuilder"/>.
    /// </summary>
    /// <typeparam name="TClient">The type of the client.</typeparam>
    /// <typeparam name="TOptions">The options type used by the client.</typeparam>
    public interface IAzureClientBuilder<TClient, TOptions> where TOptions : class
#pragma warning restore CA1040 // Avoid empty interfaces
    {
    }
}
```

I would suggest that there are added an empty abstract base class for clients to implement, and set the constraint based on that, because it should be constrained.

I'll fork and raise a PR later with the changes I suggest

**Comment by pakrym** [comment]
Yep, working on it. I'm trying to convince folks that this is not by design.

**Comment by pakrym** [comment]
>@pakrym I believe the issue is that "TClient" has no constraints here, (https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/Azure.Core/src/Extensions):

There is no constraint we can put on in that would work.

**Comment by pakrym** [comment]
We are back on track with this being a dup of a compiler issue.
