### ISSUE TITLE
[FEATURE REQ] Add TryGetSecret to the KeyVault SDK

### ISSUE THREAD

**Issue by andrewtsw** [Azure/azure-sdk-for-net#15600]
**Libraries:**
Azure.Security.KeyVault.Secrets
Azure.Security.KeyVault.Keys
Azure.Security.KeyVault.Certificates

When I want to get a secret from the Azure KeyVault secrets I can use these .NET client methods
Sync: https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.secrets.secretclient.getsecret?view=azure-dotnet
Async: https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.secrets.secretclient.getsecretasync?view=azure-dotnet
These methods work fine. But they throw a RequestFailedException when a secret with the specified name is not found.
I believe it is a very useful scenario to check if a secret exists without an exception.
For example, I want to add a confirmation before changing the value for existing secret -  "Are you sure you want to override it"?

I use a following code for now
```cs
public static async Task<Result<KeyVaultSecret>> TryGetSecretAsync(this SecretClient secretClient, string name)
{
	try
	{
		var secret = await secretClient.GetSecretAsync(name);
		return Result<KeyVaultSecret>.Ok(secret.Value);
	}
	catch (RequestFailedException ex)
	{
		if (ex.Status == 404)
		{
			return Result<KeyVaultSecret>.NotFound();
		}
		throw;
	}
}
```
 I believe this extension will be useful for other users of the KeyVault SDK.

Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
You can check if resources exist using methods like `SecretClient.GetPropertiesOfSecretsAsync`. Does that work for you? It merely requires the "list" permission. Attempting to get a specific resource requires the "get" permission, which may not be as pervasive as "list" depending on your configured access control.

**Comment by andrewtsw** [comment]
@heaths thanks for your answer!
Yes, this task can be solved in this way. In the same way as in Azure CLI.
But I believe it is more efficient to use a single API call. And I do not need "List" permission for this scenario.
Just like `int.TryParse` method. I need a flag - exists or not. And if a secret/key/certificate exists - it info.
But it is just a suggestion to client API.

**Comment by heaths** [comment]
We will discuss and consider this. If your principal does not have "list" permissions, hopefully your extension method is not needed often. Exceptions for code flow is poor form of course, but it's in tight loops that we have seen performance really get bogged down.

**Comment by heaths** [comment]
After some discussion, we've decided not to provide Try-style client methods. While using exceptions for code flow is not recommended, getting a resource without knowing if it exists should be uncommon enough that adding Try-style client methods to any GET requests is not the design approach we want to take at this time.
