### ISSUE TITLE
[BUG] `ODataQuery` incorrectly adds quotes to dates when building the query from an expression

### ISSUE THREAD

**Issue by TomBonnerAtTFL** [Azure/azure-sdk-for-net#15614]
Either `ODataQuery` incorrectly adds quotes to dates when building the query from an expression, or API-M cannot handle quoted date-values in it's queries.

The result of `ToString()` for the following two values should be identical, but instead the variable `queryFromExpression` add quotes and encodes the values. The encoding of values isn't the problem, but the addition of quotes causing API-M to throw an exception. For context, this is when we are making Report requests from Azure API-M.

```csharp
var start = (DateTime.UtcNow - TimeSpan.FromDays(1));
var end = (DateTime.UtcNow - TimeSpan.FromSeconds(1));

var queryFromExpression = new ODataQuery<RequestReportRecordContract>(i => i.Timestamp >= start && i.Timestamp <= end);
var queryFromString = new ODataQuery<RequestReportRecordContract>($"timestamp ge {start:o} and timestamp le {end:o}");
```

**Expected behavior**
```csharp
new ODataQuery<RequestReportRecordContract>(i => i.Timestamp >= start && i.Timestamp <= end).ToString()
```
should equal
```
$filter=timestamp ge 2020-09-30T16:47:41.9064247Z and timestamp le 2020-10-01T16:47:40.9064355Z
```
This is based upon what the Azure Portal makes as a request when you use the Analytics component within Azure API-M.

**Actual behavior (include Exception or Stack Trace)**
Instead 
```csharp
new ODataQuery<RequestReportRecordContract>(i => i.Timestamp >= start && i.Timestamp <= end).ToString()
``` 
equals
```
$filter=timestamp ge '2020-09-30T16%3A47%3A41Z' and timestamp le '2020-10-01T16%3A47%3A40Z'
```
which leads to the `Microsoft.Rest.Azure.CloudError` exception  `Invalid filter clause specified: 'timestamp ge '2020-09-30T17:01:09Z' and timestamp le '2020-10-01T17:01:08Z''.` being thrown.

**To Reproduce**
The line `new ODataQuery<RequestReportRecordContract>(i => i.Timestamp >= start && i.Timestamp <= end)` shouldn't contain quoted dates, or the issue is that API-M cannot support quoted dates.

I also checked the following:

`new ODataQuery<RequestReportRecordContract>($"timestamp ge 2020-09-30T16%3A35%3A52Z and timestamp le 2020-10-01T16%3A35%3A51Z")` is Valid, which means that the encoding isn't the issue.

`new ODataQuery<RequestReportRecordContract>($"timestamp ge '2020-09-30T16%3A35%3A52Z' and timestamp le '2020-10-01T16%3A35%3A51Z'")` is Invalid, which means it's the quotes that's causing the problem.

**Environment:**
- Microsoft.Azure.Management.ApiManagement (6.0.0-preview)
 - Windows 10
 - Microsoft.NETCore.App (2.1.0)
 - Visual Studio 16.7.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
For OData V3, datetime can be enclosed in quote. Assigning to service team.
