### ISSUE TITLE
[BUG] Diagnostic Listener throws System.OverflowException

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#15615]
**Describe the bug**
Diagnostic Listener throws System.OverflowException

**Expected behavior**
What is the expected behavior?
Exception is not thrown.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
![MicrosoftTeams-image](https://user-images.githubusercontent.com/61715331/94842155-e8931900-03cf-11eb-9c29-96df5bd4c95f.png)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

(there's probably easier way, but this is where I got it)
1. Fetch master (i.e. from this commit https://github.com/Azure/azure-sdk-for-net/tree/ef88997b2120e7685414d19a44548f036fb1219b )
2. Open Storage Webjobs Extension Solution
3. Enable trace listener (like shown on screeenshot)
4. Run webjobs E2E tests (make sure to set AzureWebJobsStorage and AzureWebJobsSecondaryStorage with connection strings).

**Environment:**
- Windows 10
- VS 2019
- netcoreapp2.1

Btw. I've also seen some transient index out of bounds exceptions in the net461 suite.

**Comment by pakrym** [comment]
I was never able to repro this. Please reopen if it still persists.
