### ISSUE TITLE
ShareDirectoryClient.Exists() may throw an exception if directory does not exist (ErrorCode: ParentNotFound)

### ISSUE THREAD

**Issue by fokkog** [Azure/azure-sdk-for-net#15628]
**Describe the bug**
For a non-existing directory, the behaviour of ShareDirectoryClient.Exists() varies:
- For a path "dir_does_not_exist" it returns False
- For a path "parent_dir_exists\sub_dir_does_not_exist" it returns False
- For a path "parent_dir_does_not_exist\sub_dir_does_not_exist" it throws an exception

**Expected behavior**
It seems reasonable to assume that an Exists() method always returns True or False under normal conditions. Hence not occasionally throw an exception for a non-existing directory, depending on the part of the path that does not exist.
We did get such consistency earlier, from the CloudFileDirectory.ExistsAsync() method in the v9.x SDK (WindowsAzure.Storage package) and the v11.x SDK (Microsoft.Azure.Storage.File package).

**Actual behavior (include Exception or Stack Trace)**
See description above, full exception is:
```
Azure.RequestFailedException: The specified parent path does not exist.
RequestId:adf8bd21-501a-001e-0d40-980676000000
Time:2020-10-01T22:14:40.7697655Z
Status: 404 (The specified parent path does not exist.)
ErrorCode: ParentNotFound

Headers:
Server: Windows-Azure-File/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: adf8bd21-501a-001e-0d40-980676000000
x-ms-client-request-id: 06861a3e-6caf-45b9-a296-d538afe4556d
x-ms-version: 2019-12-12
x-ms-error-code: ParentNotFound
Date: Thu, 01 Oct 2020 22:14:40 GMT
Content-Length: 224
Content-Type: application/xml

   at Azure.Storage.Files.Shares.FileRestClient.Directory.GetPropertiesAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Files.Shares.FileRestClient.Directory.GetPropertiesAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, String sharesnapshot, Nullable`1 timeout, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Files.Shares.ShareDirectoryClient.GetPropertiesInternal(Boolean async, CancellationToken cancellationToken, String operationName)
   at Azure.Storage.Files.Shares.ShareDirectoryClient.ExistsInternal(Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Files.Shares.ShareDirectoryClient.Exists(CancellationToken cancellationToken)
...
```

**To Reproduce**
Invoke Exists() or ExistsAsync() on a ShareDirectoryClient object that has been created for a path like "parent_dir_does_not_exist\sub_dir_does_not_exist"

**Environment:**
- Name and version of the Library package used: Azure.Storage.Files.Shares v12.x 
- Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): not relevant
- IDE and version : not relevant

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

Thanks for bringing this issue to our attention. This is a reasonable ask, you're right, we should be also catching that error code. We will look to update the exists method soon. I will label this as a bug.

**Comment by fokkog** [comment]
Thanks for the quick response. Let me add that ShareFileClient.Exists() behaves similar to ShareDirectoryClient.Exists().
