### ISSUE TITLE
Write MigrationGuide.md for Search

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#15635]
Write a migration guide a la Key Vault (can use top several paragraphs almost as-is, which we're starting to use consistently) for migrating from Search track 1 to track 2 libraries.

Should include,
- [ ] How to search
- [ ] How to filter
- [ ] How to upload/merge/etc. documents
- [ ] How to use FieldBuilder
- [ ] Maybe mention something about spatial types and converters

**Comment by heaths** [comment]
We could also point to this: https://docs.microsoft.com/azure/search/search-dotnet-sdk-migration-version-11

@AlexGhiondea @tg-msft @brjohnstmsft is there any reason to effectively duplicate these docs? A migration guide here would have samples, but maybe those same samples could be put into the current online one. The MigrationGuide.md doesn't get packaged with the nupkg, so I don't see much value in collocating one here, except maybe to direct them to the aforementioned link.

**Comment by brjohnstmsft** [comment]
I think pointing to the docs that already exist should be fine.

**Comment by AlexGhiondea** [comment]
This is done.
