### ISSUE TITLE
[FEATURE REQ] Allow mocking of ResourceGroup

### ISSUE THREAD

**Issue by Snejj** [Azure/azure-sdk-for-net#15639]
**Library or service name.**
Azure.ResourceManager.Resources.Models.ResourceGroup
 
**Is your feature request related to a problem? Please describe.**
Currently you are unable to Mock ResourceGroup (at least not using Moq like I am). This could be solved in multiple ways, but the simplest way I know is to add a parameterless constructor to the ResourceGroup class. It could probably be solved by doing a few other things like making the attributes virtual or adding public setters to ResourceGroup's attributes but that could have unintended side effects.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Snejj** [comment]
There are quite a few classes that aren't Mockable in Azure.ResourceManager.Resources.Models. Actually, most of them aren't. Just ran into this issue again with Azure.ResourceManager.Resources.Models.DeploymentExtended. Just wanted to give a heads up :)

**Comment by markcowl** [comment]
@m-nash let's make sure we think about this in the .Net sdk preview update

**Comment by jhested** [comment]
I really think this is something that needs to be addressed. It makes testing very difficult. I can do a pull request if you like, but isn't this something that should be done by autorest?

**Comment by jhested** [comment]
It seems like this might have been resolved with commit https://github.com/Azure/azure-sdk-for-net/commit/d4606a27f838d3dd283a559b4db39e96bacb4e13#diff-e99ffef763538241ea128c2bda0c8377adda55d3bcf5603cb8d32f71a57f772d

If im not mistaken?

**Comment by ArthurMa1978** [comment]
We're working on the [model factory](https://github.com/Azure/autorest.csharp/issues/2112) that will provide the mocking test for all models.
