### ISSUE TITLE
CertificatePolicy accepts a list of certificate LifetimeActions but specifying more than one fails when creating a new cert.

### ISSUE THREAD

**Issue by mikaelm12** [Azure/azure-sdk-for-net#15633]
**Describe the bug**
The CertificatePolicy type in the Microsoft.Azure.Management.KeyVault.Models namespace accepts a list of certificate `LifetimeActions`. I figured this implied you could set multiple actiions but doing so causes an error when trying to create the certificate. 

Here I think: https://github.com/Azure/azure-sdk-for-net/blob/cdf82949f13ea1e432d2bac6e55ac98899c0ab1c/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/CertificatePolicy.cs#L230

**Expected behavior**
Should probably not accept a list of LifeTimeActions since having more than one causes an error. A little misleading

**Actual behavior (include Exception or Stack Trace)**
```
{"error":{"code":"BadParameter","message":"At most one action is allowed"}}

   at Microsoft.Azure.KeyVault.KeyVaultClient.<CreateCertificateWithHttpMessagesAsync>d__85.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<CreateCertificateAsync>d__68.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Define 2 certificate lifetime actions and add them to the certificate policy
2. Try to create the certificate

**Environment:**
 -     <PackageReference Include="Microsoft.Azure.Management.KeyVault" Version="2.4.3" />

Thanks!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by heaths** [comment]
Microsoft.Azure.KeyVault is deprecated. We recommend everyone upgrade to [Azure.Security.KeyVault.Certificates](https://nuget.org/packages/Azure.Security.KeyVault.Certificates) for a [number of good reasons](https://aka.ms/azsdk/intro).

However, it's still a list of actions (and is the code you pointed to): <https://docs.microsoft.com/dotnet/api/azure.security.keyvault.certificates.certificatepolicy.lifetimeactions?view=azure-dotnet#Azure_Security_KeyVault_Certificates_CertificatePolicy_LifetimeActions>

This is what the service specifies, and changing it would be a breaking change. It's possible at some point multiple values may be accepted. We have [guidelines](https://azure.github.io/azure-sdk/general_implementation.html#general-params-server-validation) to not validate service parameters, which could become a blocking issue when the service updates it's behavior.

We could, perhaps, update the documentation for the property. Would that discoverable enough and help?

**Comment by mikaelm12** [comment]
Yeah, I think updating the docs here would be the best option given the breaking change constraint. I probably would have avoided the error with a warning in the docs

**Comment by heaths** [comment]
@KrzysztofCwalina, @schaabs from a guidelines perspective, do you see any problem with me adding a current constraint to documentation only? There's a possibility it may some day be inaccurate, but at least it wouldn't cause any blocking behavior.
