### ISSUE TITLE
[FEATURE REQ]The Azure Compute RP version (2019-07-01) doesn't support Disk Create from Gallery Image Reference Id.

### ISSUE THREAD

**Issue by richadua** [Azure/azure-sdk-for-net#15649]
The current version of Fluent .NET SDK (using [2019-07-01](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2019-07-01/disk.json#L1617-L1620)) does not support create disk from gallery.
This can however be done using latest Java (about [2020-05-01](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/Microsoft.Compute/stable/2020-05-01/disk.json#L2067-L2074)) but fails on:

```
DiskInner disk1 = new DiskInner()
{
    OsType = OperatingSystemTypes.Linux,
    Location = Region.JapanEast.Name,
    CreationData = new CreationData()
    {
        CreateOption = DiskCreateOption.FromImage,
        ImageReference = new ImageDiskReference()
        {
            Id = "/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourcegroups/rg-weidxu/providers/Microsoft.Compute/galleries/gallery1weidxu/images/image1weidxu/versions/0.0.1",
        },
    },
};
```
The Azure CLI has an exposed method to create a disk using gallery image reference id:
az disk create -g MyResourceGroup -n MyDisk --gallery-image-reference $id

I urgently need it to support my application. Since there is no way to create a blob uri from the marketplace shared image gallery.

**Comment by richadua** [comment]
Any update on this issue?

**Comment by markcowl** [comment]
@richadua The fluent .Net SDKs are not under active development, as we are moving to a new .Net SDK based on [Azure.Core](https://www.nuget.org/packages/Azure.Core/).  These libraries are currently in early preview, and we are expecting a preview update in the coming months that will contain many more convenience features. You can find the current version of the new SDKs [here](https://www.nuget.org/packages/Azure.ResourceManager.Compute/1.0.0-preview.2). 

 @nickzhums Can you ensure that we consider this scenario in the next preview of the Track 2 SDKs.

**Comment by yungezz** [comment]
@richadua  the development focus shifted to the next generation of Azure SDKs. For .NET, the packages are currently in preview state and we are actively working on making it production ready. For packages that follow the new Azure SDK standard, you can visit this link : https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

That said, .NET Fluent is on the path to deprecation (although it might not happen soon), we are in a low maintenance mode. Let us know if further questions, thanks!

**Comment by xccc-msft** [comment]
@richadua We have updated Compute API version to `2020-06-01`. Can you please check if it solves your problem now? Thanks.

**Comment by weidongxu-microsoft** [comment]
New SDK at https://aka.ms/azsdk/dotnet/mgmt
