### ISSUE TITLE
[FEATURE REQ] Have Recording save to the proper location

### ISSUE THREAD

**Issue by bquantump** [Azure/azure-sdk-for-net#15664]
**Library or service name.**
Common Test Framework
 
**Is your feature request related to a problem? Please describe.**
Recording as of right now do not get saved to the Session Records directory. One has to run tests and then copy them over to the correct directory. This should be changed to automatically put them in the correct spot. This would be in line with how the Python SDK test framework and CLI test work.

**Comment by pakrym** [comment]
Sounds like a good general-purpose improvement.

**Comment by YalinLi0312** [comment]
Hi @pakrym , this issue is a small part of the test framework improvement task in my team, and I'm going to work on it. What's the plan in your end?

**Comment by JoshLove-msft** [comment]
Here is where we determine the path to store the session record in - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.TestFramework/src/RecordedTestBase.cs#L81

If we can construct the path to the users test directory, we could use that instead. We currently use `TestContext.CurrentContext.TestDirectory` which gives us the directory of the dll. I would think we could grab the pieces we need from that directory and translate it into the code directory instead.
I think the only missing piece is the service directory name, which is available in the constructor of the [TestEnvironment](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.TestFramework/src/TestEnvironment.cs#L30). Maybe we can expose a ServiceName property here? 

There may be a simpler way that I'm not aware of.

**Comment by pakrym** [comment]
>What's the plan in your end?

Fixing this issue is not triaged on our side. We are happy to get help from you.
