### ISSUE TITLE
[FEATURE REQ] Initialize clients should be autogenerated and auto instantiated appropriately 

### ISSUE THREAD

**Issue by bquantump** [Azure/azure-sdk-for-net#15665]
**Library or service name.**
Common TestFramework
 
**Is your feature request related to a problem? Please describe.**
As of this moment, a user writing a new test case for a new RP would need to had write code for to initializeclients (This is what the method is typically called, but really just setting up the clients for recordings correctly). The user should not have to write this code, it should be generated and called appropriately before each test or before a setup to save, dispose, and setup the clients for a new recording for a new test.

**Comment by pakrym** [comment]
Doesn't look like an Azure.Core issue. More of a code generator one. Please reopen if needed.
