### ISSUE TITLE
[FEATURE REQ] [Azure.Identity] Add SilentTokenCacheCredential

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#15678]
**Library or service name.**
What library or service is this request related to?
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
Current SharedTokenCacheCredential doesn't satisfy requirement of Az.Accoiunts, so need to introduce new SilentTokenCacheCredential:
- Allow specify Client Id
- Allow specify TokenCache in options
- Need not compare tenant id when filtering account from cache

The proposed change:
https://github.com/Azure/azure-sdk-for-net/pull/15552/files/0e6904a88b0faf570a53c0d1b148e15bab5536b1..78c85396fa545dfc0bdc783f0cc3aab638f720ae#diff-a099a31f65e7e222de9564e5762b1959

**Comment by pallavit** [comment]
/cc: @christothes as FYI. This was not added to the Identity project so linking to it as well.
