### ISSUE TITLE
[FEATURE REQ] [Azure.Identity] [MSA] Extend AuthenticationRecord to contain access token

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#15677]
**Library or service name.**
What library or service is this request related to? 
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
AuthenticationRecord should contain access token: when using MSA account to login, we first use common tenant "organization" and get authentication record, then we will get exception if using this record to get access token against common tenant "organization" because of some limitation of MSA account. We could avoid such issue if first call returns authentication record plus access token. The proposed change: https://github.com/Azure/azure-sdk-for-net/pull/15552/files/0e6904a88b0faf570a53c0d1b148e15bab5536b1..78c85396fa545dfc0bdc783f0cc3aab638f720ae#diff-08815b87fd1fd344370b2cc08eb6fa5c

**Comment by schaabs** [comment]
We are not planning on adding `AccessToken` to `AuthenticationRecord` as our design intent for the `AuthenticationRecord` is that it not contain any sensitive information. As discussed offline with the issue author, the prefered method for getting the access token after an application has called `Authenticate` would be a subsequent call to `GetToken` or `GetTokenAsync`. Closing the issue.
