### ISSUE TITLE
Docs on docs.ms.com have incorrectly encoded characters for < and >

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-net#15674]
Docs on docs.ms.com have incorrectly encoded characters for ```<``` and ```>```. The are coming through as ```&lt;``` and ```&gt;``` HTML entities.

Example:
https://docs.microsoft.com/en-us/dotnet/api/azure.asyncpageable-1?view=azure-dotnet

**Comment by scbedd** [comment]
This has been resolved!
