### ISSUE TITLE
[FEATURE REQ] No way to chain policies in ClientOptions in Azure.Core

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-sdk-for-net#15673]
**Library or service name.**

Azure.Core v. 1.5.0.0
 
**Is your feature request related to a problem? Please describe.**

Currently my code looks like this for any Client/ClientOptions:

```c#
var options = new ResourcesManagementClientOptions();
options.AddPolicy(myPolicy1);
options.AddPolicy(myPolicy2);

var client =  new ResourcesManagementClient(
    endpoint,
    subscription,
    creds,
    options);
```

because `AddPolicy()` has the return type `void`.

While it could look like this, note it's now a one-liner:

```c#
var client =  new ResourcesManagementClient(
    endpoint,
    subscription,
    creds,
    new ResourcesManagementClientOptions()
        .ChainPolicy(myPolicy1)
        .ChainPolicy(myPolicy2));
```

With [the existing method](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/ClientOptions.cs#L53) `AddPolicy()` it won't work easily:

```c#
public void AddPolicy(HttpPipelinePolicy policy, HttpPipelinePosition position)
{
}
```
because then it would have the return type of itself - `ClientOptions`, which is a base class and not the particular child class:

```c#
public ResourcesManagementClient(
    Uri endpoint,
    string subscriptionId,
    TokenCredential tokenCredential,
    ResourcesManagementClientOptions options = null) // <-- here it's the concrete child class
{
}
```

So the user would have to cast, what's _ugly_:

```c#
var client =  new ResourcesManagementClient(
    endpoint,
    subscription,
    creds,
    (ResourcesManagementClientOptions)new ResourcesManagementClientOptions()
        .AddPolicy(myPolicy1)
        .AddPolicy(myPolicy2));
```

Options:

1. An extension method would do the trick:

```c#
 public static TOptions ChainPolicy<TOptions>(this TOptions options,, HttpPipelinePolicy policy, HttpPipelinePosition position)
    where TOptions  : ClientOptions
{
        options.AddPolicy(policy, position);
        return options;
}
```

2. Make `AddPolicy()` itself generic,

I can submit a PR for either option.

**Comment by abatishchev** [comment]
@jsquire ping on this issue, please

**Comment by jsquire** [comment]
Unfortunately, I am only first-line triage in this area and have no insight.   @pakrym would be the best positioned to update the status.

**Comment by KrzysztofCwalina** [comment]
We tend to avoid fluent APIs in the SDK. They look cute but have several negatives. For example, it's not clear whether the returned options instance is the same as the *this* instance.

Also, the generic extension method proposed can be added to user project, if the user prefers fluent APIs.
