### ISSUE TITLE
[BUG] OSDiskImage SizeInGB property

### ISSUE THREAD

**Issue by j-rewerts** [Azure/azure-sdk-for-net#15705]
The Compute REST API allows us to get the OS disk size required for marketplace images ([link](https://docs.microsoft.com/en-us/rest/api/compute/virtualmachineimages/get)). Would it be possible for [OSDiskImage.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/compute/Azure.ResourceManager.Compute/src/Generated/Models/OSDiskImage.cs) to also have that property?

I just realized while writing this issue that the REST docs don't show sizeInGb or sizeInBytes, but if you try the API, it returns them. Here is the Ubuntu marketplace image response: 

``` json
{
  "properties": {
    "hyperVGeneration": "V1",
    "replicaType": "Unmanaged",
    "disallowed": {
      "vmDiskType": "None"
    },
    "automaticOSUpgradeProperties": {
      "automaticOSUpgradeSupported": true
    },
    "osDiskImage": {
      "operatingSystem": "Linux",
      "sizeInGb": 31,
      "sizeInBytes": 32213303808
    },
    "dataDiskImages": []
  },
  "location": "southeastasia",
  "name": "18.04.202009220",
  "id": "/Subscriptions/e605a3bc-ee4e-4c7a-9709-1868a28b1d4d/Providers/Microsoft.Compute/Locations/southeastasia/Publishers/Canonical/ArtifactTypes/VMImage/Offers/UbuntuServer/Skus/18.04-LTS/Versions/18.04.202009220"
}
```

**Environment:**
 Microsoft.Azure.Management.Compute 39.0.0

.NET Core SDK (reflecting any global.json):
 Version:   2.2.207
 Commit:    f7b16a2cd5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.207\

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
Assigning to Compute team for evaluation. As of right now, this is not exposed in [REST API spec for SDK](https://github.com/Azure/azure-rest-api-specs/blob/544bb00645b4e09590df6a8aa476bd7369562e77/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-01/compute.json#L7602).

**Comment by avirishuv** [comment]
@Vaibhav-Agar is this something you could take a look at?

**Comment by Vaibhav-Agar** [comment]
This has been submitted to the dev team to fix.

**Comment by Vaibhav-Agar** [comment]
This is in the backlog but doesn't have an ETA right now.

**Comment by Vaibhav-Agar** [comment]
Same status - this is in the backlog but doesn't have an ETA right now.

**Comment by Vaibhav-Agar** [comment]
Same status - this is in the backlog but doesn't have an ETA right now.

**Comment by oriwolman** [comment]
Working with the Dev team on ETA

**Comment by TravisCragg-MSFT** [comment]
I am following up with this now

**Comment by navba-MSFT** [comment]
@j-rewerts Apologies for the late reply. We will update this thread once we have more details on this.

@TravisCragg-MSFT Could you please provide an update on this issue ? Awaiting your reply.

**Comment by TravisCragg-MSFT** [comment]
no ETA for a fix yet, pushing this forward.

**Comment by Drewm3** [comment]
Updating this issue to clarify that it is a feature request as compared to a bug.

**Comment by ArthurMa1978** [comment]
The new [SDK](https://www.nuget.org/packages/Azure.ResourceManager.Compute/) support this property now.
