### ISSUE TITLE
[FEATURE REQ]: Include ResourceUtils from Microsoft.Azure.Management.ResourceManager.Fluent.Core

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure/azure-sdk-for-net#15717]
**Library or service name.**
Azure.ResourceManager

**Is your feature request related to a problem? Please describe.**
No, this is related to missing classes when compared to the older Fluent ResourceManagement SDK

**What feature would you like to get added? What problem is it solving?**
Microsoft.Azure.Management.ResourceManager.Fluent.Core had an extremely useful **ResourceUtils** class which is not (yet) available in Azure.ResourceManager

**Comment by yungezz** [comment]
hi @allenjzhang I think the ask to have similiar function ResourceUtils of Microsoft.Azure.Management.ResourceManager.Fluent.Core in new Azure.ResourceManager.

**Comment by KalyanChanumolu-MSFT** [comment]
@yungezz Yes, that is correct. Those are missing on the new SDK

**Comment by yungezz** [comment]
> @yungezz Yes, that is correct. Those are missing on the new SDK

thanks for confirmation. hi @allenjzhang I'll reassign the issue to you since this is ask on new SDK, not fluent.

**Comment by yungezz** [comment]
hi @allenjzhang will reassign the issue to you since the ask is on new generate of .NET SDK. thanks. PIng me if any question

**Comment by allenjzhang** [comment]
Yes. many of the functionality will be incorporated into our new APIs. Stay tuned. Thx
