### ISSUE TITLE
IResourceGroupsOperations::ListAsync issues with Top clause

### ISSUE THREAD

**Issue by cfauchere** [Azure/azure-sdk-for-net#15715]
**Describe the bug**
I use a service principal that can only access a single resource group. Using top=10 (ODataFilter) does not behave as I would expect. I get an empty result with a next link. The next link has an empty result with a next link and so on. Looping like this I can get the unique RG that is accessible from my service principle but it involves a lot of requests where I would expect being able to do so in a single request.

**Expected behavior**
Single request needed when using top=10 and when only 1 item is returned

**Actual behavior (include Exception or Stack Trace)**
Multiple requests needed to retrieve a single item

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Use a service principal scoped to a specific resource group
2. call IResourceManagementClient.ListAsync with a ODataFilter with top 10

```
            var rgs = new List<string>();
            var resp = await azureClient.ResourceGroups.ListAsync(new ODataQuery<ResourceGroupFilter>()
            {
                Top = 10
            }, cancellationToken: cancellationToken);
            rgs.AddRange(resp.Select(x => x.Name));

            while (resp.NextPageLink != null)
            {
                resp = await azureClient.ResourceGroups.ListNextAsync(resp.NextPageLink, cancellationToken: cancellationToken);
                rgs.AddRange(resp.Select(x => x.Name));
            }
```

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.ResourceManager 3.10.0-preview
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
