### ISSUE TITLE
6.1.1-preview WindowsAzure.Storage Exception "A strongly-named assembly is required"

### ISSUE THREAD

**Issue by TerribleDev** [Azure/azure-sdk-for-net#1573]
I am on beta 8 (of aspnet 5) and I keep getting the following exception with WindowsAzure.Storage whenever I try to load the assembly.

"A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)"

Repro project: https://github.com/tparnell8/AspNetCache-AzureTableStorage/tree/master/src/AzureTableStorageCacheSample

**Comment by gongdo** [comment]
Also rc1 too.

**Comment by mirobers** [comment]
This issue has been resolved long ago, but missed closing it because it's not in the azure-storage-net repo. Feel free to report further issues with the storage client in azure-storage-net. Thanks!
