### ISSUE TITLE
[BUG] DataLakeFileClient.Rename InvalidSourceUri

### ISSUE THREAD

**Issue by vforteli** [Azure/azure-sdk-for-net#15764]
**Describe the bug**
Calling DataLakeFileClient.Rename on a file with "special" characters requiring html encoding results in Bad Request "The source URI is invalid". Other methods like Exists() and GetProperties() work with the same client.
Very similar to this issue in the java client: https://github.com/Azure/azure-sdk-for-java/issues/8761

**Expected behavior**
Successfully rename the file

**Actual behavior (include Exception or Stack Trace)**
Bad Request "The source URI is invalid"

**To Reproduce**
1. Create a file in a DataLakeGen2 account with special characters, eg "foo bar.txt"
2. Create a DataLakeFileClient to this file, eg service.GetFileSystemClient("...").GetDirectoryClient("...").GetFileClient("foo bar.txt")
3. Call Rename on file client

**Environment:**
 - NetCore 3.1
 - Azure.Storage.Files.DataLake 12.4.0
 - DataLake Gen2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by vforteli** [comment]
Apparently this is already fixed in 12.5.0-preview.1
