### ISSUE TITLE
Why is apiVersion argument needed ResourcesOperationsExtensions::DeleteByIdAsync?

### ISSUE THREAD

**Issue by cfauchere** [Azure/azure-sdk-for-net#15770]
**Describe the bug**
I do not know if this is really a bug. It might be by design but it makes the API/sdk hard/impossible to use.
The problem is with the apiVersion argument in this extension method. The value stored in IResourceManagementClient::ApiVersion is not accepted by the SDK.

`
public static Task DeleteByIdAsync(this IResourcesOperations operations, string resourceId, string apiVersion, CancellationToken cancellationToken = default);
`

**Expected behavior**
The SDK uses default or latest version. 

**Actual behavior (include Exception or Stack Trace)**
The SDK requires API version to be provided. How does a developer determine the version to use? Can it be hardcoded? Does it have to be updated to reflect latest updates? Does it vary by provider?

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.
2.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.ResourceManager 3.10.0-preview
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by cfauchere** [comment]
> @cfauchere The ApiVersion parameter is required by the Azure REST API and hence needs to be supplied by the management library too.
> 
> I had a similar scenario while working with the Fluent SDK (Microsoft.Azure.Management.ResourceManager.Fluent.Core)
> I wrote a function to help me retrieve the API version from the resourceId.
> You can then use the API version for your DeleteByIdAsync call.
> 
> Please check if it helps
> 
> ```cs
> using Microsoft.Azure.Management.ResourceManager.Fluent.Core;
> ...
> ...
>         public static string GetAPIVersion(IResourceManager ResourceManager, string resourceId)
>         {
>             string apiVersion;
> 
>             try
>             {
>                 var resourceProvider = ResourceUtils.ResourceProviderFromResourceId(resourceId);
>                 var providerResourceTypes = ResourceManager.Providers.GetByName(resourceProvider).ResourceTypes;
> 
>                 apiVersion = providerResourceTypes.Where(c => string.Equals(c.ResourceType, ResourceUtils.ResourceTypeForApiVersion(resourceId), StringComparison.OrdinalIgnoreCase))
>                                                   .Select(c => c.ApiVersions.FirstOrDefault()).FirstOrDefault();
>             }
>             catch (Exception ex)
>             {
>                 throw new Exception($"GetAPIVersion failed for ResourceId {resourceId} with Exception {ex.Message}", ex);
>             }
> 
>             return apiVersion;
>         }
> ```

I ended up doing something similar. What I do not understand is why going through the extra burden? eg why this is not encapsulated in the SDK like it is for other operations. For instance if I want to create a resource group I do not have to worry about api version.

**Comment by KalyanChanumolu-MSFT** [comment]
@cfauchere I don't work on the Azure Rest team and cannot say for sure why this is a requirement.
One use case that I know, it helps customers use the same code base across hybrid environments such as Azure Stack and global Azure.

But I agree that the SDK can help here. I will research this a bit more and put in a feature request.

**Comment by allenjzhang** [comment]
I think this is by design. The generic resource level operation implemented at ARM level. ARM will not know the specific API version of the RP and would require the api-version to be passed in.

But I agree this makes it harder to use. I am opening a feature request to look into this as part of our track 2 API design.

**Comment by allenjzhang** [comment]
@eladperets, @chiragg4u, any ideas why the api-version is required [here](https://github.com/Azure/azure-rest-api-specs/blob/c0d29bdb92c4e2f1400a22ab40797c4ee5c3fdab/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#L3341) and few other places?

**Comment by eladperets** [comment]
> @eladperets, @chiragg4u, any ideas why the api-version is required [here](https://github.com/Azure/azure-rest-api-specs/blob/c0d29bdb92c4e2f1400a22ab40797c4ee5c3fdab/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#L3341) and few other places?

I didn't add this API version, or generated the SDK (I think it was @filizt in [this ](https://github.com/Azure/azure-rest-api-specs/pull/9487)PR. The team that owns this SDK is ARM). In any case, API versions are required in all Azure REST API operations. Is it a common thing in the .NET SDKs that it defaults to the latest API version and it's just this SDK that's not behaving as expected? How does the SDK 'knows' to default to the latest API version? is that part of the auto-generation process or is it something that the SDK owners need to add manually?

**Comment by markcowl** [comment]
The reason this is required is because the generic resource operations allow you to address operations to individual RPs, which all have api-versions that are not related to the ARM api-version.  If you want to forego the api-version parameter, for deletion, you should use the typed management library for that RP (e.g. Microsoft.Azure.Management.Compute).
