### ISSUE TITLE
[BUG] IWebAppsOperations.ListSlotConfigurationNamesWithHttpMessagesAsync lacking slotName input

### ISSUE THREAD

**Issue by Devvox93** [Azure/azure-sdk-for-net#15827]
**Describe the bug**
The `IWebAppsOperations.ListSlotConfigurationNamesWithHttpMessagesAsync` method lacks an input parameter for the slot name, which causes the method to only work for Web apps (and not Web app **slots**).
See also related [issue 12680](https://github.com/Azure/azure-powershell/issues/12680) over at Azure Powershell.

**Expected behavior**
I can pass a slot name and get the slot config names for the **slot**.

**Actual behavior (include Exception or Stack Trace)**
The above is not possible.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Get-AzWebAppSlot to get a slot
2. Use Get-AzWebAppSlotConfigName and pass the resulting object from above to the -WebApp parameter
3. The error "Input object is a deployment slot, not a production web app" is displayed.

The error mentioned above might come from the Powershell commandlet, but it throws this because of the bug I'm reporting now.
See also [my comment](https://github.com/Azure/azure-powershell/issues/12680#issuecomment-706055722) in the related issue mentioned earlier.

**Environment:**
 - Microsoft.Azure.Management.WebSites (2.2.0, obtained from [this file](https://github.com/Azure/azure-powershell/blob/v4.4.0-July2020/src/Websites/Websites/Websites.csproj), but parameter is lacking in [file on the master branch](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/websites/Microsoft.Azure.Management.WebSites/src/Generated/IWebAppsOperations.cs))
 - See environment data in related issue (mentioned at the top) for more info.
 - IDE and version : N/A

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Kotasudhakarreddy** [comment]
@Devvox93 - The `Get-AzWebAppSlotConfigName` cmdlet retrieves the list of App Setting and Connection String names that are currently marked as slot settings. To get the slot config names we should pass webapp object not webapp slot object.

1. `$webApp= Get-AzWebApp -ResourceGroupName "Default-Web-WestUS" -Name "ContosoSite"` - to fecth webapp object
2. Use `Get-AzWebAppSlotConfigName  -WebApp $webApp` - to fetch the slot config names.

check [here](https://docs.microsoft.com/en-us/powershell/module/az.websites/get-azwebappslotconfigname?view=azps-4.8.0) for more details.

@panchagnula - FYI

**Comment by Devvox93** [comment]
With the steps described above, one can only get the slot settings for the main web app. It is impossible to get the slot settings for a specific slot with this command. Since this issue is closed, I conclude that full support will not be built into this command nor in an alternative.
