### ISSUE TITLE
[BUG] BlobSasBuilder appears to generate invalid signature in SAS token

### ISSUE THREAD

**Issue by jkindwall** [Azure/azure-sdk-for-net#15837]
I am trying to adapt this sample code (https://github.com/Azure-Samples/batch-dotnet-quickstart/blob/master/BatchDotnetQuickstart/Program.cs) to use the v12 Azure Storage API and I'm having trouble generating a SasUri for a blob.  Here is the updated code I'm using:

```c#
        private static async Task<ResourceFile> UploadFileToContainer(BlobContainerClient blobContainerClient, string containerName, string filePath)
        {
            Console.WriteLine("Uploading file {0} to container [{1}]...", filePath, containerName);

            string blobName = Path.GetFileName(filePath);

            filePath = Path.Combine(Environment.CurrentDirectory, filePath);
            BlobClient blobClient = blobContainerClient.GetBlobClient(blobName);
            try
            {
                await blobClient.UploadAsync(filePath);
            }
            catch (RequestFailedException ex)
            {
                if (ex.ErrorCode != "BlobAlreadyExists") { throw; }
            }

            BlobSasBuilder blobSasBuilder = new BlobSasBuilder()
            {
                StartsOn = DateTimeOffset.Parse("2020-10-08T19:58:00Z"),//DateTimeOffset.UtcNow,
                ExpiresOn = DateTimeOffset.Parse("2020-10-09T19:58:00Z"),//DateTimeOffset.UtcNow.AddHours(2),
                BlobContainerName = blobContainerClient.Name,
                BlobName =  blobClient.Name
            };
            blobSasBuilder.SetPermissions(BlobContainerSasPermissions.Read);
            UriBuilder uriBuilder = new UriBuilder(blobClient.Uri);
            uriBuilder.Query = blobSasBuilder.ToSasQueryParameters(new StorageSharedKeyCredential(Program.BatchAccountName, Program.BatchAccountKey)).ToString();

            return ResourceFile.FromUrl(uriBuilder.Uri.ToString(), blobName);
        }
```

I've verified that the files are successfully uploaded to my storage account, so that implies that the BatchAccountName and BatchAccountKey values are correct.  This code generates the following SAS Uri:

`https://batchetjobsa.blob.core.windows.net/input/taskdata0.txt?sv=2019-12-12&st=2020-10-08T19%3A58%3A00Z&se=2020-10-09T19%3A58%3A00Z&sr=b&sp=r&sig=IBR0CZhDcC2vp%2BS65LzNph5iXMvThciHbE366mkwKeA%3D
`

When I try this in a browser, I get the following:

```xml
<Error>
  <Code>AuthenticationFailed</Code>
  <Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:d4436973-b01e-005c-2e65-9e147a000000 Time:2020-10-09T17:55:57.0422053Z</Message>
  <AuthenticationErrorDetail>Signature did not match. String to sign used was r 2020-10-08T19:58:00Z 2020-10-09T19:58:00Z /blob/batchetjobsa/input/taskdata0.txt 2019-12-12 b </AuthenticationErrorDetail>
</Error>
```

While attempting to debug this issue, I generated a SAS Uri for the same blob using the same parameters from the azure portal, and this is what it produced:

`https://batchetjobsa.blob.core.windows.net/input/taskdata0.txt?sp=r&st=2020-10-08T19:58:00Z&se=2020-10-09T19:58:00Z&sv=2019-12-12&sr=b&sig=lX4w0nwJQjkRALgL6PVp7%2B%2FkBrvwNYDYTS7dTwEqwtI%3D`

At a glance, it seems the order of query parameters is a little different in this URI, and the colons in the timestamps are not urlencoded, but otherwise all the actual values in the query string (except the signature) are the same, and most importantly, this url works.  As a final sanity check to make sure both signatures were signing the same string, I changed one character in the signature of this url and plugged it into a browser in order to generate the same error payload as above and sure enough, the signed string shown in the error message is identical:

`String to sign used was r 2020-10-08T19:58:00Z 2020-10-09T19:58:00Z /blob/batchetjobsa/input/taskdata0.txt 2019-12-12 b`

So am I missing something wrong in my code, or is this a bug in the BlobSasBuilder?  As far as I can tell we have the exact same source string, signed with what should be the exact same key, and we're getting different signatures.

**Environment:**
 - Azure.Storage.Blobs 12.6.0 
 - Windows 10/CentOS 7.5 (.NET Core 3.1)
 - Visual Studio 2019 (v16.7.3)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jkindwall** [comment]
Okay, I figured out my problem.  The example code uses both a Batch Account and a Storage Account, and I accidentally used the name and key for the Batch account instead of the Storage account when creating the StorageSharedKeyCredential.

You can close this.
