### ISSUE TITLE
Add metadata to a block

### ISSUE THREAD

**Issue by jigar61** [Azure/azure-sdk-for-net#15849]
**Query/Question**
We have a need to store some metadata on the blocks while uploading them. Currently it looks like you can set metadata on the blob level but not at the block level. Is there a way to add metadata to the block while uploading them that you can pull down at a later stage?

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.6.0
 - Hosting platform or OS and .NET runtime version: Windows 10 .NET Core 3.1.8
 - IDE and version : Visual Studio 16.7.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi,

This would be a feature request for the backend service.  We will take in under consideration, but it is unlikely this feature will be added in the near future.

-Sean
