### ISSUE TITLE
[BUG] Can't create instance of "FileSmbProperties" with Azure.Storage.files.shares

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#15853]
**Describe the bug**
Can't new instance of "FileSmbProperties" in Azure.Storage.files.shares 12.5.0-preview.1.
So can't use FileSmbProperties in ShareFileClient.Create().

This is because "FileSmbProperties" construct function is set as internal, see [code](https://github.com/Azure/azure-sdk-for-net/blob/7c83666526cdda52664a06e7897ed4cbbe4ec53f/sdk/storage/Azure.Storage.Files.Shares/src/Models/FileSmbProperties.cs#L55).

**Expected behavior**
In project reference Azure.Storage.files.shares 12.5.0-preview.1, can't new instance of "FileSmbProperties".

As we see in the [SDK Unit test](https://github.com/Azure/azure-sdk-for-net-pr/blob/311c797e27d246f2622697da23c6565d04ae75fc/sdk/storage/Azure.Storage.Files.Shares/tests/DirectoryClientTests.cs#L158),  User should can new a instance of "FileSmbProperties".

**Actual behavior (include Exception or Stack Trace)**

In project reference Azure.Storage.files.shares 12.5.0-preview.1, can't new instance of "FileSmbProperties".
Error is : can't new instance of "FileSmbProperties"

**To Reproduce**

1. create a new standalone project reference Azure.Storage.files.shares 12.5.0-preview.1
2. try to run following code 

```
FileSmbProperties smbProperties = new FileSmbProperties();
```
**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.files.shares 12.5.0-preview.1] 
Azure.Storage.files.shares 12.5.0-preview.1

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by amishra-dev** [comment]
@seanmcc-msft / @amnguye can one of you please look at this.

**Comment by blueww** [comment]
@seanmcc-msft / @amnguye 
IS there any update for this issue?

**Comment by amnguye** [comment]
`FileSmbProperties` empty constructor is set to internal, so no one run the line
`FileSmbProperties smbProperties = new FileSmbProperties();`

However this problem has existed before 12.5.0-preview.1, I tried it out with 12.4.0 and it also doesn't work.

@seanmcc-msft do you know if there's any reason why we would set it to internal? I can imagine the original intention being along the lines of using internally to convert responses to the correct format and class. Would it be a big deal to set the constructor to set it to public?

**Comment by seanmcc-msft** [comment]
@amnguye, our model constructors are internal by default.  It appears this one shouldn't be, I think we were just following the pattern.  I think it would make sense to make it public.

**Comment by amnguye** [comment]
I made issue #16692 to address our tests not being able to catch an issue like this.
