### ISSUE TITLE
[BUG]: AddEntityAsync on TableClient doesn't work with ITableEntity

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure/azure-sdk-for-net#15859]
**Describe the bug**

AddEntityAsync doesn't work unless a concrete implementation T is specified when passed as argument to another function

![image](https://user-images.githubusercontent.com/8835012/95685514-f6d60600-0c15-11eb-885c-f3e9d48b5a14.png)

![image](https://user-images.githubusercontent.com/8835012/95684454-862beb00-0c0f-11eb-9022-84b1178b2688.png)

![image](https://user-images.githubusercontent.com/8835012/95684470-9e9c0580-0c0f-11eb-933e-3f960673bf72.png)

**Expected behavior**
We should be able to pass the object to another function to do the add/insert operations.

**Actual behavior (include Exception or Stack Trace)**
It results in Compiler Error CS0310

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Define an entity, implementing ITableEntity

```c#
       public class OfficeSupplyEntity : ITableEntity
        {
            public string Product { get; set; }
            public double Price { get; set; }
            public int Quantity { get; set; }
            public string PartitionKey { get; set; }
            public string RowKey { get; set; }
            public DateTimeOffset? Timestamp { get; set; }
            public ETag ETag { get; set; }
        }

```
2.
```c#
// Create an instance of the strongly-typed entity and set its properties.
            var strongEntity = new OfficeSupplyEntity
            {
                PartitionKey = partitionKey,
                RowKey = rowKeyStrong,
                Product = "Notebook",
                Price = 3.00,
                Quantity = 50
            };

// Add the newly created entity by passing to another function
       await AddEntitiesAsync(tableName, strongEntity);
```

```c#

    public static async Task AddEntitiesAsync(string tableName, ITableEntity tableEntity)
        {
            try
            {
                var TableClient = GetAuthenticatedTableClient(tableName);

                await TableClient.AddEntityAsync(tableEntity);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }

```

**Environment:**
 - Name and version of the Library package used: **Azure.Data.Tables 3.0.0-beta.2**
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):.NET SDK (reflecting any global.json):
 Version:   5.0.100-rc.1.20452.10
 Commit:    473d1b592e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20226
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20452.10\

Host (useful for support):
  Version: 5.0.0-rc.1.20451.14
  Commit:  38017c3935

.NET SDKs installed:
  5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.1.20451.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.1.20451.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.1.20452.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by christothes** [comment]
Hi @KalyanChanumolu-MSFT  - Thanks for the feedback.

This is expected behavior when specifying the TableEntity by its interface only. The `ITableEntity` interface is not enough information to satisfy the generic type constraint for the `AddEntityAsync` method on the `TableClient`. 

Changing your example method as follows will allow it to compile as expected:

```C#
public static async Task AddEntitiesAsync<T>(string tableName, T tableEntity) where T : class, ITableEntity, new()
{
	try
	{
		var TableClient = new TableClient("DefaultEndpointsProtocol=https;AccountName=chrissprim;AccountKey=w2GsjnU25EwBrWG2mpF8n9BRuhJP3EzbaoLoM/JBlxP246q1jDKWGVvF041/Czrf7C2iIGmhDd5EeMtlvTh9dA==;EndpointSuffix=core.windows.net", "githubbug");

		await TableClient.AddEntityAsync(tableEntity);
	}
	catch (Exception ex)
	{
		Console.WriteLine(ex.Message);
	}
}
```

Does that approach work for your scenario?

**Comment by KalyanChanumolu-MSFT** [comment]
@christothes Thank you. 
Although we would need to change our existing methods a bit, this seems cleaner and will work.
Closing the bug.

**Comment by christothes** [comment]
Thanks @KalyanChanumolu-MSFT. Just for some more context, we could have also addressed this by enforcing an abstract base class for the TableEntity type, however our thought was that this places more restrictions on existing code that would need to not only be decorated with the `ITableInterface` but also derive from our base class. This approach allows existing classes not to change any possible base classes they may already be using.

**Comment by KalyanChanumolu-MSFT** [comment]
Thanks @christothes 
This works.

I just started porting to the new SDK's from the Fluent libraries and will post more bugs/feedback.
