### ISSUE TITLE
[FEATURE REQ] Support for entity-scoped connection strings for Azure Service Bus

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-sdk-for-net#15864]
**Library or service name.**
Azure.Messaging.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
Support for entity-scoped connection strings for Azure Service Bus instead of namespace-level connection strings.

Today you still have to provide the entity path when creating a receiver while we tend to pass it in the connection string.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by JoshLove-msft** [comment]
Interesting, yeah we can consider an overload that doesn't take an entity path and will throw if the entity path was not in the connection string.

**Comment by tomkerkhove** [comment]
Happy to hear you are considering, but until this or https://github.com/Azure/azure-sdk-for-net/issues/15892 is supported we cannot migrate given we cannot use entity-scoped connection strings.

**Comment by JoshLove-msft** [comment]
[ServiceBusConnectionStringProperties](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusConnectionStringProperties.cs) is now public, allowing you to get the EntityPath from the connection string.

**Comment by tomkerkhove** [comment]
Awesome, thanks!
