### ISSUE TITLE
Proxy for blob storage connection

### ISSUE THREAD

**Issue by Metrowerks** [Azure/azure-sdk-for-net#15868]
**Query/Question**
- Would it be possible to configure the blob storage connection to use a proxy, similar to using RestExecutorConfiguration for CloudTableClient?
- Is it recommended to use BlobContainerClient as a singleton or is it better to create the object when needed?

**Environment:**
 - Azure.Storage.Blobs 12.2.0]
 - Azure AppService with .NET Core 3.1
 - Visual Studio 16.7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
@tg-msft, do you have any insight into the proxy?

Each BlobContainerClient is immutable associated with a specific container in the storage service, so it is not possible to use it as a singleton.

**Comment by Metrowerks** [comment]
> @tg-msft, do you have any insight into the proxy?
> 
> Each BlobContainerClient is immutable associated with a specific container in the storage service, so it is not possible to use it as a singleton.

I understand that but within the context of a specific container, can it be used as a singleton. In other words, will there be any concerns if I keep the client open for a long time, like an instance running on a web service.

**Comment by seanmcc-msft** [comment]
>  In other words, will there be any concerns if I keep the client open for a long time, like an instance running on a web service.

Nope, no issues.  All our clients are stateless, any don't actually communicate with the storage service unless you perform an API call.

**Comment by tg-msft** [comment]
Yes, see https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy for how to setup a proxy by customizing the Transport.

You can read more about suggested lifetime patterns at https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/.  They don't hold network or system resources so we suggest you use them as singletons.

**Comment by amnguye** [comment]
Please reoopen if there's any further questions related to the issue opened.
