### ISSUE TITLE
Use --prerelease instead of --version in `dotnet add package` in README

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#15876]
Allows us to avoid changing README every time we ship a beta.

**Comment by heaths** [comment]
Maybe implied, but I wanted to call out: this should probably only be for betas, though. I think as people "stumble" across our readmes (perhaps linked from nuget.org itself), they'll most often want the GA'd versions.

**Comment by christothes** [comment]
related to https://github.com/Azure/azure-sdk-for-net/issues/18474

**Comment by jsquire** [comment]
Fixed by [#28193](https://github.com/Azure/azure-sdk-for-net/pull/28193).
