### ISSUE TITLE
[FEATURE REQ] File Share Upload/ Download needs parallelize uploads

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#15882]
**Library or service name.**
Azure.Storage.Files.Shares

**Is your feature request related to a problem? Please describe.**
For upload and download, we do not take advantage of `StorageTransferOptions` for parallelizing uploads and downloads like how we do for `Azure.Storage.Blobs` and `Azure.Storage.Files.DataLake`. 

This wouldn't be too bad since we already did it for blobs and datalake. This would help with the new feature of being able to upload a smb file of 4TB

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
