### ISSUE TITLE
[FEATURE REQ] Helper method to parse Service Bus & Event Hubs connection strings

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#15892]
**Library or service name.**
Azure Service Bus and Azure Event Hubs
 
**Is your feature request related to a problem? Please describe.**

Today, the clients in Azure.Messaging.EventHubs and Azure.Messaging.ServiceBus libraries allow client construction using connection string which can either have the SharedAccessSignature (SAS token) directly in it or have the SharedAccessKey & SharedAccessKeyName in it using which the client can then create the SharedAccessSignature. The other overload is the one that takes the fully qualified namespace and a TokenCredential from Azure.Identity that allows one to use AAD

It is common that to have different auth requirements (connectionString with shared key vs connectionString with SAS vs AAD) based on the environment where their code is deployed (for eg. dev vs test vs prod). The ideal way forward to avoid having to change & re-compile code between environments is to have the below elements configured in the configuration system of choice
- connectionString
- fully qualified namespace
- entityPath

Then, the user can have an if/else block around the presence of the connectionString to decide which constructor overload to use.

Since namespace and entityPath information is already available in the connectionString, it would be helpful to have a way to parse the connectionString to extract these details. This is also helpful when even if one only has the connectionString, the choice is to use AAD. Therefore, this feature request is to add such a helper method to both Event Hubs and Service Bus libraries such that the parsed result can be a struct with 
- The fully qualified namespace
- The entity path (could be named as "EventHubName" in Event Hubs and "QueueOrTopicName" in Service Bus)
- SharedAccessKey  
- SharedAccessKeyName
- SharedAccessSignature

With this helper method, the user will have enough information just from a connection string to decide which constructor overload to use or to take the call to use AAD always.

**Comment by ramya-rao-a** [comment]
cc @jsquire, @JoshLove-msft, @MiYanni

**Comment by tomkerkhove** [comment]
This was proposed in https://github.com/Azure/azure-sdk-for-net/pull/15865, what would be needed to accept that PR? Happy to make changes accordingly.

**Comment by ramya-rao-a** [comment]
@tomkerkhove We are yet to triage the proposal here, I would recommend to wait until we have a confirmation on the right next steps here. Added the `needs-team-triage` label.

**Comment by jsquire** [comment]
Initially triaging to the backlog, pending discussions with the language architect.

**Comment by jsquire** [comment]
The person responsible for reviewing and approving the public API surface across  each of the SDKs, in order to ensure consistency and alignment.   In the case of .NET, that would be @KrzysztofCwalina.

**Comment by jsquire** [comment]
Hi @tomkerkhove.   Just looping back around to mention that plans for a public API for connection string parsing have now passed through design and approval.   The form is a bit different than the internal type, but the implementation is largely the same.   I've opened #16051 with the details around that work and the design.

If you're interested in taking that on, please feel free to ping me on that issue.   I'm happy to help get you onboarded and collaborate on your contribution.   Thanks for your patience and understanding while we worked through this on our end.   I apologize the the transparency wasn't as good as we would have preferred.

**Comment by jsquire** [comment]
Closing this out in favor of #16051, #16052  for Service Bus and #16044 for Event Hubs.

**Comment by tomkerkhove** [comment]
Sounds good and thanks for the update!

I'm happy to contribute this and can plan for this if you want.

**Comment by jsquire** [comment]
@tomkerkhove.   I'll leave that to your discretion;  we're always grateful for contributions.   :smile:

 I'll leave #16051 alone for a bit and am happy to assist with questions or difficulties.   If needed, I'll revisit in the first week of November so that it gets into our next release.
