### ISSUE TITLE
EventHubException ToString() Has No Helping Details

### ISSUE THREAD

**Issue by ericmattingly** [Azure/azure-sdk-for-net#15894]
Hi,

The ToString() override provides no real details on what the exception was or the stack trace.  Can this please be improved?  

For example, here is an exception:
![image](https://user-images.githubusercontent.com/10789017/95812088-75d84680-0cc9-11eb-9419-62b254aed6a3.png)

And here is what ToString() results in (so what is in our logs) :

![image](https://user-images.githubusercontent.com/10789017/95812149-986a5f80-0cc9-11eb-9598-5010e62e1122.png)

Relevant code:

https://github.com/Azure/azure-sdk-for-net/blob/bd94087215e8498f9307cdf7db51c1771d1e7075/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubsException.cs#L186

**Comment by jsquire** [comment]
Hi @ericmattingly.   Thanks for your feedback.   I agree; we should match the default behavior of printing the stack trace with the exception name/reason to match the default .NET exception behavior.   We'll get this patched up for our next release.

**Comment by jsquire** [comment]
Fixed by #16682
