### ISSUE TITLE
[BUG] Azure.Storage.Blob 12.6.0 changed url encoding behavior

### ISSUE THREAD

**Issue by jmather** [Azure/azure-sdk-for-net#15902]
**Describe the bug**
Version 12.5.1/12.6.0 is encoding `/` chars in the filename, so when I pass `some/path/file.json` to `BlobContainerClient.GetBlobClient(string)`, the resulting `blobClient.Uri` ends up like `https://account.blob.core.windows.net/container/some%2Fpath%2Ffile.json`.

Additionally, it seems to now be scrubbing any suffix appended to the `ContainerName` which it was not doing previously.

**Expected behavior**
Using version 12.4.2 (and tested now up to 12.4.4), I was able to pass a path like `some/path/file.json` to `BlobContainerClient.GetBlobClient(string)` and the `blobClient.Uri` returned correctly returned the url `https://account.blob.core.windows.net/container/some/path/file.json`.

Additionally, prior to 12.5.1, if I passed a container name of 'container/foo' instead of 'container', the url that resulted would be `https://account.blob.core.windows.net/container/foo/some/path/file.json`.

**Actual behavior (include Exception or Stack Trace)**
The `/`s in the filename path are getting escaped, so you end up with `some%2Fpath%2Ffile.json` instead of `some/path/file.json`.

Additionally, any suffixes to the container name are being scrubbed.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a `BlobContainerClient` instance using a connection string and a container name, `var container = new BlobContainerClient(config.ConnectionString, GetContainerName());`
2.Create a `BlobClient` using a path with `/` chars, for example `some/path/file.json`, `var client = container.GetBlobClient("some/path/file.json");`
3. use `await client.UploadAsync` to upload content
4. Observe `client.Uri.ToString()` will return a path which matches `some%2Fpath%2Ffile.json`.
5. Observe that the URL given by `client.Uri.ToString()` does not exist according to Blob Storage

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.5.1, 12.6.0
 - Hosting platform or OS and .NET runtime version: Targeting .Net Core 3.1
    ```$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.300
 Commit:    b2475c1295

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.300/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  1.1.10 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.2.105 [/usr/local/share/dotnet/sdk]
  2.2.106 [/usr/local/share/dotnet/sdk]
  2.2.207 [/usr/local/share/dotnet/sdk]
  3.1.202 [/usr/local/share/dotnet/sdk]
  3.1.300 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

 - IDE and version : Rider 2019.3 (I've applied 2020 patches though, so not sure why it's still reporting 2019...)

Edit: Updated after further re-testing, and found out 12.5.1 also wasn't working right... been up all night, sorry. :)

**Comment by seanmcc-msft** [comment]
I recommend using `BlobClient.BlobContainerName` and `BlobClient.Name` with the `BlobSasBuilder` instead of the URI.  We make sure to never incode these properties.

```
BlobSasBuilder sasBuilder = new BlobSasBuilder
{
    BlobContainerName = blobClient.BlobContainerName,
    BlobName = blobClient.Name,
    ExpiresOn = DateTimeOffset.UtcNow.AddDays(1)
}
sasBuilder.SetPermissions(...)
```

**Comment by jmather** [comment]
I was using those, but... I think I ran into the trouble of 'how to get a full URL out of BlobSasBuilder`, so in my service, instead of passing in the filename, I was passing in the URL, so I could return a url ready to go...

Knowing what I do now, I've restructured... 

Used to be...

```
                var expiresOn = DateTime.UtcNow.AddMinutes(configuration.DownloadWindowInMinutes);
                var uri = await blobStorage.StoreData(fileName, content, contentType);
                req.DownloadUri = blobStorage.SignUri(uri, expiresOn);
```

which ran:

```
        public Uri SignUri(Uri resourceUri, DateTime expiresOn)
        {
             var builder = new BlobSasBuilder {
                 BlobContainerName = factory.ContainerName,
                 BlobName = resourceUri.PathAndQuery.Substring(factory.ContainerName.Length + 2), // yes this is super dumb in retrospect... lol
                 ExpiresOn = expiresOn.ToUniversalTime(),
                 Protocol = SasProtocol.Https,
                 Resource = SasStorageResourceBlob,
             };
             builder.SetPermissions(BlobSasPermissions.Read);
 
            var queryParams = builder.ToSasQueryParameters(factory.CreateCredentials());
            return return new Uri(resourceUri + "?" + queryParams);
        }
```

But it is now:

```
                var expiresOn = DateTime.UtcNow.AddMinutes(configuration.DownloadWindowInMinutes);
                var uri = await blobStorage.StoreData(fileName, content, contentType);
                var queryParams = blobStorage.SignUri(fileName, expiresOn);

                req.DownloadUri = $"{uri.ToString()}?{queryParams}";
```

Which runs:

```
        public string SignUri(string fileName, DateTime expiresOn)
        {
            var builder = new BlobSasBuilder {
                BlobContainerName = factory.ContainerName,
                BlobName = GetBlobName(fileName),
                ExpiresOn = expiresOn.ToUniversalTime(),
                Protocol = SasProtocol.Https,
                Resource = SasStorageResourceBlob,
            };
            builder.SetPermissions(BlobSasPermissions.Read);

            return builder.ToSasQueryParameters(factory.CreateCredentials()).ToString();
        }
```

I just really wanted the full URL from that method, I think.

I've tested though, now, and structured like this, this works fine. For whatever reason, I wasn't able to find a lot of documentation around this when I was cobbling this together. It turned into a lot of digging through multiple examples and the rest api docs and so on and so forth to try and figure out how to make this work.

Thanks for working with me and helping me understand how it was all meant to be used. I appreciate it.

**Comment by seanmcc-msft** [comment]
We recommend using the `BlobSasBuilder` in conjunction with the `BlobUriBuilder`.  Continuing from my previous sample:
```
BlobSasBuilder sasBuilder = new BlobSasBuilder
{
    BlobContainerName = blobClient.BlobContainerName,
    BlobName = blobClient.Name,
    ExpiresOn = DateTimeOffset.UtcNow.AddDays(1)
}
sasBuilder.SetPermissions(...)
BlobUriBuilder uriBuilder = new BlobUriBuilder(baseServiceUri)
{
    Sas = sasBuilder.ToSasQueryParameters(credentials),
    BlobContainerName = blobClient.BlobContainerName,
    BlobName = blobClient.Name
};
Uri uri = uriBuilder.ToUri();
```

Following this, you should be able to avoid the '/' vs '%2F' and other encoding issues with SAS.

**Comment by jmather** [comment]
Ah! Excellent, thank you!

**Comment by jmather** [comment]
@seankane-msft is baseServiceUri something you're building manually, or do you have a nifty helper for that squirreled away somewhere as well? :)

**Comment by seanmcc-msft** [comment]
@jmather, that would be the URI from the `BlobServiceClient`, the client at the top of the client hierarchy.  We generally recommend a workflow something along the lines of
```
BlobServiceClient serviceClient = new BlobServiceClient(...);
// Note we are just creating a BlobContainerClient, we are assuming the container already exists in the service.  To create a container in the service, call containerClient.CreateAsync()
BlobContainerClient containerClient = serviceClient.GetBlobContainerClient(containerName);
// Same thing applies as the pervious comment.
BlobClient blobClient = containerClient.GetBlobClient(blobName);
```

This way, you don't actually have to deal with any URIs other than the base URI.

**Comment by jmather** [comment]
@seankane-msft Ok, I get that, and I'm pretty much there with the code now...

Oooooh, I think I see... `BlobContainerClient` has `Uri`, so I suspect...

```
BlobUriBuilder uriBuilder = new BlobUriBuilder(baseServiceUri)
```
could be
```
BlobUriBuilder uriBuilder = new BlobUriBuilder(blobContainerClient.Uri)
```

**Comment by seanmcc-msft** [comment]
@jmather, that would also work.

**Comment by seanmcc-msft** [comment]
Please re-open if you have any other questions!

**Comment by pharring** [comment]
-1 for using BlobUriBuilder. That's the thing that's escaping slashes!
