### ISSUE TITLE
[Test failure] Cancels_OnlySlow

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#15936]
```

Error message
Expected: False
But was:  True


Stack trace
   at Azure.Search.Documents.Tests.AsyncEventExtensionsTests.Cancels_OnlySlow() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/AsyncEventExtensionsTests.cs:line 450

```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=572950&view=ms.vss-test-web.build-test-results-tab&runId=14102406&resultId=100472&paneView=debug

**Comment by heaths** [comment]
Timing-based tests are the worst. For this, I will just increase the "slow test" delay a little and hope that helps.

/cc @tg-msft

**Comment by pakrym** [comment]
Still flaky https://dev.azure.com/azure-sdk/public/_build/results?buildId=630141&view=ms.vss-test-web.build-test-results-tab&runId=15139896&resultId=110779&paneView=debug

**Comment by heaths** [comment]
@tg-msft can you please take a look at this class of timing-related issues with batching?

**Comment by JoshLove-msft** [comment]
Hasn't failed in a while, closing.
