### ISSUE TITLE
[Test Failure]  Smoke Tests Intermittently Fail to Download Linked ARM Templates

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#15934]
See https://dev.azure.com/azure-sdk/internal/_build/results?buildId=572877&view=logs&j=bee470a6-29e9-51d9-5aed-850396332b80&t=99f929b6-b21f-50e0-4b9d-746197048402&l=46 for details.

**Comment by jsquire** [comment]
This is a timeout due to the linked ARM template having issues reaching the GitHub asset.   Daniel was looking into ways to potentially resolve this, when last we spoke.   Moving over to the engineering team.

**Comment by benbp** [comment]
Workaround/resolution: https://github.com/Azure/azure-sdk-for-net/issues/17757
