### ISSUE TITLE
Consider adding TryParse() methods to every AsX method in FieldValue and DocumentField

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#15945]
Feedback from our customers where when trying our `AsX` where `X` is a type methods in [FieldValue](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient/FieldValue.cs) and [DocumentField](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/src/DocumentField.cs) we throw exception when the `Type` doesn't match.
It will be more convenient to have a `TryParse` method that the user can call that will return a bool value. 
See https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance#try-parse-pattern

**Comment by maririos** [comment]
We need to understand which scenarios are causing the throwing and if the if ( xx is type chu) is enough or not

**Comment by maririos** [comment]
Moving to backlog while working on the design. According to when it is ready and approved will add to an active milestone

**Comment by kinelski** [comment]
After discussing this matter with architects, we won't implement `AsX` methods as it could just make the class more confusing to customers.

We decided to add an `DocumentFieldType.Unknown` enum value that can be used in these scenarios. More information here: https://github.com/Azure/azure-sdk-for-net/pull/30909

> Updated the way DocumentField is handled. When the field value is not returned by the service (which happens when they can't parse the extracted value into the expected type), we set DocumentField.FieldType to DocumentFieldType.Unknown in the SDK. Customers could then use the DocumentField.ExpectedFieldType in addition to the raw string DocumentField.Content to manually parse the field value in this case. This change permits handling this scenario without try/catch blocks (current approach).
