### ISSUE TITLE
Azure Monitor Exporter: Discuss package name change

### ISSUE THREAD

**Issue by TimothyMothra** [Azure/azure-sdk-for-net#15943]
## Question
We need to rename our package.
What is the appropriate name for packages published from this repo?

## Details
We're ready to release the first beta of the OpenTelemetry Exporter for Azure Monitor.
We're currently blocked on the name of the package.

- Affected Solution:
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/monitor/OpenTelemetry.Exporter.AzureMonitor
- Affected Project:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/monitor/OpenTelemetry.Exporter.AzureMonitor/src/OpenTelemetry.Exporter.AzureMonitor.csproj

### Currently:
The current name is "**OpenTelemetry.Exporter.AzureMonitor**".
When trying to publish we get the following error: 
> ##[error]The nuget command failed with exit code(1) and error(Response status code does not indicate success: 409 (This package ID has been reserved. Please request access to upload to this reserved namespace from the owner of the reserved prefix, or re-upload the package with a different ID.).

See also: https://github.com/open-telemetry/opentelemetry-dotnet/issues/1336

### Next Steps
I attended the OpenTelemetry Community meeting today.
Their recommendation is for 3rd parties to publish as: "**< VendorName >.OpenTelemetry.Exporter**".

Example:
- Azure.Monitor.OpenTelemetry.Exporter
- Microsoft.Azure.OpenTelemetry.Exporter

I can make this change, I just need to know what name to use :)

**Comment by reyang** [comment]
@TimothyMothra would you involve our PMs and also other language exporter owners? We can give folks two days to put options/opinions and then go with the most preferred one.

Personally I would prefer `Microsoft.Azure.OpenTelemetry.Exporter` but I'd like to avoid us making decision based on my personal preference.

**Comment by cijothomas** [comment]
My personal choice: `AzureMonitor.OpenTelemetry.Exporter` to make it obvious that it Exports to AzureMonitor. (and not to AzureBlob/Table/AzureSQL etc)

**Comment by reyang** [comment]
> My personal choice: `AzureMonitor.OpenTelemetry.Exporter` to make it obvious that it Exports to AzureMonitor. (and not to AzureBlob/Table/AzureSQL etc)

Probably `Microsoft.Azure.OpenTelemetry.Exporter.AzureMonitor`? 😂

My main consideration is that most of the V2 Azure SDKs seem to follow the `Microsoft.Azure.*` pattern:

![image](https://user-images.githubusercontent.com/17327289/95930879-7f6eb680-0d7c-11eb-82dd-6ce2a47ab9f9.png)

**Comment by jsquire** [comment]
> My main consideration is that most of the V2 (or track2, whatever it is called) Azure SDKs seem to follow the `Microsoft.Azure.*` pattern:

The pattern for track two naming is:

`Azure.[[ AREA ]].[[ SERVICE ]]`  for the data plane and `Azure.ResourceManager.[[ SERVICE ]]` for the management plane.   Things that you're seeing with `Microsoft.Azure.[[ SERVICE ]]` are the legacy libraries, with only some special case exceptions involving third party dependencies.

More context can be found in the [.NET Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-packaging)

**Comment by jsquire** [comment]
//cc: @KrzysztofCwalina

**Comment by TimothyMothra** [comment]
Thanks for sharing the guidance.
Our team is coalescing around `Azure.Monitor.OpenTelemetry.Exporter`

**Comment by pakrym** [comment]
We would have to sync with @KrzysztofCwalina, there are strong opinions around about having packages with third-party dependencies with Azure.*  names.

**Comment by ank3it** [comment]
@pakrym : Since the package is owned by us and the idea is to make sure we contribute to the open source contributions; I'm assuming this has been done before. Would love to know how other 'Azure.otherthirdpartynames' are handled.

**Comment by pakrym** [comment]
No `Azure.*` currently has any 3-rd party dependencies outside of .Net/Azure owned libraries. See https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-dependencies

**Comment by TimothyMothra** [comment]
@pakrym @jsquire Who has the authority to make a discussion here? 
Would it be appropriate to rename it as `Azure.Monitor.OpenTelemetry.Exporter` so we can unblock this Beta release?

I think we can leave this issue open and continue to discuss. I don't want the naming to be a blocking issue, and I think it's safe to rename up until we GA.

**Comment by pakrym** [comment]
Can you please start an email thread and include @KrzysztofCwalina. He would be the ultimate authority here.

**Comment by TimothyMothra** [comment]
I discussed this with @KrzysztofCwalina offline.
Recommendation is to use the name `Microsoft.Azure.Monitor.OpenTelemetry.Exporter`


![image](https://user-images.githubusercontent.com/28785781/96753805-3f639100-1385-11eb-8326-b30d83ec5895.png)

**Comment by TimothyMothra** [comment]
We closed on this last week. The final name is **Azure.Monitor.OpenTelemetry.Exporter**
