### ISSUE TITLE
[FEATURE REQ] CloudException.ToString() could be enhanced to improve debuggability

### ISSUE THREAD

**Issue by muiriswoulfe** [Azure/azure-sdk-for-net#15967]
**Library or service name.**
`Azure.Storage.Rest`
 
**Is your feature request related to a problem? Please describe.**
`CloudException` contains a lot of detailed information and in many cases it makes sense to log this detailed information server side for debugging. However, the `ToString()` method drops much of the information such as the `Details` and `AdditionalInfo` fields, as well as any internal exceptions. I propose amending this method to collate more detailed, useful information.

I've got a local file attempting to do something similar, albeit external to the class (and therefore more cumbersome to use). I'm willing to merge this into to the `ToString()` method if you agree it would be of use.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Could you clarify which library you are using?  As far as I know, we don't have a `Azure.Storage.Rest`.

**Comment by muiriswoulfe** [comment]
Apologies for the confusion. It looks like the library is `Microsoft.Rest.ClientRuntime.Azure` as the class in question is [`CloudException`](https://docs.microsoft.com/dotnet/api/microsoft.rest.azure.cloudexception?view=azure-dotnet).

**Comment by seanmcc-msft** [comment]
Oh I think this might be something from V11 and below.

**Comment by seanmcc-msft** [comment]
I recommend moving to [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs/12.7.0-preview.1), v11 and below is on a deprecation path.

**Comment by muiriswoulfe** [comment]
Thanks Sean. We didn't realise that was a deprecated version. I've now filed a bug against our project to track upgrading us to the latest versions.

Feel free to close off this feature request, as I believe it doesn't make sense given that the library is deprecated.
