### ISSUE TITLE
FilterString.Generate for OData queries

### ISSUE THREAD

**Issue by WinInsider** [Azure/azure-sdk-for-net#15991]
**Library or service name.**
Azure.Core / Azure.Search.Documents
 
**Is your feature request related to a problem? Please describe.**
In `Azure.Search.Documents` package `SearchOptions` class takes `Filter` (string) which must be in OData expression syntax.  However, in the new azure-sdk style (ones based on Azure.Core) there is no class to convert .NET Expressions to OData, similar to what `FilterString.Generate(...)` used to do in earlier version of azure-sdks.

Can :
1)  `FilterString.Generate(...)` be added back, or 
2) provided as sperate package contain `FilterString`, or
3) suggest how to deal with converting Expressions to OData... and no, building a "string" is not an option...

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by tg-msft** [comment]
Please see [`SearchFilter.Create`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/README.md#searchoptions).

**Comment by tg-msft** [comment]
Oops - didn't mean to close.

**Comment by WinInsider** [comment]
@tg-msft that's what I wanted to avoid... "string building" with `SearchFilter.Create`... 

`FilterString.Generate` offered ability to express query with C# syntax, without concerns for formatting and OData syntax.

Thus, request for feature stands... add to package or create separate package to add back the missing feature.

**Comment by zhunipingan** [comment]
@WinInsider I have the same peoblem, do you find the solution, I need one similar method as FilterString.Generate(filterExpression) to get a string in Odata style.

**Comment by pallavit** [comment]
This is something we are not planning to support currently in our SDKs. However we will keep this in mind for future planned releases.
