### ISSUE TITLE
[BUG] ComputerVision - Incorrect nullable parameters?

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-sdk-for-net#15998]
**Describe the bug**
In the previous version of the SDK (v5.0.0), many parameters were simply passed in as a list of `enum` types. While the list could be `nullable` the actual values were not. This appears to be changed in v6.0.0.

I believe this might be a similar issue to the newly generated FaceAPI SDK which has the same issue #14701

**Expected behavior**
What is the expected behavior?
That the parameter type values are **not** `nullable`

Checking OAS at https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/ComputerVision/stable/v3.1/ComputerVision.json I believe this should of been generated as a non nullable type?

![image](https://user-images.githubusercontent.com/4549796/96092757-e23b8b80-0efd-11eb-9ba7-176e572a9911.png)

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Current SDK signature, note the `VisualFeatureTypes?` nullable type
```csharp
    public static async Task<ImageAnalysis> AnalyzeImageAsync(
      this IComputerVisionClient operations,
      string url,
      IList<VisualFeatureTypes?> visualFeatures = null,  // previously this was a non nullable enum
      IList<Details?> details = null,
      string language = null,
      IList<DescriptionExclude?> descriptionExclude = null,
      CancellationToken cancellationToken = default (CancellationToken))
    {
      ImageAnalysis body;
      using (HttpOperationResponse<ImageAnalysis> operationResponse = await operations.AnalyzeImageWithHttpMessagesAsync(url, visualFeatures, details, language, descriptionExclude, (Dictionary<string, List<string>>) null, cancellationToken).ConfigureAwait(false))
        body = operationResponse.Body;
      return body;
    }
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] Microsoft.Azure.CognitiveServices.Vision.ComputerVision 6.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd
 - IDE and version : [e.g. Visual Studio 16.3] Visual Studio 16.7.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
This issue raised is on storage data plane. But I believe the question may be related to the recent nullable codegen change. @pakrym , can you take a look and confirm?

**Comment by pakrym** [comment]
This is Track 1 codegen. There were no recent changes around nullability there.

**Comment by wahyuen** [comment]
bump
