### ISSUE TITLE
[BUG] GetBlobClient does not append blobName to BlobContainerClient Uri

### ISSUE THREAD

**Issue by Ahmadbuni** [Azure/azure-sdk-for-net#16004]
I have realized that after updating from 12.4 to 12.6 that the behavior of GetBlobClient has changed and it does not append the blob name to the blob container client uri correctly.

` var container = _blobServiceClient.GetBlobContainerClient(fileLocation)`
` var result = container.GetBlobClient(fileName)`

In fileLocation string I have my container + sub folders and what I would get in result uri previously on 12.4 is root/fileLocation/filename appended correctly.

In 12.6 the container uri is correct and it contains fileLocation, however, after calling GetBlobClient, blobName replaces the uri instead of appending, which makes my result uri root/filename instead of root/fileLocation/filename

To reproduce 

` var container = _blobServiceClient.GetBlobContainerClient(fileLocation);`
` var result = container.GetBlobClient(fileName);`

calling the above code on 12.4 gives you a different uri from 12.6

The issue was produced using Visual Studio 2019 on Window environment

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @Ahmadbuni, I think there is some confusion around `BlobServiceClient.GetBlobContainerClient()`.  The parameter for `.GetBlobContainerClient()` is just the container name, not the path to the directory above the blob in question.

I recommend changing your code snippet to:
```
BlobContainerClient container = _blobServiceClient.GetBlobContainerClient(containerName);
BlobClient blob = container.GetBlobClient($"{fileLocation}/{fileName}");
```

In this case, `containerName = "root"`, `fileLocation = "fileLocation"`. and "fileName = "fileName"`.

-Sean

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
