### ISSUE TITLE
[FEATURE REQ] Computer Vision - New Read API to return language of text that it detected

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-sdk-for-net#16000]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] Microsoft.Azure.CognitiveServices.Vision.ComputerVision
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
Previous in the v2.1 Computer Vision endpoints on the OCR endpoint, multi lingual text that was detected returned a language field to indicate the language that the text was detected in
https://westus.dev.cognitive.microsoft.com/docs/services/5cd27ec07268f6c679a3e641/operations/56f91f2e778daf14a499f20d

> language
The BCP-47 language code (user-provided or auto-detected) of the text detected in the image.

It would be extremely useful to have a similar feature returned in the new v3.x Read API since it now supports more languages than just english.

![image](https://user-images.githubusercontent.com/4549796/96101165-c3da8d80-0f07-11eb-88fd-ebcc6509976d.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by wahyuen** [comment]
bump

**Comment by JimSuplizio** [comment]
Hi @wahyuen, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
