### ISSUE TITLE
Remove DoNotConvertJsonDateTokens  setting from RecordedTestSanitizer

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#16003]
Remove DoNotConvertJsonDateTokens setting from the sanitizer.

It was added a temporary workaround.

At the minimum, it should be inverted so new recordings are not affected by the bug.

**Comment by JoshLove-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/16605

**Comment by pakrym** [comment]
Still not removed.

**Comment by JoshLove-msft** [comment]
> At the minimum, it should be inverted so new recordings are not affected by the bug.

This was done.

**Comment by pakrym** [comment]
We still need to remove the setting when everyone moves off.

**Comment by JoshLove-msft** [comment]
This was removed as part of Test Proxy migration.
