### ISSUE TITLE
[FEATURE REQ] Add a section on the Service Bus Admin client operations in the migration client 

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#16010]
**Library or service name.**
Azure Service Bus
 
**Is your feature request related to a problem? Please describe.**
We have the [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md) going over most of the major changes one would encounter when moving to the new Service Bus library. The naming change of ServiceBusManagementClient to ServiceBusAdministrationClient, the reason for it, the splitting of Queue/Topic/SubscriptionDescription to Queue/Topic/Subscription Options and Properties should be called out

**Comment by JoshLove-msft** [comment]
We have a section on the Administration client, but it does not talk about the other types or the reason for the rename.

**Comment by jsquire** [comment]
The migration guide should be focused on capturing the "how do I" scenarios.   I don't think we want to make it harder to find the fast path to upgrading by including design rationale and other "why"-focused discussion.   Closing this out.
