### ISSUE TITLE
[BUG] Azure.Messaging.EventGrid validation inconsistent with Service

### ISSUE THREAD

**Issue by garrm** [Azure/azure-sdk-for-net#16012]
**Describe the bug**
Migrating to the new Azure.Messaging.EventGrid SDK from our homegrown code, has introduced inconsistencies. The EventGrid service has supported not requiring 'Source' as a required attribute. However, the SDK now mandates that it be present during deserialization (I suspect other attributes are also validated). This has the potential to break existing systems that introduce this into a current environment (ie there's messages that don't have the attribute - but are working fine).

**Expected behavior**
SDK should not validate the payload on deserialization. It makes sense to enforce standards on the way out however ie when sending messages. Though there should be consistency with the actual service, so it maybe better to delegate that responsibility.

**Actual behavior (include Exception or Stack Trace)**
Throws exceptions during parsing (deserialization).

**To Reproduce**
Attempt to parse an EventGrid message that doesn't have the 'Source' attribute or any other attribute that is validated.

**Environment:**
 - Azure.Messaging.EventGrid: 4.0.0-beta.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by JoshLove-msft** [comment]
Closing as this has been fixed.
