### ISSUE TITLE
Why does Microsoft.Azure.Common.Dependencies have a dependency on Microsoft.Bcl.Build for the .NET 4.5 target.

### ISSUE THREAD

**Issue by DaveVdE** [Azure/azure-sdk-for-net#1602]
We're using the Microsoft.WindowsAzure.Management.Storage package to programmatically create storage accounts, and I'm finding that it needs to install Bcl.Build which is, with all due respect, an atrocious NuGet package that sits in the VS process until you quit VS. 

If this package serves to allow older versions of .NET to target some of the newer types, then why is it a dependency for the .NET 4.5 target?

**Comment by markheath** [comment]
we've run into the same issue with a dependency on Microsoft.Azure.KeyVault (which depends on Microsoft.Azure.Common), which then brings Microsoft.Bcl.Build which then results in endless error messages telling you to add it to every single project in your solution, and makes it impossible to run a command line build with Visual Studio open. Would love to get rid of this from our solution (we're targeting .NET 4.5 too)

**Comment by tomleeson** [comment]
We're running into the same issue as well. Targeting 4.5.1.

**Comment by DaveVdE** [comment]
Today I found out there's a series of pre-release packages out that use a different library. The package with id "Microsoft.Azure.Management.Storage" uses "Microsoft.Rest.ClientRuntime.Azure". The only issue I had installing it was a missing reference to System.Runtime.Serialization that was easily fixed. 

Is this the way forward? IMHO, the packages are a mess, and someone should shed some light on it.

**Comment by DaveVdE** [comment]
This pre-release package seems to require a resource group for everything. I like the API better though (no naked http results to check for, no dependency on Bcl.Build) but some things are missing, like where do I pass the subscription Id? What if I don't have a resource group for the storage account I want to make?

**Comment by DaveVdE** [comment]
Also, where's the source for these preview packages?

**Comment by SaintGimp** [comment]
I'm also running into this issue.  Microsoft.Bcl.Build is viral and is super-annoying when it infects my solution.  I'm targeting .Net Framework 4.5.2 and there should be no reason for Microsoft.Bcl.Build to be brought in, right?

**Comment by collinsauve** [comment]
I've been watching Bcl infect our solution for the past 6 months.  Finally get fed up with it and traced the infection back to Microsoft.Azure.Common.

Please remove this silliness.

**Comment by abatishchev** [comment]
+1

**Comment by dallancarr** [comment]
Just upgraded to Microsoft Azure Common Library 2.1.2. Highest minor will do though.

**Comment by michaelaird** [comment]
Also, Microsoft.Azure.KeyVault no longer depends on Microsoft.Azure.Common

**Comment by shahabhijeet** [comment]
@DaveVdE I assume after upgrading Microsoft.Azure.Common library to 2.1.2 this should not be an issue.
