### ISSUE TITLE
[Service Bus] Should IsClosed on the receiver reflect the state of the underlying link?

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#16024]
**Library or service name.**
Azure Service Bus
 
**Is your feature request related to a problem? Please describe.**
In the new Azure.Messaging.ServiceBus library, we have the `IsClosed` field on the sender and receiver which reflects whether the user has called `CloseAsync()` on the sender/receiver. The underlying AMQP link can be in a closed state for a variety of different reasons. This issue is to discuss if the `IsClosed` property should reflect these scenarios as well or not. 

Few cases I can think of where this would be helpful:
- A send call on a sender that is backed by an open AMQP link will only have to send the message. If the AMQP link was closed, then the send call will also include the work of initializing a new link and then sending the message. This will result in a difference in the time taken by the call and may affect applications that have stricter SLA. Having IsClosed denote this can set up clear expectations. Additionally, a dedicated open() method on the sender can be used to set up the link beforehand. Same applies to the receiver.
- When a session receiver loses the lock on a session, every subsequent call on any method on the receiver throws an exception. Having a check on IsClosed may help here? But this is a moot point after #13735

**Comment by JoshLove-msft** [comment]
This could be helpful for the case of the session lock being lost. After this exception happens, any operation with the receiver will fail.

**Comment by JoshLove-msft** [comment]
We ended up not changing the behavior here. IsClosed only represents whether the user has called CloseAsync or DisposeAsync.
