### ISSUE TITLE
[QUERY]Is support for managed identities coming to local machines?

### ISSUE THREAD

**Issue by luckerby** [Azure/azure-sdk-for-net#16043]
As of now, it's clearly documented [here](https://docs.microsoft.com/en-us/azure/key-vault/general/service-to-service-authentication#authenticating-to-azure-services) that `Local machines don't support managed identities for Azure resources`. This means that one cannot test its own Azure functions locally against the emulator, should those functions require managed identities to access their target resources. You'd have to push your code to Azure (eg publish in Visual Studio) each time to get to see the outcome.

A concrete example: trying to use the `AzureServiceTokenProvider` class to get a token on behalf of an Azure function using its managed identity will fail while trying to debug locally, for the reasons described in the section within the link above.

I've noticed that the local Azure emulator supports just fine authenticating using enterprise apps, so I take it that the emulator talks to Azure, as opposed to being a simple sandboxed environment. In this context, is there a big hurdle of getting support for managed identities implemented as well?

**Comment by jsquire** [comment]
/cc: @heaths,  as your insight on KeyVault may be germane to the discussion.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @luckerby - Does the [DefaultAzureCredential](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme#defaultazurecredential) work for your scenario? It will use a managed identity when available, but will fallback to the Visual Studio or the Azure CLI for authorization during local development.

**Comment by luckerby** [comment]
@christothes Using an `Azure.Identity.ManagedIdentityCredential` (as not to depend on the provider order for `Azure.Identity.DefaultAzureCredential`) and then starting to debug locally within Visual Studio results in the message below. The function itself however runs just fine within Azure.

```
System.Private.CoreLib: Exception while executing function: Function1. Azure.Identity: ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
```

**Comment by christothes** [comment]
@luckerby If you want the behavior of DefaultAzureCredential without the default provider order, you can create a custom chain of providers with the [ChainedTokenCredential](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/ChainedTokenCredential.cs).

Does this work for you?

**Comment by luckerby** [comment]
@christothes I'm not after changing the provider order, but I'd only like to test _locally_ an Azure Function backed by a managed identity. If I want to do this currently, I have to push the respective function to Azure, then test. My goal is to be able to run the local Azure emulator and see the result of the function running.

**Comment by christothes** [comment]
@luckerby OK, in that case I'm not sure that is within the scope of the Azure.Identity client SDK. I'll close this for now, unless there is something else we can assist with relating to the client.
