### ISSUE TITLE
LazyLoadingReadOnlyStream.Position setter not implemented while Seek is

### ISSUE THREAD

**Issue by twsouthwick** [Azure/azure-sdk-for-net#16055]
**Describe the bug**
I often use the `Stream.Position` property to set position on seekable streams. With the recent changes to enable seekability (https://github.com/Azure/azure-sdk-for-net/pull/15032), we can now call `Stream.Seek(..., SeekOrigin)`, but `.Position` fails.

**Expected behavior**
I would expect calls to `.Position = x` to work similarly to  `.Seek(x, SeekOrigin.Begin)` as they do on other streams.

**Actual behavior (include Exception or Stack Trace)**
Throws `NotSupportedException`

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```cs
var client = _container.GetBlobClient(plateName);
var stream = client.OpenRead();
stream.Position = 0;
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.7.0-alpha.20201016.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET Framework 4.8
 - IDE and version : Visual Studio 16.7.5

**Comment by twsouthwick** [comment]
@seanmcc-msft

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
@twsouthwick I can reproduce this issue, and we will have a fix out soon.
