### ISSUE TITLE
[FEATURE REQ] CloudTable support for Azure.Data.Tables

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure/azure-sdk-for-net#16059]
Azure Functions uses CloudTable class from Microsoft.Azure.Cosmos.Table or Microsoft.WindowsAzure.Storage.Table for [input binding](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table-input?tabs=csharp-script#cloudtable-1) with Azure Storage Tables.

This class is missing in Azure.Data.Tables 3.0.0-beta.2 but should be implemented in Azure.Data.Tables going forward.
The Entity resolver for CloudTable expects Table entities to implement ITableEntity from Microsoft.Azure.Cosmos.Table

**Comment by jsquire** [comment]
//cc: @AlexGhiondea, for insight into plans for Azure Function binding updates.

**Comment by christothes** [comment]
closed via https://github.com/Azure/azure-sdk-for-net/issues/25342#issuecomment-1004454663
