### ISSUE TITLE
[QUERY] Accessing Azure app configuration from Azure function using SDK and not client library.

### ISSUE THREAD

**Issue by athrayee** [Azure/azure-sdk-for-net#16063]
I am accessing my configuration stored in Azure Appconfiguration. I am using SDK (Azure.Data.AppConfiguration) from Azure function. Following the example from https://github.com/Azure/azure-sdk-for-net/blob/Azure.Data.AppConfiguration_1.0.2/sdk/appconfiguration/Azure.Data.AppConfiguration/samples/Sample2_HelloWorldExtended.md

I am keep getting 400 error. The only difference is that I am calling from Azure Functions.

Following is my code

```csharp
 var client = new ConfigurationClient(_azureAppConfigurationOptions.ConnectionString);            
ConfigurationSetting setting = client.GetConfigurationSetting("appid");  
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

Any help or insight is appreciated.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by maririos** [comment]
Hi @athrayee what version of the Azure.Data.AppConfiguration library are you using?
Also, do you see more information returned with the exception? like the message or the error code for it?

**Comment by athrayee** [comment]
@maririos I am using  "Azure.Data.AppConfiguration" Version="1.0.2"

System.Private.CoreLib: Exception has been thrown by the target of an invocation. Azure.Data.AppConfiguration: Service request failed.

{"type":"https://azconfig.io/errors/invalid-argument","title":"Invalid request parameter 'key'","name":"key","detail":"key(0): Suffix and Full Text search is not supported","pos":0,"status":400}

**Comment by maririos** [comment]
Thanks for confirming. Do you see this while running locally the Azure Functions? or have you already deployed the function in Azure.
If you try to make the call outside of the Azure function does it worked?

I was following the tutorial here https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio and integrated our sample https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.Data.AppConfiguration/samples/Sample1_HelloWorld.md and was able to get the `ConfigurationSetting` back, so I am wondering what else could there be happening in your environment/configuration

**Comment by athrayee** [comment]
i am trying it locally and has not published the function app. i do have the app config published in Azure. Also, like i mentioned, it is only not working with SDK and followed the same example as the link. not sure if there is additional config. I am using Connection string, I am looking at it again and will update, but in the meantime if any direction would help.

**Comment by athrayee** [comment]
I'm still experiencing the issue. Is there anything that you are suggesting me to try out differently. @maririos

**Comment by athrayee** [comment]
@maririos just as an alternative, I tried with client library using

 "Microsoft.Extensions.Configuration;
 Microsoft.Extensions.Configuration.AzureAppConfiguration;

i am able to get the configuration value. just curious to understand why it would be different using SDK than client library.

**Comment by maririos** [comment]
@athrayee thank you for providing more information. What version of Azure Functions are you using?
This is the code I am using (by following both samples liked above):
```
public static class HttpExample
    {
        [FunctionName("HttpExample")]
        public static async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            log.LogInformation("C# HTTP trigger function processed a request.");
            var client = new ConfigurationClient(<connectionString>);
            
            string key = req.Query["key"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            key = key ?? data?.key;

            ConfigurationSetting retrievedSetting = client.GetConfigurationSetting(key);

            string responseMessage = string.IsNullOrEmpty(key)
                ? "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response."
                : $"Hello, {key} with value {retrievedSetting.Value}. This HTTP triggered function executed successfully.";

            return new OkObjectResult(responseMessage);
        }
    }
```

Using:
- AppConfig: Azure.Data.AppConfiguration Version="1.0.2"
- Azure functions: 3.0.14916.0

you can try it deployed here: https://mariariappconfig.azurewebsites.net/api/HttpExample?key=FontColor (notice that for the function to work in Azure I had to add information in `host.json` file and that is not included in the tutorial I linked)

you ok sharing more of your code (without keys or connection strings) to see what is happening?

**Comment by athrayee** [comment]
@maririos Thank you so much for your help. Please find my function code

 public async Task<HttpResponseMessage> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = "PostWebAppData")] HttpRequest req,
            ILogger log)
        {
             log.LogInformation($"{nameof(PostWebAppData)} trigger function processed a request.");

             log.LogInformation("test");

                   
            CancellationTokenSource source = new CancellationTokenSource();
            CancellationToken token = source.Token;


            var client = new ConfigurationClient(_azureAppConfigurationOptions.ConnectionString);

             //log.LogInformation($"{client} client value.");
            

            
           var  setting =  client.GetConfigurationSetting("appid"); 
            

               // log.LogInformation($"{setting}");


            if(!req.Headers.Keys.Contains("appid"))
            {

                return new HttpResponseMessage(System.Net.HttpStatusCode.NotAcceptable);

            }

            else
            {
                Microsoft.Extensions.Primitives.StringValues value = string.Empty;

                log.LogInformation(req.Headers.TryGetValue("appid",out value).ToString());

            var content = await new StreamReader(req.Body).ReadToEndAsync();
            

            byte[] b = Encoding.ASCII.GetBytes(content);
            MemoryStream ms = new MemoryStream(b);

            FileStream fs = req.Body as FileStream;

            log.LogInformation(content);

             var sasToken =
            _azureStorageTokenGenerator.GenerateSasToken(
                _azureStorageOptions.FilePath);

                log.LogInformation($"{_azureStorageOptions} storage options");

                 log.LogInformation($"{_azureStorageOptions.ConnectionString} storage options");

         //   var appid = _azureAppConfigurationOptions.Configuration["therasam:appid"];


            var appid = setting.Value;

            log.LogInformation($"{ appid }");
                     
            string continuationToken = null;

            var blobContainerClient = new BlobContainerClient(_azureStorageOptions.ConnectionString,_azureStorageOptions.FilePath);
        
            await blobContainerClient.SetAccessPolicyAsync(permissions:sasToken);

           var blobItems = blobContainerClient.GetBlobsAsync(prefix:"Data")
                        .AsPages(continuationToken,1);

                        BlobClient blb = blobContainerClient.GetBlobClient("test-blob");

                    log.LogInformation("upload");


                    Boolean overwrite = true;

                  //  CancellationTokenSource source = new CancellationTokenSource();
                  //  CancellationToken token = source.Token;


                        await blb.UploadAsync(ms, 
                            overwrite,
                            token);

                        log.LogInformation(blb.ToString());

           await foreach (BlobItem blob in blobContainerClient.GetBlobsAsync())
           {

                 log.LogInformation($"{blob.Name} blob name");

                 
                


                                   
               // log.LogInformation(uploadBlobContent.ETag.ToString());
           }              


            return new HttpResponseMessage(System.Net.HttpStatusCode.OK);

          // return new HttpResponseMessage(System.Net.HttpStatusCode.NoContent);
        }
        }

**Comment by AlexGhiondea** [comment]
@athrayee can you try the function that @maririos has pasted above? Trying to see if that simple function works first before looking into additional issues.
