### ISSUE TITLE
[FEATURE REQ]: Include Region Class from Fluent SDK in the Azure.ResourceManager SDK 

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure/azure-sdk-for-net#16060]
Fluent SDK has a very useful **Region** Class in Microsoft.Azure.Management.ResourceManager.Fluent.Core for Enumeration of the Azure datacenter regions.
This is missing in Azure.ResourceManager.Resources version 1.0.0-preview.2

**Comment by KalyanChanumolu-MSFT** [comment]
Related Issue [#15717](https://github.com/Azure/azure-sdk-for-net/issues/15717)

**Comment by allenjzhang** [comment]
Thank you for the request. This is in the backlog will be part of the next Track2 API preview.

/AB 4470

**Comment by JimSuplizio** [comment]
Hi @KalyanChanumolu-MSFT, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
