### ISSUE TITLE
Azure SDK should detect that I have AzureRM cmdlets installed and skip installing them

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-sdk-for-net#1607]
Azure SDK should detect that I have AzureRM cmdlets installed and skip installing them.
Currently if you have AzureRM cmdlets installed from PowerShell Gallery the SDK 2.8 will fail to install. It is better to detect that I have those cmdlets and not fail. May be the SDK can install the latest cmdlets from the PowerShell gallery instead of having its own installation. Probably cmdlets in PowerShell gallery will be updated in more frequent bases than the SDK itself.

**Comment by hovsepm** [comment]
@slavizh, please reopen the issue in the [powershell repository](https://github.com/Azure/azure-powershell). This repository contains management libraries and is not directly related to PowerShell.
