### ISSUE TITLE
[FEATURE REQ] Include resource group on models

### ISSUE THREAD

**Issue by riezebosch** [Azure/azure-sdk-for-net#16076]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
Compute
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

When using a `ListAllAsync` you receive a list of `VirtualMachine`s but you cannot do anything with it because all subsequent operations require the `resourceGroupName` and `vmName` parameters.

This probably applies to all other resource types as well.

Workaround:
I found a workaround by using the `Resources.StartDeleteByIdAsync` method on the `ResourcesManagementClient` and specifying the `api-version` myself.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by markcowl** [comment]
@m-nash Let's make sure we fully address this as part of the new preview

**Comment by ArthurMa1978** [comment]
The new sdk https://www.nuget.org/packages/Azure.ResourceManager.Compute/ support this
