### ISSUE TITLE
[BUG]Azure.Identity.CredentialUnavailableException: EnvironmentCredential authentication unavailable. Environment variables are not fully configured in Web app with User assigned MSI

### ISSUE THREAD

**Issue by TonySh127-ms** [Azure/azure-sdk-for-net#16079]
**Describe the bug**
Please provide the description of issue you're seeing.
The issue occurred after some deployments (when the app restarts). The issue could be fixed after few times app restarts. We would like to understand why we have to restart few times after this deployment

**Expected behavior**
What is the expected behavior?
It should not require the multiple restart after the resource deployment

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior? EnvironmentCredential.GetToken failure.
Similar issue https://github.com/Azure/azure-sdk-for-net/issues/11400#issuecomment-620179175
We have checked the environment variables have been defined "name": "AZURE_CLIENT_ID",

We have checked both the web app and AAD authentication. We cannot see the request sent to the server side. We would like to check the SDK side whether can find more information 
                        
**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create the web app with user assigned MSI
2. Run the web app and run under the Azure identity

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] Azure.Identity 1.2.0-preview.6 https://docs.microsoft.com/en-us/dotnet/api/azure.identity?view=azure-dotnet
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by TonySh127-ms** [comment]
Thanks @jsquire , please let me know if you need more information. Many thanks!

**Comment by TonySh127-ms** [comment]
Hi @schaabs , sorry to disturb you today, may I know whether can help to comment this issue? If you need more information from our side, please let me know. We can follow you suggestion to troubleshot it.

**Comment by Ozzian** [comment]
Stumbled upon the same issue. Trying to use managed identity via DefaultAzureCredentials to obtain a token for scope "https://management.core.windows.net/user_impersonation". Works locally (with visual studio), but with Azure Function where the Managed Identity is system assigned:

```
Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)
``` 

Rolled back to use AzureServiceTokenProvider for now

**Comment by daguito81** [comment]
Having the same problem. 
Unexpected error occurred (ClientAuthenticationError('DefaultAzureCredential failed to retrieve a token from the included credentials.\nAttempted credentials:\n\tEnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.\n\tManagedIdentityCredential: (None) An unexpected error occured while fetching the AAD Token.')). Handler shutting down.

This is intermittent and it's using System Managed Identity fo authentication. This is on a Linux Python Azure Function on consumption Plan

**Comment by christothes** [comment]
Hi @TonySh127-ms Can you confirm that all three required environment variables are defined? https://github.com/Azure/azure-sdk-for-net/tree/Azure.Identity_1.3.0/sdk/identity/Azure.Identity#environment-variables

Also, it appears that you are using an old version of the Azure.Identity client. Can you reproduce with the latest version, or the latest GA version (1.3.0)?

**Comment by senthiljack2808** [comment]
I am getting this following error ..while trying to create vnet.
Max retries 3 times exceeded. Error Details: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
ManagedIdentityCredential authentication unavailable. Connection to IMDS endpoint cannot be established, connect timed out.
SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
IntelliJ Authentication not available. Please log in with Azure Tools for IntelliJ plugin in the IDE.
Failed to read Vs Code credentials from Mac Native Key Chain.
AzureCliCredential authentication unavailable. Azure CLI not installed
