### ISSUE TITLE
[QUERY] Where is CloudBlobContainer.GetDirectoryReference(string relativeAddress) in Azure SDK12?

### ISSUE THREAD

**Issue by Syltty** [Azure/azure-sdk-for-net#16080]
**Query/Question**
Hi, I'm moving from Microsoft.Azure.Storage to Azure.Storage v12.
container
      ----> subdir1
                     ----> subdir1-1

So far I used container.GetDirectoryReference("subdir1") to list blobs from subdir1 without having subdir1-1 blobs.
Now I can't find anything to replace it. Did the logic change? 
Thank you.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.4.0
 - Hosting platform or OS and .NET runtime version: Windows 10 / netcoreapp3.1
 - IDE and version : Visual Studio 16.7.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @Syltty, if you are using a Hierarchical Namespace enabled account, I recommend using [Azure.Storage.Files.DataLake](https://www.nuget.org/packages/Azure.Storage.Files.DataLake) instead.  It has been designed specifically for HNS enabled accounts, and features Directory and File clients.

You can list files in a directory with the Data Lake SDK with `DataLakeFileSystemClient.GetPathsAsync(path = "[path to directory in question]");`  The equivalent in Blobs is `BlobContainerClient.GetBlobsByHierarchyAsync(prefix = "[path to virtual directory in question]");`

-Sean

**Comment by seanmcc-msft** [comment]
Please reopen if you have further questions.
