### ISSUE TITLE
LangVersion is set to preview for Track 2 libraries

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#16084]
I don't think we should be shipping libraries using preview compiler features.

Technically the preview and the latest is the same thing because we are not using the preview SDK but there is no point in keeping `<LangVersion>preview</LangVersion>`.

We should default to `8` and update to `9` when it comes out and we know what features we would like to consume.

@weshaggard, do you agree?

**Comment by weshaggard** [comment]
I agree we shouldn't be shipping any libraries with the preview compiler. However I think we should stick with having the LangVersion=latest as we have in our common props. See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version#c-language-version-reference as it states latest will allow you to use the latest release version minor.

**Comment by weshaggard** [comment]
https://github.com/Azure/azure-sdk-for-net/search?q=LangVersion

We should probably remove any reference to LangVersion preview. I don't recall why we set it at https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Directory.Build.Data.props#L138 but we should remove that and let https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Directory.Build.Data.props#L4 set the version to latest.

**Comment by pakrym** [comment]
I'm pretty sure it was for "await foreach"
