### ISSUE TITLE
Could not load file or assembly 'Azure.Core, Version=1.0.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by sirdank** [Azure/azure-sdk-for-net#16095]
**Describe the bug**
I receive a runtime error that crashes all my unit tests. I suspect it will crash my consuming applications also.

**Expected behavior**
I expect Azure.KeyVault.Secrets to accept versions of Azure.Core >= 1.0.2. My project currently references 1.2.3, which I do need, but gives the above error unless I explicitly install 1.0.2.

**Actual behavior (include Exception or Stack Trace)**
The runtime error:
Could not load file or assembly 'Azure.Core, Version=1.0.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot find the file specified.

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MyLibrary.Security.GetSecretsByTag(String tag) 

Fusion log:

 === Pre-bind state information ===
LOG: DisplayName = Azure.Core, Version=1.0.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8
 (Fully-specified)
LOG: Appbase = file:///C:/Users/sirdank/.nuget/packages/mstest.testadapter/1.4.0/build/_common
LOG: Initial PrivatePath = NULL
Calling assembly : Azure.Security.KeyVault.Secrets, Version=4.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8.
 ===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\git\MyLibrary\bin\net471\MyLibrary.IntegrationTests.dll.config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Azure.Core, Version=1.0.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8
LOG: Attempting download of new URL file:///C:/Users/sirdank/.nuget/packages/mstest.testadapter/1.4.0/build/_common/Azure.Core.DLL.
LOG: Attempting download of new URL file:///C:/Users/sirdank/.nuget/packages/mstest.testadapter/1.4.0/build/_common/Azure.Core/Azure.Core.DLL.
LOG: Attempting download of new URL file:///C:/Users/sirdank/.nuget/packages/mstest.testadapter/1.4.0/build/_common/Azure.Core.EXE.
LOG: Attempting download of new URL file:///C:/Users/sirdank/.nuget/packages/mstest.testadapter/1.4.0/build/_common/Azure.Core/Azure.Core.EXE.
LOG: Attempting download of new URL file:///C:/git/MyLibrary/bin/net471/Azure.Core.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Minor Version
LOG: Attempting download of new URL file:///C:/git/MyLibrary/bin/net471/Azure.Core/Azure.Core.DLL.
LOG: Attempting download of new URL file:///C:/git/MyLibrary/bin/net471/Azure.Core.EXE.
LOG: Attempting download of new URL file:///C:/git/MyLibrary/bin/net471/Azure.Core/Azure.Core.EXE.

**To Reproduce**
I have a multitargeted library like this `<TargetFrameworks>netstandard2.0;netcoreapp2.1;net471</TargetFrameworks>` with these references (among others):

		<PackageReference Include="Azure.Identity" Version="1.2.3" />
		<PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.1.0" />
		<PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.1.0" />
		<PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.1.0" />

**Environment:**
Visual Studio version is 16.7.6
dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Thank you!

**Comment by pakrym** [comment]
Hello, Can you check if `C:\git\MyLibrary\bin\net471\MyLibrary.IntegrationTests.dll.config` has any binding reddirects?

**Comment by sirdank** [comment]
Hi @pakrym, it does. Here is the full contents of that file:

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-12.0.0.0" newVersion="12.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
	<appSettings>
    <add key="TestSetting" value="AC456"/>
    <add key="TestSetting2" value="AC789"/>
	</appSettings>
</configuration>

**Comment by pakrym** [comment]
Can you please try adding the `<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>` to your test project and see if that helps?

**Comment by sirdank** [comment]
This is how the top of my test project .csproj looks:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net471;netcoreapp2.1</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>signingkey.snk</AssemblyOriginatorKeyFile>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
```

I deleted the bin folder and rebuilt but the .dll.config file is unchanged and I'm getting the same error:

> System.IO.FileNotFoundException: Could not load file or assembly 'Azure.Core, Version=1.0.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot find the file specified.

**Comment by sirdank** [comment]
This has got it working for me:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net471;netcoreapp2.1</TargetFrameworks>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>signingkey.snk</AssemblyOriginatorKeyFile>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
```
