### ISSUE TITLE
[BUG] Management Template Build Issue

### ISSUE THREAD

**Issue by dicolanl** [Azure/azure-sdk-for-net#16096]
**Describe the bug**
Please provide the description of issue you're seeing.
https://github.com/Azure/azure-sdk-for-net/blob/master/eng/templates/README.md using the template fails to build after creation.

**Expected behavior**
What is the expected behavior?
build works as expected

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
E:\azure-sdk-for-net\sdk\securityinsights\Microsoft.Azure.Management.SecurityInsights>dotnet build
Microsoft (R) Build Engine version 16.7.0+7fb82e5b2 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error : Value cannot be null. (Parameter 'folderName') [E:\azure-sdk-for-net\sdk\securityinsights\Microsoft.Azure.Management.SecurityInsights\Microsoft.Azure.Management.SecurityInsights.sln]

Build FAILED.

C:\Program Files\dotnet\sdk\3.1.403\NuGet.targets(128,5): error : Value cannot be null. (Parameter 'folderName') [E:\azure-sdk-for-net\sdk\securityinsights\Microsoft.Azure.Management.SecurityInsights\Microsoft.Azure.Management.SecurityInsights.sln]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.59

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Win 10 machine with pre-reqs
2. dotnet new azuremgmt --provider ResourceProviderName
3. dotnet build

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by markcowl** [comment]
@dicolani  Can you share what you are trying to do with the template, and also the link to Swagger?  The management templates are meant for Track 2 management libraries, which are still in preview, and not supported for Azure PowerShell cmdlets, so these may not be appropriate for your application.

If you did intend to use the management templates, then you will need to use the Azure.ResourceManager.* namespace.

**Comment by dicolanl** [comment]
@markcowl 
rest api spec is here https://github.com/Azure/azure-rest-api-specs/tree/master/specification/securityinsights/resource-manager
the goal is powershell cmdlets.  so it sounds like the template is not the right approach. instead we should mirror one of the other projects like "securitycenter".  correct?

**Comment by markcowl** [comment]
Sent (specific) instructions offline.  Closing this for now
