### ISSUE TITLE
AvroSerializer.Create should accept the Type

### ISSUE THREAD

**Issue by lennygran** [Azure/azure-sdk-for-net#1609]
Currently creating AvroSerializer does not accept the Type, but requires to define the type as T parameter. This limits usage of the serializer. Please add Create method to AvroSerializer class AvroSerializer.Create(Type type), and AvroSerializer.Create(Type type, AvroSerializerSettings settings).

**Comment by shahabhijeet** [comment]
@lennygran if you still encounter issue, please open a new issue.
