### ISSUE TITLE
Add pre-publish validation steps for nuget package

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#16094]
- [ ] Verify binaries and packages are signed
- [ ] Verify the package name matches our guidelines
- [ ] Verify that we are not shipping Debug binaries
- [ ] Verify we have a package description 
- [ ] Verify that we have a link to the project
- [ ] Verify the package dependencies are allowed. In particular for our track 2 packages there is a limited set of dependencies we allow, we want to ensure we don't accidently depend on something we shouldn't. 

Note that most of these are automatically handled by the nature of our primary release pipeline but we don't do any verification in our partner release pipelines and so this is more about that validation.

**Comment by kurtzeborn** [comment]
@chidozieononiwu, pretty sure we do most of these things already. We've had some partners request that we double check that we are doing all of the things in this list in .NET releases.

**Comment by JimSuplizio** [comment]
Hi @weshaggard, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
