### ISSUE TITLE
[FEATURE REQ] Add Container Instances to new management libraries

### ISSUE THREAD

**Issue by riezebosch** [Azure/azure-sdk-for-net#16110]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 

I expected them to be part of `Azure.ResourceManager.Compute` but the only container related operations there are `ContainerService` what seems to be pointing towards `AKS`.
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

Manage container instances with the new libraries.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by markcowl** [comment]
@nickzhums Assigning to you so we can track requests for specific library support in Track 2 SDKs

**Comment by nickzhums** [comment]
@markcowl yep, thanks for notifying me!

**Comment by nickzhums** [comment]
@riezebosch we are working on releasing the next set of .NET SDKs however we are also re-designing some of the library APIs to make it more user friendly, so it could take a little bit time. Could you share a bit on your guys timeline / when do you need this package?

**Comment by riezebosch** [comment]
ASAP 🙈 But I've got me a solution for now by using embedded ARM templates for deployment with the `ResourcesManagementClient` and querying using custom filters instead.

**Comment by nickzhums** [comment]
@riezebosch thanks. We'll take this into consideration for planning the future roadmap. Glad you found a solution.
In case if it's urgent, you can choose to use [this package instead](https://www.nuget.org/packages/Microsoft.Azure.Management.ContainerInstance.Fluent/)

May I ask how you found `Azure.ResourceManager.*` packages at first place?

**Comment by riezebosch** [comment]
Probably from the `README` of this repository but no idea how I stumbled upon that one.

**Comment by nickzhums** [comment]
@riezebosch thanks!

**Comment by ArthurMa1978** [comment]
Here is the new library for Container Instances: https://www.nuget.org/packages/Azure.ResourceManager.ContainerInstance/
