### ISSUE TITLE
[BUG] Identity: Cannot authenticate against EventHub unless using interactive credentials

### ISSUE THREAD

**Issue by mydiemho** [Azure/azure-sdk-for-net#16115]
**Describe the bug**

When I create an EventHubProducerClient without setting `includeInteractiveCredentials = true`, my code is getting unauthenticated error when I try to send events.  I have verified that I am login via `az login` and was able to run `az account get-access-token --resource https://vault.azure.net`

Here's some of the stacktrace error

```
DefaultAzureCredential failed to retrieve a token from the included credentials.
EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
ManagedIdentityCredential authentication unavailable, no managed identity endpoint found.
SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
```

**Expected behavior**
Code should use the credentials stored when I ran `az login`

**Actual behavior (include Exception or Stack Trace)**
No prompt asking for credentials when nothing is found.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create producer client without interactiveCredentials, see failure
 `eventHubProducerClient = new EventHubProducerClient(eventHubFQDN, eventHubName, new DefaultAzureCredential());`

2. Create producer client with interactiveCrendentials
` eventHubProducerClient = new EventHubProducerClient(eventHubFQDN, eventHubName, new DefaultAzureCredential(true));`

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
    
`<PackageReference Include="Azure.Messaging.EventHubs" Version="5.1.0" />`

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]

```
➜ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.402/

Host (useful for support):
  Version: 3.1.8
  Commit:  9c1330dedd

.NET Core SDKs installed:
  2.2.106 [/usr/local/share/dotnet/sdk]
  3.1.100 [/usr/local/share/dotnet/sdk]
  3.1.401 [/usr/local/share/dotnet/sdk]
  3.1.402 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

 - IDE and version : [e.g. Visual Studio 16.3]
`Jetbrains Rider`

**Comment by jsquire** [comment]
Hi @mydiemho.  Thank you for reaching out and we regret that you're experiencing difficulties.   I've routed this over to @schaabs for his insight into the identity component of this.  I'll continue to monitor and take over if this crosses over into Event Hubs areas.

**Comment by mydiemho** [comment]
That was it! Upgrading to the latest version fix the issue.  Thanks for all your help :D
