### ISSUE TITLE
Calling Tags.Add on a ResourceManagementClient object will fail if resource has no tags

### ISSUE THREAD

**Issue by josefehse** [Azure/azure-sdk-for-net#16120]
When calling Tags.Add on a ResourceManagementClient object, it will fail if resource has no tags. If the resource already has tags, the method runs fine.
Is that expected behaviour? Is there a need to initialize tags prior to using this method?

**Environment:**
 - Microsoft.Azure.Management.ResourceManager 3.10-preview
 - Local Windows 10 netcoreapp2.1 Console App
![sdk_error](https://user-images.githubusercontent.com/13967863/96630523-26a29f00-12e3-11eb-85af-fe65e3768804.png)
- Visual Studio 2019 community 16.7.6

**Comment by jongio** [comment]
@nickzhums

**Comment by nickzhums** [comment]
@m-nash @markcowl to provide accurate answer since Allen is OOF, thanks

**Comment by YalinLi0312** [comment]
@josefehse This is expected, you must check if the tag is null in model object. And this problem is being addressed in Track 2 management libraries.
