### ISSUE TITLE
[BUG] Microsoft.Azure.Management.NetApp@1.7.0 fails to create volume with ThroughputMibps set

### ISSUE THREAD

**Issue by brandonmichelsen** [Azure/azure-sdk-for-net#16122]
**Describe the bug**
ThroughputMibps cannot be set when creating ANF Volume

**Expected behavior**
Volume is created with ThroughputMibps set correctly

**Actual behavior (include Exception or Stack Trace)**
Exception is thrown

```
Microsoft.Rest.ValidationException: 'ThroughputMibps' has to be multiple of '0.001'.
	at Microsoft.Azure.Management.NetApp.Models.Volume.Validate()
	at Microsoft.Azure.Management.NetApp.VolumesOperations.BeginCreateOrUpdateWithHttpMessagesAsync(Volume body, String resourceGroupName, String accountName, String poolName, String volumeName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
	at Microsoft.Azure.Management.NetApp.VolumesOperations.CreateOrUpdateWithHttpMessagesAsync(Volume body, String resourceGroupName, String accountName, String poolName, String volumeName, Dictionary`2 customHeaders, CancellationToken cancellationToken)
```

**To Reproduce**
The following code, independent of the throughput being used results in the exception being raised

```csharp
var volume = new Microsoft.Azure.Management.NetApp.Models.Volume
{
	CreationToken = "validVolumeName",
	Location = "centralus",
	SubnetId = "<subnetId>",
	UsageThreshold = 4TiB,
	ProtocolTypes = new[] { "NFSv4.1" },
	ServiceLevel = ServiceLevel.Ultra,
	SecurityStyle = "unix",
	ThroughputMibps = 512.0d,
	SnapshotDirectoryVisible = false,
	KerberosEnabled = false
};

// throws error
var tenantVolumeResponse = await netappClient.Volumes.CreateOrUpdateWithHttpMessagesAsync(
	volume,
	"resourceGropuName",
	"accountName",
	"capacityPoolName",
	"validVolumeName",
	cancellationToken: token
);
```

**Environment:**
 Package: Microsoft.Azure.Management.NetApp@1.7.0
 
.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.302/
 
VSCode 1.49.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by timMSFT** [comment]
@meeraharidasa @lilyjma - Can you route to the NetApp owner?

**Comment by meeraharidasa** [comment]
@timMSFT we don't currently have routing support for NetApp

**Comment by audunn** [comment]
Just to chime in here I believe this was fixed in 1.8.0

**Comment by jaylabell** [comment]
Coming back as a New issue in Compute Review. Let's make sure there is a resolve. 

@audunn -  Do you mind validating that this issue was fixed before we close it out?

**Comment by audunn** [comment]
@jaylabell Yes, this issue has been fixed.
