### ISSUE TITLE
Node 13 still required?

### ISSUE THREAD

**Issue by craigktreasure** [Azure/azure-sdk-for-net#16124]
**Query/Question**

The contributor guide says that Node 13 is required. Is that still the case? Node 13 appears to have fallen out of favor, which can make it difficult for users to find. Do newer versions (14 or 15) work?

**Comment by pakrym** [comment]
14 should work, I have a PR updating autorest C# repo itself https://github.com/Azure/autorest.csharp/pull/933 when that one is in I'll update the contributor guide
