### ISSUE TITLE
[Functions Service Bus Binding] MaxConcurrentCalls not working

### ISSUE THREAD

**Issue by kosnkow** [Azure/azure-sdk-for-net#16148]
i have {
  "version": "2.0",
  "extensions": {
    "serviceBus": {
      "messageHandlerOptions": {
        "maxConcurrentCalls": 1
      }
    }
  }
}

and 10 messages in service bus and the function alwasy starts processing all messages paralell despite "maxConcurrentCalls": 1 , instance is also set to 1 (this is local testing) but the same is on azure

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by kosnkow** [comment]
IT works i double checked but when session is disabled.

sob., 13 mar 2021, 17:05 użytkownik msftbot[bot] ***@***.***>
napisał:

**Comment by AlexGhiondea** [comment]
@kosnkow is this addressed now?
