### ISSUE TITLE
[FEATURE REQ] Please Open up AddAzureKeyVault or allow InsertAzureKeyVault

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/azure-sdk-for-net#16149]
**Library or service name.**
Azure.Security.KeyVault.Secrets + Azure.Extensions.AspNetCore.Configuration.Secrets
 
**Is your feature request related to a problem? Please describe.**
Right now it's impossible to specify the order that the Azure Keyvault secrets should be put in when adding Keyvault configuration. This makes it difficult to override with environment variables etc. which should always take precedence in the environment and often is outright required like in k8s.

So either we need to have what AddAzureKeyVault does made fully public instead of it all being internal classes, or we need an index property that does an insert instead of an add in that case on all overloads of AddAzureKeyVault or an InsertAzureKeyVault extension method that does the same as Add but allows you to specify where in the hierarchy.

In general both would be desirable as there's little reason for these to be internal only.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/19788
