### ISSUE TITLE
[FEATURE REQ] Expose refresh interval in AzureKeyVaultConfigurationProvider

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/azure-sdk-for-net#16150]
**Azure.Extensions.AspNetCore.Configuration.Secrets**
 
The internals of `AzureKeyVaultConfigurationProvider` support a refresh interval for polling against KeyVault, yet there's no way to actually set that value from the public API, due to the provider being `internal` and it seems the value is null by default (don't reload).

https://github.com/Azure/azure-sdk-for-net/blob/766d3c354ce4b35e4086be90cf9167f21f4062d1/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationProvider.cs#L33

Our use case is that we store a token in KeyVault that is used by our web app and that needs refreshing once a day. I have built a Azure function that refreshes this token well before the expiration. I would like this updated token to be available to my web app, using the `AzureKeyVaultConfigurationProvider`. This won't work if the provider doesn't fetch the newly updated secret from KeyVault though.

Am I missing something or is this not possible yet?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Thank you for the report. Seems we have missed this API when migrating the library.

**Comment by pakrym** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/16254

**Comment by BrianVallelunga** [comment]
Thanks!
