### ISSUE TITLE
JsonWebKey from the Library is not compliant with IETF

### ISSUE THREAD

**Issue by maxonweb** [Azure/azure-sdk-for-net#16155]
**Question:**
Azure.Security.KeyVault.Keys.JsonWebKey returned from the Library as per https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.keyvaultkey.key?view=azure-dotnet does not have kty, kid, key_ops properties for e.g., 

IETF Link: https://tools.ietf.org/html/rfc7517

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
@heaths:  I'm not sure if this is better routed to the service team.  Would you be so kind as to triage and redirect if needed?

**Comment by heaths** [comment]
Those properties are serialized according to the spec, but have different names across our SDKs following idiomatic language conventions. For .NET:

* `kty` -> `JsonWebKey.KeyType`
* `kid` -> `JsonWebKey.Id`
* `key_ops` -> `JsonWebKey.KeyOps`

Other key parameters like `k` remain the same, though are cased idiomatically for the language, e.g. in .NET `K`.

Have you found a case where properties are not serialized to or from the Key Vault service correctly?

**Comment by maxonweb** [comment]
Which I can understand, but when I convert the Azure.Security.KeyVault.Keys.JsonWebKey object to Json, I expect the JSON produced to be IETF compliant. So with properties name KeyType, Id, KeyOps in the JSON it is not a IETF compliant JWK.

**Comment by heaths** [comment]
How are you converting it? Note we don't currently support serializing the JWK outside the SDK. When de/serialized within the SDK (like importing to or getting a key from Key Vault), then JWK is formatted correctly.

**Comment by maxonweb** [comment]
If I am not able to get a IETF compliant JSON out of the JsonWebKey object I am not going call it as IETF compliant. The previous library Microsoft.Azure.KeyVault.WebKey ToString() method used to produce JSON which was IETF compliant. This new library Azure.Security does not exhibit the same behavior - https://docs.microsoft.com/en-gb/dotnet/api/microsoft.azure.keyvault.webkey.jsonwebkey.tostring?view=azure-dotnet-legacy#Microsoft_Azure_KeyVault_WebKey_JsonWebKey_ToString

I was able to do

`new Microsoft.IdentityModel.Tokens.JsonWebKeySet(Microsoft.Azure.KeyVault.WebKey.ToString()) `

which does not work the same way in this new library, when I do

`new Microsoft.IdentityModel.Tokens.JsonWebKeySet(Azure.Security.KeyVault.Keys.JsonWebKey.ToString())`

Reference:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.jsonwebkeyset.-ctor?view=azure-dotnet#Microsoft_IdentityModel_Tokens_JsonWebKeySet__ctor_System_String_

**Comment by heaths** [comment]
Note: see https://datatracker.ietf.org/doc/html/rfc7517
