### ISSUE TITLE
Unable to use the SBSuscription.ForwardTo property to forward messages to another Topic

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-sdk-for-net#16174]
**Describe the bug**

Unable to use the SBSuscription.ForwardTo property to forward messages to another Topic.
Both source and target topics are in the same service bus namespace.

**Expected behavior**

It should just work 🙏

**Actual behavior (include Exception or Stack Trace)**

```
{
    "error": {
        "code": "LinkedAuthorizationFailed",
        "message": "The client '<client-id>' ... has permission to perform action 'write' on scope
        '/subscriptions/<subscription-id>/resourceGroups/service-bus/providers/Microsoft.ServiceBus/namespaces/<namespace-name>/topics/<topic-name>/subscriptions/<subscription-name>';
        however, it does not have permission to perform action 'write' on the linked scope(s)
        '/subscriptions/<subscription-id>/resourceGroups/service-bus/providers/Microsoft.ServiceBus/queues/<forwarded-to-topic-name>'
        or the linked scope(s) are invalid."
    }
}
```

Please, note the `/queues/<forwarded-to-topic-name>` section in the error message.
For the record, I tried forwarding to Service Bus Queue instead, but with no success.
I also tried `<namespace-name>/<forwarded-topic-name` with no avail.

**To Reproduce**

```
await client.Subscriptions.CreateOrUpdateAsync(
    resourceGroupName,
    namespaceName,
    topicName,
    subscriptionName,
    SBSubscription = new SBSubscription
    {
        ForwardTo = ForwardedToTopicName,
    },
    cancellationToken
);
```

**Environment:**
 - `<PackageReference Include="Microsoft.Azure.Management.ServiceBus" Version="2.1.0" />`
 - Windows 10 - .net core 3.1
SDK .NET Core (reflétant tous les global.json) :
 Version:   3.1.403
 Commit:    9e895200cd

Environnement d'exécution :
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   c:\program files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.401 [c:\program files\dotnet\sdk]
  3.1.403 [c:\program files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [c:\program files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [c:\program files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [c:\program files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [c:\program files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by axisc** [comment]
@springcomp this seems to be a permissioning issue. Do you have the management permissions to perform the operation?

**Comment by springcomp** [comment]
@axisc, I do have permissions. This is part of a program that uses the management library with a service principal with `Service Bus Data Owner` role. I reverted to using another Service Bus library for the specific purpose of setting the `ForwardTo` property. The program otherwise creates topics, subscriptions, rules successfully. It also succeeds in setting the `ForwardDeadLetteredMessagesTo` property.

Here is a portion of the code that does not work:

```
dotnet add package Microsoft.Azure.Management.ServiceBus --version 2.1.0
```

```
IServiceBusManagementClient client;
…
try
{
    var sbSubscription = new SBSubscription
    {
        ForwardTo = $"{SB_NAMESPACE}/{UNPROCESSED_MESSAGES_TOPIC_NAME}",
    };
    await client.Subscriptions.CreateOrUpdateAsync(
        RESOURCE_GROUP_NAME,
        SB_NAMESPACE,
        TOPIC_NAME,
        SUB_NAME,
        sbSubscription,
        cancellationToken
    );
}
catch (ErrorResponseException e)
{
    Console.WriteLine(e.Response.ReasonPhrase);
    throw;
}
```

The error response in that case is a simple `Bad Request`. However, if I try the same operation as part of creating the subscription in a single call, the errror message is a bit clearer:

```
{"error":{"code":"LinkedInvalidPropertyId","message":"Property id 'servicebus-namespace/unprocessed' at path 'properties.forwardTo' is invalid. Expect either resource name e.g. 'myResource' or qualified resource name e.g. 'myParent/myResource'."}}
Unhandled exception. Microsoft.Azure.Management.ServiceBus.Models.ErrorResponseException: Operation returned an invalid status code 'BadRequest'
```
I have tried with an unqualified name without the namespace prefix, but with the same error.

For the record, here is a portion of the code that works:

```
dotnet add package Microsoft.Azure.ServiceBus --version 5.0.0
```

```
var description = new Microsoft.Azure.ServiceBus.Management.SubscriptionDescription(TOPIC_NAME, SUB_ NAME)
{
    ForwardTo = UNPROCESSED_MESSAGES_TOPIC_NAME,
};
var management = new Microsoft.Azure.ServiceBus.Management.ManagementClient(CONNECTION_STRING);
await management.UpdateSubscriptionAsync(description, cancellationToken);
```

**Comment by axisc** [comment]
@springcomp  - in that case, please open a support ticket - we can then investigate on the backend.

**Comment by TWolverson** [comment]
@springcomp We appear to have the same problem as your last update, emitting an error with code `LinkedInvalidPropertyId` with the same error message. Did you open a ticket as requested, and did you find a resolution?

Thanks.

**Comment by springcomp** [comment]
@TWolverson unfortunately I did not have the time to pursue and open a ticket.
