### ISSUE TITLE
Azure KeyVault is broken

### ISSUE THREAD

**Issue by cmatskas** [Azure/azure-sdk-for-net#1619]
@anurse @cbilson @paulbatum @Porges @johndeu 

Trying to run the Azure KeyVault sample app but it's currently broken. I forked the SDK in an effort to resolve the problem but as it turns out the whole KeyVault solution is broken. I've managed to get most of the projects to work but the main test one is still broken due to references to dlls and NuGet packages that don't exist anymore. 

I would like to get this fixed but I'll need help from the team. Could anyone ping me some details so that we can take this further?

I could commit my changes and send a PR with the current state of the project so that we can use this as the basis. (only 16 errors down from ~1K)

In addition, is this service still actively maintained by the Azure team or is it something that may soon be dropped due to the luck of interest? 

A response/help would be greatly appreciated.

**Comment by devigned** [comment]
Azure Key Vault isn't going away. Key Vault is a core security component in Azure.

Per the Key Vault solution not building, @mayurid we need someone from the our or the Key Vault team to take a look at this. There's no reason solutions in the project shouldn't build.

**Comment by devigned** [comment]
@Azure/adx-sdk-team any ideas on why @cmatskas is experiencing this?

**Comment by cmatskas** [comment]
Hi @devigned,

Thanks for getting back to me. There were a lot of packages missing from the package configure and it took the best of 2 hours to figure out what to restore/add to get the solution to build. 

In the end, the only thing failing to build is the KeyVault.Tests project and that's because it references Microsoft.Azure.Test.Framework which has since been pulled from NuGet. This missing library seems to be used heavily to bootstrap the tests so it's a vital piece and not something I would like/could remove on my own.

However, since I have a personal and professional interest in this project, I would like to work with the team to make KeyVault functional again.

I have committed all the changes on my fork so I could do a PR to save the team time and effort in getting at a good state and focus on the stuff that are truly broken.

Happy to help and be part of the community

**Comment by cmatskas** [comment]
Morning  @Azure/adx-sdk-team Any news/progress on this?

**Comment by herveyw** [comment]
This was fine recently, I published an update to KeyVault.Extensions. We'll take a look to see what has broken.

**Comment by cmatskas** [comment]
Hi @herveyw, I did a pull and tried to built the solution in VS2015 Update 1 RC. The NuGet packages failed to download and there were many references missing from the package.json on each project under the solution. 

I had to use NuGet Command Line to install the missing packages and in the end, I was able to built all projects apart from the KeyVault.Test project. This one relies on a NuGet package no longer available (it was a beta anyway).

Is there anything I can do to help? Would a PR be useful to generate a delta between what's currently checked in and the stuff I committed to fix the build? Or did I totally screw up on my end? Thanks

**Comment by herveyw** [comment]
@cmatskas: master branch seems to build cleanly for me from both command line and VS 2013, including after I have deleted all my local packages and had VS restore; it also built cleanly on the Jenkins build server when I last published. However, I still have to check the package sources on my development machine.

**Comment by cmatskas** [comment]
@herveyw Did you run the unit tests?

**Comment by herveyw** [comment]
I built and ran the crypto tests but not the main tests as I don't have that set up at present, one of my colleagues should have that working as we have some updates pending, I'll check with him.

**Comment by herveyw** [comment]
@cmatskas tests cases (except HSM, as I have a standard vault) are working for a colleague and for me from VS2013. We're continuing to investigate.

**Comment by cmatskas** [comment]
@herveyw I was able to do a fresh fork and build on VS2013 without changing anything. There's definitely an issue with VS2015 so maybe we could look into this as well?

**Comment by cmatskas** [comment]
@devigned @herveyw any progress on this issue?

**Comment by herveyw** [comment]
@cmatskas Just getting back to this on a completely clean machine with VS2015 Update 1. What I see going on in VS2015 is that the Nuget package manager isn't restoring the packages to the expected location in the packages directory at the root of the SDK, instead it seems to be installing them to a packages folder next to the solution file. This causes all the assembly references in the key vault project files to be broken. After a cmd line build of the SDK, the root level packages folder exists and the Key Vault projects almost all build barring one warning in KeyVault.Extensions.Test. I'm investigating and will update here as I have news.

**Comment by cmatskas** [comment]
@herveyw the problem is that the KeyVault.Extensions.Test was a temp NuGet package that was created to support the unit tests by simulating stuff (my assumption). It would be nice to be able to download the full suite and run the tests locally. That package has now been discontinued and is not available on the NuGet server

**Comment by herveyw** [comment]
@cmatskas I doubt that KeyVault.Extensions.Test was ever published to NuGet, it's a unit test and doesn't build a NuGet package. During December and January, Extensions.Test grew some additional test cases that were not initially integrated with the Record/Playback model of the SDK but it was updated recently and can now run locally. I don't think this has anything to do with the build errors that I am seeing when opening VS 2015 Update 1 against the KeyVault.sln without having previously built the SDK from the command line.

**Comment by herveyw** [comment]
@cmatskas @hovsepm @Azure/adx-sdk-team Build failures with VS 2015 do not seem to be KeyVault specific, the other projects in the SDK also fail to build with the same symptoms as KeyVault: $LibraryNugetPackageFolder is not getting resolved correctly _unless_ you have already done a command line build of the SDK.

**Comment by markcowl** [comment]
### Description
Verify the build of all packages in the latest VS2015, correct any errors

### Cost: 2
