### ISSUE TITLE
May be Key vault SDK issue

### ISSUE THREAD

**Issue by worlin** [Azure/azure-sdk-for-net#16205]
**Query/Question**
How can we help?
Cx used app service which was coded by key vault SDK to get key vault secret.
Cx used app service to get key vault secret.
Uploaded Image
![image](https://user-images.githubusercontent.com/73322628/96948645-bbdaa900-1518-11eb-870f-45a4c7913546.png)

Uploaded Image
![image](https://user-images.githubusercontent.com/73322628/96948667-c4cb7a80-1518-11eb-9608-40104bde2391.png)

From August to now, cx got many dependency failures every day.
Uploaded Image
![image](https://user-images.githubusercontent.com/73322628/96948758-f0e6fb80-1518-11eb-902c-94f3863635cf.png)

Checked sample key vault logs, there are two 401 code returned, but the final results are successful.
Uploaded Image
![image](https://user-images.githubusercontent.com/73322628/96948765-f6dcdc80-1518-11eb-81d5-22918aae6ea4.png)

For the two 401 errors, we checked MSI ESTS logs and app service logs.

![image](https://user-images.githubusercontent.com/73322628/96948800-078d5280-1519-11eb-8ecf-c62a03c238c0.png)

![image](https://user-images.githubusercontent.com/73322628/96948815-0c520680-1519-11eb-8332-4cf1f76f7bde.png)
![image](https://user-images.githubusercontent.com/73322628/96948838-170c9b80-1519-11eb-8af8-02289886b8a3.png)

There are no findings from azmsicl logs.
Since it happens intermittently, we cannot get fiddler trace.

As key vault product team suggested, this may be azure key vault SDK issue. I was wondering if this is related to SDK issue.
**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8] app service
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Key Vault itself will issue HTTP 401 responses to authenticate a caller, which contain a challenge that must be authenticated and returned; however, that URI is not from Key Vault directly. @schaabs do you recognize the endpoint or URI here? Is this MSI that is failing?

Also, please note that Microsoft.Azure.KeyVault is now deprecated. We recommend upgrading to Azure.Security.KeyVault.Secrets for secret management, which along with [Azure.Extensions.AspNetCore.Configuration.Secrets](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets) (or similar libraries) not only offers easier configuration, but [DefaultAzureCredential](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/identity/Azure.Identity#defaultazurecredential) from the Azure.Identity package that works for development and production environments.
