### ISSUE TITLE
[Question] Azure Storage Queue run multiple GetMessagesAsync concurrently take longer time than expected

### ISSUE THREAD

**Issue by ExileLee** [Azure/azure-sdk-for-net#16209]
**Question**
We use Azure Storage Queue to do some daily job
when schedule job (for example Azure Function、AWS Lambda) lunch need to pull all message from queue

we run multiple task to batch all message concurrently 

```   .......
     var getMessageTasks = Enumerable.Range(1, batchCount).Select(x => queue.GetMessagesAsync(32));
     var tasksResult = await Task.WhenAll(getMessageTasks);
     .......
```

**but we encounter pull duplicate message occasionally**
when we Inspect logs we found that await `await Task.WhenAll(getMessageTasks);` take longer time than we expected (only 64 message take 1 min)
maybe the reason is that first batch task take longer time(maybe network latency) than visibility timeout(default 30s), so that second task pull same message again

but when change below code everything works fine
every GetMessagesAsync call was fast (100ms)
```
       .....
        for (int currentSize = allMessageSize; currentSize> 0 ; currentSize -= 32)
        {
            int processSize = Math.Min(currentSize, 32);
            var batchQueue = await queue.GetMessagesAsync(processSize);
            queueMessages.AddRange(batchQueue);
        }
        .....
```

**Environment:**
 -  WindowsAzure.Storage 7.2.1
 -  .NET Core 2.1
 -  Runtime Environment: AWS Lambda(OS: Linux)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @ExileLee, WindowsAzure.Storage 7.2.1 is no longer supported, I recommend moving to [Azure.Storage.Queues](https://www.nuget.org/packages/Azure.Storage.Queues/12.5.0-preview.1).

Looking at your code snippet, how many network calls are actually being made?  I believe you should be able to retrieve all 32 message in a single REST call.

**Comment by amishra-dev** [comment]
Please reactivate if you are still facing this issue.
