### ISSUE TITLE
[QUERY] How to mock BlobItem ?

### ISSUE THREAD

**Issue by marcino239** [Azure/azure-sdk-for-net#16253]
**Query/Question**
How to mock BlobItem class? It has internal constructor and internal property setters.

**Environment:**
 - Azure Storage 12.6.0
 - OS: Ubuntu 18.04 and .NET runtime version: 3?.1.4
 - IDE: Vscode

Thanks!

**Comment by jsquire** [comment]
Hi @marcino239.  Thank you for reaching out and we regret that you're experiencing difficulties.   `BlobItem`, as well as the other model types, can be mocked using the [`BlobsModelFactory`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Models/BlobsModelFactory.cs#L756).

**Comment by marcino239** [comment]
Fantastic @jsquire - thank you so much for quick response!

**Comment by IanKemp** [comment]
Please can this information be included in https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/ ?
