### ISSUE TITLE
[FEATURE REQ] Azure.Identity lacks OnBehalfOf flow

### ISSUE THREAD

**Issue by pwlodek** [Azure/azure-sdk-for-net#16264]
**Azure.Identity**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
 
**Is your feature request related to a problem? Please describe.**

Looking at Credential Classes [here](https://github.com/Azure/azure-sdk-for-net/tree/6858e819428a0e247b305cf5f27fcae3d08a8aa6/sdk/identity/Azure.Identity#credential-classes) I see important flow is missing: On Behalf Of (OBO). I have a case where a public client authenticates against Azure AD using Interactive way and obtains JWT token to talk to Web API, but inside the web api I would like to gain access to Azure Data Lake as a calling user to get advantage of build ACL mechanism. To do that I have to use [OBO flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow). Currently no such credential exists to support this scenario and I have to implement it myself.

There needs to be Azure.Identity credential implemented that makes use of MSAL confidential client AcquireTokenOnBehalfOf method.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pwlodek** [comment]
To make sure this is clear, when the public client authenticates to Azure AD to get JWT token to speak to the Web API, the "aud" claim of the token is set to the WebAPI. I need to get new token on the web api side on behalf of the calling user, to get JWT token with "aud" claim set to "https://storage.azure.com". Hope this makes sense.

**Comment by schaabs** [comment]
@pwlodek  Thanks for the feedback. Adding support for the on behalf of authentication flow is currently on the backlog for the Azure.Identity library. I'm not 100% sure when we will be adding this feature, but I suspect it will be sometime early next year. In the meantime you will need to create your own `TokenCredential` implementation. Here's an example which implements a `TokenCredential` to authenticate with the OBO flow using the `IConfidentialClientApplication` from MSAL. 

```C#
public class OnBehalfOfCredential : TokenCredential
{
    private readonly IConfidentialClientApplication _confidentialClient;
    private readonly UserAssertion _userAssertion;

    public OnBehalfOfCredential(string clientId, string clientSecret, string userAccessToken)
    {
        _confidentialClient = ConfidentialClientApplicationBuilder.Create(clientId).WithClientSecret(clientSecret).Build();

        _userAssertion = new UserAssertion(userAccessToken);
    }

    public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
    {
        return GetTokenAsync(requestContext, cancellationToken).GetAwaiter().GetResult();
    }

    public override async ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
    {
        AuthenticationResult result = await _confidentialClient.AcquireTokenOnBehalfOf(requestContext.Scopes, _userAssertion).ExecuteAsync();

        return new AccessToken(result.AccessToken, result.ExpiresOn);
    }
}
```

You can use an instance  to authenticate a `BlobClient`. Keep in mind that this credential (at least as it's coded above) will only be valid while the specified `userAccessToken` is valid.

```C#
var oboCredential = new OnBehalfOfCredential(clientId, clientSecret, userAccessToken);

var client = new BlobClient(new Uri("https://myaccount.blob.core.windows.net/mycontainer/myblob"), oboCredential);
```

Hope this helps. Please let me know if you have further questions or you have trouble getting the sample working.

**Comment by pwlodek** [comment]
yeah I came of with similar code, but thanks for the confirmation. Of course this works. To your comment that the above will work only when the user token is valid, isnt that assumed by the OBO itself? You have to have valid token to act upon it, right? Unless you have a refresh token of the original token, but how would you get it inside "the backend" since the user token comes from HTTP Authorization token? You would have to pass it yourself, which then it makes your solution sort of custom from the security point of view. Unless I am missing something ;-)

**Comment by pwlodek** [comment]
@schaabs Also a different question but related to OBO, why OBO doesn't work with access tokens for apps (ie. tokens obtained by client credential flow). Seems like an app (backend service) can't act on behalf of another application, it can only act on behalf of a user. Is there an explanation for that?
