### ISSUE TITLE
[BUG] Microsoft.Azure.Management.StreamAnalytics uses an old REST API version  

### ISSUE THREAD

**Issue by shivan19** [Azure/azure-sdk-for-net#16304]
**Describe the bug**
I'm trying to create an ASA job with managed identity and while I was trying to use Microsoft.Azure.Management.StreamAnalytics SDK, I figured it points to the 2016 version of ASA's REST API.

**Expected behavior**
To be able to specify the API version or update the SDK to refer to the later version, if possible.

**Actual behavior (include Exception or Stack Trace)**
A call is made to the 2016 version of the API instead of 2017 (which supports managed identities).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by shivan19** [comment]
@jsquire: I do see a pull request that was merged in. (https://github.com/Azure/azure-sdk-for-net/pull/15198).
Is it the case that the nuget package has not been updated? I'm trying to find a work around to v2.1.0.

**Comment by YalinLi0312** [comment]
This sdk package version 3.0.0 preview(https://www.nuget.org/packages/Microsoft.Azure.Management.StreamAnalytics/3.0.0-preview) uses API version 2020-03-01-preview which should have the feature you are looking for.
