### ISSUE TITLE
FromConnectionString method for StorageSharedKeyCredential

### ISSUE THREAD

**Issue by j055** [Azure/azure-sdk-for-net#16308]
**Library or service name.**
Azure.Storage.Common
 
**Is your feature request related to a problem? Please describe.**
It looks like `StorageSharedKeyCredential` should have a static `FromConnectionString` method. The Java library has one:

https://docs.microsoft.com/en-us/java/api/com.azure.storage.common.storagesharedkeycredential.fromconnectionstring?view=azure-java-stable

Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @j055, this seems like a reasonable suggestion, we will look into adding it to the SDK soon.

**Comment by tommck** [comment]
@seanmcc-msft would you want a pull request for this?  Seems like it should be pretty simple to implement

**Comment by amnguye** [comment]
Relabeled as feature-request

**Comment by JimSuplizio** [comment]
Hi @j055, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
