### ISSUE TITLE
[BUG] [TABLES] TableBatchResponse.IsBatchSuccessful incorrect

### ISSUE THREAD

**Issue by kieronlanning** [Azure/azure-sdk-for-net#16351]
**Describe the bug**
When the `TableTransactionBatch` is successfully processed, `TableBatchResponse.IsBatchSuccessful` should be true, currently it returns false.

The error looks to be [here](https://github.com/Azure/azure-sdk-for-net/blob/a0f79c121d1ae4add81961102dffa275a3152d14/sdk/tables/Azure.Data.Tables/src/TableBatchResponse.cs), on line 21.

`public bool IsBatchSuccessful => _requestLookup.Values.Any(r => r.Message.Response.Status >= 400);`

**Expected behavior**
`TableBatchResponse.IsBatchSuccessful` should be true.

**Actual behavior (include Exception or Stack Trace)**
`TableBatchResponse.IsBatchSuccessful` is false.

![image](https://user-images.githubusercontent.com/5364423/97401455-c31eff80-18e8-11eb-83a7-ecf29617f7f1.png)

**To Reproduce**
1. Create a transaction batch.
2. Execute against table.
3. Validate response.

**Environment:**
 - Azure.Data.Tables 3.0.0-beta2
 - Windows 10, .NET Core 3.1.403
 - Visual Studio 16.7.6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kieronlanning** [comment]
@jsquire / @christothes just realised this was marked a `-beta1`, but it's actually `-beta2`. Updated accordingly.

**Comment by christothes** [comment]
@kieronlanning Thanks for this - `IsBatchSuccess` was intended to be removed from the response type since if it were not successful, we would have thrown and never created the `TableBatchResponse` in the first place.

**Comment by kieronlanning** [comment]
@christothes OK. What type of exception would it throw?

Will it still give us access to the element(s) (via RowKey/ Index) that failed? It's useful to know which one(s) have caused problems... especially as I use these as a means of idempotency...

**Comment by christothes** [comment]
Yes, see https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/tests/TableClientLiveTests.cs#L1088

I plan to add a sample demonstrating this soon.

**Comment by kieronlanning** [comment]
@christothes Thanks for that.

I had a situation where I add things in a very specific order so I can report back different error states based on the entity that failed.

For example, if it's idx:0, I'll know it's an idempotent issue. idx:1, then it's an optimistic concurrency exception for example.

Is that something that I'll be able to easily replicate. I couldn't really tell from that sample...

**Comment by christothes** [comment]
The exception message will contain two hints as to which entity failed. The body of the exception message will contain an index value of the failed entity as described here:
https://docs.microsoft.com/en-us/rest/api/storageservices/performing-entity-group-transactions#error-response-for-request-in-json-format

`"value":"0:One of the request ...`

The above error indicates that the entity at index 0 contains the error. 

In addition we append the RowKey value to the message here:

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/src/TableRestClient.cs#L169

Given both of those you would have the ordinal index and row key values of the entity that caused the transaction to fail. 

Does that provide you what you need?

**Comment by kieronlanning** [comment]
@christothes Technically, yes it does. But I'm down to string parsing to get the error details out - and modify code paths accordingly. Seems a little... fragile.

Can you include the details as an object, similar to the success object where I can call `GetResponseForEntity` from the `TableBatchResponse`?

For example:

![image](https://user-images.githubusercontent.com/5364423/97803847-d4973d00-1c43-11eb-82c8-6b9a0dc12545.png)
