### ISSUE TITLE
[FEATURE REQ] Ability to traverse blob hierarchy upwards. BlobClient->BlobContainer

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#16359]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
While working on Storage Webjobs Extension migration from V11 to V12 I keep finding places where original authors leveraged ability to traverse hierarchy upwards. I.e. jump from BlobClient to Container client (and to service client). To make it work with V12 I often had to pass higher level client along with lower level client or magically resolve creds or higher level client from some "context".
A recent example of such pain is in https://github.com/Azure/azure-sdk-for-net/pull/16336 where in order to jump from BlockBlobClient to BlobClient and vice versa requires magic. Ideally I should be able to write `blockBlobClient.GetContainerClient().GetBlobClient(blockBlobClient.Name)`. 
Additionally the `blobClients` already have `ContainerName` property, so information about parent is available. But if someone doesn't have reference to higher level client handy then they're facing quite a refactoring as there's no good way to transfer pipeline and credential from one blobClient to other blobClient.

Adding such capability might ease a lot of migration pains.

**Comment by kasobol-msft** [comment]
@tg-msft  @seanmcc-msft what do you think ?

**Comment by seanmcc-msft** [comment]
@kasobol-msft, seems reasonable.

**Comment by tg-msft** [comment]
As long as we do it with extension methods in the `.Specialized` namespace, I think it's great.  It's fine to have protected virtuals for mocking, but public instance methods would be problematic for the original flow that folks on your team felt strongly about when we decided on the client hierarchy.
