### ISSUE TITLE
[QUERY] Table Entity - Additional Properties on TableEntity vs. ITableEntity

### ISSUE THREAD

**Issue by kieronlanning** [Azure/azure-sdk-for-net#16354]
`Azure.Data.Tables`.

When adding entities to Azure Table Storage and using `TableEntity` as a base class, additional properties are not serialised (silently).

Example:

```
public class CustomEntity1 : TableEntity
{
    public string? AStringValue { set; set; } <-- DOES NOT SERIALIZE

    public int AnInt32Value { set; set; } <-- DOES NOT SERIALIZE
}
```

However, serializing a custom entity that implements `ITableEntity` successfully serializes additional properties:

```
public class CustomEntity2 : ITableEntity
{
    public string? AStringValue { set; set; } <-- _DOES_ SERIALIZE

    public int AnInt32Value { set; set; } <-- _DOES_ SERIALIZE

    ... additional ITableEntity properties...
}
```

Currently `CustomEntity1` silently fails to serialize these additional properties, is this intentional?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
@kieronlanning This is an interesting scenario and one that I hadn't considered. I suppose `TableEntity` should be sealed as a result.

Could you talk a bit about why you'd want to derive from `TableEntity` to add custom properties rather than using it as a dictionary or creating a class directly implementing `ITableEntity` as in your `CustomEntity2` example?

**Comment by kieronlanning** [comment]
@christothes It seemed logical from the point of view of migrating from the old package to the new one. 

Plus, from a laziness perspective it's a little quicker to use `TableEntity` than implement `ITableEntity`.

You could use the `TableEntity` to wrap gets/ sets from the dictionary to typed properties too... that's another scenario.

It almost feels like it needs a Roslyn Analyzer.
