### ISSUE TITLE
[BUG] Microsoft.Azure.ServiceBus 5.0.0 doesn't work statically after first call

### ISSUE THREAD

**Issue by josh-endries** [Azure/azure-sdk-for-net#16356]
This is getting tiresome. I think this is my fourth or fifth issue with this library not working as described.

It seems to be [recommended](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk) to use client types from this library statically, but whenever I do, I run into problems. The latest of I think three cases where it doesn't work is that `PeekAsync` just stops returning any messages after the first call.

I have a test service bus queue with 2 messages in it and no receivers, and when I run the following Function the first time it returns both messages, but it never returns any after that:

```
private static IMessageReceiver MR = new MessageReceiver(
    "connectionstring",
    "queuename",
    ReceiveMode.PeekLock,
    RetryPolicy.Default,
    0 // prefetch count; using int.MaxValue doesn't make a difference
);


[FunctionName(nameof(Jobs))]
public static async IAsyncEnumerable<Message> Jobs(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get")] HttpRequestMessage req
)
{
    IList<Message> messages;
    do
    {
        messages = await MR.PeekAsync(int.MaxValue);
        foreach (var m in messages) yield return m;
    } while (messages.Count > 0);
}
```

This is stripped down. The real app does a lot more but ultimately returns an `HttpResponseMessage` using an `IAsyncEnumerable` for content, which is why that loop is in there, but it didn't work for subsequent calls when I just returned the messages directly, either. `PeekAsync` just returns an empty list.

The only way I've gotten it to work correctly is to create a new `MessageReceiver` instance for every request and call `CloseAsync` after yielding out the messages. Otherwise, it just retrieves no messages, regardless of how many times I call `PeekAsync` or make multiple requests to the Function. However that pattern seems to be discouraged...

I must be missing something about how `MessageReceiver` should be used but I've spent several dozen hours troubleshooting this and haven't gotten anywhere.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @MiYanni

**Comment by axisc** [comment]
@josh-endries 

Calling peek maintains a checkpoint of the last peeked sequence number and only messages from that point are peeked again. In your case, since you have just 2 messages, they can't be peeked once it's done

Here is the [source code](https://github.com/Azure/azure-sdk-for-net/blob/4bab05144ce647cc9e704d46d3763de5f9681ee0/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Core/MessageReceiver.cs#L804)
