### ISSUE TITLE
Add support for producing ActivitySource activities

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#16375]
Currently we are only producing activities via the diagnostic source. A new ActivitySource type is shipping as part of .NET 5 and the OpenTelementry is going to consume ActivitySource only.

**Comment by AlexGhiondea** [comment]
@pakrym Is this still something we need to do?

**Comment by pakrym** [comment]
Yes, this is still not done.

**Comment by pakrym** [comment]
Now it's done.
