### ISSUE TITLE
[Service Bus] Update Hello World sample to use the processor

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#16393]
**Library or service name.**
Azure.Messaging.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
The hello world sample for receiving messages uses the ReceiveMessagesAsync() method where as it is the processor model that we want to present as the getting started path.

Same for the package readme

**Comment by JoshLove-msft** [comment]
The [quickstart](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues) uses the processor, and the README has a section for the processor.
