### ISSUE TITLE
Manage Azure Relay from dotnet core 3.1 with shared access policy

### ISSUE THREAD

**Issue by joaroyen** [Azure/azure-sdk-for-net#16413]
**Query/Question**
Is it possible to manage Azure Relay with a shared access policy connection string with Manage claim on dotnet core 3.1?

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.Relay 2.0.2
 - Hosting platform or OS and .NET runtime version:  Microsoft.AspNetCore.App 3.1.9
 - IDE and version : Visual Studio 16.7.7

I'm upgrading relay management code from classic service bus management library WindowsAzure.ServiceBus to the new relay management library. Previously we issued a shared access secret based on a policy that included Manage claim and configured our existing app with a service bus connection string. Using the classic full framework library we could manage WCF relays, even in a new Azure Relay namespace.

I've tried acquiring a token using Microsoft.Azure.Relay.TokenProvider.CreateSharedAccessSignatureTokenProvider(keyName, key) but this token is of course a SharedAccessSignature token intended for the service bus namespace endpoint and not Azure Resource Manager.

Is there a similar library like the service bus `Microsoft.Azure.ServiceBus.Management.ManagementClient(connectionString)` that can be used to manage Azure Relay on dotnet standard?

My reason for asking is that we have legacy code that we don't want to issue certificates and create app registrations for to be able to acquire token from AAD. This legacy code should also be restricted to only manage service bus and relay resources.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jfggdl** [comment]
@joaroyen, we should be getting back to you soon. Thanks for your question.

**Comment by jfggdl** [comment]
@joaroyen, this feature is part of our new Management API for Hybrid Connections that we have in our backlog. However, there are no current plans to implement it as there are higher priority features that should be implemented first. We have added a reference to this GitHub issue to our internal backlog so that along with similar requests, they can inform our priorities. I am going to close this issue. We thank you for reaching out to us requesting this feature. Your input will inform our future roadmap.

**Comment by joaroyen** [comment]
Thanks for the response. Not exactly what we wanted to hear, and I believe we will distribute certificate and use the Microsoft.Azure.Management.Relay library.
