### ISSUE TITLE
Accept the Azure.Core Shared Key and SAS Credentials

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#16419]
# Summary

Service Bus allows for authorization using a shared key and shared access signature that is currently only supported when using a connection string.  To align with best practices, we would like to guide library users to down the path of using Identity credentials for production applications by supporting shared key and SAS scenarios using a similar API shape.

# Scope of Work

- Extend the Service Bus client constructors to accept the `Azure.Core` credential types representing shared keys and shared access signatures.

- Incorporate the credentials into the `SharedAccessSignature` type such that the shared key and value or the shared access signature to be updated without stopping or recreating the associated clients..

# Success Criteria

- All clients that accept a `TokenCredential` also accept the new credential types with a similar signature.

- The credentials are integrated with the `SharedAccessSignature` , allowing them to be used within the existing authorization infrastructure.

- The tests necessary for its validation have been created or adjusted and pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

# References

- [Follow-Up: Client Creation Discussion](https://gist.github.com/jsquire/13742f53bf642ec67baf9491fc844cff)
- [Client Creation Discussion](https://gist.github.com/jsquire/55a1a934246fd6d9fe9c9e21443d7023)

**Comment by jsquire** [comment]
Note to self: Review retry rules to ensure that Unauthorized exceptions are retried.

**Comment by JoshLove-msft** [comment]
@jsquire can this be closed or is there something else we are planning here?

**Comment by jsquire** [comment]
Wow.... yup, this should have been closed.
