### ISSUE TITLE
TextRecognitionResult is not found in Version 6

### ISSUE THREAD

**Issue by leemorris** [Azure/azure-sdk-for-net#16422]
I am using Microsoft.Azure.CognitiveServices.Vision.ComputerVision.ComputerVisionClient to call BatchReadFileInStreamAsync.
I then call `results = await client.GetReadOperationResultAsync(operationId);`
Which contains an `IList<TextRecognitionResult>`.

I upgraded Microsoft.Azure.CognitiveServices.Vision.ComputerVision, from Version=5.0.0, to Version= 6.0.0. 

The TextRecognitionResult is not found after upgrade.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by alex19497** [comment]
Any updates on this issue?

**Comment by leemorris** [comment]
Is there an update on this??

**Comment by timctho** [comment]
The underlying model will be different, as starting from 6.0.0 it's using v3 Read API, which has much better performance than before. Usages are very similar, except slightly difference in result schema, detailed as below.

[GetReadOperationResultAsync]
https://westus.dev.cognitive.microsoft.com/docs/services/5adf991815e1060e6355ad44/operations/5be108e7498a4f9ed20bf96d

[GetReadResultAsync]
https://centraluseuap.dev.cognitive.microsoft.com/docs/services/computer-vision-v3-2/operations/5d9869604be85dee480c8750

**Comment by JimSuplizio** [comment]
Hi @leemorris, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
