### ISSUE TITLE
[MetricsAdvisor] Remove AZC0007 NoWarn option

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#16435]
Blocked by: https://github.com/Azure/azure-sdk-tools/issues/127

[Our guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-usage-options) state that:

> If the options type can be shared by multiple client types, name it with a plural or more general name. For example, the BlobClientsOptions class can be used by BlobClient, BlobContainerClient, and BlobAccountClient.

We can't create a `MetricsAdvisorClientsOptions` (pluralized "Clients") because the API analyzer expects a `ClientOptions` suffix. A `NoWarn` property was added to avoid the warning for the time being.

**Comment by pallavit** [comment]
@kinelski is this still valid?

**Comment by kinelski** [comment]
> @kinelski is this still valid?

We don't seem to get the warning anymore. I'll create a PR to update the code and close this issue.
