### ISSUE TITLE
Update the autorest.md file to use swagger README instead of json file

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#16445]
We should be using swagger README files instead of json in `autorest.md`. For management plane we are using README for all the SDKs but most of the data plane libraries are using json files.

List of data Plane libraries that are using Json as an `input-file`:
[Anomaly Detector](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/anomalydetector/Azure.AI.AnomalyDetector/src/autorest.md)
[Form Recognizer](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/autorest.md)
[Text Analytics](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/src/autorest.md)
[Search](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/src/autorest.md)
[Digital Twins](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/digitaltwins/Azure.DigitalTwins.Core/src/autorest.md)
[Communication.Administration](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/communication/Azure.Communication.Administration/src/autorest.md)
[Communication.Chat](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/communication/Azure.Communication.Chat/src/autorest.md)
 [Communication.Sms](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/communication/Azure.Communication.Sms/src/autorest.md)
[Security.KeyVault.Administration](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Administration/src/autorest.md)
[Metrics Advisor](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/autorest.md)
[Synapse.AccessControl](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/synapse/Azure.Analytics.Synapse.AccessControl/src/autorest.md)
[Synapse.Artifacts](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/autorest.md)
[Synapse.Spark](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/synapse/Azure.Analytics.Synapse.Spark/src/autorest.md)
[Tables](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/src/autorest.md)

**Comment by christothes** [comment]
Tracking this for Tables in #16510

**Comment by ShivangiReja** [comment]
Tracking issues here:

* Form Recognizer - https://github.com/Azure/azure-sdk-for-net/issues/18728
* Anomaly Detector - https://github.com/Azure/azure-sdk-for-net/pull/18729
* Text Analytics- https://github.com/Azure/azure-sdk-for-net/issues/18730
* Search - https://github.com/Azure/azure-sdk-for-net/issues/18731
* Digital Twins - https://github.com/Azure/azure-sdk-for-net/issues/18732
* Communication - https://github.com/Azure/azure-sdk-for-net/issues/18733
* Keyvault - https://github.com/Azure/azure-sdk-for-net/issues/18734
* Metrics Advisor - https://github.com/Azure/azure-sdk-for-net/issues/18735
* Synapse - https://github.com/Azure/azure-sdk-for-net/issues/18736
* Tables - https://github.com/Azure/azure-sdk-for-net/issues/18737
* Attestation - https://github.com/Azure/azure-sdk-for-net/issues/18739
* Mixed Reality - https://github.com/Azure/azure-sdk-for-net/issues/18741
* monitor - https://github.com/Azure/azure-sdk-for-net/issues/18742
* Storage - https://github.com/Azure/azure-sdk-for-net/issues/18744
