### ISSUE TITLE
GetPropertiesOfKeyVersions throws for non-existent key on Managed HSM

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#16444]
The `KeyClient.GetPropertiesOfKeyVersions` method throws when requesting versions on a non-existent key on Managed HSM because HTTP 404 is returned. Key Vault, in contrast, returns HTTP 200 with an empty response. Arguably in this case, 404 is better, but I'm sure customers will expect a constsitent experience using `KeyClient` against Key Vault or Managed HSM.

This may be best handled by the service to have consistent behavior, so that any client - in the Azure SDK or not - has consistent behavior. If we have to make the behavior consistent in clients, we'll want to avoid throwing exceptions/errors in some languages where it's expensive to do so (e.g. .NET).

**Comment by sebansal** [comment]
Adding @amitbapat

**Comment by sebansal** [comment]
Ping @amitbapat

**Comment by jlichwa** [comment]
From Vick:
We have already fixed the back compatiblity issue for the 404 vs 200 empty key list.

If this is not the observed production behavior in SDK automation, it will be fixed mid way next week.

**Comment by sebansal** [comment]
@vickm has this been resolved?

**Comment by sebansal** [comment]
Resolved.
