### ISSUE TITLE
[ServiceBus] Set message count limit for tryAdd on message batch

### ISSUE THREAD

**Issue by MiYanni** [Azure/azure-sdk-for-net#16450]
Currently, the service only allows 4500 messages in a batch. To accommodate for this, we should make tryAdd on a message batch fail if trying to add more than 4500 messages.

Related: https://github.com/Azure/azure-service-bus/issues/397

*Edit*: Instead of adding this hard limit client-side, we are instead going to place information in the documentation for tryAdd, since the limit for Basic and Standard tier is 4500 and the limit for Premium is ~15885. It would be best to link to Service Bus documentation on these limits instead of hard-coding into our reference documentation. However, we'd have to wait until they publish that information.

**Comment by JoshLove-msft** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-net/issues/21451
