### ISSUE TITLE
We need a NonParallelizableAttribute that parallelizes during test playback

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#16453]
We have a number of tests can't can't be run concurrently, hence are attributed with `[NonParallelizable]` from NUnit. Most likely these can be parallelized during playback of recorded tests. We should add our own attribute that accomplishes this to speed up dev- and CI-testing.

Putting this in Azure.Core only because it'd likely go in the Azure.Core.TestFramework.

**Comment by pakrym** [comment]
Playback can't be parallelized because NUnit reuses the same test class instance and the test recording is a part of it.

**Comment by heaths** [comment]
That's unfortunate. At least they run pretty fast regardless.
