### ISSUE TITLE
error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2.

### ISSUE THREAD

**Issue by Ludo-CVS** [Azure/azure-sdk-for-net#16467]
From my Azure pipeline, I have since today an error while restoring the nugets:

[error]The nuget command failed with exit code(1) and error(C:\Program Files\dotnet\sdk\2.1.519\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 2.2.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 2.2. 

I can't seem to find a solution to my problem.

6 months ago everything worked fine.
My code has not changed.

**Comment by sagar-thakkar-dev** [comment]
Can you verify your build agent in Azure Pipeline? 
It might be vs2017-win2016.

If yes, please change it to windows-2019.

That worked for me.

**Comment by Ludo-CVS** [comment]
That good, 

Thank you
