### ISSUE TITLE
[BUG] [Application Insight SDK] GetIntervaledMetric doesn't populate start and end property MetricsIntervaledData 

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Azure/azure-sdk-for-net#16465]
**Describe the bug**
Using `Microsoft.Azure.ApplicationInsights.Query` I invoked `GetIntervaledMetric ` API to call GET /metric endpoint to get a time-series custom metrics.
https://dev.applicationinsights.io/documentation/Using-the-API/Metrics
https://dev.applicationinsights.io/reference

When invoking REST API directly, each element of the segment object has start and end keys. We can find the example response here.
https://dev.applicationinsights.io/documentation/Using-the-API/Metrics

However. when using `GetIntervaledMetric ` API, start and end property are always null.
https://github.com/Azure/azure-sdk-for-net/blob/e362517174464bd5d18167f454bfedd676df8519/sdk/applicationinsights/Microsoft.Azure.ApplicationInsights.Query/src/Customized/Models/MetricsIntervaledData.cs#L16

**Expected behavior**
The start and end properties are populated.

**Actual behavior (include Exception or Stack Trace)**
The start and end properties are always null.

**To Reproduce**

1. Invoke the `GetIntervaledMetric` API to get time series metrics.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ApplicationInsights.Query 1.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Core 3.1
 - IDE and version : Visual Studio 2019

**Comment by tanaka-takayoshi** [comment]
I'm wondering this is because the start and end properties are not populated here.
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/applicationinsights/Microsoft.Azure.ApplicationInsights.Query/src/Customized/Metrics.cs#L204-L211

**Comment by scottaddie** [comment]
Support for the `Microsoft.Azure.ApplicationInsights.Query` package ended on March 31st. It has been deprecated in favor of [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query). We recommend migrating to continue receiving support. To assist in that migration, see [this migration guide](https://aka.ms/azsdk/net/migrate/ai-monitor-query).
