### ISSUE TITLE
[BUG] BlobClient Name is getting URL Encoded

### ISSUE THREAD

**Issue by robrtrix** [Azure/azure-sdk-for-net#16460]
**Describe the bug**
If the blob.Name contains "/" like in a hierarchical structure, in the BlobClient, the name is escaped to %2F for the slashes. This passes through in the blobClient.Uri, which returns `https://<accountname>.blob.core.windows.net/<containername>/blobroot%2Fsubfolder%2Fblobname.ext`
 as an example. 

This works in some browsers still, but if the URL is URL Encoded, which it should be able to, it then breaks because the % symbols causes issues with future URL encoding where they get converted into %25, plus the 2F, turns in to %252F.

**Expected behavior**
If the blob.Name has "/" then it should stay as "/" and not be escaped to %2F

**Actual behavior (include Exception or Stack Trace)**
Blob name passed in as "blobroot/subfolder/blobname.ext" 
is converted to "blobroot%2Fsubfolder%2Fblobname.ext"

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a BlobClient with a hierarchical name containing at least one subfolder.
2. Then look at the blobClient.Uri and you will see that the blob Name has been escaped.

**Environment:**
 - Azure.Storage.Blobs 12.6.0
 - .NET Core 2.2
 - Visual Studio 2019

**Comment by robrtrix** [comment]
Work around:
instead of using blobClient.Uri.ToString() or blobClient.Uri.AbsoluteUri, you can use: 
$"{blob.Uri.Scheme}://{blob.Uri.Host}{blob.Uri.LocalPath}"

The blob.Uri.LocalPath has the correct original blob Name in it.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
This is by design, the storage service considers '/' and '%2F' to be the same character.

To get the unescaped blob name, I recommend using BlobClient.Name to get the unencoded blob name.

If the blob name is already URL-encoded, we encode it a second time.  Apparently there are a lot of customers who want to literally name their blob something along the lines "my%2Fblob%2Fname".  Since the service considers '/' and '%2F' to be the same, we have to encode the URL a second time.

**Comment by seanmcc-msft** [comment]
Please reopen if you have further questions.

**Comment by ipanin** [comment]
Such Uri escaping is very inconvenient if I use virtual directories inside blobs. I have to un-escape BlobClient.Uri to get meaningful URL.

**Comment by seanmcc-msft** [comment]
The service considers “/“ and “%20” to be the same character. In addition, you can get the unescaped blob name with BlobClient.Name.

**Comment by SiobhanBaynes** [comment]
I **can** get the name by using `blobClient.Name` but then I have to do some string manipulation to get the full URI.  If the service considers them the same, then it should be consistent in the way in which it returns them.
