### ISSUE TITLE
February Release of Key Vault for .NET

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#16486]

**Comment by RoundNutz4** [comment]
>

**Comment by IvanAlekseev** [comment]
We are getting very close to keyvault limits and would like to use local cryptography. Will we have 4.2 with local signing in February or we better implement it internally for now?

**Comment by heaths** [comment]
`LocalCryptographyClient` is available in the preview now, though we will be removing it in favor of making the existing `CryptographyClient` work in a local-only mode given a JWK.

This will not be a GA library and we have no announced date at this time, but after February have no current plans for major changes, including breaking changes to previews.

Note that unless you have a JWK with private key material, the local cryptography client can only do operations against a public key including encrypt, verify, and wrapKey. But if you have a JWK, you can use the `ToRsa()` or `ToEc()` methods to get a cryptographic provider you can use locally (i.e. regular `System.Security.Cryptography` code).

**Comment by heaths** [comment]
February betas have been released.
