### ISSUE TITLE
Search SDK: Search states that it has one record but the results are empty

### ISSUE THREAD

**Issue by brunoshine** [Azure/azure-sdk-for-net#1650]
Hi all,

I've done a search that the Count states it has a record but the results are empty. I've run the same filter on the azure search explorer and it retuns a record.

Any thoughts?
Thanks.
![search](https://cloud.githubusercontent.com/assets/709567/11608632/c08bc956-9b66-11e5-81ac-703f33b239f7.png)

**Comment by brjohnstmsft** [comment]
Hi Bruno,
Could you share the values for `searchText` and all properties of the `SearchParameters` object for the SDK request, as well as the full URL for the REST API request?

**Comment by brjohnstmsft** [comment]
Closing this since there was not enough info provided to repro.
