### ISSUE TITLE
EventDataBatch is not mockable

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#16504]
I'm trying to write a test for code that uses the `EventHubProducerClient` and `EventDataBatch`. The goal is to verify that the batch contains an expected set of events without running against the live service.

It's possible to create a mock EventHubProducerClient but there is no way to create a mock `EventDataBatch`.

**Comment by JoshLove-msft** [comment]
Related - https://github.com/Azure/azure-sdk-for-net/issues/16142

**Comment by JoshLove-msft** [comment]
Would a factory method be sufficient or does the type need to be mockable?

**Comment by pakrym** [comment]
EventDataBatch doesn't expose a way to enumerate added events so I don't see how a model factory would help here unless it returns a test-specific EventDataBatch implementation that exposes more properties.

**Comment by JoshLove-msft** [comment]
Ok I guess this is a special case due to how this type works.

**Comment by pakrym** [comment]
It's related to the pattern we use in messaging libraries where not only client types can communicate with the service.

**Comment by JoshLove-msft** [comment]
This type doesn't communicate with the service.. It is created by communicating with the service though.

**Comment by pakrym** [comment]
You are right.

**Comment by jsquire** [comment]
This will be covered as part of #9117.   The model factory will be including a mocked up transport batch and likely taking a list to use as a backing source so that developers can inspect what was accepted.   

I'm going to close this out as a dupe.
