### ISSUE TITLE
[Core AMQP] AmqpAnnotatedMessage review follow up

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#16524]
This is from the follow up after an internal review of the new AmqpAnnotatedMessage type
- The constructor takes bytes which then is internally converted to AmqpMessageBody. In Java, the constructor takes AmqpMesageBody. Should .Net consider doing the same instead of adding more constructor overloads in the future when needing to support more body sections?
- The current name `AmqpDataMessageBody` does not read well. These are for users familiar with AMQP and the different body sections in the AMQP message. 
    - Consider `AmqpDataBody` which is simpler. If needed, we can rename the interface `AmqpMessageBody` to `AmqpBody` as well.
    - Another option is to treat "AmqpMessage" as the prefix we want to preserve and use "AmqpMessageDataBody`

**Comment by JoshLove-msft** [comment]
If we are going to remove Message from the name, we should probably do the same for AmqpMessageProperties, AmqpMessageHeader, and AmqpMessageBodyType.

**Comment by ramya-rao-a** [comment]
To be in sync with all those names, I would treat "AmqpMessage" as the prefix and not just "Amqp". So that way we can have `AmqpMessageBody` and `AmqpMessageDataBody`

**Comment by JoshLove-msft** [comment]
I was responding to this comment: 
 > If needed, we can rename the interface AmqpMessageBody to AmqpBody as well.

**Comment by JoshLove-msft** [comment]
One message body type with TryGet pattern -> the name becomes AmqpMessageBody.

We would leave the Body as settable, and have constructor for AmqpAnnotatedMessage take an AmqpMessageBody only.
The different section types would be constructed via AmqpMessageBody ctors.

**Comment by JoshLove-msft** [comment]
We wanted to follow up with Clemens about whether it is correct that Sequence that it is really a list of lists or if it should just be a sequence.

**Comment by clemensv** [comment]
AMQP 3.2 http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#section-message-format 

"The body consists of one of the following three choices: one or more data sections, one or more amqp-sequence sections, or a single amqp-value section."
