### ISSUE TITLE
[BUG] QueueUriBuilder ignores AccountName in ConnectionString if local Docker host name is used

### ISSUE THREAD

**Issue by PureKrome** [Azure/azure-sdk-for-net#16542]
**Describe the bug**
When a custom docker hostname is used in the connection string for a Queue, the account name is not correctly resolved.
This was previously mentioned in #9404 .. which was subsequently fixed (for BLOBS only) in PR #13124 

**Expected behavior**
A connection string with a host name should correctly extract the relevant sections.

**Actual behavior (include Exception or Stack Trace)**
The account name is not extracted. This results in an HTTP 400 result when using the SDK to do stuff against a queue.

**Environment:**
 - Azure.Storage.Queues 12.4.2
 - dotnet core 3.1
 - Visual Studio 16.7.7

---

Basically, the previous issue reported occurred for Blobs and Queues. I'm _assuming_ Tables also, but I don't use Tables so I'm not checking that. The PR fix to previous issue only updated/fixed Blobs, so Queues still have this problem.

I found this issue because I'm doing some .net core web api's targetting Azurite as the storage emulator, all in a docker-compose file and the api can't connect to the azurite (docker) instance. For arguments sake, lets assume that I got all my docker ports correct, etc.

So, when I create the test in the current code base (copied from the PR), I get the following:

![image](https://user-images.githubusercontent.com/899878/97958933-5c2aaa80-1e02-11eb-994e-d90807145f7b.png)

Okay, great - we have a bug.

I'll see if I can create a PR to fix this. 🤞🏻

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
Please see related PR:  #16543

**Comment by amnguye** [comment]
Hi,

This seems like a duplicate of this existing issue.
https://github.com/Azure/azure-sdk-for-net/issues/15403

Could you confirm if you're having the same problem so we can label this issue accordingly?

I also replied to your PR and noted that I actually resolved that today in the PR https://github.com/Azure/azure-sdk-for-net/pull/15972 that I merged.

**Comment by PureKrome** [comment]
Yep - confirmed duplicate issue #15403 and yep #15972 includes the same fix. Doh! oh well, there goes a few hours.

Great to see that this is now fixed, though. Well done team!

**Comment by amnguye** [comment]
Yeah sorry about that! Thank you for your time and contribution though. We appreciate it!
