### ISSUE TITLE
Which nuget should I reference for Microsoft.Azure.Management.Reservations 

### ISSUE THREAD

**Issue by cfauchere** [Azure/azure-sdk-for-net#16546]
**Query/Question**
Which nuget should I reference to use [IQuotaOperations ](https://github.com/Azure/azure-sdk-for-net/blob/a7f25a2edb41d7830e722138dddf08480da4e31e/sdk/reservations/Microsoft.Azure.Management.Reservations/src/Generated/IQuotaOperations.cs#L24)

**Environment:**
 - Name and version of the Library package used: this is the question
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 

> .NET Core SDK (reflecting any global.json):
>  Version:   3.1.401
>  Commit:    5b6f5e5005
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\3.1.401\
> 
> Host (useful for support):
>   Version: 3.1.7
>   Commit:  fcfdef8d6b
> 
> .NET Core SDKs installed:
>   3.1.301 [C:\Program Files\dotnet\sdk]
>   3.1.401 [C:\Program Files\dotnet\sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download

 - IDE and version : Visual Studio 16.6.2

**Comment by jsquire** [comment]
Thank you for your feedback.  From the repository path that you've listed, I'd assume that [Microsoft.Azure.Management.Reservations](https://www.nuget.org/packages/Microsoft.Azure.Management.Reservations) is the package that you're looking for.  However, it looks as if the `IQuotaOperations` type that you listed was added in July for `v1.14.0-preview`, according to the [ChangeLog](https://github.com/Azure/azure-sdk-for-net/blob/a7f25a2edb41d7830e722138dddf08480da4e31e/sdk/reservations/Microsoft.Azure.Management.Reservations/CHANGELOG.md) entry.    That version does not appear to have been released yet.

I'm hopeful that @allenjzhang  or @rahuls-microsoft can offer insight on when that may be released.

**Comment by cfauchere** [comment]
Thanks for the follow up. Does it come or will it come with the fluent package?

**Comment by allenjzhang** [comment]
The fluent package for .NET management SDK is not planned. I see that the code has been updated to [1.14](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/reservations/Microsoft.Azure.Management.Reservations/src/Microsoft.Azure.Management.Reservations.csproj)  but not published to NuGet. Let me loop in the service team. 

@rahuls-microsoft, do you have any update on the new version of SDK?

**Comment by rahuls-microsoft** [comment]
We are working on the GA readiness. The final SDK for GA will be released by the end of the month.
The Preview SDK links are available at the doc site - https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/quotaapi

**Comment by rahuls-microsoft** [comment]
@markcowl When the new .net SDK will be released?

**Comment by markcowl** [comment]
@rahuls-microsoft Service teams are responsible for releasing their .Net SDK.

**Comment by rahuls-microsoft** [comment]
Please refer to the page for Azure SDK links-
https://docs.microsoft.com/en-us/rest/api/reserved-vm-instances/quotaapi#support-in-other-languages-and-interfaces

**Comment by rahuls-microsoft** [comment]
https://www.nuget.org/packages/Microsoft.Azure.Management.Reservations/1.15.0-preview - Please use the new .net SDK package.

**Comment by ramaganesan-rg** [comment]
Please let us know if you have any further questions.

**Comment by ramaganesan-rg** [comment]
I believe the response provided by our eng team helps with your ask. please feel free to reopen the issue if needed.
