### ISSUE TITLE
Azure.WebJobs.Extensions.Storage.Queues nuget package missing?

### ISSUE THREAD

**Issue by maris-jurgenbergs** [Azure/azure-sdk-for-net#16569]
**Query/Question**
Has Azure.WebJobs.Extensions.Storage.Queues nuget package been removed? I cant seem to find it in nuget.org

**Comment by jsquire** [comment]
Hi @maris-jurgenbergs.   Thank you for your question.  Unfortunately, the WebJobs extensions are not a part of the Azure SDK repository so we're unable to assist.  I've moved this over to the WebJobs.Extensions repository, issue #[682](https://github.com/Azure/azure-webjobs-sdk-extensions/issues/682) to bring this to the attention of the team that can help.   

I'm going to close this out; please feel free to reopen if you would like to discuss further.

**Comment by maris-jurgenbergs** [comment]
@jsquire azure-sdk-for-net/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/ this project is located in this repository. Does that not indicate that its part of the repository?
![image](https://user-images.githubusercontent.com/5676955/98120934-49be7880-1eb7-11eb-9d89-74c62cdb2941.png)

**Comment by jsquire** [comment]
That's..... new.   Apologies, you are correct.  I wasn't aware that it had been pulled into this repository.   Tagging and routing to the Storage team to assist.

**Comment by jsquire** [comment]
//cc: @kasobol-msft

**Comment by kasobol-msft** [comment]
`Azure.WebJobs.Extensions.Storage.Queues` has not yet been released to nuget. The release is planed in near future.

**Comment by maris-jurgenbergs** [comment]
@kasobol-msft Would a pre-release be faster? :) or were You thinking of a pre-release?

**Comment by kasobol-msft** [comment]
@maris-jurgenbergs I meant pre-release `5.0.0-beta.1`.

**Comment by kasobol-msft** [comment]
@maris-jurgenbergs https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/5.0.0-beta.1 is out.
