### ISSUE TITLE
[QUERY] Question about certificate pinning

### ISSUE THREAD

**Issue by cassiejones444** [Azure/azure-sdk-for-net#16614]
**Query/Question**
How can we help?

Hi

![nuget](https://user-images.githubusercontent.com/47842107/98203377-0e3faf00-1f88-11eb-9181-71f6f3cb0961.png)

I have a client that is asking around whether, as part of the SDK development, the TLS certificate chains have been pinned and if they need to upgrade their Azure nuget packages to newer versions or not. See the png file that i've attached.

Putting aside the fact they don't regularly update, any help or statements would be gratefully received.

Thanks Cassie

**Comment by jsquire** [comment]
//cc: @schaabs, @allenjzhang, @AlexGhiondea

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by jsquire** [comment]
@schaabs, @heaths:  I'm hoping that you may have insight, as KeyVault is likely in scope for any security considerations around certificates.   If there's a better source of information, would you be so kind as to re-route?

**Comment by heaths** [comment]
Considering our SDK can be used to connect to many different services and clouds, we don't pin certificates; however, the .NET SDKs - all our language SDKs, really - do validate the certificate subject's CN matches the endpoint domain you specified. You're encouraged to also enable CRL verification.

If you want to enable pinning for your application, in both our old and new SDKs you can pass in your own `HttpClient` which can take a `HttpClientHandler` that allows you to validate server certificates, like so using our Azure.Security.KeyVault.Secrets package:

```c#
using Azure.Core.Pipeline;
using Azure.Identity;
using Azure.Security.KeyVault.Secrets;
using System;
using System.Net.Http;
using System.Net.Security;
using System.Security.Cryptography.X509Certificates;
using System.Threading.Tasks;

class Program
{
    static async Task Main(string[] args)
    {
        if (!Uri.TryCreate(args?[0], UriKind.Absolute, out Uri vaultUri))
        {
            Console.Error.WriteLine("You must pass a Key Vault URI");
        }

        HttpClientHandler handler = new HttpClientHandler
        {
            ServerCertificateCustomValidationCallback = ValidateServerCertificate
        };

        HttpClient httpClient = new HttpClient(handler);
        SecretClientOptions secretClientOptions = new SecretClientOptions
        {
            Transport = new HttpClientTransport(httpClient)
        };

        SecretClient secretClient = new SecretClient(
            vaultUri,
            new DefaultAzureCredential(),
            secretClientOptions);

        Console.WriteLine("Secrets:");
        await foreach (var secret in secretClient.GetPropertiesOfSecretsAsync())
        {
            Console.WriteLine(secret.Name);
        }
    }

    private static bool ValidateServerCertificate(HttpRequestMessage request, X509Certificate2 serverCertificate, X509Chain certificateChain, SslPolicyErrors errors)
    {
        if (serverCertificate.Verify())
        {
            foreach (X509ChainElement element in certificateChain.ChainElements)
            {
                // Check against the intermediate CA.
                if ("B0C2D2D13CDD56CDAA6AB6E2C04440BE4A429C75".Equals(element.Certificate.Thumbprint, StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }
        }

        return false;
    }
}
```

You could also validate the public key, the server certificate itself (rotated more often), or other authoritative data.

Please also note that Microsoft.Azure.KeyVault is deprecated. Customers should move to Azure.Security.KeyVault.*. We also have ARM binaries releasing soon, and many other services on Azure.*, which use a simpler authentication mechanism, more customizable pipeline, better diagnostics, and more. See https://aka.ms/azsdk/intro.

Does that answer your question?
