### ISSUE TITLE
[QUERY] Payload sent to the DiagnosticListeners

### ISSUE THREAD

**Issue by ebbeflarup** [Azure/azure-sdk-for-net#16621]
**Query/Question**
The payload sent to the DiagnosticListerne differs in the packages Azure.Messaging.ServiceBus and Microsoft.Azure.ServiceBus, is this by design?

In the Microsoft.Azure.ServiceBus package, the payload is the message received from the servicebus upon receiving messages shown [here](https://github.com/Azure/azure-sdk-for-net/blob/a135037e4f6d8c6133a216dea072a85d945defeb/sdk/servicebus/Microsoft.Azure.ServiceBus/src/ServiceBusDiagnosticsSource.cs#L639)

This is very usable when the object is, for instance, to adhere to the OpenTelemtry [standards](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/messaging.md) and export to any OpenTelemetry comtatible technology, not just ApplicationInsigths,

However, in the new Microsoft.Azure.ServiceBus package, this information is not available in the current for, since the payload is just a [copy of the activity](https://github.com/Azure/azure-sdk-for-net/blob/a135037e4f6d8c6133a216dea072a85d945defeb/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs#L255) used from [here](https://github.com/Azure/azure-sdk-for-net/blob/a135037e4f6d8c6133a216dea072a85d945defeb/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs#L76) and not the received message, is this on purpose?

**Environment:**
Azure.Messaging.ServiceBus - current version
Microsoft.Azure.ServiceBus - current version

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by pakrym** [comment]
The intent is to produce an activity that already follows the open telemetry messaging guidelines without application developers having to manually adapt them.

**Comment by ramya-rao-a** [comment]
@pakrym Any updates here? If this is a valid feature request or a bug, can you please add the appropriate label and milestone?
