### ISSUE TITLE
Activity parent id for diagnostics

### ISSUE THREAD

**Issue by ebbeflarup** [Azure/azure-sdk-for-net#16620]
Question:

Setting the parent id of the current activity when receiving message through the Azure Servicebus is inconsistent in the current Microsoft.Azure.ServiceBus and this new Azure.Messaging.ServiceBus package, is this by design?

To be more precise, this particular code from the Microsoft.Azure.ServiceBus [MessageDiagnosticsExtensions.cs](https://github.com/Azure/azure-sdk-for-net/blob/c3c91c9f87c696761e2a190e0ff0d931a9085866/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Extensions/MessageDiagnosticsExtensions.cs#L80) sets the new activity parent id, when processing messages, to metadata received in the 'Diagnostic-Id' field.

While this particular code from the Azure.Messaging.ServiceBus [DiagnosticExtensions.cs](https://github.com/Azure/azure-sdk-for-net/blob/c3c91c9f87c696761e2a190e0ff0d931a9085866/sdk/servicebus/Azure.Messaging.ServiceBus/src/Diagnostics/DiagnosticExtensions.cs#L89) sets the data received in the metadata in the 'Diagnostic-Id' field as a linked activity for the current activity. 

Is this by design? Is it correctly understood that this causes different behaviour and also breaks the trace correlation chain since no parent is set here?

And additionally, this particular piece of code from the Azure.Core.Pipeline [DiagnosticScope.cs](https://github.com/Azure/azure-sdk-for-net/blob/a135037e4f6d8c6133a216dea072a85d945defeb/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs#L110) adds a private class 'DiagnosticActivity' which adds the property 'Links' to the Activity class. This is then used in the Azure.Messageing.ServiceBus package [here](https://github.com/Azure/azure-sdk-for-net/blob/a135037e4f6d8c6133a216dea072a85d945defeb/sdk/servicebus/Azure.Messaging.ServiceBus/src/Diagnostics/DiagnosticExtensions.cs#L89). This causes problems when using this package with the OpenTelemetry(or any other package) packages since the OpenTelemetry packages uses the newest version(Version=5.0.0.0) of the "System.Diagnostics.DiagnosticSource" which also add a 'Links' property to the Activity type :)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by pakrym** [comment]
This is the guidance we got for integration with OpenTelemetry and ApplicationInsights.

>Is it correctly understood that this causes different behaviour and also breaks the trace correlation chain since no parent is set here?

It is understood that behavior is different. I don't see it breaking correlation though. The parent of the processing span is whoever started it and links are used to correlate messages.

> And additionally, this particular piece of code from the Azure.Core.Pipeline DiagnosticScope.cs adds a private class 'DiagnosticActivity' which adds the property 'Links' to the Activity class. This is then used in the Azure.Messageing.ServiceBus package here. This causes problems when using this package with the OpenTelemetry(or any other package) packages since the OpenTelemetry packages uses the newest version(Version=5.0.0.0) of the "System.Diagnostics.DiagnosticSource" which also add a 'Links' property to the Activity type :)

Do you see problems with it at runtime?

**Comment by ebbeflarup** [comment]
> It is understood that behavior is different. I don't see it breaking correlation though. The parent of the processing span is whoever started it and links are used to correlate messages.

Maybe I'm asking for something not supported, It's a bit difficult to figure out.
I'm asking because I want to take the diagnostics and export them directly from the application to any OpenTelemetry supported platform, not  necessarily ApplicationInsights.

I just noticed your post [here](https://github.com/Azure/azure-sdk-for-net/issues/16375). Does this mean that you are planning on making everything OpenTelemetry compatiable? And additionally making it possible to subscribe to these diagnostics and handle them however the application developer wants? Is it even neccessary to do anything explicit to export the diagnostics using the [OpenTelemetry dotnet](https://github.com/open-telemetry/opentelemetry-dotnet) exporters like the already existing instrumentation packages for [AspNetCore](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.AspNetCore), the [HTTP client](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.Http) or [SQL](https://github.com/open-telemetry/opentelemetry-dotnet/tree/master/src/OpenTelemetry.Instrumentation.SqlClient)? (I know none of these are related to the Azure SDK and that you guys probably have your own agenda separate from these 3 areas)

I feel like I have completely misunderstood something really basic here, sorry if that's the case :/

>>And additionally, this particular piece of code from the Azure.Core.Pipeline DiagnosticScope.cs adds a private class 'DiagnosticActivity' which adds the property 'Links' to the Activity class. This is then used in the Azure.Messageing.ServiceBus package here. This causes problems when using this package with the OpenTelemetry(or any other package) packages since the OpenTelemetry packages uses the newest version(Version=5.0.0.0) of the "System.Diagnostics.DiagnosticSource" which also add a 'Links' property to the Activity type :)

>Do you see problems with it at runtime?

Never mind this. I guess that since the [DiagnosticActivity](https://github.com/Azure/azure-sdk-for-net/blob/a135037e4f6d8c6133a216dea072a85d945defeb/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs#L110) class is declared private it was never the intention to expose these links anyways :)

**Comment by pakrym** [comment]
>I just noticed your post here. Does this mean that you are planning on making everything OpenTelemetry compatible

Yes, that's the plan. We are going to use ActivitySource and produce Activities that are natively compatible with the OpenTelemetry and don't require any additional collectors. That would include the new Links property.

**Comment by ramya-rao-a** [comment]
@pakrym Any updates here? If this is a valid feature request or a bug, can you please add the appropriate label and milestone?

**Comment by pakrym** [comment]
We since added the ActivitySource/OpenTelemetry support: https://devblogs.microsoft.com/azure-sdk/introducing-experimental-opentelemetry-support-in-the-azure-sdk-for-net/#get-started
