### ISSUE TITLE
DataLakeAclChangeFailedException when InnerException is RequestFailedException should print out all content

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#16631]
Currently the `DataLakeAclChangeFailedException` stores the `RequestFailedException` as an InnerException when a `RequestFailedException` is thrown. Previously when a `RequestFailedException` is thrown, it would print out all the contents like so

```
This request is not authorized to perform this operation using this permission.
RequestId:<requestid>
Time:2020-11-05T01:31:35.8711412Z
Status: 403 (This request is not authorized to perform this operation using this permission.)
ErrorCode: AuthorizationPermissionMismatch

Headers:
x-ms-error-code: AuthorizationPermissionMismatch
x-ms-request-id: 59b92c7b-a01f-0011-3813-b3acf8000000
x-ms-version: 2020-02-10
x-ms-client-request-id: <client-requestid>
Content-Length: 227
Content-Type: application/json;charset=utf-8
Date: Thu, 05 Nov 2020 01:31:35 GMT
Server: Windows-Azure-HDFS/1.0 Microsoft-HTTPAPI/2.0
```

Now it just prints this.
```
An error occurred while recursively changing the access control list. See the InnerException of type Azure.RequestFailedException with Status=403 and ErrorCode=AuthorizationPermissionMismatch for more information.  You can resume changing the access control list using ContinuationToken= after addressing the error.
```

It needs to print out this along with the extra information that `RequestFailedException` prints out.

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
