### ISSUE TITLE
[FEATURE REQ] Ability to specify timeout per operation

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#16643]
**Library or service name.**
Azure.Core
 
**Is your feature request related to a problem? Please describe.**
This is follow up from https://github.com/Azure/azure-sdk/issues/1984 . The UploadFromUrl API that is being introduced is potentially blocking and long running depending on what customer is moving over the network. If customer is aware that their workload require larger timeout for this operation they should be able to specify that without impacting other APIs.

**Comment by tasherif-msft** [comment]
This is available in Python :) 
I will close this issue.

**Comment by kasobol-msft** [comment]
That's .NET repo...

**Comment by tasherif-msft** [comment]
WOOPS sorry about that

**Comment by ljian3377** [comment]
The timeout option is available in JavaScript Azure.Core. But storage chose to hide it from the user. I will expose it for this API.

**Comment by pakrym** [comment]
Core now supports NetworkTimeout on HttpMessage
