### ISSUE TITLE
[BUG] DefaultServiceVersion returns nothing for new Storage

### ISSUE THREAD

**Issue by imtrobin** [Azure/azure-sdk-for-net#16664]
I created a new storage account, and I try to get DefaultServiceVersion. it returns empty  string.

I tried on an old storage, it returns 2018-03-28 fine.

```
            BlobClientOptions options = new BlobClientOptions ();
            options.Retry.MaxRetries = 5;

            // Create our client and make a simple request
            BlobServiceClient client = new BlobServiceClient(connectionString, options);

            Response <BlobServiceProperties> properties = client.GetProperties ();

            Console.WriteLine ($"DefaultServiceVersion:{properties.Value.DefaultServiceVersion}");
```

Azure.Core 1.6.0
Azure.Storage.Blob 12.6.0
Azure.Storage.Common 12.5.2
VS 16.6.2
.NET Core SDK (reflecting any global.json):
 Version:   3.1.301

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @imtrobin, I believe `DefaultServiceVersion` is not automatically set in the service if you have not previously specified it.  Have you set the DefaultServiceVersion on your Storage account?

**Comment by imtrobin** [comment]
I did not set it. I was under the impression that it would set to the oldest version, it's strange that it is not set to a value by default.  I don't remember setting the old storage. Can you confirm this is expected behavior?

**Comment by seanmcc-msft** [comment]
I just ran our unit test for `BlobServiceClient.GetProperties()` on a test account, and DefaultServiceVersion was null in Fiddler.  The service did not return a DefaultServiceVersion.

**Comment by imtrobin** [comment]
So from here, https://azure.microsoft.com/en-us/blog/microsoft-azure-storage-service-version-removal/

I would assume there would be a default version returned. I didn't see empty string as a response

https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-service-properties

**Comment by amnguye** [comment]
Hi, I'm a little confused on what the issue actually is. So you want the `DefaultServiceVersion` to return or you don't. I think @seanmcc-msft already confirmed that it does not. and with this update we validate it will not

https://azure.microsoft.com/en-us/blog/microsoft-azure-storage-service-version-removal-update-extension-to-2016/

I saw on this issue you linked https://github.com/Plasma/AzureBlobUtility/issues/5 that this is something that is changed on the service as per the article above and not on the SDK.

So I guess my next question is, are you just trying to get the DefaultServiceVersion to return in general? To guarantee it, especially with the update, you would have to specify it in the storage account.

Please reactivate if you still have any other question or problems with this.
