### ISSUE TITLE
[Text Analytics] Add tests for CreateRequestFailedException method for Healthcare Async

### ISSUE THREAD

**Issue by suhas92** [Azure/azure-sdk-for-net#16686]
**Query/Question**
How can we help?

Add tests for CreateRequestFailedException method for Healthcare Async. Adding this issue for future tracking. 

**Environment:**
 - Name and version of the Library package used: TextAnalytics 5.2-beta.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by suhas92** [comment]
#16434

**Comment by jsquire** [comment]
Shifting to match the milestone of the associated epic, as the MQ milestone has passed.

**Comment by maririos** [comment]
Method called: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/src/AnalyzeHealthcareEntitiesOperation.cs#L257

We need to understand: 
- When this happens
- What the service returns
- See if the current methods surfaces information in the right way (might need mocking for this)
