### ISSUE TITLE
Event Grid - Migration guide

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#16688]
Create a migration guide for customers transitioning from Track 1 to Track 2 similar to what we have for Service Bus and Event Hubs.

**Comment by ramya-rao-a** [comment]
Please wait for this issue to be updated with the link to the Migration Guide template.

**Comment by ramya-rao-a** [comment]
Please use the template in this [PR that adds the migration guide to our policies](https://github.com/Azure/azure-sdk/pull/2132)

**Comment by jsquire** [comment]
Closing this as a duplicate of #16740
