### ISSUE TITLE
Add unit and/or functional tests for Perf and Stress framework

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#16697]
Add tests to verify the Perf and Stress frameworks work correctly as they are changed over time.

**Comment by JimSuplizio** [comment]
Hi @mikeharder, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
