### ISSUE TITLE
Integrate TestEnvironment into Perf and Stress frameworks

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#16708]
The Perf and Stress frameworks should use the TestEnvironment helper class to integrate with the automatic resource deployment.

https://github.com/Azure/azure-sdk-for-net/pull/16671#discussion_r519018881

**Comment by JimSuplizio** [comment]
Hi @mikeharder, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
