### ISSUE TITLE
Status of Key Vault client for .NET 5 Core CLR

### ISSUE THREAD

**Issue by GuardRex** [Azure/azure-sdk-for-net#1670]
@herveyw

Was wondering if there is any status on getting https://github.com/Azure/azure-sdk-for-net/tree/master/src/KeyVault/Microsoft.Azure.KeyVault.Core for Core CLR (dnxcore50)?

**Comment by herveyw** [comment]
@GuardRex 

Its planned but won't happen until early next year.

**Comment by GuardRex** [comment]
Thx
