### ISSUE TITLE
Azure.Identity.CredentialUnavailableException not marked Serializable

### ISSUE THREAD

**Issue by YouLearnSomethingNewEveryDay** [Azure/azure-sdk-for-net#16702]
Looks similar to this issue https://github.com/Azure/azure-sdk-for-net/issues/4370
When publishing a .Net 4.7.2 App we get the following error:

##[error] ASPNETCOMPILER(0,0): Error ASPRUNTIME: Type 'Azure.Identity.CredentialUnavailableException' in assembly 'Azure.Identity, Version=1.2.3.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' is not marked as serializable.

Looks like the class isn't serialized.

**Comment by AlexGhiondea** [comment]
@schaabs can you take a look here?

**Comment by YouLearnSomethingNewEveryDay** [comment]
Could I get an update on this?
Is it something that will be fixed in Azure.Identity or do we need to add special build parameters to make this work?

**Comment by schaabs** [comment]
@YouLearnSomethingNewEveryDay Thanks for brining this issue to our attention. We will need to fix this in Azure.Identity. I'll update all the custom exception types in Azure.Identity and the fix will go into our next release.

**Comment by YouLearnSomethingNewEveryDay** [comment]
@schaabs Thanks for the update.

**Comment by dil-bpecor** [comment]
Any timeline on this one, I have the same issue.

**Comment by YouLearnSomethingNewEveryDay** [comment]
@schaabs Could you provide me a rough estimate when exception classes will be fixed? My corporation is asking me for an estimate.

**Comment by andrewrimmer** [comment]
We are getting this too. Is there an eta for the fix?

Does anybody have a workaround?
