### ISSUE TITLE
Search: Add batching EventSource

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#16706]
We want to surface detailed information about the performance and behavior of `SearchIndexingBufferedSender` including:
- Summary statistics
   - Document Size
   - Document Count
   - Batch Size
- Info on throttled responses
- Split batches
- Async event handler exceptions being swallowed

**Comment by heaths** [comment]
We might want to consider just making it a Search-specific EventSource (fewer providers should be esier to register for events for customers). We can still have batch-specific events, certainly.
