### ISSUE TITLE
Base exception type for authentication failures

### ISSUE THREAD

**Issue by craigktreasure** [Azure/azure-sdk-for-net#16711]
**Library or service name.**

Future Mixed Reality clients.
 
**Is your feature request related to a problem? Please describe.**

Would be great if there was a common exception type in Azure.Core that we could either extend or throw for authentication failures.

Thanks!

@schaabs

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by pakrym** [comment]
Tacking this working in https://github.com/Azure/azure-sdk-for-net/issues/10759
