### ISSUE TITLE
[BUG] GetAccessTokenAsync returned expired token for a fresh token request

### ISSUE THREAD

**Issue by atiasadir** [Azure/azure-sdk-for-net#16718]
**Describe the bug**
We are using AzureServiceTokenProvider
and somethimes we are getting expired token (permanently, for few hours) for a fresh token requests.

**Expected behavior**
Valid token will be returned by AzureServiceTokenProvider and we will be able to access to Azure Resources

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
We are running a micro-service (in a container in a pod) as part of kubernetes cluster (version 1.16.15)
we are using AAD Pod Identity for the identity management,
the micro-service using a managed identity with the relevant role assignments.
The micro-service have Assigned Identity, which most of the time works properly and get valid token.

unforutnatelly, in a sporadic frequency we are getting expired token.
and we need to restart the service in order to overcome this issue.

```
09:51:54.8646702 HandleExceptionAsync: Exception handler caught tenant XXX Unauthorized exception - consider as Unhealthy
{"Type":"YYY.Exceptions.ZZZZClientExceptionClientException","Message":"**Response code is Unauthorized.
Content: {\"Message\":\"Authorization has been denied for this request.**\"}
.
.
.
-**same error written to log till restart service is performed** (no need to restart the pod, only the micro-service container)
.
.

11:21:46.2729312 HandleExceptionAsync: Exception handler caught tenant XXX Unauthorized exception - consider as Unhealthy    
{"Type":"YYY.ZZZZClientException","Message":"Response code is Unauthorized. Content: {\"Message\":\"Authorization has been denied for this request.\"}
```
we are using this nuget package https://www.nuget.org/packages/Microsoft.Azure.Services.AppAuthentication

**Steps To Reproduce**
We don't have steps the exact stetps to reproduce.
but we can say that it happened every few weeks on different services.

**Environment:**
 - VisualStudioVersion: 15.0.28010.2041
 - Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

- .NET Core SDKs installed:
  No SDKs were found.

- .NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**It's important to mention that** 

-	Relevant Node, Pod, MIC, NMI -  logs looks totally ok without any issue from AAD Pod Identity side.
Identity assigned to the VMSS properly, other Pods on the same node got token as expected during the failure (09:51:54-11:21:46)
-	Stress tests for Identity request from Pod CLI works as expected, also in described bug, the node wasn’t too loaded and it should recover after few seconds and not stuck ~1h.
-	Azure Assigned Identity CRD age of the problematic pod has ~30h age immediately after the service application restart (it means that the container restart was transparent from AAD Pod Identity side, and nothing was changed on this side)
-	Only container restart without pod deletion solve the issue – this is really good point.
Sometimes the token request failed and it should be transient, in this case it was permanent,
AAD Pod identity handle requests in a Pod (and not container) level, As you know, Azure Assigned Identity created per pod.

we are using now Microsoft.Azure.Services.AppAuthentication- (updated from 1.3.1 to 1.6.0)
we upgrade now to version 1.6.0, in order to be able to do force cache update as fallback, for more info see this PR https://github.com/Azure/azure-sdk-for-net/pull/12633
we suspect that there is a caching issue that not working properly.

**Comment by jsquire** [comment]
//cc: @nonik0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by anaismiller** [comment]
@atiasadir 
It appears that the issue is with the caching of the token. You are using the function to call for the token, but it is still using the one in the cache. The response has an ExpiresOn property that you can view to see if this is the case. Link to method property [here](https://github.com/Azure/azure-sdk-for-net/blob/355e28da265e90da680cbfe77b7feafa4662d713/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/AppAuthenticationResult.cs#L23). 

Can you please try using this method instead: [GetAuthenticationResultAsync(string resource, string tenantId,
            bool forceRefresh, CancellationToken cancellationToken = default)](https://github.com/Azure/azure-sdk-for-net/blob/661b4eccf92e8accba04e5ecd081fb5913ded81a/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/AzureServiceTokenProvider.cs#L346)
It makes use of the GetAuthResultAsyncImpl function that looks in the cache, sees if the token is [near expiry](https://github.com/Azure/azure-sdk-for-net/blob/9a916fe5765286fb119b71cc5dee01d1eae0e93a/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/Cache/AppAuthResultCache.cs#L27), and return a result accordingly.

**Comment by varunsh-msft** [comment]
@atiasadir Would you be able to fetch token using GetAuthenticationResultAsync and confirm that the returned token is expired? We already check for this in the library and do not believe it returns expired tokens. So it would be good to get confirmation on that. If you can get the result and log expiry info if the token is already expired, it will provide clear evidence of the issue. Thanks!

**Comment by joeyeng** [comment]
@varunsh-msft @jsquire @atiasadir I'm getting expired access tokens from AzureServiceTokenProvider as well when calling GetAccessTokenAsync: https://stackoverflow.com/questions/66502950/why-is-azureservicetokenprovider-returning-an-expired-access-token

I'll give GetAuthenticationResultAsync  a try and report back on my findings.

**Comment by joeyeng** [comment]
Okay, I tried GetAuthenticationResultAsync but it gave me the same expired token. ExpiredOn value was the same expired date that I was getting with GetAccessTokenAsync.

**Comment by anaismiller** [comment]
@joeyeng Would you be able to retry? I'm curious if it was an issue with VS authentication and changing to the Azure.Identity library and following their guide made you re-auth in VS.

From your SO question, I got that you used AppAuth 1.6.1 and using the lib for VS auth (`connection string = "RunAs=Developer; DeveloperTool=VisualStudio"`). Can you also share your VS version?

**Comment by joeyeng** [comment]
@anaismiller My org's AAD auth policy logs us out all the time, so I have to frequently check my VS auth and re-authententicate it. So unfortunately that is not the issue. I'm on VS2019 16.8.4. I was getting expired tokens in Azure too though.

**Comment by anaismiller** [comment]
Thanks Joey for the response. I am going to assume this was not an AppAuth library issue, but something larger that got fixed based on your previous response. Still a little suspicious that the token was able to travel through as expired, but I am unable to reproduce it.
 
Adir also confirmed with me that this is no longer an issue.
