### ISSUE TITLE
[QUERY] using the c# sdk to upgrade control plane only sample 

### ISSUE THREAD

**Issue by digeler** [Azure/azure-sdk-for-net#16717]
**Query/Question**
How can we help?
Looking for a c# sample on how to upgrade control plane only 
cli has this switch : --control-plane-only -k 1.18.8 --debug
how do i implement it using the sdk ?

**Comment by jsquire** [comment]
Hi @digeler.  Thanks for reaching out.   I'm afraid that I'm not sure what you're asking, nor what SDK libraries you're working with, so I'm unable to route you to the folks that can best assist.    Can you provide a bit more context around your scenario and which libraries from the SDK are in use?

**Comment by jsquire** [comment]
Hi @digeler.  Unfortunately, with the current context, we're unable to assist at this time.  Please feel free to reopen with additional context if you're still experiencing difficulties that we can help with.
