### ISSUE TITLE
Alternative to GetBlobReferenceFromServer in v12 library

### ISSUE THREAD

**Issue by TheAzureGuy** [Azure/azure-sdk-for-net#16719]
Our code is heavily dependent on ability to read blobs using their fully-qualitied URIs. We don't always know the source container names, nor we care about it since it is in the URI. We used to be calling into **GetBlobReferenceFromServer**. With migration to Azure.Storage.Blobs v12, this ability has been lost. Please advise.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @TheAzureGuy,

I would recommend using one of the constructors for [BlobClient](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs), [BlockBlobClient](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs), [PageBlobClient](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/PageBlobClient.cs), or [AppendBlobClient](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/AppendBlobClient.cs) that take the Uri of a blob:

- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L105
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L128
- https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L151

These constructors exist for all 4 blob client types.

-Sean

**Comment by TheAzureGuy** [comment]
Nicely done! Love these simplifications and standardization in the API. Thanks a lot, Sean and team!
