### ISSUE TITLE
Update Learn modules for Key Vault

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16728]
This issue is to review the learn modules in https://docs.microsoft.com/en-us/learn/ that are for .Net developers in the area of Key Vault and update them if they are not using the latest version of the Key Vault package

- [x] manage-secrets-with-azure-key-vault
  - [x] https://github.com/MicrosoftDocs/learn-pr/blob/master/learn-pr/azure/manage-secrets-with-azure-key-vault/includes/5-access-secrets-from-web-app.md
- [x] manage-secrets-with-azure-key-vault
  - [x] https://github.com/MicrosoftDocs/learn-pr/blob/master/learn-pr/azure/authenticate-apps-with-managed-identities/includes/6-build-applications-using-managed-identities.md
  - [x] https://github.com/MicrosoftDocs/learn-pr/blob/master/learn-pr/azure/authenticate-apps-with-managed-identities/includes/7-exercise-configure-app-using-managed-identity.md
    - [x] Dependency project: https://github.com/MicrosoftDocs/mslearn-authenticate-apps-with-managed-identities/tree/master/secretapp

https://github.com/MicrosoftDocs/mslearn-authenticate-apps-with-managed-identities/pull/3

**Comment by christothes** [comment]
Pending PR merges
