### ISSUE TITLE
Bug bash to find samples for Event Hubs that need to use the latest package

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16737]
_Update from @ramya-rao-a_ 

Review the .Net samples for Event Hubs in the below locations to find the ones that do not use the latest version of the package. Update this issue with the list of samples that need updating.

- [Event Hubs .Net samples repos under Azure-samples org](https://github.com/Azure-Samples?q=%22Event+Hubs%22&type=&language=c%23)
- [Event Hubs .Net samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Event%20Hubs%22&languages=csharp)

Additionally, ensure the samples that live next to the source code for Event Hubst in this repo shows up in [Event Hubs .Net samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Event%20Hubs%22&languages=csharp). This is done by setting up the right metadata. Ensure that these samples are not outdated.

**Comment by jsquire** [comment]
There are several archived repositories with old content under the `Azure Samples` org.   I ignored those, as there's no opportunity to modernize.

### Using the legacy SDK

- [Getting started on managing event hub geo-disaster recovery using C#](https://docs.microsoft.com/en-us/samples/azure-samples/eventhub-dotnet-manage-event-hub-geo-disaster-recovery/getting-started-on-managing-event-hub-geo-disaster-recovery-using-c/)
- [Azure IoT Device Telemetry Simulator](https://docs.microsoft.com/en-us/samples/azure-samples/iot-telemetry-simulator/azure-iot-device-telemetry-simulator/) 
- [Getting started on managing event hub and associated resources using C#](https://github.com/Azure-Samples/eventhub-dotnet-manage-event-hub) 
-  _(wow.  This is using a preview of T0)_
- [Getting started on managing event hub geo-disaster recovery using C#](https://github.com/Azure-Samples/eventhub-dotnet-manage-event-hub-geo-disaster-recovery)  _(wow.  This is using a preview of T0)_

### Bonus commentary

- [Getting started - Managing Event Hub Events using Azure .NET SDK](https://docs.microsoft.com/en-us/samples/azure-samples/azure-samples-net-management/eventhub-manage-eventhub-events/) - There are several of these that are basically duplicates and all are low-quality.   I think it would be helpful to de-dup and refine the content, both code and text.

**Comment by jsquire** [comment]
Analysis complete;  transferring ownership for follow-up actions.

**Comment by ramya-rao-a** [comment]
Thanks @jsquire!
