### ISSUE TITLE
Updated outdated content from bug bash in docs.microsoft.com for Key Vault

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16732]
_Update from @ramya-rao-a_ :

- The below two pages are using the older `Microsoft.Azure.KeyVault` and `Microsoft.Azure.Services.AppAuthentication` packages. Should these be using the new KeyVault and Identity package instead?
  - [Save Web App Secrets](https://docs.microsoft.com/en-us/previous-versions/azure/key-vault/vs-secure-secret-appsettings?toc=/azure/key-vault/general/toc.json&bc=/azure/key-vault/breadcrumb/toc.json)
  - [Service to service to Key Vault using .Net](https://docs.microsoft.com/en-us/azure/key-vault/general/service-to-service-authentication). 
- The below places have Quick start links only for secrets, not for keys and certificates. Other languages are missing links too, so consider doing an update for other languages as well
  - [x] The [table for all Key Vault packages in Client libraries page](https://docs.microsoft.com/en-us/azure/key-vault/general/client-libraries#client-libraries-per-language-and-object) is missing the Quick Start for Keys and Certificates. 
  - [x] The section for [Manage keys, certificates and secrets](https://docs.microsoft.com/en-us/azure/key-vault/general/developers-guide#manage-keys-certificates-and-secrets)
  - [x] The [Code examples table](https://docs.microsoft.com/en-us/azure/key-vault/general/authentication#code-examples) section under Authenticate to Key Vault.
- [x] The [Code examples table](https://docs.microsoft.com/en-us/azure/key-vault/general/authentication#code-examples) section under Authenticate to Key Vault and the [Reference node under Secrets](https://docs.microsoft.com/en-us/azure/key-vault/secrets/about-secrets) has an entry for .Net SDK v3. Why?

**Comment by christothes** [comment]
https://github.com/Azure/azure-docs-sdk-dotnet/pull/1670

**Comment by ramya-rao-a** [comment]
@christothes, Re-opening this issue after finding a few places for Key Vault under https://docs.microsoft.com/en-us/azure/key-vault/general/ where we can use a few updates

**Comment by christothes** [comment]
@ramya-rao-a 
> - The below two pages are using the older `Microsoft.Azure.KeyVault` and `Microsoft.Azure.Services.AppAuthentication` packages. Should these be using the new KeyVault and Identity package instead?
>  - [Save Web App Secrets](https://docs.microsoft.com/en-us/previous-versions/azure/key-vault/vs-secure-secret-appsettings?toc=/azure/key-vault/general/toc.json&bc=/azure/key-vault/breadcrumb/toc.json)
>  - [Service to service to Key Vault using .Net](https://docs.microsoft.com/en-us/azure/key-vault/general/service-to-service-authentication). 

Both of these pages seem to be clearly marked as older or non-recommended versions. Would it still make sense to update these?

**Comment by ramya-rao-a** [comment]
Nah, we should be good.
I will follow up with Jon on whether they need to be updated or not
