### ISSUE TITLE
Bug bash to find samples for Key Vault that need to use the latest package

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16731]
_Update from @ramya-rao-a_ 

Review the .Net samples for Key Vault in the below locations to find the ones that do not use the latest version of the package. Update this issue with the list of samples that need updating.

- [Key Vault .Net samples repos under Azure-samples org](https://github.com/Azure-Samples?q=%22Key+Vault%22&type=&language=c%23)
  - [ ] key-vault-dotnet-manage-key-vaults
    - This is a management sample
  - [ ] key-vault-dotnet-authentication
    - This shows how to authenticate to KV -- we need to update this to use the newer version
  - [ ] app-service-managed-identity-key-vault-csharp
    - Needs to be updated
  - [ ] key-vault-dotnet-managed-storage
    - Needs to be updated
  - [x] key-vault-dotnet-recovery
    - Already updated to Track 2 library, but not absolutely latest version.
  - [x] storage-dotnet-client-side-encryption
    - This repo is archived
  - [x] app-service-dotnet-access-key-vault-by-msi-for-web-apps
    - Already updated to Track 2 library, but not absolutely latest version.
  - [ ] key-vault-dotnet-vnet
    - This would need to be updated
  - [x] key-vault-dotnet-vm-msi-service-bus
    - This repo is archived
  - [ ] sql-database-dotnet-manage-sql-server-keys-with-azure-key-vault
    - This is a management sample
- [Key Vault .Net samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Key%20Vault%22&languages=csharp)
  - [ ] Getting started on managing key vaults in C#
    - This is an administration sample
  - [x] Cache certain responses from Key Vault
     - Already done.
  - [ ] Getting Started with Azure Key Vault with .NET Core
     - Needs to be updated
  - [ ] .NET SDK samples illustrating the management and consumption of Azure Key Vault-managed storage account keys.
    - Uses old SDK but points to the newer libraries.
  - [ ] How to recover and restore Azure Key Vault entities with .NET
    - Needs to be updated
  - [x] Get a Certificate Including the Private Key
    - Uses Track 2
  - [x] Use Key Vault from App Service with Azure Managed Identity
    - Uses Track 2
  - [ ] .NET SDK sample illustrating virtual network-based management of access policies for Azure key vaults.
    - Management sample
  - [x] Getting started on safeguarding Web app secrets in Key Vault using convenience API
    - Uses Track 2
  - [x] ShareLink
    - Uses Track 2

Additionally, ensure the samples that live next to the source code for Key Vault in this repo shows up in [Key Vault .Net samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Key%20Vault%22&languages=csharp). This is done by setting up the right metadata. Ensure that these samples are not outdated.
  - [x] They seem to have the right metadata.

**Comment by ramya-rao-a** [comment]
@christothes Re-opening this issue with additional instructions added to the issue description following the approach we are using across languages and services. Please take another look

**Comment by ramya-rao-a** [comment]
Thanks for updating the issue description @AlexGhiondea 
@christothes Please use https://github.com/Azure/azure-sdk-for-net/issues/16733 to update the above samples
