### ISSUE TITLE
Updated outdated content from bug bash in samples for Service Bus

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16748]
Update the outdated content found in https://github.com/azure/azure-sdk-for-net/issues/16746

**Comment by ramya-rao-a** [comment]
Closing this issue as there is a separate effort to update samples by another team. We will be using what we found in https://github.com/Azure/azure-sdk-for-net/issues/16746 to cross reference samples that need an update
