### ISSUE TITLE
Updated outdated content from bug bash in docs.microsoft.com for Service Bus

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16747]
_Update from @ramya-rao-a :_

A lot of content under https://docs.microsoft.com/en-us/azure/service-bus-messaging/ has links going to classes from older packages or samples for older packages. The content under `Quickstarts` and `Tutorials` nodes are good. Its the `Concepts` and `How-to guides` that need a big sweep to find such content and fix them. Please work with @spelluru to get an exhaustive list

**Comment by spelluru** [comment]
For GA, I focused on updating quick starts, tutorials, samples page, links from the reference node. I have a spreadsheet with the list of articles from the Concepts and How-to nodes that need to be updated. I am planning to prioritize them based on page views. I will be out of office from 12/14 until new year and Ashish is out too. Sorry. I will pick it up first thing when I come back in Jan and work with you on it. I would definitely need help with updating all these articles. 

Thanks.

**Comment by ramya-rao-a** [comment]
No worries @spelluru, I did recall you had this list, so looped you in here before we made a sweep of our own :)
We can do this in the first week of Jan once you are back, enjoy your time off!

**Comment by JoshLove-msft** [comment]
This was completed as part of MQ.
