### ISSUE TITLE
Bug bash to find samples for Service Bus that need to use the latest package

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16746]
_Update from @ramya-rao-a_ 

Review the .Net samples for Service Bus in the below locations to find the ones that do not use the latest version of the Service Bus package. Please note that some of these maybe using the preview version of the latest Service Bus package, these need to be identified as well. Update this issue with the list of samples that need updating.

- [Service Bus .Net samples repos under Azure-samples org](https://github.com/Azure-Samples?q=%22Service+Bus%22&type=&language=c%23)
- [Service Bus .Net samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Service%20Bus%22&languages=csharp)

Additionally, ensure the samples that live next to the source code for Service Bus in this repo shows up in[Service Bus .Net samples under docs.microsoft.com/samples](https://docs.microsoft.com/en-us/samples/browse/?terms=%22Service%20Bus%22&languages=csharp). This is done by setting up the right metadata. Ensure that these samples are not outdated.

**Comment by JoshLove-msft** [comment]
- https://github.com/Azure-Samples/service-bus-dotnet-messaging-performance contains an app for running throughput tests. It currently uses Track 1.
- https://github.com/Azure-Samples/service-bus-dotnet-manage-queue-with-basic-features - uses Track 1
- https://github.com/Azure-Samples/key-vault-dotnet-vm-msi-service-bus/blob/master/sampleSecretMSI/sampleSecretMSI/GetSecretMSI.cs uses Track 0
- https://github.com/Azure-Samples/event-grid-relay-listener uses Track 0
