### ISSUE TITLE
Swagger to SDK C#

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16752]

**Comment by ShivangiReja** [comment]
Track-2 SDK automation is enabled for c#. For more details check- https://github.com/Azure/azure-sdk-for-net/pull/17193

**Comment by ShivangiReja** [comment]
[Here](https://github.com/Azure/azure-rest-api-specs/pull/12169/files) we have enabled track-2 sdk automation in `Azure/azure-rest-api-specs` repo.
