### ISSUE TITLE
Investigate flaky tests and address issues as applicable

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#16754]

**Comment by maririos** [comment]
Thanks to the reports in: 

The information for the last 10 days (ish) looks like this:
![image.png](https://images.zenhubusercontent.com/583ddbb0b9dc3c622022b006/11467390-4f32-4ec2-b89c-f72c1a3ac954)

For now I am looking at schedule builds - Test resources failures as it is the area with the majority of errors.

There are 3 major categories:
- Individual libraries
  - Synapse specially. PR https://github.com/Azure/azure-sdk-for-net/pull/17460 might help with the errors here.
- weekly builds
  - https://github.com/Azure/azure-sdk-for-net/issues/17483
  - https://github.com/Azure/azure-sdk-for-net/issues/17484
  - https://github.com/Azure/azure-sdk-for-net/issues/17486
- smoke-tests builds
  - Failing for USGov and China clouds. => @benbp is looking into it :)

**Comment by benbp** [comment]
@maririos The china cloud failures appear to be flakiness downloading resources from github.

I have an ICM that I think is never going to be responded to for the usgov failures: https://portal.microsofticm.com/imp/v3/incidents/details/216412834/home. Working on figuring out how to submit a support request against us gov cloud.

**Comment by maririos** [comment]
After looking at the `Unknown` failures for the past 10 days, most of them are related to `Inheritdoc` errors. some have been fixed thanks to @christothes  and PR https://github.com/Azure/azure-sdk-for-net/pull/17429. For remaining  failures, issue https://github.com/Azure/azure-sdk-for-net/issues/17549 has more information.

**Comment by maririos** [comment]
For this week the issues reported/created are:
- Tables weekly tests in Canary: https://github.com/Azure/azure-sdk-for-net/issues/17714
- Mixed reality tests provisioning wrong region: https://github.com/Azure/azure-sdk-for-net/issues/17715
- Attestation tests provisioning wrong region: https://github.com/Azure/azure-sdk-for-net/issues/17716
- KeyVault flaky certificate cancel tests: https://github.com/Azure/azure-sdk-for-net/issues/17718

**Comment by maririos** [comment]
As conclusion for the work done in this issue:
- Most build failures were focused on the weekly pipelines. Then eng services starting adding support for new regions and different services support different regions which was not as generic as the approach initially planned by eng services. Most builds have been fixed and remaining failures have issues opened and assigned.
- Smoke test pipeline is also dead, but errors are understood and eng services has been working on fixing it.

As for other errors:
- If library has an owner in our team, errors get looked up and either assigned or test disabled.
- For other services onboarding our infrastructure it is not clear how the pipelines are set, who owns the pipelines, and the health of them. At the same time, email notifications for build failures might not be set so they don’t know about the failures.
=> FYI @benbp as you might now better how the notifications are set
