### ISSUE TITLE
[Service Bus] Review Quick Start doc for Track 2 Service Bus

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#16777]
This issue is to track the review of the quick start docs that @spelluru has written for Azure.Messaging.ServiceBus library.
Use either this issue or email to share feedback with @spelluru and close this issue once we are satisfied with the content.

- [Quick start for Queues](https://review.docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues?branch=release-service-bus-track2-sdk-ga)
- [Quick start for Topics & Subscriptions](https://review.docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions?branch=release-service-bus-track2-sdk-ga)

**Comment by spelluru** [comment]
Hi @JoshLove-msft - Please wait until tomorrow morning to review the quick start. I am going to test with the latest preview packages and update the quick starts today. Thanks!

**Comment by spelluru** [comment]
Hi @JoshLove-msft - The above two articles are ready for your review now. I tried to keep the quick start as simple as possible but with these in mind: 

- Use Async
- Use batching

And, provide a link to all the samples on GitHub. 

I appreciate if you could review and provide your feedback as soon as you can. 

Thanks,
Sreedhar

**Comment by JoshLove-msft** [comment]
When creating a message we can just do:
```cs
            ServiceBusMessage message = new ServiceBusMessage("Hello world!");
```

**Comment by JoshLove-msft** [comment]
```cs 
await Task.Delay(5000);
```

Instead of doing this, let's use:
``` 
// press any key to end the processing
Console.ReadKey();
```

**Comment by JoshLove-msft** [comment]
```cs
static string subName = "<SUBSCRIPTION NAME>";
```
Please use `subscriptionName`

**Comment by JoshLove-msft** [comment]
LGTM!

**Comment by JoshLove-msft** [comment]
@jsquire I noticed the Event Hubs quick start doesn't have the same degree of checks that were added for Service Bus - https://review.docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-send?branch=release-service-bus-track2-sdk-ga

**Comment by spelluru** [comment]
@JoshLove-msft - Thanks for the feedback. Making the changes now. Will upload them soon. Thanks.

**Comment by spelluru** [comment]
@JoshLove-msft - 

When I try with the following code:

```
                // start processing 
                await processor.StartProcessingAsync();

                Console.WriteLine("Press any key to end the processing");
                Console.ReadKey();

                // stop processing 
                await processor.StopProcessingAsync();
```

I get the following output:

```
Sent a single message to the queue
Sent a batch of messages to the queue: myqueue
**Press any key to end the processing**
Received: Hello world!
Received: First message in the batch
Received: Second message in the batch
Received: Third message in the batch
```

And then it does not terminate the program even if I press any key. It ends after a few minutes.

**Comment by spelluru** [comment]
@JoshLove-msft - The StopProcessingAsync method is taking sometime to complete. Is that normal? Thanks.

**Comment by spelluru** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/137952

**Comment by spelluru** [comment]
@JoshLove-msft - I have updated both quick starts based on your feedback. Please review when you get a chance. Thanks.

**Comment by JoshLove-msft** [comment]
Can we change the batching code to look like this:

```cs
            while (messages.Count > 0)
            {
                using ServiceBusMessageBatch messageBatch = await sender.CreateMessageBatchAsync();
                // if the first message can't fit, then it is too large
                if (!messageBatch.TryAddMessage(messages.Peek()))
                {
                    throw new Exception($"Message {messageCount - messages.Count} is too large and cannot be sent.");
                }
                while (messages.Count > 0 && messageBatch.TryAddMessage(messages.Peek()))
                {
                    messages.Dequeue();
                }
                await sender.SendMessagesAsync(messageBatch);
            }
```

**Comment by spelluru** [comment]
@JoshLove-msft - 

Sorry. I am not sure where this code fits in the quick start code. 

I have a CreateMessages method that creates a list of messages. The SendMessageBatchAsync method creates batches and sends them to Service Bus. I can't use Peek or Dequeue methods on the list of messages.

**Comment by jsquire** [comment]
> @jsquire I noticed the Event Hubs quick start doesn't have the same degree of checks that were added for Service Bus - https://review.docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-send?branch=release-service-bus-track2-sdk-ga

@JoshLove-msft:  Not sure that I'm following the context.   Can you help me understand what "the checks" are?

**Comment by spelluru** [comment]
@JoshLove-msft - I have tried to adapt the logic in your code snippet to the quick start and seems to work. Can you please review the following code and tell me if you see any issues? Thanks. 

```
                IList<ServiceBusMessage> listOfMessages = CreateMessages();
                int nMessages = listOfMessages.Count;
                int counter = 0;

                while (nMessages > 0)
                {
                    using ServiceBusMessageBatch messageBatch = await sender.CreateMessageBatchAsync();

                    // if the first message itself is too large
                    if (!messageBatch.TryAddMessage(listOfMessages[counter]))
                    {
                        throw new Exception($"Message {counter} is too large and cannot be sent.");
                    }

                    while (nMessages > 0 && messageBatch.TryAddMessage(listOfMessages[counter]))
                    {
                        counter++;
                        nMessages--;
                    }
                    await sender.SendMessagesAsync(messageBatch);
                }
```

**Comment by JoshLove-msft** [comment]
Queue is a .NET queue. To add the messages to it we would just call https://docs.microsoft.com/en-us/dotnet/api/system.collections.queue.enqueue?view=net-5.0

**Comment by JoshLove-msft** [comment]
> > @jsquire I noticed the Event Hubs quick start doesn't have the same degree of checks that were added for Service Bus - https://review.docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-send?branch=release-service-bus-track2-sdk-ga
> 
> @JoshLove-msft: Not sure that I'm following the context. Can you help me understand what the "checks" are?

In the quick start for EH, it doesn't actually check the return value of `TryAdd`

**Comment by jsquire** [comment]
> In the quick start for EH, it doesn't actually check the return value of TryAdd

Thanks.... yeah.   We definitely need to go and fix up some of that.   Our samples were a bit... loose... in some of those conventions assuming some understanding that we shouldn't have.   The samples rewrite fixed those oversights, but we need to go through and fan those changes out;  there's time in MQ set aside for that.

**Comment by spelluru** [comment]
@JoshLove-msft - I had to make a slight modification to get it to work. I added a DeQueue if the first message is added successfully to the batch. Otherwise, I was getting a duplicate first message. 

```
                // create a sender for the topic 
                ServiceBusSender sender = client.CreateSender(topicName);

                Queue<ServiceBusMessage> messages = CreateMessages();
                int messageCount = messages.Count;
                while (messages.Count > 0)
                {
                    using ServiceBusMessageBatch messageBatch = await sender.CreateMessageBatchAsync();
                    // if the first message can't fit, then it is too large
                    if (messageBatch.TryAddMessage(messages.Peek()))
                    {
                        messages.Dequeue();
                    }
                    else
                    {
                        throw new Exception($"Message {messageCount - messages.Count} is too large and cannot be sent.");
                    }

                    while (messages.Count > 0 && messageBatch.TryAddMessage(messages.Peek()))
                    {
                        messages.Dequeue();
                    }
                    await sender.SendMessagesAsync(messageBatch);
                }

                Console.WriteLine($"Sent a batch of {messageCount} messages to the topic: {topicName}");
```

**Comment by spelluru** [comment]
https://github.com/MicrosoftDocs/azure-docs-pr/pull/138085

**Comment by spelluru** [comment]
@JoshLove-msft - Please see the updated articles and close this GitHub issue if you are fine with the content. Thanks. 


* [Quick start for Queues](https://review.docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues?branch=release-service-bus-track2-sdk-ga)
* [Quick start for Topics & Subscriptions](https://review.docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-how-to-use-topics-subscriptions?branch=release-service-bus-track2-sdk-ga)

**Comment by JoshLove-msft** [comment]
There is a typo in the comments:
                    // deque the message from the .NET queue once the message is added to the batch
should be dequeue

**Comment by JoshLove-msft** [comment]
Aside from the typo, it looks great! thanks!

**Comment by spelluru** [comment]
> dequeue

Fixed it in this PR: https://github.com/MicrosoftDocs/azure-docs-pr/pull/138178. 

Thank you,
