### ISSUE TITLE
The requested path does not exist

### ISSUE THREAD

**Issue by DominikErnst** [Azure/azure-sdk-for-net#16770]
Hello,

I receive following error message. I find no sample code or good documentation. so maybe someone knows how to correct my shortened code.

**Microsoft.Azure.ApplicationInsights.Query.Models.ErrorResponse
Code=PathNotFoundError, Message=The requested path does not exist**

Source:
```csharp
                private GetMetrics()
		{
			var appId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx";
			var apiKey = "xxxxxxxxxxxxxxxxuxxxxxxxxxxxxxxxxxxxxxx";

			var baseUrl = new Uri("https://api.applicationinsights.io");
			// var baseUrl = new Uri("https://api.applicationinsights.io/");
			// var baseUrl = new Uri("https://api.applicationinsights.io/v1");
			// var baseUrl = new Uri("https://api.applicationinsights.io/v1/");

			var creds = new ApiKeyClientCredentials(apiKey);

			using (var client = new ApplicationInsightsDataClient(baseUrl, creds))
			{
				**_var results = await client.Events.GetExceptionEventsAsync(appId);    // -> PathNotFoundError-Exception_**

                                // ...
                                // work with results
                                // ...
			}
		}
```

THX a lot

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by adymorz** [comment]
I get the same error when running the following code which is an example from the [documentation](https://learn.microsoft.com/en-us/dotnet/api/azure.monitor.query.logsqueryclient?view=azure-dotnet):

```c#
logsQueryClient = new LogsQueryClient(tokenCredential);
Response<IReadOnlyList<string>> response = await _logsQueryClient.QueryWorkspaceAsync<string>(
    _logAnalyticsWorkspaceResourceId,
    "AzureActivity | summarize Count = count() by ResourceGroup | top 10 by Count | project ResourceGroup",
    new QueryTimeRange(TimeSpan.FromDays(1)));
return response.Value;
```

There are a lot of error issues without solution, also this one. Is this project still maintained?

**Comment by DominikErnst** [comment]
@scottaddie Thanks for the info, it's been a long time and I forgot how I solved it, but good to know that the new package is called 'Azure.Monitor.Query' and how to migrate.
