### ISSUE TITLE
Add support for the Azure PowerShell login in Azure.Identity

### ISSUE THREAD

**Issue by olandese** [Azure/azure-sdk-for-net#16782]
I use Azure Powershell a lot, and I would like to see support for it in the Azure.Identity, like a AzurePowerShellCredential class.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by olandese** [comment]
I did it myself, see my PR:

https://github.com/Azure/azure-sdk-for-net/pull/17081

**Comment by olandese** [comment]
My pr 17081 has been merged :)
