### ISSUE TITLE
[Service Bus] Update migration guide with a list of features from previous library that are not supported yet

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#16788]
We have the below features in the `Microsoft.Azure.Servicebus` library that are not yet supported in the new `Azure.Messaging.ServiceBus` library. The migration guide should call these out with a note that upcoming updates would cater to these

- Cross entity transactions
- Plugin support
- Support the different AMQP body section types in the message

Also worth calling out are
- ServiceBusMessage vs ServiceBusReceivedMessage
- For advanced users familiar with AMQP, you can now set the header, footer, message annotations and properties on the AMQP message and read the same

**Comment by ramya-rao-a** [comment]
@SeanFeldman, Thanks for the feedback on this topic. Please feel free to suggest anything that I may have missed.

**Comment by JoshLove-msft** [comment]
As per https://github.com/Azure/azure-sdk-for-net/issues/16773#issuecomment-724270638, we are currently not supported the session wait time.

**Comment by SeanFeldman** [comment]
Testing types are not mentioned. Aside from that looks good.

One thing that caught my attention:
> Cross entity transactions

This should be supported AFAIK. @JoshLove-msft can confirm.

**Comment by JoshLove-msft** [comment]
> Testing types are not mentioned

Do you mean the model factories?

**Comment by ramya-rao-a** [comment]
Hey @SeanFeldman 

Regarding the cross entity transactions, the service team is considering alternatives to implement this feature that will make it more intuitive than the elusive `SendVia` option on the sender. In the current `Microsoft.Azure.ServiceBus` this will be done in a backward compatible way. In the new `Azure.Messaging.ServiceBus` library, we want to wait until this new design is flushed out a bit more. Therefore, we are pulling out the `SendVia` option in the upcoming release. We will add the new design in the new year.

Once we have the design flushed out a bit, we will create an issue with the details, ship it in a preview to get feedback and a chance for folks to try it out.

cc @axisc for a reminder to publish the said design when ready

**Comment by SeanFeldman** [comment]
> Once we have the design flushed out a bit, we will create an issue with the details, ship it in a preview to get feedback and a chance for folks to try it out.

Is this something that can be viewed?

The fact that the SDK is out of preview and has no features **required** by customers makes it unusable. `SendVia` is something a very large number of my customers depend upon. We cannot start moving to the new SDK w/o it.

**Comment by ramya-rao-a** [comment]
Yes, the details of how the SDK is expected to react to the service changes to the SendVia feature can be viewed will be made available in the next week. Please subscribe to https://github.com/Azure/azure-sdk-for-net/issues/17355 which we will be updating with the said details.
