### ISSUE TITLE
[QUERY] Cosmos Sql Container Indexing Policy Included/Excluded paths are get only. Why?

### ISSUE THREAD

**Issue by coppercosmo** [Azure/azure-sdk-for-net#16793]
**Query/Question**
Why are included and excluded paths `get` only for Cosmos creation via Azure.ResourceManager.CosmosDB? Shouldn't I be able to set the paths upon creation or update?

**Environment:**
 - Azure.ResourceManager.CosmosDB 1.0.0-preview.1 
 - Windows 10 .Net Core 3.1
 - Visual Studio 16.7.7

**Comment by markcowl** [comment]
@YalinLi0312 Please verify if this property is unsettable in the SDK, and route this issue appropriately

**Comment by YalinLi0312** [comment]
The IncludedPaths and ExcludedPaths in IndexingPolicy are [unsettable](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/IndexingPolicy.cs#L47), and I don't see they are read-only in it's [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2020-09-01/cosmos-db.json#L7110). @pakrym Can you take a look?

**Comment by coppercosmo** [comment]
I found a way to achieve what I was looking for. After the initial `SqlContainerCreateUpdateParameters` creation, I have to add each item to the list like so:


    var parameters = new SqlContainerCreateUpdateParameters(new SqlContainerResource(containerName), new CreateUpdateOptions())
            {
                Location = sqlDbLocation, 
                Resource =
                {
                    IndexingPolicy = new IndexingPolicy
                    {
                        Automatic = containerConfig.Settings.IndexingPolicy.Automatic,
                        IndexingMode = MapToIndexingMode(containerConfig.Settings.IndexingPolicy.IndexingMode)
                    },
                    DefaultTtl = containerConfig.Settings.DefaultTtl,
                    PartitionKey = new ContainerPartitionKey
                    {
                        Kind = containerConfig.Settings.PartitionKey.Kind,
                        Version = containerConfig.Settings.PartitionKey.Version,
                        Paths = { containerConfig.Settings.PartitionKey.Path }
                    }
                }
            };

            foreach (var includedPath in containerConfig.Settings.IndexingPolicy.IncludedPaths)
            {
                parameters.Resource.IndexingPolicy.IncludedPaths.Add(new IncludedPath
                {
                    Path = includedPath
                });
            }

            foreach (var excludedPath in containerConfig.Settings.IndexingPolicy.ExcludedPaths)
            {
                parameters.Resource.IndexingPolicy.ExcludedPaths.Add(new ExcludedPath
                {
                    Path = excludedPath
                });
            }

**Comment by pakrym** [comment]
They are mutable collections. You can add/remove items from them.
