### ISSUE TITLE
[BUG] ShareFileClient.UploadAsync() upload a big file, progressHandler not report correct progress 

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#16817]
**Describe the bug**
Please provide the description of issue you're seeing.
Use ShareFileClient.UploadAsync() to upload a file bigger than 4MB, the progressHandler  not output the right progress.
It will report progress 0 to 4MB, then back to 0, then to 4MB again and back to 0, again and again ... 
It seems only report progress inside a chunk, but not the whole file upload progress.
Repro with with Azure.Storage.Files.Shares, version 12.5.0-preview.1.

Like following file is is the progress reported by transfer  a file (not finished), and I print it to a file:
[progressbar.txt](https://github.com/Azure/azure-sdk-for-net/files/5515221/progressbar.txt)

**Expected behavior**
What is the expected behavior?
The progressHandler  should report the correct bytes when have been tranferredd.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
The progressHandler  reported value change from 0 to 4MB , again and again.
It seems it can only report progress inside a 4MB chunk.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Try to run ShareFileClient.UploadAsync()  with a progressHandler , like following code , to upload a file > 4MB
2. See the progress reported

```C#

IProgress<long> progressHandler = new Progress<long>((finishedBytes) =>
{
    outputProgress.Add(finishedBytes.ToString());
    if (finishedBytes == 0)
    {
        System.IO.File.AppendAllLines(@"c:\temp\progressbar.txt", outputProgress);
        outputProgress.Clear();
    }
});

await fileClient.CreateAsync(fileSize, smbProperties: smbProperties, cancellationToken: this.CmdletCancellationToken).ConfigureAwait(false);

// Upload file content
using (FileStream stream = System.IO.File.OpenRead(localFile.FullName))
{
    await fileClient.UploadAsync(stream, progressHandler, null, this.CmdletCancellationToken).ConfigureAwait(false);
}
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Files.Shares, version 12.5.0-preview.1] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by JimSuplizio** [comment]
Hi @blueww, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
