### ISSUE TITLE
[BUG] ShareFileClient.UploadAsync() has memory leak when upload a big file

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#16816]
**Describe the bug**
Please provide the description of issue you're seeing.
ShareFileClient.UploadAsync() has memory leak when upload a big file, with Azure.Storage.Files.Shares, version 12.5.0-preview.1.
Like following picture shows upload a 10GB file , and finished about 7.5GB. You can see the memory (black line) increase with uploading .
![image](https://user-images.githubusercontent.com/6926193/98633476-731a5100-235c-11eb-984c-b77314c924ee.png)

Find this issue when try to upload a 4TB file with ShareFileClient.UploadAsync(), after a while the memory reach >13GB, use up the system memory.
So this bug blocks upload 4TB file with ShareFileClient.UploadAsync()

**Expected behavior**
What is the expected behavior?
Memory should be stable when upload a big file with ShareFileClient.UploadAsync()

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Memory increase with content uploading.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Try to upload a big file with ShareFileClient.UploadAsync(), with Azure.Storage.Files.Shares, version 12.5.0-preview.1, like following code.
2. Track the memory usage of the uploading process

```c#
await fileClient.CreateAsync(fileSize, cancellationToken: this.CmdletCancellationToken).ConfigureAwait(false);

// Upload file content
using (FileStream stream = System.IO.File.OpenRead(localFile.FullName))
{
    await fileClient.UploadAsync(stream, progressHandler, null, this.CmdletCancellationToken).ConfigureAwait(false);
}
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Files.Shares, version 12.5.0-preview.1] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
VS 15.7.4

**Comment by jaschrep-msft** [comment]
Files.Shares partitioned uploader code is not properly releasing it's resources after each segment of the upload. Observing web activity and memory usage reveals that the memory spikes up proportional to the new segment length whenever a new range upload is started. Still need to determine the root cause.

It appears that while Files.Shares uses a different implementation for this than Blobs and Files.Datalake, they both suffer from the same issue. Additionally, Files.Shares memory jumps by double the expected amount (new range size), while Blobs and Files.Datalake jump the expected amount.

**Comment by jaschrep-msft** [comment]
@mikeharder #25732 resolves this according to your repro app.
