### ISSUE TITLE
Update WebSite slot settting as non-slot setting

### ISSUE THREAD

**Issue by xtreampb** [Azure/azure-sdk-for-net#16828]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
Microsoft.Azure.Management.WebSites
 
**Is your feature request related to a problem? Please describe.**
method definition `public static Microsoft.Azure.Management.WebSites.Models.StringDictionary UpdateApplicationSettingsSlot[Async] (this Microsoft.Azure.Management.WebSites.IWebAppsOperations operations, string resourceGroupName, string name, Microsoft.Azure.Management.WebSites.Models.StringDictionary appSettings, string slot);` 

the ability to update a slot setting and optionally set it as a slot setting or not.  Either have this take an optional bool to set it as a slot setting, or have the method `UpdateApplicationSettings[Async]`  take an optional slot name parameter.  I would like the ability to set an appsetting on a slot and not it be a slot setting.

i've tried using the "sitename/slotname" in the update applicaiton setting method but threw not found error.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xtreampb** [comment]
Additionally, according to the documentation found [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.webappsoperationsextensions.updateapplicationsettingsslot?view=azure-dotnet#Microsoft_Azure_Management_WebSites_WebAppsOperationsExtensions_UpdateApplicationSettingsSlot_Microsoft_Azure_Management_WebSites_IWebAppsOperations_System_String_System_String_Microsoft_Azure_Management_WebSites_Models_StringDictionary_System_String_), if the slot is not specified, the production slot will be updated.  If i set the slot parameter to `null`, or `string.empty` it throws an error saying that the slot must be specified.  Can we get some example or clarification on how to update app settings and slot app settings, specifically how to set the app setting as a slot setting.

**Comment by xtreampb** [comment]
Been doing some more testing and poking.  What I've discovered thus far is that no way to specify a setting as a slot setting (slot setting check in UI). For some reason, I thought we could pass the advanced edit json string to api and update the settings.  Is there a way to pragmatically set this value of an app setting?

**Comment by xtreampb** [comment]
So after analyzing the azure portal network in my chrome browser, it is this (undocumented) API that I need to be hitting: `[Get/Put] https://management.azure.com/subscriptions/{subID}/resourceGroups/{rgName}/providers/Microsoft.Web/sites/{SiteName}/config/slotconfignames`, with a json body of:
 ```
"properties":{
    "appSettingNames":[
      "string",
      "string2"
  ]
}
```
if we could somehow capture this in the library that would be great

**Comment by nisha-bhatia** [comment]
Thank you for your feedback, routing to service team.

**Comment by KranthiPakala-MSFT** [comment]
@nisha-bhatia - Following up to see if there is any update on this feedback? - Thank you

**Comment by ArthurMa1978** [comment]
@KranthiPakala-MSFT can you help to coordinate this issue to the WebApp service team as they are the owner
