### ISSUE TITLE
PageBlobClient.DownloadAsync hangs on AppService

### ISSUE THREAD

**Issue by sebastianburckhardt** [Azure/azure-sdk-for-net#16825]
**Describe the bug**
Under some circumstances, calls to PageBlobClient.DownloadAsync hang. 

**Expected behavior**
Calls should return quickly (this is a simple read from Azure Storage with no other load), or at least throw an exception after the timeout period.

**Actual behavior (include Exception or Stack Trace)**
Hangs indefinitely. There is no exception and I don't know how to get a stack trace (as this is happening inside a functions application running on an AppService Plan). It does not repro locally on my machine unfortunately.

**To Reproduce**
The call that hangs has this form:                    

```csharp
Response<BlobDownloadInfo> response = await pageBlobClient.DownloadAsync(range, null, true, this.PartitionErrorHandler.Token);
```

I have managed to find a sequence of steps to get repro 100% of times inside a Premium Functions Plan during startup, but this involves running my application, with custom tracing logic that can detect the hang. I have not been successful in reducing the steps, i.e. it does not hang if I just call this one line, out of context.

This issue has been around for a while. I previously reported it on azure/azure-storage-net#998 before it was suggested that I report it here.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.6.0
 - component is built as .NET Standard 2.1 and loaded via dependency injection
 - Environment is EP1 premium plan, Windows
 - IDE and version : Visual Studio 16.7.3
 -  .NET Core SDK  Version  3.1.403

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by sebastianburckhardt** [comment]
After doing a bit more testing, I have been able to reduce my repro scenario to the following.
The deadlock happens if I execute the following code while the Azure Functions is loading the durable task extension, i.e. within `Microsoft.Azure.WebJobs.Host.Listeners.IListener.StartAsync()`:

```csharp
        public static async Task TestAsync(string where)
        {
            Logger.LogWarning($"testing storage async {where}...");

            BlobServiceClient serviceClient = new BlobServiceClient(ConnectionString);
            var containerClient = serviceClient.GetBlobContainerClient("perftests-storage");
            await containerClient.CreateIfNotExistsAsync();

            int done = 0;

            Task _ = ReadAsync().ContinueWith(_ => done = 1);

            while (done != 1)
            {
                continue;
            }

            Logger.LogWarning($"storage test completed");
        }

        public static async Task ReadAsync()
        {
            try
            {
                BlobServiceClient serviceClient = new BlobServiceClient(ConnectionString);
                var containerClient = serviceClient.GetBlobContainerClient("perftests-storage");
                PageBlobClient pageBlobClient = containerClient.GetPageBlobClient("p00/commit-log/commit-log.0");
                HttpRange range = new HttpRange(0, 379392);

                Logger.LogWarning("starting download...");

                // this one hangs
                var result = await pageBlobClient.DownloadAsync(range, null, false, CancellationToken.None);

                Logger.LogWarning($"download result received");
            }
            catch (Exception e)
            {
                Logger.LogError("TestStorage error {exception}", e);
            }
        }
```

**Comment by kasobol-msft** [comment]
@sebastianburckhardt I'm not sure if I got exactly the same repro, but when I hooked up your sample to my durable function (modified a sample that VS generates for durable function project) I was getting 502 from the part I hooked it up and there was no trace in app insights from `ReadAsync`.

Then I modified:
`
            Task _ = ReadAsync().ContinueWith(_ => done = 1);

            while (done != 1)
            {
                continue;
            }
`
to
`
await ReadAsync();
`
then it started to work normally and produced relevant logs.

When I was trying to repro this on my dev box I wasn't getting that behavior. I guess in functions that active while loop is kind of overwhelming resources not letting async task to complete. So I'd suggest to check if this isn't just resource exhaustion in your deployment.

If further investigation is needed then please provide full sample VS project (minus sensitive data) that we could play with.

**Comment by sebastianburckhardt** [comment]
>  I guess in functions that active while loop is kind of overwhelming resources not letting async task to complete

Maybe, but that is a bug. The SDK should never deadlock, even if the user code contains a spinloop. Such deadlocks cause serious problems.

While we can eliminate all spin loops in our own code, we are a platform that also runs user code. It is not possible for us to categorically avoid spin loops in all the code that runs on our platform.

**Comment by kasobol-msft** [comment]
@sebastianburckhardt I don't think SDK deadlocks in your case. I think it's getting starved by the spin loop, i.e. the continuation task is never completed as it can't get scheduler attention (especially if you end up with 1 vCPU on low end hosting plan). We can't help with .NET TPL misuse.
If you can't avoid spin loops it would be good idea to throw in `await Task.Delay(...)` or `await Task.Yield()` or something similar into the loops to give some breathing room for other work you want to go concurrently.
See [here](https://answers.unity.com/questions/1807158/asyncawait-function-hangs-when-caller-has-infinite.html) and [here](https://stackoverflow.com/questions/34693229/async-infinite-loop)

**Comment by sebastianburckhardt** [comment]
Yeah, I know not to write such spin loops. And I know I can fix them with sleep. 

But, these spin loops are in other people's code, not mine. It's really not great if the SDK is vulnerable to this issue.

It took me forever to even find out what the cause is (the spin loop was in an imported NuGet package) and create a repro.

Still, even assuming that spin loops are "not recommended", I believe the scheduler is not behaving correctly here. I understand that this may be partly an issue with the TPL scheduler, and not the storage SDK, but I have not seen this behavior in other contexts so I am wondering if the SDK is doing some nonstandard scheduling. 

In particular, the following seem odd:
- Why would the continuation *never* be scheduled? That seems wrong. TPL should eventually do it, adding threads if necessary.
- Adding Thread.sleep() does work, but adding  Thread.yield() does not.

**Comment by kasobol-msft** [comment]
The storage SDK doesn't do anything nonstandard in asynchronous APIs. We are not in position to fix other packages or change the TPL schedulers. We recommend to:
- file a bug against that other NuGet package to not spin wait.  Use a `TaskCompletionSource` instead.
- file a bug against the TPL if you think the threadpool should be able to continue scheduling when a single core environment is spin waiting (or all cores are busy spin waiting in environment where there's more parallelism involved).
