### ISSUE TITLE
[BUG] - Fix AnalyzeOperationBatchWithStatisticsTest in TextAnalytics

### ISSUE THREAD

**Issue by suhas92** [Azure/azure-sdk-for-net#16839]
**Describe the bug**
We have a test ignored due to a bug on the TA service. The statistics are not showing up in the response.

**Expected behavior**
What is the expected behavior?
The test should not be ignored

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
The test is ignored
https://github.com/Azure/azure-sdk-for-net/pull/16785#discussion_r520178521

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.
2.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
//cc: @maririos

**Comment by maririos** [comment]
Stats are now returned from the service. Check and enable test https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/tests/AnalyzeOperationTests.cs#L370

**Comment by maririos** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/18516
