### ISSUE TITLE
[BUG] `Microsoft.Azure.Graph.RBAC.Models.DirectoryObject` is missing all expandable properties

### ISSUE THREAD

**Issue by paule96** [Azure/azure-sdk-for-net#16874]
**Describe the bug**

If you browse the OData API (`https://graph.windows.net/tenantid/$metadata`), you will see the `DirectoryObject` has the following properties:

- `objectType`
- `objectId`
- `deletionTimestamp`

and the following navigation properties:

- `createdOnBehalfOf`
- `createdObjects`
- `manager`
- `directReports`
- `members`
- `transitiveMembers`
- `memberOf`
- `transitiveMemberOf`
- `owners`
- `ownedObjects`

The problem is that all the navigation properties are not present in the [`DirectoryObject`](https://github.com/Azure/azure-sdk-for-net/blob/d56012f35ebf4be29aa2f2ee4f60f19d06692927/sdk/graphrbac/Microsoft.Azure.Graph.RBAC/src/Generated/Models/DirectoryObject.cs) model.

**Expected behavior**

The navigation properties should be there.

**Actual behavior (include Exception or Stack Trace)**

There is no way to get the navigation properties, so no stack trace.

**To Reproduce**

no reproduction possible. 

**Environment:**

not relevant. Is broken everywhere

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by paule96** [comment]
# fyi

This is also more or less related to this issue: https://github.com/MicrosoftDocs/feedback/issues/1339

I wan't to solve this issue and needs the owners of the AdApplication. But I can't get it from the data model.

**Comment by paule96** [comment]
any updates on this @jsquire .

It would also help if anybody can provide the implementation of the function `Start-AutoRestCodeGeneration`. Then I can fix the bug by myself. But I can't find it.

> The function is used [here](https://github.com/Azure/azure-sdk-for-net/blob/d56012f35ebf4be29aa2f2ee4f60f19d06692927/sdk/graphrbac/Microsoft.Azure.Graph.RBAC/src/generate.ps1)

**Comment by jsquire** [comment]
Unfortunately, I'm only serving as first-line triage in this case.  I don't have insight into the process that is used by the team that owns this library.   Generally, there's a 72 hour window provided for teams to triage and respond.   If we don't see engagement by the owners after 72 hours, please feel free to ping me again and I'll do what I'm able to escalate.

**Comment by paule96** [comment]
ping @jsquire ;) 72h are over 🕐

**Comment by jsquire** [comment]
Thank you for the ping, @paule96.   I've started an internal thread to track down the correct owner and escalate.

**Comment by paule96** [comment]
Ping again @jsquire.
It would be good to have an update on this.

**Comment by jsquire** [comment]
Hi @paule96.   I apologize for the lack of engagement;  we're still working internally to find the appropriate owner and get you some assistance.   Unfortunately, while we're closer, I don't have a solid timeline.  With the US holidays at the end of this week, we may be delayed until folks return to the office next week.

**Comment by paule96** [comment]
all good :) I just try to not forget this. So don't worry if I asking ever 72h. It's also a reminder for me. ^^

So any updates here?

**Comment by jsquire** [comment]
No updates;  the email thread was kicked but, as mentioned, the US holiday last week had many folks out.   I'll kick it next on Wednesday, to give some time for those returning to get through their email backlog.

**Comment by jsquire** [comment]
Just a quick note, there is still discussion ongoing internally.  One key contact was out through last week.   We apologize for the delay and confusion surrounding ownership here.

**Comment by paule96** [comment]
Thanks for letting me know. 👍 You do a great job!

**Comment by paule96** [comment]
@jsquire Are there any updates?

**Comment by jsquire** [comment]
Hi @paule96.   Apologies for not touching base sooner.  Unfortunately, though we've continued to dig in we've still not been able to locate the owner of the library.  At this point, I've been going through the commit history and reaching out to those that contributed and who still work for Microsoft in the hope of finding some insight.   This morning, I reached out a small set of contributors from 5 years ago.... so we're pretty close to the end of that.

There's also been discussion happening at the leadership levels to try and understand that the future plans and directions are for the library, but I don't have any updates there nor any deep insight into the process.

This is the part where I apologize, again, that you've been waiting for so long.... though I imagine that it is starting to feel rather disingenuous.

**Comment by paule96** [comment]
But sounds good you are close to finding the know-how. Hope you can find a new owner for this library

**Comment by deyaaeldeen** [comment]
@jsquire you can find the API reference for the RBAC package here: https://docs.microsoft.com/en-us/previous-versions/azure/ad/graph/api/api-catalog. The service does not maintain the swagger and @lmazuel is the owner of the swagger. I know that this package is on its way to deprecation and it is highly discouraged to use it. I tried to regenerate it for JS with the latest swagger but was told not to do so here https://github.com/Azure/azure-sdk-for-js/pull/13858. The recommendation is to use [@microsoft/microsoft-graph-client](https://developer.microsoft.com/en-us/graph) instead.

**Comment by paule96** [comment]
@deyaaeldeen you mean this: https://github.com/microsoftgraph/msgraph-sdk-dotnet?
Okay so I must talk to the Azure AD PowerShell Module owner how we can use the new tools.

**Comment by jsquire** [comment]
Thanks for your input, @deyaaeldeen.   Given that we don't know who the owner of the package is, I'm not sure that I agree that we can authoritatively make the statement that it is deprecated.   I'll follow-up with @ramya-rao-a offline to better understand the source of her statement, as it differs from the insight provided by others.

That said, I would certainly agree that no PowerShell module should have a dependency on this library; in the best case, it is a preview that hasn't been updated in several years.  I would strongly advise that it not be used in production scenarios nor critical workloads.

**Comment by deyaaeldeen** [comment]
@jsquire @ramya-rao-a pointed to this [post](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363) in the closed PR I linked to earlier.

**Comment by ramya-rao-a** [comment]
Thanks for your patience @paule96 

The [Azure AD Graph API](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-graph-api) is definitely on its [path of being deprecated](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363) in favor of the [Microsoft Graph API](https://developer.microsoft.com/graph)

Relevant support statements from the service: 

![image](https://user-images.githubusercontent.com/16890566/110153345-c85cf100-7d97-11eb-8c2d-fea8d72a53fa.png)

The packages we have for Azure AD Graph will also follow suit i.e. get security updates until June 30th 2022 after which they will be deprecated.

Please refer to [Update your applications to use Microsoft Authentication Library and Microsoft Graph API](https://techcommunity.microsoft.com/t5/azure-active-directory-identity/update-your-applications-to-use-microsoft-authentication-library/ba-p/1257363) for next steps. There are relevant links in there with pointers to places where you can provide feedback or ask any follow up questions.

**Comment by paule96** [comment]
Okay so it's shouldn't be used by the Azure PowerShell team. So what are the next steps to remove the dependency from [here](https://github.com/Azure/azure-powershell/blob/master/src/Resources/Resources/Resources.csproj)?
Is this an issue that will be routed internally at Microsoft to the Azure PowerShell team or should I open an issue in [their repo](https://github.com/Azure/azure-powershell/)?

**Comment by jsquire** [comment]
@paule96:  If you don't mind opening an issue in the PowerShell repository, that is likely to be the most expedient path forward.  With no known owner for for the Graph RBAC library, it would probably be one of the folks involved in this thread who would reach out to the PowerShell team via a GitHub issue to make them aware.   You are likely to carry more weight, as you have a real-world driver for the change.

Please feel free to mention myself, @ramya-rao-a, and @AlexGhiondea in as needed if we can help with the resulting discussion there.
