### ISSUE TITLE
Make Azure.Security.KeyVault.Keys.Cryptography.SignResult serializable

### ISSUE THREAD

**Issue by flytzen** [Azure/azure-sdk-for-net#16879]
**Azure KeyVault Key Client**

**Is your feature request related to a problem? Please describe.**

SignResult is not serialisable/deserialible with either NewtonSoft.Json or System.Text.Json despite some nod to it with a (partial?) implementation of `IJsonDeserializable`.

SignResult represents the three things you need to store about a signature in order to be able to verify it, meaning it is a common data structure you have to store. It would make this usecase easier if I could simply serialise and deserialise this class to json.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
The interface is internal only and depends on System.Text.Json, which not every uses (we use internally because it's faster than Newtonsoft.Json, arguably much more popular than System.Text.Json. At this time we have no intentions of exposing those interfaces, but you could write a `JsonConverter` (or whatever your serialization framework of choice calls it) for this and any other classes you need. There are many classes that have necessary information, but how that information is stored (JSON, XML, etc.) is largely application-specific.

**Comment by flytzen** [comment]
Thanks @heaths. The thing is that you return `SignResult` in public methods and go pains to explain to the consumer that they need to store all the values that are exposed on that class.
I have indeed written my own wrapper that is serializable - it just seems like yak shaving :)

In case anyone else comes across this issue, here is a wrapper (this one depends on newtonsoft but can easily be adapted)

```csharp
   class SerializableSignResult
    {
        
        [JsonConstructor]
        public SerializableSignResult(string algorithmAsString, string keyId, string signatureAsBase64)
        {
            this.AlgorithmAsString = algorithmAsString;
            this.KeyId = keyId;
            this.SignatureAsBase64 = signatureAsBase64;
        }
        
        public SerializableSignResult(SignResult signResult)
        {
            this.Algorithm = signResult.Algorithm.ToString();
            this.KeyId = signResult.KeyId;
            this.Signature = signResult.Signature;
        }   
        
        [JsonIgnore]
        public SignatureAlgorithm Algorithm
        {
            get 
            {
                return new SignatureAlgorithm(this.AlgorithmAsString);
            }
            private set
            {
                this.AlgorithmAsString = value.ToString();
            }

        }
        
        public string AlgorithmAsString { get; private set; }

        public string KeyId { get; private set;}

        [JsonIgnore]
        public byte[] Signature { 
                get 
                {
                    return System.Convert.FromBase64String(this.SignatureAsBase64);
                }
                private set 
                {
                    this.SignatureAsBase64 = System.Convert.ToBase64String(value);
                } 
            }

        public string SignatureAsBase64 { get; private set; }
    }
```

**Comment by flytzen** [comment]
PS I tested serialising/deserializing SignResult with System.Text.Json and it doesn't work at all, so I don't think the (partial) implementation of `IJsonDeserializable` is working.

**Comment by heaths** [comment]
That interface doesn't support serialization - it supports reading from a JSON stream directly and is internal only. How (format, shape) an object is serialized is not something we support generally. Different applications have different requires on either or both of these, thus is left to the application to implement as with most .NET classes as well. If we get lots of requests for this across services we can consider it, but currently do not support serializing any random model across the SDKs.
