### ISSUE TITLE
[QUERY] How to create a new blob using OpenWriteAsync and setting metadata with a single operation

### ISSUE THREAD

**Issue by bragma** [Azure/azure-sdk-for-net#16875]
**Query/Question**
Hi, I am migrating an old "Microsoft.WindowsAzure.Storage.Blob" based application to the new "Azure.Storage.Blobs" v12.7 and I don't know how to translate some code that allowed to create a new blob from a stream and setting metadata to it.

Previous code was:

```
var blockBlob = container.GetBlockBlobReference(blobName);
blockBlob.Properties.ContentType = contentType;
foreach (var pair in metadata)
{
	blockBlob.Metadata.Add(pair);
}

using var s = await blockBlob.OpenWriteAsync();
using var writer = new StreamWriter(s);
using var jsonWriter = new JsonTextWriter(writer);

var serializer = new JsonSerializer();
serializer.Serialize(jsonWriter, data);
await jsonWriter.FlushAsync();

return blockBlob.Uri;
```

This allowed me to create the blob with content type and medatada already set. Now it seems the only way to create a blob with metadata is to use UploadAsync in this way:

```
await blockBlob.UploadAsync(stream, new BlobUploadOptions
{
	HttpHeaders = new BlobHttpHeaders
	{
		ContentType = contentType
	},
	Metadata = metadata
});
```

The only way I see to do port the original code is to use a MemoryStream to write the json into, then use the same stream to feed UploadAsync. But this requires to store the data in memory and was not originally required. Is there a way to create a new blob with OpenWriteAsync() and set headers/metadata? Am I missing anything?

Thanks!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
You should be able to use `OpenWrite` to create the blob and upload setting metadata, please take a look at the snippet below
```
 BlockBlobOpenWriteOptions options = new BlockBlobOpenWriteOptions
            {
                BufferSize = Constants.KB,
                HttpHeaders = new BlobHttpHeaders
                {
                    ContentType = "samplecontetnttype"
                }
                Metadata = metadata
            };

            Stream stream = await blob.OpenWriteAsync(
                overwrite: true,
                options);

byte[] data = GetRandomBuffer(16 * Constants.KB);

            // Act
            await stream.WriteAsync(data, 0, 512);
            await stream.WriteAsync(data, 512, 1024);
            await stream.WriteAsync(data, 1536, 2048);
            await stream.WriteAsync(data, 3584, 77);
            await stream.WriteAsync(data, 3661, 2066);
            await stream.WriteAsync(data, 5727, 4096);
            await stream.WriteAsync(data, 9823, 6561);
            await stream.FlushAsync();
```

Let me know if that works for you.

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
