### ISSUE TITLE
[BUG] Azure Blob Storage - When using a Shared Access Key on BlobServiceClient, BlobClient throws RequestFailedException during SyncCopyFromUriAsync

### ISSUE THREAD

**Issue by hallidev** [Azure/azure-sdk-for-net#16882]
**Describe the bug**

I'm using a connection string like the following with BlobServiceClient:

```
DefaultEndpointsProtocol=https;AccountName=<myaccountname>;AccountKey=<myaccountkey>;EndpointSuffix=core.windows.net
```

Most operations on ```BlobServiceClient``` work just fine. The following code using ```SyncCopyFromUriAsync``` fails, however,

```
public static async Task RenameFile(this BlobServiceClient blobServiceClient,
    string container,
    string fileName,
    string newFileName,
    CancellationToken cancellationToken = default)
{
    var containerClient = blobServiceClient.GetBlobContainerClient(container);

    var sourceBlobClient = containerClient.GetBlobClient(fileName);
    var targetBlobClient = containerClient.GetBlobClient(newFileName);

    await targetBlobClient.SyncCopyFromUriAsync(sourceBlobClient.Uri, cancellationToken: cancellationToken);
    await sourceBlobClient.DeleteAsync(cancellationToken: cancellationToken);
}
```

**Expected behavior**

```SyncCopyFromUriAsync``` succeeds.

**Actual behavior (include Exception or Stack Trace)**

```SyncCopyFromUriAsync``` fails with the following:

```
Azure.RequestFailedException: Public access is not permitted on this storage account.
RequestId:ae1a2277-301e-006c-164f-b8620b000000
Time:2020-11-11T17:25:47.1435687Z
Status: 409 (Public access is not permitted on this storage account.)
ErrorCode: CannotVerifyCopySource

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: ae1a2277-301e-006c-164f-b8620b000000
x-ms-client-request-id: 8f565382-8a48-4f42-b8ba-68cecfa528f9
x-ms-version: 2020-02-10
x-ms-error-code: CannotVerifyCopySource
Date: Wed, 11 Nov 2020 17:25:46 GMT
Content-Length: 246
Content-Type: application/xml
```

**To Reproduce**

1. Create a ```BlobServiceClient``` using a Shared Access Key in the connection string
2. Attempt to call the above extension method

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 

Azure.Storage.Blobs 12.7.0

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]

(same problem on netcore 3.1)

.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

 - IDE and version : [e.g. Visual Studio 16.3]

Visual Studio 16.8 (same problem on 16.7.x)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

Can I ask which operations are successful on the `BlobServiceClient` ? 

Also have you tried initializing the `BlobClient` through using the connection string? (e.g. `var blobClient = new BlobClient(connection string, blobname)` ? Does that not still work for you?

Maybe the container or blob itself does not allow the level of access you are authenticating with.

**Comment by hallidev** [comment]
Currently I'm using ```DeleteAsync```, ```DownloadAsync```, ```CreateIfNotExistsAsync```, and ```UploadAsync``` without issue.

I am initializing the BlobClient via connection string, but since I'm using the .NET 5 DI Container, my initialization looks like this in ```Startup.ConfigureServices```:

```
            services.AddAzureClients(builder =>
            {
                builder
                    .AddBlobServiceClient(_configuration["ConnectionStrings:AzureBlobStorage"])
                    .WithName("DefaultAzureStorage");
            });
```

Where ```_configuration["ConnectionStrings:AzureBlobStorage"]``` looks like ```DefaultEndpointsProtocol=https;AccountName=<myaccountname>;AccountKey=<myaccountkey>;EndpointSuffix=core.windows.net```.

I then inject the following into a constructor: ```IAzureClientFactory<BlobServiceClient> blobClientFactory```

To get my ```BlobServiceClient``` instance, I do the following:

```var blobServiceClient = _blobClientFactory.CreateClient("DefaultAzureStorage");```

All of this is per the documentation and everything works except ```SyncCopyFromUriAsync```. 

If you look at the above error, the message is ```Public access is not permitted on this storage account.```. I'm not using public access though - I'm using the connection string with a Shared Access Key.

I've read the documentation at ```https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal```, and although it's not especially clear what I should do to resolve this issue, I don't think I have it configured wrong.

**Comment by amnguye** [comment]
Okay, just to reconfirm from your reply, you cannot create a `BlobClient` unless it's from the `BlobServiceClient` because you must use this `Startup.ConfigureServices` ?

I tried to run a similar scenario as close to yours without using the `Startup.ConfigureServices`, however I was unable to reproduce.
Here's the snippet I have
```
BlobServiceClient serviceClient = new BlobServiceClient(connectionString);

            BlobContainerClient containerClient = serviceClient.GetBlobContainerClient("containerName");

            BlobClient sourceBlob = containerClient.GetBlobClient("sourceblob");
            BlobClient destBlob = containerClient.GetBlobClient("destblob");

            try
            {
                await destBlob.SyncCopyFromUriAsync(sourceBlob.Uri, cancellationToken: cancellationToken);
            }
...
```
I also tried without a cancellationToken as well.

I find the 409 (CannotVerifyCopySource) to be very interesting because if you actually did not have access to the blob (like if you didn't give public access to the blob, or it's permitted only to a certain degree), the service throws a 404 (BlobNotFound, ContainerNotFound), not the error you received. We throw the 404 because if you were say an outside user, we wouldn't want anyone just poking around in your storage account and giving information that a blob does actually exist there when they don't have permissions to even know what's in your storage account or blob container.

There must be something about your storage account that's actually not allowing you to set public access on this blob container or blob itself, but at the same time telling you that you do have access to the blob.

I was able to reproduce your error if I set my "Allow Blob public access" to disabled
![image](https://user-images.githubusercontent.com/48961492/101959853-0690ad00-3bbb-11eb-855d-b1b681e2afc8.png)
Then switching it back to enabled solved it. Can you confirm for me that you have this enabled? (Please wait at least 30 seconds before running anything after enabling this).

**Comment by hallidev** [comment]
I must be confused about what “allow blob public access” means. I currently have public access disabled. 

My impression from the docs was that this would make the blob available to anyone, which is not what I want. 

Additionally, with public access disabled I’m still able to do everything except the SyncCopy, making it even less clear what this setting does. Should the setting name just be “Allow SyncCopy operation” rather than “Allow public access”. 

I will try to enable this and see if it works, but if it does, does this mean anyone on the public internet can read the files I have stored?

**Comment by amnguye** [comment]
Sorry for the late reply. If you have this enabled (which is normally recommended) for copy, we only allow copies if the source blob is public or via Shared Access Signature (SAS).

https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob
![image](https://user-images.githubusercontent.com/48961492/106316933-618d6a80-6222-11eb-8150-96574ca882ca.png)

Can you initialize your BlobServiceClient/BlobContainerClient/BlobBaseClient with a SAS URI instead and see if that will work for you? It's probably best if you don't enable blob public access and keep things private.

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
