### ISSUE TITLE
[QUERY] Have you considered moving Azure.Core into a generic .net namespace? (not Azure specific)

### ISSUE THREAD

**Issue by Riff451** [Azure/azure-sdk-for-net#16890]
Hello,
I was having a look at the Azure.Core project and I just watched a nice dotnetconf presentation about the unified design model for Azure sdks . To me Azure.Core and all principles behind it look that might be applied to any kind of http client scenario, not just for calling Azure services. That's why I was wondering whether it's been considered moving Azure.Core into maybe a more general .net namespace.
Thanks :)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by pakrym** [comment]
Don't let Azure.* namespace stop you from using the Azure.Core library! We are committed to the high level of quality and support as you would have with any other .net library.

But we would also like to keep it clear that while primitives we provide are generally applicable the primary goal is to support Azure SDK libraries and defaults are tailored to that (x-ms-client-request-id/User-Agent header support) etc.

**Comment by Riff451** [comment]
@pakrym Thank you very much for the explanation. It makes sense. :) But as suggested I'll consider using Azure.Core standalone.

**Comment by tg-msft** [comment]
Thank you for the suggestion.  It's not a goal of the project at this time or the near future so I'm closing the work item.  As discussed though, you could use this to implement your own client libraries on top of our stack.  I'd suggest taking a look at https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/template/Azure.Template to start.
