### ISSUE TITLE
[FEATURE REQ] Azure SDK Update - Application Gateway

### ISSUE THREAD

**Issue by WhitWaldo** [Azure/azure-sdk-for-net#16908]
**Library or service name.**
I'm looking through the new Azure SDK packages and don't see one for Application Gateway (ideally v2). Is there any timeline on having such a package available?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by markcowl** [comment]
@WhitWaldo Application gateway is in the 'Azure.ResourceManager.Network' package on nuget: https://www.nuget.org/packages/Azure.ResourceManager.Network/1.0.0-preview.2
