### ISSUE TITLE
SchemaRegistryAvroObjectSerializer Exception

### ISSUE THREAD

**Issue by LarryF813** [Azure/azure-sdk-for-net#16923]
**Question**
I have attempted to recreate a simple Schema Registry sample based on the [Microsoft.Azure.Data.SchemaRegistry.ApacheAvro][1] GitHub sample. Unfortunately, the serializer fails to serialize. I receive the following error: System.ArgumentException: 'Type Person is not supported for serialization operations.'

Any ideas?

  [1]: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/schemaregistry/Microsoft.Azure.Data.SchemaRegistry.ApacheAvro

Here is my schema from Azure Portal

    {
        "type": "record",
        "name": "Person",
        "namespace": "PersonSchema",
        "fields": [
            {
                "name": "PersonId",
                "type": "int"
            },
            {
                "name": "PersonName",
                "type": "string"
            }
        ]
    }

Here is my POCO class. I added the [Serializable] attribute but that did not help.

        [Serializable]
        public class Person
        {
            public int PersonId { get; set; }
    
            public string PersonName { get; set; }
    
            public Person()
            {
    
            }
        }

Here is the code that  creates SchemaRegistryClient and serializes my Person class instance using SchemaRegistryAvroObjectSerializer. I can retrieve a schema from the schema registry so it would appear that security is in order with my Azure portal setup.

            internal void TestSchemaMethod()
            {
                var cred = new ClientSecretCredential("MY_TENANT_ID", "MY_CLIENT_ID", "MY_SECRET");
                var schemaRegistryClient = new SchemaRegistryClient("MYNAMESPACE.servicebus.windows.net", cred);
                using (var memoryStream = new MemoryStream())
                {
                    var serializer = new SchemaRegistryAvroObjectSerializer(schemaRegistryClient, "TestDataSchema", new SchemaRegistryAvroObjectSerializerOptions { AutoRegisterSchemas = true });
                    var id = 1;
                    var person = new Person() { PersonId = id, PersonName = $"SomeName{id}" };
                    serializer.Serialize(memoryStream, person, typeof(Person), CancellationToken.None);
                }
            }

**Environment:**
Microsoft.Azure.Data.SchemaRegistry.ApacheAvro --version 1.0.0-beta.1
WIndows 10 .NET Core 3.1
Visual Studio 16.7.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by MiYanni** [comment]
@LarryF813 The `Person` class you defined was not generated by the ApacheAvro library. Currently, we don't support arbitrarily serializable classes. Here is an example of an ApacheAvro generated class:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/schemaregistry/Microsoft.Azure.Data.SchemaRegistry.ApacheAvro/tests/Models/Employee.cs

Here is the class I used from the ApacheAvro library to generate it. I have an example on how to use it but it is on another machine. I'll provide it tomorrow.
https://avro.apache.org/docs/1.10.0/api/csharp/html/classAvro_1_1CodeGen.html

**Comment by LarryF813** [comment]
OK. I have changed the sample and am getting closer but still getting an error, but a different error now. I also tried getting the Schema from the registry and setting the property on the Person object. Either way it did not matter, I got the same exception: {"Code":400,"Detail":"Schema validation failed: Error parsing undefined value. Path 'u0022typeu0022', line 1, position 17. 

Here is my updated Person class:
'
    public class Person : ISpecificRecord
    {
        public static Schema _SCHEMA = Avro.Schema.Parse("{\\"type\":\\"record\",\\"name\\":\\"Person\",\\"namespace\\":\\"PersonSchema\\",\\"fields\\": [{\\"name\\":\\"PersonId\\",\\"type\\":\\"int\\"},{\\"name\\":\\"PersonName\\",\\"type\\":\\"string\\"}]}");
        public int PersonId { get; set; }

        public string PersonName { get; set; }

        public Schema Schema { get { return _SCHEMA; } }

        public object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return PersonId;
                case 1: return PersonName;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }
'

**Comment by MiYanni** [comment]
@LarryF813 Since this is beta, there was a bug with the first version of the client. The dependency on the client pulled in from `Microsoft.Azure.Data.SchemaRegistry.ApacheAvro` is out-of-date. To fix, you just need to add a dependency on `Azure.Data.SchemaRegistry` version **1.0.0-beta.2** to your project. It should fix the issue.

**Comment by MiYanni** [comment]
@jsquire @LarryF813 
Also, for future reference, here is how to generate a class using the Apache Avro library:
```csharp
var currentDirectory = Directory.GetCurrentDirectory();
var examplePath = Path.Combine(currentDirectory, "Example.avsc");
var schema = Schema.Parse(File.ReadAllText(examplePath));
var codeGen = new CodeGen();
codeGen.AddSchema(schema);
codeGen.GenerateCode();
codeGen.WriteTypes(currentDirectory);
```

**Comment by LarryF813** [comment]
Hi. I was able to get the serializer working. I had some questions about the formatting of the message. Here is an example of 5 Person objects that I serialized into a single MemoryStream:
\0\0\0\01bab7355bb194101b51a55d562f84d01\u0006\u0012SomeName1
\0\0\0\01bab7355bb194101b51a55d562f84d01\b\u0012SomeName2
\0\0\0\01bab7355bb194101b51a55d562f84d01\n\u0012SomeName3
\0\0\0\01bab7355bb194101b51a55d562f84d01\f\u0012SomeName4
\0\0\0\01bab7355bb194101b51a55d562f84d01\u000e\u0012SomeName5

I used the Encoding.UTF8 class to extract this data from the byte[] of the MemoryStream. I understand some of the following items from both studying the data and the [client documentation](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.data.schemaregistry.apacheavro-readme-pre):

- \0\0\0\0 - This is a record format indicator (which appears to be currently not in use)

- 1bab7355bb194101b51a55d562f84d01 - This is the GUID of the message format (I can see this value in the Azure portal)

- \u0006 - This seems like some form of my int property (PersonID) which has an int value of 3.
	The subsequent objects above had int values of 4,5,6,7 which would correspond to \b,\n,\f,\u00e
	_**How are these values calculated (e.g. PersonID of  int 3 seems to be represented by \u0006)?**_
	_**Is \u00 some sort of separator value / prefix being used in Avro serializer?**_
- \u0012SomeName1 - SomeName1 is the string property value so I understand this part of the value.
	_**What does \u0012 represent?**_

**Comment by MiYanni** [comment]
The message format is not finalized. Format identifier is hard-coded for this beta. The GUID is the Schema ID (from Schema Registry). Everything after that GUID is the Apache Avro library's serialization of the data you gave it. So, either a ISpecificRecord or GenericRecord, which are the only supported types right now.
