### ISSUE TITLE
Pipeline testing support and nuget targets for the newly released .NET 5.0

### ISSUE THREAD

**Issue by drwill-ms** [Azure/azure-sdk-for-net#16921]
**Library or service name.**
All
 
**Is your feature request related to a problem? Please describe.**
.NET 5.0 just released and I was wondering if we think it is important to add testing support for it in our pipelines and nuget targets (if that makes sense).

**Comment by kurtzeborn** [comment]
@pakrym, we're suspicious this was already done previously with your .NET 5.0 pass through the repo.

**Comment by pakrym** [comment]
Yep, we have .NET 5 testing
