### ISSUE TITLE
[BUG] BlobItem.ETag has no quotes

### ISSUE THREAD

**Issue by bragma** [Azure/azure-sdk-for-net#16920]
**Describe the bug**
ETags obtained from GetBlobsAsync have no quotes, so their format is differnt from those obtained from other methods. Ex: 0x8D88739958C9830 instead of "0x8D88739958C9830"

**Expected behavior**
If all methods produce tags with quotes, BlobItem from GetBlobs() should do the same. (Personally I think quotes should be stripped away from all ETags).

**To Reproduce**
Consider this sample code:

```
var serviceClient = new BlobServiceClient(connectionString);
var containerClient = serviceClient.GetBlobContainerClient("container");
var blobClient = containerClient.GetBlobClient("blob");

var containerItems = new List<BlobContainerItem>();
await foreach (var ci in serviceClient.GetBlobContainersAsync())
{
	containerItems.Add(ci);
}
var containerItem = containerItems.First();

BlobContainerProperties containerProperties = await containerClient.GetPropertiesAsync();

var blobItems = new List<BlobItem>();
await foreach (var bi in containerClient.GetBlobsAsync(BlobTraits.Metadata))
{
	blobItems.Add(bi);
}
var blobItem = blobItems.First();

BlobProperties blobProperties = await blobClient.GetPropertiesAsync();

Console.WriteLine("BlobContainerItem ETag: {0}", containerItem.Properties.ETag);
Console.WriteLine("BlobContainerProperties ETag: {0}", containerProperties.ETag);
Console.WriteLine("BlobItem ETag: {0}", blobItem.Properties.ETag);
Console.WriteLine("BlobProperties ETag: {0}", blobProperties.ETag);
```

The output is:
BlobContainerItem ETag: "0x8D7DC7D780794C0"
BlobContainerProperties ETag: "0x8D8873979F15570"
BlobItem ETag: 0x8D88739958C9830
BlobProperties ETag: "0x8D88739958C9830"

**Environment:**
Azure.Storage.Blobs 12.7.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

I agree we should be parsing out the quotes. It's unreasonable for to have the user to remove the quotations themselves, when in ListBlobs we have the quotations parsed out.

Looks like there's a problem with the generated code and the inconsistent parsing.

Thanks for bringing this issue to our attention.

**Comment by seanmcc-msft** [comment]
I'm not sure if we can make this change, it might be considered breaking.  @tg-msft

**Comment by seanmcc-msft** [comment]
So I did some more research.  This is what the storage service returns for Blob Get Properties:
```
HTTP/1.1 200 OK
Content-Length: 1024
Content-Type: application/octet-stream
Content-MD5: PsgU0CjhNHB9vVFeslhxTQ==
Last-Modified: Wed, 16 Dec 2020 22:01:28 GMT
Accept-Ranges: bytes
ETag: "0x8D8A20E2374ECB1"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 8f9707eb-e01e-005e-29f7-d33122000000
x-ms-client-request-id: 488e8266-b94a-420f-bcb7-27199d622ce0
x-ms-version: 2019-02-02
x-ms-creation-time: Wed, 16 Dec 2020 22:01:28 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
x-ms-server-encrypted: true
x-ms-access-tier: Hot
x-ms-access-tier-inferred: true
Date: Wed, 16 Dec 2020 22:01:27 GMT
```
And this is what is being returned for List Blobs:
```
<?xml version="1.0" encoding="utf-8"?>
<EnumerationResults ServiceEndpoint="https://seanmcccanary3.blob.core.windows.net/" ContainerName="test-container-feb237c2-2ac9-446c-a59a-ecdd69d62c97">
	<Blobs>
		<Blob>
			<Name>bar</Name>
			<Properties>
				<Creation-Time>Wed, 16 Dec 2020 22:03:26 GMT</Creation-Time>
				<Last-Modified>Wed, 16 Dec 2020 22:03:26 GMT</Last-Modified>
				<Etag>0x8D8A20E69E4E40A</Etag>
				<Content-Length>1024</Content-Length>
				<Content-Type>application/octet-stream</Content-Type>
				<Content-Encoding />
				<Content-Language />
				<Content-CRC64 />
				<Content-MD5>E/Y2R8jHD2JvWKsDCf3opg==</Content-MD5>
				<Cache-Control />
				<Content-Disposition />
				<BlobType>BlockBlob</BlobType>
				<AccessTier>Hot</AccessTier>
				<AccessTierInferred>true</AccessTierInferred>
				<LeaseStatus>unlocked</LeaseStatus>
				<LeaseState>available</LeaseState>
				<ServerEncrypted>true</ServerEncrypted>
			</Properties>
		</Blob>
	</Blobs>
	<NextMarker />
</EnumerationResults>
```

The service is returning ETag without quotes, most likely because quotes are not a valid xml character.

Since we are returning the ETag which is returned by the service, and adding quotes could break existing customers, I'm believe the current design is correct.

**Comment by amnguye** [comment]
Closing the issue, as a fix for this would be a breaking change.

Please tag my name in the reply if you have any other questions.
