### ISSUE TITLE
[FEATURE REQ] BinaryData should/could validate that bytes are UTF8 before attempting ToString conversion.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#16951]
**Library or service name.**
System.Memory.Data 1.0.0
 
**Is your feature request related to a problem? Please describe.**

I'm working with a scenario where both UTF8 bytes and non-UTF8 bytes flow through the system. In that scenario app would throw on attempt of non-UTF -> string conversion. See https://github.com/Azure/azure-storage-net/blob/b0d47bfd4c1c0dcbe60eaf373e2977cd7405aa5f/Lib/Common/Queue/CloudQueueMessage.Common.cs#L83-L86

Today my app throws if non-UTF8 to string is attempted. I'd like to preserve this while using BinaryData, but that means I have to write validation on the top of BinaryData in app code before attempting ToString conversion. It would be nice if BinaryData could do that for me or if it could accept knob or expose ToString overload that offers such validation.

Consider the following code:
```
using System;
using System.Text;

namespace ConsoleApp5
{
    class Program
    {
        static void Main(string[] args)
        {
            byte[] content = new byte[] { 0xFF, 0x00 }; // Not a valid UTF-8 byte sequence.
            var binaryData = BinaryData.FromBytes(content);

            Console.WriteLine(binaryData.ToString()); // This works and prints some garbage

            var stringFromBinaryData = binaryData.ToString();
            byte[] bytesFromString = Encoding.UTF8.GetBytes(stringFromBinaryData);
            Console.WriteLine(bytesFromString.Length); // This prints 4, why not 2 ?
        }
    }
}

```

FYI @JoshLove-msft @tg-msft @pakrym

**Comment by pakrym** [comment]
I think adding this validation now would be a breaking change.
