### ISSUE TITLE
[BUG] GetClient from another client does not pass the Shared Key unable to GenerateSas

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#16953]
**Describe the bug**
If attempting to generate a SAS from a client that is created from another parent client
e.g.
```
BlobServiceClient serviceClient = new BlobServiceClient(connection string) or BlobServiceClient(storageSharedKeyCredential)
BlobContainerClient containerClient = serviceClient.GetContainerClient();
```
the Shared Key Credential does not get passed properly. so CanGenerateSas and GenerateSas and GetAccountSas would fail

**Expected behavior**
What is the expected behavior?
The StorageSharedKeyCredential gets passed properly

**To Reproduce**
```
BlobServiceClient serviceClient = new BlobServiceClient(connection string) or BlobServiceClient(storageSharedKeyCredential)
BlobContainerClient containerClient = serviceClient.GetContainerClient();
containerClient.GenerateSas(..)
```

**Environment:**
Azure.Storage.Blobs 12.7.0

**Comment by Ma3yTa** [comment]
@amnguye when is the expected release date of the new Nuget package version? thanks

**Comment by amnguye** [comment]
We are expecting to make a release (that includes this bug fix) in the coming week.
