### ISSUE TITLE
[BUG] Tables - ETag represents null value unless `TableEntity` is used.

### ISSUE THREAD

**Issue by kieronlanning** [Azure/azure-sdk-for-net#16974]
To reproduce:

1. Add an entity to table storage.
2. Create a class that implements `ITableEntity`
3. Using `GetEntityAsync<TableEntity>(pk, rk)` - note the etag is correct.
4. Using `GetEntityAsync<YourCustomEntity>(pk, rk)` - note the etag represents null.

Examples:

Using TableEntity:

![image](https://user-images.githubusercontent.com/5364423/99141411-0b595400-2643-11eb-843c-be3823937f09.png)

Custom Entity:

Here is the result:

![image](https://user-images.githubusercontent.com/5364423/99141393-e49b1d80-2642-11eb-844c-cbe2c60b3335.png)

Here is the entity:

![image](https://user-images.githubusercontent.com/5364423/99141404-f977b100-2642-11eb-91b9-a228d991f567.png)

**Environment:**
 - Azure.Data.Tables 3.0.0-beta.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Thank you @kieronlanning! This was a regression from https://github.com/Azure/azure-sdk-for-net/pull/16315.

**Comment by kieronlanning** [comment]
@christothes No probs! Do you know when the next release will be?

**Comment by christothes** [comment]
We typically release the second Tuesday of each month. If you'd like to get the bits sooner than that, you can grab them from the nightly dev feed [here](https://dev.azure.com/azure-sdk/public/_packaging?_a=package&feed=azure-sdk-for-net&package=Azure.Data.Tables&protocolType=NuGet&version=3.0.0-alpha.20201117.1&view=overview)

**Comment by kieronlanning** [comment]
Wicked, I'll do that. Thanks @christothes.
