### ISSUE TITLE
Make model types deserializable

### ISSUE THREAD

**Issue by cgillum** [Azure/azure-sdk-for-net#16977]
**Library or service name.**
Azure.ResourceManager.Resources
 
**Is your feature request related to a problem? Please describe.**
Model types such as `Subscription` can be serialized but not deserialized. This is because all the properties have `get` accessors but not `set` accessors. This violates the Azure SDK guidelines as described in the [Service Method Return Types](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-method-return) section:

> Ensure you include an internal setter to allow for deserialization. For more information, see [JSON Serialization](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-usage-json).

My scenario is that I want to expose the service client operations from this SDK behind a service abstraction (specifically for use in [Azure Durable Functions](https://docs.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-overview?tabs=csharp), but there are other valid scenarios as well). I need to be able to deserialize these objects in order to make my scenario work (model entities need to be persisted to storage and then deserialized later). Adding private or internal setters should be sufficient and would make these types compliant with the Azure SDK guidelines that I referenced above.

_FWIW, I am internal so feel free to reach out to me directly for more clarification._

**Comment by jsquire** [comment]
//fyi:  @KrzysztofCwalina, @tg-msft

**Comment by markcowl** [comment]
@cgillum The Azure.* management libraries are currently in preview, and are planned to have a preview update in the New Year,  Before these packages go GA, they will conform with Json serialization requirements in the SDK Guidelines.  Adding @m-nash  to track this issue in the preview and ensure that we address systematically ass soon as possible.

**Comment by pallavit** [comment]
@m-nash , @ArthurMa1978 I believe this issue will be addressed as part of the serialization workflow we are implementing?
Please let me know if that is not the case?
