### ISSUE TITLE
[Perf, Stress] Handle multiple test class ctors

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#16971]
The frameworks assume test classes have a single ctor which accepts the `Options` object.  The frameworks should handle multiple ctors (as long as one matches the expected ctor), and throw a nice error if none match.

https://github.com/Azure/azure-sdk-for-net/pull/16965#discussion_r523284663

**Comment by JimSuplizio** [comment]
Hi @mikeharder, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
