### ISSUE TITLE
[QUERY] How to specify exponential backoff retry policy for Azure.Storage.Blobs.BlobServiceClient

### ISSUE THREAD

**Issue by george-zubrienko** [Azure/azure-sdk-for-net#16980]
**Query/Question**
How to specify exponential backoff retry policy for Azure.Storage.Blobs.BlobServiceClient?

I assumed this code should work:
```
            var _retryOptions = new RetryOptions
            {
                Delay = TimeSpan.FromSeconds(10),
                MaxDelay = TimeSpan.FromSeconds(60),
                MaxRetries = 3,
                NetworkTimeout = TimeSpan.FromSeconds(120),
                Mode = Azure.Core.RetryMode.Exponential
            };

            var _blobClientOptions = new BlobClientOptions()
            {
                Retry = _retryOptions
            };

            _blobClient = new BlobServiceClient(connectionString, _blobClientOptions);
```

but VS compiler doesn't like this at all:
- `RetryOptions` doesn't have a 0-arg constructor, but no others are available
- `Retry` is read-only and there is no way to provide it?

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.7.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure Functions ~3 (.netcore31)
 - IDE and version : Visual Studio 16.7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by george-zubrienko** [comment]
Hi, any updates on this one? :(

**Comment by seanmcc-msft** [comment]
Hi @george-zubrienko,

I'm able to initialize a `RetryOptions` inline:
```
            BlobClientOptions blobClientOptions = new BlobClientOptions
            {
                Retry =
                {
                    Mode = RetryMode.Exponential,
                    MaxRetries = 5,
                    Delay = TimeSpan.FromSeconds(5),
                    MaxDelay = TimeSpan.FromSeconds(10)
                }
            };
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString, blobClientOptions);
```

Please re-open if you have further questions.

-Sean
