### ISSUE TITLE
Default system proxy is not detected when using HttpWebRequest transport 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#16990]

**Comment by zak-nye** [comment]
@pakrym Thanks for doing this fix - I have been experiencing the issue this should fix. Do you have any idea when this will make it into a release? Judging by the date of previous nuget packages it is sometime around the beginning of December...?

**Comment by pakrym** [comment]
@zak-nye this would be out at the beginning of January. We are skipping December to avoid disruptions while a lot of people are out. 

You can work around the failure using the AZURE_CORE_DISABLE_HTTPWEBREQUESTTRANSPORT=true environment variable or app config switch described here: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/CHANGELOG.md#added-2

**Comment by erich-wang** [comment]
Azure PowerShell has applied this fix in Az.Accounts 2.2.3, thanks.
