### ISSUE TITLE
[FEATURE REQ] Support TokenCredential in Azure Files SDK (ShareClient, etc.)

### ISSUE THREAD

**Issue by mj1856** [Azure/azure-sdk-for-net#17000]
With `BlobClient`, we can authenticate using either `StorageSharedKeyCredential` or `TokenCredential`.  However with `ShareClient` (and others from `Azure.Storage.Files.Share`) we can only authenticate with `StorageSharedKeyCredential`.

I should be able to authenticate using a token generated with `DefaultAzureCredental` in either client.

My use case is to get the current used bytes and quota of a file share to determine percent full.  The following program works:

```csharp
static async Task Main(string[] args)
{
    var client = new ShareClient(
        new Uri("https://myaccountname.file.core.windows.net/mysharename"), 
        new StorageSharedKeyCredential("myaccountname", "myaccountkey"));
    
    Task<Response<ShareStatistics>> statsTask = client.GetStatisticsAsync();
    Task<Response<ShareProperties>> propertiesTask = client.GetPropertiesAsync();
    await Task.WhenAll(statsTask, propertiesTask);
    ShareStatistics stats = statsTask.Result.Value;
    ShareProperties properties = propertiesTask.Result.Value;

    long usedBytes = stats.ShareUsageInBytes;
    int usedGiB = (int) (usedBytes / 1024 / 1024 / 1024);

    int quotaGiB = properties.QuotaInGB!.Value;
    long quotaBytes = (long)quotaGiB * 1024 * 1024 * 1024;
    
    double pct = 100.0 * usedBytes / quotaBytes;

    Console.WriteLine($"{usedGiB} GiB / {quotaGiB} GiB = {pct:F1}%");
}
```

I should instead be able to do this:

```csharp
static async Task Main(string[] args)
{
    var client = new ShareClient(
        new Uri("https://myaccountname.file.core.windows.net/mysharename"),
        new DefaultAzureCredential());

    Task<Response<ShareStatistics>> statsTask = client.GetStatisticsAsync();
    Task<Response<ShareProperties>> propertiesTask = client.GetPropertiesAsync();
    await Task.WhenAll(statsTask, propertiesTask);
    ShareStatistics stats = statsTask.Result.Value;
    ShareProperties properties = propertiesTask.Result.Value;

    long usedBytes = stats.ShareUsageInBytes;
    int usedGiB = (int)(usedBytes / 1024 / 1024 / 1024);

    int quotaGiB = properties.QuotaInGB!.Value;
    long quotaBytes = (long)quotaGiB * 1024 * 1024 * 1024;

    double pct = 100.0 * usedBytes / quotaBytes;

    Console.WriteLine($"{usedGiB} GiB / {quotaGiB} GiB = {pct:F1}%");
}
```

**Comment by mj1856** [comment]
Maybe the issue is that it's not possible to perform this operation on the service without a shared key? Not sure.

**Comment by jsquire** [comment]
Hi @mj1856.   Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
We cannot support this feature request because SMB Files cannot authenticate with a TokenCredential, you have to provide the Shared Key Credential.

Sorry for the inconvenience

**Comment by Matthewsre** [comment]
@amnguye I thought TokenCredential support was going to be standard in all of the Azure.* SDKs. I believe it was ServiceBus that had the same type of challenge where keys are used, but they were still able to handle leveraging TokenCredential to get the keys and handle getting the required credentials under the hood. I just want to use my TokenCredential with the proper role assignments that would enable getting the proper credentials for this to work. Is this something that could be added to align with the rest of the Azure.* SDKs?

**Comment by Matthewsre** [comment]
It looks like this was an option in the V11 SDK using StorageCredentials(TokenCredential).

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.auth.storagecredentials?view=azure-dotnet
