### ISSUE TITLE
[QUERY] Using Key Vault with a Windows Forms application

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-sdk-for-net#17018]
My company has a WinForms application that is deployed to multiple client machines. This application currently connects directly to an Azure SQL database (don't ask about the reasons), which means it needs that DB's connection string stored in its configuration file. To improve security, we'd like to move the connection string into Key Vault and have the app pull it down as needed.

It seems like this scenario has been considered, because the docs have an example of using a client certificate to accomplish this: https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-3.1#use-application-id-and-x509-certificate-for-non-azure-hosted-apps

That all looks promising until step #4, "Register the app with Azure AD (App registrations)". When I go to register my application in the Azure Portal, it asks me to specify the supported account types - but my app isn't (as far as I know) going to be using **any** account to authenticate, it's going to be using the client cert!

Are account types not relevant to the client certificate scenario? If they are, which option should I select here?

**Comment by jsquire** [comment]
//cc: @heaths

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
The certificate is used to authenticate the application, so the app registration is necessary. It's really just creating a service principal, which would be equivalent to `az ad sp create-for-rbac` using the Azure CLI. The app is then authorized to access SQL with whatever role (built-in or custom as needed) has the minimal permissions you need.

**Comment by IanKemp** [comment]
> The certificate is used to authenticate the application, so the app registration is necessary. It's really just creating a service principal, which would be equivalent to `az ad sp create-for-rbac` using the Azure CLI. The app is then authorized to access SQL with whatever role (built-in or custom as needed) has the minimal permissions you need.

I understand that the app registration is necessary - what I don't understand is which account type I should select during the process, since my app won't technically be using any accounts:

![image](https://user-images.githubusercontent.com/1726434/99682410-12cf9180-2a77-11eb-9890-e58f9c52c747.png)

The help popout for "Help me choose..." doesn't provide any information relevant to the app-with-client-certificate scenario:

![image](https://user-images.githubusercontent.com/1726434/99682813-91c4ca00-2a77-11eb-8b15-dc7bf13335c3.png)

In the end, I chose "Accounts in this organizational directory only", which to my mind is the correct one as the service principal being created is effectively an account, and of course internal to my organisation. Please advise if this is correct or not?

**Comment by heaths** [comment]
Yes, the service principal is an account that you can associate passwords, certificates, etc. If your resource is in the same tenant and you either don't have other tenants or don't suspect you'll ever move the resource, yes, I'd say you chose correctly with a single tenant application.
