### ISSUE TITLE
Cannot reRegisterMessageHandler after calling UnregisterMessageHandlerAsync

### ISSUE THREAD

**Issue by SMooren** [Azure/azure-sdk-for-net#17013]
when calling UnregisterMessageHandlerAsync runningTaskCancellationTokenSource gets disposed. RegisterMessageHandler only checks whether or not the token is null not if it was disposed thus you cannot Call RegisterMessageHandler for a second time.
https://github.com/Azure/azure-sdk-for-net/blob/5655e978ab32cd4e94402c846420a0230a0ba2d2/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Core/MessageReceiver.cs#L1335

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@SMooren  Could you elaborate on the use-case where you want to unregister and then re-register?

**Comment by SMooren** [comment]
We are have a condition on when we want to process messages when the condition is false we stop the processing using UnregisterMessageHandlerAsync but we cannot Restart the process because of the issue. We do not want to use ReceiveMessagesAsync because RegisterMessageHandler has some features we do not we to build our selfs (MaxConcurrentCalls, exceptionHandling etc)

**Comment by axisc** [comment]
@SMooren - even if you stop processing the messages, the messages will continue to pile up on the queue/subscription. This will then be picked up when you re-register the message handler. 

In that case, what is achieved by unregistering the message handler?

**Comment by axisc** [comment]
closing this for now. Please feel free to reopen if there are further questions.

**Comment by BertCotton** [comment]
We have the use case where we would like to pause processing for a period of time and then start back up.

We have a business case were data is being refreshed from one source to another.  During that time we need to pause the processing.  

I had hoped that I could Unregister while the data is being refreshed, and once it is done, continue processing through the messages that have piled up.
