### ISSUE TITLE
[QUERY] Azure.Messaging.ServiceBus question - calling DeadLetterMessageAsync in the ProcessMessageAsync event handler

### ISSUE THREAD

**Issue by yaeldekel** [Azure/azure-sdk-for-net#17010]
**Query/Question**
How can we help?
I would like to catch some exceptions in the `ProcessMessageAsync` event handler, and call `args.DeadLetterMessageAsync` when they occur, (in order to prevent the message from staying in the queue). However, it seems that if I do that and the lock expires, the `ProcessErrorAsync` event handler gets called anyway, and somehow the message ends up back in the queue. Is there a way to prevent this? Or, alternatively, is there a way to access the `ServiceBusReceiver` in the error handler and call `DeadLetterMessageAsync` from there?

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.ServiceBus version 7.0.0-preview.9
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Core 3.1
 - IDE and version : Visual Studio Version 16.7.7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
@yaeldekel thanks for the question.
Once you lose the lock on a message, you aren't able to dead-letter it as another receiver may have the lock. You would need to receive the message again to dead-letter it. Are you losing the lock often? Is your processing taking a long time typically? The default amount of time that the processor will renew the lock is 5 minutes, but this can be configured to be longer if needed - https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Messaging.ServiceBus/7.0.0-preview.9/api/Azure.Messaging.ServiceBus/Azure.Messaging.ServiceBus.ServiceBusProcessorOptions.html#Azure_Messaging_ServiceBus_ServiceBusProcessorOptions_MaxAutoLockRenewalDuration

**Comment by yaeldekel** [comment]
@JoshLove-msft, thanks for the answer and for the reference. Just to make sure I understand it correctly:
* The message goes back to the queue immediately when the lock expires, and can be picked up by a different processor, correct?
* When does a processor pick up a new message, is it only after the message processor event handler exits, or is it as soon as the lock expires? (assuming that I set `MaxConcurrentCalls` to be 1)
* In case the error handler gets invoked, when does the processor pick up a new message?

I am thinking of the following scenario: The `ProcessMessageAsync` event handler catches an exception, but after losing the lock - by that time, is another processor already processing it again? Is there a way to dead-letter a message in such a case without retrying it?

**Comment by JoshLove-msft** [comment]
> The message goes back to the queue immediately when the lock expires, and can be picked up by a different processor, correct?

Correct, if the lock is expired a different processor might have already received the message.

> When does a processor pick up a new message, is it only after the message processor event handler exits, or is it as soon as the lock expires? (assuming that I set MaxConcurrentCalls to be 1)

With MaxConcurrentCalls of 1, you wouldn't pick up a new message until after the processor event handler exits.

> In case the error handler gets invoked, when does the processor pick up a new message?

It would be after the error handler is invoked as well. 

> I am thinking of the following scenario: The ProcessMessageAsync event handler catches an exception, but after losing the lock - by that time, is another processor already processing it again? Is there a way to dead-letter a message in such a case without retrying it?

If you are the only consumer of your queue and you are using MaxConcurrentCalls = 1, then the message would not be received again yet. There isn't a way to dead-letter the message without first receiving it again.

**Comment by JoshLove-msft** [comment]
@yaeldekel, thanks for the question - I'm going to close this out now. Please reopen if you have further questions.
