### ISSUE TITLE
Enable FxCop Analyzers

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#17022]
Building on #7467, we should enable FxCop analyers: https://docs.microsoft.com/visualstudio/code-quality/install-fxcop-analyzers. Not only is this recommended by TwC but it allows us to catch things like `catch (Exception ex) { /* do stuff */ throw ex; }` ([CA2200](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2200)).

To note, some of this can be enabled via our existing .editorconfig: https://docs.microsoft.com/dotnet/fundamentals/code-analysis/code-quality-rule-options

**Comment by heaths** [comment]
We might start with .NET's https://github.com/dotnet/runtime/blob/master/eng/CodeAnalysis.ruleset since we started with their .editorconfig as well (with 1 small tweak I don't remember).

**Comment by pakrym** [comment]
Update the package to the latest version.
