### ISSUE TITLE
[FEATURE REQ] Azure Monitor Exporter - Support OpenTelemetry Semantics 

### ISSUE THREAD

**Issue by rajkumar-rangaraj** [Azure/azure-sdk-for-net#17026]
**Library or service name.**
What library or service is this request related to? Microsoft.OpenTelemetry.Exporter.AzureMonitor
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

* Identify `HTTP`, `RPC`, `FaaS`, `Messaging`, `Db` and `Azure` from OpenTelemetry Batch Activity. 
* Parse identified semantics and set the Request and Dependency telemetry data, type, source and target.

**Comment by vishweshbankwar** [comment]
closing this as it is completed.
