### ISSUE TITLE
[WebJobs/EventHubs] Processor takes long time to stop

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17049]
EventProcessor takes MaximumWaitTime. Follow up it it's acceptable for WebJobs and what did T1 do.

**Comment by jsquire** [comment]
v5.4.1 of the Event Hubs client library includes some enhancements in this area; for the majority of scenarios, the processor is now able to avoid waiting for the timeout to complete before responding to a Stop request.

**Comment by pakrym** [comment]
I think it's fast enough. I haven't heard any more complaints.
