### ISSUE TITLE
Create App Service Wizard hangs when a resource group does not exist in the subscription

### ISSUE THREAD

**Issue by BernieWhite** [Azure/azure-sdk-for-net#1704]
Running Azure SDK 2.8.1, when trying to create a new Web App the Create App Service Wizard on an ASP.NET 5 project the wizard hangs if a resource group does not already exist in the subscription.

Anybody else seeing this? Isolated case?

**Comment by MikeCer** [comment]
Hi Bernie, yes, I confirm ... same behavior here!

**Comment by lebowitz** [comment]
Still a problem in 2.9!

**Comment by arthurspa** [comment]
Same problem here.

**Comment by ronaldnsabiyera** [comment]
I can confirm as well on VS2015 Update 3

**Comment by borysl** [comment]
I have created the group, but it looks even if you have a group, but doesn't have a service app and service plan VS2015 Update 3 (I use community edition) still hangs

**Comment by naveedaz** [comment]
Does this issue still repro?

**Comment by Petermarcu** [comment]
Since @naveedaz hasn't gotten a response, I'm going to close this for now. If someone does hit this issue again, please open a new issue with exact versions of everything you are trying to use.
