### ISSUE TITLE
Azure SDK installation fails if you have Azure PowerShell module installed from PowerShell Gallery

### ISSUE THREAD

**Issue by slavizh** [Azure/azure-sdk-for-net#1706]
Azure SDK installation fails if you have Azure PowerShell modules installed from PowerShell Gallery.
It will be good if Azure SDK does not rely on Azure PowerShell module msi. That way I cannot use the latest version of Azure PowerShell modules with the SDK. 
Workaround is to remove the Azure PowerShell modules installed from the PowerShell Gallery, install the Azure SDK, remove the Azure PowerShell module from Control Panel and than install it again from PowerShell Gallery. The workaround is not suitable for long term.

**Comment by hovsepm** [comment]
@slavizh I cannot repro it with the latest Azure PowerShell modules and Azure SDK installer 2.8.2. Please use latest installers and reopen this bug with more details if it still repro's.
