### ISSUE TITLE
The way of storage blob endpoint constructed in Azure SDK for net doesn't support use in azurite

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-net#17074]
**Error Description:**
[Azurite](https://github.com/Azure/Azurite) is an Azure Storage emulator. 
Current endpoint which is constructed in azure sdk for net can not access azurite. The reason is the storage blob endpoint for Azurite is different from the one of an Azure storage account.
In Azurite, storage blob endpoint constructed is shown as following:
```
https://127.0.0.1:10000/<account-name>/<resource-path>
```
In Azure SDK for net, storage blob endpoint constructed is shown as following:
```
https://<account-name>.blob.core.windows.net/<resource-path>
```

**Error Track:**
The code for storage blob endpoint constructed in Azure SDK for net is [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/src/Shared/StorageConnectionString.cs#L853)
![Screenshot 2020-11-19 142713](https://user-images.githubusercontent.com/20970631/99629750-7eaffb00-2a73-11eb-9098-72224018c95d.png)
![Screenshot 2020-11-19 142815](https://user-images.githubusercontent.com/20970631/99629753-7fe12800-2a73-11eb-9f42-b7fa85c20493.png)

**Expected Behavior**
Storage blob endpoint which is constructed in azure sdk for net can access azurite.

@jongio for notification.

**Comment by jsquire** [comment]
//fyi: @jongio

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Can you provide a reproduceable snippet to show this error? We actually have tests surrounding custom endpoints and I altered the tests to try to accurately portray the issue you are running into but I was unable to see.

I see that you provided the code in question that is causing the problem. However it might be that we are parsing the endpoint correctly elsewhere (that's where a code snippet would be helpful, incase my tests aren't running the same codepath you are).

Related: Just wanted to make sure that the other issue that you posted gets relayed here as well https://github.com/Azure/azure-sdk-for-net/issues/17522

**Comment by zzhxiaofeng** [comment]
@amnguye  Well, I find this issue by this [test case](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L67) and you can use the test case as reproduceable snippet.

**Comment by zzhxiaofeng** [comment]
@amnguye Well, the problem still exists. I find the issue by this [test case](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L67). In this test case, the method `GetConnectionString` calls the method `ConstructUris` which is shown in my picture.  You can use the test case as reproduceable snippet.

**Comment by amnguye** [comment]
Hi,

I ran the test case with both `true` and `false` cases, and those both pass.

Could you provide a code snippet that would reproduce the error you are running into?

**Comment by zzhxiaofeng** [comment]
@amnguye Ok, I write a demo to reproduce the error. It needs to be placed under the `azure-sdk-for-net\sdk\storage\Azure.Storage.Blobs\tests` folder if you want to use it. The demo is shown as following:
```
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

using System;
using System.Threading.Tasks;
using Azure.Storage.Test;
using Azure.Storage.Test.Shared;
using NUnit.Framework;

namespace Azure.Storage.Blobs.Tests
{
    public class Demo : BlobTestBase
    {
        public Demo(bool async, BlobClientOptions.ServiceVersion serviceVersion)
            : base(async, serviceVersion, null /* RecordedTestMode.Record /* to re-record */)
        {
        }

        [Test]
        public async Task Test()
        {
            string accountName = "<Azurite-account-name>";
            string accountKey = "<Azurite-account-key>";
            (Uri, Uri) serviceUri = StorageConnectionString.ConstructBlobEndpoint(
                Constants.Https,
                accountName,
                default,
                default);
            StorageSharedKeyCredential credential = new StorageSharedKeyCredential(accountName, accountKey);
            BlobServiceClient service = new BlobServiceClient(serviceUri.Item1, credential);

            await TestHelper.AssertExpectedExceptionAsync<RequestFailedException>(
                service.GetPropertiesAsync(),
                e => Assert.AreEqual("AuthenticationFailed", e.ErrorCode));
        }
    }
}
```
Note: Please make sure the demo runs in Azurite server.

**Comment by v-xuto** [comment]
azsdk-azurite

**Comment by v-xuto** [comment]
@scottaddie, @AlexGhiondea, @kyle-patterson, @tg-msft, @amishra-dev Do you have any ideas or plans to fix this issue?

**Comment by JimSuplizio** [comment]
Hi @zzhxiaofeng, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
