### ISSUE TITLE
DeploymentProperties.Parameters is an object in Microsoft.Azure.Management.Resources.3.3.1-preview

### ISSUE THREAD

**Issue by cwchapma** [Azure/azure-sdk-for-net#1707]
Why are DeploymentProperties.Parameters and DeploymentProperties.Template of type object in the nuget package Microsoft.Azure.Management.Resources 3.3.1-preview but they are strings in the source since at least March 25, 2015.

https://github.com/Azure/azure-sdk-for-net/blame/21db6e5490e66af39a9c6dbf0ad10650d9ca037b/src/ResourceManagement/Resource/ResourceManagement/Generated/Models/DeploymentProperties.cs

They seem to be unusable as objects.  I've tried passing json strings directly and json serializable objects - neither worked.

**Comment by isaacabraham** [comment]
+1 - this is really confusing. The powershell version of this allows you to supply local template files but it appears that the .NET one forces you to upload to blob first which is a real pain.

**Comment by isaacabraham** [comment]
Links to #1777 and #1749

**Comment by ravbhatnagar** [comment]
We should support strongly typed objects for template and parameter. In the meantime, you can still use local file. But you will have to pass in the contents of the file to the Template and Parameter properties as below:
 string pathToTemplate = @"E:\Azure\ARM\Templates\Website\Web Site.json";
 string pathToParameter = @"E:\Azure\ARM\Templates\Website\WebSite.param.net.json";

JObject templateFileContent = GetJsonFileContents(pathToTemplate);
JObject parameterFileContent = GetJsonFileContents(pathToParameter);

public static JObject GetJsonFileContents(string pathToJson)
        {
            JObject templatefileContent = new JObject();
            using (StreamReader file = File.OpenText(pathToJson))
            {
                using (JsonTextReader reader = new JsonTextReader(file))
                {
                    templatefileContent = (JObject)JToken.ReadFrom(reader);
                    return templatefileContent;
                }
            }

        }
.........
deployment.Properties = new DeploymentProperties
            {
                Mode = DeploymentMode.Complete,
                Template = templateFileContent,
                Parameters = parameterFileContent
            };

**Comment by blumu** [comment]
There is a design issue with the API. This API is expecting a JObject from version 6.0 of JSon.net as input to the template parameter. If you program uses a more recent version of JSon.net (e.g. 8.0) the call will fail with the following error:

	'Error reading string. Unexpected token: StartArray. Path 'properties.template.$schema', line 4, position 19.'.

**Comment by isaacabraham** [comment]
@ravbhatnagar @blumu thanks for the tips - this helps.

I think that the simplest solution from an consuming API point of view (for the future) would be to be able to provide the string contents of the two files themselves, rather than having to convert it to a JObject or pass the filename (one could dynamically construct templates).

**Comment by TarasRoshko** [comment]
Any updates? This API is just wow

**Comment by olivierdagenais** [comment]
For the record, I encountered the same result as @TarasRoshko when I tried to provide a `JObject` to the `Template` property, but a `string` representing the JSON worked.

**Comment by adrianhall** [comment]
My apologies for this taking so long.  Is this still an issue?

**Comment by khipukamayuq** [comment]
@adrianhall Still an issue for me. Azure.Management.ResourceManager version 2.0.0. Newtonsoft 12.0.1. Sending template and parameter JObjects as DeploymentProperties on Deployment object in Deployments.CreateOrUpdate. Getting the above _cannot convert to type_ message.

**Comment by Petermarcu** [comment]
@filizt

**Comment by filizt** [comment]
@alex-frankel

**Comment by filizt** [comment]
> @adrianhall Still an issue for me. Azure.Management.ResourceManager version 2.0.0. Newtonsoft 12.0.1. Sending template and parameter JObjects as DeploymentProperties on Deployment object in Deployments.CreateOrUpdate. Getting the above _cannot convert to type_ message.
> 
> Neither string nor JObject is being accepted for me.
> 
> 2nd edit: fixed an issue with my dynamically generating a value. Now I'm getting the _Long running operation failed with status 'Failed'_ that I've seen in other related issues.
> 
> 3rd edit: Got it. Was server/resource group mismatch.

@khipukamayuq Thanks for your updates though I am unsure if I understand if you still see the issue. Please let us know if that's the case.

**Comment by alex-frankel** [comment]
Closing as it looks like you have resolved this issue. If this is not resolved, let us know and we can reopen
