### ISSUE TITLE
[QUERY] Azure ServiceBus TopicClient Retry Policy

### ISSUE THREAD

**Issue by kabirhussain** [Azure/azure-sdk-for-net#17080]
**Query/Question**
How can we help?

Hi Community,

I have custom Retry Policy class for my Azure TopClient. Class is inheriting from **RetryPolicy** and  I am overriding the following method:
```
abstract bool OnShouldRetry(TimeSpan remainingTime, int currentRetryCount, out TimeSpan retryInterval);
```
From what I have observed, the first argument (**remainingTime**) is the total time of the operation being performed e.g. if its 20 seconds then the retry will occur only within this timeframe. 

Question I have, is their a configuration of setting a timeout per attempt i.e. lets say from the above code the (**remainingTime**) is 20 seconds and I have a total of 3 retry attempts. When the first retry occurs I want it to timeout within x seconds but within the time frame of (**remainigTime** )?
This is to reduce each attempts during the timeframe of the (**remainingTime**)

**Environment:**
 - Microsoft.Azure.ServiceBus 5.0.0
 - .NET runtime version: .NET Framework 4.7.2
 - IDE and version : Visual Studio 16.7.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@kabirhussain There is no configuration setting to override this. To truly modify this, you will have to extend the RetryPolicy class.

hope this helps.
#please-close

**Comment by kabirhussain** [comment]
> @kabirhussain There is no configuration setting to override this. To truly modify this, you will have to extend the RetryPolicy class.
> 
> hope this helps.
> #please-close

Thank you for the response but i am extending RetryPolicy class as mentioned from the post. Can you please elaborate what you mean by truly modify it as i unable to see how to change this?
