### ISSUE TITLE
Improve code coverage for track 2 management, then re-enable code coverage

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#17090]
In PR https://github.com/Azure/azure-sdk-for-net/pull/17067 I'm disabling code coverage of track 2 management libraries because there is very little coverage and it significantly reduces the reported coverage of other track 2 libraries. For example, track 2 Key Vault client coverage at this moment is over 70% on average, but with track 2 management coverage brings that down to 60% - itself only at 30%.

I'll add details about how to re-enable code coverage when the PR is complete .

**Comment by YalinLi0312** [comment]
@m-nash Please follow up.
