### ISSUE TITLE
Fixed the broken links reported by aggregate-report

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-net#17105]
Here are failed links need to be fixed:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=625528&view=logs&j=10327055-d4d6-50a6-a312-3d2cd4bd9cb9&t=65f0e4aa-f456-5911-deca-bd807ca3354c

**Comment by jsquire** [comment]
Unless I'm misreading, it appears the links in the report all resolve to AppConfig samples.   Asking the folks working on AppConfig to take look and triage.

**Comment by maririos** [comment]
@weshaggard fixed this in PR https://github.com/Azure/azure-sdk-for-net/pull/17127
