### ISSUE TITLE
[BUG] Azure Batch CloudTask alters command line

### ISSUE THREAD

**Issue by lastcoolnameleft** [Azure/azure-sdk-for-net#17107]
**Describe the bug**
Using the Azure Batch .NET SDK, I want to create a task echo's an environment variable's value on a Linux host.  

SEE: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.cloudtask.-ctor?view=azure-dotnet#Microsoft_Azure_Batch_CloudTask__ctor_System_String_System_String_

Example code:
```
await batchClient.JobOperations.AddTaskAsync(jobId, new CloudTask("task0", "echo $AZ_BATCH_POOL_ID"));
```

Output:
```
$AZ_BATCH_POOL_ID
```

I believe this is because the SDK is altering the command line to add a `\` in front of the `$` causing the literal `$` to be printed instead of interpreted.

**Expected behavior**
What is the expected behavior?

Instead of printing out the literal `$AZ_BATCH_POOL_ID`, I expect it to print out the actual Batch Pool ID.
**Actual behavior (include Exception or Stack Trace)**

What is the actual behavior?

The output for that task is the literal `$AZ_BATCH_POOL_ID`

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Use the Azure Batch Sample as a base.
2. Update to use an Linux/Ubuntu host
3. Add a AddTaskAsync: `await batchClient.JobOperations.AddTaskAsync(jobId, new CloudTask("task0", "echo $AZ_BATCH_POOL_ID"));`

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Batch v14.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure Batch + .NET SDK 5.0
```
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.302 [/usr/local/share/dotnet/sdk]
  5.0.100 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by lastcoolnameleft** [comment]
I discovered the issue, which I believe is in the documentation.

What works is:
```
await batchClient.JobOperations.AddTaskAsync(jobId, new CloudTask("task2", "/bin/sh -c \"echo $AZ_BATCH_JOB_ID\""));
```

The documentation here talks about needing `/bin/sh -c mycommand $MY_ENV_VAR`; however, that is inaccurate.  You need additional quotes around the command (e.g. /bin/sh -c "echo $AZ_BATCH_JOB_ID")

https://docs.microsoft.com/en-us/azure/batch/batch-compute-node-environment-variables
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.cloudtask.commandline?view=azure-dotnet

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by lastcoolnameleft** [comment]
I opened a ticket to update the documentation which has been merged.  Marking as closed: https://github.com/MicrosoftDocs/azure-docs/pull/66405
