### ISSUE TITLE
Remove an explicit UseDotNet step when .NET 5 would be available on Devops machines

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17118]
actions/virtual-environments#1891

**Comment by jsquire** [comment]
The associated pull requests have been merged; closing this out.   Please feel free to reopen if this is still tracking active work.

**Comment by pakrym** [comment]
Still needed. https://github.com/Azure/azure-sdk-for-net/pull/17281 is the real PR.

**Comment by jsquire** [comment]
Sorry about that.   Sliding the milestone for compliance.

**Comment by pakrym** [comment]
No problem at all. Being more aggressive with the cleanup is something I wholeheartedly support.
