### ISSUE TITLE
[BUG] BlobClient.Exists() throws exception when blob is missing.

### ISSUE THREAD

**Issue by hultqvist** [Azure/azure-sdk-for-net#17129]
**Describe the bug**

Calling BlobClient.Exists() throws an exception when the specified blob is missing.

```C#
new BlobClient(connectionString, containerName, "Exists.json").Exists(); //Works
new BlobClient(connectionString, containerName, "DoesntExist.json").Exists(); //Throws exception
```

**Expected behavior**

Return value false.

**Actual behavior (include Exception or Stack Trace)**

Azure.RequestFailedException: 'Service request failed.
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound

**To Reproduce**

```C#
var connectionString="..." //From Azure portal
var containerName = "data" //Manually created
new BlobClient(connectionString, containerName, "Exists.txt").Exists();
new BlobClient(connectionString, containerName, "DoesntExist.txt").Exists();
```

![image](https://user-images.githubusercontent.com/505330/99852938-519e3e00-2b82-11eb-998c-ff9b4f3210cb.png)

**Environment:**
 - Azure.Storage.Blobs 12.7.0
 - Visual Studio 16.8.2

.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by hultqvist** [comment]
Although a separate example it falls within the same category of "throwing exception for reason it should? handle"

I'm running this sample code to download.

https://github.com/Azure/azure-sdk-for-net/blob/620a140bf82af37148cc172f468a26a2eb29de3f/sdk/storage/Azure.Storage.Blobs/samples/Sample01a_HelloWorld.cs#L67-L104

I simplified the code and replaced all random generated container and blob names with fixed strings.
Thus when the code was aborted the container still existed, so I changed the following 

```C#
container.Create(); //From
container.CreateIfNotExists(); //To
```

Then I get this error:

    The specified container already exists.

![image](https://user-images.githubusercontent.com/505330/99869433-46bbcb80-2bcb-11eb-9127-d49ccc9af9e9.png)

Similar how I expected BlobClient.Exists() to return false if the blob doesn't exist, I expected BlobContainerClient.CreateIfNotExists() to silently continue if the container already existed.

**Comment by amnguye** [comment]
Hi I'm having trouble reproducing your issue. I tried running both examples where you were running into the issue however both exceptions were caught.

Probably an unrelated question, but why don't you have your code doing `bool existsResult = container.CreateIfNotExists()` but you only have `container.CreateIfNotExists()`? Do you not care about whether or not the blob or container exists?

**Comment by hultqvist** [comment]
I will check next week and see if I can zip a test project.

Correct, in this case I don't care whether or not the container existed before, only that it exists for the rest of the code.
The typical use case is to include all setup code at the start, so when I run the code with a new configuration or reset the storage it won't fail on a missing container.

**Comment by hultqvist** [comment]
My bad,
It appears that the exceptions thrown were caught before reaching my code shown in the screenshots.

This code was running in an ASP.NET Core project where the concept of unhandled exceptions is not the same as in console projects. Therefore I had changed the exception settings to stop on all exceptions, which happened to be inside the Azure SDK before leaving for my code.

**Comment by Perrow** [comment]
The Exists call generates an exception for us that gets logged to Application Insights. While our code works (exception does not reach our code) the AppInsights log sees a lot of errors that shouldn't be there.

**Comment by RichMercer** [comment]
@Perrow A PR to supress this error was merged recently. https://github.com/Azure/azure-sdk-for-net/pull/20064

**Comment by kajalsharma-dev** [comment]
Hi , I got error in Application insights "BlobBaseClient.Exists" 404 error but my code working fine . I am using ExistsAsync() and DeleteIfExistsAsync() functions also but I don't understand why I am getting this error in application Insights.

**Comment by kajalsharma-dev** [comment]
I got error of 404 in console window and application Insight also .Can you please help me how can I resolve this error .

**Comment by RDavis3000** [comment]
Same here, getting loads of these in my AppInsightsExtension/DetailsV2Blade/ which I mistakenly believed were something I needed to look into. If this is part of the internal, non exceptional, operation of the method, why is is leaking into my logs and application insights?

**Comment by renaudrenaud85** [comment]
Same problem here. Really strange, I can't even wrap with try-catch, the RequestFailedException will be logged anyway.

**Comment by webbes** [comment]
Same here... it's pretty stupid to have your logs flooded with this nonsense. For more than a year now...

**Comment by amnguye** [comment]
Hi, please open a new issue as the current issue has been close and is unrelated to the issue you are running into.

The original customer was running into an issue of the Exception still being thrown even though they were using the *Exists method. The issue has been commented on here since the issue has been since closed by the original poster is that application insights logs are being flooded with these exceptions.

Looks like your issue that your running into is more related to either
https://github.com/Azure/azure-sdk-for-net/issues/19982
https://github.com/Azure/azure-sdk-for-net/issues/9908

Please do not future comment on this post as it's creating buzz for the original creator of the post who does not have the same exact issue as you (and as they have already resolved their issue).
