### ISSUE TITLE
PolicyAssignments.ListForScope fails because of API version

### ISSUE THREAD

**Issue by bvirkler** [Azure/azure-sdk-for-net#1712]
Using Microsoft.Azure.Management.Resources 3.3.1-preview.

    string scope = string.Format("/subscriptions/{0}/", subscriptionId);
    ResourceManagementClient client = new ResourceManagementClient(new TokenCredentials(GetToken()));
    client.SubscriptionId = subscriptionId;
    var result = client.PolicyAssignments.ListForScope(scope);

throws this exception:

>Microsoft.Rest.Azure.CloudException: The resource type 'policyAssignments' could not be found in the namespace 'Microsoft.Authorization' for api version '2014-04-01-preview'. The supported api-versions are '2015-10-01-preview'.

`ResourceManagementClient.ApiVersion` is read-only and hard-coded to '2014-04-01-preview'.  Shouldn't callers be able to override that?

**Comment by hovsepm** [comment]
@bvirkler the idea behind api version is that they are bound to a functionality. If we allow overriding this parameter in the SDK then there is no guarantee that other method calls will work,

**Comment by bvirkler** [comment]
That makes sense.  But I would have thought whoever generated the client classes for policyAssignments would have bumped the API version and tested.  Otherwise what's the point of having the classes?  Or am I missing something?
