### ISSUE TITLE
Use PackageReference for ReportGenerator instead of tool

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#17136]
Using a tool for ReportGenerator requires running `dotnet tool restore` separately. Instead, we can use a `PackageReference` with all private assets and just reference it explicitly (will need to get the version, but there are ways).

Relates to #14427

**Comment by AlexGhiondea** [comment]
@heaths what's the advantage of using package references vs using dotnet tool restore? It looks like there is some additional work needed if we move to package references.

**Comment by heaths** [comment]
For CIs it's not really a problem since I added that step as an early step before build. But for end users, it's something extra they have to do if they want to personally run code analysis.

That said, no one has asked questions or given comment about it, so I'll close this.
