### ISSUE TITLE
ServiceBusManagementClient null reference exception when using HttpClient and creating Azure Namespace

### ISSUE THREAD

**Issue by afdabro** [Azure/azure-sdk-for-net#1713]
I'm currently attempting to use a Windows Azure Management Certificate for authenticating with Service Management API.

Steps:
1) Retrieve Azure Management Certificate -- Returns valid Management certificate
2) Create Service Bus Management Client
3) Create Azure Namespace -- Throws Null reference Exception

NuGet Package info:
Id Microsoft.WindowsAzure.Management.ServiceBus
Version: 0.17.1-preview (Prerelease)

Snippet:
[ServiceBusManagementClient Certificate Snippet.txt](https://github.com/Azure/azure-sdk-for-net/files/81737/ServiceBusManagementClient.Certificate.Snippet.txt)

I decompiled NamespaceOperations for the CreateNamespaceAsync method and noticed this.Client.Credentials and this.Client.BaseUri both have a chance to throw a null reference exception if the objects are not set. I verified the ServiceBusManagementClient (Client) constructor with HttpClient is not setting either property:

    /// <summary>
    /// Initializes a new instance of the ServiceBusManagementClient class.
    /// 
    /// </summary>
    /// <param name="httpClient">The Http client
    ///             </param>
    public ServiceBusManagementClient(HttpClient httpClient)
      : base(httpClient)
    {
      this._namespaces = (INamespaceOperations) new NamespaceOperations(this);
      this._notificationHubs = (INotificationHubOperations) new NotificationHubOperations(this);
      this._queues = (IQueueOperations) new QueueOperations(this);
      this._relays = (IRelayOperations) new RelayOperations(this);
      this._topics = (ITopicOperations) new TopicOperations(this);
      this._apiVersion = "2013-08-01";
      this._longRunningOperationInitialTimeout = -1;
      this._longRunningOperationRetryTimeout = -1;
      this.HttpClient.Timeout = TimeSpan.FromSeconds(300.0);
    }

I know the service bus management packages are in a pre-release state. Is there a work around for using a management certificate?

Thanks!

**Comment by hovsepm** [comment]
@afdabro to use a management certificate you will need to construct SubscriptionCloudCredentials manually. You can refer to a code that we have in Authetication library on how to handle custom authentication - https://github.com/Azure/azure-sdk-for-net/blob/master/src/Authentication/Common.Authentication/Authentication/AccessTokenCredential.cs
