### ISSUE TITLE
Sample project throws "Timeouts are not supported on this stream."

### ISSUE THREAD

**Issue by hultqvist** [Azure/azure-sdk-for-net#17141]
**Query/Question**

I'm trying to download a blob using this sample.

https://github.com/Azure/azure-sdk-for-net/blob/620a140bf82af37148cc172f468a26a2eb29de3f/sdk/storage/Azure.Storage.Blobs/samples/Sample01a_HelloWorld.cs#L67-L104

Creating the container and uploading to a new blob works, but downloading throws an exception.

> **System.InvalidOperationException:** 'Timeouts are not supported on this stream.'

![image](https://user-images.githubusercontent.com/505330/99869797-1b86ab80-2bce-11eb-9767-38a859f93ffb.png)

**Environment:**
 - Azure.Storage.Blobs 12.7.0
 - Visual Studio 16.8.2

.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.200 [C:\Program Files\dotnet\sdk]
  3.1.300-preview-015048 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jarahn** [comment]
Have there been any updates regarding this issue?

**Comment by hultqvist** [comment]
Sorry nothing has changed.

At this moment I'm unable to use the newer Azure storage SDK and I'm not sure whether I should wait for this to be fixed or go back to using the old CloudBlockBlob.

**Comment by amnguye** [comment]
I'm not able to reproduce your issue. I'm a little confused as to how you could be getting a stream issue when you call to download.

There's no changes you made to the sample before you ran it correct? (If not please provide a full snippet to help me reproduce your issue on my side).
Have you also tried changing `var` to `BlobDownloadInfo` ? Maybe some stream isn't initializing the way we expect it to, however i did change it to var as well and it's works fine.

**Comment by hultqvist** [comment]
My bad.
It was the Visual Studio that can't catch unhandled exception in ASP.NET core project.
The only solution is to catch them all which also catches the ones inside the SDK.

**For example** is is what an exception **unhandled** by the SDK looks like:
![image](https://user-images.githubusercontent.com/505330/101465546-5ca5ec00-3940-11eb-8329-bd6c17b5af4e.png)

And this is what the **handled** exception looks like:
![image](https://user-images.githubusercontent.com/505330/101465658-7fd09b80-3940-11eb-8ba5-1aedf14fcb68.png)

**Conclusion:** it's not an issue with the SDK but with Visual Studio ASP.NET Core
