### ISSUE TITLE
[FEATURE REQ][Synapse] - Improve test coverage

### ISSUE THREAD

**Issue by idear1203** [Azure/azure-sdk-for-net#17145]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
[Microsoft.Azure.Management.Synapse]
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
Currently we only have test cases for core features. We need to improve test coverage.

**Comment by pallavit** [comment]
Closing this issue as it is not being actively worked upon, please feel free to open as needed.
