### ISSUE TITLE
Improve Error Messages and comments for clearer understanding on how to construct a SAS

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#17150]
Currently when constructing a SAS or using `Client.GenerateSas(SasBuilder ..)` it is unclear on how to resolve some issues.

e.g.
- When passing the DataLakeSasBuilder to DataLakeDirectoryClient.GenerateSas(..) if the FileSystemName and Path is omitted, NullReferenceException is thrown, we should be throwing which parameters are empty and put that in an exception message that way the user know what fields should be filled. (Also if these fields are omitted, maybe we should fill these parameters for them, since they're already provided in the client)

- "SAS Uri cannot be generated. Expected builder.IsDirectory to be set to true to generate the respective SAS for the client." This error message should be something like "SAS Uri cannot be generated for DataLakeDirectoryClient. Expected DataLakeDirecotryClient.IsDirectory to be set to true to generate the respective SAS for the DataLakeDirectoryClient."

**Comment by amnguye** [comment]
Let's also improve the comment and documentations surrounding SAS (e.g. We should specify they're creating a service sas or account sas, like for CanGenerateSasUri etc)

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
