### ISSUE TITLE
[EventHubs] Re-enable suppressed warnings

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17153]
Suppressions for CA1816;CA2016 were added as part of FxCop rules update. Individual callsites need to be investigated and fixed/suppressed.

**Comment by jsquire** [comment]
@pakrym:  At a glance, these seem like they're more likely to apply to the track one projects than track two.    From your earlier work, do you happen to know if that statement is correct so that I can tag and route this appropriately?

**Comment by pakrym** [comment]
No, this is for Track 2 projects.

**Comment by jsquire** [comment]
Fixed by #17428
