### ISSUE TITLE
Event Grid - create tests for IAzureClientBuilder extensions

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#17158]
We don't currently test these in any libraries. We can start with Event Grid and then create issues for all libraries once we come up with a good pattern.

**Comment by JimSuplizio** [comment]
Hi @JoshLove-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
