### ISSUE TITLE
[Monitor] Re-enable suppressed warnings

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17155]
Suppressions for AZC0001;CS0108;CS1591 were added as part of FxCop rules update. Individual callsites need to be investigated and fixed/suppressed.

**Comment by AraHaan** [comment]
speaking of FXCop, It should be replaced with the replacement package that is suggested when trying to use the package.

**Comment by JimSuplizio** [comment]
Hi @pakrym, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
