### ISSUE TITLE
Curly braces in file names breaks coverlet (Code Coverage)

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#17164]
While testing #17067 I found an [issue in coverlet](https://github.com/coverlet-coverage/coverlet/issues/998) where curly braces in file names breaks the logger that is required for CI builds, which in turn prevents some (many, actually, including Azure.Core) assemblies from getting covered with an error message like so:

```
TpTrace Verbose: 0 : 9956, 1, 2020/11/23, 14:06:13.817, 5686906590323, datacollector.dll, [coverlet]Mapping resolved: '/_2/autorest.csharp.v3/1.0.0-alpha.20201028.2/content/Generator.Shared/ResponseWithHeaders.cs' -> 'C:\Users\heaths\.nuget\packages\autorest.csharp.v3\1.0.0-alpha.20201028.2\content\Generator.Shared\ResponseWithHeaders.cs'
```

This is evident with `/p:ContinuousIntegrationBuild=true` is passed, which is used to run the `CoverletGetPathMap` MSBuild target in that PR which in turn allows code coverage to work (without it, you can't filter out unrelated or undesirable files).

The logging method that fails is always called whether verbose logging is enabled or not: all logging methods would have this problem, but it's file source mapping method that calls `Verbose` and we need that to run. Instead, we'll have to rename files and disable SA1649 warnings for those affected files since `OfT` is [not considered a valid file name](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3250) (though it's a common pattern even used in https://github.com/dotnet/runtime).

**Comment by heaths** [comment]
To note, I was using the same commands locally (which doesn't repro this in a normal dev workflow because it has to do with source file mapping needed by the CI) except root paths changed. I also have to explicitly set `ContinuousIntegrationBuild` to `true`:

```powershell
$env:COVERLET_DATACOLLECTOR_OUTOFPROC_DEBUG=1
dotnet build-server shutdown

dotnet test eng/service.proj --filter TestCategory!=Live --framework netcoreapp2.1 --logger "trx;LogFileName=netcoreapp2.1.trx" --logger:"console;verbosity=normal" /p:ContinuousIntegrationBuild=true /p:ServiceDirectory=keyvault /p:IncludeSrc=false /p:IncludeSamples=false /p:IncludePerf=false /p:IncludeStress=false /p:Configuration=Debug  /p:CollectCoverage=true /p:CodeCoverageDirectory=keyvault /bl:C:\src\logs\msbuild.keyvault.binlog --diag:C:\src\logs\log.txt

dotnet tool run reportgenerator -reports:C:\src\azure-sdk-for-net\sdk\keyvault\**\coverage.cobertura.xml -targetdir:C:\src\azure-sdk-for-net\logs\TestResults "-reporttypes:Cobertura;Html" -sourcedirs: -historydir: -plugins: -assemblyfilters:+* -classfilters:+* -filefilters:+C:\src\azure-sdk-for-net\sdk\keyvault\** -verbosity:Verbose -title: -tag:20201120.10_#629023
```

**Comment by jsquire** [comment]
Can we please add to the scope of this issue either to restore the curly braces in the path `/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor{TPartition}.cs`  or shoot out a team email to let us know that we can use them again?

**Comment by heaths** [comment]
I will open a bug to restore them if coverlet takes my PR to fix the issue and releases a new version. But eliding the type param from the file should hopefully be effective. We have many generic classes that don't use them already. SA1649 doesn't require them.
