### ISSUE TITLE
Update DataLakeSasBuilder.IsDirectory comment to include that "sdd" parameter is populated by the SDK

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#17160]
For DataLakeSasBuilder.IsDirectory this should be updated with the comment that the "sdd" parameters is calculated based on the directory path given, and is currently not settable.

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
