### ISSUE TITLE
[BUG] EventHub doesn't receive all messages from IOTHUB

### ISSUE THREAD

**Issue by SilverBkk** [Azure/azure-sdk-for-net#17176]
**Describe the bug:**
We noticed that some messages in our IOTHUB are not read by our eventHubReceiver ( 4 partitions = 4 eventHubReceiver ). In the logs of the WebApp BackgroundWorker, some messages logged in the IOTHUB had never arrived in any of eventHubReceiver. We follow the code sample to implement a BackgroundWorker: Azure-Samples/azure-iot-samples-csharp/iot-hub/Quickstarts/read-d2c-messages/

**Expected behavior:**
We expect that every messages in IOTHUB are read and received in our eventHubReceiver.

**Actual behavior:**
As you can see in the logs below, the messages 03, 04, 06, 10, 11, 14, 16, 17, 19, 20, 23 and 25 in IOTHUB never arrive in eventHubReceiver. For a 15mn window, with a total of 27 messages, 11 messages never arrive at destination (eventHubReceiver). This is more than 40% loss! Is anyone can explain to me this huge loss of messages? What are we doing wrong? Can anyone help? Thanks in advance.

**Environment:**
Microsoft Azure Cloud (West Europe)
Azure IoT Hub resource (Tier S1 Standard - IoT Devices: 154)
Microsoft.Azure.EventHubs v4.2.0
Windows 10, .NET Core v2.1 (netcoreapp2.1)
Visual Studio 16.8.2

**D2C Reader BackgroundWorker:**

```csharp
public class D2CMessageReaderWorker : BackgroundWorkerBase, ISingletonDependency
{
	private readonly IMessageManager messageManager;
	private string eventHubsCompatibleEndpoint;
	private string eventHubsCompatiblePath;
	private string iotHubSasKey;
	private string iotHubSasKeyName;
	private readonly ISettingManager settingManager;
	private EventHubClient eventHubClient;
	private readonly CancellationTokenSource cancelToken = new CancellationTokenSource();
	private readonly List<Task> tasks = new List<Task>();
	public D2CMessageReaderWorker(IMessageManager msgManager, ISettingManager settingManager)
	{
		this.messageManager = msgManager;
		this.settingManager = settingManager;
		Logger = NullLogger.Instance;
	}
	public override async void Start()
	{
		Logger.Info($"Start D2CMessageReaderWorker: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss}");
		try
		{
			this.eventHubsCompatibleEndpoint = settingManager.GetSettingValue(AppSettings.IotHubManagement.IotHubCompatibleEndpoint);
			this.eventHubsCompatiblePath = settingManager.GetSettingValue(AppSettings.IotHubManagement.IotHubCompatiblePath);
			this.iotHubSasKey = settingManager.GetSettingValue(AppSettings.IotHubManagement.IotHubSasKey);
			this.iotHubSasKeyName = settingManager.GetSettingValue(AppSettings.IotHubManagement.IotHubSasKeyName);
		}
		catch
		{
			this.Logger.Error("The D2CMessageReaderWorker couldn't be started because parameters are missing");
		}
		if (!string.IsNullOrEmpty(this.eventHubsCompatibleEndpoint) && !string.IsNullOrEmpty(this.eventHubsCompatiblePath) && !string.IsNullOrEmpty(this.iotHubSasKey) && !string.IsNullOrEmpty(this.iotHubSasKeyName))
		{
			// Create an EventHubClient instance to connect to the IoT Hub Event Hubs - compatible endpoint.
			var connectionString = new EventHubsConnectionStringBuilder(new Uri(eventHubsCompatibleEndpoint), eventHubsCompatiblePath, iotHubSasKeyName, iotHubSasKey);
			eventHubClient = EventHubClient.CreateFromConnectionString(connectionString.ToString());
			// Create a PartitionReciever for each partition on the hub.
			var runtimeInfo = await eventHubClient.GetRuntimeInformationAsync();
			tasks.Clear();
			foreach (string partition in runtimeInfo.PartitionIds)
			{
				tasks.Add(ReceiveMessagesFromDeviceAsync(partition, cancelToken.Token));
			}
		}
		else
		{
			this.Stop();
		}
	}
	public override void Stop()
	{
		cancelToken.Cancel();
	}
	public override void WaitToStop()
	{
		Task.WaitAll(tasks.ToArray());
	}
	private async Task ReceiveMessagesFromDeviceAsync(string partition, CancellationToken token)
	{
		var eventHubReceiver = eventHubClient.CreateReceiver("$Default", partition, EventPosition.FromEnqueuedTime(DateTime.Now));
		eventHubReceiver.SetReceiveHandler(new PartitionReceiveHandler());
		while (true)
		{
			try
			{
				if (token.IsCancellationRequested)
				{
					Logger.Debug($"Stop receiving on partition {partition}: Cancellation requested!");
					break;
				}
				// Check for EventData - this methods times out if there is nothing to retrieve.
				var events = await eventHubReceiver.ReceiveAsync(10);
				// If there is data in the batch, process it.
				if (events == null)
				{
					Logger.Debug($"No message received on partition {partition}...");
					continue;
				}
				foreach (EventData eventData in events)
				{
					string data = Encoding.UTF8.GetString(eventData.Body.Array);
					string sender = eventData.SystemProperties.GetValueOrDefault("iothub-connection-device-id")?.ToString();
					// Log message received and sender
					Logger.Info($"Message from [{sender}] received on partition {partition}: {data}");
					// Handles the message
					await messageManager.HandleReceivedMessage(sender, data);
				}
			}
			catch (Exception ex)
			{
				Logger.Error($"Exception on partition {partition} from receiver {eventHubReceiver.Identifier}: {ex.GetType().Name} {ex.Message}");
			}
		}
	}
}
public class PartitionReceiveHandler : IPartitionReceiveHandler
{
	public NullLogger Logger { get;  }
	public int MaxBatchSize { get; set; }
	public PartitionReceiveHandler()
	{
		this.MaxBatchSize = 10;
		Logger = NullLogger.Instance;
	}
	public Task ProcessEventsAsync(IEnumerable<EventData> msgs)
	{
		return Task.CompletedTask;
	}
	public Task ProcessErrorAsync(Exception error)
	{
		Logger.Error($"Exception {error.GetType().Name}: {error.Message}");
		return Task.CompletedTask;
	}
}
```

**LOG from IOTHUBMONITOR:**
01. [IoTHubMonitor] [2020-11-23 07:24:54] Message received from [000666XXX1]: "S K 00\n"
02. [IoTHubMonitor] [2020-11-23 07:27:56] Message received from [000666XXX1]: "S K 00\n"
03. [IoTHubMonitor] [2020-11-23 07:29:58] Message received from [000666XXX1]: "S K 00\n"
04. [IoTHubMonitor] [2020-11-23 07:30:58] Message received from [000666XXX1]: "S K 00\n"
05. [IoTHubMonitor] [2020-11-23 07:31:59] Message received from [000666XXX1]: "S K 00\n"
06. [IoTHubMonitor] [2020-11-23 07:32:59] Message received from [000666XXX1]: "S K 00\n"
07. [IoTHubMonitor] [2020-11-23 07:34:00] Message received from [000666XXX1]: "S K 00\n"
08. [IoTHubMonitor] [2020-11-23 07:34:14] Message received from [000666XXX1]: "S U 319 ...\n"
09. [IoTHubMonitor] [2020-11-23 07:34:26] Message received from [000666XXX1]: "S U 319 ...\n"
10. [IoTHubMonitor] [2020-11-23 07:35:01] Message received from [000666XXX1]: "S K 00\n"
11. [IoTHubMonitor] [2020-11-23 07:35:04] Message received from [000666XXX1]: "G C 00\n"
12. [IoTHubMonitor] [2020-11-23 07:35:05] Message received from [000666XXX1]: "G T 02 00\n"
13. [IoTHubMonitor] [2020-11-23 07:35:12] Message received from [000666XXX1]: "S U 31B ...\n"
14. [IoTHubMonitor] [2020-11-23 07:35:48] Message received from [000666XXX1]: "B M 02 01\n"
15. [IoTHubMonitor] [2020-11-23 07:35:49] Message received from [000666XXX1]: "B 0 08 01 01 00 01\n"
16. [IoTHubMonitor] [2020-11-23 07:35:51] Message received from [000666XXX1]: "P 1 04 4B 01\n"
17. [IoTHubMonitor] [2020-11-23 07:35:58] Message received from [000666XXX1]: "B 0 08 01 01 00 00\n"
18. [IoTHubMonitor] [2020-11-23 07:35:59] Message received from [000666XXX1]: "L 0 04 80 00\n"
19. [IoTHubMonitor] [2020-11-23 07:36:01] Message received from [000666XXX1]: "S K 00\n"
20. [IoTHubMonitor] [2020-11-23 07:36:15] Message received from [000666XXX1]: "S U 31C ...\n"
21. [IoTHubMonitor] [2020-11-23 07:36:31] Message received from [000666XXX1]: "S U 31C ...\n"
22. [IoTHubMonitor] [2020-11-23 07:37:02] Message received from [000666XXX1]: "S K 00\n"
23. [IoTHubMonitor] [2020-11-23 07:37:12] Message received from [000666XXX1]: "B M 02 00\n"
24. [IoTHubMonitor] [2020-11-23 07:37:13] Message received from [000666XXX1]: "B 0 08 00 00 00 00\n"
25. [IoTHubMonitor] [2020-11-23 07:37:34] Message received from [000666XXX1]: "S U 31C ...\n"
26. [IoTHubMonitor] [2020-11-23 07:38:02] Message received from [000666XXX1]: "S K 00\n"
27. [IoTHubMonitor] [2020-11-23 07:39:03] Message received from [000666XXX1]: "S K 00\n"

**LOG from D2CMessageReaderWorker (D2CMRW):**
01. 2020-11-23 07:24:54 [65] D2CMRW - Message from [000666XXX1] received on partition 3: S K 00
02. 2020-11-23 07:27:56 [70] D2CMRW - Message from [000666XXX1] received on partition 3: S K 00
05. 2020-11-23 07:31:59 [25] D2CMRW - Message from [000666XXX1] received on partition 3: S K 00
07. 2020-11-23 07:34:00 [47] D2CMRW - Message from [000666XXX1] received on partition 3: S K 00
08. 2020-11-23 07:34:14 [70] D2CMRW - Message from [000666XXX1] received on partition 3: S U 319 ...
09. 2020-11-23 07:34:26 [70] D2CMRW - Message from [000666XXX1] received on partition 3: S U 319 ...
12. 2020-11-23 07:35:05 [68] D2CMRW - Message from [000666XXX1] received on partition 3: G T 02 00
13. 2020-11-23 07:35:12 [49] D2CMRW - Message from [000666XXX1] received on partition 3: S U 31B ...
15. 2020-11-23 07:35:49 [68] D2CMRW - Message from [000666XXX1] received on partition 3: B 0 08 01 01 00 01
18. 2020-11-23 07:35:59 [70] D2CMRW - Message from [000666XXX1] received on partition 3: L 0 04 80 00
21. 2020-11-23 07:36:31 [68] D2CMRW - Message from [000666XXX1] received on partition 3: S U 31C ...
22. 2020-11-23 07:37:02 [47] D2CMRW - Message from [000666XXX1] received on partition 3: S K 00
24. 2020-11-23 07:37:13 [51] D2CMRW - Message from [000666XXX1] received on partition 3: B 0 08 00 00 00 00
26. 2020-11-23 07:38:02 [51] D2CMRW - Message from [000666XXX1] received on partition 3: S K 00
27. 2020-11-23 07:39:03 [25] D2CMRW - Message from [000666XXX1] received on partition 3: S K 00

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by SilverBkk** [comment]
Does anyone can help?

**Comment by jsquire** [comment]
@serkantkaraca, @JamesBirdsall:  Would you folks mind offering your thoughts, please?

**Comment by serkantkaraca** [comment]
You should PartitionReceiveHandler, you don't need that. Using both PartitionReceiveHandler and the ReceiveAsync API is causing the issue your are observing.

**Comment by SilverBkk** [comment]
Thanks for your reply and the help. I understand that there is a conflict between to different ways to do the same thing.
But which one should be implemented? Which one is best to implement? PartitionReceiveHandler or ReceiveAsync API?
Thanks in advance for your support.
Best regards.

**Comment by serkantkaraca** [comment]
You should actually use neither. Client receiver and receive handler APIs are implementing connectors. 

EventProcessorHost is the correct framework for consuming event streams. Have a look at sample below and let us know if you have any questions.

https://github.com/Azure/azure-event-hubs/tree/master/samples/DotNet/Microsoft.Azure.EventHubs/SampleEphReceiver

**Comment by SilverBkk** [comment]
Thanks for your help and support.
