### ISSUE TITLE
ILogger for Azure Storage SDK

### ISSUE THREAD

**Issue by Vandersteen** [Azure/azure-sdk-for-net#17197]
**Query/Question**
How can we help?

How can one enable logging with ILogger in asp.net core for the azure storage sdk's ?

Looking at: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#aspnet-core-applications

We could use https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/extensions/Microsoft.Extensions.Azure/README.md

However we would like to use the logging part of that component only, our clients are unknown at startup time and created / configured at run time. Which is why we can't use the component as presented

**Comment by jsquire** [comment]
//cc: @pakrym, who may have insight.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by pakrym** [comment]
[Microsoft.Extensions.Azure/1.1.0-beta.1](https://www.nuget.org/packages/Microsoft.Extensions.Azure/1.1.0-beta.1) has a public type called `AzureEventSourceLogForwarder` that can be used for ILogger forwarding without registering your client in DI.


```C#
// In ConfigureServices
public void ConfigureServices(IServiceCollection services)
{
	services.AddAzureClientsCore();
}

// In Configure
public void Configure(IApplicationBuilder builder, AzureEventSourceLogForwarder forwarder)
{
	forwarder.Start();
}
```

**Comment by Vandersteen** [comment]
Thanks this works !

Do you have recommendations when to call `forwarder.Start();` in a WorkerService (IHostBuilder)

For now I started it in a HostedService OnStart override.

**Comment by pakrym** [comment]
The `HostedService.OnStart` is a good spot for it.

**Comment by Vandersteen** [comment]
Great, thank you for the quick responses
