### ISSUE TITLE
ServiceBusManagementClient CreateNamespace returns 400 Bad Request with Guid as namespace name sometimes

### ISSUE THREAD

**Issue by afdabro** [Azure/azure-sdk-for-net#1719]
The following is a bug within the Service Bus REST resource provider API:

Based on the documentation it states that it is possible to create service bus namespaces using a Guid. However, the response _sometimes_ returns a 400 Bad request. I'm using the C# Service Bus Management Client and generating a new Guid service bus namespace name per a request using the following snippet. Since the snippet is generating a new Guid per a request it is possible the RegEx for the namespace naming convention could be hitting an edge case in Guid generation.

var guidNamespace = Guid.NewGuid();

var subscriptionId = ConfigurationManager.AppSettings["subscriptionId"];

client.CreateNamespaceAsync(
                            guidNamespace.ToString(),
                            subscriptionId,
                            new ServiceBusNamespaceCreateParameters(ConfigurationManager.AppSettings["azureLocation"], NamespaceType.Messaging),
                            CancellationToken.None);

Example request over the wire:
PUT https://management.core.windows.net/{{ Subscription Id }}/services/ServiceBus/Namespaces/778254fc-e30c-4eac-af49-efd4e08dff63

<entry xmlns="http://www.w3.org/2005/Atom">
  <content type="application/atom+xml;type=entry;charset=utf-8">
    <NamespaceDescription xmlns="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect">
      <Region>East US</Region>
      <CreateACSNamespace>false</CreateACSNamespace>
      <NamespaceType>Messaging</NamespaceType>
    </NamespaceDescription>
  </content>
</entry>

Response:

400 Bad Request
<entry xmlns="http://www.w3.org/2005/Atom"><id>uuid:d6ff7308-bb12-4958-9d2d-fddaf953a193;id=11189136</id><title type="text"></title><updated>2016-01-12T15:43:38Z</updated><content type="application/xml"><Error xmlns=""><Code>400</Code><Detail>The specified service namespace is invalid.</Detail></Error></content></entry>

Reference:
https://msdn.microsoft.com/en-us/library/azure/jj856303.aspx

**Comment by jfggdl** [comment]
@afdabro Would you please check if your GUID adheres to the rules defined in https://docs.microsoft.com/en-us/rest/api/servicebus/create-namespace ?

We are closing this issue, but please feel free to reopen it if your GUID adheres to the rules.

Thanks
