### ISSUE TITLE
InstanceView property of Virtual machine object is null (other props are initiated)

### ISSUE THREAD

**Issue by UNdedss** [Azure/azure-sdk-for-net#1720]
var vm1 = _cmClient.VirtualMachines.Get(
                resourceGroupName: "ArmDeployment",
                vmName: "ArmVM"); // vm is acquired

var iv = vm1.InstanceView; // == null

**Comment by huangpf** [comment]
This is by design. For you to get the instance view, you need to call the GetInstanceView API.
