### ISSUE TITLE
The way of storage table second endpoint constructed in Azure SDK for net doesn't support use in Azurite

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-net#17215]
**Error Description:**
[Azurite](https://github.com/Azure/Azurite) is an Azure Storage emulator. 
Current storage table second endpoint which is constructed in Azure SDK for net can not access Azurite. The reason is the storage table second endpoint for Azurite is different from the one of an Azure storage account.
In Azurite, storage table second endpoint constructed is shown as following:
```
https://127.0.0.1:10002/<account-name>-secondary/<resource-path>
```
In Azure SDK for net, storage table second endpoint constructed is shown as following:
```
https://<account-name>-secondary.table.core.windows.net/<resource-path>
```

**Error Track:**
The code for storage table second endpoint constructed in Azure SDK for net is [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/src/TableServiceClient.cs#L151)
![Screenshot 2020-11-26 163623](https://user-images.githubusercontent.com/20970631/100327058-b5eb5280-3005-11eb-813e-56f9e0bb6d52.png)

**Expected Behavior**
Storage table second endpoint which is constructed in azure sdk for net can access azurite.

@jongio for notification.

**Comment by jsquire** [comment]
@christothes:  I'm not sure if this falls in the scope of the client library or should be routed to the Storage service team.   Would you mind offering your thoughts?

**Comment by christothes** [comment]
@zzhxiaofeng Please take a look at https://github.com/Azure/azure-sdk-for-net/pull/17246 and validate if this approach resolves the issue.

**Comment by pakrym** [comment]
@zzhxiaofeng is there any benefit to having a secondary endpoint for azurite? Do you see a downside to always using the primary one for the loopback

**Comment by zzhxiaofeng** [comment]
@christothes Yes, the issue has been resolved. thank you.

**Comment by zzhxiaofeng** [comment]
@pakrym I just think using a secondary endpoint for Azurite when the primary one becomes unavailable.

**Comment by v-xuto** [comment]
azsdk-azurite
