### ISSUE TITLE
Error ASPRUNTIME: Type is not resolved for member: AzureServiceTokenProviderException

### ISSUE THREAD

**Issue by rushilShetty** [Azure/azure-sdk-for-net#17216]
**Query/Question**
I have an aspnet project which builds fine locally, but on Azure DevOps I get this error. We use our own build agent. I installed Visual studio on it and built and it's fine. But when I use it with MSbuild.exe, I get this error.

> ##[error]ASPNETCOMPILER(0,0): Error ASPRUNTIME: Type is not resolved for member 'Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException,Microsoft.Azure.Services.AppAuthentication, Version=1.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

I don't have /p:PrecompileBeforePublish parameter any where in our project. Even then I provided it /p:PrecompileBeforePublish=false, but it still doesn't seem to work. Would you know perhaps any other reason?

**MSBuild command**
> C:\Windows\Microsoft.NET\Framework\v4.0.30319\aspnet_compiler.exe -v /MyProject -p MyProject\ -u -f PrecompiledWeb\MyProject\

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Services.AppAuthentication - 1.4.0.0
 - Hosting platform or OS and .NET runtime version: .Net 4.7.1 - Windows 10
 - IDE and version : MSBuild 16.8.2.56705

**Related issue**
#4370

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by rushilShetty** [comment]
I tried this with Azure DevOps hosted agent (windows VM image) and the problem still occurs. It's not the same error but I think it's related. So doesn't necessarily seem like related to the build machine itself.

> ##[error]src\ElsyArres.API.v821\web.config(13,0): Error ASPCONFIG: The configBuilder 'AzureKeyVault' failed during Initialization.: Could not load file or assembly 'Microsoft.Azure.Services.AppAuthentication, Version=1.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified

**Comment by YalinLi0312** [comment]
@markcowl Can you take a look if it is a potential issue to fix?

**Comment by stefan-komierowski** [comment]
Hi, I have the same issue. Works with visual studio but not when I try to deploy it with teamcity:
[AspNetCompiler] ASPNETCOMPILER error ASPRUNTIME: Type is not resolved for member 'Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException,Microsoft.Azure.Services.AppAuthentication, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by kitestefan** [comment]
I have solved it now after many tries.
This is the steps I had to do to be able to run msbuild in TeamCity with BuildMVCViews = true

In the Views folder in the project, there is a web.config. (Observe that its not the web.config in the root Im talking about. Its the web.config in the Views folder) There I have put one line:
<add assembly="Microsoft.Azure.Services.AppAuthentication, Version=1.6.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />

in the section  <system.web>    <compilation>      <assemblies>

Then on the build agent where msbuild is run I have put in the computers system environment variable following:
Variable name: AzureServicesAuthConnectionString
Variable value: RunAs=App;AppId=yourappid;TenantId=yourtenantid;AppKey=yourappsecretkey

Hope this will help anyone else with same issues.

**Comment by rushilShetty** [comment]
@kitestefan Thanks. Going to try that out and see, I hope it works for me too.

**Comment by kitestefan** [comment]
> @kitestefan Thanks. Going to try that out and see, I hope it works for me too.

Ok, please let me know if it worked for you as well or not.

**Comment by rushilShetty** [comment]
@kitestefan Yes this worked for me. Thanks a ton! 👍 

I had to do few extra things to make it work.
- Create a new app registration in Azure AD.
- Create a client secret for that newly created app.
- Set the environment variable as @kitestefan mentioned with the app id and app secret key.

Hope this helps others.

**Comment by littlecharva** [comment]
I also have this issue, and I think the suggestions above are a work-around, not a solution.  I get the following error when deploying using msbuild:

`ASPNETCOMPILER : error ASPRUNTIME: Type is not resolved for member 'Azure.Identity.CredentialUnavailableException,Azure.Identity, Version=1.4.0.0, Culture=neutral, PublicKeyToken=92742159e1
2e44c8`

Which is being caused by the references to AzureKeyVault in my web.config.  If I remove the configBuilders sections, then it builds fine.

There should be no need for msbuild to authenticate with the AzureKeyVault when building this app.  If I build and deploy the app with the configBuilder sections missing from the web.config file, then I add those sections back in using FTP, the whole thing builds and deploys correctly, and runs correctly.  Why is msbuild failing?

**Comment by psskalyan** [comment]
@littlecharva : Whats the outcome for you, i also see same exception while using msbuild, even when tried with workaround's mentioned above.

**Comment by tafs7** [comment]
@rushilShetty, IMO this is still a bug (though you fixed with a workaround) so this issue should be reopened for visibility.

I agree with @littlecharva - there should not be a need to authenticate to Az KV during a build.

**Comment by spowser** [comment]
I have an open ticket with the IIS /ASP.NET team on the same error @littlecharva is seeing.  No resolution yet but I will post any updates I get here.

**Comment by tegrit-joe-trupiano** [comment]
> I have an open ticket with the IIS /ASP.NET team on the same error @littlecharva is seeing. No resolution yet but I will post any updates I get here.

Did you get any updates I just ran into the same issue using devops/msbuild?

ASPNETCOMPILER(0,0): Error ASPRUNTIME: Type is not resolved for member 'Azure.Identity.CredentialUnavailableException,Azure.Identity, Version=1.5.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'. 
Process 'msbuild.exe' exited with code '1'.

**Comment by mkieloch-352** [comment]
I am also experiencing this issue in Azure devops. @rushilShetty did you set the variable name in the Azure devops variables or in the YAML pipeline as part of the msbuild args? Can you provide an example?
