### ISSUE TITLE
[Perf, Stress] Add Doc Comments

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#17217]
# Summary

None of the types or members of the performance and stress frameworks are decorated with the standard .NET XML doc comments, rendering editors unable to provide information and context while working with the frameworks.  It would greatly improve the developer experience working with the frameworks to have documentation available via code-completion, tooltips, and by viewing type definitions.

# Scope of Work

- Add document comments for the public types and members in the performance and stress frameworks detailing the usage, parameters, and potential "gotchas" of using them, as well as discussing semantics around topics such as ownership and lifespan where they apply.

- Consider adding document comments to the non-public types and members as well; as an open-source project that both team members and our community may contribute to, understanding the implementation details is important.

- Consider adding an embedded samples, where they would help to add clarity.

# Success Criteria

- The document comments detailed by the scope for public members have been added, reviewed, and are in a good state of polish to provide value to developers using the frameworks.

- A decision has been made regarding document comments for non-public members;  if accepted into the scope, the comments added, reviewed, and are in a good state of polish to provide value to contributors to the frameworks.

**Comment by JimSuplizio** [comment]
Hi @jsquire, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
