### ISSUE TITLE
[Service Bus] Add a possibility to update an already created subscription rule description

### ISSUE THREAD

**Issue by zive7** [Azure/azure-sdk-for-net#17229]
[SubscriptionClient](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/SubscriptionClient.cs) class does not support update on an already created rule subscription identifier.

Shall we extend this client with a new method named UpdateRuleAsync(string ruleName, RuleDescription description) which will perform updates on specific rule internally?

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@zive7  I'd recommend deleting the old subscription and creating a new one with the same name.

Any reason that does not work?

**Comment by axisc** [comment]
@zive7 closing this for now, please do let us know if there are any questions.

**Comment by zive7** [comment]
@axisc Sorry for the late reply. I've developed like that, but I think that recreating the subscription is not a good idea. With this solution, there is a possibility some of the events not being handled at all.
