### ISSUE TITLE
[FEATURE REQ] Support listing blobs from name or continuation token

### ISSUE THREAD

**Issue by fernacolo** [Azure/azure-sdk-for-net#17222]
**Library or service name.**

Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**

We have an application that lists and processes a huge number of blobs. The processing takes ~16 hours to complete, but it needs to finish within 24h otherwise an underrun situation happens. Sometimes the application is deployed, rebooted or it restarts for whatever reason. In order to avoid restarting the entire procedure, the application stores the blob continuation token on persistent media. When it restarts and detects an unfinished processing, it lists the blobs using the persisted blob continuation token and that allows working only un unprocessed blobs instead of the entire dataset.

This works well in `WindowsAzure.Storage` 9.3, which provides the `CloudBlobContainer.ListBlobsSegmentedAsync` method that takes the blob continuation token and exposes a single page on every call.

However the `Azure.Storage.Blobs` package only provides `BlobContainerClient.GetBlobsAsync`, and that neither exposes the blob continuation token, nor it provides a way of listing blobs starting from an specific blob name or marker.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @fernacolo, here is an example of how to list blobs by page:

```
using Azure;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;
using System;
using System.Threading.Tasks;

namespace ConsoleApp10
{
    class Program
    {
        static async Task Main(string[] args)
        {
            string connectionString = "";
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient("mycontainer3423428");
            try
            {
                await containerClient.CreateAsync();
                await CreateBlobs(containerClient, 15);

                await foreach (Page<BlobItem> page in containerClient.GetBlobsAsync().AsPages(pageSizeHint: 5))
                {
                    Console.WriteLine("New Page");
                    foreach(BlobItem blobItem in page.Values)
                    {
                        Console.WriteLine(blobItem.Name);
                    }
                }
            }
            finally
            {
                await containerClient.DeleteAsync();
            }
        }

        static async Task CreateBlobs(BlobContainerClient containerClient, int blobCount)
        {
            for (int i = 0; i < blobCount; i++)
            {
                AppendBlobClient appendBlobClient = containerClient.GetAppendBlobClient($"blob{i}");
                await appendBlobClient.CreateAsync();
            }
        }
    }
}
```

You can also break up the foreach loop, and manually save `page.ContinuationToken`, store it, and re-use it later with `containerClient.GetBlobsAsync().AsPages(continuationToken, pageSize)`.

Please re-open if you have further questions.

-Sean
