### ISSUE TITLE
[Synapse] Deploy test resources step failing on nightly tests 

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-for-net#17237]
Builds such as [this](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=636184&view=logs&j=78d7b60f-679d-537e-e1b0-533d8dbc7bcc&t=5cafe072-2e58-54df-eea8-d035fe317e27) are failing with:

Name 'sparkt499f98df8c4d4f46' is invalid. The name must be at 
 | most 15 characters long and must contain only alphanumeric 

Discussions suggest there is a test-resources.json file that needs updating with a shorter name.

**Comment by jsquire** [comment]
Following-up on the Teams conversation,  I'll add the pedantic issue stuff here.  :smile:

For work-item issues, we're asked to add an estimate, milestone, and (if possible) assign to an epic.     If this is work that isn't scheduled, adding to the "Backlog" milestone is a good place to park, and allows you to defer estimating.

**Comment by tg-msft** [comment]
This was discussed internally at one point and the suggestion was to use https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/template-functions-string?tabs=json#take to trim the random name down to the right number of characters for a spark job.
