### ISSUE TITLE
[BUG] EventHubConsumerClient properties are not mockable

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17233]
ConsumerGroup, EventHubName, FullyQualifiedNamespace, IsClosed.

Haven't found any mentions in https://github.com/Azure/azure-sdk-for-net/issues/9117

**Comment by jsquire** [comment]
These are not something that we'd set using the model factory.

The first three are properties of the consumer itself, derived from either the connection string or the items used for creation.   They can be set during construction, either directly or from the connection string.

`IsClosed` represents the state of the object and can be set by calling `CloseAsync` after creating the client.   It does not require opening the connection to the service to do do.

**Comment by pakrym** [comment]
Interesting. Am I correct in understanding that there would be no network IO until some async client method is called?

**Comment by jsquire** [comment]
> Am I correct in understanding that there would be no network IO until some async client method is called?

Correct;  the connection to the service is not made until the first service operation is invoked.   If you create the client and close it, there's no network communication taking place.

**Comment by jsquire** [comment]
If you wanted more control, you could also mock out the `EventHubConnection` and call [this](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Consumer/EventHubConsumerClient.cs#L284) overload.
