### ISSUE TITLE
[macOS] Recorded Synapse tests crash test runner on macOS 

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-for-net#17239]
While running this command (with ? filled to valid bits):

`SYNAPSE_AZURE_STORAGE_FILE_SYSTEM_NAME=? SYNAPSE_AZURE_STORAGE_ACCOUNT_NAME=? SYNAPSE_AZURE_SYNAPSE_SPARK_POOL_NAME=? AZURE_SYNAPSE_WORKSPACE_URL=? TENANT_ID=? CLIENT_SECRET=? CLIENT_ID=? AZURE_TEST_MODE=Live dotnet test --filter SubmitSparkJobSync`

I fail on macOS with:
```
The active test run was aborted. Reason: Test host process crashed
Test Run Aborted.
Test run for /Users/donblas/Programming/azure-sdk-for-net/artifacts/bin/Azure.Analytics.Synapse.Spark.Tests/Debug/net5.0/Azure.Analytics.Synapse.Spark.Tests.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
The active test run was aborted. Reason: Test host process crashed
```

[Crash log](https://gist.github.com/chamons/33f47065995a27d1d802ae1a186db003)

But the same setup works on Windows (matching env variables, etc).

Someone needs to look at why the tests can't be run in live mode locally. 

The nightly builds are currently failing due to https://github.com/Azure/azure-sdk-for-net/issues/17237, so we don't know if this is a local configuration issue on my end or a deeper issue (normal CI is only running playback).

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @christothes

**Comment by jsquire** [comment]
Not quite sure who is best to route this to, but you folks have all been active in parts of the Azure.Core Test Framework.   Would one of you mind triaging?
