### ISSUE TITLE
[Perf] Investigate adding a per-operation setup/cleanup methods excluded from timing

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#17248]
Some tests may want to have per-operation setup and/or cleanup methods that should be excluded from timing.  An example would be an "append blob" test which wants to append X bytes to a file with original size Y bytes.  Ideally, the test could create the blob with size Y in the per-operation setup and have this excluded from timing, and only measure the time of the "append" operation.

Currently, there is no easy way to do this.  A few options in the current framework:

1. Append to the same blob in a loop, and hope that the server processing time does not increase as the blob grows.
2. Create and append inside `Run()`, then write another test which just does "create", and subtract the results to find the perf of just "append".
3. Create many files in `Setup()`, then append to them in sequence inside `Run()`.  Might make `Setup()` very slow, and requires a parameter specifying the number of files to create in advance.

The main question is whether per-operation setup/cleanup methods would add too much overhead and/or require a timer with higher precision than is available.

**Comment by JoshLove-msft** [comment]
This would be useful for ServiceBus perf tests when we want to receive messages. Otherwise, we have to guess how many invocations of the Run method can occur within the duration.

**Comment by JimSuplizio** [comment]
Hi @mikeharder, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
