### ISSUE TITLE
Include sample for using spatial converts for FieldBuilder

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#17240]
The READMEs https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.Core.Spatial_1.0.0-beta.1/sdk/core/Microsoft.Azure.Core.Spatial/README.md and https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.Core.Spatial.NewtonsoftJson_1.0.0-beta.1/sdk/core/Microsoft.Azure.Core.Spatial.NewtonsoftJson/README.md already include samples for Cognitive Search using Microsoft.Spatial converters, but do not include a sample for how to specify them for FieldBuilder which, given customer feedback, would be worth-while (i.e. creating an index that matches the example query).

**Comment by heaths** [comment]
@Mohit-Chakraborty were you already planning something like this - to at least reference the samples I wrote for the spatial migration packages (already in their READMEs)?

**Comment by Mohit-Chakraborty** [comment]
Not yet. I am new to this issue.

**Comment by heaths** [comment]
Per offline discussion, we were talking about the camelCase sample which I used in these spatial samples, so that might've been the correlation of which I was thinking. For this issue, the setup would be about the same as https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Microsoft.Azure.Core.Spatial/README.md, which we could link to for more information, but then use in FieldBuilder.

**Comment by pallavit** [comment]
Given where we are with search - closing this issue as not planned.
