### ISSUE TITLE
ManagementClient.ManagementCertificates.Create throws on HttpStatusCode.Created response

### ISSUE THREAD

**Issue by hashtagchris** [Azure/azure-sdk-for-net#1725]
Adding a management certificate to Azure returns 201 Created. ManagementCertificateOperations.CreateAsync throws an exception if the response is something other than 200 OK.

**Comment by markcowl** [comment]
@singhkay This is in the service management library, can you take a look?

**Comment by adrianhall** [comment]
Is this still an issue?  If so, can you please provide the .NET library and version being used?
(Close on Oct 9 if no response)

**Comment by hashtagchris** [comment]
Looks like the issue has been fixed, I'm no longer able to reproduce it. When I filed this issue, we were using version 4.1.1 of the [Microsoft.WindowsAzure.Management package](https://www.nuget.org/packages/Microsoft.WindowsAzure.Management/). We've since updated to  version 4.1.3. Thanks!
