### ISSUE TITLE
Azure.Messaging.EventGrid.EventGridPublisherClient and tcp connection management

### ISSUE THREAD

**Issue by mathieuisabel** [Azure/azure-sdk-for-net#17258]
Hi,

Are there best practices to follow in regards to EventGridPublisherClient and connection management? i.e. Is is possible to use it as a singleton or it's safer to instantiate each time events should be published?

I'm asking as with the 3.2.x client seems to be causing socket exhaustion when used in an Aazure Function app. I just want to make sure I use the new client correctly.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @mathieuisabel, you can use the client as a singleton. In fact that is the recommendation across our Azure SDK libraries. You may want to read this [recent blog post](https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/) on this very subject.

**Comment by JoshLove-msft** [comment]
I will close this issue out. @mathieuisabel feel free to reopen if you have any other questions.

**Comment by mathieuisabel** [comment]
Thank you @JoshLove-msft, that did answer the question!
