### ISSUE TITLE
Azure Tables client library: why is there no example of authenticating using Managed Identity?

### ISSUE THREAD

**Issue by patrickjlee** [Azure/azure-sdk-for-net#17256]
I thought a major benefit of the new libraries using Azure.Core was that there would be more standardisation in the ways of accessing Azure resources securely. 
Other libraries (e.g. for Key Vault or Azure Storage Blobs or Queues) allow one to use Managed Identity e.g. using DefaultAzureCredential(), but apparently not in the Azure Tables library.  If not, why not and will this be introduced soon?

A major issue for us with Managed Identity has been the lack of a consistent approach across various Azure resources, so it would be good if Azure Tables also supported the same approach as Key Vault, and Azure Storage Blobs/Queues please.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
@patrickjlee Currently the service doesn't support Azure AD authentication. If you'd like to provide this feedback to the team that would need to implement this, please file an issue here https://feedback.azure.com/forums/263030-azure-cosmos-db .
