### ISSUE TITLE
[BUG] DataLakeDirectoryClient  GetFileClient(LoadFileName).ReadAsync() Doesn't implement IDisposable

### ISSUE THREAD

**Issue by lawrencegripper** [Azure/azure-sdk-for-net#17254]
**Describe the bug**
When calling `ReadAsync` an object is returned which contains a `stream` representing the file content. The object which contains the stream isn't disposable but a stream is disposable. 

My expectation is that the returned object should be disposable to highlight that a `using` statement should be in place to cleanup the stream when you are finished with it.

```
            Response<FileDownloadInfo> fileInfo = await _batchDirectory.GetFileClient(LoadFileName).ReadAsync(); // Should this return a disposable?
            Stream content = fileInfo.Value.Content; // The stream it contains is disposable
            using (StreamReader reader = new StreamReader(content, detectEncodingFromByteOrderMarks: true))
            {
                // do stuff here with the stream. 
            } 
```

Apologies if I'm doing something silly here I've been out of dotnet for a little bit so there maybe something I'm missing which mitigates this issue.

**Expected behavior**

Returned type implements `IDisposable` to cleanup stream. 

**Actual behavior (include Exception or Stack Trace)**
The response isn't disposable

**To Reproduce**

1. Use `ReadAsync` to access a file
2. Observe response contains disposable objects but isn't disposable

**Environment:**
 - Name and version of the Library package used: "Azure.Storage.Files.DataLake" Version="12.5.0"
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):

```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.401
 Commit:    39d17847db

Runtime Environment:
 OS Name:     debian
 OS Version:  10
 OS Platform: Linux
 RID:         debian.10-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.401/

Host (useful for support):
  Version: 3.1.7
  Commit:  fcfdef8d6b

.NET Core SDKs installed:
  3.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : VSCode

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by jsquire** [comment]
//fyi: @pakrym

**Comment by lawrencegripper** [comment]
Any feedback on this one?

I found another case where something seems like it wraps a disposable type but itself isn't disposable. 

```c#
        public async Task<IDictionary<string, string>> GetMetadataAsync()
        {
            Response<PathProperties> props = await _directory.GetPropertiesAsync();

            // THIS CALL HERE .... under props is raw response which is disposable, shouldn't props be disposable?
            props.GetRawResponse().Dispose();
            
            return props.Value.Metadata
                .Where(x => x.Key.StartsWith("something"));
        }
```

**Comment by KrzysztofCwalina** [comment]
The problem is that a huge majority (99.9%+) of Response<T> objects do not contain any resources that need to be disposed. If we made Response<T> IDisposable, it would push users to dispose these instances, for no good reason. We would prefer to solve the problem highlighted in this issue with analyzers that alert the users to these few cases where Response<T> streams need to be disposed. I think @pakrym has been working on an analyzer for this.

**Comment by AlexGhiondea** [comment]
@tg-msft @pakrym any updates on this?

**Comment by tg-msft** [comment]
We're not going to make `Response<T>` implement `IDisposable`, but we should make the model type

```C#
public class FileDownloadInfo { ...  }
```

implement `IDisposable` so that DataLake `Read` matches Blob `DownloadStreaming`

```C#
public class BlobDownloadStreamingResult : IDisposable { ... }
```

This will make it possible for an analyzer per https://github.com/Azure/azure-sdk-tools/issues/1798 to warn about it.

**Comment by JimSuplizio** [comment]
Hi @lawrencegripper, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
