### ISSUE TITLE
Update Microsoft.Extensions.Configuration.AzureAppConfiguration to Azure.Extensions

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#17265]
**Library or service name.**
AppConfiguration
 
**Is your feature request related to a problem? Please describe.**

To be consistent with the rest of the extensions, we should update Microsoft.Extensions.Configuration.AzureAppConfiguration to Azure.Extensions

**Comment by jongio** [comment]
Also update this doc when ready: https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-aspnet-core-app?tabs=core3x

**Comment by pakrym** [comment]
Microsoft.Extensions.Configuration.AzureAppConfiguration is already based on track 2 client.

**Comment by jongio** [comment]
Should we keep this open to move to the new namespace?

**Comment by pakrym** [comment]
I don't think it's worth the break. The extension has a lot of existing customers
