### ISSUE TITLE
Replace all NoWarn compiler options with WarningsNotAsError

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#17269]
This will allow warnings to surface without breaking CI

**Comment by pallavit** [comment]
@christothes Just to make sure I understand this issue you want us to move to WarningsNotAsError instead of NoWarn so we are aware of the gaps and not be completely blindsided or is there any other motivation of this change?

**Comment by christothes** [comment]
I don't recall the motivation behind this one, so I'll go ahead and close it since it's been a couple years.
