### ISSUE TITLE
Restore curly braces in files after updating to new coverlet

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#17270]
Now with coverlet-coverage/coverlet#1000 merged, once 3.0 is released and we update to it, we could probably go back and restore `OfT` -> `{T}` in file names that need it (I removed it from those that don't) and remove the corresponding `#pragma`s for disabling SA1649.

**Comment by pallavit** [comment]
@heaths could you please help me understand the scenario here?

**Comment by heaths** [comment]
We use coverlet to generate reports, but it couldn't handle curly braces in the file name. To work around it, I took the same approach .NET itself did and changed "{T}" to "OfT". This was a tracking issue to restore it, though I don't see much point. People have been repeating this "OfT" pattern just fine since.
