### ISSUE TITLE
Inexplicable Warnings Readme Updates on Readme Updates

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-net#17274]
@maririos raised a good question on [this doc pr](https://github.com/Azure/azure-docs-sdk-dotnet/pull/1691). We're used to a few warnings on the doc build, but this one is throwing a bunch of new warnings that I do NOT expect. 

Filing this issue so I can remember to engage with the docs team.

**Comment by jsquire** [comment]
@scbedd, @JimSuplizio:  Please advise whether this is still relevant - the linked PR is nearly 3 years old.   If not, I'd like to close it out.

**Comment by JimSuplizio** [comment]
> @scbedd, @JimSuplizio: Please advise whether this is still relevant - the linked PR is nearly 3 years old. If not, I'd like to close it out.

I don't know why I was at mentioned here, @danieljurek is the best person to weigh in on this one.

**Comment by danieljurek** [comment]
Closing. The docs team follows up with warnings that are of concern.
