### ISSUE TITLE
[BUG]  #17067 Broke MGMT track 2 pipelines

### ISSUE THREAD

**Issue by bquantump** [Azure/azure-sdk-for-net#17286]
https://github.com/Azure/azure-sdk-for-net/pull/17067 Broke All track 2 MGMT plane pipelines. 

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=638376&view=results

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=638383&view=results

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=638383&view=results

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=638383&view=results

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=638396&view=results

**Comment by heaths** [comment]
Seems since mgmt-only directories (mgmt plane is excluded currently) don't generate reports, the report generator fails.
