### ISSUE TITLE
Avro Serializer Very Slow

### ISSUE THREAD

**Issue by LarryF813** [Azure/azure-sdk-for-net#17284]
**Issue**
When serializing a test object with both the Avro serializer and JSON serializer I found a huge difference in performance. The JSON serializer serialized 2,000,000 (2M) objects in about 36 seconds while the Avro serializer only serialized 100 objects in 45 seconds. That makes it really unusable for processing large amounts of data.

![image](https://user-images.githubusercontent.com/74378706/100929648-f50e1d80-34b5-11eb-9c14-84b4243bb5fa.png)

**Code Example**
**Note:** The serialization methods below are getting a schema defined in Azure and assigning it to the Schema property of the test object. However, the test object also provides the same schema as a hard coded string. The code fetching the schema can be removed. It does not make any applicable difference in performance.

`
       internal void TestSchema()
        {
            var avroCount = 100;
            var jsonCount = 2000000;
            var bytes = AvroSerialize(avroCount);
            bytes = JsonSerialize(jsonCount);
        }

       private byte[] AvroSerialize(int max)
        {
            var randomGenerator = new Random();
            var schemaClient = GetSchemaRegistryClient();
            var s = schemaClient.GetSchema("MY_SCHEMA_GUID_HERE");
            var schema = Avro.Schema.Parse(s.Value.Content);
            byte[] bytes;
            var start = DateTime.Now;
            using (var memoryStream = new MemoryStream())
            {
                var serializer = new SchemaRegistryAvroObjectSerializer(schemaClient, "TestDataSchema", new SchemaRegistryAvroObjectSerializerOptions { AutoRegisterSchemas = true });
                for (var id = 1; id <= max; id++)
                {
                    var person = new Person() { PersonId = id, PersonName = $"SomeName{id}", PersonDate = DateTime.Now, Schema = schema };
                    serializer.Serialize(memoryStream, person, typeof(Person), CancellationToken.None);
                }
                bytes = memoryStream.ToArray();
            }
            var finish = DateTime.Now;
            var elapsed = finish - start;
            Console.WriteLine($"Avro serialized {max} Person objects in {elapsed}");
            return bytes;
        }

        private byte[] JsonSerialize(int max)
        {
            var randomGenerator = new Random();
            var schemaClient = GetSchemaRegistryClient();
            var s = schemaClient.GetSchema("MY_SCHEMA_GUID_HERE");
            var schema = Avro.Schema.Parse(s.Value.Content);
            byte[] bytes;
            var start = DateTime.Now;
            using (var memoryStream = new MemoryStream())
            {
                using (var sw = new StreamWriter(memoryStream, new UTF8Encoding(false), 1024, leaveOpen: true))
                {
                    for (var id = 1; id <= max; id++)
                    {
                        var person = new Person() { PersonId = id, PersonName = $"SomeName{id}", PersonDate = DateTime.Now, Schema = schema };
                        var serialized = JsonConvert.SerializeObject(person);
                        sw.Write(serialized);
                        sw.Flush();
                    }
                }
                bytes = memoryStream.ToArray();
                var finish = DateTime.Now;
                var elapsed = finish - start;
                Console.WriteLine($"JSON serialized {max} Person objects in {elapsed}");
            }
            return bytes;
        }

    public class Person : ISpecificRecord
    {
        public static Schema _SCHEMA = Avro.Schema.Parse(@{\"type\":\"record\",\"name\":\"Person\",\"namespace\":\"DataWriterDriver\",\"fields\":[{\"name\":\"PersonId\",\"type\":\"int\"},{\"name\":\"PersonName\",\"type\":\"string\"},
{\"name\":\"PersonDate\",\"type\":\"long\",\"logicalType\":\"local-timestamp-millis\"}]}");
        public int PersonId { get; set; }

        public string PersonName { get; set; }

        public DateTime PersonDate { get; set; }

        public Schema Schema { get; set; }

        public Person()
        {
            Schema = _SCHEMA;
        }

        public object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return PersonId;
                case 1: return PersonName;
                case2:
                    var offset = new DateTimeOffset(PersonDate);
                    return offset.ToUnixTimeMilliseconds();
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            };
        }

        public void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0: PersonId = (int)fieldValue; break;
                case 1: PersonName = (string)fieldValue; break;
                case 2:
                    if (fieldValue is long unixTicks)
                    {
                        PersonDate = DateTimeOffset.FromUnixTimeMilliseconds(unixTicks).DateTime;
                    }
                    break;
                default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            };
        }

        public override string ToString()
        {
            return $"PersonID:{PersonId} PersonName:{PersonName} PersonDate:{PersonDate}";
        }
    }
`
**Environment:**
Azure.Data.SchemaRegistry.ApacheAvro --version 1.0.0-beta.2
WIndows 10 .NET Core 3.1
Visual Studio 16.7.5

**Comment by jsquire** [comment]
Hi @LarryF813.  Thank you for your feedback.  The SchemaRegistry library and its serializer integrations are still in a very early beta state.  The poor performance with Avro is something that we expect in its current form, as this is an interim implementation that relies on a reflection-based wrapper around the Apache Avro library.  This is not the final approach that we're planning on for the long-term;  As we move into further betas and arrive at a better design for Avro serialization, performance is something that we'll be looking at as a critical measure and will be working to tune.

**Comment by jsquire** [comment]
//fyi:  @AlexGhiondea, @KrzysztofCwalina

**Comment by LarryF813** [comment]
Is there an ETA on when the performance improvement will occur in order to make this useful for processing large amounts of data?

**Comment by jsquire** [comment]
Unfortunately, there's no definitive roadmap that I'm able to share at this point; the earliest that a new beta would be released is February, but it is unlikely that would offer a new Avro Serializer with large performance differences.

**Comment by jkmbowachas** [comment]
Avro serializer is still very slow I'm running a simple integration test where deserializing takes 12 seconds.

**Comment by JoshLove-msft** [comment]
Hi @jkmbowachas, 
Can you let us know what version you are using?

@LarryF813,
The version that you were using did not have caching of schema Ids, so each serialize call would need to talk to the service to look up the schema ID. The current [beta](https://www.nuget.org/packages/Microsoft.Azure.Data.SchemaRegistry.ApacheAvro/1.0.0-beta.5), has caching along with some fundamental changes to the API.

**Comment by jkmbowachas** [comment]
I'm using version Microsoft.Azure.Data.SchemaRegistry.ApacheAvro 1.0.0-beta.4

**Comment by JoshLove-msft** [comment]
> I'm using version Microsoft.Azure.Data.SchemaRegistry.ApacheAvro 1.0.0-beta.4

Can you provide a code snippet? The first deserialization is expected to take longer as it would need to go to the service to look up the schema.

**Comment by JoshLove-msft** [comment]
@LarryF813, @jkmbowachas, out of curiosity are you integrating the Avro serializer with Event Hubs?

**Comment by jkmbowachas** [comment]
@JoshLove-msft this is one of the solutions I am testing. Is this recommended? Also I was wondering the thought process behind attaching schema registry to event hubs if you don't mind me asking?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft this is one of the solutions I am testing. Is this recommended? Also I was wondering the thought process behind attaching schema registry to event hubs if you don't mind me asking?

Yes, it is designed to be used with Event Hubs - I was just curious 😄 

In terms of including it under the Event Hubs umbrella, I'll defer to @hmlam for that question.
