### ISSUE TITLE
Fix behavior where unmapped types are transformed to BinaryData

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#17298]
Because the GetData method returns an `object`, and we return `BinaryData` if the type is unmapped, we could end up in a scenario where a model goes from being returned as `BinaryData` to a rich model type, when the model gets mapped as a system event in an SDK update.

**Comment by JoshLove-msft** [comment]
Thinking about this more, I would expect that if someone would wanted to use a system event type before the SDK update was released, they would use the GetData<T> method and pass in the type, as opposed to using GetData, so there code would continue to work even after updating to a new SDK version. There wouldn't really be any value in using GetData only to then call ToObjectFromJson<T> on the BinaryData instance.

**Comment by lmazuel** [comment]
I'm not sure I understand your last paragraph :(. But yes what we want to avoid, is that adding a new system event creates a breaking change and forces us to update the major version. If you believe the current design works fine for C#, I'm all for it.

For the sake of it, coud you write a code block with what you mean maybe?

**Comment by JoshLove-msft** [comment]
So this first snippet, will continue to work after a hypothetical event Type is mapped as a system event in a new version of the SDK:
```cs
        foreach (var evt in events)
        {
            switch (evt.EventType) 
            {
                case "SomeCustomSystemData":
                    // this will continue to work after upgrade, though customers would likely want to use the model type from the SDK rather
                    // than their custom type
                    SomeCustomSystemData systemData = evt.GetData<SomeCustomSystemData>();
                    break;
                default: 
                    ...
            }
        }
```

This code snippet would break:
```cs
        foreach (var evt in events)
        {
            switch (evt.GetData()) 
            {
                // this will never be hit as the SDK doesn't know about the user's custom type
                case SomeCustomSystemData systemData:
                    ...
                case BinaryData binaryData:
                    // this branch will not be hit for this event type once the customer upgrades to the new version of the SDK
                    // as it will be explicitly mapped to the new type
                    SomeCustomSystemData systemData = binaryData.ToObjectFromJson<SomeCustomSystemData>();
            }
        }
```

**Comment by JoshLove-msft** [comment]
We could avoid the second scenario by making GetData always return BinaryData, and introducing a new `AsSystemData` method that will only return currently mapped system events:
```cs
        foreach (var evt in events)
        {
            switch (evt.AsSystemData()) 
            {
                // not a system type
                case null:
                // this will never be hit as the SDK doesn't know about the user's custom type
                case SomeCustomSystemData systemData:
                    ...
            }
        }
```

**Comment by lmazuel** [comment]
I find the `AsSystemData` ok, don't you? Do we want to check this particular design with KC?

**Comment by YijunXieMS** [comment]
I like the idea of `AsSystemData`. For naming, "SystemData" sounds a new term to the user. We already have the concept of "system events", so maybe `AsSystemEventData` or `GetSystemEventData` is a better name?

**Comment by JoshLove-msft** [comment]
I didn't like GetSystem... because it feels more like every event may actually have both system data and regular data.

**Comment by ellismg** [comment]
FWIW, I think this `AsSystemEventData` idea is great.

**Comment by JoshLove-msft** [comment]
> FWIW, I think this `AsSystemEventData` idea is great.

I think this naming was actually suggested by @KrzysztofCwalina a while back. @KrzysztofCwalina, are you okay with the proposal described here:
- Update GetData to return BinaryData instead of object
- Add AsSystemEventData which will attempt to deserialize to one of the known system event types based on the EventType property. If not a system event, it will return null.
- `GetData<T>` will continue to work the same way meaning that it can be used for known system events or custom events.

**Comment by KrzysztofCwalina** [comment]
I like the plan.

**Comment by JoshLove-msft** [comment]
Using IsSystemEvent:

```cs
            foreach (var evt in events)
            {
                if (evt.IsSystemEvent)
                {
                    switch (evt.AsSystemData())
                    {
                        // this will never be hit as the SDK doesn't know about the user's custom type
                        case SomeCustomSystemData systemData:
                        ...
                    }
                }
            }
```

**Comment by JoshLove-msft** [comment]
Another option using TryGet pattern:
```cs
            foreach (var evt in events)
            {
                if (evt.TryGetSystemData(out object data)
                {
                    switch (data)
                    {
                        // this will never be hit as the SDK doesn't know about the user's custom type
                        case SomeCustomSystemData systemData:
                        ...
                    }
                }
            }
```
