### ISSUE TITLE
[FEATURE REQ] Provide overloads of Blob DownloadTo and DownloadToAsync that include an HttpRange parameter

### ISSUE THREAD

**Issue by OracPrime** [Azure/azure-sdk-for-net#17305]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
As described in #17149 there is considerable performance variability (and underperformance) using the blob Download method.  To achieve proper performance an iterative (to cope with partial result returns) and parallel (to get performance) solution has to be manually wrapped around the Download call.  These optimisations are already present in DownloadTo and DownloadToAsync, but both of these methods always download the entire blob.

Adding an overload to each of DownloadTo and DownloadToAsync that takes an HttpRange specifier would remove the need for end-users to write their own performance enhancing code around a Download call.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by OracPrime** [comment]
I'm hoping this is still on the backlog; this a comment to avoid a no-activity close-out.
