### ISSUE TITLE
[BUG] PersistKeysToAzureBlobStorage throws Could not load type 'Azure.Storage.StorageClientOptions' from assembly 'Azure.Storage.Common, Version=12.4.1.0

### ISSUE THREAD

**Issue by dawwa** [Azure/azure-sdk-for-net#17321]
**Describe the bug**

.Net Core 3.1 App
Invoking `ProtectKeysWithAzureKeyVault` throws the following exception.

**Looks like some code is trying to call internal code?**  `StorageClientOptions` appears internal here at [StorageClientOptions.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/src/Shared/StorageClientOptions.cs)

{"Could not load type 'Azure.Storage.StorageClientOptions' from assembly 'Azure.Storage.Common, Version=12.4.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'.":"Azure.Storage.StorageClientOptions"}

`
   at Azure.Storage.Blobs.BlobServiceClient..ctor(String connectionString, BlobClientOptions options) in D:\a\1\SourceDirWith49CharsLengthTestForLongPaths\sdk\storage\Azure.Storage.Blobs\src\BlobServiceClient.cs:line 151
   at Azure.Storage.Blobs.BlobServiceClient..ctor(String connectionString) in D:\a\1\SourceDirWith49CharsLengthTestForLongPaths\sdk\storage\Azure.Storage.Blobs\src\BlobServiceClient.cs:line 124
   at Microsoft.AspNetCore.DataProtection.AzureStorageBlobDataProtectionBuilderExtensions.PersistKeysToAzureBlobStorage(IDataProtectionBuilder builder, String connectionString, String containerName, String blobName) in /_/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Blobs/src/AzureStorageBlobDataProtectionBuilderExtensions.cs:line 159
`

**To Reproduce**

Try to use the ProtectKeysWithAzureKeyVault API, e.g.,
```csharp

            // Setup the Storage and Blob Container
            string storageConnectionString = Environment.GetEnvironmentVariable("AzureWebJobsStorage");

            // Setup the Data Protection
            string keyIdentifier = Environment.GetEnvironmentVariable("DATAPROTECTION_KEYID");

            try
            {
                return services
                    .AddDataProtection(options => options.ApplicationDiscriminator = "xxxx")
                    .PersistKeysToAzureBlobStorage(storageConnectionString, "dataprotection", "keys.xml")
                    .ProtectKeysWithAzureKeyVault(
                    new Uri(keyIdentifier),
                    new DefaultAzureCredential(new DefaultAzureCredentialOptions()));
            }
            catch (Exception ex)
            {
                ;
            }
```

**Environment:**
 - Name and version of the Library package used: \.nuget\packages\azure.extensions.aspnetcore.dataprotection.blobs\1.0.1\lib\netstandard2.0\Azure.Extensions.AspNetCore.DataProtection.Blobs.dll

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
```cmd
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.100\

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  2.1.811 [C:\Program Files\dotnet\sdk]
  2.2.110 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.110 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

 - IDE and version : Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi! I see that you're using the `Azure.Extensions.AspNetCore.DataProtection.Blobs` package, I was wondering if anywhere you have the nuget package `Azure.Storage.Blobs` as a dependency to your project because the package above (making an assumption here) takes a dependency on that.

Could you get the version of `Azure.Storage.Blobs` you are using as well? I will attempt to repoduce your code as well.

**Comment by amnguye** [comment]
Can anyone from Extensions ASP NET help with this issue, or route it to the people can help? @jsquire @pakrym 

I was syncing up with the customer and looks like these are the versions that their package is using.
![image](https://user-images.githubusercontent.com/48961492/102287009-57234580-3eee-11eb-8f4d-cffd45115f8c.png)
The error is linking it to 12.4.1 of `Azure.Storage.Common` but in their dependencies it looks like their extension library is taking a dependency on `12.0.0` which is the older version. Should the extensions package upgrade to the latest version?

**Comment by pakrym** [comment]
In the screenshot you've included, it looks like all the versions are in sync. Is there some other package that brings common 12.4.1?

**Comment by dawwa** [comment]
looks like the top level project reference to 12.4.1 forced it, and this means there are breaking change that need to take care of?
![image](https://user-images.githubusercontent.com/44714043/102287883-352ac280-3ef0-11eb-96bb-4e2ebf0e4ca9.png)

**Comment by pakrym** [comment]
Makes sense. I think we had a minor breaking change in the Storage libraries early on. I'll bump the extension dependency past it.

**Comment by amnguye** [comment]
Thanks for your help on this @pakrym !

**Comment by pakrym** [comment]
The https://www.nuget.org/packages/Azure.Extensions.AspNetCore.DataProtection.Blobs/1.2.0 is out.
