### ISSUE TITLE
Add a sample showing client side batching when sending

### ISSUE THREAD

**Issue by bjuris** [Azure/azure-sdk-for-net#17331]
**Query/Question**
We are migrating to the new client *Azure.Messaging.ServiceBus* from *WindowsAzure.ServiceBus*. The previous client had a [client-side batching feature](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-framework-sdk#client-side-batching), is there something similar in the new client?

We have a bursty load so it would not be possible to use the batching feature at Send time, it would have to be a background process that buffer messages for a short while and then sends them off. We could ofcourse implement this ourselves instead if you have some pointers.

**Environment:**
 - Azure.Messaging.ServiceBus 7.0.0
 - .NET 5
 - IDE and version : Visual Studio 16.8.1

**Comment by JoshLove-msft** [comment]
Hi @bjuris, thanks for trying out the new library. Similar to the previous SDK, Microsoft.Azure.ServiceBus, the Azure.Messaging.ServiceBus SDK does not currently support client side batching. For now, I think you would need to implement this yourself by queueing up messages until you reach a threshold of messages or time elapsed in which you would want to send the messages. Would it be helpful to have a sample showing something like this?

**Comment by bjuris** [comment]
Thanks for the quick reply, that would certainly help.

**Comment by RobHudson72** [comment]
+1 for this request... Our environment is that we have an App Service based API that has high volume and performance requirements.  We need events from multiple requests to be batched together, similar to the behavior available in WindowsAzure.ServiceBus.  We need the message to send from a background thread in batches, flushing after a certain interval.  Sample code would be very helpful.

**Comment by jashu-csl** [comment]
+1 for this request. any ETA on this.

**Comment by bjuris** [comment]
@JoshLove-msft Any update on this?

**Comment by JoshLove-msft** [comment]
I've put this in our milestone that ends in the beginning of June.

**Comment by JimSuplizio** [comment]
Hi @bjuris, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
