### ISSUE TITLE
[BUG] Azure.Identity: Too strict scopes

### ISSUE THREAD

**Issue by dmladek-dtml** [Azure/azure-sdk-for-net#17333]
**Describe the bug**

I tried to get user_impersonation scope on arm (https://management.core.windows.net/user_impersonation) which I understand from [here ](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent) is standard scope but I get an error that underscore cannot be used (I was using AzureCliCredential specifically, not sure about other credentials. I tried with default credential before and it got all the way to vs code where it obtained the token).
```
AzureCliCredential authentication failed: The specified scope is not in expected format. Only alphanumeric characters, '.', '-', ':', and '/' are allowed (Parameter 'scope')
```

**Expected behavior**
Accept the scope parameter.

**Actual behavior (include Exception or Stack Trace)**
Throws an error.

**To Reproduce**
```
var tokenProvider = new AzureCliCredential();
var token= tokenProvider.GetToken(new Azure.Core.TokenRequestContext(new[]{"https://management.core.windows.net/user_impersonation"})).Token;
```
**Environment:**
 - Name and version of the Library package used: Azure.Identity 1.2.3
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET 5.0.100 CLI (the project is core 3.1 though).
 - IDE and version : VS Code 1.43.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
@dmladek-dtml Although there does seem to be an issue with the scope validation, it appears that you are attempting to do an On Behalf Of flow. Unfortunately, we don't yet support that, but the following issue has some information about how to work around this until we do.

https://github.com/Azure/azure-sdk-for-net/issues/16264#issuecomment-716869572

Does this work for your scenario?

**Comment by mladedav** [comment]
(the reporter account is another account of mine to prevent any confusion)
@christothes I don't remember what exactly I was trying to accomplish, but I believe I got it working in the end for the scenario needed, possibly without the use of actual scopes, but thank you for the links.
