### ISSUE TITLE
[QUERY] Use of StorageTransferOptions is not very discoverable and "sensible" parameters are not obvious

### ISSUE THREAD

**Issue by NeilMacMullen** [Azure/azure-sdk-for-net#17337]
**Environment:**
 - Azure.Storage.Blobs 12.7.0 

I just discovered that BlockBlobClient.UploadAsync() is extraordinarily slow in its default configuration.  Transferring 24 MB from UK to US was taking 15-20 minutes.

The solutions is to pass in a BlobUploadOptions object containing a StorageTransferOptions object.  I used 

```
   new StorageTransferOptions
   {
       MaximumConcurrency = 20,
       InitialTransferLength = 0x10000,
       MaximumTransferSize = 0x10000
   }
```
and reduced the upload time to well under a minute.

This leads to a couple of comments....

1) Whatever defaults that are used when the options are NOT explicitly specified lead to dreadful performance and it's not terribly discoverable that you need to hand-tune them to get to a decent baseline.  (I'm guessing DownloadToAsync will suffer from the same issue.)

2) It's not at all obvious what "sensible" values should be provided.  I appreciate that everyone's system is different and there's no "right" answer but perhaps some singletons such as StorageTransferOptions.TypicalDesktop or StorageTransferOptions.IIS would help.  Failing that, improving the documentation (https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Storage.Common/12.4.1/api/Azure.Storage/Azure.Storage.StorageTransferOptions.html) to suggest some typical values would be useful.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
@jaschrep-msft @kasobol-msft To help address better defaults for download/upload options and to see if maybe documentation is needed to help suggest certain values (obviously this would require the user to have a good grasp on their environment and we should have to put some kind of disclaimer that the defaults suggested can only help to an extent)

**Comment by amishra-dev** [comment]
@jaschrep-msft, James can you coordinate with Tamra and get the doc updated to reflect the sensible defaults and then close this bug with the link to the doc?

**Comment by JohnLBevan** [comment]
For those hitting this thread, there's some useful related info in this checklist (not addressing the specific point of optimal StorageTransferOptions settings; but closely related): https://docs.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#checklist

**Comment by jaschrep-msft** [comment]
Update: a guide to `StorageTransferOptions` is underway and going through our internal review and publishing process.

**Comment by jaschrep-msft** [comment]
A [blog post](https://devblogs.microsoft.com/azure-sdk/tuning-your-uploads-and-downloads-with-the-azure-storage-client-library-for-net/) on this topic has been published to the Azure SDK dev blog.
