### ISSUE TITLE
[BUG] Problem While Creating a Basic Application Gateway Using the New Azure.ResourceManager.Network Library

### ISSUE THREAD

**Issue by ItayPodhajcer** [Azure/azure-sdk-for-net#17354]
**Describe the bug**
An exception is thrown when trying to create a basic Application Gateway.

**Expected behavior**
Application Gateway should be created successfully.

**Actual behavior (include Exception or Stack Trace)**
Message:
```
Service request failed.
Status: 400 (Bad Request)

Content:
{
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.httpListeners[0].properties.frontendIPConfiguration."
      },
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.httpListeners[0].properties.frontendPort."
      },
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.httpListeners[1].properties.frontendIPConfiguration."
      },
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.httpListeners[1].properties.frontendPort."
      }
    ]
  }
}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-request-id: REDACTED
x-ms-client-request-id: cb9a5f00-31f7-461e-bf25-626042581094
Strict-Transport-Security: REDACTED
Server: Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
X-Content-Type-Options: REDACTED
Date: Sat, 05 Dec 2020 19:12:09 GMT
Content-Length: 859
Content-Type: application/json; charset=utf-8
Expires: -1
```

Stack Trace:
```
   at Azure.ResourceManager.Network.ApplicationGatewaysRestOperations.<CreateOrUpdateAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.ResourceManager.Network.ApplicationGatewaysOperations.<StartCreateOrUpdateAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Cladular.Platform.Backend.Adapters.Azure.AzureAdapter.<CreateBasicGatewayAsync>d__11.MoveNext() in C:\Users\itayp\Source\Repos\cladular\platform\src\Backend\Adapters\AzureAdapter.cs:line 233
```

**To Reproduce**
The problem seems to be related to the `HttpListeners` requiring the IDs of the frontend IP configuration and front port, which at that point don't exist, as they are created as part of the Application Gateway, as the HTTP listeners are.

```
appGatewayConfig.HttpListeners.Add(new()
{
    Name = $"MyHttpListener",
    FrontendIPConfiguration = appGatewayConfig.FrontendIPConfigurations[0],
    Protocol = ApplicationGatewayProtocol.Http,
    FrontendPort = appGatewayConfig.FrontendPorts[0],
});
```

I think it is similar to #3359 and #3361.

**Environment:**
 - Name and version of the Library package used: Azure.ResourceManager.Network 1.0.0-preview.2

**Comment by ItayPodhajcer** [comment]
Problem is consistent in all sub-resources that depend on other sub-resources that are created as part of the application gateway creation operation.
Workaround is to manually build and supply the resource ID of each of the required sub-resources.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by YalinLi0312** [comment]
@m-nash Can you look into this?

**Comment by valault1** [comment]
Hello,

I don't think this was ever addressed, as I'm still getting this error. Fully configured application gateways are very important to automating our deployments, so we'd be thrilled if this was fixed!

**Comment by SaurabhSharma-MSFT** [comment]
@ItayPodhajcer Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know.

**Comment by ItayPodhajcer** [comment]
Been a while since I touched that code, but I'll be happy to learn about any solution/workaround for the issue.

**Comment by hovermind** [comment]
> Problem is consistent in all sub-resources that depend on other sub-resources that are created as part of the application gateway creation operation. Workaround is to manually build and supply the resource ID of each of the required sub-resources.

Currently Pulumi Azure Native example does this. I was getting error for 2 days until came here!

**Comment by archerzz** [comment]
This indeed is a service API issue. The swagger sample also requires those IDs: https://github.com/Azure/azure-rest-api-specs/blob/e729721df20047dcb4fdb675d234b6821f1a4f81/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/examples/ApplicationGatewayCreate.json#L140

The SDK team cannot help here. We need the service team to take a look at this issue.

**Comment by archerzz** [comment]
The SDK is auto-generated. One API is mapped to one method in SDK. The Service API requires all depending resources to be created, before creating application gateway.

I could not see an easy way there since creating application gateway is not simple. Here are some references:
- Azure docs on how to create application gateway in Powershell (which is close to .Net SDK): https://docs.microsoft.com/en-us/azure/application-gateway/quick-create-powershell
- Test case on creating application gateway: https://github.com/Azure/azure-sdk-for-net/blob/0e9e877b70c8219acc8a37653ee421b6b4c07f5e/sdk/network/Azure.ResourceManager.Network/tests/Tests/ApplicationGatewayTests.cs#L81
