### ISSUE TITLE
ServiceBusSessionProcessorOptions is missing setter

### ISSUE THREAD

**Issue by TKocoloski** [Azure/azure-sdk-for-net#17352]
**Query/Question**
How can we help?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

In the latest 7.0.0.0 version it appears there is no way to set the SessionIds property.  How is this property to be set to limit the session that the processor processes?

**Comment by jsquire** [comment]
Hi @TKocoloski.  Thank you for your feedback and we regret that you're experiencing difficulties.   The `ServiceBusSessionProcessorOptions` contains a property for [`SessionIds`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusSessionProcessorOptions.cs#L135) which allows you to specify the set of sessions that you'd like the processor to work with.   The options are passed into the constructor when creating the processor.   

A simple example would look something like:

```csharp

var options = new ServiceBusSessionProcessorOptions();
options.SessionIds.Add("first-session");
options.SessionIds.Add("second-session");

await using var client = new ServiceBusClient(connectionString);
var processor = client.CreateSessionProcessor(queueName, options);
```

**Comment by TKocoloski** [comment]
I see, thank you for the follow up!

**Comment by JoshLove-msft** [comment]
This can also be set using the list inializer syntax:
```cs
var options = new ServiceBusSessionProcessorOptions
{
   SessionIds = { "session1", "session2" }
};
```
