### ISSUE TITLE
Support for Cross Entity transactions

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#17355]
# Cross-entity transactions

## Background
Transactions are used in Service Bus (and generally in AMQP) to perform a series of operations atomically - either they all succeed or none of them do. As an example, suppose a user wants to complete a message that represents an order being filled and send another message that represents a notification to a customer, but only if both succeed - that is if an error prevents the message about the order being filled from being completed, they don't want to send the notification message. Service Bus transactions enable this feature. Where it gets tricky is if you are attempting to perform a transaction that involves multiple entities - for instance in the order example, if you have an Orders queue and a separate Notifications queue, the service has to perform some magic to get things to work correctly. Essentially the user has to tell the SDK that they want the sender that is configured to send messages to the Notifications queue, to send messages via the Orders queue. This allows the service to perform the transaction atomically because all the messages involved in the transaction are located on the same entity at some point. After the transaction is committed, the message that is really destined for the Notifications queue will be forwarded on from the Orders queue. The way that this was initially exposed in our T2 clients during preview was as follows:

```cs
        var client = new ServiceBusClient(connectionString);
        ServiceBusReceiver receiver = client.CreateReceiver(OrdersQueue);
        ServiceBusSender sender = client.CreateSender(NotificationsQueue, new ServiceBusSenderOptions { SendVia = OrdersQueue});
        
        ServiceBusReceivedMessage received = await receiver.ReceiveMessageAsync();

        using (var ts = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
        {
            await receiver.CompleteMessageAsync(received);
            await sender.SendMessageAsync(new ServiceBusMessage());
            ts.Complete();
        }
```

## Service Update

The send-via feature is unique to Service Bus and isn't really relevant to the user's workflow. In order to address this, the service has made updates to infer what the send-via entity is based on usage rather than requiring the client to specify it. To be clear, the service still uses send-via to perform cross-entity transactions, but the goal is to hide this from users. 

The way it is implemented is that when the client alerts the service that it will be doing cross-entity transactions on an AMQP link, the first link that is established on the AMQP session becomes the implicit send-via entity. Any subsequent links that wish to participate in the cross-entity transaction would need to be created on the same AMQP session, and all operations will send-via the first link. This does introduce a subtlety in the usage in that any links established after the first link need to either be senders or if they are receivers, they have to be receiving from the same entity as the first link. Otherwise you would be saying to the service that you want to receive-via a different entity which isn't possible. This wasn't an issue with the explicit SendVia option because the client would be telling the service what the SendVia entity was explicitly, so assuming that part was setup correctly, a user could do operations in any order that they want. In practice, users will generally be receiving before sending when doing transactions so hopefully this will not be a major concern. Additionally, the service throws an exception with this setup so it would be caught during testing.

Another subtlety is that any operations that are done outside of a transaction scope with these cross-entity transaction senders/receivers will still use the send-via semantics. The difference is that if they are not part of a transaction the operations will be persisted to their final destinations immediately as opposed to waiting for the transaction to be committed by the user. This means that the same rule about the ordering of sender/receiver link applies outside of transaction scopes as well when using the new feature.

## Usage

In order to support this feature in the Track 2 SDK, we introduce a new option on the senders/receivers/processors - `string CrossEntityTransactionGroup`.

```cs
        var client = new ServiceBusClient(connectionString);

        var sender = client.CreateSender(
            NotificationsQueue, 
            new ServiceBusSenderOptions 
            { 
                CrossEntityTransactionGroup = "ordersGroup"
            });
        var receiver = client.CreateReceiver(
            OrdersQueue, 
            new ServiceBusReceiverOptions 
            { 
                CrossEntityTransactionGroup = "ordersGroup"
            });
        
        using (var ts = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
        {
            // throws as the receiver link is created after the sender link and they target different entities
            // if they targeted the same entity, this would be allowed
            // NOTE: in the SDK, the links are created lazily on the first operation that would use them. So we 
            // assume in this example, these are the first send and receive operations with these entities.
            await sender.SendMessageAsync(new ServiceBusMessage());
            var received = await receiver.ReceiveMessageAsync();
            await receiver.CompleteMessageAsync(received);
            ts.Complete();
        }

        using (var ts = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
        {
            // allowed as the sender link is created after the receive link
            var received = await receiver.ReceiveMessageAsync();
            await receiver.CompleteMessageAsync(received);
            await sender.SendMessageAsync(new ServiceBusMessage());
            ts.Complete();
        }
```

## Design considerations

- Looking at the API updates, a natural question is why do we even need this `CrossEntityTransactionGroup` option. Should we just have it on by default? The issue there is that this would likely hurt performance for users that don't need this feature and have an adverse impact on the service (since everything would need to use send-via). Additionally, by having users opt in with a string, they could configure multiple transaction groups within the same client.

- What about just having a `bool` property like `EnableCrossEntityTransactions`? The issue here is that this would probably sound too inviting for users and many users would end up enabling it without understanding what it does. By leaving the option as a string, it will force users to read the documentation to understand whether they actually need this feature - they should understand specifically that there are drawbacks to using it if they don't need it (perf).
Additionally, by having users opt in with a string, they could configure multiple transaction groups within the same client.

- What about transactions that span only a single entity? This option should not be set if a user does not need to span multiple entities in a transaction. They can just do transactions as before on a single entity and the implicit send-via will not be used.

**Comment by SeanFeldman** [comment]
Related PR: https://github.com/Azure/azure-sdk-for-net/pull/18402

**Comment by JoshLove-msft** [comment]
Closing as this has been merged in and will be included in a future preview.

**Comment by JoshLove-msft** [comment]
After further internal discussion, we are planning to go with the approach of having a single bool property. As discussed in design considerations:

> What about just having a bool property like EnableCrossEntityTransactions? The issue here is that this would probably sound too inviting for users and many users would end up enabling it without understanding what it does. By leaving the option as a string, it will force users to read the documentation to understand whether they actually need this feature - they should understand specifically that there are drawbacks to using it if they don't need it (perf).
> Additionally, by having users opt in with a string, they could configure multiple transaction groups within the same client.

The possible confusion of having to set an arbitrary string outweighs the concerns around limiting to a single send-via entity per client. If customers run into issues where they need multiple send-via entities per client, we can extend at that time to support TransactionGroups or some other mechanism to enable this.

**Comment by danielmarbach** [comment]
In general, I like the boolean approach. One thing though that you have to consider is that with the previous design of using the transaction scope it would have been possible design atomic units of failure by wrapping and grouping things with a scope. With the new design this is no longer possible. Have you considered the angle that  customers might be using it that way? As an example

```
receiver = new MessageReceiver(connection, inputQueue);
sender = new MessageSender(connection, destinationQueue, inputQueue);
receiver.RegisterMessageHandler(
    async (message, token) =>
    {
        await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("We always want this one to go out")));

        // atomic group
        using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
        {
            await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Should be atomic 1")));

            if (!message.UserProperties.ContainsKey("Win")) throw new InvalidOperationException();

            await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Should be atomic 2")));

            scope.Complete();
        }
    },
    ...
);
```

or even more advanced scenarios like

```
                    try
                    {
                        using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
                        {
                            await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Should be atomic 1")));

                            if (!message.UserProperties.ContainsKey("Win")) throw new InvalidOperationException();

                            await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Should be atomic 2")));

                            scope.Complete();
                        }
                    }
                    catch 
                    {
                        await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Should always go")));
                    }
```

how would I be able to design a system where a message is allowed to get out with this new bool property?

Or even this scenario?

```
try
                    {
                        using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
                        {
                            await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Will not leak")));

                            if (!message.UserProperties.ContainsKey("Win")) throw new InvalidOperationException();

                            await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Will not leak")));

                            scope.Complete();
                        }
                    }
                    catch 
                    {
                        //await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Will leak")));
                    }
                    finally
                    {
                        using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
                        {

                            await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Will not leak")));

                            await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Will not leak")));

                            scope.Complete();
                        }
                    }
```

Wouldn't it be much better to design a capability similar to the batch? For example something like

```
using ServiceBusAtomicMessageBatch atomicBatch = await receiver.CreateAtomicMessageBatchAsync();
atomicBatch.TryAddMessage(...)
await sender.SendAtomicMessagesAsync(atomicBatch);
```

with that, the previous scenarios are still possible and since the receiver is in charge of creating the atomic batch the relationship between the receiver and the sender becomes even clear. On top of that the weird problem of knowing when the TxScope is copied, that you always require async flow options and other shortcomings of txscope are gone. This makes the lib also automatically more interoperable due to no longer needing to rely on the transactions API.

**Comment by JoshLove-msft** [comment]
> In general, I like the boolean approach although I think it is too simplistic considering the power of the previous API. One thing though that you have to consider is that with the previous design of using the transaction scope it would have been possible design atomic units of failure by wrapping and grouping things with a scope. With the new design this is no longer possible. Have you considered the angle that customers might be using it that way? As an example

Perhaps I'm missing something but I'm not sure why these scenarios wouldn't be possible with the bool property. When setting the bool property equal to true, all links will be created under the same AMQP session. This will allow cross entity-transactions to work provided the first link that attached makes sense to be used as the send-via entity. TransactionScopes are still expected to be used. This bool is just replacing the viaEntity param from the previous library. The property would not need to be set for transactions on a single entity.

**Comment by danielmarbach** [comment]
OK now I understand. To me that wasn't clear even after rereading it previously multiple times. The only information I had available was the information in this issue and not all the background discussions and context. Now that you clarified the bool property works similar to the group key I can envision how the code would look like. Thanks!

I still think the API proposal I've made would have several intention revealing benefits like I mentioned in the previous comment. T Scope has the additional disadvantage that it has to be explicitly suprressed when other Transactional resources are at play to not enlist into ambient contexts (which with the SDK tx would even be actively prevented like before right?). The API proposed wouldn't have that shortcoming

**Comment by JoshLove-msft** [comment]
> OK now I understand. To me that wasn't clear even after rereading it previously multiple times. The only information I had available was the information in this issue and not all the background discussions and context. Now that you clarified the bool property works similar to the group key I can envision how the code would look like. Thanks!

That's fair. I've updated my comment to include a code snippet using the bool property. 

> I still think the API proposal I've made would have several intention revealing benefits like I mentioned in the previous comment. T Scope has the additional disadvantage that it has to be explicitly suprressed when other Transactional resources are at play to not enlist into ambient contexts (which with the SDK tx would even be actively prevented like before right?). The API proposed wouldn't have that shortcoming

We did consider doing something more explicit like:
```cs
var client = new ServiceBusClient(connectionString);
ServiceBusTransactionGroup txnGroup = client.CreateTransactionGroup();
ServiceBusSender sender = txnGroup.CreateTransactionalSender(OrdersQueue);
ServiceBusProcessor processor = txnGroup.CreateTransactionalProcessor(OrdersQueue);

processor.ProcessMessageAsync += MessageHandler;
processor.ProcessErrorAsync += ErrorHandler;

async Task MessageHandler(ProcessMessageEventArgs args)
{
    using (var ts = txnGroup.CreateTransactionScope())
    {
        // the ordering here does matter
        await args.CompleteMessageAsync(args.Message);
        await sender.SendMessageAsync(new ServiceBusMessage());
        ts.Complete();
    }
}
```
The downside is that this is a lot of new API surface area for what is a more advanced scenario. I think the same is true for your proposal, while more explicit, it adds a lot of surface area. Our current thought was to start with the bool property with the thought that we could always add something more explicit in the future if this property turns out to be limiting for these use cases.

**Comment by danielmarbach** [comment]
I do agree that it adds a bit more surface area. Yet it would allow to also properly design into the API surface area the restrictions of the cross entity transaction like the maximum allowed elements a cross entity transaction can contain. 

I also think that ambient transactions are non-intuitive to work with and require a high degree of API understand of the non-obvious transaction scope while a dedicated transaction group or "batch" for the cross entity transaction could be much more lightweight to carry around.

**Comment by JoshLove-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/19161 merged

**Comment by JoshLove-msft** [comment]
Closing for tracking purposes but feel free to add additional comments or thoughts before we GA this feature.
