### ISSUE TITLE
Support for AMQP Value/Sequence

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#17356]
This issue will track the support for being able to get/set the Amqp Value/Sequence sections on an AmqpAnnotadedMessage. This will eventually be exposed via Azure.Core.Amqp and can be used as part of Azure.Messaging.ServiceBus.

**Comment by pakrym** [comment]
Wasn't this done?

**Comment by JoshLove-msft** [comment]
Yep
