### ISSUE TITLE
[BUG] ServiceBusSessionReceiverOptions race condition

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#17388]
There is a race condition that can occur when using the same `ServiceBusSessionReceiverOptions` instance for multiple receivers. We are setting the SessionId to use on the internal `SessionId` property which would cause issues when the same instance is being used for multiple receivers. We should instead just remove the internal property and pass the session Id as a parameter wherever it is needed. Alternatively, we could clone the options that the user provides but this would be an unnecessary allocation.

**Comment by jsquire** [comment]
Since the options themselves are mutable, doesn't that still leave you open to potential problems when they're updated?  Are they held by clients after construction and referenced at all?

**Comment by JoshLove-msft** [comment]
> Since the options themselves are mutable, doesn't that still leave you open to potential problems when they're updated? Are they held by clients after construction and referenced at all?

No we don't hold onto the options.
