### ISSUE TITLE
[EventHubs] Partition checkpoint retrieval can be optimized

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17386]
Currently, we load all checkpoints from the blob container and then look for a single one for the partition we care about. This is inefficient and can be improved by only loading the blob properties for a single partition.

Considering `ListCheckpointsAsync` is part of the public API I propose adding a virtual GetCheckpointsAsync(string partitionId, string fullyQualifiedNamespace, string eventHubName, string consumerGroup, CancellationToken cancellationToken)` and having a default implementation that works via the `ListCheckpointsAsync` call. We would then override `GetCheckpointsAsync` with a more efficient implementation int the `BlobsCheckpointStore`

**Comment by jsquire** [comment]
Self note:  Also review suggestions from the internal email thread for optimizations during this workstream.
