### ISSUE TITLE
Samples for Mocking Client Types

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#17380]
# Summary

The Service Bus client library aims to be mockable and fully support testability.  To help illustrate usage of the new API for the testing scenarios, a set of samples  mocking the various Service Bus client types and illustrating use of the model factory  is needed.

# Scope of Work

- Implement a sample or set of samples demonstrating a basic approach for mocking the high level client types for their core scenarios.  Included should be:<br />
  - `ServiceBusClient`
  - `ServiceBusProcessor`
  - `SeviceBusSessionProcessor`
  - `ServiceBusReceiver`
  - `ServiceBusSessionReceiver`
  - `ServiceBusSender`
  - `ServiceBusAdministrationClient`<br /><br />

- Ensure that the use of the model factory is demonstrated for key types, including:<br />
  - ` ServiceBusReceivedMessage`
  - `QueueProperties`,
  - `TopicProperties`,
  - `RuleProperties`

# Success Criteria

- The sample(s) have been created, with a clear and simple approach and detailed discussion to support the goal of helping those unfamiliar with Service Bus to get started testing its types.

- The sample(s) adhere to the coding conventions and standards defined for track two libraries.

- All projects in the solution compile; any warnings that exist have either been fixed or additional work items filed to address them if they were deemed non-critical.

- The sample(s) follow the pattern within the Service Bus library, are compiled and executed as part of the Live test suite.

**Comment by Matthewsre** [comment]
I came across this issue when trying to find a reason there is no IServiceBusSender option to create for tests. From the "track 1" Microsoft.Azure.ServiceBus we could use the IQueueClient, but it looks like testing/interfaces aren't available for this new library. 

@jsquire, I won't be able to get any adoption from my colleagues on this new library without being able to write unit tests. Any guidance until this documentation is added, or is this just not possible currently?

**Comment by jsquire** [comment]
Hi @Matthewsre.  Thank you for reaching out and we regret that you're experiencing difficulties.   The Service Bus library is able to be mocked for testing today; this issue is for tracking the work to create samples to demonstrate common mocking scenarios and aid discoverability.

Support for mocking and unit testing is one of the core goals of the new Azure SDKs, and the details of the approach that we use is discussed in the [Azure SDK Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking).  Our intent is to ensure that it is usable with a mocking library such as `Moq` or `FakeItEasy` in addition to supporting custom mocks via inheritance.

Each of the Service Bus client types are unsealed, have a parameterless constructor, and all of the public members are either `virtual` or settable.  Each SDK also has a model factory class that allows creation of the types returned from service operations that can't be directly created.  In the case of Service Bus, the [ServiceBusModelFactory](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusmodelfactory) is the factory.

You should be able to mock any client using the same approach that you prefer for other types in your application, using the model factory to help simulate behavior.  If you're seeing other unit testing gaps that we haven't considered, we'd be very interested in your specific scenarios so that we can take them into account and improve the experience.

**Comment by forktrucka** [comment]
I'm using Moq. Trying to new up a ServiceBusClient for Azure.Messaging.ServiceBus.ServiceBusClient, i get this:

```
System.ArgumentException: Type to mock ({0}) must be an interface, a delegate, or a non-sealed, non-static class.
 ---> System.TypeLoadException: Method 'CreateSender' on type 'Castle.Proxies.MockableServiceBusClientProxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is overriding a method that is not visible from that assembly.
   at System.Reflection.Emit.TypeBuilder.TermCreateClass(QCallModule module, Int32 tk, ObjectHandleOnStack type)
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateTypeInfo()
   at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.CreateType(TypeBuilder type)
   at Castle.DynamicProxy.Generators.Emitters.AbstractTypeEmitter.BuildType()
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateType(String name, Type[] interfaces, INamingScope namingScope)
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.<>c__DisplayClass1_0.<GenerateCode>b__0(String n, INamingScope s)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.<>c__DisplayClass33_0.<ObtainProxyType>b__0(CacheKey _)
   at Castle.Core.Internal.SynchronizedDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Castle.DynamicProxy.Generators.BaseProxyGenerator.ObtainProxyType(CacheKey cacheKey, Func`3 factory)
   at Castle.DynamicProxy.Generators.ClassProxyGenerator.GenerateCode(Type[] interfaces, ProxyGenerationOptions options)
   at Castle.DynamicProxy.DefaultProxyBuilder.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyType(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxy(Type classToProxy, Type[] additionalInterfacesToProxy, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Moq.CastleProxyFactory.CreateProxy(Type mockType, IInterceptor interceptor, Type[] interfaces, Object[] arguments) in C:\projects\moq4\src\Moq\ProxyFactories\CastleProxyFactory.cs:line 62
   --- End of inner exception stack trace ---
   at Moq.CastleProxyFactory.CreateProxy(Type mockType, IInterceptor interceptor, Type[] interfaces, Object[] arguments) in C:\projects\moq4\src\Moq\ProxyFactories\CastleProxyFactory.cs:line 66
   at Moq.Mock`1.InitializeInstance() in C:\projects\moq4\src\Moq\Mock`1.cs:line 311
   at Moq.Mock`1.OnGetObject() in C:\projects\moq4\src\Moq\Mock`1.cs:line 325
   at Moq.Mock.get_Object() in C:\projects\moq4\src\Moq\Mock.cs:line 179
   at Moq.Mock`1.get_Object() in C:\projects\moq4\src\Moq\Mock`1.cs:line 283
```

**Comment by SeanFeldman** [comment]
> Each of the Service Bus client types are unsealed, have a parameterless constructor, and all of the public members are either `virtual` or settable. The Service Bus client library also has a model factory class that allows creation of the types returned from service operations that can't be directly created [ServiceBusModelFactory](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusmodelfactory).
> 
> You should be able to mock any client using the same approach that you prefer for other types in your application, using the model factory to help simulate behavior. If you're seeing other unit testing gaps that we haven't considered, we'd be very interested in your specific scenarios so that we can take them into account and improve the experience.

This needs to be in the documentation. Ideally, in the following order of preference:
1. SB how-to guide at [docs.microsoft.com](https://docs.microsoft.com/en-us/azure/service-bus-messaging/)
2. [readme.md](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/README.md)

**Comment by worldspawn** [comment]
I can mock virtuals with my chosen mock library (nSubstitute). But it's not really ideal vs interfaces, there always seems to be more gotchas when testing in this way (speaking generally). Interfaces also don't require any documentation to explain how to use. Its a bit of an annoying design choice :)

What was the reason for defining no interfaces? I see this is a thing in the storage sdk as well.

**Comment by jsquire** [comment]
Hi @worldspawn.  With respect to the lack of interfaces, the Azure SDKs have a goal of strict backwards compatibility with a very high bar for any breaking changes.  With that in mind, the use of an interface makes evolving over time difficult; any change to the public API surface represented in an interface becomes a breaking change for anyone who has implemented it - including when we want to add new members.  

Adding more interfaces to define new members (much like native COM interfaces do in Windows) is possible, but becomes burdensome and confusing to consumers of the SDK.  While default interface implementation makes this somewhat more palatable, they're not supported in all of the frameworks that we target.  Our classes and their virtual members can still be mocked and do not have this problem.  As a result, we intentionally avoid using interfaces outside of special circumstances.

**Comment by JDZelenak** [comment]
I have been able to mock ServiceBusSender, but I seem to be having an issue mocking ServiceBusReceiver.  I get the following error using Autofac and Moq
`Message: 
Autofac.Core.DependencyResolutionException : An exception was thrown while activating λ:System.Object.
---- System.ArgumentException : Type to mock must be an interface or an abstract or non-sealed class. 
-------- System.TypeLoadException : Method 'CompleteMessageAsync' on type 'Castle.Proxies.TestServiceBusReceiverProxy' from assembly 'DynamicProxyGenAssembly2, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' is overriding a method that is not visible from that assembly.
`
I look forward to the samples that this issue will generate.
