### ISSUE TITLE
Azure.Identity.CredentialUnavailableException

### ISSUE THREAD

**Issue by zhenlan** [Azure/azure-sdk-for-net#17394]
@abethan commented on [Sun Dec 06 2020](https://github.com/Azure/AppConfiguration/issues/439)

        public Startup(IHostingEnvironment env)
        {
            var localConfig = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();

            TokenCredential tokenCredential = new DefaultAzureCredential();

            if (env.IsDevelopment())
            {
                localConfig.AddUserSecrets(Assembly.Load(new AssemblyName(env.ApplicationName)));
                tokenCredential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { VisualStudioTenantId = "<tenantId>" });
            }

            var localConfigBuild = localConfig.Build();

            Configuration = new ConfigurationBuilder()
                .AddConfiguration(localConfigBuild)
                .AddAzureAppConfiguration(options => options.Connect(new Uri(localConfigBuild["AzureConfiguration:AppConfigurationEndPoint"]), tokenCredential)
                                                            .ConfigureKeyVault(x => x.SetCredential(tokenCredential))
                                                            .ConfigureClientOptions(clientOptions => clientOptions.Retry.MaxRetries = 5)).Build();
        }

I'm getting the below exception with this code
**Azure.Identity.CredentialUnavailableException: 'Process "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\b1hwzg3d.j4s\TokenService\Microsoft.Asal.TokenService.exe" has failed to get access token in 30 seconds.'**

I have got 2 accounts inside the Visual Studio 
![image](https://user-images.githubusercontent.com/6123545/101303711-be0f8180-3892-11eb-89d0-06f59af1e265.png)

But I have assigned the correct AD tenant in the Options.

![image](https://user-images.githubusercontent.com/6123545/101303797-fa42e200-3892-11eb-9a79-d3186ac6a659.png)

Please help me to fix this issue. Thanks.

**Comment by jsquire** [comment]
Hi @abethan.  Thank you for your feedback and we regret that you're experiencing difficulties.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @abethan - I have a few questions: 
- Can you confirm which version of VS 2019 you are using?
- Does it reproduce with the latest version?
- Does it reproduce if you only have one account registered?
