### ISSUE TITLE
Could not load type 'Microsoft.WindowsAzure.CloudConfigurationManager' from assembly 'Microsoft.WindowsAzure.Configuration'

### ISSUE THREAD

**Issue by omnoms** [Azure/azure-sdk-for-net#1740]
Similar to #1006

The latest nuget package 3.2.0 (assembly 3.0.0 still) doesn't work well with latest AzureGraphClient package. That package tries to use Microsoft.WindowsAzure.CloudConfigurationManager whilst it's under Microsoft.Azure.CloudConfigurationManager.

Checking the Object Explorer I see that the namespace desired by the azure graph client is indeed empty. 

![image](https://cloud.githubusercontent.com/assets/7261863/12547157/eef5c75a-c34e-11e5-83a1-39b2ee5ab2a8.png)

I've re-downloaded the 2.8 SDK, I've even pointed the NuGet Manager to the local source as primary source and reinstalled, and the issue prevails.

![image](https://cloud.githubusercontent.com/assets/7261863/12547173/13f9153e-c34f-11e5-95d8-973e1ed05bfa.png)

Exception thrown;

[TypeLoadException: Could not load type 'Microsoft.WindowsAzure.CloudConfigurationManager' from assembly 'Microsoft.WindowsAzure.Configuration, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.]
   Azure.ActiveDirectory.GraphClient..cctor() +0

[TypeInitializationException: The type initializer for 'Azure.ActiveDirectory.GraphClient' threw an exception.]

**Comment by hovsepm** [comment]
@omnoms please use latest version 3.2.1. It should be fixed there. Please reopen this issue if it is not fixed.

**Comment by markcowl** [comment]
@dreadeddev Apologies for the incompatibility, but unfortunately there is no fix here in ConfigurationManager.  All new development must use the Microsoft.Azure namespace.  Either the AzureGraphClient must update to use the new namespace, or you must use an earlier version of ConfigurationManager that is compatible with AzureGraphClient
