### ISSUE TITLE
Azure.Search.Documents (11.2.0-beta.1) / Common SerializePropertyNamesAsCamelCase not available

### ISSUE THREAD

**Issue by dougse** [Azure/azure-sdk-for-net#17402]
Unable to use the SerializePropertyNamesAsCamelCase  attribute as a matching assembly/nuget Azure.Search.Common which contains the attribute is not available

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by tg-msft** [comment]
We've got much more flexible serialization in v11.  You can set your own https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.searchclientoptions.serializer?view=azure-dotnet#Azure_Search_Documents_SearchClientOptions_Serializer.  You'd want something like `options.Serializer = new JsonObjectSerializer(new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase });`

**Comment by dougse** [comment]
@tg-msft Thanks, we tried the serialization option you suggested, however, but the problem is when the fieldbuilder is called, it creates PascalCased properties, and the AzureAPI returns them in that case (Pascal) - so we really need to find a way to get SerializePropertyNamesAsCamelCase working

**Comment by tg-msft** [comment]
Please try setting https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.indexes.fieldbuilder.serializer?view=azure-dotnet to the same serializer instance.

**Comment by dougse** [comment]
Thanks, that is how we have "solved" this but we have a need to create a wrapper for others to consume, doing this on the service/builder instantiation is causing us to do some sloppy things.  Having the  SerializePropertyNamesAsCamelCase attribute working would help us write better code/solutions....
