### ISSUE TITLE
LazyLoadingReadOnlyStream.Seek with SeekOrigin.End alters stream length

### ISSUE THREAD

**Issue by aecucu** [Azure/azure-sdk-for-net#17401]
**Describe the bug**
LazyLoadingReadOnlyStream.Seek with SeekOrigin.End alters stream length and subsequent Read operation returns zero

**Expected behavior**
Seek does not alter Length.

**Actual behavior (include Exception or Stack Trace)**
LazyLoadingReadOnlyStream.Seek with SeekOrigin.End alters stream length.
See also:
https://github.com/Azure/azure-sdk-for-net/blob/d263f23aa3a28ff4fc4366b8dee144d4c0c3ab10/sdk/storage/Azure.Storage.Common/src/Shared/LazyLoadingReadOnlyStream.cs#L384

**Environment:**
Azure.Storage.Blobs 12.7.0
Windows 10 .NET Framework 4.7.2
 - IDE and version : Visual Studio 16.8.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
@seanmcc-msft Can you look into and explain why length is adjusted when we go to calculate the the new position of the stream when `SeekOrigin.End` ?

**Comment by seanmcc-msft** [comment]
Hi @aecucu,

Thank you for reporting this, I've put out a PR to address this issue: https://github.com/Azure/azure-sdk-for-net/pull/17443

-Sean
