### ISSUE TITLE
Static Registers of IServiceClientInterceptor in Multithreaded Environment

### ISSUE THREAD

**Issue by flipch** [Azure/azure-sdk-for-net#17409]
This is handled by the client runtime. If this is still an issue, please reopen it [there](https://github.com/Azure/azure-sdk-for-net).

_Originally posted by @olydis in https://github.com/Azure/autorest/issues/1408#issuecomment-315888906_

Hello there, I'm trying to add tracing to only **one** of my HTTP Clients instances. It happened to have been generated by Autorest, the issue is when enabling it like in the documentation

```cs
ServiceClientTracing.AddTracingInterceptor(clientTracing);
ServiceClientTracing.IsEnabled = true;
```

It'll actually start redirecting **all** traffic to my TracingInterceptor for the entire Webjob(in this case), including totally unrelated HTTP Clients

This enables it globally. According to @olydis, this is handled by the client runtime and therefore I must ask for help here. Can someone guide me through the necessary fixes or is this a bug?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
@pakrym:  I may be routing incorrectly.   If so, please let me know.

**Comment by flipch** [comment]
I haven't been able to find any alternatives other than the static initalizer. Do I have to create some sort of concurrent list where I keep track of each client to track if I want to differentiate the `SentRequest` `ReceivedResponse` methods?

**Comment by pakrym** [comment]
I'm afraid there is no non-global way to register the interceptor. 

You can try and use the `Enter` event to map from the `invocationId` to client `instance` and then only log `SentRequest`/`ReceivedResponse` for those ids.

A simpler option might be implementing a `DelegatingHandler` and passing it to the client constructor. That way you don't need any additional mapping.

**Comment by flipch** [comment]
I ended up with some of a hacky solution. 

- Created a wrapper handler that takes in multiple interceptors
- Each interceptor got initialized with a unique guid
- Each request we make that we want to get intercepted has those unique guids attached in the headers with a unique header name so that server ignore them
- The handler catches all requests/responses but looks for the header guid's and redirects it to the proper interceptor.
