### ISSUE TITLE
AppAuthentication is not detecting MSI in a Windows container on Azure App Service

### ISSUE THREAD

**Issue by krispenner** [Azure/azure-sdk-for-net#17425]
**Describe the bug**
I use the `Microsoft.Azure.Services.AppAuthentication` package to retrieve the access token of the MSI to authenticate with both Key Vault and other App Services. This works great for a ASP.NET Core 3.1 web app running in Linux container on an Azure App Service. The exact same code also works great for a ASP.NET Core 2.2 web app targeting the .NET Framework 4.8 and running on a normal Windows Azure App Service. The exact same code does NOT work for a ASP.NET Core 2.2 web app targeting the .NET Framework 4.8 and **running in a Windows container** on a Windows Azure App Service.

When running in a Windows container, the `Microsoft.Azure.Services.AppAuthentication` library does not seem to pickup the MSI credentials or detect the MSI for some reason. I'm wondering if this is expected to work or not and if anyone has actually tested this and can confirm if it works?

If I supply an `AzureServicesAuthConnectionString` environment variable it works fine and the `Microsoft.Azure.Services.AppAuthentication` library detects and uses the SP and credentials that are specified in the `AzureServicesAuthConnectionString` environment variable. But this is not meant to be used like this for production deployments. It should detect and use the MSI of the web app.

**Expected behavior**
Microsoft.Azure.Services.AppAuthentication should work the same in a Windows container on an Azure App Service as it does for a Linux container on an Azure App Service and also a normal web app.

**Actual behavior (include Exception or Stack Trace)**
Seems to ignore the MSI credentials.  I am having a difficult time getting any logs out of the container regarding Microsoft.Azure.Services.AppAuthentication.

**Environment**
Azure Windows container App Service with MSI enabled.
ASP.NET Core 2.2 targeting the .NET Framework 4.8.
Microsoft.Azure.Services.AppAuthentication v1.6.0.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//cc: @nonik0, @anaismiller

**Comment by anaismiller** [comment]
@krispenner Would you be able to request the MSI token manually inside the container? This is to verify that you are able to call the MSI token in the environment and then to see if the error is potentially with the container not picking up the MSI environment variables.

You can follow the example in here [Managed identities - Azure App Service | Microsoft Docs](https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=dotnet#obtain-tokens-for-azure-resources) to request an MSI token manually.

**Comment by jvano** [comment]
I haven’t tried with AppAuthentication class but manually it works fine. For example, I’ve just tried the following commands using Kudu console from a container using the image “microsoft/iis” with system MSI enabled:

$resourceURI = "https://vault.azure.net"
$tokenAuthURI = $env:IDENTITY_ENDPOINT + "?resource=$resourceURI&api-version=2019-08-01"
$tokenResponse = Invoke-RestMethod -Method Get -Headers @{"X-IDENTITY-HEADER"="$env:IDENTITY_HEADER"} -Uri $tokenAuthURI
$accessToken = $tokenResponse.access_token

Can you try restarting the Windows Container Web App after enabling MSI and try again? Let us know if that works

**Comment by jvano** [comment]
I tried with a .net core 3.1 app inside a Windows Container in Azure App Service and the following code worked fine as well:

AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider();
string accessToken = await azureServiceTokenProvider.GetAccessTokenAsync("https://vault.azure.net");

**Comment by krispenner** [comment]
﻿
Sorry for the lack of response from my end. I will test this soon and report back. I think it may be failing with the KeyVaultConfigurationProvider which I’m not sure if it’s using the AppAuthentication library internally. All I know is when I added the  AzureServicesAuthConnectionString environment variable then it all works. The configuration from key vault is loaded at startup and authentication works with all APIs via the AppAuthentication library during requests. When I remove the AzureServicesAuthConnectionString  environment variable, the container cannot startup.

Anyways will try to test this more very soon.

On Dec 17, 2020, at 11:05 AM, Joaquín Vano Newman <notifications@github.com> wrote:

﻿

I tried with a .net core 3.1 app inside a Windows Container in Azure App Service and the following code worked fine as well:

AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider();
string accessToken = await azureServiceTokenProvider.GetAccessTokenAsync("https://vault.azure.net");

**Comment by krispenner** [comment]
Sorry for the lack of response from my end. I will test this soon and report back. I think it may be failing with the `AzureKeyVaultConfigurationProvider in Microsoft.Extensions.Configuration.AzureKeyVault v3.1.10.0` which I’m not sure if it’s using the AppAuthentication library internally. All I know is when I added the `AzureServicesAuthConnectionString` environment variable then it all works. The configuration from key vault is loaded at startup and authentication works with all APIs via the `AppAuthentication` library during requests. When I remove the `AzureServicesAuthConnectionString` environment variable, the container cannot startup.

Anyways will try to test this more very soon.

**Comment by jvano** [comment]
Please share the code that works in App Service Web Apps and doesn't work in App Service Web App Container. I would like to try to reproduce the issue

**Comment by krispenner** [comment]
Just providing some more info, when I set the `AzureServicesAuthConnectionString` environment variable so the container starts. I then display all the environment variables and I see the following all set related to this issue which seem correct.

## Environment Variables
| Name | Value |
|-|-|
| AzureServicesAuthConnectionString | RunAs=App;AppId=_removed_ ;TenantId=_removed_ ;AppKey=_removed_  |
| IDENTITY_ENDPOINT | http://100.64.100.2:41580/MSI/token/ |
| IDENTITY_HEADER | _removed_ |
| MSI_ENDPOINT | http://100.64.100.2:41580/MSI/token/ |
| MSI_SECRET | _removed_ |

I know this isn't what you were asking for, but I just thought it helps prove the MSI does seem to be enabled correctly.
Looking into `AzureKeyVaultConfigurationProvider`, it is dependent on `AppAuthentication` as well. I'm adding some code to skip the `AzureKeyVaultConfigurationProvider` at start-up so that I can then test the other API calls that request a token via `GetAccessTokenAsync` and see if any of them succeed.

Sharing code is a bit difficult at the moment, just a lot of unrelated code to be removed and cleaned up. Will see what I can put together later tomorrow.

**Comment by krispenner** [comment]
So after disabling the `AzureKeyVaultConfigurationProvider` the container was able to startup just fine. I then invoked some some test requests I added to retrieve a key vault token like you asked. They are failing to connect to the MSI service at the TCP level, timing out after 21 seconds which is the typical TCP connection timeout. However, since the app now starts up, I am able to get logs from the requests including the error message from `AzureServiceTokenProvider` that I was hoping for.

>Tried to get token using Managed Service Identity. Failed after 5 retries. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.

#### Error Message
```
Unhandled AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried the following 4 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried to get token using Managed Service Identity. Failed after 5 retries. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Visual Studio token provider file not found at "C:\Windows\system32\config\systemprofile\AppData\Local\.IdentityService\AzureServiceAuth\tokenprovider.json"
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: . Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command,
operable program or batch file.

Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.microsoftonline.com/common. Exception Message: Tried to get token using Active Directory Integrated Authentication. Access token could not be acquired. Failed to get user name from the operating system.Inner Exception : No mapping between account names and security IDs was done.

```

#### Stack Trace
```

   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<GetAuthResultAsyncImpl>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<GetAccessTokenAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

#### MSI Endpoint
MSI Service according to environment variables at the time of the error was: `http://100.64.100.2:41838/MSI/token/`

#### MSI Failed Attempt (1 of 5)
![image](https://user-images.githubusercontent.com/8837910/102596944-bd66be80-40ce-11eb-8a94-f095dea40f12.png)

#### Timeline
![image](https://user-images.githubusercontent.com/8837910/102598127-65c95280-40d0-11eb-9232-c9ac4f7d216a.png)

**Comment by krispenner** [comment]
I thought I would share my Dockerfile in case that helps:

```
FROM mcr.microsoft.com/dotnet/framework/aspnet:4.8

ADD https://download.visualstudio.microsoft.com/download/pr/ba001109-03c6-45ef-832c-c4dbfdb36e00/e3413f9e47e13f1e4b1b9cf2998bc613/dotnet-hosting-2.2.8-win.exe /dotnethosting/dotnethosting.exe
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Start-Process C:\\dotnethosting\\dotnethosting.exe -ArgumentList '/quiet', '/install' -Wait
RUN Remove-Item -Force -Recurse C:\\dotnethosting
RUN Start-Process iisreset.exe -NoNewWindow -Wait

## setup environment
ENV API_APPNAME=MyApp \
    API_APPVERSION=2

## setup app
WORKDIR /inetpub/wwwroot
COPY . .
```

**Comment by krispenner** [comment]
@jvano I have isolated the issue to having VNet integration configured on the web app with the application setting `VNET_ROUTE_ALL` set to `1`.

#### Success:
![image](https://user-images.githubusercontent.com/8837910/102644268-60dac200-4115-11eb-98bb-9cb55bc38bda.png)

#### Failure:
![image](https://user-images.githubusercontent.com/8837910/102644509-ccbd2a80-4115-11eb-8932-1ec0ad262771.png)

So my next questions are:
1. Is VNet integration expected to be supported by Windows container App Services?
1. If yes, then is VNET_ROUTE_ALL expected to be supported by Windows container App Services?

#### IP Restrictions
I also have IP restrictions configured which I thought might also be causing issues, but after removing them all it didn't make any difference. Definitely seems to be an issue with Azure's Windows container based App Service and not properly working with VNet Integration.

#### App Service Support
I will raise this issue with the Azure App Service's team now to get a jump in that direction. Seems the `AppAuthentication` library is probably fine. I went through many teething issue with Linux App Services when they were released and didn't support VNet integration properly, I found more than a few issues then, looks to be the same with Windows containers as well now.

**Comment by jvano** [comment]
Answering the questions:
1. Yes, VNet integration is supported for Windows Containers on Azure App Service.
2. No, while we support VNet, we don't have the capability to route all the traffic thru the VNet, so VNET_ROUTE_ALL=1 functionality doesn't work with Windows Containers on Azure App Service. The reason why it changes the behavior once you enable it is because we added some code trying to make the feature VNET_ROUTE_ALL=1 work but as I mentioned earlier, it doesn't work right now.
3. Managed NAT is not expected to work at this point as we don't route all the traffic thru the VNet.

**Comment by krispenner** [comment]
Great, thanks for confirming that. It would be ideal if you can indicate this somehow in the container start-up logs to log an error if `VNET_ROUTE_ALL=1` is enabled on a Windows container and warn that it's not supported and it will break other app functionality such as MSI.

Regardless, I will need to leave Windows containers alone for the time being.

Any timeline on when `VNET_ROUTE_ALL=1` is expected to work for Windows containers?

**Comment by jvano** [comment]
We have no plans to fix VNET_ROUTE_ALL=1 in the short term but I will make sure that if it is defined not to break existing functionality like MSI

**Comment by krispenner** [comment]
Feel free to re-open this ticket to publicly track and update VNET_ROUTE_ALL=1 support for Windows containers.

**Comment by krispenner** [comment]
@jvano I am now testing with on a Windows container within an ASE**v3**. The web app settings require `VNET_ROUTE_ALL=1` to be enabled, which I find a bit odd considering the web app is deployed within my VNet so it really can't not route through it. If I set it to `0` or try to delete the setting it just always reappears with a value of `1`. The problem now, is that Managed Identities don't work with Windows containers in an ASE because of this, even though I see no documentation saying that Managed Identities are not supported on Windows containers when in an ASE.

**Comment by jvano** [comment]
Hi

Recently we fixed VNET_ROUTE_ALL behavior for Windows Containers on Azure App Service and as you mentioned ASEv3 is always in a VNet context, so please open a support ticket and we will assist you:

How to create an Azure support request:
https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by krispenner** [comment]
Thanks @jvano. I have created a support request. Will close this.
