### ISSUE TITLE
[FEATURE REQ] Support custom Client App ID in DefaultAzureCredential (currently hard-coded to use the az cli client ID)

### ISSUE THREAD

**Issue by ohadschn** [Azure/azure-sdk-for-net#17427]
**Library or service name.**
Azure.Identity 
 
**Is your feature request related to a problem? Please describe.**
We have strict control over some of our AAD apps, where we allow only specific client IDs to access them.
Specifically, we do not allow the Azure CLI Client ID (04b07795-8ddb-461a-bbee-02f9e1bf7b46).

Unfortunately, when using `DefaultAzureCredential`, there is no way to specify the client ID to use:
https://github.com/Azure/azure-sdk-for-net/blob/cd97a7ffcb948d5a6e21f3c3fc6ef0d4737b0424/sdk/identity/Azure.Identity/src/Constants.cs#L17

Adding something like a `ClientAppId` property to `DefaultAzureCredentialOptions` would be great (and I imagine not too hard to implement).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Some credentials used by DefaultAzureCredential can be configured with a ClientId via the options. Is there a specific scenario where you've found this not to be possible?

**Comment by ohadschn** [comment]
> Some credentials used by DefaultAzureCredential can be configured with a ClientId via the options. Is there a specific scenario where you've found this not to be possible?

It looks likes things have changed since I opened this bug, specifically `InteractiveBrowserCredentialClientId` and `ManagedIdentityClientId` which look great. I guess I'd have to exclude all the others though to make sure e.g. token is not taken from cache with the wrong ClientId, which would be a shame if I had the right token in the cache for some reason...

How about something like a unified `ClientId` instead (or in addition, where the above specific ones can override it), where the same order of credentials is tried (environment, managed identity, etc) and the first one which is successful for that Client ID takes?

**Comment by christothes** [comment]
> It looks likes things have changed since I opened this bug, specifically `InteractiveBrowserCredentialClientId` and `ManagedIdentityClientId` which look great. I guess I'd have to exclude all the others though to make sure e.g. token is not taken from cache with the wrong ClientId, which would be a shame if I had the right token in the cache for some reason...

Could you talk a bit more about how the current configuration options prevent using the intended ClientId in your specific scenario? For example, in a production scenario, I would think that you'd have a very specific credential to target, such as ManagedIdentity. In a development scenario, you'd have control over which credential would be selected based on your dev environment configuration. My assumption is that it should be rare that the intended credential (and in effect the intended ClientId) in the chain is not chosen.

Another thing to consider is that if you need more control over the credential chain and how it is configured, the `ChainedTokenCredential` is intended exactly for that. `DefaultAzureCredential` is definitely the most convenient options, but is not intended for scenarios where total control over the configuration is necessary.
