### ISSUE TITLE
non mockable objects. how do I test my code?

### ISSUE THREAD

**Issue by cfauchere** [Azure/azure-sdk-for-net#17435]
**Describe the bug**
Here is the definition of Resource
```
namespace Azure.ResourceManager.Compute.Models
{
    //
    // Summary:
    //     The Resource model definition.
    public class Resource : IUtf8JsonSerializable
    {
        //
        // Summary:
        //     Initializes a new instance of Resource.
        //
        // Parameters:
        //   location:
        //     Resource location.
        //
        // Exceptions:
        //   T:System.ArgumentNullException:
        //     location is null.
        public Resource(string location);

        //
        // Summary:
        //     Resource Id.
        public string Id { get; }
        //
        // Summary:
        //     Resource name.
        public string Name { get; }
        //
        // Summary:
        //     Resource type.
        public string Type { get; }
        //
        // Summary:
        //     Resource location.
        public string Location { get; set; }
        //
        // Summary:
        //     Resource tags.
        public IDictionary<string, string> Tags { get; }
    }
}
```
how can I mock this class or derived classes for test given the readonly non virtual properties?

**Environment:**
 - Name and version of the Library package used: Azure.ResourceManager.Compute 1.0.0-preview.2
 - Hosting platform or OS and .NET runtime version

> .NET SDK (reflecting any global.json):
>  Version:   5.0.100
>  Commit:    5044b93829
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.18363
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.100\
> 
> Host (useful for support):
>   Version: 5.0.0
>   Commit:  cf258a14b7
> 
> .NET SDKs installed:
>   3.1.401 [C:\Program Files\dotnet\sdk]
>   5.0.100 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 

 - IDE and version : VS 19 Version 16.8.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by YalinLi0312** [comment]
@m-nash Could you take a look?

**Comment by cfauchere** [comment]
Hi, this issue is still blocking adoption. Prompt assistance would be appreciated. Thanks.

**Comment by cfauchere** [comment]
ping

**Comment by m-nash** [comment]
Can you give me more context into how you intend to mock the class?  In general given this is a response object you can mock the transport for the service client and define the response you want as json which will be deserialized into this object.

This reference here might be helpful https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/.

**Comment by cfauchere** [comment]
> Can you give me more context into how you intend to mock the class? In general given this is a response object you can mock the transport for the service client and define the response you want as json which will be deserialized into this object.
> 
> This reference here might be helpful https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/.

Well I am not looking in testing the SDK by injecting a mock of the transport layer but mock the SDK itself so I can test my code. For example: 
`ResourceGroupsOperations `as public virtual method `ListAsync`
```
public virtual AsyncPageable<ResourceGroup> ListAsync(string filter = null, int? top = null, CancellationToken cancellationToken = default);
```
I should be able to build a mock of `ResourceGroupsOperations` and inject it in my code. The problem is I can't do so because I cannot instantiate `ResourceGroup` objects.

**Comment by m-nash** [comment]
There is a work item on the code generator to automatically add a factory to construct and set the readonly properties for these models.  https://github.com/Azure/autorest.csharp/issues/543.
