### ISSUE TITLE
[FEATURE REQ] Support zero-touch certificate rotation in ClientCertificateCredential

### ISSUE THREAD

**Issue by pharring** [Azure/azure-sdk-for-net#17432]
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
In our service, certificates are retrieved from KeyVault. We use SNI authentication. Certificates can be rotated at any time while the service is running and we want zero-touch certificate rotation. i.e. you shouldn't have to restart the app just because certificates have been rotated. Rather, the service should periodically go back to Key Vault and, if there's a new version, the service should automatically pick it up and use it when OAuth tokens expire. We have a (self-imposed) 4 hour SLA for responding to certificate rotation events and renewing tokens.

To do this, we wrote custom code in a class derived from `TokenCredential` that implements both SNI and certificate refresh. To implement certificate refresh, we introduced a `ICertificateProvider` interface. This is similar to the internal `ClientCertificateCredential.IX509Certificate2Provider` interface, but it is used not only for constructing the `ConfidentialClientApplication`, but also inside `AcquireTokenForClientAsync`.

My proposal is:
1. Un-nest `IX509Certificate2Provider` and make it public:

```csharp
namespace Azure.Identity
{
    public interface IX509Certificate2Provider
    {
        ValueTask<X509Certificate2> GetCertificateAsync(bool async, CancellationToken cancellationToken);
    }
}
```
2. Add a constructor overload on `ClientCertificateCredential` that accepts an `IX509Certificate2Provider`:
```csharp
        public ClientCertificateCredential(string tenantId, string clientId, IX509Certificate2Provider certificateProvider, ClientCertificateCredentialOptions options);
```

3. Update `MsalConfidentialClient` to call `GetCertificateAsync` each time `AcquireTokenForClientAsync` is called and cache the resulting `X509Certificate2` object. If the value changes (due to a certificate refresh), then the confidential client needs to be recreated or updated. This part is tricky, I realize -- but that's why I'd like the SDK to take care of it for us.

You do have to be clear about the semantics of `IX509Certificate2Provider` since certificates are `IDisposable` -- does the caller take ownership of the returned certificate, for example?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pharring** [comment]
An even more complete solution here would involve something in Azure.KeyVault.Secrets/Certificates that implements IX509Certificate2Provider. However, I realize neither of those packages currently have a dependency on Azure.Identity. Perhaps that means IX509Certificate2Provider needs to go into Azure.Core.

**Comment by schaabs** [comment]
@Pharring thanks for the feature request. The introduction of SNI authentication certainly makes automatic certificate rotation more desirable. Currently we have an unrelated feature request to enable the `ClientCertificateCredential` to fetch certificates from stores other than the local file system, and I think we might have a proposed solution which could satisfy both these feature requests.

What if we were to add a means of constructing the `ClientCertificateCredential` with a callback similar in shape to `GetCertificateAsync` from `IX509Certificate2Provider` rather then a `X509Certificate2` instance or path. This would enable users to provide custom code for loading a certificate, and also provide a mechanism for rolling a certificate across the lifetime of the credential. We would need to think through how we control how this method is called, would it be called every time the certificate is used? only every so often? should it be configurable? etc, but I think this might be a workable solution to your request.  What do you think?

**Comment by pharring** [comment]
@schaabs
> What if we were to add a means of constructing the ClientCertificateCredential with a callback similar in shape to GetCertificateAsync from IX509Certificate2Provider rather then a X509Certificate2 instance or path. 

Yes, that's exactly what I proposed. For simplicity sake, I would call it every time the certificate is used. We can then supply default policy classes (implementations of IX509Certificate2Provider) to add features like caching and refresh.

As I've mentioned, we should be clear about ownership of the X509Certificate2 object -- who calls Dispose?

**Comment by loic-sharma** [comment]
It seems subject name / issuer (SNI) auth is now supported if you set [`ClientCertificateCredentialOptions.SendCertificateChain`](https://docs.microsoft.com/dotnet/api/azure.identity.clientcertificatecredentialoptions.sendcertificatechain?view=azure-dotnet#azure-identity-clientcertificatecredentialoptions-sendcertificatechain) to `true`:

```cs
var credential = ClientCertificateCredential(
    tenantId,
    clientId,
    certificate,
    new ClientCertificateCredentialOptions
    {
        SendCertificateChain = true
    });
```

Perhaps this issue can be closed :)

**Comment by degant** [comment]
Any update on the original ask of making `IX509Certificate2Provider` public as well as the new ctor on `ClientCertificateCredential`?

A bunch of services we own will benefit from this i.e being able to dynamically retrieve and use new certs from KV periodically without restarting the app.

**Comment by JimSuplizio** [comment]
Hi @pharring, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
