### ISSUE TITLE
Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretVersionsAsync GET's incorrect URL

### ISSUE THREAD

**Issue by loekd** [Azure/azure-sdk-for-net#1743]
Calling 'GetSecretVersionsAsync' on Microsoft.Azure.KeyVault.KeyVaultClient throws an exception of type 'KeyVaultClientException'
At that time, the value of 'RequestUri' on the exception is:
https://mykeyvault.vault.azure.net/secrets//secrets/1/versions?api-version=2015-06-01
Notice that 'secrets' is duplicated in the URL, which causes a 404 Resource not found error.

The bug is in Microsoft.Azure.KeyVault.Internal.SecretOperations.cs line 449, where an additional '/secrets' string is appended to the vault URL. 

Note that the other Secret-related operations (SetSecretAsync, DeleteSecretAsync) don't tamper with the vault URL.

**Comment by herveyw** [comment]
@loekd Hi, a vault URL should just be the name of the vault and should not contain any path information as the SDK handles that automatically. For example, https://mykeyvault.vault.azure.net is a valid vault name, but https://mykeyvault.vault.azure.net/secrets is not. Would you check that you're not passing in the additional path segment?
