### ISSUE TITLE
[Perf, Stress] Add '-log' and '-validate' options in test frameworks

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#17439]
Consider adding options to let the perf tests log and validate operations that can serve as verification runs.

**Comment by Mohit-Chakraborty** [comment]
@mikeharder I created this issue as per our discussion.

**Comment by JimSuplizio** [comment]
Hi @Mohit-Chakraborty, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
