### ISSUE TITLE
[QUERY] Microsoft.Azure.Management.Subscription 1.1.0-preview version

### ISSUE THREAD

**Issue by maamleka** [Azure/azure-sdk-for-net#17434]
**Query/Question**
I am using Microsoft.Azure.Management.Subscription 1.1.0-preview NuGet package for C# and need to know if this package is being deprecated, if so, what is the timeline and what are the breaking changes if I need to upgrade to the latest package. 

**Environment:**
 - Name and version of the Library package used:   Microsoft.Azure.Management.Subscription 1.1.0-preview NuGet

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maamleka** [comment]
Any inputs on this?

Madhura

**Comment by anuragdalmia** [comment]
Hi, the latest version is at https://www.nuget.org/packages/Microsoft.Azure.Management.Subscription/. This is actually the GA version of our APIs. Following is the breaking change release note. Note that as of now, we encourage you to adopt the GA version of the APIs vs the preview APIs, but we dont have any timeline when we will completely deprecate the preview version.  

Breaking changes:
               * This is the new release of Microsoft.Subscription
               * SDK structure has been updated to make it more consistent and user-friendly:
 1. Put Subscription Alias Api has been added to support subscription creation
                 2. Post CreateSubscription APIs have been removed as new subscription alias API provides the same functionality.
