### ISSUE TITLE
Azure.Search.Document How to specify headers to capture telemetry

### ISSUE THREAD

**Issue by mathieuisabel** [Azure/azure-sdk-for-net#17449]
I'm currently using Azure.Search.Document v11.2.0-beta.2 with c# and I can't seem to be able to pass customHeaders in the Search method as suggested here:

https://docs.microsoft.com/en-us/azure/search/search-traffic-analytics#step-2-request-a-search-id-for-correlation

Is there another method that should be used to achieve this?

Also, the procedure on the Azure Portal seems to refer to the previous Microsoft.Azure.Search package which I think has been deprecated in favor of Azure.Search.Document. Is that correct?

![image](https://user-images.githubusercontent.com/15805484/101780864-1928ba80-3ac5-11eb-9061-23019f3e8975.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by tg-msft** [comment]
The equivalent of that would be writing a custom pipeline policy that adds the headers.  See https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Pipeline.md#implementing-a-syncronous-policy for a basic example adding a custom header.

**Comment by mskuratowski** [comment]
I am facing the same problem. 

@tg-msft Thanks for that but it seems like a workaround. 

The question is how to do it using the .NET SDK.

**Comment by AlexGhiondea** [comment]
@mathieuisabel @mskuratowski it seems like the sample has been updated to show how to do this with the v11 of the library. Are you still running into issues?

**Comment by as-99** [comment]
We're currently using Azure.Search.Documents v11.1.1 (latest stable) and are having this issue, is it resolved in the latest beta (v11.2.0-beta.2)?

The documentation sample for this still doesn't seem to actually match what we're seeing, there are no overloads to receive customHeaders either.

We've implemented a custom pipeline policy and managed to get the search-id returning there, but that doesn't give us a particularly elegant way of getting that information where we actually require it.

Thanks for your help

**Comment by PiotrPerak** [comment]
@as-99 no it's not resolved in v11.2.0-beta.2.
@AlexGhiondea where is this sample?

**Comment by AlexGhiondea** [comment]
@PiotrPerak I was referring to the link you [shared](https://docs.microsoft.com/en-us/azure/search/search-traffic-analytics#step-2-request-a-search-id-for-correlation) - it now shows how to use the new SDK as well.
