### ISSUE TITLE
[BUG] Blob client Exists does not send customer provided encryption key

### ISSUE THREAD

**Issue by fvaillancourt** [Azure/azure-sdk-for-net#17458]
**Describe the bug**
If the blob is encrypted with a customer provided encryption key, even though you provide the key in your client, Exists[Async] method will fail. I noticed the BlobBaseClient.ExistsInternal calls BlobRestClient.Blob.GetPropertiesAsync which takes the key parameter but it is not provided. Thus the call fails with a message that tell us the encryption key is missing.

**Expected behavior**
The call should succeed.

**Actual behavior (include Exception or Stack Trace)**
The call fails with a message that tell us the encryption key is missing.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a blob client and set a customer provided key.
2. Use the client to upload some data.
3. Call the Exists method, which will fail even though the key is in the client.

**Environment:**
 - Azure.Storage.Blobs 12.7.0
 - Windows 10 .Net Framework 4.6.1
 - Rider 2020.2

**Comment by gapra-msft** [comment]
@fvaillancourt Thank you for reporting this issue. 

@amnguye It looks like existsInternal needs to call into getPropertiesInternal instead of calling BlobRestClient.Blob.GetPropertiesAsync. We need to do this to preserve the CPK/encryption scope data. Could you please confirm when you get a chance?

**Comment by seanmcc-msft** [comment]
I have created a PR to address this issue, and also a related issue with Encryption Scopes.
