### ISSUE TITLE
[Synapse] Why does creating base Trigger type not set name but return no error

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-for-net#17459]
A number of trigger tests required this change:

```
- TriggerCreateOrUpdateTriggerOperation createOperation = await TriggerClient.StartCreateOrUpdateTriggerAsync(triggerName, new TriggerResource(new Trigger()));
+ TriggerCreateOrUpdateTriggerOperation createOperation = await TriggerClient.StartCreateOrUpdateTriggerAsync(triggerName, new TriggerResource(new ScheduleTrigger(new ScheduleTriggerRecurrence())));
```

else the returned trigger does not have the requested name.

And I can confirm using the derived "works", however why is this necessary? Should we not allow instancing Trigger by itself?

**Comment by jsquire** [comment]
Given the age of this issue, closing this as stale.  If tests are still failing, please file a new issue.
