### ISSUE TITLE
[FEATURE REQ] TextAnalytics:  Add LRO Polling sample document

### ISSUE THREAD

**Issue by suhas92** [Azure/azure-sdk-for-net#17475]
**Library or service name.**
Cognitive Services  / Long Running Operations

**Is your feature request related to a problem? Please describe.**
We should add a document for using polling in LRO's.

Similar to this one
https://github.com/Azure/azure-sdk-for-net/blob/948d075e16b8599f8c48f92b356eb5f17efa2bad/sdk/textanalytics/Azure.AI.TextAnalytics/samples/Sample_LROPolling.md

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
This is included here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Response.md
