### ISSUE TITLE
Consider exposing InitializeWithLegacyCheckpoints on EventProcessorClientOptions

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17474]
Now that we have an internal implementation of legacy checkpoint reading it would be nice to allow the processor customers to use it.

**Comment by jsquire** [comment]
Agreed.   I'll raise it to the feature team and architects post-MQ.

**Comment by jsquire** [comment]
## Notes for Implementation

It looks as if the [legacy blob prefix](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/BlobCheckpointStore/BlobsCheckpointStore.cs#L52) is not a stable value.  `EventProcessorHost` allows it to be [customized](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.EventHubs.Processor/src/EventProcessorHost.cs#L64) with the default form being [empty](https://github.com/Azure/azure-sdk-for-net/blob/5e548be88453d763bd220a704fb236caef21cc71/sdk/eventhub/Microsoft.Azure.EventHubs.Processor/src/AzureStorageCheckpointLeaseManager.cs#L58).   The current format mask in the `BlobCheckpointStore` assumes the format specific to the form [generated by Azure Functions](https://github.com/Azure/azure-functions-eventhubs-extension/blob/5eb8543e47b448eb3b485a571a2ceb1ab404650f/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Config/EventHubOptions.cs#L356), which is used to [initialize the `EventProcessorHost`](https://github.com/Azure/azure-functions-eventhubs-extension/blob/5eb8543e47b448eb3b485a571a2ceb1ab404650f/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Config/EventHubOptions.cs#L262).

If we decide to expose the functionality for the Event Hubs client library, we'll need to mimic the track one functionality of allowing customization of the prefix and defaulting to an empty value.

**Comment by jsquire** [comment]
I had an initial discussion on this topic with @ramya-rao-a, who wanted to give this further consideration, discuss at the leads level, and circle-back.   I'm going to reassign to Ramya for now and ask that she assign back to me when a decision has been reached.

**Comment by jsquire** [comment]
@ramya-rao-a:  Have any decisions been made for this?

**Comment by ramya-rao-a** [comment]
In the year that has passed since this issue was logged, we have not seen any customer requests for this feature. Therefore, closing.
