### ISSUE TITLE
[MetricsAdvisor] Tests: validate WebNotificationHook.CertificateKey

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#17485]
The service won't accept any string as a certificate key. We need to get a valid mock certificate key and update the `TODO` comments in `NotificationHookLiveTests`.

**Comment by Gyeonghun-Park** [comment]
Hello @kinelski :)
I found some `TODO: add CertificateKey validation` comments in `NotificationHookLiveTests` class.
So I am interested in contributing this issue but I wonder if I could help with this?
