### ISSUE TITLE
Storage weekly tests broken for Canary region

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#17484]
Looks like all storage [weekly test builds](https://dev.azure.com/azure-sdk/internal/_build?definitionId=2030&_a=summary) running in Canary are broken with:

```
"error": {
      "code": "DeploymentFailed",
      "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
      "details": [
        {
          "code": "FeatureNotSupportedForAccount",
          "message": "supportsBlobContainerRetention is not supported for the account."
        }
      ]
    }
```

**Comment by maririos** [comment]
Note that this is still failing. Latest build example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=667359&view=results

**Comment by JimSuplizio** [comment]
Hi @maririos, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
