### ISSUE TITLE
Microsoft.Azure.CognitiveServices.Vision.ComputerVision - v3.X support

### ISSUE THREAD

**Issue by AlexGilliland** [Azure/azure-sdk-for-net#17482]
**Query/Question**
Is there an ETA as to when the ComputerVision SDK will support alternate endpoints? The latest version when building the URL isn't supported by on-prem containers.

```
// ComputerVisionClient.cs
// Construct URL 
            var _baseUrl = BaseUri;
            var _url = _baseUrl + (_baseUrl.EndsWith("/") ? "" : "/") + "ocr";
            _url = _url.Replace("{Endpoint}", Endpoint);
            List<string> _queryParameters = new List<string>();
```

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.CognitiveServices.Vision.ComputerVision  6.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): On-prem docker containers
 - IDE and version : [e.g. Visual Studio 16.3] VS 16.8.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by SaurabhSharma-MSFT** [comment]
@AlexGilliland Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .
