### ISSUE TITLE
[Perf, Stress] Allow test framework environment to specify token credentials

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#17480]
Tracking bug to follow-up on discussion in PR #17453.

pakrym - Should we use the token credential instead?
jsquire - These are not executed in the test environment currently; we're not guaranteed to have a principal created and configured. Given that connection strings are the more common customer experience, it makes sense to use this approach from that perspective as well. Was there a benefit that you had in mind to having the credential used instead?
pakrym - Mostly because it avoids having to compose connection strings and in general seems easier if you have the test environment ofcourse.
Mohit-Chakraborty - Tabling this for now. Will revisit when we have a test environment set up for perf tests.

**Comment by JimSuplizio** [comment]
Hi @Mohit-Chakraborty, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
