### ISSUE TITLE
[Microsoft.Azure.ServiceBus] Failed to retreive session ID from broker. Please retry

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-sdk-for-net#17481]
**Describe the bug**
Use ServiceBus Topics with Session enabled. Got the following error on consuming events:

> Failed to retreive session ID from broker. Please retry

What does it error mean? Is it documented somewhere?
How to avoid that error?

**Expected behavior**
No errors

**Actual behavior (include Exception or Stack Trace)**

> Failed to retreive session ID from broker. Please retry

> Microsoft.Azure.ServiceBus.ServiceBusException: Failed to retreive session ID from broker. Please retry.
>    at Microsoft.Azure.ServiceBus.SessionClient.AcceptMessageSessionAsync(String sessionId, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.SessionReceivePump.SessionPumpTaskAsync()
> 

**To Reproduce**
```
var options = new SessionHandlerOptions(ExceptionReceivedHandler)
{
                MaxConcurrentSessions = _options.MaxConcurrentCalls,
                AutoComplete = true
};
SubscriptionClient.RegisterSessionHandler(async (session, message, ct) => await messageHandler(message), options);
```

Environment:

Microsoft.Azure.ServiceBus 4.1.3
Hosting platform or OS: docker Linux container

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@Marusyk , can you try by changing the below 
```csharp
SubscriptionClient.RegisterSessionHandler(async (session, message, ct) => await messageHandler(message), options);
```

to

```csharp
SubscriptionClient.RegisterSessionHandler(async (message, ct) => await messageHandler(message), options);
```

and try it?

**Comment by Marusyk** [comment]
@axisc 

I got compile time error

> Delegate 'Func<IMessageSession, Message, CancellationToken, Task>' does not take 2 arguments

when change to 
`SubscriptionClient.RegisterSessionHandler(async (message, ct) => await messageHandler(message), options);`

**Comment by axisc** [comment]
ah, my apologies. my recommendation was incorrect, the async method should include `session` as one of the parameters.

The specific error means that the application is trying to receive messages on a session which has no more messages on it. When such an error is seen, the session can be abandoned and the program should accept the next session.

**Comment by axisc** [comment]
@Marusyk  - do let us know if you have more follow up questions. If not, I'll proceed to close this issue.

**Comment by Hatallia** [comment]
The same error is for Microsoft.Azure.ServiceBus 4.1.1.0, Azure Service Bus has a topic with Session enabled. Topic has several subscriptions, and subscribers are in-process Azure functions. Azure functions SDK version is 3.7.1.0. Exception seems to be the same as mentioned above, but it is reported from Azure functions side:

Microsoft.Azure.ServiceBus.ServiceBusException at Microsoft.Azure.ServiceBus.SessionClient+<AcceptMessageSessionAsync>d__37.MoveNext

Failed to retreive session ID from broker. Please retry.

Is there anything that can be done to fix that? it seems, Azure functions have started to throw exceptions recently, although there were not significant changes of custom code base or infrastructure.
