### ISSUE TITLE
Remove hardcoded region in FR test-resources.json

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#17486]
Currently, the FR `test-resources.json` is [assigning location](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/test-resources.json#L14) to `canadacentral` because of a service request.
This is causing that when running the weekly tests, the Canary region is still `canadacentral` so not really coverage there.

Is there another way to ask for a specific region for public builds?

Build as example: https://dev.azure.com/azure-sdk/internal/_build?definitionId=2024&_a=summary

**Comment by kinelski** [comment]
Issue is not present anymore. Closing this.
