### ISSUE TITLE
[BUG] Azure.Storage.Queues.QueueClient builds invalid queue URI from SAS connection string

### ISSUE THREAD

**Issue by mikamins** [Azure/azure-sdk-for-net#17493]
**Describe the bug**
The Azure.Storage.Queues.QueueClient constructor builds an invalid queue URI from a SAS connection string, causing queue operations to fail with 403 AuthenticationFailed

**Expected behavior**
I expect QueueClient to build a valid queue URI from a SAS connection string.

**Actual behavior (include Exception or Stack Trace)**
After constructing a QueueClient from a SAS connection string, queue operations fail with 403 AuthenticationFailed errors indicating "Signature did not match"
```
    Azure.RequestFailedException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
    RequestId:4d117c3a-1003-005c-4743-d04998000000
    Time:2020-12-12T05:01:26.7469698Z
    Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
    ErrorCode: AuthenticationFailed
    
    Additional Information:
    AuthenticationErrorDetail: Signature did not match. String to sign used was stgcytestsfarc01
    rwdxftlacup
    bfqt
    sco
    2020-12-12T04:44:04Z
    2020-12-13T04:44:04Z
    
    
    2019-12-12
    
    
    Headers:
    x-ms-request-id: 4d117c3a-1003-005c-4743-d04998000000
    x-ms-error-code: AuthenticationFailed
    Content-Length: 517
    Content-Type: application/xml
    Date: Sat, 12 Dec 2020 05:01:26 GMT
    Server: Microsoft-HTTPAPI/2.0
```

**To Reproduce**
In the example below, I've generated a SAS connection string from Storage Explorer, and hand-crafted a queue URI from that connection string.  Using the QueueClient created from the URI works as expected. Using the QueueClient created from the connection string fails with the 403.

```
    public async Task TestAsync()
    {
        var connectionString =
            "SharedAccessSignature=sv=2019-12-12&ss=btqf&srt=sco&st=2020-12-12T04%3A44%3A04Z&se=2020-12-13T04%3A44%3A04Z&sp=rwdxftlacup&sig=(redacted);BlobEndpoint=https://myaccount.blob.core.windows.net/;FileEndpoint=https://myaccount.file.core.windows.net/;QueueEndpoint=https://myaccount.queue.core.windows.net/;TableEndpoint=https://myaccount.table.core.windows.net/;";
        var uri =
            "https://myaccount.queue.core.windows.net/test-queue?sv=2019-12-12&ss=btqf&srt=sco&st=2020-12-12T04%3A44%3A04Z&se=2020-12-13T04%3A44%3A04Z&sp=rwdxftlacup&sig=(redacted)";

        // succeeds
        var uriClient = new QueueClient(new Uri(uri));
        await uriClient.SendMessageAsync("foo");

        // fails with 403
        var connectionStringClient = new QueueClient(
            connectionString,
            "test-queue");
         await connectionStringClient.SendMessageAsync("bar");
    }
```

The URI built from the SAS connection string in the QueueClient constructor is:
```
https://myaccount.queue.core.windows.net/test-queue?sv=2019-12-12&ss=bfqt&srt=sco&st=2020-12-12T04%3A44%3A04Z&se=2020-12-13T04%3A44%3A04Z&sp=rwdxftlacup&sig=(redacted)
```

The `ss=bfqt` in the URI does not match the value in the supplied connection string `ss=btqf`. The reordering within the `ss` parameter seems to be responsible for the issue.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Queues 12.5.0
 - Hosting platform or OS and .NET runtime version: Windows 10 .NET Framework 4.7.2
 - IDE and version : Visual Studio 16.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @mikamins, I can reproduce this issue.  We will work to get a fix out soon.

**Comment by mikamins** [comment]
Thanks, @seanmcc-msft

**Comment by amnguye** [comment]
Hi sorry for the lack of update. I'm trying to figure out the difference between the SAS that's working correctly and not. Currently when I try to reproduce your scenario, neither one is giving me success. Also the speculation of `ss=btqf` being reordered is not the source of the problem. I tried it unordered and it works fine. 

Give me a second to get a mitigation snippet and further look into this issue. Thanks for your patience.

**Comment by mikamins** [comment]
I've confirmed that the corruption of the `ss` parameter by QueueUriBuilder is the root cause. I built the SDK with the attached patch, [queue-uri-sas-fix.txt](https://github.com/Azure/azure-sdk-for-net/files/6016909/queue-uri-sas-fix.txt), and it fixes the authorization issue in our application.

This patch is localized to QueueUriBuilder and ensures that the SAS information provided by the user is not corrupted. The modified unit test fails without the bug fix, but passes with it. Please consider something like this as a short-term fix, as this bug is a blocker for my team meeting our semester goals. Thanks!

**Comment by mikamins** [comment]
@amishra-dev, @amnguye, @seanmcc-msft, Any updates here? It's been close to 5 months, and we still cannot connect to a queue using a connection string. This doesn't feel acceptable for such a fundamental issue.

We are a large customer who performs close to 100 billion queue operations per month. Until this is fixed we will not be able to break our dependency on the old SDK. Please let us know where this stands

**Comment by kasobol-msft** [comment]
[Azure.Storage.Common 12.7.2](https://www.nuget.org/packages/Azure.Storage.Common/12.7.2) shipped with a fix. Updating this package alone should resolve the problem.
