### ISSUE TITLE
Passing in an object to DeploymentProperties.Parameters fails to serialize and results in ARM deployment rejection

### ISSUE THREAD

**Issue by wgraham17** [Azure/azure-sdk-for-net#1749]
Creating an Azure Resource Manager Deployment by specifying the parameters as an object in the request results in the parameters being dropped from serialization:

```
deployment.Properties = new DeploymentProperties
{
    Mode = DeploymentMode.Incremental,
    TemplateLink = new TemplateLink("[redacted]"),
    Parameters = new
    {
        diskStorageAccountName = "value",
        imageVhdPath = "value",
        virtualNetworkName = "value",
        virtualNetworkSubnetName = "value",
        vmName = value,
        vmAdminUserName = "value",
        vmAdminPassword = "value"
    }
};
```

generates the following request:

```
PUT https://management.azure.com/subscriptions/[redacted]/resourcegroups/[redacted]/providers/Microsoft.Resources/deployments/gameserver?api-version=2014-04-01-preview HTTP/1.1
x-ms-client-request-id: [redacted]
accept-language: en-US
Authorization: [redacted]
User-Agent: Microsoft.Azure.Management.Resources.ResourceManagementClient/3.0.0.0
Content-Type: application/json; charset=utf-8
Host: management.azure.com
Content-Length: 200
Expect: 100-continue

{
  "properties": {
    "templateLink": {
      "uri": "[redacted]"
    },
    "parameters": {},
    "mode": "Incremental"
  }
}
```

which results in a 400 result in the status, as parameters are missing from the request.

**Comment by wgraham17** [comment]
I also tried the following, attempting to mirror the actual params file:

```
deployment.Properties = new DeploymentProperties
{
    Mode = DeploymentMode.Incremental,
    TemplateLink = new TemplateLink("[redacted]"),
    Parameters = new
    {
        diskStorageAccountName = new { value =  "value" },
        imageVhdPath = new { value =  "value" },
        virtualNetworkName = new { value =  "value" },
        virtualNetworkSubnetName = new { value =  "value" },
        vmName = new { value =  "value" },
        vmAdminUserName = new { value =  "value" },
        vmAdminPassword = new { value =  "value" }
    }
};
```

Same result. Inspecting the request in Fiddler shows that parameters remains an empty object.

**Comment by wgraham17** [comment]
I think something is wonky around line 700 of https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Resource/ResourceManagement/Generated/DeploymentOperations.cs

as I am not sure why it would attempt to JObject.Parse an object (not a string).

**Comment by ravbhatnagar** [comment]
We should support strongly typed objects for parameter and template. For now, can you please try passing in the params like below and see if it works for you -
 string parameterJsonString = @"{
                                     'siteName': {
                                     'value': 'ravdotnetws2'
                                     },
                                     'hostingPlanName': {
                                     'value': 'ravHp4444'
                                     },
                                     'siteLocation': {
                                     'value': 'westUS'
                                     }
                                     }";
            JObject parameters = JObject.Parse(parameterJsonString);
deployment.Properties = new DeploymentProperties
            {
                Mode = DeploymentMode.Complete,
                Template = templateFileContent,
                Parameters = parameters
            };

**Comment by blumu** [comment]
There is a design issue with the API. This API is expecting a JObject from version 6.0 of JSon.net as input to the template parameter. If you program uses a more recent version of JSon.net (e.g. 8.0) the call will fail with the following error:

	'Error reading string. Unexpected token: StartArray. Path 'properties.template.$schema', line 4, position 19.'.

**Comment by fabsenet** [comment]
this issue is over two years old and I still struggle with it today. I found no other sources on the web and I have no idea how others are doing this. There should be a .Net-way of providing parameters but there isn't.

I created the working json parameters string from objects in this way to mirror the json parameters template file:

```cs
var parametersObject = new
{
    myParam1 = new { value = "abc" },
    myParam2 = new {value = "def" },
    command3 = new { value = "aaa" }
};

var parametersJson = JsonConvert.SerializeObject(new { parametersObject });```

**Comment by adrianhall** [comment]
My apologies for this taking so long.  Is this still an issue?
