### ISSUE TITLE
Using .NET SDK for Front-door and APIM

### ISSUE THREAD

**Issue by hem-sharma** [Azure/azure-sdk-for-net#17499]
**Query/Question**
1. I'm exploring Microsoft.Azure.Management.FrontDoor 3.0.0 for .NET Core, Is it okay to use this for managing front-end endpoints addition, creating routing rules and even creating a new front door?
2. is there any other package to manage APIM subscription, users & products?

I created a utility for common operation using .NET SDK (Microsoft.Azure.Management.Fluent, Microsoft.Azure.Management.ResourceManager.Fluent) which is working perfectly for storage accounts.

**Environment:**
```xml
    <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.36.1" />
    <PackageReference Include="Microsoft.Azure.Management.FrontDoor" Version="3.0.0" />
    <PackageReference Include="Microsoft.Azure.Management.ResourceManager.Fluent" Version="1.36.1" />
```
 - Windows 10 .NET Core V3
 - IDE and version : [e.g. Visual Studio 16.8.3]

Quick response is highly appreciated, thanks.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by SaurabhSharma-MSFT** [comment]
@hem-sharma Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .

**Comment by hem-sharma** [comment]
@SaurabhSharma-MSFT Yes, I am not using it as of now but can you shed some light on the SDK usage in gerneral to manage azure resources.
