### ISSUE TITLE
[Flaky Test] net - textanalytics - tests-weekly

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#17502]
This test has been failing often recently:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=652668&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=652794&view=results

**Comment by maririos** [comment]
Thanks @annelo-msft . This is a dup of https://github.com/Azure/azure-sdk-for-net/issues/17483
