### ISSUE TITLE
Types missing at Microsoft.Azure.Management.Compute.Fluent.Models VirtualMachineSizeTypes

### ISSUE THREAD

**Issue by jaaktammtpt** [Azure/azure-sdk-for-net#17510]
**Describe the bug**
Please provide the description of issue you're seeing.
I want to update vm to Standard E16-4s_v3  and Standard E8-4s_v3, but sizes are not in class. 

**Expected behavior**
What is the expected behavior?
All azure vm types should be in class 

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Not all vm sizes are seletable

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.Compute.Fluent 1.36.1
 - IDE and version : Visual Studio 16.8.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by avirishuv** [comment]
I'll take a look at this issue and provide an update

**Comment by avirishuv** [comment]
hi @jaaktammtpt would you mind sharing the steps you are using to update the VM size? Also, are you facing this issue in one particular region / subscription, or is this across multiple regions / subscriptions?

**Comment by Drewm3** [comment]
VM Sizes need to be entered as strings. The list of enumerated sizes in the SDK are not longer being maintained by the Azure compute team.
