### ISSUE TITLE
[WebJobs/EventHubs] Migrate initial offset configuration feature

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17521]
https://github.com/Azure/azure-functions-eventhubs-extension/pull/79 was merged after our initial migration.

**Comment by JoshLove-msft** [comment]
This feature relies on the [InitialOffsetProvider](https://github.com/Azure/azure-sdk-for-net/blob/2b594335737a65cb8f36543ef817deaba5c43f4b/sdk/eventhub/Microsoft.Azure.EventHubs.Processor/src/EventProcessorOptions.cs) option in EventProcessorOptions, which isn't available in Track 2. @jsquire do you know why this wasn't included for Track 2? Any objections to including it now, or is there another hook that we can use? I think this is where we need to update to read the InitialOffset if there are no checkpoints - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L1365

**Comment by JoshLove-msft** [comment]
Nevermind, I see that we have the DefaultStartingPosition property in Track 2.
