### ISSUE TITLE
The way of storage queue endpoint constructed in Azure SDK for net doesn't support use in azurite

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-net#17522]
**Error Description:**
[Azurite](https://github.com/Azure/Azurite) is an Azure Storage emulator. 
Current endpoint which is constructed in azure sdk for net can not access azurite. The reason is the storage queue endpoint for Azurite is different from the one of an Azure storage account.
In Azurite, storage queue endpoint constructed is shown as following:
```
https://127.0.0.1:10001/<account-name>/<resource-path>
```
In Azure SDK for net, storage queue endpoint constructed is shown as following:
```
https://<account-name>.queue.core.windows.net/<resource-path>
```

**Error Track:**
The code for storage queue endpoint constructed in Azure SDK for net is [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/src/Shared/StorageConnectionString.cs#L927)
![Screenshot 2020-12-15 094914](https://user-images.githubusercontent.com/20970631/102157647-d1d26d80-3eba-11eb-8f7e-89b01cce1b2c.png)

**Expected Behavior**
Storage queue endpoint which is constructed in azure sdk for net can access azurite.

@jongio for notification.

**Comment by v-xuto** [comment]
azsdk-azurite

**Comment by v-xuto** [comment]
@scottaddie, @AlexGhiondea, @kyle-patterson, @tg-msft, @amishra-dev Do you have any ideas or plans to fix this issue?

**Comment by JimSuplizio** [comment]
Hi @zzhxiaofeng, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
