### ISSUE TITLE
[QUERY] How to set Blob Content type on the new SDK for files already stored?

### ISSUE THREAD

**Issue by yukumura** [Azure/azure-sdk-for-net#17533]
**Query/Question**
How to set Blob Content type on the new SDK for files already stored?

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.7.0.0
 - Hosting platform or OS and .NET runtime version:  Windows 10 .NET Framework 4.7.2
 - IDE and version : Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @yukumura,

You can set the blob content type like this:

```
BlobServiceClient serviceClient = new BlobServiceClient(connectionString);
BlobContainerClient containerClient = serviceClient.GetBlobContainerClient("name of container");
BlobClient blobClient = containerClient.GetBlobClient("name of blob");
Response<BlobProperties> propertiesResponse = await blobClient.GetPropertiesAsync();
BlobHttpHeaders httpHeaders = new BlobHttpHeaders
{
    ContentType = "desired content type",
    ContentHash = propertiesResponse.Value.ContentHash,
    ContentEncoding = propertiesResponse.Value.ContentEncoding,
    ContentLanguage = propertiesResponse.Value.ContentLanguage,
    ContentDisposition = propertiesResponse.Value.ContentDisposition,
    CacheControl = propertiesResponse.Value.CacheControl
};
await blobClient.SetHttpHeaders(httpHeaders);
```

Note that is if you don't preform the `GetPropertiesAsync()` request and set the existing `ContentHash`, `ContentEncoding`, `ContentLanguage`, `ContentDisposition`, and `CacheControl` in the `BlobHttpHeader`, the existing values will be wiped out.

-Sean
