### ISSUE TITLE
[FEATURE REQ] Expose allowBlobPublicAccess property in StorageAccount

### ISSUE THREAD

**Issue by GalPillar** [Azure/azure-sdk-for-net#17536]
**Library or service name.**
Azure.ResourceManager.Storage
 
**Is your feature request related to a problem? Please describe.**
When using the new unified sdk for storage account (Azure.ResourceManager.Storage), if you fetch a storage account, the property allowBlobPublicAccess in StorageAccount isn't parsed and exposed via the sdk, even though it is returned in the json response from the api.
I realize that the solution will probably be to generate the code based on the updated api in the next release, but the real question is when will that next release come? I would love to get a rough estimate if you can give me one.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nisha-bhatia** [comment]
@GalPillar Could you please provide your request and responses that show the error?

**Comment by GalPillar** [comment]
I think you might have misunderstood me, there are no errors, the sdk simply doesn't expose that field.
 `client.StorageAccounts.ListAsync()` returns a `StorageAccount` object, which in version 1.0.0-preview.2 doesn't include a property named `AllowBlobPublicAccess`

**Comment by nisha-bhatia** [comment]
Thank you for your feedback. AllowBlobPublicAccess is in the Swagger, but is not seen in the generated code. Routing to service team.

**Comment by blueww** [comment]
@allenjzhang , @nisha-bhatia 
Would you please clarify :  who's the owner of "Azure.ResourceManager.Storage"?

For storage team, we owned the storage mgmt plane SDK: [Microsoft.Azure.Management.Storage](https://www.nuget.org/packages/Microsoft.Azure.Management.Storage/), and it DO support "allowBlobPublicAccess" from version 17.1.0.

**Comment by GalPillar** [comment]
Just to clarify, the Azure.ResourceManager.Storage are a part of the new azure unified sdk, you can find details on your own repo's Readme. 
Regarding the issue, I'm kind of concerned that no one is assigned, and it seems like this this is going to go unnoticed...

**Comment by jsquire** [comment]
Not sure why Allen was unassigned;  reassigning for triage.

**Comment by nisha-bhatia** [comment]
Re-routing to another team member feedback. Response might be delayed due to holidays. Thank you.

**Comment by allenjzhang** [comment]
Hi, @GalPillar, thank you for your question. We are in the process of improving the API surface for track 2 SDK (Azure.ResourceManager.xx). These preview SDKs will be updated with new API previews to the newer REST API spec in a few months' time. I don't have an accurate timeline at this point, but it would be safe to assume before June this year.

**Comment by GalPillar** [comment]
Thanks for the reply!!!
