### ISSUE TITLE
Azure SDK diagnostics - xUnit test output when using Azure.Messaging.ServiceBus

### ISSUE THREAD

**Issue by cosminstirbu** [Azure/azure-sdk-for-net#17530]
**Query/Question**

In our automated tests we are using `Azure.Messaging.ServiceBus` to create test subscriptions, listen for messages and then tear down the subscriptions.

Part of running our tests we want to capture the diagnostics / logs emitted by `Azure.Messaging.ServiceBus` clients.

We're using `public AzureEventSourceListener(Action<EventWrittenEventArgs, string> log, EventLevel level)` to redirect the logs to `Xunit.Abstractions.ITestOutputHelper`.

However, our tests run in parallel and so far we can't seem to find an approach to "filter" the logs emitted by `AzureEventSourceListener` in order for test output to contain only the output related to that specific test.

Each test creates its own instances of `ServiceBusAdministrationClient`, `ServiceBusClient`, `ServiceBusReceiver` - however it's not clear how to filter and include only the logs emitted by these instances.

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.ServiceBus 7.0.0
 - Hosting platform or OS and .NET runtime version

```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

```
 - IDE and version : Visual Studio Version 16.8.3

**Comment by JoshLove-msft** [comment]
Hi @cosminstirbu, is each test targeting a different Queue/Topic/etc? Or do you have multiple tests targeting the same entity that you need to filter?

**Comment by cosminstirbu** [comment]
The tests clone "production" subscriptions so they can verify the rules of those subscriptions.

Multiple tests can clone the same "production" subscription but each test will use a unique name for the clone subscriptions.

Basically each tests creates, receives on and deletes its own clone subscription.

We've ended up filtering the logs by the clone subscription name, since it's unique per tests and most log messages include the subscription name.

This works for most cases, but if the clients emit log messages that dont't contain the subscription name then those messages won't be logged.

Not sure if there is a better way to filter the log messages.

**Comment by JoshLove-msft** [comment]
That was where I was heading. The log messages that are related to subscriptions should have the subscription name in them. Operations with ServiceBusClient, which is not specific to a topic, subscription, or queue, but rather the overall namespace, wouldn't include the subscription name in the messages.
