### ISSUE TITLE
ImageAnalysisSkill and read only collection

### ISSUE THREAD

**Issue by snapfisher** [Azure/azure-sdk-for-net#17534]
**Query/Question**
For the ImageAnalysisSkill class, per Issue #11712, the VisualFeatures collection has been made read only.  However, according to the ImageAnalysisSkill documentation here: https://docs.microsoft.com/en-us/azure/search/cognitive-search-skill-image-analysis
This field is supposed to be used to select the feature returned.  Now you can no longer select?  How is this supposed to work?

Thx.

**Environment:**
All.  Azure.Search.Documents.Indexes.Models namespace

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by tg-msft** [comment]
You can use [list initializer syntax](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#collection-initializers) like `new ImageAnalysisSkill { VisualFeatures = { ... } }` or call `IList.Add` on `VisualFeatures` to provide values.

**Comment by snapfisher** [comment]
Thanks.
