### ISSUE TITLE
InheritDoc errors do not consistently fail the build

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17548]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=653592&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=45862c6e-83c5-515f-73e2-e7009eff9f9b

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=655334&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=45862c6e-83c5-515f-73e2-e7009eff9f9b

The same error was produced in both build but only one failed.

cc @maririos I think this is what you've hit as well.

cc @christothes

**Comment by maririos** [comment]
Yeah, I was actually looking into this. And after [re-trying](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=655334&view=logs&j=7e6a3fb7-dbfe-5169-4db8-92b72295ba6c&t=36b11785-bc7b-5bc8-300a-2691a3c072c2) the failed job, it passed.

Same is true for KeyVault:
- Failed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=653643&view=results
- Passed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=655397&view=results
