### ISSUE TITLE
[Perf, Stress] Support a --quiet mode for perf tests

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#17541]
Info from 'Warmup' and 'Run' steps can be suppressed with only the final ops/sec printed at the end. This would not result in any loss of info and would make for cleaner output.

**Comment by JimSuplizio** [comment]
Hi @Mohit-Chakraborty, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
