### ISSUE TITLE
[Perf] Add feature for tests to log warnings or other metrics

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#17556]
The Perf framework should expose a feature to log warnings or other metrics.  As an example, occasional retries are expected when running a perf test against a live service, but a high number of retries is a sign of a problem.  Ideally, the results of a perf test would include both the number of operations per second, plus the number of retries (absolute and percentage of operations).

**Comment by JimSuplizio** [comment]
Hi @mikeharder, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
