### ISSUE TITLE
[WebJobs/EventHubs] Checkpoint container should be created automatically

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17552]
Track 1 did it on start, we should as well.

**Comment by jsquire** [comment]
Please be aware that the Event Hubs library does not do this by design to ensure that it can be run with only read/write permissions.   When making this change, please limit it to the Functions scope.

**Comment by pakrym** [comment]
I'm OK doing this change in functions only but wanted to get more context on why the main library can't offer the same behavior.

Let's take 2 cases:
1. Container exists - if we detect that container is available we don't try to create anything.
2. No container - in this case, we try to create it. If there are not enough permissions we fail but we would've failed anyway.


What am I missing?

**Comment by jsquire** [comment]
Callers own the responsibility of creating the blob storage client before passing it to the processor.  Creating the container via `CreateIfNotExists` is a single line of code and makes the behavior of the application clear and explicit.  I would prefer not to introduce non-deterministic behavior based on the presence or absence of permissions - which may or may not be intended by the developer.    Did they think they were passing us an existing container?  Did they intend to create a new one?

I don't believe that the additional call for creating the container blocks adoption or hinders usability, which leaves the implicit behavior as just a tiny bit of convenience that I don't believe is justified against the concerns.  I'm not strictly opposed, but would want to gate this behind an option to allow developers the ability to be explicit about their intent.

Another consideration is that this would change the approach and design agreed upon by the feature team; the behavioral change (and any accompanying option) would need to be championed across languages and consensus reached.   Finally, we'd need to be sure that the architects do not see this as a behavioral breaking change, though we can easily mitigate that using the option's default value, if need be.

**Comment by pakrym** [comment]
> Did they think they were passing us an existing container? Did they intend to create a new one?

Does it matter though? They wanted the checkpointing to work with the provided container. There is no useful behavior processor has when a non-existent container is passed in.

I don't think the requirement of the extra line is too bad just wanted to understand the concern with the simplified approach.

**Comment by jsquire** [comment]
In some environments, yes.  For example, many enterprise and validated environments require a deep understanding of resources, permissions to them, and inclusion/details in documentation upfront.   

In production and (hopefully) UAT environments, developers will often be provided with credentials without "manage" rights where an exception would present itself.   In development and integration environments, its common for developers to control resources and have extended permissions.  The lack of parity in the environment combined with the implicit creation results in inconsistent behavior across environments and friction for development.   

The counterpoint to that is "well, they're giving us a container name so shouldn't there be an understanding" - which seems reasonable but is often not the case in the real world.  There are some who will not have an understanding of storage, provide a name and assume that behavior will be the same across environments.

**Comment by pakrym** [comment]
>hey will not discover the "problem" until their application development is far enough along to go into a controlled environment and then have to troubleshoot the issue and try to understand why the behavior differs.

But the same can be said about the `container.CreateIfNotExists()` call they manually put in their code. Or about the other permissions like blob write access that are also required to get things working.

**Comment by jsquire** [comment]
Yes, but the principal of "prefer explicit over implicit" applies.   We can't solve the problem for all cases, we can just make sure that the problem is discovered early and there's an explicit code path within the application that can be traced to the behavior, rather than having to drill into documentation and examples for the client library.  

If you feel strongly, I'm not strongly opposed so long as its an option.   I'll let you champion the feature to Ramya for consideration across the team.  😄
