### ISSUE TITLE
[WebJobs/EventHubs] Figure out if RuntimeInformation is being logged correctly

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#17557]
The [RuntimeInformation ](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Listeners/EventHubListener.cs#L269-L277) is only logged when the processor is still open as part of Checkpointing and Close, but it doesn't seem to be deterministic. We should figure out whether this can be made deterministic and add tests.

**Comment by pakrym** [comment]
@JoshLove-msft  does this still make sense?
