### ISSUE TITLE
TestPipeline parameter should be removed from the template ci.yml

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17569]
We already have a few instances of partners copying the template without realizing the parameter should be removed: https://github.com/Azure/azure-sdk-for-net/search?l=YAML&q=TestPipeline

I think it can be auto-calculated based on the `template` service name.

cc @chidozieononiwu @weshaggard @benbp

**Comment by chidozieononiwu** [comment]
auto-calculating parameter values does not work for yaml. Perhaps we could use add a comment indicating that it should be removed when used in a not template pipeline.

**Comment by pakrym** [comment]
Can we base [this](https://github.com/Azure/azure-sdk-for-net/blob/e88652129c13a5e0bd9384979070e2dba023e567/eng/pipelines/templates/jobs/archetype-sdk-client.yml#L38) condition on the artifact name?

**Comment by chidozieononiwu** [comment]
> Can we base [this](https://github.com/Azure/azure-sdk-for-net/blob/e88652129c13a5e0bd9384979070e2dba023e567/eng/pipelines/templates/jobs/archetype-sdk-client.yml#L38) condition on the artifact name? Or ServiceDirectory?

Yes we can. But we also need it for [here](https://github.com/Azure/azure-sdk-for-net/blob/e88652129c13a5e0bd9384979070e2dba023e567/eng/pipelines/templates/stages/archetype-net-release.yml#L172)

**Comment by pakrym** [comment]
Let's keep it open until we fix occurrences in the C# repo
