### ISSUE TITLE
[WebJobs/ServiceBus] Adapt configuration option names if they change

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17568]
See https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Config/EventHubWebJobsBuilderExtensions.cs#L39-L83

and 

https://github.com/Azure/azure-sdk-for-net/pull/17416

**Comment by jsquire** [comment]
Closing, as the referenced PR has merged.
