### ISSUE TITLE
Blob Sdk OpenReadAsync() and DownloadAsync()

### ISSUE THREAD

**Issue by khong33** [Azure/azure-sdk-for-net#17572]
Hello I'm trying to upload the blob zip file into azure. 

Currently I was using DownloadAsync() to fetch the stream and upload that into a separate blob.

```csharp
var response = await new BlobClient(new Uri(sasUri)).DownloadAsync(cancellationToken);
            using (ZipArchive archive = new ZipArchive(response))
            {
                foreach (ZipArchiveEntry entry in archive.Entries)
                {
                    BlobClient blobClient = _blobServiceClient.GetBlobContainerClient(containerName).GetBlobClient($"{buildVersion}/{entry.FullName}");
                    using (var fileStream = entry.Open())
                    {
                        await blobClient.UploadAsync(fileStream, true, cancellationToken).ConfigureAwait(false);
                    }
                }
            }
```

However this doesn't work b/c the stream is over 2gb.

I'm trying to use:

```csharp
var response = await new BlobClient(new Uri(sasUri)).OpenReadAsync();
```
and wasn't sure if this is the right way. If I do `OpenReadAsync()` and use that stream to `ZipArchive(response)` would that work??

If not is there any suggestion?

Thanks,

Best

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @khong33, what is the `ZipArchive`?

For large files, I recommending doing a streaming download with `BlockBlobClient.OpenReadAsync()`, performing any processing you need to on the resulting stream, and then doing a streaming upload with `BlockBlobClient.OpenWriteAsync()`.

-Sean

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
