### ISSUE TITLE
[Service Bus] Bugs in reference doc contents

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#17578]
In the API reference docs for the new Azure.Messaging.ServiceBus package, we found that 

- we were missing class level docs for [AccessRights](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.accessrights?view=azure-dotnet) and [ServiceBusReceivedMessage](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceivedmessage?view=azure-dotnet)
- the description for [ServiceBusReceivedMessage.CorrelationFilter](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceivedmessage.correlationid?view=azure-dotnet#Azure_Messaging_ServiceBus_ServiceBusReceivedMessage_CorrelationId) says "Gets the **a** correlation identifier"
- missing method docs for `ProcessSessionMessageEventArgs.SetSessionState`
- remarks for ServiceBusMessage.Body needs an update

Found during #16745 by @JoshLove-msft

**Comment by JoshLove-msft** [comment]
It seems like there is a bug in the documentation generation as the ServiceBusMessage.Body property does not have any remarks as of 7.0.0, yet the remarks are present in the docs - https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.body?view=azure-dotnet#remarks

@ramya-rao-a is there someone that can look into this?

**Comment by JoshLove-msft** [comment]
SetSessionState is using InheritDocs which there was an issue with that has been fixed.
