### ISSUE TITLE
[Key Vault] Reference doc nodes nesting is buggy

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#17573]
This is the [Overview for latest.Net API reference docs for all packages](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet). Scroll down to Key vault, expand it and observe the nesting:

- The node `Common` does not lead anywhere and should be removed
- The node `V3` is for the older Key Vault package and should not be appearing under the latest moniker. It should be under `Legacy`
- Side note: Click on the `Overview` or anything under the `Key Vault` node, you will see that the drop down for the Latest/Legacy/Preview disappears

![image](https://user-images.githubusercontent.com/16890566/102303015-1ee02f00-3f0f-11eb-8c0e-be883bcda942.png)

Found during #16730

cc @christothes

**Comment by kurtzeborn** [comment]
This is an issue that library owners should be able to address by following the documentation we've created for these types of issues [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/283/Docs.MS-Primer?anchor=how-do-i-actually-update-the-toc%3F).  Please reach out to @danieljurek or @scbedd if you need assistance.

**Comment by ramya-rao-a** [comment]
Thanks @kurtzeborn 

I have logged a separate issue with the docs team for the last point of the drop down for Preview/Legacy/Latest disappearing

@christothes I believe the files to update are https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-toc/top_level_toc.yml and https://github.com/MicrosoftDocs/azure-docs-sdk-python/blob/783d5692032d0336350d92b635d901d40d882e68/docs-ref-mapping/reference-previous.yml. When you create a PR to fix this, please add @scbedd and @danieljurek as reviewers.

Please see if we can get this fixed in the current milestone. If not, please move it to the March milestone

**Comment by ramya-rao-a** [comment]
@christothes While you can send the PR to remove the `Common` node, please hold off on the work to move the V3 node until https://github.com/Azure/azure-sdk-for-net/issues/17576#issuecomment-771121941 is resolved

**Comment by heaths** [comment]
Moving this to the backlog for now since there's no definite timeline for getting the underlying issue resolved.

**Comment by ramya-rao-a** [comment]
Closing this issue as the `Common` node is gone now. The other two observations are for the generic .NET docs rendering and not something trivial that we can change from our side
