### ISSUE TITLE
[Event Hubs] Reference doc nodes nesting is buggy

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#17576]
This is the [Overview for latest.Net API reference docs for all packages](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet). Scroll down to Event Hubs, expand it and then expand `Event Hubs Client`. Observe the nesting:

- `Event Hubs Processor` is empty
- The node V4 is for the older Event Hubs package and should not be appearing under the latest moniker. It should be under Legacy

![image](https://user-images.githubusercontent.com/16890566/102303816-e3defb00-3f10-11eb-92f8-d80be35b906f.png)

Found during https://github.com/azure/azure-sdk-for-net/issues/16736

cc @jsquire

**Comment by kurtzeborn** [comment]
This is an issue that library owners should be able to address by following the documentation we've created for these types of issues [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/283/Docs.MS-Primer?anchor=how-do-i-actually-update-the-toc%3F).  Please reach out to @danieljurek or @scbedd if you need assistance.

**Comment by ramya-rao-a** [comment]
Thanks @kurtzeborn 

@jsquire I believe the file to update is https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-toc/top_level_toc.yml. When you create a PR to fix this, please add @scbedd and @danieljurek as reviewers.

Please see if we can get this fixed in the current milestone. If not, please move it to the March milestone

**Comment by ramya-rao-a** [comment]
@scbedd and @danieljurek,

Do the latest vs latest monikers and query parameters even work?
Below are links for Event Hubs with legacy and latest query parameters
- https://docs.microsoft.com/en-us/dotnet/api/overview/azure/event-hubs?view=azure-dotnet-latest
- https://docs.microsoft.com/en-us/dotnet/api/overview/azure/event-hubs?view=azure-dotnet-legacy

Both show the same content and same toc tree

Another way of looking at this:
- https://docs.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet is the general landing page for Azure SDK API ref docs for .Net. Select Event Hubs here. This should point to latest SDK docs
- Open https://docs.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet in another page, select "Legacy" from the drop down, and then select Event Hubs here. This should point to legacy SDK docs

Both show the same content and same toc tree

**Comment by jsquire** [comment]
It's worth noting that the hierarchy for Event Hubs seems to match other T2 libraries _(although the naming for the legacy node is inconsistent):_
![6b8caee1-b0f0-4f92-abd6-a747ff40278c](https://user-images.githubusercontent.com/913445/106512092-2481dc00-649f-11eb-8f64-5fe253d3f656.jpg)

![dfb24dc7-1b59-46eb-b2a7-f06dea99a46d](https://user-images.githubusercontent.com/913445/106512243-57c46b00-649f-11eb-96bc-f8837689b7a3.jpg)

![c8021dad-03ee-446a-b02a-806b096d871e](https://user-images.githubusercontent.com/913445/106512260-5bf08880-649f-11eb-87b2-6ed0c85af1d6.jpg)

To Ramya's point.... it seems like there should be a stronger segmentation between the current and legacy generation to avoid confusion.  I think this may be a larger conversation than just following the docs that Scott shared.

**Comment by ramya-rao-a** [comment]
Had a chat with @scbedd and @danieljurek offline. Looks like the moniker problem is a limitation of the docs engineering system for .Net. 

@maggiepint, While doing a git blame on the file, found your commits that did the renames for Event Hubs v4 node and Key Vault v3 node. Do you recall reasons to do so rather than using the package name?

**Comment by jsquire** [comment]
Moving to the backlog, as work is blocked by unclear next-steps.   

//fyi: @ramya-rao-a

**Comment by heaths** [comment]
Has anything changed? #17573 is blocked on this and wondering if I should just close it for now instead of kicking it down the road.

**Comment by scbedd** [comment]
@heaths The core issue with the CI generating all together against a single unified ToC is definitely still present. That is really the core of the issues that I can see with this #17573. 

I'm covering for @danieljurek 's vacation this week, so I don't have exact details of his interactions / ETAs for any .NET improvements that would address that core problem.

All that aside, I am [seeing if I can fix](https://github.com/Azure/azure-docs-sdk-dotnet/tree/feature/processor-host-empty) the empty EventHubs Processor issue. Given the current configuration I definitely don't expect that.

**Comment by scbedd** [comment]
This is resolved now.

![image](https://user-images.githubusercontent.com/45376673/126692895-b978c7cf-5188-400e-b66e-1fc2da332d43.png)

**Comment by scbedd** [comment]
We can't resolve the `V4` node issue until we can split the monikers for .NET.

**Comment by ramya-rao-a** [comment]
Thanks @scbedd!
