### ISSUE TITLE
[Event Hubs] Azure Function regular spikes in event hub write latency

### ISSUE THREAD

**Issue by kamilzzz** [Azure/azure-sdk-for-net#17588]
I'm noticing regular spikes in event hub write latency using Azure Function.

Architecture:
IoT Hub -> Azure Function (preprocess message) -> Event Hub

So basically my Azure Function is listening on IoT Hub, preprocesses events (in-memory, simple deserialization/format change) and then pushes them to Event Hub.

Under heavier load (~100 events/s or more) I can notice regular latency spikes (spike more or less every single minute) on event hub dependencies - up to 3 seconds for single write, where typical latency is about 20 ms.
When the load is lower (let's say 10-20 events/s) spikes also can be observed but latency is lower (below 1s per single write) and intervals are longer.

Event Hub is scaled high enough to accept load (no throttled requests in metrics).
Under heavy load App Service Plan CPU usage is ~15-20%, under smaller load below 10%.

Live metrics during light load:
![metrics](https://user-images.githubusercontent.com/32141632/102385181-d5a2e480-3fcd-11eb-92d4-9b800f4d9e36.gif)

App Insights with spikes from above run:
![spikes](https://user-images.githubusercontent.com/32141632/102385332-03882900-3fce-11eb-83a0-14780eba235c.png)

AI logs from heavier load run:

- Total executions count (1 function execution is 1 event sent to Event Hub): ~270k
![q1](https://user-images.githubusercontent.com/32141632/102386445-5adac900-3fcf-11eb-819d-2bac39a0401e.png)

- Spike more or less every 1 minut
![q2](https://user-images.githubusercontent.com/32141632/102386668-a1c8be80-3fcf-11eb-8d3b-95405ba1f91b.png)

- Event Hub dependency duration distribution
![dd](https://user-images.githubusercontent.com/32141632/102386980-1d2a7000-3fd0-11eb-84a4-871b560d9faa.PNG)

2 years ago similar issue was created but no clear explanation or fix was provided.
https://github.com/Azure/azure-event-hubs-dotnet/issues/316

EventHubProducerClient is reused across all functions executions.
```csharp
var clientOptions = new EventHubProducerClientOptions
{
    ConnectionOptions = new EventHubConnectionOptions
    {
        TransportType = EventHubsTransportType.AmqpTcp
    },
    RetryOptions = new EventHubsRetryOptions
    {
        Mode = EventHubsRetryMode.Exponential,
        TryTimeout = TimeSpan.FromSeconds(10),
        Delay = TimeSpan.FromSeconds(1),
        MaximumRetries = 5
    }
};

_client = new EventHubProducerClient(_options.ConnectionString, clientOptions);
```

Azure Function host.json config:
```json
    "eventHubs": {
      "batchCheckpointFrequency": 8,
      "eventProcessorOptions": {
        "maxBatchSize": 32,
        "prefetchCount": 128,
        "receiveTimeout": "00:01:00",
        "enableReceiverRuntimeMetric": true,
        "invokeProcessorAfterReceiveTimeout": true
      }
    }
```

**Environment:**
 - Azure.Messaging.EventHubs - 5.2.0
 - Microsoft.NET.Sdk.Functions - 3.0.11
 - .NET Core 3.1
 - Function running on P1V3 plan

**Comment by kamilzzz** [comment]
@serkantkaraca I've noticed you were investigating similar problem in older issue (https://github.com/Azure/azure-event-hubs-dotnet/issues/316) and you mentioned 60 sec interval which is what I see also in my case, so I would be glad if you could take a look at it 😄

**Comment by jsquire** [comment]
Hi @kamilzzz.  Thank you for your feedback, and we regret that you're experiencing difficulties.  Thank you for the detailed write-up and context.   There are a few additional things that would be helpful for troubleshooting, if you'd be so kind.

- Is your Function running on a consumption or dedicated plan?  

- How is the Function triggered?  From your description it seems as if you're using the Event Hubs binding to receive from the Event Hub associated with IoT Hub, is that correct?  

- Is your Function consistently active and publishing, is it more occasional, or is the usage more peak-and-valley?

- Can you share the code that you're using to publish events and help me understand how many events are typically being published in a Function invocation and what the rough average size of the event body is?

- Other than publishing, what other tasks is the Function performing and how long does an invocation of the Function normally take?

- Are you willing to collect some ETW logs from the Event Hubs client library?  That will give us insight into what internal operations the client is performing, including the number of retries that the client is using for each attempt to publish.    _(I've added some more information on this below)_

** Event Hubs client logs **

 - Are emitted using an [ETW event source](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Diagnostics/EventHubsEventSource.cs), which a `EventSourceListener` can intercept.   To make this easier, there is a dedicated `AzureEventSourceListener` available in the `Azure.Core` library that will capture all Azure SDK logs.  A [sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md) for its use can be found here.

- We're particularly interested in the log events with ids 3, 4, and 5 - which correspond to publishing.  These have an `operationId` that we can use to correlate them and group retries for a single operation together.

- Assuming that you're using the Event Hubs trigger to receive the IoT Hub events, we'll probably also be interested in its logs to tell us how many partitions are owned and track ownership changes.

**Comment by serkantkaraca** [comment]
@kamilzzz how is this impacting your pipeline? Is it causing some sort of backlog built up?
