### ISSUE TITLE
[FEATURE REQ] Add GetParentClient to DataLake, File Shares, and Queues

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#17589]
In Blobs we added the ability to traverse up the storage client tree (see PR https://github.com/Azure/azure-sdk-for-net/pull/16437)
We should also look to add it to DataLake, File Shares and Queues.

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
