### ISSUE TITLE
Can I Get Scheduled messages by session id?

### ISSUE THREAD

**Issue by JpDotFranca** [Azure/azure-sdk-for-net#17583]
**Azure.Messaging.ServiceBus.**
 
My application need to handle scheduled messages that using session. So, I use the next code to handle this situation today:

```
 await using (ServiceBusClient client = new ServiceBusClient(Constants.AzureQueueNotificationConnection))
            {
                var sessionReceiver = await client.AcceptSessionAsync("queueName", "sessionId");
                var messages = await sessionReceiver.ReceiveMessagesAsync(10);
```
   But using this code don't fetch the scheduled messages. how can I do that?

Thanks is advance.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @JpDotFranca,
You can't actually receive the messages until after the ScheduledEnqueueTime has passed. You can peek the scheduled messages before this time though, but you wouldn't be able to settle the messages in any way.

**Comment by JoshLove-msft** [comment]
I'm going to go ahead and close this issue. @JpDotFranca please reopen if you have further questions!
