### ISSUE TITLE
Can I Get Scheduled messages by request

### ISSUE THREAD

**Issue by JpDotFranca** [Azure/azure-sdk-for-net#17582]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

**Comment by jsquire** [comment]
Hi @JpDotFranca.  This looks to be a duplicate of #17583, so I'm going to close it out.   If I'm mistaken, please feel free to reopen with additional context for discussion.
