### ISSUE TITLE
[FEATURE REQ] Support updating SasToken in storage clients

### ISSUE THREAD

**Issue by johnthcall** [Azure/azure-sdk-for-net#17596]
**Library or service name.**
What library or service is this request related to? Azure.Storage.Common
 
**Is your feature request related to a problem? Please describe.**
In my team there is a partner service which we can request SAS Tokens from. In V11 of the SDK we are able to create a StorageCredential, create a long lived client, and periodically call UpdateSASToken after fetching a new token from the partner service. StorageSharedKeyCredential in V12 has the SetAccountKey method to enable this exact scenario for shared keys.

I looked at creating my own HttpPipelinePolicy to add the SAS token query params to each request but constructors taking these policies are internal, I would have to extend BlobServiceClient to call the protected CreateClient method.

The only other alternative I see is to make a new BlobServiceClient each time a new sas token is fetched and try to enforce that all consumers reference a BlobServiceClient property which will be updated on refresh. In cases where one of the subcomponent only operates on a specific container having to create the BlobContainerClient from the BlobServiceClient is very wasteful. This options is incredibly fragile.

Is there any other alternative or recommended solution for this scenario?

**Comment by tg-msft** [comment]
We'll be adding an AzureSharedAccessSignatureCredential that supports rolling as part of https://github.com/Azure/azure-sdk/issues/1954.

**Comment by johnthcall** [comment]
Thanks @tg-msft, is there any timeline for AzureSasCredential? I understand that it is a big change as it's affecting Azure.Core. Is any help needed in funding this?

**Comment by amnguye** [comment]
Sorry this fell under the radar. Looks like `AzureSasCredential` got added in already as per PR https://github.com/Azure/azure-sdk-for-net/pull/17636
And added into storage here https://github.com/Azure/azure-sdk-for-net/pull/17646
