### ISSUE TITLE
Azure.Messaging.EventHubs Readme issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#17616]
1.
Section [link:](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs#event-hubs-exception)

![image](https://user-images.githubusercontent.com/65581162/102322999-de3def80-3fba-11eb-94ac-d3b65dfd8208.png)

Suggestion:  Update   `EventHubException` to `EventHubsException`.

@jongio for notification.

**Comment by jsquire** [comment]
Fixed by #17816
