### ISSUE TITLE
Azure.DigitalTwins.Core Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#17620]
1.
Section [link:](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/digitaltwins/Azure.DigitalTwins.Core#azure-iot-digital-twins-client-library-for-net)
![image](https://user-images.githubusercontent.com/65581162/102427718-e5154280-404c-11eb-950d-3a880471e6e9.png)
Suggestion: Update link to ' https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/digitaltwins/Azure.DigitalTwins.Core/src '

2.
Section [link:](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/digitaltwins/Azure.DigitalTwins.Core#contributing)
![image](https://user-images.githubusercontent.com/65581162/102428660-50f7ab00-404d-11eb-9016-a16ae1fd34ea.png)
Suggestion:  Add hyperlink for Conduct FAQ  https://opensource.microsoft.com/codeofconduct/faq/

@jongio for notification.

**Comment by azabbasi** [comment]
Thank you for pointing them out.
