### ISSUE TITLE
[BUG] Cannot generate SAS URI from BlobContainerClient created through BlobServiceClient.GetBlobContainerClient

### ISSUE THREAD

**Issue by mikamins** [Azure/azure-sdk-for-net#17626]
**Describe the bug**
A SAS URI cannot be generated from a `BlobContainerClient` obtained through `BlobServiceClient.GetBlobContainerClient`. 

**Expected behavior**
If a `BlobServiceClient` is created from an account key connection string, I expect a `BlobContainerClient` obtained through `BlobServiceClient.GetBlobContainerClient` to be able to generate a SAS URI.

That is, I expect the following test to pass:
```
    [TestMethod]
    public void ContainerClientCanGenerateSasUri()
    {
        var connectionString = "UseDevelopmentStorage=true;";
        var serviceClient = new BlobServiceClient(connectionString);
        var containerClient = serviceClient.GetBlobContainerClient("test");

         // passes as expected
        Assert.IsTrue(serviceClient.CanGenerateAccountSasUri);

         // fails unexpectedly
        Assert.IsTrue(containerClient.CanGenerateSasUri);
    }
```

**Actual behavior (include Exception or Stack Trace)**
In the above example, `containerClient.CanGenerateSasUri` returns false.

**To Reproduce**
1. Create a `BlobServiceClient` from an account key connection string
2. Call `GetBlobContainerClient` on the service client
3. `CanGenerateSasUri` returns false since the `StorageSharedKeyCredential` isn't passed to the container

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.7.0
 - Hosting platform or OS and .NET runtime version: Windows 10 .NET Framework 4.7.2
 - IDE and version : Visual Studio 16.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by berendhaan** [comment]
Ran into the same issue today.

**Comment by seanmcc-msft** [comment]
This bug was fixed in [Azure.Storage.Blobs 12.8.0-beta.1](https://www.nuget.org/packages/Azure.Storage.Blobs/12.8.0-beta.1):
- [Fix to be able to CanGenerateSas and GenerateSas from clients generated GetClient #17232](https://github.com/Azure/azure-sdk-for-net/pull/17232)
- [12.8.0-beta.1 Changelog](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md#1280-beta1-2020-12-07)

-Sean
