### ISSUE TITLE
[QUERY] Storage Queues: Why there are no overloads that accepts CancellationToken only?

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-sdk-for-net#17648]
**Query/Question**

Here's the method signature for `QueueClient.CreateIfNotExists()`:

```c#
public virtual Response CreateIfNotExists(Metadata metadata = default, CancellationToken cancellationToken = default) =>
```
What means `metadata` can be null.

Then why there is no overload:

```c#
public virtual Response CreateIfNotExists(CancellationToken cancellationToken = default) =>
```

So I could write less chatty code:

```c#
await queueClient.CreateIfNotExists(cancellationToken);
```

instead of current

```c#
await queueClient.CreateIfNotExists(cancellationToken: cancellationToken);
```

**Environment:**
 - Name and version of the Library package used:
```
Azure.Storage.Queues 12.5.0
```
 - Hosting platform or OS and .NET runtime version:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
 - IDE and version:
```
Microsoft Visual Studio Enterprise 2019
Version 16.8.3
VisualStudio.16.Release/16.8.3+30804.86
Microsoft .NET Framework
Version 4.8.04084
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
This would require us to redo not just this API, but all of our APIs (across all libraries) for unpretty call for consistency. @seanmcc-msft @tg-msft Not sure if we have any SDK guidelines or suggestions that would prevent us from adding all these overloads.

**Comment by seanmcc-msft** [comment]
I don’t think needed to specify ‘cancellationToken: cancellationToken’ is a major inconvenience.

**Comment by abatishchev** [comment]
Convince/inconvenience is quite subjective so I'd not go there :)
But the overall cost of the maintenance of an API having (numerous) overloads is a good argument in my mind though. Especially when consistency across numerous libraries is added to the mix.

After looking at the overall [API surface of QueueClient](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient?view=azure-dotnet) I see no methods have any overloads. And as you say, that was a design decision.

Is there a public doc explaining the rationale behind this decision? I'd like to learn about it.

**Comment by seanmcc-msft** [comment]
It might be in here - https://azure.github.io/azure-sdk/dotnet_introduction.html

**Comment by abatishchev** [comment]
hi @seanmcc-msft, the article you linked reads as:

>Simple methods should follow standard [.NET Framework Design Guidelines](https://learning.oreilly.com/library/view/framework-design-guidelines/9780135896457/ch05.xhtml) for parameter list and overload design.

>Complex methods should use option parameter to represent the request payload, and consider providing convenience simple overloads for most common scenarios.

The .NET Framework Design Guideline doesn't mention getting rid of overloads, it states quite the opposite:

>Overloading is one of the most important techniques for improving the usability, productivity, and readability of reusable libraries.

So I'm still looking for technical justification for the new design. /cc @JeffreyRichter.

**Comment by JeffreyRichter** [comment]
It is common to have simple overloads for common cases and overloads that take completely different things. But we deem passing a CancellationToken to be NOT common and so the overload that accepts it accepts all parameters. We can't add overloads for all methods that just take a CancellationToken. Some of this is historical with the idioms of C#/.NET.

**Comment by JimSuplizio** [comment]
Hi @abatishchev, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
