### ISSUE TITLE
[FEATURE REQ] Azure.Identity doesn't support AzureServicesAuthConnectionString

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-sdk-for-net#17652]
**Library or service name.**

`Azure.Identity`
 
**Is your feature request related to a problem? Please describe.**

Rather a regression as the old library `Microsoft.Azure.Services.AppAuthentication` did support.

**Problem statement:**

Let's start from the fact that over the years the Managed Identity team refused to provide the support for [local development](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication#local-development-authentication), told to go elsewhere.

The now-legacy library `AppAuthentication` has the built-in fallback mechanism via environment variable `AzureServicesAuthConnectionString` which would be used instead of a managed identity and enable to run the service code locally.

Moreover, the connection string could point to a certificate in the store that marked as non-exportable, see more below.

In the new `Azure.Identity` the support for a connection string is absent.

**Details:**

Currently I'm using [DefaultAzureCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) which by default would fallback to (among others):

- [ManagedIdentityCredential](
https://docs.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet)
- [EnvironmentCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet)

The problem with the latter is that it supports only the following [environment variables](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#environment-variables) in the scope of a certificate:

- AZURE_TENANT_ID
- AZURE_CLIENT_ID
- AZURE_CLIENT_CERTIFICATE_PATH

What means:

1. If the path to a certificate is checked in under the source control then it means it's hard-coded and must be same for every engineer on a 25-person team
2. It must be a pfx what means it's an "open" secret. In the contrast to its imported version in the store which is makers as non-exportable

**Potential workaround (which I don't see would work)**:

I could've used [ChainedTokenCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.chainedtokencredential?view=azure-dotnet) with:
- [ManagedIdentityCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet)
- [ClientCertificateCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.clientcertificatecredential?view=azure-dotnet)

The problem with the latter that it doesn't support lazy loading of a certificate: it must be present at the time of construction. In production the certificate won't be present and [the ctor will throw exception](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/ClientCertificateCredential.cs#L121).

What means that there is no one-fits-all solution that will fallback automatically, I need to manually detect whether the code is running locally or not and use the appropriate subtype of [token credential](https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet). I even potentially can parse the connection string from the environment variable myself. But I rather would prefer the library to do it for me.

**Potential solution:**

- Add a constructor parameter accepting `Func<X509Certificate2> certificateFactory`
- Add a constructor parameter accepting `string thumbprint` and/or `string subjectName`
- Add a constructor parameter indicating lazy loading `bool lazyLoad`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by andyvig** [comment]
My team has the same need with a slightly different use-case.  

**Use-case**
We're connecting to AppConfigService and KeyVault via Azure.Identity in a service deployed to a customer's VM and we're using a certificate to authenticate.

**Goal**
We'd much prefer to use a non-exportable cert in the Windows cert-store than a path to a cert.

**Current workaround**
Our plan is to wire up a ClientCertificateCredential and use that instead of DefaultAzureCredential for this particular host.  
Note that this code is in a shared library that's used across a variety of hosts, and most of those hosts work fine with DefaultAzureCredential.

Our original hope was that DefaultAzureCredential supported environment variables to load from the Windows CertStore, but that doesn't seem to be the case.

**Comment by abatishchev** [comment]
+@schaabs

**Comment by schaabs** [comment]
@abatishchev Thanks for filing this feature request. We have discussed adding support for loading certificates from the certificate store in the past, but we haven't prioritized this as it's a Windows only solution and would require native dependencies to implement in some other languages such as Java. However, the first solution you suggested does provide a way around this by leaving it to the app developer to load the certificate on demand. Let me discuss this with the feature team at our next standup and I'll update / schedule this feature request once I've had a chance to discuss with the other language developers.

**Comment by abatishchev** [comment]
@christothes why was it closed, furthermore as "completed"? I know there is some resistance to ship it as an official feature, but there is also a customer demand for it, being shipped in one way or another. Please reopen.

**Comment by abatishchev** [comment]
@christothes bump.

**Comment by christothes** [comment]
Adjusting the close reason. This will remain closed unless we see some significant demand for it.
