### ISSUE TITLE
[FEATURE REQ] ADF PipelineRunInvokedBy does not return parent PipelineRunId when the InvokedByType is PipelineActivity

### ISSUE THREAD

**Issue by tangdi** [Azure/azure-sdk-for-net#17655]
**Library or service name.**
Azure.DataFactory 
**Is your feature request related to a problem? Please describe.**
I try to build a graph of pipeline runs. However, if a pipeline run is triggered by a parent pipeline run, it is hard to build this link using the SDK.
Using HTTP Rest API I can get the InvokedBy property like
   "invokedBy":{
      "id":"abc",
      "name":"abc",
      "invokedByType":"PipelineActivity",
      _"pipelineName":"Parent Pipeline Name",
      "pipelineRunId":"Parent pipeline run id"_
   },
However, the SDK does not include the parent pipelineRunId in the model.

**Potential solutions:**

- Add the explicit properties in the PipelineRunInvokedBy class and enrich the doc. 
- Add additional properties using JsonExtensionDataAttribute in the PipelineRunInvokedBy class and enrich the doc.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by shawnxzq** [comment]
@LijuanZ Could you please help look into this issue? Thanks!

**Comment by tangdi** [comment]
any feedback?

**Comment by LijuanZ** [comment]
@shawnxzq @tangdi This is caused by the new properties (pipelineName and pipelineRunId) are not added to swagger spec yet. We've created a bug internally to track the fix.

**Comment by tangdi** [comment]
any rollout to fix the Spec and SDK model?

**Comment by LijuanZ** [comment]
@tangdi The bug is not fixed yet. I'll update here when it's done. While waiting for the fix, can you try use rest API as workaround? Sorry about the inconvenience.

**Comment by shawnxzq** [comment]
@LijuanZ We can change the swagger now as it's unblocked, please help on this, thanks!

**Comment by LijuanZ** [comment]
@shawnxzq yes, it's no longer blocked, we'll get to it based on priority

**Comment by shawnxzq** [comment]
@LijuanZ Just a reminder, please share the status of the fix here, thanks!

**Comment by LijuanZ** [comment]
@shawnxzq Thanks for the reminder, I'll update here when it's done.

**Comment by shawnxzq** [comment]
@tangdi This is still being worked on, thanks for your patience on this.

**Comment by shawnxzq** [comment]
@tangdi we are still working on this, and we will have a backlog item to track this, could you mind we can close the issue here? Thanks!

**Comment by shawnxzq** [comment]
Still working one. 
@LijuanZ If we already created backlog items, let me know and we can close the issue here as well, otherwise we need to update the status here monthly, thanks!

**Comment by LijuanZ** [comment]
@shawnxzq this work item is done, swagger change has been checked in for a while: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/datafactory.json#L5820

**Comment by shawnxzq** [comment]
Close the issue now since swagger is checked in and it's already available rest API/SDK.
