### ISSUE TITLE
[Bug] Memory usage when upload file to DataLake gen2

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-sdk-for-net#17665]
**Query/Question**
I'm using Azure.Storage.Files.DataLake to send data every minute from my C# code.

```csharp
public class DataLakeStorage : IFileStorage
{
	private readonly DataLakeServiceClient _dataLakeClient;

	public DataLakeStorage(FileStorageOptions options)
	{
		var sharedKeyCredentials = new StorageSharedKeyCredential(options.AccountName, options.AccountKey);
		_dataLakeClient = new DataLakeServiceClient(new Uri($"https://{options.AccountName}.dfs.core.windows.net"), sharedKeyCredentials);
	}

	public async Task Add(string containerName, string path, string name, object data)
	{
		DataLakeFileSystemClient fileSystemClient = _dataLakeClient.GetFileSystemClient(containerName.ToLower());
		await fileSystemClient.CreateIfNotExistsAsync();

		DataLakeDirectoryClient directoryClient = fileSystemClient.GetDirectoryClient(path);
		DataLakeFileClient fileClient = await directoryClient.CreateFileAsync(name);

		await using var stream = new MemoryStream();
                await JsonSerializer.SerializeAsync(stream, data, data.GetType());
                stream.Position = 0;
                await fileClient.AppendAsync(stream, 0);
                await fileClient.FlushAsync(stream.Length);
	}
}
```
`DataLakeStorage` is registered as a Singleton in web application.
When I start using this code to send data every minute, I got a lot of memory usage of my application (each file ~150 bytes).

App without sending to datalake after 3 days uptime: ~170Mb
App with sending to datalake after 6 hours uptime: ~900Mb

Where can be the issue? Could you please suggest what I'm doing wrong with sending data to datalake?

UPDATE
Also, tried `await fileClient.UploadAsync(stream, overwrite: true);` instaed of 
```
                await fileClient.AppendAsync(stream, 0);
                await fileClient.FlushAsync(stream.Length);
```
and added
```
  <PropertyGroup>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>
```
but the same result. It uses a lot of memory. 

**Environment:**
Package: Azure.Storage.Files.DataLake 12.4.0
App: netcoreapp3.1
OS: Linux in container

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by Marusyk** [comment]
It seems I found the issue.

It was **Application Insights**

I'm using AppInsights with Dependency tracking enabled. There are a lot of operations with Datalake (now it's more than 5000 per hour). After disabled AppInsights, the app using only 96 MB (9-hour uptime).

I'm going to write custom `ITelemetryProcessor` and skip all dependency that related to the Datalake operations.
What would you recommend?

**Comment by Marusyk** [comment]
Actually, after disabling Application Insights it consumes less memory, but

App without sending to datalake after 2 weeks uptime: ~160Mb
App with sending to datalake after 2 weeks uptime: ~460Mb

can it be an issue in Azure.Storage.Files.DataLake package?

**Comment by Marusyk** [comment]
any updates?
I upgraded my application to .NET 5 but it didn't help

**Comment by Marusyk** [comment]
any updates?
I upgraded my application to .NET 5 but it didn't help

**Comment by jsquire** [comment]
Hi @Marusyk.  Unfortunately, I'm only serving as first triage in this case and have no insight into the status of this nor process that the owning team uses for triage.   I'll need to defer to @sumantmehtams and @xgithubtriage for assistance.

**Comment by Marusyk** [comment]
Hi @sumantmehtams and @xgithubtriage 
any comments from your side?
