### ISSUE TITLE
[BUG] No setter for min/max length on TokenLengthFilter in .net sdk

### ISSUE THREAD

**Issue by nokternol** [Azure/azure-sdk-for-net#17662]
**Describe the bug**
In the deprecated Microsoft.Azure.Search you could pass values in the constructor. In the Java sdk it shows a method named setMinLength.
However, in the .NET SDK the properties are readonly, omitted from the constructor AND missing the setMinLength method rendering them unusable.

**Expected behavior**
There should be some way to adjust the min/max values to something other than the default 0 and 300.

**Actual behavior (include Exception or Stack Trace)**
You can create a new Filter but only with the default values for min/max making it impossible to replicate a solution that used them in the older library.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create new TokenLengthFilter
2. Try to set the minLength property

**Environment:**
Azure.Search.Documents 11.1.1
.NET 4.6.1 (.NET Standard) Windows 10
Visual Studio 2019 16.7.7

**Comment by nokternol** [comment]
If needs be I am happy to raise a PR for this as I need it resolved ASAP in order to finish a production migration to this sdk

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team memer best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by nokternol** [comment]
Based on the implementation in the java sdk I think the approach that was taken was as below

`        /// <summary> Set the minLength property: The minimum length in characters. Default is
        /// 0. Maximum is 300. Must be less than the value of max.
        /// </summary>
        /// <param name="minLength"> minLength the minLength value to set. </param>
        /// <returns> the LengthTokenFilter object itself. </returns>
        public LengthTokenFilter setMinLength(int minLength) {
            this.min = minLength;
            return this;
        }

        /// <summary> Set the maxLength property: The maximum length in characters. Default
        /// and maximum is 300.
        /// </summary>
        /// <param name="maxLength"> the maxLength value to set. </param>
        /// <returns> the LengthTokenFilter object itself. </returns>
        public LengthTokenFilter setMaxLength(int maxLength) {
            this.max = maxLength;
            return this;
        }`
        
        Java SDK: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/search/azure-search-documents/src/main/java/com/azure/search/documents/indexes/models/LengthTokenFilter.java
        
        .NET File: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/src/Generated/Models/LengthTokenFilter.cs
        
        Unfortunately I do not have the required .Net Core environment to create a PR for this change myself.
        I also do not have the time to figure out what generates this code and how that works.

**Comment by nokternol** [comment]
I also have no idea how to get github's code block to format properly :D

**Comment by nokternol** [comment]
But then the approach taken in the EdgeNGramTokenizer was just to make the values that were previously in the constructor public properties so they could then be configured in object initialization. 
e.g. 
`new LengthTokenFilter(name) { MinLength = 3, MaxLength = 100 };`

**Comment by AlexGhiondea** [comment]
@nokternol thanks for reporting this. @tg-msft or @Mohit-Chakraborty will take a look.

**Comment by nokternol** [comment]
Thank you @AlexGhiondea, this was a new change in the old library that I am merging in at the point of completion.
It is the only piece that does not seem to be supported by the new library.
@tg-msft @Mohit-Chakraborty If you could provide any kind of workaround while this is being fixed that would be greatly appreciated

**Comment by nokternol** [comment]
The base TokenFilter is not able to be implemented myself due to it's protection level so I cannot roll my own TokenLengthFilter to bridge the gap for now either

**Comment by Mohit-Chakraborty** [comment]
I don't see a workaround for this unfortunately. We would need to provide setters for the properties.

**Comment by nokternol** [comment]
I've already upgraded to 11.2 beta pre release to get a fix for a different bug I was experiencing so hopefully it can be resolved quickly. I would have happily raised the PR myself if I had more evironment experience to know how to get around the global.json warnings.

**Comment by nokternol** [comment]
It appears there is a new VS version for me to update to.
I can add setters in a PR if that is the approach that should be taken

**Comment by nokternol** [comment]
I obviously didn't set something to link it properly to this defect but...
PR: https://github.com/Azure/azure-sdk-for-net/pull/17694

**Comment by AlexGhiondea** [comment]
@nokternol thanks for providing a PR! Closing as the PR was merged!
