### ISSUE TITLE
[FEATURE REQUEST] OpenRead(): loop downloads for Read() calls larger than internal buffer

### ISSUE THREAD

**Issue by PaulVrugt** [Azure/azure-sdk-for-net#17673]
**Describe the bug**
We discovered an issue that when we use `OpenRead` on `BlockBlobClient`, the returned stream doesn't handle reads of more than 4mb well. When reading more than 4mb, it only reads 4mb:

![image](https://user-images.githubusercontent.com/7567114/102876620-bda3e880-4445-11eb-89f9-62d69a9a87e8.png)

**Expected behavior**
I expect that when I read the entire length of the stream into a buffer, it reads the entire stream

**Actual behavior (include Exception or Stack Trace)**
The current behavior seems to be that even when you pass a number larger than 4mb to the read method, it only reads 4mb.

**To Reproduce**
Use the following snippet to download a file larger than 4mb from a blob container:

```
 var connectionString = "<connectionstring>";
 var blobContainerName = "<containername>";
 var blobName = "<blobName>";
 var targetPath = "<targetPath>";

 var blobClient = new BlobServiceClient(connectionString);
 var blobContainer = blobClient.GetBlobContainerClient(blobContainerName);
 var blob = blobContainer.GetBlockBlobClient(blobName);

 using (var stream = blob.OpenRead())
 {
    using (var destStream = new System.IO.FileStream(targetPath, System.IO.FileMode.Create, System.IO.FileAccess.ReadWrite))
    {
        byte[] buffer = new byte[stream.Length];
        var read = stream.Read(buffer, 0, (int)stream.Length);
        destStream.Write(buffer, 0, (int)stream.Length);
    }
}
```

**Environment:**
 - Name and version of the Library package used:Azure.Storage.Blobs 12.7.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by seanmcc-msft** [comment]
Hi @PaulVrugt, this is by design.  We are using 4 MB as the default buffer size for Open Read.  The [Stream.Read](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-5.0) method can return less than the number of bytes requested:
 > [Returns] The total number of bytes read into the buffer. This can be less than the number of bytes allocated in the buffer if that many bytes are not currently available, or zero (0) if the end of the stream has been reached.

I recommend modifying your code to something like:
```
 using (var stream = blob.OpenRead())
 {
    using (var destStream = new System.IO.FileStream(targetPath, System.IO.FileMode.Create, System.IO.FileAccess.ReadWrite))
    {
        byte[] buffer = new byte[stream.Length];
        int totalRead = 0;
        int read = 0;
        do
        {
            read = stream.Read(buffer, totalRead, (int)stream.Length - totalRead);
            totalRead += read;
        }
        while(read != 0);
        destStream.Write(buffer, totalRead);
    }
}
```
-Sean

**Comment by PaulVrugt** [comment]
@seanmcc-msft 
Well that's mighty disappointing. We use streams as an abstraction level, and we can't have one type of stream behaving differently from all other stream implementation. That kind of defeats the purpose of abstraction. I would urge you to reconsider the design if this behaviour really is by design. We literally have millions of lines of code using these streams. We can't simply check every case to see if more than 4mb is read at once. 

I think this forces us to write a wrapper stream around the blob stream implementation to override this behaviour. But I really believe this shouldn't be necessary. Internal buffers should not be my concern when using this library

**Comment by seanmcc-msft** [comment]
@PaulVrugt, the design conforms to the spec for Stream.  I recommend using a [StreamReader](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader?view=net-5.0) to abstract away this issue.

**Comment by seanmcc-msft** [comment]
@kasobol-msft

**Comment by PaulVrugt** [comment]
Could you direct me that spec? Other streams like memorystream or filestream don't behave like this. I am not in complete control on how developers in my company use the streams. Most of them aren't even aware the stream might come from azure storage. I can't explain to them they can sometimes not read more than 4mb from a stream. Furthermore, we also pass these streams to other 3rd party libraries for which I can't guarantee they take the 4mb limit into account

**Comment by seanmcc-msft** [comment]
[https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.read?view=net-5.0](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamreader.read?view=net-5.0).

In the remarks section:
 > An implementation is free to return fewer bytes than requested even if the end of the stream has not been reached.

You can manually set the buffer size with `BlobBaseClient.OpenRead(options: new BlobOpenReadOptions { BufferSize = [desired buffer size] })`.

The Open Read and Open Write APIs are intended for stream operations.  Attempting to to read a large amount of data is going to be pretty inefficient.  Let's say we are attempting to read a 20 GB blob in your code snippet.  The way you have it set up (if the buffer size was large enough), we would download the entire 20 GB into ram, and then write it to the destination file stream.  Instead, it would be much more memory and time efficient to do multiple small reads from the OpenRead, while writing to the output stream within the loop.  This would use no more than ~1MB of ram:

```
 using (Stream stream = await blob.OpenReadAsync())
 {
    using (Stream destStream = new System.IO.FileStream(targetPath, System.IO.FileMode.Create, System.IO.FileAccess.ReadWrite))
    {
        // we don't want to read the entire stream in one shot.  It could be huge.
        byte[] buffer = new byte[1024 * 1024]; // 1MB buffer
        int read = 0;
        int totalRead = 0;
        do
        {
            read = await stream.ReadAsync(buffer, 0, buffer.Length);
            await destStream.WriteAsync(buffer, totalRead, read);
            totalRead += read;
            Array.Clear(buffer, 0, buffer.Length);
        }
        while(read != 0);
    }
}
```

-Sean

**Comment by PaulVrugt** [comment]
@seanmcc-msft 

Hi Sean,

Sorry about the late reply, we have a bit of incompatible time zones ;)

- I understand reading the entire stream into memory is bad practice, and I completely agree. But unfortunately we don't live in a perfect world where all code adheres to bestpractices, and I cannot go through millions of lines of code to change every implementation. 

- I also understand that streams are allowed to do this by spec, but that doesn't mean it is a good idea. For people migrating to the cloud with existing code implementations, this is a breaking change from file streams, making it harder to migrate code to the cloud. Besides this, file streams also have an internal buffer, but they don't have this behavior. With a file stream, I can read as much data at once as I want without being limited to the buffer size (even though I agree it is a bad practice to read a lot of data at once)

- Increasing the buffer doesn't really help me, because the only way to mitigate the issue is by increasing to buffer to a ridiculous high amount because I don't know how much data will be read at once. And upping the buffer will increase memory consumption for every stream created, not just the problematic onces.

Since I don't think this discussion is going anywhere, I'm happy to implement my own wrapper to mitigate this limitation of the blob storage stream, because luckily in our code all file access is funneled through the same code. But others that run into this might not be so lucky. So I really hope you will consider to implement the `do while` loop inside the library to refill the buffer a few times if a client is trying to read more than the buffer size, just as a file streams seem to do.

**Comment by seanmcc-msft** [comment]
> I understand reading the entire stream into memory is bad practice, and I completely agree. But unfortunately we don't live in a perfect world where all code adheres to bestpractices, and I cannot go through millions of lines of code to change every implementation.

If you are not using `BlobBaseClient.OpenRead()` to perform streaming operations, why not just call `BlobBaseClient.DownloadTo(Stream steam)` and sidestep this issue entirely?  It sounds like the streaming functionality isn't actually necessary for your use case.

```
    using (Stream destStream = new System.IO.FileStream(targetPath, System.IO.FileMode.Create, System.IO.FileAccess.ReadWrite))
    {
        await blobClient.DownloadTo(destStream);
    }
```

**Comment by PaulVrugt** [comment]
The problem is that our situation is not black or white. We have a generic "file access layer" that provides read or write streams to the requested files. What the caller does with these streams is not up to our file access layer. Most of the places where the file access layer is used we are actually using streaming bestpractices, but in some places we don't (and sometimes there is a good reason for this, but I have to admit that I know for a fact that some other places just use a bad implementation of using the stream).

But the thing is, it is not doable for us to go through ALL places where these streams are being used in millions of lines of code.

I've already implemented a wrapper stream around the stream returned from the blob library to circumvent this issue, but I would still rather have this case supported in the library itself, but that decision is not up to me.

At least thank you for taking the time to engage in this discussion, and happy holidays!

**Comment by kasobol-msft** [comment]
The implementation of `Stream` returned by `OpenRead()` is compliant with [the contract](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.readasync?view=net-5.0). One should always check value returned by `Read/ReadAsync`. The fact that some `Stream` implementations would fill provided buffer doesn't imply that this implementation is non-compliant.

However, I think that this is fair ask. The internal buffer (4mb by default) is mostly kept to avoid too many requests if someone is passing smaller buffers to `Read/ReadAsync` and keep excess bytes in memory instead. 
But if someone is passing buffer larger (or much larger) to `Read/ReadAsync` I think we should attempt to fill it. I.e. either ignore internal buffer and request enough bytes to fill provided buffer OR keep requesting 4mb of data and copy it to provided buffer until it's full (i.e. wrap existing logic in a loop that checks provided buffer size).

**Comment by PaulVrugt** [comment]
I completely agree @kasobol-msft . So what's the plan here? Do we reopen the issue?

**Comment by seanmcc-msft** [comment]
We originally had this functionality, I was asked to remove it in the PR - https://github.com/Azure/azure-sdk-for-net/pull/12400#discussion_r446440767.  @jaschrep-msft @tg-msft.

**Comment by jaschrep-msft** [comment]
Reopening as a feature request to loop current `Read()`/`ReadAsync()` implementation, rather than force the caller to do so.

**Comment by tg-msft** [comment]
Hi folks – I don't think we should make this change for a couple of reasons:
- We don't like to redefine semantics for .NET types in Azure libraries.  [`Stream.Read`](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.read?view=net-6.0#System_IO_Stream_Read_System_Byte___System_Int32_System_Int32_) has behaved like this forever.  Even [`FileStream.Read`](https://docs.microsoft.com/en-us/dotnet/api/system.io.filestream.read?view=net-6.0#System_IO_FileStream_Read_System_Byte___System_Int32_System_Int32_) cited above does not always return the number of bytes requested [(reference source)](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/io/filestream.cs#L1538).
- If we were to implement this, I think it should be a separate `BlockingRead` method rather than a mode of the `Stream`.  I'd rather be very explicit about APIs that could negatively impact performance.  That idea should be filed in https://github.com/dotnet/runtime for the .NET team to evaluate, if desired.
- The workaround of wrapping in a "blocking `Stream`" is straightforward and not too onerous when this behavior is required.
