### ISSUE TITLE
Potential memory leak issue in Azure.Documents.Search 11.2.0

### ISSUE THREAD

**Issue by d6teo** [Azure/azure-sdk-for-net#17674]
Hi, we just migrated from v10 to v11 SDK. 

Under heavy load, SearchClient seems to leak memory. The stress test we conducted included sending ~15k requests (750 batches x 25 requests each), with each batch triggered after a random delay between 200ms-2sec.

Environment:
- Azure.Search.Documents (11.2.0-beta.2)
- .NET Core 3.1 web api (as created by dotnet new webapi)
- OS: Win10 Pro 19042.685
- Profiling: VS2019 Diagnostic Tools

Memory footprint:
![image](https://user-images.githubusercontent.com/22095087/102895413-539f3980-446d-11eb-96f9-7de96381b886.png)

Repro:
```csharp
    [ApiController]
    [Route("[controller]")]
    public class TestController : ControllerBase
    {         
        static Azure.Search.Documents.SearchClient client;

        public TestController(IOptions<SearchConfig> cfg)
        {
            client = new Azure.Search.Documents.SearchClient(new Uri(cfg.Value.SearchUrl), cfg.Value.SearchIndexName, new AzureKeyCredential(cfg.Value.SearchKey));
        }

        [HttpGet]
        [Route("stressnative")]
        public async Task<IActionResult> StressNative(bool container)
        {
            var batches = 750;
            var requestsPerBatch = 25;

            var keys = System.IO.File.ReadAllText(container ? "/app/res.txt" : System.IO.Path.Combine(Environment.CurrentDirectory, "res.txt")).Split(',');
            var rnd = new Random();

            var opts = new Azure.Search.Documents.GetDocumentOptions();
            var selectedFields = new List<string>(3);
            selectedFields = TestParams.GetSelectedFields();

            foreach (var x in selectedFields) opts.SelectedFields.Add(x);

            var queued = Enumerable.Range(1, batches).Select(async _ =>
            {
                await Task.Delay(rnd.Next(200, 2000));
                
                var currKeys = keys.Skip(rnd.Next(1, 2974)).Take(requestsPerBatch);
                try
                {
                    foreach (var key in currKeys)
                        await client.GetDocumentAsync<MyDocument>(key, opts);
                }
                catch { }
            });

            await Task.WhenAll(queued);

            return Ok();
        }
    }
```

Could this be something on our end? If so, any guidance for fixing the issue would be greatly appreciated

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by AlexGhiondea** [comment]
@d6teo thanks for filing this. I tried to reproduce this on my end but I am not seeing anything that would lead me to believe there is a memory leak in there.

Can you share more information about what the leak looks like on your side?

**Comment by d6teo** [comment]
@AlexGhiondea, sure. What information would be useful? 
As a side note, we have reproduced the issue in a container environment as well (although the sample targets .NET Core 3 we wanted to make sure that this is reproducable in an "isolated" environment as well -> Docker containers)

**Comment by AlexGhiondea** [comment]
@d6teo when I ran the test on my machine the majority of objects that were created were due to the closures and lambdas used in the code. Did you see those going away via GC? If you take memory snapshots at the start and end of the test, which objects do you see in the delta -- do you know what they are rooted in?

Do you also see the memory continuing to grow unbounded for the duration of the application, or does it grow when the objects are retrieved and then it goes back down?

**Comment by d6teo** [comment]
@AlexGhiondea, my best wishes for a happy new year.

Thanks for pointing out the issue with closures/lambdas. I understand that these create the majority of allocations, however I am not sure that this is the root cause of the mem utilization issue - mem remains high after all the requests have been completed.

To demonstrate, please see below repro scenario (i believe that this leaves closure/lambda issues out of the equation):
```
[ApiController]
[Route("[controller]")]
public class TestController : ControllerBase
{             

    private static Lazy<Azure.Search.Documents.SearchClient> _lazyClient = new Lazy<Azure.Search.Documents.SearchClient>(() =>new Azure.Search.Documents.SearchClient(new Uri("<url>"), "<indexname>", new AzureKeyCredential("<key>")));      

    [HttpGet]
    public async Task<IActionResult> Stress()
    {
        var keys = Enumerable.Repeat(1, 25).Select(_ => "<any indexed document key>").ToList();
    
        // add a few fields, repro case adds 3 fields in [GetDocumentOptions] instance
        var opts = new Azure.Search.Documents.GetDocumentOptions();     
    
        try
        {
            foreach (var key in keys)
                await _client.GetDocumentAsync<MyDocument>(key, opts);
        }
        catch { }
    
        return Ok();
    }
```
I used ab testing to simulate stress conditions:
`ab.exe -n 750 -c 750 -s 600 http://localhost:<port>/test/stress`

Mem utilization chart w. object/heap snapshot during the entire test's lifecycle:
![image](https://user-images.githubusercontent.com/22095087/103570701-4012ba80-4ed2-11eb-81fd-8102ad30653d.png)

**Comment by AlexGhiondea** [comment]
@d6teo thanks for the wishes -- Happy New Year!

From the diff that you have in there were you able to figure out who is holding on to the objects?

I am going to ask @heaths to take a look at this as well.

**Comment by d6teo** [comment]
Unfortunately i couldn't find where the objects are rooted. 
Funny thing is that the heap size is much smaller than the process memory; I also tried profiling the app using VS Performance Profiler and mem footprint was ~100MB less, but still high and still there after all requests were completed. 

See below, managed heap+native heap size sum up to ~70MB, process memory is ~450MB:
![image](https://user-images.githubusercontent.com/22095087/103632785-835e3f00-4f4d-11eb-8e47-3fba18406dc4.png)

However, when turning Server GC off, mem footprint looks much better; in fact, the first GC collection after all requests have completed restores memory to ~80MB. See below:
![image](https://user-images.githubusercontent.com/22095087/103634128-54e16380-4f4f-11eb-9e14-9b1f4339a231.png)

Maybe it's not something specific to search SDK, but something related to the way GC returns free memory to the OS??

**Comment by heaths** [comment]
Depending on how your app is hosted, turning off server GC may be a good idea anyway. See https://docs.microsoft.com/dotnet/standard/garbage-collection/workstation-server-gc for details.

I'm not seeing anything in code that would lead me to believe there is (directly) a leak, though for deserialization some static caching for System.Text.Json may occur (definitely if you're using Newtonsoft.Json for deserialization), but for your example document it shouldn't be anything close to that. The [closure still gets created in your last example](https://sharplab.io/#v2:EYLgtghgzgLgpgJwD4AEAMACFBGALAbgFgAodLbAOgBkBLAOwEcjSBmLAJgwGEMBvEjIKxsUuDAFkAFAEo+AoQoBuEBBgA2NWBgC8GOnADuGWrAA8ONAD55Cwf2K3HGAEQRnAGhtPBz4B6/ezgDG/g5OAL7M3sqqEDrqmjAUAMpwanBBMJIA+jqWLm7SUULhJOFAA===) as well.

It'd be great to get a nettrace to track down the allocations in your environment where this repros. Could you [run dotnet-trace](https://heaths.dev/azure/2020/02/04/trace-azure-sdk-for-net.html) with your app to sample the GC. Per the article, it'd be great if you'd trace the network calls as well so we can see how allocations correlate.

**Comment by ComponentFactory** [comment]
I have just debugged a memory leak in our .NET Core service and it was also caused by the SearchClient. Commenting out use of this class fixed the issue immediately. There seemed to DiagnosticListener instances on the the heap when the leak was occuring.
