### ISSUE TITLE
Investigate using Azure.Core Test Framework Base Classes

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#17688]
# Summary

Since the Event Hubs tests were written, the Azure.Core Test Framework was created, offering a common set of base classes intended to be used with live tests and tests containing sample snippets.   We should determine if there is an advantage to using these within the Event Hubs test projects.

# Scope of Work

- Investigate the structure and functionality of the Azure.Core Test Framework `LiveTestBase` class, which will require determining an approach for allowing tests to execute in parallel for Event Hubs, as the base class is annotated to prevent this.

- Investigate the structure and functionality of the Azure.Core Test Framework `SamplesBase` class, which may require determining an approach for allowing tests to execute in parallel for Event Hubs.  It is not know if the base class is annotated to prevent this.

- Determine whether it makes sense to build on the base classes for Event Hubs..

# Success Criteria

- Investigate the potential for use of the Azure.Core Test Framework base classes, as detailed in the scope.

- Discuss any potential approach for parallelism with the Azure.Core team and architects, ensuring alignment.

- If the base classes will be used with Event Hubs, the issues needed to track the implementation work have been created.

**Comment by Heldy09** [comment]
Hay@jsquire. Perlu pemantawan dan kerjasama di bidang ini menganalisis apa kah even tersbut layak di jalan kan apa ngak karna memerlu kan pengalang dana. Angota yang lain belum tertarik. Apa kah iven ini layak apa ngak. Perlu ada poting untuk mendapat kan bantuan dari angota yang lain di projek tersebut.

**Comment by jsquire** [comment]
After poking around, there doesn't seem to be enough value to justify the efforts to migrate things over and adjust test patterns.   Closing this out.
