### ISSUE TITLE
stop listening to service bus queue messages

### ISSUE THREAD

**Issue by ahmettahasakar** [Azure/azure-sdk-for-net#1768]
Hello,
I'm listening to service bus queue messages like below.

```
NotificationQueueClient.OnMessage(arg =>
                {
                    if (token.IsCancellationRequested)
                    {
                        arg.Abandon();
                        Thread.Sleep(Timeout.Infinite);
                    }

                    try
                    {
                        NotificationMessage message = arg.GetGenericBody<NotificationMessage>();
                       Process(message);
                        arg.Complete();
                    }
                    catch (Exception ex)
                    {
                        arg.Abandon();
                    }

                }, options);

                while (!token.IsCancellationRequested)
                {
                    token.WaitHandle.WaitOne(10000);
                }

                Thread.Sleep(30000); //waiting just to be safe that queue processing is complete

                NotificationQueueClient.Close();
            }

```

when I close the connection like this, I get the following error
The server was unable to process the request; please retry the operation. If the problem persists, please contact your Service Bus administrator and provide the tracking id.

How do I close the connection gracefully. I'm trying to make sure that the connection is not closed in the middle of a message processing but I still get this error.

**Comment by nemakam** [comment]
@ahmettahasakar, If I understand your question correctly, you are looking for a way to pause/stop receiving messages before you call the `Close()` right?
This functionality is not present right now. You can open a feature request if needed. Meanwhile, calling `QueueClient.Close()` is the only, way which could lead to client side exceptions.

**Comment by jfggdl** [comment]
@ahmettahasakar   We are going to close this issue, but if you feel that you need a new feature, please reopen this issue.

**Comment by asumner** [comment]
@ahmettahasakar I have a machine processing messages that needs to be allowed to finish current work but also stop receiving new messages, why is it not ok to close(). Jobs hopefully will complete and I can reboot the machine, or allow it to shutdown cleanly, ideally I'd like the client to be in a paused listening state?
