### ISSUE TITLE
Support for Azure Monitor custom metrics

### ISSUE THREAD

**Issue by cgwrench** [Azure/azure-sdk-for-net#17687]
I'm trying to publish [custom metrics to Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview). This is currently in public preview. While the [REST API is documented](https://docs.microsoft.com/en-us/rest/api/monitor/metrics%20%28data%20plane%29/create), there doesn't appear to be a .NET client that can be used to publish custom metrics (please let me know if there is one, and I'm just not finding it).

I thought I'd try and roll my own client that builds on top of `Azure.Core`, so that this client looks and feels like the official SDK clients that I'm using elsewhere in my code. However, I'm running into issues with authenticating with the Azure Monitor service.

I'm creating a `HttpPipleline` as follows:

```csharp
HttpPipelineBuilder.Build(
    options, // An instance of an options class that derives from `Azure.Core.ClientOptions`.
    new BearerTokenAuthenticationPolicy(
        tokenCredential, // An instance of `Azure.Core.TokenCredential`.
        "https://monitoring.azure.com/.default"));
```

Note that here I've used a scope of `https://monitoring.azure.com/.default`, which ends in `.default`.

Authentication seems to work, and I get an access token. However, when I try and POST to https://uksouth.monitoring.azure.com/ using this access token (note the [region specific URL](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview#supported-regions), which differs to the scope used in the previous code snippet), I get an error message of:

> The access token is intended for the wrong audience or resource. It should exactly match (including forward slash) audience 'https://monitoring.azure.com/'.

If I change the scope in the previous code snippet to the URL in this error message (i.e. if I drop the ".default"), I get a different error message:

> AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://monitoring.azure.com/ is not valid…

I'd appreciate answers to the following questions:

1. Should it be possible to create a client for the Azure Monitor service that uses `Azure.Core`? If so, what am I doing wrong?
2. If this shouldn't be possible, what's the best approach for creating an Azure Monitor custom metrics client (given that I'm already using the newer versions of the SDK in my code)

I've included below a complete sample that demonstrates the errors I've been seeing.

<details>
 <summary>Repro</summary>

using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Core.Pipeline;
using Azure.Identity;

namespace AzureMonitorTest
{
    public static class Program
    {
        public static async Task Main()
        {
            var credential = new ClientSecretCredential(
                tenantId: "insert value here",
                clientId: "insert value here",
                clientSecret: "insert value here");

            // Note the region specific URL used here. See
            // https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview#supported-regions
            var monitorClient = new MonitorClient(
                subscriptionId: "insert value here",
                endpoint: new Uri("https://uksouth.monitoring.azure.com"),
                credential);

            await monitorClient.CreateAsync(
                resourceGroupName: "can be left empty",
                resourceProviderNamespace: "can be left empty",
                resourceType: "can be left empty",
                resourceName: "can be left empty",
                new {});
        }
    }

    public class MonitorClientOptions : ClientOptions
    {
    }

    public class MonitorClient
    {
        private readonly string _subscriptionId;
        private readonly Uri _endpoint;
        private readonly HttpPipeline _pipeline;

        public MonitorClient(
            string subscriptionId,
            Uri endpoint,
            TokenCredential tokenCredential,
            MonitorClientOptions options = null)
        {
            options ??= new MonitorClientOptions();

            // Note the use of ".default" here. Without this, authentication
            // fails with a message "AADSTS70011: The provided request must
            // include a 'scope' input parameter. The provided value for the
            // input parameter 'scope' is not valid. The scope
            // https://monitoring.azure.com/ is not valid…".
            _pipeline = HttpPipelineBuilder.Build(
                options,
                new BearerTokenAuthenticationPolicy(tokenCredential, "https://monitoring.azure.com/.default"));

            _subscriptionId = subscriptionId;
            _endpoint = endpoint;
        }

        public virtual async Task<Response> CreateAsync(
            string resourceGroupName,
            string resourceProviderNamespace,
            string resourceType,
            string resourceName,
            object parameters,
            CancellationToken cancellationToken = default)
        {
            using var message = CreateRequest(
                resourceGroupName,
                resourceProviderNamespace,
                resourceType,
                resourceName,
                parameters);
            
            // This fails with a message "The access token is intended for the
            // wrong audience or resource. It should exactly match (including
            // forward slash) audience 'https://monitoring.azure.com/'.".
            await _pipeline.SendAsync(message, cancellationToken).ConfigureAwait(false);

            return message.Response.Status switch
            {
                200 => message.Response,
                _ => throw new Exception("Something when wrong: " + new StreamReader(message.Response.ContentStream).ReadToEnd()) // Forgive this line.
            };
        }

        private HttpMessage CreateRequest(
            string resourceGroupName,
            string resourceProviderNamespace,
            string resourceType,
            string resourceName,
            object parameters)
        {
            var message = _pipeline.CreateMessage();

            var request = message.Request;

            request.Method = RequestMethod.Post;

            var uri = new RequestUriBuilder();

            uri.Reset(_endpoint);
            uri.AppendPath("/subscriptions/", escape: false);
            uri.AppendPath(_subscriptionId, escape: true);
            uri.AppendPath("/resourceGroups/", escape: false);
            uri.AppendPath(resourceGroupName, escape: true);
            uri.AppendPath("/providers/", escape: false);
            uri.AppendPath(resourceProviderNamespace, escape: true);
            uri.AppendPath(resourceType, escape: true);
            uri.AppendPath(resourceName, escape: true);
            uri.AppendPath("/metrics", escape: false);
            uri.AppendQuery("api-version", "2018-09-01-preview", true);

            request.Uri = uri;

            request.Headers.Add("Content-Type", "application/json");
            request.Headers.Add("Accept", "application/json");

            // Here `parameters` should represent the custom metric, and this
            // should be serialised here. For this repro, the content doesn't
            // matter.
            request.Content = RequestContent.Create(
                Encoding.UTF8.GetBytes("This can be anything, since auth will fail."));

            return message;
        }
    }
}
</details>

**Environment:**

 - Name and version of the Library package used: Azure.Core 1.7.0
 - Hosting platform or OS and .NET runtime version: Windows 10, .NET Core SDK 5.0.100
 - IDE and version: Visual Studio Code 1.5.1.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by cgwrench** [comment]
A [comment on another issue](https://github.com/Azure/azure-sdk-for-net/issues/14122#issuecomment-673030919) hints, I think, that this should be possible:

> we have created some sample extension libraries that demonstrate how to use `Azure.Identity` in libraries which currently only support legacy forms of authentication. It should be possible to use the `DefaultAzureCredential` to authenticate both clients, with a bit of temporary code.

This sounds related to the problem I'm trying to solve. If so, could anyone point me to where these samples are?

**Comment by cgwrench** [comment]
I've managed to figure this out. Using a scope of `https://monitoring.azure.com//.default` appears to work (note the double forward slash). This appears to be documented here: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#trailing-slash-and-default.

**Comment by levalencia** [comment]
@cgwrench Can you check the issue  linked above, maybe you already implemented this and I would be very thankful if you can help me out.

I use some part of the code you put in this issue
