### ISSUE TITLE
[QUERY] How to query for keys on demand during runtime?

### ISSUE THREAD

**Issue by cesarsouza** [Azure/azure-sdk-for-net#17704]
**Query/Question**
I've been using Azure in my ASP.NET Core application with no problems in the past months. I've configured the application to retrieve configuration options using ```config.AddAzureAppConfiguration(options =>... ``` in Program.cs through ``` .ConfigureWebHostDefaults(webBuilder => webBuilder.ConfigureAppConfiguration((hostingContext, config) => ... ``` as instructed in https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-aspnet-core-app?tabs=core3x and it has been working great. 

However, I currently understand that this approach is going to load the Azure vault keys into the IConfiguration object at startup. I needed to be able to retrieve those keys during execution, depending on some parameters that have been informed by the current logged in user. Also, it could happen that the keys that the current user is going to ask were not available when the website was first started, but had been added afterwards.

Therefore, my question is: How could I query the Azure Key Vault for the latest versions of a particular key string during program execution?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0]: 
 
Microsoft.AspNetCore.DataProtection.AzureKeyVault 3.1.10
 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 
PM> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  3.1.300 [C:\Program Files\dotnet\sdk]
  5.0.100-rc.2.20479.15 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0-rc.2.20475.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0-rc.2.20475.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0-rc.2.20475.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

 - IDE and version : [e.g. Visual Studio 16.3]
 
Visual Studio 16.8.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by jsquire** [comment]
@pakrym:  Would you mind offering your thoughts or helping to route to the correct individual?

**Comment by AlexGhiondea** [comment]
@cesarsouza is the ask about how to query for KeyVault values on demand or how to configure Asp.net to do that itself?

**Comment by cesarsouza** [comment]
> @cesarsouza is the ask about how to query for KeyVault values on demand or how to configure Asp.net to do that itself?

Hi thanks for the response! Well... Both ? I didn't realize asp.net could request new values by itself after the application had started. Isn't the Azure configuration applied, and keys read, only during application startup?

What I wanted to know was how one could load, reload, or simply keep up to date API keys that could have been added or updated to the vault while the application is running. 

Most of the tutorials I've seen seem to load the configuration at startup and use them to configure a service also at startup, and that's it. I couldn't figure out how to make a service make sure that the keys it's about to use are the latest ones that are currently available at the vault. 

Regards and thanks again for the reply! 
Cesar

**Comment by AlexGhiondea** [comment]
@cesarsouza I am not sure that Asp.Net can automatically update the keys -- and I wanted to make sure that wasn't the scenario you had in mind! 🙂

I don't think we have any documentation that shows how an app can ensure that its keys are up to date. However, one approach is to always assume that the key is valid and handle the case where a request fails and, at the time, obtain an updated key?

@pakrym do you know of a better way of doing this?

**Comment by cesarsouza** [comment]
Hi @AlexGhiondea thanks for the reply again! Just to give a bit more information, this would be useful in a multi-tenant scenario where the main content provider shouldn't be aware of the main keys of its tenants (I am oversimplofiying a bit). However, just to give an example, this would be needed in an hypothetical situation where, for example, a tenant would like to keep absolute control over their own keys to decrypt their own data storing them into their own azure vault irrespective of the time the main application had been started. We wouldn't like to restart the global application everytime a new tenant would be added with their own personal key. 

If a new tenant has been added after the main application would have been started, or changed their keys while the application was running, it would be the best if the application could reload those keys during runtime.

I've oversimplified a little bit and the example doesn't really correspond to what we would really need, but surely there should be a way to ensure that a service would be using the latest versions of the keys during runtime and not only after application startup? 

Cheers,
Cesar

**Comment by pakrym** [comment]
Couple comments:

1. The `IConfiguration` abstraction is inherently eager-loading one. There is no per-key call that configuration providers get so there is no way for them to re-load individual values.
2. `IConfiguration` abstraction does have a `Reload()` method that allows you to reload all providers. See https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.iconfigurationroot.reload?view=dotnet-plat-ext-5.0#Microsoft_Extensions_Configuration_IConfigurationRoot_Reload
3. KeyVault configuration provider also supports auto-reload. 
``` C#
configurationBuilder.AddAzureKeyVault(vaultUri, credential, new AzureKeyVaultConfigurationOptions()
            {
                ReloadInterval = TimeSpan.FromMinutes(5)
            });

```
