### ISSUE TITLE
[BUG][Storage] server return 404 also retry 

### ISSUE THREAD

**Issue by yunair** [Azure/azure-sdk-for-net#17703]
**Describe the bug**
blob client call `GetPropertiesAsync` will retry even though server return 404?
We have a case, get a blob path return 404, but it takes too long for me.
In Application insight, we can see it will retry 6 times. but we don't config the client retry policy.

![image](https://user-images.githubusercontent.com/4322540/103131268-06c09a80-46db-11eb-84f6-b88ecbd34f45.png)

**Expected behavior**

don't retry.

**Actual behavior (include Exception or Stack Trace)**

retry 6 times

![image](https://user-images.githubusercontent.com/4322540/103131288-21930f00-46db-11eb-8512-0979f500a424.png)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.
2.

**Environment:**
 - Azure.Storage.Blobs 12.4.4
 - Win 10 and netstandard2.0
 - Visual Studio 16.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by amnguye** [comment]
I'm having a difficult time reproducing this issue. We have a test surrounding this case, where if we get a `404` or a `BlobNotFound` error and my fiddler trace shows we only sent this request once, and afterwards we did not send retries to the service.


Is the error code returning back `BlobNotFound`?

**Comment by yunair** [comment]
I have reproduce this problem, just set `GeoRedundantSecondaryUri` same as `serviceUrl`

**Comment by older** [comment]
> I have reproduce this problem, just set `GeoRedundantSecondaryUri` same as `serviceUrl`

Tank you @yunair your comment helped me a lot! 

It is really weird that this bug is still not fixed even in the latest version of SDK (I'm using Azure.Storage.Blobs 12.13.1 right now). I wasted couple of days trying to understand what I'm doing wrong. @amnguye you still cannot reproduce it?

**Comment by JimSuplizio** [comment]
Hi @yunair, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
