### ISSUE TITLE
why Azure file share SDK is being degraded over time?

### ISSUE THREAD

**Issue by martys** [Azure/azure-sdk-for-net#17706]
How come, that the **old package** works **better** than the new one ? 
In particular speaking of [DEPRECATED] "WindowsAzure.Storage" Version="9.3.3" 
                                                           or "Microsoft.Azure.Storage.File" Version="11.2.2" 
(question **#1** - how long can I keep using it until I'm forced to use the "NEW" "Azure.Storage.Files.Shares" Version="12.5.0" ????)

and as for the main question - Your [page ](https://azure.microsoft.com/en-us/blog/previewing-azure-sdks-following-new-azure-sdk-api-standards/) clearly states that:  
>  ...Azure SDKs that we believe will make the libraries easier to learn and integrate into your software.

Which in the case "Azure.Storage.Files.Shares" Version="12.5.0" - is completely opposite. 
I'm as developer am being "forced" to use this library, without any knowledge for how long the old one will keep working,
and I would dare saying - one which is **worse, and more difficult to use and integrate than the OLD one**.

I'm speaking in particular about the File Upload API, which is now forcing me to write code that requires me to **split files into chunks and upload them piece by peace** instead of just pointing the SDK to the file, and asking it to UPLOAD IT!
(that's at least how it perfectly worked in the OLD  "WindowsAzure.Storage" package)

so the question **#2**  are You planning to provide a proper API in the SDK that would allow users to seamlessly upload files bigger than 4MB ? (or for that matter at least samples !?!?!) 

And lastly - (I do not have the data yet, to back this statement up) - but it feels like it's also slower !?!?!?
**#3.** Whys is the performance worse ??

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by AlexGhiondea** [comment]
@martys thank you for the feedback.

Have you looked at [this](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Files.Shares#create-a-share-and-upload-a-file) sample? It shows how you can easily create a file share and upload a file to it without having to manually split the file into blocks.

Would you be able to share more about the scenario where you are seeing slowness?

**Comment by martys** [comment]
Yes of course. Following this sample is exactly what got me into the error - that request size is too big, and that I must split my file into chunks .
to be more exact : `Azure.Storage.Files.Shares Azure.RequestFailedException: The request body is too large and exceeds the maximum permissible limit.`

**Comment by AlexGhiondea** [comment]
@martys thanks for the quick reply. Let me take a quick look. The `Upload` method you are using should use the partitioned uploaded that would split the file into multiple chunks.

**Comment by AlexGhiondea** [comment]
Can you try replacing the line:

```csharp
 file.UploadRange(
        new HttpRange(0, stream.Length),
        stream);
```

with 

```csharp
file.Upload(stream);
```

**Comment by martys** [comment]
@AlexGhiondea  Thanks. Will test it out tomorrow, and will measure the speed difference also.
Any word on - for how long the old deprecated package can be used ?

**Comment by AlexGhiondea** [comment]
@martys great! Let me know if that works and also what you perf number show!

You should be able to continue to use the deprecated package, however we **strongly** recommend that you consider upgrading to our latest version of those libraries.

**Comment by martys** [comment]
Interestingly - my feelings were deceptive... the old package is actually noticeably slower than the new one

And thank You for a very quick response and guidance. I did jump to conclusions too quickly :( 

![image](https://user-images.githubusercontent.com/210054/103375618-4f18f780-4ae3-11eb-9032-9d6ac6467711.png)
