### ISSUE TITLE
[Event Hubs Client] All Track1 Tests fail while authrityhost from key vault secret doesn't end with "/"

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-net#17701]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.
Based on following [code](https://github.com/Azure/azure-sdk-for-net/blob/1ee01cbe78969514ce104502fc9fa627e2c5a293/sdk/eventhub/Microsoft.Azure.EventHubs/tests/Infrastructure/EventHubScope.cs#L277), all clouds' authorityhost must  end with "/".  But now from subscription configuration in key vault secret only Public end with "/".
This leads to all track 1 tests fail. 
In Issue [15009](https://github.com/Azure/azure-sdk-for-net/issues/15009),  track2 Event Hub code was fixed, track1 Eventhub code need to be fixed also.  

![image](https://user-images.githubusercontent.com/53427149/92563944-f65eee00-f2aa-11ea-8e91-83609cda8f40.png)
Now the value of AZURE_AUTHORITY_HOST from subscription configuration in key vault secret :
sub-config-azure-cloud-test-resources-test: None,so using default value : https://login.microsoftonline.com/ 
sub-config-cn-test-resources-test : https://login.chinacloudapi.cn
sub-config-gov-test-resources-test : https://login.microsoftonline.com
@jongio @danieljurek

**Comment by jsquire** [comment]
Fixed by #17816
