### ISSUE TITLE
Not all messages are being peeked from Azure Service Bus queue

### ISSUE THREAD

**Issue by craig-wagner** [Azure/azure-sdk-for-net#17702]
I have an Azure Service Bus queue with 236 messages in the dead-letter sub-queue. I know this because the Azure Portal and Service Bus Explorer show me that number.

I wrote the following in LINQPad v6.11.11 x64 to retrieve all 236 messages and examine them. However it only ever returns 136 of the 236 messages.

I'm using v5.1.0 of the Microsoft.Azure.ServiceBus nuget package.

Any thoughts as to why I'm not getting all 236 messages?

    const string queueName = "the-queue-name";
    const string serviceBusConnectionString = "Endpoint=...";
    
    var receiver = new MessageReceiver(serviceBusConnectionString, EntityNameHelper.FormatDeadLetterPath(queueName));
    var receivedMessages = await receiver.PeekAsync(300);

    Console.WriteLine($"Received [{receivedMessages.Count()}] dead-letters");

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by axisc** [comment]
@craig-wagner can you confirm if it's the first 136 messages or the last 136 messages?

Peeking utilizes a checkpoint so that you don't peek the same messages again and again. I suspect that is what is happening here (especially if you are seeing the last 136 messages).

**Comment by axisc** [comment]
@craig-wagner 
closing the ticket. Please feel free to open a new ticket and reference this if there is still an issue.
