### ISSUE TITLE
Typo in AzureAsyncOperationResponse documentation

### ISSUE THREAD

**Issue by ahmetb** [Azure/azure-sdk-for-net#1770]
![image](https://cloud.githubusercontent.com/assets/159209/12761418/c58f819c-c99f-11e5-9e80-e4a8d31af1d4.png)

**Comment by ahmetalpbalkan** [comment]
comes from https://github.com/Azure/azure-rest-api-specs/blob/b0d83f3ccf1e4e4615c395b9a15f2a5186f2cf7f/arm-network/2015-05-01-preview/swagger/network.json#L6540

**Comment by ahmetalpbalkan** [comment]
hopefully gets fixed someday...
