### ISSUE TITLE
Mixed reality region westus2 not supported

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#17715]
The [net - mixedreality - tests](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=668254&view=logs&j=d3e478ed-bc60-5eef-15f3-c813c959402d&t=5f20e984-615c-5bea-9b30-1036c4bd0878) are failing when provisioning the resource as `westus2` is not supported.

```
Body:
{
  "error": {
    "code": "LocationNotAvailableForResourceType",
    "message": "The provided location 'westus2' is not available for resource type 'Microsoft.MixedReality/spatialAnchorsAccounts'. List of available regions for the resource type is 'australiaeast,eastus,eastus2,koreacentral,northeurope,westeurope,southcentralus,uksouth,southeastasia'."
  }
}
```

FYI @craigktreasure, more information about the pipelines can be found [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/389/-.net-Configuring-Live-Tests)
Also feel free to ping @benbp as he has been working on it.

**Comment by craigktreasure** [comment]
Thanks @maririos for the info. I'm trying to determine the status of Azure Spatial Anchors for WestUS2. It was previously a pilot region, but there has been a desire to change it to a production region. I'm trying to determine what the status of that migration is currently. Is it possible to skip that region for now?

@vriveras for awareness.

**Comment by craigktreasure** [comment]
@benbp I just confirmed with the team that the westus2 region is not available for Azure Spatial Anchors. Can we skip that region for now for these tests?

**Comment by craigktreasure** [comment]
@benbp What do we do about this?

**Comment by benbp** [comment]
@craigktreasure you can change the test region by adding it as a parameter to tests.yml, for example in `sdk/mixedreality/tests.yml`:

```
trigger: none

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-tests.yml
  parameters:
    ServiceDirectory: mixedreality
    Location: <some other valid location>
```
