### ISSUE TITLE
[QUERY] GetDirectoryReference is Missing in Azure.Storage.Blobs?

### ISSUE THREAD

**Issue by piklu-sutradhar** [Azure/azure-sdk-for-net#17713]
**GetDirectoryReference is Missing in Azure.Storage.Blobs**
How can we help?

- So I need to get the list of blobs in a sub directory in a container. In Microsoft.Auzre.Storage.Blobs has a somehting like Container.GetDirectoryReference() which I did not find in Azure.Storage.Blobs.

I can get the list of blobs in the container using BlobContainerClient.GetBlobs(), but I do not want it since I have around more than 100K blobs in that container. So is there any way to get the list of blobs only in a specific sub dir in a container?

**Environment:**
 - SDK: Azure.Storage.Blobs 12.6.0
 - Hosting platform or OS and .NET runtime version 
 .NET Core SDK (reflecting any global.json):
 Version:   3.1.301
 Commit:    7feb845744

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.301\

Host (useful for support):
  Version: 3.1.5
  Commit:  65cd789777
 - IDE and version : VSCode 1.52.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by seanmcc-msft** [comment]
Hi @piklu-sutradhar,

You can list blobs under a specific prefix with this code snippet:
```
            await foreach (BlobItem blobItem in containerClient.GetBlobsAsync(prefix: "prefix/in/question"));
```

If you are using a [hierarchical namespace-enabled account](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-namespace), I recommend using [Azure.Storage.Files.DataLake](https://www.nuget.org/packages/Azure.Storage.Files.DataLake/12.6.0-beta.1) instead.

-Sean

**Comment by Saibamen** [comment]
@seanmcc-msft: And how to delete `BlobItem`?
These is no `DeleteIfExists()` method

**Comment by seanmcc-msft** [comment]
new up `BlobClient` for the blob in question, and call `.DeleteIfExists()`
