### ISSUE TITLE
Flaky tests for CancelCertificateOperation

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#17718]
Only visible in the [net - keyvault - tests-weekly](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=667418&view=logs&j=c4f774f2-c444-5fdf-929f-e652716d4adf&t=7d400157-10b1-54bc-89e1-ff2aeca4fa3e) pipeline, the `VerifyCancelCertificateOperation` and `VerifyUnexpectedCancelCertificateOperation` are randomly failing with:

```
Error Message:
     Expected: <System.OperationCanceledException>
  But was:  null
```

**Comment by heaths** [comment]
Likely a timing issue (e.g. don't cancel fast enough). If so, I may mark the test inconclusive if the expected exception isn't received.

**Comment by heaths** [comment]
I'm going to log more information for now. Parsing through the code, it's not clear why the expected exception was not thrown.

**Comment by maririos** [comment]
@heaths  have you seen this fail again? should the issue remain open?

**Comment by heaths** [comment]
Yes, it happens from time to time but has been lower priority vs. features that needed to get out in preview first. I plan to address it in the April milestone.

**Comment by maririos** [comment]
No worries. I was just checking

**Comment by heaths** [comment]
To note, when I added more logging for the status and any error message, in the rare case the expected exception is not thrown, the status is "inProgress". Yet, I can find no way to exit the wait loop in that case, so I'm adding more logging for `UpdateStatus` and `UpdateStatusAsync` via EventSource.
