### ISSUE TITLE
Synchronous retrieving of access token when using Azure.Identity leads to performance issues

### ISSUE THREAD

**Issue by Rookian** [Azure/azure-sdk-for-net#17736]
**Requirements**
We have the requirement to provide a constantly fast Web Api with response times of less than 50ms. The Web Api provides data from Azure Sql.

**Current Solution**
We use Managed Identity to authorize access from an Azure App Service to Azure Sql. 
In order to have an authorized SqlConnection for EF Core we use our own `DbConnectionInterceptor`.
```csharp
public class AADTokenInjectorDbInterceptor : DbConnectionInterceptor
{
    private readonly IAzureCredentialProviderFactory _azureCredentialProviderFactory;
    private readonly IMeasureTime _measureTime;
    private static readonly string[] Scopes = { "https://database.windows.net/.default" };
    private AccessToken _accessToken;

    public AADTokenInjectorDbInterceptor(IMeasureTime measureTime)
    {
        _measureTime = measureTime;
    }

    public override async Task<InterceptionResult> ConnectionOpeningAsync(
        DbConnection connection,
        ConnectionEventData eventData,
        InterceptionResult result,
        CancellationToken cancellationToken = default)
    {
        var sqlConnection = (SqlConnection)connection;

        await RefreshTokenIfNecessary();
        sqlConnection.AccessToken = _accessToken.Token;
        return result;
    }

    private async Task RefreshTokenIfNecessary()
    {
        if (_accessToken.ExpiresOn != default && DateTimeOffset.UtcNow < _accessToken.ExpiresOn)
            return;

        _accessToken = await _measureTime.For("Refresh token for SQL Server",
            async () =>
            {
                var tokenCredential = new ChainedTokenCredential(new AzureCliCredential(), new ManagedIdentityCredential());
                return await tokenCredential.GetTokenAsync(new TokenRequestContext(Scopes), CancellationToken.None);
            });
    }
}

```

**Issue**
The "synchronous" retrieving of an access token, which can take several seconds, slows down requests constantly. 
**e.g.** Sql query _(5ms)_ + retrieving access token _(1500ms)_ = _1505ms_ instead of _5ms_.

**Failed Solution Idea**
We tried to cache the access token using ASP.NET Core Background Service in order to remove the blocking/synchronous call from our own `DbConnectionInterceptor` implementation. This idea back fired as we assumed `TokenCredential.GetTokenAsync` would give us a **new** access token which it doesn't.

**Questions**
Is there anyway on how we can force Azure.Identity to give us a **new** access token?
Are there any other solutions to achieve a constantly fast responding Web Api that access Sql Server using Managed Identity?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by jongio** [comment]
Tagging @pakrym as he is our ASP.NET Guru

I don't have the answer myself, but I recommend putting ManagedIdentityCredential before AzureCliCredential so you don't try AzureCliCredential in prod env with MI.

**Comment by schaabs** [comment]
@Rookian Thanks for reaching out to us with this issue, and I'm sorry your having this trouble.
 > Is there anyway on how we can force Azure.Identity to give us a new access token?

Azure.Identity doesn't provide an mechanism to force issuing a new token because there is no way for the library to guarantee this as the token can be cached at many levels, including the STS. So any mechanism we would add to enable this would only be a best attempt, and unreliable.

Also I would second what @jongio suggested about reordering your credentials putting the `ManagedIdentityCredential` before the `AzureCliCredential`, I think that the long delays you're seeing in acquiring a token (> 1sec) are probably due to the the `AzureCliCredential`. This credential shells out the to the Azure CLI to obtain a token and the CLI startup can easily take as long as the delays your seeing. Could you try switching the ordering of your credentials and see if you're still seeing the same latency when deployed to a host with managed identity enabled?

If this still doesn't fix the problem, I think your background refresh approach could also be a viable work around, but since you cannot guarantee you'll get a new token when calling `GetTokenAsync` I would suggest simply doing this refresh more frequently.

**Comment by Rookian** [comment]
@schaabs, @pakrym 
>Also I would second what @jongio suggested about reordering your credentials putting the ManagedIdentityCredential before the AzureCliCredential, I think that the long delays you're seeing in acquiring a token (> 1sec) are probably due to the the AzureCliCredential.

Sry, my given code example did not show our production code. We have used `DefaultAzureCredential`.
``` csharp
new DefaultAzureCredential(new DefaultAzureCredentialOptions
{
   ExcludeVisualStudioCredential = true,
   ExcludeVisualStudioCodeCredential = true,
   ExcludeSharedTokenCacheCredential = true
}
```

> So any mechanism we would add to enable this would only be a best attempt, and unreliable.

> ... but since you cannot guarantee you'll get a new token when calling GetTokenAsync I would suggest simply doing this refresh more frequently.

I am a bit concerned and I fear that doing the refresh more frequently is unreliable. Don't we have the same problem (predict when we will get a new token) as you have?
Our background service has to guarantee that a valid token is always available. Imo this is not possible due to the fact that we only can just hammering on `GetTokenAsync`. Even if we would do this every millisecond there would be still a possible gap. 

Is there something like a token expiration tolerance threshold that would minimize or even eliminate the gap? e.g. an expired token is still valid for 5 minutes.

**Comment by schaabs** [comment]
@Rookian 

> Is there something like a token expiration tolerance threshold that would minimize or even eliminate the gap? e.g. an expired token is still valid for 5 minutes.

There is current no configuration to control when new tokens would be requested, as this has the same problem I mentioned above, The library has no control over when the token endpoint is also caching the token, so exposing a configuration value for this would be misleading.  That being said, any layer of caching (both in our library, or on the STS side) will not cache a token until it is expired. There will be a buffer like you suggested, it's just not configurable. I would suggest refreshing the token once a minute to start with, I think this should ensure you will get a new token before the token you are holding expires. However finding an appropriate time might require some trial an error, and it will probably vary depending on the host your running on. I know this isn't ideal, but it's probably the best approach available today.

Regarding the request timings you collected above they seem much higher than I would expect when authenticating with managed identity. What environment did you collect these in? Were you running locally, or deployed to an Azure host with managed identity enabled? If the latter what host were you deploying to.

**Comment by Rookian** [comment]
> Regarding the request timings you collected above they seem much higher than I would expect when authenticating with managed identity. What environment did you collect these in? Were you running locally, or deployed to an Azure host with managed identity enabled? If the latter what host were you deploying to.

The request timings were collected in our productive environment in Azure with managed identity enabled.
- Location: West Europe
- Operating System: Linux
- Service Plan: B2, P1v2 (`AADTokenInjectorDbInterceptor` is shared among different kinds of applications)

I also want to point out that we get login errors from time to time (so far two times) with our current solution (`AADTokenInjectorDbInterceptor`).
>Login failed for user '<token-identified principal>'. 

Stacktrace
>Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'.
   at Microsoft.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnectionAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(DbContext _, Boolean result, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
ClientConnectionId:04d0f339-c552-4a3c-8c5b-31dff55db4e5
Error Number:18456,State:1,Class:14

**Comment by Rookian** [comment]
@schaabs, @pakrym 
Are there any news?
Why does it take so long to get a token?
Do you have any plans to improve Managed Identity token-handling for our scenario in future?

**Comment by schaabs** [comment]
@Rookian, I think we need a bit more information to determine why `GetTokenAsync` is taking so long to get a token. Probably the best place to start would be to collect logs with timing as we create an event source event when `GetToken` is called as well as one when it returns so collecting logs should give us both the credentials which were tried and how long they took to respond.  You should be able to enable such logging by adding an event source listener somewhere in your process startup.

```c#
using AzureEventSourceListener listener = new AzureEventSourceListener(
    (e, message) => Console.WriteLine("[{​​​​​​​​0:HH:mm:ss:fff}​​​​​​​​][{​​​​​​​​1}​​​​​​​​] {​​​​​​​​2}​​​​​​​​", DateTimeOffset.Now, e.Level, message),
    level: EventLevel.Verbose);
```

More information around logging and diagnostics can be found in the [Azure.Identity readme](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/README.md#logging), as well as the [Azure.Core diagnostics documentation](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#custom-logging-callback).

**Comment by Rookian** [comment]
@schaabs 
Here are the collect logs:
```
09:58:39.108 ImportWorker info ImportWorker started.
09:58:39.558 ImportWorker info [08:58:39:558][Informational] DefaultAzureCredential.GetToken invoked. Scopes: [ https://database.windows.net/.default ] ParentRequestId:
09:58:39.566 DefaultAzureCredential.GetToken info [08:58:39:565][Informational] EnvironmentCredential.GetToken invoked. Scopes: [ https://database.windows.net/.default ] ParentRequestId:
09:58:39.575 DefaultAzureCredential.GetToken info [08:58:39:575][Informational] EnvironmentCredential.GetToken was unable to retrieve an access token. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
09:58:39.581 DefaultAzureCredential.GetToken info [08:58:39:581][Informational] ManagedIdentityCredential.GetToken invoked. Scopes: [ https://database.windows.net/.default ] ParentRequestId:
09:58:39.586 DefaultAzureCredential.GetToken info [08:58:39:586][Informational] Probing IMDS endpoint for availability. Endpoint: http://169.254.169.254/metadata/identity/oauth2/token
09:58:39.598 DefaultAzureCredential.GetToken info [08:58:39:598][Informational] IMDS endpoint is did not respond. Endpoint: http://169.254.169.254/metadata/identity/oauth2/token
09:58:39.617 DefaultAzureCredential.GetToken info [08:58:39:617][Informational] ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
09:58:39.642 DefaultAzureCredential.GetToken info [08:58:39:642][Informational] AzureCliCredential.GetToken invoked. Scopes: [ https://database.windows.net/.default ] ParentRequestId:
09:58:40.412 info Now listening on: https://localhost:5001
09:58:40.422 info Application started. Press Ctrl+C to shut down.
09:58:41.461 DefaultAzureCredential.GetToken info [08:58:41:461][Informational] AzureCliCredential.GetToken succeeded. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  ExpiresOn: 2021-03-18T09:48:44.4891800+00:00
09:58:41.473 DefaultAzureCredential.GetToken info [08:58:41:473][Informational] DefaultAzureCredential.GetToken succeeded. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  ExpiresOn: 2021-03-18T09:48:44.4891800+00:00
09:58:41.528 info Refresh token for SQL Server took 2547ms.
09:58:41.940 DefaultAzureCredential.GetToken info [08:58:41:940][Informational] AzureCliCredential.GetToken succeeded. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  ExpiresOn: 2021-03-18T09:48:44.4891800+00:00
09:58:41.946 DefaultAzureCredential.GetToken info [08:58:41:946][Informational] DefaultAzureCredential.GetToken succeeded. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  ExpiresOn: 2021-03-18T09:48:44.4891800+00:00
09:58:41.962 ImportWorker info Refresh token for SQL Server took 2406ms.
```

**Comment by christothes** [comment]
> ```
> 09:58:39.617 DefaultAzureCredential.GetToken info [08:58:39:617][Informational] ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
> 09:58:39.642 DefaultAzureCredential.GetToken info [08:58:39:642][Informational] AzureCliCredential.GetToken invoked. Scopes: [ https://database.windows.net/.default ] ParentRequestId:
> 09:58:40.412 info Now listening on: https://localhost:5001
> 09:58:40.422 info Application started. Press Ctrl+C to shut down.
> 09:58:41.461 DefaultAzureCredential.GetToken info [08:58:41:461][Informational] AzureCliCredential.GetToken succeeded. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  ExpiresOn: 2021-03-18T09:48:44.4891800+00:00
> 09:58:41.473 DefaultAzureCredential.GetToken info [08:58:41:473][Informational] DefaultAzureCredential.GetToken succeeded. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  ExpiresOn: 2021-03-18T09:48:44.4891800+00:00
> 09:58:41.528 info Refresh token for SQL Server took 2547ms.
> 09:58:41.940 DefaultAzureCredential.GetToken info [08:58:41:940][Informational] AzureCliCredential.GetToken succeeded. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  ExpiresOn: 2021-03-18T09:48:44.4891800+00:00
> 09:58:41.946 DefaultAzureCredential.GetToken info [08:58:41:946][Informational] DefaultAzureCredential.GetToken succeeded. Scopes: [ https://database.windows.net/.default ] ParentRequestId:  ExpiresOn: 2021-03-18T09:48:44.4891800+00:00
> 09:58:41.962 ImportWorker info Refresh token for SQL Server took 2406ms.
> ```

Hi @Rookian - According to this log output, the IMDS endpoint was not available and the GetToken request fell back to the `AzureCliCredential`, which is known to be relatively slow. In which environment were these logs collected (on an Azure VM, on a local dev machine, etc)?

**Comment by cornillemichiel** [comment]
Seeing this as well on app service.  Using active directory default in connection string with default EF core setup.  Are we supposed to somehow modify the underlying list of credentials used in the default credential so that it wouldn't use the azure cli one? Is that really what makes it slow? Or is it just the endpoint "warming up"?
