### ISSUE TITLE
[FEATURE REQ] Add blockBlob.DownloadTextAsync() on "Azure.Storage.Blobs" 12.7.0

### ISSUE THREAD

**Issue by najrul-islam** [Azure/azure-sdk-for-net#17732]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
can we have like "blockBlob.DownloadTextAsync()", Which is not exist in "Azure.Storage.Blobs" 12.7.0 but it was exist on previous "Microsoft.Azure.Storage.Blob" 11.1.6.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by seanmcc-msft** [comment]
Hi @najrul-islam,

You can get the same functionality with the following:
```
            using FileStream fileStream = new FileStream(path, FileMode.Create);
            await blockBlobClient.DownloadToAsync(fileStream);
```

-Sean

**Comment by najrul-islam** [comment]
sorry my mistake, I was asking for "blockBlob.DownloadTextAsync()" on "Azure.Storage.Blobs" 12.7.0 version.

**Comment by amnguye** [comment]
@seanmcc-msft @kasobol-msft what do you think of this feature request? We will probably have to iron out the details if we go through with this. Looks like if we let the user set the `Encoding` then they are free to alter how the text gets returned. Maybe a concern I would have is if the `string` returned by the API is too large and so forth (however hopefully the user knows this and would limit or use a stream instead).

Ideally we would want customers to use stream

In v11 the API looks like this
```
/// <summary>
        /// Initiates an asynchronous operation to download the blob's contents as a string.
        /// </summary>
        /// <param name="encoding">An object that indicates the text encoding to use.</param>
        /// <param name="accessCondition">An <see cref="AccessCondition"/> object that represents the condition that must be met in order for the request to proceed.</param>
        /// <param name="options">A <see cref="BlobRequestOptions"/> object that specifies additional options for the request.</param>
        /// <param name="operationContext">An <see cref="OperationContext"/> object that represents the context for the current operation.</param>
        /// <param name="progressHandler"> A <see cref="System.IProgress{StorageProgress}"/> object to handle <see cref="StorageProgress"/> messages.</param>
        /// <param name="cancellationToken">A <see cref="CancellationToken"/> to observe while waiting for a task to complete.</param>
        /// <returns>A <see cref="Task{T}"/> object of type <c>string</c> that represents the asynchronous operation.</returns>
        [DoesServiceRequest]
        public virtual async Task<string> DownloadTextAsync(Encoding encoding, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext, IProgress<StorageProgress> progressHandler, CancellationToken cancellationToken)
        {
            using (SyncMemoryStream stream = new SyncMemoryStream())
            {
                await this.DownloadToStreamAsync(stream, accessCondition, options, operationContext, progressHandler, cancellationToken).ConfigureAwait(false);
                byte[] streamAsBytes = stream.GetBuffer();
                return (encoding ?? Encoding.UTF8).GetString(streamAsBytes, 0, (int)stream.Length);
            }
        }     
```

For now doing something similar to the body of function in the above code snippet would be an easy mitigation for users if they want to achieve something similar to this.

**Comment by kasobol-msft** [comment]
I think we could explore adding this as an extension package to the main SDK.

**Comment by kasobol-msft** [comment]
@amnguye This might be good candidate to add APIs/extensions that use https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/core/System.Memory.Data .
@tg-msft what do you think?

**Comment by tg-msft** [comment]
Yes.  I'm very much in favor of adding DownloadData/UploadData methods that return/accept BinaryData so we don't have to add DownloadText, DownloadJson, DownloadAvro, DownloadProtobuf, ..., etc.

**Comment by cbailiss** [comment]
Re:
> I'm very much in favor of adding DownloadData/UploadData methods that return/accept BinaryData so we don't have to add DownloadText, DownloadJson, DownloadAvro, DownloadProtobuf, ..., etc.

As someone going through the pain of upgrading from the Microsoft.Azure.Storage.Blob, I think the above statement is unhelpful.  You are basically saying that every Microsoft customer should incur the pain of dealing with these conversions rather than Microsoft doing it once.  It isn't particularly customer-centric.

**Comment by jaschrep-msft** [comment]
For this particular issue of download, it seems we have already introduced [`DownloadContent`](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.downloadcontent) and have just failed to update this issue accordingly.

@cbailiss While I recognize the pain of updating a method name change + return type in many places, such a find/replace feels somewhat trivial compared to everything else involved in migrating from Microsoft.Azure.Storage.Blob to Azure.Storage.Blobs. That said, this can be eased further via extension methods. You could introduce something like the following to your own code that takes advantage of the existing `DownloadContent` API.

```csharp
public static async Task<string> DownloadTextAsync(this BlobBaseClient client)
{
    return (await client.DownloadContentAsync()).Value.Content.ToString()
}
```
I don't remember the exact signature off the top of my head, but you could make the adjustments for this to look exactly the way you want. Then all the existing code using the old method signature pre-migration could avoid needing this update.

**Comment by jaschrep-msft** [comment]
Closing this issue as it appears the need is addressed.
