### ISSUE TITLE
[BUG] Azure.Search.Documents README Index Creation Example Incorrect

### ISSUE THREAD

**Issue by SvenPam** [Azure/azure-sdk-for-net#17737]
**Describe the bug**
README Documentation example for Azure.Search.Documents shows a read-only field being set during instantiation.

**Expected behavior**

Azure.Search.Documents README should show how to correctly set a suggested field.

**Actual behavior (include Exception or Stack Trace)**

Example results in a compilation error: "[CS0200] Property or indexer 'SearchIndex.Suggesters' cannot be assigned to -- it is read only" on lines 298 & 334 (of README).

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
1. Follow README docs on creating a project.
2. Follow steps for creating an index
2. Observe the compilation issue when attempting to set `index.Suggesters`.

**Environment:**
N/A

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please be aware that due to the holidays, responses may be delayed.
