### ISSUE TITLE
[BUG] BlobClient.Uri.AbsoluteUri returns escaped path causing wrong file names

### ISSUE THREAD

**Issue by fabich** [Azure/azure-sdk-for-net#17735]
**Describe the bug**
When adding a "sub folder" to the blobName .net returns a wrong result for the URL and file name compared to e.g. Azure Storage Explorer

**Expected behavior**
The URL looks like this:
`https://xxx.blob.core.windows.net/xxx-public-development/pdf/210104-111027151-0.pdf`
and the filename looks like this:
`210104-111027151-0.pdf`

**Actual behavior (include Exception or Stack Trace)**
The URL looks like this:
`https://xxx.blob.core.windows.net/xxx-public-development/pdf%2F210104-111027151-0.pdf`
and the filename looks like this:
`pdf_210104-111027151-0.pdf`

**To Reproduce**
```csharp
public async Task<string> UploadPDFReturnURLAsync(PDFCreateInternalDTO dto)
{
            const string folderName = "pdf";
            var fileName = $"{folderName}/{DateTime.Now:yyMMdd-hhmmssfff}-{dto.PDFType}.pdf";

            var blob = Container.GetBlobClient(fileName);

            dto.PDFMemoryStream.Seek(0, SeekOrigin.Begin);
            await using var fileStream = dto.PDFMemoryStream;
            await blob.UploadAsync(fileStream);

            return blob.Uri.AbsoluteUri;
}
```

**Environment:**
 - Name and version of the Library package used: `Azure.Storage.Blobs 12.7.0`
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
 ```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.401 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
 - IDE and version : `Microsoft Visual Studio Professional 2019 Version 16.8.3`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by seanmcc-msft** [comment]
This is by design.  The service considers '/' and '%20' to be the same character.  See https://github.com/Azure/azure-sdk-for-net/issues/16460, https://github.com/Azure/azure-sdk-for-net/issues/15902, https://github.com/Azure/azure-sdk-for-net/issues/15064, and https://github.com/Azure/azure-sdk-for-net/issues/14857.

**Comment by fabich** [comment]
@seanmcc-msft thank you for your answer.
what is the indented way of saving a file in a "sub folder" and getting it's AbsoluteUri?

**Comment by fabich** [comment]
`return $"https://{blob.Uri.Host}{blob.Uri.LocalPath}";` seems to work yet `return blob.Uri.AbsoluteUri;` does not.
IMHO it is hard for me to belief that "this is by design"...

**Comment by pharring** [comment]
Ran into this in our service too when we upgraded from the older storage SDK. Definitely an unexpected surprise and caused a user-facing regression which we didn't spot for a long time.

**Comment by chassq** [comment]
Just caught us too. We moved over to the new storage library and the Absolute path and URI are now only partially encoded (e.g. https://<storage account>.blob.core.windows.net/storage-default/new-folder-test**%2F**test-img.jpg). Total change from the old library and causes production problems for us as well. Totally unexpected. If this is by design it needs to be thought through again. Think before you break assumptions people clearly have had and are expecting.
