### ISSUE TITLE
Survey feedback on cosmos table storage[FEATURE REQ]

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk-for-net#17745]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
 Cosmos db

**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
Lacking and lagging-behind support for a good Table storage client for .NET. The current "cosmos-db" flavor one doesn't support injecting a SocketsHttpHandler to control concurrency and connection pooling so it's hard to use in app functions/app services with severely limited tcp connections and SNAT ports.

**Comment by christothes** [comment]
Hi @elraikhm - Could you add a bit more context on what you are not able to accomplish with the [current client version](https://www.nuget.org/packages/Azure.Data.Tables)?

For reference, here is some info on how to control connection pooling with the latest SDK clients, as well as how HTTP client lifetime is managed.

https://devblogs.microsoft.com/azure-sdk/net-framework-connection-pool-limits/
https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/#clients-are-not-disposable-shared-httpclient-as-default
