### ISSUE TITLE
Survey feedback on Azure Function bindings for Event Hubs

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk-for-net#17748]
**Describe the bug**
Please provide a description of the issue you're seeing.
" func.exe seems to be using the older Microsoft.Azure.EventHubs library and precludes functions to be written in Azure.Messaging.EventHubs due to parameter types.  Also, checkpointing for event hubs does not seem to checkpoint properly.  Seems to be 2 potential causes: does not honor the ConsumerGroup configured in the function and always uses $Default or fact that the current configuration has UseDevelopmentStorage=true and it is not persisted properly.  This causes all events to be replayed when starting to debug sessions."

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by jsquire** [comment]
@pakrym:  I don't believe there is anything actionable here in the context of the binding updates, but wanted to float it past you to be sure.   Any thoughts would be appreciated.

**Comment by pakrym** [comment]
I think I'm going to close this issue. The migration is already in progress and the checkpointing seems to be working properly there.
