### ISSUE TITLE
Survey feedback on "create if not exist" pattern [FEATURE REQ]

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk-for-net#17743]
**Library or service name.**
Azure.Storage.Blobs

 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
The REST API is sometimes limited, typically for "create if not exist", where the SDK has to make a first REST call that can fail (and logs an error, ugh!) and then if necessary the actual creation. If the REST API cannot evolve then plz at least do not log an error on expected failure.

**Comment by amnguye** [comment]
This is feedback for the REST API not the SDK. I've created a backlog item for this feature request please contact me offline for more detail.
