### ISSUE TITLE
Survey feedback on identity [FEATURE REQ]

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk-for-net#17747]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
 Azure.Identity

**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
For EF targeting an Azure SQL database with AAD, i need to generate a token manually using e.g. DefaultAzureCredential.GetTokenAsync().   The docs on DefaultAzureCredential tell me i need to manage caching myself, but it's hard! Please do it for me, e.g. make that AsyncLock class public or something.    The hard bits are:   1) making sure only one request is active at a time, and getting all the other waiters to wait on a task (i.e. yield their threads), and   2) managing the refresh. How soon should i refresh the token? Is 5 mins to expire safe? 1 minute?   3) understanding whether DefaultAzureCredential is doing any caching itself. e.g. What if i try to refresh when there is 10 mins left, but DefaultAzureCredential actually caches the token and refreshes when there is only 5 mins left. Then i would be spamming the refresh action but getting the same token for 5 mins.    BTW, ALL the blogs i see on the internet for this case (EF core manual AccessToken generation) are doing it wrong; none of them are caching the result.

**Comment by christothes** [comment]
Hi @elraikhm - Would [this feature](https://github.com/Azure/azure-sdk-for-net/issues/12145) to add support for Azure SQL authentication address your issue, or is this generally a feature request for token caching?
