### ISSUE TITLE
[MetricsAdvisor] Add validation for updating DataFeed.Administrators

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#17766]
Possibly depends on: https://github.com/Azure/azure-sdk-for-net/issues/17765

No new tests need to be added, but the set up and validation in the `DataFeedLiveTests.UpdateWithEveryMember` can be improved.

The setup is expected to happen in the helper method `SetOptionalMembers`, while the validation happens in `ValidateUpdatedDataFeedWithOptionalMembersSet`, as we do to other properties.

**Comment by ibocon** [comment]
Hi, I am interested in contributing this issue.

I cannot find `TODO: add administrator update validation` in **Azure.AI.MetricsAdvisor** solution.

I found similar existing tests in **DataFeedLiveTests**. (`Update...DataFeedWithEveryMemberAnd...`)

https://github.com/Azure/azure-sdk-for-net/blob/a4f6ce0975f8e8c467b1521f5a39fdcfcfec56c8/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/MetricsAdvisorAdministrationClient/DataFeedLiveTests.cs#L781-L801

Is this test case a good starting point to contribute this issue?

**Comment by kinelski** [comment]
Hello @ibocon, and thank you for showing interest in contributing!

You're right. We changed these tests a lot after I created this issue, so the TODO comment was lost at some point.

The tests you mentioned were recently merged into a single `UpdateWithEveryMember` test, where we expect to validate the `DataFeed.Administrators` property:
https://github.com/Azure/azure-sdk-for-net/blob/dc6d5577ec3b6cb2fd97c5316d9b21c73a0e1922/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/MetricsAdvisorAdministrationClient/DataFeedLiveTests.cs#L367-L392

I'll update the issue description accordingly.

Also, I mentioned this issue may depend on https://github.com/Azure/azure-sdk-for-net/issues/17765, but as long as we don't trigger the bug in our tests, it won't be blocking.

I'll assign this issue to you. Let me know if you have any questions!

**Comment by ibocon** [comment]
@kinelski I have a question.

According to comments on `SetOptionalMembers` and `ValidateUpdatedDataFeedWithOptionalMembersSet` in `DataFeedLiveTests.cs` and the issue description you recently updated, What I need to do is to check `dataFeed.Administrators` is not changed or changed correctly after call `adminClient.UpdateDataFeedAsync(dataFeedToUpdate)`. Do I understand correctly what is expected be solved?

https://github.com/Azure/azure-sdk-for-net/blob/dc6d5577ec3b6cb2fd97c5316d9b21c73a0e1922/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/MetricsAdvisorAdministrationClient/DataFeedLiveTests.cs#L970-L978

https://github.com/Azure/azure-sdk-for-net/blob/dc6d5577ec3b6cb2fd97c5316d9b21c73a0e1922/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/MetricsAdvisorAdministrationClient/DataFeedLiveTests.cs#L1135-L1138

If I understand it right way, I can see code that solving issue in `ValidateUpdateedDataFeedWithOptionalMembersSet` method.

https://github.com/Azure/azure-sdk-for-net/blob/dc6d5577ec3b6cb2fd97c5316d9b21c73a0e1922/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/MetricsAdvisorAdministrationClient/DataFeedLiveTests.cs#L1140-L1147

So, I read [DataFeed.Administrators](https://docs.microsoft.com/en-us/dotnet/api/azure.ai.metricsadvisor.models.datafeed.administrators?view=azure-dotnet#Azure_AI_MetricsAdvisor_Models_DataFeed_Administrators) document to search other things to validate.

> If MetricsAdvisorKeyCredential authentication will be used, the string must be the user's email address. If AAD authentication will be used instead, the string must uniquely identify the user's principal. For instance, for a ClientSecretCredential, the string must be the client ID.

I can see current test code does not validate **client ID**, but I can not sure it is worth to test.

Or should I do prepare live test, even if it will be failed by #17765?
