### ISSUE TITLE
ARM template deployment does not work when Parameter property is used

### ISSUE THREAD

**Issue by ravbhatnagar** [Azure/azure-sdk-for-net#1777]
An unhandled exception of type 'Microsoft.Rest.Azure.CloudException' occurred in mscorlib.dll

Additional information: The request content was invalid and could not be deserialized: 'Error converting value "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.$schema', line 291, position 100.'.

var deployment = new Deployment();
            deployment.Properties = new DeploymentProperties
            {
                Mode = DeploymentMode.Incremental,
                Template = templateFileContent,
                Parameters = parameterFileContent
            };

File contents are being read as follows:
JObject parameterFileContent = GetJsonFileContents(pathToParameter);
public static JObject GetJsonFileContents(string pathToJson)
        {
            JObject templatefileContent = new JObject();
            using (StreamReader file = File.OpenText(pathToJson))
            {
                using (JsonTextReader reader = new JsonTextReader(file))
                {
                    templatefileContent = (JObject)JToken.ReadFrom(reader);
                    return templatefileContent;
                }
            }

        }

**Comment by blumu** [comment]
There is a design issue with the API. This API is expecting a JObject from version 6.0 of JSon.net as input to the template parameter. If you program uses a more recent version of JSon.net (e.g. 8.0) the call will fail with the following error:

	'Error reading string. Unexpected token: StartArray. Path 'properties.template.$schema', line 4, position 19.'.

**Comment by ravbhatnagar** [comment]
This should be fixed.

**Comment by blumu** [comment]
@ravbhatnagar In which version of the Nuget is this fixed?

**Comment by TianoMS** [comment]
@blumu you can get the fix with version>=1.1.5-preview. 

With the fix, you don't need to parse the Template and Parameters to JObject now. You can just pass in them as string, and it should just work. Like this:

                var deployment = new Deployment
                {
                    Properties = new DeploymentProperties()
                    {
                        Template = File.ReadAllText(Path.Combine("path", "template.json")),
                        Parameters = File.ReadAllText(Path.Combine("path", "parameters.json")),
                        Mode = DeploymentMode.Incremental,
                    }
                };

**Comment by blumu** [comment]
@TianoMS I'm guessing you are referring to nuget [Microsoft.Azure.Management.ResourceManager](https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceManager/) which I am guessing is now replacing  [Microsoft.Azure.Management.Resources](https://www.nuget.org/packages/Microsoft.Azure.Management.Resources/)? I actually tried the latest version of this package (1.3.1) and got a weird error:

```
One or more errors occurred.The request content was invalid and could not be deserialized: 'Error converting value "{
 "myTemplateParameter": {
    "value": "ed103462dsfasdf"
 }
 }" to type 'System.Collections.Generic.Dictionary`2[System.String,Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition]'. Path 'properties.parameters', line 78, position 424.'.
```

Is the Azure REST API now expecting a different format for the `Parameters` field?

**Comment by TianoMS** [comment]
@blumu Yes, Microsoft.Azure.Management.ResourceManager is the right one. As for the error, it looks like your template/parameters file doesn't have the right format. Check this repo for examples: https://github.com/Azure/azure-quickstart-templates.

**Comment by blumu** [comment]
@TianoMS  The template parameter files on azure-quickstart have a different format from the one documented by the Azure REST API on MSDN. In particular they contain the extra `$schema` headers and have the parameters listed under a `parameters` subnode:
```
{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "addressPrefix": {
      "value": "10.0.0.0/16"
    },
    "subnetPrefix": {
      "value": "10.0.0.0/24"
    }
  }
}
```
This format does not seem right either given that the Azure frontend attempts to deserialize the input to a `Dictionary<string,DeploymentParameterDefinition>`

Do you have a working example showing how to use the new `Microsoft.Azure.Management.ResourceManager` API by any chance?

**Comment by blumu** [comment]
OK, so that was it. The new Nuget (named `Microsoft.Azure.Management.ResourceManager`) introduces a breaking change: you now need to specify the entire template parameter file content including the `$schema` and `contentVersion` field, as opposed to just the `"paramters" : { }` node like in previous version of the nuget (`Microsoft.Azure.Management.Resources`).

**Comment by nakhanha** [comment]
I am hitting 

https://github.com/Azure/azure-sdk-for-net/issues/8314

**Comment by nakhanha** [comment]
@blumu 

Any inputs ?
