### ISSUE TITLE
[BUG] EventHubProducerClient times out on all future SendAsync requests after null reference

### ISSUE THREAD

**Issue by tekking** [Azure/azure-sdk-for-net#17792]
**Describe the bug**
In our application we use a singleton EventHubProducerClient for sending batches of EventData to an eventhub. We ran into an issue where all SendAsync calls on the instance would start to return timeout exceptions.

It turned out that this started each time after the SendAsync method was accidentally called with an empty list of EventData. Doing so results in a null-reference exceptions on that method call (which is not a major issue). It appears that this somehow breaks the underlying connection within the EventHubProducerClient, since all other calls (with valid input) to SendAsync afterwards result in a timeout. 
This seems to fix itself after exactly 30 minutes, at which point all requests to SendAsync succeed again (until another call with empty list is made). 

We have a fine fix for the problem in our case (just check if the list is empty before calling SendAsync), but it seems weird that all future calls to the same client also break.

**Expected behavior**
Calling SendAsync with an empty list does not influence future calls to the same EventHubProducerClient.

**Actual behavior (include Exception or Stack Trace)**
Calling EventHubProducerClient.SendAsync with an empty list of EventData results in a null-reference 
![image](https://user-images.githubusercontent.com/6793200/103785254-496b6680-503b-11eb-9e11-e717d2b43d84.png)

Afterwards calling the SendAsync method on the same client results in a timeout on any request (for the next 30 minutes). 
![image](https://user-images.githubusercontent.com/6793200/103785129-20e36c80-503b-11eb-85b1-c173fe2be926.png)

The issue resolves itself after 30 minutes, I suspect because the AMQP connection times out and is reset.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. EventhubProducerClient is created (as a singleton) using connectionstring to eventhub (SAS policy)
 `this.producerClient = new EventHubProducerClient(connectionString, null, null)`
2. Call SendAsync on producerClient with an empty IEnumerable (resulted in nullreference).
3. Call SendAsync on same producerClient with a non-empty IEnumerable (resulted in Timeout).
4. Wait 30 minutes.
5. Call SendAsync on same producerClient with a non-empty IEnumerable (succeeds).

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.Eventhubs (v5.2.0)
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Reproduced issue both on Azure Function v3 (windows/.net) and local devmachine .NET sdk v3.1.402 and host version 3.1.8.
 - IDE and version : When running locally, Visual Studio 16.7.5

**Comment by jsquire** [comment]
Hi @tekking.  Thank you for your feedback and we regret that you're experiencing difficulties.  This was indeed a bug in the AMQP transport that the client uses to interact with the service.   We fixed this as part of #15034 for both overloads of `SendAsync`.  The producer client now tests for an empty batch or empty set of events and avoids making the unnecessary service call.   

The change will be included in v5.3.0 when it is released.  Unfortunately, there is no committed date at present, but we expect that to land in the next 90 days.  The fix is currently is available in the v5.3.0-beta.4 on [NuGet](https://www.nuget.org/packages/Azure.Messaging.EventHubs/5.3.0-beta.4).

**Comment by tekking** [comment]
That's good to know! I've just ran some checks in our application using the prerelease -beta4 version and can confirm this fixes the issue. In fact it appears the sendAsync now handles empty lists as valid input (it no longer throws an exception). 

I'll close this issue and keep an eye out for the stable release of 5.3.0, thanks for the fast response!
