### ISSUE TITLE
Missing more information link in summary

### ISSUE THREAD

**Issue by gnabgib** [Azure/azure-sdk-for-net#17795]
In the summary section of *DataLakePathClient.SetAccessControlRecursive* the last paragraph seems to be lacking a link to further documentation.

Current state: "For more information, see ."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d7bf759a-798d-1a9f-907f-5fe18249f08e
* Version Independent ID: 25150b6a-0c84-273a-2987-2f99afe7756b
* Content: [DataLakePathClient.SetAccessControlRecursive(IList&lt;PathAccessControlItem&gt;, String, AccessControlChangeOptions, CancellationToken) Method (Azure.Storage.Files.DataLake) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakepathclient.setaccesscontrolrecursive?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Files.DataLake/DataLakePathClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.DataLake/DataLakePathClient.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by amnguye** [comment]
Closing this issue as the PR was merged.
