### ISSUE TITLE
[BUG] Azure.ResourceManager.Insights fails to create Diagnostic Settings

### ISSUE THREAD

**Issue by coppercosmo** [Azure/azure-sdk-for-net#17836]
**Describe the bug**
Using a valid subscription and service principal to create an InsightsManagementClient, I then use the `CreateOrUpdateAsync` method on the DiagnosticSettings class with valid parameters. In this case I am only needing the Event Hub sink, so I give the proper event hub namespace authorizationRuleId. During this method I am receiving this error: `{"Service request failed.\r\nStatus: 409 (Conflict)\r\n\r\nContent:\r\n{\"code\":\"Conflict\",\"message\":\"The subscription '<SUBSCRIPTION_ID>' is not registered to use microsoft.insights.\"}\r\n\r\nHeaders:\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nStrict-Transport-Security: REDACTED\r\nx-ms-request-id: REDACTED\r\nServer: Microsoft-IIS/10.0\r\nx-ms-ratelimit-remaining-subscription-resource-requests: REDACTED\r\nx-ms-correlation-request-id: REDACTED\r\nx-ms-routing-request-id: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nDate: Wed, 06 Jan 2021 23:27:24 GMT\r\nContent-Length: 132\r\nContent-Type: application/json; charset=utf-8\r\nExpires: -1\r\n"}`

To make sure the subscription I am using actually is registered to use `microsoft.insights` I go to the Azure Portal and go to Subscriptions -> My Subscription -> Resource Providers -> Microsoft.Insights and I do indeed see a green checkmark. I have also tried this with a separate subscription and service principal, with the same result. 

I have tried this with the storage account in one subscription, while the event hub sink is in a different subscription, and this yields the same error. I have also tried this with the storage account and the event hub in the same subscription, which also yields the same error. I have also tried this while changing the sink to serviceBus and changing the sink to storageAccount, with the same error.

**Expected behavior**
The expected behavior is that this InsightsManagementClient and DiagnosticSettings class can create diagnostic settings and send the logs to the configured event hub sink. The expected behavior is also that when the Azure Portal tells me that my subscriptions are registered to use `microsoft.insights`, this library also agrees that my subscription is registered to use that resource provider.

**Actual behavior (include Exception or Stack Trace)**
`{"Service request failed.\r\nStatus: 409 (Conflict)\r\n\r\nContent:\r\n{\"code\":\"Conflict\",\"message\":\"The subscription '<SUBSCRIPTION_ID>' is not registered to use microsoft.insights.\"}\r\n\r\nHeaders:\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nStrict-Transport-Security: REDACTED\r\nx-ms-request-id: REDACTED\r\nServer: Microsoft-IIS/10.0\r\nx-ms-ratelimit-remaining-subscription-resource-requests: REDACTED\r\nx-ms-correlation-request-id: REDACTED\r\nx-ms-routing-request-id: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nDate: Wed, 06 Jan 2021 23:27:24 GMT\r\nContent-Length: 132\r\nContent-Type: application/json; charset=utf-8\r\nExpires: -1\r\n"}`

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. New up the InsightsManagementClient with proper subscription and service credentials.
`var insightsManagementClient = new InsightsManagementClient(subscriptionId, clientCredentials);`

2. Try to create the DiagnosticSettings using the above InsightsManagementClient.
`        
                public class DiagnosticSettingsClient : IDiagnosticSettingsClient
                {
                private readonly InsightsManagementClient _insightsManagementClient;
        
            public DiagnosticSettingsClient(InsightsManagementClient insightsManagementClient)
            {
                _insightsManagementClient = insightsManagementClient;
            }
        
            public async Task CreateDiagnosticSettingsAsync(ResourceGroup resourceGroup, DiagnosticSettings diagnosticSettings)
            {
                try
                {
                    var parameters = diagnosticSettings.PrepareParameters();
        
                    var result = await _insightsManagementClient.DiagnosticSettings.CreateOrUpdateAsync(diagnosticSettings.ResourceUri, diagnosticSettings.Name, parameters);
                }
                catch (Exception e)
                {
                }
            }
        }
`

**Environment:**
 - Name and version of the Library package used: [Azure.ResourceManager.Insights 1.0.0-preview.1] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [.NET Core 3.1]
 - IDE and version : [Visual Studio Enterprise 2019 16.8.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by JonathanCrd** [comment]
@jsquire after investigating, this seems to be a service issue, but when adding the Service Attention label the bot is not assigning someone from the service team. Can you help routing to the proper person in that team?

**Comment by jsquire** [comment]
> @jsquire after investigating, this seems to be a service issue, but when adding the Service Attention label the bot is not assigning someone from the service team. Can you help routing to the proper person in that team?

Sure thing.  I'm not entirely sure the proper path, but am hoping the Monitor team can offer guidance if needed.

**Comment by coppercosmo** [comment]
Any update on this?

**Comment by coppercosmo** [comment]
Bump

**Comment by allenjzhang** [comment]
With `microsoft.insights` shows up as a registered provider in my sub, I was **unable** to repro this issue. 

Here are some suggestions:
1. Verify the subscription id is correct
2. Reregister the provider. You can click on re-register while selecting the `microsoft.insights` in the portal.

If you still not having any luck, please let us know. I have updated the area to ARM.

**Comment by coppercosmo** [comment]
@allenjzhang Does re-registering a resource provider break existing resources that depend on that resource provider?

**Comment by coppercosmo** [comment]
@allenjzhang ^

**Comment by allenjzhang** [comment]
No, it does not.
