### ISSUE TITLE
Need sample for Blob Storage lifecycle management 

### ISSUE THREAD

**Issue by blrchen** [Azure/azure-sdk-for-net#17834]
**Query/Question**
Is manage Azure Blob Storage lifecycle policy supported by DotNet SDK? If yes, can you please provide a how to sample. 

**Environment:**
 - Name and version of the Library package used: [Azure.Storage.Blobs 12.7.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Core 3.1
 - IDE and version : [eVisual Studio 16.8.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by amnguye** [comment]
Just for reference are you referring to
https://azure.microsoft.com/en-us/blog/azure-blob-storage-lifecycle-management-now-generally-available/
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-lifecycle-management-concepts?tabs=azure-portal ?

Looks like creating management policies through the management plane storage SDK.
@blueww is there a feature like this in the management storage SDK or is there a sample available?

**Comment by blrchen** [comment]
Correct i am looking for sample on how to use DotNet Storage SDK for storage lifecycle management

**Comment by blrchen** [comment]
I seems found it: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Microsoft.Azure.Management.Storage/src/Generated/Models/ManagementPolicyBaseBlob.cs
