### ISSUE TITLE
Incorrect text displayed back to users

### ISSUE THREAD

**Issue by gewarren** [Azure/azure-sdk-for-net#17848]
---
**Issue moved from MicrosoftDocs/feedback#2853**
- Please respond to @mniem.

---

_From @mniem on Thursday, June 11, 2020 9:09:40 PM_

Issue is on [this ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.site.clientaffinityenabled?view=azure-dotnet) page.

Gets or sets **&lt;**code**&gt**;true&lt;/code&gt; to enable client affinity; &lt;code&gt;false&lt;/code&gt; to stop sending session affinity cookies, which route client requests in the same session to the same instance. Default is &lt;code&gt;true&lt;/code&gt;.

**Comment by AlexGhiondea** [comment]
This seems to come from this line in the swagger: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-09-01/CommonDefinitions.json#L1812 

And the generated code seems to not handle the 'code' tags very well.

**Comment by gewarren** [comment]
@rloutlaw How should the true/false values be formatted in the JSON?

**Comment by calvinsID** [comment]
@AlexGhiondea weird, that file was copied directly from the previous version 2020-06-01, which also has the <code></code> tags

**Comment by AlexGhiondea** [comment]
@calvinsID yeah ... I don't think that ever showed up correctly 🙁.

**Comment by navba-MSFT** [comment]
@gewarren Apologies for the late reply. We will update this thread once we have more details.

@calvinsID Could you please update this github thread once you get a chance ? Awaiting your reply.

**Comment by calvinsID** [comment]
Let me find the code owners in the backend repo that generates this, and tag them
