### ISSUE TITLE
Investigate Docs CI Pipline - ServiceBus XML Not Updating

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-net#17850]
Josh reached out with a question as to why a specific member of the servicebus library wasn't properly reflecting what the published package actually had. [This member specifically](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.body?view=azure-dotnet#remarks)

The .NET CI Job runs at least once daily.

That is easily visible [here](https://github.com/Azure/azure-docs-sdk-dotnet/commits/smoke-test/xml).

However, for _some_ reason that this issue exists to answer, it was only after I _deleted_ the existing `Azure.Messaging.ServiceBus` that new updates were actually written:

![image](https://user-images.githubusercontent.com/45376673/103968756-46df3e80-5119-11eb-893c-1035924bd5ee.png)

This is _doubly_ confusing because this package is obviously showing up under the `azure-dotnet` (read: latest) moniker!

This is a docs pipeline bug _somewhere_, need to run it down and either resolve it or come up with a workaround on our end.

**Comment by danieljurek** [comment]
Investigation revealed that this is an issue in the internal processes. An appropriate bug has been filed. Will re-open if we should fix it ourselves.
