### ISSUE TITLE
[Test Coverage] Connection String parsing tests for Case Insensitivity

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#17856]
https://github.com/Azure/azure-sdk-for-net/pull/17642

This PR needs more tests for the cases of parsing a storage connection string. Namely going down the code paths of parsing connection strings of AllRequired, Optional, AtLeastOne, None, MatchesAll.

**Comment by JimSuplizio** [comment]
Hi @amnguye, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
