### ISSUE TITLE
[BUG] Error in using BlobClient.OpenRead, the file stream positions are not correct.

### ISSUE THREAD

**Issue by XiangweiTang** [Azure/azure-sdk-for-net#17851]
**Describe the bug**
Error in using BlobClient.OpenRead, the file stream positions are not correct.

**Expected behavior**
When we use FileStream.Read(byte[] buffer, int offset, int count), we expect the file stream position to move forward "count" bytes. 

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
In one certain file, the forward bytes were not correct.
When I download the files to local, the read were correct.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

The target is to verify if two wave file content are identical. 
1. Two wave files in local, using FileStream to read and compare them are the same. Code runs as expected.
2. Upload these two wave files to Azure, using BlobClient.OpenRead, most of the time, the performances are good, but in some certain positions, the Read got problem.
3. The following is the output. 
Normally, two columns, left one is the position of the first file stream, the right one is the position of the second file stream.
The left one reads from offset 112, right one reads from offset 108, and both of them read a 10_000 bytes buffer at the same time.
However, after reading position 4190112 and 4190108, they both blocked at 4194324, and then continue to jump 10_000 as normal.
4. The local read(using filestream) also call this code as sub-process, and the local result is normal, so I suspect the problem is not the stream part, it is the azure part.
5. This bug can be reproduced in another Azure path.
6. The file itself is classified, and I'm not sure if I can provide it directly. If you really need the file itself to repro the bug, I'll need a permission for this.

Output:
4120112 4120108
4130112 4130108
4140112 4140108
4150112 4150108
4160112 4160108
4170112 4170108
4180112 4180108
4190112 4190108    <===Still normal here, 10_000 bytes every step.
4194324 4194324    <===Problem comes out.
4204324 4204324    <===Normal again, with a wrong start up.
4214324 4214324    

Code of read Azure file to stream:
```
public static Stream ReadBlobToStream(string uriString)
        {
            Uri uri = new Uri(uriString);
            BlobClient client = new BlobClient(uri);
            return client.OpenRead(new BlobOpenReadOptions(false));
        }
```

Code of compare two stream. 
```
public static bool BinaryIdentical(Stream fs1, int offset1, Stream fs2, int offset2)
        {
            const int BUFFER_SIZE = 10_000;   
            fs1.Seek(offset1, SeekOrigin.Begin);   // Read the stream from a certain offset.
            fs2.Seek(offset2, SeekOrigin.Begin);   // Read anothe stream
            byte[] buffer1 = new byte[BUFFER_SIZE];
            byte[] buffer2 = new byte[BUFFER_SIZE];
            while (fs1.Position < fs1.Length)
            {
                try
                {
                    int p=fs1.Read(buffer1, 0, BUFFER_SIZE);   // Each time, read a 10_000 size block into buffer.
                    int q=fs2.Read(buffer2, 0, BUFFER_SIZE);   // For both streams.
                    Console.WriteLine($"{fs2.Position}\t{fs1.Position}");   // Output the current position for the two streams.
                    if (fs2.Position - fs1.Position == offset2 - offset1)
                        ;
                    else
                        ;
                    if (buffer1.SequenceEqual(buffer2))
                        continue;
                    //return false;
                }
                catch
                {
                    return false;
                }
            }
            return true;
        }
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

All of these are from nuget.org:
Azure.Core 1.7.0 
Azure.Storage.Blobs 12.17.0
Azure.Storage.Common 12.6.0

OS: Windows Server 2016 Datacenter(an Azure machine).

IDE: Visual studio 2019 Community 16.8.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by amnguye** [comment]
Do you have an approximate file size that this issue keeps occurring to? Also is this only on WAV files?

**Comment by XiangweiTang** [comment]
> Do you have an approximate file size that this issue keeps occurring to? Also is this only on WAV files?

I don't know, because even 99% of the waves I processed are correct, For now there is only one wave got this problem. So it might be some special case. So it is hard to say if other files could have same problem.

**Comment by XiangweiTang** [comment]
> Do you have an approximate file size that this issue keeps occurring to? Also is this only on WAV files?

For the file itself, it is around 8.7MB. The files larger or smaller doesn't show similar problem.

**Comment by amnguye** [comment]
Have you attempted to call OpenRead on this particular file again and were you able to run into the same exact problem? Maybe there's something that can only be reproduced with this particular WAV file. If so we might have to take this to email.

**Comment by XiangweiTang** [comment]
> Have you attempted to call OpenRead on this particular file again and were you able to run into the same exact problem? Maybe there's something that can only be reproduced with this particular WAV file. If so we might have to take this to email.

Sorry for this late reply:
1. I tried this code on the specific wav file several times. And the problem could be reproduced.
2. There are also a few other files had the similar problem.
3. Most of the case this code works fine.

**Comment by amishra-dev** [comment]
@XiangweiTang could you please reactivate if you are still facing this?
