### ISSUE TITLE
[Storage Client] Clarify if an integrity check is done as part of the copy operation

### ISSUE THREAD

**Issue by WillComply** [Azure/azure-sdk-for-net#17866]
Please state in the remarks section whether or not an integrity check such as an MD5 comparison is performed, and if the result has an effect on the blob's [CopyStatus property.](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobproperties.copystatus?view=azure-dotnet#Azure_Storage_Blobs_Models_BlobProperties_CopyStatus)

This also applies to the following related pages:
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.startcopyfromuri?view=azure-dotnet
https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd0e00b-df56-46f2-be22-3949805f85d3
* Version Independent ID: e106e179-f3d8-30ad-14ea-2bbc06772f17
* Content: [BlobBaseClient.StartCopyFromUriAsync(Uri, BlobCopyFromUriOptions, CancellationToken) Method (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.startcopyfromuriasync?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
I'm under the impression that the service does not do an integrity check for the copy blob operation. I think the [original reference document](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob) would need to be updated and the copy blob API can just reference this link. That way we don't have to end up updating all documents related to this operation, in the case that if there's any changes or updates.

@tamram What do you think about adding this ? or does it seem overkill to specify everything the API features and does not feature.

**Comment by WillComply** [comment]
> I'm under the impression that the service does not do an integrity check for the copy blob operation. I think the [original reference document](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob) would need to be updated and the copy blob API can just reference this link. That way we don't have to end up updating all documents related to this operation, in the case that if there's any changes or updates.
> 
> @tamram What do you think about adding this ? or does it seem overkill to specify everything the API features and does not feature.

Thanks for the update, updating just the original reference document would be fine.

I agree that it's unnecessary to specify all aspects of the API, but I do think that it's important to communicate that the API makes no guarantees about the integrity of the copied blob. The fact that the API simply copies over the Content-MD5 property of the blob led to some confusion on my part about file integrity.

**Comment by amnguye** [comment]
Now that I looked over your original issue, you're using the StartCopyFromUri API and not the regular API that calls the regular Copy Blob operation.

So actually the [Copy Blob From Url](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) does allow you to specify the `x-ms-source-content-md5` header so the storage service does the proper checks you are looking for between the source and destination.
![image](https://user-images.githubusercontent.com/48961492/104359421-7fd63500-54c4-11eb-8dea-a8554c7d4448.png)

**Comment by amnguye** [comment]
I will also look to update the StartCopyFromUri API to reference the correct document Copy Blob from URL , instead of the regular Copy Blob article.

**Comment by WillComply** [comment]
> Now that I looked over your original issue, you're using the StartCopyFromUri API and not the regular API that calls the regular Copy Blob operation.
> 
> So actually the [Copy Blob From Url](https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob-from-url) does allow you to specify the `x-ms-source-content-md5` header so the storage service does the proper checks you are looking for between the source and destination.
> ![image](https://user-images.githubusercontent.com/48961492/104359421-7fd63500-54c4-11eb-8dea-a8554c7d4448.png)

Thanks for clarifying, this is very helpful. Just to confirm, the SDK doesn't support this header yet right? I'm looking at the [BlobRequestConditions](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobrequestconditions?view=azure-dotnet) and seeing only a handful of these headers supported.
