### ISSUE TITLE
[Azure.Data.Tables] Maintianing Existing Timestamp on Add/ Upsert/ Batch

### ISSUE THREAD

**Issue by kieronlanning** [Azure/azure-sdk-for-net#17872]
Is there a means by which we can maintain an entities Timestamp when adding, upserting or when using batch?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
@kieronlanning Could add a bit more context on what it is you are trying to accomplish? If you are asking about how to obtain the Timestamp for entities that are modified as part of a batch operation, you should be able to obtain the ETag value for any of the responses in the header of the responses.

For example:

`response.GetResponseForEntity(entity.RowKey).Headers.ETag`

**Comment by kieronlanning** [comment]
@christothes No, I'm doing a migration between storage accounts - the entities stored use their timestamp in other areas. So when migrating we'd like to be able to maintain the original timestamp, rather than that of the current operation.

**Comment by christothes** [comment]
Ah - Unfortunately, the Timestamp property is only managed by the service and [cannot be modified](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#system-properties).
