### ISSUE TITLE
Breaking change to public API in Microsoft.WindowsAzure.ConfigurationManager 3.2.0

### ISSUE THREAD

**Issue by DixonD-git** [Azure/azure-sdk-for-net#1787]
The signature of `CloudConfigurationManager.GetSetting` was changed by adding `bool outputResultsToTrace` argument. It was done in https://github.com/Azure/azure-sdk-for-net/pull/1693 . Now some compiled code throws `MissingMethodException`, the workaround is to rollback to the previous version of `Microsoft.WindowsAzure.ConfigurationManager`

**Comment by hovsepm** [comment]
@DixonD-git, please use version 3.2.1. This issue is already fixed there.
