### ISSUE TITLE
Links to samples don't work on this page

### ISSUE THREAD

**Issue by PaulTzl** [Azure/azure-sdk-for-net#17876]
Do you have the correct links please?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2b138b-2471-5e90-0a7d-07f8ba5e7ce3
* Version Independent ID: 695b4a2a-7975-075d-db2c-c16250098824
* Content: [Azure compute libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/virtualmachines?view=azure-dotnet)
* Content Source: [api/overview/azure/virtualmachines.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/virtualmachines.md)
* Service: **virtual-machines**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
add @xccc-msft to help

**Comment by xccc-msft** [comment]
@PaulTzl Can you please check if you could find desired sample from [here](https://github.com/Azure/azure-libraries-for-net#ready-to-run-code-samples-for-virtual-machines)? Thanks.

**Comment by weidongxu-microsoft** [comment]
New .NET SDK will be here https://aka.ms/azsdk/dotnet/mgmt
