### ISSUE TITLE
create updated SDK and pwoerShell for Microsoft.OperationalInsights [FEATURE REQ]

### ISSUE THREAD

**Issue by dabenhamMic** [Azure/azure-sdk-for-net#17873]
**Library or service name.** : **Microsoft.OperationalInsights**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
we recently released a new version: 2020-10-01 and require a new SDK and PowerShell update

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by AlexGhiondea** [comment]
@dabenhamMic could you share a bit more information about this? What version did you release? And what would you need help with?

/cc @pakrym

**Comment by dabenhamMic** [comment]
@AlexGhiondea 
we have updated 2 main flows: the first is DedicattedClusters and the other is our Table api's.
we have extended the Table contract.
Cluster is a new feature that is becoming GA.

**Comment by AlexGhiondea** [comment]
@dabenhamMic thanks for that additional information. Unfortunately I am still not sure what is it that you are asking for 🙁. Are you asking for help releasing a new version of the SDK as the service maintainer or are you asking for help figuring out who the service owner is so that they can release a new version of the SDK?

**Comment by dabenhamMic** [comment]
@AlexGhiondea 
I'm asking for help releasing a new version of the SDK :)

**Comment by AlexGhiondea** [comment]
@dabenhamMic got it! Please reach out to me on teams! 🙂

**Comment by scottaddie** [comment]
The `Microsoft.Azure.OperationalInsights` package you're referring to was replaced by [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query). `Azure.Monitor.Query` is based on the [latest stable Swagger file](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/operationalinsights/data-plane/Microsoft.OperationalInsights/stable/2022-10-27/OperationalInsights.json). As for the PowerShell work, that's being tracked at https://github.com/Azure/azure-powershell/issues/16787.
