### ISSUE TITLE
Cognitive Search: How to field map complex types

### ISSUE THREAD

**Issue by snapfisher** [Azure/azure-sdk-for-net#17874]
**Query/Question**
I am setting up an index/indexer with the C# SDK.  I have documents with images.  I am using the ImageAnalysisSkill to get image captions.  I want to then use the MergeSkill to merge the captions with the rest of the text.  

I can merge simple fields, and I can see the captions in my index, but I cannot get the merge to work on the complex field.

The index is: 
```csharp
new ComplexField("description", true)
{
    Fields =
    {
        new SearchableField("tags", true) { IsFilterable = true, IsFacetable = true, IsSortable = false},
        new ComplexField("captions", true)
        {
            Fields =
            {
                new SearchableField("text") { IsFilterable = false, IsFacetable = false, IsSortable = false},
                new SimpleField("confidence", SearchFieldDataType.Double) { IsFilterable = false, IsFacetable = false, IsSortable = false}
            }
        }
    }
},
```

The mapping in the skill I am trying to use is:

```csharp
inputMappings.Add(new InputFieldMappingEntry("itemsToInsert")
{
    Source = @"/document/normalized_images/*/text"
});
```
With a mapping in the indexer of:

```csharp
new FieldMapping(@"/document/normalized_images/*/text") {TargetFieldName = "text"},
```

I have also tried to use as a mapping parameter: "/document/normalized_images/*description/captions/text, for both the skill and indexer.

We don't seem to have any complex examples documented, although we actually have this exact case mentioned in the document as a use for the MergeSkill.

Thanks.

**Environment:**
 - Name and version of the Library package used: Azure.Search.Documents v11.2.0-beta2
 -
 - Hosting platform or OS and .NET runtime version: azure functions runtime, but the same occurs if I run the code in VS Studio locally for debugging (Microsoft.Net.Sdk.Functions 3.0.11)
 
 - IDE and version : Visual Studio 16.8.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by snapfisher** [comment]
Ping.  I hope silence != "can't be done" :-)

**Comment by snapfisher** [comment]
I made some progress and now think that this is an actual bug, or bugs: in both the ImageAnalysisSkill and the MergeSkill

I figured out how to flatten the data in the index, but the merge still fails when trying to use the image description text, but does work correctly if I use OCR text (from the OcrSkill).

I think that the issue is the number of outputs created.  The working ocr text has an entry for each image, even if there is no text.  So the output looks like:  "ocrtext": "[\"DC 15\",\"15\",\"dyson\",\"yson\",\"\",\"\",\"\",\"\",\"\",\"\", but there are no blank entries for the image caption descriptions.  However, there are less descriptions.  The only thing I can surmise is that when the image skill cannot come up with a caption, it produces no output, this causes a mismatch in the array size between the descriptions and the offesets, and the merge skill just does nothing.

The best fix would be for the merge skill to do the best it can, i.e. if there are not enough replacements, it should still try and use what it has.  This should be combined with a change to the image skill so that it produces some output for each image.

I'd like it if you all can confirm my initial request -- i.e. am I just doing something wrong, and if I'm not, one of us can submit this as a proper bug.  Thx.

**Comment by AlexGhiondea** [comment]
@Mohit-Chakraborty  could you take a look?

**Comment by Mohit-Chakraborty** [comment]
@dereklegenzoff, can you please check and let us know the behavior of the skills and if the observed behavior is by design.

**Comment by dereklegenzoff** [comment]
You can use fieldMappings to map fields that aren’t complex. However, for the complex fields, you first need to shape them using a [shaper skill](https://docs.microsoft.com/azure/search/cognitive-search-skill-shaper) and then use an outputFieldMapping to map them the way you want to.

I pasted in a quick example below from another scenario in case it's helpful:

```json
{
    "name": "sql-skillset",
    "description": "",
    "skills": [
        {
            "@odata.type": "#Microsoft.Skills.Util.ShaperSkill",
            "context": "/document",
            "inputs": [
              {
                "name": "City",
                "source": "/document/City"
              },
              {
                "name": "StreetAddress",
                "source": "/document/AddressLine1"
              },
              {
                "name": "StateProvince",
                "source": "/document/StateProvince"
              }
            ],
            "outputs": [
              {
                "name": "output",
                "targetName": "Address"
              }
            ]
          }
    ]
}
```

And then the indexer would have the field mapping like this:
```json
{
    "name": "sql-indexer",
    "dataSourceName": "sql-datasource",
    "targetIndexName": "sql-index",
    "skillsetName": "sql-skillset",
    "fieldMappings": [
        {
            "sourceFieldName": "AddressID",
            "targetFieldName": "id"
        }
    ],
    "outputFieldMappings": [
        {
            "sourceFieldName": "document/Address",
            "targetFieldName": "Address"
        }
    ]
}
```
