### ISSUE TITLE
[WebJobs/EventHubs] Extension migration causes an invalid checkpoint message

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17882]
```
[2021-01-08T20:16:27.746Z] Function 'FunctionApp1.ProcessMessages.Run': An invalid checkpoint was found for partition: '8' of FullyQualifiedNamespace: 'pbatum-track2.servicebus.windows.net'; EventHubName: 'hub1'; ConsumerGroup: '$Default'.  This checkpoint is not valid and will be ignored
```

**Comment by shivanigoyal0705** [comment]
Hi,

We upgraded eventhub packages from 4.2.0 to 5.1.1 and ran into same issue. From issue #17896 I can see change has veen merged but I am still getting same issue

**Comment by shivanigoyal0705** [comment]
> We are also facing this problem, the checkpoints written to blob storage are 0 bytes after upgrading from 4.* to 5.* so we end up consuming the same messages multiple times.

blob storages will be 0 bytes because checkpoints are now stored as properties from event hub 5.* onwards. We had to migrate checkpoints  https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md#migrating-eventprocessorhost-checkpoints

**Comment by furier** [comment]
We use EventHubTrigger with Function App so checkpoints are managed for us,
but we end up with processing the same messages multiple times.

tor. 1. des. 2022 kl. 15:21 skrev shivanigoyal0705 ***@***.***

**Comment by shivanigoyal0705** [comment]
I am also using same way. As a workaround, 
1) First deployed the upgraded function app with all EventHubTriggerFunction in disabled mode to stop re-processing messages immediately.
2) Setup a migration utility using the code shared in migration guide. Ran the utility locally to migrate checkpoint for each event hub.
3) Once checkpoints are restored at new location in new format , re-enabled EventHubTrigger functions . This was manual activity for one-time. By doing this eventhub trigger resumed events from last checkpoint. 
4)Deployed function app again to revert disable setting of event hub trigger functions. This step was to avoid manual intervention for future deployments.
