### ISSUE TITLE
Add Microsoft.Extensions.Azure client registration sample for Azure Functions

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17888]
The sample should show how to register, configure, and resolve a client that doesn't have native Functions extensions.

**Comment by jsquire** [comment]
This scenario is now covered by the [Dependency injection with the Azure SDK for .NET](https://github.com/dotnet/docs/blob/992ff048d2616e8ea95fbb6a8da671513cbc6d1f/docs/azure/sdk/dependency-injection.md).   Closing.
