### ISSUE TITLE
[BUG] Azure Search - Still Cannot $filter by fields containing special characters, even when escaped

### ISSUE THREAD

**Issue by yviouswilliamous** [Azure/azure-sdk-for-net#17907]
Hi,

I still have the problem mentionned in the following [issue](https://github.com/Azure/azure-sdk-for-net/issues/9828)

I have the same problem with escaping a single quote in a filter expression.

I applied the solution you proposed on the SO post. I doubled the single quote. But there is no values in the response.

I use the latest version of the API (2020-06-30).

Here is the request I execute from the Azure search explorer :
search=revue&$filter=(tags/any(tag: search.in(tag/value,'services d''investissement')))

Thank you for your answer.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Mohit-Chakraborty** [comment]
This is not a client SDK issue.
@bleroy, @dereklegenzoff - can you help the customer with their query.

**Comment by brjohnstmsft** [comment]
@Mohit-Chakraborty This was already answered on the [related issue](https://github.com/Azure/azure-sdk-for-net/issues/9828). Closing.
