### ISSUE TITLE
Fixed failed aggregate-report link issue

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-net#17909]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=682937&view=logs&j=10327055-d4d6-50a6-a312-3d2cd4bd9cb9&t=65f0e4aa-f456-5911-deca-bd807ca3354c&l=760

**Comment by AlexGhiondea** [comment]
@jsquire could you take a look at this break?

**Comment by jsquire** [comment]
fixed by: #17919
