### ISSUE TITLE
ComputerVision 6.0.0 gives ComputerVisionErrorException "Operation returned an invalid status code 'NotFound'"

### ISSUE THREAD

**Issue by logtosachin993** [Azure/azure-sdk-for-net#17903]
**ReadInStreamAsync** method in computer vision SDK(6.0.0) throws "**Operation returned an invalid status code 'NotFound**'" calling from container Cognitive Services Computer Vision API(**vision/v3.2-preview.1/read**). 
Container have been configured with :
1)billing endpoint
2)eula -> accept
3)apikey
Cognitive container service Ready returns:
{"service":"computervisionread","ready":"ready","message":"Api is ready.."}
Should we use a different version in container cognitive service for computer vision SDK(6.0.0)? Please help

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by SaurabhSharma-MSFT** [comment]
@logtosachin993 
Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .
