### ISSUE TITLE
DatabaseCreateOrUpdateProperties is missing RestorePointInTime property

### ISSUE THREAD

**Issue by ChristianRygg** [Azure/azure-sdk-for-net#1791]
I'm trying to do a restore in time for an Azure Sql DB, but I get an error:

`BadRequest: The point in time was not specified for restoring live database 'xxxxxxx'.`

I would expect a RestorePointInType property in the DatabaseCreateOrUpdateProperties class, but there doesn't seem to be one. Am I doing it wrong, or is this something which isn't being generated properly from AutoRest?

**Comment by akromm** [comment]
The library has been updated to include the RestorePointInTime property: https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Sql/SqlManagement/Generated/Models/DatabaseCreateOrUpdateProperties.cs
