### ISSUE TITLE
[BUG] Azure FrontDoor Model does not contain its ResourceGroup, making some update paths impossible.

### ISSUE THREAD

**Issue by Ofekw** [Azure/azure-sdk-for-net#17924]
**Describe the bug**
If I fetch all FrontDoors for a given subscription `await frontDoorManagementClient.FrontDoors.ListAsync();` , there is no way to get from the AzureFrontDoor models in the response to the [update path without knowing the resource group](https://github.com/Azure/azure-sdk-for-net/blob/2b594335737a65cb8f36543ef817deaba5c43f4b/sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/src/Generated/FrontDoorsOperationsExtensions.cs#L144) of the AzureFrontDoor beforehand; because the ResourceGroup is not contained within the [FrontDoor model.](https://github.com/Azure/azure-sdk-for-net/blob/2b594335737a65cb8f36543ef817deaba5c43f4b/sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/src/Generated/Models/FrontDoorModel.cs) 

**Expected behavior**
[FrontDoor model.](https://github.com/Azure/azure-sdk-for-net/blob/2b594335737a65cb8f36543ef817deaba5c43f4b/sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/src/Generated/Models/FrontDoorModel.cs) contains resource information such as its ResourceGroup etc so that the update path is always reachable. 

**Environment:**
 - Name and version of the Library package used: "Microsoft.Azure.Management.FrontDoor" Version="3.0.0"

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
@Ofekw, in general, resource definition does not expose ResourceGroup as a property. However, the resource id (FrontDoor.Id) contains the full path to the resource which contains all of the contextual information such as subscription and resource group etc. You can parse the resource group name out using a simple regex.

**Comment by Ofekw** [comment]
Hey @allenjzhang, thank you for the prompt response. 

This is indeed the path we went with - however I'd still urge you consider this feedback. Requiring regex to extract unstructured data from a model in order to satisfy the update path isn't user-friendly and is prone to errors. 

For prosperity here's the full code snippet of the workaround:

```
private readonly Regex resourceGroupRegex = new Regex(@"resourcegroups/([^/]+)", RegexOptions.IgnoreCase);

private bool TryExtractResourceNameFromFromFrontDoorModel(FrontDoorModel model, out string resourceGroup)
{
    Match match = this.resourceGroupRegex.Match(model.Id);

    if (match.Length > 0)
    {
        resourceGroup = match.Groups[1].Value;
        return true;
    }

    resourceGroup = string.Empty;
    return false;
}
```
