### ISSUE TITLE
[BUG] Microsoft.Web/sites/functions returns ResourceNotFound

### ISSUE THREAD

**Issue by coppercosmo** [Azure/azure-sdk-for-net#17927]
**Describe the bug**
Trying to create a new app service function using the Azure.ResourceManager library is not working.

**Expected behavior**
I expect to be able to create a new app service function by using the Microsoft.Web/sites/functions Resource Provider Namespace. This microsoft website says that it should be available. https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites/functions

Here is a code snippet of what I am trying:
`
                var functionApp = await _resourcesManagementClient.Resources.StartCreateOrUpdateAsync(
                    resourceGroup.Name,
                    "Microsoft.Web",
                    "sites",
                    "functions",
                    resource.Name,
                    resource.ApiVersion,
                    parameters
                );
`

**Actual behavior (include Exception or Stack Trace)**
{"Service request failed.\r\nStatus: 404 (Not Found)\r\n\r\nContent:\r\n{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Web/sites/functions' under resource group '<RESOURCE_GROUP>' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix\"}}\r\n\r\nHeaders:\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nx-ms-failure-cause: REDACTED\r\nx-ms-request-id: REDACTED\r\nx-ms-correlation-request-id: REDACTED\r\nx-ms-routing-request-id: REDACTED\r\nStrict-Transport-Security: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nDate: Wed, 13 Jan 2021 01:26:22 GMT\r\nContent-Type: application/json; charset=utf-8\r\nExpires: -1\r\nContent-Length: 219\r\n"}

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Try to create an app service function using the code snippet above.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.ResourceManager.Resources 1.0.0-preview.2] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [Windows 10 .NET Core 3.1]
 - IDE and version : [e.g. Visual Studio 16.8.4]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by coppercosmo** [comment]
Any update on this?

**Comment by coppercosmo** [comment]
Was there any more information on this?

**Comment by coppercosmo** [comment]
@bquantump @allenjzhang ?

**Comment by coppercosmo** [comment]
At this point I have had to resort to use the `azure-libraries-for-net` fluent libraries to create my function apps. Since this is losing support and probably becoming deprecated, I would really love some help using the `azure-sdk-for-net` management libraries (or client libraries) to achieve creating functions apps.

**Comment by SaurabhSharma-MSFT** [comment]
@coppercosmo 
Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .
