### ISSUE TITLE
[BUG] Codeless Application Insights is broken after adding Azure.Core.1.8.0 Nuget package to my solution

### ISSUE THREAD

**Issue by lwlwalker** [Azure/azure-sdk-for-net#17936]
*Describe the bug
We have a WebAPI in our team deployed a an Azure Web App. We had Application Insights configured (Codeless, using Azure UI, so no code). This was working perfectly fine.

As an improvement to the API, we moved our data from SQL Server to CosmosDB. So we need to add this package to our solution: Microsoft.Azure.Cosmos. This package adds Azure.Core.1.8.0 package as a dependency, and it depends on System.Diagnostics.DiagnosticSource.

The problem is that this package (System.Diagnostics.DiagnosticSource) is incompatible with AppInsights Codeless integration. So we don't get any data in AppInsights now.

My question is: Is this dependency needed? Is there any plan to fix this? (the dependency or AppInsights Codeless incompatibility) If not, please, think about adding this to the priority list, as this is affecting all of us in Azure using Azure technology... not an uncommon situation ;-D

This issue is documented here: https://docs.microsoft.com/en-us/azure/azure-monitor/app/azure-web-apps?tabs=net#troubleshooting
From the page: "Confirm that there are no entries for AppAlreadyInstrumented, AppContainsDiagnosticSourceAssembly, and AppContainsAspNetTelemetryCorrelationAssembly."

In this case, AppContainsDiagnosticSourceAssembly is happening.

Environment summary
SDK Version: Azure.Core.1.8.0, required by Microsoft.Azure.Cosmos 3.15.1 (last one so far)
Hosting: Azure Web App (West Europe)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by pakrym** [comment]
cc @reyang

We need the `System.Diagnostics.DiagnosticSource` reference to be able to produce diagnostic tracing events that Application Insights is exporting. Can we relax the rule for code-less instrumentation?

**Comment by reyang** [comment]
@pakrym depending on whether this is .NET Framework or .NET Core.
In .NET Core we don't have such restriction, it doesn't matter whether `System.Diagnostics.DiagnosticSource` is used by the application or not, and which version is being used.
In .NET Framework there is side-by-side issue and `AppContainsDiagnosticSourceAssembly` will be reported - the behavior has been existing since the ever beginning and there is no immediate plan to address it given the focus is more on .NET Core.

**Comment by pakrym** [comment]
Closing as by-design. Azure.Core requires System.Diagnostics.DiagnosticSource to produce events that are consumed by AppInsights, we can't drop a dependency and provide distributed tracing features at the same time.

**Comment by DaleCam** [comment]
Hi there, can you please provide a workaround for those of us still using .net 4.8?

**Comment by gunnim** [comment]
@DaleCam Use the NuGet package, it itself has a dependency on DiagnosticSource. You don't get automatic AI updates via the platform instrumentation but works well enough.

**Comment by vanillajonathan** [comment]
@gunnim Could you please elaborate? Use which package?

@reyang @pakrym as @DaleCam asked, are there any workarounds for .NET Framework 4.7 / 4.8?

**Comment by gunnim** [comment]
@vanillajonathan yes, workaround is to install the ApplicationInsights NuGet packages alongside Azure.Core, forgoing the automatic Azure instrumentation.
I configured an ApplicationInsights.config with instrumentation key to get it working correctly.

**Comment by vanillajonathan** [comment]
This might solve by adding a binding redirect to the web.config file.

```xml
<dependentAssembly>
  <assemblyIdentity name="Azure.Core" publicKeyToken="92742159E12E44C8" culture="neutral"/>
  <bindingRedirect oldVersion="0.0.0.0-1.16.0.0" newVersion="1.16.0.0"/>
</dependentAssembly>
```
