### ISSUE TITLE
[BUG] Microsoft Azure SDK for .NET is available as download in Download Center

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#17935]
I found this "Microsoft Azure SDK for .NET - 3.0" download in the download center.  We should either remove or add a message which links to the new libs.

https://www.microsoft.com/en-us/download/details.aspx?id=54917

azsdke2e
azsdke2e2

**Comment by minhkhang1795** [comment]
Hi @jongio, how do I download Microsoft Azure SDK for .NET - 3.0 ? The link is broken. Thanks

**Comment by jongio** [comment]
@alexghi - Can you have a look?

**Comment by AlexGhiondea** [comment]
@minhkhang1795 that is not a supported product. Please use NuGet to get the packages you need 🙂.
