### ISSUE TITLE
Add migration guide from WindowsAzure.ServiceBus to Azure.Messaging.ServiceBus

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#17933]
We currently have a migration guide to move from Microsoft.Azure.ServiceBus to Azure.Messaging.ServiceBus. Since there are active users of the older WindowsAzure.ServiceBus package as well, we should have a migration guide from this package as well. We  need to decide whether we want to update the current migration guide or create a new one.

Related issue for Event Hubs: #17934

**Comment by ErikMogensen** [comment]
Great idea! Preferably it should mention all known features that are part of WindowsAzure.ServiceBus but not in Azure.Messaging.ServiceBus. 

The only one I am aware of is the State property on messages, #10241 but there are probably more.
