### ISSUE TITLE
Microsoft.Azure.KeyVault.LRUCache<K, V>.Add throws System.ArgumentException

### ISSUE THREAD

**Issue by northtyphoon** [Azure/azure-sdk-for-net#1793]
When multiple threads try to add the same (k,v), the function will throw the exception.

System.ArgumentException: An item with the same key has already been added.

Looking at the implementation, after entering write lock, it should double check if the (k,v) exists before _cache.Add.

67                 _lock.EnterWriteLock(); 
68 
 
69                 // Cache before List as the cache may throw an exception 
70                 _cache.Add( key, value ); 
71                 _list.AddLast( key );

**Comment by pomortaz** [comment]
Thanks for reporting the issue. This is addressed in the pull request: https://github.com/Azure/azure-sdk-for-net/pull/1849
