### ISSUE TITLE
[QUERY] Where could I find code of Microsoft.Azure.WebJobs.Extensions.EventHubs v4.2.0? 

### ISSUE THREAD

**Issue by nanan1993** [Azure/azure-sdk-for-net#17932]
**Query/Question**
Where could I find code of Microsoft.Azure.WebJobs.Extensions.EventHubs v4.2.0? And when would the release of v5.0.0 released to the nuget?

**Comment by jsquire** [comment]
Hi @nanan1993.  `Microsoft.Azure.WebJobs.Extensions.EventHubs` v4.2.0 can be found in the [Azure/azure-functions-eventhubs-extension](https://github.com/Azure/azure-functions-eventhubs-extension) repository.   

Unfortunately, there are no committed dates for the v5 releases that I'm able to share at this time.

**Comment by nanan1993** [comment]
Thanks for your answer!  But, by the way, the versions of code sometimes confused me while working. Maybe you could do something to make it clearer : )
