### ISSUE TITLE
Why is there no sample code? 

### ISSUE THREAD

**Issue by fvalencia12** [Azure/azure-sdk-for-net#17937]
Sample code should be required for all documentation. Sample code is the best type of documentation and it is missing most of the time now a days. :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1be36c1a-bf94-fd12-7010-4ca4dc38d419
* Version Independent ID: 1d043ff3-d5fa-1e6f-cf26-223f89155e5d
* Content: [DataLakeDirectoryClient.CreateIfNotExists(PathHttpHeaders, IDictionary&lt;String,String&gt;, String, String, CancellationToken) Method (Azure.Storage.Files.DataLake) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakedirectoryclient.createifnotexists?view=azure-dotnet#Azure_Storage_Files_DataLake_DataLakeDirectoryClient_CreateIfNotExists_Azure_Storage_Files_DataLake_Models_PathHttpHeaders_System_Collections_Generic_IDictionary_System_String_System_String__System_String_System_String_System_Threading_CancellationToken_)
* Content Source: [xml/Azure.Storage.Files.DataLake/DataLakeDirectoryClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.DataLake/DataLakeDirectoryClient.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by AlexGhiondea** [comment]
@fvalencia12 thanks for reporting this -- are you looking for a specific sample for that API?

**Comment by fvalencia12** [comment]
Yes, it is good to have documentation, but using that method is confusing to me and needed a sample of how to use it. It took me a bit to find some sample online in how to use it. It would help a lot if we can find samples so we know how to use the code. Something like this:

public override bool OnStart()
        {
            ServicePointManager.DefaultConnectionLimit = 12;

            var dbConnString = CloudConfigurationManager.GetSetting("PhotoGalleryDbConnectionString");
            db = new PhotoGalleryContext(dbConnString);

            var storageAccount = CloudStorageAccount.Parse(RoleEnvironment.GetConfigurationSettingValue("StorageConnectionString"));

            Trace.TraceInformation("Creating images blob container");
            var blobClient = storageAccount.CreateCloudBlobClient();
            imagesBlobContainer = blobClient.GetContainerReference("images");
            if (imagesBlobContainer.CreateIfNotExists())
            {

                imagesBlobContainer.SetPermissions(new BlobContainerPermissions { PublicAccess = BlobContainerPublicAccessType.Blob });
            }

            Trace.TraceInformation("Creating images queue");
            CloudQueueClient queueClient = storageAccount.CreateCloudQueueClient();
            imagesQueue = queueClient.GetQueueReference("images");
            imagesQueue.CreateIfNotExists();

            Trace.TraceInformation("Storage initialized");
            return base.OnStart();
        }


Fabian Valencia
Information Technology
William Blair
The William Blair Building | 150 North Riverside Plaza, Chicago, Illinois 60606
Direct: +1-312-364-5132
fvalencia@williamblair.com<mailto:fvalencia@williamblair.com> | williamblair.com<http://www.williamblair.com/>
Facebook<https://www.facebook.com/WilliamBlairCo/> | LinkedIn<https://www.linkedin.com/company/166939> | YouTube<https://www.youtube.com/channel/UC7CPnCaTlZcLxOF7WFwY0uw> | Twitter<https://twitter.com/WilliamBlair>

**Comment by AlexGhiondea** [comment]
@fvalencia12 thanks for the detailed response.

While we don't have samples directly in the reference documentation, we do have some samples [here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Files.DataLake). Would you be interested in contributing a sample there?

**Comment by amnguye** [comment]
@fvalencia12 The code snippet you provided uses the v11 library instead of the v12 library. The v11 library is deprecated, therefore we cannot create newer samples with this library.

If you're interested in using our v12 library we have many places with documentation and simpler samples as well.

[Azure.Storage.Blobs](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs)
[Azure.Storage.Files.Shares](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Files.Shares)
[Azure.Storage.Files.DataLake](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Files.DataLake)
[Azure.Storage.Queues](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Queues)

Was their a specific example you were looking for? What API are you looking to use?

**Comment by amnguye** [comment]
Please reopen if there are any further questions.
