### ISSUE TITLE
Can't change WebSite settings while creating

### ISSUE THREAD

**Issue by andrewNestorenko** [Azure/azure-sdk-for-net#1794]
Trying to remove or change php support/version on new sites that are created. 
Using:

``` c#
CreateOrUpdateSiteWithHttpMessagesAsync(resourceGroupName,
                siteName, new Site()
                {
                    Location = location.ToString(),
                    ServerFarmId = serverFarmId,
                    SiteConfig = new SiteConfig()
                    {
                        PhpVersion = "5.6",
                        PythonVersion = "3.4",
                        Location = location.ToString()
                    }
                }).Result
```

PhpVersion isn't changed. I also tried PhpVersion = "off" - doesn't work also

Tried to catch http request. Found that http request was sent with json data:

``` json
{
  "location": "JapanWest",
  "properties": {
    "serverFarmId": "%serverfarm id here%",
    "siteConfig": {
      "location": "JapanWest",
      "properties": {
        "phpVersion": "5.6",
        "pythonVersion": "3.4"
      }
    }
  }
}
```

but PHP and Python versions has not been changed

**Comment by istvanko** [comment]
I've just removed the PHP version setting because it seems the "off" is the default one. phpVersion setting was working a half year ago anyway so something had to change recently.

**Comment by adrianhall** [comment]
Is this still an issue?  If so, can you please provide the .NET library and version you are using for this?
(Close on Oct 9 if no response)
