### ISSUE TITLE
Link update for cloud-init on Linux VM?

### ISSUE THREAD

**Issue by gdryke** [Azure/azure-sdk-for-net#17952]
Link needs updating I think!
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-automate-vm-deployment
For the "how to use cloud-init" for a linux VM.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86f86194-cf92-a56f-b47d-ac80de2ee313
* Version Independent ID: 648b3b5f-100c-2a52-2037-2113a046a441
* Content: [OSProfile.CustomData Property (Microsoft.Azure.Management.Compute.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.osprofile.customdata?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/OSProfile.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/OSProfile.xml)
* Service: **multiple**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by SaurabhSharma-MSFT** [comment]
@gdryke Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .

**Comment by navba-MSFT** [comment]
@gdryke [This](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/tutorial-automate-vm-deployment) documentation talks about 'How to use cloud-init to customize a Linux virtual machine in Azure on first boot'. Could you please be more specific on the ask? and which link needs to be fixed ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@gdryke This is a follow-up to check if you had a chance to look at my above comment. Please let us know if you need any assistance on this issue.
