### ISSUE TITLE
[QUESTION] Microsoft.Azure.Management.Media: Best practice of AzureMediaServicesClient

### ISSUE THREAD

**Issue by zsybupt** [Azure/azure-sdk-for-net#17970]
I am wondering why AzureMediaSerivcesClient is not thread-safe, I see HttpClient is used underlying, so I think it should be thread-safe of concurrent api calls to server. 
If the design is not thread-safe, so the best practice is to manage HttpClient instances for reuse ourselves and create new AzureMediaServicesClient each time ?

Thanks.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by m-nash** [comment]
That class should be threadsafe.  Can you provide a repro which demonstrates the non threadsafe behavior?

**Comment by zsybupt** [comment]
@m-nash I get this information from media service documentation:
![image](https://user-images.githubusercontent.com/3711046/107145124-92844280-697a-11eb-904b-d6b039c7309e.png)
check section Multithreading below:
https://docs.microsoft.com/en-us/azure/media-services/latest/stream-files-tutorial-with-api#:~:text=The%20Azure%20Media%20Services%20v3,new%20AzureMediaServicesClient%20object%20per%20thread.

**Comment by allenjzhang** [comment]
I got the original developer to comment on the thread safety on the underlying Rest.ClientRuntime and related libraries. He indicated those are not guaranteed to be threadsafe. Hence the message for the track 1 .NET SDK (in Microsoft.Azure.Management.XXX) are not guaranteed to be threadsafe. Please follow the prescribed approach when using the client.
