### ISSUE TITLE
[BUG]  Missing relationships in Digital Twin API relationships pagination

### ISSUE THREAD

**Issue by CarlosLanderas** [Azure/azure-sdk-for-net#17972]
**Describe the bug**

Digital Twin data plane api is not creating pages for all twin relationships. This is not a SDK bug, is a problem coming directly from the digital api service itself

**Expected behavior**

I have more relationships created than the ones that appear throught the api

**Actual behavior (include Exception or Stack Trace)**

I am only offered some of the relationships, and then the nextLink becomes null, but I can directly access to non listed relationships by name

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create more than 20 relationships with the same sourceTwin and unique relationship names
2. Use ADT Explorer or query the api with  /digitaltwins/{sourceTwinId}/relationships and paginate until the end.

In my case, I am creating 19 relationships but only 17 are accessible using pagination.

If I use:

> digitaltwins/{sourceTwinId}/relationships?api-version=2020-10-31 until the last page, I never see the latest two relationships.

If I use:

> /digitaltwins/{sourceTwinId}/relationships/{relationShipName}?api-version=2020-10-31

The non-listed relationships are displayed correctly

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by CarlosLanderas** [comment]
Just to add more information, I'm using Azure.DigitalTwins.Core 1.2.0

**Comment by azabbasi** [comment]
Hello Carlos, 
We have engaged the SDK team and will get back to you ASAP.

**Comment by CarlosLanderas** [comment]
Hello, I've been contacted by azure support that the product team has already fixed this issue and I am not having the problem anymore.

**Comment by azabbasi** [comment]
Thank you
