### ISSUE TITLE
Azure Key Vault Extensions - "CachingKeyResolver" is not thread safe

### ISSUE THREAD

**Issue by pableess** [Azure/azure-sdk-for-net#1797]
CachingKeyResolver is not ThreadSafe.

The LRU cache uses locks for get and add, the problem is that the key resolver would need to lock around both the get and add.

Right now it is possible that two threads call get on the LRUCache, and no key is returned so both threads resolve the key and try to add it the cache.

This causes a "ArgumentException" - "An element with the same key already exists in the Dictionary".  I have seen this in practice.

LRUCache needs to provide a method like, "GetOrAdd" that does both the get check and add in an atomic operation, or the CachingKeyResolver needs to implement its own locks.

**Comment by pomortaz** [comment]
Thanks for reporting the issue. This is addressed in the pull request: https://github.com/Azure/azure-sdk-for-net/pull/1849
