### ISSUE TITLE
[QUESTION] Guidance on how to best register the EventGridClient with DI in a .NET 5.0 Worker Service 

### ISSUE THREAD

**Issue by ershadnozari** [Azure/azure-sdk-for-net#17971]
I'm using the EventGridClient from the Microsoft.Azure.EventGrid NuGet package to publish events to an Azure Event Grid Topic. I understand that worker services are registered with singleton lifetime. I'm looking for guidance on how to best register the EventGridClient with the DI container in a worker service? I'm using a .NET 5.0 worker hosted in a windows services.

DI registration (not sure if I've done the right thing here):

```csharp
Host.CreateDefaultBuilder(args)
.UseWindowsService()
.ConfigureServices((hostContext, services) =>
{
    services.AddSingleton(new EventGridClient(new TopicCredentials("topicKey"), // proxy auth
        new HttpClientHandler {DefaultProxyCredentials = CredentialCache.DefaultCredentials}));
    services.AddHostedService<Worker>();

})
.Build()
.Run();
```
Worker implementation:

```csharp
public class Worker : BackgroundService
{
    private readonly EventGridClient client;
    private readonly ILogger<Worker> logger;

    public Worker(EventGridClient client, ILogger<Worker> logger)
    {
        this.client = client;
        this.logger = logger;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        while (!stoppingToken.IsCancellationRequested)
        {
            var events = new List<EventGridEvent>();

            await client.PublishEventsAsync("topicHostname", events, stoppingToken);

            logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
            await Task.Delay(1000, stoppingToken);
        }
    }
}
```
Any guidance is highly appreciated.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ershadnozari** [comment]
@jsquire Thanks for forwarding this to your team. Would appreciate a response highly as we are going to use this approach for a high scale messaging/eventing scenario.

**Comment by SaurabhSharma-MSFT** [comment]
@ershadnozari Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .

**Comment by ershadnozari** [comment]
Issue to old to recall my resolution on this,
