### ISSUE TITLE
[BUG] Azure.Storage.Blobs#CreateIfNotExistsAsync throws exception if the BLOB container already exists

### ISSUE THREAD

**Issue by feisler** [Azure/azure-sdk-for-net#18000]
**Describe the bug**
The method Azure.Storage.Blobs.CreateIfNotExistsAsync() throws an exception with:
* Status: 409 (The specified blob already exists.)
* ErrorCode: BlobAlreadyExists
However, it is suppost to do nothing if the BLOB container already exists.

**Expected behavior**
Nothing.
Therer should just be no change.

**Actual behavior (include Exception or Stack Trace)**
An Exception is thrown
```
  Exception:
    Azure.RequestFailedException: The specified blob already exists.
    RequestId:xxx
    Time:2021-01-15T14:09:55.1569279Z
    Status: 409 (The specified blob already exists.)
    ErrorCode: BlobAlreadyExists
    
    Headers:
    x-ms-request-id: xxx
    x-ms-client-request-id: xxx
    x-ms-version: 2020-04-08
    x-ms-error-code: BlobAlreadyExists
    Content-Length: 220
    Content-Type: application/xml
    Date: Fri, 15 Jan 2021 14:09:54 GMT
    Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
    
  Stack Trace: 
    BlockBlob.UploadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
    <UploadAsync>d__0.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    ValueTask`1.get_Result()
    <UploadInternal>d__27.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <<GetPartitionedUploaderBehaviors>b__0>d.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <UploadInternal>d__19.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <StagedUploadInternal>d__31.MoveNext()
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    TaskAwaiter`1.GetResult()
    <UploadFileAsync>d__5.MoveNext() line 62
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    TaskAwaiter.GetResult()
    <UploadExistingFile_NoOverwrite_Test>d__2.MoveNext() line 30
    --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
    ExceptionDispatchInfo.Throw()
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    ThreadOperations.ExecuteWithAbortSafety(Action action)

```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```
var client = new BlobContainerClient("my connection string", "any unique container name which does not yet exists");
await client.CreateIfNotExistsAsync(); // Creates the BLOB client - no Exception
await client.CreateIfNotExistsAsync(); // Throws the exception
```

**Environment:**
 - Name and version of the Library package used: **Azure.Storage.Blobs Version=12.8.0.0**
 - Hosting platform or OS and .NET runtime version: **.NET Framework 4.6.1**
 - IDE and version : **Microsoft Visual Studio Professional 2019 Version 16.8.4**

**Comment by feisler** [comment]
Sorry, pasted the wrong exception in Actual Behavior. Here is the  correct one:
```
Azure.RequestFailedException: The specified container already exists.
RequestId:b138d53d-501e-001e-654d-eb4437000000
Time:2021-01-15T14:46:18.3813227Z
Status: 409 (The specified container already exists.)
ErrorCode: ContainerAlreadyExists

Headers:
x-ms-request-id: xxx
x-ms-client-request-id: xxx
x-ms-version: 2020-04-08
x-ms-error-code: ContainerAlreadyExists
Content-Length: 230
Content-Type: application/xml
Date: Fri, 15 Jan 2021 14:46:17 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

   bei Azure.Storage.Blobs.BlobRestClient.Container.CreateAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
```

**Comment by amnguye** [comment]
Hi,

I was not able to reproduce the issue you are running into. I was able to recreate the scenario where the `ContainerAlreadyExists` is thrown by the service, but the SDK was able to catch the exception.

Is your project running in like where the exception settings are set to stop at all exceptions thrown even if they're caught (e.g. ASP NET Core project). We had a customer run into a similar [issue](
https://github.com/Azure/azure-sdk-for-net/issues/17129) a while back.

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.

**Comment by renaudrenaud85** [comment]
Same problem here. blobContainerClient.ExistsAsync() throws a RequestFailedException if it does not exist instead of just returning false, CreateIfNotExistsAsync() throws an exception if it exists. Very annoying because I don't know how to keep those exceptions away from AppInsights.

**Comment by adrian-crisan625** [comment]
I agree with [renaudrenaud85](https://github.com/renaudrenaud85). The exception is thrown when the container already exists.
By the name of the method CreateIfNotExistsAsync nothing should happen when the container exists. Instead the exception is thrown and Application Insights is filling up with these kind of useless exceptions

**Comment by amnguye** [comment]
This issue regarding the exceptions being logged to Application Insights is unrelated to the original issue. The original poster was not using Application Insights. They were simply noting an exception was still being thrown from their code (not Application Insights) and they saw it, when they expected it not to.

Please do not create unnecessary noise for the original poster of the issue.

I found the related issue you're looking for that you can take your concerns to

https://github.com/Azure/azure-sdk-for-net/issues/18592

Thanks.
