### ISSUE TITLE
Markup mistake in Remarks section

### ISSUE THREAD

**Issue by JeffEmery** [Azure/azure-sdk-for-net#18025]
The Remarks section has a mistake where part of the sentence is inside a code block.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47f3ba00-15b2-f56d-2420-dfd5dec94147
* Version Independent ID: 32340b9d-e5e0-052b-10c8-d4fc4d68f4df
* Content: [ServiceBusMessage.ScheduledEnqueueTime Property (Azure.Messaging.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.scheduledenqueuetime?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.ServiceBus/ServiceBusMessage.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus/ServiceBusMessage.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Hi @JeffEmery.  Thank you for your feedback.   We'll get this patched up.

**Comment by jsquire** [comment]
@scbedd:  I'd appreciate your thoughts here.   The MS Docs content is definitely malformed, but the [code](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs#L381) comments are valid.   The only difference that I can see from other areas is that the `<remarks>` tags are inline with a multi-line comment rather than being on a separate line.

//cc: @JoshLove-msft

**Comment by jsquire** [comment]
I think this should be fixed by #18063.     @scbedd:  Is there a way that we can regen and validate without waiting for a release?

**Comment by danieljurek** [comment]
Investigation revealed that inconsistencies in spaces between the start of doc comments is causing the DocFX to render markdown in unintended ways. We are testing a limited fix https://github.com/Azure/azure-sdk-for-net/pull/18485 

This may be happening in more places throughout the code. If it is happening in other places in the code it makes sense to consider language-specific automation that enforces correct spacing practices in doc comments.

**Comment by danieljurek** [comment]
Update -- We have had an internal tools issue opened to track fixing this: https://ceapex.visualstudio.com/Engineering/_workitems/edit/373096 

The team has triaged this and will be working on a feature which should fix the behavior. I'm following up.

**Comment by danieljurek** [comment]
Verified formatting looks good -- https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.scheduledenqueuetime?view=azure-dotnet#Azure_Messaging_ServiceBus_ServiceBusMessage_ScheduledEnqueueTime
