### ISSUE TITLE
[QUERY] Azure.Storage.Blobs and TokenCredential - Reuse of existing Access Tokens

### ISSUE THREAD

**Issue by harisubramaniam1** [Azure/azure-sdk-for-net#18028]
**Query/Question**
Currently I have a public client application. I am able to log the user in interactively through AAD tenant.
I also have a Azure blob storage configured and it is protected using AAD. To work with the Storage blob, I use **Azure.Storage.Blobs 12.8.0** and **BlobServiceClient**  I need to use the same access token and pass it to **BlobServiceClient** so that I can re use the Access token.

Currently, the only way this is possible seems to be to implement a custom implementation of `TokenCredential` and pass the access token into that and pass a object of the custom type into **BlobServiceClient**. This has the problem of managing token expiry etc.

Due to this, I am having to fall back to Azure storage V11 SDK and use Microsoft.Azure.Storage.Auth.StorageCredentials and Microsoft.Azure.Storage.Auth.TokenCredential and hook a function into that in case token needs to be renewed.

Am I missing something obvious?

**Environment:**
 - Name and version of the Library package used: **Azure.Storage.Blobs 12.8.0** and **Azure.Identity 1.3.0** and **Microsoft.Identity.Client 4.24.0**
 - Hosting platform or OS and .NET runtime version **Windows 10 and .net core 3.1**
 - IDE and version : [e.g. Visual Studio 16.9.2]

**Comment by jsquire** [comment]
//cc: @schaabs, who may have some thoughts.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi, Is there no derived class of `TokenCredential` that fits your criteria of passing the access token? The link below has all the derived options.
https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet

I think we might have trouble managing refreshing and the expirey of the key if all we have is the access token, and not the criteria to refresh the token.
@schaabs Is there an object where they can pass their access token easily into the `TokenCredential` ? Or is there a different object they can use? (If there's a different object, we might have to add a feature request to support this)

**Comment by asgoe** [comment]
I have a similar question that I posted here: https://github.com/Azure/azure-sdk-for-net/issues/18144
Will using ClientSecretCredential as the TokenCredential allow the storage SDK to be able manage the refresh and expiry of the token. https://docs.microsoft.com/en-us/dotnet/api/azure.identity.clientsecretcredential?view=azure-dotnet
From the description of the methods, it seems that the storage SDK should  be calling  the GetToken methods to manage the refresh of the token
![image](https://user-images.githubusercontent.com/58997343/105537586-fafad080-5ca6-11eb-97ad-08f31a0a11e5.png)

**Comment by amnguye** [comment]
I think this document was written in reference to the `Azure.Identity` package where this method lives. Not referencing the storage library at all. I think this sentence needs to be updated so customers don't assume every single Azure SDK Client library supports the feature of refreshing the token for the customer.

**Comment by schaabs** [comment]
@asgoe as @amnguye mentioned the Azure SDK doesn't have a `TokenCredential` implementation which allows you to just pass a previously acquired access token. There are several reasons for this, one of which is the one you mentioned that the client libraries would have no way to refresh this token so the credential would be invalid once the original access token had expired. To your other questiuon, If you are using the `ClientSecretCredential` with any of the client libraries in the Azure SDK, including the storage client library, the clients should handle the expiration and refresh of tokens. This should be true of *every* library in the SDK and if you find a case where it is not it is a bug. Most client libraries rely on an authentication policy in Azure.Core called `BearerTokenAuthenticationPolicy` to handle the token lifetime, and this is the case in the storage libraries. But even in the very uncommon case a client library is not using this they are required to handle the lifetime in our SDK.

**Comment by asgoe** [comment]
@schaabs Thanks for the quick response. Just so that I understand it correctly, when you say above "If you are using the ClientSecretCredential with any of the client libraries in the Azure SDK, including the storage client library, the **clients should handle the expiration and refresh of tokens**."

here "clients" refer to the Storage Client library that we are using. Our code which uses the Storage library DOES NOT need to handle the expiration and refresh of tokens. Is that a correct understanding?

**Comment by amnguye** [comment]
Sorry I was definitely thinking about a different type of token when I looked I saw the documentation about refreshing token.

@asgoe Is it currently refreshing for you while using the storage library? Or were you looking to manage the refreshing of the token yourself?

**Comment by amnguye** [comment]
Sorry I responded at the same time you did. So you answered my question about not refreshing. So over time are you receiving a 403 authentication error after the credential expires? Can you send the error exception that gets sent back?

**Comment by asgoe** [comment]
I am in the middle of testing this in our pre-production environment. However, its a bit difficult to test completely, since the token we receive has a 24hr validity and our application process usually gets moved around (due to load balancing) every few hours which results in a new token being acquired. In our production environment however this is not the case. Thus, I am trying to understand this before we take our code to production, where if we start seeing authentication errors it will quickly become a Sev2/Sev3 for us :(

**Comment by amnguye** [comment]
It's extremely difficult for us debug the issue with the refresh of the token without a stack trace or the exception response from the SDK. So to be clear you created a token that has an expirey of 24 hours after the token is created, but in your test environment you are actually manually acquiring a new token every few hours (so the you are unable to see when the token gets close to the expired time). Is there any way in your test environment you could change the expirey to like an hour or 2 hours that way you can run into the scenario quicker that way we can obtain a exception response?

But in the production environment you guys will not be refreshing the token that often, so your worry is that the error might happen?

**Comment by asgoe** [comment]
That is correct. I am running a test right now on a different application which hopefully will not acquire a new token every few hours. Will know the result by tomorrow morning. From the discussion, it seems that the expected behavior is that by using ClientSecretCredential, the Azure Storage Client library should be taking care of refreshing the token. Can you confirm if my understanding is correct?

**Comment by amnguye** [comment]
Yes the understanding is correct. Sorry I was under the impression that you ran into a bug where the token was not refreshing, that's why I was asking for the logs, stack trace and exception message.

**Comment by seanmcc-msft** [comment]
Please reopen if you have further questions.
