### ISSUE TITLE
[BUG] Microsoft.Rest.ClientRuntime Dependency Loop

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-sdk-for-net#18024]
**Describe the bug**
Please provide the description of issue you're seeing.

Installing the following package:
https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/

NOTE: the command is wrong, the parameter -Version should be -RequiredVersion.

After entering the command, I get a dependency loop error:

```
PS C:\Users\Administrator\Desktop\dotnet\hybrid-compute-dotnet-manage-vm> Install-Package Microsoft.Rest.ClientRuntime -RequiredVersion 2.3.22

The package(s) come(s) from a package source that is not marked as trusted.
Are you sure you want to install software from 'nuget.org'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): A
Install-Package : Dependency loop detected for package 'Microsoft.Rest.ClientRuntime'.
At line:1 char:1
+ Install-Package Microsoft.Rest.ClientRuntime -RequiredVersion 2.3.22
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : Deadlock detected: (Microsoft.Rest.ClientRuntime:String) [Install-Package], Exception
    + FullyQualifiedErrorId : DependencyLoopDetected,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

**Expected behavior**
What is the expected behavior?

Should not have an error.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

There was an error.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Install-Package Microsoft.Rest.ClientRuntime -RequiredVersion 2.3.22

**Environment:**
 - Name and version of the Library package used: Microsoft.Rest.ClientRuntime 2.3.22
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows Server 2019 Datacenter
 - IDE and version : [e.g. Visual Studio 16.3] Visual Studio Code

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by YalinLi0312** [comment]
@jsquire It looks is Microsoft.Rest.ClientRuntime, why it is a question for management package?

**Comment by jsquire** [comment]
@YalinLi0312: That's a mistake on may part.  Apologies for the confusion.

**Comment by AlexGhiondea** [comment]
@TheOnlyWei there is a newer version of the package -- are you still seeing this?

**Comment by TheOnlyWei** [comment]
@AlexGhiondea Yes, I get the same error in 2.3.23 (the latest version I found).

`Install-Package: Dependency loop detected for package 'Microsoft.Rest.ClientRuntime'.`

**Comment by pakrym** [comment]
There are two versions of `Install-Package` commands. One exists inside Package Manager Console in VisualStudio and works just fine:

![image](https://user-images.githubusercontent.com/1697911/147493728-ba8378e6-a5f9-434b-805e-abf3045e76a8.png)

The other is from PackageManagement Powershell module and is intended for general-purpose powershell packages, not .NET packages. You are ending up using this version. It's unable to handle .NET-specific package authoring. 

When using VSCOde I recommend using `dotnet package add` to install the package.


```
dotnet add package Microsoft.Rest.ClientRuntime --version 2.3.22
```
