### ISSUE TITLE
Azure service bus .NET sdk raises OperationCanceledException from time to time

### ISSUE THREAD

**Issue by EnricoMassone** [Azure/azure-sdk-for-net#18035]
Hi all,

I'm working with a .NET core **3.1** worker service application.  We are referencing the **Microsoft.Azure.ServiceBus** nuget package version **5.1.0**. The application is deployed as a pod inside a kubernetes cluster. We use Azure Kubernetes Service (AKS) to manage our cluster.

This application is meant to listen to messages published to an Azure Service Bus **topic** by another application. When the application starts up a subscription is created on the existing Azure Service Bus topic and a  `SubscriptionClient` instance is created in order to listen to incoming messages. 

Our subscription client is configured as follows:

- the receive mode is `ReceiveMode.ReceiveAndDelete`
- the retry policy is `RetryPolicy.Default`
- we register a message handler by using the `SubscriptionClient.RegisterMessageHandler` method
- we set `AutoComplete = true` in the `MessageHandlerOptions`
- we set a default value of `10` for the `MaxConcurrentCalls` property in the `MessageHandlerOptions`
- we provide an `exceptionReceivedHandler` in the constructor of class `MessageHandlerOptions` which simply logs a warning log message each time an error occurs while receiving messages.

We noticed that, from time to time, our application raises some `OperationCanceledException` while receiving messages from the Azure Service Bus topic. 

In order to better understand what's going on I followed [this documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-end-to-end-tracing#tracking-without-tracing-system) to add additional application-level logs in order to better understand the issue. 

**First of all I noticed that, before throwing the `OperationCanceledException`, the `Microsoft.Azure.ServiceBus.Receive` operation works fine every time it is performed.** This is a sample log that our application writes before the error appears (this is one of the additional logs that I added):

> Operation "Microsoft.Azure.ServiceBus.Receive" is finished, Duration=00:00:59.9991789, Status=RanToCompletion, Id="00-9cd1f0d0190fb34381fe58b8e06191ec-00ac27ca7a505a4b-00", StartTime="2021-01-17T13:39:51.4380719Z"

Suddenly the error occurs and we get the following error log (this is one of the additional logs that I added):

> Operation "Microsoft.Azure.ServiceBus.Receive" with id "00-fe45ce4ba807fb45af16386641cd86ce-2786cf7eab4ba24c-00" started at "2021-01-17T13:39:56.4920237Z" raised an error: "The operation was canceled.Reference: 790ae7c96ae64a65861fbc662626fb07_G8, 01/17/2021 13:40:54"

> Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: The operation was canceled.Reference: 790ae7c96ae64a65861fbc662626fb07_G8, 01/17/2021 13:40:54
>  ---> System.OperationCanceledException: The operation was canceled.
>    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at Microsoft.Azure.Amqp.ReceivingAmqpLink.EndReceiveMessages(IAsyncResult result, IEnumerable`1& messages)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass65_0.<<ReceiveAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.MessageReceivePump.<MessagePumpTaskAsync>b__12_0()

The **exact same error** is also logged as a warning by the `exceptionReceivedHandler` delegate that we pass to the constructor of the `MessageHandlerOptions` class for our subscription client message handler: 

> Azure Notification Bus Message handler encountered an exception 
> Exception context for troubleshooting:
>  - Endpoint: ***** REDACTED *****
>  - Entity Path: ***** REDACTED *****
>  - Executing Action: Receive

> Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: The operation was canceled.Reference: 790ae7c96ae64a65861fbc662626fb07_G8, 01/17/2021 13:40:54
>  ---> System.OperationCanceledException: The operation was canceled.
>    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at Microsoft.Azure.Amqp.ReceivingAmqpLink.EndReceiveMessages(IAsyncResult result, IEnumerable`1& messages)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass65_0.<<ReceiveAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.MessageReceivePump.<MessagePumpTaskAsync>b__12_0()

At the this point we have another log, which notifies us that this time the `Microsoft.Azure.ServiceBus.Receive` has failed (this is one of the additional logs that I added):

> Operation "Microsoft.Azure.ServiceBus.Receive" is finished, Duration=00:00:57.7255408, Status=Faulted, Id="00-fe45ce4ba807fb45af16386641cd86ce-2786cf7eab4ba24c-00", StartTime="2021-01-17T13:39:56.4920237Z"

After a couple of failed `Microsoft.Azure.ServiceBus.Receive` operations (both of them creates the exact logs sequence that I have described above) things work properly again. The following `Microsoft.Azure.ServiceBus.Receive` operations complete without errors:

> Operation "Microsoft.Azure.ServiceBus.Receive" is finished, Duration=00:01:00.1531469, Status=RanToCompletion, Id="00-487f0fa5352c6545a7938da9a13c405a-4c77146b1efa4646-00", StartTime="2021-01-17T13:39:56.5046654Z"

We have noticed that this kind of errors are **much more frequent** when we deploy our application inside of kubernetes. For some other customers the same application is deployed as a web job inside an Azure App Service: **in that case this kind of errors are much less frequent.**

Usually in the .NET world `OperationCanceledException` means a timeout due to a canceled `CancellationToken`. This seems to be contradicted by the above log messages: as you can see the duration of the faulted  `Microsoft.Azure.ServiceBus.Receive` operation (`00:00:57.7255408`) is shorter than the duration of the successful one (`00:00:59.9991789` and `00:01:00.1531469`). This seems really strange to me. 

Can you please help us to understand what is the root cause of this errors ?

Kind regards.

Enrico.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//fyi:  @JoshLove-msft

**Comment by EnricoMassone** [comment]
@jsquire many thanks. Let me know if you need any further detail to carry on the investigation.

**Comment by axisc** [comment]
@EnricoMassone 

This may be caused due to disruptions in the connection between the containers in Kubernetes and Azure Service Bus. This is expected behavior and the SDK is designed to retry to recover from this.

**Comment by EnricoMassone** [comment]
> @EnricoMassone
> 
> This may be caused due to disruptions in the connection between the containers in Kubernetes and Azure Service Bus. This is expected behavior and the SDK is designed to retry to recover from this.

Hi and thanks for helping. 

So basically we can assume that these errors are harmless, correct? 

The main point for us is being sure that no messages will be lost from the worker service. What happens if a message is published during these periods of lost connectivity? Is the application able to get the message once the connectivity is recovered? 

Is there anything that we can check or do at the AKS level in order to mitigate these connectivity errors?

**Comment by EnricoMassone** [comment]
@axisc this morning I have checked the logs again and I have found another type of errors. 

These errors come from a different pod of our kubernetes cluster. This component is a **.NET core 2.2 console application**.  Apart from the different .NET core version **everything else is the same as the aforementioned worker service application**: we reference the **same** version of the **Microsoft.Azure.ServiceBus NUGET package (5.1.0)**, we setup a `SubscriptionClient `instance where we register a message handler by calling `SubscriptionClient.RegisterMessageHandler` (all the settings for the subscription client are the **same** as described above). 

Here is the error message and stacktrace that we log for these new errors:

> Operation "Microsoft.Azure.ServiceBus.Receive" with id "00-e8a50f7c1984f24f80b3d93fc00d2a99-51b4867f88bcb247-00" started at "2021-01-19T08:51:01.9020027Z" raised an error: "The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'fe050101-102d-4ac7-bd43-3d314ca2cbdc'.Reference: 80d5dc8c897745ff82c6687b79096042_G7, 01/19/2021 08:52:07"

> Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'fe050101-102d-4ac7-bd43-3d314ca2cbdc'.Reference: 80d5dc8c897745ff82c6687b79096042_G7, 01/19/2021 08:52:07 ---> Microsoft.Azure.ServiceBus.ServiceBusException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'fe050101-102d-4ac7-bd43-3d314ca2cbdc'.
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass65_0.<<ReceiveAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.MessageReceivePump.<MessagePumpTaskAsync>b__12_0()

The exact **same** error is also logged as a warning by the `exceptionReceivedHandler` delegate that we pass to the constructor of the `MessageHandlerOptions` class for our subscription client message handler:

> Azure Notification Bus Message handler encountered an exception 
> Exception context for troubleshooting:
>  - Endpoint: *** REDACTED ***
>  - Entity Path: *** REDACTED ***
>  - Executing Action: Receive

> Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'fe050101-102d-4ac7-bd43-3d314ca2cbdc'.Reference: 80d5dc8c897745ff82c6687b79096042_G7, 01/19/2021 08:52:07 ---> Microsoft.Azure.ServiceBus.ServiceBusException: The connection was inactive for more than the allowed 60000 milliseconds and is closed by container 'fe050101-102d-4ac7-bd43-3d314ca2cbdc'.
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass65_0.<<ReceiveAsync>b__0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ReceiveAsync(TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.MessageReceivePump.<MessagePumpTaskAsync>b__12_0()

The pattern seems to be the same of the errors described in my original question. Before the exceptions pop up everything seems to work fine inside the kubernetes pod:

> Operation "Microsoft.Azure.ServiceBus.Receive" is finished, Duration=00:01:12.3908558, Status=RanToCompletion, Id="00-33b4323ad1e4ea4196298f4f8e992e7e-506b29dfa0063242-00", StartTime="2021-01-19T08:50:53.5191260Z"

After the two error logs reported above we get an information log which notifies the failure of the `Microsoft.Azure.ServiceBus.Receive` operation: 

> Operation "Microsoft.Azure.ServiceBus.Receive" is finished, Duration=00:01:06.0124836, Status=Faulted, Id="00-e8a50f7c1984f24f80b3d93fc00d2a99-51b4867f88bcb247-00", StartTime="2021-01-19T08:51:01.9020027Z"

**Again it seems that the pod is able to automatically recover the connectivity to the Azure service bus subscription**. This log is written **after** the previous one: 

> Operation "Microsoft.Azure.ServiceBus.Receive" is finished, Duration=00:01:02.5989493, Status=RanToCompletion, Id="00-1a6168d50a4f4145aa619949d31851fc-96f12be1bbd1f14c-00", StartTime="2021-01-19T08:51:10.0042316Z"

@axisc are these errors of the same nature of the ones reported in my original question ? This time the error message seems to clearly indicate a timeout / communication issue between the kubernetes cluster and the Azure service bus server.

**Comment by axisc** [comment]
The first set of errors you saw were because of connection disruption. The messages are not "lost", because the service bus will not ack it and the client side SDK will retry the operation. The client will only proceed to the next message after the current message is successfully ACKed by Service Bus.

The second set of errors you saw are due to an idle connection. In Azure Service Bus, connections are stateful and do utilize resources, so idle connections are disconnected by Service Bus. Again there is no impact to this because the client SDK has built in retry logic.

**Comment by EnricoMassone** [comment]
> The first set of errors you saw were because of connection disruption. The messages are not "lost", because the service bus will not ack it and the client side SDK will retry the operation. The client will only proceed to the next message after the current message is successfully ACKed by Service Bus.
> 
> The second set of errors you saw are due to an idle connection. In Azure Service Bus, connections are stateful and do utilize resources, so idle connections are disconnected by Service Bus. Again there is no impact to this because the client SDK has built in retry logic.

@axisc thanks for all the clarifications. 

Based on what you said the .NET sdk has been designed to gracefully handle these errors (via retry policies). So **no changes are required at the application level** and we still have the guarantee that the application will have a canche to consume **all** the messages published to the topic, regardless these transient errors. Is my understanding correct ? 

I would like to investigate what happens at the AKS level for the first set of errors (the one caused by 'connection disruption'), in order to understand whether we can do anything at the infrastructure level to mitigate this. Do you think this is worth the effort ? I mean, should we consider these *connection disruption events* as expected and related to the 'business as usual' of the Azure Service Bus or, instead, should they be considered as a symptom that something is not working well in our infrastructure ?

**Comment by axisc** [comment]
@EnricoMassone 

There is no cache, it is just that every data operation is committed to storage and log before you get an ACK. So no application changes are needed. Your business logic must wait for the ACK to make sure it went through.

You might need to pull some AKS experts for the AKS specific issues. My understanding is that if your containers move across the AKS cluster, then the stateful links between that container and Service Bus will break and the retry logic will engage to rebuild the connection. Do you know if container moves are occurring frequently (or at all)?

Is it worth the effort? It really depends - you should consider them business as usual and rely on retry policy regardless for all cloud native services, but if it is a significant hindrance and you have to process the same message multiple times because the connection broke, it may help to refine the configuration.

**Comment by axisc** [comment]
@EnricoMassone just checking in if you had any follow up questions. If not, I can proceed to close the issue.

**Comment by EnricoMassone** [comment]
@axisc I'm going to investigate what happens at the AKS level, we have an open ticket with the Azure service desk. 

Just a clarification request, above you mentioned the ack. The only ack I'm aware of, in the context of the Azure service bus messaging, is the ack done by the client when the message processing is complete, so that the Azure Service Bus can remove the message from the subscription. Are you talking about that kind of ack ? (based on my understanding, you were referring to a different idea of ack).

**Comment by axisc** [comment]
When you use receive and delete, then yes the client ACK is not needed. 

However, given the rest of the discussion, I'd recommend using the PeekLock (and complete) since that will eliminate the possibility of losing messages during such disconnects/reconnects/etc.

ACK is also sent by Service Bus to the sender when the messages are accepted.

**Comment by EnricoMassone** [comment]
> When you use receive and delete, then yes the client ACK is not needed.
> 
> However, given the rest of the discussion, I'd recommend using the PeekLock (and complete) since that will eliminate the possibility of losing messages during such disconnects/reconnects/etc.
> 
> ACK is also sent by Service Bus to the sender when the messages are accepted.

Thanks for the clarification. About the receive and delete you are right: that's not the right strategy and we should change that. Based on my understanding, if there is a network error while the message is dispatched from the service bus to the client, that message will be lost forever. So, considering our transient connectivity issues, we should prevent that with a PeekLock strategy.

**Comment by axisc** [comment]
@EnricoMassone  spot on!

Do let me know if there are follow up questions. If not, I can go ahead and close the issue.

**Comment by EnricoMassone** [comment]
> @EnricoMassone spot on!
> 
> Do let me know if there are follow up questions. If not, I can go ahead and close the issue.

@axisc thanks for all the answers. I can proceed to close this issue. In case of further troubles I'll reopen this one.

**Comment by sksk571** [comment]
We are also seeing this error from time to time. It happens in both AKS cluster and in on-prem data center connected to Azure via Express route. If this error is meant to be automatically retried by client, then why it shows up in the error log?

We use 5.1.0 version of the SDK.

```
Message: The operation was canceled.Reference: 37edd876e8554bbfa0dd202cd38097b8_G14, 04/08/2021 07:07:16

Microsoft.Azure.ServiceBus.Core.MessageReceiver+<OnReceiveAsync>d__88.MoveNext():662
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
 
Microsoft.Azure.ServiceBus.Core.MessageReceiver+<>c__DisplayClass65_0+<<ReceiveAsync>b__0>d.MoveNext():125
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
 
Microsoft.Azure.ServiceBus.RetryPolicy+<RunOperation>d__19.MoveNext():449
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
Microsoft.Azure.ServiceBus.RetryPolicy+<RunOperation>d__19.MoveNext():177
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
 
Microsoft.Azure.ServiceBus.Core.MessageReceiver+<ReceiveAsync>d__65.MoveNext():482
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
 
Microsoft.Azure.ServiceBus.Core.MessageReceiver+<ReceiveAsync>d__63.MoveNext():118
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
 
-- Application-specific call stack removed


Message: The operation was canceled.
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result):245
Microsoft.Azure.Amqp.ReceivingAmqpLink.EndReceiveMessages(IAsyncResult result, IEnumerable`1& messages):8
System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization):15
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw():12
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task):38
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task):40
 
Microsoft.Azure.ServiceBus.Core.MessageReceiver+<OnReceiveAsync>d__88.MoveNext():472
```

**Comment by EnricoMassone** [comment]
@sksk571 hi, we have solved the issue by adoting the new [Azure.Messaging.ServiceBus SDK](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus) as a replacement for **Microsoft.Azure.ServiceBus version 5.1.0**.

By adopting the [Azure.Messaging.ServiceBus package](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/) we get rid of all the errors.
