### ISSUE TITLE
[Storage] Use correct http transport in storage tests.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#18046]
Follow up on https://github.com/Azure/azure-sdk-for-net/issues/18039 .
We should be using `HttpWebRequestTransport` in storage tests on NET FX. Or potentially remove [this customization](https://github.com/Azure/azure-sdk-for-net/blob/016c7e031e2728b6c83791c6c66a188f0df65cc5/sdk/storage/Azure.Storage.Common/tests/Shared/StorageTestBase.cs#L186-L192) and use defaults (as now timeouts are handled by http pipeline).

**Comment by pakrym** [comment]
Related https://github.com/Azure/azure-sdk-for-net/issues/18047

**Comment by pakrym** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/18047 is fixed
