### ISSUE TITLE
[FEATURE REQ] Better error handling of Data Lake Storage write errors

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-sdk-for-net#18044]
**Library or service name.**

`Azure.Storage.Files.DataLake` v12.5.0
 
**Is your feature request related to a problem? Please describe.**

When writing a content using `OpenWriteAsync(false)`, if a 500 error occurs in the flush process, the optimistic concurrency control seems to fail with a 412 error returned as follows.

```
PATCH https://***.dfs.core.windows.net/111/222.csv?action=append&position=1100138 => status code 202
PATCH https://***.dfs.core.windows.net/111/222.csv?action=flush&position=1101107 => status code 500
PATCH https://***.dfs.core.windows.net/111/222.csv?action=flush&position=1101107 => status code 412
PATCH https://***.dfs.core.windows.net/111/222.csv?action=flush&position=1101107 => status code 412 => throw exception
```

If flush is returning a 500 error, but the possibility exists that the process is successful, then better error handling would be desirable.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by shibayan** [comment]
It seems to continue to occur in `Azure.Storage.Files.DataLake` v12.6.0.

If a 500 error occurs when executing flush, it will change to a 412 error on retry, and the user will not be able to determine whether the write was successful or not.

I would like to have a guideline as to whether we should retry the write or treat it as a success.

**Comment by SaurabhSharma-MSFT** [comment]
@shibayan Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .

**Comment by shibayan** [comment]
Yes, this issue is still affecting us.

The essence of the problem is that ADLS Gen 2 is returning a 500 error but the write is still successful, but with the current SDK, once you get a 412 error, you have to discard the current state and start over.

**Comment by nathan-plotts** [comment]
This issue is affecting me as well. As a workaround I'm wrapping all my write actions with Polly retry policies to automatically retry 412 errors from the SDK. I would definitely prefer if the SDK handled these errors.

**Comment by JimSuplizio** [comment]
Hi @shibayan, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
