### ISSUE TITLE
Documentation for apiVersion parameter

### ISSUE THREAD

**Issue by stmax82** [Azure/azure-sdk-for-net#18040]
Some methods require the "apiVersion" parameter. Could you please provide some more documentation on why this parameter is required and how to obtain a list of valid values?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53d032ca-ee39-5b8f-444e-4a02281fb809
* Version Independent ID: bdf8d598-5ed1-f56b-0d4b-da61e41745ae
* Content: [ResourcesOperationsExtensions.DeleteById(IResourcesOperations, String, String) Method (Microsoft.Azure.Management.ResourceManager) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.resourcesoperationsextensions.deletebyid?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.ResourceManager/ResourcesOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ResourceManager/ResourcesOperationsExtensions.xml)
* Service: **azure-resource-manager**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by bquantump** [comment]
@stmax82 what methods in particular? These may mean different things depending on the API.

**Comment by stmax82** [comment]
@bquantump see link above or screenshot below. Some methods take an "apiVersion" parameter without explaining what it is.

![image](https://user-images.githubusercontent.com/6381927/105208525-13ed6f80-5b49-11eb-95a7-5bb5a0feadfd.png)

**Comment by bquantump** [comment]
@stmax82 in this case it is going to be the API version for the resource you want to delete. For example, if the resource is a VM then you need to give it one of the valid api-version for VM. The latest is "2019-07-01" for vm for example. 

You can find api version in the docs https://docs.microsoft.com/en-us/rest/api/azure/

We can also update this docs in future releases

**Comment by stmax82** [comment]
The link https://docs.microsoft.com/en-us/rest/api/azure/ doesn't really explain what the valid values for the apiVersion parameter are?
Not sure where you found "2019-07-01" for VMs? It's not in the provided link.

As you can see, it's quite hard for users to figure out the right value that should be passed to the apiVersion parameter.

I am for example trying to delete a Workbook resource. Where do I find the correct value for the apiVersion parameter?

The docs should provide examples or references to other pages that contain lists of valid apiVersions per resource type.

**Comment by bquantump** [comment]
![image](https://user-images.githubusercontent.com/53361486/105216661-b8e75880-5b07-11eb-8e8a-76bec1bfc1f5.png)

**Comment by bquantump** [comment]
This will show the latest version that is RELEASED. You can find older version and all version here for compute as an example: 

https://github.com/Azure/azure-rest-api-specs/tree/master/specification/compute/resource-manager/Microsoft.Compute/stable

**Comment by bquantump** [comment]
Is it a Azure Monitor Workbook resource you are trying to delete?

**Comment by stmax82** [comment]
@bquantump I think so, yes.. it was an Azure Monitor Workbook that was exported as ARM template and re-imported with workbookType = tsg (Techsupport Guide). But I'm not sure if this matters.. the apiVersion parameter needs better documentation that can be used to lookup the correct value for any resource type.

**Comment by allenjzhang** [comment]
@Arm team. I think we can update the description of [API version](https://github.com/Azure/azure-rest-api-specs/blob/825cc5cfa5fc3581a7b405cb7063282e8651ea76/specification/resources/resource-manager/Microsoft.Resources/stable/2020-10-01/resources.json#L6365) to include links to [Azure Rest API reference](https://docs.microsoft.com/en-us/rest/api/azure/) for user to locate the current version.

**Comment by ArthurMa1978** [comment]
@xboxeer please help to follow this issue
