### ISSUE TITLE
Code section for this page is mangled

### ISSUE THREAD

**Issue by schil227** [Azure/azure-sdk-for-net#18077]
The code example under the "remarks" section is mangled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 618f5a97-362b-6c27-0f8d-6af860d0f8f0
* Version Independent ID: b27fae0e-33b6-b92a-b349-37eee7db35e9
* Content: [MessageReceiver Class (Microsoft.ServiceBus.Messaging) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.messagereceiver?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.ServiceBus.Messaging/MessageReceiver.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus.Messaging/MessageReceiver.xml)
* Service: **service-bus-messaging**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
@scbedd: I'd appreciate your thoughts.  It looks like the code and resulting XML is valid and this may be a problem with the Docs extraction/translation.

**Comment by ramya-rao-a** [comment]
@TianqiZhang, can you please help with @jsquire's question above?

**Comment by jsquire** [comment]
@ramya-rao-a:  I've got the new location;  I just need to carve out a day or two on my end to put things together and submit.

**Comment by jsquire** [comment]
//fyi:  @AlexGhiondea, for consideration as an MQ item.

**Comment by jsquire** [comment]
It looks as if the docs team has already patched this;  the code snippets in the `<remarks>` section for the referenced doc appears to be rendering correctly.   Though the indentation is unusual, it matches the format in the code source.     I'm going to close this out as resolved and we can revisit if we find other occurrences that still appear incorrect.
