### ISSUE TITLE
Azure Monitor Exporter API changes based on arch board review

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-net#18081]
Based on the [arch board feedback](https://github.com/Azure/azure-sdk/issues/1975) for Azure Monitor exporter, update the APIs to support the following:

- [ ] Include an option to configure the service API version when constructing the exporter instance
- [ ] Provide a convenience method on the exporter to get the `endpoint`
- [ ] Consider adding APIs for configuring `endpoint` and `instrumentationKey` separately. Continue to support `connectionString` which contains both endpoint and instrumentationKey.

**Comment by reyang** [comment]
> Based on the [arch board feedback](https://github.com/Azure/azure-sdk/issues/1975) for Azure Monitor exporter, update the APIs to support the following:
> 
> * [ ]  Include an option to configure the service API version when constructing the exporter instance
> * [ ]  Provide a convenience method on the exporter to get the `endpoint`
> * [ ]  Consider adding APIs for configuring `endpoint` and `instrumentationKey` separately. Continue to support `connectionString` which contains both endpoint and instrumentationKey.

The 1st item makes sense to me.
I have doubts on the 2nd and 3rd item, since the exporter instance could connect to more than one endpoints:
1. There are scenarios where the exporter might send live stream of telemetry to a different endpoint with a different protocol.
2. There will be redirection from the ingestion service, it is unclear why do we need to "get the endpoint" and what's the semantic (do we get the original one specified in the connection string, or the one that we got from the redirection response).

**Comment by TimothyMothra** [comment]
Thinking out loud...

1. 
sounds fair. Just last week we were discussing a new version of the service API to support redirections. 
However, I can't imagine what that API would look like. Or why a customer would want to choose versions. I assume most customers would expect this part to work without additional input.
 
2. 
I think that's very trivial to include.
However, from my experience with the testing... If users are configuring the exporter as we've documented they won't have a reference to the exporter unless they're doing the configuration very manually. If needed, I can provide some code samples for discussion.
To Reiley's point, we would need to decide if we return the configured endpoint or the redirection endpoint.
 
3.
I have mixed feelings about this.
I understand it's important from the Azure SDK perspective, but it seems silly from the perspective of our Azure Monitor business. It was the services side that pushed for the convergence around ConnectionStrings and we've been emphasizing that in all our public docs.

However, the relationship between ConnectionString and Exporters is different than that of the former Application Insights SDK.
In the AI SDK, you set the Connection String once and you're done. The AI SDK will configure 5 different service endpoints.

In the OTel Exporters, we seem to be trending towards multiple Exporters per service endpoint (TracesExporter -> AzMon Ingestion, LogExporter -> AzMon Ingestion).
This doesn't yet include support for LiveMetrics, SnapshotDebugger, or Profiler. 
Thinking long term... do we intend to have a meta-package so allow customers to set the ConnectionString once which then configures every possible endpoint on every possible Exporter?

**Comment by reyang** [comment]
We discussed offline and agreed that we'll only proceed with item 1, which is "Include an option to configure the service API version when constructing the exporter instance".

I've forwarded you an email about deprecation of instrumentation key @joshfree @srnagar

**Comment by TimothyMothra** [comment]
Today, we met online to discuss item 1: configuring the service api version.
(Hector, Jeff Fisher, Leighton Chen, Pavel Kryments, Raj, Rakshith, Srikanta, Timothy, Trask)


### Versioning
The "ServiceVersion" needs to support a scenario where the ingestion service accepts unique data schemas.
For example:
- Swagger v2001-01-01 == ingestion v2/track with data schema v2019
- Swagger v2002-02-02 == ingestion v2/track with data schema v2020
- Swagger v2003-03-03 == ingestion v3/track with data schema v2021


The swagger version is defined in the [swagger.json](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/applicationinsights/data-plane/Monitor.Exporters/preview/2020-09-15_Preview/swagger.json#L4) and uses the REST Community Convention of dates.


### Naming
The name of this field will follow language naming conventions:
- Python: `api_version`
- Java: `AzureMonitorExporterServiceVersion`
- .NET: `ServiceVersion`


### Property
This property needs to be set on the Exporter. This is an optional property that must default to the latest available version. 

For .NET this is is an enum on the ClientOptions object.


### See also
- [dotnet service version option](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-service-version-option)
- [java service versions](https://azure.github.io/azure-sdk/java_introduction.html#service-versions)
