### ISSUE TITLE
[synapse] Some tests currently can not be automated due to test infrastructure

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-for-net#18080]
A number of synapse tests originally had this attribute:

        [Ignore("This test case cannot be automated due to the inability to configure infrastructure to test against.")]

or

        [Ignore("This test case cannot pass due to backend limitations for service principals.")]

We should research this further, and determine if we can setup the required infrastructure in the arm template.

**Comment by jsquire** [comment]
@annelo-msft:  Do you know if this is this a general issue that we should track for the test infrastructure or something specific to Synapse?   Since the Synapse team owns this SDK, I'd like to close this out if it's the latter.

**Comment by annelo-msft** [comment]
I don't know - I believe this issue represented the work to do that investigation.

**Comment by jsquire** [comment]
fair enough.   I'll keep it around then.   Thanks!

**Comment by JimSuplizio** [comment]
Hi @chamons, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
