### ISSUE TITLE
WebApp:[BUG] WebSiteManagementClient->ListGeoRegionsAsync returns DefaultErrorResponseException: Operation returned an invalid status code 'NotFound'

### ISSUE THREAD

**Issue by pyliakm** [Azure/azure-sdk-for-net#18091]
**Describe the bug**
see part of code:
`using (WebSiteManagementClient wsmClient = new WebSiteManagementClient(new TokenCredentials(token)))
 {
                wsmClient.SubscriptionId = subscriptionId;
                return (await wsmClient.ListGeoRegionsAsync()).Select(p => p.Name).ToList();
 }`

**Expected behavior**
List of geoRegions

**Actual behavior (include Exception or Stack Trace)**
Microsoft.Azure.Management.WebSites.Models.DefaultErrorResponseException: Operation returned an invalid status code 'NotFound'
**Fiddler Response Body:**
{"error":{"code":"InvalidResourceType","message":"The resource type 'georegions' could not be found in the namespace 'Microsoft.Web' for api version '2020-06-01'. The supported api-versions are '2019-08-01,2018-11-01,2018-02-01,2016-03-01,2015-08-01,2015-07-01,2015-06-01,2015-05-01,2015-04-01,2015-02-01,2014-11-01,2014-06-01,2014-04-01,2014-04-01-preview'."}}

**Environment:**
 - Microsoft.Azure.Management.Websites, Version=3.1.0.0
 - Windows 19041.746  .NET Core 3.1

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by allenjzhang** [comment]
Thank you for reporting this.  The [rest API spec](https://github.com/Azure/azure-rest-api-specs/blob/44ec11c74634f1afa5bbe0d3f2678b7f819ebf8e/specification/web/resource-manager/Microsoft.Web/stable/2020-06-01/ResourceProvider.json#L291) indicated support for 2020-06-01. 

routing to WebSite team.

**Comment by panchagnula** [comment]
Checking with Navy this might be an arm manifest update miss ; we are looking at it. This is now impacting all SDKs not just .NET

**Comment by n9839950** [comment]
Is this issue fixed? I am experiencing the same issue with python SDK
