### ISSUE TITLE
Access event data from a client application

### ISSUE THREAD

**Issue by gksarma96** [Azure/azure-sdk-for-net#18105]
Query - 
I have a class library which uses PartitionReceiver to receive data from Azure event hub. The event hub data is received and stored in a custom List/Dictionary defined in the class library. As soon as any new event data is received, it is stored in the List/Dictionary. 
The question is how to extract this data to a client application which uses this class library as a reference(dll or nuget)? As soon any new data is received, it is stored in the List defined in the class library. How will the client application know that this List/Dictionary is updated in the class Library. 

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.EventHubs v4.3.1 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):  Windows 10 .NET Framework 4.6.1, .NET Standard Library 2.0
 - IDE and version : Visual Studio 15.9.28

**Comment by jsquire** [comment]
Hi @gksarma96.   Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, I'm not quite sure what you're asking.   If I understand correctly, you are reading events from the `PartitionReceiver` into your application and holding them in a list.  From there, I'm not clear on what you're describing.   Can you help me understand what you're attempting to do?
