### ISSUE TITLE
Possible Issue?  Checked-in Certificate Thumbprint

### ISSUE THREAD

**Issue by Mike-EEE** [Azure/azure-sdk-for-net#1810]
I have noticed that there appears to be a thumbprint checked in for a certificate [here](https://github.com/Azure/azure-sdk-for-net/blob/master/src/KeyVault/Microsoft.Azure.KeyVault.Samples/samples/SampleAzureWebService/SampleKeyVaultClientService/ServiceConfiguration.Cloud.cscfg#L22) and [here](https://github.com/Azure/azure-sdk-for-net/blob/master/src/KeyVault/Microsoft.Azure.KeyVault.Samples/samples/SampleAzureWebService/SampleKeyVaultClientService/ServiceConfiguration.Local.cscfg#L22), and wanted to verify if that is intended.  It is my understanding that the samples require users to create their own certificate(s) and then place the thumbprint(s) in configuration.

If this is intended, it would be nice to know why, as it seems out of place. :)  Thank you for any assistance!

**Comment by pomortaz** [comment]
Thanks Michael! 
I have addressed the issue in this pull request: https://github.com/Azure/azure-sdk-for-net/pull/1824

**Comment by Michael-DST** [comment]
Coooooool... I guess I could have done that, too. :angel: Thank you @pomortaz !
