### ISSUE TITLE
[BUG] Blob Storage: User delegation SAS is not authorized

### ISSUE THREAD

**Issue by mattcowen** [Azure/azure-sdk-for-net#18108]
**Describe the bug**
When attempting to list blobs using User Delegation SAS with the identity of a Service Principal, i can't list blobs in a container due to a 403 and AuthenticationErrorDetail "The specified signed resource is not allowed for the this resource level".

**Expected behavior**
That the following would work

        
        Response<UserDelegationKey> userDelegationKey = await oauthService.GetUserDelegationKeyAsync(
                startsOn: DateTime.UtcNow.AddHours(-1),
                expiresOn: DateTime.UtcNow.AddHours(1)); // succeeds

        var installers = GetServiceClient_BlobServiceIdentitySas_Container(container, userDelegationKey)
                .GetBlobContainersAsync().AsPages(default, 20); // this fails when enumerated

**Actual behavior (include Exception or Stack Trace)**

```
HTTP/1.1 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Content-Length: 447
Content-Type: application/xml
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: ba9eafd5-201e-005a-73eb-ef3544000000
x-ms-error-code: AuthenticationFailed
Date: Thu, 21 Jan 2021 11:52:29 GMT

<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:ba9eafd5-201e-005a-73eb-ef3544000000
Time:2021-01-21T11:52:30.2336387Z</Message><AuthenticationErrorDetail>The specified signed resource is not allowed for the this resource level</AuthenticationErrorDetail></Error>

```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Configure Contributor rights for a Service Principal on a storage account
2. run code like below taken from the unit tests and amended slightly

```

        public BlobServiceClient GetServiceClient_BlobServiceIdentitySas_Container(
            string containerName,
            UserDelegationKey userDelegationKey,
            BlobSasQueryParameters sasCredentials = default)
            => new BlobServiceClient(
                    new Uri($"https://{storageAccountName}.blob.core.windows.net?{ GetNewBlobServiceIdentitySasCredentialsContainer(containerName: containerName, userDelegationKey, storageAccountName)}"),
                    GetOptions());


        public BlobSasQueryParameters GetNewBlobServiceIdentitySasCredentialsContainer(string containerName, UserDelegationKey userDelegationKey, string accountName)
        {
            var builder = GetBlobSasBuilder(containerName);
            builder.SetPermissions(BlobContainerSasPermissions.All);
            return builder.ToSasQueryParameters(userDelegationKey, accountName);
        }


        private BlobSasBuilder GetBlobSasBuilder(
            string containerName,
            string blobName = default,
            string snapshot = default,
            string blobVersion = default,
            string sasVersion = default)
            => new BlobSasBuilder
            {
                BlobContainerName = containerName,
                BlobName = blobName,
                //Snapshot = snapshot,
                //BlobVersionId = blobVersion,
                Protocol = SasProtocol.Https,
                StartsOn = DateTime.UtcNow.AddHours(-1),
                ExpiresOn = DateTime.UtcNow.AddHours(+1),
                //IPRange = new SasIPRange(IPAddress.None, IPAddress.None),
                Version = ToSasVersion(BlobClientOptions.ServiceVersion.V2020_04_08)
            };

....

            this.oauthService = new BlobServiceClient(
                    new Uri($"https://{storageAccountName}.blob.core.windows.net"),
                    GetOAuthCredential(this.configuration["storage:AZURE_TENANT_ID"], this.configuration["storage:AZURE_CLIENT_ID"], this.configuration["storage:AZURE_CLIENT_SECRET"]),
                    GetOptions());


            Response<UserDelegationKey> userDelegationKey = await oauthService.GetUserDelegationKeyAsync(
                startsOn: DateTime.UtcNow.AddHours(-1),
                expiresOn: DateTime.UtcNow.AddHours(1));

            var installers = GetServiceClient_BlobServiceIdentitySas_Container(container, userDelegationKey)
                .GetBlobContainersAsync().AsPages(default, 20);
```

**Environment:**
 - Azure.Storage.Blobs 12.8.0 
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 - IDE and version :Visual Studio 16..8.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hello,

User Delegation SAS cannot grant access to certain operations:
- Containers cannot be created, deleted, or **listed**.
- Container metadata and properties cannot be read or written.
- Containers cannot be leased.

As for your case you are attempting to make a User Delegation Container SAS to list blobs, but that does not grant access to that operation.

https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas#specify-permissions

In order to construct a SAS that grants access to these operations please use an [account SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas) or [service SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas#specifying-the-signed-resource-blob-service-only)

**Comment by mattcowen** [comment]
@amnguye thank you for clearing up my confusion
