### ISSUE TITLE
Resetting position of RetriableStream not working

### ISSUE THREAD

**Issue by abhaldar** [Azure/azure-sdk-for-net#18115]
Throwing out error
System.NotSupportedException: Specified method is not supported. at Azure.Core.Pipeline.RetriableStream.RetriableStreamImpl.set_Position(Int64 value)
While trying to discardBuffer and reset stream position back to 0.

How can we achieve the same here without creating a copy in memory stream?

Code snippet:

```csharp
using (var reader = new StreamReader(stream))
.....
......
try { .... }
catch (JsonSerializationException serializationException)
{
      reader.DiscardBufferedData();
      reader.BaseStream.Position = 0;
}
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
What method do you use to get the stream?

**Comment by pakrym** [comment]
Closing, please reopen if you still have the issue.
