### ISSUE TITLE
[BUG] AuthorizationManagementClient.ProviderOperationsMetadata returns non-English results for "Microsoft.Aad"

### ISSUE THREAD

**Issue by michfa** [Azure/azure-sdk-for-net#18118]
**Describe the bug**
I'm using Microsoft.Azure.Management.Authorization and AuthorizationManagementClient to retrieve ProviderOperationsMetadata for all available providers. For each ProviderOperationsMetadata I'm iterating over the Operations list in order to read the each operation property (e.g: description). The values should be in English, but I'm getting some values in Chinese or in Russian (for different runs).

**Expected behavior**
I would expect the different operations properties to be in English (I've verified that the client AcceptLanguage is "en-US")

**Actual behavior**
Specifically for "Microsoft.Aad" provider, and without modifying anything in the environment and the delegated user used for the access token retrieval, the results return in Chinese/Russian and only occasionally in English (couldn't detect a specific pattern of behavior so far).
This happens in the Azure Portal powershell as well using the "Get-AzProviderOperation Microsoft.Aad/*" command.
I would expect all the result values to be in English, for every run.

**To Reproduce**
1. Create a AuthorizationManagementClient client
2. Call client.ProviderOperationsMetadata.GetAsync("Microsoft.Aad")
3. Iterate over metadata.Operations and see that some operation's Description/DisplayName aren't in English

Operations names whose matching Description wasn't in English:
- "Microsoft.AAD/unregister/action"
- "Microsoft.AAD/register/action"

**Environment:**
Library package used: Microsoft.Azure.Management.Authorization package, version 2.12.0-preview
OS and .NET runtime version: Windows 10, .NET Framework 5.0.1
IDE and version: Visual Studio 16.8.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by michfa** [comment]
Didn't receive the results in non-English for a while now, closing, thanks.
