### ISSUE TITLE
Azure ServiceBus: Unregister and re-register a MessageHandlers results in System.ObjectDisposedException 

### ISSUE THREAD

**Issue by RicoBakels** [Azure/azure-sdk-for-net#18139]
With the Azure ServiceBus I want to create a pause functionality to stop processing messages from a subscription for a while. To accomplish this pause mechanism, I want to unregister a MessageHandler from the ISubscriptionClient so that messages won't be processed from the subscripiton, and re-register the MessageHandler later in time. 

When I do that, the problem is that the runningTaskCancellationTokenSource in the MessageReceiver.cs class is disposed so I can't register a new MessageHandler. I do not know if this is by design, but the runningTaskCancellationTokenSource  in the MessageReceiver.cs get re instantiated, but the runningTaskCancellationTokenSource does not. Why is that?

What is the appropriate way to pause my SubscriptionClient from receiving messages? I want the messages to be preserved in the queue.

It was this PR where the UnregisterMessageHandlerAsync method was added: https://github.com/Azure/azure-sdk-for-net/pull/14021

Microsoft.Azure.ServiceBus 4.1.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by DorothySun216** [comment]
@RicoBakels The new nuget 5.1.2 is out with the fix: https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/
Please check out the new lib to see if your error goes away.
