### ISSUE TITLE
[BUG] WebSiteManagementClient ListHybridConnectionsAsync returns a single object instead of a list of objects

### ISSUE THREAD

**Issue by nboettcher** [Azure/azure-sdk-for-net#18148]
**Describe the bug**
WebSiteManagementClient ListHybridConnectionsAsync returns a single object instead of a list of objects

**Expected behavior**
Return a List<HybridConnection> that are associated to the web app.

**Actual behavior (include Exception or Stack Trace)**
Return a single HybridConnection object.

**To Reproduce**

```csharp
public IEnumerable<HybridConnection> ListHybridConnectionsForWebApp(string subscriptionId, string resourceGroup, string appName)
{
    using (var client = new WebSiteManagementClient( _tokenCredentials))
    {
        client.SubscriptionId = subscriptionId;
        var hybridConnections = client.WebApps.ListHybridConnectionsAsync(resourceGroup, appName).ConfigureAwait(false).GetAwaiter().GetResult();
        return hybridConnections;
    }
}
```

**Environment:**
Microsoft.Azure.Management.Websites package Version="3.1.0"

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by YalinLi0312** [comment]
@nboettcher Are you expecting an IEnumerable list contains more than one object for your given resource group and app name?

**Comment by nboettcher** [comment]
yes

**Comment by YalinLi0312** [comment]
@nboettcher If you have Azure CLI installed, can you try [this command](https://docs.microsoft.com/en-us/cli/azure/webapp/hybrid-connection?view=azure-cli-latest#az_webapp_hybrid_connection_list) with the resource group and app name?  Do you see all HybridConnections returned for that resource group and app name?

**Comment by nboettcher** [comment]
@YalinLi0312  yes I do

**Comment by allenjzhang** [comment]
Thank you for reporting this! There seems discrepancy between the published rest API spec vs. the service behavior. We are engaging WebApp team on this bug. Will update once have a resolution.

**Comment by ArthurMa1978** [comment]
The new [AppService](https://www.nuget.org/packages/Azure.ResourceManager.AppService/) lib support this now.
