### ISSUE TITLE
[QUERY] Azure.Identity:  Using ClientSecretCredential with Azure Storage SDK v12

### ISSUE THREAD

**Issue by asgoe** [Azure/azure-sdk-for-net#18144]
**Query/Question**
We are migrating from V11 to V12 of Azure Storage SDK. We are using the .NET SDK. In V11 we could provide a callback to TokenCredential which allowed clients to refresh their token. We were using this to refresh our AAD token in advance of the token expiry. This callback functionality allowed us to cache our client. I don't see anything like that in V12. The reference document only points to the Azure Identity library. Can someone provide a sample design/code for the best way that users are supposed to replace such a code (the callback functionality)? Feel free to reach out to me over Teams/email if any clarification is required.

Edit: Will using ClientSecretCredential as the TokenCredential allow the storage SDK to be able manage the refresh and expiry of the token. https://docs.microsoft.com/en-us/dotnet/api/azure.identity.clientsecretcredential?view=azure-dotnet
From the description of the methods, it seems that the storage SDK should  be calling  the GetToken methods to manage the refresh of the token
![image](https://user-images.githubusercontent.com/58997343/105537677-2087da00-5ca7-11eb-91d7-58658171bc56.png)

**Environment:**
 - Name and version of the Library package used:  Azure.Storage.Blobs 12.7.0, Azure Identity 1.3.0, Azure Core 1.6.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):  Windows 10 .NET Framework 4.7
 - IDE and version : Visual Studio 16.5.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jongio** [comment]
@schaabs - This might be a good scenario to include in a migration guide or this doc: https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration

**Comment by christothes** [comment]
Hi @asgoe - Do you have a specific requirement to manage the token refresh or just curious how it is managed in the new client? If the latter, this should be getting handled automatically by the [authorization policy](https://github.com/Azure/azure-sdk-for-net/blob/c2ecc7170691d1a5ea51c025ac697e99aeb2844a/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs) used by the storage clients. This is done either in response to an expired token resulting in a 401 response, or preemptively in a background task.
