### ISSUE TITLE
System.InvalidOperationException: 'Local transactions cannot span multiple entities or partitions.

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-sdk-for-net#18160]
I'm trying to use the "send via" feature to be able to send messages to more than one entity inside a transaction.

I have the following entities:

- Topic: `mytesttopic`, which has one subscription: `input_subscription`
- Topic: `output_1`
- Topic: `output_2`
- Queue: `transferqueue`

I'm trying to receive sessions from `input_subscription` and for each received message:
1. Send a new message to `output_1` (via `transferqueue`)
2. Send another message to `output_2` (via `transferqueue`)
3. Complete the received message

All within one transaction, meaning, if the transaction doesn't complete, then the received message should be restored in the `input_subscription` and no messages should have been send.

Visually: 
```
                                                 ┌⟶ output_1
input_subscription ⟶ Handler ⟶ transferqueue ─┤
                                                 └⟶ output_2
```

This is the code:

```cs
var incomingSubscriptionClient = new SubscriptionClient(connection, "mytesttopic", "input_subscription", ReceiveMode.PeekLock, new NoRetry());
var output1sender = new MessageSender(connection, "output_1", "transferqueue");
var output2sender = new MessageSender(connection, "output_2", "transferqueue");

incomingSubscriptionClient.RegisterSessionHandler(async (receivedMessage, message, cancellation) =>
{
	using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
	{
		await output1sender .SendAsync(new Message
		{
			Body = Encoding.UTF8.GetBytes("something"),
			SessionId = "mySessionId"
		});

		await output2sender .SendAsync(new Message
		{
			Body = Encoding.UTF8.GetBytes("something else"),
			SessionId = "mySessionId"
		});

		await session.CompleteAsync(receivedMessage.SystemProperties.LockToken);

		transaction.Complete();
	}
}, new SessionHandlerOptions(exception =>
{
	Console.WriteLine("session Receiver exception: " + exception.Exception.Message);
	return Task.CompletedTask;
}));
```

But I'm getting this exception when completing the received message:
> System.InvalidOperationException: 'Local transactions cannot span multiple entities or partitions.'

I'm not sure if this is a bug or if I'm doing something wrong.

**Comment by johnknoop** [comment]
The error doesn't seem related to the fact that I'm sending two messages. If I remove the sending to output2, I still get the same exception.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by danielmarbach** [comment]
My memory might be bad but I seem to remember it only works against a single entity from the receive perspective and only queues or topics

> From a consumer perspective, Service Bus supports grouping of certain operations against a single entity in the scope of a transaction. You can, for instance, send several messages to one Queue from within a transaction scope, and the messages will only be committed to the Queue's log when the transaction successfully completes.

https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/AtomicTransactions#how-does-service-bus-support-transactions

**Comment by johnknoop** [comment]
@danielmarbach 

It's true that you can only send messages to a single destination entity within the scope of a transaction. And as I've understood it, that's why the "send via" feature exists. So if you look at my example, I'm sending both messages to `transferqueue` to then be redirected to their respective destination topics.

**Comment by danielmarbach** [comment]
@johnknoop yeah I saw that. My point was I think the transfer queue needs to be the receiving entity. In your case, you receive from a subscription which is a "virtual queue" and I'm not certain if that supports what you want to achieve. But like I said I don't know for sure.

**Comment by johnknoop** [comment]
@danielmarbach I just tried replacing `input_subscription` with a queue instead, but the same exception occurs.

**Comment by danielmarbach** [comment]
You ar using the previous generation SDK right? I might be able to send a sample a bit later today

**Comment by johnknoop** [comment]
No I'm using the nuget package Microsoft.Azure.ServiceBus version 5.1.1.

**Comment by danielmarbach** [comment]
Work fine on my end

https://github.com/danielmarbach/AzureServiceBus.DeepDive/pull/2/files


```
            // connection has to be shared
            receiver = new MessageReceiver(connection, inputQueue);
            sender = new MessageSender(connection, destinationQueue, inputQueue);
            var anotherSender = new MessageSender(connection, anotherDestinationQueue, inputQueue);
            receiver.RegisterMessageHandler(
                async (message, token) =>
                {
                    using (var scope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
                    {
                        Console.WriteLine(
                            $"Received message with '{message.MessageId}' and content '{Encoding.UTF8.GetString(message.Body)}'");

                        await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Will not leak")));
                        await sender.SendAsync(new Message(Encoding.UTF8.GetBytes("Will not leak")));

                        await anotherSender.SendAsync(new Message(Encoding.UTF8.GetBytes("Will not leak")));
                        await anotherSender.SendAsync(new Message(Encoding.UTF8.GetBytes("Will not leak")));

                        if (!message.UserProperties.ContainsKey("Win")) throw new InvalidOperationException();

                        scope.Complete();
                    }

                    await Prepare.ReportNumberOfMessages(connectionString, destinationQueue);
                    await Prepare.ReportNumberOfMessages(connectionString, anotherDestinationQueue);
                },
                Prepare.Options(connectionString, destinationQueue, anotherDestinationQueue)
            );
            Console.ReadLine();
```

**Comment by johnknoop** [comment]
@danielmarbach Oh, you're using the INPUT queue as "sendvia". Is that the way to do it? Isn't there a chance that the message will get read again by the same process?

When I try using the input queue as transfer queue, I get past the last exception, but now I get this instead every time:
> The session lock has expired on the MessageSession. Accept a new MessageSession.

Not sure why, since I've set the lock duration to 2 minutes and the processing of the message only takes a few seconds.

**Comment by axisc** [comment]
Thanks @danielmarbach for really answering this query!

@johnknoop  the way to think about this feature is that the first entity you interact with, in your original case - the subscription, is what is scoped to the transaction.

So, since we can't send messages to a subscription, you faced the error.

Regarding your query - the message won't be read by the same process because it is immediately forwarded to the actual destination (i.e. before it is committed to the log of the transfer queue).

The session related error message is independent of the transactions feature.

**Comment by johnknoop** [comment]
@axisc Got it. Any idea if subscriptions will be supported in the future as well? Or is there a workaround to make this work with subscriptions?

**Comment by axisc** [comment]
@johnknoop the model is a bit clunky because it works with Topics and Queues.

Can you try with making the Topic as the transfer entity. I'm guessing that works for your case and I'll need to change the doc then.

**Comment by johnknoop** [comment]
@axisc Yes, that seems to work!! That's awesome.

Thanks

**Comment by johnknoop** [comment]
Is there any downside to using the SendVia feature? The reason I'm asking is that my codebase could be made a lot simpler if I use SendVia all the time, instead of only the few places where I need to send more than one message within a transaction. Is there some penalty associated with SendVia?

**Comment by axisc** [comment]
there is some overhead because the service requires compute to accept messages on the transfer entity and then forward it to the actual destination. I'd recommend using it only when there is a need for cross entity transactions.
