### ISSUE TITLE
[QUERY] Time Series Management Api

### ISSUE THREAD

**Issue by cvellan** [Azure/azure-sdk-for-net#18161]
**Query/Question**
Hi, just wondering if there are any plans to create a Management Api for Time Series anytime soon, or if I have missed any issues or development towards that end.

**Environment:**
 - Library - N/A
 - Runtime version - .Net Core 3
 - Visual studio 16.8.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by cvellan** [comment]
Hi, just bumping this issue for an update. Thanks in advance!

**Comment by ArthurMa1978** [comment]
@cvellan we will check with service team if it's ready for a Sdk for .Net

**Comment by ArthurMa1978** [comment]
@cvellan Just to provide you an update, the TSI service is being deprecated and it is recommended that you move to the ADX. You can find more information about this migration [here] (https://learn.microsoft.com/en-us/azure/time-series-insights/migration-to-adx).
We apologize for not offering an SDK for TSI.
