### ISSUE TITLE
[Synapse] Test Coverage Improvements

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-for-net#18166]
This is a tracking issue to cover the test improvements in Synapse. 

The goal is to provide basic coverage for each exposed client, and one test for each API. 

Admittingly, this is primarily "happy path" coverage, but given the limited previous coverage, it's a good start.

It also let's us flush out some basic service issues.

## Punch List

- [x] Refactor shared code and build infrastructure
   - https://github.com/Azure/azure-sdk-for-net/pull/18010
- [x] Stub out test files for each client
   - https://github.com/Azure/azure-sdk-for-net/pull/18010
- [x] AccessControl
- [x] Artifacts
   - https://github.com/Azure/azure-sdk-for-net/pull/18010
   - https://github.com/Azure/azure-sdk-for-net/pull/18114
- [ ] ManagedPrivateEndpoints
- [x] Monitoring
    - Existing tests provided solid coverage
- [x] Spark
- [ ] Walk through broken [Ignore]'ed tests and make sure service team has issues
   - Marked up in code with https://github.com/Azure/azure-sdk-for-net/issues/18079
- [ ] Walk thorough [Ignore]'ed tests due to automation and research if we can extend test template to include needed resources

**Comment by jsquire** [comment]
Given the age of this issue, closing this as stale.  If tests are still failing, please file a new issue.
