### ISSUE TITLE
Null collections serialize as literal null when indexing documents, causing service to fail

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#18169]
From https://stackoverflow.com/questions/65823922/, in track 2 when we serialize documents during upload, null (e.g. uninitialized) collections serialize an explicit `null`, which causes the service to respond with:

```text
A node of type 'PrimitiveValue' was read from the JSON reader when trying to read the contents of the property. However, a 'StartArray' node was expected json.
```

Consider simple models:

```c#
public class Parent
{
    [SimpleField(IsKey = true)]
    public string Id { get; set; }

    public string Name { get; set; }

    public Child[] Children { get; set; }
}

public class Child
{
    public string Id { get; set; }

    public string Name { get; set; }
}
```

With our test infrastructure, the following would fail:

```c#
await using SearchResources search = await SearchResources.CreateWithEmptyIndexAsync<Parent>(this);

var documents = new Parent[]
{
    new Parent
    {
        Id = "a",
        Name = "Parent A",
        Children = new Child[]
        {
            new Child
            {
                Id = "b",
                Name = "Child B",
            }
        },
    },

    new Parent
    {
        Id = "c",
        Name = "Parent C",
    },
};

var searchClient = search.GetSearchClient();
var result = await searchClient.UploadDocumentsAsync(documents);

Assert.AreEqual(2, result.Value.Results.Count);
```

Because the JSON is serialized as:

```json
"value": [
    {
    "@search.action": "upload",
    "Id": "a",
    "Name": "Parent A",
    "Children": [
        {
        "Id": "b",
        "Name": "Child B"
        }
    ]
    },
    {
    "@search.action": "upload",
    "Id": "c",
    "Name": "Parent C",
    "Children":  null
    }
]
```

A workaround that is similar to what we do in track 1 is to, on serialization, set `JsonSerializerSettings.NullValueHandling` to `NullValueHandling.Ignore`:

```c#
await using SearchResources search = await SearchResources.CreateWithEmptyIndexAsync<Parent>(this);

var documents = new Parent[]
{
    new Parent
    {
        Id = "a",
        Name = "Parent A",
        Children = new Child[]
        {
            new Child
            {
                Id = "b",
                Name = "Child B",
            }
        },
    },

    new Parent
    {
        Id = "c",
        Name = "Parent C",
    },
};

var settings = new JsonSerializerSettings
{
    NullValueHandling = NullValueHandling.Ignore,
};

var options = new SearchClientOptions
{
    Serializer = new NewtonsoftJsonObjectSerializer(settings),
};

var searchClient = search.GetSearchClient(options);
var result = await searchClient.UploadDocumentsAsync(documents);

Assert.AreEqual(2, result.Value.Results.Count);
```

However, this is merely a workaround. We should find a way to retain track 1 behavior by default whether using `System.Text.Json` or `Newtonsoft.Json`.

To note, `NullValueHandling.Ignore` [was only used during serialization](https://github.com/Azure/azure-sdk-for-net/blob/a70eb1aca352a3757bcf61b69a22469be93bde40/sdk/search/Microsoft.Azure.Search.Data/src/Customizations/Serialization/JsonUtility.cs#L47). `NullValueHandling.Include' [was used during deserialization](https://github.com/Azure/azure-sdk-for-net/blob/a70eb1aca352a3757bcf61b69a22469be93bde40/sdk/search/Microsoft.Azure.Search.Data/src/Customizations/Serialization/JsonUtility.cs#L73) to raise errors instead of corrupt data. This should result in assigning `null` back to the property as it would've started uninitialized anyway.

**Comment by AlexGhiondea** [comment]
@Mohit-Chakraborty could you take a look?
