### ISSUE TITLE
[FEATURE REQ] Improve track 2 packages visibility at the package manager

### ISSUE THREAD

**Issue by elraikhm** [Azure/azure-sdk-for-net#18171]
**Library or service name.**
This request is for the Key Vault and Search legacy libraries 
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

Customers requested on multiple occasions to clearly distinguish track1 vs track2 libraries at Readme documentation and at the package manager. They also asked to surface migration guides at the Readmes and at the package managers, as those are not easily discoverable otherwise

Please use instructions under  https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/377/Updates-to-improve-track2-release-visibility to update packages README/Package Manager intro for each old and legacy package

You can find legacy and new package details under  https://microsoft-my.sharepoint.com/:x:/p/elraikhm/EV1zDgE84hJHs1Sx0ZFn5y4BlvODJSzAeM9EK6UdKh7yhw?e=Xb1Avz 

- [x] https://www.nuget.org/packages/Microsoft.Azure.KeyVault/
- [x] https://www.nuget.org/packages/Microsoft.Azure.Search/ 
- [x] https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault
- [x] https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault-webkey
- [x] https://mvnrepository.com/artifact/com.microsoft.azure/azure-keyvault-cryptography
- [x] https://www.npmjs.com/package/@azure/search

Thank you!

**Comment by heaths** [comment]
Each of the older packages has been deprecated (though, only in description for Maven) with a link to the new one.
