### ISSUE TITLE
Attestation Readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-net#18183]
1.
Section [link](https://github.com/benbp/azure-sdk-for-net/tree/benbp/new-sov-rebase/sdk/attestation/Azure.Security.Attestation#create-the-thing):
![image](https://user-images.githubusercontent.com/57166602/105810726-71b90600-5fe6-11eb-8fd1-b274a99316a0.png)

Reason：No `create_thing` method .

Suggestion:  Delete the whole part about `Create the thing`.

2.
Section [link](https://github.com/benbp/azure-sdk-for-net/tree/benbp/new-sov-rebase/sdk/attestation/Azure.Security.Attestation#examples):
![image](https://user-images.githubusercontent.com/57166602/105810860-a5942b80-5fe6-11eb-8f8a-dc55720251a4.png)

Suggestion: 
We should keep the items listed in sample summary  match to the headlines.
Update `Get the thing` to `Get an attestation policy for a specified attestation type`.
Update `List the things` to `Set an attestation policy for a specified attestation type`.

3.
Section [link](https://github.com/benbp/azure-sdk-for-net/tree/benbp/new-sov-rebase/sdk/attestation/Azure.Security.Attestation#set-an-attestation-policy-for-a-specified-attestation-type):
![image](https://user-images.githubusercontent.com/57166602/105811033-f3109880-5fe6-11eb-9387-b26d5f2c6aa4.png)

Reason：No `list_things`  method.
Suggestion: Delete the code  `things = client.list_things()`

@jongio for notification.

**Comment by LarryOsterman** [comment]
Funny you should mention that - I just went through building a decent one for Java, let me see what I can do about transferring it.

**Comment by LarryOsterman** [comment]
Removed the label - I've been working on other issues, getting back to this one soonish.
