### ISSUE TITLE
Azure.Identity migration guide does not demonstrate correct approach to specify the scope

### ISSUE THREAD

**Issue by dimsedane** [Azure/azure-sdk-for-net#18186]
The last example on this page is just what I need, but the library has no such overload:

```c#
var tokenCredential = new DefaultAzureCredential();
var accessToken = await tokenCredential.GetTokenAsync(ResourceId);
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f95d1f9-f552-ab33-2cbb-f5bc09f6cf5f
* Version Independent ID: 76c243d5-0e9f-cb8d-8919-a06e75ad2cf5
* Content: [App Authentication to Azure Identity Migration Guidance - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration)
* Content Source: [api/overview/azure/app-auth-migration.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/app-auth-migration.md)
* Product: **azure**
* GitHub Login: @jlichwa
* Microsoft Alias: **jalichwa**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jongio** [comment]
@schaabs - This sample code passes ResourceId to GetTokenAsync - I don't know if old lib supported that, but new one def does not.

@dimsedane - You can get a token for a scope like this:

```
var cred = new DefaultAzureCredential();
var token = cred.GetTokenAsync(
    new TokenRequestContext(scopes: new string[] { "your scope here" }) { }
);
```

**Comment by jlichwa** [comment]
FYI @nonik0
