### ISSUE TITLE
MixedReality.Authentication  Readme issues

### ISSUE THREAD

**Issue by v-xuto** [Azure/azure-sdk-for-net#18184]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/mixedreality/Azure.MixedReality.Authentication#authenticating-a-user-using-device-code-authentication):
![image](https://user-images.githubusercontent.com/57166602/105811265-51d61200-5fe7-11eb-9f43-9e4c378fcf93.png)

Reason: The method `GetTokenAsync` does not require parameters.
Suggestion: Remove `accountId `.

@jongio for notification.

**Comment by jsquire** [comment]
@AlexGhiondea:  Do you have a suggestion for a Mixed Reality contact to route this to?   There's none registered for `Service Attention`.
