### ISSUE TITLE
[BUG] no exception is thrown when trying to delete a non existent Disk object

### ISSUE THREAD

**Issue by nir-yurman** [Azure/azure-sdk-for-net#18181]
**Describe the bug**
Deleting a disk resource from Azure using IcomputeManagementClient.Disks.DeleteWithHttpMessagesAsync() does not fail when disk resource does not exist 

**Expected behavior**
Either an HTTP exception with error code 404 (not found), or the AzureOperationResponse which is returned should indicate a bad request through 4XX status code

**Actual behavior (include Exception or Stack Trace)**
Response as HTTP code 204 

**To Reproduce**
1. Simply make a call to DeleteWithHttpMessagesAsync with valid resource group and invalid resource name

**Environment:**
Microsoft.Azure.Management.Compute v41.0.0

for more info please reach-out to nyurman@microsoft.com

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
Per [rest api spec](https://github.com/Azure/azure-rest-api-specs/blob/44ec11c74634f1afa5bbe0d3f2678b7f819ebf8e/specification/compute/resource-manager/Microsoft.Compute/stable/2020-06-30/disk.json#L226)  Service will return 204 if disk already deleted as defined behavior.
