### ISSUE TITLE
[BUG] MediaServices Assets.DeleteAsync "object reference not set" 

### ISSUE THREAD

**Issue by jhancock4d** [Azure/azure-sdk-for-net#18187]
**Describe the bug**
On client.Assets.DeleteAsync with Microsoft.Azure.Management.Media including a valid id for the asset in question it throws an object not set error.

**Expected behavior**
Should delete the asset.

**Actual behavior (include Exception or Stack Trace)**
Crash.

**To Reproduce**
1. Create a client
2. Create media services asset.
3. Delete the same asset.

**Environment:**
nuget: Microsoft.Azure.Management.Media 3.0.3
.net core 5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
@jhancock4d, is it possible to provide a call stack for the crash? Thanks

**Comment by akucer** [comment]
@jsquire - Are you able to provide a call stack for the crash? If this isn't available, please provide your media services account name and Azure DC location and date that you saw this issue look into investigating this from logs.

**Comment by jsquire** [comment]
@akucer:  Please be aware that I am only serving as first triage.   The reporter of this issue is @jhancock4d;  you'll need their insight on your inquiry.
