### ISSUE TITLE
Resource Manager Documentation is Missing Information

### ISSUE THREAD

**Issue by geedsen** [Azure/azure-sdk-for-net#18185]
And what does it return if the RG does not exist, exception? null?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f04c9c8-98db-4f04-0256-cd2986561c17
* Version Independent ID: 76d52b7f-5d45-8e1b-8f84-c2e5a7b7ad5b
* Content: [ISupportsGettingByName&lt;T&gt;.GetByName(String) Method (Microsoft.Azure.Management.ResourceManager.Fluent.Core.CollectionActions) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.core.collectionactions.isupportsgettingbyname-1.getbyname?view=azure-dotnet#Microsoft_Azure_Management_ResourceManager_Fluent_Core_CollectionActions_ISupportsGettingByName_1_GetByName_System_String_)
* Content Source: [xml/Microsoft.Azure.Management.ResourceManager.Fluent.Core.CollectionActions/ISupportsGettingByName`1.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ResourceManager.Fluent.Core.CollectionActions/ISupportsGettingByName`1.xml)
* Service: **azure-resource-manager**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member  best able to assist.

**Comment by yungezz** [comment]
hi @xccc-msft could you pls help? thanks

**Comment by xccc-msft** [comment]
@geedsen It will throw `CloudException` with message below:
```csharp
Microsoft.Rest.Azure.CloudException : Resource group 'xxx' could not be found.
```
