### ISSUE TITLE
[BUG] Is ClientDiagnostics's DiagnosticListener leaking?

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#18199]
An internal partner is seeing a leak caused by:
- [ClientDiagnostics derives from DiagnosticScopeFactory](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs#L20)
- [DiagnosticScopeFactory creates a DiagnosticListener](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/DiagnosticScopeFactory.cs#L25)
- [DiagnosticListener disposal removes itself from a global list](https://github.com/dotnet/corefx/blob/release/3.1/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticListener.cs#L160)
- We don't dispose `ClientDiagnostics`.

Should we add a destructor on DiagnosticScopeFactory that disposes its listener?

**Comment by pakrym** [comment]
Related: https://github.com/microsoft/ApplicationInsights-dotnet/issues/1867

**Comment by pakrym** [comment]
We can go about it in two ways:
1. Add a finalizer to the `DiagnosticScopeFactory`
2. Cache DiagnosticListener in a dictionary based on the namespace.

**Comment by kasobol-msft** [comment]
Azure Storage SDK included this fix in the release today. Package versions can be found [here](https://github.com/Azure/azure-sdk-for-net/commit/049ccc4ddcdb874b4869144d434d46a83920831a)
