### ISSUE TITLE
[QUERY] Azure.RequestFailedException thrown/logged in Debug window when Exists() method called on BlobClient

### ISSUE THREAD

**Issue by DaveSlinn** [Azure/azure-sdk-for-net#18209]
**Query/Question**
Is it normal for the BlobClient Exists method to log a RequestFailedException which is displayed in the debug window of Visual Studio?

**Environment:**
 - Azure.Storage.Blobs version 12.8.0
 - Windows Forms .NET 5 app (running on Windows 10 Version 20H2 build 19042.782
 - Visual Studio Enterprise 2019 Version 16.8.4

Here is my code that is calling the .Exists() method to see if the blob already exists.  If it doesn't, then it calls .Upload().
```C#
    public class AzureFileUploader
    {
        private const string ACCESSKEY = "**REDACTED**;
        private const string CONTAINER = "files";

        private BlobContainerClient blobContainer;

        public AzureFileUploader()
        {
            blobContainer = new BlobContainerClient(ACCESSKEY, CONTAINER);
        }

        public string UploadFile(string filename, string filePath)
        {            
            var blob = blobContainer.GetBlobClient(filename);            

            if (!blob.Exists())
            {
                UploadFile(filePath, blob);
            }

            return blob.Uri.AbsoluteUri;
        }

        private void UploadFile(string filePath, BlobClient blob)
        {
            blob.Upload(filePath);
            blob.SetHttpHeaders(new BlobHttpHeaders() { ContentType = "image/jpeg" });
        }
    }
```
The code runs fine and the images are upload but I do see a lot of Exception thrown: 'Azure.RequestFailedException' in Azure.Storage.Blobs.dll in the debug output:
![image](https://user-images.githubusercontent.com/18301427/105918751-1133c400-5ffa-11eb-9df6-494994b2c71c.png)

When stepping through the code, they appear during the called to .Exists(). It seems like that function catches the thrown exception and then logs it.  Seems like this is expected behaviour and I can safely ignore it, but just wanted to be sure.  Seems weird that if you were going to expect an exception (for instance, if the blob does not exist), so you catch it, handle it properly - in this case, return false, but then log it.  I've read the source and think the culprit is here: 
https://github.com/Azure/azure-sdk-for-net/blob/e2fad94b95fa2a27a73af758e4e2c39b724c5949/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L1557
But in my opinion, expecting a specific exception, handling it and still logging it can be misleading.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

Yes this is expected behavior. The service naturally throws an HTTP error code to confirm whether or not the blob exists. The `Exists` method is merely a convenience method so that users don't have to parse the Error Code to see if it's the error code they expect for a blob not existing.
