### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by Adam-Howarth** [Azure/azure-sdk-for-net#18223]
Propeties of a Blob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aee2a111-1d68-f5a5-5e90-24c9567d74a3
* Version Independent ID: ee336e90-0a99-0068-1af3-3c44e75327d2
* Content: [BlobProperties Class (Azure.Storage.Blobs.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobproperties?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Models/BlobProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Models/BlobProperties.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Thanks for catching this, we will look to correct this as soon as we can.
