### ISSUE TITLE
Cannot mock the BlobBaseClient.CanGenerateSasUri property for testing

### ISSUE THREAD

**Issue by DMEvans** [Azure/azure-sdk-for-net#18224]
When trying to unit test a class that provides SAS token URI's for blob access I'm struggling to be able to assert all of the necessary invocations on the BlobClient.

The following code example shows what I'm trying to do:

```
var blobClient = GetBlobClient(blobName);

if (!blobClient.CanGenerateSasUri)
{
    throw new InvalidOperationException(MSG_CANNOT_GENERATE_TOKENS);
}

var sasBuilder = ...

var sasUri = blobClient.GenerateSasUri(sasBuilder)
```

In my tests I want to ensure that the correct exception is thrown when "CanGenerateSasUri" evaluates to "false", and that the correct values are passed to "GenerateSasUri" when it evaluates to "true".

However, the source code shows that the "CanGenerateSasUri" property is not virtual, so it cannot be overridden by my mocking framework.  However, ALL of the other public members of this class are marked as virtual except this one.
https://github.com/Azure/azure-sdk-for-net/blob/430f2eba747d6de99a43f4f8bd63cd28e673f979/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L176-L180

So my question is two-fold...
1) Is there a reason why this property (and the same property on several other client classes in the Azure.Storage namespace) cannot be made virtual so it can be overridden for testing?
2) Is there a workaround that will allow me to control within an individual test whether "CanGenerateSasUri" will return "true" or "false"?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi, there's actually no reason why we didn't make this virtual. It was an oversight when we implemented the new feature. Thanks for catching this, we will update this in all our clients so that it can become mockable.

**Comment by amnguye** [comment]
Just merged a PR to resolve the issue. The fix will be in the next release.
