### ISSUE TITLE
ReceiveAsync(Int64) only works for deferred messages

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/azure-sdk-for-net#18238]
Unlike the other Receive methods on this page ReceiveAsync(Int64) only works with deferred messages. It should be mentioned in the documentation. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d143c39-d0eb-b3ed-1ac3-6acd89beff8d
* Version Independent ID: 05b757af-1781-65c5-57a1-40a8f12a7511
* Content: [MessageReceiver.ReceiveAsync Method (Microsoft.ServiceBus.Messaging) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.messagereceiver.receiveasync?view=azure-dotnet#Microsoft_ServiceBus_Messaging_MessageReceiver_ReceiveAsync_System_Int64_)
* Content Source: [xml/Microsoft.ServiceBus.Messaging/MessageReceiver.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus.Messaging/MessageReceiver.xml)
* Service: **service-bus-messaging**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by axisc** [comment]
Thanks for raising this issue @ErikMogensen.

This documentation is auto-generated, we will make the edits to the comment in the next push.

cc: @DorothySun216

**Comment by DorothySun216** [comment]
I have sent out a PR and we will release a .net framework SDK (WindowsAzure.Servicebus) reflecting the change soon.
