### ISSUE TITLE
[FEATURE REQ] Enforce CA2214: Do not call overridable methods in constructors

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#18244]
This is follow up on https://github.com/Azure/azure-sdk-for-net/pull/18243 .

We noticed that some Moq scenarios (i.e. where client constructor is involved) don't work due to overridable members usage (see referenced PR for examples).

The ask is to:
- enforce [CA2214 rule](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2214) across the board.
- check if CA2214 can catch situation where overridable member is called indirectly from constructor (like in the PR referenced), possibly build analyzer for that case.

**Comment by pallavit** [comment]
I think this will be a good issue to consider for the new toolchain.
/cc: @annelo-msft , @KrzysztofCwalina

**Comment by JimSuplizio** [comment]
Hi @kasobol-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
