### ISSUE TITLE
Seriously, how many times is it gonna take?

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-sdk-for-net#18241]
Do you create one of these things during an application life cycle, or when you need one?

Are the methods thread safe?

It boggles the mind that you guys haven't figured out that you need to include this information for these types of classes EVERY TIME. It's like your selling cars and surprised that everyone wants headlights and a steering wheel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c0ad0bb-9243-5608-ad41-6eafe131c286
* Version Independent ID: 7de4ef17-3aa4-2003-be81-173aea1b2dec
* Content: [ConfigurationClient Class (Azure.Data.AppConfiguration) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.data.appconfiguration.configurationclient?view=azure-dotnet)
* Content Source: [xml/Azure.Data.AppConfiguration/ConfigurationClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Data.AppConfiguration/ConfigurationClient.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by AlexGhiondea** [comment]
Hey @jackbond! Thanks for creating this issue and for your feedback.

To answer your question about the `ConfigurationClient` -- you can think of that as the object that you use to communicate with the App Configuration Azure Service. As such, you can either create it once per application or whenever you need to connect to Azure. This is dependent on what your application is doing and on your architecture.

As for the methods on the client itself, I believe they are all thread safe -- have you seen a case where that is not correct?

**Comment by jackbond** [comment]
Thanks for the quick response Alex. It's not so much IF you can do it one way or the other, it's what's the guidance. For example, the authors of the HttpClient make it very clear, it's best to create one per application. In the case of ConfigurationClient, if it's thread safe, I'll inject one and not waste time creating one for every call.

At the bare minimum, and this goes to my primary point, thread safety should be included for all client libraries, ZERO exceptions. Hearing, "I believe they're all thread safe", isn't at all reassuring. Has the library actually been tested? Do the tests not include multithreading tests?

Sorry if I seem short, but this seems like the billionth time I've had to ask this question regarding an Azure library.

**Comment by AlexGhiondea** [comment]
@jackbond thanks for clarifying. It sounds like you've had this comment several times before and it is frustrating to have to repeat it, but this is the first time I've seen this feedback for any of our libraries. 

It is good feedback and something I'll follow-up on to make sure that information is captured in our docs.microsoft.com page.

For the App Configuration client, as well as our other clients, they are thread-safe and you should be able to create one per application and use it.

We have a blog post talking about this and other topics around the lifetime management of our clients that you can read: [Lifetime management for Azure SDK .NET clients](https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/). 

Please feel free to ask any questions that are not addressed in that blog post!

**Comment by jackbond** [comment]
Now THAT is an outstanding response.

You guys should link to that page from literally every client library home page.

Thank you so much, just about made my day.

**Comment by AlexGhiondea** [comment]
@jackbond thanks for the feedback and happy this helped you!

I am following up on the right way to address this for all of our libraries!

I am closing this issue for now, but please reopen/ping me on it if you have additional feedback!
