### ISSUE TITLE
[BUG] Management.EventGrid Client Throws Null Reference When Deleting EventSubscription

### ISSUE THREAD

**Issue by mariohdez** [Azure/azure-sdk-for-net#18250]
**Describe the bug**
The management event grid client sdk version 6.0.0 is throwing a null reference exception when trying to delete an event subscription. The event subscription is successfully deleted, and when I hit "continue" on visual studio debugger, the code goes on as expected.

**Expected behavior**
The `client.EventSubscriptions.DeleteAsync(scope, subscriptionName)` should delete the event subscription without throwing null reference exception on the azure rest client.

**Actual behavior (include Exception or Stack Trace)**
Microsoft.Rest.ClientRuntime.Azure is throwing null reference exception even though I am able to successfully delete the event subscription.
![image](https://user-images.githubusercontent.com/22581660/106111041-66f29400-6100-11eb-8583-641b693a8d5e.png)
![image](https://user-images.githubusercontent.com/22581660/106111238-a4efb800-6100-11eb-8e51-14665b6ea21b.png)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. On visual studio 2019, install management event grid package version 6.0.0.
2. using valid credentials, create an instance of the management event grid client
3. call the delete async call on the event subscriptions
4. run the code through debugger

**Environment:**
 - Name and version of the Library package used: [e.g. Microsoft.Managmenet.EventGrid 6.0.0] 
 - Hosting platform or OS and .NET runtime version 
PS C:\Users\marher> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\
 - IDE and version : Microsoft Visual Studio Enterprise 2019
Version 16.8.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
Looking at your repro step, it may because you have enabled debug exception setting to always break on NullRefException (catch first chance exception). This exception may be thrown due to probing for a few different supported LRO mechanisms. The [exception is handled](https://github.com/Azure/azure-sdk-for-net/blob/84b3a20665abed7254f883d7c71ffdcc1d04a878/sdk/mgmtcommon/ClientRuntime.Azure/ClientRuntime.Azure/LRO/LROPollState.cs#L128) and will move onto other checks. If this is the case, it is normal.

**Comment by mariohdez** [comment]
@allenjzhang , how do I go about disabling "catch first chance exceptions" to test your hypothesis?

Mario

**Comment by mariohdez** [comment]
@allenjzhang, I enabled the "Just my code" debugging option in Visual Studio and proceeded to not hit the error.

Thanks for the help here.
