### ISSUE TITLE
Figure out state of FR track 1 package 

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#18291]
Package: https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.FormRecognizer/0.8.0-preview.
Instructions: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/377/Updates-to-improve-track2-release-visibility

**Comment by kinelski** [comment]
Package has been deprecated and unlisted.
