### ISSUE TITLE
[FEATURE REQ] Provide Task equivalents to IAsyncEnumerable methods

### ISSUE THREAD

**Issue by isaacabraham** [Azure/azure-sdk-for-net#18306]
Related to **Azure.Storage.Blobs**, but may be more widespread.

The SDK library exposes methods that return data e.g. `GetBlobsAsync` as either pages or through single items, both times via `IAsyncEnumerable`. Unfortunately, F# doesn't have any built-in way to consume these. You can sort of work around it by writing some code that flattens the result into a `Task` and returns the array of all blobs i.e. `IAsyncEnumerable<'T> -> Task<'T array>`. However, this changes the semantics of the query (rather than lazily returning items, it eagerly retrieves all of them).

I propose either introducing something similar to the old storage SDK where you had a continuation token, or some other way to yield out a page of data e.g. skip / take (although I appreciate this might not really fit with the nature of e.g. blobs). Alternatively, provide methods which returns `Task<T []>` as well as `IAsyncEnumerable<T>`.

**Comment by jsquire** [comment]
//cc: @tg-msft, @KrzysztofCwalina

**Comment by jsquire** [comment]
Hi @isaacabraham.  Thank you for your feedback. Tagging and routing to the team best able to assist with the Storage portions and the .NET architecture team for wider consideration.

**Comment by tg-msft** [comment]
Dropping Storage and adding Azure.Core because this question is more about `AsyncPageable<T>` support in F#.

Adding workarounds to Azure client libraries isn't the best approach.  I think it's up to the F# team/community to figure out how they want to integrate with new(er) .NET features like `IAsyncEnumerable<T>`.  I would expect something like `FSharp.Control.AsyncSeq` to provide a reasonable solution.

In the meantime, you can still work with the interface directly.  Here's a basic example of [manually iterating pages](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Response.md#iterating-over-asyncpageable-pages) like you would have done in the old Storage library:

```F#
open System.Collections.Generic
open Azure.Storage.Blobs
open Azure.Storage.Blobs.Models

// Gets the first item in an IAsyncEnumerable
let firstAsync (seq : IAsyncEnumerable<'a>) =
    async {
        let enumerator = seq.GetAsyncEnumerator()
        // TODO: Not sure if Async has anything for ValueTask yet?
        let! hasPage = enumerator.MoveNextAsync().AsTask() |> Async.AwaitTask
        return if hasPage then enumerator.Current else null
    }

[<EntryPoint>]
let main argv =
    async {
        let storage = BlobServiceClient "<Connection-String>"
        let containers = storage.GetBlobContainersAsync()
        let mutable continuationToken = null
        let mutable finished = false
        while not finished do
            let remainingPages = containers.AsPages continuationToken
            let! nextPage = firstAsync remainingPages
            printfn "Page:"
            for (container : BlobContainerItem) in nextPage.Values do
                printfn $"    Container: {container.Name}"
            printfn $"    ContinuationToken: {nextPage.ContinuationToken}"
            continuationToken <- nextPage.ContinuationToken
            finished <- System.String.IsNullOrEmpty continuationToken
    } |> Async.RunSynchronously |> ignore
    0
```

**Comment by isaacabraham** [comment]
@tg-msft I've also raised an issue in fslang/suggestions on this: https://github.com/fsharp/fslang-suggestions/issues/975 with a simple AsyncIEnumerable to Task function.

There's actually a `task { }` builder in F# as a third-party package which is commonly used nowadays and it allows use of `let!` on tasks and value tasks, so that's not an issue. The bigger concern from that sample is that it's really not composable - every time you wanted to do this, you'd need to duplicate this pattern. As you say, something like `AsyncSeq` would be needed (or a `TaskSeq` if you will) to allow this to really work properly.

Perhaps the best thing to do then is to put some documentation up on the Azure SDK site which provides some guidance on how to consume `Pageable`s from F#, given that this is something that is pervasive within the new Azure SDK.

**Comment by tg-msft** [comment]
Sure, that sample was showing how you'd manually follow continuation tokens like the old library.  It's definitely clunky and why we switched to `Async/Pageable<T>` for the new libraries.  :smile:

I agree we should have samples for F# users on how to use of all our major patterns.  I filed #18322.
