### ISSUE TITLE
[BUG] ManagedIdentityCredential fails sometimes in AKS

### ISSUE THREAD

**Issue by PSanetra** [Azure/azure-sdk-for-net#18312]
**Describe the bug**
We are using the `ManagedIdentityCredential` class to get access tokens for managed identities. We are deploying the application to AKS, where we are using https://github.com/Azure/aad-pod-identity.

The instance of the `ManagedIdentityCredential` is a singleton.

Sometimes after starting a new pod, we get the exception `Azure.Identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.` everytime when the pod is trying to get the access token. If the pod is able to start without this exception, the exception is never observed during the lifetime of the pod.

The problem seems to be that there might be a delay after starting up the pod, after which the IMDS endpoint is available for the pod in AKS. When the pod is trying to get the access token before the endpoint is available, it has some bad state, where it will never be able to recover from.

The cause of the issue is probably this code: https://github.com/Azure/azure-sdk-for-net/blob/705f3296529b2e30e16bfe42fdd2245511a5c0b0/sdk/identity/Azure.Identity/src/ManagedIdentityClient.cs#L51-L67

The `ManagedIdentityClient` tries several strategies to get a `ManagedIdentitySource`. If all of them fail, it sets the value of `_identitySourceAsyncLock` to `null` and will therefore never try to resolve the `ManagedIdentitySource` again.

**Expected behavior**
The exception should not occur or it should be possible to recover from this failed state when the IMDS endpoint gets available.

**Actual behavior**
The exception occurs and it is not possible to recover from the failed state.

**To Reproduce**

1. Deploy AKS
2. Deploy the aad-pod-identity services
3. Deploy a pod using the ManagedIdentityCredentials
4. Pray for observing the exception
5. Observe the exception

**Environment:**
 - AKS 1.17.11
 - AAD Pod Identity 1.7.1
 - Azure.Identity 1.2.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by christothes** [comment]
Hi @PSanetra - In your testing, how long does it take the IMDS endpoint to become available? The reason I ask is that I am wondering if changing to a less aggressive timeout would be a better way to approach this issue. 

We currently are set to [timeout after 1 second](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/ImdsManagedIdentitySource.cs#L22). However, the recommendation is to [retry in the event of a timeout](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#retry-guidance).

**Comment by PSanetra** [comment]
Hi @christothes, I am not sure how long the endpoint needs to become available in these problematic edge cases. By gut feeling I would say that the pods are currently starting in 7 out of 10 times in a correct state.

I think most of the time the first attempt to get an access token should be triggered by a readiness probe and our readiness probes are configured to run after an inital delay of 5 seconds.

**Comment by christothes** [comment]
It seems like either your initialization code would need to implement a retry or `ImdsManagedIdentitySource` could just handle that. I think my preference would be to have `ImdsManagedIdentitySource` handle the retry.

**Comment by PSanetra** [comment]
@christothes I am not sure if a less aggressive timeout would help. I think it would be better to quickly throw an exception and let the application decide to retry.

It might cause some weird trouble with `ChainedTokenCredentials` if the `ImdsManagedIdentitySource` would handle the retry as it would block trying other TokenCredentials, wouldn't it?

I think for our services it would not be a big problem to retry as they wouldn't report as ready until the it was possible to get an access token for the first time.

**Comment by christothes** [comment]
> @christothes I am not sure if a less aggressive timeout would help. I think it would be better to quickly throw an exception and let the application decide to retry.
> 
> It might cause some weird trouble with `ChainedTokenCredentials` if the `ImdsManagedIdentitySource` would handle the retry as it would block trying other TokenCredentials, wouldn't it?
> 
> I think for our services it would not be a big problem to retry as they wouldn't report as ready until the it was possible to get an access token for the first time.

Could you expand a bit more on the scenario where the retry policy would block trying other TokenCrednetials? Since `ImdsManagedIdentitySource` only gets invoked when all other request mechanisms fail, and other code paths requiring `ImdsManagedIdentitySource` would be blocked either way , I'm wondering how this would occur. There may be a scenario here I am unfamiliar with.

https://github.com/Azure/azure-sdk-for-net/blob/f611aedabcbee5d9cf58b65d0ca5cd84990d3c43/sdk/identity/Azure.Identity/src/ManagedIdentityClient.cs#L59-L63

**Comment by PSanetra** [comment]
@christothes The scenario I had in mind were using `DefaultAzureCredential`.

So when I would try the get an access token via an `DefaultAzureCredential` it would be tried to get a token via, `EnvironmentCredential`, `ManagedIdentityCredential`, `SharedTokenCredential`, and so on.

https://github.com/Azure/azure-sdk-for-net/blob/a79bd104ab8c2cf79e0f9b2c60619de85f101d71/sdk/identity/Azure.Identity/src/DefaultAzureCredential.cs#L169-L220

When you are now introducing a retry mechanism in the `ImdsManagedIdentitySource`, the `ManagedIdentityCredential.GetTokenAsync()` method would block until the timeouts and retries of `ImdsManagedIdentitySource` are exhausted. And this would always happen, even if the IMDS endpoint will never be available, which is quite often the case when using `DefaultAzureCredential`.

**Comment by christothes** [comment]
@PSanetra Thanks for the clarification. I did a bit of research on this one and I discovered that we've encountered this issue before and created an example workaround pod that works around this issue without having to consider changes to the default behavior. 

Would this work for your scenario? https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/tests/pod-identity/test-pod-identity/templates/job.yaml#L23

**Comment by PSanetra** [comment]
@christothes hmm, yes I guess this would work, although we are currently using a different workaround by retrying getting the access token with new `ManagedIdentityCredential` instances.

I think this should be fixed in the library. The PR, I have submitted should at least be a significant improvement in contrast to the current behavior as this will make it possible to retry getting the access token with the same `ManagedIdentityCredential` instance.

**Comment by christothes** [comment]
The only concern with the fix proposed in the PR is that it could also introduce a retry for `ImdsManagedIdentitySource` on every GetToken request as part of a `ChainedTokenCredentials`, which doesn't cache the first successful credential in the chain. 

Would it be possible for you to try the proposed workaround?

**Comment by PSanetra** [comment]
@christothes I guess the proposed workaround could work, but I prefer to continue to use our current workaround approach.

I think retrying to get a Token via `ImdsManagedIdentitySource` was actually the expected behavior of `ChainedTokenCredential`. I guess most of the time the check for the endpoint will not even wait for the timeout. Instead it will probably receive a connection reset very quickly.

**Comment by PSanetra** [comment]
@christothes Maybe it would be a good idea to implement the retry strategy in the `ManagedIdentityClient` in such a way that it will perform the next check only after the time, specified in https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#retry-guidance

After 5 retries it may never retry again. This way it may be possible that some of the first `GetTokenAsync()` calls may be slow, but after a while it will not try anymore to check if the IMDS endpoint is available as it would be very unlikely that the IMDS endpoint becomes available after such a long time.

**Comment by christothes** [comment]
@PSanetra - Initially, I had some same thought, but since the retry behavior has other implications in the context of chained credentials, I think it is safest to workaround it either with the pod workaround, or by retrying manually with a new instance of `DefaultAzureCredential`.

**Comment by bohlenc** [comment]
> @PSanetra Thanks for the clarification. I did a bit of research on this one and I discovered that we've encountered this issue before and created an example workaround pod that works around this issue without having to consider changes to the default behavior.
> 
> Would this work for your scenario? https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/tests/pod-identity/test-pod-identity/templates/job.yaml#L23

Hi,
in case anyone faces the same problem and wants or needs to implement the workaround for a number of deployments without touching the each of them directly, I implemented a mutating webhook that can be configured accordingly: https://github.com/bohlenc/k8s-pod-mutator-webhook (see [Examples](https://github.com/bohlenc/k8s-pod-mutator-webhook#examples)

**Comment by deyanp** [comment]
Please note that the initContainers sample

https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/tests/pod-identity/test-pod-identity/templates/job.yaml#L23

must be extended with 

`&mi_res_id=pod-identity-test`

otherwise it will check for any managed identity (there might be others on VM) ...
