### ISSUE TITLE
Allow SDK authors to use nullable annotations internally

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#18328]
We would like to allow SDK authors to use nullable annotations internally but avoid them on the public API surface.

- [ ] Add a check to ensure we don't ship annotations in public API (a Roslyn analyzer should be reasonable)
- [ ] Maybe find a way to compile the package against annotated APIs without shipping an extra package target so the library author get System.* type annotations.

**Comment by chwarr** [comment]
Can you expand on why the annotations shouldn't be on the public API surface? When I'm programming against an API, nullable annotations are a boon to me. They quickly let me know when an API admits a null value and when it doesn't. I have to look at documentation or guess otherwise.
