### ISSUE TITLE
Missing examples and spelling issues

### ISSUE THREAD

**Issue by Kellybnd** [Azure/azure-sdk-for-net#18347]
The main page for the BlobUploadOptions class has a misspelling of "paratmers" for parameters.  It is also lacking in examples of usage.  From the documentation it is not clear how to specify the Content Type of the uploaded blob. After digging into the various options I was able to determine that it is set via the HttpHeaders property.  It would be nice to have a few examples in the BlobUploadOptions documentation for common use scenarios, such as:
`var opts = new BlobUploadOptions();
{
   HttpHeaders = new BlobHttpHeaders() 
   {
       ContentType = "application/octet-stream"
   }
};`

Having additional examples for using the Metadata property would also greatly improve the documentation.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1d51fd10-c84b-a5d1-4cad-d2cc4e085ce0
* Version Independent ID: cf24bf5d-caf9-a84e-2edc-31d9d9d841d9
* Content: [BlobUploadOptions Class (Azure.Storage.Blobs.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobuploadoptions?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Models/BlobUploadOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Models/BlobUploadOptions.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi! Thanks for the feedback, we will look to updating the mispellings. The examples you are referring to are rather specific, we would have to add an example for every single available parameter out there. We will do our best to come up with an example that would encompass this scenario.

**Comment by NimbleKelly** [comment]
Hi @amnguye, 

I'd suggest that examples simply cover some of the common scenarios. For instance, the blob storage documentation for managing blob properties and metadata contains examples for setting the ContentType and ContentLanguage https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-properties-metadata?tabs=dotnet.  Both of these properties can be set using BlobUploadOptions while uploading.  I don't think you need to have an example for every available parameter, but certainly the ones that cover common use cases would be helpful.  Having no examples at all, along with minimal descriptions make the API much more difficult to use.

Thanks!

**Comment by navba-MSFT** [comment]
@Kellybnd Apologies for the late reply. Thanks for the feedback. The above PR has been created and it is currently under review. In the meantime, if you have any questions on this, please let us know.
