### ISSUE TITLE
[BUG] AKV10032 when accessing key vault cross-tenant

### ISSUE THREAD

**Issue by dapathy** [Azure/azure-sdk-for-net#18359]
**Describe the bug**
Receiving an authentication error when accessing cross-tenant Keyvault using ClientSecretCredential.

This works using legacy Microsoft.Azure.KeyVault package.

Additionally, workarounds mentioned here: [https://github.com/Azure/azure-sdk-for-net/issues/11559](https://github.com/Azure/azure-sdk-for-net/issues/11559) do not seem to work.

**Expected behavior**
Should be able to access key vault in another tenant when the service principal has been assigned the sufficient permissions.

**Actual behavior (include Exception or Stack Trace)**

> Status: 401 (Unauthorized)
> 
> Content:
> {"error":{"code":"Unauthorized","message":"AKV10032: Invalid issuer. Expected one....

**To Reproduce**

`CertificateClient = new CertificateClient(new Uri(KeyVaultUrl), new ClientSecretCredential(TenantId, AppId, ClientSecret));`

Where TenantId is different from the Tenant that owns the Key Vault

**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Certificates 4.1.0
 - Hosting platform or OS and .NET runtime version: .NET Framework 4.7.2/Windows 10
 - IDE and version : Visual Studio 16.8.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by NickMOrlando** [comment]
Any update on this particular issue? 
I'm actively trying to coordinate a large migration of resources between two tenants after an acquisition.
We'd like to be able to move/re-create our applications independently from the KeyVault to minimize downtime during the migration, but it seems we can't proceed this way until this bug is resolved.

**Comment by heaths** [comment]
This has been enabled in Azure.Identity but needs to be enabled in Key Vault, built upon that work:

* https://github.com/Azure/azure-sdk-for-net/pull/21378/files#diff-e6cdf954943d7cfe61416c460ce4b0b034d1f3821e334b4c78a3ad27a94f3961R84
* https://github.com/Azure/azure-sdk-for-net/blob/e26ff0247ed6a9a08d29081ef3ccaf00bf01c68f/sdk/keyvault/Azure.Security.KeyVault.Secrets/tests/SessionRecords/SecretClientLiveTests/BackupSecret.json#L27
