### ISSUE TITLE
[QUERY] Azure Servicebus Prefetch and Session Behavior in Azure.Messaging.ServiceBus

### ISSUE THREAD

**Issue by davidallyoung** [Azure/azure-sdk-for-net#18350]
**Query/Question**
How can we help?
Hi everyone,

My team and I are utilizing sessions and curious if when using prefetch if the messages that are prefetched are only for the Session that the client currently has locked, or if it prefetches other messages. We assume it prefetches messages for only that session, but wanted to check in and vet our assumption.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] Azure.Messaging.ServiceBus 7.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8] NetCore 3.1, running with base `mcr.microsoft.com/dotnet/aspnet:3.1-alpine`
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by JoshLove-msft** [comment]
Hi @davidallyoung, you are correct that the prefetch only applies to sessions that are currently locked. When using a `ServiceBusSessionReceiver`, there would be only a single session that the receiver is bound to. With a `ServiceBusSessionProcessor`, there may be multiple sessions locked simultaneously, but prefetch only happens with the sessions that are locked.

**Comment by davidallyoung** [comment]
Awesome thank you for the clarification @JoshLove-msft !

**Comment by JoshLove-msft** [comment]
Sure thing, feel free to reopen if you have further questions on this topic.
