### ISSUE TITLE
[FEATURE REQ] Support SAS credentials in Azure.Data.Tables

### ISSUE THREAD

**Issue by johnthcall** [Azure/azure-sdk-for-net#18360]
**Library or service name.**
What library or service is this request related to? Azure.Data.Tables
 
**Is your feature request related to a problem? Please describe.**
Recently Azure.Core added support for SAS credentials, Azure Storage added support for blob and queue for creating clients with AzureSasCredential in  #17646. The ask is to support similar constructors accepting AzureSasCredential for TableServiceClient and TableClient.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
