### ISSUE TITLE
[FEATURE REQ] Ability to configure client options together with connection string. 

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#18365]
**Library or service name.**
Storage Webjobs Extension (and possibly others).
 
**Is your feature request related to a problem? Please describe.**
When I'm using connection string I can't specify client option like retry policy and so on.
Relevant code is here https://github.com/Azure/azure-sdk-for-net/blob/7cf8349b646ee4c87997a49a0bf67f261c5f9f6f/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/src/Shared/StorageClientProvider.cs#L59 .

Something like this could be viable solution:
```
connectionName" : {
"connectionString": "...",
"other options" ...
}
```

**Comment by jsquire** [comment]
Closing;  This is not a feature that we'll be moving forward with, as the intent is to ensure that client configuration is performed in `host.json`.
