### ISSUE TITLE
Microsoft.Azure.ServiceBus.QuotaExceededException: Cannot allocate more handles. The maximum number of handles is 4999.

### ISSUE THREAD

**Issue by daviegy** [Azure/azure-sdk-for-net#18363]
Ever since I implemented Microsoft Azure Service Bus, I have been having this error in my production environment.  
`Microsoft.Azure.ServiceBus.QuotaExceededException: Cannot allocate more handles. The maximum number of handles is 4999.`

I noticed that this error messages come up frequently when processing large numbers of messages but works with fewer.

Just to give you a overview my system processes lots of messages and service bus is core part of our processes. 

Please, find below my code

` public class ServiceBusSender: IServiceBusSender
    {  
        private  IQueueClient _queueClient;
        private readonly ServiceBusConnection _connection;
        
        public ServiceBusSender(ServiceBusConnection connection)
        {  
            _connection = connection;
        }

        public Task Publish<T>(T value, string queueName,string partitionkey = null)
        {          
            try
            {
                var message = new Message
                {
                    Body = Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(value)),
                    PartitionKey = partitionkey
                };
                _queueClient = new QueueClient(_connection, queueName, ReceiveMode.PeekLock, RetryPolicy.Default);
                return _queueClient.SendAsync(message);
            }
            catch(QuotaExceededException ex)
            {
               throw ex;
            }
        }

    }
`
 Please, I will really appreciate if the servicebus team can point me to something I am doing wrong.
thanks

**Comment by SeanFeldman** [comment]
@daviegy, the issue now is in the right repo and will be triaged. Cheers.
