### ISSUE TITLE
[BUG] ManagedIdentityCredential fails with AuthenticationFailedException for a 502 response

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#18362]
In the event that no managed identity endpoint information is available in the environment, the `ManagedIdentityCredential` will attempt to connect to the well-known IMDS endpoint `http://169.254.169.254` and it treats either the failure to connect or a 400 response from the service as an indication that no managed identity is available resulting in a `CredentialUnavailableException` ultimately being thrown from `GetToken`. All other failures result in raising an `AuthenticationFailedException` indicating there is a managed identity available, but some unknown error has occurred obtaining a token. This overlooks the case where the machine is using a proxy, in these cases the connection may succeed and a request results in a 502 response rather than 400.

>ManagedIdentityCredential authentication failed: Service request failed.
Status: 502 (cannotconnect)

Here the well-known endpoint is really not available and should be treated as such raising a `CredentialUnavailableException`.

The `DefaultTokenCredential` and `ChainedTokenCredential` handle any `CredentialUnavailableException` thrown from their inner credentials, and treat them as a signal that the credential is not available, and to fallback to the next credential in the chain. Whereas `AuthenticationFailedException` will not be handled, and hence fail the request to `GetToken`. Because of this, the above issue in `ManagedIdentityCredential` impacts developers running in environments with certain proxy configurations, as it prevents the `DefaultAzureCredential` from falling back to credentials intended to authenticate in the development environment.

**Expected behavior**
What is the expected behavior?

Gateway errors encountered when connecting to the IMDS endpoint should be treated as the endpoint not being available, and hence result in a `CredentialUnavailableException` being thrown.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

These errors go unhandled and result in an `AuthenticationFailedException` ultimately being thrown, preventing fallback to subsequent credentials in `DefaultAzureCredential` or `ChainedTokenCredential`.

**Next Steps**
We should update the response handling in `ImdsManagedIdentitySource` to handle 502 responses to raise `CredentialUnavailableException`. Also we need to investigate if there are any similar HTTP responses we might receive which don't necessarily indicate the IMDS endpoint is available.

**Comment by jacwil** [comment]
All requests destined to Azure Instance Metadata Service must bypass web proxies. Depending on how a web proxy is configured it may return a 404, 502, or other status code.

https://docs.microsoft.com/azure/virtual-machines/windows/instance-metadata-service?tabs=windows#access-azure-instance-metadata-service
