### ISSUE TITLE
RequestId is always null from ComputeManagementClient.VirtualMachines.CreateOrUpdateWithHttpMessagesAsync

### ISSUE THREAD

**Issue by johnbooze** [Azure/azure-sdk-for-net#1837]
computeManagementClient.GenerateClientRequestId = true;
var vmResult = await this.computeManagementClient.VirtualMachines.CreateOrUpdateWithHttpMessagesAsync(resourceGroupName, vmName, vm);
Console.WriteLine("RequestID: " + vmResult.RequestId);  // RequestId is always null

**Comment by adrianhall** [comment]
Is this an issue?  If so, can you please provide the .NET library and version being used?
(Close on Oct 9 if no response)
