### ISSUE TITLE
[BUG REQ] Dependency Version problem

### ISSUE THREAD

**Issue by qingqueenking** [Azure/azure-sdk-for-net#18383]
**Describe the bug**
Please provide the description of issue you're seeing.
version 2.4.1 net461 relies on Microsoft.IdentityModel.Clients.ActiveDirectory 4.3.0 only

**Expected behavior**
What is the expected behavior?
it should also support versions higher than 4.3.0, e.g. 5.2.7

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.
2.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Hi @qingqueenking.   Unfortunately, I'm not able to determine which of the Azure SDK libraries you're using from the context of this issue.   In order for me to help make sure that the right folks see this and can assist, I'll need to ask for a bit more information.   Can you help me understand which library you're discussing that has the dependency on `Microsoft.IdentityModel.Clients.ActiveDirectory`?

**Comment by jsquire** [comment]
Hi @qingqueenking.  Because we don't have enough information to assist, I'm going to close this out.  Please feel free to reopen with additional context if you are still in need of help.
