### ISSUE TITLE
[BUG]Publishing LUIS  app to Prod returns the wrong endpoint url

### ISSUE THREAD

**Issue by nathanaelk** [Azure/azure-sdk-for-net#18384]
**Describe the bug**
Calling the api to publish a LUIS app from both the SDK and the rest api always returns the wrong endpoint.
It returns an endpoint in the format of:
`https://{endpointregion}.api.cognitive.microsoft.com/luis/v2.0/apps/{1}`

**Expected behavior**
`{0}` in this format (`https://{0}.api.cognitive.microsoft.com/luis/v2.0/apps/{1}`) be the prediction resource endpoint

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
`https://westus.api.cognitive.microsoft.com/luis/v2.0/apps/xxxx`
**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Call a POST to `{0}/luis/authoring/v2/apps/{1}/publish`  with `{0}` being the prediction resource and `{1}` the appId and in the JSON body set `isstaging` to false
2. Alternatively use the SDK to call:
```csharp
    var endpointInfo = await myAuthoringClient.Apps.PublishAsync(theappId, new ApplicationPublishObject
    {
        VersionId = appVersion,
        IsStaging = false
    });
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by JimSuplizio** [comment]
Hi @nathanaelk, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
