### ISSUE TITLE
[BUG] Documentation for Upload/UploadAsync Blob methods misrepresent overwrite behavior

### ISSUE THREAD

**Issue by achampto** [Azure/azure-sdk-for-net#18381]
**Describe the bug**
The documentation for Upload/UploadAsync indicates that by default an existing blob would be overwritten. However, if there is an existing blob it will instead throw an exception with the BlobErrorCode of BlobAlreadyExists.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.7.0

Looks like there was a similar bug for DataLake at #13278

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amishra-dev** [comment]
@amnguye can you update the code comment or this bug with the expected behavior

**Comment by j055** [comment]
Some `UploadAsync` / `Upload` method overloads perform silent overwrite and some throw `RequestFailedException: The specified blob already exists` exception.

e.g.

`await blobClient.UploadAsync(stream);` throws `RequestFailedException`

`await blobClient.UploadAsync(stream, httpHeaders: httpHeaders);` silently overwrites existing blob

Worse still, if you want to use `httpHeaders` and receive `BlobAlreadyExists` error code you must do something like the following:

`await blobClient.UploadAsync(stream, httpHeaders: httpHeaders, conditions: new BlobRequestConditions { IfNoneMatch = new ETag("*") });`

Expected outcome is consistent behaviour between overloaded methods with the sensible default behaviour to return  `BlobAlreadyExists` error

**Comment by SeanFeldman** [comment]
> `overwrite` parameter should be available across all overloads

That. And better documentation about how `overwrite` is derived. Right now it looks really confusing to see code with
```c#
private static readonly BlobRequestConditions overwrite = new BlobRequestConditions {IfNoneMatch = new ETag("*")};
```
to pass it into the call
```c#
await blobClient.UploadAsync(data, httpHeaders:headers, conditions:overwrite);
```

**Comment by amnguye** [comment]
Will be taking all into consideration as we update all the Upload Docs to provide more details on the overwrite behavior

**Comment by amnguye** [comment]
Should be resolved by this PR https://github.com/Azure/azure-sdk-for-net/pull/24984
