### ISSUE TITLE
Accessing PropertyName@odata.type on TableEntity?

### ISSUE THREAD

**Issue by kieronlanning** [Azure/azure-sdk-for-net#18386]
Using Azure.Data.Tables, and pulling `TableEntity` objects using `TableClient.QueryAsync <T>`, how can we include the property type information on each entity returned?

The RESTful spec defines the property type returned as `PropertyName@odata.type` - how is that accessible?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @kieronlanning - currently we don't expose the odata annotations in the client model. They are stripped from the result so that only the entity values remain. Is there a scenario where you need this metadata?

**Comment by kieronlanning** [comment]
Hi @christothes - we have a scenario where we run a basic backup of table storage data, and in this instance we're testing the restore.

One of the the primary goals is to also clone environments. For example, after one of our environments was used during a pen test the data now is relatively useless. So to re-seed it we'll take data from another environment and push it into that one.

The process for executing a backup goes something like this:
1. Iterate over the tables in a storage account, processing only the ones that match a regex.
2. Page the data out using the new `Azure.Data.Tables` API, utilising `TableClient.QueryAsync<T>`  to get the data and `TableEntity` to map it.
3. Once we have a page of data, and it's in a `TableEntity` format serialize the entity to another store - in this instance we're doing a basic JSON serialize on the entity itself. 
4. Repeat until we have all of the data.

It's important to note that during this process we do not understand what schema the entities have - this is a generic operation.

One of the entities we return was inserted using a typed class that looks something like this:

```
public class VersionData : ITableEntity
{
    [standard ITableEntity properties]
   
    public int Version { get; set; }
}
```

Checking the record using Storage Explorer shows the entity has a property type of `Int32`:

![image](https://user-images.githubusercontent.com/5364423/106851087-93348480-66ad-11eb-905e-0c31f2f24a22.png)

When this type of entity is serialized during the backup, it comes out with the following payload:

```
{ "PartitionKey": "xxx", "RowKey": "xxx", Version: 166, ... etc }
```

As you can see, the `Version` is correctly written out as a JSON number, but remember that the detail of what type of number has been lost.

On the other side of this operation is the restore, where we iterate over each entity, deserialize each one as a `TableEntity` and attempt to add it back into a table (grouping by `PartitionKey` and then batching).

However, when it's added the property is now a `Int64`:

![image](https://user-images.githubusercontent.com/5364423/106851305-e4dd0f00-66ad-11eb-8e11-0eb68f48f158.png)

When this entity is read as part of a services normal operation, using `TableClient.GetEntityAsync<T>` where `T`` is the previously defined `VersionData` the operation fails with the following error:

```
System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int32'.
   at Azure.Data.Tables.DictionaryTableExtensions.<>c.<.cctor>b__7_14(PropertyInfo property, Object propertyValue, Object result)
   at Azure.Data.Tables.DictionaryTableExtensions.ToTableEntity[T](IDictionary`2 entity, PropertyInfo[] properties)
   at Azure.Data.Tables.TableClient.GetEntityAsync[T](String partitionKey, String rowKey, IEnumerable`1 select, CancellationToken cancellationToken)
```

If we change the `VersionData` `Version` property to `long` - matching the source entities new property type - then this error goes away and we can happily get the entity.

--------------

So to solve this issue, I want to include the type information when I'm serializing this data to ensure that _all_ properties have the correct type when they're being restored in the future.

**Comment by christothes** [comment]
> On the other side of this operation is the restore, where we iterate over each entity, deserialize each one as a `TableEntity` and attempt to add it back into a table (grouping by `PartitionKey` and then batching).
> 
> However, when it's added the property is now a `Int64`:

Could you provide any more detail about the above step?

It is strange that a json number value would end up as an `Int64` once de-serialized to `TableEntity`. For a property value to be treated as `Int64` by the client, it would have to be de-serialized as long. Only in that case would the client convert it to string and add an odata annotation (`"Version@odata.type":"Edm.Int64"`) before serializing it to the service. Without this odata annotation, a string value would be treated as `string` and a number value would be treated as `Int32` ([see this reference](https://docs.microsoft.com/en-us/rest/api/storageservices/payload-format-for-table-service-operations#property-types-in-a-json-feed)).

**Comment by kieronlanning** [comment]
That's what I thought too...

The deserialization is as simple as taking the JSON mentioned above, and using JSON.NET to `JsonConvert.DeserializeObject<TableEntity>(content)`.

That's put in a batch, with other matching partition keys and fired over to table storage.

It's pretty much as simple as that - we don't massage the data at, simply read it, deserialize, group and batch.

**Comment by christothes** [comment]
Would it be possible for you to provide a small code sample with a sample fake entity json payload that demonstrates this behavior?

**Comment by kieronlanning** [comment]
I'll try and knock one up tonight... I'll let you know!

**Comment by kieronlanning** [comment]
@chamons Here's the repo: https://github.com/kieronlanning/azure-ts-json-net-failure

The curious part is coming from JSON to TableEntity, where the value changes from Int32 to Int64. I've labelled everything up.

I'm not sure it's technically a TableEntity related issue, but if I can get ahold of the type information, it would certainly help.

**Comment by christothes** [comment]
Thanks for the repro. This is an [issue](https://stackoverflow.com/questions/8297541/how-do-i-change-the-default-type-for-numeric-deserialization/9444519#9444519) with `Json.Net`, which serializes numbers to `Int64` by default when the model property is `object`. 

Below is a workaround using `System.Text.Json` (the same is possible with Json.Net, if you prefer). The `ObjectToInferredTypesConverter` is just slightly tweaked from the example [here](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0#deserialize-inferred-types-to-object-properties).

```C#
void Main()
{
	string json = @"{""Version"":166}";
	var settings = new JsonSerializerSettings();
	Repro jsonDotNet = JsonConvert.DeserializeObject<Repro>(json);

	var options = new JsonSerializerOptions();
	options.WriteIndented = true;
	options.Converters.Add(new ObjectToInferredTypesConverter());
	Repro systemDotTextDotJson = System.Text.Json.JsonSerializer.Deserialize<Repro>(json, options);
	
	Console.WriteLine($"{jsonDotNet.Version.GetType()}"); // System.Int64
	Console.WriteLine($"{systemDotTextDotJson.Version.GetType()}"); // System.Int32
	
}

// You can define other methods, fields, classes and namespaces here
public class Repro
{
	public object Version { get; set; }
}

public class ObjectToInferredTypesConverter : System.Text.Json.Serialization.JsonConverter<object>
{
	public override object Read(
		ref Utf8JsonReader reader,
		Type typeToConvert,
		JsonSerializerOptions options) => reader.TokenType switch
		{
			JsonTokenType.True => true,
			JsonTokenType.False => false,
			JsonTokenType.String when reader.TryGetInt64(out long l) => l,
			JsonTokenType.Number => reader.GetInt32(),
			JsonTokenType.String when reader.TryGetDateTime(out DateTime datetime) => datetime,
			JsonTokenType.String => reader.GetString(),
			_ => JsonDocument.ParseValue(ref reader).RootElement.Clone()
		};

	public override void Write(
		Utf8JsonWriter writer,
		object objectToWrite,
		JsonSerializerOptions options) =>
		System.Text.Json.JsonSerializer.Serialize(writer, objectToWrite, objectToWrite.GetType(), options);
}
```

**Comment by kieronlanning** [comment]
Crap, sorry @christothes - didn't mean to waste your time with a JSON.NET issue.
