### ISSUE TITLE
No code examples

### ISSUE THREAD

**Issue by ExtraGravy** [Azure/azure-sdk-for-net#18392]
It would be much easier to upgrade to v12 if there were code examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c2c6e27f-6043-7fe6-7413-9a5bf946fe78
* Version Independent ID: e6155477-40f6-9fbb-2f43-6428d4a9e137
* Content: [ShareDirectoryClient.GetFilesAndDirectoriesAsync(String, CancellationToken) Method (Azure.Storage.Files.Shares) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharedirectoryclient.getfilesanddirectoriesasync?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Files.Shares/ShareDirectoryClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.Shares/ShareDirectoryClient.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi, are you asking about samples or examples in general for the entire v12 library or for this specific API?

As for the API linked in your issue, I'm not sure how more clear the documentation can be on how to use the API. Please provide how this API needs more documentation or samples.

A list of samples can be found here:
Migration guide for Blobs from v11 to v12: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md
[Azure.Storage.Blobs](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs)
[Azure.Storage.Files.Shares](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Files.Shares)
[Azure.Storage.Files.DataLake](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Files.DataLake)
[Azure.Storage.Queues](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Queues)

**Comment by ExtraGravy** [comment]
Yes, there are obviously numerous examples for Blobs, but there are not examples for Files.

**Comment by amnguye** [comment]
Hi, in my reply I linked the sample for Azure.Storage.Files.Shares.

Here it is again.
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Files.Shares/samples

**Comment by ExtraGravy** [comment]
Originally I wasn’t looking on GitHub.  I was looking on the standard site for azure documentation, https://docs.microsoft.com/en-us/azure/storage/, which had blob examples but not file examples.  That is where I posted my request for examples, not on GitHub.  You are pointing me at docs within GitHub, which is fine but not the point I was making and not the same as the Quick Start provided for blobs on docs.microsoft.
I was frustrated that there were no file examples there – why is the documentation so fragmented – why can’t there be a link from there to where its squirreled away in GitHub?

**Comment by ExtraGravy** [comment]
BTW – the links to GitHub docs are useful and I appreciate it.  Just leaves me wishing there was a Quick Start for Files like there is for Blobs.
Thanks.

From: Larry Bickel<mailto:t3chnomonk@hotmail.com>
Sent: Thursday, February 11, 2021 5:56 PM
To: Azure/azure-sdk-for-net<mailto:reply@reply.github.com>; Azure/azure-sdk-for-net<mailto:azure-sdk-for-net@noreply.github.com>
Cc: Author<mailto:author@noreply.github.com>
Subject: RE: [Azure/azure-sdk-for-net] No code examples (#18392)


Originally I wasn’t looking on GitHub.  I was looking on the standard site for azure documentation, https://docs.microsoft.com/en-us/azure/storage/, which had blob examples but not file examples.  That is where I posted my request for examples, not on GitHub.  You are pointing me at docs within GitHub, which is fine but not the point I was making and not the same as the Quick Start provided for blobs on docs.microsoft.
I was frustrated that there were no file examples there – why is the documentation so fragmented – why can’t there be a link from there to where its squirreled away in GitHub?

**Comment by amnguye** [comment]
Hi,

Your issue was opened on our github issues page in regardings to queries, bugs and feature requests about the storage SDK not about issues about where documents are located. @CamSoper can you help direct this customer with their issue about the documentation to the correct place? Unfortunately we do not manage the documents they are referring to.

**Comment by seanmcc-msft** [comment]
Please reopen if you have further questions.
