### ISSUE TITLE
WindowsAzure.ConfigurationManager Nuget error installing into Portable Library

### ISSUE THREAD

**Issue by JasonAlexander** [Azure/azure-sdk-for-net#1840]
When installing Azure Service Bus 3.1.4 through Nuget into VS 2015 Portable Library, the SB package installs correctly but the ConfigurationManager package fails. The Portable Library targets Win 8, Win 8 Phone, iOS, & Android.

**Comment by markcowl** [comment]
### Cost: 4

**Comment by kirthik** [comment]
Please update to later version 3.1.7. The CloudConfigurationManager package dependency has been removed.
