### ISSUE TITLE
[BUG] Bloburibuilder does not populate versionid or snapshot

### ISSUE THREAD

**Issue by brensolvexia** [Azure/azure-sdk-for-net#18401]
**Describe the bug**
Providing a url of a blobs version or shapshot, e.g. 
passing url into constructor of bloburibuilder https://storageaccount.blob.core.windows.net/testcontainer/testfile.txt?versionId=2020-11-17T01:12:35.3895766Z

**Expected behavior**
The properties of bloburibuilder, versionid, should be populated with 2020-11-17T01:12:35.3895766Z

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
the property is simply null

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Instantiate bloburibuilder with url https://storageaccount.blob.core.windows.net/testcontainer/testfile.txt?versionId=2020-11-17T01:12:35.3895766Z
2. Look at property versionid

**Environment:**
 - package Azure.Storage.Blobs 12.8.0
 - Windows 10, .Net Core 3.1
 - Visual studio 2017

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by Mohit-Chakraborty** [comment]
@xgithubtriage

**Comment by amnguye** [comment]
Hi, I believe that parameter is case sensitive. If the parameter was "versionid" instead of "versionId" as you have it in your issue, the BlobUriBuilder should be able to parse the value.

What are you doing for snapshot?

**Comment by brensolvexia** [comment]
Then it still looks wrong because https://storageaccount.blob.core.windows.net/testcontainer/testfile.txt?versionId=2020-11-17T01:12:35.3895766Z is as it appears from Azure portal.

Can you confirm from an api perspective what a versioned url would look like?

The snapshot urls actually work though.

**Comment by amishra-dev** [comment]
@amnguye can you check with other SDKs on what they do, portal is generating versionId (https://ashishwithversioning.blob.core.windows.net/test/text.txt?versionId=2021-11-30T20:32:49.6056147Z)

**Comment by amishra-dev** [comment]
@amnguye did you get a chance to check?
