### ISSUE TITLE
[BUG] Microsoft.Azure.Management.ApiManagement UserOperations CreateOrUpdate does not contain notify parameter

### ISSUE THREAD

**Issue by xakpc** [Azure/azure-sdk-for-net#18407]
**Describe the bug**
According to [documentation](https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/user/createorupdate) `ApiManagement.UserOperations.CreateOrUpdate` must contain `notify` parameter which should trigger welcome email.

This parameter is missing in the [latest version of Microsoft.Azure.Management.ApiManagement](https://github.com/Azure/azure-sdk-for-net/blob/e0fd1cd415d8339947b20c3565c7adc7d7f60fbe/sdk/apimanagement/Microsoft.Azure.Management.ApiManagement/src/Generated/UserOperations.cs#L775) package

**Expected behavior**
I expect to be able to pass `notify` parameter to `apiManagement.User.CreateOrUpdateAsync`

**Actual behavior (include Exception or Stack Trace)**
There is no such parameter in `apiManagement.User.CreateOrUpdateAsync`

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Install package Microsoft.Azure.Management.ApiManagement -Version 6.0.0-preview
2. Create ApiManagementClient
3. Check apiManagement.User.CreateOrUpdateAsync

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.ApiManagement -Version 6.0.0-preview
 -  dotnet 
 Version:   5.0.200-preview.20601.7
 Commit:    b3b934bbf2
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 - IDE and version: Visual Studio 16.3

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by allenjzhang** [comment]
@pakrym ,  looks like [notify query parameter](https://github.com/Azure/azure-rest-api-specs/blob/a4cb421282907dd35ce50b6be718371790ab4b68/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2019-12-01/apimusers.json#L229) was not generated on neither [OperationExtension](https://github.com/Azure/azure-sdk-for-net/blob/81ab5df7ef0190a097382c6aeaf0434c271302fb/sdk/apimanagement/Microsoft.Azure.Management.ApiManagement/src/Generated/UserOperationsExtensions.cs#L198) nor [Operation[(https://github.com/Azure/azure-sdk-for-net/blob/81ab5df7ef0190a097382c6aeaf0434c271302fb/sdk/apimanagement/Microsoft.Azure.Management.ApiManagement/src/Generated/UserOperations.cs#L775).  Do we have a bug on track 1 codegen?

**Comment by pakrym** [comment]
I don't think the library was re-generated after https://github.com/Azure/azure-rest-api-specs/pull/10122 went in.

**Comment by allenjzhang** [comment]
@vfedonkin, please regenerate SDK to incorporate new swagger changes. Thx.
