### ISSUE TITLE
[Feature Req][Azure.Extensions.AspNetCore.Configuration.Secrets] Ability to lazily load secrets from Azure KV

### ISSUE THREAD

**Issue by jananiva** [Azure/azure-sdk-for-net#18410]
Our code uses `Azure.Extensions.AspNetCore.Configuration.Secrets` package to load secrets from KV into configuration instance during app startup. Since there is no option but to load all secrets at once from KV, when multiple app instances are trying to connect to KV during startup, KV throttles us.

And during high loads, when we scale up the number of VMs/instances, all of these instances try to come up at the same time and try to read it from KV and KV keeps throttling us.

Service Fabric cluster doesn't take to startup failures pretty well and it keeps aggressively retrying to startup which further worsens the load on KV!

The app does not need 'ALL' the secrets in the keyvault during start-up, it only needs a subset. So, please add the ability to lazily load secrets on demand from KV.

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by heaths** [comment]
Actually, this is an ASP.NET extensions ask with @pakrym owns but I can take a look as well, so adding him as co-assignee.

**Comment by pakrym** [comment]
Unfortunately, the ASP.NET Core Options system doesn't support lazy loading. All configuration sources are enumerated eagerly when on ConfigurationBuilder.Build()

https://github.com/dotnet/runtime/blob/8241168b2d85e8e7ff25fa8984d91fed8da7922a/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationRoot.cs#L35

You can use the https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/KeyVaultSecretManager.cs to only load a subset of secrets by overriding the `Load` method.
