### ISSUE TITLE
[BUG] BlobClient URI encoding unexpected behavior

### ISSUE THREAD

**Issue by cornem** [Azure/azure-sdk-for-net#18417]
**Describe the bug**
When creating a blob in a virtual directory, the `BlobClient.Uri` property encodes the file path. However, when requesting a new instance of `BlobClient` with the URI returned by the first `BlobClient`, the blob actually isn't found. One needs to first decode the URI (e.g. by calling `System.Net.WebUtility.UrlDecode` before using it with another instance of `BlobClient`.

**Expected behavior**
When creating blobs, the service should return URIs that don't need to be manipulated before they can be reused.

**To Reproduce**
1. Create a blob
2. Use the created blob's Uri to get a new blob client reference
3. Try to call operations on this new blob client

```csharp
var container = new BlobContainerClient(connectionString, "my-container");
string destinationPath = "signatures/323ac38d-1bbc-4234-9765-d5cb6157adee.jpg";
var blob = container.GetBlobClient(destinationPath);
await blob.UploadAsync(stream);

string uri = blob.Uri.AbsoluteUri; 
// this value will look like 'https://<endpoint>/my-container/signatures%2F323ac38d-1bbc-4234-9765-d5cb6157adee.jpg

// let's say we store the absolute URI and want to use it again later
var blob1 = container.GetBlobClient(uri);
bool exists1 = await blob1.ExistsAsync(); // returns false

// it does work when we UrlDecode the URI
var blob2 = container.GetBlobClient(WebUtility.UrlDecode(uri));
bool exists2 = await blob2.ExistsAsync(); // returns true
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by shibayan** [comment]
I am facing the same problem: when I generate URLs with SAS, the directory separator is URL-escaped, so I cannot download the file with the intended filename.

**Comment by seanmcc-msft** [comment]
@cornem, this is by design.  `BlobContainerClient.GetBlob()` takes the name of the blob, not the URI.

I recommend this approach instead:

```
BlobContainerClient container = new BlobContainerClient(connectionString, "my-container");
string destinationPath = "signatures/323ac38d-1bbc-4234-9765-d5cb6157adee.jpg";
BlobClient blob = container.GetBlobClient(destinationPath);
await blob.UploadAsync(stream);

// Couple things here.  First, BlobContainerClient.GetBlobClient() takes a blob name, not a URI.
// Second, we don't encode BlobClient.Name, so this works:
BlobClient blob1 = container.GetBlobClient(blob.Name);
bool exists1 = await blob1.ExistsAsync(); 

```

-Sean
