### ISSUE TITLE
[QUERY] Search: Azure.RequestFailedException when trying to Upload or MergeOrUpload

### ISSUE THREAD

**Issue by SebastianAtWork** [Azure/azure-sdk-for-net#18416]
Hi Team,
I´m having a real hard time using the Azure.Search.Documents Package. The Exception I get is: The request is invalid. Details: parameters: A resource without a type name was found, but no expected type was specified. To allow entries without type information, the expected type must also be specified when the model is specified.

Status: 400 (Bad Request)

This is the class that served as the type to produce the FieldMap : 
```csharp
    public class SearchListItem
    {
        [SimpleField(IsKey = true,IsFilterable = true)]
        public string Id { get; set; }
        [SearchableField(IsFilterable = true,IsFacetable = true,IsSortable = true)]
        public string Label { get; set; }
        [SearchableField(IsFilterable = true, IsFacetable = true, IsSortable = true)]
        public string BuildType { get; set; } = String.Empty;
        [SearchableField(IsFilterable = true, IsFacetable = true, IsSortable = true)]
        public string SerialNumber { get; set; } = String.Empty;
        [SearchableField(IsFilterable = true, IsFacetable = true, IsSortable = true)]
        public string OrderNumber { get; set; } = String.Empty;
        [SearchableField(IsFilterable = true, IsFacetable = true, IsSortable = true)]
        public string OrderDescription { get; set; } = String.Empty;
    }
```
This is a snapshot of the Index FieldMap in Azure:
![image](https://user-images.githubusercontent.com/19798013/106848479-5b2f4080-66b1-11eb-82ef-24a8154d61b5.png)
And this is the code that calls the IndexAsync Method:

```csharp
        private async Task Upload(SearchListItem document)
        {
            var uploadToIndex = IndexDocumentsAction.MergeOrUpload(document);
            await _azureSearchConnectionProvider.QueryClient.IndexDocumentsAsync(
                IndexDocumentsBatch.MergeOrUpload(new[] {uploadToIndex}));
        }
```

And, in case it's important, here is the Index Creation:

```csharp
        private void CreateIndex()
        {
            var fieldBuilder = new FieldBuilder();
            var searchFields = fieldBuilder.Build(typeof(SearchListItem));
            var definition = new SearchIndex(_searchSettings.IndexName, searchFields);
            var suggester = new SearchSuggester("sg",
                nameof(SearchListItem.BuildType), nameof(SearchListItem.Label), nameof(SearchListItem.OrderDescription),
                nameof(SearchListItem.OrderNumber), nameof(SearchListItem.SerialNumber));
            definition.Suggesters.Add(suggester);
            SearchIndexClient.CreateOrUpdateIndex(definition);
        }
```

What am I missing here? The Exception, after some googling, sounds like the types don't match but I literally used the same type. I tried Version 11.1 and 11.2.beta2

Also, for some reason, posting the Code here as Code is messing up the formatting?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Can you please provide a stack trace of the exception - at least from Azure.Search.Documents?

A note on optimizations: making every field facetable and sortable will make your index huge and increase costs, and making something like OrderDescription (assuming that's a free-form text box with lots of descriptive data) facetable may not really help. You might find the following links helpful:

* https://docs.microsoft.com/azure/search/search-performance-optimization
* https://docs.microsoft.com/azure/search/search-what-is-an-index

**Comment by seble-nigussie** [comment]
Hi, are there any solutions? I'm getting the same exception with the following settings
![image](https://user-images.githubusercontent.com/93709073/140295424-4cbbadf2-88d4-4533-af03-f1cccb1b9ade.png)
Index model used :
`public class IndexModel
    {
        public string Id { get; set; }
        public string OrganizationId { get; set; }
        public int EntityType { get; set; }
        public int UserType { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string Description { get; set; }

    }`
and the upload code 
`public async Task Index(IndexModel data)
        {
            var actions = new[] { IndexDocumentsAction.Upload(data) };
            var batch = IndexDocumentsBatch.Upload(actions);
            await _searchClient.IndexDocumentsAsync(batch);
        }`

**Comment by Mohit-Chakraborty** [comment]
Hi, can you check [the reply above](https://github.com/Azure/azure-sdk-for-net/issues/18416#issuecomment-773641583) and provide us with a call-stack of the error when using the SDK.

**Comment by seble-nigussie** [comment]
> Hi, can you check [the reply above](https://github.com/Azure/azure-sdk-for-net/issues/18416#issuecomment-773641583) and provide us with a call-stack of the error when using the SDK.

Here is what its throwing. 

Message: 
    Azure.RequestFailedException : The request is invalid. Details: parameters : A resource without a type name was found, but no expected type was specified. To allow entries without type information, the expected type must also be specified when the model is specified.
    
    Status: 400 (Bad Request)
    
    Content:
    {"error":{"code":"","message":"The request is invalid. Details: parameters : A resource without a type name was found, but no expected type was specified. To allow entries without type information, the expected type must also be specified when the model is specified.\r\n"}}
    
    Headers:
    Cache-Control: no-cache
    Pragma: no-cache
    client-request-id: e702640b-77f7-4129-913b-d782e7b42342
    x-ms-client-request-id: e702640b-77f7-4129-913b-d782e7b42342
    request-id: e702640b-77f7-4129-913b-d782e7b42342
    elapsed-time: 103
    OData-Version: 4.0
    Preference-Applied: REDACTED
    Strict-Transport-Security: REDACTED
    Date: Thu, 04 Nov 2021 09:49:21 GMT
    Content-Type: application/json; odata.metadata=none
    Content-Language: REDACTED
    Expires: -1
    Content-Length: 274
    
  Stack Trace: 
    SearchClient.IndexDocumentsInternal[T](IndexDocumentsBatch`1 batch, IndexDocumentsOptions options, Boolean async, CancellationToken cancellationToken)
    SearchClient.IndexDocumentsAsync[T](IndexDocumentsBatch`1 batch, IndexDocumentsOptions options, CancellationToken cancellationToken)

**Comment by seble-nigussie** [comment]
Found the problem. I was using `IndexDocumentsBatch.Upload(actions)` the upload method here instead of create. After changing that it worked. I hope this helps someone.

**Comment by Mohit-Chakraborty** [comment]
Glad you fixed the issue, and thanks for sharing it.
