### ISSUE TITLE
[FEATURE REQ] Allow for accepting fallback KVs in IConfigurationBuilder.AddAzureKeyVault methods

### ISSUE THREAD

**Issue by jananiva** [Azure/azure-sdk-for-net#18411]
**Library:**
Azure.Extensions.AspNetCore.Configuration.Secrets
 
**Is your feature request related to a problem? Please describe.**
Allow for accepting one or more fallback KVs so that if the primary KV is not available, the secrets/certs are fetched from the fallback KVs.

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by heaths** [comment]
Actually, this is an ASP.NET extensions ask with @pakrym owns but I can take a look as well, so adding him as co-assignee.

**Comment by pakrym** [comment]
Unfortunately, the ASP.NET Core Options system doesn't support lazy loading all configuration sources are enumerated eagerly when on ConfigurationBuilder.Build()


https://github.com/dotnet/runtime/blob/8241168b2d85e8e7ff25fa8984d91fed8da7922a/src/libraries/Microsoft.Extensions.Configuration/src/ConfigurationRoot.cs#L35

**Comment by pakrym** [comment]
Wrong issue.

**Comment by heaths** [comment]
@jananiva was this only to mitigate throttling? Did randomizing the retry policy across nodes help with the issue?

@pakrym if someone were to add multiple `SecretClient`s to the configuration now - is that even possible? Seems if it were, would the configuration system automatically move to the next one if a request for a previous provider timed out?

**Comment by pakrym** [comment]
There is no way to add multiple `SecretClients`. There is no fallback feature as of now.

**Comment by jananiva** [comment]
> @jananiva was this only to mitigate throttling? Did randomizing the retry policy across nodes help with the issue?
> 
> @pakrym if someone were to add multiple `SecretClient`s to the configuration now - is that even possible? Seems if it were, would the configuration system automatically move to the next one if a request for a previous provider timed out?

@heaths I've added the retry policy but will have to wait for the next prod release to confirm if it helps! But having the ability to fallback to other KVs helps in general for our service's resiliency (for example, when a geo/region/dc is completely down)

**Comment by heaths** [comment]
Because multiple clients can't be added to the ASP.NET extension, you could currently work around this. We allow deriving clients mainly for testing, but you could actually aggregate. Something like (error handling elided for brevity):
```c#
public class AggregatingSecretClient : SecretClient
{
  private readonly List<SecretClient>_clients;

  public AggregatingSecretClient(IEnumerable<Uri> vaultUris, TokenCredential credential, SecretClientOptions options = default)
  {
    foreach (Uri vaultUri in vaultUris)
    {
      _clients.Add(new SecretClient(vaultUri, credential, options));
    }
  }

  public override Response<KeyVaultSecret> GetSecret(string name, CancellationToken cancellationToken = default) =>
    CallMethodWithFallback((client, token) => client.GetSecret(name, token), cancellationToken);

  private Response<T> CallMethodWithFallback<T>(Func<SecretClient, CancellationTokenSource, T> func, CancellationToken cancellationToken)
  {
    foreach (SecretClient client in _clients)
    {
      try
      {
        using CancellationTokenSource cts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
        cts.CancelAfter(TimeSpan.FromSeconds(30));

        return func(client, cts.Token);
      }
      catch (TaskCancelledException) when (!cancellationToken.IsCancellationRequested)
      {
        // Continue to the next client...
      }
    }

    throw new TaskCancelledException($"No Key Vaults responded in time");
  }
}
```

**Comment by pakrym** [comment]
We are not planning to ship the feature and the workaround was provided.
