### ISSUE TITLE
[QUERY] - Is there an Azure SDK endpoint that returns a VirtualMachineInstanceView object?

### ISSUE THREAD

**Issue by 1RedOne** [Azure/azure-sdk-for-net#18425]
**Query/Question**
Hi!  In looking at the Rest API documentation, I found that this return type has a valuable field to me, namely the OS Profile Type, so I can easily tell if it's a Linux or Windows family VM.  

https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/instanceview

I see that this type does exist in the Fluent SDK models, but I can't determine how to get one from the Fluent SDK.  

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.fluent.models.virtualmachineinstanceview?view=azure-dotnet

I'm retrieving VM info today using this approach, but this gives me a `Microsoft.Azure.Management.Compute.Fluent.VirtualMachineImpl` object type which lacks the useful OSName fields.

```
azure.VirtualMachines.GetByIdAsync(vmArmID).Result;
```

*Is there a way to get a VirtualMachineInstanceView object from the Fluent or ResourceManager SDKs?*

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
Once you have a vm object from Create() or GetById(), this object has an InstanceView property that provides access to the information you are seeking.

```
            var vm1 = azure.VirtualMachines.GetById("VMID");
            Console.WriteLine(vm1.InstanceView.OsName);
            Console.WriteLine(vm1.InstanceView.OsVersion);
            Console.WriteLine(vm1.InstanceView.XXXXX);
            ...
```

**Comment by 1RedOne** [comment]
That's great, thank you Allen!
