### ISSUE TITLE
[BUG] Search: GetIndexAsync fails when azure search profile has weights, but doesn't have a scoring function

### ISSUE THREAD

**Issue by Valdeminas** [Azure/azure-sdk-for-net#18427]
**Describe the bug**
I have a scoring profile setup on my index in Azure.
The scoring profile has weights on two fields, but does not have a scoring function defined.
After upgrade to client 11, SearchIndexClient.GetIndexAsync throws error: Unknown scoring function aggregation value. (Parameter 'value')

**Expected behavior**
Index is loaded without errors.

**Actual behavior (include Exception or Stack Trace)**
SearchIndexClient.GetIndexAsync throws error: Unknown scoring function aggregation value. (Parameter 'value')

**To Reproduce**
Setup an index in azure cloud.
Set scoring profile to use weight, but to not use any scoring function.
SearchIndexClient.GetIndexAsync on that index.

**Environment:**
 - Azure.Search.Documents v11
 - .NET SDK 5.0.200-preview.20614.14
 - IDE and version : Visual Studio Version 16.9.0 Preview 3.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AlexGhiondea** [comment]
@Mohit-Chakraborty can you take a look?

/cc @brjohnstmsft

**Comment by brjohnstmsft** [comment]
@Mohit-Chakraborty This sounds like an issue deserializing the response on the client. Are you able to repro this with SDK tests?

**Comment by Mohit-Chakraborty** [comment]
@Valdeminas - this issue has been fixed a while back.
Please try any [release](https://www.nuget.org/packages/Azure.Search.Documents/) later than 11.2.0-beta.2, preferably the latest GA - 11.3.0 and let me know if the issue still occurs.

**Comment by Valdeminas** [comment]
Thanks!
