### ISSUE TITLE
[BUG] TableTransactionalBatch.UpdateEntity does not merge entities

### ISSUE THREAD

**Issue by dzendras** [Azure/azure-sdk-for-net#18433]
**Describe the bug**
You cannot merge entities inside a transactional batch. The TableUpdateMode argument is ignored and entities are always overwritten.
Given an entity in TS with property A, when attempting to merge property B into it, then property A is erased and the entity only contains property B.

**Expected behavior**
The entity in TS contains 2 properties: A & B.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

The entity in TS contains only the property B;

PS. Property B can be added to the entity without erasing property A, only when using the table client directly (TableClient.UpdateEntity), bypassing batching.

**To Reproduce**

```
var client = new TableClient("<connectionString>", "tableName");
await client.AddEntityAsync(new TableEntity
{
	PartitionKey = "PK",
	RowKey = "RK",
	["A"] = "valueA"
});
var batch = client.CreateTransactionalBatch("PK");
var entity = new TableEntity
{
	PartitionKey = "PK",
	RowKey = "RK",
	["B"] = "valueB"
};
batch.UpdateEntity(entity, ETag.All, TableUpdateMode.Merge);
await batch.SubmitBatchAsync();

var entityAfterMerge = (await client.GetEntityAsync<TableEntity>("PK", "RK")).Value;
entityAfterMerge.ContainsKey("A") == false; //should return true!
```

**Environment:**
Azure.Data.Tables 3.0.0-beta5
Windows 10 Pro
Tried against an Azure-hosted real TableStorage as well as against Windows Azure Storage Emulator 5.10.0.0
.NET Core 3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
@dzendras Thank you! I have a PR to address this.

**Comment by dzendras** [comment]
Thanks to everyone involved! Is beta-6 approaching any time soon?

**Comment by christothes** [comment]
@dzendras it should be released next month.
