### ISSUE TITLE
[BUG] CosmosDB ExtendedResourceProperties is not referenced in the code

### ISSUE THREAD

**Issue by MehaKaushik** [Azure/azure-sdk-for-net#18442]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/cosmosdb/Microsoft.Azure.Management.CosmosDB/src/Generated/Models/ExtendedResourceProperties.cs

The data model ExtendedResourceProperties should not exist as a separate object. It is not used anywhere.

**Comment by jsquire** [comment]
Closing this out; the package referenced by this issue has been deprecated and is superseded by `Azure.ResourceManager.CosmosDB`.
