### ISSUE TITLE
There is no client for the RateCard REST API

### ISSUE THREAD

**Issue by ericame** [Azure/azure-sdk-for-net#1846]
While this project includes a client for the [Usage REST API](https://msdn.microsoft.com/library/azure/1ea5b323-54bb-423d-916f-190de96c6a3c), it does not include a client for the complimentary [RateCard REST API](https://msdn.microsoft.com/library/azure/1ea5b323-54bb-423d-916f-190de96c6a3c). This makes it impossible to use the usage client for cost analysis without manually implementing your own RateCard client.

Can we provide a client for the RateCard REST API?

**Comment by markcowl** [comment]
@Matt-Westphal Can you please assign this appropriately on the billing team

**Comment by takekazuomi** [comment]
It has already been over 9 months.
When is RATE AIP client planned for implementation?

**Comment by masters3d** [comment]
@markcowl any updates on this? Is there an alternative that API that we should be using?

**Comment by alexeldeib** [comment]
@markcowl @Matt-Westphal Is there any progress here? We are looking for the same functionality to use internally.

**Comment by AlexGhiondea** [comment]
@Matt-Westphal ping.

**Comment by allenjzhang** [comment]
This has been an old thread. From what I can gather, that API is EOL. I do see new APIs under [Consumption](https://docs.microsoft.com/en-us/rest/api/consumption/pricesheet). You can try out the SDK [here](https://www.nuget.org/packages/Microsoft.Azure.Management.Consumption/).
