### ISSUE TITLE
Title of the article refers to latest version but install section doesn't

### ISSUE THREAD

**Issue by vnbaaij** [Azure/azure-sdk-for-net#18471]
The title of the article refers to the latest available version (3.0.0-beta5) but the 'Install the package' section refers to older version 3.0.0-beta3

`dotnet add package Azure.Data.Tables --version 3.0.0-beta.3`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7139f609-fc7c-361d-ab81-bd8c15be23c4
* Version Independent ID: 5a22db59-9012-23a0-5139-00ef98214928
* Content: [Azure Tables client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/Data.Tables-readme-pre#contributing)
* Content Source: [api/overview/azure/data.tables-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/data.tables-readme-pre.md)
* Service: **tables**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
