### ISSUE TITLE
[ACR] Ensure scope is correctly retrieved from Www-Authenticate header in challenge response

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#18476]
This was originally missing from the Track 1 library.  See https://github.com/Azure/azure-sdk-for-net/pull/17195 for details.

**Comment by annelo-msft** [comment]
@jsquire I'd like to keep this issue open until I have a chance to resolve it - is there a reason the bot flagged this as a PR?

**Comment by jsquire** [comment]
Yes; the bot incorrectly caught issues in the stale PR rule.  This shouldn't have been flagged.   Apologies for the confusion.

**Comment by pallavit** [comment]
@annelo-msft do you want to still keep this active?
