### ISSUE TITLE
Add method overloads with specific options instead of generic options type

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#18482]
Because of the addition of `Actions`, there are new `xxOption` types that we should also use in the non LRO endpoints.

Similar to what Java is doing here => https://github.com/Azure/azure-sdk-for-java/pull/18984/files#r571145846
.NET can use the approach we did for AnalyzeSentiment on how to "hide" the old method from the user in order to expose the new ones

Endpoints affected:
- [ ] `ExtractKeyPhrases`
- [x] `RecognizeEntities`
- [x] `RecognizeLinkedEntities`
* Note that RecognizePiiEntities already uses `RecognizePiiEntitiesOptions`

**Comment by heaths** [comment]
I can't find anything related to an `EntityLinking` class or the like, though I do see a `ExtractKeyPhraseOptions` that's not used as a parameter type currently - nor in Java, comparatively.

**Comment by heaths** [comment]
Per offline discussion, "EntityLinking" was added in error, but we should also do this for `ExtractKeyPhrases` (but don't need to for `DetectLanguages`). I've updated the description accordingly.
