### ISSUE TITLE
[QUERY] Replacement for IRetryPolicy in V12 of Azure Blob Storage SDK

### ISSUE THREAD

**Issue by asgoe** [Azure/azure-sdk-for-net#18489]
**Query/Question**
How can we help?
We are migrating from V11 to V12 SDK of Azure Storage. In V11 we could implement the IRetryPolicy interface which allowed us to log information whenever retry happened by using the ShouldRetry method (see code below). We were able to set the RetryPolicy object of BlobRequestOptions. How do we do the same in V12 SDK? I do not see any such option which allows us to log information whenever a retry happens for blob operations.  

```
  //Existing V11 code
    internal class BlobStorageRetryPolicy : IRetryPolicy
    {        
        public string Operation { get; }

        public IRetryPolicy InnerPolicy { get; }

        public StorageContext LoggerContext { get; }        

        public BlobStorageRetryPolicy(StorageContext context, string operation)
        {
            this.LoggerContext = context;
            this.Operation = operation;
            this.InnerPolicy = new ExponentialRetry();            
        }

        IRetryPolicy IRetryPolicy.CreateInstance()
        {
            return new BlobStorageRetryPolicy(LoggerContext, Operation);
        }

        bool IRetryPolicy.ShouldRetry(int currentRetryCount, int statusCode, Exception lastException, out TimeSpan retryInterval, OperationContext operationContext)
        {
            var lastResult = operationContext?.LastResult;            
            if (lastResult != null)
            {
                var lastDuration = (lastResult.EndTime - lastResult.StartTime).Duration();
                Logger.LogBlobStorageTransientRetryErrorEvent(
                    loggerContext: LoggerContext,                    
                    errorCode: statusCode,
                    operation: Operation,
                    attemptedDurationInMs: (long)lastDuration.TotalMilliseconds,
                    ex: lastResult.Exception
                );
            }
            
            var p = InnerPolicy.ShouldRetry(currentRetryCount, statusCode, lastException, out retryInterval, operationContext);
            if (this.LoggerContext is InternalStorageContext internalCxt)
            {
                internalCxt.LatencyProfiler.AddCheckpoint($"Retry count:{currentRetryCount} with retryInterval:{retryInterval} for operation:{Operation}, ClientRequestId:{operationContext.ClientRequestID}");
            }            

            return p;
        }
    }
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.7.0, Azure Identity 1.3.0, Azure Core 1.6.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Framework 4.7
 - IDE and version : Visual Studio 16.5.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by asgoe** [comment]
Can someone respond to this please?

**Comment by amnguye** [comment]
Hi, 

To alter the retry policy please see https://github.com/Azure/azure-sdk-for-net/issues/16980.

In regards to logging every time a retry occurs, I will need to get back to this thread, logging most likely can be enabled in the Azure.Core Diagnostics or Logger.

**Comment by asgoe** [comment]
Thanks for the link for setting the retry policy. I have that working already. My main concern is logging when retry happens, so that we do not have to look at storage logs to verify if retry is the reason for higher latency on a certain operation.

**Comment by kasobol-msft** [comment]
This question is about generic retry/diagnostic. @pakrym

**Comment by pakrym** [comment]
You can use a custom logging callback:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#custom-logging-callback

and filter using the event name `e.EventName == "RequestRetrying"` (https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Diagnostics/AzureCoreEventSource.cs#L121)

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
