### ISSUE TITLE
[BUG] ManagedServiceIdentityClient fails to create due to a wrong api version

### ISSUE THREAD

**Issue by kceiw** [Azure/azure-sdk-for-net#18506]
**Describe the bug**
When I call ManagedServiceIdentityClient.UserAssignedIdentities.CreateOrUpdateAsync(), I get an exception saying that the api version is invalid.

See the snippet and the exception in the screenshot.
![image](https://user-images.githubusercontent.com/1449194/107103360-3e3e5e80-67d2-11eb-8b56-d5654645949f.png)

**Expected behavior**
Create the user assigned identity successfully.

**Actual behavior (include Exception or Stack Trace)**
And exception occurs saying that the api version is invalid.

**To Reproduce**
See the attached screenshot. It's just a simple call to ManagedServiceIdentityClient.UserAssignedIdentities.CreateOrUpdateAsync()

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] Microsoft.Azure.Management.ManagedServiceIdentity 1.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 It's debugging from Visual Studio 16.9. It's a aspnet.core 3.1 project.

❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.20614.14
 Commit:    863605c8c3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20614.14\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.405 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 - IDE and version : [e.g. Visual Studio 16.3]
 
![image](https://user-images.githubusercontent.com/1449194/107103482-a3924f80-67d2-11eb-8671-0e739ba070ee.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
Thank you. I am engaging the doc team to identify the fix.

**Comment by allenjzhang** [comment]
Assigning to the service team. 

The .NET SDK version 2018-11-30 aligns with [published REST API spec](azure-rest-api-specs/ManagedIdentity.json at master · Azure/azure-rest-api-specs (github.com)). Please verify that the service side still supports this API-version. If not, please update the REST API spec and republish .NET SDK.

**Comment by kceiw** [comment]
What's the resolution of this bug?

**Comment by ArthurMa1978** [comment]
@fengzhou-msft  please help to check with service team if this issue has been addressed

**Comment by live1206** [comment]
This has been covered in [UserAssignedIdentityOperationTests](https://github.com/Azure/azure-sdk-for-net/blob/0b1c440bdaae30f8bcd69929ed33c3822cda9227/sdk/managedserviceidentity/Azure.ResourceManager.ManagedServiceIdentities/tests/Scenario/UserAssignedIdentityOperationTests.cs#LL22C18-L22C37), it is working fine now.
