### ISSUE TITLE
[QUERY] Service Bus: SendVia and Deduplication

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-sdk-for-net#18513]
Hi

I haven't been able to find any information in the documentation about how deduplication works when a queue is used as a transfer entity.

Say I have a queue "Queue A" with deduplication enabled with a window of 2 minutes, and I send a message to that queue. Directly after I send a message to another queue via "Queue A". Will the deduplication system for "Queue A" look at the message id of that message as well and potentially filter it out? Or will it bypass the deduplication system for "Queue A" completely?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@johnknoop it should bypass the dedup system and go through Queue A onto the actual destination.

Are you seeing a different behavior?

**Comment by johnknoop** [comment]
Hi @axisc 

Thanks! No I'm not seeing a different behaviour, but I just wanted to make sure :)
