### ISSUE TITLE
[Perf] Perf Framework occasionally fails to compute average

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#18510]
One time, the perf framework failed to compute the average throughput:

```
[02:14:00.445] === Test ===
[02:14:00.445] Current          Total           Average
[02:14:01.448] 8475             8475            NaN
[02:14:02.452] 8860             17335           NaN
[02:14:03.460] 9745             27080           NaN
[02:14:04.468] 9411             36491           NaN
[02:14:05.476] 9532             46023           NaN
[02:14:06.478] 9010             55033           NaN
[02:14:07.484] 9122             64155           NaN
[02:14:08.488] 9514             73669           NaN
[02:14:09.500] 9561             83230           NaN
[02:14:10.502] 9068             92298           NaN
[02:14:10.508] 0                92298           NaN
```

**Comment by vhvb1989** [comment]
I have seen this for C++ just or the first row from the print thread.  
My guess is that we could be trying to read from one of the results array while its been updated.

How important is this? Wouldn't it be OK if the final result row provides the avg ?

**Comment by mikeharder** [comment]
The question is what should the perf framework do if one of the parallel work streams has never completed a single operation.  For context, here's how the perf framework works at a high level.

Say parallel=32.  The perf framework creates 32 parallel work streams (async tasks or threads), and for each work stream it tracks the number of completed operations and the time of the last computed operation.  The time is necessary to correctly compute the average operations/second across all the work streams, since each work stream finishes at a slightly different time.

Now say one of the work streams gets stuck on its first request, so it has completed zero requests and the "last completion time" is undefined.  What is the average operations/second for this work stream?

Strictly speaking it is undefined, since the numerator is zero and the denominator is undefined.  We could choose to keep it this way in the perf framework, since this is usually a sign something is wrong with your test or config (say parallel is too high).  It's best to ensure each work stream has completed one operation.

Alternatively, we could count the average operations/second as `0`.  This slightly undercounts since the work stream has likely done some work already, but it has the advantage of ensuring there is always a valid "average throughput" even if one of the work streams got stuck on it's first request.

I prefer the "count as 0" approach since I think it more closely fits the sprit of the perf framework, which is to calculate the performance of the work that **was** completed, and ignore any pending work that was cancelled when the test completion timer fired.

**Comment by vhvb1989** [comment]
> What is the average operations/second for this work stream?

I though we only provide the entire `all threads` avg result. Can we show the per-thread avg?  There are 2 places where we need to calculate (make the division) and print the avg. The first place in from the progress reporter, and the other place is once test duration is reached and the test results are printed.  

In both cases, the displayed avg is the avg of the all avgs from each thread.  There is a zip() operation to get each thread avg and produce the total avg right?

Then, even if there is one or two threads that got stock and did not complete not even one operation, it would just impact the total avg but, how do I noticed there was a slow or dead thread in there?

I might be missing something, but, what I meant is:  if we just don't consider the results from the array where operations count is zero for the avg results, (update the Zip method with a condition to check operation count > 0), wouldn't that be just enough ?

**Comment by mikeharder** [comment]
@vhvb1989: I understand what you are suggesting now, and I updated #18512.  I agree this is a cleaner way to fix this.

I created an issue to add an option to display the per-parallel data:

https://github.com/Azure/azure-sdk-for-net/issues/18614
