### ISSUE TITLE
[Text Analytics] Health Care is not support on China cloud and US GOV

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-net#18519]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.
All tests about health care failed in china cloud and US GOV. The error message is as follow:

Content:
{"error":{"code":"InvalidRequest","message":"Invalid request has been sent.", "innererror":{"code" : "UnsupportedFeature", "message":"Feature is not supported"}}}

Based on https://docs.microsoft.com/en-us/azure/cognitive-services/text-analytics/how-tos/text-analytics-for-health?tabs=ner#supported-languages-and-regions,
Health Care is currently only available on Azure public cloud in following regions: West US 2, East US 2, Central US, North Europe and West Europe.
AZURE_AUTHORITY_HOST setting:
USGOV : https://login.microsoftonline.us/
China: https://login.microsoftonline.us/
@jongio @danieljurek @benbp

**Comment by jsquire** [comment]
@maririos:  Do you mind offering any thoughts that you have?

**Comment by maririos** [comment]
The healthcare feature is in private preview so it is restricted. This won't change at least for the upcoming 2 months.
@Luyunmt  or @benbp  Is there a way to configure which test run where? or to exclude them from a particular run?

FYI @suhas92

**Comment by jongio** [comment]
@Luyunmt - Can you please give examples of how this is achieved in the sdk with other cloud endpoints?

**Comment by Luyunmt** [comment]
@jongio Example in This Link https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/tests/RecognizeHealthcareEntitiesTests.cs#L53 can repro this issue

**Comment by maririos** [comment]
@Luyunmt and @jongio this is expected to fail. The healthcare feature is in private preview so it is restricted. This won't change at least for the upcoming 2 months. Even then I am not sure it will be available in the other clouds.
@Luyunmt or @benbp Is there a way to configure which test run where? or to exclude them from a particular run?
if not, the recommendation will be to not run TA test in China or USGOV clouds

**Comment by benbp** [comment]
@maririos Seems like we should exclude TA from sovereign clouds for now, which is the default behavior. There is not currently a way to filter by tests without making some test code changes. I'd say we should close this issue for now and re-visit it when the feature is out of public preview, or test filter support is added, whichever comes first.

**Comment by maririos** [comment]
Thanks @benbp . I agree
