### ISSUE TITLE
"Explore the client APIs" link is not working

### ISSUE THREAD

**Issue by hmrc87** [Azure/azure-sdk-for-net#18526]
Hi the link EXPLORE THE CLIENT API points to 
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/servicebus/client

but probably should point to:

https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus?view=azure-dotnet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56e82a9b-4ee7-a093-4e13-635551f3c8de
* Version Independent ID: 666177cc-1304-4380-bf6b-6a773810b902
* Content: [Azure Service Bus libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-bus?view=azure-dotnet)
* Content Source: [api/overview/azure/service-bus.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/service-bus.md)
* Service: **service-bus-messaging**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Hi @hmrc87.  Thank you for your feedback;  we'll get that fixed up.

**Comment by jsquire** [comment]
Fixed by [#1793](https://github.com/Azure/azure-docs-sdk-dotnet/pull/1793)
