### ISSUE TITLE
[Form Recognizer] Storage Account was not created in China and Preview

### ISSUE THREAD

**Issue by Luyunmt** [Azure/azure-sdk-for-net#18522]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.
Deploying failed in china cloud and Preview. The error message is as follow:
Resource group 'TrainingData' could not be found.
The Resource 'Microsoft.Storage/storageAccounts/azuresdktrainingdata' under resource group 'TrainingData' was not found.

![image](https://user-images.githubusercontent.com/53427149/107197943-83130100-6a2f-11eb-893b-84f9409b9fca.png)
Now Form Recognizer Tests use the storage account created manually in advance. But in Preview and China Subscription it wasn't created leads to deploy failed.
@jongio @danieljurek @benbp

**Comment by benbp** [comment]
@maririos I have access to these clouds and can help you initialize resources in there if needed.

**Comment by maririos** [comment]
That will be great @benbp ! I am not sure what the best way to do it is. the idea will be to replicate the folders and files content we have in `TrainingData`.

**Comment by maririos** [comment]
@benbp  looks like this is a change we will need for all of our libraries so each language can point their tests.
@witemple-msft   had the same issue in JS https://github.com/Azure/azure-sdk-for-js/issues/10086 
@danieljurek

**Comment by maririos** [comment]
This has been fixed thanks to @benbp . equivalent storage accounts and blobs have been created in each cloud. Same name is used so pipelines should work.
Test for .NET is here => https://dev.azure.com/azure-sdk/internal/_build/results?buildId=742811&view=results

The errors are unrelated to the storage account creation.

Thanks a ton Ben!

**Comment by benbp** [comment]
@maririos are the training data resources checked in? I'm thinking we may want to introduce some concept of pre-requisite resources (i.e. those that can't just be declared in an ARM template) to eliminate this issue in the future.

For posterity, here's what I did to set up the resources:
```
mkdir blob

# from public subscription
az storage blob download-batch -s trainingdata --account-name azuresdktrainingdata -d ./blob

# in gov, china subscriptions
az group create -n TrainingData -l <sovereign cloud location>
az storage account create -n azuresdktrainingdata -g TrainingData
az storage container create --account-name azuresdktrainingdata -n trainingdata
az storage blob upload-batch -d trainingdata --account-name azuresdktrainingdata -s ./blob
```

**Comment by maririos** [comment]
>@maririos are the training data resources checked in?

No, not all of them. We avoided checking in all the files because of the amount, and the specifics of it. It could cause for one language to have a different version or a different file and when looking at error behaviors (which we constantly do) increase the investigation complexity.
