### ISSUE TITLE
Is ServiceRuntime available in any official nuget package?

### ISSUE THREAD

**Issue by am11** [Azure/azure-sdk-for-net#1852]
We are using kudu to auto deploy DNX application. In kudu environment, ServiceRuntime v2.8 is not available out of the box (GAC, Program Files etc.). 

<kbd>https://www.nuget.org/profiles/azure-sdk</kbd> lists several packages for SDK assemblies. I could not find one for ServiceRuntime. Is it (or would it be) available?

Therefore, we have added a `wrap` project for the DNX app which [bin-wraps local copy](https://github.com/aspnet/Home/wiki/Project.json-file#bin-syntax-wrapping-a-dll) of ServiceRuntime assembly (everything dotnet is a nuget package these days). Given this situation, we are considering three options:

* Checkin the assembly in our source tree so project.json of wrapper project picks up.
* Use unofficial service runtime https://www.nuget.org/packages/Unofficial.Microsoft.WindowsAzure.ServiceRuntime/.
* Upload local assembly to kudu's GAC.

**Comment by markcowl** [comment]
@am11 Unfortunately, this repo does not contain the .net service runtime, so we cannot service this request.  Please place the request on the microsoft azure forums: https://azure.microsoft.com/en-us/support/forums/

**Comment by am11** [comment]
Thanks for the link @markcowl. I was busy working on other projects. I have opened a discussion topic over at Azure Forums. Here is the link (for back-reference purpose):
https://social.msdn.microsoft.com/Forums/azure/en-US/73e39964-a9c3-4fbd-974f-0d374bf23d40/need-the-official-nuget-package-for-serviceruntime.
