### ISSUE TITLE
[Design Discussion] Should the Event Processors Eagerly Validate Connections at Startup

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#18552]
# Summary

When the `EventProcessorClient` and `EventProcessor<TPartition>` are constructed, they perform basic validation on their configuration, ensuring that any connection string is well-formed and that any necessary configuration items are populated.   However, this does not prove that the connection information provided is valid according to the Event Hubs service nor that the storage client is able to communicate with the storage service.  

Validation on the connection to the Event Hubs and storage services are performed lazily during background processing when service operations are necessary.  Any failures during this time are surfaced to the error handler and the processor will continue to try to recover and keep processing.  In some cases, this can be helpful - such as when a key or token is rolled and the new credentials haven't fully propagated.  

Many times however, the connection information is incorrect and the processor will be unable to recover.  In this scenario, the result of this behavior is that the processor reports that it is running but will never actually be able to perform work, forcing applications to detect this scenario using the error handler without any guarantee of determinism round the timing of when it will occur.

# Scope of Discussion

- Should event processors attempt to validate the ability to connect to the Event Hubs and storage services as part of the start-up operation, failing if unsuccessful?

- Should event processors attempt to validate permissions by performing a service operation for the Event Hubs and storage services as part of the start-up operation, failing if unsuccessful?

- Should the behavior be optional and allow callers to opt-in when configuring the event processor?

# Considerations

- Because network connections would need to be established and, potentially, service operations take place, validation would have a non-trivial impact on startup time for processors.

- It isn't possible for the processor to intelligently and accurately detect when a connection or authorization issue may be transient; validation fail on potentially transient issues, preventing the processor from starting and forcing application logic to assume responsibility for recovery.

- Because most storage providers do not establish a persistent connection, the overhead of validating the connection would not result in more efficient operation downstream; the Event Hubs connection is persistent and establishing it during start-up would replace the need to do so later.

- Operations performed during startup would be throw-away and would not provide any downstream benefits.

**Comment by jsquire** [comment]
//fyi: @pakrym

**Comment by pakrym** [comment]
I think this makes a lot of sense. Throwing from StartAsync if we can't even enumerate partitions to process would make diagnosing issues easier for customers. We can also eagerly enumerate ownership to see if the checkpoint storage is online.

**Comment by srnagar** [comment]
I am in favor of eagerly validating too. 

However, there are some things we need to consider:

- If a custom checkpointstore is provided by the user, how do we identify a transient error vs a non-transient error? This is difficult even for Storage and Event Hubs too but we can identify most (if not all) transient errors.
- Enumerating ownership validates read permissions to checkpointstore, but this will not validate write access. So, do we then create a dummy "ownership" entry to ensure we have both permissions?
- Doing the initial validation doesn't ensure there will be no issues later. For e.g. storage container is deleted after the processor starts up. So, the user will still have to rely on the errorHandler to detect such issues.
- The connection used to validate EH will not likely be reused as each partition will require a new connection anyway.

For Java, when do we do this validation?
- In buildProcessorClient() method - do we need async build method?
- In `start()` method - do we need async method - `startAsync()`?

**Comment by jsquire** [comment]
Srikanta raises some interesting considerations.    I think we need to set some context for what we could do:

- Validation is a convenience function that offers a best-effort attempt; it is not an iron-clad guarantee.
- Validation is point-in-time at startup; we can't guarantee the state will remain valid for the entire duration that the processor is run.
- Validation is meant to detect obvious cases and scenarios like "we used the wrong connection string" - it cannot account for custom types or non-obvious errors.
- Validation is permissive; if it cannot definitively prove an unrecoverable scenario, then the processor will assume normal operation and use the error handler.

> Enumerating ownership validates read permissions to checkpointstore, but this will not validate write access. So, do we then create a dummy "ownership" entry to ensure we have both permissions?

I'd vote yes;  we should create some form of dummy record and, if possible, remove it.    .NET is unique in this regard, since we're accepting a raw client from the Storage SDK, so we have access to more than just the contract for checkpoint/ownership.    I suspect it'll be a bit more constrained in the other languages.

**Comment by jsquire** [comment]
We appear to have consensus here that validation is desired, should be considered best-effort, and is a point-in-time check.  The form that this takes and the validations will differ a bit by language due to the design of the processor.   

I'm promoting this to an active work item and tentatively scheduling for April.    _(see: #19301)_

**Comment by jsquire** [comment]
Going to close this out as the discussion has run its course and the feature has been added to the .NET processors.
