### ISSUE TITLE
[Flaky Test] AddsMoreDelay

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#18570]
```

Error message
Expected a delay between 148ms and 500ms, not 728
Expected: True
But was:  False


Stack trace
   at Azure.Search.Documents.Tests.ManualRetryDelayTests.AddsMoreDelay() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\ManualRetryDelayTests.cs:line 52
```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=726220&view=ms.vss-test-web.build-test-results-tab&runId=16543174&resultId=110041&paneView=debug

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=730848&view=ms.vss-test-web.build-test-results-tab&runId=16605492&resultId=109575&paneView=debug

**Comment by JoshLove-msft** [comment]
Not observed for a while - closing.
