### ISSUE TITLE
Clarify ScheduledEnqueueTime

### ISSUE THREAD

**Issue by jaganth** [Azure/azure-sdk-for-net#18588]
Message enqueuing time does not mean that the message will be sent at the same time. It will get enqueued, but the actual sending time depends on the queue's workload and its state.

change above to 

ScheduledEnqueueTime is the time after which a message is activated. The actual time the messages becomes active depends on the queue's workload and its state.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47f3ba00-15b2-f56d-2420-dfd5dec94147
* Version Independent ID: 32340b9d-e5e0-052b-10c8-d4fc4d68f4df
* Content: [ServiceBusMessage.ScheduledEnqueueTime Property (Azure.Messaging.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.scheduledenqueuetime?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.ServiceBus/ServiceBusMessage.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus/ServiceBusMessage.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by FredrikDahlberg** [comment]
Please clarify what this actually does. What happens between the time you call SendAsync on the client and the ScheduledEnqueueTime? Where is the message?

Is this the same as the InitialVisibilityDelay on storage queues but with a fixed DateTime instead of a TimeSpan?

**Comment by jsquire** [comment]
Closed via #37861
