### ISSUE TITLE
[BUG] Title is incorrect "Azure SDK for NET APIs" and inconsistent with official branding

### ISSUE THREAD

**Issue by IEvangelist** [Azure/azure-sdk-for-net#18596]
**Describe the bug**
On the https://azure.github.io/azure-sdk-for-net/ site, the title and top-level breadcrumb are incorrectly named. Instead of "Azure SDK for NET APIs", is should read "Azure SDK for .NET APIs". This is very important for our consistency in branding .NET. I'm assuming that this issue is somewhat related to this [docfx generation script here](https://github.com/Azure/azure-sdk-for-net/blob/master/eng/common/docgeneration/Generate-DocIndex.ps1#L161).

**Expected behavior**
The site title and breadcrumb should be "Azure SDK for .NET APIs"

**Actual behavior (include Exception or Stack Trace)**
The site title and breadcrumb actually say "Azure SDK for NET APIs"

**To Reproduce**

1.Visit https://azure.github.io/azure-sdk-for-net/ and observe

![image](https://user-images.githubusercontent.com/7679720/107386496-86eb6580-6ab9-11eb-9895-c0cafc94c4d3.png)

**Comment by jsquire** [comment]
Hi @IEvangelist.  Thanks for bringing this to our attention.   I've tagged and routed to the person best able to address this.

**Comment by sima-zhu** [comment]
Here is the PR for fix.
https://github.com/Azure/azure-sdk-for-net/pull/18623

**Comment by sima-zhu** [comment]
Issue got fixed.
https://azure.github.io/azure-sdk-for-net/

Thanks for reporting the issue. Closed the issue for now. Feel free to reopen if anything unaddressed.
