### ISSUE TITLE
Typo in property name

### ISSUE THREAD

**Issue by JeffreyArt1** [Azure/azure-sdk-for-net#18598]
The documentation mention a "Size" property, when really is "top"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 66f81756-d055-b61e-8b71-c5cb0537ad0f
* Version Independent ID: 3a173f05-bcf6-df16-6f0e-572a11edf1d0
* Content: [SearchOptions Class (Azure.Search.Documents) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.searchoptions?view=azure-dotnet)
* Content Source: [xml/Azure.Search.Documents/SearchOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Search.Documents/SearchOptions.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Mohit-Chakraborty** [comment]
Hi,
  The documentation focuses on the Client API types. [Azure.Search.Documents.SearchOptions.Size](https://github.com/Azure/azure-sdk-for-net/blob/30a070e8932b0c8151a4d773226b274e5ec39aa2/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L111) is the public property that users of the Client SDK reference in their code.

The property maps to 'top' for the underlying REST API calls, but that is not documented. We feel that these lower-level translations should be transparent and adding them to the documentation will not add value.
