### ISSUE TITLE
How to use storage client as check point store for Custom processor

### ISSUE THREAD

**Issue by snober** [Azure/azure-sdk-for-net#18593]
**Query/Question**
We are creating a [custom event processor](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/design/event-processor%7BT%7D-proposal.md), in which how can we use storage client (azure storage blob container) as a checkpoint store. How to use BlobsCheckpointStore(StorageManager) and its dependent classes / are there any suggestions?

**Environment:**
 - Azure.Messaging.EventHubs : 5.2.0
 - Azure.Messaging.EventHubs.Processor : 5.2.0
 - .Net Core 3.1

**Comment by jsquire** [comment]
Hi @snober.  Thank you for reaching out and we regret that you're experiencing difficulty.  The `BlobCheckpointStore` class is an internal implementation and not exposed as a public type.  At this point, it isn't available for authors of a custom processor to use in a way that is supported.  

We are in the process of building a sample that demonstrates the basics of constructing a custom processor and using Blob storage for persistence, which should be available in a few days.   If you'd like to see the work in progress, it is available in draft form as part of PR #18434, which is still being iterated on.   That sample will be accompanied by a blog post on the Azure SDK blog with additional discussion, though I don't have a date to share for publication.

The best thoughts that I can offer for the moment is using the source of the [`BlobCheckpointStore`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/BlobCheckpointStore/BlobsCheckpointStore.cs) as an example of one approach to storing data in Blob storage, and the source of the [`EventProcessorClient`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L687) as an illustration of how to integrate it with the `EventProcessor<TPartition>` overrides.
