### ISSUE TITLE
AutoDeleteOnIdle - what is Idle actually?

### ISSUE THREAD

**Issue by lAnubisl** [Azure/azure-sdk-for-net#18591]
What Idle really means?
When a new message comes to queue and noone is listening for a queue does idle reset?
When someone is listening for a queue but no messages are pushed there will the queue be deleted by idle?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9113c501-b9ba-0e4e-c497-2c5735dee396
* Version Independent ID: 705669ed-ced6-654b-6f75-72e0c48932eb
* Content: [QueueDescription.AutoDeleteOnIdle Property (Microsoft.ServiceBus.Messaging) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queuedescription.autodeleteonidle?view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceBus.Messaging/QueueDescription.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus.Messaging/QueueDescription.xml)
* Service: **service-bus-messaging**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@lAnubisl thanks for raising this issue.

Any operation (send or receives) resets the idle timer.

**Comment by Aleksey-Kudryavtsev** [comment]
@axisc , and if there's a connection listening for messages from a queue but no messages being pushed to the queue?
Will listening to the queue count as NOT idle when no actual messages are sent/received?

**Comment by axisc** [comment]
If there are any connections listening for messages on the queue, then they usually have a long polling mechanism. In that case the queue is not idle.

The queue is only truly idle if no operations are executed against it.

**Comment by axisc** [comment]
closing this issue for now, do let us know if there are any follow up questions.

**Comment by siewers** [comment]
The documentation is still not very clear on this. I can't read from the current page, what exactly "idle" means.
I had to search and found this issue, which explains it in a comment.

Will the documentation be updated with the answer in this thread?

**Comment by EldertGrootenboer** [comment]
There actually needs to be traffic for the interval to be reset, just having a connection is not enough. We will update the documentation accordingly (https://docs.microsoft.com/en-us/azure/service-bus-messaging/advanced-features-overview#autodelete-on-idle).

**Comment by SeanFeldman** [comment]
@EldertGrootenboer it would be good to expand on what 'traffic' stand for. Receiving from the entity, sending to the entity, or both.
