### ISSUE TITLE
[Perf] Add option to show throughput per parallel workstream

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#18614]
Add an option to show the detailed perf data for each parallel workstream.  Something like this:

```
ID   Operations    Last Completed   Ops/Sec
 0           90              10.0      9.00
 1           85               9.9      8.56
TOTAL                                 17.56
```

**Comment by JimSuplizio** [comment]
Hi @mikeharder, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
