### ISSUE TITLE
MS Docs Publishing: Front Matter Generated for README Files Fails Validation

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#18612]
# Summary

The front matter that is generated by the MS Docs publishing toolchain is failing the automated validation pass.

# Details

## Validation Issues

- Line 2, Column 1: [Warning-ms-prod-and-service] Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.

- Line 9, Column 16: [Warning-ms-prod-technology-invalid] Invalid value for 'ms.technology': 'azure' is not valid with 'ms.prod' value 'azure'.

- Line 11, Column 13: [Warning-ms-service-subservice-invalid] Invalid value for 'ms.service': 'eventhubs'.

- Line 2, Column 1: [Suggestion-description-missing] Missing required attribute: 'description'.

## Generated Front Matter

```
---
title: Azure Event Hubs Event Processor client library for .NET
keywords: Azure, dotnet, SDK, API, Azure.Messaging.EventHubs.Processor, eventhubs
author: maggiepint
ms.author: magpint
ms.date: 02/09/2021
ms.topic: article
ms.prod: azure
ms.technology: azure
ms.devlang: dotnet
ms.service: eventhubs
---
```

## Previously Generated Front Matter (September, 2020)

```
---
title: Azure Event Hubs Event Processor client library for .NET
description: Azure Event Hubs Event Processor client library for .NET - Version 5.2.0
keywords: Azure, dotnet, SDK, API, Azure.Messaging.EventHubs.Processor, eventhubs
author: maggiepint
ms.author: magpint
ms.date: 09/08/2020
ms.topic: article
ms.devlang: .net
ms.service: event-hubs
---
```

# Success Criteria

- Determine if the validation issues are an indication of a problem, or are expected and benign.

- If a problem was determined, front matter generation has been updated to correct the issues.

- **_BONUS POINTS_**:  Front matter generation has been updated to attribute the author of the most recent commit as the article author.

# Related and References

- [Docs.MS Release Updates for Azure.Messaging.EventHubs.Processor (#1797)](https://github.com/Azure/azure-docs-sdk-dotnet/pull/1797)
- [Docs.MS Release Updates for Azure.Messaging.EventHubs (#1796)](https://github.com/Azure/azure-docs-sdk-dotnet/pull/1796)

**Comment by kurtzeborn** [comment]
The customer impact here is minimal (better reporting data).  We haven't gotten to this in 2+ years.  

To get this right, we need to figure out what the fields need to be and then get them into our release plans or have them in a common location and read them out as part of the release.

Please reactivate if you feel strongly about this one.
