### ISSUE TITLE
[BUG] 502 (Bad gateway) when using CheckExistence() for Event Grid

### ISSUE THREAD

**Issue by kamil-mrzyglod** [Azure/azure-sdk-for-net#18616]
**Describe the bug**
Hi, I'm trying to use the following method to check existence of Azure Event Grid existence:
```
client.Resources.CheckExistence(Configuration.ResourceGroupName, "Microsoft.EventGrid", "", "topics", "test", "2020-06-01");
```
I managed to get a result few times, but most executions fails with **Service request failed.** error.

**Expected behavior**
I should receive `Response` object with no error.

**Actual behavior (include Exception or Stack Trace)**
In response I'm getting the following exception:
```
Service request failed.
Status: 502 (Bad Gateway)

Content:


Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-request-id: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Tue, 09 Feb 2021 20:11:35 GMT
Connection: close
Content-Length: 151
Content-Type: application/json; charset=utf-8
Expires: -1
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

I'm authenticating and creating the client as follows:
```
var credentials = new ClientSecretCredential(Configuration.TenantId, Configuration.ClientId, Configuration.ClientSecret);
var client = new ResourcesManagementClient(Configuration.SubscriptionId, credentials);
```

Then I'm performing a bunch of other operations(like checking if RG exists and perfoming deployment - those operations succeed):
```
var rgExists = client.ResourceGroups.CheckExistence(Configuration.ResourceGroupName);
client.Deployments.StartCreateOrUpdate((..)
```

But the command `client.Resources.CheckExistence(Configuration.ResourceGroupName, "Microsoft.EventGrid", "", "topics", "test", "2020-06-01")` fails.

**Environment:**
 - Azure.ResourceManager.Resources 1.0.0-preview.2, Azure.Identity 1.3.0
 - VS Code 1.53.0
 ```
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.1.805 [C:\Program Files\dotnet\sdk]
  3.1.102 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ahamad-MS** [comment]
Hello @kamil-mrzyglod  .. Thanks for reaching out and reporting this issue. Even though you are trying to check EventGrid resources, the API used here is not an EventGrid API or ends up into our Resource Provider. It is Azure Resource Manager (ARM) API.

Here is the equivalent REST API https://docs.microsoft.com/en-us/rest/api/resources/resources/checkexistence 

The Bad Gateway error you get indicates some issues with ARM frontend .. However, to allow me to investigate further and direct your request to the right team if needed, please provide couple of instances when this happens with the following info:

1. Exact time (UTC or Pacific).
2. Region/location?

Also, I would like to understand your case scenario and why you need to do this operation? What are you trying to achieve here and why not using Event Grid API directly?

Thanks

**Comment by ahamad-MS** [comment]
Hello @allenjzhang and @jsquire.. Thanks for forwarding this to Event Grid. FYI, this is not event grid specific issue and should ideally go to ARM Team. I will do initial investigation first before routing it to the right team. additional info requested from customer.

Can you please let me know the right service label to be used for ARM services?

thanks

**Comment by jsquire** [comment]
Thank you, @ahamad-MS.   I believe the `ARM` tag is what we're looking for.   I've retagged based on your feedback.

**Comment by ahamad-MS** [comment]
Great. thank you @jsquire

**Comment by kamil-mrzyglod** [comment]
@ahamad-MS I was using this particular generic method as I wanted to use `Azure.ResourceManager.Resources` package and(correct me if I'm wrong) there's no corresponding package for Event Grid. My understanding of `CheckExistence` method is I'm able to check any resource I want assuming I'm providing correct parameters.

**Comment by ahamad-MS** [comment]
Your understanding is correct and I am not discouraging you from using it if it fits your need. It just seems unnecessary for EventGrid case if you are using the right API version but I can see how you would use it if needed.

I will let ARM team handle your questions and case because this is outside scope of Event Grid service and in arm service area.

thanks

**Comment by jbockle** [comment]
I'm seeing the same issue with this api https://docs.microsoft.com/en-us/rest/api/resources/resources/checkexistencebyid
also
P.S. the api version listed in the docs appears to be incorrect, if i use getbyid which references the same api version `2020-06-01`, I get an error that its not a supported api version.

**Comment by Yao725** [comment]
This is an issue regarding arm service. However, you can use the method `CheckIfExists` in the re-designed Azure.ResourceManager 1.0.0-beta.7 package as a work around. Code will like this:
```
ArmClient armClient = new ArmClient(new DefaultAzureCredential());
Subscription subscription = await armClient.GetDefaultSubscriptionAsync();
var result = await subscription.GetGenericResources().CheckIfExistsAsync("resourceId");
```

**Comment by navba-MSFT** [comment]
@kamil-mrzyglod Apologies for the late reply. Could you please let me know if you had a chance to try the above suggestion? Awaiting your reply.

**Comment by kamil-mrzyglod** [comment]
@navba-MSFT I don't have that codebase anymore so no chance of verifying that on my side unfortunately.

**Comment by navba-MSFT** [comment]
@kamil-mrzyglod Thanks for your getting back. I am sorry to hear about that. If you happen to work on this again, please do get back to us on this github thread. We would be happy to work with you again on this.
