### ISSUE TITLE
[MetricsAdvisor] Updates for GA

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-sdk-for-net#18610]
### Contract updates

- [x] New data source types: Event Hubs and Log Analytics
- [x] ~**Alert config** -> value filter : add value type (value & mean)-> add a parameter : send by dim~ (moved to https://github.com/Azure/azure-sdk-for-net/issues/21670)
- [x] **Anomaly | incident result** -> add value and expected value

### Fixed issues (may or may not need SDK changes)

- [x] Rename $top to $maxPageSize

**Comment by kinelski** [comment]
All items implemented/moved.
