### ISSUE TITLE
[QUESTION] OpenWrite stream not generating md5 checksum

### ISSUE THREAD

**Issue by WSebo** [Azure/azure-sdk-for-net#18641]
Hello, I ran into a problem, while streaming files to zip blob. To do that I OpenWrite stream of blob (it is no seekable), then pass it to ZipArchive and stream files directly to this zip archive. Everythink works fine, no memory is used to materialize files, but md5 content is not generated on blob. When i load all files to seekable stream like MemoryStream, then upload it to blob - md5 content is here, but it needs to load 500mb of files into RAM.

So my question is, how to do it? How to stream lots of files packed into zip, directly to blob, without materialize to RAM.

Here is the code as I do it now.

```cs
var zipPath = $"{Paths.GetPath(query.FileTypeEnum)}{Guid.NewGuid()}.zip";
var blockBlobClient = _blobManipulator.GetBlockBlobClient(zipPath);

await using (var blobStream = await blockBlobClient.OpenWriteAsync(true))
{
    using (var zip = new ZipArchive(blobStream, ZipArchiveMode.Create, true))
    {
        createDto = await query.ProcessUploadContentDelegate(async file =>
        {
            await ValidateFile(file, query.FileTypeEnum);

            await using (var fileStream = file.OpenReadStream())
            {
                var zipEntry = zip.CreateEntry(file.FileName);
                await using (var zipEntryStream = zipEntry.Open())
                {
                    _logger.LogInformation($"Adding {file.FileName} to zip");
                    await fileStream.CopyToAsync(zipEntryStream);
                }
            }
        });
    }
}
```

Azure.Storage.Blobs 12.9.0-beta.1
Windows 10 .NET 5.0.101
Visual Studio 16.8.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

This might be how the storage service works with the difference of how Put Blob and Put Block List. I think @seanmcc-msft explains it [here](https://github.com/Azure/azure-sdk-for-net/issues/17676#issuecomment-749777800) well. Open write works by doing Put Block List(s), so the service does not calculate the MD5. Compared to when you are just using `MemoryStream` and calling `Upload`, that calls Put Blob which calculates the MD5.

**Comment by WSebo** [comment]
Ok, thank you for response. I would like to mention that it worked on the deprecated version. The same code.
I am not sure about files >256MB. So why in the new version decided to change this behavior (for OpenWrite) even for small files?
By way of deduction, earlier OpenWrite must using Put Blob, and it was changed to Put Block List for some reason.

**Comment by amnguye** [comment]
I can't speak entirely for the deprecated version of openwrite, but I'm assuming that it either would do an entire Put Blob for the small files (which is something you probably don't want anyways) which would give you the content md5 or it was not writing each block up as you are writing to the stream and was either waiting until the block gets big enough, you closed the stream or there was a delay on the Put Block List.

I think the current version of how we have OpenWrite accurately describes the functionality of the feature.
