### ISSUE TITLE
Please explain what withhttpmessagesasync suffix means. 

### ISSUE THREAD

**Issue by cjjohansen** [Azure/azure-sdk-for-net#18644]
Please explain what withhttpmessagesasync suffix means. 

Its used widely in EventGridManagementClient.

But I have no idea what it means.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 004f540e-d697-ada1-ce7b-7793da288f88
* Version Independent ID: fd051ebd-69f1-22a9-40bb-bb9ee7e327dc
* Content: [EventGridClient.PublishEventsWithHttpMessagesAsync(String, IList&lt;EventGridEvent&gt;, Dictionary&lt;String,List&lt;String&gt;&gt;, CancellationToken) Method (Microsoft.Azure.EventGrid) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventgrid.eventgridclient.publisheventswithhttpmessagesasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.EventGrid/EventGridClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.EventGrid/EventGridClient.xml)
* Service: **event-grid**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by qcnguyen** [comment]
any updates team ? I have the same question.

**Comment by navba-MSFT** [comment]
@cjjohansen Apologies for the late reply. The sample code for this API is available here [event-grid-dotnet-publish-consume-events/Program.cs at master · Azure-Samples/event-grid-dotnet-publish-consume-events (github.com) ](PublishEventsWithHttpMessagesAsync ).

However, please be advised that we are stopping support for this nuget/API and is being replaced with a new one under  Azure.Messaging.EventGrid Namespace (namely,. [Azure.Messaging.EventGrid Namespace - Azure for .NET Developers | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventgrid?view=azure-dotnet)).

Sample code for this API and more details are available here: [azure-sdk-for-net/Sample1_PublishEventsToTopic.md at main · Azure/azure-sdk-for-net (github.com)](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventgrid/Azure.Messaging.EventGrid/samples/Sample1_PublishEventsToTopic.md). Hope this helps.

Please let us know if more info needed.
