### ISSUE TITLE
FormRecognizer: ModelName not found in Manage custom models of FormTrainingClient

### ISSUE THREAD

**Issue by ShamineDsouza** [Azure/azure-sdk-for-net#18642]
Dear Team ,

Under manage Custom models , I was going through "Manage Custom Models Asynchronously"
However there seems to be some issue , certain properties are not found and there are errors being thrown
Eg: ModelName, Properties , etc

Code:

```csharp
using Azure;
using Azure.Core;
using Azure.AI.FormRecognizer;
using Azure.AI.FormRecognizer.Training;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

// List the models currently stored in the account.
AsyncPageable<CustomFormModelInfo> models = client.GetCustomModelsAsync();

await foreach (CustomFormModelInfo modelInfo in models)
{
    Console.WriteLine($"Custom Model Info:");
    Console.WriteLine($"  Model Id: {modelInfo.ModelId}");

    // These lines are the focal point of the problem:
    Console.WriteLine($"  Model name: {modelInfo.ModelName}");
    Console.WriteLine($"  Is composed model: {modelInfo.Properties.IsComposedModel}");
    // ...

    Console.WriteLine($"  Model Status: {modelInfo.Status}");
    Console.WriteLine($"  Training model started on: {modelInfo.TrainingStartedOn}");
    Console.WriteLine($"  Training model completed on: : {modelInfo.TrainingCompletedOn}");
}
```
![image](https://user-images.githubusercontent.com/25946929/107481484-4e1dc000-6b8f-11eb-89f2-729222a81334.png)

Please help.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best member able to assist.

**Comment by maririos** [comment]
@ShamineDsouza which version of the Form Recognizer library are you using? ModelName was introduced in package 3.1.0-beta.1 ([NuGet](https://www.nuget.org/packages/Azure.AI.FormRecognizer/3.1.0-beta.1) | [Changelog](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/CHANGELOG.md#310-beta1-2020-11-23)) so I wonder if you are targeting a different version.
