### ISSUE TITLE
How is it used?

### ISSUE THREAD

**Issue by AndyP2** [Azure/azure-sdk-for-net#18648]
It would be really great to have links here to associated extension methods like UseSampling and UseAdaptiveSampling.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f02d4e4b-acd4-807f-0533-843b6d6626bd
* Version Independent ID: 854dc341-dbc9-22db-7f16-ae3d2c3fd080
* Content: [TelemetryProcessorChainBuilder Class (Microsoft.ApplicationInsights.Extensibility.Implementation)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.extensibility.implementation.telemetryprocessorchainbuilder?view=azure-dotnet)
* Content Source: [xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryProcessorChainBuilder.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights.Extensibility.Implementation/TelemetryProcessorChainBuilder.xml)
* Service: **application-insights**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
This has been moved to the Azure SDK repository:   https://github.com/Azure/azure-sdk-for-net/issues/18647

**Comment by pakrym** [comment]
I think https://docs.microsoft.com/en-us/azure/azure-monitor/app/sampling has it

**Comment by AndyP2** [comment]
/unresolve
That page does contain the missing information, but there is no way I could find to discover or navigate to that document from here. The least I would expect is the "Sampling in Application Insights" document to appear in the 'Recommended content' section at the bottom, or better, to have a link to it in the text.
In fact this observation applies to many of the detail pages in the API reference. It feels like asking a taxi to take you somewhere and being told "If that's where you are going, I wouldn't start from here" :-)

**Comment by AlexGhiondea** [comment]
Submitted a PR to the sample: https://github.com/Azure/azure-docs-sdk-dotnet/pull/2091
