### ISSUE TITLE
[FEATURE REQ] Release ScheduledQueryRule API 2020-05-01-preview to SDK

### ISSUE THREAD

**Issue by yanivlavi** [Azure/azure-sdk-for-net#18643]
**Library or service name.**
What library or service is this request related to? 
Azure Monitor ScheduledQueryRule API
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving? 
Can you please release an SDK for ScheduledQueryRule API 2020-05-01-preview. This is needed for PowerShell development for the GA release.

**Comment by yanivlavi** [comment]
Swagger definition is available here:
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/monitor/resource-manager

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
