### ISSUE TITLE
Azure Application Insights libraries for .NET Documentation - Broken link

### ISSUE THREAD

**Issue by stephen-cripps** [Azure/azure-sdk-for-net#18647]
"Application Insights Analytics with OpenSchema" link is broken

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3628e326-be45-e441-eb62-627b721d3e70
* Version Independent ID: e4e26910-eda8-a7f8-de42-150232c24a8b
* Content: [Azure Application Insights libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/insights?view=azure-dotnet)
* Content Source: [api/overview/azure/insights.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/insights.md)
* Service: **application-insights**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by pakrym** [comment]
@reyang can you please forward to the appropriate person on the AppInsights team?

**Comment by reyang** [comment]
> @reyang can you please forward to the appropriate person on the AppInsights team?

Sorry @pakrym I don't know the appropriate person.

**Comment by AlexGhiondea** [comment]
https://github.com/Azure/azure-docs-sdk-dotnet/pull/2091
