### ISSUE TITLE
What is the default value for MaxAutoRenewDuration?

### ISSUE THREAD

**Issue by bibliothek** [Azure/azure-sdk-for-net#18650]
What is the default value MaxAutoRenewDuration? 

This information should be included in the documentation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cde8a2d5-889d-9746-cdae-49e8036ac504
* Version Independent ID: f4b244d8-2d2a-c276-76b7-0b2bd7179a2e
* Content: [MessageHandlerOptions.MaxAutoRenewDuration Property (Microsoft.Azure.ServiceBus)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.messagehandleroptions.maxautorenewduration?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.ServiceBus/MessageHandlerOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.ServiceBus/MessageHandlerOptions.xml)
* Service: **service-bus**
* GitHub Login: @erickson-doug
* Microsoft Alias: **douge**

**Comment by jsquire** [comment]
Migrating to the Azure SDK repository.  Tagging and routing to the team best able to assist.

**Comment by Marusyk** [comment]
Still open since 2018 🤔

**Comment by ramya-rao-a** [comment]
@JoshLove-msft 

The default values are already documented at the docs for the [MessageHandlerOptions class](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/servicebus/Microsoft.Azure.ServiceBus/src/MessageHandlerOptions.cs#L19-L27)

Any idea why everything in the docs are blank?

cc @danieljurek

**Comment by ramya-rao-a** [comment]
#11798 might be related

**Comment by ramya-rao-a** [comment]
Since the default values are already documented in the source code and we have #11798 to track the larger problem of the documentation not appearing in docs.microsoft.com for the Microsoft.Azure.ServiceBus package, we will close this issue and use #11798 to track the larger problem

Thanks for reporting!
