### ISSUE TITLE
Verify there is no cross-service ProjectReferences when releasing a package

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#18656]
Cross-service ProjectReferences might lead to releasing packages with dependencies that can't be satisfied and should be discouraged.

**Comment by jsquire** [comment]
This part of the process is covered by the work that @ckairen is doing to parse available packages and versions for consumption by the smoke tests.    Reassigning.

//cc: @benbp

**Comment by pakrym** [comment]
I think this is already covered by the installation check added by @ckairen. I'll let him close.

**Comment by JimSuplizio** [comment]
Hi @pakrym, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
