### ISSUE TITLE
Build Reliability

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#18669]
Report: https://msit.powerbi.com/groups/3e17dcb0-4257-4a30-b843-77f47f1d4121/reports/c30a45b0-ae9b-4b19-9a33-b8ecfe8e5e3c/ReportSectioncabe9e2b85ee20b17671

**Comment by ShivangiReja** [comment]
**Test Failure issues**: 

* [Form Recognizer] flaky test : https://github.com/Azure/azure-sdk-for-net/issues/19144
* [Form Recognizer] weekly tests fails with RequestFailedException in Canary region: https://github.com/Azure/azure-sdk-for-net/issues/19146
* [Search] flaky test in weekly runs: https://github.com/Azure/azure-sdk-for-net/issues/19148
* [App Config] CreateSecretReference test is failing in weekly runs - https://github.com/Azure/azure-sdk-for-net/issues/19150
* [Synapse] TestListSparkApplications test is failing in nightly runs - https://github.com/Azure/azure-sdk-for-net/issues/19151
* [Tables] weekly tests in Canary: #17714

**Comment by ShivangiReja** [comment]
Test Resources Failure issues:

* [Digital Twins] weekly runs fail with DeploymentFailed error: https://github.com/Azure/azure-sdk-for-net/issues/19335
* [Storage] weekly runs fail with FeatureNotSupportedForAccount error: https://github.com/Azure/azure-sdk-for-net/issues/19337
