### ISSUE TITLE
GetTokenAsync of DefaultAzureCredential does not simply take a resourceId

### ISSUE THREAD

**Issue by Ofekw** [Azure/azure-sdk-for-net#18685]
Specifically referencing: `var accessToken = await tokenCredential.GetTokenAsync(ResourceId);` 

Looking at the implementation of [DefaultAzureCredential](https://github.com/Azure/azure-sdk-for-net/blob/a79bd104ab8c2cf79e0f9b2c60619de85f101d71/sdk/identity/Azure.Identity/src/DefaultAzureCredential.cs#L98), this is incorrect. The GetTokenAsync only takes in a TokenRequestContext so the call would actually look like:
`var accessToken = await tokenCredential.GetTokenAsync(ResourceId + "/.default");` 
 e.g  `"https://keyvault.microsoft.com//.default"`

The docs imply that resourceId is a string, which is the same as the appAuthentication library. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f95d1f9-f552-ab33-2cbb-f5bc09f6cf5f
* Version Independent ID: 76c243d5-0e9f-cb8d-8919-a06e75ad2cf5
* Content: [App Authentication to Azure Identity Migration Guidance - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration)
* Content Source: [api/overview/azure/app-auth-migration.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/app-auth-migration.md)
* Product: **azure**
* GitHub Login: @jlichwa
* Microsoft Alias: **jalichwa**

**Comment by jlichwa** [comment]
@nonik0 can you take a look.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
closed by https://github.com/Azure/azure-docs-sdk-dotnet/pull/1854
