### ISSUE TITLE
[BUG] FrontDoorModel maps 'Cname' to wrong property and is always null

### ISSUE THREAD

**Issue by asleire** [Azure/azure-sdk-for-net#18691]
**Describe the bug**
The `FrontDoorModel.Cname` property is [mapped](https://github.com/Azure/azure-sdk-for-net/blob/e547c1b601afea7cb40fa4fedd0198b338e9f7cf/sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/src/Generated/Models/FrontDoorModel.cs#L163) to the JSON property `properties.cname`, which is wrong, resulting in `FrontDoorModel.Cname` always being null.

**Expected behavior**
It should be mapped to the JSON property `properties.cName`. `FrontDoorModel.Cname` should not be null.

**Actual behavior (include Exception or Stack Trace)**
It is not mapped to the JSON property `properties.cName`. `FrontDoorModel.Cname` is always null.

**To Reproduce**

Use `FrontDoorManagementClient` to retrieve any Front Door instance. The `FrontDoorModel.Cname` property will be null.

**Environment:**
 - `Microsoft.Azure.Management.FrontDoor` `4.0.0`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JonathanCrd** [comment]
@asleire Can you provide the JSON that you received from the service?

**Comment by asleire** [comment]
I don't want to paste the complete JSON with all the IDs publicly. In the Azure Portal you can use JSON View on any front door, and regardless of API version the cname property will have the JSON key `cName`
![image](https://user-images.githubusercontent.com/631907/107698694-36d8f280-6cb5-11eb-9afa-5aee1d6de17c.png)

**Comment by JonathanCrd** [comment]
Thank you for your response, rerouting to the service team.
