### ISSUE TITLE
Smoke Tests should run samples

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#18721]
Other languages are already doing this (see Java's [issue](https://github.com/Azure/azure-sdk-for-java/issues/14690)).
.NET has a smoke test pipeline but it is not fully done, so there is work to be done to get there.

@benbp and @hemanttanwar have done it before so reach out to them for their expertise

**Comment by AlexGhiondea** [comment]
We have decided to have a different approach with our smoke tests.
