### ISSUE TITLE
Update the autorest.md file to use README.md as an input instead of swagger json file

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#18727]
We should be using README file from the spec repo instead of json as an `input-file` in [autorest.md](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/anomalydetector/Azure.AI.AnomalyDetector/src/autorest.md) because readme.md file has all the configuration. If you want to change the configuration, you can override it in the autorest.md.

For example check `require` parameter [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/appconfiguration/Azure.ResourceManager.AppConfiguration/src/autorest.md), we pass readme file as an input.

**Comment by pakrym** [comment]
Consider adding some validation mechanism similar to how we validate that paths contain sha here: https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/build/CodeGeneration.targets#L30
