### ISSUE TITLE
Port fix from WebJobs.Extensions.Storage track 2

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-sdk-for-net#18720]
Port https://github.com/Azure/azure-webjobs-sdk/commit/21d9d4ea4917a11f274bcd9f61600fbfbfceed17

**Comment by amnguye** [comment]
Ah okay I see, the blobName is incorrectly parsed in KustoLogs. Let me mark this as a bug and we where the changes we have to apply to match the PR you linked.
