### ISSUE TITLE
[Keyvault] Update the autorest.md file to use README.md as an input instead of swagger json file

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#18734]
We should be using README file from the spec repo instead of json as an `input-file` in [autorest.md](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Administration/src/autorest.md) because readme.md file has all the configuration. If you want to change the configuration, you can override it in the autorest.md.

For example check `require` parameter [here](https://github.com/azure/azure-sdk-for-net/blob/master/sdk/anomalydetector/Azure.AI.AnomalyDetector/src/autorest.md), we pass readme.md file as an input.

**Comment by heaths** [comment]
@ShivangiReja how would this work with split swaggers? The service team does not create separate tags for each swagger, and we have separate client SDKs for each (well, almost all of them). What benefits does using the autorest.md file over the swaggers have? Is it worth trying to make this scenario work (I imagine other SDKs will have a similar problem)?

**Comment by ShivangiReja** [comment]
I did not see the split swaggers case before but if this is a case then I think we should create a separate tag with the swaggers that we would like to generate SDK from. You can also update the[ readme.md](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/keyvault/data-plane/readme.md) file and create a tag.

CC: @pakrym

**Comment by heaths** [comment]
Those tags are used by other generators. I hesitate to make such a drastic change to a shared file (i.e. not just by other Azure SDKs) without understanding if the benefits are worth the risks. Many times, for example, I've seen both the Go SDK and Azure CLI teams make changes to this file due to issues more general changes have caused for them.

**Comment by heaths** [comment]
Per internal, ongoing discussion it seems few languages are using these currently. We should unify across languages as well as services, so this will require some effort to make per-feature, per-version tags (at least going forward) and use them across languages. I doubt the technical work itself will be much (almost definitely not), but making sure we get this all in place across languages will take a bit.

**Comment by heaths** [comment]
We're nearing a GA, so we want to push this out - especially since some other languages may need to change process some.

**Comment by heaths** [comment]
To note, we may be able to do this before May, but I'd rather under-promise and over-deliver than vice versa. 😉

**Comment by heaths** [comment]
Too many languages have different customizations and, while that is supported, with a push toward Cadl this doesn't seem worth it given how long it's been open and undone.
