### ISSUE TITLE
Make sure links in source do not hardcode a locale

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#18738]
No links should have a hard-coded language, i.e.:

```suggestion
        /// For more information, see <see href="https://docs.microsoft.com/rest/api/storageservices/creating-a-snapshot-of-a-blob">
```

Please remove "en-us/" from this and other links within this PR so that users are taken to the preferred language of their browser/OS.

@scbedd should DocWarden be catching these?

_Originally posted by @heaths in https://github.com/Azure/azure-sdk-for-net/pull/17825#discussion_r575557453_

**Comment by jsquire** [comment]
These are caught during CI as part of analysis now.   Closing this out.   @heaths - if I'm overlooking some nuance, please feel free to reopen.

**Comment by heaths** [comment]
It's been a while since I opened this, but I think it was meant (and I should've been more clear) to check *all* files. That said, I had also more recently opened Azure/azure-sdk-tools#6107 that should cover that.
