### ISSUE TITLE
[Communication] Update the autorest.md file to use README.md as an input instead of swagger json file

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#18733]
We should be using README file from the spec repo instead of json as an `input-file` in autorest.md because readme.md file has all the configuration. If you want to change the configuration, you can override it in the autorest.md.

For example check `require` parameter [here](https://github.com/azure/azure-sdk-for-net/blob/master/sdk/anomalydetector/Azure.AI.AnomalyDetector/src/autorest.md), we pass readme file as an input.

**Comment by RezaJooyandeh** [comment]
@ShivangiReja is there a documentation for the format of the readme.md combined with this `required` format when we have multiple packages each using a different swagger? The example that you linked has only one swagger, but communication services has multiple swagger and we are not.

**Comment by ShivangiReja** [comment]
If you have multiple swaggers, then you can use `tag` property in your `autorest.md` which is defined [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/communication/data-plane/readme.md).

For example: you can update [this](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/communication/Azure.Communication.Chat/src/autorest.md) autorest.md like below. It will map the tag value defined [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/communication/data-plane/readme.md) and use the swagger input-file based on the tag.
```
tag: package-2020-11-01-preview3
require:
    -  https://raw.githubusercontent.com/Azure/azure-rest-api-specs/5c659a0b9a2826f1133cef96748f5c7b956557bf/specification/communication/data-plane/readme.md
.
.
.
```

You can refer [Synapse ](https://github.com/azure/azure-sdk-for-net/blob/master/sdk/synapse/Azure.Analytics.Synapse.Monitoring/src/autorest.md) as an example. It also has multiple swaggers.

**Comment by ShivangiReja** [comment]
If you have multiple swaggers, then you can use `tag` property in your `autorest.md` which is defined [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/communication/data-plane/readme.md).

For example: you can update [this](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/communication/Azure.Communication.Chat/src/autorest.md) autorest.md like below. It will map the tag value defined [here](https://github.com/Azure/azure-rest-api-specs/blob/5c659a0b9a2826f1133cef96748f5c7b956557bf/specification/communication/data-plane/readme.md#tag-package-2020-11-01-preview3) and use the swagger input-file based on the tag.
```
tag: package-2020-11-01-preview3
require:
    -  https://raw.githubusercontent.com/Azure/azure-rest-api-specs/5c659a0b9a2826f1133cef96748f5c7b956557bf/specification/communication/data-plane/readme.md
.
.
.
```

You can refer [Synapse ](https://github.com/azure/azure-sdk-for-net/blob/master/sdk/synapse/Azure.Analytics.Synapse.Monitoring/src/autorest.md) as an example. It also has multiple swaggers.

**Comment by DominikMe** [comment]
@ShivangiReja We have multiple swaggers under the same tag in the spec repo, but we want exactly one swagger per library in the SDK repo. So our library only wants to pull one swagger out of the set of swaggers for that tag.

I don't know how this would work unless we change the README in the spec repo to have a seperate tag for each swagger.

**Comment by RezaJooyandeh** [comment]
Separate tag is ok, I was talking to some of the rest repo reviewers and we did that a little while ago for SMS too.

**Comment by JoshuaLai** [comment]
This has been merged in and I have completed this task for all the other language platforms as well @RezaJooyandeh. 
Closing this task
