### ISSUE TITLE
App Service Management Library: Link is broken

### ISSUE THREAD

**Issue by mturzynski** [Azure/azure-sdk-for-net#18750]
**Manage your web apps with the .NET SDK for Azure** link at the end of the page is broken (404)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 277adb93-5a3c-b8bb-44bd-22c55722d92d
* Version Independent ID: e1c13879-63dd-2e01-2759-a8ac7a49670a
* Content: [Azure App Service libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/appservice)
* Content Source: [api/overview/azure/appservice.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/appservice.md)
* Service: **app-service**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by allenjzhang** [comment]
@CamSoper , can you please take a look at this doc issue?

**Comment by CamSoper** [comment]
Submitted https://github.com/Azure/azure-docs-sdk-dotnet/pull/1925
