### ISSUE TITLE
Update the ServerPublicNetworkAccess for a Azure SQL server

### ISSUE THREAD

**Issue by ivanscattergood** [Azure/azure-sdk-for-net#18752]
**Query/Question**
I'd like to change the state of ServerPublicNetworkAccess for an Azure SQL server from the c# Management package. 

I can find the resource using the following list method and then getting the first element
    
```
var listResult = await resources.ListByResourceGroupAsync(resourceGroupName, "resourceType eq '" + type  + "' and name eq '" + name + "'").ToEnumerableAsync();
GenericResource genericResource = listResult[0]; 
```

I want to then update the one of the properties: 

 ```
       genericResource.Properties = new Dictionary<string, object>
                            {
                            { "publicNetworkAccess", "Disabled" }
                            };

            ResourcesUpdateOperation result =    resources.StartUpdate(resourceGroupName,
                "",
                "",
                    "Microsoft.Sql/servers",
                    name,
                    "2014-04-01",
                   genericResource);
```

But I get the following error: 

Status: 400 (Bad Request)

Content:
{"code":"BadRequest","message":"An error occurred while processing this request.","target":null,"details":[],"innererror":[]}

Headers:
Cache-Control: no-store, no-cache
x-ms-request-id: REDACTED
X-Content-Type-Options: REDACTED
DataServiceVersion: REDACTED
Strict-Transport-Security: REDACTED
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Date: Sun, 14 Feb 2021 23:28:16 GMT
Content-Length: 125
Content-Type: application/json

   at Azure.ResourceManager.Resources.ResourcesRestOperations.Update(String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, GenericResource parameters, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.ResourcesOperations.StartUpdate(String resourceGroupName, String resourceProviderNamespace, String parentResourcePath, String resourceType, String resourceName, String apiVersion, GenericResource parameters, CancellationToken cancellationToken)
   at ManageResource.Program.RunSample(TokenCredential credential) in C:\code\azure-samples-net-management\samples\resources\manage-resource\Program.cs:line 59

**Environment:**
 dotnet --info 
.NET SDK (reflecting any global.json):
 Version:   5.0.102
 Commit:    71365b4d42

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.102\

Host (useful for support):
  Version: 5.0.2
  Commit:  cb5f173b96

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ivanscattergood** [comment]
@jsquire  I have managed a workaround using  an arm template:


```
            string serverName = Environment.GetEnvironmentVariable("SQL_SERVER");
            string rgName = Environment.GetEnvironmentVariable("RESOURCE_GROUP");
            string location = Environment.GetEnvironmentVariable("LOCATION");

            
            var deploymentName = "publicNetworkAccess.json";
            
            
            var templateJson = Utilities.GetArmTemplate(deploymentName);

            var resourceClient = new ResourcesManagementClient(subscriptionId, credential);
            var resourceGroups = resourceClient.ResourceGroups;
            var deployments = resourceClient.Deployments;

            try
            {


                // Create a deployment for an Azure App Service via an ARM
                // template.

                Utilities.Log("Starting a deployment for: " + deploymentName);

                JToken contourManifest = JObject.Parse(templateJson);

                JObject resources = (JObject)contourManifest["resources"][0];

                resources["name"] = serverName;
                resources["location"] = location;

                JObject properties = (JObject)resources["properties"];
                properties["publicNetworkAccess"] = state;



                Utilities.Log("Starting a deployment for: " + contourManifest.ToString());

                    var parameters = new Deployment
                    (
                        new DeploymentProperties(DeploymentMode.Incremental)
                        {
                            Template = templateJson,
                            Parameters = "{}"
                        }
                     );
                    var rawResult =  deployments.StartCreateOrUpdate(rgName, deploymentName, parameters);
                    rawResult.WaitForCompletionAsync();

                Utilities.Log("Completed the deployment: " + deploymentName);
            }
            catch (Exception ex)
            {
                Utilities.Log(ex);
            }
```



Here is the contents of my json arm file: 


```
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
   
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Sql/servers",
      "apiVersion": "2019-06-01-preview",
      "name": "canvolution",
      "location": "uksouth",
      "kind": "v12.0",
      "properties": {
        "publicNetworkAccess": "Disabled"
      }
    }
  ]
}

```

**Comment by ivanscattergood** [comment]
Any news on this issue?

**Comment by SaurabhSharma-MSFT** [comment]
@ivanscattergood Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .
