### ISSUE TITLE
Cognitive - Text Analytics for .NET (January-June 2021)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#18769]
This tracks the work for Cognitive - Text Analytics for .NET.

**Comment by maririos** [comment]
Apparently I can't add closed epics, so manually: #16282

**Comment by maririos** [comment]
lol thanks @AlexGhiondea !!!

**Comment by maririos** [comment]
@AlexGhiondea is the idea to open another issue for the next semester? or rename this one

**Comment by jsquire** [comment]
Closing;  no open issues remain and the milestone has ended.
