### ISSUE TITLE
Messaging - Service Bus for .NET (January-June 2021)

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#18773]
[Azure Service Bus](https://azure.microsoft.com/services/service-bus/) is a cloud messaging service with message queues and publish-subscribe topics.

The [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.Servicebus) package provides the SDK for .Net developers to write applications that use Azure Service Bus. Version 7 of this package follows the latest [guidelines for writing C# .Net SDKs for Azure services](https://azure.github.io/azure-sdk/dotnet_introduction.html) with the goal of being  a client library that is developer-friendly, idiomatic to the .Net ecosystem, and as consistent across different languages and platforms as possible.

This issue tracks the work we have planned for this package for the duration of January - June 2021

### New features:
- Support Cross Entity Transactions
- Support for **SharedKeyCredential and SASCredential** to allow rotation of Shared keys and SAS tokens which is not possible when using connection strings
- Support all AMQP body section types in the Service Bus message
- Investigate alternatives for Plugins from Microsoft.Azure.ServiceBus
- Support credit draining

### General improvements:
- Fix incoming customer reported issues
- Build Trouble Shooting Guides

### Testing improvements:
- Add perf tests that are run before every update to catch regressions
- Fix flaky tests if any

### Documentation
- Consider having counterparts to the samples in https://github.com/azure/azure-service-bus that use Microsoft.Azure.ServiceBus
- Migration Guide from WindowsAzure.ServiceBus to Azure.Messaging.ServiceBus

**Comment by JoshLove-msft** [comment]
Closing as current semester work will be tracked in https://github.com/azure/azure-sdk-for-net/issues/22173
