### ISSUE TITLE
startswith in filter expression returns bad request

### ISSUE THREAD

**Issue by glenthomas** [Azure/azure-sdk-for-net#18786]
The example filter shown causes the service bus to return "(400) Bad Request. Invalid Filter. StartsWith is not allowed in the filter expression"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e3dc0f0b-ef56-7ffd-a0a4-70ec75ac8c30
* Version Independent ID: 125cff6f-a5ec-b488-3b82-907e0aff1834
* Content: [NamespaceManager.GetSubscriptions Method (Microsoft.ServiceBus)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.namespacemanager.getsubscriptions?view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceBus/NamespaceManager.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus/NamespaceManager.xml)
* Service: **service-bus**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by ramya-rao-a** [comment]
@DorothySun216, Can you please update the docs for the `GetSubscriptions` method?

@glenthomas Please note that a newer package Azure.Messaging.ServiceBus,is available as of November 2020 for Azure Service Bus. While the older `WindowsAzure.ServiceBus` will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read https://aka.ms/azsdk/blog/msging/intro for more details.

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the service team tracks issues for the `WindowsAzure.ServiceBus` library as [#667](https://github.com/Azure/azure-service-bus/issues/667).
