### ISSUE TITLE
IClientAssertionCertificate Thumbprint

### ISSUE THREAD

**Issue by tgradu** [Azure/azure-sdk-for-net#18784]
Hello, 
As per the MS Documentation, the Thumbprint property of the IClientAssertionCertificate should contain the Thumbprint of the Certificate.

However in order to get it to work you need to set the Thumbprint to Convert.ToBase64String(Certificate.GetCertHash());

Can you please update the documentation as this is not that straight forward and it took quite a while to figure it out. 

Thanks
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2230241c-e9fd-312e-5ab3-d7dfb18fa2b5
* Version Independent ID: 379a762b-c6ad-05ae-8cf3-1a79cf12c46e
* Content: [IClientAssertionCertificate.Thumbprint Property (Microsoft.IdentityModel.Clients.ActiveDirectory)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.iclientassertioncertificate.thumbprint?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_IClientAssertionCertificate_Thumbprint)
* Content Source: [xml/Microsoft.IdentityModel.Clients.ActiveDirectory/IClientAssertionCertificate.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory/IClientAssertionCertificate.xml)
* Service: **active-directory**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
//cc: @nonik0, @anaismiller

**Comment by jsquire** [comment]
Given the age of this issue and number of releases of the package since this was filed, closing this as stale.  Please feel free to [open an issue in the repository for the Identity Model package](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues) if this remains a problem with the latest version.
