### ISSUE TITLE
What is the definition of idle?

### ISSUE THREAD

**Issue by beaubgosse** [Azure/azure-sdk-for-net#18785]
What is considered idle? Does the idle only reset if a message is placed in the queue/subscription? Or does it stay non-idle if there is a service bus running listening to this queue?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9113c501-b9ba-0e4e-c497-2c5735dee396
* Version Independent ID: 705669ed-ced6-654b-6f75-72e0c48932eb
* Content: [QueueDescription.AutoDeleteOnIdle Property (Microsoft.ServiceBus.Messaging)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queuedescription.autodeleteonidle?view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceBus.Messaging/QueueDescription.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus.Messaging/QueueDescription.xml)
* Service: **service-bus**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by axisc** [comment]
@beaubgosse any operation of a entity in Service Bus will reset the idle timer. This includes sends, receives (even if nothing is on the queue), or management operations.

Hope this helps.
