### ISSUE TITLE
Example Sections of CosmosDB CosmosClientOptions Class Not Well-Formatted

### ISSUE THREAD

**Issue by mindlessroman** [Azure/azure-sdk-for-net#18795]
The docs for the [CosmosClientOptions class](https://docs.microsoft.com/en-us/dotnet/api/azure.cosmos.cosmosclientoptions?view=azure-dotnet-preview)
[SerializerOptions Property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.serializeroptions?view=azure-dotnet)
and [Serializer Property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.serializer?view=azure-dotnet) in the Microsoft.Azure.Cosmos namespace and the azure.cosmos namespace both have code snippets that are formatted like regular text:
![image](https://user-images.githubusercontent.com/7254163/92964142-a1a1ab80-f441-11ea-9c10-2fa1dcd9b4c0.png)
![image](https://user-images.githubusercontent.com/7254163/92963775-fe509680-f440-11ea-8720-81f91c44fc28.png)
![image](https://user-images.githubusercontent.com/7254163/92963820-11636680-f441-11ea-9988-16aaace3736a.png)

The associated docs in this repo don't seem to correctly parse these as code snippets -
https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml 
https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Cosmos/CosmosClientOptions.xml

The Azure.Cosmos docs do not wrap it in a `code` tag but the Microsoft.Azure.Cosmos namespace does. But neither are formatted correctly. If there is a convention to adding code snippets from these XML tags, I can add them in PR.

**Comment by jsquire** [comment]
@danieljurek:  This looks to be a tooling issue.   Would you please be so kind as to offer your thoughts?

**Comment by kexugit** [comment]
The recommended way is to use `<code>` inside `<example>`.

[Recommended XML documentation tags for a class and its members | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#example)

**Comment by kurtzeborn** [comment]
Thanks Ke!  Closing.
