### ISSUE TITLE
Remove "or sets" from https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.brokeredmessage.enqueuedtimeutc?view=azure-dotnet&source=docs

### ISSUE THREAD

**Issue by gewarren** [Azure/azure-sdk-for-net#18796]
---
**Issue moved from MicrosoftDocs/feedback#3215**
- Please respond to @jaslawinMs.

---

_From @jaslawinMs on Friday, October 23, 2020 10:58:47 PM_

**Describe the bug**
https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.brokeredmessage.enqueuedtimeutc?view=azure-dotnet&source=docs describes read only property, but the description reads "Gets or sets"

**To Reproduce**

**Expected behavior**
Remove "or sets"

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by axisc** [comment]
Will be refined when we release the next version of the .NET SDK.

cc: @DorothySun216 to make the edits to the docs.

**Comment by DorothySun216** [comment]
I have sent out a PR and we will release a .net framework SDK (WindowsAzure.Servicebus) reflecting the change soon.
A new .net core SDK (Microsoft.Azure.Servicebus 5.1.2) containing this fix is already out.
