### ISSUE TITLE
What does autocomplete actually do

### ISSUE THREAD

**Issue by boylec** [Azure/azure-sdk-for-net#18790]
I can't find documentation anywhere as to what autocomplete actually does for a session.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58bffeab-d9c9-3db1-02a0-f155e13cc343
* Version Independent ID: a65b7ee1-ec70-bba7-a569-4a645925cc0a
* Content: [SessionHandlerOptions.AutoComplete Property (Microsoft.ServiceBus.Messaging)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.sessionhandleroptions.autocomplete?view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceBus.Messaging/SessionHandlerOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus.Messaging/SessionHandlerOptions.xml)
* Service: **service-bus-messaging**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by axisc** [comment]
Here are some link that indicate the behavior of AutoComplete
   * [OnMessageOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.onmessageoptions.autocomplete?view=azure-dotnet)
   * [SessionHandlerOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.sessionhandleroptions.autocomplete?view=azure-dotnet#Microsoft_Azure_ServiceBus_SessionHandlerOptions_AutoComplete)

Hope this helps.
