### ISSUE TITLE
Documentation for epoch time unit in Store API is incorrect (should be milliseconds)

### ISSUE THREAD

**Issue by Ruin0x11** [Azure/azure-sdk-for-net#18792]
In the `Microsoft.Azure.Management.DataLake.Store.Models` namespace, the `FileStatusProperties.ModificationTime` property has this [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datalake.store.models.filestatusproperties.modificationtime?view=azure-dotnet#Microsoft_Azure_Management_DataLake_Store_Models_FileStatusProperties_ModificationTime):

> Gets the modification time as ticks since the epoch.

However the returned value is actually the number of _milliseconds_ since the epoch. It's likely the other docs referencing tick values are incorrect also.

**Comment by allenjzhang** [comment]
I looked over the current package version source there are no FileStatus anywhere to be found. Also this service SDK hasn't been updated from 3 years. Looks like this is obsolete.
