### ISSUE TITLE
[QUERY] Atomic blob upload with OpenWriteAsync() ?

### ISSUE THREAD

**Issue by hhermas** [Azure/azure-sdk-for-net#18797]
**Query/Question**
I'm using `OpenWriteAsync()` to write to a new block blob (around 30 MB).
If the program is terminated during upload, a blob with empty or zero ContentLength (created by the operation) is left behind in the container and is returned when querying blobs in the container, i.e. `containerClient.GetBlobs()`. 
Is this behavior expected? what are some ways or alternatives to make the upload operation atomic?

**Environment:**
Azure.Storage.Blobs 12.8.0

Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by kasobol-msft** [comment]
The `OpenWriteAsync` mimics [File.OpenWrite](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.openwrite?view=net-5.0#remarks) to some extent. I.e. it may leave partially written blob if application crashed in the middle of writting.
For atomic uploads I suggest to use [BlobClient.UploadAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet) .

**Comment by hhermas** [comment]
Thanks for your reply. 

I think I read somewhere that the blob client uses the `Put Block` and `Put Blob List` operations behind the scenes for the upload. My understanding is that the `Put Block` call would first create a new block blob with a content length of 0 (uncommitted state). This does not get committed until the client calls `Put Block List` on the new block(s) it uploaded earlier.
https://docs.microsoft.com/en-us/rest/api/storageservices/put-block

Now, `GetBlobs()` is _not_ supposed to return any uncommitted blobs unless one explicitly specifies `include=uncommittedblobs` in the parameters:
https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs

I'm wondering if there's a possible issue in GetBlobs() in this case?

**Comment by kasobol-msft** [comment]
That is correct. Upload will use `Put Block` and `Put Blob List` if input is large enough. You can use optional `BlobUploadOptions` parameter to set the threshold, i.e. `BlobUploadOptions.TransferOptions.InitialTransferSize`. If input is smaller that this then upload will use single `Put Blob` call.

However, it seem that `GetBlobs` won't return uncommitted blobs by default, therefore this might be sufficient for your scenario. Consider the following code:
```
            BlobServiceClient serviceClient = new BlobServiceClient(ConnectionString);
            var containerClient = serviceClient.GetBlobContainerClient("test-uncommited-blob");
            await containerClient.CreateIfNotExistsAsync();

            var blockBlobClient = containerClient.GetBlockBlobClient("test_blob");

            var bytes = new byte[1024];
            new Random().NextBytes(bytes);

            var blockId = Convert.ToBase64String(Guid.NewGuid().ToByteArray());

            await blockBlobClient.StageBlockAsync(blockId, new MemoryStream(bytes));

            Console.WriteLine("Block Uploaded");

            await foreach(var blobItem in containerClient.GetBlobsAsync())
            {
                Console.WriteLine($"Blob item: {blobItem.Name}");
            }

            Console.WriteLine("Finished");
```
prints:
```
Block Uploaded
Finished
```
I.e. blob is not visible until committed.

Other option is to use `BlockBlobClient.UploadAsync` which is just raw `Put Blob` operation. But I'd recommend to use `BlobClient.UploadAsync` if that suits your scenario.

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.

**Comment by EthanSK** [comment]
Is it possible to stream the data on the fly to uploadAsync? I wanted to use openwriteasync but it's not atomic, but uploadasync takes an existing stream as opposed to providing us with a stream to write to
