### ISSUE TITLE
[WebSites] SiteLoadBalancing enum members need detailed descriptions

### ISSUE THREAD

**Issue by nirnaymsft** [Azure/azure-sdk-for-net#18793]
In web app's SiteConfig.loadBalancing enum
Please explain internal working implementation of all Possible values include: 'WeightedRoundRobin', 'LeastRequests', 'LeastResponseTime', 'WeightedTotalTraffic', 'RequestHash'

and how this could change behaviour of Azure internal Routing to Instance.

As user has no way to route request to Instances, this property is very important to understand.

**Comment by allenjzhang** [comment]
Routing to Service team for detailed explanations.

**Comment by SaurabhSharma-MSFT** [comment]
@nirnaymsft Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still looking for assistance on this query? Please let us know .

**Comment by ptjuanramos** [comment]
Can we open again this issue? The explanation is really important
