### ISSUE TITLE
Design for preview.3 features

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#18805]
https://github.com/Azure/azure-rest-api-specs/pull/12997

- [ ] Regenerate code from new swagger.
- [ ] Support page range selection for custom and prebuilt model recognition.
- [ ] Support new Reading Order feature for content recognition.
- [ ] Add tests for BMP images.
- [ ] Support new ID document recognition API.

**Comment by maririos** [comment]
Features won't be deployed until middle of March, so moving milestones

**Comment by kinelski** [comment]
Created a new issue for each feature, so closing this one.
