### ISSUE TITLE
ResourceSkuCosts not populating

### ISSUE THREAD

**Issue by RonniePitts** [Azure/azure-sdk-for-net#18826]
How is the ResourceSkuCosts populated via the ResourceSku.

Currently this isn't returned in the json output.

Thanks
Ron

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by Drewm3** [comment]
The various resource costs are provided via a separate set of APIs that are common for all of Azure. Please see the following documentation for these APIs: https://docs.microsoft.com/en-us/rest/api/cost-management/retail-prices/azure-retail-prices.
