### ISSUE TITLE
Bootstrapping ListBlobsSegmentedAsync's currentToken argument

### ISSUE THREAD

**Issue by chwarr** [Azure/azure-sdk-for-net#18824]
All of the `CloudBlobDirectory.ListBlobsSegmentedAsync` overloads take a `BlobContinuationToken currentToken` argument. This is documented as "A continuation token returned by a previous listing operation.". Can this documentation be updated to address how to start listing when I don't yet have a continuation token? E.g., should I pass `null`? `new BlobContinuationToken()`? something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6cc800-331f-7132-d9b7-e3ac59ba5d94
* Version Independent ID: 04716976-30f5-bf72-82d4-60ef68d76cb3
* Content: [CloudBlobClient.ListBlobsSegmentedAsync Method (Microsoft.Azure.Storage.Blob) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblobclient.listblobssegmentedasync?view=azure-dotnet-legacy)
* Content Source: [xml/Microsoft.Azure.Storage.Blob/CloudBlobClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.Blob/CloudBlobClient.xml)
* Service: **storage**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by amnguye** [comment]
This documentation is from our deprecated library. The documentation is generated from our XML comments in that deprecated repo and namespace: https://github.com/Azure/azure-storage-net

We are not looking to update anything from that repo unless there's a data integrity or security issue.
See https://github.com/Azure/azure-storage-net#support-statement
