### ISSUE TITLE
[BUG] Kudu has constant errors when trying to access from the portal (403/500) but web app is available

### ISSUE THREAD

**Issue by LukeBolly** [Azure/azure-sdk-for-net#18842]
**Describe the bug**
Attempting to access the kudu console via the App Service portal results in either 403 Web App Stopped or 500 Unavailable errors.

I know this definitely isn't the right place, but I can't for the life of me figure out where to report a bug for Kudu inside the portal. Let me know and I'll make the issue elsewhere.

**Expected behavior**
Kudu console should work.

**Actual behavior (include Exception or Stack Trace)**
Error 403 - This web app is stopped.
The web app you have attempted to reach is currently stopped and does not accept any requests. Please try to reload the page or visit it again soon.

**To Reproduce**
1. Go to Azure Portal
2. Click on App Service. Click on Advanced Tools in side blade. Click Go ->

**Environment:**
 - Azure App Service: .NET Core 3.1
 - Web Deploy from Visual Studio 16.8.5

**Comment by Mohit-Chakraborty** [comment]
Hi,
  I think you want the [kudu repo](https://github.com/Azure/kudu) on GitHub.
