### ISSUE TITLE
KeyVault Docs: missing private key sample 

### ISSUE THREAD

**Issue by iricigor** [Azure/azure-sdk-for-net#18847]
Remark section says:
_This property contains only the public key. If you must retrieve the key pair including the private key instead of performing cryptographic operations in Azure Key Vault, see the sample:_

But, there is no sample...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2c7ead4-7dcc-3149-ca5e-7543eaca58ff
* Version Independent ID: b5c97c78-2cbc-d103-4d63-b76e433c8625
* Content: [KeyVaultCertificate.Cer Property (Azure.Security.KeyVault.Certificates) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.certificates.keyvaultcertificate.cer?view=azure-dotnet#Azure_Security_KeyVault_Certificates_KeyVaultCertificate_Cer)
* Content Source: [xml/Azure.Security.KeyVault.Certificates/KeyVaultCertificate.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Security.KeyVault.Certificates/KeyVaultCertificate.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
@danieljurek: This appears to be a tooling problem when transforming the doc comments.    The page renders without a samples link:

![image](https://user-images.githubusercontent.com/913445/108364494-1d0f4200-71c4-11eb-8fcd-82a84a504d12.png)

The [source](https://github.com/Azure/azure-sdk-for-net/blob/65b19a062e246ceb283f89edefe4bc436d31f1e7/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/KeyVaultCertificate.cs#L65), however, links to the sample in a valid `<see>` element:

```xml
        /// <summary>
        /// Gets the CER formatted public X509 certificate.
        /// </summary>
        /// <remarks>
        /// This property contains only the public key.
        /// If you must retrieve the key pair including the private key instead of performing cryptographic operations in Azure Key Vault, see the sample:
        /// <see href="https://docs.microsoft.com/samples/azure/azure-sdk-for-net/get-certificate-private-key"/>
        /// </remarks>
        public byte[] Cer { get; internal set; }
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
There were changes made to the render and this is fixed:

![image](https://user-images.githubusercontent.com/1532486/118568406-9ddecb00-b72c-11eb-9188-1a9ea208236b.png)
