### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by DonFrazier** [Azure/azure-sdk-for-net#18841]
Typo: Evalutates

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 994c402a-0c34-a387-5592-2416ccf31fa9
* Version Independent ID: b79fa1da-b462-eb14-d2c2-00d987bd0ecf
* Content: [IFeatureFilter Interface (Microsoft.FeatureManagement) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.featuremanagement.ifeaturefilter?view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.FeatureManagement/IFeatureFilter.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.FeatureManagement/IFeatureFilter.xml)
* Service: **azure-app-configuration**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Mohit-Chakraborty** [comment]
Hi,
  I looked into it. The component lives in the [FeatureManagement-Dotnet](https://github.com/microsoft/FeatureManagement-Dotnet/pull/99/files) repo.

Looks like the typo was [fixed](https://github.com/microsoft/FeatureManagement-Dotnet/commit/1a66739bc4f97b503674c7a3b3d4760762efa676) on October 1st, but the [latest release](https://github.com/microsoft/FeatureManagement-Dotnet/releases/tag/2.2.0) is from September 16.

So, the change is not yet available.
