### ISSUE TITLE
[BUG] Azure.Extensions.AspNetCore.Configuration.Secrets with DefaultAzureCredential seemingly ignores tenant

### ISSUE THREAD

**Issue by joukevandermaas** [Azure/azure-sdk-for-net#18845]
**Describe the bug**
We use guest accounts in the tenant that contains our azure subscription for various reasons. Generally speaking all azure tools support taking a tenant id so we can still authenticate properly.

We upgraded from `Microsoft.Extensions.Configuration.AzureKeyVault` to the new `Azure.Extensions.AspNetCore.Configuration.Secrets`. We replaced a line like this:

```csharp
builder.AddAzureKeyVault(myKeyvault);
```

with this:

```csharp
builder.AddAzureKeyVault(new Uri(myKeyvault), new DefaultAzureCredential());
```

We're now getting errors of this form:

>   ----> Azure.RequestFailedException : Service request failed.
>   Status: 401 (Unauthorized)
>   Content:
>    {"error":{"code":"Unauthorized","message":"AKV10032: Invalid issuer. Expected one of https://sts.windows.net/[tenantid for azure subscription]/, found https://sts.windows.net/[tenant id for home tenant of guest account]/."}}

This is after having logged in to azure using `az login --tenant [tenant for azure subscription]`.

The old package supported this scenario of logging in with a different tenant than the home tenant for the user, the new one apparently doesn't.

**Expected behavior**
The package uses the same tenant I logged into using the azure cli.

**Actual behavior (include Exception or Stack Trace)**
The package uses the "home" tenant for my user account (which doesn't contain an azure subscription). See above for the error message.

**To Reproduce**
See above for details.

1. Sign into azure cli using a guest account, specifying the tenant (`az login --tenant [tenant in which you are guest account]`).
2. Try use `DefaultAzureCredential` to add keyvault to the configuration builder.
3. Result: error saying "invalid issuer".

**Environment:**
 - Name and version of the Library package used: Azure.Extensions.AspNetCore.Configuration.Secrets 1.0.2
 - Hosting platform or OS and .NET runtime version: Windows 10 and net472
 - IDE and version: Visual Studio 16.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by jsquire** [comment]
@schaabs, @christothes:  This seems to be related to the flow in `Azure.Identity`.   Would you please offer your thoughts?

**Comment by christothes** [comment]
@joukevandermaas For your scenario, are you always expecting the same tenantId? If so,  if you specify the tenantId, does it work as expected? This can be done in code with the `SharedTokenCacheTenantId` or by setting the `AZURE_TENANT_ID` environment variable.

https://github.com/Azure/azure-sdk-for-net/blob/72d4c479d82a7f71fd5b40dccf736ce96d9ec6a4/sdk/identity/Azure.Identity/src/DefaultAzureCredentialOptions.cs#L28

**Comment by joukevandermaas** [comment]
@christothes yes, we do always use the same tenant id in this project. I tried your suggestion and that does work. So that's a good solution for us. Thanks for the super quick reply.

I am not sure if the issue should be closed, feel free to do so if the original description is expected behavior.
