### ISSUE TITLE
Ability to add dependent jars and tags to batch jobs submitted via the C# SDK

### ISSUE THREAD

**Issue by ksiomelo** [Azure/azure-sdk-for-net#18866]
Azure.Analytics.Synapse.Spark.Models.SparkBatchJobOptions.Jars|Tags are read-only in the 
Azure.Analytics.Synapse.Spark SDK 1.0.0 for C#.

![image](https://user-images.githubusercontent.com/362411/108429731-3977a280-71f5-11eb-8bc9-81793a4887e0.png)

This is supported in the Java port of the SDK.

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by idear1203** [comment]
@ksiomelo , it is readonly so you cannot assign it to a new list. However, you can use `Add` method to modify its content.
e.g. `SparkJobOptions.Tags.Add`
