### ISSUE TITLE
[BUG][Microsoft.Azure.ServiceBus] AmqpExceptionHelper.GetClientException throws System.FormatException

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-sdk-for-net#18873]
**Describe the bug**
We got following exception while receiving messages.
```
System.AggregateException: One or more errors occurred. (Input string was not in a correct format.)
 ---> System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.Text.StringBuilder.AppendFormat(IFormatProvider provider, String format, Object[] args)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpExceptionHelper.GetClientException(Exception exception, String referenceId, Exception innerException, Boolean connectionError)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass64_0.<<ReceiveAsync>b__0>d.MoveNext()
```

It seems AmqpExceptionHelper.GetClientException throws new exception while formatting the original exception.
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Amqp/AmqpExceptionHelper.cs#L178

**To Reproduce**
It happens randomly.

**Environment:**
 - Name and version of the Library package used
 Microsoft.Azure.ServiceBus 5.1.0
 - Hosting platform or OS and .NET runtime version
.NET Core 3.1 in Linux Container

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by zhiweiv** [comment]
BTW, there is same logic in https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpExceptionHelper.cs#L187.

**Comment by JoshLove-msft** [comment]
We recently fixed this in the new library - https://github.com/Azure/azure-sdk-for-net/pull/22630

**Comment by zhiweiv** [comment]
Thanks for the update, we have switched to Azure.Messaging.ServiceBus, so it should be fine now.

BTW, any plan to fix it in Microsoft.Azure.ServiceBus aslo? If not I will close this.

**Comment by KozakSergii** [comment]
Hi we have the same problem with Microsoft.Azure.ServiceBus nuget, will be fix applied to it?

**Comment by zhiweiv** [comment]
The new SDK Azure.Messaging.ServiceBus has got fixed, the Microsoft.Azure.ServiceBus is marked as deprecated and will only receive critical bug fixes, I guess this fix will not ported to Microsoft.Azure.ServiceBus.
