### ISSUE TITLE
Tagging resources in Azure using .Net 

### ISSUE THREAD

**Issue by nads205** [Azure/azure-sdk-for-net#18879]
**Query/Question**
Are there any examples of being able to tag resources in Azure using the **Azure.ResourceManager.Resources** libraries?
Is this the best library to use given it is currently in preview? There appears to be [other libraries](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/resources/management?view=azure-dotnet) that can also tag resources: 

- [Microsoft.Azure.Management.ResourceManager.Fluent](https://github.com/Azure-Samples/resources-dotnet-manage-resource)

The example code includes tagging of a [resource group](https://github.com/Azure-Samples/azure-samples-net-management/blob/432602f2bee2f240aea4b508571a36ac24949853/samples/resources/manage-resource-group/Program.cs), but would like to see examples of tagging all types of taggable resources in Azure via .Net code.

**Environment:**
 - Name and version of the Library package used: [Azure.ResourceManager.Resources/1.0.0-preview](https://www.nuget.org/packages/Azure.ResourceManager.Resources/1.0.0-preview.2)
 - Hosting platform or OS and .NET runtime version: Windows 10. Dot net core 3.1.
 - IDE and version : Visual Studio 2019 ide version: 16.8.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
**Microsoft.Azure.Management.Resources**. does not have a centralized tag update method. Instead, Tags are properties on each of the resources. By updating the Tags property and then with the usual `CreateOrUpdate/Update()` on the resource, tags will be updated.

Here are some examples:

https://github.com/Azure/azure-sdk-for-net/blob/2d2adffee576ea533b5219ede0cdafb8aae9c162/sdk/compute/Microsoft.Azure.Management.Compute/tests/DiskRPTests/DiskRPTestsBase.cs#L75

https://github.com/Azure/azure-sdk-for-net/blob/2d2adffee576ea533b5219ede0cdafb8aae9c162/sdk/synapse/Microsoft.Azure.Management.Synapse/tests/ScenarioTests/WorkspaceOperationTests.cs#L43

Let me know if they have additional questions.

**Comment by allenjzhang** [comment]
`
