### ISSUE TITLE
HDinsight: cannot configure http settings - MethodNotAllowed

### ISSUE THREAD

**Issue by ailn** [Azure/azure-sdk-for-net#1887]
Using latest SDK package and when trying to call 
`hdinsightClient.Clusters.ConfigureHttpSettings(...)`
I get 

```
{
  "code": "MethodNotAllowed",
  "message": "Exception of type 'Microsoft.ClusterServices.RDFEProvider.ResourceTypes.Models.RdfeResourceHandlerException' was thrown."
}
```

This looks like service issue not client though...

**Comment by RoelantStegmann** [comment]
Same error (with Azure CLI on linux) but when trying to delete the cluster

**Comment by AlicewD** [comment]
Same exception but a "InternalServerError", while creating HDinsight cluster. Has anyone found the solution?

**Comment by AbhiMadav** [comment]
I run into this when there are multiple delete requests (for different clusters) in different threads.

**Comment by tylerfox** [comment]
ClusterOperationsExtensions.ConfigureHttpSettings is now deprecated and has been replaced by ClusterOperationsExtensions.UpdateGatewaySettings. Please see our documentation for more information: [Migrate to granular role-based access for cluster configurations](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-migrate-granular-access-cluster-configurations)
