### ISSUE TITLE
Error while using Azure.Messaging.ServiceBus library for Service bus trigger function

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-sdk-for-net#18886]
Azure.Messaging.ServiceBus 7.1.0
Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.2.1
Microsoft.NET.Sdk.Functions 3.0.11
Azure Cloud.
Windows/Linux
VS 2019

Hello
I have an Azure function, with a Service Bus trigger, 

using Azure.Messaging.ServiceBus;
public static void Run(ServiceBusReceivedMessage myQueueItem, ILogger log, Microsoft.Azure.WebJobs.ExecutionContext context) {..}

Is that supported? The [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp#usage) says that it should be used Microsoft.Azure.ServiceBus libray, but I need to used the newest libray.
The code throws an error so it doesn't seem to be supported..

Binding parameters to complex objects (such as 'ServiceBusReceivedMessage') uses Json.NET serialization or XML object serialization. 1. If ContentType is 'application/json' deserialize as JSON 2. If ContentType is not 'application/json' attempt to deserialize using Message.GetBody, which will handle cases like XML object serialization 3. If this deserialization fails, do a final attempt at JSON deserialization to catch cases where the content type might be incorrect The JSON parser failed: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.

Thanks.

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
Hi @sjuarezgx.  Thank you for reaching out and we regret that you're experiencing difficulties.  The current version of the Azure Functions bindings use the `Microsoft.Azure.ServiceBus` library internally.   The trigger is going to pass your function a Service Bus messages typed as `Microsoft.Azure.ServiceBus.Message` as a result.  You're welcome to use `Azure.Messaging.ServiceBus` in the body of your function, but you'd have to map messages and other types between the libraries to do so.    There is work in progress to update the bindings to use the current Service Bus client library, but I don't have a timeframe to share at present for when that may be released.  

May I ask why you feel that you need to use `Azure.Messaging.ServiceBus` in this case?   The two libraries are compatible in that you can send a message using one version of the library and read it using the other version of the library.

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by sjuarezgx** [comment]
Hello. 
Thank you very much for your feedback.
It tried to get all the metadata information of a message sent using the new package, from the function (which uses the old package) and it seemed to work. That is, I could get the Application Properties although the function uses the old SDK.

**Comment by j2jensen** [comment]
Just as an update, the documentation linked to in this issue [now says](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp#additional-types):

> Apps using the 5.0.0 or higher version of the Service Bus extension use the ServiceBusReceivedMessage type in Azure.Messaging.ServiceBus instead of the one in the Microsoft.Azure.ServiceBus namespace. This version drops support for the legacy Message type in favor of the following types:
> - ServiceBusReceivedMessage

**Comment by Prinsn** [comment]
> May I ask why you feel that you need to use Azure.Messaging.ServiceBus in this case?

Just want to really highlight this comment, as of now, this is an irrelevant statement with .NET 6, which expects you to use Azure.Messaging.ServiceBus
