### ISSUE TITLE
[BUG] [Critical] Azure.Storage.Blobs Stream created by using BlockBlobClient.OpenWrite outputs invalid data

### ISSUE THREAD

**Issue by yahorsi** [Azure/azure-sdk-for-net#18884]
**Describe the bug**
After migrating from the V11 to the V12 stream, that is created using  BlockBlobClient.OpenWrite produces incorrect output.
Exactly the same code works fine with streams made from the file or from the V11 SDK.

I did manage to create small repo where the issue could be reproduced.
https://github.com/yahorsi/BlobBlokClientOpenWriteBug

I tried both V11 and file-based stream and the code works just fine, the problem reproduces only on the V12.

**Expected behavior**
The stream made by calling BlockBlobClient.OpenWrite operates same way as file stream of the one from V11

**Actual behavior (include Exception or Stack Trace)**
The stream made by calling BlockBlobClient.OpenWrite outputs invalid data.

**To Reproduce**
https://github.com/yahorsi/BlobBlokClientOpenWriteBug

**Environment:**
Windows 10
Core 3.1
Azure.Storage.Blobs 12.8.0

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by yahorsi** [comment]
Seems like setting BlockBlobOpenWriteOptions.BufferSize = 1 solves the issue. So must be something related to the buffering

**Comment by yahorsi** [comment]
The problem seems in the BlockBlobWriteStream, we get 2 same BlockId's and the code below is simply not valid:

```C#
        protected override async Task AppendInternal(bool async, CancellationToken cancellationToken)
        {
            if (_buffer.Length > 0)
            {
                _buffer.Position = 0;

                // 140 + 4
                // 142 + 2
                string blockId = StorageExtensions.GenerateBlockId(_position + _buffer.Length);

                Debug.WriteLine(blockId);

               // Deleted
            }
        }
```

The reason it is not correct is. Imagine you write
100 bytes
50 bytes
25 bytes


So, you have
1. _position = 100, _buffer.Length = 100, so sum = 200
2. _position  = 150, _buffer.Length = 50, so sum = 200
3. _position  = 175, _buffer.Length = 25, so sum = 200

In these 3 cases, generated Id will be the same

**Comment by yahorsi** [comment]
Guys this is a critical bug with a very simple repo that is causing data corruption. Any chance it will be fixed soon?

**Comment by amnguye** [comment]
Sorry for the delay. I was attempting to investigate your issue and I think I was able to reproduce your issue. You're correct, the calculation of the blockIds is off and causing it to be overwritten. I will update the thread once more investigation is given how we can better the blockId calculation.

**Comment by yahorsi** [comment]
@amnguye Thank you for the update. 

So far, this is very critical as causing random data corruption. The fix is IMHO very simple, just use _position to generate the block Id. At the point,AppendInternal is called _position contains the amount of data flushed plus current buffer so just by leaving _position we will achieve what author wanted to achieve...

**Comment by amnguye** [comment]
Hi, if you feel that is the root cause issue you are free to create a PR and propose the fix. Elsewise I will continue the investigation to  ensure that the fix we put in place is the correct fix to make. Thanks for your patience.

**Comment by yahorsi** [comment]
Guys, any update on when to expect beta2? It's been reported 14 days ago and this is really critical one

**Comment by yahorsi** [comment]
Any info on when beta2 will be available? Our clients getting hurt hard by this, are there any instructions on how we can build it locally?
