### ISSUE TITLE
[FEATURE REQ] Azure.Messaging.ServiceBus please make EntityNameFormatter public

### ISSUE THREAD

**Issue by joshdean2000** [Azure/azure-sdk-for-net#18891]
**Library or service name.**
Azure.Messaging.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
EntityNameFormatter has been set to internal only please make it a public class? 

This means can continue to use it to format entity names like previous libraries.

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @joshdean2000,
Any chance you can give an example of how you would use the EntityNameFormatter in the new library?

**Comment by joshdean2000** [comment]
This already exists what I want is access to it.

Example 1: Can validate entity names before attempting to create using the validation functions.
 - EntityNameFormatter.CheckValidQueueName("MyQueueName");
Example 2: Can generate deadletter queue path to be consistent with code using older sdks.
 - var deadletterPath = EntityNameFormatter.FormatDeadLetterPath("MyQueuePath");

**Comment by JoshLove-msft** [comment]
So for the DeadLetter scenario, you can create a dead letter receiver in this way:
```cs
ServiceBusReceiver dlqReceiver = client.CreateReceiver(queueName, new ServiceBusReceiverOptions
{
    SubQueue = SubQueue.DeadLetter
});
ServiceBusReceivedMessage dlqMessage = await dlqReceiver.ReceiveMessageAsync();
```
You wouldn't need to format the dead letter path yourself.

In terms of `CheckValidQueueName`, the library will use this method internally when you attempt to set the Name property in the `CreateQueueOptions`. However, you wouldn't be able to proactively call it when working through a set of potential queue names. Is this what you were doing with the previous library?

**Comment by joshdean2000** [comment]
In our existing code we are not using the SDK code to validate names before, we had to write custom code.  I was just hoping we could remove that logic and use this code so it's the same everywhere.  These names are then stored in database so not creating client at that time.

In existing code we are using the EntityNameHelper which is now replaced by EntityNameFormatter for getting the Subscription paths and DeadLetter paths for logging purposes before we actually create the clients.  We are also using it in exceptions we generate.

**Comment by JoshLove-msft** [comment]
> In our existing code we are not using the SDK code to validate names before, we had to write custom code. I was just hoping we could remove that logic and use this code so it's the same everywhere. These names are then stored in database so not creating client at that time.

Got it, thanks for the explanation.

> In existing code we are using the EntityNameHelper which is now replaced by EntityNameFormatter for getting the Subscription paths and DeadLetter paths for logging purposes before we actually create the clients. We are also using it in exceptions we generate.

Once you actually create the clients, you can get the paths from the EntityPath property on the clients. The idea is that you wouldn't need to format the paths yourselves, but rather the SDK would do it for you. But I understand this only helps if you are able to create the clients first.

**Comment by ramya-rao-a** [comment]
@JoshLove-msft Can you bring this up in our next meeting? And if we want to mark this as a valid feature request, please add the right labels and milestone
