### ISSUE TITLE
FormRecognizerClientOptions shouldn't suggest 3.1 SDK can target 2.0 service version

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#18908]
Currently there is a bug in the [FormRecognizerClientOptions](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClientOptions.cs#L23) class which suggest that the user can target either 2.0 or 2.1 service version, when after 3.1 version of the SDK, we can only target 2.1. => swagger generation.
We should find a way to communicate with the user that 3.1 only targets 2.1 service version. 
Maybe we shouldn't receive the service version as parameter and instead always instantiate it in the constructor?

**Comment by kinelski** [comment]
After investigating we figured out this can be fixed with swagger transforms. We currently have a PR open for that (https://github.com/Azure/azure-sdk-for-net/pull/19085), but it still needs proper testing. Follow-up issue: https://github.com/Azure/azure-sdk-for-net/issues/19132.
