### ISSUE TITLE
RecordedTest attribute indicates test was re-recorded when it wasn't

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#18903]
If some of the Event Grid tests fail on playback and needs to be re-recorded, the output indicates that it was re-recorded successfully, but no new session record appears.

**Comment by JoshLove-msft** [comment]
The issue turned out to be the tests weren't actually re-recorded because the RecordMatcher thought they were equivalent to the previous session. We should probably update the output in this case to say the test was not recorded.

**Comment by christothes** [comment]
@JoshLove-msft Do you know the sequence of events that causes this scenario? It's not clear why we'd attempt a re-record or think that a re-record occurred unless the first run of the test ended with a status other than `Passed` or `Skipped`.

**Comment by JoshLove-msft** [comment]
Yes the first test failed, so a re-record was initiated, but then we ended up not re-recording because there was an existing session record - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.TestFramework/src/TestRecording.cs#L181

**Comment by JoshLove-msft** [comment]
@pakrym is the equivalence check working this way by design? Is it intended that a test that fails to match in playback would match in the IsEquivalent call? My understanding is that IsEquivalent is meant to shield against a bunch of extra recordings. Now that we have RecordedTestAttribute available, is this still valuable?

**Comment by pakrym** [comment]
> it intended that a test that fails to match in playback would match in the IsEquivalent call? 

No, this shouldn't happen. Do you know why IsEquivalent was more permissive?

> My understanding is that IsEquivalent is meant to shield against a bunch of extra recordings

Correct.

> Now that we have RecordedTestAttribute available, is this still valuable?

Not everyone is using the `RecordedTestAttribute`. In particular storage tests were the main reason we've added the `IsEquivalent`

**Comment by JoshLove-msft** [comment]
> No, this shouldn't happen. Do you know why IsEquivalent was more permissive?

IsEquivalent doesn't seem to check the request content - only the headers, URI, and request method.

**Comment by pakrym** [comment]
That would do it.

**Comment by JoshLove-msft** [comment]
If IsEquivalent is not supposed to be more permissive, why do we have it?

**Comment by pakrym** [comment]
Imagine you are re-recording a test that was already passing in playback. The goal is to avoid writing another recording. You are right that it's a poor man's `RecordedTestAttribute`.

**Comment by JoshLove-msft** [comment]
> Imagine you are re-recording a test that was already passing in playback. The goal is to avoid writing another recording. You are right that it's a poor man's `RecordedTestAttribute`.

If it was passing in playback, then using the same playback matching to determine whether to re-record would result in it not being re-recorded.

**Comment by pakrym** [comment]
Two recordings can both pass playback but not be the same when matched 1:1. Dates, IDs, ETags change between recordings.
