### ISSUE TITLE
Generate code from swagger

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#18914]
What each language may still need in convenience layer
- [x] pageable. The `link` value returned by the service is not in the form that expected by the generated `getXxxxNext()` method. We still need to parse the value to extract the part we need. Example TS code: https://github.com/Azure/azure-sdk-for-js/blob/4bdce8c1cce1303bbae0a52efd59085524d2d881/sdk/containerregistry/container-registry/src/utils.ts
  - Tracking this via: https://github.com/azure/azure-sdk-for-net/issues/19392
- [x] ManifestsDeleted and TagsDeleted should be get-only.
  - Tracking this via: https://github.com/azure/azure-sdk-for-net/issues/19547
- [x] `GetTags()` should return a list of `TagProperties`, and `GetRegistryArtifacts()` should return a list of `RegistryArtifactProperties`
  - We don't have a good solution to inject properties into array elements via transformation. So we have to do the transformation in convenience layer. Example TS code: https://github.com/Azure/azure-sdk-for-js/blob/4bdce8c1cce1303bbae0a52efd59085524d2d881/sdk/containerregistry/container-registry/src/containerRepositoryClient.ts#L475-L480
  - Tracking this via: https://github.com/azure/azure-sdk-for-net/issues/19547

**Comment by annelo-msft** [comment]
Closed via: https://github.com/Azure/azure-sdk-for-net/pull/19696
