### ISSUE TITLE
Address Arch Board feedback

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#18919]
This includes considerations we're tracking with the service as well as direct client API issues.

**Comment by annelo-msft** [comment]
Created work items per: https://github.com/azure/azure-sdk/issues/2514

**Comment by annelo-msft** [comment]
@AlexGhiondea I am moving this to May since we'll do most of this work then.

**Comment by annelo-msft** [comment]
Closing this since we're addressing issues filed in https://github.com/Azure/azure-sdk/issues/2514 directly.
