### ISSUE TITLE
[Service Bus] Mention the replacement for EntityNameHelper in the migration guide

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#18921]
In `Microsoft.Azure.ServiceBus`, we had the `EntityNameHelper` which got used for a few different purposes. It is not covered in the [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md) as to what one would need to do in `Azure.Messaging.ServiceBus` in these cases. 

From https://github.com/Azure/azure-sdk/issues/2463#issuecomment-783603803

**Comment by JoshLove-msft** [comment]
We can add a section to the migration guide to explain this.

**Comment by Mossharbor** [comment]
for anybody that comes here this sample:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/DeadLetterQueue/Program.cs
around line 168 shows what to do to get to the dead letter queue

**Comment by jsquire** [comment]
The pattern for reading from dead-letter and other subqueues is covered in a migration guide sample.
