### ISSUE TITLE
[BUG] Connection String parsing fails in Azure.Data.Tables TableClient and TableServiceClient

### ISSUE THREAD

**Issue by OQO** [Azure/azure-sdk-for-net#18949]
**Describe the bug**
The Azure.Data.Tables library (TableConnectionString) does not correctly parse connections strings if they do not have a TableEndpoint and do not have a EndpointSuffix

**Expected behavior**
The same connection string parses just fine when used for accessing blobs (BlobClient etc.). The blob libraries just use the default EndpointSuffix (core.windows.net)

**Actual behavior (include Exception or Stack Trace)**
Exception is thrown in TableConnectionString

**To Reproduce**
Pass a connection string to TableClient or TableServiceLCinet etc. that does not have a TableEndpoint nor an EndpointSuffix.

**Environment:**
 - Azure.Data.Tables 3.0.0-beta.5
 - .net Core 5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @OQO - I'm curious where you would get a connection string that does not contain the `EndpointSuffix`. For example, the one created in the portal includes it. 

Since the endpoint suffix could be different outside of the standard Azure public cloud, I'm wondering if we should default it or keep the current behavior.

**Comment by OQO** [comment]
@christothes Good question, I don't remember. We have many of those in this format for many years.

Note that the documentation implies that EndpointSuffix is optional (https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string). See _Configure a connection string for an Azure storage account_ setion: It gives this as an example: `DefaultEndpointsProtocol=[http|https];AccountName=myAccountName;AccountKey=myAccountKey`. EndpointSuffix is only explained further down the page as an optional parameter to be used for non-default Azure locations.

The old Storage SDK (tested for blobs, tables and queues) did support this format and would automatically infer the default EndpointSuffix (core.windows.net) if no specific endpoints were provided and if no EndPointsuffix was provided. 

The new Storage SDk does support a connection string without EndPointsuffix (and endpoints) for both blobs ( BlobClient etc. in Azure.Storage.Blobs) and queues (QueueClinet etc. in Azure.Storage.Queues). It also just uses the default core.windows.net in that case. That is why it was very surprising when this same connection string led to exceptions in TableClient in Azure.Data.Tables.

> Since the endpoint suffix could be different outside of the standard Azure public cloud, I'm wondering if we should default it or keep the current behavior.

It would feel more consistent across the Azure .net SDK if the behavior regarding connection string parsing would be consistent. It feels strange if the same connection string (`DefaultEndpointsProtocol=[http|https];AccountName=myAccountName;AccountKey=myAccountKey`) does work for blobs and queues, but not for tables. I think changing the behavior for blobs and queues would probably break things for many people. So from my perspective making tables behave the same as blobs and queues seems recommended but of course I am not an Azure SDK design expert so maybe there are other arguments. 

Also in general most new version of SDKs have been developed such that old connection strings still work with new versions of SDKs. See for example also SQLServerClient. Breaking backward compatibility for connection strings should be a higher hurdle than breaking the APIs of the SDK. Connection strings are usually stored separately in production and having non-backward compatible changes can easily break production without it being caught during testing.

**Comment by christothes** [comment]
@OQO Thanks for the discussion. I agree that making this behavior consistent is best.

**Comment by OQO** [comment]
@christothes You're welcome. Thanks for all your efforts on this library. Looking forward to seeing it fully released!

**Comment by isaacabraham** [comment]
@christothes good to see this fixed - this one caught us out today! We are generating our connection strings from ARM templates and many of the samples for that don't use the Endpoint suffix, so I could have imagined this catching out a lot of people when upgrading.

Cheers
