### ISSUE TITLE
[QUERY] Using BlobRequestOptions.SingleBlobUploadThresholdInBytes in Azure.Storage.Blobs

### ISSUE THREAD

**Issue by WillRock19** [Azure/azure-sdk-for-net#18940]
**Question**
We've been using the Microsoft.WindowsAzure.Storage.Blob version 9.3.2.0 and used a **BlobRequestOptions** to set the property **SingleBlobUploadThresholdInBytes** in our **CloudBlobClient** as follows:

```csharp

public void SomeMethod()
{
     var container = GetContainer(connectionString, containerName, new BlobRequestOptions
      {
          SingleBlobUploadThresholdInBytes = 2 * 1024 * 1024
      });
}

private CloudBlobContainer GetContainer(string connectionString, string containerName, BlobRequestOptions blobRequestOptions)
{
            CloudStorageAccount storageAccount  = CloudStorageAccount.Parse(connectionString);
            CloudBlobClient client = storageAccount.CreateCloudBlobClient();
            client.DefaultRequestOptions = blobRequestOptions;
        
        //Do something more...        
 }
````

Now we are making the migration of the library *Microsoft.WindowsAzure.Storage.Blob 9.3.2.0* to *Azure.Storage.Blobs v12.8.0* and I can't manage to find an equivalent to this configuration. How can I still do this now? 

**Environment:**
 
 - .Net Version: *Full Framework 4.8*
 - Original version: **Microsoft.WindowsAzure.Storage.Blob 9.3.2.0**
 - New version: **Azure.Storage.Blobs v12.8.0**
  - IDE and version : *Visual Studio 16.8.5*

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
I don't believe we have an equivalent in v12. @seanmcc-msft please correct me if I'm wrong. Did you want to ask for a feature request of this in v12?

**Comment by seanmcc-msft** [comment]
Hi @WillRock19, in v12, this is a parameter you set per API call.
```
Stream content = ...;
BlobClient blobClient = new BlobClient(...);
BlobUploadOptions options = new BlobUploadOptions
{
    TransferOptions = new StorageTransferOptions
    {
        InitialTransferSize = 2 * 1024 * 1024,
        MaximumTransferSize = 2 * 1024 * 1024
    }
};
await blobClient.UploadAsync(content, options);
```

-Sean

**Comment by WillRock19** [comment]
Hi @seanmcc-msft, thank you very much for the answer!

I'm gonna try this and let you guys know if everything worked fine. I have another question tough:

In the *Microsoft.WindowsAzure.Storage* way, I could get a Sas Token using the following code:

```csharp
public string GetSASToken(string connectionString, string containerName, string blobName, SharedAccessBlobPermissions permissions, Enums.StorageSharedAccessExpiryTimeMinutes storageSharedAccessExpiryTimeMinutes)
{
    var container = GetContainer(connectionString, containerName);
    CloudBlockBlob blockBlob = container.GetBlockBlobReference(blobName);

    var policy = new SharedAccessBlobPolicy
    {
        Permissions = permissions
    };

    if (storageSharedAccessExpiryTimeMinutes != Enums.StorageSharedAccessExpiryTimeMinutes.Infinite)
    {
        policy.SharedAccessExpiryTime = DateTime.UtcNow.AddMinutes((int)storageSharedAccessExpiryTimeMinutes);
    }
    else
    {
        policy.SharedAccessExpiryTime = DateTime.MaxValue.AddYears(-1);
    }

    var sasToken = container.GetSharedAccessSignature(policy);

    return sasToken;
}
```

This original method returns only the parameters from a Sas URI, like *?sv=2018-03-28&sr=c&sig=C%2FKtDSnwdrkVkGezbJ7A%2BINUEILRGqTHl3YlPUiPXgw%3D&se=2021-03-03T12%3A34%3A39Z&sp=a*. Now, I know that I can create a BlobSasUri using the *BlobSasBuilder* as follows: 

```csharp
public string GetBlobUriNew(string connectionString, string containerName, string blobName, StoragePolicies policy, StorageSharedAccessExpiryTimeMinutes storageSharedAccessExpiryTimeMinutes)
{
    var container = GetContainerNew(connectionString, containerName);
    var blobClient = container.GetBlobClient(blobName);
    var accessHasExpireDate = storageSharedAccessExpiryTimeMinutes != StorageSharedAccessExpiryTimeMinutes.Infinite;

    var startTime = DateTime.UtcNow.AddMinutes(-5);
    var expiryTime = accessHasExpireDate
        ? DateTime.UtcNow.AddMinutes((int)storageSharedAccessExpiryTimeMinutes)
        : DateTime.MaxValue.AddYears(-1).AddDays(1);

    var sharedAccessServiceBuilder = new BlobSasBuilder
    {
        StartsOn = startTime,
        ExpiresOn = expiryTime,
        BlobContainerName = container.Name,
        BlobName = blobName,
        Identifier = policy.ToString()
    };

    var sasUri = blobClient.GenerateSasUri(sharedAccessServiceBuilder);
    return sasUri.AbsoluteUri;
}

```

To get only the token, I should generate an URI and extract the token part from it, or there is another way to do it?

**Comment by amnguye** [comment]
Hi @WillRock19 ,

Next time when you have a separate question could you open a new thread? that way we can get notified of your issue, Thanks.

If you're looking to only grab the sasToken and not the SasUri, you can either do what you're doing above which is
```
Uri sasUri = container.GenerateSasUri(permissions,expiryTime);
BlobUriBuilder uriBuilder= new BlobUriBuilder(sasUri);
string sasToken = uriBuilder.sas
```

or you can create the sas token from using the `BlobSasBuilder`
```
BlobSasBuilder sasBuilder = new BlobSasBuilder() {
....
};
string sasToken = sasBuilder.builder.ToSasQueryParameters(ClientConfiguration.SharedKeyCredential).ToString();
```
