### ISSUE TITLE
[QUERY] Using "*" as Etag with MatchConditions.IfMatch while accessing blob

### ISSUE THREAD

**Issue by asgoe** [Azure/azure-sdk-for-net#18955]
**Query/Question**
How can we help?
We are trying to access blob with a pre-condition where the operation should happen ONLY IF the blob ALREADY exists (etag does not need to match). Upon testing we found that using the MatchConditions.IfMatch with etag of "\*" helps achieve this (see code below). However, the documentation does not explicitly specify that "\*" can be provided with the IfMatch condition (as it says for IfNotMatch). Is the use of "*" etag with IfMatch supported?

https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-conditional-headers-for-blob-service-operations

```
var startetag = "*";
var requestCondition = new BlobRequestConditions()
  {
      IfMatch = new ETag(startetag)
  };
  using (MemoryStream stream = new MemoryStream(bytearray))
  {
      await blob.UploadAsync(content: stream,
                          httpHeaders: null,
                          metadata: null,
                          conditions: requestCondition,
                          progressHandler: null,
                          accessTier: null,
                          transferOptions: default);
  }
```
**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.7.0, Azure Identity 1.3.0, Azure Core 1.6.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Framework 4.7
 - IDE and version :Visual Studio 16.5.2

**Comment by amnguye** [comment]
Hi, I would like to know what scenario you are trying to achieve with performing an operation only when the blob exists. If you try to perform the operation, and the blob doesn't exist then it's natural for the service to kick back a 404 (BlobNotFound) and not perform the operation you are trying to attempt. You might not need to specify the IfMatch at all at that point. If wildcard is working for that value for your scenario then I'm not in the position to stop you from using it.

@tamram Is the doc the customer referring to up to date with the information of what the IfMatch header value takes in?

**Comment by asgoe** [comment]
I think I was a bit unclear in my original question. This is related to Upload, by default upload does a upsert. We are trying achieve a Replace functionality similar to a functionality that CosmosDb provides (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.documentclient.replacedocumentasync?view=azure-dotnet). So, we want the upload to fail if the blob does not already exist (etag does not need to match). In our testing we tried IfMatch with "*" etag and it worked.

**Comment by seanmcc-msft** [comment]
Yes, base on your testing appears that `IfMatch = "*"` works as you intend.  Please re-open if you have further questions.
