### ISSUE TITLE
ImdsManagedIdentitySource should bypass the Proxy by default

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#18967]
related to #18362 
related to #18479

IMDS has a requirement per the docs: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows#usage to bypass any proxy to be successful. The `ImdsManagedIdentitySource` should do this by default and perhaps allow for a flag to disable this behavior for developer scenarios that require a proxy for local development.

This will require some testing (most specifically AKS pod identity since it uses the same provider as IMDS)

**Comment by maliksahil** [comment]
On a developer's machine with McAffee, DefaultAzureCredential using the following code attempts to use ManagedIdentityCredential. This is incorrect, it should use VisualStudioCredential and use the user's identity signed into VS2019.
 
```
DefaultAzureCredentialOptions defaultAzureCredentialOptions = new DefaultAzureCredentialOptions();
defaultAzureCredentialOptions.SharedTokenCacheTenantId = tenantID;
defaultAzureCredentialOptions.ExcludeManagedIdentityCredential = true;
DefaultAzureCredential tokenCredential = new DefaultAzureCredential(defaultAzureCredentialOptions);
````

This is the exception we get,
```
Azure.Identity.AuthenticationFailedException
  HResult=0x80131500
  Message=ManagedIdentityCredential authentication failed: Service request failed.
Status: 403 (URLFilter(General))
```

**Comment by jacwil** [comment]
@maliksahil what you are describing is a different issue. You may need to open a new issue to track a proper fix.

This issue (#18967) prevents clients that run on Azure VMs with web proxy configured in their environment from using Azure managed identities. These clients often cannot disable or bypass their web proxy due to either their corporate policies or because they are a software package that cannot modify their customer's environment.

**Comment by ABratMaxed** [comment]
Hi, just ran in to this same issue and then found this ticket. 

Just wanted to check if there any plans to implement this feature, thanks!

**Comment by JimSuplizio** [comment]
Hi @christothes, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
