### ISSUE TITLE
[BUG] AzureDefaultCredentials fails after Managed Identity attempt

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-sdk-for-net#18961]
**Describe the bug**
`AzureDefaultCredentials.GetToken()` fails immediately after attempting Managed Identity, when run locally.

**Expected behavior**
`AzureDefaultCredentials.GetToken()` tries other credentials.

**Actual behavior (include Exception or Stack Trace)**
Exception message: ManagedIdentityCredential authentication failed

<details>
<summary>Stack Trace</summary>

> Azure.Identity.AuthenticationFailedException
>   HResult=0x80131500
>   Message=ManagedIdentityCredential authentication failed: Service request failed.
> Status: 403 (GlobalBlock)
> 
> Content:
> <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
> <html>
> <head>
> 	<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
> 	  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
> 	<title>Blocked Request: http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&amp;resource=https%3A%2F%2Fstorage.azure.com</title>
> 	<style type="text/css">
> 		body { padding: 5px }
> 		p { margin: 1em 0; font-family: Tahoma,Sans; font-size: 12px; color: #333 }
> 		li { margin: 1em 0; font-family: Tahoma,Sans; font-size: 12px; color: #333 }
> 	</style>
> </head>
> <body>
> 	<h1 style="margin: 0 0 45px 0; font-family: Tahoma,Sans; font-size: 24px; font-weight: bold; color: #900;">McAfee</h1>
> 
> 	<p>The Web request to http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&amp;resource=https%3A%2F%2Fstorage.azure.com has been blocked.
> 	<p><b>Reason: Category (Global Blocklist)</b></p>
> 	<p>If you feel that the Web site you requested has been blocked inappropriately, please contact your system administrator.</p>
> 
> 
> </body>
> </html>
> 
> 
> Headers:
> Cache-Control: no-cache
> X-Frame-Options: REDACTED
> Proxy-Connection: REDACTED
> Content-Type: text/html
> Content-Length: 1173
> 
>   Source=Azure.Identity
>   StackTrace:
>    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
>    at Azure.Identity.ManagedIdentityCredential.<GetTokenImplAsync>d__9.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Identity.ManagedIdentityCredential.<GetTokenAsync>d__7.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at Azure.Identity.DefaultAzureCredential.<GetTokenFromSourcesAsync>d__14.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__12.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
>    at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__12.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Identity.DefaultAzureCredential.<GetTokenAsync>d__11.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueFromCredentialAsync>d__11.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
>    at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueAsync>d__8.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
>    at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__6.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<ProcessAsync>d__1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<ProcessAsync>d__1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<ProcessAsync>d__1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
>    at GarbageCollector.SimpleTracingPolicy.<ProcessAsync>d__0.MoveNext() in C:\repos\azure-sdk-for-net\samples\CloudClipboard\GarbageCollector\Program.cs:line 38
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<ProcessAsync>d__1.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Storage.Blobs.BlobRestClient.Service.<ListBlobContainersSegmentAsync>d__9.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Azure.Storage.Blobs.BlobServiceClient.<GetBlobContainersInternal>d__47.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.Storage.Blobs.Models.GetBlobContainersAsyncCollection.<GetNextPageAsync>d__5.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.<GetAsyncEnumerator>d__5.MoveNext()
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
>    at Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.<GetAsyncEnumerator>d__5.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
>    at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
>    at GarbageCollector.Program.<Main>d__1.MoveNext() in C:\repos\azure-sdk-for-net\samples\CloudClipboard\GarbageCollector\Program.cs:line 25
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at GarbageCollector.Program.<Main>d__1.MoveNext() in C:\repos\azure-sdk-for-net\samples\CloudClipboard\GarbageCollector\Program.cs:line 25
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
> 
> Inner Exception 1:
> RequestFailedException: Service request failed.
> Status: 403 (GlobalBlock)
> 
> Content:
> <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
> <html>
> <head>
> 	<meta http-equiv="Content-Type" content="text/html;charset=utf-8">
> 	  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
> 	<title>Blocked Request: http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&amp;resource=https%3A%2F%2Fstorage.azure.com</title>
> 	<style type="text/css">
> 		body { padding: 5px }
> 		p { margin: 1em 0; font-family: Tahoma,Sans; font-size: 12px; color: #333 }
> 		li { margin: 1em 0; font-family: Tahoma,Sans; font-size: 12px; color: #333 }
> 	</style>
> </head>
> <body>
> 	<h1 style="margin: 0 0 45px 0; font-family: Tahoma,Sans; font-size: 24px; font-weight: bold; color: #900;">McAfee</h1>
> 
> 	<p>The Web request to http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&amp;resource=https%3A%2F%2Fstorage.azure.com has been blocked.
> 	<p><b>Reason: Category (Global Blocklist)</b></p>
> 	<p>If you feel that the Web site you requested has been blocked inappropriately, please contact your system administrator.</p>
> 
> 
> </body>
> </html>
> 
> 
> Headers:
> Cache-Control: no-cache
> X-Frame-Options: REDACTED
> Proxy-Connection: REDACTED
> Content-Type: text/html
> Content-Length: 1173
> 
</details>

**To Reproduce**

1. Install McAfee
2. Configure McAfee to block something?
3. Clone https://github.com/Azure/azure-sdk-for-net/
4. Load [GarbageCollector project](https://github.com/Azure/azure-sdk-for-net/tree/master/samples/CloudClipboard/GarbageCollector)
5. Run project

**Environment:**

 - Name and version of the Library package used: Azure.Identity 1.3.0
 - Windows 10 v1909, .NET Core 3.1.11
 - IDE and version : Visual Studio 16.8

<details>
<summary>McAfee About</summary>

> System Information  
> Computer Name: XXXX 
>    
> McAfee Data Exchange Layer  
> Version number: 6.0.0.218 
> Build date: Friday, March 27, 2020 
> DXL Connected State: Not Connected 
> Broker DNS Name  
> Broker Address  
> Broker Port Number  
>    
>    
> McAfee Agent  
> Version number: 5.6.5.236 
> Status: Managed 
> Last security update check: 2/23/2021 12:32:16 PM 
> Last agent-to-server communication: 2/23/2021 1:07:14 PM 
> Agent to Server Communication Interval (every): 1 hours 15 minutes 0 seconds 
> Policy Enforcement Interval (every): 1 hour 
> Agent ID: {039a49e4-6190-11eb-03bb-5405db8e683b} 
> ePO Server/Agent Handler  
> DNS Name: XXXX
> IP Address: XXXX
> Port Number: 15002 
> DNS Name: XXXX
> IP Address: ####
> Port Number: 15002 
>    
>    
> McAfee DLP Endpoint  
> Version number: 11.5.0.602 
> Language: English (United States) 
>    
>    
> McAfee Client Proxy  
> Version number: 3.2.0.189 
> Language: English (United States) 
>    
>    
> McAfee Management of Native Encryption  
> Version number: 5.1.0.9 
> Language: Multiple 
>    
>    
> McAfee Endpoint Security  
> Version number: 10.7 
> For module and content information, view the About page   
> in the McAfee Endpoint Security Client   
>   
> Copyright (C) 2020 McAfee LLC.  
> All Rights Reserved.  
> www.mcafee.com  

</details>

**Workaround**

```csharp
var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { ExcludeManagedIdentityCredential = true });
```

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by schaabs** [comment]
@MisinformedDNA thanks for filing this issue. I believe the underlying issue here is that McAfee is configures a proxy which ends up causing the ManagedIdentityCredential to fail in an unexpected way. Specifically failing do to a 502 gateway error rather than failing to connect to the well known managed identity local ip. This is a known issue that we're currently working to address and should have a fix available in our next preview due out in March. Here is the [existing issue](https://github.com/Azure/azure-sdk-for-net/issues/18362) I'm referring to, does this seem to be the same problem your encountering?
