### ISSUE TITLE
[QUERY] Webjob restarts durable function activity after crashing/restarting

### ISSUE THREAD

**Issue by alexsegura1** [Azure/azure-sdk-for-net#18971]
**Query/Question**
I have a Webjob (2.3.0) running some durable functions.  We had an issue where the machine was running out of memory and crashing.  The problem we're encountering is upon restarting the webjob kicks off the activity again, causing the webjob to crash again and it just repeats ad infinitum.  Our RetryOptions for each durable activity are set for a max of 2, but this is kicking off outside of that and we have no way to tell that the activity is being restarted.  In our case the activity will eventually succeed, but it ran a dozen times to get there and consumed a lot of resources along the way without us having any say in the matter.  

Is there a setting/strategy to handle this?  Ideally we can configure a retry strategy here, or at least have a way for the code to see how many times this method has been tried.

I can reproduce locally by simply putting a breakpoint and stopping the Webjob in the middle of a durable activity.  When I debug again and sometimes wait a few minutes the activity method will be called (but not the orchestrator).

**Environment:**
 - Azure.WebJobs 2.3.0 with Durable Functions
 - Azure AppService
 - Visual Studio 2019 16.8.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by KranthiPakala-MSFT** [comment]
@ fabiocav Following up to see if there is any update on this issue? - Thank you

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the Functions durable extensions are maintained as [#2524](https://github.com/Azure/azure-functions-durable-extension/issues/2524)
