### ISSUE TITLE
How small is "small" for BlobRequestOptions.ParallelOperationThreadCount?

### ISSUE THREAD

**Issue by thebaysix** [Azure/azure-sdk-for-net#18970]
> If blobs are small (less than 256 MB), keeping this value equal to 1 is advised.

256 MB is not small, and I can imagine parallelism in the form of 4MB chunks being quite valuable to a blob that size. This almost makes me think that this is a typo and is supposed to say 256 **KB**. 256KB is also the threshold for [HTBB](https://docs.microsoft.com/en-us/azure/storage/blobs/scalability-targets#scale-targets-for-blob-storage) which also leads me to believe this is a mistake, since that is the more frequently referenced magic number.

Can someone verify this for me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b28db753-772c-9cfe-64cd-3351b42552a8
* Version Independent ID: 1fb83247-08e8-f739-618b-306cb68cc95a
* Content: [BlobRequestOptions.ParallelOperationThreadCount Property (Microsoft.Azure.Storage.Blob) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobrequestoptions.paralleloperationthreadcount?view=azure-dotnet-legacy)
* Content Source: [xml/Microsoft.Azure.Storage.Blob/BlobRequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.Blob/BlobRequestOptions.xml)
* Service: **storage**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by amnguye** [comment]
Also I think I found the answer to your question. **256 MB** is correct because that's the maximum size we can send in one put block, any bigger we have to send in chunks.

https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#remarks

**Comment by jsquire** [comment]
@amnguye:  All issues from the .NET SDK Docs repository are automatically forwarded into this repository and we're working to triage and move any that were previously parked over there.  Going forward, we'd like to keep the docs repository empty.  Please feel free to triage and transfer legacy documentation issues elsewhere, however, if you'd prefer not to manage them here.
