### ISSUE TITLE
[BUG] ServiceBus: Closing SubscriptionClient Instance results in CanceledException

### ISSUE THREAD

**Issue by bizmonger** [Azure/azure-sdk-for-net#18980]
Closing a SubscriptionClient instance immediately results in CanceledException.

**Client:**

    Xamarin.Forms

**Setup:**        

    subscriptionClient <- new SubscriptionClient(connectionString, topic, subscription)
    subscriptionClient.OperationTimeout <- TimeSpan.FromMinutes(5.0)

    let msgOptions = MessageHandlerOptions(fun args -> exceptionReceivedHandler(args))
    msgOptions.AutoComplete         <- false
    msgOptions.MaxAutoRenewDuration <- TimeSpan.FromHours(1.0)
    msgOptions.MaxConcurrentCalls   <- 1

    subscriptionClient.RegisterMessageHandler(processMessageAsync, msgOptions)

**Execution**

    if not (subscriptionClient.IsClosedOrClosing) then
        do! subscriptionClient.CloseAsync() |> Async.AwaitTask // THROWS EXCEPTION

**Expected:**

    No exception

**Actual:**

    System.OperationCanceledException: 'The operation was canceled.'

**Environment:**
 - .Net Standard library
 - Microsoft.Azure.Amqp 2.4.11
 - Microsoft.Azure.ServiceBus 5.1.1
 - 
 - Hosting platform: Xamarin.Forms
 - IDE and version : Visual Studio 16.8.6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by bizmonger** [comment]
@jsquire - Any updates?

**Comment by jsquire** [comment]
Hi @bizmonger.   Unfortunately, I'm serving only as first triage in this case.   I don't have any insight into the status of this nor the process that the owning team is using for triage.   I'll need to defer to @axisc for assistance here.

**Comment by axisc** [comment]
@bizmonger  we're investigating this internally and will provide an update soon.

**Comment by taabdull** [comment]
Hey @bizmonger , I am trying to repro this but am not getting an exception. Are you still having this issue? Could you provide some more details on how MessageHandler is implemented? Could you also provide more of the exception stack trace? 
An issue similar to this was fixed in 4.1.1 https://github.com/Azure/azure-sdk-for-net/issues/6410

**Comment by bizmonger** [comment]
Here's the method that attempts to close the subscription:


Here's the entire class:

```
namespace OrderRequest.DataGateway

open System
open System.Text
open System.Diagnostics
open System.Threading.Tasks
open System.Threading
open Microsoft.Azure.ServiceBus
open Newtonsoft.Json
open OrderRequest.Core
open OrderRequest.DataTransfer

type AzureTopicListener<'T>(subscriptionInfo:SubscriptionInfo) as x =
    
    let topic            = subscriptionInfo.Topic
    let subscription     = subscriptionInfo.Subscription
    let connectionString = subscriptionInfo.ConnectionString

    let requested = Event<_>()

    let mutable subscriptionClient : SubscriptionClient = null

    let exceptionReceivedHandler (args:ExceptionReceivedEventArgs) =

        Debug.WriteLine(sprintf "\nERROR: %s\n" <| args.Exception.GetBaseException().Message)
        Task.CompletedTask

    let processMessageAsync (message:Message) (_:CancellationToken) = 
    
        Debug.WriteLine $"\nProcessing message for: {subscriptionInfo.Topic}\n"

        try
            message.SystemProperties.LockToken 
            |> subscriptionClient.CompleteAsync 
            |> Async.AwaitTask 
            |> Async.RunSynchronously

            let json    = Encoding.UTF8.GetString(message.Body)
            let payload = JsonConvert.DeserializeObject<'T>(json)

            (x :> IEventNotifier<'T>).Notify payload

            Task.CompletedTask

        with ex -> 
            async {

                let error = ex.GetBaseException().Message
                Debug.WriteLine(error)
                return Task.CompletedTask

            } |> Async.RunSynchronously

    interface IEventNotifier<'T> with

        member x.IsEnabled with get() = subscriptionClient <> null && not (subscriptionClient.IsClosedOrClosing)

        member x.Notify(order) = requested.Trigger order

        member x.EnableAsync() =
        
            async {

                try
                    Debug.WriteLine <| sprintf "\n\nPreparing to subscribe to topic: %s\n\n" topic

                    subscriptionClient <- new SubscriptionClient(connectionString, topic, subscription)
                    subscriptionClient.OperationTimeout <- TimeSpan.FromMinutes(5.0)

                    let msgOptions = MessageHandlerOptions(fun args -> exceptionReceivedHandler(args))
                    msgOptions.AutoComplete         <- false
                    msgOptions.MaxAutoRenewDuration <- TimeSpan.FromHours(1.0)
                    msgOptions.MaxConcurrentCalls   <- 1

                    subscriptionClient.RegisterMessageHandler(processMessageAsync, msgOptions)

                    Debug.WriteLine <| sprintf "\n\nSubscribed to topic: %s\n\n" topic
                    Debug.WriteLine <| sprintf "\n\nConnection: %s\n\n" connectionString

                with 
                    ex -> Debug.WriteLine(ex.GetBaseException().Message)
                          Debug.WriteLine <| sprintf "\n\nConnection: %s\n\n" connectionString

            } |> Async.StartAsTask

        member x.DisableAsync() =

            async {
            
                Debug.WriteLine $"\n\nDisabling subscription for topic: {topic}\n\n"

                try
                    if subscriptionClient <> null && 
                        not (subscriptionClient.IsClosedOrClosing) then

                        let! result =

                            Async.Catch(

                              async { do! subscriptionClient.CloseAsync() |> Async.AwaitTask
                                      Debug.WriteLine $"\n\nDisabled subscription for topic: {topic}\n\n" })

                        match result with
                        | Choice1Of2 ()  -> ()
                        | Choice2Of2 msg -> Debug.WriteLine($"\n\n{msg}\n\n")

                with ex -> 
                    let error = ex.GetBaseException().Message
                    Debug.WriteLine($"\n\n{error}\n\n")
            
            } |> Async.StartAsTask

    [<CLIEvent>]
    member x.Notification = requested.Publish
```

**Comment by taabdull** [comment]
@bizmonger . Sorry for the delay. I'm still trying to get a repro. I've tried both of the implementations you provided and they haven't given me the OperationCanceledException. They both process messages and exit successfully. 
![image](https://user-images.githubusercontent.com/82469669/116142305-9b89d380-a68e-11eb-9c9f-58d459fae157.png)

Could you copy the details from the exception?

**Comment by bizmonger** [comment]
Hi @taabdull 

I'm executing this code on a **Xamarin.Forms** client using **F#**.

Here's some details regarding my visual studio environment:

Microsoft Visual Studio Community 2019
Version 16.9.4
VisualStudio.16.Release/16.9.4+31205.134
Microsoft .NET Framework
Version 4.8.04084

Azure App Service Tools v3.0.0   16.9.693.2781
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.9.693.2781
Azure Functions and Web Jobs Tools

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.2.6 (master@34d6af2)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2019 - v2.9.40331.1

Mono Debugging for Visual Studio   16.9.7 (df23ba6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.9.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Visual F# Tools   16.9.0-beta.21102.9+7ce7132f1459095e635194d09d6f73265352029a
Microsoft Visual F# Tools
Xamarin   16.9.000.273 (d16-9@1bba9e0)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android SDK   11.2.2.1 (d16-9/877f572)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 5e9cb6d
    Java.Interop: xamarin/java.interop/d16-9@54f8c24
    ProGuard: Guardsquare/proguard/v7.0.1@912d149
    SQLite: xamarin/sqlite/3.34.1@daff8f4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-9@d210f11

**Comment by taabdull** [comment]
Hey @bizmonger, 
Could you paste the full details of the exception here? There should be a call stack with the exception. 
![image](https://user-images.githubusercontent.com/82469669/117087724-2f017b00-ad05-11eb-8765-672074180927.png)

**Comment by bizmonger** [comment]
I clicked 'Copy Details' but received a copy to clipboard error.

Here's the screenshot from the exception's data tip:

![image](https://user-images.githubusercontent.com/11041788/117135055-6eb37b80-ad74-11eb-832e-ef9601360561.png)

**Comment by bizmonger** [comment]
I am unable to retrieve stack trace details.

**Client:**
Here's the updated code that attempts to write the stack trace in case of exception:


        member x.DisableAsync() =

            async {
            
                Debug.WriteLine $"\n\nDisabling subscription for topic: {topic}\n\n"

                try //()
                    //----------------------------------------------------
                    // PROBLEM: Throws TaskCancelledException
                    //----------------------------------------------------
                    if processor <> null && 
                        not (processor.IsClosed) then

                        let! result =

                            Async.Catch(
                            

                              async { do! processor.CloseAsync() |> Async.AwaitTask
                                      Debug.WriteLine $"\n\nDisabled subscription for topic: {topic}\n\n" 
                                    })                                      

                        match result with
                        | Choice1Of2 () -> ()
                        | Choice2Of2 ex -> Debug.WriteLine($"\n\n{ex.StackTrace.ToString()}\n\n")
                        //----------------------------------------------------
                with ex -> 
                    let error = ex.StackTrace.ToString()
                    Debug.WriteLine($"\n\n{error}\n\n")
            
            } |> Async.StartAsTask

**Output:**

```

Disabling subscription for topic: Topic.courier-arrived-at-dropoff_8909a4670dbd
Resolved pending breakpoint at 'AzureTopicListener2.fs:115,1' to Microsoft.FSharp.Control.FSharpAsync<Microsoft.FSharp.Core.Unit> <StartupCode$Notifications-DataGateway>.$AzureTopicListener2.Notifications-DataGateway-IEventNotifier<'T>-DisableAsync@94-7.Invoke (System.Exception _arg7) [0x00002].
Resolved pending breakpoint at 'AzureTopicListener2.fs:106,1' to Microsoft.FSharp.Control.FSharpAsync<Microsoft.FSharp.Core.Unit> <StartupCode$Notifications-DataGateway>.$AzureTopicListener2.Notifications-DataGateway-IEventNotifier<'T>-DisableAsync@106-2[[OrderRequest.DataTransfer.ArrivedAtDropoff, OrderRequest.Specification, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null].Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000].
Resolved pending breakpoint at 'AzureTopicListener2.fs:106,39' to Microsoft.FSharp.Control.FSharpAsync<Microsoft.FSharp.Core.Unit> <StartupCode$Notifications-DataGateway>.$AzureTopicListener2.Notifications-DataGateway-IEventNotifier<'T>-DisableAsync@106-2[T_REF].Invoke (Microsoft.FSharp.Core.Unit unitVar) [0x00000].
Resolved pending breakpoint at 'AzureTopicListener2.fs:112,1' to Microsoft.FSharp.Control.FSharpAsync<Microsoft.FSharp.Core.Unit> <StartupCode$Notifications-DataGateway>.$AzureTopicListener2.Notifications-DataGateway-IEventNotifier<'T>-DisableAsync@110-5.Invoke (Microsoft.FSharp.Core.FSharpChoice<Microsoft.FSharp.Core.Unit,System.Exception> _arg6) [0x00030].
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[Google Maps Android API] Google Play services package version: 202414022
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->getInt(Ljava/lang/Object;J)I (greylist, linking, allowed)
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
[com.companynam] Accessing hidden method Lsun/misc/Unsafe;->getObject(Ljava/lang/Object;J)Ljava/lang/Object; (greylist, linking, allowed)
**System.OperationCanceledException:** 'The operation was canceled.'

[Choreographer] Skipped 646 frames!  The application may be doing too much work on its main thread.
[HostConnection] HostConnection::get() New Host Connection established 0xbb980d00, tid 1112
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan 
```

**Comment by taabdull** [comment]
Hi @bizmonger , Without an exception or a repro it is difficult to draw any conclusion on this. Since this does not repro in a console app it may be an application issue. If you can provide a repro in a simple console C# app based on how your application uses the provided code that would be helpful in making progress. Otherwise we will consider this as an application issue.

**Comment by bizmonger** [comment]
@taabdull I reproduced the issue on .NET 5.
Can you send me your email so that I can provide you access to the repo I reproduced the issue in?

**Comment by bizmonger** [comment]
@taabdull Here's a [video ](https://www.youtube.com/watch?v=vDvt0Utow3A)of me reproducing the anomaly:

**Comment by taabdull** [comment]
Hi @bizmonger, I am seeing the hanging you mention in the video. However when I change from Azure.Messaging.ServiceBus
 to Microsoft.Azure.ServiceBus (using the code provided above) it works without an issue. 
![image](https://user-images.githubusercontent.com/82469669/120561693-da135c00-c3b9-11eb-95e2-b8c6b318b0ec.png)

Will loop in team working on Azure.Messaging.ServiceBus since there seems to be a working repro there.

**Comment by ramya-rao-a** [comment]
This issue started off as a problem for Microsoft.Azure.ServiceBus and moved to Azure.Messaging.ServiceBus.
Can we have a new issue logged for Azure.Messaging.ServiceBus with relevant details copied over?

**Comment by ramya-rao-a** [comment]
@JoshLove-msft, @taabdull Does the conclusion in https://github.com/Azure/azure-sdk-for-net/issues/21672#issuecomment-900599381 apply to Microsoft.Azure.ServiceBus as well? If so, can we close this issue?

**Comment by KranthiPakala-MSFT** [comment]
@shankarsama  Following up to see if there is any update on this issue? - Thank you

**Comment by bizmonger** [comment]
This issue has been resolved.

```
  We have looked into the issue and we think that this issue is caused by a deadlock in the code.
  How the Close() operation is implemented, it is designed wait for the handler to complete. However since Close() is called from within the handler, it is not able to close.
The fix would be to either not await the stop processing call, or to not trigger the stop processing directly within the handler.
```
