### ISSUE TITLE
[FEATURE REQ] Need Azure Blob Storage Permanent Delete

### ISSUE THREAD

**Issue by tigertechdev** [Azure/azure-sdk-for-net#18983]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
I need the Permanent Delete feature described [here](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-blob).

I found PR #16229 which is exactly what I need but the code is not in the latest release (12.8.0 as of now) or prerelease (12.9.0-beta.1).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
@seanmcc-msft

**Comment by amnguye** [comment]
The SDK not supporting Permanent Delete is by design. This is because the use of permanent delete should not be a regular occurrence that any user should be using regularly. If Permanent Delete is used mistakenly, users can accidentally delete their data and not be able to recover.

We recommend directly calling the REST API if you want to use this feature.

**Comment by tigertechdev** [comment]
@amnguye Your concern is understandable but I see a few problems.

1) The feature exists and making it harder to use doesn't make it any less dangerous.
2) What do you mean by the user?
a) If you mean the end user of Azure, they have some measure of protection in the way of having to explicitly enable the feature for the blob service. (see [Set Blob Serivce Properties](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-service-properties))
b) If you mean the user of the SDK - that is me. I can't imagine accidentally writing code that uses permanent delete and your suggestion of using the REST API directly leads to the exact same end result.
3) I can certainly implement the  REST call with all the authorization intricacies myself but the likelihood of implementing it as good as the SDK team is slim.
4) [The changelog claims support of service version 2020-06-12](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/CHANGELOG.md) but doesn't actually support a 2020-02-10 feature. This is confusing to say the least.

Just for context, this is why I need the feature. Some of our clients request a way to rename their blobs. Since this isn't a supported operation we achieve it by copying the blob and deleting the old one. This triggers soft delete and if the client later needs to perform disaster recovery (undelete) before the retention period is over, they get two copies of their blob. Needless to say, this is not ideal.
