### ISSUE TITLE
[Text Analytics] v3.1-preview.4 Implement PiiCategory

### ISSUE THREAD

**Issue by suhas92** [Azure/azure-sdk-for-net#18985]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

**Comment by maririos** [comment]
Pii-category in analyze needs more clarification so we will not implement it for the March milestone. 
Will close this issue and leave #19237 to track the work in analyze
