### ISSUE TITLE
[Text Analytics] v3.1-preview.4 Implement Healthcare relations

### ISSUE THREAD

**Issue by suhas92** [Azure/azure-sdk-for-net#18984]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

**Comment by maririos** [comment]
Closed with PR https://github.com/Azure/azure-sdk-for-net/pull/19111
