### ISSUE TITLE
Improve exception documentation in method ref docs

### ISSUE THREAD

**Issue by daningalla** [Azure/azure-sdk-for-net#18990]
Would be nice to know what exceptions we could expect from this method and other methods in the SDK, especially when using Polly to retry requests.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5cd9d15-96d9-1a2a-87cb-95a66a55e33a
* Version Independent ID: 1b72728b-8e75-b582-9224-8a9351caf7c6
* Content: [ServiceBusSender.SendMessageAsync(ServiceBusMessage, CancellationToken) Method (Azure.Messaging.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussender.sendmessageasync?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.ServiceBus/ServiceBusSender.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus/ServiceBusSender.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @daningalla,
Exceptions are possible when sending, but the library will automatically retry exceptions that are considered [transient](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusexception.istransient?view=azure-dotnet#Azure_Messaging_ServiceBus_ServiceBusException_IsTransient).
