### ISSUE TITLE
Include comment with ApiCompatVersion

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#18995]
The ApiCompatVersion is automatically set to the last GA version by our bots after release. Can we include a comment in the csproj that indicates the value does not need to be manually changed?

/cc @weshaggard

**Comment by weshaggard** [comment]
Are you seeing folks trying to manually update it? Can you point at an instance?

Sure we could have the script add a comment. Feel free to update the script https://github.com/Azure/azure-sdk-for-net/blob/master/eng/scripts/Update-PkgVersion.ps1#L94 to add that comment.
