### ISSUE TITLE
Is there a way to persist token cache?

### ISSUE THREAD

**Issue by aloneguid** [Azure/azure-sdk-for-net#19027]
This is great, however as long as I understand there is no way to persist token cache externally, it's kept in memory and on application restart we need to authenticate again. For UI based applications it won't be acceptable. Can you recommend a way or point me in the direction of how to persist the token cache?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ad0ed2dc-fd93-c2e2-ecc7-0a1f7ce10c62
* Version Independent ID: 44070167-c751-c3da-b787-0240850690f4
* Content: [Authenticate with the Azure libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-authenticate?view=azure-dotnet#feedback)
* Content Source: [docs-ref-conceptual/dotnet-sdk-azure-authenticate.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/docs-ref-conceptual/dotnet-sdk-azure-authenticate.md)
* Service: **multiple**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Moving this to the Azure SDK repository and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @aloneguid -  Is this the scenario you were looking for?

https://github.com/Azure/azure-sdk-for-net/blob/59821ed753e23cc70c1edfa1d08a3d37305d71df/sdk/identity/Azure.Identity/samples/TokenCache.md

**Comment by aloneguid** [comment]
Yes that seems like it should solve my problem. Thank you.
