### ISSUE TITLE
[BUG] BlobClient errors with "The specified blob already exists" despite the docs stating that this method will "or updates the content of an existing block blob"

### ISSUE THREAD

**Issue by sonic1981** [Azure/azure-sdk-for-net#19022]
**Describe the bug**
the method [`BlobClient.UploadAsync`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet#Azure_Storage_Blobs_BlobClient_UploadAsync_System_IO_Stream_) is described as: 

> The UploadAsync(Stream) operation creates a new block blob or **updates the content of an existing block blob**. Updating an existing block blob overwrites any existing metadata on the blob.

Yet when I run this against an existing blob this method throws an exception:

> Azure.RequestFailedException: 'The specified blob already exists.
> RequestId:126d5fed-801e-00b7-5257-0b0cb9000000
> Time:2021-02-25T09:22:06.9289999Z
> Status: 409 (The specified blob already exists.)
> ErrorCode: BlobAlreadyExists
> 
> Headers:
> Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
> x-ms-request-id: 126d5fed-801e-00b7-5257-0b0cb9000000
> x-ms-client-request-id: c44116a3-d17d-497e-8a9d-222bc62ed8fd
> x-ms-version: 2020-02-10
> x-ms-error-code: BlobAlreadyExists
> Date: Thu, 25 Feb 2021 09:22:06 GMT
> Content-Length: 220
> Content-Type: application/xml
> '

**Expected behavior**
Blob should be updated

**Actual behavior (include Exception or Stack Trace)**
Exception is thrown

**To Reproduce**
Simply call `await blobClient.UploadAsync(ms);` on an existing blob.

**Environment:**
 - Azure.Storage.Blobs, Version=12.7.0.0
 - .Net Core 3.1
 - Visual Studio 2019 16.8.5

**Comment by sonic1981** [comment]
Ok, looking into it, it looks like this has been reported and closed once before https://github.com/MicrosoftDocs/azure-docs/issues/44973. But this issue **has not been addressed**

**Comment by sonic1981** [comment]
so upgrading from 12.7.0.0 to 12.8.0.0 shows the overwrite overload. So it seems that an upgrade helps but I'm still going to say that the docs are wrong.

**Comment by prachita-mane** [comment]
There are still some inconsistencies in documentation:
[Link](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet#Azure_Storage_Blobs_BlobClient_UploadAsync_System_IO_Stream_Azure_Storage_Blobs_Models_BlobUploadOptions_System_Threading_CancellationToken_)

<img width="682" alt="image" src="https://user-images.githubusercontent.com/48495471/147897488-5608038f-b911-4828-a5a6-713b89f6160d.png">

[Link](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet#Azure_Storage_Blobs_BlobClient_UploadAsync_System_String_)

<img width="677" alt="image" src="https://user-images.githubusercontent.com/48495471/147897529-10e73690-3fe0-4125-b6d0-39be8153bb4d.png">

Do we have a method that accepts contents of type string?
