### ISSUE TITLE
remove path 

### ISSUE THREAD

**Issue by jonathanLincoqueo** [Azure/azure-sdk-for-net#19025]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3700ae6-6561-51cc-607b-eca5d00c1266
* Version Independent ID: 1a907e55-5f7a-adb0-6fb0-9b534309049d
* Content: [Azure Storage File Shares client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.files.shares-readme)
* Content Source: [api/overview/azure/storage.files.shares-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/storage.files.shares-readme.md)
* Service: **storage**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
Hi @jonathanLincoqueo.   Can you offer a bit more context on your feedback?   I'm not sure of what difficulty you're running into or suggestion that you're making here.
