### ISSUE TITLE
[BUG] Azure Blob Storage: Unable to generate a SAS token for file that contain URL encoded char in its name

### ISSUE THREAD

**Issue by LudovicSiegenthaler** [Azure/azure-sdk-for-net#19021]
**Describe the bug**
When using the `BlobSasBuilder` to generate a SAS token for a file that contains URL encoded characters in its name, the file name defined in the signature does not contain the encoded character but their non-encoded version.

**Expected behavior**
The file name defined in the signature should be the same as the one provided to generate the SAS token.

It's good to know that the SAS token generated from the Azure portal for the same file is working as expected.

**Actual behavior (include Exception or Stack Trace)**
When generating a SAS token to access the file `123456%2E.json`, the generated URI return the following error:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Error>
    <Code>
        AuthenticationFailed
    </Code>
    <Message>
        Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
        RequestId:0fc6dc09-a01e-014f-2e57-0b502e000000
        Time:2021-02-25T09:19:05.2377243Z
    </Message>
    <AuthenticationErrorDetail>
        Signature did not match. String to sign used was r
        2021-02-25T08:55:51Z
        2021-02-26T08:55:51Z
        /blob/STORAGEACCOUNT_NAME/CONTAINER_NAME/FOLDER_NAME/123456..json
        2019-12-12
        b
    </AuthenticationErrorDetail>
</Error>
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.1 Create a file named `123456%2E.json` in Azure Blob Storage.
2.1 Generate a SAS token with the below code:
```csharp
private string GetServiceSasUriForBlob(
    BlobClient blobClient,
    string storedPolicyName = null)
{
    var keyCredential = new StorageSharedKeyCredential(_blobServiceClient.AccountName, _accountKey);

    var sasBuilder = new BlobSasBuilder
    {
        BlobContainerName = blobClient.GetParentBlobContainerClient().Name,
        BlobName = blobClient.Name,
        Resource = "b"
    };

     if (storedPolicyName == null)
    {
        sasBuilder.ExpiresOn = DateTimeOffset.UtcNow.AddMinutes(5);
        sasBuilder.SetPermissions(BlobSasPermissions.Read);
    }
    else
    {
        sasBuilder.Identifier = storedPolicyName;
    }

    var sasQueryParameters = sasBuilder.ToSasQueryParameters(keyCredential);

    var uriBuilder = new UriBuilder
    {
        Scheme = "https",
        Host = $"{_blobServiceClient.AccountName}.blob.core.windows.net",
        Path = $"{sasBuilder.BlobContainerName}/{sasBuilder.BlobName}",
        Query = sasQueryParameters.ToString()
    };

    return uriBuilder.Uri.OriginalString;
}
```
2.2 Generate a SAS token from the Azure Storage Explorer for the specified file.
3. Try to use the generated URI to download the file.

**Environment:**
 - Azure.Storage.Blobs 12.8.0
 - .NET 5.0
 - Visual Studio 16..8.2
 - Microsoft Azure Storage Explorer 1.17.0

**Comment by amnguye** [comment]
Just to clarify, is your blob name `123456%2E.json` or `123456..json` ?

But looks like your suspicions is on the right track. Looks like when we go to create the signature, we are calculating the signature based on the encoded character and not the unencoded character. I need to look at how it's handling the blob name and how we are sending it in the URI that way the signature can be calculated correctly.

Thanks for bringing this bug up.

**Comment by LudovicSiegenthaler** [comment]
> Just to clarify, is your blob name `123456%2E.json` or `123456..json` ?

The blob name is `123456%2E.json`

**Comment by seanmcc-msft** [comment]
Hi @LudovicSiegenthaler, for your repo, try this instead:
```
    var sasQueryParameters = sasBuilder.ToSasQueryParameters(keyCredential);

    var uriBuilder = new UriBuilder(blobClient.Uri)
    {
        Sas = sasQueryParameters;
    }
    return uriBuilder.ToUri().ToString();
```

**Comment by seanmcc-msft** [comment]
Please reopen if you have further questions.

**Comment by HarryPi** [comment]
I am facing the exact same issue and as per our advice tried the above however the UriBuilder has no Sas property or a ToUri, it has a Query parameter and a Uri parameter but have tried those.

**Comment by amnguye** [comment]
@HarryPi Use the BlobUriBuilder instead and then call `uriBuilder.Sas.ToString()`. If there are any further questions please open up a new github issue.
