### ISSUE TITLE
[BUG] Auth policy won't be the last one when there is a custom policy added in the clientOptions

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-net#19020]
**Describe the bug**
The auth policy is expected to be the last policy in the pipeline array before the transport adapter.
See: 
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Common/src/Shared/StorageClientOptions.cs#L112

Hoever, the HttpPipelineBuilder will add any policy from the clientOptions per-retry list to be after the auth policy (which is at the end of the per-retry policies from the client SDK)
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Pipeline/HttpPipelineBuilder.cs#L70

**Expected behavior**
What is the expected behavior?

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.
2.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by pakrym** [comment]
Is this issue blocking some scenario? I'm slightly reluctant to reorder policies without a strong need now that we have customers that might rely on existing order.

**Comment by jsquire** [comment]
There have been no customer reports of this behavior causing issues in the two years since this was filed.  As Pavel mentioned, it is potentially risky to change the ordering of policies.   I'm going to close this out and we can reconsider a course of action if we see a customer report for real-world impact.
