### ISSUE TITLE
LineCounter sample no longer builds

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#19038]
When I was running `dotnet build eng/services.proj -p:ServiceDirectory=*`, I found that samples/linecounter does not build anymore (our CIs exclude samples) because it uses a public `CloudEvent` type, which was made internal and renamed to `CloudEventInternal` in the referenced EventGrid project.

> C:\src\azure-sdk-for-net\samples\linecounter\Controllers\HomeController.cs(70,56): error CS0246: The type or namespace name 'CloudEvent' could not be found (are you missing a using directive or an assembly reference?) [C:\src\azure-sdk-for-net\samples\linecounter\LineCounter.csproj]

**Comment by JoshLove-msft** [comment]
I thought we did build samples in CI - https://github.com/Azure/azure-sdk-for-net/pull/9808

**Comment by JoshLove-msft** [comment]
Nevermind, it only triggers the build if the samples are changed.
