### ISSUE TITLE
Azure.Storage returned 401 status code when I used the wrong account to access Azure Blob Storage.

### ISSUE THREAD

**Issue by momoliu-msft** [Azure/azure-sdk-for-net#19044]
I was trying to use AzCli credential with "Storage Blob data Contributor" role to access Azure Blob Storage with the following code in dev environment:

```csharp
string blobEndpoint = $"https://{accountName}.blob.core.windows.net";
BlobServiceClient blobServiceClient = new BlobServiceClient(new Uri(blobEndpoint), new AzureCliCredential());
var scriptContainer = blobServiceClient.GetBlobContainerClient(containerName);
await scriptContainer.CreateIfNotExistsAsync();
```
Then I got the error “Server failed to authenticate the request. Please refer to the information in the www-authenticate header.” with a 401 status code. 

**Actual behavior**
I realized that I had logged in with the wrong account. After I switched the account, everything was good.

**Environment:**
 - Azure.Identity 1.3.0
 - Windows 10 .NET Framework 4.8
 - Visual Studio 16.8.5

**Comment by jsquire** [comment]
Hi @momoliu-msft.   Could you provide the stack trace that you're seeing as well, please?   From the context, I'm not sure whether this is the return from the storage service due to the invalid credential or this was returned from `Azure.Identity` when trying to authenticate.    For now, I'll ask @schaabs to offer his thoughts and reroute if necessary.

**Comment by schaabs** [comment]
@momoliu-msft  Thanks for filing this issue. In this case the 401 (Unauthorized) is returned from the storage service, because the account of the token supplied isn't authorized to perform the requested operation. This is the designed behavior of the storage service. Were you expecting a different error? I'm not sure we can do much to provide a better error experience from the client side.

**Comment by momoliu-msft** [comment]
Yeah, the error is returned as expected. Filling the issue here for giving those who may encounter the same problem as me an idea to solve the problem. I will paste the stack trace after I could use the other account to log in and reproduce the error.

**Comment by momoliu-msft** [comment]
Here is the stack trace of the failure:

"ClassName\":\"System.AggregateException\",\"Message\":\"One or more errors occurred.\",\"Data\":{\"IsLogged\":true},\"InnerException\":{\"Status\":401,\"ErrorCode\":\"InvalidAuthenticationInfo\",\"ClassName\":\"Azure.RequestFailedException\",\"Message\":\"Server failed to authenticate the request. Please refer to the information in the www-authenticate header.\
RequestId:15e51a47-b01e-0130-5e95-0fa67e000000
Time:2021-03-02T18:57:56.2861795Z
Status: 401 (Server failed to authenticate the request. Please refer to the information in the www-authenticate header.)
ErrorCode: InvalidAuthenticationInfo
Additional Information:
AuthenticationErrorDetail: Issuer validation failed. Issuer did not match.
Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 15e51a47-b01e-0130-5e95-0fa67e000000
x-ms-error-code: InvalidAuthenticationInf
WWW-Authenticate: REDACTED
Date: Tue, 02 Mar 2021 18:57:55 GMT
Content-Length: 402
Content-Type: application/xml
\",\"Data\":{\"AuthenticationErrorDetail\":\"Issuer validation failed. Issuer did not match.\"},\"InnerException\":null,\"HelpURL\":null,\"StackTraceString\":\"   at Azure.Storage.Blobs.BlobRestClient.Service.GetUserDelegationKeyAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)\\
   at Azure.Storage.Blobs.BlobRestClient.Service.GetUserDelegationKeyAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, KeyInfo keyInfo, String version, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)\\
   at Azure.Storage.Blobs.BlobServiceClient.GetUserDelegationKeyInternal(Nullable`1 startsOn, DateTimeOffset expiresOn, Boolean async, CancellationToken cancellationToken)\\
   at Azure.Storage.Blobs.BlobServiceClient.GetUserDelegationKeyAsync(Nullable`1 startsOn, DateTimeOffset expiresOn, CancellationToken cancellationToken)\",\"RemoteStackTraceString\":null,\"RemoteStackIndex\":0,\"ExceptionMethod\":null,\"HResult\":-2146233088,\"Source\":\"Azure.Storage.Blobs\",\"WatsonBuckets\":null},\"HelpURL\":null,\"StackTraceString\":\"   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\\
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\\
   at System.Threading.Tasks.Task`1.get_Result() at...
