### ISSUE TITLE
Add support for RSA PRIVATE KEY in PemReader

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#19046]
We should probably also support `RSA PRIVATE KEY` as an alternative loading X509 certificates. This is encoded as PKCS\#1 and just the base64-encoded private key.

_Originally posted by @heaths in https://github.com/Azure/azure-sdk-for-net/pull/19018#discussion_r583277313_

**Comment by heaths** [comment]
See https://github.com/dotnet/runtime/blob/6a80a380a1644d962137ad62bc16067bc0dbfb72/src/libraries/System.Security.Cryptography.X509Certificates/tests/X509Certificate2PemTests.cs#L223-L241 for some examples where `X509Certificate2` does support PKCS\#1 RSA and ECDsa private keys, though KV doesn't format keys it created that way. Will need to test import.

**Comment by heaths** [comment]
Actually, since lines ~74 through 102 assume RSA, that will have to be changed. The only way we could tell is to also download the key and check it's type before deciding which route to go down. ECDsa certificates have their own extension methods.

**Comment by pallavit** [comment]
@heaths has this been recently asked by any customers? If not do you see us implementing in the near future?

**Comment by heaths** [comment]
No. It was more of a "we should do this in case" feature request, but we can close it for now and wait for user feedback.
