### ISSUE TITLE
[BUG] ServiceBusProcessor not receving messages when using Azure.Identity.ClientSecretCredential (TokenCredential)

### ISSUE THREAD

**Issue by fosterbuster** [Azure/azure-sdk-for-net#19059]
**Describe the bug**

I have tested the code using a connection string, and the code functions as expected. 

Instantiating a `ServiceBusAdministrationClient` using `Azure.Identity.ClientSecretCredential` also works fine, and allows me to add new subscriptions - So I presume that this is not an authentication issue.

Using the following setup:

1. Instantiate a servicebus client using 

`public ServiceBusClient(string fullyQualifiedNamespace, TokenCredential credential);`

2. Create a ServiceBusProcessor

```
 _processor =  client.CreateProcessor(
                   topicName: "...",
                   subscriptionName: "...",
                   new ServiceBusProcessorOptions { }
                );
```
`_processor.ProcessMessageAsync += ....`

**Expected behavior**
Events on ProcessMessageAsync are fired

**Actual behavior (include Exception or Stack Trace)**
Events on ProcessMessageAsync are not fired

_No exceptions are thrown._

**To Reproduce**
1. Create an App Registration
2. Create A client secret
3. Add App Registration to AIM.
4. Use previously generated Client Secret to instantiate `Azure.Identity.ClientSecretCredential`
5. Instantiate `ServiceBusClient(string fullyQualifiedNamespace, TokenCredential credential)`
6. Create a `ServiceBusProcessor`
7. Send a message over a topic which the service bus processor subscribes.
8. Message is not received.

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.ServiceBus, Version=7.1.0.0. Azure.Identity, Version=1.3.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 x64, net5.0
 - IDE and version : Visual Studio Professional 2019, Version 16.8.6

**Comment by jsquire** [comment]
Hi @fosterbuster.  Thank you for reporting this and we regret that you're experiencing difficulties.   Would you be so kind as to help us diagnose by providing some additional information?

- Could you confirm what roles your principal was assigned?   We'll want to ensure that your principal has either [`Azure Service Bus Data Owner`](https://docs.microsoft.com/azure/role-based-access-control/built-in-roles#azure-service-bus-data-owner) or [`Azure Service Bus Data Receiver`](https://docs.microsoft.com/azure/role-based-access-control/built-in-roles#azure-service-bus-data-receiver) granted.

- Are you seeing the `IsProcessing` property returning `true` after calling `StartProcessingAsync`?

- Are you seeing  your `ProcessErrorAsync` handler fire and, if so, what errors is it reporting?

- Would you be willing to share some additional code?  It would be helpful to see the how you're configuring the handlers, how the handlers are structured and what they do, and the context surrounding the processor being started.

**Comment by fosterbuster** [comment]
> 
> 
> Hi @fosterbuster. Thank you for reporting this and we regret that you're experiencing difficulties. Would you be so kind as to help us diagnose by providing some additional information?
> 
>     * Could you confirm what roles your principal was assigned?   We'll want to ensure that your principal has either [`Azure Service Bus Data Owner`](https://docs.microsoft.com/azure/role-based-access-control/built-in-roles#azure-service-bus-data-owner) or [`Azure Service Bus Data Receiver`](https://docs.microsoft.com/azure/role-based-access-control/built-in-roles#azure-service-bus-data-receiver) granted.

My principal is a Service Bus Data Owner

![billede](https://user-images.githubusercontent.com/3317522/109466067-6a639d00-7a69-11eb-8187-4c7938a2e55c.png)

> 
>     * Are you seeing the `IsProcessing` property returning `true` after calling `StartProcessingAsync`?

Yes.

`IsClosed` is `false`
`IsProcessing` is `true`
`IsSessionProcessor` is `false`
> 
>     * Are you seeing  your `ProcessErrorAsync` handler fire and, if so, what errors is it reporting?

`ProcessErrorAsync` does not fire.

> 
>     * Would you be willing to share some additional code?  It would be helpful to see the how you're configuring the handlers, how the handlers are structured and what they do, and the context surrounding the processor being started.

**Again, I would like to point out that this code works fine using a connection string, and that the `ClientSecretCredential` works fine, when using `ServiceBusAdministrationClient`.**

    public class AuthenticationHelper
    {
        // ServiceBusOptions is my own options object for DI 
        public static ClientSecretCredential GetClientSecretCredential(AzureServiceBusOptions options)
        {
            return new ClientSecretCredential(options.TenantId, options.ApplicationId, options.ClientSecret);
        }
    }

In the constructor of the class wrapping processing: 

    ....
    var client = new ServiceBusClient(optionValues.ServiceBusFullyQualifiedNamespace, AuthenticationHelper.GetClientSecretCredential(optionValues));
    string subscriptionName = EnsureSubscription(optionValues).Result;

     _messageProcessor = client.CreateProcessor(
        topicName: optionValues.Topic,
        subscriptionName,
        new ServiceBusProcessorOptions { }
    );

     _messageProcessor.ProcessMessageAsync += ProcessMessageAsync;
     _messageProcessor.ProcessErrorAsync += ProcessErrorAsync;

    _messageProcessor.StartProcessingAsync().Wait();
    ....

Processing, which is not triggered:

      private Task ProcessMessageAsync(ProcessMessageEventArgs messageArgs)
      {
            _logger.LogInformation("Message {messageId} received", messageArgs.Message.MessageId);

            var messageString = messageArgs.Message.Body.ToString();

            _onMessageReceived(new CloudMessage { Contents = messageString });

            return Task.CompletedTask;
        }

**Comment by JoshLove-msft** [comment]
@fosterbuster, I've not been able to reproduce this issue.
To help narrow down where the failure is occurring, can you try to receive messages using a regular receiver rather than the processor?

**Comment by fosterbuster** [comment]
> 
> 
> @fosterbuster, I've not been able to reproduce this issue.
> To help narrow down where the failure is occurring, can you try to receive messages using a regular receiver rather than the processor?

Hi Josh. I started making a small program for you, that reproduced the issue - However, after deleting all subscriptions on the topic it started working just fine, and I am no longer able to reproduce it myself. As such, I suspect that it might have been a rule issue, though I am still confused as to why it would work with a connection string.

In any case, since I cant reproduce the issue myself, and my code is functioning as I want I am closing the issue.

Thank you for your time.
