### ISSUE TITLE
Azure.Storage.Blobs Sample issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#19051]
1.
Section [link:](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/samples/Sample03_Migrations.cs#L497)

![image](https://user-images.githubusercontent.com/65581162/109246552-70653e00-781d-11eb-9ce1-3543d4cb1caa.png)

Suggestion:
![image](https://user-images.githubusercontent.com/65581162/109247146-5c6e0c00-781e-11eb-8e7c-041e02d157be.png)

1.Add  `+ "/" ` ;

2.Update ' foreach (var blobName in new List<string> { "foo.txt", "bar.txt", virtualDirName + `"/fizz.txt", virtualDirName + "/buzz.txt"` })' to 'foreach (var blobName in new List<string> { "foo.txt", "bar.txt", virtualDirName + `"fizz.txt", virtualDirName + "buzz.txt"` })'

3.Add ` ,delimiter: "/" `

@jongio for notification.

**Comment by amnguye** [comment]
Resolved with https://github.com/Azure/azure-sdk-for-net/pull/22380
