### ISSUE TITLE
BlobBaseClient.StartCopyFromUriAsync document: Text overflowing edge of browser, can't scroll over

### ISSUE THREAD

**Issue by cbrit** [Azure/azure-sdk-for-net#19066]
The summary statement at the top of the page goes of the page and I am unable to scroll horizontally.

![image](https://user-images.githubusercontent.com/23322838/109336576-3863f800-7829-11eb-81eb-64ea917dd6b5.png)

Resizing the window does not fix the issue

I am using Microsoft Edge browser Version 88.0.705.74

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: efd0e00b-df56-46f2-be22-3949805f85d3
* Version Independent ID: e106e179-f3d8-30ad-14ea-2bbc06772f17
* Content: [BlobBaseClient.StartCopyFromUriAsync(Uri, BlobCopyFromUriOptions, CancellationToken) Method (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.startcopyfromuriasync?view=azure-dotnet#Azure_Storage_Blobs_Specialized_BlobBaseClient_StartCopyFromUriAsync_System_Uri_Azure_Storage_Blobs_Models_BlobCopyFromUriOptions_System_Threading_CancellationToken_)
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
@danieljurek:  This looks like it may be a tooling issue.   The summary section from the doc comments isn't wrapping and the `<see cref="" />` expansion is way wrong.   The [comment source](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L1748) looks like:

```xml
/// <summary>
/// The <see cref="StartCopyFromUri(Uri, BlobCopyFromUriOptions, CancellationToken)"/>
/// operation begins an asynchronous copy of the data from the <paramref name="source"/> to this blob.
/// You can check the <see cref="BlobProperties.CopyStatus"/>
/// returned from the <see cref="GetProperties"/> to determine if the
/// copy has completed.
///
/// For more information, see
/// <see href="https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob">
/// Copy Blob</see>.
/// </summary>
```

Do you mind offering your thoughts?

**Comment by danieljurek** [comment]
Sorry for the delay. We have an issue open with the docs team to investigate how the formatting is improperly wrapping. I believe the formatting fix can be done on their side and changes won't be required in this repo.

**Comment by kurtzeborn** [comment]
Yeah, this appears to be a problem specific to the docs.ms.com processing of the refdocs.  It appears to be fully qualifying the types which creates the wrapping problem.  If we can fix the types from being fully qualified, there won't be a line wrapping problem.  

For comparison, [here](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Storage.Blobs/12.8.0/api/Azure.Storage.Blobs.Specialized/Azure.Storage.Blobs.Specialized.BlobBaseClient.html#Azure_Storage_Blobs_Specialized_BlobBaseClient_StartCopyFromUriAsync_System_Uri_Azure_Storage_Blobs_Models_BlobCopyFromUriOptions_System_Threading_CancellationToken_) is a link to the github.io docs for the same function and it doesn't fully qualify the types.

**Comment by danieljurek** [comment]
Link to internal work item: https://dev.azure.com/ceapex/Engineering/_workitems/edit/389299?src=WorkItemMention&src-action=artifact_link

**Comment by kurtzeborn** [comment]
Internal tracking item is closed.  Closing...
