### ISSUE TITLE
Query resource group via blob URI?

### ISSUE THREAD

**Issue by kirk-marple** [Azure/azure-sdk-for-net#19089]
Given an Azure blob URI, I know the storage account name, but I can't seem to find anyway to lookup the containing resource group for the storage account in the subscription.

I'm using Microsoft.Azure.Management.Storage, and can call StorageAccounts.ListWithHttpMessagesAsync, and then parse the resource group from the ID - but that requires enumerating all storage accounts in the subscription and matching by name.  Obviously not optimal.

Even looking at the blob and container data models, I can't find the resource group anywhere.

Hoping there's a better approach here, thanks.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by blueww** [comment]
@kirk-marple

Do you want to list all resource group in a subscription?
This is out of storage side, it's handled by resources SDK.

You can find the test code to list resource group from: https://github.com/Azure/azure-sdk-for-net/blob/91f2566acf60957b0eca0b22beaca2d8a93511d1/sdk/resources/Microsoft.Azure.Management.Resource/tests/ScenarioTests/ResourceGroupTests.ScenarioTests.cs#L77

**Comment by kirk-marple** [comment]
Sorry, I think my question wasn't clear.  

Let me walk through the scenario again:
- We are using a blob event trigger, and receive an event in an Azure Function (HTTP) that contains the Azure blob URI
- From that URI, I can parse out the storage account name
- But what I really need to know, to use the Storage APIs, is the resource group that the storage account belongs to.
- The only way I've seen is to list all storage accounts in the subscriptions, match on the name, and then parse the resource group from the storage account ID.

This isn't optimal, since I have to list every storage account, and there may be 10s or 100s in the subscription.
 
I was hoping for a way to look up the containing resource group from a storage account name.

**Comment by blueww** [comment]
@kirk-marple 
From storage side, there's no existing API to query a storage account's resource group only from account name without list all accounts.

If you want a quick query, you might can try to list the resources in the subscription with `$filter=resourceType EQ 'Microsoft.Storage/storageAccounts'`，(storage account is one kind of resource),  then find the resource with same name as the account in the result, and see the resource group of it. 
List resource API responds is smaller than list storage account, and should be quicker.
You can see a sample of .net SDK on this in https://github.com/Azure/azure-sdk-for-net/blob/91f2566acf60957b0eca0b22beaca2d8a93511d1/sdk/resources/Microsoft.Azure.Management.Resource/tests/ScenarioTests/ResourceTests.ScenarioTests.cs#L413

**Comment by kirk-marple** [comment]
@blueww I appreciate the note, and that should work.  Also it gave me some ideas since I'm tagging the storage account and resource group with the same ID, and that OData filter looks like it can filter by tags.

I should be able to come up with a more optimal solution with a combination of these approaches.

I'll close this issue.
