### ISSUE TITLE
[BUG] ServiceBusSessionProcessor should not log ServiceTimeout as an error when accepting sessions

### ISSUE THREAD

**Issue by pawepaw** [Azure/azure-sdk-for-net#19098]
**Describe the bug**
I've configured ServiceBusSessionProcessor to listen to the queue and process new messages as they arrive. Unfortunately every minute i'm receiving exception with timeout. I use raw default of ServiceBusSessionProcessor with just queue name.

```csharp
        public async Task StartAsync(CancellationToken cancellationToken)
        {
            ServiceBusSessionProcessor = _serviceBusClient.CreateSessionProcessor("queue-name");

            ServiceBusSessionProcessor.ProcessMessageAsync += async (ctx) =>
            {
                Logger.Information("Received message, SessionId:{SessionId}", ctx.SessionId);
            };
            
            ServiceBusSessionProcessor.ProcessErrorAsync += (ctx) =>
            {
                Logger.Error(ctx.Exception,"Error occurred when processing message from service bus.");
                return Task.CompletedTask;
            };

            await ServiceBusSessionProcessor.StartProcessingAsync(cancellationToken);
        }

        public async Task StopAsync(CancellationToken cancellationToken)
        {
            await ServiceBusSessionProcessor.StopProcessingAsync(cancellationToken);
        }
```
**Expected behavior**
No exception thrown

**Actual behavior (include Exception or Stack Trace)**
```
EventId: {Id: 85, Name: 'CreateReceiveLinkException'}

An exception occurred while creating receive link for Identifier: queue-name-1e63397e-81f2-40f2-9b07-8d5ea5c9f15b. Error Message: 

System.TimeoutException: The operation did not complete within the allocated time 00:00:59.9958173 for object receiver16.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenAmqpObjectAsync(AmqpObject target, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, Boolean isSessionReceiver, String identifier)
```

**To Reproduce**
Just keep it running with no messages in a queue.

**Environment:**
 - Azure.Messaging.ServiceBus 7.1.0
 - K8s pod with asp.net 5.0 and processor working as hosted service.

**Comment by jsquire** [comment]
Hi @pawepaw.   The exception that you're seeing indicates that your container/pod is having difficulty with network communication and isn't able to establish a link to the Service Bus service within the configured timeout period.   If you are seeing these consistently every 60 seconds, that indicates the processor is continually try and failing to connect;  it won't be able to receive messages.

Can you help us to understand how you're configuring your `ServiceBusClient` and the network configuration of your host pod?   It would also be very helpful if you'd be willing to create a sender from within the same application host environment and confirm whether or not you're able to publish a message to the queue or are seeing the same inability to create a sender link.

**Comment by pawepaw** [comment]
Well that's strange because i'm using 

```
            services.AddAzureClients(cfg =>
            {              
                cfg.AddServiceBusClient(ServiceBusConnectionString);
            });
```

and i'm experiencing same exceptions on my local machine, and what's strange it consumes messages correctly when they appear on the queue.

**Comment by JoshLove-msft** [comment]
@pawepaw - can you clarify where you are seeing the error? Is it in your error logs? The timeout would occur when no messages are available in any sessions on the queue. It shouldn't be bubbled up to your error handler, but it is still thrown at a lower level, which seems to be what is happening here. We could potentially thread a parameter through so that this exception is not thrown at all when using the processor.

**Comment by pawepaw** [comment]
Yea it exactly matches my problem. I have no messages at queue, It doesn't buble up but it's still logged as error, i have serilog configured so that's why i'm observing it. 

Why is it logged if that's not abnormal situation?

**Comment by JoshLove-msft** [comment]
It is an implementation detail that it is logged right now - it is an exceptional case when using the receiver directly, but not when using the processor. This is why the processor catches the exception and does not bubble it. We can investigate not logging in this case (or maybe changing the log level to Informational).

**Comment by jsquire** [comment]
Apologies for adding to the confusion here;  I missed the nuance of the session behavior being different than the norm.

**Comment by JoshLove-msft** [comment]
I would propose that when we are attempting to Accept a session from the processor, we log ServiceTimeout as Informational rather than Error.
@pawepaw would this change address your concerns?

**Comment by pawepaw** [comment]
@JoshLove-msft yes that make sense. It's just information that there were no messages, doesn't fit error severity.

**Comment by codelogiq** [comment]
I'm experiencing pretty much the exact same behavior.  One suggestion I'd like to make would be to just add an option to ServiceBusProcessor options for severity of this specific behavior so that I can suppress it entirely in an easier fashion.  In my workflow scenario, if things are working as expected and my processing business logic is keeping up in regards to throughput, I *want* my sessions to be empty a majority of the time.

My scenario is using sessionIds in a high volume (~2m messages per hour) scenario in which sessions are being used to allow concurrent processing but also preserve guarantee granular fifo.  In my workflow the sessionIds are generated by the sending side, then once all of the messages for a specific session are processed, I'm calling SetState(null) in the SessionClosing event handler, and that very well could be the last time that session is ever touched.  The SetState is likely unnecessary but it was more of a safety precaution than anything else to avoid some stale session scenario and trying to keep the queues themselves relatively clean. 

Regardless, I'd really like to avoid my logging being essentially becoming a dumping ground of link receiver timeout errors, so any kind of way to suppress or filter these would be great.

**Comment by JoshLove-msft** [comment]
@codelogiq we generally rely on the pattern of apps filtering logs in their listeners as opposed to allowing what is logged to be configurable. Would these logs being classified as Informational be an issue for you? I suppose we could even consider Verbose..

**Comment by JoshLove-msft** [comment]
This issue shouldn't be closed.

**Comment by jsquire** [comment]
Fixing tags to avoid triggering bot rules.

**Comment by codelogiq** [comment]
> @codelogiq we generally rely on the pattern of apps filtering logs in their listeners as opposed to allowing what is logged to be configurable. Would these logs being classified as Informational be an issue for you? I suppose we could even consider Verbose..

My vote would be verbose -- I would probably argue that it isn't even informational as in a healthy scenario an empty queue may not be an uncommon scenario at all.  I could see value in it for debugging purposes, but that's about it.

**Comment by JoshLove-msft** [comment]
A similar issue is around how we log errors when stopping the processor.

**Comment by JoshLove-msft** [comment]
Here is how I would like to propose that we address this:
When using the session processor, accept session timeouts will be given a new event that is logged as Verbose. Accept session timeouts that occur when using the ServiceBusSessionReceiver directly will not be changed. Along similar lines, I'd like to take this opportunity to no longer log task cancelled errors when stopping the processor as errors, and instead to log them under another new event as Verbose.
So we would have two new events - ProcessorAcceptSessionTimeout and ProcessorStoppingTaskCanceled that would both be Verbose. What do folks think about this plan?
