### ISSUE TITLE
[Container Instances] Missing Example

### ISSUE THREAD

**Issue by ddobric** [Azure/azure-sdk-for-net#19095]
I would like to mount the volume to the azure file storage. To do this I obviously need to use WithVolumeMountSetting.
But the question is how?!

Want to do following with the C# Microsoft.Azure.Management.ContainerInstance.Fluent;:

```
   --azure-file-volume-account-name $ACI_PERS_STORAGE_ACCOUNT_NAME \
    --azure-file-volume-account-key $STORAGE_KEY \
    --azure-file-volume-share-name $ACI_PERS_SHARE_NAME \
    --azure-file-volume-mount-path /aci/logs/
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c84fc88b-45dd-35d3-ee62-40e2df946b3e
* Version Independent ID: 268618d6-1521-7f40-4aa6-fdcd57d24050
* Content: [IWithVolumeMountSetting&lt;ParentT&gt;.WithVolumeMountSetting Method (Microsoft.Azure.Management.ContainerInstance.Fluent.ContainerGroup.Definition) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.containerinstance.fluent.containergroup.definition.iwithvolumemountsetting-1.withvolumemountsetting?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.ContainerInstance.Fluent.ContainerGroup.Definition/IWithVolumeMountSetting`1.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ContainerInstance.Fluent.ContainerGroup.Definition/IWithVolumeMountSetting`1.xml)
* Service: **container-instances**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nisha-bhatia** [comment]
@ddobric Could you please provide the API version and VS version you're using? Thank you.

**Comment by ddobric** [comment]
This is the version of the fluent API that I use:
  
`<PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.37.0" />`

**Comment by JonathanCrd** [comment]
Re-routing to the service team.

**Comment by KranthiPakala-MSFT** [comment]
@dkkapur  Following up to see if there is any update on this issue? - Thank you

**Comment by ddobric** [comment]
Anything new?

**Comment by ArthurMa1978** [comment]
Hi @ddobric , the fluent sdk is being deprecated, and the new sdk for Container Instance is here https://www.nuget.org/packages/Azure.ResourceManager.ContainerInstance/.
@HarveyLink please help to provide a sample / test for this scenario.

**Comment by dvbb** [comment]
Hi, @ddobric 

As Microsoft.Azure.Management.Fluent has been deprecated, we recommend customers migrate to Azure.ResourceManager.XX
Here is an example for creating an azure container with a volume, I hope it helps

#### environment
* .net 6.0
* Azure.ResourceManager.ContainerInstance 1.0.1

#### prerequisites
  created a storage account that has a file share

```csharp
// get your azure access token, for more details of how Azure SDK get your access token, please refer to https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication?tabs=command-line
TokenCredential cred = new DefaultAzureCredential();
ArmClient client = new ArmClient(cred);
ResourceIdentifier resourceGroupResourceId = ResourceGroupResource.CreateResourceIdentifier("subscriptionId", "resourceGroupName");
ResourceGroupResource resourceGroup = client.GetResourceGroupResource(resourceGroupResourceId);

string volumeName = "volume0";
string volumePath = $"/mnt/{volumeName}";
string sharedName = "<Your-File-Share>";
string storageAccountName = "<Storage-Account-Name>";
string storageAccountKey = "<Storage-Account-Key>";

// create a container with a volume
ContainerResourceRequirements requirements = new ContainerResourceRequirements(new ContainerResourceRequestsContent(memoryInGB: 1.5, cpu: 1));
var containers = new List<ContainerInstanceContainer>()
{
    new ContainerInstanceContainer("Container0", "mcr.microsoft.com/azuredocs/aci-helloworld:latest", requirements)
    {
        VolumeMounts =
        {
            new ContainerVolumeMount(volumeName, volumePath)
        },
    },
};
ContainerGroupData data = new ContainerGroupData(resourceGroup.Data.Location, containers, ContainerInstanceOperatingSystemType.Linux)
{
    Volumes =
    {
        new ContainerVolume(volumeName)
        {
            AzureFile = new ContainerInstanceAzureFileVolume(sharedName, storageAccountName)
            {
               StorageAccountKey = storageAccountKey,
            }
        },
    }
};
var containerGroup = await resourceGroup.GetContainerGroups().CreateOrUpdateAsync(WaitUntil.Completed, "containergroup0", data);
Console.WriteLine(containerGroup.Value.Data.Containers[0].VolumeMounts);
Console.WriteLine(containerGroup.Value.Data.Containers[0].VolumeMounts.Count);
```
