### ISSUE TITLE
[Compute Swagger] Dead link to virtual-machines-linux-use-root-privileges

### ISSUE THREAD

**Issue by mostverydoge** [Azure/azure-sdk-for-net#19093]
Hi,

The link to https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-use-root-privileges?toc=/azure/virtual-machines/linux/toc.json returns 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 696674d3-df55-bb81-adb4-d87e3ffc7c45
* Version Independent ID: 2afe6e9c-7bad-80ff-57bc-5fc356aee93d
* Content: [OSProfile Class (Microsoft.Azure.Management.Compute.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.osprofile?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/OSProfile.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/OSProfile.xml)
* Service: **multiple**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by amjads1** [comment]
@jaylabell Can you please look into this issue?

**Comment by Drewm3** [comment]
@jsquire, could you share where you are seeing this bad link? It is not clear from your description where you are seeing the link because that will be the location that will need to be updated.

**Comment by Mohit-Chakraborty** [comment]
It's in the description of the `AdminUsername` property at https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.osprofile?view=azure-dotnet

![image](https://user-images.githubusercontent.com/8271806/110032954-9d1dc780-7ced-11eb-8c1a-6c71e8369e62.png)

**Comment by Drewm3** [comment]
@avirishuv, could you work with Micah to determine the right doc page for this URL, and then work with the API owner to update the swagger docs.

**Comment by avirishuv** [comment]
Marking this as a bug, we have identified the links that need to be fixed and will be updating those.

**Comment by avirishuv** [comment]
The docs have been updated for the correct link: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.osprofile.adminpassword?view=azure-dotnet#Microsoft_Azure_Management_Compute_Models_OSProfile_AdminPassword 

Closing this issue. Please feel free to reopen if you have additional questions on this topic.
