### ISSUE TITLE
[BUG] Cannot read Tags of subscription if permission is inherited via Management Group

### ISSUE THREAD

**Issue by DGOIT-Jan** [Azure/azure-sdk-for-net#19099]
**Describe the bug**
I want to read the tags on an Azure Subscription using "Microsoft.Azure.Management.ResourceManager.SubscriptionClient".
The Service Principal is able to read the subscriptions details but the tags-property is always null if the SP was given the "Reader" role on the management group of the subscription.
If I add the SP directly to the Subscription itself as a "Reader" I can successfully read the tags.

It seems some permissions are not fully inherited from the parent management group.

**Expected behavior**
The Service Principal should be able to read the Tags of the subscription.

**Actual behavior (include Exception or Stack Trace)**
The Tags property of the subscription is always null.

**To Reproduce**
You need to have some subscriptions bound to an Azure Management Group.
1. Create an App Registration in Azure.
2. Assign the created Service Principal the Reader-role on the management-group.
3. Set some Tags on the subscription.
4. Get some azure credentials:

```csharp
var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(clientId,
                    clientSecret, tenantId,
                    AzureEnvironment.AzureGlobalCloud);
```

5. Get a new resource-manager-client and check the Tags-Property. It is always null:

```csharp
var subscriptionClient = new Microsoft.Azure.Management.ResourceManager.SubscriptionClient(azureCredentials);
var subscriptions = await subscriptionClient.Subscriptions.ListAsync();
      foreach (var sub in subscriptions)
      {
          var t = sub.Tags;
      }
```

6. Assign the Reader-role directly to the subscription and now you're able to read the tags successfully.

**Environment:**
VS 16.8.3
Microsoft.Azure.Management.ResourceManager: 3.12.1-preview

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nisha-bhatia** [comment]
Thank you for your question, we will route to the appropriate team for follow-up.

**Comment by nisha-bhatia** [comment]
@DGOIT-Jan could you please provide the HTML request and response? Thank you
