### ISSUE TITLE
Ability to express user-assigned managed identity in IConfiguration

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-sdk-for-net#19090]
**Library or service name.**
Microsoft.Extensions.Azure
 
**Is your feature request related to a problem? Please describe.**
When using a configuration source to drive a connection, I would like to be able to reference a user-assigned identity. The model today accounts for system-assigned only. That's the default case, and a client ID option exists in conjunction with a secret to form a client credential. Just adding a solo client ID could create some confusion there, so it needs to be explicit. That's especially true considering deployment environments.

Proposal (CC @pakrym) : Add an explicit `credential` property (possibly useable in other areas), which can be set to "managedidentity" and indicates the `ManagedIdentityCredential` type should be used. A `clientId` property is optional and if set indicates the used-assigned identity as per the `ManagedIdentityCredential` constructor. In absence of `clientId`, the system-assigned identity should be used. In practice, setting credential on its own is unlikely since omitting it entirely would provide the same result + local options per `DefaultAzureCredential` underneath.

Using a Blob as an example (json config):

```json
{
  "MyStorageConnection": {
      "serviceUri": "…",
      "credential": "managedidentity",
      "clientId": "…"
  }
}
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Done in https://github.com/Azure/azure-sdk-for-net/pull/18459.
