### ISSUE TITLE
[Fluent Compute] Create resource in multiple step

### ISSUE THREAD

**Issue by toutougabi** [Azure/azure-sdk-for-net#19100]
I am trying to create virtual machines using the fluent api but there are conditions that will affect the creation.

For example, in some cases i might want to enable boot diagnostics and some others i don't. 

How can i do this in stages for ex:

```csharp
var vm = azure.VirtualMachines
    .Define(vm.Name)
    .WithRegion(vm.ArmResource.Inner.Location)
    .WithExistingResourceGroup(tmpRg)
    .WithExistingPrimaryNetworkInterface(primaryNic)
    .WithSpecializedOSDisk(osDisk, (OperatingSystemTypes)osType);

if(bootdiag)
    vm = vm.WithBootDiagnostics();
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nisha-bhatia** [comment]
Thank you for the question, routing to the appropriate team for follow-up.

**Comment by amjads1** [comment]
Looking into the issue.

**Comment by toutougabi** [comment]
I answered my answer, i was able to use the iwithcreate and the managed version in multiple steps with success, i think what confused me is that the changes are not stored in the main variable but in private properties.
