### ISSUE TITLE
ServiceBus: Allow For Customized Lock Renewal Algorithm

### ISSUE THREAD

**Issue by michaelwstark** [Azure/azure-sdk-for-net#19123]
Microsoft.Azure.ServiceBus

Our service occasionally encounters LockLostExceptions while renewing locks on messages exceeding the lease time.  We are investigating this issue from multiple directions.  One of the potential items we looked into to mitigate the problem is to add some intelligence for when to renew the lock.  The default algorithm for when the underlying SDK's autorenewal to kick in is below.  For us, the following will only initiate a lock renew when the lock is within 10 seconds of expiring. 

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/MessagingUtilities.cs

Would the service bus sdk team be accept a contribution which allows for a custom implementation to be provided?  If so I can define a strategy and follow the corresponding contribution guide.

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @ramya-rao-a

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@michaelwstark  Thanks for the offer to make a contribution. What custom lock renewal algorithm did you have in mind?

**Comment by michaelwstark** [comment]
@axisc - Specifically, we would like to increase the lock renewal window to up to 30 seconds before lock lost when we start receiving lostlockexceptions.  Specifically, to the offer, I would just like to change the code so that a consumer of the SDK can provide their own implementation.  E.g. add a interface for IAutoRenewalStrategy (name TBD) which someone can inject into the pump so they can customize the window without re-implementing the auto-renew logic E2E.

**Comment by axisc** [comment]
@michaelwstark Thanks for sharing the details. There is one consideration though - locks are volatile, so being able to renew too early may be more problematic if the client app ignores the volatile nature and makes it a dependency for their business logic. It's still worth having some upper limit (of the order of seconds) for this custom retry logic.

Please feel free to make a PR and add @yvgopal, @DorothySun216, and myself as reviewers.
