### ISSUE TITLE
[FormRecognizer] Allow support for older service versions

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#19132]
Currently only the latest service version can be targeted in the Form Recognizer client. We do have a `Version` enum that's set in the client options, but it's not used internally.

- PR with swagger transform to address the issue: https://github.com/Azure/azure-sdk-for-net/pull/19085
- We should include tests and maybe documentation as well.

**Comment by maririos** [comment]
The current plan is:
- [ ] Apply transform to have multi-version support
- [ ] Enable multi-version tests for `FormTrainingClient`
- [ ] Enable multi-version tests for `FormRecognizerClient`
- [ ] Enable multi-version tests for `OperationLiveTest`
- [ ] Update methods docstrings to include information about the version
- [ ] Update Model properties docstrings to include information about the version
- [ ] Update Readme with table on version support like Python does
- [ ] Update changelog
