### ISSUE TITLE
Core pipeline build is too slow

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#19136]
We run the core pipeline to test a lot of cross-cutting concerns:

 * Core changes don't break other libraries	
 * Test framework changes don't break tests/recorded tests
 * Everything compiles
 * Package updates don't break libraries
 * Generator changes don't break libraries

It's possible we don't need to test all libraries for all the core changes and instead have multiple separate more targeted runs.

In addition we need to look at the test performance and parallelization.

**Comment by pakrym** [comment]
cc @weshaggard @maririos

**Comment by weshaggard** [comment]
FYI @m-nash

**Comment by pakrym** [comment]
NUnit issue that makes the test discover slow https://github.com/nunit/nunit/issues/3786

**Comment by rprouse** [comment]
@pakrym NUnit 3.13.2 has been released with the fix for this issue, https://github.com/nunit/nunit/releases/tag/v3.13.2

**Comment by pakrym** [comment]
I think it's reasonable now. We'll track future improvements separately.
