### ISSUE TITLE
Consider adding a depency on Storage to allow for documents to be passed to translator and sdk uploads to storage

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#19143]
It will involve taking a direct dependency on Storage.
The flow will be, user passes files, and storage account, the SDK will upload the files to the storage account, generate SAS, and pass that to the translator service.
What about the Target? created by the SDK?

**Comment by chriswendt1** [comment]
Upvote.
It does make sense to provide a collection of local files to translate, provide a local target location, and have the translations deposited in the target location. Needs some creativity with the file/directory naming. I solved that by allowing to pass a '*' in the target, which the code replaces with the <language ID for *this* language>.
