### ISSUE TITLE
Update the azure-messaging-replication-dotnet repo to use Azure.Messaging.* packages

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#19154]
https://github.com/Azure-Samples/azure-messaging-replication-dotnet contains utilities to help with replicating messages between EH/EH, EH/SB, SB/EH and SB/SB. These currently use the Microsoft.Azure.EventHubs and Microsoft.Azure.ServiceBus packages. 

This was added late last year as part of [Message replication and cross-region federation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-federation-overview)

Now that we have newer packages for the Event Hubs and Service Bus, the code here should be updated to use the same.

**Comment by ramya-rao-a** [comment]
cc @lilyjma , @spelluru, @axisc

**Comment by jsquire** [comment]
Moving to the backlog; this work is blocked until the Functions bindings packages using `Azure.Messaging.*` have been released to GA.

**Comment by jsquire** [comment]
Closing this out; the conversion was done and submitted.  We cannot control when review and merging takes place.
