### ISSUE TITLE
[BUG] Deadletter Async causes a MessageLockLost Exception

### ISSUE THREAD

**Issue by ISAF87** [Azure/azure-sdk-for-net#19163]
**Describe the bug**
We register a message handler. When an exception is thrown, because we cannot process the file, there is no point in retrying, so we catch the exception, and call DeadLetterAsync to move the message to the deadletter queue. This works as expected. However, it also throws an lockexpired exception from within Microsoft.Azure.ServiceBus

**Expected behavior**
Message is deadlettered, without exeptions

**Actual behavior (include Exception or Stack Trace)**
Message is deadlettered, with exception:
EXCEPTION:
Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.AbandonAsync(String lockToken, IDictionary`2 propertiesToModify)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.AbandonMessageIfNeededAsync(Message message)    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, 

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```csharp
public Task StartAsync(CancellationToken cancellationToken)
        {
            queueClient = new QueueClient(_config.ConnectionString, QueueName);

            queueClient.RegisterMessageHandler(async (message, token) =>
            {
                var messageBody = Encoding.UTF8.GetString(message.Body);
                var messageToHandle = JsonConvert.DeserializeObject<Message>(messageBody);

                try
                {
                    await _customService.ProcessAsync(messageToHandle.Id, messageToHandle.Path)
                        .ConfigureAwait(false);

                    await queueClient.CompleteAsync(message.SystemProperties.LockToken)
                        .ConfigureAwait(false);
                }
                catch (SystemException ex) when (ex is ArgumentNullException
                        || ex is NotSupportedException
                        || ex is System.IO.IOException)
                {
                    await queueClient.DeadLetterAsync(message.SystemProperties.LockToken)
                        .ConfigureAwait(false);

                    throw;
                }


            }, new MessageHandlerOptions(ExceptionReceivedHandlerAsync)
            {
                MaxConcurrentCalls = 1,
                AutoComplete = false
            });

            return Task.CompletedTask;
        }

        /// <summary>
        /// Stop listening to the service-bus queue.
        /// </summary>
        public async Task StopAsync(CancellationToken cancellationToken)
        {
            await queueClient.CloseAsync().ConfigureAwait(false);
        }

        private Task ExceptionReceivedHandlerAsync(ExceptionReceivedEventArgs exceptionDetails)
        {
            _logger.LogError(exceptionDetails.Exception);
            return Task.CompletedTask;
        }
```
**Environment:**
 - Microsoft.Azure.ServiceBus (5.1.1)
 - Windows Server 2016
 - IDE: Visual Studio Enterprise 2019, v16.8
 - .Net Standard 2.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@ISAF87  Is this happening all the time, or occasionally? Locks are volatile so you may have lost the lock on the message when you try to deadletter it. The solution here is to retry obtaining the message lock and then deadlettering it.

**Comment by ISAF87** [comment]
It happens all the time when we try to deadletter it. We validate the message to see if we can process it, if not, we deadletter it as retrying makes no sense. This validation takes only milliseconds, so locks expired seem unlikely. 

Weird thing is, that we moved the handling logic to a common assembly, to reuse it. Now the issue is gone. The only difference the additional throw; after deadletterasync. This no longer happens in our current implementation.

**Comment by davidallyoung** [comment]
@ISAF87 I have run into an experience like this before when using prefetching. If the service prefetches a larger batch than it can handle in the lock duration, it will attempt to process messages whose lock expired waiting in the prefetched state on the client. Could that have been what you were experiencing?

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-prefetch#if-it-is-faster-why-is-prefetch-not-the-default-option
