### ISSUE TITLE
[Cosmos] Typo in sample code

### ISSUE THREAD

**Issue by paulomorgado** [Azure/azure-sdk-for-net#19170]
The sample code has this in several places:

```csharp
foreach(var item in await feedIterator.ReadNextAsync()){
```

and it should be:

```csharp
foreach(var item in await feedIterator.ReadNextAsync())
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f022e1c2-c13f-e4ff-a5c9-932b5dc412c0
* Version Independent ID: f0b87c16-a3a2-61a0-2c45-f320ddc2a8ca
* Content: [Container.GetItemQueryIterator Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.getitemqueryiterator?view=azure-dotnet#Microsoft_Azure_Cosmos_Container_GetItemQueryIterator__1_Microsoft_Azure_Cosmos_QueryDefinition_System_String_Microsoft_Azure_Cosmos_QueryRequestOptions_)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
