### ISSUE TITLE
Use System.Formats.Asn1 for ASN.1 decoding

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#19198]
Based on https://github.com/Azure/azure-sdk-for-net/pull/19194, rather than decode a limited set of ASN.1 tags ourselves, use https://www.nuget.org/packages/System.Formats.Asn1/7.0.0.

Need to check compatibility with Azure Functions runtime, Windows PowerShell, and PowerShell Core support for Functions.

**Comment by heaths** [comment]
Re-evaluate now that we did recently update dependencies for System.Text.Encodings.Web.

**Comment by pallavit** [comment]
@heaths do you still see value in us implementing this support?

**Comment by heaths** [comment]
From a maintainability perspective, I think it's still worth it but depends on multi-targeting per #33488. `System.Formats.Asn1` supports >= net462.
