### ISSUE TITLE
[BUG] Azure.Identity.ManagedIdentityCredential does not implement the recommended retry policy

### ISSUE THREAD

**Issue by darkoa-msft** [Azure/azure-sdk-for-net#19190]
**Describe the bug**
We migrated from AppAuthentication to Azure.Identity and started getting 429 from IMDS.
The old library implemented the [recommended retry](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#retry-guidance)

We are not caching tokens.

**Expected behavior**
What is the expected behavior?
We should not see 429s from IMDS

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
We are seeing 429s from IMDS

**To Reproduce**
Create a service that uses a ManagedIdentityCredential.GetTokenAsync() to get an ARM token, deploy it to Azure and create a lot of requests. Log the failures.

**Environment:**
 - Azure.Identity 1.4.0-beta2
 - Windows 10 .NET Core 3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
The current retry behavior can be customized via the `TokenCredentialOptions` passed to `ManagedIdentityCredential`

```c#
var options = new TokenCredentialOptions();
options.Retry.MaxRetries = 5;
var credential = new ManagedIdentityCredential(null, options);
```

As a side note - Generally, if there are excessive 429 responses from IMDS, your code should consider caching tokens where possible.

**Comment by darkoa-msft** [comment]
We added the caching on our side which mitigated the issue.
My point is that behavior changed in Azure.Identity.
Without caching we occasionally saw a 429 with the old library.

Note that the IMDS may be unavailable during the host upgrade (not talking about the VM host, but the host on which VMs are running) so your code will fail to get a token if it is not using the recommended retry policy.

I understand that you are hesitant to implement the MSI recommended retry policy as a default retry policy because of the chaining of credential providers.
Maybe you should reorder them?

**Comment by christothes** [comment]
> Maybe you should reorder them?

The [ChainedTokenCredential](https://github.com/Azure/azure-sdk-for-net/blob/bb7d612114a8a6c8e5ce8c55a9359cded69488dd/sdk/identity/Azure.Identity/README.md#define-a-custom-authentication-flow-with-the-chainedtokencredential) can be used if you need custom ordering.

**Comment by darkoa-msft** [comment]
I failed to make my point, sorry - In Default you have a certain order that makes you not want to wait for one minute for IMDS to be up (in case someone does not care about MSI). We had an IcM alert due to IMDS not running for more than a minute (we were not using Azure.Identity at the time).

As far as I am concerned you can close this issue, I was just trying to make a suggestion.
