### ISSUE TITLE
Consider using CngKey on Windows to replace parsing PKCS8 PrivateKeyInfo

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#19196]
Based on https://github.com/Azure/azure-sdk-for-net/pull/19194#discussion_r587688563, consider using `CngKey` to read the DER-encoded private key blob for either RSA or ECDsa keys, and use the `AlgorithmGroup` to check that (@bartonjs also recommends treating `ECDiffieHellman` as `ECDsa` as well).

This does leave a gap, however, for netcoreapp2.1 customers on non-Windows platforms. `CngKey` is only implemented on Windows; however, a number of algorithms are already unsupported across platforms and frameworks (like any ECDsa requiring us to load private keys on net461) so will this be a problem?

/cc @jlichwa @schaabs

**Comment by pallavit** [comment]
@heaths do you see us changing the implementation here? What benefit would it bring to our customers?

**Comment by heaths** [comment]
This was to improve maintainability, but we haven't saw fit to prioritize this in a few years so I'm fine with closing it. We can always revisit if/when needed.
