### ISSUE TITLE
[QUERY] Management.Reservations error

### ISSUE THREAD

**Issue by pilara-ms** [Azure/azure-sdk-for-net#19200]
**Query/Question**
I'm getting this error: MissingRegistration while calling Quota PUT.

**Environment:**
 - Microsoft.Azure.Management.Reservations -Version 1.15.0-preview

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nisha-bhatia** [comment]
@pilara-ms could you please provide the HTML request and response? Thank you

**Comment by pilara-ms** [comment]
My issue is resolved.
