### ISSUE TITLE
Build broken on SDK 5.1.200

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#19206]
On SDK 5.0.200, the build is broken with errors like this:
 
```
/home/mharder/net/sdk/storage/Azure.Storage.Common/src/Shared/LazyLoadingReadOnlyStream.cs(236,23):
error CA2208: Method ValidateReadParameters passes 'offset cannot be less than 0.' as
the paramName argument to a ArgumentOutOfRangeException constructor.
Replace this argument with one of the method's parameter names.
Note that the provided parameter name should have the exact casing as declared
on the method. [/home/mharder/net/sdk/storage/Azure.Storage.Blobs/src/Azure.Storage.Blobs.csproj]
```

The root `global.json` contains this:

https://github.com/Azure/azure-sdk-for-net/blob/f240ef2127603c487b06abb59bfb4b8758f958ad/global.json#L5-L8

My Windows machine has both SDK 5.0.103 and 5.0.200 installed, and 5.0.103 is chosen at build time, so the build succeeds.
 
But my Linux machine only has 5.0.200 installed, so 5.0.200 is chosen at build time, and the build fails.

I think we need to change our `global.json` to:

```
"sdk": {
  "version": "5.0.100",
  "rollForward": "patch"
}
```
 
https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x#rollforward

Separately, I'm not sure if this is considered a valid "feature-level" change in the SDK, or if it was an accidental breaking change.

**Comment by jsquire** [comment]
//cc: @AlexGhiondea, @tg-msft
