### ISSUE TITLE
ContentHash when using BlockBlobClient.OpenWriteAsync(true)

### ISSUE THREAD

**Issue by michaeldtaylor** [Azure/azure-sdk-for-net#19218]
**Describe the bug**
I am upgrading from storage v11 to v12. Looking at [Issue 17676](https://github.com/Azure/azure-sdk-for-net/issues/17676) I understand that there are two modes depending on file size: Put Blob and Put Block / Put Blob List.

A test is failing which creates a small Blob using OpenWriteAsync(true), because the ContentHash is not being set. When I try and set ContentHash I am not allowed to, because it doesn't match what the server calculates. If the server can calculate it, why isn't it set?

**Expected behavior**
When I set the BlobHttpHeaders explicity, then it should accept whatever I give it, or set it itself:

```csharp
await using var outputStream = await blockBlobClient.OpenWriteAsync(true, new BlockBlobOpenWriteOptions
{
    HttpHeaders = new BlobHttpHeaders
    {
        ContentHash = content.ToMd5()
    }
});
```
I get:

```
The MD5 value specified in the request did not match with the MD5 value calculated by the server.
RequestId:6a06f4b4-a243-438a-bb83-f7fc23531ee1
Time:2021-03-04T17:08:10.0157094Z
Status: 400 (The MD5 value specified in the request did not match with the MD5 value calculated by the server.)
ErrorCode: Md5Mismatch

Additional Information:
UserSpecifiedMd5: mJNTIjPK/5jNCDoRawE8Cw==
ServerCalculatedMd5: 1B2M2Y8AsgTpgAmY7PhCfg==
```

Now the MD5 I calculate is wrong - it is the MD5 of the string rather than the gzipped string - my concern is as follows:

- If the server can calculate the MD5, then why doesn't it set the value into ContentMD5? If you run this code without the headers then the ContentMD5 property is not set.
- How do I make all files sizes act consistently using OpenWriteAsync? I can't see any obvious way to prevent the server calculting the MD5 and letting me set what I want - I think with UploadAsync I would use InitialTransferLength = 0, which would then use Put Block / Put Blob List for everything?
- If the server doesn't set ContentMD5, then why isn't this user settable to anything? I haven't tested yet but presumably if the blob size was greater > 256MB, it would use Put Block / Put Blob List and the server couldn't/wouldn't calculate the Hash and I could set whatever I wanted? In this case the behaviour would be inconsistent.
- I don't want to refactor to use UploadAsync if I can help it. The way streams are passed around in this app makes this undesirable.

**Actual behavior (include Exception or Stack Trace)**
A small blob doesn't get a ContentMD5 set, but knows what it should be and doesn't let me set it to what I want.

**To Reproduce**
```csharp
var content = "something small";

await using var outputStream = await blockBlobClient.OpenWriteAsync(true, new BlockBlobOpenWriteOptions
{
    HttpHeaders = new BlobHttpHeaders
    {
        ContentHash = content.ToMd5()
    }
});

await using var gZipStream = new GZipStream(outputStream, CompressionMode.Compress);
await using var streamWriter = new StreamWriter(gZipStream);

await streamWriter.WriteAsync(content);
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.0 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Core 3.1
 - IDE and version : Visual Studio 16.8.6

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by michaeldtaylor** [comment]
Some additional information that is related to this. I was just experimenting with UploadAsync (again, I would prefer not to use it) and found the following docs:

[UploadAsync sample](https://github.com/Azure/azure-sdk-for-net/pull/17759/commits/7e15bcc206be9c0e6e48adb323c58990d36cf73a)

As per the test, this works:

```csharp
var content = "Hello world";

await using var memoryStream = new MemoryStream(Encoding.ASCII.GetBytes(content));

using var md5 = MD5.Create();

var contentHash = md5.ComputeHash(memoryStream);

memoryStream.Position = 0;

await blockBlobClient.UploadAsync(memoryStream, new BlobUploadOptions
{
    HttpHeaders = new BlobHttpHeaders
    {
        ContentHash = contentHash
    }
})
```

This does not:

```csharp
var content = "Hello world";

await using var outputStream = new MemoryStream();
await using var gZipStream = new GZipStream(outputStream, CompressionMode.Compress);
await using var memoryStream = new MemoryStream(Encoding.ASCII.GetBytes(content));

await memoryStream.CopyToAsync(gZipStream);

using var md5 = MD5.Create();

var contentHash = md5.ComputeHash(outputStream);

memoryStream.Position = 0;

await blockBlobClient.UploadAsync(outputStream, new BlobUploadOptions
{
    HttpHeaders = new BlobHttpHeaders
    {
        ContentHash = contentHash
    }
});
```

What am I doing wrong when I use Gzip?

**Comment by kasobol-msft** [comment]
This might be related https://github.com/Azure/azure-sdk-for-net/issues/18884

**Comment by seanmcc-msft** [comment]
Hi @michaeldtaylor,

`OpenWrite()` is always using [Put Block](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block) and [Put Block List](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block-list), so the service is not calculating content-MD5.

To set your own content-md5 on the blob, I'd recommend uploading the blob with `OpenWrite()`, and then setting the content-MD5 you want with `BlockBlobClient.SetHttpHeadersAsync()`

-Sean

**Comment by michaeldtaylor** [comment]
Hi Sean. So are you saying to use OpenWrite and not OpenWriteAsync? I've explained the problem and replication with OpenWriteAsync. Feel free to try it, assuming they don't work differently?

**Comment by seanmcc-msft** [comment]
@michaeldtaylor, no `OpenWrite()` and `OpenWriteAsync()` have the same implementation.

**Comment by michaeldtaylor** [comment]
Then your assertation must be false then. When I run the code above and set an MD5 in one go it is not accepted with the error being the my MD5 is incorrect. How does it know this if the server is not calculating it?

**Comment by michaeldtaylor** [comment]
This is all slightly academic to me now anyway as I am no longer on the project I was upgrading from v11 to v12. In the end I calculated the real MD5 correctly and refactored to use UploadAsync. This involved Blob -> File -> Blob, so I could calculate the real MD5 and not have to hold the blob in memory (~8GB). The v11 to v12 upgrade experience wasn't the most fun I've ever had, but at least it seemed to prevent Block List Error race conditions.

**Comment by seanmcc-msft** [comment]
https://docs.microsoft.com/en-us/rest/api/storageservices/put-block#request-headers

> Content-MD5 Optional. An MD5 hash of the block content. This hash is used to verify the integrity of the block during transport. When this header is specified, the storage service compares the hash of the content that has arrived with this header value. Note that this MD5 hash is not stored with the blob.If the two hashes do not match, the operation will fail with error code 400 (Bad Request).

For Put Block, the content of the individual blocks is calculated and checked by the service, not the entire blob.

**Comment by michaeldtaylor** [comment]
Ok, I probably missed a trick with "SetHttpHeadersAsync". Does this allow you to set anything?

**Comment by seanmcc-msft** [comment]
It allows you to set `x-ms-blob-content-md5`.  https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-properties#request-headers-all-blob-types

**Comment by michaeldtaylor** [comment]
I meant any value to ContentHash/x-ms-blob-content-md5. I assume the answer is yes.

**Comment by seanmcc-msft** [comment]
Yes, you can set it to any value.
