### ISSUE TITLE
[QUERY] GetUserDelegationKeyAsync returned 500 status code after IMDS identity endpoint is ready

### ISSUE THREAD

**Issue by momoliu-msft** [Azure/azure-sdk-for-net#19239]
**Query/Question**
I got three failures with 500 status code back while invoking GetUserDelegationKeyAsync() after getting the MSI credential. Here are the request IDs:
RequestId:2b018973-b01e-0003-29cc-0bacc4000000
RequestId:115b31fa-e01e-0031-3dcc-0bacb3000000
RequestId:c7b838f7-801e-007a-56cc-0b50e0000000

**Same innerExceptionMessage, pasting the first one as an example:**

Operation could not be completed within the specified time.
RequestId:2b018973-b01e-0003-29cc-0bacc4000000
Time:2021-02-25T23:20:47.9319903Z
Status: 500 (Operation could not be completed within the specified time.)
ErrorCode: OperationTimedOut

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 2b018973-b01e-0003-29cc-0bacc4000000
Date: Thu, 25 Feb 2021 23:20:47 GMT
Content-Length: 246
Content-Type: application/xml

**Environment:**
 - Azure.Storage.Blobs 12.7.0
 - Azure.Identity 1.3.0
 - k8s

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by christothes** [comment]
@momoliu-msft Are you able to reproduce this? If so, could you provide the steps?

**Comment by momoliu-msft** [comment]
Hi, @christothes, I added retry for the service by following this doc: https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows#errors-and-debugging. It looks good now.

**Comment by momoliu-msft** [comment]
Hi, @christothes, we have seen four failures on this recently. So basically we check the identity endpoint before sending a request to retrieve a user delegation key. And what happened for the failures were, after querying the imds identity endpoint(http://169.254.169.254/metadata/identity/oauth2/token?resource=https://vault.azure.net&), it gets "No Managed Identity endpoint found." while retrieving the user delegation key. 

The max wait time we set for this is 76s, which covered most of the cases, but not the four above. Any suggestions? Thx in advance.

**Comment by christothes** [comment]
You may need to take this up with the Managed Identity service team, who owns that endpoint.
