### ISSUE TITLE
Need support TestMockSupport in .Net SDK like in powershell

### ISSUE THREAD

**Issue by pattipaka** [Azure/azure-sdk-for-net#1923]
Currently, we had to use Thread.Sleep in out APIs. We don't have API like TestMockSupport in .Net SDK to do sleep appropriately.

**Comment by shahabhijeet** [comment]
@pattipaka would this work?
Microsoft.Rest.ClientRuntime.Azure.TestFramework.Testutilities.Wait()
https://github.com/azure/azure-sdk-for-net/blob/AutoRest/src/TestFramework/Microsoft.Rest.ClientRuntime.Azure.TestFramework/Utilities/TestUtilities.cs#L84
