### ISSUE TITLE
No documentation for SubscriptionClient(String, String, String, ITokenProvider, TransportType, ReceiveMode, RetryPolicy)

### ISSUE THREAD

**Issue by ColeSiegelTR** [Azure/azure-sdk-for-net#19236]
Hi

I cannot find any documentation or code samples how to properly use Token Provider in the constructor of SubscriptionClient. I have played around with it myself by implementing ITokenProvider and am able to connect but cannot understand when the tokens will be refreshed. Is there any explanation of how to use this code? Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f8c81ed8-9c7b-83a5-c5bd-d1e4f321b4e0
* Version Independent ID: 80026bce-76e8-9068-bb0e-c9c4d66e8bf1
* Content: [SubscriptionClient Constructor (Microsoft.Azure.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.subscriptionclient.-ctor?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.ServiceBus/SubscriptionClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.ServiceBus/SubscriptionClient.xml)
* Service: **service-bus-messaging**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
This is related to a doc publish issue. Will update the thread when fixed.

**Comment by ramya-rao-a** [comment]
For samples around TokenProvider, you can checkout https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl

The same approach can be applied to SubscriptionClient

The problem with missing docs is being tracked in https://github.com/Azure/azure-sdk-for-net/issues/11798
