### ISSUE TITLE
[QUERY] Sending request to IMDS identity endpoint got 403 status code back

### ISSUE THREAD

**Issue by momoliu-msft** [Azure/azure-sdk-for-net#19242]
**Query/Question**
We got 403 status code while checking the IMDS identity endpoint and waiting for it to be ready.

_Here is the innerExceptionMessage:_

ManagedIdentityCredential authentication failed: Service request failed.
Status: 403 (Forbidden)

Content:
failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: Bad Request

Headers:
X-Content-Type-Options: REDACTED
Date: Sat, 27 Feb 2021 16:31:39 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 110

**Environment:**
 - Azure.Identity 1.3.0
 - k8s

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by schaabs** [comment]
@momoliu-msft Thanks for filing this issue. To help us in our investigation can you please include the host you are running on. Is this running on VM, VMSS or an AKS cluster with pod identity?

**Comment by momoliu-msft** [comment]
Hi, it is AKS cluster with pod identity.

**Comment by christothes** [comment]
Hi @momoliu-msft -  If this is still an issue, would you mind providing the logging output after reproducing this with [logging enabled](https://github.com/Azure/azure-sdk-for-net/blob/e4c4e7f3985e73fb1e0ad56af1ba6bccf5bfe867/sdk/core/Azure.Core/samples/Diagnostics.md)?

**Comment by momoliu-msft** [comment]
Hi, @christothes, we do not see this recently. Closing it now.
