### ISSUE TITLE
[QUERY] Got 403 status code while invoking GetUserDelegationKeyAsync()

### ISSUE THREAD

**Issue by momoliu-msft** [Azure/azure-sdk-for-net#19247]
**Query/Question**
(Most of the time, the request succeeded.)

MSI credential in k8s clusters.

innerExceptionMessage

ManagedIdentityCredential authentication failed: Service request failed.
Status: 403 (Forbidden)

Content:
failed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: Bad Request

Headers:
X-Content-Type-Options: REDACTED
Date: Sat, 27 Feb 2021 18:10:27 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 110

What is the reason for getting this?

**Environment:**
 - Azure.Storage.Blobs 12.7.0
 - Azure.Identity 1.3.0
 - k8s

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
In order to see a bit more information about what is happening, could you [enable logging](https://github.com/Azure/azure-sdk-for-net/blob/e4c4e7f3985e73fb1e0ad56af1ba6bccf5bfe867/sdk/core/Azure.Core/samples/Diagnostics.md) and provide those details?
