### ISSUE TITLE
[QUERY] "No Managed Identity endpoint found." after successfully sending out request to the endpoint

### ISSUE THREAD

**Issue by momoliu-msft** [Azure/azure-sdk-for-net#19244]
**Query/Question**
I could see the imds identity endpoint is ready by sending request to "http://169.254.169.254/metadata/identity/oauth2/token?resource=https://vault.azure.net&api-version=2020-09-01". Then my service still failed to get user delegation key by calling GetUserDelegationKeyAsync().

message got:
"No Managed Identity endpoint found."

**Environment:**
 - Azure.Storage.Blobs 12.7.0
 - Azure.Identity 1.3.0
 - k8s

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
In order to see a bit more information about what is happening, could you [enable logging](https://github.com/Azure/azure-sdk-for-net/blob/e4c4e7f3985e73fb1e0ad56af1ba6bccf5bfe867/sdk/core/Azure.Core/samples/Diagnostics.md) and include those details?
