### ISSUE TITLE
[QUERY] Sending request to IMDS identity endpoint got 500 status code back

### ISSUE THREAD

**Issue by momoliu-msft** [Azure/azure-sdk-for-net#19241]
**Query/Question**
We got 500 status code while checking the IMDS identity endpoint and waiting for it to be ready. 

_Here is the innerExceptionMessage:_

ManagedIdentityCredential authentication failed: Service request failed.
Status: 500 (Internal Server Error)

Content:
pod list is empty

Headers:
X-Content-Type-Options: REDACTED
Date: Mon, 01 Mar 2021 11:02:42 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 18

What is the reason and what would be the suggestions to avoid any similar issues like this in the future?

**Environment:**
 - Azure.Identity 1.3.0
 - k8s

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @momoliu-msft - Please see the documentation for the IMDS endpoint here https://docs.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows#errors-and-debugging

**Comment by momoliu-msft** [comment]
We still see the error after adding a max wait time of 76s. Regardless of other requirements like end-to-end latency requirement, SLA, any suggestions for a better max wait time setup?
