### ISSUE TITLE
[BUG][blob storage] The leaseId fetched by sdk is different than then one set on azure portal.

### ISSUE THREAD

**Issue by star286** [Azure/azure-sdk-for-net#19258]
**Describe the bug**

I'm using the latest azure blob storage sdk for .net: **Azure.Storage.Blobs 12.8.0.**

Then I acquire a lease for a blob from azure portal directly, here I get a leaseId.

Then in my code, I'm trying to get the leaseId of that blob. The code like below:

           ```
           var c_client = blobServiceClient.GetBlobContainerClient("mycontainer");
            var blob = c_client.GetBlobClient("myblob");
            var c = blob.GetBlobLeaseClient();
            Console.WriteLine(c.LeaseId);
          ```

**Expected behavior**
The leaseId fetched by code should be matched with the one I get via azure portal.

**Actual behavior (include Exception or Stack Trace)**
The leaseId fetched by code is different than the one I get via azure portal.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by star286** [comment]
@jsquire hello, I want to know if somebody has looked into it? Thanks.

**Comment by jsquire** [comment]
Hi @star286.  Unfortunately, I'm only serving as first triage in this case.  I don't have insight into the current state or the process that the Storage team is using for their more focused triage.   I'll need to defer to @xgithubtriage for updates.

**Comment by amnguye** [comment]
Hi, In your snippet where are you acquiring a new lease? I see you've created your `BlobLeaseClient` but you didn't call Acquire or renew Lease.

Just to clarify calling `BlobLeaseClient.LeaseId` does not make the request to the service to get the current lease on the blob, if that was the expectation. If you create a `BlobLeaseClient` and you know the lease id on the blob (for security reasons you should know the lease), then when you go to create the client do.

`var blobClient = blob.GetBlobLeaseClient(leaseid)`

If you do not set the lease id, the client will automatically generate a lease id, and use that lease id for all operations. We do this out of convenience for the customer, so they know which lease Id will be used for future operations when the client is called.

**Comment by star286** [comment]
@amnguye yes,  I acquired a lease for a blob from azure portal directly. Then in the code I tried to get the lease id. Thanks for your clarification.

One thing need to confirm, If I've already acquired a lease for a blob from azure portal(like leaseid_1 for blob_1). And then in the code, I used BlobLeaseClient.LeaseId to get another lease id(like leaseid_2 for blob_1). I want to know if the 2nd lease id leaseid_2 can work for the blob blob_1as well?

**Comment by amnguye** [comment]
Sorry for the lack of response. In order to acquire another lease, you would have to provide the original lease.

"If the blob does not have an active lease, the Blob service creates a lease on the blob and returns a new lease ID. If the blob has an active lease, you can only request a new lease using the active lease ID" (from: https://docs.microsoft.com/en-us/rest/api/storageservices/lease-blob#request-headers)

**Comment by star286** [comment]
@amnguye wow, great answer! Thanks very much, I know it now:).
