### ISSUE TITLE
[QUERY] Blobs saved as octet-stream instead of image/jpeg

### ISSUE THREAD

**Issue by charconstpointer** [Azure/azure-sdk-for-net#19275]
**Query/Question**
Given IFormFile in a ASP.NET controller
```
[HttpPost]
public async Task<IActionResult> Upload(IFormFile formFile, CancellationToken cancellationToken)
```
and blob upload using new ContainerClient
```
var containerClient = blobServiceClient.GetBlobContainerClient("foo");
await containerClient.UploadBlobAsync(formFile.FileName, formFile.OpenReadStream(), cancellationToken);
```
My files end up being saved as 
```
application/octet-stream
```
instead of 
```
image/jpeg
```

I've verified that the content I'm trying to upload has the correct content-type set (image/jpeg in this case) 
```
formFile.ContentType; //image/jpeg
```
Is this behavior expected?

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.9.0-beta.1
 - Hosting platform or OS and .NET runtime version :  Windows 10 .NET Framework 5
 - IDE and version : JetBrains Rider 2021.1 EAP 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
@charconstpointer, you need to set the content type of the blob yourself, it is not autodetected.

```
BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient("foo");
BlobClient blobClient = containerClient.GetBlobClient(formFile.FileName);
BlobUploadOptions options = new BlobUploadOptions
{
    HttpHeaders = new BlobHttpHeaders
    {
        ContentType = "image/jpeg"
    }
};
await blobClient.UploadAsync(formFile.OpenReadStream(), options);
```

-Sean
