### ISSUE TITLE
[QUERY] Microsoft.Azure.ServiceBus Usage of ITokenProvider with SubscriptionClient

### ISSUE THREAD

**Issue by ColeSiegelTR** [Azure/azure-sdk-for-net#19283]
**Query/Question**

I am using `Microsoft.Azure.ServiceBus.SubscriptionClient` to connect to Azure Service Bus using shared access signatures.

Since the shared access signature token is short lived I need a way to update my `SubscriptionClient` connection so that it remains authorized over a long period. I figured that might be doable using `ITokenProvider` since there is a constructor for `SubscriptionClient` which takes `ITokenProvider` instead of a connection string or connection object. https://docs.azure.cn/zh-cn/dotnet/api/microsoft.azure.servicebus.subscriptionclient.-ctor?view=azure-dotnet#Microsoft_Azure_ServiceBus_SubscriptionClient__ctor_System_String_System_String_System_String_Microsoft_Azure_ServiceBus_Primitives_ITokenProvider_Microsoft_Azure_ServiceBus_TransportType_Microsoft_Azure_ServiceBus_ReceiveMode_Microsoft_Azure_ServiceBus_RetryPolicy

By implementing `ITokenProvider` and passing it to `SubscriptionClient`, I observed that for regular `MessageHandler` the token provider updates the connection with a new SAS when the `SecurityToken` has expired. This is great. However, the behaviour for `SessionHandler` is not the same. I've followed a similar implementation to https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.Azure.ServiceBus/Sessions/Program.cs and when I use the `ITokenProvider` constructor noted in the paragraph above, the SAS tokens are not refreshed based on the `SecurityToken` expiry. Instead, it appears that the session connection closes often based on `operationTimeout` (which is defaulted to 1 minute but could be included in the connection string). The timers in `ITokenProvider` are not actually utilized.

I think maybe this has something to do with how `ActiveClientLinkManager` https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Amqp/ActiveClientLinkManager.cs is used by the session implementation vs regular message handlers.

Can you please help to clarify the usage of the `ITokenProvider` for `SubscriptionClient`, or how the token refresh process may differ between `MessageHandler` and `SessionHandler`? Or otherwise suggest an approach to keep a long running `SubscriptionClient` connection open with short lived SAS tokens used for the connection?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ColeSiegelTR** [comment]
Here is a code sample to help clarify what I am trying to use and understand:

`
using System;
using System.Threading.Tasks;
using Microsoft.Azure.ServiceBus;
using Microsoft.Azure.ServiceBus.Primitives;

namespace SubscriptionClient
{
    class Program
    {
        static void Main(string[] args)
        {
            string endpoint = "sb://xxx.servicebus.windows.net/";
            string topicName = "topicabc";
            string initialSasToken = "SharedAccessSignature sr=xxx";
            string subscription = "subscription-name";
            TokenProvider tokenProvider = new TokenProvider();
            Microsoft.Azure.ServiceBus.SubscriptionClient client = new Microsoft.Azure.ServiceBus.SubscriptionClient(
                new ServiceBusConnection(new ServiceBusConnectionStringBuilder(
                    endpoint,
                    topicName,
                    initialSasToken))
                {
                    TokenProvider = tokenProvider,
                },
                topicName,
                subscription,
                ReceiveMode.PeekLock,
                null);
            
            client.RegisterSessionHandler(
               async (session, message, cancellationToken) =>
                {
                    Console.WriteLine("Got a message");
                    await session.CompleteAsync(message.SystemProperties.LockToken);
                },
                new SessionHandlerOptions(e => LogMessageHandlerException(e))
                {
                    MessageWaitTimeout = TimeSpan.FromSeconds(5),
                    MaxConcurrentSessions = 50,
                    AutoComplete = false
                });

            Task.WaitAny(
                Task.Run(() => Console.ReadKey()),
                Task.Delay(TimeSpan.FromSeconds(180)));
            
            client.CloseAsync();
        }
        
        private static Task LogMessageHandlerException(ExceptionReceivedEventArgs e)
        {
            Console.WriteLine("Exception: \"{0}\" {1}", e.Exception.Message, e.ExceptionReceivedContext.EntityPath);
            return Task.CompletedTask;
        }
    }

    class TokenProvider : ITokenProvider
    {
        // This gets called by many threads when using RegisterSessionHandler, and gets triggered at least once a minute due to operationTimeout
        // See SessionClient -> acceptMessageSessionTask = this.RetryPolicy.RunOperation(() => session.GetSessionReceiverLinkAsync(operationTimeout),operationTimeout);
        // It also gets called when new messages are sent to the Service Bus topic
        // When using RegisterMessageHandler, it only gets called based on the SecurityToken expiry time
        // Looking for clarification on this and what sessions are doing behind the scenes
        private static string newSasToken = "SharedAccessSignature sr=xxx";
        public Task<SecurityToken> GetTokenAsync(string appliesTo, TimeSpan timeout)
        {
            Console.WriteLine("Got a token! There must be a new session connection opening behind the scenes.");
            return Task.FromResult(
                new SecurityToken(
                    newSasToken,
                    DateTime.UtcNow.AddSeconds(180),
                    appliesTo,
                    "SharedAccessSignature")
            );
        }
    }
}
`

**Comment by ramya-rao-a** [comment]
@DorothySun216 Can you respond to the point on SessionHandler and the regular MessageHandler behaving differently when using TokenProvider?

@ColeSiegelTR Please note that a newer package Azure.Messaging.ServiceBus is available as of November 2020. While the older package Microsoft.Azure.ServiceBus will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the migration guide at https://aka.ms/azsdk/net/migrate/sb for more details.

In the newer package you can use the AzureSasCredential in the client constructor to make use of your shared access signature. @JoshLove-msft, do we have any sample that we can point to that uses the AzureSasCredential?

**Comment by KranthiPakala-MSFT** [comment]
@shankarsama Following up to see if there is any update on this issue? - Thank you

**Comment by JoshLove-msft** [comment]
> In the newer package you can use the AzureSasCredential in the client constructor to make use of your shared access signature. @JoshLove-msft, do we have any sample that we can point to that uses the AzureSasCredential?

No we don't have a sample for this.

**Comment by iamandymcinnes** [comment]
Hi

I just wondered if there is any input on this? The migration guide and documentation don't detail the AzureSasCredential approach which doesn't help when migrating from using the ITokenProvider in the previous SDK.

Many thanks

Andy

**Comment by ramya-rao-a** [comment]
Logged https://github.com/Azure/azure-sdk-for-net/issues/25787 to track the work to update the migration guide and a separate sample if needed.

cc @yvgopal for thoughts on the original issue with ITokenProvide when used in MessageHandler vs SessionHandler

**Comment by yvgopal** [comment]
Sorry to have kept this question open for so long.
No. SessionHandler also works fine with ITokenProvider. If a session is accepted, the SDK will keep renewing the token underneath.
To create a connection, one doesn't need any token. It is only to create links that tokens are needed. Once a link is created, the sdk keeps renewing the token when it is about to expire.
In case of a message handler, a link is created right away.
In case of a session handler, a link is created only if a session is available. If a session is not available, link creation will timeout after oepration timeout. That timeout is caused by non-availability of sessions, not because token expired. OperationTimeout has nothing to do with token renewal.

If token is really expired, the error message will clearly say that. It will never throw timeout.
