### ISSUE TITLE
Supplying custom TokenCredential for authentication in web job extensions with Event Hub / Storage checkpoint

### ISSUE THREAD

**Issue by remoba** [Azure/azure-sdk-for-net#19312]
**Query/Question**
If I understand correctly MSI / AAD App auth support was recently added to the extensions nuget through the use of `TokenCredential`. However it seems currently `TokenCredential` can only be extracted from configuration, so there's no option to inject a custom implementation.

The authentication strategy in my team is having a custom token provider, that can be either be implemented by using MSI or by AAD app with a certificate. In the latter option fetch the certificate from the key vault and parse it in-memory, so we never go through the certificate store, which means I can't really use the out-of-the-box `TokenCredential`.

For direct access packages (e.g. `Azure.Storage.Blobs`) we can simply inherit from `TokenCredential` and add our custom token-providing code, but here I don't see any option to do so.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0-beta.1
 - Hosting platform or OS and .NET runtime version (dotnet --info output for .NET Core projects): Windows 10 .NET Core 5
 - IDE and version : Visual Studio 16.8.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ramya-rao-a** [comment]
@pakrym Any thoughts here?

**Comment by pakrym** [comment]
There is no programmatic way to do it right now.

**Comment by jsquire** [comment]
Setting a custom credential is now possible by configuring DI in a custom functions startup via the `UseCredential` method.

```csharp
using System;
using System.Threading;
using System.Threading.Tasks;
using Azure.Core;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Azure.WebJobs;
using Microsoft.Extensions.Azure;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;

[assembly: FunctionsStartup(typeof(CustomFunctionsStartup.Startup))]

namespace CustomFunctionsStartup
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            // This registers whatever token credential type you'd like for ALL
            // Azure clients.
            builder.Services.AddAzureClients(builder =>
            {
                builder.UseCredential(new CustomTokenCredential());
            });
 
            // This is template code.  Unsure if needed to initialize Functions/WebJobs or
            // can be omitted.   
            var services = builder.Services;
            var wbBuilder = services.AddWebJobs(_ => {});

            wbBuilder.AddBuiltInBindings();
            wbBuilder.AddExecutionContextBinding();
        }
    }
```
