### ISSUE TITLE
Add SAS and other blob sanitization rules to the base framework

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#19316]
Other services use storage and don't know they need to add sanitization rules.

**Comment by weshaggard** [comment]
We should see if there is a way to plugin the credscan detection library into the framework to try and sanitize all the text in the recording files.

**Comment by pakrym** [comment]
We should consider sanitizing bodies too or adding a post-recording check that would throw if SAS signature is found.

**Comment by JoshLove-msft** [comment]
@weshaggard can you provide more details on the credscan library that we use?

**Comment by pakrym** [comment]
https://github.com/Azure/azure-sdk-tools/issues/1950 should handle this.

**Comment by JoshLove-msft** [comment]
Closing as this will be tracked by the linked Test Proxy issue - https://github.com/Azure/azure-sdk-tools/issues/1950
