### ISSUE TITLE
[409 - BlobHasBeenModified] Azure Storage Blobs Error Code not documented

### ISSUE THREAD

**Issue by melzayet** [Azure/azure-sdk-for-net#19311]
**Query/Question**

How can we help?

My code is occasionally getting 409 response with ErrorCode BlobHasBeenModified which is non-retriable being 400 level. I could not find any information on that error code.

- Code has continuous input of multiple data streams
- For every data steam, code creates new dotnet Task for uploading exactly two blobs
- The code uses new BlockBlobClient for every blob and later calls UploadAsync
- StorageTransferOptions Max Concurrency is set to number of processors
- Blobs uploaded are always more than 256 MB
- Code is continuously uploading data to an immutable container

1. Does BlobHasBeenModified error code map to any error code here: https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes?
2. Is there any case where StageBlock can suffer from multi-threads uploading same block? Or is there any case it could affect immutable blobs?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
  **Azure.Storage.Blobs 12.8.0**
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 **Azure VM - Windows Server 2019 - DOTNET 5.0** 
 - IDE and version : [e.g. Visual Studio 16.3]
 **Visual Studio 16.8.4**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
