### ISSUE TITLE
[BUG] BlobContainerClient.CreateIfNotExistsAsync Logs 409error

### ISSUE THREAD

**Issue by stefannikolei** [Azure/azure-sdk-for-net#19310]
using Azure.Storage.Blobs v12.8.0 the BlobContainerClient logs an 409 error in Application Insights. This is flooding my Failures in App Insights.

Should it really log an failure if this method is called.

The Problem seems to be the CreateInternal Method which seems to Log the Exception on every Exception and just the calling method has the Exceptionfilter applied

**Comment by jsquire** [comment]
//fyi:  @pakrym, @tg-msft

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by tg-msft** [comment]
This is waiting on https://github.com/Azure/azure-sdk-for-net/issues/9934.

**Comment by pakrym** [comment]
Dup https://github.com/Azure/azure-sdk-for-net/issues/19982
