### ISSUE TITLE
BlobLeaseClient uses string data type for lease id instead of guid

### ISSUE THREAD

**Issue by gasgesgos** [Azure/azure-sdk-for-net#19329]
**Describe the bug**
BlobLeaseClient allows for arbitrary strings as the lease id parameter, but only GUIDs are actually allowed at runtime.

**Expected behavior**
BlobLeaseClient constructor parameters should use GUID types if GUID types are the only allowable values. 

Using the specific type that aligns with the type necessary at runtime helps promote a self-documenting interface for the BlobLeaseClient constructors. The requirement for using a GUID is not documented in constructor comment/header documentation, nor in the [SDK documentation](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobleaseclient?view=azure-dotnet)

**Actual behavior (include Exception or Stack Trace)**

```text
The value for one of the HTTP headers is not in the correct format.
RequestId:d19c85fa-a01e-004c-3062-140fee000000
Time:2021-03-08T21:34:26.3763191Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Additional Information:
HeaderName: x-ms-proposed-lease-id
HeaderValue: notaguid

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: d19c85fa-a01e-004c-3062-140fee000000
x-ms-client-request-id: d7281c94-0282-4224-8734-87e8fffe3375
x-ms-version: 2020-04-08
x-ms-error-code: InvalidHeaderValue
Date: Mon, 08 Mar 2021 21:34:26 GMT
Content-Length: 336
Content-Type: application/xml
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```csharp
    var blobClient = containerClient.GetBlobClient("some_existing_file.txt");
    var leaseClient = new BlobLeaseClient(blobClient, "notaguid");
    var leaseClient.Acquire(TimeSpan.FromSeconds(20));
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.0
 - Hosting platform or OS and .NET runtime version: dotnet 5.0.103
 - IDE and version : VS 2019 16.8.5

**Comment by amnguye** [comment]
This isn't something that is not uncommon in our library where GUIDs are strings. However if we were to change this now, this would be a breaking change for all customers.

What we can do is provide better documentation for this property specifying that a GUID format for the lease id is required.
