### ISSUE TITLE
Azure.Storage.Queue Managed Identity Examples Do Not Work

### ISSUE THREAD

**Issue by Boaz101** [Azure/azure-sdk-for-net#19323]
The managed identity examples in https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.queues-readme?view=azure-dotnet-preview&source=docs do not work for Azure.Storage.Queues. The url and the type of client are wrong. The code should look like this:
Uri accountUri = new Uri("https://MYSTORAGEACCOUNT.queue.core.windows.net/");
Queue**Service**Client queue = new Queue**Service**Client(accountUri, new DefaultAzureCredential());

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2afd9939-f666-3438-a82a-9a7c32ee85ed
* Version Independent ID: 2d40c7be-4280-108a-ecc1-f77af98f9a5b
* Content: [Azure Storage Queues client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.queues-readme?view=azure-dotnet-preview&source=docs)
* Content Source: [api/overview/azure/storage.queues-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/storage.queues-readme.md)
* Service: **storage**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi,

It looks like you are correct.  I think we could also change the sample to:
```
Uri queueUri = new Uri("https://MYSTORAGEACCOUNT.blob.core.windows.net/QUEUENAME");
QueueClient queue = new QueueClient(queueUri, new DefaultAzureCredential());
```

**Comment by seanmcc-msft** [comment]
Resolved by https://github.com/Azure/azure-sdk-for-net/pull/20083
