### ISSUE TITLE
[BUG] BaseBlobClient.GenerateSasUri(BlobSasBuilder) requires container name and blob name despite error message stating otherwise, also throws unhandled NullReferenceException

### ISSUE THREAD

**Issue by gasgesgos** [Azure/azure-sdk-for-net#19330]
**Describe the bug**
When using BlobSasBuilder to create SAS tokens for a blob, there are a few odd scenarios that come up calling GenerateSasUri.

When the BlobSasBuilder's BlobContainerName or BlobName properties are empty (set to string.Empty), GenerateSasUri throws InvalidOperationException with a message about the name not matching. The same message then states that the name must either match the client's value **or be left empty**.  But it was empty, so the message is not correct.

When the BlobContainerName or BlobName are null, GenerateSasUri throws an unhandled NullReferenceException, which appears to come from [a check that the name matches the existing value in the client](https://github.com/Azure/azure-sdk-for-net/blob/2c0cc4e8966f4e3a0942aa46a1b7d255dc4f8400/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L4854).

**Expected behavior**
Expected error messages should reflect the error or values should default to be the only potential correct value if they are not specified or explicitly are empty. There is only one possible correct value for these properties anyways, so defaulting logic would be useful here. This is what GenerateSasUri(BlobSasPermissions, DateTimeOffset) does.

**Actual behavior (include Exception or Stack Trace)**

Value for BlobContainerName or BlobName are string.Empty => InvalidOperationException with a message that the value can be empty, which it is.

> System.InvalidOperationException: 'SAS Uri cannot be generated. BlobSasBuilder.BlobContainerName does not match BlobContainerName in the Client. BlobSasBuilder.BlobContainerName must either be left empty or match the BlobContainerName in the Client'

Value for BlobContainerName or BlobName are null => Unhandled NullReferenceException, instead of a message that the value needs to be populated (since it can't be empty).

> System.NullReferenceException: 'Object reference not set to an instance of an object.' at Azure.Storage.Blobs.Specialized.BlobBaseClient.GenerateSasUri(BlobSasBuilder builder)
   at AzureStorageLeaseId.Program.Main(String[] args) in C:\Users\gasge\source\repos\AzureStorageLeaseId\AzureStorageLeaseId\Program.cs:line 24

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Generates improper error message:

`   
var builder = new BlobSasBuilder(BlobSasPermissions.Read, DateTimeOffset.Now.AddDays(7))
    {
        BlobContainerName = string.Empty,
        BlobName = string.Empty
    };

    // Error message that indicates the values can be empty, which they are:
    blobClient.GenerateSasUri(builder);
`

Generates unhandled NullReferenceException: 
`
    var builder = new BlobSasBuilder(BlobSasPermissions.Read, DateTimeOffset.Now.AddDays(7));

    // Unhandled NullReferenceException:
    blobClient.GenerateSasUri(builder);
`

**Environment:**
Name and version of the Library package used: Azure.Storage.Blobs 12.8.0
Hosting platform or OS and .NET runtime version: dotnet 5.0.103
IDE and version : VS 2019 16.8.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
@amnguye, could you take a look?

**Comment by amnguye** [comment]
Yeah this is my bad for not providing a proper response.

Also for both the container name and blob name being both empty, looks like for some reason the exception is being thrown here. So we will look into providing a better exception as well as, if they provide empty parameters for both the container name and blob name, it should just use the values stored in the `blobclient` instead.

So I do agree we should be checking for the null values and providing a better exception that way users can correct the values placed in the `BlobSasBuilder` so that way they know what to fix in order to create their SAS.
