### ISSUE TITLE
[Digital Twins] weekly runs fail with DeploymentFailed error

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#19335]
Digital Twins weekly runs fail with:
>"error": {
      "code": "DeploymentFailed",
      "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
      "details": [
        {
          "code": "BadRequest",
          "message": "Subscription '***' has '10' instances in this region. Please visit http://aka.ms/dtv2limits for details."
        }
      ]
    }

looking at the error, it seems the resource hit the capacity.

For more details please check here:
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=744812&view=logs&j=b3c5e6b4-3625-542a-c71c-14f53e24907a&t=fba0a23f-5f2b-50ef-192c-04beb2c6bf1f&l=13131
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=757167&view=logs&j=29db982d-9ba6-5e12-d46b-2c3be1210716&t=3ce76081-8b44-57cc-7c29-7bbf3e757905&l=13112
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=769978&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=770245&view=results

**Comment by azabbasi** [comment]
#19339 is expected to fix this issue. Will monitor and close the issue on the next run.
