### ISSUE TITLE
[Perf/Blob] BlobContainerClient.GetBlobs() is slower than expected

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#19356]
`BlobContainerClient.GetBlobs()` is slower than expected.  .NET performance is comparable to Java for download and upload, but over 50% slower for list-blobs.

Scenario|Size|Parallel|Sync|.NET|Java
-----|-----|-----|-----|-----|-----
download|10,240|32|async|9,074|7,720
upload|10,240|32|async|5,161|5,231
list-blobs|500|32|async|155|383

Here's the Network and CPU utilization during the `list-blobs` test.  The network throughput indicates Java is downloading twice the HTTP responses, which confirms the operations/second.  CPU is fairly close, but it suggests both that .NET is less efficient (less operations per CPU), and that .NET is more bottlenecked on something other than CPU.

  | .NET | Java
-- | -- | --
Network (Mbps) | 526 | 1,100
CPU % | 79% | 90%

### Test Sources
.NET: https://github.com/Azure/azure-sdk-for-net/blob/de522d92a5366b7d0d2d7df9cfbd99fff3373833/sdk/storage/Azure.Storage.Blobs/perf/Azure.Storage.Blobs.Perf/Scenarios/GetBlobs.cs#L43-L49

Java: https://github.com/Azure/azure-sdk-for-java/blob/7a96ea9419eb0ccbcf9d712124ec6b06f39facd1/sdk/storage/azure-storage-perf/src/main/java/com/azure/storage/blob/perf/ListBlobsTest.java#L32-L36

**Comment by mikeharder** [comment]
We suspect the issue is the Java test is not fully consuming the results returned from listBlobs():

https://github.com/Azure/azure-sdk-for-java/blob/7a96ea9419eb0ccbcf9d712124ec6b06f39facd1/sdk/storage/azure-storage-perf/src/main/java/com/azure/storage/blob/perf/ListBlobsTest.java#L32-L36

**Comment by mikeharder** [comment]
I tried increasing the ThreadPool minimum workerThreads and completionPortThreads, but this slightly reduced perf (might be noise).

```
--count 500 --parallel 32: 208 ops/sec
--count 500 --parallel 32 --min-worker-threads 32 --min-completion-port-threads 32: 196 ops/sec
```

**Comment by seanmcc-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L2520

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Models/GetBlobsAsyncCollection.cs#L68

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobExtensions.cs#L1124

Probably something to do with the object conversions I had to do when we migrated to the new generator.

**Comment by Dan127001** [comment]
+1
Are there any plans in the near future to handle this?
