### ISSUE TITLE
Re-enable parallel test execution for Key Vault test base classes

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#19377]
In #11170 for #10496 I disabled parallel test execution due to concurrency issues, but to speed up testing `[NonParallelizable]` should be removed from the _*TestBase_ classes and concurrent issues dealt with. For example, but possibly not limited to:

* Enumerating keys and secrets should ignore managed keys and secrets (from certs).
* Enumerating any resource type should ignore 404s. When tests are running concurrently, enumerating a resource type while deleting other instances of that resource type will lead to 404s. Instead, each such test should create a sentinel it can specifically watch for when enumerating.

**Comment by pallavit** [comment]
@heaths - Given how we are trying to move away from testing service code, do you see value in us in enabling this scenario

**Comment by heaths** [comment]
Not move away from, but to reduce. Given that is tracked separately, I can close this one.
