### ISSUE TITLE
Are attributes mandatory when reading from Azure Cognitive Search

### ISSUE THREAD

**Issue by AlexTorianyk** [Azure/azure-sdk-for-net#19374]
Do I have to specify attributes like `SimpleField` on properties? I've copied my data by indexing from cosmos db, and I'm using the same model when trying to upload the documents but I'm getting 400. Copying over the object with those attributes included obviously works.

@Mohit-Chakraborty

**Comment by AlexGhiondea** [comment]
@AlexTorianyk you should specify those attributes on your models.
