### ISSUE TITLE
Blob Storage: Error in a comment, misleading.

### ISSUE THREAD

**Issue by gtondato** [Azure/azure-sdk-for-net#19379]
In: **Examples -> Uploading a blob**

It says:
```
// Get a reference to a blob named "sample-file" in a container named "sample-container"
```

But, it should say:

```
// Get a reference to a blob named "sample-blob" in a container named "sample-container"
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c63ab683-1a38-4ffa-e432-0a76346d9dc2
* Version Independent ID: 651c2fe9-d1c4-64b0-6d11-bd70feac305b
* Content: [Azure Storage Blobs client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.blobs-readme#feedback)
* Content Source: [api/overview/azure/storage.blobs-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/storage.blobs-readme.md)
* Service: **storage**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by seanmcc-msft** [comment]
@gtondato, I'm not seeing what you mean.  This line is accurate - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/samples/Sample01a_HelloWorld.cs#L51, `string blobName = Randomize("sample-file");` above.
