### ISSUE TITLE
[Storage]: More defaults for StorageTransferOptions

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#19384]
One of the issues in using Storage effectively is tuning `StorageTransferOptions`.  They're currently dialed in for running in Azure Compute which isn't a bad choice, but there are plenty of other good choices and we're making customers figure that out themselves.

First, we should make it easier to specify `StorageTransferOptions` globally.  Imagine if we had something like
```C#
public partial class BlobClientOptions : Azure.Core.ClientOptions
{
    // ...
    
    public StorageTransferOptions? UploadTransferOptions { get; set; }
    public StorageTransferOptions? TransferTransferOptions { get; set; }
}
```
that we use whenever an explicit `StorageTransferOptions` isn't passed to `Upload` or `Download*`.  Then customers could globally change the performance characteristics of their app per environment if needed.  It's worth considering whether we want different values for uploads vs. downloads and should have two properties.

Second, we should provide additional default `StorageTransferOptions` so people can get desired behavior more easily.  I'd like to add static properties like:
```C#
public partial struct StorageTransferOptions
{
    // It's already the default, but let's name it to improve discoverability
    public static StorageTransferOptions AzureCompute => new StorageTransferOptions();
    
    public static StorageTransferOptions Speed =>
        new StorageTransferOptions
        {
            // I'm pulling 2 cores per proc and 4 tasks per core out of nowhere, but we could test and tune this well
            MaximumConcurrency = Environment.ProcessorCount * 2 * 4,
            InitialTransferSize = 8 * Constants.MB
        };

    public static StorageTransferOptions SlowDevice =>
        new StorageTransferOptions
        {
            MaximumConcurrency = 1,
            InitialTransferSize = 1 * Constants.MB
        };

    // Assuming we have environment variables for well known environments like Compute, Functions, etc.
    public static StorageTransferOptions Environment =>
        Environment.GetEnvironmentVariable("AZURE_COMPUTE") != null ?
            AzureCompute :
            Speed;
}    
```

We could also add other helper methods like recommending the default concurrency for the given machine if we thought that added value.

If customers had existing code like:
```C#
var blob = new BlobClient(sasUri);
blob.Upload("<file-path-1>");
blob.Upload("<file-path-2>");
blob.Upload("<file-path-3>");
```

They could make it run much faster by changing to:
```C#
var options = new BlobClientOptions { UploadTransferOptions = StorageTransferOptions.Speed };
var blob = new BlobClient(sasUri, options);
blob.Upload("<file-path-1>");
blob.Upload("<file-path-2>");
blob.Upload("<file-path-3>");
```

**Comment by kasobol-msft** [comment]
Nice. There are also customers who ask about this being even smarter (like [here](https://github.com/Azure/azure-sdk-for-net/issues/14506#issuecomment-692998257)) .I.e. there should be `StorageTransferOptions.Auto` where runtime decides best settings reactively.

**Comment by tg-msft** [comment]
Adding a `bool AutoScale { get; set; }` property (but with a different, better name) to `StorageTransferOptions` that helps prevent uploads that are too slow (per the linked issue), and also allows changing the transfer size so we scale up to JumboBlobs when somebody passes a file that big (instead of throwing like we do today) would be awesome.

**Comment by kasobol-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-net/issues/21933 .

**Comment by tg-msft** [comment]
Discussed at the end of [Recording](https://msit.microsoftstream.com/video/b8920840-98dc-ae70-21f2-f1ec0b729db2)[MS INTERNAL ONLY] as well.
