### ISSUE TITLE
From ACR Arch Board: Consider removing ContainerRegistryUserCredential

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#19394]
Per security concerns, consider removing ContainerRegistryUserCredential type.

@pallavit  to confirm this is warranted.

**Comment by annelo-msft** [comment]
@pallavit, can you confirm that we want to do this?

**Comment by pallavit** [comment]
Yes, we only want to support AAD backing model and anonymous access - (for the read scenarios likes pull images and list the catalog).

**Comment by annelo-msft** [comment]
Thanks @pallavit !  Updated the [APIView](https://apiview.dev/Assemblies/Review/ba57bf904e524ce3bf647dad124ddc7c/12cb5d5471dd467da550ffe6b63c202d?doc=False) to reflect this.
