### ISSUE TITLE
[QUERY] Storage: Migration from v11 to v12 (Download, Upload)

### ISSUE THREAD

**Issue by asafzafrany** [Azure/azure-sdk-for-net#19422]
Hello,

I'm in the process of migrating from Azure.Storage.Blobs v11 to v12.
I'm struggling to find the following:

1. In v11 there was the following field:
Microsoft.Azure.Storage.Shared.Protocol.Constants.HeaderConstants.UserAgent

In v12 I found this:
Azure.Core.HttpHeader.Names.UserAgent

Is this indeed the equivalent?

2. In v11 there was the following field:
Microsoft.Azure.Storage.OperationContext.GlobalSendingRequest

In v12 I could not find the equivalent. 
Would like direction on that.

3. In v11 when uploading a page blob, it was quite simple to add a timeout.
In v12 I'm using the following method:
PageBlobClient.UploadPagesAsync
And I could not find any overload that contains a timeout
Would appreciate guidance on the matter.

4. In v11 when downloading a blob, there was an option to add an offset.
In v12 I'm using the following method:
BlobBaseClient.DownloadToAsync
And I could not find any overload that contains an offset
Would appreciate guidance on the matter.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): netstandard2.0
 - IDE and version : Rider 2020.3.1 or Visual Studio 2019

Thanks in advance

**Comment by asafzafrany** [comment]
Hello,

Any update on the matter?

Thanks

**Comment by lilyjma** [comment]
@amnguye, @seanmcc-msft: I was wondering if you could help to answer this question

**Comment by amnguye** [comment]
For 1 & 2 these both moved to the Azure.Core package. You would have to inject your `HttpMessage` to the `HttpPipelinePolicy`, there's a sample here, but let me know if you need a more detailed sample.
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Pipeline.md

As for 3, are you referring to the timeout in the retry policy? https://github.com/Azure/azure-sdk-for-net/issues/16980 Here's a duplicate issue. If you're saying a timeout on the entire request, you could look to setting the `CancellationToken` on the operation or inject something into the policy.

As for 4, have you tried using `DownloadStreaming` yet (This has a range you can specifiy)? As far as I can see in v11 ranges / offset are only for streams or byte arrays, so this would match the API you are looking for. 
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.downloadstreamingasync?view=azure-dotnet#Azure_Storage_Blobs_Specialized_BlobBaseClient_DownloadStreamingAsync_Azure_HttpRange_Azure_Storage_Blobs_Models_BlobRequestConditions_System_Boolean_System_Threading_CancellationToken_

**Comment by amishra-dev** [comment]
Please reactivate if you have any further questions
