### ISSUE TITLE
[BUG] BearerTokenAuthenticationPolicy AccessTokenCache request optimization causes problems with cancellation

### ISSUE THREAD

**Issue by egraff** [Azure/azure-sdk-for-net#19424]
**Describe the bug**
Prerequisite for the bug is that the `BearerTokenAuthenticationPolicy`'s `AccessTokenCache` does not already have a cached access token, or the previously cached access token has expired. From this state, the next request to be processed will hit one of these two cases in `GetTaskCompletionSources`:

 - https://github.com/Azure/azure-sdk-for-net/blob/8970711b5c82c9fac3f7135529ab57de5a294f08/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs#L153-L158

 - https://github.com/Azure/azure-sdk-for-net/blob/8970711b5c82c9fac3f7135529ab57de5a294f08/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs#L175-L180

In both cases, the calling code in `GetHeaderValueAsync`, which looks like this

https://github.com/Azure/azure-sdk-for-net/blob/8970711b5c82c9fac3f7135529ab57de5a294f08/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs#L97

will have `headerValueTcs` set to the cached (and newly created) `_infoTcs`, and `getTokenFromCredential` is set to `true`.

Next, `GetHeaderValueAsync` will execute the following code:

https://github.com/Azure/azure-sdk-for-net/blob/8970711b5c82c9fac3f7135529ab57de5a294f08/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs#L110-L124

Note that the message's `CancellationToken` is passed as argument to `GetHeaderValueFromCredentialAsync`.

Now, if another request is processed by the `BearerTokenAuthenticationPolicy` before `GetHeaderValueFromCredentialAsync` has been able to complete the process of acquiring an access token, it will hit this case in `GetTaskCompletionSources`:

https://github.com/Azure/azure-sdk-for-net/blob/8970711b5c82c9fac3f7135529ab57de5a294f08/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs#L160-L165

and after returning to `GetHeaderValueAsync`, it will execute the following code:

https://github.com/Azure/azure-sdk-for-net/blob/8970711b5c82c9fac3f7135529ab57de5a294f08/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs#L127-L146

Note that the `headerValueTcs` is the same as the `_infoTcs` created by the previous request.

Now, if the first request is cancelled, and `GetHeaderValueFromCredentialAsync` still hasn't been able to complete the process of acquiring an access token for that first request, the `_infoTcs` will be cancelled by the call to `SetCanceled()` as shown above. This means that the second request is affected, since it is waiting for the outcome of `_infoTcs`, and will fail with a `TaskCanceledException` as a result of this.

**Expected behavior**
The second request should not fail, as a result of the first request being canceled.

**Actual behavior (include Exception or Stack Trace)**
The second request will fail, because it is affected by the caching/optimization in `AccessTokenCache` going wrong when the first request is canceled.

**To Reproduce**
I have reproduced this using integration tests I am writing for some application code that is using Azure Blob Storage. Unfortunately, the integration tests have too many dependencies on our private integration test tools to be included in its entirety here. However, the main part of the test looks roughly like this:

```csharp
using (var cts = new CancellationTokenSource())
{
    Task firstReq = blobServiceClient.CreateBlobContainerAsync(
        "newBlobContainer",
        cancellationToken: cts.Token
    );
    Task secondReq = blobServiceClient.CreateBlobContainerAsync(
        "anotherBlobContainer",
        cancellationToken: CancellationToken.None
    );

    await getTokenRequestMadeTcs.Task.ConfigureAwait(false);
    cts.Cancel();
    await Task.Delay(100, CancellationToken.None).ConfigureAwait(false);
    getTokenResponseDelayTcs.SetResult(null);

    try
    {
        await firstReq.ConfigureAwait(false);
    }
    catch (OperationCanceledException)
    {
    }

    await secondReq.ConfigureAwait(false);
}
```

The `getTokenRequestMadeTcs` and `getTokenResponseDelayTcs` are `TaskCompletionSource`s I use to delay the token request (made by `GetHeaderValueFromCredentialAsync`) to ensure the second request ends up in the state where it is waiting for the `_infoTcs` created by the first request.

The test fails on `await secondReq.ConfigureAwait(false);`, which will throw a `TaskCanceledException` when it shouldn't.
Also note that I had to configure the `blobServiceClient` (an instance of `BlobServiceClient`) with `RetryOptions` that has `MaxRetries` set to zero, to provoke the exception to bubble back to the caller, since otherwise, the second request would be retired. This does not mean that the observed behaviour is not a bug, since there shouldn't be any expectations about how the `RetryOptions` have been configured for this to work properly.

**Environment:**
 - Name and version of the Library package used: Azure.Core 1.9.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
