### ISSUE TITLE
[BUG] Form Recognizer Client – unable to json Serialize/Deserialize output needed for unit testing

### ISSUE THREAD

**Issue by chrizy** [Azure/azure-sdk-for-net#19428]
When creating unit tests for processing the FormPageCollection result, I ideally want to store (Serialize/Deserialize) the FormPageCollection object. However, 
1.	It currently errors as it has no parameter less constructer when calling Deserialize
2.	When using Serialize, the FormElement BoundingBox PointF does not output.

Can this be fixed or how do suggest the processing of FormPageCollection can be unit tested without having it call your API to create the object?

**Expected behavior**
I eould like to be able to unit test the output from Form Recognizer Client

Using Azure.AI.FormRecognizer v3.0.0

Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Hi @chrizy !
You could use our [FormRecognizerModelFactory](https://docs.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.models.formrecognizermodelfactory?view=azure-dotnet) class that will help you instantiate the objects that have private constructors. That way you don't need to serialize/deserialize the objects.

See a sample of it here:  https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/Sample_MockClient.md

Let me know if that helps

**Comment by chrizy** [comment]
Hi,
It helps a little, I'm dealing with large 9+ page documents so it would involve quite a bit of work to setup the text cases compared to just using some sample API output. Currently I have re-created your object structure so that I can store the output for use in unit tests and that has resolved the issue for me, happy for this to be closed as its no longer blocking me.
Thanks
Chris

**Comment by maririos** [comment]
Glad it worked out. 
Thank you!
