### ISSUE TITLE
[QUERY] AzureBlobXmlRepository is marked internal while it's previous version in AspNetCore repo was public

### ISSUE THREAD

**Issue by RamjotSingh** [Azure/azure-sdk-for-net#19449]
**Query/Question**
Current [AzureBlobXmlRepository.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Blobs/src/AzureBlobXmlRepository.cs) is marked internal while its [previous version in AspNetCore repo was public](https://github.com/dotnet/aspnetcore/blob/cf2c5c9c6dca430b97aa96429b84d0da07eb77f1/src/DataProtection/AzureStorage/src/AzureBlobXmlRepository.cs) this makes migration very tricky. The only option is to copy over the code. Would it be possible to mark the current implementation public?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
@RamjotSingh, are you using the AzureBlobXmlRepository directly? What's the use case you have?

**Comment by RamjotSingh** [comment]
The use case was use unique blob accounts in certain cases or resolve the account at runtime rather than Startup time.

**Comment by pakrym** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/19788
