### ISSUE TITLE
Update documentation with AzurePowerShellCredential

### ISSUE THREAD

**Issue by olandese** [Azure/azure-sdk-for-net#19450]
With version 1.4.0 AzurePowerShellCredential will be added, this document needs to be updated
See: https://github.com/Azure/azure-sdk-for-net/pull/17081

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f73df56-2312-5851-7b59-3dfb766e5f66
* Version Independent ID: 31be349e-063e-6696-bc5f-752c413fa079
* Content: [Azure Identity client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme)
* Content Source: [api/overview/azure/identity-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/identity-readme.md)
* Service: **identity**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
@christothes:  I don't see any mention of the `AzurePowerShellCredential` in the Identity [README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/README.md), so I don't believe this is a pending update or refresh issue.  Would you please be so kind as to offer your thoughts?

**Comment by jsquire** [comment]
Hi @olandese.   Thank you for your feedback.  Tagging and routing the team member best able to assist.
