### ISSUE TITLE
[QUERY] Not able to read AVRO file (following the tutorial for event-hubs + apache drill)

### ISSUE THREAD

**Issue by Nordes** [Azure/azure-sdk-for-net#19452]
**Query/Question**
It's regarding [streaming-at-scale/eventhubs-capture/](https://github.com/Azure-Samples/streaming-at-scale/tree/main/eventhubs-capture). 

I tried it with by sending basic data such as described in the MSDN doc (https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-send). However, when I try to read the avro files, it simply fails. I tried to download the avro file locally and I have the same issue.

Is there any particular configuration that are required on the event hub in order to make Apache Drill to work with the content of Event Hubs?

```sh
apache drill> select * from dfs.`temp/16.avro`;
Error: UNSUPPORTED_OPERATION ERROR: 'complex union' type is not supported

Column: value
Fragment: 0:0

[Error Id: c0f67d7f-a43d-4efc-b643-b1ff48660a4b on host.docker.internal:31010] (state=,code=0)
```
> Note: I also tried to convert to JSON, but the issue remain the same.

**Environment:**
 - Windows 10 - Local install, Docker and WSL produce the same issue.

**Comment by jsquire** [comment]
Hi @Nordes.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, we can't offer support for Apache Drill, as it is a third party product and not part of the Azure offerings.  The sample that you linked is not one that I'm familiar with nor that the Azure SDK or Event Hubs teams own.   

You may want to consider opening an issue in the [Azure-Samples](https://github.com/Azure-Samples/streaming-at-scale/issues) repository and mentioning @yorek and @algattik.  Looking through the history, they seem to be the authors of that sample and may have insight that can help.

**Comment by Nordes** [comment]
Thank's I'll do that. I tough I was already in the good repository. My bad.
