### ISSUE TITLE
Default shared HttpClientTransport might not reflect DNS changes

### ISSUE THREAD

**Issue by tpajurek-dtml** [Azure/azure-sdk-for-net#19457]
Default shared `HttpClientTransport` is currently constructed as follows:

```csharp
var httpClientHandler = new HttpClientHandler();
return new HttpClient(httpClientHandler);
```
in the https://github.com/Azure/azure-sdk-for-net/blob/f92de12bd669d9dd5f64dd1490be773de69b5dbb/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs#L128 

.

The transport (and by extension the SDK clients) are encouraged to be used as singleton as described e.g. here 

https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/ .

I think that this combination is subjected to the well known [issue ](https://github.com/dotnet/runtime/issues/18348) of `HttpClient` that causes DNS changes not to be reflected. 

Should the `HttpClientTransport` create its `HttpClient` with the newer `SocketsHttpHandler` to prevent the issue, as described e.g. here

https://www.stevejgordon.co.uk/httpclient-connection-pooling-in-dotnet-core

?

I have something like this on my mind:

```csharp
var socketsHandler = new SocketsHttpHandler
{
    PooledConnectionLifetime = TimeSpan.FromMinutes(4),
    PooledConnectionIdleTimeout = TimeSpan.FromMinutes(4),
};

var httpClient= new HttpClient(socketsHandler);
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Yes, I think we want a shorter timeout than infinity. 4 minutes might be too short but I'll work on figuring out the correct one.

**Comment by QiaochuShen** [comment]
Looking at the code, it seems the issue was resolved for .net core 2.1+ (`SocketsHttpHandler`) and .net framework (HttpWebRequestTransport), but not resolved for .net standard 2.0?
