### ISSUE TITLE
[BUG] Form Recognizer - Table Row and Column Indexing not accurate

### ISSUE THREAD

**Issue by chrizy** [Azure/azure-sdk-for-net#19461]
Apologies if this is not the correct place to raise, I am finding the auto Table parsing not completely accurate. Trying to train models on multple documents has not improved things.

Take the following example
![image](https://user-images.githubusercontent.com/3624292/110864975-c8d71980-82ba-11eb-8dde-f7a8320635a3.png)

The highlighted text has been placed in row 16 column 8, when it should be part of row 17.

Using Azure.AI.FormRecognizer v3.0.0

Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Thanks @chrizy for the information. 
Looping @NHaiby @ramparab as in this case, the information is coming directly from the service

**Comment by anrothMSFT** [comment]
Looping @esclee in as owner

**Comment by NHaiby** [comment]
Please also try out the new release which enables you to label and train on tables. 
https://docs.microsoft.com/en-us/azure/cognitive-services/form-recognizer/whats-new

**Comment by AlexGhiondea** [comment]
@esclee @NHaiby @anrothMSFT can you help with this issue?

**Comment by KranthiPakala-MSFT** [comment]
@esclee @NHaiby @anrothMSFT - Following up to see if there is any update on this issue? - Thank you

**Comment by kinelski** [comment]
@chrizy Can you still reproduce this issue with the latest SDK version (4.0.0-beta.3)?
