### ISSUE TITLE
Ending Dot on URL

### ISSUE THREAD

**Issue by TheTilodon** [Azure/azure-sdk-for-net#19479]
![image](https://user-images.githubusercontent.com/5927783/110927983-a2e75e80-8326-11eb-957b-267c01f1a335.png)

In the URL https://docs.microsoft.com/en-us/azure/iot-pnp/howto-manage-digital-twin. is an ending dot, So it's clicked the page is not found. Removing the dot will fixe this issue. =)

**Comment by jsquire** [comment]
Hi @TheTilodon.  Thank you for your feedback.  It looks like the content for that article is sourced from the MS Docs repository.   I'm going to close this out and transfer the issue there so that the folks best able to assist are more likely to see it.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@jsquire I believe the document that @TheTilodon found this in is the C# reference for the [DigitalTwinClient Class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.digitaltwinclient?view=azure-dotnet#methods).

While the [feedback](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.digitaltwinclient?view=azure-dotnet#feedback) section at the bottom of the page points to [Azure/azure-docs-sdk-dotnet](https://github.com/Azure/azure-docs-sdk-dotnet) repo, the content source seems to be the [Azure/azure-docs-sdk-dotnet](https://github.com/Azure/azure-docs-sdk-dotnet) repository. Not sure if this is expected.

Nonetheless, I've created a new issue here: [#1919](https://github.com/Azure/azure-docs-sdk-dotnet/issues/1919) to get this addressed. Please let me know if that isn't the right place for this issue.
