### ISSUE TITLE
Communication.Identity:  CommunicationUserIdentifier type definition is not in sync with javascript sdk

### ISSUE THREAD

**Issue by guru98** [Azure/azure-sdk-for-net#19483]
The 2 sdk have different definitions for CommunicationUserIdentifier type last version (beta.5)
in .net  the property that contains the communication id is id while in javascript is communicationUserId

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by DominikMe** [comment]
Hi @guru98 , thanks for reaching out!

We're striving to make the SDKs consistent across languages but sometimes languages are different enough that we diverge. In this case TypeScript uses interfaces and you can pass in object literals like `{ communicationUserId: "<actual id>" } and `{ phoneNumber: "#123456789" }` which we've felt to be more idiomatic to JavaScript than using classes. In C# classes are the idiomatic way to model these identifier types.

Let us know any more feedback and how we can improve to make the usage patterns more clear.

**Comment by guru98** [comment]
Understand but in the case of communicationUserToken the json properties are different that make inconsistent, for example use an azure function written in .net to provide token to a javascript app. I fixed it using my own json
Regards

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: ***@***.***>
Inviato: giovedì 1 aprile 2021 01:32
A: ***@***.***>
Cc: Ugo ***@***.***>; ***@***.***>
Oggetto: Re: [Azure/azure-sdk-for-net] Communication.Identity: CommunicationUserIdentifier type definition is not in sync with javascript sdk (#19483)


Hi @guru98<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fguru98&data=04%7C01%7C%7C88e17a84166849ddc60e08d8f49d4135%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637528303522248723%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ngvZWmxUr4DtNO7UM8uX4zqGHk1G%2FuOQKcRWbfQvVos%3D&reserved=0> , thanks for reaching out!

We're striving to make the SDKs consistent across languages but sometimes languages are different enough that we diverge. In this case TypeScript uses interfaces and you can pass in object literals like { communicationUserId: "<actual id>" } and { phoneNumber: "#123456789" }` which we've felt to be more idiomatic to JavaScript than using classes. In C# classes are the idiomatic way to model these identifier types.

Let us know any more feedback and how we can improve to make the usage patterns more clear.

**Comment by DominikMe** [comment]
@guru98 Thanks for sharing your specific use case. You're right, we're not helping much in terms of serializing a C# model and then deserializing it as the corresponding JS model. 

What you described with a .NET token issue route and a JS client is a common scenario, we can see if we can improve our documentation around that and provide code snippets.

cc @ProbablePrime

**Comment by DominikMe** [comment]
Taking this back to the team to discuss supporting the flow you described better.
