### ISSUE TITLE
Permissions required when tagging resources

### ISSUE THREAD

**Issue by nads205** [Azure/azure-sdk-for-net#19480]
I am trying to trying to update tags (adding tags but also removing/updating) on the resources of type ```Microsoft.Compute```.

I have a service principal that has been granted [Tag Contributor](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#tag-contributor), however I receive this when updating the tag using the code below:

```The client '<guid>' with object id '<guid>' does not have authorisation to perform action 'Microsoft.Compute/disks/write' over scope <resource id> or the scope is invalid```. 

Please can you take a look at the code below either let me know if it can be modified so I can get away with the tag contributor permission or will I need to grant my service principal a higher level of privileges?

```c#

var azureCredentials #set above

using (var client = new Microsoft.Azure.Management.Resources.ResourceManagementClient(azureCredentials))
{
  var tags = new Dictionary<string, string>
  {
   { "environment", "test" },
   { "department", "tech" }
  };

  try
  {
    var result = await client.Resources.CreateOrUpdateAsync(resourceGroupName, resourceIdentity, genericResourceParameters, cts.Token);
    if (result.StatusCode == System.Net.HttpStatusCode.OK)
    {
      System.Console.WriteLine(string.Format("Tags updated for {0}", resource.Name));
      InsertLogEntry(resource.Id, true, null);
    }
  }
  catch (Hyak.Common.CloudException cloudException)
  {
    System.Console.WriteLine(string.Format("Caught Hyak.Common.CloudException when updating {0}, {1}", resource.Name, cloudException.Message));
  }
}

```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nisha-bhatia** [comment]
Thank you for your feedback, we are routing to the appropriate team for follow-up.

**Comment by nads205** [comment]
Hi @allenjzhang - small chaser - please let me know your thoughts on this

**Comment by allenjzhang** [comment]
To leverage the `tag contributor` permission, the call must explicitly go thru `tags` operation instead of general update operation on the resource. Otherwise the underlying call is a PUT on  `/provider/Microsoft.Provider/xxx` instead of `/provider/Microsoft.Provider/xxx/provider/Microsoft.Resource/tags/default` which triggers different RBAC.

Here is the sample code. You can look into TagsOperation documentation.  Methods without `AtScope` are creating default tags collections at subscription level vs ones with it applying the tags on each resource (specified with scope). Hope this clear it up. 

```
                    var patchTags = new TagsPatchResource(
                        "Delete",
                        new Tags(new Dictionary<string, string>
                            {
                                { "environment", "test2" },
                                { "department", "tech2" }
                            }));

                    var result = await client.Tags.UpdateAtScopeAsync(
                        "/subscriptions/XXX/resourceGroups/XX/providers/Microsoft.Network/networkSecurityGroups/XXX",
                        patchTags);
```

**Comment by nads205** [comment]
Can you let me know which namespace `client `sits? 

I'm using `Microsoft.Azure.Management.Resources.ResourceManagementClient`, however the `UpdateAtScopeAync `gives a compiler error CS106:

`'ITagOperations' does not contain a definition for 'UpdateAtScopeAsync' and no accessible extension method 'UpdateAtScopeAsync' accepting a first argument of type 'ITagOperations' could be found (are you missing a using directive or an assembly reference?)	`

Please can you put in an example into sample repository and share with me perhaps - or point me to an existing one? Failing that let me know the correct namespace/assembly. 

Thanks.
