### ISSUE TITLE
Stop intellisense pollution / No method extensions on type object!

### ISSUE THREAD

**Issue by aureole82** [Azure/azure-sdk-for-net#19481]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/search/Azure.Search.Documents/src/SearchClientBuilderExtensions.cs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
These extension methods are not on the object, the bug is in the compiler and is tracked by https://github.com/dotnet/roslyn/issues/39689
