### ISSUE TITLE
Understand what the failures are for Track2 in CredScan

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#19492]
Goal: Understand which and why credscan errors there are for track2 libraries

For a period of 2 weeks, we should monitor the [net - aggregate-reports](https://dev.azure.com/azure-sdk/internal/_build?definitionId=1399&_a=summary) pipeline, look into the Track2 errors, and understand what is happening and what the possible fix could be.

Details:
- Look into the step `Run CredScan` step for the failures.
- For more information (logs that include the exact line in the file that is being flagged):
  - Download the sarif file (like json or txt) and open in a text editor.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/9868623/111008830-d0dc9b00-8346-11eb-9f4b-cb82d0b1fc16.png)

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/9868623/111008868-ef429680-8346-11eb-8e96-0ca9b3e686c2.png)

For more information, ping @sima-zhu

**Comment by pakrym** [comment]
Those results are pretty clean!

**Comment by maririos** [comment]
@pakrym what do you mean?

**Comment by pakrym** [comment]
I'm looking at https://dev.azure.com/azure-sdk/internal/_build/results?buildId=780697&view=logs&j=10327055-d4d6-50a6-a312-3d2cd4bd9cb9&t=85d8bc15-d2a9-5b63-fbab-33f0a1192a0d and all errors seem plausible/reasonable and there are only ~60 of them.

**Comment by ShivangiReja** [comment]
Attaching a report I've made where I listed some of the data plane track-2 issues -
[CredScan-Track2.xlsx](https://github.com/Azure/azure-sdk-for-net/files/6260955/CredScan-Track2.xlsx)
