### ISSUE TITLE
EventHub Checkpoint payload is of zero bytes

### ISSUE THREAD

**Issue by sriharshatechi** [Azure/azure-sdk-for-net#19514]
**Query/Question**
I have implemented EventHub Reader using EventProcessorClient. Checkpoint is performed as follows:
 **_args.UpdateCheckpointAsync(args.CancellationToken).ConfigureAwait(false); ._**
When checked blob in the container/storage account , the blob files are of zero size. I was expecting the blob to contain EventData in json serialized form. Wrote a sample application , just to make sure that this isn't a problem with our application. The same behavior was observed in the  sample application.

**Environment:**
 -  Azure.Messaging.EventHubs.Processor 5.3.0
 - .net core 3.1
 - VS 16.9.1

**Comment by jsquire** [comment]
Hi @sriharshatechi.  Thank you for reaching out.  What you're seeing is expected;  checkpoint blobs contain no body.  The checkpoint attributes are set as part of the blob metadata with fields containing the offset and sequence number.  The name/path of the blob provides the rest of the information needed for the processor to operate.

**Comment by sriharshatechi** [comment]
@jsquire Thanks. I was able to locate the metadata. Can the documentation be updated so that this point can come out in a succinct manner.
