### ISSUE TITLE
[QUERY] Microsoft.Azure.WebJobs.Host.Storage vs Microsoft.Azure.WebJobs.Extensions.Storage.Blobs

### ISSUE THREAD

**Issue by mderriey** [Azure/azure-sdk-for-net#19515]
**Query/Question**

I'm super keen to start using the `Microsoft.Azure.WebJobs.Extensions.Storage.Blobs` and `Microsoft.Azure.WebJobs.Extensions.Storage.Queues` packages as they natively support Azure Identity, which would allow us to have credential-less WebJobs.

I'm confused about the feature parity between `Microsoft.Azure.WebJobs.Host.Storage` and `Microsoft.Azure.WebJobs.Extensions.Storage.Blobs`.
I understand the new packages provide for a ready-to-use replacement for blob/queue bindings and triggers, but I'm not sure about the hosting aspect.

`Microsoft.Azure.WebJobs.Host.Storage` has [a `.AddAzureStorageCoreServices()` method](https://github.com/Azure/azure-webjobs-sdk/blob/b36006c56969cbaadce95b34d37ed413728b5c1f/src/Microsoft.Azure.WebJobs.Host.Storage/RuntimeStorageWebJobsBuilderExtensions.cs#L29-L46) which "makes the Runtime itself use storage for its internal operations".
Unfortunately, this method uses the v11 SDK, which only supports authentication to the storage account via a connection string.

Do the new `.AddAzureStorageBlobs()` and `.AddAzureStorageQueues()` methods provide the same capability?
I found this piece of test code which calls boths methods: https://github.com/Azure/azure-sdk-for-net/blob/d263f23aa3a28ff4fc4366b8dee144d4c0c3ab10/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Scenario.Tests/tests/BlobBindingEndToEndTests.cs#L704-L714

A few questions to try and summarise my confusion:

1. What benefits does calling `.AddAzureStorageCoreServices()` have?
2. What do we risk losing if we decide not to call it in our WebJobs?

/cc @pakrym as he seems to be the one working on these integrations.

**Environment:**
 - Name and version of the Library package used:
    - `Microsoft.Azure.WebJobs.Extensions` v4.0.1
    - `Azure.Storage.Blobs` v12.8.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): App Service using .NET 5
 - IDE and version: VS 2019 v16.9.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by kasobol-msft** [comment]
@mderriey There's still work pending to support Azure Identity end to end in functions. Please see https://github.com/Azure/azure-functions-host/issues/6423#issuecomment-773659251 for more details.

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
