### ISSUE TITLE
[BUG] Azure.Storage.Blobs - Invalid computed signature when updating blob metadata

### ISSUE THREAD

**Issue by bbo76** [Azure/azure-sdk-for-net#19521]
Hello there,
I have a .net core console app to upload blob in Azure and when I try to call the SetMetaData I get a HTTP 403 error:

> Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
> RequestId:xxxxxxxxxxxxxxxxxxxxxxxxxxxx
> Time:2021-03-15T15:09:31.6350209Z
> Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
> ErrorCode: AuthenticationFailed
> 
> Additional Information:
> AuthenticationErrorDetail: The MAC signature found in the HTTP request '+jbtOBnJZyjIHbzbg2VpSFHMXXXXXXXXXXXX=' is not the same as any computed signature. Server used following string to sign: 'PUT

I only get this error when I put string with '.' character. I wanna store a version of package in the metadata like '10.0.1.5' and with this value it throw the 403, not when I juste put a string like "hello". When I try to put the same metada with Azure Storage Explorer or directly in Azure portal, I don't have any problems with version storage.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by seanmcc-msft** [comment]
Hi @bbo76,

Metadata is set to the Storage Service as individual HTTP Headers [Set Metdata](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata).

Header values must be ASCII characters, with special characters encoded - https://stackoverflow.com/questions/47687379/what-characters-are-allowed-in-http-header-values

I recommend URL encoding your metadata values before attempting to set blob metadata.

-Sean

**Comment by bbo76** [comment]
Hi @seanmcc-msft , yes I know this, but my metadata is something like '10.0.1.2' so it's already URL encoded. The problem is with the computed Authorization header generated by the method SetMetadata
