### ISSUE TITLE
GenerateSasUri encodes url / characters partially to %2F

### ISSUE THREAD

**Issue by spylkkanen** [Azure/azure-sdk-for-net#19525]
**Describe the bug**
GenerateSasUri method creates Sas uri where url path is partially encoded. e.g.
`https://mydomain.blob.core.windows.net/test-data/MyData%2Ftest_file.txt?sv=2020-04-08&se=2021-03-15T17%3A47%3A20Z&sr=b&sp=r&sig=...`

`https://mydomain.blob.core.windows.net/test-data/MyData%2Ftest_file.txt`

Should it be either of following
`https://mydomain.blob.core.windows.net/test-data/MyData/Ftest_file.txt` or `https://mydomain.blob.core.windows.net%2Ftest-data%2FMyData%2Ftest_file.txt`

Is this a bug or expected behaviour on GenerateSasUri method?

**To Reproduce**
```
string connectionString = "your_connection_string";
string containerName = "test-data";
string filename = "MyData/test_file.txt";
BlobContainerClient container = new BlobContainerClient(connectionString, containerName);
BlobClient blobClient = container.GetBlobClient(filename);
string storedPolicyName = null;

if (blobClient.CanGenerateSasUri) {
	BlobSasBuilder sasBuilder = new BlobSasBuilder() {
		BlobContainerName = blobClient.GetParentBlobContainerClient().Name,
		BlobName = blobClient.Name,
		Resource = "b"
	};

	if (storedPolicyName == null) {
		sasBuilder.ExpiresOn = DateTimeOffset.UtcNow.AddHours(1);
		sasBuilder.SetPermissions(BlobSasPermissions.Read);
	}
	else {
		sasBuilder.Identifier = storedPolicyName;
	}

	Uri sasUri = blobClient.GenerateSasUri(sasBuilder);
	string url = sasUri.ToString();
	url = null;
	// https://mydomain.blob.core.windows.net/test-data/MyData%2Ftest_file.txt?sv=2020-04-08&se=2021-03-15T17%3A47%3A20Z&sr=b&sp=r&sig=...
}
```

**Environment:**
 - C# dotnet core 3.1
 - Azure.Storage.Blobs 12.8.0.0
 - Windows 10 Pro
 - Visual Studio Code 1.54.2

**Comment by seanmcc-msft** [comment]
Hi @spylkkanen.  The base URL is being intentionally encoded, but this is the first we've heard about the SAS part of the query not being encoded.

Is the resulting SAS URL functioning for you?

-Sean

**Comment by spylkkanen** [comment]
SAS URL technically works correctly. We noticed behavior change when we upgraded Microsoft.Azure.Storage.Blob version 11.2.2 to Azure.Storage.Blobs 12.8.0.0. So technically it's correct and as you mention _"The base URL is being intentionally encoded"_. So I don't think this is an issue.
