### ISSUE TITLE
No supporting explanations whatsoever

### ISSUE THREAD

**Issue by TPucke** [Azure/azure-sdk-for-net#19523]
This page should document the usage of the arguments, particularly something like the filter string, which obviously must follow a specific protocol.  Is there some other place to find an explanation of the arguments for this function?  If so, at least a link would be useful. 

The same question applies to seemingly all methods of all Azure APIs.  I find it impossible to believe that I am expected to learn how to use Azure APIs without any helpful documentation.  It makes me wonder whether Microsoft really wants to support the cloud, which is absurd of course, but after years, how can there be no easily found documentation - for anything?  

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 69d0c15b-8624-268b-7870-4599d6135616
* Version Independent ID: 4a758196-cd40-48e5-76c3-487fca330d0e
* Content: [GroupsExtensions.GetGroupsAsync(IGroups, String, Nullable&lt;Int32&gt;, Nullable&lt;Int32&gt;, CancellationToken) Method (Microsoft.PowerBI.Api.V2) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powerbi.api.v2.groupsextensions.getgroupsasync?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.PowerBI.Api.V2.GroupsExtensions.GetGroupsAsync);k(MiscellaneousFilesProject);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet)
* Content Source: [xml/Microsoft.PowerBI.Api.V2/GroupsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.PowerBI.Api.V2/GroupsExtensions.xml)
* Service: **powerbi**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
@AlexGhiondea:  Would you be so kind as to assist in routing this?

**Comment by jsquire** [comment]
Hi @TPucke.  Thank you for your feedback and we regret that you're experiencing difficulties.  Tagging and looping in folks to help route this to the team best able to assist.

**Comment by TPucke** [comment]
Thanks, I appreciate the attention.  This is submitted against one simple page, but I want to make it clear that this intended to highlight an issue of huge scope, since the same complaint can be made about all the Azure APIs.  It seems that there are probably no method comments in any of the API code for Azure.  I have never understood this, it's the foundation for all of Microsoft and there is literally nothing.

**Comment by KranthiPakala-MSFT** [comment]
@CamSoper - Following up to see if there is any update on this issue? - Thank you
