### ISSUE TITLE
[Container Instance] tests fail because there is no projects available with pattern [..\sdk\containerinstance\**\*.csproj]

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#19538]
Container Instance tests fail with:
>Determining projects to restore...
  Nothing to do. None of the projects specified contain packages to restore.
D:\a\_work\1\s\eng\service.proj(37,5): error : No Projects found with patttern [..\sdk\containerinstance\**\*.csproj], please make sure you have passed in the correct ServiceDirectory.

Please check here for more details:
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=767940&view=logs&j=b08a78d6-c9ce-53c1-53b1-9a5d436f78f6&t=756e146f-7609-5d03-4e3a-e5bd2f3174ad&l=18
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=769943&view=logs&j=b08a78d6-c9ce-53c1-53b1-9a5d436f78f6&t=756e146f-7609-5d03-4e3a-e5bd2f3174ad&l=17
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=773187&view=logs&j=1e00682f-6081-5348-8da2-7d601664b2e3&t=4f3e1a81-cacf-5ad2-6e75-5049507bfdad&l=34
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=778151&view=logs&j=b08a78d6-c9ce-53c1-53b1-9a5d436f78f6&t=756e146f-7609-5d03-4e3a-e5bd2f3174ad&l=18
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=780887&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=780887&view=results

**Comment by ShivangiReja** [comment]
@LucasYao93  I see you added [this](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/containerinstance/ci.yml) ci.yml file. [Here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/containerinstance/ci.yml#L31) it's looking to run `Azure.ResourceManager.ContainerInstance` which does not exist in the folder. Could you please fix this issue?

**Comment by LucasYao93** [comment]
@ShivangiReja,
I have created PR, but it has not been merged.
PR: #18273

**Comment by jsquire** [comment]
Given the age of this issue, closing this as stale.  If tests are still failing, please file a new issue.
