### ISSUE TITLE
[Digital Twins] EventRoutes_Lifecycle test is flaky in weekly runs

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#19540]
EventRoutes_Lifecycle test fails with:

>Failed EventRoutes_Lifecycle [376 ms]
  Error Message:
   Azure.RequestFailedException : Service request failed.
Status: 404 (Not Found)

>Content:
{"error":{"code":"EventRouteNotFound","message":"There is no route available that matches the provided input. Check for all valid event routes by calling EventRoute_List. See Swagger example (http://aka.ms/RouteSwSmpl)."}}

For more details check here:
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=782852&view=logs&j=9f6e9dd9-0daa-5061-5c37-5c529436a384&t=7d15db3d-f1cc-50eb-c1e0-80c490f74744&l=47957
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=770245&view=logs&j=1ac41dec-e41f-5171-5870-980f5310a5cd&t=b2b6d108-81fa-5623-17f8-9ce56b31740a&l=123
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=769978&view=logs&j=6ad7a364-7142-5301-b5f7-272d775f6d69&t=24a9607f-3b7b-58d2-2d0e-e67f335afa2b&l=89
  -  Here it failed with
  >Expected a <Azure.RequestFailedException> to be thrown, but no exception was thrown

**Comment by azabbasi** [comment]
The same tests shows flaky behavior in JAVA pipelines as well. Will investigate.

**Comment by timtay-microsoft** [comment]
This appears to be tied to the service not making it's newly created resources "gettable" immediately after creation. Following up with the service team to see if they are going to fix this

**Comment by azabbasi** [comment]
> This appears to be tied to the service not making it's newly created resources "gettable" immediately after creation. Following up with the service team to see if they are going to fix this

We have contacted the service team multiple times and still haven't heard anything back about why these issue keeps popping up. 
As of today, we have a wait logic to work around the issue and get a more consistent live test result.
