### ISSUE TITLE
[Text Analytics] Weekly tests are failing with RequestFailedException in Canary region

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#19550]
Text Analytics Weekly tests are failing with:

> Error Message:
   Azure.RequestFailedException : Service request failed.
Status: 401 (PermissionDenied)

For more details check here:
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=770059&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=770300&view=results

**Comment by maririos** [comment]
Looks like that weekend the service had some issues. For the following [weekend](https://dev.azure.com/azure-sdk/internal/_build?definitionId=2033&_a=summary), the build passed.
I will keep this issue open for another week and if we have another green build I will close.
