### ISSUE TITLE
RecordedTest attribute improvements

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#19556]
- Consider making the test result configurable when a test is successfully re-recorded. Currently the result is an error to indicate that a re-recording was performed. Perhaps this should be configurable via env variable to support silent success in this case.
- Add documentation to the attribute to indicate that setting the `TF_BUILD` environment variable will disable the re-record functionality. Consider also creating a separate variable that can be configured independently of `TF_BUILD`

**Comment by kasobol-msft** [comment]
For us (Storage) disabling the feature is important for situation where we bump service version across the board. Therefore decoupling the "kill switch" from CI is important and making it easy is also important (e.g. runsettings, global variable or both).

**Comment by christothes** [comment]
Closing this since there hasn't been any significant feedback since it was created.
