### ISSUE TITLE
[Time Series Insights] Nightly tests are failing

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#19552]
Time Series Insights nightly test runs are failing with:

> Error Message:
   Expected createInstancesResult.Value to contain only items matching (errorResult == null), but {{empty}} do(es) not match.

For more details check here:
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=775941&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=778604&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=781326&view=results

**Comment by maririos** [comment]
Looks like build is fixed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=906963&view=results
