### ISSUE TITLE
[Time Series Insights] Fails with "Build and release is not allowed for GA package without API review approval"

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#19578]
Time Series Insights fails with:

>Package name: Azure.Iot.TimeSeriesInsights
Version: 
SDK Type: client
Package version  is GA and automatic API Review is not yet approved for package Azure.Iot.TimeSeriesInsights.
Build and release is not allowed for GA package without API review approval.
You will need to queue another build to proceed further after API review is approved
You can check http://aka.ms/azsdk/engsys/apireview/faq for more details on API Approval.
##[error]PowerShell exited with code '1'.

For more details please check:
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=786007&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=c6642a37-b24b-5443-7452-ff95456b7c94&l=23
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=783610&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=c6642a37-b24b-5443-7452-ff95456b7c94
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=781312&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=c6642a37-b24b-5443-7452-ff95456b7c94
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=778586&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=c6642a37-b24b-5443-7452-ff95456b7c94&l=23

**Comment by jsquire** [comment]
Given the age of this issue, I'm going to close it as stale.  If builds continue to fail, please reopen or file a new issue.
