### ISSUE TITLE
[BUG] Cannot create a Frontend within Front Door with HTTPS configuration via CreateOrUpdate method

### ISSUE THREAD

**Issue by briantre** [Azure/azure-sdk-for-net#19579]
**Describe the bug**
Unable to create HTTPS configuration for a new Frontend endpoint in Azure Front Door via the `CreateOrUpdate` API.

**Expected behavior**
I would expect to be able to create a Frontend endpoint, specify its HTTPS configuration and have it created all in one go via the `CreateOrUpdate` method.  Looking at the docs for the [`CreateOrUpdate` REST API](https://docs.microsoft.com/en-us/rest/api/frontdoorservice/frontdoor/frontdoors/createorupdate) it looks like this should be possible.

**Actual behavior**
What's actually happening is that my Frontend endpoint is being created, but the HTTPS configuration is missing.  I did some digging and I think I found the root cause.
1. Here in [FrontdoorOperations.cs](https://github.com/Azure/azure-sdk-for-net/blob/cd511f144276a8fd061065d605403a1b5e7dc951/sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/src/Generated/FrontDoorsOperations.cs#L1077) we serialize the object that contains the request body for the `CreateOrUpdate` REST API.  On that line you can see that we're passing the `Client.SerializationSettings` to our serialization library.
2. Here in [FrontendManagementClient.cs](https://github.com/Azure/azure-sdk-for-net/blob/d59a7f1a7563c4fea63108ef519685aef0e19d4e/sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/src/Generated/FrontDoorManagementClient.cs#L398) you can see that the serialization settings include the use of the `ReadOnlyJsonContractResolver`.
3. Here in [ReadOnlyJsonContractResolver](https://github.com/Azure/azure-sdk-for-net/blob/d59a7f1a7563c4fea63108ef519685aef0e19d4e/sdk/mgmtcommon/ClientRuntime/ClientRuntime/Serialization/ReadOnlyJsonContractResolver.cs#L31) you can see that we will NOT serialize any properties that have a private setter.
4. In this scenario, the class that we're serializing is [`Microsoft.Azure.Management.FrontDoor.Models.FrontendEndpoint`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/src/Generated/Models/FrontendEndpoint.cs).  On this [line](https://github.com/Azure/azure-sdk-for-net/blob/d59a7f1a7563c4fea63108ef519685aef0e19d4e/sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/src/Generated/Models/FrontendEndpoint.cs#L149) you can see that the setter for the `CustomHttpsConfiguration` property is private.  Therefore, the `ReadOnlyJsonContractResolver` excludes that property from being serialized and included in the request body sent to the `CreateOrUpdate` REST API.
5. Since the `CustomHttpsConfiguration` object is never being serialized and sent to the `CreateOrUpdate` REST API then it makes sense that the HTTPS configuration is not being applied for the newly created Frontend endpoint.

**To Reproduce**
I've been trying to create Frontend endpoints via Powershell, but I believe that I have tracked down the root cause of the issue within the C# Azure SDK.  Here is the Powershell that I've been using:
```powershell
$new_front_end = New-AzFrontDoorFrontendEndpointObject `
     -Name $title_host_name.Replace('.', '-') `
     -HostName $title_host_name `
     -CertificateSource AzureKeyVault `
     -Vault $key_vault_resource_id `
     -SecretName "my_ssl_cert" `
     -MinimumTlsVersion "1.0"

$front_door.FrontendEndpoints += $new_front_end

Set-AzFrontDoor -InputObject $front_door
```
If you're running Fiddler and grab the request being made to the `CreateOrUpdate` REST API you will see that the request body does not contain the `properties.CustomHttpsConfiguration` field in the new Frontend endpoint object.

**Environment:**
- Using Azure Powershell Az Modules version 5.6.0
- I'm using Powershell version 5.1.19041.610.  I'm new to Powershell, but I think that means I'm running on .NET Full Framework.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JonathanCrd** [comment]
Thanks for your feedback, re-routing to service team.

**Comment by KranthiPakala-MSFT** [comment]
@cdnfdsuppgithub Following up to see if there is any update on this issue? - Thank you
