### ISSUE TITLE
azure virtual machine backup enabled and disaster recovery (azure site recovery ) enabled 

### ISSUE THREAD

**Issue by vscodewinodws** [Azure/azure-sdk-for-net#19618]
I need to check particular azure virtual machine has backup enabled and disaster recovery (azure site recovery ) enabled or not if we see in sdk we can find property for IsBootDiagnosticsEnabled but same kind  of property i am looking for vm , also i seen rest api for backup and site recovery exist but they are specific to their operation they are not resulting like particular vm is in backup or site recovery but azure portal can load associated backup and site recovery so there might be some way so can you please help me with property or rest api or any other possible way to get it .

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by JonathanCrd** [comment]
Hi @vscodewinodws, could you provide the SDK name and version you are using please?
