### ISSUE TITLE
[BUG] BlobServiceClient throws a AuthenticationFailed from SAS connection string

### ISSUE THREAD

**Issue by pilarodriguez** [Azure/azure-sdk-for-net#19619]
**Describe the bug**
The BlobServiceClient builds an invalid queue URI from a SAS connection string and the blob operations fail with an AuthenticationFailed exception.

**Expected behavior**
Using the same connection string was working in the deprecated WindowsAzure.Storage package version 9.3.3, and it is also working if I use that connection string from [Microsoft Azure Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/)

**Actual behavior (include Exception or Stack Trace)**
In my code, I get the SAS token and use it to construct the connection string (note the `?` in the SharedAccessSignature)
`BlobEndpoint=https://testaccount.blob.core.windows.net;SharedAccessSignature=?sv=2020-02-10&ss=b&srt=c&sp=rwdlacx&se=2020-03-18T19:49:15Z&st=2021-03-18T11:49:15Z&spr=https&sig=mockedsignature`

Using that connection string, the BlobServiceClient generates a URL with an extra `?`. 
`https://testaccount.blob.core.windows.net/??sv=2020-02-10&ss=b&srt=c&sp=rwdlacx&se=2020-03-18T19:49:15Z&st=2021-03-18T11:49:15Z&spr=https&sig=mockedsignature`

After that, if I try to access data in blob (for example, verify if a container exists), I get the following error:
```
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:58fa4342-b01e-0065-09cb-159609000000
Time:2021-03-10T16:39:24.4103037Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed
```

**To Reproduce**
In this example, I've generated a SAS token from Azure portal and use it to construct my connection string (I have removed the real signature value from here, but I've used the correct one when I did my test). If I trim the initial `?` from the SAS token, it works fine.
```csharp
var sasToken = "?sv=2020-02-10&ss=b&srt=c&sp=rwdlacx&se=2020-03-18T19:49:15Z&st=2021-03-18T11:49:15Z&spr=https&sig=mockedsignature";

var correctConnectionString =
    $"BlobEndpoint=https://testaccount.blob.core.windows.net;SharedAccessSignature={sasToken.TrimStart('?')}";
var correctBlobClient = new BlobServiceClient(correctConnectionString);

var azureContainer = correctBlobClient.GetBlobContainerClient("test");
await azureContainer.ExistsAsync(); //this works

var wrongConnectionString = $"BlobEndpoint=https://testaccount.blob.core.windows.net;SharedAccessSignature={sasToken}";

var wrongBlobClient = new BlobServiceClient(wrongConnectionString);

azureContainer = wrongBlobClient.GetBlobContainerClient("test");
await azureContainer.ExistsAsync(); //this throws an exception
```

In my code, I trim the initial `?` as a workaround, but as this was working with the previous package and it is also working in Azure Storage Explorer, I would also expect it to work with this package. 

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.0
 - Hosting platform or OS and .NET runtime version: Azure AppService .NET Framework 4.7.2
 - IDE and version: Visual Studio 16.8.1

**Comment by kasobol-msft** [comment]
@pilarodriguez According to documentation and samples [here](https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#create-a-connection-string-using-a-shared-access-signature) the connection string with SAS isn't supposed to have leading "?" in the SAS token part. Also if you go to Azure Portal and generate SAS you'll get a connection string without that extra "?". 

Therefore I think that previous version and Storage Explorer handling that is rather unintentional.

Have you considered using [`BlobServiceClient(Uri, BlobClientOptions)` ctor](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.-ctor?view=azure-dotnet#Azure_Storage_Blobs_BlobServiceClient__ctor_System_Uri_Azure_Storage_Blobs_BlobClientOptions_) instead of connection string?

**Comment by seanmcc-msft** [comment]
Please reopen if you have further questions.
