### ISSUE TITLE
[QUERY] Why is AuthenticationResult a pre-requisite to create ApplicationTokenProvider

### ISSUE THREAD

**Issue by ravarnamsft** [Azure/azure-sdk-for-net#19614]
**Query/Question**
The ApplicationTokenProvider class is supposed to be providing an AuthenticationResult and there is a circular logic dependency introduced by adding AuthenticationResult into the Constructor and making it non-nullable. It seems to be used to extract the accessTokenType and accessToken and expiredOn. All of these are not required to get the token and the class can manage token lifetme within itself. I understand there are some new static methods brought in, however, looks like all users are now required to write a new interface similar to ITokenProvider for dependency injection and other purposes (since an instance of ApplicationTokenProvider cannot be created).

The class was nicely handling the case of clientSecret vs certificate etc. We are having to write all by ourselves now (it is not a lot of code, but anyone in a similar situation would have to write one). Seems like an unnecessary burden on the user when this class already had all the functionality.

What's the reason for it?

**Environment:**
 - Name and version of the Library package used: Microsoft.Rest.ClientRuntime.Azure.Authentication 2.4.1 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):.NET SDK (reflecting any global.json):
 Version:   5.0.104
 Commit:    ca6b6acadb

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.104\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

**Comment by jsquire** [comment]
@AlexGhiondea:  This appears to be related to the AutoRest Runtime, but I'm not familiar with the package or ownership.   Would you be so kind as to help route to the folks best able to assist?

**Comment by AlexGhiondea** [comment]
@schaabs can you help answer or route this issue? Thank you!

**Comment by ravarnamsft** [comment]
@jsquire  and @AlexGhiondea I filed this issue here because the nuget pointed me here I believe and that I found the file in this repo -
https://github.com/Azure/azure-sdk-for-net/blob/2b594335737a65cb8f36543ef817deaba5c43f4b/sdk/mgmtcommon/Auth/Az.Auth/Az.Authentication/ApplicationTokenProvider.cs

While it is not directly the nuget package, I felt it owned and used here for other purposes. Just FYI.

**Comment by allenjzhang** [comment]
@ravarnamsft , Can you show your usage of this class? I expect the user just use the static method Login/LoginSilent rather than construct it directly and that would be the typical usage

**Comment by markcowl** [comment]
Closing as won't fix, per offline discussion
