### ISSUE TITLE
[QUERY] Azure Search: How can I set the retry options?

### ISSUE THREAD

**Issue by everlongwan** [Azure/azure-sdk-for-net#19623]
**Query/Question**
Azure.Search.Documents v11.2.0

SearchClientOptions has a property Retry, but it's read only. How do I set it?

**Environment:**
Azure.Search.Documents 11.2.0
Windows 10
Nuget Package, with target frameworks net461;netstandard2.0
Visual Studio 16.8.3
![Screenshot 2021-03-18 094736](https://user-images.githubusercontent.com/80913005/111664533-1a0d6e80-87cf-11eb-94a1-7a07f20a4d46.png)

**Comment by jsquire** [comment]
Hi @everlongwan.  Thank you for your feedback and we regret that you're experiencing difficulties.  Setting the retry options can be done directly using the properties on the `Retry` member after the `SearchClientOptions` has been constructed.   For example:

```csharp
var options = new SearchClientOptions
{
    Serializer = new JsonObjectSerializer(searializerOptions);
};

options.Retry.MaxRetries = 5;
options.Retry.Delay = TimeSpan.FromSeconds(0.5);
```

**Comment by everlongwan** [comment]
Perfect, Thank you
