### ISSUE TITLE
FileServices.SetServicePropertiesAsync throws XML specified is not syntactically valid.

### ISSUE THREAD

**Issue by pawelpabich** [Azure/azure-sdk-for-net#19620]
**Describe the bug**

FileServices.SetServicePropertiesAsync throws XML specified is not syntactically valid.

**Expected behavior**

No exception

**Actual behavior (include Exception or Stack Trace)**

```
Microsoft.Rest.Azure.CloudException: XML specified is not syntactically valid.
RequestId:cfad924b-401a-0011-3d03-1c9ff4000000
Time:2021-03-18T14:28:52.7368664Z
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```C#
var properties = await managementClient.FileServices.GetServicePropertiesAsync(resourceGroupName, storageAccountName);
properties.ShareDeleteRetentionPolicy = new DeleteRetentionPolicy(true, 30);
await managementClient.FileServices.SetServicePropertiesAsync(resourceGroupName, storageAccountName, properties);
```

**Environment:**
 - Microsoft.Azure.Management.Storage 1.19
 - Windows 10 .NET Core 3.1

**Workaround**
```C#
await managementClient.FileServices.SetServicePropertiesAsync(azure.ResourceGroupName, storageAccount.Name, new FileServiceProperties(shareDeleteRetentionPolicy: new DeleteRetentionPolicy(true, 30)));
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JonathanCrd** [comment]
Thank you for your feedback, Re-routing to service team.

**Comment by amishra-dev** [comment]
@blueww can you please look at this one?

**Comment by blueww** [comment]
+ @SRP ***@***.***> as the error is reported from server.


Microsoft.Rest.Azure.CloudException: XML specified is not syntactically valid.
RequestId:cfad924b-401a-0011-3d03-1c9ff4000000
Time:2021-03-18T14:28:52.7368664Z


获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Ashish Mishra ***@***.***>
发送时间: Thursday, June 3, 2021 8:10:54 AM
收件人: Azure/azure-sdk-for-net ***@***.***>
抄送: Wei Wei (AZURE) ***@***.***>; Mention ***@***.***>
主题: Re: [Azure/azure-sdk-for-net] FileServices.SetServicePropertiesAsync throws XML specified is not syntactically valid. (#19620)


@blueww<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fblueww&data=04%7C01%7Cweiwei%40microsoft.com%7C0fbdc09c7da9489b308708d926240e2b%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637582758569005469%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m5EVS35zkEWYvM1joNgBHjwcujnTCTE8RpYQ7NQ2nqI%3D&reserved=0> can you please look at this one?

―

**Comment by amnguye** [comment]
@blueww did this issue get resolved offline? Looks like you replied from email.

**Comment by amishra-dev** [comment]
please let us know if you are still blocked.

**Comment by pawelpabich** [comment]
@amishra-dev is this problem fixed? If so, in what version?

**Comment by amishra-dev** [comment]
My apologies @pawelpabich, looks like we are waiting for a service fix

**Comment by amishra-dev** [comment]
@pawelpabich can you raise a support request? As service issues are not tracked here. I will try and help someone pick this up as well.

**Comment by pawelpabich** [comment]
Support request? Where can I do this?

**Comment by blueww** [comment]
@pawelpabich 
You can raise a support request in Azure Portal as following picture:
![image](https://user-images.githubusercontent.com/6926193/132302260-f1fbee9a-6b1c-4176-b534-080fb3ac405d.png)


Besides that, as this is a server log, please give a request ID for the issue in the recent time (in 3 days), as server side might need look into server log to investigate it.

**Comment by ArthurMa1978** [comment]
@pawelpabich did file the support ticket?
If yes please put the link here and I would like to close this issue.

**Comment by pawelpabich** [comment]
Yes,  I did.  Id: 2109070060001835
