### ISSUE TITLE
[FEATURE REQ] Expose ServerTimeout in Storage SDK

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#19621]
Opening this on behalf of customer.

**Library or service name.**
Azure.Storage.* libraries
 
**Is your feature request related to a problem? Please describe.**
Customers migrating from V11 report that [ServerTimeout](https://docs.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-blob-service-operations) is missing.
There's a known workaround [here](https://github.com/Azure/azure-sdk-for-net/issues/12445#issuecomment-645507734) but it's far from being user friendly.
Additional challenge is that it seems to make sense for this to be configurable per API, i.e. customer may want to use different values for upload/download vs get properties. Also max values are different depending on which API is called.

**Comment by amnguye** [comment]
Related issues: https://github.com/Azure/azure-sdk-for-net/issues/19697, https://github.com/Azure/azure-sdk-for-net/issues/12445#issuecomment-645507734
