### ISSUE TITLE
Remove test dependency on Track 1 management client

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#19633]
Per https://github.com/azure/azure-sdk-for-net/issues/19570 we will use Track 1 management client to import images to make tests standalone for testing delete operations.

We need  a long-term solution to remove the dependency on the management client.  Part of this work item is determining what the approach should be.

**Comment by AlexGhiondea** [comment]
We've decided to keep the T1 dependency on the mgmt client from tests.
