### ISSUE TITLE
[FEATURE REQ] add `DataChanged` method to `KeyVaultSecretManager` to support custom load logic

### ISSUE THREAD

**Issue by irontoby** [Azure/azure-sdk-for-net#19638]
**Library or service name.**
What library or service is this request related to? Azure.Extensions.AspNetCore.Configuration.Secrets
 
**Is your feature request related to a problem? Please describe.**
`KeyVaultSecretManager` has `GetKey` and `Load` methods to customize the behavior of the `AzureKeyVaultConfigurationProvider` but there are other scenarios such as #11943 which require more complex custom logic.

Rather than have the provider try to support all scenarios, end-users could implement their own custom logic if `KeyVaultSecretManager` included a method such as `public virtual void DataChanged(Dictionary<string, LoadedSecret> loadedSecrets)` which defaults to a no-op in the default implementation.

This could be called [immediately after loading secrets](https://github.com/Azure/azure-sdk-for-net/blob/bb7d612114a8a6c8e5ce8c55a9359cded69488dd/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationProvider.cs#L107) but immediately before setting the `Data` and issuing reload notices. This will allow custom logic to modify/add/remove dictionary entries as needed, before they're actually set on the provider.

```csharp
foreach (var secretBundle in loadedSecret)
{
    newLoadedSecrets.Add(secretBundle.Value.Name, new LoadedSecret(_manager.GetKey(secretBundle), secretBundle.Value.Value, secretBundle.Value.Properties.UpdatedOn));
}

_manager.DataChanged(newLoadedSecrets); // allow KeyVaultSecretManager to execute custom logic on all loaded secrets

_loadedSecrets = newLoadedSecrets;
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by irontoby** [comment]
Taking another look, since the `LoadedSecret` struct is private, it would likely be better to make the signature `public virtual void DataChanged(Dictionary<string, KeyVaultSecret> secrets)` instead, and call it after the loaded struct has been converted into `KeyVaultSecret` entries in the `SetData` method.

```csharp
private void SetData(Dictionary<string, KeyVaultLoadedSecret> loadedSecrets, bool fireToken)
{
    var data = new Dictionary<string, string>(loadedSecrets.Count, StringComparer.OrdinalIgnoreCase);
    foreach (var secretItem in loadedSecrets)
    {
        data.Add(secretItem.Value.Key, secretItem.Value.Value);
    }

    _manager.DataChanged(data);

    Data = data;
    if (fireToken)
    {
        OnReload();
    }
}
```

**Comment by pakrym** [comment]
This sounds like a general-purpose I configuration feature that's not specific to KeyVault in-particular. I can see the same being useful for AppConfiguration, SQL-server, and other configuration storages.

**Comment by irontoby** [comment]
@pakrym the reason it's specific to KeyVault is that with the current implementation of `AzureKeyVaultConfigurationProvider`, it's not possible for callers to access the data items in any way, especially since the class is `internal`. If it were `public` then at least I could override the `Load` method, although it would still not be possible to get data specific to KeyVault such as the `Properties` collection on `KeyVaultSecret`.

**Comment by pakrym** [comment]
I see, makes sense.

**Comment by irontoby** [comment]
Thanks for considering it, I realize my approach may mess with the old/new loaded logic & you may not want to bother with that but having a public class with maybe a protected method called inside `LoadAsync` would really help add custom functionality for those of us who need it.

**Comment by pakrym** [comment]
How about https://github.com/Azure/azure-sdk-for-net/pull/19788 ?

**Comment by irontoby** [comment]
@pakrym that definitely looks like it checks all the boxes for what I need to customize the loading behavior. Thanks so much for the turnaround on this!
