### ISSUE TITLE
[Perf] Add mode to specify number of operations and measure time

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#19648]
There are two ways to measure maximum client throughput:

1. Specify duration, measure how many operations completed
2. Specify number of operations, measure time to complete

In general, I prefer option 1 since you usually want to run the test for some reasonable amount of time (say 10 seconds), and you don't know the throughput in advance so you can't specify an equivalent number of operations.

However, for services with throttles, option 2 is preferable since you want to specify a number of operations just below the throttle limit, and measure the time to complete them.

**Comment by pakrym** [comment]
#2 is also nice for profiling.

**Comment by kasobol-msft** [comment]
Please add in Java as well.
