### ISSUE TITLE
[QUERY] Passing proxy credentials with the new Azure.Messaging.EventGrid client library

### ISSUE THREAD

**Issue by ershadnozari** [Azure/azure-sdk-for-net#19659]
Is there way to pass proxy credentials to EventGridPublisherClient when using the new Azure.Messaging.EventGrid client library? 

using the Microsoft.Azure.EventGrid library we could do the following:

```
IEventGridClient client = (new EventGridClient(
                new TopicCredentials("TopicKey"),
                new HttpClientHandler
                {
                    DefaultProxyCredentials = CredentialCache.DefaultCredentials
                }));
```

There's nothing mentioned about this in the migration guide. Any assistance is highly appreciated.

Cheers

**Comment by JoshLove-msft** [comment]
Yes, there is!
```cs
  var handler = new HttpClientHandler
  {
      DefaultProxyCredentials = CredentialCache.DefaultCredentials,
  };
  var options = new EventGridPublisherClientOptions
  {
      Transport = new HttpClientTransport(new HttpClient(handler))
  };
  EventGridPublisherClient client = new EventGridPublisherClient(
      new Uri("<topic host>"),
      new AzureKeyCredential("<access key>"),
      options);
```

**Comment by JoshLove-msft** [comment]
Note that this pattern isn't specific to the Event Grid SDK, but is available in any of the new "Azure.*" libraries that use the Azure.Core ClientOptions:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy
