### ISSUE TITLE
Update Identity README and MS Docs.

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-net#19657]
Identity README Changes:
- [x] Remove the part from intro that says "This library currently supports...." and ensure intro section looks like [this](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#azure-identity-client-library-for-java).
- [x] Update the DAC description to look like [this](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#defaultazurecredential).
- [ ] Add Detailed Identity examples in the wiki for Identity Scenarios mentioned [here](https://github.com/Azure/azure-sdk-for-java/wiki/Azure-Identity-Examples) and reference the link to the wiki in the README as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#examples).
- [ ] Add Configuration, examples reference links to Credential classes tables as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#credential-classes).
- [x] Update the Next Steps to reference the libraries in azure-SDK repos as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#next-steps).
- [x] Add Managed Identity Support section as [here](https://github.com/g2vinay/azure-sdk-for-java/blob/update-identity-readme/sdk/identity/azure-identity/README.md#managed-identity-support).

MS Docs Change:
- [ ] Update Azure SDK for NET Identity MS Docs to contain the content as [here](https://docs.microsoft.com/en-us/azure/developer/java/sdk/identity).

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by joshfree** [comment]
adding back `blocking-release` to track for the Identity GA this month
