### ISSUE TITLE
[FEATURE REQ] Missing extension for AppConfiguration

### ISSUE THREAD

**Issue by pekspro** [Azure/azure-sdk-for-net#19664]
**Azure.Data.AppConfiguration.**
`Azure.Extensions.AspNetCore.Configuration.Secrets` makes it easy to add Azure KeyVault into the configuration builder during startup. I have not found any similar for `Azure.Data.AppConfiguration`. 

There is a `Microsoft.Extensions.Configuration.AzureAppConfiguration` for the “old” `Microsoft.Azure.AppConfiguration.AspNetCore` (actually updated today).

Are there any plans add this? Just for fun I took the code in `Azure.Extensions.AspNetCore.Configuration.Secrets` and adapted it to AppConfiguration instead. Not that hard, I think. I could create an PR if there is an interest.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Libraries that you've mentioned are not "old", they are current, supported, and based on Azure.Data.AppConfiguraiton.

`Microsoft.Extensions.Configuration.AzureAppConfiguration` is a `IConfiguration-AppConfig` extension package.

`Microsoft.Azure.AppConfiguration.AspNetCore` has a few additional features on top of that mostly around refreshing configuration during the request processing.

I would recommend starting with `Microsoft.Extensions.Configuration.AzureAppConfiguration`.
