### ISSUE TITLE
[QUERY] Is the TableTransactionBatch intended to capture entity state?

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#19671]
**Query/Question**
I am moving from WindowsAzure.Storage SDK to Azure.Data.Tables and I have many places in my code where I use a transaction entity batch to reduce round trips to Table Storage and to leverage atomic updates to many entities within a partition.

In WindowsAzure.Storage, it's possible to built up a transaction batch and then modify the entities prior to submitting the batch and have those latest entity changes be reflected in the submitted change. In other words, this works:

1. Add entity to batch
2. Modify entity
3. Submit batch
4. See changes on step 2 in the resulting entity.

In Azure.Data.Tables, it looks like step 1 immediately captures all of the OData properties from the entity at the moment, in a deep-clone type fashion, making any changes (i.e. step 2) have no affect the batch that gets submitted.

Is this an intentional design decision? It's certainly not an insurmountable problem. For example step 1 can actually be adding logical entity operations to a list like `List<Action<TableTransactionBatch>>` that I manage and then at step 3 I actually create the batch and add all of the collected operations into the batch at that time, thus capturing the latest entity state.

If this was intentional, do you think it would be worth enhancing the XML docs on the `TableTransactionBatch` methods to say that the current entity state is captured and future changes to the `ITableEntity` will not affect the batch? It caught me off guard in the migration to the new SDK so I'm wondering if others might fall into the same trouble.

**Environment:**
 - Name and version of the Library package used: Azure.Data.Tables 12.0.0-beta.6
 - Hosting platform or OS and .NET runtime version:
    - Windows 10
    - .NET 5 SDK

<details>

    .NET SDK (reflecting any global.json):
    Version:   5.0.201
    Commit:    a09bd5c86c

    Runtime Environment:
    OS Name:     Windows
    OS Version:  10.0.19042
    OS Platform: Windows
    RID:         win10-x64
    Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

    Host (useful for support):
    Version: 5.0.4
    Commit:  f27d337295

    .NET SDKs installed:
    1.1.14 [C:\Program Files\dotnet\sdk]
    2.1.814 [C:\Program Files\dotnet\sdk]
    3.1.407 [C:\Program Files\dotnet\sdk]
    5.0.100-dev [C:\Program Files\dotnet\sdk]
    5.0.104 [C:\Program Files\dotnet\sdk]
    5.0.200 [C:\Program Files\dotnet\sdk]
    5.0.201 [C:\Program Files\dotnet\sdk]

    .NET runtimes installed:
    Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.0-preview.8.20359.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.0-preview.8.20358.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.0-rc.1.20366.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.0-preview.8.20352.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    To install additional .NET runtimes or SDKs:
    https://aka.ms/dotnet-download
</details>

 - IDE and version: Visual Studio 16.10 Preview 1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @joelverhagen - Thanks for filing this issue. This behavior wasn't a specific decision, but I agree that adding some docs to clarify the behavior would be helpful.

**Comment by joelverhagen** [comment]
If this is helpful, here's a diff where I moved a simple module from WindowsAzure.Storage to Azure.Data.Tables:
https://github.com/joelverhagen/ExplorePackages/compare/28762403101995e518463213e5789aad8cb085b0..9f95e495b2fded7e98032f0537263eb265cbd073#diff-fbd0ef9457ec5339f8446a2fd91ba401fd76c452b415f952e0b3b5784a035f9dL145-R223

I've tried to link to the specific part of the changeset that is interesting. Main pain points:

1. No `Count`/enumeration API on the batch type to determine a no-op. Submitting an empty batch results in an HTTP 400 from Table storage, which the Azure.Data.Tables APIs allows forcing the caller to protect against this.
2. Entities must be modified prior to adding them to the batch. This causes some duplication in code where previously I could update all of the entities in one place.

**Comment by christothes** [comment]
> 1. No `Count`/enumeration API on the batch type to determine a no-op. Submitting an empty batch results in an HTTP 400 from Table storage, which the Azure.Data.Tables APIs allows forcing the caller to protect against this.

Would it be your expectation for `SubmitBatch` to throw `InvalidOperationException` if it contains no operations? I think this makes sense. 

Outside of that, would you find it helpful to have the operation count available either way?

> 2. Entities must be modified prior to adding them to the batch. This causes some duplication in code where previously I could update all of the entities in one place.

This one I am less sure about since I wonder if being able to manipulate entities already added to the batch might give the expectation that after execution the entities would be updated based on the batch results. Do you have any thoughts about this?

**Comment by joelverhagen** [comment]
> Would it be your expectation for `SubmitBatch` to throw `InvalidOperationException` if it contains no operations? I think this makes sense.

I would expect that, yes. The SDK can save some unnecessary IO on a case that is likely unintended by the caller.

> Outside of that, would you find it helpful to have the operation count available either way?

The only reason I have used the count is for an "is empty" check. I can't think of anything additional except perhaps, in the future and as needed, an enumeration API to inspect the items in the batch. But TBH I can't think of a scenario for that more extensive API.

> This one I am less sure about since I wonder if being able to manipulate entities already added to the batch might give the expectation that after execution the entities would be updated based on the batch results. Do you have any thoughts about this?

Hmm... interesting point. I think my vision is clouded/biased based on legacy SDK behavior which would do both of those things. That's something I hadn't even considered yet since I haven't gotten to the part in my own codebase where batch updates are done and I need the subsequent etags.

Is it feasible to get all of the new etags from the successful result of batch of entity updates?

**Comment by christothes** [comment]
> > Would it be your expectation for `SubmitBatch` to throw `InvalidOperationException` if it contains no operations? I think this makes sense.
> 
> I would expect that, yes. The SDK can save some unnecessary IO on a case that is likely unintended by the caller.

Cool, I'll add an issue to make that minor change. 

> Is it feasible to get all of the new etags from the successful result of batch of entity updates?

Yes! Although I don't think we have a good sample showing this yet.
Example:
```C#
TableBatchResponse response = await batch.SubmitBatchAsync().ConfigureAwait(false);
// Get the new ETag for the updated entity
response.GetResponseForEntity(entity.RowKey).Headers.ETag;
```

**Comment by christothes** [comment]
Actually, we do show this in the samples here:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/samples/Sample6TransactionalBatch.md#adding-entities-with-a-transactional-batch

https://github.com/Azure/azure-sdk-for-net/blob/533ee2530f783f081d04c4bbcb79d483d9ef16a6/sdk/tables/Azure.Data.Tables/tests/samples/Sample6_TransactionalBatchAsync.cs#L74
