### ISSUE TITLE
[BUG] Exception on receiver (MT 7.1.6, Transport: Azure Service Bus )

### ISSUE THREAD

**Issue by Yauheni-Butski** [Azure/azure-sdk-for-net#19675]
Our app hosted on Azure WebApps, we use MassTransit 7.1.6 with Azure Service Bus. 

And few weeks ago we noticed that our Workers started throwing 2 types of exceptions:
- "Receive transport faulted: sb://... queueName.."
- "Exception on receiver sb://...queueName.. on 'Receive' "
 
 Logs for the first exception: [log-file](https://github.com/Yauheni-Butski/shared-logs/blob/master/receiveTransportFaulted.txt)
 Logs for the second exception: [log-file](https://github.com/Yauheni-Butski/shared-logs/blob/master/exceptionOnReceiver.txt)
 
 Exceptions for the second type could have different messages:
 - The connection was inactive for more than the allowed 60000 milliseconds and is closed by container '0934b54d-9e58-40ff-b1aa-704a446fb01c'
 - The link '{guid id}:source({queue name}):{queue name}' is force detached. Code: RenewToken. Details: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: '{queue name}'
 - The operation did not complete within the allocated time 00:00:59.9999049 for object request15.
 
 And looks like they all point to this place: [Microsoft.Azure.ServiceBus.Core.MessageReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan serverWaitTime)](https://github.com/Azure/azure-service-bus-dotnet/blob/dev/src/Microsoft.Azure.ServiceBus/Core/MessageReceiver.cs#L354)

We haven't found anything useful about what we can change. It looks like connection between Azure Service Bus and client breaks sometimes and throws exception. 

Any help would be appreciated. And if you will need something more, please let me know,

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@Yauheni-Butski 

Are there actually messages on the queue/subscription when you see these exceptions? These are standard timeouts that occur when there is nothing to receive. Connections in Service Bus are stateful and hence idle connections are disconnected.

**Comment by Yauheni-Butski** [comment]
Yeah, thanks @axisc ! We investigated it more and yeah, looks like the issue more in our connection which sometimes could be interrupted. 
So I think we can close this ticket.
