### ISSUE TITLE
No sample code for all of Azure.Storage.Blob

### ISSUE THREAD

**Issue by mduu** [Azure/azure-sdk-for-net#19674]
No sample code for all of Azure.Storage.Blobs. Eg. if/when/how to free resources?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64a0297c-b082-5ef1-3b1c-fba59b0a7176
* Version Independent ID: bf40f25b-8789-13dd-eff8-08b3274509bd
* Content: [Azure.Storage.Blobs Namespace - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs?view=azure-dotnet)
* Content Source: [xml/ns-Azure.Storage.Blobs.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Azure.Storage.Blobs.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by amnguye** [comment]
Hi, I'm a bit confused on the last bit of the question (the how and if part) but I'm assuming this is just simply asking where the samples live.

Our docs team did a great job on this article and quick start here
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet

If you scroll of the bottom there's a link to other samples as well.
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Blobs/samples
