### ISSUE TITLE
Ensure Track 1 Management Client traffic is recorded in test recordings

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#19690]
In tests for `DeleteTag`, we are not currently recording traffic to import an image using the Track 1 management client.

The work to do this has begun in this branch:  https://github.com/Azure/azure-sdk-for-net/compare/master...annelo-msft:record-track-1-requests

It is currently blocked on a [bug in Azure.Core](https://github.com/Azure/azure-sdk-for-net/issues/19691) where 202 responses aren't handled correctly.  Return to this once that issue has been resolved.

**Comment by AlexGhiondea** [comment]
Closing this for now.
