### ISSUE TITLE
[QUERY] How can I download a blob into a Stream passing some BlobRequestOptions's properties?

### ISSUE THREAD

**Issue by WillRock19** [Azure/azure-sdk-for-net#19697]
**Query/Question**
Hi. We've been using the Microsoft.WindowsAzure.Storage.Blob version 9.3.2.0 and used a BlobRequestOptions to set some properties before downloading and existing blob to a stream, as follows: 

```csharp
public void Test()
{
  var blob = StorageFileManager.GetBlobReference(
  file.StorageArquivo.Storage.CaminhoFisico,  //connectionString
  file.StorageArquivo.Container,                      //containerName
  blobName                                                     //blobName
  );
  
  blob.FetchAttributes();
  var blobSize = blob.Properties.Length;
  long blockSize = (5 * 1024 * 1024); // 5MB
  blockSize = Math.Min(blobSize, blockSize);
  
  var blobRequestOptions = new BlobRequestOptions
  {
    RetryPolicy = new ExponentialRetry(TimeSpan.FromSeconds(5), 3),
    MaximumExecutionTime = TimeSpan.FromMinutes(60),
    ServerTimeout = TimeSpan.FromMinutes(60)
  };
  
  long currentPointer = 0;
  long bytesRemaining = blobSize;
  int partNumber = 0;
  do
  {
      var bytesToFetch = Math.Min(blockSize, bytesRemaining);
      using (MemoryStream ms = new MemoryStream())
      {
          blob.DownloadRangeToStream(ms, currentPointer, bytesToFetch, null, blobRequestOptions);
          ms.Position = 0;
          
          /*Do some more things with the stream*/
      }
    } 
    while (bytesRemaining > 0);
}
```

I know that in the new library we have the **DownloadTo** method, and it receives an **BlobRequestConditions**, but it does not contain any of the properties I'm looking for. 

![image](https://user-images.githubusercontent.com/6953687/112051200-6ab6fb80-8b30-11eb-8758-90f75dcfa2c8.png)

I wanted to know where can I find this properties to configure it before making the download.

**Environment:**

    - .Net Version: Full Framework 4.8
    - Original version: Microsoft.WindowsAzure.Storage.Blob 9.3.2.0
    - New version: Azure.Storage.Blobs v12.8.0
    - IDE and version : Visual Studio 16.8.5

**Comment by Mohit-Chakraborty** [comment]
Hi,
You can use the [overload of `DownloadTo()`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.downloadto?view=azure-dotnet#Azure_Storage_Blobs_Specialized_BlobBaseClient_DownloadTo_System_IO_Stream_Azure_Storage_Blobs_Models_BlobRequestConditions_Azure_Storage_StorageTransferOptions_System_Threading_CancellationToken_) that allows users to specify non-default [`StorageTransferOptions`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.storagetransferoptions?view=azure-dotnet).

**Comment by WillRock19** [comment]
Hi @amnguye, thanks for the feedback! I've changed the title of my question, think it makes more sense now. 

Sorry about that :).

So, I've read the "retry policy" and the "timeout" examples. As I can tell:

- **Retry Policy**: I should set it when creating a new **BlobServiceClient** (as bellow)

![image](https://user-images.githubusercontent.com/6953687/112470136-0f138a80-8d49-11eb-98db-8dbc5343ae76.png)

- **Timeout**: I should create a custom policy and set the timeout in the **BlobClientOptions** before passing it to create a container (as bellow)

![image](https://user-images.githubusercontent.com/6953687/112470357-56018000-8d49-11eb-9509-1ef3e0668d06.png)

With that in mind, I still have a question. I'm currently updating an old library to the new one. In the old, we were using the *CloudBlob* class and its method **DownloadRangeToStream**, where we configured the **BlobRequestOptions**. In the new, I'm using a *BlobClient* class and trying to use the **DownloadTo** method to download it to a stream, as we used before (see bellow). 

![image](https://user-images.githubusercontent.com/6953687/112470921-02436680-8d4a-11eb-9977-b28ea7fae1c4.png)

![image](https://user-images.githubusercontent.com/6953687/112470771-d1fbc800-8d49-11eb-8500-0f762de574d4.png)

With that in mind, my questions are:

1. There is a way to set the RetryPolicy in the container, since I'm not using a **BlobServiceClient**? Should I create a custom policy as it is done in the **timeout** example?

2. The only way to configure those two options is in the container's creation? Can't I do it only when making the download to a stream?

Thanks again for all the help :)

**Comment by seanmcc-msft** [comment]
> There is a way to set the RetryPolicy in the container, since I'm not using a BlobServiceClient? Should I create a custom policy as it is done in the timeout example?

Yes, all clients including `BlobContainerClient` take `BlobClientOptions` as a constructor parameter.

> The only way to configure those two options is in the container's creation? Can't I do it only when making the download to a stream?

Yes, the only way to configure these options is on the client's creation.

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
