### ISSUE TITLE
Add DelayAsync to TestRecording

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#19694]
We should probably add this to https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.TestFramework/src/TestRecording.cs

_Originally posted by @JoshLove-msft in https://github.com/Azure/azure-sdk-for-net/pull/19680#discussion_r598977494_

**Comment by christothes** [comment]
fixed in #25327
