### ISSUE TITLE
Correctly handle 202 responses

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#19691]
In ACR, we get back a 202 response for a DELETE method on the tags resource.

The responseMessage in Azure.Core is coming back with a null message `Content`, but also a `Content-Length` header with a value of 4.  See screenshot from 

![image](https://user-images.githubusercontent.com/21269347/112040335-58be6400-8b02-11eb-92ad-8c30cf8a4b21.png)

The result is that an `InvalidOperationException` is thrown.

We'll need to investigate and correct Azure.Core's handling of 202 responses.

**Comment by JoshLove-msft** [comment]
I'm hitting this as well when trying to migrate management recordings to use Test Proxy

**Comment by JoshLove-msft** [comment]
It's unclear to me whether this is an issue in Azure.Core or in the service response.

**Comment by annelo-msft** [comment]
Closing as stale.
