### ISSUE TITLE
[Attestation] Nightly tests are failing with System.FormatException

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#19708]
Attestation nightly tests are failing with:
> Error Message:
   System.Text.Json.JsonException : The JSON value could not be converted to Azure.Security.Attestation.Models.PolicyCertificatesResult. Path: $ | LineNumber: 0 | BytePositionInLine: 19.
  ----> System.FormatException : Either the JSON value is not in a supported format, or is out of bounds for an Int32.

For more details please check here:
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=795791&view=logs&j=68082d65-ebf7-5f3f-494d-d3fd09e80dd6&t=6f6444ca-c101-5878-5224-de85502bb056&l=206
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=793027&view=logs&j=3fed8f10-c675-5f16-84cf-3d00285d9ecb&t=f7b2093a-e925-5604-777d-23646808606b&l=1453
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=790765&view=logs&j=9a3edcf8-64f7-5b1f-99ca-17780c3518e6&t=f2f3acac-d9d0-54d7-1189-c4d4fac1b232&l=1437

**Comment by LarryOsterman** [comment]
What a fun little bug.

It's actually a bug in the MAA service in our test clusters, we started returning floating point values when we were returning integer values. And the SDK parser for numbers assumed that all JSON numbers were integers, and not floating point values....

Fun times.



From: ShivangiReja ***@***.***>
Sent: Monday, March 22, 2021 4:07 PM
To: Azure/azure-sdk-for-net ***@***.***>
Cc: Larry Osterman ***@***.***>; Assign ***@***.***>
Subject: [Azure/azure-sdk-for-net] [Attestation] Nightly tests are failing with System.FormatException (#19708)


Attestation nightly tests are failing with:

Error Message:
System.Text.Json.JsonException : The JSON value could not be converted to Azure.Security.Attestation.Models.PolicyCertificatesResult. Path: $ | LineNumber: 0 | BytePositionInLine: 19.
----> System.FormatException : Either the JSON value is not in a supported format, or is out of bounds for an Int32.

For more details please check here:

  *   https://dev.azure.com/azure-sdk/internal/_build/results?buildId=795791&view=logs&j=68082d65-ebf7-5f3f-494d-d3fd09e80dd6&t=6f6444ca-c101-5878-5224-de85502bb056&l=206<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fazure-sdk%2Finternal%2F_build%2Fresults%3FbuildId%3D795791%26view%3Dlogs%26j%3D68082d65-ebf7-5f3f-494d-d3fd09e80dd6%26t%3D6f6444ca-c101-5878-5224-de85502bb056%26l%3D206&data=04%7C01%7CLarry.Osterman%40microsoft.com%7Cfc900b33aef445440f7008d8ed8736c1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637520512286165006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=v%2FX83bUnyc86d1tgg0WKYog6fFLufPRZrRe%2BZNTinGU%3D&reserved=0>
  *   https://dev.azure.com/azure-sdk/internal/_build/results?buildId=793027&view=logs&j=3fed8f10-c675-5f16-84cf-3d00285d9ecb&t=f7b2093a-e925-5604-777d-23646808606b&l=1453<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fazure-sdk%2Finternal%2F_build%2Fresults%3FbuildId%3D793027%26view%3Dlogs%26j%3D3fed8f10-c675-5f16-84cf-3d00285d9ecb%26t%3Df7b2093a-e925-5604-777d-23646808606b%26l%3D1453&data=04%7C01%7CLarry.Osterman%40microsoft.com%7Cfc900b33aef445440f7008d8ed8736c1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637520512286165006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=hm3Zrhh9zDnBbClwOx1wcyXF163bn8x2Lock2EQgMrA%3D&reserved=0>
  *   https://dev.azure.com/azure-sdk/internal/_build/results?buildId=790765&view=logs&j=9a3edcf8-64f7-5b1f-99ca-17780c3518e6&t=f2f3acac-d9d0-54d7-1189-c4d4fac1b232&l=1437<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fazure-sdk%2Finternal%2F_build%2Fresults%3FbuildId%3D790765%26view%3Dlogs%26j%3D9a3edcf8-64f7-5b1f-99ca-17780c3518e6%26t%3Df2f3acac-d9d0-54d7-1189-c4d4fac1b232%26l%3D1437&data=04%7C01%7CLarry.Osterman%40microsoft.com%7Cfc900b33aef445440f7008d8ed8736c1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637520512286165006%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wW7kEUx23P1snPJpnmg7vUNWoouLdJhpIo7Wf6kD06c%3D&reserved=0>

-
