### ISSUE TITLE
[FEATURE REQ] Introduce a response object for Add, Update, and Upsert entity methods

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#19723]
**Library or service name.**
Azure.Data.Tables
 
**Is your feature request related to a problem? Please describe.**
This response object would be called something like "EntityUpdateInfo" and would have at least an `ETag` property but in the future could contain a property with the whole `T` entity if the `Prefer: return-content` header is able to be specified as a parameter (don't know if there's plans to support this).

When using Azure.Data.Tables to insert, update, or upsert a record to a table, it's important to have the latest etag returned in the response headers to continue a chain of operations based on optimistic concurrency. If the etag is not surfaced in the API you must either:

1. Tease the `ETag` out of the returned `Response.Headers.ETag.Value` (not terrible, but not ideal)
2. Query the entity again (UNSAFE, the entity may have been changed!)

As a nice to have, it would be great if the a `Timestamp` was included as well on this new response type, which is what `WindowsAzure.Storage` does by parsing the etag (perhaps a bad idea, especially if the behavior is different on Cosmos DB). I can't find the source of `WindowsAzure.Storage` but if you decompile it with ILSpy there is a `ParseETagForTimestamp` method much like this Java one:
https://github.com/Azure/azure-storage-android/blob/2c643c37c6b8c9081058add284c601a2393afc93/microsoft-azure-storage/src/com/microsoft/azure/storage/table/TableResult.java#L168-L180

**Comment by joelverhagen** [comment]
Alternatively, the `ETag` property could be set on the provided entity (since `ITableEntity.ETag` has a setter), but I don't know how well this would work with the current implementation since, AFAICT, the entity is mapped to a dictionary early on in the pipeline so settings the etag may not be issue since the reference may be lost.

Also, it seems like the general direction of the Tables SDK is to not modify the provided entity. But maybe I'm missing something 😄.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @joelverhagen Thanks for filing this issue. Could you explain a bit about why grabbing the `ETag` value from the strongly typed `Response.Headers.ETag` doesn't work well for your scenarios? 

Also, could you talk a bit about why having the parsed TimeStamp value is important?

> Also, it seems like the general direction of the Tables SDK is to not modify the provided entity

Preventing modification of entities is definitely not a goal, so if we are doing things to prevent that I'd like to fix it or explain the expected approach. If you have examples of scenarios where it seems like we are making it difficult to modify an entity, please share them.

**Comment by joelverhagen** [comment]
> Could you explain a bit about why grabbing the `ETag` value from the strongly typed `Response.Headers.ETag` doesn't work well for your scenarios?

It works okay, but I think it's a little unintuitive.

I moved my entire codebase's blob and queue usage to the new Azure.* SDKs and I never had to use the `Response` object. There was always a model that specifically described that the service was returning in specific terms, rather than the generic HTTP response shape that `Response` describes. For example, consider [`BlobContentInfo.ETag`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobcontentinfo.etag?view=azure-dotnet#Azure_Storage_Blobs_Models_BlobContentInfo_ETag) returned by [`BlobClient.UploadAsync`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet).

Also, the `ETag` is nullable on `Response.Headers.ETag` but I think Table storage will always return an ETag for these operations so caller (code using the SDK) needs to do the research to be sure that you can safely do `ETag.Value` all the time and not check for null.

If the `ETag` were null for some reason this would cause serious problems for a sequence of optimistic concurrency calls! You'd either have to do a subsequent, unconditional entity update with no etag (dangerous) or perform a `GET` and diffgram-like operation to determine if the current entity state matches what was just `PATCH`/`POST`ed so that the returned etag can be used.

> Also, could you talk a bit about why having the parsed TimeStamp value is important?

In my case, I simply had some tests that assert the expected state on my `ITableEntity` implementation ([source](https://github.com/joelverhagen/ExplorePackages/blob/28762403101995e518463213e5789aad8cb085b0/test/ExplorePackages.Worker.Logic.Test/Cursors/CursorStorageServiceTest.cs#L47)) and I noticed the `Timestamp` was being set. I'm not using the `Timestamp` property in my app code so if it's left unset or isn't returned on some response object I don't mind too much 😄. But perhaps others moving to this SDK will be surprised by it. I imagine some folks might want to return the "last modified" date of the entity to a web UI without performing another round trip or using `DateTimeUtc.Now` as an approximation. But this is just guessing. Consider the `Timestamp` part to be the least important component of this issue from my perspective 👍. 

> Preventing modification of entities is definitely not a goal, so if we are doing things to prevent that I'd like to fix it or explain the expected approach. If you have examples of scenarios where it seems like we are making it difficult to modify an entity, please share them.

Sorry, I think what I said was confusing. What I mean is that (AFAIK) none of the Azure.Data.Tables APIs modify the provided entity. The provided entity is only read from (e.g. via reflected property getters) for producing the HTTP request body. I was thinking that perhaps this was a design philosophy and that was why the `ETag` was not being automatically updated/set on the entity provided to `Add`/`Update`/`Upsert`. I think I got this "feeling" originally from https://github.com/Azure/azure-sdk-for-net/issues/19671 but it also sort of makes sense, if you ask me, considering the `Merge` Table Storage operation which cannot bring the provided entity up to the current full state without another round trip since more properties may exist on the server which are not known about. 

Said another way, `WindowsAzure.Storage` updates the entity `ETag` when performing these operations so I was expecting the new SDK to either a) have strongly typed model containing the subsequent etag (akin to the Azure.Storage.Queue) or b) update the provided entity (akin to `WindowsAzure.Storage`).

> If you have examples of scenarios where it seems like we are making it difficult to modify an entity, please share them.

Only https://github.com/Azure/azure-sdk-for-net/issues/19671. I'll leave that issue's discussion out of this issue.

**Comment by joelverhagen** [comment]
As an aside, I'm a huge fan of Azure Table Storage (cheap+simple+fast) so I'm quite passionate about this new Azure.Data.Tables SDK. I am moving my side project over to the new SDK one module at a time and will be opening issues/PRs as I come upon things.

**Comment by christothes** [comment]
Thank you for the detailed and thoughtful feedback!

> I moved my entire codebase's blob and queue usage to the new Azure.* SDKs and I never had to use the `Response` object. There was always a model that specifically described that the service was returning in specific terms, rather than the generic HTTP response shape that `Response` describes. For example, consider [`BlobContentInfo.ETag`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobcontentinfo.etag?view=azure-dotnet#Azure_Storage_Blobs_Models_BlobContentInfo_ETag) returned by [`BlobClient.UploadAsync`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet).

The dilemma here is that by default, we do not echo the entity in the response for these operations. So if we did return a model type, it would need to be something that is just the `ETag`. Other than returning the whole entity, which seems like it would be inefficient in the main line case, I'm not sure if it would make sense to create a model containing just the `ETag`.

> Also, the `ETag` is nullable on `Response.Headers.ETag` but I think Table storage will always return an ETag for these operations so caller (code using the SDK) needs to do the research to be sure that you can safely do `ETag.Value` all the time and not check for null.
> 
> If the `ETag` were null for some reason this would cause serious problems for a sequence of optimistic concurrency calls! You'd either have to do a subsequent, unconditional entity update with no etag (dangerous) or perform a `GET` and diffgram-like operation to determine if the current entity state matches what was just `PATCH`/`POST`ed so that the returned etag can be used.

When calling `UpdateEntity`, the ETag value is required. We'll throw if it is a default value, and unless it is set to "*", it will never be treated as an unconditional update.

> Sorry, I think what I said was confusing. What I mean is that (AFAIK) none of the Azure.Data.Tables APIs modify the provided entity. The provided entity is only read from (e.g. via reflected property getters) for producing the HTTP request body. I was thinking that perhaps this was a design philosophy and that was why the `ETag` was not being automatically updated/set on the entity provided to `Add`/`Update`/`Upsert`. I think I got this "feeling" originally from #19671 but it also sort of makes sense, if you ask me, considering the `Merge` Table Storage operation which cannot bring the provided entity up to the current full state without another round trip since more properties may exist on the server which are not known about.
> 
> Said another way, `WindowsAzure.Storage` updates the entity `ETag` when performing these operations so I was expecting the new SDK to either a) have strongly typed model containing the subsequent etag (akin to the Azure.Storage.Queue) or b) update the provided entity (akin to `WindowsAzure.Storage`).

OK, interesting. Yes, I think I prefer having the operations not affect the supplied entity. Updating just the `ETag` seems inconsistent, and updating the whole entity makes some assumptions that the object is not being used again for something else by the caller.
