### ISSUE TITLE
[QUERY] Azure.Messaging.Service bus custom TokenCredential using MSAL ConfidentialClientApplication and number of calls to get access token

### ISSUE THREAD

**Issue by chris-skuvault** [Azure/azure-sdk-for-net#19730]
**Query/Question**
How can we help?

Currently we use a custom implementation of a TokenCredential and pass it into the ServiceBusClient. This uses MSAL ConfidentialClientApplication and calls AcquireTokenForClient passing in the scopes for the overridden GetTokenAsync callback. It seems like we are seeing a lot of network noise every time this gets called.

My question is does this get called every time a amqp link is opened and should we provide some mechanism in the overridden GetTokenAsync to account for being called multiple times as it seems like we get thousands of outgoing requests to login.microsoft.com roughly every 55 mins? 

We have thousands of receivers running at the same time so if each receiver would call this around the same time it might account for what we are seeing. Just trying to understand if we need to synchronize the GetTokenAsync with a lock and then after the first access token gets acquired all subsequent calls that are let into the lock can be checked to see if an access token is still needed based on the new access tokens expiration. Does this seem like a correct approach and would the GetTokenAsync be called as many times as we are seeing?

**Environment:**
 - Azure.Messaging.Service 7.0.0
 - Net core 3.1

**Comment by jsquire** [comment]
Hi @chris-skuvault.  Thank you for reaching our and we regret that you're experiencing difficulties.  The token credential does get sent each time an AMQP link is opened as well as when its expiration is near (or at the 49 day mark, whichever comes first).   The credential is assumed responsible for understanding when it is safe to perform local caching and when an active request is needed.  The credential is also assumed to be thread-safe. 

As I know there are MSAL mechanisms for caching and some caveats around doing so, I'll ask @schaabs for any thoughts or learnings from `Azure.Identity` that may help in that context.

**Comment by chris-skuvault** [comment]
Hey @jsquire,

Thanks for the information. That helps me understand that I will need to handle local caching of the token and as well as making sure its thread safe. 

Our current implementation is similar to https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpClient.cs#L204 method so the current plan is to add a lock  around calling azure to acquire the token and if we detect that we need to acquire a new token then we will acquire it only on the first call to GetTokenAsync and cache the result of that. Subsequent ampq links that called GetTokenAsync that were waiting on the lock can then enter and check and see that the token is no longer expired and just to use the new token. This should help us cut down on calls we see being sent to azure. 

Does this approach sound reasonable to you?

**Comment by jsquire** [comment]
It sounds reasonable off the top of my head, and should work.  Though the lock-based implementation does come with performance trade-offs.  Since the majority of Service Bus use should be background calls to refresh, it shouldn't be impactful.  That is, unless there is some unusual pattern where client instances are being created/closed often and new AMQP links are needed frequently.
