### ISSUE TITLE
Are the service clients registered via Microsoft.Extensions.Azure DI already using .NET Core's `IHttpClientFactory` management to avoid socket exhaustion?

### ISSUE THREAD

**Issue by felinepc** [Azure/azure-sdk-for-net#19732]
I just want to confirm that when I use

```
 services.AddAzureClients(builder =>
 {
     builder.AddQueueServiceClient(...)
     .WithCredential(...);
});
```
Then later inject the service client and use
```
var queueClient = _queueServiceClient.GetQueueClient(...);
```
I assume the underlying `HttpClient` to make the API calls is already optimized for reusability, i.e., using .NET Core's `IHttpClientFactory` for message handler pooling, to avoid issues such as socket exhaustion? 

Also I assume there is no need for any manual disposing when used in any transient/socoped/singleton classes?

Clarifications would be greatly appreciated!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
We are not using the `IHttpClientFactory` but the HttpClient backing the QueueService client is optimized for reusability.
