### ISSUE TITLE
AddLoggedHeadersAndQueryParameters 

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#19743]
See an example here: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClientOptions.cs#L66

This will allow the user to see more information, specially when something fails.

**Comment by a-noyass** [comment]
Update BadRequest sample after this is fixed
