### ISSUE TITLE
Cannot round trip nullable enum property in Azure.Data.Tables

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#19769]
**Describe the bug**
When a nullable enum is used on an `ITableEntity` implementation, serialization (writing the entity) works but deserialization (reading the entity) fails with an exception.

**Expected behavior**
When the entity property is a string (not null) `Enum.Parse` should be called internally. This is properly done for non-nullable enums. When the entity property does not exist (essentially the null case since Azure Table Storage doesn't store nulls), the default property value should be left (or `null` should be assigned).

**Workaround**
Use a string property for the nullable enum and add a `public MyEnum? GetMyEnum() { ... }` method that handles the mapping.

**Actual behavior (include Exception or Stack Trace)**
The entity cannot be deserialized using, say, `GetEntityAsync<T>(...)` and an exception is thrown.

```
Unhandled exception. System.ArgumentException: Object of type 'System.String' cannot be converted to type 'System.Nullable`1[ConsoleApp5.Program+MyEnum]'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Azure.Data.Tables.DictionaryTableExtensions.ToTableEntity[T](IDictionary`2 entity, PropertyInfo[] properties)
   at Azure.Data.Tables.TableClient.GetEntityAsync[T](String partitionKey, String rowKey, IEnumerable`1 select, CancellationToken cancellationToken)
   at ConsoleApp5.Program.Main(String[] args) in C:\Users\joelv\Desktop\ConsoleApp5\ConsoleApp5\Program.cs:line 17
   at ConsoleApp5.Program.<Main>(String[] args)
```
**To Reproduce**

```csharp
using System;
using System.Threading.Tasks;
using Azure;
using Azure.Data.Tables;

namespace ConsoleApp5
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var client = new TableServiceClient("UseDevelopmentStorage=true");
            var table = client.GetTableClient("mytable");
            await table.CreateIfNotExistsAsync();
            var pk = Guid.NewGuid().ToString();
            await table.AddEntityAsync(new MyEntity { PartitionKey = pk, RowKey = "rk", MyProperty = MyEnum.Foo });
            var output = await table.GetEntityAsync<MyEntity>(pk, "rk");
        }

        public class MyEntity : ITableEntity
        {
            public string PartitionKey { get; set; }
            public string RowKey { get; set; }
            public DateTimeOffset? Timestamp { get; set; }
            public ETag ETag { get; set; }
            public MyEnum? MyProperty { get; set; }
        }

        public enum MyEnum
        {
            Foo,
            Bar,
        }
    }
}
```

**Environment:**
 - Name and version of the Library package used: 12.0.0-beta.6
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET 5

<details>

    .NET SDK (reflecting any global.json):
    Version:   6.0.100-preview.1.21103.13
    Commit:    b8a03527b2

    Runtime Environment:
    OS Name:     Windows
    OS Version:  10.0.19042
    OS Platform: Windows
    RID:         win10-x64
    Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.1.21103.13\

    Host (useful for support):
    Version: 6.0.0-preview.1.21102.12
    Commit:  9b2776d481

    .NET SDKs installed:
    5.0.100 [C:\Program Files\dotnet\sdk]
    5.0.102 [C:\Program Files\dotnet\sdk]
    5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
    5.0.201 [C:\Program Files\dotnet\sdk]
    6.0.100-preview.1.21103.13 [C:\Program Files\dotnet\sdk]

    .NET runtimes installed:
    Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
    Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.AspNetCore.App 6.0.0-preview.1.21103.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.NETCore.App 6.0.0-preview.1.21102.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
    Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.0-preview.1.21103.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

    To install additional .NET runtimes or SDKs:
    https://aka.ms/dotnet-download
</details>

 - IDE and version : VS 16.9

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Good find - thanks!

**Comment by LEBATRUNG** [comment]
Tkanhs

**Comment by LEBATRUNG** [comment]
Tkanhs

**Comment by LEBATRUNG** [comment]
Tkanhs
