### ISSUE TITLE
Tables:  Error message is missing relevant details

### ISSUE THREAD

**Issue by baskialdensys** [Azure/azure-sdk-for-net#19779]
Getting PropertyNameInvalid error. This is not helpful unless the actual propertyname is listed in the error message.

{"odata.error":{"code":"PropertyNameInvalid","message":{"lang":"en-US","value":"The property name is invalid.\nRequestId:74dc5939-bfba-4954-b84b-b58f83b7a33b\nTime:2021-03-24T14:06:26.9960796Z"}}}

**Comment by LEBATRUNG** [comment]
****

**Comment by jsquire** [comment]
Hi @baskialdensys.  Thank you for your feedback and we regret that you're experiencing difficulties.  Can you help me understand which Azure library you're using so that I can make sure that we share your feedback with the folks best able to assist?

**Comment by baskialdensys** [comment]
Azure.Data.Tables(12.0.0.-beta.6). I'm using Azure storage emulator .

**Comment by christothes** [comment]
Hi @baskialdensys  - Can you provide a bit more detail about the repro steps required to generate this error in your scenario?

**Comment by christothes** [comment]
Thanks @baskialdensys - Unfortunately, this message comes from the service and it does not provide details about which property was invalid.

**Comment by baskialdensys** [comment]
I believe the server exception are translated to RequestFailedException in the client sdk side. Please check the following stackoverflow thread https://stackoverflow.com/questions/14859405/azure-table-storage-returns-400-bad-request/14866888
The server might return StorageException and that might have more info.(StorageException.RequestInformation.ExtendedInformation)

**Comment by christothes** [comment]
Unfortunately, the error you supplied above is all the information returned by the service. It offers no additional extended information that could be used to populate more details in the exception produced by the client SDK.
