### ISSUE TITLE
[BUG] Should not have to disable VisualStudioCodeCredential on macOS

### ISSUE THREAD

**Issue by elliotchaim** [Azure/azure-sdk-for-net#19777]
Re-open this issue: https://github.com/Azure/azure-sdk-for-net/issues/14362

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Thanks @elliotchaim for raising this issue! I've re-opened the linked issue. I'll close this one out as a duplicate of #14362

**Comment by christothes** [comment]
Duplicate of #14362
