### ISSUE TITLE
[FEATURE REQ] Allow specific properties to be ignored on ITableEntity implementation

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#19782]
**Library or service name.**
Azure.Data.Tables
 
**Is your feature request related to a problem? Please describe.**
Currently all public instance properties on an `ITableEntity` implementation are serialized to Azure Table Storage.
https://github.com/Azure/azure-sdk-for-net/blob/533ee2530f783f081d04c4bbcb79d483d9ef16a6/sdk/tables/Azure.Data.Tables/src/Extensions/TableEntityExtensions.cs#L24

For my scenario, I have several read-only (no setter), convenience properties that I do not want serialized to Table Storage. Also, I have other properties that have both getters and setters than I do not want serialized. This latter case are nullable enum properties that are workarounds for https://github.com/Azure/azure-sdk-for-net/issues/19769.

In both `{ get; }` and `{ get; set; }` cases, I want to be able to mark specific properties as ignored.

In `WindowsAzure.Storage`, you can do this with an [`[IgnoreProperty]`](https://docs.azure.cn/en-us/dotnet/api/microsoft.windowsazure.storage.table.ignorepropertyattribute?view=azure-dotnet) attribute. There are also analogies in Newtonsoft.Json, System.Text.Json, etc.

One question is whether `{ get; }` only properties should ever be serialized considering they fail round-tripping with this exception:

```
Result Message:	System.ArgumentException : Property set method not found.
Result StackTrace:	
at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Azure.Data.Tables.DictionaryTableExtensions.ToTableEntity[T](IDictionary`2 entity, PropertyInfo[] properties)
   at Azure.Data.Tables.DictionaryTableExtensions.ToTableEntityList[T](IReadOnlyList`1 entityList)
   at Azure.Data.Tables.TableClient.<>c__DisplayClass33_0`1.<<QueryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToList.cs:line 36
   at Knapcode.ExplorePackages.Worker.BaseCatalogScanIntegrationTest.AssertEntityOutputAsync[T](TableClient table, String dir, Action`1 cleanEntity) in C:\z\Git\joelverhagen\ExplorePackages\test\ExplorePackages.Worker.Logic.Test\TestSupport\BaseCatalogScanIntegrationTest.cs:line 90
   at Knapcode.ExplorePackages.Worker.FindLatestCatalogLeafScan.FindLatestCatalogLeafScanIntegrationTest.AssertOutputAsync(String dir) in C:\z\Git\joelverhagen\ExplorePackages\test\ExplorePackages.Worker.Logic.Test\CatalogScan\Drivers\Internal_FindLatestCatalogLeafScan\FindLatestCatalogLeafScanIntegrationTest.cs:line 118
   at Knapcode.ExplorePackages.Worker.FindLatestCatalogLeafScan.FindLatestCatalogLeafScanIntegrationTest.Internal_FindLatestCatalogLeafScan.Execute() in C:\z\Git\joelverhagen\ExplorePackages\test\ExplorePackages.Worker.Logic.Test\CatalogScan\Drivers\Internal_FindLatestCatalogLeafScan\FindLatestCatalogLeafScanIntegrationTest.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
```

**Workarounds:**
- Implement these properties as `GetFoo()` or `SetFoo(...)` methods for ignored properties.
- Implement an `IDictionary<string, object>` instead of `ITableEntity` and manage the dictionary building yourself.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
related to #15383

**Comment by ChadNedzlek** [comment]
I use this feature very often to wrap PartitionKey and RowKey with more meaningful named properties, so that I don't have to repeat data in the table, but I can do something like:
```csharp
[Ignore]
public int BuildId {
  get => int.Parse(RowKey);
  set => RowKey.ToString();
```

That way my code isn't filled with a bunch of code having to have comments like
CallAThing(int.Parse(entity.RowKey) /* this is the Build id */)

**Comment by jmelkins** [comment]
I use [IgnoreProperty] both to have convenience properties and to allow custom storing of enum values, and would also like to have this attribute available, not least so I can move code from depending on Microsoft.Azure.Cosmos.Table without major refactoring.

**Comment by christothes** [comment]
This is implemented in the latest version of the client via the `[IgnoreDataMember]` attribute.

#addressed

**Comment by jmelkins** [comment]
Is that the IgnoreDataMemberAttribute from System.Runtime.Serialization? - It's not exactly obvious that this should apply and not so discoverable since a) System.Runtime.Serialization will not typically be in scope as creators of classes derived from ITableEntity will not typically be doing binary or XML serialization (i.e. intellisense will not find this attribute), and b) while the library may use System.Runtime.Serialization classes internally to serialize objects into Azure Table Storage, this is an implementation detail that I think I should not need to know.

I think the library needs an IgnorePropertyAttribute (or similar name) in the Azure.Data.Tables namespace, for easy discoverability, in the same way that System.Text.Json and Newtonsoft.Json have their own JsonIgnoreAttribute in the same namespace.

**Comment by christothes** [comment]
> Is that the IgnoreDataMemberAttribute from System.Runtime.Serialization? -

yes.


> I think the library needs an IgnorePropertyAttribute (or similar name) in the Azure.Data.Tables namespace, for easy discoverability, in the same way that System.Text.Json and Newtonsoft.Json have their own JsonIgnoreAttribute in the same namespace.

Thanks for the feedback, however I don't think we'd ever create a custom attribute specific to SDK client libraries.

**Comment by peter-bozovic** [comment]
I'm currently migrating to Azure Storage v12 library and hitting an issue with the changes from IgnoreProperty to IgnoreDataMember.

My object has read-only properties that I don't want to save into the table, but I want to serialize them as Json.

Currently, if I put IgnoreDataMember on this property it won't be saved to the table, but won't be serialized into Json either.

And if I remove IgnoreDataMember to have this property in my Json, my AddEntity to the table will throw "Not supported type" exception

It would be nice if we could have back the InoreProperty so that we can fine tune what we want to persist into Azure Table or not, or for example just ignore the read-only properties when doing AddEntity and avoid the exception, or there is another solution that I'm not aware of ...

**Comment by christothes** [comment]
@peter-bozovic What type is the property when it causes the "Not Supported Type" exception? Assuming it is some complex object type, what if you store the property as its object type with the IgnoreDataMember attribute and serialize the object as JSON into a different unignored property in the setter for the first property?

**Comment by peter-bozovic** [comment]
Yes, my property that I want to ignore for my Azure table storage is custom class used to reformat data.
About creating another property for the JSON serialization, woudn't I hit the same issue as the first property since it's unignored ?

Simplified exemple of my previous implementation:
```
public class MyPerson : TableEntity {
	//	...
	//	... Other properties
	//	...

	// This is the value that I want to persist in my Azure Table
	public string FullName { get; set; }

	// This is the property that I want to serialize into my JSON
	[IgnoreProperty]
	public Person Person {
		get {
			var data = FullName.Split(' ');
			return new Person() { FirstName = data[0], LastName = data[1] };
		}
	}
}
```

So when I removed the [IgnoreProperty], I got the Not Supported Type exception, and then when I added [IgnoreDataMember] instead, it's not serialized anymore into my JSON ...

**Comment by christothes** [comment]
If you needed to persist the who serialized Person object in the table, I was thinking something more like this:

```c#
public class MyPerson : ITableEntity {

    public string PersonJson { get; set; }

    private Person _person;
    [IgnoreDataMember]
    public Person Person {
        get { 
            if (_person == null)
            {
                 _person = JsonSerializer.Deserialize<Person>(PersonJson);
            }
            return _person;
        set { 
            _person = value;
                PersonJson = JsonSerializer.Serialize(_person);
    }
}
```

Alternatively, you could explode all distinct properties of `Person` into the `MyPerson` model.

```c#
public class MyPerson : ITableEntity {
    //    ...
    //    ... Other properties
    //    ...

    public string FirstName { get; set; }
    public string LastName { get; set; }

    // This is the value that I want to persist in my Azure Table
    [IgnoreDataMember]
    public string FullName => $"{FirstName} {LastName}"

    private Person _person;
    [IgnoreDataMember]
    public Person Person {
        get { 
            if (_person == null)
            {
                 _person = new Person(){ FirstName = FirstName, LastName = LastName };
            }
            return _person;
        set { 
            _person = value;
            FirstName = _person.FirstName;
            LastName = _person.LastName;
    }
}
```

**Comment by christothes** [comment]
Perhaps I am missing something, but in the first example above, `PersonJson` contains "{"FirstName":"John","LastName":"Doe"}" and is DeSerialized to the ignored `Person` property the first time it is accessed.

**Comment by peter-bozovic** [comment]
Yes, the object itself is deserialized and contains the values, but if I want to return it as Json for API for example, it will be ignored ...
Example of the result: https://dotnetfiddle.net/ketjE6

**Comment by christothes** [comment]
> Yes, the object itself is deserialized and contains the values, but if I want to return it as Json for API for example, it will be ignored ... Example of the result: https://dotnetfiddle.net/ketjE6

Your fiddle works if you remove the `JsonIgnore` attribute from `PersonJson` - You'd need that property to be serialized and sent to/from the table for it to be serializable.

**Comment by peter-bozovic** [comment]
I'll have PersonJson property as text, but not the Person object with multiple properties
You get :
`
{"PersonJson":"{\"FirstName\":\"John\",\"LastName\":\"Doe\"}"}
`
Instead of
`
{"Person":{"FirstName":"John","LastName":"Doe"}}
`

`[JsonIgnore]` allows me to store the serialized text into the Azure table without having it in the Json output, while the previous `[IgnoreProperty]` allowed me to have the property for Json serialization that was not stored in the Azure rable.
That's unfortunately not possible anymore with the new SDK

**Comment by christothes** [comment]
Thanks for clarifying - and I appreciate your patients as I ask these questions!

One part I am not quite understanding - why would you need to call `JsonConvert.SerializeObject(person);` to get the serialized json of Person when you already have it in `PersonJson`? The output you are getting from `JsonConvert.SerializeObject(person);` is the same but with the Person object assigned to another object's Person property.

**Comment by peter-bozovic** [comment]
As explained in my previous comment, the output is not the same, serialized json text is not the same as json object (you'll notice quotes around the brackets and escape backslash for inside quotes)

**Comment by christothes** [comment]
This is because of how the json was initialized in the fiddle. This works:
https://dotnetfiddle.net/xiQOO5

```c#
using System;
using System.Runtime.Serialization;
using System.Text.Json;
using System.Text.Json.Serialization;

var person = new PersonTable() { Person = new Person { FirstName = "John", LastName = "Doe" }};
Console.WriteLine($"FirstName: {person.Person.FirstName}");

Console.WriteLine($"Serialized: {person.PersonJson}");
var po = JsonSerializer.Deserialize<Person>(person.PersonJson);

public class Person
{
	public string FirstName { get; set; }
	public string LastName { get; set; }
}

public class PersonTable
{

	[JsonIgnore]
	public string PersonJson { get; set; }

	private Person _person;
	[IgnoreDataMember]
	public Person Person
	{
		get
		{
			if (_person == null)
			{
				_person = JsonSerializer.Deserialize<Person>(PersonJson);
			}
			return _person;
		}
		set
		{
			_person = value;
			PersonJson = JsonSerializer.Serialize(_person);
		}
	}
}
```

**Comment by peter-bozovic** [comment]
The simplified example doesn't contain other properties within the `PersonTable`, but I need to return the serialized `PersonTable` with other properties, including the complex objects.
You are writing `person.PersonJson` instead of serialized `person` (that I tried to demonstrate in my initial fiddle)

**Comment by jmelkins** [comment]
The difference between code examples is that the Json.NET serializer, unlike the one from System.Text.Json, recognizes the [IgnoreDataMember] leading to a clash.

The problem could be resolved by switching to System.Text.Json but if you want to stay with Json.NET then perhaps a suitable workaround would be to make properties opt-in for JSON serialization, which is supported by Json.NET?

```c#
using System;
using System.Runtime.Serialization;
using Newtonsoft.Json;

var person = new PersonTable
{
    PersonJson = "{\"FirstName\":\"John\",\"LastName\":\"Doe\"}",
    OtherProperty = "OtherValue"
};

Console.WriteLine($"FirstName: {person.Person.FirstName}");
var serialized = JsonConvert.SerializeObject(person);
Console.WriteLine($"Serialized: {serialized}");

public class Person {
	public string FirstName { get; set; }
	public string LastName { get; set; }
}

[JsonObject(MemberSerialization.OptIn)] // Makes properties opt-in for JSON rather than the default opt-out
public class PersonTable {

	public string PersonJson { get; set; }

    private Person _person;
    
	[JsonProperty]  // Opt-in to JSON serialization
	[IgnoreDataMember]
    public Person Person {
        get { 
            if (_person == null)
            {
                 _person = JsonConvert.DeserializeObject<Person>(PersonJson);
            }
            return _person;
		}
        set { 
            _person = value;
			PersonJson = JsonConvert.SerializeObject(_person);
	    }
	}
	
	[JsonProperty]  // Opt-in to JSON serialization
	public string OtherProperty { get; set; }
}
```

[https://dotnetfiddle.net/hr4sre](url)

Or taking the first code example posted:

```c#
[JsonObject(MemberSerialization.OptIn)]
public class MyPerson : TableEntity {
	//	...
	//	... Other properties
	//	...

	// This is the value that I want to persist in my Azure Table
	public string FullName { get; set; }

	// This is the property that I want to serialize into my JSON
        [JsonProperty]
        [IgnoreDataMember]
	public Person Person {
		get {
			var data = FullName.Split(' ');
			return new Person() { FirstName = data[0], LastName = data[1] };
		}
	}
}
```

You would need to add [JsonProperty] to all other properties that you want to appear in the JSON.
Perhaps this can help?

**Comment by peter-bozovic** [comment]
Thanks @jmelkins, this is exactly what I needed ! 
I was sure there must be some way but was not aware of the `MemberSerialization.OptIn` option ...

On the subject of `System.Text.Json`, I had the inverse problem in another project where I needed it to take into account the [IgnoreDataMember] (defined in another class I don't have control over), but currently it doesn't . Apparantly it's planned for future version or maybe already inplemented in dotnet 6. 

`System.Text.Json` has it's own specific `[JsonIgnore]` and I think it was good to have also specific `[IgnoreProperty]` for Azure Tables. That allowed to fine tune which properties should be included for which logic.
If tomorrow everyone uses just `[IgnoreDataMember]` it will not be possible to do such distinction anymore ...
