### ISSUE TITLE
Add live tests that update the Named key value

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#19798]
Would it be possible to have a live test where we actually update the key after the client is already constructed and after we've already done some operations with the initial key? Maybe we could just update it to use the secondary key from the namespace.

_Originally posted by @JoshLove-msft in https://github.com/Azure/azure-sdk-for-net/pull/19785#discussion_r600875650_

**Comment by JoshLove-msft** [comment]
We can use the ARM package to invalidate the primary key and regenerate keys as needed.

**Comment by jsquire** [comment]
After 2 years, I think it's safe to assume that we don't plan on doing this.   closing it out.
