### ISSUE TITLE
Add tests to ACR Auth Policy for concurrency scenarios

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#19792]
Add a unit test to the collection of auth policy tests to ensure that the correct behavior happens when two messages come through at the same time.

**Comment by pallavit** [comment]
@annelo-msft could you please share more details on what the scenario is here? Looking at the implementation here the parallelization is handled by the BearerTokenAuthenticationPolicy and ACR auth policy is only parsing the jwt token as needed.
