### ISSUE TITLE
In ContainerRegistryChallengeAuthenticationPolicy, evaluate failure scenarios

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#19791]
See comment: https://github.com/Azure/azure-sdk-for-net/pull/19696#discussion_r599948927

We'll want to look into whether or not this has an effect on retries, and what the desired outcome here should be.

**Comment by pallavit** [comment]
Given we have not seen any customer reports around it, I will go ahead and close this issue. Feel free to open if you disagree
/cc: @annelo-msft
