### ISSUE TITLE
[FormRecognizer] Add tests for BMP image format

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#19809]

**Comment by maririos** [comment]
Last sprint we decided not to add a test for it as this was more like testing the service than the SDK. We did add a test for the content type https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/Extensions/StreamExtensionsTests.cs#L56

Do you think we should still add a BMP test and therefore one per every content type the service supports?

**Comment by kinelski** [comment]
> Do you think we should still add a BMP test and therefore one per every content type the service supports?

No, I think you have a point. Since we're already testing our `TryGetContentType` method, this should be enough.

Closing the issue.
