### ISSUE TITLE
Bug in KeyVaultClient.GetSecretsAsync with maxresults not allowed to be more than 25

### ISSUE THREAD

**Issue by dshakhovsky** [Azure/azure-sdk-for-net#19802]
KeyVaultClient.GetSecretsAsync doesn't allow to retrieve more than 25 records when you supply a parameter maxresults > 25.
it throws the exception that maximum allowed number is 25
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fdb88857-aa4a-5c4b-1ae7-0e2d754192a1
* Version Independent ID: de0e86da-2808-be84-ff5e-2200f9b16043
* Content: [KeyVaultClient Class (Microsoft.Azure.KeyVault) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.keyvaultclient?view=azure-dotnet-legacy)
* Content Source: [xml/Microsoft.Azure.KeyVault/KeyVaultClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.KeyVault/KeyVaultClient.xml)
* Service: **key-vault**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Thank you for the feedback.

We [do not validate client-parameters](https://azure.github.io/azure-sdk/general_implementation.html#parameter-validation) beyond null checks for required parameters to avoid tightly coupling to the service, which can and does change. Did you find the error message was specific to this case?

I also wanted to point out that `KeyVaultClient` in the Microsoft.Azure.KeyVault package is deprecated and no further development is being done on it. While it wouldn't resolve this particular issue (if the limit still exists in newer API versions), we recommend customers upgrade to Azure.Security.KeyVault.* packages. We have separate packages (which can be used together if needed) for Secrets, Keys, and Certificates.

**Comment by bballpaul4work** [comment]
Using the API and specifying any number greater than 25 for maxresults yields the same issue. Error message, Bad parameter "invalid maxresults". 
https://docs.microsoft.com/en-us/rest/api/keyvault/getsecrets/getsecrets
GET {vaultBaseUrl}/secrets?maxresults={maxresults}&api-version=7.1

There is no way to retrieve more than 25 secrets...

**Comment by heaths** [comment]
Thank you. I will pass the feedback along to the service team to include the limit in the error message.

**Comment by heaths** [comment]
I should add that in our newer libraries - Azure.Security.KeyVault.* - you don't need to worry about it. E.g.:

```csharp
await foreach (KeyVaultKey key in keyClient.GetPropertiesOfSecretsAsync())
{
  Console.WriteLine(key.Name);
}
```
This will fetch additional pages as needed based on the server response.
