### ISSUE TITLE
[FormRecognizer] Regression in invoice test in service version 2.1-preview.3

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#19810]
Test `StartRecognizeInvoicesPopulatesExtractedTiff` stopped returning the `InvoiceTotal` field.

Goals:
- Notify the service team about the regression.
- Uncomment commented sections of the test when issue is fixed.

```cs
// Assert.True(form.Fields.ContainsKey("InvoiceTotal"));
// Assert.That(form.Fields["InvoiceTotal"].Value.AsFloat(), Is.EqualTo(56651.49f).Within(0.0001));
```

**Comment by maririos** [comment]
We decided to remove extra test for each endpoint, so the `tiff` test went away. It also seems like files need to follow a more strict format which is probably why the service was fialing.
https://github.com/Azure/azure-sdk-for-net/pull/20018
