### ISSUE TITLE
Retry failed after 4 tries. (The SSL connection could not be established, see inner exception.)

### ISSUE THREAD

**Issue by krunalnexus** [Azure/azure-sdk-for-net#19814]
`

string businessCardsPath = file.Path; // where file.path is Phone's Image Path
 using var stream = new FileStream(businessCardsPath, FileMode.Open);
 var options = new RecognizeBusinessCardsOptions() { Locale = "en-US" };

 RecognizeBusinessCardsOperation operation = await client.StartRecognizeBusinessCardsAsync(stream, options); // Getting Error : Retry failed after 4 tries. (The SSL connection could not be established, see inner exception.)`

**Comment by jsquire** [comment]
Hi @krunalnexus.  Thank you for reaching out and we regret that you're experiencing difficulties.  From the available context, this seems likely a network-related issue.   In order for us to assist, can you help us better understand the context and whether this a consistent failure that you can reproduce?

It would be very helpful to see the details of the inner exception, as the message that you're seeing indicates.   Would you be willing to share the inner exception type, message, and stack trace?

**Comment by krunalnexus** [comment]
Hello,
I was using Formrecogniser API into Xamarin. it works well on IOS but when i hit API in Android it shows above error.
Currently it's working fine on other device.
