### ISSUE TITLE
When a field is an AvroUnion of Null and a Non-primitive type, incorrect code is generated

### ISSUE THREAD

**Issue by adammodlin** [Azure/azure-sdk-for-net#1982]
I was working with a schema (attached in .zip) with a field defined like so:

```
"fields": [
        {"name": "shouldNotBeObject", "type":
            [  
                "null",
                {"type":"map", "values": 
                    { "type": "array", "items":
                        {"type":"string","avro.java.string":"String"} 
                    } 
                }
            ]
        }
    ]
```

When running `Microsoft.Hadoop.Avro.Tools codegen` incorrect code is generated. The field is given type `object` on the property as well as for the parameter in the constructor. In this example, the field should be type `Dictionary<string,IList<string>>`.

I am a Microsoft FTE (admodlin). I reached out to Maxim Lukiyanov and he suggested I submit a bug and a PR. This is my first time doing this so please let me know if I did something wrong.

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.
