### ISSUE TITLE
[FormRecognizer] Multipage receipt tests should use multipage receipt files

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#19826]
Currently we're using multipage invoices to test our receipts API. This makes the recognition not so reliable and prone to behavior changes with every service update.

We should get proper multipage receipt files for our tests.

**Comment by maririos** [comment]
Java is adding a proper multipage receipt file so we can copy it

**Comment by maririos** [comment]
https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/formrecognizer/azure-ai-formrecognizer/src/test/resources/sample_files/Test/contoso_allInOne_multipage_receipt.pdf
