### ISSUE TITLE
[FormRecognizer] StartRecognizeCustomForms changed behavior when a broken file is passed

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#19829]
Originally we could successfully start a Custom Form recognition operation with a damaged file. The service would return an error only when polling the operation status.

This old test illustrates this behavior:
https://github.com/Azure/azure-sdk-for-net/blob/2a0a498df4b066bd836d1130e2c415632f1f5010/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/FormRecognizerClientLiveTests.cs#L2359-L2366

Starting in service version 2.1-preview.3, the behavior changed to throw as soon as the user tries to start the long-running operation, which can be seen in the updated test below:
https://github.com/Azure/azure-sdk-for-net/blob/b2737417f9a1e8f705209d8f7dc0d971955a58dd/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/FormRecognizerClientLiveTests.cs#L2362-L2363

Related discussion: https://github.com/Azure/azure-sdk-for-net/pull/19799#discussion_r600939467
Similar issue: https://github.com/Azure/azure-sdk-for-net/issues/19375

This is a breaking change, so we should follow up with the service and the SDK team.

**Comment by maririos** [comment]
After following up with REST API board and .NET architects, this is considered an ok change. We have added it to our Changelog notes so users get notified.
