### ISSUE TITLE
Live test are printing way too much information and is polluting our test output

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#19835]
This started happening around March 9th and I see if in multiple libraries:
- TA:
  - Before March 9th and preferred output: [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=772942&view=logs&j=9f6e9dd9-0daa-5061-5c37-5c529436a384&t=7d15db3d-f1cc-50eb-c1e0-80c490f74744)
  - After with too much info: [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=775167&view=logs&j=9f6e9dd9-0daa-5061-5c37-5c529436a384&t=7d15db3d-f1cc-50eb-c1e0-80c490f74744)
- [Translator](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=804654&view=logs&j=68082d65-ebf7-5f3f-494d-d3fd09e80dd6&t=6f6444ca-c101-5878-5224-de85502bb056)
- FR:
  - [Before](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=773053&view=logs&j=9f6e9dd9-0daa-5061-5c37-5c529436a384&t=7d15db3d-f1cc-50eb-c1e0-80c490f74744)
  - [After](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=775351&view=logs&j=9f6e9dd9-0daa-5061-5c37-5c529436a384&t=7d15db3d-f1cc-50eb-c1e0-80c490f74744)

Was this on purpose? if so, is there a way to turn it off?

cc: @JoshLove-msft 
FYI @pakrym

**Comment by JoshLove-msft** [comment]
Interesting, it should only be printing the logs for failed tests.

**Comment by JoshLove-msft** [comment]
I'm guessing something changed in the new version of NUnit - https://github.com/Azure/azure-sdk-for-net/pull/19282
