### ISSUE TITLE
How to use AzureServiceTokenProvider.GetAccessTokenAsync to obtain an access token for an Azure Function http trigger protected by Azure AD authentication?

### ISSUE THREAD

**Issue by felinepc** [Azure/azure-sdk-for-net#19841]
I have an Azure Function app that uses the integrated Azure AD Authentication configured via the Azure portal.

Via the "Express" mode setup, this creates an Azure App Registration along with Enterprise Application.

Now when my app needs to invoke the function app HTTP triggers protected by this AAD auth, I need to set a bearer token.

I assume `AzureServiceTokenProvider.GetAccessTokenAsync` can be used to obtain such a token either as VS/Azure CLI (when in local dev) or as the managed identity (when deployed in Azure).

But I can't figure out which resource URL to use to obtain the token.

Is this a supported scenario?

**Comment by jsquire** [comment]
//cc: @nonik0,  @anaismiller

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by anaismiller** [comment]
@felinepc 
These links may be helpful for you [Azure Function Authentication](https://docs.microsoft.com/en-us/azure/app-service/overview-authentication-authorization) and [allowed ResourceUrls](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities#azure-services-that-support-azure-ad-authentication) .
Your understanding of what authentication method to use is correct. The resourceUrl would be for whatever service you are trying to access/authenticate to next. You should already be authenticated to the Azure Function with the initial integrated authentication.

**Comment by felinepc** [comment]
I figured it out. The resource URL is the function app instance, i.e.  https://appname.azurewebsites.net. 

HOWEVER, there is an additional step that is crucial: Under the App Registration of the service principal created by Azure Functions when AAD Auth was enabled, one must add any "non-interactive" clients (such as Azure CLI) to the "Authorized Client Applications" list under "Expose and API" (enter their Azure AD client ID). Otherwise these won't work when they attempt to access the app on behalf of a user, because they can't "consent" to the delegate permissions.
