### ISSUE TITLE
[BUG] Event Grid:  Unexpected Date Format

### ISSUE THREAD

**Issue by ThDoor** [Azure/azure-sdk-for-net#19859]
When publishing event to Azure Event Grid using the Azure Event Grid Event Schema DateTimeOffset in Data are converted to UTC.

The event is published as http request to event grid and viewed with the Azure Event Grid Viewer

br,

**Comment by jsquire** [comment]
Hi @ThDoor.  Thank you for reaching out and we regret that you're experiencing difficulties.   I'm not sure that I understand what you're describing.  `DateTimeOffset` is a type that is based on UTC and is not relative to local time as `DateTime` is.  _(see: [docs](https://docs.microsoft.com/en-us/dotnet/api/system.datetimeoffset))_.

Would you be so kind as to help us better understand your scenario by providing some additional context around what you're trying to do and what you're observing?  Code snippets would be very helpful, if you're able to share.

**Comment by ThDoor** [comment]
I publish an event to eventgrid with "timeOfEvent":"2022-03-29T10:15:30+04:00" in the payload.
When looking at the event in azure event grid viewer i see  "timeOfEvent": "2022-03-29T06:15:30+00:00"

**Comment by JoshLove-msft** [comment]
I just checked in our test records, and we do include the correct offset - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventgrid/Azure.Messaging.EventGrid/tests/SessionRecords/EventGridClientLiveTests/CanPublishSingleEvent.json#L18

It may be that the time is normalized to UTC by the service. @ahamad-MS can you comment?

**Comment by JoshLove-msft** [comment]
@ThDoor can you include the code you are using to publish the event?

**Comment by ThDoor** [comment]
@JoshLove-msft In this particular case I'm publishing directly to the endpoint and I got the datetime offset from the string content of the request, so I'm wondering if the service is normalising to utc. I'm using azure event grid schema. Br

**Comment by ThDoor** [comment]
Hi
Any updates on this one?
br

**Comment by ThDoor** [comment]
Hi @jsquire , @JoshLove-msft , @jfggdl 

It's been nearly 3 weeks without any feedback. 
Can you please give feedback?

best regards

**Comment by jsquire** [comment]
Hi @ThDoor.  I apologies for the lack of feedback.  Unfortunately, this was confirmed to be behavior in the Event Grid service and isn't something under the control of the SDK.  Neither @JoshLove-msft nor I have insight into the status or the triage process used by the Event Grid team.   We'll need to defer to @jfggdl.

**Comment by ThDoor** [comment]
Hi,
Thanks. Waiting for update from @jfggdl.
br

**Comment by ThDoor** [comment]
Hi @jfggdl,
Can you give any update? 
Best regards

**Comment by JoshLove-msft** [comment]
Hi @ThDoor, we chatted with the service team on this and they pointed us to the [documentation](https://docs.microsoft.com/en-us/azure/event-grid/event-schema#event-properties) that indicates that the EventTime is expected to be in UTC, so it appears that the service will convert it to UTC based on the provided DateTimeOffset.

**Comment by ThDoor** [comment]
Hi @JoshLove-msft , I'm fully aware of the specification on EventTime. I'm referring to a datetimeoffset in the data property of the event.  
There was a similar problem with cloud schema that apparently was fixed see https://stackoverflow.com/questions/53938043/avoid-converting-datetimeoffset-to-utc-time-in-azure-eventgrid

With an event like this, somePointInTime is normalized to UTC by eventgrid as I see it (should be fairly easy for you guys to test):
`[{
  "id": "deadbeef-cafe-4d7c-bd0c-e34b19da4e66",
  "topic": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "subject": "",
  "data": {
    "somePointInTime": "2021-04-22T14:47:42+02:00"
  },
  "eventType": "Thomas.Test.DateTimeOffsetModifiedWhenItShouldNotEvent",
  "eventTime": "2021-04-21T22:12:19.4556811Z",
  "metadataVersion": "1",
  "dataVersion": "1"
}]`

**Comment by ThDoor** [comment]
Hi @JoshLove-msft ,
![image](https://user-images.githubusercontent.com/27347655/115831735-4a6dab80-a412-11eb-8020-0b4d22d6de74.png)
Just adding a picture from event grid viewer documenting my point
best regards

**Comment by JoshLove-msft** [comment]
Thanks, I'm thinking that this may be an issue with the Event Grid Viewer as it is not configuring the DateParseHandling to be string, so it is using the default of DateTime.

**Comment by ThDoor** [comment]
Hi @JoshLove-msft,
Can you confirm that the bug I referenced above that was fixed in cloud schema, does not exist in event grid schema? Sounds like its the same issue.
Best

**Comment by JoshLove-msft** [comment]
I tested it out by delivering an event to a Service Bus queue. The DateTimeOffset was delivered with the offset to ServiceBus so it does not look like that is the bug. You can confirm this by viewing the delivered event using some other means than the event grid viewer.

**Comment by ThDoor** [comment]
Hi @JoshLove-msft ,
As you, I have now confirmed that the datetimeoffsets are delivered unmodified. The event grid viewer let me astray.
I'm closing this issue. Thank you for your assistance.

best
Thomas
