### ISSUE TITLE
Remove unnecessary unboxing and boxing

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#19852]
As @pakrym pointed out after running a memory profile, we have some unnecessary unboxing and boxing here - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpMessageConverter.cs#L322-L349

The MessageAnnotations Dictionary has `object` values, so there is no reason to cast from the `pair.Value` object to long, string, etc. as this does an unnecessary unboxing, only to rebox it when setting it into the dictionary.

**Comment by danielmarbach** [comment]
Coincidently this was the next thing on my list

**Comment by danielmarbach** [comment]
Here we go https://github.com/Azure/azure-sdk-for-net/pull/19856
