### ISSUE TITLE
calling CloudServiceManagementClient.Create on a pre-existing cloud service, an unexpected exception is thrown

### ISSUE THREAD

**Issue by pjganesh** [Azure/azure-sdk-for-net#1986]
The following code works fine the first time through - a fresh cloud service name and the service returns with an expected HttpStatusCode and CloudServiceOperationStatus.

On the second run (leaving the names the same to see what happens on a subsequent create with the same details), I expected the following code to print out "failed."

Instead, I received a CloudException instance with the message:
**"BadRequest: The condition specified by the ETag is not satisfied."**

var cloudServiceManagementClient = new CloudServiceManagementClient(new CertificateCloudCredentials(subscriptionId, certificate));
var response = loudServiceManagementClient.CloudServices.Create(&quot;myCloudService&quot;,
   new CloudServiceCreateParameters()
   {
        GeoRegion = &quot;uswest&quot;,
        Label = &quot;myCloudService&quot;,
        Description = &quot;My Cloud Service Scheduler&quot;,
       Email = &quot;[my-email-address-omitted]&quot;
   });

Creating this new bug since bug # 328 is closed & getting no response.

**Comment by markcowl** [comment]
@pjganesh Which version of the Schedule package are you using?

**Comment by pjganesh** [comment]
@markcowl : I'm using Microsoft.WindowsAzure.Management.Scheduler.dll v6.2.0.0

**Comment by adrianhall** [comment]
My apologies for taking so long.  I do note that the Scheduler package you are using is still the current one.  Is this still an issue?
