### ISSUE TITLE
[QUERY] Azure Service Bus Potential Bug in AmqpMessageExtensions due to underlying buffer returning?

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#19871]
Please bear with me, it is almost weekend and I might not have gotten this right. Still I figured I want to place it here for your consideration. I was looking at Azure.Messaging.ServiceBus receive path and went into the abyss of 

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpMessageExtensions.cs#L51-L70

It seems for cases when

`arraySegment.Count == arraySegment.Array?.Length`

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpMessageExtensions.cs#L57-L58

we are not taking a defensive copy of the memory like in

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpMessageExtensions.cs#L59-L67

Isn't that dangerous because the ArraySegments are managed through the MS AMQPLib internally and returned on AmqpMessage.Dispose which happens at line

https://github.com/Azure/azure-sdk-for-net/blob/845a37dd2d02b017245218c6bd6e33dcc86657fa/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpMessageConverter.cs#L368

I'm wondering if there is missing test coverage for this case. When I started tweaking 

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpMessageExtensions.cs#L59-L67

to no longer copy the memory for experiments the deadletter tests started failing because the body comparison no longer matches due to the memory being returned. But I figured the same should actually happen for the non-copying code I mentioned above.

// cc @JoshLove-msft @jsquire 

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by danielmarbach** [comment]
Also slightly related to discussion started in https://github.com/Azure/azure-sdk-for-net/issues/19666#issuecomment-808143529

**Comment by jsquire** [comment]
Thanks, @danielmarbach.  I probably won't get free to dig into this today, but I'll aim to circle back on Monday if Josh doesn't beat me to it.

**Comment by JoshLove-msft** [comment]
Yes, it does look like this is a bug (or at least dead code). I couldn't actually get a test to hit the branch as the arraysegment count is always less than the array length. Still, we should remove this case from the switch statement.

/cc @DorothySun216 as it looks like Track 1 has the same logic.

**Comment by danielmarbach** [comment]
Here we go https://github.com/Azure/azure-sdk-for-net/pull/19979
