### ISSUE TITLE
API consistency nitpicks for Azure.Data.Tables

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#19881]
**Library or service name.**
Azure.Data.Tables
 
**Is your feature request related to a problem? Please describe.**
I've been working on moving a project that uses Azure Table Storage heavily over to the new SDK. Love it so far. Just found a couple places that maybe could be brought to a more consistency state before the first RTM:

- [x] 1. No `Name` or `AccountName` properties on `TableClient`.
   - These are very helpful for logging when passing around `TableClient` to helper methods.
   - `QueueClient` has these
   - `BlobContainerClient` has these

- [x] 1. The `TableItem` type returned by `TableServiceClient.GetTableAsync(...)` has a `TableName` property instead of `Name`
   - No negative impact for me, just inconsistent
   - `BlobContainerItem` has `Name` ([docs](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobcontaineritem?view=azure-dotnet))
   - `QueueItem` has `Name` ([docs](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.models.queueitem?view=azure-dotnet))
   
- [ ] 1. No `TableClient.ExistsAsync()` method
   - Some of my tests could really use this. I have cases where I want to verify a table was not created.
   - Workaround: A small `Query` with no filter, catch the 404 ([example](https://github.com/joelverhagen/ExplorePackages/blob/6d23681b17d7c131f7f2ab25b111fc4bcb421ba6/src/ExplorePackages.Logic/Storage/TableExtensions.cs#L36-L49))
   - `QueueClient` has this
   - `BlobContainerClient` has this
   
- [x] 1. No `TableServiceClient.GetTablesAsync(Expression<Func<TableSomething, bool>>)` overload, you must write the OData yourself
   - I would prefer compile-time checks on comparisons against the available table properties for these queries
   - This is inconsistent with the `Expression<Func<T, bool>> filter` parameter on `TableClient.QueryAsync<T>`
   - Workaround: Use `TableClient.CreateQueryFilter<TableItem>` since fortunately (?) it doesn't have `ITableEntity` constraint
   
- [ ] 1. No `TableServiceClient.GetTablesAsync(prefix: ...)` overload
   - This is helpful for test clean-up. I have many integration tests that run in parallel, with their own table name prefix.
   - Workaround: use an OData range query, bounded on the top by some max char ([example](https://github.com/joelverhagen/ExplorePackages/blob/6d23681b17d7c131f7f2ab25b111fc4bcb421ba6/src/ExplorePackages.Logic/Storage/TableExtensions.cs#L15-L22))

- [x] 1. No `TableClient.DeleteIfExistsAsync`
   - This is helpful for clean-up/finalize routines in distributed workflows.
   - Already reported here https://github.com/Azure/azure-sdk-for-net/issues/13984 but linked for reference.

- [ ] 1. No `TableServiceClient.Uri`
   - This is helpful for diagnostics, for example if you have the wrong cloud endpoint suffix provided
   - `BlobServiceClient` has this
   - `QueueServiceClient` has this

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Great feedback! Thanks again for all the effort you've been putting in here!

**Comment by joelverhagen** [comment]
FYI I added another one that I ran into today, which is `TableServiceClient.Uri` is missing.

I was going to mention `TableServiceClient.CanGenerateAccountSasUri` as well but to be honest I don't know if it makes sense for Table. I think I've used it in the past for blobs...

**Comment by dzendras** [comment]
There is one more thing that's inconsistent in version 12.1.0. When creating TableServiceClient or TableClient using a connection string "UseDevelopmentStorage=true" for local development, then an attempt to access AccountName throws the following exception:

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: uri
  Source=Azure.Data.Tables
  StackTrace:
   at Azure.Data.Tables.TableUriBuilder..ctor(Uri uri)
   at Azure.Data.Tables.TableClient.get_AccountName()

BlobServiceClient & QueueServiceClient return "devstoreaccount1".

**Comment by christothes** [comment]
> There is one more thing that's inconsistent in version 12.1.0. When creating TableServiceClient or TableClient using a connection string "UseDevelopmentStorage=true" for local development, then an attempt to access AccountName throws the following exception:
> 
> System.ArgumentNullException
> HResult=0x80004003
> Message=Value cannot be null.
> Parameter name: uri
> Source=Azure.Data.Tables
> StackTrace:
> at Azure.Data.Tables.TableUriBuilder..ctor(Uri uri)
> at Azure.Data.Tables.TableClient.get_AccountName()
> 
> BlobServiceClient & QueueServiceClient return "devstoreaccount1".

This should be fixed in the latest version.

**Comment by christothes** [comment]
extracted a couple of distinct feature issues for the remaining requests still under consideration.

**Comment by christothes** [comment]
> @christothes what about TableClient.ExistsAsync(), is that on the horizon as well?

No - An Exists method is inherently racy. 
For example, what decision could accurately be made after getting the result of `Exists()`? No matter the result, there is no guarantee that the result is still accurate when your code does something after that. You are better off just trying to do whatever you would have done and letting it either fail or succeed.
