### ISSUE TITLE
Clarification for "redirect URL is pre-proposed"

### ISSUE THREAD

**Issue by sabuncu** [Azure/azure-sdk-for-net#19882]
Under the remarks section, it says:

The redirect URL is **pre-proposed** by the library. It does not need to be passed in the constructor

What's this mean?  Does it mean the redirect URL is set to a default value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bc4b80d8-15c7-2854-8123-5d0550989dd5
* Version Independent ID: 9eacf25f-2f23-268a-7a2a-b48ed5e9d498
* Content: [PublicClientApplication Class (Microsoft.Identity.Client) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.publicclientapplication?view=azure-dotnet)
* Content Source: [xml/Microsoft.Identity.Client/PublicClientApplication.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Client/PublicClientApplication.xml)
* Service: **active-directory**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
//cc: @nonik0, @anaismiller

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best members able to assist.

**Comment by nonik0** [comment]
@schaabs This looks specific to Azure.Identity, could you take a look?

**Comment by schaabs** [comment]
This is actually regarding the Microsoft.Idenitty.Client (MSAL) documentation. I'm not sure why the issue was created in this repo. MSAL is developed in this repo, https://github.com/AzureAD/microsoft-authentication-library-for-dotnet. 

@jsquire any ideas on how to properly route this issue so it links up property to the ms.docs feedback?

**Comment by sabuncu** [comment]
> 
> 
> I'm not sure why the issue was created in this repo. MSAL is developed in this repo, https://github.com/AzureAD/microsoft-authentication-library-for-dotnet.
> 
> @jsquire any ideas on how to properly route this issue so it links up property to the ms.docs feedback?

@schaabs Hi.  I created the issue here because the Feedback button at the bottom of the page directed me here.

**Comment by jsquire** [comment]
@schaabs:  Anything that is related to an Azure SDK for .NET gets forwarded to our repository by the docs system now.  In this case, we'll want to transfer over to the MSAL repository.    I'll take care of doing that.

**Comment by jsquire** [comment]
Closing this out; the issue has been transferred to the MSAL library.  [#2553](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2553)
