### ISSUE TITLE
NuGet Microsoft.Azure.Management.Resources confusion

### ISSUE THREAD

**Issue by stevef51** [Azure/azure-sdk-for-net#1988]
The docs at [https://msdn.microsoft.com/en-us/library/azure/mt418626.aspx] indicate that the constructor for _ResourceManagerClient_ [https://msdn.microsoft.com/en-us/library/azure/microsoft.azure.management.resources.resourcemanagementclient.aspx] can take a _SubscriptionCloudCredentials_ instance (which can be Token or Certificate based) - fine, I am using the _SqlManagementClient_ from _Microsoft.Azure.Management.Sql_ which has same constructor and I am able to connect using a _CertificateCloudCredentials_ instance and am wanting to list the Resource Groups in my subscription in order to create Sql databases (which requires a Resource Group)

However the link to NuGet [https://www.nuget.org/packages/Microsoft.Azure.Management.Resources/] shows to install the (now DEPRECATED) 

`Install-Package Microsoft.Azure.Management.Resources -Pre`

this package has the _ResourceManagerClient_ but has a different set of constructors none of which accept a _SubscriptionCloudCredentials_ instance.  Additionally the NuGet link to GitHub [https://github.com/Azure/azure-sdk-for-net] shows the source for the _ResourceManagerClient_ indeed uses the _SubscriptionCloudCredentials_.

On NuGet there are 3 Azure ResourceManager packages 
```

Microsoft.Azure.ResourceManager (3.0.0 preview on 2016-04-20 DEPRECATED)
Microsoft.Azure.Management.ResourceManager (1.1.1 preview on 20160-04-27)
Microsoft.Azure.Management.Resources (3.4.0 preview on 2016-02-06 DEPRECATED)

```
and none of them have a _ResourceManagerClient_ that takes the _SubscriptionCloudCredentials_ as indicated in the docs which is not surprising since they all use _Microsoft.Rest.ClientRuntime_ for their REST stuff whilst _Microsoft.Azure.Management.Sql_ uses _Microsoft.Azure.Common_ for REST connectivity.

So my issue is that both the docs and the GitHub source say the constructor should take _SubscriptionCloudCredentials_ yet the package(s) are obviously built from different source code since there is no such constructor available.

**Comment by hovsepm** [comment]
@stevef51 Sorry for the confusion. you should use https://www.nuget.org/packages/Microsoft.Azure.Management.Resources/2.20.0-preview. 
@vivsriaus, could you take a look to the documentation issues above?

**Comment by vivsriaus** [comment]
@stevef51 Apologize for the confusion as well. The correct ARM package to use is actually Microsoft.Azure.Management.ResourceManager (1.1.1 preview on 20160-04-27).

We're also trying to update the documentation to reflect this as we speak. You can use this [link](https://azure.microsoft.com/en-us/documentation/articles/resource-group-authenticate-service-principal/) as an example to create a auth token, which you can then use to instantiate the ResourceManagementClient.

**Comment by stevef51** [comment]
Thanks guys, much appreciated

**Comment by AlexGevorkyan** [comment]
Hi guys! I have read the previous posts and still have to write my question. 
In accordance with the article 
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-get-started-csharp 
I try to add the package Microsoft.Azure.Management.ResourceManager to my solution.

I used both variants to install it:
Install-Package Microsoft.Azure.Management.ResourceManager -Pre
and
Install-Package Microsoft.Azure.Management.Resources -Version 2.20.0-preview -Pre
They both failed with message:
"Install-Package : An error occurred while retrieving package metadata for 'Microsoft.Azure.Management.Sql.1.2.0-preview' ..."
I use VS2015.
Could you tell me what is wrong please.
