### ISSUE TITLE
Azure Iot DeviceUpdate Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#19895]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/Azure.IoT.DeviceUpdate_1.0.0-beta.2/sdk/deviceupdate/Azure.Iot.DeviceUpdate#azure-device-update-for-iot-hub-client-library-for-net):
![image](https://user-images.githubusercontent.com/65581162/112801688-c7bc2f80-90a3-11eb-8c88-7ad64889205b.png)
Suggestion: 

Update the link to https://github.com/Azure/azure-sdk-for-net/tree/Azure.IoT.DeviceUpdate_1.0.0-beta.2/sdk/deviceupdate/Azure.Iot.DeviceUpdate/src

2.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/Azure.IoT.DeviceUpdate_1.0.0-beta.2/sdk/deviceupdate/Azure.Iot.DeviceUpdate#examples):
![image](https://user-images.githubusercontent.com/65581162/112802138-65affa00-90a4-11eb-94b2-22d70e10c6fd.png)
Suggestion: 

Update the link to https://github.com/Azure/azure-sdk-for-net/tree/Azure.IoT.DeviceUpdate_1.0.0-beta.2/sdk/deviceupdate/Azure.Iot.DeviceUpdate/samples

3.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/Azure.IoT.DeviceUpdate_1.0.0-beta.2/sdk/deviceupdate/Azure.Iot.DeviceUpdate#next-steps):
![image](https://user-images.githubusercontent.com/65581162/112802578-ea027d00-90a4-11eb-8112-3201774a6862.png)
Suggestion: 

Update  the link to https://github.com/Azure/azure-sdk-for-net/tree/Azure.IoT.DeviceUpdate_1.0.0-beta.2/sdk/deviceupdate/Azure.Iot.DeviceUpdate/samples

4.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/Azure.IoT.DeviceUpdate_1.0.0-beta.2/sdk/deviceupdate/Azure.Iot.DeviceUpdate#contributing):
![image](https://user-images.githubusercontent.com/65581162/112802276-9001b780-90a4-11eb-9362-ee7761876b87.png)
Suggestion: 

1.Update ' [Microsoft Open Source Code of Conduct][code_of_conduct]' to '[Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/)'

2.Add hyperlink for `Code of Conduct FAQ`  https://opensource.microsoft.com/codeofconduct/faq/

@jongio for notification.

**Comment by v-xuto** [comment]
Close this issue, due to it has been fixed.
