### ISSUE TITLE
Azure Communication Chat Sample issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#19893]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/communication/Azure.Communication.Chat/tests/samples/Sample3_ParticipantOperations.cs#L36):
![image](https://user-images.githubusercontent.com/65581162/112802897-50879b00-90a5-11eb-8521-6f0ce3a2e14d.png)

Suggestion:  Update `DateTime `to `DateTimeOffset`

@jongio for notification.

**Comment by ashwinder** [comment]
Thanks for raising this issue. Our team will be looking into this shortly.

**Comment by juancamilor** [comment]
@Tianyun-G  I don't seem to be able to reproduce the error you have on the screenshot.  I guess you are running the tests locally, in that case, can you share your timezone / region settings so we can reproduce it before changing the sample code ?
Thanks !

**Comment by Tianyun-G** [comment]
@juancamilor Hi, this is our timezone.
![image](https://user-images.githubusercontent.com/65581162/114122588-2b0b5480-9923-11eb-8182-fcbf4b38e579.png)

**Comment by Tianyun-G** [comment]
PR fix and merged in https://github.com/Azure/azure-sdk-for-net/pull/20263 .
