### ISSUE TITLE
Future proof Tables expression parser

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#19901]
According to https://github.com/dotnet/runtime/issues/47231 , we may need to do some work to future proof our expression parser implementation in Tables. 

Although we do not implement IQueryable directly, we're still using reflection and comparing against argument count in a couple of places like [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/src/Queryable/ExpressionNormalizer.cs#L120) though.  Might be worth being more explicit or adding unit tests in case someone ever puts new overloads in .NET Core vNextNextNext.

**Comment by pallavit** [comment]
@christothes do you still see value in making this change?
