### ISSUE TITLE
Error obtaining access token

### ISSUE THREAD

**Issue by Contengo** [Azure/azure-sdk-for-net#19914]
I recently (in the last few weeks) started getting the following error in my development environment when trying to obtain an access token for Azure SQL using AzureServiceTokenProvider:

`Parameters: Connection String: RunAs=App;AppId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx, Resource: https://database.windows.net, Authority: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. A socket operation was attempted to an unreachable network. (169.254.169.254:80)`

The code is obtaining the access token is

`accessToken = await new AzureServiceTokenProvider($"RunAs=App;AppId={_appId}")
    .GetAccessTokenAsync("https://database.windows.net", _tenantId);`

This works perfectly well when I publish the application to an App Service - and previously worked in the development environment for many months (with or without the ASTP connection string). I've tried every troubleshooting suggestion I can find online for similar issues - but none work. Suggestions I've tried include:

1. Updating Visual Studio to the latest version.
2. Updating from .NET Core 3.1 to .NET 5
3. Updating all Nuget packages to the latest version.
4. Allowing all three methods of getting an access token to be tried (this was the original setup before the problems started).
5. Changing the configuration of Azure CLI to return JSON by default.

With option 4. the full error message becomes:

`Parameters: Connection String: [No connection string specified], Resource: https://database.windows.net, Authority: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. 

Exception Message: Tried the following 3 methods to get an access token, but none of them worked. Parameters: Connection String: [No connection string specified], Resource: https://database.windows.net, Authority: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. 

Exception Message: 
Tried to get token using Managed Service Identity. Access token could not be acquired. A socket operation was attempted to an unreachable network. (169.254.169.254:80) Parameters: Connection String: [No connection string specified], Resource: https://database.windows.net, Authority: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. 

Exception Message: 
Tried to get token using Visual Studio. Access token could not be acquired. Exception for Visual Studio token provider Microsoft.Asal.TokenService.exe :  Parameters: Connection String: [No connection string specified], Resource: https://database.windows.net, Authority: https://login.microsoftonline.com/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. 

Exception Message: 
Tried to get token using Azure CLI. Access token could not be acquired. Token response is not in the expected format. Exception Message: Expecting element 'root' from namespace ''.. Encountered 'None'  with name '', namespace ''.`

I don't believe it's a bug in my code or Azure configuration because - as I say - all works fine when published to an app service. Somewhat at my wit's end with this one: can anyone help?

**Comment by jsquire** [comment]
//cc: @nonik0, @anaismiller

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by anaismiller** [comment]
Managed Identities are not supported in local development environments and so using "`$"RunAs=App;AppId={_appId}"`" in the `Connection String` won't work locally. I'd recommend setting an environment variable for this. This [connection string table](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication#connection-string-support) can be helpful for you.

As for making option 4 work, can you try re-authenticating into AzureCLI or Visual Studio? It is possible your credentials need to be refreshed from in-active usage.

**Comment by Contengo** [comment]
Hi Anais,

Thanks for the message: the connection string table is very helpful.

I have tried re-authenticating AzureCLI and Visual Studio multiple times: it doesn’t seem to help. I have found something interesting though: the problem only seems to occur when the code containing the call to AzureServiceTokenProvider is in a different assembly from the main application (because I’m using a common shared library between several related applications). If I move all the code into the one assembly, the problem goes away. However it works fine with the separate assembly once published into an App Service – so perhaps the Visual Studio Authentication is thrown off by the fact that the call is from a shared library class?

Best regards,

Charles

**Comment by anaismiller** [comment]
Hmm, that is interesting; I have not seen this issue before.
When `AzureServiceTokenProvider` is called, it looks for an identity to use to get the tokens. Are you perhaps logged into multiple accounts and so in different assemblies, it picks up a different account? And this doesn't happen when running in the App Service as there is only one identity there to use.

**Comment by Contengo** [comment]
Hi Anais,

I am working with multiple accounts,  so that's definitely a possibility.

Best regards,

Charles

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by anaismiller** [comment]
Alright, then can you open the common shared library, authenticate with the account you want, then run your different assembly code and see if that fixed your issue?

**Comment by anaismiller** [comment]
@Contengo , do you have any updates to share?

**Comment by Contengo** [comment]
Hi,

Sorry,  had put this on hold for a while. Could you let me know the exact steps to follow to try your suggestion below? I wasn't exactly sure what you meant.

Thanks,

Charles

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anaismiller** [comment]
You mentioned that you have multiple accounts and the authentication flow is in a different project.

I am thinking what is happening is a different account without access is being used to get the token. So you have to try and get the right account to do the access. You can try using AzureCli and logging in to only that one account and signing out of your others or with VS, make sure that the tokens are only being requested from that one account and not any other.

**Comment by anaismiller** [comment]
@Contengo, may I close this issue? Have you resolved your issue?

**Comment by Contengo** [comment]
Hi Anais,

Apologies for not responding to this earlier: I am working on multiple projects and had to park this one for a while.

I see you have closed the ticket, but the problem is not solved. I have found a couple of interesting things about it – including a workaround (a bit clunky, but it at least means I can continue with development):


  1.  As I mentioned before, the problem only occurs when the code calling GetAccessTokenAsync is in a separate .dll file (shared library) from the application being debugged.
  2.  If I put a breakpoint on the line which makes that call, then use a Quick Watch window to manually evaluate “provider.GetAccessTokenAsync("https://database.windows.net", _tenantId).Result”, it successfully returns an access token and I can then remove the breakpoint and continue for the rest of that debugging session.
  3.  If, however, I re-start the application the problem returns unless I do the same thing again.

The fact that the problem does not arise in the Quick Watch window, but does if I try to let the code run through without a breakpoint, indicates to me that there must be an underlying bug in this part of the system when running in an environment with multiple Microsoft IDs registered.  The behaviour of the Quick Watch window should surely be the same?

There is another problem with the Visual Studio handling of multiple Microsoft accounts that might be related to the above, but I’ve tried to eliminate it as a factor: in the customer domain I’m working with there is a main Active Directory tenancy, plus there is also a B2C tenancy that I created a while back but am not using. I can no longer access the B2C tenancy because I changed phones and did not re-register the B2C account on Authenticator on my new phone (but it seems I am the only administrator so can’t delete it).

I was struggling for a while to understand why, when I try to “Refresh Credentials” for the account I have on this domain it claims to have sent an authentication request to my Microsoft Authenticator app, but none appears in the app and I can’t log in. I’ve realised it’s almost certainly because, when I try to add the account in Visual Studio I am not asked for a specific Azure tenancy, only a username and password, and I strongly suspect that Visual Studio is defaulting to the B2C version of the identity which I can no longer access.

I have put in a support request to delete this unwanted B2C directory, which will hopefully mean that I can have two Microsoft Identities in Visual Studio without problems – I will let you know if that makes any difference to the problem above.

In general the underlying problem here is that the system is always trying to guess which tenancy I’m trying to use and getting it wrong – I would far rather we have the ability to specifically set which one we’re working with – either within Options or by prompting me  when I run. Users of Visual Studio are software developers – we are generally technical enough to be able to pick the right tenancy if asked – this whole “School or Work Account” thing is too dumbed down – not least because it doesn’t actually work.

Best regards,

Charles


***@***.***D744CC.93B0E5A0]<https://contengo.net/>
   ***@***.***D744CC.93B0E5A0] <https://www.linkedin.com/in/charlessouthey/>     ***@***.***D744CC.93B0E5A0] <https://www.facebook.com/contengo.net>     ***@***.***D744CC.93B0E5A0] <https://twitter.com/ContengoLtd>
