### ISSUE TITLE
[BUG] Fail to copy public url to block blob

### ISSUE THREAD

**Issue by LinY-90** [Azure/azure-sdk-for-net#19945]
**Describe the bug**
We used the function **BlobBaseClient.SyncCopyFromUriAsync** to copy a public url to a block blob. It was working fine before, but it failed when I ran the unit test today. It is strange that the copy status is success, but the size of the blob is 0.  The copyId is 7e6337ea-c904-4aa8-906a-78010dac8c31. Some screen shots are as follow:
**The response of source url:**
![image](https://user-images.githubusercontent.com/74641470/113013754-8d8b8480-91ae-11eb-861b-8d18cc877815.png)
**Copy Status:**
![image](https://user-images.githubusercontent.com/74641470/113015024-b5c7b300-91af-11eb-9ef7-7f8fd8f0a947.png)
**The properties of target blob:**
![image](https://user-images.githubusercontent.com/74641470/113015393-15be5980-91b0-11eb-8cde-6a8728955256.png)
**The response of target blob:**
![image](https://user-images.githubusercontent.com/74641470/113015352-0a6b2e00-91b0-11eb-9033-2549f6362b78.png)

**Expected behavior**
Succeed to copy the public url to the block blob

**Actual behavior (include Exception or Stack Trace)**
Fail to copy the thumbnail, but the copy status is success.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Use the function BlobBaseClient.SyncCopyFromUriAsync to copy the url to a block blob

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.7.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Microsoft.NETCore.App 3.1.13
 - IDE and version : Visual Studio 16.9.1

**Comment by seanmcc-msft** [comment]
Hi.  Are you sure your source URL is valid, and is authorize to access the resource?

**Comment by LinY-90** [comment]
> Hi. Are you sure your source URL is valid, and is authorize to access the resource?

Of course. I am sure that the url is valid, and it can be accessed anonymously.

**Comment by LinY-90** [comment]
> This sounds like an intermittent issue with the service than an SDK issue since you said it was working fine before and it failed in the instance you ran the unit test.
> 
> This would be a difficult thing for us to reproduce since this isn't tied to a version of the SDK you upgraded to or anything. I would open an incident issue with the storage service and provide them the information to this copy request you sent.
> https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

I think you are right. It seems that this is indeed a service issue. Thanks for you help.
