### ISSUE TITLE
[FEATURE REQ] bring the useful utilities from Fluent SDK

### ISSUE THREAD

**Issue by cfauchere** [Azure/azure-sdk-for-net#19957]
The fluent SDK has a few very useful utility classes.
for name generation [SdkContext](https://github.com/Azure/azure-libraries-for-net/blob/fcc1e5b00376634dc8f675e655bffc76c1cf0e20/src/ResourceManagement/ResourceManager/SdkContext.cs)
for id generation (testing) [ResourceUtils](https://github.com/Azure/azure-libraries-for-net/blob/fcc1e5b00376634dc8f675e655bffc76c1cf0e20/src/ResourceManagement/ResourceManager/Core/ResourceUtils.cs)
for id parsing [ResourceId](https://github.com/Azure/azure-libraries-for-net/blob/fcc1e5b00376634dc8f675e655bffc76c1cf0e20/src/ResourceManagement/ResourceManager/Core/ResourceId.cs)
It would be great to have such utilities in the new SDK.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by markcowl** [comment]
@nickzhums Can you help with the priority for this ask?  DO we have data on the usage of these utilities?

**Comment by nickzhums** [comment]
We don't have data on individual SDK object / model usage, but this might be something we can consult with Java Fluent team

**Comment by nickzhums** [comment]
@markcowl  @m-nash given the current track 1 impl, i think this is probably after Public Preview but before GA scope

**Comment by ArthurMa1978** [comment]
This is in our radar that will build convenient layer upon Track 2 sdk
