### ISSUE TITLE
Parse default Azure error format and extract message, error code and additional properties

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#19987]
We should also consider extracting inner errors.

Spec:

https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses

Remove existing implementations:

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/keyvault/Azure.Security.KeyVault.Shared/src/ClientDiagnostics.cs
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ClientDiagnostics.cs
​https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/textanalytics/Azure.AI.TextAnalytics/src/ClientDiagnostics.cs

**Comment by allenjzhang** [comment]
With this work item, we can have opportunities for full support for ARM exceptions without having to create a separate ArmException. This will help create consistent result from data plane and mgmt plane code. The [ARM exception](https://github.com/Azure/azure-rest-api-specs/blob/0461eb89cb81ff7c883f80481601d8da09249f42/specification/common-types/resource-management/v2/types.json#L313) pretty much fit the error response laid out in the spec above.

We looked at ArmException class and the mapping of the fields into a standard Exception:

* Suggested Mapping. Please note. Details are deserialized into Exception trees and set on InnnerException via a AggregatedException.

Exception Class | RequestFailedException | ArmException | REST ARM ErrorResponse
-- | -- | -- | --
Message |   |   | Message
Source |   | Target | Target
InnerException |   | Details | Details
Data |   | Store in data dictionary and expose via AdditionaInfo (Client_ReqId, ReqId Request, Response ?) Any additional custom exception data | AdditionalInfo
StackTrace |   |   |  
... | Status (http) |   |  
  | Code |   | Code
  |   |   |  

* Allow user access to response headers for things like CorrelationId, ClientRequest-Id etc. While having few special ones as first class properties, we are ok with access via a ResponseHeader property.

**Comment by pakrym** [comment]
These are the formats I found in recordings:
```
 1215   {"code":"","message":""}
 48     {"code":"","message":"","innererror":{"code":"","message":""}}
 22     {"code":"","innerError":{"requestId":""},"message":""}
 14     {"code":"","message":"","details":[{"code":"","message":""}]}
 12     {"message":"","code":"","correlationId":"","innererror":{"code":"","message":""}}
 11     {"code":null,"innererror":null,"message":null}
 10     {"code":"","message":"","innerError":{"code":""}}
 8      {"code":"","message":"","target":"","innerError":{"code":"","message":""}}
 8      {"code":null,"message":null,"innererror":null}
 4      {"code":"","message":"","target":"","innerError":{"parseErrorDetails":[{"pos":[6,6],"line":"","col":"","msg":"","code":"","target":""}],"code":""}}
 4      {"code":"","message":"","target":""}
 3      {"description":"","readOnly":"","$ref":""}
 2      {"code":"","message":"","details":null,"target":null,"innerError":null}
 2      {"errorCode":"","message":"","failureType":"","target":""}
 2      {"occurredDateTime":"","code":"","message":"","innerError":{"code":"","message":"","errorDetail":""}}
 2      {"code":"","message":"","innererror":{"code":""}}
 2      {"code":"","message":"","additionalInfo":[{"type":"","info":{"lineNumber":"","linePosition":"","path":""}}]}

```
