### ISSUE TITLE
ConnectionStrings support in CloudConfigurationManager

### ISSUE THREAD

**Issue by cannehag** [Azure/azure-sdk-for-net#2001]
We are using CloudConfigurationManager in our webjobs to access the hosting sites app settings. Is there any reason why the connectionstrings settings is not exposed in CloudConfigurationManager?

**Comment by markcowl** [comment]
This is outside the scope of cloud configuration manager.  Please see the azure websites documentation for information on hpw to access application settings.

**Comment by cannehag** [comment]
I don't really agree on the answer. Connectionstrings and AppSettings are the same kind of configuration that you would expect to be accessible via the CloudConfigurationManager class. I know how to access them, but I would rather see the same approach for them.
Why are they outside the scope ?

**Comment by cannehag** [comment]
@markcowl Any update on my last reply ?

**Comment by cannehag** [comment]
@markcowl ?
