### ISSUE TITLE
[FormRecognizer] Get multipage ID Document test files

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#20019]
The service skips Document Results whose pages have no ID document fields. For this reason, if we try to use the multipage invoices we have, we'll get an empty list of forms back, which makes it impossible for us to test it. We should get proper testing files for the multipage Document ID scenarios.

Tests to be added:
- `StartRecognizeIdDocumentsCanParseMultipageForm`
- `StartRecognizeIdDocumentsWithOnePageArgument`
- `StartRecognizeIdDocumentsWithMultiplePageArgument`
- Consider adding `StartRecognizeIdDocumentsCanParseMultipageFormWithBlankPage` given the different way it handles blank pages.

**Comment by maririos** [comment]
I think I saw Java adding some tests for multiple pages. I wonder if they added a new file.
@samvaity

**Comment by kinelski** [comment]
Today we have no good reason to include tests for this particular scenario, specially because it feels more like a service test than an SDK test. The other unit tests for multipage files already give us coverage on this area. Closing this.
