### ISSUE TITLE
[QUERY] Which Service Bus client?

### ISSUE THREAD

**Issue by ishepherd** [Azure/azure-sdk-for-net#20023]
**Query/Question**

I see this repo hosts:
* https://github.com/Azure/azure-sdk-for-net/tree/Microsoft.Azure.ServiceBus_5.1.2/sdk/servicebus/Microsoft.Azure.ServiceBus
* https://github.com/Azure/azure-sdk-for-net/tree/Azure.Messaging.ServiceBus_7.1.1/sdk/servicebus/Azure.Messaging.ServiceBus

Both are recent releases.

Can you put a guidance in the README to say which one is current or how to decide?

The Azure.Messaging one was released a month later and it has a higher version so I'm just gonna guess I should use this one.

**Comment by jsquire** [comment]
For new development, we would recommend using the `Azure.Messaging.ServiceBus` package and the `Azure.[[ AREA ]].[[ SERVICE ]]` packages for other services.   The `Microsoft.Azure.ServiceBus` package will continue to be supported with receive bug fixes and critical updates for the foreseeable future.  There is no a definitive date for end-of-life, but it's safe to say that the timeline is most likely measured in years.  That said, at some point in the near future, it will stop receiving new features and enhancements.  

More information on the benefits and differences between the libraries can be found in the [Service Bus Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md#migration-benefits).   Once `Azure.Messaging.ServiceBus` has reached full feature parity, you'll start to see guidance in the legacy package documentation advising migrating.
