### ISSUE TITLE
[FEATURE REQ] Add support for Managed Identity regional AAD authentication endpoints Azure.Identity

### ISSUE THREAD

**Issue by ctstone** [Azure/azure-sdk-for-net#20027]
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
The [guidance] from the Azure IAM wiki for service teams using MI is to authenticate using a regional endpoint (e.g. `https://eastus2euap.login.microsoft.com`). However, the MSAL example given in the wiki uses APIs that are not currently exposed/used by [MsalConfidentialClient], namely `WithAuthority(Uri, bool)` and `WithInstanceDicoveryMetadata(string)`.

Today, when using the regional AAD endpoint with Azure.Identity (using a [ClientCertificateCredential]), we see an error `Application error - the login request was malformed and could not be matched with an existing authentication endpoint or instance.` The error goes away when using a global endpoint (`https://login.microsoftonline.com/`). 

It would be good see guidance on using the regional authentication endpoint with Azure.Identity.

[guidance]: https://armwiki.azurewebsites.net/authorization/managed_identities/MSIOnboardingRequestingAToken.html#aad-regional-endpoint-with-msal
[MsalConfidentialClient]: https://github.com/Azure/azure-sdk-for-net/blob/5dc46af51b953d2b95959a41cefd886f7236e22f/sdk/identity/Azure.Identity/src/MsalConfidentialClient.cs#L40
[ClientCertificateCredential]: https://docs.microsoft.com/en-us/dotnet/api/azure.identity.clientcertificatecredential?view=azure-dotnet

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
