### ISSUE TITLE
[BUG][Synapse] - PipelineRunClient fails to create pipeline run with parameters 

### ISSUE THREAD

**Issue by idear1203** [Azure/azure-sdk-for-net#20051]
**Describe the bug**
Please provide the description of issue you're seeing.

`CreatePipelineRunAsync` has an optional argument named “parameters”. It is in type of Dictionary<string, object>. When calling the method with “parameters” specified, the “parameters” will be used in the request body. However, currently the real HTTP request body is not consistent with the value of “parameters”.
 
With some debugging, I find the root cause is that the SDK doesn’t deserialize the type “Dictionary<string, object>” properly. Please see gist here for the test code. In this case, we have “parameters” as below:
string parameterAsJson = @"{""TablesToMove"": [{""TableName"":""TestTable""}]}";
 
However, the HTTP request body is as below:
{"TablesToMove":[[[[]]]]}

I suspect this is a underlying serialization issue of track 2 SDK.

**Expected behavior**
What is the expected behavior?
The request body should be consistent with the input: {"TablesToMove": [{"TableName"":"TestTable"}]}

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Currently the request body is: {"TablesToMove":[[[[]]]]}

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Copy the following code snippet to [PipelineRunClientLiveTests.cs](https://github.com/Azure/azure-sdk-for-net/blob/6c04751c96929ff444028182f7ced31c219b44a1/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/PipelineRunClientLiveTests.cs)
    ``` c#
        [RecordedTest]
        public async Task TestRunWithParameter()
        {
            PipelineClient pipelineClient = CreatePipelineClient();
            PipelineRunClient runClient = CreatePipelineRunClient();

            await using DisposablePipeline pipeline = await DisposablePipeline.Create (pipelineClient, this.Recording);

            string parameterAsJson = @"{""TablesToMove"": [{""TableName"":""TestTable""}]}";
            var parameters = ReadParametersFromJson(parameterAsJson);
            CreateRunResponse runResponse = await pipelineClient.CreatePipelineRunAsync (pipeline.Name, parameters: parameters);
            Assert.NotNull(runResponse.RunId);
        }

        private Dictionary<string, object> ReadParametersFromJson(string rawJsonContent)
        {
            var parameters = new Dictionary<string, object>();
            if (!string.IsNullOrWhiteSpace(rawJsonContent))
            {
                parameters = JsonConvert.DeserializeObject<Dictionary<string, object>>(rawJsonContent);
            }

            return parameters;
        }
    ```
2. Remove the `Ignore` annotation on the top of the test file [here](https://github.com/Azure/azure-sdk-for-net/blob/6c04751c96929ff444028182f7ced31c219b44a1/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/PipelineRunClientLiveTests.cs#L22)
3. Execute the test case in record mode

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] Azure.Analytics.Synapse.Artifacts 1.0.0-preview.7 (latest master branch)
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
    ```
    .NET SDK (reflecting any global.json):
     Version:   5.0.201
     Commit:    a09bd5c86c
    
    Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.19042
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\5.0.201\
    
    Host (useful for support):
      Version: 5.0.4
      Commit:  f27d337295
    
    .NET SDKs installed:
      3.1.407 [C:\Program Files\dotnet\sdk]
      5.0.104 [C:\Program Files\dotnet\sdk]
      5.0.201 [C:\Program Files\dotnet\sdk]
    
    .NET runtimes installed:
      Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
      Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
      Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
      Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    ```
 - IDE and version : [e.g. Visual Studio 16.3] Microsoft Visual Studio Enterprise 2019 Version 16.9.2

**Comment by idear1203** [comment]
I also meet issues when using System.Text.Json. See the code below.

```c#
        [RecordedTest]
        public async Task TestRunWithParameter()
        {
            PipelineClient pipelineClient = CreatePipelineClient();
            PipelineRunClient runClient = CreatePipelineRunClient();

            await using DisposablePipeline pipeline = await DisposablePipeline.Create (pipelineClient, this.Recording);

            string parameterAsJson = @"{""TablesToMove"": [{""TableName"":""TestTable""}]}";
            Dictionary<string, object> parameters = ReadParametersFromJson(parameterAsJson);
            CreateRunResponse runResponse = await pipelineClient.CreatePipelineRunAsync (pipeline.Name, parameters: parameters);
            Assert.NotNull(runResponse.RunId);
        }

        private Dictionary<string, object> ReadParametersFromJson(string rawJsonContent)
        {
            var parameters = new Dictionary<string, object>();
            if (!string.IsNullOrWhiteSpace(rawJsonContent))
            {
                parameters = JsonSerializer.Deserialize<Dictionary<string, object>>(rawJsonContent);
            }

            return parameters;
        }

```

**Comment by chamons** [comment]
I tried running this and run into permission issues:

`    {"code":"ClientIpAddressNotAuthorized","message":"Client Ip address : MY_IP"}`

I then tried to access Synapse Studio and ran into more permissions issues, which are described in an internal e-mail.

**Comment by idear1203** [comment]
The issue is related to firewall rule. You can add the firewall rule on the Azure portal (see the snapshot below, you can find your client IP address on that page). 
 
![image](https://user-images.githubusercontent.com/7024383/115097686-5105aa00-9f5e-11eb-8d7a-29a21d6c739c.png)


Alternatively, you can use the one of the following PowerShell commands:

``` powershell
# Option 1: To allow all IPs to access the workspace
New-AzSynapseFirewallRule -WorkspaceName $workspaceName -AllowAllIp
```

``` powershell
# Option 2: To allow some specific IP
$ruleName = '<your rule name>'
$clientIpAddress = '<your public ip address>' # One way to get this is: $clientIpAddress = Invoke-RestMethod -uri https://api.ipify.org
New-AzSynapseFirewallRule -WorkspaceName $workspaceName -StartIpAddress $clientIpAddress -EndIpAddress $clientIpAddress -Name $ruleName 
```

**Comment by chamons** [comment]
This will be fixed with https://github.com/Azure/autorest.csharp/pull/1204

**Comment by chamons** [comment]
Reopening until this lands in azure-sdk-for-net.
