### ISSUE TITLE
How can i get list of Virtual machine image

### ISSUE THREAD

**Issue by mehulbhalala** [Azure/azure-sdk-for-net#2005]
how can i get list of virtual machine image like same as portal

[
![4](https://cloud.githubusercontent.com/assets/14832554/15353714/ed91a47a-1d07-11e6-90bf-95e0663352c9.png)
](url)

**Comment by markcowl** [comment]
@singhkay interested to hear the response

**Comment by JasonRShaver** [comment]
Clarifying question.  The image shown as an example are Gallery items if I am not mistaken, which I believe do more than VM Images do.  Is the goal to get the VM Images or Gallery items?

**Comment by devigned** [comment]
@JasonRShaver, yes.

**Comment by kamaljit** [comment]
Yes, programmatically getting a list of VM images in the gallery will be a good feature.

**Comment by singhkay** [comment]
@mehulbhalala If you're looking for .NET SDK methods, look into the cmdlet source code https://github.com/Azure/azure-powershell/tree/dev/src/ResourceManager/Compute/Commands.Compute/Images

Here's how you use these PS cmdlets to find the images https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-cli-ps-findimage/#powershell
