### ISSUE TITLE
Fix issues with InitialOffsetOptions

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#20054]
The example timestamp might need to be modified to reflect the format used in tests: yyyy-MM-dd HH:mm:ssZ

_Originally posted by @sidkri in https://github.com/Azure/azure-sdk-for-net/pull/19700#discussion_r603602887_

**Comment by pakrym** [comment]
Do we still support the originally documented format?

**Comment by JoshLove-msft** [comment]
> Do we still support the originally documented format?

Yes, we should. I updated the test to make it easier to round-trip, but I will add back a test with the original format.

**Comment by JoshLove-msft** [comment]
We already have a test with the original format - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubConfigurationTests.cs#L132
