### ISSUE TITLE
Please document how to grab the computed ETag after updating the twin

### ISSUE THREAD

**Issue by uriel-kluk** [Azure/azure-sdk-for-net#20060]
[Enter feedback here]
The **UpdateDigitalTwinAsync** returns an HTTP Response<T> object, but it is not clear how to grab the computed ETag.
The workaround is to do a new Read, but the extra trip is undesirable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be700a53-abbf-f28d-671e-2eaa058a8ef0
* Version Independent ID: f89f1c40-3007-1bd8-2e98-d7c8c2f75d9e
* Content: [DigitalTwinsClient.UpdateDigitalTwinAsync(String, JsonPatchDocument, Nullable&lt;ETag&gt;, CancellationToken) Method (Azure.DigitalTwins.Core) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.digitaltwins.core.digitaltwinsclient.updatedigitaltwinasync?view=azure-dotnet)
* Content Source: [xml/Azure.DigitalTwins.Core/DigitalTwinsClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.DigitalTwins.Core/DigitalTwinsClient.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by timtay-microsoft** [comment]
Hi @uriel-kluk you do not need to do a GetDigitalTwin after UpdateDigitalTwin in order to get the ETag. Within the Http headers of the Response object that UpdateDigitalTwin returns should be the new ETag for your digital twin after the update

**Comment by timtay-microsoft** [comment]
[From the swagger](https://github.com/Azure/azure-rest-api-specs/blob/1e2c9f3ec93078da8078389941531359e274f32a/specification/digitaltwins/data-plane/Microsoft.DigitalTwins/stable/2020-10-31/digitaltwins.json#L505), you can see that this ETag is returned for you:

```json
"responses": {
  "204": {
    "description": "Success",
    "headers": {
      "ETag": {
	    "description": "Weak Etag.",
	    "type": "string"
      }
    }
  }
}
```
```
