### ISSUE TITLE
[BUG] ListRegionalByResourceGroupWithHttpMessagesAsync() does not return expected fields.

### ISSUE THREAD

**Issue by brennfoster** [Azure/azure-sdk-for-net#20074]
**Describe the bug**
When calling ListRegionalByResourceGroupWithHttpMessagesAsync using the EventGridManagementClient found in the  Microsoft.Azure.Management.EventGrid SDK, certain fields are not being populated.

**Expected behavior**
I expect that all fields for the Event Grid Event Subscription are returned when fetching a list. When I query for a single Event Grid Event Subscription, I do see all the fields being populated.

**Actual behavior (include Exception or Stack Trace)**
Certain fields are not being populated. They are:
DeadLetterDestination,
Filter.IncludedEventTypes

There may be more missing that I haven't noticed.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Initialize EventGridManagementClient.
2. Call EventGridManagementClient.EventSubscriptions.ListRegionalByResourceGroupWithHttpMessagesAsync().

**Environment:**
 - Microsoft.Azure.Management.EventGrid 6.0.0
 - Azure Appservice, .NET 5
 - IDE and version : Visual Studio 16.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by brennfoster** [comment]
My apologies, the reason I wasn't seeing those fields is because one of the Event Subscriptions I am querying was not setup with Event Type filters or a DeadLetter container. I will close this out.
