### ISSUE TITLE
3014: Generic error during prediction - Azure Form Recognizer

### ISSUE THREAD

**Issue by rajurh** [Azure/azure-sdk-for-net#20081]
Hi team,

I am trying to call custom trained Azure Form recognizer with Azure SDK .NET and I am getting the error "3014: Generic error during prediction." The error message doesn't look to be timeout it's spontaneous as part of WaitForCompletionAsync. Below is the sample code snippet. I can see model id and URI is having the correct value. For the same model id if I try using Postman rest API not the sdk then it works but not with SDK client.

**Note: I have old model which works with same code but newly trained model which has custom fields tagged + table tagging causing issue**

Code snippet
![image](https://user-images.githubusercontent.com/15551296/113460268-8eedd300-9474-11eb-95b7-45d93f5dfea2.png)

Nuget versions
![image](https://user-images.githubusercontent.com/15551296/113460163-3b7b8500-9474-11eb-88ad-e40bc23c632e.png)

Trained model version
![image](https://user-images.githubusercontent.com/15551296/113460311-c9577000-9474-11eb-899c-26a5a330c01d.png)

**Expected behavior**
Provide Json results from the API call

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
![image](https://user-images.githubusercontent.com/15551296/113460099-0cfdaa00-9474-11eb-9abf-ce4c3372aac2.png)

**Environment:**
I am trying to invoke using Azure Function.
![image](https://user-images.githubusercontent.com/15551296/113460321-da07e600-9474-11eb-956f-24174379e5bf.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by tchekjunior** [comment]
I have had the same problem for several days.
I think is target version sdk and trained model no matching.
If you use v2.1-preview.2 version of OCR Form Tools you can target sdk 3.1.0-beta.3 or waiting next beta release like me.

**Comment by thomas-gregg-bz-agency** [comment]
I have the same issue as well. Would prefer not to have to go back to preview.2 as the new table feature is great. Any expectations when the targeted version will change?

**Comment by maririos** [comment]
@tchekjunior is right. Version mismatch is probably the culprit. 
We actually released today the new version of the SDK `3.1.0-beta.4` that targets the service version `preview.3`. You can download it now from [NuGet](https://www.nuget.org/packages/Azure.AI.FormRecognizer/3.1.0-beta.4).

Give it a try and let us know if the problem is fixed

**Comment by thomas-gregg-bz-agency** [comment]
@maririos For me this has resolved the above issue. Thanks.

**Comment by rajurh** [comment]
@maririos Thanks issue is resolved

**Comment by tchekjunior** [comment]
Cool, so thanks, is work for me
