### ISSUE TITLE
[QUERY] Is it possible to set LastModified property from BlobContainerProperties?

### ISSUE THREAD

**Issue by WillRock19** [Azure/azure-sdk-for-net#20091]
**Query/Question**

I want to unit test a logic in my code. The logic gets a BlobContainerClient from the storage, get all blobs from it, and then filter the blobs for those who **last modified date** is before last week and delete those. I have somethind as the following:

```csharp
                var blobContainerClient = storageWrapper.GetContainerReference(_connectionString, containerName); //returns a BlobContainerClient
                var dateLastWeek = DateTime.Now.AddDays(-7);

                var desiredBlobs = blobContainerClient
                    .GetBlobs()
                    .ToList()
                    .Where(x => x.Properties.LastModified < dateLastWeek)
                    .ToList();
```

But then I realized that the BlobContainerProperties.LastModified is a get only property, and non virtual (so I can't mock it's return). 

![image](https://user-images.githubusercontent.com/6953687/113581224-3bf35780-95fd-11eb-90fa-d5094ab59a5f.png)

Is there a way to create one of these objects with the LastModified date so I can use it in my test logic?

**Environment:**
- .Net Version: Full Framework 4.8
- New version: Azure.Storage.Blobs v12.8.0
- IDE and version : Visual Studio 16.8.5

**Comment by seanmcc-msft** [comment]
Hi @WillRock19,

To create a `BlobContainerProperties` for testing purposes, I recommend using [BlobsModelFactory.BlobContainerProperties()](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Models/BlobsModelFactory.cs#L875)

You can then create a mock `BlobContainerClient`, and set it up to return the `BlobContainerProperties` in question.  `BlobContainerClient.GetProperties()` and `BlobContainerClient.GetPropertiesAsync()` are virtual.

-Sean

**Comment by WillRock19** [comment]
Hi  @seankane-msft, thanks for the feedback!

Just a question: there's a way to set the **Properties** property from **BlobItem**? 

As I can see, I've made a mistake in the description of my problem; I need to set the **Properties** from **BlobItem**, that is what the **GetBlobs** returns to me.

![image](https://user-images.githubusercontent.com/6953687/113617737-18480580-962d-11eb-9cb7-8c5ef4c33cef.png)

![image](https://user-images.githubusercontent.com/6953687/113617767-23029a80-962d-11eb-83ca-d60f1bcae699.png)

I can still use the factory you sugested (need the BlobsModelFactory.BlobItemProperties()), but don't know how to set the BlobItemProperties inside the class **BlobItem**. Can you help me, please?

as I can tell, the way you sugested whould set the container LastModified date, no? Since my logic is depending on the blob LastModified property (i'm going to delete the blobs that are in a specific range), using the BlobsModelFactory.BlobContainerProperties() whould set de property in the blob?

**Comment by seanmcc-msft** [comment]
You can create a `BlobItemProperties` for testing with [BlobsModelFactory.BlobItem()](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Models/BlobsModelFactory.cs#L1043).  You can create the `BlobItemProperties` with [BlobsModelFactory.BlobItemProperties()](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/Models/BlobsModelFactory.cs#L482).

**Comment by WillRock19** [comment]
Hi @seanmcc-msft , thanks for the feedback!

I've ran into another question, still in this scope of testing> I have to test the return of the GetBlobs method, that returns an Pageable<BlobItem> as you can see bellow:

![image](https://user-images.githubusercontent.com/6953687/113619577-88f02180-962f-11eb-8f86-5788f2246cf7.png)

I've looked into the **BlobsModelFactory** and I can create a BlobItem there, but I'm not managing to create the Pageable to use in my mocks. 

As I could see this github, the Pageable<BlobItem> it is create throught the **StorageAsyncPageable** class, and that's a private class (bellow, the breadcrumb I've followed to get into this conclusion). Is there another way to create a Pageable that I can use to create my mocks?

![image](https://user-images.githubusercontent.com/6953687/113619711-b63ccf80-962f-11eb-8fad-41b36d41f822.png)

![image](https://user-images.githubusercontent.com/6953687/113619800-cfde1700-962f-11eb-8a00-dd0d45633a0b.png)

![image](https://user-images.githubusercontent.com/6953687/113619882-eedca900-962f-11eb-9a14-d736f6e19db9.png)

Thanks again!

**Comment by seanmcc-msft** [comment]
You can use [Azure.Core.PageResponseEnumerator](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/PageResponseEnumerator.cs).  An example of this is here - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs.ChangeFeed/tests/ChangeFeedTests.cs#L73

**Comment by WillRock19** [comment]
@seankane-msft thanks for the answers! I'm sorry to say I've tried to remove the question from this topic and created a new one, so it could be easily found by people that may strougle with the same issue. I'm not able to delete the other topic (here it is: https://github.com/Azure/azure-sdk-for-net/issues/20124), and I'm sorry about the confusion.

**Comment by WillRock19** [comment]
@seanmcc-msft, I've tried your sugestion, but the  Azure.Core.PageResponseEnumerator is internal. Is that right?

**Comment by seanmcc-msft** [comment]
@tg-msft

**Comment by tg-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Mocking.md#creating-a-mock-of-the-method-that-returns-pageable has an example of mocking `Pageable<T>`.

**Comment by WillRock19** [comment]
It worked! Thank you very much :)
