### ISSUE TITLE
[QUERY] Is it possible to delete a Blob through a BlobItem?

### ISSUE THREAD

**Issue by WillRock19** [Azure/azure-sdk-for-net#20092]
**Query/Question**
I'm converting a logic from an old library to a new one. In here, I'm getting all blobs from a container, filtering it by the LastModified property, and then deleting it. With the old library, I could do this in a very straight foward manner:

```csharp
        var storageConnectionString = ConfigurationManager.ConnectionStrings["AzureWebJobsStorage"].ConnectionString;
        CloudStorageAccount storageAccount = CloudStorageAccount.Parse(storageConnectionString);
	CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();

	var containerHostArchive = blobClient.GetContainerReference("azure-jobs-host-archive");
	if (containerHostArchive.Exists())
	{
		var blobsHostArchive = containerHostArchive
			.ListBlobs()
			.OfType<CloudBlob>()
			.Where(b => b.Properties.LastModified < new DateTimeOffset(DateTime.Now.AddDays(-RETENTION_DAYS_JOBS_LOGS)))
			.ToList();

		foreach (var item in blobsHostArchive)
		{
			item.DeleteIfExists();
		}
	}
```

In the new library, I'm not finding a easy way to do this. I have to make two access to the storage, first one to find the BlobItems from a container, the second to get a reference to the BlobClient so I can delete it (see bellow):}

```csharp
                var blobContainerClient = storageWrapper.GetContainerReference(_connectionString, containerName); //Returns a BlobContainerClient
                var dateLastWeek = DateTime.Now.AddDays(-7);

                var desiredBlobs = blobContainerClient
                    .GetBlobs()
                    .ToList()
                    .Where(x => x.Properties.LastModified < dateLastWeek)
                    .ToList();

                var blobsToDelete = desiredBlobs
                    .Select(blob => storageWrapper.GetBlobReferenceNew(_connectionString, containerName, blob.Name)) //GetReferenceNew returns a BlobClient
                    .ToList();

                blobsToDelete.ForEach(blob => blob.DeleteIfExists());
```

Is there a way to do this without accessing the storage twice?

**Environment:**

- .Net Version: Full Framework 4.8
- Original version: Microsoft.WindowsAzure.Storage.Blob 9.3.2.0
- New version: Azure.Storage.Blobs v12.8.0
- IDE and version : Visual Studio 16.8.5

**Comment by seanmcc-msft** [comment]
This functionality is not supported by the SDK.  `BlobItem` is a model, `BlobClient` is a client.  This is a well established pattern in the new SDKs across Azure.

>  I have to make two access to the storage, first one to find the BlobItems from a container, the second to get a reference to the BlobClient so I can delete it

Getting a refence to a `BlobClient` doesn't actually make a REST call into the service, it just creates a new `BlobClient` locally.  Same for newing up a `BlobContainerClient`

No matter what the SDK APIs look like, there is going to be a call into the storage service to [list the blobs in a container](https://docs.microsoft.com/en-us/rest/api/storageservices/list-blobs), and [another call for each blob you would like to delete](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-blob).

-Sean
