### ISSUE TITLE
Service Bus: Performance Tests

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#20100]
# Summary

In order to ensure consistent performance, avoid regressions release-to-release, and measure across generations of the SDK the Service Bus family of packages will each need a set of performance tests that can be run.  These tests will make use of the central performance framework, allowing them to be automated to run on a consistent schedule and trends reported on.

# Scope of Work

- Create the skeleton needed for an Service Bus performance project, using the central performance framework and integrating the testing resources from the Service Bus tests for resource scaffolding and environment infrastructure.

- Identify the scenarios for `Azure.Messaging.ServiceBus` that can reasonably be worked into the performance framework in its current form.  These are believed to be:
  - Publishing in all forms
  - Reading messages via the receiver types

- Mirror the tests for `Azure.Messaging.ServiceBus`, implement the scenarios that map cleanly to the `Microsoft.Azure.ServiceBus` API surface

- Attempt to use the standard [`SizeCountOptions`](https://github.com/Azure/azure-sdk-for-net/blob/master/common/Perf/Azure.Test.Perf/SizeCountOptions.cs) as the basis for the tests, unless additional criteria is deemed necessary during the implementation.

# Out of Scope

- Performance tests for the `ServiceBusProcessor`, `ServiceBusSessionProcessor`, and the `Microsoft.Azure.ServiceBus` push receiving model;  the performance framework does not have the needed support for long-running background operations at this point in time.

# Success Criteria

- The performance test project for Service Bus has been created and integrated into the repository, following established patterns.  _(see example references below)_

- The performance tests cover the publishing scenarios that were identified as part of the initial scope.   If a core scenario is unsupported by the performance framework, an issue has been filed to implement them at a later point when framework support is available.

- The performance tests support a configurable number of messages to be published/read in addition to the standard options.  

# References and Related

- [Performance Testing Framework and Sample Project](https://github.com/Azure/azure-sdk-for-net/tree/master/common/Perf)
- [Azure.Messaging.EventHubs implementation](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventhub/Azure.Messaging.EventHubs/perf)

**Comment by JoshLove-msft** [comment]
Related https://github.com/azure/azure-sdk-for-net/issues/18466

**Comment by JoshLove-msft** [comment]
Performance tests were added for T2. Still need to add perf tests for T1.
