### ISSUE TITLE
[ACR] add a method to get all tags for a given image

### ISSUE THREAD

**Issue by jeremymeng** [Azure/azure-sdk-for-net#20104]
From @annelo-msft 
> it would be nice to expose this functionality (get all tags for a given image) as a separate method that more clearly indicates the intent to customers.

**Comment by annelo-msft** [comment]
[GetAllTagProperties](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Artifact/RegistryArtifact.cs#L231) provides this functionality.
