### ISSUE TITLE
[FEATURE REQ] Get tokens from Aad v2.0 endpoint

### ISSUE THREAD

**Issue by poyadav2001** [Azure/azure-sdk-for-net#20118]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
We are using 

`ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken = `default)`
to get an access token.

The token is from AAD v1.0 endpoint. Are there any plans to move to move to the v2.0 endpoint

https://docs.microsoft.com/en-us/azure/active-directory/develop/access-tokens

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by schaabs** [comment]
@poyadav2001 The `ManagedIdentityCredential` acquires tokens from a variety of managed identity enabled host endpoints. Currently all of those endpoints currently use the AAD v1.0 protocol. These need to be upgraded to use the v2.0 protocol. Until they are upgraded there is nothing we can do on the client side to fetch v2.0 tokens. Once they have been upgraded the `ManagedIdentityCredential` will be updated to use the new API versions to acquire v2.0 tokens without any changes needed in application code, as the `GetToken` and `GetTokenAsync` already accept the necessary information to call the v2.0 endpoint.

**Comment by poyadav2001** [comment]
Thank you @schaabs for the quick response.

I understand from your explanation that no changes will be required in our application code to get v2.0 tokens. This will get handled by the this library when the endpoints are upgraded.

But the token validation code will have to be changed, to connect to OpenId Connect v2.0 to get signing keys and issuer to validate v2.0 tokens, right

**Comment by schaabs** [comment]
> validation code will have to be changed, to connect to OpenId Connect v2.0 to get signing keys and issuer to validate v2.0 tokens

This is correct. The Azure.Identity library doesn't handle any token validation. It's generally considered out of scope, since the library's main purpose is to authenticate calls on the client side, not authorize calls on the service side. However if an application is validating the tokens returned from the Azure.Identity library for some reason, this code would have to change.

**Comment by poyadav2001** [comment]
Thank you @schaabs

**Comment by poyadav2001** [comment]
Sorry, but do you have any ideas about the timeline of this upgrade
