### ISSUE TITLE
[QUERY] How can I create (or mock) a Pageable<T> to use in my unit tests?

### ISSUE THREAD

**Issue by WillRock19** [Azure/azure-sdk-for-net#20124]
**Query/Question**

I'm trying to create mocks to unit test a filter I use into a Pageable<BlobItem> list resulted from a call to **BlobContainerClient.GetBlobs()** (see bellow the method logic I'm trying to test and the method I'm using from the **BlobContainerClient** class).  

![image](https://user-images.githubusercontent.com/6953687/113621102-9b6b5a80-9631-11eb-9094-d71f936deebe.png)

![image](https://user-images.githubusercontent.com/6953687/113620391-a4a7f780-9630-11eb-8a91-7f77312f4a16.png)

As I could see in your github, the Pageable<BlobItem> is created throught the **StorageAsyncPageable** class, which is a private class (bellow, the classes I've followed to get into this conclusion).

![image](https://user-images.githubusercontent.com/6953687/113619711-b63ccf80-962f-11eb-8fad-41b36d41f822.png)

![image](https://user-images.githubusercontent.com/6953687/113619800-cfde1700-962f-11eb-8a00-dd0d45633a0b.png)

![image](https://user-images.githubusercontent.com/6953687/113619882-eedca900-962f-11eb-9a14-d736f6e19db9.png)

 Is there another way to create (or mock) a Pageable<T> that I could use to test my **.Where clause**? 
 
 Thank you!

**Environment:**
 - .Net Version: Full Framework 4.8
 - New version: Azure.Storage.Blobs v12.8.0 
 - IDE and version : Visual Studio 16.8.5

**Comment by seanmcc-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/20091#issuecomment-813619200

You can use [Azure.Core.PageResponseEnumerator](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Shared/PageResponseEnumerator.cs).  An example of this is here - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs.ChangeFeed/tests/ChangeFeedTests.cs#L73
