### ISSUE TITLE
[BUG] HttpClientTransport calls CreateDefaultClient regardless of argument / not compatible with Blazor

### ISSUE THREAD

**Issue by TheBoss3433** [Azure/azure-sdk-for-net#20125]
**Describe the bug**
Cannot instantiate HttpClientTransport using HttpClient, it calls CreateDefaultClient() regardless of the argument given. This happens with any Client SDK or with an autorest generated one.
Is the SDK not supposed to be compatible with Blazor WASM?

**Expected behavior**
What is the expected behavior?
Instantiate a BlobClient and/or HttpClientTransport based on HttpClient that is compatible with Blazor WASM

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: The type initializer for 'Azure.Core.Pipeline.HttpClientTransport' threw an exception.
System.TypeInitializationException: The type initializer for 'Azure.Core.Pipeline.HttpClientTransport' threw an exception.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.SocketsHttpHandler.get_MaxConnectionsPerServer()
   at Azure.Core.Pipeline.ServicePointHelpers.SetLimits(SocketsHttpHandler socketsHttpHandler)
   at Azure.Core.Pipeline.HttpClientTransport.CreateDefaultClient()
   at Azure.Core.Pipeline.HttpClientTransport..ctor()
   at Azure.Core.Pipeline.HttpClientTransport..cctor()
   --- End of inner exception stack trace ---
   at QuoteBux.Pages.Index.test() in C:\Users\mathi\source\repos\QuoteBux\Pages\Index.razor:line 25
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
```
**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a new Blazor WASM project
2. run this 
```
  var httpClientTransport = new HttpClientTransport(HttpClient);
        var options = new BlobClientOptions() {Transport = httpClientTransport};
        var client = new BlobClient(new Uri(connectionString), options);
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.1
 - Hosting platform or OS and .NET runtime version 
 ```
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  3.1.402 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
 - IDE and version : [e.g. Visual Studio 16.3] VS 16.9

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by TheBoss3433** [comment]
I believe the issue is in ClientOptions, there;s no way to override the class to prevent 
https://github.com/Azure/azure-sdk-for-net/blob/762a7b2c21d486bfa9853af07586a5621b689975/sdk/core/Azure.Core/src/ClientOptions.cs#L16 from being called

It should allow for overriding of GetDefaultTransport() or somehow prevent it from being called when initializing ClientOptions (or a derived class) with Transport set. 

 In it's current format, there's no way to prevent Blazor from crashing due to unsupported operation as _transport field is private, GetDefaultTransport() method is private. this means HttpClientTransport.Shared will always get called no matter what. 

HttpClientTransport.Shared then calls default constructor of HttpClientTransport which calls 
https://github.com/Azure/azure-sdk-for-net/blob/214b67d9763dad7ab681920ed34b53dd4833f503/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs#L128 which 
calls
https://github.com/Azure/azure-sdk-for-net/blob/214b67d9763dad7ab681920ed34b53dd4833f503/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs#L141
and MaxConnectionsPerServer is not supported on browser...

Would it be possible to either make ClientOptions.GetDefaultTransport public? That way I could create BlazorClientOptions to use as base for my client options Coud also move the initialization to the constructor, as I could override that too...I might be missing something as to why that can't be the case, feel free to correct me I am still pretty new at this

There might be some more issues in subsequent calls but this seems to be the main problem. Hopefully this makes sense
