### ISSUE TITLE
[BUG] SqlServerStoredProcedureActivity class for DataFactory management does not save the LinkedServiceName properly 

### ISSUE THREAD

**Issue by kktam** [Azure/azure-sdk-for-net#20137]
**Describe the bug**
SqlServerStoredProcedureActivity class for DataFactory management does not save the LinkedServiceName properly into the pipeline for execution.  When the pipeline runs, it will fail and gives the following error

```
Error code
2400
Failure type
User configuration issue
Details
Cannot create Sql Source. Please double check the connection string, stored procedure are set with correct format. Error: The connection string provided is invalid.
Source
Pipeline
<name of the pipeline>
```

**Expected behavior**
Pipeline executes the store procedure activity with given Azure SQL database linked service reference and run to completion.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?  Azure Data factory failed, with error code 2400.
The developer now needs to login to Azure and open DataFactory pipeline editor, and edit and re-choose the same database service reference, and resave the store procedure (when you reselect the reference, it also clears the saved store procedure name), and validate and republish the pipeline. Now, if you rerun the pipeline it will work.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. create a data factory management project in .net using Visual Studio code, and Microsoft.Azure.Management.DataFactory Nuget library (I use version 4.15.0).  Use tutorial [https://docs.microsoft.com/en-ca/azure/data-factory/tutorial-copy-data-dot-net](https://docs.microsoft.com/en-ca/azure/data-factory/tutorial-copy-data-dot-net) as a starting point.
2. Create and Add SqlServerStoredProcedureActivity to the pipeline
3. Run pipeline.

**Environment:**
- "Microsoft.NET.Sdk.Functions" Version="3.0.11"
 - Microsoft.Azure.Management.DataFactory , version="4.15.0"
 - Microsoft.Azure.Management.ResourceManager Version="3.12.1-preview"
 - Hosting platform or OS . Windows 10
 - Azure Function
 - IDE and version : Visual Studio Code latest

Below is the complete listing of the package reference used in the Azure function

```
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="0.5.1-preview" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
    <PackageReference Include="Microsoft.Azure.Management.DataFactory" Version="4.15.0" />
    <PackageReference Include="Microsoft.Azure.Management.ResourceManager" Version="3.12.1-preview" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.2.8" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.13" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="1.1.4" />
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
@kktam , thanks for raising this issue. I have routed the request to DataFactory team to answer your question. In the meantime, there is a new version 4.17.0 out. If you could try it out and advise back if the problem persists.

Thanks

**Comment by kktam** [comment]
I just tested both v4.16.0 and v4.17.0 and still shows the same problem.  Right after the StoreProcedure activity is added to the pipeline resource and created pipeline, the JSON output from .net library clearly shows the Linked Service name is properly registered on the JSON output (and without errors).

```
        "linkedServiceName": {
          "referenceName": "AzureStorageLinkedService",
          "type": "LinkedServiceReference"
        },
```

Running the pipeline, however shows the error code 2400. It is very strange that on the Data Factory pipeline editor, the "validate" step still shows the pipeline passed all checks, while the editor on the linked service edit box  did not show "AzureStorageLinkedService" was selected, but only on the dropdown list as one of the only choice available.

**Comment by shawnxzq** [comment]
@kktam The json code you shared means you probably link to storage linked service to SP activity, this might be reason why it run failed.

**Comment by kktam** [comment]
@shawnxzq  in the JSON code for setting up linkedService Name

```
"linkedServiceName": {
          "referenceName": "AzureStorageLinkedService",
          "type": "LinkedServiceReference"
        },
```

The word "AzureStorageLinkedService" is the demo name (string) of the SQL storage linked service object.  If it is incorrect to put the name of the service reference in the "referenceName" property, what should be put here instead.

There are significant difference between v4.13 and v4.17 (what I use now)

Here is the documentation for v4.13 

[https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactories.models.sqlserverstoredprocedureactivity?view=azure-dotnet](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactories.models.sqlserverstoredprocedureactivity?view=azure-dotnet). 

and for v4.17

[https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.sqlserverstoredprocedureactivity?view=azure-dotnet](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.sqlserverstoredprocedureactivity?view=azure-dotnet)

in v4.17 linked service required is given here

[https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.executionactivity.linkedservicename?view=azure-dotnet#Microsoft_Azure_Management_DataFactory_Models_ExecutionActivity_LinkedServiceName](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.executionactivity.linkedservicename?view=azure-dotnet#Microsoft_Azure_Management_DataFactory_Models_ExecutionActivity_LinkedServiceName)

 I am using Azure SQL server serverless, and not Azure SQL synapse.

**Comment by kktam** [comment]
Here is the full sample construction code

```
public List<Activity> CreateStoreProcedureActivity(string storeProcedureName, string serviceName)
        {
            LinkedServiceReference serviceRef = new LinkedServiceReference();
            serviceRef.ReferenceName = serviceName;

            List<Activity> activites = new List<Activity>
                {
                    new SqlServerStoredProcedureActivity
                    {
                        Name = "InsertIntoProductTable",
                        DependsOn = new List<ActivityDependency>
                        {
                            new ActivityDependency()
                            {
                                Activity = "CopyFromBlobToSQL",
                                DependencyConditions = new string[]{ "Succeeded" }
                            }
                        },
                        Policy = new ActivityPolicy
                        {
                            Timeout = "7.00:00:00",
                            Retry = 0,
                            RetryIntervalInSeconds = 30,
                            SecureOutput = false,
                            SecureInput = false
                        },
                        StoredProcedureName = storeProcedureName,
                        StoredProcedureParameters = new Dictionary<string, StoredProcedureParameter> {
                            { "currency", new StoredProcedureParameter { Value ="CAD", Type = "String" } },
                            { "createdBy", new StoredProcedureParameter { Value ="APerson", Type = "String" } },                            
                        },
                        LinkedServiceName = serviceRef
                    }
                };

            return activites;
        }  
```

**Comment by kktam** [comment]
> @kktam The json code you shared means you probably link to storage linked service to SP activity, this might be reason why it run failed.

Hi @shawnxzq can you verify if I have constructed the LinkedServiceReference  object correctly, or if I need to use DataFactory SDK to instantiate it on the cloud side before using it in this statement?

**Comment by shawnxzq** [comment]
@kktam What's the value of the parameter "serviceName" for the method CreateStoreProcedureActivity? And it should be the name of Azure SQL linked service, and the linked service should have the correct connection string defined.

**Comment by kktam** [comment]
the value of service name is passed in with name of the service linked created, and used (shared) with another DataSet. I am not sure if there is a restriction in sharing service reference between Activity like this, and other data sets. When I ran into this issue, on the Azure Data Factory portal pipeline editor, I can reference the same service reference to multiple datasets and this activity without issues (only if I modified pipeline in the editor and save and run).

**Comment by kktam** [comment]
otherwise, I will need to demonstrate this in a virtual meeting session, and run it in my Data Factory setup to demonstrate this bug.

**Comment by shawnxzq** [comment]
@kktam It is not related to sharing, most likely the "serviceName" passed in is not the name of a SQL linked service. If you still have any issue, suggest you can raise a support ticket with the activityRunId which run with the error message, thanks!

**Comment by kktam** [comment]
@shawnxzq What are the steps to raise a ticket with activityRunId ?  Can I paste the run Id here, or I have to go through a different system to log the ticket. Can you describe the steps to create the ticket here?

**Comment by shawnxzq** [comment]
@kktam You can follow the standard azure process to raise the support case, please close this one after you filed the support case, thx!

![image](https://user-images.githubusercontent.com/6882305/115714090-540ef900-a3a9-11eb-96b5-0f3150059e21.png)

**Comment by shawnxzq** [comment]
@kktam Have you got your issue resolved through support? Thanks!

**Comment by shawnxzq** [comment]
@allenjzhang We already suggest customer the right channel to solve this issue and didn't get more response, could you please help close this as I don't have the permission? Thanks!

**Comment by shawnxzq** [comment]
@allenjzhang  @lmy269 We can close this one now, please help close it since I don't have the permission, thx!

**Comment by shawnxzq** [comment]
Close it as it's feature related and suggest customer to go through support channel.
