### ISSUE TITLE
[FEATURE REQ]Enable MSAL log

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#20140]
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
Azure.Identity should allow customers to configure MSAL logging levels, including PII info and platform loggings.

**Comment by christothes** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/14450

**Comment by christothes** [comment]
FYI - logging (without PII) is implemented in https://github.com/Azure/azure-sdk-for-net/pull/19637 and should be available in the next release.
