### ISSUE TITLE
[BUG] LabeledUtterance id is int32 but client response data bigger than it.

### ISSUE THREAD

**Issue by kdl12138** [Azure/azure-sdk-for-net#20143]
LabeledUtterance id is int32 but client response data bigger than it.
![image](https://user-images.githubusercontent.com/32616612/113679785-bc47b480-96f2-11eb-917e-2e550251c359.png)

![image](https://user-images.githubusercontent.com/32616612/113679750-b225b600-96f2-11eb-91ee-7f5a22c72803.png)

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring 3.1.0
 - Windows 10 .NET Core 3.1.403
 - IDE and version : Visual Studio 16.7.7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by hebaelfadly** [comment]
@jsquire any updates on this? 
Same issue when deleting example
![image](https://user-images.githubusercontent.com/61690067/121340101-7d66f280-c91f-11eb-80a3-4336e7228239.png)

**Comment by jsquire** [comment]
Hi @hebaelfadly.  Unfortunately, I am only serving as first triage and have no insight into the Cognitive Services offerings nor their team process for triaging.   I'll need to defer to @cahann, @kayousef for updates.

**Comment by cahann** [comment]
hi @hebaelfadly , thanks for reporting the bug. I will be working with @moabba on triaging the bugs in on of our coming sprints.

**Comment by SaurabhSharma-MSFT** [comment]
@cahann @moabba Do you have any updates on this issue.
