### ISSUE TITLE
[FEATURE REQ]Need to support both TokenCredentialOptions  and ClientCertificateCredentialOptions  with ClientCertificateCredential

### ISSUE THREAD

**Issue by yangyud-cn** [Azure/azure-sdk-for-net#20142]
**Library or service name.**
What library or service is this request related to? Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
The public constructors of ClientCertificateCredential can either go with TokenCredentialOptions  or with ClientCertificateCredentialOptions , but not both, although the underlaying internal only interface can do that.   This breaks the following usage:   Subject Issuer authentication with none AzurePublic cloud.

**Comment by yangyud-cn** [comment]
Refer to #16298 where the ClientCertificateCredentialOptions.SendCertificateChain prop was added

**Comment by schaabs** [comment]
@yangyug-cn Thanks for filing this issue. `ClientCertificateCredentialOptions` derives from `TokenCredentialOptions` so you can if you're using a cloud other than Azure Public cloud you can set the `AuthorityHost` directly on `ClientCertificateCredentialOptions` as you previously did on `TokenCredentialOptions`. Hopefully this helps, and I'm sorry for any confusion the extra overloads might have introduced. I'm closing this issue as I believe what you're attempting to do is already supported, but if you find this still doesn't address your issue please feel free to reopen it.

**Comment by yangyud-cn** [comment]
Thanks for the information.  Just noticed the document and also code do mentioned all these.  I missed that because the document's navigation tree only shows newly introduced properties :(

![image](https://user-images.githubusercontent.com/16533616/113810505-fe2d3500-979c-11eb-8847-a4ebf2005534.png)
