### ISSUE TITLE
[QUERY] Is it possible to use the GetDirectoryReference() method in a BlobContainerClient?

### ISSUE THREAD

**Issue by WillRock19** [Azure/azure-sdk-for-net#20162]
**Query/Question**
Hi. We've been using the Microsoft.WindowsAzure.Storage.Blob version 9.3.2.0 and used the code bellow:

```csharp
CloudStorageAccount storageAccount = CloudStorageAccount.Parse(storageConnectionString);
CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();
var cloudBlobContainer = blobClient.GetContainerReference("azure-webjobs-hosts"); //returns a CloudBlobContainer
			
if (cloudBlobContainer .Exists())
{
var blobsOutputLogs = cloudBlobContainer 
	.GetDirectoryReference("output-logs")
	.ListBlobs()
	.OfType<CloudBlob>();
}
```
I'm trying to find something similar to the **cloudBlobContainer.GetDirectoryReference("output-logs").ListBlobs()** call. I'm converting this to the Azure.Storage.Blobs and using a **BlobContainerClient** instead of a **CloudBlobContainer** (see bellow):

```csharp
var containerReference = _storageWrapper
  .GetContainerReference(connectionString, containerName); //returns a BlobContainerClient

if (containerReference.Exists())
{
  var blobsToBeDeleted = containerReference
    .GetBlobs()
    .ToList();
}
```

But I'm not finding anything similar to the **GetDirectoryReference** method. How could I use it in this new version?

**Environment:**
- .Net Version: Full Framework 4.8
- Original version: Microsoft.WindowsAzure.Storage.Blob 9.3.2.0
- New version: Azure.Storage.Blobs v12.8.0
- IDE and version : Visual Studio 16.8.5

**Comment by seanmcc-msft** [comment]
@WillRock19, there are no directory references in Azure.Storage.Blobs.  If you are using a storage account with hierarchical namespace enabled, I recommend using Azure.Storage.Files.DataLake.

**Comment by WillRock19** [comment]
@seanmcc-msft, thanks for the heads up!

Just to be sure: I could use the DataLake to get a directory and then get the blobs inside that directory, as I used to do in the old version? (see the code in the first message). Is there any example of how to do something like this?

**Comment by seanmcc-msft** [comment]
Yes.

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeDirectoryClient.cs#L2361

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Files.DataLake/tests/DirectoryClientTests.cs#L4854
