### ISSUE TITLE
Creating Deployment against Germany region results in time out or internal server error

### ISSUE THREAD

**Issue by MrMeemus** [Azure/azure-sdk-for-net#2018]
We are able to delete the staging slot through the DeleteBySlotAsync, but when attempting to createdeployment against the same slot we receive the following error.

**05/23/2016 22:18:12 Info System.AggregateException: One or more errors occurred. ---> System
.Threading.Tasks.TaskCanceledException: A task was canceled.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancella
tionToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at ImportExportServiceDeployer.ManagementController.CreateDeployment(DeploymentSlot slot,
DeploymentCreateParameters parameters)
   at ImportExportServiceDeployer.DeployIEServiceStagingSlot.Execute(HostedServiceType deplo
yItem)
---> (Inner** Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.
<---

The deployment had a time out with 15 min and we run it synchronously. We use certificate authentication. Please reach out to me if you need more information.

**Comment by singhkay** [comment]
@MrMeemus It looks like you're trying to create a PaaS deployment. It would be best to reach out to support team for guidance with PaaS issues. This repo is for the client libraries that are used by PowerShell cmdlets.

**Comment by MrMeemus** [comment]
@singhkay I believe we are attempting a Iaas deployment. Fortunately this issue has been resolved, as it was a issue in the Mangement Service Rest API.

**Comment by singhkay** [comment]
@MrMeemus Glad to hear :+1:
