### ISSUE TITLE
Review errors for all FAQ DefaultAzureCredential error scenarios

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#20203]
There are a common set of edge case issues that customers encounter when using `DefaultAzureCredential` that result in failures that are difficult to diagnose or debug. 

Review all of these error scenarios and improve the relevant error messages as appropriate.

**Comment by ericsampson** [comment]
Hi @christothes , re your [comment that led to this issue being created](https://github.com/Azure/azure-sdk-for-net/issues/19511#issuecomment-816848413)

I'm sure that I'm missing information, but why does the az CLI work fine with this tenant scenario, if as per your comment there is something fundamental that needs to be addressed for VS/VSCode token providers to work. I'm just curious why they can't do the same thing that allows the CLI to work fine in this case.

Our org has been running into this too and it has been a real pain for us.
In this related issue, Anais said that they created an internal request for VS to address this.
https://github.com/Azure/azure-sdk-for-net/issues/12773#issuecomment-807852417

**Comment by christothes** [comment]
> Hi @christothes , re your [comment that led to this issue being created](https://github.com/Azure/azure-sdk-for-net/issues/19511#issuecomment-816848413)
> 
> I'm sure that I'm missing information, but why does the az CLI work fine with this tenant scenario, if as per your comment there is something fundamental that needs to be addressed for VS/VSCode token providers to work. I'm just curious why they can't do the same thing that allows the CLI to work fine in this case.
> 
> Our org has been running into this too and it has been a real pain for us.
> In this related issue, Anais said that they created an internal request for VS to address this.
> [#12773 (comment)](https://github.com/Azure/azure-sdk-for-net/issues/12773#issuecomment-807852417)

We're planning to address the tenant discovery feature mentioned in that comment you linked to. Here is the tracking item: https://github.com/Azure/azure-sdk-for-net/issues/19404
