### ISSUE TITLE
Azure Storage Blobs Batch Sample issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#20214]
1.
Sample [Sample03a_Batching.cs](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs.Batch/samples/Sample03a_Batching.cs#L131) and [Sample03b_BatchingAsync.cs]( https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs.Batch/samples/Sample03b_BatchingAsync.cs#L116):
![image](https://user-images.githubusercontent.com/65581162/113984961-3c4e5580-987e-11eb-9fc9-dedb9d77c261.png)

[Azure.Storage.Blobs.Batch/src/Models/Internal/DeleteSnapshotsOptionType.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs.Batch/src/Models/Internal/DeleteSnapshotsOptionType.cs):
![image](https://user-images.githubusercontent.com/65581162/124742366-38020900-df4f-11eb-98de-e8a428631b4a.png)
Reason:The enum class `DeleteSnapshotsOption` in Azure.Storage.Blobs.Models convert to the enum class `DeleteSnapshotsOptionType` in Azure.Storage.Blobs.Batch.Models failed, lead to the delete request failed .

@scottaddie , @AlexGhiondea , @kyle-patterson , @tg-msft , @amishra-dev and @jongio for notification.

**Comment by v-xuto** [comment]
@tg-msft What are your plans to fix this issue? Can you find the right person to fix this issue?

**Comment by tg-msft** [comment]
The Storage team will triage this and fix the break as appropriate.  The current tags will put this on their radar.  You can follow up with @seanmcc-msft for more if needed.
