### ISSUE TITLE
Azure Quantum Jobs Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#20213]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/quantum/Azure.Quantum.Jobs#azure-quantum-jobs-client-library-for-net):
![image](https://user-images.githubusercontent.com/65581162/113977992-f5f4f880-9875-11eb-8042-cd94c111be05.png)
Suggestion:  Update `t` to `to:`

2.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/quantum/Azure.Quantum.Jobs#install-the-package):
![image](https://user-images.githubusercontent.com/65581162/113978130-2341a680-9876-11eb-8fd5-c633786ca9a5.png)
Suggestion: Add [nuget]: https://www.nuget.org/

3.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/quantum/Azure.Quantum.Jobs#contributing):
![image](https://user-images.githubusercontent.com/65581162/113978345-6dc32300-9876-11eb-8e34-68aa72908349.png)
Suggestion:   
1.Update to https://cla.microsoft.com

2.Add  [coc]: https://opensource.microsoft.com/codeofconduct/

3.Add [coc_faq]: https://opensource.microsoft.com/codeofconduct/faq/

4.Update to opencode@microsoft.com

@jongio for notification.

**Comment by vxfield** [comment]
Acknowledged and thanks for reporting these issues. 
Planning to do this in April.

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-net/pull/21133 merged.
