### ISSUE TITLE
Azure WebJobs EventGrid Readme issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#20216]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/eventgrid/Microsoft.Azure.WebJobs.Extensions.EventGrid#using-event-grid-output-binding):
![image](https://user-images.githubusercontent.com/65581162/113980658-55a0d300-9879-11eb-8510-0340f6a3a5c9.png)
Suggestion: Update link to https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid-output?tabs=csharp

@jongio for notification.

**Comment by JoshLove-msft** [comment]
There is no functional difference as C# is the first tab in the table.
