### ISSUE TITLE
[Service Bus] Sample needed for Dead Letter Queues

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#20212]
The doc [Overview of dead letter queues](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues) links to a sample that uses the older .NET package WindowsAzure.ServiceBus

Ideally, there should be links to samples that use packages from all languages. This issue is to add a corresponding sample that uses the `Azure.Messaging.ServiceBus` package so that it can be linked appropriately.

Reference: [DeadLetterQueue](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/DeadletterQueue)

Adding this sample will also be useful for us to re-direct readers who land at the above sample.

cc @spelluru

**Comment by JoshLove-msft** [comment]
We have this already https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample02_MessageSettlement.md#dead-letter-a-message

**Comment by JoshLove-msft** [comment]
@ramya-rao-a given that we have this sample is there anything that needs to be done to help the docs experience? Do we need the sample to be stand-alone or is it okay that it is part of a larger sample doc?

**Comment by ramya-rao-a** [comment]
The doc expects the sample to show the different ways a message can get dead lettered and then how to access the dead letter queue. So, I would recommend a stand alone sample
