### ISSUE TITLE
[BUG] Azure.Identity should wrap MsalUiRequiredException as inner exception when throwing CredentialUnavailableException

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-sdk-for-net#20218]
**Describe the bug**
This is prerequisite for fix the issue https://github.com/Azure/azure-powershell/issues/14717

When MsalUiRequiredException exception is thrown from MSAL library, Azure.Identity Credentials swallow the exception and throw  general CredentialUnavailableException exception, e.g. [SharedTokenCacheCredential](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/SharedTokenCacheCredential.cs#L121). However Azure PowerShell needs to give user actionable message based on the detail error info from CredentialUnavailableException, e.g. suggest user to login with specific tenant id for MFA.

**Environment:**
 - Name and version of the Library package used: Azure.Identity

**Comment by jiasli** [comment]
Only FYI: previously I asked `azure-identity` from Python SDK to expose the original MSAL error (https://github.com/Azure/azure-sdk-for-python/issues/16906).

It was eventually solved by exposing the original HTTP response (https://github.com/Azure/azure-sdk-for-python/pull/17442).

**Comment by christothes** [comment]
Hi @erich-wang - Which credential are you using where it is not being wrapped?

**Comment by erich-wang** [comment]
At least https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/SharedTokenCacheCredential.cs#L119-L122, I did not go thru all credentials, but most of them do not expose it.

**Comment by joshfree** [comment]
tagging as 'blocking-release' for the May milestone

**Comment by dingmeng-xue** [comment]
Hi Josh, what's the release timeline of May milestone? We are considering whether it can be ready by the mid of May and we will release Az major release after some verifications.

User hit this vague message because recently more and more companies deployed MFA policy.

**Comment by christothes** [comment]
Code complete for the Azure SDK is always the first Friday of the month; and the release is early the following week.  So code complete will be Friday May 7th and the release will be the week of May 10.
