### ISSUE TITLE
[Service Bus] Sample needed for Topic Filters 

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#20211]
The section on [Rules and actions in docs for Service Bus](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-queues-topics-subscriptions#rules-and-actions) links to a sample that uses the older .NET package Microsoft.Azure.ServiceBus.

Ideally, there should be links to samples that use packages from all languages. This issue is to add a corresponding sample that uses the `Azure.Messaging.ServiceBus` package so that it can be linked appropriately.

Reference: [TopicSubscriptionWithRuleOperationsSample](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample)

Adding this sample will also be useful for us to re-direct readers who land at the above sample.

cc @spelluru

**Comment by JoshLove-msft** [comment]
Created https://github.com/MicrosoftDocs/azure-docs-pr/pull/157495 for docs update
