### ISSUE TITLE
ComputeManagementClient creation signature

### ISSUE THREAD

**Issue by f1crazed** [Azure/azure-sdk-for-net#2022]
I noticed that the signature for the ComputeManagementClient constructor has changed for version 13 and no longer includes a constructor for SubscriptionCloudCredentials. This would be highly valuable to leave in place unless there is another way to allow for TokenCloudCredentials to be used when initializing a new ComputerManagementClient. This would help in keeping the following authentication method consistent.

```csharp
var authenticationContext = new AuthenticationContext("https://login.windows.net/" + tenant);
 var credential = new ClientCredential(clientId: clientId, clientSecret: pw);
 Task<AuthenticationResult> tskGetToken = authenticationContext.AcquireTokenAsync(resource: "https://management.core.windows.net/", clientCredential: credential);
AuthenticationResult token = tskGetToken.Result;
SubscriptionCloudCredentials scc = new TokenCloudCredentials(_strSubscriptionID, token.AccessToken);
ComputeManagementClient cmc = new ComputeManagementClient(scc);
```

**Comment by adrianhall** [comment]
Is this still an issue for you?  If so, can you please provide the .NET library and version that you are using? 
(Close on Oct 9 if no response)

**Comment by f1crazed** [comment]
This is still an issue. The version I am using is 9.1.0. I just tried to update to 29.0.0 and get the same error that ComputeManagementClient does not take SubscriptionCloudCredentials. In 9.1.0 it did.

**Comment by AlexGhiondea** [comment]
@f1crazed can you share more information about the library you are using?

**Comment by f1crazed** [comment]
AlexGhiondea, Sorry for the delay in my response.  I am using version 9.1.0 of the Microsoft.Azure.Management.Compute library.

**Comment by nickzhums** [comment]
@isra-fel could you take a look please, thanks

**Comment by isra-fel** [comment]
f1crazed `TokenCloudCredentials` is no longer supported. Please use [Microsoft.Rest.ClientRuntime](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime) to authenticate your client.

```csharp
// instead of SubscriptionCloudCredentials scc = new TokenCloudCredentials(_strSubscriptionID, token.AccessToken);
ServiceClientCredentials scc = new TokenCredentials(token.AccessToken, token.AccessTokenType);
```
