### ISSUE TITLE
[FEATURE REQ] AzureKeyVaultConfigurationProvider logging/metrics capability needed

### ISSUE THREAD

**Issue by wn9237** [Azure/azure-sdk-for-net#20231]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
Azure.Extensions.AspNetCore.Configuration.Secrets

**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
I am trying to use AddAzureKeyVault for managing secerts for my .net core web app, and would like to add metrics/logging capability into the flow, for cases like key vault connection failures, metrics on current cert thumbprint, etc.. the current interface doesn't allow to easily add them.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pallavit** [comment]
@jsquire is this something you see us absorbing in the near future?

**Comment by jsquire** [comment]
@pallavit :  I don't believe so.   Logging and tracing takes place in the underlying Key Vault clients.  Any extensions for custom metrics would be done there, not as part of the extensions.   To my knowledge, we have no plans for custom metrics as an extension point our client libraries.

**Comment by jsquire** [comment]
After discussion, this isn't an enhancement that we'll be moving forward with.  The underlying clients emit logs for these activities today; there are no current plans to add an additional metrics interface currently.
