### ISSUE TITLE
[BUG] Microsoft.Azure.WebJobs.Extensions.ServiceBus doesn't Support Value/Sequence AMQP message bodies

### ISSUE THREAD

**Issue by TsuyoshiUshio** [Azure/azure-sdk-for-net#20236]
Microsoft.Azure.WebJobs.Extensions.ServiceBus (5.0.0-beta.1) doesn't support it.  Since it uses Azure.Messaging.ServiceBus7.2.0-beta.1, however bet.2 looks support it.  I recommend to upgrade it for supporting the scenario.

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/CHANGELOG.md#720-beta2-2021-04-07

**Comment by jsquire** [comment]
Hi @TsuyoshiUshio.  That is the plan.  Our next release of the Function Extensions for Service Bus will be using the updated client library version.

**Comment by JoshLove-msft** [comment]
The new preview will allow you to use access the value/sequence when binding to the `ServiceBusReceivedMessage`. It won't have the updated string binding support that would look to the AMQP value the way that Track 1 does - but this will be added by GA. This issue can be used to track this gap.

**Comment by jsquire** [comment]
Adjusting tags, since we're going to use this for tracking past this month's release.

**Comment by JoshLove-msft** [comment]
Another issue has come up with how this is implemented - currently an exception is thrown if the ServiceBusReceivedMessage.Body getter is called for a Sequence/Value body. The functions runtime uses reflection to get all property values, even when the function is just binding to the ServiceBusReceivedMessage rather than the body. We will need to reconsider throwing from the property getter in this case.

**Comment by JoshLove-msft** [comment]
This is fixed in https://github.com/Azure/azure-webjobs-sdk/releases/tag/v3.0.29
We just need to wait for this version to be published to nuget and then release a new version of the extension depending on it.

**Comment by JoshLove-msft** [comment]
The fix has been released in https://www.nuget.org/packages/Microsoft.Azure.WebJobs/3.0.29. We just need to update the dependency and add tests to the Service Bus extension.
