### ISSUE TITLE
Respect working directory in RecordedTestBase

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#20246]
While debugging an issue in a Linux container using Visual Studio, session files are not read because of `GetSessionPath()` or, more specifically, [`TestEnvironment.GetSourcePath`](https://github.com/Azure/azure-sdk-for-net/blob/950e358b4ba335718b1d6568be1d9eb45c10e835/sdk/core/Azure.Core.TestFramework/src/RecordedTestBase.cs#L98), but that might be a little harder to fix and would only help support live tests (e.g. recording).

We could instead do something like:

```diff
             string fileName = name + (IsAsync ? "Async" : string.Empty) + ".json";

-            string path = TestEnvironment.GetSourcePath(GetType().Assembly);
+            string path = Path.Combine(TestContext.CurrentContext.TestDirectory, "SessionRecords");
+            if (!Directory.Exists(path))
+            {
+                path = Path.Combine(TestEnvironment.GetSourcePath(GetType().Assembly), "SessionRecords");
+            }

             return Path.Combine(path,
-                "SessionRecords",
                 additionalParameterName == null ? className : $"{className}({additionalParameterName})",
                 fileName);
         }
```

However, this has the downstream effect of saving new recordings to the `$(OutputPath)` again, and it's been nice having them show up in place. Perhaps we could get and store both locations - a read-only location, and a read-write (or even write-only) path that uses the source from the attribute.

We might even consider translating the original path and mapping onto the working directory.

**Comment by heaths** [comment]
/cc @pakrym @christothes 

I'm going to write up a post how I did this. I tried to automate it in Visual Studio, but it seems to only work seamlessly with ASP.NET Core projects. I'm asking around internally to find out more.

**Comment by pakrym** [comment]
The entire story with `TestEnvironment.GetSourcePath` was to enable re-recording without having to copy records around.

**Comment by heaths** [comment]
1. Is it accidental (i.e. never cleaned up) that tests still get copied to the `$(OutputPath)` then?
2. Are you open to consider potentially reading from one location and always writing to the other?

Then again, if we want to support writing tests even when running in a container (though I prefer mounting the output as a read-only file system) I guess we'd have to map the path anyway.

**Comment by pakrym** [comment]
>Is it accidental (i.e. never cleaned up) that tests still get copied to the $(OutputPath) then?

Yes, I think so.

> Are you open to consider potentially reading from one location and always writing to the other?

Do you mean reading from the output path and writing to the src? I would prefer if we don't as it might create confusion for developers about what's being loaded from where and removing the Copiyng of records might actually improve the build perf.

**Comment by heaths** [comment]
I wonder if we can write the normalized source path like is done for nupkgs which enables SourceLink instead. It's basically a repo-relative path which is easy to translate. That can be mapped onto other paths like GitHub URLs (something like that; it's been a while since I delved a little into this but can refresh on it).

**Comment by pakrym** [comment]
I think that's a great idea.

**Comment by heaths** [comment]
I'm self-assigning then. I'll take a look at this when a preview of some functionality demo'd in .NET Conf is available.

**Comment by pallavit** [comment]
@heaths would you still want to track and experiment here?

**Comment by heaths** [comment]
@JoshLove-msft do you think this is even a problem anymore given all the changes introduced for test proxy? OP should help, but effectively it's a file resolution problem. If the test proxy support always walks back to the repo root and follows a fixed breadcrumb pattern back down to session files, this may inadvertently be fixed.
