### ISSUE TITLE
Importing ECDsa prime-field curves fails on Linux and OSX

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#20244]
A few tests are failing on P256K curve names because Key Vault generates them as prime-field curves, and OpenSSL-based implementations of `ECDsa` on Linux and OSX are failing to [import the private key](https://github.com/Azure/azure-sdk-for-net/blob/950e358b4ba335718b1d6568be1d9eb45c10e835/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/PemReader.cs#L63). This works on Windows so presumably the ASN.1 parsing is correct, so more investigation is required.

**Comment by pallavit** [comment]
@heaths Is this still relevant?

**Comment by heaths** [comment]
Yes, but no one else has asked about it so I propose we close it until there is need to support different key formats for local cryptography on non-Windows platforms.
