### ISSUE TITLE
Typo on NotificationOutcomeState Enum Fields description

### ISSUE THREAD

**Issue by bemartin** [Azure/azure-sdk-for-net#20240]
There is a typo in the description for the Completed value:

> NotificationOutcome when the notification sent has been **recevied**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed8832ed-bfc1-a7c0-889c-c072cf578d5d
* Version Independent ID: d10e016f-323a-3431-3687-e044ddd492ce
* Content: [NotificationOutcomeState Enum (Microsoft.Azure.NotificationHubs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.notificationoutcomestate?view=azure-dotnet&source=docs#fields)
* Content Source: [xml/Microsoft.Azure.NotificationHubs/NotificationOutcomeState.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.NotificationHubs/NotificationOutcomeState.xml)
* Service: **notification-hubs**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
