### ISSUE TITLE
Race condition in batch receiving 

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#20253]
In the `ServiceBusListener`, the _started flag is used to exit the batch receive loop. It is possible the receive loop might hit [this line](https://github.com/Azure/azure-sdk-for-net/blob/2f76ccd6ff3448bcc3f39ad559ad71c5b19d5a46/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs#L245) before the _started flag ever [gets set to true](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs#L109), which would cause the listener to never receive any messages.
This seems to happen more commonly in .NET 5.0 and has been happening in our live tests.

I believe this same issue exists in the T1 extensions. /cc @mathewc @paulbatum

**Comment by mathewc** [comment]
@alrod I've created a T1 issue https://github.com/Azure/azure-functions-servicebus-extension/issues/147 for this. Can you please confirm that this is an issue there as well?

**Comment by mpaul31** [comment]
I'm hesitant to start using batch receiving with the sb extension knowing this is a potential issue. Can we get confirmation if this is the case?

**Comment by JoshLove-msft** [comment]
Which version of the extensions are you asking about? This was an issue and has been fixed in the new 5.0 beta versions.

**Comment by mpaul31** [comment]
> Which version of the extensions are you asking about? This was an issue and has been fixed in the new 5.0 beta versions.

4.2.2

**Comment by JoshLove-msft** [comment]
For that I will have to defer to @mathewc and @alrod for confirmation. That version of the extension lives in a separate repo and is tracked with this issue - https://github.com/Azure/azure-functions-servicebus-extension/issues/147
