### ISSUE TITLE
Error in the default scope for the resource

### ISSUE THREAD

**Issue by ilya-git** [Azure/azure-sdk-for-net#20256]
At the very bottom there is this string:

`ResourceId + "./default"`

It looks like it's wrong and should be:

`ResourceId + "/.default"`

The first one fails while the other one worked for me

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f95d1f9-f552-ab33-2cbb-f5bc09f6cf5f
* Version Independent ID: 76c243d5-0e9f-cb8d-8919-a06e75ad2cf5
* Content: [App Authentication to Azure Identity Migration Guidance - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration?view=azure-dotnet)
* Content Source: [api/overview/azure/app-auth-migration.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/app-auth-migration.md)
* Product: **azure**
* GitHub Login: @jlichwa
* Microsoft Alias: **jalichwa**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ilya-git** [comment]
It would also be nice with some clarification what this "/.default" mean since usually the app URI is enough to get the token
