### ISSUE TITLE
Review Service Bus samples repo

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#20279]
azure-service-bus/samples/DotNet/Microsoft.Azure.ServiceBus at master · Azure/azure-service-bus (github.com)

That has a bunch of samples explaining a few different features of Service Bus. We should update the README for each of these samples providing a link to the corresponding T2 sample (where such a sample exists). For features where we don't have corresponding samples, we can consider adding them if they add value.

**Comment by ramya-rao-a** [comment]
There are 3 of these samples that we know for sure are linked from docs and so need counterparts that use Azure.Messaging.ServiceBus. Issues have already been logged for these:
- [Azure Identity](https://github.com/Azure/azure-sdk-for-net/issues/20281)
- [Dead Letter Queues](https://github.com/Azure/azure-sdk-for-net/issues/20212)
- [Topic Filters](https://github.com/Azure/azure-sdk-for-net/issues/20211)

**Comment by JoshLove-msft** [comment]
Going through the samples listed here one by one - https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus.
I've included columns for each language to either link to an issue in your repo or the existing sample.

| Scenario | Recommendation | .NET | Java | JS | Python |
| --------- | ------------- | ----- | ----- | -- | ------- |
[Auto-Forward](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/AutoForward) | this contains the ARM template for creating the resource. As it is not using the client SDK there is no need to add this for T2. 
[Dead-Letter Queues](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/DeadletterQueue) | we should have this already in all languages | https://github.com/Azure/azure-sdk-for-net/issues/20212
[Deferral](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/Deferrall) | we should have this already in all languages
[Duplicate Detection](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/DuplicateDetection) | this is another ARM example that is SDK agnostic - so not needed
| [Durable Sender](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/DurableSender) | .NET only (or at least Windows only as it relies on MSMQ) - would be nice to include T2 version.
| [GeoReplication](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/GeoReplication) | this uses the ARM SDK so we don't need any samples for the data plane SDK.
| [Queue CRUD](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ManagingEntities/QueueCRUD) | we should already have samples for this in all languages
| [SAS](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ManagingEntities/SASAuthorizationRule) | we should add this for T2, in particular we should show how this can be done with AzureSasCredential.
| [Message Browse](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/MessageBrowse) | we should already have samples for this in all languages
| [PartitionedQueues](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/PartitionedQueues) | we should add this for T2
| [Prefetch](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/Prefetch) | we should add this for T2 for languages that support it
| [Priority Subscriptions](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/PrioritySubscriptions) | should add for T2
| [Queues Getting Started](https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.Azure.ServiceBus/QueuesGettingStarted/Program.cs) | we should already have samples for this in all languages
| [Request/Response](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/QueuesRequestResponse) | this shows how to simulate a request/response pattern between two queues in separate namespaces. It would be nice to add for T2 though the current example is with T0 (not T1).
| [Receive Loop](https://github.com/Azure/azure-service-bus/blob/master/samples/DotNet/Microsoft.Azure.ServiceBus/ReceiveLoop/Program.cs) | this likely already exists for JS/Python but probably not for Java/.NET. It is a more advanced use case as we recommend using the processor for Java/.NET, but it would be nice to have as an advanced scenario.
| [Role Based Access Control](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/RoleBasedAccessControl) | we should add this for T2. | https://github.com/Azure/azure-sdk-for-net/issues/20281
| [Schedule Messages](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/ScheduledMessages) | we should add this for T2.
| [Senders/Receivers Queue](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/SendersReceiversWithQueues) | we should already have samples for this in all languages
| [Senders/Receivers Topic](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/SendersReceiversWithTopics) | we should already have samples for this in all languages
| [Session State](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/SessionState) | we should already have samples for this in all languages
| [Sessions](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/Sessions) | we should already have samples for this in all languages
| [TimeToLive](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TimeToLive) | we should add this for T2
| [Topic Filters](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TopicFilters) | this is an ARM example.
| [Transactions](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.Azure.ServiceBus/TransactionsAndSendVia) | we should already have these for .NET/Java.
| [Basic Send Receive Queue](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient) | we should already have samples for this in all languages
| [Basic Send Receive Topic](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingTopicSubscriptionClient) | we should already have samples for this in all languages 
| [Basic Send Receive Queue](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSendReceiveUsingQueueClient) | we should already have samples for this in all languages 
| [Basic Send Receive Session](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/BasicSessionSendReceiveUsingQueueClient) | we should already have samples for this in all languages 
| [Subscription rules](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/GettingStarted/Microsoft.Azure.ServiceBus/TopicSubscriptionWithRuleOperationsSample) | we should add this for T2 | https://github.com/Azure/azure-sdk-for-net/issues/20211

**Comment by JoshLove-msft** [comment]
Closing as the investigation is done, but the table can still be used for documentation purposes.
