### ISSUE TITLE
[Service Bus] Sample needed for Azure Identity 

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#20281]
The doc [Authenticate and authorize an application with Azure Active Directory to access Azure Service Bus entities](https://docs.microsoft.com/en-us/azure/service-bus-messaging/authenticate-application) has a section towards the end that points to a sample that uses the older .NET package WindowsAzure.ServiceBus. 

Ideally, there should be links to samples that use packages from all languages. This issue is to add a corresponding sample that uses the `Azure.Messaging.ServiceBus` package so that it can be linked appropriately.

Reference: [Azure role-based access control for Service Bus.](https://github.com/Azure/azure-service-bus/tree/master/samples/DotNet/Microsoft.ServiceBus.Messaging/RoleBasedAccessControl)

Adding this sample will also be useful for us to re-direct readers who land at the above sample.

What we need is a sample that will show the use of either DefaultAzureCredential or ClientSecretCredential.

In case of Event Hubs, we pointed to https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample06_IdentityAndSharedAccessCredentials.md

cc @spelluru

**Comment by JoshLove-msft** [comment]
We already have https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Azure.Messaging.ServiceBus#authenticating-with-azureidentity but we should add a full-fledged sample like Event Hubs that includes details around the AAD setup.
