### ISSUE TITLE
[QUERY] Why is there no AsDecimal/AsDouble for FieldValue?

### ISSUE THREAD

**Issue by yowl** [Azure/azure-sdk-for-net#20293]
**Query/Question**
Looking at https://docs.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.models.fieldvalue.ascountrycode?view=azure-dotnet-preview&viewFallbackFrom=azure-dotnet  

If you have high precision numbers, and many forms require more than `Single` provides, why are there no methods for AsDouble or AsDecimal?  I suppose the workaround is to leave as string type and do the conversion in userland.

**Environment:**
 -Azure.AI.FormRecognizer v3.1.0-beta.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Rodrick45** [comment]
AsDouble/AsDecimal methods won't do you any good if the data is stored internally as a float (the precision is already lost). I just want to make sure it is taken into account that the underlying datatype needs to change to solve this issue.

**Comment by yowl** [comment]
@Rodrick45 is this directed at me (author)?  I'm working around this by using a string, so assume internally the data is there in its complete form as read from the OCR.  E.g.

```
            var field = Form.Fields["allowedLaytime"];
            decimal d;
            if (decimal.TryParse(field.ValueData.Text, NumberStyles.AllowDecimalPoint | NumberStyles.AllowThousands, ci, out d))
            {
```

**Comment by maririos** [comment]
@Rodrick45 the service manages the numbers as `double`. The SDK is casting it as a `float` and then exposing it, so in the SDK we should definitely consider exposing `AsDouble` so there is no precision lost.

> @kinelski @maririos is this something we should add?

@AlexGhiondea yes. We want to add it for future releases (4.0.0-beta.1). For other versions, we could consider leave as is as there is a workaround (like @yowl mentioned) or do a `3.2.0 GA` release to include this.
