### ISSUE TITLE
[QUERY] AsFloat() Should there be an option for locale?

### ISSUE THREAD

**Issue by yowl** [Azure/azure-sdk-for-net#20294]
**Query/Question**
For Europe and Latin America, numbers use commas for decimal points so for the input 180,00  (that's a comma).  In US/UK terms that would be 180.00 (one hundred and eighty), but there doesn't appear to be a way to get ToFloat to accept that.

In the RecognizedForm json it is:

```
          {
            "type": "number",
            "text": "180,00",
            "page": 1,
            "boundingBox": [3.23, 9.19, 3.56, 9.19, 3.56, 9.285, 3.23, 9.285],
            "confidence": 0.995,
            "elements": ["#/readResults/0/lines/96/words/4"]
          },
```
And if you do AsFloat()  on that you get 18000.  How can you tell AsFloat what the locale is?

As a workaround I am doing:

```
            if (decimal.TryParse(field.ValueData.Text, NumberStyles.AllowDecimalPoint | NumberStyles.AllowThousands, new CultureInfo("de-DE"), out d))
            {
```

**Environment:**
 - Azure.AI.FormRecognizer 3.1.0-beta.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Note in this case service is not returning `valueNumber`, and the code is following a workaround done for receipt https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FieldValue.cs#L244
FYI @kinelski 

This belongs to the deeper conversation of what to do when service doesn't return `value<type>`. Should text be used?

Related to #17712

**Comment by maririos** [comment]
Need to follow up on how the service team handles locale. In the case the service returns `ValueNumer` will it take into account the locale so user doesn't have to do a workaround?

**Comment by maririos** [comment]
@yowl which function on the `FormRecognizerClient` are you using?

**Comment by yowl** [comment]
I'm using
```
                var forms = await recognizerClient
                    .StartRecognizeCustomForms("model guid here", stream) 
                    .WaitForCompletionAsync();
```

**Comment by maririos** [comment]
After following up, currently `StartRecognizeCustomForms` doesn't support locale on the service side. Other functions, like for example, `StartRecognizeBusinessCards` or `StartRecognizeInvoices` do.

The service is working on adding it though but there isn't a specific date yet for it.
For now, your workaround is the best option.
