### ISSUE TITLE
[BUG] FormsRecognizer/ FieldValue.AsTime fails because the json does not contain valueTime

### ISSUE THREAD

**Issue by yowl** [Azure/azure-sdk-for-net#20295]
**Describe the bug**
Attempting to do AsTime on a time field fails with 
```
Field value is null.
```
**Expected behavior**
AsTime should return the TimeSpan if it was parsed successfully.

**Actual behavior (include Exception or Stack Trace)**
The StartRecognizeCustomForms returns json which contains:

```
                  "time": {
                    "type": "time",
                    "text": "23:55",
                    "page": 1,
                    "boundingBox": [2.95, 6.095, 3.22, 6.095, 3.22, 6.175, 2.95, 6.175],
                    "elements": ["#/readResults/0/lines/46/words/0"]
                  }
```
Note that there is no `valueTime` which appear to be what `FieldValue_internal.DeserializeFieldValue_internal` looks for:

```
                if (property.NameEquals("valueTime"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    valueTime = property.Value.GetTimeSpan("T");
                    continue;
                }
```
Hence it throws in
```
 	Azure.AI.FormRecognizer.dll!Azure.AI.FormRecognizer.Models.FieldValue.AsTime`
```
 as the `valueTime` field is not set.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Anaylse a form with a Time tag using c#
```
            var forms = recognizerClient
                .StartRecognizeCustomForms("modelIdHere", fs, new RecognizeCustomFormsOptions
                {
                    
                })
                .WaitForCompletionAsync();
```

2.  Find the field and do AsTime(), in my case this is in a table so I have
```
            var fieldName = portCallIx == 0 ? "load" : "discharge";
            if (Form.Fields.ContainsKey(fieldName))
            {
                var list = Form.Fields[fieldName].Value.AsList();
                var arrivedRow = list.FirstOrDefault(lv => lv.Value.AsDictionary()["event"].Value.AsString().StartsWith("Arrived", true, CultureInfo.InvariantCulture));
                if (arrivedRow != null)
                {
                    var dict = arrivedRow.Value.AsDictionary();
                    var ts = dict["time"].Value.AsTime();
                    return dict["date"].Value.AsDate().SetTime(ts.Hours, ts.Minutes);
                }
            }
```

**Environment:**
 - Name and version of the Library package used: Azure.AI.FormRecognizer 3.1.0-beta.4
 - WIndows 10 .net framework 4.7.2
Microsoft Visual Studio Professional 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Professional

LightSwitch for Visual Studio 2015   00322-40000-00000-AA879
Microsoft LightSwitch for Visual Studio 2015

Microsoft Visual Studio Tools for Applications 2015   00322-40000-00000-AA879
Microsoft Visual Studio Tools for Applications 2015

Visual Basic 2015   00322-40000-00000-AA879
Microsoft Visual Basic 2015

Visual C# 2015   00322-40000-00000-AA879
Microsoft Visual C# 2015

Visual C++ 2015   00322-40000-00000-AA879
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.0.20622.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1 (Beta8)   14.1.11107.0
ASP.NET and Web Tools 2015.1 (Beta8)

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JetBrains ReSharper 2020.3.4   Build 203.0.20210316.132251
JetBrains ReSharper package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper. Copyright © 2021 JetBrains, Inc.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   3.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Thanks for reporting @yowl . This doesn't seem a bug on the SDK side.

Although the service is identifying the filed as `"type": "time"`, it is not returning the `"valueTime"` property which is what the SDK uses to deserialize the type to `TimeSpan`. We need to follow up with the service team to understand what the behavior on the SDK should be for this type of scenario.

Related to https://github.com/Azure/azure-sdk-for-net/issues/17712 .

**Comment by maririos** [comment]
@bojunehsu could you help me understand in which scenarios the `value<Type>` will not be returned by the service? What will be the desired behavior in this scenario?

**Comment by maririos** [comment]
After understanding more the scenario, what the SDK should do here is provide a clear message to the user on why we were not able to parse the property to the specified type and provide a way to get the user unblocked.
This work will be done as part of #17712

**Comment by yowl** [comment]
Hmm, but surely "23:55" can be parsed to a TimeSpan?

**Comment by yowl** [comment]
My current workaround is to do just this:
```
                    var text = dict["time"].ValueData.Text;
                    var ts = TimeSpan.ParseExact(text, "T", ci);
```

**Comment by yowl** [comment]
/unresolve  Bot, as I understand it we are waiting for the service team to update .

**Comment by yowl** [comment]
oh, sorry, I didn't see @AlexGhiondea  had manually marked it as addressed, I thought it was just a bot getting excited.

**Comment by AlexGhiondea** [comment]
@yowl I marked it as addressed since from the perspective of the SDK there isn't anything we can do until the service add support for it. 

Let me know if you're ok with closing this issue for now.

**Comment by yowl** [comment]
Sure, fine with me, thanks for asking.

**Comment by maririos** [comment]
@yowl you could pin and constantly check the service `What's new` page to learn when this feature is going to be included: https://docs.microsoft.com/azure/applied-ai-services/form-recognizer/whats-new?tabs=csharp
