### ISSUE TITLE
[BUG] SendAsync performance degradation

### ISSUE THREAD

**Issue by evadelnuevo** [Azure/azure-sdk-for-net#20298]
**Describe the bug**
After updating the `Microsoft.Azure.ServiceBus` package from 4.1.1 to 5.1.2 our performance load tests started to fail. We believe there is a performance degradation issue that affects the queue client (`SendAsync` method).

**Expected behavior**
The performance is stable.

**Actual behavior (include Exception or Stack Trace)**
The performance is degraded.

Version 4.1.1 load tests performance (for different builds):
duration...................: avg=1274.325813 min=28.1346 med=1164.3777 max=5199.2588 p(90)=2152.46747 p(95)=2516.562035
duration...................: avg=1228.571845 min=16.9841 med=1098.56585 max=5672.2006 p(90)=2323.30299 p(95)=2639.88406
duration...................: avg=1402.146743 min=33.019  med=1268.26185 max=6997.9666 p(90)=2321.07433 p(95)=2763.291545
duration...................: avg=1258.797064 min=19.0035 med=1178.0737 max=5760.0523 p(90)=2046.12003 p(95)=2410.7208

Version 5.1.2 load tests performance (for different builds):
duration...................: avg=1674.858551 min=31.0022 med=1508.90515 max=7353.941 p(90)=2910.44202 p(95)=3372.70381
duration...................: avg=1740.276796 min=28.0038 med=1620.86505 max=7111.0786 p(90)=2783.84421 p(95)=3265.554415
duration...................: avg=1887.889699 min=14.9668 med=1774.9656 max=6988.9752 p(90)=3116.05071 p(95)=3584.0975
duration...................: avg=1725.125742 min=57.1496 med=1638.98715 max=8505.227 p(90)=2706.48648 p(95)=3043.7245

**To Reproduce**
To reproduce the issue, you can create a console application that sends several messages using the `public Task SendAsync(Message message)` method from the queue client and compare the performance using the versions 4.1.1 and 5.1.2.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ServiceBus 5.1.2
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure AppService

**Comment by jsquire** [comment]
//fyi: @JoshLove-msft

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@evadelnuevo was this against a standard or premium namespace?

**Comment by evadelnuevo** [comment]
@axisc It's against a standard namespace

**Comment by axisc** [comment]
@evadelnuevo it's possible that the degradation may be due to reasons unrelated to the client library.

Can I request you to run the same workload (with old and new library) against a premium namespace?

**Comment by evadelnuevo** [comment]
@axisc Our load tests started to fail after a commit that only updated the azure service bus library. We tried deploying an older version and they succeeded. We also tested our latest version from master but reverting that commit, that's why we doubt that the problem is not related to the library.

Unfortunately the option to upgrade the namespace to premium is not available in the portal for us:

![premium tier](https://user-images.githubusercontent.com/28533791/114667427-c0319300-9cff-11eb-8a16-3651b3db4136.PNG)

**Comment by axisc** [comment]
Checking against the premium tier is the best way to get a comparable dedicated setup each time.

How many times did you test it out against standard and see your load tests failing? It's best to try it multiple times before we consider digging further.
Also, and more importantly, we don't make any SLA guarantees on send or receive latency, so I'd recommend avoiding having your business logic depend on any observed latency.

**Comment by evadelnuevo** [comment]
Our load tests run daily after deploying master to our development environment, and we also tested this manually several times. According to the Test failure report from VSO, they have failed 20 times after we deployed the version with the latest service bus library:
![image](https://user-images.githubusercontent.com/28533791/114832666-073a8980-9dcf-11eb-9b09-6cdeb081663c.png)

**Comment by axisc** [comment]
@evadelnuevo  what is the criteria for failure?

**Comment by evadelnuevo** [comment]
The load tests make lots of calls to one of our API methods, simulating multiple callbacks from another API. That method only reads the request and puts a message in the azure service bus queue.
The criteria for the failure is that the median of the response time is greater than 1300 ms

**Comment by evadelnuevo** [comment]
I'll close the issue as we have requested help from Microsoft Premium Support. Many thanks for your time.
