### ISSUE TITLE
[Storage] Figure out why live tests fail with OOM on net461

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#20301]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=837569&view=ms.vss-test-web.build-test-results-tab&runId=18242910&resultId=100885&paneView=debug

**Comment by kasobol-msft** [comment]
![image](https://user-images.githubusercontent.com/61715331/114447915-c7359580-9b87-11eb-8d53-3da893eceecc.png)

**Comment by benbp** [comment]
If you DO need to skip net461, you can add a regex exclude filter to your tests.yml parameters:

```
parameters:
  MatrixFilters:
    - TestTargetFramework=^(?!net461)
```

**Comment by kasobol-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/20324
