### ISSUE TITLE
[BUG] Misleading error message when sending an EventGrid event

### ISSUE THREAD

**Issue by garrm** [Azure/azure-sdk-for-net#20332]
**Describe the bug**
When sending a message for EventGrid and supplying an invalid type (an object instance in my case), the following error message is returned:

```Attribute values must be of type bool, byte, int, Uri, DateTime, or DateTimeOffset.```

This was somewhat concerning that it was so narrow and wouldn't meet my needs. However, looking at the source code I found this switch:

```csharp
            // https://github.com/cloudevents/spec/blob/v1.0/spec.md#type-system
            switch (value)
            {
                case string:
                case byte[]:
                case ReadOnlyMemory<byte>:
                case int:
                case bool:
                case Uri:
                case DateTime:
                case DateTimeOffset:
                    return;
                default:
                    throw new ArgumentException($"Values of type {value.GetType()} are not supported. " +
                        "Attribute values must be of type bool, byte, int, Uri, DateTime, or DateTimeOffset.");
            }
```
As can be seen the error message doesn't match the actual values that are acceptable, most notably `string`.

**Expected behavior**
Error message should include all valid types

**Actual behavior (include Exception or Stack Trace)**
Doesn't include all valid types

**To Reproduce**
Send a message with an ExtensionAttributes
`cloudEvent.ExtensionAttributes.Add("metadata", <object instance>);`

**Environment:**
Library version: 4.1.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
