### ISSUE TITLE
Consider switching all tests to run in 64 bit mode

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#20338]
Currently, .NET Framework tests are running in 32-bit mode. This was unexpected to me.

We should either add an additional x64 test configuration or switch the default.

**Comment by pakrym** [comment]
@weshaggard what do you think?

**Comment by weshaggard** [comment]
I don't think we are configuring this anywhere currently so I suspect 32-bit is the default mode. I don't have any problems with switching the default to 64-bit as I don't think there is enough value to run a mix at this point at least.
