### ISSUE TITLE
[QUERY] Correlation information in DiagnosticSource event ServiceBusProcessor.ProcessMessage.Start

### ISSUE THREAD

**Issue by mangeg** [Azure/azure-sdk-for-net#20349]
**Query/Question**

When implementing OpenTelemetry instrumentation for the Azure.Messaging.ServiceBus SDK I have run into a a problem regarding correlation-id handling.
When consuming the DiagnosticListener with name **Azure.Messaging.ServiceBus** and the event **ServiceBusProcessor.ProcessMessage.Start** the correlation information has not yet been set on the DiagnosticActivity. In the code the DiagnosticActivity is first started, triggering the Start-event, and then after the correlation data is set with DiagnosticScope.SetMessageData in the form of a linked Activity.
When handling the event it is then not possible to set the parent trace id in the Activity to sent to OpenTelemetry as the linked activity does not exist yet.

One way to solve it is to send the OpenTelemetry tracing from the ServiceBusProcessor.ProcessMessage.Stop event as the Activity.Current then has linked activity containing the correlation-id/trace-id. But unsure if that is the way to go.

Is there any reason that the correlation information is not set before the DiagnosticScope.Start is invoked? That is to reverse the order of Start and SetMessageData.

[https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs#L118-L120](https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs#L118-L120)

**Environment:**
 Azure.Messaging.ServiceBus 7.1.1

**Comment by jsquire** [comment]
//cc: @pakrym

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by JoshLove-msft** [comment]
I think it is a reasonable expectation that the message data would be included before the start of the scope. @jsquire do you know how this is handled in Event Hubs?

**Comment by jsquire** [comment]
> I think it is a reasonable expectation that the message data would be included before the start of the scope. @jsquire do you know how this is handled in Event Hubs?

Event Hubs reads the diagnostic identifier from the event and creates the link before starting the scope.
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L541-L562

**Comment by JoshLove-msft** [comment]
@mangeg thanks for filing the issue, we will get this fixed and we also accept contributions 😄
