### ISSUE TITLE
[FEATURE REQ] Azure Search Geo.Distance in Select result

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#20350]
Currently, we can filter or sort Azure Search documents by geo.distance but not able to get the distance in the Select result. There is a UserVoice request at https://feedback.azure.com/forums/263029-azure-search/suggestions/17760211-support-geo-distance-in-select-result to add Geo.Distance in Select result. Azure Cosmos Db supports returning distance between two points in Select query so it would be great if we can implement the same in Azure Search too.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Mohit-Chakraborty** [comment]
@ssghoda - this feedback is best addressed by the Search service team.
I see there has been engagement from the team on https://feedback.azure.com. That is the best forum for this request. I suggest you continue engaging there.

**Comment by ssghoda** [comment]
@Mohit-Chakraborty Thanks for your response. I had already found that as a request https://feedback.azure.com/forums/263029-azure-search/suggestions/17760211-support-geo-distance-in-select-result and upvoted it but there was no recent development there so wanted to draw your attention here. :)

**Comment by Mohit-Chakraborty** [comment]
Understood. I just remembered that a better forum to engage with the Search service team would be on SO (issues tagged with 'azure-cognitive-search').
Please ask on https://stackoverflow.com/questions/tagged/azure-cognitive-search.
