### ISSUE TITLE
This setting will help prevent Event Based Triggers from Triggering twice

### ISSUE THREAD

**Issue by aodugga** [Azure/azure-sdk-for-net#20351]
Hi Team,

Recently, my customer had some issues where their event based trigger for ADF was triggering the pipeline twice. Upon closer inspection, we saw that two events were sent to ADF from Azure Storage, once then zero bytes blob was created and again when the payload was appended. 

Would it be possible to add a note here on this page to explain this scenario please and why this setting was introduced? 
Feel free to ping me for any details.

Kind Regards,
Aoife

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75e3f83d-2bd2-646b-40e0-fc07c0c68dcd
* Version Independent ID: d1e01995-a29e-6ed4-d645-977e2abaab8c
* Content: [BlobEventsTrigger.IgnoreEmptyBlobs Property (Microsoft.Azure.Management.DataFactory.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.blobeventstrigger.ignoreemptyblobs?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.DataFactory.Models/BlobEventsTrigger.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.DataFactory.Models/BlobEventsTrigger.xml)
* Service: **data-factory**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by seanmcc-msft** [comment]
@aodugga, what is ADF?  What is the pipeline you are referring to?  More context would be great.

-Sean

**Comment by shawnxzq** [comment]
@aodugga This is not related to API & SDK & PS issues, could you please raise support ticket for your issue? Thanks a lot!

**Comment by shawnxzq** [comment]
@aodugga Have you got the chance to raise support case? If so, please help close the issue here, thx!

**Comment by shawnxzq** [comment]
@aodugga Thanks for confirm and good to know issue resolved, you can close the issue directly if no more help needed, thanks!

@jsquire I can't close this issue, could you please give me the permission or help on this? Thanks!
