### ISSUE TITLE
Create AzureApplicationCredential

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#20364]
This issue is to track the design and implementation of the `AzureImplementationCredential` for applications calling service APIs not suited for `DefaultAzureCredential`. Details can be found [here](https://gist.github.com/9793dbc036d16708fb7d8fe411fe0f1f)

**Comment by joshfree** [comment]
Related PR: https://github.com/Azure/azure-sdk-for-python/pull/19403

**Comment by joshfree** [comment]
@schaabs could you update this issue please?
