### ISSUE TITLE
[FEATURE REQ] Make Service Version selection for testing flexible

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#20388]
As a dev who often interacts with Storage SDK test suite I'd like to:
- Improve VS test runner experience. I don't want to be shown cartesian product of all SVs and sync/async options. What matters to me is latest version I run live tests with and version that I use in CI builds (can be latest live but can be different).
- I don't like reports and logs in pipelines that are bloated with "Skipping ...". If we're spinning up pipeline that is expected to test some service versions I don't want to see report that tells me 10% of tests succeeded and 90% were skipped. Can we filter out service versions early in the process so they just don't show up?
- Now that we have "test matrix" I'd like to be able to specify service versions outside of the test code. I.e. I'd like to create sparse test matrix with dimensions (OS, service version, net framework) and run it weekly. I want each SV to run on separate agent in separate jobs to parallelize execution and make the run as fast as it can be. Which means there should be a way to specify "relevant service versions" as environment configuration somehow. **(I think this is most important as we disabled old service version testing "temporarily")**

Related items:
https://github.com/Azure/azure-sdk-for-net/pull/20357
https://github.com/Azure/azure-sdk-for-net/pull/20387
https://github.com/Azure/azure-sdk-for-net/issues/20386
https://github.com/Azure/azure-sdk/issues/2025

FYI @benbp @pakrym @seanmcc-msft

**Comment by pakrym** [comment]
cc @JoshLove-msft @maririos

**Comment by seanmcc-msft** [comment]
Unfortunately, the storage tests are basically unrunnable locally at this point in playback mode.  Blobs on its own has over 50,000 tests, almost all of which skipped.  In playback mode, the test running just sits there and spins for me.

**Comment by JoshLove-msft** [comment]
Seems like https://github.com/nunit/nunit/pull/3787 would help with the Test Discovery perf at least.

**Comment by kasobol-msft** [comment]
@JoshLove-msft That NUnit fix will address largest share of pain.

However, navigating storage tests in VS test explorer is not great when 80% of the tree is ignored/inactive - involves some amount of scrolling (or big screen...) and cognitive load to pick right group to expand. Would be great if this could be addressed as well.

It's lesser annoyance than perf problem, but the pain is real:
![image](https://user-images.githubusercontent.com/61715331/114918959-8aaea780-9ddc-11eb-8d46-2ad331a67f05.png)

**Comment by pakrym** [comment]
I think this is done in https://github.com/Azure/azure-sdk-for-net/pull/20463
