### ISSUE TITLE
[Service Bus] Sample needed for peeking messages

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#20389]
https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azuremessagingservicebus-samples/ is the list of samples available for the Azure.Messaging.ServiceBus package. There is no sample for peeking. We need a sample here so that it can be linked from https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-browsing

We have samples for Service Bus SDKs in other languages and the older packages for .NET and Java. Just waiting for one for Azure.Messaging.Servicebus to complete the picture

cc @spelluru

**Comment by JoshLove-msft** [comment]
The sample exists, we just need to update the service bus doc to link to https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_HelloWorld.md#peeking-a-message

**Comment by jsquire** [comment]
Closing; peeking is covered in the sending and receiving sample and there has been no customer feedback to indicate that a dedicated sample is needed.
