### ISSUE TITLE
[Storage] Reenable service version testing in weekly runs

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#20386]
We have disabled all service version testing in storage nightly due to stability problem.
Now that we have "test matrix generation" we'd like to have sparse matrix with various versions, OSes and net frameworks running weekly.

Depends on https://github.com/Azure/azure-sdk-for-net/issues/20388

**Comment by benbp** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/20633
