### ISSUE TITLE
[FEATURE REQ]Extension method to help inject TableServiceClient as dependency

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-net#20392]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
[Azure.Data.Tables](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/tables/Azure.Data.Tables#create-the-table-service-client)
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

I'm trying to inject TableServiceClient as a dependency into a .NET Core Web App like below: 
```
services.AddAzureClients(builder =>
            {
                builder.AddServiceBusClient(Configuration.GetSection("ServiceBus"));
                builder.AddBlobServiceClient(Configuration.GetSection("StorageBlob"));
                builder.AddTableServiceClient(Configuration.GetSection("Table"));
            });
```
The `AddServiceBusClient` and `AddBlobserviceClient` methods are fine, but the  `AddTableServiceClient` can't be found. I believe that extension method is missing.

**Comment by jsquire** [comment]
//cc: @pakrym

**Comment by lilyjma** [comment]
Resolved in PR https://github.com/Azure/azure-sdk-for-net/pull/20656
