### ISSUE TITLE
AzurePowerShellCredential can't parse Cloud Shell output

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-for-net#20417]
Cloud Shell's default profile writes to stdout when loaded, producing output like this, which won't parse as JSON:
```
MOTD: Save files to $home/clouddrive for persistence across sessions

{
  "Token": "...",
  "ExpiresOn": "2021-04-13T16:58:50+00:00",
  "TenantId": "72f988bf-86f1-41af-91ab-2d7cd011db47",
  "UserId": "MSI@50342",
  "Type": "Bearer"
}
```

My solution for this and #20317 was to have the credential's embedded script write the output in a consistent, easy to parse format:
```ps
Write-Output "`nazsdk%$($token.Token)%$($token.ExpiresOn.ToUnixTimeSeconds())`n"
```

**Comment by christothes** [comment]
@chlowell I don't think our `AzurePowerShellCredential` uses Cloud Shell. Is there a scenario where it gets invoked somehow when calling az from the local shell?

**Comment by chlowell** [comment]
It's not the credential using Cloud Shell but it being used in Cloud Shell that exposes this problem. I suppose something similar would happen locally if the default profile writes to stdout. The upshot is that it's unsafe in general to assume the output is JSON, or that the credential's embedded script determines the entire output.

**Comment by christothes** [comment]
I switched the format to XML which seems to be consistent across versions and does not format the date in odd ways.

**Comment by christothes** [comment]
> Can you parse as XML a string containing arbitrary content around XML?

No - I think I am misunderstanding the issue. Are there repro steps to encounter this cloud shell issue?

**Comment by chlowell** [comment]
Sure, use the credential in Cloud Shell, or manually do what it does:
```console
$ /bin/sh -c 'pwsh -NonInteractive -EncodedCommand JABFA...' 2>/dev/null

MOTD: Cmdlet help is available: help <cmdlet name>

<Object Type="Microsoft.Azure.Commands.Profile.Models.PSAccessToken"><Property Name="Token" Type="System.String">eyJ0e...</Property><Property Name="ExpiresOn" Type="System.DateTimeOffset">4/15/2021 4:41:31 PM +00:00</Property><Property Name="TenantId" Type="System.String">72f988bf-86f1-41af-91ab-2d7cd011db47</Property><Property Name="UserId" Type="System.String">MSI@50342</Property><Property Name="Type" Type="System.String">Bearer</Property></Object>
```
I should have focused on the general problem here rather than Cloud Shell specifically, which just provides an example. The general problem is that PowerShell may execute a profile before the credential's encoded command. That profile may write to stdout. We therefore can't assume that stdout contains only what the encoded command wrote. We could set `-NoProfile` but that would break the credential in Cloud Shell (because the default profile there sets Azure PowerShell's context) and perhaps in other places (who knows what necessary stuff users have in profiles).
