### ISSUE TITLE
[QUERY] How to use the Microsoft.Azure.Management.Sql.Fluent to pause database

### ISSUE THREAD

**Issue by unruledboy** [Azure/azure-sdk-for-net#20423]
**Query/Question**
I noticed there is a `PauseAsync `in `Microsoft.Azure.Management.Sql.Fluent.DatabasesOperationsExtensions`. And it expects an `IDatabasesOperations`. I googled lots of places: Microsoft.com, github etc., even reading through the source code of the sdk, could not find out what exact object I should pass that implements that interface.

I tried:

`FooIAzure.SqlServers.Inner`

And I tried:

```
var sqlServer = azure.SqlServers.GetByResourceGroup("FooRG", "FooServer");

var sqlDatabase = azure.SqlServers.Databases.GetById("FooDatabase');

sqlDatabase.PauseAsync(); //not the right interface
sqlDatabase.Inner.PauseAsync(); //not the right interface

```

**Environment:**
 - Name and version of the Library package used: [Microsoft.Azure.Management.Fluent 1.37.1] 
 - Hosting platform or OS and .NET runtime version  

> .NET SDK (reflecting any global.json):
>  Version:   5.0.201
>  Commit:    a09bd5c86c
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.17763
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.201\
> 
> Host (useful for support):
>   Version: 5.0.4
>   Commit:  f27d337295
> 
> .NET SDKs installed:
>   2.1.809 [C:\Program Files\dotnet\sdk]
>   5.0.201 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download

 - IDE and version : [Visual Studio 16.9.2]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by unruledboy** [comment]
hi, is there any update on this please?

**Comment by markcowl** [comment]
@yungezz Can you please answer about the usage of this extension method?

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help on this

**Comment by weidongxu-microsoft** [comment]
@unruledboy 
It is .NET extension method. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods

First parameter only means it extends the `IDatabasesOperations` interface.

**Comment by unruledboy** [comment]
@weidongxu-microsoft  I know what extension method is.

I am only asking exactly how to use this API, if you would please look closer to my question above.

To simply put, how do I obtain an instance of `IDatabasesOperations`.

**Comment by weidongxu-microsoft** [comment]
@unruledboy
 
`azure.SqlServers.Manager.Inner.Databases`

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

**Comment by unruledboy** [comment]
> @unruledboy
> 
> `azure.SqlServers.Manager.Inner.Databases`

Hi, when I use that, it gave me this error:

This feature is not available for the selected database's edition (THE-NAME-OF-THE-DATABASE).'

The database is currently on General Purpose: Serverless, Gen5, 6 vCores, which clearly supports database pause/resume.

**Comment by unruledboy** [comment]
> For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
> https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/
> 
> We have also published a few blog posts on why we are doing this:
> https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/
> 
> With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

Sure, I can have a look. thx

**Comment by weidongxu-microsoft** [comment]
@unruledboy

This message is likely from service. It they do not support it, they might have the reason. Some google result, but might be not very up-to-date https://www.sqlservercentral.com/forums/topic/can-an-azure-sql-database-be-paused

If you have the logging https://github.com/Azure/azure-libraries-for-net#logging, we can involve service team, if you can paste the response JSON from service.

Note that in Fluent SDK, the "pause" is available for sql warehouse https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Sql/SqlWarehouseImpl.cs#L33-L37

**Comment by unruledboy** [comment]
Hi,

Right, so this is only for Azure SQL warehouse only, NOT for serverless tier of Azure SQL database? Is there one API for this product edition? Happy to use any API that works.

**Comment by weidongxu-microsoft** [comment]
@unruledboy 

If it is not supported by sql service, there is no API that works.

The next thing near it might be "auto-pause delay" when create/update the sql database. However it is not available in Fluent SDK.
Likely you need to wait for the new generation SDK (I believe will be preview on June or July).

**Comment by unruledboy** [comment]
Hi @weidongxu-microsoft  I do notice there is a setting, but in Azure Portal minimal is required to use 1 hour, cannot be less than that, like 5 minute.
