### ISSUE TITLE
Can't set a filter rule with the ApplicationProperties of a CorrelationRuleFilter() property

### ISSUE THREAD

**Issue by olakusibe** [Azure/azure-sdk-for-net#20424]
It seems the ApplicationProperties can only be 'get' and it is not possible to set user specific rule filter on CorrelationRuleFilter().

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bde65e2b-a5f5-0c7c-6290-d2be5ae3322e
* Version Independent ID: 040613ea-f19e-e174-baac-39c0608efa9f
* Content: [CorrelationRuleFilter Class (Azure.Messaging.ServiceBus.Administration) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.correlationrulefilter?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.ServiceBus.Administration/CorrelationRuleFilter.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus.Administration/CorrelationRuleFilter.xml)
* Service: **azure**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @olakusibe, even though the property is get-only, you can still add key/value pairs to it. Also if using initializer syntax you can do something like:
```cs
var filter = new CorrelationRuleFilter
{
    ApplicationProperties =
    {
        {"propertyName", "value"}
    }
};
```

**Comment by olakusibe** [comment]
Hi @JoshLove-msft , got it now, was doing it wrong, but it would be easy if the [documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-filter-examples) included your examples.

Thanks

**Comment by ramya-rao-a** [comment]
Thanks @olakusibe and @JoshLove-msft 

This is in our list of docs to update for the month.

cc @spelluru, @axisc
