### ISSUE TITLE
[BUG] TelemetryItem tag ai.operation.parentId not set when Activity.Parent is null when Activity.ParentSpanId is defined

### ISSUE THREAD

**Issue by mangeg** [Azure/azure-sdk-for-net#20433]
**Describe the bug**
When starting a new Activity with passing a parent ActivityContext that has ParentSpanId set the Parent property on Activity is null while the ParentSpanId is set.
In the current implementation the Activity.ParentSpanId is not used and that results in the TelemetryItem not having the tag ai.operation.parentId set.

Examples when this happens is if one or more activities are not part of the ActivitySource that is being monitored. Then the started activities has the parent set manually from ActivityContext to maintain the link between them regarding parents.

**Expected behavior**
The ai.operation.parentId tag should be set when Activity.ParentSpanId is set

**Actual behavior (include Exception or Stack Trace)**
The ai.operation.parentId is not set when the Activity is created with a ActivityContext passed as the Parent property is null

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a ActivitySource
2. Start a Activity from the ActivitySource
3. Start another Activity from the ActivitySource but this time pass a ActivityContext with the TraceId and SpanId set to the previous Activity's TraceId and SpanId
4. When transmitted the 2nd Activity produces a TelemetryItem with ai.operation.id set but without ai.operation.parentId set.

**Environment:**
 - Name and version of the Library package used: Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
