### ISSUE TITLE
Consider building samples with SNIPPET preprocessor directive defined 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#20432]
To verify that whatever gets embedded into READMEs and XML docs builds.

**Comment by AlexGhiondea** [comment]
@pakrym isn't there a build that will validate this already?

**Comment by pakrym** [comment]
Nope.

**Comment by AlexGhiondea** [comment]
Then we should do this 🙂.

**Comment by heaths** [comment]
Not building with `SNIPPET` lead to a syntax error in snippets, fixed by PR #20432. @chidozieononiwu @weshaggard any problems with adding a step to just build with `SNIPPET` defined? Perhaps as part of the Analyze stage since it is doc-related?

**Comment by weshaggard** [comment]
Do we need another step? Couldn't it just happen as part of the test build?

**Comment by weshaggard** [comment]
OK we can do the build where it makes sense. Ideally it would be enabled in another build but if there isn't one, we can enable then we can add a new one.

**Comment by heaths** [comment]
I'm working on a solution and the changes to the _eng_ directory are fairly small, but the fallout is massive. In Key Vault I made a bunch of changes - minimal as possible to make the code easier to maintain - to just make it compile with the assumption that nothing in scope with only `SNIPPET` would be built. I imagine many other devs did the same thing. This might be something we instead need to work toward, or maybe it's just worth it to be more conscious of the problem in extracted snippets during review.

/cc @AlexGhiondea
