### ISSUE TITLE
[FEATURE REQ] Test Framework: All environment variable driven setting should be also configurable via .runsettings files.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#20443]
As a dev running SDK tests I have mixed experience configuring my test runs.
I.e. 
I can use env variable or runsettings file to configure live/recorded/playback mode. See https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/core/Azure.Core.TestFramework/src/RecordedTestUtilities.cs#L15

But to disable "auto re-recording" I can only use env variable (which is not well defined/scoped btw, i.e. could be separate switch). https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/core/Azure.Core.TestFramework/src/RecordedTestAttribute.cs#L46

Could we please make sure that all settings added to test framework are configurable via env variables and runsettings files?
The later is much better experience when using VS as it doesn't need IDE restart.

**Comment by JoshLove-msft** [comment]
> But to disable "auto re-recording" I can only use env variable (which is not well defined/scoped btw, i.e. could be separate switch).

Agreed that we would probably want a separate setting for this - I don't think we would want IsRunningInCI to be configurable via runsettings.

**Comment by kasobol-msft** [comment]
The `IsRunningInCI` is not the best example. The point I'm trying to make is that tests are scattered with calls to environment (see [search](https://github.com/Azure/azure-sdk-for-net/search?q=GetEnvironmentVariable)). 
It would be great if there was some pattern/rule established that settings that matter both in pipelines and in local dev env (VS) that takes advantage of IDE (runnsettings). 
Maybe better example is that I'd like to control [WebJobsTestEnvironment](https://github.com/Azure/azure-sdk-for-net/blob/82c67372eaeebc69340328e70bd9c61f68588c0b/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/tests/WebJobsTestEnvironment.cs#L1-L14) via runnsettings rather than restart VS.

**Comment by JoshLove-msft** [comment]
I'm not sure we would want to allow secrets to be read from runsettings as this seems likely to lead to leaked credentials.

**Comment by kasobol-msft** [comment]
That's a good point. Maybe we could do something similar to what App Services/Azure Functions do. I.e. when you create Azure Function project from template it creates appsettings.local.json to define settings including secrets but that file is on .gitignore so never gets checked in.

**Comment by pakrym** [comment]
I think this is done in https://github.com/Azure/azure-sdk-for-net/pull/20463
