### ISSUE TITLE
[QUERY]

### ISSUE THREAD

**Issue by amitSahu9** [Azure/azure-sdk-for-net#20461]
**Query/Question**
How can we help?

Can i use azure authentication for a custom application in which i want to authenticate without interacting with the UI and also perform the MFA if enabled.

Windows 10
using C# application

**Comment by jsquire** [comment]
Hi @amitSahu9.  Apologies, but I'm not sure how to find the right folks to assist.  

From the context of your issue, it seems as if you may be asking about the capabilities of Azure product offerings and not one of the SDKs from this repository.   Unfortunately, if that is the case, we're not able to offer assistance.  I'd recommend that you take a look at the product documentation for [Azrue AD](https://azure.microsoft.com/en-us/services/active-directory/#get-started) and [Azure AD B2C](https://azure.microsoft.com/en-us/services/active-directory/external-identities/b2c/#getting-started).  

If I'm misunderstanding and you're looking for help with the Azure SDK for .NET, can you help me understand which library you're working with and offer a bit more context about your scenario?

**Comment by amitSahu9** [comment]
> Hi @amitSahu9. Apologies, but I'm not sure how to find the right folks to assist.
> 
> From the context of your issue, it seems as if you may be asking about the capabilities of Azure product offerings and not one of the libraries from this repository. Unfortunately, if that is the case, we're not able to offer assistance. I'd recommend that you take a look at the product documentation for [Azrue AD](https://azure.microsoft.com/en-us/services/active-directory/#get-started) and [Azure AD B2C](https://azure.microsoft.com/en-us/services/active-directory/external-identities/b2c/#getting-started).
> 
> If I'm misunderstanding and you're looking for help with the Azure SDK for .NET, can you help me understand which library you're working with and offer a bit more context about your scenario?

Hi @jsquire i want to user azure authentication without interacting with the UI , i mean is there an end point where i can pass the username and password and after that i can perform Multifactor Authentication with the UI . Please let me know if it is possible.

**Comment by jsquire** [comment]
Hi @amitSahu9.  Unfortunately, this isn't an area where the Azure SDK team can assist.   You are most likely to find what you're looking for as part of the Azure Active Directory offerings, though I cannot speak to whether they meet your needs.  

I'd recommend taking a look at the product documentation for [Azrue AD](https://azure.microsoft.com/en-us/services/active-directory/#get-started) and [Azure AD B2C](https://azure.microsoft.com/en-us/services/active-directory/external-identities/b2c/#getting-started).  They'll discuss the features offered by each and offer quick-starts to help you explore their capabilities.

I'm going to close this out; please feel free to reach out with any questions or feedback pertaining to the Azure SDK libraries as you build out your application.
