### ISSUE TITLE
Prototype Operations class discovery in .Net clients

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2046]
### Description

.Net azure clients should have a central class (called AzureClient) that can bring together all the generated client operations in an app domain, and provide a single place where the http client is created, credentials and subscription are applied, and incorporating simple methods for login.

Create prototypes for a few options, including
- Simple, generic methods for creating clients from the central client
- Extension methods for getting operations classes from the generated clients in the app domain (added to client generation)
- Also consider how to model the SmartOperations and the subscriptions client in this infrastructure.
-  As an extension, consider adding some conveniences to the central client, including 
  - default resource group
  - extensible default configuration settings (default storage account, other rp-specific defaults)
  - smart operations

**Comment by brjohnstmsft** [comment]
Is this for management clients only?

**Comment by markcowl** [comment]
@brjohnstmsft To start with.  The design shoudl allow discovering any AutoRest client library added to the AppDomain

**Comment by brjohnstmsft** [comment]
I ask because many of the requirements above do not apply to a data plane SDK. Credentials may work differently, there is no inherent notion of subscription ID, etc.

**Comment by markcowl** [comment]
@brjohnstmsft The design is loosely coupled and opt-in, so clients need not include the extension required for discovery.  See: https://github.com/Azure/azure-sdk-for-net/pull/2472 for the latest design

**Comment by Petermarcu** [comment]
This is addressed in Azure.Core
