### ISSUE TITLE
User Assigned Managed Identity + ACI + Azure.Identity: ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/azure-sdk-for-net#20462]
Is it supported to use ManagedIdentityCredential to access ServiceBus? Is there any setup needed? Please help take a look. 

Here's the details:

### Packages
```xml
    <PackageReference Include="Azure.Identity" Version="1.3.0" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.1.2" />
```

Container: `mcr.microsoft.com/dotnet/aspnet:3.1`

### Code
```c#
ManagedIdentityCredential cred = new ManagedIdentityCredential(_authority.StampManagedIdentityClientId);
ServiceBusClient sbClient = new ServiceBusClient(sbNamespace, cred);
```

### Some investigation
1. Curl 169.254.169.254 works, for example
  ```bash
  curl 'http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fvault.azure.net' -H Metadata:true -s
  ```
Returns the access token successfully from within the running container;

2. There no variables set any endpoints (checking by using `printenv`).

3. Checked the source code a bit, it seems like some ENDPOINTS are needed. I tried to setup on manually in resource explorer for the container instance:

  ```jsonc
            {
              "name": "IDENTITY_ENDPOINT",
              "value": "http://169.254.169.254"
            },
            {
              "name": "IDENTITY_HEADER",
              "value": "Metadata:true"
            }
  ```

That got me another error:

```bash
Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 404 (Not Found)

Content:
404 page not found


Headers:
X-Content-Type-Options: REDACTED
Date: Fri, 16 Apr 2021 05:52:12 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 19

 ---> Azure.RequestFailedException: Service request failed.
Status: 404 (Not Found)

Content:
404 page not found
...
```

**Comment by jsquire** [comment]
Hi @xiaomi7732.  Thank you for your feedback and we regret that you're experiencing difficulties.  With respect to Service Bus, both the service and the client library support Managed Identity.   I can't speak to what setup may be required for the namespace, but your snippet for instantiating the client looks correct to me.

I've looped in the folks that represent Azure.Identity, as they're best able to assist with any nuances around setup and use of the `ManagedIdentityCredential`.

**Comment by christothes** [comment]
Hi @xiaomi7732 - Can you clarify what error you were getting before making any configuration changes using the code below?

```c#
ManagedIdentityCredential cred = new ManagedIdentityCredential(_authority.StampManagedIdentityClientId);
ServiceBusClient sbClient = new ServiceBusClient(sbNamespace, cred);
```

One possible problem you could be hitting is that the IMDS endpoint can sometimes take a few seconds to initialize in container. You could validate this by reproducing this with [logging enabled](https://github.com/Azure/azure-sdk-for-net/blob/e4c4e7f3985e73fb1e0ad56af1ba6bccf5bfe867/sdk/core/Azure.Core/samples/Diagnostics.md). The output should indicate what error was encountered and whether the IMDS endpoint was found.

**Comment by xiaomi7732** [comment]
Hi @christothes Thanks for the asking. The initial exception was:

```bash
ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
```

I know about the issue that it could takes a few for the IMDS to show up in ACI and I don't believe it was the cause here because my service is a message pump that keeps trying to fetch a message out of a sb topic/sub - it will keep retrying when it failed.

Now that I look into it more, there are something that I noticed for what it worth:

### What I tried but does NOT work

* The scopes on the `TokenRequestContext` comes with '/.default' (form ADAL?), for example

```csharp
"https://servicebus.azure.net/.default" 
```

* To invoke the IMDS endpoint, the resource query needs to be:

```csharp
resource=UrlEncoded("https://servicebus.azure.net/")   // No './default'
```
I haven't got a chance to look into the SDK code to see if that is handled - derive and overriding GetTokenAsync for ManagedIdentityCredential to remove the `.default` from the TokenRequestContext didn't work. I guess that is not it.

### What I tried and worked for me

* I got it work by invoking the endpoint manually so that there's no other issues:

```csharp
using System;
using System.Linq;
using System.Net.Http;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Web;
using Azure.Core;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using Microsoft.TraceManager.Models;

namespace Microsoft.TraceManager.Service
{
    public class ManualManagedIdentityCredential : TokenCredential
    {
        private static readonly string CacheKeyPrefix = new Guid("db9b9f68-223a-4034-be20-4f97bf7e048a").ToString();

        private readonly HttpClient _httpClient;
        private readonly IMemoryCache _memoryCache;
        private readonly JsonSerializerOptions _serializerOptions;
        private readonly ILogger _logger;

        public ManualManagedIdentityCredential(
            HttpClient httpClient,
            IMemoryCache memoryCache,
            JsonSerializerOptions serializerOptions,
            ILogger<ManualManagedIdentityCredential> logger)
        {
            _logger = logger ?? throw new ArgumentNullException(nameof(logger));
            _httpClient = httpClient ?? throw new ArgumentNullException(nameof(httpClient));
            _memoryCache = memoryCache ?? throw new ArgumentNullException(nameof(memoryCache));
            _serializerOptions = serializerOptions ?? throw new ArgumentNullException(nameof(serializerOptions));
        }
        public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
        {
            // Not used.
            _logger.LogDebug("[{method}]{requestContext}", nameof(GetToken), JsonSerializer.Serialize(requestContext));
            throw new NotImplementedException();
        }

        public override async ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
        {
            _logger.LogTrace("[{method}]{requestContext}", nameof(GetToken), JsonSerializer.Serialize(requestContext));

            string resource = string.Join(',', requestContext.Scopes.Select(s => s.Replace(".default", "")));
            if (string.IsNullOrEmpty(resource))
            {
                throw new InvalidOperationException("No target resource for authentication.");
            }

            var cacheKey = GetCacheKey(resource);
            try
            {
                AccessToken accessToken = await _memoryCache.GetOrCreateAsync(cacheKey, GetAccessTokenAsync).ConfigureAwait(false);
                _logger.LogDebug("Access token fetched.");
                _logger.LogTrace("Access token: {accessToken}", accessToken);
                return accessToken;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error getting access token from cache");
                _memoryCache.Remove(cacheKey);
            }
            return default;
        }

        private async Task<AccessToken> GetAccessTokenAsync(ICacheEntry cacheKeyEntry)
        {
            (string Prefix, string Key) entryValue = ((string Prefix, string Key))cacheKeyEntry.Key;
            string resource = entryValue.Key;
            string resourceEncoded = HttpUtility.UrlEncode(resource);
            string targetUrl = $@"http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource={resourceEncoded}";
            Uri identityUri = new UriBuilder(targetUrl).Uri;
            HttpRequestMessage identityRequest = new HttpRequestMessage(HttpMethod.Get, identityUri);
            identityRequest.Headers.TryAddWithoutValidation("Metadata", "true");
            HttpResponseMessage response = await _httpClient.SendAsync(identityRequest).ConfigureAwait(false);
            response.EnsureSuccessStatusCode();
            string responseBody = await response.Content.ReadAsStringAsync();
            ManagedIdentityResponse managedIdentityResponse = JsonSerializer.Deserialize<ManagedIdentityResponse>(responseBody, _serializerOptions);
            cacheKeyEntry.SetAbsoluteExpiration(managedIdentityResponse.Expiry.AddSeconds(-10));
            return new AccessToken(managedIdentityResponse.AccessToken, managedIdentityResponse.Expiry);
        }

        private (string Prefix, string Key) GetCacheKey(string resource)
        {
            return (CacheKeyPrefix, resource);
        }
    }
}
```

**Comment by christothes** [comment]
@xiaomi7732 The credential should work without having to do any manual configuration. Just out of curiosity, does it work if you use the `DefaultAzureCredential` as shown in [this example](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme#specifying-a-user-assigned-managed-identity-with-the-defaultazurecredential)?

**Comment by xiaomi7732** [comment]
@christothes That was my understanding too. If I understand correct, `DefaultAzureCredentical` is just a chain of credentials. For a service deployed to ACI, only managed identity will possibly working. In that sense, how is it different than using `ManagedIdentityCredential` directly? Thanks.

**Comment by christothes** [comment]
It shouldn't be different, other than it constructs the `ManagedIdentityCredential` for you with the client option set from the `ManagedIdentityCredentialOptions`. I don't expect that it will make a difference.  Actually, what would be more interesting is the logging output suggested initially. 

Details on how to enable logging can be found [here.](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md)
