### ISSUE TITLE
[BUG] Azure.Monitor.OpenTelemetry.Exporter - TelemetryItem.Time format does not include milliseconds

### ISSUE THREAD

**Issue by mangeg** [Azure/azure-sdk-for-net#20475]
**Describe the bug**
TelemetryItem.Time is set in a format that does not keep the milliseconds. This results in events in ApplicationInsights appear to have happened simultaneously when they happen within the same second.

**Expected behavior**
The format should be including milliseconds and follow the https://en.wikipedia.org/wiki/ISO_8601#UTC format according the ApplicationInsights API description, ex. 2021-04-16 23:22:25.0660Z.

https://raw.githubusercontent.com/Azure/azure-rest-api-specs/0ae35fd0c27e0f06004d820e75a13c615b9c2e96/specification/applicationinsights/data-plane/Monitor.Exporters/preview/2020-09-15_Preview/swagger.json
_This field must be formatted in UTC ISO 8601 format, with a trailing 'Z'_

**Actual behavior (include Exception or Stack Trace)**
Time is set without milliseconds in a format not according to the API description, ex. 04/16/2021 23:22:25

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. View TelemetryItem.Time property after it has been created by **TelemetryPartA.GetTelemetryItem(Activity activity, Resource resource, string instrumentationKey)**

**Environment:**
 - Name and version of the Library package used: Azure.Monitor.OpenTelemetry.Exporter-1.0.0-beta.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
