### ISSUE TITLE
Prototype error reporting mechanism in .Net clients

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2048]
### Description
- Ensure That ClientRequestID is set (if  not previously set) and recorded for long-running operations
- Ensure that the original RequestId is kept throughout long-running operations
- Ensure that Client Request Id and Request Id are always returned with exceptions (lro and synchronous calls)
- Validate retrieval of service-side logs using client reqquest id and request id

**Comment by Petermarcu** [comment]
@KrzysztofCwalina lets close this if its already covered in Azure.Core.
