### ISSUE TITLE
[QUERY] Configuration of ServiceBusProcessorOptions.MaxAutoLockRenewalDuration property

### ISSUE THREAD

**Issue by EnricoMassone** [Azure/azure-sdk-for-net#20482]
**Query/Question**

We have a web application built with **ASP.NET core 3.1** which is used to dequeue messages from an Azure Service Bus queue and to process them. Message processing is done by using a proper hosted service.
We use **Azure.Messaging.ServiceBus 7.1.1** to interact with the Azure Service Bus queue from our application.

The specifics of how we interact with the queue are the followings:

- we use a `ServiceBusProcessor` instance to process messages
- we employ `ServiceBusReceiveMode.PeekLock` as the read mode
- we set `AutoCompleteMessages` to `true`
- by default we set `MaxConcurrentCalls` to 10 (this is customizable based on the customer and the environment)
- by default we set `MaxAutoLockRenewalDuration` to 10 minutes (this is customizable based on the customer and the environment)

Some of the messages that we receive can take quite a long time to be processed. Sometimes we have observed this error message in our logs: 

`Azure.Messaging.ServiceBus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.`

Based on my understanding, this happens when the message processing takes a long time and the message lock expires **before** the message completion ack is sent to Azure Service Bus by our  `ServiceBusProcessor` instance. Based on this, I'm thinking of changing the default value for `MaxAutoLockRenewalDuration` to something like 20 or 30 minutes. 

Is it safe to increase the value assigned to `MaxAutoLockRenewalDuration` this way ? Is there any issue or drawback in setting huge values for this configuration ? 

**I'm not saying that 30 minutes must be considered a **huge** value, I'm just asking in general for the possible implications of having huge message processing times.**

My current understanding is that **setting huge values for this configuratiuon is harmless and can be done safely if the message processing scenario at hand requires so**. I'm asking just to be sure there isn't any known issue or problem which can arise from that.

Thanks for helping.

Enrico.

**Environment:**
 - Name and version of the Library package used: _Azure.Messaging.ServiceBus 7.1.1_ 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): we are working with _ASP.NET core 3.1_. We build a docker container for the app by using _mcr.microsoft.com/dotnet/core/aspnet:3.1_ as the base image for the runtime container. The docker container is then managed by a kubernetes cluster built by using Azure Kubernetes Service (AKS).
 - IDE and version : Visual Studio Professional 2019 version 16.9.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @EnricoMassone,
I would agree with your understanding of the configuration options. The one thing I would mention is that if the MaxAutoLockRenewalDuration is increased, and you have messages that require that much processing time, then the library will be performing additional renew lock operations which could impact [cost](https://azure.microsoft.com/en-us/pricing/details/service-bus/).

**Comment by EnricoMassone** [comment]
@JoshLove-msft thanks for all the clarifications.
