### ISSUE TITLE
[QUERY][Synapse]What is the correct way to de-serialize Pipeline Run API response to Azure.Analytics.Synapse.Artifacts.Models.PipelineRun

### ISSUE THREAD

**Issue by shbhmpthk** [Azure/azure-sdk-for-net#20487]
**Query/Question**
I am trying to de-serialize a JSON response for PipelineRun into Azure.Analytics.Synapse.Artifacts.Models.PipelineRun .net Type. Since all the constructors and JsonConverter are internal I am getting the error `'Cannot deserialize readonly or fixed size dictionary: Azure.Analytics.Synapse.Artifacts.Models.PipelineRun. Path 'id`. I have tried a lot of combinations, different libraries and searched a lot but couldn't find any relevant document or code. I wonder if that is even possible or those objects can only be instantiated when I am using a synapse client from the same library?

**Environment:**
 - **Name and version of the Library package used:** Azure.Analytics.Synapse.Artifacts - 1.0.0-preview.4
 - **Hosting platform or OS and .NET runtime version** (`dotnet --info` output for .NET Core projects): Windows 10 .netcoreapp3.1
 - **IDE and version**:  Visual Studio 16.9.4

Sample JSON Input: 
```json
{
"id": "/SUBSCRIPTIONS/XYZSubs/RESOURCEGROUPS/XYZRG/PROVIDERS/MICROSOFT.SYNAPSE/WORKSPACES/XYZ/pipelineruns/6c544f5d-2ec6-4467-b23c-d28b1179a2a9",
    "runId": "6c544f5d-2ec6-4467-b23c-d28b1179a2o9",
    "debugRunId": null,
    "runGroupId": "6c544f5d-2ec6-4467-b23c-d28b1179a2a9",
    "pipelineName": "testNestedPipeline",
    "parameters": {},
    "invokedBy": {
        "id": "ed653fa4-6189-47c2-9636-4b69h1fd8c44",
        "name": "ed653fa4-6189-47c2-9636-4b69d1fd9c44",
        "invokedByType": "PipelineActivity",
        "pipelineName": "ParentPipeline",
        "pipelineRunId": "f7cf129bc-c385-48cd-b8ad-407306706be4"
    },
    "runStart": "2021-03-10T05:59:26.5172255Z",
    "runEnd": "2021-03-10T06:01:01.3045391Z",
    "durationInMs": 94787,
    "status": "Succeeded",
    "message": "",
    "lastUpdated": "2021-03-10T06:01:01.3045391Z",
    "annotations": [],
    "runDimension": {},
    "isLatest": true
}
```
.Net Code to DeSerialize:
`Rest.Serialization.SafeJsonConvert.DeserializeObject<PipelineRun>(pipelineRuninfo)`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by chamons** [comment]
Given those model types are internal, I'm not sure you can deserialize without creating a parallel set of objects from the json, which is not great.

We have https://github.com/Azure/autorest.csharp/issues/543 open to provide a path to create these types, but I don't think that will solve your use case.

**Comment by jsquire** [comment]
Given the age of this issue and lack of discussion, I'm going to close this out as addressed.   Please feel free to unresolve if further discussion is needed.
