### ISSUE TITLE
[QUERY] Cannot understand how to remove REDACTED when using AzureEventSourceListener

### ISSUE THREAD

**Issue by fhtino** [Azure/azure-sdk-for-net#20481]
**Query/Question**
I've read page https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md about activating logging.

I used:
```
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
```
Output looks like:
```
Azure-Core: Request [a9113e9a-44fd-48f0-bb8f-45024850e3d9] GET http://127.0.0.1:10002/devstoreaccount1/aaaatest1()?$format=REDACTED&$filter=REDACTED
x-ms-version:REDACTED
DataServiceVersion:REDACTED
.....
```
I do not understand how to remove REDACTED and having full parameters visible. The page mentions `SecretClientOptions options` but it's not clear how to use it with  AzureEventSourceListener.CreateConsoleLogger 

**Environment:**
 - Name and version of the Library package used: Azure.Data.Tables - 12.0.0-beta.7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
The key part is here - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#logging-redacted-headers-and-query-parameters

**Comment by fhtino** [comment]
I'm really sorry but it's not clear - at least for me - how to use `SecretClientOptions options = new . . .`  with `using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Warning);`
I think a small, but complete, example generating "not redacted" logs would be very useful for people interested in the topic.

**Comment by JoshLove-msft** [comment]
So the equivalent for the Tables library is the `TableClientOptions` type. You would use that instead of `SecretClientOptions` from the example, and include the names of any headers and query parameters that you would like to not be redacted. You would then pass your `TableClientOptions` instance into the constructor for the `TableClient`.

```cs
TableClientOptions options = new TableClientOptions()
{
    Diagnostics =
    {
        LoggedHeaderNames = { "x-ms-request-id", "DataServiceVersion" },
        LoggedQueryParameters = { "api-version", "format", "filter" }
    }
};

var client = new TableClient("<connection string>", "<table name>", options);
```

**Comment by fhtino** [comment]
@JoshLove-msft your code works like a charm. Just a suggestion for helping other users like me: I would add your piece of code like an usage example and explain that SecretClientOptions, TableClientOptions , etc. are the classes to work with in the various cases (tables, blobs, vault, etc.).

**Comment by JoshLove-msft** [comment]
Sure, I will do that.
It's also possible that these particular query parameters and headers should be logged by default by having these specified in the `TableClientOptions`, so that users don't have to add these themselves. /cc @christothes
