### ISSUE TITLE
[BUG] Deserializing Issue / FormRecognizer 3.1.0-beta.4 

### ISSUE THREAD

**Issue by LucienUrech** [Azure/azure-sdk-for-net#20495]
**Describe the bug**
In cases where the custom model predicts an empty cell in a "label table", an InvalidOperationException occurs when the library deserializes the result.

**Expected behavior**
No Exception

**Actual behavior (include Exception or Stack Trace)**
System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Null'. at System.Text.Json.JsonElement.EnumerateObject() at Azure.AI.FormRecognizer.Models.FieldValue_internal.DeserializeFieldValue_internal(JsonElement element) at Azure.AI.FormRecognizer.Models.FieldValue_internal.DeserializeFieldValue_internal(JsonElement element) at Azure.AI.FormRecognizer.Models.FieldValue_internal.DeserializeFieldValue_internal(JsonElement element) at Azure.AI.FormRecognizer.Models.DocumentResult.DeserializeDocumentResult(JsonElement element) at Azure.AI.FormRecognizer.Models.AnalyzeResult.DeserializeAnalyzeResult(JsonElement element) at Azure.AI.FormRecognizer.Models.AnalyzeOperationResult.DeserializeAnalyzeOperationResult(JsonElement element) at Azure.AI.FormRecognizer.FormRecognizerRestClient.GetAnalyzeFormResultAsync(Guid modelId, Guid resultId, CancellationToken cancellationToken) at Azure.AI.FormRecognizer.Models.RecognizeCustomFormsOperation.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) at Azure.AI.FormRecognizer.Models.RecognizeCustomFormsOperation.UpdateStatusAsync(CancellationToken cancellationToken) at Azure.Core.OperationHelpers.DefaultWaitForCompletionAsync[TResult](Operation1 operation, TimeSpan pollingInterval, CancellationToken cancellationToken)    at System.Threading.Tasks.ValueTask1.get_Result()

**To Reproduce**

1. Create a custom model which contains a "label table".
2. Analyze a document in which at least one cell in the "label table" has an empty value.

**Environment:**
 - Azure.AI.FormRecognizer 3.1.0-beta.4
 - .Net Core 2.1 / Azure Functions
 - Visual Studio 16.4.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by maririos** [comment]
Thanks @LucienUrech for the information. I was able to repro the issue and I am currently looking into what the proper fix is.
I will keep this issue updated.

**Comment by maririos** [comment]
@LucienUrech
We have fixed the issue you have reported. Thank you for letting us know! 
While this fix is going to be included in our May release, if you are blocked by it, I created a developer package that you could use for now:

•	Package name: Azure.AI.FormRecognizer 3.1.0-alpha.20210422.1
•	Feed with instructions on how to install: https://dev.azure.com/azure-sdk/public/_packaging?_a=package&feed=azure-sdk-for-net&package=Azure.AI.FormRecognizer&protocolType=NuGet&version=3.1.0-alpha.20210422.1&view=overview

Note that this is a developer package that won't be supported. It is meant to unblock you.

Let me know!

**Comment by LucienUrech** [comment]
Hi @maririos 
I installed your package and tested my faulty cases. It works great. Many thanks to you and your team. I am impressed how quickly you solved the problem.

**Comment by maririos** [comment]
So glad to hear! Here is the issue that tracks the May release => https://github.com/Azure/azure-sdk-for-net/issues/19997
Once the package is available on GitHub we will post the link in the issue.

Thanks!
