### ISSUE TITLE
[FEATURE REQ] TableClient constructor that takes a single Uri argument.

### ISSUE THREAD

**Issue by Identifier** [Azure/azure-sdk-for-net#20522]
**Library or service name.**
Azure.Storage.Table
 
**Is your feature request related to a problem? Please describe.**
I'd like to request that we have a constructor to TableClient that takes a single SAS URL, in the same way that Microsoft.WindowsAzure.Storage.Table.CloudTable.cctor(Uri) did. You can do this because Table-level SAS's look like this:

https://STORAGEACCOUNT.table.core.windows.net/TABLENAME?si=ACCESSPOLICY&sv=2020-02-10&sig=sssssssssssssssssssssssssssssssssssssssssss%3D&tn=TABLENAME

So the TableClient can extract out all of the necessary information from the single URL that is given out when the SAS is created. Having a separate parameter for tableName and credentials is confusing when dealing with Table-level SASs.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
