### ISSUE TITLE
"Publishing Events to an Event Grid Topic" sample is incorrect regarding JSON serialization

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-sdk-for-net#20520]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventgrid/Azure.Messaging.EventGrid/samples/Sample1_PublishEventsToTopic.md states:

> EventGridPublisherClient also accepts a set of configuring options through EventGridPublisherClientOptions. For example, specifying a custom serializer used to serialize the event data to JSON:

But the example given after that paragraph is identical to the previous example, i.e. has nothing about `EventGridPublisherClientOptions` nor anything about JSON serialization. `EventGridPublisherClientOptions` itself doesn't seem to have any properties that could affect JSON serialization, unless it's possible to achieve this via a custom `HttpPipelineTransport` - but again, if that is so, it isn't mentioned in this doc or the accompanying source code.

The "Using CloudEvent" section **does** demonstrate using a custom JSON serializer - however, that has nothing to do with the `EventGridPublisherClient`, only the messages being created.

Therefore, not only is the paragraph I've quoted missing an example, it seems to be completely incorrect. If there *is* a way to specify a custom JSON serializer when creating `EventGridPublisherClient`, please can the docs be updated to contain an example thereof; otherwise I suggest that the quoted paragraph and its duplicate example simply be replaced with a reference to the "Using CloudEvent" section.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Thanks for filing the issue @IanKemp. That second paragraph should be deleted. The way that custom JSON serialization works is through using the constructors for EventGridEvent/CloudEvent that take a BinaryData instance. We will get this fixed up.

**Comment by IanKemp** [comment]
> Thanks for filing the issue @IanKemp. That second paragraph should be deleted. The way that custom JSON serialization works is through using the constructors for EventGridEvent/CloudEvent that take a BinaryData instance. We will get this fixed up.

I assume by deleting that errant paragraph and updating the "Using EventGridEvent" section (and example source code) to have both JSON and BinaryData examples, like the "Using CloudEvent" section?

**Comment by JoshLove-msft** [comment]
Correct, we should match what we have for CloudEvent.
