### ISSUE TITLE
[BUG] AzureDatafactory log send to EventHub results in an incorrect JSON Format

### ISSUE THREAD

**Issue by Pierl0** [Azure/azure-sdk-for-net#20521]
I have plug the diagnostic reports to be sent to an event hub (try basic and standard tier). 
I choose only "ActivityRuns", "PipelineRuns", "TriggersRun" because we don't have any SSIS. 

When I access the hub, and and want to see the preview of the log in JSON, there is a message : 
" Source '<unknown_location>' had 1 occurrences of kind 'InputDeserializerError.InvalidData' between processing times '2021-04-20T12:20:35.9747529Z' and '2021-04-20T12:20:35.9747529Z'. Could not deserialize the input event(s) from resource 'Partition: [0], Offset: [114888], SequenceNumber: [62]' as Json. Some possible reasons: 1) Malformed events 2) Input source configured with incorrect serialization format
"

even in CSV, the file is not fomat correctly. 

But if I export in a blob storage, json file is correctly formatted. 

I've put a zip with csv file out from eventhub. 
[eventHub_sample.zip](https://github.com/Azure/azure-sdk-for-net/files/6343441/eventHub_sample.zip)

![image](https://user-images.githubusercontent.com/23164047/115395339-0dbc6d00-a1e4-11eb-9840-cb6a1701cbbf.png)

![image](https://user-images.githubusercontent.com/23164047/115395397-1f057980-a1e4-11eb-9779-a1d411592fbb.png)

![image](https://user-images.githubusercontent.com/23164047/115395479-37759400-a1e4-11eb-82d0-bbede0a935a8.png)

Thanks for your help

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by shawnxzq** [comment]
@Pierl0 This is not related to api/sdk/powershell, please go with support ticket for this kind of issue, then we will have more experts  there to help you, thanks!

**Comment by shawnxzq** [comment]
@Pierl0 Have you got your issue resolved through support system? Thanks!

**Comment by shawnxzq** [comment]
@jsquire We already suggest customer use the right channel to solve the issue and didn't get more response from customer, could you please help close this for now as I don't have the permission? Thanks!

**Comment by jsquire** [comment]
@shawnxzq:  will do.
