### ISSUE TITLE
Microsoft.Azure.KeyVault.Tests playback is slow

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#20535]
I realize that these are T1 tests but the test suite takes ~5m to finish in playback with multiple tests taking 30s. I suspect there is some `Task.Delay(10)` that's not conditioned on the playback mode.

**Comment by pakrym** [comment]
cc @heaths

**Comment by jsquire** [comment]
Given the age of this issue and the deprecation of most of the track one libraries, closing this as stale.  I believe that we're not longer running the T1 tests as part of CI.
