### ISSUE TITLE
Planning and Roadmap Feedback - Second Half 2021

### ISSUE THREAD

**Issue by maggiepint** [Azure/azure-sdk-for-net#20549]
Hello Azure SDK community!

The Azure SDK team is beginning our next planning cycle as part of Azure's twice a year planning process. As a part of this effort, we want to hear from you about what new features and services you are most interested in having as part of the New SDK. In general, we can separate requests into two categories: 

1. Feature requests for various aspects of the SDK
2. Requests to move Azure services onto the new SDK paradigm

We would love to hear your thoughts on both!

There are three ways you can contribute feedback:

1. Browse existing issues labeled `feature-request` in [this repository](https://github.com/Azure/azure-sdk-for-net/issues?q=is%3Aissue+is%3Aopen+label%3Afeature-request). Use the thumbs up (+1) emoji to give us your indication it's a high priority for you. 
2. Reply to this issue with comments on new services and features you are looking for. 
3. Upvote comments in this thread using the thumbs up (+1) emoji.

Note: Being specific with your use case and sample code. The more information you can give us, the more likely we are to take your request.

## Please do not create new issues for new service requests - instead, reply inline.

We will be reviewing community feedback and incorporating it into the planning process starting May 10th 2021.

**Comment by pacorreia** [comment]
hi @maggiepint,

First of all amazing work being done! I've a specific question regarding Microsoft.Azure.WebJobs.Extensions.Storage.Blobs version 5.0.0

Is there an estimate for the first stable release? 2nd quarter of 2021?

Many thanks

**Comment by TechWatching** [comment]
I really like the new Azure SDKs, consistent, easy to use, easy to unit test... I would really to have that with the Azure IoT SDK which  currently lack these features (unit testing some parts of it is just not possible).

By the way Comos Db SDK v4 has been in preview for a long long time, it would be great to finally see this version released.

thanks.

**Comment by Mortana89** [comment]
Cosmos SDK V4 here as well, been in preview since Jan 2020! 🧐

**Comment by qub1n** [comment]
1. **True async support**
 It would be great if the library would be completely asynchronous, currently there are several places which looks like sync, but are in reality async in background and such call block threads. This is a performance issue. For example IVirtualMachine.GetPrimaryNetworkInterface.  I can live even with breaking changes here.

Please do a audit and search for all places which contains Task.Result or similar expressions and replace those with async version.

**Comment by qub1n** [comment]
It would be nice to add support for SQL telemetry endpoint once SQL team finish it. Please contact Alain Dormehl from Microsoft to get more info.

**Comment by qub1n** [comment]
Please add support for [Azure Retail Pricelist](https://docs.microsoft.com/en-us/rest/api/cost-management/retail-prices/azure-retail-prices)

**Comment by scottaddie** [comment]
@qub1n Thank you for your input! Regarding your async request, full async support is provided for .NET 5.0 where the HTTP stack is available. You mentioned `IVirtualMachine.GetPrimaryNetworkInterface` as an example of a method. Can you please provide a few other examples and/or relevant code samples? I'd like to make sure the team fully understands before getting this work prioritized.

**Comment by gethari** [comment]
Hi @maggiepint kudos to the team for all the support. I need a clarification. Assume I have a ton of ARM Templates and I have to deploy them. The deployment happens via REST API from our application.

Take [this example](https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template) on the sample project the main dependency is `Microsoft.Azure.Management.Fluent`

But this assembly depends on a lot of other assemblies which I won't need or use. Is there any other way I can do something like this with any other assembly ?

```csharp
azure.Deployments.Define(deploymentName).WithExistingResourceGroup(request.ResourceGroupName)
.WithTemplate(templateJson)
.WithParameters(parametersJson)
.WithMode(DeploymentMode.Incremental).BeginCreate();
```

![image](https://user-images.githubusercontent.com/20477956/120313305-66a91600-c2f7-11eb-9502-3751de32a700.png)

Thank you

**Comment by jsquire** [comment]
Closing, as the second half of 2021 has passed, and feedback has been recorded.
