### ISSUE TITLE
[QUERY] Why does EventGridPublisherClient not have a backing interface?

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-sdk-for-net#20567]
The old/legacy/superseded `Microsoft.Azure.EventGrid` package exposes the `EventGridClient` class, which is backed by the `IEventGridClient` interface.
The new `Azure.Messaging.EventGrid` package exposes the `EventGridPublisherClient` class that fulfils the same role as `EventGridClient`. However the former lacks a backing interface, which means it cannot be reimplemented, which means it cannot be mocked for testing purposes, which means that code using `EventGridPublisherClient` cannot be tested effectively.

Is there a deliberate reason why this approach was chosen?

**Comment by jsquire** [comment]
Hi @IanKemp.  Thank you for your feedback.   Support for mocking and unit testing is one of the core goals of the new Azure SDKs, and the details of the approach that we use is discussed in the [Azure SDK Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking).  All of the public members of `EventGridPublisherClient` are `virtual` or settable, the class is not sealed, and a parameterless constructor is available to ensure that it is usable with a mocking library such as Moq or FakeItEasy.   

With respect to the lack of interfaces, the Azure SDKs have a goal of strict backwards compatibility with a very high bar for any breaking changes.  With that in mind, the use of an interface makes evolving over time difficult; any change to the public API surface becomes a breaking change, including adding new members.  While default interface implementation makes this easier, they're not supported in all of the frameworks that we target.  As a result, we intentionally avoid using interfaces outside of special circumstances.

If you're willing, I'd like to understand a bit more about your statement that the client could not be mocked or tested effectively.  Was there a specific scenario or difficulty that you were running into that we may be able to help with?
