### ISSUE TITLE
Example code is out of date?

### ISSUE THREAD

**Issue by bruce31** [Azure/azure-sdk-for-net#20576]
Cannot find class mentioned in the example
125,256 results for "recovery services backup management client" in Azure SDK for .NET
We couldn't find any results matching "RecoveryServicesBackupManagementClient"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f36ab87-a10d-8f30-35a7-1a7c02cee54c
* Version Independent ID: b9180df8-0292-e2da-e052-b78a216c40fc
* Content: [Azure Recovery Services and Backup libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/recovery-services)
* Content Source: [api/overview/azure/recovery-services.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/recovery-services.md)
* Service: **backup**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by bruce31** [comment]
Please can all example code include the namespaces of any classes used

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by pvrk** [comment]
@pratimaupadhyay02: can you please check this?

**Comment by adityabalaji-msft** [comment]
The class name is actually "RecoveryServicesBackupClient". We will update the example code to reflect the correct class name

**Comment by adityabalaji-msft** [comment]
Closing the issue as the PR is merged
