### ISSUE TITLE
Unable to send per-request properties to HttpClient handlers for telemetry, logging, and other purposes

### ISSUE THREAD

**Issue by dadeside** [Azure/azure-sdk-for-net#2057]
Currently there is no hook to send custom data/properties per request to the HttpClient (and delegating handlers). There is a need here to send through specific properties and data for the purpose of request logging, gathering telemetry, and instrumenting the individual requests automatically. Adding a hook to add a Key/Value properties collection through per request into the HttpRequestMessage.Properties collection will expose this data to downstream DelegatingHandlers used in the HttpClient.

**Comment by brjohnstmsft** [comment]
@dadeside Requests are already logged. For example, see this code in `DocumentsOperations.DoIndexWithHttpMessagesAsync`:

```csharp
            // Tracing
            bool shouldTrace = ServiceClientTracing.IsEnabled;
            string invocationId = null;
            if (shouldTrace)
            {
                invocationId = ServiceClientTracing.NextInvocationId.ToString();
                Dictionary<string, object> tracingParameters = new Dictionary<string, object>();
                tracingParameters.Add("batch", payload);
                tracingParameters.Add("clientRequestId", clientRequestId);
                tracingParameters.Add("cancellationToken", cancellationToken);
                ServiceClientTracing.Enter(invocationId, this, "Index", tracingParameters);
            }
```

Every operation method contains similar logic. The logging itself is the responsibility of the AutoRest ClientRuntime library for .NET.

Besides logging request data, what other sort of telemetry would you want to flow through to a `DelegatingHandler`?

**Comment by brjohnstmsft** [comment]
@dadeside Closing this issue per our offline discussion. I recommend re-opening it in the Azure/autorest repo.
