### ISSUE TITLE
Explore the Management APIs link is broken

### ISSUE THREAD

**Issue by bruce31** [Azure/azure-sdk-for-net#20575]
Broken link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2f36ab87-a10d-8f30-35a7-1a7c02cee54c
* Version Independent ID: b9180df8-0292-e2da-e052-b78a216c40fc
* Content: [Azure Recovery Services and Backup libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/recovery-services)
* Content Source: [api/overview/azure/recovery-services.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/recovery-services.md)
* Service: **backup**
* GitHub Login: @CamSoper
* Microsoft Alias: **casoper**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by pvrk** [comment]
@pratimaupadhyay02: can you please check this?

**Comment by pvrk** [comment]
submitted the correct [link](https://docs.microsoft.com/dotnet/api/overview/azure/recoveryservicesandbackup/management?view=azure-dotnet) in a [PR](https://github.com/Azure/azure-docs-sdk-dotnet/pull/2004)

**Comment by adityabalaji-msft** [comment]
@bruce31 Can you re-check if the link is working now?

**Comment by adityabalaji-msft** [comment]
Closing this issue as the link is now working
