### ISSUE TITLE
Announcement: Renaming "master" to "main" in this repository

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-for-net#20584]
On the 18th of June, 2021 (PST) we will be renaming the ```master``` branch in this repository to ```main```. When this occurs there will be some disruption to the engineering system as we address any issues that earlier preparations did not address. Please read the following centralized issue for more background on what to expect:

> https://github.com/Azure/azure-sdk/issues/2745

Localized issues in this repository can be discussed here.

# Engineering System Checklist
The following checklist will be executed by a member of the Azure SDK Engineering System team when the branch rename occurs. If errors occur they'll need to be addressed:

- [ ] Ensure repo mirroring is stopped (coordination across repos required).
- [ ] Rename the master branch to main on this repository.
- [ ] Rename the master branch on the ```-pr``` repository.
- [ ] Rename the master branch on the ```azure-sdk``` user's clone of this repository.
- [ ] Rename the master branch on the ```azure-sdk``` user's clone of the ```-pr``` repository.
- [ ] Ensure repo mirroring is started (coordination across repos required).
- [ ] Ensure pipeline generation has been run and pipelines have been updated to correct branch.
- [ ] Submit a PR to ensure that PR validation is executing correctly.
- [ ] Merge PR to ensure that CI triggers are executing correctly.
- [ ] Trigger template release pipeline to ensure end-to-end release process is working correctly.

**Comment by kurtzeborn** [comment]
Removed date from title and updated description with new date.

**Comment by jsquire** [comment]
@mitchdenny, @kurtzeborn:  Since this work has completed, should we consider closing this issue out?

**Comment by mitchdenny** [comment]
Just waiting on some link updates. I'd say next week at the latest.
