### ISSUE TITLE
[BUG] Extension methods calling RegisterClientFactory() pollute the suggestion options in VS

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#20596]
**Describe the bug**
When coding with almost all types in the Azure NET client SDK, the completion options list has ~5 static helper methods that have a very particular use and simply clutter up the list in most cases. See screenshot below for details.

**Expected behavior**
Ideally, these should not show up. Now, I guess with VS picking up on potential options and auto-suggesting the needed 'usings', this problem has become worse. Users don't need to add `using Microsoft.Extensions.Azure;` in their code to be seeing these suggestions.

**Actual behavior (include Exception or Stack Trace)**
See screenshot below to see what users see when looking at the completion list.
It may get worse with more components calling that static method and all those options showing up in the list.

![image](https://user-images.githubusercontent.com/8271806/115769885-eb9c2980-a360-11eb-83d4-2515583ec3bb.png)

**Comment by Mohit-Chakraborty** [comment]
@pakrym , what do you suggest to mitigate this issue?

**Comment by pakrym** [comment]
It's tracked in roslyn https://github.com/dotnet/roslyn/issues/39689

**Comment by Mohit-Chakraborty** [comment]
Thanks for the context.
Seems like we may have to live with this behavior for at least some time.
