### ISSUE TITLE
Refactor ManagedIdentityCredential to send token requests unconditionally

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#20617]
IMDS endpoint discovery causes lots of customer confusion and unpredictable behavior for the `DefaultAzureCredential`. Rather than probing for the IMDS endpoint as part of credential chain evaluation, a token request should be issued immediately and allowed to succeed or fail naturally. This would tend to avoid common issues with endpoint availability timing causing the `ManagedIdentityCredential` to be marked as unavailable prematurely.

**Comment by ryanaitken** [comment]
can i help with this at all? i can submit a PR if that would be useful. if not, is there a rough timeline for when this might be available?

my work laptop is administered remotely, with loads of background services running, so the initial TCP connection to 169.254.169.254 succeeds but the token request fails and throws `AuthenticationFailedException`. im hoping with this change, the   token request will fail gracefully and move onto `VisualStudioCredential`, which will succeed. i am using connectionstrings like `Server=xxxxx.database.windows.net; Authentication=Active Directory Default; Database=testdb;` which i think calls `DefaultAzureCredential`.

**Comment by christothes** [comment]
Hi @ryanaitken - We'll probably get to this in the next couple months. Unfortunately, if you are using SQL to get DefaultAzureCredential functionality, any fix we add here won't affect your scenario until the version of Azure.Identity is updated in the SQL client package.
