### ISSUE TITLE
[FEATURE REQ] Provide system property identifying party that inserted the event

### ISSUE THREAD

**Issue by fabicz** [Azure/azure-sdk-for-net#20618]
We are using `Azure.Messaging.EventHubs` to produce events at various apps and consume them in other app.

We primarily use AAD to authenticate against Event Hubs despite there are other authentication schemas.

Now because there are multiple producers, we would like to verify the authenticity of the producer. This cannot be achieved by adding additional property to event (properties) by producers itself as there is no authority guaranteeing its authenticity.

Because [AAD authentication](https://docs.microsoft.com/en-us/azure/event-hubs/authenticate-application) validation happens server side and is the only authority, we would like the EventHub service to fill [SystemProperties](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.eventdata.systemproperties?view=azure-dotnet) server side with App Id / Tenant Id or other sort of information related to that authentication. 

I don't see an issue to have it only for certain scenarios (AAD app auth).

Is there anything like this possible?

**Comment by jsquire** [comment]
//cc: @sjkwak, @serkantkaraca

**Comment by jsquire** [comment]
Hi @fabicz.  Thank you for your feedback.  This feature would need to happen within the Event Hubs service which owns the system properties tracked by the broker; I've routed this to the service team for consideration.

**Comment by serkantkaraca** [comment]
Azure Event Hubs doesn't support cross-tenant authorization. So the tenant will always be the same as the Event Hubs namespaces's tenant.

Service doesn't allow any app to access an eventhub w/o a prior role based claims assignment. So, all clients accessing the eventhubs are ensured to have permission for the operation they execute.

If you want to secure your namespace even further, you can enable firewall rules or VNET features on your namespace.

Please also feel free to make a feature request at https://feedback.azure.com/forums/911458-event-hubs

**Comment by fabicz** [comment]
Hi @serkantkaraca, I think you misunderstood our ask.

We don't want to put any extra security measure in place to limit partners. They are all valid partners and producers of events. Authentication for all of them is valid. 

What we are looking for is to identify origin of event to identity what partner (AAD auth) sent the event. And we need to for further auditing and validation. 

We could theoretically split that each of our tens of partners will have their own Event Hub / namespace and have consumer side logic to guarantee origin of event based on Event Hub / namespace. But that would loose all the elegancy and benefits of shared infra and create burden at consumer side.

**Comment by serkantkaraca** [comment]
Hi @fabicz 

Can you make a feature request at https://feedback.azure.com/forums/911458-event-hubs ? Better if we track this there. In the meantime, the only way to identify producer is have them add an identifier property in the message itself.

**Comment by fabicz** [comment]
@serkantkaraca Created [feedback](https://feedback.azure.com/forums/911458-event-hubs/suggestions/43296366-identify-producer). Note producer cannot provide this information because we cannot verify the authenticity. We need for auditing to know who created what events in case they would like to fake each others events.

**Comment by jsquire** [comment]
Since tracking for this request has been shifted to the Azure Feedback site, marking as addressed.
