### ISSUE TITLE
[Storage] Fix weekly test run

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#20634]
Looks like adding service versions revealed some potential regressions or wrongly written tests.
Let's investigate that.

Related:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=859255&view=results
https://github.com/Azure/azure-sdk-for-net/pull/20633

**Comment by amnguye** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/21166
