### ISSUE TITLE
[FEATURE REQ] Azure Monitor OpenTelemetry Protocol (OTLP) support

### ISSUE THREAD

**Issue by ma3yta** [Azure/azure-sdk-for-net#20646]
**Library or service name.**
Microsoft.OpenTelemetry.Exporter.AzureMonitor
 
**Is your feature request related to a problem? Please describe.**
Support for OTLP protocol
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
