### ISSUE TITLE
.Net Azure.Data.Tables 12.0.0-beta.7 - Batch issue and Error Message

### ISSUE THREAD

**Issue by middiu** [Azure/azure-sdk-for-net#20649]
Hello guys, 

I'm playing with the .NET Azure.Data.Tables 12.0.0-beta.7 SDK and I'm experiencing some strange behaviour:

I'm trying to insert some custom objects (that implement ITableEntity), using batch and using single operations.
When I use the batch, the app always fails to insert few of them, when I loop over the single object execute a single UpsertEntity operation all the objects are created correctly.

Is there any limitation that I'm not aware of in using TableTransactionalBatch? is there anything wrong with my code below?

Also, what the best way to get a the real error message of the batch? I can only see that one object is not created but I don't know why...

Single operations:

````csharp
List<EXTran> list = ba.OfType<EXTran>().ToList();
                    if (list.Count > 0)
                    {
                        this._logger.LogDebug($"Will save in Table {list.Count} EXTran");
                        foreach (EXTran m in list)
                        {
                            try{
                            Response r = await tableClient.UpsertEntityAsync(m);
                            if (r.Status != 204)
                            {
                                this._logger.LogError($"Problem with RowKey: '{m.RowKey}'");
                            }
                            }catch(Exception e){
                                this._logger.LogError(e.Message);
                            }
                        }
                    }
````

Using batch:

````csharp
List<EXTran> list = ba.OfType<EXTran>().ToList();
                    if (list.Count > 0)
                    {
TableTransactionalBatch batch = tableClient.CreateTransactionalBatch(partitionKey);
                                                batch.AddEntities<EXTran>(list);
                                                TableBatchResponse batchResponse = await batch.SubmitBatchAsync().ConfigureAwait(false);

                                                foreach (EXTran entity in list)
                                                {
                                                    Response r = batchResponse.GetResponseForEntity(entity.RowKey);

                                                    //if (this._logger.IsEnabled(LogLevel.Trace)) this._logger.LogTrace($"The ETag for the entity with RowKey: '{entity.RowKey}' is {r.Headers.ETag}");
                                                    if (r.Status != 204)
                                                    {
                                                        this._logger.LogError($"Problem with RowKey: '{entity.RowKey}'");

                                                        EXTran errObj = list.First(o => o.RowKey == entity.RowKey);
                                                    }
                                                }
}
````

**Environment:**
 - .NET Azure.Data.Tables 12.0.0-beta.7
 - Azure Function App
 - Visual Studio Code 1.55

**Comment by middiu** [comment]
I have some further tests and I've been able to add/upsert ~20.000 items using UpsertEntityAsync in a foreach loop, but as soon as I try to creat ~100 items in a batch it fails.

The code above is still valid.

Thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @middiu - Batch operations are transactional and either succeed or fail 100%. If you are not receiving an exception on the call to `SubmitBatchAsync`, then all operations should have succeeded. See the sample below.

What is the response code for the entity that seems to have failed in your example? Have you verified in storage explorer that it doesn't exist?

https://github.com/Azure/azure-sdk-for-net/blob/b8eafa8eda9b7942a903475e83b706274602c629/sdk/tables/Azure.Data.Tables/tests/TableClientLiveTests.cs#L1130-L1137

**Comment by E-PressSend** [comment]
Hi @christothes 

No exception is raised by `batch.SubmitBatchAsync().ConfigureAwait(false)` but I can observe two things:

1) In Az Storage Explorer I see less records, for example if the batch items are 100, in the Storage Explorer I see only 96-97
2) When I loop over the items and I check the `Response` for each using `GetResponseForEntity` I get the return code 400 BadRequest for the missing ones.

````
foreach (EXTran entity in list) {
   Response r = batchResponse.GetResponseForEntity(entity.RowKey);

    if (r.Status != 204){
        this._logger.LogError($"Problem with RowKey: '{entity.RowKey}'");

         EXTran errObj = list.First(o => o.RowKey == entity.RowKey);
     }
 }
````

Question: should I expect better performance by batch operations compared to single transactions or batch is useful only for consistency (all success or all fails)?

Thanks

**Comment by middiu** [comment]
Hi @christothes

No exception is raised by `batch.SubmitBatchAsync().ConfigureAwait(false)` but I can observe two things:

In Az Storage Explorer I see less records, for example if the batch items are 100, in the Storage Explorer I see only 96-97
When I loop over the items and I check the `Response` for each using `GetResponseForEntity` I get the return code 400 BadRequest for the missing ones.
````
foreach (EXTran entity in list) {
   Response r = batchResponse.GetResponseForEntity(entity.RowKey);

    if (r.Status != 204){
        this._logger.LogError($"Problem with RowKey: '{entity.RowKey}'");

         EXTran errObj = list.First(o => o.RowKey == entity.RowKey);
     }
 }
````
Question: should I expect better performance by batch operations compared to single transactions or batch is useful only for consistency (all success or all fails)?

Thanks

**Comment by christothes** [comment]
> Hi @christothes
> 
> No exception is raised by `batch.SubmitBatchAsync().ConfigureAwait(false)` but I can observe two things:
> 
> In Az Storage Explorer I see less records, for example if the batch items are 100, in the Storage Explorer I see only 96-97
> When I loop over the items and I check the `Response` for each using `GetResponseForEntity` I get the return code 400 BadRequest for the missing ones.

That's very strange. Would it be possible for you to provide some sample code that reproduces the issue end to end? 

> 
> Question: should I expect better performance by batch operations compared to single transactions or batch is useful only for consistency (all success or all fails)?

While performance is not an explicit goal of batch operations, I would expect it to be more efficient than non-parallelized single requests.

**Comment by middiu** [comment]
Hi @christothes 

I've done some further test and the issue i a bit different from what I wrote originally.
You are correct when you say that the batch fails all or success all, in fact none of the transaction is completed.

The problem is that the same items are correctly created using `UpsertEntityAsync` but fail using a batch.

As you can see now I'm trying to add exactly the same list of items in two distinct Tables.
When I run this code, ALL the items are created in the SEQ table, none in the BATCH table.

This is the code that I'm using:
````
            var watch = System.Diagnostics.Stopwatch.StartNew();
            string partitionKey = Guid.NewGuid().ToString();

            List<EXCatMap> list = new List<EXCatMap>();
            for (var i = 0; i <= 200; i++){
                list.Add(new EXCatMap(){
                        id = Guid.NewGuid().ToString(),
                        exCatId = Guid.NewGuid().ToString(),
                        exCatName = "Spider",
                        catTitle = "Spider",
                        exCatItemId = Guid.NewGuid().ToString(),
                        catItemTitle = "Cat",
                        exCatItemName = "Dog",
                        isActive = true,
                        exTranId = Guid.NewGuid().ToString(),
                        tenantId = partitionKey
                });
            }
            
            var tableClientSeq = this.Client.GetTableClient($"{ExternalDataTable}SEQ");
            var tableClientBatch = this.Client.GetTableClient($"{ExternalDataTable}BATCH");

            this._logger.LogInformation($"{list.Count} items");

            /*
            EXCatMap
            */

            var objType = "EXCatMap";
            if (list.Count > 0)
            {
                this._logger.LogDebug($"Will save in Table {list.Count} {objType}s");
                Parallel.ForEach<EXCatMap>(list, parOptions, async m =>
                {
                    try
                    {
                        Response r = await tableClientSeq.UpsertEntityAsync(m);
                        if (r.Status != 204)
                        {
                            this._logger.LogError($"SEQ: Problem with {objType} RowKey: '{m.RowKey}'");
                        }
                    }
                    catch (Exception e)
                    {
                        this._logger.LogError($"Error with SEQ {objType} = {e.Message}");
                    }
                });
            }
            var elapsedSeqSecs = watch.ElapsedMilliseconds / 1000;
            this._logger.LogDebug($"Sequencial done in {elapsedSeqSecs} secs");

            TableTransactionalBatch batch = tableClientBatch.CreateTransactionalBatch(partitionKey);
            foreach (EXCatMap m in list)
            {
                batch.UpsertEntity(m);
            }

            TableBatchResponse batchResponse = await batch.SubmitBatchAsync().ConfigureAwait(false);

            foreach (EXCatMap entity in list)
            {
                Response r = batchResponse.GetResponseForEntity(entity.RowKey);
                if (r.Status != 204)
                {
                    this._logger.LogError($"BATCH: Problem with RowKey: '{entity.RowKey}' - Status : {r.Status} - {r.ReasonPhrase}");
                }
            }
            this._logger.LogDebug($"Batch done");

            watch.Stop();
            var elapsedSecs = watch.ElapsedMilliseconds / 1000;
            this._logger.LogTrace($"{list.Count} items saved in db in {elapsedSecs} seconds");

````

**Comment by christothes** [comment]
Hi @middiu - Thanks for providing the repro. There are two problems here - 
- The batch should not have returned a successful status code (this is something I'll need to investigate with the service team)
- The batch item size limit is 100 items per transaction.

If you reduce your list size to 100 items, the batch will succeed. Below is the output from my results:

```
100 items
Will save in Table 100 EXCatMaps
Sequencial done in 0 secs
Batch done
100 items saved in db in 1 seconds
```

Note: I also had to make some minor tweaks to your entity creation to set a RowKey and PartitionKey value.

**Comment by E-PressSend** [comment]
Thanks @christothes I'll test with 100 items and I will come back to you.

Sorry, I forgot to attach the definition of my EXCatMap, which has already RowKey and PartitionKey.

Does the batch has a limit in request size (1mb for example) as well,  like the Cosmosdb SQL batch?

Should you guys document this limitation somewhere?

Thanks a lot

**Comment by christothes** [comment]
I discovered a bug in the SDK that prevented this from throwing. That should be fixed in the next release.

On the limits, they are documented here for storage endpoints: https://docs.microsoft.com/rest/api/storageservices/performing-entity-group-transactions#requirements-for-entity-group-transactions

**Comment by E-PressSend** [comment]
Hi @christothes 

I've done somefurther test and I found that that the batch keeps failing if I try to upsert different object types in the same batch.

If a batch contains only one single object type it works fine, it I try to tu upsert different object types it fails.

does it sound like a known limitation or a bug?

**Comment by christothes** [comment]
> Hi @christothes
> 
> I've done somefurther test and I found that that the batch keeps failing if I try to upsert different object types in the same batch.
> 
> If a batch contains only one single object type it works fine, it I try to tu upsert different object types it fails.
> 
> does it sound like a known limitation or a bug?

Are the items using the same `PartitionKey` value? Batches cannot span more than one partition.
