### ISSUE TITLE
inconsistent document between README.md and docs.microsoft.com

### ISSUE THREAD

**Issue by herohua** [Azure/azure-sdk-for-net#20647]
The example of `Specifying a user assigned managed identity with the DefaultAzureCredential` should mention that the id can also be specified as env var of `AZURE_CLIENT_ID`. 

See document on the code repo:
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/README.md#specifying-a-user-assigned-managed-identity-with-the-defaultazurecredential

![image](https://user-images.githubusercontent.com/2174068/115982639-476bea00-a5cf-11eb-9792-85d8fd595352.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f73df56-2312-5851-7b59-3dfb766e5f66
* Version Independent ID: 31be349e-063e-6696-bc5f-752c413fa079
* Content: [Azure Identity client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme#specifying-a-user-assigned-managed-identity-with-the-defaultazurecredential)
* Content Source: [api/overview/azure/identity-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/identity-readme.md)
* Service: **identity**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @herohua Thanks for the feedback. Could you clarify which section of the document is missing the statement about `AZURE_CLIENT_ID`? It appears that the one in your example has the text at the bottom.
