### ISSUE TITLE
[FEATURE REQ] ManagedIdentityCredential support user managed identity resource ID

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-sdk-for-net#20651]
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
Previously we're using `Microsoft.Azure.KeyVault`, which is claimed to be deprecated in favor of `Azure.Security.KeyVault.Secrets`.
`Microsoft.Azure.KeyVault` uses `ServiceClientCredentials`
`Azure.Security.KeyVault.Secrets` uses `TokenCredential`.

For `ServiceClientCredentials`, we can create MSI credential with `SdkContext.AzureCredentialsFactory.FromMSI` , it takes [MSILoginInformation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.authentication.msilogininformation?view=azure-dotnet), which accepts resource id of managed identity.

However, for `TokenCredential`, the constructor of [ManagedIdentityCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet) only accepts `clientId` instead of resource id.

We have too many user managed identities in use, whereas the resource IDs could be built-up by convention, but it doesn't work if we have to specify the GUID client id.

How to build up a ManagedIdentityCredential  with user managed identity resource id?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by karataliu** [comment]
@christothes  We have tons of user managed identities, for resource id it is easy to build up by convention:
/<sub>/./<group>./managediidenties/<component>-<region>

But if specifying clientids, we need to store all those magic numbers somewhere, which is great bundle

**Comment by karataliu** [comment]
Say there are 20 components and 60 regions, there will be 1200 user MSIs.
We can have a single function to generate all the resource IDs, but I think no one would like to hard code those 1200 GUIDs somewhere.

There should be no technical issue as `SdkContext.AzureCredentialsFactory.FromMSI` already supports that.

And this would be a blocker for us to switching to Azure.Identity.

What do you think?

**Comment by christothes** [comment]
Hi @karataliu We're considering adding support for this in a future release. Updates will be posted to this issue when I have more information on timelines.

**Comment by karataliu** [comment]
@christothes Thank you. Before that is ready we could not migrate to the new Azure.Identity lib. 
Looking forward to that feature got shipped.

**Comment by karataliu** [comment]
ping. is there any ETA for this feature? passing guid directly is not practical in production use.

**Comment by karataliu** [comment]
ping

**Comment by karataliu** [comment]
ping

**Comment by christothes** [comment]
No ETA - but we will update this work items when there is one.

**Comment by karataliu** [comment]
@christothes  Would you please do an announcement that people should move from `TokenCredential` to ``ServiceClientCredentials`? `TokenCredential` is not ready, since this is such a basic requirement and there is never a fix.

**Comment by apranaseth** [comment]
+1 on this feature. Its easier to use the resource id instead of the client id.

**Comment by sadasant** [comment]
why was this issue closed? we haven’t merged the feature
