### ISSUE TITLE
Azure Key Vault Client ImportKeyAsync passing PFX path and password

### ISSUE THREAD

**Issue by paolorr** [Azure/azure-sdk-for-net#2065]
Is there any extension method similar to Add-AzureKeyVaultKey cmdlet, where I pass the PFX file path and password? Or a method to convert PFX to keyBundle?

**Comment by pomortaz** [comment]
No @paolorr, but you can implement the PFX converter similar to [how Add-AzureKeyVaultKey does the conversion](https://github.com/pomortaz/azure-powershell/blob/master/src/ResourceManager/KeyVault/Commands.KeyVault/Models/PfxWebKeyConverter.cs).
