### ISSUE TITLE
BlockBlobWriteStream flush method creates a new blob version

### ISSUE THREAD

**Issue by PaulVrugt** [Azure/azure-sdk-for-net#20652]
**Describe the bug**
We use the OpenWrite of BlockBlobClient to create writeable streams to azure block blob storage. Whenever we call flush to clear the internal buffer of the write stream, it seems that the the stream tells the storage container we are done writing to the file and the file is committed, creating a new blob version for each "flush" call, while the write stream is still open.

Some background:
We use 3rd party libraries that can handle streams. We pass a BlockBlobWriteStream to a method of a 3rd party library to save some file to the stream. This library calls flush multiple times, causing loads of blob versions in blob storage. As a workaround we have now implemented a wrapper stream that ignores flush calls.

**Expected behavior**
We would expect that the "flush" method would only clear internal buffers to azure storage, but does not cause a new version of the blob to be created.

**Actual behavior (include Exception or Stack Trace)**
Currently, each call to "flush" creates a new blob version. Even more interesting: we discovered that every once in a while (very rarely) a file doesn't get written to blob storage correctly and the file becomes corrupt. This seems to be related to the flush calls, because since we implemented the wrapper stream to avoid flush calls, the file corruption seems to have disappeared. We haven't been able to reproduce the corruption in a test scenario though.

**To Reproduce**
Make you you have a storage account with blob versioning enabled.

The following snippet creates 100 versions of the same blob, while I would expected only 1 version to be created:
```
var bytes = <a bunch of bytes>
using (var inputstream = blockBlob.OpenWrite(true))
{
  for (var i = 0; i < 100; i++)
  {
    inputstream.Write(bytes, 0, 100);
    inputstream.Flush();
  }
}
```

**Environment:**
 - Azure.Storage.Blobs 12.8.1
 - Windows 10 .NET Framework 4.8
 - Visual Studio 16.9.4

**Comment by amnguye** [comment]
Every time you flush that's considered updating the blob. For every time you update the blob (and when you have blob versioning enabled) a new version will be created.

https://docs.microsoft.com/en-us/azure/storage/blobs/versioning-overview#how-blob-versioning-works

So this is by design for versioning and flushes.

I think my concern mainly is the corruption that's happening. If you have a wrapper stream preventing flushs (and other functionality), I would like to see the implementation for that because it could be there where the corruption is happening. I would also like to see the logs on the requests that are being sent causing the corruption.

**Comment by PaulVrugt** [comment]
@amnguye 

Thanks for the quick feedback. I understand how versioning works, but I would argue that your answer is a inconsistent with the behavior. You say each flush updates the blob, and each update to a blob is a new version. Following that argument, each implicit flush done by the BlockblobWriteStream because the internal buffer is full would also create a new version. But this is not the case. The default buffer for the WriteStream is 4mb. I can easily write 400mb to it, and still only 1 new version will be created. This is also what I would expect to happen. As long as I have the write stream open, it shouldn't matter if there is an implicit of explicit flush. The blob write should only be considered finished when the write stream is disposed. From the System.IO.Stream.Flush docs:

> When overridden in a derived class, clears all buffers for this stream and causes any buffered data to be written to the underlying device.

Nothing in this doc states anything about the write operation being finished. It only says the stream should clear it's buffer. The current behavior of an explicit flush call sounds more like the behavior the "close" call should have (except that in this implementation close doesn't actuall close the stream)

About the corruption
I think you misunderstood the issue. We were experiencing corruption when NOT using a wrapper stream. The 3rd partly library calls flush about 30 times when saving, and this would somehow sometimes result in a corrupted files. Ever since we added the wrapper stream to ignore flush calls, the corruption has disapeared.

**Comment by yapaxi** [comment]
I have encountered the same problem recenly which is also related to excessive flushes and I managed to make it fully reproducible:

Corruption always happens if you do this:

- write 4 bytes
- flush
- write 2 bytes
- dispose the stream
- read it back

4+1 and 4+3 are fine
4+2 - always causes corruption

More details: https://stackoverflow.com/questions/67280408/specific-combinations-of-flush-and-write-calls-corrupts-blockblob-used-via-openw

**Comment by amnguye** [comment]
For the corruption issue we are looking to put out a release very soon for 12.8 to include the corruption fix.

As for the query about functionality and details on how flushing works @seanmcc-msft can you weigh in on this?

**Comment by kasobol-msft** [comment]
The corruption issue fix is now available in https://www.nuget.org/packages/Azure.Storage.Blobs/12.8.3

**Comment by seanmcc-msft** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.flush?view=net-5.0

> When overridden in a derived class, clears all buffers for this stream and causes any buffered data to be written to the underlying device.

This is exactly what we are doing in `OpenWrite.Flush()`.

**Comment by PaulVrugt** [comment]
Could you then please explain to me what's the difference between calling flush explicitly to clear the buffer, and writing 100mb to the stream causing multiple internal flushes due to the buffer being full? Because the first one causes a new blob version, and the second one doesn't.

I understand you are flushing the buffers, but something is causing a new blob version to be created, which is unwanted.

**Comment by amnguye** [comment]
Calling flush explicitly will cause the blob to be updated because a commit block list is called. Since the blob is updated, a version will be created.

Writing to the 100mb to the stream (aka appending to the stream) causes a stage/put block list (`StageBlock(..)`) to occur. Since these blocks are not commited, the blob is not updated therefor no version is created, until you flush (or close the stream which causes a flush).

**Comment by PaulVrugt** [comment]
Good. I get the feeling I'm not getting any traction here. I've stated my use case and I still think the explicit flush should clear the buffer, but not cause a new version to be written (or at least give me the option to make it behave like this). It just doesn't make any sense combined with versioning and makes versioning messy and useless with lots of flushes. But since I'm not getting any traction I'll keep working with yet another wrapper stream to not get hundreds of versions in the blob container and to get the stream to work the way I would expect it to.

I would urge you to reconsider the use case and look beyond what the stream should/will do theoretically, but we can manage with the workaround

**Comment by amnguye** [comment]
As @seanmcc-msft pointed out, the `OpenWrite.Flush()` is operating as it should according to how the original `Stream.Flush` operates. "When overridden in a derived class, clears all buffers for this stream and causes any buffered data to be written to the underlying device." Therefore an explicit flush should clear the buffers and cause the data to be updated and written to the blob.

Changing how `OpenWrite.Flush()` operates would not align with the original `Stream.Flush` and would also cause a breaking change to how `OpenWrite.Flush()` operates (and sends the commit block list). 

For your use case it's not ideal. A proposal we have here is to do a feature request where we add to the `DataLakeFileOpenWriteOptions` and have a knob/property that allows you to control the behavior of flush, and only committing the block list at `Close` of the stream. @seanmcc-msft @kasobol-msft What do you think? This would prevent constant updates to the blob, which triggers new versions to be created to the blob. Also maybe if other customers have events tracking every time their blobs update.

**Comment by kasobol-msft** [comment]
The knob is fine.

**Comment by PaulVrugt** [comment]
This would be the best of both worlds, and everyone will be happy.

**Comment by MatthewSteeples** [comment]
Is this still planned to be implemented at some point? We came across this when we moved from using MemoryStream to writing to Blob storage directly. We're using SharpZipLib and that calls Flush twice for each file you save in the zip file.
