### ISSUE TITLE
[QUERY] Deserialization and Serialization issue and discriminator "objectType" is not getting addressed

### ISSUE THREAD

**Issue by mayankagg9722** [Azure/azure-sdk-for-net#20685]
**Query/Question**
How can we help?
I am trying to write mock tests for Microsoft.DataProtection SDK. I am facing issues in deserialization of the request body that I am using in the mock request and the issues child class values are not being deserialized. Also, "objectType" from the request body is not addressed.

**Example Policy request body "properties" contains:** "BackupPolicy" as "obejctType" but the sdk after deserialization giving "BaseBackupPolicy" object. 

**Pull request link:** https://github.com/Azure/azure-sdk-for-net/pull/20683
**File name:** DPPDisksE2ETests.cs (line 29) and TestHelper.cs (line  46)
**Swagger link:** https://github.com/Azure/azure-rest-api-specs/tree/master/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2021-01-01

**Environment:**
 - Name and version of the Library package used: 
 
 autorest/core  3.0.6369
 
 - Hosting platform or OS and .NET runtime version 
 .NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  2.1.523 [C:\Program Files\dotnet\sdk]
  2.1.815 [C:\Program Files\dotnet\sdk]
  3.1.408 [C:\Program Files\dotnet\sdk]
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  
 - IDE and version : [e.g. Visual Studio 16.3]
Visual Studio Enterprise 2019

**Comment by jsquire** [comment]
//cc: @ShivangiReja

**Comment by chamons** [comment]
If you are trying to create mock classes then https://github.com/Azure/autorest.csharp/issues/543 may be blocking you.

I'm having trouble exactly following your issue, given the size of PRs linked and lack of specifics.

Could you point out one exact swagger operation that isn't be generated correctly, so i can be sure I'm looking at your specific issue.

**Comment by mayankagg9722** [comment]
> If you are trying to create mock classes then [Azure/autorest.csharp#543](https://github.com/Azure/autorest.csharp/issues/543) may be blocking you.
> 
> I'm having trouble exactly following your issue, given the size of PRs linked and lack of specifics.
> 
> Could you point out one exact swagger operation that isn't be generated correctly, so i can be sure I'm looking at your specific issue.

https://github.com/Azure/azure-rest-api-specs/blob/2aa64e009a52b508db1038d1bbe41906b24b05f9/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2021-01-01/dataprotection.json#L686

This is one swagger operation where when I tried to deserialize request body to Autorest generated classes, it didn't worked.
Other specification for this:
**Pull request link:** https://github.com/Azure/azure-sdk-for-net/pull/20683
**File name:** DPPDisksE2ETests.cs (#29 line) and TestHelper.cs (#46 line)

**Comment by mayankagg9722** [comment]
> > If you are trying to create mock classes then [Azure/autorest.csharp#543](https://github.com/Azure/autorest.csharp/issues/543) may be blocking you.
> > I'm having trouble exactly following your issue, given the size of PRs linked and lack of specifics.
> > Could you point out one exact swagger operation that isn't be generated correctly, so i can be sure I'm looking at your specific issue.
> 
> https://github.com/Azure/azure-rest-api-specs/blob/2aa64e009a52b508db1038d1bbe41906b24b05f9/specification/dataprotection/resource-manager/Microsoft.DataProtection/stable/2021-01-01/dataprotection.json#L686
> 
> This is one swagger operation where when I tried to deserialize request body to Autorest generated classes, it didn't worked.
> Other specification for this:
> **Pull request link:** #20683
> **File name:** DPPDisksE2ETests.cs (line 29) and TestHelper.cs (line 46)

Can you aslo please tell me what helped you to resolve your issue? What changes I should try?

**Comment by markcowl** [comment]
@mayankagg9722 Can you provide an example of a deserialization that isn't working?  By this, I mean a response with the json for a discriminator type that is not being properly generated.  Without seeing the actual json payload, it is difficult to disgnose any issue.

**Comment by markcowl** [comment]
Note that https://github.com/Azure/autorest.csharp/issues/543 is an issue for the v3 generator, which would not impact v2 management client generation.

**Comment by mayankagg9722** [comment]
> @mayankagg9722 Can you provide an example of a deserialization that isn't working? By this, I mean a response with the json for a discriminator type that is not being properly generated. Without seeing the actual json payload, it is difficult to disgnose any issue.

**Original request body for create BackupPolicy:**
`{
    "id": "/subscriptions/f2edfd5d-5496-4683-b94f-b3588c579009/resourceGroups/mayaggarDiskRG/providers/Microsoft.DataProtection/BackupVaults/DiskbackupVault1/backupPolicies/retentionpolicy2",
    "name": "retentionpolicy2",
    "type": "Microsoft.DataProtection/backupPolicies",
    "properties": {
        "policyRules": [
            {
                "backupParameters": {
                    "backupType": "Incremental",
                    "objectType": "AzureBackupParams"
                },
                "trigger": {
                    "schedule": {
                        "repeatingTimeIntervals": [
                            "R/2019-12-26T13:08:27.8535071Z/PT4H"
                        ]
                    },
                    "taggingCriteria": [
                        {
                            "tagInfo": {
                                "tagName": "Default",
                                "id": "Default_"
                            },
                            "taggingPriority": 99,
                            "isDefault": true,
                            "objectType": "TaggingCriteria"
                        }
                    ],
                    "objectType": "ScheduleBasedTriggerContext"
                },
                "dataStore": {
                    "dataStoreType": "OperationalStore",
                    "objectType": "DataStoreInfoBase"
                },
                "name": "BackupHourly",
                "objectType": "AzureBackupRule",
                "ruleType": "Backup"
            },
            {
                "lifecycles": [
                    {
                        "sourceDataStore": {
                            "dataStoreType": "OperationalStore",
                            "objectType": "DataStoreInfoBase"
                        },
                        "deleteAfter": {
                            "objectType": "AbsoluteDeleteOption",
                            "duration": "P1W"
                        }
                    }
                ],
                "isDefault": true,
                "name": "Default",
                "objectType": "AzureRetentionRule",
                "ruleType": "Retention"
            }
        ],
        "name": "retentionpolicy2",
        "id": "75efeda6-7c58-4771-a618-0ec86fe8e423",
        "datasourceTypes": [
            "Microsoft.Compute/disks"
        ],
        "objectType": "BackupPolicy"
    }
}`

**Serialized string (of above json):**
`{\r\n  \"id\": \"/subscriptions/f2edfd5d-5496-4683-b94f-b3588c579009/resourceGroups/mayaggarDiskRG/providers/Microsoft.DataProtection/BackupVaults/DiskbackupVault1/backupPolicies/retentionpolicy2\",\r\n  \"name\": \"retentionpolicy2\",\r\n  \"type\": \"Microsoft.DataProtection/backupPolicies\",\r\n  \"properties\": {\r\n\t\"policyRules\": [\r\n\t  {\r\n\t\t\"backupParameters\": {\r\n\t\t  \"backupType\": \"Incremental\",\r\n\t\t  \"objectType\": \"AzureBackupParams\"\r\n\t\t},\r\n\t\t\"trigger\": {\r\n\t\t  \"schedule\": {\r\n\t\t\t\"repeatingTimeIntervals\": [\r\n\t\t\t  \"R/2019-12-26T13:08:27.8535071Z/PT4H\"\r\n\t\t\t]\r\n\t\t  },\r\n\t\t  \"taggingCriteria\": [\r\n\t\t\t{\r\n\t\t\t  \"tagInfo\": {\r\n\t\t\t\t\"tagName\": \"Default\",\r\n\t\t\t\t\"id\": \"Default_\"\r\n\t\t\t  },\r\n\t\t\t  \"taggingPriority\": 99,\r\n\t\t\t  \"isDefault\": true,\r\n\t\t\t  \"objectType\": \"TaggingCriteria\"\r\n\t\t\t}\r\n\t\t  ],\r\n\t\t  \"objectType\": \"ScheduleBasedTriggerContext\"\r\n\t\t},\r\n\t\t\"dataStore\": {\r\n\t\t  \"dataStoreType\": \"OperationalStore\",\r\n\t\t  \"objectType\": \"DataStoreInfoBase\"\r\n\t\t},\r\n\t\t\"name\": \"BackupHourly\",\r\n\t\t\"objectType\": \"AzureBackupRule\",\r\n\t\t\"ruleType\": \"Backup\"\r\n\t  },\r\n\t  {\r\n\t\t\"lifecycles\": [\r\n\t\t  {\r\n\t\t\t\"sourceDataStore\": {\r\n\t\t\t  \"dataStoreType\": \"OperationalStore\",\r\n\t\t\t  \"objectType\": \"DataStoreInfoBase\"\r\n\t\t\t},\r\n\t\t\t\"deleteAfter\": {\r\n\t\t\t  \"objectType\": \"AbsoluteDeleteOption\",\r\n\t\t\t  \"duration\": \"P1W\"\r\n\t\t\t}\r\n\t\t  }\r\n\t\t],\r\n\t\t\"isDefault\": true,\r\n\t\t\"name\": \"Default\",\r\n\t\t\"objectType\": \"AzureRetentionRule\",\r\n\t\t\"ruleType\": \"Retention\"\r\n\t  }\r\n\t],\r\n\t\"name\": \"retentionpolicy2\",\r\n\t\"id\": \"75efeda6-7c58-4771-a618-0ec86fe8e423\",\r\n\t\"datasourceTypes\": [\r\n\t  \"Microsoft.Compute/disks\"\r\n\t],\r\n\t\"objectType\": \"BackupPolicy\"\r\n  }\r\n}"`

**Deserializing the json in here: TestHelper.cs (line 46)**
BaseBackupPolicyResource body = JsonConvert.DeserializeObject<BaseBackupPolicyResource>(requestData.ToString());

In output all the fileds are g

**Comment by markcowl** [comment]
@mayankagg9722 You have provided a request json and a serialized request json, I I am not sure how this bears on what you are asking. I was asking for a response that was deserialized incorrectly.  The SDK library does not translate from json to json, so I am not sure what this represents.

Is the problem you are seeing that you aren't sure how to construct an object to serialize the request, or that deserialization results in the wrong *actual* types? Note that it is expected that the type signature will be for the base type, as that is how polymorphism is implemented, however, the underlying types returned should *actually* be more derived types, so I should be able to cast the returned  BaseBackupPolicy to a BackupPolicy. The actual polymorphism is implemented by json serializer settings provided in the client.

Please provide an example of the actual failure you are seeing on deserialization.  That is a json that results in a BackupPolicy, but isn't

**Comment by mayankagg9722** [comment]
> @mayankagg9722 You have provided a request json and a serialized request json, I I am not sure how this bears on what you are asking. I was asking for a response that was deserialized incorrectly. The SDK library does not translate from json to json, so I am not sure what this represents.
> 
> Is the problem you are seeing that you aren't sure how to construct an object to serialize the request, or that deserialization results in the wrong _actual_ types? Note that it is expected that the type signature will be for the base type, as that is how polymorphism is implemented, however, the underlying types returned should _actually_ be more derived types, so I should be able to cast the returned BaseBackupPolicy to a BackupPolicy. The actual polymorphism is implemented by json serializer settings provided in the client.
> 
> Please provide an example of the actual failure you are seeing on deserialization. That is a json that results in a BackupPolicy, but isn't

**Comment by mayankagg9722** [comment]
> @mayankagg9722 You have provided a request json and a serialized request json, I I am not sure how this bears on what you are asking. I was asking for a response that was deserialized incorrectly. The SDK library does not translate from json to json, so I am not sure what this represents.
> 
> Is the problem you are seeing that you aren't sure how to construct an object to serialize the request, or that deserialization results in the wrong _actual_ types? Note that it is expected that the type signature will be for the base type, as that is how polymorphism is implemented, however, the underlying types returned should _actually_ be more derived types, so I should be able to cast the returned BaseBackupPolicy to a BackupPolicy. The actual polymorphism is implemented by json serializer settings provided in the client.
> 
> Please provide an example of the actual failure you are seeing on deserialization. That is a json that results in a BackupPolicy, but isn't

**Json before deserialization:**
`{
  "id": "/subscriptions/f2edfd5d-5496-4683-b94f-b3588c579009/resourceGroups/mayaggarDiskRG/providers/Microsoft.DataProtection/BackupVaults/DiskbackupVault1/backupPolicies/retentionpolicy2",
  "name": "retentionpolicy2",
  "type": "Microsoft.DataProtection/backupPolicies",
  "properties": {
	"policyRules": [
	  {
		"backupParameters": {
		  "backupType": "Incremental",
		  "objectType": "AzureBackupParams"
		},
		"trigger": {
		  "schedule": {
			"repeatingTimeIntervals": [
			  "R/2019-12-26T13:08:27.8535071Z/PT4H"
			]
		  },
		  "taggingCriteria": [
			{
			  "tagInfo": {
				"tagName": "Default",
				"id": "Default_"
			  },
			  "taggingPriority": 99,
			  "isDefault": true,
			  "objectType": "TaggingCriteria"
			}
		  ],
		  "objectType": "ScheduleBasedTriggerContext"
		},
		"dataStore": {
		  "dataStoreType": "OperationalStore",
		  "objectType": "DataStoreInfoBase"
		},
		"name": "BackupHourly",
		"objectType": "AzureBackupRule",
		"ruleType": "Backup"
	  },
	  {
		"lifecycles": [
		  {
			"sourceDataStore": {
			  "dataStoreType": "OperationalStore",
			  "objectType": "DataStoreInfoBase"
			},
			"deleteAfter": {
			  "objectType": "AbsoluteDeleteOption",
			  "duration": "P1W"
			}
		  }
		],
		"isDefault": true,
		"name": "Default",
		"objectType": "AzureRetentionRule",
		"ruleType": "Retention"
	  }
	],
	"name": "retentionpolicy2",
	"id": "75efeda6-7c58-4771-a618-0ec86fe8e423",
	"datasourceTypes": [
	  "Microsoft.Compute/disks"
	],
	"objectType": "BackupPolicy"
  }
}`

**Above Json shows requestData**
![image](https://user-images.githubusercontent.com/17884128/116669697-84afed80-a9bc-11eb-8721-7413b3c6f046.png)

**Json after deserilization:**

`{"properties":{"datasourceTypes":["Microsoft.Compute/disks"]},"id":"/subscriptions/f2edfd5d-5496-4683-b94f-b3588c579009/resourceGroups/mayaggarDiskRG/providers/Microsoft.DataProtection/BackupVaults/DiskbackupVault1/backupPolicies/retentionpolicy2","name":"retentionpolicy2","type":"Microsoft.DataProtection/backupPolicies","systemData":null}`


![image](https://user-images.githubusercontent.com/17884128/116671044-1ec46580-a9be-11eb-9c25-03b761c19f3f.png)

"Properties" is of the type "BaseBackupPolicy" but if you will see above in the original json discriminator "objectType": "BackupPolicy" is used.


**Issue we are facing is C# sdk converters are not able to create instance of child types(the one used as discriminator) and only base class properties are getting returned to us.**

**Comment by markcowl** [comment]
Gotcha.  

Serialization and deserialization for polymorphism is handled by the serialization and deserialization settings passed in the call to JsonConvert (actually, sdk code uses SafeJsonConvert, but that shouldn't matter).  Here is where the Serialization Settings and DeserializationSettings are set up: https://github.com/mayankagg9722/azure-sdk-for-net/blob/users/mayaggar/newDataProtection/sdk/dataprotection/Microsoft.Azure.Management.DataProtection/src/Generated/DataProtectionClient.cs#L397-L451

And here is a sample deserialization call using the settings: https://github.com/mayankagg9722/azure-sdk-for-net/blob/users/mayaggar/newDataProtection/sdk/dataprotection/Microsoft.Azure.Management.DataProtection/src/Generated/DataProtectionClient.cs#L586

And a sample serialization call using the settings: https://github.com/mayankagg9722/azure-sdk-for-net/blob/users/mayaggar/newDataProtection/sdk/dataprotection/Microsoft.Azure.Management.DataProtection/src/Generated/DataProtectionClient.cs#L957

**Comment by mayankagg9722** [comment]
Thanks it resolved the issue.
