### ISSUE TITLE
DefaultAzureCredential() Fails with unhandled exception on ManagedIdenity authentication.

### ISSUE THREAD

**Issue by lindkj** [Azure/azure-sdk-for-net#20727]
While out of the office due to Covid we converted our application to utilize DefaultAzureCredential to access AzureKeyVault. When deployed in Azure it is using ManagedIdentity to access the vault secrets, while debugging the code local it would utilize our VS credentials. Everything was working great. Upon coming back to the office last week we experience an issue where a user was unable debug the application local due to unhandled exception from ManagedIdentityClient. The error was in relation to SSL certificate mismatch.  The inner exception stated:

_{"The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors"}_

After enabling debugging on all code and adding breakpoints to the ManagedIdentityClient.cs to capture the requested URI, we found that it was hardcoded to check for TCP connection against ip address 169.254.169.254. After checking that IP in our network we found an administrative server for BARCO systems Click-Share devices utilizing that IP address, this is what caused the SSL error as the IP address was redirecting to Barco's support site for login. 

Our network engineers shut down the administration server and the DefaultAzureCredential is now working again as expected for local debugging sessions while in the office.

In the ManagedIdentityClient.cs file there is an if block that checks the MSIType to see if we are in an Azure environment or not, the first check is for EnvironmentVariables. The second check is to check if IMDS endpoint is available (this is where we were broken). The function called ImdsAvailable() will try to create a TCP connection to the IMDS IP address. It is then assumed if a connection can be established that the connection is a IMDS server. In our case since we had a server that was broadcasting on that IP address it responded to the TCP connection validating per code that it was available for Imds. Then the subsequent call to get token from the endpoint would fail due to the Barco instance returning an SSL cert for the barco.com domain which did not match the request, since request was in ip form.  

Is there a way this function can be modified to confirm the correct type of server prior to moving forward with setting the MSIType, which in turn moves the process along? Alternatively should we handle the SSL cert or the rejection from the "msi endpoint" so that the DefaultAzureCredentials fails over to the next authentication protocol?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @lindkj - We're considering a change that may avoid this issue in a different way. See https://github.com/Azure/azure-sdk-for-net/issues/20617

**Comment by lindkj** [comment]
> Hi @lindkj - We're considering a change that may avoid this issue in a different way. See #20617
I agree with a different approach, and what is stated in 20617 appears to be a solid way to confirm. 

Though follow up question, in our case if the "rogue" end point at the ip address is still there would we still not get the same SSL error due to name mismatch when the token request is sent immediately? Since a connection will attempt to be established and the http call will handle the request, it will handle the errors differently then returning nothing. Again this may not be an SDK issue, but a network issue where another application is using an industry standard IP address for its own internal purpose.

**Comment by christothes** [comment]
I would expect the GetToken request would fail and we'd treat the credential as unavailable.

**Comment by lindkj** [comment]
I will follow #20617 and test if and when that is added to release. 
Thanks guys. Keep up the great work!
