### ISSUE TITLE
[QUERY] Performance degradation from Microsoft.Azure.ServiceBus 4.0.0

### ISSUE THREAD

**Issue by pilarodriguez** [Azure/azure-sdk-for-net#20721]
**Query/Question**
Let me explain to you my problem.

We have an API endpoint that receives requests and then it is just sending a message to a queue using the [SendAsync](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.ServiceBus_4.0.0/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Core/ISenderClient.cs#L21) method. The API is in an Azure AppService.

Then we have a webjob contained in a different AppService. That webjob is listening to the queue and processing the messages sent by the API endpoint. When the message is received, we update some entries in our database. We are using `Microsoft.Azure.ServiceBus` (version 3.2.0) and `Microsoft.Azure.WebJobs.Extensions.ServiceBus` (version 3.0.3) to listen to the messages:

```
public async Task HandleCallbackTask([ServiceBusTrigger("queue-name")] Message message)
{
   await HandleMessages(message);
}
```

We have a performance test that sends a lot of requests to the endpoint. We measure the response time of the endpoint, and we also measure how much it takes for the webjob to process all the messages. 

We were using `Microsoft.Azure.ServiceBus` version 3.2.0 and it was working fine. But after updating to version 4.0.0, the performance of the endpoint was worse. In our tests, the initial response time was around 1200 milliseconds per request, and with the new version is around 1700 milliseconds. Each request takes around half a second more. The problem is visible in the API, but the issue seems to be caused by the webjob. If I only update the Microsoft.Azure.ServiceBus version in the API and keep the webjob at version 3.2.0, the performance is not affected.

If I remove all the code to process the message from the webjob (just receive the message and return), the performance of the API is the same with both versions. The problem seems to be a combination of our code, together with the new package.

I couldn't find what is the problem. Do you know what are the changes in the 4.0.0 version that could have an impact in the scenario that I've described?

I looked at multiple metrics (CPU, memory consumption, thread counts and connection count), and they are the same with both versions. I also try to update to the latest version of Microsoft.Azure.ServiceBus and Microsoft.Azure.WebJobs.Extensions.ServiceBus, but there is no improvement.

**Environment:**

 - Name and version of the Library package used: Microsoft.Azure.ServiceBus 4.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure AppService, .Net Core 3.1
 - IDE and version: Visual Studio 16.8.1

**Comment by jsquire** [comment]
//fyi: @JoshLove-msft

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by navba-MSFT** [comment]
@pilarodriguez Apologies for the late reply. Since [Microsoft.Azure.ServiceBus ](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus) is now deprecated. Could you please let me know if you are facing the same issue while using [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/) ? Awaiting your reply.

**Comment by pilarodriguez** [comment]
Hello! Thanks for your answer. Migrating all our services to verify if the performance improves is not an easy task. We have planned to pick it up soon, but it would take few weeks before we have it ready

**Comment by navba-MSFT** [comment]
@pilarodriguez Sure. Thanks for the update. Please feel free to update this thread once you are done with the tests.
