### ISSUE TITLE
Require overriding comments on some members

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#20736]
When overriding members, `<inheritdoc/>` is invaluable. There are a few APIs, however, where we should probably provide specialized documentation, such as - but not limited to - the following list.

- [ ] `Operation<T>.Value`
- [ ] Types including classes, interfaces, and structs.
- [ ] Constructors

Perhaps we could add an XML tag like `<override/>` or something that signals to an analyzer or our documentation generation tool that a dev should override the doc comments for that member. I don't think we should elide documentation, though (which would cause `<inheritdoc/>` to fail), since forgetting to override the comments means no documentation is generated.

For types and constructors we probably could just disallow `<inheritdoc/>` since there's probably no practical reason to inherit documentation. These should always have specialized documentation.

For example, the common constructor doc pattern is:
```csharp
/// <summary>
/// Initializes a new instance of the <see cref="BaseClassName"/> class.
/// </summary>
```

Inheriting that on `DerivativeClassName` is confusing. And for types, they are usually derived for a reason specific to the SDK they are in and shouldn't inherit docs either.

**Comment by pallavit** [comment]
Is this something we would want our generator to generate? Do you see a lot of manual documentation which will benefit from this? I can see us having to do this for core APIs though.

**Comment by heaths** [comment]
Enough has changed since I opened this for tracking it's probably not worth keeping open. We certainly haven't prioritized any work toward this end - not explicitly, anyway: general codegen changes might've affected some change here - so I'm fine with just closing this. /cc @m-nash
