### ISSUE TITLE
Azure Attestation Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#20745]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/attestation/Azure.Security.Attestation#azure-attestation-client-library-for-net):
![image](https://user-images.githubusercontent.com/65581162/116520997-01cc5b80-a906-11eb-983b-70e5a2feb759.png)
Reason: This link is wrong.
Suggestion:
Update the link to: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/attestation/Azure.Security.Attestation/src

2.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/attestation/Azure.Security.Attestation#contributing):
![image](https://user-images.githubusercontent.com/65581162/116521119-26283800-a906-11eb-91a0-ee5c6b3d88b4.png)

Suggestion:
1.Update  `[Microsoft Open Source Code of Conduct][microsoft_code_of_conduct]` to '[Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/)'

2.Add hyperlink for `Code of Conduct FAQ`  https://opensource.microsoft.com/codeofconduct/faq/

3.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/attestation/Azure.Security.Attestation#key-concepts):
![image](https://user-images.githubusercontent.com/65581162/116521609-bfefe500-a906-11eb-9773-51cbcf59ba21.png)
Suggestion: Remove a `management`

@jongio for notification.

**Comment by LarryOsterman** [comment]
Thank you very much. I'll address all of them except the last - it is not a typo, these are apis for managing the policy management apis, thus policy management management. The text here is intended to be a humorous element. I could change it to "yes, there are APIs for managing policy management", but that loses the punch somewhat.
