### ISSUE TITLE
Azure Storage Blobs Sample issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#20746]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/samples/Sample03_Migrations.cs#L840),[link2](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/samples/Sample03_Migrations.cs#L867):
![image](https://user-images.githubusercontent.com/65581162/116525246-e748b100-a90a-11eb-9c1b-89cb35556250.png)
![image](https://user-images.githubusercontent.com/65581162/116526433-2deadb00-a90c-11eb-9701-96c86eb60cb5.png)

Reason: The lack of  create blob code after 876 lines of code.
Suggestion:
Add
` await containerClient.CreateAsync();` 
after 
`var containerClient = new BlobContainerClient(ConnectionString, containerName);`

@jongio for notification.

**Comment by v-yilinhu** [comment]
Close this issue, due to this issue had been fixed at [commit](https://github.com/Azure/azure-sdk-for-net/commit/38441a45981c9c9433c6b78382ee23cebcb60309#diff-a5feba67398fbf6e4ac19fe62d34d33ecfb2c0027c977d2285ee363df9866fc6).
