### ISSUE TITLE
Azure Service Bus Readme issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#20748]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Microsoft.Azure.ServiceBus#azure-service-bus-client-library-for-net):
![image](https://user-images.githubusercontent.com/65581162/116528590-976be900-a90e-11eb-9a05-ae78bfdf3b26.png)
Suggestion:
Update the link to  https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Microsoft.Azure.ServiceBus/src

@jongio for notification.

**Comment by jsquire** [comment]
Fixed by #20776
