### ISSUE TITLE
[FEATURE REQ] Identify untranslatable value exists in FormRecognizer CustomModel analysis

### ISSUE THREAD

**Issue by RJWerning** [Azure/azure-sdk-for-net#20764]
**Library or service name.**
Azure.AI.FormRecognizer
 
**Is your feature request related to a problem? Please describe.**
When processing a document against a custom trained model, when a value is present but not able to be translated (such as a signature), would it be possible to include something in the response to identify it as having a value though it wasn't able to be processed?  

The specific use case is that our client needs to know that a document was signed by the parties involved.  Without this feature, someone will be required to manually review thousands of document images per week to verify that they have been signed.

I have attached an example of mock data to illustrate the issue. 
![SignatureIssue](https://user-images.githubusercontent.com/35701652/116614806-05f57a80-a900-11eb-87a5-c5b586165722.jpg)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
The Form Recognizer library does provide functionality that can tell you if something was handwritten (and if you know the field and location, you could assume it is a signature).
For example, on a `RecognizedForm` object you could look at the `Lines` property https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/samples/Sample2_RecognizeCustomFormsFromUri.cs#L80 and look at the `Appearance`.

Here is an example: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/samples/Sample1_RecognizeContentFromUri.cs#L42

Let me know if this helps
