### ISSUE TITLE
[storage] Supporting destination SAS query parameters with DataLakeDirectoryClient.Rename()

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#20783]
In `DataLakeDirectoryClient.Rename(destinationPath)`, does not have a convenient way to pass the SAS Query Parameters along with the path. Users have to do a hack where `DataLakeDirectoryClient.Rename(destinationPath + "?" + sasQueryParameters)`. 

Related PSH issue: https://github.com/Azure/azure-powershell/issues/14875

**Comment by amnguye** [comment]
We are discussing the correct way to address this issue.

**Comment by seanmcc-msft** [comment]
The workaround is to call DataLakeSasQueryParameters.ToString().
