### ISSUE TITLE
Authorization: No details on what a condition is or what it can be set to

### ISSUE THREAD

**Issue by etaham** [Azure/azure-sdk-for-net#20788]
There is no description of what a condition is and what it's potential values are. Please update the docs and/or add a link to the documentation for role assignment conditions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eb250c7-6d78-2a09-3aee-3433cc0e69de
* Version Independent ID: 3c077586-9509-8530-1701-15ccd53ad609
* Content: [RoleAssignment.Condition Property (Microsoft.Azure.Management.Authorization.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.authorization.models.roleassignment.condition?view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Azure.Management.Authorization.Models/RoleAssignment.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Authorization.Models/RoleAssignment.xml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by markcowl** [comment]
@jsquire service documentation issue

**Comment by navba-MSFT** [comment]
@etaham Apologies for the late reply. We are looking into this issue. The above PR has been filed. It is under Review now. In the meantime, if you have any questions, please feel free to ask.
