### ISSUE TITLE
Ref docs repo content/configuration audit

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#20784]
Audit for content/configurations that are outside of the scope of reference docs (e.g. conceptual content, conceptual docs redirects). 

Items outside of this scope should be placed in the appropriate repositories.

**Comment by openpublishbuild** [comment]
@danieljurek Is there any ETA for this? As this work item attached to postmortem, it may flag in s360 passed the due date.

**Comment by pallavit** [comment]
@danieljurek can you please help me understand what auditing entails here? Is this something you want help from the .NET team to do?
