### ISSUE TITLE
Azure.Extensions.AspNetCore.DataProtection.Blobs should create container if not exists

### ISSUE THREAD

**Issue by leotsarev** [Azure/azure-sdk-for-net#20798]
**Library or service name.**
Azure.Extensions.AspNetCore.DataProtection.Blobs
 
**Is your feature request related to a problem? Please describe.**
I call PersistKeysToAzureBlobStorage in Startup and expect everything should work out of box, but I have to create container manually.

**Comment by jsquire** [comment]
Hi @leotsarev.  The `Azure.Extensions.AspNetCoreDataProtection.Blobs` library is not part of the Azure SDK and is owned by the ASP.NET Core team.   I've transferred this issue to the AspNetCore repository as [#32316](https://github.com/dotnet/aspnetcore/issues/32316).

**Comment by blowdart** [comment]
@jsquire This is *not* part of ASP.NET, it's yours.

https://github.com/Azure/azure-sdk-for-net/blob/Azure.Extensions.AspNetCore.DataProtection.Blobs_1.2.0/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Blobs/CHANGELOG.md

You should reopen this. 

(But, as an aside, IMO no this change shouldn't be made, it would involve granting the asp.net app rights to create a blob store, which isn't in keeping with least privilege)

**Comment by jsquire** [comment]
Apologies;  this was my mistake.  Reopening and routing.

**Comment by seanmcc-msft** [comment]
@tg-msft, what is https://github.com/Azure/azure-sdk-for-net/tree/Azure.Extensions.AspNetCore.DataProtection.Blobs_1.2.0/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Blobs ?  I've never heard of this before.

**Comment by tg-msft** [comment]
This is a Blobs implementation of ASP.NET's DataProtection interface that we've had for about a year or so.

Removing Storage tags and +@pakrym to evaluate the request.

**Comment by pakrym** [comment]
@blowdart recommended that we don't implement this as it would require giving the application more access to the Storage Account than required and violate the principle of least privilege.

**Comment by tg-msft** [comment]
The [README](https://github.com/Azure/azure-sdk-for-net/tree/Azure.Extensions.AspNetCore.DataProtection.Blobs_1.2.0/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Blobs#prerequisites) suggests using "Storage Blob Data Contributor" which [has the permission to create containers.](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor)

Two thoughts:
- If we want least privilege, we should scope the README to [exactly what's required](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory#permissions-for-calling-blob-and-queue-data-operations)
- We could consider trying to create the container but ignore 403s if we don't have permission.

**Comment by pakrym** [comment]
>The README suggests using "Storage Blob Data Contributor" which has the permission to create containers.

But we are applying the role to the container itself so that won't allow the container creation (_I think_).

> We could consider trying to create the container but ignore 403s if we don't have permission.

Agreed.

**Comment by blowdart** [comment]
Or you could consider publishing a powershell script to support the creation. We did that for IIS data protection permissions.

**Comment by jsquire** [comment]
After review and discussion, this isn't a feature that we'll be adding.  

Besides the desire to adhere to the principle of least privilege, a change to the default behavior would be breaking and may obscure a misconfiguration.   We would have to add an additional parameter or overloads to allow callers to express the desire to create the container.  Callers would still need to understand the default behavior and know to set the option - which doesn't provide much convenience over creating the container externally.

I'm going to mark this as addressed and close, but please feel free to unresolve if you'd like to continue the discussion.
