### ISSUE TITLE
[FEATURE REQ] Name property on TableClient

### ISSUE THREAD

**Issue by Identifier** [Azure/azure-sdk-for-net#20799]
**Library or service name.**
Azure.Data.Tables
 
**Is your feature request related to a problem? Please describe.**
Hi, can we have a `public string Name { get; }` property on Azure.Data.Tables.TableClient?  All it needs to do is return the tableName that was determined in the constructor.  It's a nice to have that was there in previous versions of the CloudTableClient APIs.

**Comment by jsquire** [comment]
Hi @Identifier.  I'm happy to say that a [`Name`](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L39) property was added to the `TableClient` earlier this month with #20190.   @christothes would be the best person for insight on when that is expected to make its way into a release.

**Comment by Identifier** [comment]
Ah, great, thanks @jsquire and @christothes .  Yes, there are quite a few nice improvements I've seen in the latest version.  When will the next prerelease be?  (beta 8 I guess?)
