### ISSUE TITLE
Support caching in SecretClient.GetSecretAsync

### ISSUE THREAD

**Issue by jesperkristensen** [Azure/azure-sdk-for-net#20800]
**Library or service name.**
Azure.Security.KeyVault.Secrets
 
**Is your feature request related to a problem? Please describe.**
Getting secrets using SecretClient.GetSecretAsync is slow, and Key Vault has service limits that might be reachable without caching. It would be nice if SecretClient would handle that caching, so I don't have to build my own.

For example I am using Key Vault to store an API key. A system regularly rotates that API key and stores it in a Key Vault Secret. I know that the Key Vault Secret will be updated to contain the new API key at least X minutes before the old API key is revoked. I therefore want to cache the API key for a time span slightly less than X minutes.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Thanks for your suggestion. It is something we have discussed, but caching is an application concern with different constraints depending on how your application is hosted, lifetime management requirements, and more. We have options available, though, such as our Key Vault Proxy sample: https://docs.microsoft.com/samples/azure/azure-sdk-for-net/azure-key-vault-proxy/. You can use it as-is or copy the code and customize it to fit your needs.
