### ISSUE TITLE
AppServicesAuthenticationInformation.IsAppServicesAadAuthenticationEnabled does not get set for the new authentication experience

### ISSUE THREAD

**Issue by falconkirtaran** [Azure/azure-sdk-for-net#20801]
When enabling the classic authentication experience in Azure App Service, AppServicesAuthenticationInformation.IsAppServicesAadAuthenticationEnabled is true.  But, when I migrated to the new experience with Microsoft as the IdP, allowing only authentication against my AAD instance, now it is false.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dba9939d-a450-27a8-cc1d-a49da0212e68
* Version Independent ID: b5402f4d-bfbb-5c84-29a1-0785b5c95b30
* Content: [AppServicesAuthenticationInformation.IsAppServicesAadAuthenticationEnabled Property (Microsoft.Identity.Web) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.appservicesauthenticationinformation.isappservicesaadauthenticationenabled?view=azure-dotnet-preview#Microsoft_Identity_Web_AppServicesAuthenticationInformation_IsAppServicesAadAuthenticationEnabled)
* Content Source: [xml/Microsoft.Identity.Web/AppServicesAuthenticationInformation.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Web/AppServicesAuthenticationInformation.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue references documentation for the [`Microsoft.Identity.Web`](https://www.nuget.org/packages/Microsoft.Identity.Web/) package, which is hosted in the [AzureAD/microsoft-identity-web](https://github.com/AzureAD/microsoft-identity-web) repository.  I've transferred this there as [#1176](https://github.com/AzureAD/microsoft-identity-web/issues/1176)
