### ISSUE TITLE
Consider adding CreateIfNotExists to ServiceBusAdministrationClient

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#20814]
Currently, we expose the QueueExists/TopicExists/etc methods on the admin client.
The usage pattern is:
```cs
  if (!(await client.QueueExistsAsync(queueName)))
  {
      await client.CreateQueueAsync(queueName);
  }
```
This works fine if there is only ever one application or process that is responsible for creating an entity, but if there are multiple processes that may create an entity, this is inherently racy as the queue might get created between the two method calls, which would result in an exception.

These methods were carried forward from T1 due to the reasoning that there might be other scenarios where you just need to query the existence of an entity without necessarily creating it.

We should consider adding CreateQueueIfNotExists/CreateTopicIfNotExists/etc methods to better support the scenario of idempotent entity creation, similar to other T2 libraries like Storage.

**Comment by richardpark-msft** [comment]
If the race condition you mentioned above _does_ occur would you just throw on the .CreateQueue() call? Or would this method eat the exception or do something special in response if the error indicates the queue is already present?

**Comment by JoshLove-msft** [comment]
The way that the method would be implemented would be to just call CreateQueue and catch the 409 exception that is thrown if the queue already exists.

**Comment by richardpark-msft** [comment]
One edge case - a user is calling this method but they've changed the queue definition from what has currently been created. Would their expectation be that it might be updated? Or there'd be some indication that the queue's definition is different than what they passed in to our call?

I'm thinking we're okay because we're calling the method CreateIfNotExist() or similar (ie, not Upsert).

**Comment by richardpark-msft** [comment]
(incidentally - do you think what users are really looking for here is 'upsert')?

**Comment by JoshLove-msft** [comment]
> One edge case - a user is calling this method but they've changed the queue definition from what has currently been created. Would their expectation be that it might be updated? Or there'd be some indication that the queue's definition is different than what they passed in to our call?
> 
> I'm thinking we're okay because we're calling the method CreateIfNotExist() or similar (ie, not Upsert).

Ooh good point. I think the name of the method would make it clear what the semantics are, but it does detract a bit from the idempotence story.

> (incidentally - do you think what users are really looking for here is 'upsert')?

I don't think so.

**Comment by jsquire** [comment]
This hasn't moved forward in two years and there doesn't seem to be customer demand.  Closing out for now and we can revisit if we start to see feedback asking for it.
