### ISSUE TITLE
Response description is wrong, "A Azure.Response on successfully deleting."

### ISSUE THREAD

**Issue by bhavin07** [Azure/azure-sdk-for-net#20824]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8d9a8a80-10c4-4171-4a63-ecc45db5b1b5
* Version Independent ID: 2948b267-903f-3916-f94e-3d11da94c9b0
* Content: [BlobBaseClient.UndeleteAsync(CancellationToken) Method (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.undeleteasync?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amnguye** [comment]
Thanks for bringing this doc bug to our attention. Looks like it should have said Task<Response> instead of just response, even though a line above the doc it does state Task<Response> already.

**Comment by seanmcc-msft** [comment]
On the line above `A Response on successfully deleting.`, it clearly states `Returns Task<Response>`.
