### ISSUE TITLE
Is there a migration guide from v11 SDK's "Microsoft.Azure.Storage.DataMovement.TransferManager"?

### ISSUE THREAD

**Issue by mgroetan** [Azure/azure-sdk-for-net#20828]
**Query/Question**
We're using the "Microsoft.Azure.Storage.DataMovement.TransferManager" class in the v11 SDK to handle vast amounts of file copying between local disk and BLOB storage. This is a very integral part of our solution, and the current implementation is working quite well, even though we've had to implement some checksum/retry logic.

We're "of course" in the process of migrating to the new v12 SDK, and are having good progress on the "regular" BLOB handling elsewhere, through the "Azure.Storage.Blobs" package.
But we struggle to see a clear migration path for the "TransferManager" functionality. Can you point us in the right direction?

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.3
 - Hosting platform or OS and .NET runtime version: Azure AppService running .NET Core 3.1 and .NET Standard 2.0.
 - IDE and version : Visual Studio 16.9.4

**Comment by mgroetan** [comment]
And as mentioned over in the ["data movement" repo](https://github.com/Azure/azure-storage-net-data-movement/issues/270#issuecomment-829967894), the docs for "Data transfer" still points to the v11 SDK code examples.

**Comment by amnguye** [comment]
There's no migration guide because the development of the next generation of the Data Movement Library is still underway.

**Comment by domedellolio** [comment]
Hi @amnguye,

Q1: is there any update regarding "the next generation of the Data Movement Library"?.
Q2: From a guidance perspective, should we still continue to use Microsoft.Azure.Storage.DataMovement?

Thanks

**Comment by kinizumi** [comment]
I believe people are abandoning this library because of deprecates, what a shame
