### ISSUE TITLE
Integrate Samples into build

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#20842]
Verify sure that the new sample applications are being built at some regular interval. Also, use the repo-wide dependencies when being built within the repo.

**Comment by pakrym** [comment]
Do we have a similar problem with all the samples?

**Comment by JoshLove-msft** [comment]
I think work was done to ensure that the cross-app samples were being built, but yes, we should double check this. I seem to recall the linecounter sample app breaking due to the CloudEvent change, but the build not being affected so it's possible something has changed with samples in general.

**Comment by jsquire** [comment]
This work is done.
