### ISSUE TITLE
AppConfig: FeatureFlagConfigurationSettings  Update Value

### ISSUE THREAD

**Issue by Brendan510** [Azure/azure-sdk-for-net#20853]
**Query/Question**
Hi

I am using Feature Flags with Targeting and want to update the Target values (domain) programmatically

![Uploading firefox_n3tXL7xEcP.png…]()

Currently i am using 
 
```csharp
Response<ConfigurationSetting> response = client.GetConfigurationSetting(FeatureFlagConfigurationSetting.KeyPrefix + "zzzTest");
```

works great and i can obtain value edit string and insert additional domain. 
when i use below:- (strTarget = new value string for flag)

```csharp
ConfigurationSetting setting = client.SetConfigurationSetting(FeatureFlagConfigurationSetting.KeyPrefix + "zzzTest", strTarget);
```

the content-type of the flag gets voided and Key-Value is no longer a flag

if I use

```csharp
var featureFlagSetting = new FeatureFlagConfigurationSetting("zzztest", isEnabled: true);
            ConfigurationSetting setting = client.SetConfigurationSetting(featureFlagSetting, strTarget);
```

I get similar response and a new unwanted configuration. 

Am i Doing this wrong?? Is there a way to update Feature Flags value programmatically or perhaps with post? I couldn't find a put in the API.

my controller action used for test is below=>

```csharp
[HttpPost]
        public IActionResult Create(PartnerList partner)
        {
if (ModelState.IsValid)
            {
                PartnerList newpartner = _partnerManager.Add(partner);
            }
            string connectionString = _configuration.GetValue<string>("ConnectionStrings:AppConfig");
            var client = new ConfigurationClient(connectionString);
            Response<ConfigurationSetting> response = client.GetConfigurationSetting(FeatureFlagConfigurationSetting.KeyPrefix + "zzzTest");
            int n = 32;
            var respond = response.Value.ToString().Remove(0, n);
            var finalrespond = respond.Remove(respond.Length - 1);
            // string user = "],\"Groups";
            string group = "],\"DefaultRolloutPercentage\"";
            // string newuser = ",\"testUser@test.com\"";
            string newgroup = ",{\"Name\":\"" + partner.PartnerName + "\",\"RolloutPercentage\":3}";
            string strTarget = finalrespond;
            // strTarget = strTarget.Insert(strTarget.IndexOf(user), newuser);
            strTarget = strTarget.Insert(strTarget.IndexOf(group), newgroup);
            // var featureFlagSetting = new FeatureFlagConfigurationSetting("zzztest", isEnabled: true);
            ConfigurationSetting setting = client.SetConfigurationSetting(FeatureFlagConfigurationSetting.KeyPrefix + "zzzTest", strTarget);
   return RedirectToAction("Create");     
        }
```

** I haven't incremented RolloutPercentage index yet , but this shouldn't effect update content-type? or will it?**

Image below from Azure Portal of changed flag
![Uploading devenv_xk6e35Q1H4.png…]()

**Environment:**
  Azure.Data.AppConfiguration 1.1.0-beta.2
![image](https://user-images.githubusercontent.com/3981053/117118365-07c5af00-add4-11eb-9c44-be26789f86aa.png)
Azure AppService application
Visual Studio 2019 community 16.9.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
You should be able to update the value of existing setting using the following code:

``` C#
ConfigurationSetting setting = client.GetConfigurationSetting(FeatureFlagConfigurationSetting.KeyPrefix + "zzzTest");

setting.Value = ...;

client.SetConfigurationSetting(setting);
```

**Comment by Brendan510** [comment]
Thanks Pavel
I knew i must of missed something ,
 your solution worked perfectly,
