### ISSUE TITLE
[BUG] RenewMessageLockTask and starvation.

### ISSUE THREAD

**Issue by qsdfplkj** [Azure/azure-sdk-for-net#20874]
I have a lot of message in a queue. When all those messages are being process the RenewMessageLockTask in the MessageReceivePump seems to be waiting longer than the Task.Delay that is used in it. (Thread starvation?) And eventually triggers a MessageLockLostexception once it gets executed long after the message lock expires.

It might be related but I use transactions on the queue and all the actions take only a few hundred milliseconds.

I think when all the transactions on the queue try to commit somehow all the available threads are being locked and the RenewMessageLockTask just doesn't continue because there isn't any thread available? 

I can simple prevent this issue from reducing the maxConcurrentcalls (to be less than the number of cpu-cores) in the host.json but that just reduced the throughput and feels more like a work around than a solution.

**Comment by qsdfplkj** [comment]
Additionally  maxConcurrentCalls it's documented default is 16 but when inspecting in the debugger it seems to be Environment.ProcessorCount * 16?  Increasing ThreadPool.SetMinThreads(Environment.ProcessorCount * 16, Environment.ProcessorCount * 16); seems to increase througput and shows that messages in a transaction are not renewed?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
@qsdfplkj  - Can you clarify what package you are using? It looks like this issue is for the Microsoft.Azure.ServiceBus package.

**Comment by qsdfplkj** [comment]
> @qsdfplkj - Can you clarify what package you are using? It looks like this issue is for the Microsoft.Azure.ServiceBus package.

Microsoft.Azure.ServiceBus 5.1.3

**Comment by ramya-rao-a** [comment]
@qsdfplkj Apologies for the delay in response here. 

Please note that the Microsoft.Azure.ServiceBus package is now deprecated. A newer package Azure.Messaging.ServiceBus is available as of November 2020. While the older package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the [getting started guide](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues) and  [migration guide](https://aka.ms/azsdk/net/migrate/sb) for more details.

If you still have issues using the older Microsoft.Azure.ServiceBus package, please use your [Azure support plan](https://azure.microsoft.com/support/options/) to open an [Azure support ticket](https://azure.microsoft.com/support/create-ticket/).
