### ISSUE TITLE
[BUG] BlobClient.ExistsAsync method throws Azure.RequestFailedException when blob does not exist

### ISSUE THREAD

**Issue by VladimirKhvostov** [Azure/azure-sdk-for-net#20882]
**Describe the bug**
BlobClient.ExistsAsync method throws Azure.RequestFailedException when blob does not exist and catches it internally. 
It is NOT unexpected to not have the blob when someone calls ExistsAsync method.
AppInsights writes errors into dependency channel in this case. which produces a lot of noise and makes it more difficult to investigate real issues.

**Expected behavior**
ExistsAsync should not throw RequestFailedException on 404 and 

**Actual behavior (include Exception or Stack Trace)**
App Insights telemetry:
```
{
  "tag": "mdsd.applog.dependencies",
  "id": "60dfc8d9959d6a4e",
  "name": "BlobBaseClient.Exists",
  "success": false,
  "duration": "00:00:00.1766709",
  "data": "",
  "target": "",
  "type": "InProc | Microsoft.Storage",
  "resultCode": "",
  "operation_Id": "54b44b8581ad764f81c2e93cf0172c69",
  "cloud_RoleInstance": "vk-ryzen",
  "timestamp": "2021-05-06T15:12:20.4250869+00:00",
  "application_Version": "1.0.0.0",
  "env": "Development",
  "customDimensions": {
    "AspNetCoreEnvironment": "Development",
    "Error": "Azure.RequestFailedException: Service request failed.\r\nStatus: 404 (The specified blob does not exist.)\r\nErrorCode: BlobNotFound\r\n\r\nHeaders:\r\nTransfer-Encoding: chunked\r\nServer: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0\r\nx-ms-request-id: 032ac84c-601e-00fd-458a-42f30f000000\r\nx-ms-client-request-id: 0bbd8a22-63f2-40db-8c85-4340b560a9a3\r\nx-ms-version: 2020-04-08\r\nx-ms-error-code: BlobNotFound\r\nDate: Thu, 06 May 2021 15:12:20 GMT\r\n\r\n   at Azure.Storage.Blobs.BlobRestClient.Blob.GetPropertiesAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)\r\n   at Azure.Storage.Blobs.BlobRestClient.Blob.GetPropertiesAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, String snapshot, String versionId, Nullable`1 timeout, String leaseId, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String ifTags, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)"
  }
}

```

**To Reproduce**
Call BlobClient.ExistsAsync method. Make sure blob does not exist.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by amnguye** [comment]
Looks like this is related to https://github.com/Azure/azure-sdk-for-net/issues/19982 (Exists and CreateIfNotExists work very similarly where it catches 404 errors like `BlobNotFound`)

**Comment by seanmcc-msft** [comment]
Is your request property authenticated?  I believe the storage service returns a 404 instead of a 403 if there is an authentication problem for security reasons.

**Comment by amnguye** [comment]
Please reactivate with the queries above being answered.
