### ISSUE TITLE
Migrate JWT parsing to Core

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#20883]
We've implemented one-off JWT parsing in [ContainerRegistryRefreshTokenCache.cs](https://github.com/Azure/azure-sdk-for-net/blob/acd54421aca8d52bf23810415987b9e7d61afe96/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Authentication/ContainerRegistryRefreshTokenCache.cs#L240) to obtain the expiration date from the returned ACR refresh token.

Consider generalizing this logic and moving it into Core/Shared.

**Comment by pallavit** [comment]
Given ACR refresh token is different from other tokens do you see value in bringing this code into core? What metrics do you have in mind that will help us make this call?

As of now we have very few SDKs having to do this outside of identity SDK. And this should remain an anomaly i.e. it will benefit only those services that do not follow the usual patterns of authentication and implement their own scheme.

**Comment by annelo-msft** [comment]
I don't think we'd move this to Azure.Core unless we were doing it in other client libraries and wanted to centralize the functionality.  If Identity was doing it (I think I had discussed with either @schaabs or @christothes?), it might make sense to put it in one place, but if it's simple parsing to a standard, it may not be needed, esp with the advent of DynamicData.

**Comment by pallavit** [comment]
That was my mental model as well. How about I close this issue and we can reopen if we see multiple feature asks where this is needed in core? I would still see this mostly as a helper extension than anything else. Do we have a natural place in core for extension methods\helpers which is not shared code :P

**Comment by christothes** [comment]
JWT parsing should be rare, so I'd hesitate to put it in Core. Usually, the parsing is very scenario specific rather than generalized.

**Comment by annelo-msft** [comment]
>  Do we have a natural place in core for extension methods\helpers which is not shared code

We don't tend to put extension methods in Core APIs.  We have a very few of them with very specific and clear scenarios.

Regarding helpers - we have many internal types that implement helper functionality within the Core library. We'd want to look case-by-case at scenarios for anything that would qualify as a "helper" that's needed outside of Core.

**Comment by pallavit** [comment]
> Regarding helpers - we have many internal types that implement helper functionality within the Core library. We'd want to look case-by-case at scenarios for anything that would qualify as a "helper" that's needed outside of Core.

Ahh so we don't have public helper classes that other SDKs\libraries can benefit from - I believe we rely on shared code to make those internal.

Thanks, given @christothes , let me know if you have any concerns with closing this issue.

**Comment by annelo-msft** [comment]
Not explicitly, no.  We discussed possibly making Argument public in ClientModel, but decided not to prioritize that as part of that effort.

We may want to look at the helpers question as part of https://github.com/Azure/azure-sdk-for-net/issues/28369.  We have a goal to make shared source go away for various reasons that we'd like to move toward over time.

**Comment by pallavit** [comment]
Given we wouldn't want to expose Jwt functionality in core (as that is a very advanced scenario) and common pieces there would be limited, I am going ahead and closing this issue. 

As @annelo-msft mentioned we may consider exposing Helper\Utility classes as part of Core APIs at some point in future. I have added those details to the above link shared. 

/cc: @christothes as FYI
