### ISSUE TITLE
[QUERY] Enforce Message ordering obsolete?

### ISSUE THREAD

**Issue by lindgrend** [Azure/azure-sdk-for-net#20908]
**Query/Question**
We are upgrading from an older nuget and there used to be a property 'Enforce Message Ordering' when creating or updating a queue. This is now gone does this mean that it can just be ignored or am I missing something?

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ServiceBus.Management 2.1.0
 - Hosting platform or OS and .NET runtime version: Windows 10  Microsoft.NETCore.App 3.1.13 
 - IDE and version : Visual Studio 16.9.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ramya-rao-a** [comment]
Hey @lindgrend 

I am assuming that you are referring to the [SupportOrdering property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queuedescription.supportordering?view=azure-dotnet) in the older package.

We have this property on topics, but have intentionally removed it for queues.

Below is the justification we got from the Service Bus team

> SupportOrdering indicates if messages are sequenced or received in the same order they are sent. If partitioned entity, defaults to false and setting it to true has no effect. For non-partitioned entities, it is always true for a queue. Setting it to false has no effect. For non-partitioned topics, setting it to false will improve perf, but messages may not received in the order they are sent

**Comment by ramya-rao-a** [comment]
Additionally, please note that a newer package Azure.Messaging.ServiceBus is available as of November 2020. While the older package Microsoft.Azure.ServiceBus will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the migration guide at https://aka.ms/azsdk/net/migrate/sb for more details.
