### ISSUE TITLE
[BUG] Azure Trigger Functions - Migrating to Azure.Messaging.EventHubs from Microsoft.Azure.EventHubs

### ISSUE THREAD

**Issue by yigitgursoy** [Azure/azure-sdk-for-net#20916]
**Describe the bug**
We've been using Microsoft.Azure.EventHubs NuGet package in our Azure Functions on live environments for a couple of years. Recently we've been advised by the Microsoft support team to migrate to Azure.Messaging.EventHubs package. However, the new package doesn't support all of the features of the old one.

**Expected behaviour**
The expected behaviour is for trigger functions (EventHubs input and SignalR output) to operate the same way as they did with the legacy package.
With the legacy package, the EventData[] array can be used as a function parameter as shown under "To Reproduce" section below.

Also, it's stated in the documentation that the legacy package should be used to get access to event metadata:
> To get access to event metadata in function code, bind to an EventData object (requires a using statement for Microsoft.Azure.EventHubs). You can also access the same properties by using binding expressions in the method signature. The following example shows both ways to get the same data:
Source: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=csharp

**Actual behaviour (include Exception or Stack Trace)**
EventData[] or EventData object under Azure.Messaging.EventHubs isn't supported by trigger functions. Check exception below.

```
 [2021-05-07T15:03:42.667Z] System.Private.CoreLib: Exception while executing function:******Trigger. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'eventHubMessages'. Microsoft.Azure.WebJobs.Host: Binding parameters to complex objects (such as 'EventData') uses Json.NET serialization.
 1. Bind the parameter type as 'string' instead of 'EventData' to get the raw values and avoid JSON deserialization, or
 2. Change the queue payload to be valid json. The JSON parser failed: Unable to find a constructor to use for type Azure.Messaging.EventHubs.EventData. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'IdempotentId', line 1, position 16.
```

Option 1 isn't an option for us because we use some of the data stored in the event metadata.

**To Reproduce**
Steps to reproduce the behaviour (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Code example to reproduce the issue:
```csharp
using Azure.Messaging.EventHubs;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.SignalRService;
using System.Threading.Tasks;

[FunctionName("MessagesEventHubTrigger")]
public async Task Run([EventHubTrigger("%MessagesEventHubName%", Connection = "MessagesEventHubConnection")] EventData[] eventHubMessages, [SignalR(HubName = "messageHub", ConnectionStringSetting = "Azure:SignalR:ConnectionString")] IAsyncCollector<SignalRMessage> signalRMessages)
{
    .....
}
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 

Package versions that we use:
PackageReference Include="Azure.Messaging.EventHubs" Version="5.4.0"
PackageReference Include="Azure.Messaging.EventHubs.Processor" Version="5.4.0"
PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0"
PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.2.0"
PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11"
PackageReference Include="Newtonsoft.Json" Version="13.0.1"
PackageReference Include="Microsoft.Azure.WebJobs.Extensions.SignalRService" Version="1.3.0"

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 
 
.NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.202\

Host (useful for support):
  Version: 5.0.5
  Commit:  2f740adc14

.NET SDKs installed:
  2.1.815 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.All 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 - IDE and version : [e.g. Visual Studio 16.3]

Microsoft Visual Studio Professional 2019 Version 16.9.4

**Comment by jsquire** [comment]
Hi @yigitgursoy.  Thank you for reaching out and we regret that you're experiencing difficulties.  The behavior that you're seeing is because the Functions bindings currently use `Microsoft.Azure.EventHubs` while the body of your function is using `Azure.Messaging.EventHubs`.   We're currently working to update the bindings, which are available as a beta;  updating [`Microsoft.Azure.WebJobs.Extensions.EventHub`](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs/5.0.0-beta.4) to the v5.x set of betas will resolve the issue.

If you're unable to use the beta bindings, there are a couple of ways to work around this:

- Continue using `Microsoft.Azure.EventHubs` until the v5.x line of bindings is released to GA.

- Explicitly reference `Microsoft.Azure.EventHubs.EventData` as your incoming parameter.  This should allow the binding to function.    You will have to manually map the `Microsoft.Azure.EventHubs` types to their `Azure.Messaging.EventHubs` types in the body of the function, including the `EventData` if you're doing any Event Hubs-specific operations.  Likewise, if you're using any output bindings, you'd have to translate back to the `Microsoft.Azure.EventHubs` types.

**Comment by yigitgursoy** [comment]
Thanks @jsquire
