### ISSUE TITLE
RequestOptions in Azure.Core.Experimental should have a Default

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-for-net#20913]
As noted [here](https://github.com/Azure/autorest.csharp/pull/1219#discussion_r627734348):

```
We should add an RequestOptions.Default or something for this case, to save ourselves the allocation on each call. 
```

**Comment by jsquire** [comment]
Closing out; the type no longer exists in Experimental and does not seem to exist in the same form in Core.

**Comment by annelo-msft** [comment]
For posterity - this issue is tracking similar work: https://github.com/Azure/azure-sdk-for-net/issues/29015
