### ISSUE TITLE
ServiceBusTransportType is always AmqpTcp

### ISSUE THREAD

**Issue by kepar** [Azure/azure-sdk-for-net#20910]
**Describe the bug**
When creating a new ServiceBusClient the ServiceBusTransportType configured via options or the connectionstring is ignored.
the resulting TransportType is always AmqpTcp.

**Expected behavior**
ServiceBusTransportType.AmqpWebSockets should be used

**Actual behavior (include Exception or Stack Trace)**
Wrong Transporttype is used, and gets blocked by corporate firewall.

**To Reproduce**
1. new console application

2. Add PackageReference to "zure.Messaging.ServiceBus Version 7.1.2

```
    var client = new ServiceBusClient(connectionString, new ServiceBusClientOptions { TransportType = ServiceBusTransportType.AmqpWebSockets });
              
    if (client.TransportType != ServiceBusTransportType.AmqpWebSockets)
    {
        throw new NotImplementedException();
    }
```
or
```
    var client = new ServiceBusClient(connectionString + ";TransportType=AmqpWebSockets");

    if (client.TransportType != ServiceBusTransportType.AmqpWebSockets)
    {
        throw new NotImplementedException();
    }
```

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.ServiceBus 7.1.2
 - Hosting platform or OS and .NET runtime version: Windows 10 .net Core 3.1
 - IDE and version : Visual Studio 16.9.4

**Comment by kepar** [comment]
Hi @jsquire Thank u for the prompt reply!

I was indeed a bit to focused on the `ServiceBusClient.TransportType` property.
after some more tests I found that when using ";TransportType=AmqpWebSockets" in the connection string

`var client = new ServiceBusClient(connectionString + ";TransportType=AmqpWebSockets");`

the internal TransportType is not "correct" or maybe this is no longer supported:
![image](https://user-images.githubusercontent.com/1457302/117474867-afb9b480-af5b-11eb-850c-2ab7be0956ef.png)

with this exception as a result:

"A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

I can confirm it works as expected now when using the `ServiceBusClientOptions` (here I focused to much on the TransportType property without stepping further through my program)

so al that remains is the bug where the transport type isn't being reflected correctly in the ServiceBusClient property (when using the ServiceBusClientOptions)

**Comment by jsquire** [comment]
Hi @kepar.   You are correct that the transport type must be set as an option; we don't support configuration of the clients via connection string - just the basic form needed to establish a connection and available in the Azure portal.

**Comment by jsquire** [comment]
I just fixed up the property mismatch and added some additional context around the connection string semantics.    I'm going to close this out, but please feel free to reopen if you'd like to discuss further.
