### ISSUE TITLE
Corrections to docs

### ISSUE THREAD

**Issue by JamesDuggan** [Azure/azure-sdk-for-net#20914]
Really great to see this feature becoming available. Is there any visibility on when the SDK will be GA? 

On the docs:
1. <event_hub_name>.servicebus.windows.net should be <event_hub_namespace_name>.servicebus.windows.net.
2. on configuring identity it would be useful to include this section https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#grant-permission-to-the-identity or link to it 

Thanks

James

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c172402-1297-fb7f-0fa0-6be8f5b8f1d6
* Version Independent ID: 3875c979-e888-9f90-86b3-c542a881b6c4
* Content: [Azure WebJobs Event Hubs client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.eventhubs-readme-pre)
* Content Source: [api/overview/azure/microsoft.azure.webjobs.extensions.eventhubs-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/microsoft.azure.webjobs.extensions.eventhubs-readme-pre.md)
* Service: **webjobs**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
Hi @JamesDuggan.  Thank you for your feedback.   I've got a pull request (#20924) out to correct the typo and take your suggestion on the permissions links.   Those corrections should get published with the next release.

**Comment by jsquire** [comment]
I'm going to close this out since the changes have been merged; please feel free to reopen if you would like to discuss further.
