### ISSUE TITLE
BlobClient.DownloadContent() methods do not exist, these should be removed from documentation and migration guide

### ISSUE THREAD

**Issue by RostumAhady** [Azure/azure-sdk-for-net#20912]
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md
the migration guide as well as the documentation suggests to use DownloadContent() for downloading text. However BlobClient.DownloadContent() does not exist as a usable method and should be removed from the documentation and migration guide. The method I assume was inherited from BlobBaseClient

Should we be using BlobClient.Download() instead? And utilising BlobDownloadInfo instead of BlobDownloadResult?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653ab58-62b8-9eac-d2e5-b444c3e1da56
* Version Independent ID: c2c0cf2a-8e2a-d769-eada-fb4943e0db02
* Content: [BlobBaseClient.DownloadContent Method (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.downloadcontent?view=azure-dotnet-preview&viewFallbackFrom=azure-dotnet#Azure_Storage_Blobs_Specialized_BlobBaseClient_DownloadContent)
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amnguye** [comment]
I don't think this is a bug, `BlobClient.DownloadContent` and `BlobClient.DownloadContentAsync` do exist as usual methods. Your assumption is correct they are both inherited from `BlobBaseClient`.

Could you recheck your environment? It would be useful to provide the version of Azure.Storage.Blobs, version of Net Framework or core you are using as well.

**Comment by kasobol-msft** [comment]
These are available in latest beta. Docs pages will get this updated soon - when we GA these new APIs.
