### ISSUE TITLE
Search SDK: Make sure to only use property names that are defined by the type

### ISSUE THREAD

**Issue by harsh288** [Azure/azure-sdk-for-net#2092]
Hello,

I have updated to latest azure sdk for .net taken from nutget, I managed to fix lot of bugs post upgrade however I 'm stuck at **IndexManager.IndexClient.Documents.Index(batch);**
which gives error "**The request is invalid. Details: parameters : The property 'indexEntityType' does not exist on type 'search.documentFields'. Make sure to only use property names that are defined by the type**"
The same code is working for old sdk but not for the new one, please help me to resolve.

**Comment by brjohnstmsft** [comment]
@harsh288 Can you please share the code that you use to construct the batch (including the type you're using to represent your documents, if you're using Index<T>), as well as your index definition?

**Comment by harsh288** [comment]
Well I commented the class which was been interfaced and it was working however I need to understand where I need to mention interface details in "search.documentfields"

public interface IIndexEntityBase
    {
        IndexEntityType IndexEntityType { get; set; }
    }

public class IndexEntityBase : IIndexEntityBase
    {
        public IndexEntityType IndexEntityType { get; set; }

        public override string ToString()
        {
            return IndexEntityType.ToString();
        }
    }
    public enum IndexEntityType
    {
        A,
        B,
        C
    }

public class Cust //: IndexEntityBase			//After Commenting indexEntityBase code works 
    {
        public string Id { get; set; }
        public string CustomerId { get; set; }
        public string CustomerName { get; set; }
        public DateTimeOffset? ModifiedOn { get; set; }
        public DateTimeOffset? CreatedOn { get; set; }
             
        public override string ToString()
        {
            return CustomerName;
        }
    }

Post that we create drop index and recreate the same index and then have our document obj ready using azure sql database.

var batch = IndexBatch.Upload(documents);
 IndexManager.IndexClient.Documents.Index(batch);    // This line gives error if interface entity type is not commented

**Comment by brjohnstmsft** [comment]
I'm not sure how this would have worked with the old SDK. In general you can't have properties on your model class that don't map to fields in your index. To exclude `IndexEntityType` from being sent to the index, mark it with the `[JsonIgnore]` attribute.

**Comment by harsh288** [comment]
Sorry for replying late, thanks a lot that helped.

**Comment by tomasjurasek** [comment]
Hi, i have same issue. 
I created index by SDK 

```
var definition = new Index()
            {
                Name = index,
                Fields = FieldBuilder.BuildForType<NewsletterAzureSearch>()
            };
```

And when i want upload some document
```
var action = new IndexAction<NewsletterAzureSearch>[]
            {
                IndexAction.Upload(model)
            };

            try
            {
                var batch = IndexBatch.Upload(action);
                searchClient.Documents.Index(batch);
            }
            catch (Exception ex)
            {
                var a = ex;
                throw;
            }
```

I get error :  **The request is invalid. Details: parameters : The property 'ActionType' does not exist on type 'search.documentFields'. Make sure to only use property names that are defined by the type.**
here is my model
```
public class NewsletterAzureSearch
    {
        [IsFilterable]
        public string Id { get; set; }
        [IsSearchable]
        public string Name { get; set; }
        [IsSearchable]
        public string Description { get; set; }
    }

```
