### ISSUE TITLE
[QUERY] How do I programmatically set-up storage account access keys for auto rotation in key vault?

### ISSUE THREAD

**Issue by aniruddhagore1984** [Azure/azure-sdk-for-net#20941]
**Query/Question**
I intend to accomplish the following:

1) create a storage account
2) create a key vault
3) add the storage account to the key vault aka add access keys to vault
4) set-up storage access keys for auto rotation

I am developing in C# and have managed to accomplish (1) and (2) but not getting any help in docs for (3) and (4). Could you please point me in the right direction?

**Environment:**
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Framework
 - IDE and version : Visual Studio

**Comment by blueww** [comment]
@aniruddhagore1984 

From storage SDK side, first you will need assign an ideneity to the storage account, and get the account identity ID, like following.
```
                var updateParameters = new StorageAccountUpdateParameters()
                {
                    Identity = new Identity() { Type = IdentityType.SystemAssigned }
                };
                account = storageMgmtClient.StorageAccounts.Update(rgname, accountName, updateParameters);
                string accountId = account.Identity.PrincipalId;
```

Then you need give the `accountId ` wrapkey,unwrapkey,get access to the keyvault, and you also need create a key with Destination  as Software in the keyvault. This part depends on Keyvault SDK.

Finally, you can update the keyvault key information to the storage account. As you need enabled key auto rotation, just skip set key version.
```
updateParameters = new StorageAccountUpdateParameters
                {
                    Encryption = new Encryption
                    {
                        Services = new EncryptionServices { Blob = new EncryptionService { Enabled = true }, File = new EncryptionService { Enabled = true } },
                        KeySource = "Microsoft.Keyvault",
                        KeyVaultProperties =
                            new KeyVaultProperties
                            {
                                KeyName = keyVaultKey.KeyIdentifier.Name,
                                KeyVaultUri = keyVault.Properties.VaultUri
                            }
                    }
                };

                account = storageMgmtClient.StorageAccounts.Update(rgname, accountName, updateParameters);
```

**Comment by jlichwa** [comment]
@aniruddhagore1984  if you are looking for managed storage account keys feature, here is the sample in .NET https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/share-link/

This feature does not add storage account key to key vault, just use Key Vault to manage access by generating storage account keys SAS tokens, more can be find here:
https://docs.microsoft.com/en-us/azure/key-vault/secrets/overview-storage-keys

Other than that when direct access to keys is required, key vault does not provide any built in way to rotate access keys in key vault besides using function like here:
https://docs.microsoft.com/en-us/azure/key-vault/secrets/tutorial-rotation-dual?tabs=azure-cli
