### ISSUE TITLE
ServiceRuntime dependency and 32/64-bit issues

### ISSUE THREAD

**Issue by bgever** [Azure/azure-sdk-for-net#2096]
In our projects we depend on the `Microsoft.WindowsAzure.ServiceRuntime` assembly and in particular the `Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment` type for run-time diagnostics to tell us more about the role and instance information so that we know where our services are running and that we can include that in our application logs.

We can find and include a reference to the ServiceRuntime from the SDK installation path. However there are several assembly files with the same name (example for v2.9):
```
C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\ref\Microsoft.WindowsAzure.ServiceRuntime.dll
C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\runtimes\base\Microsoft.WindowsAzure.ServiceRuntime.dll
C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\runtimes\base\x86\Microsoft.WindowsAzure.ServiceRuntime.dll
C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\runtimes\base\x64\Microsoft.WindowsAzure.ServiceRuntime.dll
C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\runtimes\NET45\base\Microsoft.WindowsAzure.ServiceRuntime.dll
C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\runtimes\NET45\base\x86\Microsoft.WindowsAzure.ServiceRuntime.dll
C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\runtimes\NET45\base\x64\Microsoft.WindowsAzure.ServiceRuntime.dll
```

My guess is, the first one in the `ref` folder, means it's for *reference purpose*?
What is the difference with the other ones?

However, when I do reference the one in the ref folder, and deploy to Azure App Service, where IIS runs as 32-bit by default, then I get at random a run-time binding exception related to the `msshrtmi` assembly. (horrible to pronounce btw :wink:)
This can be solved by explicitly referencing in the project the 32-bit version of that assembly from the Azure SDK:
```
C:\Program Files\Microsoft SDKs\Azure\.NET SDK\v2.9\bin\runtimes\base\x86\msshrtmi.dll
```
Again, there are multiple versions of this assembly in different paths. For instance, if I target .NET 4.5+, should I use the one in the NET45 folder instead?

Now I was looking through the SDK source code, and I spotted the following in the [internal `AzureApplicationSettings` class](https://github.com/Azure/azure-sdk-for-net/blob/master/src/Common/Configuration/AzureApplicationSettings.cs):
```cs
/// <summary>
/// Loads and returns the latest available version of the service 
/// runtime assembly.
/// </summary>
/// <returns>Loaded assembly, if any.</returns>
[SuppressMessage("Microsoft.Reliability", "CA2001:AvoidCallingProblematicMethods", MessageId = "System.Reflection.Assembly.LoadFrom",
    Justification = "The ServiceRuntime.dll has to be loaded at runtime so calling Assembly.LoadFrom method is essential to do the loading")]
private Assembly GetServiceRuntimeAssembly()
```

This is used in the SDK to get a reference to the assembly and access its classes through reflection.

Is this the way how we should do it in our own code as well? If so, should this method be made available publicly?

**Comment by hovsepm** [comment]
@bgever Sorry for the confusion but this repo contains Azure Management SDK sources only and has nothing to do with Azure .Net SDK sources you mention. Please file an issue through azure portal.
