### ISSUE TITLE
Azure.Storage.Blobs.ChangeFeed: expose the blobVersion from avro file

### ISSUE THREAD

**Issue by msfcolombo** [Azure/azure-sdk-for-net#20969]
Please expose the `blobVersion` field in the `Azure.Storage.Blobs.ChangeFeed` library. The blob version identifier is required for accurate snapshot and point-in-time recovery. Without the blob version, the changefeed processor needs to list blob properties in order to match by `etag`, which is not efficient. The blob version identifier allows blob version to be retrieved in a single request to [Get Blob](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob) API (see `versionid` URI parameter).

As of `12.0.0-preview.11` of the changefeed library, the `blobVersion` field is not exposed. It only exposes EventTime and Etag properties.

It appears that the change is very small. You only have to change the definition and constructor at [BlobChangeFeedEventData](https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/storage/Azure.Storage.Blobs.ChangeFeed/src/Models/BlobChangeFeedEventData.cs#L21). I verified that the `record` argument already contains the `blobVersion` with the right value (i.e. you are already reading the value; you are just not exposing it).

**Comment by amnguye** [comment]
Adding feature request label to this

**Comment by msfcolombo** [comment]
Hello. Is there an ETA for this? Has the feature request been accepted?

**Comment by amnguye** [comment]
Looks like in the current version of changefeed we started parsing the blob version.
See
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs.ChangeFeed/src/Models/BlobChangeFeedEventData.cs#L36
and
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs.ChangeFeed/src/Models/BlobChangeFeedEventData.cs#L106

I don't believe it's valid for us to change the constructor of BlobChangeFeedEventData for getting the version id, and can be easily obtainable in the `BlobChangeFeedEventData.BlobVersion` property.

Reopen if there's any questions.
