### ISSUE TITLE
Is there a replacement for Microsoft.Azure.EventHubs.ServiceFabricProcessor?

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-sdk-for-net#20972]
Now, when Microsoft.Azure.EventHubs is deprecated and we have to migrate to use Azure.Messaging.EventHubs instead of it... Is there a replacement for Microsoft.Azure.EventHubs.ServiceFabricProcessor (which still uses Microsoft.Azure.EventHubs)?

**Comment by jsquire** [comment]
The current `ServiceFabricProcessor` is still a pre-release version, so the standard guidance about the risks of using a non-GA library in a production environment apply.  That said, if you're using it today and are comfortable with the risk, it is no less safe today than it was yesterday.  The `Microsoft.Azure.EventHubs.*` family of packages will continue to be supported and receive critical fixes for the foreseeable future, though it will no longer be receiving feature updates.   To my knowledge, there's no definitive answer to whether it will receive a GA release.

For new development where you do not have an existing investment in the legacy package, the recommendation would be to build on the `Azure.Messaging.EventHubs.*` family of packages; for the equivalent deep integration with Service Fabric, extending the [`EventProcessor<TPartition>`](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessor-1) would likely be the best option.  A sample for creating a custom processor can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample08_CustomEventProcessor.md) and the Azure SDK blog article [Building A Custom Event Hubs Event Processor with .NET](https://devblogs.microsoft.com/azure-sdk/custom-event-processor/) discusses doing so in greater detail.

**Comment by dmytro-gokun** [comment]
@jsquire Thanks a lot!
