### ISSUE TITLE
CloudConfigurationManager documentation

### ISSUE THREAD

**Issue by sixpi** [Azure/azure-sdk-for-net#2100]
The documentation link in the nuget package points to https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.cloudconfigurationmanager.aspx, which appears to be a dead link. While we could just look at the source code, it would be nice to have some documentation somewhere.

**Comment by markcowl** [comment]
### Description 

search for offical documentation.  If found, update the link in the package.  If not, remove the documentation link.

**Comment by cormacpayne** [comment]
@markcowl it looks like the only docs remaining for `CloudConfigurationManager` are the following:

https://msdn.microsoft.com/en-us/library/azure/mt634650.aspx

https://msdn.microsoft.com/en-us/library/azure/mt634649.aspx

**Comment by twitchax** [comment]
@sixpi, from where are you getting this link?

**Comment by sixpi** [comment]
This was a while ago so I can't be sure, but I think I got that link from the Azure Configuration Manager nuget page (https://www.nuget.org/packages/Microsoft.WindowsAzure.ConfigurationManager/3.2.3). If you click on the "Project Site" link on the left side, it takes you to the link I originally posted.

**Comment by twitchax** [comment]
Ahhh, yes, thanks for the information!

**Comment by xt0rted** [comment]
Just ran into this issue. Was hoping to land on this repo so I could look at the source, instead I was sent to a page that no longer exists.

The link in question came from [Microsoft.WindowsAzure.ConfigurationManager.nuspec#L10](https://github.com/Azure/azure-sdk-for-net/blob/7a44e44a5ec45cc2ee822b927cd91aa705e18549/src/Common/Configuration/Microsoft.WindowsAzure.ConfigurationManager.nuspec#L10) and sent me to https://msdn.microsoft.com/en-us/library/microsoft.windowsazure.cloudconfigurationmanager.aspx

**Comment by sixpi** [comment]
Looks like this package has been renamed to https://www.nuget.org/packages/Microsoft.Azure.ConfigurationManager/.
