### ISSUE TITLE
[BUG] Blob Storage Query Acceleration SQL API Hard Limit on 49 Explicit Columns

### ISSUE THREAD

**Issue by deenairn** [Azure/azure-sdk-for-net#21011]
**Describe the bug**

Using the .NET API to run Query Acceleration there appears to be a hard limit on the explicit selection of 49 columns or less. This is (as far as I can tell) not documented anywhere. 

For us, we could have >= 50 columns and would like to select a subset. It doesn't appear to be related to the query length as using the _1, _2, etc syntax results in the same problem.

Oddly the API works when using the * syntax, with the resulting workaround being that we need to return all the columns. This seems overly limited and I am curious as to if there is some underlying reason behind this?

The query and error is as follows, returned from .NET API, but clearly an error from the underlying Web API.

**Expected behavior**

Underlying Web API would be changed to allow explicit selection of > 49 columns. If this is impossible, this hard limit should be documented at the [Query Acceleration SQL language reference](https://docs.microsoft.com/en-us/azure/storage/blobs/query-acceleration-sql-reference).

**Actual behavior (include Exception or Stack Trace)**

This query is successful.
`
SELECT _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49 FROM BlobStorage LIMIT 10
`

This query is not successful
`
SELECT _1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23, _24, _25, _26, _27, _28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47, _48, _49, _50 FROM BlobStorage LIMIT 10
`

Following status is reported from .NET API for the second query:

```
Exception: Azure.RequestFailedException: Service request failed.
Status: 400 (Syntax error!)
ErrorCode: ErrorProcessingQueryExpression

Headers:
x-ms-error-code: ErrorProcessingQueryExpression
x-ms-request-id: aa82517b-301e-008f-18b0-46dea1000000
x-ms-version: 2020-04-08
x-ms-client-request-id: e496a041-8045-4093-a2bf-e129e1e9e3e2
Content-Length: 213
Content-Type: application/xml
Date: Tue, 11 May 2021 22:00:03 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Run the first and second queries above in the .NET API
2. First query will result in success, second in failure

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.3
 - Hosting platform or OS and .NET runtime version: Windows Server 2016 .NET Framework 4.6.2
 - IDE and version : Visual Studio 16.9.4

**Comment by seanmcc-msft** [comment]
Hi @deenairn, thanks for reporting this.  I'll sync with some colleagues and get back to you shortly.

-Sean

**Comment by seanmcc-msft** [comment]
Hi @deenairn,

I reached of to the Query Acceleration team, and Query Acceleration is limited to a max query depth expression of 50 in the storage service.  If you would like to receive more columns, the recommended workaround is "Select *".

@tamram, would it be possible to update https://docs.microsoft.com/en-us/azure/storage/blobs/query-acceleration-sql-reference to reflect this limitation?

-Sean

**Comment by deenairn** [comment]
Hi Sean,

Thanks for the confirmation, it at least confirms the behaviour I've observed. In addition to adding the constraint to the documentation, it may be worthwhile exposing the error message to the user via the .NET client API too.

Could you provide any clarity on the rationale for the 50 columns, and whether this might be altered in the future? 

For me it seems a slightly arbitrary constraint. I understand it will take more resources on the server side to parse a very large CSV file, but the approach adopted doesn't fully achieve this. For example, I could have a file with 1,500 columns, but only read the last 49 columns or even just the last column. In this situation, the server has to parse the entire line. It would achieve this outcome if you could only parse the **first** 49 columns (please don't do this - it will make the situation even worse for us...).

We have are developing an application where the 1,500 columns in a dataset is a genuinely possible requirement, as well as the requirement to select up to around 100 columns (TBC) of these. This means that despite very good performance for <= 49 columns, for any above this we will have a noticeable degradation in performance. This may be difficult to explain to clients why selecting one additional column would result in this.

Thanks,
Donald

**Comment by deenairn** [comment]
> Hi @deenairn,
> 
> I reached of to the Query Acceleration team, and Query Acceleration is limited to a max query depth expression of 50 in the storage service. If you would like to receive more columns, the recommended workaround is "Select *".
> 
> @tamram, would it be possible to update https://docs.microsoft.com/en-us/azure/storage/blobs/query-acceleration-sql-reference to reflect this limitation?
> 
> -Sean

Is it definitely the case that it's limited to 50 columns? My testing suggested it was from _1, ..., _49 - which suggests it's 49.

**Comment by normesta** [comment]
@seanmcc-msft - I've updated the ref article as well as the related "how to" article with note that clarifies this limitation. @deenairn - thank you for raising the issue!

**Comment by deenairn** [comment]
@normesta, @seanmcc-msft, @tamram - thanks for updating - I can see the documentation has been updated. However, it has been updated **incorrectly**, the limitation is 49 columns, not 50 (note: the _ syntax starts from column _1, not _0). 

Could this be corrected?

Could it also be clarified if this limitation will be increased the future?

Thanks,
D

**Comment by normesta** [comment]
Thanks for keeping us honest @deenarin. @seanmcc-msft can you please confirm that the limit is 49 rather than 50?

**Comment by seanmcc-msft** [comment]
@normesta, I can confirm the limit is 49.

**Comment by normesta** [comment]
Thanks @seanmcc-msft !  @deenairn I've made the content update.  The change should appear live in the content just after 3:00 PM today. Thanks again!

**Comment by deenairn** [comment]
1500 in which timezone? Just checked this morning (0930 BST) - but the page is still 50 columns.

**Comment by tamram** [comment]
@deenairn - There is a content freeze in place until next week for the //build conference. Expect to see this live by next Weds.

**Comment by normesta** [comment]
Thank you @tamram . I was just about to reply with that info. Yes. I misspoke in my reply. We are indeed in a freeze at the moment, but the change is queued for publish.  Thx!

**Comment by amishra-dev** [comment]
@seanmcc-msft can we please add a test case to test this boundary (both failure [50] and success[49])

**Comment by deenairn** [comment]
Can confirm the online documentation has not been updated.

**Comment by amishra-dev** [comment]
@deenairn can you please send a link. I see the following
![image](https://user-images.githubusercontent.com/12189888/121059420-4ef9e380-c776-11eb-9818-2c34c3546a72.png)

**Comment by deenairn** [comment]
Fixed the typo :)
