### ISSUE TITLE
[FEATURE REQ] Add WaitForCompletion to Operation & Operation<T>

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-for-net#21026]
**Library or service name.**
Azure.Core
 
**Is your feature request related to a problem? Please describe.**
There is interest from the Synapse and Management teams for a built in and supported WaitForCompletion on Operation & Operation<T>

Today clients are writing their own, and with the non-generic Operation two copes are required. It's also pretty easy to introduce sync over async issues by mistake.

cc @pakrym

**Comment by pakrym** [comment]
cc @christothes
