### ISSUE TITLE
[Documentation]: Pull request process

### ISSUE THREAD

**Issue by kirthik** [Azure/azure-sdk-for-net#2103]
- This should include documentation on the requirements for sending PR from partner teams
  - Build should be green
  - Already reviewed by their team member. Please mention the name of the team member who reviewed it
  - Clear and descriptive PR title and commit messages
  - Link to the test document 
- Suggestions for cleaning up commits
  - When SDK team expects a single commit in a PR vs when multiple PRs are acceptable
    - If it’s a bug fix that is being addressed, then PR with single commit should be submitted
    - If a new feature is being introduced, then PR can have multiple logical commits with each commit clearly describing what it does
  - Commands for rebasing, squashing, cherry picking commits
  - Links to detailed git documentation on rebasing, squashing and cherry picking commits
- SDK team's advice on when to fork vs create a branch
  - If there is a big feature that involves multiple partners, then partner teams should create a branch in the repo that everyone can work on. Delete the branch once feature is merged
  - Small issues can be addressed in individual forks
- Checkpoints for PR sign off
  - SDK team 
    - Verify metadata
      - nuspec(master)/project.json(Autorest) should look good
      - Dependencies, project title, descriptions, tags should be valid. Titles and descriptions should clearly describe the intent.
    - Generated code should have right structure
    - Code comments should be clear
    - PRs should include tests
      - Check if the tests environment independent
      - Hard coded/static values must NOT be used anywhere in code
  - For partner team(s)
    - The PR should already be reviewed by someone in partner team. Include the name of partner who reviewed the PR 
- Always send PRs in logical small chunks
- Add release notes in nuget package and have a process for updating it
- Generate.cmd should be part of every project. Add documentation on what generate.cmd's purpose is and how to create a new one.

**Comment by cormacpayne** [comment]
Fixed.
