### ISSUE TITLE
[Documentation]: CI information

### ISSUE THREAD

**Issue by kirthik** [Azure/azure-sdk-for-net#2104]
- For Partner team(s)
  - Teams should know we have automatic CI that guards every PR and release
  - Documentation in this section should mention the following
    - Mention the purpose of each CI job
    - Mention the CI jobs that partners can use for ondemand runs for change verification
    - Mention the CI jobs that can create packages for net sdk and msi for powershell gallery
    - For powershell repo, we have extended test CI job that runs on every PR later in process for release
    - Mention about the names of CI jobs
      - All jobs have similar name strategy that we use across sdk and powershell repos
        - sign job: sdk-for-net-sign
        - PR validation job:sdk-for-net
        - Publish job: sdk-for-net-publish
- For Internal team
  - Link to Partner team CI job and in addition to that explanation about the remaining CI jobs and their purpose
  - How to create new jobs
  - Slave configuration
  - How to backup data on CI machines
  - Names of CI machines and their user names for accessing
- Link to information on getting encrypted credentials

**Comment by cormacpayne** [comment]
This is part of the on-boarding documentation that needs to be worked on.
