### ISSUE TITLE
[BUG] `Request.Content` throws `InvalidOperationException` when we expect it should not

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk-for-net#21048]
In a9a4ef4f9a2fb2bd19d9f452c5689df9ee98ca2e we added a `.Content` property to `Response`.  The intention was that this property would make it easy for people to access the content of the response without having to deal with the underlying stream (which would include perhaps rewinding it since it is often read as part of constructing the response).

This is throwing InvalidOperationException on some platforms (net461, net50) and not others (netcoreapp3.0).  We should figure out a way to fix this.  Something to consider is in the case where the response is a memory stream, but the underlying buffer can not be extracted, we could copy the contents to a new `BinaryData`.  Since the underlying data has already been copied to the MemoryBuffer, we should have to "go async" to do this.

**Comment by ellismg** [comment]
@JoshLove-msft mentioned that he was able to reproduce this with the service bus administration client tests.

**Comment by JoshLove-msft** [comment]
Looks like at least sometimes, [HttpContent](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpContent.cs#L267) will use a MemoryStream [constructors](https://docs.microsoft.com/en-us/dotnet/api/system.io.memorystream.-ctor?view=net-5.0#System_IO_MemoryStream__ctor_System_Byte___System_Int32_System_Int32_System_Boolean_) that does not expose the underlying buffer.

**Comment by pakrym** [comment]
The memory stream exposed in our pipelines should always be created in https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Pipeline/Internal/ResponseBodyPolicy.cs#L80

**Comment by JoshLove-msft** [comment]
The key line appears to be here - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/Pipeline/Internal/ResponseBodyPolicy.cs#L66

If the stream is seekable then we don't copy to a new memory stream. I'm not sure when the stream would not be seekable.

**Comment by pakrym** [comment]
When it's an actual live network stream. But that might be the cause of the issue. If the HttpClient returns a memory stream without buffer available we won't rebuffer it.

**Comment by pakrym** [comment]
I don't know if it ever would as we use the HttpCompletionOption.ResponseHeadersRead

**Comment by JoshLove-msft** [comment]
> If the HttpClient returns a memory stream without buffer available we won't rebuffer it.

Isn't it when the HttpClient returns a seekable memory stream, we won't rebuffer it?

**Comment by JoshLove-msft** [comment]
It turned out the error was occurring in Playback mode for the Service Bus tests due to how the memory stream is constructed here - https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core.TestFramework/src/PlaybackTransport.cs#L115

**Comment by pakrym** [comment]
I thought yuou were able to repro it with HttpClient/

**Comment by JoshLove-msft** [comment]
> I thought yuou were able to repro it with HttpClient/

I think I was able to - I actually remember stepping into the HttpContent code, but I have not been able to repro it again.
