### ISSUE TITLE
[BUG] HTTP 400 with corrupted query string when partition key contains special characters

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#21053]
**Describe the bug**
This is a tricky one I've had a very hard time coming up with a minimal repro for. I have plenty of logs, a reliable repro in my Azure Function, and a minidump. But I haven't been able to repro it locally. When I run the same code locally, I can't reproduce the issue. I think it may have to do with the high degree on concurrency in an Azure Functions process.

I don't feel comfortable uploading the memory dump here since secrets are in the memory but I'd be happy to provide the memory dump directly to anyone investigating this issue on the team. I'm a Microsoft employee, alias `jver`.

Here's an example request:
```
Request [b6568b0a-1316-4478-b3fe-9bc3c33fab8c] PUT https://nugetdevusncinsights.table.core.windows.net/catalogleafscans3e2lwn4vtsmujfhud2s5zuno3q(PartitionKey='08585807480981896314-3e2lwn4vtsmujfhud2s5zuno3q-%C6%BF%C4%81t%C4%81k%C4%81-1800-790-9186-hp-printer-contact-number-hp-pri',RowKey='1.0.0')nter-helpline-number?sv=REDACTED&ss=REDACTED&srt=REDACTED&sp=REDACTED&se=REDACTED&spr=REDACTED&sig=REDACTED&$format=REDACTED
x-ms-version:REDACTED
DataServiceVersion:REDACTED
If-Match:W/"datetime'2021-05-12T22%3A50%3A56.5336982Z'"
Accept:application/json
x-ms-client-request-id:b6568b0a-1316-4478-b3fe-9bc3c33fab8c
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Data.Tables/12.0.0-beta.8,(.NET Core 3.1.13; Microsoft Windows 10.0.14393)
Content-Type:application/json
client assembly: Azure.Data.Tables
```

This is produced by a `TableClient.UpdateEntityAsync<T>(entity, etag, TableUpdateMode.Replace)`. But I have another similar example in the same memory dump that is from a batch operation `new TableTransactionAction(TableTransactionActionType.UpdateReplace, entity, etag)`. 

For emphasis, this is the URL path, no query string
`/catalogleafscans3e2lwn4vtsmujfhud2s5zuno3q(PartitionKey='08585807480981896314-3e2lwn4vtsmujfhud2s5zuno3q-%C6%BF%C4%81t%C4%81k%C4%81-1800-790-9186-hp-printer-contact-number-hp-pri',RowKey='1.0.0')nter-helpline-number`

Notice how there is extra text after the close parenthesis: `nter-helpline-number`. It's like the partition key got broken in two.

The partition key should be `08585807480981896314-3e2lwn4vtsmujfhud2s5zuno3q-ƿātākā-1800-790-9186-hp-printer-contact-number-hp-printer-helpline-number`.

This did not occur on package version `12.0.0-alpha.20210408.1` but did occur on `12.0.0-beta.8`.

**Expected behavior**
The request URL should be more like:
`/catalogleafscans3e2lwn4vtsmujfhud2s5zuno3q(PartitionKey='08585807480981896314-3e2lwn4vtsmujfhud2s5zuno3q-%C6%BF%C4%81t%C4%81k%C4%81-1800-790-9186-hp-printer-contact-number-hp-printer-helpline-number',RowKey='1.0.0')`

**Actual behavior (include Exception or Stack Trace)**
The following error response is returned:
```
Error response [b6568b0a-1316-4478-b3fe-9bc3c33fab8c] 400 Bad Request (00.0s)
Transfer-Encoding:chunked
Server:Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:ab559a46-7002-000d-07ba-472de3000000
x-ms-client-request-id:b6568b0a-1316-4478-b3fe-9bc3c33fab8c
x-ms-version:REDACTED
X-Content-Type-Options:REDACTED
Date:Thu, 13 May 2021 05:42:58 GMT
Content-Type:application/json; odata=minimalmetadata; streaming=true; charset=utf-8
```
```
Error response [b6568b0a-1316-4478-b3fe-9bc3c33fab8c] content: {"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"Bad Request - Error in query syntax.\nRequestId:ab559a46-7002-000d-07ba-472de3000000\nTime:2021-05-13T05:42:58.1393326Z"}​}}
```

**To Reproduce**
Well, the way I have reproduced it is with my project [ExplorePackages](https://github.com/joelverhagen/ExplorePackages). I essentially write all NuGet.org package IDs and versions to Azure Table Storage. I have scripts to "easily" deploy my code and the whole thing is open source. If you'd like a full repo in Azure Functions, I'm happy to provide instructions.

If you need a more minimal repro, I can try for that but I'm concerned that my devbox won't be able to simulate the concurrency that intra-Azure region traffic allows. The minimal repro I tried did not work but perhaps I need to start cutting away code from my app.

I'm hoping any AI logs I have or a memory dump are enough to understand the problem. If you'd like me to instrument the code to capture more information let me know. Right now I have the request, response, and response body Azure SDK logging enabled which is how I produced the info above.

**Environment:**
 - Name and version of the Library package used: Azure.Data.Tables 12.0.0-beta.8
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure Functions, .NET Core 3.1, App Service Plan
 - IDE and version : VS 16.10 preview

**Comment by jsquire** [comment]
Thanks, @joelverhagen, for your continued help in improving the Tables experience.   Routing this over to @christothes for assistance.

**Comment by christothes** [comment]
I have a local repro that doesn't involve the table client code at all (using just the `RequestUriBuilder`). I'll get a fix out soon.
