### ISSUE TITLE
[QUERY] Does this SDK expose az cli features

### ISSUE THREAD

**Issue by SaiNageswarS** [Azure/azure-sdk-for-net#21059]
**Query/Question**
Does this sdk expose az cli features like az vmss list for a resource group etc. If yes, kindly share the documentation.

**Environment:**
 - Name and version of the Library package used: Azure.Core

**Comment by jsquire** [comment]
Hi @SaiNageswarS.   I'm not exactly sure what you're asking.   It seems as if you'd like to know if `Azure.Core` is a library that allows you to work against the Azure ARM plane to manage resources.   If that interpretation is correct, the answer is no.   `Azure.Core` is a library of common building blocks for the Azure SDKs; more information can be found in its [README](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/README.md).

Each of the Azure resource providers have a library associated with them that would allow you to programmatically manage that category of resources.   For example, you mention listing out VM scale sets, for that you'd want to use [`Azure.ResourceManager.Compute`](https://www.nuget.org/packages/Azure.ResourceManager.Compute) for the current generation (in preview) or [`Microsoft.Azure.Management.Compute`](https://www.nuget.org/packages/Microsoft.Azure.Management.Compute/) if you're in need of a GA release.

More information can be found in the articles [Announcing the new Azure SDK Resource Management Libraries GA](https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/) and the [Documentation]https://docs.microsoft.com/en-us/azure/?product=featured) for the service that you're interested in.

**Comment by SaiNageswarS** [comment]
Thanks a lot ☺️

**Comment by SaiNageswarS** [comment]
@jsquire Thanks for the pointers. I went through the documentation in detail. Could find documentation to create various Azure resources, however, I couldn't get any api to do below:
```
az vmss list --resource-group xyz
```
Also tried exploring REST API of az cli. The documentation to get auth token seems very difficult to follow. 
https://docs.microsoft.com/en-us/rest/api/azure/

Would be grateful to you if you could give little more details. Thanks.

**Comment by jsquire** [comment]
Hi @SaiNageswarS.   I'm going to route this over to the folks that own the management SDKs, who may have more insight to offer.

**Comment by YalinLi0312** [comment]
Hi @SaiNageswarS , I checked tracke1(Microsoft.Azure.Management.Compute) and track2(Azure.ResourceManager.Compute), they both have vmss list operations. For example, in track2, we provide some Sync/Async operations for list in VirtualMachineScaleSetsOperations([here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/compute/Azure.ResourceManager.Compute/src/Generated/VirtualMachineScaleSetsOperations.cs#L202)) and VirtualMachineScaleSetsRestOperations([here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/compute/Azure.ResourceManager.Compute/src/Generated/VirtualMachineScaleSetsRestOperations.cs#L660), [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/compute/Azure.ResourceManager.Compute/src/Generated/VirtualMachineScaleSetsRestOperations.cs#L1897)).
