### ISSUE TITLE
Build errors in AutoRest generated KeyVault REST client

### ISSUE THREAD

**Issue by aniruddhagore1984** [Azure/azure-sdk-for-net#21074]
**Query/Question**
I want to use new Azure KeyVault SDK, I followed the instructions and generated the REST client using autorest. But I am running into the following errors:

1) 'ClientDiagnostics' is inaccessible due to its protection level	
2) The type or namespace name 'RawRequestUriBuilder' could not be found (are you missing a using directive or an assembly reference?)

This is without me making any changes, these are in the files generated by the tool. I am sure I am missing something obvious, could someone please point me in the right direction? 

I have been referring to the ShareLink sample so far. I see the same errors if I download the Generated folder from the sample and add it to my project.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 
 .NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\
 - IDE and version : Visual Studio

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
Hi @aniruddhagore1984.  I may be misunderstanding what you're looking to do, but if you're interested in using the Azure KeyVault SDK, there's no need to generate the code.  The package releases are available on [NuGet](https://www.nuget.org), with the client library packages having names that follow the pattern `Azrue.Security.KeyVault.*` and the management package having the name [`Microsoft.Azure.Management.KeyVault`](https://www.nuget.org/packages/Microsoft.Azure.Management.KeyVault/).

If you're interested in contributing to the library, the source for the client and management packages are available [here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault) to be forked;  in most cases you won't need to regenerate the code.

**Comment by aniruddhagore1984** [comment]
Hey Jesse, thanks for the response. Your understanding is right, I am trying to consume the SDK (not contribute yet :)). I had been referring to the [ShareLink](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/keyvault/samples/sharelink) sample and it uses the generated REST client. Is there a reason that sample might be using the generated REST client? Also, I am looking to create a KeyVault managed storage account. If there is one, could you please point me to the right sample? :)

**Comment by jsquire** [comment]
Hi @aniruddhagore1984.   I'm going to step aside and ask that our resident KeyVault expert, @heaths offer his thoughts so that I don't unintentionally lead you in the wrong direction.

**Comment by jsquire** [comment]
@heaths:  I don't want to reassign and draw attention away form what may be an issue with codegen, but if you would be so kind as to scan the comments and offer your thoughts on the KeyVault portions, it would be very much appreciated.

**Comment by aniruddhagore1984** [comment]
If I can copy the REST client from SDK samples if that is advised, I got it to build just fine. If I go that route though, I run into other issues that I am trying to get help in this post: https://github.com/Azure/azure-sdk-for-net/issues/21126

**Comment by heaths** [comment]
The ShareLink sample is only for managing Key Vault storage APIs which were deprecated in the newer SDKs since the Key Vault service team recommends customer-managed keys through Storage itself, which uses Key Vault directly.

If you only want to manage secrets, keys, or certificates you can use the packages @jsquire mentioned.

I can look into why the sample no longer builds correctly, but seems it may be orthogonal. Was there a particular reason - like an article or something - that lead you to this sample?

**Comment by aniruddhagore1984** [comment]
Thanks for responding here Heath, I agree investigating these build failures would be orthogonal if those SDKs have been deprecated.

My goal is to create Key Vault managed Storage accounts programmatically. 

I started out using [Microsoft.Azure.KeyVault](https://www.nuget.org/packages/Azure.Security.KeyVault.Keys/4.2.0-beta.6) which I later realized is deprecated. So I posted asking for the right way to do this: https://github.com/Azure/azure-sdk-for-net/issues/20941, where ShareLink was recommended. I have since also found [Azure.Security.KeyVault.Keys](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.keys.keyclient?view=azure-dotnet) but have been running into authentication issues using it which I posted in https://github.com/Azure/azure-sdk-for-net/issues/21126.

Can you please confirm Azure.Security.KeyVault.Keys is the recommended SDK to use going forward?

**Comment by heaths** [comment]
Azure.Security.KeyVault.Keys is the correct package to use for key management, but we deprecated Storage account management in Key Vault in favor of using RBAC (I misremembered above why we did, thinking CMK was the preferred solution but is orthogonal), which is also highlighted in the ShareLink example:

> We recommend you use role-based access control (RBAC) to secure access to your storage accounts. You can centrally manage access for users and applications to resources in a way that is consistent across Azure, and works with Azure Active Directory.

Does RBAC not work for your requirements? It's often far less work to manage.

**Comment by heaths** [comment]
Also, can you clarify this:

> I want to use new Azure KeyVault SDK, I followed the instructions and generated the REST client using autorest. But I am running into the following errors:

The [instructions](https://docs.microsoft.com/samples/azure/azure-sdk-for-net/share-link/#:~:text=building%20the%20sample) only specify, `dotnet build`. I was able to build that in a completely clean directory from the ZIP I downloaded.

**Comment by aniruddhagore1984** [comment]
Got it, I think I can just copy paste the generated REST client. My bad here, if I do that then it builds just fine so closing this.
