### ISSUE TITLE
Please provide GeoJson functionality in Azure.Core

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#21085]
**Library or service name.**
Azure.Core
 
**Is your feature request related to a problem? Please describe.**
We are working to release a new GA version of `Azure.Search.Documents` that maps closely with the service features that are in GA.
`GeoJson` support will be included in the GA library, and we need to switch the dependency from `Azure.Core.Experimental` to `Azure.Core`.

**Comment by Mohit-Chakraborty** [comment]
This is required for #21084

**Comment by Mohit-Chakraborty** [comment]
cc: @pakrym

**Comment by pakrym** [comment]
Required for Jun release.
