### ISSUE TITLE
recognizeOnceAsync Calls For Microphone Permissions Every Time

### ISSUE THREAD

**Issue by adammpolak** [Azure/azure-sdk-for-net#21098]
Currently recognizeOnceAsync calls for microphone permissions every time when called.

The UX for our product would make it better to ask permissions BEFORE recording is actually triggered due to the flow of the product.

Need to be able to ask for microphone permissions, THEN later trigger recognizeOnceAsync (which should then take the already given permissions).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d6f17ab1-726a-2d97-65b5-7b69bc0640d7
* Version Independent ID: bbc1ea8c-fcdd-c452-281c-24511e765005
* Content: [SpeechRecognizer.RecognizeOnceAsync Method (Microsoft.CognitiveServices.Speech) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognizer.recognizeonceasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.CognitiveServices.Speech/SpeechRecognizer.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.CognitiveServices.Speech/SpeechRecognizer.xml)
* Service: **cognitive-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
