### ISSUE TITLE
[FEATURE REQ] Allow IndexDocumentsBatch to have Actions with different document types

### ISSUE THREAD

**Issue by njourdain** [Azure/azure-sdk-for-net#21090]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 

Azure.Search.Documents
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

I would like IndexDocumentsBatch to be able to contain IndexDocumentsAction of different document types. For example,

```
batch.Actions.Add(IndexDocumentsAction<ClassA>(type, doc));
batch.Actions.Add(IndexDocumentsAction<ClassB>(type, doc));
```

I tried casting the documents to object, but this causes the `JsonObjectSerializer` to ignore some `JsonSerializerOptions` such as `PropertyNamingPolicy` when calling `SerializeAsync` on the batch.

For now, the only workaround I found is to create a class that inherits `JsonObjectSerializer`, override `SerializeAsync` and replace the `inputType` with `value.GetType()`.

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  We will take a look.

**Comment by Mohit-Chakraborty** [comment]
@njourdain, can you explain a bit more about your scenario. The type of the document needs to match with the index schema. Is there a relationship between the different types of documents being uploaded?
Also, take a look at [`SearchDocument`](https://docs.microsoft.com/dotnet/api/azure.search.documents.models.searchdocument?view=azure-dotnet). It allows for untyped free-form document representation.

**Comment by njourdain** [comment]
Sure. Let's say I have a people index, that can be represented with the following class :

```
public class IndexablePerson
{
    public string Id { get; set; }
    public string PhoneNumber { get; set; }
    public string Email { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```

So the schema would simply be four fields of type edm.string. In my real case, the schema is much more complex, with around 50 fields.

We have a CQRS architecture where the front-end application will send a command to update a specific section of the person. So we would have the PersonContactInfo page to update phone number and email, and the PersonalInfo page to update first name and last name.

In the backend, we have an azure function that receives batches of commands. Each command is converted to an indexable object if applicable (example will follow), and those indexable objects are then sent to the index as a single batch. Here, we leverage the **MergeOrUpload** functionality to do partial updates.

```
public class IndexablePersonContactInfo
{
    public string Id { get; set; }
    public string PhoneNumber { get; set; }
    public string Email { get; set; }
}

public class IndexablePersonPersonalInfo
{
    public string Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```

So the code that sends the data to the index looks like this :

```
var indexableObjects = commands.Select(command => GetIndexableObject(command)).ToArray();
await _searchClient.MergeOrUploadDocumentsAsync(
    indexableObjects,
    new IndexDocumentsOptions {ThrowOnAnyError = true}
);
```

So, in this example, indexableObjects is an object[]. Therefore, the client will create an IndexDocumentsBatch<object>, and will internally call the SerializeAsync method in the IndexDocumentsBatch class. Down the line, typeof(object) will be passed on to the json converter when converting each document, instead of the real type. This has caused us issues with the casing on the property names.

Even though we configure the client like this :

```
var jsonOptions = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };
jsonOptions.Converters.Add(new JsonStringEnumConverter(JsonNamingPolicy.CamelCase));
var searchClientOptions = new SearchClientOptions { Serializer = new JsonObjectSerializer(jsonOptions) };
var searchClient = new SearchClient(
    new Uri("endpoint here"),
    "index name here",
    "key here",
    searchClientOptions
);
```

When testing with a list of only IndexablePersonContactInfo (and therefore having indexableObjects as IndexablePersonContactInfo[]), property names were correctly serialized as camelCase. This led us to use the following workaround :

```
public class CustomJsonObjectSerializer : JsonObjectSerializer
{
    public CustomJsonObjectSerializer(JsonSerializerOptions options) : base(options)
    {
    }

    public override ValueTask SerializeAsync(Stream stream, object value, Type inputType, CancellationToken cancellationToken)
    {
        return base.SerializeAsync(stream, value, value.GetType(), cancellationToken);
    }
}
```

And creating the search client options becomes `var searchClientOptions = new SearchClientOptions { Serializer = new CustomJsonObjectSerializer(jsonOptions) };`

So we override the SerializeAsync method called by the sdk, replacing inputType (which in our case is typeof(object) with value.GetType() to have the real type. This isn't ideal because there is an overhead when calling GetType, and this code risks breaking if the sdk changes.

So this explains the feature request to be able to create a batch with different document types.

As for your suggestion of using SearchDocument, it's an interesting idea that I would have to test. We are using automapper, so I could try mapping command => IndexablePersonContactInfo => SearchDocument, and maybe adding `DictionaryKeyPolicy = JsonNamingPolicy.CamelCase` in the options. Performance-wise, I'm not sure which would be better between creating an extra object or calling GetType, but at least it would be more robust.

**Comment by Mohit-Chakraborty** [comment]
@njourdain, did you get a chance to look into `SearchDocuments` for your scenario?
I am wondering how that's working out.
