### ISSUE TITLE
Delay of 1min in processing messages from subscription when using sessions 

### ISSUE THREAD

**Issue by jsum04** [Azure/azure-sdk-for-net#21106]
**Query/Question**
I have been able to push 1000 messages within in few seconds using my publisher. But I can that there is a delay of ~1min while consuming the messages. I have the below settings for my session processor.
PrefetchCount = 10,
AutoCompleteMessages = false,
MaxAutoLockRenewalDuration = TimeSpan.FromMinutes(5),
MaxConcurrentCallsPerSession = 1,
MaxConcurrentSessions = 10

Most of the time, each of those 1000 messages have unique sessionId's. The consumer is processing 10 messages at any given point of time but once the message is completed, the next message is picked up almost after 1 min. I would the consumer to pick up the next message immediately even if it is a new session.

Could you please tell me If I have missed setting a parameter.

**Environment:**
 - Azure.Messaging.ServiceBus 7.1.1
 - Azure AppService S1
 - Azure service bus Standard Tier
 - AMQP 1.0 protocol
 
I have tried doing the same with the sample code (https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample05_SessionProcessor.md) and found the same issue when I set the MaxConcurrentSessions to 1.

![image](https://user-images.githubusercontent.com/84323132/118484825-ff1d9300-b75a-11eb-9314-0010fa554a70.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @jsum04, as of 7.2.0-beta.1, this can be configured via [SessionIdleTimeout](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussessionprocessoroptions.sessionidletimeout?view=azure-dotnet-preview). We expect to release a GA of this version next month.

**Comment by jsum04** [comment]
Hello Josh, Is there a workaround for version 7.1.1

**Comment by JoshLove-msft** [comment]
Yes, you can configure the [TryTimeout](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusretryoptions.trytimeout?view=azure-dotnet) within the ServiceBusClientOptions but this would impact all operations, not just the receive operations that the processor is performing.

**Comment by jsum04** [comment]
Thanks Josh

**Comment by jsum04** [comment]
Josh, how safe is it to use the beta version and also do you have any tentative date for the GA version. Thanks

**Comment by JoshLove-msft** [comment]
The main risk of using the beta version is that there could be breaking changes from the current beta to the actual GA version. We plan to GA in mid June.

**Comment by jsum04** [comment]
Hello Josh, I tried the TryTimeout option and it didnt work. It is throwing a ServiceCommunicatioException. I have given the following config. Please let me know If I need to do it differently.

![image](https://user-images.githubusercontent.com/84323132/118584816-0be1cb80-b7db-11eb-98b5-42106a24729c.png)

**Comment by JoshLove-msft** [comment]
That is too small of a timeout - it is essentially saying that every operation needs to complete in 5 milliseconds. I would suggest trying something like 5 or 10 seconds if that is an acceptable wait time.

**Comment by jsum04** [comment]
Hi Josh, Setting it to 5 worked. Just to confirm, the application can take longer to process the message as that is controlled by the message lockout time. Am I correct in saying that.

**Comment by JoshLove-msft** [comment]
Yes, that is correct - this specifies how long operations with the service are allowed to take before the client times out.

**Comment by jsum04** [comment]
Thanks for all you help Josh

**Comment by JoshLove-msft** [comment]
Going to close this out now. Feel free to reopen if you have further questions.
