### ISSUE TITLE
[FEATURE REQ] Azure.Data.Tables TokenCredential

### ISSUE THREAD

**Issue by flipch** [Azure/azure-sdk-for-net#21100]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 
Azure.Data.Tables
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
Many of the libraries in here allow you to initialize the credential clients with an implementation of the class
`TokenCredentials` that allow you to authenticate with, for example, oauth which table storage supports.

https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory

For example, i'm using a `ITokenAcquisition` from Identity.Web that allows me to use a token from Azure AD to instantiate an Service Client for Queue, just like:

`queueServiceClient = new QueueServiceClient(serviceUri, new TokenAcquisitionTokenCredential(tokenAcquisition));`

This would allow me, in this case, make use of the logged in Oauth user and the user_impersonation scope for Azure Storage and make calls in behalf of the user, for an automatic lockdown of resources.

Let me know if you need me to go deeper.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
`TokenCredential` authorization is currently not supported by the service. If they do add it, we will implement it in the client SDK.

**Comment by flipch** [comment]
I see now that this [section](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app?tabs=dotnet#azure-storage-resource-id) does not mention the `.table` domain. 

Appreciate the fast response time @christothes.
