### ISSUE TITLE
[BUG] Azure.Extensions.AspNetCore.Configuration.Secrets: Secrets are not being read

### ISSUE THREAD

**Issue by martynas-m** [Azure/azure-sdk-for-net#21117]
**Describe the bug**
after updating to 1.1.0 (from 1.0.2) secrets are not being read. no error, no messages, just values not populated in config. after downgrading the same app works as expected.

note: config value is nested, like, `Client:Api:Connection:Key`, in key vault it translates to `Client--Api--Conection--Key`, maybe some breaking change was introduced there?

**Expected behavior**
secrets read to config

**Actual behavior (include Exception or Stack Trace)**
secrets not read to config

**To Reproduce**
create project with 

```csharp
builder.AddAzureKeyVault(new Uri(url), new DefaultAzureCredential());
```

secrets not appear in config.

**Environment:**
 - Azure.Extensions.AspNetCore.Configuration.Secrets 1.1.0
 - Hosting platform or OS and .NET runtime version
```
 .NET SDK (reflecting any global.json):
 Version:   5.0.202
 Commit:    db7cc87d51

Runtime Environment:
 OS Name:     arch
 OS Version:  
 OS Platform: Linux
 RID:         arch-x64
 Base Path:   /home/<...>/.dotnet/sdk/5.0.202/

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  2.2.402 [/home/x/.dotnet/sdk]
  3.1.402 [/home/x/.dotnet/sdk]
  3.1.404 [/home/x/.dotnet/sdk]
  5.0.100 [/home/x/.dotnet/sdk]
  5.0.202 [/home/x/.dotnet/sdk]
  5.0.203 [/home/x/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [/home/x/.dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [/home/x/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.8 [/home/x/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [/home/x/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/home/x/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [/home/x/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/home/x/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.7 [/home/x/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.8 [/home/x/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [/home/x/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/home/x/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [/home/x/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/home/x/.dotnet/shared/Microsoft.NETCore.App]

```

**Comment by jsquire** [comment]
//cc: @heaths

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by martynas-m** [comment]
Hi,

I think I've found the problem- have you changed something related
uppercase / lowercase in configuration keys and azure key vault keys? I had
config where keys were starting with capital letter (like Key:SubKey:Name)
and in azure key vault had key--SubKey--Name). it was working before nuget
update, and stopped afterwards. so in my case azure secret with key
'key--SubKey--Name' could be retrieved via
Configuration["Key:SubKey:Name"], and after update- not. (notice Uppercase
in Key - it took me lot of time to notice that)

**Comment by pakrym** [comment]
Hey, thank you for the report. From the sound of it looks like you are right. I'll try to reproduce and fix ASAP.

**Comment by pakrym** [comment]
The fix is out in https://www.nuget.org/packages/Azure.Extensions.AspNetCore.Configuration.Secrets/1.2.1
