### ISSUE TITLE
Faulty `ExpiresAt` and `TimeToLive` values when peeking a message that was not yet moved from queue

### ISSUE THREAD

**Issue by ben-002** [Azure/azure-sdk-for-net#21127]
I have a queue with a TTL of one day (the behavior is identical on topics subscriptions). When a message is sent to the queue, its TTL will automatically be set to one day. I know this because, after that one day, the message expires. However, if the message is not processed, in other words, if it will keep the state it had since it arrived in the queue a strange behavior can be observed. When I perform a peek of this massage I see wrong data inside `ExpiresAt` property(12/31/9999 11:59:59 PM +00:00). Once the message moved, let's say to deadletter and back to the queue, `ExpiresAt` will have the correct value. Same thing applies to `TimeToLive` property.

**Expected behavior**
When peeking a message that has not been yet moved anywhere, the right values should be fetched for `ExpiresAt` and `TimeToLive`

**Actual behavior (include Exception or Stack Trace)**
`ExpiresAt` and `TimeToLive` are populated with the maximum value, `12/31/9999 11:59:59 PM +00:00`, even though the TTL will still produce its effects as expected.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. In a service bus namespace, create a test queue with a TTL different than the default (e.g 1 day)
2. Send a message to that specific queue.
3. Using the Azure.Messaging.ServiceBus NuGet package, peek the message in debugging mode.
4. Find the `ExpiresAt` property of the message and check its value
5. Same as point 4 but for `TimeToLive` property
6. Both values would be `12/31/9999 11:59:59 PM +00:00` instead of the real ones.

```c#
using System.Threading.Tasks;

using Azure.Messaging.ServiceBus;

namespace ConsoleApp4
{
    class Program
    {
        static string connectionString = "connection string placeholder";
        static string queueName = "queue name placeholder";

        static async Task Main()
        {
            await PeekMessageAsync();
        }

        static async Task PeekMessageAsync()
        {
            await using (ServiceBusClient client = new ServiceBusClient(connectionString))
            {
                ServiceBusReceiver receiver = client.CreateReceiver(queueName);

                var messages = await receiver.PeekMessagesAsync(10);
            } // place Breakpoint here and look into messages
        }
    }
}

```

![image](https://user-images.githubusercontent.com/69915112/118565966-c215c880-b77b-11eb-92f1-f2734d6a7b3a.png)

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.ServiceBus 7.1.2
 - IDE and version:  Visual Studio 16.9.5

**Comment by ben-002** [comment]
Same behavior for the old NuGet, WindowsAzure.ServiceBus, v6.1.1. Not sure where should I ask or open an issue for this package as well.

```C#
using Microsoft.ServiceBus.Messaging;

namespace ConsoleApp3
{
    class Program
    {
        static void Main(string[] args)
        {
            string connectionString = "connection string placeholder";

            MessagingFactory factory = MessagingFactory.CreateFromConnectionString(connectionString);

            MessageReceiver testQueueReceiver = factory.CreateMessageReceiver("queue name placeholder");

            var messages = testQueueReceiver.PeekBatch(10);
        }// place Breakpoint here and look into messages
    }
}

```

**Comment by jsquire** [comment]
@JoshLove-msft:  This looks like it is hitting the fallback logic [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusReceivedMessage.cs#L375).   We can't see the TTL here, but if it is returning 24 hours, that condition should be `false`.    

Do you mind taking a look?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
I believe this behavior is not specific to any particular SDK but is at the service level. Also, this doesn't seem specific to Peek but occurs also with Receive. Note that if you set an explicit TimeToLive on the message, the ExpiresAt property is set as expected.

I will have to follow up with the service team to find out more about why this is happening.

**Comment by JoshLove-msft** [comment]
The service team confirmed that this is the expected behavior. The TTL on the message does not take into account the entity-level TTL.

**Comment by ben-002** [comment]
@JoshLove-msft Thanks for your response. From what I understand this is an expected behavior. I wonder why, though. Is there any documentation where this behavior is detailed?

[Here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-expiration) I found out that "The default expiration is used for all messages sent to the entity where time-to-live isn't explicitly set"

**Comment by JoshLove-msft** [comment]
Hi @ben-002, 
I don't think there is any documentation that explicitly describes this behavior. I think we can update the docs to include this information. I'm unsure as to the "why" the messages are not updated automatically with the entity expiration time, but I can try to find out.

**Comment by JoshLove-msft** [comment]
The reasoning mentioned by the service team is that since the expiry time can be changed on an entity, it wouldn't be clear what should happen with the entity time that may have already been stamped on the message. In order to avoid this potential ambiguity, they decided to leave the expiry time blank and respect the current entity-level expiration.

**Comment by ben-002** [comment]
@JoshLove-msft Thank you for finding the explanation! I will close the issue now.
