### ISSUE TITLE
Look into implications of service removing TaskState in Analyze response

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#21120]
Will be deleted for all tasks as it is already included per task. How does it affect the SDK?

**Comment by deyaaeldeen** [comment]
Wait, I must have missed this part. Why?

**Comment by maririos** [comment]
The service is looking into removing `properties` from `tasks` as the information is repeated in each task. I haven't looked into what it means in the SDK but from a quick look, it seems appropiate

```
"TasksState": {
    "properties": {
    "tasks": {
        "completed": {
            "type": "integer"
        },
        "failed": {
            "type": "integer"
        },
        "inProgress": {
            "type": "integer"
        },
        "total": {
            "type": "integer"
        },
        "entityRecognitionTasks": {
            "type": "array",
            "items": {
            "type": "object",
            "allOf": [
                {
                "$ref": "#/definitions/TaskState" // Needed
                },
                {
                "$ref": "#/definitions/EntitiesTaskResult"
                }
            ]
            }
        },
```

**Comment by maririos** [comment]
I looked in .NET and this won't be an issue for us as we actually ignore these properties and either look at the JobState or the specific task state. i.e. https://github.com/maririos/azure-sdk-for-net/tree/notaskdetails
Once the change is done in the swagger, we can consume it.
