### ISSUE TITLE
[QUERY]Suggestion on make "BlockCountExceedsLimit" for specific

### ISSUE THREAD

**Issue by celinama** [Azure/azure-sdk-for-net#21137]
**Query/Question**
How can we help?
In Document 
https://docs.microsoft.com/en-us/rest/api/storageservices/blob-service-error-codes 
we have Error Code "BlockCountExceedsLimit" listed twice for different User message. One with "The committed block count cannot exceed the maximum limit of 50,000 blocks." and the other comes with "The uncommitted block count cannot exceed the maximum limit of 100,000 blocks".
In this request I'm talking about Error Code with User Message "The uncommitted block count cannot exceed the maximum limit of 100,000 blocks". The ask is can we make the Error Code more specific? for example in our case the Error Code customer got is "RequestEntityTooLargeBlockCountExceedsLimit". Is that possible we use more detailed Error Code to differentiates "committed block count exceed 50,000 blocks" and "uncommitted block count exceed 100,000 blocks".
Thank you!

**Comment by amnguye** [comment]
This is not an ask specific to the SDK, this an ask specific towards the service. I would suggest that this would be posted somewhere that would be brought to the service's attention.

https://azure.microsoft.com/en-us/support/community/
