### ISSUE TITLE
Make AnalyzeActionsOptions.IncludeStatistics bool?

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#21130]
Instead of `bool` as the user can decide not to set it and we shouldn't set it.
This hasn't GA so we can make the change here

**Comment by maririos** [comment]
Need to verify with architects first

**Comment by maririos** [comment]
From Krzysztof: Is this property (property of the JSON payload) optional or not? If it's optional, we should use nullable. If it's required, it's a bit more difficult. We struggled in the past with having a clear guidance here, and I am wondering if we should not make the guidance more crisp at least for pure inputs: always use nullable, in case the property changes to optional. For inputs, the cost of using nullable is very small (all primitives types just cast to nullable). For outputs, we can stay with current guidance as it's a breaking change to go from required to optional outputs, and such breaking changes should never happen.

**Comment by maririos** [comment]
So we can make it bool?

**Comment by kinelski** [comment]
> 
> 
> So we can make it bool?

I got very confused by this comment. I thought it was a question. "Is she talking to herself?".

**Comment by maririos** [comment]
@kinelski I admit that sometimes in issues I end up talking to my future self. So when I go back I understand what the thought process or just the process I took was :P
I will make it more clear next time so it is clear for people outside my brain
