### ISSUE TITLE
Investigate cancellation support options for GA

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#21153]
Currently, we have implemented the ability to cancel receive operations, but this has the side effect of clogging up the receive link until the operation times out. Ultimately, we want this to be supported via the AMQP library. For the June GA, we may want to scope down the cancellation support to apply only when stopping the processor.

**Comment by JoshLove-msft** [comment]
FYI @danielmarbach

**Comment by danielmarbach** [comment]
Thanks for the heads up! Currently I'm super busy with other things and can't contribute much otherwise I would have loved to help out. I guess the good thing though is that we now have the technique in place that we can move into the correct place
