### ISSUE TITLE
[FEATURE REQ] ManagementClient missing from Azure.Messaging.ServiceBus

### ISSUE THREAD

**Issue by jasond-s** [Azure/azure-sdk-for-net#21186]
**Azure.Messaging.ServiceBus**

The latest azure SDK for service bus seems to have dispensed with the `ManagementClient` that was present in `Microsoft.Azure.ServiceBus`.

I know that there was a bit of back and forth about the mis-use of things like `CreateIfNotExists` functionality and how this could be quite detrimental to performance. What about for users that are being sensible with it? I know really we should be using ARM to deploy topics and subs programmatically at deployment, but there are a bunch of use cases for creating subs on the fly at runtime (integration testing is one of them). 

Is there an alternative library I am missing? I don't really want to have to interact with the base ARM APIs because they are a nightmare and require things like a tenant ID to float around in config. I really want to just use the Service Bus connection string for management activities. Do I have to import both old and new NuGet packages?

**Comment by jsquire** [comment]
Hi @jasond-s.   Thank you for reaching out and we regret that you're experiencing difficulties.   The functionality for managing resources under a Service Bus namespace is available in the `Azure.Messaging.ServiceBus` package using the [`ServiceBusAdministrationClient`](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient), which has feature parity with the `ManagementClient` in the legacy SDK.
