### ISSUE TITLE
[QUERY] Microsoft.Azure.ServiceBus: Scheduled Messages Appear Immediately

### ISSUE THREAD

**Issue by onlywithlad** [Azure/azure-sdk-for-net#21185]
**Query/Question**
I am converting my dot net framework code to dot net core azure function which publishes message on service bus. In this I am having functionality of publishing scheduled messages.
Earlier I was using WindowsAzure.ServiceBus and its working. But now in core, I am using Microsoft.Azure.ServiceBus with transport type as AMQPWebSockets. But here schedule messages are directly moving to queue though future time is set to ScheduledEnqueueTimeUTC property. Same service bus set up is working on old code.

To send a message we are creating message senders with transport type as AMQPWebSockets.

Kindly help on the same.

versions used 
Dot net core 3.1
Microsoft.Azure.ServiceBus 5.1.3

Rules set on service bus are proper as it is working with old code.

**Comment by jsquire** [comment]
//cc: @shankarsama

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by onlywithlad** [comment]
HI Team,

Any update on this.

**Comment by KranthiPakala-MSFT** [comment]
@onlywithlad We still have not heard back from you. Just wanted to check if you still need assistance on this? Please let us know if this issue can be closed.

Thank you
