### ISSUE TITLE
[QUERY] Fastest API to poll on azure async operations

### ISSUE THREAD

**Issue by ishaniGupta27** [Azure/azure-sdk-for-net#21196]
**Query/Question**
How can we help?

We need to poll Azure-AsyncOperation for checking for status of a previously triggered operation. Tried using ComputeManagementClient API for the polling:

**_GetLongRunningOperationResultAsync(azureresponse, Arm.GetCustomArmHeaders(), CancellationToken.None).Result;_**

Above API has latency of 20 sec +, which is not acceptable for our application. When tried via another rest client ( Postman), the latency is < 1 second. Is there an alternative light weight API which can be used for polling Azure-AsyncOperation?

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.Compute 46.0.0.0
 - Hosting platform or OS and .NET runtime version : Windows , v4.7.2 .Net Framework
 - IDE and version :Microsoft Visual Studio Enterprise 2019 Version 16.9.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by allenjzhang** [comment]
Thank you for your question. The current Compute service does send a pretty generous Retry-After header on LRO operations even when many operations succeed just slightly longer than 1 second. The SDK is designed to respect that value. This would prevent users from busy polling and causing unnecessary load on the system and to avoid throttling. 

Having said that, if your scenario does call for busy polling, I think you can do so by adding a custom Delegating handler via Client construction. In the custom Delegating handler, you can override the Retry-After value based on your conditions, such as for 200 range status code AND/OR specific resources (you can check via RequestUri). This would alter the behavior of the LRO logic in SDK to respect the values in Retry-After to achieve your goal of more frequent polling and faster completion.

Let me know if the approach is clear and works for you. We are looking to add more convenient way for you to control that.
