### ISSUE TITLE
[FEATURE REQ] Expose AllowBlobPublicAccess property in StorageAccountCreateParameters

### ISSUE THREAD

**Issue by liabadi** [Azure/azure-sdk-for-net#21195]
**Library or service name.**
Azure.ResourceManager.Storage

 
**Is your feature request related to a problem? Please describe.**
The SDK doesn't expose `StorageAccountCreateParameters.AllowBlobPublicAccess`. As a result, all storage accounts generated by the SDK lack this safety feature (which is a Microsoft [recommendation](https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal#allow-or-disallow-public-read-access-for-a-storage-account )).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by blueww** [comment]
@allenjzhang 

"Microsoft.Azure.Management.Storage" SDK already support this parameter in create account.
"Azure.ResourceManager.Storage" is not owned by our team. Would you please help to look why it doesn't support this parameter in create account

**Comment by ArthurMa1978** [comment]
@liabadi the new lib exposed AllowBlobPublicAccess now
https://www.nuget.org/packages/Azure.ResourceManager.Storage/1.0.0-beta.4
