### ISSUE TITLE
Devise better way to build and publish samples from service directories

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#21204]
The original work that went into sdk/keyvault/samples and the effort required to resolve #21170 required a lot of understanding and discovery of all our MSBuild properties and targets as well as MSBuild projects in general. This is not ideal for onboarding new teams who want to publish non-package-specific samples or, as in the case of these Key Vault samples, some which use multiple Key Vault packages and don't really fit in a single one.

Ideally, I think we could probably change a few of the item groups in eng/services to also treat `sdk/$(ServiceDirectoy)/samples` as samples and subject them to all the same rules as normal `IsClientLibrary=true` packages, but treat them as non-shipping automatically.

General props and targets also need to consider that samples may be `OutputType=Exe` and cannot use "netstandard2.0", which some targets seem to assume and required significant workarounds, understanding how `TargetFramework` and `TargetFrameworks` relate to each other.

/cc @pakrym @chidozieononiwu @weshaggard

**Comment by weshaggard** [comment]
I do think we can probably create a samples props/targets file that we can use for samples but we want them to mostly act like standard project defaults and not be treated like IsClientLibrary because that ends up being too coupled to our engineering system.

**Comment by heaths** [comment]
But I think being coupled into our engineering system when built within our repo is exactly what we want. We want all the same analyzers, build, and possibly even test processes to run (I do have tests for one of my samples), but hide all that when built isolated from our repo, like when downloaded from Samples Browser. With Directory.Build.{props, targets} in sdk/keyvault/samples I've tried to do that as much as possible, but there are still some artifacts.

There are also some interesting cases like sdk/keyvault/samples/sharelink where I have to copy linked friles to a directory or include them for the sample. Since @pakrym moved almost all autorest and core-shared code to a nupkg that list because SO much smaller, at least. What I devised in that case I think is worth generalizing as well.

**Comment by weshaggard** [comment]
From my prospective the samples should mostly be built like they are outside of our engineering system, as if they were pulled out of our repo and built independently. 
Do we have reasons to build the samples within our engineering system processes? If so then we should make sure our CI builds the samples in both contexts.

**Comment by pallavit** [comment]
@heaths do you still value in exploring this? What would be the benefit of doing this? Any particular use case you have in mind here?

**Comment by heaths** [comment]
Pretty much the same [resolution](https://github.com/Azure/azure-sdk-for-net/issues/24070#issuecomment-1875966622) I gave for closing #24070: Key Vault established a pattern others have copied and can continue to copy, and given other priorities, this probably doesn't rise much beyond ground floor.
