### ISSUE TITLE
[BUG][ DOTNET SDK 3.0.11 ]Satellite assemblies from PackageReference copying to root folder

### ISSUE THREAD

**Issue by divyapurwar** [Azure/azure-sdk-for-net#21215]
**Describe the bug**
I have been using .net sdk 3.0.11 in my project. During Azure build it is not copying the dll's into the bin folder of artifact instead it is copying it to root folder.

**Expected behavior**
It should copy all the dll's into bin folder.

**Actual behavior (include Exception or Stack Trace)**
As you can see from the below logs, It is first copying the files into root folder, then creating zip artifact after that it is copying .dll into bin folder.
    
GenerateProjectArtifacts:
  Creating directory "d:\dbs\el\143e\target\distrib\Release\x64\abc\..\abc\bin\".
  Zipping directory "d:\dbs\el\143e\target\distrib\Release\x64\abc\" to "d:\dbs\el\143e\target\distrib\Release\x64\abcArtifacts\bin\abc.zip".
_FunctionsPostBuildCopyFiles:
  Copying file from "d:\dbs\el\143e\target\distrib\Release\x64\abc\Azure.Core.dll" to "d:\dbs\el\143e\target\distrib\Release\x64\abc\bin\Azure.Core.dll".
_FunctionsPostBuildCopyFiles:
  Copying file from "d:\dbs\el\143e\target\distrib\Release\x64\abc\Azure.Identity.dll" to "d:\dbs\el\143e\target\distrib\Release\x64\abc\bin\Azure.Identity.dll".

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
1. Create a new project which uses  latest .NetSDK.
2. Build it.
3. Please check drops from the URL and check projectartifact.

**Environment:**
 - Name and version of the Library package used: [.Net SDK 3.0.11] 
 - 
when I reverted the SDK to 3.0.3 it is working fine.

**Comment by divyapurwar** [comment]
I am sorry I have added this bug to Azure SDK. It is related to DOTNET SDK. Is it possible to move it or should I close it and raise another bug in DOTNET SDK Directory?

**Comment by divyapurwar** [comment]
Sorry I am closing this issue here. Thanks for the reply.

**Comment by jsquire** [comment]
@divyapurwar.   No worries at all.   I'm sorry that we weren't able to help you.  Closing and opening a new issue, like you've done, is the best path forward.   Good luck!   😄
