### ISSUE TITLE
Azure web jobs not picking up transaction timeout from machine.config

### ISSUE THREAD

**Issue by pjganesh** [Azure/azure-sdk-for-net#2124]
Hi,
Below are the steps I followed to test this scenario.
- Our web app uses EF 6 with TransactionScope.
- Deployed web app with web jobs in Azure portal.
- When we tested the TransactionManager.MaxTimeout property via Web jobs, it often shows as 00:10:00 (10 mins) and it timesout exactly on it.
- Our requirement is to increase it and we followed some blogs and tried setting it using applicationHost.xdt to increase the transaction timeout in applicationHost.config in Azure.
- I could see the Transform logs that this xdt file got deployed successfully. But still this was not working and TransactionManager.MaxTimeout property returning 00:10:00 (10 mins) only.
- Code in our applicationHost.xdt is as follows -

```
<?xml version="1.0"?>
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
  <system.transactions xdt:Transform="Insert">
    <machineSettings xdt:Transform="InsertIfMissing" maxTimeout="01:00:00" />
  </system.transactions>
</configuration>
```
- Is there any workaround for this to do settings in xdt file and TransactionManager picks it up in Azure web jobs ?
- Also we tried having <system.transactions> in web.config of web app and app.config of web jobs, this didn't worked.

Can someone please help in this regard ?

**Comment by abatishchev** [comment]
Let me reiterate on Ganesh's point. We need to modify machine.config and tried out all known to us techniques:

- Web.config of the web host
- App.config of the console app
- applicationHost.xdt

None of them affected machine.config. TransactionManager.*Timeout properties still return default values of 00:10:00 what is the real roadblocker for us.

Please advise.
Thanks,
Alex
MPSIT Engineering

**Comment by pjganesh** [comment]
Can anyone please help in this issue ?

**Comment by abatishchev** [comment]
@davidebbo hi, please assist in escalation. this critically blocks PI Payment Request (MPSIT/UST) to go live. thanks!

**Comment by davidebbo** [comment]
Please use the [forum](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) for general Azure Web App issues. This does not seem related to the .NET SDK.

**Comment by abatishchev** [comment]
The issue only with WebJobs console host. Web App itself can see the changes in applicationHost.config/xdt.

**Comment by davidebbo** [comment]
That's normal, as `applicationHost.config` is an IIS file, and generally does not apply to Console apps.

Why doesn't it work in app.config? Is this specific to WebJob/Azure, or does this section generally not work from app.config?

**Comment by abatishchev** [comment]
Right, applicationHost.xdt modifies applicationHost.config, IIS-specific config.

But we need to modify machine.config itself or anything intermediate between console's app.config and machine.config. Because `system.transactions/machineSettings` section is marked with `allowDefinition="MachineOnly"`

**Comment by davidebbo** [comment]
There is no way to modify machine.config in Azure Web Apps today. Are you sure that it would work even if you removed the `allowDefinition="MachineOnly"`? Some settings are intrinsically only effective at machine level.

**Comment by abatishchev** [comment]
Yes, removing allowDefinition and setting it in app.config works. Also setting in machine.config directly.

We've moved to WebJobs from Web API where were facing load balancer timeout 230 seconds and now facing 15 minutes timeout of TransactionScope itself. Yes, this is not right to hit the timeout, we're planning to move to Service Fabric but for now this is a serious blocker for us.

**Comment by davidebbo** [comment]
I suggest requesting feature to internal Web App alias. The issue is totally unrelated to this repo.

**Comment by abatishchev** [comment]
@davidebbo oh, right, I'm sorry, we've opened this issue not in the right repo indeed. would be https://github.com/Azure/azure-webjobs-sdk/issues the right place? should I copy it over?

**Comment by adrianhall** [comment]
Seems to be closed as resolved.  If this is not resolved and needs further action, please re-open
