### ISSUE TITLE
Error when use "DefaultAzureCredential" in v1 Azure Function app

### ISSUE THREAD

**Issue by jaganpt** [Azure/azure-sdk-for-net#21262]
Hi, 
I am getting the below error when use "DefaultAzureCredential" in v1 Azure Function app.

Error:
Could not load file or assembly 'Azure.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot find the file specified.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @jaganpt Could you provide some more details about how your function app is configured and its assembly and package dependencies?

**Comment by jaganpt** [comment]
Hi @christothes ,
Please refer the below details.

Function app run time version : ~1 
Assembly and package ependencies:
![image](https://user-images.githubusercontent.com/78982760/119172036-afdea780-ba65-11eb-8194-95a824d74d6a.png)

**Comment by jaganpt** [comment]
Hi @christothes ,
It would be great if you could provide feedback on the above issue. Thanks.

**Comment by christothes** [comment]
related to #21361

**Comment by christothes** [comment]
Hi @jaganpt - Sorry for the slow response. I'll need to look further into this. To get unblocked, is it possible for you to use a later version of Azure Functions?

**Comment by christothes** [comment]
Does the solution mentioned in this issue resolve the issue for you?

https://github.com/Azure/azure-sdk-for-net/issues/21361#issuecomment-848895367

**Comment by jaganpt** [comment]
Hi @christothes ,

It is an existing v1 azure function app. Hence not possible to use later version for now.

**Comment by jaganpt** [comment]
Hi,
I have alredy provided the required information. Please let me know what additional information is needed.

Function App version : v1
Description : Error when use "DefaultAzureCredential" in v1 Azure Function app.
Error:
Could not load file or assembly 'Azure.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The system cannot find the file specified.

Note: It is working for v3 function app. But I could not upgrade my existing production v1 function app.

**Comment by christothes** [comment]
Hi @jaganpt - Did you try the suggestion in this comment? https://github.com/Azure/azure-sdk-for-net/issues/21262#issuecomment-848895760
