### ISSUE TITLE
[QUERY] How to get an instance of TokenCredential if I already (and only) have a valid access token?

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-sdk-for-net#21263]
**Query/Question**
I am trying to list subscriptions and I have a valid access token that I got from some other place. In order to create an instance of `ResourcesManagementClient`, I need `TokenCredential`. However I am not sure how to get it if I only have a valid access token. 

I looked at the documentation for `TokenCredential` class here: https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet and could not find any of the derived classes that would help me out (as far as I can tell).

Am I missing something out here or do I need to create a class of my own?

Any help would be highly appreciated.

**Environment:**
 - Name and version of the Library package used: Azure.ResourceManager.Resources (Version 1.0.0-preview.2) 
 - Hosting platform or OS and .NET runtime version: macOS, .Net 5.0.3
 - IDE and version : Visual Studio for Mac (version 8.9.10)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
> I am trying to list subscriptions and I have a valid access token that I got from some other place. In order to create an instance of ResourcesManagementClient, I need TokenCredential. However I am not sure how to get it if I only have a valid access token.

hi @gmantri - Please try this sample to accomplish this:

https://gist.github.com/schaabs/edbce217621e5ce5aca1a8fa6f711952#authenticating-with-a-prefetched-access-token

**Comment by gmantri** [comment]
@christothes - Many thanks! This is exactly how I ended up implementing.
