### ISSUE TITLE
[Service Bus] setAutoDeleteOnIdle is not working for subscription a topic

### ISSUE THREAD

**Issue by johnwickfootball** [Azure/azure-sdk-for-net#21276]
After sitting up setAutoDeleteOnIdle for 7mins the subscription is not getting delete. I am using Java with Azure service bus version 7.0.2

```
 SubscriptionDescription  sub = ManagementClient.createSubscription(topicName, subName);
 sub.setAutoDeleteOnIdle(duration(7mins);
 ManagementClient.updateSubcribeption(sub);
```

**Comment by jsquire** [comment]
Hi @johnwickfootball.  Thanks for reaching out and we regret that you're experiencing difficulties.   I'm going to transfer this over to the Java SDK repository, as the folks there would be better able to assist.

**Comment by jsquire** [comment]
Issue moved to [Azure/azure-sdk-for-java #21724](https://github.com/Azure/azure-sdk-for-java/issues/21724) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jsquire** [comment]
//cc: @hemanttanwar, @YijunXieMS
