### ISSUE TITLE
Get search/purchase operation by ID

### ISSUE THREAD

**Issue by PetraVujevic** [Azure/azure-sdk-for-net#21270]
Can SDK expose a method to get SearchAvailablePhoneNumbersOperation and PurchasePhoneNumbersOperation by ID?

Since these are long-running operations, we don't want to "await" for their completion because that would block our client/UI. Instead, we want to run them and schedule a task that, once arrived, looks up if the operation is completed or still running. Since we don't have the operation in the memory at this point, we can't use .HasCompleted property of the operation itself - we need to fetch it and look up it's state.

**Comment by DominikMe** [comment]
Synced offline with @PetraVujevic . The challenge is that their service doesn't want to hold any state in memory. So the feature request is to send down info to the client who can then poll the service for status changes.

In other words, we need to be able to serialize a long-running operation and rehydrate it.

@KrzysztofCwalina @tg-msft This request has come up multiple times, where are we at with a standardized design for LRO rehydration?

**Comment by tg-msft** [comment]
The standard pattern in .NET is to add a .ctor overload taking the state necessary to rehydrate (typically just `Operation.Id`) and a client that you'll use to check the status.  See [CopyFromUriOperation](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.copyfromurioperation.-ctor?view=azure-dotnet#Azure_Storage_Blobs_Models_CopyFromUriOperation__ctor_System_String_Azure_Storage_Blobs_Specialized_BlobBaseClient_) as an example.

Using it looks like:
```C#
FooClient client = new FooClient(uri, credential);

// ...

FooOperation operation = await client.StartFooAsync();
string id = operation.Id;
SaveIdForLater(id);

// ... some time later ...

string id = GetIdFromEarlier();
FooOperation operation = new FooOperation(id, client);
await operation.UpdateStatusAsync();
// or await operation.WaitForCompletionAsync();
```

**Comment by DominikMe** [comment]
We will need to have some more conversations with AutoRest as our LRO implementation is generated.

Our team is tracking this work internally
[Feature 2459412: SDK - PhoneNumbers long-running operations can be persisted and rehydrated](https://skype.visualstudio.com/SPOOL/_workitems/edit/2459412)
