### ISSUE TITLE
Add a `BinaryData.ToString()` overload that takes `Encoding`.

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#21272]
Add a `BinaryData.ToString()` overload that takes `Encoding`. When using .NET Framework there is no Encoding.GetString overloads that take a `Span` so you either need to copy or cross-compile or use MemoryMashal.

cc @JoshLove-msft

**Comment by JoshLove-msft** [comment]
Wouldn't this open the door to passing an Encoding when constructing a BinaryData as well?

**Comment by pakrym** [comment]
It would be nice for symmetry but I care less because Encoding.GetByte works well in this case.

**Comment by jsquire** [comment]
I thought we had talked about having the `Encoding` overloads on the constructor and `ToString` at one point, no?   Did we decide against them for some reason?

**Comment by JoshLove-msft** [comment]
If I recall correctly, we opted to not add these for simplicity. If a user wanted to use a different encoding, they could do that directly by using Encoding.GetString. @pakrym brings up a scenario where there are actually perf concerns with doing this on .NET Framework. So the tradeoff is between complicating the API and improving perf for .NET Framework vs keeping a simpler API and making this type less efficient for .NET Framework.

**Comment by annelo-msft** [comment]
It's unclear what a concrete scenario for this is.
