### ISSUE TITLE
[QUERY] Service bus session receiver and deadlettering

### ISSUE THREAD

**Issue by chris-skuvault** [Azure/azure-sdk-for-net#21271]
**Query/Question**
How can we help?

How can deadlettering work with session receivers? All the documentation I've found so far isn't using a message sessions with examples of deadlettering just regular receivers/processors.

I have a solution using session receivers and I can call DeadLetterMessageAsync on my session receiver based on application conditions to put it into the deadletter queue but how do I get the message back out? There doesn't seem to be a way to define a subqueue like you'd do in a non-session enabled queues when creating a new receiver.

Are the deadletter queues when using a session enabled queue not able to be session enabled? What is the correct approach to get dead letter messages out of a session enabled queue? 

Based on https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.1.2/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/SessionReceiverLiveTests.cs#L392 test it looks like for deadletters; there isn't really sessions and instead you'd just create a regular receiver with the SubQueue.DeadLetter being passed in the options. The received deadletter message will have the sessionId property on it so you could modify the message and send it back to the main session enabled queue with that info if needed. Do I have this correct?

**Environment:**
 - Azure.Messaging.ServiceBus 7.1.2
 - Windows

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @chris-skuvault, when receiving from the dead letter subqueue, you would just use a regular receiver as opposed to accepting a session. I will leave this issue open to track the work of adding an additional sample that demonstrates this.

**Comment by JoshLove-msft** [comment]
Closing this out as the README has been updated to include details about how this works for session-enabled entities. Feel free to reopen if there are further questions.

**Comment by chris-skuvault** [comment]
@JoshLove-msft 

In testing deadletter queue, I have seen some delays in messages making it to that queue. For instance I saw a several min delay where I message got removed from the main queue but didn't get added to the deadletter for a few mins. Is this expected occasionally or did I run into some kind of sb networking issue while testing? 

There were no errors received from the library in regards to the dead letter call when it was delayed.

**Comment by JoshLove-msft** [comment]
Hi @chris-skuvault, I just checked with the service team, and they mentioned that when you get the ack for the DeadLetter operation, the message should be ready to be received from the DeadLetter queue. Are you able to repro the issue?

**Comment by Overrided** [comment]
@JoshLove-msft 

Hi
I happen to bump into same situation - having session enabled + dead lettering.
I saw new way to receive Dead Letters you've mentioned above, and I have one question left:

Can I use the Processor instead of the Receiver to get Dead Letter with Session? 

Simple Processor with ```new ServiceBusProcessorOptions { SubQueue = SubQueue.DeadLetter }``` does not react to Dead Letters with Session enabled, and SessionProcessor has no ```SubQueue``` setting in ```ServiceBusSessionProcessorOptions```.

Any advise?)

**Comment by JoshLove-msft** [comment]
when receiving from the DeadLetter subqueue, you would use the regular ServiceBusProcessor/ServiceBusReceiver, even when your main queue has sessions enabled.
