### ISSUE TITLE
[QUERY] How to implement pagination when fetching resources from an Azure Subscription?

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-sdk-for-net#21283]
**Query/Question**
I am trying to fetch a list of all resources from an Azure Subscription. What I want to do is fetch "x" number of records, check for continuation token and then get next set of records. I am not able to figure out how to accomplish the same with `Azure.ResourceManager.Resources` SDK.

It is not clear to me how to include continuation token in the initial request and how to extract continuation token from the result.

            TokenCredential tokenCredentials = new DefaultAzureCredential(); 
            ResourcesManagementClient client = new ResourcesManagementClient("subscriptionid", tokenCredentials);
            var result = client.Resources.List();//Where to put continuation token here???
            //?? How to check and extract continuation token from result?

Any help regarding this will be highly appreciated.

**Environment:**
 - Name and version of the Library package used: Azure.ResourceManager.Resources (Version 1.0.0-preview.2)
 - Hosting platform or OS and .NET runtime version: macOS, .Net 5.0.3
 - IDE and version : Visual Studio for Mac (version 8.9.10)

**Comment by gmantri** [comment]
I think I figured it out. Please see the code below. It fetches one resource group at a time.

```
TokenCredential tokenCredentials = new DefaultAzureCredential();
ResourcesManagementClient client = new ResourcesManagementClient("", tokenCredentials);
var resourceGroupsClient = client.ResourceGroups;
string continuationToken = null;
int pageSize = 1;
do
{
    var response = resourceGroupsClient.ListAsync().AsPages(continuationToken, pageSize);
    var page = response.GetAsyncEnumerator().Current;
    continuationToken = page.ContinuationToken;
    IReadOnlyList<ResourceGroup> resourceGroups = page.Values;
    foreach (ResourceGroup rg in resourceGroups)
    {
        Console.WriteLine($"Name: {rg.Name}; Location: {rg.Location}");
    }
}
while (continuationToken != null);
```

I am wondering if this is the right approach or can this be done in a better way. Keeping the issue open for someone to comment.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by m-nash** [comment]
The Pageable object that is returned by the List call will handle the "next page" logic for you if all you want to do is loop through every item in every page.  When the iterator reaches the end of a page it will check to see if another page exists, and if so make the call to azure and retrieve the next page then continue iterating on the list.

`foreach (ResourceGroup rg in resourceGroupsClient.List())
{
    Console.WriteLine($"Name: {rg.Name}; Location: {rg.Location}");
}`

or async

`await foreach (ResourceGroup rg in resourceGroupsClient.ListAsync())
{
    Console.WriteLine($"Name: {rg.Name}; Location: {rg.Location}");
}`

AsPages can be used for things like passing each page to thread pool to be processed in parallel, but in the simple iteration case its not necessary to use it.
