### ISSUE TITLE
query for session enabled queues 

### ISSUE THREAD

**Issue by lokesh-goyal** [Azure/azure-sdk-for-net#21285]
why messages are not redelivered when message lock expires  OR message is not acknowledged in peeklock mode in session enabled queues

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @lokesh-goyal, the message should be redelivered if the _session lock_ expires, but message locks are not relevant for session enabled queues. If you abandon the message it should be redelivered on the next receive call. If you simply don't acknowledge the message (i.e. don't settle it), then it would not be redelivered until the session lock is lost and the session is accepted again. Hope this answers your question!

**Comment by lokesh-goyal** [comment]
Thanks for the info. I have a one more question regarding the quotas

https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-quotas

In the documentation it is not mentioned how many sessions listeners/receivers we can create on a single queue. 

In the documentation it is mentioned that we can create at max 5000 concurrent connections that means we can only create 5000 session receivers or we can create as many as we want  but only 5000 session receivers receive the message concurrently

**Comment by JoshLove-msft** [comment]
Each session receiver does not require a separate connection, so you should not run into the limit if you are sharing connections between the different session receivers.

**Comment by JoshLove-msft** [comment]
> In the documentation it is mentioned that we can create at max 5000 concurrent connections that means we can only create 5000 session receivers or we can create as many as we want but only 5000 session receivers receive the message concurrently

"we can create as many as we want but only 5000 session receivers receive the message concurrently" is my understanding.

**Comment by JoshLove-msft** [comment]
I've confirmed with the service team that there is no limit on the number of sessions that can be locked at any one time. Feel free to reopen if you have further questions.
