### ISSUE TITLE
Regression on v1.0 where there are missing headers when returning request error

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#21305]
In 1.0-preview.1 of the service, when there was a request error, the service was returning valuable information in the headers, like for example: `Content-type` as `application/json` which helps the SDK do proper parsing of the message in the body. 
We also expose to the customers the `apim-request-id` as a way to communicate that with the service in case further investigation needs to happen.

![MicrosoftTeams-image (4).png](https://images.zenhubusercontent.com/583ddbb0b9dc3c622022b006/4b8d5ba2-69cd-487c-bcfb-77a90dd7f3c0)

We currently don't see this in the v1.0 endpoint and this is causing that the .NET SDK to not be able to present the information to the user.

![MicrosoftTeams-image (5).png](https://images.zenhubusercontent.com/583ddbb0b9dc3c622022b006/5e88ac58-e835-4a7f-990f-5c4c74e19924)

**Comment by maririos** [comment]
Service has been informed and they are looking into it

**Comment by mohamedshabanofficial** [comment]
@maririos 
can you please provide more info?
i understand the premise, ..
but have couple of quiestions ..
1. did the service team do the required update?
2. should we modify our error class to reflect this? and if so, could you provide similar examples (FormRecognizer, or preview 1.0)

**Comment by maririos** [comment]
Great questions.
>1. did the service team do the required update?

They started the process when I created the issue but I am not sure what the result of that was. An easy way to find out before pinging them could be to enable test https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/translation/Azure.AI.Translation.Document/tests/DocumentTranslationClientLiveTests.cs#L2, run it in live mode, and see if it passes. If it passes then we are good to go and just need to re-record the test and leave it enabled. If not, then we need to ping the service team and see where we are.

>2. should we modify our error class to reflect this? and if so, could you provide similar examples (FormRecognizer, or preview 1.0)

We should just enable and re-record our test as the SDK code is correct.
