### ISSUE TITLE
would like more examples

### ISSUE THREAD

**Issue by saseiler** [Azure/azure-sdk-for-net#21316]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8ed471c1-18af-0266-74d3-98449465a17d
* Version Independent ID: bb750d55-4be7-214d-dc30-ee10317e98f5
* Content: [PartitionReceiver Class (Microsoft.Azure.EventHubs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.partitionreceiver?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.EventHubs/PartitionReceiver.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.EventHubs/PartitionReceiver.xml)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ramya-rao-a** [comment]
Samples can be found in https://github.com/Azure/azure-event-hubs/tree/master/samples/DotNet/Microsoft.Azure.EventHubs
