### ISSUE TITLE
AvroUnion serialization does not work for properties with explicit type

### ISSUE THREAD

**Issue by murali-a-pds** [Azure/azure-sdk-for-net#2131]
eg. When attempting to serialize an object of following type

```
[DataContract]
public class TestSample
{
    [DataMember]
    [AvroUnion(typeof(AvroNull), typeof(System.String))]
    public string TestProp { get; set; }
}
```

it fails, with the error message "_No coercion operator is defined between types 'System.String' and 'Microsoft.Hadoop.Avro.AvroNull'_"

Excerpt of serialization code :

```
        var testProp = new TestSample
        {
            TestProp = "main"
        };
        var serializer = AvroSerializer.Create<TestSample>();
        using (MemoryStream ms = new MemoryStream())
        {
            serializer.Serialize(ms, testProp);                
        }
```

If the TestProp is of type object, then the serialization works fine.

Another problem noticed in the same area,

When trying to serialize the following property, received an error _"Expression of type 'System.Int64' cannot be used for parameter of type 'System.Object'"_ 

```
    [DataMember]
    [AvroUnion(typeof(AvroNull), typeof(long))]
    public long StartIndex { get; set; }
```

When the type of StartIndex property is object, then following error was thrown "_The type used in TypeAs Expression must be of reference or nullable type, System.Int64 is neither_"

```
    [DataMember]
    [AvroUnion(typeof(AvroNull), typeof(long))]
    public object StartIndex { get; set; }
```

**Comment by Inverness** [comment]
If you want strong typing for properties you need to use NullableSchemaAttribute instead of AvroUnionAttribute.

This will tell the reflection schema builder to use an union type with the first type being null and the second being your property's type.

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.
