### ISSUE TITLE
I am facing below error while running PowerShell "Get-AzDiagnosticSetting" command 

### ISSUE THREAD

**Issue by lakshayarora476** [Azure/azure-sdk-for-net#21328]
I am facing error "Microsoft.Azure.Management.Monitor.Models.ErrorResponseException" while running Get-AzDiagnosticSetting command in PowerShell. Is there anyone who can help me to resolve this issue. or If there is any alternative for this command that can also work.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4024587-141c-b84b-1778-4c93a0c4355c
* Version Independent ID: 31faced9-6ace-0e64-ff62-28386c2a9976
* Content: [ErrorResponseException Class (Microsoft.Azure.Management.Monitor.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.monitor.models.errorresponseexception?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Monitor.Models/ErrorResponseException.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Monitor.Models/ErrorResponseException.xml)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by navba-MSFT** [comment]
@lakshayarora476 Apologies for the late reply. The PS Get-AzDiagnosticSetting command still seems to be using an older api-version (2017-05-01-preview). The Product owners are aware of this issue and a workitem is in place for the fix. But there is no ETA as of now. Could you please invoke [this](https://docs.microsoft.com/en-us/rest/api/monitor/diagnostic-settings/get ) REST API and test the behavior using [InvokeRestMethod](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.2#examples) and recent api version? 

Awaiting your reply.
