### ISSUE TITLE
IReliableConcurrentQueue<T>.TryDequeue Timeout behavior description

### ISSUE THREAD

**Issue by smstuebe** [Azure/azure-sdk-for-net#21326]
The documentations says:

> If a value was dequeued within the given time, return a ConditionalValue with HasValue as false, else it returns a ConditionalValue with HasValue as true and the Value as the dequeued item of Type T

shouldn't it be:

> If a value was >>>not<<< dequeued within the given time, return a ConditionalValue with HasValue as false, else it returns a ConditionalValue with HasValue as true and the Value as the dequeued item of Type T

?

**Second topic**
I as a reader can't understand what the exact timeout behavior is, because there is this the sentence I mentioned above, but there is also a `TimeOutException`. The documentation should be more explicitly about the differences and when wich case happens. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 717b1d3d-c79c-79bf-d5e6-580ab89954ed
* Version Independent ID: 3e72f47e-8899-ce6e-1fb8-c18ef8a3c978
* Content: [IReliableConcurrentQueue&lt;T&gt;.TryDequeueAsync(ITransaction, CancellationToken, Nullable&lt;TimeSpan&gt;) Method (Microsoft.ServiceFabric.Data.Collections) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicefabric.data.collections.ireliableconcurrentqueue-1.trydequeueasync?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.ServiceFabric.Data.Collections.IReliableConcurrentQueue%601.TryDequeueAsync);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceFabric.Data.Collections/IReliableConcurrentQueue`1.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceFabric.Data.Collections/IReliableConcurrentQueue`1.xml)
* Service: **service-fabric**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
