### ISSUE TITLE
[Documentation] What are the best practices for mixing Management.ResourceManager client with Hyak clients?

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2134]
### Description

Need to decide the right story for mixing client types.  We can

* Undeprecate the older version of the ResourceManager client so that there is a compatible, supported, undeprecated version
* Publish a version of Microsoft.Azure.Common.Authentication that can work with new ADAL and rest clientruntime versions.
* Document how to use ClientRuntime.Azure.Authentication with older clients, using an adapter liek the following:

```C#
public class SubscriptionCredentialsAdapter : SubscriptionCloudCredentials 
{
            ServiceClientCredentials _credentials;
            string _subscriptionId;

            public SubscriptionCredentialsAdapter(ServiceClientCredentials wrapped, string subscriptionId)
            {
                _credentials = wrapped;
                _subscriptionId = subscriptionId;
            }
            public override string SubscriptionId
            {
                get { return _subscriptionId; }
            }

            public override Task ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
            {
                return _credentials.ProcessHttpRequestAsync(request, cancellationToken);
            }
}

```

**Comment by kirthik** [comment]
Added documentation - https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/Documentation/AuthConflictsBetweenSDKs.md
