### ISSUE TITLE
Cannot use StartCopyFromUriAsync for Uri's that have # in the filename in Blob

### ISSUE THREAD

**Issue by karthik-iyer** [Azure/azure-sdk-for-net#21349]
**Describe the bug**
When I try to copy a file having a "#" in the name using the StartCopyFromUriAsync , the Fragment part of the uri is not considered as part of the filename. Also the StartCopyFromUriAsync must consider the filenames with special characters like #.

**Expected behavior**
What is the expected behavior?
 The StartCopyFromUriAsync must consider the Uri with filenames with special characters like #.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
It gives an error saying 
/////////////
The specified blob does not exist.
RequestId:8f7debeb-001e-0064-03a8-511e94000000
Time:2021-05-25T20:59:44.1140397Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 8f7debeb-001e-0064-03a8-511e94000000
x-ms-client-request-id: 3db21d39-ab2a-43bc-ac4d-5f37c92b3410
x-ms-version: 2020-04-08
x-ms-error-code: BlobNotFound
Date: Tue, 25 May 2021 20:59:43 GMT
Content-Length: 215
Content-Type: application/xml

////////

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Use the StartCopyFromUriAsync method with uri of a file with # sign in it.
2. Try executing the method and it gives the above error

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by amnguye** [comment]
Hi could you provide a code snippet and maybe a sample of a file name that has a '#' in it. I attempted to reproduce the error you gave however I was not able to reproduce. I included '#' in the source uri and I was not able to reproduce. I also tried to include '#' in the destination blob and I was not able to reproduce.

**Comment by amnguye** [comment]
Closing this issue as it has gone stale. Please reopen with the answer to the above questions. Thanks.
