### ISSUE TITLE
Avro Serializer looses offset from DatetimeOffset  if useEpochTime is set

### ISSUE THREAD

**Issue by Karamell** [Azure/azure-sdk-for-net#2135]
When roundtripping a `DateTimeOffset` property with an offset different to 0 the serializer will chop off the offset.

To reproduce:
1. make a class with a `DateTimeOffset` property
2. assign a date with offset.
3. set `UsePosixTime=true`
4. serialize/deserialize.

Maybe the DateTimeOffset serializer should not use posixtime.

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.
