### ISSUE TITLE
Azure.Identity not compatible with Azure Function v1 SDK

### ISSUE THREAD

**Issue by Yangsh-w** [Azure/azure-sdk-for-net#21361]
**Describe the bug**
While using the Azure.Identity in a dotnet v1 azure function, it is throwing the following exception.
`System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`

**Expected behavior**
Function get access token via user managed identity.

**Actual behavior (include Exception or Stack Trace)**
`System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`

**To Reproduce**
1. Create a dotnet framework 4.7(v1) function app in visual studio.
2. Add NuGet package Azure.Identity v1.3/v1.4 to this function app. NuGet management after that:
![image](https://user-images.githubusercontent.com/76461730/119596172-436efa00-be11-11eb-86f3-1182056d58c7.png)
3. Edit the function code(function1.cs in my case) as below:
```
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Azure.Core;
using Azure.Identity;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Extensions.Http;
using Microsoft.Azure.WebJobs.Host;

namespace FunctionApp2
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task<HttpResponseMessage> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)]HttpRequestMessage req, TraceWriter log)
        {
            log.Info("C# HTTP trigger function processed a request.");

            try
            {
                log.Info("testing with only azure.identity 1.3");
                AccessToken token = new DefaultAzureCredential().GetToken(new TokenRequestContext());
            }
            catch (Exception ex)
            {
                log.Info(ex.ToString());
            }
            return null;
        }
    }
}
```
Or we could skip step 1-3 with this [test repo](https://github.com/Yangsh-w/azureidentityfatest) I created.
4. Create a dotnet 4.7 function app in azure.
5. Publish the local app to the azure one.
6. Enabled user managed identity for the azure function app.
7. Run the azure function and get the exception.

**Environment:**
 - Azure.Identity v1.3/v1.4, for project limitation, we could not use lower version than 1.3.
 - Windows, dotnet framework 4.7

**Things I tried:**
1. I tried to install the **System.Runtime.CompilerServices.Unsafe 4.6.0** but the issue persists. For project limitation, we could not use lower version than 4.6.0 for this package. I suppose this will not fix the issue because package version 4.6.0 corrosponds to assembly version **4.0.5.0**, as mentioned in [this thread](https://stackoverflow.com/questions/62764744/could-not-load-file-or-assembly-system-runtime-compilerservices-unsafe/62770487#62770487).
2. I also tried following [this article](https://codopia.wordpress.com/2017/07/21/how-to-fix-the-assembly-binding-redirect-problem-in-azure-functions/) to enable binding redirect for my function, but issue persists even after that.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Configuring an assembly binding redirect should resolve the problem. Here is an post that explains some approaches to do it. 

https://stackoverflow.com/questions/38093972/azure-functions-binding-redirect

Your local.settings.json should look like this:

```json
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "AzureWebJobsDashboard": "UseDevelopmentStorage=true",
    "BindingRedirects": "[ { \"ShortName\": \"System.Runtime.CompilerServices.Unsafe\", \"RedirectToVersion\": \"5.0.0\", \"PublicKeyToken\": \"b03f5f7f11d50a3a\" } ]"

  }
}
```

**Comment by Yangsh-w** [comment]
Thank you @christothes  for your reply!

I have already tried the binding redirect and it's listed in the **Things I tired** section - part 2. Unfortunately, it is not working. You could test the same if possible, maybe I'm doing something wrong.

I tied the RedirectToVersion 4.0.4.1 as mentioned in the error message, also tried 5.0.0 as you shared, neither is working.

If the suggestion could work in your environment, could you please point me to the right direction regarding binding redirect?
Otherwise, may I know if there is any other approaches for this issue?

**Comment by christothes** [comment]
Yes, I did get it working. Here is my csproj:

csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <AzureFunctionsVersion>v1</AzureFunctionsVersion>
    <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.4.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.24" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="5.0.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.2" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

I also needed to implement the AssemblyBindingRedirectHelper mentioned in one of the linked blog posts.

**Comment by Yangsh-w** [comment]
Thank you so much @christothes !

Seems I'm missing below 2 lines in our csproj,
```
    <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
```
After I modified my csproj, the 4.0.4.1 issue is not showing again.

Many thanks!
