### ISSUE TITLE
Support for netstandard

### ISSUE THREAD

**Issue by niemyjski** [Azure/azure-sdk-for-net#2136]
When is support for netstandard coming?

**Comment by hovsepm** [comment]
@niemyjski for which library? We have some libraries already converted to .NetCore RC2.

**Comment by niemyjski** [comment]
All of them that I checked were not updated for storage, servicebus and queues

**Comment by hovsepm** [comment]
@niemyjski ServiceBus will not be ported. Storage ARM was ported - https://github.com/Azure/azure-sdk-for-net/tree/AutoRest/src/ResourceManagement/Storage . You should check AutoRest branch.

**Comment by herecydev** [comment]
> ServiceBus will not be ported.

Can I ask why? That seems a really terse decision.

**Comment by moswald** [comment]
If `ServiceBus` is not going to be ported, what's the alternative?

**Comment by herecydev** [comment]
@hovsepm any update on this. You've closed the issue and, by the reactions posted here, confused most people and left us no alternative option.

**Comment by sickboy** [comment]
There is hope? https://github.com/Azure/azure-sdk-for-net/commit/4cf74b3ebafc0ebea9d220d63fe7535326614854
