### ISSUE TITLE
UpdateSiteSourceControlAsync & CreateOrUpdateSiteSourceControlAsync fail with "Parameter x-ms-client-principal-name is null or empty."

### ISSUE THREAD

**Issue by eralston** [Azure/azure-sdk-for-net#2137]
Using the Azure SDK in C#, I am attempting to programmatically setup a site that uses a VSTS git repository for source control. I am able to connect to the repo from the portal easily enough and I simply wish to recreate the process of creating the site then attaching the repo.

I am able to create a site with no issue; however, when I try to attach source control to it, for instance using the following snippet:

```
            using (WebSiteManagementClient websiteClient = await CreateClient())
            {
                Site options = CreateOptions(model);
                var site = await websiteClient.Sites.CreateOrUpdateSiteAsync(Region.Name, model.Name, options);
                model.SystemId = site.Id;

                SiteSourceControl src = new SiteSourceControl() { Branch = "master", RepoUrl = "https://livetilesnyc.visualstudio.com/_git/LiveTiles%20Cloud", DeploymentRollbackEnabled = false, IsManualIntegration = false, IsMercurial = false, Name = model.Name, Location = Region.Location, Type = "VSO" };
                await websiteClient.Sites.CreateOrUpdateSiteSourceControlAsync(Region.Name, model.Name, src);
            }
```

All requests will fail with the following error:

> Parameter x-ms-client-principal-name is null or empty.

I am able to successfully read the source control settings for an existing site using GetSiteSourceControlAsync, which even returns seemingly correct data for a source control configuration created via the Azure Portal; however, attempting an operation like changing properties on that object and calling UpdateSiteSourceControlAsync has the same error as above.

In case anyone thinks I might be able to work around using the Resource client: I have pursued attempting to deploy the site with source control via ARM template (modifying this example here https://github.com/Azure/azure-quickstart-templates/tree/master/201-web-app-github-deploy); however, even when I manage to successfully set the value on source controls, it is unable to fetch from VSTS.

Is loading from VSTS programmatically just not something that can be done?

**Comment by adrianhall** [comment]
Is this still an issue?
