### ISSUE TITLE
Update Identity README/MSDocs

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-net#21388]
Update Docs with details of:
- [ ] PowerShell Credential - Add it to the DAC chain diagram and the Development Platform Credentials matrix section in the README. Update MS Docs with this credential as well.
- [ ] Authenticating with Sovereign Clouds - Add a brief description of the feature with code samples/link to code samples in README/MS-Docs.

**Comment by christothes** [comment]
I noticed these additional docs issues recently
- Update [this DefaultAzureCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) doc to include PowerShellCredential
- VSCode is missing from the diagram both above and in the [main readme](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme)

@g2vinay We should validate whether the above items also need to be addressed in the other langs.
