### ISSUE TITLE
NuGet availability forAzure.ResourceManager.MachineLearningServices

### ISSUE THREAD

**Issue by keesschollaart81** [Azure/azure-sdk-for-net#21403]
**Query/Question**
Any timeline for releasing [the Azure.ResourceManager.MachineLearningServices package](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/machinelearningservices/Azure.ResourceManager.MachineLearningServices) to NuGet?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by paulshealy1** [comment]
We are working on a new dotNet package that will be available later this year. We'll release that package to NuGet when it's available.

**Comment by keesschollaart81** [comment]
Any update on this?
