### ISSUE TITLE
Creating a table entity with a user defined property named ETag fails with 500 code

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#21405]
If you try to add an entity with a user defined property named "ETag", the operation fails with the following error:

```json
{"odata.error":{"code":"InternalServerError","message":{"lang":"en-us","value":"The property or indexer 'Microsoft.Azure.Documents.Resource.ETag' cannot be used in this context because the set accessor is inaccessible\nRequestID:154067c0-7cf7-b79c-6a60-26834a7abbe3\n"}}}
```

Close when this closes
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/168966

**Comment by christothes** [comment]
@sakash279, Do we have an internal tracking bug for this?

**Comment by sakash279** [comment]
Hi @christothes - this was supposed to be a documentation update on our end. @ThomasWeiss for documentation. I will follow up and update here.

**Comment by sakash279** [comment]
Here's the doc update PR for cosmosdb table API : https://github.com/MicrosoftDocs/azure-docs-pr/pull/168966

Please close the issue once the docs are updated.
