### ISSUE TITLE
Validate SDK dependencies 

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#21422]
We should add a check in our EngSys to ensure that the set of dependencies for our libraries will not conflict with the set of dependencies the Functions are using.

The set of dependencies we should validate against for Functions is [here](https://github.com/Azure/azure-functions-host/blob/dev/test/WebJobs.Script.Tests/Microsoft.Azure.WebJobs.Script.WebHost.deps.json).

**Comment by weshaggard** [comment]
I think it would be best if someone on the libraries team does this work. They can build on top of the work I did for powershell last year, see https://github.com/Azure/azure-sdk-for-net/pull/13656.

**Comment by pallavit** [comment]
@jsquire do you see value in doing this?

**Comment by jsquire** [comment]
@pallavit:  Not really, unless we have a source for dependencies that is absolutely reliable, and we can include it as part of the merge validation when `Packages.Daata.props` is updated.  The PowerShell validation runs in the aggregate reports and the dependency list is not maintained, so it's well out of date.   It hasn't provided much value and would be reactive in the best case.

**Comment by pallavit** [comment]
Given this - I will close the issue, please feel free to open if you think otherwise.
