### ISSUE TITLE
[BUG] Azure.Data.Table ConnectionString vs StorageURI/Credentials with Azurite

### ISSUE THREAD

**Issue by thesaladmander** [Azure/azure-sdk-for-net#21433]
**Describe the bug**
Was trying to connect to connect to azurite for local development using the TableClient with a single connection string (as opposed to the StorageUri/Credential way which DOES work).  The azure connection string works out-of-the-box, but the azurite connection string doesn't seem to work.  

**Expected behavior**
new TableClient(connectionString, tableName)..CreateIfNotExists(); won't throw

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Initially I used this connection string:
> string azuriteConnStr = @"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey = Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;";
I think that's right, but the TableClient ctor throws a System.ArgumentOutOfRangeException.  Obviously the string parsing isn't happy with it.

So I tore off the TableEndpoint and that was obviously offending the parser because that got through.  Unfortunately, when I make the 'CreateIfNotExists()' call  I get:
> Azure.RequestFailedException indicating that the "Server failed to authenticate.  Make sure the value of Authorization header is formed correctly the signature...".  

Looking at a log line, I see this:
> [Informational] Azure-Core: Request [a8881d48-ed0c-4b7e-914c-780b571e7780] POST http://devstoreaccount1.table.core.windows.net/Tables?$format=REDACTED

So ... the address is obviously not right.  I CAN add an Endpoint suffix to change some of that, but NOT the base of the URL.  I want localhost:10002 for Azurite.  I don't see anyway to change this.  So I suspect it's not possible.  I think the problem is that the ctor expects the "TableEndpoint=https://myaccount.table.core.windows.net" like in docs, but this obviously doesn't work for local development.

**To Reproduce**
```csharp
public static TableClient CreateAzuriteBad()
{
    string azuriteConnStr = @"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=[[ REDACTED ]];";
    return new TableClient(azuriteConnStr, "myBigFatTable");
}
```

**Environment:**
I'm using the 12.0.0.0-beta.8 release of Azure.Data.Tables.

$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by SteveCurran** [comment]
I am not seeing this fix in 12.4 release of Azure.Data.Tables. Any ETA?

**Comment by christothes** [comment]
> I am not seeing this fix in 12.4 release of Azure.Data.Tables. Any ETA?

Are you saying it is not in the changelog, or that you can still reproduce the error?

**Comment by SteveCurran** [comment]
@christothes both

**Comment by christothes** [comment]
Ah - I think you may be referring to this feature https://github.com/Azure/azure-sdk-for-net/issues/25710

The fix associated with this issue was actually a parsing bug.

**Comment by SteveCurran** [comment]
@christothes Sorry, its an issue with azurite parsing uri for storage account https://github.com/Azure/Azurite/issues/1263
