### ISSUE TITLE
Update SignalR Functions extension to support Azure.Identity

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#21446]
**Library or service name.**
Microsoft.Azure.WebJobs.Extensions.SignalRService
 
**Is your feature request related to a problem? Please describe.**

Right now the only way to connect to SignalRService is via connection string, which causes the developer to have to store the connection string in a secret store.

The SignalR service supports managed identity.

We should update the SignalRService binding to also support Azure Identity.

**Comment by Y-Sindo** [comment]
It is supported since 1.7.0 .
