### ISSUE TITLE
Azure MixedReality ObjectAnchors Conversion Sample issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#21459]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/objectanchors/Azure.MixedReality.ObjectAnchors.Conversion/tests/Samples/AssetConversionProcessSample.cs#L81):
![image](https://user-images.githubusercontent.com/65581162/120147684-9da8fa00-c219-11eb-9a48-b9a85e96261c.png)

Reason: The operation has not completed yet. 
Suggestion: Add 
```
            await operation.WaitForCompletionAsync();

            if (!operation.HasCompletedSuccessfully)
            {
                throw new Exception("The asset conversion operation completed with an unsuccessful status");
            }
```
after line 81 `AssetConversionOperation operation = new AssetConversionOperation(jobId, client);`  

@scottaddie , @AlexGhiondea for notification.

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-net/pull/22460 merged.
