### ISSUE TITLE
[Service Bus] AMQP Link Setting to Expose the Maximum Number of Messages 

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#21451]
# Problem statement

To provide the best possible developer experience, the Service Bus client library attempts to eagerly validate caller-provided data before invoking a service operation to allow for a more responsive API.   To avoid drift between the client and service enforcement, the client limits validations to items that either have meaning only to the client or that are based on information that the Service Bus service provides.

When publishing messages, there is a maximum number of items that the service will accept in a single operation, regardless of any size considerations.  At the time of writing, the Service Bus service will reject any request containing more than 4,500 messages.  Because the service doesn't communicate the object limit, the client library is unable to validate that constraint or provide a guided development experience for ensuring safe limits. 

Please consider exposing the maximum message limit as part of the settings for a `SendingAmqpLink`, following the same pattern that is currently used to communicate the  maximum message size.

# Potential workarounds

Because the limit is not believed to be discoverable, the only viable workaround would be for the client library to hardcode an assumption for the maximum message limit and enforce it.  Some of the shortcomings of this approach are:

  - The client logic may become out-of-sync with the limits enforced by the Service Bus service.  This would lead to a developer experience where the service may reject operations that the client library believes are valid or the client library may be artificially limiting throughput for callers.

- The client logic would have to potentially account for differences in the limits by tier of resource, which exacerbates the first point by adding more potential for drift and additional points of failure.

- Each version of the client library would have a baked-in limit;  this would potentially cause drift between versions of the client library and/or the client libraries in different languages, further exacerbating the the first point and making developer troubleshooting more difficult.

# Desired outcome

- When a sending link is negotiated between the Service Bus client library and the service, the link settings contain a member in the `Settings` collection that defines the maximum message count that the service will accept for any single publishing operation.

- The maximum message limit is dynamic and accurately reflects the limits applied to the specific Service Bus entity that the link was requested for.

- The semantics around communicating the maximum message limit mirror that of the maximum message size that is currently used.

# References and related

- [[Azure Service Bus] Batch.TryAdd should respect service limits of 4500 items max (#19125)](https://github.com/Azure/azure-sdk-for-net/pull/19125)

**Comment by jsquire** [comment]
//cc: @ramya-rao-a, @JoshLove-msft, @hemanttanwar, @conniey, @YijunXieMS, @yunhaoling, @chradek, @richardpark-msft

**Comment by EldertGrootenboer** [comment]
We have opened an investigation task for this in our backlog, and will update this issue when we have more information.

**Comment by danielmarbach** [comment]
This would be cool. Then I can revive my PR. Yehaa :tada:

**Comment by danielmarbach** [comment]
@JoshLove-msft maybe add it to the description too in the references and related section?

**Comment by EldertGrootenboer** [comment]
We have assigned an engineer to look further into this issue. We will update this issue when we have more information.
