### ISSUE TITLE
Azure.Data.Tables 12.0.0-beta.8 - NullReferenceException in tableClient.DeleteEntity

### ISSUE THREAD

**Issue by makar-sasha** [Azure/azure-sdk-for-net#21458]
**Describe the bug**
NullReferenceException in tableClient.DeleteEntity call

**Expected behavior**
Row added and deleted.

**Actual behavior (include Exception or Stack Trace)**
Row is added but not deleted because of exception.

**To Reproduce**
```csharp
            var tableClient = new TableClient(<cs>, <table>);
            var entity = new TableEntity("a", "b")
            {
                { "Product", "Marker Set" }
            };
            tableClient.AddEntity(entity);
            tableClient.DeleteEntity("a", "b");
```

**Environment:**
 - Azure.Data.Tables 12.0.0-beta.8
 - Win 10 .NET 3.1
 - Visual Studio 16.9.6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dan5082** [comment]
I'm also seeing `System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.Data.Tables.TableClient.DeleteEntity(String partitionKey, String rowKey, ETag ifMatch, CancellationToken cancellationToken)    
   at MyTimerTriggeredAzureFunction(TimerInfo timer, ILogger log)` when trying to delete

**Comment by christothes** [comment]
Thanks @dan5082 Could you provide a simple code snippet that reproduces the problem? This one is a bit odd because it works in our current tests.

**Comment by dan5082** [comment]
Windows 10 VS Code using:
Azure Functions Core Tools
Core Tools Version:       3.0.3160 Commit hash: 00aa7f43cc5c5f15241b5e6e5363256f19ceb990
Function Runtime Version: 3.0.14916.0

"Azure.Core" Version="1.14.0"

[FunctionName("ReproduceDeleteIssue")]
         public static async Task ReproduceDeleteIssue(
            [TimerTrigger("0 */12 * * *", RunOnStartup = true)] TimerInfo timer,
            ILogger log
        )
        {
            TableClient client = new TableClient(storageTableConnectionString, "deleteThisTable");
            client.CreateIfNotExists();
            var entity = new TableEntity("TestPartitionKey", "testRowKey")
            {
                { "Product", "Marker Set" }
            };
            client.AddEntity(entity);
            entity = client.GetEntity<TableEntity>("TestPartitionKey", "testRowKey");
            Console.WriteLine($"created entity {entity.RowKey} {entity.PartitionKey}");
            await client.DeleteEntityAsync(entity.PartitionKey, entity.RowKey);
            Console.WriteLine($"Entity Deleted from table");
            client.Delete();
            
           return;
        }

using 12.0.0-beta.6
![image](https://user-images.githubusercontent.com/14451970/120707790-5ff9da80-c480-11eb-8f04-2a09de5412b7.png)

using newest Azure.Data.Tables 12.0.0-beta.8:
![image](https://user-images.githubusercontent.com/14451970/120707907-7ef86c80-c480-11eb-84f6-8bd46a45a180.png)

**Comment by christothes** [comment]
Thanks for providing this info. Unfortunately I still can't reproduce with similar code.

Could you please try with the latest dev build which has the very latest version of the implementation? 

https://dev.azure.com/azure-sdk/public/_packaging?_a=package&feed=azure-sdk-for-net&package=Azure.Data.Tables&protocolType=NuGet&version=12.0.0-alpha.20210603.1&view=overview

**Comment by makar-sasha** [comment]
unfortunately the latest build has the same behavior for me. stack trace doesn't have any useful data (just at Azure.Data.Tables.TableClient.DeleteEntity(String partitionKey, String rowKey, ETag ifMatch, CancellationToken cancellationToken) and no inner exceptions).
 maybe I have to setup some symbols?

**Comment by christothes** [comment]
Can you reproduce it outside of an Azure Function?

**Comment by jkalweit** [comment]
I get the same NullReferenceException in a server-side blazor app. Reverting to 12.0.0-beta.7 fixes it with no code changes.

**Comment by kristofdegrave** [comment]
I'm having the same issue when working with the 12.0.0 version. The 12.0.0-beta.7 works fine.

Delete of both Entity as Table give the same exception.

**Comment by christothes** [comment]
> I'm having the same issue when working with the 12.0.0 version. The 12.0.0-beta.7 works fine.
> 
> Delete of both Entity as Table give the same exception.

@kristapratico Is your repro also in an Azure function? If so, can you reproduce outside of the function? If not, can you provide a snippet of sample code that demonstrates the exception?

**Comment by christothes** [comment]
> I get the same NullReferenceException in a server-side blazor app. Reverting to 12.0.0-beta.7 fixes it with no code changes.

Hi @jkalweit Could you provide a stack trace of the exception?

**Comment by christothes** [comment]
Disregard the code requests, I have a repro now. Thanks!

**Comment by christothes** [comment]
I have a fix, but here is a workaround in the meantime. The issue only exists when the TableClient is created with the connectionString constructor. Here is how you can take a connection string and turn it into a TableSharedKeyCredential so that the other ctor can be used until a fix is available:

```c#
var pairs = storageTableConnectionString
    .Split(';')
    .Select<string, KeyValuePair<string,string>>(p =>
    {
        var pair = p.Split('=', 2);
        return KeyValuePair.Create(pair[0], pair[1]);
    })
    .ToDictionary(p => p.Key, p => p.Value);

string accountName = pairs["AccountName"];
var cred = new TableSharedKeyCredential(accountName, pairs["AccountKey"]);
var uri = new Uri($"https://{accountName}.table.core.windows.net");

TableClient client = new TableClient(uri, "deleteThisTable", cred);
```

**Comment by kristofdegrave** [comment]
@christothes This solves the issue for me. 

To awnser your question, for me it wasn't in an Azure Function context. I was using it to write my workflow data to tablestorage.
