### ISSUE TITLE
DeleteEntity does not allow PartitionKey in Azure.Data.Tables.TableTransactionalBatch

### ISSUE THREAD

**Issue by cesarpv27** [Azure/azure-sdk-for-net#21450]
Library: Azure.Data.Tables.TableTransactionalBatch
Method: DeleteEntity
Version: p12.0.0-beta.6
Framework: netstandard2.0
 
Description:
TableTransactionalBatch class does not contain a public constructor that takes a partition key as parameter.
DeleteEntity method also does not receive the partition key as parameter.
We need a DeleteEntity overload which receives at least the partition key and the row key of target entity

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
This class no longer exists in the latest package version. Please upgrade to the latest.
