### ISSUE TITLE
[QUERY] How to pause the `EventProcessorClient`?

### ISSUE THREAD

**Issue by ibradwan** [Azure/azure-sdk-for-net#21469]
**Query/Question**
Is there a way to pause the EventProcessorClient without stopping it. I do not need to lose the partition ownerships and terminate the underlying connections, what I need is to pause receiving events until I resume it again.

The purpose here is that we have a high throughout system where we need to buffer the received events in memory before processing them and I need to pause the processor when spikes occur to avoid OOM exceptions. Stopping the processor is not an instantaneous operation (could take up to one minute) and we flush the memory every few seconds, so I need some functionality to pause reading the data for a few seconds and then resume it. I believe if pulling the events from EH is supported then we can achieve this by ourselves, but I believe it was not recommended last time I checked.

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs.Processor 5.4.0
 - Hosting platform: Azure App Services, .Net Core 3.1

**Comment by jsquire** [comment]
Hi @ibradwan.   Thank you for reaching out and we regret that you're experiencing difficulties.  There's no formal support for pausing processing; it is either started or stopped.   That said, it would be possible to simulate by taking advantage of the processor waiting for the handler to complete when dispatching events.   If your event handler were to pause, the processor would effectively pause while waiting for the handlers to complete.   

There are some corner cases to be aware of:

  - The handler may be invoked once per partition,  so if you block the handler you'd need to either decide to do that using a shared construct or would need to think about a mechanism to do that only on the desired partitions.

- If there is scaling taking place and partition ownership changes, you may see the processor initialize new partitions and dispatch to the handler, or you may lose ownership for a partition while your handler is blocked; that partition would start processing elsewhere but your hander may still have an (older) event held in memory.

> I believe if pulling the events from EH is supported then we can achieve this by ourselves, but I believe it was not recommended last time I checked.

The `PartitionReceiver` and `EventHubConsumerClient` support pull-based patterns.  The recommendation that I believe your referring to exists as general guidance for those new to the Event Hubs developer ecosystem.  The other clients are a valid and reasonable approach to consuming events so long as you're willing to hold responsibility for resilience and recovery - such as checkpointing.

It would also be possible to to create a custom event processor by deriving from `EventProcessor<TPartition>` _([sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample08_CustomEventProcessor.md))_ and adding the ability to pause there, which would give you a bit more control over event dispatch but would largely be similar to the approach of blocking in the handler.

**Comment by ibradwan** [comment]
Thanks for the comprehensive explanation, I will be thinking about the different approaches you mentioned and will reopen this issue if needed.
