### ISSUE TITLE
Azure Analytics Purview Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#21463]
1.
Section [link1](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/purview/Azure.Analytics.Purview.Catalog#azure-purview-catalog-client-library-for-net),[link2](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/purview/Azure.Analytics.Purview.Scanning#azure-purview-scanning-client-library-for-net):
![image](https://user-images.githubusercontent.com/65581162/120171555-c094d780-c234-11eb-886f-b33fa7c14030.png)
Suggestion: 
Update link to https://docs.microsoft.com/en-us/azure/purview/

2.
Section [link1](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/purview/Azure.Analytics.Purview.Catalog#contributing),[link2](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/purview/Azure.Analytics.Purview.Scanning#contributing):
![image](https://user-images.githubusercontent.com/65581162/120155022-08aafe80-c223-11eb-91a1-5b4b12548cf7.png)
Suggestion:
Add link for `[contributing]`:https://github.com/Azure/azure-sdk-for-net/blob/master/CONTRIBUTING.md 

3.
Section [link1](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/purview/Azure.Analytics.Purview.Scanning#using-azure-active-directory),[link2](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/purview/Azure.Analytics.Purview.Scanning#list-all-data-sources):
![image](https://user-images.githubusercontent.com/65581162/120171880-136e8f00-c235-11eb-8219-29c76a078d8a.png)
Suggestion:  Update `scanning` to `scan`

@jongio for notification.

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-net/pull/22460 merged.
