### ISSUE TITLE
Azure Media VideoAnalyzer Edge Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#21462]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/videoanalyzer/Azure.Media.VideoAnalyzer.Edge#azure-video-analyzer-edge-client-library-for-net):
![image](https://user-images.githubusercontent.com/65581162/120152394-03988000-c220-11eb-9c7d-58ec9acab8bf.png)
Reason: Link is not correct.
Suggestion:  
1.Update link to https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/
2.Update link to https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/direct-methods
3.Update link to https://docs.microsoft.com/en-us/azure/azure-video-analyzer/video-analyzer-docs/pipeline
4.Update link to https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/videoanalyzer/Azure.Media.VideoAnalyzer.Edge/src

2.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/videoanalyzer/Azure.Media.VideoAnalyzer.Edge#authenticate-the-client):
![image](https://user-images.githubusercontent.com/65581162/120153604-8241ed00-c221-11eb-9aa9-852bb7fc552f.png)
Suggestion:  
Update link to https://github.com/Azure/azure-iot-sdk-csharp

3.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/videoanalyzer/Azure.Media.VideoAnalyzer.Edge#install-the-package):
![image](https://user-images.githubusercontent.com/65581162/120154271-48251b00-c222-11eb-868e-f08c4ce65348.png)
Suggestion:
	1. Add link for NuGet: https://www.nuget.org/packages/Azure.Media.VideoAnalyzer.Edge
	2. Add link for NuGet: https://www.nuget.org/packages/Microsoft.Azure.Devices/

4.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/videoanalyzer/Azure.Media.VideoAnalyzer.Edge#contributing):
![image](https://user-images.githubusercontent.com/65581162/120154505-8ae6f300-c222-11eb-9469-6ea10b8f032d.png)

Suggestion:  Add link https://opensource.microsoft.com/codeofconduct/faq/

@jongio for notification.

**Comment by jsquire** [comment]
//cc: @giakas

**Comment by v-xuto** [comment]
Close this issue, due to PR https://github.com/Azure/azure-sdk-for-net/pull/22459 merged.
