### ISSUE TITLE
PersonDirectory support

### ISSUE THREAD

**Issue by cvb941** [Azure/azure-sdk-for-net#21467]
Hello,

A new feature PersonDirectory has been added to the Cognitive Face API in April.
However, it does not yet seem to be present in the SDK for .NET.

Could you release a new version of the Face SDK with PersonDirectory included?

Thank you

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by navba-MSFT** [comment]
@cvb941 Apologies for the late reply. Could you please confirm if [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.vision.face.ifaceclient.persondirectory?view=azure-dotnet) is what you are referring to ? Awaiting your reply.

**Comment by cvb941** [comment]
It seems to be included now, thanks.

You might want to update the [example documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/face/face-api-how-to-topics/use-persondirectory#verify-faces-against-persons-in-the-persondirectory) to include the usage of the new models and methods from the library, instead of using manually created HTTP calls.
