### ISSUE TITLE
Azure.Data.Tables not working under .NET 4.7.2

### ISSUE THREAD

**Issue by isoindisystems** [Azure/azure-sdk-for-net#21472]
**Describe the problem**
Under .NET 4.7.2 you cant query tables of the Azure Table Storage

**Expected behavior**
All data of the table should be returned

**Actual behavior (include Exception or Stack Trace)**
The following exception is thrown:
"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:b775b6da-5002-0060-7ef4-562996000000\nTime:2021-06-01T14:46:21.3463852Z\r\nStatus: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)\r\nErrorCode: AuthenticationFailed\r\n\r\nContent:\r\n{\"odata.error\":{\"code\":\"AuthenticationFailed\",\"message\":{\"lang\":\"en-US\",\"value\":\"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\nRequestId:b775b6da-5002-0060-7ef4-562996000000\\nTime:2021-06-01T14:46:21.3463852Z\"}}}\r\n\r\nHeaders:\r\nx-ms-request-id: b775b6da-5002-0060-7ef4-562996000000\r\nx-ms-error-code: REDACTED\r\nContent-Length: 299\r\nContent-Type: application/json\r\nDate: Tue, 01 Jun 2021 14:46:21 GMT\r\nServer: Microsoft-HTTPAPI/2.0\r\n"

**To Reproduce**
1. Create a new Project with .NET 4.7.2
2. Initialize a TableClient with a SAS and a tablename
3. var query = tableClient.Query<TableEntity>();
4. foreach(var item in query)
5. Exceptions gets thrown

**Environment:**
Azure.Data.Tables-beta.8
Windows 10 with Visual Studio 2017
.NET Framework 4.7.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @isoindisystems - I can't reproduce the issue you are describing. Could you please include a short code snippet that demonstrates how you are constructing the client and executing the query?

**Comment by isoindisystems** [comment]
Sure! I found another interesting thing:
I checked the request with fiddler and found out, that the SASString was encoded before the request.
With the encoded string the request failed.
