### ISSUE TITLE
Add Support for ChainedTokenCredential in Azure Functions Extensions

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#21479]
**Library or service name.**

Azure Functions Extensions
 
**Is your feature request related to a problem? Please describe.**

Azure Identity in Azure Functions is great!

I would love to also see it support ChainedTokenCredential.

```
MyConnection__credential="azureCliCredential, managedIdentity"
```

And then the options would stick for each of the well-known types, i.e.:

```
MyConnection__clientId=""
```

Would work for all types that support clientId param.

I would say to not make it too complex, start with that.  But I could see a scenario where someone would want to use different param values for each type, i.e. Have a diff __clientId for the first credential in the list than the rest of them.

azsdke2e
azsdke2e2

**Comment by jsquire** [comment]
Routing to @AlexGhiondea, as the lead for Functions integrations.

//cc: @christothes, @schaabs (for Identity expertise)

**Comment by jongio** [comment]
@joshfree - Not sure if this would fall under Azure Identity or the Functions extensions work.  Also tagging @JoshLove-msft
