### ISSUE TITLE
[QUERY] Mocking Azure.Storage.Blobs.BlobContainerClient?

### ISSUE THREAD

**Issue by jez9999** [Azure/azure-sdk-for-net#21473]
I'm rather confused by the Azure.Storage.Blobs.BlobContainerClient class. One of its constructors (without any parameters) has documentation that suggests the class was specifically designed for mocking:

```
// Summary:
//     Initializes a new instance of the Azure.Storage.Blobs.BlobContainerClient class
//     for mocking.
protected BlobContainerClient();
```

However, some of the class's methods require things to be returned that have no public constructor and therefore cannot be meaningfully mocked. For example:

```
public virtual Pageable<BlobItem> GetBlobs(BlobTraits traits = BlobTraits.None, BlobStates states = BlobStates.None, string prefix = null, CancellationToken cancellationToken = default);
```

Although `Pageable<T>` can be mocked because it has a protected constructor, the type that it's required to return (`BlobItem`) cannot; there's no public constructor. The only thing a mock can do is return an empty list, which is not at all useful. Am I missing something, or or this a significant oversight in one's ability to mock this class?

**Comment by KrzysztofCwalina** [comment]
Take a look at https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobsmodelfactory?view=azure-dotnet. It's a type designed for constructing values returned from client methods.

You might also find the following document useful. It describes basics of mocking with the new Azure SDK libraries: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Mocking.md

**Comment by jez9999** [comment]
Yes, `BlobsModelFactory.BlobItem("abc")` and then `Page<BlobItem>.FromValues(new[] { blobItemValue }` seems to work, thanks.
