### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.x release date

### ISSUE THREAD

**Issue by alexeymarkov** [Azure/azure-sdk-for-net#21510]
Hi,

when are you going to release Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.x?

Regards,
Alexey

**Comment by jsquire** [comment]
Thank you for your question.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
//cc: @pakrym, @JoshLove-msft

**Comment by pakrym** [comment]
We are planning for Q3 2021

**Comment by swettstein** [comment]
Q3 is nearly over. is everything still on track?

**Comment by swettstein** [comment]
@pakrym today is the end of Q3 2021. any update on the release?

**Comment by AlexGhiondea** [comment]
@swettstein thanks for your interest. 

We are working on this and I will update this issue when we have a concrete answer.

**Comment by AlexGhiondea** [comment]
This is now available! 🙂.
