### ISSUE TITLE
[QUERY] How to get list of topics from ServiceBusAdministrationClient

### ISSUE THREAD

**Issue by rorococo** [Azure/azure-sdk-for-net#21518]
Query/Question
I want to get a list of all topics created during tests so that I can delete them. This is what I have tried so far but topics.MoveNextAsync() just silently fails. Is there any other way to get all the topics?

`            
    var topics = _adminClient.GetTopicsAsync().GetAsyncEnumerator();

    try
    {
        while (await topics.MoveNextAsync())
        {
            var topic = topics.Current;
            if (topic.Name.StartsWith("test-topic-azure"))
            {
                await _adminClient.DeleteTopicAsync(topic.Name);
            }
        }
    }
    finally
    {
        await topics.DisposeAsync();
    }
`

Environment:
Azure.Messaging.ServiceBus 7.1.0
Hosting platform or OS and .NET runtime version: Windows 10.0.19042, .NET 5.0.103
IDE and version : Visual Studio 16.8.2

**Comment by jsquire** [comment]
Hi @rorococo.  Thank you for reaching out and we regret that you're experiencing difficulties.   The `AsyncPagable` returned by `GetTopicsAsync` is a standard async enumerable and can be iterated with the `await foreach` pattern.    More details can be found in this [MSDN article](https://docs.microsoft.com/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8)

For your snippet, this would look something like:

```csharp

var topics = _adminClient.GetTopicsAsync();

await foreach (var topic in topics)
{
    if (topic.Name.StartsWith("test-topic-azure"))
    {
        await _adminClient.DeleteTopicAsync(topic.Name);
    }
}
```

**Comment by rorococo** [comment]
Hi @jsquire 
This is what I had tried originally but also silently failed as soon as it went into the foreach

**Comment by jsquire** [comment]
Hi @rorococo.   Can you help me better understand the behavior that you're describing when you say "silently failed?"   Were you just not seeing any topics in the loop or were you seeing an exception at some point in the code.


//cc: @JoshLove-msft

**Comment by rorococo** [comment]
No exceptions. It literally stops the project from running at that point

**Comment by jsquire** [comment]
Hi @rorococo.   I'm afraid that I still don't understand the behavior that you're describing.  When you say "stops the project from running" do you mean:

- Your application exits (terminates without error?)
- Your application hangs at some point in the code with the process still running but nothing executing?
- Your IDE hangs while running your project in debug/release mode?

I've been unable to reproduce any issues with the code snippet that I shared;  I'm seeing topics be enumerated and deleted with multiple pages of results.  The one caveat is that I'm working against topics that have no real volume of messages published to them nor with subscriptions actively reading that may cause Service Bus to respond more slowly to remove them.

I'd recommend that we start by testing against a fresh Service Bus namespace and set of topics in your environment which are empty and without subscriptions.  We should also consider logging to understand where in the execution any freeze or termination happens.  Finally, we'll also probably want to capture the Service Bus SDK logs to understand the client's view of things.  _(sample [here](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#logging))_

Would you also be so kind as to share:

- What tier your Service Bus namespace is?
- How many topics are being enumerated in your test case?
- How many subscriptions exist against the topic?
- Are there active readers for any subscriptions as you're running this delete process?
- Are there any active publishers for the topic as you're running this delete process?
- What is the host environment for the application running your test case?   (console application, Azure Function, etc)
- Anything else that may be unique about your environment that may help reproduce.

**Comment by rorococo** [comment]
The application exits without error.
There are multiple topics, max will be about 10. Some topics may have messages on the subscriptions. Each topic will have one or two subscriptions.

The delete method is called in a Dispose method at the end of all tests being completed. So there may be multiple instances of my bus implementation at this time. Meaning there could be multiple processors running but this shouldn't affect me being able to loop through the topics?


Tier: standard.
Running using test explorer in visual studio

**Comment by jsquire** [comment]
Thank you for the additional context.   The VS test runner makes it a bit difficult; in my experience, it can often swallow exceptions in infrastructure that aren't triggered in an individual test.   It may, or may not, help to try running via the command line to see what happens.   

> So there may be multiple instances of my bus implementation at this time. Meaning there could be multiple processors running but this shouldn't affect me being able to loop through the topics?

I wouldn't expect that to impact your ability to loop through the topics, though I honestly don't know what the Service Bus service behavior is if you ask to delete a topic that has an associated subscription with an active reader.   I'd expect an error on the `Delete` call, however, not a silent ignore.    I'll block some time early next week to try to simulate active readers on an associated subscription and see if that reproduces what you're seeing.

I believe that our best bet to understand will be collecting the SDK logs.   That will give us insight into the service calls being made and the responses coming beck from the Service Bus administration endpoint and what the SDK is doing with them in your specific environment.  I'm hopeful that will either give us an understanding of the root cause of the behavior that you're seeing or at least help to narrow the areas that we'll want to dig into.
