### ISSUE TITLE
TableClient(Uri) constructor passes forbidden null to TableClient(Uri, AzureSasCredential) constructor

### ISSUE THREAD

**Issue by Identifier** [Azure/azure-sdk-for-net#21521]
https://github.com/Azure/azure-sdk-for-net/blob/41beb1fe0f106ea80bff5127a3965631f61891a7/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L84

When you pass just a single Uri to `new TableClient(endpoint)` that contains all of the connection information (endpoint, tablename, sas credentials, etc), it calls `: this(endpoint, null, ...)` passing `null` for `credential`, but that overload of the constructor immediately calls `Argument.AssertNotNull(credential, nameof(credential))` and throws an `ArgumentNullException`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
@Identifier - Thanks, I can see how this behavior can cause a problem. As a workaround, until this is fixed, you can pass the string value of the full connection string to this ctor:

https://github.com/Azure/azure-sdk-for-net/blob/d77cf20b959d18fff101b6d105994a29f8745640/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L167

**Comment by Identifier** [comment]
@christothes - That constructor won't work for SASs, but this is the workaround I'm using (where `uri` is the full SAS): `new TableClient(new Uri($"{uri.Scheme}://{uri.Host}"), new AzureSasCredential(uri.Query))`

**Comment by christothes** [comment]
Sorry, I for some reason read the initial problem description as using a full connection string (not a SAS). I have a PR out now with the fix.
