### ISSUE TITLE
Add Digital Twins Performance Tests

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-net#21527]
Add Performance tests for the performance-critical champion scenarios of Digital Twins SDK.

Performance Test Writing Guidelines:
https://github.com/Azure/azure-sdk-for-net/wiki/Writing-performance-tests-for-Client-libraries

**Comment by azabbasi** [comment]
We have checked in the perf test for the QueryAsync API on ADT. Closing the issue and waiting for feedback.
