### ISSUE TITLE
[FEATURE REQ] Include CloudError.Message in CloudException.ToString()

### ISSUE THREAD

**Issue by shawnnapora** [Azure/azure-sdk-for-net#21533]
**Library or service name.**
`Microsoft.Rest.ClientRuntime.Azure`
 
**Is your feature request related to a problem? Please describe.**
The `Microsoft.Rest.Azure.CloudException` [exception](https://github.com/Azure/azure-sdk-for-net/blob/eb00937e0741a8dfe8c45c6365d5d8606a261dc3/sdk/mgmtcommon/ClientRuntime.Azure/ClientRuntime.Azure/CloudException.cs#L12) currently uses the default `.ToString()` inherited from `Exception`, but the important information describing what error actually occurred is generally only able to be found in the `CloudError` in the [CloudException.Body](https://github.com/Azure/azure-sdk-for-net/blob/eb00937e0741a8dfe8c45c6365d5d8606a261dc3/sdk/mgmtcommon/ClientRuntime.Azure/ClientRuntime.Azure/CloudException.cs#L27). This presents a problem for debuggability when we log exceptions throughout our services: we would currently need to wrap every area that we interact with Azure in order to catch `CloudException` and throw a new, more loggable exception or specially handle `CloudException` in our logging infrastructure.

`CloudException` could override `.ToString()` and display the `CloudException.?Body.?Message` if present, allowing us to understand what failed simply from the exception being logged into our logging infrastructure.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by shawnnapora** [comment]
Oops, I just (re)discovered that the `CloudException.Body` `CloudError` may also have nested `CloudError`s under `CloudError.Details`. Ideally we'd walk these or otherwise expose all of them.

**Comment by markcowl** [comment]
Thanks for your feedback, unfortunately we aren't currently making enhancements to the the Rest ClientRuntime, as we are moving to an SDK based on the Azure.Core library.  We generally handle simple summaries of the exception by placing the most relevant bits from the response body (code, message) into the message property of the exception, which allows all exceptions to be processed uniformly.  If we were to take such an enhancement, we generally wouldn't override the ToString(), but would enhance the contents of the exception Message property.

**Comment by shawnnapora** [comment]
👍 I came to the same conclusion (enhancing Message) by the time I made a wrapper so that I can get more error detail for our service, but I have to wrap the exception everywhere we care about those details.

Thanks for your response!
