### ISSUE TITLE
Add Schema Registry Performance Tests

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-net#21530]
Add Performance tests for the performance-critical champion scenarios of Schema Registry SDK.

Performance Test Writing Guidelines:
https://github.com/Azure/azure-sdk-for-net/wiki/Writing-performance-tests-for-Client-libraries

**Comment by pallavit** [comment]
@jsquire , @m-redding please let me know if this issue can be closed.

**Comment by m-redding** [comment]
@pallavit do you know if there is still a goal to have perf tests for all services? Are there any guidelines as to which services should have them? This hasn't been done for `Azure.Data.SchemaRegistry`, but it has for `Microsoft.Azure.Data.SchemaRegistry.ApacheAvro`.  If it should be done for `Azure.Data.SchemaRegistry`, I can work on this one.

**Comment by pallavit** [comment]
@m-redding I do see most of our HLCs having perf but I do not see that being propagated to DPG libraries. Do you see any perf sensitive scenarios for this SDK? If so, I do think there is merit in doing it. However if you don't think there are any such scenarios I would recommend closing it. Creating perf libraries w/o a specific perf sensitive scenarios seems like an overkill
/cc: @jsquire

**Comment by m-redding** [comment]
There aren't any perf-sensitive scenarios part of Azure.Data.SchemaRegistry. All the APIs are just putting headers into responses with models. I'll close this one out.
