### ISSUE TITLE
[QUERY] KeyVault: Sharelink sample can not be built in vs code

### ISSUE THREAD

**Issue by Jinnanms** [Azure/azure-sdk-for-net#21543]
**Environment:**
Sharelink 

I download sharelink.zip and extract it, but build in vs code, error is:
...\ShareLink\Properties\AssemblyInfo.cs(4,23): error CS0234: The type or namespace name 'CodeGenSuppressTypeAttributeAttribute' does not exist in the namespace 'Azure.Core' (are you missing an assembly reference?)

can anyone give me some idea? thanks

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Did you run `dotnet restore` on the project?

**Comment by heaths** [comment]
And how did you build it in VSCode? You need to run `dotnet build` (which does restore automatically by default). I was able to download the ZIP from the Samples Browser, extract it, and build it with `dotnet build` per instructions in the README successfully.

Please include all commands and output.

**Comment by Jinnanms** [comment]
I open the VS code from extracted folder；open terminal, run dotnet build:
PS C:\Users\jinnliu\ShareLink> dotnet build

Welcome to .NET Core 3.1!
---------------------
SDK Version: 3.1.409

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of tlemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Find out what's new: https://aka.ms/dotnet-whats-new
Learn about the installed HTTPS developer cert: https://aka.ms/aspnet-core-https
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs
Write your first app: https://aka.ms/first-net-core-app
--------------------------------------------------------------------------------------
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored C:\Users\jinnliu\ShareLink\ShareLink.csproj (in 661 ms).
Properties\AssemblyInfo.cs(4,23): error CS0234: The type or namespace name 'CodeGenSuppressTypeAttributeAttribute' does not exist in the namespace 'Azure.Core' (are
you missing an assembly reference?) [C:\Users\jinnliu\ShareLink\ShareLink.csproj]
Properties\AssemblyInfo.cs(4,23): error CS0234: The type or namespace name 'CodeGenSuppressTypeAttribute' does not exist in the namespace 'Azure.Core' (are you missBuild FAILED.

Properties\AssemblyInfo.cs(4,23): error CS0234: The type or namespace name 'CodeGenSuppressTypeAttributeAttribute' does not exist in the namespace 'Azure.Core' (are 
you missing an assembly reference?) [C:\Users\jinnliu\ShareLink\ShareLink.csproj]
Properties\AssemblyInfo.cs(4,23): error CS0234: The type or namespace name 'CodeGenSuppressTypeAttribute' does not exist in the namespace 'Azure.Core' (are you missing an assembly reference?) [C:\Users\jinnliu\ShareLink\ShareLink.csproj]
    0 Warning(s)
    2 Error(s)

and run dotnet add package Azure.Core, run dotnet build again, error is same.

**Comment by heaths** [comment]
I see what happened. https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/share-link/ was just recently updated. The "Properties" folder wasn't even there before, but is now and shouldn't be. I'll fix the sample.

**Comment by heaths** [comment]
Thank you for reporting this. I checked in a change that should fix this. I copied the files out as if they were downloaded from Samples Browser, so this should work. It may take a few days to upload to Samples Browser, though. If you'd like, you can clone this repo and either build the sample from within sdk/keyvault/samples/ShareLink or copy the source files for your own project needs (i.e. not as a running executable, but the generated REST client) by running `dotnet build /t:CopySource /p:Destination="<path\to\wherever>"` on that same project.

**Comment by Jinnanms** [comment]
Thank you for supporting. I download the raw code of ShareLink.csproj, and replace it in my project, and build it again, success.
