### ISSUE TITLE
[Container Registry] Validate delete 404s

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-net#21554]
On delete operations that return a status code of 404, we should validate the body of the response contains the appropriate response of `NAME_UNKNOWN` for `delete_repository`, `TAG_UNKNOWN` for `delete_tag`, and `MANIFEST_UNKNOWN` for delete_manifest` operations

**Comment by annelo-msft** [comment]
@seankane-msft, can you share the scenario that requires this?

**Comment by annelo-msft** [comment]
Closing since .NET doesn't have a precedent for this.
