### ISSUE TITLE
latest preview fails to install via Nuget

### ISSUE THREAD

**Issue by fayyazpoonawala** [Azure/azure-sdk-for-net#2157]
Hello, i was trying to install the 1.1.3-preview version of Microsoft.Azure.ResourceManager
and while restoring the package, i get this exception:

PM> Install-Package Microsoft.Azure.Management.ResourceManager –Pre
Attempting to resolve dependency 'Microsoft.Rest.ClientRuntime.Azure (≥ 3.1.0 && < 4.0.0)'.
Attempting to resolve dependency 'Microsoft.Rest.ClientRuntime (≥ 2.1.0 && < 3.0.0)'.
Attempting to resolve dependency 'Newtonsoft.Json (≥ 6.0.8)'.
**Install-Package : 'Microsoft.Azure.Management.ResourceManager' already has a dependency defined for 'System.Runtime.Serialization.Primitives'.
At line:1 char:1
+ Install-Package Microsoft.Azure.Management.ResourceManager –Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId :** NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
Is this a known issue and if so, what is the workaround?

**Comment by alistairwhite** [comment]
Hi, 

I had the same issue in VS2013 and updating the Nuget Package Manger as mentioned in the answer for http://stackoverflow.com/questions/25725545/nuget-x-already-has-a-dependency-defined-for-y solved the problem for me.

Link to the package manager for VS2013: https://visualstudiogallery.msdn.microsoft.com/4ec1526c-4a8c-4a84-b702-b21a8f5293ca

Version of package manager I installed was 2.12.0.817

**Comment by hovsepm** [comment]
Please update VS 2013 to the latest update 5 and update nuget package manager from VS 2013->Tools->Extensions and updates

**Comment by JoeBrockhaus** [comment]
I'm currently getting this same error attempting to create a nuget package that depends on Microsoft.Rest.ClientRuntime 2.3.2. Using the latest version of NuGet & VS Updates, and the same error occurs in VSO during the NuGet Packager step. The nuspec for the MS.Rest.CR has somewhat goofy syntax for Versions .. not sure if that could be causing issues (version="[1.0.0.0, )"). 

Any insight into the source of this error that might help point us in the direction to get this solved?
