### ISSUE TITLE
[QUERY] Trouble configuring the retry mechanism using exponential retry mode

### ISSUE THREAD

**Issue by jsum04** [Azure/azure-sdk-for-net#21581]
Trouble configuring the retry mechanism using exponential retry mode
This is the config I have for the client..

```csharp
var options = new ServiceBusClientOptions()
                {
                    RetryOptions = new ServiceBusRetryOptions()
                    {
                        Mode = ServiceBusRetryMode.Exponential,
                        Delay = TimeSpan.FromSeconds(10),
                        MaxDelay = TimeSpan.FromMinutes(5),
                        MaxRetries = 100
                    }
                };

Session processor options
ServiceBusSessionProcessorOptions()
{
    PrefetchCount = 10,
    AutoCompleteMessages = false,
    MaxAutoLockRenewalDuration = TimeSpan.FromMinutes(5),
    MaxConcurrentCallsPerSession = 1,
    MaxConcurrentSessions = 3,
    SessionIdleTimeout = TimeSpan.FromMilliseconds(30)
});
```

I am getting this error while configuring the retry mechanism. Want to correctly understand the exponential retry mode so that I can set it to the max value.

TimeSpan overflowed because the duration is too long.

```text
at System.TimeSpan.Interval(Double value, Double scale)
   at Azure.Messaging.ServiceBus.Core.BasicRetryPolicy.CalculateExponentialDelay(Int32 attemptCount, Double baseDelaySeconds, Double baseJitterSeconds, Random random)
   at Azure.Messaging.ServiceBus.Core.BasicRetryPolicy.CalculateRetryDelay(Exception lastException, Int32 attemptCount)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenLinkAsync(Boolean isProcessor, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.OpenLinkAsync(Boolean isProcessor, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.CreateSessionReceiverAsync(String entityPath, ServiceBusConnection connection, IList`1 plugins, ServiceBusSessionReceiverOptions options, String sessionId, CancellationToken cancellationToken, Boolean isProcessor)
   at Azure.Messaging.ServiceBus.SessionReceiverManager.CreateReceiver(CancellationToken processorCancellationToken)
   at Azure.Messaging.ServiceBus.SessionReceiverManager.CreateAndInitializeSessionReceiver(CancellationToken processorCancellationToken)
   at Azure.Messaging.ServiceBus.SessionReceiverManager.EnsureCanProcess(CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.SessionReceiverManager.ReceiveAndProcessMessagesAsync(CancellationToken processorCancellationToken)
```

Azure.Messaging.ServiceBus 7.2.0-beta.3
Azure app service S1 
Dotnet core 3.1

**Comment by jsquire** [comment]
Hi @jsum04.  Thank you for reaching out and we regret that you're experiencing difficulty.  Your approach to configuring is correct;  this is a bug in the way that we're calculating the delay before clamping to the `MaxDelay` value.   I'll fix up the calculation.

One thing that is of note is that this scenario doesn't occur until the 38th retry attempt with your configured values.  By the time you hit the overflow, you've failed 37 consecutive times and waited 2 hours and 45 minutes for a single operation to complete.  That's an unusually long period of time to consider an error transient.

I'd be interested in understanding your scenario and why you've chosen this pattern, if you're open to sharing.

**Comment by jsquire** [comment]
Fixed by #21591

**Comment by jsum04** [comment]
Hi jsquire, Thanks for the response. I wanted to retry exponentially atleast 100 times incase of an connectivity issue with service bus. I could probably reduce the Delay to 2 secs and the retry count to 50 to avoid this scenario. Would that work?
You have raised an interesting point that it should have failed 37 times before it threw this exception. Does the call come to ServiceBusSessionProcessor.ProcessErrorAsync in these scenarios? I want to verify that as I had a logger statement in the ProcessErrorAsync handler, but it wasn't logged 37 times. Also, I see it happen at least a couple of times in a day, does that mean, the client is losing its connection or could these be caused due to other reasons. My understanding was that the retry option are there to handle transient errors like connection failures. Please correct me If my understanding is wrong. Our application is hosted in azure itself so I am not sure why it would loose connections that many times.

**Comment by jsquire** [comment]
> Would that work?

Any values that are accepted by validation will work, after the fix is released.   The decision lies in what you believe helps your application scenario best.

> You have raised an interesting point that it should have failed 37 times before it threw this exception. Does the call come to ServiceBusSessionProcessor.ProcessErrorAsync in these scenarios? 

Retries are handled by the SDK implicitly when an error is deemed transient.   The error handler is invoked only if all configured retries for a single operation fail.   In this case, your processor was effectively frozen for nearly 3 hours on one operation, unable to make forward progress.  You would only know about the failures if you had registered an Event Source listener and were monitoring the SDK logs.    _(To be pedantic, at least one task was stuck in the retry loop; if you had set max concurrency higher than one, you may still have seen activity from the other tasks)_  

The processor itself is built to be resilient and continue attempting to recover in the face of failures for individual operations.  For example, if you had used the default retry configuration, operations that fail would be retried 3 times silently and then be surfaced to the error handler so that your application was made aware.  The processor would continue running and reading events.   The intent of that design is to be sure that your application is able to observe problems that appear transient to the SDK but may indicate a pattern that indicates there are problems that the application may need to take action to resolve.

My recommendation would be to use a retry configuration closer to the default and allow the processor notify your application of persistent issues.   

>  Also, I see it happen at least a couple of times in a day, does that mean, the client is losing its connection or could these be caused due to other reasons.

If you're seeing the overflow consistently, that's the sign of a big problem.  Nothing that is truly transient should fail consistently for 3 hours.   Any connection issues should recover in a retry or two unless there's a larger issue.  Without knowing what the actual exceptions are that you're experiencing, it's difficult to speculate beyond that.

**Comment by jsum04** [comment]
Hello jsquire, If one of the processor is having issues to connect to the service bus, wouldn't the remaining have the same issue as they would be using the service bus client connection? I did set my consumers to 3. I haven't seen any other exception getting logged in the error event handler. Could you please point to how to register an event source listener to get the errors. As I mentioned earlier, my application is hosted in azure so I am not sure what it causing the transient errors without further log info.
Also could you please tell me what is the default configuration for the retry mechanism.

**Comment by jsquire** [comment]
If you're having connection issues that are transient, something closer to the default retry policy should overcome them.   If your processor is having connection issues that are persistent or that occur for long periods of time, I would suspect that you want to know about them and should let the operation fail and trigger the error handler.   

The important bit that is that the processor does not halt on an exception; it will continue attempting to read messages until it is explicitly stopped.   The main difference in behavior that you would see between an extremely long retry policy and the default policy would only be that your application would be made aware that there was a frequent or persistent issue via the error handler.   The processor would continue to attempt to recover and process messages in either case.

> Also could you please tell me what is the default configuration for the retry mechanism.

 The defaults are:

- Mode: Exponential
- Max Retries:  3
- Delay:  0.8 seconds
- Max Delay:  1 minute
- Try Timeout:  1 minute

Apparently, we're not exposing them in the docs like we should;  I'll get that fixed up. 

> Could you please point to how to register an event source listener to get the errors. 

[This sample](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#logging) talks through the basics of hooking up a listener.

**Comment by jsum04** [comment]
Thanks for all the info jsquire. Just one more thing to clarify. So the retry option is applicable to each individual operation. If the retry fails, it doesn't mean that the consumer will completely stop. Am I correct in saying that. Initially my understanding was a bit different as I thought it would completely stop and that's why I had set the max retry attempts to 100.

**Comment by jsquire** [comment]
> So the retry option is applicable to each individual operation.

Correct.   In this case, an individual operation would be defined as "I'm trying to read messages from the service, but I was unable to do so."

> If the retry fails, it doesn't mean that the consumer will completely stop.

Correct, in the case where a "consumer" is one of the processor types.   The processor will continue to try to recover and keep working.  If an operation fails across all retries, it will fault the task that owns that attempt, that fault will alert the error handler, then the processor will spawn a new task to start over again at the beginning.   This will keep happening until your application stops the processor.

**Comment by jsum04** [comment]
Thanks jsquire for all the info. This definitely helps a lot.
