### ISSUE TITLE
[BUG] Folder structure change for FarmBeats. 

### ISSUE THREAD

**Issue by RGKarthik** [Azure/azure-sdk-for-net#21593]
Can the folder structure for FarmBeats SDK be changed from 'azure-sdk-for-net/sdk/farmbeats' to 'azure-sdk-for-net/sdk/agrifood'.

FarmBeats is a product name and is susceptible to change. Hence, we prefer to use AgriFood.

**Comment by RGKarthik** [comment]
cc: @ramya-rao-a

**Comment by ramya-rao-a** [comment]
@ellismg Please make the above change
