### ISSUE TITLE
Convert DI code sample in Service Bus readme into a snippet 

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-net#21599]
For reference: 

DI section in readme: https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/servicebus/Azure.Messaging.ServiceBus#aspnet-core
PR that adds the DI content https://github.com/Azure/azure-sdk-for-net/pull/21410

**Comment by jsquire** [comment]
Fixed via #37863
