### ISSUE TITLE
[BUG] Service Bus: Unknown error after calling GetNamespaceInfo

### ISSUE THREAD

**Issue by eddynaka** [Azure/azure-sdk-for-net#21629]
**Describe the bug**
When I call `client.GetNamespaceInfoAsync` it is returning an exception. The message shows an "unknown error".

**Expected behavior**
Throw an error that is not unknown or successful.

**Actual behavior (include Exception or Stack Trace)**
Returning unknown error.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. start the clientManagement
2. call GetNamespaceInfoAsync

```
   at Microsoft.Azure.ServiceBus.Management.NamespaceInfoExtensions.ParseFromContent(String xml)
   at Microsoft.Azure.ServiceBus.Management.ManagementClient.<GetNamespaceInfoAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ServiceBus 5.1.3
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8] netstandard2.1, called by netcoreapp3.1
 - IDE and version : [e.g. Visual Studio 16.3] VS16.10

**Comment by jsquire** [comment]
//cc: @shankarsama

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by eddynaka** [comment]
Hi @ramya-rao-a ,

I just changed and now I receive this: `Unknown error. (GeneralError)`

and the inner exception:
```
<feed xmlns="http://www.w3.org/2005/Atom"><title type="text">Publicly Listed Services</title><subtitle type="text">This is the list of publicly-listed services currently available.</subtitle><id>uuid:9f875c19-3997-4acb-838f-5233bc5dff57;id=87</id><updated>2021-10-08T00:34:10Z</updated><generator>Service Bus 1.1</generator></feed>
Status: 200 (OK)

Content:
<feed xmlns="http://www.w3.org/2005/Atom"><title type="text">Publicly Listed Services</title><subtitle type="text">This is the list of publicly-listed services currently available.</subtitle><id>uuid:9f875c19-3997-4acb-838f-5233bc5dff57;id=87</id><updated>2021-10-08T00:34:10Z</updated><generator>Service Bus 1.1</generator></feed>

Headers:
Date: Fri, 08 Oct 2021 00:34:10 GMT
Server: Microsoft-HTTPAPI/2.0
Transfer-Encoding: chunked
Strict-Transport-Security: REDACTED
x-ms-client-request-id: 77693b4a-9b5a-462f-8f29-afe726bbc2f2
Content-Type: application/atom+xml; type=feed; charset=utf-8
```

**Comment by JoshLove-msft** [comment]
Hi @eddynaka,
Can you include a code snippet so we can attempt to reproduce the issue?

**Comment by eddynaka** [comment]
Hi @JoshLove-msft ,

below the snippet:
```csharp
var serviceBusOptions = new ServiceBusAdministrationClientOptions();
serviceBusOptions.Retry.MaxRetries = (retry == bool.TrueString) ? 3 : 0;
var client = new ServiceBusAdministrationClient(serviceBusConnectionString, serviceBusOptions);
NamespaceProperties ni = await client.GetNamespacePropertiesAsync();
```

**Comment by eddynaka** [comment]
Hi @JoshLove-msft , since both use ServiceBus, I was expecting both to work or at least to ServiceBus generate some specific message like "u are using the wrong thing".

Don't know if you have a use case for that, for accepting any kind of SB.

Thanks :)

**Comment by eddynaka** [comment]
HI @JoshLove-msft ,

Below, a connection string from NotificationHub Resource:
```
Endpoint=sb://resource.servicebus.windows.net/;SharedAccessKeyName=DefaultListenSharedAccessSignature;SharedAccessKey=long_key
```

Below, a connection string from a ServiceBus Resource:
```
Endpoint=sb://resource.servicebus.windows.net/;SharedAccessKeyName=DefaultListenSharedAccessSignature;SharedAccessKey=long_key
```

So, I imagined, "hey, both have the same connection string, would that work?"

:)
