### ISSUE TITLE
Why are redundancy comment?

### ISSUE THREAD

**Issue by paul-cheung** [Azure/azure-sdk-for-net#21637]
https://github.com/Azure/azure-sdk-for-net/blob/012db171c60356aedae977e02c5c8951afd9f61b/sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/src/Generated/Models/AzureAsyncOperationResult.cs#L41

I mean why the comment has the comment someting like "**Possible values are**" and "**Possible values include**" meanwhile.

**Comment by jsquire** [comment]
Since this appears in a generated class, the comment is sourced from the service Swagger.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by paul-cheung** [comment]
> Since this appears in a generated class, the comment is sourced from the service Swagger directly and would need to be updated there.

yeah, I think so, it was from Azure service that generated the swagger the SDK team using.
