### ISSUE TITLE
[BUG] Synapse artifact resource serialization does not preserve artifact name

### ISSUE THREAD

**Issue by mikegoatly** [Azure/azure-sdk-for-net#21648]
**Describe the bug**
When serializing an artifact resource, e.g. a `LinkedServiceResource`, the name of the artifact is not emitted in the JSON. (This is likely to affect the other properties on `SubResource`, e.g. etag, id and type.)

**Expected behavior**
I would expect the name property to be emitted to the JSON, preserving the information that was deserialized.

**Actual behavior (include Exception or Stack Trace)**
None of the properties on the base `SubResource` class are written to the JSON.

**To Reproduce**
[.NET Fiddle](https://dotnetfiddle.net/bI4nqW)

``` csharp
using System;
using System.Text.Json;					
using Azure.Analytics.Synapse.Artifacts.Models;

public class Program
{
	public static void Main()
	{
		var linkedService = JsonSerializer.Deserialize<LinkedServiceResource>(@"{
  'name': 'MyKeyVault',
  'properties': {
    'annotations': [],
    'type': 'AzureKeyVault',
    'typeProperties': {
      'baseUrl': 'https://myvault.vault.azure.net/'
    }
  }
}".Replace("'", "\""));
		
		// Outputs MyKeyVault
		Console.WriteLine(linkedService.Name);
		
		var serialized = JsonSerializer.Serialize(linkedService);
		
		// Outputs {"properties":{"type":"AzureKeyVault","annotations":[],"typeProperties":{"baseUrl":"https://myvault.vault.azure.net/"}}}
		Console.WriteLine(serialized);
	}
}
```

**Environment:**
 - Azure.Analytics.Synapse.Artifacts 1.0.0-preview.10

.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

 - Visual Studio 16.10.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by annelo-msft** [comment]
Investigation in progress:

Properties JSON written here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/Models/LinkedServiceResource.Serialization.cs#L21

**Comment by pakrym** [comment]
Are those properties readonly?

**Comment by annelo-msft** [comment]
@pakrym, yes, they are: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v1/types.json#L14

**Comment by pakrym** [comment]
That's why. We don't serialize readonly properties when sending requests.

**Comment by annelo-msft** [comment]
Thanks, @pakrym!  Can you share the thinking behind this?  Is it because, since they're readonly a user can't set them, so we don't send them?  How do we think about this in the context of round-trip models?

**Comment by pakrym** [comment]
>Can you share the thinking behind this? Is it because, since they're readonly a user can't set them, so we don't send them?

The behavior is defined by the spec: 

https://swagger.io/docs/specification/data-models/data-types/ the `Read-Only and Write-Only Properties` sections.

>How do we think about this in the context of round-trip models?

As soon as someone defines a property readonly there is no roundtripping the value. By definition, it can't be changed or removed so omitting is not a problem.

**Comment by annelo-msft** [comment]
Thanks, @pakrym!

@mikegoatly, I'm afraid this is by design.  I'll resolve this issue, but please follow up with us regarding the scenario you're trying to accomplish and we may be able to help you find another approach to do it.

**Comment by mikegoatly** [comment]
Thanks for following up @annelo-msft
