### ISSUE TITLE
Page lacks enough information to explain how methods work

### ISSUE THREAD

**Issue by tgpinq** [Azure/azure-sdk-for-net#21646]
The method here and associated ones appear to be broken. None of the methods return more than 100 Applications and methods that should allow you to get more either can't be used as next-page-links are null or don't work as they simply return null.

Please provide documentation detailing how this method should be used, specifically how it can be used to list all applications in the tenant as this is the purpose of the method. 

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a290f2f9-897e-a11e-28b8-e5e766e16b92
* Version Independent ID: 2497b21c-6497-20e0-8f1c-fbda8860026d
* Content: [ActiveDirectoryApplicationsImpl Class (Microsoft.Azure.Management.Graph.RBAC.Fluent) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.graph.rbac.fluent.activedirectoryapplicationsimpl?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Graph.RBAC.Fluent/ActiveDirectoryApplicationsImpl.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Graph.RBAC.Fluent/ActiveDirectoryApplicationsImpl.xml)
* Service: **role-based-access-control**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Issue moved to [Azure/azure-libraries-for-net #1243](https://github.com/Azure/azure-libraries-for-net/issues/1243) via [**ZenHub**](https://www.zenhub.com/)
