### ISSUE TITLE
Feature Request - Batch Encrypt/Decrypt operation in keyvault

### ISSUE THREAD

**Issue by krish-gh** [Azure/azure-sdk-for-net#2166]
We have a requirement for a customer where in course of a data processing flow, we need to encrypt/decrypt a list of items (let's say 100 in a batch) individually. Now if we do that from client side sending multiple requests to keyvault, there is a throttling from keyvault and also network latency. So, we need something for bulk operation at one shot. Let's say if the API can accept and array of key operation input and return an array of key operation result.

**Comment by pomortaz** [comment]
@krish-gh batch operations are not supported by Key Vault service as of now. To bypass the issue, you can send the requests at the same time to key vault and if throttled, you need to back off and wait for few seconds. Here is the [throttling limit for Key Vault](https://azure.microsoft.com/en-us/documentation/articles/key-vault-service-limits/). Does it work for you?

**Comment by pomortaz** [comment]
We are adding your request to the requested features to review. :) There is no plan to support it yet.
