### ISSUE TITLE
Garbage collection for deletion is handled on the server side?

### ISSUE THREAD

**Issue by Kandhan-Sekar** [Azure/azure-sdk-for-net#21673]
[Enter feedback here]
When deleteasync is called on a file/ folder, the path is marked for deletion. But does this depend on the client for garbage collection? as in if the client crashes down the line will it end up not cleaning it up or is it done on the server side by adls on a separate thread?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 648562f1-4bc4-97c6-303e-8793ad4b7bf7
* Version Independent ID: f1db63f3-e097-fb7f-08ec-8c0993979c5c
* Content: [DataLakeFileClient.DeleteAsync(DataLakeRequestConditions, CancellationToken) Method (Azure.Storage.Files.DataLake) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakefileclient.deleteasync?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Files.DataLake/DataLakeFileClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.DataLake/DataLakeFileClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@Kandhan-Sekar Apologies for the late reply. The [DeleteAsync(DataLakeRequestConditions, CancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakefileclient.deleteasync?view=azure-dotnet#azure-storage-files-datalake-datalakefileclient-deleteasync(azure-storage-files-datalake-models-datalakerequestconditions-system-threading-cancellationtoken)) operation marks the specified path deletion. The path is later deleted during garbage collection which could take several minutes. 

>After the storage account or blob container is deleted, it is queued to be recycled and collected by the garbage collector. The system can then free up space for reuse. The deleted storage account or blob container may be restored if the garbage collector has not yet run and the storage space is not yet cleaned up. This is handled by the Storage service in the background. 
The time at which the garbage collector is run varies depending on many factors, such as workloads on the storage scale unit, the number of available storage spaces, and so on. On average, the garbage collection of storage accounts occurs 14 days after deletion. Typically the data is unrecoverable by Microsoft. It is recommended to enabled soft delete for blobs that allow you to recover blob data after it has been deleted. 

Refer: https://docs.microsoft.com/en-us/troubleshoot/azure/general/data-restore-storage

Please let me know if you have any further queries on this.
