### ISSUE TITLE
[BUG] ServiceBus: Closing SubscriptionClient Instance results in CanceledException [Mono] or Hanging  [.NET Core]

### ISSUE THREAD

**Issue by taabdull** [Azure/azure-sdk-for-net#21672]
**Describe the bug**
Copied from https://github.com/Azure/azure-sdk-for-net/issues/18980
This issue is happening in both Azure.Messaging.ServiceBus and Microsoft.Azure.ServiceBus. However the .NET Core repro only happens for Azure.Messaging.ServiceBus. When closing the subscription client it throws an exception.

**Expected behavior**
What is the expected behavior? 
No Exception

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
OperationCanceledException in Mono Runtime
Hanging in .NET Core

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
```
if not (subscriptionClient.IsClosedOrClosing) then
    do! subscriptionClient.CloseAsync() |> Async.AwaitTask // THROWS EXCEPTION
```

See code snippets in original Bug:  https://github.com/Azure/azure-sdk-for-net/issues/18980#issuecomment-823167705
Customer provided proj with repro:
https://github.com/bizmonger/GitHub_Bug_18980

**Environment:**
- Azure.Messaging.ServiceBus 7.1.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
This was discussed offline and the issue was a deadlock in the code stemming from awaiting the StopProcessing call from the user message handler.
