### ISSUE TITLE
Azure Search Ranking

### ISSUE THREAD

**Issue by harsh288** [Azure/azure-sdk-for-net#2168]
Hi,

My application is in MVC and I have a search text box based on azure index, its working fine however I have a scenario where in if I enter "chres Harris" instead of "chris Harris" it should return result "chris Harris" but it returns different result like "bob Harris" and then "chris harris", I want the results to be nearabout the same even if there is a spell mistake, please help will any index scoring profile, parameter boost or something useful ?

**Comment by brjohnstmsft** [comment]
Hi @harsh288,

This issue is not specific to the .NET SDK, so I'm going to close it. Please start a new thread on the Azure Search MSDN forum and I'll make sure the right person on our team helps you out:

https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=azuresearch

Thanks,

-Bruce

**Comment by harsh288** [comment]
Sure thanks !!
