### ISSUE TITLE
[BUG] In fluent networking models, Direction and SecurityRuleDirection should be the same type

### ISSUE THREAD

**Issue by paulmey** [Azure/azure-sdk-for-net#21691]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1740197/121190172-12f47a80-c86b-11eb-8983-989a6d32e39f.png)
Both types define the same members and serve the same purpose.

**Expected behavior**
They should be the same type.

**Actual behavior (include Exception or Stack Trace)**
They are two different types, frustrating the users of the SDK.

**To Reproduce**
Try to code adding an NSG rule...

The only difference between these files is the type name:
https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Network/Generated/Models/SecurityRuleDirection.cs
https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Network/Generated/Models/Direction.cs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you help on this? thanks

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!
