### ISSUE TITLE
[BUG] DefaultAzureCredential doesn't work with IIS environment variables

### ISSUE THREAD

**Issue by AndyMcKenna** [Azure/azure-sdk-for-net#21706]
**Describe the bug**
`EnvironmentCredential` doesn't get the necessary values if they are stored in IIS environment variables.  It only works when we create OS level environment variables.  This is when using `DefaultAzureCredential` to authenticate against KeyVault.

**Expected behavior**
IIS environment variables and OS env vars would both work

**Actual behavior (include Exception or Stack Trace)**
```
Unhandled Exception: Azure.Identity.CredentialUnavailableException: DefaultAzureCredential failed to retrieve a token from the included credentials.
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
- ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource.
Status: 400 (Bad Request)
Content:
{"error":"invalid_request","error_description":"Identity not found"}
Headers:
Server: IMDS/150.870.65.511
Date: Tue, 08 Jun 2021 13:56:20 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 68 
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Aspnet Core 2.1 application, connecting to KeyVault in program.cs like:
```
var secretClient = new SecretClient(new Uri($"https://{builtConfig["KeyVault:VaultName"]}.vault.azure.net/"), new DefaultAzureCredential());
config.AddAzureKeyVault(secretClient, new PrefixKeyVaultSecretManager(prefix));
```
2. Environment variables added in IIS to the app pool, saved in applicationHost.config:
![image](https://user-images.githubusercontent.com/29063167/121238312-f6097880-c865-11eb-92d8-dc90c1551727.png)
3.  Application crashes at startup because the KeyVault call is unauthenticated
4. Switch the environment variables to the OS, restart IIS and it all works.

**Environment:**
 - Name and version of the Library package used: Azure.Identity 1.3.0, Azure.Extensions.AspNetCore.Configuration.Secrets 1.0.2
 - Hosting platform or OS and .NET runtime version: 
 Host (useful for support):
  Version: 2.1.18
  Commit:  ba3b934aa4

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

 - IDE and version : Visual Studio 16.9.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @AndyMcKenna From what I can tell from the IIS documentation, those variables should be passed to the worker process, which would make them available to `Azure.Identity`'s call to `Environment.GetEnvironmentVariable`

However, looking at your screen shot, I noticed that one of the variables has the wrong casing for the first letter. Does it work if you change that to "AZURE_TENANT_ID"?

![image](https://user-images.githubusercontent.com/1279263/121745955-b8f1f000-caca-11eb-811b-4cbb83b3fec0.png)

**Comment by AndyMcKenna** [comment]
I tried fixing the lowercase "a" and that didn't work and then I noticed it's spelled TEN**T**ANT there  🤦‍♂️.  Corrected that, reset the app pool and then everything starts up successfully.
