### ISSUE TITLE
Proxy with HttpClientHandler to WebSiteManagementClient - gives object reference exception from the Azure SDK

### ISSUE THREAD

**Issue by rajeshkdev** [Azure/azure-sdk-for-net#2172]
Proxy with HttpClientHandler to WebSiteManagementClient - gives object reference exception from the Azure SDK.        

```
            HttpClientHandler clientHandler = new HttpClientHandler()
            {
                Proxy = AzureADManager.GetWebProxy(proxySettings)
            };
            client = new WebSiteManagementClient(credentials, new HttpClient(clientHandler)); // Error occurs
```

When we pass this "new HttpClient(clientHandler)" to WebSiteManagementClient, getting object reference exception from the Azure SDK. 

How to handle this? or Any Hot fix available?

Is this issue from Azure SDK?

**Comment by shahabhijeet** [comment]
@rajeshkdev could you start using latest Microsoft.Azure.Management.Websites package.
Please file an issue if you have any issues with that package.
