### ISSUE TITLE
[BUG]Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0-beta.5 will make unit test start failed.

### ISSUE THREAD

**Issue by yunair** [Azure/azure-sdk-for-net#21723]
**Describe the bug**
If I add Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0-beta.5 to project, I can't run unit test for my project.

**Expected behavior**
I can run unit test success.

**Actual behavior (include Exception or Stack Trace)**
I can't run the unit test, and in test outputs, it said: 
![image](https://user-images.githubusercontent.com/4322540/121286072-e8a9c800-c911-11eb-9102-f3613389105f.png)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. add this to a project
2. create unit test for that project.

**Environment:**
 - Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0-beta.5
 - Windows 10 .NETCore 3.1
 - Visual Studio 16.10

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @yunair,
Can you include more information on what specific unit tests you are trying to run?

**Comment by yunair** [comment]
I can't repro this in demo, so close this.
