### ISSUE TITLE
Migration guide link not pointing to the most updated guide

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-net#21733]
The migration guide link needs to be updated:

current link: https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.2.0-beta.3/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md

correct link with most updated guide: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 502cdc58-1a24-406f-878d-6ef61304b844
* Version Independent ID: 7a8b44e7-ae5c-6c25-6a3d-5cb8eb30c17e
* Content: [Azure Service Bus client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/messaging.servicebus-readme-pre)
* Content Source: [api/overview/azure/messaging.servicebus-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/messaging.servicebus-readme-pre.md)
* Service: **servicebus**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by lilyjma** [comment]
(not sure why the font size is weird..)

**Comment by jsquire** [comment]
This is normal and expected; the pre-release version of the README generates locked to the tag that it was released from.
