### ISSUE TITLE
Using SDK for Elastic Db Pool operations?

### ISSUE THREAD

**Issue by shaulbehr** [Azure/azure-sdk-for-net#2174]
Hi,
I just found this library, and I've cloned it locally.
I'm trying to find how to do operations on Elastic Db pools, specifically how to create a pool, and how to create a database within that pool.
I couldn't find any documentation or sample code for this, and the package version I'm using in my project (Microsoft.WindowsAzure.Management.Libraries 2.0.0, which is the latest according to NuGet) seems to be very much out of sync with the master branch of this project, e.g. namespaces start with Microsoft.WindowsAzure rather than Microsoft.Azure.
In the master branch here, there's an ElasticPools property of the SqlManagementClient that isn't available in the NuGet package.
Am I doing something wrong?  Where can I find the interfaces I need in the NuGet package?

TIA for your help

**Comment by akromm** [comment]
@shaulbehr I just noticed this!  I need to update my email filters.

The [Microsoft.WindowsAzure.Management.Sql library ](https://www.nuget.org/packages/Microsoft.WindowsAzure.Management.Sql/) contains the older set of APIs.  The [Microsoft.Azure.Managment.Sql library](https://www.nuget.org/packages/Microsoft.Azure.Management.Sql/) contains the new APIs.  You need to use the newer API to get access to things like Elastic Pools.
