### ISSUE TITLE
BlobTrigger - User ManagedIdentity - "Unable to find matching constructor"

### ISSUE THREAD

**Issue by sescandell** [Azure/azure-sdk-for-net#21753]
Hello,

I'm trying to deploy a .NetCore Azure Function where the trigger is a BlobTrigger using a User Managed Identity (thanks to the early preview feature).

Here is my code:
```csharp
[FunctionName("MyFunction")]
public async Task Run(
    [BlobTrigger("import/{name}", Connection = "StorageAccountCS")]string fileContent,
    string name,
    ILogger log
)
{
    log.LogInformation($"C# Blob Trigger function executed for {name} at: {DateTime.Now}");
}
```

Here is the local.settings.json used:
```json
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "UseDevelopmentStorage=true",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet",
        "StorageAccountCS__serviceUri": "https://myblobaccount.blob.core.windows.net",
    }
}
```

Locally, connected through the Azure CLI: everything is working fine.

Matters comes once on Azure.
Here is the configuration used:

```json
[
  {
    "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
    "value": "AI-KEYa",
    "slotSetting": false
  },
  {
    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
    "value": "AI-KEY",
    "slotSetting": false
  },
  {
    "name": "AZURE_CLIENT_ID",
    "value": "USER IDENTITY ID",
    "slotSetting": false
  },
  {
    "name": "AzureServicesAuthConnectionString",
    "value": "RunAs=App;AppId=USER IDENTITY ID",
    "slotSetting": false
  },
  {
    "name": "AzureWebJobsStorage__accountName",
    "value": "ACCOUNT",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_EXTENSION_VERSION",
    "value": "~3",
    "slotSetting": false
  },
  {
    "name": "FUNCTIONS_WORKER_RUNTIME",
    "value": "dotnet",
    "slotSetting": false
  },
  {
    "name": "InstrumentationKey",
    "value": "AI-KEY",
    "slotSetting": false
  },
  {
    "name": "StorageAccountCS__serviceUri",
    "value": "https://ACCOUNT.blob.core.windows.net",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
    "value": "DefaultEndpointsProtocol=https;AccountName=ACCOUNT;AccountKey=KEY;EndpointSuffix=core.windows.net",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_CONTENTSHARE",
    "value": "CONTENTSHARE-VALUE",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_ENABLE_SYNC_UPDATE_SITE",
    "value": "true",
    "slotSetting": false
  },
  {
    "name": "WEBSITE_RUN_FROM_PACKAGE",
    "value": "1",
    "slotSetting": false
  }
]
```

But on execution, I got the following error:

> The 'MyFunction' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'MyFunction'. Microsoft.Extensions.Azure: Unable to find matching constructor. Define one of the follow sets of configuration parameters:
> 1. connectionString 
> 2. serviceUri
> 3. serviceUri, credential
> 4. serviceUri, credential
> 5. serviceUri, credential
> . 

I also tried, as mentionned in [this blog post](https://devblogs.microsoft.com/azure-sdk/introducing-the-new-azure-function-extension-libraries-beta/), to add the following config:

```json
{
    "name": "StorageAccountCS__blobServiceUri",
    "value": "https://ACCOUNT.blob.core.windows.net",
    "slotSetting": false
  },
```

But i'm still getting the same issue.

Just as an aditionnal info: I also have a `Blob` Binding using the same logic, and it's working as expected. I only encounter issues with the `BlobTrigger` Binding.

```csharp
[FunctionName("OtherFunction")]
public Task Run(
    [TimerTrigger("0 15 5,7,10,13,16,18 * * *", RunOnStartup = true)]TimerInfo myTimer,
    [Blob("import/{DateTime}.xml", FileAccess.Write, Connection = "StorageAccountCS")]Stream output,
    ILogger log
)
// everything is working here
```

**Environment:**

 Here is the csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0-beta.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.13" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
    <PackageReference Include="SSH.NET" Version="2020.0.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>

```

**Comment by kasobol-msft** [comment]
I was able to reproduce the issue with 5.0.0-beta.3 version (as posted). The stacktrace isn't related to `StorageAccountCS` connection but rather to `AzureWebJobsStorage`. It seems that it can't derive right configuration from `AzureWebJobsStorage__accountName`.

The relevant piece of logic seems to be [here](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.WebJobs.Extensions.Storage_5.0.0-beta.3/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/src/Shared/StorageClientProvider.cs#L72), [here](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.WebJobs.Extensions.Storage_5.0.0-beta.3/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/src/Shared/StorageClientProvider.cs#L44) and [here](https://github.com/Azure/azure-sdk-for-net/blob/Microsoft.Azure.WebJobs.Extensions.Storage_5.0.0-beta.3/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/src/Shared/StorageClientProvider.cs#L58).

![image](https://user-images.githubusercontent.com/61715331/121932829-2d5ea600-ccfa-11eb-945d-e873475671ab.png)

Opened https://github.com/Azure/azure-sdk-for-net/issues/21850 to improve logging.

FWIW. The connection format has evolved a bit. See https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/CHANGELOG.md . So, I'd recommend to try 5.0.0-beta.4 which aligns with [the article](https://devblogs.microsoft.com/azure-sdk/introducing-the-new-azure-function-extension-libraries-beta/) .

I'll post another update with configuration that's working.

**Comment by kasobol-msft** [comment]
@sescandell Updating extension to `5.0.0-beta.4` seems to be solving this problem. (Even without updating configs...)

Please keep in mind that BlobTrigger depends on queues therefore recommended config is:
```
StorageAccountCS__blobServiceUri=https://ACCOUNT.blob.core.windows.net
StorageAccountCS__queueServiceUri=https://ACCOUNT.queue.core.windows.net
```
OR
```
StorageAccountCS__accountName=ACCOUNT
```

Please let us know if this resolves the issue.

**Comment by sescandell** [comment]
> @sescandell Updating extension to `5.0.0-beta.4` seems to be solving this problem. (Even without updating configs...)
> 
> Please keep in mind that BlobTrigger depends on queues therefore recommended config is:
> 
> ```
> StorageAccountCS__blobServiceUri=https://ACCOUNT.blob.core.windows.net
> StorageAccountCS__queueServiceUri=https://ACCOUNT.queue.core.windows.net
> ```
> 
> OR
> 
> ```
> StorageAccountCS__accountName=ACCOUNT
> ```
> 
> Please let us know if this resolves the issue.

Hi,

I tried version beta4... but I didn't put the queueServiceUri... I'll test again and let you know.

Thanks,

**Comment by sescandell** [comment]
@kasobol-msft I updated to the beta.4 with __accountName suffix and it works! Thanks.

Any insights on which roles my Managed Identity should have on the targeted storage.
Because internally it's using Queues, I imagine I need to add Storage Blob Data Contributor and Storage Queue Data Contributor.
But I'm also using the Manage Identity for the AzureWebJobsStorage. Is there any additional role required?

I firstly tested with full contributor role... I can try with less of them.

And, finally, is there any way / plan to use Managed Identity for the configuration key `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` ?

Thanks for your help,

**Comment by kasobol-msft** [comment]
@sescandell Please take a look at [this page](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#configure-an-identity-based-connection), especially at [connecting to host storage with an identity](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference#connecting-to-host-storage-with-an-identity) section which talks about `AzureWebJobsStorage`. 
For blob trigger the Storage Blob Data Contributor and Storage Queue Data Contributor should be enough. I'd recommend to follow principle of least privilege and grant only necessary access. This may require additional effort on your side and depends on how are you using storage (i.e. if by any chance you're binding to `QueueClient` or `BlobClient` and using Storage SDK APIs directly you may require some additional roles).

For the WEBSITE_CONTENTAZUREFILECONNECTIONSTRING please follow https://github.com/Azure/azure-functions-host/issues/6423 .

**Comment by sescandell** [comment]
@kasobol-msft Thanks ;)

**Comment by kasobol-msft** [comment]
> > @sescandell Updating extension to `5.0.0-beta.4` seems to be solving this problem. (Even without updating configs...)
> > Please keep in mind that BlobTrigger depends on queues therefore recommended config is:
> > ```
> > StorageAccountCS__blobServiceUri=https://ACCOUNT.blob.core.windows.net
> > StorageAccountCS__queueServiceUri=https://ACCOUNT.queue.core.windows.net
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > OR
> > ```
> > StorageAccountCS__accountName=ACCOUNT
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Please let us know if this resolves the issue.
> 
> Hi,
> 
> I tried version beta4... but I didn't put the queueServiceUri... I'll test again and let you know.
> 
> Thanks,

@sescandell I recall now that `BlobTrigger` uses `AzureWebJobsStorage` for internal queues regardless of which `Connection` is used, so `StorageAccountCS` can have only blobs uri.
