### ISSUE TITLE
Searching a recommendation to which Azure Service bus package to install

### ISSUE THREAD

**Issue by OmerNassie** [Azure/azure-sdk-for-net#21772]
**Query/Question**
Hi there!
We're the infrastructure team in the company and we built our infrastructure using the Microsoft.Azure.ServiceBus package of yours which last maintained in April,
I see all your documentation examples for Azure service bus are using the Azure.Messaging.ServiceBus package 
which also last maintained in April this year.

I wonder which package are you maintaining from them and of course, which package should we use? 
Do you recommend to plan a migration to the Azure.Messaging.ServiceBus package or to stay for now with the package we already integrated?

**Comment by jsquire** [comment]
Hi @OmerNassie.   For new development, we would recommend using the `Azure.Messaging.ServiceBus` package and the `Azure.[[ AREA ]].[[ SERVICE ]]` packages for other services.   

For a scenario like you describe with an existing investment in the `Microsoft.Azure.ServiceBus` package, there's no risk of abandonment or other forcing function that would require an immediate change.  The `Microsoft.Azure.ServiceBus` package will continue to be supported with receive bug fixes and critical updates for the foreseeable future; unfortunately, I don't have definitive timeline to share, but it's safe to say that it is most likely measured in years.  

As you're making your decision, one criteria to be aware of is that in the more near-term future, `Microsoft.Azure.Service` will stop receiving the new features and enhancements that are being added to the `Azure.Messaging.ServiceBus` package.  Again, I don't have a definitive timeline for when that will be.

**Comment by OmerNassie** [comment]
Thank you for the quick and informative reply! You helped me a lot
