### ISSUE TITLE
[QUERY] How to check if blob versioning is enabled for a storage account?

### ISSUE THREAD

**Issue by tigertechdev** [Azure/azure-sdk-for-net#21774]
**Query/Question**
We've been using Azure.Storage.Blobs to manage customers' data using connection string with account name and key.
Now we need to know if blob versioning is enabled. We've looked at the following options:

* BlobServiceClient.GetProperties() - unfortunately it has information about soft delete but not versioning.
* StorageManagementClient.StorageAccounts.GetProperties (from Microsoft.Azure.Management.Storage) - this would work if I could authenticate with account name and key but it seems this isn't possible.
* The newer Azure.ResourceManager.Storage seems to have the same problem.
* We could upload a test blob and check if the response contains a version id but this not ideal.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.0, Microsoft.Azure.Management.Storage 22.0.0
 - Hosting platform or OS and .NET runtime version Windows 10, .NET Framework 4.6.1

EDIT: Having a way to enable versioning would be ideal but we can live with just checking and directing users to enable it manually.

**Comment by amishra-dev** [comment]
@tigertechdev is the ask to add support to Azure.Storage.Blobs sdk's BlobServiceClient.GetProperties API to return versioning information?

**Comment by tigertechdev** [comment]
@amishra-dev It already returns soft delete information. It would be great if it can return information about versioning too.
If that's not possible, I'd like to know how to get it with account name and key.

**Comment by amnguye** [comment]
I believe this is a management plane API ask not an SDK ask. We can only implement what the service provides.

@blueww Do you know if this is something the service has thought of returning when doing get storage properties
https://docs.microsoft.com/en-us/rest/api/storagerp/srp_json_get_storage_account_properties

**Comment by blueww** [comment]
You can use  storageMgmtClient.BlobServices.GetServiceProperties()
See detail in test case: https://github.com/Azure/azure-sdk-for-net/blob/d38779fa437c2cdad251463f01039119439c2703/sdk/storage/Microsoft.Azure.Management.Storage/tests/Tests/BlobServiceTests.cs#L817
