### ISSUE TITLE
[FEATURE REQ] - Ability to do a WhatIF deployment in the Fluent SDK?

### ISSUE THREAD

**Issue by 1RedOne** [Azure/azure-sdk-for-net#21786]
Hi, we are looking to use the Azure.Management.Fluent SDK and wondered if there is a supported method to do a WhatIf deployment using IAzure.   I know that WhatIf deployments only became GA back in December, so just checking to see if that's on the road map!

What library or service is this request related to? [Azure.Deployments] 
 
**Is your feature request related to a problem? Please describe.**
What if Deployments are relatively new and presently supported in Azure.ResourceManager, but they don't seem to be available in Azure Fluent SDK yet.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
hi @1RedOne thanks for reporting the issue. For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!
