### ISSUE TITLE
Convert AutoRest projects to CoreCLR

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-sdk-for-net#2178]
List of Projects that could be converted:
```
~~ Microsoft.Azure.Management.Intune (We are not shipping this library) ~~ 
Microsoft.Azure.Management.ServerManagement
Microsoft.Azure.Management.Logic
Microsoft.Azure.Management.Scheduler
```

Need to notify partners that we will convert their libraries and publish to nuget.org new version with patch version bump. 

Ask partner teams to convert during this release first.

**Comment by cormacpayne** [comment]
Logic conversion in PR https://github.com/Azure/azure-sdk-for-net/pull/2200
Scheduler conversion in PR https://github.com/Azure/azure-sdk-for-net/pull/2236
ServerManagement conversion in PR https://github.com/Azure/azure-sdk-for-net/pull/2238
