### ISSUE TITLE
HealthcareEntityCategories are in uppercase in swagger and service returns Pascal case

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#21796]
Input: "Baby not likely to have Meningitis. in case of fever in the mother, consider Penicillin for the baby too.",

Output:
"jobId": "28fe5c99-7cc7-4734-907b-285272bdab23",
    "lastUpdateDateTime": "2021-06-10T20:16:41Z",
    "createdDateTime": "2021-06-10T20:16:30Z",
    "expirationDateTime": "2021-06-11T20:16:30Z",
    "status": "succeeded",
    "errors": [],
    "results": {
        "documents": [
            {
                "id": "1",
                "entities": [
                    {
                        "offset": 0,
                        "length": 4,
                        "text": "Baby",
                        "category": "Age",
                        "confidenceScore": 0.94,
                        "name": "Infant",
...

**Comment by maririos** [comment]
https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/10123708

**Comment by joseharriaga** [comment]
The service team has changed the values in the swagger spec to PascalCase, thus aligning with what is returned by the server:
https://github.com/Azure/azure-rest-api-specs/blob/338ccc7bfc79689760959765543387e58b0e4855/specification/cognitiveservices/data-plane/TextAnalytics/stable/v3.1/TextAnalytics.json#L1884

I will prepare a small PR to add back the test that was mark as ignored.
