### ISSUE TITLE
Pii task with PHI doesn't return taskName

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#21802]
Input: 
{
    "analysisInput": {
        "documents": [
            {
                "id": "1",
                "text": "A patient with medical id 12345678 whose phone number is 800-102-1100 is going under heart surgery",
                "language": "en"
            }
        ]
    },
    "tasks": {
        "entityRecognitionPiiTasks": [
            {
                "parameters": {
                    "domain":"phi"
                }
            }
        ]
    }
}

Output:
{
    "jobId": "c3b98cb5-ec5d-43ab-a099-e4404a5f4eae",
    "lastUpdateDateTime": "2021-06-10T21:51:36Z",
    "createdDateTime": "2021-06-10T21:51:21Z",
    "expirationDateTime": "2021-06-11T21:51:21Z",
    "status": "succeeded",
    "errors": [],
    "displayName": "NA",
    "tasks": {
        "completed": 1,
        "failed": 0,
        "inProgress": 0,
        "total": 1,
        "entityRecognitionPiiTasks": [
            {
                "lastUpdateDateTime": "2021-06-10T21:51:36.8465993Z",
                "state": "succeeded",
                "results": {
                    "documents": [
                        {
                            "redactedText": "A patient with medical id ******** whose phone number is ************ is going under heart surgery",
                            "id": "1",
                            "entities": [
                                {
                                    "text": "12345678",
                                    "category": "PhoneNumber",
                                    "offset": 26,
                                    "length": 8,
                                    "confidenceScore": 0.8
                                },
                                {
                                    "text": "800-102-1100",
                                    "category": "PhoneNumber",
                                    "offset": 57,
                                    "length": 12,
                                    "confidenceScore": 0.8
                                }
                            ],
                            "warnings": []
                        }
                    ],
                    "errors": [],
                    "modelVersion": "2021-01-15"
                }
            }
        ]
    }
}

**Comment by maririos** [comment]
https://msazure.visualstudio.com/Cognitive%20Services/_workitems/edit/10123739

**Comment by maririos** [comment]
This is still an issue. For now we are making TaskName not required so our SDK doesn't fail. Will move to backlog until service fixes it

**Comment by maririos** [comment]
This is still happening so I just pinged the service issue

**Comment by pallavit** [comment]
@joseharriaga can you please check if this is still an issue
