### ISSUE TITLE
'List supported node agent SKUs' operation

### ISSUE THREAD

**Issue by sarbohan** [Azure/azure-sdk-for-net#21844]
What is "'List supported node agent SKUs' operation" ? Shouldn't it be a link? If not, there is absolutely missing information about how to get the value. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c2622a3-e643-ba97-cdaf-018dc70cf147
* Version Independent ID: 217b0272-aece-6a64-9268-a1e7817600fa
* Content: [VirtualMachineConfiguration.NodeAgentSkuId Property (Microsoft.Azure.Management.Batch.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.batch.models.virtualmachineconfiguration.nodeagentskuid?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Batch.Models/VirtualMachineConfiguration.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Batch.Models/VirtualMachineConfiguration.xml)
* Service: **batch**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
@allenjzhang:  This looks to be sourced from the service swagger, so I've routed it with that understanding.   If I'm mistaken, please feel free to adjust as needed.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by navba-MSFT** [comment]
@sarbohan Apologies for the late reply. Thanks for sharing the feedback. The above PR has been filed and it is currently under review phase. In the meantime if you have any queries, please feel free to ask. Awaiting your reply.

**Comment by paterasMSFT** [comment]
Apologies for the delay. The solution in the linked PR will not work, but we will put a fix out in our next release.

**Comment by navba-MSFT** [comment]
Thanks @paterasMSFT
