### ISSUE TITLE
How can I create a cosmosDB database account with Gremlin APIs enabled

### ISSUE THREAD

**Issue by malviyanshiv** [Azure/azure-sdk-for-net#21843]
**Query/Question**
How can we help?
I was trying to create a database account with Gremlin APIs enabled using the **StartCreateOrUpdateAsync** function of DatabaseAccountsOperations. These are part of **Azure.ResourceManager.CosmosDB**. After going through some examples I got to know the I need to set the **Capabilities** parameter of **DatabaseAccountCreateUpdateParameters** something like

```csharp
var createUpdateParameters = new DatabaseAccountCreateUpdateParameters
{
    Location = dBAccountLocation,
    Locations = locations,
    Capabilities = new List<Capability>() {new Capability {Name = "EnableGremlin" }},
};
```
But there is no constructor supporting this operation and Capabilities is a read-only attribute. Is there another way to achieve the same?
**Environment:**
 - Azure.ResourceManager.CosmosDB -Version 1.0.0-preview.1
 - Runtime Environment:
     OS Name:     Windows
     OS Version:  10.0.19043
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\5.0.204\
 - IDE and version : Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by MehaKaushik** [comment]
Hey @malviyanshiv Can you please follow the example here: https://github.com/markjbrown/cosmos-management-net/blob/master/cosmos-management-generated/Program.cs
This does what you want to do.

Let me know if this doesn't help.

**Comment by malviyanshiv** [comment]
Thanks @MehaKaushik , 
Can we achieve the same by using [Azure.ResourceManager.CosmosDB](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.ResourceManager.CosmosDB/1.0.0-preview.1/api/index.html) . 
We are already using **Azure.ResourceManager.*** management client libraries for managing other resources. I was taking reference from here: https://github.com/Azure-Samples/cosmos-management-net/blob/de4333b83bb385ac9c94718bdd24451ce457aca0/cosmos-management-generated/DatabaseAccount.cs But it seems, the **DatabaseAccountCreateUpdateParameters** defined under **Azure.ResourceManager.CosmosDB** doesn't have a constructor to set the **Capabilities** parameter. Can you please help me with that?

**Comment by MehaKaushik** [comment]
@allenjzhang would be able to help you with Azure.ResourceManager.*

**Comment by MehaKaushik** [comment]
Hey @malviyanshiv, I was looking at the tests, you can also do like this:             

https://github.com/Azure/azure-sdk-for-net/blob/1911ff236e2c539c142405e02e3199ab7a9a986d/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/tests/ScenarioTests/CassandraResourcesOperationsTests.cs#L66

Let me know if this doesn't work.
