### ISSUE TITLE
Does DataFactoryManagementClient use a shared HttpClient?

### ISSUE THREAD

**Issue by stevendarby** [Azure/azure-sdk-for-net#21868]
Does DataFactoryManagementClient use a shared HttpClient?

[This article](https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/#clients-are-not-disposable-shared-httpclient-as-default) suggests it does ("All Azure SDK clients, by default, use a single shared HttpClient instance"), however, looking at the source code it appears to instantiate a new HttpClient and handler if one isn't passed in. The client is also disposable and disposes the HttpClient.

I'm also looking for some general advice about managing the number of concurrent requests, which ties in with this question.

I have an app which makes multiple concurrent requests using the DataFactoryManagementClient- request tasks are begun and awaited as a group. When there are hundreds of requests it sometimes fails with a 21s timeout and this exception message:

> A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 

I am looking to limit the number of concurrent requests so as not to overload the server with connections. I can do this by manually batching the requests, but was looking at other options built into the client. That's when I came across the fact I can pass my own HttpClient to the DFM client, and could set the MaxConnectionsPerServer option on the underlying handler.

This made me question whether I can further reduce the number of connections over the lifetime of the app by using a single HttpClient shared among multiple DFM clients (I have a need to create multiple, for different subscriptions). This is when I came across the documentation suggesting this is what happens anyway, but I'm not too sure that is the case. What is the best way to approach this problem?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by stevendarby** [comment]
Adding some more info / findings in case it's useful.

I confirmed with netstat that creating DataFactoryManagementClients without passing in my own HttpClient led to a lot of connections. e.g. I used one client to make 100 concurrent requests and this led to 100 connections: OK. Shortly after, repeated the requests with a new client: this opened another 100 connections, leading to 200 in total. Repeating this over and over could easily exhaust sockets.

So instead, I'm now creating an HttpClient using IHttpClientFactory (which ensures the underlying handler which manages the connections is not disposed, instead it's reused among new instances of the HttpClient) and creating DataFactoryManagementClients using that. Now the connection count doesn't grow over time; existing connections from previous requests are reused for subsequent requests that follow shortly after.

Based on the documentation linked in the first post, I had expected DataFactoryManagementClient would manage something like this itself internally, e.g. using a shared HttpClient instance. However, my workaround works for me as I also want to configure the HttpClient a bit more anyway.

(For example, I can configure the maximum number of connections when configuring the client created by IHttpClientFactory in the service collection setup, with something like the below)

```C#
services 
    .AddHttpClient(nameof(DataFactoryManagementClient))
    .ConfigurePrimaryHttpMessageHandler(sp => new HttpClientHandler {MaxConnectionsPerServer = 50});
```

**Comment by shawnxzq** [comment]
@stevendarby It depends on how you create the DataFactoryManagementClient instance, if you don't pass the HttpClient instance in, then it will create one, then each DataFactoryManagementClient instance will has a dedicate HttpClient instance. If you pass your HttpClient instance when creating DataFactoryManagementClient instance, you have the control whether have it disposed together with the DataFactoryManagementClient instance, if not,  then you can also pass the same HttpClient instance to multiple DataFactoryManagementClient  instances.  In general, you have all of the controls on whether share the HttpClient instance or not.  

@jsquire This is a general Azure SDK practice and it's all managed by SDK in generated code, not specific to data factory, I would expect SDK team can answer this kind of question directly, thanks!

**Comment by jsquire** [comment]
@shawnxzq:  Please be advised that my contribution here is simply first triage.   If it isn't apparent if there are customizations in a library that may have influenced core behavior, we'll route to the library owner for a more thorough triage.   Please feel free to re-tag and route if you believe there is another owner better suited to assist.

**Comment by shawnxzq** [comment]
@stevendarby I don't have the details on the other client as I work on ADF only, but what we discussed for the DataFactoryManagementClient is correct. And if you want to know more details on the other clients, suggest you can check the source code directly: https://github.com/Azure/azure-sdk-for-net

**Comment by shawnxzq** [comment]
@stevendarby  Any more issues on this? If not, we will try to close this issue later, thanks!

**Comment by shawnxzq** [comment]
Answered question and close the issue.
