### ISSUE TITLE
[QUERY] Any recommend way to handle Eventhub Checkpoint file change during migration to sdk v5？

### ISSUE THREAD

**Issue by RetYn** [Azure/azure-sdk-for-net#21867]
**Query/Question**
Eventhub Checkpoint saved style changes during migration to sdk v5. Checkpoint is stored in metadata in new SDK while the old one is stored just in file.
Does any code tools or client option I can use to help the migration process ? 
Or I just need to create the checkpoint file manually myself if I do not want to redo the message?
https://github.com/Azure/azure-sdk-for-net/issues/17474 I found this issue, has it be done?

**Comment by jsquire** [comment]
Hi @RetYn.   Thank you for reaching out and we regret that you're experiencing difficulties.  You'll need to perform the migration of checkpoints that you wish to preserve before running one of the `Azure.Messaging.EventHubs` event processors, unless you're using the [beta extension](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs/5.0.0-beta.6) for Azure Functions, which allows an implicit one-way upgrade. 

Our [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md) has a section for [Migrating EventProcessorHost checkpoints](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md#migrating-eventprocessorhost-checkpoints) that walks through the details of conversion and provides a code sample for doing so.

**Comment by RetYn** [comment]
@jsquire  Got it. And we also have situations in upgrading the extension you mentioned for Azure Function. 
Do you mean if I use the beta extension, it will handle the legacy format for me?

**Comment by jsquire** [comment]
> Do you mean that duration upgrade the extension to beta, it will handle the legacy format automatically? /unresolve

Correct;  Upgrading the extension package to the beta upgrades the Event Hubs SDK used by Functions to `Azure.Messaging.EventHubs` and has logic that will upgrade legacy checkpoints to the new format on the fly.   The major consideration to note is that this is a forward-only operation.   Should you decide to downgrade the extensions package,  you will not see the new checkpoints and your Function will reprocess from the previous legacy checkpoint.

**Comment by RetYn** [comment]
Thank you, addition question, do any planned time that the extension will be stable? 
You can closed the issue.

**Comment by jsquire** [comment]
> Thank you, an addition question, does any planned time that the extension will be stable?

The current plan, though not final and subject to change, is that we'd like to GA the extension early next month.   It is still undergoing some final testing and approvals, however, which may potentially impact that plan.

**Comment by jsquire** [comment]
> You can closed the issue.

I'll go ahead and do that.    I'll apply the addressed tag again so that you've got the `\unresolved` command available should something come up and you wish to reopen.

**Comment by RetYn** [comment]
/unresolve
I have upgraded to Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0-beta6.
It looks work well with old checkpoint version since I do not see any message re-processed. 
But does it normal that I can not find any new checkpoint folder in the container?  By the way I see the owner container

**Comment by jsquire** [comment]
If checkpoints are being written, you should see them in the container.    They would be in a sibling to the "ownership" path and should look something like:
    `[[ container name ]]/[[ Event Hubs namespace ]]/[[ Event Hub name ]]/[[ Consumer Group name ]]/checkpoint`.   

Under that path, you should have a blob for each partition that a checkpoint was written for.   The checkpoint data itself is stored as metadata on that blob.   If you're not seeing blobs in that path, that would indicate that a checkpoint isn't being written.  If that's the case, please let me know and we'll pull in some folks with a deeper understanding of the bindings internals to help troubleshoot why.

**Comment by RetYn** [comment]
Sorry for the weekend absent.
I have seen the checkpoint folder by now.  The checkpoint folder and files were created 2 hours behind the ownership files. (Since I worked in dev env , the data flow is very small. after 2 hours I guess event job reached its commit threshold?)  Is that act as your design that in migration situation, the new checkpoint will only be created after a ack?

**Comment by jsquire** [comment]
That sounds about right.   My understanding is that the Functions bindings will automatically create a checkpoint after some number of event batches has been processed (configurable) as well as allowing a manual checkpoint creation.  The [docs](https://docs.microsoft.com/azure/azure-functions/functions-bindings-event-hubs#hostjson-settings) appear to confirm that as well.  In your scenario, it sounds like the threshold took a while to reach.

Sounds like everything is working as intended.
