### ISSUE TITLE
Need clarification on the scope

### ISSUE THREAD

**Issue by gkarnik-gl** [Azure/azure-sdk-for-net#21866]
The page mentions: "Enables authentication to Azure Active Directory using a client secret that was generated for an App Registration." Is the mention of "client secret generated for an App Registration" in Azure AD a bit misleading since this also supports service principal rbac credential as mentioned in https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme, section: Authenticating Service Principals
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b859488-2706-23cd-71bb-e9c95a157079
* Version Independent ID: 1a4c5617-75a2-78fc-8e3e-13c7076dd67e
* Content: [ClientSecretCredential Class (Azure.Identity) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.clientsecretcredential?view=azure-dotnet)
* Content Source: [xml/Azure.Identity/ClientSecretCredential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Identity/ClientSecretCredential.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Thanks @gkarnik-gl - Do you have a suggestion for how it could be re-worded to be more clear?

**Comment by gkarnik-gl** [comment]
@christothes - thanks for your reply! I was wondering if you could also mention that it supports service principal rbac?
