### ISSUE TITLE
DataContractBinarySerializer equivalent in Azure.Messaging.ServiceBus

### ISSUE THREAD

**Issue by JacksonHong** [Azure/azure-sdk-for-net#21874]
When we previously migrated from WindowsAzure.ServiceBus to Microsoft.Azure.ServiceBus we had to use DataContractBinarySerializer provided in Microsoft.Azure.ServiceBus.InteropExtensions to make sure that messages are backward compatible during rollout.

It appears that there is no such serializer in Azure.Messaging.ServiceBus 7.1.2. I would like to confirm that just to make sure I did not miss anything.

We are trying to migrate to Azure.Messageing.ServiceBus but in order to be compatible with existing services we need to serialize our messages in the old format so they can be deserialized by services not yet upgraded to Azure.Messaging.ServiceBus. I could do it in one step instead of two steps if there is an equivalent to DataContractBinarySerializer in 7.1.2

**Comment by JoshLove-msft** [comment]
Hi @JacksonHong,
There is no equivalent to DataContractBinarySerializer in Azure.Messaging.ServiceBus. Please let us know if we can help with anything else.
