### ISSUE TITLE
The dependency WindowsAzure.ServiceBus 3.3.1 does not support framework .NETCoreApp,Version=v1.0.

### ISSUE THREAD

**Issue by himadrinath** [Azure/azure-sdk-for-net#2188]
how can i fixed it

**Comment by DeluxZ** [comment]
Also doesn't support .NETCoreApp,Version=v2.0

**Comment by SeanFeldman** [comment]
WindowsAzure.ServiceBus is the old client that does not support .NET Core.
For .NET Core, use [Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/) client.

**Comment by jfggdl** [comment]
Closing issue.

@himadrinath Please feel free to reopen this issue if your concerns/questions were not addressed. Thank you.
