### ISSUE TITLE
Are symbols publish to symweb | MSDL?

### ISSUE THREAD

**Issue by LittleLittleCloud** [Azure/azure-sdk-for-net#21891]
**Query/Question**
Hi Azure SDK team, We are inserting a VS component into VS which has reference to `Azure.Storage.Common` and it fails at symbol check step. This usually indicates that the symbol is missing on symweb, but symbol check task will also fail if the symbol is the portable format.

If it is the first case, is it possible for your team to add symbols to symweb in the near future? This should not be a very easy task with arcade and it also facilitates external users if pdb symbols are available. If it's the second case(portable pdb published), feel free to close this issue.

Regards

**Comment by jsquire** [comment]
@weshaggard:  This seems like something that may benefit from deeper knowledge of our build pipeline and publishing.   Do you mind offering your thoughts?

**Comment by weshaggard** [comment]
@LittleLittleCloud our packages should be archiving symbols on symweb. Can you point me at the version the package and the symchk command output you are getting for that version?

**Comment by LittleLittleCloud** [comment]
Hi @weshaggard happy to do that

The version is 12.7.3 and symchk command is (you might need replace the path to symchk exe on your PC)
```
"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\symchk.exe" /v /s SRV*http://symweb Azure.Storage.Common.dll
```

And the output is
```
[SYMCHK] Searching for symbols to C:\Users\xiaoyuz\Desktop\Azure.Storage.Common.dll in path SRV*http://symweb
DBGHELP: Symbol Search Path: SRV*http://symweb
[SYMCHK] Using search path "SRV*http://symweb"
DBGHELP: No header for C:\Users\xiaoyuz\Desktop\Azure.Storage.Common.dll.  Searching for image on disk
DBGHELP: C:\Users\xiaoyuz\Desktop\Azure.Storage.Common.dll - OK
SYMSRV:  BYINDEX: 0x1
         http://symweb
         Azure.Storage.Common.pdb
         5949092657144DDEA29F1C0E3CA29F621
SYMSRV:  UNC: C:\ProgramData\dbg\sym\Azure.Storage.Common.pdb\5949092657144DDEA29F1C0E3CA29F621\Azure.Storage.Common.pdb - path not found
SYMSRV:  UNC: C:\ProgramData\dbg\sym\Azure.Storage.Common.pdb\5949092657144DDEA29F1C0E3CA29F621\Azure.Storage.Common.pd_ - path not found
SYMSRV:  UNC: C:\ProgramData\dbg\sym\Azure.Storage.Common.pdb\5949092657144DDEA29F1C0E3CA29F621\file.ptr - path not found
SYMSRV:  HTTPGET: /index2.txt
SYMSRV:  HttpSendRequest: 800C2EE7 - ERROR_INTERNET_NAME_NOT_RESOLVED
SYMSRV:  HTTPGET: /Azure.Storage.Common.pdb/5949092657144DDEA29F1C0E3CA29F621/Azure.Storage.Common.pdb
SYMSRV:  HttpSendRequest: 800C2EE7 - ERROR_INTERNET_NAME_NOT_RESOLVED
SYMSRV:  RESULT: 0x800C2EE7
DBGHELP: Azure.Storage.Common - no symbols loaded
[SYMCHK] MODULE64 Info ----------------------
[SYMCHK] Struct size: 1680 bytes
[SYMCHK] Base: 0x10000000
[SYMCHK] Image size: 90112 bytes
[SYMCHK] Date: 0xf848baef
[SYMCHK] Checksum: 0x0002230d
[SYMCHK] NumSyms: 0
[SYMCHK] SymType: SymNone
[SYMCHK] ModName: Azure.Storage.Common
[SYMCHK] ImageName: C:\Users\xiaoyuz\Desktop\Azure.Storage.Common.dll
[SYMCHK] LoadedImage: C:\Users\xiaoyuz\Desktop\Azure.Storage.Common.dll
[SYMCHK] PDB: ""
[SYMCHK] CV: RSDS
[SYMCHK] CV DWORD: 0x53445352
[SYMCHK] CV Data:  /_/artifacts/obj/Azure.Storage.Common/Release/netstandard2.0/Azure.Storage.Common.pdb
[SYMCHK] PDB Sig:  0
[SYMCHK] PDB7 Sig: {59490926-5714-4DDE-A29F-1C0E3CA29F62}
[SYMCHK] Age: 1
[SYMCHK] PDB Matched:  TRUE
[SYMCHK] DBG Matched:  TRUE
[SYMCHK] Line nubmers: FALSE
[SYMCHK] Global syms:  FALSE
[SYMCHK] Type Info:    FALSE
[SYMCHK] ------------------------------------
SymbolCheckVersion  0x00000002
Result              0x00010001
DbgFilename         Azure.Storage.Common.dbg
DbgTimeDateStamp    0x00000000
DbgSizeOfImage      0x00000000
DbgChecksum         0x00000000
PdbFilename         /_/artifacts/obj/Azure.Storage.Common/Release/netstandard2.0/Azure.Storage.Common.pdb
PdbSignature        {00000000-0000-0000-0000-000000000000}
PdbDbiAge           0x00000000
[SYMCHK] [ 0x00000000 - 0x00010001 ] Checked "C:\Users\xiaoyuz\Desktop\Azure.Storage.Common.dll"
SYMCHK: Azure.Storage.Common.dll FAILED  - /_/artifacts/obj/Azure.Storage.Common/Release/netstandard2.0/Azure.Storage.Common.pdb mismatched or not found

SYMCHK: FAILED files = 1
SYMCHK: PASSED + IGNORED files = 0
```

However, the failure only indicates that symchk fails to find traditional windows-format pdb on symweb. So if the archived symbol format is portable (the second type), this check will fail as well.

**Comment by weshaggard** [comment]
@LittleLittleCloud this works for me locally. I believe you are pointing to the wrong server please use `https://symweb` (note the s in https).

**Comment by weshaggard** [comment]
Actually I did it on another clean machine and http vs https didn't really do anything like I thought. However if you don't have access to symweb you can get them from the public symbol server http://msdl.microsoft.com/download/symbols. Please try that and if that still doesn't work for you please ping me offline and I can help you find the right symbols. 

As far as I'm aware we are publishing the full windows pdbs to all the correct symbol servers so I'm going to close this until we find that isn't true.
