### ISSUE TITLE
[QUERY] Proxy authentication with TableClient in the Azure.Data.Tables package 

### ISSUE THREAD

**Issue by ershadnozari** [Azure/azure-sdk-for-net#21902]
Hello,

How do I set proxy credentials with the TableClient? I am using Azure.Data.Tables version12.0.1

Code sample is appreciated.

Many thanks.
Ershad

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @ershadnozari - Please see the following documentation: https://docs.microsoft.com/en-us/dotnet/azure/sdk/azure-sdk-configure-proxy?tabs=cmd

**Comment by ershadnozari** [comment]
@christothes many thanks for response. The only issue I have with this approach is using the command prompt to set the username and password. At the organization I work we are required to change our corporate passwords every 3 months. Setting the credentials via the command line there is a potential risk that the account gets locked out when password changes. Is there another way, i.e. through code/config?

**Comment by christothes** [comment]
The value is obtained from the environment variable, so you could automate how that is set with code. But other than that, this is currently the only way to set it.

**Comment by ershadnozari** [comment]
@christothes ok thanks.
