### ISSUE TITLE
Can't refer to columns by the name that is specified in the header row when using .NET Azure.Storage.Blobs v12.9.0

### ISSUE THREAD

**Issue by mauricio-msft** [Azure/azure-sdk-for-net#21901]
**Describe the bug**
I have an CSV file with a header row, and after updating package .NET Azure.Storage.Blobs to latest version (v12.9.0), whether I set true or false to HasHeaders property in InputTextConfiguration, it will be ignored.

So, I can't refer to columns by the name that is specified in the header row without getting an Azure.RequestFailedException

string query = @"SELECT col1 FROM BlobStorage";
And... of course, my CSV file has a row header like: col1, col2, col3...

This works with previous .NET Azure.Storage.Blobs versions packages, like v12.8.4

Exception:

Exception: Azure.RequestFailedException: Column names can be used only if 'hasHeader' is set in the config and there is a header row.
RequestId:8d691e9c-c01e-0003-4da2-5f4d59000000
Time:2021-06-12T15:48:30.2248117Z
Status: 400 (Column names can be used only if 'hasHeader' is set in the config and there is a header row.)
ErrorCode: ErrorProcessingQueryExpression

Content:

ErrorProcessingQueryExpressionColumn names can be used only if 'hasHeader' is set in the config and there is a header row.
RequestId:8d691e9c-c01e-0003-4da2-5f4d59000000
Time:2021-06-12T15:48:30.2248117Z

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-error-code: ErrorProcessingQueryExpression
x-ms-request-id: 8d691e9c-c01e-0003-4da2-5f4d59000000
x-ms-version: 2020-08-04
x-ms-client-request-id: 596a2068-b4a1-461d-a433-c9cababc7b5d
Date: Sat, 12 Jun 2021 15:48:29 GMT
Content-Length: 302
Content-Type: application/xml

at Azure.Storage.Blobs.BlobRestClient.QueryAsync(String snapshot, Nullable1 timeout, String leaseId, String encryptionKey, String encryptionKeySha256, Nullable1 encryptionAlgorithm, Nullable1 ifModifiedSince, Nullable1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, QueryRequest queryRequest, CancellationToken cancellationToken)
at Azure.Storage.Blobs.Specialized.BlockBlobClient.QueryInternal(String querySqlExpression, BlobQueryOptions options, Boolean async, CancellationToken cancellationToken)
at Azure.Storage.Blobs.Specialized.BlockBlobClient.QueryAsync(String querySqlExpression, BlobQueryOptions options, CancellationToken cancellationToken)
at ConsoleApp1.Program.DumpQueryCsv(BlockBlobClient blob, String query, Boolean headers) in C:\Cases\Danny\ReadCSVFile\ReadCSVFile\Program.cs:line 90

Base doc: https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-query-acceleration-how-to?tabs=dotnet%2Cpowershell#retrieve-data-by-using-a-filter

**Expected behavior**
When set true to HasHeaders property in InputTextConfiguration, and if the source file contains a header row, then you can refer to columns by the name that is specified in the header row, as long as 

**Actual behavior (include Exception or Stack Trace)**
I have an CSV file with a header row, and after updating package .NET Azure.Storage.Blobs to latest version (v12.9.0), whether I set true or false to HasHeaders property in InputTextConfiguration, it will be ignored.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Just follow the sample provided in https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-query-acceleration-how-to?tabs=dotnet%2Cpowershell#retrieve-data-by-using-a-filter

**Environment:**
 - .NET Azure.Storage.Blobs v12.9.0 
 - Azure Data Lake Storage query acceleration
 - IDE and version : Visual Studio 16.10.2

**Comment by amishra-dev** [comment]
We are following up on email. will post a resolution here and close this issue out.

**Comment by amnguye** [comment]
Mitigated offline.
