### ISSUE TITLE
Allow developer to override QueueOptions.MaxPollingInterval during development

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#21903]
**Library or service name.**
QueueOptions has MaxPollingInterval. It is hardcoded to 2 seconds in dev mode here: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/src/StorageQueuesWebJobsBuilderExtensions.cs#L60

The setting in host.json is ignored.

```json
{
    "version": "2.0",
    "extensions": {
        "queues": {
            "maxPollingInterval": "00:00:10"
        }
    }
}
```

The local dev experience needs to be able to override this value.

**Is your feature request related to a problem? Please describe.**

I spent a lot of time trying to figure out how to override that value to no avail.  So, I had to reach out to my function team friends and they assisted in figuring out a workaround.

The extension should honor what the developer puts in host.json

This is my current workaround, but isn't sufficient as I would not have been able to figure this out on my own.

```csharp
 public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            builder.Services.PostConfigure<QueuesOptions>(options => options.MaxPollingInterval = TimeSpan.FromSeconds(10));
        }
    }
```

azsdke2e
azsdke2e2

**Comment by kasobol-msft** [comment]
This is behavior carried forward from previous version, see https://github.com/Azure/azure-webjobs-sdk/issues/1869 .

I think we can keep 2 seconds as default in dev env, but honor other values if they're explicitly set either in host.json or programmatically.

**Comment by jongio** [comment]
Thank you @kasobol-msft!
