### ISSUE TITLE
[Storage] ObjectDisposedException when cancelling BlobClient.DownloadTo() on net461

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#21923]
When I run the DownloadBlob perf test on net461 through the test-proxy, and I cancel the token while the `DownloadToAsync()` API is running, it sometimes (but not always) fails with this exception:

```
Exception: System.ObjectDisposedException: Cannot access a closed Stream.
at System.IO.Stream.CopyToAsync(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
at Azure.Storage.Blobs.PartitionedDownloader.<CopyToAsync>d__8.MoveNext()
```

I was only able to repro when using net461.  It doesn't repro when I run against the live service.  I also couldn't get it to repro using a simpler program with the test proxy.

## Repro Steps
1. Run test proxy
    1. `git clone https://github.com/Azure/azure-sdk-tools`
    2. `git checkout 9170a2c6f87ac9f9c7bc90b112e78bc634529c80`
    3. `cd tools\test-proxy\Azure.Sdk.Tools.TestProxy`
    4. `dotnet run -f net5.0`
2. Run perf test
    1. `git clone https://github.com/mikeharder/azure-sdk-for-net`
    2. `git checkout c3fbb9738452eac274cced7e16f56a108a8a93a0`
    3. `cd sdk\storage\Azure.Storage.Blobs\perf\Azure.Storage.Blobs.Perf`
    4. `dotnet run -f net461 -- downloadblob -w 1 -d 1 -s 1 -x https://localhost:5001`
3. If you run the perf test several times, you should eventually get the above exception.

## Possibly Related
* https://github.com/Azure/azure-sdk-for-net/issues/18483

**Comment by kasobol-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-net/issues/23862
