### ISSUE TITLE
[FEATURE REQ] Client-side Encryption KEK Rotation Method

### ISSUE THREAD

**Issue by maxi1983** [Azure/azure-sdk-for-net#21930]
Legacy SDK feature parity issue. Legacy SDK provided a method to download encryption metadata for a blob, unwrap the CEK, re-wrap the CEK using a new KEK, update encryption metadata accordingly, and set the new metadata. The legacy method also preserved all metadata on the blob and forced ETag locking on the operation to ensure safety. Such a method doesn't exist in the new SDK and the model classes for encryption metadata aren't public for a manual workaround.

Original issue text:
> **Query/Question**
> Can not find RotateEncryptionKey or equivalence in Azure.Storage.Blobs version 12
> 
> **Environment:**
>  - Name and version of the Library package used: Azure.Storage.Blobs 12.9.0 
> 
> Our application references Azure Blob Storage sdk and now I am working on upgrade the sdk from 11 to 12. I found that in version 11, there is a method named RotateEncryptionKeyAsync in Microsoft.Azure.Storage.Blob.CloudBlob, but in version 12, I can't find an equivalence.

**Comment by amishra-dev** [comment]
@jaschrep-msft can you look at this tomorrow.

**Comment by jaschrep-msft** [comment]
You are correct, there is not an equivalent method, and we do not publicize the classes needed for you to roll your own implementation on top of the existing SDK.

Editing this issue to be a feature request for an equivalent method.

**Comment by ArielZhang** [comment]
the issue blocked us upgrade to v12, can you share a timeline with us?

**Comment by seanmcc-msft** [comment]
We have this in our backlog, but we do not currently have an exact timeline for when it will be addressed.
