### ISSUE TITLE
[Azure.Messaging.ServiceBus] error deserializing the object of type System.String [BUG]

### ISSUE THREAD

**Issue by JarFrank** [Azure/azure-sdk-for-net#21932]
Hi guys!
I am having issues with receiving messages from Azure.Messaging.ServiceBus. 
In most cases (95%), my process works as expected, but randomly I get such an error:
`Moved because of Unable to get Message content There was an error deserializing the object of type System.String. The input source is not correctly formatted.`

Send method:
```csharp
public async Task Send(string serializedMessage, string endpointName)
{
    await using var client = new ServiceBusClient(AppSettingServiceBusConnectionString);
    var sender = client.CreateSender(endpointName);

    var bytes = System.Text.Encoding.UTF8.GetBytes(serializedMessage);
    var message = new ServiceBusMessage(bytes);
    await sender.SendMessageAsync(message).ConfigureAwait(false);
}
```
When I recieve the message I use a CreateProcessor with MessageHandler:
```csharp
private async Task MessageHandler(ProcessMessageEventArgs args)
{
    try
    {
        _logger.Info("MessageHandler is started");
        
        var bytes = args.Message.Body.ToArray();
        var message = System.Text.Encoding.UTF8.GetString(bytes);
        var result = MyWorkerService(message);

        await args.CompleteMessageAsync(args.Message);
        _logger.Info("MessageHandler is finished");
    }
    catch (Exception ex)
    {
        await args.DeadLetterMessageAsync(args.Message, "Error while processing message", ex.Message);
        _logger.Error(ex.Message);
    }
}
```
The message is always sent correctly and goes to the queue, after that my MessageHandler reads the it and try to process. If everything goes as expected then message is completed, but when something goes wrong, the error is logged and the message is moved to the DeadLetter.

The problem is when I get a message with this particular error my logger doesn't log anything so I assume the error is thrown somewhere inside the library just before calling my MessageHandler. The message is then automatically moved to the DLQ with this reason and error description:
```
DeadLetterReason: Moved because of Unable to get Message content There was an error deserializing the object of type System.String. The input source is not correctly formatted.
DeadLetterErrorDescription: Des
Diagnostic-Id: |a703babc-849e-453c_
```
Moreover, when I try to manually process a dead letter messages, I am doing it successfully...

Have any of you dealt with something similar?

**Environment:**
 - Azure.Messaging.ServiceBus: 7.1.2
 - Sender: .NET Framework 4.6.2
 - Receiver: .NET Framework 4.7.2

**Comment by JoshLove-msft** [comment]
Hi @JarFrank,
Any chance you can include the logs for when this error occurs? I see you have pasted in what looks like the message properties once the message is moved to the DLQ, but it would help to see the SDK logs to figure out where this error is occuring.

**Comment by JarFrank** [comment]
Hi @JoshLove-msft ! Thank you for your response!

I believe Azure Service Bus doesn't support custom logging by default and I have to configure this separately. I found this link  below 
[Messaging.ServiceBus_7.1.2/sdk/core/Azure.Core/samples/Diagnostics.md](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.1.2/sdk/core/Azure.Core/samples/Diagnostics.md)

Is it enough for me to add this snipet to the code?
```
_listener = new AzureEventSourceListener(
    (e, message) => _logger.InfoFormat("[AZURE-SDK][{0}] {1}", e.Level, message),
    level: EventLevel.Verbose);
```

**Comment by JoshLove-msft** [comment]
Yes that should be enough.

**Comment by JoshLove-msft** [comment]
I think this error comes from the DataContractSerializer. The client library doesn't use it anywhere so I assume this error is actually originating in the service. 
Were all of your messages sent in the same way using the Azure.Messaging.ServiceBus client library? Were any sent with the Service Bus Explorer or with a different library?
