### ISSUE TITLE
[BUG] Memory usage problem using OpenReadAsync inside a list

### ISSUE THREAD

**Issue by pilarodriguez** [Azure/azure-sdk-for-net#21933]
**Describe the bug**
There is a memory issue when using OpenReadAsync inside a list.
In our code, we get all the blobs from a container and add them to a list. We use the OpenReadAsyc. Once the list is created, we loop through all the items and add them to a zip file. 
With the WindowsAzure.Storage package 9.3.3 version, there were no problems, but with the Azure.Storage.Blobs package version 12.8.3 we have a memory leak problem. In each iteration, the memory goes up. When we have many blobs, the service crashes. 
With the previous version the memory usage is stable, but with Azure.Storage.Blobs is not.

**Expected behavior**
What is the expected behavior?
Memory usage should be stable, as it was in the WindowsAzure.Storage package. Memory usage in WindowsAzure.Storage:

![image](https://user-images.githubusercontent.com/19167534/122381075-d01c5c00-cf68-11eb-8d55-ac1529ada2b2.png)

**Actual behavior (include Exception or Stack Trace)**
Memory usage using Azure.Storage.Blobs:

![image](https://user-images.githubusercontent.com/19167534/122381181-e9250d00-cf68-11eb-886a-4d6b6de8cf10.png)

**To Reproduce**
You can reproduce this behavior using this simple test to upload some blobs and then loop through them doing an OpenReadAsync. 

 WindowsAzure.Storage:
```
const string folderName = "test";

var blobClient = CloudStorageAccount.Parse("UseDevelopmentStorage=true").CreateCloudBlobClient();
var azureContainer = blobClient.GetContainerReference(_containerName);
await azureContainer.CreateIfNotExistsAsync();

for (var i = 0; i < 1000; i++)
{
    var blobName = BlobPath.Combine(folderName, $"{_blobName}{i}");

    var blob = azureContainer.GetBlockBlobReference(blobName);
    await blob.UploadFromByteArrayAsync(content, 0, content.Length).ConfigureAwait(false);
}

var blobList = new List<Task<Stream>>();
for (var i = 0; i < 1000; i++)
{
    var blobName = BlobPath.Combine(folderName, $"{_blobName}{i}");
    var blob = azureContainer.GetBlobReference(blobName);

    blobList.Add(blob.OpenReadAsync());
}
```

Azure.Storage.Blobs. The memory goes up on every iteration of the second foreach
```
var content = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8 };
const string folderName = "test";

var blobClient = new BlobServiceClient("UseDevelopmentStorage=true");
var azureContainer = blobClient.GetBlobContainerClient(_containerName);
await azureContainer.CreateIfNotExistsAsync();

for (var i = 0; i < 1000; i++)
{
    var blobName = BlobPath.Combine(folderName, $"{_blobName}{i}");

    var blob = azureContainer.GetBlobClient(blobName);
    using (var stream = new MemoryStream(content, 0, content.Length))
    {
        await blob.UploadAsync(stream, overwrite: true).ConfigureAwait(false);
    }
}

var blobList = new List<Task<Stream>>();
for (var i = 0; i < 1000; i++)
{
    var blobName = BlobPath.Combine(folderName, $"{_blobName}{i}");
    var blob = azureContainer.GetBlobClient(blobName);

    blobList.Add(blob.OpenReadAsync());
}
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.8.3
 - Hosting platform or OS and .NET runtime version: Azure AppService .NET Framework 4.6.2
 - IDE and version: Visual Studio 16.8.3

**Comment by amishra-dev** [comment]
@kasobol-msft can you look?

**Comment by kasobol-msft** [comment]
@pilarodriguez V12 SDK uses larger buffer by default, i.e. 4MB (see [here](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobopenreadoptions.buffersize?view=azure-dotnet#Azure_Storage_Blobs_Models_BlobOpenReadOptions_BufferSize)). The V11 SDK used just above 16KB.

Therefore I recommend to specify smaller buffer size explicitly when calling open read to accommodate your usage pattern. Please let us know if this resolves your issue.

**Comment by pilarodriguez** [comment]
Yes, this fixes the issue. Thanks a lot

**Comment by pilarodriguez** [comment]
One extra question, is the buffer size specified in megabytes or in bytes? In the [method summary](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L1947) it is only mentioned that the default is 1MB.

**Comment by kasobol-msft** [comment]
Buffer size is in bytes.
