### ISSUE TITLE
Azure Device Update - Managed Identity

### ISSUE THREAD

**Issue by sourabhkrishna** [Azure/azure-sdk-for-net#21937]
Does the Azure Device Update SDK support Managed Identities ? Facing below exceptions for all calls via MI

  _updatesClient = new UpdatesClient(appConfig.AccountEndpoint, appConfig.Instance, new DefaultAzureCredential());

"@timestamp":"2021-06-17T09:37:52.7224991+00:00","level":"Error","message":"Import update operation failed with Exception, Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.\nStatus: 403 (Forbidden)\n\nContent:\nfailed to refresh token, error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS100009: Regional Cache Auth Service token requests for flows that require encrypted tokens are forbidden.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by AlexGhiondea** [comment]
@drwill-ms do you happen to know?

**Comment by drwill-ms** [comment]
My team doesn't own that SDK or service, so I can't say.

**Comment by sourabhkrishna** [comment]
Will this be available in the PPR ?
