### ISSUE TITLE
[BUG] Blob storage service/container/blob clients drop account name for emulator connection string with custom domain name and port number

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#21956]
**Describe the bug**

Give the following connection string:

> AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://host.docker.internal:10010/devstoreaccount1;

`BlobServiceClient` is constructed incorrectly, with missing `AccountName`

<img src="https://user-images.githubusercontent.com/1309622/122505834-5f059480-cfba-11eb-8774-51f388b9b541.png" width="500px"/>

As a result of that, the subsequent `BlobContainerClient` and `BlobClient` created from the service client, are also malformed.

```
var serviceClient = new BlobServiceClient(connectionString);
var containerClient = serviceClient.GetBlobContainerClient("containername"); 
var blobClient = containerClient.GetBlobClient("abc.txt");
```
results in
<img src="https://user-images.githubusercontent.com/1309622/122506001-b3107900-cfba-11eb-9093-4bcb8932dcdd.png" width="500px"/>

and

<img src="https://user-images.githubusercontent.com/1309622/122506025-bd327780-cfba-11eb-9feb-5e262c9129f1.png" width="500px"/>

The missing `AccountName` is causing the blob URI to be malformed: `http://host.docker.internal:10010/devstoreaccount1/abc.txt`, resulting in blob operations failing.

**Expected behavior**

`BlobClient` should have account name should be detected properly (known emulator account name), preserved and blob operations succeed.

**Actual behavior (include Exception or Stack Trace)**

<img src="https://user-images.githubusercontent.com/1309622/122506278-3b8f1980-cfbb-11eb-9809-7bf15f8982b4.png" width="300px"/>

**To Reproduce**

```
[Fact]
public void Use_custom_host_name_and_port_for_emulator()
{
    var connectionString = string.Format("AccountName={0};AccountKey={1};BlobEndpoint={2};",
        "devstoreaccount1", "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==", "http://host.docker.internal:10010/devstoreaccount1");
    var containerName = "containername";
    var blobName = "abc.txt";

    var serviceClient = new BlobServiceClient(connectionString);
    var containerClient = serviceClient.GetBlobContainerClient(containerName); //new BlobContainerClient(connectionString, containerName);
    var blobClient = containerClient.GetBlobClient(blobName);

    Assert.Equal(10_010, blobClient.Uri.Port);
    Assert.Equal("devstoreaccount1", blobClient.AccountName); // ❌ ""
    Assert.Equal("containername", blobClient.BlobContainerName); // ❌ "devstoreaccount1"
    Assert.Equal("abc.txt", blobClient.Name); // ❌ "containername/abc.txt"
}
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.x
 - Windows 10
 - .NET Core 3.1

**Comment by SeanFeldman** [comment]
It looks like there are already pre-planned milestones from July to December 2021, and there's some decision-making process to assigned backlogged items to those milestones. @jsquire, would you be able to shed some light on the process of how bugs from the `Backlog` milestone get triaged and assigned to those milestones?

**Comment by jsquire** [comment]
Hi @SeanFeldman.   Happy to offer what context I can.  In this case, it's purely procedural.  Any issue tagged with `bug` or `feature`  is required to have a milestone associated with it.  Issues are also required to have only one of `bug`, `feature`, and `question`.  Weekly, validation takes place and generates a report listing issues in an invalid state.  

Once the `bug` label was added, the issue started failing validation and alerting the triage team.  Since `bug` was added by the team that owns the issue, it was given precedence so `question` was removed.  By default issues with no milestone are shifted to `backlog` until the team that owns them decides to schedule them.

**Comment by amishra-dev** [comment]
@seanmcc-msft can you please try this?

**Comment by seanmcc-msft** [comment]
Couple things here:

First, the Azure Storage Emulator is [deprecated](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#authorize-with-shared-key-credentials), we recommend moving to [Azurite](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio).

Also, I'm not sure if the Azure Storage Emulator supports custom domain names and port numbers.  From the documentation, it looks like it only supports `BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;` https://docs.microsoft.com/en-us/azure/storage/common/storage-use-emulator#connect-to-the-emulator-account-using-the-shortcut

-Sean

**Comment by navba-MSFT** [comment]
@SeanFeldman Apologies for the late reply. The Azure Storage Emulator is now deprecated. Microsoft recommends that you use the [Azurite emulator](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio) for local development with Azure Storage. Azurite supersedes the Azure Storage Emulator. Could you please test this and let us know if you face the same issue ? Awaiting your reply.

**Comment by SeanFeldman** [comment]
The issue was originally detected using Azurite, not Storage Emulator. The term 'emulator' is a general term. But that's not the core issue. The problem is with the client that drops information (see issue description).

Azurite is capable of running multiple accounts.

**Comment by navba-MSFT** [comment]
Thanks @SeanFeldman for getting back. 
@seanmcc-msft Could you please look into this once you get a chance and update this thread?

**Comment by dgarciarubio** [comment]
Is this bug related to [this one](https://stackoverflow.com/questions/75183405/blobserviceclient-making-wrong-calls-when-azurite-is-not-on-default-port)? In this case what seems to be missing is the container name in the URL, not the account name.

Not sure if both things are related

**Comment by SeanFeldman** [comment]
If the decision is not to fix the bug, state it so. Otherwise, no reason to close.
