### ISSUE TITLE
Create Certificate Policy with SAN

### ISSUE THREAD

**Issue by shuyinggg** [Azure/azure-sdk-for-net#21953]
Hi All,

I am currently using the Nuget package Azure.Security.KeyVault.Certificate version 4.2.0.0 to create some certs in C# and have questions with SANs.

I'm creating a cert with SAN using the list of DNS names, however, when I do so, all the fields in the SubjectAlternativeNames are read-only. In this case, how can we input SANs in the cert creation time? Please advise. Thanks for your help.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
You can use the [C# object initializer](https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers) pattern:

```csharp
CertificatePolicy policy = new CertificatePolicy
{
  SubjectAlternativeNames =
  {
    DnsNames =
    {
      "host1.domain.com",
      "host2.domain.com"
    }
  },
  // ...
};
```

Following [.NET guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values), our collection properties are read-only but the collections are still often mutable.
