### ISSUE TITLE
Update the documentation page to point to stable release

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure/azure-sdk-for-net#21957]
Update the documentation page to point to stable release.
It still refers to beta.8 version

![image](https://user-images.githubusercontent.com/8835012/122510987-31553580-d024-11eb-99ab-e493ee66d1e6.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7139f609-fc7c-361d-ab81-bd8c15be23c4
* Version Independent ID: 5a22db59-9012-23a0-5139-00ef98214928
* Content: [Azure Tables client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/data.tables-readme-pre)
* Content Source: [api/overview/azure/data.tables-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/data.tables-readme-pre.md)
* Service: **tables**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
@danieljurek:  The `Overview` node from the left nav is inking to the pre-release doc.   Are you able to retarget to the [release version](https://docs.microsoft.com/dotnet/api/overview/azure/data.tables-readme)?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by danieljurek** [comment]
This was fixed
