### ISSUE TITLE
[QUERY] FormRecognizer - Serialization for RecognizedFormCollection

### ISSUE THREAD

**Issue by saucepleez** [Azure/azure-sdk-for-net#21982]
**Query/Question**
What is the correct way to handle serializing/deserializing Form Recognizer responses to and from JSON format using the Azure SDK?  I am using Newtonsoft and attempting to serialize the `RecognizedFormCollection` for future processing as the `FormField` class contains methods to operate on the data that is loaded into the model, however, the class constructors are marked internal and as such cannot be deserialized directly.  What is the correct way to handle this scenario?

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/src/RecognizedFormCollection.cs

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0]  Form Recognizer 3.2
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8] .NET 5
 - IDE and version : [e.g. Visual Studio 16.3] VS2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by maririos** [comment]
Hi @saucepleez to make sure I understand your scenario, you want a way to access the internal constructors for mocking purposes?
The library includes a static class `FormRecognizerModelFactory` . You can find it here: https://docs.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.models.formrecognizermodelfactory.recognizedform?view=azure-dotnet#Azure_AI_FormRecognizer_Models_FormRecognizerModelFactory_RecognizedForm_System_String_Azure_AI_FormRecognizer_Models_FormPageRange_System_Collections_Generic_IReadOnlyDictionary_System_String_Azure_AI_FormRecognizer_Models_FormField__System_Collections_Generic_IReadOnlyList_Azure_AI_FormRecognizer_Models_FormPage__System_String_System_Nullable_System_Single__

Let me know if that helps.

**Comment by saucepleez** [comment]
Hello,

No.  What I am trying to do is execute Form Recognizer which returns a `RecognizedFormCollection`.  Once I have that object, I would like to export it as a json string somewhere (ex. Database) as I will need to process it at a later time.  Once I decide later on to to process it, I would like to deserialize the json back into a new `RecognizedFormCollection` and then use the methods such as `field.Value.GetConvertedValue();` to pull out the values.

Given that `RecognizedFormCollection` does not support constructors, how am I supposed to load the data into the class properly?

**Comment by maririos** [comment]
Thanks for the clarification @saucepleez .
It does seem like what you are trying to do won't be possible with the SDK as the `RecognizedFormCollection` is not meant to be initialized or modified by the user. It only exposes the data the service recognized.
You could take a different approach and get all the fields and information from each field from the beginning (each field only has one type so the method to use will always be the same. i.e. `AsList()` and save that as a json file that you can later consume.

For example, if you take this [sample ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/Sample2_RecognizeCustomForms.md#recognize-custom-forms-from-a-uri)instead of printing the values, you save them in a json file format. Of course, you will need to modify the code to make sure it adjusts to your files and the output you desire

**Comment by vadimkhm** [comment]
This is really strange, I want to save RecognizedFormCollection
as JSON and pars it back at a later point, and there is no option for deserialization of those data back. There is also a FormField class with internal constructor and so on. And how your `.AsList` will work on all the classes when all subclasses have internal constructors.

**Comment by jacob-hutchings** [comment]
It appears we can serialize a `RecognizedFormCollection`, but not deserialize it.

We are wanting to create a flow that can work with a `RecognizedFormCollection` created from either `FormRecognizerClient` or from a JSON string. 

Recreating the structure of `RecognizedForm` is not ideal.

**Comment by maririos** [comment]
>Recreating the structure of RecognizedForm is not ideal.

For sure. That is why the SDK is in charge of that. So the user doesn't have to.

I am re-opening the issue and will add it to triage.

**Comment by maririos** [comment]
Removed the tags that trigger that comment as now we are waiting on triaging this issue

**Comment by maririos** [comment]
@kinelski as he might have more context of where this is at

**Comment by ckpearson** [comment]
Hi has there been any update on this? We're using document intelligence and our processing pipeline may need to run multiple times, but there's no sense in hitting the endpoint multiple times for the same input file.

At the moment we're extracting a subset of the information on `AnalyzeResult` but it's a pain having to create duplicate types and do the mapping, as others have mentioned serialisation is just fine, but deserialising the response (stored somewhere) currently isn't possible.
