### ISSUE TITLE
Missing classes in Azure.AI.TextAnalytics .Net SDK in 5.1.0-Beta.7

### ISSUE THREAD

**Issue by Rathanavel** [Azure/azure-sdk-for-net#21986]
**Query/Question**
ExtractKeyPhrasesAction, RecognizeEntitiesAction, and AnalyzeActionsOperation are not available, but the below document says otherwise. how to resolve it?
Documentation URL: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/samples/Sample_AnalyzeActions.md

**Environment:**
 - 5.1.0-Beta.7 "Azure.AI.TextAnalytics" 
 - .Net core 3.1
 - IDE and version : Visual Studio 16.3.x

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Hi @Rathanavel ,
Apologies for the confusion. What you are seeing is a mismatch between what we released in version `5.1.0-beta.7` and the current development in the `main` branch which is pointing to `5.1.0-beta.8` as you can see here. https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/src/Azure.AI.TextAnalytics.csproj#L5

This new version is adding the classes and includes other renames too that you can check in the changelog here: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/CHANGELOG.md#510-beta8-unreleased

Note that the `5.1.0-beta.8` version has not been released in NuGet.

A good way to always make sure you are looking at the documentation for the specific library version you are using is to use the release tag (which includes the version). For that case, the sample for actions is https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.TextAnalytics_5.1.0-beta.7/sdk/textanalytics/Azure.AI.TextAnalytics/samples/Sample_AnalyzeBatchActions.md

Let me know if that helps.

**Comment by maririos** [comment]
Great!

The stable release will be as close as possible to `5.1.0-beta.8` :)
