### ISSUE TITLE
[BUG] AzureBlobXmlRepository 

### ISSUE THREAD

**Issue by dnsoftpl** [Azure/azure-sdk-for-net#21987]
Hello 
I found bug (or inconsistency) when 2 types of Data Protection Xml Repository is used. 
 **FileSystemXmlRepository** and **AzureBlobXmlRepository**

Steps:
1. Application A hosted on premise generates the key using FileSystemXmlRepository.
2. Distribite key from disc to Azure Storage 
3. Application B tries to read this key using AzureBlobXmlRepository.
4, Data protector could not find any key and that is why we could not authorize request. 

This is how they read keys differently:
![image](https://user-images.githubusercontent.com/11705751/122669970-e96b1580-d1bf-11eb-9a55-b505a730b089.png)

When I changed key file structure (like below) everythink is working fine.

< keys >
  < key >< /key >
< /keys >

Instead of 

< key >
< /key >

I think this is the root cause.  
![image](https://user-images.githubusercontent.com/11705751/122670128-a1002780-d1c0-11eb-8859-e4be2919f164.png)

Best regards

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
FileSystemXmlRepository and AzureBlobXmlRepository were not designed to allow key migration. The larger difference is that in file system keys are stored with a single key per file while in blob all keys are in the same blob. Supporting this kind of migration would require a tool that would merge keys into a single blob.

**Comment by dnsoftpl** [comment]
As I understood we can transform keys structure on our own then upload to storage account container. Thank you very much.

**Comment by dnsoftpl** [comment]
However I got one more question. Why you designed that to store all keys in one file? Could not pass SAS token to container with READ,WRITE permissions and files could be created.

**Comment by pakrym** [comment]
It's cheaper and faster to download a single blob during the app startup than to scan the container and download many tiny blobs.

**Comment by dnsoftpl** [comment]
Ok thank you for explanation. I am closing the ticket.
