### ISSUE TITLE
TenantId and userName not present in the Powershell test framework

### ISSUE THREAD

**Issue by shuagarw** [Azure/azure-sdk-for-net#2201]
It was present in hydra test framework. Used to be available in environment.AuthResult.

**Comment by shuagarw** [comment]
Mark suggested a workaround to have userName and tenantId set as environment variables for now to unblock but needs to be fixed.

**Comment by hovsepm** [comment]
Fixed in AutoRest branch. Added to PS with https://github.com/Azure/azure-powershell/pull/2616 PR
