### ISSUE TITLE
Search SDK: MergeOrUpload - skip nullable properties

### ISSUE THREAD

**Issue by andemt** [Azure/azure-sdk-for-net#22016]
**Query/Question**
Hi, we have duplicate sources populating/updating Azure Search Index.

Source 1 is updating the index with MergeOrUpload with all properties filled out for our typed model, except for PopularityScore.

```
public class IndexModel
{
       [SimpleField(IsKey = true, IsFilterable = true)]
       public string Id { get; set; }

       [SimpleField(IsFilterable = true, IsSortable = true, IsFacetable = true)]
       public double? PopularityScore { get; set; }

       //.... more properties
}
```

Source 2 is updating with Merge, ie:
```
SearchDocument() 
{ 
       [Id] = "123", 
       ["PopularityScore"] = 4.5 
}
```
1. We are populating/updating with source 1
2. Source 2 is updating popularity score
3. Source 1 is updating again.

When we update our index in step 3, PopularityScore ends up null. 

How do we update the index from source 1 without ending up with PopularityScore is NULL? (with typed model)

**Environment:**
Azure.Search.Documents 11.2.0

**Comment by andemt** [comment]
Oh, yeah, we are using c# framework 4.6.2.

Found a solution.  Upgraded System.Text.Json to 5.0.2 (before 4.x.x).
Added JsonIgnore-attribute to my property.

```
public class IndexModel
{
       [SimpleField(IsKey = true, IsFilterable = true)]
       public string Id { get; set; }
       
       [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]  // Condition is new in 5.x
       [SimpleField(IsFilterable = true, IsSortable = true, IsFacetable = true)]
       public double? PopularityScore { get; set; }

       //.... more properties
}
```

But then FieldBuilder() didn't include my field
```
SearchFields = new FieldBuilder().Build(typeof(IndexModel));
```

So I had to "hack" the fields.
```
       SearchFields = new FieldBuilder().Build(typeof(IndexModel));

       const string name = nameof(IndexModel.PopularityScore);

       if (SearchFields.FirstOrDefault(x => x.Name.Equals(name)) != null)
              return fields;

       SearchFields.Add(new SearchField(name, SearchFieldDataType.Double)
       {
              IsFacetable = true,
              IsSortable = true,
              IsFilterable = true,
       });
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Mohit-Chakraborty** [comment]
@andemt, glad you found a solution. Is there another issue we can look into that is blocking your scenarios?
