### ISSUE TITLE
[FEATURE REQ] Ability to filter pipeline runs by list of RunId

### ISSUE THREAD

**Issue by stevendarby** [Azure/azure-sdk-for-net#22025]
Microsoft.Azure.Management.DataFactory
 
We need to be able to query for pipeline runs using a list of RunIds. Currently it appears the only way to do this is to individually query each pipeline run using `client.PipelineRuns.GetAsync`. The `QueryByFactoryAsync` looks promising for querying multiple pipeline runs but `RunId` is not one of the filters you can use. 

I tried `RunGroupId` (not entirely sure of the purpose of this, but it seems to match the value of `RunId` in results), however I got a CloudException with the message: `Filter operand 'RunGroupId' does not support and array of values. Make sure to provide only one.` (Note the 'and` instead of 'an' typo in this btw)

This is a multitenant data factory which contains runs for many tenants. We store a list of of run IDs for tenants in our system, so being able to query these efficiently for a given tenant would be incredibly beneficial. 

Say we have 100 tenants, each has 250 run IDs stored, and a given tenant wants to query their 250 pipeline runs.

Currently we are making 250 API calls using `GetAsync`. I can do some of these in parallel. First problem is socket exhaustion, so have to mitigate this by taking control of the HttpClient and ensuring not too many connections are created at once. Second problem is rate limiting and getting 429 responses. Limited to 1000 calls per minute so if customer does this query more than 4 times in a minute - forgetting about tenants doing this in parallel for a moment - we get errors. Not nice for customer.

Alternative option: query all runs for all tenants and then filter to the run IDs in memory after the API call. But consider page size is 100 and we have 100 tenants, each having 250 runs. We have to make 250 calls to page through all runs, and these can't be parallelised.

If we could query by a list of Run IDs that we have stored - or the Tenant ID parameter value that is a parameter on each run - that would really help. With given examples we would just have to make 3 calls to page through a tenant's 250 runs and rate limiting is no longer a problem.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by shawnxzq** [comment]
@stevendarby Thanks for your feedback. 
Currently our API model is focus on the primitive (CRUD) APIs. These are the building blocks that we can use to build whatever desired model. In this case, we can – and should – invoke the get API multiple times. This is a much more scalable model, with retry logic and request time per API. An API like this would have to be async and paged to scale. We would probably get better performance with parallel sync calls instead of one long async operation.

**Comment by stevendarby** [comment]
@shawnxzq the problem as mentioned is we are hitting 429s frequently. 

We work with Microsoft for solutions and have been led into a solution that Microsoft can’t support.

**Comment by shawnxzq** [comment]
@LijuanZ For awareness.

**Comment by shawnxzq** [comment]
@LijuanZ We can track this as new requirement in our backlog, thanks!

**Comment by LijuanZ** [comment]
@shawnxzq query by a collection of runIds are not supported today. I can add it to backlog but it will take time to add the support based on priority. @stevendarby you mentioned there are multiple tenants within the factory, are there any common info for the runs for a tenant? If the pipelineName is the same for tenant, you can consider query by pipeilne name.

**Comment by stevendarby** [comment]
The pipelines in the factory are shared by all tenants. The pipelines have a tenant parameter when running. So filtering by pipeline name is not an option. Filtering by parameter value would be an alternative to the main idea proposed here.

**Comment by shawnxzq** [comment]
@LijuanZ Thanks for the update, please create backlog item to track and we can close the issue here. 

@stevendarby As we will have internal backlog to track the requirement, we will close this issue later, thanks!

**Comment by LijuanZ** [comment]
@shawnxzq yes, I've created backlog item to track, thanks!

**Comment by stevendarby** [comment]
@shawnxzq @LijuanZ thanks, will this issue be updated if the feature is ever implemented or do we need to keep an eye on release notes? Have you assessed priority yet and able to give any indication of when it might be implementated? Would you be interested to know the organisation (the Microsoft customer) this impacts in case that affects priority?

**Comment by shawnxzq** [comment]
@stevendarby Thanks for your ask, you can check our swagger or SDK, or create customer case to us to check the status, we will close this feature request here for now, thanks!

**Comment by stevendarby** [comment]
Can you provide links to the swagger or SDK?

Are you able to give an update on your internal backlog item's status/priority? Thank you!
