### ISSUE TITLE
[BUG]DefaultAzureCredential / EnvironmentCredential  doesn't have an option to set ClientCertificateCredentialOptions.SendCertificate

### ISSUE THREAD

**Issue by yangyud-cn** [Azure/azure-sdk-for-net#22031]
**Describe the bug**
When we use DefaultAzureCredential and then set the AZURE_CLIENT_CERTIFICATE_PATH,  it fails to authenticate to AAD because the Application is only enabled Subject Name + Issuer authentication and the hardcoded behavior of EnvironmentCredential is set ClientCertificateCredentialOptions to null.

**Expected behavior**
We should have an option to allow ClientCertificateCredentialOptions.SendCertificate to be set to true when using DefaultAzureCredential / EnvironmentCredential.  

**Actual behavior (include Exception or Stack Trace)**
There's no such code path that we can do it today.

**To Reproduce**
As is.

**Environment:**
 - Azure.Identity, Version="1.3.0"
 -  Service Fabric Local dev + Windows 10, .Net Core App 3.1
 - Visual Studio 16.5

**Comment by christothes** [comment]
Hi @yangyud-cn - Could you try constructing a `ChainedTokenCredential` that includes a [ClientCertificateCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.clientcertificatecredential?view=azure-dotnet) (among the other credentials you prefer)? This would allow you to configure the options fully.

**Comment by yangyud-cn** [comment]
@christothes, as a work around I can do it but the idea here is to make sure we could reuse existing things as much as possible.

**Comment by christothes** [comment]
Hi @yangyud-cn `DefaultAzureCredential` is meant to be used as a simple default option that works for most scenarios. You can think of `ChainedTokenCredential` as an advanced version of `DefaultAzureCredential` that allows you to configure it with full control. 

In your case, you wouldn't add `DefaultAzureCredential` to the `ChainedTokenCredential`, rather each specific credential you want in the chain. For example:

```c#
var credential = new ChainedTokenCredential(
    new ManagedIdentityCredential(),
    new EnvironmentCredential(),
    new AzureCliCredential(),
    new ClientCertificateCredential(new ClientCertiificateCredentialOptions{ <...>}),
    new VisualStudioCredential());

```

**Comment by yangyud-cn** [comment]
@christothes,  sorry for the late reply.  ```ChainedTokenCredential``` requires each credential to be not null, and ```ClientCertificateCredential``` requires all basic arguments to be valid on ctor, while ```EnvironmentCredential``` provides a safe fall back in the case where env variables are not set.    So I will have to write my own ```EnvironmentCredential``` to not throw in the case of missing env variable and to return ```ClientCertificateCredential```  when we have the env variables.

**Comment by christothes** [comment]
@yangyud-cn - I think you may get the behavior you want with ChainedTokenCredential using just these credentials:

```C#
var options = new ClientCertificateCredentialOptions { SendCertificateChain = true };
var credential = new ChainedTokenCredential(
    new ManagedIdentityCredential(),
    new EnvironmentCredential(options));
```

The logic of the EnvironmentCredential already has conditional logic to use the certificate credential if the `AZURE_CLIENT_CERTIFICATE_PATH` environment variable is set, and the `ChainedTokenCredential` has the logic to try the MSI first and fallback to the `EnvironmentCredential` when it is not available.

**Comment by yangyud-cn** [comment]
@christothes Thanks for the update. I missed that ```EnvironmentCredential``` can take options :)

**Comment by abatishchev** [comment]
+1.

`DefaultAzureCredentialOptions` already exposed a bunch of underlying credentials specific properties. 
Basically one the most important for each of them. But it doesn't expose anything for certificate based auth, and `SendCertificateChain` is exactly one.

I'm willing to work on a pull request if it'll be considered.

Otherwise I'll file a pull request to remove all custom properties, because it's black and white: either they 
all belong to `DefaultAzureCredentialOptions` or none do.

**Comment by abatishchev** [comment]
@yangyud-cn please reopen the issue.
