### ISSUE TITLE
Must set (Microsoft.Azure.Management.Compute.Models.VirtualMachine).Extensions to null before calling (Microsoft.Azure.Management.Compute.ComputeManagementClient).CreateOrUpdate()

### ISSUE THREAD

**Issue by DrEsteban** [Azure/azure-sdk-for-net#2205]
I'm writing a simple app that transfers ownership of a DataDisk from one VM to another programmatically.  So, my pseudo-code looks like:

`ComputeManagementClient client = new ComputeManagementClient(creds);`
`var vm1 = client.VirtualMachines.Get(ConfigurationManager.AppSettings["ResourceGroup"], ConfigurationManager.AppSettings["VM1ResourceName"]).VirtualMachine;`
`var vm2 = client.VirtualMachines.Get(ConfigurationManager.AppSettings["ResourceGroup"], ConfigurationManager.AppSettings["VM2ResourceName"]).VirtualMachine;`

`DataDisk disk = vm1.StorageProfile.DataDisks.First(x => x.Name == ConfigurationManager.AppSettings["VHDName"]);`
`vm1.StorageProfile.DataDisks.Remove(disk);`
`vm2.StorageProfile.DataDisks.Add(disk);`

`client.VirtualMachines.CreateOrUpdate(ConfigurationManager.AppSettings["ResourceGroup"], vm1);`
`client.VirtualMachines.CreateOrUpdate(ConfigurationManager.AppSettings["ResourceGroup"], vm2);`

The call to CreateOrUpdate fails with:

> An unhandled exception of type 'Hyak.Common.CloudException' occurred in Microsoft.Threading.Tasks.dll
> 
> Additional information: InvalidRequestContent: The request content was invalid and could not be deserialized: 'Could not find member 'resources' on object of type 'ResourceDefinition'. Path 'resources', line 37, position 15.'.

It seems a little ridiculous that I can't simply update the exact same object that was retrieved with the Get() call... I must manually set the Extensions properties to null, to clear out the 'resources' section of the schema.  Seems like bad design to me, because it requires the developer to have a deep understanding of the underlying JSON schema of the API, which doesn't sound very abstracted to me :)

**Comment by rosshinkley** [comment]
+1, I'm also having this problem.  For v14.0.0-prerelease, the `Resources` field needs to be set to null, and is unfortunately a protected set.  To set it to `null`, you'll need to use reflection:

```c#
var resourceMember = typeof(VirtualMachine).GetProperty("Resources");
resourceMember.SetValue(virtualMachine, null);
```

**Comment by Petermarcu** [comment]
Sorry there was no response on this. At this point the issue is quite old and the library is up to version 28 with completely different implementation so it's unclear whether this issue will still happen. If you move to the newest version and still hit this, please open a new issue with all the details. 
https://www.nuget.org/packages/Microsoft.Azure.Management.Compute/
