### ISSUE TITLE
[BUG] Azure.Monitor.OpenTelemetry.Exporter depreciated or supposed to work?

### ISSUE THREAD

**Issue by DanialK** [Azure/azure-sdk-for-net#22077]
**Query/Question**
I'm hoping to be using `<PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc5" />` (which is the latest at the time of writing) and want to push my logs and traces to App insights on azure. The latest version of `Azure.Monitor.OpenTelemetry.Exporter` is currently `1.0.0-beta.1` and most of the extension methods don't work as things seem to have been moved.

Use case 1: Tracing
```
                    builder.AddAzureMonitorTraceExporter(options =>
                    {
                        options.ConnectionString = "";
                    });
```
following code builds but gives the following error at runtime 
```
  Startup.cs(169, 21): [CS7069] Reference to type 'TracerProviderBuilder' claims it is defined in 'OpenTelemetry', but it could not be found
```

Use case 2: exporting logs
```
                .ConfigureLogging((context, builder) =>
                {
                    ...
                    builder.AddOpenTelemetry(options =>
                    {
                        options.AddAzureMonitorLogExporter();
                    });
                });
```
this code doesn't compile as it is unable to find  `AddAzureMonitorLogExporter`, it seems like some files have moved but also 
[AzureMonitorExporterLoggingExtensions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/AzureMonitorExporterLoggingExtensions.cs) seem to be internal for some reason?

Is this library being depreciated or still supposed to work? do you have alternative suggestions?
Could you please make those public and create a new nuget release

**Environment:**
 - Name and version of the Library package used:  <PackageReference Include="Microsoft.OpenTelemetry.Exporter.AzureMonitor" Version="1.0.0-beta.1" />
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 
 ```
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  2.2.207 [/usr/local/share/dotnet/sdk]
  2.2.401 [/usr/local/share/dotnet/sdk]
  3.1.301 [/usr/local/share/dotnet/sdk]
  3.1.406 [/usr/local/share/dotnet/sdk]
  5.0.102 [/usr/local/share/dotnet/sdk]
  5.0.103 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by reyang** [comment]
This is being addressed by #22017.

**Comment by DanialK** [comment]
Thanks @jsquire and @reyang 
Have you had the chance to publish the latest version? I can still only see  1.0.0-beta.2
![image](https://user-images.githubusercontent.com/2878450/128444308-ef5b484b-0883-461f-8291-962c90e9cc71.png)

**Comment by reyang** [comment]
Next version is expected to come around late Oct. this year.

**Comment by hejingkan2005** [comment]
@reyang , I'm already with Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.3 (released on Oct. 5th), but it looks that I still could not locate extension method AddAzureMonitorLogExporter() as it's internal, any reason for it?

**Comment by TimothyMothra** [comment]
@hejingkan2005 beta3 was released in Oct 2021.
Our team is currently preparing to release beta4, targeting Friday Oct 7, 2022.
`AddAzureMonitorLogExporter` will be available in beta4.

We've recently updated our [Readme](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter).
There you'll find instructions to get our nightly builds which would let you test the LogExporter today.
You'll also find links to our Demo app which gives a basic example to help you get started.

**Comment by hejingkan2005** [comment]
@TimothyMothra , there is one more question here. Is it correct to understand another extension method `AddAzureMonitorMetricExporter` would be Public available as well along with  `AddAzureMonitorLogExporter` in beta4 release?

**Comment by TimothyMothra** [comment]
> @TimothyMothra , there is one more question here. Is it correct to understand another extension method `AddAzureMonitorMetricExporter` would be Public available as well along with `AddAzureMonitorLogExporter` in beta4 release?

@hejingkan2005 yes, an `Add` method will be public for Traces, Metrics, and Logs.
You can evaluate this today by getting the latest nightly build or checking out this repo and reviewing our Demo app linked in the [Readme](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter).

**Comment by TimothyMothra** [comment]
Beta4 was just released. It generally takes nuget an hour to make a new package available.
https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.Exporter/1.0.0-beta.4
