### ISSUE TITLE
[QUERY] Add samples for Azure.ResourceManager.CosmosDB

### ISSUE THREAD

**Issue by ThomasWeiss** [Azure/azure-sdk-for-net#22099]
The repo doesn't contain any sample showing how to use the Azure.ResourceManager.CosmosDB library, which makes it difficult for new users to get started.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
@ThomasWeiss, thanks for the input!!

We are currently still working on track 2 (Azure.ResourceManager.xxx) SDKs. The current code base will be refreshed with a new API shape. For now, you could reference the test code to see the usage. If you have any specific scenarios, please post them here and we can provide examples.

**Comment by allenjzhang** [comment]
Adding folks from CosmosDB. In the meantime, the test code in the repo could provide certain samples of the API usage in a pinch.

**Comment by MehaKaushik** [comment]
Thomas is a member of CosmosDB Service team. I believe what is asked here is proper docs for customers. @allenjzhang if there is any support needed from CosmosDB team, we will be happy to provide. Please let us know.

For now I am closing this issue and I would follow up offline with Allen and team, who developed the module.
