### ISSUE TITLE
UploadAsync(Stream) will throw an exception if the blob exists.

### ISSUE THREAD

**Issue by KarlZ** [Azure/azure-sdk-for-net#22100]
For UploadAsync with a string it states correctly:
_The UploadAsync(String) operation creates a new block blob or throws if the blob already exists._
It should say the same thing for UploadAsync(Stream), but instead, states:
_The UploadAsync(Stream) operation creates a new block blob or updates the content of an existing block blob. Updating an existing block blob overwrites any existing metadata on the blob._
And of course the comments in the code are wrong too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84dd6a0a-8ef5-bb23-6498-a6a6b75995c7
* Version Independent ID: 236218cc-38cb-0067-5cbf-1d36f63bbddf
* Content: [BlobClient.UploadAsync Method (Azure.Storage.Blobs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet&source=docs)
* Content Source: [xml/Azure.Storage.Blobs/BlobClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs/BlobClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Also reported by #18381

**Comment by amnguye** [comment]
Will work to update all the upload methods with better documentation to provide more clarity about overwriting or no overwriting.

**Comment by navba-MSFT** [comment]
@KarlZ  Thanks for your question. The same issue was reported in #18381 too and @amnguye has confirmed that this issue is now fixed in this PR #24984.

Please let me know if you are still facing this issue. Awaiting your reply and confirmation.

**Comment by navba-MSFT** [comment]
@KarlZ This is a quick follow-up to check if you need any further assistance on this issue. Awaiting you reply.

**Comment by tscbp** [comment]
Confirming documentation still incorrect as of 12.12.0.  Example: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L399 - 
```The <see cref="UploadAsync(Stream)"/> operation creates a new block blob
        /// or updates the content of an existing block blob.```
This comment is incorrect, an exception is thrown if the blob exists.

**Comment by Bellarmine-Head** [comment]
This just tripped me up.  Documentation still wrong as of Azure.Storage.Blobs 12.14.1

**Comment by seanmcc-msft** [comment]
The documentation has been clarified:
