### ISSUE TITLE
Remove unused snippets for keyvault

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#22126]
Please remove these snippets or remove the `#region Snippet:<snippet name>` or use them in a markdown file.

keyvault: Snippet:CreateKeyVaultAccessControlClient
keyvault: Snippet:GetRoleDefinitions
keyvault: Snippet:ReadmeCreateRoleAssignment
keyvault: Snippet:KeysSample4DeleteKey
keyvault: Snippet:KeysSample5DeleteKeys
keyvault: Snippet:KeysSample6DeleteKey

**Comment by heaths** [comment]
This was completed some time ago.
