### ISSUE TITLE
Event Hubs: Remove unused snippets

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#22123]
Please remove these snippets or remove the `#region Snippet:<snippet name>` or use them in a markdown file.

eventhub: Snippet:EventHubs_ReadMe_ReadPartition
eventhub: Snippet:EventHubs_SamplesCommon_ProducerBasicConfig
eventhub: Snippet:EventHubs_Processor_Sample03_ErrorHandlerExceptionHandling

**Comment by jsquire** [comment]
Thanks for this!    Out of curiosity, how did you mismatch them?

**Comment by christothes** [comment]
> Thanks for this! Out of curiosity, how did you mismatch them?

It's an update to Snippet Generator (and Update-Snippets.ps1) https://github.com/Azure/azure-sdk-for-net/pull/22090

![](https://media.giphy.com/media/l0MYw6Cu1TfY3gsWk/giphy.gif)
