### ISSUE TITLE
Remove unused snippets for iot

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#22125]
Please remove these snippets or remove the `#region Snippet:<snippet name>` or use them in a markdown file.

iot: Snippet:IotHubCreateDeviceIdentities
iot: Snippet:IotHubUpdateDeviceIdentities
iot: Snippet:IotHubUpdateDeviceTwins
iot: Snippet:IotHubDeleteDeviceIdentities
iot: Snippet:IotHubGetDeviceIdentities
iot: Snippet:IotHubGetDeviceTwins
iot: Snippet:IotHubCreateModuleIdentities
iot: Snippet:IotHubUpdateModuleIdentities
iot: Snippet:IotHubUpdateModuleTwins
iot: Snippet:IotHubDeleteModuleIdentities
iot: Snippet:IotHubGetModuleIdentities
iot: Snippet:IotHubGetModuleTwins
iot: Snippet:IotHubCreateConfiguration
iot: Snippet:IotHubGetConfiguration
iot: Snippet:IotHubUpdateConfiguration
iot: Snippet:IotHubDeleteConfiguration
iot: Snippet:IotHubImportJob
iot: Snippet:IotHubExportJob
iot: Snippet:GetImportExportJob
iot: Snippet:IotInvokeMethodOnModule
iot: Snippet:IotInvokeMethodOnDevice
iot: Snippet:IotHubCreateModuleIdentity
iot: Snippet:IotHubGetModuleIdentities
iot: Snippet:IotHubGetModuleIdentity
iot: Snippet:IotHubUpdateModuleIdentity
iot: Snippet:IotHubGetModuleTwin
iot: Snippet:IotHubUpdateModuleTwin
iot: Snippet:IotHubDeleteModuleIdentity
iot: Snippet:IotHubQueryDeviceTwins
iot: Snippet:IotHubQueryModuleTwins
iot: Snippet:IotHubGetDeviceStatistics
iot: Snippet:IotHubGetServiceStatistics

**Comment by timtay-microsoft** [comment]
@christothes which file are you seeing this snippets in?

**Comment by christothes** [comment]
Running `eng/scripts/Update-Snippets.ps1` should give you the latest list - it's possible these are stale now.

**Comment by jamdavi** [comment]
@christothes These snippets are part of an in progress SDK is there a way to get an exception? 

Instead of removing these snippets I could just put them in a blanket "placeholder.md" if that's an acceptable solution.

**Comment by christothes** [comment]
> @christothes These snippets are part of an in progress SDK is there a way to get an exception?
> 
> Instead of removing these snippets I could just put them in a blanket "placeholder.md" if that's an acceptable solution.

Why not just comment out the #region line until you are ready to incorporate them into a markdown file?
