### ISSUE TITLE
Remove unused snippets for textanalytics

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#22133]
Please remove these snippets or remove the `#region Snippet:<snippet name>` or use them in a markdown file.

textanalytics: Snippet:TextAnalyticsSampleHealthcare
textanalytics: Snippet:TextAnalyticsSampleHealthcareAsync
textanalytics: Snippet:RecognizeHealthcareEntitiesAsyncAutomaticPolling
textanalytics: Snippet:TextAnalyticsSampleHealthcareAsyncCancellation
textanalytics: Snippet:RecognizeHealthcareEntitiesAsyncAutomaticPolling
textanalytics: Snippet:RecognizeHealthcareEntitiesAsyncManualPolling
textanalytics: Snippet:TextAnalyticsSampleHealthcareCancellation
textanalytics: Snippet:Sample7_AnalyzeHealthcareEntities_ManualPolling
textanalytics: Snippet:TextAnalyticsAnalyzeOperation
textanalytics: Snippet:AnalyzeOperationBatchAsync
textanalytics: Snippet:AnalyzeOperationConvenience

**Comment by heaths** [comment]
This was completed some time ago. I did double check all these as well, but `Update-Snippets.ps1 textanalytics -StrictMode` also yields no errors.
