### ISSUE TITLE
[BUG] Missing deserialization of LeaseStatus in Azure.Storage.Blobs.BlobExtensions.ToBlobDownloadStreamingResult

### ISSUE THREAD

**Issue by egraff** [Azure/azure-sdk-for-net#22144]
**Describe the bug**
`Azure.Storage.Blobs.BlobExtensions.ToBlobDownloadStreamingResult()` does not populate the `BlobDownloadDetails`'s `LeaseState` from the response headers object. It _does_ set the `LeaseState` and `LeaseDuration`:
https://github.com/Azure/azure-sdk-for-net/blob/0c9f9efe68533703bc7f608f7394e0c2c992d205/sdk/storage/Azure.Storage.Blobs/src/BlobExtensions.cs#L872-L873
but is missing something like:
```csharp
LeaseStatus = response.Headers.LeaseStatus.GetValueOrDefault()
```

This is a regression introduced in https://github.com/Azure/azure-sdk-for-net/commit/1814567d1f6cfb4905539e71d54377ab46ed6737.

As a result of this, the `BlobDownloadDetails` you get after doing e.g. `BlobBaseClient.DownloadAsync()` returns a `LeaseStatus` that is always equal to `LeaseStatus.Locked` (since this is the default value of the enum).

**Expected behavior**
The `BlobDownloadDetails` should contain a `LeaseStatus` that reflects the value of the `x-ms-lease-status` header from the "Get Blob" HTTP response.

**Actual behavior (include Exception or Stack Trace)**
`BlobDownloadDetails` always contains a `LeaseStatus` equal to `LeaseStatus.Locked`.

**To Reproduce**
```csharp
/* Pseudo-code */
BaseBlobClient blobClient = GetClientForUnlockedBlob();
Response<BlobDownloadInfo> downloadResponse = await blobClient.DownloadAsync().ConfigureAwait(false);
Assert.That(downloadResponse.Value.Details.LeaseStatus, Is.EqualTo(LeaseStatus.Unlocked));
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.9.0 (issue is not present in Azure.Storage.Blobs 12.8.4)

**Comment by amishra-dev** [comment]
@seanmcc-msft Sean, could you please look at this one.

**Comment by seanmcc-msft** [comment]
Hi @egraff, I can repo this issue, and will work to address it shortly.

Thanks for reporting this!

-Sean
