### ISSUE TITLE
[BUG] CheckExistenceById throws 400 Bad Request

### ISSUE THREAD

**Issue by nobody-msft** [Azure/azure-sdk-for-net#22153]
**Describe the bug**
I'm trying to check if an Azure resource exists by it's full Id, but I always get back a 400 bad request from ARM when using the ResourcesManagementClient class.

**Expected behavior**
The response should return either 404 or 204, depending on if the resource exists

**Actual behavior (include Exception or Stack Trace)**
ARM always returns 400 Bad Request

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```CSharp
// Make sure you run "az login" and set your account to the proper subscription before running this code.
string subscriptionId = "YourSubscriptionid"
string resourceId = $"/subscription/{subscriptionId}/...." // Full resource id here
var resourceManagementClient = new ResourcesManagementClient(subscriptionId , new AzureCliCredential());
var response = resourceManagementClient.Resources.CheckExistenceById(resourceId, "2021-04-01"); // latest API version

// The above line throws a RequestFailedException
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0]: Azure.ResourceManager.Resource 1.0.0-preview.2
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]:
```
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.204
 Commit:    84d1fe1bb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.204\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  3.1.410 [C:\Program Files\dotnet\sdk]
  5.0.204 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]: Visual Studio Code 1.57.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@HarveyLink please help on this issue

**Comment by HarveyLink** [comment]
Hi @nobody-msft ,
Azure.ResourceManager.Resource 1.0.0-preview.2 has been deprecated. You could use our re-designed: [Azure.ResourceManager.Resource](https://www.nuget.org/packages/Azure.ResourceManager.Resources) as a work around. Code will like this:

```
ArmClient armClient = new ArmClient(new DefaultAzureCredential());
Subscription subscription = await armClient.GetDefaultSubscriptionAsync();
var result = await subscription.GetGenericResources().CheckIfExistsAsync("resourceId");
```
