### ISSUE TITLE
[BUG] AzureServiceTokenProvider.GetAccessTokenAsync hangs forever on corpnet domain joined machines with two identities

### ISSUE THREAD

**Issue by MattMcL4475** [Azure/azure-sdk-for-net#22151]
**Describe the bug**
AzureServiceTokenProvider.GetAccessTokenAsync() hangs forever on corpnet domain joined machines with two identities

**Expected behavior**
A token is successfully returned.

**Actual behavior (include Exception or Stack Trace)**
This line of code never returns:

`await new AzureServiceTokenProvider().GetAccessTokenAsync("https://management.azure.com/");`

... and so a token is never returned.  It appears the process Microsoft.Asal.TokenService.exe is hanging in VisualStudioAccessTokenProvider:

"![Microsoft Asal TokenService exe-hang](https://user-images.githubusercontent.com/23408335/123315720-e1bdb080-d4e0-11eb-9aac-a64c349d3ce1.png)"

**To Reproduce**

1.  Use a Windows corpnet-joined machine with two identities (2 x @microsoft.com accounts)
2.  az logout
3.  I've created a console app that repros the issue.  Clone this fork and open this solution:
https://github.com/MattMcL4475/azure-sdk-for-net/blob/6e4398c2690d7d51f3ad369057d233817ee4e1d9/sdk/mgmtcommon/AppAuthentication/AppAuthentication.sln
4.  Set "AppAuth-hang-win" as the startup project and run.  You will see it hang on line 22:
https://github.com/MattMcL4475/azure-sdk-for-net/blob/6e4398c2690d7d51f3ad369057d233817ee4e1d9/sdk/mgmtcommon/AppAuthentication/AppAuth-hang-win/Program.cs
5.  If the console app is published in release mode, this issue still occurs.  So it occurs both when debugging in VS, and also running a published release EXE directly.

![image](https://user-images.githubusercontent.com/23408335/123317077-7379ed80-d4e2-11eb-912a-0af4f011ef37.png)

**Environment:**

Microsoft.Azure.Services.AppAuthentication 1.6.1, and also in latest main branch.
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): 
 - .NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.524 [C:\Program Files\dotnet\sdk]
  2.1.816 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.1.116 [C:\Program Files\dotnet\sdk]
  5.0.204 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 **- IDE and version:** 
Microsoft Visual Studio Enterprise 2019
Version 16.10.2

**Comment by jsquire** [comment]
//cc: @nonik0, @anaismiller

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by nonik0** [comment]
@crmann1 This looks like the VS token service is hanging/slow. Could you take a look?

**Comment by MattMcL4475** [comment]
Met with @crmann1 and the conclusion is that the root cause is that Microsoft.Asal.TokenService.exe process never exits.  Why that is the case is unclear.
