### ISSUE TITLE
[BUG] [AgriFood] `FarmClient` should be named `FarmOperationsClient`

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk-for-net#22156]
In the swagger specification for the service, there is an operation group named `FarmOperations`:

https://github.com/Azure/azure-rest-api-specs/blob/683e3f4849ee1d84629d0d0fa17789e80a9cee08/specification/agfood/data-plane/Microsoft.AgFoodPlatform/preview/2021-03-31-preview/agfood.json#L3156

Since we generate a client per operation group, we would expect that this would create a client type named `FarmOperationsClient` but instead we generated a client named simply `FarmClient`:

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/agrifood/Azure.Verticals.AgriFood.Farming/src/Generated/FarmClient.cs#L17

Suspect the issue here is that "Operations" is a pretty special term and it's getting "cleaned" somewhere in our pipeline.

**Comment by pallavit** [comment]
Closing this issue from the .NET repo and moving it over to the autorest.csharp repo.
