### ISSUE TITLE
[FEATURE REQ] Service bus web jobs extension PeekMessage and ReceiveDeferredMessage with ServiceBusMessageActions 

### ISSUE THREAD

**Issue by akakaule** [Azure/azure-sdk-for-net#22154]
**Library or service name.**
Microsoft.Azure.WebJobs.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
Using Service Bus trigger for Azure Functions with web job extension providing access to IMessageSession which allow for both use of PeekMessage and ReceiveDeferredMessage. Migrating to the new Service Bus SDK and web job extension 5.x it's possible to use ServiceBusMessageActions but it does not provide access to the above two methods. Since ServiceBusMessageActions uses ServiceBusReceiver it should be easy to expose the methods.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @akakaule,
Can you provide context around how you are using these methods inside your function?

**Comment by akakaule** [comment]
> Hi @akakaule,
> Can you provide context around how you are using these methods inside your function?
> 
> The actions are designed to represent the set of actions you can take on a received message. Do you have a use case where you need to receive a specific deferred message whenever a message is received?

We have solution/sdk that relies on IMessageSession where when we are processing a message (session-based) if the consumer cannot process the message then the message stored as failed (by sending the message back into the topic and forwarded to another topic/subscription where it is stored in some storage). We then set the session state marking it as "blocked". When the consumer processed then next message for the same session the session state is checked. If it is marked as "blocked" then the session state is updated and the sequence number of the message is stored in the session state and the message is deferred. It's then possible for the consumer (via a web ui) to reprocess the failed message by resubmitting it again (new copy). When resubmitting a message (specific message type) the session state is checked and the sequence number of the "blocked" message is read and the deferred message is recieved (using  ReceiveDeferredMessageAsync on IMessageSession). A continuation request (another message type) is sent to itself (topic) where the deferred message is retrieved and processed and the process continues until all "blocked" messages have been processed for the given session.

So it's a solution where we can ensure FIFO and if any message fails all other messages are halted for the same session.

The consumer/users of the solution are normally implemented using Azure Function with the web job extension giving us access to the IMessageSession that are also available through the RegisterSessionHandler in the SubscriptionClient that are used for consumers that are .NET console apps etc.

So our solution now have to handle both ServiceBusSessionReceiver and the ServiceBusSessionMessageActions

**Comment by JoshLove-msft** [comment]
Ok so that explains the ReceiveDeferred use case. I'm not sure using the ServiceBusSessionReceiver will even work as you may not be able to lock the session if it is locked by the functions. How are you using Peek?

**Comment by LeszekKalibrate** [comment]
Over one year and this was not brought back yet?
Please bring back this functionality or provide alternative solution in Migration guide - Breaking changes section.

**Comment by akakaule** [comment]
@LeszekKalibrate no unfortunately not and right now make it impossible to migrate to the new SDK.
