### ISSUE TITLE
Re-enable nightly Key Vault tests

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#22179]

**Comment by kurtzeborn** [comment]
Is this going to blow up our test costs again because of HSM?  If so, can we run this less often?  Say weekly maybe?

**Comment by heaths** [comment]
To be clear, these were disabled because of service performance issues. If cost is a concern, we should probably open a new issue to conditionalize our test matrixes. Hypothetically, with the changes @benbp made for matrix generation we probably could run them on weeklies.

On a related note, .NET's "weeklies" are still running both Saturday and Sunday. Shouldn't that just run once? /cc @weshaggard

**Comment by heaths** [comment]
This is done, though we are experiencing a new problem with certificate LROs. Discussing offline with the service team.
