### ISSUE TITLE
Incorporate Monitor Query Beta-2 UX study feedback into August (Beta-3)

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#22188]
Tracking issue to update the August Release to incorporate the TBD Beta-2 UX Study Feedback
/cc @scottaddie

Action items from 7/23 meeting:

- [x] Add a multi-workspace logs query code sample to the _samples_ directory.
- [x] Add an "Advanced scenarios" section to the _README_. Within that section, provide a link to the multi-workspace logs query code sample.
- [x] Add a logs query response object hierarchy tree to the _README_.
- [x] Add a metrics query response object hierarchy tree to the _README_.
- [x] In the resource ID strings in the _README_, replace "Microsoft.OperationalInsights" with a placeholder.
- [x] In the XML docs for `LogsBatchQuery`'s `AddQuery` method, rename the 2 occurrences of the `workspaceId` parameter to `workspace`. https://github.com/Azure/azure-sdk-for-net/blob/c9ce3ed6ad340a64aefde07db55b6251f7c09631/sdk/monitor/Azure.Monitor.Query/src/Models/LogsBatchQuery.cs#L30
- [x] Rename the `MetricQueryResult` class to `MetricsQueryResult`.
- [x] Await Srikanta's response from the service team. If necessary, remove the `PrimaryTable` property of the `LogsQueryResult` class. https://github.com/Azure/azure-sdk-for-net/blob/c9ce3ed6ad340a64aefde07db55b6251f7c09631/sdk/monitor/Azure.Monitor.Query/src/Models/LogsQueryResults.cs#L27
- [x] Test the display of IntelliSense code samples in VS 2022 (Dev 17) Preview 2. Per the email from Mika Dumont, add CDATA sections where necessary to preserve spacing.

**Comment by joshfree** [comment]
@pakrym could you update this issue?

**Comment by pakrym** [comment]
Done, only model hierarchy is left.

**Comment by joshfree** [comment]
@nisha-bhatia can you make sure these final changes make it into this month's final beta release?

**Comment by nisha-bhatia** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/23934
