### ISSUE TITLE
Finish Monitor Query Samples for the 7 example scenarios

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#22186]
Tracking issue to ensure Monitor Query Beta-2 includes samples for the following seven (7) scenarios

1.  Get an auth token to talk to the service  
2.  Make a simple query to the service "requests | summarize count() by bin(timestamp, 1h)", "timestamp = P1D"
3.  Get the results in tabular form
4.  Get the results in key-value form
5.  Use $batch to run 5 queries in 1 api call
6.  Run a more complex query (demo how to increase server timeout)
7.  Get query statistics (cpu usage / memory / execution time)

**Comment by joshfree** [comment]
@pakrym is this still active by accident?

**Comment by pakrym** [comment]
Adding the last scenario in an open PR.
