### ISSUE TITLE
Add Missing Performance Tests for Monitor Query

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#22189]
Add performance tests for

1) Making a simple query to the service "requests | summarize count() by bin(timestamp, 1h)", "timestamp = P1D"
2) Use $batch to run 5 queries in 1 api call
3) Get query statistics (cpu usage / memory / execution time)

**Comment by joshfree** [comment]
@pakrym could you follow up on this issue?

**Comment by joshfree** [comment]
Related https://github.com/Azure/azure-sdk-for-python/pull/19941 and https://github.com/Azure/azure-sdk-for-java/pull/23280

**Comment by pakrym** [comment]
Not done yet. Reassigned to @nisha-bhatia
