### ISSUE TITLE
[Event Hubs] Incorrect description for `EventProcessorOptions`

### ISSUE THREAD

**Issue by felipepessoto** [Azure/azure-sdk-for-net#22193]
I believe this statement is incorrect:

 EventProcessorHost will call IEventProcessor.OnEvents(null)

There is no IEventProcessor.OnEvents. And it doesn't call the ProcessEventsAsync with null argument, it sends a empty Enumerable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53e538ca-4c3d-d328-9559-cdd0ee59daf2
* Version Independent ID: b81b04ae-6a7d-1dca-28b9-672a678eb838
* Content: [EventProcessorOptions.InvokeProcessorAfterReceiveTimeout Property (Microsoft.Azure.EventHubs.Processor) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor.eventprocessoroptions.invokeprocessorafterreceivetimeout?view=azure-dotnet#Microsoft_Azure_EventHubs_Processor_EventProcessorOptions_InvokeProcessorAfterReceiveTimeout)
* Content Source: [xml/Microsoft.Azure.EventHubs.Processor/EventProcessorOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.EventHubs.Processor/EventProcessorOptions.xml)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ramya-rao-a** [comment]
@serkantkaraca, Any thoughts here?

**Comment by serkantkaraca** [comment]
I will submit a PR for XMLDoc fix.

**Comment by serkantkaraca** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/23991

**Comment by ramya-rao-a** [comment]
Thanks for reporting @felipepessoto 

We have updated the docs in https://github.com/Azure/azure-sdk-for-net/pull/23991

The package in question `Microsoft.Azure.EventHubs.Processor` is currently deprecated. Therefore this doc change will roll out the next time we have critical bug fix to ship for this deprecated package.

We highly encourage you to use the newer `Azure.Messaging.EventHubs` and `Azure.Messaging.EventHubs.Processor` packages instead. Please refer to the [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md) for more details.
