### ISSUE TITLE
Update Monitor Query Samples, Quickstarts, and Documentation based on final consistency review

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#22191]
Tracking issue to update all Samples and related documentation based on the final September Release consistency review 
/cc @scottaddie

- [ ] Move DateTimeRange to Azure Monitor Query
- [ ] Throw exception on partial error
- [ ] Add new option in LogsQueryOption to disable throwing exception on partial error
- [ ] Include an enum LogsQueryResultStatus in LogsQueryResult to indicate if the result is success, failure or partial failure.
- [ ] Retain code and message only in ResponseError (core type). Remove all other fields and update `ToString()` method to include details available in inner error.

**Comment by joshfree** [comment]
@nisha-bhatia PTAL

**Comment by pakrym** [comment]
Related: https://github.com/Azure/azure-sdk-for-net/issues/23580
