### ISSUE TITLE
RecordMatcher fails with doubles on different runtime versions

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#22219]
I have some doubles in both requests and reponses, and the `RecordMatcher` has a problem with doubles in requests on .NET 5.0 vs older versions. For example, here's what I get in a test that was recorded with .NET 5.0 but used on older runtimes:

```
  Message: 
    Azure.Core.TestFramework.TestRecordingMismatchException : Unable to find a record for the request POST https://wuppe.api.cognitive.microsoft.com/language/:query-knowledgebases?projectName=190a9e13-8ede-4e4b-a8fd-c4d7f2aeab6c&deploymentName=test&api-version=2021-05-01-preview
    Header differences:
        <Content-Length> values differ, request <360>, record <328>
    Body differences:
    Request and response bodies do not match at index 109:
         request: "shold":0.20000000000000001,"co"
         record:  "shold":0.2,"context":{"previou"
```

I can disable body comparisons, but I'm wondering if we could have the recording framework somehow inject a double converter to control precision.

For example, I believe Newtonsoft.Json uses `double.ToString("R")` so maybe we could as well, or even pass something like "f8" to always emit 8 decimal places (or whatever number) unconditionally.

**Comment by heaths** [comment]
See https://github.com/dotnet/runtime/issues/435 for some discussion about this.

**Comment by pakrym** [comment]
The recording framework is not the one that is serializing the request so it can't control the number formatting. Unfortunately this is not the first time we hit this issues so we do need a fix.

One possibility might be a semantic JSON comparer instead of bytes comparer.

**Comment by heaths** [comment]
Another possibility might be something conceptually similar to what they did [here](https://github.com/dotnet/runtime/pull/35042/files#diff-a31e2a8eea664a0b94fff01d8bc216318a37636f42aca04c4dc43c23780654cfR7740-R7752): if we can safely (and we should probably make this behavior optional to mitigate risk) determine we are writing a double, we could precision to some degree as long as rounding works in our favor. While this change ignores ".0", we could use stateful comparisons to limit precision to 4 decimals or so. The only problem might be if on one machine we had a number like .3542 while on another .35419001. We should be able to mitigate that by handling rounding ourselves to whatever precision we define. Perhaps the degree of precision is an input to even enable this hypothetical encoder.

**Comment by JoshLove-msft** [comment]
I think this is rare enough that we can consider adding an attribute that would allow for separate recording per framework. Or even just separate recordings for .NET Framework vs .NET Core and above.

**Comment by christothes** [comment]
I wonder if we could address this with a "double value sanitizer" just to avoid an explosion of recording files.

**Comment by JoshLove-msft** [comment]
> I wonder if we could address this with a "double value sanitizer" just to avoid an explosion of recording files.

Could you expand on that?

**Comment by christothes** [comment]
> > I wonder if we could address this with a "double value sanitizer" just to avoid an explosion of recording files.
> 
> Could you expand on that?

Just an idea, but for example, when the transport detects that a mismatch failure is related to a double value formatting on Playback, it normalizes the matching somehow.

**Comment by heaths** [comment]
> The "somehow" part is what is tricky. I don't think there is a clear algorithm for normalizing the doubles between frameworks.

Exactly, or Pavel or I would've done this earlier. In digging into this problem, I did find where the .NET team themselves implemented a heuristic-based approach in a derived [`JavaScriptEncoder`](https://docs.microsoft.com/dotnet/api/system.text.encodings.web.javascriptencoder?view=net-6.0) which the JSON parser uses. Later, I couldn't find it again. But it effectively scans char by char (which it already does anyway) and watches for patterns like "{numbers}.{numbers}" and assumes it's a double, though it might also exclude that pattern if in a string already. That was the only way we could find to augment our current parsing/recording since we could plug a derived encoder into our JSON options somewhere (sorry, forget the exact details off hand but not hard to dig up again).

But I'm with Chris, I'd rather not have to record per-framework - at least, not until we have a solution in place to deal with all the huge recording files.

Perhaps - at least in the short-term - we could ignore recording discrepancies based on the .NET version? IIRC, this issue with doubles was fixed in netcoreapp3.0. Anything older than that, and a `RecordingMismatchException` could just be ignored. It shouldn't affect the rest of the test, so assertions should still (except where doubles are concerned for exact matches) work.

**Comment by JoshLove-msft** [comment]
The record per-framework would be something that could be enabled per test, so it would just be for these exceptional cases.

**Comment by heaths** [comment]
For Cognitive Services, it's the norm rather than the exception.

**Comment by christothes** [comment]
Did a bit of research on this:
- The key difference between the two formats is that prior to netcore 3.0, Utf8JsonWriter.WriteNumber formatted with "G17".  >=netcore 3.0 formats with "G".

```c#
double d = 0.2;
Console.WriteLine(d.ToString("G"));      // 0.2
Console.WriteLine(d.ToString("G15"));  // 0.2
Console.WriteLine(d.ToString("G17"))  // 0.20000000000000001
```

**Comment by christothes** [comment]
I'm not sure this is worth fixing in lieu of simpler workarounds like only disabling body compare when not on framework like we are doing here:

https://github.com/Azure/azure-sdk-for-net/blob/bd5c715e0b25f80fee7e78f779c1cab9f6387f50/sdk/objectanchors/Azure.MixedReality.ObjectAnchors.Conversion/tests/ObjectAnchorsConversionClientLiveTests.cs#L38-L42

**Comment by heaths** [comment]
I'm in favor of just ignoring bodies on older runtimes:
> Perhaps - at least in the short-term - we could ignore recording discrepancies based on the .NET version? IIRC, this issue with doubles was fixed in netcoreapp3.0. Anything older than that, and a RecordingMismatchException could just be ignored. It shouldn't affect the rest of the test, so assertions should still (except where doubles are concerned for exact matches) work.

**Comment by JoshLove-msft** [comment]
@heaths users can already do this with the CompareBodies property for affected tests. I don't think we should ignore by default.

**Comment by JoshLove-msft** [comment]
So to resolve this issue, I propose we update the Test Framework README to describe the workaround.

**Comment by heaths** [comment]
That's probably suitable, but I also think we should include a link to the preproc expression support. I've seen at least one senior person not aware of the newish `_OR_GREATER` support that was added sometime back.

https://learn.microsoft.com/dotnet/standard/frameworks#how-to-specify-a-target-framework

**Comment by JoshLove-msft** [comment]
> That's probably suitable, but I also think we should include a link to the preproc expression support. I've seen at least one senior person not aware of the newish `_OR_GREATER` support that was added sometime back.
> 
> https://learn.microsoft.com/dotnet/standard/frameworks#how-to-specify-a-target-framework

Yes, this is the workaround..

**Comment by heaths** [comment]
Speaking of recording on Core, I opened #31768 that might help. Right now, if you just press the "Play" button in Test Explorer, net461 will run first and all tests get recorded there and used in subsequent ("Core") runtimes. I want to default test runs to the latest and "filter" the test coverage reports similar. The order as it is was intentional, though someone effectively "broke" it when they added "net6.0" last.

**Comment by JoshLove-msft** [comment]
I can take this now that it is scoped to a doc update 😆
