### ISSUE TITLE
[BUG] ShareDirectoryClient SetMetadataAsync returns incorrect last modified time

### ISSUE THREAD

**Issue by Alanddq** [Azure/azure-sdk-for-net#22217]
**Describe the bug**
Please provide the description of issue you're seeing.

ShareDirectoryClient SetMetadataAsync returns incorrect last modified time

**Expected behavior**
What is the expected behavior?

ShareDirectoryClient SetMetadataAsync should return correct last modified time

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

ShareDirectoryClient SetMetadataAsync returns 1/1/0001 12:00:00 as last modified time

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

            ShareDirectoryClient dirClient = shareClient.GetDirectoryClient("dir");
            var mata = new Dictionary<string, string>();
            mata["key"] = "value";
            ShareDirectoryInfo info = await dirClient.SetMetadataAsync(mata);
            Console.WriteLine($"{info.LastModified}");  // -> 1/1/0001 12:00:00 AM +00:00

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Files.Shares 12.7.0 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Framework 4.6.1
 - IDE and version : Visual Studio 16.9.8

**Comment by seanmcc-msft** [comment]
Hi @Alanddq, I can reproduce this issue, and will have a fix out soon.

Thanks for reporting this!

-Sean
