### ISSUE TITLE
[QUERY] Search: Using DateTimeOffset in POST body for azure search filter

### ISSUE THREAD

**Issue by Sandeep7OnShell** [Azure/azure-sdk-for-net#22236]
**Query/Question**
I am trying to implement azure search via POST that involves a DateTimeOffset field. My filter run fine if I don't have the DateTimeOffset field added. Below is the query that works fine:
POST:BODY:
{"filter":"statusCode eq 'ACTIVE'","top":100,"skip":0,"orderby":"code asc","count":true,"search":"*"}
but this doesn't work:
POST:BODY:
{"filter":"statusCode eq 'ACTIVE' and DateTimeOffset ge 2010-01-01T00:00:00Z","top":100,"skip":0,"orderby":"code asc","count":true,"search":"*"}

Same query with DateTimeOffset  works fine when I use GET instead of POST.

These is no documentation available in how to use azure serach using POST verbs. Azure portal also allows testing only via query string (GET).

**Environment:**
Azure search API - api-version=2017-11-11 and above

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Mohit-Chakraborty** [comment]
This seems like a question for the service, and not the client SDK.
@bleroy, can you please help or loop in the right set of people.

**Comment by Mohit-Chakraborty** [comment]
@dereklegenzoff, can you please help or loop in the right set of people.

**Comment by brjohnstmsft** [comment]
@Sandeep7OnShell Please ask your question on [StackOverflow](https://stackoverflow.com) and tag it with "azure-cognitive-search". It will be automatically assigned to engineers on our team who can help you. Also, please provide the error message you're getting for your POST request in your StackOverflow post. Thanks!
