### ISSUE TITLE
[QUERY] When will Azure.ResourceManager.Sql be available via NuGet?

### ISSUE THREAD

**Issue by coppercosmo** [Azure/azure-sdk-for-net#22248]
**Query/Question**
I see [here](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/sqlmanagement/Azure.ResourceManager.Sql) that there is a link that should send me to the NuGet package for Azure.ResourceManager.Sql, but I am not seeing that package anywhere. When will Azure.ResourceManager.Sql be available via NuGet?

**Environment:**
 - Name and version of the Library package used: [Azure.ResourceManager.Sql 1.0.0-preview.1] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [Sql Server .Net Core 3.1]
 - IDE and version : [Visual Studio 16.4]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
Thank you for your inquiry. We are currently working on Azure.ResourceManager.xxx SDKs and will preview a number of key RPs in the coming month. I expect SQL to follow that later this year.

**Comment by coppercosmo** [comment]
@allenjzhang Is there an update you can provide since June 28 on the key RPs that have been completed?
