### ISSUE TITLE
Description displays &lt; and &gt; instead of formatting the text

### ISSUE THREAD

**Issue by StefanJanssen95** [Azure/azure-sdk-for-net#22246]
```
Gets or sets &lt;code&gt;true&lt;/code&gt; to enable client affinity; &lt;code&gt;false&lt;/code&gt; to stop sending session affinity cookies, which route client requests in the same session to the same instance. Default is &lt;code&gt;true&lt;/code&gt;.
```
The text shows encoded characters for `<` (`&lt;`) and `>` (`&gt;`)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c89f7c02-ca6c-3a95-b967-b8ca3e80e269
* Version Independent ID: d1c50b62-bbc7-304f-1313-65266458bdaa
* Content: [Site.ClientAffinityEnabled Property (Microsoft.Azure.Management.WebSites.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.site.clientaffinityenabled?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.WebSites.Models/Site.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/Site.xml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
@allenjzhang:  I believe this is sourced from the swagger directly, so I've routed to the service team.  Please feel free to reroute if my assumption is incorrect.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
