### ISSUE TITLE
[QUERY] How to specify TimeToLive for Azure.Data.Tables ?

### ISSUE THREAD

**Issue by snakefoot** [Azure/azure-sdk-for-net#22254]
**Query/Question**
How to specify TimeToLive for Azure.Data.Tables ? See also: https://docs.microsoft.com/en-us/azure/cosmos-db/time-to-live

Looked at the [ReadMe.md](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/tables/Azure.Data.Tables) but failed to find anything.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @snakefoot - This property is not exposed in the Cosmos Tables API, I believe it only applies to Cosmos DB proper.

**Comment by snakefoot** [comment]
Have the method `CreateIfNotExistsAsync` that takes `defaultTimeToLive` as input:
```c#
var table = _client.GetTableReference(tableName);
await table.CreateIfNotExistsAsync(Microsoft.Azure.Cosmos.IndexingMode.Consistent, null, defaultTimeToLive, cancellationToken).ConfigureAwait(false);
```

See also: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.cloudtable.createifnotexistsasync?view=azure-dotnet#Microsoft_Azure_Cosmos_Table_CloudTable_CreateIfNotExistsAsync_Microsoft_Azure_Cosmos_IndexingMode_System_Nullable_System_Int32__System_Nullable_System_Int32__System_Threading_CancellationToken_

**Comment by christothes** [comment]
The older client does some magic behinds the scenes to bypass the Table REST API endpoint and talks directly to the Cosmos direct mode endpoint. The newer client strictly interacts with the REST API, which does support this Cosmos specific feature.

**Comment by snakefoot** [comment]
Guess I will read about all this when you have writen the migration guide:  #16771

**Comment by snakefoot** [comment]
Funny that  AdminAzure Cosmos DB Team says Collection Default TTL is supported by the REST API:

https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/19309504-allow-ttl-to-be-set-by-the-azure-cosmos-db-rest-ap
