### ISSUE TITLE
[BUG] EventGridPublisherClient.SendEventsAsync fails if event handler function receives single EventGridEvent

### ISSUE THREAD

**Issue by kzu** [Azure/azure-sdk-for-net#22270]
Given the following Azure Functions v3 precompiled function:

```csharp
[FunctionName("event-handle")]
public void HandleAsync([EventGridTrigger] EventGridEvent e, ILogger logger)
{
   logger.LogInformation(e.Subject);
}
```

And an Event Grid Domain (with no custom topic) with a Domain-Scoped Event Subscription (that basically handles *every* event with no filters whatesoever):

![image](https://user-images.githubusercontent.com/169707/123800143-5cab1080-d8bf-11eb-83ac-1478022f560a.png)
![image](https://user-images.githubusercontent.com/169707/123800233-74829480-d8bf-11eb-9194-f4192bd44272.png)

When using the code shown in [PublishEventsToTopic](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/eventgrid/Azure.Messaging.EventGrid/samples/Sample1_PublishEventsToTopic.md#publishing-events-to-azure-event-grid) to send all events in a batch:

```csharp
await client.SendEventsAsync(eventsList);
```

the code fails with:

```
This resource is configured to receive event in 'EventGridEvent' schema. 
The JSON received does not conform to the expected schema. Token Expected: StartObject, Actual Token Received: EndArray. 
```

If the code is changed to send each event individually, delivery succeeds.

**Expected behavior**
I would expect the batching on the client to have no impact on how the handling function is authored, and automatically invoke the function multiple times for each sent event. 

**Environment:**
 - Azure.Messaging.EventGrid 4.3.0 
 - Hosted Azure Functions v3 runtime
 - Visual Studio 16.10

**Comment by jsquire** [comment]
@JoshLove-msft:  This seems like it may be a service behavior.  Would you mind offering your thoughts and routing to the Event Grid team if that is the case?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @kzu,
Can you let us know the version of the Event Grid trigger that you are using?

Can you also include the code you are using to collect and send the event list?

**Comment by kzu** [comment]
Client code is exactly the one linked in my original report. EG trigger is latest stable from the legacy API : https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/2.1.0

**Comment by JoshLove-msft** [comment]
So you are using the EventGridEvent defined in the 2.1.0 trigger, but publishing using Azure.Messaging.EventGrid? Most likely this is sending the message as a custom schema event. Can you confirm the overload of SendEvents that is being used?

**Comment by kzu** [comment]
Seriously? What a mess. I'm now pushing to the EG HTTP endpoint directly. Quite terrible user experience on the libs side.

**Comment by JoshLove-msft** [comment]
Hi @kzu,
We are sorry that you are experiencing trouble here. The stable EventGrid functions bindings still rely on the old Microsoft.Azure.EventGrid library, which is why you are seeing this behavior. There is a beta EventGrid binding that uses the new models defined in Azure.Messaging.EventGrid - https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/3.0.0-beta.3
If you would like to try it out, things should work more smoothly. Additionally, we will have a stable release of the EventGrid binding in the coming months that you can try.
