### ISSUE TITLE
Please Make AzureKeyVaultConfigurationSource public OR (Better) add an Insert Extension Method that takes an index

### ISSUE THREAD

**Issue by JohnGalt1717** [Azure/azure-sdk-for-net#22272]
**Library or service name.**
Azure.Extensions.AspNetCore.Configuration.Secrets
 
**Is your feature request related to a problem? Please describe.**
The problem right now is that the AddAzureKeyVault method appends the keyvault configuration to the list of configuration sources which by default already has command line, environment variables and config files (to name a few) automatically added by AspNetCore.  In virtually every case AzureKeyVault is your baseline and then environment variables etc. override those baseline values.

Thus, in virtually every case beyond the Hello World example, you'll want AzureKeyVault added as the first source with the config.Sources.Insert method.

Right now this isn't possible because the IConfigurationSource (AzureKeyVaultConfigurationSource) for AzureKeyVault is internal (you can use reflection which isn't optimal) 

So the request is, either make AzureKeyVaultConfigurationSource public so that we can create our own instance and then use config.Sources.Insert, and/or create an extension method InsertAzureKeyVault() that takes an index (i.e. 0) so that we can put it in the right order so that all other sources of configuration override azure key vault as is the basic use case for this per above.

I'm not sure what the value is in it being marked internal anyhow.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Good suggestion.

There are a few workarounds before we implement the change:

1. Copy the AzureKeyVaultConfigurationSource into you project (https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationSource.cs). It's pretty simple and AzureKeyVaultConfigurationProvider is public.
2. Use the extension method but modify the `builder.Sources` list after adding.l
```C#
builder.AddKeyvault();
builder.Insert(0, builder.Sources[builder.Sources.Count - 1]);
builder.RemoveAt(builder.Sources.Count - 1)
```

**Comment by JohnGalt1717** [comment]
Thanks!
