### ISSUE TITLE
TableClient needs to clean SAS URL before passing to TableRestClient

### ISSUE THREAD

**Issue by Identifier** [Azure/azure-sdk-for-net#22278]
https://github.com/Azure/azure-sdk-for-net/blob/15259c676941f6700e9295e4f25a5703adc10f79/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L253

In the `TableClient` constructor that takes a `Uri endpoint`, it creates a new `TableRestClient(..., endpoint.AbsoluteUri, ...)`.  But unfortunately that will cause the table name to be duplicated in eventual REST queries to Azure.  This is because `TableRestClient.CreateQueryEntitiesRequests` expects the value to be just the base URL without the table name.  You can see this in the `TableRestClient.CreateQueryEntitiesRequests` code (where `url` is the endpoint passed in above):

```csharp
        internal HttpMessage CreateQueryEntitiesRequest(string table, int? timeout, string nextPartitionKey, string nextRowKey, QueryOptions queryOptions)
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Get;
            var uri = new RawRequestUriBuilder();
            uri.AppendRaw(url, false);
            uri.AppendPath("/", false);
            uri.AppendPath(table, true);
            uri.AppendPath("()", false);
```

For example, if the endpoint (`uri` here) passed in was `https://myaccount.table.core.windows.net/mytable?sp=ra&st=blahblah&tn=mytable`, then the resulting `uri` will be `https://myaccount.table.core.windows.net/mytable/mytable()?sp=ra&st=blahblah&tn=mytable`, which will cause the eventual query request to return 501 not implemented.

The fix is for `TableClient` to call `TableRestClient(..., new Uri($"{endpoint.Scheme}://{endpoint.Host}"), ...)` instead.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
