### ISSUE TITLE
Update breaking change detection tool to iterate over multiple RPs

### ISSUE THREAD

**Issue by kirthik** [Azure/azure-sdk-for-net#2230]
Breaking change detection script looks at first 3 files in a pull request to determine the Resource Provider(RP) and it builds only the projects under the discovered RP.  If a change spans across multiple RPs then breaking change tool does not run. This works for most of the scenarios. There are times where common code changes happen and that could cause breaking changes across multiple RPs. To address this scenario, breaking change detection script should iterate over all files in a Pull request instead of first 3 files and make a list of all the RPs that are being changed. Then it should run breaking change tool on all RPs in that list.

**Comment by adrianhall** [comment]
Is this still an issue?

**Comment by cormacpayne** [comment]
@adrianhall this isn't implemented in the .NET SDK repository, and I think it would be beneficial to add it to CI for the data plane SDKs. For management plane, any breaking changes in the SDK should be caught at the swagger spec level, so the CI in that repository should be responsible for flagging any breaking changes in the API there. We currently have a static analysis in the PowerShell repository that's checking for breaking changes between versions of a module, so we could leverage that existing functionality to implement a tool to check breaking changes in new versions of data plane SDKs in this repository.

**Comment by adrianhall** [comment]
Thanks for the response!

**Comment by Petermarcu** [comment]
I'm thinking we should open a new issue to track breaking change detection for the data plane and close this one if the original intent was satisfied. I'm going to do that.
