### ISSUE TITLE
Dependency on .net 2.0.5.0

### ISSUE THREAD

**Issue by paulgmiller** [Azure/azure-sdk-for-net#2231]
Seems like the management dlls have refernces to .net 2.0. Any reason why? This makes it harder to deploy as we have to ensure 2.0.5.0 is installed on all machines (or maybe I am wrong about that?)

ilspy lib\net40\Microsoft.WindowsAzure.Management.Compute.dll 

// mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
// Microsoft.WindowsAzure.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
...
// System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

lib\portable-net45+sl50+wp80+win\Microsoft.WindowsAzure.Management.WebSites.dll

// mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
// Microsoft.WindowsAzure.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
// System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

**Comment by paulgmiller** [comment]
Hmm trying to to see if this is only an issue when we reference the portable libraries instead of net40 in the nugget package. The net40 have refeences to both 4.0 and 2.0.5.0 while portable only has 2.0.5.0. Guidance on how to deploy 2.0.5.0 with the app rather than with a machine install would also be useful if that's possible.

**Comment by markcowl** [comment]
@paulgmiller What is the issue you are seeing?  The 2.0 framework is generally included in the 4.0 Gramework, so there should be no deployment issue.  If you're seeing a particular depoloyment issue, please let us know what it is.

**Comment by paulgmiller** [comment]
We were seeing this crash. 
7/26/2016 5:53:59 PM,FatalError,Request#2329947 failed: System.IO.FileNotFoundException: Could not load file or assembly 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The system cannot find the file specified.
File name: 'System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'
   at Microsoft.WindowsAzure.Management.Storage.StorageManagementClient..ctor(SubscriptionCloudCredentials credentials)
   at

Again our current theory is that someone referenced portable framework dlls instead of net40 in the nuget package so we're seeing if that gets us to a happy place.

**Comment by paulgmiller** [comment]
This seems to be related to targeting the portable class libraries (PCL).
For example in ilspy they’ll have 
[assembly: TargetFramework(".NETPortable,Version=v4.0,Profile=Profile102", FrameworkDisplayName = ".NET Portable Subset")]
Rather than something like : TargetFramework(".NETFramework,Version=v4.0

Thus you get these references. 
// mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e 
// System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e

I actually upgraded/repointed most of our azure.managment/azure.common packages to remove this  but hyak.common doesn’t seem to have anything that doesn’t target the portable class library (and the source doesn't seem available). Even though hyak.common's nugget has net40,net435 and portable* folders all of them target the PCL.  

For some reason the machines I am running on (not under my control) don't just retarget this to 4.0 and searching for other solutions just turned up this old KB  http://support.microsoft.com/kb/2468871 which will not install on the winserver 2012. 

If you know where the owener/sources for hyak is I could go bug them.

**Comment by paulgmiller** [comment]
So there are versions the management sdk's that do not target portable. However there is no version of hyak that doesn't. Nor does it appear there ever will be since more recent versions have moved onto autorest. If you need to use manangement packages that still use hyak you have to bundle up the portable dll's along with your app. This is hard since there is no nuget for the portable libraries. Instead you need to find some random installed version and use those.
