### ISSUE TITLE
Default values for avro

### ISSUE THREAD

**Issue by xqrzd** [Azure/azure-sdk-for-net#2232]
Is there a way to provide a default value for a property/field using the reflection API? Basically, I want to use

`AvroSerializer.Create<MyClass>();`

and have it include a default value

`{ "name": "something", "type": "string", "default": "" }`

From what I've read, default values are a key part of schema evolution. If there isn't already functionality to do this (I couldn't find anything), I'd be happy to create a pull request for it. My initial thought was to have avro honor the the DefaultValueAttribute.

Let me know if this works and I'll start working on it, or let me know if you'd prefer something else. I imagine it would be consumed like,

```C#
[DataContract]
class MyClass
{
    [DataMember]
    [DefaultValue("")]
    public string SomeProperty { get; set; }
}
```

**Comment by treziac** [comment]
Same thing here. Doc and Alias would be nice too.
Actually there are two issues for me:

- no way to add doc, default values or aliases from reflection (and maybe more, but those are the ones I've seen so far) 
Like xqrzd proposed, adding attributes [Doc], [Aliases] and [DefaultValue] would be fine

Note for DefaultValue : even if we add a default value with attribute (for Schema class to know it when writing WriterSchema), there doesn't seem to be a way to ensure the user is using this default value in the class (like putting `SomeProperty="" `in constructor like Avro.Utils do) so we have to entrust the user here. Or make dirty reflection to ensure it. 
If we add attributes, make sure to use them in Avro.Utils code generation

- default are not serialized in WriterSchema even if exisiting in Schema (RecordField.ToJsonSafe is missing two lines :
```
if(hasDefaultValue)
   writer.WriteProperty("default", this.DefaultValue); 
```

Default and Aliases in schema are important as may break compatibility with avro schemas if missing

A nice test to have would be to check that writerSchema stay identical when using Avro.Utils followed by AvroSerializer.Create (it is usefull when using Schema Repository like ConfluentInc one)

**Comment by markcowl** [comment]
@shefaliv Can you take a look?

**Comment by xqrzd** [comment]
Just got back to this, I'm going to close this issue as it seems like the reflection API works fine without explicitly setting default values in the schema; it seems to just use the default value for a type if the schema changes, which works great for me.

**Comment by ahilis** [comment]
Hot to make it work? "default" property doesn't appear in avro scheme.
Im trying to make schema from object: `AvroSerializer.Create<Object>().WriterSchema.ToString().`
Property declaration:
```
[DataMember]
[NullableSchema]
[DefaultValue(null)]
public int? Test { get; set; }
```

**Comment by xqrzd** [comment]
It requires a lot of changes to the library. It might be better to open an issue [here](https://github.com/dougmsft/microsoft-avro), as this library isn't maintained anymore.

**Comment by ahilis** [comment]
Ok, I'll do it. Thanks!
