### ISSUE TITLE
[FEATURE REQ] DefaultAzureCredential should use user-assigned managed identity if available

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/azure-sdk-for-net#22328]
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
In Azure, we use a user-managed identity for many of our services instead of the default system-assigned identity so that many services can share the permissions of the user-managed identity that are set on several resources. Otherwise we'd have to set up a cross-product of permissions for system-identities and resources (for example, if we have 30 functions apps and 4 resources they each access, that's 120 permissions to set).

The problem with the current functionality is that we have to both assign a user-managed identity to the consuming app (which is fine) and then separately store and reference the client id of that identity in code, such as:

```c#
string managedIdentityClientId = Environment.GetEnvironmentVariable("ManagedIdentityClientId", EnvironmentVariableTarget.Process);
var options = new DefaultAzureCredentialOptions { ManagedIdentityClientId = managedIdentityClientId };
var credentials = new DefaultAzureCredential(options);
```

**Request**
With system-assigned identity, the code is reduced to one line `var credentials = new DefaultAzureCredential();` and the client id of the identity doesn't have to be stored separately and referenced repeatedly.

What I'm requesting is that the default constructor for `DefaultAzureCredential` use the user-assigned managed identity if one (and only one) is assigned to a resource (such as an App Service). Alternatively, being able to iterate through the user-assigned managed identities would allow us to get the client id and use the existing options constructor.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by BrianVallelunga** [comment]
@christothes I'll check that out. It seems like exactly the behavior I wanted. Thanks!

**Comment by BrianVallelunga** [comment]
/unresolve

I wanted to believe.

I modified my code to use the basic `DefaultAzureCredential()` constructor. Below is the code I'm now using in conjunction with the `Azure.Extensions.AspNetCore.Configuration.Secrets` package to bring in KeyVault settings into IConfiguration in an Azure Function app running on a App Service Plan with a Managed User Identity assigned.

Unfortunately, with this new code I get the following notification warning and the app seems to hang.

> Azure.Identity: ManagedIdentityCredential authentication failed: Service request failed. Status: 400 (Bad Request) Headers: Date: Wed, 15 Sep 2021 23:08:13 GMT Content-Length: 133 . Azure.Identity: Service request failed. Status: 400 (Bad Request) Headers: Date: Wed, 15 Sep 2021 23:10:13 GMT Content-Length: 133 .


**NEW CODE (Failing)**
```C#
IConfigurationBuilder builder; // Passed in
var keyVaultCredentials = new DefaultAzureCredential();
var configOptions = new AzureKeyVaultConfigurationOptions { ReloadInterval = TimeSpan.FromMinutes(8) };
builder.AddAzureKeyVault(new Uri($"https://{keyVaultName}.vault.azure.net/"), keyVaultCredentials, configOptions);
```

**OLD CODE (Working)**
```C#
IConfigurationBuilder builder; // Passed in
var options = new DefaultAzureCredentialOptions { ManagedIdentityClientId = "CLIENT ID FROM ENVIRONMENT" };
var keyVaultCredentials = new DefaultAzureCredential(options);
var configOptions = new AzureKeyVaultConfigurationOptions { ReloadInterval = TimeSpan.FromMinutes(8) };
builder.AddAzureKeyVault(new Uri($"https://{keyVaultName}.vault.azure.net/"), keyVaultCredentials, configOptions);
```

**Comment by christothes** [comment]
Just to verify, could you confirm that the resource where this app is deployed has no system assigned managed identity, but just this single user assigned identity?

**Comment by BrianVallelunga** [comment]
Correct, no system assigned identity is present:

![image](https://user-images.githubusercontent.com/351190/133654411-41ec1bcc-821b-410c-8f73-a947b50825c2.png)

**Comment by christothes** [comment]
I'm not sure why it isn't behaving as documented then.. Unfortunately, I don't think there is anything reasonable the client could do to change the behavior since `Azure.Identity` is agnostic to the hosting environment.

**Comment by BrianVallelunga** [comment]
Is there no resolution to this then?

**Comment by christothes** [comment]
Hi @BrianVallelunga - The only workaround is to specify the User assigned Client Id. As an alternative, we are soon going to be merging a feature that makes it possible to specify a Resource Id rather than a Client Id.

**Comment by BrianVallelunga** [comment]
Thanks for the info.
