### ISSUE TITLE
Azure AI Translation Document Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#22323]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/translation/Azure.AI.Translation.Document#create-documenttranslationclient-with-azure-active-directory-credential):
![image](https://user-images.githubusercontent.com/65581162/123936266-98c99880-d9c7-11eb-81fd-25b328f12b63.png)

Suggestion:
1.Add link for `[azure_identity]`: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/README.md
2.Add link for `[custom_subdomain]`: https://docs.microsoft.com/en-us/azure/cognitive-services/authentication?tabs=powershell#create-a-resource-with-a-custom-subdomain
3.Update link to https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/README.md#defaultazurecredential
4. Add link for `[register_aad_app]`: https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad#-configure-with-advanced-settings
5. Add link for `[aad_grant_access]`: https://docs.microsoft.com/en-us/powershell/module/az.Resources/New-azRoleAssignment?view=azps-1.8.0

@jongio for notification.

**Comment by maririos** [comment]
ohhh this is awesome! thanks @Tianyun-G for finding this!
