### ISSUE TITLE
[FEATURE REQ] Azure.Management.EventHub allow MaximumThroughputUnits of 40

### ISSUE THREAD

**Issue by RoncoCo** [Azure/azure-sdk-for-net#22327]
Azure.Management.EventHub

We are using the .Net SDK for the creation of EHs and we have notices that the allowed maximumThroughputUnits is validated between 0 and 20 even though in the Azure portal EHs can have maximumThroughputUnits of 40.

I can see that there is a validation [here](https://github.com/Azure/azure-sdk-for-net/blob/2a535113da4f71b2d454dbb8e69b4aae60883440/sdk/eventhub/Microsoft.Azure.Management.EventHub/src/Generated/Models/EHNamespace.cs#L185) is that intentionally not synced with the portal behavior?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
For additional context,  40 is the documented limit as well:

![image](https://user-images.githubusercontent.com/913445/124032822-13de7f00-d9c7-11eb-9c35-c76c9f00d90b.png)


_([source](https://docs.microsoft.com/azure/event-hubs/event-hubs-scalability))_

**Comment by RoncoCo** [comment]
@jsquire thank you, I am willing to contribute if it is needed. (assuming it is more than just changing the validation 😁 )

**Comment by kasun04** [comment]
Yes, we are currently working on the changes related to updating SDK, CLI and PowerShell to 40TU limit. Will update the issue once it is done.

**Comment by ramya-rao-a** [comment]
@kasun04 Any updates here?

**Comment by kasun04** [comment]
We have released SDK to remove validation on 20 TU. You can find the generated code [here](https://github.com/Azure/azure-sdk-for-net/blob/5b74f611c7cc6d3a2d19dfb9d6109ac129b5633a/sdk/eventhub/Microsoft.Azure.Management.EventHub/src/Generated/Models/EHNamespace.cs#L228 ).

**Comment by jsquire** [comment]
Thanks, @kasun04.   I'm going to mark this as addressed; @RoncoCo, please feel free to unresolve if you'd like to continue the discussion.
