### ISSUE TITLE
[QUERY] Azure.Security.KeyVault.Secrets accepts ServiceClientCredentials

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-sdk-for-net#22322]
**Query/Question**
How can we help?

Is it possible to let Azure.Security.KeyVault.Secrets accept `ServiceClientCredentials` besides `TokenCredential` as auth method?

We get blocked in upgrading from `Microsoft.Azure.KeyVault` to `Azure.Security.KeyVault.Secrets`.

`Azure.Security.KeyVault.Secrets` uses `TokenCredential` which doesn't support use MSI resource ID.

see related: https://github.com/Azure/azure-sdk-for-net/issues/20651

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
`TokenCredential` is the base for all authentication in the Azure SDKs. @schaabs, @christothes are there definitely plans to allow for user managed identities, or at least add a `TokenCredential` to Azure.Identity to support it outside of `DefaultAzureCredential`?

**Comment by christothes** [comment]
I believe what @karataliu is referring to is the ability for Azure.Identity to support specifying user specified Managed Identities by Resource Id rather than Client Id. This is planned for a future version of Azure.Identity, but we don't yet have a specific release targeted.

**Comment by heaths** [comment]
Given this is an auth issue I'm transferring it as a feature request for Azure.Identity.

**Comment by christothes** [comment]
duplicate of #20651

**Comment by karataliu** [comment]
@christothes per latest update there is no fix for the issue. What about switching to `ServiceClientCredentials`? `TokenCredential` is not supposed to functioning.

**Comment by karataliu** [comment]
Could you please reopen this issue? The new Azure.Security package is not usable.

**Comment by christothes** [comment]
Hi @karataliu - It's not possible for the SDK to start accepting `ServiceClientCredentials` in addition to `TokenCredential`. `TokenCredential` is the common abstraction that is supported throughout all client SDKs, so such a change would affect every other client.

**Comment by karataliu** [comment]
@christothes 
Then it is wrong to deprecate below package when the new keyvault package Azure.Security.KeyVault.Secrets is not functioning.
https://www.nuget.org/packages/Microsoft.Azure.KeyVault/3.0.5?_src=template

Can you bring back the support for Microsoft.Azure.KeyVault please?
