### ISSUE TITLE
Do we need to specify '@' before parameter name if it is specified in the sql stored procedure

### ISSUE THREAD

**Issue by dheerajawale-svg** [Azure/azure-sdk-for-net#22320]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe8e943-3db2-f498-11ba-c19a3649697e
* Version Independent ID: ded9de8a-c881-fbc8-6717-d1f6fbab8438
* Content: [SqlDWSource.StoredProcedureParameters Property (Azure.Analytics.Synapse.Artifacts.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.analytics.synapse.artifacts.models.sqldwsource.storedprocedureparameters?view=azure-dotnet-preview)
* Content Source: [xml/Azure.Analytics.Synapse.Artifacts.Models/SqlDWSource.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Analytics.Synapse.Artifacts.Models/SqlDWSource.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by annelo-msft** [comment]
@idear1203, @wonner, can you help us find the answer to this question?

**Comment by dheerajawale-svg** [comment]
Any inputs on this?
