### ISSUE TITLE
Create solution for Storage WebJobs projects

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#22356]
There are several storage webjobs projects - it would be helpful to have a solution that includes all of them for dev purposes.

**Comment by kasobol-msft** [comment]
You mean this https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.sln ?

**Comment by JoshLove-msft** [comment]
Yeah that'll work.
