### ISSUE TITLE
[QUERY] Microsoft.Azure.ContainerRegistry supports TokenCredential?

### ISSUE THREAD

**Issue by JamieMagee** [Azure/azure-sdk-for-net#22361]
**Query/Question**
How can we help?

Is it possible to update Microsoft.Azure.ContainerRegistry, specifically `AzureContainerRegistryClient`, to accept `TokenCredential`? Currently it only accepts `TokenCredentials` (or rather `ServiceClientCredentials`).

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ContainerRegistry 1.0.0-preview2
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET 5.0.204
 - IDE and version : Visual Studio 2019

**Comment by jsquire** [comment]
//cc: @annelo-msft

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by annelo-msft** [comment]
To my knowledge, changes are no longer being made to Microsoft.Azure.ContainerRegistry.

There is a new Azure SDK package that takes an Azure.Core `TokenCredential` -- you can find it here: https://www.nuget.org/packages/Azure.Containers.ContainerRegistry/

@northtyphoon @AlexGhiondea FYI

**Comment by JamieMagee** [comment]
@annelo-msft that looks like what I'm after. I didn't look hard enough 😅 Thank you!
