### ISSUE TITLE
Can Microsoft.Azure.Management.DataFactory work with a git config

### ISSUE THREAD

**Issue by shannonlowder** [Azure/azure-sdk-for-net#22408]
**Query/Question**
I'm able to use the DataFactory library to create linked services, data sets, and pipelines when the DataFactory does not use a git configuration. I'm unable to find any code to show how to do the same thing and target a given git branch.  Is it possible to use the library when your DataFactory is configured to use git?

**Environment:**
 - Microsoft.Azure.Management.DataFactory 4.20.0
 - .net core 3.1/.net 5.0
 - Visual Studio 16.10.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by shawnxzq** [comment]
@shannonlowder Do you mean you want to to update the linked service/datasets in the git repository associated to the factory?

**Comment by shawnxzq** [comment]
@shannonlowder Git repository is managed by our own, you can use the git restful API to save changes to the repository or try to find some git client lib if necessary. Data factory client only works with factory metadata store, thanks!

**Comment by shawnxzq** [comment]
Answered the question.
