### ISSUE TITLE
[BUG] SDK may generate null or empty permission for KeyVault Access Policies

### ISSUE THREAD

**Issue by jiacheng-L** [Azure/azure-sdk-for-net#22403]
**Describe the bug**
Please provide the description of issue you're seeing.
Key Vault RP is not allowed null Permissions for access policies. However, we found the Workspace team who use SDK and generate access policies with Null Permissions. We are looking for help from SDK team to confirm if there is any logic to generate this Null permissions. 

**Expected behavior**
What is the expected behavior?
Workspace team use the SDK and generate the correct Access policies permissions.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
We found the policies is generated as below:

```JSON
{
  "permissions": {
    "keys": [
      "all"
    ],
    "secrets": [
      "all"
    ],
    "certificates": [
      "all"
    ],
    "storage": []
  }
}
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.
2.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Hi @jiacheng-L.  Thank you for your feedback and we regret that you're experiencing difficulties.   I'll need to ask for some additional information before I'm able to route this over to the team that would be best able to assist.

Can you help me understand which Azure package you're working with and what steps would be needed to repro the output that you're showing?

**Comment by jsquire** [comment]
As we do not have the requested information to triage this, I'm closing the issue out.   If you're still experiencing difficulties, please open a new issue with the additional context and we'd be happy to assist.
