### ISSUE TITLE
timeout argument ignored

### ISSUE THREAD

**Issue by nfoscolos** [Azure/azure-sdk-for-net#22411]
https://github.com/Azure/azure-sdk-for-net/blob/63e9552523a06ca62d7c39e61a7fe5e5123f8e1b/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Primitives/SharedAccessSignatureTokenProvider.cs#L97

The timeout input is ignored in this method

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//cc: @shankarsama

**Comment by ramya-rao-a** [comment]
@nfoscolos Apologies for the delay in response here. 

Please note that the Microsoft.Azure.ServiceBus package is now deprecated. A newer package Azure.Messaging.ServiceBus is available as of November 2020. While the older package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the [getting started guide](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues) and  [migration guide](https://aka.ms/azsdk/net/migrate/sb) for more details.

If you still have issues using the older Microsoft.Azure.ServiceBus package, please use your [Azure support plan](https://azure.microsoft.com/support/options/) to open an [Azure support ticket](https://azure.microsoft.com/support/create-ticket/).
