### ISSUE TITLE
Please add details of Status field

### ISSUE THREAD

**Issue by heyucongtom** [Azure/azure-sdk-for-net#22425]
Add these descriptions: https://docs.microsoft.com/en-us/azure/data-factory/monitor-programmatically

> Pipeline run information
> For pipeline run properties, refer to PipelineRun API reference. A pipeline run has different status during its lifecycle, the possible values of run status are listed below:
> 
> Queued
> InProgress
> Succeeded
> Failed
> Canceling
> Canceled
> 

to the status (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.pipelinerun.status?view=azure-dotnet#Microsoft_Azure_Management_DataFactory_Models_PipelineRun_Status) page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82c2de2d-d5e8-e192-4bcb-7de9ec8b3e26
* Version Independent ID: 00ab9c63-ac31-954e-f395-7a50b84324db
* Content: [PipelineRun Class (Microsoft.Azure.Management.DataFactory.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.pipelinerun?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.DataFactory.Models/PipelineRun.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.DataFactory.Models/PipelineRun.xml)
* Service: **data-factory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
@allenjzhang:  I've routed this to the service team, as I believe the documentation in question is populated directly from the swagger.  Please feel free to reroute if I'm mistaken.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by shawnxzq** [comment]
@LijuanZ Could you please take care of this? Thanks!

**Comment by shawnxzq** [comment]
@LijuanZ Please check whether we can add this in the swagger, currently, rest API document is generated from swagger.

**Comment by LijuanZ** [comment]
Sure, will do. Thanks!

**Comment by shawnxzq** [comment]
@LijuanZ Please share the status here if it's done, we need to update the every month till the issue closed, thanks!

**Comment by LijuanZ** [comment]
@shawnxzq the work item is still in backlog, will update here when it's done, thanks!

**Comment by shawnxzq** [comment]
Feature request, add the feature-request tag.

**Comment by shawnxzq** [comment]
@LijuanZ  Any update on this? Thanks!

**Comment by LijuanZ** [comment]
@shawnxzq Swagger change has been merged

**Comment by shawnxzq** [comment]
Thanks @LijuanZ !
