### ISSUE TITLE
Enrich authentication failed exceptions with more information about credential

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#22424]
It's hard to debug auth errors and even harder with DefaultAzureCredential when you don't know which one was selected.

Can we attach more diagnostic information to 403 failures in clients?

related https://github.com/Azure/azure-sdk-for-net/issues/8948

**Comment by pakrym** [comment]
cc @schaabs @christothes

**Comment by christothes** [comment]
> Can we attach more diagnostic information to 403 failures in clients?

What did you have in mind? Logging, stashing data in the exception, other ideas?

**Comment by pakrym** [comment]
I was leaning toward the data on exception. We would have plenty of logging with your latest change but it's not that easy to get to logs quickly.

**Comment by heaths** [comment]
The trickier bit will be that the successful provider *could* change when, for example, refreshing an expired token, right? How this data is retained and what code uses that should be tolerant of that data changing. It's probably unlikely in most cases, but certainly possible.
