### ISSUE TITLE
Event Grid docs point to old libs

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#22437]
**Describe the bug**
This doc: https://docs.microsoft.com/en-us/dotnet/api/overview/azure/eventgrid

References old libs.

**Expected behavior**

Should ref new libs.

**Comment by jsquire** [comment]
//cc: @spelluru

**Comment by spelluru** [comment]
Hi @jsquire - Thank you. I am back to work. I have updated the index page in [this PR ](https://github.com/Azure/azure-docs-sdk-dotnet/pull/2048). Instead of showing the code on this page, I just linked to the readme page that gives an overview along with the sample code. Thanks.

**Comment by jsquire** [comment]
@spelluru:  There was one minor comment that I left about a link;  otherwise, looks good to me.    Give me a yell when you're comfortable and would like me to merge.

**Comment by spelluru** [comment]
@jsquire - Fixed the link. Please merge when you get a chance. Thanks.

**Comment by jsquire** [comment]
All merged in.   Thanks, @spelluru!    

@jongio:  I'm going to close this issue out; changes should flow in with the next docs sync.
