### ISSUE TITLE
Event Hubs: Update snippet replacement syntax

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#22435]
# Summary

For snippets, there is often a need to differentiate the code that appears when rendered versus that which actually runs as part of the test.  Historically, this was done though an esoteric set of comment markers, `//@@` and `/*@@*/`.  In order to aid readability and clarity, the `SNIPPET` compiler constant has been added as to the CI environment, allowing the use of an `#if` preprocessor directive.

The snippets used with Event Hubs should be updated to remove the comment markers and make use of the preprocessor directive.

# Scope of Work

- The snippets across the Event Hubs family of packages should be refactored to remove the `//@@` and `/*@@*/` comment use and instead use a preprocessor directive in the form of `#if SNIPPET .. #endif` 

- Included in these efforts are:
    - The core Event Hubs package, with snippets found in its [`/tests/Snippets`](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Azure.Messaging.EventHubs/tests/Snippets) path.
    - The processor package, with snippets found in its [`/tests/Snippets`](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/tests/Snippets) path.
    - The Function extensions package,  in its [`/tests/Samples`](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/Samples) path.

# Success Criteria

- There are no remaining occurrences of the `//@@` or `/*@@*/` in the Event Hubs samples discussed in the scope.

- The samples render with no changes after the refactoring has been performed.

- The samples tests are valid, can be run, and pass reliably.

- Existing tests continue to produce deterministic results and pass reliably.

# References and Related

- [Update Snippet replacement syntax (#20431)](https://github.com/Azure/azure-sdk-for-net/issues/20431)

**Comment by pakrym** [comment]
FYI, There are some old-style snippets left in the migration guide.

**Comment by jsquire** [comment]
Thanks for the heads-up.   Looks like we missed a few.   I'll get those changed over.

**Comment by jsquire** [comment]
The missed set is fixed by #25684
