### ISSUE TITLE
Clarify behavior if no record is found

### ISSUE THREAD

**Issue by jlautman** [Azure/azure-sdk-for-net#22432]
It is unclear from the documentation what GetAsync does if no such record is found. Does it throw an exception, return null, or return a non-null RecordSet object?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d38978c-39fc-8655-90e4-e960b575f960
* Version Independent ID: ad22de88-e4fa-9e61-c1d3-251c22bc53c2
* Content: [RecordSetsOperationsExtensions.GetAsync(IRecordSetsOperations, String, String, String, RecordType, CancellationToken) Method (Microsoft.Azure.Management.Dns) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.dns.recordsetsoperationsextensions.getasync?view=azure-dotnet#Microsoft_Azure_Management_Dns_RecordSetsOperationsExtensions_GetAsync_Microsoft_Azure_Management_Dns_IRecordSetsOperations_System_String_System_String_System_String_Microsoft_Azure_Management_Dns_Models_RecordType_System_Threading_CancellationToken_)
* Content Source: [xml/Microsoft.Azure.Management.Dns/RecordSetsOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Dns/RecordSetsOperationsExtensions.xml)
* Service: **dns**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
@allenjzhang: Routing this to the service team, as it appears the documentation is coming from the service swagger.  Please feel free to reroute if I'm mistaken.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jlautman** [comment]
I don't see any change made. There's still no documentation that I can find
for how the library behaves if there's an error or no such record found.

**Comment by bretthacker** [comment]
This is quite the joke. Nobody answers for 2 years, then it's closed because it was inactive for 2 years. And...it's still not answered. Clearly DNS isn't important to Microsoft.
