### ISSUE TITLE
Event Hubs: Legitimize the stress test suite

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#22436]
# Summary

While effective, the current suite of stress tests for Event Hubs is largely ad-hoc and lives in a private repository.  With a common approach to long-running stress tests now agreed upon, the suite should be revised for a more structured approach, reworked to fit the common approach, integrated with the shared hosting assets, and moved into the official repository.

This issue is primarily intended for personal thoughts and notes;  it is not expected that it be a clear and comprehensive work item that could be fully understood and implemented by others.  Please expect some gaps in descriptions and a non-trivial amount of assumed knowledge.

# Scope of Work

- Refactor the existing ad-hoc stress tests to remove code duplication, follow a modular architecture, and follow the conventions used for the other Event Hubs areas.  Like the performance suite, the stress tests should make use of the Event Hubs shared code project for common items.

- Integrate metrics collection with Application Insights, following the common conventions agreed upon.  _(coordinate with Ben and Richard)_

- Integrate chaos injection with the current platform toolset.  _(coordinate with Ben and Richard)_

- Adjust the architecture to support the concept of "roles" for the stress testing, allowing scenarios to be focused without taking on additional resource overhead.  For example, tests for the event processor should not include an embedded producer; that should exist as an independent role that may be deployed separately and then coordinated with.   Roles should probably include:
    - Publisher
    - Processor
    - Consumer 
    - Partition Receiver

- Allow for the concept of an orchestrator to control scenarios.  The orchestrator will be responsible for deploying roles needed and coordinating between the roles for a scenario.   For example, the orchestrator should be able to run a processor-based scenario that:
    - Deploys a set of publishers
    - Deploys a set of processors
    - Configures both roles to shared some form of key/value store to coordinate around what events have been published
    - Can simulate processor scale up/down
    - Configures both roles to publish metrics to some common location.

- Roles should have the ability to react to configuration that is specific to the scenario that they're running in.  For example, a publisher should be able to be told to collect metrics or not, allowing noise to be removed from consuming scenarios.

- Stress tests should use an approach to bootstrap consistent with Test Resources and the dynamic creation of child entities.  It should be possible to run multiple scenarios concurrently without them interfering with one another and resources should be cleaned up after the run.

# Success Criteria

- The stress tests have been integrated into the repository under the `Azure.Messaging.EventHubs` package, in a dedicated `stress` folder.

- The stress tests can be run locally with reasonable configuration/effort needed.

- The stress tests can be deployed to AKS, using the common platform elements.

- Stress tests have their own ReadMe that details how to run different scenarios, highlighting local runs.

# Reference and Resources

- [Getting Started guide](https://github.com/Azure/azure-sdk-tools/tree/master/tools/stress-cluster/chaos)
- [Richard's work for JS](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/servicebus/service-bus/test/stress)
- [Event Hubs metrics discussion](https://github.com/Azure/azure-sdk/issues/3200)
- [Event Hubs quick-n-dirty stress harness](https://github.com/kinelski/EventHubStressTest)
- [Stress wiki](https://aka.ms/azsdk/stress) **(Microsoft Internal)**
- Teams channel for stress  **(Microsoft Internal)**

**Comment by jsquire** [comment]
//cc: @richardpark-msft

Just in case you had any thoughts on things that we've talked about and I forgot to include.

**Comment by richardpark-msft** [comment]
This looks really great to me. Some comments, but mostly just additive:

> Adjust the architecture to support the concept of "roles" for the stress testing, allowing scenarios to be focused without taking on additional resource overhead. 

I like thinking about this not just as overhead, but also a necessity if we're trying to mimic customers environments with our testing:
- Enabling independent scaling of producers vs consumers (we'll have way more consumers than producers, more than likely)
- Be realistic about how apps are generally written - consuming/producing are typically separate apps (this is our theory, at least).
- Possible re-use in other scenarios that are not EH specific (ie, as we build out _more_ stress testing in other areas it might be useful to reuse some of these producing/consuming containers).

> Allow for the concept of an orchestrator to control scenarios. The orchestrator will be responsible for deploying roles needed and coordinating between the roles for a scenario.

I'd slate this as a "phase 2" feature, mostly because it _might_ be complicated and we could technically use replicasets to accomplish 95% of this. It might be worth calling this out just to make it clear that there are some cheap options here (Kubernetes specific, but still), since it sounds larger than it might be.

> Stress tests should use an approach to bootstrap consistent with Test Resources and the dynamic creation of child entities. It should be possible to run multiple scenarios concurrently without them interfering with one another and resources should be cleaned up after the run.

I know this is written more as requirements, but this is very much in @benbp's court and he's got a lot of great stuff here (got a chance to test drive it last week). You could technically leave this off here because there'll be no real responsibilities to the person building out these tests for .net

As always, love reading these.

**Comment by benbp** [comment]
This is great! Thinking about this from the perspective of the "stress test platform" I think there are a few key design decisions we'll want to make (granted these may change as we get further feedback from our work):

1. Should this class of testing try to conform to having started and finished states, or should we instead consider it as a workflow(s) that runs continuously and generates metrics/data until we stop it? With the current job model, start/finish aligns to pod exit codes. I could see the main job corresponding to the work the orchestrator is doing. If it isn't loop based, then whenever it's done with all its scale up/down work it will exit and we can come up with a generic way to trigger cleanup of child resources.
2. Related to ^^, do we want the orchestrator to run in the cluster, or be something manually invoked by a user? Further, should we expect that these tests are ever run as part of a scheduled pipeline/release gate, or rather that they are only kicked off manually (even if that means they run "forever").
  - Perhaps in the above scenarios, a triggered pipeline's job is to update the running tests to use new SDK versions.

To me the most important question is to what level do we generalize the orchestration pieces? I.e. we could go as far as supporting some sort of generic kubernetes object modification workflow, but I think it would be better to start with simple scripts wrapped in jobs that patch objects imperatively, and maybe eventually graduate to making those patch operations event driven or even [kubernetes controllers](https://kubernetes.io/docs/concepts/architecture/controller/) that live in cluster. Script-based orchestration will be easier to share across languages though.

> Roles should have the ability to react to configuration that is specific to the scenario that they're running in. For example, a publisher should be able to be told to collect metrics or not, allowing noise to be removed from consuming scenarios.

This might be a good area for us to come up with a general convention that future stress tests can follow. I can see this taking several forms, depending on whether we take a feature flag or IPC style approach, such as state sharing via [configmaps](https://kubernetes.io/docs/concepts/configuration/configmap/) and env vars, sockets on a shared volume, http endpoints between pods, etc. It also depends on whether we want to support behavioral changes with or without process/container restarts.

> Adjust the architecture to support the concept of "roles" for the stress testing, allowing scenarios to be focused without taking on additional resource overhead.

I think with the [helm package](https://helm.sh/) model I've been building out, this should be rather easy to accomplish. We can define different "roles" as their own helm packages, which can be configured and deployed independently or rolled up as dependencies into a main package.

> Stress tests should use an approach to bootstrap consistent with Test Resources and the dynamic creation of child entities. It should be possible to run multiple scenarios concurrently without them interfering with one another and resources should be cleaned up after the run.

Similar to what @richardpark-msft said, I've already added support for this, so all you need to do is include an arm template/bicep file in the directory and resources will be deployed before the container starts.
