### ISSUE TITLE
SqlServer entity missing data compared to CLI response

### ISSUE THREAD

**Issue by ilia-cy** [Azure/azure-sdk-for-net#22446]
I'm using the SDK to retrieve SqlServer entities - `IAzure.SqlServers.ListAsync()`.
I'm seeing a difference between the response given by the SDK and the response given by the CLI `az sql server list` command.
Example for missing fields:

- `minimalTlsVersion`
- `privateEndpointConnections`
- `publicNetworkAccess`
- `identity`

Looking at the entity response [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.sql.fluent.isqlservers?view=azure-dotnet), I can't see any fields that can correlate to the fields I stated above.
Same regarding the `ServerInner` [entity](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.sql.fluent.models.serverinner?view=azure-dotnet), which also lacks these parameters.

Am I missing some other API in which I can retrieve the fields that are returned by the Azure CLI?

**Environment:**
- Microsoft.Azure.Management.Fluent 1.36.1
- Mac OS X 10.16, Microsoft.NETCore.App 3.1.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
hi @WeidongXu-microsoft, could you help to look at this Fluent issue? thanks.

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

**Comment by weidongxu-microsoft** [comment]
The Fluent .NET SDK is still on composite-v1 of Sql, while latest is v5. It is possible that v1 missed some properties which is added later.
However there is huge breaking changes across v1 to v3 and to v5, hence it is almost not possible for Fluent SDK to catch to latest while not break everyone else.

Hence I would recommend wait for new generation SDK on https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html, and migrate to it when available.

**Comment by lilyjma** [comment]
@ilia-cy : I'm assuming this issue has been resolved. Tagging it as so. Please feel free to let us know otherwise.
