### ISSUE TITLE
[Storage] Server failed to authenticate the request against China cloud and UsGov.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-sdk-for-net#22456]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

### Error Description:
Method `Batch_AzureSasCredential` test about authenticate the request failed. The Error Message as follow:
```
Azure.RequestFailedException : Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Status: 403
ErrorCode: AuthenticationFailed

Additional Information:
AuthenticationErrorDetail: Signature fields not well formed.

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-error-code: AuthenticationFailed
x-ms-request-id: 790ddb08-e01e-002f-725a-6eb353000000
x-ms-version: 2019-02-02
x-ms-client-request-id: c2b99276-3347-458b-888e-c98f32a920ca
Date: Thu, 01 Jul 2021 09:21:59 GMT
Content-Length: 409
Content-Type: application/xml
```

### Error Track:
Detail: [Code Link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs.Batch/tests/BlobBatchClientTests.cs#L216-L232)
![image](https://user-images.githubusercontent.com/81678720/124531809-d9029e00-de41-11eb-88ad-d394d60f2dd5.png)
The exception above throws by Method `DeleteBlobsAsync`.
But the error message points signature, it was set in Method `ToSasQueryParameters`.

### Expected Behavior
The investigation so far, what we know is that we need to use different SignedVersion in different clouds. Such as:
Public: "2020-08-04"
UsGov: "2020-02-10"
China: "2020-02-10"
We want to know whether sas is supported in UsGov? If supported, does it different from in Public?

@jongio, @benbp, @kyle-patterson, @tg-msft  for notification.

**Comment by amishra-dev** [comment]
SAS is supported in various clouds, but you are right that it needs the right sv, what sv did you pass?

**Comment by zedy-wj** [comment]
"2020-08-04" in public could pass, but neither "2020-08-04" nor "2020-02-10" could not pass in UsGov.

**Comment by amishra-dev** [comment]
@zedy-wj can do a fresh repro and send me and email about this (assuming by the verbage that you are a MS employee/contractor)

**Comment by zedy-wj** [comment]
Steps to reproduce this issue :

1. Clone the [codes](https://github.com/zedy-wj/azure-sdk-for-net/tree/ReproduceIssue).

2. Create a Storage Account in `Public` and `UsGov`. We need three parameters in Storage Account : "BlobServiceEndPoint", "AccountName" and "AccountKey".

3. Test it in `Public` : Replace "BlobServiceEndPoint", "AccountName" and "AccountKey" in files [StorageTestBase.cs](https://github.com/zedy-wj/azure-sdk-for-net/blob/ReproduceIssue/sdk/storage/Azure.Storage.Common/tests/Shared/StorageTestBase.cs#L248), [BlobTestBase.cs](https://github.com/zedy-wj/azure-sdk-for-net/blob/ReproduceIssue/sdk/storage/Azure.Storage.Blobs/tests/BlobTestBase.cs#L292-L293) and [BlobBatchClientTests.cs](https://github.com/zedy-wj/azure-sdk-for-net/blob/ReproduceIssue/sdk/storage/Azure.Storage.Blobs.Batch/tests/BlobBatchClientTests.cs#L225-L226)  with actual value of Storage Account you created in cloud `Public`. 

- Expected Result : Pass 

- Actual Result : Pass 

4. Test it in `UsGov` : Repeat the previous step with actual value of Storage Account which you created in cloud `UsGov`. 

- Expected Result : Pass
- Actual Result : Failed 
- ErrorMessage : 
```
    Azure.RequestFailedException : Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
    RequestId:6b49512f-e01e-0026-5f85-77a6a1000000
    Time:2021-07-13T01:23:58.6210771Z
    Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
    ErrorCode: AuthenticationFailed
    
    Additional Information:
    AuthenticationErrorDetail: Signature fields not well formed.
```

@jongio, @v-xuto for notification.

**Comment by amishra-dev** [comment]
closing it here in favor of email
