### ISSUE TITLE
Factories for QueueRuntimeProperties, TopicRuntimeProperties and SubscriptionRuntimeProperties

### ISSUE THREAD

**Issue by devgorbenko** [Azure/azure-sdk-for-net#22467]
**Library or service name.**
Azure.Messaging.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
There is no way to mock some `ServiceBusAdministrationClient` methods due to inability to construct returned models.

**Comment by jsquire** [comment]
Hi @devgorbenko.   Thank you for reaching out and we regret that you're experiencing difficulties.   It does indeed appear that these were overlooked in the `ServiceBusModelFactory`;  tagging and routing to the team member best able to assist.
