### ISSUE TITLE
Add support for double.NaN for table access 

### ISSUE THREAD

**Issue by punio** [Azure/azure-sdk-for-net#22486]
**Library or service name.**
Azure.Data.Tables
 
**Is your feature request related to a problem? Please describe.**
When accessing table storage using WindowsAzure.Storage 9.3.3, I was able to read and write double.NaN (NegativeInfinity, PositiveInfinity) to Edm.Double. 
In Azure.Data.Tables, reading and writing such as double.NaN raises an exception.

I want to use it in an existing system that handles NaN, so please support it if possible.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by punio** [comment]
Any update on this one?

**Comment by christothes** [comment]
This issue is dependent on [this fix.](https://github.com/Azure/autorest.csharp/pull/1519) Once it propagates to the repo, I'll create a fix.

**Comment by christothes** [comment]
waiting on #24080 to merge

**Comment by AlexGhiondea** [comment]
@christothes can this move forward now?

**Comment by christothes** [comment]
This should have been closed by #24140.
