### ISSUE TITLE
[BUG] Bad SaS when settting the ServiceVersion

### ISSUE THREAD

**Issue by stwolfe** [Azure/azure-sdk-for-net#22489]
**Describe the bug**
The SaS produced when needing to set the service version is not valid. 

**Expected behavior**
Successful access to the requested storage service using the generated SaS token.

**Actual behavior (include Exception or Stack Trace)**
INFO: Authentication failed, it is either not correct, or expired, or does not have the correct permission -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /home/vsts/go/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.10.1-0.20210407023846-16cf969ec1c3/azblob/zc_storage_error.go:42
===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====
Description=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:f694ca28-b6e5-0e86-773a-6b596fca857b
Time:2021-07-06T23:05:10.9506641Z, Details:
   AuthenticationErrorDetail: sv is either not in the correct format or is not equal or later than version 2012-02-12
   Code: AuthenticationFailed
   PUT http://blobcopydataset.blob.dbe-1d5nhq2-1.microsoftdatabox.com/blobcopydataset2/dataset/foo.txt?se=2021-07-07t23%3A05%3A10z&sig=-REDACTED-&sp=racwdxlt&sr=c&sv=2020-08-04&timeout=901
   Content-Length: [202]
   User-Agent: [AzCopy/10.11.0 Azure-Storage/0.13 (go1.15; Windows_NT)]
   X-Ms-Blob-Cache-Control: []
   X-Ms-Blob-Content-Disposition: []
   X-Ms-Blob-Content-Encoding: []
   X-Ms-Blob-Content-Language: []
   X-Ms-Blob-Content-Md5: []
   X-Ms-Blob-Content-Type: [text/plain]
   X-Ms-Blob-Type: [BlockBlob]
   X-Ms-Client-Request-Id: [8f6c75f5-df74-49a6-6558-381576d21a4f]
   X-Ms-Version: [2019-07-07]

**To Reproduce**
```C#
    var serviceOptions = new BlobClientOptions(BlobClientOptions.ServiceVersion.V2019_02_02);
    var blobClient = new BlobServiceClient(connectionString, serviceOptions);
    var containerClient = blobClient.GetBlobContainerClient(containerName);
    var sasUri = containerClient.GenerateSasUri(BlobContainerSasPermissions.All, DateTimeOffset.UtcNow.AddDays(1));

    Console.WriteLine(sasUri.ToString());
```

Result:

```
...   ?sv=2020-08-04   ...
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.9.1] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

.NET SDK (reflecting any global.json):
 Version:   5.0.400-preview.21277.10
 Commit:    024913d52c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400-preview.21277.10\

Host (useful for support):
  Version: 6.0.0-preview.3.21201.4
  Commit:  236cb21e3c

.NET SDKs installed:
  2.1.524 [C:\Program Files\dotnet\sdk]
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.116 [C:\Program Files\dotnet\sdk]
  5.0.204 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.3.21201.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by stwolfe** [comment]
The URI created above is being used by azcopy 10 to try to upload a blob to the Blob service running on Azure Stack Edge.

**Comment by amishra-dev** [comment]
Hi @stwolfe, you are using Microsoft DataBox, i am not entirely sure which service version is there on your databox, would it be possible to reach out to us through microsoft support?
Meanwhile i will check why the SAS is not including the SV you passed

**Comment by amishra-dev** [comment]
This was resolved offline. The resolution was to downgrade the SDK to a version that matches the storage version in Databox.
