### ISSUE TITLE
[QUERY] DownloadToAsync function throws 412 "The condition specified using HTTP conditional header(s) is not met" exception

### ISSUE THREAD

**Issue by dianacrt** [Azure/azure-sdk-for-net#22485]
**Query/Question**
How can we help?
I have an Azure Front Door in front of two storage accounts. I am using AAD authentication and I am trying to download a large file using DownloadToAsync function, but it throws "The condition specified using HTTP conditional header(s) is not met" exception. This is a snippet of the code:

```csharp
                ClientSecretCredential credential =
                new ClientSecretCredential(
                    TENANT_ID,
                    CLIENT_ID,
                    CLIENT_SECRET,
                    new TokenCredentialOptions() { AuthorityHost = new Uri("https://login.windows.net/") });

                BlobServiceClient service = new BlobServiceClient(new Uri(AZURE_FRONT_DOOR_URI), credential);
                var containerClient = service.GetBlobContainerClient(CONTAINER_NAME);

                var blob2 = containerClient.GetBlobClient(BLOB_NAME);

                using FileStream stream = File.Create(FILE_PATH);
                await blob2.DownloadToAsync(stream).ConfigureAwait(false);
```

I also tried with an older version of the Azure.Storage.Blobs ( v9.2) and I had the same problem there with DownloadToFileParallelAsync function. However, it seemed that with DownloadToFileAsync it works fine, so the error is thrown when the requests are made in parallel.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.9.1
 - Hosting platform or OS and .NET runtime version: Windows 10  .NET Core SDK 2.1.816 
 - IDE and version : Visual Studio 16.10

**Comment by amnguye** [comment]
That's interesting that this error was thrown but `BlobRequestConditions` was not attached to the call. The error looks very similar to this issue.
https://github.com/Azure/azure-sdk-for-net/issues/20931
Where a one shot upload would work but not a parallel upload. The only workaround I see here is to not do the parallel download and do a one shot download where we do the download in one request.

I will attempt to repro, maybe it has something to do with FileStream.

**Comment by dianacrt** [comment]
I managed to find a workaround, I think the reason why it was not working was that the Azure Front Door was not sending all the parallel GET requests to the same storage so the request_id from the header was different which caused the 412 error response. Enabling session affinity on Azure Front Door made the function work. However, the download function still throws an "Object reference is null" error during the download.

What is usually the best strategy to scale out storage accounts? I am guessing these errors happen because the storage is not compatible with Azure Front Door?

**Comment by amnguye** [comment]
What does "same storage" mean, you mean the same storage account? or the same blob? Either way that sounds like a problem with Azure Front Door which you should interface with them to figure out.

Is there a full stack trace of the error "Object reference is null". I can't tell which object it's talking about and how it's getting thrown.

I think your last question is not appropriate for this forum, as this is not a specifically an SDK question and we cannot give official guidance on that. We have many other different forums for this type of discussion. https://support.microsoft.com/en-us/topic/contact-microsoft-azure-support-2315e669-8b1f-493b-5fb1-d88a8736ffe4
