### ISSUE TITLE
List partition keys

### ISSUE THREAD

**Issue by thiagorizzo** [Azure/azure-sdk-for-net#22492]
**Query/Question**
Is there any way to get partitions keys sent to a topic?

**Environment:**
 - Azure.Messaging.ServiceBus 7.1.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @thiagorizzo,
There is not a way to do this currently. Can you describe what you are trying to achieve with this information?
