### ISSUE TITLE
Operational Insights: Broken link to example

### ISSUE THREAD

**Issue by afratila** [Azure/azure-sdk-for-net#22490]
Hi,

There is a broken link on this page under "Remarks" where it says "[Here] (/documentation/2-Using-the-API/Query)". Could this be fixed, I'd like to read the example. Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2463fe7f-e35e-9db5-3f8a-7a0c56236f02
* Version Independent ID: 2b903fcd-9956-c2e8-0167-f4f2ea89270c
* Content: [OperationalInsightsDataClient.QueryWithHttpMessagesAsync(String, Nullable&lt;TimeSpan&gt;, IList&lt;String&gt;, Dictionary&lt;String,List&lt;String&gt;&gt;, CancellationToken) Method (Microsoft.Azure.OperationalInsights) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.operationalinsights.operationalinsightsdataclient.querywithhttpmessagesasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.OperationalInsights/OperationalInsightsDataClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.OperationalInsights/OperationalInsightsDataClient.xml)
* Service: **operational-insights**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by navba-MSFT** [comment]
@afratila Apologies for the late reply. Thanks for sharing the feedback. We have filed the above PR which is pending under review. In the meantime, if you have any queries please do let me know. Awaiting your reply.
