### ISSUE TITLE
[BUG] Azure.Data.Tables cannot initialize TableServerClient/TableClient 

### ISSUE THREAD

**Issue by daiyk** [Azure/azure-sdk-for-net#22491]
**Describe the bug**
Please provide the description of issue you're seeing.
I try to use the new Azure.Data.Tables in Unity to connect with my Azure Storage account. 
either create tableclient or create tableserverclient failed and throw exception, the code:
`tableAccount = new TableServiceClient(connectionString);`
or
```
var client = new TableClient(
                            connectionString,
                            tableName);
```
both trigger exception as follows, I also try other authentication methods like Shared Key Signatures, still the same exception:

```
"System.TypeInitializationException: The type initializer for \'Azure.Data.Tables.TableClientOptions\' threw an exception. ---> 
System.TypeInitializationException: The type initializer for \'Azure.Core.Pipeline.HttpClientTransport\' threw an exception. ---> 
System.NotImplementedException: The method or operation is not implemented.\r\n  at
System.Net.Http.HttpClientHandler.get_MaxConnectionsPerServer () [0x00000] in <efff4cb93af94c0c950db61b78368b54>:0 \r\n  at Azure.Core.Pipeline.ServicePointHelpers.SetLimits (System.Net.Http.HttpMessageHandler messageHandler) [0x0001c] in <626cc779b13d418999ef918abad55406>:0 \r\n  at Azure.Core.Pipeline.HttpClientTransport.CreateDefaultClient () [0x0000b] in <626cc779b13d418999ef918abad55406>:0 \r\n  at Azure.Core.Pipeline.HttpClientTransport..ctor () [0x00000] in <626cc779b13d418999ef918abad55406>:0 \r\n  at Azure.Core.Pipeline.HttpClientTransport..cctor () [0x00000] in <626cc779b13d418999ef918abad55406>:0 \r\n   --- End of inner exception stack trace ---\r\n  at Azure.Core.ClientOptions..ctor () [0x00000] in <626cc779b13d418999ef918abad55406>:0 \r\n  at Azure.Data.Tables.TableClientOptions..ctor (Azure.Data.Tables.TableClientOptions+ServiceVersion serviceVersion) [0x00000] in <5b9b26bedd314731972adb66b865bbcc>:0 \r\n  at Azure.Data.Tables.TableClientOptions..cctor () [0x00000] in <5b9b26bedd314731972adb66b865bbcc>:0 \r\n   --- End of inner exception stack trace ---\r\n  at Azure.Data.Tables.TableClient..ctor (System.String connectionString, System.String tableName, Azure.Data.Tables.TableClientOptions options) [0x0008e] in <5b9b26bedd314731972adb66b865bbcc>:0 \r\n  at Azure.Data.Tables.TableClient..ctor (System.String connectionString, System.String tableName) [0x00000] in <5b9b26bedd314731972adb66b865bbcc>:0 \r\n  at Rimon.AzureStorage.Common.AzureTable+<CreateAzureTableStatic>d__6.MoveNext () [0x00018] in E:\\Rimon\\handhold-development\\Assets\\Rimon\\AzureStorage\\Common\\AzureTable.cs:48 "
```

**Expected behavior**
What is the expected behavior?
the init of tableserveclient or tableclient should be success without exception

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
trigger System.NotImplementedException

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Simple code:
`tableAccount = new TableServiceClient(connectionString);`

**Environment:**
 - Azure.Data.tables 12.1.0, Unity 2020.3.6f LTS
 - .NET SDKs 5.0.301 and Windows 10 10.0.19041
 - IDE and version : [e.g. Visual Studio Version 16.10.2

Update:

I tested it on a Xamarin project, the TableClient can be normally initialized, so I don't know whether this bug can be related to Unity.
I also notice that other guys also complains about the azure storage working with Unity, like  this
[Azure blob storage](https://stackoverflow.com/questions/67703166/getting-notimplementedexception-when-attempting-azure-connection-with-unity-c). I think it need to be tested on Unity to solve the problem.

**Comment by jsquire** [comment]
@pakrym:  This looks like it is likely to be related to the Core pipeline moreso than the Tables client.  Would you be so kind as to offer your thoughts and reroute if needed?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by daiyk** [comment]
Can you tell me when you will release this fix? we need it in our package development. I tried to pack this updated Azure.Core source code in visual studio, it always report "No entry for version [1.17.0-beta.1] found in the ChangeLog [E:\azure-sdk-for-net-main\azure-sdk-for-net-main\sdk\core\Azure.Core\CHANGELOG.md]. "....

**Comment by pakrym** [comment]
@daiyk, you can get a nightly build from the https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json feed.
