### ISSUE TITLE
EventGridPublisherClient constructor does not support TokenCredentials for AAD authentication

### ISSUE THREAD

**Issue by jordanfryer** [Azure/azure-sdk-for-net#22505]
We have a requirement to use AAD authorization on all Azure Resources (versus SAS / Key credentials). For most client libraries this is supported through a constructor on the client using the Azure.Core.TokenCredentials class. However, EventGridPublisherClient does not have such a constructor. Is this something that is planned to be supported?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
This work is planned as part of https://github.com/Azure/azure-sdk-for-net/issues/22109

**Comment by jordanfryer** [comment]
Thanks @JoshLove-msft for the quick update, I see that is tagged as the July 2021 milestone? Does this mean I should expect this to be available for trial end of the month timeframe?

**Comment by JoshLove-msft** [comment]
Hi @jordanfryer, we will be releasing an update that includes TokenCredential support next week.

**Comment by JoshLove-msft** [comment]
This is now available - https://www.nuget.org/packages/Azure.Messaging.EventGrid/4.5.0

**Comment by jordanfryer** [comment]
This is great! Thank you.
