### ISSUE TITLE
Adding test setup in scenario tests for Azure SQL Advisors and Recommended Actions APIs

### ISSUE THREAD

**Issue by anilyela** [Azure/azure-sdk-for-net#2250]
In Sql scenario tests, we are adding session records without any test setup. This will make it difficult for next developer to generate session records with similar responses for new versions of APIs.

See Mark's comment in pull request: https://github.com/Azure/azure-sdk-for-net/pull/2203
"You have json files, which indicate that you ran these tests against live azure. It looks like youi set up a bunch of Sql asssets in some subscription and then just ran list cmdlets against this setup. If this is the case, the next person who has to make a change here will have a great deal of difficulty in running these tests live for new recordings - they will basically have to either replicate exactly the setup you had live, or they will have to change the code.

If these changes are time sensitive, it is OK to check-in and add the test setup as part of the tests within the next month. If you want to do this, please file a bug for this in github, assign to yourself and reference it here."

**Comment by jaredmoo** [comment]
Test improvement for hyak-based client not needed because we are moving forward with autorest-based client. When advisors api is added to autorest-based client, the test will need to be fully automated before I sign off.
