### ISSUE TITLE
Event Grid API ref points to wrong location

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#22515]
This page:
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/Messaging.EventGrid-readme

API reference doc link points to:
https://azure.github.io/azure-sdk-for-net/eventgrid.html

Which is this:
![image](https://user-images.githubusercontent.com/2163001/124838272-5827cd00-df3b-11eb-9274-1739da361ea8.png)

And I can't find the API ref easily.

**Comment by jsquire** [comment]
This looks like the docs are rendering correctly, but our [README](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventgrid/Azure.Messaging.EventGrid) is pointing to an incorrect location.

![image](https://user-images.githubusercontent.com/913445/124929643-ab972b00-dfce-11eb-8431-0dec4a989282.png)
