### ISSUE TITLE
Decide on "knowledgebase" vs "knowledge base"

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#22510]
I agree it probably should be "knowledge base" in writing everywhere, but that also conflicts with "knowledgebase" (as opposed to, say, "knowledgeBase") throughout the swagger. @annatisch @rokulka do you see any problems with us in written language to use "knowledge base" everywhere consistently unless, of course, referring to a parameter or property name?

_Originally posted by @heaths in https://github.com/Azure/azure-sdk-for-net/pull/21810#discussion_r664909590_

**Comment by annatisch** [comment]
I have no concerns with documenting this in text as "knowledge base" - I will make the adjustments in Python :)

**Comment by heaths** [comment]
That's probably enough, too. But it does seem odd to refer to it in docs as "knowledge base" but have types and parameter names as "knowledgebase" instead of "knowledge_base" or "knowledgeBase".

/cc @rokulka

**Comment by annatisch** [comment]
I don't feel too weirdly about having that distinction between docs and parameter name - I don't think anyone will be tripped up by it. I prefer `knowledgebase` to `knowledge_base` as a parameter name.

**Comment by jsquire** [comment]
@heaths:  Is that `QnA Maker` label correct or do we need a new service label for this?

**Comment by annatisch** [comment]
After doing some googling - it does seem that "knowledge base" is the correct form here. @rokulka do you have an "official service team position" here?

After updating the documentation, I confess now "KnowledgebaseQueryParameters" looks odd to me - and would not be opposed to more universally upgrading to "KnowledgeBase".

If we did so, in terms of snake case, I would probably end up with something like:
```python
client.query_knowledge_base(
    parameters=KnowledgeBaseParameters("foo")  # Note the shorted keyword arg name
)
```

This would require some swagger spec tweaking.

**Comment by heaths** [comment]
@jsquire I created a "Cognitive - Language" label I forgot to add here a while back at least for .NET and Python repos. Maybe we do want to rename or add a "Question Answering" service label, but it's really a rebranding of QnA Maker - a subset (in terms of SDKs - not REST APIs) of Cognitive Language. What do you, @AlexGhiondea, and @mayurid think?

**Comment by heaths** [comment]
@annatisch note that in .NET we use "Options" instead of "Parameters". In fact, this is in [general guidelines](https://azure.github.io/azure-sdk/general_design.html#general-client-options-param-naming). About the [only thing I see](https://azure.github.io/azure-sdk/python_design.html#python-client-splat-args) close specific to Python doesn't necessary override this guideline, but does recommend a `dict`-like parameter that would serialize like request parameters. IMO, unifying on "options" would be more consistent with other client libraries. Key Vault is the only one I know of that used "Parameters" and it seems archboard opinions have changed since that decision was signed, sealed, and delivered.

/cc @johanste @tg-msft

**Comment by rokulka** [comment]
@heaths , @annatisch  - I'm okay with changing it to KnowledgeBase , as in the docs we refer to it as 'knowledge base' . I can update the Swagger if we decide to go ahead with it.

**Comment by annatisch** [comment]
@heaths - sure, let's go with Options then :)
Are we agreed on the move to KnowledgeBase?

**Comment by heaths** [comment]
Yeah, that sounds good. @rokulka you could either now, or we could wait till we settle a couple of the other discussions about model and method names and do it in one shot. Up to you.
