### ISSUE TITLE
Typo in EventHubsConnectionStringBuilder Sample Code

### ISSUE THREAD

**Issue by openshac** [Azure/azure-sdk-for-net#22533]
There is a typo in the [Sample Code](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.eventhubsconnectionstringbuilder?view=azure-dotnet#examples)

It says:
`var connectionStringBuiler = new EventHubsConnectionStringBuilder(`

Is should be:
`var connectionStringBuilder = new EventHubsConnectionStringBuilder(`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b5a8afbe-024a-eff4-d738-35d3c25f851b
* Version Independent ID: 43ab484f-1dd3-de05-6eb7-a4df54e42f74
* Content: [EventHubsConnectionStringBuilder Class (Microsoft.Azure.EventHubs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.eventhubsconnectionstringbuilder?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.EventHubs/EventHubsConnectionStringBuilder.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.EventHubs/EventHubsConnectionStringBuilder.xml)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.
