### ISSUE TITLE
[BUG] Azure.Messaging.ServiceBus, multiple hosts stopped receiving ONE queue.

### ISSUE THREAD

**Issue by NiklasArbin** [Azure/azure-sdk-for-net#22534]
**Describe the bug**
Azure support #2107050050002321
Queue processing stopped for a single high throughput queue, at the same time across 3 pods on 3 different hosts.

(Our setup creates a new servicebus client per queue, and all other queues had throughput, except the one affected. During this time the queue overflowed since the receivers stopped reading messages from the queue.) IE all other aspects of the client side code and machines were healthy except this. Edge case unaccounted for? 

Our client side code is open source at https://github.com/BookBeat/knightbus/blob/master/knightbus-azureservicebus/src/KnightBus.Azure.ServiceBus/ServiceBusQueueChannelReceiver.cs

**Expected behavior**

Client side SDK should either throw or re-establish processing.

**Actual behavior (include Exception or Stack Trace)**

No exception, no reconnect, the queue overflowed because processing had stopped.

**To Reproduce**

No easy way, current queue was operating around 1.5Million msg/h when processing stopped

**Environment:**
 - Azure.Messaging.ServiceBus Version="7.2.0"
 - dotnet 5, Ubuntu 18, AKS 1.19

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @NiklasArbin,
Did you have SDK logging enabled when this occurred? Was anything being logged by the SDK at this time? 
Is it possible that your app called StopProcessingAsync/CloseAsync at this time for the processor?

**Comment by JoshLove-msft** [comment]
> Queue processing stopped for a single high throughput queue, at the same time across 3 pods on 3 different hosts.

The fact that the issue occurred across hosts makes me wonder if something was temporarily changed in the queue definition (e.g. marking it as Disabled). Were you able to get processing to start again for the queue?

**Comment by NiklasArbin** [comment]
> Hi @NiklasArbin,
> Did you have SDK logging enabled when this occurred? Was anything being logged by the SDK at this time?
> Is it possible that your app called StopProcessingAsync/CloseAsync at this time for the processor?

We have our own logging hooked into ProcessErrorAsync and ProcessMessageAsync, nothing was logged at this time, it just went silent. 
StopProcessingAsync/CloseAsync is connected to the application host shutdown signal, that would have triggered all queue processors to stop and logging the shutdown.

> The fact that the issue occurred across hosts makes me wonder if something was temporarily changed in the queue definition 
> (e.g. marking it as Disabled). Were you able to get processing to start again for the queue?

No changes were made to the queue, we checked the events just to be sure. Also at the time well outside normal business hours.
Once the queue overflowed, our alerting system brought our on-call teams attention, they restarted the pods, and processing resumed. (With lots of expected client side errors of course, since messages was stale, and the system scaled to 9 pods to be able to work through the load)

**Comment by NiklasArbin** [comment]
My best guess is something like:

- Something unexpected happened serverside. This is the only way something can happen across 3 servers, where nothing else was affected, including other queue processing against the same ASB.
- Client SDK code failed to detect and react to that specific serverside event, and continued in a state where it appeared from a code perspective to be processing, but in fact had shut down.

We have been running this code, with minor modifications and SDK updates for over 3 years, and have never seen this before.

**Comment by JoshLove-msft** [comment]
> We have our own logging hooked into ProcessErrorAsync and ProcessMessageAsync, nothing was logged at this time, it just went silent.

It would be great to have the logs that are generated by the library itself, so that we could know what is happening in the processor at this time - see https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging

> Something unexpected happened serverside. This is the only way something can happen across 3 servers, where nothing else was affected, including other queue processing against the same ASB.

I think we may need to get help from the service team to look at the server side logs. Have you filed a support issue?

**Comment by NiklasArbin** [comment]
> I think we may need to get help from the service team to look at the server side logs. Have you filed a support issue?

Azure support #2107050050002321

**Comment by JoshLove-msft** [comment]
> How much logs would this produce in a live environment with 2M Messages/h? I can have a look into it, but then again, I can't reproduce the issue.

There would be a lot of logs with that volume.

> Is there any way to check the status of the connection from the SDK "manually" so that our client code could make a health check to see if there is connectivity periodically.

You could always just peek a single message to attempt to check the connection, but this really shouldn't be necessary. The client library will always try to re-establish a connection/link on the next operation if the connection/link is dropped. If this were to fail, an error should be getting logged.

Even though the issue occurred across 3 separate hosts, were they all using the same network connection? 

The only other idea I had was if there is thread starvation happening in the app that prevents the client from doing anything. Could you provide the ServiceBusProcessorOptions that are being used?

**Comment by aresowj** [comment]
@NiklasArbin hi, would you please provide the value in your production for these settings?

  - PrefetchCount
  - MaxConcurrentCalls 

In the case that client was not able to process fast enough to drain prefetched messages due to some reasons, the client SDK would not prefetch more messages from server side, which leads to the symptom that nothing was received during that time. I checked all metrics and logs on our end, nothing is meaningful to explain this situation. I would say at this point, we have not found any issue on the server side, as all sends are working on this particular queue, while receive did not happen.

**Comment by JoshLove-msft** [comment]
> In the case that client was not able to process fast enough to drain prefetched messages due to some reasons, the client SDK would not prefetch more messages from server side, which leads to the symptom that nothing was received during that time. 

Good point - even if not using prefetch if all of the processing was somehow blocked for a while you would see this behavior. @NiklasArbin - do you have logging for the start and end of your process message handler? If you do, we could rule out this possibility if all starts had a corresponding end log.

**Comment by NiklasArbin** [comment]
> > In the case that client was not able to process fast enough to drain prefetched messages due to some reasons, the client SDK would not prefetch more messages from server side, which leads to the symptom that nothing was received during that time.
> 
> Good point - even if not using prefetch if all of the processing was somehow blocked for a while you would see this behavior. @NiklasArbin - do you have logging for the start and end of your process message handler? If you do, we could rule out this possibility if all starts had a corresponding end log.

HI, sorry for the delay, been away on vacation. We have our apm hooked into message start and end of message processing. This would have triggered an incident if processing times went up. We saw no instances of messages having extreme processing duration. End would have been logged when the cancellation token expired.

**Comment by JoshLove-msft** [comment]
Closing as we haven't been able to repro the issue. We are investigating adding a way to check the connectivity in https://github.com/Azure/azure-sdk-for-net/issues/8561 so you may want to follow that issue @NiklasArbin.

**Comment by JoshLove-msft** [comment]
Looking at this again - @NiklasArbin did you have prefetch enabled when this happened?

**Comment by NiklasArbin** [comment]
> Looking at this again - @NiklasArbin did you have prefetch enabled when this happened?

Yes prefetch is enabled for this processor.

**Comment by JoshLove-msft** [comment]
Do you always settle the message - by either calling complete, abandon, defer, or deadletter? If the message don't always get settled, it's possible this is causing the issue, as we only request new credits when a message is settled when using prefetch.

**Comment by NiklasArbin** [comment]
> Do you always settle the message - by either calling complete, abandon, defer, or deadletter? If the message don't always get settled, it's possible this is causing the issue, as we only request new credits when a message is settled when using prefetch.

We always call complete/abandon or deadletter the message

**Comment by NiklasArbin** [comment]
We've started seeing this again, now on the same high throughput queue, and also a very low throughput queue. 

Since there is no way in the SDK to check the connection status, we've had to code a timer task that checks that at least one message has been processed within X TimeSpan and then close and reconnect if there's been no messages.

One thing that might differ in our code from other frameworks is that we keep a separate connection per queue.

Sems like a 2 part problem:

1. Something happens server side which severs the connection in "some" way
2. The client side SDK does not recognize this happening and just stops

Could you please look into this, having running queues is mission critical to us.

**Comment by JoshLove-msft** [comment]
Hi @NiklasArbin,
Are you able to enable SDK logging? That would be extremely helpful in determining what the client is doing during the periods where this happens?

**Comment by NiklasArbin** [comment]
> Hi @NiklasArbin, Are you able to enable SDK logging? That would be extremely helpful in determining what the client is doing during the periods where this happens?

No sure this is feasible in our production environement with over 40M messages per day.

One thing we do that might make the problem more obvious is that we use a separate TCP connection per queue/topic.
