### ISSUE TITLE
[FEATURE REQ] Add option to disable intermediate Flushes in OpenWrite

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#22572]
Users migrating from V11 notice performance degradation when using OpenWrite API.
The behavior change is that V12 write stream has operational Flush, so if stream is used in a context that frequently flushes that generates more requests to the service.

We should consider adding an option to disable intermittent flush.

Related:
https://github.com/Azure/azure-sdk-for-net/issues/22462
https://github.com/Azure/azure-sdk-for-net/issues/20652

**Comment by amishra-dev** [comment]
This was opened in response to an email. Filing it here for tracking
