### ISSUE TITLE
[BUG] Zero width space use

### ISSUE THREAD

**Issue by shlomiassaf** [Azure/azure-sdk-for-net#22594]
**Describe the bug**
In the source code (entire repo) there is a single location where [Zero-Width-Space](https://en.wikipedia.org/wiki/Zero-width_space) is used.

It's in [EntityNameFormatter.FormatTransferDeadLetterPath](https://github.com/Azure/azure-sdk-for-net/blob/d1243e3b02070bf1ad6e1133e14dce2647a4582a/sdk/servicebus/Azure.Messaging.ServiceBus/src/EntityNameFormatter.cs#L86)

Notice how GitHub is not able to style the code for this function. When highlighting, only the first word (Format) is marked since there is a hidden space there.

![image](https://user-images.githubusercontent.com/5377501/125260560-1e730f80-e309-11eb-92cd-1e9a3c7db5a9.png)

Im on OSX with JetBrain's Rider and it shows an error...

![image](https://user-images.githubusercontent.com/5377501/125260755-52e6cb80-e309-11eb-806e-b58ef426edd1.png)

I assume this is not the case on windows.

Is this intentional?

**Comment by jsquire** [comment]
Hi @shlomiassaf.  Thank you for bringing this to our attention and we regret that you're experiencing difficulties.   This is not intentional; we'll get this fixed up.
