### ISSUE TITLE
Re-enable warnings which are currently disabled in the build

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-net#2259]
Currently there are some warnings disabled in the build (mostly related to `///` comments). #2258 removes some of them, but even after that is merged there will be these remaining: `<NoWarn>1591;1573</NoWarn>`. Note that these warnings are disabled in [this file](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/tools/Library.Settings.targets).

[1591](https://msdn.microsoft.com/en-us/library/zk18c1w9.aspx) is about missing comments
[1573](https://msdn.microsoft.com/en-us/library/01248w2b.aspx) is about missing `<param>` tags in comments.

It seems that AutoRest should generate code which is C# compliant (with no warnings), and that we should have these flags turned on in this repo to ensure that we ship the best possible documentation to our clients.

Cost: 3

**Comment by dsgouda** [comment]
There are certain warnings that come from the generated/customized SDKs. Fixing these now may cause breaking changes to these SDKs, hence skipping them for now.
Focusing on the test projects, most warnings are related to incorrect/inefficient use of the xUnit functionalities. Fixed these warnings [here](https://github.com/Azure/azure-sdk-for-net/pull/4664)
This PR also enables reporting warnings as errors only for the test projects. This will ensure better code quality in our tests.
Some stats:
Total number of warnings for a repo build before PR: 1085
Total number of warnings for a repo build after PR: 328

**Comment by dsgouda** [comment]
Update: I haven't fixed 1591 (comments for public members) for the Test projects. Not sure if we would want to do it for the test projects.
Will talk to @shahabhijeet and make necessary fixes.

**Comment by matthchr** [comment]
Shouldn't we have 1591 enabled on our actual SDKs? (I don't really care about tests, just SDKs).

And if the code-generator isn't generating code with comments, fix the generator so it does?

It seems a pretty reasonable requirement that all public methods have comments in the public SDKs, right?

**Comment by dsgouda** [comment]
Agreed, we should, and we will investigate if there are any other warnings being reported in the generated SDKs which probably need an AutoRest fix. This was an initial effort to reduce number of warnings reported in the build and we will tackle the rest moving forward.

**Comment by Petermarcu** [comment]
@weshaggard @shahabhijeet do you think we will complete this work or should we just close?

**Comment by kurtzeborn** [comment]
As Deepak says above, these warnings are in generated code, so it represents an update to the code generators to address them and re-enable the warnings.

@erich-wang Is this something you guys care about or should we close it.

**Comment by erich-wang** [comment]
@kurtzeborn, if the warnings come from generated code, there's little thing we team could do since current process need service team to generate code. Please feel free to reopen the issue.
