### ISSUE TITLE
[BUG] UnscheduledInvocationReason: IsPastDue and process does not restart

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-sdk-for-net#22590]
TargetFramework : net5.0
AzureFunctions Version : v3
Function App platform: Linux
Consumption plan
Microsoft.Azure.Functions.Worker.Extensions.Timer : 4.1.0
VS 2019

Hi 
I have a timer trigger function which is scheduled to run once every 10 minutes, and according to the recommendations, the useMonitor property is set to "true".

"bindings": [{
		"schedule": "0 */10 * * * *",
		"useMonitor": true
		"runOnStartup": false,
		"name": "TimerInfo",
		"type": "timerTrigger"
	}]

I have the following error every time the function is triggered (I can reproduce the problem locally also)

[2021-07-10T15:05:17.825Z] Trigger Details: UnscheduledInvocationReason: IsPastDue, OriginalSchedule: 2021-07-10T11:50:00.0000000-03:00
[2021-07-10T15:06:16.410Z] Starting worker process failed
[2021-07-10T15:06:16.413Z] The operation has timed out.
[2021-07-10T15:06:16.452Z] Failed to start a new language worker for runtime: dotnet-isolated.
[2021-07-10T15:06:16.455Z] System.Private.CoreLib: The operation has timed out.

If I set useMonitor = false, then IsPastDue is false, but the ScheduleStatus of my timer is null so I get null reference exception.

I think that this problem is mostly happening on linux platform.

I think that the expected behavior is that the function should run (having useMonitor TRUE ), and in case there is a "past due" it should retry without the worker process to fail.

Besides, I don't know why ScheduleStatus is null when useMonitor = false.

Thank you very much
Sabrina.

**Comment by jsquire** [comment]
Issue moved to [Azure/azure-functions-dotnet-worker #534](https://github.com/Azure/azure-functions-dotnet-worker/issues/534) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jsquire** [comment]
This package is maintained in the [Azure/azure-functions-dotnet-worker](https://github.com/Azure/azure-functions-dotnet-worker/issues) repository;  I've transferred this over as [#534](https://github.com/Azure/azure-functions-dotnet-worker/issues/534).
