### ISSUE TITLE
Make condition failures from BlobBaseClient.DownloadContentAsync detectable

### ISSUE THREAD

**Issue by idg10** [Azure/azure-sdk-for-net#22598]
If you call `DownloadContentAsync` on `BlobBaseClient` passing in `condition` with `IfNoneMatch` set to an ETag, then in cases where the ETag passed in matches the blob that is already present, the underlying Blob Storage REST API returns a 304 Not Modified to indicate that no body is being returned because the entity in storage still matches the ETag supplied.

Unfortunately, `DownloadContentAsync` does not make it possible to detect when this occurs. The problem arises here, inside `DownloadContentInternal`:

https://github.com/Azure/azure-sdk-for-net/blob/33213307d4b6bdf39f8f82c5e9860b8018ee24bb/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L1569-L1576

After `DownloadStreamingInternal` returns, the `response` variable here correctly reports that the Storage API has returned a 304. However, the code does not check for this, and immediately tries to evaluate `response.Value`. That doesn't work because the type of `response` here is `NoBodyResponse<BlobDownloadStreamingResult>`, which has a `Value` property that is hard-coded to throw an exception:

https://github.com/Azure/azure-sdk-for-net/blob/33213307d4b6bdf39f8f82c5e9860b8018ee24bb/sdk/core/Azure.Core/src/Shared/NoBodyResponseOfT.cs#L19-L25

Unhelpfully, the exception type it throws is the private `NoBodyResponse<T>.ResponseBodyNotFoundException` class, which derives directly from `Exception`.

Although that exception does embed the HTTP status code, there's no reliable way for code using this library to extract that, because the property is defined by a private class.

The effect of this is to make it more or less pointless passing in conditions to `DownloadContentAsync` because it is not possible to distinguish between failures caused by the condition not being met, and failures of any other kind.

Better options would include:
 * make `Response<BlobDownloadResult>` return instead of throwing an exception in these cases, because `Response<T>` can describe this outcome perfectly well
 * throw an exception that tells you something about the failure e.g. a `RequestFailedException`

The first would be preferable if we were starting from a clean sheet because the case "The thing I have cached matches the entity in blob storage" is very much not an exceptional case. However, this would be a breaking change, meaning the second is arguably better at this point, even though it's a suboptimal design. (Client code cannot currently distinguish between failure modes because the exception type is opaque, but it is nonetheless possible that there's code out there depending on getting an exception when conditions are not met.)

Another possibility would be an overload enabling you to specify that in cases where you get a non-2xx status code, you just want the `Response<T>` to tell you what happened, instead of throwing.

**Comment by amnguye** [comment]
@kasobol-msft

**Comment by NtgTNabet** [comment]
Same issue with BlobDownloadStreamingAsync. 
Any news on when this will get release. Current state make use of cache control quite useless.

**Comment by amnguye** [comment]
This should be in our 12.10.0-beta.10 release. Please upgrade accordingly.

Closing this issue as this issue should have been resolved due to the PR merged.
