### ISSUE TITLE
[FEATURE REQ] Allow an option for BlockBlobClient.UploadAsync to only use PUT Blob

### ISSUE THREAD

**Issue by yufeih** [Azure/azure-sdk-for-net#22593]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**

Today `BlockBlobClient` chooses to call `PUT Blob` or `PUT Block` internally. While these strategies both upload the content, the first API has an auto-generated server side MD5 content hash, which is useful in many scenarios. The second API doesn't.

While input stream length can be adjusted with `InitialTransferSize`, it is not obvious that a non-seekable stream would also cause chunked upload. We are dealing with a lot of streams with a known length but un-seekable (like an HTTP request stream), it is not optimal to convert these streams to a seekable stream just to bypass chunked transfer behavior.

Force `UploadAsync` to use `PUT Blob` is a simple way to enforce MD5 hash for all blobs, Consider add an option to disable chunked upload.

https://github.com/Azure/azure-sdk-for-net/issues/17676#issuecomment-749777800

**Comment by amnguye** [comment]
You should be able to get Upload to to a Put Blob instead of a Put Block / Put Block List by altering the `InitialTransferSize` to be larger than the size given. That way it will be done in a one shot upload. As a mitigation.

@seanmcc-msft @kasobol-msft What do you think about making it more obvious on how to force upload to do a single Put Blob, instead of telling people to alter the InitialTransferSize.

**Comment by seanmcc-msft** [comment]
Note that `Put Blob` has a size limit of 4000MiB - https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#remarks

**Comment by yufeih** [comment]
@amnguye @seanmcc-msft 

Simply altering `InitialTransferSize` may not work for all cases. The [`GetLengthOrDefault`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Common/src/Shared/PartitionedUploader.cs#L462) method requires the source stream to be seekable. Some streams aren't seekable but have length information, like an HTTP request stream where we can get  the length from `Content-Length` header but the stream itself if not seekable. Today we are using a relaying memory stream just to workaround that method.

**Comment by amnguye** [comment]
Adding in this feature request would have the limitation of a 4000MB upload, because the `Put Blob` REST call has a 4000MB size. (There's nothing the SDK can change about this limitation).

So I don't see how adding this feature request would resolve your scenario.

**Comment by kasobol-msft** [comment]
@amnguye I think there should be an API on `Specialized.BlockBlobClient` that just maps directly to put blob (like [here](https://github.com/Azure/azure-sdk-for-java/blob/af17a1edd24e440b8ea83535a5ebcd3acce9f9b8/sdk/storage/azure-storage-blob/src/main/java/com/azure/storage/blob/specialized/BlockBlobAsyncClient.java#L287-L323)).
