### ISSUE TITLE
[Query] CloudBlockBlob.OpenWriteAsync and number of blocks connection. [Azure Storage]

### ISSUE THREAD

**Issue by MohitNagpaldce** [Azure/azure-sdk-for-net#22591]
[Query] CloudBlockBlob.OpenWriteAsync and number of blocks 
How number of blocks in blob are connected to OpenWriteAsync. if stream opened by 
Stream stream  = CloudBlockBlob.OpenWriteAsync ;
treamWriteSizeInBytes = 4 MB 
stream.Write() // 4 MB data
stream.Write() // 4 MB data
stream.Flush() // will this create 2 blocks in block blob or How it is connected.

Hitting 50000 block limit error on using stream.Write()  based writing to cloudbloclBlob

**Comment by amnguye** [comment]
Hi, this looks like you're using the deprecated library. Please upgrade to our current version which is v12+

All issues regarding the deprecated library can be found and placed here.
https://github.com/Azure/azure-storage-net/issues

Also if you have any further issues after upgrading please clarify the question you have or the problems you are having. Thanks. I recommend following the form given when first making the issue.

**Comment by MohitNagpaldce** [comment]
Using Microsoft.Azure.Storage.Blob, Version=11.2.3.0 and doing below steps : 
CloudBlockBlob cloudBlob = new CloudBlockBlob(new Uri(FullPath));
cloudBlob.StreamWriteSizeInBytes = blockSize // 4 MB
var blobStream = cloudBlob.OpenWriteAsync(null, BlobOptions); 

now on writing blobStream it will take block size = blockSize  or it wont take blockSize. Writes to blobStream can be any length
i.e. 

blobStream.Write() 1 MB data
blobStream.Write() 2 MB data
blobStream.Write() 1 MB data
blobStream.Write() 1 MB data
blobStream.Write() 1 MB data
blobStream.Write() 1 MB data

block size is 4 MB and total written is 7 MB , will this create 2 blocks on block blob ? if not then how to make sure it creates 2 blocks on blockblob. for above write pattern.

**Comment by amnguye** [comment]
Sorry to repeat myself.

Please upgrade to our current version which is v12+. You are using a deprecated library ( Version=11.2.3).

All issues regarding the deprecated library can be found and placed here.
https://github.com/Azure/azure-storage-net/issues

Also can you be more clear on what the question is when you make the issue on the other repo. I don't know what problem you're hitting with OpenWrite. Are you seeing two block on the block blob? or are you not? (Confusion can be easily solved if you followed the initial form given in the github issue when you initially made it).

**Comment by MohitNagpaldce** [comment]
Thanks for update. Sorry for confusion. with library  11.2.3.0 i am seeing more than 2 blocks are getting created. This issue will go away by moving to v12+ ?

**Comment by amnguye** [comment]
We do not see this issue in v12.

If you would like assistance with v11 please follow the statement in my previous replies.

**Comment by MohitNagpaldce** [comment]
v12 is for .netstandard 2.0. Is there anything simialr for .netframework 4.5

**Comment by amnguye** [comment]
Unfortunately not. I would not recommend .net framework 4.5 either as support ended in 2016
https://docs.microsoft.com/en-us/lifecycle/faq/dotnet-framework#what-is-the-microsoft-lifecycle-policy-for-the--net-framework-

**Comment by MohitNagpaldce** [comment]
v12 will work with .net 4.6.1 ?

**Comment by MohitNagpaldce** [comment]
Moving to blob12 dll and doing like this : 
BlobStreamOptions =
            new BlockBlobOpenWriteOptions()
            {
                BufferSize = 8 * 1024 * 1024,
            };

blobStream = cloudBlobClient.OpenWrite(true, BlobStreamOptions);

blobStream.Write() 1 MB data
blobStream.Write() 2 MB data
blobStream.Write() 1 MB data
blobStream.Write() 1 MB data
blobStream.Write() 1 MB data
blobStream.Write() 1 MB data

this will make each block to size of 8 MB ? Please confirm this part. Thanks for help.

**Comment by amnguye** [comment]
Yes v12 works with .NET 4.6.1

and as stated before
> We do not see this issue in v12.
I will make each buffer size / block size 8MB if you set `BlockBlobOpenWriteOptions.BufferSize` to 8MB.
