### ISSUE TITLE
[BUG] Error on Application Startup using KeyVault 4.2.0 

### ISSUE THREAD

**Issue by XpandIT-RFID** [Azure/azure-sdk-for-net#22607]
I am getting this error on my app:
![image](https://user-images.githubusercontent.com/83280308/125369145-9e35c400-e373-11eb-8009-2b24bfcd85b4.png)

This is my code:
![image](https://user-images.githubusercontent.com/83280308/125369168-ac83e000-e373-11eb-8093-cf7509c364d0.png)
![image](https://user-images.githubusercontent.com/83280308/125369177-b0affd80-e373-11eb-9471-42dc0846a1c7.png)
![image](https://user-images.githubusercontent.com/83280308/125369230-c7565480-e373-11eb-9718-8425d2ac9bbd.png)

Can someone help me with this? 
I can give more info on the comments.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
//cc: @pakrym.    I'm not sure if the ASP.NET Extension is potentially a cause;  would you mind also taking a look?

**Comment by heaths** [comment]
What does this return?

![image](https://user-images.githubusercontent.com/1532486/125534783-4abbeaaa-3d60-4115-8cbb-46c37274452a.png)

Note that the URL has to be an absolute URL including host, such as "https://myvault.vault.azure.net".
