### ISSUE TITLE
Release pipelines should validate that a released package does not depend on unpublished packages

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#22604]
If a package takes a project reference on Azure.Core and is released after Core ships, it can result in a package dependency reference in the nuget package artifact produced that refers to the unpublished version of Azure.Core.

Example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=994998&view=results

**Comment by jsquire** [comment]
//cc: @AlexGhiondea

**Comment by pallavit** [comment]
I believe this issue is already fixed in the release pipelines as we now check all dependencies are already released before the final release step.

/cc: @hallipr , @benbp , @weshaggard to confirm.
