### ISSUE TITLE
[BUG] Document Translation SDK: Cannot specify source language AND a glossary

### ISSUE THREAD

**Issue by chriswendt1** [Azure/azure-sdk-for-net#22609]
**Describe the bug**
Document Translation: Cannot specify source language AND a glossary.
There are two Constructors for DocumentTranslationInput.
One does not allow to specify a glossary, the other one does not allow to specify a source language. In practice we need to specify both.

This is a problem with the SDK only. The REST API does allow to specify both. 

**Expected behavior**
In this constructor
DocumentTranslationInput(TranslationSource, IEnumerable<TranslationTarget>)
the glossary is {get} only. It should be settable.

**Actual behavior (include Exception or Stack Trace)**
No way to specify a glossary and a source language. 

**To Reproduce**
Try to specify a glossary and a source language. Intended UI is:
![image](https://user-images.githubusercontent.com/11096941/125374448-e33e0400-e33b-11eb-9cf8-2dadf2505ffd.png)

**Environment:**
 - Name and version of the Library package used: Azure.AI.Translation.Document (1.0.0-beta.3)
 - Hosting platform or OS and .NET runtime version: .Net 5 on Windows
 - IDE and version : Visual Studio 16.10.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Hey @chriswendt1 thank you for asking this question. 

You are right that the way to go is by using the `DocumentTranslationInput(TranslationSource, IEnumerable)` constructor and setting the `Glossaries` per `target`. 
Our input collections are not settable but you can add items to it. See more information here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-collection-read-only-property-initialization

Following your intended UI as example, here is how it could look like:

```
var source = new TranslationSource(sourceSasUri)
{
    LanguageCode = "af"
};

var glossary = new TranslationGlossary(glossarySasUri, glossaryFormat);

var target = new TranslationTarget(targetSasUri, "nl")
{
    Glossaries = { glossary }
};

var input = new List<DocumentTranslationInput>()
{
    new DocumentTranslationInput(source, new List<TranslationTarget>() { target } )
};

DocumentTranslationOperation operation = await client.StartTranslationAsync(inputs);
```

Let me know if this helps

**Comment by chriswendt1** [comment]
Thank you so much, Mariana, for the pointer to the collection initialization for read-only properties.
Since user may want to add multiple glossary files, I am using

            TranslationTarget translationTarget = new(sasUriTarget, tolanguage);
            if (glossary.Glossaries is not null)
            {
                foreach (var glos in glossary.Glossaries) translationTarget.Glossaries.Add(glos.Value);
            }

And it works well. 
FYI the app is here: https://github.com/microsofttranslator/documenttranslation.

**Comment by maririos** [comment]
>FYI the app is here: https://github.com/microsofttranslator/documenttranslation.

This is so cool!!! Let me know if you have more questions or suggestion on how we can improve the SDK :)
