### ISSUE TITLE
Move data plane libraries out of ResourceManagement folder

### ISSUE THREAD

**Issue by kirthik** [Azure/azure-sdk-for-net#2262]
We want to move to a structure that has management plane libraries under `ResourceManagement` folder. Data plane libraries will exist at the same level as `ResourceManagement` folder. The following should be moved out 
- DataLake.Store
- DataLake.StoreUploader
- Graph.RBAC

**Comment by markcowl** [comment]
@twitchax Please decide how we should do this

**Comment by adrianhall** [comment]
Is this still an issue?
