### ISSUE TITLE
[QUERY] Service Bus - OperationCanceledException on RenewLock

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-sdk-for-net#22635]
**Query/Question**
Sometimes I got "The operation was canceled." in my SubscriptionClient with SessionHandler.
I could not find any reasons for that. Could you please describe the case?

Please let me know if I need provide more info

> Microsoft.Azure.ServiceBus.ServiceBusException:
>    at Microsoft.Azure.ServiceBus.MessageSession+<OnRenewSessionLockAsync>d__14.MoveNext (Microsoft.Azure.ServiceBus, Version=5.1.2.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Azure.ServiceBus.MessageSession+<OnRenewSessionLockInstrumentedAsync>d__18.MoveNext (Microsoft.Azure.ServiceBus, Version=5.1.2.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Azure.ServiceBus.SessionReceivePump+<RenewSessionLockTaskAsync>d__24.MoveNext (Microsoft.Azure.ServiceBus, Version=5.1.2.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c)
> Inner exception System.OperationCanceledException handled at Microsoft.Azure.ServiceBus.MessageSession+<OnRenewSessionLockAsync>d__14.MoveNext:
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Azure.Amqp.AsyncResult.End (Microsoft.Azure.Amqp, Version=2.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver+<>c__DisplayClass86_0.<ExecuteRequestResponseAsync>b__1 (Microsoft.Azure.ServiceBus, Version=5.1.2.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver+<ExecuteRequestResponseAsync>d__86.MoveNext (Microsoft.Azure.ServiceBus, Version=5.1.2.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c)
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
>    at Microsoft.Azure.ServiceBus.MessageSession+<OnRenewSessionLockAsync>d__14.MoveNext (Microsoft.Azure.ServiceBus, Version=5.1.2.0, Culture=neutral, PublicKeyToken=7e34167dcc6d6d8c)
> 

There is similar issue with [MessagePumpTaskAsync](https://github.com/Azure/azure-sdk-for-net/issues/6410). It was fixed by ignoring the OperationCanceledException. Can I also ignore such exceptions or is it critical for RenewLock?

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ServiceBus 5.1.3
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):  5.0.203 Windows 
 - IDE and version : Visual Studio 16.9.6

**Comment by jsquire** [comment]
//cc: @shankarsama

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by Marusyk** [comment]
Hi @shankarsama could you please help?

**Comment by Marusyk** [comment]
Hi @shankarsama could you please help?

**Comment by Marusyk** [comment]
Can anyone answer me? Please

**Comment by jsquire** [comment]
Hi @Marusyk.   Yes;  @shankarsama's team owns the Service Bus service and the generation of the SDK that you're asking about.    Looping in a few of the other team members in case they're available to assist.

//cc: @DorothySun216, @bainian12345,  @vinaysurya, @yvgopal

**Comment by ramya-rao-a** [comment]
@Marusyk Apologies for the delay here. 

Please note that the Microsoft.Azure.ServiceBus package is now deprecated. A newer package Azure.Messaging.ServiceBus is available as of November 2020. While the older package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the [getting started guide](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dotnet-get-started-with-queues) and  [migration guide](https://aka.ms/azsdk/net/migrate/sb) for more details.

If you still have issues using the older Microsoft.Azure.ServiceBus package, please use your [Azure support plan](https://azure.microsoft.com/support/options/) to open an [Azure support ticket](https://azure.microsoft.com/support/create-ticket/).

**Comment by Marusyk** [comment]
Thanks @ramya-rao-a very useful and in time :(
