### ISSUE TITLE
KeyVaultClient.GetSecretsAsync: maxresults upper limit isn't specified in docs

### ISSUE THREAD

**Issue by TechniMan** [Azure/azure-sdk-for-net#22641]
We were using `GetSecretsAsync` and recently needed to expand it to more than the default 25 results. However, when we made this change we got an exception message as follows:
```
Unhandled exception. Microsoft.Rest.ValidationException: 'maxresults' exceeds maximum value of '25'.
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
```
It appears that there is a maximum allowable value of `maxresults` of `25`, which the docs do not specify. We are changing our approach to use `GetSecretsNextAsync`, which could be a Remark perhaps in the page for `GetSecretsAsync/GetSecretsWithHttpMessagesAsync` if greater than 25 results are required.

I am assuming because of the exception message that it is intended for there to be a maximum of 25 results per call. So this issue is for the docs to be amended to be up-front about that limitation and explain the ideal work-around. My only worry is that this code worked locally, and not when deployed to run in Azure (in a test environment, thankfully), so we're unsure where this discrepancy could have arisen from. If the issue is actually with our code and this `maxresults` limit isn't a fact, please let me know. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6ddf60c-8c02-4b23-225f-2e8d676041e3
* Version Independent ID: cf2dabbd-c1e6-402e-1a92-ad5f6a6c7774
* Content: [KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient, String, Nullable&lt;Int32&gt;, CancellationToken) Method (Microsoft.Azure.KeyVault) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.keyvaultclientextensions.getsecretsasync?view=azure-dotnet-legacy#Microsoft_Azure_KeyVault_KeyVaultClientExtensions_GetSecretsAsync_Microsoft_Azure_KeyVault_IKeyVaultClient_System_String_System_Nullable_System_Int32__System_Threading_CancellationToken_)
* Content Source: [xml/Microsoft.Azure.KeyVault/KeyVaultClientExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.KeyVault/KeyVaultClientExtensions.xml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
//cc: @shaabs, since this is referencing the legacy version of the KeyVault library.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by heaths** [comment]
The REST API documents this here: https://docs.microsoft.com/en-us/rest/api/keyvault/get-secrets/get-secrets#uri-parameters

In general, we do not tightly couple limitations in the SDK because the service behavior may change.

That said, please note that Microsoft.Azure.KeyVault is deprecated and we recommend people use Azure.Security.KeyVault.Secrets instead for secrets. That also enables both synchronous and asynchronous paging like so: 

```csharp
foreach (var response in client.GetPropertiesOfSecrets())
{
}

await foreach (var response in client.GetPropertiesOfSecretsAsync())
{
}
```

See [our sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/samples/Sample3_GetSecrets.md#listing-secrets) for more details.
