### ISSUE TITLE
MetricsInMemoryTests Not Finished / Not Working

### ISSUE THREAD

**Issue by solvingj** [Azure/azure-sdk-for-net#2265]
In trying to debug another issue, I found that the tests for Insights were apparently set to Ignore 455 days ago by yugangw-msft and nobody followed back up on it.  I recommend someone please take a look at these tests and get them working. 

Reference: 

```
public class MetricsInMemoryTests : TestBase

        [Fact(Skip="TODO: invetigate with Inights team when owner is back to office")]
        public void GetMetricDefinitionsTest()

```

If anyone can speak to the situation below, it would be helpful.  The actual problem class I need to debug the tests for is as follows: 

https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Insights/Insights/OnetimeGenerated/Insights/MetricOperations.cs

Line 113 of method "GetMetricsInternalAsync" indicates that one can obtain the metric values by using the /metrics path suffix.  

> /subscriptions/subscriptionId/resourceGroups/resourceGroupName/providers/Microsoft.Compute/virtualMachines/ServerName/metrics",

However, when hitting this path via REST (outside the .NET library), I receive: 

> "400 Bad Request"
> {"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'northeurope' and API version '2014-04-01' for type 'virtualMachines'. The supported api-versions are '2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-04-30-preview'. The supported locations are 'eastus, eastus2, westus, centralus, northcentralus, southcentralus, northeurope, westeurope, eastasia, southeastasia, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, southindia, centralindia, westindia, canadacentral, canadaeast, westus2, westcentralus'."}}

Meanwhile, /metricDefinitions works as expected via REST: 

> /subscriptions/subscriptionId/resourceGroups/resourceGroupName/providers/Microsoft.Compute/virtualMachines/ServerName/metricdefinitions",

That path is referenced by this class:
https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Insights/Insights/OnetimeGenerated/Insights/MetricDefinitionOperations.cs

Finally, I was told by someone that the path probably just doesn't work for virtual machines, however I cannot believe this because the powershell cmdlet Get-AzureRMMetric is able to pull metrics from the VM, and when I looked in the source code I found it simply leverages the .NET SDK. 

https://blogs.msdn.microsoft.com/cloud_solution_architect/2016/02/26/retrieving-resource-metrics-and-creating-alert-rules-via-azure-powershell/

It also pulls them so quickly, I don't believe it's doing an Azure Storage (table) query which is extremely slow.  Also, I couldn't find any reference in the source code to Azure Storage tables. 

The priority is fixing the test cases, but any insight as to how I can achieve the same output as the powershell above via REST would be helpful.

**Comment by markcowl** [comment]
@asheniam Can you take  a look?

**Comment by solvingJ** [comment]
Bump?

**Comment by adrianhall** [comment]
Checking in to older bugs.  Is this still an issue?
