### ISSUE TITLE
DeserializeAdalV3(byte[]) needs exceptions listed

### ISSUE THREAD

**Issue by JesseMcClusky** [Azure/azure-sdk-for-net#22655]
DeserializeAdalV3's page doesn't list the exceptions it can throw.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65c9b325-ecc6-e1aa-bbcd-0d26c5042907
* Version Independent ID: e97ca8d8-1d2f-79e3-51f9-20280307fa7e
* Content: [TokenCache.DeserializeAdalV3(Byte\[\]) Method (Microsoft.IdentityModel.Clients.ActiveDirectory) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.clients.activedirectory.tokencache.deserializeadalv3?view=azure-dotnet#Microsoft_IdentityModel_Clients_ActiveDirectory_TokenCache_DeserializeAdalV3_System_Byte___)
* Content Source: [xml/Microsoft.IdentityModel.Clients.ActiveDirectory/TokenCache.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Clients.ActiveDirectory/TokenCache.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @JesseMcClusky.  Thank you for your feedback.   I'm transferring this to the [repository](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet) where the `Microsoft.IdentityModel.Clients.ActiveDirectory` package is maintained as issue [#1728](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/1728).
