### ISSUE TITLE
[QUERY] What is the actual type of Azure.Storage.Queues.Models.QueueMessage.MessageId?

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-sdk-for-net#22673]
**Query/Question**
[According to MSDN](https://docs.microsoft.com/dotnet/api/azure.storage.queues.models.queuemessage.messageid?view=azure-dotnet), the type of `QueueMessage.MessageId` is `string`. However in our testing, we have seen that it is actually always a `Guid` that's been `ToString()`'ed.

Other MSDN docs, e.g. [this one](https://docs.microsoft.com/en-us/python/api/azure-storage-queue/azure.storage.queue.models.queuemessage?view=azure-python-previous), explicitly state that this value is a GUID even though typed as a `string`. (I'm aware that linked doc is referring to a very old version, I'm just giving an example of a mismatch).

**Can I rely on this value always being a GUID in actuality**? The reason I ask is that I have a requirement to serialize specific queue messages into a SQL database (please don't ask why), and obviously if the `MessageId` is actually a GUID I can just use it directly as the primary key on the table to look up a particular message. Conversely, if it's actually a string, I need a standard integer PK with a separate indexed `nvarchar(max)` column holding the `MessageId`.

Finally, if `MessageId` **is** a GUID, why is it still typed as `string` in the SDK POCOs? Simply for backwards-compatibility reasons?

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Queues 12.6.1.0

**Comment by kasobol-msft** [comment]
@IanKemp [The REST API doc](https://docs.microsoft.com/en-us/rest/api/storageservices/get-messages#response-body) states that message id is a GUID. Same doc states that message id is opaque to the client, i.e. client should not attempt to interpret that value, hence `string` in SDK models (which also means less parsing/serializing).
