### ISSUE TITLE
Make GetParentBlobContainerClient and GetParentBlobServiceClient mockable

### ISSUE THREAD

**Issue by shrallap** [Azure/azure-sdk-for-net#22679]
For our testing we are trying to mock BlobClient and ContainerClient. But looks like the extension methods are not mockable.

var mockBlobClient = new Mock<BlobClient>();
            var mockParentBlobClient = new Mock<BlobContainerClient>();
            var mockBlobServiceClient = new Mock<BlobServiceClient>();
            mockBlobClient.Protected().Setup<BlobContainerClient>("GetParentBlobContainerClient").Returns(mockParentBlobClient.Object);
            mockParentBlobClient.Protected().Setup<BlobServiceClient>("GetParentBlobServiceClient").Returns(mockBlobServiceClient.Object);

**Comment by kasobol-msft** [comment]
See https://github.com/Azure/azure-sdk-for-net/blob/526cd0f61e8cc9d285767a88138c7cd53800c4ee/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L3372-L3386

**Comment by shrallap** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/526cd0f61e8cc9d285767a88138c7cd53800c4ee/sdk/storage/Azure.Storage.Blobs/tests/BlobBaseClientTests.cs#L7782-L7794
