### ISSUE TITLE
[QUERY] Release Microsoft.Azure.Management.Automation NuGet with clean version

### ISSUE THREAD

**Issue by BastienPerdriau** [Azure/azure-sdk-for-net#22676]
**Query/Question**
Hello,

I started to use Microsoft.Azure.Management.Automation nuget package but it seems I have a bug with 2.0.7 version but not with 3.8.3-preview version, and would prefer to use a more recent version (2.0.7 is from 2018).
However, use a preview version is not ideal with our versioning management.

Is it planned to release proper version, since this package is not updated frequently ?

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.Automation 2.0.7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allenjzhang** [comment]
Hi, @BastienPerdriau, thank you for your question. I have marked with the correct label to route to the service team. I did check the [AzSDK.RP.props](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/automation/Microsoft.Azure.Management.Automation/AzSdk.RP.props) file and it looks like containing newer preview version of RestAPI, which may be the reason service team kept the preview name on the nugget package. I would say that if the API version you are using is NOT preview, you could use the package just fine functionally. But I agree having a stable version is essential for particularly enterprise customers. The .NET SDK release is owned by service team which I will leave them to answer and provide any updates/remedies. Thanks.  cc @zjalexander

**Comment by BastienPerdriau** [comment]
/unresolve

Sorry, I wasn't available until today.
As far as I can see, the latest version of the nuget is still 3.8.3-preview.

From the initial trouble, I managed to use the 2.0.7 version, using the older documentation of the related API version but it wasn't easy, and I still prefer use a more recent version of SDK and API if possible.

@ArthurMa1978 As you stated the this issue was adressed, have you any update ?

**Comment by SaurabhSharma-MSFT** [comment]
@ArthurMa1978 Can you please look into this.

**Comment by BastienPerdriau** [comment]
I close this issue as it seems that the package [Azure.ResourceManager.Automation](https://www.nuget.org/packages/Azure.ResourceManager.Automation) will be the next iteration for Automation resource management SDK.

Hopefully it will be released as 1.0.0 asap, alongside every other SDK which are released these past few weeks/months.
