### ISSUE TITLE
https://aka.ms/ms-identity-web/daemon-ACL link is broken

### ISSUE THREAD

**Issue by jlautman** [Azure/azure-sdk-for-net#22684]
https://aka.ms/ms-identity-web/daemon-ACL Redirects to https://www.bing.com/?ref=aka&shorturl=ms-identity-web/daemon-ACL, which is a broken link. Please update.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d02c1e9f-dbee-afae-b6a1-c822889bb2d8
* Version Independent ID: c8fe7023-c6ab-8b43-aaaa-452361a87ca7
* Content: [MicrosoftIdentityOptions Class (Microsoft.Identity.Web) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.microsoftidentityoptions?view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Identity.Web/MicrosoftIdentityOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Web/MicrosoftIdentityOptions.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the [repsitory](https://github.com/AzureAD/microsoft-identity-web) where the `Microsoft.Identity.Web` package is maintained as [#1322](https://github.com/AzureAD/microsoft-identity-web/issues/1322).
