### ISSUE TITLE
Request to change wordings in the Remarks section.

### ISSUE THREAD

**Issue by ChaitanyaNaykodi-MSFT** [Azure/azure-sdk-for-net#22696]
In the Remarks section of `CreateTimer<T>(DateTime, T, CancellationToken)` the current wording says.

`All durable timers created using this method must either expire or be cancelled using the cancelToken before the orchestrator function completes. Otherwise the underlying framework will keep the instance alive until the timer expires`

Suggested change.

`All durable timers created using this method must either expire or be cancelled using the cancelToken before an orchestration instance can transition to the "Completed" state. Otherwise the underlying framework will keep the instance in the "Running" state even after the orchestrator function has completed`

Please refer to this issue (https://github.com/MicrosoftDocs/azure-docs/issues/78334#issuecomment-881591472) for additional details.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8baac8e-b591-9ce4-5afd-9ce3e3f17966
* Version Independent ID: e86f7868-fc74-28d9-28da-6d8b7e24337d
* Content: [IDurableOrchestrationContext.CreateTimer Method (Microsoft.Azure.WebJobs.Extensions.DurableTask) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.extensions.durabletask.idurableorchestrationcontext.createtimer?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.WebJobs.Extensions.DurableTask/IDurableOrchestrationContext.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.WebJobs.Extensions.DurableTask/IDurableOrchestrationContext.xml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Issue moved to [Azure/azure-functions-durable-extension #1893](https://github.com/Azure/azure-functions-durable-extension/issues/1893) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jsquire** [comment]
This issue has been transferred to the [repository](https://github.com/Azure/azure-functions-durable-extension) where the `Microsoft.Azure.WebJobs.Extensions.DurableTask` package is maintained as [#1893](https://github.com/Azure/azure-functions-durable-extension/issues/1893).
