### ISSUE TITLE
[BUG] - When not providing an apiVersion, Fluent ResourceManager will resolve non-existing version 

### ISSUE THREAD

**Issue by stowen-msft** [Azure/azure-sdk-for-net#22698]
**Describe the bug**
Hi,

 We use the ResourceManagerClient's `GenericResources.GetByIdAsync()` method to retrieve information from ARM relating to Azure Automation accounts. In our normal usage, we provide only the `ResourceID` of the resource we're querying, and do not provide an apiVersion, as that is an optional parameter.

This has worked for the last year, but in the last few days, we have observed `No registered Resource Provider exists for version and location....`

##  Example Request:

```csharp
var thisResource = await resourceManagerAuthenticationClient.GenericResources.GetByIdAsync(resourceId);
```

**Expected behavior**
Code should return the expected Azure Automation account, which is known to exist.  Code should NOT REQUIRE an APIVersion be provided.

**Actual behavior (include Exception or Stack Trace)**

## Response

> No registered resource provider found for location 'centralus' and API version '2021-06-22' for type 'automationAccounts'. The supported api-versions are '2015-01-01-preview, 2015-10-31, 2017-05-15-preview, 2018-01-15, 2018-06-30, 2019-06-01, 2020-01-13-preview, 2021-04-01, 2021-06-22'. The supported locations are 'japaneast, eastus2, westeurope, southafricanorth, ukwest, switzerlandnorth, brazilsoutheast, norwayeast, germanywestcentral, uaenorth, switzerlandwest, japanwest, uaecentral, australiacentral2, southindia, francesouth, norwaywest, westus3, swedencentral, koreasouth, southeastasia, southcentralus, northcentralus, eastasia, centralus, westus, australiacentral, australiaeast, koreacentral, eastus, westus2, brazilsouth, uksouth, westcentralus, northeurope, canadacentral, australiasoutheast, centralindia, francecentral'.

### This error goes away when we provide an API Version, such as `2021-04-01`

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.  Create an Azure Resource Manager client like so:
```csharp
                var credentials = this.GetAzureCredentials(token);
                var subscriptionId = parseResource.SubscriptionId;
                var resourceManagerAuthenticationClient = ResourceManager.Configure().Authenticate(credentials).WithSubscription(subscriptionId);
```
2. Look for an Azure Automation account in any region, like `centralUs` 
```csharp
  var resource = await resourceManagerAuthenticationClient.GenericResources.GetByIdAsync(resourceId);
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 -  Microsoft.Azure.Management.ResourceManager.Fluent
1.33.0
 - Hosting platform or OS and .NET runtime version
 - Azure AppService
 - IDE and version : [e.g. Visual Studio 16.3]
 - Visual Studio 2019 or 2022 or Prod

Should the SDK attempt to use the newest apiVersion when a user does not provide one?  If an apiVersion isn't available in all regions, a similar error could likely be encountered.  What if it tried the second most recent apiVersion?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
HI @weidongxu-microsoft could you help on this Fluent issue? thanks

**Comment by weidongxu-microsoft** [comment]
@stowen-msft

The suggestion is to provide an `api-version` for consistency. In very rare case (as in your case), service might register an api-version that they have yet to onboard (or onboard to all regions). This could cause unexpected result.

**Comment by weidongxu-microsoft** [comment]
To automation service. From the message `2021-06-22` and `centralus` is supported, but requests result in error.
