### ISSUE TITLE
Azure.Storage.Blobs.Cryptography - Broken link - HTTP 404 Error

### ISSUE THREAD

**Issue by jonmikeli** [Azure/azure-sdk-for-net#22704]
[Enter feedback here]
HTTP 404 Error

Broken link:
https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.Storage.Blobs.Cryptography

![image](https://user-images.githubusercontent.com/22737122/126048185-703796c5-e2df-455e-841f-ac042c8a2df3.png)

Note:
I have tried to find the right link [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage) to propose a fix.
There is nothing that seems to match the expected content of the broken link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 910dab69-65c9-d3b9-4bde-a04320ab8f7d
* Version Independent ID: d85d233b-9b65-e24a-390f-1dc1e5844b40
* Content: [Azure Storage client libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage?view=azure-dotnet)
* Content Source: [api/overview/azure/storage.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/storage.md)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amnguye** [comment]
That line in the table should be removed considering that there's actually no `Azure.Storage.Blobs.Cryptography` package. To clarify the `Azure.Storage.Cryptography` is used by `Azure.Storage.Blobs` and `Azure.Storage.Queues`, so when customers go to use Encryption, this library will already be included.

I will submit a PR to remove this line.
