### ISSUE TITLE
incorrect English grammar means unclear explanation

### ISSUE THREAD

**Issue by kbdguy** [Azure/azure-sdk-for-net#22717]
"...on behalf of the user account which claims are provided in the User member..."

Not clear what that means.  Possibly "... on behalf of the user account in the User member..." and related to the claims requested on the call, but since I can't understand the original statement, I don't know.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 712b76af-89ea-f3a8-1efc-eef633348d92
* Version Independent ID: 8e15c5d3-3129-889f-587d-34f30a6d4de0
* Content: [ITokenAcquisition.GetAccessTokenForUserAsync Method (Microsoft.Identity.Web) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.itokenacquisition.getaccesstokenforuserasync?view=azure-dotnet-preview#Microsoft_Identity_Web_ITokenAcquisition_GetAccessTokenForUserAsync_System_Collections_Generic_IEnumerable_System_String__System_String_System_String_System_Security_Claims_ClaimsPrincipal_Microsoft_Identity_Web_TokenAcquisitionOptions_)
* Content Source: [xml/Microsoft.Identity.Web/ITokenAcquisition.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Web/ITokenAcquisition.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the [repository](https://github.com/AzureAD/microsoft-identity-web) where the `Microsoft.Identity.Web` package is maintained as [#1325](https://github.com/AzureAD/microsoft-identity-web/issues/1325).
