### ISSUE TITLE
Summary for Base64UrlEncoder.Encode(byte[]) overload is incorrect

### ISSUE THREAD

**Issue by AgWillow** [Azure/azure-sdk-for-net#22715]
The description of `Base64UrlEncoder.Encode(Byte[])` simply duplicates the description for `Encode(Byte[], Int32, Int32)`. It should read, "Converts an array of 8-bit unsigned integers to its equivalent string representation that is encoded with base-64-url digits."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ec745ad5-9e62-f99d-bdb6-0a6fe96f5e0b
* Version Independent ID: 12238b66-0c88-ab73-4e94-74acb53add3d
* Content: [Base64UrlEncoder.Encode Method (Microsoft.IdentityModel.Tokens) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.base64urlencoder.encode?view=azure-dotnet#Microsoft_IdentityModel_Tokens_Base64UrlEncoder_Encode_System_Byte___)
* Content Source: [xml/Microsoft.IdentityModel.Tokens/Base64UrlEncoder.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Tokens/Base64UrlEncoder.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This has been transferred to the [repository](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) where the `Microsoft.IdentityModel.Tokens` package is maintained, as [#1668](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1668).
