### ISSUE TITLE
EventHubProducerClient.CreateBatchAsync() never returns in web application with when HTTPRuntime targetFramework="4.7.2"

### ISSUE THREAD

**Issue by Abhijit77** [Azure/azure-sdk-for-net#22734]
Following in the code i am executing,  producerClient.CreateBatchAsync() line never responds
 var clientOptions = new EventHubProducerClientOptions
            {
                RetryOptions = new EventHubsRetryOptions
                {
                    MaximumRetries = 10,
                    Delay = TimeSpan.FromSeconds(5),
                    MaximumDelay = TimeSpan.FromSeconds(10),
                    Mode = EventHubsRetryMode.Fixed,
                    TryTimeout = TimeSpan.FromSeconds(5)
                }
            };
            var producerClient = new EventHubProducerClient("Endpoint=sb://abc", "ehName", clientOptions);

            var batch = producerClient.CreateBatchAsync();
----------------------------------
1. I am always connected to internet
2. Everything works perfectly fine in console app
3. Everything works perfectly fine in web app
4. As soon as i add _httpRuntime targetFramework="4.7.2"_ in web.config. producerClient.CreateBatchAsync() never returns the control back to application
5. If I change _httpRuntime targetFramework="4.8"_ in web.config, everything is back normal, working perfectly fine.

Our production systems are in 4.7.2 and want to continue stay the same for some more time, instead of creating one more framework version variable.

Is there anything i am missing ?

**Comment by Abhijit77** [comment]
GetAwaiter().GetResult() was the culprit

**Comment by deoraashish** [comment]
Hello Abhijit, I am facing the same problem here. I wanted to understand how you solved this. Your code doesn't use GetAwaiter().GetResult(). When I try to use the same on the CreateBatchAsync() I get a message that says, "ValueTaskAwaiter<EventBatchData> does not contain definition for 'GetAwaiter'
