### ISSUE TITLE
Null properties in Avro

### ISSUE THREAD

**Issue by eqr** [Azure/azure-sdk-for-net#2275]
I have issues serializing this class

```
    [DataContract]
    public class TestClass
    {
        [DataMember]
        public string Test { get; set; }
    }
```

with the next code:

```
 TestClass tc = new TestClass();
 var avro = AvroSerializer.Create<TestClass>();
 using (var mem = new MemoryStream())
  {
     avro.Serialize(mem, tc);
 }
```

Stack trace is:

> Microsoft.Hadoop.Avro.dll!Microsoft.Hadoop.Avro.BinaryEncoder.Encode(string value)
> [Lightweight Function]  
> Microsoft.Hadoop.Avro.dll!Microsoft.Hadoop.Avro.AvroSerializer<Com.IntApp.Walls.ExtensionServiceProcess.TestClass>.Serialize(Microsoft.Hadoop.Avro.IEncoder encoder, Com.IntApp.Walls.ExtensionServiceProcess.TestClass obj)
> Microsoft.Hadoop.Avro.dll!Microsoft.Hadoop.Avro.AvroSerializer<Com.IntApp.Walls.ExtensionServiceProcess.TestClass>.Serialize(System.IO.Stream stream, Com.IntApp.Walls.ExtensionServiceProcess.TestClass obj)

Adding tc.Test = "" makes thing working.

Is it legal to have null property strings? What's wrong with this code?

Thanks in advance.

**Comment by Inverness** [comment]
@eqr It's not legal to have null for strings in Avro. Null is considered its own type.

When using reflection, you must allow it by adding the NullableSchema attribute to the property.
