### ISSUE TITLE
[Sample] get all subscriptions in a tenant

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-sdk-for-net#22769]
**Query/Question**
Trying to get all subscriptions in a tenant and couldn't find sample

I'm guessing we can achieve this using below class but not sure how i can initialize it..
https://docs.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.subscriptionsoperations.list?view=azure-dotnet-preview#Azure_ResourceManager_Resources_SubscriptionsOperations_List_System_Threading_CancellationToken_

found sample in js sdk as below
https://stackoverflow.com/questions/50756033/azure-sdk-list-subscriptions

- I have is credentials object(generated using service principal)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
thanks for the inquiry. For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, existing Azure.ResourceManager.* SDKs has no plan to update now. They're subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks! cc @nickzhums

**Comment by ArthurMa1978** [comment]
Hi @prashanthmadi, the new Track 2 sdk has released, @HarveyLink  please help to provide the sample

**Comment by HarveyLink** [comment]
Hi @prashanthmadi , Here is a simple sample of how to get all subscriptions in a tenant.

Following packages are used in this sample:
[Azure.ResourceManager](https://www.nuget.org/packages/Azure.ResourceManager)
[Azure.Identity](https://www.nuget.org/packages/Azure.Identity/1.9.0-beta.1)

```
using Azure.Identity;
using Azure.ResourceManager;

var client = new ArmClient(new DefaultAzureCredential());
var subs = client.GetSubscriptions().GetAllAsync();
await foreach (var sub in subs)
{
    Console.WriteLine(sub.Data.DisplayName);
}
```
