### ISSUE TITLE
Support serialization option to ignore nulls in EventGridPublisherClient

### ISSUE THREAD

**Issue by Elip-tdlr** [Azure/azure-sdk-for-net#22765]
It would be useful to allow some serialization options such as ignoring nulls. This can significantly reduce the payload size in many cases.

https://github.com/Azure/azure-sdk-for-net/blob/3b0d98e1f079989fc6e5bca40a42ad5f26ff2a06/sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/EventGridPublisherClient.cs#L180

**Comment by JoshLove-msft** [comment]
Hi @Elip-tdlr, I assume you are wanting to ignore nulls from your Data payload. This is achievable today by using the constructor for EventGridEvent that takes a BinaryData instance for the data:
```cs
var customSerializer = new JsonObjectSerializer(
    new JsonSerializerOptions()
    {
        IgnoreNullValues = true
    });
var evt = new EventGridEvent(
    "ExampleEventSubject",
    "Example.EventType",
    "1.0",
    myCustomDataSerializer.Serialize(new CustomModel() { A = 5, B = true }));
```
