### ISSUE TITLE
invalid api-version

### ISSUE THREAD

**Issue by yamamoWorks** [Azure/azure-sdk-for-net#2276]
An error occurred when use this method.
`ComputeManagementClient.VirtualMachines.GetAsync()`

> The api-version '2016-03-30' is invalid. The supported versions are '2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

Version 13.0.4-prerelease

**Comment by adrianhall** [comment]
This is an old issue (and my apologies for not getting to it sooner - we're getting better at this, but there is a large backlog to process).  Is this within Microsoft.WindowsAzure.Management.Compute?  Is it still a problem in the latest version of the library?

**Comment by yamamoWorks** [comment]
I don't care this, too old...
No problem to close.
