### ISSUE TITLE
Implement design for ExtractiveSummarization

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#22773]
Following design https://apiview.dev/Assemblies/Review/f62ee261035a44189c597868c7a8a7ee?diffRevisionId=e29160855fe14bfb97045ae5c2220c70&doc=False&diffOnly=True

**Comment by kinelski** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-net/pull/22791 and https://github.com/Azure/azure-sdk-for-net/pull/22841.
