### ISSUE TITLE
[BUG] Context propagation for eventhub between Java and .NET is broken

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#22775]
**Describe the bug**
Spans for events sent from java app are not correlated with Spans for events on .NET processor.
Java sends `diagnostic-id` and .NET expects `Diagnostic-Id`, we should make it case-insensitive or support both spellings.

**Expected behavior**
Spans are correlated

**Actual behavior (include Exception or Stack Trace)**
Spans are not correlated

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. create java producer
2. create .net consumer (processor)
3. add opentelemetry/appinsights

**Environment:**
 - Name and version of the Library package used:  Azure.Messaging.EventHubs.Processor 5.5.0, Azure.Core 1.16.0
 - Hosting platform or OS and .NET runtime version, N/A
 - IDE and version : N/A

**Comment by jsquire** [comment]
//cc: @pakrym

**Comment by jsquire** [comment]
@lmolkova:  Not sure if it's helpful, but I can adjust on the Event Hubs side if we think that's the best path forward.   That said, it looks to be the same capitalization in Service Bus as well.

**Comment by lmolkova** [comment]
@jsquire I will definitely appreciate your help changing it, a couple of points:
- JS and Python and old ,.NET apps use `Diagnostic-Id`, so we can't stop supporting it, but we can additionally support `diagnostic-id`
- you're right, ServiceBus would have the same issue and it would be great to fix both

**Comment by jsquire** [comment]
> JS and Python and all existing .NET apps use Diagnostic-Id, so we can't stop supporting it, but we can additionally support diagnostic-id

Given that context, as well as knowing the legacy Event Hubs and Service Bus libraries in .NET did likewise, are we sure that changing the case in our EH and SB libraries would be desirable?  It seems like Java may be the outlier;  wouldn't it be better to align that with the other languages?

That said, @pakrym would have the best insight on feasibility of doing something case-insensitive in Core or the exporter; we should probably get his thoughts before making any decisions.

**Comment by lmolkova** [comment]
> wouldn't it be better to align that with the other languages

Yes, we need to change Java as well. If we just change it, we'll break context propagation between java apps: the current-version Java app will send context that the newer Java app would not understand. This is a breaking change (however tracing plugin in Java is still in preview, so we potentially can afford it). 

The alternative is to allow the old context key and the new one altogether. This way there is no breaking. Let me chat with few more java folks, maybe we'll break things :)

**Comment by lmolkova** [comment]
fixed on java, thanks @jsquire
