### ISSUE TITLE
[BUG]  TokenCredentialOptions is initialized in the wrong order in EnvironmentCredential 

### ISSUE THREAD

**Issue by yangyud-cn** [Azure/azure-sdk-for-net#22787]
**Describe the bug**
In the public ctor of EnvironmentCredential, the _options is only initialized after base ctor internal EnvironmentCredential(CredentialPipeline pipeline) is called which actually depends on this value to be initialized in advance.

https://github.com/Azure/azure-sdk-for-net/blob/4cc1a6811808cfe180294545b74aecd6b1e036b8/sdk/identity/Azure.Identity/src/EnvironmentCredential.cs#L54

**Expected behavior**
_options should be set in EnvironmentCredential(CredentialPipeline pipeline) before usage.

**Actual behavior (include Exception or Stack Trace)**
_options is null when EnvironmentCredential(CredentialPipeline pipeline) is called.

**To Reproduce**
Check code.

**Environment:**
In the latest code.

**Comment by yangyud-cn** [comment]
This is just a proposed fix to the issue, for your references only.  I'm having problem build the sdk source code at the moment and haven't had enough free time to sort that out yet.

[change.zip](https://github.com/Azure/azure-sdk-for-net/files/6860230/change.zip)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.
