### ISSUE TITLE
Auzre Storage Design Patterns Doc includes track 1 code snippets in C#

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-sdk-for-net#22793]
The Azure storage [table design patterns page](https://docs.microsoft.com/en-us/azure/storage/tables/table-storage-design-patterns) on Microsoft Docs includes example code snippets toward the end that look like they may be referencing Track 1 libraries. 

I could use some help with updating the code examples, so I'm creating an issue for follow up by engineering as per email conversation with Chris Scott. 

![Tables Design Patterns](https://user-images.githubusercontent.com/85648637/126685167-b128678b-fc55-47e4-ab40-495eeca5023c.JPG)

**Comment by zedy-wj** [comment]
We are upgrading `Table` from Track1 to Track2, we haven't found similar class as `DynamicTableEntity` in the new lib. Am I missing anything? In the new lib (Azure.Data.Table) `TableClient.Query<T>()` method need to specify the type of table entity

**Comment by christothes** [comment]
`TableEntity` Is the equivalent https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/src/TableEntity.cs

**Comment by zedy-wj** [comment]
Hi @christothes , Thank you for the guidance. 
This code snippet show to retrieves multiple entities of different types from the table, but returns all entities as DynamicTableEntity instances. It then uses the EntityType property to determine the type of each entity. 

We can use `TableEntity` instead `DynamicTableEntity` : 
`Pageable<TableEntity> entities = employeeTable.Query<TableEntity>(filter : )`

 But `EntityProperty` not be used any longer in new package (Azure.Data.Table), so how we get those types we need from entities in new package?

Code snippet :
```
string filter =
    TableQuery.CombineFilters(
        TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, "Sales"),
        TableOperators.And,
        TableQuery.CombineFilters(
            TableQuery.GenerateFilterCondition("RowKey", QueryComparisons.GreaterThanOrEqual, "B"),
            TableOperators.And,
            TableQuery.GenerateFilterCondition("RowKey", QueryComparisons.LessThan, "F")));
        
TableQuery<DynamicTableEntity> entityQuery =
    new TableQuery<DynamicTableEntity>().Where(filter);
    
var employees = employeeTable.ExecuteQuery(entityQuery);

IEnumerable<DynamicTableEntity> entities = employeeTable.ExecuteQuery(entityQuery);
foreach (var e in entities)
{
    EntityProperty entityTypeProperty;
    if (e.Properties.TryGetValue("EntityType", out entityTypeProperty))
    {
        if (entityTypeProperty.StringValue == "Employee")
        {
            // use entityTypeProperty, RowKey, PartitionKey, Etag, and Timestamp
        }
    }
}  
```

**Comment by christothes** [comment]
> Hi @christothes , Thank you for the guidance.
> This code snippet show to retrieves multiple entities of different types from the table, but returns all entities as DynamicTableEntity instances. It then uses the EntityType property to determine the type of each entity.
> 
> We can use `TableEntity` instead `DynamicTableEntity` :
> `Pageable<TableEntity> entities = employeeTable.Query<TableEntity>(filter : )`
> 
> But `EntityProperty` not be used any longer in new package (Azure.Data.Table), so how we get those types we need from entities in new package?
> 
> Code snippet :
> 
> ```
> string filter =
>     TableQuery.CombineFilters(
>         TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, "Sales"),
>         TableOperators.And,
>         TableQuery.CombineFilters(
>             TableQuery.GenerateFilterCondition("RowKey", QueryComparisons.GreaterThanOrEqual, "B"),
>             TableOperators.And,
>             TableQuery.GenerateFilterCondition("RowKey", QueryComparisons.LessThan, "F")));
>         
> TableQuery<DynamicTableEntity> entityQuery =
>     new TableQuery<DynamicTableEntity>().Where(filter);
>     
> var employees = employeeTable.ExecuteQuery(entityQuery);
> 
> IEnumerable<DynamicTableEntity> entities = employeeTable.ExecuteQuery(entityQuery);
> foreach (var e in entities)
> {
>     EntityProperty entityTypeProperty;
>     if (e.Properties.TryGetValue("EntityType", out entityTypeProperty))
>     {
>         if (entityTypeProperty.StringValue == "Employee")
>         {
>             // use entityTypeProperty, RowKey, PartitionKey, Etag, and Timestamp
>         }
>     }
> }  
> ```

I would re-write the above snippet like this:

```c#
await foreach (var entity in employeeTable.Query<TableEntity>(x =>
    x.PartitionKey ==  "Sales" && x.RowKey.CompareTo("B") >= 0 && x.RowKey.CompareTo("F") <= 0))
{
    if (entity.GetString("EntityType") == "Employee")
    {
        // use entityTypeProperty, RowKey, PartitionKey, Etag, and Timestamp
    }
}
```

**Comment by zedy-wj** [comment]
@christothes - Thanks a lot!

**Comment by mario-guerra** [comment]
The doc has been update and this issue can be closed.
