### ISSUE TITLE
More details on SearchOptions.Facets please

### ISSUE THREAD

**Issue by dwat001-auror** [Azure/azure-sdk-for-net#22808]
It would be great to have the syntax and value for the facet options here, or a link to the documentation of that.
e.g. ",count:10,sort:count" I don't know other options as that is what I am looking for :)

Ahh there found it https://docs.microsoft.com/en-us/rest/api/searchservice/search-documents `Query Parameters - facet` is the documentation that should be replicated or linked to from this page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 82915345-60a2-c113-aaf6-b75341afe105
* Version Independent ID: 6d9c141c-6221-ccf6-78df-f47656387ecc
* Content: [SearchOptions.Facets Property (Azure.Search.Documents) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.searchoptions.facets?view=azure-dotnet#Azure_Search_Documents_SearchOptions_Facets)
* Content Source: [xml/Azure.Search.Documents/SearchOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Search.Documents/SearchOptions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
