### ISSUE TITLE
Fix Graph ToenAudience for built-in environments and allow setting in connectionstring

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2280]
### Description

Change the GraphTokenAudience to match the graph endpoint for all built-in environments.  The graph endpoitn in test clusters has changed so that it no longer accepts https://graph.windows.net

Also, use the graph token audience setting when constructing the TestEnvironemtn here:  https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/TestFramework/Microsoft.Rest.ClientRuntime.Azure.TestFramework/TestEnvironment.cs#L249

Fix and publish a new test library for consumption in powershell

### COST: 2

**Comment by corinajacobson** [comment]
May I check in to see if anyone is currently working on this? Unfortunately I'm partially blocked on my current project being unable to run tests on daily tests endpoint.

**Comment by markcowl** [comment]
This is fixed in the AutoRest branch, just need to update the test library

**Comment by markcowl** [comment]
Closing as fixed
