### ISSUE TITLE
Prevent releases of packages with cross-service ProjectReference

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#22834]
Libraries often take a dependency on the unreleased Azure.Core to get new features. 

If the ProjectReference is not changed to PackageReference before release it could lead to a package being released that doesn't have all required dependencies. 

We should catch all ProjectReference that cross service boundary (from storage to core) and fail the release process.

**Comment by pallavit** [comment]
I believe this is already added as a check to all our pipelines - @weshaggard , @hallipr to confirm.

**Comment by pallavit** [comment]
@benbp I believe this issue was fixed as well similar to validating release dependency are already on nuget before releasing the package. Please correct me if that is not the case.
