### ISSUE TITLE
Cognitive Services Keyword Missing Link in Page

### ISSUE THREAD

**Issue by bcage29** [Azure/azure-sdk-for-net#22833]
The Text in the article:

> See also: [Use a keyword model with the SDK](/azure/cognitive-services/speech-service/custom-keyword-basics?pivots=programming-language-csharp#use-a-keyword-model-with-the-sdk)

Is not showing as a link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a99f9e4-cef6-7bdd-27a7-12d85de06aaa
* Version Independent ID: ab0fe6e4-171e-f273-3518-92e083b47a93
* Content: [SpeechRecognizer.StartKeywordRecognitionAsync(KeywordRecognitionModel) Method (Microsoft.CognitiveServices.Speech) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognizer.startkeywordrecognitionasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.CognitiveServices.Speech/SpeechRecognizer.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.CognitiveServices.Speech/SpeechRecognizer.xml)
* Service: **cognitive-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
The root of this appears to be the `<remarks>` tag using embedded markdown instead of the `<seealso href="...">Some Link</seealso>`  or `<see href="...">Some Link</seealso>` syntax that the MS Docs pipeline will translate.   A quick scan of the `Content Source` linked above shows a few more links that would also fail to render.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by bcage29** [comment]
Also, found another for the same topic [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.keywordrecognitionmodel?view=azure-dotnet):
