### ISSUE TITLE
[Event Grid] test failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#22831]
Event Grid nightly test runs are failing with:

> Error Message
> Azure.RequestFailedException : The principal associated with access token presented with the incoming request does not have permission to send data to /subscriptions/2cd617ea-1866-46b1-90e3-fffb087ebf9b/resourceGroups/rg-eventgrid-t04b41f9ba5334509/providers/Microsoft.EventGrid/topics/t04b41f9ba5334509cloudevent-topic. Report '5e3d4746-b3b7-4329-add6-e4fb4e5ae1be:0:7/19/2021 7:55:30 PM (UTC)' to our forums for assistance or raise a support ticket.
> Status: 401 (The principal associated with access token presented with the incoming request does not have permission to send data to /subscriptions/2cd617ea-1866-46b1-90e3-fffb087ebf9b/resourceGroups/rg-eventgrid-t04b41f9ba5334509/providers/Microsoft.EventGrid/topics/t04b41f9ba5334509cloudevent-topic. Report '5e3d4746-b3b7-4329-add6-e4fb4e5ae1be:0:7/19/2021 7:55:30 PM (UTC)' to our forums for assistance or raise a support ticket.)
> ErrorCode: Unauthorized
> 
> Content:
> {
> "error": {
> "code": "Unauthorized",
> "message": "The principal associated with access token presented with the incoming request does not have permission to send data to /subscriptions/2cd617ea-1866-46b1-90e3-fffb087ebf9b/resourceGroups/rg-eventgrid-t04b41f9ba5334509/providers/Microsoft.EventGrid/topics/t04b41f9ba5334509cloudevent-topic. Report '5e3d4746-b3b7-4329-add6-e4fb4e5ae1be:0:7/19/2021 7:55:30 PM (UTC)' to our forums for assistance or raise a support ticket.",
> "details": [{
> "code": "Unauthorized",
> "message": "The principal associated with access token presented with the incoming request does not have permission to send data to /subscriptions/2cd617ea-1866-46b1-90e3-fffb087ebf9b/resourceGroups/rg-eventgrid-t04b41f9ba5334509/providers/Microsoft.EventGrid/topics/t04b41f9ba5334509cloudevent-topic. Report '5e3d4746-b3b7-4329-add6-e4fb4e5ae1be:0:7/19/2021 7:55:30 PM (UTC)' to our forums for assistance or raise a support ticket."
> }]
> }
> }
> 
> Headers:
> Server: Microsoft-HTTPAPI/2.0
> Strict-Transport-Security: REDACTED
> x-ms-request-id: 5e3d4746-b3b7-4329-add6-e4fb4e5ae1be
> Date: Mon, 19 Jul 2021 19:55:29 GMT
> Content-Length: 1017
> Content-Type: application/json; charset=utf-8
> 
> Stack Trace
> at Azure.Messaging.EventGrid.EventGridPublisherClient.SendCloudEventsInternal(IEnumerable`1 events, Boolean async, CancellationToken cancellationToken) in /_/sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/EventGridPublisherClient.cs:line 259
>    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task) in /_/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 33
>    at Azure.Messaging.EventGrid.EventGridPublisherClient.SendEvents(IEnumerable`1 cloudEvents, CancellationToken cancellationToken) in /_/sdk/eventgrid/Azure.Messaging.EventGrid/src/Customization/EventGridPublisherClient.cs:line 229
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 165
>    at Azure.Messaging.EventGrid.Tests.EventGridClientLiveTests.CanPublishCloudEventAAD() in /mnt/vss/_work/1/s/sdk/eventgrid/Azure.Messaging.EventGrid/tests/EventGridClientLiveTests.cs:line 298
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1004287&view=results

**Comment by JoshLove-msft** [comment]
This was probably due to RBAC permissions not being propagated in time. We already have a 120 second delay though here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventgrid/test-resources-post.ps1.

I just ran the pipeline twice and no errors. Will keep an eye on it and adjust delay if needed.
