### ISSUE TITLE
[BUG] StatusMessage:The uncommitted block count cannot exceed the maximum limit of 100,000 blocks. ErrorCode:BlockCountExceedsLimit

### ISSUE THREAD

**Issue by MohitNagpaldce** [Azure/azure-sdk-for-net#22856]
![image](https://user-images.githubusercontent.com/11233980/126892820-df65d995-5d8f-4b5f-b3d8-8a04a4d8b14d.png)

**Comment by MohitNagpaldce** [comment]
Question is around. on using StreamWriteSizeInBytes = 8 MB and writing on blobstream.write. Unless 8MB*100000 => 800GB is written , it should not give 100000 block limit error. How uncommited block are counted when using blobstream.write. expectation is each block will be 8 MB.

**Comment by amishra-dev** [comment]
Hi @MohitNagpaldce /Mohit,
Every time we upload we create a new block, if the overall write fails the block stays behind until the GC runs or until the blob is committed (putblocklist) or deleted . If you do not see the blob committed yet in your account, you can just call a delete blob on it and it will clear-up all the uncommitted blocks.

**Comment by MohitNagpaldce** [comment]
Thanks Amishra. So to understand it correctly setting StreamWriteSizeInBytes = 8 MB and. writing on blobstream.write(data)  total lets say 50 GB so ideally it should create 50GB/8MB = 6400 blocks.  writing on blobstream.write. 
However if write fails than it could be more blocks left behind so can cause this error and which on retry should be solved.
another Question is , stream.dispose , does the putblocklist automatically ?

**Comment by amishra-dev** [comment]
Yes it should

**Comment by Alilux** [comment]
Bug contacting me
