### ISSUE TITLE
Move to .Net 4.5.2. 

### ISSUE THREAD

**Issue by sphibbs** [Azure/azure-sdk-for-net#2285]
support for 4, 4.5 and 4.5.1 is going away. We will need to move to a more recent version of .Net. 

Plan is to target the lowest supported version which is currently 4.5.2

**Comment by erezvani1529** [comment]
Thanks @sphibbs! Do we have an ETA for this change? (any specific Azure SDK version?)

**Comment by sphibbs** [comment]
Not yet. We'll tag the milestone here and communicate on slack once it's scheduled.
