### ISSUE TITLE
[FEATURE REQ] Convenient method to generate SAS url from user delegation key

### ISSUE THREAD

**Issue by yufeih** [Azure/azure-sdk-for-net#22866]
**Library or service name.**
Azure.Storage.Blobs
 
**Is your feature request related to a problem? Please describe.**
For storage clients created from account key, there is a convenient `GenerateSasUri` method to generate a blob SAS url. The security best practice suggests to use MSI for authentication, thus the code need to switch to use user delegation key. There are some common problems about user delegation key that needs taken care for each consumer:

- For best performance, a user delegation key could be cached in memory to sign subsequent requests until expiry.
- The cache refresh should consider user delegation key expiration as well as SAS url expiration.
- Handle request burst scenario so we don't make excessive user delegation key get requests.

This feature request asks the blob client SDK to provider a helper method that allows developers to generate SAS urls easily and efficiently using user delegation key, providing a similar experience as `GenerateSasUri` today, with the above details encapsulated underneath.

**Comment by amnguye** [comment]
Very similar to this feature request, can probably be done in conjunction.
https://github.com/Azure/azure-sdk-for-net/issues/16470
