### ISSUE TITLE
[QUERY] Replacement for IRetryPolicy.ShouldRetry in V12 of Azure Blob Storage SDK

### ISSUE THREAD

**Issue by vrozovmicrosoft** [Azure/azure-sdk-for-net#22860]
We are migrating from AzureStorage SDK V11 to V12

We implement IRetryPolicy interface, particularly we implement ShouldRetry() method use our own logic to decide if the retry is needed.

How this can be implemented with SDK V12 using ClientOptions.RetryOptions or any other classes?.

**Comment by jsquire** [comment]
@pakrym:  This seems more relevant to the `Azure.Core` pipeline than Storage specifics.   Would you be so kind as to offer your thoughts and redirect if needed?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
There is currently no way to provide custom retry logic in V12 SDK but we are looking into designing a feature like this.

What additional logic do you have in your custom `ShouldRetry`?

**Comment by vrozovmicrosoft** [comment]
Thanks for your reply.
Please, find below the method with most of the logic. In addition we have detailed traces per each 'return' in this method.

 public bool ShouldRetry(int currentRetryCount, int statusCode, Exception lastException, out TimeSpan retryInterval, OperationContext operationContext)
{
	retryInterval = GetRetryInterval(currentRetryCount);

	if (statusCode == 0)
	{

		if (lastException is IOException && lastException.InnerException == null)
		{
			return true;
		}

		var webException = lastException as WebException;
		if (webException != null)
		{
			HttpWebResponse httpWebResponse = webException.Response as HttpWebResponse;
			if (httpWebResponse != null)
			{
				// Surface the inner status code up and take action on it
				return ShouldRetry(currentRetryCount, (int)httpWebResponse.StatusCode, webException, out retryInterval, operationContext);
			}

			if (webException.Status == WebExceptionStatus.Success)
			{
				return false;
			}

			if (ExtendedWebExceptionStatus.IsTransient(webException.Status))
			{
				return true;
			}

			return false;
		}

		var socketException = lastException as SocketException;
		if (socketException != null)
		{
			bool result = ExtendedSocketError.IsTransient(socketException.SocketErrorCode);
			return result;
		}

		// We can't decide on the outer exception, so try deciding on any inner (if there is one)
		if (lastException?.InnerException != null)
		{
			return ShouldRetry(currentRetryCount, statusCode, lastException.InnerException, out retryInterval, operationContext);
		}

		// Something else that we haven't seen so far...
		// We assume it is non-retryable
		return false;
	}

	// If this method is called after a successful response, it means
	// we failed during the response body download. So, we should not
	// check for success codes here
	if ((statusCode >= 300 && statusCode < 500 && statusCode != 408)
		|| statusCode == 501 // Not implemented
		|| statusCode == 505 // Version not supported
		|| lastException?.Message == "Blob type of the blob reference doesn't match blob type of the blob." // We apologize for the stupidity that forced us to do this
		)
	{
		return false;
	}

	// Do not retry permanent errors
	bool permanent = ExtendedException.IsTransient(lastException).IsFalse;

	bool tryAgain = !permanent && (currentRetryCount < m_maxAttempts);
	var operation = GetOperationFromOperationContext(operationContext);

	return tryAgain;
}

**Comment by pakrym** [comment]
It seems there is a lot of cases that we already handle today. The goal of our new SDKs is to bring customers a complete experience out of the box. I would recommend trying the V12 SDK without custom retry logic and if you see a request that should be retried but isn't filing an issue.

cc @kasobol-msft
