### ISSUE TITLE
[FEATURE REQ] Make it possible to mock SchemaRegistryClient

### ISSUE THREAD

**Issue by PSanetra** [Azure/azure-sdk-for-net#22868]
**Library or service name.**
Azure.Data.SchemaRegistry
 
**Is your feature request related to a problem? Please describe.**
As far as I can see it is currently not possible to mock the `SchemaRegistryClient` type as it is not possible to create instances of the `SchemaProperties` type. Other Azure SDK libraries like `Azure.Storage.Blobs` provide Factory classes like `BlobsModelFactory` to create instances of such classes for mocking purposes, but a similar Factory class is missing in `Azure.Data.SchemaRegistry`.

**Comment by PSanetra** [comment]
@AlexGhiondea @JoshLove-msft is there already a release containing the factory class?

**Comment by JoshLove-msft** [comment]
No there is not. Adding this issue to our November milestone.

**Comment by JoshLove-msft** [comment]
This was fixed in https://github.com/Azure/azure-sdk-for-net/pull/25099 and is available in the GA version of Azure.Data.SchemaRegistry.
