### ISSUE TITLE
Use StringIndexType from Azure.Core and default to UTF-16

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#22887]
There was some talk about putting `StringIndexType` into Azure.Core, and @annatisch suggested we default it to UTF-16 if not hide it all together.

/cc @maririos

**Comment by heaths** [comment]
See https://github.com/Azure/azure-sdk-for-net/blob/fe8e623c8ef31810a4712fb12fec4ecbc019859f/sdk/textanalytics/Azure.AI.TextAnalytics/src/Constants.cs#L10 for what @maririos did.

**Comment by annatisch** [comment]
Looking at how this is handled in the TextAnalytics in the Python SDK - the default is set [at the client level](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py#L122-L124), and can be [overridden per operation](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py#L281-L285). The default value is `UnicodeCodePoint`.

Current default in QnA is `TextElements_v8`. I think if the default is to change - that needs to be from the Service team and updated in the Swagger spec.
As for hiding this setting and handling it internally, for QnA, this is part of the request model, not an operation argument. And the model already defaults the value.

**Comment by maririos** [comment]
For more context on TA, the default for the service is also `TextElements_v8` so someone that uses REST can decide which encoding according to the environment they are using.

Each library sets the value that aligns with its language. .NET, JS, and Java use `Utf16CodeUnit` and Python `UnicodeCodePoint` so the output the service sends makes sense for that language

**Comment by annatisch** [comment]
Ah thanks for that context @maririos! That helps :)

**Comment by annatisch** [comment]
In that case we might need to move the clientside per-language default into a directive in the autorest readme to update the model. Otherwise we'd need to hand-wrap the generated models which I'd rather avoid...
Or we remove this from the generated model entirely, and like TA, have this as a client parameter that we apply to the outgoing model on request.
