### ISSUE TITLE
Generating a SAS for a DataLake Blob Directory

### ISSUE THREAD

**Issue by vivere-dally** [Azure/azure-sdk-for-net#22896]
In portal, I can click on a directory and generate a SAS for it and all it's children recursively.
![image](https://user-images.githubusercontent.com/62178141/127127292-94fff8be-f324-468d-8d8c-0e9f01812509.png)

The Resource types for `BlobSasBuilder` do not work. I also tried with `DatalakeSasBuilder` or something like that, but I saw it is mainly used for file system? (correct me if I'm wrong).

How can I do the same using the .Net SDK?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 077b3fa5-15a2-e3a8-10f6-2bd25e001b09
* Version Independent ID: 85c7f2d2-d246-45a4-3e95-7abbbc207821
* Content: [BlobSasBuilder.Resource Property (Azure.Storage.Sas) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.sas.blobsasbuilder.resource?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Sas/BlobSasBuilder.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Sas/BlobSasBuilder.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amnguye** [comment]
Hi,

In order to create a SAS for the directory and all of its files and subdirectories you can either two ways.

Generate using a DataLakeDirectoryClient (recommended way to not have to specify a lot of parameters)
```
// client authenticated with a Shared Key (connection string contains the shared key)
DataLakeDirectoryClient directoryClient = new DataLakeDirectoryClient(connectionString, fileSystemName, path);
// generate the SAS with setting the permissions and the expirey time
Uri sasUri = directoryClient.GenerateSasUri(DataLakeSasPermissions.All, Recording.UtcNow.AddDays(1));
// OR to specify more parameters pass a DataLakeSasBuilder
DataLakeSasBuilder sasBuilder = new DataLakeSasBuilder(permissions, expiresOn)
{
    StartsOn = startsOn
};
Uri sasUri = directoryClient.GenerateSasUri(sasBuilder);
```

Using the DataLakeSasBuilder to generate a directory SAS
```
DataLakeSasBuilder sasBuilder = new DataLakeSasBuilder(permissions, expiresOn)
{
    FileSystemName = fileSystemName,
    Path = path,
    IsDirectory = true,
};
DataLakeUriBuilder expectedUri = new DataLakeUriBuilder(serviceUri)
{
    FileSystemName = fileSystemName,
    DirectoryOrFilePath = path
    **Sas = sasBuilder2.ToSasQueryParameters(constants.Sas.SharedKeyCredential);**
};
```

Please let me know if you have any questions.

**Comment by vivere-dally** [comment]
> Hi,
> 
> In order to create a SAS for the directory and all of its files and subdirectories you can either two ways.
> 
> Generate using a DataLakeDirectoryClient (recommended way to not have to specify a lot of parameters)
> 
> ```
> // client authenticated with a Shared Key (connection string contains the shared key)
> DataLakeDirectoryClient directoryClient = new DataLakeDirectoryClient(connectionString, fileSystemName, path);
> // generate the SAS with setting the permissions and the expirey time
> Uri sasUri = directoryClient.GenerateSasUri(DataLakeSasPermissions.All, Recording.UtcNow.AddDays(1));
> // OR to specify more parameters pass a DataLakeSasBuilder
> DataLakeSasBuilder sasBuilder = new DataLakeSasBuilder(permissions, expiresOn)
> {
>     StartsOn = startsOn
> };
> Uri sasUri = directoryClient.GenerateSasUri(sasBuilder);
> ```
> 
> Using the DataLakeSasBuilder to generate a directory SAS
> 
> ```
> DataLakeSasBuilder sasBuilder = new DataLakeSasBuilder(permissions, expiresOn)
> {
>     FileSystemName = fileSystemName,
>     Path = path,
>     IsDirectory = true,
> };
> DataLakeUriBuilder expectedUri = new DataLakeUriBuilder(serviceUri)
> {
>     FileSystemName = fileSystemName,
>     DirectoryOrFilePath = path
>     **Sas = sasBuilder2.ToSasQueryParameters(constants.Sas.SharedKeyCredential);**
> };
> ```
> 
> Please let me know if you have any questions or if this resolves your issue.

I have one more question. I think I'm not familiar with the terminology but does this create a SAS for the blobs or for files/directories in the file shares? I'm working with the blob storage. If you have a hierarchical namespace (datalake) then the terminology changes from blobs to files? I'm not getting it.

**Comment by amnguye** [comment]
Hi,

Our documentation writers wrote up this great document about DataLake that would help you understand the difference.
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction

Essentially just to answer your question, this would create a SAS for a DataLake Directory (not a SMB file share directory). When you have Hierarchical namespace (datalake) enabled, then the terminology changes to datalake file (not SMB file). This is because datalake works on top of blobs.

**Comment by gopala000** [comment]
I followed the steps given earlier and always get the below exception. Azure side everything is open. I'm not sure what changes the name of my DFS endpoint https://gopdfsfoo.dfs.core.windows.net/ to gopblobfoo.dfs.core.windows.net. 

`One or more errors occurred. (Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry. (No such host is known. (gopblobfoo.dfs.core.windows.net:443)) (No such host is known. (gopblobfoo.dfs.core.windows.net:443)) (No such host is known. (gopblobfoo.dfs.core.windows.net:443)) (No such host is known. (gopblobfoo.dfs.core.windows.net:443)) (No such host is known. (gopblobfoo.dfs.core.windows.net:443)) (No such host is known. (gopblobfoo.dfs.core.windows.net:443)))
`
Code below:
```
        public static async Task WTH(DataLakeSasPermissions permissions)
        {
            // client authenticated with a Shared Key (connection string contains the shared key)
            DataLakeDirectoryClient directoryClient = new DataLakeDirectoryClient("redacted connection string" , "gop-filesystem2", "gop-dir");
            // generate the SAS with setting the permissions and the expirey time
            Uri sasUri = directoryClient.GenerateSasUri(DataLakeSasPermissions.All, DateTimeOffset.UtcNow.AddDays(1));

            DataLakeDirectoryClient sasDirectoryClient = new DataLakeDirectoryClient(sasUri);

            // Act
            await foreach (PathItem pathItem in sasDirectoryClient.GetPathsAsync())
            {
                // Just make sure the call succeeds.
                Console.WriteLine(pathItem.Name);
            }
        }

```
@vivere-dally
