### ISSUE TITLE
[BUG] azure media services - crop issue

### ISSUE THREAD

**Issue by dehghanfar** [Azure/azure-sdk-for-net#22895]
I believe there is a bug with the encoder in azure media services.

this is my encoding code in C#

```csharp
                 var aacAudio = new AacAudio(channels: 2, samplingRate: 48000, bitrate: 128000,
                        profile: AacAudioProfile.AacLc);
 
                               rectangle = new Rectangle("656", "0", "1079", "607");

                    var hd3600Kbps = new H264Layer(bitrate: 3600000, height:"640", width:"360");

                    var h264Video = new H264Video(keyFrameInterval: TimeSpan.FromSeconds(2),
                        layers: new[] {hd3600Kbps});
                    var pngLayer = new PngLayer("50%", "50%");
                    var pngImage = new PngImage("25%", step: "25%", range: "80%", layers: new[] {pngLayer});
                    var codecs = new Codec[] {aacAudio, h264Video, pngImage};
                    var mp4Format = new Mp4Format("Video.{Basename}.{Label}.{Bitrate}{Extension}");
                    var pngFormat = new PngFormat("Thumbnail-{Basename}-{Index}{Extension}");
                    var formats = new Format[] {mp4Format, pngFormat};
                    var filters = rectangle == null ? null : new Filters {Crop = rectangle};
                    var standardEncoderPreset = new StandardEncoderPreset(codecs, formats, filters);
                    var outputs = new TransformOutput[]
                        {new(standardEncoderPreset, OnErrorType.StopProcessingJob, Priority.Normal)};


                    await client.Transforms.CreateOrUpdateAsync(_azureMediaOption.ResourceGroup,
                        _azureMediaOption.AccountName,
                        transformName,
                        outputs,
                        cancellationToken: cancellationToken);
```

I am cropping the video with this info:

{Left: 656, Top: 0, Height: 1079, Width: 607}

The video I have is 1920x1080 using the C# code above, the video needs to  get cropped and encoded.

azure media services gives me an output but the output video is not cropped properly. 

if I manually change the bit rate of the video on my computer and then encode it again this time it will work. I uploaded both videos as attachments to this issue.

this one is the problematic video, the video that dose not encode based on the code
https://user-images.githubusercontent.com/14353301/127079656-667419c0-2de2-45f6-850a-da03041e8e86.mp4

here is the exact same video but with different bit rate and it gets encoded based on the job input

https://user-images.githubusercontent.com/14353301/127079720-375c406b-e672-43df-a47b-6589fe93ff5c.mp4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jiayali-ms** [comment]
Hi @dehghanfar, can you confirm that the two videos you linked/uploaded in your original post are the output videos? If they are the output videos, can you link/upload the source input video so we can do a deeper dive into the problem? Thanks.

**Comment by dehghanfar** [comment]
@jiayali-ms  they are the source video,  if I crop them, one of them work the other one doesn't work.

I had to move to AWS media converter because of this bug for my need. they do it right on these two videos

**Comment by jiayali-ms** [comment]
@dehghanfar, thanks for confirming that. Both of those videos are output videos, just different bitrates. The 1920x1080 one does not encode with the code given. 

What is your desired output? Can you link/paste it in here? Our team tried to crop with the code and it had worked for us. If we can see what you want to achieve, we can help identify if there's a bug in the encoder. Thanks.

**Comment by dehghanfar** [comment]
@jiayali-ms  both are input video. I want to encode (crop, encode, trim) them one of them work and the other one dosnt work. I pasted the code.

the crop doesn't work. I now moved on to AWS I dont have it handy to test it if it is working. I am pretty sure the code was not cropping the input video properly.

if it works for you, I take your word.

**Comment by jiayali-ms** [comment]
Thanks for the feedback @dehghanfar, I'm sorry to hear that you moved to AWS. Our team will continue investigating this issue. In the meantime, it seems that you have found your own solution, so @jsquire can we close this issue?
