### ISSUE TITLE
[BUG] The latest change for Azure.Core doesn't fix the bug in Unity  

### ISSUE THREAD

**Issue by daiyk** [Azure/azure-sdk-for-net#22901]
Hi, I test the new fix in Unity, I found that the [#22539](https://github.com/Azure/azure-sdk-for-net/pull/22539#issue-686142286) PR for Azure.Core didn't fix the bug, the code actually catch the wrong exception

Unity uses a very old version of Mono, so the access to some https functions throws NotImplementedException rather than NotSupportedException, in their code [Unity Https](https://github.com/Unity-Technologies/mono/blob/unity-2021.1-mbe/mcs/class/System.Net.Http/System.Net.Http/HttpClientHandler.cs#L448).

**Environment:**
-Azure.Data.tables 12.1.0, Unity 2020.3.6f LTS
-.NET SDKs 5.0.301 and Windows 10 10.0.19041
-IDE and version : [e.g. Visual Studio Version 16.10.2

I just created a new PR to fix the issue, tested in Unity.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
