### ISSUE TITLE
Convert old operation types to use new Operation Helper

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#22914]
Track 2 data plane libraries that make use of LROs:
- [x] FormRecognizer
- [ ] MixedReality.RemoteRendering
- [ ] Storage.Blobs
- [ ] Synapse.Spark
- [x] TextAnalytics
- [ ] Translation

KeyVault is being tracked by https://github.com/Azure/azure-sdk-for-net/issues/22912.

**Comment by annelo-msft** [comment]
Note: OperationHelper has been superseded by OperationInternal

**Comment by heaths** [comment]
Removing this from TA for project tracking purposes since it's already handled.

**Comment by pallavit** [comment]
@kinelski is this still valid, can you please help me understand what is needed to be done here and what is the benefit of doing this?

**Comment by annelo-msft** [comment]
This may be superseded by other LRO efforts happening in Core.  If not, we should file a "step back and take stock of LROs and unify the many LRO pieces we have" issue, possibly as part of https://github.com/Azure/azure-sdk-for-net/issues/28369 or other of the shared source tracking issues.
