### ISSUE TITLE
Enable spellchecker

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#22917]
In order to enable spell checker, we need to add `SpellCheckPublicApiSurface: true` to https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/translation/ci.yml#L25.

To run the tool, run `eng\scripts\Export-API.ps1 -SpellCheckPublicApiSurface translation`.
If there are errors, we need to fix them. If there are false positives, we need to add them to https://github.com/Azure/azure-sdk-for-net/blob/main/.vscode/cspell.json#L68

Part of https://github.com/Azure/azure-sdk-for-net/issues/17798

**Comment by AhmedLeithy** [comment]
I ran the tool and there are no errors to be found.

![image](https://user-images.githubusercontent.com/41678585/127356922-019753a5-1775-4aaa-acf8-315f24861467.png)

**Comment by maririos** [comment]
Awesome!! 
We will still need to enable it for our live tests.
You will have to create a PR with the changes:
> In order to enable spell checker, we need to add SpellCheckPublicApiSurface: true to https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/translation/ci.yml#L25.

**Comment by AhmedLeithy** [comment]
Yes of course, I forgot to PR the change. I have created the PR #22992.
