### ISSUE TITLE
Blazor WASM - how to get SAS

### ISSUE THREAD

**Issue by ivancavlek** [Azure/azure-sdk-for-net#22929]
**Query/Question**
Hi,

I am using Blazor WASM to connect directly to Azure Blob Storage (without a supporting server side code).

My intention is to use the storage resource URL inside HTML tags (like images and videos in `<img>` and `<video>` tags). As these URLs should only be visible inside my organization, I have set the container Public access level to _Private (no anonymous access)_. As I understand, the only option to achieve this is through SAS, which I want to retrieve through SDK.

When I try to execute `ToSasQueryParameters` I always get _System.PlatformNotSupportedException: System.Security.Cryptography.Algorithms is not supported on this platform_.

I understand that this is a limitation in .NET 5 with Blazor WASM.
My question is, if I have done everything correctly, is there a workaround or an alternative approach?

```C#
async Task<string> IAzureStorageService.GetUserDelegationSasTokenUriAsync(string uri)
{
    var userDelegationKey = await GetUserDelegationKey();
    var containerName = await ContainerName();
    var storageAccountUri = StorageAccountUri();

    var sasBuilder = new BlobSasBuilder(BlobSasPermissions.Read, EndOfCurrentDay())
    {
        BlobContainerName = containerName,
        BlobName = uri[(uri.LastIndexOf("/") + 1)..],
        Resource = "b"
    };

    var blobUriBuilder = new BlobUriBuilder(new Uri(uri))
    {
        Sas = sasBuilder.ToSasQueryParameters(userDelegationKey, StorageAccountName())
    };

    return blobUriBuilder.ToUri().AbsoluteUri;
}

private async Task<UserDelegationKey> GetUserDelegationKey()
{
    if (_userDelegationKey is not null)
        return _userDelegationKey;

    var blobServiceClient = new BlobServiceClient(
        new Uri(StorageAccountUri()), new AzureTokenCredential(_accessTokenProvider));

    _userDelegationKey = await blobServiceClient.GetUserDelegationKeyAsync(CurrentTime(), EndOfCurrentDay());

    return _userDelegationKey;
}

internal class AzureTokenCredential : TokenCredential
{
    private readonly IAccessTokenProvider _accessTokenProvider;

    public AzureTokenCredential(IAccessTokenProvider accessTokenProvider) =>
        _accessTokenProvider = accessTokenProvider;

    public override async ValueTask<Azure.Core.AccessToken> GetTokenAsync(
        TokenRequestContext requestContext, CancellationToken cancellationToken)
    {
        var accessTokenResult = await _accessTokenProvider
            .RequestAccessToken(
                new AccessTokenRequestOptions
                {
                    Scopes = new List<string> { "https://storage.azure.com/user_impersonation" }
                });

        if (accessTokenResult.TryGetToken(out var accessToken))
            return new Azure.Core.AccessToken(accessToken.Value, accessToken.Expires);

        throw new Exception("Couldn't get the access token");
    }

    public override Azure.Core.AccessToken GetToken(
        TokenRequestContext requestContext, CancellationToken cancellationToken)
    {
        // in Blazor, it only works async, this throws PlatformNotSupported as of 06.2021.
        throw new NotImplementedException();
    }
}
```

![image](https://user-images.githubusercontent.com/16662190/127331679-a412c979-5c73-4cda-a2f9-3fb0d4af1121.png)

**Environment:**
 - Azure.Storage.Blobs 12.9.1 
 - Windows 10, .NET 5
 - Visual Studio 16.10.4

**Comment by amnguye** [comment]
I don't think there's a way to create a User Delegation SAS if `ToSasQueryParameters` is not functional under .NET 5 using Blazor WASM. This library, `System.Security.Cryptography.Algorithms` is required to compute the SHA256.

Is generating a Service SAS an option?

**Comment by ivancavlek** [comment]
If I understand correctly, to create a Service SAS I would have to present the storage account key?
If true, unfortunately that won't do for security reasons. For Blazor WASM that would mean that I have to store the key in app's config file and then the app is distributed across the Internet. It has no service backend like ASP.NET MVC or similar technologies. Storage Account key would be exposed.

Can you tell me if there are plans to circumvent this limitation for such apps as Blazor WASM?

**Comment by amnguye** [comment]
There are no plans for this because it's required that we computer the SHA256 when signing the User Delegation SAS.

**Comment by amnguye** [comment]
Closing this issue if there are no further questions.
