### ISSUE TITLE
Support Fine Grained Audience AAD Token in storage SDKs

### ISSUE THREAD

**Issue by XiaoningLiu** [Azure/azure-sdk-for-net#22925]
**Library or service name.**

Azure.Storage
 
**Is your feature request related to a problem? Please describe.**

.Net SDK is using a hard coded scope/audience when acquiring an AAD token.

https://github.com/Azure/azure-sdk-for-net/blob/d1ab8677aa2e78ee1568c57cc75bf990855f34e8/sdk/storage/Azure.Storage.Common/src/Shared/StorageClientOptions.cs#L21

The hard coded audience "https://storage.azure.com" is general and the generated AAD token can apply to any accounts and any services (blob, queue, table). The recommendation is to use a fine-grained audience like https://account1.blob.core.windows.net, which can be applied only for account1 and blob service.

Can we have a feature to customize?

**Comment by kasobol-msft** [comment]
@schaabs

**Comment by amnguye** [comment]
Looks like a thing we might have to add?
https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app?tabs=dotnet#azure-storage-resource-id

**Comment by christothes** [comment]
@kasobol-msft  Is there something missing in Azure.Identity or Azure.Core that prevents Storage from allowing this granularity?

**Comment by kasobol-msft** [comment]
@christothes I added you to relevant email thread. @schaabs may know more about Azure.Identity plans for this feature.
