### ISSUE TITLE
[QUERY] - How do I mock an IPage<DeploymentOperation> for my unit tests

### ISSUE THREAD

**Issue by 1RedOne** [Azure/azure-sdk-for-net#22930]
**Query/Question**
I saw this blog post which provides an example of making a Page using the `.FromValues` method but with the Azure Resource Manager SDK, I don't see this exposed as an option when trying to mock a DeploymentOperations object.

We are specifically trying to setup a moq for this method:

![image](https://user-images.githubusercontent.com/1247626/127344583-63d91dd4-730d-4d56-962c-c105e41ae368.png)
```
ResourceManagerClient.DeploymentOperations.ListAtScopeWithHttpMessagesAsync
```
This method returns an object of type 

```
Task<AzureOperationResponse<IPage<DeploymentOperation>>>
```

We have tried a number of things and been unable to create a Mock object of this type for unit testing.  How do we convert our test response object into a Paged version?  Note: making an AzureOperationResponce isn't too hard, it's the Page/IPage that is giving us grief.

```
var operationProperties = new DeploymentOperationProperties(
                provisioningOperation: ProvisioningOperation.Create,
                provisioningState:"complete",
                DateTime.UtcNow,
                duration:"2 minutes", 
                serviceRequestId:null, 
                statusCode: "OK", 
                statusMessage: new StatusMessage("OK"));

            var myOperation = new DeploymentOperation(
                id:"someid123", operationId:"hello",
                properties: operationProperties);

            var l = myOperation as Page<DeploymentOperation>;
```

This gives an error of:

>Cannot convert type 'Microsoft.Azure.Management.ResourceManager.Models.DeploymentOperation' to 'Microsoft.Azure.Management.ResourceManager.Models.Page<Microsoft.Azure.Management.ResourceManager.Models.DeploymentOperation>' via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion

Documentation for this shows people using `Page<T>.FromValues` which we do not see as available.

**Environment:**
 - Name and version of the Library package used:  
 Microsoft.Azure.Management.ResourceManager. 3.13.1-preview
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
hi @archerzz could you help on this? thanks

**Comment by archerzz** [comment]
Hi @1RedOne I guess the blog post you've read is [this one](https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/), right? It's for the track2 (e.g. new design) SDK. All SDK with name pattern `Azure.XXXX` is track2.

For track2 resources SDK, you may want to check [Azure.ResourceManager.Resources](https://www.nuget.org/packages/Azure.ResourceManager.Resources/1.0.0-beta.1)

As for track1, @pakrym do you have any suggestion? Thanks.

**Comment by pakrym** [comment]
The easiest might be to compy one of the existing page models that implement IPage and use it in tests:

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/redis/Microsoft.Azure.Management.Redis/src/Generated/Models/Page.cs

```
var operationProperties = new DeploymentOperationProperties(
                provisioningOperation: ProvisioningOperation.Create,
                provisioningState:"complete",
                DateTime.UtcNow,
                duration:"2 minutes", 
                serviceRequestId:null, 
                statusCode: "OK", 
                statusMessage: new StatusMessage("OK"));

            var myOperation = new DeploymentOperation(
                id:"someid123", operationId:"hello",
                properties: operationProperties);
var page = new Page<DeploymentOperation>()
{
    Items = new List<DeploymentOperation>()
	{
		{  myOperation  }
	}
}
```

**Comment by archerzz** [comment]
Thanks @pakrym !

@1RedOne Does that resolve your question?
