### ISSUE TITLE
[BUG] Timeseries Insights with DateTime as value results in parse error.

### ISSUE THREAD

**Issue by ebbz** [Azure/azure-sdk-for-net#22976]
**Describe the bug**
When requesting a DateTime as value via the TimeSeriesIngsights an exception is thrown.
Inspecting the returned json shows a correct timestamp is present in the response
Code:
`(DateTimeOffset)value.GetValue("mydatetimevalue");`

**Expected behavior**
Correctly parse to a DateTimeOffset when a DateTime value is being parsed by the client.

**Actual behavior (include Exception or Stack Trace)**
Exception:
```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.String' to type 'System.Nullable`1[System.DateTimeOffset]'.
  Source=Azure.IoT.TimeSeriesInsights
  StackTrace:
   at Azure.IoT.TimeSeriesInsights.PropertyValues.CreateValues()
   at Azure.IoT.TimeSeriesInsights.PropertyValues.get_Values()
   at Azure.IoT.TimeSeriesInsights.TimeSeriesPoint.GetValue(String propertyName)
   ...
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a query like this:
```
AsyncPageable<TimeSeriesPoint> GetLatestMeasurementAsync(..)
{
            var queryclient = _client.GetQueriesClient();
            TimeSeriesId id = CreateTimeSeriesId(deviceId);
            var span = new TimeSpan(30, 0, 0, 0);
            var options = new QueryAggregateSeriesRequestOptions { Store = StoreType.WarmStore };

            var valueExpression = new TimeSeriesExpression($"coalesce($event.['x'].Double, todouble($event.['x'].Long))");
            var valueName = "value";
            var typevar = new NumericVariable(valueExpression, new TimeSeriesExpression($"last($value)"));
            options.InlineVariables[valueName] = typevar;
            options.ProjectedVariableNames.Add(valueName);

            var valueName2 = "lasttime";
            var typevar2 = new AggregateVariable(new TimeSeriesExpression($"last($event.$ts)"));
            options.InlineVariables[valueName2] = typevar2;
            options.ProjectedVariableNames.Add(valueName2);

            var x = queryclient.CreateAggregateSeriesQuery(id, start, end, span, options, cancellationToken);
            return x.GetResultsAsync();
}
```
2.
Get the value like this:

```
await foreach(var value in GetLatestMeasurementAsync(...))
{
 var time = (DateTimeOffset)value.GetValue("lasttime");
}
```

**Environment:**
 - Azure.IoT.TimeSeriesInsights [1.0.0-beta.1]
- .NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 - IDE and version :Visual Studio 16.10.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ebbz** [comment]
Is anybody looking into this?
