### ISSUE TITLE
Add Claim Check pattern sample

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#22970]
Add a sample that shows how to integrate with Storage SDK to implement claim check pattern.

**Comment by SeanFeldman** [comment]
This would not be necessary if pipelines (#11986, #12943) would be implemented.

**Comment by SeanFeldman** [comment]
Thank you, @JoshLove-msft.
Too bad pipelines are not there. All the code would not need to be written :)
