### ISSUE TITLE
[Servicebus] AbandonMessages failing intermittently in nightly runs

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#22986]
Servicebus nightly test runs are failing with:

> Error message
> String lengths are both 36. Strings differ at index 0.
> Expected: "4814a91e-9abb-4c4c-b0cd-c6cd08647d42"
> But was:  "93d3cdf6-e6aa-42b8-8890-397182d5fed5"
> -----------^
> 
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Receiver.SessionReceiverLiveTests.AbandonMessages(Boolean useSpecificSession) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/SessionReceiverLiveTests.cs:line 410
>    at Azure.Messaging.ServiceBus.Tests.Receiver.SessionReceiverLiveTests.AbandonMessages(Boolean useSpecificSession) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/SessionReceiverLiveTests.cs:line 434
>    at Azure.Messaging.ServiceBus.Tests.Receiver.SessionReceiverLiveTests.AbandonMessages(Boolean useSpecificSession) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/SessionReceiverLiveTests.cs:line 435
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass5_0.<RunTestOnSeparateThread>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()

For more details check here:
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=956483&view=results

**Comment by JoshLove-msft** [comment]
Has not been failing for a while.
