### ISSUE TITLE
Microsoft.Azure.WebJobs.Extensions.Storage does not fire BlobTrigger on CloudBlockBlob when version >= v4

### ISSUE THREAD

**Issue by tobimax** [Azure/azure-sdk-for-net#22989]
When using Microsoft.Azure.WebJobs.Extensions.Storage does not fire BlobTrigger on CloudBlockBlob when version > 3

Create an Azure Function

`
public static async Task Run([BlobTrigger("incoming/{name}", Connection = "SourceStorageAccount")] CloudBlockBlob sourceBlob, string name, ILogger log)
{
}
`

The Event does not fire is the Microsoft.Azure.WebJobs.Extensions.Storage  is v4 or v5.

What is the expected behavior? The Blob trigger to fire.

What is the actual behavior? The Trigger does not fire.

Steps to reproduce the behavior

Create Azure BlobTrigger Function using v4 or v5  Microsoft.Azure.WebJobs.Extensions.Storage

**Comment by paulbatum** [comment]
Hi @tobimax!

You can't bind to a CloudBlockBlob using the V5 extension. The type CloudBlockBlob does not exist in `Azure.Storage.Blobs`. For more information on the differences in Azure.Storage.Blobs see [here](https://github.com/Azure/azure-sdk-for-net/blob/38441a45981c9c9433c6b78382ee23cebcb60309/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md#migrating-from-cloudblockblob). You will get a startup error if you try to do that. It will look something like this:

`The 'Function1' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Host: Can't bind BlobTrigger to type 'Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob'.`

![image](https://user-images.githubusercontent.com/10663/127686196-b69df72a-ffa5-470a-834d-796b49ebb7d3.png)

If you're using the V4 extension you have to be careful to make sure you're using the right CloudBlockBlob type, as the namespaces changed between storage v9 and storage v11, and you need to be using the v11 type. You can do that by doing `using Microsoft.Azure.Storage.Blob;` and **not** `using Microsoft.WindowsAzure.Storage.Blob;`

If you are still having problems getting the V4 extension blob trigger to work with CloudBlockBlob after following above, I suggest you file a support case (you can use the azure portal, just "New Support Case" in the lefthand nav with the function app open). If you don't want to file a support case you could file an issue against functions host and fill out the template, but you're likely to get a quicker response with the support case. You would do that here:
https://github.com/Azure/azure-functions-host/issues/new?assignees=&labels=&template=Bug_report.md

You will need to include more detail if you file the issue as the above description isn't enough to determine why the V4 trigger isn't working for you.

**Comment by jchannon** [comment]
What should you use for `v5 Microsoft.Azure.WebJobs.Extensions.Storage` where you had a `CloudBlockBlob` previously?
