### ISSUE TITLE
[Servicebus] test failing in nightly runs

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#22987]
Servicebus nightly test runs are failing with:

> Error message
> System.AggregateException : One or more hosted services failed to stop. (  cff4e46c-f1f9-FixtureSetUp-83add967-5ed8-451e-9dd5-988e950f634a: RenewSessionLockAsync Exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
> at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 171 at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.RenewSessionLockAsync(CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1116 at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.RenewSessionLockAsync(CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusSessionReceiver.cs:line 235. Expected: <empty> But was: < <[13:23:40.902] [Azure.Messaging.ServiceBus] cff4e46c-f1f9-FixtureSetUp-83add967-5ed8-451e-9dd5-988e950f634a: RenewSessionLockAsync Exception: System.Threading.Tasks.TaskCanceledException: A task was canceled. at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 171
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.RenewSessionLockAsync(CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1116
> at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.RenewSessionLockAsync(CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusSessionReceiver.cs:line 235. > >
> )
> ----> NUnit.Framework.AssertionException :   cff4e46c-f1f9-FixtureSetUp-83add967-5ed8-451e-9dd5-988e950f634a: RenewSessionLockAsync Exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
> at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 171 at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.RenewSessionLockAsync(CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1116 at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.RenewSessionLockAsync(CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusSessionReceiver.cs:line 235. Expected: <empty> But was: < <[13:23:40.902] [Azure.Messaging.ServiceBus] cff4e46c-f1f9-FixtureSetUp-83add967-5ed8-451e-9dd5-988e950f634a: RenewSessionLockAsync Exception: System.Threading.Tasks.TaskCanceledException: A task was canceled. at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 171
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.RenewSessionLockAsync(CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1116
> at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.RenewSessionLockAsync(CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusSessionReceiver.cs:line 235. > >
> 
> cff4e46c-f1f9-FixtureSetUp-83add967-5ed8-451e-9dd5-988e950f634a: RenewSessionLockAsync Exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
> at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, Cancellatio
> 
> Stack trace
>    at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusSessionsEndToEndTests.ServiceBusSessionQueue_DifferentHosts_DifferentSessions() in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusSessionsEndToEndTests.cs:line 140
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> --AssertionException
>    at NUnit.Framework.Assert.ReportFailure(String message)
>    at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
>    at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
>    at NUnit.Framework.Assert.IsEmpty(IEnumerable collection, String message, Object[] args)
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTestService.StopAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/WebJobsServiceBusTestBase.cs:line 260
>    at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=956483&view=results

**Comment by jsquire** [comment]
This appears to be a transient failure due to an environmental issue; no test adjustments are needed.
