### ISSUE TITLE
[Servicebus] ServiceBusBinderTestSyncCollector failing intermittently in nightly runs

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#22985]
Servicebus nightly test runs are failing with:

> Error message
> Expected: 30
> But was:  19
> 
> 
> Stack trace
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.ServiceBusBinderTestAsyncCollector() in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusEndToEndTests.cs:line 76
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=949784&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=989154&view=results

**Comment by JoshLove-msft** [comment]
Has not failed recently.
