### ISSUE TITLE
[Servicebus] UserCallbackThrowingCausesMessageToBeAbandonedIfNotSettled failing intermittently in nightly runs

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#22982]
Servicebus nightly test runs are failing with:

> Error message
> Expected: not null
> But was:  null
> 
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.UserCallbackThrowingCausesMessageToBeAbandonedIfNotSettled(String settleMethod) in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/SessionProcessorLiveTests.cs:line 863
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.UserCallbackThrowingCausesMessageToBeAbandonedIfNotSettled(String settleMethod) in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/SessionProcessorLiveTests.cs:line 882
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.UserCallbackThrowingCausesMessageToBeAbandonedIfNotSettled(String settleMethod) in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/SessionProcessorLiveTests.cs:line 882
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.UserCallbackThrowingCausesMessageToBeAbandonedIfNotSettled(String settleMethod) in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/SessionProcessorLiveTests.cs:line 883
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass5_0.<RunTestOnSeparateThread>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=927009&view=results

**Comment by JoshLove-msft** [comment]
Not failing recently.
