### ISSUE TITLE
[Servicebus] StopProcessingAllowsCallbackToComplete failing intermittently in nightly runs

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#22984]
Servicebus nightly test runs are failing with:

> Error message
> Multiple failures or warnings in test:
> 
> Azure.Messaging.ServiceBus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. Reference:4905f38c-f9ae-4a1a-9a80-1313a95d7bdc, TrackingId:c3cb094d000000010001cd9d60b9fcf9_G4_B4, SystemTracker:sb-tf18fc84165db49c6:Queue:4c01c121-9f26-stopprocessinga, Timestamp:2021-06-04T10:14:44 (MessageLockLost)
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.DisposeMessageAsync(Guid lockToken, Outcome outcome, TimeSpan timeout) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 530
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteInternalAsync(Guid lockToken, TimeSpan timeout) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 474
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<CompleteAsync>b__40_0>d.MoveNext() in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 447
> --- End of stack trace from previous location ---
> at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__201.<<RunOperation>b__20_0>d.MoveNext() in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 113 --- End of stack trace from previous location --- at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 144
> at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 164 at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1](Func4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 110
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteAsync(Guid lockToken, CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 443
> at Azure.Messaging.ServiceBus.ServiceBusReceiver.CompleteMessageAsync(Guid lockToken, CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs:line 544
> at Azure.Messaging.ServiceBus.ServiceBusReceiver.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs:line 507
> at Azure.Messaging.ServiceBus.ProcessMessageEventArgs.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ProcessMessageEventArgs.cs:line 62
> at Azure.Messaging.ServiceBus.Tests.Processor.ProcessorLiveTests.<>c__DisplayClass10_0.<<StopProcessingAllowsCallbackToComplete>g__ProcessMessage|0>d.MoveNext() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/ProcessorLiveTests.cs:line 579
> --- End of stack trace from previous location ---
> at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessMessageAsync(ProcessMessageEventArgs args) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs:line 441
> at Azure.Messaging.ServiceBus.ReceiverManager.OnMessageHandler(ServiceBusReceivedMessage message, CancellationToken processorCancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs:line 254
> at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs:line 168
> Azure.M
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.ServiceBusTestBase.ExceptionHandler(ProcessErrorEventArgs eventArgs) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Infrastructure/ServiceBusTestBase.cs:line 42
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs:line 451
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args)
>    at Azure.Messaging.ServiceBus.ReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs:line 357
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs)
>    at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs:line 200
>    at Azure.Messaging.ServiceBus.Tests.ServiceBusTestBase.ExceptionHandler(ProcessErrorEventArgs eventArgs) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Infrastructure/ServiceBusTestBase.cs:line 42
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs:line 451
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args)
>    at Azure.Messaging.ServiceBus.ReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs:line 357
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs)
>    at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs:line 200
>    at Azure.Messaging.ServiceBus.Tests.ServiceBusTestBase.ExceptionHandler(ProcessErrorEventArgs eventArgs) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Infrastructure/ServiceBusTestBase.cs:line 42
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs:line 451
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args)
>    at Azure.Messaging.ServiceBus.ReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs:line 357
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs)
>    at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage message, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs:line 200
>    at Azure.Messaging.ServiceBus.Tests.ServiceBusTestBase.ExceptionHandler(ProcessErrorEventArgs eventArgs) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/te

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=927009&view=results

**Comment by jsquire** [comment]
Hi @Tianyun-G:  The team working on Service Bus is aware of the inconsistency of some tests and is tracking on their own; there's no need to monitor Service Bus runs and file issues.

**Comment by jsquire** [comment]
@v-xuto:  Please be aware that you're assigning the wrong individual for Service Bus issues.   The Josh that you're looking for is @JoshLove-msft.

**Comment by v-xuto** [comment]
@jsquire - I'm sorry, thanks for your reminder.

**Comment by JoshLove-msft** [comment]
No longer occurring.
