### ISSUE TITLE
Max values for maxBatchSize and prefetchCount

### ISSUE THREAD

**Issue by ajsaclayan** [Azure/azure-sdk-for-net#22997]
What is the maximum value for maxBatchSize? I wasn't able to find the constraints in the docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47f65d3b-7b17-223e-2ffa-caff402d0e57
* Version Independent ID: 3a7e1ff6-06f6-672f-b9bc-05c642d94593
* Content: [EventProcessorOptions.MaxBatchSize Property (Microsoft.Azure.EventHubs.Processor) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor.eventprocessoroptions.maxbatchsize?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.EventHubs.Processor/EventProcessorOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.EventHubs.Processor/EventProcessorOptions.xml)
* Service: **event-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @ajsaclayan.  The maximum for the batch size and prefetch counts are not bounded by the client; they are constrained only be the limits of its type declaration.   In this case,  [int](https://docs.microsoft.com/dotnet/csharp/language-reference/builtin-types/integral-numeric-types#characteristics-of-the-integral-types) which has a maximum of 2,147,483,647.

An important call-out, however, is that the `maxBatchSize` is the maximum size that you'll receive in a single call, intended to limit the amount not.   It does not guarantee the number of events that you will receive in a batch and the client does not attempt to build a batch of that size.  Each receive call will return the number of events that are available in the prefetch queue.  If the prefetch queue is empty, the client will attempt to wait until the queue has at least one event available and then populate the batch with those.

**Comment by serkantkaraca** [comment]
As @jsquire pointed there is no boundary for those settings other than the INT type. I would also like to add that most clients won't see any meaningful improvements after around 5000 on both settings.
