### ISSUE TITLE
[Jenkins] Publish job will publish all the packages under a directory

### ISSUE THREAD

**Issue by pomortaz** [Azure/azure-sdk-for-net#2300]
When trying to publish one package in Key Vault project using this [job](http://azuresdkci.cloudapp.net/view/2-.NET%20SDK/job/sdk-for-net-publish), all packages gets published.

Key Vault has multiple NuGet packages and we tried to only publish one package using [these parameters](http://azuresdkci.cloudapp.net/view/2-.NET%20SDK/job/sdk-for-net-publish/887/parameters/). However, the job published [all the packages](http://azuresdkci.cloudapp.net/view/2-.NET%20SDK/job/sdk-for-net-publish/887/console).

**Comment by pomortaz** [comment]
@markcowl any update?

**Comment by herveyw** [comment]
@markcowl @pomortaz We could do with a fix here, our last publish job published our private test framework to the public NuGet servers...

**Comment by markcowl** [comment]
as part of this, we should ensure that Batch and DataLake packages (including StoreUploader) can be individually signed and published

**Comment by shahabhijeet** [comment]
This has been fixed a while back (see issue# 2549). Please let me know or reopen this issue if you still see any problem.
