### ISSUE TITLE
[BUG] KeyVault certificate download fails using latest SDK

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/azure-sdk-for-net#23016]
**Describe the bug**
I'm trying to download a PFX certificate, including the private key, from KeyVault using the new `DownloadCertificateAsync` method from the 4.2.0 version of the `Azure.Security.KeyVault.Certificates` package.

I've ensured the calling code has read access to both the certificate and the secrets in KeyVault. Unfortunately calling this method to obtain an X509Certificate2 fails with a WindowsCryptographicException.

I've done everything I can think of to confirm this isn't an obvious error on my part, but since the API is new, maybe there are still some bugs or edge cases.

**Expected behavior**
The file is downloaded as an X509Certificate, including the private key.

**Actual behavior (include Exception or Stack Trace)**
An exception is thrown:

```
Result: Failure Exception: System.AggregateException: One or more errors occurred.
(The system cannot find the file specified.) ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: 
The system cannot find the file specified. at Internal.Cryptography.Pal.CertificatePal.FilterPFXStore(ReadOnlySpan`1 rawData, SafePasswordHandle password, PfxCertStoreFlags pfxCertStoreFlags) at 
Internal.Cryptography.Pal.CertificatePal.FromBlobOrFile(ReadOnlySpan`1 rawData, String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags) at 
System.Security.Cryptography.X509Certificates.X509Certificate..ctor(ReadOnlySpan`1 data) at 
System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(Byte[] rawData) at 
Azure.Security.KeyVault.Certificates.CertificateClient.DownloadCertificateAsync(String certificateName, String version, 
CancellationToken cancellationToken)
```

**To Reproduce**

1. Store a certificate with an exportable key in KeyVault
2. Configure permissions for GET for both certificates and secrets
2. Attempt to download the certificate with `var certificate = await certificateClient.DownloadCertificateAsync("mycert");`

**Environment:**
 - Azure.Security.KeyVault.Certificates 4.2.0
 - .NET 5.0
 - Azure Functions running in Azure on private App Service Plan.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Thank you for helping us troubleshoot the issue. I had a couple follow-up questions:

1. What key algorithm did you use to create the key?
2. If you feel comfortable doing so, could you share the public key so I could examine the ASN.1-encoded headers?

**Comment by juna-gupta** [comment]
@heaths I think X509KeyStorageFlags should be set to EphemeralKeySet | MachineKeySet in the SDK as these certificates are not persisted on disk. 

Identity.Web library does that :

 [LoadFromKeyVault](https://github.com/AzureAD/microsoft-identity-web/blob/210645a5ccc0a9b888a05f0bde8222ccc95dff72/src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs#L105)
[Setting default flags](https://github.com/AzureAD/microsoft-identity-web/blob/210645a5ccc0a9b888a05f0bde8222ccc95dff72/src/Microsoft.Identity.Web/CertificateManagement/CertificateDescription.cs#L250)

**Comment by BrianVallelunga** [comment]
I did not create the key, but it was given to me to communicate with Azure AD in order to get a token for SQL Azure. From what I've seen, I think this is just an issue on Azure Functions. I had a similar issue trying to load the certificate from blob storage and ended up needing the EphemeralKeySet | MachineKeySet settings @juna-gupta suggested as well.

 Right now I'm working around this by uploading the cert to the App Service and getting it via the following code:

    using var certStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);
    certStore.Open(OpenFlags.ReadOnly);
    var certCollection = certStore.Certificates.Find(X509FindType.FindByThumbprint, "XXXXXX", false);
    return certCollection.OfType<X509Certificate2>().First();

This works, but I'd certainly like to use KeyVault.

**Comment by heaths** [comment]
Thanks @juna-gupta and @BrianVallelunga for the info. I'll give that a try. It's odd the issue didn't repro in the various tests I have but perhaps the environment into which these encoded certificates matters. I don't persist to disk, as you noted, but my tests are running under a test runner and no in Azure Functions.

I can try to repro with Azure Functions, but since you already have an environment in which you know this fails, would you be willing to test a private with this change? Or is that what you did already when you said:

> and ended up needing the EphemeralKeySet | MachineKeySet settings @juna-gupta suggested as well.

Did you clone, modify, and build the source to test that?

**Comment by heaths** [comment]
As for where to fix this, can you wait until the next beta release (early September) or do you require a servicing event to existing GA'd libraries?

**Comment by BrianVallelunga** [comment]
I can certainly wait since I'm loading the certificate from the app service right now and that is working fine for us. 

I haven't tested this to be entirely sure, but I think the issue is probably present in both Azure Functions and general app service instances. I needed to add a configuration key of WEBSITE_LOAD_CERTIFICATES to make loading the uploaded certificates work. In theory you set the value equal to a comma-separated list of thumbprints, but I've seen reports that even dummy values will work since the presence of just the key with any allow the app service to work with certificates.

I didn't modify the source myself, I am simply not storing the certificate in KeyVault for now. If you do want to send me a build to test, I'll go ahead and do that.

When I said that I used `EphemeralKeySet  |  MachineKeySet` that was on a previous attempt with storing the certificate in blob storage. I was able to get that to work with those settings, but it was easier to store it directly on the App Service itself.

**Comment by heaths** [comment]
I'm talking with cryptography experts in both .NET and Windows about why this is happening and whether we can safely pass these flags unconditionally - thinking about cross-platform cryptography (Mac [will fail](https://docs.microsoft.com/dotnet/standard/security/cross-platform-cryptography#:~:text=macos%20can't%20load%20certificate%20private%20keys%20without%20a%20keychain%20object) with `EphemeralKeySet`, for example)), as well as process elevation e.g., will `MachineKeySet` fail for a non-elevated application. When OR'd with `EphemeralKeySet` it shouldn't since the private key wouldn't be persisted to disk, but then that raises the question of why `MachineKeySet` is needed at all.

**Comment by heaths** [comment]
We're probably just going to add an options bag to let you specify your own storage flags. After some internal discussion, there's no certain default that will work in every case e.g. some App Services SKUs.

That said, `DownloadCertificate` was new in 4.2.0 so there's no regression. I'd also make sure the fixed method does not break (i.e. I'll add an overload). If you were downloading the cert and related secret before to construct your own `X509Certificate2`, you might continue doing so. The new overload we'll add hopefully should work, but if you can't wait the old "manual" way of downloading a certificate will still work.

**Comment by BrianVallelunga** [comment]
@heaths Thanks for the update.
