### ISSUE TITLE
MessageText property missing from QueueMessage class docs. (And VS intellisense completions?)

### ISSUE THREAD

**Issue by osobeso** [Azure/azure-sdk-for-net#23011]
Hi, I noticed the documentation doesn't have the 'MessageText' property.
Also, when using Visual Studio's IntelliSense autocompletion 'MessageText' doesn't appear as one of the completions for a QueueMessage object, but when you type it without using the completion assistance, it works, which is really weird (not sure if it's related due to it being missing from the docs?)

When I ctrl+click onto the MessageText property it does send me to metadata of QueueMessage and it shows there.

![messageTextMissing](https://user-images.githubusercontent.com/54292402/127706405-b03a01a3-3afe-4ab4-9598-48f14f2f2744.gif)

Not sure if this is the right place to report it, but it's really confusing to figure property MessageText exists out without the proper docs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e04d90ca-7f80-aa7c-5bae-3da124040703
* Version Independent ID: b0c301bf-72b0-fdb2-a544-72fd0ff70684
* Content: [QueueMessage Class (Azure.Storage.Queues.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.models.queuemessage?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Queues.Models/QueueMessage.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Queues.Models/QueueMessage.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amnguye** [comment]
This is intentional. We would prefer that you would use `BinaryData Body` instead of `string MessageText` in order to ensure the contents of the message do not get altered in some sort of way when being converted to a string.

**Comment by osobeso** [comment]
@amnguye Thanks for clearing that out and for the quick response!

Just to point out that the [docs](https://docs.microsoft.com/en-us/azure/storage/queues/storage-dotnet-how-to-use-queues?tabs=dotnet) on using Queues seem to be deprecated as they use MessageText on their samples.
That's where my confusion came from in the first place.

Regards,
Oscar.

**Comment by amnguye** [comment]
Thanks for pointing those docs out, I will contact the docs owner to make sure those samples get updated that way they use the recommended way of accessing the body of the queue message.

**Comment by amnguye** [comment]
The change has been made https://github.com/Azure-Samples/AzureStorageSnippets/pull/149.
