### ISSUE TITLE
[BUG] RecordedTestBase fails to collect logs for failed tests

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#23023]
To diagnose an issue happening only in the live test pipeline I tried to look at logs however they seem to incomplete. About 10% of the tests in the results seem to have StdOutput, and these were all passed tests. None of the failing tests had any logs. I also tried explicitly enabling log collection:

```c#
        private AzureEventSourceListener _logListener;

        [SetUp]
        public void EnableLogging()
        {
            _logListener = new AzureEventSourceListener((_, message) => TestContext.WriteLine(message), EventLevel.Verbose);
        }

        [TearDown]
        public void DisableLogging()
        {
            _logListener.Dispose();
        }
```

However this still didn't result in the logs being collected.

**Comment by pakrym** [comment]
cc @JoshLove-msft 

I think I've seen this in monitor tests as well. Makes it very hard to debug issues.

**Comment by pakrym** [comment]
Also, it seems that devops doesn't show the stdout attachment even when it exists. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1025206&view=ms.vss-test-web.build-test-results-tab&runId=22051432&paneView=debug&resultId=100200

**Comment by pakrym** [comment]
I think the latter is the result of the test passing.

>If you use the Visual Studio Test task to run tests, diagnostic output logged from tests (using any of Console.WriteLine, Trace.WriteLine or TestContext.WriteLine methods), will appear as an attachment for a failed test.

**Comment by heaths** [comment]
I changed this in Key Vault a while back and would be interested in doing this; though, I think I removed it by request since it could be a lot of info. I think we can do it a little differently to reduce the load on AzDO, though.

**Comment by heaths** [comment]
This has been working correctly for a while at least. Here's an example of a failed test (throttled) with everything captured to stdout:

![Image](https://user-images.githubusercontent.com/1532486/205400039-72feb53d-67b1-4c39-81d3-99aa493b20dc.png)

If you are seeing this in other cases still, please reopen with a link to the build I can take a further look.
