### ISSUE TITLE
[BUG] Failed to use AzurePageBlob.UploadPagesFromUriAsync with data from managed disk incremental snapshot

### ISSUE THREAD

**Issue by Yutolivo** [Azure/azure-sdk-for-net#23031]
**Describe the bug**
Use API AzurePageBlob.UploadPagesFromUriAsync to upload a page into target page blob while the source Uri is the SAS Uri from a incremental managed disk snapshot.

**Expected behavior**
Upload pages successfully.

**Actual behavior (include Exception or Stack Trace)**
Source blob of a copy operation cannot be non-snapshot incremental copy blob.
RequestId:04d2b21f-201e-00c3-1eb7-865f83000000
Time:2021-08-01T09:24:52.9391333Z
Status: 409 (Source blob of a copy operation cannot be non-snapshot incremental copy blob.)
ErrorCode: CopySourceCannotBeIncrementalCopyBlob

Content:
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>CopySourceCannotBeIncrementalCopyBlob</Code><Message>Source blob of a copy operation cannot be non-snapshot incremental copy blob.
RequestId:04d2b21f-201e-00c3-1eb7-865f83000000
Time:2021-08-01T09:24:52.9391333Z</Message></Error>

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-error-code: CopySourceCannotBeIncrementalCopyBlob
x-ms-request-id: 04d2b21f-201e-00c3-1eb7-865f83000000
x-ms-version: 2020-08-04
x-ms-client-request-id: 560c07cb-5c97-4667-9636-e2af49757d34
Date: Sun, 01 Aug 2021 09:24:52 GMT
Content-Length: 284
Content-Type: application/xml

**To Reproduce**
1. Create a managed disk incremental snapshot.
2. Generate SAS uri with read permission for the snapshot.
3. Initialize a source page blob with SAS uri
4. Initialize a target page blob.
5. Get pages info from source page blob
6. Upload the pages with invoking the API AzurePageBlob.UploadPagesFromUriAsync
7. You can use the sample code to reproduce the issue https://github.com/Azure-Samples/managed-disks-dotnet-backup-with-incremental-snapshots.
8. Important！！！！！ The API can be invoked with no errors with Azure.Storage.Blobs 12.4.1, when update the package to Azure.Storage.Blobs 12.9.1, the error occurred.

**Environment:**
 - Azure.Storage.Blobs 12.9.1
 - Windows 10 .NET Framework 5.0.300
 - Visual Studio Community 2019 16.10.31321.278

**Comment by Yutolivo** [comment]
I tested with Azure.Storage.Blobs 120.10.0-beta.2, still got the error.

**Comment by amishra-dev** [comment]
@kasobol-msft can you take a quick look at this tomorrow.

**Comment by kasobol-msft** [comment]
@Yutolivo Thank you for reporting. I was able to reproduce this problem using [the sample](https://github.com/Azure-Samples/managed-disks-dotnet-backup-with-incremental-snapshots).
The problem seems to be introduced on the service side starting with version `2020-06-12` of the REST API.

While this is investigated further the workaround is to downgrade service version used by `PageBlobClient` when calling `UploadPagesFromUriAsync` API. Example below:
![image](https://user-images.githubusercontent.com/61715331/127902679-8b8b73ac-b34b-4f89-a568-9ce2d567eb68.png)

**Comment by kasobol-msft** [comment]
@Yutolivo Yes, we'll be working on the fix and will post update here when this is addressed.

**Comment by amishra-dev** [comment]
The service fix is still rolling out. I am trying to get an ETA for it.

**Comment by amishra-dev** [comment]
The service fix has rolled out for this.
