### ISSUE TITLE
Microsoft.Azure.Management.Authorization AuthorizationManagementClient exception

### ISSUE THREAD

**Issue by briansteiner** [Azure/azure-sdk-for-net#2303]
I get this exception when calling RoleAssignments.Create:

The api-version '2015-07-01' is invalid. The supported versions are '2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'

I am using version v2.4.2-preview of the package.

**Comment by markcowl** [comment]
@briansteiner Is this call being made against Azure or against a national cloud?  Can you provide the request/response in this case ( the logging modules here https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Etw/2.1.1-preview
https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Log4Net/2.1.1-preview
 should help with getting logs)

**Comment by markcowl** [comment]
@shuagarw can you take a look?

**Comment by shuagarw** [comment]
@rbacAsk @rashidqureshi for FYI
@briansteiner Please provide the command you are using to create role assignment. This error can be misleading. I have seen cases where this error is thrown on Powershell if its a permission issue.
Also, check the user creating RoleAssignment has write permissions on Microsoft.Authorization (i.e. either the user is a classicAdmin or has roleAssignment to some role which gives this permission.)

**Comment by briansteiner** [comment]
Here is the method I use to make the call:

`public void CreateResourceRoleAssignment(string subscriptionId, string resource, string role, string principalId, string Transaction)
        {
            Log(MethodBase.GetCurrentMethod(), "Creating the role assignment...", Transaction);

            var credential = GetAzureManagementCredential();

            var handler = new HttpClientHandler()
            {
                Proxy = new WebProxy(Proxy),
                UseProxy = UseProxy
            };

            var authorizationManagementClient = new AuthorizationManagementClient(credential, handler, null);
            authorizationManagementClient.SubscriptionId = subscriptionId;

            var result = authorizationManagementClient.RoleAssignments.Create(
                String.Format("/subscriptions/{0}/{1}", subscriptionId, resource),
                role,
                new RoleAssignmentProperties { PrincipalId = principalId }
                );
        }`

**Comment by briansteiner** [comment]
The call is being made against an Azure subscription with a client that has owner level permissions at the subscription level.

**Comment by shuagarw** [comment]
The scope to which you are creating the roleAssignment looks wrong. It should be in following pattern- /subscriptions/<subId>/resourceGroups/<RGName>/providers/<RPName>/<resourceName>

For e.g. 
This will assign role to the particular resource.
/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/resourceGroups/Shubham_TestRG/providers/Microsof.Storage/storageAccounts/shubhamstorage12345

If you want to assign a role to a ResourceGroup, scope would looks something like this - 
/subscriptions/4004a9fd-d58e-48dc-aeb2-4a4aec58606f/resourceGroups/Shubham_TestRG

Please check the value of resource in your method and conform it to the above pattern.

**Comment by briansteiner** [comment]
Thanks I seem to be getting farther now.  What value should be used for RoleAssignmentName in the Create method?  The method is now asking for a role definition ID in the form of a GUID.  How is that obtained say for the Owner role?

**Comment by shuagarw** [comment]
If it is asking for a Role *Assignment* Id , then it will be a new guid, as you are creating a new role assignment. When it asks for a Role Id, then it will the Guid of the role, which you can get by fetching the role by name.

Please refer to the code used by powershell cmdlets. The api contract might be a bit different as the version used is different but the data passed should be in the same format.

https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Resources/Commands.Resources/RoleAssignments/NewAzureRoleAssignmentCommand.cs#L170

https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/Resources/Commands.Resources/Models.Authorization/AuthorizationClient.cs#L155

**Comment by adrianhall** [comment]
This looks to be resolved, but was never closed.  Can you confirm this is no longer an issue?
