### ISSUE TITLE
[Synapse] test failing in nightly runs

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#23035]
Synapse nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 400 (Bad Request)
> 
> Content:
> {"code":"BadRequest","message":"Creating debug session failed: Not able to start cluster.","target":null,"details":null,"error":null}
> 
> Headers:
> Cache-Control: no-cache
> Pragma: no-cache
> Server: Microsoft-IIS/10.0,Microsoft-HTTPAPI/2.0
> Strict-Transport-Security: REDACTED
> x-ms-correlation-request-id: REDACTED
> X-Content-Type-Options: REDACTED
> X-Powered-By: REDACTED
> x-ms-request-id: a9ba5208-e202-4e71-a27f-b5b4d677530f
> x-ms-client-request-id: 18ac285d-6f2a-41fe-a568-8648083974ef
> Date: Thu, 01 Jul 2021 19:06:33 GMT
> Content-Length: 133
> Content-Type: application/json; charset=utf-8
> Expires: -1
> 
> 
> Stack trace
>    at Azure.Analytics.Synapse.Artifacts.DataFlowDebugSessionRestClient.DeleteDataFlowDebugSessionAsync(DeleteDataFlowDebugSessionRequest request, CancellationToken cancellationToken) in /_/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/DataFlowDebugSessionRestClient.cs:line 277
>    at Azure.Analytics.Synapse.Artifacts.DataFlowDebugSessionClient.DeleteDataFlowDebugSessionAsync(DeleteDataFlowDebugSessionRequest request, CancellationToken cancellationToken) in /_/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/DataFlowDebugSessionClient.cs:line 109
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 165
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.DisposableDataFlowDebugSession.DisposeAsync() in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.Artifacts\tests\DataFlowDebugSessionClientLiveTests.cs:line 51
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.QuerySessions() in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.Artifacts\tests\DataFlowDebugSessionClientLiveTests.cs:line 103
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.QuerySessions() in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.Artifacts\tests\DataFlowDebugSessionClientLiveTests.cs:line 103
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=977894&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Given the age of this issue, closing this as stale.  If tests are still failing, please file a new issue.

**Comment by annelo-msft** [comment]
@wonner, @pshao25 FYI.
