### ISSUE TITLE
[Synapse] test failing in nightly runs

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#23034]
Synapse nightly test runs are failing with:

> Error message
> System.ArgumentException : Expected: IEnumerable But was: null (Parameter 'actual')
> 
> 
> Stack trace
>    at NUnit.Framework.Internal.ConstraintUtils.RequireActual[T](Object actual, String paramName, Boolean allowNull)
>    at NUnit.Framework.Constraints.CollectionConstraint.ApplyTo[TActual](TActual actual)
>    at NUnit.Framework.Constraints.NotConstraint.ApplyTo[TActual](TActual actual)
>    at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
>    at NUnit.Framework.CollectionAssert.IsNotEmpty(IEnumerable collection, String message, Object[] args)
>    at NUnit.Framework.CollectionAssert.IsNotEmpty(IEnumerable collection)
>    at Azure.Analytics.Synapse.Monitoring.Tests.MonitoringClientLiveTests.TestListSparkApplications() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Monitoring/tests/MonitoringClientLiveTests.cs:line 43
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=977894&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=982106&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=983758&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=985054&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=987353&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=989706&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=991999&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=994406&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=996653&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=998602&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1000470&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1002095&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1004149&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1006246&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1009272&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1011963&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1014282&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1016844&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1019115&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1021293&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1023554&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1025725&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Given the age of this issue, closing this as stale.  If tests are still failing, please file a new issue.
