### ISSUE TITLE
[Azure.Identity] Explicitly selecting the managed identity source

### ISSUE THREAD

**Issue by mataness** [Azure/azure-sdk-for-net#23044]
In Azure.Identity NuGet, the implementation of ManagedIdentityCredential implicitly selecting the ManagedIdentitySource (e.g. IMDS, ServiceFabric).

In my scenario, we have both IMDS and ServiceFabric managed identities available for the process.
However, in some cases I want that my application will use ServiceFabricManagedIdentitySource and in some other cases I want to use the IMDS source.

Is it possible to add additional constructor to ManagedIdentityCredential that will force choosing the managed identity source?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
As a workaround, the IMDS endpoint host can now be configured via environment variable. 
https://github.com/Azure/azure-sdk-for-net/blob/72630d5bb04538967195c199632d8260133d25e5/sdk/identity/Azure.Identity/src/EnvironmentVariables.cs#L21

**Comment by mataness** [comment]
Not sure why it's close, overriding the environment variable is not a clean design. Why not exposing this functionality as a constructor parameter?

**Comment by christothes** [comment]
Hi @mataness - We'll consider this a feature request and monitor the issue to see if there is more demand for this feature.

**Comment by mataness** [comment]
If I want to contribute and submit a PR to support this functionality, will you allow it ?

**Comment by mataness** [comment]
> ManagedIdentityCredential

1. Defining a new enum: ManagedIdentitySource with the following values: AppService, CloudShell, AzureArc, ServiceFabric, TokenExchange, InstanceMetadataService
2. Add a new optional parameter to [ManagedIdentityCredential](https://github.com/Azure/azure-sdk-for-net/blob/33cfc7e84f7b5e38d59fa482370d3bc1e2cb98da/sdk/identity/Azure.Identity/src/ManagedIdentityCredential.cs) constructor - that enum (e.g. ManagedIdentitySource? identitySource = null)
3. The parameter value will be proagated from ManagedIdentityCredential to the underyling [ManagedIdentityClient](https://github.com/Azure/azure-sdk-for-net/blob/ec129c10c8492d3871ec6dde9b0b99bde80becdb/sdk/identity/Azure.Identity/src/ManagedIdentityClient.cs), when given, the [SelectManagedIdentitySource](https://github.com/Azure/azure-sdk-for-net/blob/ec129c10c8492d3871ec6dde9b0b99bde80becdb/sdk/identity/Azure.Identity/src/ManagedIdentityClient.cs) will use that source explicitly, if it fails to use that source - it will thrown an exception.

What do you think? should I go ahead and implement this ?
