### ISSUE TITLE
[BUG] Can not set PrefixMatch on ManagementPolicyFilter

### ISSUE THREAD

**Issue by blrchen** [Azure/azure-sdk-for-net#23051]
**Describe the bug**
Can not set PrefixMatch on ManagementPolicyFilter

**Expected behavior**
Able to set PrefixMatch on ManagementPolicyFilter, either via construction or public property

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Not able to set PrefixMatch on ManagementPolicyFilter, either via construction or public property. Please refer to following source code
```
public class ManagementPolicyFilter : IUtf8JsonSerializable
{
 public ManagementPolicyFilter(IEnumerable<string> blobTypes);
 public IList<string> PrefixMatch { get; }
}
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Use following code to create ManagementPolicyRule instance, failed can not set PrefixMatch 
```
    var rules = new List<ManagementPolicyRule>();
    var rule1 = new ManagementPolicyRule("DeleteLongerThan24Hours", RuleType.Lifecycle, 
        new ManagementPolicyDefinition(new ManagementPolicyAction {BaseBlob = new ManagementPolicyBaseBlob(){ Delete =new DateAfterModification(1)},})
        {
            Filters = new ManagementPolicyFilter(new List<string> { "blockBlob" })
            {
                PrefixMatch = new List<string> { "upload" }
            }
        });
    rules.Add(rule1);
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0]  azure.resourcemanager.storage 1.0.0-preview.2
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8] Windows 10, DotNet Core
 - IDE and version : [e.g. Visual Studio 16.3] VS version does not matter

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by blrchen** [comment]
Hello, is there any update?

**Comment by yungezz** [comment]
thanks for the inquiry. For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, existing Azure.ResourceManager.* SDKs has no plan to update now. They're subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks! cc @nickzhums

**Comment by ArcturusZhang** [comment]
Hi @blrchen please try this:
```
    var rules = new List<ManagementPolicyRule>();
    var rule1 = new ManagementPolicyRule("DeleteLongerThan24Hours", RuleType.Lifecycle, 
        new ManagementPolicyDefinition(new ManagementPolicyAction {BaseBlob = new ManagementPolicyBaseBlob(){ Delete =new DateAfterModification(1)},})
        {
            Filters = new ManagementPolicyFilter(new List<string> { "blockBlob" })
            {
                PrefixMatch = { "upload" }
            }
        });
    rules.Add(rule1);
```
Please note since the property `PrefixMatch` is unassignable, therefore you cannot construct a new list and assign to that property. The usage here is a C# grammar sugar of the collection initialization, check out more information here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-collection-read-only-property-initialization

**Comment by blrchen** [comment]
This works, thanks man.
