### ISSUE TITLE
Requesting the updated link info on the MicrosoftIdentityOptions.ClientCertificates Property document. There are 2 links having the same content updated on different dates.

### ISSUE THREAD

**Issue by DhivyaG19** [Azure/azure-sdk-for-net#23064]
This MicrosoftIdentityOptions.ClientCertificates Property [Document](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.microsoftidentityoptions.clientcertificates?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.Identity.Web.MicrosoftIdentityOptions.ClientCertificates);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet-preview) provides this "[Using Certificate](https://github.com/AzureAD/microsoft-identity-web/wiki/Using-certificates)" link - Jenny Ferries edited this page on Sep 21, 2020 · 30 revisions.

But there is an other Certificate link for the same page. : https://github.com/AzureAD/microsoft-identity-web/wiki/Certificates  -Jean-Marc Prieur edited this page on May 16 · 6 revisions

Please update the latest updated link for https://aka.ms/ms-id-web-certificates in the  MicrosoftIdentityOptions.ClientCertificates Property document to avoid confusion on which page is the updated and the latest one to follow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7f40ebd-8e67-91ba-c26d-561d497237ca
* Version Independent ID: 8ff69227-a066-0c61-326f-1a63ae64dfc5
* Content: [MicrosoftIdentityOptions.ClientCertificates Property (Microsoft.Identity.Web) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.microsoftidentityoptions.clientcertificates?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.Identity.Web.MicrosoftIdentityOptions.ClientCertificates);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Identity.Web/MicrosoftIdentityOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Web/MicrosoftIdentityOptions.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Identity.Web` package is maintained as [#1368](https://github.com/AzureAD/microsoft-identity-web/issues/1368).
