### ISSUE TITLE
[BUG] ServiceBusSessionProcessor reporting millions of SessionLockLost exceptions over time

### ISSUE THREAD

**Issue by EranGon** [Azure/azure-sdk-for-net#23065]
Our service consumes messages from Service Bus queues using message sessions.
We are running in Azure using multiple deployments (and multiple instances) reading from the same queue. 
We've noticed that from time to time, our service gets TONS of SessionLockLost exceptions while trying to read from the queue.  TONS being over a million exceptions at a time in 10-20 minutes periods.

Trying to dig a bit into the ServiceBusSessionProcessor and receiver code it seems that although we check and throw if the session's lock was lost - this error is not handled. I would have expected the processor to catch this exception and dispose of the receiver in order to start handling a new session. 

Other then this being a telemetry noise, it's a waste of processor time.
We are using Azure.Messaging.ServiceBus NuGet version 7.2.0
The exception's stack trace:
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ThrowIfSessionLockLost()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<ReceiveMessagesAsyncInternal>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<ReceiveMessagesAsync>b__38_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<ReceiveMessagesAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<ReceiveMessagesAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.SessionReceiverManager.<ReceiveAndProcessMessagesAsync>d__21.MoveNext()

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @EranGon,
The session lock being lost is not an expected scenario in most cases. It may be that the connection is being dropped intermittently by the service and causing this. Can you tell us how many concurrent sessions you are attempting to read from? In general, you should only get 1 exception per session where the lock is lost.

**Comment by JoshLove-msft** [comment]
> Trying to dig a bit into the ServiceBusSessionProcessor and receiver code it seems that although we check and throw if the session's lock was lost - this error is not handled. I would have expected the processor to catch this exception and dispose of the receiver in order to start handling a new session.

The exception is caught but it is also logged as an error.

**Comment by EranGon** [comment]
@JoshLove-msft we are reading from 12 concurrent sessions.
To be clear on what we experience

1. The session lock lost issue is no infrequent - we're getting a few thousands of those every week (running in a massive scale service with dozens of nodes)
2. When we do encounter it, we get over a million errors at a time (all reported through the ProcessErrorAsync event in ServiceBusSessionProcessor) with the exact same message. For example: 
_The session lock has expired on the MessageSession. Accept a new MessageSession. TrackingId:1ad509100000000f000d5da761051853_G0_B29, SystemTracker:XXXXXXX, Timestamp:2021-07-31T09:32:59 (SessionLockLost)_

**Comment by JoshLove-msft** [comment]
Thanks for the clarification. I assumed that this was coming from the SDK logs and not actually hitting the user error handler. It does seem like there is a bug here.
Would you be able to provide the ServiceBusSessionProcessorOptions that you are using to help track down the issue?

**Comment by JoshLove-msft** [comment]
It would also be helpful if you have the ErrorSource from the ProcessErrorEventArgs.

**Comment by EranGon** [comment]
So:
Yes - the stack trace is the full stack trace
ErrorSource == Receive
```
new ServiceBusSessionProcessorOptions
{
  MaxConcurrentSessions = 12,
  SessionIdleTimeout = TimeSpan.FromSeconds(120),
  AutoCompleteMessages = false,
  MaxAutoLockRenewalDuration = TimeSpan.FromSeconds(240 * 5)
}
```

**Comment by JoshLove-msft** [comment]
You are using 7.2.0 or 7.2.1? Has this just started happening recently?

**Comment by JoshLove-msft** [comment]
> When we do encounter it, we get over a million errors at a time (all reported through the ProcessErrorAsync event in ServiceBusSessionProcessor) with the exact same message. For example:
The session lock has expired on the MessageSession. Accept a new MessageSession. TrackingId:1ad509100000000f000d5da761051853_G0_B29, SystemTracker:XXXXXXX, Timestamp:2021-07-31T09:32:59 (SessionLockLost)

Are you able to log the SessionId here from the EventArgs? Is it logging the same session over and over or is different each time?

>The session lock lost issue is no infrequent - we're getting a few thousands of those every week (running in a massive scale service with dozens of nodes)

Do you mean this is happening for thousands of sessions, and then for each session you are getting thousands of logs?

**Comment by EranGon** [comment]
> You are using 7.2.0 or 7.2.1? Has this just started happening recently?

We are using 7.2.0. This has just started happening recently, but we've just recently upgraded from version 4.1.3 so it might be related



> > When we do encounter it, we get over a million errors at a time (all reported through the ProcessErrorAsync event in ServiceBusSessionProcessor) with the exact same message. For example:
> > The session lock has expired on the MessageSession. Accept a new MessageSession. TrackingId:1ad509100000000f000d5da761051853_G0_B29, SystemTracker:XXXXXXX, Timestamp:2021-07-31T09:32:59 (SessionLockLost)
> 
> Are you able to log the SessionId here from the EventArgs? Is it logging the same session over and over or is different each time?

We don't log the SessionId specifically, but all of these errors arrive with the exact SystemTracer if that helps
 
> > The session lock lost issue is no infrequent - we're getting a few thousands of those every week (running in a massive scale service with dozens of nodes)
> 
> Do you mean this is happening for thousands of sessions, and then for each session you are getting thousands of logs?

This is happening for thousands of sessions, and then for each session we are getting **over a million** of logs

**Comment by JoshLove-msft** [comment]
I haven't been able to repro this, have you still been seeing this issue?

**Comment by EranGon** [comment]
We are not seeing this since I've changed our telemetry code to not emit telemetry in these cases - it cluttered our telemetry for no good reason.
From my understanding, the problem is [here](https://github.com/Azure/azure-sdk-for-net/blob/76e66c801a24ae2334707fd29956714ebe510f89/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L278) - when calling the ReceiveMessagesAsync() we don't catch and handle the session lock lost exception. We should catch it and dispose of that receiver since we don't have a lock on that session anymore.

**Comment by JoshLove-msft** [comment]
We do cancel our cancellationTokenSource when we get a SessionLockLost - https://github.com/Azure/azure-sdk-for-net/blob/76e66c801a24ae2334707fd29956714ebe510f89/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L313

**Comment by JoshLove-msft** [comment]
Since, we can't repro the issue, I will close it for now. Feel free to reopen if you are able to repro.
