### ISSUE TITLE
[BUG] SDK generate PS still use swagger from the "master" branch, while swagger already changed to use "main" branch

### ISSUE THREAD

**Issue by shawnxzq** [Azure/azure-sdk-for-net#23067]
**Describe the bug**
Please provide the description of issue you're seeing.
SDK generation tool still uses swagger from master branch to generate SDK.

**Expected behavior**
What is the expected behavior?
SDK generation tool should use the latest swagger from main branch since swagger repo already changed to use it instead of the original master branch.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

SDK generation tool still uses swagger from master branch to generate SDK.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

N/A

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
Currently, swagger repo has a daily sync from main branch to master branch, so you're likely to get the latest SDK if you wait for one day. But the sync will stop at the end of August, @AlexanderSher can plan to solve this issue before that?

**Comment by fengzhou-msft** [comment]
A fix PR is submitted: https://github.com/Azure/azure-sdk-tools/pull/1928

**Comment by HarveyLink** [comment]
Hi @shawnxzq, this issue is resloved. Could you please pull the lasted code and run 
`dotnet msbuild eng/mgmt.proj /t:Util /p:UtilityName=InstallPsModules` 
This will update the script and unblock you.

**Comment by shawnxzq** [comment]
Thanks for the update!
