### ISSUE TITLE
[FEATURE REQ] AuthorizationCodeCredential should support a client certifcate as an alternative to client secret

### ISSUE THREAD

**Issue by jasonjoh** [Azure/azure-sdk-for-net#23079]
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
Currently AuthorizationCodeCredential only supports using a client secret. Auth code redemption can also be done [using a client certificate](https://docs.microsoft.com/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-access-token-with-a-certificate-credential), which is the more secure option.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
We have no current plans to add this functionality, but will monitor this issue to gauge additional interest.
