### ISSUE TITLE
Check if StorageInputType needs to be in TranslationSource or in DocumentTranslationInput

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#23084]
The reason why it is in `DocumentTranslationInput` is that both `source` and `target` had to have the same `storageInput`. I believe the service updated their behavior and this is no longer required, but need to double-check.

If it is no longer needed for a target too, we should move the `DocumentTranslationInput.Storagetype` property to the `TranslationSource` type

**Comment by ZulaMostafa** [comment]
It's true now that `source` and `target` can have different `storageInput`. But I don't get why should we move the property to `TranslationSource`, shouldn't the target have a `StorageType` too?

**Comment by maririos** [comment]
Ohh interesting. So looking at the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/TranslatorText/stable/v1.0/TranslatorBatch.json#L1076), StorageType seems to be independent of source or target (which is how we have it in the library).
How will a request work in order to say source is folder, and target is file? or the opposite, source is file and target is folder?

Something that could help will be to have a table with the 4 possible combinations and see which cases it works, which casses don't work, and try to send those requests with Postman and see what you get

**Comment by ZulaMostafa** [comment]
Let's have a look into the interesting results, I've tested all the combinations using both Postman and the actual SDK.

Case 1: 
Source: Folder
Target: Folder 
Status: Succeeds

Case 2: 
Source: File
Target: Folder 
Status: Succeeds only if the `StorageType` is specified as `File`.

Case 3: 
Source: File
Target: File
Status: Succeeds only if the `StorageType` is specified as `File`. 
There is one more comment about this case, it works only if the target is a container with adding filename at the end of the path in the URL. If the target is a blob Postman responds with Ok status but the file never changes. and for the SDK, that was the error I got: 
Cannot access target document location with the current permissions.
Status: 200 (OK)
ErrorCode: InvalidTargetDocumentAccessLevel

Case 4:
Source: Folder
Target: File
Status: Fails. 
When I use a container as the target with adding the file name at the end of the path it creates a new folder. And when i use a blob it's just the same as the previous case.

I think we need to move `StorageType` property to `TranslationSource`. I had to specify the type only if the source was `File`. Regarding the permissions issue, I'm not sure if I've done something wrong but the permissions given to the blob was read and write.

**Comment by maririos** [comment]
This is great @ZulaMostafa . I agree with you that it seems like we can move the `SotrageType` property into `TranslationSource`. 
There is a concern and is that the service could decide to change this in the future and we will have to add extra logic to see how we reconcile.
Let's ask the service team and get their opinion.

**Comment by maririos** [comment]
The service team didn't see a reason to move it, especially since the service already GAd this way. The fear is that in the future this property applies equally to both source and target and if we move it in the SDK to only source, it will be harder to reconcile.

Decision in SDK: leave as is
