### ISSUE TITLE
[BUG] Using FileStreamResult with client side encrypted blobs, results in never ending download

### ISSUE THREAD

**Issue by januszj** [Azure/azure-sdk-for-net#23096]
**Describe the bug**
When using FileStreamResult with encrypted blob stream reported Length of stream is of the encrypted blob and not decrypted one. This results browser waiting for missing bytes reported by FileStreamResult and download fails.

**Expected behavior**
Client side encrypted blob stream should report decrypted size.

**Actual behavior**
When trying to download in browser it will first try to download missing bytes and then download will time out and fail

**To Reproduce**
Here is sample Azure function:

```csharp
[FunctionName("Download")]
        public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
            ILogger log)
        {
            string name = req.Query["name"];

            string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
            dynamic data = JsonConvert.DeserializeObject(requestBody);
            name ??= data?.name;

            string storageConnectionString = Environment.GetEnvironmentVariable("CONNECTION_BLOB");
            BlobClientOptions options = await Helper.GetOptions(); 

            BlobClient blob = new BlobServiceClient(storageConnectionString, options)
                .GetBlobContainerClient("encrypted")
                .GetBlobClient(name);

            var blobStream = await blob.OpenReadAsync();

            return new FileStreamResult(blobStream, "application/octet-stream")
            {
                FileDownloadName = name,
            };
        }
```

```csharp
        public static async Task<BlobClientOptions> GetOptions()
        {
            string tenantId = Environment.GetEnvironmentVariable("tenantId");
            string clientId = Environment.GetEnvironmentVariable("clientId");
            string clientSecret = Environment.GetEnvironmentVariable("clientSecret");
            string vaultName = Environment.GetEnvironmentVariable("vaultName");
            string keyName = Environment.GetEnvironmentVariable("keyName");


            ClientSecretCredential cred = new ClientSecretCredential(tenantId, clientId, clientSecret);
            var vaultUri = new Uri($"https://{vaultName}.vault.azure.net/");
            KeyClient keyClient = new KeyClient(vaultUri, cred);

            KeyVaultKey rasKey = await keyClient.GetKeyAsync(keyName);
            IKeyEncryptionKey key = new CryptographyClient(rasKey.Id, cred);
            IKeyEncryptionKeyResolver keyResolver = new KeyResolver(cred);

            ClientSideEncryptionOptions encryptionOptions = new ClientSideEncryptionOptions(ClientSideEncryptionVersion.V1_0)
            {
                KeyEncryptionKey = key,
                KeyResolver = keyResolver,
                KeyWrapAlgorithm = "RSA1_5"
            };
            BlobClientOptions options = new SpecializedBlobClientOptions() { ClientSideEncryption = encryptionOptions };
            return options;
        }
```

**Environment:**
 - Azure.Storage.Blobs 12.9.1
 -  Azure.Security.KeyVault.Keys  4.2.0
 - Azure.Identity 1.4.0
 - Microsoft.Azure.WebJobs.Extensions.Storage 4.0.4
 - Microsoft.NET.Sdk.Functions 3.0.13
 - Azure AppService Core 3.1 Azure Functions
 - Visual Studio 2019

**Comment by amishra-dev** [comment]
@jaschrep-msft can you please look at this?

**Comment by jaschrep-msft** [comment]
In general, unless you need to seek through your stream at will or a known `Length` is critical, `DownloadStreaming()` is likely a far better option for you than `OpenRead()`. Code that is dependent on a stream's Length parameter will have a tough time with `OpenRead()` as the returned stream is designed to resize its length to accommodate blobs that are updating underneath you (assuming you've disabled ETag locking).

Even with etag locking enabled, reading using client-side decryption will still result in a changing stream length, as it's impossible to know the length of the plaintext until decryption is finished, which is impossible until the stream is fully consumed.

From an initial glance, it looks like our stream implementation does not accommodate the final read being shorter than expected, but even patching that may not be enough. I can't speak to the implementation details of `FileStreamResult` but if it can't handle a resizing stream at the very end then this route is doomed no matter what.

I would encourage you to see if `FileStreamResult` can handle a lengthless stream and to use `DownloadStreaming()` if that is the case. You will get a more efficient read and avoid the problem entirely.

If length/seekability is a requirement, I would encourage you to test whether `FileStreamResult` can handle a stream that gets shorter as you hit the final Read() call. If it cannot, then even a bug fix from us will not help you.

**Comment by januszj** [comment]
Thanks, after changing to:
```csharp
            var response = await blob.DownloadStreamingAsync();

            return new FileStreamResult(response.Value.Content, "application/octet-stream")
            {
                FileDownloadName = name,
            };
```
download works fine in browser. It does not report size so it just downloads util finished, but it works perfectly.

One more question. Is the download from blob this way limited in speed ? I always got max of 500 kB/s...

**Comment by jaschrep-msft** [comment]
It should not be limited unless the account you are downloading from is being throttled due to excessive traffic. If anything, I'd expect this method to be faster than OpenRead, as open read downloads a single section (4MB default), buffers it, then lets you read from that buffer, fetching a new buffer when you attempt to read from a stream position that is not buffered. This API just makes a single GET request to the service and gets the whole blob content as the HTTP response body.

You are likely experiencing something else in your environment that is limiting your speeds.

**Comment by januszj** [comment]
Thanks a lot James, I will check the reasons for low speed in environment. Reported issue is resolved.
