### ISSUE TITLE
[QUERY] Azure.Identity Multi-tenancy Support?

### ISSUE THREAD

**Issue by bdschaap** [Azure/azure-sdk-for-net#23094]
**Query/Question**
Does Azure.Identity support multi-tenancy and if not is there a timeline for when it will support it?

I'm trying to use one app registration associated with two service principals.  The service principals are in two different AAD tenants.  I'm also using AAD Pod Identity on Kubernetes to support Managed Identity credentials.  When I try to use this configuration I'm running into an issue with Azure.Identity.  The authentication response I receive contains two access tokens in a JSON array of objects.  However, Azure.Identity expects a single JSON object and throws an exception.  I'm trying to narrow down whether the problem is in Azure.Identity or AAD Pod Identity.  I initially reported an [issue to AAD Pod Identity](https://github.com/Azure/aad-pod-identity/issues/1120) but they seem to indicate that Azure.Identity may not have the concept of multi-tenancy.  

**Environment:**
 - Name and version of the Library package used: _Azure.Identity 1.3.0_
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): _.NET Core 3.1 on Kubernetes / Linux_
**dotnet --info output**
```
Host (useful for support):
  Version: 3.1.17
  Commit:  3a75b805fa

.NET Core SDKs installed:
  No SDKs were found.

.NET Core runtimes installed:
  Microsoft.NETCore.App 3.1.17 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```
 - IDE and version : Visual Studio 16.9.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
This is supported in the latest version of Azure.Identity. The `TokenRequestContext` passed to `GetToken` now accepts a `TenantId` property which can be supplied as a hint in multi-tenant scenarios. Note we do not support the concept of multiple tokens.
