### ISSUE TITLE
[BUG] Infinite ServiceBus retry loop in Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0-beta.5

### ISSUE THREAD

**Issue by erwinkramer** [Azure/azure-sdk-for-net#23102]
**Describe the bug**
When using Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0-beta.5 messages will keep retrying indefinitely .

**Expected behavior**
Messages going to the deadletter queue. 

**Actual behavior (include Exception or Stack Trace)**
Let's see the host config when the Azure Function boots, there is a maxRetryCount of 2:
```
[2021-08-04T16:46:12.832Z] Host configuration file read:
[2021-08-04T16:46:12.833Z] {
[2021-08-04T16:46:12.834Z]   "version": "2.0",
[2021-08-04T16:46:12.840Z]   "retry": {
[2021-08-04T16:46:12.841Z]     "delayInterval": "00:00:03",
[2021-08-04T16:46:12.842Z]     "maxRetryCount": 2,
[2021-08-04T16:46:12.862Z]     "strategy": "fixedDelay"
[2021-08-04T16:46:12.864Z]   },
[2021-08-04T16:46:12.865Z]   "logging": {
[2021-08-04T16:46:12.866Z]     "logLevel": {
[2021-08-04T16:46:12.868Z]       "default": "Information"
[2021-08-04T16:46:12.873Z]     },
[2021-08-04T16:46:12.900Z]     "applicationInsights": {
[2021-08-04T16:46:12.902Z]       "samplingSettings": {
[2021-08-04T16:46:12.903Z]         "isEnabled": true,
[2021-08-04T16:46:12.905Z]         "excludedTypes": "Dependency;Event;Request"
[2021-08-04T16:46:12.906Z]       }
[2021-08-04T16:46:12.907Z]     }
[2021-08-04T16:46:12.923Z]   }
[2021-08-04T16:46:12.925Z] }
```
...and the servicebus retries, that's 2 as well:
```
[2021-08-04T16:46:14.307Z] ServiceBusOptions
[2021-08-04T16:46:14.310Z] {
[2021-08-04T16:46:14.313Z]   "ClientRetryOptions": {
[2021-08-04T16:46:14.315Z]     "Mode": "Exponential",
[2021-08-04T16:46:14.317Z]     "TryTimeout": "00:01:00",
[2021-08-04T16:46:14.318Z]     "Delay": "00:00:00.8000000",
[2021-08-04T16:46:14.320Z]     "MaxDelay": "00:02:00",
[2021-08-04T16:46:14.324Z]     "MaxRetries": 2
[2021-08-04T16:46:14.326Z]   },
[2021-08-04T16:46:14.327Z]   "TransportType": "AmqpTcp",
[2021-08-04T16:46:14.329Z]   "WebProxy": "",
[2021-08-04T16:46:14.331Z]   "AutoCompleteMessages": true,
[2021-08-04T16:46:14.332Z]   "PrefetchCount": 0,
[2021-08-04T16:46:14.336Z]   "MaxAutoLockRenewalDuration": "00:05:00",
[2021-08-04T16:46:14.338Z]   "MaxConcurrentCalls": 50,
[2021-08-04T16:46:14.339Z]   "MaxConcurrentSessions": 8,
[2021-08-04T16:46:14.340Z]   "MaxMessageBatchSize": 1000,
[2021-08-04T16:46:14.341Z]   "SessionIdleTimeout": "00:01:00"
[2021-08-04T16:46:14.344Z] }
```

My binding looks like this, from queue-A to queue-B, I've put a function scoped retry count to 2: 
```
 [FunctionName("LoopyLoop")]
        [ExponentialBackoffRetry(2, "00:00:04", "00:15:00")]
        public static async Task Run(
            [ServiceBusTrigger("queue-A", Connection = "some-user-assigned-id")] ServiceBusReceivedMessage myQueueItem, ServiceBusMessageActions messageActions, 
            [ServiceBus("queue-B", Connection = "some-user-assigned-id")] ServiceBusSender sender, ILogger log)
        {
```

If I understand correctly, for retries: the host setting will be overridden by the function setting, which is 2, and the servicebus setting is 2, which makes a total of (2*2) 4 attempts at most.  I created a settlement, this always gets hit (with a hard coded throw exception) : 
```
  var count = myQueueItem.DeliveryCount;
            if(count > 30)
            {
                await messageActions.DeadLetterMessageAsync(myQueueItem, "Things that grind your gears", "Infinite Retries");
                return;
            }
```

As you see, it gets hit at attempt 31.  This is the only way my Function can stop the retry loop. Without this, it will keep going.

**To Reproduce**
1. Create a SB Premium instance
2. Create a SB triggered function that will send to another queue, and keep retrying by hard coding an exception...

**Environment:**
 - Windows locally or inside the Azure host, same behavior in both.

Libraries: 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <PackageReference Include="Azure.Storage.Blobs" Version="12.9.1" />
    <PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="1.0.8" />
    <PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.27" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.12" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.0.0-beta.5" />
    <PackageReference Include="Microsoft.Graph" Version="3.20.0" />
    <PackageReference Include="Microsoft.Graph.Auth" Version="1.0.0-preview.5" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.35.1" />
    <PackageReference Include="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="6.12.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="4.7.0" />
  </ItemGroup>
  <ItemGroup>
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
//fyi:  @pakrym

**Comment by JoshLove-msft** [comment]
Hi @erwinkramer,
So are you essentially throwing an exception after that if block in your function? This would cause the message to be abandoned and redelivered to your function. So it isn't that the retry policy is retrying your function, it is the fact that the message has not been completed, so it is available to be redelivered over and over again until it is deadlettered.

**Comment by erwinkramer** [comment]
@JoshLove-msft 
> Hi @erwinkramer,
> So are you essentially throwing an exception after that if block in your function? This would cause the message to be abandoned and redelivered to your function (evidenced by the DeliveryCount incrementing each time - which is set by the service). So it isn't that the retry policy is retrying your function, it is the fact that the message has not been completed, so it is available to be redelivered over and over again until it is deadlettered.
> 
> I believe things are working as expected here, but let me know if I am misunderstanding.
 
Yes I'm throwing an exception after checking the delivery count. 

The behavior is different from the stable version. There, when you throw exceptions, it would eventually go into the dead letter queue. I only refactored my code in a minimal way to work with the beta version. 

Are you telling me I have to complete the message somehow, even though the whole deal is not being able to complete it because an (on purpose) error occured. Please show me how completing looks like in a fault scenario... where it would force the actual retry policy.

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft
> 
> > Hi @erwinkramer,
> > So are you essentially throwing an exception after that if block in your function? This would cause the message to be abandoned and redelivered to your function (evidenced by the DeliveryCount incrementing each time - which is set by the service). So it isn't that the retry policy is retrying your function, it is the fact that the message has not been completed, so it is available to be redelivered over and over again until it is deadlettered.
> > I believe things are working as expected here, but let me know if I am misunderstanding.
> 
> Yes I'm throwing an exception after checking the delivery count.
> 
> The behavior is different from the stable version. There, when you throw exceptions, it would eventually go into the dead letter queue. I only refactored my code in a minimal way to work with the beta version.
> 
> Are you telling me I have to complete the message somehow, even though the whole deal is not being able to complete it because an (on purpose) error occured. Please show me how completing looks like in a fault scenario... where it would force the actual retry policy.

Moving a message to the deadletter queue is done by the service, once the delivery count exceeds the threshold you've set for your queue (by default it is 10). Can you confirm what the threshold is for your queue?

**Comment by erwinkramer** [comment]
> > @JoshLove-msft
> > > Hi @erwinkramer,
> > > So are you essentially throwing an exception after that if block in your function? This would cause the message to be abandoned and redelivered to your function (evidenced by the DeliveryCount incrementing each time - which is set by the service). So it isn't that the retry policy is retrying your function, it is the fact that the message has not been completed, so it is available to be redelivered over and over again until it is deadlettered.
> > > I believe things are working as expected here, but let me know if I am misunderstanding.
> > 
> > 
> > Yes I'm throwing an exception after checking the delivery count.
> > The behavior is different from the stable version. There, when you throw exceptions, it would eventually go into the dead letter queue. I only refactored my code in a minimal way to work with the beta version.
> > Are you telling me I have to complete the message somehow, even though the whole deal is not being able to complete it because an (on purpose) error occured. Please show me how completing looks like in a fault scenario... where it would force the actual retry policy.
> 
> Moving a message to the deadletter queue is done by the service, once the delivery count exceeds the threshold you've set for your queue (by default it is 10). Can you confirm what the threshold is for your queue?

That must be part of the problem I will let you know tomorrow. 

Does that mean the retry functionality in Functions have no use in this scenario? (SB to SB) Because once service bus thinks it's over and sends it to the deadletter queued, there isn't much to retry in a Function. I would have thought there is retrying based on Functions logic first, and when that's over it should see it as a failed delivery by incrementing the delivery count based on SB logic.

**Comment by JoshLove-msft** [comment]
> Does that mean the retry functionality in Functions have no use in this scenario?

The Service Bus SDK has retries internally for transient errors. The functions retry policy is more for retrying errors that may be retriable within your function. So if there is some other transient error that is not related to the Service Bus SDK, it can still be useful.

**Comment by JoshLove-msft** [comment]
Yes, in this case, but I was speaking in general about when the Functions retry functionality can be useful.

**Comment by erwinkramer** [comment]
> Yes, in this case, but I was speaking in general about when the Functions retry functionality can be useful.

I guess that clears it up. Feels like some missed opportunities to merge retry behaviors from these 2 products IMO.

**Comment by JoshLove-msft** [comment]
We are planning to make the retry behavior smarter so that function retry doesn't happen if the error is not retriable - https://github.com/Azure/azure-sdk-for-net/issues/20177

**Comment by erwinkramer** [comment]
Looks like some nice progress. 

Looking further into the locking issues, it seems like the functions retry can actually cause some harm right now with SB. So it's best to remove it all together? And that would mean I cannot enable it on a global state in the host.json as well?  (In the retry root element)

**Comment by JoshLove-msft** [comment]
Right now, the way it interacts with the SB SDK is not ideal, so I would agree it would be best to not use it for SB functions until we address the linked issue. 

> And that would mean I cannot enable it on a global state in the host.json as well? (In the retry root element)

That is my understanding - you would have to enable it in each function that you want it in instead.

**Comment by erwinkramer** [comment]
> Right now, the way it interacts with the SB SDK is not ideal, so I would agree it would be best to not use it for SB functions until we address the linked issue.
> 
> > And that would mean I cannot enable it on a global state in the host.json as well? (In the retry root element)
> 
> That is my understanding - you would have to enable it in each function that you want it in instead.

Gotcha. 

Right now, this doc part doesn't make any sense anymore then ; https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp#using-retry-support-on-top-of-trigger-resilience . It explicitly states that there are function retries before SB delivery increments.

**Comment by JoshLove-msft** [comment]
I may have not been clear in my previous explanation. The function does retry on top of the SB retries. The delivery count corresponds to how many times a message has been received from the queue - the function retrying will not cause the delivery count to be incremented. The delivery count is only incremented after the function retry is finished and the trigger attempts to receive the message again.

**Comment by erwinkramer** [comment]
@JoshLove-msft thanks for all your comments. I've checked by DeliveryCount on the queue itself and it was way too high, I've set it to 10 and it works as expected. Not an issue caused by the beta package after all. 

Since we talked about so many different types of retries, I went ahead and made a table to breakdown the different configurations and their effect on Service Bus behavior. Does it make sense? 

| Retry configuration | Function retry  | Function ServiceBus SDK retry | ServiceBus retry |
| ------------- | ------------- | ------------- |------------- |
| **Where to configure** | Function Retry policies as decoration for a single Function, or at the retry element in Function settings | extensions:serviceBus:clientRetryOptions element in Function settings | DeliveryCount on a queue |
| **In effect when** | Transient errors caused by the function runtime | Transient errors caused by the servicebus 'client' SDK  when sending a message or when receiving from a ServiceBus trigger  | Unhandled exceptions inside the Run() of a function with a ServiceBus trigger |
| **Compatible with ServiceBus triggers** | Not at the moment  | Yes | Yes  |
| **Can increment the SB DeliveryCount on retry** | Maybe?  | No | Yes  |

**Comment by JoshLove-msft** [comment]
I think there are really only two categories of retry - Function level, and Service Bus SDK level. You can kind of think of the incremented delivery count as the service retrying, but let's treat that separately.

The function level retry is configured by adding the retry attribute or in the function settings as you mention. The function retry kicks in when your function has an unhandled exception.

The Service Bus SDK retries are configured as you show in the table. These retries occur when any transient error occurs while the trigger is attempting to receive messages and deliver them to your function, or when you interact with any of the SDK types from within your function, e.g. ServiceBusMessageActions/ServiceBusSender/etc.

Now, imagine that you have retries configured at both levels - once the SDK retries are exhausted, the function retries would kick in so you end up multiplying the max retries from both levels. On the other hand, if an error occurs from the SDK that is NOT retriable, such as the message lock being lost when attempting to complete the message, the function retry logic will still kick in even though the SDK knew not to retry. This is what we are planning on fixing in the future, and why I said using both together does not work great right now.

I think of function level retries as being most useful when you have logic that is outside of the Service Bus SDK actions that may need to be retried. If you are only concerned about retrying SDK operations, it is not really needed.

Now let's get to the delivery count. The delivery count of a message is incremented by the service every time it delivers the message to a receiver. So when the trigger receives a message and delivers it to your function, the delivery count is 1. If your function doesn't complete it, the message remains in the queue. The next time the trigger receives the message, the delivery count would be 2. The function and Service Bus SDK retries will not generally cause the delivery count to be incremented - if while receiving a message, there is a transient error, the receive will be retried but the message should still have a delivery count of 1 when it is received as it was only actually delivered once. The reason the delivery count gets incremented is that the trigger just continually receives messages in a loop, so it will eventually get the same message again if you don't complete it in your function.
