### ISSUE TITLE
[BUG] BlobBaseClient.OpenReadAsync and BlobBaseClient.OpenRead producing IOE: Response Content-Length mismatch: too few bytes written (3692 of 3696).

### ISSUE THREAD

**Issue by yotkoKanchev** [Azure/azure-sdk-for-net#23128]
**Describe the bug**
Recently replaced BlobBaseClient.DownloadToAsync with OpenReadAsync as I needed to, and after I'm getting the stream I'm trying to create a File from it

**Expected behavior**
to pass the full content

**To Reproduce**

var blobStream = await blob.OpenReadAsync();
/same thing with var blobStream = await blob.OpenReadAsync(0, 1024); and when used OpenRead();/
return File(blobStream, "application/octet-stream", "file-name");

**Environment:**
used Azure.Storage.Blobs 12.9.0

**Comment by amnguye** [comment]
Have you tried converting the stream to something like a `MemoryStream` in order to mitigate the issue?

Also I'm having trouble with your repro, I'm confused how you got to return a static type like File, since it's meant to just provide static methods. 
https://docs.microsoft.com/en-us/dotnet/api/system.io.file?view=net-5.0

**Comment by yotkoKanchev** [comment]
> Have you tried converting the stream to something like a `MemoryStream` in order to mitigate the issue?
> 
> Also I'm having trouble with your repro, I'm confused how you got to return a static type like File, since it's meant to just provide static methods.
> https://docs.microsoft.com/en-us/dotnet/api/system.io.file?view=net-5.0

**Comment by yotkoKanchev** [comment]
Sorry closed it by mistake :(

**Comment by amishra-dev** [comment]
@seanmcc-msft / @amnguye can you please look

**Comment by yotkoKanchev** [comment]
Any updates here?

**Comment by amishra-dev** [comment]
@amnguye ?
