### ISSUE TITLE
[Form Recognizer] The given key 'Contact' was not present in the dictionary.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-sdk-for-net#23123]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

### Error Description:
Task `StartRecognizeCustomFormsWithLabelsCanParseMultipageForm` failed in [pipeline weekly-test](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1018418&view=logs&j=c7de73c1-1fa3-5f12-91c3-9e3a0d31061f&t=33bf5cdb-a707-561f-8a41-a824e21c1a5c&l=7078) on `UsGov`. The error message as follow:

```
  Error Message:
   System.Collections.Generic.KeyNotFoundException : The given key 'Contact' was not present in the dictionary.
  Stack Trace:
     at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Azure.AI.FormRecognizer.Tests.RecognizeCustomFormsLiveTests.StartRecognizeCustomFormsWithLabelsCanParseMultipageForm(Boolean useStream) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/RecognizeCustomFormsLiveTests.cs:line 210
   at Azure.AI.FormRecognizer.Tests.RecognizeCustomFormsLiveTests.StartRecognizeCustomFormsWithLabelsCanParseMultipageForm(Boolean useStream) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/RecognizeCustomFormsLiveTests.cs:line 217
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
  Standard Output Messages:
 [09:46:35.132] Request daecd95c-2c54-4c05-aea8-7b956e98083e
   method: POST
   uri: ***/formrecognizer/v2.0/custom/models
   headers: 
     Accept:application/json
     x-ms-client-request-id:daecd95c-2c54-4c05-aea8-7b956e98083e
     x-ms-return-client-request-id:true
     User-Agent:azsdk-net-AI.FormRecognizer/3.2.0-alpha.20210727.1,(.NET Core 3.1.17; Linux 5.8.0-1039-azure #42~20.04.1-Ubuntu SMP Thu Jul 15 14:11:07 UTC 2021)
     Ocp-Apim-Subscription-Key:REDACTED
     Content-Type:application/json
   clientAssembly: Azure.AI.FormRecognizer
```
### Error Track:
Detail: [Code Link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/RecognizeCustomFormsLiveTests.cs#L174-L228)
![image](https://user-images.githubusercontent.com/81678720/128283477-915eed0b-2843-42fe-990d-abc8f4245033.png)

The exception above throws by assert code : 
`Assert.AreEqual("Jamie@southridgevideo.com", recognizedForm.Fields["Contact"].Value.AsString());` .

### Expected Behavior
The investigate so far, in local test: `recognizedForm.Fields` does not contains parameter `Contact`, but contains some parameters that not exist in `TestFile.InvoiceMultipage` file, it's really strange. Environment variables I gived in local test:
- Endpoint
- ApiKey
- MultipageBlobContainerSasUrl

Am I missing something or need to set other variables?

@jongio, @benbp, @maririos for notification.

**Comment by maririos** [comment]
@chidozieononiwu we  need to keep in sync what we have in public azure storage container `trainingdata` with other souvereign clouds. Someone from eng service team helped us a while back, but I imagine the files got out of sync again.
Could you help us look into this? And also, is there a process to keep the storage containers in sync? I expected with the work we are doing in upcoming releases that the content in the container will vary.

**Comment by maririos** [comment]
Interesting. If this test passes for public cloud, it means the field `Contact` is present in the document and/or the custom model.
Is there any way you can share what the json response from the service is when the test is running targeting `UsGov`? 
looking at what the service returns might help us understand a little more about what is happening

**Comment by zedy-wj** [comment]
The test passes for public cloud in pipeline, I cannot get the json response from the service in pipeline. So I run the test in local, it failed even in public. The data in recognizedForms.Fields as follow:
![image](https://user-images.githubusercontent.com/81678720/130406585-996a8b97-b87c-4d8d-814c-6283a16f2ae4.png)
May I need to set something?

**Comment by maririos** [comment]
The weird thing is that I don't see those fields in the file https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/Assets/multi1.pdf the test is using ....
When I ran it locally, everything works :(
If you run the test under the debugger and set a breakpoint [here ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/Models/AnalyzeOperationResult.Serialization.cs#L18) you can see the json response from the service. Look for the one where the status is `succeeded`. That one should contain all the information with all the fields.
If you can put that in a file and shared it, we can get a closer idea of what might be happening in your environment

**Comment by zedy-wj** [comment]
@maririos - Thanks for your help! It seems that I uploaded the wrong blobs in container in my storage account. 
When running in the pipeline, is there a fixed storage account, or can you tell me which blobs should I upload to my own container?

**Comment by maririos** [comment]
I sent you the files over email.

**Comment by zedy-wj** [comment]
@maririos - Completed the updates in container, thanks for your help :)

**Comment by v-xuto** [comment]
This issue has been fixed, so we close this issue.
