### ISSUE TITLE
[Form Recognizer] No valid blobs found in the specified Azure blob container.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-sdk-for-net#23122]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

### Error Description:

Task `StartTrainingSucceedsWithValidPrefix` failed in [pipeline weekly-test](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1018418&view=logs&j=c7de73c1-1fa3-5f12-91c3-9e3a0d31061f&t=33bf5cdb-a707-561f-8a41-a824e21c1a5c&l=921) on `UsGov` cloud. The error message as follow:
```
Azure.RequestFailedException : Invalid model created with ID f3463a6e-aed4-4350-9576-28d778b96590
Status: 200 (OK)
ErrorCode: 2014

Additional Information:
error-0: 2014: No valid blobs found in the specified Azure blob container. Please conform to the document format/size/page/dimensions requirements.

Content:


Headers:
ms-azure-ai-errorcode: REDACTED
x-envoy-upstream-service-time: 16
apim-request-id: 31bff020-535a-4790-9bf8-855b287cae3b
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Date: Wed, 04 Aug 2021 09:26:07 GMT
Content-Length: 403
Content-Type: application/json; charset=utf-8

```

### Error Track:
Detail: [Code Link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormTrainingClient/FormTrainingClientLiveTests.cs#L239-L251)
![image](https://user-images.githubusercontent.com/81678720/128276263-b4137179-518e-4ed5-988f-d77c94c980f9.png)
The exception above throws by method `StartTrainingAsync` .

### Expected Behavior

The investigation so far, local test can pass. On `UsGov` cloud, the pipeline provided the container whether contains blobs which has the prefix "subfolder"?  If not, should we upload such a blob?

@jongio, @benbp, @maririos for notification.

**Comment by maririos** [comment]
@chidozieononiwu we  need to keep in sync what we have in public azure storage container `trainingdata` with other souvereign clouds. Someone from eng service team helped us a while back, but I imagine the files got out of sync again.
Could you help us look into this? And also, is there a process to keep the storage containers in sync? I expected with the work we are doing in upcoming releases that the content in the container will vary.

**Comment by zedy-wj** [comment]
@maririos - Issue has been fixed, thanks for your help!
