### ISSUE TITLE
Azure Cognitive Services ContentModerator DeleteTerm method does not work

### ISSUE THREAD

**Issue by gokhanald** [Azure/azure-sdk-for-net#23127]
Hello,

I am using content moderator on my api but one method does not work. Every other method will work correctly but delete term method does not work. Can you help me for this method?

Packages and tools are;
**-Visual Studio 2019 Community
-.net core 5.0 web api
-Microsoft.Azure.CognitiveServices.ContentModerator 2.0 nuget version
-PC W10 last version**

My method:
**await _contentModeratorClient.ListManagementTerm.DeleteTermWithHttpMessagesAsync(_termListId, text, AzureCognitiveConsts.TurkeyCode);**

I tried every way to delete term on exist list but it did not work. Also status code is 204 with no content. Other delete methods(deletelist etc) work fine. Why this delete method creates problem.

**Edit:** This problem occurs when language is selected as "tur" (Turkish). Term can be deleted from English term list. There is a language problem on this method.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by KranthiPakala-MSFT** [comment]
@swiftarrow11 Following up to see if there is any update on this issue? - Thank you
