### ISSUE TITLE
[BUG] Extracted numbers too large for 'float' type

### ISSUE THREAD

**Issue by Rodrick45** [Azure/azure-sdk-for-net#23134]
**Describe the bug**
In FieldValue_internal I see that ‘ValueNumber’ is of type ‘float?’. This datatype is inadequate for the data being returned. For example. if you attempt to parse "52091725" into a float you will end up with "52091724". In other words, the data returned from the form recognizer engine will be changed by the SDK.

**Expected behavior**
Preserve the value of larger numbers.

**Actual behavior (include Exception or Stack Trace)**
Returns the wrong number for larger numeric values.

**To Reproduce**
Parse an invoice with an invoice amount of $52,091,725. See what the results are in the SDK.

**Environment:**
 - Name and version of the Library package used: Azure.AI.FormRecognizer_3.1.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Framework 4.8 (any I would think)
 - IDE and version : Any I would think

**Comment by maririos** [comment]
We should consider adding `AsDouble`  so the user can decide accordingly

**Comment by AlexGhiondea** [comment]
Closing this in favor of #20293
