### ISSUE TITLE
[BUG] : Not able to insert messages in a Service bus queue after reading message from the same queue using ServiceBusClient defined methods

### ISSUE THREAD

**Issue by v-moush** [Azure/azure-sdk-for-net#23143]
**Describe the bug**
We have use cases like read the messages from the service bus queue and then insert different messages into the same queue
But unfortunately, we were not able to insert messages in a Service bus queue after reading a message from the same queue using  ServiceBusClient defined methods

**Expected behavior**
ServiceBusClient should insert messages into the queue once we execute the SendMessagesAsync/SendMessageAsync

**Actual behavior (include Exception or Stack Trace)**
Immediately not inserting messages into the service bus queue.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```csharp
class Program
	{
		static string connectionString = "Pass_service_bus_connectionstring";
		static string QueueName = "queue_name";
		static async Task Main(string[] args)
		{
			////1.Reading messages from the queue
			//// Create  service bus client
			var sbc = new ServiceBusClient(connectionString);
			var receiver = sbc.CreateReceiver(QueueName, new ServiceBusReceiverOptions() { ReceiveMode = ServiceBusReceiveMode.ReceiveAndDelete });
			////Try to read messages from the queue using receiver
			var result = await receiver.ReceiveMessagesAsync(maxMessages: 10);

			//// 2. Sending messages to the queue.
			var sbc1 = new ServiceBusClient(connectionString);
			var sender = sbc1.CreateSender(QueueName);
			//// Try to send single message
			await sender.SendMessageAsync(new ServiceBusMessage("Test"), default);
			var messages = new List<ServiceBusMessage>() { new ServiceBusMessage("Test2"), new ServiceBusMessage("Test3") };
			/// Try to send multiple messages 
			await sender.SendMessagesAsync(messages, default).ContinueWith(_ =>
			 {

			 });
		}
	}
```

**Environment:**
 - Name and version of the Library package used: [Azure.Messaging.ServiceBus 7.2.1/7.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
     Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400-preview.21328.4\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  3.1.411 [C:\Program Files\dotnet\sdk]
  5.0.205 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21328.4 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 - IDE and version : [Microsoft Visual Studio Enterprise 2019 Version 16.10.3]
[ConsoleApp1.zip](https://github.com/Azure/azure-sdk-for-net/files/6941858/ConsoleApp1.zip)

**Comment by jsquire** [comment]
Hi @v-moush.  Thank you for reaching out and we regret that you're experiencing difficulties.  Can you help us understand the behavior that you're seeing a bit better?   When you say that you "can't insert messages into a queue", do you mean that the "SendAsync" call is throwing an exception or is there something else that you're observing?

**Comment by v-moush** [comment]
Hi @jsquire,

We didn't get any sort of exception when executing the provided code. 

can't insert messages into a queue: What I mean here is, When we execute this piece of code 
await sender.SendMessagesAsync(messages, default).ContinueWith(_ =>
			 {
			 });

I am excepting that, It should immediately(without any delay)  insert the list of messages into the provided queue. I verified the count of messages in the azure service bus portal, but no messages got inserted into the queue.
FYI : 
![image](https://user-images.githubusercontent.com/88513552/128530642-9d6a4756-f7be-43d7-9f21-2196d2cb423b.png)

To add more to this
1. Failure scenario : 
     - Read the messages from the service bus queue if any
     
        var sbc = new ServiceBusClient(connectionString);
			var receiver = sbc.CreateReceiver(QueueName, new ServiceBusReceiverOptions() { ReceiveMode = ServiceBusReceiveMode.ReceiveAndDelete });
			////Try to read messages from the queue using receiver
			var result = await receiver.ReceiveMessagesAsync(maxMessages: 10);

      - Try to insert the messages into the same queue(which we read messages from the previous step)
      
          var sbc1 = new ServiceBusClient(connectionString);
			var sender = sbc1.CreateSender(QueueName);
			//// Try to send single message
			await sender.SendMessageAsync(new ServiceBusMessage("Test"), default);
			var messages = new List<ServiceBusMessage>() { new ServiceBusMessage("Test2"), new ServiceBusMessage("Test3") };
			/// Try to send multiple messages 
			await sender.SendMessagesAsync(messages, default).ContinueWith(_ =>
			 {

			 });

As per our requirement, I have to follow the below workflow
- Read any messages in the queue 
- Build custom messages and into the same queue


Please let me know if you need any other information.

Thanks & Regards,
Moueen Shaik

**Comment by JoshLove-msft** [comment]
@v-moush I think I see what is happening here. Your initial receive call times out after putting a request for 10 credits (messages) on the receive link. After your messages are sent, they are immediately delivered to your still open link, that you are no longer actively listening to. Since you are receiving in ReceiveAndDelete mode, the messages do not show up in the portal. In order to get the behavior you are looking for, you can either receive in PeekLock mode, or close your receiver immediately after the receive operation times out, by calling:
```c#
await receiver.CloseAsync();
```
