### ISSUE TITLE
MaxAutoLockRenewalDuration is not working for Azure Service Bus  

### ISSUE THREAD

**Issue by cvakarna** [Azure/azure-sdk-for-net#23156]
MaxAutoLockRenewalDuration is not working on the ServiceBusProcessor.
I have a queue which is configured as lock duration 5 min, and running two concurrent listeners for the queue,
Message processing will take more than 5min(assume that it takes 8min),then lock renewal should happen automatically but message is available for the other consumer/listener after 5 min.

code sample to configure ServiceBusProcessor

>  
        public void ReceiveMessages()
        {
            
            
            var client =  CreateQueueClient("managedQueue");
            var serviceBusProcessorOptions = new  ServiceBusProcessorOptions
            {
                MaxConcurrentCalls = 2,
                AutoCompleteMessages = false,
                MaxAutoLockRenewalDuration = new TimeSpan(0, 10, 0),
            };
            var proc = client.CreateProcessor("managedQueue", options: serviceBusProcessorOptions);
            proc.ProcessMessageAsync += MessageHandler;
            proc.ProcessErrorAsync += ErrorHandler;
            // start processing 
            proc.StartProcessingAsync().GetAwaiter().GetResult();
         
        }

**Expected behavior**
as per the documentation message should be auto renewal after message lock duration expires 
Doc:
` // Summary:
        //     Gets or sets the maximum duration within which the lock will be renewed automatically.
        //     This value should be greater than the longest message lock duration; for example,
        //     the LockDuration Property.`

**Actual behavior (include Exception or Stack Trace)**
auto renewal not happening and message is available for the other consumer.

 - Name and version of the Library package: Azure.Messaging.ServiceBus (2.7.2)

Can please any one help me regarding this

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @cvakarna,
We have several tests that exercise this functionality and they all appear to be working as expected. Can you clarify how you are detecting that the same message is being received by your other listener - do they have the same SequenceNumber? Does the initial listener eventually attempt to complete the message? Does it throw an exception when it does?

**Comment by cvakarna** [comment]
Hi @JoshLove-msft 
Thanks for the response,
**Can you clarify how you are detecting that the same message is being received by your other listener?**
  As i mentioned in the above code , MaxConcurrentCalls = 2, and set lock max duration 5 min, Assuming processing takes 7 mins.
  

> 
        async Task MessageHandler(ProcessMessageEventArgs args)
        {
            try
            {
                
                  string body = args.Message.Body.ToString();
                Console.WriteLine($"Received: {body}");
                Console.WriteLine($"SequenceNumber:{args.Message.SequenceNumber}, Lock Until:{args.Message.LockedUntil}, Received DateTime Utc:{DateTime.UtcNow},DeliveryCount:{args.Message.DeliveryCount}");
                await Task.Delay(420000);//7 min
                Console.WriteLine("Processing Comepleted");

                // complete the message. messages is deleted from the queue. 
                await args.CompleteMessageAsync(args.Message);
                Console.WriteLine("Message Marked as Comepleted");
            }
            catch(Exception ex)
            {
                Console.WriteLine("Exception In Handler:"+ex);
            }
           
        }

After 5 min , same method is calling and processing same message again instead of Auto renew the lock duration.

**do they have the same SequenceNumber?** 
yes its same sequence number.

**Does the initial listener eventually attempt to complete the message? Does it throw an exception when it does?**
Yes , after 7 min of processing , its throwing exception when trying to complete the message.

I have attached screen shot, please find it
![image](https://user-images.githubusercontent.com/34210823/128660767-9d4aa94d-85ab-46f1-80b8-696a6f7081f8.png)

**Comment by JoshLove-msft** [comment]
I haven't been able to reproduce this using the provided code. One thing I did notice is that the provided code is using sync over async, so I wonder if there could be thread starvation happening. Could you try making your code fully async and adding SDK logging to further troubleshoot:
```c#
        static async Task Main(string[] args)
        {
            Program p = new Program();
            Console.WriteLine("Hello World!");
            using var logger = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Verbose);
            await p.CreateConsumer();
            await Task.Delay(Timeout.Infinite);
        }
```

**Comment by cvakarna** [comment]
@JoshLove-msft 
can you please check with this repo, still i am facing same issue after changing as per your suggestion also

https://github.com/cvakarna/servicebus_issue/blob/main/ServicebusSample/Program.cs

**Comment by JoshLove-msft** [comment]
Can you include the SDK logs?

**Comment by cvakarna** [comment]
![image](https://user-images.githubusercontent.com/34210823/128823389-e30930d1-d8a3-4419-93ad-b58a22d69c34.png)

please find the sdk logs

**Comment by JoshLove-msft** [comment]
Looks like the lock is already being lost before the first renew lock call.
Would you mind including the lockedUntilTime like you have in the snippet from this issue:
            Console.WriteLine($"SequenceNumber:{args.Message.SequenceNumber}, Lock Until:{args.Message.LockedUntil}, Received DateTime Utc:{DateTime.UtcNow},DeliveryCount:{args.Message.DeliveryCount}");

**Comment by cvakarna** [comment]
Observed that My system time is 1 min slower than actual , i have reset to 1 min faster then its working as expected

**Comment by JoshLove-msft** [comment]
> Observed that My system time is ~1 min slower than actual , i have reset to 1 min faster then its working as expected ,
> Is there any chances to get this issue when we deploy in Azure kubernetes ?

I see - good find! I can't really speak to what the system timing would be when using Azure Kubernetes. I found a somewhat related issue in the repo there - https://github.com/Azure/AKS/issues/1994

**Comment by cvakarna** [comment]
Thanks @JoshLove-msft  for your assistance. We will check that.
