### ISSUE TITLE
[BUG] AzureCliCredential with specified tenant Id does not work

### ISSUE THREAD

**Issue by tpajurek-dtml** [Azure/azure-sdk-for-net#23158]
There is bug in the generating command line arguments for Azure CLI in `AzureCliCredential`:

https://github.com/Azure/azure-sdk-for-net/blob/f07fd00dc3fb6311f4a85a9e02e05b162b4f2976/sdk/identity/Azure.Identity/src/AzureCliCredential.cs#L182

Instead of `--tenant` there is `-tenant` argument which leads to following error:

`unrecognized arguments: xxx`

PR: https://github.com/Azure/azure-sdk-for-net/pull/23159

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.
