### ISSUE TITLE
[Servicebus] test failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23152]
Servicebus nightly test runs are failing with:

> Error message
> Multiple failures or warnings in test:
> 
> Azure.Messaging.ServiceBus.ServiceBusException: The session lock was lost. Request a new session receiver. (SessionLockLost) ---> Azure.Messaging.ServiceBus.ServiceBusException: The write operation failed, see inner exception. ErrorCode: ConnectionReset (ServiceCommunicationProblem) ---> System.IO.IOException: The write operation failed, see inner exception. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
> at Microsoft.Azure.Amqp.Transport.TransportStream.EndWrite(IAsyncResult asyncResult)
> at System.Net.Security.SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
> at System.Net.Security.SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
> --- End of inner exception stack trace ---
> at System.Net.Security.SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
> at System.Net.Security.SslStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback asyncCallback, Object asyncState)
> at Microsoft.Azure.Amqp.Transport.TlsTransport.WriteAsync(TransportAsyncCallbackArgs args)
> at Microsoft.Azure.Amqp.AsyncIO.AsyncWriter.WriteCore()
> --- End of inner exception stack trace ---
> --- End of inner exception stack trace ---
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ThrowIfSessionLockLost() in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1440
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<ExecuteRequest>d__59.MoveNext() in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1102
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult() at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<GetStateInternal>d__63.MoveNext() in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1181 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.ConfiguredTaskAwaitable1.ConfiguredTaskAwaiter.GetResult()
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<GetStateAsync>b__62_0>d.MoveNext() in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1164
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at System.Threading.Tasks.ValueTask1.get_Result() at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__212.MoveNext() in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 144
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__212.MoveNext() in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 164 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Threading.Tasks.ValueTask1.get_Result()
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<GetStateAsync>d__62.MoveNext
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.<ProcessSessionMessage>d__2.MoveNext() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 176
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.<ProcessSessionMessage>d__2.MoveNext() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 187
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.<ProcessSessionMessage>d__2.MoveNext() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 187
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.<ProcessSessionMessage>d__2.MoveNext() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 188
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1034081&view=results

**Comment by JoshLove-msft** [comment]
All of the failures were in Canary and all related to the service shutting down the connection. Nothing to do here.
