### ISSUE TITLE
eventgrid - cspell found spelling errors in public API surface

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#23179]
Investigation for this PR: https://github.com/Azure/azure-sdk-for-net/pull/23150 found spelling errors. When the linked PR merges this service will be opted out of public API surface spell checking to keep other PRs unblocked. This issue describes how to opt back in. 

If the above linked PR has not merged this service is still opted out and not blocked by the detection of spelling errors in the public API surface. 

## What to do

1. Correct spelling errors or check in fixes for the false positives 
1. Opt back into Public API surafe spell checking

## Correct errors

To correct false positives or learn about spell checking see: https://aka.ms/azsdk/engsys/spellcheck

#### Spell Check Output

```
1/3 .\sdk\eventgrid\Azure.Messaging.EventGrid\api\Azure.Messaging.EventGrid.netstandard2.0.cs 1433.40ms X
D:\code\azure-sdk-for-net\sdk\eventgrid\Azure.Messaging.EventGrid\api\Azure.Messaging.EventGrid.netstandard2.0.cs:288:37 - Unknown word (Errored)
D:\code\azure-sdk-for-net\sdk\eventgrid\Azure.Messaging.EventGrid\api\Azure.Messaging.EventGrid.netstandard2.0.cs:288:67 - Unknown word (Errored)
D:\code\azure-sdk-for-net\sdk\eventgrid\Azure.Messaging.EventGrid\api\Azure.Messaging.EventGrid.netstandard2.0.cs:292:43 - Unknown word (Errored)
D:\code\azure-sdk-for-net\sdk\eventgrid\Azure.Messaging.EventGrid\api\Azure.Messaging.EventGrid.netstandard2.0.cs:292:79 - Unknown word (Errored)
D:\code\azure-sdk-for-net\sdk\eventgrid\Azure.Messaging.EventGrid\api\Azure.Messaging.EventGrid.netstandard2.0.cs:660:97 - Unknown word (Gcch)
2/3 .\sdk\eventgrid\Microsoft.Azure.Messaging.EventGrid.CloudNativeCloudEvents\api\Microsoft.Azure.Messaging.EventGrid.CloudNativeCloudEvents.netstandard2.0.cs 36.05ms
3/3 .\sdk\eventgrid\Microsoft.Azure.WebJobs.Extensions.EventGrid\api\Microsoft.Azure.WebJobs.Extensions.EventGrid.netstandard2.0.cs 29.89ms
CSpell: Files checked: 3, Issues found: 5 in 1 files
```

To check the public API surface locally, in the root of the repo run:

```
eng/scripts/Export-API.ps1 -ServiceDirectory eventgrid -SpellCheckPublicApiSurface
```

You may also need to set `-SDKType` if the appropriate value of `SDKType` is not `all` for the service.

## Opt back in

NEW INSTRUCTIONS: In the [`.vscode/cspell.json`](https://github.com/Azure/azure-sdk-for-net/blob/main/.vscode/cspell.json) file remove the line for your service (of the form `"sdk/<service>/*/api/*.cs"`) from the `ignorePaths` section and check in the change. 

OLD INSTRUCTIONS: ~~In the `ci.yml` file for this service, remove the line: `SpellCheckPublicApiSurface: false`~~

**Comment by pallavit** [comment]
@jsquire I moved this issue to the EventHubs project so it does not get lost, please feel free to move it to any other location you want.

**Comment by jsquire** [comment]
These are GA'd types published by Media Services.  As these names were approved by the REST API board, we have no plans to change them.
