### ISSUE TITLE
sqlmanagement - cspell found spelling errors in public API surface

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#23188]
Investigation for this PR: https://github.com/Azure/azure-sdk-for-net/pull/23150 found spelling errors. When the linked PR merges this service will be opted out of public API surface spell checking to keep other PRs unblocked. This issue describes how to opt back in. 

If the above linked PR has not merged this service is still opted out and not blocked by the detection of spelling errors in the public API surface. 

## What to do

1. Correct spelling errors or check in fixes for the false positives 
1. Opt back into Public API surafe spell checking

## Correct errors

To correct false positives or learn about spell checking see: https://aka.ms/azsdk/engsys/spellcheck

#### Spell Check Output

```
1/1 .\sdk\sqlmanagement\Azure.ResourceManager.Sql\api\Azure.ResourceManager.Sql.netstandard2.0.cs 1325.21ms X
D:\code\azure-sdk-for-net\sdk\sqlmanagement\Azure.ResourceManager.Sql\api\Azure.ResourceManager.Sql.netstandard2.0.cs:1639:165 - Unknown word (Droppeded)
D:\code\azure-sdk-for-net\sdk\sqlmanagement\Azure.ResourceManager.Sql\api\Azure.ResourceManager.Sql.netstandard2.0.cs:1640:199 - Unknown word (Droppeded)
D:\code\azure-sdk-for-net\sdk\sqlmanagement\Azure.ResourceManager.Sql\api\Azure.ResourceManager.Sql.netstandard2.0.cs:2712:96 - Unknown word (CIAS)
D:\code\azure-sdk-for-net\sdk\sqlmanagement\Azure.ResourceManager.Sql\api\Azure.ResourceManager.Sql.netstandard2.0.cs:3652:102 - Unknown word (Vcores)
D:\code\azure-sdk-for-net\sdk\sqlmanagement\Azure.ResourceManager.Sql\api\Azure.ResourceManager.Sql.netstandard2.0.cs:3652:129 - Unknown word (Vcores)
D:\code\azure-sdk-for-net\sdk\sqlmanagement\Azure.ResourceManager.Sql\api\Azure.ResourceManager.Sql.netstandard2.0.cs:3677:38 - Unknown word (Vcores)
D:\code\azure-sdk-for-net\sdk\sqlmanagement\Azure.ResourceManager.Sql\api\Azure.ResourceManager.Sql.netstandard2.0.cs:3679:30 - Unknown word (Vcores)
D:\code\azure-sdk-for-net\sdk\sqlmanagement\Azure.ResourceManager.Sql\api\Azure.ResourceManager.Sql.netstandard2.0.cs:4079:65 - Unknown word (Unrestorable)
CSpell: Files checked: 1, Issues found: 8 in 1 files
```

To check the public API surface locally, in the root of the repo run:

```
eng/scripts/Export-API.ps1 -ServiceDirectory sqlmanagement -SpellCheckPublicApiSurface
```

You may also need to set `-SDKType` if the appropriate value of `SDKType` is not `all` for the service.

## Opt back in

NEW INSTRUCTIONS: In the [`.vscode/cspell.json`](https://github.com/Azure/azure-sdk-for-net/blob/main/.vscode/cspell.json) file remove the line for your service (of the form `"sdk/<service>/*/api/*.cs"`) from the `ignorePaths` section and check in the change. 

OLD INSTRUCTIONS: ~~In the `ci.yml` file for this service, remove the line: `SpellCheckPublicApiSurface: false`~~

**Comment by yungezz** [comment]
Azure.ResourceManager.Sql pacakge or Azure.ResourceManager.* is old Track2 pacakges. They'll not be updated, and will be deprecated. While we can see if the issue is in new Track2 SDK. add @ArcturusZhang to help confirm on this.
