### ISSUE TITLE
Azure OpenTelemetry Exporter for logs availability

### ISSUE THREAD

**Issue by stoff3l** [Azure/azure-sdk-for-net#23207]
Hi,

I've been looking for a way to export logs to Azure AppInsights / Monitor. Currently it looks like OpenTelemetry provides only a ConsoleExporter for this purpose and I couldn't find one in the Azure.Monitor.OpenTelemetry.Exporter package.

The following configuration of logging on the IHost builder works for logging to the Console, I am however unable to find a way to configure the same for logging to AppInsights.
```C#
.ConfigureLogging((context, builder) =>
{
    builder.ClearProviders();
    builder.AddConsole();
    builder.AddOpenTelemetry(options =>
    {
        options.IncludeScopes = true;
        options.ParseStateValues = true;
        options.IncludeFormattedMessage = true;
        options.AddConsoleExporter();
    });
});
```

Is there a way to configure this so logs are sent to App Insights? If functionality is not yet available, is it on the roadmap?

Thank you

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by pakrym** [comment]
cc @reyang

**Comment by mattmccleary** [comment]
Hi @stoff3l, thank you for reaching out! Yes logging is definitely on the roadmap, though I cannot say exactly when. It did not make the cut for 2021, and we'll of course consider it as a high priority item in 2022. Keep in mind that we have a dependency on the OpenTelemetry community. We release features as they stabilize in OpenTelemetry, and logging is still experimental. Please don't hesitate to reach out with other questions.

**Comment by stoff3l** [comment]
Hi @mattmccleary, thank you for the feedback, it is appreciated.
