### ISSUE TITLE
Microsoft Hadoop Avro Source code

### ISSUE THREAD

**Issue by welly87** [Azure/azure-sdk-for-net#2321]
Hi all, 

I can't find the source code of the microsoft hadoop avro here. It's said that it has been move here. 

Any help would be really appreciated

**Comment by markcowl** [comment]
@shefaliv can you take a look?

**Comment by mbauerdev** [comment]
Any news on that?

**Comment by javierholguera** [comment]
I'm interested on this as well

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.
