### ISSUE TITLE
[FEATURE REQ] Add AddTableServiceClient(Uri) extension method

### ISSUE THREAD

**Issue by flcdrg** [Azure/azure-sdk-for-net#23221]
**Library or service name.**
Azure.Data.Tables
 
**Is your feature request related to a problem? Please describe.**
All the other extension methods for Blob and Queue include an extension that just takes a Uri. For some reason when https://github.com/Azure/azure-sdk-for-net/issues/20392 was resolved, this overload was overlooked.

eg.

```csharp
AddTableServiceClient<TBuilder>(TBuilder, Uri)
```

**Comment by Alilux** [comment]
@msftbot 
aHR0cHM6Ly9kYXRhdHJhY2tlci5pZXRmLm9yZy9kb2MvaHRtbC9yZmM4MjUy

**Comment by Alilux** [comment]
aHR0cHM6Ly93d3cuZ29vZ2xlYWRzZXJ2aWNlcy5jb20vcGFnZWFkL2FjbGs/ZmJzX2FlaWQ9LTY5
MjMyNTcyNzM0NTI4NDMwMDgmc2E9TCZhaT1DN3Btd0p3Z1NZZS1nRmRIUGJwN1JrTGdGeXYyb3Ay
VHF6X3VSMHd5Tmh0XzRzd3NRQVNDVDdmRjdZTW1HNUlxMHBOZ1BvQUhFOXI3ZkE4Z0JDYWdEQWNn
RGlnU1lCQWlxQk9ZQlQ5Q0VEUkJ2UFh4aEtkMFlmM1BER3UwRXNTbkJ4aTU3bXp1bEIwQlpJclNT
QzBrX2JQUy04Q0JWNlp5QVJiSExjVFpIYXVYNktpa2poMURnRTRtV3RndlI5LTZuVkhGWnBzZXdj
UDQtb29MM0lhNHowZUNTcjU4VjFVNDJjTmRWZ1pVZnFiWU52RHR4MDdnalh6Q0FlTDlpREx1bVhJ
ZVhKTlZiMnVSUHQydUE0cW9Ock50VWpSX0ZnWUJyTnpFTWMxWjM5bEo1OGJFelhqNHZaV2tDNUx2
SUNHYTY5Tm5QVm9YZjBlMHJldURtaWNrMU5LWkZOZ2tQRjUwRk14bm9lU2FfWkZIWUQ2cF9MbElu
bHdMV2ZtNnZKcnNJRGxZNXQtYUxuRUNMS2tVMjdfQmQxR3ZBQlA2TnN2Ml9Bb2dGcUxtc255RDZC
UVlJSlJBQkdBQ1FCZ0dnQmk3WUJnS0FCNlNKd1NDWUJ3R29CX0RaRzZnSDh0a2JxQWVPemh1b0I1
UFlHNmdIdWdhb0ItNldzUUtvQjZhLUc2Z0g3TlVicUFmejBSdW9CLXpWRzZnSGx0Z2JxQWVxbTdF
QzJBY0EtZ2NQWTI5dExtVmlZWGt1Ylc5aWFXeGxvQWpUdzZVRXNBZ0N3QWdCMGdnSENJQmhFQUVZ
SDRBS0FwQUxBOGdMQVlBTUFiZ01BYmdUN2dQWUV3dUNGQjhhSFcxdlltbHNaV0Z3Y0RvNk1pMWpi
MjB1WVdJdVlYQnBZMnhwWlc1MGlCUUswQlVCbUJZQmdCY0ImYWU9MiZudW09MSZjaWQ9Q0FBU0V1
Um9jMjFmajNGM2tqUmVHVHZzMU8xcmx3JnNpZz1BT0Q2NF8zZW5OM0Rsb1BIMmk1ODhUUUdJejRs
TGJoT3VnJmNsaWVudD1jYS1hcHAtcHViLTMyNTk2MjYzNzk1NTYxMTImbmI9OSZueD04MSZueT0z
NSZtYj0xJm1zPUNvQUNNMXFLWERyNWViby0xYklXZ0pQdWxlMmZRVzhsZFcyWWJGNkx4Z1FyQmQ0
YVlYZHVzUjRMLWlsQXRoY2NZb19LUWVZeU9SOU45UFFNSzQ4N213LUdwRjVUc3ZNMmNlNklLSlMy
VERKY3JCSm82WUpqNUJROWlQQVRQMmp4eWtSSDZkbXFxX3ZOenFyZThEWEViV1BGS3BmbHJvZjFR
QUd3dHZaa3FmVWMwVzRqdEtLVkdtTVFpUlRWTC1OblFTRlhXTXFSSm1BTzRzWS1ucDBLSXg5U2pu
a28zdERKWEVjMk5EcEpvVHdIMWVMXzhnOV9UellqbFVxY0ozdG5hY2NJNmpKYnl4UTZ5Zjh3US1f
TDF5bzJYdEk1RkRERlRvWmlxWnY5allTSjJXY3NpOGVIZTl6YTJuTEJmTGo5SHh2VERieXl0RVMx
LXlyR3BWcVRRY1c1ZHhJUVhqenh3dXZEZVVWekY5eVhoVjlJd2cmZGN0PTEmYWR1cmw9aHR0cHM6
Ly93d3cuZWJheS5jb20vaXRtLzM3MzA4MTc4MjE1MSUzRm5vcm92ZXIlM0QxJTI2bXB0JTNEJTVC
Q0FDSEVCVVNURVIlNUQlMjZzaXRlaWQlM0QwJTI2aXBuJTNEYWRtYWluMiUyNm1rZXZ0JTNEMSUy
Nm1rcmlkJTNENzExLTE1NzY4Ny05MTU4MzctNyUyNm1rY2lkJTNENCUyNnBsYWNlbWVudCUzRDUy
OTcxNg==

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
//cc: @christothes
