### ISSUE TITLE
Microsoft Hadoop Avro .NET Core

### ISSUE THREAD

**Issue by welly87** [Azure/azure-sdk-for-net#2322]
I have been porting avro to .NET core. 

https://github.com/welly87/Microsoft-Avro-Core

However a couple of test is failing. 

![image](https://cloud.githubusercontent.com/assets/242694/18260427/f06adfd8-7417-11e6-90f7-326f331d0544.png)

Any pull request would be really appreciated.

**Comment by markcowl** [comment]
@shefaliv Please take a look

**Comment by bdparrish** [comment]
trying to include Avro in a .NET Core app.  any timeline on this being solved?

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.
