### ISSUE TITLE
No public BatchPoolIdentity constructor

### ISSUE THREAD

**Issue by jeanbaptisteranson** [Azure/azure-sdk-for-net#23225]
Hi,
It looks like that in the latest SDK for Azure Batch (Microsoft.Azure.Batch in version 15.0), the constructor for BatchPoolIdentity is internal.
Did I miss something? I can we assign the newly added property cloudPool.Identity?

Regards,
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e94ed49-54e5-a2a3-805b-89b0cfd96557
* Version Independent ID: 58829d6a-f3ef-01c1-3095-c5bc2a931297
* Content: [BatchPoolIdentity Class (Microsoft.Azure.Batch) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.batchpoolidentity?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Batch/BatchPoolIdentity.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Batch/BatchPoolIdentity.xml)
* Service: **batch**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jeanbaptisteranson** [comment]
Hello,
Microsoft.Azure.Batch in version 15.1.0 has still the same limitation:  No public BatchPoolIdentity constructor.
I can instantiate a BatchPoolIdentity using reflection API, but I assume there is a reason why the constructor is internal.
I noticed that Managed Pool Identities are now GA since 08.30.21: https://azure.microsoft.com/en-us/updates/azure-batch-updates-august2021/ so when will we be able to use the SDK for such a purpose?

**Comment by paterasMSFT** [comment]
Hello, @jeanbaptisteranson. We are targeting this for our next release. Thank you for your patience and for bringing this to our attention.

**Comment by navba-MSFT** [comment]
@jeanbaptisteranson Apologies for the delayed response. We are looking into this issue and we will update this thread once we have more details.

@paterasMSFT Could you please provide an update on the fix ?

**Comment by bscheurm** [comment]
The code sample in the [documentation](https://docs.microsoft.com/en-us/azure/batch/managed-identity-pools#create-a-batch-pool-with-user-assigned-managed-identities) on how to assign an identity to a pool still sets the Identity property with `new BatchPoolIdentity()`. Is it possible to read key vault secrets from a batch node without the ability to set that property (due to the internal ctor)?

I've been trying to get Batch to access secrets with a user assigned identity for a few days now and no matter what I try it results in the error below:
```
Azure.Identity.CredentialUnavailableException: DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
- ManagedIdentityCredential authentication unavailable. The requested identity has not been assigned to this resource.
Status: 400 (Bad Request)

Content:
{"error":"invalid_request","error_description":"Identity not found"}

... stack trace, etc. ...
```

**Comment by dazfuller** [comment]
Any update on this as it's causing issues here as well

**Comment by paterasMSFT** [comment]
Identities can be assigned to a pool via the [Batch SDK Management library](https://github.com/Azure/azure-sdk-for-net/blob/81049cb412a8cccab586b8fdeedbf37aa0328c36/sdk/batch/Microsoft.Azure.Management.Batch/src/Generated/Models/Pool.cs#L122). You can instantiate a [BatchPoolIdentity](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/batch/Microsoft.Azure.Management.Batch/src/Generated/Models/BatchPoolIdentity.cs) using the Management plane as well.

This cannot be done using the Data Plane SDK.

**Comment by dazfuller** [comment]
I think that is pretty well known and is highlighted in the documentation. However it exists in the client SDK but doesn't work. And then mixing the SDKs to achieve the desired result leads to a lot of ambiguity, with names duplicated, interfaces being similar but not the same, and with the management SDK having it's own issues such as hiding API errors leading to breaking out Fiddler to intercept the requests to work out what exactly is going on.

This is still a valid issue. The SDK has an option but it is broken. So it should be removed or fixed.
