### ISSUE TITLE
SendDirectNotificationAsync doc does not specify that List<string> is only available in Basic tier or higher

### ISSUE THREAD

**Issue by Reisclef** [Azure/azure-sdk-for-net#23262]
The SendDirectNotificationAsync() method which utilises a string parameter works successfully.

However, if passing in a list of string tokens (using the IList<string> parameter), and your Notification Hub is on the Free tier, Azure will throw an error: "Microsoft.Azure.NotificationHubs.Messaging.QuotaExceededException:  This operation is not available for your tier".

I appreciate that this is more down to the way the tiers are configured within Azure itself, but I thought that this area of the docs could perhaps include information about this.

It's not especially clear that the single send method will be successful on the free tier, but that the higher tiers are required for sending the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b43d313-9725-124e-73a1-ae17ae0cdf6e
* Version Independent ID: 540dc7ff-c532-6c09-3b66-941f35601f2d
* Content: [NotificationHubClient.SendDirectNotificationAsync Method (Microsoft.Azure.NotificationHubs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.notificationhubclient.senddirectnotificationasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.NotificationHubs/NotificationHubClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.NotificationHubs/NotificationHubClient.xml)
* Service: **notification-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
This issue has been transferred to the Azure Notification Hubs repository as [#200](https://github.com/Azure/azure-notificationhubs-dotnet/issues/200).
