### ISSUE TITLE
[BUG] Operation names empty and activities shows child activities as external services

### ISSUE THREAD

**Issue by SebastianStehle** [Azure/azure-sdk-for-net#23266]
**Query/Question**
Hi, I try to migrate my application to OpenTelemetry to support more providers. It is kine of working, but I am not sure if I understand everything.

In my application startup I have the following code to configure Open Telemetry:

```
public static void AddMyTelemetry(this IServiceCollection services, IConfiguration config)
{
	services.AddOpenTelemetryTracing(builder =>
	{
		builder.SetResourceBuilder(
			ResourceBuilder.CreateDefault()
				.AddService("Notifo",
					"Notifo",
					typeof(Startup).Assembly.GetName().Version!.ToString()));

		builder.AddSource("Notifo");

		builder.AddAspNetCoreInstrumentation();
		builder.AddHttpClientInstrumentation(

		if (config.GetValue<bool>("logging:applicationInsights:enabled"))
		{
			builder.AddAzureMonitorTraceExporter(options =>
			{
				config.GetSection("logging:applicationInsights").Bind(options);
			});
		}
	});
}
```

Then I have a global ActivitySource:

```
public static class Telemetry
{
    public static readonly ActivitySource Activities = new ActivitySource("Notifo");
 }
```

And a few calls:

```
public async Task<IResultList<Event>> QueryAsync(...)
{
	using (Telemetry.Activities.StartActivity("MongoDbEventRepository/QueryAsync"))
	{
	}
}
```

What I do not understand:

1. Why are my sub-activities marked as external:
![image](https://user-images.githubusercontent.com/1236435/129059026-bd42338f-b36a-46f6-a7b3-8644e323a36d.png)

2. Why is my operation name always empty:
![image](https://user-images.githubusercontent.com/1236435/129059131-911a2c87-f6e6-4b7d-96e3-8f8f81b08158.png)

**Environment:**
 - Name and version of the Library package used: Azure.Monitor.OpenTelemetry.Exporter" Version="1.0.0-beta.2

**Comment by SebastianStehle** [comment]
My conclusions so far:

1. Operation name is not set. There is a context variable called `ai.operation.name` but it is not set. Should be set to display name.
2. The default telemetry type is `Dependency`, I don't know why, because it seems that the "normal" SDK also supports "Trace", which should be the default: https://github.com/microsoft/ApplicationInsights-dotnet/blob/3822ab1c591298b4c0c00eb6a853265a180e8d70/WEB/Src/PerformanceCollector/PerformanceCollector/Implementation/Service%20contract/TelemetryType.cs

**Comment by jsquire** [comment]
k you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by pakrym** [comment]
cc @reyang

**Comment by SebastianStehle** [comment]
I think this is actually a bug.

**Comment by BenjaBobs** [comment]
Any updates on this?
We're using MassTransit with a long tree of logic happening, so having the correct operation name show up instead of `<Empty>` would be quite valuable to us in terms of debugging time.

**Comment by BenjaBobs** [comment]
Possibly related to https://github.com/Azure/azure-sdk-for-net/issues/29807, it seems the `GetOperationName()` method in some cases ignore the `Activity.DisplayName` property.
