### ISSUE TITLE
[QUERY] Is there a way to get Sql Database connection strings with the SDK?

### ISSUE THREAD

**Issue by coppercosmo** [Azure/azure-sdk-for-net#23267]
**Query/Question**
Is there a way to get Sql Database connection strings with the SDK? I see that I can get SQL Server Keys with the SDK, but I'm not seeing any properties or methods that would get me the SQL DB connection string. Is this only available through the portal?

**Environment:**
 - Name and version of the Library package used: [Microsoft.Azure.Management.Fluent 1.37.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [.NET Core 3.1]
 - IDE and version : [Visual Studio 16.4]

**Comment by jsquire** [comment]
k you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help on this

**Comment by weidongxu-microsoft** [comment]
@coppercosmo 
There is no connection string from SDK. You had to make your connection string, based on server endpoint, authentication info etc., and for the application that consumes it.
