### ISSUE TITLE
[QUERY] Unable to copy to ShareFileClient from BlockBlobClient with URI

### ISSUE THREAD

**Issue by Lann094** [Azure/azure-sdk-for-net#23260]
**Query**
I'm attempting to make (what I think should be) a rudimentary copy: An existing block blob to a new share file. My understanding is the API should be capable of performing this purely on the storage account. But I cannot for the life of me work this out.

My simplified code:
```csharp
var blobClient = new BlockBlobClient(storageAccountDetails, "temp", blobName);

var shareClient = new ShareClient(storageAccountDetails, shareName);
await shareClient.CreateIfNotExistsAsync();
var fileClient = shareClient.GetRootDirectoryClient().GetFileClient(fileName);

await fileClient.StartCopyAsync(blobClient.Uri);
```

This occurs after the block blob is committed, and confirmed it exists. The same connection string are used for blob and share operations. But upon attempting to start the copy, it throws "The specified resource does not exist" for the sourceUri.

Is this not possible? Am I missing something?

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.9.1, Azure.Storage.Files.Shares 12.6.0
 - Hosting platform: Windows 10 .NET Core 3.1
 - IDE and version : Visual Studio 16.10.4

**Comment by seanmcc-msft** [comment]
Hi @Lann094,

I believe this is by-design with how the Storage Service works in terms of source authentication for copies.  I recommend creating a SAS URL for the source blob and passing it to `ShareFileClient.StartCopyAsync()`.  The other option would be to set the Public Access Policy of the source Container to public.

-Sean
