### ISSUE TITLE
Migration to `UpsertEntityAsync` from `TableOperation.InsertOrReplace` does not support ETag

### ISSUE THREAD

**Issue by jasond-s** [Azure/azure-sdk-for-net#23289]
The following code in the `Microsoft.Azure.Cosmos.Table` will obey the provided ETag value, and throw an exception if you attempt to update the entity.

```csharp
public async Task<bool> InsertOrReplaceAsync(T entity, CancellationToken cancellationToken = default)
{
    var insertOperation = TableOperation.InsertOrReplace(entity);
    var result = await _table.ExecuteAsync(insertOperation, TableRequestOptions, OperationContext(entity.ETag), cancellationToken);
    return ValidateResult(result);
}
```

Using the new `Azure.Data.Tables` package the ETag on the provided entity is not obeyed, and there is no overload to specify it, which there is for the `UpdateAsync` method.

```csharp
public async Task<bool> InsertOrReplaceAsync(T entity, CancellationToken cancellationToken = default)
{
    var result = await _table.UpsertEntityAsync(entity, TableUpdateMode.Replace, cancellationToken);
    return ValidateResult(result);
}
```

Some code has been removed for brevity of the example.

Is this a conscious design decision not to support the ETag for upsert operations? Or am I missing something?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
> Is this a conscious design decision not to support the ETag for upsert operations? Or am I missing something?

Yes, this is a conscious design. Is there a specific scenario you have where this is a blocker?

**Comment by jasond-s** [comment]
It's just really useful for playing fast and loose with optimistic concurrency. Sometimes we might have processors that are racing each other, and post processors, it's nice to just throw data at the table and not have to worry if something else has beaten you to it.

Appreciate we could just use a `409` for the insert and then use the ETag for updates. Still. ETag for both was a nice feature.

**Comment by HansOlavS** [comment]
Hi @christothes! I'm having the exact same issue as @jasond-s and this the first blocker I've run into when migrating from Microsoft.Azure.Cosmos.Table. The way I see it it's a glaring feature omission and renders UpsertEntity useless for most of my use-cases where I previously used InsertOrReplace.

I'd be happy to send a PR with an introduced optional ETag parameter in UpsertEntity.

**Comment by christothes** [comment]
Closing unless we see some additional feedback in support of this feature.
