### ISSUE TITLE
Insights - Web App - /metricDefinitions and /metrics don't match

### ISSUE THREAD

**Issue by solvingj** [Azure/azure-sdk-for-net#2329]
For azure web apps /metricDefinitions endpoint output is incomplete.  It only return the following 15 metrics, while the /metrics endpoint returns 23.  This problem does not appear to affect other resource types.  

Note: This is a problem with the API and not the SDK.

Metric Definitions
    CpuTime
    Requests
    BytesReceived
    BytesSent
    Http2xx
    Http3xx
    Http401
    Http403
    Http404
    Http406
    Http4xx
    Http5xx
    MemoryWorkingSet
    AverageMemoryWorkingSet
    AverageResponseTime

Metric Values
    CpuTime
    Requests
    BytesReceived
    BytesSent
    Http2xx
    Http3xx
    Http401
    Http403
    Http404
    Http406
    Http4xx
    Http5xx
    MemoryWorkingSet
    AverageMemoryWorkingSet
    AverageResponseTime
    OutgoingRequestBytes
    OutgoingRequestResponseBytes
    LocalReadBytes
    LocalWrittenBytes
    NetworkReadBytes
    NetworkWrittenBytes
    IncomingRequestBytes
    IncomingRequestResponseBytes

**Comment by adrianhall** [comment]
This is an old issue (so my apologies for the long period of inattention).  Is this still an issue?  If so, can you provide more details on the current state of the problem, including any .NET libraries in use?
