### ISSUE TITLE
[TextAnalytics] Adding Extract Summary service methods

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#23304]
Currently the Extract Summary API is hidden inside the Analyze Actions service method, which compromises discoverability. This is a pattern we are probably going to see more frequently going forward.

Consider adding convenience service methods in the SDK to expose this feature as a separate API. Take into consideration:
- The feedback we get from the UX Studies.
- Feedback from architects.

**Comment by jsquire** [comment]
Closing in favor of #28067.
