### ISSUE TITLE
Insights - /metrics endpoint - timeGrain - inconsistently required parameter

### ISSUE THREAD

**Issue by solvingj** [Azure/azure-sdk-for-net#2330]
When querying the /metrics endpoint for a database (and some other resource types), timeGrain is not a required parameter. 

When querying the /metrics endpoint of a web app, if one omits "timeGrain" in the query, Azure returns the following: 

> code=500, message=Internal Server Error

It would be preferable for many use cases if the timeGrain parameter was made optional across the board.  This would reduce the number of API calls necessary to batch collect metric values in many cases.  

Note: This is a problem with the API and not the SDK.

**Comment by solvingJ** [comment]
It seems that DocumentDB suffers the same required parameter, however provides a bit more detailed error message (although it still doesn't tell you what's missing... I think the storage API queries tell you whats missing specifically): 

> INFO: {"code":"BadRequest","message":"Failed to parse query startTime eq 2016-09-08T20:26:50.398Z and endTime eq 2016-09-08T20:31:50.398Z\r\nActivityId: 57b62c10-f16a-4385-bccc-a59e41aca548"}

Once I added the timegrain to the query, I got a successful result.

**Comment by markcowl** [comment]
@asheniam can you take a look at this API request?

**Comment by adrianhall** [comment]
Can you please confirm this is still an issue?  If it is, please can you provide more information on the current state, including any .NET libraries (and their version) in use?
