### ISSUE TITLE
[Tables] GetPropertiesReturnsProperties failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23317]
Tables nightly test runs are failing with:

> Error message
> Expected: True
> But was:  False
> 
> 
> Stack trace
>    at Azure.Data.Tables.Tests.TableServiceClientLiveTests.CompareServiceProperties(TableServiceProperties expected, TableServiceProperties actual) in D:\a\_work\1\s\sdk\tables\Azure.Data.Tables\tests\TableServiceClientLiveTests.cs:line 325
>    at Azure.Data.Tables.Tests.TableServiceClientLiveTests.<GetPropertiesReturnsProperties>d__7.MoveNext() in D:\a\_work\1\s\sdk\tables\Azure.Data.Tables\tests\TableServiceClientLiveTests.cs:line 311
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1044718&view=results

@jsquire for notification.

**Comment by christothes** [comment]
transient service issue
