### ISSUE TITLE
[Synapse] QuerySessions failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23318]
Synapse nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 500 (Internal Server Error)
> 
> Content:
> {"code":"InternalServerError","message":"Context creation failure for session=f1848e81-7c78-47ee-9d6c-054d76cf01f3","target":null,"details":null,"error":null}
> 
> Headers:
> Cache-Control: no-cache
> Pragma: no-cache
> Server: Microsoft-IIS/10.0,Microsoft-HTTPAPI/2.0
> Strict-Transport-Security: REDACTED
> x-ms-correlation-request-id: REDACTED
> X-Content-Type-Options: REDACTED
> X-Powered-By: REDACTED
> x-ms-failure-cause: REDACTED
> x-ms-request-id: 22a6c866-5e52-4da3-afa2-ce8372936198
> x-ms-client-request-id: 020422d2-c932-4ee9-8f58-d6221599910c
> Date: Fri, 06 Aug 2021 19:18:10 GMT
> Content-Length: 158
> Content-Type: application/json; charset=utf-8
> Expires: -1
> 
> 
> Stack trace
>    at Azure.Analytics.Synapse.Artifacts.DataFlowDebugSessionRestClient.DeleteDataFlowDebugSessionAsync(DeleteDataFlowDebugSessionRequest request, CancellationToken cancellationToken) in /_/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/DataFlowDebugSessionRestClient.cs:line 268
>    at Azure.Analytics.Synapse.Artifacts.DataFlowDebugSessionClient.DeleteDataFlowDebugSessionAsync(DeleteDataFlowDebugSessionRequest request, CancellationToken cancellationToken) in /_/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/DataFlowDebugSessionClient.cs:line 109
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 165
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.DisposableDataFlowDebugSession.DisposeAsync() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/DataFlowDebugSessionClientLiveTests.cs:line 51
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.QuerySessions() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/DataFlowDebugSessionClientLiveTests.cs:line 103
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.QuerySessions() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/DataFlowDebugSessionClientLiveTests.cs:line 103
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1036635&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Given the age of this issue, closing this as stale.  If tests are still failing, please file a new issue.
