### ISSUE TITLE
[Container Registry] CanGetTagsStartingMidCollection(True) failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23314]
Container Registry nightly test runs are failing with:

> Error message
> System.InvalidOperationException : The requested operation requires an element of type 'Array', but the target element has type 'Null'.
> 
> 
> Stack trace
>    at System.Text.Json.JsonElement.EnumerateArray()
>    at Azure.Containers.ContainerRegistry.TagList.DeserializeTagList(JsonElement element) in /_/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Generated/Models/TagList.Serialization.cs:line 37
>    at Azure.Containers.ContainerRegistry.ContainerRegistryRestClient.GetTagsNextPageAsync(String nextLink, String name, String last, Nullable`1 n, String orderby, String digest, CancellationToken cancellationToken) in /_/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Generated/ContainerRegistryRestClient.cs:line 1314
>    at Azure.Containers.ContainerRegistry.RegistryArtifact.<>c__DisplayClass25_0.<<GetTagPropertiesCollectionAsync>g__NextPageFunc|1>d.MoveNext() in /_/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Artifact/RegistryArtifact.cs:line 259
> --- End of stack trace from previous location ---
>    at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() in /_1/microsoft.azure.autorest.csharp/3.0.0-beta.20210805.1/content/Generator.Shared/PageableHelpers.cs:line 56
>    at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.CanGetTagsStartingMidCollection(Boolean anonymous) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/RegistryArtifactLiveTests.cs:line 224
>    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.CanGetTagsStartingMidCollection(Boolean anonymous) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/RegistryArtifactLiveTests.cs:line 224
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1043166&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Closing; if tests continue to fail, test run monitoring will generate a new issue for tracking.
