### ISSUE TITLE
CosmosDB: do we have any API to do bulk update 

### ISSUE THREAD

**Issue by sachin-agarwal-by** [Azure/azure-sdk-for-net#23313]
[Do we have any api like ReplaceItemStreamAsync where I can pass list of object and can update in document db]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea7e89f-fd6a-f414-aa63-15147f73c54b
* Version Independent ID: 7cb94820-e98a-ddf2-ad16-4c9a4f6ad03e
* Content: [Container.ReplaceItemStreamAsync(Stream, String, PartitionKey, ItemRequestOptions, CancellationToken) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.replaceitemstreamasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by sachin-agarwal-by** [comment]
@ealsur I have raised my question here and closed another thread , can you please help.

**Comment by ealsur** [comment]
The answer is no, Replace operations are for 1 document. This is a documentation for the ReplaceItem API.

**Comment by sachin-agarwal-by** [comment]
thanks.. but just wanted to know the difference if I can use ReplaceItem opeartion in multiple threaded way like Task.Add(ReplaceItem) like this and anther is using BulkMode as u suggested so what is the difference

**Comment by ealsur** [comment]
You can use ReplaceItem in concurrent tasks with or without Bulk. When Buk is off, each Task will be an independent network request. When Bulk is on, then the SDK will optimize it and group related network requests. It's explained here https://devblogs.microsoft.com/cosmosdb/introducing-bulk-support-in-the-net-sdk/#wait-what-is-happening-with-those-tasks
