### ISSUE TITLE
[BUG] two copies of PiiDetectionSkillMaskingMode.cs varying only by case are present

### ISSUE THREAD

**Issue by idg10** [Azure/azure-sdk-for-net#23320]
**Describe the bug**
As of https://github.com/Azure/azure-sdk-for-net/commit/2789b52daa4f16d0ad97235cad18d644d74f7c8c the repo contains both this:

`sdk/search/Azure.Search.Documents/src/Generated/Models/PIIDetectionSkillMaskingMode.cs`

and this:

`sdk/search/Azure.Search.Documents/src/Generated/Models/PiiDetectionSkillMaskingMode.cs`

Note that the first three letters of the file vary only by case. (`PII` vs `Pii`.)

It looks like after updating Autorest, the name of this generated file changed the casing, but I believe these are logically meant to be the same file.

**Expected behavior**
There should be just one copy of this file, probably cased as `PiiDetectionSkillMaskingMode.cs` (i.e., the `PIIDetectionSkillMaskingMode.cs` copy should have been deleted when the one starting `Pii` was added).

**Actual behavior (include Exception or Stack Trace)**
Two copies of the file with different casing are present.

**To Reproduce**
This is most easily seen by cloning the repo in Windows, which will produce this warning:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'sdk/search/Azure.Search.Documents/src/Generated/Models/PIIDetectionSkillMaskingMode.cs'
  'sdk/search/Azure.Search.Documents/src/Generated/Models/PiiDetectionSkillMaskingMode.cs'
```

**Environment:**
GitHub. (The problem is in the repo.)

**Comment by jsquire** [comment]
//fyi:  @christothes

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
