### ISSUE TITLE
Lacking of interface for SecretClient

### ISSUE THREAD

**Issue by dxynnez** [Azure/azure-sdk-for-net#23335]
**Query/Question**
Hi team, 

We are migrating from the legacy KeyVault client to the new SecretClient and found out that, unlike the IKeyVaultClient, the new SecretClient doesn't have any abstraction which makes it pretty hard to unit-test our components that depends on it. Is there any plan to add an interface in the future? If not, what would be the right approach to unit-test the components that directly depends on the SecretClient? Thanks.

**Comment by jsquire** [comment]
Hi @dxynnez.  Thank you for your feedback.   Support for mocking and unit testing is one of the core goals of the new Azure SDKs, and the details of the approach that we use are discussed in the [Azure SDK Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking).  

All of the public members of the client types are `virtual` or settable, the class is not sealed, and a parameterless constructor is available to ensure that it is usable with a mocking library such as Moq or FakeItEasy.   For model types that are returned by service operations, a factory class exists to enable creating them for testing.  In this case, the [SecretModelFactory](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/SecretModelFactory.cs) is likely of interest.

With respect to the lack of interfaces, the Azure SDKs have a goal of strict backwards compatibility with a very high bar for any breaking changes.  With that in mind, the use of an interface makes evolving over time difficult; any change to the public API surface becomes a breaking change, including adding new members.  While default interface implementation makes this easier, they're not supported in all of the frameworks that we target.  As a result, we intentionally avoid using interfaces outside of special circumstances.

For more discussion and details around unit testing and mocking the Azure SDKs, I'd recommend [this](https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/) post from the Azure SDK blog.

I'm going to mark this as addressed, but please feel free to use the "`/unresolve`" command should you wish to discuss further.

**Comment by dxynnez** [comment]
Thanks @jsquire ! It was my bad didn't look into the code carefully, now that makes sense as all the public APIs are virtual.

Just out of curiosity - what do you mean by 'the use of an interface makes evolving over time difficult; any change to the public API surface becomes a breaking change, including adding new members'? My take is now all the virtual APIs become the contract and any change to the API signature would still become a breaking change. Could you elaborate a bit more on how would not using interfaces mitigate such problem? Thanks!

**Comment by heaths** [comment]
We will not change method signatures. As needed, we will add overloads or new members.

You can't add members to an interface. That's a breaking change for anyone who implemented it, which they might've done for mocking. Creating derivative or completely new interfaces becomes burdensome for mocking as well, and of unnecessary when using virtual methods like we do now.
