### ISSUE TITLE
[BUG] ComplexType field with Facets throwing Azure.Core.dll errors during Document.Search 

### ISSUE THREAD

**Issue by KevinPoorDeveloper** [Azure/azure-sdk-for-net#23331]
With this (partial) index in Azure Cognitive Search:
```
    {
      "name": "tagdata",
      "type": "Collection(Edm.ComplexType)",
      "analyzer": null,
      "synonymMaps": [],
      "fields": [
        {
          "name": "tagid",
          "type": "Edm.Int32",
          "facetable": true,
          "filterable": true,
          "retrievable": true,
          "sortable": false,
          "analyzer": null,
          "indexAnalyzer": null,
          "searchAnalyzer": null,
          "synonymMaps": [],
          "fields": []
        },
        {
          "name": "tag",
          "type": "Edm.String",
          "facetable": true,
          "filterable": true,
          "key": false,
          "retrievable": true,
          "searchable": false,
          "sortable": false,
          "analyzer": null,
          "indexAnalyzer": null,
          "searchAnalyzer": null,
          "synonymMaps": [],
          "fields": []
        }
      ]
    },
```
And a varchar(2000, null) field in SQL Server that contains the following (along with some null rows):
{"tagdata":[{"tagid":200,"tag":"text1"},{"tagid":84,"tag":"text2"},{"tagid":1785,"tag":"text3"}

We are getting random errors with this code:
`SearchResults<SearchDocument> response = client.Search<SearchDocument>("test", null);`

We cannot step into the code, they are being thrown on that line. The majority of the errors (tens or hundreds of them) are like this:
```
Exception thrown: 'System.Text.Json.JsonException' in Azure.Core.dll
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonException' in Azure.Core.dll
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll
Exception thrown: 'System.Text.Json.JsonException' in Azure.Core.dll
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll
```

I also have seen a few "error working with GeoJSON"  - this field has nothing to do with GeoJSON but that doesn't reliably throw an error. This has got to be a bug? We've tried everything, the errors stop if we remove that field from the index and rebuild it.

**Comment by Mohit-Chakraborty** [comment]
Thank you for your reporting the issue.  I will take a look.

**Comment by KevinPoorDeveloper** [comment]
I wanted to also mention that switching to the Newtonsoft JSON serializer as described [here](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.core.newtonsoftjson-readme) also "fixed" the problem.

**Comment by Mohit-Chakraborty** [comment]
That is good to know. Glad you are unblocked and thanks for sharing a solution.
