### ISSUE TITLE
Azure Tables client library for .NET doc needs track 2 update

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-sdk-for-net#23338]
The following doc is currently returned as the top search result when googling "Azure Tables SDK":

https://docs.microsoft.com/en-us/dotnet/api/overview/azure/data.tables-readme-pre

The doc is referring to the prerelease version of the library, which could confuse customers into believing that the libraries are not yet GA. 

At minimum, the doc needs to be updated to include a big bold call out at the top stating that the libraries are now GA and directing users to the GA announcement page for the new libraries.

**Comment by jsquire** [comment]
@danieljurek:   This looks to be another case of the main navigation node still referencing the `-pre`  README.   Would you be so kind as to assist?

![image](https://user-images.githubusercontent.com/913445/129600210-118ced91-d49e-4604-a817-5df690d86512.png)
![image](https://user-images.githubusercontent.com/913445/129600236-840f4efc-ebc7-4567-8eb5-924d75452fa4.png)

**Comment by danieljurek** [comment]
I have a PR to update the ToC: https://github.com/Azure/azure-docs-sdk-dotnet/pull/2066/files 

We should automate this process as well to help users more readily find the GA docs: https://github.com/Azure/azure-sdk-tools/issues/2005
