### ISSUE TITLE
Telemetry for when using Event Grid Blob Trigger vs Blob Trigger

### ISSUE THREAD

**Issue by cachai2** [Azure/azure-sdk-for-net#23344]
Currently, it is difficult for customers to determine when they are using the Event Grid Blob Trigger vs the standard Blob Trigger. We should add some additional telemetry specifying to customers which trigger is executing.

**Comment by fabiocav** [comment]
@anatoliB would you be able to triage/assign this item?

**Comment by AnatoliB** [comment]
> @AnatoliB would you be able to triage/assign this item?

Yes, thank you
