### ISSUE TITLE
Design the DocumentFilterProperties type

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#23353]
Currently, the usage looks like this: 
```
var filter = new TranslationFilter
{
    OrderBy = { new TranslationFilterOrder(property: TranslationFilterProperty.CreatedOn, asc: false) }
};
```

The architects are asking if it will be worth just removing the `asc` parameters and instead modify the `TranslationFilterProperty` to have `CreatedOn`, and `CreatedOnDescending`, so the user will do:
```
var filter = new TranslationFilter
{
    OrderBy = { new TranslationFilterOrder(property: TranslationFilterProperty.CreatedOnDescending) }
};
```

Making the change means that every time a value is added to the `TranslationFilterProperty`, we will need to add 2 properties to the type. Also, will it be confusing to have only `CreateOn`? or should we say `CreatedOnAscending`?

I personally like the approach we currently have, but open to other people's feedback

**Comment by ZulaMostafa** [comment]
I like the approach we currently have too. However, If we will modify it to have `CreateOn` and `CreatedOnDescending`. I believe it's better to rename `CreateOn` to `CreatedOnAscending` to be more clear.

**Comment by maririos** [comment]
>However, If we will modify it to have CreateOn and CreatedOnDescending. I believe it's better to rename CreateOn to CreatedOnAscending to be more clear.

You don't have to make the change if you don't agree with it :) .We can definitely leave it as is in terms of design.
The only ask for a PR will be to rename the parameter `asc` to `ascending` in the `TranslationFilterOrder` constructor

**Comment by ZulaMostafa** [comment]
It's just my opinion, I can change it if it's for the better.
