### ISSUE TITLE
kind attribute missing from generated Site.cs

### ISSUE THREAD

**Issue by jcurlier** [Azure/azure-sdk-for-net#2335]
I am getting the SiteCollection using:
**SiteCollection sites = await webSiteClient.Sites.GetSitesAsync("MyResourceGroup");**

It seems that the Site data object is missing the _kind_ attribute.
[/MyResourceGroup/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/Site.cs](https://github.com/Azure/azure-sdk-for-net/blob/6fb0342e898a9f0e5df2c3c9aa84328881414da7/src/MyResourceGroup/WebSite/Microsoft.Azure.Management.Websites/Generated/Models/Site.cs)

When using the Rest API, I am getting the kind attribute:

```
{
  "value": [
    {
      "id": "/subscriptions/060a50f.../resourceGroups/.../providers/Microsoft.Web/sites/w...",
      "name": "website2016...",
      "type": "Microsoft.Web/global",
      "kind": "mobileApp",
      "location": "South Central US",
```

Thanks

**Comment by demali** [comment]
It would be great it if this attribute gets added as it would help filter out _Mobile Apps_ from other _Web Apps._

**Comment by markcowl** [comment]
@naveedaz Can you take a look?

**Comment by naveedaz** [comment]
This is fixed now in the latest SDK version.  [https://www.nuget.org/packages/Microsoft.Azure.Management.Websites/1.5.0-preview](url).


[https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/WebSites/Microsoft.Azure.Management.Websites/Generated/Models/Site.cs#L38](url)

[https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/WebSites/Microsoft.Azure.Management.Websites/Generated/Models/Resource.cs#L66](url)
