### ISSUE TITLE
Insights - /metrics - DocumentDb - Metric Filter Parameter Issues

### ISSUE THREAD

**Issue by solvingj** [Azure/azure-sdk-for-net#2336]
The "Consistency Level" metric only has two availabilities "PT1H" and "PT1D".  All other DocumentDB metrics have one additional availability: "PT5M".  This shouldn't be an issue, but it is. 

Currently,  one must specify both a "timeGrain" and one or more "field names" (name.value eq ... ) in the $filter of an API call to get metric values.  If not for Consistency Level, I suspect this would not be required. 

Moving forward, it would be preferable if only startTime and endTime were required (as is the case with SQL Database metrics).  If not possible, then it would be preferable if startTime, endTime and timeGrain were required (as is the case with web app metrics). 

As it is today, to retreive all metric values of PT5M timegrain for a DocDB, there are two options: 
1.  Make one API call for each field, with a single name filter:  "...name.value eq 'Total Requests'"
2.  Make a single API call for all fields, by creating a long filter string that includes all field names:   "...(name.value eq 'Total Requests' or name.value eq 'Http 2xx' or .... etc.) " 

These are both highly inefficient.  It's worth noting that I tried using the "Not equal" filter (name.value ne 'Consistency Level'), but it returns "bad request". 

I imagine that the intention is for a query featuring just the timeGrain to return all metric values that have that timegrain, and simply omitting the metrics which don't have that timegrain.  If so, it's a simple bug and fixing it will resolve this issue.  However, I could be wrong, and if so, please advise. 

In any case, a working "Not Equal" (ne) filter operator would have minimized the inconvenience of issue, and provided a much more efficient workaround. 

Finally, when using the powerhsell module, I discovered that it's impossible to retrieve the PT1H and PT1D metrics no matter how you filter.  You can only get them for Consistency Level.  It's probably a related side-effect, and will be fixed when the metric filtering is next updated.  However, please let me know if I should open this as a ticket on the powershell module project instead. 

```
$endTime = Get-Date
$startTime = $endTime.AddMinutes(-20)
$timeGrain = New-TimeSpan -Hours 1
$metricNames = 'Total Requests'
$subsId = 'subscriptionidhere'
$rgId = 'resourcegroupnamehere'
$provider = 'Microsoft.DocumentDb'
$type = 'databaseAccounts'
$resourceName = 'databaseName'
$metricNames = 'Total Requests'
Get-AzureRmMetric -ResourceId $resourcePath -TimeGrain $timeGrain -DetailedOutput -StartTime $startTime -EndTime $endTime -MetricNames $metricNames
```

If you replace 'Total Requests' with 'Consistency Level' it works.

**Comment by markcowl** [comment]
@asheniam can you take  alook?

**Comment by adrianhall** [comment]
Given that DocumentDb has been removed in favor of Cosmos, and the SDK has moved forward, can you please confirm this is still an issue?  If so, please provide more details on the problem, including all .NET libraries and their versions.
