### ISSUE TITLE
[BUG] ConsumptionManagementClient is using outdated apiVersion making request to fail

### ISSUE THREAD

**Issue by plaramee1** [Azure/azure-sdk-for-net#23371]
**Describe the bug**
ConsumptionManagementClient is using outdated apiVersion (2018-01-31)for your latest release making request failing with message : Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01

**Expected behavior**
using newer api version so request will work

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.Consumption 3.0.2
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Framework 4.8
 - IDE and version : VisualStudio 2017 (15.9.25)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
route to service team to see if need a new version SDK on latest API version

**Comment by thiagocamargos** [comment]
Hi,

We would like to use the updated version of .net sdk for consumption.
Is there a timeline for a new release, or has this package been dropped/replaced?
