### ISSUE TITLE
unwrapkey support in Azure.Security.KeyVault.Keys

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-sdk-for-net#23384]
**Library or service name.**
Azure.Security.KeyVault.Keys
 
**Is your feature request related to a problem? Please describe.**
User is asking unwrapkey support in PowerShell
https://github.com/Azure/azure-rest-api-specs/blob/5b604aa492a2590ec6d0b028379becdd47b6ee80/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.2/keys.json#L753

https://github.com/Azure/azure-powershell/issues/15679

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
This is already supported in the `Azure.Security.KeyVault.Keys.Cryptography.CryptographyClient` within the _Azure.Security.KeyVault.Keys_ package already. The [issue](Azure/azure-powershell#15679) you opened would be the place to track a request for support from the Az PowerShell module.

I'm going to mark this issue as addressed, but please feel free to use the `/unresolve` command should you wish to discuss further.

**Comment by BethanyZhou** [comment]
Thank you @heaths for the information. Found the feature in the `Azure.Security.KeyVault.Keys.Cryptography.CryptographyClient`. Please feel free to close this issue.
