### ISSUE TITLE
[QUERY] Code generation script, GithubBranchName after main branch rename

### ISSUE THREAD

**Issue by audunn** [Azure/azure-sdk-for-net#23389]
**Query/Question**
Hi, I am looking for but cannot find information on where Start-AutoRestCodeGeneration (generate.ps1) gets the branch name from. We are having issues since the branch name change. Running generate.ps1 to generate a new version our SDK and we seem to be targeting master rather than main  `GithubBranchName = "master";`.

Is there some config we need to update to pull from main rather than master?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by ShivangiReja** [comment]
@pakrym do you have any information on where `generate.ps1` script gets the branch name from?

**Comment by ShivangiReja** [comment]
CC: @chidozieononiwu

**Comment by pakrym** [comment]
https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/Mgmt.CI.BuildTools/NugetToolsPackage/CI.Tools.Package/build/psModules/CodeGenerationModules/AutoRestCodeGenerationModule/AutoRestCodeGenerationModule.psm1#L307 


master seems to be the default:

https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/Mgmt.CI.BuildTools/NugetToolsPackage/CI.Tools.Package/build/psModules/CodeGenerationModules/AutoRestCodeGenerationModule/AutoRestCodeGenerationModule.psm1#L425

**Comment by audunn** [comment]
Indeed that works thank you very much. 

Perhaps the readme could include this bit of info to make it easier to find, that is if it does not already but at least U did not find it?

My generate.ps1 that now works on main is:
`Start-AutoRestCodeGeneration -ResourceProvider "netapp/resource-manager" -AutoRestVersion "v2" -SpecsRepoBranch "main" -AutoRestCodeGenerationFlags "--use:@microsoft.azure/autorest.csharp@2.3.90"`

**Comment by pakrym** [comment]
@weshaggard, is that module something we want to update as part of M2M migration?

**Comment by weshaggard** [comment]
This was owned by @allenjzhang but I think @yungezz's team now owns this so I will leave it up to them if they want to update it.

**Comment by yungezz** [comment]
hi @HarveyLink could you help on this? thanks.

**Comment by HarveyLink** [comment]
Quick fix https://github.com/Azure/azure-sdk-tools/pull/1928
