### ISSUE TITLE
[QUERY]: Azure Storage needed for azure logic apps

### ISSUE THREAD

**Issue by stepro71** [Azure/azure-sdk-for-net#23383]
Hi, I was referred to this from the dapr team. I want to use azure logic apps locally without the requirement for azure storage to store the workflows. Is this possible? How do I get started with this?

**Comment by jsquire** [comment]
Hi @stepro71.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, your inquiry is focused on Logic Apps which isn't something that we're able to assist with.   To ensure that the right folks are able to help, I've transferred this to the Logic Apps repository as [#356](https://github.com/Azure/logicapps/issues/356).
