### ISSUE TITLE
VirtualMachineExtension with CustomScriptExtension  Api 13.0.4

### ISSUE THREAD

**Issue by johnrsierra** [Azure/azure-sdk-for-net#2339]
**Using API 'Microsoft.Azure.Management.Compute' 13.0.4-prerelease**

When I am creating a virtual machine with custom script extensions I am getting the following error:

> {
>   "startTime": "2016-09-09T15:24:59.3347541+00:00",
>   "endTime": "2016-09-09T15:25:38.2890993+00:00",
>   "status": "Failed",
>   "error": {
>     "code": "VMExtensionProvisioningError",
>     "message": "VM has reported a failure when processing extension 'UpdateVmServices'. Error message: \"Invalid handler configuration. Exiting. Error Message: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. \"."
>   },
>   "name": "8173d843-239c-48cb-8310-d6e58fe37112"
> }
## **When the code is:**

> using (var computeManagementClient = new ComputeManagementClient(azureCredential.TokenCredential))
>             {
>                 computeManagementClient.SubscriptionId = virtualMachineExtensionConfiguration.SubscriptionId;
>                 await computeManagementClient.VirtualMachineExtensions.CreateOrUpdateAsync(
>                 virtualMachineExtensionConfiguration.GroupName,
>                 virtualMachineExtensionConfiguration.VirtualMachineName,
>                 virtualMachineExtensionConfiguration.Name,
>                 new VirtualMachineExtension
>                                 (
>                                 location: virtualMachineExtensionConfiguration.Location,
>                                 type: "Microsoft.Compute/virtualMachines/extensions"
>                                 )
>                 {
>                     VirtualMachineExtensionType = "CustomScriptExtension",
>                     Tags = new Dictionary<string, string>() { { "displayName", "DName" } },
>                     Publisher = "Microsoft.Compute",
>                     TypeHandlerVersion = "1.7",
>                     AutoUpgradeMinorVersion = false,
>                     Settings = @"{""commandToExecute"" : ""powershell -ExecutionPolicy Unrestricted -Command SetX /M EnvironmentVariable envValue"" }"
>                 });
>             }

In Virtual Machine the logs are: 

**C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.7\RuntimeSettings\0.settings**

`{
  "runtimeSettings": [
    {
      "handlerSettings": {
        "publicSettings": "{\"commandToExecute\" : \"powershell -ExecutionPolicy Unrestricted -Command SetX /M EnvironmentVariable envValue\" }"
      }
    }
  ]
}`

**C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.7\Status\0.status**

`[{"status":{"code":3,"formattedMessage":{"lang":"en-US","message":"Invalid handler configuration. Exiting. Error Message: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. "},"name":"CustomScriptHandler","operation":"Exiting","status":"error","substatus":null},"timestampUTC":"\/Date(1473453990452)\/","version":"1"}]`
## **When the code is:**

> using (var computeManagementClient = new ComputeManagementClient(azureCredential.TokenCredential))
>             {
>                 computeManagementClient.SubscriptionId = virtualMachineExtensionConfiguration.SubscriptionId;
>                 await computeManagementClient.VirtualMachineExtensions.CreateOrUpdateAsync(
>                 virtualMachineExtensionConfiguration.GroupName,
>                 virtualMachineExtensionConfiguration.VirtualMachineName,
>                 virtualMachineExtensionConfiguration.Name,
>                 new VirtualMachineExtension
>                                 (
>                                 location: virtualMachineExtensionConfiguration.Location,
>                                 type: "Microsoft.Compute/virtualMachines/extensions"
>                                 )
>                 {
>                     VirtualMachineExtensionType = "CustomScriptExtension",
>                     Tags = new Dictionary<string, string>() { { "displayName", "DName" } },
>                     Publisher = "Microsoft.Compute",
>                     TypeHandlerVersion = "1.7",
>                     AutoUpgradeMinorVersion = false,
>                     Settings = new {
>                                 CommandToExecute = "powershell -ExecutionPolicy Unrestricted -Command SetX /M EnvironmentVariable envValue"
>                      }
>                 });
>             }

In Virtual Machine the logs are: 

**C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.7\RuntimeSettings\0.settings**

`{
  "runtimeSettings": [
    {
      "handlerSettings": {
        "publicSettings": "{ }"
      }
    }
  ]
}`

**C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.7\Status\0.status**

`[{"status":{"code":3,"formattedMessage":{"lang":"en-US","message":"Invalid handler configuration. Exiting. Error Message: VM has reported a failure when processing extension 'UpdateVmServices'. Error message: \"Invalid Configuration - CommandToExecute is not specified in the configuration; it must be specified in either the protected or public configuration section\". "},"name":"CustomScriptHandler","operation":"Exiting","status":"error","substatus":null},"timestampUTC":"\/Date(1473453990452)\/","version":"1"}]`
## **When the code is:**

> using (var computeManagementClient = new ComputeManagementClient(azureCredential.TokenCredential))
>             {
>                 computeManagementClient.SubscriptionId = virtualMachineExtensionConfiguration.SubscriptionId;
>                 await computeManagementClient.VirtualMachineExtensions.CreateOrUpdateAsync(
>                 virtualMachineExtensionConfiguration.GroupName,
>                 virtualMachineExtensionConfiguration.VirtualMachineName,
>                 virtualMachineExtensionConfiguration.Name,
>                 new VirtualMachineExtension
>                                 (
>                                 location: virtualMachineExtensionConfiguration.Location,
>                                 type: "Microsoft.Compute/virtualMachines/extensions"
>                                 )
>                 {
>                     VirtualMachineExtensionType = "CustomScriptExtension",
>                     Tags = new Dictionary<string, string>() { { "displayName", "DName" } },
>                     Publisher = "Microsoft.Compute",
>                     TypeHandlerVersion = "1.7",
>                     AutoUpgradeMinorVersion = false,
>                     Settings = JsonConvert.SerializeObject
>                                   (new
>                               {
>                                   CommandToExecute = "powershell -ExecutionPolicy Unrestricted -Command SetX /M EnvironmentVariable envValue"
>                               }
>                     )
>                 });
>             }

In Virtual Machine the logs are: 

**C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.7\RuntimeSettings\0.settings**

`{
  "runtimeSettings": [
    {
      "handlerSettings": {
        "publicSettings": "{\"commandToExecute\" : \"powershell -ExecutionPolicy Unrestricted -Command SetX /M EnvironmentVariable envValue\" }"
      }
    }
  ]
}`

**C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.7\Status\0.status**

`[{"status":{"code":3,"formattedMessage":{"lang":"en-US","message":"Invalid handler configuration. Exiting. Error Message: Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. "},"name":"CustomScriptHandler","operation":"Exiting","status":"error","substatus":null},"timestampUTC":"\/Date(1473453990452)\/","version":"1"}]`

It seems if the Json parser has taken the backslashes of the quotes and passing them literally to the extension script to be excecuted.

On the previous version of the Api **'Microsoft.Azure.Management.Compute' (9.1.0)** this problem did not happend

**Comment by markcowl** [comment]
@sighkays can you take a look

**Comment by singhkays** [comment]
@hyonholee can you take a look at this?

**Comment by adrianhall** [comment]
Is this still an issue with the latest version of the library?
