### ISSUE TITLE
[BUG] GenerateSasUri fails when TableClient is created with ConnectionString

### ISSUE THREAD

**Issue by GoradeAarti** [Azure/azure-sdk-for-net#23404]
I am trying to GenerateSasUri by creating TableClient directly with ConnectionString and it says - SharedkeyCredential is Null.
looks like a hard dependency on SharedkeyCredential to generate SasUri.

I am able to generate SasUri only when I create TableClient with constructor where tableSharedKeyCredential is input e.g. (endpoint, tableName, tableSharedKeyCredential) and tableSharedKeyCredential needs AccountKey as input 

Sample code which throws error for 'SharedkeyCredential' is Null:

```csharp
var tableClient = new TableClient(connectionString, tableName);
var sasUri = tableClient.GenerateSasUri(
                TableSasPermissions.All,
                new DateTime(2040, 1, 1, 1, 1, 0, DateTimeKind.Utc));
```

I expected to work with TableClient object created with ConnectionString directly

**Environment:**
 - Name and version of the Library package used: Azure.Data.Tables (12.0.1)
 - Hosting platform or OS and .NET runtime version : Windows 10 .NET Framework 4.7.2
 - IDE and version : Visual Studio 16.9.10

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
