### ISSUE TITLE
Insights - /metrics - DocumentDb - One Metric Name Crashes Query

### ISSUE THREAD

**Issue by solvingj** [Azure/azure-sdk-for-net#2340]
Some change occurred last night and now a query to the DocumentDB metrics returns an error.  My tests ran successfully yesterday, but they are failing.  I've isolated it down to the following: 

If the filter parameter:  "name.value eq Service Availability"  is present, the query will crash.  If I remove it, the query is successful.  

Here is a filter string which crashes the request: 

> "startTime eq 2016-09-10T22:49:41.374Z and endTime eq 2016-09-10T22:55:41.374Z and timeGrain eq duration'PT5M' and (name.value eq 'Total Requests' or name.value eq 'Service Availability')"

Here is the trace Error:

> {"message":"Failed to get a response from the server. TraceId:{26a0547b-d972-44bb-88a2-8e9ac8b809c3}, Url:https://prod2.metrics.nsatc.net/api/flight/dq/batchedReadv3/monitoringAccount/DocumentDB/metricNamespace/DocDB/metric/OverallRequestAvailability?SamplingType=Availability&startTime=1473547781374&endTime=1473548141374&includeSeries=True&reducer=Average&seriesAggregationType=Min&seriesResolution=300000&noFilter=true, HandlingServer:prod2_east-prod2_Metrics.Server_IN_2 Stage:ValidateStatus, LatencyMs:0, ResponseStatus:NotFound, Response:[TraceId={26a0547b-d972-44bb-88a2-8e9ac8b809c3}] No possible dimension values found for this input.  Please review your query and try again. ","code":"Internal Server Error"}

Here is a working filter string, where the only difference is that I've replaced:
This:             name.value eq 'Service Availability'
With this:        name.value eq 'Service Unavailable'
(Service Unavailable is just another metric)

> "startTime eq 2016-09-10T22:57:50Z and endTime eq 2016-09-10T23:03:50Z and timeGrain eq duration'PT5M' and (name.value eq 'Total Requests' or name.value eq 'Service Unavailable')"

Here is the metric definition for "Service Availability", verifying that it exists and should have PT5M timeGrain.: 

{
    "metricAvailabilities" : [{
            "timeGrain" : "PT5M",
            "retention" : "P2D"
        }, {
            "timeGrain" : "PT1H",
            "retention" : "P14D"
        }, {
            "timeGrain" : "P1D",
            "retention" : "P60D"
        }
    ],
    "primaryAggregationType" : "Average",
    "unit" : "Percent",
    "resourceUri" : "myresourceuri",
    "name" : {
        "value" : "Service Availability",
        "localizedValue" : "Service Availability"
    }
}

**Comment by markcowl** [comment]
@asheniam can you take a look?

**Comment by adrianhall** [comment]
Given the age of this issue, I suspect it is no longer an issue.  Could you confirm that this is the case?  If not, please provide the current state of the issue, along with all .NET libraries (and versions) in use?
