### ISSUE TITLE
Typo on the page

### ISSUE THREAD

**Issue by YevgenBorodkin** [Azure/azure-sdk-for-net#23405]
Typo:
 Note that the**]** lease may be renewed even

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 53c6ebb5-1552-33ca-64d6-eb10a8497da4
* Version Independent ID: 1726ebae-6c9a-8347-4bcd-e15a404e0fac
* Content: [DataLakeLeaseClient.Renew(RequestConditions, CancellationToken) Method (Azure.Storage.Files.DataLake) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeleaseclient.renew?view=azure-dotnet#feedback)
* Content Source: [xml/Azure.Storage.Files.DataLake/DataLakeLeaseClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.DataLake/DataLakeLeaseClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@YevgenBorodkin Apologies for the delay. We have created a PR to fix this issue.
