### ISSUE TITLE
[QUERY] Azure Service Bus Sender Throttling 

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#23417]
**Query/Question**

I'm in the process of upgrading some client code from MS.Azure.ServiceBus to Azure.Messaging.ServiceBus. The code surrounding the previous SDK added a throttling behaviour of 5000 msg/s for all tiers. It has been claimed they have seen effects in the past on the premium tier even with 8 mu to be throttled when they surpassed that rate despite CPU and memory being fairly stable and below 50%. Now I wonder if I can replace the hard coded value with some better more dynamic behaviour or if this code is even still needed. If you could share some insights / ideas I would highly appreciate it 

**Environment:**
 - Name and version of the Library package used: Microsoft. Azure. ServiceBus 5.x (latest) 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): net5
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
//cc: @shankarsama

**Comment by jsquire** [comment]
Hi @danielmarbach.   Unless I'm misunderstanding, I believe that you're discussing service-throttling.   Assuming that I'm correct, I believe that Service Bus service team would be best able to assist.   

If I am misunderstanding, please let me know and I'll make the necessary corrections.

**Comment by danielmarbach** [comment]
@jsquire correct. I raised it here as well because maybe there is something in the SDK that I'm missing that could help too.

**Comment by jsquire** [comment]
> @jsquire correct. I raised it here as well because maybe there is something in the SDK that I'm missing that could help too.

There's nothing in the SDK itself that attempts to throttle or shape traffic.  Other than respecting the recommended back-off period when the service signals a throttle response, each `SendAsync` call translates to a service operation.

@JoshLove-msft:  Please keep me honest here;  am I overlooking any SB-specific logic?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft: Please keep me honest here; am I overlooking any SB-specific logic?

Nope, that all sounds correct to me.
