### ISSUE TITLE
[QUERY] If the creation record is not in the dnsZone/activity logs, does it mean it failed?

### ISSUE THREAD

**Issue by momoliu-msft** [Azure/azure-sdk-for-net#23421]
**Query/Question**
I do not see the creation record in the activity logs on Portal, but I see it was deleted successfully. How does that work? Is there any other way to check whether the creation succeeded or encountered any kind of issue?

The operation id of the delete is: b9bd814f-b344-4e42-abda-952591d07528

**Comment by momoliu-msft** [comment]
What would be suggested if the creation goes silently? It looks like there is no exception at all.

**Comment by jsquire** [comment]
Hi @momoliu-msft.   Thank you for reaching out and we regret that you're experiencing difficulties.    Unfortunately, I'm not able to determine which of the Azure SDKs you're asking about  from the context of your question.   Would you be so kind as to let us know which SDK you're using and provide more context for your scenario so that we can identify the right team members to assist?

#feedback

**Comment by momoliu-msft** [comment]
Hi Jesse, the version of "Microsoft.Azure.Management.Fluent" we are using is 1.25.0

**Comment by momoliu-msft** [comment]
Hi, Jesse, the version of the package "Microsoft.Azure.Management.Fluent" we are using is 1.25.0

**Comment by yungezz** [comment]
add @weidongxu-microsoft to help look at it.

**Comment by weidongxu-microsoft** [comment]
@momoliu-msft

What is your code, and whether it throws exception when fails to create the record? Any logging (https://github.com/Azure/azure-libraries-for-net#logging)?

PS: this SDK is going to be replaced by new SDKs that will appear here https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html

**Comment by momoliu-msft** [comment]
Here is our code for creation:
var dnsZone = await Azure.DnsZones.GetByResourceGroupAsync(TheResourceGroupName, OurDnsDomain);
await dnsZone
        .Update()
        .DefineARecordSet(dnsRecordName)
        .WithIPv4Address(frontend.GetPublicIPAddress().IPAddress)
        .WithMetadata(dnsVmIdMetadataKey, vmId)
        .WithMetadata(dnsEarliestDeleteMetadataKey, earliestDeleteTimeText)
        .Attach()
        .ApplyAsync();
// dnsRecordName is the subdomain we are trying to add.

There was no exception thrown and the execution continued just looked like the creation completed successfully until the service tried to connect to the "dnsRecordName.OurDnsDomain" and failed. Then we went to the Azure portal DNS zone/activity log to look for the creation record, it is not there. At the same time, it has a record for deletion.

**Comment by momoliu-msft** [comment]
Unfortunately, we do not have any logs that could be used to investigate this. We just started to see this recently and intermittently.

**Comment by weidongxu-microsoft** [comment]
This is probably a hard issue. From SDK's source code, if user code only calls `DefineARecordSet` (no `WithoutARecordSet`), SDK will never call DELETE to a record.

**Comment by momoliu-msft** [comment]
Sorry for the confusion. The delete action is called by the following code, I just want to say it could be deleted even though we did not get explicit indication saying that it was created successfully:

var dnsZone = await Azure.DnsZones.GetByResourceGroupAsync(TheResourceGroupName, OurDnsDomain);
var recordSetsApi = dnsZone.Manager.Inner.RecordSets;
await recordSetsApi.DeleteAsync(
                dnsZone.ResourceGroupName,
                dnsZone.Name,
                dnsRecordName,
                Microsoft.Azure.Management.Dns.Fluent.Models.RecordType.A);

**Comment by momoliu-msft** [comment]
Probably. what happened is that we failed to connect to it permanently. Any suggestions on how to monitor and investigate? currently, we still have this going on intermittently.

**Comment by weidongxu-microsoft** [comment]
@momoliu-msft 

I double checked, DELETE is success (status 204) even if the record is not there. So it is quite possible that the record is not created in the first place.

You may try 1.37.1, which could have some fix with response timeout.

Again, this SDK is in maintenance mode and probably getting deprecated soon. Please be prepared to migrate. @nickzhums

**Comment by lilyjma** [comment]
@momoliu-msft :  I'm assuming this issue has been resolved. Tagging it as so. Please feel free to let us know otherwise.
