### ISSUE TITLE
[Servicebus] PeekWithZeroTimeout failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23435]
Servicebus nightly test runs are failing with:

> Error message
> Expected: True
> But was:  False
> 
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.PeekWithZeroTimeout() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 68
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.PeekWithZeroTimeout() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 68
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.PeekWithZeroTimeout() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 68
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.PeekWithZeroTimeout() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 69
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass5_0.<RunTestOnSeparateThread>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1046940&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1051802&view=results

**Comment by JoshLove-msft** [comment]
This test was fixed in https://github.com/Azure/azure-sdk-for-net/pull/23356/files
