### ISSUE TITLE
[Servicebus]  Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusSessionsEndToEndTests.ServiceBusSessionQueue_SessionLocks failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23436]
Servicebus nightly test runs are failing with:

> Error message
> Expected: False
> But was:  True
> 
> 
> Stack trace
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusSessionsEndToEndTests.GetLogMessages(IHost host) in /mnt/vss/_work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusSessionsEndToEndTests.cs:line 305
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusSessionsEndToEndTests.ServiceBusSessionQueue_SessionLocks() in /mnt/vss/_work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusSessionsEndToEndTests.cs:line 231
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1051802&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Given the age of this issue, closing this as stale.  If tests are still failing, please file a new issue.
