### ISSUE TITLE
[Synapse] [Spark] Feature To Specify The Spark Config Attributes In SparkSessionOptions

### ISSUE THREAD

**Issue by reynoldspravindev** [Azure/azure-sdk-for-net#23433]
Currently the SparkSessionOptions does not have the feature to pass Spark config attributes when creating the Spark Session. But actual Synapse REST API allows that. Is this a feature that is already available in the SDK. The "Configuration" attribute in SparkSessionOptions is read -only.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by idear1203** [comment]
@reynoldspravindev Spark config is settable when creating Spark session. https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/synapse/Azure.Analytics.Synapse.Spark/src/Generated/Models/SparkSessionOptions.cs#L34 .

Code looks like below:
```csharp
var options = SparkSessionOptions(sessionName);
options.Configuration['key'] = 'value';
```
