### ISSUE TITLE
[Servicebus] UserCallbackThrowingCausesMessageToBeAbandonedIfNotSettled("DeadletterOverload") failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23439]
Servicebus nightly test runs are failing with:

> Error message
> Microsoft.Azure.Management.ServiceBus.Models.ErrorResponseException : Operation returned an invalid status code 'BadRequest'
> 
> 
> Stack trace
>    at Microsoft.Azure.Management.ServiceBus.QueuesOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String namespaceName, String queueName, SBQueue parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ServiceBus.QueuesOperationsExtensions.CreateOrUpdateAsync(IQueuesOperations operations, String resourceGroupName, String namespaceName, String queueName, SBQueue parameters, CancellationToken cancellationToken)
>    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
>    at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
>    at Azure.Messaging.ServiceBus.Tests.ServiceBusScope.CreateWithQueue(Boolean enablePartitioning, Boolean enableSession, Boolean forceQueueCreation, Nullable`1 lockDuration, String overrideNamespace, String caller) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Infrastructure/ServiceBusScope.cs:line 150
>    at Azure.Messaging.ServiceBus.Tests.Processor.ProcessorLiveTests.UserCallbackThrowingCausesMessageToBeAbandonedIfNotSettled(String settleMethod) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/ProcessorLiveTests.cs:line 605
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass5_0.<RunTestOnSeparateThread>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location ---
>    at NUnit.Framework.Internal.Commands.TimeoutCommand.Execute(TestExecutionContext context)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1051802&view=results

**Comment by JoshLove-msft** [comment]
This is a transient failure with the ARM client and is not related to the SDK.
