### ISSUE TITLE
[Servicebus] CanUpdateSessionConcurrency failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23437]
Servicebus nightly test runs are failing with:

> Error message
> Azure.Messaging.ServiceBus.ServiceBusException: The AMQP object session1327 is aborted. (ServiceCommunicationProblem)
> ---> System.OperationCanceledException: The AMQP object session1327 is aborted.
> at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
> at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
> at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
> at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
> at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.<OpenAmqpObjectAsync>g__Open|82_1(AmqpObject target, TimeSpan timeout, TaskCompletionSource1 openObjectCompletionSource) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:line 1102 at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenAmqpObjectAsync(AmqpObject target, TimeSpan timeout, CancellationToken cancellationToken, String entityPath, Boolean isProcessor) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:line 1112 at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.CreateAndOpenSessionAsync(AmqpConnection connection, TimeSpan timeout) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:line 737 at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.CreateSessionIfNeededAsync(AmqpConnection connection, TimeSpan timeout) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:line 721 at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.CreateReceivingLinkAsync(String entityPath, String identifier, AmqpConnection connection, Uri endpoint, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:line 645 --- End of inner exception stack trace --- at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.CreateReceivingLinkAsync(String entityPath, String identifier, AmqpConnection connection, Uri endpoint, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:line 702 at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, Boolean isProcessor, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpConnectionScope.cs:line 349 at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 200 at Microsoft.Azure.Amqp.FaultTolerantAmqpObject1.OnCreateAsync(TimeSpan timeout)
> at Microsoft.Azure.Amqp.Singleton1.GetOrCreateAsync(TimeSpan timeout) at Microsoft.Azure.Amqp.Singleton1.GetOrCreateAsync(TimeSpan timeout)
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<OpenLinkAsync>b__72_0>d.MoveNext() in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1425
> --- End of stack trace from previous location where exception was thrown ---
> at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in //sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 144
> at Azure.Messaging.ServiceBus.ServiceBusRetryPolic
> 
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.SessionErrorHandler(ProcessErrorEventArgs args) in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/SessionProcessorLiveTests.cs:line 1947
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs:line 509
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args)
>    at Azure.Messaging.ServiceBus.ServiceBusSessionProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusSessionProcessor.cs:line 153
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ServiceBusSessionProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args)
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:line 396
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs)
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.ReceiveAndProcessMessagesAsync(CancellationToken processorCancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:line 319

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1051802&view=results

@jsquire for notification.

**Comment by JoshLove-msft** [comment]
This test has stabilized.
