### ISSUE TITLE
[Servicebus] StopProcessingDoesNotCloseLink failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23438]
Servicebus nightly test runs are failing with:

> Error message
> Expected: instance of <Azure.Messaging.ServiceBus.ServiceBusException> and property Reason equal to SessionCannotBeLocked
> But was:  ServiceTimeout
> 
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.<StopProcessingDoesNotCloseLink>d__19.MoveNext() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 1591
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.<StopProcessingDoesNotCloseLink>d__19.MoveNext() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 1614
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.<StopProcessingDoesNotCloseLink>d__19.MoveNext() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 1614
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.<StopProcessingDoesNotCloseLink>d__19.MoveNext() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Processor\SessionProcessorLiveTests.cs:line 1617
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1051802&view=results

@jsquire for notification.

**Comment by JoshLove-msft** [comment]
This has been fixed.
