### ISSUE TITLE
Azure functions proxies not working

### ISSUE THREAD

**Issue by sjuarezgx** [Azure/azure-sdk-for-net#23455]
TargetFramework : net5.0
AzureFunctions Version : v3
Microsoft.Azure.Functions.Worker.Extensions.Http Version="3.0.13"
Consumption plan
VS 2019

Hi

I have a mobile app and need to pulish all the backend services as serverles Http functions in Azure. This app is configured with the Route prefix "rest" in the host.json file.

The app security is implemented using Oauth 2.0 and the Identity Provider is implemented as a set of services which are part of the services of the app.
Those services run at routes like the following: 
- /oauth/access_token.
- /oauth/userinfo

That is, when hit /oauth/access_token, a service does its job.

How should I solve the issue that the Identity Provider services should be called under another routing path, different than the one of the backend services?

Should I use an Azure function proxy, defining the proxies.json with the mapping to my service?

{
    "$schema": "http://json.schemastore.org/proxies",
    "proxies": {
        "proxy1": {
            "matchCondition": {
                "methods": [ "POST" ],
                "route": "/oauth/access_token"
            },
            "backendUri": "https://test5netwin.azurewebsites.net/gxoauthaccesstoken"
        }
    }
}

It isn't working, so I'd like to know if this is the right way to solve the issue, or if there's another solution.

Thanks

**Comment by jsquire** [comment]
Hi @sjuarezgx.  The package that you're inquiring about is managed in another repository.  I've transferred this over as [#590](https://github.com/Azure/azure-functions-dotnet-worker/issues/590) to ensure that the team best able to assist can see it.
