### ISSUE TITLE
Azure search fails when using empty string for replacement value of PatternReplaceCharFilter

### ISSUE THREAD

**Issue by StephenCleary** [Azure/azure-sdk-for-net#2346]
Creating an index fails when using `PatternReplaceCharFilter` with `Replacement = ""` with error:

    Microsoft.Rest.Azure.CloudException: The request is invalid. Details: index.charFilters[1].replacement : The replacement field is required.

This can be duplicated by attempting to create the following index definition:

    new Index()
    {
        Name = "bob",
        Fields = new[]
        {
            new Field("id", DataType.String) { IsKey = true },
        },
        CharFilters = new CharFilter[]
        {
            new PatternReplaceCharFilter
            {
                Name = "cant_replace_with_empty_string",
                Pattern = "bob",
                Replacement = "",
            },
        },
    };

**Comment by brjohnstmsft** [comment]
@StephenCleary This is a bug in the REST API. We're working on a fix now. ETA for the fix to be deployed is a few weeks. We'll follow up once the fix is deployed and leave this issue open in the meantime.

**Comment by brjohnstmsft** [comment]
@StephenCleary The fix has been deployed. Closing this issue.
