### ISSUE TITLE
[BUG] Microsoft.Azure.ServiceBus is restricted to namespaces with a fully quantified domain.

### ISSUE THREAD

**Issue by martinjt** [Azure/azure-sdk-for-net#23463]
**Describe the bug**
This is part way between a bug and a feature, so feel free to choose which.

Currently, the Microsoft.Azure.ServiceBus client mandates that the namespace endpoint includes a `.` in it.  Therefore ensuring that only "real" domains can be used.  This precludes using something that is hosted on `localhost`.  This seems like something that shouldn't be there as locally contacting servicebus should be ok.

**Expected behavior**
A servicebus namespace can be specified without a `.` e.g. `localhost`

**Actual behavior (include Exception or Stack Trace)**
An exception is thrown on startup.

**To Reproduce**
Have a namespace that is `localhost`, start the client and you'll see it fail.

**Environment:**
All environment, there's nothing specific here.

**Notes:**
The line of code that does this is:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.ServiceBus/src/ServiceBusConnectionStringBuilder.cs#L174

This restriction is not in `Azure.Messaging.ServiceBus`

**Comment by NickCraver** [comment]
One more thing I think worth noting here is that since generally you'll want to be testing with TLS locally, so while `localhost.` would appear to be a domain-based workaround until this is changed, that's much more difficult to get working end-to-end than face value due to none of the local certificate management handling that directly or as a SAN on the certificate (unless we're missing something here!).

**Comment by jsquire** [comment]
//cc: @shankarsama

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ramya-rao-a** [comment]
> This precludes using something that is hosted on localhost. This seems like something that shouldn't be there as locally contacting servicebus should be ok.

@martinjt, @NickCraver,

Can either of you share details around how you are hosting Service Bus locally?

**Comment by martinjt** [comment]
It's something I'm working on, @shankarsama is aware of the usecase, it's just not something I want to share publicly yet.

Using `localhost` will be crucial to adoption though, and as it's not in the `Azure.Messaging.ServiceBus` library, this would bring the solution to parity.

**Comment by jsquire** [comment]
@EldertGrootenboer:  Is this something that you're able to follow-up on?  I'd like to close this out if the feature is no longer under consideration.

**Comment by EldertGrootenboer** [comment]
We are not bringing new functionality to the previous SDKs. As I understand this restriction is not in the latest SDK, as such we recommend using that one.
