### ISSUE TITLE
Content is outdated

### ISSUE THREAD

**Issue by EdiWang** [Azure/azure-sdk-for-net#23466]
Follow the steps in https://docs.microsoft.com/en-us/dotnet/api/overview/azure/billing

It doesn't work. The latest `Microsoft.Azure.Management.Billing` nuget package is not having the .NET types needed for the code.

![image](https://user-images.githubusercontent.com/3304703/130343322-5932cecd-0ac4-45aa-bd2a-e3b84f916eed.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5822f8b9-7782-88c0-ea92-876eadac5e1e
* Version Independent ID: 7a5d1169-d674-1a57-a8c1-07fff302b5af
* Content: [Azure Billing libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/billing)
* Content Source: [api/overview/azure/billing.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/billing.md)
* Service: **billing**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
HI @EdiWang Could you pls share the SDK version you're using?
hi @HarveyLink do you have idea of what's .NET SDK documentation process? Is it auto build and public after SDK published?

**Comment by EdiWang** [comment]
I am using version 4.1.0 of Microsoft.Azure.Management.Billing

https://www.nuget.org/packages/Microsoft.Azure.Management.Billing/4.1.0

**Comment by HarveyLink** [comment]
To unblock this issue, @EdiWang, you can install `Microsoft.Rest.ClientRuntime.Azure.Authentication` package.
@yungezz This is a manual maintenance need doc repo, I have no idea about any auto pipeline which can monitor this.

**Comment by EdiWang** [comment]
Thanks @HarveyLink I will try that.

**Comment by HarveyLink** [comment]
@EdiWang Further update, This should be the correct  sample code:
```
            // Log into Azure
            var serviceCreds = ApplicationTokenProvider.LoginSilentAsync(tenantId, clientId, secret).Result;
            var billingClient = new BillingManagementClient(serviceCreds);
            billingClient.SubscriptionId = subscriptionId;

            // Get list of invoices
            billingClient.Invoices.ListByBillingAccount(accountName);
```

**Comment by lilyjma** [comment]
@EdiWang - I'm assuming this issue has been resolved. Tagging it as so. Please feel free to let us know otherwise.
