### ISSUE TITLE
[BUG] ResourceManager - SubscriptionClient.Subscriptions.ListAsync() does not return Tag data

### ISSUE THREAD

**Issue by schuettecarsten** [Azure/azure-sdk-for-net#23473]
**Describe the bug**
SubscriptionClient.Subscriptions.ListAsync() does not return Tag data, but according to docs page, it should. When requesting a single subscription, Tag values are returned as expected. I am not sure if this is an issue with the SDK or with the Azure API itself.

**Expected behavior**
Tag values should be returned.

**Actual behavior (include Exception or Stack Trace)**
Tag is always null, also if subscription has several tags.

**To Reproduce**
Code to request a list of subscriptions - subscription.Tags is always null:
```
	// Query subscription list
	using (var client = new SubscriptionClient(credentials))
	{
		IPage<Subscription> subscriptionsPage = await client.Subscriptions.ListAsync().ConfigureAwait(false);
		while (true)
		{
			foreach (var subscription in subscriptionsPage)
			{
```

When requesting a single subscription, subscription.Tags is returned as expected:
```
	subscription = await client.Subscriptions.GetAsync(subscriptionGuid).ConfigureAwait(false);
```

**Environment:**
Microsoft.Azure.Management.ResourceManager 3.14.0-preview

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
thanks for the inquiry. For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are will be public preview soon around early September. cc @nickzhums

**Comment by schuettecarsten** [comment]
Ok - it's very, very difficult to find the latest Azure SDK libries in NuGet and in the documentation...

**Comment by yungezz** [comment]
feedback well received. We're working on docs improvment to make latest libraries more visibility, and easy to discover. cc @nickzhums .

**Comment by lilyjma** [comment]
@schuettecarsten -  I'm assuming this issue has been resolved. Tagging it as so. Please feel free to let us know otherwise.
