### ISSUE TITLE
[FEATURE REQ] Keyvault - Support key rotate and rotation policy

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-sdk-for-net#23471]
**Library or service name.**
`Azure.Security.KeyVault.Keys`
 
**Is your feature request related to a problem? Please describe.**
Feature request from service team. The Swagger is updated. https://github.com/Azure/azure-rest-api-specs/pull/11965/files

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Duplicate of #22685
