### ISSUE TITLE
Providers / SKUS API - Which resources provide costs, capacity, and capabilities fields?

### ISSUE THREAD

**Issue by solvingj** [Azure/azure-sdk-for-net#2347]
This is the documentation:   https://msdn.microsoft.com/en-us/library/azure/mt748085.aspx

Says: "Currently, the sku operation is not supported by all resource providers."
And:  "Many of the values are optional and may not be in your response."

I've tested four core resource types on 5 of the latest API versions, none of them provide anything other than the 6 fields in the Microsoft.Compute example.  Which types provide the additional fields?

This API would be extremely useful if all of the native azure resource types were available through it.  Are they moving to this API?  Or, are the extended fields only intended for marketplace apps?

**Comment by markcowl** [comment]
@ravbhatnagar Can you take a look at this API query?

**Comment by adrianhall** [comment]
This does not reference current documentation, so we can't go back, and Azure APIs have moved on significantly.  If this is still a problem, please open a new issue with a reference to your current state.  Thanks!
