### ISSUE TITLE
[BUG] 'Request url is invalid' exception when trying to use TableClient for cosmos with TokenCredential

### ISSUE THREAD

**Issue by shakednai1** [Azure/azure-sdk-for-net#23474]
I tried to initialize the TableClient with:
1. (https://{account_name}.table.cosmos.azure.com/{table_name}, tableName, TokenCredential) and got:
        **Azure.RequestFailedException: 'Request url is invalid.**
        ActivityId: 2b031a99-d483-4475-ba1a-60d4d288f650, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
        RequestID:2b031a99-d483-4475-ba1a-60d4d288f650
        **Status: 400 (Bad Request)
        ErrorCode: InvalidInput
        Content:
        {"odata.error":{"code":"InvalidInput","message":{"lang":"en-us","value":"Request url is invalid.\r\nActivityId: 2b031a99-d483-4475-ba1a-60d4d288f650, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0\nRequestID:2b031a99-d483-4475-ba1a-60d4d288f650\n"}}}**
        Headers:
        Transfer-Encoding: chunked
        x-ms-request-id: 2b031a99-d483-4475-ba1a-60d4d288f650
        Content-Type: application/json;odata=fullmetadata
        Date: Sun, 22 Aug 2021 12:39:56 GMT

2. (https://{account_name}.table.cosmos.azure.com, tableName, TokenCredential) and got:
**Azure.RequestFailedException: 'Authorization header doesn't confirm to the required format. Please verify and try again.**
ActivityId: 72028f0b-e90c-486b-95bc-7618f0c14a62, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
RequestID:72028f0b-e90c-486b-95bc-7618f0c14a62
**Status: 401 (Unauthorized)
ErrorCode: Unauthorized
Content:
{"odata.error":{"code":"Unauthorized","message":{"lang":"en-us","value":"Authorization header doesn't confirm to the required format. Please verify and try again.\r\nActivityId: 72028f0b-e90c-486b-95bc-7618f0c14a62, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0\nRequestID:72028f0b-e90c-486b-95bc-7618f0c14a62\n"}}}**
Headers:
Transfer-Encoding: chunked
x-ms-request-id: 72028f0b-e90c-486b-95bc-7618f0c14a62
Content-Type: application/json;odata=minimalmetadata
Date: Sun, 22 Aug 2021 12:41:40 GMT

Using Azure.Data.Tables Version 12.1.0

**Comment by christothes** [comment]
Sorry for the confusion - `TokenCredential` is currently only supported on Storage Tables endpoints. 

#addressed

**Comment by christothes** [comment]
Will update the xml docs to clarify this.
