### ISSUE TITLE
Failure running Key Vault client on-premise behind firewall

### ISSUE THREAD

**Issue by rolsendk** [Azure/azure-sdk-for-net#23494]
Hi, I'm developing to an environment where all outbound traffic is denied unless it goes through a web proxy which uses a whitelist of urls; if a outbound url is not whitelisted the proxy will deny the call.
I'm attempting to run a Key Vault client in this environment with a custom HttpClient configured to use a proxy.

**First problem**
 Tests show that library code will trigger requests not going through the proxy, resulting in timeouts as all calls have to go through the proxy. Using a proxy like Fiddler and network inspection tools I can see that my custom HttpClient is used by the library to call my Key Vault while several calls to unknown Azure ip's are triggered directly not going through the proxy. 
Question: How can I ensure that the library will use my custom HttpClient only?

**Second problem**
It's been very difficult to gather all the urls the Key Vault client calls, for whitelisting. At the moment I know of the Key Vault url and the authority thing _login.windows.net_, but what else is there? Judging from the network inspection at least two other Azure ips are called by the library.
Question: Which urls will the Key Vault client call? And I mean _any_ outbound request. Hints or source references are much appreciated.

I've tested using old (Microsoft.*) and new Azure.Core libraries, same problem.

Using Azure.Core:
```
using (HttpClientHandler handler = new HttpClientHandler()
{
	Proxy = new WebProxy(new Uri(proxyUrl))
}) 
{
	SecretClientOptions options = new SecretClientOptions
	{
		Transport = new Azure.Core.Pipeline.HttpClientTransport(handler)
	};

	X509Certificate certificate = FindCertificateByThumbprint(thumbprint);
	var credentials = new ClientCertificateCredential(tenantId, clientId, certificate);
	var client = new SecretClient(new Uri(vaultUrl), credentials, options);

	KeyVaultSecret secret = await client.GetSecretAsync("sharepointUsername");

	secret.Value.Dump();
}
```

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by rolsendk** [comment]
@Mohit-Chakraborty  After some consideration I believe this needs to be re-submitted as a bug; the Key Vault client does not use the custom HttpClient for all outbound requests. This is a bug. Can you convert this question to a bug, or do I need to do submit a new issue?

**Comment by heaths** [comment]
The `SecretClient` is calling into the credential provider which will authenticate against your AAD. To use the same transport, you can do the same to the credential provider:

```csharp
HttpClientTransport transport = new(handler);

SecretClientOptions secretOptions = new SecretClientOptions
{
    Transport = transport,
};

ClientCertificateCredentialOptions credentialOptions = new()
{
    Transport = transport,
};

ClientCertificateCredential credential = new(tenantId, clientId, certificate, credentialOptions );
SecretClient client = new(new Uri(vaultUrl), credential, secretOptions);
```

Does that work for you? We also [support](https://github.com/Azure/azure-sdk-for-net/blob/df05d84fdc1842df1b3ec9031d4e28aef1de7cfb/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs#L168-L192) various common [environment variables](https://github.com/Azure/azure-sdk-for-net/blob/df05d84fdc1842df1b3ec9031d4e28aef1de7cfb/sdk/core/Azure.Core/src/Pipeline/Internal/HttpEnvironmentProxy.cs#L14) you could set environment variables for standard proxy configuration that should work without a custom transport. I also opened #23774 to better document these.

As for endpoints, Key Vault will only connect to your vault but the authentication call(s) may connect to additional endpoints like login.microsoft.com (which varies in different cloud environments if you support them in your app), or potentially any users' domain if using a custom domain for their AAD, I believe.

**Comment by heaths** [comment]
In Azure.Core [1.17 or newer](https://github.com/Azure/azure-sdk-for-net/blob/df05d84fdc1842df1b3ec9031d4e28aef1de7cfb/sdk/core/Azure.Core/CHANGELOG.md#1170-2021-08-10) there's also a `ClientOptions.Default` you can use to set a transport for any client e.g.,

```csharp
ClientOptions.Default.Transport = new HttpClientTransport(handler);
```

**Comment by rolsendk** [comment]
@heaths Thanks for the reply. I already set a transport using ClientOptions, to no avail; Although the library will call my Key Vault at Azure using the transport proxy at least two unknown Azure ip range requests are not using the proxy and thus timeouts occur. I had to install a network sniffer to test this.
You can find my code for the tests at the top, it's practical identical to your example. I'm using Azure.Core 1.18.

To solve my problem I need to 1) Have all Azure.Core libraries involved in fetching a secret from a Key Vault use my proxy, and 2) Document all url requests by said libraries, for proxy whitelisting. So far this has not been possible. So what can I do from here? I desperately need your help.

**Comment by heaths** [comment]
Did you set the default options for all Azure.* HTTP clients like in this [comment](https://github.com/Azure/azure-sdk-for-net/issues/23494#issuecomment-912685058)? Did you try the environment variables? Any non-Azure.* packages may use those standard variables as well.

The Key Vault SDK only connects to your vault. The IP may vary if reverse-proxied - I honestly don't know, but I doubt it. Those other IP ranges could be for authentication, which Azure.Identity would be making and if you use either of those methods above should proxy as well.

**Comment by rolsendk** [comment]
Both alternatives does the trick: Authentication requests are now routed via proxy, and secrets are fetched. Big thanks for the help! :heart:

So in the end only two urls had to be whitelisted in the proxy: _xyz.vault.azure.net_ and  _login.microsoftonline.com_ 

BTW: When testing the environment variable alternative I simply created a system variable named "HTTPS_PROXY" with the proxy url as the value. It's documented here https://docs.microsoft.com/en-us/dotnet/azure/sdk/azure-sdk-configure-proxy
