### ISSUE TITLE
Clarify documentation around what is retried automatically

### ISSUE THREAD

**Issue by EnricoMassone** [Azure/azure-sdk-for-net#23493]
Hi, I'm using the **Azure.Messaging.ServiceBus** package version **7.1.0** from an **ASP.NET core 3.1** application.

I'm trying to understand [this part of the library documentation](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus#exception-handling), related with exception handling. The point that is not totally clear to me is the one related with the retry policy in case of service timeout errors.

Based on my understanding the _Azure.Messaging.ServiceBus_ library has a built in retry policy, which the developer gets for free and can customize if needed. The default built in retry policy is the one called [BasicRetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/servicebus/Azure.Messaging.ServiceBus/src/Core/BasicRetryPolicy.cs). My understanding is that this retry policy is automatically applied by the library when needed. Is that correct ?

 The [documentation](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus#exception-handling) states that each time the library throws an exception of type `ServiceBusException` having `IsTransient = true`  the retry policy **has already been applied and retries were unsuccessful**. A few lines below the documentation states that when the `ServiceBusException.Reason` is `ServiceBusFailureReason.ServiceTimeout` **the developer** should evaluate **whether or not** to retry the failed operation. 

So, my question is: in case of a `ServiceBusException`  having `ex.Reason == ServiceBusFailureReason.ServiceTimeout` is the library retry policy **automatically** applied, or in this case the retry is delegated to the developer ? The source of confusion is that usually timeouts are considered transient errors, so I would expect them to be automatically handled by the library retry policy. 

**Environment:**
 - Name and version of the Library package used: **Azure.Messaging.ServiceBus version 7.1.0** 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET SDK (reflecting any global.json):
 Version:   5.0.302
 Commit:    c005824e35

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.302\

Host (useful for support):
  Version: 5.0.8
  Commit:  35964c9215

.NET SDKs installed:
  5.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
 - IDE and version : Visual Studio Professional 2019 version 16.10.4

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @EnricoMassone,
If you get a ServiceBusException thrown that has IsTransient = true, it means that the exception was already retried up to the MaxTries limit.

**Comment by EnricoMassone** [comment]
/unresolved

Hi @JoshLove-msft thanks for replying.

To summarize: each time the library throws and error deemed to be transient, I have the guarantee that retries has already been applied by the library itself, regardless of the error `Reason` . 

Correct ?

**Comment by EnricoMassone** [comment]
Hello @JoshLove-msft I have another question related with the built in retry policy in **Azure.Messaging.ServiceBus**

Is there a way to turn-off / disable the built in retry policy ? I mean is there a way to **prevent** the application of the retry policy in case of transient failures ?

**Comment by JoshLove-msft** [comment]
You can set the MaxRetries = 0 so that no retries will occur.

**Comment by EnricoMassone** [comment]
> You can set the MaxRetries = 0 so that no retries will occur.

Simple enough, thanks!

**Comment by ramya-rao-a** [comment]
@JoshLove-msft Can we do the required doc update for the Oct milestone?

**Comment by JoshLove-msft** [comment]
This has been clarified here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/TROUBLESHOOTING.md#handle-service-bus-exceptions
