### ISSUE TITLE
[BUG] Scaleset naming convention

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-sdk-for-net#23507]
It blows my mind that this wasn't resolved in the very first preview, but the naming convention for nodes in a scaleset should be

nodename_000 (or more)

and not

nodename_0

**Comment by AlexGhiondea** [comment]
@jackbond thanks for opening this issue.

Could you provide us more information about the package and service you are running into an issue with?

**Comment by jackbond** [comment]
I don't have a scaleset with more than 9 nodes (I have in the past), but since they can go to 999 the screen below becomes a total mess. This is literally a 10 second fix, wherever your code looks like this...

$"{nodename}_{nodeIndex}"

change it to this

$"nodename_{nodeIndex:D3}"

![image](https://user-images.githubusercontent.com/2799232/130709817-5fa1367c-f296-4c04-ac26-b6cb2d832c95.png)

**Comment by navba-MSFT** [comment]
@jackbond Apologies for the late reply. Thanks for the feedback. We are looking into this issue. We will update this thread once we have more details on this.

 @QingChenmsft, @vaishnavk, @juhacket Could you please provide an update on this ? Awaiting your reply.
