### ISSUE TITLE
[Core] CredScan: handle false positives

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#23505]
## Issue

We currently have 2 test secrets in Core Track 2 library being detected by CredScan ([report](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1062613&view=logs&j=10327055-d4d6-50a6-a312-3d2cd4bd9cb9&t=f5631f7d-b32d-5870-f8fc-4da93924d5ce&l=177)).

These are the secrets being detected:
1.
https://github.com/Azure/azure-sdk-for-net/blob/303b75341ba17aecf239a3232d28ca76209a5346/sdk/core/Azure.Core/tests/PemReaderTests.cs#L304-L331
2.
https://github.com/Azure/azure-sdk-for-net/blob/303b75341ba17aecf239a3232d28ca76209a5346/sdk/core/Azure.Core/tests/PemReaderTests.cs#L368-L395

## Goal

We need to move the certificate keys to a separate file and make tests read them from there. After that's done, the file path must be added to the suppression file as well:
https://github.com/Azure/azure-sdk-for-net/blob/303b75341ba17aecf239a3232d28ca76209a5346/eng/CredScanSuppression.json#L53-L58
Here's [an example](https://github.com/Azure/azure-sdk-for-net/blob/303b75341ba17aecf239a3232d28ca76209a5346/sdk/identity/Azure.Identity/tests/Data/cert.pem).

**Comment by pakrym** [comment]
@heaths, can you look at this, please?

**Comment by heaths** [comment]
Can't we just add _azure-sdk-for-net/sdk/core/Azure.Core/tests/PemReaderTests.cs_ to the suppression list?

**Comment by kinelski** [comment]
> @kinelski can't we just add azure-sdk-for-net/sdk/core/Azure.Core/tests/PemReaderTests.cs to the suppression list?

I would advise against doing so because this would prevent us from identifying possible other leaks in this file in the future. I think actual leaks are only likely to happen in recording files, though. @weshaggard What do you think?

**Comment by weshaggard** [comment]
We have been trying to avoid adding entire source files to the suppression list unless the file is known to only contain test/fake secrets like a cert file or a fakes file but for any standard cs files we don't add them to the suppression list to avoid potential leaks.
