### ISSUE TITLE
[BUG] IsLoggingPIIEnabled property clarity needed

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#23518]
**Describe the bug**

I enabled IsLoggingPIIEnabled on DAC and expected to not see REDACTED  in logs.  But I still see this:

```
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
```

I discussed with @christothes and it appears that this only applies to certain clients.  If that is the case, then I think we need to improve docs, or not have it at the TokenOptions level.

I would like to understand better what this setting applies to and how to view the data.

**Expected behavior**

I expected to see the values instead of them be redacted.

**Actual behavior (include Exception or Stack Trace)**

They are still redacted.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
```
            var client = new SecretClient(vaultUri,
                new AzureCliCredential(
                    new AzureCliCredentialOptions { IsLoggingPIIEnabled = true }
                )
            );
```

Look at the logs and see the REDACTED.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
```
    <PackageReference Include="Azure.Identity" Version="1.5.0-beta.3"/>
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.3.0-beta.1"/>
```
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

VS CODE

azsdke2e
azsdke2e1

**Comment by Mohit-Chakraborty** [comment]
@pakrym - can you give your opinion on this.
Is there some improvement that needs to be made or can the user objective be achieved with current support?
