### ISSUE TITLE
[BUG] AllowMultiTenantAuthentication clarity needed

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#23519]
**Describe the bug**

I couldn't figure out what AllowMultiTenantAuthentication did by reading the comments.  

Here's the best I explanation I could come up with based on discussions with @christothes 

-------
## Multi-Tenant and Tenant Fallback Setting

> This is a new feature that is currently in beta as of 8/24/2021.

Sometimes your app needs to support multiple tenants and you don't want to hard-code a single Tenant Id. By default, if the user doesn't belong to the default or specified tenant, then the Azure Identity token request will fail. But now there's a way to fix that.

When an Azure service authentication fails and the resource is in a tenant different than the one used in the request, then the service will return its Tenant Id with the 403:Unauthenticated response as part of the WWW-Authenticate challenge.

Azure Identity now provides a setting that allows you to take advantage of that response and will try to auth again with the alternate Tenant Id.  It will also ensure that the user is part of the alternate tenant and has permissions to access the resource.

Here's how to enable that multi-tenant fallback feature:

```csharp
 var client = new SecretClient(vaultUri,
    new DefaultAzureCredential(
        new DefaultAzureCredentialOptions { AllowMultiTenantAuthentication = true }
    )
);
```
-------

I'd like to see this fully explained in docs.

azsdke2e
azsdke2e1

**Comment by christothes** [comment]
I think this is obsolete based on where we ended up with the feature.
