### ISSUE TITLE
[BUG] EventsResults Not show @odata:count when send parameter count: true

### ISSUE THREAD

**Issue by rafa-arcangel** [Azure/azure-sdk-for-net#23525]
**Describe the bug**
I'm using the library for Microsoft.Azure.ApplicationInsights.Query and when I made the request through the method client.Events.GetCustomEventsAsync, the response didn't contain the value for the global count.

**Expected behavior**
When make a call to the Application Insight REST API, it returns a json object with those properties:
```json
 ...
    }
  ],
  "@odata.count": 17389
}
```
The value for @odata.count didn't exist on the model for the response.

I reviewed the code and saw that in the model Microsoft.Azure.ApplicationInsights.Query.Models.EventsResults this property not exist (and it couldn't be parsed):
```
       [JsonProperty(PropertyName = "@odata.context")]
        public string Odatacontext { get; set; }

       ///THIS PROPERTY MUST EXIST IN THE MODEL, but not
       [JsonProperty(PropertyName = "@odata.count")]
        public string Odatacount { get; set; }
```
I think that it missed the most kind of Models in the library.

**To Reproduce**
1. Configure the AppInsight client
2. Make a call 
```
var events = await client.Events.GetCustomEventsAsync(appId, timespan, count: true, cancellationToken: cancellationToken); 
```
3. Expected result must have the global count, but doesn't exist.

**Environment:**
 - Name and version of the Library package used: MicrosoftApplicationInsightsQuery 1.0.0
 - Hosting platform or OS and .NET runtime version: Any
 - IDE and version : Visual Studio 16.9.5

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by AndrewTheWild** [comment]
The problem still exists :)

**Comment by rafaarcangel** [comment]
Nearly a year after, we still waiting for a fix on this......

I think you only need to add, as I suggested, the property json converter
```
[JsonProperty(PropertyName = "@odata.count")]
        public string Odatacount { get; set; }
```

**Comment by scottaddie** [comment]
Support for the `Microsoft.Azure.ApplicationInsights.Query` package ended on March 31st. It has been deprecated in favor of [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query). We recommend migrating to continue receiving support. To assist in that migration, see [this migration guide](https://aka.ms/azsdk/net/migrate/ai-monitor-query).
