### ISSUE TITLE
[BUG] Azure.Storage.Queues package 12.7.0 raises multiple activities with same Operation Name for one method

### ISSUE THREAD

**Issue by russcam** [Azure/azure-sdk-for-net#23545]
**Describe the bug**

When calling `QueueClient.ReceiveMessageAsync()` on the `QueueClient` from Azure.Storage.Queues package 12.7.0, two activities with OperationName `QueueClient.ReceiveMessage` are raised for a single method call:

1. First one is started in internal method call `ReceiveMessagesInternal`
    https://github.com/Azure/azure-sdk-for-net/blob/b0403de6fff3cfc961deba543e3c657287fc0626/sdk/storage/Azure.Storage.Queues/src/QueueClient.cs#L2343-L2347

2. Second one is started inside the body of the internal method call `ReceiveMessagesInternal` called in the body of the first `ReceiveMessagesInternal`
    https://github.com/Azure/azure-sdk-for-net/blob/b0403de6fff3cfc961deba543e3c657287fc0626/sdk/storage/Azure.Storage.Queues/src/QueueClient.cs#L2180-L2183

This seems like undesirable behaviour if using these activities for telemetry purposes. 

There might be other Azure SDK packages that exhibit similar behaviour. From testing, it appears that `BlobClient.DownloadToAsync()` in Azure.Storage.Blobs package version 12.9.1 starts two activities with OperationNames `BlobBaseClient.DownloadTo` and `BlobBaseClient.DownloadStreaming`.

**Expected behavior**

I would expect one Activity with OperationName `QueueClient.ReceiveMessage` to be started per ReceiveMessage method call. This is the behaviour in Azure.Storage.Queues 12.6.0.

**Actual behavior (include Exception or Stack Trace)**

Two activities with OperationName `QueueClient.ReceiveMessage` are started.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Here's a reproduction

```c#
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using Azure.Storage.Queues;

namespace QueueClientTelemetryDemo
{
    class Program
    {
        static async Task<int> Main(string[] args)
        {
            using var _ = DiagnosticListener.AllListeners.Subscribe(new DiagnosticObserver());
            
            var connectionString = "[REDACTED]";
            
            var queueName = Guid.NewGuid().ToString();
            var client = new QueueClient(connectionString, queueName);

            var createResponse = await client.CreateAsync();
            var sendResponse = await client.SendMessageAsync("sample message");
            var receiveResponse = await client.ReceiveMessageAsync();

            return 0;
        }
    }
    
    public class DiagnosticObserver : IObserver<DiagnosticListener>
    {
        public void OnCompleted() { }

        public void OnError(Exception error) { }

        public void OnNext(DiagnosticListener value)
        {
            if (value.Name == "Azure.Storage.Queues")
            {
                value.Subscribe(new QueueObserver());
            }
        }
    }

    public class QueueObserver : IObserver<KeyValuePair<string, object>>
    {
        public void OnCompleted()
        {
        }

        public void OnError(Exception error)
        {
        }

        public void OnNext(KeyValuePair<string, object> value)
        {
            Console.WriteLine("Azure.Storage.Queues Key " + value.Key);
        }
    }
}
```

which yields

```
Azure.Storage.Queues Key QueueClient.Create.Start
Azure.Storage.Queues Key QueueClient.Create.Stop
Azure.Storage.Queues Key QueueClient.SendMessage.Start
Azure.Storage.Queues Key QueueClient.SendMessage.Stop
Azure.Storage.Queues Key QueueClient.ReceiveMessage.Start
Azure.Storage.Queues Key QueueClient.ReceiveMessage.Start
Azure.Storage.Queues Key QueueClient.ReceiveMessage.Stop
Azure.Storage.Queues Key QueueClient.ReceiveMessage.Stop
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Queues 12.7.0

**Comment by seanmcc-msft** [comment]
@tg-msft

**Comment by pakrym** [comment]
>Can you help me understand the value of the specific Activity types? What am I missing in their utility?

Helping customers understand what client call resulted in a particular HTTP request, grouping multiple HTTP requests that resulted from a single call (retries, multi request calls like stages uploads)

>Are "Azure.Core" activities the recommended approach to base telemetry collection exposed through Activity for Azure SDKs on?

If you don't need to have logic based on a particular SDK method being called listening to "Azure.Core" events would give you the most coverage.

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
