### ISSUE TITLE
Schema registry corrupt

### ISSUE THREAD

**Issue by YaliBar** [Azure/azure-sdk-for-net#23563]
library: Azure.Data.SchemaRegistry.ApacheAvro(version 1.0.0-beta.2)

While using the schema registry avro extension, I noticed that SchemaRegistryAvroObjectSerializer(with auto-register-schema=True) accepts any schema groups and Event-Hub resource, which sometimes when users have misconfigured, it can register new version on a different resources from other product environments.

It's important to restrict the auto register feature, only if the producer Event-Hub resource is the same the Serializer endpoint when registering new Avro schemas.

**Comment by YaliBar** [comment]
@JoshLove-msft
Yes indeed.

**Comment by JoshLove-msft** [comment]
I don't see how the library can infer your intent here. If the group name does not exist in the endpoint that you specify, then autoregister would fail. If it does exist, but it is not the endpoint you intended, the library is not able to tell this. The recommendation is to only set AutoRegisterSchemas to True for testing purposes, so hopefully this would not come up in production scenarios.
