### ISSUE TITLE
[BUG] AnalyzeActionsResult serialization does not preserve EntityCategory value

### ISSUE THREAD

**Issue by raj4all** [Azure/azure-sdk-for-net#23568]
**Describe the bug**
The AnalyzeActionResult response has _RecognizeEntitiesActions_ as a field. After serializing the content Azure.AI.TextAnalytics _EntityCategory_ is empty. When debugged, I can see the EntityCategory value as _Person, DateTime_ etc. However, after serializing those fields are rendered empty. like _"category": {},_

The reason could be:
 _EntityCategory_ has members defined as static. JSON serializer is ignoring static members and constants.
`public static readonly EntityCategory Person;`

**Expected behavior**
We should see the JSON values as _"category": "Person"_ etc.

**Actual behavior (include Exception or Stack Trace)**
The JSON serialization shows as _"category": {}_

**To Reproduce**
![image](https://user-images.githubusercontent.com/20979256/130976150-a04aa8e6-c49a-469f-995b-ef017285f6e2.png)

**Environment:**
 - SDK: Azure.AI.TextAnalytics, Version=5.1.0
 - .NET Framework Version: 5.0
 - OS: Windows 10
 - IDE and version : Visual Studio 2019 V 16.11.1

**Comment by AlexGhiondea** [comment]
@kinelski can you take a look?

**Comment by raj4all** [comment]
Thanks for the reply.
Yes this works as a workaround.

**Comment by kinelski** [comment]
> Thanks for the reply. Yes this works as a workaround.

That's great! Feel free to open a new issue and please let us know if you have further questions.
