### ISSUE TITLE
Does ListBlobsSegmentedAsync returns blobs sequentially?

### ISSUE THREAD

**Issue by dheerajawale-svg** [Azure/azure-sdk-for-net#23581]
[Enter feedback here]
Does ListBlobsSegmentedAsync returns blobs sequentially?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e6cc800-331f-7132-d9b7-e3ac59ba5d94
* Version Independent ID: 04716976-30f5-bf72-82d4-60ef68d76cb3
* Content: [CloudBlobClient.ListBlobsSegmentedAsync Method (Microsoft.Azure.Storage.Blob) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblobclient.listblobssegmentedasync?view=azure-dotnet-legacy)
* Content Source: [xml/Microsoft.Azure.Storage.Blob/CloudBlobClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.Blob/CloudBlobClient.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by seanmcc-msft** [comment]
Please re-open if you have further questions.
