### ISSUE TITLE
[Service Bus] AcceptNextSessionRespectsCancellation failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23606]
Service Bus nightly test runs are failing with:

> Error message
> Expected: less than 00:00:10
> But was:  00:00:36.9847420
> 
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Client.ServiceBusClientLiveTests.AcceptNextSessionRespectsCancellation() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Client/ServiceBusClientLiveTests.cs:line 213
>    at Azure.Messaging.ServiceBus.Tests.Client.ServiceBusClientLiveTests.AcceptNextSessionRespectsCancellation() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Client/ServiceBusClientLiveTests.cs:line 221
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass5_0.<RunTestOnSeparateThread>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1067259&view=results

**Comment by JoshLove-msft** [comment]
No longer seeing failures for this.
