### ISSUE TITLE
Azure.Storage.Queues proxy config

### ISSUE THREAD

**Issue by juligu** [Azure/azure-sdk-for-net#23608]
**Query/Question**
There was an option with the previous library version to implement a proxy https://stackoverflow.com/questions/55927663/connect-to-azure-storage-queue-behind-proxy but it doesn't seem to be possible with the latest one, is there any guidance on this?

**Environment:**
 - Azure.Storage.Queues, 12.7.0 
 - dotnet 5
 - Visual Studio 16.11.2

**Comment by amishra-dev** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy is what you are looking for
