### ISSUE TITLE
[QUERY] Microsoft.Azure.WebJobs.Extensions.EventHubs AzureFunction works with EventData rather then PartitionEvent

### ISSUE THREAD

**Issue by devedse** [Azure/azure-sdk-for-net#23610]
**Query/Question**
Hello, I just started converting some code from an EventHub listener which runs in my AppService to Azure Functions. In my app service I'm using the latest `Azure.Messaging.EventHubs` package. I read that to be able to use the same "EventData" object I need to use the beta version of `Microsoft.Azure.WebJobs.Extensions.EventHubs` (5.0.0 beta 7 is what I'm using).

This all works fine.

In the code in my AppService I've written my code around handling these PartitionEvents:
```
await foreach (PartitionEvent partitionEvent in consumer.ReadEventsFromPartitionAsync(partitionIdInternal, startingPosition, stoppingToken))
```

It's nice for logging to see if for whatever reason events ended up in the wrong partitions. All of this code has been released as an internal NuGet package for other projects to use.

When migrating this code to Azure Functions I noticed that the entry point in an Azure Function only provides a list of `EventData`. Normally the EventData object is container within the `PartitionEvent`.

Is there any reason for this discrepancy or can you also use PartitionEvent inside an Azure Function?

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.WebJobs.Extensions.EventHubs AzureFunction 5.0.0 beta 7
 - Hosting platform or OS and .NET runtime version: N/A
 - IDE and version : N/A

**Comment by devedse** [comment]
Thanks that should solve my issue. I could not find this in the documentation though. Is this described somewhere? Or is there another way to find all possible options?

**Comment by JoshLove-msft** [comment]
Yes, there is documentation for the possible binding types here - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=csharp#usage
