### ISSUE TITLE
[Issue] Could not create BlobServiceClient to obtain the BlobContainerClient using Connection: Storage

### ISSUE THREAD

**Issue by dahmad515** [Azure/azure-sdk-for-net#23639]
I created a .net function last year which was working perfectly fine using Microsoft.WindowsAzure.Storage, Microsoft.WindowsAzure.Storage.Auth and Microsoft.WindowsAzure.Storage.Blob.

_CloudStorageAccount SourcestorageAccount = CloudStorageAccount.Parse(SourceConnectionString);
CloudBlobClient SourceblobClient = SourcestorageAccount.CreateCloudBlobClient();_  This is how I am using the class.

Now that I'm deploying the function again on Azure function app, I'm receiving this error message. 
Can anyone guide what's wrong.

**Comment by seanmcc-msft** [comment]
Hi, it appears you are using an old version of the SDK.  I recommend you upgrade to [Azure.Storage.Blobs v12](https://www.nuget.org/packages/Azure.Storage.Blobs).
