### ISSUE TITLE
Wrong System.Runtime version is published for .NET 4.6.2

### ISSUE THREAD

**Issue by DixonDs** [Azure/azure-sdk-for-net#2363]
I have System.Runtime 4.1.0 Nuget package used in the Web and Worker role projects targeting .Net 4.6.2. When I package it for publishing or publish it, the target package contains System.Runtime version from .Net installation instead of Nuget package which causes exception "Could not load file or assembly 'System.Runtime, Version=4.1.0.0" in the cloud VM.

**Comment by markcowl** [comment]
@DixonDs This repository is for the azure management libraries, and not the SDK that contains System.Runtime.  Please send this question through the Azure forums for a response.
