### ISSUE TITLE
[BUG]Cannot parse the blob URI with "#" correctly

### ISSUE THREAD

**Issue by amarkwong** [Azure/azure-sdk-for-net#23634]
**Describe the bug**
Please provide the description of issue you're seeing.
We are trying to parse some blob file from EventGrid Trigger in Azure Function, like 

```
public static void Run([EventGridTrigger] EventGridEvent eventGridEvent, [Blob("{data.url}",FileAccess.Read)] Stream meterdata, ILogger log)
```

and if the data.url, or to be specific, the blob name contains **#**, then the Stream is empty.

We try to handle the exception when the binding stream is empty, and we did something like
```
            //Read stream from url if current meterdata is empty
            if (meterdata ==null)
            {
                    BlobUriBuilder blobUriBuilder = new BlobUriBuilder(new Uri(blobUri));

                    BlobContainerClient blobContainerClient = new BlobContainerClient(blobConnStr, blobUriBuilder.BlobContainerName);

             // our workaround, this can give us the correct BlobName
                 // string blobName = blobUri.Substring(blobUri.IndexOf(blobUriBuilder.BlobContainerName) + (blobUriBuilder.BlobContainerName.Length + 1));

             // if we try to use the BlobUriBuilder to get the blob name directly 
                    string blobName = blobUriBuilder.BlobName;
                    BlobClient blobClient = blobContainerClient.GetBlobClient(blobName);

...
           }

```
**Expected behavior**
For example, the blob name is NEM12#210827000000#GLOBALM#ORGNAME.csv
We expect the stream can be fetched directly and the BlobName property should return the actual blob name.

**Actual behavior (include Exception or Stack Trace)**
The stream is empty, while the BlobName from the BlobUriBuilder is NEM12, everything after **#** is considered as comment and got filtered out.

I understand there is a concern of interpreting the comment contents into actually blob name, but I believe in most scenario, the blobname should be consider as the truth of fact. Or at least a toggle to set this feature.
**To Reproduce**
see the code in bug description field

**Environment:**
 - Name and version of the Library package used:  Azure.Storage.Blobs 12.8.0 
 - Hosting platform or OS and .NET runtime version: Azure Function Windows 10 .NET Core 3.1.18
 - IDE and version : Visual Studio 2022 Preview

**Comment by amnguye** [comment]
I will look into reproducing this however, this does look extremely similar to this issue where I wasn't able to reproduce.

https://github.com/Azure/azure-sdk-for-net/issues/21349

So you're saying EventGrid SDK can't parse it or the Storage SDK can't.

**Comment by amarkwong** [comment]
Hi Amanda,

I think most likely it is the Storage SDK issue. I printed out the {data.url} and it has every bit of the filename. I would say it is the **UnescapePath()** in line 221 of BlobUriBuilder.cs cause the issue? Or the last bit of the uri is discarded when calling GetPath() at line 186.
![image](https://user-images.githubusercontent.com/6657590/131825458-494099e3-2f94-4c04-baac-64ead25e3032.png)

![image](https://user-images.githubusercontent.com/6657590/131825551-af974d1c-312f-4c9d-ad9c-93d5ffffa875.png)

**Comment by amishra-dev** [comment]
@seanmcc-msft can you please look

**Comment by seanmcc-msft** [comment]
Hi @amarkwong,

Blob names with URL reserve characters in them need to be escaped - https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#blob-names

> The stream is empty, while the BlobName from the BlobUriBuilder is NEM12, everything after # is considered as comment and got filtered out.

This behavior is from the URI constructor - https://docs.microsoft.com/en-us/dotnet/api/system.uri?view=net-5.0#remarks

If you would like to create a `BlobClient` pointed at a blob with URL reserve characters in the name, I recommend an approach similar to this:

```
BlobContainerClient blobContainerClient = new BlobContainerClient(connectionString, containerName);
BlobClient blobClient = blobContainerClient.GetBlobClient("NEM12#210827000000#GLOBALM#ORGNAME.csv");
```
`blobClient.Uri` will be property escaped, and the blobClient will be pointed at the correct blob.

If you would like to construct the escaped Uri, I'd recommend an approach like this:
```
BlobUriBuilder blobUriBuilder = new BlobUriBuilder(new Uri("https://account.blob.core.windows.net"))
{
    BlobContainerName = "containerName",
    BlobName = "NEM12#210827000000#GLOBALM#ORGNAME.csv"
};
Uri uri = blobUriBuilder.ToUri();
```

-Sean
