### ISSUE TITLE
[BUG] Service Bus appears to be not closing connections

### ISSUE THREAD

**Issue by tkachuk2222** [Azure/azure-sdk-for-net#23641]
**Describe the bug**
I have azure function dotnet-isolated that runs on App Service Plan and with some periodicity azure function throws error because of a lot of open outgoing connections 

**Expected behavior**
Closed connections

**Actual behavior (include Exception or Stack Trace)**
```text
Exception: System.Net.Http.HttpRequestException: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full. (**************.vault.azure.net:443)
 ---> System.Net.Sockets.SocketException (10055): An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String vaultBaseUrl, String secretName, CancellationToken cancellationToken)
   at Scappman.AzureFunctions.Program.GetStoreConnectionString() in C:\work\scappman\Scappman.AzureFunctions\Program.cs:line 75
   at Scappman.AzureFunctions.Program.<>c.<Main>b__9_2(DbContextOptionsBuilder options) in C:\work\scappman\Scappman.AzureFunctions\Program.cs:line 50
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 16
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166
Stack:    at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretAsync(IKeyVaultClient operations, String vaultBaseUrl, String secretName, CancellationToken cancellationToken)
   at Scappman.AzureFunctions.Program.GetStoreConnectionString() in C:\work\scappman\Scappman.AzureFunctions\Program.cs:line 75
   at Scappman.AzureFunctions.Program.<>c.<Main>b__9_2(DbContextOptionsBuilder options) in C:\work\scappman\Scappman.AzureFunctions\Program.cs:line 50
   at Microsoft.Extensions.DependencyInjection.EntityFrameworkServiceCollectionExtensions.CreateDbContextOptions[TContext](IServiceProvider applicationServiceProvider, Action`2 optionsAction)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45
   at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 16
   at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166 
```
**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
```html
<html>
<body>
<!--StartFragment-->

Instance | RemoteAddress | Established | TimeWait
-- | -- | -- | --
[xxxxxxxx] | 65.52.***.***:5671 | 2015 | 0

<!--EndFragment-->
</body>
</html>
```

![image](https://user-images.githubusercontent.com/20381930/131330676-254348a7-be4a-4737-b9a4-c4ec88db84ef.png)

code example 1:
```csharp
   public class Program
    {
        public static AzureServiceTokenProvider AzureServiceTokenProvider = new AzureServiceTokenProvider();
        private static readonly KeyVaultClient KeyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(AzureServiceTokenProvider.KeyVaultTokenCallback));

        public Program(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        private static string KeyVaultEndpoint => Environment.GetEnvironmentVariable("KEYVAULT_ENDPOINT");
        private static IConfiguration Configuration { get; set; }
        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureAppConfiguration((context, builder) =>
                {
                    var keyVaultEndpoint = KeyVaultEndpoint;
                    if (string.IsNullOrEmpty(keyVaultEndpoint))
                    {
                        return;
                    }
                    builder.AddAzureKeyVault(
                        keyVaultEndpoint, KeyVaultClient, new DefaultKeyVaultSecretManager());
                })
                .ConfigureServices(collection =>
                {
                    collection.AddDbContext<IApplicationDbContext, StoreDbContext>(options =>
                        options.UseSqlServer(GetStoreConnectionString()));
                })
                .Build();

            host.Run();
        }

        private static string GetStoreConnectionString()
        {
            var keyVaultEndpoint = KeyVaultEndpoint;
            if (string.IsNullOrEmpty(keyVaultEndpoint))
            {
                return null;
            }
            var azureServiceTokenProvider = new AzureServiceTokenProvider();
            using var keyVaultClient = new KeyVaultClient(
                new KeyVaultClient.AuthenticationCallback(
                    azureServiceTokenProvider.KeyVaultTokenCallback));
            var secret = keyVaultClient.GetSecretAsync(keyVaultEndpoint, "StoreConnection").GetAwaiter().GetResult();
            return secret.Value;
        }
    }
```
code example 2:
```csharp
    public class Program
    {
        private static KeyVaultClient _keyVaultClient;

        public Program(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        private static string KeyVaultEndpoint => Environment.GetEnvironmentVariable("KEYVAULT_ENDPOINT");
        private static IConfiguration Configuration { get; set; }
        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureAppConfiguration((context, builder) =>
                {
                    var keyVaultEndpoint = KeyVaultEndpoint;
                    if (string.IsNullOrEmpty(keyVaultEndpoint))
                    {
                        return;
                    }

                    var keyVaultClient = GetKeyVaultClient();

                    builder.AddAzureKeyVault(
                        keyVaultEndpoint, keyVaultClient, new DefaultKeyVaultSecretManager());
                })
                .ConfigureServices(collection =>
                {
                    collection.AddDbContext<IApplicationDbContext, StoreDbContext>(options =>
                        options.UseSqlServer(GetStoreConnectionString()));
                })
                .Build();

            host.Run();
        }

        private static string GetStoreConnectionString()
        {
            var keyVaultEndpoint = KeyVaultEndpoint;
            if (string.IsNullOrEmpty(keyVaultEndpoint))
            {
                return null;
            }

            SecretBundle secret;
            var keyVaultClient = GetKeyVaultClient();
            
            secret = keyVaultClient.GetSecretAsync(keyVaultEndpoint, "***********").GetAwaiter().GetResult();
            
            return secret.Value;
        }

        private static KeyVaultClient GetKeyVaultClient()
        {
            if (_keyVaultClient == null)
            {
                var tokenProvider = new AzureServiceTokenProvider();
                
                _keyVaultClient = new KeyVaultClient(new KeyVaultCredential(
                    new KeyVaultClient.AuthenticationCallback(tokenProvider.KeyVaultTokenCallback)));
            }

            return _keyVaultClient;
        }
    }
```

**Environment:**
 - Name and version of the Library package used:
```xml
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.2.1" />
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.2.0" />
    <PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.2.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.4" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.5.1" />
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="5.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.18" />
```
 - Hosting platform or OS and .NET runtime version:
  Runtime Environment:
  Windows 10.0.14393 win10-86
  Host: 
  Version 5.0.7
  App Service Plan
 - IDE and version : 
    VS Code 1.59
    Azure Functions Extension 1.5.0

**Comment by tkachuk2222** [comment]
Name and version of the Library package used:
Azure.Messaging.ServiceBus Version="7.2.1"
Azure.Security.KeyVault.Certificates Version="4.2.0"
Azure.Security.KeyVault.Keys Version="4.2.0"
Azure.Security.KeyVault.Secrets Version="4.2.0"
Microsoft.Azure.Functions.Worker.Extensions.Http Version="3.0.13"
Microsoft.Azure.Functions.Worker.Extensions.ServiceBus Version="4.2.1"
Microsoft.Azure.Functions.Worker.Extensions.Timer Version="4.1.0"
Microsoft.Azure.Functions.Worker.Sdk Version="1.0.4" OutputItemType="Analyzer"
Microsoft.Azure.Functions.Worker Version="1.5.1"
Microsoft.Azure.ServiceBus Version="5.1.3"
Microsoft.Extensions.Configuration Version="5.0.0"
Microsoft.Extensions.Configuration.AzureKeyVault Version="3.1.18"

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Microsoft.Azure.KeyVault is deprecated and we ask that customers move to Azure.Security.KeyVault.Secrets. We have a migration guide available at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/MigrationGuide.md.

The older code does not make efficient / correct use of the default `HttpClient` while the newer code does (shares one by default). A workaround for this in the older code is to pass your own `HttpClient` to every Microsoft.Azure.* client you create. There are several constructors for `KeyVaultClient` that take an `HttpClient`.

I'm going to mark this issue as addressed, but please feel free to use the `/unresolve` command should you wish to discuss further.

**Comment by tkachuk2222** [comment]
/unresolve

looks like migration to the new library haven't help
![image](https://user-images.githubusercontent.com/20381930/131629347-5a94ec6b-33f3-4b9f-917d-b641099c3558.png)

`public class Program
    {
        private static SecretClient _secretClient;

        public Program(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        private static string KeyVaultEndpoint => Environment.GetEnvironmentVariable("KEYVAULT_ENDPOINT");

        private static IConfiguration Configuration { get; set; }

        public static void Main()
        {
            var host = new HostBuilder()
                .ConfigureFunctionsWorkerDefaults()
                .ConfigureAppConfiguration((context, builder) =>
                {
                    var keyVaultEndpoint = KeyVaultEndpoint;
                    if (string.IsNullOrEmpty(keyVaultEndpoint))
                    {
                        return;
                    }

                    var keyVaultClient = GetKeyVaultClient();

                    builder.AddAzureKeyVault(keyVaultClient, new KeyVaultSecretManager());
                })
                .ConfigureServices(collection =>
                {
                    collection.AddDbContext<IApplicationDbContext, StoreDbContext>(options =>
                        options.UseSqlServer(GetStoreConnectionString()));
                })
                .Build();

            host.Run();
        }

        private static string GetStoreConnectionString()
        {
            var keyVaultEndpoint = KeyVaultEndpoint;
            if (string.IsNullOrEmpty(keyVaultEndpoint))
            {
                return null;
            }

            var keyVaultClient = GetKeyVaultClient();

            var secret = keyVaultClient.GetSecret("StoreConnection");

            return secret.Value.Value;
        }

        private static SecretClient GetKeyVaultClient()
        {
            if (_secretClient == null)
            {
                var options = new DefaultAzureCredentialOptions { ExcludeVisualStudioCredential = true };
                _secretClient = new SecretClient(
                    new Uri(KeyVaultEndpoint),
                    new DefaultAzureCredential(options));
            }

            return _secretClient;
        }
    }`


<html>
<body>


Instance | RemoteAddress | Established | TimeWait
-- | -- | -- | --
[xxxxxxxx] | 65.52.***.***:5671 | 2021 | 0


</body>
</html>

**Comment by heaths** [comment]
Could you explain what the table represents? Is that the number of active connections to the given IP address? I don't recognize the 8 bits. Which cloud for Key Vault do you connect to, i.e. what's the domain suffix?

Does `netstat -a` on the host also show all open sockets to the same Key Vault IP? I'm also wondering if this could be a managed identity issue, which does open inbound sockets but should still close them.

The first graph - going up and dropping off as clients gets disposed during GC - is typical of our older packages using the default `HttpClient`, but the latter graph is not something we've seen from our newer packages.

**Comment by tkachuk2222** [comment]
> Could you explain what the table represents? Is that the number of active connections to the given IP address? I don't recognize the 8 bits. Which cloud for Key Vault do you connect to, i.e. what's the domain suffix?
> The table represents the number of active connections to the given IP address
A domain suffix is `.net` (and it's azure)
I don't recognize the 8 bits - What do you mean?

> Does `netstat -a` on the host also show all open sockets to the same Key Vault IP? If you resolve your Key Vault's IP address, does that match the IP address for opened sockets?
> I can't execute `netstat -a` on Azure. I got message `Access is denied.` 

> The first graph - going up and dropping off as clients gets disposed during GC - is typical of our older packages using the default `HttpClient`, but the latter graph is not something we've seen from our newer packages.
> The first graph - dropping off because of manually restart of azure function service

**Comment by heaths** [comment]
Not the TLD ".net", but the your Key Vault domain name sans host e.g., "vault.azure.net"? Different clouds have different domains. What I meant is that I don't recognize the first 8 bits of the IP address, i.e. 65. It's not one seemingly used by Key Vault in the public cloud, nor is there any reason we'd connect to remote port 5671.

What I can find for port 5671 is that it's used for AMQPS, which is used for Event Hubs. Are you using Event Hubs in your app?

**Comment by jsquire** [comment]
Port 5761 is likely used by Service Bus in this case. I notice that you're referencing both the legacy `Microsoft.Azure.ServiceBus` and `Azure.Messaging.ServiceBus` packages. Can you share more context around how you're using Service Bus and how you're managing the lifetime of the clients?

**Comment by tkachuk2222** [comment]
@jsquire yes, I'm using Service Bus (as a queue trigger and time trigger that calls dead letter queue), also, I'm using HttpClient that is configured in DI as a Singleton
in Program.cs:
`.ConfigureServices(collection =>
{
   collection.AddSingleton<HttpClientWrapper>();
}`
in HttpClientWrapper.cs:
`public class HttpClientWrapper
    {
        public readonly HttpClient HttpClient = new HttpClient();

        public HttpClient GetHttpClient()
        {
            return HttpClient;
        }
    }`

then I just inject HttpClientWrapper and use HttpClient from wrapper (so I use one HttpClient)


short example of how I use azure function time trigger that calls Service Bus dead-letter queue:

` public class InstallDeadLetterTimeTrigger
    {
        private readonly IConfiguration _configuration;
        private readonly IApplicationDbContext _dbContext;
        private readonly HttpClientWrapper _httpClientWrapper;

        public InstallDeadLetterTimeTrigger(IApplicationDbContext dbContext, IConfiguration configuration, HttpClientWrapper httpClientWrapper)
        {
            _dbContext = dbContext;
            _configuration = configuration;
            _httpClientWrapper = httpClientWrapper;
        }

        [Function("[xxxxxxxxxx]DeadLetterTimeTrigger")]
        public async Task Run([TimerTrigger("0/40 * * * * *")] MyInfo myTimer, FunctionContext context)
        {
            var log = context.GetLogger("[xxxxxxxxxx]DeadLetterTimeTrigger");

            log.LogInformation("Executed [xxxxxxxxxx]DeadLetterTimeTrigger");

            var freeSlotsUrl = _configuration["[SomeSecretName]"];

            var response = await _httpClientWrapper.HttpClient.GetStringAsync(freeSlotsUrl);

            var freeSlotsData = JsonConvert.DeserializeObject<FreeSlotsResponse>(response);
            if (freeSlotsData != null && freeSlotsData.FreeSlots > 0)
            {
                var dlqReceiver = new MessageReceiver(_configuration["[SomeSecretName]"],
                    EntityNameHelper.FormatDeadLetterPath(_configuration["[SomeSecretName]"]));
                log.LogInformation("dlqReceiver created");
                var deadQueueItem = await dlqReceiver.ReceiveAsync();
                log.LogInformation("dlqReceiver received");
                if (deadQueueItem == null)
                {
                    log.LogWarning("*******Completed. No dead queue messages.********");
                    return;
                }

                // some logic here

                await dlqReceiver.CompleteAsync(deadQueueItem.SystemProperties.LockToken);

                await _dbContext.SaveChangesWithoutUserAsync(CancellationToken.None);

                log.LogWarning($"*******Completed {deadQueueItem.MessageId}");
            }

            log.LogWarning($"*******Completed*********");
        }
    }` 

example of service bus trigger function:

`
 public class InstallServiceBusTrigger
    {
        private readonly IConfiguration _configuration;
        private readonly IApplicationDbContext _dbContext;
        private readonly IBlobService _blobService;
        private readonly IPackageInstallHelper _packageInstallHelper;
        private readonly PackageInstallationService _packageInstallationService;
        private readonly HttpClientWrapper _httpClientWrapper;

        public InstallServiceBusTrigger(PackageInstallationService packageInstallationService, IPackageInstallHelper packageInstallHelper,
            IApplicationDbContext dbContext, IConfiguration configuration, IBlobService blobService, HttpClientWrapper httpClientWrapper)
        {
            _packageInstallationService = packageInstallationService;
            _packageInstallHelper = packageInstallHelper;
            _dbContext = dbContext;
            _configuration = configuration;
            _httpClientWrapper = httpClientWrapper;
            _blobService = blobService;
        }

        [Function("[xxxxxxxx]ServiceBusTrigger")]
        public async Task Run([ServiceBusTrigger("queue-name", Connection = "[configNameFromKeyVault]")]
            string queueItem,
            FunctionContext context, string lockToken)
        {
            var log = context.GetLogger("[xxxxxxxx]ServiceBusTrigger");
           
            try
            {
                log.LogInformation($"C# ServiceBus queue trigger function processed message: {queueItem}");
                log.LogInformation("Executed [xxxxxxxx]ServiceBusTrigger");

                var freeSlotsUrl = _configuration["secretName"];

                var response = await _httpClientWrapper.HttpClient.GetStringAsync(freeSlotsUrl);

                var freeSlotsData = JsonConvert.DeserializeObject<FreeSlotsResponse>(response);

                if (freeSlotsData != null && freeSlotsData.FreeSlots > 0)
                {
                    log.LogInformation($"Free slots: {freeSlotsData.FreeSlots}");
                    // some logic here
                }
                else
                {
                    log.LogInformation($"No free slots. Abandoned. Lock token: {lockToken}");
                    // some logic here
                    await receiver.AbandonAsync(lockToken);
                }

                await _dbContext.SaveChangesWithoutUserAsync(CancellationToken.None);
            }
            catch (AggregateException e)
            {
                log.LogError(e.Message, e.InnerException?.Message);
            }
            catch (Exception e)
            {
                log.LogError(e.Message, e.InnerException?.Message);
                throw;
            }


            log.LogWarning($"*******Completed execution*******");
        }
    }
`

**Comment by tkachuk2222** [comment]
@heaths yes, it's 'vault.azure.net'. No, I'm using Service Bus, not Event Hub. 
This  is all outbound TCP connections of azure functions:
<html>
<body>


Instance | RemoteAddress | Established | TimeWait
-- | -- | -- | --
[xxxxxxxxx] | 65.52.128.xxx:5671 | 1983 | 3
[xxxxxxxxx] | 40.91.199.xxx:443 | 15 | 0
[xxxxxxxxx] | 52.157.162.xxx:443 | 14 | 0
[xxxxxxxxx] | 13.95.155.xxx:443 | 9 | 2
[xxxxxxxxx] | 52.239.138.xxx:443 | 3 | 7


</body>
</html>

**Comment by jsquire** [comment]
You are creating a new `MessageReceiver` for each invocation of the DeadLetterTimeTrigger function and not closing it.   This is going to cause a new AMQP connection to be created and then left open until it times out after ~90 seconds of inactivity or the service force-closes it.   Since your trigger is running every 40 seconds, you're accumulating connections more quickly than they are closing.   If possible, I'd recommend treating `MessageReceiver` as a singleton.   If the entity you're reading from is dynamic for each invocation,  then wrapping it in a try/finally and ensuring that the receiver gets closed properly would be the next best thing.

It's hard to speculate about ServiceBusTrigger since the `receiver` variable that is being used to abandon the message.   If you're using Functions v3, you may be binding the receiver directly.   If you're not, the same guidance would apply.

**Comment by tkachuk2222** [comment]
@jsquire I've added to all places code with closing connections, but it didn't affect

`   
                log.LogWarning($"Is connection closed - {dlqReceiver.IsClosedOrClosing}");

                log.LogWarning($"OwnsConnection - {dlqReceiver.OwnsConnection}");
  if (!dlqReceiver.IsClosedOrClosing)
                {
                    log.LogWarning($"Closing connection");
                    await dlqReceiver.CloseAsync();

                    log.LogWarning($"Closed - {dlqReceiver.IsClosedOrClosing}");
                }`

in logs:
`
2021-09-08T14:25:05.083 [Warning] Is connection closed - False
2021-09-08T14:25:05.084 [Warning] OwnsConnection - True
2021-09-08T14:25:05.084 [Warning] Closing connection
2021-09-08T14:25:05.084 [Warning] Closed - True
`

I've changed time trigger from 40 sec to 2 min and it didn't affect too

this is how the connections look like after those changes: 
![image](https://user-images.githubusercontent.com/20381930/132530204-0fd435fa-3edb-4a82-9eeb-dc58246edbb4.png)

**Comment by jsquire** [comment]
@tkachuk2222:   Can you share the changes that you've made to your code?   Also, is there a reason that you're unable to treat the Service Bus clients as singletons in your application?

**Comment by tkachuk2222** [comment]
` 
using System;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.ServiceBus;
using Microsoft.Azure.ServiceBus.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace [xxxxxxxxx].AzureFunctions
{
public class InstallDeadLetterTimeTrigger
    {
        private readonly IConfiguration _configuration;
        private readonly IApplicationDbContext _dbContext;
        private readonly HttpClientWrapper _httpClientWrapper;

        public InstallDeadLetterTimeTrigger(IApplicationDbContext dbContext, IConfiguration configuration, HttpClientWrapper httpClientWrapper)
        {
            _dbContext = dbContext;
            _configuration = configuration;
            _httpClientWrapper = httpClientWrapper;
        }

        [Function("[xxxxxxxx]DeadLetterTimeTrigger")]
        public async Task Run([TimerTrigger("0/40 * * * * *")] MyInfo myTimer, FunctionContext context)
        {
            var log = context.GetLogger("[xxxxx]DeadLetterTimeTrigger");

            log.LogInformation("Executed [xxxx]DeadLetterTimeTrigger");

            var freeSlotsUrl = _configuration["[secretName]"];

            var response = await _httpClientWrapper.HttpClient.GetStringAsync(freeSlotsUrl);

            var freeSlotsData = JsonConvert.DeserializeObject<FreeSlotsResponse>(response);
            if (freeSlotsData != null && freeSlotsData.FreeSlots > 0)
            {
                var dlqReceiver = new MessageReceiver(_configuration["[SomeSecretName]"],
                    EntityNameHelper.FormatDeadLetterPath(_configuration["[SomeSecretName]"]));
                log.LogInformation("dlqReceiver created");
                var deadQueueItem = await dlqReceiver.ReceiveAsync();
                log.LogInformation("dlqReceiver received");
                if (deadQueueItem == null)
                {
                    log.LogWarning("*******Completed. No dead queue messages.********");
                    return;
                }

                // some logic here    

                await dlqReceiver.CompleteAsync(deadQueueItem.SystemProperties.LockToken);

                if (!dlqReceiver.IsClosedOrClosing)
                {
                    await dlqReceiver.CloseAsync();
                }

                await _dbContext.SaveChangesWithoutUserAsync(CancellationToken.None);

                log.LogWarning($"*******Completed {deadQueueItem.MessageId}");
            }

            log.LogWarning($"*******Completed*********");
        }
    }
}`


this is how my code look like now. I tried change time trigger from 40 sec to 2 min but it didn't help. I've showed logs to demonstrate that code in the if is executed.

**Comment by jsquire** [comment]
I don't see anything obvious in the snippet that you've shared.  If you're logging that `CloseAsync` is being called, as you've mentioned, and you're still seeing connections orphaned, then we should escalate to the team that owns that version of the Service Bus SDK.   I'm going to reassign this over for their investigation.


In the meantime, what I'd recommend is treating the `MessageReceiver` as a singleton.   This will ensure that it uses a single connection;  there's no benefit to creating/destroying it unless your `_configuration` changes between invocations.

```csharp
using System;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.ServiceBus;
using Microsoft.Azure.ServiceBus.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace [xxxxxxxxx].AzureFunctions
{
    public class InstallDeadLetterTimeTrigger
    {
        private readonly IConfiguration _configuration;
        private readonly IApplicationDbContext _dbContext;
        private readonly HttpClientWrapper _httpClientWrapper;
        private readonly MessageReceiver _dlqReceiver;

        public InstallDeadLetterTimeTrigger(IApplicationDbContext dbContext, IConfiguration configuration, HttpClientWrapper httpClientWrapper)
        {
            _dbContext = dbContext;
            _configuration = configuration;
            _httpClientWrapper = httpClientWrapper;
            _dlqReceiver = new MessageReceiver(_configuration["[SomeSecretName]"], EntityNameHelper.FormatDeadLetterPath(_configuration["[SomeSecretName]"]));
        }

        [Function("[xxxxxxxx]DeadLetterTimeTrigger")]
        public async Task Run([TimerTrigger("0/40 * * * * *")] MyInfo myTimer, FunctionContext context)
        {
            var log = context.GetLogger("[xxxxx]DeadLetterTimeTrigger");

            log.LogInformation("Executed [xxxx]DeadLetterTimeTrigger");

            var freeSlotsUrl = _configuration["[secretName]"];

            var response = await _httpClientWrapper.HttpClient.GetStringAsync(freeSlotsUrl);

            var freeSlotsData = JsonConvert.DeserializeObject<FreeSlotsResponse>(response);
            if (freeSlotsData != null && freeSlotsData.FreeSlots > 0)
            {
                var deadQueueItem = await _dlqReceiver.ReceiveAsync();
                log.LogInformation("dlqReceiver received");
                if (deadQueueItem == null)
                {
                    log.LogWarning("*******Completed. No dead queue messages.********");
                    return;
                }

                // some logic here    

                await _dlqReceiver.CompleteAsync(deadQueueItem.SystemProperties.LockToken);
                await _dbContext.SaveChangesWithoutUserAsync(CancellationToken.None);

                log.LogWarning($"*******Completed {deadQueueItem.MessageId}");
            }

            log.LogWarning($"*******Completed*********");
        }
    }
}
```

**Comment by jsquire** [comment]
@shankarsama:  This Functions app is using the `Microsoft.Azure.ServiceBus` package and it seems as though connections are being left open for a `MessageReceiver` despite `CloseAsync` being called.    

Earlier in the thread, the following observation was made about open connections, with one of the AMQP ports having a high number of connections.    

Instance | RemoteAddress | Established | TimeWait
-- | -- | -- | --
[xxxxxxxxx] | 65.52.128.xxx:5671 | 1983 | 3
[xxxxxxxxx] | 40.91.199.xxx:443 | 15 | 0
[xxxxxxxxx] | 52.157.162.xxx:443 | 14 | 0
[xxxxxxxxx] | 13.95.155.xxx:443 | 9 | 2
[xxxxxxxxx] | 52.239.138.xxx:443 | 3 | 7

Your thoughts would be very much appreciated.

**Comment by tkachuk2222** [comment]
it looks like fixed. I  forgot to close the connection here:
![image](https://user-images.githubusercontent.com/20381930/132723611-09387286-02c9-43a9-8092-e6522ee191a3.png)

I'll see in a day. if everything will be good I close the bug
