### ISSUE TITLE
Is CloudTableClient thread safe?

### ISSUE THREAD

**Issue by ulfkri** [Azure/azure-sdk-for-net#23645]
Is it thread safe?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59855499-8cb1-9518-8e1a-0c98e862608c
* Version Independent ID: ca4a8579-0b37-c22b-de8a-1dc4f00cd0b5
* Content: [CloudTableClient Class (Microsoft.Azure.Cosmos.Table) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.cloudtableclient?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos.Table/CloudTableClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos.Table/CloudTableClient.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by sakash279** [comment]
@ulfkri - Yes, CloudTableClient is thread safe. The recommendation is to use a single CloudTableClient instance across all operations.
