### ISSUE TITLE
Fix Monitor Query tests

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#23659]
Tracking issue for investigating and fixing the 26 unique consistently failing tests in net - monitor tests

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1072674&view=ms.vss-test-web.build-test-results-tab

https://dev.azure.com/azure-sdk/internal/_test/analytics?definitionId=2545&contextType=build

**Comment by nisha-bhatia** [comment]
Duplicated in https://github.com/Azure/azure-sdk-for-net/issues/23879
