### ISSUE TITLE
Azure WebJobs Web PubSub Readme and Sample issue

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#23669]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSub#prerequisites):

![image](https://user-images.githubusercontent.com/65581162/131432386-46884d4d-4ff2-4a57-8e65-4611273da911.png)

Suggestion:
Update link to https://review.docs.microsoft.com/azure/azure-web-pubsub/howto-develop-create-instance?branch=main

2.
Section [link1](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSub/samples/WebPubSubConnectionBindingFunction.cs#L18),[link2](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSub/samples/WebPubSubOutputBindingFunction.cs#L18),[link3](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSub#functions-that-uses-web-pubsub-input-binding),[link4](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSub#functions-that-uses-web-pubsub-output-binding):
![image](https://user-images.githubusercontent.com/65581162/131432879-d8e05298-8a2d-4f91-b763-c0b8a47aecca.png)

Reason:
Lack of `ConnectionStringSetting`.

Suggestion: 
Update to
 ```
[WebPubSubConnection(ConnectionStringSetting = "<connection_name>", Hub = "hub", UserId = "{query.userid}")] WebPubSubConnection connection)
```

@scottaddie,@AlexGhiondea,@nickzhums and @vicancy for notification.

**Comment by JialinXin** [comment]
@Tianyun-G Thanks for the suggestions. The `ConnectionStringSetting` is an optional parameter which is provided in case customer need to use different connection strings for different functions. Generally we suggest customer to use global connection string `WebPubSubConnectionString` in function settings for easy management. And in the readme we have introduction on this: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSub#authenticate-the-client

Is it required or it's a general guide to add `ConnectionStringSetting` in every function sample?

**Comment by v-yilinhu** [comment]
@JialinXin I think adding `ConnectionStringSetting`is more convenient to understand, and of course the status quo will be fine.

**Comment by JialinXin** [comment]
Thanks for clarify. I'll update the links.

**Comment by v-yilinhu** [comment]
@JialinXin Thank you for your reply, do you have any plans to fix this issue?

**Comment by JialinXin** [comment]
Link and code are updated. Thanks for reporting the issue!
