### ISSUE TITLE
CheckNameAvailability on Microsoft.Web/Sites errors with {"The resource type could not be found in the namespace 'Microsoft.Web' for api version '2015-08-01'."}

### ISSUE THREAD

**Issue by SankarGopalan** [Azure/azure-sdk-for-net#2366]
Hi All,

Package id="Microsoft.Azure.Management.Websites" version="1.3.2-preview" 

The following code always fails with "{"The resource type could not be found in the namespace 'Microsoft.Web' for api version '2015-08-01'."}" on CheckNameAvailabilityAsync call.

var cred = new TokenCredentials(token);
var client = new Microsoft.Azure.Management.WebSites.WebSiteManagementClient(new Uri("https://management.azure.com/"), cred)
{
    SubscriptionId = "1885d885-......"
};
var checkName = await GlobalModelOperationsExtensions.CheckNameAvailabilityAsync(client.GlobalModel, new ResourceNameAvailabilityRequest
{
    Name = "myWebApp",
    Type = "Microsoft.Web/Sites", 
});

In some thread - I had read that Azure team is working on consolidating Check Availability methods for all resources and the work is still in progress. Is this bug related to that work?

Interestingly the above code works in Azure PPE environment but not in Azure Production environment.

Thanks,
Sankaranarayanan MG

**Comment by cormacpayne** [comment]
@Nking92 Hey Nicholas, would you mind taking a look at this issue?

**Comment by Nking92** [comment]
Thanks for pinging me. We're looking into it.

**Comment by naveedaz** [comment]
@cormacpayne This should now be fixed. Please try again and let us know if you still run into issues.

**Comment by SankarGopalan** [comment]
Verified - its working now.

Thanks,
Sankaranarayanan MG

Date: Wed, 5 Oct 2016 11:38:39 -0700

**Comment by naveedaz** [comment]
Thanks I will close the issue now.

**Comment by OlgaOkaralkina** [comment]
@cormacpayne @Nking92 @naveedaz I got this error.
I used this package https://www.nuget.org/packages/Microsoft.Azure.Management.RecoveryServices (latest version)
```
{
  "error": {
    "code": "InvalidResourceType",
    "message": "The resource type 'locations/checkNameAvailability' could not be found in the namespace 'Microsoft.RecoveryServices' for api version '2016-06-01'. The supported api-versions are '2018-01-10'."
  }
}
```
