### ISSUE TITLE
Target lower netstandard version in Key Vault preview library

### ISSUE THREAD

**Issue by cwe1ss** [Azure/azure-sdk-for-net#2367]
Hi, I've seen that there is now a preview package of Azure Key Vault on nuget.org - that's great news! However IMO targeting netstandard1.5 is pretty high. 

It would be great if you could go down to at least netstandard1.3 to also support Universal Windows Platform and to make it easier for other libraries to depend on this library.

Also, I think you should upgrade to Newtonsoft.Json 9.0.1 - this would probably allow you to drop your `imports` directives in your project.json. Most netstandard libraries I've seen moved to this version - even ASP.NET Core.

**Comment by herveyw** [comment]
@cwe1ss We are targeting the same version of NetStandard as the rest of the SDK and currently have no plans to support a lower version. We do also build for .NET 4.5.x as well.

**Comment by cwe1ss** [comment]
Ok, thx for the info!
