### ISSUE TITLE
[FEATURE REQ] Support sanitizing or ignoring specific properties in returned JSON response when recording

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-net#23709]
**Library or service name.**
What library or service is this request related to?
`Azure.Core.TestFramework`
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?
Right now the sanitizer can only recognize some patterns of contents which need sanitized. In reality, each service could have specific contents in the responses to be sanitized. We need a way to let test case writers to customize the contents to sanitize or ignore.

In test cases, we could provide the following annotations.
```csharp
[RecordedTest]
[Sanitize("JSONPath")]
[Drop("JSONPath")]
public void yourtest()
{
...
}
```
Both attributes must accept a [JSONPath](https://jsonpath.com/) expression to specify the properties to be sanitized or ignored. Any property which match the JSONPath expression will be sanitized or ignored.

**Comment by jsquire** [comment]
//cc: @pakrym

**Comment by pakrym** [comment]
We do support this already. see https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/README.md#sanitizing in particular the section about AddJsonPathSanitizer

**Comment by archerzz** [comment]
Thanks @pakrym It's very helpful!

Closing
