### ISSUE TITLE
[Feature Request] Enhance ServiceBusProcessor LockRenewal to better handle Prefetched messages

### ISSUE THREAD

**Issue by adminnz** [Azure/azure-sdk-for-net#23704]
**Describe the bug**
When using Azure.Messaging.ServiceBus.ServiceBusProcessor with a MaxAutoLockRenewalDuration > TimeSpan.Zero and a PrefetchCount higher than the MaxConcurrentCalls.
The ServiceBusProcessor (internally its actually the ReceiverManager) will only start renewal of a messages lock token when it actually starts handling that message (even though the message could be one that has been prefetched).
(see [here](https://github.com/Azure/azure-sdk-for-net/blob/2aec0594edf97d8f835e2d1012e6b29ec2fba68d/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs#L152) for the MessageRenewal task creation)

This means that if the PrefetchCount is for example 3 and the MaxConcurrentCalls is 1, and the user's ProcessMessageAsync(..) implementation takes 30 seconds and the MessageLock duration is the default 60 seconds.
The ServiceBusProcessor will:
1. Do a remote call to and prefetch 3 messages (A,B,C) each with a lock token set to expire in T+60 seconds.
2. Message (A) will start to be handled (T+0) which involves:
    - Start MessageLockRenew task for message (A)
    - Await ProcessMessageAsync for message (A)
    - AutoComplete message (if configured) & await the end of renewal task
3. Message (B) will start to be handled (T+30) which involves:
    - Start MessageLockRenew task for message (B)
    - Await ProcessMessageAsync for message (B)
    - AutoComplete message (if configured) & await the end of renewal task
3. Message (C) will start to be handled (T+60) which involves:
    - Start MessageLockRenew task for message (C) which will **fail** because the lock has now expired
    - Await ProcessMessageAsync for message (C) (if the user has  AutoCompleteMessages=false, then their calls will fail with MessageLockLost exceptions)
    - AutoComplete message (if configured) & await the end of renewal task

This is confusing and effectively means that PrefetchCount must always be 1 to guarantee that when ProcessMessageAsync is called that the Message's lock token is not already expired.
(or be less than MaxConcurrentCalls for a higher chance the lock token is not already expired)

**Expected behavior**
When messages are prefetched for the ServiceBusProcessor they should be collectively managed in terms of Lock token renewal, and the renewal operation should begin for all of the messages when they are prefetched.

**Actual behavior (include Exception or Stack Trace)**
Lock tokens are only renewed on a message by message bases and only have the renewal operation started when each message is handled.

**To Reproduce**
See the sample program.txt attached, with code for a console app to reproduce the issue.
Things to note: 
In the demo if prefetchCount is set to 5, then on the 3rd message the lock token will be expired, and then that will also mean message 4 & 5 are also expired.
[Program.txt](https://github.com/Azure/azure-sdk-for-net/files/7088186/Program.txt)

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.ServiceBus 7.2.1
 - Azure Kubernetes Cluster
 - DotNet info: Version: 5.0.8 Commit: 35964c9215 .NET runtimes installed: Microsoft.NETCore.App 5.0.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
Due to the way that the prefetch queue is managed in the AMQP library, there is no way for the client to access the pending messages to renew them.  Prefetch visibility is not currently on the roadmap for `Microsoft.Azure.Amqp`.   Without transport library support, we would need to avoid using the built-in version and write an approximation in the client.   At this point, we have not received enough feedback or additional to justify the investment of writing a client-based copy.    

I'm going to close this out; should we see sufficient developer demand for this in the future, we'll revisit.
