### ISSUE TITLE
[BUG] Azure.Identity GetTokenAsync() sporadically timing out in Azure function

### ISSUE THREAD

**Issue by erikumhoefer** [Azure/azure-sdk-for-net#23713]
**Describe the bug**
We have an Azure function that is using a system assigned managed identity. When we try to request a token to access our SQL database in the same resource group, occasionally the request will get "stuck" when making the request and is unable to return the token. I have logs around this request and I see the log for starting the token request, but the log after the token request is not logged and the function times out after 5 minutes. This also makes debugging hard as there is no exception thrown by the request - the only exception is the function timeout exception.

We are also noticing long request times (2s+ compared to normal request length of < 500ms)

**Expected behavior**
The token request is successful and does not "hang", causing the function timeout.

**Actual behavior (include Exception or Stack Trace)**
Sporadically the function times out due to the request not completing.
See logs attached from insights (might not be super useful).

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

This is difficult to reproduce as it happens sporadically / inconsistently. It does **not** seem to be correlated with multiple concurrent requests / multiple requests in short succession. It is happened for an isolated request.

Here is the code snippet that is failing.

```csharp
ManagedIdentityCredential azureCredential = new ManagedIdentityCredential();
DateTime requestStart = DateTime.Now;
log.LogInformation("Token request created at {date}.", requestStart);
AccessToken accessToken = await azureCredential.GetTokenAsync(new TokenRequestContext(scopes: new string[] { "https://database.windows.net/.default" }));
log.LogInformation("Token request successful. Request length: {requestTime}ms.", DateTime.Now - requestStart);
connection.AccessToken = accessToken.Token;
```

**Environment:**
 - Name and version of the Library package used: Azure.Identity.1.4.1
 - Hosting platform or OS and .NET runtime version: Azure Functions 3.1.3.0 / netcoreapp3.1
 - IDE and version:  Visual studio 16.5

I have seen some similar looking bugs that are open / have been resolved in the past that seemed to be due to deadlock. This _could_ be a similar issue as the token request hangs indefinitely.
#14691
#22314

Logs:
[tokenTimeoutLogs.csv](https://github.com/Azure/azure-sdk-for-net/files/7091579/tokenTimeoutLogs.csv)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @erikumhoefer - 
Would you mind providing the logging output after reproducing this with [logging enabled](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md)?

I looked at the logs attached, but I'm not sure what those are from.

**Comment by erikumhoefer** [comment]
@christothes those logs are from azure app insights - sorry the format is pretty terrible.

Since Azure Functions use Microsoft.Extensions.Logging and write to Microsoft.Extensions.Logging.ILogger, I am unsure how to add the AzureEventSourceListener. I attempted to get the messages from the event source listener to go to the azure function logger, but was unsuccessful. See snippet

```
[FunctionName("VersioningService")]
public static async Task<ObjectResult> Run([HttpTrigger(AuthorizationLevel.Function, "get", Route = "VersioningService/{id}")]HttpRequestMessage req, ILogger log, string id)
{
  string functionVersion = Environment.GetEnvironmentVariable("FunctionVersion");
  try
  {
	  using AzureEventSourceListener listener = new AzureEventSourceListener((e, message) =>
	  {
		  if(e.Level == EventLevel.Error)
		  {
			  log.LogError(message);
		  }
		  else
		  {
			  log.LogInformation(message);
		  }
	  }, level: EventLevel.Informational);
  
	  int result = 0;
	  string connectionString = Environment.GetEnvironmentVariable("SqlConnectionString");
	  log.LogInformation("VersioningService {version} received request for id {id}.", functionVersion, id);
	  using (SqlConnection connection = new SqlConnection(connectionString))
	  {
		  if (!connectionString.ToLower().Contains("password"))
		  {
			  ManagedIdentityCredential azureCredential = new ManagedIdentityCredential();
			  DateTime requestStart = DateTime.Now;
			  log.LogInformation("Token request created at {date}.", requestStart);
			  AccessToken accessToken = await azureCredential.GetTokenAsync(new TokenRequestContext(scopes: new string[] { "https://database.windows.net/.default" }), CancellationToken.None);
			  log.LogInformation("Token request successful. Request length: {requestTime}ms.", DateTime.Now - requestStart);
			  connection.AccessToken = accessToken.Token;
		  }
		  await connection.OpenAsync();
		  SqlParameter resultParameter = new SqlParameter("@result", System.Data.SqlDbType.Int);
		  resultParameter.Direction = System.Data.ParameterDirection.Output;
		  SqlParameter identifierParameter = new SqlParameter("@id", id);
		  SqlCommand command = new SqlCommand(_INSERT_OR_UPDATE_VERSION, connection);
		  command.Parameters.Add(resultParameter);
		  command.Parameters.Add(identifierParameter);
  
		  await command.ExecuteScalarAsync();
		  result = (int)resultParameter.Value;
		  log.LogInformation("Version {version} returned.", id + result.ToString());
		  return new OkObjectResult(result);
	  }
  }
  catch(Exception ex)
  {
	  log.LogError(ex, "VersioningService {version} encountered an error trying to retrieve a version for {id}.", functionVersion, id);
	  return new ExceptionResult(ex, true)
	  {
		  StatusCode = StatusCodes.Status500InternalServerError
	  };
  }
}
```

**Comment by erikumhoefer** [comment]
I have added the AzureEventSourceListener to my function and I see its logs in insights. I'm going to wait for another failure to occur and come back with those logs, thanks! 👍

**Comment by erikumhoefer** [comment]
Looking at those new logs, I can see the token request is timing out after 100 seconds, and then failing with the exception
```
Request [9abbb824-c2e1-4875-8238-426a88dd98f1] exception System.Threading.Tasks.TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
```
It will then retry the token request two more times, both timing out. After 5 minutes, the function times out.

**Comment by christothes** [comment]
Hi @erikumhoefer - 
Because this appears to be an issue with the Managed Identity service itself, I'd recommend opening a support ticket at https://support.microsoft.com to get assistance on troubleshooting this further.

**Comment by Tealons** [comment]
We are seeing the same issue. If happens with only a part of our function projects and the occurrence is very flaky indeed. We opened a ticket, but the response from support is very slow... Any way you can escalate this @christothes?

**Comment by erikumhoefer** [comment]
@Tealons  could you please link your ticket with Microsoft ?

**Comment by Tealons** [comment]
The ticket number is 2109140050001157.

**Comment by Tealons** [comment]
We got the response from the support team that there is a bug in some of the clusters in Azure. Apparently, the MSI endpoint on some clusters have become stuck in a faulty state induced by a high number of token requests by a site running in the cluster. The product team is aware of this and is working on a fix, but no ETA is given at this moment. The current advice is to restart your functions when this problem occurs.
