### ISSUE TITLE
MSI for Cosmos Tables

### ISSUE THREAD

**Issue by sdandu21** [Azure/azure-sdk-for-net#23716]
**Query/Question**
CosmosClient now supports MSI based authentication. Are there clients/libraries that interact with Cosmos Tables that have similar options? Why don't major libraries like Azure.Data.Tables and Microsoft.Azure.Cosmos.Tables support token based authentication to Cosmos Tables? 

It seems odd that there doesn't seem to be an option to use MSI for Cosmos Tables but there is for storage tables. Do the Azure.Core.Identity and the tables libraries plan to implement support for this in the near future?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by sdandu21** [comment]
Got confirmation from Cosmos team that MSI authentication for Cosmos Tables is not supported at this time.
