### ISSUE TITLE
[QUERY] What is the replacement for ServiceBus' ExtractActivity?

### ISSUE THREAD

**Issue by yvesgoeleven** [Azure/azure-sdk-for-net#23729]
**Query/Question**

I'm in the process of upgrading code that has a dependency on Microsoft.Azure.ServiceBus (Track 1) to Azure.Messaging.ServiceBus (Track 2).

It seems that there is no equivalent for [MessageDiagnosticsExtensions.ExtractActivity](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Extensions/MessageDiagnosticsExtensions.cs#L64)

What is it replaced with? Where can I find upgrade documentation? I've looked into https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md and can't find anything there.

**Comment by jsquire** [comment]
Hi @yvesgoeleven.  Thank you for reaching out and we regret that you're experiencing difficulties.   To my knowledge, there is not yet an official replacement for extracting diagnostic activities.   Until one is available, the following approach can be used:

```csharp
public static bool TryExtractDiagnosticId(ServiceBusMessage message, out string id)
{
    id = null;
    
    if (message.ApplicationProperties.TryGetValue("Diagnostic-Id", out var objectId) && objectId is string stringId)
    {
        id = stringId;
        return true;
    }

    return false;
}
```

@pakrym or @JoshLove-msft may have additional insight to offer on the plan for a diagnostics extension replacement.

**Comment by SeanFeldman** [comment]
@jsquire, the diagnostics/AppInsights story seems very fractured among several Microsoft groups/teams. Is there an "umbrella" issue to track the efforts to bring this all to a state where no manual workarounds such as the suggested one are needed?

**Comment by jsquire** [comment]
@SeanFeldman:  If there is, I'm not aware of it.   @lmolkova may have more visibility and additional insights.

**Comment by JoshLove-msft** [comment]
@yvesgoeleven - can you clarify why you would need to extract the diagnostic Id? Are you correlating it with another activity that you are creating in your app?

**Comment by yvesgoeleven** [comment]
@JoshLove-msft Something similar. I need to manually tie the activity representing the inbound message to the activity representing the outbound message, as the default propagation of activities is broken by a disruptor pattern that sits in the processing pipeline.

**Comment by lmolkova** [comment]
@yvesgoeleven thanks for the context!  In addition to extracting Diagnostic-Id, make sure to create Activity and pass to ApplicationInsights `StartOperation` (or other API you're using). 

@SeanFeldman I've generalized this issue here https://github.com/Azure/azure-sdk/issues/3319. If you know about any cases where it was needed/missed, please help us prioritize it.
