### ISSUE TITLE
How to add ServiceBusClient to Dependency Injection with ServiceBusClientOptions different than default?

### ISSUE THREAD

**Issue by willyt150** [Azure/azure-sdk-for-net#23731]
**Query/Question**
Following the [Best Practices for performance improvements using Service Bus Messaging](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk-2#reusing-factories-and-clients) I'm now utilizing the [ServiceBusClientBuilderExtensions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Compatibility/ServiceBusClientBuilderExtensions.cs) to Add the Service Bus Client.

I want to use a different ServiceBusClientOptions than the default (for different retry options) and I have been unable to find any examples/documentation on how to accomplish this.

I've tried registering my own ServiceBusClientOptions as Singleton in the ServiceCollection, but the ServiceBusClient I receive from DI still has the defaults.

OR, should I just be creating a new ServiceBusClient myself with the options and registering that as singleton?

I'm assuming I'm missing something pretty straightforward, any help would be appreciated. Thanks!

**Environment:**
 - Azure.Messaging.ServiceBus
 - Microsoft.Extensions.Azure

 - Azure Function v3 C#
 - IDE and version : Visual Studio 16.11.1

**Comment by JoshLove-msft** [comment]
Hi @willyt150,
There is a ConfigureOptions method on the IAzureClientBuilder that you can use to specify a delegate for configuring the ServiceBusClientOptions, e.g.:
```c#
builder.AddServiceBusClient("<conn string>").ConfigureOptions(options => options.RetryOptions.MaxRetries = 10);
```

**Comment by willyt150** [comment]
Thank you very much for your quick reply! That's what I was missing!

One more quick question.

If I happen to have something that's needing to communicate with 2 separate Service Bus resources, e.g. one to receive and one to send, am I correct in understanding that I would NOT use the extension methods provided and instead have to manage the singleton instances of the ServiceBusClient myself by whatever key I decide to go with?

**Comment by JoshLove-msft** [comment]
Ah, I see your point. I think you are right that you wouldn't be able to inject two instances of the same type.

@pakrym please keep me honest here.

**Comment by willyt150** [comment]
Ok, thank you very much!

**Comment by pakrym** [comment]
You actually can register multiple, you just need to name them and use a little bit more verbose resolution syntax:

``` C#
        builder.AddSecretClient(Configuration.GetSection("KeyVault"))
            // Set the name for this client registration
            .WithName("namedSecretClient")
```

Then inject `IAzureClientFactory<SecretClient> secretClientFactory` and call `secretClientFactory.CreateClient("namedSecretClient");`

**Comment by willyt150** [comment]
That's awesome! Thank you very much for the additional info @pakrym
