### ISSUE TITLE
[QUERY] DefaultAzureCredential for Face API

### ISSUE THREAD

**Issue by misterjunio** [Azure/azure-sdk-for-net#23744]
**Environment:**
 - `Microsoft.Azure.CognitiveServices.Vision.Face 2.8.0-preview.1`

**Query/Question**
Hi there. I was just wondering if there are any plans to support the use of token credentials rather than service client credentials with the `CognitiveServices.Vision.Face`'s `FaceApiClient`, similar for example to the latest `TextAnalyticsClient` of `AI.TextAnalytics`. I'm trying to standardise access to all Azure resources via `DefaultAzureCredential` (which is awesome btw!) but can't seem to find a way to use it for the Face API yet. Is that right, or are there any workarounds while explicit support doesn't come out? Cheers.

**Comment by mburumaxwell** [comment]
+1
