### ISSUE TITLE
VisualStudioCodeCredentials does not work on WSL2 [BUG]

### ISSUE THREAD

**Issue by tshaiman** [Azure/azure-sdk-for-net#23758]
**Describe the bug**
when working against Cosmos Db with VisualStudioCodeCredentials  (after login to the Azure Subscription) 
The following exception is thrown :
```
Exception has occurred: CLR/Azure.Identity.CredentialUnavailableException
An exception of type 'Azure.Identity.CredentialUnavailableException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Stored credentials not found. Need to authenticate user in VSCode Azure Account.'
```
The same code with the same Azure Subscription after login is working on Windows.

**Expected behavior**
- VisualStudioCodeCredentials   should work in WSL2

**Actual behavior (include Exception or Stack Trace)**
Exception is thrown : 
```
Exception has occurred: CLR/Azure.Identity.CredentialUnavailableException
An exception of type 'Azure.Identity.CredentialUnavailableException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Stored credentials not found. Need to authenticate user in VSCode Azure Account.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.NullReferenceException : Object reference not set to an instance of an object.
   at Azure.Identity.VisualStudioCodeCredential.IsRefreshTokenString(String str)
   at Azure.Identity.VisualStudioCodeCredential.GetStoredCredentials(String environmentName)
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
1. Open VS Code in WSL2 , and login to Azure Subscription using the Azure Account Plugin
2. Run a sample code that uses VisualStudioCodeCredentials  for example
```
var cosmosClient = new CosmosClient(endpoint, new Azure.Identity.VisualStudioCodeCredential());
```

**Environment:**
Azure.Identity 1.4.1 , Microsoft.Azure.Cosmos 3.20.1
OS Name:     ubuntu
OS Version:  18.04
OS Platform: Linux
.Net Sdk 5.0.301
Vs Code Version 1.60.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
closing until #30525 is addressed
