### ISSUE TITLE
[BUG] Update-Snippets.ps1 doesn't set SnippetToolPath correctly

### ISSUE THREAD

**Issue by lynshi** [Azure/azure-sdk-for-net#23756]
**Describe the bug**
[Update-Snippets.ps1](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/Update-Snippets.ps1) is used to update code snippets in README files. When [run locally](https://github.com/Azure/azure-sdk-for-net/blob/e1f6bc5ad44470265f7b1df697173b57b2c8692a/eng/scripts/Update-Snippets.ps1#L22), the script downloads `Azure.Sdk.Tools.SnippetGenerator` but does not set `SnippetToolPath`, causing `Resolve-Path "$root" | %{ & "${SnippetToolPath}snippet-generator" -b "$_" }` to have the following error:

```
&: azure-sdk-for-net/eng/scripts/Update-Snippets.ps1:44
Line |
  44 |  … lve-Path "$root" | %{ & "${SnippetToolPath}snippet-generator" -b "$_" …
     |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'snippet-generator' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if
     | a path was included, verify that the path is correct and try again.
```

**Expected behavior**
`snippet-generator` should run correctly after being downloaded. The variable `SnippetToolPath` should not only be set when `(-not (Test-Path Env:TF_BUILD))` is `False`.

**Actual behavior (include Exception or Stack Trace)**
`snippet-generator` cannot be found as `SnippetToolPath` is empty and not set to either `%USERPROFILE%\.dotnet\tools\` or `$HOME/.dotnet/tools/`.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Clone the repository.
2. `cd azure-sdk-for-net/eng/scripts` and `pwsh Update-Snippets.ps1`.

**Environment:**
 - Windows Subsystem on Linux 2

**Comment by lynshi** [comment]
By the way, if `PATH` contains `$HOME/.dotnet/tools`, then this bug is masked. Not sure if you would generally expected `PATH` to include the folder though.

**Comment by chidozieononiwu** [comment]
What OS exactly are you using. 
The install of snippet generator in that script is a global install which should automatically add it to the path.

**Comment by lynshi** [comment]
I'm using Ubuntu 20.04 on WSL2. Incidentally, I just tried it out in PowerShell on Windows and it worked.

The [documentation](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-install#description) for `dotnet tool install` just says the tool is installed into the default directory of `$HOME/.dotnet/tools` or `%USERPROFILE%\.dotnet\tools`, which doesn't imply anything is added to the path automatically. It appears `env:Path` on Windows has `%USERPROFILE%\.dotnet\tools` appended while `PATH` on Linux does not contain `$HOME/.dotnet/tools`, so maybe there is something different about how the respective installers set up the system.

**Comment by chidozieononiwu** [comment]
Ok, I see. I will work to fix it for Ubuntu
