### ISSUE TITLE
[Tables] CustomizeSerialization failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23767]
Tables nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : This request is not authorized to perform this operation using this permission.
> RequestId:a9d057a4-8002-00a5-550c-9f27a7000000
> Time:2021-09-01T08:33:54.7971556Z
> Status: 403 (Forbidden)
> ErrorCode: AuthorizationPermissionMismatch
> 
> Content:
> {"odata.error":{"code":"AuthorizationPermissionMismatch","message":{"lang":"en-US","value":"This request is not authorized to perform this operation using this permission.\nRequestId:a9d057a4-8002-00a5-550c-9f27a7000000\nTime:2021-09-01T08:33:54.7971556Z"}}}
> 
> Headers:
> Cache-Control: no-cache
> Transfer-Encoding: chunked
> Server: Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0
> x-ms-request-id: a9d057a4-8002-00a5-550c-9f27a7000000
> x-ms-client-request-id: 8e8ea813-cbd0-4a3e-b9ff-6758387f9d50
> x-ms-version: REDACTED
> X-Content-Type-Options: REDACTED
> Preference-Applied: REDACTED
> Date: Wed, 01 Sep 2021 08:33:54 GMT
> Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8
> 
> 
> Stack trace
>    at Azure.Data.Tables.TableRestClient.InsertEntityAsync(String table, Nullable`1 timeout, Nullable`1 responsePreference, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken) in /_/sdk/tables/Azure.Data.Tables/src/Generated/TableRestClient.cs:line 937
>    at Azure.Data.Tables.TableClient.AddEntityAsync[T](T entity, CancellationToken cancellationToken) in /_/sdk/tables/Azure.Data.Tables/src/TableClient.cs:line 561
>    at Azure.Data.Tables.Samples.TablesSamples.CustomizeSerialization() in D:\a\_work\1\s\sdk\tables\Azure.Data.Tables\tests\samples\Sample8_CustomizingSerialization.cs:line 55
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1076476&view=results

@jsquire for notification.

**Comment by christothes** [comment]
This is a transient environment issue
