### ISSUE TITLE
[Servicebus] TransactionalSendRollback(False,True) failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23766]
Servicebus nightly test runs are failing with:

> Error message
> Azure.Messaging.ServiceBus.ServiceBusException : Connection timed out ErrorCode: TimedOut (ServiceCommunicationProblem)
> ----> System.Net.Sockets.SocketException : Connection timed out
> 
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(IEnumerable`1 messages, TimeSpan timeout, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpSender.cs:line 286
>    at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendAsync>b__20_0>d.MoveNext() in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpSender.cs:line 313
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__20`1.<<RunOperation>b__20_0>d.MoveNext() in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 113
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 144
>    at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 164
>    at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 110
>    at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendAsync(IReadOnlyList`1 messages, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpSender.cs:line 310
>    at Azure.Messaging.ServiceBus.ServiceBusSender.SendMessagesAsync(IEnumerable`1 messages, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusSender.cs:line 211
>    at Azure.Messaging.ServiceBus.ServiceBusSender.SendMessageAsync(ServiceBusMessage message, CancellationToken cancellationToken) in /_/sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusSender.cs:line 163
>    at Azure.Messaging.ServiceBus.Tests.Transactions.TransactionLiveTests.TransactionalSendRollback(Boolean partitioned, Boolean sessionEnabled) in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs:line 172
>    at Azure.Messaging.ServiceBus.Tests.Transactions.TransactionLiveTests.TransactionalSendRollback(Boolean partitioned, Boolean sessionEnabled) in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs:line 184
>    at Azure.Messaging.ServiceBus.Tests.Transactions.TransactionLiveTests.TransactionalSendRollback(Boolean partitioned, Boolean sessionEnabled) in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Transactions/TransactionLiveTests.cs:line 185
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass5_0.<RunTestOnSeparateThread>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
> --- End of stack trace from previous location whe

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1071995&view=results

@jsquire for notification.

**Comment by JoshLove-msft** [comment]
Seems to have been a transient issue - passing consistently since then.
