### ISSUE TITLE
[BUG] Microsoft.Azure.WebJobs.Extensions.ServiceBus used with managed identity produces errors during both build and development runtime

### ISSUE THREAD

**Issue by ilya-git** [Azure/azure-sdk-for-net#23768]
**Describe the bug**
If I use the described method of connecting using `DefaultAzureCredential` / `ManagedIdentity` I get warnings both during the build and runtime. 

**Expected behavior**
No warnings as this is the supported scenario described in the documentation.

**Actual behavior (include Exception or Stack Trace)**
Warning during the build:

> C:\Users\myuser\.nuget\packages\microsoft.net.sdk.functions\3.0.11\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): Warning  : Function [MyFunction]: cannot find value named 'MyConnectionString' in local.settings.json that matches 'connection' property set on 'serviceBusTrigger'

Warning during runtime:

> Warning: Cannot find value named 'MyConnectionString' in local.settings.json or User Secrets that matches 'connection' property set on 'serviceBusTrigger' in 'C:\Source\myproject\bin\Debug\netcoreapp3.1\MyFunction\function.json'. You can run 'func azure functionapp fetch-app-settings <functionAppName>' or specify a connection string in local.settings.json
>  or User Secrets.

**To Reproduce**

1. Create a function MyFunction with a service bus trigger:

```csharp
[FunctionName("MyFunction")]
public async Task Run
(
    [ServiceBusTrigger(
        "%MyTopicName%",
        "%MySubscriptionName%",
        Connection = "MyConnectionString")]
    ServiceBusReceivedMessage receivedMessage
)
```

2. Add a fully qualifed namespace in the local.settings.json as described in the documentation:

```json
"Values": {
    "MyConnectionString__fullyQualifiedNamespace": "sb-my-servicebus.servicebus.windows.net"
}
```

3. Build and run and see warnings during both processes

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0-beta5
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10, Microsoft.AspNetCore.App 5.0.9
 - IDE and version : Rider 2021.2.1

**Notes:**
I am assuming that the library is using `DefaultAzureCredential` and it makes sense to use it locally (with e.g. Azure CLI login). If this is not possible, then at least the runtime warning is correct, and maybe it should be a feature request instead to support `DefaultAzureCredential` and not just managed identity

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
@fabiocav - do you know if the Core Tools fix to relax this validation is available yet?

**Comment by JoshLove-msft** [comment]
I believe this is fixed in the latest release - https://www.npmjs.com/package/azure-functions-core-tools/v/3.0.3734
