### ISSUE TITLE
[Servicebus] StopProcessingAllowsCallbackToComplete failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#23765]
Servicebus nightly test runs are failing with:

> Error message
> Expected: null
> But was:  <{MessageId:c629c4bb-5ad9-4e14-b6ed-4a247b20b864}>
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Processor.ProcessorLiveTests.StopProcessingAllowsCallbackToComplete() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/ProcessorLiveTests.cs:line 592
>    at Azure.Messaging.ServiceBus.Tests.Processor.ProcessorLiveTests.StopProcessingAllowsCallbackToComplete() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/ProcessorLiveTests.cs:line 592
>    at Azure.Messaging.ServiceBus.Tests.Processor.ProcessorLiveTests.StopProcessingAllowsCallbackToComplete() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/ProcessorLiveTests.cs:line 592
>    at Azure.Messaging.ServiceBus.Tests.Processor.ProcessorLiveTests.StopProcessingAllowsCallbackToComplete() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/ProcessorLiveTests.cs:line 593
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass5_0.<RunTestOnSeparateThread>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1071995&view=results

@jsquire for notification.

**Comment by JoshLove-msft** [comment]
Seems to have been a transient issue - passing consistently since.
