### ISSUE TITLE
Outdated Power BI Client Documentation

### ISSUE THREAD

**Issue by abbgrade** [Azure/azure-sdk-for-net#23763]
This documentation is helpful, but outdated and hard to find.
Please update it for v3 and add a link on https://www.nuget.org/packages/Microsoft.PowerBI.Api/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5f23ae7f-4493-e285-c093-6fa10e20cbcc
* Version Independent ID: f3a805d2-5c34-ab67-41a8-a8880917dae2
* Content: [Power BI Embedded libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/powerbi-embedded?view=azure-dotnet)
* Content Source: [api/overview/azure/powerbi-embedded.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/powerbi-embedded.md)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
@CamSoper: Would you mind taking a look or helping to route to the right contact?

**Comment by CamSoper** [comment]
@ali-hamud @MahirDiab @laurent-mic  Hello recent contributors to Microsoft/PowerBI-CSharp! 

Would somebody be able to please help us update [this overview](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/powerbi-embedded?view=azure-dotnet)? Looks like it's pretty out of date.
