### ISSUE TITLE
We should document proxy configuration

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#23774]
We should document that we support these proxy environment variables:

https://github.com/Azure/azure-sdk-for-net/blob/df05d84fdc1842df1b3ec9031d4e28aef1de7cfb/sdk/core/Azure.Core/src/Pipeline/Internal/HttpEnvironmentProxy.cs#L16-L24

We [already have a section](https://github.com/Azure/azure-sdk-for-net/blob/df05d84fdc1842df1b3ec9031d4e28aef1de7cfb/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy) that talks briefly about proxy configuration where we could put these, but I wonder if a dedicated section on general networking (perhaps more in Pipeline.md?) would be better.

On a related note, we should probably also document `ClientOptions.Default` - at least as an alternative to setting up a proxy for all clients in case they have a custom proxy where the environment variables may not work properly, or otherwise have custom auth.

**Comment by pakrym** [comment]
We can reference/copy https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-6.0#remarks

**Comment by heaths** [comment]
Did we replicate that functionality to support < netcoreapp3.0 (based on the "applies to" section)? Copying seems appropriate to me. A reference might update when we don't.

**Comment by pakrym** [comment]
Yep: https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/core/Azure.Core/src/Pipeline/Internal/HttpEnvironmentProxy.cs
