### ISSUE TITLE
[BUG] Missing Slot Version of CreateOrUpdateSwiftVirtualNetworkConnectionWithCheck in Microsoft.Azure.Management.WebSites 3.1.1

### ISSUE THREAD

**Issue by AJAnderhub** [Azure/azure-sdk-for-net#23779]
**Describe the bug**
There is no function corresponding to the API for "Web Apps - Create Or Update Swift Virtual Network Connection Slot"  https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/create-or-update-swift-virtual-network-connection-slot in the SDK Microsoft.Azure.Management.WebSites 3.1.1

The functions `DeleteSwiftVirtualNetworkSlotAsync` and `GetSwiftVirtualNetworkConnectionSlotAsync` (and their non-async versions) already exist but there seems to be missing some functions that would be named something like this:  `CreateOrUpdateSwiftVirtualNetworkConnectionSlotWithCheckAsync` (as well as the non-async version)  https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/websites/Microsoft.Azure.Management.WebSites/src/Generated/WebAppsOperationsExtensions.cs

This create function changed names from from `CreateOrUpdateSwiftVirtualNetworkConnectionAsync` in version 3.1.0 to `CreateOrUpdateSwiftVirtualNetworkConnectionWithCheckAsync` and it does not seem like the `Slot` version made it through the revision.

**Environment:**
 - Microsoft.Azure.Management.WebSites 3.1.1 
 - Windows 10 .NET Core 3.1
 - Visual Studio 16.11.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@AJAnderhub the CreateOrUpdate has been removed since 2020-12-1 this is why this operation was removed from sdk, please check here https://github.com/Azure/azure-rest-api-specs/tree/main/specification/web/resource-manager/Microsoft.Web/stable
