### ISSUE TITLE
Test Recording: TenantId=<tenantId> is not recognized in the environment variable string

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-sdk-for-net#2378]
The AADTenant key/value pair does not properly parse a string that uses TenantId=<tenantId>. In order for me to get it to work I needed to be explicit in the format:
AADTenant=<tenantId>.

We should allow the user to put in the key name that we use everywhere else, which is TenantId.

**Comment by markcowl** [comment]
won't fix.  Use AADTenant
