### ISSUE TITLE
Unclear what the format of the json string is supposed to be.

### ISSUE THREAD

**Issue by LeonLamMS** [Azure/azure-sdk-for-net#23806]
It is unclear what the format of the json string is supposed to be. Reading a json file into a string with File.ReadAllText(paramPath) does not work, and the documentation is not very helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2024d768-b80d-f542-50bb-3ffb578d8ba7
* Version Independent ID: 680045a8-d336-255a-e873-bd82baeb64e4
* Content: [IWithParameters.WithParameters Method (Microsoft.Azure.Management.ResourceManager.Fluent.Deployment.Update) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.deployment.update.iwithparameters.withparameters?view=azure-dotnet#Microsoft_Azure_Management_ResourceManager_Fluent_Deployment_Update_IWithParameters_WithParameters_System_String_)
* Content Source: [xml/Microsoft.Azure.Management.ResourceManager.Fluent.Deployment.Update/IWithParameters.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ResourceManager.Fluent.Deployment.Update/IWithParameters.xml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@xboxeer please help to follow up this docs issue
