### ISSUE TITLE
[QUERY] Empty blob creation in BlockBlobClient.OpenWrite

### ISSUE THREAD

**Issue by razorenov** [Azure/azure-sdk-for-net#23802]
**Query/Question**
While migrating from v11 Storage SDK, we've noticed, that BlockBlobClient.OpenWrite method now makes an additional API request before creating the write stream. Looking at [the code](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs#L2622), it seems that this method creates an empty blob before returning the stream. At the first glance it looks like an unnecessary API request that does not affect the functionality of this method. Could you please clarify, what is the rationale behind this behaviour?

**Environment:**
Azure.Storage.Blobs 12.9.1

**Comment by jsquire** [comment]
Thanks for the feedback! We are routing this to the appropriate team for follow-up. cc @xgithubtriage.
<details>
<summary>Issue Details</summary>
<hr />

**Query/Question**
While migrating from v11 Storage SDK, we've noticed, that BlockBlobClient.OpenWrite method now makes an additional API request before creating the write stream. Looking at [the code](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs#L2622), it seems that this method creates an empty blob before returning the stream. At the first glance it looks like an unnecessary API request that does not affect the functionality of this method. Could you please clarify, what is the rationale behind this behaviour?

**Environment:**
Azure.Storage.Blobs 12.9.1

<table>
  <tr>
    <th align="left">Author:</th>
    <td>ppekrol</td>
  </tr>
  <tr>
    <th align="left">Assignees:</th>
    <td>-</td>
  </tr>
  <tr>
    <th align="left">Labels:</th>
    <td>

`Storage`, `Service Attention`, `Client`, `needs-triage`, `customer-reported`, `question`, `needs-team-attention`

</td>
  </tr>
  <tr>
    <th align="left">Milestone:</th>
    <td>-</td>
  </tr>
</table>
</details>

**Comment by tpajurek-dtml** [comment]
Is there any progress on this? We are seeing increase in requests for the blob storage that seem to be completely unnecessary (if not using leases). This increase is very significant when uploading smaller blobs, effectively making the new SDK unusable for us.

Also, these requests was not there in the previous version of SDK.

Permalink for the relevant code section: https://github.com/Azure/azure-sdk-for-net/blob/80e82be340bbf006cad1822cbf5243c59278b750/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs#L2764

**Comment by amishra-dev** [comment]
@tpajurek-dtml we acknowledge the bug, we will fix this in our January release. 
/cc @seanmcc-msft

**Comment by amishra-dev** [comment]
This was fixed. Please reactivate if you disagree.
