### ISSUE TITLE
Pointless page

### ISSUE THREAD

**Issue by Sectaur** [Azure/azure-sdk-for-net#23805]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba0a1d89-3377-deef-faf6-8d73cba667e7
* Version Independent ID: 0d322b99-0aeb-8dcd-41be-0cadbd07d96b
* Content: [ClientApplicationBase.UserTokenCache Property (Microsoft.Identity.Client) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.clientapplicationbase.usertokencache?view=azure-dotnet#Microsoft_Identity_Client_ClientApplicationBase_UserTokenCache)
* Content Source: [xml/Microsoft.Identity.Client/ClientApplicationBase.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Client/ClientApplicationBase.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
//cc: @nonik0, @anaismiller

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by nonik0** [comment]
@jsquire I took a look at this and looks like it's an MSAL page. I don't have a recent contact with them, can you cc that team please?

**Comment by jsquire** [comment]
Thanks, @nonik0.   I appreciate the assist.

**Comment by jsquire** [comment]
This issue has been transferred to the MSAL repository as [#2872](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2872).   Closing this out.
