### ISSUE TITLE
[FEATURE REQ] App Service Support for Availability Zones

### ISSUE THREAD

**Issue by Rookian** [Azure/azure-sdk-for-net#23801]
As mentioned here https://azure.github.io/AppService/2021/08/25/App-service-support-for-availability-zones.html we can use Availability Zones for Azure App Services.

How can we activate this feature when using the old or/and new Azure SDK?

Old SDK:
"Microsoft.Azure.Management.Fluent" Version="1.37.0" 
"Microsoft.Azure.Management.ResourceManager.Fluent" Version="1.37.0"

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by weidongxu-microsoft** [comment]
New .NET SDK will be available at https://aka.ms/azsdk/dotnet/mgmt

**Comment by weidongxu-microsoft** [comment]
New SDK will be `Azure.ResourceManager.AppService`. It is not yet released.

Code here https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/websites/Azure.ResourceManager.AppService

Create: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/websites/Azure.ResourceManager.AppService/tests/TestsCase/AppServicePlanOperationsTests.cs#L22

ZoneRedundant: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/websites/Azure.ResourceManager.AppService/src/Generated/AppServicePlanData.cs#L142

**Comment by ArthurMa1978** [comment]
The new SDK is released now [Azure.ResourceManager.AppService](https://www.nuget.org/packages/Azure.ResourceManager.AppService/)
