### ISSUE TITLE
ManagedIdentityCredential for Service Bus throwing error

### ISSUE THREAD

**Issue by kisalay19** [Azure/azure-sdk-for-net#23808]
I am trying to implement, managed identity authentication using the Azure SDK .NET in my C# application to establish connectivity to Service Bus and Send a Message to it but getting the error as below

**Error Message**: **_ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found_**

Below is my code snippet.

```csharp
...
//Creation Service Bus Client connection
var serviceBusClientOptions = new ServiceBusClientOptions();
serviceBusClientOptions.TransportType = ServiceBusTransportType.AmqpWebSockets;
ManagedIdentityCredential managedIdentityCredential = new ManagedIdentityCredential("<My App Registration Client Id>");
var serviceBusClient = new ServiceBusClient("myservicebus.servicebus.windows.net", managedIdentityCredential , serviceBusClientOptions);

//Sending Message to queue
var serviceBusSender = serviceBusClient.CreateSender("testsb");
var serviceBusMessage = new ServiceBusMessage("TestMessage");
serviceBusMessage.ContentType = "Text/Plain";
serviceBusSender.SendMessageAsync(serviceBusMessage);
...
```

I am using the packages with below version :
.NET Core 3.1
Azure.Messaging.ServiceBus 7.2.1
Azure.Identity 1.4.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kisalay19** [comment]
@christothes I am executing the code directly in my Visual Studio IDE as a class library. A Web API is consuming this library.

A note, if I replace ManagedIdentityCredential with ClientSecretCredential in that case message sending works but I am more interested in making this ManagedIdentityCredential work. Am I missing anything?

**Comment by christothes** [comment]
> @christothes I am executing the code directly in my Visual Studio IDE as a class library. A Web API is consuming this library.
> 
> A note, if I replace ManagedIdentityCredential with ClientSecretCredential in that case message sending works but I am more interested in making this ManagedIdentityCredential work. Am I missing anything?

Ah - if you are running this locally in Visual Studio, then what you are experiencing is expected. The Managed Identity credential only works inside an Azure environment. If you were to deploy that code to a Web App that has a system assigned Managed Identity, it should work. 

This is one of the main reasons that `DefaultAzureCredential` is used. It falls back to other credentials when the MI credential is not available, but tries it first so that if the code is deployed to Azure, it works as expected.
