### ISSUE TITLE
Azure SDK 2.9.5 Release notes

### ISSUE THREAD

**Issue by centur** [Azure/azure-sdk-for-net#2380]
Hi,
There is Azure SDK 2.9.5 in the pipeline for about a month (VS update says it's available since 30 Aug).
Is there any place where we can read what's changes are in  - Release notes are missing from Github, ms pages and can't be found with Google.

Upd: Also see discussion in comments here - seems that there is some issues with installer
https://azure.microsoft.com/en-us/documentation/articles/azure-sdk-dotnet-release-notes-2-8/

**Comment by markcowl** [comment]
@centur This repository is for the azure management libraries, and not the Azure SDK webpi feed.  Please submit this report to the Azure forum.
