### ISSUE TITLE
Domain in example is not owned by Microsoft

### ISSUE THREAD

**Issue by avwolferen** [Azure/azure-sdk-for-net#23813]
The given example mentions "myvault.azure.vaults.net", the domain vaults.net is not even owned by Microsoft and mistakes happen when people implement this. If you happen to implement this in your own code and not use the proper Vault URI then your or your managed identity token might get compromised if the receiving endpoint captures this.

Please update the example with at least the proper example domain like "https://myvault.vault.azure.net/"

The wrong uri is also given in examples on stackoverflow. https://www.google.com/search?q=%22azure.vaults.net%22

Best regards,
Alex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f73df56-2312-5851-7b59-3dfb766e5f66
* Version Independent ID: 31be349e-063e-6696-bc5f-752c413fa079
* Content: [Azure Identity client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme#authenticating-with-the-defaultazurecredential)
* Content Source: [api/overview/azure/identity-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/identity-readme.md)
* Service: **identity**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.
