### ISSUE TITLE
Azure Messaging Eventgrid (4.6.0) issue with JObject in data property

### ISSUE THREAD

**Issue by SahinOzdemir** [Azure/azure-sdk-for-net#23810]
We have been using Microsoft.Azure.Eventgrid 3.2.x package for quite a while now in our function projects to publish messages. 
When publishing, we use a JObject to fill the data property of the EventGridEvent, works like a charm as shown in the following example

`var data = new JObject
            {
                {"fileId", fileId},
                {"fileName", fileName}
            };`

and later on this JObject is used as
`var eventGridEvent = new EventGridEvent(
                Guid.NewGuid().ToString(),
                subject,
                **someJObject**,
                eventType,
                DateTime.Now,
                "1.0"
            );`

Last week we saw that this nuget package has been deprecated and we needed to move to the new Azure Messaging Eventgrid 4.6.x nuget package so we did.
When using empty JObjects in some cases (just sending a notification that something is ready for processing), we also use the above code, which breaks (new method signature isn't reflected in above example). In run time, we get the error: **The collection type 'Newtonsoft.Json.Linq.JObject' is not supported.**

When we do some modifications to use a json string instead, all quotation marks get translated to unicode formatting (even when specifying the formatter to None). The Microsoft Docs example to use objects and serialize them might be an option, but requires quite some code changes.

In the end, this left us in a non working situation on production, where we had to rollback to the old package. 

Any idea if JObject support for the data element will be back into support? Is this just some bug that needs to be resolved, or is this by design?

Awaiting your responses.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @SahinOzdemir,
The Azure.Messaging.EventGrid library uses System.Text.Json by default for serializing objects to JSON. This is by design as the Azure.* libraries will not depend on NewtonSoft.Json. In order to use NewtonSoft types directly, you would need to use the constructor that accepts a `BinaryData` instance, and serialize the JObject to BinaryData by using the [Microsoft.Azure.Core.NewtonSoftJson](https://www.nuget.org/packages/Microsoft.Azure.Core.NewtonsoftJson/) package.

```c#
var serializer = new NewtonsoftJsonObjectSerializer();
var evt = new EventGridEvent(
  "Subject",
  "Microsoft.MockPublisher.TestEvent",
  "1.0",
  serializer.Serialize(new JObject { {"fileId", fileId}, {"fileName", fileName} }));
```

Alternatively, you can parse your JSON string into a JsonElement (from System.Text.Json):
```c#
var data = JsonDocument.Parse(new JObject { {"fileId", "id1"}, {"fileName", "name1"} }.ToString()).RootElement;
var evt = new EventGridEvent(
  "Subject",
  "Microsoft.MockPublisher.TestEvent",
  "1.0",
  data);
```

**Comment by JoshLove-msft** [comment]
@pakrym pointed out that in .NET 6.0 (which is still in preview), there is a JsonNode type being included in System.Text.Json which should have similar semantics to the JObject so swapping out those types would be a third option.

**Comment by SahinOzdemir** [comment]
Hi,

Thanks for your quick responses! I'll check if the provided solution solves our issue.

**Comment by SahinOzdemir** [comment]
Above approach seems to work, and is a minor adjustment in code.

Thanks for the support and I'll close the issue
