### ISSUE TITLE
[ACR] [BlobClient] Upload manifest directly as stream

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#23827]
There is a bug in the ACR service preventing us from exposing a method to allow users to uploading a manifest from a file stream directly.  The team is working on this.

https://msazure.visualstudio.com/AzureContainerRegistry/_workitems/edit/10780642 

Once this is fixed, we can re-enable the `UploadManifest(stream)` overload.  It was previously written to deserialize/serialize to `OciManifest` to workaround this issue, but with the stream upload available, we can take a more streamlined approach.

**Comment by annelo-msft** [comment]
Exposing this in the public API has been requested by the Bicep team as well.

@majastrz FYI

**Comment by majastrz** [comment]
Btw, does this include downloading the OCI manifest as a stream also?

**Comment by annelo-msft** [comment]
@Mohit-Chakraborty FYI

This issue itself is concerned only with blob upload.

**Comment by annelo-msft** [comment]
The Stream overload of UploadManifest is functional and has test coverage.
