### ISSUE TITLE
[ACR] [BlobClient] Implement standard .NET download pattern in ContainerRegistryBlobClient

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#23826]
Use Storage Blobs library as a model:

- [ ] Investigate the need to implement `RetriableStream` in `DownloadBlobResult`
- [ ] Implement `IDisposable` on `DownloadManifestResult` and `DownloadBlobResult`

**Comment by pallavit** [comment]
@annelo-msft - I believe our new API supports this scenario already so going ahead and closing this one. Please let me know if this is tracking something else and we need to reopen this issue.
