### ISSUE TITLE
Improve documentation for TokenCachePersistenceOptions as it relates to AuthenticationRecord

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#23837]
Documentation for `TokenCachePersistenceOptions` should go into more detail explaining how an `AuthenticationRecord` should be used to access entries in a shared cache.

What we need is an e2e example that pieces together the [token cache samples ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md#persisting-credentials-by-configuring-tokencachepersistenceoptions) with the [AuthenticateRecord samples](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md#persisting-user-authentication-data)

**Comment by pallavit** [comment]
@christothes is this still valid?
