### ISSUE TITLE
[ACR] [BlobClient] Enable manifest download by tag

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#23831]
Since we currently only support manifest download by digest, users currently must take the following steps to download a manifest by its tag:

```csharp
ContainerRegistryClient registryClient = new ContainerRegistryClient(new Uri("example.azurecr.io"), new DefaultAzureCredential());
var tagProperties = registryClient.GetArtifact(repository, tag).GetTagProperties(tag);
manifestResponse = await client.DownloadManifestAsync(tagProperties.Value.Digest);
```

We should update `DownloadManifestAsync` to work with either a digest or a tag.

**Comment by majastrz** [comment]
Doing this will also eliminate one REST call, which is always nice.

**Comment by annelo-msft** [comment]
@Mohit-Chakraborty FYI

**Comment by annelo-msft** [comment]
Either Tag or Digest can be specified in [DownloadManifestOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/DownloadManifestOptions.cs#L11)
