### ISSUE TITLE
[FEATURE REQ] Allow BlobClient.UploadAsync to use PUT Blob even when using client-side encryption

### ISSUE THREAD

**Issue by gocha** [Azure/azure-sdk-for-net#23860]
**Library or service name.**
Azure.Storage.Blobs

**Is your feature request related to a problem? Please describe.**
I hope to perform small uploads using PUT Blobs, even when using client-side encryption.

As mentioned in #22593, `BlockBlobClient` internally chooses and calls PUT Blob or PUT Block depending on the input. It seems that PUT Blob is chosen if the input is seekable and the size does not exceed `InitialTransferSize`, but this is not the case if client encryption is enabled.

```cs
using Azure.Storage.Blobs.Specialized;

BlobClient plaintextBlob;
ClientSideEncryptionOptions encryptionOptions;
BlobClient blob = plaintextBlob.WithClientSideEncryptionOptions(encryptionOptions);

BinaryData smallBinaryData;
await blob.UploadAsync(smallBinaryData); // always uploaded with PUT Block?
```

This behavior is actually commented as "content is now unseekable, so PartitionedUploader will be forced to do a buffered multipart upload" in the [StagedUploadInternal](https://github.com/Azure/azure-sdk-for-net/blob/29fbb4f3c5e51044e670a88aeda448018d017471/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L1627). The non-seekable `CryptoStream` returned by `ClientSideEncryptInternal` will be used for uploads, so multipart upload will always be selected.

I am not happy with the fact that the PUT Block is selected even when the content is very small and seekable. If I understand correctly, the PUT Block is less efficient than the PUT Blob because the former sends one request and the latter sends two requests, `BlockBlobClient.StageBlock` and `BlockBlobClient.CommitBlockList`. I don't understand how the upload works in Blob Storage v11, but I believe that in v11, small data encryption and upload was completed in a single request.

Thanks for reading.

**Comment by jaschrep-msft** [comment]
Hi, @gocha.

This is an understandable feature request and should be doable if the stream passed to the client was seekable to begin with. I have logged it for future development.

However, I cannot speak here to a general-case solution for #22593 where the initial stream was unseekable to begin with. That conversation will need to continue over there.
