### ISSUE TITLE
Refactor TenantIdResolver calls to avoid duplication of code.

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#23866]
All credentials which support multi-tenant authentication now have to call `TenantIdResolver.Resolve` before acquiring a token. We should investigate if we can refactor this logic into a shared place, possibly inside `MsalConfidentialClient` and `MsalPublicClient`

**Comment by pallavit** [comment]
@christothes , @schaabs is this still valid?
