### ISSUE TITLE
[BUG] Memory leak when uploading large file (~500mb) to blob storage from Blazor WASM 

### ISSUE THREAD

**Issue by jonganej** [Azure/azure-sdk-for-net#23863]
**Describe the bug**
Following the advice on the [ASP.NET Core Blazor file uploads](https://docs.microsoft.com/en-us/aspnet/core/blazor/file-uploads?view=aspnetcore-5.0&pivots=webassembly), passing a stream from `IBrowserFile.OpenReadStream` to `BlobClient.UploadAsync` results in the file being loaded into memory and remains even after upload process was completed.

**Expected behavior**
Memory usage on page should return to pre-upload levels.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Check memory heap using browser's memory profiler tool
2. Upload a large file on Blazor WASM that uses `Azure.Storage.Blobs` SDK to upload to Blob Storage
3. Check memory heap again. The heap usage remains at a high level, relative to the size of the file uploaded.

**Environment:**
 - `Azure.Storage.Blobs` 12.9.1
 - Blazor WASM .NET 5

**Comment by amishra-dev** [comment]
@kasobol-msft Kamil, could you kindly look at this?

**Comment by kasobol-msft** [comment]
@jonganej I've tried to reproduce the issue with the following code:
```
@page "/"
@using Azure.Storage.Blobs

<InputFile OnChange="@LoadFiles" multiple />

<p>@message</p>

@code {
    private string message = "";

    private async Task LoadFiles(InputFileChangeEventArgs e)
    {
        try
        {
            message = "Upload in progress";
            var sasUri = "REDACTED";
            var blobServiceClient = new BlobServiceClient(new Uri(sasUri));
            var containerClient = blobServiceClient.GetBlobContainerClient("foo");
            await containerClient.CreateIfNotExistsAsync();
            var blob = containerClient.GetBlobClient("blazor.txt");
            await blob.UploadAsync(e.File.OpenReadStream(1024*1024*1024), overwrite: true);

            message = "Upload complete";
        } catch (Exception err)
        {
            message = err.Message + "<br>" + err.StackTrace;
        }
    }
}
```

I tried uploading 508MB file. The memory in browser remained slightly elevated but the level was around 3MB, i.e. nowhere close to the file size.

![image](https://user-images.githubusercontent.com/61715331/132762249-60a5deab-e1a0-4e9b-8d6e-7e7cec57ddfe.png)


To triage this further. Could you please share the code that reproduces the issue on your end? Please also share screenshots from your debugging session in the browser. Also information about the tools, i.e. browser, profiler used would be great.

**Comment by jonganej** [comment]
@kasobol-msft Thanks for your prompt response! My code is similar to yours (see code snippet), except for the fact that I've also included additional options to monitor progress and handle cancellations of the upload for UX purposes. 

```
@implements IDisposable
@using Azure.Storage.Blobs;

<InputFile id="zip-file" OnChange="@OnFileChanged" accept=".zip" />

@code {
  CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();

  private void OnFileChanged(InputFileChangeEventArgs e)
  {
    var blobClient = new BlobClient(new Uri("mybloburl"));
    var progressHandler = new Progress<long>();
    progressHandler.ProgressChanged += OnProgressChanged;
    fileSizeInBytes = e.File.Size;
    uploadStatus = UploadStatus.InProgress;
    var fileStream = e.File.OpenReadStream(1048576000, cancellationTokenSource.Token);
    var blobContentInfo = await blobClient.UploadAsync(fileStream,
	    progressHandler: progressHandler, cancellationToken: cancellationTokenSource.Token);
    fileStream.Dispose();
  }
}

```

I managed to reproduce the results with your code too. The JS Heap numbers on the performance profiler seem to be in the sane range. My observation is based on the memory snapshot part of the developer tools on MS Edge (see screenshots below). Before uploading, the heap is around 60mb and after upload, it remains at ~900mb. 
Looking at the Browser Task Manager on Edge also shows how the 'Memory' (not the 'Javscript memory' column) rises from around 1000K at page load to 1000000K after uploading is complete.

Maybe I'm looking at wrong numbers here, but 1GB of memory after uploading a file on the heap doesn't seem to be too good. I implemented the same. I also implemented blob upload logic using XHR (as multiple `PUT Block` and a final `PUT Block list` ) with some JSInterop calls and a before / after snapshot of memory seems to be around the same levels.

_Screenshot: Before large file (500MB) upload_
![memoryprofiler_beforeupload](https://user-images.githubusercontent.com/4180997/132826414-49ac290e-43a9-4dcf-9d0a-1b95fc1b9a71.PNG)

_Screenshot: After large file upload:_
![memoryprofiler](https://user-images.githubusercontent.com/4180997/132826501-b62ccf90-7f8b-4a17-b9bb-2419b6364b3c.PNG)

**Comment by kasobol-msft** [comment]
@jonganej 

I have reduced the repro to :
```
@page "/"

<InputFile OnChange="@LoadFiles" multiple />

<p>@message</p>

@code {
    private string message = "";

    private async Task LoadFiles(InputFileChangeEventArgs e)
    {
        try
        {
            message = "Upload in progress";

            using var fileStream = e.File.OpenReadStream(1024 * 1024 * 1024);

            byte[] array = new byte[1024 * 8];
            while (await fileStream.ReadAsync(array) > 0) ;

            message = "Upload complete";
        }
        catch (Exception err)
        {
            message = err.Message + "<br>" + err.StackTrace;
        }
    }
}
```

I.e. I got rid of Storage SDK.

It seems that you're running into https://github.com/dotnet/aspnetcore/issues/35540
