### ISSUE TITLE
[BUG] Fix reference documentation issues in 'Microsoft.Azure.CognitiveServices.Knowledge.QnAMaker'

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#23884]
**Describe the bug**
Enabling ref documentation for the library gives errors on build.

**Expected behavior**
We should be able to generated ref documentation with build.

**To Reproduce**
1. Enable generation of ref docs by removing the exclusion of the library from 'eng\Directory.Build.Common.props'
2. Build the SDK directory.

**Comment by heaths** [comment]
This package is deprecated.
