### ISSUE TITLE
[BUG] Fix reference documentation issues in 'Microsoft.Azure.KeyVault*'

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#23894]
**Describe the bug**
Enabling ref documentation for these libraries gives errors on build.
- 'Microsoft.Azure.KeyVault'
- 'Microsoft.Azure.KeyVault.Core'
- 'Microsoft.Azure.KeyVault.Cryptography'
- 'Microsoft.Azure.KeyVault.Extensions'
- 'Microsoft.Azure.KeyVault.WebKey'

**Expected behavior**
We should be able to generated ref documentation with build.

**To Reproduce**
1. Enable generation of ref docs by removing the exclusion of the libraries from 'eng\Directory.Build.Common.props'
2. Build the SDK directory.

**Comment by heaths** [comment]
All those packages are officially deprecated. Since they are also already [documented](https://docs.microsoft.com/dotnet/api/microsoft.azure.keyvault?view=azure-dotnet-legacy), what would be the reason to generate new documentation for them now? I'd rather not do anything new with them if we can avoid it.

**Comment by Mohit-Chakraborty** [comment]
Users still using the track1 SDK packages complain when they don't find reference documentation for them.
See https://github.com/Azure/azure-sdk-for-net/issues/11798 as an example.

We have made a change to generate docs for all libraries, whereas earlier it was only enabled for track2 libraries.
Some libraries have doc errors during build, and they are kept disabled for now. These bugs are tracking those instances.

Individual library owners can either -
1. Ignore this issue because there isn't enough interest in the track1 packages.
2. Fix the errors and enable generation of ref docs. Then, release an update if/when there is customer demand.

**Comment by heaths** [comment]
Closing for now since we have no plans to generate new packages, but should we, we can resolve this then.
