### ISSUE TITLE
SetSecretAsync gives error "Could not load file or assembly 'System.Text.Encodings.Web"

### ISSUE THREAD

**Issue by kgbuddhima** [Azure/azure-sdk-for-net#23902]
**Describe the bug**

When I call SetSecretAsync() method, I'm having above error.

> Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.5.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

**Expected behavior**
App should save the given secret to Azure vault.

**Actual behavior (include Exception or Stack Trace)**
SetSecretAsync fails with the above exception

Previously I had following error too and I solved after upgrading Azure.Security.KeyVault.Secrets to v 4.2.0

> Method not found: 'System.Text.Json.JsonEncodedText System.Text.Json.JsonEncodedText.Encode(System.String, System.Text.Encodings.Web.JavaScriptEncoder)'.

**To Reproduce**
```
string vaultUrl = MyUrls.ConnectorKeyVaultUrl;

var client = new SecretClient(vaultUri: new Uri(vaultUrl), credential: new DefaultAzureCredential());

result = await client.SetSecretAsync(key, value);

```

**Environment:**
```
<PackageReference Include="JWT" Version="8.2.3" />
<PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
<PackageReference Include="Azure.Identity" Version="1.4.1" />
<PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0" />
```

- Mac OS  - .Net Core 3.1
 - IDE and version : [e.g. Visual Studio mac 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kgbuddhima** [comment]
Now I'm having "_Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.5.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified_". too while the System.Text.Encodings.Web.dll file is available in the bin folder

**Comment by heaths** [comment]
Where is this application running? For example, there's was an issue with Azure Functions that was fixed by requiring an update to the newest Azure Functions SDK (they were pinning to an older version of System.Text.Encodings.Web). If not Azure Functions, check if your application is loading an older version of System.Text.Encodings.Web.

If you need help tracing binding events, see https://docs.microsoft.com/dotnet/core/dependency-loading/collect-details for .NET 5.0 and newer. Prior to that, see https://github.com/dotnet/runtime/blob/main/docs/design/features/host-tracing.md. If even older than that, _fuslogvw.exe_ from the .NET Framework SDK should also work, but you need to run it elevated and enable logging of binding event.

**Comment by kgbuddhima** [comment]
@heaths I'm running the funcrions app on Mac. The app a .net core 3.1 app
when I run the same app on windows machine, it works fine.

**Comment by heaths** [comment]
I'm assuming you mean "functions", but can you clarify what the "functions app" is? Are you talking about the Azure Functions SDK / test host? Did you try updating to the latest Azure Functions SDK or do any host logging?

The Key Vault SDK - all our latest SDKs, actually - will automatically pull in a new versions, but if the host application is ignoring that DLL and loading an older version (which has a security vulnerability), the host application needs to be updated.

**Comment by kgbuddhima** [comment]
@heaths I'm having an azure function app. 

here is the .csproj of it.

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.3" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Microsoft.Azure.WebJobs.Extensions.Storage" />
    <None Remove="System.Text.Encodings.Web" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BusinessLogicLayer\BusinessLogic.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\ModelLibrary\ModelLibrary.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
    <ProjectReference Include="..\UtilityLayer\UtilityLayer.csproj" />
    <ProjectReference Include="..\MyResources\MyResources.csproj">
      <GlobalPropertiesToRemove></GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemGroup>
</Project>
```

**Comment by kgbuddhima** [comment]
And UtilityLayer is the project that I use to connect with the keyvault though the keyvault secrets sdk. 
And here is the csproj file of it.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="AccountPackage\XeroAuthentication.json" />
    <None Remove="AccountPackage\XeroSettings.json" />
    <None Remove="Interfaces\" />
    <None Remove="AccountPackage\" />
    <None Remove="Azure.Security.KeyVault.Keys" />
    <None Remove="Azure.Identity" />
    <None Remove="Azure.Security.KeyVault.Secrets" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AccountPackage\XeroAuthentication.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="AccountPackage\XeroSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="JWT" Version="8.2.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Azure.Identity" Version="1.4.1" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ModelLibrary\ModelLibrary.csproj" />
    <ProjectReference Include="..\MyResources\MyResources.csproj" />
  </ItemGroup>
</Project>
```

**Comment by kgbuddhima** [comment]
**The following issue happens with Microsoft.NET.Sdk.Functions v. _3.0.3_**
Method not found: 'System.Text.Json.JsonEncodedText System.Text.Json.JsonEncodedText.Encode(System.String, System.Text.Encodings.Web.JavaScriptEncoder)'.

**The following issue happens with Microsoft.NET.Sdk.Functions v. _3.0.13_**

Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.5.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

========================================================================

Seems the runtime is unable to find the correct library version.

Actually, the library has installed the following versions.

<img width="356" alt="image" src="https://user-images.githubusercontent.com/14989528/132950753-ddffd34c-8eb1-4e36-9d57-31991ef761be.png">

**Comment by heaths** [comment]
See https://github.com/Azure/azure-sdk-for-net/issues/20942#issuecomment-843399827. Upgrading Microsoft.NET.Sdk.Functions package to 3.0.12 or newer should delete the old System.Text.Encodings.Web from your runtime folder, but if it doesn't you can remove it manually. Rebuilding should not restore it so that the right version deployed by building your app gets loaded.

The problem is not with the Azure SDKs referencing a new assembly, but that the host - Azure Functions in this case - deploying and first loading an older, [insecure](https://github.com/Azure/azure-sdk-for-net/issues/20942#issuecomment-837350998) version

**Comment by kgbuddhima** [comment]
@heaths I tried all of mentioned solutions on my mac.
But nothing worked for me.

Here are the things that I have tried..

1. add following code to the function project's csproj file
```
  <ItemGroup>
    <FunctionsPreservedDependencies Include="Microsoft.AspNetCore.Http.dll" />
    <FunctionsPreservedDependencies Include="Microsoft.AspNetCore.Http.Extensions.dll" />
    <FunctionsPreservedDependencies Include="Microsoft.AspNetCore.Http.Features.dll" />
    <FunctionsPreservedDependencies Include="System.Text.Encodings.Web.dll" />
  </ItemGroup>
```

2. Downgrade Azure.Identity to v 1.3.0 from v 1.4.1
3. Upgrade Microsoft.NET.Sdk.Functions to v 3.0.13

**Comment by heaths** [comment]
Did you manually try deleting the old files? Microsoft.NET.Sdk.Functions is supposed to remove it, but may not. The problem is definitely that the host - Azure Functions - is deploying an loading an older version. The Azure SDKs do not pin to a specific version, only requiring that a certain version or higher is installed. Azure Functions deployed an older version.

If you're not sure which assembly to delete, search your source repository for System.Text.Encodings.Web and delete any copy, then rebuild your solution with the correct version of Microsoft.NET.Sdk.Functions installed.

@fabiocav is there any place else he could look to find and delete the old System.Text.Encodings.Web?

**Comment by kgbuddhima** [comment]
@heaths I created a very basic app without any third-party libraries.

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/14989528/134964112-9855c5e5-4a83-48cc-ab5b-c450c4513cb0.png">

I can share the code if needed

**Comment by heaths** [comment]
You need to be using Microsoft.NET.Sdk.Functions 3.0.12 or newer. I understand that with 3.0.13 you're getting an assembly binding error which means the wrong version of assembly is loaded, and I need to know from where. I posted the [tracing information](https://github.com/Azure/azure-sdk-for-net/issues/23902#issuecomment-917145098) earlier.

I created a new Functions app in VSCode and added the latest Azure SDK packages, so my total PackageReferences are:

```xml
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.4.1" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
  </ItemGroup>
```

Using a `SecretClient` to just show a secret worked fine. I see System.Text.Encodings.Web.dll file version 4.700.32.11602 (assembly version 4.0.5.1) in bin/Debug/netcoreapp3.1.

What versions (and where, exactly) of System.Text.Encodings.Web.dll are in your solution when you build and deploy (even locally)?

**Comment by kgbuddhima** [comment]
@heaths 
mySystem.Text.Encodings.Web.dll is in following path locally.
TestFunction/bin/Debug/netcoreapp3.1/bin

**Comment by kgbuddhima** [comment]
Then I upgraded Microsoft.NET.Sdk.Functions to 3.0.13
and now the file location is different.
TestFunction/bin/Debug**/netcoreapp3.1**/System.Text.Encodings.Web.dll

**Comment by heaths** [comment]
The file version and the assembly version are not aligned. Given how much older that file version is, it's likely not 4.0.5.1. You should delete it - any copies you find - and rebuild. The package should do that, but may not work in all cases, so a complete clean-up and rebuild is necessary.

**Comment by heaths** [comment]
Did you delete any copies of System.Text.Encodings.Web you found? As stated above, the new nupkg *should* remove old versions, but it may not in all cases. The app is loading from the wrong location and that file needs to be deleted. This is not a problem specifically with this SDK, but with assembly loading against the Azure Functions SDK.
