### ISSUE TITLE
StackOverflow if reloadInterval is very small

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-sdk-for-net#23937]
https://github.com/Azure/azure-sdk-for-net/blob/e10ed5d3c1a8fb51609f4d3f12de3b7c0404cf3c/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationProvider.cs#L128

This null check is not thread-safe and fails if the `reloadInterval` is like `TimeSpan.FromTicks(1)` and results in a StackOverflowException

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by cmenzi** [comment]
I think it can be solved, be adding a 

```csharp
await Task.Yield().ConfigureAwait(false);
```

here, before the `while` statement: https://github.com/Azure/azure-sdk-for-net/blob/e10ed5d3c1a8fb51609f4d3f12de3b7c0404cf3c/sdk/extensions/Azure.Extensions.AspNetCore.Configuration.Secrets/src/AzureKeyVaultConfigurationProvider.cs#L59

**Comment by pakrym** [comment]
While technically true, what is the scenario where you need a single tick poll interval?

**Comment by cmenzi** [comment]
Its not a use case. I did my unit test with Timespan.FromTicks(1) and just encounter it.

**Comment by pallavit** [comment]
@jsquire is this still valid? Do you see us fixing this issue in the near future?

**Comment by pallavit** [comment]
Also do we have a project that we use to track Extensions issues?
