### ISSUE TITLE
What Configuration Settings?

### ISSUE THREAD

**Issue by rjarratt** [Azure/azure-sdk-for-net#23949]
The overloads that take a configuration section says it needs "the necessary settings", but it doesn't tell you what those necessary settings are. I thought it might be the settings in JwtBearerOptions and MicrosoftIdentityOptions, but that can't be right because when I use the ASP.NET Core template in Visual Studio it includes an option that is not in either of these classes (CallbackPath). So can we please say what configuration settings are required?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6abd74e1-f841-f4c3-6201-3192c7329ac9
* Version Independent ID: de87694b-b1ac-bcb5-fb5e-9cc67dcf2590
* Content: [MicrosoftIdentityWebApiAuthenticationBuilderExtensions.AddMicrosoftIdentityWebApi Method (Microsoft.Identity.Web) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.microsoftidentitywebapiauthenticationbuilderextensions.addmicrosoftidentitywebapi?view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Identity.Web/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Web/MicrosoftIdentityWebApiAuthenticationBuilderExtensions.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Closing;  this issue has been transferred to the repository where the `Microsoft.Identity.Web` package is maintained as [#1441](https://github.com/AzureAD/microsoft-identity-web/issues/1441).
