### ISSUE TITLE
[BUG] Docs Refer to "Azure Table Service"

### ISSUE THREAD

**Issue by csharpfritz** [Azure/azure-sdk-for-net#23948]
**Describe the bug**
Documentation refers to the non-existent "Azure Table Service" from the "Azure.Data.Tables" NuGet package

**Expected behavior**
Reference the product name "Azure Table Storage" or "Azure Storage"

**Actual behavior (include Exception or Stack Trace)**
Reference to non-existent service on https://www.nuget.org/packages/Azure.Data.Tables

**To Reproduce**
Docs bug at https://www.nuget.org/packages/Azure.Data.Tables

**Comment by csharpfritz** [comment]
Also:  please deprecate other documentation and packages that confusingly refer to this service as "CosmosDb Table Storage" "CosmosDb Tables" 

The following packages should be deprecated and should be replaced with a dependency on this package:
- Microsoft.Azure.Cosmos.Table
- WindowsAzure.Storage
- Microsoft.Azure.CosmosDb.Table
- WindowsAzure.Storage-PremiumTable

**Comment by jsquire** [comment]
//cc: @AlexGhiondea for legacy package deprecation considerations

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @csharpfritz 
The naming of Azure Table Service is intentional since it is not specific to the storage service. 

Regarding the older package depreciation, this work is underway. Cc @mario-guerra

**Comment by csharpfritz** [comment]
Are there links or references that will help developers find this package?

The SDK for table service has had breaking changes, name changes, package re-issuing and very little way for our customers to be able to keep track of when and why they should make these changes.

Are there benefits for our customers to use this package over one of the deprecated ones if they're using Azure Storage Tables?



- Jeff
________________________________

**Comment by christothes** [comment]
> Are there links or references that will help developers find this package?

Yes, there is an effort underway to fixup all the docs to refer to the new packages and ensure all the examples are up to date. 

> The SDK for table service has had breaking changes, name changes, package re-issuing and very little way for our customers to be able to keep track of when and why they should make these changes.

Whether to make the change or when to do so for existing code bases is very much dependent on the specific scenario.  But for new code bases the default choice should be the new SDK.  You can find a migration guide [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/MigrationGuide.md).

> Are there benefits for our customers to use this package over one of the deprecated ones if they're using Azure Storage Tables?

Here is a great summary explaining the philosophy and benefits of these newer SDKs https://www.youtube.com/watch?v=38RYIx7a2M4

**Comment by jsquire** [comment]
> Are there benefits for our customers to use this package over one of the deprecated ones if they're using Azure Storage Tables?

Just to chime in, in addition to the video that Chris suggested:

For new development, we would recommend using the `Azure.Data.Tables` package and the `Azure.[[ AREA ]].[[ SERVICE ]]` packages for other services.   The legacy packages will continue to be supported with bug fixes and critical updates for the foreseeable future.  Unfortunately, I don't have definitive date to share, but it's safe to say that the timeline is most likely measured in years.  That said, at some point in the near future, it will stop receiving new features and enhancements.  Unfortunately, once again, I don't have a firm timeline.

With respect to the motivations and differences, as Azure has matured and been embraced by a more diverse group of developers, we have been focused on learning the patterns and practices to best support developer productivity and to understand the gaps that the .NET client libraries have.

There were several areas of consistent feedback expressed across the Azure client library ecosystem.  One of the most important is that the client libraries for different Azure services have not had a consistent approach to organization, naming, and API structure.  Additionally, many developers have felt that the learning curve was difficult, and the APIs did not offer a good, approachable, and consistent onboarding story for those learning Azure or exploring a specific Azure service.

To try and improve the development experience across Azure services, a set of uniform [design guidelines](https://azure.github.io/azure-sdk/general_introduction.html) was created for all languages to drive a consistent experience with established API patterns for all services.  A set of [.NET-specific guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html) was also introduced to ensure that .NET clients have a natural and idiomatic feel that mirrors that of the .NET base class libraries.  Further context, rationale, and details are available in the linked guidelines.
