### ISSUE TITLE
How to view raw request uri and content before sending (for debuging)

### ISSUE THREAD

**Issue by jmerkow** [Azure/azure-sdk-for-net#23940]
I am debugging a few endpoints and I would like to view the request content (json).  For the life of me, I cannot seem to figure out how to do this.  I am most interested in looking at the Request content.

Sorry I meant to post this to autorest.csharp,  This is for a C# generated client.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AlexGhiondea** [comment]
@AlexanderSher or @ShivangiReja can you help here?

**Comment by AlexanderSher** [comment]
In your generated `*RestClient`, there should be a call to `await _pipeline.SendAsync(message` (or `_pipeline.Send(message` if you're using sync version). From there you can use `message.Request.Content`.

Or, if you need to debug how the content is created, you can look for the `CreateXXXRequest` methods where `request.Content` is assigned and go from there.
