### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#23941]
This is a test of a new msftbot change.

**Comment by heaths** [comment]
I'm going to mark this issue as addressed, but please feel free to use the `/unresolve` command should you wish to discuss further.

**Comment by heaths** [comment]
> I'm going to mark this issue as addressed, but please feel free to use the `/unresolve` command should you wish to discuss further.

Thanks.

**Comment by jsquire** [comment]
> I'm going to mark this issue as addressed, but please feel free to use the `/unresolve` command should you wish to discuss further.

One more test, since some time has passed.
