### ISSUE TITLE
[QUERY] User Managed Identity not working

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-sdk-for-net#23954]
**Query/Question**

### Created this issue on behalf of  @dsm4u, please be sure to include them on any questions or replies.

I am trying to use usermanaged identity to access storage account from VM scale set.
Created a managed identity, added it to scaleset and then given storage contribute access to the identity for the storage account.

But when i try to access the storage account via .net console app running on the scaleset instance, it giving authentication error.

The same scenario is working fine for system managed identity,

Can you please advise.

These are the steps I have followed:
1. Created a Manged Identity via portal.
2. In the Virtual Scaleset, went to the identity and added the newly created identity as user assigned identity.
![image](https://user-images.githubusercontent.com/90440178/132994397-03621ff1-3d57-4c4c-a966-263338f25135.png)
3. In the portal, went to the storage account, and in the access control (IAM) added role assignment. In that selected user assigned managed identity and selected the identity created above.
![image](https://user-images.githubusercontent.com/90440178/132994455-c08cce22-3761-470d-9dcf-9fa406383887.png)
4. These are the configuration done on the portal level.
5. Now in the console app used the queue client and tried to access the storage account. and the console app was executed from the scale set instance. code as below:
QueueClient queueClient = new QueueClient(queueUri, new DefaultAzureCredential(false));
var message = queueClient.ReceiveMessage();

Please do let me know if any other details required on this.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @dsm4u - Can you verify that you are setting the `ManagedIdentityClientId` on the `DefaultAzureCredentialOptions` ?

https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#specifying-a-user-assigned-managed-identity-with-the-defaultazurecredential

**Comment by dsm4u** [comment]
I was not but as part of checking all options i did tried specifying that explicitly but it gave same error saying as below:
![image](https://user-images.githubusercontent.com/90440178/133115837-dd23b5ea-a2dd-4628-957c-ba38945d3af3.png)

Code used for that:
string userAssignedClientId = "clientidofidentity";
            var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { ManagedIdentityClientId = userAssignedClientId });
            var tableconn = ConfigurationManager.AppSettings["queuename"];
            Uri QueueUri = new Uri(tableconn);

            Azure.Storage.Queues.QueueClient queueClient = new Azure.Storage.Queues.QueueClient(QueueUri , credential);            
            QueueMessage message = queueClient.ReceiveMessage();

**Comment by christothes** [comment]
That code seems correct. Would you mind providing the logging output after reproducing this with [logging enabled](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md)?

**Comment by dsm4u** [comment]
Can you please advise how to enable the logging for this and capture the logs?

Along with the above error, the stack trace is as below:
![image](https://user-images.githubusercontent.com/90440178/133119620-e4267b5a-4582-4b55-b5ae-ec068e6a556b.png)

**Comment by christothes** [comment]
Sorry, I meant to send this more specific link initially. Check out the Logging section of the readme [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#logging).

**Comment by dsm4u** [comment]
Np, as soon as I posted, seen your link in previous comment.. Thats why deleted my comment :) sorry for that..

So I added the options for enabling logging and re-ran the application and the error content is as below:
![image](https://user-images.githubusercontent.com/90440178/133120982-c6a5473b-921d-433c-bae1-ad6ed9993d7e.png)

**Comment by christothes** [comment]
You should be getting a lot more log output. If you are using App Insights, for example, it should all be there. Otherwise, if console output is not easy to get while deployed, you configure a [custom listener](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#custom-logging-callback).

**Comment by dsm4u** [comment]
please find the details as below:
[Informational] Azure-Identity: DefaultAzureCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] 
[Informational] Azure-Identity: EnvironmentCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] 
[Informational] Azure-Identity: EnvironmentCredential.GetToken was unable to retrieve an access token. Scopes: [ https://storage.azure.com/.default ] Exception: Azure.Identity.CredentialUnavailableException (0x80131500): EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
[Informational] Azure-Identity: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] 
[Informational] Azure-Identity: Probing IMDS endpoint for availability. Endpoint: http://169.254.169.254/metadata/identity/oauth2/token
[Informational] Azure-Identity: IMDS endpoint is available. Endpoint: http://169.254.169.254/metadata/identity/oauth2/token
[Informational] Azure-Core: Request [b7ec4610-eadd-48fe-a498-030337ab9d1d] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED&client_id=REDACTED
Metadata:REDACTED
x-ms-client-request-id:b7ec4610-eadd-48fe-a498-030337ab9d1d
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.1 (.NET Framework 4.7.3850.0; Microsoft Windows 10.0.14393 )
client assembly: Azure.Identity
[Informational] Azure-Core: Response [b7ec4610-eadd-48fe-a498-030337ab9d1d] 200 OK (00.1s)
Content-Length:1713
Content-Type:application/json; charset=utf-8
Date:Mon, 13 Sep 2021 16:37:40 GMT
Server:IMDS/150.870.65.517

[Informational] Azure-Identity: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://storage.azure.com/.default ]  ExpiresOn: 2021-09-14T16:20:16.0000000+00:00
[Informational] Azure-Identity: DefaultAzureCredential.GetToken succeeded. Scopes: [ https://storage.azure.com/.default ]  ExpiresOn: 2021-09-14T16:20:16.0000000+00:00
[Informational] Azure-Core: Request [14183a12-d4f7-4af3-8c89-8fccf2d9193d] GET https://xxxx.queue.core.windows.net/xxx/messages?numofmessages=1
x-ms-version:2018-11-09
Accept:application/xml
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Queues/12.8.0 (.NET Framework 4.7.3850.0; Microsoft Windows 10.0.14393 )
Authorization:REDACTED
client assembly: Azure.Storage.Queues
[Warning] Azure-Core: Error response 403 This request is not authorized to perform this operation using this permission. (00.1s)
x-ms-version:2018-11-09
x-ms-error-code:AuthorizationPermissionMismatch
Content-Length:279
Content-Type:application/xml
Date:Mon, 13 Sep 2021 16:37:39 GMT
Server:Windows-Azure-Queue/1.0 Microsoft-HTTPAPI/2.0

[Informational] Azure-Core: Error response content: ?<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.

Time:2021-09-13T16:37:40.4651476Z</Message></Error>

Unhandled Exception: Azure.RequestFailedException: This request is not authorized to perform this operation using this permission.

Time:2021-09-13T16:37:40.4651476Z
Status: 403 (This request is not authorized to perform this operation using this permission.)
ErrorCode: AuthorizationPermissionMismatch

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.

Time:2021-09-13T16:37:40.4651476Z</Message></Error>

**Comment by christothes** [comment]
Thanks - this confirms that the IMDS endpoint is being used. There is one additional step you can take to verify that the clientId being used is the one set in your options. To do this, you'll need the latest pre-release version of Azure.Identity and the following change your options:

```C#
var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions 
    { ManagedIdentityClientId = userAssignedClientId,  IsPiiLoggingEnabled = true });
```

**Note: this logging option will include sensitive information, so please take that into consideration when deciding how this logging is output.**

Once this is enabled, the following line from your log output should no longer be redacted:

```
[Informational] Azure-Core: Request [b7ec4610-eadd-48fe-a498-030337ab9d1d] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED&client_id=REDACTED
Metadata:REDACTED
```

**Comment by dsm4u** [comment]
do we need to explicitly pass client id for user managed identity?   
For system assigned identity its working fine without passing the client id.

**Comment by christothes** [comment]
> do we need to explicitly pass client id for user managed identity?
> For system assigned identity its working fine without passing the client id.

Yes

**Comment by dsm4u** [comment]
Oh ok.. So that means now we need to add clientid to config file instead of connection string right?

Also, in the above case if the client id captured in log is different than what we passed then can it be due to scaleset configurations?

**Comment by dsm4u** [comment]
@christothes I tried the above suggestion, and looks like a different client id is been send as part of the request. any powershell script or anything to identify the resource for that client id?

**Comment by dsm4u** [comment]
@christothes I tried the above suggestion, but still the client id is showing up as REDACTED.  took 1.5.0.beta version of azure.identity.

**Comment by christothes** [comment]
Can you confirm it is https://www.nuget.org/packages/Azure.Identity/1.5.0-beta.4 ?

**Comment by dsm4u** [comment]
Yes that's the version I applied.

**Comment by christothes** [comment]
Sorry, I was mistaken about the logging. In order to un-redact this information, we need to enable a slightly different logging option. We'll need to pass options to the QueueClient as follows:


```c#
var options = new QueuClientOptions()
{
    Diagnostics =
    {
        IsLoggingContentEnabled = true
    }
};
Azure.Storage.Queues.QueueClient queueClient = new Azure.Storage.Queues.QueueClient(QueueUri , credential, options); 
```

**Comment by dsm4u** [comment]
IsLoggingContentEnable is set to true for me, after that only I received those logs with redact content. 
Currently I have enable LoggingContent and the PiiLogging.

**Comment by christothes** [comment]
Please add that same option to the CredentialOptions also.

**Comment by dsm4u** [comment]
unfortunately still not getting the values:
 GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=REDACTED&resource=REDACTED&client_id=REDACTED
Metadata:REDACTED
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.5.0-beta.4 (.NET Framework 4.8.4410.0; Microsoft Windows 10.0.14393 )

**Comment by christothes** [comment]
We're getting closer :) I think this is what we actually need:

Add the string "client_id" to this list property:

```c#
credentialOptions.Diagnostics.LoggedQueryParameters.Add("client_id");
```

**Comment by dsm4u** [comment]
still no luck :(

**Comment by christothes** [comment]
Just for a sanity check, could you paste your current code with the configurations we discussed?

**Comment by dsm4u** [comment]
Here we go :)

QueueClientOptions options = new QueueClientOptions()
            {
                Diagnostics = { IsLoggingContentEnabled = true, IsLoggingEnabled = true }
            };
            options.Diagnostics.LoggedQueryParameters.Add("client_id");
            AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();

            string userAssignedClientId = "1E1EAF1B-26AB-49A0-9DDE-E0DB669EB0A7";
            var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { ManagedIdentityClientId = userAssignedClientId, 
                IsLoggingPIIEnabled = true, Diagnostics = { IsLoggingContentEnabled = true, IsLoggingEnabled=true } }); ;

            var tableconn = ConfigurationManager.AppSettings["storagequeue"];
            Uri tableUri = new Uri(tableconn);

            Azure.Storage.Queues.QueueClient queueClient = new Azure.Storage.Queues.QueueClient(tableUri, credential, options);
            QueueMessage message = queueClient.ReceiveMessage();

**Comment by christothes** [comment]
Looks like we are missing the LoggedQueryParameters on the credential options. Try this change:

```c#
var credOptions = new DefaultAzureCredentialOptions { ManagedIdentityClientId = userAssignedClientId, 
    IsLoggingPIIEnabled = true, Diagnostics = { IsLoggingContentEnabled = true, IsLoggingEnabled = true } };
credOptions.Diagnostics.LoggedQueryParameters.Add("client_id");
var credential = new DefaultAzureCredential(credOptions); ;

```

**Comment by dsm4u** [comment]
Thanks this worked..
Also, observed that if we turn off the system managed identity for the scaleset and enable only user managed identity then its working fine without explicitly setting the clientid.

**Comment by christothes** [comment]
> Thanks this worked..
> Also, observed that if we turn off the system managed identity for the scaleset and enable only user managed identity then its working fine without explicitly setting the clientid.

FYI - [These docs ](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/managed-identities-faq#what-identity-will-imds-default-to-if-dont-specify-the-identity-in-the-request)explain this behavior

**Comment by dsm4u** [comment]
Its now resolved and can be closed. Thanks for all the help.
