### ISSUE TITLE
[FEATURE REQ] Support for customizing load process of SecretProperties

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-sdk-for-net#23959]
**Azure.Extensions.AspNetCore.Configuration.Secrets**

Currently, when using the `AzureKeyVaultConfigurationProvider`, it always loads all secrets from the Azure Key Vault. 

Sometimes, multiple services are using the same Azure Key Vault and only one secret is needed.

By allowing to customize the loading process for the secrets properties, it's possible to load only a specific secret or a subset of secrets. In conjunction with `JsonKeyVaultSecretManager` is very easy to have one secret with JSON document, where all secrets for a particular service are stored.

**Comment by pakrym** [comment]
This seems like a perfect use case for AppService secret references: https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/app-secrets-configuration/?tabs=visualstudio

**Comment by cmenzi** [comment]
> This seems like a perfect use case for AppConfig secret references: https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/app-secrets-configuration/?tabs=visualstudio

Yes, it's would be an option. But we would need change all our services on how they load secrets and settings. Changing all CI/CD pipelines on how they provide app settings and secrets and buy App Configuration Service. 

I went through the docs and looks promising, but it would be longer journey for us. 

This small extension would already help us a lot.

**Comment by cmenzi** [comment]
Just something off topic: this extension can also be used in Function Apps, but are in the AspNetCore namespace. 

Is this intensional?

**Comment by pakrym** [comment]
Yes, the desire was to unify the naming schema for extension packages. So we went with Azure.AspNetCore even though some apply to more app models.
