### ISSUE TITLE
[BUG] Missing DependencyTelemetry for EventHub Consumer Receive Events

### ISSUE THREAD

**Issue by xinyi-joffre** [Azure/azure-sdk-for-net#23966]
**Describe the bug**
We recently made the upgrade from the older Microsoft.Azure.EventHubs library to the newer Azure.Messaging.EventHubs 5.6.0. 

After we made the switch, we realized that the DependencyTelemetry for EventHub Receive events (which had useful information such as partition_key, start_sequence_number, consumer_group, event_count, etc) is no longer there.

We now only see DependencyTelemetry for types "Azure Event Hubs" and "Queue Message | Azure Event Hubs", neither of which has the received message information.

**Expected behavior**
DependencyTelemetry for Receive events is still logged with useful fields such as partition_key, start_sequence_number, consumer_group, event_count, etc.

**Actual behavior (include Exception or Stack Trace)**
No telemetry out of the box for receive events.

**To Reproduce**
Set up producer and consumer and instrument w/ Application Insights.

Look in the DependencyTelemetry table and look for receive events.

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventHubs 5.6.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Dotnet Core and Azure AppService

**Comment by jsquire** [comment]
Hi @xinyi-joffre.   Thank you for your feedback and we regret that you're experiencing difficulties.  The omission of these items is by-design.  The tracing performed by the `Azure.Messaging.EventHubs` library is following a form defined as part of the OpenTelemetry initiative, and is attempting to standardize information across different messaging services.  The attributes written by the SDK are what we were asked to strictly follow.   

The work in defining the format is still ongoing across multiple Azure teams and adjustments are being made as the spec evolves.  It is possible that similar attributes may be included at some point in the future but, at present, they're not part of the standard set.

The bulk of the metrics that you're asking about are available by inspecting your consumer client and the `EventData` instance that you are working with, should you wish to emit similar logs.  If you'd like to correlate with the diagnostic identifier that the SDK is using, it can be queried from the event using an approach similar to the following:

```csharp
public static bool TryExtractDiagnosticId(EventData eventData, out string id)
{
    id = null;

    if (eventData.Properties.TryGetValue("Diagnostic-Id", out var objectId) && objectId is string stringId)
    {
        id = stringId;
        return true;
    }

    return false;
}
```

I'm going to mark this as addressed, but please feel free to use the "`/unresolve`" command if you'd like to continue the discussion.

**Comment by xinyi-joffre** [comment]
/unresolve

Thank you for the response @jsquire! I understand now why the format and properties of changed to follow the OpenTelemetry standard.

One piece that still seems to be a gap is that the DependencyTelemetry Receive event itself is missing (even not related to the additional custom fields). The source of this seems to be that in the older EventHub library, the Receive event was logged so that consumers that use the EventHubClient directly for ReadEventsFromPartitionAsync would get telemetry for both send and receive.

Now, it seems like unless you are using EventHubProcessor, you will get incomplete telemetry unless you implement/parse the standard yourself.

Can the telemetry logic for receiving events be moved back into the EventHubConsumerClient so that projects such as Orleans that use the EventHubConsumerClient, but not EventHubProcessor, will still be able to get benefits of OpenTelemetry standard tracing?

@ReubenBond

**Comment by jsquire** [comment]
Hi @xinyi-joffre.  The spec that we were following had those operations split into two different activities:
  
  - One for "processing events" that was marked as high value and implemented in the processor types
  - One for "receiving events" that was marked as low value and would apply to the `EventHubConsumerClient` and `PartitionReceiver` (Orleans uses the latter)

To be honest, I don't recall why the decision was made to not instrument the "receive events" activity at the time.  I'll take a follow-up to track down the folks who own our OpenTelemetry story and see what I can find out.   If there are no blockers from that perspective, I'll bring it up for consideration with the rest of the Event Hubs feature team.

**Comment by jsquire** [comment]
Looping in @lmolkova, who is our knowledge expert on OpenTelemetry and the author of the spec that we based our implementation on.   Liudmila had some thoughts around the "receive events" activity, both as it existed in the legacy package and would apply to the current generation.

**Comment by jsquire** [comment]
After internal discussion, the guidance that we are using for instrumentation has not changed, and advises not including the requested spans.   As a result, we won't be making the requested changes.

I'm going to close this out, but please feel free to "`/unresolve`" if you'd like to continue the discussion.

**Comment by lmolkova** [comment]
sorry, I somehow missed this thread. 

@xinyi-joffre as @jsquire mentioned we don't have specific plans to instrument receive operations mostly we don't really know how to do it right. From track1 library instrumentations, we learned a few things:
- receive call is a local call if events are prefetched: it has 0 duration and is successful, i.e. tracing it brings a low value
- if there are no messages on the EventHubs tracing it, yields a timeout which is not a real error, and is quite noisy
- we expect users to have sampling enabled and we can't make receive calls to be sampled consistently with a producer or the rest of consumer telemetry.

I'd be happy to learn about specific scenarios where tracing receive call would make sense and what would you want to know about receive operations if we'd start tracing them.

**Comment by lmolkova** [comment]
I created cross-language issue: https://github.com/Azure/azure-sdk/issues/3647, please add any insights and feedback there
