### ISSUE TITLE
[ResourceManager] Case-insensitive file collisions

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#23972]
When cloning the .NET repo on a default Windows machine, the following warnings are printed:

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree: 

  'sdk/resources/Azure.ResourceManager.Resources/tests/SessionRecords/DeploymentScriptContainerTests/ListByRG().json'
  'sdk/resources/Azure.ResourceManager.Resources/tests/SessionRecords/DeploymentScriptContainerTests/ListByRg().json'
  'sdk/resources/Azure.ResourceManager.Resources/tests/SessionRecords/DeploymentScriptContainerTests/ListByRG()Async.json'
  'sdk/resources/Azure.ResourceManager.Resources/tests/SessionRecords/DeploymentScriptContainerTests/ListByRg()Async.json'
```

These files were added in https://github.com/Azure/azure-sdk-for-net/pull/23090.

@fengzhou-msft: Do you know how this PR ended up containing these files which only differ by case?  Is it an issue in our test recording and playback infrastructure?  Or maybe the PR was created on both Windows and Linux/Mac which caused this?

These files should be deleted or renamed to avoid the collision, but we should also try to understand how this happened so we can prevent it going forward.

**Comment by Yao725** [comment]
Thanks for your feedback. Let me explain how this problem happened. The test ListByRg was initially named ListByRG, which leads to the existence of test records named ListByRG().json and ListByRG()Async.json. So it's not an problem in the test recording and playback infrastructure. I have created #23974 to delete the unnecessary test records.
