### ISSUE TITLE
[FEATURE REQ] Azure.Core.AccessToken should have a ToString() that returns the base64 token

### ISSUE THREAD

**Issue by JustinGrote** [Azure/azure-sdk-for-net#23985]
**Library or service name.**
Azure.Core.AccessToken
 
**Is your feature request related to a problem? Please describe.**
Add a tostring, so that it can more easily be used in applications like PowerShell without having to call the .token member instead. This will make pipelines and whatnot work much more efficiently.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by AlexGhiondea** [comment]
@JustinGrote can you share more information about this? I'm trying to see why calling ToString is preferable to calling Token on the same object?

**Comment by JustinGrote** [comment]
@AlexGhiondea In Powershell, items with a ToString() call the method when cast to a string. This would allow the token to be easily pipelined without having to first do a `Foreach-Object` to extract the token, making for much messier code.
