### ISSUE TITLE
[QUERY] Is there a way to set the batch size for an EventProcessorClient?

### ISSUE THREAD

**Issue by stambunan** [Azure/azure-sdk-for-net#24001]
**Query/Question**
Is there a way to set the batch size for an EventProcessorClient? I've been trying to figure it out as the remarks mention that events in the batch may be between 0 and a `batch size`?

https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventprocessorclient.onprocessingeventbatchasync?view=azure-dotnet#remarks

**Environment:**
 - Name and version of the Library package used: 
Azure.Messaging.EventHubs.Processor v5.6.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET 5
 - IDE and version : VS 16.11.2

**Comment by jsquire** [comment]
Hi @stambunan.   The answer to your question is "it depends on your intent":

- If you're asking "can my handler be called with more than a single event,"  the answer is no.   The `EventProcessorClient` reads events in a batch from the service and dispatches them to your `ProcessEventHandler` individually.   For batch-based processing, you'd want to use the `EventProcessor<T>` as the base for an event processor implementation.   

- If you're asking "can I tune my processor to read from the service more efficiently for my application's needs," the answer is yes.   The [CacheEventCount](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.eventprocessorclientoptions.cacheeventcount) controls the size of the batch read and can be tuned in collaboration with the [PrefetchCount](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.eventprocessorclientoptions.prefetchcount) when constructing your `EventProcessorClient`.   These values can help tune throughput.

For more information on the Event Hubs clients and what scenarios they're intended to help with,  please see [Event Hubs Clients](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample02_EventHubsClients.md#hierarchy) and [How to choose the right Azure Event Hubs .NET client library type for your application](https://devblogs.microsoft.com/azure-sdk/eventhubs-clients).

If you're interested in extending `EventProcessor<T>` for batch-based processing,  you may want to take a look at [Building a custom processor with EventProcessor<TPartition>](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample08_CustomEventProcessor.md) and [Building A Custom Event Hubs Event Processor with .NET](https://devblogs.microsoft.com/azure-sdk/custom-event-processor/).

I'm going to mark this as addressed, but please feel free to use the "`/unresolve`" command if you'd like to continue the discussion.

**Comment by stambunan** [comment]
Thanks @jsquire
