### ISSUE TITLE
[FEATURE REQ] Web Account Manager Support

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-sdk-for-net#24005]
**Library or service name.**
Azure.Identity
 
**Is your feature request related to a problem? Please describe.**
MSAL supports [Web Account Manager (WAM)](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/wam) now. Azure PowerShell is asked to WAM support and we hope Azure.Identity to include this feature. It requires Azure.Identity to call `.WithWindowsBroker().` instead of `.WithBroker().` 

To reduce the potential risk, we are thinking to enable this feature gradually with 2 steps.
* Opt-in – where the default experience for your users remains the same, while we can roll out this functionality and easy rollback in case we find an issue. This will allow us to test with zero risk.
* Default – where we (you) have confidence that this will not cause an issue for your customers.

**Comment by maliksahil** [comment]
@schaabs - should there be a milestone/date assigned to this?

**Comment by joshfree** [comment]
updating to the `February 2022` milestone (January - Feb 4th coding milestone).
