### ISSUE TITLE
Clarify how to use C# API to describe and create indexes containing complex types

### ISSUE THREAD

**Issue by MACEL94** [Azure/azure-sdk-for-net#24014]
Can you please provide an example on how to use this class if i wanted to create a list of complextype objects like rooms in the example provided when creating a new index or updating it?
That example describes how to do it only using REST but i'd like to use the SDK.

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dbc6937e-0f99-38ca-7a84-aa06ddc399e4
* Version Independent ID: f20ee539-6e2d-8fc9-768d-be2e76654548
* Content: [ComplexField Class (Azure.Search.Documents.Indexes.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.indexes.models.complexfield?view=azure-dotnet)
* Content Source: [xml/Azure.Search.Documents.Indexes.Models/ComplexField.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Search.Documents.Indexes.Models/ComplexField.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AlexGhiondea** [comment]
@MACEL94 a good starting point for how to use the Azure Search Library is https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/README.md.

**Comment by MACEL94** [comment]
/unresolve

Here:
```C# Snippet:Azure_Search_Tests_Samples_Readme_StaticType
public class Hotel
{
    [JsonPropertyName("HotelId")]
    [SimpleField(IsKey = true, IsFilterable = true, IsSortable = true)]
    public string Id { get; set; }

    [JsonPropertyName("HotelName")]
    [SearchableField(IsFilterable = true, IsSortable = true)]
    public string Name { get; set; }
}
```

I'd suggest to add how to map a list of complex types using c#.
I managed to do it by trying but i'd say there is a lack of example in the documentation because i did not find a single example of a complex type being mapped by using the c# sdk and then using the FieldBuilder on that complex object.

That is why i asked how to use the ComplexField class, but that is not even needed.

**Comment by AlexGhiondea** [comment]
@MACEL94 does this mean you are looking for a sample with a complex type being mapped?

You mentioned you had something working -- would you be willing to submit a PR with that as a sample?

**Comment by MACEL94** [comment]
Ok, tonight or tomorrow i'll try to submit a PR with an example, I can't use the one I have as is.

Have a good day
