### ISSUE TITLE
[QUERY] Recommendations to replace IQueryable functionality?

### ISSUE THREAD

**Issue by misholson** [Azure/azure-sdk-for-net#24033]
**Query/Question**
I'm looking at upgrading from older versions of the SDK, but I see that this version doesn't include IQueryable support. That's fine for simple queries, but I have a number of places in my code where we have something to the effect of:

```csharp
var query = CreateQuery<MyEntity>();
query = query.Where(e => e.PartitionKey == "whatever");

if (startDate.HasValue)
{
    query = query.Where(e => e.CreatedDate >= startDate.Value);
}

if (endDate.HasValue)
{
    query = query.Where(e => e.CreatedDate <= endDate.Value);
}

var result = await query.ExecuteSegmentedAsync();
```

If I understand the new library correctly, the only way I could replicate this kind of code is to build the OData strings myself. Is there a better way to handle this? Would you consider including some kind of query builder, even if it's not based on IQueryable?

**Environment:**
 - Name and version of the Library package used: Azure.Data.Tables 12.2.0 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure Cloud Services, .NET Framework 4.7.2
 - IDE and version : Visual Studio

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
We support filter queries in the new client. See the sample [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md#linq-expression).

**Comment by misholson** [comment]
Sorry I didn't get to this earlier. I don't see from the links you sent how I could write the code I described in my original post. The LINQ queries are fine as long as they don't have to be dynamic, but I'm trying to build different queries based on different input and I don't see how I can do that using LINQ. It's certainly possible that I could build the text string myself, but that seems dangerous. Plus if that were the case I'd like to see some documentation on what escape characters I need to use.

Every table SDK before this one has had some form of a dynamic query builder, and I'm wondering if I'm just missing something of if it was purposefully not added.

**Comment by misholson** [comment]
I haven't had time to try it, but something like this seems promising, since what you're expecting is an Expression rather than an IQueryable:

https://petemontgomery.wordpress.com/2011/02/10/a-universal-predicatebuilder/

But I wondered if there was something built into the framework that I'm missing to build dynamic predicates.

**Comment by christothes** [comment]
Here are a couple examples of how to optionally combine some expressions as in your initial example:

If you want to deal just with expressions:
```c#
// Create the base expression
Expression<Func<MyEntity, bool>> query = e => e.PartitionKey == Partition;

// Create a variable for the expression body
var queryBody = query.Body;

// Create a variable for the expression parameter (MyEntity)
ParameterExpression parameter = query.Parameters[0];

if (startDate.HasValue)
{
    // Create the startDate filter
    Expression<Func<MyEntity, bool>> withStart = e => e.CreatedDate >= startDate.Value;

    // Combine this filter with the base expression    // Combine this with the current queryBody
    queryBody = Expression.AndAlso(queryBody, withStart.Body);
}

if (endDate.HasValue)
{
    // Create the endDate filter
    Expression<Func<MyEntity, bool>> withEnd = e => e.CreatedDate <= endDate.Value;

    // Combine this with the current queryBody
    queryBody = Expression.AndAlso(queryBody, withEnd.Body);
}

// Create a new lambda with the current queryBody and our parameter
var lambda = Expression.Lambda<Func<MyEntity, bool>>(queryBody, parameter);

// Give the lambda to the Query method
client.Query(lambda);
```

Or if you want to do a bit of string management and avoid the complexity of expression manipulation:
```C#
// Get the oData string filter for your initial expression
string filter = TableClient.CreateQueryFilter<MyEntity>(e => e.PartitionKey == Partition);

if (startDate.HasValue)
{
    // Get the oData string filter for the startDate expression
    string withStart = TableClient.CreateQueryFilter<MyEntity>(e => e.CreatedDate >= startDate.Value);

    // Combine the two strings with an 'and'
    filter = $"({filter}) and ({withStart})";
}

if (endDate.HasValue)
{
    // Get the oData string filter for the endDate expression
    string withEnd = TableClient.CreateQueryFilter<MyEntity>(e => e.CreatedDate <= endDate.Value);

    // Combine the two strings with an 'and'
    filter = $"({filter}) and ({withEnd})";
}

// Give the filter string to the Query method
client.Query(filter);
```

**Comment by misholson** [comment]
Thank you, this is exactly the info I needed!
