### ISSUE TITLE
IHttpOperationResponse should inherit from IDisposable

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-net#2403]
The interface defines two properties of types `HttpRequestMessage` and `HttpResponseMessage` (which are both `IDisposable`, but it doesn't define a way to dispose of them. The class `HttpOperationResponse` does.

We should move the `IDisposable` bit up to the interface so that those using the interface have access to the full set of functionality required to correctly manage the life cycle of one of these responses.

**Comment by matthchr** [comment]
@fearthecowboy @markcowl -- Moved this here from the AutoRest repo, since the C# client runtime is apparently moving to here.

**Comment by markcowl** [comment]
Note: HttpOperationResponse implements IDisposable, so ensure that we won't need to generate new code to support this.

**Comment by twitchax** [comment]
I recommend we punt until we have a release with required breaking changes.  Any public interface changes require a breaking change notification, and this fix is not worth pegging the major version number.

Recommend punt to next major version.

**Comment by shahabhijeet** [comment]
@matthchr is this still an issue? I am cleaning up old issues. Will close this if I don't hear back in a week.

**Comment by matthchr** [comment]
@shahabhijeet - yes, I don't see this fixed in the latest drops of the SDKs, so it's still a problem.

**Comment by shahabhijeet** [comment]
@matthchr ok I looked at this and what I am not very clear is the following:
1. are you suggesting that the base interface should have IDisposable (from a good design point of view)
or
2. You have a scenario where you will be using the base Interface IHttpOperationResponse and not the concrete class HttpOperationResponse? If yes can you provide me a scenario in your SDK where you are using the Interface and not the Concrete class.
I am actually more curious to know which API/Type you have in your SDK that you work with using the IHttpOperationResponse and not the base concrete class.

**Comment by matthchr** [comment]
@shahabhijeet - I guess most just 1?

Since `IHttpOperationResponse` has two properties whose types implement disposable, it (from a good design point of view) should probably implement `IDisposable` itself.

We do use the interfaces to set up generic constraints, for example:
```
    public abstract class BatchRequestBase<TOptions, TResponse> : IBatchRequest<TResponse>
        where TOptions : IOptions, new()
        where TResponse : IAzureOperationResponse
```

Right now it doesn't really matter that `IAzureOperationResponse` doesn't implement `IDisposable` because of the way that the concrete class actually implements `Dispose` and the way we invoke things we never actually manually call `Dispose` on an `IAzureOperationResponse` -- we just rely on the default ref-counting implementation to do it for us. But we _cant_ call dispose right now even if we wanted to because `IAzureOperationResponse` doesnt implement dispose.

As per here: https://github.com/aspnet/Security/issues/886 it's probably not that big of a deal the way we're doing it now but still think we should just fix the interfaces anyway.

**Comment by shahabhijeet** [comment]
@matthchr thank you for pointing this out.
At this point, we are not thinking of changing anything in our base interfaces. We will revisit this when we will be redesigning our base class probably after Titanium.
Plus the referenced issue is good confirmation that this will be good to have and not a must.
Closing.
