### ISSUE TITLE
[LLC] [Feature] Determine where LLC-generated model files will go

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#24049]
For RCv2, the LLC will generate model types where input models can be implicitly cast from model to RequestContent, and output models can be implicitly cast from Response to model.

We expect these models to change over time, either from service changes, or changes for the convenience layer that may be added to the library based on business needs.  In order to guarantee that we will not make breaking changes to our libraries, these models need to be generated to a target outside a library package.  For them to be useful, we need to provide the ability for customers to copy the model code into their projects and take ownership of this code.

This issue tracks the work to define that process.

**Comment by jsquire** [comment]
@annelo-msft:  This seems like it has been superseded by DPG changes.   Should we close this out?

**Comment by annelo-msft** [comment]
@m-nash can share whether it is still needed.  This was a post-GA feature for value-add over currently generated models, so it might make sense to put it on the backlog.
