### ISSUE TITLE
[LLC] `RequestOptions` into Azure.Core

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-for-net#24050]
At some point RequestOptions will move from Experimental to Core, and we need to update for that.

- [ ] Finalize `ResponseClassifier` API
- [ ] Review `RequestOptions` at arch board
- [ ] Consider renamings to make [ResponseStatusOption](https://apiview.dev/Assemblies/Review/b67e68cfee4841bda045f895c90ad383/0ea8d18067c344208352d5a9506ea22a?doc=False#Azure.ResponseStatusOption) enum and value a little easier to understand

**Comment by annelo-msft** [comment]
We won't move to Core for RC1.0, because it's a proper GA.  We will do an arch board review and agree on what's Experimental/RC1.0.

**Comment by annelo-msft** [comment]
ResponseClassifier APIs have been removed to allow more bake time.
