### ISSUE TITLE
Get Key Vault READMEs clean to better spot mistakes

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#24069]
Using the cSpell and Docs VSCode extensions (the Docs pack is from Microsoft intended for docs.microsoft.com in general), our READMEs show a lot of blue (cSpell) and yellow (Docs pack) squigglies that make spotting issues incredibly hard. I've often wanted to clean up Key Vault's READMEs, for example, but would be so noisy in any random PR and low-pri to do standalone.

By cleaning these up, we can better spot *real* issues if those extensions are installed, which we should recommend through `.vscode/extensions.json`.

It's also worth noting that, with all the code we have in READMEs, there's a good way in cSpell (`.vscode/cspell.json`) to use programming dictionaries in markdowns, like I do [here](https://github.com/heaths/go-console/blob/b21455dd53b8a945a48c5f98264c75c5d0fc54c7/.vscode/cspell.json#L17-L22) in a personal project. There's dictionaries for C# and whatever else we might use in markdowns.

**Comment by danieljurek** [comment]
We already apply the `csharp` dictionary to all files: https://github.com/Azure/azure-sdk-for-net/blob/main/.vscode/cspell.json#L5 

We could scope to *.cs, and *.md files but we'd probably keep expanding the scope if other files contain source code or examples. 

The thinking behind the current approach is that all files in the .NET repository may contain some valid C# words so we don't gain much by treating those words as spelling errors anywhere within a repo. 

When editing a markdown file with the current configuration `.vscode/cspell.json` configuration the word `struct` is treated as valid: 
![image](https://user-images.githubusercontent.com/2158838/134055475-39afde33-6b94-48f8-b5b0-d06bb881f49b.png)

When removing the "csharp" entry from the current configuration the word `struct` is treated as invalid: 
![image](https://user-images.githubusercontent.com/2158838/134055536-989490cf-fd98-43b3-bc88-199adc2c5f99.png)


This might be a behavior of the plugins on your machine.

**Comment by heaths** [comment]
It's more than just spelling errors:

![image](https://user-images.githubusercontent.com/1532486/134056634-eca9919b-21e0-4749-8f32-ca9b6a7ef55f.png)

I only mentioned spelling as one issue. If "csharp" is already added as a dictionary, great. But the [Docs Authoring Pack](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack) - which anyone editing docs for docs.microsoft.com should have installed - flags a bunch of other issues. See how orange my scrollbar is with warnings? Hard to see anything valid I should fix.

**Comment by pallavit** [comment]
@heaths is this still valid? What kind of checks do you have in mind here?

**Comment by heaths** [comment]
I still think this is worth it, but would require each library owner to do it themselves, or one large push by someone to clean it up. No non-formatting changes should be required, I'd think. Even then, people would need to install the ~~Docs~~ Learn Authoring Pack to keep them clean, or we run `markdown-lint` during builds.

Probably not enough people care to check over the READMEs, so I'm happy to just retitle and scope this to KV. It wouldn't take me long to clean them up. I just never wanted to do that in some other PR because it would introduce too much noise. This should be a scoped change.

Thoughts?

**Comment by pallavit** [comment]
I think KV would be a good start. One thing I am not sure is how would this be different than the current cspell checks that we already do validation against?

**Comment by heaths** [comment]
It's not just spelling, but markdown linting. I use the docs package - you're supposed to for Learn content, and it's enforced in CIs - and almost every MD file I open in our repo has blue squiggles. It makes it hard to spot non-trivial issues.
