### ISSUE TITLE
[TESTS] Need to add BindingData tests for Microsoft.Azure.WebJobs.Extensions.Blobs/Queues

### ISSUE THREAD

**Issue by karshinlin** [Azure/azure-sdk-for-net#24086]
**Query/Question**
Since the package Microsoft.Azure.WebJobs.Extensions.Blobs was migrated to the Azure SDK in the track1 to track2 move, the BindingData tests from the WebJobs repo also need to be migrated. 

These tests are currently in the [WebJobs repo](https://github.com/Azure/azure-webjobs-sdk/blob/4a16c273b40ee47ec318bb6d7aa12e0075f30402/test/Microsoft.Azure.WebJobs.Host.FunctionalTests/JobHostTests.cs#L449).

There are some Queue BindingData tests in the Azure SDK [here](https://github.com/Azure/azure-sdk-for-net/blob/2103c3801199eeaa0cd8b762b28658f8223ffb02/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/tests/QueueTriggerTests.cs?plain=1#L302), but these tests should be cross-referenced with the WebJobs repo to ensure test coverage remains the same. 

I don't see similar tests for blobs extensions. These will need to be added to test the logic [here](https://github.com/Azure/azure-sdk-for-net/blob/2103c3801199eeaa0cd8b762b28658f8223ffb02/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/src/Triggers/BlobTriggerBinding.cs?plain=1#L136).

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.WebJobs.Extensions.Blobs and Microsoft.Azure.WebJobs.Extensions.Queues

**Comment by kasobol-msft** [comment]
The Queues tests are covered here.
https://github.com/Azure/azure-sdk-for-net/blob/c13662bd5365cb66a13beb9ffa32337965e8c2a7/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/tests/QueueTriggerTests.cs#L822-L910

**Comment by kasobol-msft** [comment]
Blobs https://github.com/Azure/azure-sdk-for-net/pull/24391 .

**Comment by mathewc** [comment]
What about Queues?

**Comment by kasobol-msft** [comment]
@mathewc please see comment above. Queues are already covered.
