### ISSUE TITLE
[BUG] Not able to retrieve secrets from KeyVaul using ManagedIdentity

### ISSUE THREAD

**Issue by sunkararp** [Azure/azure-sdk-for-net#24107]
**Describe the bug**
AKS version: 1.20.7
Azure.Identity: 1.4.1
Azure.Security.Keyvault.Secrets: 4.1.1
Grpc.AspNetCore: 2.38.0

We were unable to retrieve secrets from Azure KeyVault using AAD pod managed identity, below are our code snippets and the corresponding errors we received accordingly. 

Below code snippets were tried on the .net GRPC server side when client call arrives. 

The 1st code snippet works perfectly fine, however, if we **FIRST** try to retrieve a non-existing secret from the KeyVault in the service Startup.cs code and later try to retrieve actual secret. We were totoally baffled by this behaviour. Can someone through some light on this please.

- - Code Snippet 1
  ```csharp
  var client = new SecretClient(new Uri(_keyVaultUrl), new DefaultAzureCredential());
  secret = client.GetSecret(secretName, version: secretVersion);
  ```
  Error
  ```
  Azure.Identity.AuthenticationFailedException: Azure CLI authentication timed out.
  ```

- - Code Snippet 2
  ```csharp
  var credential = new ChainedTokenCredential(new ManagedIdentityCredential(), new AzureCliCredential());
  var client = new SecretClient(new Uri(_keyVaultUrl), credential );
  secret = client.GetSecret(secretName, version: secretVersion);
  ```
  Error
  ```
  Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
  ```

**Expected behavior**
What is the expected behavior?

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.
2.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by sunkararp** [comment]
It feels like ManagedIdentity bootstrapping is failing in multithreading scenarios.

```csharp
public sealed class MyGrpcService : MyGrpcServiceBase
{
    public override async Task<MyMethodResponse> MyMethodAsync(
          MyMethodRequest request,
          ServerCallContext context)
    {
          return  await CallInternalMethodAsync(...).ConfigureAwait(false);
    }
}

private async Task<MyMethodResponse>CallInternalMethodAsync(...)
{
     // Failure happens here
     // Retrieve KeyVault secret with either code snippet 1 or 2.
    //  Our AKS cluster was configured to use managed identity
}
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @sunkararp - 
Would you mind providing the logging output after reproducing this with [logging enabled](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#logging) on the credential?

**Comment by sunkararp** [comment]
- We use ManagedIdentity heavily in our AKS cluster, to name few ServiceBus and Storage
- We are not blocking metadata entry point 169.254.169.254/32  
- This is what we see in our aks logs
```
ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
 ---> System.AggregateException: Multiple exceptions were encountered while attempting to authenticate. (EnvironmentCredential authentication unavailable. Environment variables are not fully configured.) (ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.) (Operating system Linux 5.4.0-1055-azure #57~18.04.1-Ubuntu SMP Fri Jul 16 19:40:19 UTC 2021 isn't supported.) (Stored credentials not found. Need to authenticate user in VSCode Azure Account.) (Azure CLI not installed) (PowerShell is not installed.)

---> (Inner Exception #1) Azure.Identity.CredentialUnavailableException: ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.
```

**Comment by christothes** [comment]
Is the first token request always on startup? 
There is a workaround pod example which waits for the IMDS endpoint to become available at startup. You can find it [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/identity/azure-identity/tests/pod-identity/test-pod-identity/templates/job.yaml#L23)

We also [made a change to how the Managed Identity endpoint is initialized ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#bugs-fixed-1)in 1.5.0-beta.4 - would you be able to try if it reproduces with that newest pre-release version?

**Comment by sunkararp** [comment]
No, we cannot work with beta version because of security and compliance policy. When will this become release candidate?

**Comment by sunkararp** [comment]
> Is the first token request always on startup?

As mentioned in my original bug report, since fetching KeyVault is failing we found following ugly workaround...
1. Try to retrieve a non-existing secret from the KeyVault in the service Startup.cs code; we know this will fail
2. Later during the client call execution, we will retrieve actual secret
3. Without the step 1, the step 2 will fail

**Comment by christothes** [comment]
> No, we cannot work with beta version because of security and compliance policy. When will this become release candidate?

There is no distinction between release candidate and pre-release. It will become a released version next month.

> As mentioned in my original bug report, since fetching KeyVault is failing we found following ugly workaround...
> 
> 1. Try to retrieve a non-existing secret from the KeyVault in the service Startup.cs code; we know this will fail
> 2. Later during the client call execution, we will retrieve actual secret
> 3. Without the step 1, the step 2 will fail

Could you please provide logging of this scenario (not aks logs, but the Credential ETW logs as mentioned in my first response)?

**Comment by sunkararp** [comment]
> Could you please provide logging of this scenario (not aks logs, but the Credential ETW logs as mentioned in my first response)?

Can you provide steps to collect Credential ETW logs in AKS?

**Comment by christothes** [comment]
Please see this example: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#logging
