### ISSUE TITLE
[Tables] GetTablesReturnsTablesWithAndWithoutPagination(null) failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#24102]
Tables nightly test runs are failing with:

> Error message
> Expected: 11
> But was:  15
> 
> 
> Stack trace
>    at Azure.Data.Tables.Tests.TableServiceClientLiveTests.GetTablesReturnsTablesWithAndWithoutPagination(Nullable`1 pageCount) in /Users/runner/work/1/s/sdk/tables/Azure.Data.Tables/tests/TableServiceClientLiveTests.cs:line 229
>    at Azure.Data.Tables.Tests.TableServiceClientLiveTests.GetTablesReturnsTablesWithAndWithoutPagination(Nullable`1 pageCount) in /Users/runner/work/1/s/sdk/tables/Azure.Data.Tables/tests/TableServiceClientLiveTests.cs:line 219
>    at Azure.Data.Tables.Tests.TableServiceClientLiveTests.GetTablesReturnsTablesWithAndWithoutPagination(Nullable`1 pageCount) in /Users/runner/work/1/s/sdk/tables/Azure.Data.Tables/tests/TableServiceClientLiveTests.cs:line 241
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1090619&view=results

@jsquire for notification.

**Comment by christothes** [comment]
This has been passing for the past 5 days
