### ISSUE TITLE
ServiceBusMessage.ApplicationProperties Property

### ISSUE THREAD

**Issue by nirzaf** [Azure/azure-sdk-for-net#24117]
[Enter feedback here]
Please add some sample code for the implementation of this section 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 081e1612-bfed-d699-344b-924874f4927c
* Version Independent ID: e392aa54-9876-7d1e-4e66-174a296a00c9
* Content: [ServiceBusMessage.ApplicationProperties Property (Azure.Messaging.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage.applicationproperties?view=azure-dotnet#Azure_Messaging_ServiceBus_ServiceBusMessage_ApplicationProperties)
* Content Source: [xml/Azure.Messaging.ServiceBus/ServiceBusMessage.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus/ServiceBusMessage.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @nirzaf,
Can you clarify what you are looking for here?

**Comment by nirzaf** [comment]
> Hi @nirzaf, Can you clarify what you are looking for here?

I was looking for some sample code implementation on how to add custom user defined Application Properties in C#, finally I figured out how do it, but it would comfortable if we have some official sample code

**Comment by JoshLove-msft** [comment]
I see - was the issue that you were running into related to the dictionary being "get" only? Were you trying to set it to a new dictionary?
