### ISSUE TITLE
Validation build: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1102675&view=results

### ISSUE THREAD

**Issue by Dave0412** [Azure/azure-sdk-for-net#24111]
Validation build: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1102675&view=results

_Originally posted by @mikeharder in https://github.com/Azure/azure-sdk-for-net/issues/24095#issuecomment-922034118_

**Comment by jsquire** [comment]
Hi @Dave0412.   Unfortunately, I can't determine from the context of the issue what you're inquiring about.  The comment that you're referencing belongs to an internal pull request.    I'm going to close this out; if you're still in need of assistance, please open a new issue and let us know how we can help.
