### ISSUE TITLE
Use sparse checkout for CI/live tests and release pipelines

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-for-net#24146]
We have [sparse checkout templates](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/pipelines/templates/steps/sparse-checkout.yml) that are used in various places to speed up pipeline job runtime, especially in repos like java and net where test recordings are substantial and make the full repo clone very large.

In java, we use sparse checkout across CI, live tests and release. Generally this results in about a 3-4 minute improvement per job and should be similar for net.

There are a few considerations with sparse checkout that need to be handled when adding support:

1. Excluding test recordings has the most impact.
2. Excluding other SDK and mgmt directories also has benefit, but takes more work (sometimes there are file dependencies across directories).
3. Certain types of files need to be included everywhere or in most places, such as markdown files, xml files and CODEOWNERS files.

Related: https://github.com/Azure/azure-sdk-for-net/pull/21789

@weshaggard @pakrym

**Comment by pakrym** [comment]
>Excluding other SDK and mgmt directories also has benefit, but takes more work (sometimes there are file dependencies across directories).

Can we only exclude recordings in other directories?

**Comment by benbp** [comment]
> Can we only exclude recordings in other directories?

Yeah I think this would be a great starting point.
