### ISSUE TITLE
LLC: Reference docs for protocol methods are not sufficient

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#24145]
See https://docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.account.purviewaccountclient.updateaccountproperties?view=azure-dotnet-preview#Azure_Analytics_Purview_Account_PurviewAccountClient_UpdateAccountProperties_Azure_Core_RequestContent_Azure_RequestOptions_

Protocol methods require the caller to know the schema of the body payload. The current docs (link above) are show the schema in a format that is impossible to understand.

**Comment by annelo-msft** [comment]
Closing as duplicate of https://github.com/Azure/azure-sdk-for-net/issues/28833
