### ISSUE TITLE
Deprecate Track1 Azure Query Monitor SDKs

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#24156]
Tracking issue to deprecate the following packages in favor of https://www.nuget.org/packages/Azure.Monitor.Query/:

- [x] https://www.nuget.org/packages/Microsoft.Azure.OperationalInsights/
- [x] https://www.nuget.org/packages/Microsoft.Azure.ApplicationInsights.Query/

**Comment by scottaddie** [comment]
Microsoft.Azure.OperationalInsights was deprecated on Jan. 6th.

**Comment by scottaddie** [comment]
Microsoft.Azure.ApplicationInsights.Query was deprecated on March 16th.
