### ISSUE TITLE
Migrate test recording framework to unified test framework

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#24167]
- [x] Start (and install if needed) and stop test proxy from Test Framework
- [x] Load session records from test proxy in Playback mode
- [x] Send session records to test proxy in Record mode
- [x] Translate custom sanitizers to Test Proxy sanitizers
- [x] Migrate all libraries
- [x] Delete legacy code

**Comment by JoshLove-msft** [comment]
We can make the necessary changes in a PR to use the Test Proxy and see what breaks in CI. This should uncover any tests that are using custom sanitizers/matchers that need to be migrated.

**Comment by JoshLove-msft** [comment]
Remaining libaries:

Azure.AI.FormRecognizer
Azure.AI.MetricsAdvisor
Azure.Analytics.Synapse.Artifacts
Azure.Identity
Azure.IoT.Hub.Service
Azure.Monitor.OpenTelemetry.Exporter
Azure.ResourceManager
Azure.ResourceManager.Compute
Azure.ResourceManager.DeviceUpdate
Azure.ResourceManager.EventHubs
Azure.ResourceManager.KeyVault
Azure.ResourceManager.Network
Azure.ResourceManager.Resources
Azure.ResourceManager.ServiceBus
Azure.ResourceManager.Storage
Azure.Security.KeyVault.Administration
Azure.Storage.Blobs
Azure.Storage.Blobs.ChangeFeed
Azure.Storage.Common
Azure.Storage.Files.DataLake
Azure.Storage.Files.Shares
Azure.Storage.Queues
