### ISSUE TITLE
How to export the template of one resource?

### ISSUE THREAD

**Issue by StannieV** [Azure/azure-sdk-for-net#24161]
https://github.com/Azure/azure-libraries-for-net/blob/151496e1f28cad3759cb6861b975994aeb1e8196/src/ResourceManagement/ResourceManager/ResourceGroup/ResourceGroupImpl.cs#L99

Hi All,

I want to export all templates of my resource groups. My resource groups have more than 200 resources and returns the following error: **'Export template is not supported for resource groups that have more than '200' resources.'**

When I look into the Azure API documentation (https://docs.microsoft.com/en-us/rest/api/resources/resource-groups/export-template) it states that it is also possible to provide the: 'The IDs of the resources to filter the export by.'. Unfortunately, specifying the IDs is not supported in the library because it always specifies '*' in the code.

How can I export, with this library, a template per resource?

**Comment by Yao725** [comment]
Hi @StannieV , sorry for the late reply.

The type that returned by GetByResourceGroup method is Pageable<GenericResource>, which inherits from IEnumerable. So you can use code below to traverse the returned resources.

```
ArmClient armClient = new ArmClient(new DefaultAzureCredential());
ResourceGroup resourceGroup = await armClient.DefaultSubscription.GetResourceGroups().GetAsync(resourceGroupName);
foreach (var resource in armClient.DefaultSubscription.GetGenericResources().GetByResourceGroup(resourceGroupName))
{
    var export = await resourceGroup.ExportTemplateAsync(new ExportTemplateRequest { Resources = { resource.Id }, Options = "IncludeParameterDefaultValue,IncludeComments" });
    var templateJson = JsonConvert.SerializeObject(export.Value.Template, Formatting.Indented);
    Console.WriteLine(templateJson);
}
```

Please let me know if it works for you.

**Comment by StannieV** [comment]
Hi @Yao725, your code is not that different and also throws the same exception. The issue is in retrieving all the services. In the 'PublicIPAddresses' service with an SKU tier value: 'Regional' which is not supported. Did your resource group also contain a 'PublicIPAddresses' service?

**Comment by mattwhitfield** [comment]
@StannieV Hi, I'm actually just trying to count the resources in each resource group - so I'm not trying to query specific resources. I have code like this:

`var resources = await subscription.GetGenericResources().GetByResourceGroupAsync(groupName).ToListAsync();`

And that will just blow up on some resource groups. The simplest one that I have is a resource group that contains just three resources, an App Service Plan, a Function App and a Storage Account.

Having iterated over the resource groups in our subscription, I collected the distinct exception messages that I got - and they are here:

Unknown SkuTier value. (Parameter 'value') Actual value was Dynamic.
Unknown SkuTier value. (Parameter 'value') Actual value was PremiumV2.
Unknown SkuTier value. (Parameter 'value') Actual value was ElasticPremium.
Unknown SkuTier value. (Parameter 'value') Actual value was Regional.
Unknown SkuTier value. (Parameter 'value') Actual value was BusinessCritical.
Unknown SkuTier value. (Parameter 'value') Actual value was System.

For my use case, I really don't care about the SkuTier, and I certainly don't care if it's an enum versus a string.

If there's anything else you need, please let me know 👍

**Comment by mattwhitfield** [comment]
@Yao725 Just FYI - I pulled the azure SDK repo, and changed the SKU Tier to a string in the Azure.ResourceManager project (and made the consequential changes to serialization) and it worked just fine. Obviously that might result in more changes in other projects (seeing as there seem to be a lot of SkuTier.cs files in the repo as a whole), but I thought at least that might be a useful data point.

**Comment by Yao725** [comment]
@mattwhitfield , thanks for your feedback, I will fix it according to the [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json#L5527-L5530) ASAP.

**Comment by isaacrlevin** [comment]
@Yao725 when will this be pushed to Nuget? Seeing the same thing in Azure.ResourceManager 1.0.0-beta6

**Comment by Yao725** [comment]
> @Yao725 when will this be pushed to Nuget? Seeing the same thing in Azure.ResourceManager 1.0.0-beta6

Hi @isaacrlevin , the new version of Azure.ResourceManager will be pushed to Nuget at the end of Dec.

**Comment by Yao725** [comment]
Close it as this issue will be fixed with next release of Azure.ResourceManager.

**Comment by StannieV** [comment]
@Yao725 Thank you very much.
