### ISSUE TITLE
List of exceptions that can be thrown by ModuleClient.SendEventAsync is not complete

### ISSUE THREAD

**Issue by fgheysels** [Azure/azure-sdk-for-net#24191]
The documentation mentions that the `SendEventAsync` method can throw an `OperationCanceledException`, and no other exception types are listed.
However, I have a situation where this method throws a `TimeoutException` as well:

![image](https://user-images.githubusercontent.com/3605786/134530420-d7829182-a29a-4edc-a87d-2d76713b247d.png)

It would be nice if the list of exceptions that can be thrown by this method is completed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfaaeae3-f8de-02b1-7bc6-bf22027c0a99
* Version Independent ID: e48c3c7b-1944-6927-cefb-5e505dab8ce4
* Content: [ModuleClient.SendEventAsync Method (Microsoft.Azure.Devices.Client) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.client.moduleclient.sendeventasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Devices.Client/ModuleClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Client/ModuleClient.xml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Devices.Client` library is maintained as [#2176](https://github.com/Azure/azure-iot-sdk-csharp/issues/2176).   Closing this out.
