### ISSUE TITLE
How to Detect an Anonymous Request

### ISSUE THREAD

**Issue by rjarrattmsft** [Azure/azure-sdk-for-net#24208]
I tested a function using Postman where I did not include any kind of Authorization header. When I request.Identities.FirstOrDefault() I get the following exception:

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Azure.Functions.Worker.Grpc
  StackTrace:
   at Microsoft.Azure.Functions.Worker.GrpcHttpRequestData.<>c.<get_Identities>b__16_0(RpcClaimsIdentity id) in D:\a\1\s\src\DotNetWorker.Grpc\Http\GrpcHttpRequestData.cs:line 81
   at System.Linq.Enumerable.SelectIListIterator`2.TryGetFirst(Boolean& found)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LI.CrossBorder.CrossBorderFunction.Run(HttpRequestData request, FunctionContext context) in C:\Source\Repos\Livestock\Integration\source\service\src\LI.CrossBorder\CrossBorderFunction.cs:line 47

How should I test for an anonymous call?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee033456-b610-5325-5e48-ecb12b821c9b
* Version Independent ID: 99068dbe-d073-7199-e957-ece9c70b8db9
* Content: [HttpRequestData.Identities Property (Microsoft.Azure.Functions.Worker.Http) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httprequestdata.identities?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Functions.Worker.Http/HttpRequestData.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Functions.Worker.Http/HttpRequestData.xml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by rjarrattmsft** [comment]
In the debugger I can see that _httpData in GrpcHttpRequestData is as follows:
{{ "method": "POST", "url": "http://localhost:7071/api/CrossBorderFunction", "identities": [ { "nameClaimType": { "value": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name" }, "roleClaimType": { "value": "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" } } ], "nullableHeaders": { "connection": { "value": "keep-alive" }, "accept": { "value": "*/*" }, "accept-encoding": { "value": "gzip, deflate, br" }, "host": { "value": "localhost:7071" }, "user-agent": { "value": "PostmanRuntime/7.28.4" }, "content-length": { "value": "0" }, "postman-token": { "value": "f5180fdd-3a12-4144-9aea-9d240cb1ac47" } } }}

so the code is getting a null reference on id.AuthenticationType.Value.

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Functions.Worker.Core` package is maintained, as [#637](https://github.com/Azure/azure-functions-dotnet-worker/issues/637).
