### ISSUE TITLE
[FEATURE REQ] make Microsoft.Azure.WebJobs.Extensions.ServiceBus support autoComplete:false and retries

### ISSUE THREAD

**Issue by drdamour** [Azure/azure-sdk-for-net#24201]
**Library or service name.**
Microsoft.Azure.WebJobs.Extensions.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
In azure functions we receive messages with automComplete: false so we can defer them or possibly dead letter them. Looking at the retry functionality from host.json i'm confused how these can be compatible.  The retry relies on us throwing an exception, but i never know if it's the "last retry" after reading through #23102  i def can know the delivery count from ASB and maybe deadletter on the first retry...but then i have to keep the two configs in sync.  Otherwise i can't "early" dead letter something, it has to go through all the retries and all the max deliveries with timeouts to end up in the dead letter (put there by ASB, not the receiver)

Is there anyway to know it's the final retry and that i should be calling deadletter on it in autoComplete:false scenarios

**Comment by JoshLove-msft** [comment]
Hi @drdamour, 
Are you talking about the function-level retries described [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp)? Are you saying that you want to allow exceptions to propagate so that the function can be retried and that you want to deadletter it only if the function retries are exhausted?

**Comment by drdamour** [comment]
was actually referring to these retry settings https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#retry-settings

**Comment by JoshLove-msft** [comment]
Ok in that case, I'm a little confused about the use case. Those retries are for errors that occur when communicating with the service. Once you get an exception from any operations with the service, that means that the retries have already been exhausted. You could try deadlettering at that point, but it may not work if the errors you were getting were related to the message lock being lost, for instance.

**Comment by drdamour** [comment]
so i won't see my function being called N times?

**Comment by JoshLove-msft** [comment]
No, these retries are for communicating with the service. Function-level retries are configured differently - see https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-error-pages?tabs=csharp
