### ISSUE TITLE
Why Multiple Identities?

### ISSUE THREAD

**Issue by rjarrattmsft** [Azure/azure-sdk-for-net#24207]
Under what circumstances could there be more than one identity?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee033456-b610-5325-5e48-ecb12b821c9b
* Version Independent ID: 99068dbe-d073-7199-e957-ece9c70b8db9
* Content: [HttpRequestData.Identities Property (Microsoft.Azure.Functions.Worker.Http) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httprequestdata.identities?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Functions.Worker.Http/HttpRequestData.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Functions.Worker.Http/HttpRequestData.xml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Functions.Worker.Core` package is maintained, as [#638](https://github.com/Azure/azure-functions-dotnet-worker/issues/638).
