### ISSUE TITLE
Add more high quality comments

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#24224]
For code where the design decisions, tradeoffs, or critical implementation considerations are not obvious to the average SDK developer, add some high quality comments that provide any relevant context.

**Comment by pallavit** [comment]
@christothes do you have any particular snippets in mind that could benefit from it?
I think this is valuable but I am not sure where to start? How do we identify such code paths in our current code base?

**Comment by christothes** [comment]
None in particular. Initially this was targeted at Core, but it should probably just apply as a general principle moving forward.
