### ISSUE TITLE
Questions about Azure storage failover

### ISSUE THREAD

**Issue by asgoe** [Azure/azure-sdk-for-net#24223]
We had some questions related to azure storage failover and the associated data loss (not sure if this is the correct forum). Based on this public documentation, initiating a manual failover will lead to data loss based on the Last Sync Time property.
https://docs.microsoft.com/en-us/azure/storage/common/storage-disaster-recovery-guidance

Questions:
1) How long does the failover process take? Is this dependent on the amount of data in the account or incoming traffic to the account?
2) If our service is still sending read/write traffic to the storage account when failover is occurring, do these operations succeed? If they do succeed, what happens to the data that is written during this time.
3) To avoid data loss due to a manual failover, is it possible for us to configure the storage account into a read-only mode? We are trying to do this for multiple accounts/services (50-60 services) inside Intune, so doing it at the service level might not be feasible for us.

**Comment by jsquire** [comment]
Hi @asgoe.   Thanks for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK for .NET and we're unable to assist with general questions about the Azure services.   I'd recommend taking creating an [Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).  That will ensure that you've got folks with the right knowledge to assist with your specific questions and scenario.
