### ISSUE TITLE
[FEATURE REQ] Ability to provide EventHubConnectionOptions to the Function Trigger

### ISSUE THREAD

**Issue by gelihu** [Azure/azure-sdk-for-net#24244]
**Library or service name.**
What library or service is this request related to? Microsoft.Azure.WebJobs.Extensions.EventHubs
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added?

I would like the ability to customize the EventHub connection to be added in the EventHub Azure Function trigger so that I can explicitly mention the transport type.

What problem is it solving?

I work behind a proxy, AMQP over TPC doesn't work for me. I would like to change TransportType to AMQP over WebSockets(If required I would like to customize the other properties as well, such as Proxy).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by JoshLove-msft** [comment]
This feature is available in the new version of the extension which is in beta - https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventHubs/5.0.0-beta.7

I don't believe the feature will be added to V4.

**Comment by gelihu** [comment]
Thank you, kindly. I was able to configure the options with the beta package.
