### ISSUE TITLE
[QUERY]How to set AzureWebJobsStorage while using managed identity with blob triggered function?

### ISSUE THREAD

**Issue by lonegunmanb** [Azure/azure-sdk-for-net#24243]
**Query/Question**
Hi there,
I'm an Azure newbie and I want to compose a pr for Terraform Azure Provider to solve this [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/12155), but found myself stuck in figuring out whether I need set `AzureWebJobsStorage` or not. If I need set `AzureWebJobsStorage`, what value should I set since I want get rid of storage account access key?

I've written a blob triggered function:

```csharp
[FunctionName("Function1")]
        public static void Run([BlobTrigger("container1/{name}")]Stream myBlob, [Blob("container2/{name}", FileAccess.Write)] Stream o, string name, ILogger log)
        {
            log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
            myBlob.CopyTo(o);
        }
```

It works fine if I set `AzureWebJobsStorage` with `AccountName` and `AccountKey`, but if I delete `AzureWebJobsStorage` or remove these two properties from the setting, the function stopped working.

I've already granted my system assigned identity `Storage Blob Data Owner` and `Storage Queue Data Contributor` roles to my storage account, and both `container1` `container2` belong to the same storage account, and I've set `AzureWebJobsStorage__accountName` to my storage account name, but still have no luck. Have I missed something? I've read #21753 and I thinks it must be my fault because someone did it.

Would @kasobol-msft be so kind to give me some advice? Many thanks!

-------------------

Btw, as Azure Function builtin monitoring requires `AzureWebJobsDashboard` string, how to compose a valid `AzureWebJobsDashboard` while using mis only? Many thanks!

**Environment:**
 Microsoft.Azure.WebJobs.Extensions.Storage 5.0.0-beta.5
 Visual Studio 2019

**Comment by kasobol-msft** [comment]
@lonegunmanb It's hard to say what went wrong. The setup you described sounds correct to me. The best answer why it doesn't work is most likely in the logs - have you tried capturing them?
Also could you share more details:
- where did you define the `AzureWebJobsStorage__accountName` ?
- are you trying to run it locally or in Azure?
- could you share how your `*.json` configuration files look like?

As for the `AzureWebJobsDashboard`. Please see a note [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings#azurewebjobsdashboard). We recommend to use App Insights instead of WebJobs Dashboard, therefore we didn't provide MSI support there - it's a functionality that's being phased out in favor of App Insights.
Please see this [tutorial](https://docs.microsoft.com/en-us/azure/azure-functions/configure-monitoring?tabs=v2).

**Comment by lonegunmanb** [comment]
@kasobol-msft thank you for your reply!

* where did you define the `AzureWebJobsStorage__accountName` ?

I defined it via WebApp's SiteConfig (I'm using Pulumi's azure native provider), I can see these config via resources.azure.com, the json retrieved as below (https://management.azure.com/subscriptions/{my_subcription_id}/resourceGroups/{my_resource_group_id}/providers/Microsoft.Web/sites/{my_function_app_name}/config/appsettings/list?api-version=2020-12-01):
```json
{
  "id": "/subscriptions/{my_subcription_id}/resourceGroups/{my_resource_group_id}/providers/Microsoft.Web/sites/{my_function_app_name}/config/appsettings",
  "name": "appsettings",
  "type": "Microsoft.Web/sites/config",
  "location": "East Asia",
  "properties": {
    "runtime": "dotnet",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "FUNCTIONS_EXTENSION_VERSION": "~3",
    "AzureWebJobsStorage__accountName": "{my_storage_account_name}",
    "AzureWebJobsDashboard": "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName={my_storage_account_name};AccountKey={{my_storage_account_access_key}"
  }
}
```

* are you trying to run it locally or in Azure?

I'm trying to run the function in Azure.

* could you share how your *.json configuration files look like?

The `host.json` file my Visual Studio generated as below:

```json
{
    "version": "2.0",
    "logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        }
    }
}
```

The `local.settings.json` file my Visual Studio generated as below:

```json
{
    "IsEncrypted": false,
    "Values": {
        "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;AccountName={my_storate_account_name};AccountKey={my_storate_account_access_key;BlobEndpoint=https://{my_storate_account_name}.blob.core.windows.net/;TableEndpoint=https://{my_storate_account_name}.table.core.windows.net/;QueueEndpoint=https://{my_storate_account_name}.queue.core.windows.net/;FileEndpoint=https://{my_storate_account_name}.file.core.windows.net/",
        "FUNCTIONS_WORKER_RUNTIME": "dotnet"
    }
}
```

I used `System assigned` identity and had granted `Storage Blob Data Owner` and `Storage Queue Data Contributor` roles on my storage account.

>The best answer why it doesn't work is most likely in the logs - have you tried capturing them?

My apology I'm newbie to Azure so I'm still searching for how to find the logs, if I found the runtime log, I'll paste here.

Again, thanks a lot for your guidance!

**Comment by lonegunmanb** [comment]
An update.

The first time I created the function app with `AzureWebJobsStorage__accountName` only, there was **NO** storage account queue at all. After I published my dotnet function and uploaded file to `container1`, there was still no queue.

Then, I deleted this function app, and redeployed a new one, with  `AzureWebJobsStorage` which contained `AccountName` and `AccountKey` this time. After the deployment finished, there was still no queue. I redeployed the very same dotnet function again, there was no queue, but after I uploaded file to `container1`, a queue named `azure-webjobs-blobtrigger-{my_function_app_name}` was created, and the replicator function worked as expected.

Since I need grant `Storage Queue Data Contributor` role to identity, was this queue issue blocked my function?

**Comment by lonegunmanb** [comment]
I tried provisioned a Function App with both `AzureWebJobsStorage` and `AzureWebJobsStorage__accountName`, removed `AccountName` and `AccountKey` inside `AzureWebJobsStorage`, then I run my dotnet function on my local machine, connected to this remote Azure Function App, with `local.settings.json` like below:

```json
{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "DefaultEndpointsProtocol=https;BlobEndpoint=https://{my_storage_account_name}.blob.core.windows.net/;TableEndpoint=https://{my_storage_account_name}.table.core.windows.net/;QueueEndpoint=https://{my_storage_account_name}.queue.core.windows.net/;FileEndpoint=https://{my_storage_account_name}.file.core.windows.net/",
    "AzureWebJobsStorage__accountName": "{my_storage_account_name}",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```

And I got error message on local func.exe:
* Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.WindowsAzure.Storage: No valid combination of account information found.
* Error indexing method 'Function1'
* Function 'Function1' failed indexing and will be disabled.

And my local function cannot work properly.

It seems like a complete `AzureWebJobsStorage` was required no matter whether I've used managed identity or not, right? Have I missed something? Thanks!

**Comment by kasobol-msft** [comment]
@lonegunmanb Yes the `Storage Queue Data Contributor` is needed, but you mentioned in original post that you assigned both `Storage Blob Data Owner` and `Storage Queue Data Contributor` roles. If by any chance you omitted one this could have been the reason why it didn't work in Azure.

As for the local environment. I was able to run a function with just `AzureWebJobsStorage__accountName`. It could be that one of libraries or tooling you're using is out of date. 
Can you share your .csproj file as well as the versions of azure functions cli and core tools? (see screenshot below to as for how to find them)
![image](https://user-images.githubusercontent.com/61715331/135121065-3a5b19b2-c65d-4124-bd0a-ffe925efd61d.png)

**Comment by lonegunmanb** [comment]
@kasobol-msft Thanks for your guidance. I'll paste my pulumi code as well as my Azure Function project info here, hopefully I can figure out which part i've screwed up.

My pulumi code here:
```csharp
public MyStack()
    {
        var resourceGroup = new ResourceGroup($"keyless", new ResourceGroupArgs
        {
            Location = "East Asia",
        });

        var storageAccount = new StorageAccount($"keyless", new StorageAccountArgs
        {
            ResourceGroupName = resourceGroup.Name,
            AccountName = "keyless210929",
            Location = "East Asia",
            Sku = new SkuArgs
            {
                Name = SkuName.Standard_LRS
            },
            Kind = Kind.StorageV2
        });

        var primaryKey = Output.All(new Output<string>[] {resourceGroup.Name, storageAccount.Name}).Apply(async array =>
        {
            var resourceGroupName = array[0];
            var storageAccountName = array[1];
            var keys = await ListStorageAccountKeys.InvokeAsync(new ListStorageAccountKeysArgs
            {
                ResourceGroupName = resourceGroupName,
                AccountName = storageAccountName,
            });
            return keys.Keys[0].Value;
        });

        var storageContainer = new BlobContainer("keyless", new BlobContainerArgs
        {
            AccountName = storageAccount.Name,
            ContainerName = "keyless",
            PublicAccess = PublicAccess.None,
            ResourceGroupName = resourceGroup.Name,
        });

        var storageContainer2 = new BlobContainer("keyless2", new BlobContainerArgs
        {
            AccountName = storageAccount.Name,
            ContainerName = "keyless2",
            PublicAccess = PublicAccess.None,
            ResourceGroupName = resourceGroup.Name,
        });

        var functionApp = new WebApp($"keyless2", new WebAppArgs
        {
            Name = "keylesspulumi",
            Kind = "FunctionApp",
            Location = "East Asia",
            ResourceGroupName = resourceGroup.Name,
            // ServerFarmId = appServicePlan.Id,
            Identity = new ManagedServiceIdentityArgs
            {
                Type = Pulumi.AzureNative.Web.ManagedServiceIdentityType.SystemAssigned
            },
            SiteConfig = new SiteConfigArgs
            {
                AppSettings = new[]
                {
                    new NameValuePairArgs
                    {
                        Name = "runtime",
                        Value = "dotnet",
                    },
                    new NameValuePairArgs
                    {
                        Name = "FUNCTIONS_WORKER_RUNTIME",
                        Value = "dotnet",
                    },
                    new NameValuePairArgs
                    {
                        Name = "FUNCTIONS_EXTENSION_VERSION",
                        Value = "~3"
                    },
                    new NameValuePairArgs
                    {
                        Name = "AzureWebJobsStorage__accountName",
                        Value = storageAccount.Name
                    },
                },
            },
        });
    }
```

The Function's application settings only contain `AzureWebJobsStorage__accountName`, with storage account name as it's value.
I've met some authorization issues when I use pulumi's RoleAssignment feature, so I added `Storage Queue Data Contributor` and `Storage Blob Data Owner` manually after the stack was successful created.

The local dotent Azure Function csproj file (generated by Visual Studio 2019's default template):

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0-beta.5" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```

The local.settings.json file:
```json
{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage__name": "keyless210929",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```

The Function1.cs file:
```csharp
using System;
using System.IO;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;

namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static void Run([BlobTrigger("keyless/{name}", Connection = "")]Stream myBlob, string name, ILogger log)
        {
            log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
        }
    }
}
```

After I runned my local dotnet function, the output is below:

```shell
Azure Functions Core Tools
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
Function Runtime Version: 3.0.15417.0

[2021-09-29T02:09:15.344Z] Found D:\project\filelengther\FunctionApp1\FunctionApp1.csproj. Using for user secrets file configuration.
Missing value for AzureWebJobsStorage in local.settings.json. This is required for all triggers other than httptrigger, kafkatrigger, orchestrationTrigger, activityTrigger, entityTrigger. You can run 'func azure functionapp fetch-app-settings <functionAppName>' or specify a connection string in local.settings.json.
Press any to continue....
```

And like before, the uploading file to `keyless` container didn't trigger this function.

**Comment by lonegunmanb** [comment]
@kasobol-msft Thanks for your guidance. I'll paste my pulumi code as well as my Azure Function project info here, hopefully I can figure out which part i've screwed up.

My pulumi code here:

```csharp
public MyStack()
    {
        var resourceGroup = new ResourceGroup($"keyless", new ResourceGroupArgs
        {
            Location = "East Asia",
        });

        var storageAccount = new StorageAccount($"keyless", new StorageAccountArgs
        {
            ResourceGroupName = resourceGroup.Name,
            AccountName = "keyless210929",
            Location = "East Asia",
            Sku = new SkuArgs
            {
                Name = SkuName.Standard_LRS
            },
            Kind = Kind.StorageV2
        });

        var primaryKey = Output.All(new Output<string>[] {resourceGroup.Name, storageAccount.Name}).Apply(async array =>
        {
            var resourceGroupName = array[0];
            var storageAccountName = array[1];
            var keys = await ListStorageAccountKeys.InvokeAsync(new ListStorageAccountKeysArgs
            {
                ResourceGroupName = resourceGroupName,
                AccountName = storageAccountName,
            });
            return keys.Keys[0].Value;
        });

        var storageContainer = new BlobContainer("keyless", new BlobContainerArgs
        {
            AccountName = storageAccount.Name,
            ContainerName = "keyless",
            PublicAccess = PublicAccess.None,
            ResourceGroupName = resourceGroup.Name,
        });

        var storageContainer2 = new BlobContainer("keyless2", new BlobContainerArgs
        {
            AccountName = storageAccount.Name,
            ContainerName = "keyless2",
            PublicAccess = PublicAccess.None,
            ResourceGroupName = resourceGroup.Name,
        });

        var functionApp = new WebApp($"keyless2", new WebAppArgs
        {
            Name = "keylesspulumi",
            Kind = "FunctionApp",
            Location = "East Asia",
            ResourceGroupName = resourceGroup.Name,
            // ServerFarmId = appServicePlan.Id,
            Identity = new ManagedServiceIdentityArgs
            {
                Type = Pulumi.AzureNative.Web.ManagedServiceIdentityType.SystemAssigned
            },
            SiteConfig = new SiteConfigArgs
            {
                AppSettings = new[]
                {
                    new NameValuePairArgs
                    {
                        Name = "runtime",
                        Value = "dotnet",
                    },
                    new NameValuePairArgs
                    {
                        Name = "FUNCTIONS_WORKER_RUNTIME",
                        Value = "dotnet",
                    },
                    new NameValuePairArgs
                    {
                        Name = "FUNCTIONS_EXTENSION_VERSION",
                        Value = "~3"
                    },
                    new NameValuePairArgs
                    {
                        Name = "AzureWebJobsStorage__accountName",
                        Value = storageAccount.Name
                    },
                },
            },
        });
    }
```
The Function's application settings only contain `AzureWebJobsStorage__accountName`, with storage account name as it's value.
I've met some authorization issues when I use pulumi's `RoleAssignment` feature, so I added `Storage Queue Data Contributor` and `Storage Blob Data Owner` manually after the stack was successfully created.

The local dotent Azure Function csproj file (generated by Visual Studio 2019's default template):

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0-beta.5" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```
The local.settings.json file:

```json
{
    "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage__accountName": "keyless210929",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet"
  }
}
```
The Function1.cs file:

```csharp
using System;
using System.IO;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;

namespace FunctionApp1
{
    public static class Function1
    {
        [FunctionName("Function1")]
        public static void Run([BlobTrigger("keyless/{name}", Connection = "")]Stream myBlob, string name, ILogger log)
        {
            log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
        }
    }
}
```
After I runned my local dotnet function, the output is below:

```shell
Azure Functions Core Tools
Core Tools Version:       3.0.3442 Commit hash: 6bfab24b2743f8421475d996402c398d2fe4a9e0  (64-bit)
Function Runtime Version: 3.0.15417.0

[2021-09-29T02:27:52.486Z] Found D:\project\filelengther\FunctionApp1\FunctionApp1.csproj. Using for user secrets file configuration.
Missing value for AzureWebJobsStorage in local.settings.json. This is required for all triggers other than httptrigger, kafkatrigger, orchestrationTrigger, activityTrigger, entityTrigger. You can run 'func azure functionapp fetch-app-settings <functionAppName>' or specify a connection string in local.settings.json.
Press any to continue....
```

And like before, the uploading file to keyless container didn't trigger this function.

**Comment by kasobol-msft** [comment]
@lonegunmanb Thanks for the details. I have the following suggestions.

You mentioned that you got a function deployed to Azure working by granting relevant roles. I'm not sure why you'd add additional `AzureWebJobsStorage` to app settings. I suggest to remove it.

As for local development. It appears that you're using older `Azure Functions Core Tools/Function Runtime Version`. The minimum version where secretless support was added is `3.0.15733.0`. However, I suggest to update to latest. Please see [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v3%2Cwindows%2Ccsharp%2Cportal%2Cbash%2Ckeda#install-the-azure-functions-core-tools) how to do this.

**Comment by lonegunmanb** [comment]
Hello @kasobol-msft , finally my function worked on Azure with `AzureWebJobsStorage__accountName` only, thanks to your guidance, I can't get this far without your help.
But my function worked after I add `Owner` role to my identity on my storage account, otherwise the log in application insight will complain about permission denied on reading storage secret. I guess there must some other  iam issues on my side, nevertheless it's enough for me to continue my terraform work.
Thanks again, you saved my day!
