### ISSUE TITLE
[BUG] Azure.Messaging.ServiceBus messages bigger than 1MB are empty

### ISSUE THREAD

**Issue by Uleertel** [Azure/azure-sdk-for-net#24253]
**Describe the bug**
I have a Premium Service Bus namespace with a topic configured to receive messages up to 100MB.
I have created a basic .NET 5 console app using the latest 7.2.1 Azure.Messaging.ServiceBus package.
I send to the topic a message with a string slightly over 1MB which was the old limit.
The message is sent without error.
In the queue the message exists but it is empty and with a size of 0. (checked with the azure portal service bus explorer, and queue explorer application).
I have tested both ServiceBusTransportType.AmqpWebSockets/AmqpTcp TransportTypes

**Expected behavior**
The message should not be empty.

**Actual behavior (include Exception or Stack Trace)**
The message with a content over 1MB is sent successfully but appears to have an empty content in the queue.

**To Reproduce**

string fileContent = File.ReadAllText("file.Log");

            var option = new ServiceBusClientOptions();

            option.TransportType = ServiceBusTransportType.AmqpTcp;

            client = new ServiceBusClient(connectionString, option);

            sender = client.CreateSender(queueName);

            await sender.SendMessageAsync(new ServiceBusMessage(fileContent));

**Environment:**
 - Azure.Messaging.ServiceBus 7.2.1
 - Windows 10 .NET 5
 - VS 16.11.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Uleertel** [comment]
I close my request because after further testing it is not a bug in the sending of the message but only a display bug on the Azure Portal where the service bus Explorer is showing empty message whereas it's not. And other tools have the same bug like Queue explorer or Service bus explorer application.
When the message is read, for example by an azure function trigger, the full content is received.
