### ISSUE TITLE
[FEATURE REQ] Please update Azure Maps Management package

### ISSUE THREAD

**Issue by YaroslavKormushyn** [Azure/azure-sdk-for-net#24273]
**Library or service name.**

`Microsoft.Azure.Management.Maps` or  `Azure.ResourceManager.Maps` _(future)_
 
**Is your feature request related to a problem? Please describe.**

_Problem:_ Right now in order to manage Azure Maps Creator resources only the `Microsoft.Azure.Management.ResourceManager` does the job. Unfortunately the [check resource existence endpoint](https://docs.microsoft.com/en-us/rest/api/resources/resources/check-existence) and [get azure maps creator resource](https://docs.microsoft.com/en-us/rest/api/maps-management/creators/get) collide. When sending a check existence request via the mentioned above package I receive a `405 method not allowed` response. This is due to the fact that the Get for Azure Maps Creator requires a `GET` method, while the package sends a `HEAD` request.

For some reason, the API does not favor the `2021-04-01` API version in the query parameters.

The `Microsoft.Azure.Management.Maps` package is lacking Azure Maps Creator management operations. API reference [here](https://docs.microsoft.com/en-us/rest/api/maps-management/creators).

I'd like to suggest regenerating the SDK package for maps management in order to include these Creator operations.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by archerzz** [comment]
`Microsoft.Azure.Management.Maps` hasn't been updated for 3 years. We need to ping service team to update the SDK. Otherwise , it will take quite some time to wait for `Azure.ResourceManager.Maps`.

**Comment by YaroslavKormushyn** [comment]
The package hasn't been updated and neither did the team publish a new SDK package. No resolution so far.

**Comment by ArthurMa1978** [comment]
@YaroslavKormushyn we have released the new SDK [Azure.ResourceManager.Maps](https://www.nuget.org/packages/Azure.ResourceManager.Maps/) which the api-version is `2021-02-01`, is this solve your problem?

**Comment by YaroslavKormushyn** [comment]
Yes, I have been using it since beta-1 and it's working fine. Thank you.
