### ISSUE TITLE
[BUG] Trying to create a BlobClient using a SAS uri throws "The method or operation is not implemented." 12.10.0

### ISSUE THREAD

**Issue by dsancho** [Azure/azure-sdk-for-net#24277]
**Describe the bug**
Trying to create a BobClient using a SAS uri throws "The method or operation is not implemented." 

**Expected behavior**
The BlobClient it's created with no error as in 12.9.1 version

**Actual behavior (include Exception or Stack Trace)**
An exception it's thrown in version 12.10.0. Just downgrade nuget package to 12.9.1 and everything it's fine.

**To Reproduce**
Create a SAS uri with write access.
var blob = new BlobClient(new Uri(response.UploadLink));
Using version 12.10.0 this line throws and exception (The method or operation is not implemented.). Version 12.9.1 doesn't.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.10.0 
 - Hosting platform or OS and .NET runtime version: Xamarin Forms (android). Library using .NET 5.0
 - IDE and version : Visual Studio 16.11.3

**Comment by seanmcc-msft** [comment]
Hi @dsancho, could you provide more information?  What is `response.UploadLink`?  Could you provide a more detailed repo?

Thanks,

-Sean

**Comment by dsancho** [comment]
It's a string property that contains just a generated SAS like
https://XXXXX.blob.core.windows.net/XXXXXX/ZweUxYw8cUOlh9fcJPTR5VCHyQEtqq.jpg?sv=2020-08-04&st=2021-09-28T15%3A04%3A04Z&se=2021-09-28T15%3A07%3A04Z&sr=b&sp=w&sig=Vq%2FOpTuh3ZYoI3Ji%2Byw7u3qOuARvfDCXLPqs8k1As6A%3D

By the way, I have discovered that with version 12.9.1 works fine in debug mode BUT in release mode (only in Android) happens this [https://github.com/Azure/azure-sdk-for-net/issues/24127](https://github.com/Azure/azure-sdk-for-net/issues/24127)
so I have to change the constructor to disable logging.
```
var blob = new BlobClient(new Uri(response.UploadLink), 
          new BlobClientOptions()
        {
          Diagnostics = { IsLoggingEnabled = false}
        });
```

**Comment by JoshLove-msft** [comment]
Sounds like the same issue described in https://github.com/Azure/azure-sdk-for-net/issues/24055

**Comment by petro2050** [comment]
I get an error when creating a **BlockBlobClient** in Xamarin Forms.

Here's the usage:

`var blockBlobClient = new BlockBlobClient(sasString);`

This is the error:

`System.TypeInitializationException: 'The type initializer for 'Azure.Core.Diagnostics.AzureCoreEventSource' threw an exception.'`

```
  at System.Diagnostics.Tracing.EventSource.GetSources () [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Diagnostics.Tracing/EventSource.cs:318 
  at Azure.Core.Diagnostics.AzureEventSource.DeduplicateName (System.String eventSourceName) [0x00010] in <0aa90fe0646d47bc95bff520717dbf16>:0 
  at Azure.Core.Diagnostics.AzureEventSource..ctor (System.String eventSourceName) [0x00000] in <0aa90fe0646d47bc95bff520717dbf16>:0 
  at Azure.Core.Diagnostics.AzureCoreEventSource..ctor () [0x00000] in <0aa90fe0646d47bc95bff520717dbf16>:0 
  at Azure.Core.Diagnostics.AzureCoreEventSource..cctor () [0x00000] in <0aa90fe0646d47bc95bff520717dbf16>:0 
```
