### ISSUE TITLE
[Monitor Query] Azure.RequestFailedException : The requested path does not exist Status: 404 (Not Found)

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#24274]
- **Package Name**: Azure.Monitor.Query
- **Package Version**: 1.0.0-alpha.20210927.1

**Error Description:**
When running [QueryLogsAsTable Sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.Query/tests/LogsQueryClientSamples.cs#L18), it runs failed and the error message is shown as following.

![image](https://user-images.githubusercontent.com/76771069/135050452-02245a3f-51a7-43f5-9dd5-2e6bf1d042e5.png)

**Error Track:**
The code that failed is [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.Query/src/LogsQueryClient.cs#L23)：

![image](https://user-images.githubusercontent.com/76771069/135052155-390baad4-3e3b-4790-896e-6347000ba516.png)

We guess is that the endpoint link is wrong.

**Expected Behavior:**
The variable `_defaultEndpoint` is a correct value. We can successfully access this endpoint.

@scottaddie,@AlexGhiondea,@srnagar and @nisha-bhatia for notification.

**Comment by v-xuto** [comment]
@nisha-bhatia Do you have any progress or plans about this issue?

**Comment by scottaddie** [comment]
@v-xuto @v-yilinhu Are either of you still able to reproduce this error? Note that the endpoint has changed since you reported this issue.

**Comment by v-yilinhu** [comment]
@scottaddie This issue has been fixed, we will close it.
