### ISSUE TITLE
[FormRecognizer] A field's confidence is not always being returned

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#24292]
In `DocumentAnalysisClientLiveTests.cs`, there's a code section marked with "TODO: confidence should be returned." in one of our validation methods.

```cs
// TODO: confidence should be returned.
if (field.Confidence != null)
{
    Assert.That(field.Confidence, Is.GreaterThanOrEqualTo(0.0).Within(0.01));
    Assert.That(field.Confidence, Is.LessThanOrEqualTo(1.0).Within(0.01));
}
```

This assertion was not necessary in V2 tests. Has the service behavior changed? Was it intentional?

**Comment by pallavit** [comment]
@kinelski this has a PR associated with it. Can this issue be closed?

**Comment by pallavit** [comment]
@kinelski is this still a valid concern?
