### ISSUE TITLE
[QUERY] Azure.ResourceManager.Communication v1 package is not visible in Nuget

### ISSUE THREAD

**Issue by usvoyager** [Azure/azure-sdk-for-net#24318]
**Query/Question**
How can we help?
Why Azure.ResourceManager.Communication 1.0.0 deprecated? I only see beta packages in Nuget. 

**Environment:**
 - Name and version of the Library package used: Azure.ResourceManager.Communication 1.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): N/A
 - IDE and version : N/A

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
fixed
