### ISSUE TITLE
Need help to redact credit card number , CVV and password 

### ISSUE THREAD

**Issue by callratnesh** [Azure/azure-sdk-for-net#24321]
**Query/Question**
How can we help?
It's easy to redact  Bank account number and Social security number via TextAnalyticsClient. 
However credit card number, CVV number and pin was not getting redact.
Please provide a sample to redact Credit card number , CVV and pin using TextAnalyticsClient.
 RecognizePiiEntitiesOptions options = new RecognizePiiEntitiesOptions() { CategoriesFilter = { PiiEntityCategory.CreditCardNumber} }; 

doesn't work.

**Environment:**
 - Name and version of the Library package used:  **Azure.AI.TextAnalytics (5.1.0)**
 - Hosting platform or OS and .NET runtime version : [ Windows 10 .NET Framework 5.0]
 - IDE and version : [ Visual Studio 16.11.2]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AlexGhiondea** [comment]
@maririos @kinelski any thoughts on this one?

**Comment by maririos** [comment]
Hi @callratnesh 

Looking at the `PiiEntityCategory` types, the Credit card number should be `CreditCardNumberValue`.

I am not seeing a specific value for CVV or pin. 
@abhahn / @suhas92  do you have more recommendations here?

**Comment by bkmallow** [comment]
@maririos There is  `CreditCardNumberValue` in `PiiEntityCategory` but in testing it doesn't flag common credit card formats.

**Comment by bkmallow** [comment]
@ali-emami the CC redaction isn't working at all for myself on "My credit card number is ####-####-####-####"
