### ISSUE TITLE
[Identity] AuthenticateWithVscCredential_EmptySettingsFile failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#24332]
Identity nightly test runs are failing with:

> Error message
> Azure.Identity.AuthenticationFailedException : VisualStudioCodeCredential authentication failed: AADSTS65002: Consent between first party application 'aebc6443-996d-45c2-90f0-388ff96faa56' and first party resource '00000003-0000-0000-c000-000000000000' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.
> Trace ID: fe7d6ea7-3296-4b21-b06a-83d960e5bd00
> Correlation ID: df8d763a-fb27-4e09-8bdd-1054a636f0ef
> Timestamp: 2021-09-24 05:28:06Z
> ----> Microsoft.Identity.Client.MsalServiceException : AADSTS65002: Consent between first party application 'aebc6443-996d-45c2-90f0-388ff96faa56' and first party resource '00000003-0000-0000-c000-000000000000' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.
> Trace ID: fe7d6ea7-3296-4b21-b06a-83d960e5bd00
> Correlation ID: df8d763a-fb27-4e09-8bdd-1054a636f0ef
> Timestamp: 2021-09-24 05:28:06Z
> 
> 
> Stack trace
>    at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex) in /_/sdk/identity/Azure.Identity/src/CredentialDiagnosticScope.cs:line 49
>    at Azure.Identity.VisualStudioCodeCredential.GetTokenImplAsync(TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken) in /_/sdk/identity/Azure.Identity/src/VisualStudioCodeCredential.cs:line 93
>    at Azure.Identity.VisualStudioCodeCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken) in /_/sdk/identity/Azure.Identity/src/VisualStudioCodeCredential.cs:line 56
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 165
>    at Azure.Identity.Tests.VisualStudioCodeCredentialLiveTests.AuthenticateWithVscCredential_EmptySettingsFile() in /mnt/vss/_work/1/s/sdk/identity/Azure.Identity/tests/VisualStudioCodeCredentialLiveTests.cs:line 73
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> --MsalServiceException
>    at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
>    at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
>    at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
>    at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
>    at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
>    at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
>    at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
>    at Microsoft.Identity.Client.Internal.Requests.ByRefreshTokenRequest.ExecuteAsync(CancellationToken cancellationToken)
>    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
>    at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByRefreshTokenParameters refreshTokenParameters, CancellationToken cancellationToken)
>    at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken) in /_/sdk/identity/Azure.Identity/src/AbstractAcquireTokenParameterBuilderExtensions.cs:line 15
>    at Azure.Identity.MsalPublicClient.AcquireTokenByRefreshTokenCoreAsync(String[] sco

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1111788&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1113907&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1116822&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1119074&view=results

**Comment by jsquire** [comment]
@v-xuto:  If we're not sure which individual to assign, please do not triage.   Leaving the `needs-triage` alone and in-place will ensure that our normal triage process detects these.

**Comment by christothes** [comment]
fixed by https://github.com/Azure/azure-sdk-for-net/pull/24212
