### ISSUE TITLE
Is there a way to register clients after the Dependency Container is constructed?

### ISSUE THREAD

**Issue by JohanKlijn** [Azure/azure-sdk-for-net#24357]
**Query/Question**
Is there a way to register clients after the Dependency Container is constructed?

Why: I have Azure functions which is triggered when a blob is added to a container (Microsoft.Storage.BlobCreated). The Azure functions is listening to a storage queue. The storage queue is filled by multiple different blob storages (e.g. https://storage1.blob.core.windows.net/, https://storage2.blob.core.windows.net/, https://storagexyz.blob.core.windows.net/), using blob storage events. In this case the Azure function doesn’t now, upfront, from which blob storages are being used, so the BlobContainerClients can be registered during startup, using:
AddBlobServiceClient(connectionString).WithCredential(new DefaultAzureCredential())

Is there a way to register clients at “runtime” after the DI container is created?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
>Is there a way to register clients at “runtime” after the DI container is created?

No, unfortunately, there is no way to add more clients to DI after it's started. You can still construct clients directly. `new BlobServiceClient(...)`
