### ISSUE TITLE
Please provide a link to the new API/method for offline cache

### ISSUE THREAD

**Issue by bigjonroberts** [Azure/azure-sdk-for-net#24355]
The release notes [here](https://github.com/Azure/AppConfiguration/pull/544) indicate that the current implementation will be removed. This implies that there will be a replacement. Has this been finalized yet and is it documented anywhere?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 586bc2ba-830f-67cf-5ab1-562910528910
* Version Independent ID: 58b6dd65-b7c0-40d5-7129-4486cf3f9951
* Content: [OfflineFileCache Class (Microsoft.Extensions.Configuration.AzureAppConfiguration) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.offlinefilecache?view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Extensions.Configuration.AzureAppConfiguration/OfflineFileCache.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Extensions.Configuration.AzureAppConfiguration/OfflineFileCache.xml)
* Service: **azure-app-configuration**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Extensions.Configuration.AzureAppConfiguration` package is maintained as [#277](https://github.com/Azure/AppConfiguration-DotnetProvider/issues/277).
