### ISSUE TITLE
[FEATURE REQ] Include SessionId in metadata bindings for ServiceBusTrigger on .NET 5 Isolated

### ISSUE THREAD

**Issue by jackelliottorr** [Azure/azure-sdk-for-net#24358]
**Library or service name.**
I'm using Microsoft.Azure.Functions.Worker.ServiceBusTrigger on .NET 5 Isolated.
 
**Is your feature request related to a problem? Please describe.**
As far as I can tell, there is no way to get the session id of a queue session. Creating feature request based off stackoverflow answer [here](https://stackoverflow.com/a/69401969/4266005).

**Comment by sonic1981** [comment]
Related feature request but doesn't quite fit the requirements here https://github.com/Azure/azure-sdk-for-net/issues/24358. took over 2 years for this one so I wouldn't be holding my breath

**Comment by danielabbatt** [comment]
Yes its frustrating that the sessionId can't be retreived.

**Comment by JoshLove-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-net/issues/27120
