### ISSUE TITLE
[SEARCH] Add support for language auto-detection in OcrSkill

### ISSUE THREAD

**Issue by tiantun** [Azure/azure-sdk-for-net#24384]
**Library or service name.**
Microsoft.Azure.Search
Azure.Search.Documents
 
**Is your feature request related to a problem? Please describe.**
Enabling auto-detection on the OCR Skill requires setting the "defaultLanguageCode" to "unk". See [OCR cognitive skill](https://docs.microsoft.com/en-us/azure/search/cognitive-search-skill-ocr):
"If the language code is unspecified or null, the language will be set to English. If the language is explicitly set to "unk", the language will be auto-detected."
This seems to be the behaviour since at least early 2019:
[Set to "unk" to have system auto-detect language.](https://github.com/microsoft/azure-docs/commit/98f315c8a7f48a2c3b585e57303f43b6ef05db0d)
However, this is currently not possible in the Search SDKs.
- For Microsoft.Azure.Search see [OcrSkillLanguage](https://github.com/Azure/azure-sdk-for-net/blob/0482e784841be94047dec98e6b2c092ed1be7e56/sdk/search/Microsoft.Azure.Search.Service/src/Generated/Models/OcrSkillLanguage.cs#L22)
- For Azure.Search.Documents see [OcrSkillLanguage](https://github.com/Azure/azure-sdk-for-net/blob/bbeffa852ae770321bcc75b287402b7dc1f6d90d/sdk/search/Azure.Search.Documents/src/Generated/Models/OcrSkillLanguage.cs#L20)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Mohit-Chakraborty** [comment]
Thanks @tiantun for reporting the issue and suggesting a change to fix the issue.

**Comment by Mohit-Chakraborty** [comment]
I see a PR has been created against the target branch - https://github.com/Azure/azure-rest-api-specs/pull/16279

**Comment by tiantun** [comment]
Thank you @Mohit-Chakraborty .
Looks like  the changes were already merged into the API specs.

Can we keep this one open until the generated code in the SDK is updated as well?
That would simplify tracking of the "unk" value's availability in the SDK.

**Comment by Mohit-Chakraborty** [comment]
Sure. Since this issue is in the .NET SDK repo, we will keep it open till we consume the change in the SDK.

**Comment by salslab** [comment]
Do we know when this will be available in the SDK?

**Comment by Mohit-Chakraborty** [comment]
It was added in '11.4.0-beta.6'.
The [Changelog ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/CHANGELOG.md#1140-beta6-2022-02-08)has a mention.

I will close the issue. Let me know if there are issues.
