### ISSUE TITLE
Typos - Commands

### ISSUE THREAD

**Issue by kasunsjc** [Azure/azure-sdk-for-net#24383]
[Enter feedback here]

There are typos in the commands

![image](https://user-images.githubusercontent.com/16514562/135820391-8795adde-95c5-4706-893e-a0c2c01bd66e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a46dbde4-c75c-96d1-fbdf-b0b6f2418153
* Version Independent ID: d1bfd135-1404-341a-1095-18d32c58cd1a
* Content: [Database.Sku Property (Microsoft.Azure.Management.Sql.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.sql.models.database.sku?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Sql.Models/Database.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Sql.Models/Database.xml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Reference doc, will contact docs team
