### ISSUE TITLE
How to edit Azure WebRole Diagnostics in VS2013 with GUI

### ISSUE THREAD

**Issue by tokiwoousaka** [Azure/azure-sdk-for-net#2438]
When I create Azure WebRole Project with VS2013(Microsoft Azure Tools 2.9), then I can not edit azure diagnostics setting in WebRole Project Property.

![screenshot](https://cloud.githubusercontent.com/assets/2379085/19141181/fc55a7f6-8bcd-11e6-97ac-f951a2394cb7.png)

Showing `To edit the diagnostics configuration for the role, fix the schema validation errors for the diagnostic configuration file in the Error List`
but error list does not show scheme error.

thx.

**Comment by markcowl** [comment]
@tokiwoousaka This repo is just for azure management sdk, please ask this question in the VS or Azure support forums
