### ISSUE TITLE
bounding box documentation

### ISSUE THREAD

**Issue by jds3d** [Azure/azure-sdk-for-net#24387]
[Enter feedback here]
the documentation doesn't describe the 8 numbers in the bounding box very well.  is it x,y or y,x?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26bb789f-a164-a962-77fa-963b26c68f8d
* Version Independent ID: d09f289c-d0f3-c67f-489a-5d732a35483b
* Content: [FieldBoundingBox Struct (Azure.AI.FormRecognizer.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.models.fieldboundingbox?view=azure-dotnet)
* Content Source: [xml/Azure.AI.FormRecognizer.Models/FieldBoundingBox.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.AI.FormRecognizer.Models/FieldBoundingBox.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by maririos** [comment]
Hi @jds3d 

Looking at the documentation on https://docs.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.models.fieldboundingbox?view=azure-dotnet I see how what you are pointing out is missing.  It is `(x,y)`.
Here is an example using the SDK where we are printing the Bounding box details: https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.FormRecognizer_3.1.1/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/Sample1_RecognizeFormContent.md#recognize-form-content-from-a-uri

Let me know if that helps.

**Comment by jds3d** [comment]
thank you, that was a very quick response.  it was just confusing for me
because we were getting x values that were not changing despite indentation
so i just wanted to rule out the possibility that I was reading it
backwards.

**Comment by maririos** [comment]
Sure thing. Feel free to close the issue if your question has been resolved

**Comment by jds3d** [comment]
You can close it.
