### ISSUE TITLE
Examples for QuerySpecification

### ISSUE THREAD

**Issue by marincon-sarmiento** [Azure/azure-sdk-for-net#24392]
[Enter feedback here]
Hi there, 

It would be helpful if you guys included an 'examples' section in the QuerySpecification page. I haven't been able to find any examples of how to make the right queries to DPS other than "SELECT * FROM enrollments". 

In my case, I am trying to query a specific registrationId, but always get the enrollement information for all my devices, probably because my query is not correct ($"SELECT * FROM enrollments WHERE enrollments.registrationId = '{registrationId}'"   this query is in C# by the way.)

Thank you very much, 

Miguel Rincon. 

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e07b1bea-e9c6-fe35-e16f-2f4a6017b6bb
* Version Independent ID: 8539d973-542c-f3ab-17b7-ba474cca0cc9
* Content: [QuerySpecification Class (Microsoft.Azure.Devices.Provisioning.Service) - Azure for .NET Developers](https://docs.microsoft.com/en-ca/dotnet/api/microsoft.azure.devices.provisioning.service.queryspecification?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Devices.Provisioning.Service/QuerySpecification.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Provisioning.Service/QuerySpecification.xml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Devices.Provisioning.Service` package is maintained as, [#2188](https://github.com/Azure/azure-iot-sdk-csharp/issues/2188).
