### ISSUE TITLE
[FEATURE REQ] Add `Uri` property on `TableClient` and `TableServiceClient`

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#24415]
Add `TableServiceClient.Uri` property
   - This is helpful for diagnostics, for example if you have the wrong cloud endpoint suffix provided
   - `BlobServiceClient` has this
   - `QueueServiceClient` has this

(extracted from #19881)

**Comment by LeaShallev** [comment]
Same request is relevant also for TableClient as available for ContainerClient, BlobClient and QueueClient

**Comment by wsugarman** [comment]
@christothes - Is there any timeline for this addition? It seems like an oversight, especially when the documentation for [Azure Storage performance](https://docs.microsoft.com/en-us/azure/storage/common/troubleshoot-storage-performance#investigating-client-performance-issues) concerning the Nagle Algorithm would require it.
