### ISSUE TITLE
[Bug] Upload large file to blob storage

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-for-net#24420]
### Discussed in https://github.com/Azure/azure-sdk-for-net/discussions/24109

<div type='discussions-op-text'>

<sup>Originally posted by **lappy4711** September 19, 2021</sup>
I am having great difficulty uploading a 50GB file to blob storage. I have tried both v12 BlockBlobClient UploadAsync (which does staging and commit of chunks internally) and I have tried to stage and commit manually myself. The problem is at the end of the transfer....In the manual case CommitBlockListAsync "never" returns, it takes hours....and then I get a timeout somewhere. Same behaviour with UploadAsync. I even get the same behaviour with the Data Movement Library. Anyone have an idea what is going on? 5GB for example works perfectly.</div>

**Comment by amnguye** [comment]
Could we get a stack trace of the timeout using the v12 library? (Unless there isn't one..)

I wonder if the timeout isn't long enough for how long the CommitBlockListAsync takes, so then we reach the default timeout time and then cancel the request we are waiting on.

**Comment by amishra-dev** [comment]
@kasobol-msft / @amnguye was this addressed?
