### ISSUE TITLE
SharedAccessBlobPermissions

### ISSUE THREAD

**Issue by Vladis466** [Azure/azure-sdk-for-net#24432]
[Enter feedback here]
Would be nice if there was a little more detail to what the enums meant. 
For example the difference between write, create, and add is not clear. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b9e09aa6-cf60-4a83-40f8-6739819acf2f
* Version Independent ID: 27c9ab34-6ea1-e9b8-85ba-644ef41ee5a0
* Content: [SharedAccessBlobPermissions Enum (Microsoft.Azure.Storage.Blob) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.sharedaccessblobpermissions?view=azure-dotnet-legacy)
* Content Source: [xml/Microsoft.Azure.Storage.Blob/SharedAccessBlobPermissions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.Blob/SharedAccessBlobPermissions.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by seanmcc-msft** [comment]
@Vladis466, Microsoft.Azure.Storage.Blobs v11.x is deprecated.  We recommend you move to [Azure.Storage.Blobs v12.x](https://www.nuget.org/packages/Azure.Storage.Blobs/).
