### ISSUE TITLE
[Track 2 Candidate]Update plans toward Microsoft.Azure.Management.SecurityInsights ??

### ISSUE THREAD

**Issue by MauRiEEZZZ** [Azure/azure-sdk-for-net#24435]
**Query/Question**
Are there any plans in updating this part of the SDK with the newer API for sentinel incidents? like api-version=2021-04-01
There are more endpoints exposed like: https://docs.microsoft.com/en-us/rest/api/securityinsights/incidents/list-of-entities which are not included in the current version.

**Environment:**
`<PackageReference Include="Microsoft.Azure.Management.SecurityInsights" Version="1.0.0" />`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by MauRiEEZZZ** [comment]
Any news?

**Comment by ArthurMa1978** [comment]
@MauRiEEZZZ will check with service team if the sdk can upgrade to 2021-04-01 or wait for the new version

**Comment by ArthurMa1978** [comment]
The latest release https://www.nuget.org/packages/Azure.ResourceManager.SecurityInsights is 2022-11.
