### ISSUE TITLE
[FormRecognizer] Hide FormContentType enum's JSON member

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24449]
@kinelski commented on [Fri Sep 03 2021](https://github.com/Azure/azure-sdk-for-net-pr/issues/1451)

We have mistakenly added JSON as a `FormContentType` option, but it's not actually used by the service. JSON is only used when the input is a form URL:
https://github.com/Azure/azure-sdk-for-net-pr/blob/a497198e0b4c9beb568b19de16d019a14b64fabc/sdk/formrecognizer/Azure.AI.FormRecognizer/src/swagger/fr3.0.yml#L34-L41

We need to:
- Hide the JSON member in `FormContentType`.
- Add proper error handling in case someone tries to use it. Would it be a breaking change?

**Comment by pallavit** [comment]
@kinelski is this still a concern?

**Comment by kinelski** [comment]
We'll keep the same error behavior but we'll still hide it. There's no point in spending much time on this one since it only affects the old client and we never got feedback related to customers trying to use this member.
