### ISSUE TITLE
Design and implement DocumentFieldSchema

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24447]
@maririos commented on [Tue Aug 24 2021](https://github.com/Azure/azure-sdk-for-net-pr/issues/1432)

DocumentFieldSchema should we populate them? or should we hide it and provide a Json type property?

**Comment by kinelski** [comment]
All languages will be exposing it as an object. If customer need arises, we can always have a helper method or  to expose it as a JSON property.
