### ISSUE TITLE
[FormRecognizer] Should AnalyzeDocumentOptions.Locale be an (extensible) enum in the SDK?

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24450]
@kinelski commented on [Tue Sep 07 2021](https://github.com/Azure/azure-sdk-for-net-pr/issues/1454)

It's now modeled as a string, which differs from what we had in V2. We need to consider creating an (extensible?) enum in the SDK side to properly communicate to customers what are the accepted values. If kept as a string, we should link proper documentation to list all possibilities in the docstrings of the property.

**Comment by kinelski** [comment]
The SDK is just reflecting the behavior of the service swagger. V2 swagger had locale as an enum, while V3 has it as a string. We still need to link proper documentation to an exhaustive list of supported locales, but I'll remove the `blocking-release` tag.

**Comment by kinelski** [comment]
Since the main question of the issue has been answered, I'll close it and move documentation tracking to a new issue: https://github.com/Azure/azure-sdk-for-net/issues/30476
