### ISSUE TITLE
Expose the createdDateTime, lastUpdatedDateTime, or resourceLocationUrl on the BuildModelOperation class

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24467]
@maririos commented on [Thu Sep 16 2021](https://github.com/Azure/azure-sdk-for-net-pr/issues/1482)

does it not make sense in .NET to expose the createdDateTime, lastUpdatedDateTime, or resourceLocationUrl on the operation class?

_Originally posted by @kristapratico in https://github.com/Azure/azure-sdk-for-net-pr/pull/1481#r709663466_

**Comment by maririos** [comment]
We didn't do it in v2.1
Is there any value in exposing these properties?

**Comment by kinelski** [comment]
There's no clear motivation to do this in the LRO class. Users can get this data from the `GetOperation` API (which we call internally), so let's keep it as it is until have a clear demand from customers. Closing this.
