### ISSUE TITLE
[FormRecognizer] Add documentation link to AnalyzeDocument docstrings

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24462]
@kinelski commented on [Tue Sep 07 2021](https://github.com/Azure/azure-sdk-for-net-pr/issues/1458)

Location to change marked with comment "TODO: consider linking to document with prebuilt IDs when service goes public.". The list of prebuilt IDs will grow with time, so it would be helpful if we could add a link to documentation that lists all possibilities, instead of adding them manually in our docstrings.

Only possible when the service goes public.

---

@maririos commented on [Tue Oct 05 2021](https://github.com/Azure/azure-sdk-for-net-pr/issues/1458#issuecomment-934587053)

With the temporary aka.ms links this should be solved, right?

**Comment by kinelski** [comment]
> With the temporary aka.ms links this should be solved, right?

You're right. We have already addressed this. Closing the issue.
