### ISSUE TITLE
[FormRecognizer] Consider creating a BoundingPolygon type

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24472]
@kinelski commented on [Mon Sep 20 2021](https://github.com/Azure/azure-sdk-for-net-pr/issues/1495)

We may need to create a new type if the service decide to start supporting general polygons from now on.

**Comment by kinelski** [comment]
Already tracked by https://github.com/Azure/azure-sdk-for-net-pr/issues/1629.
