### ISSUE TITLE
Why is warning AZC0016 triggering?

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24478]
@maririos commented on [Tue Sep 28 2021](https://github.com/Azure/azure-sdk-for-net-pr/issues/1533)

We had to suppress AZC0016 // All parts of ServiceVersion members' names must begin with a number or uppercase letter and cannot have consecutive underscores in the `DocumentAnalysisClientOptions.ServiceVersion` in public repo, while it didn't in the private repo.
Two follow-ups:
- Are analyzers out of sync between repos?
- What is this warning about?

**Comment by kinelski** [comment]
Fixed by #29808.
