### ISSUE TITLE
Consider removing Cognitive Services from documentation

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24487]
It is part of the Applied AI effort.

**Comment by kinelski** [comment]
The relationship between the Form Recognizer service and the Cognitive Services still seems a bit vague. The service docs haven't been completely updated and Cognitive Services resources can still make use of Form Recognizer. All languages decided to keep documentation as it is for the time being, but this issue may be revisited later. Moving it to the backlog.
