### ISSUE TITLE
How should Pages parameter be exposed?

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24490]
FR V3.1.0 did it as a `List<string>` following some of .NET conventions.
We did ask the architects for feedback there, but the option of `string` was not contemplated.
The service is suggesting for us to expose it as `string` as they consider it will be easier for users to consume.

**Comment by kinelski** [comment]
As we received no negative feedback for this design while in V2, it's been decided that there's no good reason to change it. Closing this issue.
