### ISSUE TITLE
Build SDK quickstart tooling

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-net#24495]
Creating a tool based on templating and various input for service team, in order to create a perfectly viable project in one call. The only acceptable input is : a Swagger and a clone of the language repo.

For instance “dotnet new sdk swagger.json –name=MyServiceName” (dotnet is an example, pick what is idiomatic to your repo). This will create:
- A compilable/shippable package in the right folder
- A sample test (simple test with assert True)
- A sample of sample (placeholder for a sample)
- A basic Readme 
- Of course the LLC code 😊

Beware of the update scenario (package exists already): it maybe be necessary to make either the tooling smart, or to have second option like “dotnet update sdk swagger.json”.

**Comment by JoshLove-msft** [comment]
> > The general use case of creating a non-LLC library - rather than copying the Template folder, and modifying files by hand, we can have the same experience that we are aiming for with LLC for non-LLC libraries.
> 
> I think that would be nice to have, but I'm not sure we should make the LLC release dependent on it (as it is on this issue). Would you be willing to file a separate issue for this, @JoshLove-msft? I imagine we could retrofit this work to include HLC.

Sure, didn't mean to hijack this issue, but just to point out that it would be great to design in a way that can be extended to HLC.

**Comment by annelo-msft** [comment]
Yeah, I was thinking more about this, and to the extent that going forward (LLC + grow-up) = HLC, I think we're covered.  There's more work to do around automating the grow-up helpers as needed after plain LLC, but that should all be additive.
