### ISSUE TITLE
LLC Quickstart

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-for-net#24493]
Assuming a service team has (_and only that_):
- A Swagger with a Readme with input-file (I don't assume any autorest flags)
- Done a git clone of azure-sdk-for-net

We a want complete documentation on how this service team can:
- Generate runnable code with LLC
- Write tests
- Write samples
- Create packaging information to get a shippable package
- Write main Readme including quickstart

This issue is about documenting the current process today, not to make the process better. This should service teams oriented.

This page should be available from azure-sdk-for-net, Wiki or doc folder depending of the guidance on that repo.

**Comment by ShivangiReja** [comment]
Part-1 of this task is completed, which is adding template-LLC project that SDK developers can refer. Here is the template-LLC project - https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/template-LLC.

Next I'm working on adding LLC quick start guide.
