### ISSUE TITLE
Daily Docs: Do not process metadata for skipped docs

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#24518]
Ensure that docs.ms metadata steps are properly skipped in archetype-___-release.yml for release and daily docs metadata.

```yml
- ${{if ne(artifact.skipPublishDocMs, 'true')}}:
```

**Comment by kurtzeborn** [comment]
We actually added this to JS recently.  We didn't do it until we found situations where we actually need it.  It's done.
