### ISSUE TITLE
Whether to "break up" the omnibus begin_analyze_document into bespoke methods

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24549]
- Do we need 2 clients?

**Comment by kinelski** [comment]
We'll keep a single `StartAnalyzeDocument` method and make customers rely on service documentation to find the appropriate prebuilt model ID. The service expects to have tens of models in the future, so creating bespoke methods for each of them can strongly hinder discoverability. We could eventually add bespoke methods for the most common scenarios once we have enough feedback, but this would be an addictive change.
