### ISSUE TITLE
Storage Docs: Simple Bug

### ISSUE THREAD

**Issue by ak98** [Azure/azure-sdk-for-net#24541]
Azure.Storage.Cryptography.ClientSideEncryptor
Where found CryptoStreamMode.Read 

should be Write not Read

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by Karishma-Tiwari-MSFT** [comment]
@ak98 Can you please share the documentation url as well, where you are seeing this issue. Thanks.

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for bringing this to our attention. We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
