### ISSUE TITLE
[Storage] Why is LeaseAsync not publicly exposed on DataLakePathClient?

### ISSUE THREAD

**Issue by degant** [Azure/azure-sdk-for-net#24574]
**Query/Question**
Trying to use the lease capabilities on the Storage SDK and wondering why the [LeaseAsync](https://github.com/Azure/azure-sdk-for-net/blob/e4939957d675aa755795ac28afeae43714cc98d3/sdk/storage/Azure.Storage.Files.DataLake/src/Generated/PathRestClient.cs#L510) action isn't exposed on the public clients on the nuget? Or is there an alternate way to acquire leases using the SDK?

Also found a related issue around lease samples #9641 but couldn't figure out a way to use leases. Is there one?

**Environment:**
- Azure.Storage.Files.DataLake 12.8.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by KalyanChanumolu-MSFT** [comment]
@degant You can use [DataLakeLeaseClient.AcquireAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeleaseclient.acquireasync?view=azure-dotnet#Azure_Storage_Files_DataLake_DataLakeLeaseClient_AcquireAsync_System_TimeSpan_Azure_RequestConditions_System_Threading_CancellationToken_) method to acquire a lease.

You can refer to the tests [here](https://github.com/Azure/azure-sdk-for-net/blob/8555426d25f08cdbc254f8584f7115276bb74ac1/sdk/storage/Azure.Storage.Files.DataLake/tests/FileClientTests.cs#L2264) for help on implementation.
Please let us know if you face any issues.
