### ISSUE TITLE
[FEATURE REQ] Microsoft.Azure.Management.SecurityInsights Models with Id property have type string instead of ResourceId

### ISSUE THREAD

**Issue by MauRiEEZZZ** [Azure/azure-sdk-for-net#24586]
**Library or service name.**

Microsoft.Azure.Management.SecurityInsights
 
**Is your feature request related to a problem? Please describe.**

What feature would you like to get added? What problem is it solving?
While working with results from the API and SDK I have come across problem solving that should be needed for this to work easily.
For instance If I receive a result and I want to relate to its origin I could use the resource Id properties that are in the Id.
Example: `/subscriptions/<subscriptionId>/resourceGroups/<resourcegroup>/providers/Microsoft.OperationalInsights/workspaces/<the workspace name>/providers/Microsoft.SecurityInsights/Incidents/<incident ID>`

At this moment the Incident object in the SDK has type string for Id. 

As far as I know there isn't any function available in de SDK to get to one of each properties inside that.

In ARM I could use the function ResourceIdentifier to get a certain property, in my case I need workspace and resource group.

It would be nice if Id will become of type ResourceId and have these properties available.

edit: I have found examples in the Azure.ResourceManager namespace on how this is done over-there, just how I thought this could work.
https://docs.microsoft.com/en-us/dotnet/azure/sdk/resource-management#structured-resource-identifier
but that implementation doesn't include resource specific properties like workspaces and incidents.

edit2:
This is currently helping me out.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.core.resourceutils.getvaluefromidbyname?view=azure-dotnet

```
using Microsoft.Azure.Management.ResourceManager.Fluent.Core;

var idAsString = "/subscriptions/<subscriptionId>/resourceGroups/<resourcegroup>/providers/Microsoft.OperationalInsights/workspaces/<the workspace name>/providers/Microsoft.SecurityInsights/Incidents/<incident ID>";

var workspacesValue = ResourceUtils.GetValueFromIdByName(idAsString, "workspaces");

Console.WriteLine($"Workspaces={workspacesValue}");

// Returns:
// Workspaces=<the workspace name>
```

**Comment by Yao725** [comment]
For track 2 .Net mgmt. plane SDK which the package name begins with the prefix `Azure.ResourceManager`, the ResourceIdentifier definition has been moved to Azure.Core and shared by all the RP, so we just support to extract common information like `subscription` `resource group` from the Id.

**Comment by MauRiEEZZZ** [comment]
Ok thank you for clarifying. 

If no further actions will be made feel free to close this issue
