### ISSUE TITLE
Azure Form Recognizer pdf Train

### ISSUE THREAD

**Issue by ozgurgunyel** [Azure/azure-sdk-for-net#24584]
Hi,

I am trying to use Azure Form Recognizer within my project. I am creating modules by uploading 5 pdf documents from the user via https://fott-preview.azurewebsites.net. I could not find a sample code where I can give the module creation process to the user. I will be glad if you can help.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
