### ISSUE TITLE
[BUG] Can't list event subscriptions using Event Grid Domain Topics

### ISSUE THREAD

**Issue by brennfoster** [Azure/azure-sdk-for-net#24601]
**Describe the bug**
Can't query list of event subscriptions when using Event Grid Domain Topics.

**Expected behavior**
Listing all event grid subscription by resource group or location should list all event subscriptions.

**Actual behavior (include Exception or Stack Trace)**
It does not return a list of event subscription unless I filter by event grid domain topic.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

az eventgrid event-subscription list --resource-group {resource-group-name} => return empty list
az eventgrid event-subscription list --location centralus => returns empty list
az eventgrid event-subscription list --source-resource-id /subscriptions/{subscription-id}/resourceGroups/{resource-group-name}/providers/Microsoft.EventGrid/domains/{eventgrid-domain} => returns empty list

This is the only command that will return a list of event subscriptions using Event Grid Domain:
az eventgrid event-subscription list --source-resource-id /subscriptions/{subscription-id}/resourceGroups/{resource-group-name}/providers/Microsoft.EventGrid/domains/{eventgrid-domain}/topics/{topic-name} => returns correct list of event subscriptions

**Environment:**
 - Microsoft.Azure.Management.EventGrid 6.0.0
 - .NET 5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
@brennfoster Is this an issue for [Azure CLI](https://github.com/Azure/azure-cli)? I don't see .NET SDK related code in the steps to reproduce.

**Comment by fengzhou-msft** [comment]
@brennfoster we have deprecated the track 1 SDK `Microsoft.Azure.Management.EventGrid` and released track 2 SDK `Azure.ResourceManager.EventGrid 1.0.0`. I tested below code with track 2 and it can return the event subscriptions list without using a filter.

``` C#
            // get your azure access token, for more details of how Azure SDK get your access token, please refer to https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication?tabs=command-line
            TokenCredential cred = new DefaultAzureCredential();
            // authenticate your client
            ArmClient client = new ArmClient(cred, "{subscription-id}");

            string rgName = "myrg";
            ResourceGroupResource resourceGroup = await client.GetDefaultSubscription().GetResourceGroupAsync(rgName);
            var eventSubs = resourceGroup.GetRegionalEventSubscriptionsDataAsync(AzureLocation.WestUS);
            await foreach(EventGridSubscriptionData eventSub in eventSubs)
            {
                // do stuff with the Event Subscription
                Console.WriteLine(eventSub.Name);
            }
```
