### ISSUE TITLE
Unable to cast COM object of type 'System.__ComObject' to interface type 'EnvDTE.Project'

### ISSUE THREAD

**Issue by kasunkv** [Azure/azure-sdk-for-net#2460]
am in the process of creating Azure Resource Manager deployment templates for my project using the Azure Resource Group Project in Visual Studio 2015 project templates. I successfully managed to create the projects before. But today, I updated the Azure SDK to v2.9.5 and suddenly the project creation failed. It failed with the following error message.

> Unable to cast COM object of type 'System.__ComObject' to interface type 'EnvDTE.Project'. This operation failed because the QueryInterface call on the COM component for the interface with IID '866311E6-C887-9833-645F5B93F6F1}' failed due to the following error: No cush interface supported (Exception from HRESULT: 0x80004002 (E_NONINTERFACE)).

This exception happens when i select starting template from the template selection dialog box (I selected WebApp+SQL template. This fails for other templates as well). So after this the project is incomplete created.

I faced this same issue in 3 different PCs with Azure SDK v2.9.5 installed. It seems to me that this is related to the SDK. is this a known issue? If not how should i fix this.

**Comment by markcowl** [comment]
@kasunkv This repository is for the azure management libraries.  Please raise this question through the Azure forum or other Azure support channels.

**Comment by naeemsarfraz** [comment]
@kasunkv did you find a solution to this? I'm facing the same issue.

There's not an obvious Azure forum to post this in.

**Comment by kasunkv** [comment]
@naeemsarfraz Actually no. the issue still exists. What i did was manually create the missing project files and continued from there. For me project was partially created and template and parameter json files were missing while Powershell deployment script was created.

**Comment by kasunkv** [comment]
@naeemsarfraz  Also, got a reply to my stackoverflow question here. Seems like they know about the issue and they are working on a fix. Good news.. :)
[](http://stackoverflow.com/questions/40006255/unable-to-cast-com-object-of-type-system-comobject-to-interface-type-envdte/40226793#40226793)

**Comment by naeemsarfraz** [comment]
@kasunkv fanstatic, thanks!
