### ISSUE TITLE
[FEATURE REQ] Move KeyVault secret Models to new Azure.Security.KeyVault.Secrets package

### ISSUE THREAD

**Issue by matt-psaltis** [Azure/azure-sdk-for-net#24617]
The deprecated package contains model classes like SecretItem.

There doesn't seem to be equivalent models in the new replacement packages:
Azure.Security.KeyVault.Secrets
Azure.Security.KeyVault.Keys
Azure.Security.KeyVault.Certificates

Additionally, these models use Json.Net so could these also be transitioned to System.Text.Json?

I'm specifically trying to serialize these models from a Server side perspective so I would like to have the models correctly serialize to match the Response structure as defined here: https://docs.microsoft.com/en-us/rest/api/keyvault/get-secrets/get-secrets#examples

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
`SecretItem` and `SecretBundle` were renamed to `KeyVaultSecret`. Please see our migration guides (e.g. https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/MigrationGuide.md - all next to the packages' README.md files).

We didn't support serialization to/from the old models directly before. If you're using the SDKs, is there some reason you're trying to de/serialize the models yourself? The SDKs take care of that directly, as did the previous ones.

**Comment by matt-psaltis** [comment]
I think I understand the confusion now. When I say server side perspective I'm trying to describe a KeyVault emulator. I'm trying to create something similar to the Azure Storage Emulator for Azure KeyVault. This means I'm focusing on producing the same HTTP responses that the KeyVault servers in Azure would produce. This is to build a like for like emulator that the Client SDK can connect to for disconnected development scenarios where access to Azure is not possible.

So, in the asp.net controllers I build up SecretItems etc and then pass them through the serialization process which produces the same HTTP responses that the KeyVault server would produce. The new Client SDK does not seem to offer a set of models that reproduce this same behaviour. Does that help at all?

**Comment by matt-psaltis** [comment]
Thanks @heaths
