### ISSUE TITLE
[Synapse] TestSparkSessionJobWithPublicConstructor failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#24610]
Synapse runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 400 (Bad Request)
> 
> Content:
> {"TraceId":"06a37920-c921-433e-8c13-df8854cb01ef | client-request-id : 8a70f86e-a252-4b3c-8be0-82f7e2704a70","Message":"Spark Compute not Found"}
> 
> Headers:
> Cache-Control: no-store, no-cache
> Pragma: no-cache
> Transfer-Encoding: chunked
> Server: Kestrel,Microsoft-HTTPAPI/2.0
> Strict-Transport-Security: REDACTED
> x-ms-response-time-ms: REDACTED
> x-ms-activity-id: REDACTED
> x-ms-client-request-id: 8a70f86e-a252-4b3c-8be0-82f7e2704a70,8a70f86e-a252-4b3c-8be0-82f7e2704a70
> x-ms-request-id: 4c8f5dc4-b675-45bb-8d43-0bc278026666
> Date: Fri, 01 Oct 2021 19:33:07 GMT
> Content-Type: application/json
> Expires: -1
> 
> 
> Stack trace
>    at Azure.Analytics.Synapse.Spark.SparkSessionRestClient.CreateSparkSessionAsync(SparkSessionOptions sparkSessionOptions, Nullable`1 detailed, CancellationToken cancellationToken) in /_/sdk/synapse/Azure.Analytics.Synapse.Spark/src/Generated/SparkSessionRestClient.cs:line 173
>    at Azure.Analytics.Synapse.Spark.SparkSessionClient.StartCreateSparkSessionInternal(Boolean async, SparkSessionOptions sparkSessionOptions, Nullable`1 detailed, CancellationToken cancellationToken) in /_/sdk/synapse/Azure.Analytics.Synapse.Spark/src/Customization/SparkSessionClient.cs:line 34
>    at Azure.Analytics.Synapse.Spark.SparkSessionClient.StartCreateSparkSessionAsync(SparkSessionOptions sparkSessionOptions, Nullable`1 detailed, CancellationToken cancellationToken) in /_/sdk/synapse/Azure.Analytics.Synapse.Spark/src/Customization/SparkSessionClient.cs:line 20
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.InstrumentResultInterceptor.InstrumentOperationInterceptor[T](IInvocation invocation, Func`1 innerTask) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/InstrumentResultInterceptor.cs:line 70
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 165
>    at Azure.Analytics.Synapse.Spark.Tests.SparkSessionClientLiveTests.TestSparkSessionJobWithPublicConstructor() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Spark/tests/SparkSessionClientLiveTests.cs:line 110
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1123977&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Closing as stale
