### ISSUE TITLE
Azure.Analytics.Synapse.Artifacts - Client classes should have public getter for endpoint Uri

### ISSUE THREAD

**Issue by mciancia8** [Azure/azure-sdk-for-net#24634]
**Library or service name.**
Azure.Analytics.Synapse.Artifacts
 
**Is your feature request related to a problem? Please describe.**

I have used a few Client classes from different libraries and all the ones I have used so far always have a property that exposes a public getter for the endpoint Uri. I find this useful during troubleshooting and for logging. I am currently trying to use the following two pipeline clients from this library and noticed that it didn't have it available:
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/PipelineRunClient.cs
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/PipelineClient.cs

I realize I could work my way through the private variables during debug mode to get it, but having it right on the client class has proven useful to me. 

Example of clients that expose a getter for it.: 
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/SecretClient.cs
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobLeaseClient.cs
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Queues/src/QueueClient.cs

So my feature request is to follow the same pattern and have a public getter for the endpoint Uri.

**Comment by Karishma-Tiwari-MSFT** [comment]
I have reached out to the internal teams to get more information on this.

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for bringing this to our attention. We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
