### ISSUE TITLE
The class BillingClient doesn't exist

### ISSUE THREAD

**Issue by metoule** [Azure/azure-sdk-for-net#24638]
I'm using version [Microsoft.Azure.Management.Billing 4.1.0](https://www.nuget.org/packages/Microsoft.Azure.Management.Billing), and the class `BillingClient` doesn't exist. I managed to use `BillingManagementClient` instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5822f8b9-7782-88c0-ea92-876eadac5e1e
* Version Independent ID: 7a5d1169-d674-1a57-a8c1-07fff302b5af
* Content: [Azure Billing libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/billing?view=azure-dotnet)
* Content Source: [api/overview/azure/billing.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/billing.md)
* Service: **billing**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@xboxeer for awareness about outdated docs.

**Comment by metoule** [comment]
It's fine, the package is now obsolete, and the doc no longer exists.
