### ISSUE TITLE
Complex Schedule not executing correctly

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-sdk-for-net#2463]
I Have a job that i want to run every hour. Using the C# Scheduler SDK I created a schedule that looks like the following

``` json
{
    "Count": null,
    "EndTime": null,
    "Frequency": 2,
    "Interval": null,
    "Schedule": {
        "Days": null,
        "Hours": null,
        "Minutes": [0],
        "MonthDays": null,
        "MonthlyOccurrences": null,
        "Months": null
    }
}
```

According the documentation this schedule should run every hour on the hour ([see {minutes:[0]}](https://azure.microsoft.com/en-us/documentation/articles/scheduler-advanced-complexity/#examples-recurrence-schedules))

But in Azure, the schedule is actually only executing once a day. The execution date was 11 October 2016. As you can see the next run was scheduled for the next day instead of the next hour - see image below.
![947245](https://cloud.githubusercontent.com/assets/8879065/19339447/b48e0156-9123-11e6-8953-098b95394114.png)

Is this a bug?

Note: I specify the hours in the schedule it seems to work.

``` json
{
    "Count": null,
    "EndTime": null,
    "Frequency": 2,
    "Interval": null,
    "Schedule": {
        "Days": null,
        "Hours": [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23],
        "Minutes": [0],
        "MonthDays": null,
        "MonthlyOccurrences": null,
        "Months": null
    }
}
```

**Comment by markcowl** [comment]
@aaronroney Please identify an appropriate assigneee for this issue

**Comment by aaronroney** [comment]
Adding @kithrik for visibility.

**Comment by twitchax** [comment]
@gorillapower, this does not appear to be a bug.  Have you tried specifying frequency as a string (source: https://docs.microsoft.com/en-us/azure/scheduler/scheduler-advanced-complexity#how-to-use-json-and-rest-api-for-creating-schedules)?

```json
{
    "count": null,
    "endTime": null,
    "frequency": "week",
    "interval": null,
    "schedule": {
        "days": null,
        "hours": null,
        "minutes": [0],
        "monthDays": null,
        "monthlyOccurrences": null,
        "months": null
    }
}
```

**Comment by gorillapower** [comment]
@twitchax thanks for the feedback. Yes apologies, that json was a serialization of the scheduler C# object as i was using the Scheduler SDK Library. I have since managed to get the json of the actual http request.

What im trying to replicate is the behaviour described in the documentation
![image](https://cloud.githubusercontent.com/assets/8879065/20957205/050f6e36-bc57-11e6-9c76-9ceb3bf8548c.png)

Here is the JSON that actually sent to the API,
```
"recurrence": {
	"frequency": "day",
	"interval": 1,
	"schedule": {
		"minutes": [15]
	}
}
```

and the result is below - schedule runs every day 15 minutes pass the start time. Am I missing something? Bearing in mind the frequency cant be hourly in this case.
![image](https://cloud.githubusercontent.com/assets/8879065/20957277/82057c28-bc57-11e6-817b-46c1cd333f41.png)

**Comment by twitchax** [comment]
You can specify the start time to XX:15, and change "recur every" to "1 Hours".

![image](https://cloud.githubusercontent.com/assets/549523/20957633/d3510fa4-bc05-11e6-99b4-5fc10a0f4b52.png)

**Comment by gorillapower** [comment]
Ok so the only way is to remove the advanced schedule and run it on a frequency of an hour? 

Is it possible to have schedule that runs 15 and 30 minutes past every hour? 

I think the documentation is misleading as this cant be done how it is described. Instead you either have to implement your solution above or include every hour 0,1,2,3...23 and run the schedule daily.

**Comment by twitchax** [comment]
Unfortunately, I think you have to enter every hour.  However, this issue would be better suited to the Scheduler team, so I can pass it along to them.

**Comment by twitchax** [comment]
Clearing assignees so the Scheduler team can pick this up.

**Comment by adrianhall** [comment]
My apologies for the drop on this one.  Is this still an issue?
