### ISSUE TITLE
Link errors to other identity resources

### ISSUE THREAD

**Issue by x509cert** [Azure/azure-sdk-for-net#24641]
At the bottom of the page, there're links to other resources, but they are all marked TBD

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70aa5df3-f8d8-ab95-3ff7-6cd845e37a71
* Version Independent ID: 129495bd-520a-d051-564e-fb6817bdd1a2
* Content: [Microsoft.Azure.Management.Authorization Namespace - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.authorization?view=azure-dotnet)
* Content Source: [xml/ns-Microsoft.Azure.Management.Authorization.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.Azure.Management.Authorization.xml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ArthurMa1978** [comment]
it has been fixed by docs team
