### ISSUE TITLE
It will take 10 minutes when a loop occurs for the number of cases set in PrefetchCount.

### ISSUE THREAD

**Issue by ryo-0813** [Azure/azure-sdk-for-net#24655]
.NET SDK (Microsoft.Azure.ServiceBus) to receive messages from Azure Service Bus Topic.
I have confirmed that the "subscriptionReceiver.PrefetchCount" property described in the following program takes 10 minutes when a loop occurs for the set number of cases.

・Program
=============================
         try
            {

                subscriptionReceiver = new MessageReceiver(SbusConnectionString, subscriptionPath, ReceiveMode.PeekLock);
                Console.WriteLine($"[{DateTime.Now:O}] Start Receive");

                // Set Prefetch
                subscriptionReceiver.PrefetchCount = 6;
=============================

・Explained as an example based on the information displayed in the console
=========
Msg 1 : [2021-08-10T14:13:37.4642259+09:00] Start Receive
Msg 2 : [2021-08-10T14:13:40.1724492+09:00] Received
Msg 3 : [2021-08-10T14:13:41.7225299+09:00] Received
Msg 4 : [2021-08-10T14:13:43.2456619+09:00] Received
Msg 5 : [2021-08-10T14:13:44.7809022+09:00] Received
Msg 6 : [2021-08-10T14:13:46.3156828+09:00] Received
Msg 7 : [2021-08-10T14:23:43.5556342+09:00] Received
Msg 8 : [2021-08-10T14:23:45.0974040+09:00] Received
Msg 9 : [2021-08-10T14:23:46.6341618+09:00] Received
Msg 10 : [2021-08-10T14:23:48.1605786+09:00] Received
Msg 11 : [2021-08-10T14:23:49.6840978+09:00] Received
Msg 12 : [2021-08-10T14:33:47.1229598+09:00] Received
Msg 13 : [2021-08-10T14:33:48.6569753+09:00] Received
Msg 14 : [2021-08-10T14:33:50.1803312+09:00] Received
Msg 15 : [2021-08-10T14:33:51.8161747+09:00] Received
Msg 16 : [2021-08-10T14:33:53.3440673+09:00] Received
=========

Based on the above, I believe that "subscriptionReceiver.PrefetchCount" has the following behavior.
・After fetching the number of messages specified in PrefetchCount, when fetching messages in the next loop (for the next number of messages specified in PrefetchCount), the operation is to re-receive messages from the local buffer in order to fetch them again at the same time, which takes 10 minutes. 

I would like to confirm the following points regarding "subscriptionReceiver.PrefetchCount".

【Question】
1. Whether or not it is a specification that it takes 10 minutes when "subscriptionReceiver.PrefetchCount" is set.
2. If it is not a specification, it may not meet the requirement to take 10 minutes when setting "subscriptionReceiver.PrefetchCount", I would appreciate it if you would consider modifying it to improve its functionality.

**Comment by yvgopal** [comment]
I don't really understand what you mean by re-receive or next loop. Could you elaborate?

To answer your questions..
1. It shouldn't take 10 minutes. I don't even know how you arrived at that 10 minute number.
2. No need of any modification.

**Comment by Karishma-Tiwari-MSFT** [comment]
@ryo-0813 Checking in if you get a chance to look at the comment above and were able to resolve it? Let me know. Thanks.

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for bringing this to our attention. We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
