### ISSUE TITLE
[QUERY] using Microsoft.Azure.Management.Support for CSP 

### ISSUE THREAD

**Issue by mesgar** [Azure/azure-sdk-for-net#24662]
８**Query/Question**
We're a CSP and we've 300 customers. We want to use API to create SR.
As far as we know we need two tokens (Primary and Auxiliary).
Do we need to register an enterprise app in 300 tenants(subscriptions)?
How do we acquire these tokens and how do we pass them to MicrosoftSupportClient.
We've tried the code below but we got  Operation returned an invalid status code 'Unauthorized' exception.

```csharp
AuthenticationResult authenticationResult = await GetATokenForGraph();
if (authenticationResult != null)
{
     auxiliaryAccessToken = authenticationResult.AccessToken;
}
ServiceClientCredentials serviceClientCreds = new CustomServiceClientCredentials(this.accessToken, auxiliaryAccessToken, "Bearer");

using (var client = new MicrosoftSupportClient(serviceClientCreds, httpClient, false))
{
     var servicesList = client.Services.List(); // raises an 'Unauthorized' exception
}
```

**UPDATE**
If I acquire a token from cloud-shell (az account get-access-token) in customers tenant, and set it for both Primary and Auxiliary tokens,
I get this error:
'Failed'. Additional Info:'Your support plan type is CSP. To create and update support tickets, and add communication operations, you need access to our high tier-support plans. Learn more at https://aka.ms/supportapi'

Well, this make sense. Customers will get the same error when they want to raise a ticket themselves.

If I sign-in to customers Azure portal using my CSP account and then acquire a token and use it for both Primary and Auxiliary tokens,
I get this error:
Operation returned an invalid status code 'Forbidden'

If I use both of them  I get "Unauthorized" error.
Now, How exactly I should acquire those tokens while the documents says _**all tokens must be from the same user**_.
Document: 
“In the code of your multi-tenant app, get the authentication token for other tenants and store them in the auxiliary headers. All the tokens must be from the same user or application. The user or application **must have been invited as a guest to the other tenants**.”

I don't understand why should I add CSP account as a guest user to customers tenants.

**Comment by archerzz** [comment]
This is about authorization requirement for CSP, better to let service team to answer.

But, @mesgar have you met all the prerequisites mentioned [here](https://docs.microsoft.com/en-us/rest/api/support/#prerequisites)?

**Comment by mesgar** [comment]
Hi @archerzz 

Well, I was already gave up.
Since the prerequisites says we have to buy extra support for each CSP tenant.
We do need to buy extra support when we use web system for SR but we need extra support for each tenant when using API. 
Is this a bug or something?
Since we already bought "Microsoft Premier Support for Enterprise" the API should be usable without extra fee for support just like the web system in Azure portal.
I don't know what happens with Microsoft Unified Support and CSP.
 
About the issue itself, I think there's a bug when using SDK.
I could send a request via postman but couldn't get it down with the SDK.

Regards
