### ISSUE TITLE
[BUG] .NET Azure.AI.FormRecognizer operation StartRecognizeIdentityDocumentsFromUri doesn't return categorized results

### ISSUE THREAD

**Issue by TPullen21** [Azure/azure-sdk-for-net#24666]
**Describe the bug**
Please provide the description of issue you're seeing.

When using the .NET package Azure.AI.FormRecognizer and using the `StartRecognizeIdentityDocumentsFromUri`/`StartRecognizeIdentityDocumentsFromUriAsync` methods on the `FormRecognizerClient` class, it doesn't return the results in the categorized format.

**Expected behavior**
What is the expected behavior?

Results are returned in the categorized format, i.e. with ID specific fields including "CountryRegion", "DateOfBirth", "DateOfExpiration", "DocumentNumber".

![image](https://user-images.githubusercontent.com/9089180/136978238-2683782c-8053-4755-b1a4-a45ead8831fb.png)

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

It only returns the `MachineReadableZone` field.

![image](https://user-images.githubusercontent.com/9089180/136978729-a462e42e-7588-464c-8c30-37893854fe5e.png)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Follow the documentation here: https://docs.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/quickstarts/try-sdk-rest-api?pivots=programming-language-csharp#analyze-id-documents
2. Fields are not returned as expected from the documentation. The categorized fields are correctly returned with the same ID document when using other programming languages, for example REST.

**Environment:**
- .NET Azure.AI.FormRecognizer 3.1.1
 - Windows 10 .NET Core 3.1
 - Visual Studio 16.10.2

**Comment by cristian9804** [comment]
I am having the same issue

**Comment by maririos** [comment]
@TPullen21 unfortunately I can't access the input file anymore, but looking at the REST output you are providing, it looks like all the fields are under the `MachineReadableZone` field. 
You will need to do something like:
```
RecognizedForm identityDocument = identityDocuments.Single();

if (identityDocument.Fields.TryGetValue("MachineReadableZone", out FormField machineRZField)) {
  if (machineRZField.Value.ValueType == FieldValueType.Dictionary) {
    
    var machineRZ= machineRZField.Value.AsDictionary();
    
    if (machineRZ.Fields.TryGetValue("Address", out FormField addressField)) {
      if (addressField.Value.ValueType == FieldValueType.String) {
        string address = addressField.Value.AsString();
        Console.WriteLine($ "Address: '{address}', with confidence {addressField.Confidence}");
      }
    }
    .....
  }
}
```

Lastly, @TPullen21 I want to confirm that if you follow the [sample ](https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.FormRecognizer_3.1.1/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/Sample11_RecognizeIdentityDocuments.md)in our .NET repo you get the information you are expecting. 

Note that the discrepancy is because of what the service is returning.

@vkurpad and @laujan looks like the input documents used here https://docs.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/how-to-guides/try-sdk-rest-api?pivots=programming-language-csharp#get-assets-for-testing are no longer available? or there were some renames made that will require the documentation to be updated.

Also, as the user is pointing out, the service is returning a different output than expected, so the code sample needs to be updated too.

**Comment by TPullen21** [comment]
@maririos thank you for getting back to me. With a few tweaks to your code it seems to be working correctly now.

Here is the a copy of my working code:

```
RecognizedForm identityDocument = documents.Single();

if (identityDocument.Fields.TryGetValue("MachineReadableZone", out FormField machineRZField))
{
    if (machineRZField.Value.ValueType == FieldValueType.Dictionary)
    {

        var machineRZ = machineRZField.Value.AsDictionary();

        if (machineRZ.TryGetValue("Sex", out FormField addressField))
        {
            if (addressField.Value.ValueType == FieldValueType.String)
            {
                string sex = addressField.Value.AsString();
                Console.WriteLine($"Sex: '{sex}', with confidence {addressField.Confidence}");
            }
        }

        if (machineRZ.TryGetValue("CountryRegion", out FormField countryRegionField))
        {
            if (countryRegionField.Value.ValueType == FieldValueType.CountryRegion)
            {
                string countryRegion = countryRegionField.Value.AsCountryRegion();
                Console.WriteLine($"CountryRegion: '{countryRegion}', with confidence {countryRegionField.Confidence}");
            }
        }

        if (machineRZ.TryGetValue("DateOfBirth", out FormField dateOfBirthField))
        {
            if (dateOfBirthField.Value.ValueType == FieldValueType.Date)
            {
                DateTime dateOfBirth = dateOfBirthField.Value.AsDate();
                Console.WriteLine($"Date Of Birth: '{dateOfBirth}', with confidence {dateOfBirthField.Confidence}");
            }
        }

        if (machineRZ.TryGetValue("DateOfExpiration", out FormField dateOfExpirationField))
        {
            if (dateOfExpirationField.Value.ValueType == FieldValueType.Date)
            {
                DateTime dateOfExpiration = dateOfExpirationField.Value.AsDate();
                Console.WriteLine($"Date Of Expiration: '{dateOfExpiration}', with confidence {dateOfExpirationField.Confidence}");
            }
        }

        if (machineRZ.TryGetValue("DocumentNumber", out FormField documentNumberField))
        {
            if (documentNumberField.Value.ValueType == FieldValueType.String)
            {
                string documentNumber = documentNumberField.Value.AsString();
                Console.WriteLine($"Document Number: '{documentNumber}', with confidence {documentNumberField.Confidence}");
            }
        }

        if (machineRZ.TryGetValue("FirstName", out FormField firstNameField))
        {
            if (firstNameField.Value.ValueType == FieldValueType.String)
            {
                string firstName = firstNameField.Value.AsString();
                Console.WriteLine($"First Name: '{firstName}', with confidence {firstNameField.Confidence}");
            }
        }

        if (machineRZ.TryGetValue("LastName", out FormField lastNameField))
        {
            if (lastNameField.Value.ValueType == FieldValueType.String)
            {
                string lastName = lastNameField.Value.AsString();
                Console.WriteLine($"Last Name: '{lastName}', with confidence {lastNameField.Confidence}");
            }
        }

        if (machineRZ.TryGetValue("Nationality", out FormField regionfield))
        {
            if (regionfield.Value.ValueType == FieldValueType.CountryRegion)
            {
                string nationality = regionfield.Value.AsCountryRegion();
                Console.WriteLine($"Nationality: '{nationality}', with confidence {regionfield.Confidence}");
            }
        }
    }
}
```

**Comment by ibrahimalgodocs** [comment]
This issue was opened on October 12, 2021 and the problem still exists in the latest API. The only resolution is the suggestion from @TPullen21. However, I expect the normal behavior, i.e. not retrieving those fields from the `MachineReadableZone` field.
Is there anyone taking care of the documentation?
