### ISSUE TITLE
[Synapse][Core] Investigate performance of LLC-recommended approach to deserializing to JSON

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#24671]
`using var doc = JsonDocument.Parse(response.Content.ToMemory());`

Per @KrzysztofCwalina:
> In particular I wonder if response.Content.ToMemory() or response.ContentStream or a new API on response would be the best way to parse the JSON. Ultimately we have this JSON in an Array (deep in our code). The most efficient way to parse JSON is to pass the array directly to the parser. And we'll want to know if Content.ToMemory simply wraps the array or goes though some overhead.

**Comment by AlexanderSher** [comment]
`System.BinaryData` stores stream as [`ReadOnlyMemory<byte>`](https://github.com/dotnet/runtime/blob/477789e70e5d179cf6789fa51f2e2fcc3ea2dddd/src/libraries/System.Memory.Data/src/System/BinaryData.cs#L24), so `response.Content.ToMemory()` has zero overhead - it simply returns private field.

[`JsonDocument.Parse`](https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.Parse.cs#L42) calls its [private overload](https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.Parse.cs#L538) which instantiates 2 structs and passes them to the [actual implementation](https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs#L927), which consumes memory to store data about tokens. 

The `JsonDocument` itself may allocate a string in [`GetString`](https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs#L279). However, it looks like [`JsonDocument.NameEquals`](https://github.com/dotnet/runtime/blob/release/5.0/src/libraries/System.Text.Json/src/System/Text/Json/Document/JsonDocument.cs#L287) doesn't allocate any strings.

**Comment by chunyu3** [comment]
For simple model someModel {
  Guid ID,
 string Description,
int Count,
}

![image](https://user-images.githubusercontent.com/10458143/141939669-43c6f352-0f83-47bb-92d8-9affe7e247c3.png)

**Comment by chunyu3** [comment]
Bechmark Result for one complex model
![image](https://user-images.githubusercontent.com/10458143/141947280-47f44db9-69b2-4d42-b8c0-e6224a0632d3.png)


![image](https://user-images.githubusercontent.com/10458143/141947039-ace29f08-1997-4f89-96aa-9a822621a2a3.png)

**Comment by chunyu3** [comment]
UseTryGetProperty cost lest time and allocated less memory.

**Comment by KrzysztofCwalina** [comment]
One of the approaches I thought would be good to investigate was to use Utf8JsonReader. I suspect it will be the fastest (significantly) and the question is whether the code we would have to generate would be too complex.

**Comment by AlexanderSher** [comment]
For this json object
```json
{
  "clusterSize": 1000,
  "timeToLive": "2012-03-19T07:22Z",
  "version": 2,
  "linkedServiceName": "ServiceName",
  "hostSubscriptionId": "a9442c29-5014-4185-9ea7-c8082445bd36",
  "servicePrincipalId": "e639e549-4ea5-4df2-852c-60a603ff8ed7",
  "servicePrincipalKey": "d3bcc406-4cb8-4bae-9a0a-ca2ee9c526b9",
  "tenant": "300dd17d-ddee-4973-8f07-f379cb144643",
  "clusterResourceGroup": "GroupName",
  "clusterNamePrefix": "Prefix",
  "clusterUserName": "User",
  "clusterPassword": "1050dcab-11ce-4a12-af2e-a8d17f7b06dd",
  "clusterSshUserName": "user",
  "clusterSshPassword": "c6c8f672-d511-4c65-8fea-5ac3f4a1eea4"
}
```

I've got the following results:
```
|               Method |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
|--------------------- |---------:|----------:|----------:|-------:|----------:|
|         JsonDocument | 4.071 us | 0.0796 us | 0.0917 us | 0.1945 |     816 B |
| JsonDocumentReversed | 4.001 us | 0.0454 us | 0.0379 us | 0.1945 |     816 B |
|       Utf8JsonReader | 4.195 us | 0.0818 us | 0.0875 us | 0.1678 |     728 B |
```

So no, `Utf8JsonReader` isn't the fastest, it is very close to the `JsonDocument` and has just small memory allocation benefit. I'd expect @chunyu3 would have the same results in her tests. 

Code, however, is significantly worse. This is `JsonDocument`:
```cs
using var doc = System.Text.Json.JsonDocument.Parse(_inputMemory);
var root = doc.RootElement;
return new SomeModel(
    root.TryGetProperty("clusterSize", out var property) ? property.GetInt32() : throw new ArgumentOutOfRangeException(nameof(SomeModel.ClusterSize)),
    root.TryGetProperty("timeToLive", out property) ? property.GetDateTimeOffset() : throw new ArgumentNullException(nameof(SomeModel.TimeToLive)),
    root.TryGetProperty("version", out property) ? property.GetDouble() : throw new ArgumentOutOfRangeException(nameof(SomeModel.Version)),
    root.TryGetProperty("linkedServiceName", out property) ? property.GetString() : throw new ArgumentNullException(nameof(SomeModel.LinkedServiceName)),
    root.TryGetProperty("hostSubscriptionId", out property) ? property.GetGuid() : Guid.Empty,
    root.TryGetProperty("servicePrincipalId", out property) ? property.GetGuid() : Guid.Empty,
    root.TryGetProperty("servicePrincipalKey", out property) ? property.GetString() : null,
    root.TryGetProperty("tenant", out property) ? property.GetString() : null,
    root.TryGetProperty("clusterResourceGroup", out property) ? property.GetString() : null,
    root.TryGetProperty("clusterNamePrefix", out property) ? property.GetString() : null,
    root.TryGetProperty("clusterUserName", out property) ? property.GetString() : null,
    root.TryGetProperty("clusterPassword", out property) ? property.GetString() : null,
    root.TryGetProperty("clusterSshUserName", out property) ? property.GetString() : null,
    root.TryGetProperty("clusterSshPassword", out property) ? property.GetString() : null
);
```

and this is `Utf8JsonReader`:
```cs
var reader = new Utf8JsonReader(_inputMemory.Span);

int clusterSize = 0;
DateTimeOffset timeToLive = default;
double version = 0; 
string linkedServiceName = null; 
Guid hostSubscriptionId = Guid.Empty; 
Guid servicePrincipalId = Guid.Empty; 
string servicePrincipalKey = null; 
string tenant = null; 
string clusterResourceGroup = null; 
string clusterNamePrefix = null; 
string clusterUserName = null; 
string clusterPassword = null; 
string clusterSshUserName = null;
string clusterSshPassword = null;

while (reader.Read())
{
    switch (reader.TokenType)
    {
        case JsonTokenType.PropertyName:
            if (reader.ValueTextEquals("clusterSize"))
            {
                reader.Read();
                clusterSize = reader.GetInt32();
            }
            else if (reader.ValueTextEquals("timeToLive"))
            {
                reader.Read();
                timeToLive = reader.GetDateTimeOffset();
            }
            else if (reader.ValueTextEquals("version"))
            {
                reader.Read();
                version = reader.GetDouble();
            }
            else if (reader.ValueTextEquals("linkedServiceName"))
            {
                reader.Read();
                linkedServiceName = reader.GetString();
            }
            else if (reader.ValueTextEquals("hostSubscriptionId"))
            {
                reader.Read();
                hostSubscriptionId = reader.GetGuid();
            }
            else if (reader.ValueTextEquals("servicePrincipalId"))
            {
                reader.Read();
                servicePrincipalId = reader.GetGuid();
            }
            else if (reader.ValueTextEquals("servicePrincipalKey"))
            {
                reader.Read();
                servicePrincipalKey = reader.GetString();
            }
            else if (reader.ValueTextEquals("tenant"))
            {
                reader.Read();
                tenant = reader.GetString();
            }
            else if (reader.ValueTextEquals("clusterResourceGroup"))
            {
                reader.Read();
                clusterResourceGroup = reader.GetString();
            }
            else if (reader.ValueTextEquals("clusterNamePrefix"))
            {
                reader.Read();
                clusterNamePrefix = reader.GetString();
            }
            else if (reader.ValueTextEquals("clusterUserName"))
            {
                reader.Read();
                clusterUserName = reader.GetString();
            }
            else if (reader.ValueTextEquals("clusterPassword"))
            {
                reader.Read();
                clusterPassword = reader.GetString();
            }
            else if (reader.ValueTextEquals("clusterSshUserName"))
            {
                reader.Read();
                clusterSshUserName = reader.GetString();
            }
            else if (reader.ValueTextEquals("clusterSshPassword"))
            {
                reader.Read();
                clusterSshPassword = reader.GetString();
            }
            break;
        case JsonTokenType.StartObject:
        case JsonTokenType.EndObject:
            break;
        default:
            throw new InvalidOperationException("Unexpected Token");
    }
}

if (clusterSize == 0)
{
    throw new ArgumentOutOfRangeException(nameof(SomeModel.ClusterSize));
}

if (timeToLive == default)
{
    throw new ArgumentNullException(nameof(SomeModel.TimeToLive));
}

if (version == 0)
{
    throw new ArgumentOutOfRangeException(nameof(SomeModel.Version));
}

if (linkedServiceName == null)
{
    throw new ArgumentNullException(nameof(SomeModel.LinkedServiceName));
}

return new SomeModel(
    clusterSize, 
    timeToLive, 
    version, 
    linkedServiceName, 
    hostSubscriptionId,
    servicePrincipalId, 
    servicePrincipalKey,
    tenant,
    clusterResourceGroup,
    clusterNamePrefix,
    clusterUserName, 
    clusterPassword, 
    clusterSshUserName, 
    clusterSshPassword
);
```

**Comment by KrzysztofCwalina** [comment]
I have to say this is surprising. 
But, can you try one more thing. Make all the literal strings you are using for lookup into statics like the following:
```csharp
static readonly byte[] b_clusterSize = Encoding.UTF8.GetBytes("clusterSize");
```

and then do lookup using the statics, i.e.:
```csharp
if (reader.ValueTextEquals(b_clusterSize)) ...
```

**Comment by KrzysztofCwalina** [comment]
@ahsonkhan, would you know what's going on? Why would JsonDocument be on par with Utf8JsonReader? Is there some optimization in JsonElement that fast paths access to properties if they are accessed in the right order (in the order they appear in the DB)?

**Comment by AlexanderSher** [comment]
Yes, byte arrays instead of strings give an improvement, about 1/3:
```
|                        Method |     Mean |     Error |    StdDev |  Gen 0 | Allocated |
|------------------------------ |---------:|----------:|----------:|-------:|----------:|
|      JsonDocument_StringNames | 4.045 us | 0.0793 us | 0.1489 us | 0.1945 |     816 B |
|   JsonDocument_ByteArrayNames | 3.781 us | 0.0753 us | 0.1759 us | 0.1945 |     816 B |
|          JsonDocumentReversed | 4.096 us | 0.0807 us | 0.1788 us | 0.1945 |     816 B |
|    Utf8JsonReader_StringNames | 4.148 us | 0.0828 us | 0.2062 us | 0.1678 |     728 B |
| Utf8JsonReader_ByteArrayNames | 2.711 us | 0.0532 us | 0.0986 us | 0.1717 |     728 B |
```

**Comment by KrzysztofCwalina** [comment]
Now the question is: what's the difference in the cost of writing a generator that would use Utf8JsonReader for more real-life models. The model you have above is a simple structure with primitive typed fields. Because of that the parser is relatively straightforward, which would be difficult to write a generator for. But I worry that a generator that can generate a similar parser for complex object graphs, e.g. some properties of the root object point to other complex objects and arrays. Maybe it's not too hard, in which case we should probably use Utf8JsonReader.

**Comment by annelo-msft** [comment]
We decided that we'll continue to use `JsonDocument` for now, so the generated code is easy to read.  As progress is made on [this proposal](https://github.com/dotnet/csharplang/blob/main/proposals/utf8-string-literals.md), we may update our serialization code to use `Utf8JsonReader` to get the performance gains.

**Comment by annelo-msft** [comment]
Investigation complete, and follow-up documented in this issue: https://github.com/Azure/azure-sdk-for-net/issues/24671

**Comment by ahsonkhan** [comment]
> @ahsonkhan, would you know what's going on? Why would JsonDocument be on par with Utf8JsonReader? Is there some optimization in JsonElement that fast paths access to properties if they are accessed in the right order (in the order they appear in the DB)?

You are absolutely correct, @KrzysztofCwalina. Doing a UTF-16 string to UTF-8 transcoding within the reader loop is relatively expensive, and caching that is a good optimization. In cases like these, where the results are surprising, it is helpful to re-evaluate how the code being measured is written, and if there is a side effect from the benchmark slowing things down.
