### ISSUE TITLE
Generating a SAS for a DataLake Blob Directory or file

### ISSUE THREAD

**Issue by gopala000** [Azure/azure-sdk-for-net#24709]
I followed the steps outlined in https://github.com/Azure/azure-sdk-for-net/issues/22896 to generate SAS for a directory and always get the below exception. In Azure side everything is open. I'm not sure what changes the name of my DFS endpoint https://gopdfsfoo.dfs.core.windows.net/ to gopblobfoo.dfs.core.windows.net. 

On a separate note, how can I generate SAS for a file? The use case is that in our SaaS service we will be storing jpg files of different customers. I would like to generate SAS token on file basis for the web & mobile client to fetch the files directly instead of proxy through us. If this is not possible, I can organize using directories.

`One or more errors occurred. (Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry. (No such host is known. (gopblobfoo.dfs.core.windows.net:443)) (No such host is known. (gopblobfoo.dfs.core.windows.net:443)) (No such host is known. (gopblobfoo.dfs.core.windows.net:443)) (No such host is known. (gopblobfoo.dfs.core.windows.net:443)) (No such host is known. (gopblobfoo.dfs.core.windows.net:443)) (No such host is known. (gopblobfoo.dfs.core.windows.net:443)))
`
Code below:

```
        public static async Task WTH(DataLakeSasPermissions permissions)
        {
            // client authenticated with a Shared Key (connection string contains the shared key)
            DataLakeDirectoryClient directoryClient = new DataLakeDirectoryClient("redacted connection string" , "gop-filesystem2", "gop-dir");
            // generate the SAS with setting the permissions and the expirey time
            Uri sasUri = directoryClient.GenerateSasUri(DataLakeSasPermissions.All, DateTimeOffset.UtcNow.AddDays(1));

            DataLakeDirectoryClient sasDirectoryClient = new DataLakeDirectoryClient(sasUri);

            // Act
            await foreach (PathItem pathItem in sasDirectoryClient.GetPathsAsync())
            {
                // Just make sure the call succeeds.
                Console.WriteLine(pathItem.Name);
            }
        }

```

**Comment by navba-MSFT** [comment]
@gopala000 Apologies for the late reply. Could you please check [this](https://docs.microsoft.com/en-us/azure/storage/blobs/sas-service-create?tabs=dotnet#create-a-service-sas-for-a-directory) sample code to create a service SAS for your datalake storage directory ? Awaiting your reply.

**Comment by gopala000** [comment]
Workaround has worked for the past few months. Please go ahead and close this ticket.
