### ISSUE TITLE
Inaccurate information

### ISSUE THREAD

**Issue by jamesosb-msft** [Azure/azure-sdk-for-net#24716]
CreateIfNotExists doesn't actually create the table if it doesn't exist.  Instead, it throws an exception with a 404 response stating that the table does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 476fd277-800d-ccc5-3081-4aa0b483680c
* Version Independent ID: 42801eef-7ec7-f7a9-29fd-542c7045f51e
* Content: [TableClient.CreateIfNotExists(CancellationToken) Method (Azure.Data.Tables) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclient.createifnotexists?view=azure-dotnet#Azure_Data_Tables_TableClient_CreateIfNotExists_System_Threading_CancellationToken_)
* Content Source: [xml/Azure.Data.Tables/TableClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Data.Tables/TableClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by christothes** [comment]
This was a bug that will be fixed in the next version - wee #24667
