### ISSUE TITLE
[BUG] TableClient does not work with Token Credentials

### ISSUE THREAD

**Issue by jamesosb-msft** [Azure/azure-sdk-for-net#24717]
1/25/2022 Update: Back in October, Christopher Scott helped me solve this issue.  It was the storage account permissions - being an 'owner' of a storage account does not grant table write access.  The requestor also needs to be a Storage Table Data Contributor.  I'm sure there's reasons for 'owner' not encompassing this and other roles.

**Describe the bug**
I can use DefaultAzureCredential() in a TableServiceClient and this works fine - I can create a table.  But if I do the same thing with a TableClient, when I call CreateIfNotExists, I get a 404 response saying the resource is not found.
Further, if I try to query an existing table with TableClient, I get a 403 "AuthorizationMismatch".  I am an owner on the storage account, so I don't see how my credentials would forbid me to query the table.  If I use a connection string, it all works fine, just when I use DefaultAzureCredential() things go bad.

**Expected behavior**
CreateIfNotExists shouldn't return a 404 if the SA doesn't exist.
Token credentials should work the same in TableClient as they do in TableServiceClient.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
CreatIfNotExists returns a 404
TableClient initialized with Token credentials is unusable.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```csharp
// You'll have to substitute your own storage account name and other various parameters here.

DefaultAzureCredential credential = new DefaultAzureCredential();
TableClient tableClient = new TableClient(new Uri($"https://{parameters["StorageAccountName"]}.table.core.windows.net/{parameters["TableName"]}"), parameters["TableName"], credential);
tableAlreadyExists = tableClient.CreateIfNotExists(); // throws a 404

// If I manually create the table, then try to query it, I get a 403:
Pageable<TableEntity> queryResultsFilter = tableClient.Query<TableEntity>(filter: $"PartitionKey eq '{FullyQualifiedInstanceName}'");

// I ensured I'm owner on the storage account.
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

I'm using:
Azure.Data.Tables 12.2.0
.Net 5.0

**Comment by christothes** [comment]
Does this problem still exist in the latest version of the package?

**Comment by jamesosb-msft** [comment]
IIRC, the issue I was facing had more to do with access policies on the storage account itself.  My false assumption was that 'owner' role would provide table write access.  It does not; I had to add Storage Table Data Contributor access as well.
