### ISSUE TITLE
Incorrect ObjectSerializer definition for some WriteAsJsonAsync<T> overloads

### ISSUE THREAD

**Issue by deanwiles** [Azure/azure-sdk-for-net#24729]
The following overloads incorrectly indicate "Write the specified value as JSON to the response body using the **provided ObjectSerializer**." when no ObjectSerializer is actually provided in the method signature. 

They should read "Write the specified value as JSON to the response body using the **default ObjectSerializer configured for this worker**." as is indicated in the other overloads that do not provide the ObjectSerializer.

- WriteAsJsonAsync<T>(HttpResponseData, T, CancellationToken)
- WriteAsJsonAsync<T>(HttpResponseData, T, HttpStatusCode, CancellationToken)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 566cdbf8-465d-a64b-f8d6-fdd172fef8ac
* Version Independent ID: a8a9381f-25ea-b0ab-d9f2-f4b7b0a3bf4b
* Content: [HttpResponseDataExtensions.WriteAsJsonAsync Method (Microsoft.Azure.Functions.Worker.Http) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httpresponsedataextensions.writeasjsonasync?view=azure-dotnet#Microsoft_Azure_Functions_Worker_Http_HttpResponseDataExtensions_WriteAsJsonAsync__1_Microsoft_Azure_Functions_Worker_Http_HttpResponseData___0_System_Threading_CancellationToken_)
* Content Source: [xml/Microsoft.Azure.Functions.Worker.Http/HttpResponseDataExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Functions.Worker.Http/HttpResponseDataExtensions.xml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Functions.Worker.Extensions.Http` package is maintained as [#679](https://github.com/Azure/azure-functions-dotnet-worker/issues/679).
