### ISSUE TITLE
Meaningless parameter description

### ISSUE THREAD

**Issue by ivanp-ms** [Azure/azure-sdk-for-net#24735]
Can we get into the habit of providing more descriptive and helpful parameter description? Parameter description which just scrambles the words is useless:

parentResourcePath
String
parentResourcePath Resource identity.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2eca981-bd82-9e6b-6ab5-4cf1569799fb
* Version Independent ID: 4ec5df2e-7bc2-3af8-7177-7ba6d80688cd
* Content: [IGenericResources.GetAsync(String, String, String, String, String, String, CancellationToken) Method (Microsoft.Azure.Management.ResourceManager.Fluent) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.igenericresources.getasync?view=azure-dotnet#Microsoft_Azure_Management_ResourceManager_Fluent_IGenericResources_GetAsync_System_String_System_String_System_String_System_String_System_String_System_String_System_Threading_CancellationToken_)
* Content Source: [xml/Microsoft.Azure.Management.ResourceManager.Fluent/IGenericResources.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ResourceManager.Fluent/IGenericResources.xml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
The reference doc is autogenerated , will check docs team if they can improve it
