### ISSUE TITLE
[ServiceBus] StopProcessingAdheresToTokenSLA failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#24746]
ServiceBus runs are failing with:

> Error message
> Expected: 00:00:03 +/- 00:00:03
> But was:  00:00:07.9884310
> Off by:   00:00:04.9884310
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Processor.ProcessorLiveTests.StopProcessingAdheresToTokenSLA() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/ProcessorLiveTests.cs:line 554
>    at Azure.Messaging.ServiceBus.Tests.Processor.ProcessorLiveTests.StopProcessingAdheresToTokenSLA() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/ProcessorLiveTests.cs:line 554
>    at Azure.Messaging.ServiceBus.Tests.Processor.ProcessorLiveTests.StopProcessingAdheresToTokenSLA() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/ProcessorLiveTests.cs:line 554
>    at Azure.Messaging.ServiceBus.Tests.Processor.ProcessorLiveTests.StopProcessingAdheresToTokenSLA() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/ProcessorLiveTests.cs:line 555
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass5_0.<RunTestOnSeparateThread>b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1142604&view=results

@jsquire for notification.

**Comment by JoshLove-msft** [comment]
Not failing lately.
