### ISSUE TITLE
[ServiceBus] DynamicConcurrencyTest failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#24745]
ServiceBus runs are failing with:

> Error message
> System.ApplicationException : Condition not reached within timeout.
> 
> Stack trace
>    at Microsoft.Azure.WebJobs.Host.TestCommon.TestHelpers.Await(Func`1 condition, Int32 timeout, Int32 pollingInterval, Boolean throwWhenDebugging, Func`1 userMessageCallback) in /Users/runner/work/1/s/sdk/extensions/Microsoft.Azure.WebJobs.Extensions.Clients/tests/shared/TestHelpers.cs:line 102
>    at Microsoft.Azure.WebJobs.Host.TestCommon.TestHelpers.Await(Func`1 condition, Int32 timeout, Int32 pollingInterval, Boolean throwWhenDebugging, Func`1 userMessageCallback) in /Users/runner/work/1/s/sdk/extensions/Microsoft.Azure.WebJobs.Extensions.Clients/tests/shared/TestHelpers.cs:line 109
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.DynamicConcurrencyTest() in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusEndToEndTests.cs:line 425
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1142604&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
This is a transient timeout;  closing.

**Comment by JoshLove-msft** [comment]
@mathewc it seems the dynamic concurrency tests fail from time to time. Any ideas how to improve them?
