### ISSUE TITLE
[QUERY]How to request a release for Microsoft.Azure.Management.ResourceManager

### ISSUE THREAD

**Issue by diwudd** [Azure/azure-sdk-for-net#24756]
**Query/Question**

How to request a release for Microsoft.Azure.Management.ResourceManager?

As it is neither a client nor management library, what is the process to request a release?

**Comment by ArthurMa1978** [comment]
@diwudd here is the new track 2 sdk for resource manager https://www.nuget.org/packages/Azure.ResourceManager/, and will have the stable release soon, you can try this lib instead of old management sdk
