### ISSUE TITLE
VisualStudioCredential - is it possible to select one of multiple accounts registered in VS?

### ISSUE THREAD

**Issue by andrei-faber** [Azure/azure-sdk-for-net#24755]
**Query/Question**
I have more than one account registered in Visual Studio. When I use VisualStudioCredential, it always chooses one of those accounts by default. Is it possible to make it choose another account?

**Environment:**
 - Azure.Identity 1.5.0
 - Windows 10 21H1, .NET 5
 - Visual Studio 16.11.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @andrei-faber  - 
Yes, you can select which account is the current one signed in by using the `Azure: Sign In` command. in the Command Pallet.

**Comment by andrei-faber** [comment]
@christothes however, is there any way to do that programmatically?
