### ISSUE TITLE
Documentation makes no mention of loss of caching

### ISSUE THREAD

**Issue by Meertman** [Azure/azure-sdk-for-net#24752]
In the previous implementation, the AzureServiceTokenProvider provided caching of the access token. In the newer Azure.Identity library this is no longer handled by the TokenCredential implementations, but rather by the Azure libraries themselves. (In the BearerTokenAuthenticationPolicy used by the HttpPipeline)

The migration documentation (https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration) makes no mention of this at all, and especially in the last example (see screenshot below), this will be very usefull for developers migrating to the newer version.
![image](https://user-images.githubusercontent.com/4199125/134167025-23d6e8b4-db2f-44eb-a0fc-a7ec045bde77.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by codewisdom** [comment]
Do you have a timeline for when this will be addressed?  Since ConfidentialClient provides token caching for free, it seems reasonable that something using this Azure.Identity approach should do the same:

https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-acquire-cache-tokens

**Comment by christothes** [comment]
Hi @codewisdom - Please see the following sample documentation describing how to persist token caching between credential instances. https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md#persisting-user-authentication-data
