### ISSUE TITLE
ArmClient ctor throws this error: "No subscriptions found for the given credentials"

### ISSUE THREAD

**Issue by andrei-faber** [Azure/azure-sdk-for-net#24754]
**Describe the bug**
ArmClient ctor throws this error: "No subscriptions found for the given credentials"

**Actual behavior (include Exception or Stack Trace)**
I have two Azure accounts. For one of those accounts, the code in the next section works properly. For another, it throws the exception quoted below (even though this account **does** have an active subscription associated with it).
```
System.Exception
  HResult=0x80131500
  Message=No subscriptions found for the given credentials
  Source=Azure.ResourceManager
  StackTrace:
   at Azure.ResourceManager.ArmClient.GetDefaultSubscription()
   at Azure.ResourceManager.ArmClient..ctor(String defaultSubscriptionId, Uri baseUri, TokenCredential credential, ArmClientOptions options)
   at Azure.ResourceManager.ArmClient..ctor(TokenCredential credential)
   at AzureTools.Program.Main(String[] args) in D:\Projects\AzureTools\AzureTools\Program.cs:line 30
```

**To Reproduce**
```csharp
var credential = new InteractiveBrowserCredential();
var armClient = new ArmClient(credential);
```

**Environment:**
 - Azure.ResourceManager 1.0.0-beta.4
 - Windows 10 21H1, .NET 5
 - Visual Studio 16.11.5

**Comment by isaacrlevin** [comment]
Seeing this as well in Azure.ResourceManager 1.0.0-beta.5

**Comment by isaacrlevin** [comment]
@jsquire any update here?

**Comment by jsquire** [comment]
Hi @isaacrlevin.   Unfortunately, beyond the initial triage, I'm not much help here.  I don't have insight into the current status.   

@ArthurMa1978:  Would you please be so kind as to provide an update?

**Comment by isaacrlevin** [comment]
@ArthurMa1978 any update on this issue. It is currently blocking me as the tool that I am writing has a dependency on the Azure CLI because of this bug.

**Comment by ArthurMa1978** [comment]
@archerzz  please help to check this issue
