### ISSUE TITLE
[LLC][Purview] The ImportGlossaryTermsViaCsv LRO operation of Catalog Glossary returns 500

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-sdk-for-net#24765]
**Describe the bug**
Calling the SDK method of `ImportGlossaryTermsViaCsv` returns 500 with the error: 

> {"requestId":"75f7d744-98b3-4898-9178-2809709b20fd","errorCode":"InternalServerError","errorMessage":"There was an error processing your request. This could be a transient issue and you may re-run the operation. If it fails again continuously, contact customer support with ID 75f7d744-98b3-4898-9178-2809709b20fd"}

On portal, the same API works fine. But I noticed in portal the content-type is `multipart/form-data; boundary=----WebKitFormBoundary53jkfAUlwEE9xxxx`. If I send the same request in Postman, service returns 400: 

> {"requestId":"75f7d744-98b3-4898-9178-2809709b20fd","errorCode":"RequestInvalid","errorMessage":"Request is not recognized. Please verify the HTTP method, header or URL"}

Then if I remove the boundary part to only keep `multipart/form-data`, service returns the same 500 error as SDK.

**Expected behavior**
What is the expected behavior?

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.
2.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by pallavit** [comment]
@pshao25 is this issue still valid?

**Comment by pshao25** [comment]
> @pshao25 is this issue still valid?

This is not customer report and doesn't have a good solution. I suggest we close it for now.
