### ISSUE TITLE
At least four links missing in documentation

### ISSUE THREAD

**Issue by AnhaytAnanun** [Azure/azure-sdk-for-net#24766]
[Enter feedback here]

Hi,

A thing in the documentation that I have noticed. In the section below, you do not provide link to logging mechanisms, there seem to be just a placeholder - [here][logging].
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.confidentialledger-readme-pre#setting-up-console-logging

There is also a similar issue in this section, for three links:
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.confidentialledger-readme-pre#contributing

Regards,
Nikolay.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30fbbcd5-c2d9-cd79-e384-57147cd8de0b
* Version Independent ID: 7dad563d-2595-e09a-667f-60b30a0e1f8f
* Content: [Azure Confidential Ledger client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.confidentialledger-readme-pre#create-a-client)
* Content Source: [api/overview/azure/storage.confidentialledger-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/storage.confidentialledger-readme-pre.md)
* Service: ****
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by wangli1030** [comment]
I have raised the PR to fix issue. Please review it.
