### ISSUE TITLE
[QUERY]question about distributed tracing with opentelemtry and Azure Monitor Exporter

### ISSUE THREAD

**Issue by pockyhe** [Azure/azure-sdk-for-net#24782]
**Query/Question**
Hi, My team would like to collect and consume traces by using Opentelemtry and Azure Monitor exporter. We still have some questions and hope you could help us.
the first question: I found the sampling supported in Opentelemtry is not supported in Azure Monitor Opentelemtry Exporter according to this guide: https://docs.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=net . so, for the latest version, is it supported?

the second question: I succeed to run my web app and the data showed up in the AppInsights. but, in the transaction detail, it showed 0 traces. 
![Picture1](https://user-images.githubusercontent.com/64390829/137707503-e98fbbfd-0cf3-43b1-a348-768d5f6a7f08.png)
it should have 1 trace with 5 spans. I don't know why it shows 0 traces

**Environment:**
Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.3
.NET 5.0
Opentelemetry  1.20-beta1

**Comment by Karishma-Tiwari-MSFT** [comment]
@pockyhe 

Azure Monitor OpenTelemetry Exporter for .NET, Node.js,and Python applications is currently in PREVIEW. Thus, there are several limitations with it currently. Sampling is not supported in Azure Monitor OpenTelemetry Exporter at this time.
Please keep an eye on [Azure updates page](https://azure.microsoft.com/en-ca/updates/) for the General availability (GA) of this feature.

For the second question, 
`I succeed to run my web app and the data showed up in the AppInsights. but, in the transaction detail, it showed 0 traces.`

Can you please confirm if you did enable sampling in OpenTelemetry? 
As mentioned under [Warning in the document](https://docs.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=net#sampling): 
`Enabling sampling in OpenTelemetry will make standard and log-based metrics extremely inaccurate which will adversely impact all Application Insights experiences. **Additionally, enabling sampling alongside the existing Application Insights SDKs will result in broken traces.**`

**Comment by Karishma-Tiwari-MSFT** [comment]
@pockyhe Did you get a chance to look at the comment above and did it help resolve your query? Please let me know. Thanks.

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for bringing this to our attention. We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
