### ISSUE TITLE
ResourceGroup - how do I get a list of resources of all types?

### ISSUE THREAD

**Issue by andrei-faber** [Azure/azure-sdk-for-net#24785]
There are many different methods that get resources of different types - GetStorageAccounts(), etc. However, I couldn't find any method that can list all the resources regardless the type, i.e. do the same what the `Get-AzResource` cmdlet without args does. Is there any way to do that?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @andrei-faber , you can use `Azure.ResourceManager` to list all the resources.
Here is the code sample which can list all the resources in current subscription.
```csharp
ArmClient armClient = new ArmClient(new DefaultAzureCredential()); //DefaultAzureCredential is in Azure.Identity
Subscription subscription = await armClient.GetSubscriptions().GetAsync(subscriptionId);
List<GenericResource> genericResources = await subscription.GetGenericResources().GetAllAsync().ToEnumerableAsync();
```
You can also use the method `GetByResourceGroupAsync` to get resources in the specific resource group.
```csharp
List<GenericResource> genericResources = await subscription.GetGenericResources().GetByResourceGroupAsync(rgName).ToEnumerableAsync();
```

**Comment by andrei-faber** [comment]
@Yao725 I see. I was looking for it in the resource group.
But it doesn't have ToEnumerableAsync(), only GetAsyncEnumerator(). Do I need to import some extra packages for this functionality?

**Comment by Yao725** [comment]
@andrei-faber Sorry, my bad. `ToEnumerableAsync()` is implemented in `Azure.Core.TestFramework`, so if you want to use this, you need to add the project reference.
BTW, I also list the source code here, you can implement this by yourself.
```csharp
namespace Azure.Core.TestFramework
{
    public static class TestAsyncEnumerableExtensions
    {
        public static async Task<List<T>> ToEnumerableAsync<T>(this IAsyncEnumerable<T> asyncEnumerable)
        {
            List<T> list = new List<T>();
            await foreach (T item in asyncEnumerable)
            {
                list.Add(item);
            }
            return list;
        }
    }
}
```

**Comment by andrei-faber** [comment]
@Yao725 thanks.
By the way, is there any reliable way to identify the kind of the resource? I see that Data.Kind can be used for this, but it uses a string rather than enum and some resource types don't have this info at all.

**Comment by Yao725** [comment]
@andrei-faber You can use `resource.Id.ResourceType` to get the type of the resource.

**Comment by andrei-faber** [comment]
@Yao725 I see. Thanks.
