### ISSUE TITLE
Breaking change in AzureAsyncOperation and GetLongRunningOperationResultAsync

### ISSUE THREAD

**Issue by blumu** [Azure/azure-sdk-for-net#2479]
How do you check for status of long running operation in the latest Azure Management NuGets based on `Microsoft.Rest.ClientRuntime.Azure 3.3.1`, such as when deleting a VM? 
* The static method extension `GetLongRunningOperationResultAsync` (replacing [`GetLongRunningOperationStatusAsync`](https://msdn.microsoft.com/en-us/library/azure/microsoft.azure.management.resources.iresourcemanagementclient.getlongrunningoperationstatusasync.aspx)) now takes a `AzureOperationResponse` as a parameter instead of `AzureAsyncOperation` from previous versions.  
* `GetLongRunningOperationResultAsync` returns a `AzureOperationResponse` which does not contain any information about the original async request (pending, failed, success?)
* The `BeginXXX` function like `BeginDeleteAsync` don't return anything anymore (they use to return an `AzureAsyncOperation`)
* The `BeginXXXWithHttpMessagesAsync` (e.g. `BeginDeleteWithHttpMessagesAsync`) do return an `AzureOperationResponse` but this type does not seem to contain any `operationStatusLink` that could be serialized/deserialized (which is sometimes needed to check operation status at a later stage).

Is there any example showing how to do check status of long running operations with the new Nugets?

**Comment by markcowl** [comment]
@blumu You are comparing apples to oranges.  The ARM based API has asynchronous creation methods that do polling for you.  operationStatusLink is an artifact of the RDFE API.  

To do manuyal polling with the current library, you would:

(1) Call Begin*WithHttpMessageAsync
(2) Use the response proeprty to get the AzureAsyncOperation header value
(3) Poll on the resulting Uri until you reach a terminal state

The library is designed for asynchronously polling for you.  Issue #2485 tracks implementing a new manual polling mechanism based on the new paradigm for asynchronous methods.  Closing this issue as a duplicate.

**Comment by blumu** [comment]
@markcowl I'm comparing two versions of the **same** SDK. For Microsoft.Azure.Management.Compute, for instance, that's 9.1.0 versus 13.0. How is that "comparing apples to oranges"?
