### ISSUE TITLE
[FEATURE REQ] Make MultipartFormDataContent public

### ISSUE THREAD

**Issue by Socolin** [Azure/azure-sdk-for-net#24819]
**Library or service name.**
Azure.Core
 

Hello,

All your HttpPipeline stuff is great and so we are using them to build client for custom services too.
Could you expose `MultipartFormDataContent` by making it `public` instead of `internal` and expose `_headers` from `MultipartContent` (or maybe there is some code that should already read _headers and put it in the request headers that I missed) ?

**Comment by annelo-msft** [comment]
Tracking this request and the overall effort with https://github.com/Azure/azure-sdk-for-net/issues/28369, so closing this instance.
