### ISSUE TITLE
Please mark this exception as transient

### ISSUE THREAD

**Issue by mtrmmsoftware** [Azure/azure-sdk-for-net#24811]
[Enter feedback here]
We got this kind of exception on our system while talking with EventGrid, I did not found an indication that this exception is transient, thus I opened a support request, because the exception message also suggested to do that, the MS support said it is transient and please retry...  The whole time would have been spared if the exception was marked here as transient!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d07969b2-8459-4174-67e4-01f4518403fe
* Version Independent ID: 37529303-83cb-f3d0-8de7-3f764881418f
* Content: [CloudException Class (Microsoft.Rest.Azure) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.azure.cloudexception?view=azure-dotnet)
* Content Source: [xml/Microsoft.Rest.Azure/CloudException.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Rest.Azure/CloudException.xml)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by AlexGhiondea** [comment]
Which library were you using?

**Comment by mtrmmsoftware** [comment]
We are using Microsoft.Azure.EventGrid v3.2.0 in the mean time we got more feedback from the MS Support that the exception can be sometimes not transient. This fuzziness is complicated to handle. Currently we retry the action for 3 times if it occurs more than 3 times we assume that the exception is not transient.

Mihail Tambur | M. Sc. Engineering | Senior Software Developer

M&M Software GmbH | Industriestr. 5 | 78112 St. Georgen | GERMANY
Phone +49 7724 9415-2516 | ***@***.******@***.***> | Teams ***@***.***>

M&M Website<http://www.mm-software.com> | M&M Newsletter<http://www.mm-software.com/newsletter/subscribe> | XING<http://www.xing.com/companies/m&msoftwaregmbh> | LinkedIn<https://www.linkedin.com/company/m&m-software-gmbh> | Facebook<https://www.facebook.com/mmsoftware.gmbh> | YouTube<http://www.youtube.com/user/mmsoftwaregmbh> | Kununu<http://www.kununu.com/de/all/de/it/mm-software>

--------------------------------------------------
Registered Office: St. Georgen, Germany - Registry Court: Freiburg HRB 602021 - Directors: Klaus Hübschle, Christian Gnädig
This email is intended solely for the use of the named address(es). Any unauthorized disclosure, copying or distribution of these confidential information contained therein, or the taking of any action based on it, is prohibited.
--------------------------------------------------
Further information regarding data processing in accordance with article 13 and 14 EU-GDPR can be found at https://mm-software.com/en/privacy

**Comment by jsquire** [comment]
The AutoRest runtime stack reached end-of-life in September and is no longer supported.  Closing.
