### ISSUE TITLE
"No Such Host is Known" exception thrown when calling DataLakeDirectoryClient.CreateFile() and storage account name contains "blob"

### ISSUE THREAD

**Issue by chbarnett-msft** [Azure/azure-sdk-for-net#24821]
**Describe the bug**
Including the string "blob" in the storage account name and calling CreateFile() of the DataLakeDirectoryClient causes the following exception to be thrown:
"System.AggregateException: 'Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry. 
(No such host is known. (adlstestdfschecker.blob.core.windows.net:443)) (No such host is known. (adlstestdfschecker.blob.core.windows.net:443)) (No such host is known. "

**Expected behavior**
Expect the file to be created when the CreateFile() method is called from the DataLakeDirectoryClient.

**Actual behavior (include Exception or Stack Trace)**
Exception is thrown (see above). The name of the storage account is modified to replace "blob" with "dfs". 
 The actual name used in the discovery scenario was "adlstestblobchecker". This name is modified to "adlstestdfschecker" after
the call is made to CreateFile().

**To Reproduce**
1. Name an account with the string "blob" in the name.
2. Run code below with the newly created account name assigned to the accountName variable.
2. Here is the code that was ran to cause the exception:

namespace ADLSDemo
{
    class Program
    {
        static void Main(string[] args)
        {
            //create variables to hold the account name and key
            var accountName = "adlstestblobchecker";
            var accountKey = "xxxx";

            //instantiate the shared key credential
            StorageSharedKeyCredential sharedKeyCredential = new StorageSharedKeyCredential(accountName, accountKey);

            //use the account name to construct the dfs uri
            string dfsUri = "https://" + accountName + ".dfs.core.windows.net";

            Console.WriteLine(dfsUri);

            //create the dataLakeServiceClient
            var dataLakeServiceClient = new DataLakeServiceClient(new Uri(dfsUri), sharedKeyCredential);

            //create the name of the container/file system
            var containerName = "testfilesystem";

            //Create container using the DataLakeServiceClient
            dataLakeServiceClient.CreateFileSystem(containerName);

            //Create a directory in the file system
            DataLakeFileSystemClient fileSystemClient = dataLakeServiceClient.GetFileSystemClient(containerName);

            //Create directory
            fileSystemClient.CreateDirectoryAsync("testdirectory");

            //Create directory client for upload
            DataLakeDirectoryClient directoryClient = fileSystemClient.GetDirectoryClient("testdirectory");

            //Create file client for uploading file
            DataLakeFileClient fileClient = directoryClient.CreateFile("adlstest.txt");

            //Create file stream of file to be uploaded
            FileStream fileStream = File.OpenRead("C:\\Users\\chbarnett\\OneDrive - Microsoft\\Documents\\Test\\adlstest.txt");

            //Get the size of the file being uploaded
            long fileSize = fileStream.Length;

            fileClient.Append(fileStream, offset: 0);

            fileClient.Flush(position: fileSize);

        }
    }
}

**Findings after reviewing source code on GitHub**
First call is to DataLakeDirectoryClient.CreateFile() - 
https://github.com/Azure/azure-sdk-for-net/blob/957ea65288a2046af2ca125ec2039e338a4fdbe4/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeDirectoryClient.cs#L1766

Next call is DataLakeFileClient.Created()
https://github.com/Azure/azure-sdk-for-net/blob/957ea65288a2046af2ca125ec2039e338a4fdbe4/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileClient.cs#L370

This method calls base.create()
base = DataLakePathClient
Here in the constructor, the URIs are created:
https://github.com/Azure/azure-sdk-for-net/blob/957ea65288a2046af2ca125ec2039e338a4fdbe4/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakePathClient.cs#L286

Next, DataLakeUriBuilder is called and performs a string replace to swap out "blob" with "dfs" over the entire host name:
https://github.com/Azure/azure-sdk-for-net/blob/957ea65288a2046af2ca125ec2039e338a4fdbe4/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeUriBuilder.cs#L304

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Files.DataLake (12.8.0)
 - Hosting platform or OS and .NET runtime version: Windows 10 with .NET 5.0
 - IDE and version : Visual Studio 2019 16.11.3

**Comment by dmfedorchuk** [comment]
I faced the same issue for 12.7.0 and 12.8.0.  (Azure.Storage.Files.DataLake)
Storage account = "somename"

> No such host is known. (somenamedfs.blob.core.windows.net:443) 

Expected to see smth like "somename.dfs.core.windows.net"
**Working fine for "12.6.2" and below.**

```
System.AggregateException: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (No such host is known. (somenamedfs.blob.core.windows.net:443)) (No such host is known. (somenamedfs.blob.core.windows.net:443)) (No such host is known. (somenamedfs.blob.core.windows.net:443))
 ---> Azure.RequestFailedException: No such host is known. (somenamedfs.blob.core.windows.net:443)
 ---> System.Net.Http.HttpRequestException: No such host is known. (somenamedfs.blob.core.windows.net:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
```
