### ISSUE TITLE
Should Last* fields in Azure.Messaging.EventHubs.EventData be public?

### ISSUE THREAD

**Issue by thomasmorrisresideo** [Azure/azure-sdk-for-net#24834]
https://github.com/Azure/azure-sdk-for-net/blob/6819082909e8c19b1d0097503c3ae5654e0d80f0/sdk/eventhub/Azure.Messaging.EventHubs/src/EventData.cs#L309

I'm using [EventProcessor\<TPartition\>](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample08_CustomEventProcessor.md), and I'd like access to the `LastPartitionSequenceNumber`, `LastPartitionOffset`, and `LastPartitionEnqueuedTime` for determining processing lag in our implementation of `OnProcessingEventBatchAsync`.

**Comment by jsquire** [comment]
Hi @thomasmorrisresideo.  Thank you for reaching out and we regret that you're experiencing difficulties.   

If you set [TrackLastEnqueuedEventProperties](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.eventprocessorclientoptions.tracklastenqueuedeventproperties) in the `EventProcessorClientOptions` when creating your processor, this information is available to your event processing handler through the `ProcessEventArgs`  passed to it.   The args have a [Partition](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.processor.processeventargs.partition) property that returns the context for the partition that the event belongs to.   On that context, the [ReadLastEnqueuedEventProperties](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.consumer.partitioncontext.readlastenqueuedeventproperties) that will give you access to the "Last*" items.

For example:
```csharp
Task processEventHandler(ProcessEventArgs args)
{
    try
    {
        if (args.CancellationToken.IsCancellationRequested)
        {
            return Task.CompletedTask;
        }

        var lastEnqueuedEventProperties = args.Partition.ReadLastEnqueuedEventProperties();
        var lastSequenceNumber = lastEnqueuedEventProperties.SequenceNumber;
    }
    catch
    {
        // It is very important that you always guard against
        // exceptions in your handler code; the processor does
        // not have enough understanding of your code to
        // determine the correct action to take.  Any
        // exceptions from your handlers go uncaught by
        // the processor and will NOT be redirected to
        // the error handler.
    }

    return Task.CompletedTask;
}
```

**Comment by jsquire** [comment]
Apologies;  I misread your inquiry.   If you're using `EventProcessor<T>` instead of the processor client, the last enqueued event properties for any given partition is available by calling the [ReadLastEnqueuedEventProperties](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessor-1.readlastenqueuedeventproperties?view=azure-dotnet) method on the processor itself. 

You'll still need to set `TrackEnqueuedEventProperties` in your processor options for that data to be available.

**Comment by thomasmorrisresideo** [comment]
thanks - that solved it!
