### ISSUE TITLE
Microsoft.Azure.Management.IotHub AccessRights does not deserialize RegistryReadRegistryWriteServiceConnectDeviceConnect enum

### ISSUE THREAD

**Issue by Sedols** [Azure/azure-sdk-for-net#24837]
**Describe the bug**
When IoT Hub access policy has set all rights "RegistryRead, RegistryWrite, ServiceConnect, DeviceConnect" when reading the keys in .NET it deserializes into RegistryWriteServiceConnectDeviceConnect enum instead of RegistryReadRegistryWriteServiceConnectDeviceConnect in Microsoft.Azure.Management.IotHub.Models 4.1.0 

**Expected behavior**
The enum RegistryReadRegistryWriteServiceConnectDeviceConnect  should be used or retired to avoid confusion

**Actual behavior (include Exception or Stack Trace)**
RegistryRight was dropped and presented as RegistryWriteServiceConnectDeviceConnect  instead

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Make sure IoTHub has access policy with all rights
2. Call /list keys API and deserialize the response to List of SharedAccessSignatureAuthorizationRule. The AccessRights returned will have RegistryWriteServiceConnectDeviceConnect 

**Environment:**
 - Microsoft.Azure.Management.IotHub Version 4.1.0 
 
 - .NET Core SDK (reflecting any global.json):
 Version:   3.1.414
 Commit:    88a3b0c5ca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\3.1.414\

Host (useful for support):
  Version: 5.0.11
  Commit:  f431858f8b

.NET SDKs installed:
  3.1.410 [C:\Program Files (x86)\dotnet\sdk]
  3.1.412 [C:\Program Files (x86)\dotnet\sdk]
  3.1.414 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files (x86)\dotnet\shared\Microsoft.WindowsDesktop.App]

 - Visual Studio 2019 16.11

**Comment by dvbb** [comment]
In the shared access policy, the [RegistryWrite] right includes the [RegistryRead] right by default
as shown in fiddler:

``` JSON
{
    "keyName": "iothubowner",
    "primaryKey": "*************",
    "secondaryKey": "*************",
    "rights": "RegistryWrite, ServiceConnect, DeviceConnect"
},
{
    "keyName": "registryReadWrite",
    "primaryKey": "*************",
    "secondaryKey": "*************",
    "rights": "RegistryWrite"
}
```

The current version of the [swagger](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/iothub/resource-manager/Microsoft.Devices/preview/2021-07-01-preview/iothub.json#L2144) file is wrong

This issue will add the [Service Attention] label
