### ISSUE TITLE
Default values

### ISSUE THREAD

**Issue by KirillBorunov** [Azure/azure-sdk-for-net#24854]
Please include the default values in the documentation. How I supossed to know if need to specify the value for the the parameter if I don't know the default value?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 522dd94f-d005-9cd0-0643-cd08b852c65b
* Version Independent ID: 855896f3-cff5-7d6f-153e-8413fdae508e
* Content: [TokenValidationParameters Class (Microsoft.IdentityModel.Tokens) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters?view=azure-dotnet)
* Content Source: [xml/Microsoft.IdentityModel.Tokens/TokenValidationParameters.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Tokens/TokenValidationParameters.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.IdentityModel.Tokens` package is maintained as [#1735](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1735).
