### ISSUE TITLE
Implement manual polling mechanism in the runtime for ARM long-running operations

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2485]
### Description

Refactor the runtime to allow manual polling using our state machine.  The Polling state should be easily serializable, and polls should be asynchronous and non-blocking.  This allows for polling in workflow scenarios where the state may need to be serialized and re-hydrated.

Optionally refactor generated code to use the manual polling mechanism.

**Comment by hovsepm** [comment]
Please consider a fix for this one as well https://github.com/Azure/azure-sdk-for-net/issues/2479

**Comment by shahabhijeet** [comment]
This work has been deprioritized. We will for sure add this feature sometime in next Feb-March 2019 time frame.

**Comment by Petermarcu** [comment]
@pakrym is this something thats already solved in Azure Core + new codegen?

**Comment by pakrym** [comment]
Yes, closing.
