### ISSUE TITLE
[Synapse] CanCheckPrincipalAccessViaGrowUpHelper failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#24869]
Synapse test runs are failing with:

> Error message
> Expected string length 7 but was 10. Strings differ at index 0.
> Expected: "Allowed"
> But was:  "NotAllowed"
> -----------^
> 
> 
> Stack trace
>    at Azure.Analytics.Synapse.AccessControl.Tests.AccessControlClientLiveTests.CanCheckPrincipalAccessViaGrowUpHelper() in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.AccessControl\tests\AccessControlClientLiveTests.cs:line 295
>    at Azure.Analytics.Synapse.AccessControl.Tests.AccessControlClientLiveTests.CanCheckPrincipalAccessViaGrowUpHelper() in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.AccessControl\tests\AccessControlClientLiveTests.cs:line 300
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1154641&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Given the age of this issue, I'm going to close it as stale.  If tests continue to fail, please file a new issue.
