### ISSUE TITLE
Allow null value when deserializing response

### ISSUE THREAD

**Issue by yukun-dong** [Azure/azure-sdk-for-net#24865]
MessagingPlan and Region in Eventhub are TrackedResource and TrackedResource has a "tags"(a dictionary) property. The response of MessagingPlan and Region has "tags":null, which causes error in deserialization.

**Comment by ArthurMa1978** [comment]
Has filed a S360 ticket to AppService teams, waiting for response

**Comment by ArthurMa1978** [comment]
@m-nash disagree this change in autorest.csharp, as we can use directive to omit this kind of error, so close it
