### ISSUE TITLE
[Microsoft.Rest.ClientRuntime] requests are malformed after another request times out

### ISSUE THREAD

**Issue by JanEggers** [Azure/azure-sdk-for-net#2487]
hi 

first i thought this was an error with kestrel so i created an issue there:

https://github.com/aspnet/KestrelHttpServer/issues/1174

after one request times out the next request "get" is malformed

![](https://cloud.githubusercontent.com/assets/6747376/19588950/65095314-9769-11e6-800d-1cd5b32f5368.png)

**Comment by JanEggers** [comment]
update: i added proxy settings to the client and now was able to capture a session with fiddler
there are several errors in it:

1. chunked encoding sometimes has fancy values (fiddler lines yellow)
2. looks like parts of the response go in the request stream

really confusing stuff please help

[brokenrequests.zip](https://github.com/Azure/azure-sdk-for-net/files/543777/brokenrequests.zip)

**Comment by JanEggers** [comment]
yet another update: i guess its a parallel processing issue

i have code like:

await Task.Whenall( parents.Select( async p =>
{
        p.childs = await m_api.GetChildForParentAsync(p.Id);
} ) );

and in the parent list there are currently 900 entries

**Comment by markcowl** [comment]
@JanEggers Can you include the generated code for the method?  There shouldn't be any asynchronous issue with the code itself.

**Comment by JanEggers** [comment]
[Generated.zip](https://github.com/Azure/azure-sdk-for-net/files/549846/Generated.zip)

GetCounterDefinitionOfMachineTypeAsync of the extenssion file is what im using.

i call it for every minute for every machinetype i get.

it must be related to many parallel requests, because when i reduced the number of machine type objects to 30 there are no issues anymore.  if i recreate more than 800 machine type objects the errors happen again.

**Comment by markcowl** [comment]
@JanEggers is this .net 4.5.2, .netcore, or both?

**Comment by JanEggers** [comment]
both

**Comment by shahabhijeet** [comment]
@JanEggers first of all sorry for getting to this issue so late.
Please help me understand this issue and let me know if this is still an issue.
What is missing in this the following information:
1) Name of SDK and version
2) Also a scenario that you can describe so that I can repro at my end.

**Comment by JanEggers** [comment]
@shahabhijeet this was aspnetcore 1.0 on core runtime and net461 and I didnt encounter the issue since. so ill close this one and open a new issue if I see anything similar.
