### ISSUE TITLE
[BUG] KeyVault Certificate Download leads to 404

### ISSUE THREAD

**Issue by samuelbentrup** [Azure/azure-sdk-for-net#24877]
**Describe the bug**
Downloading a certificate using CertificateClient.DownloadCertificate using a Managed Identity is resulting in a 404 not found.  Same for a SecretClient.GetSecret;   The Managed Identity can do a GetCertificate or GetPropertiesOfCertificates.   The certificate in question was a self-signed certificate public/private keypair Imported into a Keyvault Certificates section with the private key.   Using another identity (such as my logged in user) can retrieve the private key just fine.  Would lead me to a permission issue - but the managed service identity has all permissions available (not desired, but I blew it out just to test).

**Expected behavior**
Expected behavior that the public/private keypair are downloadable via DownloadCertificate("Name")

**Actual behavior (include Exception or Stack Trace)**
Stack Trace from VS Debugger:
Azure.RequestFailedException
  HResult=0x80131500
  Message=
Status: 404 (Not Found)

Content:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

Headers:
Strict-Transport-Security: max-age=31536000;includeSubDomains
X-Content-Type-Options: nosniff
Content-Length: 1245
Content-Type: text/html
Date: Fri, 22 Oct 2021 18:11:38 GMT
X-Powered-By: ASP.NET

  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

var certificateClient = new CertificateClient(AzureKeyVaultCertificate, defaultCreds);
var azurecert = certificateClient.DownloadCertificate("AdvanceClientScripting"); <-- results in 404 as Managed Identity.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 Azure.Security.Kevyault.Certificates Version 4.2.0.0
 - Azure App Service (ASP.NET 4.8)

**Comment by heaths** [comment]
The exception will have a stack trace which we need to see. What does `Console.WriteLine(ex.Message);` from your sample code actually emit? Without that it's impossible to troubleshoot this issue since we don't know what is saying the file wasn't found.
