### ISSUE TITLE
[BUG] Can't pass in ids for VirtualMachineScaleSetVMInstanceIDs in Azure.ResourceManager.Compute.Models

### ISSUE THREAD

**Issue by GoMADAO** [Azure/azure-sdk-for-net#24887]
**Describe the bug**
In Azure.ResourceManager.Compute VirtualMachineScaleSet class, many functions (ReImage, ReImageAll, PowerOff, PowerOn) relies on input instanceIds of type VirtualMachineScaleSetVMInstanceIDs. However, the VirtualMachineScaleSetVMInstanceIDs constructor can not pass in any instanceIds list, nor it allows to set the List<string> instanceIds. As a result, we can't execute any of those functions.

**Expected behavior**
What is the expected behavior?
VirtualMachineScaleSetVMInstanceIDs constructor should allow pass in InstanceIds parameter.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
VirtualMachineScaleSetVMInstanceIDs constructor does not allow pass in InstanceIds parameter.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

![image](https://user-images.githubusercontent.com/6690105/138531845-faf04a77-767d-4c1a-83c9-583290bf291a.png)
![image](https://user-images.githubusercontent.com/6690105/138531861-71294c7e-fa19-4cba-885d-81f86eea9925.png)

**Environment:**
 - Name and version of the Library package used: [Azure.ResourceManager.Compute.1.0.0-beta.2] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by ArthurMa1978** [comment]
@GoMADAO This is a common pattern in mgmt. sdk, the `InstanceIDs` is unassignable that the SDK will initialize it with a built-in List type, and the fact of no-setter could ensure you cannot change the list to another instance. And the usage is add element to it, you can check out more information here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-collection-read-only-property-initialization .
