### ISSUE TITLE
How can I reuse an already acquired token via interactiveBrowserCredentialOptions for Microsoft Graph using Azure.Identity 

### ISSUE THREAD

**Issue by AshleyAsh90** [Azure/azure-sdk-for-net#24906]
**Query/Question**
I am using the below code to acquire tokens interactively by signing users in.
https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/dev/docs/upgrade-to-v4.md#example-using-tokencredential-class
The problem is, once the application is stopped, I lose the logged in user and will have to sign in the user again. Is there a way to save and use the token that is obtained in the first sign in? I see some TokenPersistenceCache options but there is no sample of how to use it other than this below,
https://docs.microsoft.com/en-us/dotnet/api/azure.identity.tokencachepersistenceoptions?view=azure-dotnet
I tried to use this part of the code snippet
```
//Call AuthenticateAsync to fetch a new AuthenticationRecord.
    authRecord = await credential.AuthenticateAsync();
```

which is different from the suggested code for Microsoft.Graph which is below
```
User me = await graphClient.Me.Request()
                .GetAsync();
```
But it fails with a "InteractiveBrowserCredential authentication failed: AADSTS650057: Invalid resource." error.
I don't want the user to be asked for credentials every time they start the app if the user has already logged in once. How can I achieve this for MS Grpah with Azure.Identity? Could you help please?

**Environment:**
 -  Azure.Identity 1.5
 - Microsoft.Graph(Tried both 4.3 and 4.7) 
 - OS and .NET runtime version ( Windows 10 .NET Framework 4.7.2)
 - IDE and version : Visual Studio 16.6.5

**Comment by AshleyAsh90** [comment]
Hello, @schaabs , @christothes Just want to check again on this-what would be a neat way to logout the persisted user? How can I change the user who is logged in other than by deleting the saved Authentication Record and allowing a new Authentication Record to be created. Is there a better way to do that? Because the MSAL Cache is still persisted regardless of deleting the AuthenticationRecord and MSAL holds the sensitive info per the statement here.
>The AuthenticationRecord which is returned from the Authenticate and AuthenticateAsync, contains data identifying an authenticated account. It is needed to identify the appropriate entry in the persisted token cache to silently authenticate on subsequent executions. There is no sensitive data in the AuthenticationRecord so it can be persisted in a non-protected state.

**Comment by christothes** [comment]
Probably the safest way would be to delete the persisted cache and start over. Although MSAL does persist the cache, the `TokenCachePersistenceOptions` have a `Name` property that uniquely identifies the cache. So changing that name to a new unique name effectively makes it a new cache without any history.

https://github.com/Azure/azure-sdk-for-net/blob/6a2213dd974db0b934c7d62c309b416c371adbcd/sdk/identity/Azure.Identity/src/TokenCachePersistenceOptions.cs#L62

**Comment by AshleyAsh90** [comment]
Ok, Thanks for your help on this. I will close this query now.
