### ISSUE TITLE
Try async analyzer on Azure SDK common patterns

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#24900]
See https://github.com/dotnet/roslyn-analyzers/pull/5367

**Comment by jsquire** [comment]
Rule is not enabled by default in .NET 7.   _([docs](https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1849))_

According to the docs, this does not seem like it would play well with the sync/async patterns in the Azure SDK, given that we generally run both paths through a common method and control with a conditional:
> It's safe to suppress a warning from this rule in the case where there are two separate code paths for sync and async code, using an if condition. Also if there is a check for whether the Task has resolved, it is safe to use sync methods and properties
