### ISSUE TITLE
Escaped HTML entities are visible in the docs: &lt; br&, gt;

### ISSUE THREAD

**Issue by boumenot** [Azure/azure-sdk-for-net#24905]
There are escaped HTML entities in the document that do not appear to belong.  This include `&lt;`, `br`, and `&gt;`.  Is this due to a bad merge?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c65ea12-e84f-fc98-5394-f197f417941d
* Version Independent ID: 5afa0874-026d-9eaf-15ac-a407e17c8a4b
* Content: [OSDisk.DeleteOption Property (Microsoft.Azure.Management.Compute.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.osdisk.deleteoption?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/OSDisk.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/OSDisk.xml)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ArthurMa1978** [comment]
Will contact docs team
