### ISSUE TITLE
[EngSys] Sanitize 8 false positive CredScan leaks in Synapse

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#24911]
It seems we are using a (clearly fake) secret in our recordings: `clientSecret`. Example:

https://github.com/Azure/azure-sdk-for-net/blob/cbef31d9894a62cddb2140b05fa3f64c03abf30f/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/SessionRecords/NotebookClientLiveTests/TestGetNotebookAsync.json#L1607

CredScan doesn't seem to realize it's not an actual secret ([reported here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1157131&view=logs&j=3b141548-98d7-5be1-7ef8-eeb08ca02972&t=0e8e7737-144a-52f9-f403-f73b27780f1e&l=225)), so it's detecting 8 leaks.

We have two options here:

1. Add the string `clientSecret` to our [CredScan suppresion file](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/CredScanSuppression.json).

2. Update the Synapse tests to stop using the string `clientSecret` and start using one of the strings already being suppressed in the suppression file above (such as `__CLIENT_SECRET__`). Tests need to be recorded again in this case.

1 is way easier but we are trying to keep the suppression file clean. We should investigate how feasible it is to follow approach 2 and choose one of them.

**Comment by pallavit** [comment]
clientSecret is already in the supression file.
