### ISSUE TITLE
[QUERY]Distinguish between a new blob created vs a blob replaced based on the response

### ISSUE THREAD

**Issue by asgoe** [Azure/azure-sdk-for-net#24914]
**Query/Question**
How can we help?
How can we distinguish based on the response of UploadAsync whether a new blob was created or an existing blob updated? We need to log the creation of the new blob after calling UploadAsync. However, the status in the response for both the above cases is a 201 (Created). I do not see any other field which might help us distinguish the two cases. We do not want the overhead of checking the existence of the blob for this purpose.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.7.0, Azure Identity 1.3.0, Azure Core 1.6.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Framework 4.7
 - IDE and version : Visual Studio 16.9.12

**Comment by amishra-dev** [comment]
@asgoe this would be a request for the service. Can you shoot me an email.
