### ISSUE TITLE
Azure Resource Management Core Readme Issue

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#24922]
1.
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemanager/Azure.ResourceManager#check-if-a-resource-exists)
![image](https://user-images.githubusercontent.com/76771069/138817207-69f84ac4-f9a9-490e-9fc3-3a1a540bfb16.png)
Suggestion:
We should update 'GetIfExists()' to 'GetIfExistsAsync()'  consistent with the code

2.
Section [Link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemanager/Azure.ResourceManager#contributing)
![image](https://user-images.githubusercontent.com/76771069/138817415-54577c09-a5e6-446c-84d6-a1e325cf59ad.png)
Suggestion:
	1. Add Link: https://opensource.microsoft.com/codeofconduct/
	2. Add Link: https://opensource.microsoft.com/codeofconduct/faq/

@scottaddie,@AlexGhiondea and @archerzz for notification.

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/25986
