### ISSUE TITLE
Support region move (Azure Resource Mover)

### ISSUE THREAD

**Issue by cfauchere** [Azure/azure-sdk-for-net#24926]
**Library or service name.**
Azure.ResourceManager.Resources
Like there is `StartMoveResources` which moves resources from rg A to rg B it would be useful to be able to move resources cross region.

**Is your feature request related to a problem? Please describe.**
Using SDK I cannot move resources from region A to region B. This is required to achieve data sovereignty.

**Comment by fengzhou-msft** [comment]
> I see there is an API `IResourceMoverServiceAPIClient` that seems promising. Similarly to `IAzureReservationAPIClient` I am wondering if those are supported as it seems inconsistent with other clients such as `ResourcesManagementClient`, `NetworkManagementClient` and `ComputeManagementClient`:
> 
> * namespace have different pattern
> * interface vs class
> * even the credentials type: `ServiceClientCredentials` vs `TokenCredentials`
> 
> I wonder if those clients are legacy since `ServiceClientCredentials` is also used in the previous [library](https://github.com/Azure/azure-libraries-for-net):

@cfauchere these are track 1 SDKs and are deprecated. For track 2 SDK, we have released [Azure.ResourceManager.ResourceMover](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemover/Azure.ResourceManager.ResourceMover). Please check if it meets your need. [ResourceGroupResourceSettings](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemover/Azure.ResourceManager.ResourceMover/src/Generated/Models/ResourceGroupResourceSettings.cs) may be the model you need to set and you can check the examples in our [tests](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemover/Azure.ResourceManager.ResourceMover/tests/Scenario).
