### ISSUE TITLE
Use dynamic resources for the custom features

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24928]
@maririos:  Do you think that we should consider opening an issue to revisit this in January and if we're still unable to use ephemeral resources go down the [subscription configuration](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/389/Configuring-Tests?anchor=adding-a-new-subscriptionconfiguration) path that Ben recommended in the Python PR?

_Originally posted by @jsquire in https://github.com/Azure/azure-sdk-for-net/pull/24916#discussion_r736546847_

**Comment by pallavit** [comment]
This is duplicate of #25041
