### ISSUE TITLE
[QUERY] TokenCredential vs ServiceClientCredentials

### ISSUE THREAD

**Issue by andrei-faber** [Azure/azure-sdk-for-net#24937]
**Query/Question**
I have a C# function application with a system-assigned managed identity, and I need to use SynapseManagementClient from this app.
I authenticate using DefaultAzureCredential and that's enough to work with services that require TokenCredential (for instance ArmClient), but SynapseManagementClient requires ServiceClientCredentials instead which is not compatible with TokenCredential. How do I convert the credentials?

**Environment:**
Azure.Identity
Azure.ResourceManager
Microsoft.Azure.Management.Synapse

**Comment by sopelt** [comment]
Hi, we also came across this ... it would be nice if all Microsoft.Azure.Management.* libraries could support Azure.Identity.

**Comment by ArthurMa1978** [comment]
Microsoft.Azure.Management.* is track 1 that not support Azure.Identity, and only the new Azure.ResourceManager.* track 2 support.
To Synapse, we will upgrade it to track 2 soon
