### ISSUE TITLE
The command '/azp run prepare-pipelines' failed because of problem of vmImage

### ISSUE THREAD

**Issue by Yao725** [Azure/azure-sdk-for-net#24958]
As here https://github.com/actions/virtual-environments/issues/3287 mentioned, Ubuntu 16.04 environment has been removed from Azure DevOps on October 18, 2021, so the pool vmImage in preparing pipelines maybe need to be specified because the command `/azp run prepare-pipelines` failed recently and the error message showed like below.

![image](https://user-images.githubusercontent.com/65993944/139032119-58f682be-aa52-4315-9cae-0606a357f162.png)

**Comment by kurtzeborn** [comment]
Pretty sure @weshaggard fixed this. He changed the default pool that's used for Ubuntu16 to the Azure Pipelines default image.

Please let us know if you run into this again.
