### ISSUE TITLE
[QUERY] Does ServiceBus AutoDeleteOnIdle deletes DeadLettered Messages?

### ISSUE THREAD

**Issue by hmrc87** [Azure/azure-sdk-for-net#24957]
Does ServiceBus AutoDeleteOnIdle on a Topic delete DeadLettered Messages within a subscription?

**Comment by hmrc87** [comment]
Thanks for this very good explanation. Might be something for the docu?

**Comment by PramodValavala-MSFT** [comment]
@hmrc87 Agreed! The [idleness section](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-expiration#idleness) is the best fit. I've just worked up a PR for it. Waiting on review from the content author. 👍
