### ISSUE TITLE
[BUG]BlobUriBuilder strips trailing slash from blob name, making SDK 11's "directories" unreachable

### ISSUE THREAD

**Issue by Luaancz** [Azure/azure-sdk-for-net#24955]
**Describe the bug**
Trying to access a SDK 11-style directory blob is impossible using e.g. `BlobContainerClient.GetBlobClient`. This goes all the way to `BlobUriBuilder`, which strips the trailing slash from the blob name, resulting in the wrong Uri. Bypassing `BlobUriBuilder` by constructing the Uri manually and using `new BlobClient(new Uri("..."), credentials)` works, but we lose the ability to use the container client configuration.

**Expected behavior**
The Uri for a "directory" blob should have a trailing slash.

**Actual behavior (include Exception or Stack Trace)**
The "directory" blob Uri doesn't have a trailing slash, resulting in a 404 from the service.

**To Reproduce**

1. Create a blob with name like "foo/bar/xyz"
2. Call `BlobContainerClient.GetBlobClient("foo/bar/")`. The client's Uri doesn't contain a trailing slash, and running e.g. `client.Exists()` returns false.

**Environment:**
 - Azure.Storage.Blobs 12.10.0
 - Windows 10, .NET Core 5.0.301
 - Visual Studio 16.10.3

**Comment by jaschrep-msft** [comment]
Hi, @Luaancz. Apologies for such a late response.

Your reproduction steps confuse me. The way you use quotations for "directory" implies to me that you understand that blob containers don't truly have a directory structure, but are just flat listings with names that can be interpreted as such, leading to the concept of a "virtual directory:" a "directory" that exists in theory through names of other blobs, but for which no resource exists.

But then your reproduction steps indicate that you expect such a virtual directory to actually be created on the service; you seem to expect creating the blob `foo/bar/xyz` to create a directory `foo/bar` on the service. Clients in v12 purposefully removed the magic of blob "directories" where there were special objects to interpret them from the other blob resources. While you can still do hierarchical listings, we do not give you clients to obfuscate the actual state of the container.

If I've misunderstood your description, please let me know here.

**Comment by Luaancz** [comment]
@jaschrep-msft Good point! A better description of the steps would be a combination of creating the "directory" structure in SDK 11, and then trying to access the blobs in 12. We still have to support the structures that were created in the old version, and right now, that means using the specified workaround. As soon as you use anything that uses `BlobUriBuilder`, you cannot access blobs that end with a trailing slash - which is how the old "directory" blobs were created, for whatever reason. The internals of the structure are also hidden by the Azure Portal UI, so it's all a bit confusing :D

The main problem with the workaround is that it requires us to pass credentials to places where they really shouldn't be - while the new clients store the credentials they were created with, it's not accessible from the outside (which is a good thing, of course), and there doesn't seem to be a way to avoid `BlobUriBuilder` while also "inheriting" credentials from another client.

**Comment by jaschrep-msft** [comment]
@Luaancz So when using v11, instead of using the `CloudBlobDirectory` functionality, you explicitly created empty blobs where your virtual directories would be, and you used trailing slashes on the names when creating them. And now v12's `BlobUriBuilder` is removing trailing slashes. Is that correct?

**Comment by Luaancz** [comment]
@jaschrep-msft It's quite confusing for me too, since all of this comes from multiple separate codebases (some of which don't even use the .NET Azure SDK), each with their own approach. But the current status of our containers is that there are empty blobs where the virtual directories would be, and they have trailing slashes, yes :D Or to be most exact with what is observable to me, making requests (like GetProperties) against the virtual directories returns actual results when the trailing slash is there, and 404 when it isn't.

**Comment by amishra-dev** [comment]
@Luaancz from your last message its not clear if you still need help. could you kindly confirm

**Comment by Luaancz** [comment]
@amishra-dev  Yes, this is still a problem. No matter how they were created, we have blobs with trailing slashes, and they cannot be easily accessed in v12 SDK.
