### ISSUE TITLE
Update documentation regarding the `HasEvent` property for ProcessEventArgs

### ISSUE THREAD

**Issue by stambunan** [Azure/azure-sdk-for-net#24969]
The documentation for `HasEvent` is slightly confusing and incorrect. It implies that the partition context will be unavailable when the argument doesn't contain an event. However, the `EventProcessorClient` raises an `EmptyPartitionContext` which would provide the partition ID and can be used for logging. https://github.com/Azure/azure-sdk-for-net/blob/52362708d0a68e7ade1d19a032e7db115225d306/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L947

Can we update the documentation so it clarifies this? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ac1ac34-2015-2f18-9904-2de765ce4266
* Version Independent ID: 105bc5ae-cf98-1854-5e1d-eb351cdc3e13
* Content: [ProcessEventArgs Struct (Azure.Messaging.EventHubs.Processor) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.processor.processeventargs?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.EventHubs.Processor/ProcessEventArgs.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.EventHubs.Processor/ProcessEventArgs.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
closed by #25231

**Comment by jsquire** [comment]
These changes have been merged and will flow to the MS Docs site with the next release.
