### ISSUE TITLE
Create sample to highlight KeyResolver from Key Vault for Storage Blobs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#24963]
We received an internal request for a sample showing how to use a Key Vault `KeyResolver` with Storage Blobs, but seems we don't have any currently. Might be better located in Storage, but could see anyone writing it.

/cc @tg-msft @schaabs

**Comment by pallavit** [comment]
@heaths this probably falls in the same bucket as some of the other samples we have which are using multiple services? Should this sample also live there?

Also, not sure if this is still relevant :)

**Comment by heaths** [comment]
It's relevant and should probably move to the Azure-Samples org per my conversation with @jongio.
