### ISSUE TITLE
Possible to list generic resources of a specific type?

### ISSUE THREAD

**Issue by anthony-c-martin** [Azure/azure-sdk-for-net#24979]
I couldn't find any options to list a resource by type. Is this something that is supported by the SDK?

E.g. being able to make the following REST call:
```
GET /{scope}/providers/{provider}/{type}?api-version={version}
```

Or:
```
GET /{scope}/providers/{provider}/{type}/{name}/{childType}?api-version={version}
```

I can see we have the ability to list at resourceGroup scope, which supports filtering, but this doesn't allow you to fetch proxy resources, or children of tracked resources.

Note - I converted this from a discussion (#24682) as it didn't get any traction.

**Comment by Yao725** [comment]
The SDK is generated based on the rest API, so in the generic resource list we only supports to use filter, otherwise you need to use each RP's own package to list the specific resource.
