### ISSUE TITLE
[FEATURE REQ] Metadata on ChatThreadProperties

### ISSUE THREAD

**Issue by GuidoNeele** [Azure/azure-sdk-for-net#24974]
**Library or service name.**
What library or service is this request related to? Azure.Communication.Chat
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

Being able to store metadata on the chat thread just like what's already possible with chat messages.

**Comment by GuidoNeele** [comment]
Any news on this? Would be a nice addition.

**Comment by angiurgiu** [comment]
Thank you for your feedback. We've logged this feature request into our backlog and will consider it in the future.
