### ISSUE TITLE
Enable custom model tests with empty files

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#24995]
Tests that are failing are:
- StartAnalyzeDocumentWithCustomModelCanParseMultipageFormWithBlankPage
- StartAnalyzeDocumentWithCustomModelCanParseBlankPage
- StartAnalyzeDocumentWithCustomModelCanParseDifferentTypeOfForm

Error is:
> {"code":"InternalServerError","message":"An unexpected error occurred.","details":[{"code":"InternalServerError","message":"An unexpected error occurred."}]}

Service team has been informed [here](https://teams.microsoft.com/l/message/19:88f2d9dea2344075b5d4bc34d82a3d1c@thread.skype/1635453806061?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1635453806061&teamName=Azure%20SDK&channelName=Service%20-%20Form%20Recognizer&createdTime=1635453806061)

**Comment by pallavit** [comment]
@kinelski please take a look when you get a chance.

**Comment by kinelski** [comment]
Issue is outdated. These tests have already been re-enabled or are failing for different reasons (tracked by other issues).
