### ISSUE TITLE
Preview ResourceManager Location mixup for Norway

### ISSUE THREAD

**Issue by Jonas-Degn** [Azure/azure-sdk-for-net#25018]
**Describe the bug**
`Azure.ResourceManager.Resources.Models.Location` contains all the public cloud locations, but looking at Norway there seems to be a mixup.
`NorwayWest` is included, but `NorwayWest` is a private location, not public.

**Expected behavior**
`NorwayEast` is expected to be there instead of `NorwayWest`. `NorwayEast` is the public location.

**Environment:** (latest previews as of today 29/10/2021)
 - Azure.ResourceManager 1.0.0-beta.5
 - Azure.ResourceManager.Resources 1.0.0-beta.3

**Comment by ArthurMa1978** [comment]
@fengzhou-msft  please make sure we need to exclude private region in GA

**Comment by ArthurMa1978** [comment]
This is in Azure.Core, make sure we can take back it.

**Comment by fengzhou-msft** [comment]
@m-nash do you know where we get the list for AzureLocation? Based on the code comments, all locations are public, but it seems `NorwayWest` is a private location.

**Comment by ArthurMa1978** [comment]
After a long period of discussion, the final decision is keep it as is in azure.core because it's already there and will response the error if touch this private region.
Thanks @Jonas-Degn for your support and report this issue to us :)
