### ISSUE TITLE
ModuleClient Support in Azure Device Update for IoT Hubs

### ISSUE THREAD

**Issue by sourabhkrishna** [Azure/azure-sdk-for-net#25010]
Currently only Device Identities with modelId as dtmi:AzureDeviceUpdate;1 with ADU Core reported properties are being fetched using the Azure.IoT.DeviceUpdate.DevicesClient GetDevice() method

If a Module Identity with modelId as dtmi:AzureDeviceUpdate;1 is not being fetched using the GetDevice Method.

Getting 404 Not Found if we have a Module Identity for ADU.

Is there a support to Add ModulesClient in the Azure.IoT.DeviceUpdate SDK ?

**Comment by SaurabhSharma-MSFT** [comment]
@sourabhkrishna It looks like a feature request but we are looking into it and get back to you.

**Comment by ValOlson** [comment]
Hi @sourabhkrishna,

It should work if the caller passes “{deviceId}{space}{moduleId}” as device id to the GetDevice () method. Can you try that and let us know if you are still getting only Device Id's returned?

+ @xinanqiu

**Comment by sourabhkrishna** [comment]
@ValOlson thanks. Works fine.

**Comment by SaurabhSharma-MSFT** [comment]
@sourabhkrishna Thanks for the confirmation.  We are closing this issue for now.  Please feel free to open a new issue if you have any other questions.
