### ISSUE TITLE
[Synapse] AddAndRemoveRoleAssignmentSync failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#25013]
Synapse test runs are failing with:

> Error message
> System.InvalidOperationException : Sequence contains no matching element
> 
> Stack trace
>    at System.Linq.ThrowHelper.ThrowNoMatchException()
>    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Azure.Analytics.Synapse.AccessControl.Samples.Sample1_HelloWorld.AddAndRemoveRoleAssignmentSync() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.AccessControl/tests/samples/Sample1_HelloWorld.cs:line 37

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1166378&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Given the age of this issue, closing as stale.  If tests are still failing, please file a new issue.
