### ISSUE TITLE
What does TokenCache Platform data protection mean and what are some cases where it may not be available?

### ISSUE THREAD

**Issue by AshleyAsh90** [Azure/azure-sdk-for-net#25023]
**Query/Question**
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md#allowing-unencrypted-storage
Here it states that 
> By setting UnsafeAllowUnencryptedStorage to true, the credential will encrypt the contents of the token cache before persisting it if data protection is available on the current platform. If platform data protection is unavailable, it will write and read the persisted token data to an unencrypted local file ACL'd to the current account. If UnsafeAllowUnencryptedStorage is false (the default), a CredentialUnavailableException will be raised in the case no data protection is available.

I see that platform data protection means OS level data protection, is that something like DPAPI? And where would some such cases of no data protection arise could you advise?(I guess if it is DPAPI in windows anything below windows 2000 would probably not support encryption)
Do you have any advice on how to handle the cases where no data protection available other than relying on unencrypted text? 

**Environment:**
 - Name and version of the Library package used: [Azure.Identity 1.4.1, 1.5, Microsoft.Identity.Client.Extensions.Msal 2.18.4] 
 - Hosting platform or OS and .NET runtime version ( Windows 10 .NET Framework 4.7.2]
 - IDE and version : [Visual Studio 16.7.2]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @AshleyAsh90 - Are you concerned about a specific scenario where OS data protection is not available? How you choose to handle this case would be totally dependent on your specific needs.

**Comment by AshleyAsh90** [comment]
@christothes I am wondering what would be such a case for setting up a test/solution.

**Comment by christothes** [comment]
Are you asking in which situations would it not be available? One would be if you were running on Linux. I'm not sure if there are scenarios where it could be disabled on Windows as well.

**Comment by AshleyAsh90** [comment]
Ok, yes I was looking for to see if there are general scenarios where such an issue would occur.  Thanks @christothes.
