### ISSUE TITLE
Azure.Messaging.ServiceBus : ServiceBusMessage - support more body types

### ISSUE THREAD

**Issue by dylanmorley** [Azure/azure-sdk-for-net#25036]
**Library or service name.**
Azure.Messaging.ServiceBus
 
**Is your feature request related to a problem? Please describe.**

Currently, the ServiceBusMessage class only supports Data as a body type when performing a clone - it will throw a [NotSupportException on an AMQP 'Value' body type](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusMessage.cs#L68). 

Support the different body type options in the ServiceBusMessage constructor that takes a ServiceBusReceivedMessage parameter. This will allow 'clone and replay' scenarios when working with various messaging technology - particularly, would allow some interop between Mulesoft using ASB as transport and .net tooling. 

Example implementation in the java sdk, https://github.com/Azure/azure-sdk-for-java/blob/78967588a11508d0851646f686a394280697ce67/sdk/servicebus/azure-messaging-servicebus/src/main/java/com/azure/messaging/servicebus/ServiceBusMessage.java#L127

Any reason not to use the AmqpMessageBody.FromValue /  AmqpMessageBody.FromSequence options available for this? I can see there's some memory optimisation around MessageBody.FromReadOnlyMemorySegments for the 'Data' option - would this need to be considered for the additional types?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @dylanmorley,
This was an oversight - it should be possible to construct a ServiceBusMessage from a ServiceBusReceivedMessage that uses a Value or Sequence body type, in addition to the already supported Data body type. We will get this fixed.

**Comment by dylanmorley** [comment]
Amazing, thanks for the speedy turnaround @JoshLove-msft
