### ISSUE TITLE
Incorrect example for connectionString

### ISSUE THREAD

**Issue by mastoj** [Azure/azure-sdk-for-net#25030]
The example usage for connectionString seems to be wrong, the example used is the one that separates the host and the secret and not one connectionString.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 181b236e-e273-f74a-127b-3272c9503509
* Version Independent ID: 55f2e104-b76d-84a0-f474-bb63bde139fe
* Content: [CosmosClient Constructor (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclient.-ctor?view=azure-dotnet#Microsoft_Azure_Cosmos_CosmosClient__ctor_System_String_Microsoft_Azure_Cosmos_CosmosClientOptions_)
* Content Source: [xml/Microsoft.Azure.Cosmos/CosmosClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/CosmosClient.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by KalyanChanumolu-MSFT** [comment]
@mastoj Thank you for reporting this issue. We are investigating and will get back to you soon.

**Comment by KalyanChanumolu-MSFT** [comment]
@mastoj Thank you for taking the time to report this issue.
You are right. Format of the connection string needs to be updated.
We are routing this issue to the appropriate team.

**Comment by navba-MSFT** [comment]
@mastoj Apologies for the late reply. Thanks for reporting this issue and sharing the feedback. This PR https://github.com/Azure/azure-sdk-for-net/issues/25030 has been filed and it is merged after review. This should address the issue in the next release. With that we will proceed with closure of this issue. If you have any questions on this issue in future, please feel free to reopen this issue. We would be happy to help.
