### ISSUE TITLE
[QUERY] Form Recognizer custom models and JSON

### ISSUE THREAD

**Issue by biswajitsamal59** [Azure/azure-sdk-for-net#25034]
**Query/Question**
I am using Azure Form Recognizer custom model to extract line and table data from PDF files. For few scenarios it's not able to extract all the rows of a table (i.e. If a table contains 20 rows, it's extracting 19 rows and not able to extract last one). Is there any way so that I can compare extracted json values and file content to check if Form Recognizer is not able to extract all the rows.  

**Environment:**
 - Name and version of the Library package used: Azure.AI.FormRecognizer 3.1.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 and .NET 5
 - IDE and version : Microsoft Visual Studio Community 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by biswajitsamal59** [comment]
@jsquire @kinelski Can you please help me this issue.

**Comment by maririos** [comment]
Hi @biswajitsamal59 .

Curious, how are you training your data? Are you using the Labeling tool? or the SDK for it?

**Comment by biswajitsamal59** [comment]
> Hi @biswajitsamal59 .
> 
> Curious, how are you training your data? Are you using the Labeling tool? or the SDK for it?

Using Labeling tool to train custom model (fott-2-1.azurewebsites.net).

**Comment by maririos** [comment]
Great. So a good way to test that analyzing the custom model is returning what you want is to use the tool to Analyze a new document using your custom model. There is a button where you can download the JSON and see if all the information you need is there.

Let us know if that helps

**Comment by biswajitsamal59** [comment]
> Great. So a good way to test that analyzing the custom model is returning what you want is to use the tool to Analyze a new document using your custom model. There is a button where you can download the JSON and see if all the information you need is there.
> 
> Let us know if that helps

I have checked that. The PDF file contains a table with 1 header row and 20 data rows. But the downloaded JSON file contains table with 1 header and 19 data rows. Even the Form Recogniser Layout service giving same result (Without using custom model only analysing using Layout service).

**Comment by maririos** [comment]
Thanks for the confirmation. Apologies this is happening.

Tagging the service team for assistance here @Nhaiby @ramparab @ChrisHMSFT

**Comment by anrothMSFT** [comment]
I'm not the current owner for this issue, but I've sent mail to track down who is and will point them to this thread.

**Comment by sanjeev3** [comment]
Thanks @anrothMSFT! @biswajitsamal59 - Layout sometimes can miss the last row from the table. It's a known issue that we have been working on. Can you please try with the latest preview and the corresponding 4.0 SDK library at https://www.nuget.org/packages/Azure.AI.FormRecognizer/4.0.0-beta.1? The C# QuickStart for the new preview is at https://docs.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/quickstarts/try-v3-csharp-sdk.

**Comment by sanjeev3** [comment]
@biswajitsamal59 - In addition to my previous comment, are you able to share the document by attaching it to this thread?

**Comment by biswajitsamal59** [comment]
> @biswajitsamal59 - In addition to my previous comment, are you able to share the document by attaching it to this thread?

I have tried with 4.0.0-beta.1 SDK, getting the same response. I am extremely sorry, I can't share the file as it has some sensitive information,

**Comment by kinelski** [comment]
> I have tried with 4.0.0-beta.1 SDK, getting the same response. I am extremely sorry, I can't share the file as it has some sensitive information,

@biswajitsamal59 If you're still facing this issue, could you try the latest SDK version (4.0.0-beta.3)? This was a known issue that is believed to be fixed now.

You need to use the new `DocumentAnalysisClient` in order to target the newest service version. If you're still using the old `FormRecognizerClient`, we have a migration guide that could help you: [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/MigrationGuide.md).
