### ISSUE TITLE
Microsoft.Hadoop.Avro.Tools code generation not converting Avro doc strings to XML comments

### ISSUE THREAD

**Issue by aaron-comyn** [Azure/azure-sdk-for-net#2504]
Avro schemas can be documented with "doc" fields in their schema definitions.

The Apache.Avro code generator uses these "doc" fields as the XML comments on generated properties, but they are ignored by the Microsoft.Hadoop.Avro.Utils.CodeGenerator.

Example:

```
...
{
  "name": "title",
  "type": "string",
  "doc": "The title of the position",
  "default": "-"
} ...
```

Current output:

```
    /// <summary>
    /// Gets or sets the title field.
    /// </summary>
    [DataMember]
    public string title { get; set; }
```

Expected output:

```
    /// <summary>
    /// The title of the position
    /// </summary>
    [DataMember]
    public string title { get; set; }
```

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.
