### ISSUE TITLE
Use a dynamic resource for our live tests

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#25041]
Currently, we are using a persistent resource because we are still working with the service team on how to dynamically train the custom models and consume them from any resource created under our subscription.
Once the service provides us with the right APIs and gives us the green light, we should go back to dynamic resources.

**Comment by maririos** [comment]
Related to #24928

**Comment by pallavit** [comment]
@joseharriaga I believe you mentioned exploring this as part of the current preview release so not sure if this can be closed.
