### ISSUE TITLE
[LLC] Design serialization for LLC models s.t. it addresses broader issues

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#25045]
Related issues:
- https://github.com/Azure/azure-sdk-for-net/issues/21982
- https://github.com/Azure/azure-sdk-for-net/issues/25699
- https://github.com/Azure/azure-sdk-for-net/issues/14940#issuecomment-859701729

**Comment by annelo-msft** [comment]
@maririos @tg-msft @KrzysztofCwalina FYI

**Comment by annelo-msft** [comment]
Hi @DBojsen - yes, we are making progress on it, although I don't have an answer for you just yet on what the outcome will be.  One thing that is different from when we initially corresponded about this is that I am now confident that we will be able to expose serialization capabilities publicly.  We are working on the details in a way we can solve the problem holistically for the SDK, which is why there's a greater investment of time needed.  Thanks!

**Comment by rquackenbush** [comment]
Hi @annelo-msft - I've just run into the same roadblock. Any updates?
Thanks

**Comment by DBojsen** [comment]
> Hi @annelo-msft - I've just run into the same roadblock. Any updates?
> Thanks

Hi rquackwnbush

I solved my issue for the time being by using reflection. Perhaps that will work for you also?!

BR David

**Comment by pallavit** [comment]
@annelo-msft I am assuming this issue is getting resolved as part of the model reader writer support. 
/cc: @m-nash 

Please feel free to reopen if you think that is not the case.

**Comment by annelo-msft** [comment]
The goal of this issue was to track the various model serialization issues in one place so that when we provided a solution they would all be addressed with one set of types.  I assume @m-nash was aware of the design requirements and has been using them in the serialization work.

**Comment by annelo-msft** [comment]
I believe this has been addressed with the new `IPersistableModel<T>` interfaces in System.ClientModel v1.0.0
