### ISSUE TITLE
Create a TextAnalyticsProject bag containing the ProjectName and DeploymentName

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#25056]
To be consistent with Question Answering and Conversations SDKs, we should have a class dedicated to holding the Text Analytics project's ProjectName and DeploymentName. See [QuestionAnsweringProject](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/src/QuestionAnsweringProject.cs) for reference.

Note: Name and design proposal to be discussed with v-team

**Comment by heaths** [comment]
This was added for the Language unification effort, but more recently the concept has more or less be deprecated. We may want to revisit this. /cc @kristapratico

**Comment by heaths** [comment]
Moving to backlog. We didn't do this for CLU afterall with the new DPG principals.

**Comment by pallavit** [comment]
@heaths , @kristapratico since DPG follows a new principles is it still worth tracking this one? Or can we close this?

**Comment by heaths** [comment]
I don't think this is worth keeping. It doesn't add much value other than some slight consistency, and DPG models will present some new possibilities.
