### ISSUE TITLE
[QUERY] Can we get InstanceId for app service workers

### ISSUE THREAD

**Issue by cylin2000** [Azure/azure-sdk-for-net#25069]
**Query/Question**
How can we help?
1. we can use https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/list-instance-identifiers to get the instance Id for the workers
2. but when we use SDK, webSiteManagementClient.WebApps.ListInstanceIdentifiersAsync can't get the correct instance Id
![image](https://user-images.githubusercontent.com/2646632/139779381-4e77d95e-eabe-4484-95c7-4886fbd6b9b3.png)

Our customer want to get the instance id from SDK, would you help, thanks.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.Fluent 1.38.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
 .NET SDK (reflecting any global.json):
 Version:   5.0.208
 Commit:    d21a38d788

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.208\

Host (useful for support):
  Version: 5.0.11
  Commit:  f431858f8b

.NET SDKs installed:
  3.1.414 [C:\Program Files\dotnet\sdk]
  5.0.208 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
 - IDE and version : [e.g. Visual Studio 16.9.12]

**Comment by cylin2000** [comment]
The API returned machineName is like following , but SDK didn't return same information
![image](https://user-images.githubusercontent.com/2646632/139780563-e99c08ad-6c83-4c9d-8980-d917b40d6136.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
Hi，
For the issue you proposed, I may need to contact the appservice team to make a modification to their swagger, add the "machineName" data field you need, and regenerate a new SDK to solve this problem.
