### ISSUE TITLE
Application Insights:  Typo in "Returns" section

### ISSUE THREAD

**Issue by normand-MSFT** [Azure/azure-sdk-for-net#25061]
Definition of the Metric return value has a typo.

"A metric witht he specified identify and configuration."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc52e4dc-d9b3-bf24-87d3-2b0b4698c28c
* Version Independent ID: bb3311c7-dddd-9651-eb1f-bfab617f8c72
* Content: [MetricsCollection.GetOrCreate(MetricIdentifier, MetricConfiguration) Method (Microsoft.ApplicationInsights.Metrics) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.metrics.metricscollection.getorcreate?view=azure-dotnet)
* Content Source: [xml/Microsoft.ApplicationInsights.Metrics/MetricsCollection.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights.Metrics/MetricsCollection.xml)
* Service: **application-insights**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Karishma-Tiwari-MSFT** [comment]
I have created a PR to update the documentation. 
https://github.com/microsoft/ApplicationInsights-dotnet/issues/2469

Thanks for bringing this to our attention. We will now close this issue. If there are further questions regarding this matter, please tag me in a comment. I will reopen it and we will gladly continue the discussion.
