### ISSUE TITLE
MS internal documentation link in a public article

### ISSUE THREAD

**Issue by vkornov** [Azure/azure-sdk-for-net#25079]
This article contains a link https://aka.ms/msal-net-sni that leads to MS internal documentation.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.acquiretokenonbehalfofparameterbuilder.withsendx5c?view=azure-dotnet

![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/251923/139855084-3232cc38-2b55-49be-873d-d41b610ab5fb.png)

https://aadwiki.windows-int.net/index.php?title=Subject_Name_and_Issuer_Authentication#Third_party_Applications

![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/251923/139855266-281bb67e-5a59-4c65-8216-1760f40ec695.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59bb4ceb-83f6-bde0-35aa-87f4cb9a3253
* Version Independent ID: d8e2feca-4e24-7466-d484-6e0a00b95c47
* Content: [AcquireTokenOnBehalfOfParameterBuilder.WithSendX5C(Boolean) Method (Microsoft.Identity.Client) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.acquiretokenonbehalfofparameterbuilder.withsendx5c?view=azure-dotnet)
* Content Source: [xml/Microsoft.Identity.Client/AcquireTokenOnBehalfOfParameterBuilder.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Client/AcquireTokenOnBehalfOfParameterBuilder.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Identity.Client` package is maintained as [#2986](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2986).
