### ISSUE TITLE
[QUERY] Replacement for Alert.ActionTaken in latest version

### ISSUE THREAD

**Issue by vaibhav29498** [Azure/azure-sdk-for-net#25072]
**Query/Question**
We are currently updating the `Microsoft.Azure.Management.SecurityCenter` package from `2.1.0` to `3.0.0`. The `Microsoft.Azure.Management.Security.Models.Alert` class no longer has the `ActionTaken` property. Is there any way to retrieve this property in the latest version?

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.SecurityCenter 3.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Core 5.0.303
 - IDE and version : Visual Studio 16.10.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment]
The `ActionTaken` property of  `Microsoft.Azure.Management.Security.Models.Alert` has been removed in the [latest version](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/security/resource-manager/Microsoft.Security/stable/2020-01-01/alerts.json#L599).

This question will be routed to the service team.
