### ISSUE TITLE
[QUERY] BlockBlobClient.OpenWrite in v12, ETag issue

### ISSUE THREAD

**Issue by michaelbrichko** [Azure/azure-sdk-for-net#25077]
Hi,

We are migrating from one of the previous azure blob SDKs and I want to use OpenWrite method for writing stream to azure blob storage. Previously I was able to do so and the ETag of just written stream was inside the properties of the client whereas now it seems that I must issue a separate network call to retrieve the ETag. Is that so ?
Moreover, in order to know the ETag of just written stream, it seems that I must download just written stream with it's properties\etag and if the content hasn't changed, then I know its etag.

What's the correct way to know the etag of the stream that was written to blob storage using OpenWrite method ?

Thanks !

**Comment by amnguye** [comment]
We will look into adding this functionality gap for OpenWrite.
