### ISSUE TITLE
[BUG] Constants.DefaultMsalTokenCacheDirectory does not properly resolve in IIS

### ISSUE THREAD

**Issue by jlocke427** [Azure/azure-sdk-for-net#25098]
**Describe the bug**
While running our ASP.NET application we are seeing the following error because the Constants.DefaultMsalTokenCacheDirectory cannot be resolved

We found that when the TokenCaching is resolving Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData) in https://github.com/Azure/azure-sdk-for-net/blob/4c7620883b5d8dda86b0e466928f4efcc8980ff7/sdk/identity/Azure.Identity/src/Constants.cs it is unable to resolve the path and returns an empty string if the Application Pool setting in IIS called "Load User Profile" is set to False. 

**Expected behavior**
Expected behavior would be to resolve another path (or use a temp directory) instead of returning an invalid path for the Token Caching.

**Actual behavior (include Exception or Stack Trace)**
When Adding the TokenCachePersistenceOptions to our TokenCredential objects (ClientSecretCredentialOptions, ClientCertificateCredentialOptions, etc) our application fails to resolve a path to persist the Tokens. 

The following error is thrown.
Azure.Identity.AuthenticationFailedException: ClientCertificateCredential authentication failed: Access to the path '.IdentityService' is denied. ---> System.UnauthorizedAccessException: Access to the path '.IdentityService' is denied.
...
...

**To Reproduce**
In order to reproduce you need to host an ASP.NET application you can create a TokenCredential Object that accepts an TokenCachePersistenceOptions and set "Load User Profile" to false and then the Constant that is used cannot resolve the correct path

1. Here we see the result of the LocalApplicationData when the Load User Profile is set to true
![image](https://user-images.githubusercontent.com/19756608/139970260-1658657c-7cca-415e-bafe-7cba8cf14282.png)
2. Here we see the result of the LocalApplicationData when the Load User Profile is set to false
![image](https://user-images.githubusercontent.com/19756608/139970748-0d90d2eb-8932-4d25-9159-17c0280494ce.png)

**Environment:**
 - Azure.Identity 1.4.1
 - Windows Server 2019 64-Bit. .NET Framework 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Addressed offline
