### ISSUE TITLE
[BUG] IVirtualMachineScaleSetsOperations BeginUpdate and Update have the same description

### ISSUE THREAD

**Issue by C-Ross** [Azure/azure-sdk-for-net#25104]
**Describe the bug**
 [IVirtualMachineScaleSetsOperations.BeginUpdateWithHttpMessagesAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.ivirtualmachinescalesetsoperations.beginupdatewithhttpmessagesasync?view=azure-dotnet) and [IVirtualMachineScaleSetsOperations.UpdateWithHttpMessagesAsync ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.ivirtualmachinescalesetsoperations.updatewithhttpmessagesasync?view=azure-dotnet), as well as all of the related methods on [VirtualMachineScaleSetsOperationsExtensions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.virtualmachinescalesetsoperationsextensions?view=azure-dotnet) have the same description

> Update a VM scale set.

**Expected behavior**
The documentation should differentiate the behavior of the two calls, where `BeginUpdate` only changes the definition of the Vmss resource, but `Update` also attempts to apply that to VMs and wait for them to come to a healthy state.

**Actual behavior (include Exception or Stack Trace)**
N/A Doc bug

**To Reproduce**
N/A Doc Bug

**Environment:**
- Microsoft.Azure.Management.Compute
- Web documentation (links above) and embedded documentation.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by C-Ross** [comment]
Makes sense, especially since its deprecated.  FYI your automation didn't actually close the issue.
