### ISSUE TITLE
Delete throws error if secret doesn't exist

### ISSUE THREAD

**Issue by lukos** [Azure/azure-sdk-for-net#25125]
It is not clear how to delete a secret that might not exist. In most cases, I would definitely expect the default behaviour not to throw an exception if the secret does not exist but at worst, there should be an overload that allows us to ignore the error. Throwing an error means that for every delete, I either need to call GetSecret first or catch and ignore the exception which is nasty.

Also, the link to log a problem about "This Product" is broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b378d7c-6191-9f15-6c34-30c4bfbcb5a5
* Version Independent ID: 3fafa4d7-15a9-82dc-669a-f9e3b61a9065
* Content: [SecretClient.StartDeleteSecretAsync(String, CancellationToken) Method (Azure.Security.KeyVault.Secrets) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.secrets.secretclient.startdeletesecretasync?view=azure-dotnet#Azure_Security_KeyVault_Secrets_SecretClient_StartDeleteSecretAsync_System_String_System_Threading_CancellationToken_)
* Content Source: [xml/Azure.Security.KeyVault.Secrets/SecretClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Security.KeyVault.Secrets/SecretClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
@rloutlaw could you look into the "This Product" link at the bottom. It's 404'ing.

**Comment by heaths** [comment]
As for the change request, we could add a `DeleteIfExists` like we've done in other libraries including Storage. Newer libraries [shouldn't throw on delete by default](https://azure.github.io/azure-sdk/dotnet_introduction.html#:~:text=Deletes%20one%20or%20more%20resources%2C%20or%20no%2Dop%20if%20the%20resources%20do%20not%20exist.), but the pattern wasn't established for older ones.

That said, we are working on some new features we could take advantage of instead, but are not yet available - should be early next year. We can't change the existing method behavior, though, as that would be a breaking change.

**Comment by heaths** [comment]
Note to self: we'd want to specifically handle the case where the initial delete request already 404'd e.g., [here](https://github.com/Azure/azure-sdk-for-net/blob/4980a8a68fb70fefca0aa4cf50ff58bfdf3a5c5f/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/DeleteSecretOperation.cs#L30-L34). Could also do it in the caller but would then have to duplicate. If we don't mark the operation already-completed, `UpdateStatus()` would effectively run forever.

**Comment by pallavit** [comment]
@heaths I was looking at the following thread #25626 and looks like all the foundational pieces for it are there. Can this be done for KV now?

**Comment by annelo-msft** [comment]
I would weigh in for consistency with Tables and add a `DeleteIfExists()` method.
