### ISSUE TITLE
Error upgrading to Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0

### ISSUE THREAD

**Issue by adeliab** [Azure/azure-sdk-for-net#25126]
**Query/Question**
We have Azure Durable Function with session based service bus trigger. I upgraded the Microsoft.Azure.WebJobs.Extensions.ServiceBus package from 4.3.0 to 5.0.0

After the upgrade, the function won't start with this error:
```
Microsoft.Azure.Functions.Extensions: Method not found: 'Microsoft.Extensions.Configuration.IConfigurationBuilder Microsoft.Azure.WebJobs.Hosting.IWebJobsConfigurationBuilder.get_ConfigurationBuilder()'.
Value cannot be null. (Parameter 'provider')
```

Do I need to install/ upgrade additional package?

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): CoreTools 3.0.3734 32 bit, function in .NET Core 3.1
 - IDE and version : Visual Studio Version 16.11.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
This looks similar to https://github.com/Azure/azure-webjobs-sdk/issues/2059

**Comment by JoshLove-msft** [comment]
Can you try the workaround mentioned in https://github.com/Azure/azure-webjobs-sdk/issues/2059#issuecomment-448769239

**Comment by JoshLove-msft** [comment]
I haven't been able to repro this. Can you include the contents of your functions csproj?
Also, just to confirm, you are hitting this error locally when running from VS?

**Comment by JoshLove-msft** [comment]
@adeliab, I haven't been able to repro the error. Are you still experiencing the issue?
