### ISSUE TITLE
[QUERY] How to configure DataProtection ProtectKeysWithAzureKeyVault

### ISSUE THREAD

**Issue by barozi** [Azure/azure-sdk-for-net#25123]
Hello,
I am using the DataProtection ProtectKeysWithAzureKeyVault. The configuration of _keyIdentifier_ is provided from separate settings service registered earlier. So here is an issue. There is no `*Options` class which I could use to inject the setting into `ProtectKeysWithAzureKeyVault()`

Unfortunately in my scenario, I cannot use the `Configuration` class and also cannot (and do not want to) use `service.BuildServiceProvider();`

I thought I could so something like this:

```csharp
            services.AddOptions<KeyManagementOptions>()
                .Configure<IAppSettings>((_opt, settings) =>
                {
                    _opt.XmlEncryptor = new AzureKeyVaultXmlEncryptor(
                              settings.Get("AKV.KeyProtection"),
                              new KeyResolver(new DefaultAzureCredential()));
                });
```
but unfortunately the `AzureKeyVaultXmlEncryptor` is internal and cannot do it from my code. 

Do you have any idea how could I do this ?

**Environment:**
 - Azure.Extensions.AspNetCore.DataProtection.Keys 1.1.0
 - Azure Cluster Service
 - Visual Studio 16.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Unfortunately, there is no way to implement this right now.

**Comment by jviau** [comment]
I also was looking at how to do this and I figured a way to work around it. Basically, you can use `ActivatorUtilities` to re-construct their implementation without needing to know what it is. Like so:

``` CSharp
services.AddDataProtection()
    .ProtectKeysWithAzureKeyVault(new Uri("https://placeholder.test"), NoOpTokenCredential.Instance)
    .InjectKeyVaultDependencies();
.
.
.
.

private static IDataProtectionBuilder InjectKeyVaultDependencies(this IDataProtectionBuilder builder)
{
    builder.Services.Replace(ServiceDescriptor.Singleton<IKeyEncryptionKeyResolver>(sp =>
    {
        // replace the KeyResolve implementation here.
        return new KeyResolver(/* add credentials and client options */l);
    }));

    builder.Services.AddOptions<KeyManagementOptions>()
        .Configure<IServiceProvider,>((opt, sp) =>
        {
            string key = ""; // get your key into here however you want: IConfiguration or whatever.

            // Internal type. Lets let activator handle re-constructing it.
            // https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Keys/src/AzureKeyVaultXmlEncryptor.cs
            Type type = opt.XmlEncryptor.GetType();
            opt.XmlEncryptor = (IXmlEncryptor)ActivatorUtilities.CreateInstance(sp, type, key);
        });
}
```

**Comment by pallavit** [comment]
@jsquire do you think this is still an issue?

**Comment by jsquire** [comment]
@pallavit:  It's a corner case and we haven't seen a lot of demand, but it would also be a very low effort change to make the type public.  Seeing as we've made no changes the API in several years, I don't see a reason to not do so.   Let's keep this one open.

@AlexanderSher:  Let's discuss with the architects.  We've had prior discussions about opening up some of the internal extensions types, I don't think we'll see major concerns raised here.

**Comment by AlexanderSher** [comment]
@pallavit @jsquire We now have an extension method that support factory for token credential, so we may try to go without making these types public: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Keys/src/AzureDataProtectionKeyVaultKeyBuilderExtensions.cs#L94

@barozi, can you give a bit more details about this:

> also cannot (and do not want to) use service.BuildServiceProvider();

`Configure<IAppSettings>` requires `ServiceBuilder` to resolve `IAppSettings` instance:
https://github.com/dotnet/runtime/blob/093fdabc28310bc8f60fcaecbcbf38a59d878056/src/libraries/Microsoft.Extensions.Options/src/OptionsBuilder.cs#L61-L69

So I don't understand how configuring options would help.

**Comment by barozi** [comment]
I didn't wanted to invoke `service.BuildServiceProvider();` manually as it have read that it is not recommended. Probably I must have misunderstood the way the Configure works in that case. Thanks for all. I was able to resolve the issue with @jviau recommendation. I will check also solution  with factory, but I think the issue can be Closed
