### ISSUE TITLE
BlobClientOptions for BlobClient and BlobLeaseClient

### ISSUE THREAD

**Issue by vrozovmicrosoft** [Azure/azure-sdk-for-net#25129]
BlobContainerClient class may get BlobClientOptions in the constructor.
Assume we created BlobContainerClient instance with some BlobClientOptions.
- Will BlobClient created from BlobContainerClient instance (using GetBlobClient()) have the same options applied?
- Will BlobLeaseClient created from BlobClient instance (using new BlobLeaseClient(BlobClient) have the same options applied?

Azure SDK V12

**Comment by SaurabhSharma-MSFT** [comment]
@vrozovmicrosoft Thanks for your ask.  We are looking into it and get back to you.

**Comment by amnguye** [comment]
Yes the `BlobClientOptions` get passed from the `BlobContainerClient`  to the `BlobClient` when using `GetBlobClient`
as well as the same for `BlobClient` to the `BlobLeaseClient` when using `new BlobLeaseClient(BlobClient) `
