### ISSUE TITLE
[BUG] Memory leak - Memory being filled with CancellationTokenSource objects

### ISSUE THREAD

**Issue by stockmansy** [Azure/azure-sdk-for-net#25131]
**Describe the bug**
While developing locally I've encountered a bug where my memory gets filled by CancellationTokenSource objects.
![image](https://user-images.githubusercontent.com/483904/140379069-3f1b9452-5b74-4bcc-9535-3e069629b987.png)

This happens when trying to make use of azure servicebus configured as such:
![image](https://user-images.githubusercontent.com/483904/140379366-a4bfd8e0-1859-40e2-be69-17611857c0eb.png)

The key to triggering the bug seems to be setting the MaxConcurrentSessions to lower than the default.
The bug happens after sending a second message to the message processor.
(The message processor is currently an empty method, no logic in there)

**Expected behavior**
Messages get processed as expected, without a memory leak

**Actual behavior (include Exception or Stack Trace)**
Memory gets filled with CancellationTokenSource objects. I've had up to 10 GB of objects in memory after only 30 seconds when there is actual logic in the message handler. 

**To Reproduce**
1. Configure the servicebus processor with the setting MaxConcurrentSessions = 1
2. Receive a message
3. Receive another message
4. Briefly wait (the bug occurred usually within the next minute)

![image](https://user-images.githubusercontent.com/483904/140380633-2212b3aa-1694-4936-a45f-eaa76f958acb.png)
^ Shows me triggering the bug twice in a row.

**Environment:**
 - azure.messaging.servicebus 7.4.0
 - Windows 10.0.19042
 - .NET SDK 5.0.401
 - .NET Core 3.1
 -  Visual studio professional 2019 Version 16.11.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @stockmansy,
I just did a quick test for this and couldn't repro what you are seeing. Any chance you can include a minimal repro that I can run?

**Comment by JoshLove-msft** [comment]
This does look suspicious - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs#L777

We only dispose these after exiting the while loop.

**Comment by stockmansy** [comment]
Thank you for looking into it!

I looked into a simple repro and was able to reproduce it slightly (it went from 40 mB to 60mB) with the following code:
(I put breakpoints in the message handler, and after the last breakpoint got hit, I saw it increase. The snapshot showed a large amount of cancellationtokensource objects again.)
```
  using Azure.Messaging.ServiceBus;
  using Microsoft.AspNetCore.Hosting;
  using Microsoft.Extensions.Hosting;
  using System.Text;
  using System.Text.Json;
  using System.Threading.Tasks;
  
  namespace MemoryBugRepro
  {
      public class Program
      {
          public static async Task Main(string[] args)
          {
              var options = new ServiceBusSessionProcessorOptions
              {
                  MaxConcurrentSessions = 1,
                  MaxConcurrentCallsPerSession = 2,
              };
  
              var endPoint = "Endpoint=sb://ENDPOINTHERE";
              var queue = "QUEUENAME";
  
              var serviceBusClient = new ServiceBusClient(endPoint, new ServiceBusClientOptions
              {
                  RetryOptions = new ServiceBusRetryOptions
                  {
                      Mode = ServiceBusRetryMode.Exponential
                  }
              });
  
              await using var processor = serviceBusClient.CreateSessionProcessor(queue, options);
  
              processor.ProcessMessageAsync += MessageProccessAsync;
              processor.ProcessErrorAsync += ErrorProccessAsync;
  
              await processor.StartProcessingAsync();
  
              var message = new { Test = "Test" };
  
              var sender = serviceBusClient.CreateSender(queue);
  
              var messageBytes = Encoding.UTF8.GetBytes(JsonSerializer.Serialize(message));
              var msg = new ServiceBusMessage(messageBytes);
              msg.Subject = "Some test";
              msg.SessionId = "SomeSessionId";
  
              await sender.SendMessageAsync(msg);
  
              await Task.Delay(50000);
  
              await sender.SendMessageAsync(msg);
  
              await Task.Delay(50000);
  
              CreateHostBuilder(args).Build().Run();
          }
  
          public static IHostBuilder CreateHostBuilder(string[] args) =>
              Host.CreateDefaultBuilder(args)
                  .ConfigureWebHostDefaults(webBuilder =>
                  {
                      webBuilder.UseStartup<Startup>();
                  });
  
          private static Task MessageProccessAsync(ProcessSessionMessageEventArgs args)
          {
              return Task.CompletedTask;
          }
  
          public static Task ErrorProccessAsync(ProcessErrorEventArgs args)
          {
              return Task.CompletedTask;
          }
      }
  }
```

**Comment by JoshLove-msft** [comment]
Thanks @stockmansy - I was able to repro it on my side as well. While the number of allocated cancellation token sources is expected to grow over time, they should be getting garbage collected in a timely manner. After making the fix to Dispose these, I observed the numbers growing over time, but then dropping back down to a baseline after being garbage collected. Prior to the change, the allocations would just keep growing.

**Comment by TomaszSynak** [comment]
@JoshLove-msft I'm suffering from exact same issue now 😨 My app is going bananas with RAM reaching 27 GB on production environment 😟 I'm facing same case when debugging the app locally, seeing the RAM reaching > 2 GB just after ~2-3 minutes from the start. When can we expect newest version of `Azure.Messaging.ServiceBus` containing this fix, to be released ? 🙄

![image](https://user-images.githubusercontent.com/5030440/141181345-e600c9b8-1055-499e-b3cc-03a58b233307.png)

🔧 🛠️ Hint. the temporary workaround to this issue is to **not** set either `MaxConcurrentSessions` or `MaxConcurrentCallsPerSession` - just keep the default values without defining them.

**Comment by JoshLove-msft** [comment]
It will be released today!
