### ISSUE TITLE
SessionLockLostException in service bus trigger function

### ISSUE THREAD

**Issue by adeliab** [Azure/azure-sdk-for-net#25130]
**Query/Question**
We're getting a lot of SessionLockLostException - Message processing error (Action=Complete, xxx
We have a service bus triggered durable function. There are 2 issues:
- the start of the orchestrator is taking too long
- because of that, when the function tries to complete/ abandon the message, we get the SessionLockLostException

There's little documentation on what we can do when we get this exception in service bus trigger Azure function.
- How can we correctly complete/ abandon session based message in azure function?
- Is there a way to increase the session lock timeout?

Our function signature is like this:
public async Task Run([DurableClient] IDurableOrchestrationClient starter,
            [ServiceBusTrigger(topicName: "xxx", subscriptionName: "xxx", Connection = "xxx", IsSessionsEnabled = true)] Message message, MessageReceiver messageReceiver)

I thought upgrading the extension might help, but I got this error https://github.com/Azure/azure-sdk-for-net/issues/25126

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.3.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET Core 3.1, Function runtime ~3.0
 - IDE and version : Visual Studio Version 16.11.5 - the issue doesn't happen locally but in Azure

**Comment by adeliab** [comment]
And another question, when does a trigger function acquires & release session lock?

**Comment by SaurabhSharma-MSFT** [comment]
@ahmedelnably, @fabiocav Any suggestions on this.

**Comment by jsquire** [comment]
This appears to be related to an older version of the extensions package which used `Microsoft.Azure.ServiceBus` as part of its infrastructure, which is now deprecated and receiving only critical security and bug fixes.  With respect to lock duration and renewal - the base duration is set on the Service Bus entity when it is created.   Starting in v5.0 of the extensions package, the maximum renewal duration can be set using the [host.json](https://learn.microsoft.com/azure/azure-functions/functions-bindings-service-bus?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#hostjson-settings) property `maxAutoLockRenewalDuration`.

As the orchestrator behavior was addressed in a linked issue, I'm going to close this out.
