### ISSUE TITLE
[QUERY] Using interactivebrowserauthentication from service application doesn't popup the system browser. Is this expected behavior?

### ISSUE THREAD

**Issue by AshleyAsh90** [Azure/azure-sdk-for-net#25166]
**Query/Question**
Using interactivebrowserauthentication from service application to trigger login doesn't popup the system browser. It fails with an exception
```
 InteractiveBrowserCredential authentication failed: Showing a modal dialog box or form when the application is not running in UserInteractive mode is not a valid operation. Specify the ServiceNotification or DefaultDesktopOnly style to display a notification from a service application.,   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
    at Azure.Identity.InteractiveBrowserCredential.<AuthenticateImplAsync>d__30.MoveNext()
```
Is this expected for a service application? I thought since it pops up the browser it should work fine. It worked in debug, but fails in service when called. 

**Environment:**
 - Name and version of the Library package used:Azure.Identity 1.4.1
 - Hosting platform or OS and .NET runtime version [Windows 10 .NET Framework 4.7.2]
 - Visual Studio Version 16.7.2

**Comment by AshleyAsh90** [comment]
Closing this since it is supposed to be this way. Sevices don't have ui support hence the issue.

**Comment by Trivedi-Ashish** [comment]
@AshleyAsh90
hi, I have an ASP.NET core application in which I am trying to get browser pop-up to allow user interactively select account.
I am calling InteractiveBrowserCredential.GetToken(). 
It works in debug mode but when I deploy the application in IIS, it doesn't pops up the browser.

I am wondering if InteractiveBrowserCredential in Azure SDK for .NET is only for WPF, Winform applications?
Is there any way to use it in ASP.NET applications as well?
