### ISSUE TITLE
Board Review (bug report): Azure.Storage.Blobs - CEST/CET timezone change - ConditionNotMet

### ISSUE THREAD

**Issue by markusdresch** [Azure/azure-sdk-for-net#25165]
not sure if this is the right place, but you probably should provide a place for general bug reports / support issues.

## About the client library

* Name of the client library: Azure.Storage.Blobs
* Languages for this review: C#

starting this week we had troubles with Azure.Storage.Blob nuget and streaming to BlockBlobClient.OpenWriteAsync streams, receiving error messages like this one:

```
<?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met. | <?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met.
...
```

logging the issue, the logs show that there are conditions in the headers like this one: 

> "conditionsUsed":"If-Match=Friday, 05-Nov-21 09:20:26 GMT"

with a result "ConditionNotMet"

this seems to be a problem with the change from summer time to winter time, since last weekend time was changed from CEST to CET and we didn't have this problem before. no additional headers were sent, only using the latest stable nuget version (12.10.0).

code to reproduce:

```
var blob = Container.GetBlockBlobClient("...");

using var stream = await blob.OpenWriteAsync(true, new BlockBlobOpenWriteOptions
{
    OpenConditions = new BlobRequestConditions
    {
        IfMatch = ETag.All // tried to work around, but doesn't help
    }
}).ConfigureAwait(false);

await stream.WriteAsync(...).ConfigureAwait(false);
```

**Comment by amishra-dev** [comment]
Hi Markus,
Apologies for missing this issue, are you still facing this problem?
