### ISSUE TITLE
Horisonatl scroll bar is missing - it's impossible to read the full content of the page

### ISSUE THREAD

**Issue by vrozovmicrosoft** [Azure/azure-sdk-for-net#25179]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e480de06-b14a-5c82-73dc-65dbc3ecd03f
* Version Independent ID: c0e88ab1-ef73-3f0b-3a35-ee5d201b1486
* Content: [BlockBlobClient Class (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blockblobclient?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlockBlobClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlockBlobClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @vrozovmicrosoft.   Thank you for your feedback.  This appears to be related to the structure of the MS Docs page structure;  we've transferred this to the Azure Docs repository as [#83503](https://github.com/MicrosoftDocs/azure-docs/issues/83503) to bring it to the attention of the team best able to address it.
