### ISSUE TITLE
Azure Identity Examples - link not working

### ISSUE THREAD

**Issue by lonelydev** [Azure/azure-sdk-for-net#25175]
[Enter feedback here]
The examples section in the docs references a link that is inaccessible .
Link in question is named - _Azure Identity Examples Wiki page_ and points to https://github.com/Azure/azure-sdk-for-net/wiki/Azure-Identity-Examples
![image](https://user-images.githubusercontent.com/9505396/140615880-00a460a8-fa3d-4979-be7c-a77da96f3ce4.png)

But what I get is:
![image](https://user-images.githubusercontent.com/9505396/140615925-cbc232d1-9149-4987-ae5b-d50215899ae1.png)

I don't see any examples or links to the examples on the wiki landing page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f73df56-2312-5851-7b59-3dfb766e5f66
* Version Independent ID: 31be349e-063e-6696-bc5f-752c413fa079
* Content: [Azure Identity client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme#defaultazurecredential)
* Content Source: [api/overview/azure/identity-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/identity-readme.md)
* Service: **identity**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.
