### ISSUE TITLE
AzureManager.Resoruces Track 2 has a bug when we use the Template tag in Deployment Properties. TemplateLink works fine

### ISSUE THREAD

**Issue by NaraVen** [Azure/azure-sdk-for-net#25183]
My template.json looks like this
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "storageAccountName": {
      "defaultValue": "mystorageaccount",
      "type": "String"
    }
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Storage/storageAccounts",
      "sku": {
        "name": "Standard_LRS",
        "tier": "Standard"
      },
      "kind": "Storage",
      "name": "[parameters('storageAccountName')]",
      "apiVersion": "2016-01-01",
      "location": "southcentralus",
      "tags": {},
      "scale": null,
      "properties": {},
      "dependsOn": []
    }
  ]
}
My parameters.json looks like this
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "storageAccountName": {
      "value": "mystorageaccount"
    }
  }
}

Repeating Again if I set the TemplateLink to a URL everything works fine.
/*********code snippet
            props.Parameters = new JsonObject()
            {
                {
                    "resourceName", new JsonObject()
                    {
                        { "value", indexClusterName },
                    }
                },
                {
                    "location", new JsonObject()
                    {
                        { "value", location.Name },
                    }
                },
            };
            props.TemplateLink = new TemplateLink()
            {
                Uri = AppSettings.ArmTemplateWithVnetCreationUri,
            };
**************end of code snippet
**When I set the Template instead I get the error below this code snippet
/*********code snippet
            props.Template = templateFileContents;
            props.Parameters = parameterFileContents["parameters"].ToObject<JObject>();
**************end of code snippet
Below is the error

Azure.RequestFailedException: 'The request content was invalid and could not be deserialized: 'Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Azure.Deployments.Core.Definitions.Schema.Template' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path 'properties.template', line 1, position 27.'.
Status: 400 (Bad Request)
ErrorCode: InvalidRequestContent

Content:
{"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Azure.Deployments.Core.Definitions.Schema.Template' because the type requires a JSON object (e.g. {\"name\":\"value\"}) to deserialize correctly.\r\nTo fix this error either change the JSON to a JSON object (e.g. {\"name\":\"value\"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.\r\nPath 'properties.template', line 1, position 27.'."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-request-id: 50212480-9594-44d3-ae3a-6f47037a8952
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Mon, 08 Nov 2021 03:12:52 GMT
Content-Type: application/json; charset=utf-8
Expires: -1
Content-Length: 746
'**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by madd0** [comment]
I can confirm this bug too. Encountered while testing `Azure.ResourceManger.Resources` 1.0.0-beta.4

It looks to me like it comes from a dependency called `Azure.Deployments.Core`, which is supposed to contain types that represent a template, but (de)serialization of the type `Azure.Deployments.Core.Definitions.Schema.Template` with Json.net is not working properly. I get the same errors as above when deserializing and when serializing, I get:

```
{"$schema":{"Value":"schema"},"LanguageVersion":null,"ContentVersion":{"Value":"1.2.2"},"ApiProfile":null,"Imports":null,"Parameters":null,"Variables":null,"Functions":null,"Resources":[],"Outputs":null,"Metadata":null}
```

Hope this helps

**Comment by gavinravenlane** [comment]
I can also confirm this bug whilst testing 1.0.0-beta.4

We have a valid template which works fine when deployed through the Azure Portal - e.g.:

TEMPLATE

{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "serverFarmName": {
      "type": "String"
    },
    "resourceOwner": {
      "type": "String"
    }
  },
  "resources": [
    {
      "type": "Microsoft.Web/serverfarms",
      "apiVersion": "2021-02-01",
      "name": "[parameters('serverFarmName')]",
      "location": "[resourceGroup().location]",
      "tags": {
        "owner": "[parameters('resourceOwner')]",
        "designer": "RoomServiceDevelopmentTeam"
      },
      "kind": "functionapp",
      "sku": {
        "name": "Y1",
        "tier": "Dynamic",
        "size": "Y1",
        "family": "Y",
        "capacity": 0
      },
      "properties": {
        "perSiteScaling": false,
        "elasticScaleEnabled": false,
        "maximumElasticWorkerCount": 1,
        "isSpot": false,
        "reserved": false,
        "isXenon": false,
        "hyperV": false,
        "targetWorkerCount": 0,
        "targetWorkerSizeId": 0,
        "zoneRedundant": false
      }
    }
  ]
}

PARAMETERS

{
  "serverFarmName": "rsasf_myrssurprise",
  "resourceOwner": "gavin"
}

When we try through the Azure.ResourceManager.Resources route as follows:

            DeploymentProperties properties = new DeploymentProperties(DeploymentMode.Incremental)
            {
                DebugSetting = new DebugSetting
                {
                    DetailLevel = "requestContent,responseContent"
                },
                Parameters = parameters,   // these are the parameters as a json string
                Template = template  // This is the template as a string
            };
            
            DeploymentInput deploymentDetails = new DeploymentInput(properties)
            {
                Location = targetLocation
            };
            await currentResourceGroup.GetDeployments().CreateOrUpdateAsync(deploymentName, deploymentDetails, true);

We get the same exception

Azure.RequestFailedException
  HResult=0x80131500
  Message=The request content was invalid and could not be deserialized: 'Error converting value "{  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",  "contentVersion": "1.0.0.0",  "parameters": {    "serverFarmName": {      "type": "String"    },    "resourceOwner": {      "type": "String"    }  },  "resources": [    {      "type": "Microsoft.Web/serverfarms",      "apiVersion": "2021-02-01",      "name": "[parameters('serverFarmName')]",      "location": "[resourceGroup().location]",      "tags": {        "owner": "[parameters('resourceOwner')]",        "designer": "RoomServiceDevelopmentTeam"      },      "kind": "functionapp",      "sku": {        "name": "Y1",        "tier": "Dynamic",        "size": "Y1",        "family": "Y",        "capacity": 0      },      "properties": {        "perSiteScaling": false,        "elasticScaleEnabled": false,        "maximumElasticWorkerCount": 1,        "isSpot": false,        "reserved": false,        "isXenon": false,        "hyperV": false,        "targetWorkerCount": 0,        "targetWorkerSizeId": 0,        "zoneRedundant": false      }    }  ]}" to type 'Azure.Deployments.Core.Definitions.Schema.Template'. Path 'properties.template', line 1, position 1608.'.
Status: 400 (Bad Request)
ErrorCode: InvalidRequestContent

Content:
{"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Error converting value \"{  \"$schema\": \"https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#\",  \"contentVersion\": \"1.0.0.0\",  \"parameters\": {    \"serverFarmName\": {      \"type\": \"String\"    },    \"resourceOwner\": {      \"type\": \"String\"    }  },  \"resources\": [    {      \"type\": \"Microsoft.Web/serverfarms\",      \"apiVersion\": \"2021-02-01\",      \"name\": \"[parameters('serverFarmName')]\",      \"location\": \"[resourceGroup().location]\",      \"tags\": {        \"owner\": \"[parameters('resourceOwner')]\",        \"designer\": \"RoomServiceDevelopmentTeam\"      },      \"kind\": \"functionapp\",      \"sku\": {        \"name\": \"Y1\",        \"tier\": \"Dynamic\",        \"size\": \"Y1\",        \"family\": \"Y\",        \"capacity\": 0      },      \"properties\": {        \"perSiteScaling\": false,        \"elasticScaleEnabled\": false,        \"maximumElasticWorkerCount\": 1,        \"isSpot\": false,        \"reserved\": false,        \"isXenon\": false,        \"hyperV\": false,        \"targetWorkerCount\": 0,        \"targetWorkerSizeId\": 0,        \"zoneRedundant\": false      }    }  ]}\" to type 'Azure.Deployments.Core.Definitions.Schema.Template'. Path 'properties.template', line 1, position 1608.'."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-request-id: de4f7cab-2b64-4baa-a013-05ee7fcb6912
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Wed, 15 Dec 2021 13:12:28 GMT
Content-Type: application/json; charset=utf-8
Expires: -1
Content-Length: 1412

  Source=Azure.ResourceManager.Resources
  StackTrace:
   at Azure.ResourceManager.Resources.DeploymentsRestOperations.<CreateOrUpdateAtScopeAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.ResourceManager.Resources.DeploymentCollection.<CreateOrUpdateAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Occam.Deployment.AzurePlatform.FunctionAndLogicManager.<ApplyDeployment>d__10.MoveNext() in C:\Dev\OccamSystemsGit\DeploymentManager\Components\Occam.Deployment.Azure\Classes\FunctionAndLogicManager.cs:line 119
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Occam.Deployment.AzurePlatform.FunctionAndLogicManager.<DeployServerFarm>d__7.MoveNext() in C:\Dev\OccamSystemsGit\DeploymentManager\Components\Occam.Deployment.Azure\Classes\FunctionAndLogicManager.cs:line 83
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Occam.Deployment.AzurePlatform.FunctionAndLogicManager.<DeployFunctionApp>d__6.MoveNext() in C:\Dev\OccamSystemsGit\DeploymentManager\Components\Occam.Deployment.Azure\Classes\FunctionAndLogicManager.cs:line 58
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Occam.Deployment.AzurePlatform.DatabaseManager.<DeployResources>d__0.MoveNext() in C:\Dev\OccamSystemsGit\DeploymentManager\Components\Occam.Deployment.Azure\Classes\DatabaseManager.cs:line 38
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Program.<<Main>$>d__0.MoveNext() in C:\Dev\OccamSystemsGit\DeploymentManager\Executables\AzureDeployer\Program.cs:line 8

  This exception was originally thrown at this call stack:
    [External Code]
    Occam.Deployment.AzurePlatform.FunctionAndLogicManager.ApplyDeployment(string, string, string) in FunctionAndLogicManager.cs
    [External Code]
    Occam.Deployment.AzurePlatform.FunctionAndLogicManager.DeployServerFarm() in FunctionAndLogicManager.cs
    [External Code]
    Occam.Deployment.AzurePlatform.FunctionAndLogicManager.DeployFunctionApp() in FunctionAndLogicManager.cs
    [External Code]
    Occam.Deployment.AzurePlatform.DatabaseManager.DeployResources(string, Azure.ResourceManager.Resources.Models.Location) in DatabaseManager.cs
    [External Code]
    Program.<Main>$(string[]) in Program.cs
 
Hope that helps identify and resolve the issue
Gavin

**Comment by Yao725** [comment]
We are going to support directly passing string to the Template or Parameters in next release of Azure.ResourceManager.Resources. For now you can use this as a work around:
```csharp
using JsonObject = System.Collections.Generic.Dictionary<string, object>;
DeploymentCollection deploymentCollection = resourceGroup.GetDeployments();
string deploymentName = "myDeployment";
var templateFile = File.ReadAllText(Path.Combine(
Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location),
"Scenario",
"DeploymentTemplates",
$"storageTemplate.json"));
var input = new DeploymentInput(new DeploymentProperties(DeploymentMode.Incremental)
{
        Template = JsonDocument.Parse(templateFile).RootElement,
        Parameters = new JsonObject()
        {
                {"storageAccountType", new JsonObject()
                        {
                                {"value", "Standard_GRS" }
                        }
                }
        }
});
DeploymentCreateOrUpdateAtScopeOperation lro = await deploymentCollection.CreateOrUpdateAsync(true, deploymentName, input);
Deployment deployment = lro.Value;
```

**Comment by Yao725** [comment]
The new version 1.0.0-beta.6 of Azure.ResourceManger.Resources has been released, now it supports directly passing json string.

BTW, the `DeploymentProperties.Parameters` need to be name and value pairs, so you need to change the parameters.json file from portal to make this work as expected.

**Comment by NaraVen** [comment]
@Yao725, what about embedded resources?
