### ISSUE TITLE
Add capability to set all TestEnvironment endpoints through environment variables

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2519]
### Description 
AzureStack requires custom endppints, enable setting all endpoints and token audiences.

### Cost: 2

**Comment by shahabhijeet** [comment]
@markcowl can you clarify what is missing in our test framework that needs to be enabled.
Currently our TestFramework provides a way to select TestEnvironment using the key-vaule pair Environment={EnvName} as documented here
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/Documentation/Using-Azure-TestFramework.md#71-supported-keyvalue-pairs-in-connectionstring

**Comment by shahabhijeet** [comment]
Closing this issue, as the latest framework does have support for custom environments.
