### ISSUE TITLE
[BUG] Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0 MessagingProvider methods now protected

### ISSUE THREAD

**Issue by admalledd** [Azure/azure-sdk-for-net#25202]
**Describe the bug**

ref: [MessagingProvider.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Primitives/MessagingProvider.cs)

Per https://github.com/Azure/azure-sdk-for-net/issues/20120#issuecomment-834745445 I had tracked/assumed that MessagingProvider's methods (mostly "CreateMessageSender/Receiver") would remain public. I have a few use-cases where I have (semi) dynamically named Service Bus Queues to reply to in my triggers, and being able to use MessagingProvider as a simple queue-factory over that was useful, and was also a recommended solution a few years ago for unit testing ServiceBus triggers.

Note that I can sub-class/replace MessagingProvider, or probably find other ways to get a MessageSender (and mock the other end MessageReciver for unit tests), but there were no noted changelogs/docs informing of this change either.

This was changed in [PR 21181](https://github.com/Azure/azure-sdk-for-net/pull/21181) it seems.

**Expected behavior**
One of: 

* Methods are public
* Documented recommended way to have a at-runtime and based upon message content, a specific Queue's MessageSender
* [Use TryAddSingleton<MessagingProvider>()](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Config/ServiceBusHostBuilderExtensions.cs#L92) instead to allow user-override (See [WebJobsSDK Hosting.AddWebJobs()](https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Hosting/WebJobsServiceCollectionExtensions.cs#L41) for some how/why)

**Actual behavior (include Exception or Stack Trace)**
Methods are protected

**Environment:**
 - New: `<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.0.0" />`
 - Old: `<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.3.0" />`

Additional: This was encountered in a larger (attempted) update to dotnet6. I don't think that (directly) impacts this though.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by admalledd** [comment]
Addendum: This would all be a lot easier if there was a few safe interfaces (if they exist do point them out! I did not see any when I dug into the code) that ServiceBus or WebJobs.ServiceBus (either/or) exposed for the actual function-class via DI or on the attribute-binding:

* "IMessageBusSenderFactory" that "already binds" to the same SB connection as the function, allowing me inside my fuction/method to dynamically get/construct which Topic/Queue to send to. For UnitTests etc, it would be appreciated if this factory returned a "IMessageSender" like mockable interface (doesn't have to be exactly the older iface/model, just of-kind)

**Comment by JoshLove-msft** [comment]
Hi @admalledd,
In the next release of the extension which is going out this week, you will be able to bind to the ServiceBusClient using the "client" parameter name. This will give you access to the same SB connection as the function.

**Comment by admalledd** [comment]
That sounds like a fine middle ground (I prefer Interface or letting me "pick up" via DI instead of attribute, but meh in the end). When that is released I'll check it out and refactor code (again) to close this with a code-sample for clarity.

**Comment by JoshLove-msft** [comment]
The new version is now available - https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.1.0
