### ISSUE TITLE
Create  Changelog / Readme per product

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2520]
### Description

Add readme and changelog for each library, test framework, and tools

### Cost: 4

**Comment by cormacpayne** [comment]
PR checklist has been merged in PR https://github.com/Azure/azure-sdk-for-net/pull/2648

**Comment by adrianhall** [comment]
I think this is now the norm.  Is this required to be open any more?  (Closing in 30 days unless there is something more articulated)

**Comment by cormacpayne** [comment]
Closing as fixed.
