### ISSUE TITLE
ARM permissions ListForResource does not accommodate resources outside of resource groups

### ISSUE THREAD

**Issue by bvirkler** [Azure/azure-sdk-for-net#2521]
When calling the REST API directly, it's possible to query the current user's permissions on a resource that is not in a resource group, like a role definition:

`GET https://management.azure.com/subscriptions/xxx/providers/Microsoft.Authorization/roleDefinitions/yyy/providers/Microsoft.Authorization/permissions?api-version=2015-07-01`

This is not possible with the generated [ListForResource ](https://github.com/Azure/azure-sdk-for-net/blob/04d78e2101f7d040aaa97481757a2fb69fffe9c9/src/ResourceManagement/Authorization/Microsoft.Azure.Management.Authorization/Generated/PermissionsOperations.cs#L247) method, as resource group is required and is hard-coded in the URL.

**Comment by adrianhall** [comment]
Going through old issues that have had no attention.  Is this still an issue?
