### ISSUE TITLE
MaxAutoLockRenewalDuration property for service bus processor is not working

### ISSUE THREAD

**Issue by eegasai** [Azure/azure-sdk-for-net#25245]
I have created a .NetCore 3.1 Console application and installed Azure.Messaging.ServiceBus package. I have a service bus name space created with a topic and subscription. The MaxLockDuration for the subscription is set as 5 Minutes.

As my application needs around 15 minutes for the processing, I have set the MaxAutoLockRenewalDuration  property to 15 minutes. To test this I have introduced a delay of 6 minutes in the Process Message. After completion of 5 minutes same message is delivered again for the processing.so it seems like setting Auto renewal lock property did not work and same message is delivered again.

Can you please have a look and let me know if i am missing anything?

    internal class Program
    {
        static async Task Main(string[] args)
        {
            var client = new ServiceBusClient("");
            var options = new ServiceBusProcessorOptions
            {
                ReceiveMode = ServiceBusReceiveMode.PeekLock,
                AutoCompleteMessages = false,
                MaxConcurrentCalls = 2,
                MaxAutoLockRenewalDuration = TimeSpan.FromMinutes(15)
            };

            await using ServiceBusProcessor processor = client.CreateProcessor("topicname", "subscriptionname", options);

            processor.ProcessMessageAsync += Processor_ProcessMessageAsync;

            processor.ProcessErrorAsync += Processor_ProcessErrorAsync;

            await processor.StopProcessingAsync();

            Console.Read();
        }

        private static Task Processor_ProcessErrorAsync(ProcessErrorEventArgs arg)
        {
            Console.WriteLine(arg.Exception);
            return Task.CompletedTask;
        }

        private static async Task Processor_ProcessMessageAsync(ProcessMessageEventArgs arg)
        {
            Console.WriteLine("Received Message.going for delay");

            await Task.Delay(TimeSpan.FromMinutes(6));

            Console.WriteLine("Handle Message");

            await arg.CompleteMessageAsync(arg.Message);
        }
    }

**Environment:**
 - Azure.Messaging.ServiceBus 7.4.0 
 - .Net Core 3.1
 - Visual studio 2022 Preview

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
@eegasai, can you please verify that your machine's time is accurate? We have seen this happen before when the time was not accurate.

**Comment by eegasai** [comment]
@JoshLove-msft : I have validated my machine time and its accurate. I have tried this sample in two different machines also and same issue is happening.

**Comment by JoshLove-msft** [comment]
You say that the same message is redelivered - does that mean you are getting an exception when you try to complete the message in the first delivery?

**Comment by JoshLove-msft** [comment]
Can you also try enabling logging?
```c#
using var logger = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Verbose);
```

**Comment by eegasai** [comment]
@JoshLove-msft : No there is no exception. As soon as i hit the CompleteMessageAsync and come out of the method the same message is received in the event again.

I will enable the logger and will let you know.

**Comment by JoshLove-msft** [comment]
If the lock was lost there should be an exception. How are you determining that the messages are the same?

**Comment by eegasai** [comment]
I did not get any exception. I have pushed only one message to the topic. I have also validated the message body and confirmed the payload is same as Payload is a Guid.

**Comment by JoshLove-msft** [comment]
Ok please include the SDK logs, and we can troubleshoot further.
