### ISSUE TITLE
[BUG] Refreshing the blob listing on the Azure portal or Storage explorer causes a 409 during blob append operations

### ISSUE THREAD

**Issue by daviestoby** [Azure/azure-sdk-for-net#25246]
Whilst appending chunks to an append blob I receive a http 409 error if I refresh the blob listing in the portal or from storage explorer.

I expect that refreshing a blob listing should have no material impact on the ability to append multiple chunks.

The actual behaviour is that if I don't touch the refresh button it works fine but if I do during the append loop the process crashes with this exception.

```
An exception of type 'Azure.RequestFailedException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The blob has been modified while being read.
RequestId:62778adb-001e-011e-29a4-d589bf000000
Time:2021-11-09T20:02:29.3183234Z
Status: 409 (The blob has been modified while being read.)
ErrorCode: BlobModifiedWhileReading
```

Please see video repro for
Error - [https://tobydpublicdata.blob.core.windows.net/bugs/Error.mp4](https://tobydpublicdata.blob.core.windows.net/bugs/Error.mp4)

Working - [https://tobydpublicdata.blob.core.windows.net/bugs/Working.mp4](https://tobydpublicdata.blob.core.windows.net/bugs/Working.mp4)

My sample application is

```
using System;
using System.IO;
using System.Buffers;
using System.Threading.Tasks;
using Azure.Storage.Blobs;
using System.Text;
using Azure.Storage.Blobs.Specialized;

namespace str
{
    static class Program
    {
        static async Task Main(string[] args)
        {
            const string ContainerName = "files";
            const string BlobName = "my.blob";

            BlobServiceClient blobClient = new("some-connection-string-to-your-storage-account");

            BlobContainerClient containerClient = blobClient.GetBlobContainerClient(ContainerName);
            await containerClient.CreateIfNotExistsAsync();

            AppendBlobClient appendClient = containerClient.GetAppendBlobClient(BlobName);
            await appendClient.CreateIfNotExistsAsync();

            using FileStream fs = await FileMaker.CreateNonsenseFileAsync();
            using BinaryReader reader = new(fs);

            bool readLoop = true;

            while (readLoop)
            {
                byte[] chunk = reader.ReadBytes(appendClient.AppendBlobMaxAppendBlockBytes);

                if (chunk.Length > 0)
                    await appendClient.AppendBlockAsync(new MemoryStream(chunk));

                readLoop = chunk.Length == appendClient.AppendBlobMaxAppendBlockBytes;
            }

            fs.Close();
            File.Delete(fs.Name);
        }
    }

    public static class FileMaker
    {
        public static async Task<FileStream> CreateNonsenseFileAsync(int blocks = 30000)
        {
            string tempFile = Path.GetTempFileName();
            FileStream fs = File.OpenWrite(tempFile);
            byte[] buffer = ArrayPool<byte>.Shared.Rent(1024);

            Random randy = new();

            using (StreamWriter writer = new(fs))
            {
                for (int i = 0; i < blocks; i++)
                {
                    randy.NextBytes(buffer);
                    await writer.WriteAsync(Encoding.UTF8.GetString(buffer));
                }
            }

            return File.OpenRead(tempFile);
        }
    }
}
```

csproj is

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Files.DataLake" Version="12.8.0" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
  </ItemGroup>

</Project>
```

This was run from VSCode on Win10 x64 compiled as .net5 but was based on a problem I was encountering using VS2019 using .net 2.2 (yes, I know...).

I originally posed this on SO [here](https://stackoverflow.com/questions/69904460/azure-blob-storage-append-blob-409-modified-error-when-refreshing-portal-sto)

**Comment by amnguye** [comment]
Hi, this is not an SDK issue rather than an expectation of the storage service. This should be routed to someone on the storage service for a proper explanation.

If you are modifying a blob (e.g. the append block on an append blob) and attempting to also do a read, the service will throw you a BlobModifiedWhileReading. This is due to a read and write conflict on the same blob.

I recommend if you want to attempt both read and writes on the blob, that you write a try block catch in your code for this and attempt to retry the Append Block later on this Error Code instead of crashing the process when this exception is thrown. In the case that doing a try catch block for this exception is within threshold of your scenario.
