### ISSUE TITLE
Default outbound map issue

### ISSUE THREAD

**Issue by ihorwill** [Azure/azure-sdk-for-net#25274]
There appears to be a bug in the default outbound map for http://schemas.microsoft.com/2012/12/certificatecontext/extension/authoritykeyidentifier: it maps to "certauthority key identifier" (with spaces).

The inbound map has "certauthoritykeyidentifier" (no spaces).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d69c6c7-cf53-6725-e0c1-814838f34c9f
* Version Independent ID: 7d632897-4ce5-d90e-e742-2bb26386708f
* Content: [JwtSecurityTokenHandler.OutboundClaimTypeMap Property (System.IdentityModel.Tokens.Jwt) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtsecuritytokenhandler.outboundclaimtypemap?view=azure-dotnet#System_IdentityModel_Tokens_Jwt_JwtSecurityTokenHandler_OutboundClaimTypeMap)
* Content Source: [xml/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `System.IdentityModel.Tokens.Jwt` package is maintained as [#1773](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1773).

**Comment by ihorwill** [comment]
Ah thanks. Sorry for the misfile.

**Comment by jsquire** [comment]
> Ah thanks. Sorry for the misfile.

No worries and it wasn't on your end.   All docs-related issues route through this repo when filed.   It's on us to make sure they end up in the right place for assistance.  😄
