### ISSUE TITLE
[LLC] Add live tests for WebPubSub

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#25289]
Live tests are missing for [WebPubSub](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/webpubsub/Azure.Messaging.WebPubSub/tests).

If you need more information about the live tests, please refer https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#live-testing. Here are some examples: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/anomalydetector/Azure.AI.AnomalyDetector/tests/AnomalyDetectorClient/AnomalyDetectorClientLiveTests.cs

**Comment by Mohit-Chakraborty** [comment]
@JialinXin , @vicancy - are there existing plans to add live tests? Else, we can use this issue for tracking.

**Comment by vicancy** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/25106/files here is the PR for live test, have some tests to fix

**Comment by pallavit** [comment]
I see a ci pipeline for webpubsub
