### ISSUE TITLE
[FEATURE REQ] ArmClient: Get resource from current context

### ISSUE THREAD

**Issue by aelij** [Azure/azure-sdk-for-net#25297]
**Library or service name.**
Azure.ResourceManager, 1.0.0-beta.3
 
**Is your feature request related to a problem? Please describe.**
Let's start with an example. I want to get an existing resource (e.g. a storage account) in a resource group. My options are:

```cs
// 1 - redundant network call
var resourceGroup = await client.GetSubscription("/subscriptions/711e5d1d-90f2-4476-b9bc-033d3cd9cfc5")
  .GetResourceGroups().GetAsync("rg1"); 
var storage = await resourceGroup.Value.GetStorageAccounts().GetAsync("s1");

// 2 - manually construct resource ID
var storage = await client.GetStorageAccount("/subscriptions/711e5d1d-90f2-4476-b9bc-033d3cd9cfc5/resourceGroups/rg1/providers/Microsoft.Storage/accounts/s1").GetAsync();

// 3 - same as 2, but construct ID using a non-browsable API (AppendProviderResource)
var resourceGroup =  client.GetResourceGroup("/subscriptions/711e5d1d-90f2-4476-b9bc-033d3cd9cfc5/resourceGroups/rg1");
var storageResourceId = resourceGroup.Id.AppendProviderResource(StorageAccount.ResourceType.Namespace,
  StorageAccount.ResourceType.Type, "s1");
var storage = await client.GetStorageAccount(storageResourceId).GetAsync();
```

This is quite a common operation and I think it should be made easier. My suggestion is to generate singular methods alongside each collection method, e.g.:

```cs
var storage = await client.GetSubscription("/subscriptions/711e5d1d-90f2-4476-b9bc-033d3cd9cfc5")
  .GetResourceGroup("rg1").GetStorageAccount("s1").GetAsync();
```

For even more simplicity, add a `GetSubscriptionById`:
```cs
var storage = await client.GetSubscriptionById("711e5d1d-90f2-4476-b9bc-033d3cd9cfc5")
  .GetResourceGroup("rg1").GetStorageAccount("s1").GetAsync();
```

This way the user never needs to deal with constructing ARM resource IDs.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
We had a discussion before about this scenario and ended up with the decision to provide a more convenient `CreateResourceIdentifier` method for each resource. Now you can get the resource in this way:

```
var storageAccountId = StorageAccount.CreateResourceIdentifier("711e5d1d-90f2-4476-b9bc-033d3cd9cfc5", "rg1", "s1");
var storage = await client.GetStorageAccount(storageAccountId).GetAsync();
```

**Comment by aelij** [comment]
@fengzhou-msft Nice. But how would this work for child resources (e.g. `Microsoft.Storage/storageAccounts/blobServices/containers`) and extension resources (e.g. `Microsoft.Insights/diagnosticSettings`)?
