### ISSUE TITLE
[BUG] Service Bus receiver client PeekMessageAsync causing exception (Unable to cast object of type 'System.Int64' to type 'System.DateTime'.)

### ISSUE THREAD

**Issue by vikcher** [Azure/azure-sdk-for-net#25294]
**Describe the bug**

I am trying to Peek messages from a Service bus subscription using the  PeekMessageAsyc() method of ServiceBusReceiver.
This is causing an exception to be thrown, related to casting Int64 to DateTime.

**Expected behavior**
Expected behavior is that the first message in subscription is returned without any exception.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Actual behavior is an exception. Below is the stack trace:

Result: Failure Exception: System.AggregateException: One or more errors occurred. (Unable to cast object of type 'System.Int64' to type 'System.DateTime'.) ---> System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.DateTime'. at Azure.Messaging.ServiceBus.Amqp.AmqpMessageConverter.AmqpMessageToSBMessage(AmqpMessage amqpMessage, Boolean isPeeked) at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesInternalAsync(Int64 sequenceNumber, Int32 messageCount, TimeSpan timeout, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c__DisplayClass51_0.<<PeekMessagesAsync>b__0>d.MoveNext() --- End of stack trace from previous location --- at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation(Func`2 operation, TransportConnectionScope scope, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation(Func`2 operation, TransportConnectionScope scope, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.PeekMessagesAsync(Nullable`1 sequenceNumber, Int32 messageCount, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.ServiceBusReceiver.PeekMessagesInternalAsync(Nullable`1 sequenceNumber, Int32 maxMessages, CancellationToken cancellationToken) at Azure.Messaging.ServiceBus.ServiceBusReceiver.PeekMessageAsync(Nullable`1 fromSequenceNumber, CancellationToken cancellationToken) at Watchdog.IngestionQueueMonitor.Run(TimerInfo myTimer) in /home/vsts/work/1/s/services/Watchdog/IngestionProgressMonitor.cs:line 76 at Microsoft.Azure.Functions.Worker.Invocation.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in D:\a\1\s\src\DotNetWorker.Core\Invocation\VoidTaskMethodInvoker.cs:line 24 --- End of inner exception stack trace --- at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32 at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj) at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location --- at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45 at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 16 at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166 Stack: at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) at System.Threading.Tasks.Task`1.get_Result() at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.<>c.<InvokeAsync>b__6_0(Task`1 t) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 32 at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke() at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj) at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location --- at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread) --- End of stack trace from previous location --- at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 45 at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 16 at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 166

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Add messages to service bus susbcription.
2. Initialize ServiceBusClient from Azure.Messaging.ServiceBus package.
2. Try to peek the first message in the subscription using the following:
       
                var subscriptionReceiverClient = this.serviceBusClient.CreateReceiver(topicName, subscriptionName);

                // Get first message in subscription.
                var peekedMessage = await subscriptionReceiverClient.PeekMessageAsync();

**Environment:**
 - Azure.Messaging.ServiceBus version 7.5.0
 - Azure function app running .NET 5.0

**Comment by JoshLove-msft** [comment]
@vikcher can you please share how you are creating and sending the message?

**Comment by vikcher** [comment]
@JoshLove-msft , the message was created and sent using Python ServiceBusClient. We create JSON messages.
Here is a code snippet:

`with ServiceBusClient(self.servicebus_fqns, client_credential) as client:
                with client.get_topic_sender(self.topic_name) as sender:
                    for row in partition_data:
                        message = {EventProperty.Id.value: str(uuid.uuid4()),
                                   EventProperty.Type.value:
                                       DocumentEventType.TimelineUpsert.value,
                                   EventProperty.Version.value: self.version,
                                   EventProperty.FileFormat.value:
                                       self.file_format.value,
                                   EventProperty.FileSystem.value:
                                       self.container_name,
                                   EventProperty.IndexName.value:
                                       self.search_index,
                                   EventProperty.FilePath.value: row.FilePath}
                        sender.send_messages(
                            ServiceBusMessage(
                                json.dumps(message).encode("utf-8")))
                        yield ((row.FilePath,))`

**Comment by vikcher** [comment]
The ServiceBusClient package version is 7.4.0

**Comment by JoshLove-msft** [comment]
Thanks @vikcher 
Can you also include the actual JSON for the message so I can try to reproduce the issue?

**Comment by vikcher** [comment]
Here is a sample JSON:

`
{"id": "3a592232-89c1-4fd8-96fe-95b3a4c4662b", "indexName": "index_name", "type": "TimelineUpsert", "version": "V1", "fileFormat": "PARQUET", "fileSystem": "document", "filePath": "/Redacted/file/path/tid-4831-00614aa6-7ee5-49eb-a019-e132b9238e84-3187-1-c000.samplePath.parquet"}
`

**Comment by JoshLove-msft** [comment]
Interesting, @yunhaoling @swathipil, do you know how a JSON message like this would be sent when using the Python SDK? Are they put into the ApplicationProperties?

**Comment by vikcher** [comment]
Hi @JoshLove-msft , @yunhaoling , @swathipil - is there any update on this?

**Comment by swathipil** [comment]
@JoshLove-msft - Here, the ServiceBusMessage `body` attribute would be set to the sample JSON value.

**Comment by JoshLove-msft** [comment]
We just tried a test where @swathipil sent a message containing the body you have included using the Python SDK and I received it and completed it using the .NET SDK, and everything worked.

Are you setting any other properties on the message, or are you only setting the body as in the code snippet you have provided? 
The only way I can see this error occurring is if one of the reserved Service Bus properties was set when sending a message.
