### ISSUE TITLE
[Form Recognizer] StartBuildModel(False) failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#25295]
Form Recognizer runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 503 (Service Unavailable)
> 
> Content:
> no healthy upstream
> 
> Headers:
> apim-request-id: 1689fa00-f7d9-43aa-96d4-56d317fa260f
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> x-content-type-options: nosniff
> Content-Length: 19
> Content-Type: text/plain
> Date: Fri, 12 Nov 2021 05:29:37 GMT
> 
> 
> Stack trace
>    at Azure.AI.FormRecognizer.DocumentAnalysis.DocumentAnalysisRestClient.<DocumentAnalysisBuildDocumentModelAsync>d__14.MoveNext() in /_/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/DocumentAnalysisRestClient.cs:line 338
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.AI.FormRecognizer.DocumentAnalysis.DocumentModelAdministrationClient.<StartBuildModelAsync>d__8.MoveNext() in /_/sdk/formrecognizer/Azure.AI.FormRecognizer/src/DocumentModelAdministrationClient.cs:line 202
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.TestFramework.InstrumentResultInterceptor.<InstrumentOperationInterceptor>d__4`1.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\InstrumentResultInterceptor.cs:line 70
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<ValidateDiagnosticScope>d__6`1.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 177
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DocumentModelAdministrationClientLiveTests.<St

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1192251&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Failure not happening anymore.
