### ISSUE TITLE
[BUG] `MonitorQueryModelFactory.LogsQueryResult()` is unusable

### ISSUE THREAD

**Issue by afscrome** [Azure/azure-sdk-for-net#25299]
**Describe the bug**

I'm writing an app that can take generic log queries and convert them to metrics.  As part of this I'm needing to handle the various different numeric data types app insights can return (real, integer, decimal, float).  I'm trying to write a unit test that `print value=tofloat(5)`

`MonitorQueryModelFactory` has a `LogsQueryResult()` method which looks like what I need, however the first parameter it takes is `IReadOnlyList<LogsTable>`.  `LogsTable` has an internal constructor, but doesn't have a factory method on `MonitorQueryModelFactory` so it is only possible to create a `LogsQueryResult` with no tables, which is pretty useless result.

**Expected behavior**
I expect to be able to create a `LogsQueryResult` that mocks the data set from a simple query such as ``print value=tofloat(5)`.  I'd expect to see a `MonitorQueryModelFactory.LogsTable()` method to allow creation of a `LogsTable`.  

``
I expected to be able to use `MonitorQueryModelFactory` to produce a `LogsTable` object, and then to construct

**Actual behavior (include Exception or Stack Trace)**
No ability to mock such an object.

**Environment:**
 - Name and version of the Library package used: Azure.Monitor.Query 1.0.1
 - Hosting platform or OS and .NET runtime version: Azure Functions on .Net 3.1
 - IDE and version : VS 2022 17.0.0

**Comment by afscrome** [comment]
There also seems to be a similar problem with `MetricsQueryResult` - it accepts `IReadOnlyList<MetricResult>`, but I see no way to create `MetricResult`

**Comment by jsquire** [comment]
//cc: @kinelski

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nisha-bhatia** [comment]
LogsTable and LogsTableRow bug fixes will go out in the next release.

**Comment by scottaddie** [comment]
@nisha-bhatia Can this issue be closed now?

**Comment by nisha-bhatia** [comment]
This issue has been resolved with release 1.1.0.
