### ISSUE TITLE
[QUERY] Set Azure WebJobs Service Bus connection string in code.

### ISSUE THREAD

**Issue by henriblMSFT** [Azure/azure-sdk-for-net#25301]
**Query/Question**
In version 4.x of the extension we used to be able to set the connection string information in code like this:

```csharp
.ConfigureWebJobs((ctx, b) =>
{
    b.AddAzureStorageCoreServices()
    .AddTimers()
    .AddServiceBus(o =>
    {
        o.ConnectionString = ctx.Configuration["AlternateConnectionStringLocation"];
    });
})
```
Starting with version `5.0.0-beta.2` this property was removed from ServiceBusOptions as part of change #19892 by @JoshLove-msft 

Is it still possible to specify the connection string through code? If not, can this feature be added back to version 5.x of the SDK?

**Environment:**
 - Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.1.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
You could set the setting in code doing something like this - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/WebJobsServiceBusTestBase.cs#L142-L145

where you can set an entry in the dictionary with a key being equal to your connection setting name, and the value being your connection string.

**Comment by henriblMSFT** [comment]
/unresolve

That is quite convoluted. It may work in a test but is not as straightforward in a real application. At the time we are configuring the service bus options we no longer control the IConfiguration builder.

 Is there a reason why a the configuration option is no longer available in code?

**Comment by JoshLove-msft** [comment]
@henriblMSFT, can you share a little more about why the configuration based solution won't work for your application? Are the connection strings not able to be picked up based on app settings?

**Comment by henriblMSFT** [comment]
I'm not saying it is impossible it's just a bit convoluted. The settings is coming from keyvault on a different key as it is shared across multiple services.

Here is how it would need to be done:

```csharp
.ConfigureWebJobs((ctx, b) =>
{
    b.AddAzureStorageCoreServices()
    .AddTimers()
    .AddServiceBus(o =>
    {
        o.ConnectionString = ctx.Configuration["AlternateConnectionStringLocation"];
    });
})
.ConfigureAppConfiguration((ctx, configBuilder) =>
{
  configBuilder.AddAzureKeyVault(keyvaultUri, [...]);
  
  var settings = configBuilder.Build();
  var connectionString = settings.GetValue("MyServiceWebJobServiceBus");

  configBuilder.AddInMemoryCollection(new Dictionary<string,string>
  {
    ["AzureWebJobsServiceBus"] = connectionString,
  };
});
```

**Comment by JoshLove-msft** [comment]
I guess my question is why can't you specify the setting directly in your trigger function in Connection property?

**Comment by Munnwich** [comment]
Subscribed.  Just updated from 4.3.0 to 5.1.0 and found this issue due to compilation failures.

**Comment by mattmunich** [comment]
Subscribed - just updated from 4.3.0 to 5.1.0 and found this issue as a result of compilation issues.

**Comment by JoshLove-msft** [comment]
@mattmunich are you able to specify the connection string in app settings key in a deployed app and in localsettings.json for local dev?

**Comment by mattmunich** [comment]
> @mattmunich are you able to specify the connection string in app settings key in a deployed app and in localsettings.json for local dev?

Our pattern has been to store connection strings and other secrets in AzureKeyVault (we leverage Azure App Config for non-secret config values).  All of these configs & secrets are read into an `IConfigurationBuilder` at runtime (access is controlled by managed identities) and bound to a POCO settings class of our creation.  The only settings necessary from a developer's perspective (and deployed for that matter) are the urls to the various app config & keyvault resources.

**Comment by henriblMSFT** [comment]
@JoshLove-msft the documentation isn't clear on how the connection property on the service bus trigger needs to be used.
All the examples seem to be related to using Connection for Managed Identity authentication:

https://github.com/azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/README.md

**Comment by JoshLove-msft** [comment]
> > @mattmunich are you able to specify the connection string in app settings key in a deployed app and in localsettings.json for local dev?
> 
> Our pattern has been to store connection strings and other secrets in AzureKeyVault (we leverage Azure App Config for non-secret config values). All of these configs & secrets are read into an `IConfigurationBuilder` at runtime (access is controlled by managed identities) and bound to a POCO settings class of our creation. The only settings necessary from a developer's perspective (and deployed for that matter) are the urls to the various app config & keyvault resources.

There is a way to use config files along with Key Vault - please take a look at https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft the documentation isn't clear on how the connection property on the service bus trigger needs to be used. All the examples seem to be related to using Connection for Managed Identity authentication:
> 
> https://github.com/azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/README.md

By default, the connection string would be placed in a setting called "AzureWebJobsServiceBus". This would be in localsettings.json for local dev, or in your app settings for a deployed app.
If you want to use a different name for the setting you can do so, and then specify it in your function like this:
```c#
[FunctionName("ServiceBusQueueTriggerCSharp")]                    
public static void Run(
    [ServiceBusTrigger("myqueue", Connection = "myConnection")] 
    string myQueueItem)
```

See https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=csharp for more details.

**Comment by tonycdpp** [comment]
> @henriblMSFT, can you share a little more about why the configuration based solution won't work for your application? Are the connection strings not able to be picked up based on app settings?

I think this should be put back in. Or alternatively, provide a tutorial on how to Create a WebJob tied with KeyVault that contains a [ServiceBusTrigger] and how it all hangs together. 

Ever since this was removed, it's been utter hell to setup and not very obvious, and very poorly documented
