### ISSUE TITLE
[BUG] AppendChildResource produces incorrect ResourceType

### ISSUE THREAD

**Issue by aelij** [Azure/azure-sdk-for-net#25312]
**Describe the bug**

```cs
new ResourceIdentifier("/subscriptions/794307ce-39e3-4505-bce1-23bd9837bcc7/resourceGroups/g1")
  .AppendProviderResource("microsoft.storage", "accounts", "ac1")
  .AppendChildResource("containers", "c1").ResourceType
```

**Expected behavior**
`Microsoft.Storage/accounts/containers`

**Actual behavior (include Exception or Stack Trace)**
`Microsoft.Resources/containers`

**To Reproduce**
See above

Note that calling `new ResourceIdentifier(identifer.ToString()).ResourceType`  produces the correct result.

**Environment:**
 - Name and version of the Library package used: Azure.ResourceManager, 1.0.0-beta.5
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 11, .NET 5.0
 - IDE and version : VS 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
Hi @aelij we recently did a little bit refactor on the ResourceIdentifier class. We moved it to `Azure.Core`.
In the latest version of Azure.Core (1.22.0), you could find this class, and your code is working as expected. Therefore I believe the bug should be fixed.
```
using Azure.Core;

var id = new ResourceIdentifier("/subscriptions/794307ce-39e3-4505-bce1-23bd9837bcc7/resourceGroups/g1").AppendProviderResource("microsoft.storage", "accounts", "ac1").AppendChildResource("containers", "c1");
Console.WriteLine(id.ToString());
Console.WriteLine(id.ResourceType);
```
Result of this program:
![image](https://user-images.githubusercontent.com/10554446/151118004-91fe19be-184b-4ea4-8d06-9e0c3b239e58.png)
Please give a try with the latest version of Azure.Core to see if this resolves your issue. Thank you!

**Comment by aelij** [comment]
Thanks, looks like it's fixed
