### ISSUE TITLE
[BUG] TableEntity.GetDateTime throws InvalidOperationException

### ISSUE THREAD

**Issue by j055** [Azure/azure-sdk-for-net#25323]
**Describe the bug**
`TableEntity.GetDateTime`  throws `InvalidOperationException`. Cannot return System.Nullable`1[System.DateTime] type for a System.DateTimeOffset typed property.

The date was added using `TableEntity.Add`, e.g.

```
MyEntity entity = new MyEntity();
entity.DateTime = DateTime.UtcNow;
TableEntity tableEntity = new TableEntity();
tableEntity.Add(nameof(entity.DateTime), entity.DateTime);
```

**Expected behavior**
`TableEntity.GetDateTime` should return a valid `Nullable<DateTime>` without error.

**Actual behavior (include Exception or Stack Trace)**

```
at Azure.Data.Tables.TableEntity.EnforceType(Type requestedType, Type givenType)
at Azure.Data.Tables.TableEntity.GetValue(String key, Type type)   
at Azure.Data.Tables.TableEntity.GetValue[T](String key)   
at Azure.Data.Tables.TableEntity.GetDateTime(String key)   at UserQuery.Map(TableEntity tableEntity), line 62   
at System.Linq.Enumerable.SelectListIterator`2.ToList()   
at UserQuery.Main(), line 21

```

**To Reproduce**

* Create an Azure storage account
* Use `TableClient.UpsertEntityAsync` with a `TableEntity` containing a `System.DateTime` property
* Use `TableClient.GetEntityAsync<TableEntity>` to retrieve entity and `TableEntity.GetDateTime` to parse date.

Exception is thrown. 

As above

**Environment:**
 - Azure.Data.Tables 12.3.0
 - Hosting platform Windows 10

**Comment by christothes** [comment]
Hi @j055 
If `entity.DateTime` is typed as a `DateTimeOffset`, then this behavior is by design.

ex.
```c#
var t = new TableEntity();
t.Add("DateTime", DateTime.UtcNow);
t.Add("DateTimeOffset", DateTimeOffset.UtcNow);
Console.WriteLine(t.GetDateTime("DateTime")); // prints 11/15/2021 4:29:22 PM
Console.WriteLine(t.GetDateTimeOffset("DateTime")); // throws
Console.WriteLine(t.GetDateTimeOffset("DateTimeOffset")); // prints 11/15/2021 4:29:22 PM +00:00
Console.WriteLine(t.GetDateTime("DateTimeOffset")); // throws
```

**Comment by j055** [comment]
I've updated **To Reproduce** above. You need a storage account to reproduce. Then update and retrieve when the entity contains a `DateTime` property. Exception thrown.

**Comment by christothes** [comment]
Thanks for the additional information. I see the problem and will be working on a fix.
