### ISSUE TITLE
[QUESTION] How can I correctly send a message to the dead letter queue from the azure function service bus trigger?

### ISSUE THREAD

**Issue by tkachuk2222** [Azure/azure-sdk-for-net#25320]
**Query/Question**
How can I correctly send a message to the dead letter queue from the azure function service bus trigger?
Want to do it without exception throwing

**Environment:**
- Azure Function dotnet-isolated
- azure function version v3
- .net 5.0
- Microsoft.Azure.ServiceBus 5.1.3
- Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 4.2.1

**Comment by PramodValavala-MSFT** [comment]
@tkachuk2222 Unfortunately, this isn't possible without throwing an except with dotnet isolated (or other non-C# languages). This is only supported for in-process C# functions by binding to a `MessageReceiver` object.
