### ISSUE TITLE
[QUERY]TokenPersistence for DeviceCodeCredential

### ISSUE THREAD

**Issue by AshleyAsh90** [Azure/azure-sdk-for-net#25332]
**Query/Question**
I am following the sample([ClientSideUserAuthentication](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md)) using TokenCachePersistence for DeviceCodeCredential instead of InteractiveBrowserCredential and it seems to call the DeviceCodeCallback despite the authenticationRecord being present and it seems to be waiting for authentication.
I just replaced the InteractivebrowerCredential and InteractiveBrowserCredentialOptions with DeviceCodeCredential and DeviceCodeCredentialOptions respectively.
```
AuthenticationRecord authRecord;
using (var authRecordStream = new FileStream(AUTH_RECORD_PATH, FileMode.Open, FileAccess.Read))
{
    authRecord = await AuthenticationRecord.DeserializeAsync(authRecordStream);
}

var credential = new InteractiveBrowserCredential(
    new InteractiveBrowserCredentialOptions
    {
        TokenCachePersistenceOptions = new TokenCachePersistenceOptions(), AuthenticationRecord = authRecord
    });
```
It shouldn't call the callback if the authRecord is available right?(this is assuming that replacing the credential class(InteractiveBrowser to DeviceCode) should be enough to persist token). It seems to call the callback and wait for the user to login. I am not sure if there is a different way to persist the token or make the GraphServiceClient to use the persisted token other than this, but could you confirm this is the right way to do this?

**Environment:**
 -  Azure.Identity 1.4.1 
 -  Windows 10 .NET Framework 4.7.2
 - IDE and version : [Visual Studio ]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
In my testing with the latest version of Azure.Identity, I am able to silently auth with `DeviceCodeCredential` given a valid AuthenticationRecord.

```c#
var options = new DeviceCodeCredentialOptions();
options.TokenCachePersistenceOptions = new TokenCachePersistenceOptions { Name = TokenCacheName };
options.AuthenticationRecord = authRecord;
var cred = new DeviceCodeCredential(options);

// no credential prompt
var token = await cred.GetTokenAsync(new TokenRequestContext(myScope), default);
```

**Comment by AshleyAsh90** [comment]
Strange, I tried with 1.5.1 but I still have the async call waiting on device login even after the first call the cace was persisted to disc. Did you re-start your application and were you still able to obtain the token?

**Comment by christothes** [comment]
If this works without restart but not after, it sounds like the cache may not be getting re-hydrated properly. Have you tried providing a name for the cache to ensure it is the same across executions?

**Comment by AshleyAsh90** [comment]
Yes, I tried after changing the cache and auth record names just so there is a newer cache and authrecord, but it still requests device code and times out when there is no user logging in a second time.

**Comment by christothes** [comment]
Do you have some simplified code that reproduces this issue?
