### ISSUE TITLE
Wrong error message for omitting scheme from Uri in Storage configuration in Azure Functions

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-sdk-for-net#25334]
Please note that there was an error in documentation which led to folks omitting https:// because they were following the instructions. The docs have been updated, but it still seems very reasonable that one might hit this and be confused by the error message given.

**Describe the bug**

Omitting the https:// scheme from a parameter value causes an error having to do with the parameter set (and not an accurate projection of the set at that). It does not explain the validation failure against the value itself.

This occurs when using Azure Functions with the new 5.0.0 storage extension and attempting to use an identity-based connection. The setup works perfectly fine, but if I take the `blobTrigger__blobServiceUri` and just remove https:// from it, the following error is thrown:

```
Error indexing method 'BlobTrigger' Unable to find matching constructor while trying to create an instance of BlobServiceClient.
Expected one of the follow sets of configuration parameters:
1. connectionString
2. serviceUri
3. serviceUri, credential:accountName, credential:accountKey
4. serviceUri, credential:signature
5. serviceUri

Found the following configuration keys: queueServiceUri, credential, clientId, blobServiceUri 
```

This feels like the wrong error message for this situation.

**Expected behavior**
I would expect the error to indicate something about the value of the blobServiceUri parameter missing the scheme or similar.

**Actual behavior (include Exception or Stack Trace)**
(See above)

**To Reproduce**

1. New Functions project in VS 2022
2. Create a default blob trigger from template
2. `dotnet add package Microsoft.Azure.WebJobs.Extensions.Storage --version 5.0.0`
2. Set up the identity-based connection per https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=csharp#connections (deployed to Windows Consumption app using a user-assigned identity granted Storage Blob Data Reader role)
3. Behold it working properly
4. Remove "https://" from the blobServiceUri suffixed setting.
5. You should see the error above.

**Comment by mattchenderson** [comment]
Update here: there's a variant of this caused by using only the `blobServiceUri` and not including `queueServiceUri` in a blob trigger context. The same error is presented, except it instead refers to "an instance of QueueServiceClient."

I'm not sure if this is the same issue exactly - it could be a different cause and need a separate tracking item.

I'll be submitting an update to the docs which more clearly expresses the need for the queueServiceUri parameter, but I think it's a surprise no matter what, and the error message needs to help the customer understand when they reasonably just set things up for Blob Storage.

**Comment by vlkuznet** [comment]
@mattchenderson  Would it be reasonable to have an aka.ms short link to the docs, within the emitted error message?

**Comment by Ioana37** [comment]
I think the issue your are describing is related to the usage of the `blobServiceUri` configuration parameter.
If you use `serviceUri` and remove the `https://` part, the resulting error message is `System.Private.Uri: Invalid URI: The format of the URI could not be determined` which clearly points to the underlying issue.
