### ISSUE TITLE
[FEATURE REQ] Bring back Table binding, along with TableEntity

### ISSUE THREAD

**Issue by Jawz84** [Azure/azure-sdk-for-net#25342]
**Microsoft.Azure.WebJobs.Extensions.Storage.Table**

Table binding is a useful feature from a function app perspective. I do not understand why this is not even mentioned in the release notes for 5.0.0.

In my case, my website is using Table storage as a simple, lightweight database. I wanted to upgrade all packages to latest to stay current. from 4.0.5 to 5.0.0 breaks. I have to stay on 4.0.5 which is sad.

**Comment by wmeints** [comment]
I'm running into the same issues. The binding is perfect for scenarios where you have a reasonable amount of data you want to keep in a table without relationships or constraints. Removing it makes working with tables a lot harder since I now have to manually set up the connection etc. I would love to see this return to the SDK.

**Comment by GitMarJansen** [comment]
It took me a while to discover this functionality is removed / no longer supported. Can you please add it again?

**Comment by amishra-dev** [comment]
@christothes fyi

**Comment by patricktownley** [comment]
Agreed - table storage is incredibly powerful paired with functions for lightweight apps / services, or automating data collection while keeping things serverless & low entry cost.

**Comment by tomasr** [comment]
Wrong move. Agreed this is extremely useful functionality. Our telemetry pipeline is written on top of Storage Tables and it's a wonderful system.

**Comment by oising** [comment]
"But but but, please use CosmosDB instead and throw your cash into the inexplicable, incalculable void" - I think that's the real answer here. Microsoft, this is below the belt behavior. Reinstate.

**Comment by AlexGhiondea** [comment]
Hi!
 
Thank you for raising this issue. We did not plan to drop support for Azure Tables from the latest Extensions version and **we are working on adding support for it**. The new extension will be based on the latest [Azure.Data.Tables](https://www.nuget.org/packages/Azure.Data.Tables/) package and we hope to have a beta version of it released early next year.
 
In the meantime, there are a couple of workarounds if you are using Azure Tables:
- Remain on the older version of the Functions Extensions which has support for Tables until the new extension is released
- Directly interact with the Azure Tables service from the Azure Function code by using the Azure.Data.Tables library linked above.

Please reach out if you have any more questions about this.

**Comment by Jawz84** [comment]
Thank you @AlexGhiondea for clarifying. I look forward to the teams work in the new year. 

Given the recent events around dotnet foundation and the hot reload issue as well, I could not help a slight feeling of suspicion finding out the temporary drop of Table binding as you have now explained, was not in the release notes? The release notes are the only way we can know what's going on. Leaving this out, to me, is not the best look of transparency for Microsoft given recent events. I hope you don't mind me saying that. 

Thanks a gain for clarifying, I think it is great news that the product is going to be based on the latest Azure.Data.Tables bits!

KInd regards,
Jos

**Comment by AlexGhiondea** [comment]
@Jawz84 thank you for your feedback!

I agree that we could have been more explicit in our communication here. We did have a note in the [change-log of the first release](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage/CHANGELOG.md#500-beta1-2020-11-10) of the Extension package, but that note was definitively not easy to spot.

We are updating our docs to call out this limitation and hopefully reduce the confusion around this.

I will ping this thread once we have a package that we can share if you are interested in trying it out!

**Comment by Jawz84** [comment]
Thanks, now I see that you did mention this, but for the initial beta release only. I have overlooked this, I'm sorry. It would have helped if this would have been reiterated in the GA release notes. 

Thanks again for responding and addressing this!

I am sure me and other people in this thread will be happy to try the rewritten Table binding once it is ready! 👍

**Comment by pakrym** [comment]
Hello friends, Happy New Year!

We have a preview version of `Microsoft.Azure.WebJobs.Extensions.Tables` package available on our nightly feed.

To use it add the following entry to your NuGet.config:

```xml
  <packageSources>
	...
    <add key="azure-sdk-for-net" value="https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json" />
  </packageSources>
```

And reference the `Microsoft.Azure.WebJobs.Extensions.Tables` `1.0.0-alpha.20220103.4` package.

```xml
	  <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Tables" Version="1.0.0-alpha.20220103.4" />
```

You can now use `TableAttribute` as before. https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Microsoft.Azure.WebJobs.Extensions.Tables/README.md has some usage samples.

A few notes:
- Binding to custom model types should work without any changes
- Binding to types from the `Microsoft.Azure.Cosmos.Table` like DynamicEntity won't work anymore. You'll have to change to binding to the new `TableEntity` (https://docs.microsoft.com/en-us/dotnet/api/azure.data.tables.tableentity?view=azure-dotnet) type.
- The new extension supports connection string authentication as well as secretless token credential authentication. You can find configuration patterns for those in the [readme](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Microsoft.Azure.WebJobs.Extensions.Tables/README.md).

Please give the extension a try and file issues if you find any problems.

**Comment by Jawz84** [comment]
I tried this out, following the instructions, and double checking. I am not sure I am doing it right though, because I get this build error: 
`The type or namespace name 'TableEntity' could not be found (are you missing a using directive or an assembly reference?)` On two files that are basically like this:

```c#
using Microsoft.Azure.WebJobs.Extensions.Tables;

namespace explainpowershell.models
{
    public class HelpEntity : TableEntity
    {
        <props>
    }
}
```

In the root of my project I have a `NuGet.config` with
```xml
<configuration>
    <packageSources>
        <add key="azure-sdk-for-net" value="https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

And the relevant .csproj files have the new `packageReference` instead of the old one. I have done `dotnet clean && dotnet restore && dotnet build`.

I changed the `using` from 
`using Microsoft.Azure.WebJobs.Extensions.Storage;`
to 
`using Microsoft.Azure.WebJobs.Extensions.Tables;`
No other code changes.

**Comment by gfoidl** [comment]
@Jawz84 after adding a `nuget.config` I'm always restarting VS in order to reflect the new nuget sources.
CLI (aka using dotnet directly) isn't as demanding here.
Hope this help.

https://github.com/Azure/azure-sdk-for-net/issues/25342#issuecomment-1004454663 worked for me (and there's already a newer version out).

**Comment by pakrym** [comment]
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Tables/1.0.0-beta.1

**Comment by AlexGhiondea** [comment]
Hi everyone! I wanted to circle back here and announce that we have released the GA version of this library:
https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Tables/1.0.0

**Comment by jedicoder88** [comment]
Getting this error
`Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Extensions.Tables: Can't bind Table to type 'Microsoft.Azure.Cosmos.Table.CloudTable'.`
with the new `Microsoft.Azure.WebJobs.Extensions.Tables` 1.0.0 so going back to Extensions.Storage v4 now and removing the Extensions.Tables package. Not sure if I am doing something wrong

**Comment by jsquire** [comment]
Hi @jedicoder88.   Thank you for your feedback and we regret that you're experiencing difficulties.   Would you be so kind as to open an issue with additional details for your scenario and include the full stack trace for the exception that you're seeing?
