### ISSUE TITLE
[FEATURE REQ] RESILIENCY: GA Support ESTS-R in Azure.Identity SDK

### ISSUE THREAD

**Issue by tommymarkmamake** [Azure/azure-sdk-for-net#25340]
**Library or service name.**
What library or service is this request related to? [e.g. Azure.Storage.Blobs] 

Azure.Identity SDK 
 
**Is your feature request related to a problem? Please describe.**
What feature would you like to get added? What problem is it solving?

Our 1st party app Dev is blocked for using Azure. Identity SDK to adopt ESTS-R, due to the lack of autodetect region in GA.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @tommymarkmamake Could you describe a bit more detail about what you are trying to accomplish including any example code or errors you currently receive?

**Comment by tommymarkmamake** [comment]
Hello @christothes 
For Sure Happy to explain more! 
So with the newest Azure. Identity SDK, only supports ESTS-R via a global environment variable, which the dev needs to configure. However, it will not be for some of the 1st party clients, since they need to change the regional endpoints based on the cloud authority they target. They would need to have the Autodetact endpoint to help to support ESTS-R. However, Azure. Identity does not support that today.

**Comment by christothes** [comment]
You should be able to set your RegionalAuthority to "TryAutoDetect" via this environment variable:

https://github.com/Azure/azure-sdk-for-net/blob/72630d5bb04538967195c199632d8260133d25e5/sdk/identity/Azure.Identity/src/EnvironmentVariables.cs#L31

The [RegionalAuthority API ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/RegionalAuthority.cs)will be exposed as public in an up-coming release of Azure.Identity. 

https://github.com/Azure/azure-sdk-for-net/blob/72630d5bb04538967195c199632d8260133d25e5/sdk/identity/Azure.Identity/src/RegionalAuthority.cs#L85

**Comment by tommymarkmamake** [comment]
Hello @christothes 

I believe this issue is not addressed here. Let me try to clarify a bit more. I quote from the Azure.Identity release notes "_Removed RegionalAuthority from ClientCertificateCredentialOptions and ClientSecretCredentialOptions, along with the RegionalAuthority type. This feature will stay in preview, and these APIs will be added back in 1.6.0-beta.1." It seems customers do not have this support in the current 1.5.0 version and it will be added back in the 1.6.0 beta version, which is a preview version right? Our 1st party APP developers could not take a dependency on a preview version of the SDK in their services running in prod. So Our ask here is to make the regional endpoints support in PROD/ GA ( not in preview). We have more than 10+ high usage customers who are blocked due to this issue, and without ESTS-R, all of their apps/services are in the frontline to get compromised during an outage. Does it make a bit more sense? Happy to join a call with you.

**Comment by christothes** [comment]
Discussed offline - I think we are good now.
