### ISSUE TITLE
For Connection String support, highlight Azure.Identity instead of older library

### ISSUE THREAD

**Issue by harre096** [Azure/azure-sdk-for-net#25354]
The Connection String Support section should mention [Azure.Identity Migration](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration) instead of focusing solely on AzureServiceTokenProvider, which is part of the older, "no longer recommended" Microsoft.Azure.Services.AppAuthentication library.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56851479-9543-a30c-37da-a1852def3797
* Version Independent ID: 4b2f90e7-dbfb-a811-64ff-9eea8b5b7443
* Content: [App Authentication client library for .NET - Version 1.6.0 - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication#connection-string-support)
* Content Source: [api/overview/azure/service-to-service-authentication.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/service-to-service-authentication.md)
* Product: **azure**
* GitHub Login: @jlichwa
* Microsoft Alias: **jalichwa**

**Comment by amnguye** [comment]
@jlichwa Is this supposed to be assigned to storage, or supposed to be assigned to identity to update the docs?

**Comment by jlichwa** [comment]
@harre096 not sure I understand. This  documentation for legacy App Authentication library. For Azure Identity library you should use go to this document:
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme

**Comment by harre096** [comment]
Exactly. Can we add some memo on the page saying what you just told me?
It's not clear that this is legacy when I landed here from Google.

**Comment by harre096** [comment]
Actually come to think of it I think it was the user assigned identity page
that dumped me here to find connection string formats. Maybe that's the
link that needs to be updated.

**Comment by harre096** [comment]
I guess you can close it if you want, as the message you are saying is included in the purple box at the top of the page. Basically I didn't read the disclaimer at the top of the page so I opened this bug asking for greater clarity around the very same topic. I missed the note either because I was moving fast or the link I followed jumped me down into the page. While I still believe that more clarity could be added in the body of this page saying these steps are no longer recommended, I can see that a big part of the folly was me reading fast.
