### ISSUE TITLE
Task-based APIs

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-sdk-for-net#2535]
Hello!

First of all, GREAT work on the new libraries. Its about time to have a clear way to have management APIs well defined and easy to use.

Two questions:

1. I don’t see Azure SQL on that GH pages, will it be available soon?
2. Those operations usually takes time to provision resources… Can we have it return a Task so we can await it? The way it is today blocks the thread until the whole operation instead of return a promise and release the main (UI)thread and be “TPL-friendly”. In case there is no plan now, can we contribute to it with a PR? I think at least the write/commit and read operations must be “awaitable”.

Keep the great work! I’m looking forward to build a tool on top of it.

Thanks!
Best regards,
Gutemberg

**Comment by markcowl** [comment]
@hovsepm @jianghaolu  Please assign this issue to a milestone so that customers can track the fix timeline

**Comment by martinsawicki** [comment]
with the introduction of the asynch methods over the past few releases on pretty much all the exposed models, I think we've addressed the original request.
