### ISSUE TITLE
[FEATURE REQ] Add support for certificate thumbprint to EnvironmentCredential and ClientCertificateCredential

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#25360]
See #11804 for details

**Comment by JaredShaver** [comment]
Is this feature planned or would you be willing to accept a community contribution?

**Comment by christothes** [comment]
There are currently no plans for it - the main reason being that this is tricky to implement cross platform. Given that it is fairly trivial to write the certificate loading code for Windows, we felt that the value add is minimal when weighed against the work to make it solid on MacOS and Linux.

**Comment by JaredShaver** [comment]
It is actually not trivial because the AzureKeyVaultConfigBuilder does not have an extension point that allows the user to override the credential.  It is hard coded to use DefaultAzureCredential().  How does a user use AzureKeyVaultConfigBuilder with a certificate from the Windows certificate store?

**Comment by christothes** [comment]
If you are using `Azure.Extensions.AspNetCore.Configuration.Secrets` there is an example here: https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-6.0

**Comment by JaredShaver** [comment]
We are using https://github.com/aspnet/MicrosoftConfigurationBuilders because it is .NET Framework applications, not .NET Core/5/6.  If there was a way to provide an environment variable that gave a user provided class that was derived from TokenCredential and use that so end users can provide their own logic for looking up certificates, that would be a platform independent option.

**Comment by tegrit-joe-trupiano** [comment]
Second your comment! @JaredShaver 
Just found this issue and would very much like a way to allow the use of certificate for the .NET framework.

**Comment by christothes** [comment]
> We are using https://github.com/aspnet/MicrosoftConfigurationBuilders because it is .NET Framework applications, not .NET Core/5/6. If there was a way to provide an environment variable that gave a user provided class for creating the credential that so end users can provide their own logic for looking up certificates, that would be a platform independent option.

Could you describe how such an environment variable would work? Why not just initialize your custom class in your app startup and have it place the certificate in a well known path which is set on the AZURE_CLIENT_CERTIFICATE_PATH environment variable?

**Comment by JaredShaver** [comment]
It looks like I am not the only one who needs to customize the way the credential is initialized.  There is a PR against the MicrosoftConfigurationBuilders repo that addresses the problem https://github.com/aspnet/MicrosoftConfigurationBuilders/pull/142 but nobody is reviewing or approving it.

**Comment by wg-davegriffiths** [comment]
Yes, that PR was done in response to me raising this issue: https://github.com/aspnet/MicrosoftConfigurationBuilders/issues/117 . The Azure.Identity change in ConfigBuilders had too strict a convention compared to how it did work (connections strings), and back then, hardly any of the VS integrated credential providers worked with DefaultAzureCredential.

**Comment by wg-davegriffiths** [comment]
Could AZURE_CLIENT_CERTIFICATE_PATH be made to recognize a uri format that will load from the cert store?  Path could be similar to the Powershell Certificate provider paths i.e. cert:\CurrentUser\My\52A149D0393CE8A8D4AF0B172ED667A9E3A1F44E  

It wouldn't necessarily be Windows specific as the core framework does map some of the cert store locations to folder locations, across non-window platforms according to:
https://github.com/dotnet/runtime/issues/27658

**Comment by christothes** [comment]
You can also fetch the certificate from the store and pass it directly to the credential as an `X509Certificate2`, so it doesn't need to be on disk.

**Comment by christothes** [comment]
duplicate of #27315
