### ISSUE TITLE
Trying to use sdk to manage aks cluster

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#25369]
### Discussed in https://github.com/Azure/azure-sdk-for-net/discussions/24783

<div type='discussions-op-text'>

<sup>Originally posted by **D3m1urg3** October 18, 2021</sup>
I'm trying to use azure .net sdk in order to manage my azure kubernetes infrastructure without the need of the cli. More specifically, I want to be able to:

1. Create a resource group.
2. Create an aks cluster within the group.
3. Create aditional nodepools.
4. Add inbound rules to the nsg.
5. Delete an aks cluster.
6. Delete a security group.

I manage to do all of these using az cli. But I did not managed to use the sdk to do it. I've been searching through the packages and the documentation without success so far. 

Help will be appreciated.</div>

**Comment by AlexGhiondea** [comment]
@allenjzhang could you help with this?

**Comment by pallavit** [comment]
@ArthurMa1978 not sure if this is still valid assigning it to you for triaging as you see appropriate.

**Comment by mcgallan** [comment]
Hi @AlexGhiondea , Thank you for your feedback. Regarding the issue you mentioned, in the latest Azure SDK,[ Azure.ResourceManager.ContainerService 1.2.0](https://www.nuget.org/packages/Azure.ResourceManager.ContainerService), we can implement the functionality you need with the following code (please adjust the specific parameters according to your needs):
```
Client = new ArmClient(TestEnvironment.Credential);
Subscription = await Client.GetDefaultSubscriptionAsync();
string rgName = Recording.GenerateAssetName("rgName");
ResourceGroupData input = new ResourceGroupData(AzureLocation.EastUS);
var resourceGroup = (await Subscription.GetResourceGroups().CreateOrUpdateAsync(WaitUntil.Completed, rgName, input)).Value;
var securityRule = new SecurityRuleData()
{
    Protocol = SecurityRuleProtocol.Tcp,
    SourcePortRange = "*",
    DestinationPortRange = "80",
    SourceAddressPrefix = "*",
    DestinationAddressPrefix = "*",
    Access = SecurityRuleAccess.Allow,
    Priority = 100,
    Direction = SecurityRuleDirection.Inbound,
    Name = "AllowHTTPInbound"
};
var nsgData = new NetworkSecurityGroupData()
{
    SecurityRules = { securityRule }
};
var subnetsData = new SubnetData()
{
    AddressPrefix = "10.0.0.0/24",
    NetworkSecurityGroup = nsgData
};
var subnetResource = await resourceGroup.GetVirtualNetworks().GetAsync("vnet1").Result.Value.GetSubnets().CreateOrUpdateAsync(WaitUntil.Completed, "subnet1", subnetsData);
var clusterData = new ContainerServiceManagedClusterData(location == null ? resourceGroup.Data.Location : location.Value)
{
    AgentPoolProfiles =
    {
        new ManagedClusterAgentPoolProfile(AgentPoolProfileName)
        {
            VmSize = VmSize,
            Count = 1,
            Mode = AgentPoolMode.System,
            VnetSubnetId  = new ResourceIdentifier(subnetResource.Id)
        }
    },
    DnsPrefix = DnsPrefix,
    Identity = new ManagedServiceIdentity(ManagedServiceIdentityType.SystemAssigned),
};
var lro = await resourceGroup.GetContainerServiceManagedClusters().CreateOrUpdateAsync(WaitUntil.Completed, clusterName, clusterData);
var resource = lro.value;
```
Regarding the deletion feature you wish to implement, you can use the following method: `await containerService.DeleteAsync(WaitUntil.Completed);` to perform the operation (where containerService can be replaced with any resource you need to delete).
