### ISSUE TITLE
Best way to replace destination blob with source, only if they're different?

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#25367]
### Discussed in https://github.com/Azure/azure-sdk-for-net/discussions/25146

<div type='discussions-op-text'>

<sup>Originally posted by **irontoby** November  4, 2021</sup>
I want to determine whether two blob storage objects (in different containers) have identical contents. If they do not have the same contents, I want to update one with the contents of the other. It appears that the most straightforward way to do this is something like the following:

```csharp
var sourceBlobClient = context.SourceClient.GetBlobClient(blobName);
var destBlobClient = context.DestClient.GetBlobClient(blobName);

using var sourceStream = await sourceBlobClient.OpenReadAsync(readOptions, cancellationToken);
var sourceData = await BinaryData.FromStreamAsync(sourceStream, cancellationToken);

using var destStream = await destBlobClient.OpenReadAsync(readOptions, cancellationToken);
var destData = await BinaryData.FromStreamAsync(destStream, cancellationToken);

if (!((ReadOnlySpan<byte>)sourceData).SequenceEqual(destData))
    await destBlobClient.UploadAsync(sourceData, true, cancellationToken);
```

Does this check out? It seems like implementing `SequenceEquals` directly on `BinaryData` would be useful...</div>

**Comment by amnguye** [comment]
You could also look into comparing the Content MD5 of the blobs and see if they match as well.

@seanmcc-msft @jaschrep-msft If you have any better ideas.

**Comment by seanmcc-msft** [comment]
@amnguye think that is the best solution.  Then the customer only has to make a `GetProperties()` call instead of downloading the whole blob.

**Comment by jaschrep-msft** [comment]
Comparing hashes will be the easiest way to compare blobs, however be aware that the content md5 blob property is a user-settable property* and it is up to you to ensure the property is set and correct. If you do not already have these properties set then you will need to download the blob to compare (and maybe set the hash after comparison for quick operations in the future).

* As of service version 2012-02-12, if the blob was uploaded via PUT Blob, the service will automatically calculate an MD5 and populate the property. It will not do this if the blob contents were uploaded via a different rest API (e.g. PUT Block / PUT block list).

**Comment by irontoby** [comment]
Thanks for the tips everyone! I wasn't aware of the MD5 property; I'll update my logic to use that instead. We "own" the blobs so no worries about it being user-settable.

**Comment by amnguye** [comment]
Closing the issue.

Please comment tag respectively if you have any other questions, otherwise feel free to open a new issue.
