### ISSUE TITLE
ServiceBusMessage constructor overload with behavior to match Body.ToObjectFromJson<T>

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#25368]
### Discussed in https://github.com/Azure/azure-sdk-for-net/discussions/24616

<div type='discussions-op-text'>

<sup>Originally posted by **danleonard-nj** October  9, 2021</sup>
Sorry in advance if this is already out there somewhere and I'm just missing it.  I think it'd be nice to have an overload for ServiceBusMessage that took an object and serialized it w/ JsonSerializer, so you can pass the objects straight into the message constructor instead of serializing it then passing it in as a string. 

It doesn't save a ton of mileage, but considering there's an equivalent method for deserializing the message body, seems sensible that there'd be one on the message constructor.  Obviously passing JSON data in the body is pretty common practice.

Definitely a nice-to-have, but anything to reduce the clutter is always a win.</div>

**Comment by JoshLove-msft** [comment]
This sounds like a good enhancement request that we can look into for a future release.

**Comment by jsquire** [comment]
This behavior is now handled by `BinaryData` so that it is consistent across different libraries of the Azure SDK.  

```csharp
var message = new ServiceBusMessage(new BinaryData(someObject));
```

Closing this out.
