### ISSUE TITLE
DataDeletionDetectionPolicy in SearchIndexerDataSourceConnection

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-net#25365]
### Discussed in https://github.com/Azure/azure-sdk-for-net/discussions/25201

<div type='discussions-op-text'>

<sup>Originally posted by **quisitive-mkushnirsky** November  8, 2021</sup>
Is there a way to specify connection.DataDeletionDetectionPolicy when creating or updating datasource for indexer? 
</div>

**Comment by Mohit-Chakraborty** [comment]
We can set the `DataDeletionDetectionPolicy` property on `SearchIndexerDataSourceConnection` any time before calling `CreateDataSourceConnection()` on a `SearchIndexerClient` object.
