### ISSUE TITLE
Some typos in `System.IdentityModel.Tokens.Jwt/JwtHeader`

### ISSUE THREAD

**Issue by ShikaTech** [Azure/azure-sdk-for-net#25371]
Some comments look like typos.

- typo1 - https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtheader.-ctor?view=azure-dotnet#System_IdentityModel_Tokens_Jwt_JwtHeader__ctor_Microsoft_IdentityModel_Tokens_EncryptingCredentials_System_Collections_Generic_IDictionary_System_String_System_String__
  - `{ { typ, JWT }, { alg, SigningCredentials.Algorithm } }`
    - Is this `{ { typ, JWT }, { alg, EncryptingCredentials.Alg }, { enc, EncryptingCredentials.Enc } }`?
  - `EncryptingCredentials used when creating a JWS Compact JSON.`
    - Is this `JWE`? instead of `JWS`.
- typo2 - https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtheader.-ctor?view=azure-dotnet#System_IdentityModel_Tokens_Jwt_JwtHeader__ctor_Microsoft_IdentityModel_Tokens_EncryptingCredentials_System_Collections_Generic_IDictionary_System_String_System_String__System_String_
  - `{ { typ, JWT }, { alg, SigningCredentials.Algorithm } }`
    - Is this `{ { typ, JWT }, { alg, EncryptingCredentials.Alg }, { enc, EncryptingCredentials.Enc } }`?
  - `EncryptingCredentials used when creating a JWS Compact JSON.`
    - Is this `JWE`? instead of `JWS`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 392e9ed5-0b94-46b0-a762-5d20c3cee471
* Version Independent ID: de52ca92-4503-17e0-bd7e-c0413c0e6747
* Content: [JwtHeader Constructor (System.IdentityModel.Tokens.Jwt) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtheader.-ctor?view=azure-dotnet#feedback)
* Content Source: [xml/System.IdentityModel.Tokens.Jwt/JwtHeader.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/System.IdentityModel.Tokens.Jwt/JwtHeader.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `System.IdentityModel.Tokens.Jwt` package is maintained as [#1777](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1777).
