### ISSUE TITLE
Add a way to get replication links for a SQL Azure database

### ISSUE THREAD

**Issue by couellet** [Azure/azure-sdk-for-net#2537]
It would be handy to be able to retrieve the replication role of a SQL Azure database with the client. 

Looks like the [replication links](https://msdn.microsoft.com/en-us/library/azure/mt600929.aspx) are available through the SDK yet.

**Comment by akromm** [comment]
@couellet You can find the replication link operations here: https://github.com/Azure/azure-sdk-for-net/blob/master/src/ResourceManagement/Sql/SqlManagement/Generated/ReplicationLinkOperationsExtensions.cs
