### ISSUE TITLE
Updating from 4.2.1 to 5.1.0 introduces issue with MessageReceiver 

### ISSUE THREAD

**Issue by jenp-jb** [Azure/azure-sdk-for-net#25375]
**Query/Question**
Upgrading the extension nuget package from 4.2.1 to 5.1.0 resulted in IMessageReceiver and MessageReceiver in my function / class becoming unknown. I use this in order to be able to Complete and Deadletter messages according to our logic as some failures will never succeed so there's no point retrying.

I tried to fix this by installing the deprecated Microsoft.Azure.ServiceBus nuget package 5.2.0. This allows for the code to be compiled but running the function gives me the error:
Microsoft.Azure.WebJobs.Host: Error indexing method 'XXX'. Microsoft.Azure.WebJobs.Host: Can't bind parameter 'messageReceiver' to type 'Microsoft.Azure.ServiceBus.Core.MessageReceiver'.  
The reason I use IMessageReceiver is for moq unit test purposes so I can assert that a message was completed/deadlettered as expected.

![image](https://user-images.githubusercontent.com/77314668/142131639-016fd369-3880-47c5-bcab-268cbb071b3d.png)

![image](https://user-images.githubusercontent.com/77314668/142131692-8002573d-8d12-494b-a7b1-5f3c1b89e542.png)

Whilst there is documentation on how to instantiate a MessageReceiver - I can't seem to find any reference to accessing it within the ServiceBusTriggered Function.

It doesn't seem like MessageReceiver is part of the newer Azure.Messaging.ServiceBus package as I explored using that as well.

**Environment:**
 - Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.1.0
 - Azure Function App (but also fails locally)
 -Visual Studio 16.11.5

**Comment by JoshLove-msft** [comment]
Hi @jenp-jb,
The MessageReceiver has been replaced with ServiceBusMessageActions in version 5.0.0. Please have a look at our [samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus#message-settlement) to see how this type is used.

**Comment by jenp-jb** [comment]
@JoshLove-msft  So I have an internal property on my function that I set in the test with a mock so that I can verify completed or deadlettered was called as expected:

![image](https://user-images.githubusercontent.com/77314668/142294968-b0208734-3b68-43b4-a03f-80e52eae2748.png)

I did make some progress with the ServiceBusMessageActions but am struggling to find how to add the retryOptions to my host.json file.  For some reason Visual Studio is reporting invalid values (even if I use the example on the microsoft page) https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#additional-settings-for-version-5x

For version 4.2.1 I was using:
![image](https://user-images.githubusercontent.com/77314668/142295192-d4a29650-8ec5-4db2-9fb3-9f3b83919be1.png)

But trying to add the clientRetryOptions like so:

![image](https://user-images.githubusercontent.com/77314668/142295306-8496b3d3-0528-47c7-a432-76a2bf4ea350.png)
 gives me this warning (and doesn't have the desired impact on running my function)
![image](https://user-images.githubusercontent.com/77314668/142295358-17db9ef2-396f-44e6-b6e9-59fc8dde5d5c.png)

**Comment by srivelicheti** [comment]
@JoshLove-msft - I am also facing similar issue with being able to mock `ServiceBusMessageActions` for unit-testing purposes as it doesn't contain public parameter-less constructor. 

I see that all of the methods on this `ServiceBusMessageActions` are virtual but, trying to mock  ServiceBusMessageActions class would result in an exception because of the lack of parameter-less ctor.
![image](https://user-images.githubusercontent.com/3229242/142372761-215a7d91-30a9-4798-9744-af0fcd8363a4.png)

Most of the other SDK classes like `ServiceBusClient` or `ServiceBusMessageReceiver` have a parameter-less ctor to aid in unit-testing. Any chance of adding a parameter-less ctor? If not, can you please help with any alternate options to mock this class?

Appreciate your help, this is blocking us from migrating to .net6.0 and v4 azure functions.

**Comment by JoshLove-msft** [comment]
Yes, it looks like we are missing the mocking constructor for the actions types - we will get this added in an upcoming release.

**Comment by srivelicheti** [comment]
> Yes, it looks like we are missing the mocking constructor for the actions types - we will get this added in an upcoming release.

Thank you, would it be possible to give an ETA on the next release cycle?

**Comment by JoshLove-msft** [comment]
> > Yes, it looks like we are missing the mocking constructor for the actions types - we will get this added in an upcoming release.
> 
> Thank you, would it be possible to give an ETA on the next release cycle?

Will have to get back to you on this. When do you need this by?

**Comment by jenp-jb** [comment]
@JoshLove-msft any ideas on my config errors I was getting or should I create a different thread?

Keen on knowing the ETA for the next release cycle too as that's a blocker for us upgrading.

**Comment by JoshLove-msft** [comment]
Hi @jenp-jb, I will try to repro this and get back to you.

**Comment by JoshLove-msft** [comment]
A new release is available with the constructors required for mocking - https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.2.0

Regarding the schema validation, I was able to reproduce this and will look into getting this fixed.

**Comment by AbhishekTripathi** [comment]
MessageReceiver provided APIs to manually renew the message lock token using `RenewMessageLockAsync`. These APIs are no longer available under `ServiceBusMessageActions`. In our scenario, we renew the locks using these APIs as we find the auto-renewal not reliable when the infrastructure is under stress. The documentation doesn't state anything about it. Can someone kindly provide me guidance on how we can manually renew the message lock?
