### ISSUE TITLE
How do you convert a connection string into parts?

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/azure-sdk-for-net#25378]
How do I convert a connection string into `new ClientSecretCredential(tenantId, appId, secret)` ?

I don't really want to change all the existing connection strings.

Should the code from **Microsoft.Azure.Services.AppAuthentication AzureServiceTokenProviderFactory** be included?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f95d1f9-f552-ab33-2cbb-f5bc09f6cf5f
* Version Independent ID: 76c243d5-0e9f-cb8d-8919-a06e75ad2cf5
* Content: [App Authentication to Azure Identity Migration Guidance - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration)
* Content Source: [api/overview/azure/app-auth-migration.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/app-auth-migration.md)
* Product: **azure**
* GitHub Login: @jlichwa
* Microsoft Alias: **jalichwa**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @mikeblakeuk We have no plans to add this support to Azure.Identity. Could you describe your scenario in which connection strings are necessary? Have you considered migrating to managed identity which allow elimination of all secrets from your code and configuration?

**Comment by mikeblakeuk** [comment]
We are working towards removing connection strings.
We are working towards using managed identity.
But this takes time. We need to upgrade first and move existing, deployed production sites slowly.
We can't just big bang, rewrite he world in one go.

A small, backwards compatible method would have been nice to help people migrate.

We have ended up, reflecting on 
Microsoft.Azure.Services.AppAuthentication AzureServiceTokenProviderFactory
**AzureServiceTokenProviderFactory**
and using that :(
