### ISSUE TITLE
Please update about GA release of this package as we want to use it in our production environment

### ISSUE THREAD

**Issue by pvadhera** [Azure/azure-sdk-for-net#25380]
**Query/Question**
How can we help?

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Hi @pvadhera.   Thank you for reaching out and we regret that you're experiencing difficulties.   Unfortunately, there's not enough context available for us to assist.   Would you be so kind as to help us understand what package you're asking about?

**Comment by jsquire** [comment]
Since we haven't heard from you and there's no context that would be lost, I'm going to close this out.  Please feel free to open a new issue with additional detail if you're still in need of assistance.
