### ISSUE TITLE
[BUG] Cannot add List of Source/Destination Ports on new SecurityRuleData/NetworkSecurityGroupData

### ISSUE THREAD

**Issue by LeonB87** [Azure/azure-sdk-for-net#25385]
**Describe the bug**
I'm using the Azure.ResourceManager.Network SDK to create NSG's. However, I cannot add a range of ports on either the Destination or Source port ranges.

The property DestinationPortRange**s** and SourcePortRange**s** are read-only, so the only option is to use the DestinationPortRange and SourcePortRange property.

I've tried different values for the port range:

```c
DestinationPortRange = "[80,443]"
DestinationPortRange = "80,443"
DestinationPortRange = "80;443"
```

**Expected behavior**
being able to add multiple Port ranges into 1 NSG Rule

**Actual behavior (include Exception or Stack Trace)**

```c
Security rule has invalid Port range. Value provided: [80,443]. Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535.
Status: 400 (Bad Request)
ErrorCode: SecurityRuleInvalidPortRange

Content:
{
  "error": {
    "code": "SecurityRuleInvalidPortRange",
    "message": "Security rule has invalid Port range. Value provided: [80,443]. Value should be an integer OR integer range with '-' delimiter. Valid range 0-65535.",
    "details": []
  }
}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-request-id: 92972ce2-c51a-4528-87c4-03715a85c055
x-ms-client-request-id: 445e7d95-7f75-4459-a399-ed5391833f15
x-ms-correlation-request-id: REDACTED
x-ms-arm-service-request-id: REDACTED
Strict-Transport-Security: REDACTED
Server: Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-routing-request-id: REDACTED
X-Content-Type-Options: REDACTED
Date: Wed, 17 Nov 2021 16:41:29 GMT
Content-Length: 255
Content-Type: application/json; charset=utf-8
Expires: -1

```
**To Reproduce**

```c
using System;
using System.Collections.Generic;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Network;
using Azure.ResourceManager.Network.Models;
using Azure.ResourceManager.Resources;
using Newtonsoft.Json;


ArmClient _armClient = new ArmClient(new ClientSecretCredential(tenantId, clientId, clientSecret));

Subscription subscription = _armClient.GetSubscription($"/subscriptions/{_subscriptionId}/");

ResourceGroup rg = subscription.GetResourceGroups().GetAsync(resourcegroupName).Result;

var nsgContainer = rg.GetNetworkSecurityGroups();

NetworkSecurityGroupData newNSG = new NetworkSecurityGroupData()
{
    Location = "westeurope"
};

SecurityRuleData securityRuleData = new SecurityRuleData()
{
    Name = "testrule1",
    Access = SecurityRuleAccess.Allow,
    Direction = SecurityRuleDirection.Inbound,
    DestinationPortRange = "[80,443]",
    DestinationAddressPrefix = "*",
    SourceAddressPrefix = "*",
    SourcePortRange = "*",
    Protocol = SecurityRuleProtocol.Asterisk,
    Type = "CUSTOM",
    Priority = 300,
    Description = "Creating rule from Csharp"
};

newNSG.SecurityRules.Add(securityRuleData);

try
{
    NetworkSecurityGroupCreateOrUpdateOperation operation = nsgContainer.CreateOrUpdate("testNSG2", newNSG);
} catch (Exception Ex)
{
    var test = Ex.Message;
    throw;
}

```

**Environment:**
```
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
  </PropertyGroup>
```

    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="3.1.21" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.1.20" />
    <PackageReference Include="Microsoft.Graph" Version="4.10.0" />
    <PackageReference Include="Microsoft.Graph.Auth" Version="1.0.0-preview.7" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.36.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="System.Text.Encodings.Web" Version="6.0.0" />

Running an Azure Function project using IDE 2019 16.11.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by archerzz** [comment]
@LeonB87 This is a tricky part in track2 mgmt SDK that we follow the .Net guidelines. Especially, for collection properties, we follow [this one](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values):

> DO NOT provide settable collection properties.

For your case, you could add `80` and `443` by:

```csharp
securityRuleData.DestinationPortRanges.Add(80);
securityRuleData.DestinationPortRanges.Add(443);
```

**Comment by LeonB87** [comment]
Hi Archerzz,

Thank-you for your reply.   
That seems to works fine.

```c#
securityRuleData.DestinationPortRanges.Add("443");
securityRuleData.DestinationPortRanges.Add("5000-5100");
```

Adding an entire port range like the above works as well.

> ![image](https://user-images.githubusercontent.com/10503724/151511266-9e1a2514-5806-46c9-817e-50ce79954fb5.png)
