### ISSUE TITLE
[QUERY] How can we use Microsoft.Azure.Management APIs with DI in ASP.NET Core

### ISSUE THREAD

**Issue by binn** [Azure/azure-sdk-for-net#25382]
**Query/Question**
How can we use Microsoft.Azure.Management APIs with DI in ASP.NET Core
The Microsoft.Azure.Extensions package let us add services to ASP.NET Core's DI like so:
```cs
services.AddAzureClients(builder =>
{
    builder.UseCredential(new DefaultAzureCredential( // Uses default Azure credentials, or makes a pop up window in development mode
            includeInteractiveCredentials: Environment.IsDevelopment()
        ));

    builder.AddBlobServiceClient(Configuration.GetSection("Blob"));
});
```

but how would we go about using `IAzure`, for example, to spin up fire-and-forget tasks using ACI via `IAzure.ContainerGroups.Define().Create()` from within a managed DI service? Is this possible, or am I stuck with manually creating a singleton?

**Environment:**
 - Microsoft.Extensions.Azure
 - Windows 10, .NET 6
 - IDE and version : Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by binn** [comment]
Thank you, for reference, my current solution is this:
```
services.TryAddSingleton<IAzure>(builder =>
{
    var conf = Configuration.GetSection("Azure:ServicePrincipal");
    var creds = SdkContext.AzureCredentialsFactory
        .FromServicePrincipal(
            clientId: conf["ClientId"],
            clientSecret: conf["ClientSecret"],
            tenantId: conf["TenantId"],
            AzureEnvironment.AzureGlobalCloud
        );

    return Microsoft.Azure.Management.Fluent.Azure
        .Configure()
        .Authenticate(creds)
        .WithSubscription(conf["Subscription"]);
});
```
The primary reason for wanting the Fluent Management SDKs within `Microsoft.Extensions.Azure` DI is to use the same authentication context (`new DefaultAzureCredential()`) as part of the Fluent SDKs as well as the Service SDKs. ACI is not available with the new `Azure.ResourceManager` SDKs (and I'm unaware if they are usable with `Microsoft.Extensions.Azur`)

**Comment by dvbb** [comment]
Based on my understanding, I think you want to implement the Dependency Inject of `Microsoft.Azure.Management.Fluent.Azure` in ASP.NET Core, here is an example for that.

If my understanding is wrong, please feel free to give me feedback.

#### Startip.cs
``` c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllers();

    // dependency injection
    services.TryAddSingleton<IAzure>(builder =>
    {
        string clientId = "";
        string clientSecret = "";
        string tenantId = "";
        string subscription = "";

        AzureCredentials creds = new AzureCredentialsFactory().FromServicePrincipal(clientId, clientSecret, tenantId, AzureEnvironment.AzureGlobalCloud);
        IAzure azure = Azure.Authenticate(creds).WithSubscription(subscription);

        return azure;
    });
}
```

#### Controller
``` c#
namespace WebApplication.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class SqlFluentController : ControllerBase
    {
        private IAzure _azure;
        public SqlFluentController(IAzure azure)
        {
            _azure = azure;
        }

        [HttpGet]
        public string GetServerState()
        {
            string resourceGroupName = "Sql-RG-0000";
            string serverName = "server-0000";
            var server = _azure.SqlServers.GetByResourceGroup(resourceGroupName, serverName);

            return $"{server.Name}: {server.State}";
        }
    }
}
```
