### ISSUE TITLE
[QUERY] How to return EventErrorResponse on OnConnectAsync in WebPubSubHub

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-sdk-for-net#25391]
**Query/Question**

[Docs](https://github.com/Azure/azure-sdk-for-net/blob/3126951832bbf5f9b67a71cc7ed0db2cd6e0a149/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSub/README.md#using-web-pubsub-trigger):

> For example, Connect will only respect ConnectEventResponse or EventErrorResponse, and ignore other returns. When EventErrorResponse is returned, service will drop client connection

How to return `EventErrorResponse` on `OnConnectAsync` in WebPubSubHub?
The signature of `OnConnectAsync` in WebPubSubHub is the following:
```
public ValueTask<ConnectEventResponse> OnConnectAsync(ConnectEventRequest request, CancellationToken cancellationToken)
```
in that case, we cannot return something like
```
EventErrorResponse error =  request.CreateErrorResponse(WebPubSubErrorCode.Unauthorized, "Error");
return error;
```
Shouldn't it be like
```
public ValueTask<WebPubSubEventResponse> OnConnectAsync(ConnectEventRequest request, CancellationToken cancellationToken)
```
because 
`EventErrorResponse : WebPubSubEventResponse` and `ConnectEventResponse : WebPubSubEventResponse`

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.WebPubSub 1.0.0, Microsoft.Azure.WebPubSub.AspNetCore 1.0.0-beta.1
 - Hosting platform or OS and .NET runtime version: 5.0, Docker

**Comment by MohitGargMSFT** [comment]
@Marusyk  Thank you for your query. We will investigate on it and get back to you soon.

**Comment by Marusyk** [comment]
Cool, thanks. I'm going to validate user in `OnConnectAsync` and return an error when it fails. Could you please suggest how to do it with the current implementation?

**Comment by RyanHill-MSFT** [comment]
@Marusyk, I will defer to the development team but from I'm gathering, WebPubSubHub is a used to [maintain connections between the service and server](https://docs.microsoft.com/en-us/azure/azure-web-pubsub/key-concepts). Based on that, the service is what will send the `EventErrorResponse` and your server is what will receive the `OnConnectAsync` event from the service for the client to be registered. This is my speculation as I couldn't find any sample code `WebPubSubHub` class. However, we will reach out to the product group for further clarification.

**Comment by JialinXin** [comment]
@Marusyk, thanks for using our SDK. In this middleware implementation, we'd like to accept certain response to avoid mixed using of response type, i.e. return `ConnectEventResponse` under `UserEventRequest`. For the error response, user can directly throw exception and the middleware will identify the exception type to build response, `UnauthorizedAccessException` will return 401 and rest are 500. The behavior is same as identify `EventErrorRespone` in Functions, that the current client connection will be dropped.

**Comment by Marusyk** [comment]
Ok, thanks. But `request.CreateErrorResponse` is confused here

**Comment by JialinXin** [comment]
> Ok, thanks. But `request.CreateErrorResponse` is confused here

Yes. We'll improve the code comments that the methods works for Azure Functions only.
