### ISSUE TITLE
Add parameter less constructor to ServiceBusMessageActions

### ISSUE THREAD

**Issue by srivelicheti** [Azure/azure-sdk-for-net#25405]
**Library or service name.**
 Microsoft.Azure.WebJobs.Extensions.ServiceBus, Version=5.1.0.0
 
**Is your feature request related to a problem? Please describe.**
 I am facing issue with being able to mock ServiceBusMessageActions for unit-testing purposes as it doesn't contain public parameter-less constructor.

I see that all of the methods on this ServiceBusMessageActions are virtual but, trying to mock ServiceBusMessageActions class would result in an exception because of the lack of parameter-less ctor.
![image](https://user-images.githubusercontent.com/3229242/142461903-67806c03-5ab9-4200-8cbf-06f4bcc339fa.png)

Most of the other SDK classes like ServiceBusClient or ServiceBusMessageReceiver have a parameter-less ctor or have factory classes (like ServiceBusModelFactory) to aid in unit-testing. Can a parameter-less public ctor to ServiceBusMessageActions? If not what are the alternatives to be able to unit-test logic that depends on this `ServiceBusMessageActions` class?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
A protected parameterless constructor makes sense here as this is like a client type.
