### ISSUE TITLE
Scope (jwt 'scp' attribute) returned in VisualStudioCredential and in Microsoft Graph Explorer are different.

### ISSUE THREAD

**Issue by spmanjunath** [Azure/azure-sdk-for-net#25400]
**Describe the bug**
I have an Azure function that uses Managed Identity to access Graph API's (Sharepoint sites and files), in my development environment i want to rely on my VisualStudioCredential (VSC).  In my tests i have noticed that the Scopes that are returned for the same User identity in Graph explorer and using VSC are different.  

**Expected behavior**
Scopes (scp) returned for VSC should be same as the one in [Graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer).

**Actual behavior (include Exception or Stack Trace)**
scp value of jwt token returned in graph explorer:
`Files.ReadWrite.All Mail.ReadWrite Notes.ReadWrite.All openid People.Read profile Sites.ReadWrite.All Tasks.ReadWrite User.Read User.ReadBasic.All User.ReadWrite email`

scp value returned as part of VSC:
`Application.ReadWrite.All email openid profile User.ReadWrite.All`

**To Reproduce**
Azure C# function:
```
var credential = new ChainedTokenCredential( new VisualStudioCredential(), new ManagedIdentityCredential(), new AzureCliCredential());
var token = await credential.GetTokenAsync(new Azure.Core.TokenRequestContext(new string[] {
	"https://graph.microsoft.com/.default"
	
	//"00000003-0000-0000-c000-000000000000",
	//"https://graph.microsoft.com//sites.readwrite.all",
	//"https://graph.microsoft.com/Files.ReadWrite.All"
}));
accessToken = token.Token;
```
I have tried using different scope values while calling TokenRequestAsync(), with the first two scopes the results returned are same (expected), however while using the other two the request fails.  Is it possible to request for multiple scopes so as to have parity with explorer?

**Environment:**
 - Azure.Identity 1.5.0
 - Microsoft Graph 4.10.0
 - Azure SDK Functions 3.0.13
 - Azure function 3.1 (dotnet), Consumption plan
 - IDE and version : Visual Studio 2019 16.11.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @spmanjunath The reason for this difference is the permissions requested for the application being used by Graph Explorer are different than the ones being used by these credentials. If you are able to admin consent an application in your directory, you could register an application with all these permissions for that application and specify that clientId for the credential.

**Comment by spmanjunath** [comment]
/unresolve
How is Graph explorer able to get additional scopes using the same credential as VisualStudioCode?  I tried monitoring the network traffic in the browser (for graph explorer api requests), but couldn't figure out how it achieves these additional scope.  The endpoint that Graph explorer calls is same as that called by Azure.Identity libraries.  Is there a way that i could request additional scopes in my request for the token?  The parity between the access obtained from Graph explorer and VisualStudioCode is critical for better developer experience.  I would prefer to avoid having Client credential if there are better alternatives.  Thanks.

**Comment by christothes** [comment]
> is Graph explorer able to get additional scopes using the same credential as VisualStudioCode



> /unresolve How is Graph explorer able to get additional scopes using the same credential as VisualStudioCode? I tried monitoring the network traffic in the browser (for graph explorer api requests), but couldn't figure out how it achieves these additional scope. 

It does so by using a different client application.

The endpoint that Graph explorer calls is same as that called by Azure.Identity libraries. Is there a way that i could request additional scopes in my request for the token? 

Yes, you can request any number of scopes for each token request. However, you can only be granted scopes that the application has been consented for.
