### ISSUE TITLE
Suggested improvements for Key Vault tests

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#25414]
There are still a couple classes of bugs that cause occasional live test failures.

1. HTTP 500s.
2. HTTP 409s due to a recovery operation for Administration (MHSM) while Keys tests are running.

I propose either augmenting the Retry policy when instrumenting test clients, or replacing `[Test]` and `[RecordedTest]` with a `RecordedTestAttribute`-derived attribute that retries on these errors. The HTTP 409 error message will have to be scanned to see if a recovery operation was the culprit since there are other valid cases an HTTP 409 could result.

A change when instrumenting may be the easiest, most targeted fix but updating all tests to use `[RecordedTest]` or derived has its own advantages of not having to change the live test fixtures' constructors as often, like never when updating existing tests (still need to for new tests, IIRC).

**Comment by pallavit** [comment]
@heaths Is this still an issue we want to tackle?

**Comment by heaths** [comment]
Old tracking issue mostly solved with my `[IgnoreServiceError]` attribute.
