### ISSUE TITLE
Fluent management library does not work as expected in ASP.NET projects

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-sdk-for-net#2541]
We were using the following code from an ASP.NET API method (which is sync call) and the call never returns. I think somewhere in the code, it is using as async and wait. Can you please check? 
```
public void CreateResourceGroup(
            Subscription subs, string rgName, string trainee, string trainer, string wsCode, int wsId)
       {
            var azure = subs.GetAzureReference();
            var rg = azure.ResourceGroups
                            .Define(rgName)
                            .WithRegion(Region.US_WEST)
                            .Create();
       }

public static IAzure GetAzureReference(this Subscription subscription)
       {
            var credentials = AzureCredentials.FromServicePrincipal(
                                subscription.AppId,
                                subscription.AppSecret,
                                subscription.TenantId,
                                AzureEnvironment.AzureGlobalCloud);
            return Azure.Authenticate(credentials).WithSubscription(subscription.Guid);
       }
```

The same code when invoked from a console app works. So I thought this is a sync/async mismatch in the SDK code.
Since we already had non-fluent sdk working, we did a fall back completely to non-fluent sdk for now.

**Comment by markcowl** [comment]
@hovsepm Please assign to a sprint

**Comment by andreygoran** [comment]
Got the same problem when running azure.SqlServers.GetById() in ASP.NET.
Here is the workaround:

Thread thread = new Thread(() => { /* azure fluent code here */ });
thread.Start();
thread.Join();

**Comment by nicksav** [comment]
Still doesnt work. Cant get any response in ASP.Net...

**Comment by hovsepm** [comment]
Duplicate of https://github.com/Azure/azure-sdk-for-net/issues/3238
