### ISSUE TITLE
LLC does not add api-version to LRO URI in `UpdateStatus()`

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#25411]
While working on the LLC for Question Answering authoring, @AhmedLeithy [found](https://github.com/Azure/azure-rest-api-specs/issues/16807) that the `api-version` query parameter was not being added to the URI returned by the `Operation-Location` header. This was causing a 404 but, even if the service handled that, assuming the latest api-version could result in unexpected response models.

Talking with Jeff and Johan, an `api-version` in a Operation-Location is not required for LROs, so the client should add one if not already set (some services do pass the `api-version` back e.g., Key Vault).

On a related note, the `nextLink` model property for paged results should include an `api-version`, but it might be good to implement the same behavior  described in this bug just to make sure we are consistent.

**Comment by heaths** [comment]
@pakrym @AlexanderSher @annelo-msft could we get a fix for this ASAP, or is there some work around you can suggest?

**Comment by heaths** [comment]
For a repro, #25409.

**Comment by annelo-msft** [comment]
@heaths , could you clarify the repro steps?  They are not clear from the issue you linked

**Comment by heaths** [comment]
There really aren't any: just generate an LLC for a service that doesn't include the `api-version` in its Operation-Location header. The PR I referenced above could be used, so you could check it out and run `dotnet build /t:GenerateCode. Currently, running our tests live takes a bit of work, so I could write a mock up service + swagger if required.

**Comment by annelo-msft** [comment]
@AlexanderSher, it looks like GetResponseAsync is being called in OperationInternals.cs, rather than the CreateGetJobsRequest in the generated client: https://github.com/heaths/Issue25411/blob/main/Client/generated/JobsClient.cs#L257

**Comment by fengzhou-msft** [comment]
@heaths does this issue only apply to the `Operation-Location` header or it could also happen for `Location` and `Azure-AsyncOperation` headers?

**Comment by annelo-msft** [comment]
@mikekistler @lmazuel FYI

**Comment by lmazuel** [comment]
@heaths my personal take on what @JeffreyRichter and @johanste might have meant for "api-version in a Operation-Location is not required for LROs", is that most of the `Operation-Location` will point to an guid or some form of unique identifier, that makes the call explicit and then do not require extra metadata to be clear (like api-version). It doens't interpret to me, as the SDK should add `api-version` if it was not there. `Operation-Location` should point to an absolute URL at all time, and SDK should not change it.

See:
https://github.com/microsoft/api-guidelines/blob/50b14d32a1a5192213272c10371d1d82de02b296/azure/ConsiderationsForServiceDesign.md#long-running-operations-with-status-monitor

> The resource validates the request and initiates the operation processing. It sends a response to the client with a 202-Accepted HTTP status code. Included in this response is an Operation-location response header with the **absolute URL** of status monitor for this specific operation.

**Comment by JeffreyRichter** [comment]
The url returned in the operation-location header should not include the api-version query parameter. But the service should expect this qp and the client/sdk should add it.

Imagine that a V1 client initiates the LRO and then a V2 client wants to poll for the completion - this should work.

And now that I say this, the nextLink should also not include the api-version for the same reason. Note: I'm contradicting start I said earlier here. The nextLink value is opaque but the V1 or V2 client should identify itself via the api-version qp.

**Comment by mikekistler** [comment]
@JeffreyRichter I do not see the logic here. This is completely contrary to `Operation-Location` being an “opaque absolute URL”.  We are now asking users to crack apart the URL and add a query parameter before issuing the GET. At the very least this breaks with our previous guidance.

Can we please review this in the API Stewardship leadership team before we advise teams to go off and implement this guidance?

**Comment by darrelmiller** [comment]
HTTP API consumers are going to assume that URLs that come back in a response are opaque.  

> Imagine that a V1 client initiates the LRO and then a V2 client wants to poll for the completion - this should work.
If it is expected that clients can share URLs across different SDK versions, then SDKs should have the ability to remove any existing api-version and apply their own api-version.  This would also allow for SDKs to detect incompatible versions.

**Comment by markweitzel** [comment]
Notes from API Stewardship Board Discussion on 4-Jan-22

We are aligned on: 
For **NEW** services that use the API Version in the query parameter:
* ALL clients should replace the API version in the URL in the query parameter if they are bound to a specific API version.


Open Issue to be investigated further (in off-line thread):
* Services **SHOULD NOT** return a query parameter in the `Operation-Location` 
* The status monitor structure is NOT described in the Open API document. 
* We need to determine guidance on services that put the version in the path, e.g. cognitive. 

[Recording Link Here]()

**Comment by annelo-msft** [comment]
Thank you for the summary, @markweitzel!

@fengzhou-msft, let's close your PR https://github.com/Azure/autorest.csharp/pull/1749, and instead do the following

- When sending a request to a REST API, the client should always add the `api-version` (typically in a query parameter)

  Let's confirm that we're currently doing this, and if not, add this functionality

- When following the link in an LRO Operation-Location header or Pageable NextLink, if there is an existing `api-version` parameter in the URI, the client should overwrite this with the API version the client is using

  Let's implement this instead.

@markweitzel, do we have a timeline for determining guidance for services that put the version in the path?

**Comment by JeffreyRichter** [comment]
The guidance should be the same: replace the version path segment with the version the client wants to use. How hard is this too implement?

**Comment by fengzhou-msft** [comment]
> The guidance should be the same: replace the version path segment with the version the client wants to use. How hard is this too implement?

The API version is set in the ClientOption when creating a Client, and all requests sent by the client would use that version except the LRO cases we discuss here. If I understand correctly, we need to either add the API version or replace it for the link returned from service for LRO. That would be a simple change from https://github.com/Azure/autorest.csharp/pull/1749.

**Comment by annelo-msft** [comment]
Moving to the LLC backlog since the original issue in the QnA library was addressed by a change to the service.

**Comment by heaths** [comment]
Cross-linking Azure/azure-sdk#3809 since we may want to pull this back in depending on how that discussion turns out.

**Comment by heaths** [comment]
It was decided in https://github.com/Azure/azure-sdk/issues/3817 that the client should always set the `api-version` query parameter (not path parameters, though) if one was passed originally, which should always be the case for data plane clients.
