### ISSUE TITLE
[Question] Azure.Identity support using pfx file

### ISSUE THREAD

**Issue by MarcoEnxuto** [Azure/azure-sdk-for-net#25423]
**Query/Question**
Hi,
According to this [post](https://github.com/Azure/azure-sdk-for-net/pull/10196), pfx files should be supported. Unfortunately i don't see any support, or at least i can't get it work.
I did follow the troubleshooting steps but i don't see what i'm doing wrong.
So, i posted here a [question](https://docs.microsoft.com/en-us/answers/questions/633057/azureidentity-exception-thrown-when-using-iis-loca.html), since i'm using a local server with IIS and Environment variables. 
The app throws an exception indicating Could not load the certificate....

Either way, the certificate is in a public path and accessible.

AZURE_CLIENT_CERTIFICATE_PATH C:\Users\Public\cert.pfx
AZURE_CLIENT_ID (guid)
AZURE_TENANT_ID (another guid)

**Environment:**
 - Azure.Identity 1.5.0, Microsoft Identity Client 4.37.0
 - Windows Server 2022 and .NET 5
 - Visual Studio 16.11.7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @MarcoEnxuto - Does the following work if you try to construct the certificate directly using your file path? If not, what is the error?

```c#
new X509Certificate2(clientCertificatePath);
```

**Comment by MarcoEnxuto** [comment]
Hi @christothes, no. I'm not instantiating that class.
I'm using the following members to initiate the connection to Azure service.

Here's a code snippet...
`        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                    .AddMicrosoftIdentityWebApi(Configuration.GetSection("AzureAd"))
                    .EnableTokenAcquisitionToCallDownstreamApi()
                    .AddMicrosoftGraph(Configuration.GetSection("MicrosoftGraphAPI"))
                    .AddInMemoryTokenCaches();`


As soon i use the graph service client, it throws a "Could not load the certificate". 
Can you confirm the AZURE_CLIENT_CERTIFICATE_PATH uses PFX file path? there's some incongruencies on help pages.

**Comment by christothes** [comment]
Sorry, I know you aren't using that class directly, but it was intended as a test to see if Azure.Identity would be able to use your path since that is essentially what it does. Could you try this to verify that your pfx cert path is valid and that the password is unencrypted?

**Comment by MarcoEnxuto** [comment]
Yes. I updated the question on [Q&A](https://docs.microsoft.com/en-us/answers/questions/633057/azureidentity-exception-thrown-when-using-iis-loca.html), telling that i checked that using Import-PfxCertificate Cmdlet on PowerShell. But i'll try here on C#. Good point.

**Comment by MarcoEnxuto** [comment]
@christothes after careful debug, that code raises **The system cannot find the file specified**.
This is a quite odd.
The file present as you can see.
<img width="485" alt="certificates" src="https://user-images.githubusercontent.com/66541072/142693638-0d4c2f61-9bee-43e1-8f98-4db17d3864df.png">
On the second image, the first line is the code you mentioned, with the path of the file above.
Am i doing anything wrong?
<img width="602" alt="certificatedebug" src="https://user-images.githubusercontent.com/66541072/142693649-309ca649-12a4-41d2-8e2f-dd87dc7ce31c.png">

**Comment by christothes** [comment]
In the debugger immediate window, are you able to run these statements?

`File.Exists(@"C:\Useres\Public\cert.pfx")`
or
`Directory.GetFiles(@"C:\Useres\Public");`

**Comment by MarcoEnxuto** [comment]
Well, by using your suggestion, it exists... 
But the class X509Certificate2 doesn't find the file, or even the env variable... 

![image](https://user-images.githubusercontent.com/66541072/142700529-b8c19435-83b7-464d-9dd0-e04923aa5e8d.png)

**Comment by christothes** [comment]
This is very strange. Can you reproduce with X509Certificate2 directly?

**Comment by MarcoEnxuto** [comment]
You bet it is @christothes. 
But to clarify, I'm doing a remote debug from my dev box to the Server.
As you requested, just did that, an it throws as earlier.
![image](https://user-images.githubusercontent.com/66541072/142701482-5f29c48f-690c-4d08-aa3d-39dd1cc9225a.png)

Is it possible this happening because i have the debugger attached? I don't think so...

**Comment by MarcoEnxuto** [comment]
Hi @christothes, did you reach any conclusion based on my findings? Thanks.

**Comment by MarcoEnxuto** [comment]
Hello,
Any news regarding this @christothes?

**Comment by MarcoEnxuto** [comment]
> Hello, Any news regarding this @christothes?

Hi @schaabs, i guess @christothes might be Out of Office. Can you help me here?
Thanks a lot.

**Comment by christothes** [comment]
Hi @MarcoEnxuto - Because this reproduces directly with `X509Certificate2`, this doesn't appear to be an issue with the client SDK. Have you seen [this](https://stackoverflow.com/questions/51490379/x509certificate2-error-system-cannot-find-the-file-specified)?

**Comment by MarcoEnxuto** [comment]
> Hi @MarcoEnxuto - Because this reproduces directly with `X509Certificate2`, this doesn't appear to be an issue with the client SDK. Have you seen [this](https://stackoverflow.com/questions/51490379/x509certificate2-error-system-cannot-find-the-file-specified)?

Hi @christothes, sorry to bother. 
Well, i don't know what to say but i did read carefully your suggestion. What the link reports is an error when a user tries to instantiate X509Certificate2 class with a relative path. What i did, is the complete opposite. I use an absolute path when invoking the new instance. As you have seen earlier.

_I tried another way by copying the pfx certificate file to the output directory where i deploy my web app, which was the initial intention of the suggested. In the Immediate window i could execute successfully the code File.Exists (which returne true), but at runtime the code returns the exception "The system cannot find the file specified"._

_I also changed the AZURE_CLIENT_CERTIFICATE to a relative path, and i got the same outcome._
<img width="511" alt="cert" src="https://user-images.githubusercontent.com/66541072/144942509-bc1be89c-96f1-4812-8256-67de1048c716.png">

Something is not right here, and it is interesting that i am the only one reporting this...

**Comment by christothes** [comment]
I'm running out of ideas on this one, Perhaps you could verify the access control rules defined on the file or the containing directory? 

```c#
Debug.WriteLine(System.Security.Principal.WindowsIdentity.GetCurrent().Name);
var fileInfo = new FileInfo(@"<path to cert>");
var accessControl = fileInfo.GetAccessControl();
var rules = accessControl.GetAccessRules(true, true, typeof(System.Security.Principal.NTAccount));
foreach (FileSystemAccessRule rule in rules)
{
    Debug.WriteLine(rule.IdentityReference.Value);
}
```

**Comment by MarcoEnxuto** [comment]
Hi again @christothes,
The code snippet printed the below info:

IIS APPPOOL\<websitename>

BUILTIN\IIS_IUSRS
BUILTIN\Administrators
NT AUTHORITY\SYSTEM
NT AUTHORITY\INTERACTIVE
NT AUTHORITY\SERVICE
NT AUTHORITY\BATCH

**Comment by christothes** [comment]
> Hi again @christothes, The code snippet printed the below info:
> 
> IIS APPPOOL<websitename>
> 
> BUILTIN\IIS_IUSRS BUILTIN\Administrators NT AUTHORITY\SYSTEM NT AUTHORITY\INTERACTIVE NT AUTHORITY\SERVICE NT AUTHORITY\BATCH

Have you confirmed that those permissions allow IIS APPOOL to access the file?

The only other thought I had is to check if the certificate file is blocked. https://superuser.com/questions/590787/what-does-it-mean-when-a-file-is-blocked-in-windows

**Comment by MarcoEnxuto** [comment]
Hi @christothes, finally i found out what was wrong. And this took a while.
It seems we have to change on IIS Application Pool the following setting: **Load user profile=true** within the **Process Model** property Group. This [link told me the solution](https://jason-xge2.blogspot.com/2015/09/x509certificate2-system-cannot-find.html#:~:text=X509Certificate2%3A%20The%20system%20cannot%20find%20the%20file%20specified.,Recycle%20application%20pool%2C%20the%20error%20will%20be%20gone.). Another life saved.

Instead of using Web App service on Azure for development purposes, because well... costs... I decided to deploy on prem, using IIS.
So, for those who have the same thinking, and want to test the integration before deploying to Azure, on a Staging/Prod environments, you should consider the following configurations
**First**, get a certificate that was already configured on AAD, and place it on the local server.
**Second**, configure the Environment variables such as the image below
![image](https://user-images.githubusercontent.com/66541072/145228796-a97eda55-a95f-491e-8651-2780af38ba21.png)

**Third**, enable the "Load User profile" in the Application Pool, click ok and recycle it.
Now the **Azure.Identity** loads the certificate properly.

Thank you very much @christothes for your patience on this subject and thanks for your suggestions, i did help on my research.

On a side note: i wish you Merry Christmas for you and your family.
