### ISSUE TITLE
[BUG] Azure.Data.Tables - GetDateTime - Throws casting error

### ISSUE THREAD

**Issue by hgjura** [Azure/azure-sdk-for-net#25435]
Very simple retrieve of an entity from a table. Reading the entity form the query filter and using the default caster (GetDateTime) to read one of the properties that is a non-null Utc datetime. It throws an exception:
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot return System.Nullable`1[System.DateTime] type for a System.DateTimeOffset typed property.
  Source=Azure.Data.Tables
  StackTrace:
   at Azure.Data.Tables.TableEntity.EnforceType(Type requestedType, Type givenType)
   at Azure.Data.Tables.TableEntity.GetValue(String key, Type type)
   at Azure.Data.Tables.TableEntity.GetValue[T](String key)
   at Azure.Data.Tables.TableEntity.GetDateTime(String key)
   at ConsoleApp_TestingDatesInAzure.Program.Main(String[] args) in D:\ConsoleApp_TestingDatesInAzure\Program.cs:line 41

It should return the DateTime in Utc, without any exception. The actual value is not null and it is in Utc. But even if it was null it should return null instead and not throw an exception

Here is the code:
```
 var strongEntity = new AzureTestTableEntity
            {
                PartitionKey = "20211113",
                RowKey = $"ROWKEY",
                ETag = new ETag("*"),
                Timestamp = DateTime.UtcNow,

                EffectiveDate = DateTime.UtcNow,
                LastReadDate = DateTime.UtcNow,

            };


            Pageable<TableEntity> queryResultsFilter = tc.Query<TableEntity>(filter: $"PartitionKey eq '{"20211113"}'");


            foreach (var qEntity in queryResultsFilter)
            {
                Console.WriteLine($"{qEntity.GetDateTime("EffectiveDate")}: {qEntity.GetDateTime("LastReadDate")}");
            }

            Console.WriteLine($"The query returned {queryResultsFilter.Count()} entities.");

```

**Environment:**
- Azure.Data.Tables 12.3.0
 - Windows 10 - .net 5.0
- Microsoft Visual Studio Community 2019
Version 16.11.6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @hgjura - It appears in this case the value is DateTimeOffset. You should be able to get the value with GetDateTimeOffset. 

https://github.com/Azure/azure-sdk-for-net/blob/9c9ec82c36580deff41b8940af420519a28cd4e1/sdk/tables/Azure.Data.Tables/src/TableEntity.cs#L154

**Comment by hgjura** [comment]
I don't really understand this. The DateTime values are stored as DateTime.Utc. Why would they be retrieved as DateTimeOffset? At that point what is the value of GetDateTime if all datetime are stored as DateTimeOffset. But I am not sure this is what happening here. 
I am curious about the rules when a datetime get stored as a datetime or as a datetimeoffset, and how do I know before hand so I can call the appropriate method to retrieve it.

Thanks
Herald
