### ISSUE TITLE
What is the default sorting of GetItemLinqQueryable?

### ISSUE THREAD

**Issue by Sti2nd** [Azure/azure-sdk-for-net#25432]
I want to construct a query with optional parameters in LINQ, basically this code:

```c#
IOrderedQueryable<User> query = _userContainer.GetItemLinqQueryable<User>();
if (id != null)
{
    query = query.Where(user => user.Id == id); // returns IQueryable
}
if (name != null)
{
    query = query.Where(user => user.Name == name); // returns IQueryable
}
```

This doesn't work because IQueryable cannot be assigned to IOrderedQueryable which `GetItemLinqQueryable` returns.

To avoid doing an expensive sort operation my theory is that I can apply the same sorting that `GetItemLinqQueryable` uses in each of these if-blocks. I didn't find the default sort mentioned in the documentation, so anyone knows what it is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0207c888-39da-2768-71b5-2fc219f5ebad
* Version Independent ID: 4ed5c6d6-170d-50a5-7ac2-e8e64bd7d0f6
* Content: [Container.GetItemLinqQueryable&lt;T&gt;(Boolean, String, QueryRequestOptions, CosmosLinqSerializerOptions) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.getitemlinqqueryable?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by KranthiPakala-MSFT** [comment]
@Sti2nd 
Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by SaurabhSharma-MSFT** [comment]
@Sti2nd Sorry for delay.
Have you tried using `AsQueryable` in `GetItemLinqQueryable` with something like below -
`var queryable = container.GetItemLinqQueryable<user>()
            .OrderBy(A => A.Created)
            .AsQueryable();`

**Comment by Sti2nd** [comment]
@SaurabhSharma-MSFT Thank you for answering.
Yes, I have tried and it works. Sorting on any property will likely work but takes time.

Are you saying that `GetItemLinqQueryable` returns a result sorted on `Created` by default? If that is the case my theory is that it will be faster to use that sorting for all the LINQ queries.

**Comment by SaurabhSharma-MSFT** [comment]
@Sti2nd No, it is not a default sorting order.  Here, the query calls the `OrderBy` method on in ascending order according to the passed key (i.e. `Created`) and also it is going to spend time do the sorting.

**Comment by Sti2nd** [comment]
@SaurabhSharma-MSFT There must be a default sort order since `GetItemLinqQueryable` returns `IOrderedQueryable`.

If data is not stored sorted in db it doesn't matter what the default sort is, though.

**Comment by SaurabhSharma-MSFT** [comment]
@Sti2nd Ok. Get it. I check internally and get back to you. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@Sti2nd We are proceeding with the closure with the issue.
