### ISSUE TITLE
SendAsync(IList<Message>) send all messages in Bulk with limitation 256KB

### ISSUE THREAD

**Issue by MikeIef** [Azure/azure-sdk-for-net#25431]
Please clarify is that an expected behaviour that SendAsync(IList<Message>) send all messages in one Bulk message with limitation 256KB

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dad80d9c-c18e-915d-8f9c-8154c9149b12
* Version Independent ID: 571400d1-2f94-30b2-e394-645d6392c310
* Content: [QueueClient.SendAsync Method (Microsoft.Azure.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.queueclient.sendasync?view=azure-dotnet#Microsoft_Azure_ServiceBus_QueueClient_SendAsync_System_Collections_Generic_IList_Microsoft_Azure_ServiceBus_Message__)
* Content Source: [xml/Microsoft.Azure.ServiceBus/QueueClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.ServiceBus/QueueClient.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by KranthiPakala-MSFT** [comment]
@MikeIef Thank you for reaching out. At this time we are reviewing the ask and will provide an update as appropriate

**Comment by PramodValavala-MSFT** [comment]
@MikeIef Yes. That is correct. You will have to ensure the size of the final message is within the limit.

The newer `Azure.Messaging.ServiceBus` SDK has [a way to build the batch while keeping track of the size](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessagebatch.tryaddmessage?view=azure-dotnet).

**Comment by PramodValavala-MSFT** [comment]
@MikeIef Just following up here... Hope my previous comment clears things up.

**Comment by PramodValavala-MSFT** [comment]
@MikeIef Just following up here... Hope my previous comment clears things up.

**Comment by MikeIef** [comment]
Yep, everything is clear now, thank you!
