### ISSUE TITLE
Azure.Data.Tables - CreateTableIfNotExists throws System.NullReferenceException: 'Object reference not set to an instance of an object.'

### ISSUE THREAD

**Issue by hgjura** [Azure/azure-sdk-for-net#25434]
Hello,
I am just writing some sample code to test the Azure.Data.Tables functionality and right away I ran into an exception.

Code is rather simple:
```
var serviceClient = new TableServiceClient(new Uri("<some uri>"), new TableSharedKeyCredential("<some account name>", "<some key>"));

            string tableName = "TESTDATES";
            TableItem table = serviceClient.CreateTableIfNotExists(tableName);

            var tc = serviceClient.GetTableClient(tableName);
```
The first iteration, when table does not exists, it runs fine. Subsequent iterations, when table already exists, it throws an excpetion in the CreateTableIfNotExists() line.

Exceptions details:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Azure.Core
  StackTrace:
   at Azure.Response`1.op_Implicit(Response`1 response)
   at ConsoleApp_TestingDatesInAzure.Program.Main(String[] args) in 

There is no inner exception.

Thanks
Herald

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @hgjura - Could you confirm that the URI being passed to the TableClient constructor does not contain a table name? It should be just the account URI.

**Comment by hgjura** [comment]
Here is a screenshot of the code. It is pretty straightforward. And as you mentioned only the acct uri and the key.

![Capture](https://user-images.githubusercontent.com/9681487/143144013-32dcdaa8-d4c4-482c-acb9-b89497012ae4.PNG)

Thanks
Herald

**Comment by christothes** [comment]
Are you using the latest released version? I am unable to reproduce this.

**Comment by christothes** [comment]
I looked at this again and I realized that the issue is related to the implicit cast for Response<T>. The workaround for this is to either use `var` for the response type, or explicitly `Response<TableItem>`

I'll look into a viable fix for this as well. 

related to #25528

**Comment by hgjura** [comment]
Good catch. I didn't think that response will be null if table exists, but it is indeed null. Thanks for the workaround!

**Comment by pakrym** [comment]
Can we synthesize an instance of TableItem and return it instead of null? It has only the Name property that we have.
