### ISSUE TITLE
Azure.Identity release notes

### ISSUE THREAD

**Issue by phatcher** [Azure/azure-sdk-for-net#25447]
**Query/Question**
I want to know whether it is worthwhile updating our dependency on Azure.Identity from 1.4.1 to 1.5, but I have no information as to what has changed.

**Comment by jsquire** [comment]
Hi @phatcher.   Thank you for reaching out and we regret that you're experiencing difficulties.   A link to the change log for a specific version of  `Azure.Identity` can be found in the "Release Notes" tab of its [NuGet page](https://www.nuget.org/packages/Azure.Identity/):

![image](https://user-images.githubusercontent.com/913445/142731358-012467d7-ccd3-4838-955d-6268d8746c7c.png)

Or, if you prefer, the latest change log  version can always be found in the the [Azure SDK for .NET repository](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md) area for `Auzure.Identity`.

I'm going to mark this as addressed;  please feel free to use the "`/unresolve`" command if you'd like to discuss further.
