### ISSUE TITLE
How do I get keys from a vault in the fluent API?

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-sdk-for-net#2544]
If I have a key in a vault, I need to be able to retrieve it for use while configuring my virtual machines...

**Comment by jianghaolu** [comment]
Hi @atrauzzi 

The fluent API only helps you deploy a vault resource. To access the keys and secrets stored in a vault, you will need to use the key vault data plan library: https://www.nuget.org/packages/Microsoft.Azure.KeyVault/2.0.4-preview.

**Comment by atrauzzi** [comment]
Thanks!
