### ISSUE TITLE
[QUERY] How to return a single result from query or null

### ISSUE THREAD

**Issue by hgjura** [Azure/azure-sdk-for-net#25448]
I am looking for a way to run queries that return a single record. Something of the type of .FirstOrDefault()

Currently I have this working like this:
```
var tsc = new TableServiceClient(new Uri($"https://{AccountName}.table.core.windows.net/"), new TableSharedKeyCredential(AccountName, AccountKey));

 var tc = tsc.GetTableClient("SOMETABLE");

 SomeEntity r = null;

var q = tcQueryAsync<SomeEntity>(filter: e => e.PartitionKey == "some partition key" && e.RowKey == "some row key"); //<-- THSI RETURNS A SINGLE RECORD, ALWAYS

await foreach (var i in q) r ??= i;

return r;
```

Is there a more efficient way to return, or look for, a single query result. The way I have looked into the samples is always expected multiple results.

Thanks
Herald

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @hgjura - yes, GetEntity does what you need. 

https://github.com/Azure/azure-sdk-for-net/blob/9c9ec82c36580deff41b8940af420519a28cd4e1/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L623

**Comment by hgjura** [comment]
Perfect. This was what I was looking for. Thanks

**Comment by hgjura** [comment]
Though the solution provided was satisfactory, I would like to add two use cases when this may not fully work:
- The caller may not have details about the PartitionKey or RowKey details when calling this (in my case through a library). The uniqueness is provided through the predicate call. But a predicate seem not to be an option for this call.
- I would still have preferred a solution to the LINQ's IQueryable FirstOrDefault(). It would be more in sync with the common APIs for such calls and also fulfill the use case when, the query may or may not return one or more items but you only one the first on top of the stack, and you want to do that without bringing all records all the way to the client to inspect them (which is what I am doing now).
Thanks
Herald

**Comment by christothes** [comment]
> Though the solution provided was satisfactory, I would like to add two use cases when this may not fully work:
> 
> * The caller may not have details about the PartitionKey or RowKey details when calling this (in my case through a library). The uniqueness is provided through the predicate call. But a predicate seem not to be an option for this call.

The only valid unique predicate for a guaranteed single record result is to specify both the PartitionKey and RowKey values. Anything else is a standard Query which can have zero to many results.

> * I would still have preferred a solution to the LINQ's IQueryable FirstOrDefault(). It would be more in sync with the common APIs for such calls and also fulfill the use case when, the query may or may not return one or more items but you only one the first on top of the stack, and you want to do that without bringing all records all the way to the client to inspect them (which is what I am doing now).

Performing a server side "SingleOrDefault" is not possible with the Table service, so the only alternative is to perform a query with a `maxPerPage` option of 1 and iterate only through the first page of results. Below is an example of how you'd need to fetch just a single record this way.

```c#
var pages = table.QueryAsync<TableEntity>(t => <some filter>, maxPerPage: 1).AsPages();
await foreach (var tableEntity in pages)
{
	// Do something with the first entitiy here.
	break;
}
```

**Comment by hgjura** [comment]
Good workaround. Thanks.
