### ISSUE TITLE
[QUERY] How to return only select columns/properties

### ISSUE THREAD

**Issue by hgjura** [Azure/azure-sdk-for-net#25449]
I have a use case where I need to return only a single column form the querying, and not the whole entities.
In the old Storage SDK, there was the SelectColumns property o fthe TableQuery object that you would set with a list of strings of property names, and you would return only those properties.

Is there something similar to this in Azuer.Data.Tables Sdk? How would I be able to accomplish this?

Thanks
Herald

**Comment by jsquire** [comment]
Hi @hgjura.   Thank you for reaching out and we regret that you're experiencing difficulties.    If I understand correctly, the selection that you're looking to do is supported by providing a `select` filter in your query, as illustrated in our [Query entities with select](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md#query-entities-with-select) sample.  

I'm going to mark this as addressed, but please feel free to use the "`/unresolve`" command if I've misunderstood or you'd like to discuss further.

**Comment by hgjura** [comment]
> Hi @hgjura. Thank you for reaching out and we regret that you're experiencing difficulties. If I understand correctly, the selection that you're looking to do is supported by providing a `select` filter in your query, as illustrated in our [Query entities with select](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md#query-entities-with-select) sample.
> 
> I'm going to mark this as addressed, but please feel free to use the "`/unresolve`" command if I've misunderstood or you'd like to discuss further.

Perfect. This solved my issue. Thanks.
