### ISSUE TITLE
Get rid of netcoreapp2.0 dependence

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#25459]
The management tests still use netcoreapp2.0 runtime https://github.com/Azure/azure-sdk-for-net/blob/main/eng/mgmt/AzSdk.test.reference.props#L3
.NET Core 2.0 is out  of support since Oct 2018, should be upgrade to new .net framework.

**Comment by jsquire** [comment]
Closing as stale; linked file references netcoreapp3.1
