### ISSUE TITLE
AzureServiceTokenProvider is not resilient to absence of trailing slash in azureAdInstance

### ISSUE THREAD

**Issue by zahess** [Azure/azure-sdk-for-net#25467]
**Describe the bug**
When construction an AzureServiceTokenProvider instance, providing a `connectionString` value that includes a tenantId, and also providing a `azureAdInstance` value that does **not** include a trailing `/`, GetAccessTokenAsync will fail with an exception indicating malformed concatenation of the `authority` Uri. This URI is constructed [here, using simple concatenation](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/AzureServiceTokenProvider.cs#L354). This could be improved by adding intelligence or taking advantage of the built-in .NET Uri object using a pattern similar to the following (as a direct replacement for the highlighted line):

`string authority = string.IsNullOrEmpty(tenantId) ? string.Empty : new Uri(new Uri(_azureAdInstance), tenantId).AbsoluteUri`;

**Expected behavior**
AzureServiceTokenProvider can generate a token regardless of whether a trailing slash is provided in the azureAdInstance parameter value.

**Actual behavior (include Exception or Stack Trace)**
Exception message, tenantId redacted, using nonpublic cloud azureAdInstance:

> Unhandled exception. Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: Runas=App;AppId=a317dc4b-b536-4f1c-9ebc-df73501248b9;TenantId=*Redacted*;AppKey=*Redacted*, Resource: https://management.usgovcloudapi.net, Authority: https://login.microsoftonline.us*TenantRedacted*. Exception Message: Access token could not be acquired. 'authority' Uri should have at least one segment in the path (i.e. https:////...) (Parameter 'authority')

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Construct an **AzureServiceTokenProvider** object, specifying a connection string that includes TenantId and azureAdInstance host Uri **without** a trailing slash
2. Call GetAccessTokenAsync and observe exception.

**Environment:**
 - Any. Described problem is currently present in main branch as of posting this issue

**Comment by jsquire** [comment]
//cc: @nonik0, @anaismiller

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by anaismiller** [comment]
Thank you for sharing @zahess . Feel free to create a PR request to correct the issue :)

**Comment by jsquire** [comment]
AppAuthentication has reached end of life and is no longer maintained or supported.  Closing out this issue.
