### ISSUE TITLE
Re-enable DownloadECDsa tests using P256K on MacOS

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#25472]
I wasn't able to figure out why only this combination fails with `only named curves are supported on this platform.` exception.

Suppressed to unblock .net 6 migration.

**Comment by heaths** [comment]
What PR? What was unexpected? As the message states, only named curves are supported on the MacOS agents we run in CIs - at least at the time. But what problem did this cause?

**Comment by heaths** [comment]
E.g. https://github.com/Azure/azure-sdk-for-net/pull/24260/files#diff-9af698f6b812d750e3e50f4cdcd08dca94a62cbaf8cc0b106bdd1626356c2752R908-R912

**Comment by pallavit** [comment]
Given the discussion I will go ahead and opportunistically close this issue. Please feel free to re-open.
