### ISSUE TITLE
[BUG] Service Bus Trigger connection string managed identity

### ISSUE THREAD

**Issue by tomidix** [Azure/azure-sdk-for-net#25480]
**Describe the bug**
Service Bus Trigger connection string with managed identity defined no longer works after upgrading functions from .net5 isolated to .net6 isolated.

**Expected behavior**
Connection string defined like this should be possible and working:
Endpoint=sb://mytestsb.servicebus.windows.net/;Authentication=Managed Identity

**Actual behavior (include Exception or Stack Trace)**
Seems like the trigger function can't connect to service bus at all.
_The listener for function 'Functions.SBQueueFunction' was unable to start. The connection string used for an Service Bus client must specify the Service Bus namespace host and either a Shared Access Key (both the name and value) OR a Shared Access Signature to be valid. (Parameter 'connectionString')_

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Azure Function running .net6, configured to use Managed Identity
2. Service Bus Queue configured to provide access to function's managed identity
3. Function code on .net6 with SB Queue Trigger 
4. Connection string defined like this, which was working previously on Microsoft.Azure.ServiceBus and .net5
Endpoint=sb://mytestsb.servicebus.windows.net/;Authentication=Managed Identity

**Environment:**
 - Microsoft.Azure.Functions.Worker 1.6.0
 - Azure.Messaging.ServiceBus 7.5.0
 - Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 5.0.0-beta.6

**Comment by jsquire** [comment]
Hi @tomidix.   Thank you for your feedback and we regret that you're experiencing difficulties.   To use a managed identity with the trigger, you'll want to specify the fully qualified namespace for Service Bus, not the connection string.

An example can be found in the `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/README.md#managed-identity-authentication):

```json
{
  "Values": {
    "<connection_name>__fullyQualifiedNamespace": "<service_bus_namespace>.servicebus.windows.net"
  }
}

```

**Comment by hkusulja** [comment]
I have the same issue due to unclear change / documentation.
I will try mentioned new name.

**Comment by StefanSchoof** [comment]
I also run into this issue, while updating from 4.3.0 to 5.1.0. @jsquire with your comment I was able to get it working. For me in the documentation, it was not clear if the config needs only the `<connection_name>__fullyQualifiedNamespace` or also the  `<connection_name>`. My config is now without the `<connection_name>` and working

**Comment by tomidix** [comment]
Hi,

1st of all, locally it works the way that @jsquire described. So thanks for that.

Second, for Azure Function deployment, I fixed this by removing the connection string from appsettings.json and adding it to arm template (Function's Application Settings in Azure portal). I used 'sbqueuetrigger__fullyQualifiedNamespace' setting name and specified connection name in lowercase as 'sbqueuetrigger' in code itself. (Tried once with PascalCase and it wasn't working.)

**Comment by johanlangevillecab** [comment]
Hi,

I am a bit confused!
Accordning to [this documentation](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#:~:text=Functions.Worker.Sdk-,Binding,-extension%20packages) from Microsoft, **webjobs** is replaced by **workers** when using **.net 6 isolate**. But in the suggested solution by @jsquire we should use Microsoft.Azure.WebJobs.Extensions.ServiceBus. How?
