### ISSUE TITLE
Setting up EnableCrossEntityTransactions for ServiceBusClient bind in ServiceBusTriggered function

### ISSUE THREAD

**Issue by mfi-cvation** [Azure/azure-sdk-for-net#25490]
**Query/Question**
Hi,

I am trying to do transaction processing with servicebus inside a ServiceBusTrigger like shown in the image:
![image](https://user-images.githubusercontent.com/93116768/143046110-61dc0063-5f7e-4d06-a87d-1e1bdb90f5cb.png)

However when I run it I get the following error:
![image](https://user-images.githubusercontent.com/93116768/143046190-6ae94fb7-890f-4b20-974a-5cf7def957f0.png)

It seems I am somehow missing setting up the ServiceBusClient that I bind in my parameters to have `EnableCrossEntityTransactions
` How do I do this? I can't seem to find it in the docs.

**Environment:**
 - Azure.Messaging.ServiceBus 7.5.0
 - Windows 10 and .NetCore3.1
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
This would be configured in the host.json file using "enableCrossEntityTransactions" key.
@cachai2 - can we please get this doc updated - [EnableCrossEntityTransactions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#additional-settings-for-version-5x)

**Comment by mfi-cvation** [comment]
Thank you very much for the quick reply! This is great!

**Comment by JoshLove-msft** [comment]
Created https://github.com/MicrosoftDocs/azure-docs-pr/pull/181052

**Comment by JoshLove-msft** [comment]
The docs PR has been merged and should be live on docs site shortly.
