### ISSUE TITLE
Specifying Scope for publishing fails to publish scope specific projects/nugets

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#2549]
Specifying Scope during publish or build fails to publish particular scope project if the scope specified has multiple projects.
Investigation:
1) We search for .sln files during build and hence once we find the sln file we move forward to start the build.
2) Nest projects in a scope is simply ignored.

**Comment by markcowl** [comment]
Closing as duplicate of #2300
