### ISSUE TITLE
[BUG] Passing an invalid filter to TableClient.Query does not error

### ISSUE THREAD

**Issue by sonic1981** [Azure/azure-sdk-for-net#25514]
**Describe the bug**
If you pass an invalid or erroneous filter string to the `TableClient.Query` method the library does not error, but instead hangs. Related to: https://github.com/Azure/azure-sdk-for-net/issues/25513

**Expected behavior**
Should produce a meaningful error about invalid syntax

**Actual behavior (include Exception or Stack Trace)**
Call hangs indefinitely 

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Filter an Azure table storage instance with an invalid filter string (i.e. `PartitionKey eq abc` not `PartitionKey eq 'abc'`)
2. 
```c#
TableClient tableClient = new TableClient(connectionString);

IEnumerable<TableEntity> entities = this.tableClient.Query<TableEntity>($"PartitionKey eq abc);
entities.Any(); 
```
3. `entities.Any();` hangs and no error is produced

**Environment:**
 - Name and version of the Library package used: Azure.Data.Tables v12.3.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):

>  .NET SDK (reflecting any global.json):
> Version: 5.0.402
> Commit: e9d3381880
> 
> Runtime Environment:
> OS Name: Windows
> OS Version: 10.0.18362
> OS Platform: Windows
> RID: win10-x64
> Base Path: C:\Program Files\dotnet\sdk\5.0.402\
> 
> Host (useful for support):
> Version: 5.0.12
> Commit: 7211aa01b3
> 
> .NET SDKs installed:
> 2.1.526 [C:\Program Files\dotnet\sdk]
> 3.1.414 [C:\Program Files\dotnet\sdk]
> 5.0.402 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
> Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
> Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
> Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
> Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

 - IDE and version : Microsoft Visual Studio Enterprise 2019
Version 16.10.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by sonic1981** [comment]
That's the HTTP status @christothes  but I was seeing this with the .Net client. Does that do the same thing?

**Comment by christothes** [comment]
In my local testing, the client throws with the error I pasted above. In your local repro, does the network request to the service get invoked? If so, does it never respond and timeout, or return with an error code like above?
