### ISSUE TITLE
[BUG] Azure.Core.ResponseOfT.Implicit(Response<T> to T) Operator can raise NullReferenceException when response is null

### ISSUE THREAD

**Issue by pmariani** [Azure/azure-sdk-for-net#25528]
Normal usage looks like `Response<TableItem> table = serviceClient.CreateTableIfNotExists(tableName);` 
`table` can either be set, or null.
But the implicit conversion operator makes it easy to write code like `TableItem table = serviceClient.CreateTableIfNotExists(tableName);`.
In situations where the return value would have been null, the implicit operator throws a null reference exception.

It would be great if the implicit operator could pass the null value back to the caller instead of throwing.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
The bug here is that `serviceClient.CreateTableIfNotExists` returns `null`. If a service client makes a request it has to return it.

**Comment by pakrym** [comment]
cc @christothes
