### ISSUE TITLE
[BUG] AccountSasBuilder.SetPermissions(string), will fail when input valid permission string include "i" 

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#25525]
**Describe the bug**

Run `AccountSasBuilder.SetPermissions("i")` will get exception "i is not a valid SAS permission".
But "i" (SetImmutabilityPolicy) is a valid permission :

This permission is documented here:
[Create an account SAS - Azure Storage | Microsoft Docs](https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas#specifying-account-sas-parameters)
- Set Immutability Policy (i): Valid for the following Object resource type only: blob. Permits set/delete immutability policy and legal hold on a blob.

[AccountSasPermissions ](https://github.com/Azure/azure-sdk-for-net/blob/6a395c10a9a3126661bed9958a864f3c4487d39c/sdk/storage/Azure.Storage.Common/src/Sas/AccountSasPermissions.cs#L80)has defined the permission: SetImmutabilityPolicy.

**Expected behavior**
The function should success, and permission "i" should be set to the AccountSasBuilder.

**Actual behavior (include Exception or Stack Trace)**
Get exception:
> System.Management.Automation.MethodInvocationException: Exception calling "SetPermissions" with "1" argument(s): "i is not a valid SAS permission" ---> System.ArgumentException: i is not a valid SAS permission
>    at Azure.Storage.Sas.SasExtensions.ValidateAndSanitizeRawPermissions(String permissions, List`1 validPermissionsInOrder)
>    at CallSite.Target(Closure , CallSite , Object , String )
>    --- End of inner exception stack trace ---
>    at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo memberInfo)
>    at CallSite.Target(Closure , CallSite , Object , String )
>    at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
>    at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
>    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a AccountSasBuilder object
2. Run SetPermissions("i") on the object

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Common12.9.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]

>  .NET SDK (reflecting any global.json):
>  Version:   5.0.403
>  Commit:    bf9d168ac2
> 
> Runtime Environment:
>  OS Name:     Windows
>  OS Version:  10.0.19044
>  OS Platform: Windows
>  RID:         win10-x64
>  Base Path:   C:\Program Files\dotnet\sdk\5.0.403\
> 
> Host (useful for support):
>   Version: 5.0.12
>   Commit:  7211aa01b3
> 
> .NET SDKs installed:
>   2.2.110 [C:\Program Files\dotnet\sdk]
>   3.1.415 [C:\Program Files\dotnet\sdk]
>   5.0.209 [C:\Program Files\dotnet\sdk]
>   5.0.403 [C:\Program Files\dotnet\sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
>   Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
>   Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> To install additional .NET runtimes or SDKs:
>   https://aka.ms/dotnet-download

 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by PramodValavala-MSFT** [comment]
@blueww Looks like [this is the list](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Common/src/Sas/AccountSasBuilder.cs#L164) that is being used to check permissions against which doesn't include `i`.

We are routing this to the concerning team for more insights.

**Comment by blueww** [comment]
permission "i" missed from https://github.com/Azure/azure-sdk-for-net/blob/d24afacd836b6de8950df9d785d2042f83564576/sdk/storage/Azure.Storage.Common/src/Sas/AccountSasBuilder.cs#L164, also make "BlobContainerClient.SetAccessPolicy()" fail ,when one of the access policy has permission include "i"

**Comment by blueww** [comment]
@SeanFeldman 
Would you please help to look at this issue?
It blocks permission "i" be fully supported in Powershell.

**Comment by blueww** [comment]
@seanmcc-msft 
Thanks for the quick fix!
