### ISSUE TITLE
[BUG] Event Grid:  Deserialized EventHubCaptureFileCreatedEventData Fileurl is always null

### ISSUE THREAD

**Issue by MikeNicholls** [Azure/azure-sdk-for-net#25536]
**Describe the bug**
When using Azure.Messaging.EventGrid to deserialize an Event Hubs Capture event, [the `Fileurl` property](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventgrid.systemevents.eventhubcapturefilecreatedeventdata.fileurl) of the `EventHubCaptureFileCreatedEventData` system event data is always null.

**Expected behavior**
The `Fileurl` should be the blob URL contained in the Event Grid event data.

**Actual behavior (include Exception or Stack Trace)**
The `Fileurl` is null.

**To Reproduce**
This was encountered while using a Function App to handle Event Hubs Capture notifications delivered through Event Grid, but it can be reproduced by adding an additional check to one of the existing tests.

1. Edit ConsumeEventTests.cs, find the `ConsumeEventHubCaptureFileCreatedEvent` test.
2. After the last line (`Assert.AreEqual`), add a check for the `Fileurl`:
   ```csharp
   Assert.AreEqual("https://tf0831datamigrate.blob.core.windows.net/windturbinecapture/tfdatamigratens/hubdatamigration/1/2017/08/31/19/11/45.avro", (eventData as EventHubCaptureFileCreatedEventData).Fileurl);
   ```
3. Run the tests.  `ConsumeEventHubCaptureFileCreatedEvent` will fail, as the `Fileurl` will be null.

**Environment:**
 - Name and version of the Library package used: Azure.Messaging.EventGrid 4.7.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure AppService

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Thanks for submitting the issue @MikeNicholls. It looks as though the swagger is incorrect and needs updating.

**Comment by alexanikiev** [comment]
@JoshLove-msft I was looking into Jan 2022 milestone to see if this bug has been fixed, looks like it is not yet, do you have any updates on it? Thanks in advance
