### ISSUE TITLE
[Servicebus] DeferMessagesArray failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#25534]
Servicebus nightly test runs are failing with:

> Error message
> Expected: Deferred
> But was:  <{MessageId:5588971c-22b6-41c9-8981-cfb329c3fca8}>
> 
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.DeferMessagesArray() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 548
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.DeferMessagesArray() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 553
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.DeferMessagesArray() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 554
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1214492&view=results

@jsquire for notification.

**Comment by JoshLove-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/25520
