### ISSUE TITLE
Azure.Data.Tables docs hard to find

### ISSUE THREAD

**Issue by hinchley2018** [Azure/azure-sdk-for-net#25531]
Finding these docs was pretty difficult... CosmosDB Tables API kinda wins the search page rank if you are looking for examples where you can use Azure Storage Tables...)

Also having those names close is super confusing if anyone at Azure wants to improve it. Maybe there is a reason for it, but I would prefer discoverability over using the same name. 

Maybe we are meant to find the Azure.Data.Tables docs ourselves but it would be nice if this page or  [sdk samples](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/tests/samples) was linked from https://docs.microsoft.com/en-us/azure/storage/tables/table-storage-overview page where you are learning about the resource itself

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 832d240a-84c0-c267-5f7c-2d319868b7bd
* Version Independent ID: b2d297ee-89bb-0b34-e01e-87751658d17b
* Content: [Azure Tables client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/data.tables-readme)
* Content Source: [api/overview/azure/data.tables-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/data.tables-readme.md)
* Service: **tables**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by hinchley2018** [comment]
@maggiepint If the docs are open I'm happy to add a PR to link these docs to the overview page. Just point me in the right direction and I think that would solve this issue of discoverability

**Comment by jsquire** [comment]
//cc: @scottaddie

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
I believe @mario-guerra was working on this.

**Comment by pallavit** [comment]
@mario-guerra is this still something you are actively looking at?

**Comment by mario-guerra** [comment]
Hi @pallavit, @kyle-patterson owns Tables now.
