### ISSUE TITLE
[Form Recognizer] CopyModel(True) failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#25533]
Form Recognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : An unexpected error occurred.
> Status: 200 (OK)
> ErrorCode: InternalServerError
> 
> Additional Information:
> AdditionInformation: InternalServerError: An unexpected error occurred.
> 
> Details:
> InternalServerError: An unexpected error occurred.
> 
> Raw:
> {
> "code": "InternalServerError",
> "message": "An unexpected error occurred.",
> "details": [
> {
> "code": "InternalServerError",
> "message": "An unexpected error occurred."
> }
> ]
> }
> 
> Content:
> 
> Headers:
> Transfer-Encoding: chunked
> x-envoy-upstream-service-time: 37
> apim-request-id: 9b62c52f-d631-4c46-9d49-df120b6184c4
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Fri, 26 Nov 2021 05:04:16 GMT
> Content-Type: application/json; charset=utf-8
> 
> Data:
> AdditionInformation: InternalServerError: An unexpected error occurred.
> 
> Details:
> InternalServerError: An unexpected error occurred.
> 
> Raw:
> {
> "code": "InternalServerError",
> "message": "An unexpected error occurred.",
> "details": [
> {
> "code": "InternalServerError",
> "message": "An unexpected error occurred."
> }
> ]
> }
> 
> 
> Stack trace
>    at Azure.Core.OperationInternalBase.ApplyStateAsync(Boolean async, Response response, Boolean hasCompleted, Boolean hasSucceeded, RequestFailedException requestFailedException) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 201
>    at Azure.Core.OperationInternal`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 178
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 173
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 80
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 142
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 167
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 145
>    at Azure.AI.FormRecognizer.DocumentAnalysis.CopyModelOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /_/sdk/formrecognizer/Azure.AI.FormRecognizer/src/CopyModelOperation.cs:line 120
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DocumentModelAdministrationClientLiveTests.CopyModel(Boolean useTokenCredential) in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/DocumentModelAdministrationClient/DocumentModelAdministrationClientLiveTests.cs:line 228
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DocumentModelAdministrationClientLiveTests.CopyModel(Boolean useTokenCredential) in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/DocumentModelAdministrationClient/DocumentModelAdministrationClientLiveTests.cs:line 235
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1215250&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Failure not happening anymore.
