### ISSUE TITLE
ServiceBusMessageAction - Thread Safety Issue

### ISSUE THREAD

**Issue by oystehei** [Azure/azure-sdk-for-net#25549]
**Describe the bug**
I'm trying to batch complete messages using the new `ServiceBusMessageActions` class, using this approach (as suggested in #7921):
```
 var tasks = new List<Task>();
 for (ServiceBusReceivedMessage message in messages)
 {
     tasks.Add(actions.CompleteMessageAsync(message));
 }
 await Task.WhenAll(tasks);
```

**Expected behavior**
Messages should be successfully completed.

**Actual behavior (include Exception or Stack Trace)**
The `ServiceBusMessageActions` class throws the following exception:
```
Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported()
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value, Int32& location)
   at System.Collections.Generic.HashSet`1.Add(T item)
   at Microsoft.Azure.WebJobs.ServiceBus.ServiceBusMessageActions.<CompleteMessageAsync>d__10.MoveNext()
```
The issue appears to be caused by the fact that the `ServiceBusMessageActions` class uses an internal `HashSet<T>` to track settled messages, and this class is not thread-safe.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)
1. Create a service bus trigger that accepts a batch of messages
2. Try to complete the messages using the code above

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.WebJobs.Extensions.ServiceBus, Version=5.1.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Azure Functions (runtime version 4), .NET 6
 - IDE and version : Visual Studio 17.0.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
