### ISSUE TITLE
Fluent management library Authenticate does not throw on removed SPN

### ISSUE THREAD

**Issue by cvs79** [Azure/azure-sdk-for-net#2554]
When we do an 
```
AzureCredentials credentials = AzureCredentials.FromServicePrincipal(clientID, clientSecret, tenantId, AzureEnvironment.AzureGlobalCloud);
var azure = Azure.Authenticate(credentials).WithSubscription(subscriptionId);
```
it does not throw an exception when the SPN is not valid or doenst exist anymore. 

The actual creation of the VM 

`var windowsVM = azure.VirtualMachines.Define ....`

does throw an exception {Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS70001: Application with identifier XYZ.

I would expect that the Authenticate would allready fail when the SPN is not valid.

**Comment by jianghaolu** [comment]
Hi @cvs79 
This is by design. Creating an `Azure` instance doesn't require a network connection.

To verify if you have a valid credential, you can call `Azure.Authenticate(credentials).WithDefaultSubscription()`.
