### ISSUE TITLE
[Core] Move Core consumers to use new Response properties

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#25555]
See details at:

- [x] https://github.com/Azure/azure-sdk-for-net/pull/25362#discussion_r758599974 -- `Response.IsError` in azure-sdk-for-net
- [ ] `Response.IsError` in autorest.csharp shared source
- [ ] https://github.com/Azure/azure-sdk-for-net/pull/25362#discussion_r758600049 -- `Response.Sanitizer`
- [ ] RequestFailedException(Response response)

**Comment by annelo-msft** [comment]
@pakrym can you confirm that this work is complete based on your recent PRs?

**Comment by pakrym** [comment]
What properties did you include in this issue?

**Comment by annelo-msft** [comment]
I updated the description - it's `Response.IsError` and `Response.Sanitizer`

**Comment by pakrym** [comment]
Then no, I only did IsError.

**Comment by pallavit** [comment]
I do not see Response.Sanitizer in experimental package but shared source in Azure.Core. - https://grep.app/search?q=Response.Sanitizer&filter[repo][0]=Azure/azure-sdk-for-net

Could you please help me understand what are we tracking as part of this issue.

**Comment by annelo-msft** [comment]
@pallavit, for Sanitizer, this comes from this comment: https://github.com/Azure/azure-sdk-for-net/pull/25362#discussion_r758600049

Without investigating further, I believe we should look at where HttpMessageSanitizer is used in Azure.Core types and consolidate that usage to the single sanitizer set on the message response.

For RequestFailedException, we should evaluate places where we create instances using other constructors and consolidate to use the one constructor that takes Response if that is possible.
