### ISSUE TITLE
Cosmos: Missing property default value

### ISSUE THREAD

**Issue by BernhardHofmann** [Azure/azure-sdk-for-net#25552]
What is the default value of this property?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6ac8b690-11a0-3ef4-9aad-4955d4e78340
* Version Independent ID: 2d6086bb-5e5b-6f88-6132-b79eda26a99c
* Content: [TableRequestOptions.MaximumExecutionTime Property (Microsoft.Azure.Cosmos.Table) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tablerequestoptions.maximumexecutiontime?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos.Table/TableRequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos.Table/TableRequestOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@BernhardHofmann Sorry for the delay on this one but as a nullable Property, it doesn’t have a default value. When it’s not set, the operation will stop after your retry policy is exhausted. 

Thanks
Saurabh
