### ISSUE TITLE
Avro uses an outdated Newtonsoft.Json package

### ISSUE THREAD

**Issue by jhclark** [Azure/azure-sdk-for-net#2556]
https://github.com/Azure/azure-sdk-for-net/blob/master/src/ServiceManagement/HDInsight/Microsoft.Hadoop.Avro/packages.config points to Newtonsoft.Json 6.0 while the current version is 9.0.

For our team, this means we end up writing a lot of assembly binding redirects due to this conflicting version.

**Comment by markcowl** [comment]
@jhclark This is the service management (RDFE) version of the software.  While supported, it is unikely to get updates to the latest versions.  I would suggest updating to the resource manager version if you need to use later dependency versions

**Comment by utahkay** [comment]
What is the "resource manager version" of Microsoft.Hadoop.Avro, and how do I find it?

**Comment by jhclark** [comment]
Bump. I'm also unclear on what the distinction and purposes of the two versions are.


Get Outlook for Android






On Mon, Dec 12, 2016 at 10:28 AM -0800, "utahkay" <notifications@github.com> wrote:












What is the "resource manager version" of Microsoft.Hadoop.Avro, and how do I find it?

**Comment by mkstephenson** [comment]
I would also like to know where to get the resource manager version of the avro package.

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.
