### ISSUE TITLE
[QUERY] - How to use cloud-init with the ResourceManager or Fluent SDKs

### ISSUE THREAD

**Issue by stowen-msft** [Azure/azure-sdk-for-net#25560]
**Query/Question**
Hi!  Today I am using Fluent to create VMs in my app's deployment validation process.  I would like to create VMs and use a cloud-init script with them.  

There are plenty of examples of doing this using the `az cli` but I haven't found an example of how to do this with any of the dotnet SDKs.  

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8] dotnet 6 
 - IDE and version : [e.g. Visual Studio 16.3] VS 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by stowen-msft** [comment]
Figured it out and forgot I'd opened this one.  

Answers over here https://github.com/Azure/azure-sdk-for-net/issues/25693
