### ISSUE TITLE
[Core] Address design concerns about pipeline

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#25565]
- [ ]  Resolve the issue that we are throwing when the HttpPipeline public constructor is called AND a policy is added to the call via RequestOptions.
- [ ] Investigate whether it's possible to refactor pipeline as follows:

> It seems wrong that the classifier is set on the pipeline. It should be a parameter to the pipeline.Send method. The method would set it on the message. Message would be a fundamental object that flows through the system and Response is just a "view" over a message, i.e. Response has a pointer to message not the other way.
> 
> If the pipeline was designed this way, the error feature would be trivial to implement: a) message has internal IsError property that simply calls the classifier stored in message. b) response, having a pointer to message, would just call _message.IsError.
> 
> This is just an example of a feature that would get easier with this architecture. I feel like this would help with many other problems we ran into in the past.

See https://github.com/azure/azure-sdk-for-net/issues/24164 for further context.

**Comment by annelo-msft** [comment]
Additional design concerns about doing so much work in policies shared by @KrzysztofCwalina in a recent discussion:
- We have made Azure.Core configurable, but many of our policies are not public
- Some of them are shared source and some of them are internal, and this makes many of the customizations we hoped for not possible
- For example, header replacement requested by https://github.com/Azure/azure-sdk-for-net/issues/37427 could be done in either the pipeline.Send method when the request is created, or in generated code
- Why do we have pipeline policies adding headers later, when we know about them from the service spec and could be generated?
- More generally, it feels like we do too many things in policies, and it makes the code difficult to understand, e.g. because policies are chained and dynamic.  It is very hard to understand what the end result is when the pipeline runs
- Ideally, more logic could be moved into the pipeline send method, e.g. to create the request and then only truly auxiliary things would happen in policies that you don't need to understand concretely, like retries

Based on this, it might be good to explore how much of the pipeline we could move into static methods outside the pipeline, with a goal to improve the understandability of service method code.  Given that policies are internal and our pipeline builder logic is encapsulated, we might be able to make design improvements here without breaking changes.

**Comment by pallavit** [comment]
@annelo-msft , @KrzysztofCwalina is this still a valid concern.
If so, is this something we would like to consider for new toolchain?

**Comment by annelo-msft** [comment]
I created this issue to track design considerations @KrzysztofCwalina raises about the pipeline from time to time.  I believe we are addressing many of them in ClientModel, but we can track evaluating this as part of the ClientModel release activities.

Can you clarify if you meant more than that by your comment regarding the new toolchain?  I am unfamiliar with that terminology.

**Comment by annelo-msft** [comment]
For ClientModel, just wanting to review this to ensure we've addressed any top-of-mind design concerns we had!  Once we've done a cursory check of this, we can move this back into the backlog to improve on existing pipeline concerns over time.
