### ISSUE TITLE
DataContractResolver should throw a more specific error message for unsupported types

### ISSUE THREAD

**Issue by jhclark** [Azure/azure-sdk-for-net#2557]
Currently, the DataContractResolver throws if type.IsUnsupported() but the error message is opaque. For example, if it's unsupported because it doesn't have a parameterless constructor, then it should say so.

The work is then to return a specific error code (enum?) from TypeExtensions.IsUnsupported and add this to the exception.

**Comment by idear1203** [comment]
We don't use `DataContractResolver` in SDK code now.
