### ISSUE TITLE
[BUG] The Service Bus CPU usage for Azure.Messaging.ServiceBus is higher than WindowsAzure.ServiceBus when receiving and completing messages

### ISSUE THREAD

**Issue by mojesha** [Azure/azure-sdk-for-net#25573]
### Library name and version

Azure.Messaging.ServiceBus 7.5.0
WindowsAzure.ServiceBus 6.2.0

### Describe the bug

As mentioned in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md, WindowsAzure.ServiceBus is officially deprecated, and Azure.Messaging.ServiceBus is the new SDK. But the Service Bus CPU usage for Azure.Messaging.ServiceBus (new) is higher than WindowsAzure.ServiceBus (old) when receiving and completing messages. I done three tests and the result was shown as below. (All the messages were been received and completed successfully during testing)

- test 1 : Azure.Messaging.ServiceBus, outgoing messages were =~ 7k/min
- test 2 : WindowsAzure.ServiceBus, outgoing messages were =~ 7k/min
- test 3 : WindowsAzure.ServiceBus, outgoing messages were =~ 14k/min

Summary for the tests :
- Test 1 and test 2’s outgoing messages count is similar, but the CPU usage for test 1 is obviously higher than test2.
- In test 3, the messages count was double, and the CPU usage for test 3 is similar to test 1.
 
<img width="1619" alt="image" src="https://user-images.githubusercontent.com/84300388/143997740-5942d20a-87f5-4993-b53c-921c3ccdb903.png">

Seems like it's becasue WindowsAzure.ServiceBus is using CompleteBatchAsync. But Azure.Messaging.ServiceBus is using AutoCompleteMessages.

### Expected behavior

The Service Bus CPU usage should be similar when using both Azure.Messaging.ServiceBus and WindowsAzure.ServiceBus.

### Actual behavior

The Service Bus CPU usage for Azure.Messaging.ServiceBus is obviously higher than WindowsAzure.ServiceBus when receiving and completing messages.

### Reproduction Steps

"MessageCount" ="200"
"MessageCountInBatch" value="100"
"ReceiveMessageTimeout" value="10"
"ReceiveMessageCountInBatch" value="100"

#### Azure.Messaging.ServiceBus
```
public async Task TestProcessQueueMessageAsync()
        {
            try
            {
                // Handle V2 message
                var client = new ServiceBusClient(QueueConnectString);

                // create the options to use for configuring the processor
                var options = new ServiceBusProcessorOptions
                {
                    AutoCompleteMessages = true,

                    // I can also allow for multi-threading
                    MaxConcurrentCalls = MessageCountInBatch
                };

                // create a processor that we can use to process the messages
                var processor = client.CreateProcessor(QueueName, options);

                // configure the message and error handler to use
                processor.ProcessMessageAsync += MessageHandler;
                processor.ProcessErrorAsync += ErrorHandler;

                // start processing
                await processor.StartProcessingAsync();
                Log.Info($"Start to process the message for v2");
                
            }
            catch (Exception e)
            {
                Log.ErrorFormat("Error:{0}, stack:{1}", e.Message, e.StackTrace);
            }
        } 
```
#### WindowsAzure.ServiceBus
```
        public async Task TestReceiveQueueMessageAsync()
        {
            try
            {
                const int batchMessageTimeout = 1;
                while (true)
                {
                    var start = DateTime.UtcNow;

                    // var gotCount = MessageCount * MessageCountInBatch / ReceiveMessageCountInBatch;
                    for (int i = 0; i < MessageCountInBatch; i++)
                    {
                        var queues = QueueClient.GetMessages(batchMessageTimeout, ReceiveMessageCountInBatch);
                        Log.Info($"Receive messages, the message count is {queues.Count}");
                        if (queues.Count == 0)
                        {
                            continue;
                        }

                        foreach(var queue in queues)
                        {
                            Log.Debug($"message content is {queue.MessageBody}");
                        }

                        QueueClient.DeleteMessagesAsync(queues).GetAwaiter().GetResult();
                        Log.Info($"Delete these messages.");
                    }

                    var sleepSeconds = 90 - (DateTime.UtcNow - start).TotalSeconds;
                    if (sleepSeconds > 0)
                    {
                        System.Threading.Thread.Sleep((int)(sleepSeconds * 1000));
                    }
                    else
                    {
                        Log.Warn($"The time sent message is over than one minute");
                    }
                }
            }
            catch (Exception e)
            {
                Log.ErrorFormat("Error:{0}, stack:{1}", e.Message, e.StackTrace);
            }
        }

        public List<BaseSQSMessage> GetMessages(int iTimeoutSecs, int messageCount = 10)
        {
            List<BaseSQSMessage> baseMessages = new List<BaseSQSMessage>();
            try
            {
                var brokeredMessages = mQueueReceiver.ReceiveMessagesAsync(messageCount, TimeSpan.FromSeconds(iTimeoutSecs)).GetAwaiter().GetResult().ToList();
                foreach (var brokeredMessage in brokeredMessages)
                {
                    baseMessages.Add(new MSSQSMessageV2(brokeredMessage)
                    {
                        QueueClient = this
                    });
                }
            }
            catch (Exception e)
            {
                log.ErrorFormat("V2 GetMessages, result=Failure, queueName={0}, messageCount={1}, exception={2}, exceptionMessage={3}",
                   mQueueName, messageCount, e.GetType().Name, e.Message);
            }
            return baseMessages;
        }

        public async Task<bool> DeleteMessagesAsync(List<BaseSQSMessage> Messages)
        {
            var messageIdList = string.Join(",", Messages.Select(m => m.MessageID).ToArray());

            bool isSuccess = false;
            try
            {
                List<Guid> brokeredMessageGuidList = new List<Guid>();
                foreach (BaseSQSMessage msg in Messages)
                {
                    BrokeredMessage brokeredMessage = GetBrokeredMessage(msg);
                    brokeredMessageGuidList.Add(brokeredMessage.LockToken);
                }
                await mQueueClient.CompleteBatchAsync(brokeredMessageGuidList);
                isSuccess = true;
            }
            catch (Exception e)
            {
            }
            return isSuccess;
        }
```

### Environment

Windows 10 .NET 4.7.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @mojesha,
Thank you for submitting this issue and we're sorry that you are running into trouble. Since the metrics you are evaluating are server-side metrics, we will need to reach out to the service team to help diagnose the issue. It is possible that the differences are related to the feature set available over SBMP protocol (which WindowsAzure.ServiceBus uses) and AMQP protocol (which Azure.Messaging.ServiceBus uses). For one thing, batch message completion is not supported over AMQP.

**Comment by JoshLove-msft** [comment]
In order to verify whether the issue is SBMP vs AMQP, would you be able to run your tests targeting AMQP when using WindowsAzure.ServiceBus? If this is the issue, the numbers you see should be similar between WindowsAzure.ServiceBus and Azure.Messaging.ServiceBus.
