### ISSUE TITLE
[QUERY] Storage: Query queue runtime properties

### ISSUE THREAD

**Issue by hgjura** [Azure/azure-sdk-for-net#25579]
### Library name and version

Azure.Storage.Queues latest

### Query/Question

Hello

I have a requirement to create some functionality for some queues that resembles the Azure Service Bus' "Auto Delete When Idle".

Is there a possibility in the Sdk to retrieve Storage Queue metadata, more precisely when it was last used/accessed, or when was the last message posted or retrieved or deleted? So I can determine since when the queue was idle.

Thanks
Herald

**Comment by jsquire** [comment]
Hi @hgjura.   Thank you for reaching out and we regret that you're experiencing difficulties.    The Service Bus client library has a [ServiceBusAdministrationClient](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient) which allows you to manage entities for the namespace, including reading their runtime properties.   

For your scenario, the [GetQueueRuntimeProperties](https://docs.microsoft.com//dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient.getqueueruntimepropertiesasyn) method would allow you to view the [QueueRuntimeProperties](cs.microsoft.com/dotnet/api/azure.messaging.servicebus.administration.queueruntimeproperties), which includes the timestamp that the service believes it was last accessed.  There is also a [GetQueuesRuntimePropertiesAsync](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient.getqueuesruntimepropertiesasync) method that would allow you to inspect all queues for the namespace in a single call.

I'm going to mark this as addressed, but please feel free to use the "`/unresolve`" command if you'd like to continue the discussion.

**Comment by hgjura** [comment]
/unresolve 

Hello,

The question was not about Azure Service Bus, but rather if there was something similar in the Azure.Storage.Queues library. Something in the metadata which spots when the (Azure Storage) queue was used last.

Thanks
Herald

**Comment by jsquire** [comment]
Apologies; that's my error.   I misread.   Redirecting.

**Comment by seanmcc-msft** [comment]
Hi @hgjura,

You can retrieve queue metadata with `QueueClient.GetProperties()` or `.GetPropertiesAsync()`, which calls the REST API [Get Queue Metadata](https://docs.microsoft.com/en-us/rest/api/storageservices/get-queue-metadata).

Unfortunately, the only metadata stored for each queue is the approximant message count and user-settable metadata.  Last used/accessed and last message posted or retrieved or deleted are not properties that are tracked by the queue service.

-Sean
