### ISSUE TITLE
[QUERY] How to learn how to do something (e.g. create an app service managed certificate)

### ISSUE THREAD

**Issue by jbaumbach** [Azure/azure-sdk-for-net#25582]
Hello team, I need to do something specific but thought I'd also bring up a broader issue.

## Specific Task

I need to create an app service managed certificate via C#. Our MS support rep gave us this Powershell script, which works great:

    $PropertiesObject = @{
        canonicalName = $domainName
        serverFarmId  = $AppServicePlanId
    }
         
    New-AzResource -Name $certName -Location $location `
        -PropertyObject $PropertiesObject `
        -ResourceGroupName $ResourceGroupName `
        -ResourceType Microsoft.Web/certificates `
        -Force

Trying to do this through this SDK is proving to be incredibly challenging. Where to even start? No search terms I entered to find a way returned anything useful. Is it `Fluent`? Is it `Management`? Is it "New Releases" or "Previous Versions"? 

I eventually came across this page https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Microsoft.Azure.Management.Websites/2.2.0/api/Microsoft.Azure.Management.WebSites/Microsoft.Azure.Management.WebSites.CertificatesOperationsExtensions.html 

That seems like what I want. But what is that first parameter? Its of type `Microsoft.Azure.Management.WebSites.ICertificatesOperations` but how do you get that? I websearched for a while and came up empty.

There are no code samples or anything that can be useful for using that call.

How can this be done in C#?

## Broader Issue

The main problem seems to be a lack of useful documentation to help someone actually use these libraries. We need some kind of methodology about how to go about finding and using the correct library.

Something like, if I enter a phrase from the Azure UI that I want to do, like "Create App Service Managed Certificate", there should be *something* that comes back that has useful information. I don't know exactly what that would look like, but as of now, unless you happen to know the MS developer who wrote this stuff and can ask, it's basically useless.

For example, I wanted to list the Application Insights instance names that each of our web apps was pointing to. Through the "Fluent" library, I was able to get a list of our web apps, then get the config settings, and finally get the AI instance ID. But to look that ID up and get the AI instance name seemed impossible.

Finally I came across a comment by an MS developer towards the bottom of this page that pointed me to some rando library I had never heard of. https://github.com/Azure/azure-libraries-for-net/issues/354 

Again, no code samples to go by, but after a bit of trial and error I was finally able to get it to work. 

There has to be a better way.  I presume the vast majority of developers just give up trying to do something.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@jbaumbach thank you for reaching us, we're continues on improving the dev-exp which include the docs, and yes sill not good, sorry.
To your specific ask, we will work out a sample for it.
