### ISSUE TITLE
Can't connect to HTTPS URL because the SSL module is not available

### ISSUE THREAD

**Issue by DieselAnalytics** [Azure/azure-sdk-for-net#25584]
[Enter feedback here]
To whom it may concern,

I get the following error:

`azure.core.exceptions.ServiceRequestError: Can't connect to HTTPS URL because the SSL module is not available.`

when I run the following code:

```
service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format(
"https",
account_name
), credential=account_key)

fs_name = "container-created-with-python"
filesystem_client = service_client.create_file_system(file_system=fs_name)

```
to create a file system. Here are my complete code snippet:

```
from azure.storage.filedatalake import DataLakeServiceClient

account_name = "<my account>"
account_key = "<my key>"

service_client = DataLakeServiceClient(account_url="{}://{}.dfs.core.windows.net".format(
"https",
account_name
), credential=account_key)

fs_name = "container-created-with-python"
filesystem_client = service_client.create_file_system(file_system=fs_name)
```

What  is causing this error? Is there an additional package I need to handle this? I  am executing the code on Windows 10 inside a conda environment based on Python 3.8. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cbde321-a073-514b-3603-5b0ed15a8c20
* Version Independent ID: 6eb549df-b9a1-5005-8fe1-19057a456c25
* Content: [DataLakeServiceClient.CreateFileSystem(String, PublicAccessType, IDictionary&lt;String,String&gt;, CancellationToken) Method (Azure.Storage.Files.DataLake) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeserviceclient.createfilesystem?view=azure-dotnet#remarks)
* Content Source: [xml/Azure.Storage.Files.DataLake/DataLakeServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.DataLake/DataLakeServiceClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by MughundhanRaveendran-MSFT** [comment]
@DieselAnalytics , 
Thanks for reaching out to us.

I dont think it is a problem with the SDK. It is more related to dev/local environment settings.

Please look into this SO article which has more info about this error : https://stackoverflow.com/questions/54135206/requests-caused-by-sslerrorcant-connect-to-https-url-because-the-ssl-module

**Comment by MughundhanRaveendran-MSFT** [comment]
@DieselAnalytics , Just wanted to check if you had the chance to look into my previous comment. Please let me know if it was helpful or not

**Comment by MughundhanRaveendran-MSFT** [comment]
@DieselAnalytics , Following up to check if you need further help from us
