### ISSUE TITLE
[Flaky Build] Analyze step frequently fails with ##[error]EXEC(0,0): Error : read ECONNRESET

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#25585]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1220111&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1222222&view=results

**Comment by annelo-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/25578/checks?check_run_id=4385748798

**Comment by annelo-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/25594/checks?check_run_id=4390000611

**Comment by annelo-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/25594/checks?check_run_id=4399025474

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1229903&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9
