### ISSUE TITLE
Null in unexpected places should throw a specific actionable error

### ISSUE THREAD

**Issue by jhclark** [Azure/azure-sdk-for-net#2559]
Currently, a null value on a reference type not marked with [NullableSchema] throws an error message with very little clue about where in the object hierarchy the issue occured and what to do about it.

I believe this error is coming from https://github.com/Azure/azure-sdk-for-net/blob/master/src/ServiceManagement/HDInsight/Microsoft.Hadoop.Avro/Serializers/NullableSerializer.cs:

     var exception = new SerializationException(
                string.Format(
                    CultureInfo.InvariantCulture,
                    "Unexpected null value for the object of type '{0}'. Please check the schema.",
                    this.Schema.RuntimeType));

I would like to see the following added to this message:
* The parent class name containing the unexpected null
* The field/property name of the unexpected null
* A specific recommendation that the attribute [NullableSchema] can be added to resolve this issue. For bonus points, add a link to the documentation of this schema type.

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.
