### ISSUE TITLE
Migration from WindowsAzure.ServiceBus (legacy) to Azure.Messaging.ServiceBus (latest)

### ISSUE THREAD

**Issue by arunprakashn** [Azure/azure-sdk-for-net#25609]
### Library name and version

WindowsAzure.ServiceBus 5.1.0

### Query/Question

Our project currently uses the "Windows.Azure.ServiceBus 5.1.0" to communicate with the service bus. I have two questions,
1. Is there a migration guide for migrating from WindowsAzure.ServiceBus to the latest Azure.Messaging.ServiceBus?
2. Is there any performance improvement in terms of sending if I choose to have the latest SDK to communicate with the service bus? If yes, is there any documentation showing the improvement?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
I'm not sure how this got shuffled without being answered, @arunprakashn, and I apologize for that.   To answer your questions:

1) There is not one available at this time.  
2) There is no data available for this comparison.  Our performance benchmarking uses the previous generation library, `Microsoft.Azure.ServiceBus`.
