### ISSUE TITLE
[QUERY] How to migrate CloudBlobClient(new Uri(url), credential, handler) to BlobServiceClient ?

### ISSUE THREAD

**Issue by gabidabet** [Azure/azure-sdk-for-net#25614]
### Library name and version

Azure.Storage.Blobs 12.8.0

### Query/Question

How to migrate CloudBlobClient(new Uri(url), credential, handler) to BlobServiceClient ?

We have a legacy code base where we used the verison v11 of blob storage sdk. We want to migrate to v12. But there is an example where we didn't know how to do the same thing.
`new CloudBlobClient(uri, credential, delegateHandler)`
How to pass that delegate to BlobServiceClient  if possible. If not what is the alternative.

### Environment

Windows 10 .net core 3.1.
Visual Studio 2019.

**Comment by amishra-dev** [comment]
Hi @gabidabet,
The migration guide is located here https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md

**Comment by gabidabet** [comment]
@amishra-dev yeah I already read it and I can say that it is not sufficient, it only cover things that are in documentation. And don't replay to my question. For example the case that I asked about does not mentioned in the documentation or the migration guide or how to do it in another way. Thank you for you help.

**Comment by amishra-dev** [comment]
Hi @gabidabet,
Apologies for missing that. Are you looking for what to do with the Http delegation handler, if you can give a small snippet on what your code does with it in v11, we can give you the equivalent in v12. 
In V12 we have introduces Pipeline policies, there are a few policies we have written. Please look at this doc page in case this helps. https://docs.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection

**Comment by gabidabet** [comment]
Hi @amishra-dev ,
Thank you very much for your support, we configure proxy in that delegation handler. 
Thank you.

**Comment by amishra-dev** [comment]
> Hi @amishra-dev Ashish Mishra (AZURE) FTE , Thank you very much for your support, we configure proxy in that delegation handler. Thank you.

Kindly look at 
https://github.com/Azure/azure-sdk-for-net/blob/d92a7c8d367caa5b0711ac3ac6e5a9dd2f3d3275/sdk/core/Azure.Core/samples/Configuration.md#configuring-a-proxy
