### ISSUE TITLE
Blank remarks for RetryExponential.cs

### ISSUE THREAD

**Issue by gukoff** [Azure/azure-sdk-for-net#25612]
This looks wrong: 

![image](https://user-images.githubusercontent.com/5655837/144236838-d92f5c17-2c09-49d6-b26f-ba95bb0e8c27.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75652f4c-d360-24f6-c3a9-bab9030c6d3e
* Version Independent ID: e9b0ab11-34f7-c2f2-aea0-2a3f33a6743b
* Content: [RetryExponential Class (Microsoft.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.retryexponential?view=azure-dotnet&source=docs)
* Content Source: [xml/Microsoft.ServiceBus/RetryExponential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus/RetryExponential.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by gukoff** [comment]
Adblock is disabled.
Content source XML contains the missing remarks. Final HTML doesn't:

![image](https://user-images.githubusercontent.com/5655837/144237162-2499f19e-b815-47f3-a414-e152ac1e526a.png)

**Comment by SaurabhSharma-MSFT** [comment]
@gukoff Thanks for your feedback and yes looks like something off with the documentation.  However, you are looking at the legacy servicebus API documentation which has been archived and currently read only.  Please refer to the newer documentation page over [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.retryexponential?view=azure-dotnet). Thanks.
