### ISSUE TITLE
PersonDirectory - AddPersonFaceAsync

### ISSUE THREAD

**Issue by adamy** [Azure/azure-sdk-for-net#25629]
Hi there,

With AddPersonFaceAsync on PersonDirectory api in Congnitive - Face , how to specify the image URL in the request?
It seems that parameter is missing from the method.

Please advice, Thanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9832084-3267-7d19-1fad-e99162c3187e
* Version Independent ID: 7e5b72f9-03ef-eddc-655f-5f26b4db5164
* Content: [PersonDirectoryExtensions.AddPersonFaceAsync(IPersonDirectory, String, String, String, String, String, CancellationToken) Method (Microsoft.Azure.CognitiveServices.Vision.Face) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.vision.face.persondirectoryextensions.addpersonfaceasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.CognitiveServices.Vision.Face/PersonDirectoryExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.CognitiveServices.Vision.Face/PersonDirectoryExtensions.xml)
* Service: **cognitive-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by dev-corbett** [comment]
Hey folks, any update on this one?
