### ISSUE TITLE
Use OperationInternal for CertificateOperation

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#25627]
I used `OperationInternal` for pseudo-LROs in Key Vault with PR #25593 (issue #22912) but `CertificateOperation` is a bit different and may require additional discussions and changes to `OperationInternal` (or `OperationInternal<T>`) to support cancelled states. Specifically, the `Cancel` and `Delete` methods on `CertificateOperation` need consideration whether that creates a successful state with no value or a failed state, which would cause subsequent `UpdateStatus/Async` calls to throw, which would be a behavioral change.

I don't think any of this is necessarily a hard problem to solve, but being shared code want to make sure we consider a robust strategy.

**Comment by pallavit** [comment]
@heaths - Is this still an issue we want to tackle?

**Comment by heaths** [comment]
Those working on our helpers like Pavel and @AlexanderSher back in the day requested this, but it's clearly not been a priority. Personally, I don't think it's worth it and, if we get serious about auto-generating, would be done automatically anyway. I wonder if Alexander still wants this?

**Comment by pallavit** [comment]
I will go ahead and close it in that case.
