### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by seble-nigussie** [Azure/azure-sdk-for-net#25631]
### Library name and version

 'Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerMathTranslator' threw an exception. Could not find method 'Round' on type 'System.Math'

### Describe the bug

Hello, 

I'm getting the following exception thrown after updating to net6.0. The thing is it doesnt throw the exception locally and works fine, but in azure app service it throws.  I am using the same data both locally and for dev. So, the problem couldnt be caused by the data. Its throwing this when reading from database. All my ef packages are updated to 6.0. Please help I couldnt figure out what this could be related to. 

The type initializer for 'Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerMathTranslator' threw an exception. Could not find method 'Round' on type 'System.Math'

### Expected behavior

Should work on azure app service, like its working locally.

### Actual behavior

Fails on azure app service

### Reproduction Steps

I dont have one. Since its working locally.

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.EntityFrameworkCore.SqlServer` package is maintained as [#26878](https://github.com/dotnet/efcore/issues/26878).
