### ISSUE TITLE
IConfigurationRefresher still Preview

### ISSUE THREAD

**Issue by Terry-Cornwell** [Azure/azure-sdk-for-net#25639]
Hi,
Is the IConfigurationRefresher interface still considered Preview? Other documentation (best practice guides etc..) would imply it is not and this document is flagged as preview incorrectly.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76ce53b7-e6a5-83cc-4f30-992048ad6eef
* Version Independent ID: 6d7165dd-fa63-270f-f63a-516e628aada5
* Content: [IConfigurationRefresher Interface (Microsoft.Extensions.Configuration.AzureAppConfiguration) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfiguration.iconfigurationrefresher?view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Extensions.Configuration.AzureAppConfiguration/IConfigurationRefresher.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Extensions.Configuration.AzureAppConfiguration/IConfigurationRefresher.xml)
* Service: **azure-app-configuration**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Extensions.Configuration.AzureAppConfiguration` is maintaned as [#294](https://github.com/Azure/AppConfiguration-DotnetProvider/issues/294).
