### ISSUE TITLE
[BUG] Azure Functions - Operations that change non-concurrent collections must have exclusive access

### ISSUE THREAD

**Issue by XavierGeerinck** [Azure/azure-sdk-for-net#25652]
### Library name and version

latest

### Describe the bug

We are receiving a random error suddenly where APIM detects a 404 on a Function Invocation. This function simply gets a HTTP Incoming Requests and publishes it on Event Hub so we are a bit puzzled why this might happen.
 
What we could find back already is: “Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct."

After debugging together with internal Microsoft people, it seems that this might be causing it (to be validated again):

https://github.com/Azure/azure-sdk-for-net/blob/b407041de4f43cf9397a45bb3943e0aae736f731/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Triggers/EventHubAsyncCollector.cs#L65

### Expected behavior

No crashes in the runtime

### Actual behavior

Runtime crash causing Azure Functions to stop working with error: "Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct."

### Reproduction Steps

1. Create an Azure Function with the Code Below
2. Connect an Event Hub to it
3. Trigger the endpoint a lot under load

```csharp
#r "Newtonsoft.Json"
#r "Microsoft.Azure.WebJobs.Extensions.Http"

using System.Net;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;
using Newtonsoft.Json;
using Microsoft.Azure.WebJobs.Extensions.Http;


public static async Task<IActionResult> Run(HttpRequest req, ILogger log, IAsyncCollector<string> outputEventHub2)
{
    string message = await req.ReadAsStringAsync();
    await outputEventHub2.AddAsync(message);
    return new OkResult();
}
```

### Environment

Azure Functions

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by XavierGeerinck** [comment]
Any update on this?

**Comment by JoshLove-msft** [comment]
Hi @XavierGeerinck,
Any chance you can provide us with the full stack trace related to the exception? Or the relevant functions logs would also be helpful.

From looking at the code that you've referenced, the `_batches` dictionary already ensures exclusive access by virtue of the `_batchSemaphore`.

**Comment by XavierGeerinck** [comment]
Hi @JoshLove-msft,

How would we be able to get a full stack trace of the Azure Function?

**Comment by JoshLove-msft** [comment]
You should be able to see this in Functions monitoring from the Portal:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitoring

**Comment by gs9824** [comment]
@JoshLove-msft 
I have been working with Xavier on this issue. 

From the documentation it is not clear how to get a full stack trace. Can you please be more specific ? Most detailed information we were able to get is the following :

![issue](https://user-images.githubusercontent.com/36197920/157245341-2b165eb2-8e14-4d88-9e9d-39d63de9ce1f.png)

**Comment by XavierGeerinck** [comment]
See reply of Gerdy

**Comment by JoshLove-msft** [comment]
Are you able to click on the row that contains the error in App Insights?
