### ISSUE TITLE
[Flaky-Test] BufferedSender

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#25655]
The test frequently crosses the 8sec time limit for recorded tests.

cc @christothes

**Comment by JoshLove-msft** [comment]
Just went searching for an existing issue - this one is very flaky.
/cc @Mohit-Chakraborty

**Comment by JoshLove-msft** [comment]
And the test recording is 35MB.

**Comment by christothes** [comment]
> And the test recording is 35MB.
> 
> We should consider making this one LiveOnly.

Or put some reasonable limit on the payload sizes or test dataset.
