### ISSUE TITLE
Missing FileNotFoundException in remarks

### ISSUE THREAD

**Issue by AlfonsDreschler** [Azure/azure-sdk-for-net#25662]
I am missing a FileNotFoundException (or something like that) in the possible exceptions mentioned in the remarks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19a1d06b-12f8-7709-76e6-8144ff1020ee
* Version Independent ID: 1eca404c-9116-e0d3-674f-ce07490cbe25
* Content: [ShareFileClient.OpenReadAsync(ShareFileOpenReadOptions, CancellationToken) Method (Azure.Storage.Files.Shares) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharefileclient.openreadasync?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Files.Shares/ShareFileClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.Shares/ShareFileClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@AlfonsDreschler We are looking into this and get back to you in case need any information.

**Comment by PramodValavala-MSFT** [comment]
@AlfonsDreschler Thanks for the feedback and apologies for the delay on this! Both `OpenReadAsync` and `OpenRead` will raise a [`RequestFailedException`](https://docs.microsoft.com/en-us/dotnet/api/azure.requestfailedexception?view=azure-dotnet) for other failures that may occur.

We will work with the concerning team to get this addressed in the docs.
