### ISSUE TITLE
[Flaky Test] Relationships_PaginationWorks takes a long time

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#25666]
### Library name and version

DigitalTwins

### Describe the bug

This test frequently exceeds the global timeout of 8s.

### Expected behavior

It should take less than 8s.

### Actual behavior

Takes more than 8s.

### Reproduction Steps

Run the test locally or in CI.

**Comment by pakrym** [comment]
This takes suspiciously long considering how few requests it makes. 

It's very fast with the current test framework:

![image](https://user-images.githubusercontent.com/1697911/144527046-23377027-1f5a-4bd3-a4db-4165ff39c0a1.png)

**Comment by JoshLove-msft** [comment]
Looks like this was due to the retry-after feature not being in Test-Proxy. It is now added so once we re-enable Digital Twins to use test proxy, this should no longer be an issue.
