### ISSUE TITLE
Release ETA?

### ISSUE THREAD

**Issue by alex-makarov** [Azure/azure-sdk-for-net#25676]
What's the ETA for this feature to go out of Preview?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36ba3c46-71b7-2d92-1535-e9ab6c9ff6c6
* Version Independent ID: eeb50376-6a63-b39c-6c60-99bdbb4eeef9
* Content: [EventHubBufferedProducerClient Class (Azure.Messaging.EventHubs.Producer) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.producer.eventhubbufferedproducerclient?view=azure-dotnet-preview)
* Content Source: [xml/Azure.Messaging.EventHubs.Producer/EventHubBufferedProducerClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.EventHubs.Producer/EventHubBufferedProducerClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @alex-makarov.   There's no firm GA date at this time.  If all goes well with beta feedback and production readiness testing, we'd like to release this as GA in the first quarter of 2022.  Best case scenario would be with our March 2022 release, but that is subject to change.
