### ISSUE TITLE
[BUG] DeviceUpdate Delete recording appears incorrect

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#25672]
### Library name and version

Azure.ResourceManager.DeviceUpdate

### Describe the bug

In the [response ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/deviceupdate/Azure.ResourceManager.DeviceUpdate/tests/SessionRecords/AccountOperationsTests/Delete().json#L999) to the DELETE request, the response body is null, but the content-length is 4. It's not clear if this is a service issue or an issue with the recording, but the content-length and the response body are not consistent. It seems like the "4" might be coming from the length of `null`, but the null value would not be treated as a string by the Test Framework, and the content-length should probably either be 0 or not present.

I tried re-recording to debug and see what is causing this, but the test-resources script did not create usable resources.

### Expected behavior

Content-Length and response body should be consistent.

### Actual behavior

Content-Length and response body are inconsistent.

### Reproduction Steps

Run the Delete test from AccountOperationsTests or InstanceOperationsTests.

**Comment by scbedd** [comment]
Just for clarity, simple playback repros this right?

**Comment by JoshLove-msft** [comment]
> Just for clarity, simple playback repros this right?

Yep, you should be able to see the error in Test-Proxy from playback if you check out my branch.

**Comment by JoshLove-msft** [comment]
@mikeharder reproed this from the Portal and the response that comes back has a body consisting of "null" (without the quotes). The Test Framework is storing this as a JSON null in the session record. We will need to update the Test Proxy (new Test Framework) to correctly store this as "null".

**Comment by HarveyLink** [comment]
Closed as fixed https://github.com/Azure/azure-sdk-tools/pull/2634
