### ISSUE TITLE
[QUERY] Storage account Containers - Get Immutability Policy via C#

### ISSUE THREAD

**Issue by sdandu21** [Azure/azure-sdk-for-net#25677]
### Library name and version

Azure.Storage.Blobs v12.10.0

### Query/Question

Is there a mechanism to check whether a container has an active immutability policy via C#? I would like to check in my code before attempting to delete the container or any of its blobs or perform other actions.

https://docs.microsoft.com/en-us/azure/storage/blobs/immutable-policy-configure-container-scope?tabs=azure-portal 

### Environment

.NET

**Comment by SaurabhSharma-MSFT** [comment]
@sdandu21 We are looking into it and get back to you.

**Comment by blueww** [comment]
@sdandu21 

If you just want to see if the container has immutability policy or not, you can use the API: https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.getproperties?view=azure-dotnet, and the [output](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobcontainerproperties?view=azure-dotnet) has a bool properties "HasImmutabilityPolicy"

If you want to see the detail immutability policy properties on a container, you need to use management plane SDK.

- SDK: https://www.nuget.org/packages/Microsoft.Azure.Management.Storage/

- How to use SDK: https://azure.microsoft.com/da-dk/resources/samples/storage-dotnet-resource-provider-getting-started/

- Get container level worm sample:  https://github.com/Azure/azure-sdk-for-net/blob/dc94a67bd9a8bf22f880a32d61961a288d0e6186/sdk/storage/Microsoft.Azure.Management.Storage/tests/Tests/BlobServiceTests.cs#L575

**Comment by sdandu21** [comment]
Thank you!
