### ISSUE TITLE
404 on Samples page for "Azure IoT libraries for .NET"

### ISSUE THREAD

**Issue by kdethlefs** [Azure/azure-sdk-for-net#25685]
Samples leads to a 404. The destination is: https://azure.microsoft.com/resources/samples/event-hubs-dotnet-importfromweb/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1ca1e2-e65a-121e-efc7-d3c7209e54d5
* Version Independent ID: b75c32e7-42c2-0ea2-3f37-851976095ae2
* Content: [Azure IoT libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/iot?view=azure-dotnet#samples)
* Content Source: [api/overview/azure/iot.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/iot.md)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@kdethlefs We are looking into it and get back to you in case we need any other information.

**Comment by SaurabhSharma-MSFT** [comment]
@kdethlefs I am redirecting to specific team for documentation update as I couldn't able to find the sample myself.

**Comment by SatishBoddu-MSFT** [comment]
Hello @kdethlefs , Thanks for reporting this issue, yes we see the 'Page not found' issue.

We are working on this issue, meanwhile please let us know if the **below link** helps with your query?
[Generic Web Service to Event Hub scenario](https://github.com/jjonesbarbato/event-hubs-dotnet-importfromweb#generic-web-service-to-event-hub-scenario)

**Issue**: Page[ link ](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/iot#samples)
![image](https://user-images.githubusercontent.com/62923178/148010498-d560f112-eeca-4c39-960f-cf943cb53286.png)

**Comment by MaximRouiller** [comment]
Adding context from everyone involved. This was a link to the following sample:

https://github.com/Azure-Samples/event-hubs-dotnet-import-from-sql

Since this sample has been archived, it will not generate a corresponding page on our sample website. @kdethlefs can use this as a jumping point if some examples are required but now, the link needs to be removed as it will require us to either bring back the sample (update it, ensure correctness, etc.) which could take a longer time or create a new one. 

Either way, removing the link for now won't send people to a 404 page.

**Comment by kdethlefs** [comment]
I appreciate the tags. I'm sure this will come in use when I need it. I was exploring for a new project and it led to a 404, so I filed the issue to help out.

**Comment by kdethlefs** [comment]
I'm not sure what's the norm here, do I close the issue, as my issue is resolved, or do I wait for the removal pull request to go forward.?

**Comment by SatishBoddu-MSFT** [comment]
> I'm not sure what's the norm here, do I close the issue, as my issue is resolved, or do I wait for the removal pull request to go forward.?

Hello @kdethlefs We will take care of closing this Issue, thanks for the quick response on this.
