### ISSUE TITLE
[FEATURE REQ] Get list of active sessions in the specified queue/topic/subscription 

### ISSUE THREAD

**Issue by VeselovAndrey** [Azure/azure-sdk-for-net#25698]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

Is it possible to get list of sessions in the specified queue/topic/subscription? 
Use case: scale microservice based on sessions (there are no reasons to scale by CPU or total message count because if there are 1000 messages in single session only then 1 thread will process them all, all other instances will do nothing).

PS: Legacy WindowsAzure.ServiceBus library has such feature
https://docs.microsoft.com/ru-ru/dotnet/api/microsoft.servicebus.messaging.subscriptionclient.getmessagesessionsasync?view=azure-dotnet

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Similar request - https://github.com/Azure/azure-sdk-for-net/issues/20569

**Comment by JoshLove-msft** [comment]
Closing this as a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/20569
