### ISSUE TITLE
Documentation for Container.ReplaceItemAsync methods should include typical/accepted ItemResult codes in the remarks.

### ISSUE THREAD

**Issue by cdanek** [Azure/azure-sdk-for-net#25690]
Fairly straightforward feedback - the ReplaceItemAsync returns an ItemResult<T> with a `StatusCode` that includes all of the possible results; unfortunately there are no remarks on which results can occur, requiring the author to source-dive to explore. The Remarks section of the documentation could benefit (as could all of the container operations) from remarks that illuminate typical use-cases.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0286f791-878d-c285-c0d2-ebdfc02470be
* Version Independent ID: c8f1d594-e500-eb4b-50b5-8ec04724c482
* Content: [Container.ReplaceItemAsync&lt;T&gt;(T, String, Nullable&lt;PartitionKey&gt;, ItemRequestOptions, CancellationToken) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.replaceitemasync?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Karishma-Tiwari-MSFT** [comment]
Thanks for your feedback. We are looking into it.
