### ISSUE TITLE
[FEATURE REQ] Make Deserialize*** methods public instead of internal

### ISSUE THREAD

**Issue by DBojsen** [Azure/azure-sdk-for-net#25699]
### Library name

Azure.Analytics.Synapse.Artifacts

### Please describe the feature.

Please change accessibility level of Deserialize methods such as [DeserializeLinkedServiceResource](https://github.com/Azure/azure-sdk-for-net/blob/2dcbef7f0b56e3ebe5a2ebb57ced76d5ac0e5597/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/Models/LinkedServiceResource.Serialization.cs#L26) & [DeserializeLinkedService](https://github.com/Azure/azure-sdk-for-net/blob/2dcbef7f0b56e3ebe5a2ebb57ced76d5ac0e5597/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/Models/LinkedService.Serialization.cs#L63) to public.
I find it unnecessary restricting to have these as internal methods.

I need to be able to take the json representations in my repo and deserialize to the corresponding objects - this is currently blocking me from doing so.
This is a big change from Data Factory to Synapse Pipelines, as I can easily deserialize ADF objects from json.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by DBojsen** [comment]
For now, I have cloned the repo - changed the access level of the functions I need and build it into a dll.
Will be using that instead of the nuget - but I find it unfortunate, that I need to go thru this just to be able to use this functionality

**Comment by DBojsen** [comment]
Hi Anne

When using the git integration, all Synapse Pipeline components are saved (by Synapse) as json documents.

Venlig Hilsen

David Bojsen
+45 9181 9050
________________________________

**Comment by annelo-msft** [comment]
Hi @DBojsen, thanks for this additional information!  I'm looking into what precedents we have around making deserialization methods public in the Azure SDK (it isn't common practice), and working with the service team to understand this scenario better.  I'll need more time to understand the options here, but I will reply to you on this issue with a plan once I have it.  Thanks!

**Comment by DBojsen** [comment]
Hi Anne

Thank you for your help.
While I do not know about the normal practice in the Azure SDK, I do know that this is supported by the Data Factory nugets, which Synapse Pipelines is the logical successor for.

It would be a shame to let the community either build their own methods for this or require them to ‘hot-wire’ your code.

Venlig Hilsen

David Bojsen
+45 9181 9050
________________________________

**Comment by AtOMiCNebula** [comment]
@annelo-msft, see the issue I just referenced for another need for cross-library JSON deserialization.  ResourceGraph SDK can be used to fetch JSON representing Azure resources, and the recommended way to use them is something like this:

```csharp
ArmClient client = new(credential);
TenantCollection tenants = client.GetTenants();
await foreach (TenantResource tenant in tenants)
{
    QueryContent query = new(@"
Resources
| where type == ""microsoft.keyvault/vaults""
| order by name asc
");
    QueryResponse response = await tenant.ResourcesAsync(query);
    IList<IDictionary<string, JsonElement>> vaultDatas = response.Data.ToObjectFromJson<IList<IDictionary<string, JsonElement>>>();
}
```

It's super lousy to interact with `IDictionary<string, JsonElement>` instances though, compared to a proper type like `KeyVaultData`.  I'm hacking around this by using a reflection-aware `JsonConverter` implementation (see referenced issue), but it'd be great if the Azure SDKs would just stop trying to hide their JSON serializer/deserializer methods. 😄

**Comment by annelo-msft** [comment]
Hi @AtOMiCNebula -

Thanks for your inquiry!  @m-nash can address questions regarding management plane libraries such as `Azure.ResourceManager.KeyVault`.

**Comment by m-nash** [comment]
@annelo-msft I don't see any reason to have a separate answer here for management plane.  Consistency across all azure sdks would be the priority.  Once we have the results of your investigation from above lets make sure its compatible.
