### ISSUE TITLE
[BUG] The type initializer for 'Azure.Security.KeyVault.Keys.JsonWebKey' threw an exception.

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/azure-sdk-for-net#25705]
### Library name and version

Azure.Security.KeyVault.Keys 4.3.0-beta.4

### Describe the bug

I upgraded Azure.Security.KeyVault.Keys from 4.2.0-beta.2 to 4.3.0-beta.4
and upgrade Azure.Core from 1.20.0 to 1.21.0

When I run
```csharp
public static Track1Sdk.JsonWebKey ToTrack1JsonWebKey(this Track2Sdk.JsonWebKey track2Key){
if (track2Key.KeyType == Track2Sdk.KeyType.Rsa || track2Key.KeyType == Track2Sdk.KeyType.RsaHsm)
            {
                var rsa = track2Key.ToRSA();
                track1Key = new Track1Sdk.JsonWebKey(rsa);
            }
}
```

_**[[ REDACTED TO PREVENT KEY EXPOSURE ]]**_

It will throw exception when `track2Key.ToRSA()`

__

### Expected behavior

It should work

### Actual behavior

The conversion is failed with "The type initializer for 'Azure.Security.KeyVault.Keys.JsonWebKey' threw an exception."

### Reproduction Steps

run var rsa = track2Key.ToRSA(); in Azure.Security.KeyVault.Keys 4.3.0-beta.4

### Environment

PS C:\Users\bez> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.403\

Host (useful for support):
  Version: 5.0.12
  Commit:  7211aa01b3

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.209 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please forgive slow responses, as many of our team are out for the holidays.

**Comment by BethanyZhou** [comment]
Close as it has fixed when I load System.Text.Json correctly.
