### ISSUE TITLE
[BUG] BatchSharedKeyCredentials cannot handle trailing backslash

### ISSUE THREAD

**Issue by Flonk** [Azure/azure-sdk-for-net#25708]
### Library name and version

Microsoft.Azure.Batch 15.1.0

### Describe the bug

When passing a `baseUrl` to the `BatchSharedKeyCredentials` constructor that contains a trailing backslash, `BatchSharedKeyCredentials` fails and cannot authenticate any requests.

### Expected behavior

`BatchSharedKeyCredentials` should be able to handle baseUrls that contain or don't contain a trailing backslash.

### Actual behavior

When passing a `baseUrl` that contains a trailing backslash, `BatchSharedKeyCredentials` fails and cannot authenticate any requests.

### Reproduction Steps

```
var cred = new BatchSharedKeyCredentials(
    baseUrl: "https://somewhere.westeurope.batch.azure.com/",
    accountName: "accountName",
    keyValue: "keyValue");

var tasks = new List<CloudTask>();
var task = new CloudTask(...) { ... };
tasks.Add(task);
await batchClient.JobOperations.AddTaskAsync("BatchJobId", tasks); // this will throw
```

If the trailing backslash in the baseUrl is removed, the code will run as expected.

**Comment by SaurabhSharma-MSFT** [comment]
@Flonk We are looking into it and get back to you.

**Comment by SaurabhSharma-MSFT** [comment]
@Flonk That looks like a correct behavior as it is the expected URL for a batch account, and you can see the same on Azure portal as well - 
![image](https://user-images.githubusercontent.com/38112130/145494612-774c76fb-cf03-424f-ac51-2644fad69066.png)

Thanks
Saurabh

**Comment by Flonk** [comment]
@SaurabhSharma-MSFT In our case we were reading the URL from the environment variable `AZ_BATCH_ACCOUNT_URL` that is set inside the batch node.
`AZ_BATCH_ACCOUNT_URL` is one of many environment variables defined on batch nodes, as seen here: https://docs.microsoft.com/en-us/azure/batch/quick-create-cli

I would expect that whatever is set in `AZ_BATCH_ACCOUNT_URL` would work out of the box with `BatchSharedKeyCredentials`, but as it stands we need to remove the trailing backslash in our code. I guess an alternative to patching  `BatchSharedKeyCredentials`, the trailing backslash from the environment variable could be removed.

**Comment by SaurabhSharma-MSFT** [comment]
@Flonk I have checked this and yes you are correct environment variable `AZ_BATCH_ACCOUNT_URL` contains a trialing backslash. 
![image](https://user-images.githubusercontent.com/38112130/146261280-66a827a1-fad6-49fe-b5db-3f65666fd20d.png)
I am checking this internally and get back to you.
Thanks
