### ISSUE TITLE
Management code example incomplete

### ISSUE THREAD

**Issue by Turochamp** [Azure/azure-sdk-for-net#25719]
Managment code example is missing this line:
IAzure azure = Azure.Authenticate(credFile).WithDefaultSubscription();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2ee884-131a-5641-b433-3a305239f3a4
* Version Independent ID: 90f66938-afd9-1ffe-69ab-9ccf244e2956
* Content: [Azure SQL Database APIs for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/sql?view=azure-dotnet)
* Content Source: [api/overview/azure/sql.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/sql.md)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Turochamp** [comment]
Source:
https://github.com/Azure/azure-libraries-for-net#databases-and-storage

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
