### ISSUE TITLE
Change to LRO pattern in .NET clients

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#25716]
This issue tracks the work to move .NET clients to the new LRO pattern described here: https://github.com/Azure/azure-sdk/issues/3662#issuecomment-985112894

Changes include:
- Update .NET libraries to the new pattern
- [Updates to the .NET Guidelines](https://github.com/Azure/azure-sdk/issues/3678)
- [Updates to the Azure.Core LRO Samples](https://github.com/Azure/azure-sdk-for-net/issues/25715)

**Comment by pallavit** [comment]
@annelo-msft is this still valid? If so, could you share which SDKs need to be changed?
