### ISSUE TITLE
Supporting subscriptionTenantId and managementGroupId in SubscriptionClient.Alias.CreateAsync() Request 

### ISSUE THREAD

**Issue by jujinfu** [Azure/azure-sdk-for-net#25723]
### Library name

Microsoft.Azure.Management.Subscription

### Please describe the feature.

In the Azure UI, we already can request subscriptions to be created under a different tenant 
we see API calls being made to `https://management.azure.com/providers/Microsoft.Subscription/aliases/{subId}?api-version=2021-01-01-privatepreview`

with payload of 
`{additionalProperties: {managementGroupId: "", subscriptionTenantId: "{tenantId}",…}
billingScope: "{billingScope}"
displayName: "subscription-5"
resellerId: null
workLoad: "Production"}`

We would like to use this in our production API

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment]
`Microsoft.Azure.Management.Subscription` is able to create new subscriptions, you can refer to the following example.

``` csharp
string clientId = "";
string clientSecret = "";
string tenantId = "";

// get token
ClientCredential cc = new ClientCredential(clientId, clientSecret);
var context = new AuthenticationContext("https://login.microsoftonline.com/" + tenantId);
var result = context.AcquireTokenAsync("https://management.azure.com/", cc);
string AccessToken = result.Result.AccessToken;
var bauthCredentials = new TokenCredentials(AccessToken);
ServiceClientCredentials credentials = bauthCredentials;
DelegatingHandler[] handlers = new DelegatingHandler[] { };

// create SubscriptionClient
SubscriptionClient client = new SubscriptionClient(bauthCredentials, handlers);
client.SetRetryPolicy(new RetryPolicy<HttpStatusCodeErrorDetectionStrategy>(1));

// create new Subscription
const string aliasName = "navyprod1";
var putAliasRequest = new PutAliasRequest()
{
    Properties = new PutAliasRequestProperties()
    {
        DisplayName = "TestSub",
        Workload = Workload.Production,
        BillingScope = "/providers/Microsoft.Billing/billingAccounts/4756419/enrollmentAccounts/224190"
    }
};
var subscriptionResult = client.Alias.CreateWithHttpMessagesAsync(aliasName, putAliasRequest).ConfigureAwait(false).GetAwaiter().GetResult();

Console.WriteLine(subscriptionResult.Response.StatusCode);
Console.WriteLine(subscriptionResult);
Console.WriteLine(subscriptionResult.Body.Properties.SubscriptionId);
```

More information: [source code test sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/subscription/Microsoft.Azure.Management.Subscription/tests/FullDesktop/SubscriptionCreationTests.ScenarioTests.cs#L53)

**Comment by jujinfu** [comment]
Hi @dvbb 

thanks for the comment, however, I need to create them into a specific tenant. 

that is only available via that private preview API.

**Comment by dvbb** [comment]
Hi @jujinfu 

The API `api-version=2021-01-01-privatepreview` is not available in the current and historical versions of the SDK `Microsoft.Azure.Management.Subscription`.

This issue will route to the service team.

**Comment by veathipa** [comment]
Hey @jujinfu 

We have officially released the GA version (2021-10-01) of API which supports tenant id & management group Id, yes this is good to use for production scenarios.

https://docs.microsoft.com/en-us/rest/api/subscription/2021-10-01/alias/create

**Comment by jujinfu** [comment]
@veathipa thank you so much for the exciting news. We will try it out soon!

**Comment by jujinfu** [comment]
@veathipa 
adding more details here:

If I provision a subscription in a different tenant and set a user as owner, it will send an email to ask user to accept. 

If I provision a subscription in a different tenant, and set a service principal as owner, it still tries to send an email to accept. 
However, since this is a service principal, it wont get any email.
Digging more into this, found that accpetOwnershipUrl in the initial response.
Then we need to call that Url using Service Principal
related doc: https://docs.microsoft.com/en-us/rest/api/subscription/2021-10-01/subscription/accept-ownership?tabs=HTTP

I think we are good now and this working at lease. 
Would be nice to have this workflow documented somewhere. 

Thank you again!
