### ISSUE TITLE
[QUERY] EventGrid client publish retries

### ISSUE THREAD

**Issue by gjarzab** [Azure/azure-sdk-for-net#25747]
### Library name and version

Azure.Messaging.EventGrid

### Query/Question

Are there recommended approaches for retries when publishing custom events using the client?

**Comment by jsquire** [comment]
Hi @gjarzab.   Thank you for reaching out.  The Azure SDK clients have retry logic built-in and should take the appropriate retry actions for each operation.   Generally, we recommend using the default retry settings, but they can be adjusted if your application has a need to do so.   Information on configuring retries can be found in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#configuring-retry-options).   

To my knowledge, we don't have any special guidance for publishing custom events to Event Grid.  If you're running into specific difficulties where you believe that the built-in retries are not helping, please let us know and we'd be happy to assist.
