### ISSUE TITLE
[QUERY] How to get the number of retries we did for a request

### ISSUE THREAD

**Issue by gabidabet** [Azure/azure-sdk-for-net#25745]
### Library name and version

Azure.storage.blobs 12.8.0

### Query/Question

We want to monitor the number of retries for each request we did for some operations. In v11 we achived that by using operationContext object and saving the value retry count as a custom header and each retry we increment this value.

How to achieve the same thing in the new v12?

What I tried to do is to add a policy that add custom header in the request, but I don't receive back the header in the response.

### Environment

.net 3.1
Windows 10
visual studio 2019

**Comment by SaurabhSharma-MSFT** [comment]
@gabidabet We are looking into it and get back to you.

**Comment by gabidabet** [comment]
@SaurabhSharma-MSFT thank you.

**Comment by MughundhanRaveendran-MSFT** [comment]
@gabidabet , [OperationContext](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.operationcontext?view=azure-dotnet) Class was a part of Microsoft.Azure.Storage.Common library and this package got deprecated after V [11.2.3](https://www.nuget.org/packages/Microsoft.Azure.Storage.Common/). 

I am trying to see if there is a property/method available in the SDK that would provide the retry count. I will let you know once I have an update

**Comment by gabidabet** [comment]
@MughundhanRaveendran-MSFT  Hello thank you for your response, Yes I did tried this, but what happened is I don't know if that event is for the current request or of for another request. In other words, I try to pop a message for example, I start listening for retries how I know that the fired event is for the pop message operation.

**Comment by MughundhanRaveendran-MSFT** [comment]
@gabidabet , I am trying to see if this is possible, I will get back to you once I have an update

**Comment by MughundhanRaveendran-MSFT** [comment]
@gabidabet , 

Unfortunately, the storage service does not return back custom request headers as part of the response.

I have engaged the service team to look into this issue. In the meantime, if you would like to implement a custom retry policy, please  try the below approach :

Client side timeout
 
        public BlobClientOptions GetOptions(bool parallelRange = false)
        {
            var options = new BlobClientOptions(_serviceVersion)
            {
                Diagnostics = { IsLoggingEnabled = true },
                Retry =
                {
                    Mode = RetryMode.Exponential,
                    MaxRetries = Storage.Constants.MaxReliabilityRetries,
                    Delay = TimeSpan.FromSeconds(5),
                    MaxDelay = TimeSpan.FromSeconds(10)
                },
                Transport = GetTransport()
            };
            if (Mode != RecordedTestMode.Live)
            {
                options.AddPolicy(new RecordedClientRequestIdPolicy(Recording, parallelRange), HttpPipelinePosition.PerCall);
            }
 
            return Recording.InstrumentClientOptions(options);
        }

**Comment by MughundhanRaveendran-MSFT** [comment]
@gabidabet , following up to check if the above answer was helpful or not, please let me know

**Comment by MughundhanRaveendran-MSFT** [comment]
@gabidabet , I havent got a response from you yet. I will close this issue. Feel free to reopen if required

**Comment by gabidabet** [comment]
@MughundhanRaveendran-MSFT thank you for time and your solution. I will share the solution that we found, what we did is to add a policy that custum header to the AzureRequest that contains the retry number for that message, that policy will run for every retry, and we update the value of that header every time. Thank you again for great support and help.
