### ISSUE TITLE
[BUG] Unable to send to service bus when registering the client with  AddAzureClients and using managed identity.

### ISSUE THREAD

**Issue by kedzior-io** [Azure/azure-sdk-for-net#25743]
### Library name and version

Azure.Messaging.ServiceBus 7.5.0

### Describe the bug

Unable to send to service bus when registering the client with  `AddAzureClients` and using managed identity.

### Expected behavior

This should send the message:

```csharp
 var sender = _client.CreateSender("test");  // ServiceBusClient instance
 await sender.SendMessageAsync(new ServiceBusMessage("test"), cancellationToken: default);

```

### Actual behavior

What actually happens is this:

> ArgumentException: The connection string used for an Service Bus client must specify the Service Bus namespace host and either a Shared Access Key (both the name and value) OR a Shared Access Signature to be valid. (Parameter 'connectionString')
Azure.Messaging.ServiceBus.ServiceBusConnection.ValidateConnectionStringProperties(ServiceBusConnectionStringProperties connectionStringProperties, string connectionStringArgumentName)
Azure.Messaging.ServiceBus.ServiceBusConnection..ctor(string connectionString, ServiceBusClientOptions options)
Azure.Messaging.ServiceBus.ServiceBusClient..ctor(string connectionString, ServiceBusClientOptions options)
Microsoft.Extensions.Azure.ServiceBusClientBuilderExtensions+<>c__DisplayClass0_0<TBuilder>.<AddServiceBusClient>b__0(ServiceBusClientOptions options)
Microsoft.Extensions.Azure.AzureClientFactoryBuilder+<>c__DisplayClass3_0<TClient, TOptions>.<Azure.Core.Extensions.IAzureClientFactoryBuilder.RegisterClientFactory>b__0(TOptions options, TokenCredential _)
Microsoft.Extensions.Azure.AzureClientFactoryBuilder+<>c__DisplayClass8_0<TClient, TOptions>.<Azure.Core.Extensions.IAzureClientFactoryBuilderWithCredential.RegisterClientFactory>b__0(TOptions options, TokenCredential credential, IServiceProvider _)
Microsoft.Extensions.Azure.AzureClientFactoryBuilder+<>c__DisplayClass15_0<TClient, TOptions>.<RegisterClientFactory>b__0(IServiceProvider provider, object options, TokenCredential credential)
Microsoft.Extensions.Azure.ClientRegistration<TClient>.GetClient(IServiceProvider serviceProvider, object options, TokenCredential tokenCredential)
Microsoft.Extensions.Azure.AzureClientFactory<TClient, TOptions>.CreateClient(string name)
Microsoft.Extensions.Azure.AzureClientFactoryBuilder+<>c__15<TClient, TOptions>.<RegisterClientFactory>b__15_1(IServiceProvider provider)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor<TArgument, TResult>.VisitCallSite(ServiceCallSite callSite, TArgument argument)
Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine+<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)
lambda_method5(Closure , IServiceProvider , object[] )
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DefaultPageModelActivatorProvider+<>c__DisplayClass1_0.<CreateActivator>b__0(PageContext context)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.DefaultPageModelFactoryProvider+<>c__DisplayClass3_0.<CreateModelFactory>b__0(PageContext pageContext)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.CreateInstance()
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

### Reproduction Steps

1. Register service bus client in asp.net core project and host it on Azure App Service. 

```csharp
  public void ConfigureServices(IServiceCollection services)
  {
      services.AddAzureClients(clients => clients.AddServiceBusClient("Endpoint=sb://myservice.servicebus.windows.net/;Authentication=ManagedIdentity"));

   // this is the workaround that works: 
   // services.AddSingleton(_ => new ServiceBusClient("myservice.servicebus.windows.net", new DefaultAzureCredential()));   
  }
```

2. Create simple index page and inject `ServiceBusClient`

```csharp
public class IndexModel : PageModel
{
    private ServiceBusClient _client;

    public IndexModel(ServiceBusClient client)
    {
        _client = client;
    }

    public async Task OnGet()
    {
        var sender = _client.CreateSender("test");

        await sender.SendMessageAsync(new ServiceBusMessage("test"), cancellationToken: default);
    }
}
```

3. Assign role `Azure Service Bus Data Sender` to Azure App Service. 

You can view an example here: https://app-service-service-bus-managed-identity.azurewebsites.net/

**Comment by jsquire** [comment]
Hi @kedzior-io.  Thank you for reaching out and we regret that you're experiencing difficulties.  The connection string that you're attempting to use is not valid.   For connection strings, the Service Bus client understands only those elements that the Azure portal provides.   The `Authentication=ManagedIdentity` slug that you've added is not recognized and is ignored.  Since there is no shared key information specified, the request fails authorization.

In order to register a Service Bus client to use an Azure.Identity credential, you'll need to add the credential to the builder when adding the azure clients and then add the Service Bus client using the fully qualified namespace rather than a connection string.   For example:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddAzureClients(builder =>
    {
        builder.AddCredential(new ManagedIdentityCredential();
        builder.AddServiceBusClientWithNamespace("<< SERVICE BUS NAMESPACE (like: your-name.servicebus.windows.net) >>");
    }
}
```

More context around the options for registering Azure SDK clients can be found in the `Microsoft.Extensions.Azure` [README](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/extensions/Microsoft.Extensions.Azure#register-clients) and its associated [sample](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/extensions/Microsoft.Extensions.Azure/samples).

**Comment by kedzior-io** [comment]
@jsquire thanks for the prompt reply. 
Haha I thought I could use this connection string. 

Your example does the job with slight change to the credentials setting method!

```
services.AddAzureClients(builder =>
{
    builder.UseCredential(new ManagedIdentityCredential());
    builder.AddServiceBusClientWithNamespace("whatever.servicebus.windows.net");
});
```

Thank you!

**Comment by cristian-eriomenco** [comment]
@jsquire What is the approach for azure functions? Is there a host.json way of telling it to use the namespace approach instead of connection string?
