### ISSUE TITLE
Failed to create EventGrid subscriptions due to Long running operation failed with status 'Failed'

### ISSUE THREAD

**Issue by fscavo** [Azure/azure-sdk-for-net#25744]
This is happening with the Microsoft.Azure.Management.EventGrid 6.1.0-preview and 6.2.0-preview. It used to work before but all of the sudden it stopped.

>Failed to create EventGrid subscriptions due to Long running operation failed with status 'Failed'.
Additional Info:'The operation failed due to an internal server error.
The initial state of the impacted resources (if any) are restored. Please try again in few minutes.
If error still persists, report fe03a690-7887-47b2-994a-15a349f0bc42:12/7/2021 2:34:25 PM (UTC) to our forums for assistance or raise a support ticket .'

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by liurunliang** [comment]
Hi @fscavo ,I am not able to reproduce this issue. It might be a temporary service issue and already recovered. Please provide more information if this issue still affects you.
