### ISSUE TITLE
[FEATURE REQ] Show samples of integrating EventHubs and SchemaRegistry

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-net#25756]
### Library name

Azure.Data.SchemaRegistry 1.0.0

### Please describe the feature.

Event Hubs integration is mentioned several times in the samples but there's no samples that show how to use the two in conjunction. I think it would be great to have samples that show how to do that integration if we continue to mention it frequently in the README.

**Comment by JoshLove-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/28403
