### ISSUE TITLE
[FEATURE REQ] Show imports in samples

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-net#25754]
### Library name

Azure.Data.SchemaRegistry 1.0.0

### Please describe the feature.

I think it would be helpful to show the necessary imports as well. It took me a moment to figure out where Response was imported from. I ended up going to the `api` directory which I don't think is what we want customers to do. It's possible I don't have Visual Studio properly configured to do auto-imports (I've never used it and am an extreme novice in .NET).

**Comment by JoshLove-msft** [comment]
We don't usually show imports in samples.
