### ISSUE TITLE
[FEATURE REQ] add links for storage account, key vault, cosmos in monitor query readme

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-net#25750]
### Library name

Azure.Monitor.Query

### Please describe the feature.

It would be great to add links to Storage Account, Key Vault, and Cosmos in the [Prerequisites section of the Azure.Monitor.Query readme](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.Query#prerequisites)

**Comment by scottaddie** [comment]
Closing this issue as something that won't be fixed. I believe that turning these into links will distract from the focus of the doc. I don't want to give customers the impression that these services have first-class support in the Monitor Query library. The service names are merely intended to be examples.
