### ISSUE TITLE
[FEATURE REQ] Add details to `groupName` parameter in samples

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-for-net#25753]
### Library name

Azure.Data.SchemaRegistry 1.0.0

### Please describe the feature.

The samples use a `groupName` parameter but never define one. The only way I could find to create a new group was to do so in the portal. If that's the case we should show customers how to do that. This prevents the sample from being a copy-paste sample.

**Comment by pallavit** [comment]
@m-redding , @JoshLove-msft do you think this is still valid? If so, is this something you woudl want to consider for MQ?
