### ISSUE TITLE
Cannot Use Form Recognizer Quickstart

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-for-net#25758]
I could not get this to build and run at all. It seems like the body was ripped out of tests and that these were not run as written.

I was trying to follow this: https://docs.microsoft.com/en-us/azure/applied-ai-services/form-recognizer/quickstarts/try-v3-csharp-sdk

I am using 4.0.0-beta.2 instead of beta.1 because beta.1 was not available to me on NuGet. Otherwise, I have tried to match the quickstart verbatim.

- In `Build your application` step 3, it is unclear where these lines should be inserted. Later on it seems like they are inserted in the `Program` class but not in `Main`. When I put them here, I get the follow errors:
```
1>F:\repos\formRecognizer_quickstart\formRecognizer_quickstart\Program.cs(13,64,13,70): error CS0236: A field initializer cannot reference the non-static field, method, or property 'Program.apiKey'
1>F:\repos\formRecognizer_quickstart\formRecognizer_quickstart\Program.cs(14,76,14,84): error CS0236: A field initializer cannot reference the non-static field, method, or property 'Program.endpoint'
1>F:\repos\formRecognizer_quickstart\formRecognizer_quickstart\Program.cs(14,87,14,97): error CS0236: A field initializer cannot reference the non-static field, method, or property 'Program.credential'
1>F:\repos\formRecognizer_quickstart\formRecognizer_quickstart\Program.cs(21,56,21,62): error CS0120: An object reference is required for the non-static field, method, or property 'Program.client'
```
I made them all static to fix the build errors.

- When I copy the "Try It" code for any of the three samples, I get numerous build errors:
```
1>F:\repos\formRecognizer_quickstart\formRecognizer_quickstart\Program.cs(21,117,21,124): error CS1503: Argument 2: cannot convert from 'string' to 'System.Uri'
1>F:\repos\formRecognizer_quickstart\formRecognizer_quickstart\Program.cs(21,50,21,125): error CS4033: The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'.
1>F:\repos\formRecognizer_quickstart\formRecognizer_quickstart\Program.cs(23,13,23,53): error CS4033: The 'await' operator can only be used within an async method. Consider marking this method with the 'async' modifier and changing its return type to 'Task'.
```
I tried making Main static so as to fix the build error, but then I get `Program does not contain a static 'Main' method suitable for an entry point`. 

- The "Prebuilt Model" Try It requires `using System.IO;` and `using System.Collections.Generic;` statements.

**Comment by jsquire** [comment]
Hi @tjprescott.   Quickstart content is owned by the MS Docs team and tracked via the MS Docs repo.   We'll want to move this over, but don't have access to transfer issues directly.   Would you please be so kind as to report your feedback via the "Feedback" section in the article so that it gets routed to the right folks?

**Comment by tjprescott** [comment]
https://github.com/MicrosoftDocs/azure-docs/issues/84935

I posted the issue here because this is where the bug bash email requested we post issues.

**Comment by jsquire** [comment]
Unfortunately, it's not actionable for us.   Since you were kind enough to transfer, I'm going to close this out.
