### ISSUE TITLE
[BUG] broken link on Azure storage hub doc page

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#25755]
### Library name and version

Azure.Storage

### Describe the bug

There is a broken link on https://docs.microsoft.com/en-us/azure/storage/

### Expected behavior

link works

### Actual behavior

404 returned. 

### Reproduction Steps

Go to https://docs.microsoft.com/en-us/azure/storage/
cLick on "Review options for storage in Azure"

**Comment by SaurabhSharma-MSFT** [comment]
@KrzysztofCwalina Can you please check now and let us know if you are able to access the link.  I am able to access the link.

**Comment by SaurabhSharma-MSFT** [comment]
@KrzysztofCwalina We are still waiting for your response.  Please let us know if you are still facing error accessing the link.

**Comment by SaurabhSharma-MSFT** [comment]
@KrzysztofCwalina We are closing this issue as we have not heard back.
