### ISSUE TITLE
[FEATURE REQ] add docs for necessary using statements in readme examples

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-net#25763]
### Library name

Azure.Monitor.Query

### Please describe the feature.

Not sure if this is a .NET decision or not, but it'd be great to mention somewhere the necessary using statments you need to execute the readme examples. Had to figure out myself that I needed `using Azure` and `using Azure.Monitor.Query.Models` to get the readme examples to work

**Comment by scottaddie** [comment]
This is a problem for all .NET client libraries. Issue https://github.com/Azure/azure-sdk-tools/issues/2438 will be used to track this feature request.
