### ISSUE TITLE
[DOC] File share error code page is very confusing

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-net#25771]
### Library name and version

https://docs.microsoft.com/en-us/rest/api/storageservices/file-service-error-codes

### Describe the bug

The page is confusing.

1. Looks like the column "Error code" should be "error type"?
2. Shouldn't "HTTP status code" be code only? e.g. only 409 rather than "Conflict (409)"?
3. ClientCacheFlushDelay | Internal Server Error (500) | The specified resource state could not be flushed from an SMB client in the specified time. 
    Why timeout causes 500?
4. InvalidFileOrDirectoryPathName | Bad Request (400) | File or directory path is too long.
    InvalidFileOrDirectoryPathName | Bad Request (400) | File or directory path has too many subdirectories. 
    Same type, different meaning?

### Expected behavior

As described.

### Actual behavior

As described.

### Reproduction Steps

Doc

**Comment by jsquire** [comment]
@xiangyan99:  The page that you've listed is for the REST API and isn't part of this repository.   We'll need to transfer to the MS Docs repo where this is maintained, but don't have permissions to open issues directly.   Would you be so kind as to use the "Feedback" section at the bottom of the docs page to report this?

**Comment by xiangyan99** [comment]
Btw, is this information from our SDK?

**Comment by jsquire** [comment]
That URL indicates that it's for the REST API and sourced from the MS Docs content.

**Comment by xiangyan99** [comment]
Get it. Thank you.

**Comment by jsquire** [comment]
Cool.   I'm going to close this out, as it's not actionable here.
