### ISSUE TITLE
Incorrect link in Azure Monitor Exporter client docs

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-net#25776]
**Link**

Under the "Prerequisites" section. the "create an account" link just redirects to the main Azure site. I don't think account.windowsazure.com is the right place to direct them to.

> or use your Visual Studio Subscription benefits when you create an account.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a6828ef-23c6-0120-1e77-33b44a19d3e2
* Version Independent ID: 94f66766-aa08-4657-9e46-f1859ac5dbb5
* Content: [Azure Monitor Exporter client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/monitor.opentelemetry.exporter-readme-pre)
* Content Source: [api/overview/azure/monitor.opentelemetry.exporter-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/monitor.opentelemetry.exporter-readme-pre.md)
* Service: **monitor**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by vishweshbankwar** [comment]
fixed in #34592
