### ISSUE TITLE
[Bug Bash] Create a README for the upper `/keyvault` folder.

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-net#25786]
### Library name and version

`Azure.Security.KeyVault`

### Describe the bug

The `/keyvault` folder does not have a general README detailing what packages are available and a brief description for them. This is important because the GitHub link from the [Microsoft Docs Key Vault page for .NET](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/key-vault) sends users to this folder and it's the first approach the might have with the library.

### Expected behavior

[`/keyvault`](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/keyvault) should have a general README just like the folders for [`/storage`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/README.md) in .NET or [`/keyvault`](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/keyvault/README.md) in Java do.

### Actual behavior

The aforementioned README does not exist.

### Reproduction Steps

N/A

**Comment by heaths** [comment]
I can mostly copy the Java README, but note that "Key Vault Keys" vs. "Key Vault Secrets" vs etc., are not distinct "cloud services" as mentioned. I can work on something more universal we can use across languages.

That said, are we doing badges in READMEs now? I was surprised to see them in Java's `sdk/keyvault/README.md`.

**Comment by vcolin7** [comment]
> That said, are we doing badges in READMEs now? I was surprised to see them in Java's sdk/keyvault/README.md.

I think those had been there for a good while by the time I worked on the bug bash. I do recall fixing a couple of them because they had the wrong links to feed from. If we're not keeping those around anymore I could also remove them from the Java README.
