### ISSUE TITLE
[FEATURE REQ] Add section to SB Migration Guide on how to move from ITokenProvider to AzureSasCredential when using SAS tokens

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-net#25787]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

The migration guide for moving from the older Microsoft.Azure.ServiceBus to Azure.Messaging.ServiceBus needs a section on how to use AzureSasCredential. See prior discussion in https://github.com/Azure/azure-sdk-for-net/issues/19283.

We may also consider adding a sample as well

**Comment by JoshLove-msft** [comment]
We now have a sample showing how to use AzureSasCredential.
