### ISSUE TITLE
[Bug Bash] README example is confusing

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-for-net#25784]
In this code snippet:
```
var inputs = new List<DocumentTranslationInput>
{
    new DocumentTranslationInput(source1SasUri, spanishTargetSasUri, "es"),
    new DocumentTranslationInput(
        source: new TranslationSource(source2SasUri),
        targets: new List<TranslationTarget>
        {
            new TranslationTarget(frenchTargetSasUri, "fr"),
            new TranslationTarget(arabicTargetSasUri, "ar")
        }),
};
```
I'm not sure which method is better to declare the source and target SAS URIs (line 3 or what's shown in lines 5-9)? What is the difference between simply passing in the SAS URIs or passing in the TranslationTarget/TranslationSource? 
I think the README could focus on the desired method for declaring the source and target. (I understand if showcasing both methods is a languages convention, then please disregard)

**Comment by pallavit** [comment]
It is a language convention to show both options.
