### ISSUE TITLE
[Bug Bash] Issues with the Key Vault Administration README.

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-net#25790]
### Library name and version

`Azure.Security.KeyVault.Administration`

### Describe the bug

There are multiple small things that need to be corrected in the README for the Key Vault Administration client library.

### Expected behavior

1. In [line 26](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L26) there's a link that points to the `KeyVaultAccessControlClient`'s source code. I'm thinking this should probably point be changed to point to [an example](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md#create-keyvaultaccesscontrolclient) of creating an instance of said client. I don't think customers would be all that interested in looking at the class's source code.
2. In [line 63](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L63) we should add the word "the" before mentioning the envrionmental variables that need to be updated by users:
    > \* Use the returned credentials above to set the **AZURE_CLIENT_ID** (appId), **AZURE_CLIENT_SECRET** (password), and **AZURE_TENANT_ID** (tenant).
3. In [line 71](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L71) and [line 78](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L78), the words "above mentioned" should be hyphenated as follows: "above-mentioned".
4. In [line 72](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L72), the order of `<your-resource-group-name>` and `<your-managed-hsm-name>` should be swapped to match the order in the code sample a couple lines down.
5. In [line 78](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L78), the word "Vault" should be all lowercase, as it refers to a single vault and not the Key Vault service.
6. [Line 88](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L88) should read "A minimum of 3 RSA key-pairs (maximum 10)" instead of "Minimum 3 RSA key-pairs (maximum 10)".
7. [Line 89](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L89) should begin with "To specify the minimum number of keys..." instead of "Specify minimum number of keys...".
8. In [line 95](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L95), the word "certificate" should be changed to "certificates".
9. [Line 104](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L104) does not need a comma after "The example below".
10. [Line 122](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L122) and [line 129](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L129) should include an "a" before naming the client to create, as in: "Create **a** KeyVaultAccessControlClient."
11. [Line 123](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L123) should probably include a full sample of CLI code used to get a the `managedHsmUrl`, for example `az keyvault show --hsm-name <your-managed-hsm-name>`, as it simply mentions `az keyvault show` and users tend to skip sections of documentation and simply copy and paste.
12. [Line 130](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L130) should contain "managedHsmUrl" instead of "your-hsm-url" to match the code sample below. Additionally, the contents of section ["Create KeyVaultBackupClient"](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md#create-keyvaultbackupclient) should be worded just like section ["Create KeyVaultAccessControlClient"](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md#create-keyvaultaccesscontrolclient) just in case.
13. The ["Examples"](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md#examples) section should include sync and async code samples for the following:
    - Creating a Role Definition
    - Getting a Role Definition
    - Deleting a Role Definition

    Created [a separate issue](https://github.com/Azure/azure-sdk-for-net/issues/25791) for this.
14. [Line 206](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L206) should use "Administration" instead of "administration".
15. In [line 237](https://github.com/Azure/azure-sdk-for-net/blob/eed2d1d7a3beee21d58cac3b63d4c91d330ad799/sdk/keyvault/Azure.Security.KeyVault.Administration/README.md?plain=1#L237), the word "the" should be added before "AzureEventSourceListener.CreateConsoleLogger", as follows: "use **the** AzureEventSourceListener.CreateConsoleLogger method.".

### Actual behavior

N/A

### Reproduction Steps

N/A

**Comment by heaths** [comment]
Regarding 13, we don't include all samples in the README. READMEs should just be hero samples - the common types. I thought that was the same for all languages. We have separate samples for more detailed, less-common samples. We also don't normally highlight async samples, especially in the package README.
