### ISSUE TITLE
[BUG] 'SDK Automation' step failing due to missing .NET 6 SDK

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#25819]
### Library name and version

EngSys

### Describe the bug

'SDK Automation' step failing due to missing .NET 6 SDK
    

We are seeing the '.NET 6 SDK install missing' issue in a PR in the azure-reset-api-specs repo.

Example PR - https://github.com/Azure/azure-rest-api-specs/pull/16910/checks?check_run_id=4451288492
Build log - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1235643&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437

It is during the step where it triggers code gen on the azure-sdk-for-net repo.

### Expected behavior

All steps in the PR build pass

### Actual behavior

'SDK Automation' step fails

### Reproduction Steps

I provided link to a PR build failure

**Comment by weshaggard** [comment]
@ShivangiReja wrote this automation originally but I'm not sure if she is still the owner for it.
