### ISSUE TITLE
Publish metrics for test results trx file data

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-for-net#25814]
It would be useful to have more fine grained test result tracking (especially per project test success/fail). Right now the lowest level of granularity is a pipeline pass/fail rate. For the core ci pipeline, this makes it harder to drill down on per-project pass/fail rates.

We can introduce a post-test step that parses the published trx file and [emits logs/metrics for processing](https://github.com/azure/azure-sdk-tools/blob/main/eng/common/scripts/Write-FileSystemMetrics.ps1#L30). Once this data becomes available, we can start to analyze it via KQL queries and dashboards. We can also go through old builds and process the trx artifacts to populate historical data.

The larger goal here is to help tackle the broad problem of flaky and failing tests that are ignored or not easily tracked. In order to do this, we need better measurement data.

FYI @pakrym @hallipr

**Comment by christothes** [comment]
This would be helpful to measure individual test execution durations as well.

**Comment by kurtzeborn** [comment]
One concern raised is that that might significantly increase the amount of data we're storing and therefore the cost.  That's worth understanding before we just do this one.
