### ISSUE TITLE
azure functions event grid out binding not working with typescript [BUG]

### ISSUE THREAD

**Issue by smafre** [Azure/azure-sdk-for-net#25810]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventGrid 3.0.0

### Describe the bug

I have a simple typescript azure function with an eventGrid out binding. When the function finishes I want an array of events to be sent using event grid. This works fine with the extension bundle version 2.x, but when I upgrade to version 3.x I run into issues. Version 3.x of the extensions bundle has an updated version of Microsoft.Azure.WebJobs.Extensions.EventGrid compared to version 2.x.

### Expected behavior

I expect the function to finish and send my events using event grid. This works fine with the extension bundle version 2.x.

### Actual behavior

The error I get is this:
`System.Private.CoreLib: Exception while executing function: Microsoft.Azure.WebJobs.Host: Error while handling parameter _binder after function returned:. Microsoft.Azure.WebJobs.Extensions.EventGrid: System.Byte[] is not a valid event type.`

### Reproduction Steps

Make a simple azure function using typescript, node 14 and azure functions runtime version 4.  Use the extension bundle version 3.x (latest). Add an event grid out binding and try to add some event objects to the context to send them when the function finishes.

### Environment

Testing locally:
Core Tools Version: 4.0.3971.
Function Runtime Version: 4.0.1.16815.
Node: Version 14 og 16, I get the error using both.
ExtensionBundle version: [3.3.0, 4.0.0)

**Comment by JoshLove-msft** [comment]
Hi @smafre,
Thank you for raising this issue. We will get it fixed.
