### ISSUE TITLE
[BUG]Higher dependency in SDK than PowerShell 

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#25827]
### Library name and version

Microsoft.Azure.Messaging.EventGrid.CloudNativeCloudEvents

### Describe the bug

`Microsoft.Azure.Messaging.EventGrid.CloudNativeCloudEvents` pulls in `System.Text.Encodings.Web : 5.0.*`, `System.Text.Json : 5.0.*` and `System.Runtime.CompilerServices.Unsafe : 5.0.*` as a transitive dependencies which is higher than the version in PowerShell (4.0.*)
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1237993&view=logs&j=d41e9505-d81b-5b3c-5b50-be71bc9b0ccb&t=1d797300-f2df-5c9f-af88-b93a037bfad7

Graph
`Microsoft.Azure.Messaging.EventGrid.CloudNativeCloudEvents` → `CloudNative.CloudEvents.SystemTextJson : 2.0.0` → `System.Text.Encodings.Web : 5.0.2` 

`Microsoft.Azure.Messaging.EventGrid.CloudNativeCloudEvents` → `CloudNative.CloudEvents : 2.0.0` → `System.Memory : 5.0.*` → `System.Runtime.CompilerServices.Unsafe : 5.0.*`

### Expected behavior

SDKs should not have dependencies higher than those in powershell.

### Actual behavior

`Microsoft.Azure.Messaging.EventGrid.CloudNativeCloudEvents` pull in a dependency with version higher than present in powershell.

### Reproduction Steps

Run `net - agregate-report` pipeline after removing `Microsoft.Azure.Messaging.EventGrid.CloudNativeCloudEvents` from the ignoreList in `https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/dependencies/generate-deps.ps1`

**Comment by jsquire** [comment]
Closing; this package reached end-of-life and is no longer supported.   Nor is PowerShell v4.
