### ISSUE TITLE
Consider relaxing AddEntityAsync generic constraint

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#25820]
There seems no functional reason to have `T` be `class` but especially not `new()`.

cc @christothes

**Comment by christothes** [comment]
This is why we have the constraint:

https://github.com/Azure/azure-sdk-for-net/blob/18eff249806439372a587fae1a87adfe860cdaa6/sdk/tables/Azure.Data.Tables/src/Extensions/DictionaryTableExtensions.cs#L135-L139

**Comment by pakrym** [comment]
That's for deserialization. We don't need it for serialization.
