### ISSUE TITLE
How can I mock BlobServiceClient for unit tests when using dependency injection?

### ISSUE THREAD

**Issue by svdHero** [Azure/azure-sdk-for-net#25836]
The documentation shows the default constructor `BlobServiceClient()` with the description "Initializes a new instance of the BlobServiceClient class for mocking."

How can I mock a `BlobServiceClient` for unit testing? More precisely, I am using [dependency injection](https://docs.microsoft.com/en-us/dotnet/azure/sdk/dependency-injection) and would like to provide fake blob streams (e.g. from `MemoryStream`) and fake `BlobProperties` for my unit tests.

Please add some documentation how to do that.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f20d364d-3f29-5a7f-93d6-02dcc6c165de
* Version Independent ID: 443cc5a8-17de-8b14-8e7a-37c184ea09af
* Content: [BlobServiceClient Constructor (Azure.Storage.Blobs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.-ctor?view=azure-dotnet#Azure_Storage_Blobs_BlobServiceClient__ctor)
* Content Source: [xml/Azure.Storage.Blobs/BlobServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs/BlobServiceClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by seanmcc-msft** [comment]
Hi @svdHero,

Here are some previous GitHub issues with examples of how to mock our clients:
- https://github.com/Azure/azure-sdk-for-net/issues/14905
- https://github.com/Azure/azure-sdk-for-net/issues/21473
- https://github.com/Azure/azure-sdk-for-net/issues/9283

You can mock the `BlobServiceClient` using the same patterns.

-Sean

**Comment by svdHero** [comment]
@seanmcc-msft Thank you so much for the provided links. That helped a lot.

Maybe it would be beneficial to add a subpage to the official documentation about mocking?

**Comment by seanmcc-msft** [comment]
Hi @svdHero, that's a good idea.  I've created https://github.com/Azure/azure-sdk-for-net/issues/25987 to track.

Please re-open if you have further questions.
