### ISSUE TITLE
[BUG] Something is causing Port Exhaustion on an hourly basis (on Linux ASP)

### ISSUE THREAD

**Issue by jenspettersson** [Azure/azure-sdk-for-net#25833]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.3.0

### Describe the bug

_First, we're not sure this is caused by the ServiceBus package entered above in "Library name and version", but we're suspecting it. It might be something else..._

We're seeing spikes of "New SNAT connections established" every hour on Linux App Service Plan P1v2: 1. We first saw it on our service plan where our real system is running and immediately began looking for things in our code that might cause this (no reuse of `HttpClient` etc). We found nothing.

Then I created a brand new Azure Function App, hosted on a brand new App Service Plan P1v2 (nothing else on that ASP). The function app has:
1. One ServiceBusTrigger that consumes messages from a queue and write to the standard log output
2. One TimerTrigger that produces a message on the queue every five minutes
3. A HttpTrigger that produces a message on the queue when invoked

I deployed this yesterday evening and left it alone over night:
![image](https://user-images.githubusercontent.com/125493/145346533-8208ef50-9beb-4203-88e4-e0ddb8e513a0.png)

The reports shows that new SNAT Connections has been established every hour, and sometimes there are so many new connections that they cause port exhaustions and results in failing connections.

![image](https://user-images.githubusercontent.com/125493/145346972-a2e0f6d6-3c51-4b82-a0e7-b429ac078d4d.png)
On this image you can see a huge spike at 01:20 and then new, albeit a bit smaller, spikes at 02:20, 03:20, 04:20 and 05:20.

This is the exact same behavior we're seeing on our real system. Even with little to no load at all (we're not yet in production) we keep seeing the errors for Port Exhaustion in the diagnostics tool. We're not quite sure if this is actually impacting the performance of our system but as we've been fixing port exhaustion issues in other systems last year (these were caused by `HttpClient` being used in an incorrect way) we're always on our toes when we see these kind of error reports.

### Expected behavior

Not seeing any Port Exhaustion errors in an app with no load at all and almost no code at all.

### Actual behavior

Port Exhaustions on an almost hourly basis on an Azure Function App doing almost nothing at all.

### Reproduction Steps

Create an Azure Service Bus Namespace

Create a queue called `snat` on that namespace

Create a new App Service Plan: **Linux P1v2**

Create a new Azure Function App

Create the following Functions:

```csharp
[FunctionName("QueueMessageProducer")]
public static async Task RunAsync(
    [TimerTrigger("0 */5 * * * *")] TimerInfo myTimer,
    [ServiceBus("snat", Connection = "AzureServiceBus")] IAsyncCollector<string> messages,
    ILogger log)
{
    var now = DateTime.UtcNow;
    log.LogInformation($"C# Timer trigger function executed at: {now}");

    await messages.AddAsync($"Message from QueueMessageProducer {now}");
}
```
```csharp
[FunctionName("QueueTrigger")]
public static Task RunAsync([ServiceBusTrigger("snat", Connection = "AzureServiceBus")] string myQueueItem, ILogger log)
{
    log.LogInformation($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
    
    return Task.CompletedTask;
}
```
Deploy it and let it run and then look at the reports in **Troubleshoot** under **Diagnose and solve problems**. It's quite a long delay on the SNAT reports so you might have to let it run for a while...

### Environment

Hosting: Azure Function App (running on App Service Plan  **Linux P1v2**)
Azure Function runtime: **dotnet**
Azure Function version: **v3**
Target Framework: **netcoreapp3.1**

The following package references were used:
```
<PackageReference Include="Microsoft.Azure.WebJobs" Version="3.0.29" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Http" Version="3.0.12" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.3.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.4" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
```

**Comment by jenspettersson** [comment]
![image](https://user-images.githubusercontent.com/125493/145392429-af172106-c088-49ef-bed4-8f2b3ef4f34e.png)

Just an update of the Azure Function App "New SNAT Connection Established". Spikes every hour, and now they're increasing. Still same "load" on the app (one message, every 5 minutes, nothing else).

**Comment by jsquire** [comment]
Hi @jenspettersson.   Thank you for reaching out and we regret that you're experiencing difficulties.   I notice that you're using an older version of the Service Bus extensions which bind to a legacy version of the Service Bus client library.   You may want to consider updating to v5.2.0 of the `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package and see if the behavior persists.

For now, I've transferred this issue to the repository where v4.3.0 of the  `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package is maintained as [#176](https://github.com/Azure/azure-functions-servicebus-extension/issues/176) so the folks best able to assist are made aware.   I'm going to mark this as addressed, but if you see the same behavior with v5.0+ of the extensions package, please "`/unresolve`" this issue and let us know.

**Comment by jsquire** [comment]
//fyi:  @JoshLove-msft, @shankarsama, @DorothySun216

**Comment by jenspettersson** [comment]
> ...if you see the same behavior with v5.0+ of the extensions package, please "`/unresolve`" this issue and let us know.

Just updated to: `<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.2.0" />` and also changed the target framework to `.net6.0` and the azure functions version to `v4` and after a couple of hours running we still see spikes. Will let it run over night again, but at first glance, it doesn't seem like it made any difference.

/unresolve

**Comment by jsquire** [comment]
Hi @jenspettersson.   Thank you for confirming.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
We've seen this issue before but never quite got to the bottom of it. As a workaround, it seems that using Windows App Service does not cause this issue.
https://github.com/Azure/azure-sdk-for-net/issues/24851

**Comment by JoshLove-msft** [comment]
Are you able to collect a memory dump?

**Comment by jenspettersson** [comment]
> @jenspettersson Are you able to collect a memory dump?

Never done it on a Linux App Service Plan with an Azure Functions App. Any pointers? The `dotnet` command is not available for me when SSH:ing

**Comment by jenspettersson** [comment]
FYI - The spikes of new (and also pending and failed) connections continued over night when running the latest packages:
![image](https://user-images.githubusercontent.com/125493/145529101-bc5bcdd1-a2ce-40a4-afa5-6fc05166a68e.png)

The application still only produces one message and consume that message every five minutes.

As this P1v2 App Service Plan costs us money and we're only using it to illustrate this problem, we are probably going to stop this app and remove the App Service Plan later today.

**Comment by jenspettersson** [comment]
Another FYI - We disabled all functions, but let the actual function app running: Still spikes.

![image](https://user-images.githubusercontent.com/125493/145573900-cc32ad98-8162-4a63-8b01-9a40253cde06.png)

Later today we're going to stop the Azure Function App but let the App Service Plan be for a couple of hours to see what happens... Maybe it's something in the Function Host that causes the connections? Connections to a storage account?

**Comment by JoshLove-msft** [comment]
That is very interesting. @karshinlin have you seen this kind of behavior before? Port exhaustion is occurring even when no functions are present.

**Comment by jenspettersson** [comment]
One final graph for today, this time we turned **off** the only app on this App Service Plan at around 15.00 UTC (earlier we only disabled the functions):

![image](https://user-images.githubusercontent.com/125493/145645165-11bd4435-4e5a-4f0c-825d-55558ed1bc1d.png)

This graph is the Port Usage, and we see that once an hour something is using more than half of all the ports that are allocated, even if there is no running app on the App Service Plan. I'm certain that if we would have a "real" app running with connections to a database, service bus, some HttpClients etc, and some actual load we would probably see port exhaustions during these peaks.

We know that you can avoid outbound port usage if you use a VNET for your Azure resources but we still think this behavior is a bit strange.

**Comment by jenspettersson** [comment]
And when checking in this morning, the graphs were crazy... Here are the Failed & Pending connections from tonight:
![image](https://user-images.githubusercontent.com/125493/145668081-e1dceee9-2450-4eac-b3bd-dc5c8ba53c42.png)

And here are the SNAT Port Usage:
![image](https://user-images.githubusercontent.com/125493/145668095-c0302d84-71d2-41d5-8a99-58cc05c7c094.png)

And finally the New SNAT Conenctions established:
![image](https://user-images.githubusercontent.com/125493/145668109-d04b7d43-869a-4875-9a28-5c802bb06243.png)

Once again, this time a **STOPPED** Azure Function App on a dedicated App Service Plan - Linux P1v2. Curious on what's going on here...

**Comment by JoshLove-msft** [comment]
Thank you for the detailed analysis @jenspettersson. Since the issue does not appear related to the Service Bus extension, or even the Functions runtime, I think at this point our best bet would be for you to submit a support ticket so this can be examined by someone from the App services team. 

Would you be able to submit a ticket with this link - https://azure.microsoft.com/en-us/support/create-ticket/
