### ISSUE TITLE
[BUG] Create an EventHubs NameSpace Fails with LocationNeeded

### ISSUE THREAD

**Issue by robertitomaster** [Azure/azure-sdk-for-net#25843]
### Library name and version

Azure.ResourceManager.EventHubs 1.0.0-preview.1

### Describe the bug

When running the below code trying to create an Azure EventHub Namespace the option to add a location doesn't exist. It would be nice to add that so the requests don't fail for something that's required.

### Expected behavior

I would expect some class to provide the required constructs so that the call does not fail for something required.

### Actual behavior

I would expect the EventHubNameSpace to allow an Enum to pass the desired location. With the fillowing exception

Azure.RequestFailedException
  HResult=0x80131500
  Message=Service request failed.
Status: 400 (Bad Request)

Content:
{"error":{"code":"LocationRequired","message":"The location property is required for this definition."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-request-id: ebef1c88-8631-4620-9aa7-4b563c34ad4a
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Thu, 09 Dec 2021 16:26:49 GMT
Content-Length: 104
Content-Type: application/json; charset=utf-8
Expires: -1

  Source=Azure.ResourceManager.EventHubs
  StackTrace:
   at Azure.ResourceManager.EventHubs.NamespacesRestOperations.CreateOrUpdate(String resourceGroupName, String namespaceName, EHNamespace parameters, CancellationToken cancellationToken)
   at Azure.ResourceManager.EventHubs.NamespacesOperations.StartCreateOrUpdate(String resourceGroupName, String namespaceName, EHNamespace parameters, CancellationToken cancellationToken)
   at ModernEvventHubs.Program.Main(String[] args) in C:\Users\moral\source\repos\ModernEvventHubs\ModernEvventHubs\Program.cs:line 16

  This exception was originally thrown at this call stack:
    [External Code]
    ModernEvventHubs.Program.Main(string[]) in Program.cs

### Reproduction Steps

using Azure.ResourceManager.EventHubs;
using Azure.ResourceManager.EventHubs.Models;
using Azure.ResourceManager.Resources;
using Azure.ResourceManager.Resources.Models;
using System;
using System.Linq;

namespace ModernEvventHubs
{
    class Program
    {
        static void Main(string[] args)
        {
            //TestCreateRG();
            var eh = new EventHubsManagementClient("xxxxxxxSubscriptionIDxxxxxxxxxxxxxxx", new InteractiveBrowserCredential());
            var ehoptions = new EHNamespace();
            ehoptions.Sku = new Sku(SkuName.Standard);
            var result = eh.Namespaces.StartCreateOrUpdate("test-rg", "test-eventhubnamespace", ehoptions);
        }
    }
}

### Environment

.NET SDK (reflecting any global.json):
 Version:   5.0.403
 Commit:    bf9d168ac2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.403\

Host (useful for support):
  Version: 5.0.12
  Commit:  7211aa01b3

.NET SDKs installed:
  1.1.14 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.508 [C:\Program Files\dotnet\sdk]
  2.1.509 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.1.802 [C:\Program Files\dotnet\sdk]
  2.2.108 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]****

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by robertitomaster** [comment]
The  EHNamespace has a Location property that can be set and allows for resource creation. This bug can be closed
