### ISSUE TITLE
[BUG] Inconsistent performance issue in Azure storage

### ISSUE THREAD

**Issue by georgeli2010** [Azure/azure-sdk-for-net#25868]
### Library name and version

Azure.Storage.Blobs 12.8.0

### Describe the bug

Hi Team,

I have been facing inconsistent latency issue repeatedly in Azure blob storage. Mostly in the call with blob get properties or exist method. In the first request, which is taken 1.7 mins, it does not have server request ID generated, but for the second request, which is completed in 22.5 ms is having server request ID. 

I am not sure why some requests are taking more time, and its immediately retry by SDK is working in milliseconds. 

Version- Azure.Storage.Blobs" Version="12.8.0”
.NET Core 3.1

Any help would be greatly appreciated. 

![image](https://user-images.githubusercontent.com/8122769/145534000-490d209c-0d8f-4664-92d7-ae1a0c058152.png)

 

### Expected behavior

It is expected to complete in milliseconds

### Actual behavior

But it is taking 1.7 minutes to complete the request, and it is not reached the server and no server request ID in the Application insight logs.

### Reproduction Steps

`var blobContainerProperties = await cloudBlockBlob.GetPropertiesAsync().ConfigureAwait(false);`

### Environment

Hosting platform - Container optimized OS ubuntu 18.
.NET Core 3.1
Azure.Storage.Blobs 12.8.0

**Comment by SaurabhSharma-MSFT** [comment]
@georgeli2010 Did you check GerPropertiesAysnc on any other container or storage account and on any other hosting platform? 
Also, what's the size of your blob payload. What is the behavior you see when you debug from your local machine?  
Could you please try checking this [tech community blog](https://techcommunity.microsoft.com/t5/azure-paas-blog/how-to-isolate-latency-issue-for-azure-storage-account/ba-p/1430656) to identify the cause.

**Comment by georgelivingstonsync** [comment]
Thanks @SaurabhSharma-MSFT 

It does not occur to specific containers; it does occur randomly in many containers. The size of the blob is less than 30 KB. It does not occur locally. 

e.g. In the last 7 days, it has occurred 5 times, in a total request of 10K request. 

The server logs ($logs) in the storage does not have this request logged. So, the latency in the storage metrics doesn't reflect this. 

As per the Azure support team, it doesn't reach the Azure server.

**Comment by SaurabhSharma-MSFT** [comment]
@georgelivingstonsync Thanks for the information, I am involving other team members for further assistance.

**Comment by amishra-dev** [comment]
Hi @georgeli2010 George,
Typically this is an indication that something in the network (firewall/proxy) either dropped the packet. Can you enable the verbose logs in the SDK and see what took the time. Looking at verbose logs or fiddler trace (if possible) would give a good idea on what blocked the transfer. 
If you share the logs, please make sure you remove any credentials from it.

Thanks
Ashish

**Comment by SaurabhSharma-MSFT** [comment]
Hi @georgeli2010,
Did you check on the suggestions provided above and share the logs.
Thanks
Saurabh

**Comment by YuriyMS** [comment]
Hi @SaurabhSharma-MSFT and @amishra-dev 
We currently experience the same issue. Ticket "Re: Slow response from azure blob storage up to... - TrackingID#2201120010003223"
Any suggestion how to address it? 
![image](https://user-images.githubusercontent.com/97552677/149302437-04019ec8-fcc6-4d5b-a126-a89323b6e0ae.png)

YuriyPolishchuk-MSFT
Thanks.

**Comment by amishra-dev** [comment]
@YuriyMS i am assuming you got helped with the ticket. 
George, closing this as i have not heard back from you.

**Comment by polishchuk1980** [comment]
> Hi @SaurabhSharma-MSFT and @amishra-dev We currently experience the same issue. Ticket "Re: Slow response from azure blob storage up to... - TrackingID#2201120010003223" Any suggestion how to address it? ![image](https://user-images.githubusercontent.com/97552677/149302437-04019ec8-fcc6-4d5b-a126-a89323b6e0ae.png)
> 
> YuriyPolishchuk-MSFT Thanks.

After reviewing network communication between client side(our service) and azure blob storage, we were able to identify that it’s a client(our service) who abandon connection after 100 seconds(1.7 minutes). So we start looking why it may happen and find out that when many streams weren’t closed(disposed) properly, new streams can’t establish connection with azure blob storage service due to some buffer on client side.
Make sure that your code disposes any stream which were provided to you by Azure Storage SDK.

**Comment by YuriyMS** [comment]
> Hi @SaurabhSharma-MSFT and @amishra-dev We currently experience the same issue. Ticket "Re: Slow response from azure blob storage up to... - TrackingID#2201120010003223" Any suggestion how to address it? ![image](https://user-images.githubusercontent.com/97552677/149302437-04019ec8-fcc6-4d5b-a126-a89323b6e0ae.png)
> 
> YuriyPolishchuk-MSFT Thanks.

After reviewing network communication between client side(our service) and azure blob storage, we were able to identify that it’s a client(our service) who abandon connection after 100 seconds(1.7 minutes). So we start looking why it may happen and find out that when many streams weren’t closed(disposed) properly, new streams can’t establish connection with azure blob storage service due to some buffer on client side.
Make sure that your code disposes any stream which were provided to you by Azure Storage SDK.
