### ISSUE TITLE
[QUERY] Service bus telemetry seems excessive

### ISSUE THREAD

**Issue by jenp-jb** [Azure/azure-sdk-for-net#25865]
### Library name and version

Microsoft.Azure.WebJobs.Extension.ServiceBus 5.1.0

### Query/Question

Starting up an azure function that has service bus triggers seems to be generating an awful lot of telemetry - even filtering on EventId this is what I'm seeing when I spun up something locally:
![image](https://user-images.githubusercontent.com/77314668/145526889-c3ff14c2-bc07-4d12-883a-77da16c3c4f8.png)

We did upgrade from 4.3.x with no code change so I'm not sure if there was something we needed to update in our service bus trigger endpoint. So I'm not sure if there is something we need to tweak to make it less chatty. 

We've also noticed in the same solution a function app / api that writes to blob storage now doesn't track dependencies properly in application insights

Previously we were seeing (single entry):
![image](https://user-images.githubusercontent.com/77314668/145527815-53b9f476-7143-419a-b180-49fadc22bb99.png)

and now we see two traces
![image](https://user-images.githubusercontent.com/77314668/145527561-85e55277-be62-4db7-93bf-0ded882a742a.png)

So something seems out of whack telemetry wise in a v3 function app.

### Environment

Azure Function v3
Visual Studio 22

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @jenp-jb,
In the V5 version of the Service Bus trigger, we've enabled SDK logging, so the logs that the Service Bus SDK emits are being forwarded on to your functions logs. If you want to reduce the amount of logging, you can change the filter for logs that are coming from the SDK, e.g. something like the following:

```
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Azure.Messaging.ServiceBus": "Error"
    }
  }
```

For more info, please take a look at https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging#map-to-aspnet-core-logging

**Comment by jenp-jb** [comment]
Thanks for the info on SDK logging - but can you please provide feedback on us losing the ability to see the blob dependency correctly? ie. this part of my question:
![image](https://user-images.githubusercontent.com/77314668/145900352-76bc9f8f-fe6b-46ca-a080-a11f845d00a7.png)

**Comment by JoshLove-msft** [comment]
Which trigger are you using here?

**Comment by mrobertsonavidxchange** [comment]
/unresolve

The support [here](https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging#map-to-aspnet-core-logging) requires registering of a service bus client using the builder in startup, but for all of our service bus triggered methods, we do not register the service bus, but allow the ServiceBusTrigger attribute to create a client for us. Is there a way to reduce the logging without changing this workflow?

Creation of our service bus client:
`public async Task RunAsync([ServiceBusTrigger("%PayablesDetectorTopicName%", "%PayablesDetectorSubscriptionName%",
                Connection = "IdcSvcBusConnStr")]
            ServiceBusReceivedMessage msg, ServiceBusMessageActions messageActions)`

I've added 

`"Logging": {
        "LogLevel": {
            "Default": "Information",
            "Microsoft.AspNetCore": "Warning",
            "Azure.Messaging.ServiceBus": "Debug"
        }
    },`

to the local.appsettings.json, but it didn't work in reducing the logging, and I don't think there's any way for the C# code to reference the Logging specifications in the json.

**Comment by JoshLove-msft** [comment]
@mrobertsonavidxchange you specifying debug level logging for Azure.Messaging.ServiceBus which will include all of the Service Bus library logs. Did you mean to put "Warning"?

**Comment by MSIT-BPSC-IOT** [comment]
I know everywhere we were asked to suppress the logging via host.json or appsettings.json. However, it didn't work. Can we have a clear work around on this?

**Comment by jsquire** [comment]
@MSIT-BPSC-IOT : Please open a new issue with the context and details for your scenario.

**Comment by robertson809** [comment]
@JoshLove-msft  Thank you, that might have worked, but I found a different workaround first, (which you might be interested in @MSIT-BPSC-IOT :

`.MinimumLevel.Override("Azure.Core", LogEventLevel.Error)
                .MinimumLevel.Override("Azure.Messaging.ServiceBus", LogEventLevel.Error)
                .MinimumLevel.Override("Microsoft.Azure.WebJobs", LogEventLevel.Error)
                .MinimumLevel.Override("Microsoft.Azure.WebJobs.ServiceBus", LogEventLevel.Error)`

Takes out all the extra logging.
