### ISSUE TITLE
[Tables] CustomizeSerialization failing intermittently in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#25861]
Tables nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : This request is not authorized to perform this operation using this permission.
> RequestId:52d38834-3002-008a-79e3-ecb3e3000000
> Time:2021-12-09T09:58:59.4012893Z
> Status: 403 (Forbidden)
> ErrorCode: AuthorizationPermissionMismatch
> 
> Content:
> {"odata.error":{"code":"AuthorizationPermissionMismatch","message":{"lang":"en-US","value":"This request is not authorized to perform this operation using this permission.\nRequestId:52d38834-3002-008a-79e3-ecb3e3000000\nTime:2021-12-09T09:58:59.4012893Z"}}}
> 
> Headers:
> Cache-Control: no-cache
> Transfer-Encoding: chunked
> Server: Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0
> x-ms-request-id: 52d38834-3002-008a-79e3-ecb3e3000000
> x-ms-client-request-id: 8946fdbc-c22f-4711-808a-51eebe7abaa6
> x-ms-version: REDACTED
> X-Content-Type-Options: REDACTED
> Preference-Applied: REDACTED
> Date: Thu, 09 Dec 2021 09:58:58 GMT
> Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8
> 
> 
> Stack trace
>    at Azure.Data.Tables.TableRestClient.InsertEntityAsync(String table, Nullable`1 timeout, Nullable`1 responsePreference, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken) in /_/sdk/tables/Azure.Data.Tables/src/Generated/TableRestClient.cs:line 937
>    at Azure.Data.Tables.TableClient.AddEntityAsync[T](T entity, CancellationToken cancellationToken) in /_/sdk/tables/Azure.Data.Tables/src/TableClient.cs:line 562
>    at Azure.Data.Tables.Samples.TablesSamples.CustomizeSerialization() in /Users/runner/work/1/s/sdk/tables/Azure.Data.Tables/tests/samples/Sample8_CustomizingSerialization.cs:line 54
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1239072&view=results

@jsquire for notification.

**Comment by christothes** [comment]
This seems like an environment issue.
