### ISSUE TITLE
[QUERY] Release new version of Microsoft.Azure.WebJobs.Extensions.EventGrid

### ISSUE THREAD

**Issue by smafre** [Azure/azure-sdk-for-net#25871]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventGrid 3.0.x

### Query/Question

I recently reported an issue with Microsoft.Azure.WebJobs.Extensions.EventGrid version 3.0.0 (#25810). This was fixed in #25813, but I am wondering how long we need to wait until a new release is available so we can get our issue fixed. I didn't really find any information on how you usually manage new releases. If we have to wait long for a new release of Microsoft.Azure.WebJobs.Extensions.EventGrid we need to work our way around our issue some other way.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @smafre,
We generally release new versions the second week of each month, so we'd be looking at the week of Jan 10th. Would this work for your timelines?

**Comment by smafre** [comment]
@JoshLove-msft We need it as soon as possible. If the release won't be out until the week of Jan 10th we need to work our way around the issue some other way.

**Comment by JoshLove-msft** [comment]
Released 3.0.1 - https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/3.0.1
Please let us know if you are still seeing the issue.
