### ISSUE TITLE
[FEATURE REQ] Add disclosure to package(s)

### ISSUE THREAD

**Issue by CoryKoehler** [Azure/azure-sdk-for-net#25872]
### Library name

Azure.Core and Azure.Identity 

### Please describe the feature.

Hi,

Currently the Azure.Core and Azure.Identity package are flagged by Google Ads due to lacking a disclosure.
Would it be possible to get a disclosure added to the listed packages? I am using these packages in a Blazor WASM app and trying to get google to approve our ads on the site and one of the final hurdles are proper software disclosure on all .dll that the client downloads.

I have done the experimental bundling package provided as a solution to this but I still think adding disclosures is good for a couple of reasons.
One reason being that the bundler process is experimental and not fully supported. Another being that the build times with bundler process is quite large.

From what I can tell the following would help (not sure if everything is necessary)
1. License file (needs to also be moved into each packaged project)
2. In the .csproj of the package there are some properties that can be added
```
<PackageLicenseFile>LICENSE</PackageLicenseFile>
<Company>Microsoft</Company>
<Version>x.x.x</Version> 
<PackageIcon>someicon.png</PackageIcon>
<Authors> Whomever</Authors>
<Copyright>Copyright 2021 Microsoft</Copyright>
<PackageTags>Azure, .Net, ETC, ETC</PackageTags>
<Description>Some description</Description>
<RepositoryUrl>https://github.com/Azure/azure-sdk-for-net/</RepositoryUrl>
<RepositoryType>git</RepositoryType>
```
3. Contributing.Md
4. CODE_OF_CONDUCT.md
5. CHANGELOG.md

Thanks

**Comment by jsquire** [comment]
//cc: @pakrym, @weshaggard

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by weshaggard** [comment]
@CoryKoehler we used to directly include the license file in our packages but we switched to using a license expression (https://docs.microsoft.com/en-us/nuget/reference/nuspec#license) based on recommendation of the nuget team. We do include the CHANGELOG.md why is it important for the other files to be included directly in the package? Is there some published policy you are trying to adhere to that you can point us at?

**Comment by CoryKoehler** [comment]
Hi @weshaggard 
I do not have a publish policy from Google Ads - from my understanding they provided a team to directly look into our production website and came back with a list of packages that do not meet their criteria. 

---
The exact wording is:
"It seems these are the following links on your site that are triggering the flag: 
1. _framework/Azure[.]Core[.]dll
2. _framework/Azure[.]Identity[.]dll

They trigger a download that fails to provide proper disclosure. You can read more about the policy here. Once you remove these, you can appeal your ads to be reviewed accordingly on the account and it should work!"

---

I've looked at other packages we are utilizing that did not get flagged and I just laid out the differences in my original ask. E.G https://github.com/dotnet/runtime or https://github.com/MudBlazor/MudBlazor
Unfortunately as I said I am just doing comparisons with what passed vs what did not and am not very familiar with this space.

Could it be that the nuget config file in this project does not have a reference a license and accept ? or perhaps another referenced package within the mentioned projects are missing a license?

**Comment by weshaggard** [comment]
This is the our current nuspec for Azure.Core (and should be the same for all our packages):
```
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>Azure.Core</id>
    <version>1.21.0</version>
    <authors>Microsoft</authors>
    <requireLicenseAcceptance>true</requireLicenseAcceptance>
    <license type="expression">MIT</license>
    <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>
    <icon>pkgicon.png</icon>
    <projectUrl>https://github.com/Azure/azure-sdk-for-net/blob/Azure.Core_1.21.0/sdk/core/Azure.Core/README.md</projectUrl>
    <description>This is the implementation of the Azure Client Pipeline</description>
    <releaseNotes>https://github.com/Azure/azure-sdk-for-net/blob/Azure.Core_1.21.0/sdk/core/Azure.Core/CHANGELOG.md</releaseNotes>
    <copyright>© Microsoft Corporation. All rights reserved.</copyright>
    <tags>Microsoft Azure Client Pipeline</tags>
    <readme>README.md</readme>
    <repository type="git" url="https://github.com/Azure/azure-sdk-for-net" commit="41707fcdb76dd4f802eb0ced18a0dd9c6250b0e6" />
    <dependencies>
      <group targetFramework=".NETFramework4.6.1">
        <dependency id="Microsoft.Bcl.AsyncInterfaces" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="System.Diagnostics.DiagnosticSource" version="4.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Memory.Data" version="1.0.2" exclude="Build,Analyzers" />
        <dependency id="System.Numerics.Vectors" version="4.5.0" exclude="Build,Analyzers" />
        <dependency id="System.Text.Encodings.Web" version="4.7.2" exclude="Build,Analyzers" />
        <dependency id="System.Text.Json" version="4.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Threading.Tasks.Extensions" version="4.5.4" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETCoreApp2.1">
        <dependency id="Microsoft.Bcl.AsyncInterfaces" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="System.Diagnostics.DiagnosticSource" version="4.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Memory.Data" version="1.0.2" exclude="Build,Analyzers" />
        <dependency id="System.Numerics.Vectors" version="4.5.0" exclude="Build,Analyzers" />
        <dependency id="System.Text.Encodings.Web" version="4.7.2" exclude="Build,Analyzers" />
        <dependency id="System.Text.Json" version="4.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Threading.Tasks.Extensions" version="4.5.4" exclude="Build,Analyzers" />
      </group>
      <group targetFramework="net5.0">
        <dependency id="Microsoft.Bcl.AsyncInterfaces" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="System.Diagnostics.DiagnosticSource" version="4.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Memory.Data" version="1.0.2" exclude="Build,Analyzers" />
        <dependency id="System.Numerics.Vectors" version="4.5.0" exclude="Build,Analyzers" />
        <dependency id="System.Text.Encodings.Web" version="4.7.2" exclude="Build,Analyzers" />
        <dependency id="System.Text.Json" version="4.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Threading.Tasks.Extensions" version="4.5.4" exclude="Build,Analyzers" />
      </group>
      <group targetFramework=".NETStandard2.0">
        <dependency id="Microsoft.Bcl.AsyncInterfaces" version="1.0.0" exclude="Build,Analyzers" />
        <dependency id="System.Diagnostics.DiagnosticSource" version="4.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Memory.Data" version="1.0.2" exclude="Build,Analyzers" />
        <dependency id="System.Numerics.Vectors" version="4.5.0" exclude="Build,Analyzers" />
        <dependency id="System.Text.Encodings.Web" version="4.7.2" exclude="Build,Analyzers" />
        <dependency id="System.Text.Json" version="4.6.0" exclude="Build,Analyzers" />
        <dependency id="System.Threading.Tasks.Extensions" version="4.5.4" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

I believe we are doing everything we should for disclosure and at this point I'm not sure what else is missing. Perhaps you can follow-up more internally to figure out exactly what is missing as I don't want to just make random changes that may or may not help you get these accepted.

**Comment by CoryKoehler** [comment]
That is understandable.

I will take this back to Google Ads team and see what they say. Thank you.

**Comment by CoryKoehler** [comment]
Hi - still waiting on the google ads team for further clarification

**Comment by CoryKoehler** [comment]
Hi all -

I have no idea why but google decided to unflag our site and our dlls with no changes to the packages mentioned above.
Not sure why they were flagged in the first place and now unflagged but I'll take it.

Thank you
![image](https://user-images.githubusercontent.com/5295679/147574614-599cb277-81ab-4dc8-b281-16593dec784f.png)
