### ISSUE TITLE
[QUERY] How to import Azure.Core.TestFramework

### ISSUE THREAD

**Issue by gabidabet** [Azure/azure-sdk-for-net#25870]
### Library name and version

Azure.storage.blobs 12.8.0

### Query/Question

Hello to write some tests that test some custom policies. I need to use MockTransport and other classes in Azure.Core.TestFramework. This [Documentation](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core.TestFramework#readme) didn't work for me. I always get AzureCoreTestFramework is not defined.

### Environment

windwos 10.
Visual studio 2019.
.net 3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @gabidabet,
Those instructions assume you are working with the repo source locally, as we don't publish the Azure.Core.TestFramework package currently. Would you be able to pull down the repo code locally and add Azure.Core.TestFramework to your solution?

**Comment by gabidabet** [comment]
Thank you for your reply, I just forked why I need thank for your help. I just thought that I can import the namespace in my project.
