### ISSUE TITLE
Description of OVERLOADS GetItemQueryIterator is same

### ISSUE THREAD

**Issue by raihantaher** [Azure/azure-sdk-for-net#25878]
I see that the descriptions of the  **GetItemQueryIterator** overload methods are same. I am not sure if that is correct, because the first overloaded method 

`GetItemQueryIterator<T>(String, String, QueryRequestOptions)`

is expecting a queryText as first parameter, not a QueryDefinition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f022e1c2-c13f-e4ff-a5c9-932b5dc412c0
* Version Independent ID: f0b87c16-a3a2-61a0-2c45-f320ddc2a8ca
* Content: [Container.GetItemQueryIterator Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.getitemqueryiterator?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@raihantaher Thanks for the feedback! You are right about the description being the same and the one expecting a `queryText` doesn't accept parameters. We will work with the concerning team to get this addressed.
