### ISSUE TITLE
Add->REST API Client... command fails in VS2015

### ISSUE THREAD

**Issue by jimt4593** [Azure/azure-sdk-for-net#2587]
After installing Azure App Service Tools v2.9.6. 14.0.21111.0, I get the following error when clicking OK in the Add REST API Client dialog is:

> Generating client code and adding to project started
> Generate client code for REST API with following parameters:
> REST API Name: MessageMarkerWebAPIClient, Base namespace: ABLUploadEmailAddin, Metadata file path: C:\Users\jxxxxx\AppData\Local\Temp\WebToolsAutoRest\MessageMarkerWebAPIClient\201611201949071018\swagger.json
> > Exception: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
> Generating client code and adding to project failed
> Adding REST API client for failed

I worked around the error by copying Newtonsoft.Json.dll (file version 7.0.1.18622) into the C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE directory.

**Comment by markcowl** [comment]
@jimt4593 This is the repository for Azure management libraries, not VS tooling.  Please redirect this issue at the VS team.

**Comment by markti** [comment]
@jim4593 how exactly would we do that?

**Comment by markti** [comment]
@markcowl isn't the "Add REST Client" a visual studio extension that is included in the Azure SDK?

**Comment by pwen090** [comment]
@markcowl this is still an issue - could you please help us at least get in touch with the right MS people to get some support? Thank you much.

**Comment by ElD4n1** [comment]
Same problem here, REST API Client generation was working fine before installing newest Azure SDK, so it has to have something to do with it.
Here is a workaround that worked for me: http://stackoverflow.com/questions/41373912/add-rest-api-client-command-fails-in-vs2015
Just download the NuGet package and copy the .dll into the stated folder and it should work again.

**Comment by Xavina** [comment]
Same Issue here. Had to generate the REST API Client in Visual Studio 2013.

**Comment by ElD4n1** [comment]
For a permanent workaround consider to download the AutoRest NuGet package manually and use the included AutoRest.exe via command line (e.g. NuGet Package Manager Console) to always have the newest version in use.

**Comment by PHBeagle** [comment]
This worked for me, but I did have to resolve one additional error.  When installing the API (after copying Newtonsoft.Json.dll 7.0.1, then I had a problem with Microsoft.Rest.ClientRuntime 2.3.2 failing to install.  I installed it via NuGet Package installer, then did the API install again and it all worked.
