### ISSUE TITLE
Release Azure.ResourceManager.ApiManagement

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#25884]

**Comment by tdysko-star** [comment]
Are there plans to release SDK? it's in preview for a few years now, is it blocked by something we should monitor?

**Comment by Yao725** [comment]
> Are there plans to release SDK? it's in preview for a few years now, is it blocked by something we should monitor?

We are working on releasing this SDK, but there is no specific date planned yet.
