### ISSUE TITLE
[Text Analytics] Add a sample for setting model version

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk-for-net#25898]
### Library name

Text Analytics

### Please describe the feature.

The service team asked the SDK crew to add a sample that shows how to set the model version in the client methods.

JS sample: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/textanalytics/ai-text-analytics/samples/v5/typescript/src/modelVersion.ts

**Comment by kinelski** [comment]
JS and Python PRs for the same issue:
JS: https://github.com/Azure/azure-sdk-for-js/pull/19087
Python: https://github.com/Azure/azure-sdk-for-python/pull/22132
