### ISSUE TITLE
pageSizeHint lacks information

### ISSUE THREAD

**Issue by RDavis3000** [Azure/azure-sdk-for-net#25891]
pageSizeHint, is it in bytes or the count of T returned with each request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b64c7d78-1adc-bc52-2998-94da86d4fd3b
* Version Independent ID: 8d013082-62a2-8ed0-b67c-18575f0d8736
* Content: [AsyncPageable&lt;T&gt;.AsPages(String, Nullable&lt;Int32&gt;) Method (Azure) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.asyncpageable-1.aspages?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Azure.AsyncPageable%601.AsPages);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet)
* Content Source: [xml/Azure/AsyncPageable`1.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure/AsyncPageable`1.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
