### ISSUE TITLE
[BUG] Camel case is not supported for application properties(keys)

### ISSUE THREAD

**Issue by androsovandrii** [Azure/azure-sdk-for-net#25894]
### Library name and version

Azure.Messaging.ServiceBus, Version=7.0.0.0

### Describe the bug

when created 
service bus message with application properties
serviceBusMessage.ApplicationProperties.Add("ApiVersion", 1);
serviceBusMessage.ApplicationProperties.Add("CreateTimestamp", dateNow);

and we send it to topic (on azure topic we still have all keys in lowercase) so we have 
![image](https://user-images.githubusercontent.com/19612099/145821251-b6167c3f-40b8-4d51-872c-98fda29ea230.png)
so, please fix it, for our client is very needed to have camelCase

### Expected behavior

camelCase for aplication properties on azure service bus explorer topic message

### Actual behavior

lowercase for aplication properties on azure service bus explorer topic message

### Reproduction Steps

ServiceBusMessage serviceBusMessage = new ServiceBusMessage(message);
 serviceBusMessage.ApplicationProperties.Add("EventEntity", "LoyaltyAccount");
                    serviceBusMessage.ApplicationProperties.Add("ApiVersion", 1);
                    serviceBusMessage.ApplicationProperties.Add("CreateTimestamp", dateNow);
await sender.SendMessageAsync(serviceBusMessage);

**Comment by jsquire** [comment]
Hi @androsovandrii.  Thank you for reaching out and we regret that you're experiencing difficulties.  Both the Service Bus client and service treat the application properties of a message as an opaque set of data; neither inspects nor alters the items provided by the application, including changing capitalization of keys.   I'm not sure what tool you're using to visualize the message in the image above, but I'm unable to reproduce what you're seeing in the Azure portal nor in code.  _(details below)_  

Can you verify that you're seeing the case changed when you attempt to read back the message that you published directly in your code?   We'd also appreciate if you could help us understand a bit more about your architecture - is your code reading directly from a subscription on the topic where the message was published, or are there any intermediaries doing processing work before the message is read back?  



#### Repro Attempt details

```csharp
await using var client = new ServiceBusClient("<< CONNECTION STRING >>");
await using var sender = client.CreateSender("test");

var message = new ServiceBusMessage("dummy");
message.ApplicationProperties.Add("EventEntity", "LoyaltyAccount");
message.ApplicationProperties.Add("ApiVersion", 1);
message.ApplicationProperties.Add("CreateTimestamp", DateTime.UtcNow.ToString());

await sender.SendMessageAsync(message);
```

The portal shows me the properties with the casing preserved:

![image](https://user-images.githubusercontent.com/913445/145826556-ceadefc7-2283-45c8-815d-32116ba82370.png)

As does reading the message back in code:
```csharp
await using var receiver = client.CreateReceiver("test", "read");

var readMessage = await receiver.ReceiveMessageAsync(TimeSpan.FromMinutes(1));    
await receiver.CompleteMessageAsync(readMessage);    

readMessage.Dump();
```
![image](https://user-images.githubusercontent.com/913445/145826766-890bd946-04a5-4700-a688-18b241a7c2c5.png)

**Comment by androsovandrii** [comment]
@jsquire yes you are right but as you see

**Comment by jsquire** [comment]
> @jsquire yes you are right but as you see "The portal shows me the properties with the casing preserved:" - apiversion - not apiVersion or ApiVersion, and evententity no eventEntity or EventEntitym why so?

Unfortunately, I can't speak for the portal, as it isn't part of the Azure SDK.   Am I correct in interpreting your response as confirmation that you're not seeing the case change when reading messages back in code using the Service Bus client library?

For the portal question, unfortunately, there is no GitHub instance for me to transfer the inquiry to since the portal is not an open source product.   Your best path for seeking that answer would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

**Comment by androsovandrii** [comment]
@jsquire , thank you very much for help, yes I think it's portal issue(or some configuration topic)

thank you for cooperation

**Comment by jsquire** [comment]
I regret that we're not able to help dig into the portal behavior, but I'm glad to see that it's just a display issue.   I'm going to mark this as addressed and close things out.   Please feel free to use the "`/unresolve`" command if you'd like to continue the discussion.
