### ISSUE TITLE
[BUG] Intermittent issues calling the DeleteSiteExtensionSlotAsync method

### ISSUE THREAD

**Issue by krelf** [Azure/azure-sdk-for-net#25903]
### Library name and version

Microsoft.Azure.Management.AppService.Fluent v1.38.0

### Describe the bug

As part of application deployments via our .net CICD pipeline, we remove site extensions from a Web App as part of the slot swap.  To do so we call the DeleteSiteExtensionSlotAsync method in the Microsoft.Azure.Management.AppService.Fluent v1.38.0 library.  Intermittently we come across the error below.

`Application error: System.Net.Http.HttpRequestException: An error occurred while sending the request.`
`---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..`
`---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.`
`   --- End of inner exception stack trace ---`
`   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)`
`   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)`
`   at System.Net.Http.HttpConnection.FillAsync()`
`   at System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(Boolean foldedHeadersAllowed)`
`   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)`

### Expected behavior

The `DeleteSiteExtensionSlotAsync` method removes the site extension each time it is called.

### Actual behavior

Intermittently an error is encountered whilst removing the site extension, as per the error mentioned above.  Other times it completes successfully.

### Reproduction Steps

The method is being invoked via the code below:

`_azure.WebApps.Inner.DeleteSiteExtensionSlotAsync(WebApp.ResourceGroupName, WebApp.Name, siteExtensionId, slot.ToString());`

### Environment

.NET Core SDK (reflecting any global.json):
 Version:   3.1.120
 Commit:    6f5755c372

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.120\

Host (useful for support):
  Version: 3.1.20
  Commit:  2833dab8c3

.NET Core SDKs installed:
  3.1.120 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by liurunliang** [comment]
Hi @krelf I am not able to reproduce this issue. Please provide more information if it still affect you.

**Comment by krelf** [comment]
Hi @liurunliang, this issue still persists.  Further instances occurred within the last week.  What additional information do you require?

**Comment by liurunliang** [comment]
Hi @krelf Does this issue affects `DeleteSiteExtensionSlotAsync` only or others as well?
