### ISSUE TITLE
[BUG] BatchException is not serializable

### ISSUE THREAD

**Issue by gtrubach** [Azure/azure-sdk-for-net#25917]
### Library name and version

Microsoft.Azure.Batch 15.1.0

### Describe the bug

When [BatchException](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/batch/Microsoft.Azure.Batch/src/Common/BatchException.cs) is thrown in Azure Function, we get an exception that it can't be serialized.

### Expected behavior

BatchException is serialized without any issues.

### Actual behavior

```
The activity function 'Function1' failed: "Failed to deserialize exception from TaskActivity: 

{"$type":"Microsoft.Azure.Batch.Common.BatchException, Microsoft.Azure.Batch","RequestInformation":

{"$type":"Microsoft.Azure.Batch.Common.RequestInformation, Microsoft.Azure.Batch" 

// rest is emitted
```

### Reproduction Steps

1. Create any C# Function from template (in-process, .NET 6)
2. Install Batch client.
3. Perform any Batch operation to get `BatchException` (in my case it's a conflicting request - we add a task with the existing name).
4. See the response.

Note: I use Durable Functions, but I believe exception serialization is a more general thing.

### Environment

.NET 6
Durable Functions v4 (in-process)
Visual Studio Enterprise 2022

**Comment by PramodValavala-MSFT** [comment]
@gtrubach the error that you are seeing is from deserialization of the exception which is tracked in [this issue](https://github.com/Azure/azure-functions-durable-extension/issues/313) for Durable Functions. Based on the discussion there, I suppose one workaround would be to handle the exception and return a custom serializable one. Either way, I believe the discussion is best continued in the durable functions extension repo.
