### ISSUE TITLE
[BUG] Error while using ServiceBusProcessor - Azure.Messaging.ServiceBus SDK

### ISSUE THREAD

**Issue by arunprakashn** [Azure/azure-sdk-for-net#25919]
### Library name and version

Azure.Messaging.Servicebus 7.5.1

### Describe the bug

I am getting an exception after the StartProcessingAsync() method. The debug pointer goes to the "ProcessorErrorAsync" method. I followed similar steps provided in the link - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample04_Processor.md Am I missing some steps here? Exception Details: error.Exception.Message:

```text
 Method not found: 'System.Threading.Tasks.Task`1<System.Collections.Generic.IEnumerable`1<Microsoft.Azure.Amqp.AmqpMessage>> 
Microsoft.Azure.Amqp.ReceivingAmqpLink.ReceiveMessagesAsync(Int32, System.TimeSpan, System.TimeSpan, System.Threading.CancellationToken)'.
```

```csharp
private void ListenerBind(string key, ServiceBusProcessorOptions onMessageOptions)
        {
            ServiceBusClient tempClient = this._cacheClient.Get(key);
            ServiceBusProcessor tempProcessor = tempClient.CreateProcessor(this._topicName, this._subscriptionName, onMessageOptions);
            try
            {
                //temp.OnMessageAsync(this.MessageProcessCallBackAsync, onMessageOptions);
                tempProcessor.ProcessMessageAsync += MessageProcessCallBackAsync;
                tempProcessor.ProcessErrorAsync += ProcessErrorAsync;
                tempProcessor.StartProcessingAsync();
            }
            catch (InvalidOperationException ex)
            {
                this._logger.Log($"{ex.Message}", EventLevel.Informational);
            }
            catch (Exception ex)
            {
                this._logger.LogException(ex);
            }
        }
        private Task ProcessErrorAsync(ProcessErrorEventArgs error)
        {
            Exception ex = new Exception(
                $" , Action {error.ErrorSource}, " +
                $" , Endpoint {error.FullyQualifiedNamespace}" +
                $",EntityPath {error.EntityPath} "
                , error.Exception);
            this._logger.LogException(ex);

            this._onErrorCallback(ex, string.Empty);

            return Task.CompletedTask;
        }
```

### Expected behavior

Listening to the subscription must have started

### Actual behavior

Got Exception :

```text
Method not found: 'System.Threading.Tasks.Task`1<System.Collections.Generic.IEnumerable`1<Microsoft.Azure.Amqp.AmqpMessage>> 
Microsoft.Azure.Amqp.ReceivingAmqpLink.ReceiveMessagesAsync(Int32, System.TimeSpan, System.TimeSpan, System.Threading.CancellationToken)'.
```

### Reproduction Steps

Steps described in the description

### Environment

dotnet 4.8

**Comment by jsquire** [comment]
Hi @arunprakashn.  Thank you for reaching out and we regret that you're experiencing difficulties.  The message that you're seeing most likely indicates that there is a problem with the version of the `Microsoft.Azure.Amqp` library being used by the application.   Would you be so kind as to share the contents of the project file for your application, with any sensitive information redacted, so that we can better understand its references and transient dependencies?

**Comment by arunprakashn** [comment]
@jsquire : Even I was thinking the same.  I removed the "Azure.Messaging.ServiceBus" reference from my project and added it again. The pop-up listed the dependencies and it also contained the Amqp nuget. After completion, I see that the Amqp package is not found. Attaching the package reference from my project file.

```
 <ItemGroup Condition="'$(TargetFramework)' == 'net48'"> 
    <PackageReference Include="xyz.Platform.Core" Version="2.0.3" /> 
    <PackageReference Include="xyz.Platform.Logging" Version="2.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.0.0" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.2.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Ninject" Version="3.3.4" />
    <PackageReference Include="RabbitMQ.Client" Version="5.0.1" />
    <Reference Include="System.Net" />
    <Reference Include="System.Net.Http.WebRequest" />

  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netcoreapp2.0'">
    <PackageReference Include="xyz.Platform.Core" Version="1.7.0" />
    <PackageReference Include="xyz.Platform.Logging" Version="2.4.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="2.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Ninject" Version="3.3.4" />
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="3.3.0" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.13" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.5.1" />
    <PackageReference Include="Polly" Version="7.1.0" />
    <PackageReference Include="Itron.Platform.Code.Ruleset" Version="1.0.17" />
    <PackageReference Include="RabbitMQ.Client" Version="5.1.0" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="5.0.1" />
    <PackageReference Include="System.Diagnostics.TraceSource" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.Tracing" Version="4.3.0" />
  </ItemGroup>
```

**Comment by jsquire** [comment]
Hi @arunprakashn.   Thank you for the additional context.   Unfortunately, I'm unable to reproduce this locally using the set of dependencies that you listed.   It does appear that you've got a custom package feed, so I had to drop the `xzy.*` and `Itron.*` references, though I don't see that as being a likely cause.  We'd be grateful for any additional information or assets that you're able to share that would help us be able to reproduce what you're seeing locally.

Since we're not able to repro to troubleshoot, can we ask you do try the following:

- Delete the `obj` and `bin` folders from your application's output directory.   Run `dotnet clean && dotnet restore && dotnet build && dotnet run` from the directory with the project.   Does the same behavior reproduce? 

- Create a new console application locally on the machine where you're seeing the issue using these references and with the content of `Sample04_Processor` as the entry point.    Do you see the behavior in this context?

**Comment by arunprakashn** [comment]
Thank you @jsquire.
Resolved now. Turns out there was an issue with referencing new Amqp nuget. I see that the latest Azure.Amqp is a dependency that comes along the new service bus SDK, but still was having reference issues. I deleted the Amqp nuget several times and re-added but that didn't solve the issue. the ".nuspec" file was still having reference to the legacy SDK and when I commented it, re-added the new Azure.Messaging.Servicebus nuget, the error vanished.

I commented the line for the legacy SDK as shown below.

<group targetFramework=".NETFramework4.8">
        <dependency id="Microsoft.Extensions.DependencyInjection.Abstractions" version="2.0.0"/>
        <dependency id="Microsoft.Rest.ClientRuntime" version="2.2.0"/>
        <dependency id="Newtonsoft.Json" version="12.0.3"/>
        <dependency id="Ninject" version="3.3.4"/>
        
        <dependency id="Polly" version="7.1.0"/>
        <dependency id="RabbitMQ.Client" version="5.0.1"/>
        <dependency id="System.Diagnostics.DiagnosticSource" version="4.5.0"/>
        <dependency id="System.Diagnostics.TraceSource" version="4.3.0"/>
		<dependency id="System.Diagnostics.Tracing" version="4.3.0"/>
	  </group>

**Comment by jsquire** [comment]
Hi @arunprakashn.   Glad that you've got things figured out.   It looks like the legacy Service Bus package was not included in your initial comment, which would be why we weren't able to repro.
