### ISSUE TITLE
[QUERY] How do we enable "latest" version for a keyvault hosted certificate via the SDK

### ISSUE THREAD

**Issue by delradie** [Azure/azure-sdk-for-net#25923]
### Library name and version

Microsoft.Azure.Management.FrontDoor 4.0.0

### Query/Question

When enabling Https via the SDK, if leaving the SecretVersion blank in the CustomHttpsConfig null the configuration put in place is set with the current version ID of the certificate, rather than setting it as "latest".

Given that the guidance given states specifically that best practice is to use "latest" am I misunderstanding this part of the API, or is there another way to enable it this way?

### Environment

OS Windows 10 21H2
Target framework : .net 4.7.2
IDE: Visual Studio 17.0.1

**Comment by liurunliang** [comment]
Hi @delradie, I can't reproduce this issue. Here is an example for enabling HTTPS.
```
string resourceGroupName = "resourceGroupName";
string subscriptionId = "00000000-0000-0000-0000-0000000000";
string frontDoorName = "frontDoorName";
string frontEndpointName = "frontdoor-contoso-com";
string keyVaultName = "keyVaultName";
string secretName = "secretName";
var frontdoor = await client.FrontDoors.GetAsync(resourceGroupName, frontDoorName);
await client.FrontendEndpoints.EnableHttpsAsync(
    resourceGroupName,
    frontDoorName,
    frontEndpointName,
    new CustomHttpsConfiguration(
        "AzureKeyVault",
        "1.2",
        new KeyVaultCertificateSourceParametersVault("/subscriptions/" + subscriptionId + "/resourceGroups/" + resourceGroupName + "/providers/Microsoft.KeyVault/vaults/" + keyVaultName),
        secretName)
    );
```
