### ISSUE TITLE
[QUERY] How do I set retry policy/options on BlobClient in F#?

### ISSUE THREAD

**Issue by atsapura** [Azure/azure-sdk-for-net#25920]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Query/Question

I've seen issue [this issue](https://github.com/Azure/azure-sdk-for-net/issues/16980), but I don't see how one can do it in F#. Using
`let o = BlobClientOptions(Retry = ...)` doesn't work, compiler says 'there's no settable property `Retry`'.

Also, is there a way to specify retry policy in binding in Azure Functions or do it on an initialized instance of client?

**Comment by SatishBoddu-MSFT** [comment]
Hello @atsapura Thanks for the feedback, this is a great query!

![image](https://user-images.githubusercontent.com/62923178/146134753-ec8b7176-96af-4d4a-a1bd-1a00cd6c92b8.png)

Let me route this to the service team so that we get help on this query!

**Comment by atsapura** [comment]
Our use case is we bind `BlobContainerClient` in azure function, and use it to do deal with several blobs in one az-function call. Naturally, to do that we call `blobContainerClient.GetBlobClient(blobPath)` and later `blobClient.GetBlobLeaseClient()` (so many clients), but there're no overloads that let us specify retry options right away. Which is a real shame, because it'd be nice for the client to retry lease acquiring if the blob is currently under the other lease.

**Comment by amishra-dev** [comment]
@kasobol-msft do we even support F#?

**Comment by kasobol-msft** [comment]
@amishra-dev yes, end of the day F# and C# share runtime, so one can use .NET libraries in F# app.

@atsapura The Retry is indeed read-only see https://docs.microsoft.com/en-us/dotnet/api/azure.core.clientoptions.retry?view=azure-dotnet#azure-core-clientoptions-retry (the `BlobClientOptions` derive from `ClientOptions`). If you want to modify retry you'd need to change them after `BlobClientOptions` gets created i.e.
```
let o = BlobClientOptions()
o.Retry.Delay = ...
```
