### ISSUE TITLE
[BUG] Azure.Messaging.EventGrid cannot deserialize StorageDirectoryDeletedEventData from event data

### ISSUE THREAD

**Issue by ras-relativity** [Azure/azure-sdk-for-net#25935]
### Library name and version

Azure.Messaging.EventGrid 4.7.0

### Describe the bug

I triggered a directory deletion event in a Storage Account, the event looks like this:

{{"api":"DeleteDirectory","requestId":"c3ef9306-901f-0022-1433-f12961000000","blobUrl":"https://<storage_account>.blob.core.windows.net/<container_name>/xdcdc","url":"https://<storage_account>.dfs.core.windows.net/<container_name>/xdcdc","recursive":"false","sequencer":"00000000000000000000000000016e66000000000000005b","identity":"$superuser","storageDiagnostics":{"batchId":"962bfd51-0006-0041-0033-f16f44000000"}}}

When I try to deserialize the event with the code below, I get an exception
`var directoryDeletedEvent = eventGridEvent.Data.ToObjectFromJson<StorageDirectoryDeletedEventData>();`

The exception might be because "recursive" value is a string in the json but bool in the class?

### Expected behavior

The message is deserialized and doesn't throw exception

### Actual behavior

Exception has occurred: CLR/System.Text.Json.JsonException
Exception thrown: 'System.Text.Json.JsonException' in System.Text.Json.dll
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.InvalidOperationException : The requested operation requires an element of type 'Boolean', but the target element has type 'String'.
   at System.Text.Json.JsonElement.GetBoolean()
   at Azure.Messaging.EventGrid.SystemEvents.StorageDirectoryDeletedEventData.DeserializeStorageDirectoryDeletedEventData(JsonElement element)
   at Azure.Messaging.EventGrid.SystemEvents.StorageDirectoryDeletedEventData.StorageDirectoryDeletedEventDataConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)

### Reproduction Steps

1. Create an Azure.Messaging.ServiceBus.ServiceBusProcessor object, write a method to handle ProcessMessageAsync event, start processing.:
`
ProcessEvent(ProcessMessageEventArgs eventArgs)
{
    var eventGridEvent = EventGridEvent.Parse(eventArgs.message.Body);
    var directoryDeletedEvent = eventGridEvent.Data.ToObjectFromJson<StorageDirectoryDeletedEventData>();
    // exception should be thrown by previous line
}
`

2. Setup a queue to listen to a storage account's Directory Deleted Events, 
3. execute a directory delete in an ADLS container to trigger event to enter the queue

### Environment

.NET Core SDK (reflecting any global.json):
 Version:   3.1.302
 Commit:    41faccf259

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.302/

Host (useful for support):
  Version: 3.1.13
  Commit:  64df28ec4a

.NET Core SDKs installed:
  3.1.302 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.13 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @ras-relativity,
Looks like you are correct. The swagger says it is a boolean but it is actually a string - https://github.com/Azure/azure-rest-api-specs/blob/3dd1ef06b272160a4a0276a055b2c1ba0d422038/specification/eventgrid/data-plane/Microsoft.Storage/stable/2018-01-01/Storage.json#L168

We will need to correct the swagger and release a new version of the SDK.
