### ISSUE TITLE
[QUERY] Equivalent of Microsoft.ServiceBus.ServiceBusEnvironment

### ISSUE THREAD

**Issue by arunprakashn** [Azure/azure-sdk-for-net#25946]
### Library name and version

Azure.Messaging.Servicebus 7.5.1

### Query/Question

What is the Equivalent of "Microsoft.ServiceBus.ServiceBusEnvironment" in the new SD "Azure.Messaging.Servicebus 7.5.1"
https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.servicebusenvironment?view=azure-dotnet

### Environment

.net 4.8 and net core 3.1

**Comment by jsquire** [comment]
Hi @arunprakashn.  The class that you're asking about appears to be dedicated to creating connection strings to use with the legacy client.   There is no equivalent, as the current generation of the Service Bus client library supports connection strings only in the form that the Azure portal surfaces them.    

For common scenarios where connection strings were manipulated for the legacy package, you'll typically be using one of credential types.  For example, when using a SAS token, you'd make use of the [AzureSasCredential](https://docs.microsoft.com/dotnet/api/azure.azuresascredential?view=azure-dotnet) class.

```csharp
var credential = new AzureSasCredential("<< SHARED ACCESS KEY STRING >>");
var fullyQualifiedNamespace = "<< NAMESPACE (likely similar to {your-namespace}.servicebus.windows.net) >>";

await using var client = new ServiceBusClient(fullyQualifiedNamespace, credential);

// ...
```

The same is true for using a [managed identity](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#managed-identity-support) and other types of [service principals](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#authenticating-service-principals).

If you're able to help us understand your specific scenario, we'd be happy to offer thoughts on the equivalent way to accomplish it using the `Azure.Messaging.ServiceBus` package.

**Comment by arunprakashn** [comment]
Thank you @jsquire. Appreciate your swift response.

**Comment by arunprakashn** [comment]
Hi @jsquire ,
I see that the usage is described as below in my current legacy code,
```
            ServiceBusEnvironment.SystemConnectivity.Mode = _serviceBusHelper.GetConnectivityMode(_agentFeatureSettings.ServicebusConnectionMode);
```
There are 4 connectivity modes as per the legacy documentation. If I need to realize them in the current new version, how should I go about it? what are the settings/connection-strings to be used? Could you please help with code snippet?

**Comment by jsquire** [comment]
Hi @arunprakashn.   Looking at the [SystemConnectivityMode](https://docs.microsoft.com/dotnet/api/microsoft.servicebus.connectivitymode?view=azure-dotnet), there is no direct equivalent for each of those members.   Support for the legacy NetMessaging protocol was sunset and is not present in the last two generations of client libraries.   All connections to Service Bus make use of the AMQP protocol, and may be configured for direct TCP (default) or via web sockets (useful when a proxy is needed.)    This configuration is specified as part of the [ServiceBusClientOptions](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusclientoptions?view=azure-dotnet) passed to the client, using its `TransportType` property.    For example:

```csharp
var options = new ServiceBusClientOptions
{
    TransportType = ServiceBusTransportType.AmqpWebSockets
};

await using var client  = new ServiceBusClient("<< CONNECTION STRING >>", options);
```
