### ISSUE TITLE
[BUG] Excessive logging when using eventhub trigger/binding in azure function

### ISSUE THREAD

**Issue by lazyruss** [Azure/azure-sdk-for-net#25945]
### Library name and version

Microsoft.Azure.Functions.ExtensionBundle 3.3.0

### Describe the bug

I've upgraded to Azure Function Host v4 and ExtensionBundle v3.3.0
function is written in Javascript and uses EventHub trigger + output binding.
when logging levels set in host.json to "Information", as before, I observe huge amount of logging related to eventhub host operation, such as checkpoints, locks, etc. 
logging is defined in host.json as
```
   "logging": {
      "fileLoggingMode": "always",
      "logLevel": {
        "default": "Information",
        "Host": "Information",
        "Function": "Information",
        "Host.Aggregator": "Information"
      }
    }

```
suppressing logging from certain assemblies as was suggested for asp.net code, ie by adding
```     "Azure.Messaging.ServiceBus": "Error",
        "Azure.Messaging.EventHubs": "Error",
        "Azure.Storage.Blobs": "Error"

 ```
does not help.

### Expected behavior

i dont expect debug logging from sdk components when default logging level is set to "Information"

### Actual behavior

extremely verbose logging about every http request to blob storage, probably to other resources as well.

### Reproduction Steps

create and execute eventhub triggered azure function in javascript

### Environment

azure Function Runtime Version: 4.0.1.16815 running locally in windows 10

**Comment by JoshLove-msft** [comment]
The storage request information is actually being logged by Azure.Core, so I think you'd need to "Azure.Core": "Error", or just "Azure": "Error" to cover all Azure.* assemblies.
