### ISSUE TITLE
[FEATURE REQ] PurviewMetadataPolicyClient Get the metadata policy of the collection by using the collection name

### ISSUE THREAD

**Issue by marvinbuss** [Azure/azure-sdk-for-net#25951]
### Library name

Azure.Analytics.Purview.Administration

### Please describe the feature.

It would be great if you could add support for this API:

[Get the metadata policy of the collection by using the collection name](https://docs.microsoft.com/en-us/azure/purview/tutorial-metadata-policy-collections-apis#get-the-metadata-policy-of-the-collection-by-using-the-collection-name)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
