### ISSUE TITLE
[BUG] Overflow problem for table entity serialization / deserialization

### ISSUE THREAD

**Issue by allxiao** [Azure/azure-sdk-for-net#25968]
### Library name and version

Azure.Data.Tables 12.3.0

### Describe the bug

A ulong property `Prop=value` will be converted to the following odata payload (both for `TableEntity` and `ITableEntity` implementations):

```
{
    "Prop" = value.ToString(),
    "Prop@odata.type" = "Edm.Int64",
}
```

This will hit problem when the `ulong` value exceeds the range of `long`, e.g., `0xFFFF_FFFF_FFFF_FFFFUL` (same binary representation as `-1L`). 

### Expected behavior

ulong should not be treated as long by default in the persistent library.

### Actual behavior

ulong is converted to long, which may trigger overflow exception.

### Reproduction Steps

The following code sample results in 400 Bad Request:

```csharp
TableClient table = ...;
var entity = new TableEntity("p", "r") {
    ["Value"] = 0xFFFF_FFFF_FFFF_FFFFUL,
};
table.AddEntity(entity);
```

### Environment

N/A

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @allxiao 
The table service does not support properties of type ulong. 

However, I suppose you could work around this by down casting to long when sending the value to the service and upcasting when retrieving the value.

```c#
long longval =  unchecked((long)0xFFFF_FFFF_FFFF_FFFFUL);
var ulongEntity = new TableEntity("p", "r")
{
	["Value"] = longval,
};
table.AddEntity(ulongEntity);
TableEntity roundTripped = table.GetEntity<TableEntity>("p", "r");
ulong ul = (ulong)roundTripped.GetInt64("Value");
Console.WriteLine(ul.ToString()); // 18446744073709551615
```

**Comment by allxiao** [comment]
Hi @christothes , yes, Azure Storage Table does not support ulong. However, in the SDK source code, we have several places trying to treat ulong as long, which is misleading and may cause overflow problem and reject by the Azure Storage Table without meaningful error message.

e.g.:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/src/Extensions/DictionaryTableExtensions.cs#L40
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/src/Extensions/TablesTypeBinder.cs#L39

**Comment by christothes** [comment]
Hi @allxiao - thanks for the feedback about the error message. We'll take a look at how this could be improved without violating our design guidelines around implementing client side validation that could change on the service side.
