### ISSUE TITLE
[QUERY] How to implement AcknowledgeAsync and CompleteAsync ?

### ISSUE THREAD

**Issue by arunprakashn** [Azure/azure-sdk-for-net#25971]
### Library name and version

Azure.Messaging.Servicebus 7.5.1

### Query/Question

While migrating from legacy service bus SDK, i noticed two methods AcknowledgeAsync and CompleteAsync. How do I implement/realize them in the latest SDK?

Reference Links:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queueclient.abandonasync?view=azure-dotnet
https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queueclient.completeasync?view=azure-dotnet

### Environment

.net 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
I think you are referring to Abandon/Complete. Please take a look at our README samples:
- [Complete](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus#complete-a-message)
- [Abandon](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus#abandon-a-message)
