### ISSUE TITLE
[QUERY] How can I specify BOTH lease Id and `overwrite=true` in `BlobClient.UploadAsync`

### ISSUE THREAD

**Issue by atsapura** [Azure/azure-sdk-for-net#25972]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Query/Question

There's an overload with `bool overwrite` and there's one with `BlobUploadOptions` which can be used to set conditions with lease.
I need to do both at once, how can I do that? If I specify only lease id, I get exception, that Blob already exists

**Comment by golfalot** [comment]
I have same question. Suggestion is to use specialized BlockBlobClient but I've not yet attempted. 
https://stackoverflow.com/questions/71428072/how-to-set-overwrite-in-azure-blobclient-when-using-blobuploadoptions?noredirect=1#comment126252078_71428072
