### ISSUE TITLE
[QUERY] How to support geo-redundant stores for tables, blobs, queues

### ISSUE THREAD

**Issue by Hossam-Hazem** [Azure/azure-sdk-for-net#26006]
### Library name and version

Azure.Storage.Blobs 12.10.0, Azure.Data.Tables 12.3.0

### Query/Question

Hi all,

I am currently migrating from v11 to v12 and cant find enough resources on supporting geo-redundancy options.

For v11 we are using LocationMode Enum which we explicitly mention LocationMode.PrimaryThenSecondary which activates the secondary endpoint on retries.

I am finding it hard to achieve the same thing using the new SDK for Blobs and tables (I assume it will be the same thing for queues)

Even the docs for blobs don't mention anything for SDK v12  for supporting secondary endpoints
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-create-geo-redundant-storage?tabs=dotnet

Thanks in advance

**Comment by amishra-dev** [comment]
Hi @Hossam-Hazem,
We are aware of this feature request. its in our feature backlog, we will get to it in the coming year.

**Comment by jaschrep-msft** [comment]
Consolidating issue clones. This issue is being tracked in #21445. Closing this issue.
