### ISSUE TITLE
Resource Manager pipeline doesn't check out Core session records

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#26005]
The resource manager pipeline runs the Azure.Core tests, but it no longer checks out the core session records as of https://github.com/Azure/azure-sdk-for-net/pull/25983

This causes a test failure for [HasValidVersion](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/core/Azure.Core/tests/ClientTestBaseMultiVersionTestsWithSpecificVersions.cs#L31) whether test-proxy is enabled or not.

**Comment by JoshLove-msft** [comment]
See if this is still an issue, otherwise close.

**Comment by annelo-msft** [comment]
Moving recordings out of the repo made this obsolete.
