### ISSUE TITLE
[QUERY] How to enable security policy at server level to send the Audit Logs to event hub

### ISSUE THREAD

**Issue by prakashr1979** [Azure/azure-sdk-for-net#26002]
### Library name and version

Microsoft.Azure.Management.Sql.Fluent

### Query/Question

I have used below code create Sql server resource and i would like enable the security policy at server level and send the corresponding Audit logs to event hub.  I googled lots of places: Microsoft.com, github etc., even reading through the source code of the Azure sdk (.net), could not find out any implementation in this Fluent (Microsoft.Azure.Management.Sql.Fluent) library to enable the security policy and send the audit log thru programmatically.

Could you please help on this, Also please let me know if you need more details about this.

 var builder = azure.SqlServers
                    .Define(resource.Name)
                    .WithRegion(resource.Location)
                    .WithExistingResourceGroup(resourceGroup.Name)
                    .WithAdministratorLogin(SqlServerLoginName)
                    .WithAdministratorPassword(SqlServerLoginPassword)
                    .WithTags(resource.Tags);

var sqlServer = await builder.CreateAsync(CancellationToken.None);                    

### Environment

.NET SDK (reflecting any global.json):
 Version:   5.0.203
 Commit:    383637d63f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.203\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment]
Microsoft.Azure.Management.Sql.Fluent provide a class [ExtendedServerBlobAuditingPoliciesOperations.cs](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Sql/Generated/ExtendedServerBlobAuditingPoliciesOperations.cs) to operating Audit logs in server.

``` c# 
using Microsoft.Azure.Management.ResourceManager.Fluent;
using Microsoft.Azure.Management.ResourceManager.Fluent.Authentication;
using Microsoft.Azure.Management.Sql.Fluent;
using Microsoft.Azure.Management.Sql.Fluent.Models;
using System;
using System.Threading.Tasks;
```

#### Get server audit log infomation:
``` c#
string clientId = "";
string clientSecret = "";
string tenantId = "";
string subscription = "";
string resourceGroupName = "";
string serverName = "";

var creds = new AzureCredentialsFactory().FromServicePrincipal(clientId, clientSecret, tenantId, AzureEnvironment.AzureGlobalCloud);
var sqlManager = SqlManager.Authenticate(creds, subscription);
SqlManagementClient client = new SqlManagementClient(sqlManager.RestClient);
client.SubscriptionId = subscription;
var policy = await client.ExtendedServerBlobAuditingPolicies.GetWithHttpMessagesAsync(resourceGroupName, serverName);
Console.WriteLine($"{serverName} state: "+policy.Body.State);
```

#### Update server audit log, let it link to a storage account:
``` c#
ExtendedServerBlobAuditingPolicyInner parameters = new ExtendedServerBlobAuditingPolicyInner()
{
    State = BlobAuditingPolicyState.Enabled,
    StorageEndpoint = "https://[YOUR-STORAGE-ACCOUNT].blob.core.windows.net/",
    StorageAccountAccessKey = "[YOUR-STORAGE-ACCOUNT-ACCESS-KEY]",
};
var response = await client.ExtendedServerBlobAuditingPolicies.CreateOrUpdateWithHttpMessagesAsync(resourceGroupName, serverName, parameters);
Console.WriteLine($"{serverName} state: " + response.Body.State);
```
The current version does not provide the ability to programmatically link to the Event hubs, as model's [summary](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Sql/Generated/Models/ExtendedServerBlobAuditingPolicyInner.cs#L301) say.
This issue will add [service attention] label.

More Information:
- Method:  CreateOrUpdateWithHttpMessagesAsync [source-code](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Sql/Generated/ExtendedServerBlobAuditingPoliciesOperations.cs#L268) . [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/tableAuditing.json#L58)
- Model: ExtendedServerBlobAuditingPolicyInner [source-code](https://github.com/Azure/azure-libraries-for-net/blob/master/src/ResourceManagement/Sql/Generated/Models/ExtendedServerBlobAuditingPolicyInner.cs#L183) . [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/stable/2014-04-01/databaseSecurityAlertPolicies.json#L186)
