### ISSUE TITLE
[FEATURE REQ] Add model representation for the FailActivity from ADF

### ISSUE THREAD

**Issue by GFernandesS** [Azure/azure-sdk-for-net#26016]
### Library name

Microsoft.Azure.Management.DataFactory

### Please describe the feature.

Currently we have in this client a set of types to represent the different ADF activities, however, we don't have any that specifically represents the **_FailActivity_**, It would be interesting to have it implemented, as it's theoretically a simple implementation.. 
This implementation would be interesting for a dynamic pipeline creation project I'm developing where I need to represent activity types within .NET

**Comment by archerzz** [comment]
@GFernandesS We need to wait for the service team to update SDK, because `FailActivity` was added on Jan 6, 2022: https://github.com/Azure/azure-rest-api-specs/pull/17189

**Comment by Frey-Wang** [comment]
Hi @GFernandesS , the next update will be early Feb. We'll notice you then once completed.

**Comment by Frey-Wang** [comment]
Hi @GFernandesS , the SDK for .NET has been published here: https://www.nuget.org/packages/Microsoft.Azure.Management.DataFactory.
