### ISSUE TITLE
Published SDK packages does not work in UWP/Xamarin/Mobile apps

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-sdk-for-net#2601]
following error is reported when Fluent API Nuget Packages is referenced in Xamarin.Forms application. Happens while blank new app is created then updated the already installed packages, build the app and then tried to add these packages. 

**Could not install package 'Microsoft.Azure.Management.Fluent 1.0.0-beta3'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**

Same error is reported for AutoRest generated packages.

**Comment by twitchax** [comment]
The .NET client libraries for Azure will be transitioning to .NET Standard 1.3 by mid-February.

[.NET Standard](https://blogs.msdn.microsoft.com/dotnet/2016/09/26/introducing-net-standard/) 1.3 will support UWP 10.0+, so support for these application types should be implicit in our coming transition.

Closing in favor of #1413.
