### ISSUE TITLE
[QUERY] What is the right way to run a RunCommand? 

### ISSUE THREAD

**Issue by thebernardlim** [Azure/azure-sdk-for-net#26013]
### Library name and version

Azure.ResourceManager.Compute

### Query/Question

Currently I run the RunCommand this way, but it does not work.

`
VirtualMachine testVM = await vmCollection.GetAsync(vmName);
`
`
Azure.ResourceManager.Compute.Models.RunCommandInput cmd = new Azure.ResourceManager.Compute.Models.RunCommandInput("RunPowershellScript");
Azure.ResourceManager.Compute.Models.RunCommandInputParameter cmdInput = new Azure.ResourceManager.Compute.Models.RunCommandInputParameter("Script", "Restart-Service -Name Test");
cmd.Parameters.Add(cmdInput);
testVM.RunCommand(cmd);
`

There is no 'Setter' for `RunCommandInput` as well.

Please advice the correct way to use this. Thanks.

### Environment

OS: Windows 10 
.NET Framework 6
Visual Studio 17.0.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@thebernardlim , this is a common pattern in mgmt. sdk, the `RunCommandInputParameter` is unassignable that the SDK will initialize this property with a built-in List type, and the fact of no-setter could ensure you cannot change the list to another instance. And the usage is add element to it, you can check out more information here: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-collection-read-only-property-initialization .
