### ISSUE TITLE
[QUERY] Update/clarify docs about distributed tracing, inlusion of REDACTED headers.

### ISSUE THREAD

**Issue by Hjortsberg** [Azure/azure-sdk-for-net#26014]
### Library name and version

Azure.Messaging.EventGrid 4.0.7

### Query/Question

Hi, 
I've had trouble with Eventgrid and Azure-support asked me for the `x-ms-request-id` header for the failed requests. 
This header is however REDACTED/not logged in Application Insights so I thought I would include it according to [these docs](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.EventGrid_4.7.0/sdk/core/Azure.Core/samples/Diagnostics.md).

This document talks about how to set the value, which seems to only be get able?
```csharp
    /// <summary>
    /// Gets a list of headers names that are not redacted during logging.
    /// </summary>
    public IList<string> LoggedHeaderNames { get; internal set; }
```
I create the client with only configuration so that I can leverage my AZ CLI login session to authenticate.
```csharp
    EventGridPublisherClientOptions options = new EventGridPublisherClientOptions()
    {
        Diagnostics =
        {
            LoggedHeaderNames = { "x-ms-request-id" },
            LoggedHeaderNames = { "traceparent" }
        }
    };
    services.AddAzureClients(builder =>
    {
       builder.AddEventGridPublisherClient(configuration);
    });
```
The syntax to configure it seems to validate but I get no effect/different behaviour when adding it, how am I supposed to register the Diagnostic options? :)

Regards Philip

### Environment

* Linux, Fedora 35
* Azure Function Version V3, dotnet core 3.1
*  `dotnet --info`
``` 
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     fedora
 OS Version:  35
 OS Platform: Linux
 RID:         fedora.35-x64
 Base Path:   /usr/lib64/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  3.1.118 [/usr/lib64/dotnet/sdk]
  5.0.206 [/usr/lib64/dotnet/sdk]
  6.0.101 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.18 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.18 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Hjortsberg** [comment]
Ok, I've tried that syntax as well but had no luck with it, good to know that's what I should stick with! 👍

Currently I'm not seeing the header key at all, neither in the dist. trace span of AI or in the logs. 
What I've began to wonder is if `x-ms-request-id` has a different display name in AI, causing my confusion?
This is all properties I have in the dist. trace span for the outgoing request to EventGrid
![dependency](https://user-images.githubusercontent.com/17297258/146810214-c673d8cc-78f5-4f67-b7f4-c9f9463295d2.png)

What I want to achieve is to be able to search or trace a request through all systems it touches, using either the x-ms-request-id or the traceparent.

**Comment by pakrym** [comment]
I see. The ClientRequestId corresponds to "x-ms-client-request-id" sent by the client. And ServerRequestId is the "x-ms-request-Id" returned by the service.

**Comment by Hjortsberg** [comment]
Oh, that explains alot. Then I realize my question is not so much about this SDK in particular and more about documentation of how certain headers are displayed in Application Insights.
I think this can be closed then :)

I will have to investigate how to get the traceparent.
Thank you for your answers.
