### ISSUE TITLE
[QUERY] How can I determine when a secret from Key Vault has been purged?

### ISSUE THREAD

**Issue by joelmforsyth** [Azure/azure-sdk-for-net#26027]
### Library name and version

Azure.Security.KeyVault.Secrets 4.2.0

### Query/Question

I have code to restore a key vault secret from a backup. Calling RestoreSecretBackupAsync will return a conflict if the secret exists in the key vault, so I delete the secret first using the following two lines, per the documentation.

```
var operation = await secretClient.StartDeleteSecretAsync(secretName).ConfigureAwait(false);
await operation.WaitForCompletionAsync().ConfigureAwait(false);
```

After the second line returns, I now have to purge the secret. After this, I confirm that the secret is no longer in the key vault by calling both GetSecret and GetDeletedSecret. Both return 404 indicating that the secret is neither active in the vault, nor is it in a deleted state.

Immediately following this I perform the restore with RestoreSecretBackupAsync which fails with a status of 409 Conflict because  the key vault is saying that the secret still exists. The secret is in some limbo state it seems where it is no longer in the deleted state but it hasn't been purged. After waiting anywhere from 1 to 5 seconds, I can restore. I have to do this by repeatedly attempting to restore until it succeeds.

My question: Is there a different way for me to determine if a secret has been completely purged? I would rather not rely on repeatedly failing to complete a restore.

### Environment

.NET 4.7.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Sorry, no. The long-running operations for deleting and restoring resources like secrets actually work by querying for what should exist, but there's no analog for purged resources like secrets. The only way to do so would be to try to create a secret and check the status code, but then the secret exists when purging is done and you're back to square one. You'd have to poll as it seems you're already doing.

**Comment by joelmforsyth** [comment]
> Sorry, no. The long-running operations for deleting and restoring resources like secrets actually work by querying for what should exist, but there's no analog for purged resources like secrets. The only way to do so would be to try to create a secret and check the status code, but then the secret exists when purging is done and you're back to square one. You'd have to poll as it seems you're already doing.

Thanks for your reply, @heaths. 

The other minor thing I mentioned in the issue is that when the secret is changing states (Active > Deleted > Purged) it seems to be in some sort of "limbo" state where polling returns a 404. Even after `WaitForCompletionAsync()` returns, `GetDeletedSecretAsync()` will say the secret is not found. This means even with the polling suggestion I can't immediately trust the results. After waiting about a second the secret will be in the deleted state and I can continue. Since this operation is performed in a web application the response times are growing to an unacceptable level. Is this also by design?

**Comment by heaths** [comment]
I've not seen that. We also poll for deletion so we can kick off a purge and have not seen 404s as a result. Does this happen often for you? If seldom, do you have an activity ID from the application log the service team can review?

/cc @jlichwa from the service team.

I appreciate the polling isn't ideal, but I don't believe such resource management was intended for typical application use, at least, not creation, enumeration, or deletion - mainly retrieving and performing crypto operations against keys. Is your web application some sort of management UI? Perhaps if you explained why you're restoring from backup we could provide some alternative solutions or explore other possibilities.

**Comment by joelmforsyth** [comment]
Thanks for the quick reply, @heaths!

>Does this happen often for you?

It was happening every time, if I recall correctly. I will try to get you more information.

>Is your web application some sort of management UI? Perhaps if you explained why you're restoring from backup we could provide some alternative solutions or explore other possibilities.

Yes, the restore operation is done via a data recovery UI for a SAAS product. We store several different things in key vaults and if the user decides to restore from a backup, they push a button and a background process runs until it is completed. Since this runs behind the scenes as a job, I'm not too concerned about the time aspect here. Where I was encountering the time-sensitive issue is a scenario where a user can delete something (let's say a private API key) and then add it back. We have used set naming conventions for secret names for years but because of the new soft delete requirements, it seems we're going to have to refactor everything to use generated unique names and save them off somewhere so that we don't encounter conflicts. If we do that, I suppose I could just let the deletion continue in the background and trust that it will be taken care of. We can push forward with that unless you have a better suggestion.

**Comment by heaths** [comment]
Thanks for clarifying. Short of polling a little extra or handling the 409 Conflict case with a limited wait + retry loop, I don't really have a better suggestion than unique naming. Resource management operations like this (not to be confused with ARM operations) are queued in the backend. The long-running operations (LROs) we provided were to try to make this easier and idiomatic for other LROs we have like creating certificates, or in lots of other Azure SDKs.

One reason we may not see this is because a while back I refactored our [tests](https://github.com/Azure/azure-sdk-for-net/blob/6dde60e9d50d1fad433f5b6d484bc73d140996a9/sdk/keyvault/Azure.Security.KeyVault.Secrets/tests/SecretsTestBase.cs#L82-L104) to delete ASAP and purge later; though, before that refactoring we basically did delete + purge in succession and I don't recall seeing this.

That said, the number of resources in a Key Vault can make some backend queue operations slower, so if your SaaS offering manages a lot of resources that could be a contributing factor. For typical applications we recommend a Key Vault per application that should reduce the number of resources and lighten the load, but I appreciate that may not work in your situation.

**Comment by joelmforsyth** [comment]
Hey @heaths, 

I just wrote a console app that connects to our development key vault, creates a secret, gets it, deletes it, then gets the deleted secret. There's some authentication stuff I'm not including but here's the code code:

```
var secretName = "MySecretName";
var secretValue = "VerySecretValue";
var secret = new KeyVaultSecret(secretName, secretValue);

var secretClient = clientFactory.GetSecretClientAsync().ConfigureAwait(false).GetAwaiter().GetResult();

var setSecret = secretClient.SetSecretAsync(secret).ConfigureAwait(false).GetAwaiter().GetResult();

var getSecret = secretClient.GetSecretAsync(setSecret.Value.Name).ConfigureAwait(false).GetAwaiter().GetResult();

var deleteOperation = secretClient.StartDeleteSecretAsync(secretName).ConfigureAwait(false).GetAwaiter().GetResult();
deleteOperation.WaitForCompletionAsync().ConfigureAwait(false);

var deletedSecret = secretClient.GetDeletedSecretAsync(deleteOperation.Value.Name).ConfigureAwait(false).GetAwaiter().GetResult();
```

Here's the error response I get back:

```
Deleted Secret not found: MySecretName
Status: 404 (Not Found)
ErrorCode: SecretNotFound

Content:
{"error":{"code":"SecretNotFound","message":"Deleted Secret not found: MySecretName"}}

Headers (modified):

x-ms-client-request-id: 4257e401-6d8e-4df0-98df-48c1316dd554
x-ms-request-id: 79d9d27d-471e-41a7-ab8f-e1d2e09b517a
x-ms-keyvault-service-version: 1.9.226.1

Date: Tue, 04 Jan 2022 21:48:41 GMT

```

If I run it again later I get the conflict on setting the secret.

```
Secret MySecretName is currently in a deleted but recoverable state, and its name cannot be reused; in this state, the secret can only be recovered or purged.
Status: 409 (Conflict)
ErrorCode: Conflict

Content:
{"error":{"code":"Conflict","message":"Secret MySecretName is currently in a deleted but recoverable state, and its name cannot be reused; in this state, the secret can only be recovered or purged.","innererror":{"code":"ObjectIsDeletedButRecoverable"}}}

Headers:

x-ms-client-request-id: 0bea57d8-278d-44f4-843b-eddd3f22cfa8
x-ms-request-id: 69437370-6c46-40c5-bd76-30298f9b8d5e
x-ms-keyvault-service-version: 1.9.226.1

Date: Tue, 04 Jan 2022 22:00:04 GMT
```

**Comment by joelmforsyth** [comment]
Thanks for your time and effort @heaths!
