### ISSUE TITLE
[BUG]Can't delete empty container with an immutable policy configured

### ISSUE THREAD

**Issue by sdandu21** [Azure/azure-sdk-for-net#26026]
### Library name and version

Microsoft.Azure.Storage.Blob v11.1.0

### Describe the bug

According to the docs and in the portal you can delete a container with an unlocked/locked immutable policy if there are no blobs in the container anymore (i.e. empty container). 

However, when I call container.DeleteIfExistsAsync() on an empty container I get the following exception: 
![image](https://user-images.githubusercontent.com/89872288/146989591-38d53e1b-fdeb-431a-a0e8-d4df6ccd0974.png)

### Expected behavior

container.DeleteIfExistsAsync(); should delete the container as long as none of the blobs within it are covered by the policy or if it is an empty container

### Actual behavior

Throws the following error 
![image](https://user-images.githubusercontent.com/89872288/146989740-d6a929bf-6457-4f24-9062-2b7acab7c7cf.png)

### Reproduction Steps

   var account = new CloudStorageAccount(accountSAS, accountName, "core.windows.net", useHttps: true);
   var blobClient = account.CreateCloudBlobClient();
   var container = blobClient.GetContainerReference(containerName);
   await container.FetchAttributesAsync();
   await container.DeleteIfExistsAsync();

### Environment

.NET runtime

**Comment by dterei** [comment]
Facing the same issue -- not sure if it's an SDK problem, I'm using the legacy Python SDK (https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.baseblobservice.baseblobservice?view=azure-python-previous#delete-container-container-name--fail-not-exist-false--lease-id-none--if-modified-since-none--if-unmodified-since-none--timeout-none-).

I can delete the empty container from the Azure portal without issue, but can't delete it through the SDK...

**Comment by amishra-dev** [comment]
@sdandu21 thanks for reporting the issue, can you please confirm if you ever set the immutability policy?
V11 SDK is deprecated, but i will try this out with V12 and let you know what i find.

**Comment by amishra-dev** [comment]
> Facing the same issue -- not sure if it's an SDK problem, I'm using the legacy Python SDK (https://docs.microsoft.com/en-us/python/api/azure-storage-blob/azure.storage.blob.baseblobservice.baseblobservice?view=azure-python-previous#delete-container-container-name--fail-not-exist-false--lease-id-none--if-modified-since-none--if-unmodified-since-none--timeout-none-).
> 
> I can delete the empty container from the Azure portal without issue, but can't delete it through the SDK...

@dterei Hi David, could you kindly file an issue https://github.com/Azure/azure-sdk-for-python/issues/new/choose and tag me, i will get someone to look into it.
Same question for you though, did you set an immutability policy when you tried this? /cc @tasherif-msft

**Comment by sdandu21** [comment]
Hi, yes I have set the policy. I don't see v12 for this package?

**Comment by amishra-dev** [comment]
> Hi, yes I have set the policy. I don't see v12 for this package?

https://www.nuget.org/packages/Azure.Storage.Blobs/

**Comment by sdandu21** [comment]
Thank you. Please let me know if this is the same scenario with v12

**Comment by tasherif-msft** [comment]
Hi @dterei, I was able to reproduce this in Python v12. I have created an issue for it here: https://github.com/Azure/azure-sdk-for-python/issues/22255

@sdandu21 could you provide me the docs you referenced in the issue that state that we can delete an empty container when immutability policy is set? 

Thank you!

**Comment by amishra-dev** [comment]
@dterei / @sdandu21 I had a chat with the owners of the Immutable policy and they are telling me that the safe way to delete a container with immutability policy is to use the management plane SDK and the use the delete container from there, could you folks kindly try that?

**Comment by sdandu21** [comment]
I was referring to the docs on immutability policy that mention that we can't delete the container if there is a blob in it indicating that container deletes are permitted if it's empty. This is also the same behavior we see in the portal.
[https://docs.microsoft.com/en-us/azure/storage/blobs/immutable-storage-overview](url)

**Comment by amishra-dev** [comment]
> I was referring to the docs on immutability policy that mention that we can't delete the container if there is a blob in it indicating that container deletes are permitted if it's empty. This is also the same behavior we see in the portal. https://docs.microsoft.com/en-us/azure/storage/blobs/immutable-storage-overview

Portal uses the delete operation from the management plane SDK, could you try that?

**Comment by sdandu21** [comment]
Ya I can try that in a sample code to see if it works. 

Will there be any support for this scenario in this SDK in the future as it wouldn't really make sense for our service to use the management plane storage sdk for this one particular scenario when the rest of our code base uses Microsoft.Azure.Storage.Blob.

**Comment by dterei** [comment]
@amishra-dev, @tasherif-msft Thank you both! Great to see this level of support :)

Yes, independently I also figured out that you can delete the container but you **must** use the ARM API to do so if there is an immutability policy set. The storage API fails.

While the difference in behavior between the APIs is a little odd, it's fine. Could you please update the documentation please though for the APIs here to let people know that the ARM API must be used? Knowing this in advance would have saved about 1--2 days of investigation on my part before I figured this out.
