### ISSUE TITLE
CloudTable.CreateIfNotExists return value is not clear

### ISSUE THREAD

**Issue by bz-wow** [Azure/azure-sdk-for-net#26021]
[Enter feedback here]
In the doc, the return value description is "true if table was created; otherwise, false.", however how about the table already exists and is not created by this method? Does it returns false if table exists and is not created by this method?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2eff4810-091d-296f-a5db-38cc8f6528d0
* Version Independent ID: 04604b36-ec55-e14e-d7c8-eb2ad1deb1d1
* Content: [CloudTable.CreateIfNotExists Method (Microsoft.Azure.Cosmos.Table) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.cloudtable.createifnotexists?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos.Table/CloudTable.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos.Table/CloudTable.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@bz-wow That is correct. If the table was created by this method call, it returns `true` and the other case where it is not created because it already exists, it returns `false`.

**Comment by PramodValavala-MSFT** [comment]
@bz-wow Just following up here... Hope my previous comment clears things up.

**Comment by PramodValavala-MSFT** [comment]
@bz-wow Hope my previous comment clears things up.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
