### ISSUE TITLE
[QUERY] how to set UserAgent, RetryPolicy and handler for Azure.ResourceManager.ArmClient

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/azure-sdk-for-net#26034]
### Library name and version

Azure.ResourceManager 1.0.0-beta.6

### Query/Question

Could you please let me the way to set UserAgent, RetryPolicy and handler for Azure.ResourceManager.ArmClient?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Had a offline sync with @archerzz , so close this issue.
