### ISSUE TITLE
[BUG] ResourceManager - Subscription Id and Name/DisplayName fields mapped incorrectly

### ISSUE THREAD

**Issue by cjbhaines** [Azure/azure-sdk-for-net#26032]
### Library name and version

Azure.ResourceManager 1.0.0-beta.6

### Describe the bug

The Subscription response has the Id and Name/DisplayName fields mapped the wrong way around. 

### Expected behavior

The fields are mapped correctly.

### Actual behavior

Issues:

- Name is actually the SubscriptionGuid
- DisplayName is actually the SubscriptionGuid
- SubscriptionGuid is the Name

![image](https://user-images.githubusercontent.com/3225747/147017031-3bc31458-9864-4463-8c7e-75368e64ef14.png)

### Reproduction Steps

```
var resourceManagerClient = new ArmClient(new DefaultAzureCredential());
await foreach (var subscription in resourceManagerClient.GetSubscriptions().GetAllAsync(cancellationToken))
{
  // Do something here
}
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by brianstringfellow** [comment]
Appears to have been fixed in Azure.ResourceManager v1.0.0-beta.7.
https://github.com/Azure/azure-sdk-for-net/pull/25807
