### ISSUE TITLE
QueueTrigger failed to decoding message in .Net 6

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-sdk-for-net#26049]
### Library name and version

Azure.Storage.Queues - 12.8.0

### Query/Question

I have a Azure Web with a Queue Trigger which doesn't succeed to read the message added in the Azure Queue giving this error message:

> Message decoding has failed! Check MessageEncoding settings

Program.cs:

    var host = CreateHostBuilder(args).Build();
    
    using var scope = host.Services.CreateScope();
    var services = scope.ServiceProvider;
    var logger = services.GetRequiredService<ILogger<Program>>();
    
    using (host)
    {
        host.Run();
    }
    
    
    static IHostBuilder CreateHostBuilder(string[] args = null) => new HostBuilder()
        .ConfigureHostConfiguration(configHost =>
        {
            configHost.SetBasePath(Directory.GetCurrentDirectory());
            configHost.AddJsonFile("hostsettings.json", optional: true);
            configHost.AddEnvironmentVariables();
            configHost.AddCommandLine(args);
        })
        .ConfigureWebJobs(webJobConfiguration =>
        {
            webJobConfiguration.AddAzureStorageCoreServices();
            webJobConfiguration.AddTimers();
            webJobConfiguration.AddAzureStorageQueues();
        })
        .ConfigureAppConfiguration((hostContext, configApp) =>
        {
            var env = hostContext.HostingEnvironment;
            configApp.AddJsonFile("appsettings.json", optional: true);
            configApp.AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);
            configApp.AddEnvironmentVariables();
            configApp.AddApplicationInsightsSettings(developerMode: !env.IsProduction());
        })
        .UseServiceProviderFactory(new AutofacServiceProviderFactory())
        .ConfigureServices((hostContext, services) =>
        {
            var configuration = hostContext.Configuration;
    
            //Settings 
            services.ConfigureAndValidate<MessagerSettings>(configuration);
            services.ConfigureAndValidate<QueueSettings>(configuration);
           //(ConfigureAndValidate is a custom extension, ignore it)
        })
        .ConfigureContainer<ContainerBuilder>(builder =>
        {
            builder.RegisterModule<MessagerModule>();
        })
        .ConfigureLogging((hostContext, configLogging) =>
        {
            configLogging.AddApplicationInsightsWebJobs(c =>
                c.InstrumentationKey = hostContext.Configuration["ApplicationInsights:InstrumentationKey"]
            );
            configLogging.AddAzureWebAppDiagnostics();
        })
        .UseConsoleLifetime();

Triggers:

    public async Task QueueMessageAsync(
                [TimerTrigger("%Messager:MessageQueuerOccurence%", RunOnStartup = true)] TimerInfo timer
            )
            {
                var processStartTime = DateTimeOffset.Now;
                try
                {
                    // Get Task to reminder until now
                    _logger.LogInformation($"Queue new Message.");
                    var message = await _operationsQueueService.QueueMessageAsync(
                        new Message()
                        {
                            Title = "Bonjour",
                            Description = "Comment vas-tu?"
                        }
                    );
    
                    _logger.LogMetric($"{nameof(QueueMessageAsync)}-MessageSent", 1);
                    _logger.LogInformation($"New Message queued", message);
                }
                catch (Exception e)
                {
                    _logger.LogError(e.Message, e);
                }
                _logger.LogMetric($"{nameof(QueueMessageAsync)}-TotalExecutionTime", (DateTimeOffset.Now - processStartTime).TotalMilliseconds);
            }
    
    
            public async Task ReceiveMessageAsync(
                [QueueTrigger("%operations-message%")] Message message // I tried object or string instead of Message too
            )
            {
                var processStartTime = DateTimeOffset.Now;
                try
                {
                    _logger.LogMetric($"{nameof(QueueMessageAsync)}-MessageReceived", 1);
                    _logger.LogInformation($"Message received.", message);
                    // Do operations
                    _logger.LogMetric($"{nameof(QueueMessageAsync)}-MessageReceivedSuccess", 1);
                }
                catch (Exception ex)
                {
    
                    _logger.LogMetric($"{nameof(QueueMessageAsync)}-MessageReceivedFailed", 1);
                    _logger.LogError(ex.Message, ex);
                }
                _logger.LogMetric($"{nameof(ReceiveMessageAsync)}-TotalExecutionTime", (DateTimeOffset.Now - processStartTime).TotalMilliseconds);
            }
    
OperationsQueueService:
    
            public async Task<T> QueueMessageAsync([NotNull] T message, TimeSpan? visibilityTimeout = null)
            {
                var queueClient = GetQueueClient("operations-message");
                await queueClient.SendMessageAsync(
                    new BinaryData(message.ToJson()), // I tried message.ToJson() too
                    visibilityTimeout
                );
                _logger.LogInformation($"A new message has been queued.", message);
                return message;
            }
            private QueueClient GetQueueClient(string queueName)
            {
                return new QueueClient(
                    _queueSettings.ConnectionString,
                    queueName,
                    new QueueClientOptions
                    {
                        MessageEncoding = QueueMessageEncoding.Base64 // I tried None too
                    }
                );
            }

Extensions:

        public static string ToJson(this object obj)
        {
            var token = JToken.FromObject(obj, new JsonSerializer() { ReferenceLoopHandling = ReferenceLoopHandling.Ignore });
            return token.ToString();
        }

I added in hostsettings.json these settings, but it seems not taken by the Webjob as it continues to write try 5 times instead of 8 times before putting in Poison queue.
 

     "extensions": {
        "queues": {
          "maxPollingInterval": "00:00:02",
          "visibilityTimeout": "00:00:30",
          "batchSize": 16,
          "maxDequeueCount": 8,
          "newBatchThreshold": 8,
          "messageEncoding": "none"
        }
      }

Error:
[![enter image description here][1]][1]

How to be able to send a message to a Queue and be able to read it with the QueueTrigger?

  [1]: https://i.stack.imgur.com/RREAt.png

Stackoverflow: https://stackoverflow.com/posts/70467314

### Environment

 - .Net 6
 - Microsoft.Azure.WebJobs => 3.0.30
 - Microsoft.Azure.WebJobs.Extensions => 4.0.1
 - Microsoft.Azure.WebJobs.Extensions.Storage => 5.0.0
 - Microsoft.Azure.WebJobs.Extensions.Storage.Queues => 5.0.0
 - Microsoft.Azure.WebJobs.Host.Storage => 4.0.4
 - Microsoft.Azure.WebJobs.Logging.ApplicationInsights => 3.0.30
 - Microsoft.Extensions.Hosting => 6.0.0
 - Microsoft.Extensions.Logging => 6.0.0
 - Microsoft.Extensions.Logging.AzureAppServices => 6.0.1
 - Azure.Storage.Queues => 12.8.0

**Comment by ranouf** [comment]
The code is correct, I forgot to update my own nuget package

**Comment by robertmclaws** [comment]
@ranouf I'm dealing with the same issue now. How did you fix it? Thanks!
