### ISSUE TITLE
How can I find a place where is Outgoing connection is not closed in az func dotnet isolated? [QUERY]

### ISSUE THREAD

**Issue by tkachuk2222** [Azure/azure-sdk-for-net#26046]
### Library name and version

Microsoft.Azure.ServiceBus 5.1.3

### Query/Question

I have azure functions project. I have service bug trigger and time trigger azure functions. some of them, I don't know which ones, don't close outgoing connection. How can I find a problem?

when I use creating MessageReceiver - in the end of code execution I do closing connection calling next method:
```csharp
       private async Task CloseMessageReceiverAsync(MessageReceiver messageReceiver)
        {
            if (messageReceiver != null && !messageReceiver.IsClosedOrClosing)
            {
                await messageReceiver.CloseAsync();
            }
        }
```

When I use service bus trigger azure function - in case of needs I throw Exception for sending a message to the dead letter queue (in the dotnet-isolated azure function is not possible to send incoming queue from the queue to the dead letter queue)
example of throwing an exception:
```csharp
                else
                {
                    log.LogInformation($"No free slots. Abandoned. Lock token: {lockToken}");
                    throw new Exception("No free slots.");
                }
```

screen from the azure portal (azure function -> TCP Connections):
![image](https://user-images.githubusercontent.com/20381930/147247270-bedfb262-ae20-45be-83eb-6bf449e480a1.png)

### Environment

.NET 5.0
dotnet-isolated
function runtime version: 3
NuGet packages I use:
```xml
 <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.1" />
    <PackageReference Include="Azure.Identity" Version="1.4.1" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.2.1" />
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.2.0" />
    <PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.2.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.1.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.0.4" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.5.1" />
    <PackageReference Include="Microsoft.Azure.ServiceBus" Version="5.1.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
  </ItemGroup>
```

**Comment by PramodValavala-MSFT** [comment]
@tkachuk2222 First, it would be best to check which service the IPs belong to from the [IP Ranges JSON](https://www.microsoft.com/en-us/download/details.aspx?id=56519) (or you the [Azure IP Lookup tool](https://www.azurespeed.com/Azure/IPLookup)). In your case, the last 3 rows seem to be with AzureAD.

It would be best to check which objects you create for each request. [Including `MessageReceiver`](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk#reusing-factories-and-clients), it is likely that you could just use reuse object instances for most.

**Comment by PramodValavala-MSFT** [comment]
@tkachuk2222 Just following up here... Hope my previous comment helps
