### ISSUE TITLE
IDW10502: An MsalUiRequiredException was thrown due to a challenge for the user

### ISSUE THREAD

**Issue by AABhatt** [Azure/azure-sdk-for-net#26043]
I have set HttpContext.User = ClaimsPrincipalFactory
                            .FromTenantIdAndObjectId(tenantid,objectid);

but while getting token with await _tokenAcquisition.GetAccessTokenForUserAsync(scope) it throws error.
Inner exception message like 'No account or login hint was passed to the AcquireTokenSilent call'

Could you please help me in that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0da47a33-a7c4-b9b1-ea3a-2affbd28f934
* Version Independent ID: 6ef44932-a58a-dffc-8110-aec362c9695c
* Content: [ClaimsPrincipalFactory.FromTenantIdAndObjectId(String, String) Method (Microsoft.Identity.Web) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.claimsprincipalfactory.fromtenantidandobjectid?view=azure-dotnet)
* Content Source: [xml/Microsoft.Identity.Web/ClaimsPrincipalFactory.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Web/ClaimsPrincipalFactory.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Identity.Web` package is maintained as [#1568](https://github.com/AzureAD/microsoft-identity-web/issues/1568).
