### ISSUE TITLE
"Returns" content misleading.

### ISSUE THREAD

**Issue by itaibh** [Azure/azure-sdk-for-net#26045]
The "Returns" section states the following:

```
A Response Returns true if container exists and was deleted, return false otherwise.
```

I think it's a bit misleading, since the method only returns `false` if the container was already Garbage-Collected and not if it's only marked for deletion, in which case it returns 'true'.

This can be shown by this code:

```
[Test]
public void TestBlobContainerDeletion()
{
    string storageAccount = "connection string";
    string containerName = "deleteme";

    var client = new BlobServiceClient(storageAccount);
    var container = client.GetBlobContainerClient(containerName);
    container.CreateIfNotExists();
    var blob = container.GetBlobClient("k1");
    var options = new BlobUploadOptions();
    var data = BinaryData.FromString("v1");
    blob.Upload(data, options);

    container = client.GetBlobContainerClient(containerName);
    Assert.True(container.Exists());

    container = client.GetBlobContainerClient("nonexisting");
    var response = container.DeleteIfExists();
    Assert.False(response);

    container = client.GetBlobContainerClient(containerName);
    response = container.DeleteIfExists();
    Assert.True(response);
    
    container = client.GetBlobContainerClient(containerName);
    response = container.DeleteIfExists();
    Assert.False(response); // <-- this line fails since it takes over 30 seconds for the container to get garbage collected.

}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac0e0672-bfc7-d843-670c-36668cbdde00
* Version Independent ID: 148a9e0a-ce2c-121f-68bb-95ad2edc9e5c
* Content: [BlobContainerClient.DeleteIfExists(BlobRequestConditions, CancellationToken) Method (Azure.Storage.Blobs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.deleteifexists?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Azure.Storage.Blobs.BlobContainerClient.DeleteIfExists);k(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs/BlobContainerClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs/BlobContainerClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by itaibh** [comment]
BTW - this is a breaking change from `WindowsAzure.Storage`'s `CloubBlobContainer` where it returned `false` in the same scenario.

**Comment by PramodValavala-MSFT** [comment]
@itaibh considering that you can list and [undelete a blob container](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.undeleteblobcontainer?view=azure-dotnet) when it is marked for deletion, I think that is expected. @seanmcc-msft Could you confirm?

**Comment by seanmcc-msft** [comment]
@itaibh, we could probably make the XML comment clearer, indicating that the container has been marked for deletion, and it can take up to 30 seconds for the container deletion to occur.

-Sean
