### ISSUE TITLE
[QUERY] What's the TableQuery equivalent in Azure.Data.Tables that helps build queries?

### ISSUE THREAD

**Issue by allxiao** [Azure/azure-sdk-for-net#26042]
### Library name and version

Azure.Data.Tables 12.3.0

### Query/Question

In the predecessor library `Microsoft.Azure.Cosmos.Table` we have `TableQuery` class which has several static methods for building custom queries. This is also available in the legacy library `Microsoft.WindowsAzure.Storage`. It's easy to build helper methods based on this class to generate and **compose** business related query.

However, it seems this class is not available in the `Azure.Data.Tables` library.

Do we have any plan to add it back? If not, do we have any other replacement?

### Environment

N/A

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @allxiao - No, there is currently no replacement for this functionality from the old client. Do you have an example or scenario where you feel this functionality is required in place of the filter expression syntax or the interpolated string syntax?

For example, with the interpolated string syntax, it is possible to provide a filter without having to worry about the escaping rules of odata queries. See the sample here: https://github.com/Azure/azure-sdk-for-net/blob/ac9c1d3f6a27536428070e7e38be8060a8535d06/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md#query-entities-with-filter

**Comment by allxiao** [comment]
Hi @christothes , thanks for the update.

I think the original `TableQuery` provides the following nice functions:
1. It can be checked at compile time. The query is built by invoking several functions provided in `TableQuery` and you need to fill in correct number of arguments.
2. It's human readable and you can use code hints provided by IDE, for methods, fields (with `nameof()`) and operators. This also makes refactoring easier. I don't need to read [supported comparison operators](https://docs.microsoft.com/en-us/rest/api/storageservices/querying-tables-and-entities#supported-comparison-operators) before I can write a valid query. I read this the first time recently when I found I have to write string queries in the new SDK.
3. It can be composed. We can provide some utility methods that build part of the query, and compose them with other query parts.

LINQ query has properties 1 and 2. Interpolated string query has property 3.

**Comment by christothes** [comment]
Actually, expression queries can be composed also. See the following example: https://github.com/Azure/azure-sdk-for-net/issues/24033#issuecomment-927378891

**Comment by allxiao** [comment]
Hi @christothes , thanks for the reference. The `CreateQueryFilter` technique is more close to the original behavior. We still need to handle the `and` / `or` / `not` and parenthesis with plain string.

At this stage, we will copy the original `TableQuery` implementation to our project to ease the migration. Later, we will probably move to use `CreateQueryFilter` with some helper methods to combine filters.
