### ISSUE TITLE
[QUERY] How to deploy a new child resource with Azure.ResourceManager

### ISSUE THREAD

**Issue by marvinbuss** [Azure/azure-sdk-for-net#26059]
### Library name and version

Azure.ResourceManager 1.0.0-beta.7

### Query/Question

Can you please provide an generic example that shows how a generic resource or child resource can be deployed with the .NET SDK?

Let's imagine I have a Data Factory and I now want to add a child-resource (e.g. managed private endpoint) to it. How can this be done?

I already tried defining a generic resource and then called the update method, but that always failed and complained that the resource ID is invalid.
Thanks for your help!

### Environment

OS: Windows 11
.NET Version: 6.0.101
IDE: VS Code latest stable version

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by marvinbuss** [comment]
Hi @jsquire,
Any updates on the request above?

**Comment by jsquire** [comment]
Hi @marvinbuss.  Unfortunately, I'm only serving as initial triage in this case and have no insight.  @ArthurMa1978 is the person who would have the knowledge needed to provide an update.

**Comment by ArthurMa1978** [comment]
@fengzhou-msft  please help on it

**Comment by fengzhou-msft** [comment]
@marvinbuss with generic resource, you need to operate with a ResourceIdentifier of the child resource even with CreateOtUpdate. With your example, if you have a DataFactory with id `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataFactory/factories/{factoryName}`, then a managed private endpoint child resource id should look like `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataFactory/factories/{factoryName}/managedVirtualNetworks/{managedVirtualNetworkName}/managedPrivateEndpoints/{managedPrivateEndpointName}`. Use this child id as the resourceId when you create it with generic resource. In this case, you may need to create the managedVirtualNetworks first (with id `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataFactory/factories/{factoryName}/managedVirtualNetworks/{managedVirtualNetworkName}`) before you can create a managed private endpoint as it's actually a grandchild of datafactory and you need to create its parent first.

**Comment by marvinbuss** [comment]
Thanks @fengzhou-msft. Let me give this a try and get back if I run into any issues with this approach.

**Comment by marvinbuss** [comment]
Hi @fengzhou-msft,
When I do the following:

```cs
var principalAssignmentResource = armClient.GetGenericResource(id: new ResourceIdentifier(resourceId: "/subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.Kusto/Clusters/<kusto-name>/principalAssignments/{Guid.NewGuid()}"));
var principalAssignmentResourceParameters = new GenericResourceData(location: kusto.Value.Data.Location)
{
    Properties = new
    {
        principalId = principalId,
        principalType = "App",
        role = "AllDatabasesViewer",
        tenantId = tenantId
    }
};
await principalAssignmentResource.UpdateAsync(parameters: principalAssignmentResourceParameters, waitForCompletion: true, );
```

The following method fails: Azure.ResourceManager.Resources.GenericResource+<GetApiVersionAsync>d__27.MoveNext
Is there any option to set the api version?

**Comment by fengzhou-msft** [comment]
The issue is caused by the way GenericResource gets the api version for the resource type:
`string version = await ClientOptions.ApiVersions.TryGetApiVersionAsync(Id.ResourceType, cancellationToken).ConfigureAwait(false);`
It relies on you to pass in the api version for the resource type when you create the Client with ClientOptions.

In latest code, it's fixed with an API call:
`string version = await _providerCollection.TryGetApiVersionAsync(Id.ResourceType, cancellationToken).ConfigureAwait(false);`

The fix will be released with Azure.ResourceManager 1.0.0-beta.8.

**Comment by marvinbuss** [comment]
Hi @fengzhou-msft,
I upgraded to the new version today, but I am still running into the same issues and I am not sure how this is supposed to work.
This API call is always failing:
https://github.com/marvinbuss/PurviewAutomation/blob/737f500f03cbfd27da482d290bc2b1b0dc3e9588/code/PurviewAutomation/Clients/KustoOnboardingClient.cs#L177

Error:
Message: `Exception while executing function: PurviewAutomation Not supported type <>f__AnonymousType11`4[System.String,System.String,System.String,System.String]`
Exception type: `System.NotSupportedException`
Failed Method: `Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue`

Would be great to get some help on this issue! 👍

**Comment by marvinbuss** [comment]
This can be closed. Thanks for your help! 👍

**Comment by fengzhou-msft** [comment]
> Hi @fengzhou-msft, I upgraded to the new version today, but I am still running into the same issues and I am not sure how this is supposed to work. This API call is always failing: https://github.com/marvinbuss/PurviewAutomation/blob/737f500f03cbfd27da482d290bc2b1b0dc3e9588/code/PurviewAutomation/Clients/KustoOnboardingClient.cs#L177
> 
> Error: Message: `` Exception while executing function: PurviewAutomation Not supported type <>f__AnonymousType11``4[System.String,System.String,System.String,System.String] `` Exception type: `System.NotSupportedException` Failed Method: `Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue`
> 
> Would be great to get some help on this issue! 👍

This is resolved by using a dictionary instead of anonymous class for Properties.
