### ISSUE TITLE
[QUERY] Replace SAS token for a TableServiceClient

### ISSUE THREAD

**Issue by allxiao** [Azure/azure-sdk-for-net#26065]
### Library name and version

Azure.Data.Tables 12.3.0

### Query/Question

We use SAS token to access our Azure Storage Tables. The SAS token is configured to have a short valid time, typically 4 hours. When the SAS token expires, a new SAS token should be used to allow the client to access the table service.

In earlier SDK version (`Microsoft.WindowsAzure.Storage 9.3.2`), we use the following 2 functions provided by the SDK to work with the SAS token authentication:

1. The `CloudTableClient` has a `DefaultRequestOptions` which allows us to inject a custom `IRetryPolicy` implementation. We extend the default `ExponetialRetry` and further check if the failure is `403 Forbidden`. If yes, we consider this as a sign of SAS token expiry, and will refresh the SAS token and retry the request. (By default, 403 error is not considered as retryable.)
2. The `CloudStorageAccount` has a `Credentials` property which allows us to replace the SAS token (if the credential is indeed a SAS token) with the `UpdateSASToken` method. This is called in the above hook to replace the expired token. It will fetch a new SAS token from KeyVault (the storage account is managed by the KeyVault), and update it to the storage account.

With these two functions we are able to refresh the SAS token automatically when it is expired.

However, when we tried to migrate to the new `Azure.Data.Tables` library, we found we are not able to do it the same way:

1. The `RetryPolicy` is now fixed in the `HttpPipelineBuilder`. We can only configure some of its properties such as mode, delay, max retries, but we are not able to customize the policy itself. For example, we are not able to define a new policy which retries on 403 error. Without this, **we need to manually parse the SAS token to get the expiry time, and get a new token before it expires**. This is not supported in the SDK too, and the SAS token format looks to be implementation specific and should not parsed by our application logic.
2. SAS token passed to the `TableServiceClient` is now hidden in the `authPolicy`, which is just one policy in the per retry group. We are not able to access this policy or update the SAS token through the `TableServiceClient`. To use a new SAS token, we have to recreate the `TableServiceClient` instance. However, currently we use DI and register the table client on application starts, and inject it into the data access layer. **To replace the `TableServiceClient`, the whole DI chain needs to be refactored.**

We would like to know:
1. If we are going to improve this (e.g., support customizable retry policy, replaceable SAS token)?
2. If not, what's the recommended way to work with the SAS token refresh scenario?

Thanks,

### Environment

Environment neutral

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by allxiao** [comment]
I found the answer to _part_ of my question: How to replace the SAS token attached to a `TableServiceClient`?

When we create the `TableServiceClient`, we pass in an `AzureSasCredential` which contains the SAS token. This credential will further be wrapped in `AzureSasCredentialSynchronousPolicy` and become one of the policy in the pipeline, so we are not able to access the `AzureSasCredential` from the `TableServiceClient`.

We can keep a reference to the `AzureSasCredential` along with the `TableServiceClient`. When we need to update the SAS token, we call the `AzureSasCredential#Update` method to replace the SAS token. The replacement will be visible to the `TableServiceClient` because it keeps the reference to the original `AzureSasCredential`.

However, this looks more like a workaround which relies on the implementation details of `TableServiceClient`. If some change are made to the usage of the `AzureSasCredential` in `TableServiceClient`, for example, clone the credential rather than directly reference it, this approach will break. Besides, this looks like a sign of breaking the encapsulation of the `TableServiceClient`.

**Comment by christothes** [comment]
Hi @allxiao - The behavior you described is by design and is the correct approach for refreshing a SAS Credential across any SDK client that accepts an `AzureSasCredential`.

**Comment by allxiao** [comment]
Hi @christothes , thanks for confirming the answer.

This looks to be anti-pattern because we rely too much on the implementation details of the `TableServiceClient`. The `AzureSasCredential` is not accessible from the `TableServiceClient` instance, however, we can change the client behavior through the reference to the credential instance.
