### ISSUE TITLE
[QUERY] How to create Front Door from scatch using FrontDoorManagementClient ?

### ISSUE THREAD

**Issue by qcnguyen** [Azure/azure-sdk-for-net#26062]
### Library name and version

Microsoft.Azure.Management.FrontDoor

### Query/Question

Hi team, 
I tried to use FrontDoorManagementClient to create a frontdoor from scatch. But can't, because when we submit the request with the Microsoft.Azure.Management.FrontDoor.Models.FrontDoorModel , Azure require the HealthProbeSettingsModel Id value, but that Id is not available at the point of creating a new frontdoor from scatch. So we can't not create frontdoor. 
Please let us know are there any way to create frontdoor from scatch, using c# with Microsoft.Azure.Management.FrontDoor library. Thank you.

FYI, below is the my sample code to create FrontDoor, for your reference

`

        public async Task CreateFrontDoorAsync(AzureResourceInfo resourceInfo)

        {

            Log.Information("Creating Frontdoor");
            var client = await _clientFactory.GetFrontDoorManagementClientAsync();
            var healthProbe = new HealthProbeSettingsModel
            {
                Name = "default",
                Protocol = "Https",
                HealthProbeMethod = "Head",
                IntervalInSeconds = 30,
                Path = "/",
                Id = "default"
            };

            var balancing = new LoadBalancingSettingsModel
            {
                Name = "default",
                SampleSize = 4,
                SuccessfulSamplesRequired = 2,
                Id = "default"
            };

            var bk = new BackendPool()
            {
                Name = "default",
                ResourceState = "Disabled",
                HealthProbeSettings = healthProbe,
                LoadBalancingSettings = balancing,
                Backends = new Backend[]
                        {
                            new Backend
                            {
                                Address = "google.com",
                                BackendHostHeader = "google.com",
                                HttpPort = 80,
                                HttpsPort = 443,
                                Priority = 1,
                                Weight = 50
                            }
                        }
            };

            var enp = new FrontendEndpoint()
            {
                Name = resourceInfo.Name,
                HostName = resourceInfo.Name + ".azurefd.net"
            };

            var fd = await client.FrontDoors.CreateOrUpdateWithHttpMessagesAsync(resourceInfo.ResourceGroup, resourceInfo.Name, new FrontDoorModel()
            {
                Location = "Global",
                FrontendEndpoints = new FrontendEndpoint[]
                {
                    enp
                },
                HealthProbeSettings = new HealthProbeSettingsModel[]
                {
                    healthProbe
                },
                LoadBalancingSettings = new LoadBalancingSettingsModel[]
                {
                    balancing
                },
                BackendPools = new BackendPool[]
                {
                    bk
                },
                RoutingRules = new RoutingRule[]
                {
                    new RoutingRule
                    {
                        Name = $"default",
                        ResourceState = "Disabled",
                        RouteConfiguration = new ForwardingConfiguration
                        {
                            BackendPool = bk,
                            ForwardingProtocol = "MatchRequest"
                        },
                        FrontendEndpoints = new[] {
                            enp
                        },
                        PatternsToMatch = new[] { "/*" },
                        AcceptedProtocols = new[] { "Http", "Https" }
                    }
                }
            });
        }
`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by liurunliang** [comment]
Hi @qcnguyen, please use SubResource with ARM resource id for creating frontdoor. Here is an example.
```
using SubResource = Microsoft.Azure.Management.FrontDoor.Models.SubResource;
public async Task CreateFrontDoorAsync(AzureResourceInfo resourceInfo)
{
    Log.Information("Creating Frontdoor");
    var client = await _clientFactory.GetFrontDoorManagementClientAsync();
    var healthProbeName = "healthProbeSettings1";
    var loadBalancingSettingsName = "loadBalancingSettings1";
    var backendPoolName = "backendPool1";
    var frontendEndpointName = "frontendEndpoint1";
    var healthProbe = new HealthProbeSettingsModel
    {
        Name = healthProbeName,
        Path = "/",
        Protocol = "Https",
        HealthProbeMethod = "Head",
        IntervalInSeconds = 30
    };
    var balancing = new LoadBalancingSettingsModel
    {
        Name = loadBalancingSettingsName,
        SampleSize = 4,
        SuccessfulSamplesRequired = 2,
    };
    var bk = new BackendPool()
    {
        Name = backendPoolName,
        ResourceState = "Disabled",
        LoadBalancingSettings = new SubResource("/subscriptions/" + client.SubscriptionId + "/resourceGroups/" + resourceInfo.ResourceGroup + "/providers/Microsoft.Network/frontDoors/" + resourceInfo.Name + "/loadBalancingSettings/" + loadBalancingSettingsName),
        HealthProbeSettings = new SubResource("/subscriptions/" + client.SubscriptionId + "/resourceGroups/" + resourceInfo.ResourceGroup + "/providers/Microsoft.Network/frontDoors/" + resourceInfo.Name + "/healthProbeSettings/" + healthProbeName),
        Backends = new Backend[]
        {
        new Backend
        {
            Address = "google.com",
            BackendHostHeader = "google.com",
            HttpPort = 80,
            HttpsPort = 443,
            Priority = 1,
            Weight = 50
        }
        }
    };
    var enp = new FrontendEndpoint()
    {
        Name = frontendEndpointName,
        HostName = resourceInfo.ResourceGroup + ".azurefd.net"
    };
    var fd = await client.FrontDoors.CreateOrUpdateWithHttpMessagesAsync(resourceInfo.ResourceGroup, resourceInfo.Name, new FrontDoorModel()
    {
        Location = "Global",
        FrontendEndpoints = new FrontendEndpoint[]
        {
            enp
        },
        HealthProbeSettings = new HealthProbeSettingsModel[]
        {
            healthProbe
        },
        LoadBalancingSettings = new LoadBalancingSettingsModel[]
        {
            balancing
        },
        BackendPools = new BackendPool[]
        {
            bk
        },
        RoutingRules = new RoutingRule[]
        {
        new RoutingRule
        {
            Name = "routingrule1",
            ResourceState = "Disabled",
            RouteConfiguration = new ForwardingConfiguration
            {
                BackendPool = new SubResource("/subscriptions/" + client.SubscriptionId + "/resourceGroups/" + resourceInfo.ResourceGroup + "/providers/Microsoft.Network/frontDoors/" + resourceInfo.Name + "/backendPools/" + backendPoolName),
                ForwardingProtocol = "MatchRequest"
            },
            FrontendEndpoints = new List<SubResource> 
            {
                new SubResource("/subscriptions/" + client.SubscriptionId + "/resourceGroups/" + resourceInfo.ResourceGroup + "/providers/Microsoft.Network/frontDoors/" + resourceInfo.Name + "/frontendEndpoints/" + frontendEndpointName)
            },
            PatternsToMatch = new[] { "/*" },
            AcceptedProtocols = new[] { "Http", "Https" }
        }
        }
    });
}
```
