### ISSUE TITLE
Make sure Monitor RP need to be released in January 

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#26068]
Diagnostics is used by various of services, so the Monitor / Insight service might be released in the first wave, and some modules should be added to ResourceManager lib.

Related to https://github.com/azure/azure-sdk-for-net/issues/25889

**Comment by ArcturusZhang** [comment]
Code is ready here: https://github.com/Azure/azure-sdk-for-net/pull/26023

**Comment by ArthurMa1978** [comment]
Will release it in GA, https://github.com/azure/azure-sdk-for-net/issues/25889
