### ISSUE TITLE
[BUG] Confidential Ledger Authorization Error

### ISSUE THREAD

**Issue by HichemDax** [Azure/azure-sdk-for-net#26063]
### Library name and version

Azure.Security.ConfidentialLedger 1.0.0-beta.2

### Describe the bug

I have run the same code in documentation few days back it was working perfectly, yesterday and today facing this error knowing that my user is global admin and admin of the confidential ledger resource and nothing changed in the azure settings. What could have changed?

Azure.RequestFailedException: 'Not allowed to call POST /app/transactions
Status: 403 (Forbidden)
ErrorCode: NotAllowed

### Expected behavior

Expected to commit the data to confidential ledger and return the transaction id.

### Actual behavior

Azure.RequestFailedException: 'Not allowed to call POST /app/transactions
Status: 403 (Forbidden)
ErrorCode: NotAllowed

### Reproduction Steps

Used this code in console app:
string ledgerId = "MyConfLedger1";
            Uri identityServiceUri = new Uri("https://identity.confidential-ledger.core.azure.com");
         

            var identityClient = new ConfidentialLedgerIdentityServiceClient(identityServiceUri);

            Response response = identityClient.GetLedgerIdentity(ledgerId);
            var eccPem = JsonDocument.Parse(response.Content)
                .RootElement
                .GetProperty("ledgerTlsCertificate")
                .GetString();

            X509Certificate2 ledgerTlsCert = new X509Certificate2(Encoding.UTF8.GetBytes(eccPem));
            X509Chain certificateChain = new X509Chain();
            certificateChain.ChainPolicy.RevocationMode = X509RevocationMode.NoCheck;
            certificateChain.ChainPolicy.RevocationFlag = X509RevocationFlag.ExcludeRoot;
            certificateChain.ChainPolicy.VerificationFlags = X509VerificationFlags.AllowUnknownCertificateAuthority;
            certificateChain.ChainPolicy.VerificationTime = DateTime.Now;
            certificateChain.ChainPolicy.UrlRetrievalTimeout = new TimeSpan(0, 0, 0);
            certificateChain.ChainPolicy.ExtraStore.Add(ledgerTlsCert);

            bool CertValidationCheck(HttpRequestMessage httpRequestMessage, X509Certificate2 cert, X509Chain x509Chain, SslPolicyErrors sslPolicyErrors)
            {
                bool isChainValid = certificateChain.Build(cert);
                if (!isChainValid) return false;

                var isCertSignedByTheTlsCert = certificateChain.ChainElements.Cast<X509ChainElement>()
                    .Any(x => x.Certificate.Thumbprint == ledgerTlsCert.Thumbprint);
                return isCertSignedByTheTlsCert;
            }

            var httpHandler = new HttpClientHandler();
            httpHandler.ServerCertificateCustomValidationCallback = CertValidationCheck;

            var options = new ConfidentialLedgerClientOptions { Transport = new HttpClientTransport(httpHandler) };
            var ledgerClient = new ConfidentialLedgerClient(new Uri("https://MyConfLedger1.confidential-ledger.azure.com"), new DefaultAzureCredential(), options);

            

Error here -->            Response postResponse = ledgerClient.PostLedgerEntry(
                RequestContent.Create(
                    new { contents = "Some test data" }));

### Environment

Visual studio 19
C# project with .NET 5
Azure.Security.ConfidentialLedger 1.0.0-beta.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mattmoodytunecoin** [comment]
Any updates on this?

I'm receiving the exact error after following the documentation to create a service principal for app authentication.

```
Azure.RequestFailedException: Not allowed to call POST /app/transactions
Status: 403 (Forbidden)
ErrorCode: NotAllowed
```

**Comment by christothes** [comment]
Hi @mattmoodytunecoin - Can you reproduce this with the latest version? https://www.nuget.org/packages/Azure.Security.ConfidentialLedger/1.1.0-beta.1

**Comment by mattmoodytunecoin** [comment]
> Hi @mattmoodytunecoin - Can you reproduce this with the latest version? https://www.nuget.org/packages/Azure.Security.ConfidentialLedger/1.1.0-beta.1

Apologies, updated my original post to include the version of the library I was using, which in fact was the one you mentioned.

**Comment by christothes** [comment]
I believe you need to bootstrap at least one principal ObjectId or certificate via ARM to assign access, and then those identities can add users via the API. [Here ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/confidentialledger/test-resources.json#L54)is an example of what the ARM template looks like for assigning access.

**Comment by mattmoodytunecoin** [comment]
> I believe you need to bootstrap at least one principal ObjectId or certificate via ARM to assign access, and then those identities can add users via the API. [Here ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/confidentialledger/test-resources.json#L54)is an example of what the ARM template looks like for assigning access.

That worked for me! Using the link you provided with this [documentation](https://docs.microsoft.com/en-us/azure/confidential-ledger/quickstart-template?tabs=azure-cli%2CCLI) I was able to get past the authorization error.

👍

**Comment by christothes** [comment]
Thanks for confirming. I've created the following issue to track an improvement to the readme docs concerning this issue. #31056
