### ISSUE TITLE
Check if track 2 fully cover all track 1 policy features

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#26069]
1. The delegate handler is widely used on track 1 sdk, so need to make sure track 2 can support it by using policy and provide samples.
2. Also need to check other track 1 policy features.

**Comment by archerzz** [comment]
Track2 is using `Azure.Core` client which provides the same capability as track1.
- I think the docs are pretty good: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/README.md
- About `ClientOptions` (e.g. configure `Retry`, `Transport`, `Diagnostics`, etc): https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md
- About `Policy`: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Pipeline.md

**Comment by archerzz** [comment]
I think those should be enough for powershell.
