### ISSUE TITLE
[BUG] Azure Functions Service Bus Output ignores ServiceBusconnection__tenantId property when not using clientid+clientsecret

### ISSUE THREAD

**Issue by henrybeen** [Azure/azure-sdk-for-net#26076]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.2.0

### Describe the bug

When using the ServiceBusAttribute to use a ServiceBus Topic as an output binding, the tenantid property in the configuration is ignored, resulting in an error: "InvalidIssuer: Token issuer is invalid"

### Expected behavior

The outputbinding fetches an access token from the correct AAD Tenant, using the tenantId property specified in configuration. This is possible using the Azure.Identity platform, as we can make guest users succesfully access resources when using 

a new TokenRequestContext(new string[] { _options.Value.ResourceId }, tenantId: _options.Value.TenantId) in our own GetToken calls

### Actual behavior

A token is requested using the default (home) tenant for the logged in user, resulting in the specified error

### Reproduction Steps

Have an AAD Tenant A, with an user U
Have an AAD Tenant B, where U is a guest user
Have a Service Bus Namespace + Topic in a subscription linked to tenant B, where U has 'Servicebus Sender' permissions

Create an Azure Functions project that tries to send a message to the Topic using the Visual Studio Logged In Identity, and observe the error

### Environment

Windows, .NET6, VS2022 latest, latest&gratest on all libs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by henrybeen** [comment]
So I did some more digging today and I found that this might not be a bug, but a feature request. It seems that right now there is simply no support for this setting, and I read wrong.

Still: with organizations slowly adopting the use of guest-users, this would be a great feature to add. Allowing temporary workers to bring their own accounts as guest-account, developers would be able to stick to their own work-account, and dont have to get an account for each organization they temporarily work for (consultants, freelancers, etc)

**Comment by JoshLove-msft** [comment]
Hi @henrybeen, can you clarify which settings you would like to set?

**Comment by henrybeen** [comment]
I want to be able to switch the AAD tenant for which a token is requested/obtained when using Visual Studio authentication to connect to a service bus topic.

F.e. when using Azure.Identity directly, you can do something like this:

```
var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions
{
    VisualStudioTenantId = _options.Value.TenantId,
    ManagedIdentityClientId = _options.Value.UserAssignedManagedIdentityClientId
});
```

The equivalent of the ManagedIdentityClientId is available for setting when you use a service bus trigger, through:

```
<ServiceBusConnectionName>__clientId
```

However, there is no equivalent for setting the VisualStudioTenantId AFAIK. This is necessary if you are using a guest account, which defaults to the home tenantid, instead of the tenantid that is hosting the service bus namespace you are accessing

**Comment by JoshLove-msft** [comment]
So using this setting doesn't work?
```
<ServiceBusConnectionName>__tenantId
```
