### ISSUE TITLE
[BUG] _modelAdministrationClient.StartBuildModelAsync does not recognize "Prefix" in BuildModelOptions parameter

### ISSUE THREAD

**Issue by vijumane** [Azure/azure-sdk-for-net#26081]
### Library name and version

Azure.AI.FormRecognizer 4.0.0-beta.2

### Describe the bug

_modelAdministrationClient.StartBuildModelAsync does not recognize "Prefix" (subfolder path from root of blob container) provided in BuildModelOptions parameter, and always throw error below

Invalid request.
Status: 400 (Bad Request)
ErrorCode: InvalidRequest

Content:
{
  "error": {
    "code": "InvalidRequest",
    "message": "Invalid request.",
    "innererror": {
      "code": "TrainingContentMissing",
      "message": "Training data is missing: Could not find any training data at the given path."
    }
  }
}

Headers:
Transfer-Encoding: chunked
x-envoy-upstream-service-time: 772
apim-request-id: b91777be-49da-499d-b75f-526507e36806
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Date: Sun, 26 Dec 2021 23:30:27 GMT
Content-Type: application/json

### Expected behavior

Model administration client should be able to look for training files as per subfolder path provided in "Prefix" option

### Actual behavior

receive error like below 

Invalid request.
Status: 400 (Bad Request)
ErrorCode: InvalidRequest

Content:
{
  "error": {
    "code": "InvalidRequest",
    "message": "Invalid request.",
    "innererror": {
      "code": "TrainingContentMissing",
      "message": "Training data is missing: Could not find any training data at the given path."
    }
  }
}

### Reproduction Steps

Here is the code to reproduce

var buildModelOptions = new BuildModelOptions 
                { 
                    Prefix = docType.SubFolderName, 
                    ModelDescription = trainedModel.ModelDescription 
                };
                BuildModelOperation operation = await _modelAdministrationClient.StartBuildModelAsync(new Uri(_trainingDataSASUrl), trainedModel.ModelName, buildModelOptions);
                Response<DocumentModel> operationResponse = await operation.WaitForCompletionAsync();
                DocumentModel model = operationResponse.Value;

### Environment

.net version 5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Thank you for bringing this issue to our attention, @vijumane. I could reproduce the issue on my end, and it seems to be service-related. Could you check if the following workaround works? It solved the problem for me.
```cs
var buildModelOptions = new BuildModelOptions
{
    Prefix = docType.SubFolderName + '/', // append a slash to the subfolder name
    ModelDescription = trainedModel.ModelDescription
};
```

@ctstone Could you confirm if this behavior is intended or a bug? When building a model, it seems users need to append a slash `/` to the end of the `Prefix` property if they want to use a subfolder in the container with the training files. Subfolders are not probed by default.

**Comment by ctstone** [comment]
@kinelski , the behavior is intended. Form Recognizer relies on Azure Storage Blob which has the same prefix semantics.

**Comment by vijumane** [comment]
Thank you @kinelski and @ctstone for investigating. I confirm that it worked with '/' prefix. Unfortunately i couldnt find single online example of using "prefix" attribute anywhere, for sdk version 4.x, and in previous version it worked without such prefix. That is why reported as bug. Thanks !!
