### ISSUE TITLE
How we can add hierarchyIds to TimeSeriesInstance as HierarchyIds property in read only

### ISSUE THREAD

**Issue by mukesh-rep** [Azure/azure-sdk-for-net#26118]
### Library name and version

Azure.IoT.TimeSeriesInsights 1.0.0-beta.1

### Query/Question

We are had to create the TimeSeriseInstance by C# azure function, but we are unable to assign HierarchyIds in TimeSeriesInstance as the property is read-only. 

Can you suggest some workaround for the above case? Our use case is when we are creating the TimeSeriesInstance that time we want to assign Hierarchy and type.

**Comment by PramodValavala-MSFT** [comment]
@mukesh-rep You cannot reassign the value of the property to another list instance but can append values to the `List`. You could use the [`AddRange` method](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.list-1.addrange?view=net-6.0) to add values from a list that you have.

**Comment by mukesh-rep** [comment]
@PramodValavala-MSFT  Thanks, It works for me.

**Comment by PramodValavala-MSFT** [comment]
@mukesh-rep Glad to hear that! We will proceed to close this.
