### ISSUE TITLE
Compile failed in a unicode windows 10.

### ISSUE THREAD

**Issue by JasonYang-MSFT** [Azure/azure-sdk-for-net#2611]
## Build Error:
An error shows as following info while trying to compile by "msbuild".
`D:\work\azure-sdk-for-net\src\TestFramework\Microsoft.Azure.Test.HttpRecorder\Properties\AssemblyInfo.cs(26,30): erro
r CS1010: Newline in constant [D:\work\azure-sdk-for-net\build.proj]`

## Direct Cause:
After open src\TestFramework\Microsoft.Azure.Test.HttpRecorder\Properties\AssemblyInfo.cs in VS, there is a line string with " missing:
`[assembly: AssemblyCopyright("Copyright ?)]`

## Root cause 
This line of code show in my desktop is dfference to its original code in https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/TestFramework/Microsoft.Azure.Test.HttpRecorder/Properties/AssemblyInfo.cs#L26
`[assembly: AssemblyCopyright("Copyright ©")]`

After compare the differs in git, it shows © as <A9> which cause ©" regard as a unicode char in a my desktop.
`
-[assembly: AssemblyCopyright("Copyright <A9>")]
+[assembly: AssemblyCopyright("Copyright ")]
`
## Quick Resolve
After delete ©, compilation succeded.
`[assembly: AssemblyCopyright("Copyright ")]`

**Comment by shahabhijeet** [comment]
@JasonYang-MSFT is this compile error happening in VS or on commandline?
Also can you give me your VS settings:
1) If this is only happening during compilation in VS, what save options are selected for your VS under File --> Advanced Save Options
2) Also provide steps to repro this issue?

**Comment by JasonYang-MSFT** [comment]
Hi @shahabhijeet ,

It happend in both VS and commandline.

To answer your questions:
1. Saved as UTF-8.
2. using Win10 and VS with Chinese version, open ResourceManagement\Storage\Storage.sln. Or just call "msbuild /t:build" on commandline.
2. PATH env.

D:\work\azure-sdk-for-net\src\ResourceManagement\Storage>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\Jason Yang\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\dotnet\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\PuTTY\;C:\Program Files (x86)\Common Files\Thunder Network\KanKan\Codecs;C:\Users\Jason Yang\.dnx\bin;D:\Windows\SysWOW64;C:\Users\Jason Yang\AppData\Local\Microsoft\WindowsApps;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;

**Comment by shahabhijeet** [comment]
@JasonYang-MSFT please provide your OS and VS locale details.
Please provide steps to repro this issue.

**Comment by markcowl** [comment]
Closing for lack of response.  If you are seeing this issue, please reopen
