### ISSUE TITLE
[FEATURE REQ] Support subject-name and issuer authentication in ClientFactory

### ISSUE THREAD

**Issue by Kencdk** [Azure/azure-sdk-for-net#26115]
### Library name

Microsoft.Extensions.Azure

### Please describe the feature.

When using certificate-based authentication, relying on subject name and issuer has advantages over matching individual thumbprints and is a requirement for many developers using certificate based authentication.

MSAL and Azure.Identity both support it, by setting the SendCertificateChain on ClientCertificateCredentialOptions or using WithSendX5C() in MSAL, but there is currently, no way to pass it into the TokenCredentialOptions used in ClientFactory.

### Proposal ###
Add "clientCertificateSendCertificateChain" configuration entry and use it to build the ClientCertificateCredential, setting SendCertificateChain to the value from the configuration.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
It is possible to create and configure `ClientCertififcateCredential ` directly when registering clients.   For example:
```csharp
builder.Services.AddAzureClients(clientBuilder =>
{
    // Add a KeyVault client
    clientBuilder.AddSecretClient(builder.Configuration.GetSection("KeyVault"));

    // Use ClientCertificateCredentail with custom options
    var certificate = new X509Certificate2("./certs/cert-password-protected.pfx", "password");
    clientBuilder.UseCredential(new ClientCertificateCredential("<< TENANT >>", "<< CLIENT >>", certificate));

    // Set up any default settings
    clientBuilder.ConfigureDefaults(builder.Configuration.GetSection("AzureDefaults"));
});

builder.Services.AddControllers();
```
More information can be found in [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection).

We have no current plans to add additional configuration; closing this out.
