### ISSUE TITLE
Re-enable Backup/Restore tests

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#26122]
Tests are consistently failing and the service team asked us to temporarily disable them.

**Comment by pakrym** [comment]
The service team also requested us to move tests from uswest2 to uswestcentral region.

**Comment by heaths** [comment]
MHSM tests are run against southcentralus, which - at least prior - was one of the only regions in the US where MHSM was supported. Only KV tests run against westus2 and do not support MHSM backup/restore tests.
