### ISSUE TITLE
[QUERY] Will ResourceManager.Storage support listing of blobs in the future?

### ISSUE THREAD

**Issue by TobiasLaving** [Azure/azure-sdk-for-net#26120]
### Library name and version

Azure.ResourceManager.Storage 1.0.0-beta5

### Query/Question

Hello,

I recently started looking into doing some azure management and I want to use C# as language. I am wondering if the intention is that ResourceManager.Storage will support the blob list/download actions in the future?

Basically I wonder if I should wait or use the Azure.Storage.Blobs instead.

Maybe a silly question, but I cannot find a roadmap anywhere.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by archerzz** [comment]
@TobiasLaving `Azure.ResourceManager.Storage` is a management plane SDK, e.g. it is responsible for managing service instances.
What you want to do is in the scope of data plane SDK. Check this [example](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.Storage.Blobs#enumerating-blobs) in `Azure.Storage.Blob` SDK. Hope that can help. Thanks.

**Comment by TobiasLaving** [comment]
Ok, thanks

Will there be any convenience functionality that will allow us to get the dataplane from control plane?

Lite
```
var service = container.GetDataPlaneService();
service.GetBlobs,,,,
```

**Comment by archerzz** [comment]
@TobiasLaving No. Because if we did that, the control plane will depend on data plane, and the library size will increase.

**Comment by TobiasLaving** [comment]
Hmm, ok, understandable.
How about convenience functionality (or docs) to get a connection string for the dataplane from the control-plane?

**Comment by archerzz** [comment]
@TobiasLaving There is a doc about how to compose a connection string: https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string

You can get the keys through [`StorageAccount.GetKeys`](https://github.com/Azure/azure-sdk-for-net/blob/829526a91fd29f4712a4fcc17af2a08d2a5a0f16/sdk/storage/Azure.ResourceManager.Storage/src/Generated/StorageAccount.cs#L317), and then compose the connection strings accordingly.

**Comment by TobiasLaving** [comment]
Lovely, thanks!
