### ISSUE TITLE
Please properly format this page

### ISSUE THREAD

**Issue by bettychenyi** [Azure/azure-sdk-for-net#26125]
This section is not well formatted which makes it hard to read:

"Gets or sets specifies how the virtual machine should be created.&lt;br&gt;&lt;br&gt; Possible values are:&lt;br&gt;&lt;br&gt; Attach \u2013 This value is used when you are using a specialized disk to create the virtual machine.&lt;br&gt;&lt;br&gt; FromImage \u2013 "

"Possible values include: 'FromImage', 'Empty', 'Attach'" - No "." in the end? It also could be formated better.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1d24ee7-7dfe-ec4c-3be9-f148b890a4f4
* Version Independent ID: 24f0eeb6-9084-fddb-7aa6-112c046cab86
* Content: [OSDisk.CreateOption Property (Microsoft.Azure.Management.Compute.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.osdisk.createoption?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/OSDisk.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/OSDisk.xml)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Will check with docs team as this is a reference doc which auto-generated from lib
