### ISSUE TITLE
[BUG] Cannot change ServiceBusMessage.SessionId once it was set

### ISSUE THREAD

**Issue by petrformanek** [Azure/azure-sdk-for-net#26129]
### Library name and version

Azure.Messaging.ServiceBus 7.5.1

### Describe the bug

Dear service bus team, 
please check this issue.

Once ServiceBusMessage.SessionId and PartitionKey is set it cannot be changed later.
It is breaking change against legacy Microsoft.Azure.ServiceBus.

In some cases I need to change SessionId and PartitionKey in later code flow. 
Now it is only possible only with hack.
```csharp
var message = new ServiceBusMessage
{
    PartitionKey = "1",
    SessionId = "1"
};

message.GetRawAmqpMessage().Properties.GroupId = "2"; // HACK
message.PartitionKey = "2";
message.SessionId = "2";
```

### Expected behavior

The test should pass.
```csharp
[Fact]
public void Test()
{
    var message = new ServiceBusMessage
    {
        PartitionKey = "1",
        SessionId = "1"
    };
    
    message.PartitionKey = "2";
    message.SessionId = "2";

    Assert.Equal("2", message.PartitionKey);
    Assert.Equal("2", message.SessionId);
}
```

### Actual behavior

The above test throws an exception: `System.ArgumentOutOfRangeException : PartitionKey:2 cannot be set to a different value than SessionId:1. (Parameter 'value')`.

### Reproduction Steps

See the unit test above.

### Environment

Any supported .NET.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
It looks like we were overzealous with the validation on the SessionId property. This should be relaxed so that the partition key equals sessionId check only happens when setting the partition key. With this change you would need to change the SessionId first, and then change the Partition key. @petrformanek, would that work for you?

**Comment by petrformanek** [comment]
@JoshLove-msft it sounds good to me.
