### ISSUE TITLE
[QUERY] Azure KeyVault client every time makes a request to get an access token

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-sdk-for-net#26124]
### Library name and version

Microsoft.Azure.KeyVault 3.0.5

### Query/Question

I have the following code in Startup.cs

    services.AddSingleton<KeyVaultClient>(_ =>
    {
    	return new(async (authority, resource, _) =>
    	{
    		var adCredential = new ClientCredential(options.KeyVaultClientId, options.KeyVaultClientSecret);
    		var authenticationContext = new AuthenticationContext(authority, null);
    		var authResult = await authenticationContext.AcquireTokenAsync(resource, adCredential);
    		return authResult.AccessToken;
    	});
    });

Then, I inject `KeyVaultClient` in many places. For example one request to my Web API, first validates a certificate in one class:

    await _keyVaultClient.VerifyAsync(_options.KeyVaultUrl, _options.RootCertificateId,
        string.Empty, JsonWebKeySignatureAlgorithm.RS256, digest, signature);
then sign JWT token in another class:

    await _keyVaultClient.SignAsync(_options.KeyVaultUrl, _options.RootCertificateId,
        string.Empty, JsonWebKeySignatureAlgorithm.RS256, digest);
As a result, on every request, I got 2 login.windows.net operations which takes much time
[![enter image description here][1]][1]

    POST Tokens/Token
    POST /{TenantId}/oauth2/token
    POST //keys/MD-CARoot-dev//verify
    POST /{TenantId}/oauth2/token
    POST //keys/MD-CARoot-dev//sign
Is there a way to avoid these long operations every time you use `KeyVaultClient`?
Is it optimal to acquire a new token every time while the previous one is still valid? Why the SDK doesn't use some cache?

  [1]: https://i.stack.imgur.com/tfMTy.png

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Microsoft.Azure.KeyVault is deprecated and we would not be fixing this issue, which can happen in some cases. Instead, please use  Azure.Security.KeyVault.Keys along with Microsoft.Extensions.Azure. See https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/extensions/Microsoft.Extensions.Azure for an example (uses a `SecretClient` but would work the same for a `KeyClient`).

**Comment by heaths** [comment]
@Marusyk and, if it helps, we also have a [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Keys/MigrationGuide.md) from the old package to the new. While the class and some method names have changed, the new SDK works mostly the same as the old and map fairly 1:1 to the Key Vault and Managed HSM services.
