### ISSUE TITLE
[BUG] ConversationsProject class not available

### ISSUE THREAD

**Issue by merlijnsbaard** [Azure/azure-sdk-for-net#26121]
### Library name and version

Azure.AI.Language.Conversations 1.0.0-beta.1

### Describe the bug

no access to the ConversationsProject model.

### Expected behavior

The class [ConversationsProject](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/Models/ConversationsProject.cs) should be available in `Azure.AI.Language.Conversations`

### Actual behavior

The ConversationsProject class is not available.

### Reproduction Steps

Installed package versions:
Azure.AI.Language.Conversations 1.0.0-beta.1

```
using Azure.AI.Language.Conversations;

var classTypes = new[]
{
    typeof(AnswerSpan),
    typeof(BasePrediction),
    typeof(ConversationsModelFactory),
    typeof(AnswerSpan),
    typeof(KnowledgeBaseAnswer),
    typeof(LuisTargetIntentResult),
    typeof(TargetIntentResult),
    
    // Not accessible.
    // typeof(ConversationsProject),
};
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     pop
 OS Version:  21.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.101/

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AhmedLeithy** [comment]
Thanks for pointing this out. The change is already implemented and will be included in the next release of the `Azure.AI.Conversations` package (I'm not quite certain when that will be, @heaths might know better).

For the current version of the package, you can achieve the same functionality using the client's APIs as shown in the following [sample markdowns](https://github.com/Azure/azure-sdk-for-net/tree/310f1a5bec7be100eb9d89aef7b5a3ced292bbaa/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples) and the [sample source code](https://github.com/Azure/azure-sdk-for-net/tree/310f1a5bec7be100eb9d89aef7b5a3ced292bbaa/sdk/cognitivelanguage/Azure.AI.Language.Conversations/tests/Samples).

**Comment by xtianus79** [comment]
Yes, this is odd to not be in the actual sdk but in the documentation

**Comment by heaths** [comment]
We have no date yet to share for the next release but it should be soon. Please watch https://azure.github.io/azure-sdk/releases/latest/ for updates.

Closing this issue in lieu of the aforementioned releases page.

**Comment by BaherAbdullah** [comment]
@heaths  Hello heath!, please change the documentation to the old one: https://github.com/Azure/azure-sdk-for-net/tree/310f1a5bec7be100eb9d89aef7b5a3ced292bbaa/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples

till the new release is out, since this is affecting our production customers.

@hazemelh - FYI
