### ISSUE TITLE
[FEATURE REQ] Enable dependency injection for ServiceBusAdministrationClient

### ISSUE THREAD

**Issue by kaylumah** [Azure/azure-sdk-for-net#26131]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

Hi,

In `Compatability/ServiceBusClientBuilderExtensions.cs` in the `Azure.Messaging.ServiceBus.sln` we have a method to register a ServiceBusClient.

```
    /// <summary>
    ///   Registers a <see cref="ServiceBusClient"/> instance with the provided <paramref name="fullyQualifiedNamespace"/>.
    /// </summary>
    ///
    public static IAzureClientBuilder<ServiceBusClient, ServiceBusClientOptions> AddServiceBusClientWithNamespace<TBuilder>(this TBuilder builder, string fullyQualifiedNamespace)
        where TBuilder : IAzureClientFactoryBuilderWithCredential
    {
        return builder.RegisterClientFactory<ServiceBusClient, ServiceBusClientOptions>((options, token) => new ServiceBusClient(fullyQualifiedNamespace, token, options));
    }
```

Which allows registering it for DI via the following method

```
 public static IServiceCollection AddServiceBusUtil(this IServiceCollection services, IConfiguration config)
    {
        _ = config ?? throw new ArgumentNullException(nameof(config));

        services.AddAzureClients(builder => {
            builder.AddServiceBusClientWithNamespace(config.GetConnectionString("ServiceBus"));

        });
        return services;
    }
```

Which is great and makes managing client / client lifetime a lot easier.

Perhaps I missed another extension method, but it appears  that there is no equivalent for it for the `ServiceBusAdministrationClient`

It appears that using ServiceBusAdministrationClient ServiceBusAdministrationClientOptions would yield the same result. Is there more to it than adding a new extension method like this? 

I've tested it out in my own application and it appears doing the same trick would be enough.

```
services.AddAzureClients(builder => {
            builder.AddServiceBusClientWithNamespace(config.GetConnectionString("ServiceBus"));
            (builder as IAzureClientFactoryBuilderWithCredential).RegisterClientFactory<ServiceBusAdministrationClient, ServiceBusAdministrationClientOptions>((options, token) => new ServiceBusAdministrationClient(config.GetConnectionString("ServiceBus"), token, options));
});
```

If it is a case of creating the same set of operations ServiceBusAdministrationClient offers I am more than happy to create a PR to support that.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @kaylumah,
Yes I think we would need three new methods patterned after the existing ones for ServiceBusClient. We would be happy to take a contribution!

**Comment by kaylumah** [comment]
@JoshLove-msft I've created #26225 since this is my first time contributing please let me know if anything else needs to be done.

**Comment by kaylumah** [comment]
@JoshLove-msft for example have unexpected changes since I ran the script suggested by one of the checks to regenerate some code

**Comment by kaylumah** [comment]
Thanks for the help resolving this @JoshLove-msft
