### ISSUE TITLE
Code sample missing await keyword for async operations

### ISSUE THREAD

**Issue by Malcolm-Stewart** [Azure/azure-sdk-for-net#26156]
The line of code

sqlConnection.AccessToken = azureServiceTokenProvider.GetAccessToken**Async**("https://database.windows.net");

needs to use the await keyword because the method being called in asynchronous (GetAccessToken**Async**). e.g.

sqlConnection.AccessToken = **await** azureServiceTokenProvider.GetAccessToken**Async**("https://database.windows.net");

The following page shows the correct usage of the await keyword:

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/operators/await

 byte[] content = **await** client.**GetByteArrayAsync**("https://docs.microsoft.com/en-us/");

Otherwise, the code continues before the API returns a value and then fails.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56851479-9543-a30c-37da-a1852def3797
* Version Independent ID: 4b2f90e7-dbfb-a811-64ff-9eea8b5b7443
* Content: [App Authentication client library for .NET - Version 1.6.0 - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication#feedback)
* Content Source: [api/overview/azure/service-to-service-authentication.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/service-to-service-authentication.md)
* Product: **azure**
* GitHub Login: @jlichwa
* Microsoft Alias: **jalichwa**

**Comment by MughundhanRaveendran-MSFT** [comment]
@Malcolm-Stewart , Thanks for reporting, I will check and update accordingly.

**Comment by anaismiller** [comment]
Closing incident, MughundhanRaveendran-MSFT fixed the issue on Jan. 7.
