### ISSUE TITLE
Document in code and with tests that ClientOptions should be shareable between clients

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#26157]
### Library name and version

Azure.Core

### Describe the bug

One of the Client design tenants is that instances of ClientOptions for a given SDK client should be reusable across multiple clients. This implies certain restrictions on mutability and configuration that assumes service instance affinity.

This behavior should be documented in code and reenforced with tests.

**Comment by christothes** [comment]
cc @annelo-msft

**Comment by pallavit** [comment]
/cc: @annelo-msft , @KrzysztofCwalina is this something you woudl want to consider for the new toolchain?

**Comment by annelo-msft** [comment]
@pallavit, can you clarify what you mean by the new toolchain?  Do you mean we should add tests for this for corresponding  ClientModel types, or something else?
