### ISSUE TITLE
[BUG] Incorrect SAS returns from TableClient.GenerateSasUri

### ISSUE THREAD

**Issue by LeaShallev** [Azure/azure-sdk-for-net#26155]
### Library name and version

Azure.Data.Tables 12.2.1

### Describe the bug

Using Azure.Data.Tables TableClient.GenerateSasUri, I get a SAS with URI to the table service (e.g. https://dummysa.table.core.windows.net/?tn=TABLE_NAME), where table name appears only as a query parameter.
In contrast, using Microsoft.WindowsAzure.Storage.Table, one should pass URI where table name appears in the URI’s path (unless you get a CloudTable object with an empty name and a “System.ArgumentException: 'The argument must not be empty string. (Parameter 'tableName')'” when trying to use it).
In the portal, table SASs also include the table name in the path 
Same in the following doc for resource uri syntax- https://docs.microsoft.com/en-us/rest/api/storageservices/addressing-table-service-resources#resource-uri-syntax

Thanks!

### Expected behavior

Get a SAS in the format https://dummysa.table.core.windows.net/**TABLE_NAME**?..... when calling TableClient.GenerateSasUri

### Actual behavior

Get a SAS with URI to the table service (e.g. https://dummysa.table.core.windows.net/?tn=TABLE_NAME), where table name appears only as a query parameter.

### Reproduction Steps

var tableSasBuilder = new TableSasBuilder(tableName, TableSasPermissions.All, DateTime.Now.AddDays(1))
            {
                StartsOn = DateTime.Now.Subtract(TimeSpan.FromHours(3))
            };

var tableClient = new TableClient(connectionString, tableName);
var newSasUri = tableClient5.GenerateSasUri(tableSasBuilder);

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by LeaShallev** [comment]
Thanks for the fix. 
Should I use another SDK version to get the fix or it will be available with current SDK version 12.2.1 as the change is in the server side?
