### ISSUE TITLE
Long running operation sometimes throws TaskConceledException

### ISSUE THREAD

**Issue by csmengwan** [Azure/azure-sdk-for-net#2615]
When using SDK to make long running operation calls it sometimes throw TaskCanceledException.

This is the stackTrace:

threw exception. System.Threading.Tasks.TaskCanceledException: System.Threading.Tasks.TaskCanceledException: A task was canceled..

Error Stack Trace:
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
Microsoft.Azure.Management.Cdn.EndpointsOperations.d8.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.Azure.Management.Cdn.EndpointsOperations.d7.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.Azure.Management.Cdn.EndpointsOperationsExtensions.d__5.MoveNext()
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.Azure.Management.Cdn.EndpointsOperationsExtensions.Create(IEndpointsOperations operations, String resourceGroupName, String profileName, String endpointName, Endpoint endpoint)

This is a transient issue appears in low frequency.
Please help to take a look at the code gen.

**Comment by hovsepm** [comment]
@csmengwan we will need network payload as well (could be captured with Fiddler for example).

**Comment by markcowl** [comment]
Closing for lack of response.  Please reopen with a repro if this is still an issue.
