### ISSUE TITLE
Devise a convention that is capable of expressing soft version dependencies between client libraries

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#26158]
Currently, there is no way to express soft version dependencies for features across client SDK libraries. For example, tenant discovery is a feature that is implemented across Azure.Core, Azure.Identity, and client libraries such as KeyVault and Storage. The wrong combination of older versions of these clients will render the feature discoverable but non-operational.

There should be a way to express these feature version dependencies and make them discoverable as early as possible in the development cycle.

**Comment by pallavit** [comment]
@christothes do you still see value in implementing this? Are you looking at a way to mention minimum version that supports a feature?

**Comment by christothes** [comment]
It should be an edge case, so perhaps this is not something worth pursuing.
