### ISSUE TITLE
[FEATURE REQ] ClientOptions API for additional "User-Agent" info

### ISSUE THREAD

**Issue by sppatel82** [Azure/azure-sdk-for-net#26151]
Request for easy API to augment User-Agent string at the client options level, rather than requiring a custom-written pipeline policy to be injected into said options.

Original issue text below

> ### Library name and version
> 
> Azure.Storage.Blobs 12.10.0
> 
> ### Query/Question
> 
> In Windows.Azure.Storage Nuget we had a OperationContext class using which we can add our custom user-agent string to API calls to Azure Blob Storage. In the latest Nuget Azure.Storage.Blobs 12.10.0, OperationContext class is not there. Is there any way to set custom user-agent string?
> 
> ### Environment
> 
> _No response_

**Comment by SatishBoddu-MSFT** [comment]
Hello @sppatel82 Thanks for the query. I also didn't see any option for **OperationContext**  for blob client in **Azure.Storage.Blobs**, redirecting this to the service team for their attention and provide you any alternatives/

**Comment by sppatel82** [comment]
Is there any update on this query?

**Comment by amishra-dev** [comment]
Hi @sppatel82 SP, 
This API was removed from V12, we are working on adding it back. Meanwhile you can write a custom HTTP pipeline to set this user agent. Going forward we would like to add an api allowing you to append your user agent string to ours, but that work is yet to start. @jaschrep-msft fyi

**Comment by jaschrep-msft** [comment]
Editing to be a feature request. Current guidance is still to use a custom pipeline policy to augment the user-agent header on a "per-call" setting (as opposed to "per retry"). We recommend not overwriting the header value.

**Comment by jaschrep-msft** [comment]
@JoshLove-msft I've done some investigation on this and it looks like the code for setting this header is fully contained within Azure.Core via `TelemetryPolicy` created by `HttpPipelineBuilder.CreateTelemetryPolicy()`. If a hook were to be made rather than forcing customers to write their own pipeline policy to edit the result of ours, I think it would be best to expose said hook in `Azure.Core.ClientOptions`. Does this seem accurate to you?

**Comment by JoshLove-msft** [comment]
You can append custom application information to the user agent string using the [DiagnosticOptions.ApplicationId](https://docs.microsoft.com/en-us/dotnet/api/azure.core.diagnosticsoptions.applicationid?view=azure-dotnet#azure-core-diagnosticsoptions-applicationid) property. This would be set using the [ClientOptions.Diagnostics](https://docs.microsoft.com/en-us/dotnet/api/azure.core.clientoptions.diagnostics?view=azure-dotnet) property.

**Comment by jaschrep-msft** [comment]
It seems this functionality already exists then? Good to know. Closing this issue accordingly.
