### ISSUE TITLE
Upgrade Microsoft.Rest.ClientRuntime.Azure.Authentication reference to the latest stable ADAL library for all the target frameworks

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-sdk-for-net#2616]
Microsoft.IdentityModel.Clients.ActiveDirectory should be upgraded to version 3.13 or higher for all the frameworks that we support. After upgrade:
1. Preview tag should be removed from the Microsoft.Rest.ClientRuntime.Azure.Authentication package.
2. After publishing new Authentication library TestFramewrok should also be upgraded and republished.
3. Then Azure PowerShell projects should also upgrade their reference to ADAL, Authentication and TestFramework packages.

**Comment by shahabhijeet** [comment]
This work was already done.
Currently we have the following versions 
For .NET 452 we use ADAL 2.28.3
For netStandard 1.4 we use ADAL 3.13.5

**Comment by hidingmode** [comment]
is there support for netcoreapp1.1?

**Comment by Edmund3** [comment]
The original note says that all supported frameworks should use 3.13 or higher but this has been closed with 452 using a lower version. Could you please provide an explanation as to why this is not using the higher version as this is causing issues with certain packages wanting the much higher version?

**Comment by ChadNedzlek** [comment]
Why is the version locked to a specific version? It makes it basically impossible to use these libraries without immediate and unresolvable package dependency problems.

**Comment by aggieben** [comment]
I think it's time to do this again.  The hard dependency on ADAL 2.28.3 is causing me problems in a project I'm working on.  Also, is there any reason why this library wouldn't target netstandard2.0?
