### ISSUE TITLE
[BUG] BOM no longer removed from Service Bus incoming messages on newer extension versions

### ISSUE THREAD

**Issue by hossam-nasr** [Azure/azure-sdk-for-net#26161]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.2.0

### Describe the bug

Some messages sent to a Service Bus queue can include a BOM (Byte Order Mark) (`0xEFBBBF` for UTF-8 encoding) at the beginning of the message, for example if the message is JSON-serialized from a stream. Other messages, for example if using a simple JSON encoding directly on an object, will not have the leading BOM.

In SB extension version `4.3.0`, the BOM is removed on the receiving side by the `ServiceBusTrigger`. The incoming string parameter or `Message.Body` property does not include it. This meant that regardless of how the sender serialized the message, it could still be treated the same way.

In SB extension version `5.2.0`, the BOM is still present on the receiving side when the `ServiceBusTrigger` function executes. This is the case if the Function is binding to a string parameter or `ServiceBusMessage`. As a result, messages that were sent without a BOM will deserialize cleanly without any further processing. Any messages sent with a BOM will throw an exception upon deserializing.

### Expected behavior

The leading BOM is removed from SB queue messages before being sent to the SB queue trigger function, same as the behavior using extension version `4.3.0`.

### Actual behavior

The leading BOM is still present in the arguments received by the SB queue trigger function, which is a different behavior than the older version of the extension.

### Reproduction Steps

The following code sends two messages to a SB queue named `test-sb-queue`, assuming the connection strings are replaced appropriately. One message is created using a stream, and therefore has the leading BOM, while the other is stringified simply and doesn't contain the BOM.

```C#
using System.Globalization;
using System.Text;
using Azure.Messaging.ServiceBus;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

try {
    string payload = "Hello";

    {
        // send payload with stream
        var payloadStream = CreatePayloadWithStream(payload);
        Console.WriteLine("Now sending a message serialized from a stream.");
        Console.WriteLine($"Payload bytes: {Convert.ToHexString(payloadStream)}");
        var message = new ServiceBusMessage(payloadStream);
        var client = new ServiceBusClient(/*REPLACE WITH OWN CONNECTION STRING*/);
        var sender = client.CreateSender("test-sb-queue");
        await sender.SendMessageAsync(message);
    }

    {
       // send simple payload
        var payloadSimple = CreatePayloadSimple(payload);
        Console.WriteLine("Now sending a message serialized simply.");
        Console.WriteLine($"Payload bytes: {Convert.ToHexString(payloadSimple)}");
        var message = new ServiceBusMessage(payloadSimple);
        var client = new ServiceBusClient(/* REPLACE WITH OWN CONNECTION STIRNG */);
        var sender = client.CreateSender("test-sb-queue");
        await sender.SendMessageAsync(message);
    }
} catch (Exception e) {
    Console.WriteLine(e);
}

/// Serialize payload by creating a unicode string with a stream. This results in BOM added to beginning 
/// of string.
static byte[] CreatePayloadWithStream(string message)
{
    JsonSerializerSettings serializerSettings = new JsonSerializerSettings
    {
        TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Simple,
        TypeNameHandling = TypeNameHandling.None,
        Converters = { new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.RoundtripKind } }
    };
    JsonSerializer serializer = JsonSerializer.Create(serializerSettings);

    var stream = new MemoryStream();

    var streamWriter = new StreamWriter(stream, Encoding.UTF8);
    var jsonWriter = new JsonTextWriter(streamWriter) { Formatting = Formatting.None };
    serializer.Serialize(jsonWriter, message);
    jsonWriter.Flush();
    stream.Position = 0;

    return stream.ToArray();
}

/// Serialize payload by just calling JsonConvert.SerializeObject(). This doesn't 
/// result in BOM added to beginning of string.
static byte[] CreatePayloadSimple(string messagePayload)
{
    var item = JsonConvert.SerializeObject(messagePayload);

    return Encoding.UTF8.GetBytes(item);
}
```

Running the above code yields the following output:

```
Now sending a message serialized from a stream.
Payload bytes: EFBBBF2248656C6C6F22
Now sending a message serialized simply.
Payload bytes: 2248656C6C6F22
```

The leading BOM (`0xEFBBBF`) is present in the first message, but not the second.

Now, we can write a simple SB queue trigger function to see how the messages are received.

```C#
using System;
using System.Text;
using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace Company.Function
{
    public class ServiceBusQueueTrigger1
    {
        [FunctionName("ServiceBusQueueTrigger1")]
        public void Run([ServiceBusTrigger("test-sb-queue", Connection = "testsb")]string myQueueItem, ILogger log)
        {
            log.LogInformation($"String: {myQueueItem}");
            var bytes = Encoding.UTF8.GetBytes(myQueueItem);
            log.LogInformation($"Bytes: {Convert.ToHexString(bytes)}");
            // attempting to deserialize here will throw an error in newer versions of the extension
            var deserialized = JsonConvert.DeserializeObject<string>(myQueueItem);
        }
    }
}
```

Running the above function using version `4.3.0` of the extension yields the following output:

```
String: "Hello"
Bytes: 2248656C6C6F22
String: "Hello"
Bytes: 2248656C6C6F22
```

The old extension version removes the leading BOM and the message can be handled the same way, regardless of how it was encoded. The function does not throw an error on attempting to deserialize the incoming message.

However, running the same function using extension version `5.2.0` yields the following output:

```
String: ?"Hello"
Bytes: EFBBBF2248656C6C6F22
String: "Hello"
Bytes: 2248656C6C6F22
```

The BOM is still present at the start of the message. An error is thrown on attempting to deserialize since the string starts with an invalid character:

```System.Private.CoreLib: Exception while executing function: ServiceBusQueueTrigger1. Newtonsoft.Json: Unexpected character encountered while parsing value: ?. Path '', line 1, position 1.```

### Environment

Window 11 (OS Version 10.0.22000) with .NET version 6.0.1.
Verified on VS Code and Visual Studio 2022

**Comment by JoshLove-msft** [comment]
You are correct that the new version of the extension does not strip out the BOM. The data in ServiceBusMessage.Body and when binding to a string is representing the data that was sent _as-is_.
The default behavior when using StreamWriter without specifying an encoding would be to emit UTF8 without a BOM. Would it be possible to just not add a BOM when sending?
If this is not possible, you could strip off the BOM yourself by constructing a UTF8Encoding instance with the [constructor](https://docs.microsoft.com/en-us/dotnet/api/system.text.utf8encoding.-ctor?view=net-6.0#System_Text_UTF8Encoding__ctor_System_Boolean_) that allows you to specify whether a BOM should be included.

Would either of these options work?

**Comment by hossam-nasr** [comment]
Thanks for the quick response! I opened this ticket on behalf of a customer who filed an IcM incident saying they have a lot of functions in production that rely on the old behavior and changing the code of each function (or each application that sends messages) would have to touch a lot of their codebase. Is there a solution that doesn't require code changes? 

Also, is there a reason the behavior was changed? We thought this was a bug rather than an intentional change. Was it mentioned in the release notes somewhere? Thanks!

**Comment by JoshLove-msft** [comment]
> Thanks for the quick response! I opened this ticket on behalf of a customer who filed an IcM incident saying they have a lot of functions in production that rely on the old behavior and changing the code of each function (or each application that sends messages) would have to touch a lot of their codebase. Is there a solution that doesn't require code changes?

No, I don't think there is a way to avoid code changes. Code changes are likely necessary anyway when upgrading to the new version.

> Also, is there a reason the behavior was changed? We thought this was a bug rather than an intentional change. Was it mentioned in the release notes somewhere? Thanks!

The message body is stored in a BinaryData instance. We considered excluding the BOM from the BinaryData.ToString() method when adding this type, but we were [advised](https://github.com/Azure/azure-sdk-for-net/pull/16248#discussion_r512099122) not to by the .NET folks. This behavior was carried forward to the string binding, as it would be strange if the ToString of the message body and the string binding values differed. I don't believe this was mentioned in the release notes anywhere.

**Comment by hossam-nasr** [comment]
That makes sense, thank you! Will get back to the cx with this feedback. Closing this issue.
