### ISSUE TITLE
[BUG] ActivityLogAlertResource.Condition only allows AllOf type conditions

### ISSUE THREAD

**Issue by jamesstanleystewart** [Azure/azure-sdk-for-net#26178]
### Library name and version

Azure.ResourceManager.Insights 1.0.0-preview.1

### Describe the bug

As described in the docs here: 
https://docs.microsoft.com/en-us/rest/api/monitor/activity-log-alerts/update#alertruleanyoforleafcondition 
and here: 
https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/activitylogalerts?tabs=bicep#alertruleanyoforleafcondition

Activity log alerts should be able to be created with a mix of AllOf and AnyOf conditions however the type of the Condition field is `ActivityLogAlertAllOfCondition` and that only allows a list of `ActivityLogAlertLeafCondition`, with no option to add an AnyOf clause.

I think it is possible to work around this by creating one alert per item that I want in the AnyOf, but this approach would get much more complex in some use cases and I shouldn't need to do this.

### Expected behavior

`ActivityLogAlertResource` can be created with AllOf and AnyOff conditions as in API+ARM documentation

### Actual behavior

Only AllOf conditions are available

### Reproduction Steps

```csharp
  var alert = new ActivityLogAlertResource("global") {
      Description = "Azure resource health alerts",
      Enabled = true,
      Scopes = { },
      Actions = new ActivityLogAlertActionList() {
          ActionGroups = {
              new ActivityLogAlertActionGroup(actionGroup.Id)
          }
      },
      Condition = new ActivityLogAlertAllOfCondition(new[] {
          new ActivityLogAlertLeafCondition("category", "ResourceHealth"),
          new ActivityLogAlertLeafCondition("status", "Active"),

          //I want this to be an AnyOf like I have in my bicep
          new[] {
              new ActivityLogAlertLeafCondition("resourceType", "Microsoft.Compute/virtualMachines"),
              new ActivityLogAlertLeafCondition("resourceType", "Microsoft.Storage/storageAccounts")
          }

      },
  };
```

### Environment

Windows, Dotnet Core 6, Rider IDE (I don't think any of this matters, the models required just aren't present)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@jamesstanleystewart  this lib will be deprecated soon, but we will check it in new release

**Comment by ArcturusZhang** [comment]
HI @jamesstanleystewart sorry for the inconvenience, but the SDK you are using was made from an old api-version of monitor. In that api-version, the AnyOfOrLeafCondition was not yet supported therefore you cannot set it.

We are making a new version of monitor RP in this PR, along with the API redesign, we also update the api-version we are using, therefore the AnyOf will be supported there. Check it out in this PR: https://github.com/Azure/azure-sdk-for-net/pull/26023/files

**Comment by ArcturusZhang** [comment]
Hi we already released the new monitor SDK that includes the missing property: https://www.nuget.org/packages/Azure.ResourceManager.Monitor
Please notice that the namespace `Azure.ResourceManager.Insights` has been deprecated and no longer supported
