### ISSUE TITLE
What is replacement/updated method for CryptoKeyGenerator.GenerateKey(Int32)?

### ISSUE THREAD

**Issue by m-chau** [Azure/azure-sdk-for-net#26179]
This page says that this method is going to obsolete and deprecated in the future but offer no alternative solution on how to move away from this method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9ff4e17-b177-be41-c0f6-b24f1458e8ab
* Version Independent ID: a8acaf6e-a0f1-6422-aba1-c46b36311592
* Content: [CryptoKeyGenerator.GenerateKey(Int32) Method (Microsoft.Azure.Devices.Common) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.common.cryptokeygenerator.generatekey?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Devices.Common/CryptoKeyGenerator.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Common/CryptoKeyGenerator.xml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `MicrosoftAzure.Devices` package is maintained as [#2265](https://github.com/Azure/azure-iot-sdk-csharp/issues/2265).
