### ISSUE TITLE
[QUERY] [Azure.Messaging.EventGrid] DeadLetter questions

### ISSUE THREAD

**Issue by RDavis3000** [Azure/azure-sdk-for-net#26198]
### Library name and version

Azure.Messaging.EventGrid 4.7.0

### Query/Question

Hi, I've scoured the internet and cant find any docos or info about this, I hope you can help me please!

1) What are the possible values of "deadLetterReason"?
2) What are the causes of these values? (Is this documented anywhere?)
3) Specifically, what is "UndeliverableDueToProbationCausedByClientError" and how am I causing it? (I presume I'm causing it?)
4) What's the logic behind the batching of dead letter models into the json? Some files have only a single record, others have 10, the records don't seem to be associated in any obvious way.

My retries is set to 10 and TTL 2 hours (the portal defaults) for the examples below.

```json
[
	{
		"id": "ed68f4df-8176-4e8c-8109-255d8619048f",
		"eventTime": "2022-01-06T10:23:31.9592085Z",
		"eventType": "ITwoCX.DocSettingsAvailable",
		"dataVersion": "1.0",
		"metadataVersion": "1",
		"topic": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.EventGrid/topics/xxxx",
		"subject": "ITwoCX.DocSettingsAvailable",
		"deadLetterReason": "UndeliverableDueToProbationCausedByClientError",
		"deliveryAttempts": 3,
		"lastDeliveryOutcome": "Probation",
		"publishTime": "2022-01-06T10:23:31.9953958Z",
		"lastDeliveryAttemptTime": "2022-01-06T10:24:55.5560219Z",
		"data": {[REDACTED]}		
	},
	{
		"id": "75b7f0a3-33c7-4b7e-8ea6-fb892420263e",
		"eventTime": "2022-01-06T10:23:30.5723795Z",
		"eventType": "ITwoCX.DocSettingsAvailable",
		"dataVersion": "1.0",
		"metadataVersion": "1",
		"topic": "/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.EventGrid/topics/xxxx",
		"subject": "ITwoCX.DocSettingsAvailable",
		"deadLetterReason": "UndeliverableDueToProbationCausedByClientError",
		"deliveryAttempts": 3,
		"lastDeliveryOutcome": "Probation",
		"publishTime": "2022-01-06T10:23:30.5603343Z",
		"lastDeliveryAttemptTime": "2022-01-06T10:24:55.5560219Z",
		"data": {
[REDACTED]
		}
	},
	{
		"id": "6f0a93aa-4a94-47b3-840e-aaa8e85cf73a",
		"eventTime": "2022-01-06T10:24:01.2521170Z",
		"eventType": "ITwoCX.DocSettingsAvailable",
		"dataVersion": "1.0",
		"metadataVersion": "1",
		"topic": "/subscriptions/xxxx/resourceGroups/rg-d-lxr-aue-ingestion/providers/Microsoft.EventGrid/topics/xxxx",
		"subject": "ITwoCX.DocSettingsAvailable",
		"deadLetterReason": "UndeliverableDueToProbationCausedByClientError",
		"deliveryAttempts": 3,
		"lastDeliveryOutcome": "Probation",
		"publishTime": "2022-01-06T10:24:01.2367276Z",
		"lastDeliveryAttemptTime": "2022-01-06T10:24:55.5560219Z",
		"data": {
			[REDACTED]
		}
	},
```

### Environment

Azure Event Grid

**Comment by navba-MSFT** [comment]
@RDavis3000 Thanks for your question. We sincerely apologize for the delay in getting back to you. Please find below my answers inline to your question:

1. What are the possible values of "deadLetterReason"? 
2. What are the causes of these values? (Is this documented anywhere?)

The System defined deadletter reasons and its descriptions are explained in [this](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues#moving-messages-to-the-dlq) article. Applications can also define their own codes for the dead-letter reason property as mentioned [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-dead-letter-queues#application-level-dead-lettering).

3. Specifically, what is "UndeliverableDueToProbationCausedByClientError" and how am I causing it? (I presume I'm causing it?)

UndeliverableDueToProbationCausedByClientError --> This points to the client side error.

From the DeadLetter Event You can rely on the _lastDeliveryOutcome_ field to know the reason for the issue:
Probation | Destination is put in probation by Event Grid. Delivery isn't attempted during probation
--|--
 
[Here](https://docs.microsoft.com/en-us/azure/event-grid/delivery-and-retry#dead-letter-event) is the reasoning for Probation from the docs. You can isolate the issue and find the error by checking the [EventGrid Metrics ](https://docs.microsoft.com/en-my/azure/event-grid/metrics#event-subscriptions) for DeadLetteredEvents and DeliveryFailedEvents metrics and checking the dimensions  DeadLetterReason, Error and ErrorType.

> **LastDeliveryOutcome: Probation**
> An event subscription is put into probation for a duration by Event Grid if event deliveries to that destination start failing. Probation time is different for different errors returned by the destination endpoint. If an event subscription is in probation, events may get dead-lettered or dropped without even trying delivery depending on the error code due to which it's in probation.
> 
> Error | Probation Duration
> -- | --
> Busy | 10 seconds
> NotFound | 5 minutes
> SocketError | 30 seconds
> ResolutionError | 5 minutes
> Disabled | 5 minutes
> Full | 5 minutes
> TimedOut | 10 seconds
> Unauthorized | 5 minutes
> Forbidden | 5 minutes
> InvalidAzureFunctionDestination | 10 minutes
> 


4. What's the logic behind the batching of dead letter models into the json? Some files have only a single record, others have 10, the records don't seem to be associated in any obvious way.

Event Grid's [Batching policy](https://docs.microsoft.com/en-us/azure/event-grid/delivery-and-retry#batching-policy) and [Batching behavior](https://docs.microsoft.com/en-us/azure/event-grid/delivery-and-retry#batching-behavior) are explained here in detail. 

Hope this helps. If you have any queries around this, please feel free to get back to us.

**Comment by navba-MSFT** [comment]
@RDavis3000 This is a quick follow-up to check if you had a chance to look at my above comment. If you need further assistance, please feel free to get back to us on this thread.

**Comment by RDavis3000** [comment]
@navba-MSFT 
Thanks there is a lot of good information here and I now understand what was going on with my code. It turns out it was because I was shutting the function app down (in DEV) and assumed that EG would just wait indefinitely! So wasn't a problem with my code but with my understanding of the loose coupling between EG and subscriber state. Now that I've read everything you sent the behavior make sense.

Regarding the specific deadLetterReason: "UndeliverableDueToProbationCausedByClientError", this isn't mentioned anywhere in the links you shared. Is that because its application defined (by Azure Functions) or is it possibly something which could/should be in the docs? Is this the reason raised when EG doesn't even try to deliver it because a subscription is on probation? I've got a pretty short TTL for some of these events, and a 10 minute probation would mean they would have expired, is it possibly what was happening?

From [link](https://docs.microsoft.com/en-us/azure/event-grid/delivery-and-retry#dead-letter-event):
" If an event subscription is in probation, events may get dead-lettered or dropped without even trying delivery depending on the error code due to which it's in probation."
Is there any more information available about the circumstances this can happen? A state diagram would be awesome :)

With batching its 'all or none' for delivery success and by extension also for dead-lettering, is that correct? So whatever batching strategy the publisher is using will be reflected in the dead letter json files. In the examples I have, all the DeadLetterEvents have a deadLetterReason of "TimeToLiveExceeded" which makes sense. Can you tell me in the case where a single event failed and caused the whole batch to be dead lettered, would all the events have the same dead letter reason or would the one which actually failed have a different one to the rest?

Thanks so much.

**Comment by navba-MSFT** [comment]
@RDavis3000  Thanks for getting back. I did some research around this and sharing you the below details if it helps. 

As per [this](https://docs.microsoft.com/en-us/azure/event-grid/delivery-and-retry#dead-letter-events) article:
> Event Grid dead-letters an event when one of the following conditions is met.
> 
> 1. Event isn't delivered within the time-to-live period.
> 2. The number of tries to deliver the event has exceeded the limit.
> If either of the conditions is met, the event is dropped or dead-lettered. By default, Event Grid doesn't turn on dead-lettering. To enable it, you must specify a storage account to hold undelivered events when creating the event subscription. You pull events from this storage account to resolve deliveries.

Also Probation just means the EG subscription endpoint is repeatedly unreachable or returning errors. This will cause EG to skip the typical retry. Meaning, 'probation' is used when the destination is not reachable or unhealthy or it cannot handle the load. 

If you have configured both event-ttl and max-deliver-attempts, Event Grid uses the first to expire to determine when to stop event delivery. For example, if you set 30 minutes as time-to-live (TTL) and 10 max delivery attempts, when an event isn't delivered after 30 minutes (or) isn't delivered after 10 attempts, whichever happens first, the event is dead-lettered. 

'TimeToLiveExceeded' means that an event has expired when we were about to deliver, regardless of if there were actual attempts to deliver. For instance, if the destination  is unhealthy or cannot handle the load, we put the destination on probation. When a destination is on probation we do not attempt to deliver. In this case the event can expire before any attempt to deliver is made.

Hope this helps.

**Comment by navba-MSFT** [comment]
@RDavis3000 Hope you had a chance to look at my above comment. For now, I am proceeding with the closure of this thread. If you need any further assistance, please feel free to get back to us. We would be happy to assist you further on this.

**Comment by RDavis3000** [comment]
@navba-MSFT 

Thanks for the response.
There are still some gaps for me:

In reference to the section 'LastDeliveryOutcome: Probation' in the link you provided:
1)
There is a table of error codes and the respective Probation Durations for them; how do I know which error code has caused my subscription to go into probation?

2)
"If an event subscription is in probation, events may get dead-lettered or dropped without even trying delivery depending on the error code due to which it's in probation."

There is no specification of which error codes cause this behavior. Which error codes will cause the event to not be retried at all?

3) Is it possible to determine the state of a subscription from the Az Powershell module, or similar? There is nothing in the portal that I can see.

This is relevant to me because I am struggling to understand why so may of my events are ending up dead-lettered. Just now I ran a process where about 27,000 events were published and there were zero unhandled exceptions on a consumption plan. Everything went smoothly except right at the end of the processing (circled in yellow) all of a sudden events are being dead lettered.

![image](https://user-images.githubusercontent.com/16304586/153697944-d5d53598-d6ac-4373-9fcc-719b95fdf10d.png)

The dead-letter record shows delivery was only attempted once, can you help me understand why this message wasn't delivered?

[
	{
		"id": "0ecd4562-52a9-461d-b98a-f1bbad23926b",
		"eventTime": "2022-02-12T04:44:57.1417311Z",
		"eventType": "ITwoCX.DocBlobWritten",
		"dataVersion": "1.0",
		"metadataVersion": "1",
		"topic": "/subscriptions/814f37ac-6bb0-4108-9c29-72909f9eef1e/resourceGroups/rg-d-lxr-aue-ingestion/providers/Microsoft.EventGrid/topics/egt-d-lxr-aue-ingestion",
		"subject": "ITwoCX.DocBlobWritten",
		"deadLetterReason": "TimeToLiveExceeded",
		"deliveryAttempts": 1,
		"lastDeliveryOutcome": "Probation",
		"publishTime": "2022-02-12T04:44:57.1930759Z",
		"lastDeliveryAttemptTime": "2022-02-12T04:44:57.1980811Z",
		"data": {
			"IngestionRequestInstanceId": "4eaa3137-e07d-4400-ba9b-39556db96c69",
			"SourceIngestionRequestInstanceStepId": "1e33ddb3-aefb-4f39-87d9-84358b8832e2",
			"EventModel": {
				"DocumentId": 13801411,
				"DocumentFileName": "/xxx/4eaa3137-e07d-4400-ba9b-39556db96c69/Documents/13801411.json",
				"ITwoCXRequestPayloadModel": {
					"BaseURL": "https://au.itwocx.com/",
					"Password": "xxxx",
					"EmailAddress": "xxx",
					"Project": "xxx",
					"DeltaFromUTC": "0001-01-01T00:00:00",
					"HasDelta": true,
					"GetDeltaEpochAEST": 396000000000,
					"GetDeltaEpochUTC": 0
				}
			}
		}
	}
]

**Comment by navba-MSFT** [comment]
@RDavis3000 Thanks for your reply. This needs to be investigated in detail by looking into our logs. We would be happy to troubleshoot this issue to identify the root cause. Would you be able to open a support ticket for this issue ? So that one of our support professional can work with you until resolution.

**Comment by RDavis3000** [comment]
@navba-MSFT 
I will raise a support ticket for this specific issue, but could you answer my more general questions. These will be useful for people who come searching later :)

In reference to the section 'LastDeliveryOutcome: Probation' in the link you provided:
1)
There is a table of error codes and the respective Probation Durations for them; how do I know which error code has caused my subscription to go into probation?

2)
"If an event subscription is in probation, events may get dead-lettered or dropped without even trying delivery depending on the error code due to which it's in probation."

There is no specification of which error codes cause this behavior. Which error codes will cause the event to not be retried at all?

3)
Is it possible to determine the state of a subscription from the Az Powershell module, or similar? There is nothing in the portal that I can see.

**Comment by navba-MSFT** [comment]
@RDavis3000  Please find below the answers inline to your question:

>1.	There is a table of error codes and the respective Probation Durations for them; how do I know which error code has caused my subscription to go into probation?
>> **Answer:** As mentioned earlier, Delivery failure metric has an additional dimension to indicate “error type” and “error”.  These may not provide the exact detail you are hoping for. So to get more information about delivery failures, you will need to enable diagnostic logs. Please refer to  [Azure Event Grid - Enable diagnostic logs for Event Grid resources - Azure Event Grid | Microsoft Docs](https://docs.microsoft.com/en-us/azure/event-grid/enable-diagnostic-logs-topic#prerequisites)

>2.	"If an event subscription is in probation, events may get dead-lettered or dropped without even trying delivery depending on the error code due to which it's in probation." There is no specification of which error codes cause this behavior. Which error codes will cause the event to not be retried at all?
>>  **Answer:** When in probation, the delivery is skipped and moved to the next retry queue.  The service would consider this as a failed delivery attempt. While waiting in the retry queue, the max “time to live” condition might have been met which results in drop/dead-lettering.  Similarly max retry attempts would have been met which results in drop/dead lettering. 
There are some non-transient errors like ‘unauthorized’ or ‘bad request’ which are not retried.  You can refer to this section for which errors are not retried.  [Azure Event Grid delivery and retry - Azure Event Grid | Microsoft Docs.  ](https://docs.microsoft.com/en-us/azure/event-grid/delivery-and-retry#failure-codes)

>3.	Is it possible to determine the state of a subscription from the Az Powershell module, or similar? There is nothing in the portal that I can see.
>> **Answer:** Right now Probation is not a permanent state. It is a transient runtime state to avoid degenerative cases like not respecting “server busy” errors and making the performance of the destination resource even worse. We have cases where the “Destination failures” are permanent and they don’t go away. For those cases it makes sense to “disable” the subscription and make the user “re-enable” the subscription after fixing the destination failures. That feature does not exist today.

Hope this answers. To troubleshoot and isolate your above issue, Please open a support ticket and we would be happy to assist you further.
