### ISSUE TITLE
[FEATURE REQ] Support version 2019-05-06 of REST API in Azure.Search.Documents

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#26197]
### Library name

Azure.Search.Documents

### Please describe the feature.

My team (nuget.org) is working on moving to Azure.Search.Documents. We are currently using Microsoft.Azure.Search 5.0.3. Our main motivation is using the managed identities authentication flow. Overall, the move was relatively painless -- aside from some problems with polymorphism limitations in System.Text.Json (just like https://github.com/Azure/azure-sdk-for-net/issues/17685) which was resolved with a custom JSON converter.

However our team is very sensitive to changes in search result ranking. In Azure.Search.Documents, it is not possible (from my tests -- could be wrong) to use the classic similarity. Only the BM25 similarity (introduced in the API version 2020-06-30) is allowed. The default if none is specified is BM25 and classic similarity is rejected (HTTP 400) when an index creation is attempted.

This makes our migration to the new SDK higher risk. Essentially we are forced to couple a massive code change (new SDK) with a relevance change (BM25 instead of classic similarity). Ideally we could move to the new SDK with a matching API version and then separately evaluate and test the BM25 change enforced in the new API version.

I am going to attempt a dirty hack where we inject a special HTTP handler into HTTP pipeline that allows us to override the API version query parameter so that the index creation request can trick the server side into letting us make an index with classic similarity, but this is not ideal and assumes compatibility on the index creation endpoint between the two API versions.

Great work on the SDK by the way, we're seeing great performance improvements. On some load tests, the old SDK was getting 400 RPS on our service. New SDK is getting ~600 RPS with comparable request durations and CPU/memory metrics.

My current diff is here (without the aforementioned dirty hack) if you're interested in what a migration like this looks like: https://github.com/NuGet/NuGet.Jobs/compare/dev...jver-sdk-cmp

**Comment by Mohit-Chakraborty** [comment]
Thanks for your feedback Joel. Would love to know when the switch to `Azure.Search.Documents` completes.
Adding @dereklegenzoff and @giamordigan for the ranking algorithm details and if there are alternate ways to control it.

**Comment by joelverhagen** [comment]
@Mohit-Chakraborty - yes, I'll try to touch base offline. Our general migration plan is:

1. Roll out new SDK (ideally with no relevance changes)
3. Switch to managed identities
2. (optional) Upgrade from .NET Core 3.1 to .NET 6
4. Switch to BM25

This issue is about decoupling steps 1 and 4 to reduce risk (just to be clear).

**Comment by dereklegenzoff** [comment]
Hi @joelverhagen - I think what you might be running into is that new search services created after July 15th, 2020 can only use BM25. Older services will allow you to use both BM25 and TF/IDF (classic similarity). There're some more details here: https://docs.microsoft.com/en-us/azure/search/index-ranking-similarity

**Comment by joelverhagen** [comment]
I think there is a nuance or ... secret (?) in the implementation of this migration. If you create a new index using the old SDK, you still get classic similarity, even today. So if you swap out the API version query string and leave the similarity property out of the request body, the new SDK can do the same.

This is the applied similarity after using my "dirty hack" per Azure Portal index definition JSON:
![image](https://user-images.githubusercontent.com/94054/148608759-f2ec0fa9-e41d-49f3-9c0b-818fc1abf23a.png)

Dirty hack:
```csharp


    public class CreateIndexApiVersionHack : DelegatingHandler
    {
        private const string ExpectedPathAndQuery = "/indexes?api-version=2020-06-30";
        private const string QueryReplacement = "api-version=2019-05-06";

        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            if (request.Method == HttpMethod.Post
                && request.RequestUri.PathAndQuery == ExpectedPathAndQuery)
            {
                var uriBuilder = new UriBuilder(request.RequestUri);
                uriBuilder.Query = QueryReplacement;
                request.RequestUri = uriBuilder.Uri;
            }

            return base.SendAsync(request, cancellationToken);
        }
    }
```

Registration in my DI container:
```csharp
            services.AddTransient<HttpPipelineTransport>(p =>
            {
                var httpClientHandler = p.GetRequiredService<HttpClientHandler>();
                var apiVersionHack = new CreateIndexApiVersionHack { InnerHandler = httpClientHandler };
                return new HttpClientTransport(apiVersionHack);
            });
```

**Comment by joelverhagen** [comment]
BTW, I tested this hack to get `ClassicSimilarity` end-to-end. It works just fine.
https://github.com/NuGet/NuGet.Jobs/commit/52e8245e2052f130d71575fae8a44e70ec6fd02c

**Comment by dereklegenzoff** [comment]
Awesome, glad you were able to find a workaround!
