### ISSUE TITLE
[BUG] Azure.Messaging.ServiceBus.ServiceBusException: 'sender179' is closed (GeneralError)

### ISSUE THREAD

**Issue by deivyd321** [Azure/azure-sdk-for-net#26207]
### Library name and version

Azure.Messaging.ServiceBus 7.3.0

### Describe the bug

Hi, occasionally I am this error(sender number changes during the time):
```text
_Azure.Messaging.ServiceBus.ServiceBusException: 'sender179' is closed (GeneralError)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(IEnumerable`1 messages, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendBatchAsync>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__20`1.<<RunOperation>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchAsync(ServiceBusMessageBatch messageBatch, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusSender.SendMessagesAsync(ServiceBusMessageBatch messageBatch, CancellationToken cancellationToken)_
```

My code:

```csharp
        public async Task PublishAsync(IDomainEventBase<IEventData> domainEventBase)
        {
            var eventName = domainEventBase.GetType().Name;
            var sender = GetOrCreateSender(eventName);

            var serializedEvent = SerializeObject(domainEventBase);
            var message = new ServiceBusMessage(serializedEvent)
            {
                Subject = domainEventBase.EventType
            };

            await sender.SendMessageAsync(message);

            _telemetryClientService.TrackEvent(domainEventBase.Data.ToDictionary(), eventName);
        }
```

I have contacted the Azure Service support but it didn't provide me any details. The only suggestion was implementing retry and a link to [msdn doc.](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.retrypolicy?view=azure-dotnet)

However, how should I implement retry? I am using the default retry option so it should be retried by default. I see that these failures are happening very shortly and quite rarely but at that moment all my service bus's "Send" operations fails. Can there be an issue on Service Bus side? But then how can I rely on ServiceBus while it has a shortage every two days. At the moment Service Bus Send operations are quite critical for my application so it would be nice to resolve this kind of issues.

### Expected behavior

Service bus events should be published.

### Actual behavior

Service bus event is not published.

### Reproduction Steps

These error are seemed in Application Insights

### Environment

Asp.Net Core 5

**Comment by jsquire** [comment]
Hi @deivyd321.  Thank you for reaching out and we regret that you're experiencing difficulties.   The exception that you're seeing indicates that the sender that you're using has been closed.  This can occur if you call `CloseAsync` or `DisposeAsync` on the sender itself or the `ServiceBusClient` that it was spawned from.

In your code snippet, I notice that you're calling a factory method, `GetOrCreateSender`.   Would you be able to share the implementation of that, as well as details around how the client and sender are created and destroyed in your application?

**Comment by deivyd321** [comment]
Thank you for your response. Sure.

```
        private readonly ConcurrentDictionary<string, ServiceBusSender> _sendersByQueueName = new();

        private readonly ServiceBusClient _client;
        private readonly ITelemetryClientService _telemetryClientService;
        private const int MaximumAllowedMessagesPerServiceBusBatch = 100;

        public ServiceBusPublisher(
            ServiceBusClient client,
            ITelemetryClientService telemetryClientService)
        {
            _client = client;
            _telemetryClientService = telemetryClientService;
        }
```

```
        private ServiceBusSender GetOrCreateSender(string queue)
        {
            return _sendersByQueueName.GetOrAdd(queue, _client.CreateSender(queue));
        }
```
They are added as singletons.
```
services.AddSingleton(_ => new ServiceBusClient(serviceBusOptions));
services.AddSingleton<IEventPublisher, ServiceBusPublisher>();
```

**Comment by JoshLove-msft** [comment]
Hi @deivyd321, 
Would you be able to enable Verbose logging so that we can get more information?
https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging#enable-logging-with-built-in-methods

**Comment by JoshLove-msft** [comment]
Reached out to the owner of the AMQP library, and it sounds like we should be retrying on this error.

**Comment by deivyd321** [comment]
Thanks. I have added verbose logging but it will take a few days to see the logs.

**Comment by LeszekKalibrate** [comment]
Apology for interrupting, but I would suggest to add (in your factory) check for sender.IsCLosed() before returning it. If closed then create a new one.

Apology again, but as this is about sender and factory I would ask dear Coders about that missing factory in ASB ServiceClient?
The built in DI method for adding an AzureServiceBus client factory doesn't internally track senders. It seems an oversight on Microsoft's part that you can use it to track clients (using a key, much like you have) but when you ask the client for a sender, you just get a new one every time. 
This seems to violate MS's own best practice guide?

Thank you.

**Comment by deivyd321** [comment]
@LeszekKalibrate thank you
