### ISSUE TITLE
ServiceBus fails to send messages if folder contains Microsoft.Azure.Amqp version 2.5.8 instead of 2.5.6

### ISSUE THREAD

**Issue by klioqc** [Azure/azure-sdk-for-net#26209]
The following exception is thrown when output folder contains Microsoft.Azure.Amqp version= 2.5.8  and 'Azure.Messaging.ServiceBus version=7.5.1.0:

The type initializer for 'Azure.Messaging.ServiceBus.Amqp.AmqpTransactionManager' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Azure.Messaging.ServiceBus.Amqp.AmqpTransactionManager' threw an exception.
 ---> System.TypeLoadException: Method 'OnCreateAsync' in type 'Azure.Messaging.ServiceBus.Amqp.AmqpTransactionEnlistment' from assembly 'Azure.Messaging.ServiceBus, Version=7.5.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.
   at Azure.Messaging.ServiceBus.Amqp.AmqpTransactionManager..ctor()
   at Azure.Messaging.ServiceBus.Amqp.AmqpTransactionManager..cctor()
   --- End of inner exception stack trace ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpTransactionManager.get_Instance()
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(IEnumerable`1 messages, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(IEnumerable`1 messages, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendBatchAsync>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__20`1.<<RunOperation>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchAsync(ServiceBusMessageBatch messageBatch, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusSender.SendMessagesAsync(ServiceBusMessageBatch messageBatch, CancellationToken cancellationToken)

This is because after version 2.5.6 Microsoft.Azure.Amqp contains breaking change: base class named Singleton changed OnCreateAsync method parameters and Azure.Messaging.ServiceBus.Amqp.AmqpTransactionManager cannot be instantiated anymore as abstract method is not implemented.

Note that assembly version of Microsoft.Azure.Amqp did not change at all. I don't think it is correct way to do breaking changes.

**Comment by klioqc** [comment]
![image](https://user-images.githubusercontent.com/2091149/148563988-c9262aa1-bdbc-4851-a387-02483736c692.png)

**Comment by klioqc** [comment]
![image](https://user-images.githubusercontent.com/2091149/148564192-5ee64c24-7e65-4413-9452-12e8eb499aa0.png)

**Comment by jsquire** [comment]
Looks like this was a breaking change in the `Microsoft.Azure.Amqp` library, introduced in v2.5.7 by [this commit](https://github.com/Azure/azure-amqp/commit/68d1cef88008c4d9525303eb40c0f07b2e13d928).  I'll open an issue in the repository where the AMQP package is maintained and also reach out to the team that owns the package to see if they're able to make a patch release.

In the meantime, are you able to revert to v2.5.6 of the AMQP package?

**Comment by klioqc** [comment]
yes, it works fine if 2.5.6 is used. We had to revert and ensure that all references point to 2.5.6

**Comment by jsquire** [comment]
Thank you for confirming, @klioqc.    We've opened [#213](https://github.com/Azure/azure-amqp/issues/213) and submitted [#214](hub.com/Azure/azure-amqp/pull/214) in the repository where the AMQP package is maintained.  We've also started an internal discussion with the owners of the `Microsoft.Azure.Amqp` library, asking for them to help get a fix out and delist v2.5.8 from NuGet.

**Comment by jsquire** [comment]
Version 2.5.9 of the `Microsoft.Azure.Amqp` package has been published (and 2.5.8 has been de-listed.)   I was able to successfully run a project that referenced and used both 2.5.9 and the latest Service Bus GA.   Please let us know if you continue to see issues after upgrading.

**Comment by klioqc** [comment]
Well, it is still not working, because now Service bus does not implement new abstract method added :)
You have:
    [EditorBrowsable(EditorBrowsableState.Never)]
    protected virtual Task<TValue> OnCreateAsync(TimeSpan timeout) => this.OnCreateAsync(timeout, CancellationToken.None);

But you don't have:
    protected abstract Task<TValue> OnCreateAsync(
      TimeSpan timeout,
      CancellationToken cancellationToken);

**Comment by jsquire** [comment]
@klioqc:  Would you be willing to share your repro?   I want to be sure that we're validating the correct scenario.

**Comment by klioqc** [comment]
We have a huge project, so it will take time to do that. But  I think if you take your Azure.Messaging.ServiceBus project  and try to build using Microsoft.Azure.Amqp v2.5.9 reference you will see the build error.

**Comment by jsquire** [comment]
I think that I see the issue; the AMQP library added a new abstract that we missed when fixing their API compatibility.

**Comment by klioqc** [comment]
[SBRepro.zip](https://github.com/Azure/azure-sdk-for-net/files/7831531/SBRepro.zip)
here is a test project

**Comment by jsquire** [comment]
Much appreciated, @klioqc.   That will help to be sure that we're not overlooking any specific cases that you're hitting.   We're also going to go through and do some deeper validation on our side against the source for Service Bus v7.5.1 to try and validate that we didn't miss any other cases.

In the meantime, I've created [#215](https://github.com/Azure/azure-amqp/pull/215) as a proposal for the AMQP library maintainers, which we'll be attempting to validate against your repro, my test scenarios,  and our internal builds.

**Comment by klioqc** [comment]
Thank you.
Test project only sends message now. So it would be more reliable if you also check that Azure.Messaging.ServiceBus can be built with the latest Microsoft.Azure.Amqp, so nothing else won't be missed.

**Comment by JoshLove-msft** [comment]
2.5.10 has been published which fixes the issue - https://www.nuget.org/packages/Microsoft.Azure.Amqp/2.5.10
