### ISSUE TITLE
[a client library upgrade saga] Does a "batch" message settlement/completion corollary exist?

### ISSUE THREAD

**Issue by agause** [Azure/azure-sdk-for-net#26220]
### Library name and version

Azure.Messaging.ServiceBus 7.5.1

### Query/Question

Hello!

#### Extent of My Current Understanding
[`Microsoft.Azure.ServiceBus.MessageReceiver`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagereceiver?view=azure-dotnet) enables fine-grained control over [batch message receipt](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagereceiver.receiveasync?view=azure-dotnet#Microsoft_Azure_ServiceBus_Core_MessageReceiver_ReceiveAsync_System_Int32_) and [batch message settlement](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagereceiver.completeasync?view=azure-dotnet#Microsoft_Azure_ServiceBus_Core_MessageReceiver_CompleteAsync_System_Collections_Generic_IEnumerable_System_String__).

[`Azure.Messaging.ServiceBus.ServiceBusReceiver`](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceiver?view=azure-dotnet) enables fine-grained control over [batch message receipt](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceiver.receivemessagesasync?view=azure-dotnet#Azure_Messaging_ServiceBus_ServiceBusReceiver_ReceiveMessagesAsync_System_Int32_System_Nullable_System_TimeSpan__System_Threading_CancellationToken_) and [_single_ message settlement](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceiver.completemessageasync?view=azure-dotnet).

#### Current Dilemma
In an as-of-yet-failed attempt to upgrade to the prescribed `Azure.Messaging.ServiceBus` client library, I'm struggling to find a performance-friendly means of marking a list of batch-received messages as complete (_ideally_, w/ a single invocation, much like the `Microsoft.Azure.ServiceBus.MessageReceiver.CompleteAsync` that accepts an `IEnumerable<string>` message lock token argument).

#### Question
Am I overlooking a more appropriate set of code artifacts in the `Azure.Messaging.ServiceBus` library that might help achieve both **batch message receipt** _and_ **settlement/completion**?

Thanks much in advance for your time and wisdom!

### Environment

Ubuntu 20.04, .NET 6.0

**Comment by jsquire** [comment]
Hi @agause.  Thank you for your feedback.  Unfortunately, `Azure.Messaging.ServiceBus` does not support batch settlement of messages because there is no support for the operation in the Service Bus service; any batched API would be client-side only and would be similar to:

```csharp
  var tasks = new List<Task>();

  for (ServiceBusReceivedMessage message in messages)
  {
      tasks.Add(receiver.CompleteMessageAsync(message));
  }

  await Task.WhenAll(tasks);
```   

This is the approach that `Microsoft.Azure.ServiceBus` used in its implementation.   For `Azure.Messaging.ServiceBus`, we have concerns that this approach introduces complexity and confusion around error scenarios due to the potential for partial success.  It also may hide a performance bottleneck, which we would like to avoid.  Since this pattern is fairly straight-forward to implement, we felt it was better applied in the application than hidden within the SDK.    

More context and the full discussion can be found in [#7291](https://github.com/Azure/azure-sdk-for-net/issues/7921).

**Comment by agause** [comment]
@jsquire First off, thank you so much for the super quick response, the clarifying code snippet, the historical context behind the client-side-convenience-method/API omission! Gotta step up my search game, b/c I'm mostly sad you've had to answer the same question yet again.

Now 4 threads deep in duplication (or, at least, mentions in the full discussion), has there been any consideration toward updating the [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md#receiving-messages) to surface the client-side batching decision and potential alternative (complete w/ code snippet)?

Even a quick mention and link to the [full discussion](https://github.com/Azure/azure-sdk-for-net/issues/7921) within the [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md#receiving-messages) may help with and encourage `Azure.Messaging.ServiceBus` library adoption. I'm not the quitting type, but as alluded to in the full discussion, I was considering abandoning course by reverting my code to its `Microsoft.Azure.ServiceBus` equivalent.

Upon reflection, the trickiest part of migrating (for me) was the absence of a corollary, created by the vacuum of an uncommunicated omission. While the omission was the product of thoughtful consideration,
- communication of the choice,
- reasons for omission and
- recommendations to fill the absence, alongside
- a clarifying code snippet

...could help close the gap in the current guidance.

Again, thank you so much!

**Comment by jsquire** [comment]
Thank you for the suggestion, @agause.  This does seem to be a good candidate for a FAQ section in the migration guide.   I've opened [#26235](https://github.com/Azure/azure-sdk-for-net/pull/26235) to add one in there.

I notice that you've reopened the issue; was there something further that you were looking for assistance with?

**Comment by agause** [comment]
No sir, just a novice in this question/issue tool and wanted to leave room for you to weigh in.

FAQ, love it!

Thank you, again!

**Comment by agause** [comment]
@jsquire FYI, had to press pause on the migration, as I found myself in [this camp](https://github.com/Azure/azure-sdk-for-net/issues/25275) upon employing the `Task.WhenAll` approach.
