### ISSUE TITLE
Creation of test resources fails when running ServiceBus tests

### ISSUE THREAD

**Issue by ngruson** [Azure/azure-sdk-for-net#26224]
### Library name and version

Azure.Messaging.ServiceBus.Tests

### Describe the bug

From VS2022, I try to run the samples that are in the project Azure.Messaging.ServiceBus.Tests. In doing so, the Powershell script [New-TestResources.ps1](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/common/TestResources/New-TestResources.ps1.md) is called to setup a resource group in my Azure subscription. This results in an exception:

```
15:41:08 - TestApplicationId was not specified; creating a new service principal in subscription 'mySubscriptionId'
WARNING: We have migrated the API calls for this cmdlet from Azure Active Directory Graph to Microsoft Graph.
Visit https://go.microsoft.com/fwlink/?linkid=2181475 for any permission issues.
WARNING: Attempt 1 failed: Exception calling "Invoke" with "0" argument(s): "Cannot bind argument to parameter 'ServicePrincipalId' because it is an empty string.". Trying again in 10 seconds...
WARNING: Attempt 2 failed: Exception calling "Invoke" with "0" argument(s): "Cannot bind argument to parameter 'ServicePrincipalId' because it is an empty string.". Trying again in 20 seconds...
```

The service principal gets created ok, but the `New-AzADSpCredential` call (currently on line 152) fails which should create the credentials for the new service principal. I could reproduce the error in Powershell.

I've also tried 
```ps
$credential = New-AzADSpCredential -PasswordCredentials $password -ServicePrincipalName $servicePrincipal.DisplayName
```
which is throwing the same exception.

I'm running version 7.1.0 of the Az Powershell module on my laptop.

### Expected behavior

The test resources should be created successfully.

### Actual behavior

Aforementioned Powershell script doesn't create the required resources in my subscription.

### Reproduction Steps

In VS2022 build the Azure.Messaging.ServiceBus solution and debug a test. For example `SendAndReceiveMessage` in `Sample01_HelloWorld.cs`.

### Environment

- Windows 11
- Visual Studio 2022 17.0.4
- Az Powershell module 7.1.0

**Comment by jsquire** [comment]
Hi @ngruson.  Thank you for reaching out and we regret that you’re experiencing difficulties.  The failure that you’re seeing is the result of breaking changes made in v7.1.0 of the Azure PowerShell module.  There is a [pull request](https://github.com/Azure/azure-sdk-tools/pull/2513) in progress to adjust the test resources script to account for that change.  

Until that is merged, the best work arounds would be to create a service principal and pass it’s identifiers into New-TestResources or to use v7.0 of the Azure PowerShell module.

**Comment by ngruson** [comment]
Thanks for the quick response!
I was able to create the resources manually with New-TestResources.ps1.
However, downgrading to Az 7.0.0 or even 6.6.0 didn't work for me. I still got the same errors when trying to create the credentials in Powershell.
But no biggie, I'll follow the PR.
