### ISSUE TITLE
[BUG] MinimalTlsVersion missing in Azure SQL Server

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-net#26226]
### Library name and version

Microsoft.Azure.Management.Sql 2.0.0-preview

### Describe the bug

Getting and setting this here is not possible via SDK
https://docs.microsoft.com/en-us/azure/azure-sql/database/connectivity-settings#set-the-minimal-tls-version-via-powershell

### Expected behavior

Should be able to get and set this property.

### Actual behavior

Not possible.

### Reproduction Steps

Not much to reproduce, it's not available and should be, because it's available in all other packages like Azure PowerShell and CLI.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@davidobrien1985 this should be fixed in the new lib https://www.nuget.org/packages/Azure.ResourceManager.Sql/1.0.0-beta.2

**Comment by davidobrien1985** [comment]
@ArthurMa1978 I might be dumb. Currently we can do something like

```
var sqlServers = await azure.SqlServers.ListAsync();
```

where `azure` is of type `Microsoft.Azure.Management.Fluent.IAzure`.
I tried finding a way to list all the SQL Servers in our Subscription to then access the MinimalTlsVersion, but couldn't find a way to do it.
Any chance you have an example?

**Comment by davidobrien1985** [comment]
@ArthurMa1978 sorry to ping you again. Any chance you can help with a little working snippet?

**Comment by davidobrien1985** [comment]
Anybody got any advice here?
