### ISSUE TITLE
Azure SDK not working in vs2013 professional

### ISSUE THREAD

**Issue by laxman577** [Azure/azure-sdk-for-net#2622]
Azure SDK not working in vs2013 prof
![azure sdk error](https://cloud.githubusercontent.com/assets/13295654/20961532/6f29c864-bc8b-11e6-9ddc-c7f6d8d6730a.PNG)
essional

**Comment by markcowl** [comment]
@laxman577 Those webpi feeds are not shipped from this repository, please file this issue with the VS team
