### ISSUE TITLE
[BUG] Can't extract 'Region' for ID Documents with Prebuilt models using .Net SDK for Forms Recognizer

### ISSUE THREAD

**Issue by castasint** [Azure/azure-sdk-for-net#26233]
### Library name and version

Azure.AI.FormRecognizer_3.1.1

### Describe the bug

We use the Microsoft Azure Cognitive Services Form Recognizer client library to invoke the Form Recognizer resource with our documents. We’re using the prebuilt model(id document) for analyzing the driver’s license. During our testing, we’ve noticed that the ‘Region’ field is not being recognized by the (.NET) Microsoft Azure Cognitive Services Form Recognizer client library.

To double-check our understanding, we took the same document and analyzed it through 2 different channels(.net client library and HTTP call using Postman). We noticed that the actual(raw) response from the Form recognizer service is the same(obviously) but the .net client library was not able to parse/extract the ‘Region’ from the response and was returning NULL.

### Expected behavior

When a drivers license is analyzed, the region field should be parsed by the client library

### Actual behavior

When a driver's license is analyzed, the region field is being returned as NULL even though the Forms Recognizer Service is returning it in the API Response. 

### Reproduction Steps

Take a Drivers's License Document and invoke the forms recognizer API using Postman/curl. Once the response is returned, inspect the Region field. It will have value.
Now, invoke the same resource using the .Net Client SDK and the Region field will be returned as Null 

### Environment

Azure.AI.FormRecognizer_3.1.1
Visual Studio - 2022
.NET 5.x/6.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @castasint and thank you for bringing this issue to our attention. Unfortunately I could not reproduce the issue with the documents I have, so let me ask you a few questions:

1. What's the service version you are using for the Postman/curl request?
2. Only if possible, could you share the JSON region field returned by the Postman/curl request?
3. Could you share the piece of code you are using to extract the region field from the returned recognized form?

**Comment by castasint** [comment]
Hello @kinelski ...thanks for the prompt response. Below is the code that we've. I've stripped off the non-relevant code for this issue. The idea is to have a very generic routine that can work for any type of document and store the form recognizer service response in a  dictionary.   

Also, I found a work around to this thanks to the test cases written inside the SDK . Refer to the following files where each field was being read with `<field>.Value.AsString();`

@kinelski  : Please let me know if you need more information. 

* [Recognize identity documents from URI](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/samples/V3.1/Sample14_RecognizeIdentityDocumentsFromUri.cs)
* [Recognize identity documents from file](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/samples/V3.1/Sample14_RecognizeIdentityDocumentsFromFile.cs)

## Code Snippet
![code](https://user-images.githubusercontent.com/16588875/148903781-d4666aed-e670-470f-ae94-c12627ff706e.png)

## SDK Response(post Deserialization)

![One](https://user-images.githubusercontent.com/16588875/148905498-b5512c98-2d17-4a2e-848a-e29059992288.png)

## Test Document 


![DL_Kent](https://user-images.githubusercontent.com/16588875/148904810-f5f584f3-7c2a-444e-9ae0-5f7dfc4b709c.jpg)

## Form recognizer service response(as inspected using fiddler-  note that I got the same response from postman as well). 

`{
  "status": "succeeded",
  "createdDateTime": "2022-01-10T10:57:54Z",
  "lastUpdatedDateTime": "2022-01-10T10:57:55Z",
  "analyzeResult": {
    "version": "2.1.0",
    "readResults": [
      { "page": 1, "angle": 0, "width": 279, "height": 180, "unit": "pixel" }
    ],
    "documentResults": [
      {
        "docType": "prebuilt:idDocument:driverLicense",
        "docTypeConfidence": 0.995,
        "pageRange": [1, 1],
        "fields": {
          "Address": {
            "type": "string",
            "valueString": "100 MAIN STREET APT. 1. FRANKFORT, KY 40501-1234",
            "text": "100 MAIN STREET APT. 1. FRANKFORT, KY 40501-1234",
            "boundingBox": [86, 100, 175, 100, 175, 122, 86, 122],
            "page": 1,
            "confidence": 0.995
          },
          "CountryRegion": {
            "type": "countryRegion",
            "confidence": 0.99,
            "valueCountryRegion": "USA"
          },
          "DateOfBirth": {
            "type": "date",
            "valueDate": "1977-04-01",
            "text": "04-01-1977",
            "boundingBox": [131, 70, 180, 68, 181, 78, 131, 79],
            "page": 1,
            "confidence": 0.995
          },
          "DateOfExpiration": {
            "type": "date",
            "valueDate": "2016-04-01",
            "text": "04-01-2016",
            "boundingBox": [131, 58, 181, 58, 181, 67, 131, 68],
            "page": 1,
            "confidence": 0.995
          },
          "DocumentNumber": {
            "type": "string",
            "valueString": "S00-000-001",
            "text": "S00-000-001",
            "boundingBox": [138, 48, 194, 47, 193, 57, 138, 57],
            "page": 1,
            "confidence": 0.995
          },
          "FirstName": {
            "type": "string",
            "valueString": "CAROL ANN",
            "text": "CAROL ANN",
            "boundingBox": [87, 90, 136, 90, 136, 99, 87, 99],
            "page": 1,
            "confidence": 0.995
          },
          "LastName": {
            "type": "string",
            "valueString": "SAMPLE",
            "text": "SAMPLE",
            "boundingBox": [86, 82, 121, 82, 121, 90, 86, 91],
            "page": 1,
            "confidence": 0.995
          },
          "Region": {
            "type": "string",
            "valueString": "Kentucky",
            "confidence": 0.99
          }
        }
      }
    ]
  }
}`

## Endpoint used in postman

https://<removed domain>/formrecognizer/v2.1/prebuilt/iddocument/analyze

**Comment by kinelski** [comment]
Hello @castasint and thank you for the extra information. This is the expected behavior of the SDK. In our [Recognize Identity Documents sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/V3.1/Sample11_RecognizeIdentityDocuments.md#recognize-identity-documents-from-a-uri), you can see that using `<field>.Value.AsString()` as you suggested is the appropriate way of extracting the value of a string field:
```cs
if (identityDocument.Fields.TryGetValue("Region", out FormField regionfield))
{
    if (regionfield.Value.ValueType == FieldValueType.String)
    {
        string region = regionfield.Value.AsString();
        Console.WriteLine($"Region: '{region}', with confidence {regionfield.Confidence}");
    }
}
```

The `field.Value.ValueData.Text` you were using maps to the `text` JSON property, which is not being returned for the "Region" field in the service response:
```
"Region": {
    "type": "string",
    "valueString": "Kentucky",
    "confidence": 0.99
}
```

The "text" property is only recommended when you want the actual string representation in the same way as it's written in the input document, which only matters for some specific types such as numbers and dates.

Please let me know if you have any other questions.
