### ISSUE TITLE
[FEATURE REQ] Azure.Identity: Update client certificate in credential

### ISSUE THREAD

**Issue by microsoftruisu** [Azure/azure-sdk-for-net#26240]
### Library name

Azure.Identity and Azure.Messaging.ServiceBus

### Please describe the feature.

We use service principle to get auth info for communicate with azure resources, such as service bus. We used this function: ClientCertificateCredential
 
For example: ClientCertificateCredential(_servicePrincipalDetails.TenantId, _servicePrincipalDetails.ClientId, authCert, new ClientCertificateCredentialOptions() { SendCertificateChain = true });
 
Because service principle involve certificate, if this auth certificate got renewed, is there an easier way to update ClientCertificateCredential?
After I got a new auth cert, you can expose a call for me to just update ClientCertificateCredential?
Or just like a SNI support? 

Currently, if the auth cert is renewed, we have to re-create all service bus namespaces, topics etc. since there is no way for us to refresh ClientCertificateCredential
 
Or can I put a new feature request to this update request? 
Or do you recommend any existing work-around?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @microsoftruisu - 
Could you describe a bit more about your scenario? When updating the certificate, would this typically be done without a deployment? If so, how would you update the certificate configuration dynamically?

**Comment by microsoftruisu** [comment]
@christothes 
the cert is like an authentication cert, so it is kind of needs SNI validation. 

The current situation is that, we create ClientCertificateCredential with cert 1, then, we use that credential to create service bus namespaces and hundreds of topics. And when we have a cert 2, we have to recreate/rebuild all those connections/topics. 

The goal/feature request is to avoid doing that. if you could give us a hook so that we could just update a new cert, then we can avoid re-creating connections/topics. 

And also, yes trying to renew a cert without doing a deployment. We could dynamically/periodically reading in new certificates.

**Comment by microsoftruisu** [comment]
friendly ping, any updates
