### ISSUE TITLE
EnvironmentCredential not supporting certificate Authentication based on Thumbprint 

### ISSUE THREAD

**Issue by pallavichede** [Azure/azure-sdk-for-net#26259]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f9e9027-71c3-4071-fc06-fa0814c73a18
* Version Independent ID: 8adc947f-c7c6-55bf-2d2d-6c342b376848
* Content: [DefaultAzureCredential Constructor (Azure.Identity) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential.-ctor?view=azure-dotnet)
* Content Source: [xml/Azure.Identity/DefaultAzureCredential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Identity/DefaultAzureCredential.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @pallavichede  - Could you clarify what error exists in the docs you are referencing above? Or is this a feature request to add support for configuring the `EnvironmentCredential` based on thumbprint?
