### ISSUE TITLE
Could you please clarify the definition of "idle" in this context. Is it based purely on the number of messages or does it consider active subscribers ?

### ISSUE THREAD

**Issue by otwebti** [Azure/azure-sdk-for-net#26253]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 062a52c6-84d8-669d-45e2-9d493a95b13b
* Version Independent ID: 009db33f-e59f-c19e-a767-5c2ca71bf85d
* Content: [TopicDescription.AutoDeleteOnIdle Property (Microsoft.ServiceBus.Messaging) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.topicdescription.autodeleteonidle?view=azure-dotnet)
* Content Source: [xml/Microsoft.ServiceBus.Messaging/TopicDescription.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus.Messaging/TopicDescription.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@otwebti The idleness is based on the topic and this property set the duration for which topic must be idle before it is deleted automatically.  Please refer to the [documentation](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-expiration#idleness) to understand the idleness of different entities (Queue, Topics,Subscriptions).

Thanks
Saurabh
