### ISSUE TITLE
Service Bus: Erratic Behavior from SendMessageAsync()

### ISSUE THREAD

**Issue by spncrgr** [Azure/azure-sdk-for-net#26257]
I've created an Azure Function App to regularly poll the Dead Letter Queues and re-post the message back to the main topic (using [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/DeadLetterQueue/Program.cs#L250) as a guide)

The behavior I've noticed is that sometimes the message gets posted to the topic and sometimes it doesn't; there doesn't appear to be any pattern.

I enabled the `AzureEventSourceListener` and compared the diagnostics from a call that worked and a call that didn't; I didn't find any significant differences. I've also searched the Azure logs and have not found anything significant.

I'm attaching the function code file and the console output from the two different runs. I really could use help in figuring out the issue because, at this point, I'm at a total loss.

[ReprocessDeadLetterQueueFunction.cs.txt](https://github.com/Azure/azure-sdk-for-net/files/7847607/ReprocessDeadLetterQueueFunction.cs.txt)
[DLQ No-Post.txt](https://github.com/Azure/azure-sdk-for-net/files/7847611/DLQ.No-Post.txt)
[DLQ Post.txt](https://github.com/Azure/azure-sdk-for-net/files/7847612/DLQ.Post.txt)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @spncrgr,
It looks like the deadletter path you are using is not specific to to each subscription, but you appear to be using topics. Can you confirm whether you are 

Can you clarify whether you are reading from a queue or a topic subscription?

**Comment by JoshLove-msft** [comment]
Also, from looking at the logs, it looks like the message is sent successfully in both cases. When you say the message isn't posted to the topic, how are you determining this? Are you looking in the portal? If there are no active subscriptions for the topic when the message is sent, then the message won't be delivered anywhere.

**Comment by spncrgr** [comment]
@JoshLove-msft Thanks for your replies. Here are the answers to your questions.

We're using topic subscriptions. To get the DLQ path for the subscription we're currently using the `Microsoft.Azure.ServiceBus.EntityNameHelper.FormatDeadLetterPath()` method, like this:
```
DeadLetterQueuePath =
                EntityNameHelper.FormatDeadLetterPath($"{topicName}/Subscriptions/{subscriptionName}");
```
I just discovered the `ServiceBusReceiverOptions.SubQueue` property yesterday, so I'll switch to using that instead.

As for your other question, I'm determining that the message isn't being posted to the topic using Service Bus Explorer. And, yes, there are active subscriptions on the topic, so delivery should be happening AFAIK.

**Comment by JoshLove-msft** [comment]
Is it possible that another consumer is grabbing the message? If there are no exceptions thrown when sending to the topic, then the message should have been successfully sent.

**Comment by spncrgr** [comment]
Nope. In these cases there's only one consumer and I have it stopped during these tests so that the message will stay in the subscription. Plus, I have a test subscription that should get a copy as well and it isn't. Hopefully that makes sense 😄

**Comment by JoshLove-msft** [comment]
Based on the logs, the message appears to have been successfully sent. If you have a specific message Id of a message that should have been sent, but was not sent, can you submit an [Azure support ticket](https://azure.microsoft.com/en-us/support/create-ticket/) with this information along with your namespace so that the service team can investigate further?

**Comment by spncrgr** [comment]
I sure will...thanks @JoshLove-msft
