### ISSUE TITLE
Generate ToC from onboarded packages

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#26258]
Using onboarded packages generate a ToC

Structure: 

```
Service
  Client Package 1
    Overview (overview markdown file)
    Reference docs for Client Package 1
  Client Package 2
    Overview (overview markdown file)
    Reference docs for Client Package 2 
  ...
  Management
    Reference docs for Management Package 1 
    Reference docs for Management Package 2
    ...
``` 

Things to do: 
* [ ] Clean up metadata CSV
  * [ ] Ensure packages that are currently onboarded are in the metadata and not excluded
  * [ ] Add packages in ToC but not onboarded to CSV metadata
  * [ ] Clean up service names
* [ ] Adjust naming of package overview files to fit generated names (use `name.Replace(' ', '-')`) 
* [ ] Ensure that all onboarded packages are listed in the ToC
* [ ] Append an "Other" section to sweep any remaining packages

**Comment by kurtzeborn** [comment]
This is done.
