### ISSUE TITLE
Token Expire Time

### ISSUE THREAD

**Issue by festivus** [Azure/azure-sdk-for-net#26261]
The documentation says "The default value is 50% of the token expire time."

How do I find out what the token expire time is?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 035209e3-59a8-c20e-b1df-757a5cb27516
* Version Independent ID: 5c239551-1b1e-e732-e364-289dffad73c0
* Content: [CosmosClientOptions.TokenCredentialBackgroundRefreshInterval Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.tokencredentialbackgroundrefreshinterval?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@festivus I do not think that is exposed but I believe token returned from TokenProvider contains `ExpiresOn` property which can give actual token expiration time. Also, default token expire time is 1 hour. 
I will check internally though and get back to you.

**Comment by SaurabhSharma-MSFT** [comment]
@festivus As mentioned earlier, ExpiresOn property of the token is not exposed through any publicly and TokenCredential object is an input on the client creation only.

Thanks
Saurabh

**Comment by festivus** [comment]
If the default token expires time is 1 hours, that's all I need to know. I just need to make sure I don't set the TokenCredentialBackgroundRefreshInterval greater than the expires time.
