### ISSUE TITLE
spnClientId is now required for user/pass login for tests

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-sdk-for-net#2627]
In the latest TestFramework (1.5.0-preview) There is a bug at this line in TestEnvironment.cs:
https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/TestFramework/Microsoft.Rest.ClientRuntime.Azure.TestFramework/TestEnvironment.cs#L259

This requires the user to pass in the spnClientId for user/pass authentication. The problem with this is that the spnClientId is meant to be used with service principal authentication, and results in downstream errors (such as in powershell tests). If the user does not specify this property using the key/value pair ServicePrincipal=<clientId> then all tests will fail with "clientId cannot be null".

**Comment by shahabhijeet** [comment]
Ver. 1.5.1 has fixed this issue, will add pr info soon and close it myself.

**Comment by shahabhijeet** [comment]
@begoldsm this has been fixed in TestFramework version 1.5.2
