### ISSUE TITLE
[BUG] Read streams incorrectly refetch data for internal buffer, resulting in multiple redundant HTTP requests.

### ISSUE THREAD

**Issue by ascott18** [Azure/azure-sdk-for-net#26281]
### Library name and version

Azure.Storage.Files.Shares 12.8.0

### Describe the bug

When opening a stream and feeding it into an API that will perform a few different reads of the stream, a new HTTP GET request is made for each read of the stream. Providing an explicit `bufferSize` parameter to `OpenReadAsync` has no effect.

### Expected behavior

I'd expect that only a single GET is performed. This was the case for the Microsoft.WindowsAzure.Storage SDK.

### Actual behavior

For this specific repro, 5 separate GET requests, each for the entire contents of the file, are made.

### Reproduction Steps

Run the following, putting a URI for an image in the appropriate spot.

Observe the console output. See there's one HEAD request (expected), followed by multiple duplicate GET requests (expected only one). All GET requests are made with the same x-ms-range header representing the full byte range of the file.

``` xml
<PackageReference Include="Azure.Storage.Files.Shares" Version="12.8.0" />
<PackageReference Include="System.Drawing.Common" Version="6.0.0" />
```

``` c#
using System.Collections.Concurrent;
using System.Diagnostics;
using Azure.Storage.Files.Shares;

var httpListener = new HttpMonitoringListener();
DiagnosticListener.AllListeners.Subscribe(httpListener);

var file = new ShareFileClient(new Uri("<SAS uri of an image - the one I tested was a 44.8KB PNG file>"));
var stream = await file.OpenReadAsync();

var gdiImage = System.Drawing.Image.FromStream(stream);

public class HttpMonitoringListener : IObserver<DiagnosticListener>, IObserver<KeyValuePair<string, object>>
{
    public void OnCompleted() { }
    public void OnError(Exception error) { }
    public void OnNext(DiagnosticListener listener) { if (listener.Name == "HttpHandlerDiagnosticListener") listener.Subscribe(this); }

    int i = 1;
    public void OnNext(KeyValuePair<string, object> value)
    {
        if (value.Key == "System.Net.Http.HttpRequestOut.Start")
        {
            var request = ((HttpRequestMessage)value.Value.GetType().GetProperty("Request").GetValue(value.Value));

            Console.WriteLine($"======= Request #{i++} =======");
            Console.Write(request.Method + " ");
            Console.WriteLine(request.RequestUri);
            Console.WriteLine(request.Headers);
        }
    }
}
```

<details>
<summary>Output from Repro</summary>

Output from a 44.8 KB PNG file:

```
======= Request #1 =======
GET https://<url removed>
x-ms-version: 2020-10-02
Accept: application/xml
x-ms-client-request-id: 74421d50-d353-4ba8-ad38-f37c41b311f6
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Files.Shares/12.8.0 (.NET 6.0.1; Microsoft Windows 10.0.19043)
traceparent: 00-c3fb475d27f3cc346bdb8fee324df91d-54895f9a961eb8a2-00

======= Request #2 =======
GET https://<url removed>
x-ms-version: 2020-10-02
x-ms-range: bytes=0-4194303
x-ms-range-get-content-md5: false
Accept: application/xml
x-ms-client-request-id: 4fa4ffac-7e76-47df-a637-bafbe715ad15
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Files.Shares/12.8.0 (.NET 6.0.1; Microsoft Windows 10.0.19043)
traceparent: 00-7236457e0a74370761f4278105f84729-e598de71a40b9258-00

======= Request #3 =======
GET https://<url removed>    
x-ms-version: 2020-10-02
x-ms-range: bytes=0-4194303
x-ms-range-get-content-md5: false
Accept: application/xml
x-ms-client-request-id: 393710ce-07e2-469b-ad4d-c491b661ec0f
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Files.Shares/12.8.0 (.NET 6.0.1; Microsoft Windows 10.0.19043)
traceparent: 00-14b312a86fb8ff5fa38d7a90bdb42fde-10814ba33d601a57-00

======= Request #4 =======
GET https://<url removed>   
x-ms-version: 2020-10-02
x-ms-range: bytes=0-4194303
x-ms-range-get-content-md5: false
Accept: application/xml
x-ms-client-request-id: 7ffe8dd8-6bcb-40e5-a20f-f0f59056ad2f
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Files.Shares/12.8.0 (.NET 6.0.1; Microsoft Windows 10.0.19043)
traceparent: 00-072de5ec78830ebfe1e68da00643687e-af5018c0c605ebf8-00

======= Request #5 =======
GET https://<url removed>   
x-ms-version: 2020-10-02
x-ms-range: bytes=0-4194303
x-ms-range-get-content-md5: false
Accept: application/xml
x-ms-client-request-id: c163bda7-1ce0-4df5-b0f5-7ef6d30d7353
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Files.Shares/12.8.0 (.NET 6.0.1; Microsoft Windows 10.0.19043)
traceparent: 00-21e86590502777720398f421d58e7b23-4298db6c9005f0c2-00

======= Request #6 =======
GET https://<url removed>
x-ms-version: 2020-10-02
x-ms-range: bytes=0-4194303
x-ms-range-get-content-md5: false
Accept: application/xml
x-ms-client-request-id: f1f6f888-6821-4c60-8fe4-d557328a1e4e
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Files.Shares/12.8.0 (.NET 6.0.1; Microsoft Windows 10.0.19043)
traceparent: 00-38caf4775b4590a38fb5cce4eb43ae44-37bcee204c0c0bc3-00
```

</details>

### Environment

.NET 6.0.1, Windows 10

**Comment by amishra-dev** [comment]
@jaschrep-msft can you please help here. 
Hi @ascott18 Andrew,
The earlier versions of storage sdk were stateful and would cache a lot of state and data. The current one is not, this enables a easier programming model and better concurrency but will not cache the data for you. Having said that, once James get a chance to look at it, we will let you know if you are missing a knob (different api) or there is a genuine bug we need to fix. 
Thanks.

**Comment by ascott18** [comment]
It looks to me like the logic in LazyLoadingReadOnlyStream.Seek is incorrect.

The predicate in [this conditional](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Common/src/Shared/LazyLoadingReadOnlyStream.cs#L390-L395) should be `newPosition < _position && newPosition >= beginningOfBuffer`.

Right now, if seeking to the start of the stream when the whole file is buffered, `newPosition == beginningOfBuffer == 0`. The condition for "newPosition is less than _position, but within _buffer" fails on this, despite position `0` being within the beginning of the buffer.

**Comment by ascott18** [comment]
I was going to PR this, but there may be something else as well. Debugging through the Seek method and tweaking some local variables to get past the condition didn't make the redundant HTTP requests go away. 

I suspect there's a similar off-by-1 error in some other code.

**Comment by jaschrep-msft** [comment]
I can investigate the seek logic. Renaming this issue to reflect that this method does buffer and appears to incorrectly determine when it needs to refetch data for that buffer.
