### ISSUE TITLE
Sample: Using the `EventProcessorClient` with an ASP.NET hosted service

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#26299]
# Summary

A common usage scenario for processing events is doing so from within an ASP.NET application as a persistent host.  A sample should be available demonstrating how to create and configure the `EventProcessorClient` in an ASP.NET context as an `IHostedService` implementation.

# Scope of Work

- A stand-alone sample that demonstrates creating and configuring an `EventProcessorClient` in an ASP.NET application, illustrating a reasonable default configuration and integrating with the ASP.NET as a hosted service definition.

- The sample should include registering event handlers and demonstrate basic processing tasks.

- The sample should address the need to extend the shutdown to avoid potential data loss and demonstrate doing so.

# Out of Scope

- Demonstrating the other Event Hubs clients.

- Demonstrating use of the Azure Client Builder extensions _(they do not support the full scenario needed by the processor)_

# Success Criteria

- A sample exists, demonstrating creation of the `EventProcessorClient` and integration in to the ASP.NET host environment, as detailed in the scope.

- The code for the sample is a stand-alone application that can be executed and run.

- The sample project can be built within the Azure SDK repository structure, taking advantage of our engineering system.

- The sample project can be built on its own, with no dependencies on the Azure SDK engineering system.

- The tests necessary for sample validation have been created in the Event Hubs test suite and ensure that the sample is compliable.   

- Any functional tests pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

**Comment by jeffvan98** [comment]
Has there been any progress on this item?  This sample would prove useful for those looking to host within Azure Container Apps, where they can use the ASP.NET plumbing to report health up to the KEDA infrastructure.

**Comment by jsquire** [comment]
This is an item on our backlog that hasn't yet been scheduled.  When it does the milestone field will be updated to indicate the target date for completion.

**Comment by davetrainer** [comment]
@jsquire I can help with this. Can you assign it and I'll pick it up?

**Comment by jsquire** [comment]
Completed by #40092
