### ISSUE TITLE
[FEATURE REQ] Add methods to navigate upwards in a directory hierarchy.

### ISSUE THREAD

**Issue by ascott18** [Azure/azure-sdk-for-net#26295]
### Library name

Azure.Storage.Files.Shares 12.8.0

### Please describe the feature.

`ShareDirectoryClient` has a method `GetSubdirectoryClient` that can be used to navigate downwards into a directory hierarchy.

However, there are no methods on either `ShareDirectoryClient` nor on `ShareFileClient` that can produce a `ShareDirectoryClient` representing the item's parent. Additionally, it is not possible to implement such methods yourself because `ClientConfiguration` is internal, as is the constructor that accepts that as an argument.

This is a feature regression from `Microsoft.WindowsAzure.Storage`, which did have such mechanisms in the form of the `Parent` property on `CloudFile` and `CloudDirectory`.

**Comment by SaurabhSharma-MSFT** [comment]
@ascott18 This looks like a feature request so redirecting this to respective team.

**Comment by ascott18** [comment]
@SaurabhSharma-MSFT yes, I filed it with the "Feature request" template. Perhaps the tags for that template are wrong (that it put "question" on it).
