### ISSUE TITLE
Sample: Using the `EventHubBufferedProducerClient` with ASP.NET

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#26298]
# Summary

A common usage scenario for publishing events is doing so from within an ASP.NET application.  A sample should be available demonstrating how to create and configure the `EventHubBufferedProducerClient` in an ASP.NET context.

# Scope of Work

- A stand-alone sample that demonstrates creating and configuring an `EventHubBufferedProducerClient` in an ASP.NET application, illustrating a reasonable default configuration and integrating with the ASP.NET dependency injection framework.

- The sample should include registering event handlers for success and failure and a stubbed approach for dead-lettering failed sends.

- The sample should address the need to extend the shutdown to avoid potential data loss and demonstrate doing so.

# Out of Scope

- Demonstrating the other Event Hubs clients.

- Demonstrating use of the Azure Client Builder extensions _(they do not support the full scenario needed by the buffered producer)_

# Success Criteria

- A sample exists, demonstrating creation of the `EventHubBufferedProducerClient` and integration in to the ASP.NET host environment, as detailed in the scope.

- The code for the sample is a stand-alone application that can be executed and run.

- The sample project can be built within the Azure SDK repository structure, taking advantage of our engineering system.

- The sample project can be built on its own, with no dependencies on the Azure SDK engineering system.

- The tests necessary for sample validation have been created in the Event Hubs test suite and ensure that the sample is compliable.   

- Any functional tests pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

**Comment by andreyshihov** [comment]
Hi @jsquire, Is this issue is still relevant? Thanks

**Comment by jsquire** [comment]
@andreyshihov :  I think it's a nice-to-have sample.  It's a bit less important now that there's a [processor with ASP.NET host example](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/aspnet-hosted-service) as this would be the same approach with the details changed.    To be honest, I'm still on the fence of whether or to let the bot close this out.
