### ISSUE TITLE
[QnA Authoring] Activate tests for null argument validation once bug is fixed

### ISSUE THREAD

**Issue by AhmedLeithy** [Azure/azure-sdk-for-net#26291]
There is a bug in the LLC generator that causes certain validations to not be generated with the client. I have implemented a fix for this https://github.com/Azure/autorest.csharp/pull/1741 , but it is not yet included as part of the AutoRest.Csharp package.

Activate (Uncomment) tests for these validations when the bug fix has propagated. The tests can be [found here](https://github.com/Azure/azure-sdk-for-net/blob/eee059bdbd6942f95834fd6059b2c22bfb4c1aea/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/tests/QuestionAnsweringProjectsClientTests.cs#L79).

**Comment by pallavit** [comment]
This issue has been fixed and the tests have been enabled - https://github.com/Azure/azure-sdk-for-net/blob/aad3be7a5488a95a8c2fbdb2c2610d5f540fcd77/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/tests/QuestionAnsweringAuthoringClientTests.cs#L89
