### ISSUE TITLE
[QUERY] How to access Subscriptions from multiple tenants

### ISSUE THREAD

**Issue by timpclip** [Azure/azure-sdk-for-net#26303]
### Library name and version

Azure.ResourceManager 1.0.0-beta.7

### Query/Question

I am an Azure user with access to multiple tenants.  My primary tenant is my organization and I was invited into another tenant.  In Azure portal I can toggle between tenants by using the Switch Directory feature.
When I use DefaultAzureCredential to create the ArmClient I'm seeing this behavior:
calling armClient.GetTenants().GetAll() - I see both tenants being returned
calling armClient.GetSubscriptions().GetAll() - I see only subscriptions from my primary tenant being returned

I would like to either see all subscriptions returned from both tenants at once, or be able to set my active tenant and return subscriptions for that Tenant only.  Is there a way to do it?

### Environment

Windows 10 .NET Framework 4.6.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @timpclip , you are right about the two methods' behavior. The reason is that armClient only contains one tenant and we construct the tenant based on your credential. So for your need, I'd like to suggest you to construct a new armClient with different credential.
