### ISSUE TITLE
Documentation is misleading for ResourceGroupCollection.GetAllAsync's filter parameter

### ISSUE THREAD

**Issue by juliusl** [Azure/azure-sdk-for-net#26313]
In the doc comments it shows: 

https://github.com/Azure/azure-sdk-for-net/blob/1ea640a1ccda6aae3d42fde7b7bb2589621363f9/sdk/resourcemanager/Azure.ResourceManager/src/Resources/PseudoGenerated/ResourceGroupCollection.cs#L284

`use $filter=tagName eq &apos;tag1&apos; and tagValue eq &apos;Value1&apos`

However, the usage should actually be:

`tagName eq 'tagname' and tagValue eq 'value'` 

We found this out by looking at the unit tests, as there doesn't to appear to be many examples that use this parameter, 

https://github.com/Azure/azure-sdk-for-net/blob/1ea640a1ccda6aae3d42fde7b7bb2589621363f9/sdk/resourcemanager/Azure.ResourceManager/tests/Scenario/ResourceGroupCollectionTests.cs#L45

I would suggest to update the doc to something like, (sub ` for ```) 

`/// use ```tagName eq &apos;tag1&apos; and tagValue eq &apos;Value1&apos```  `

to avoid confusion.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thanks @juliusl for reporting this issue, @fengzhou-msft  please check if it's still existing in the new code

**Comment by iBobb** [comment]
> In the doc comments it shows:
> 
> https://github.com/Azure/azure-sdk-for-net/blob/1ea640a1ccda6aae3d42fde7b7bb2589621363f9/sdk/resourcemanager/Azure.ResourceManager/src/Resources/PseudoGenerated/ResourceGroupCollection.cs#L284
> 
> `use $filter=tagName eq &apos;tag1&apos; and tagValue eq &apos;Value1&apos`
> 
> However, the usage should actually be:
> 
> `tagName eq 'tagname' and tagValue eq 'value'`
> 
> We found this out by looking at the unit tests, as there doesn't to appear to be many examples that use this parameter,
> 
> https://github.com/Azure/azure-sdk-for-net/blob/1ea640a1ccda6aae3d42fde7b7bb2589621363f9/sdk/resourcemanager/Azure.ResourceManager/tests/Scenario/ResourceGroupCollectionTests.cs#L45
> 
> I would suggest to update the doc to something like, (sub ` for ```)
> 
> `` /// use ```tagName eq &apos;tag1&apos; and tagValue eq &apos;Value1&apos``` ``
> 
> to avoid confusion.

It was unclear to me how to use the filter but that helped, thanks a lot!

**Comment by pallavit** [comment]
Given the above comment, I am marking this issue-addressed. Please let us know if that is not the case.
