### ISSUE TITLE
IndexOutOfRangeException in Azure.Data.Tables 12.3

### ISSUE THREAD

**Issue by DannyvanderKraan** [Azure/azure-sdk-for-net#26326]
We upgraded Azure.Data.Tables from 12.2.1 to 12.3 and we got an issue running it with CosmosDb (Table API) Emulator. A CosmosDb instance on Azure works fine. The stacktrace we got:

_Message: 
System.IndexOutOfRangeException : Index was outside the bounds of the array.

Stack Trace: 
TableConnectionString.GetAccountNameFromUri(Uri uri)
TableUriBuilder.ctor(Uri uri)
TableServiceClient.ctor(String connectionString, TableClientOptions options)
CosmosDbTableFixture.InitializeAsync() line 49_

We traced this problem all the way back to GetAccountNameFromUri:

[](https://github.com/Azure/azure-sdk-for-net/blob/280eec8be896315c1c00df07d38aec3f4a2af43b/sdk/tables/Azure.Data.Tables/src/TableConnectionString.cs#:~:text=///%20%3Creturns%3E%3C/returns%3E-,internal%20static%20string%20GetAccountNameFromUri(Uri%20uri),%7D,-///%20%3Csummary%3E)

Specifically this part of the URL gives problems: 

_http://localhost:8902/_

Our full connection string is the well known connectionstring of the Cosmosdb emulator, for reference: 

_DefaultEndpointsProtocol=http;AccountName=localhost;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;TableEndpoint=http://localhost:8902/;_

Workaround:

Downgrade the package back to 12.2.1

Questions:
- Is the team aware of this problem?
- Will the problem be resolved in 12.3.1 for example?
- Does this have anything to do with switching to Azurite (we saw clues of this in the code comments)?

**Comment by christothes** [comment]
Thanks for reporting this issue. This will be fixed in the next release, however in the meantime you can work around this by adding "localhost" to the end of TableEndpoint.
