### ISSUE TITLE
[BUG] 401 Access denied due to invalid subscription key or wrong API endpoint: thinking AnalyzeConversation is affecting it

### ISSUE THREAD

**Issue by xtianus79** [Azure/azure-sdk-for-net#26321]
### Library name and version

Azure.Cognitive.Language SDK

### Describe the bug

When trying to set Azure credentials for cognitive language NLU service the sdk doesn't work per the instructions for setting up the credentials. 

here is the error message

```
Azure.RequestFailedException: "Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.\nStatus: 401 (Access Denied)\nErrorCode: 401\n\nContent:\n{\"error\":{\"code\":\"401\",\"message\": \"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.\"}}\n\nHeaders:\napim-request-id: xxxxxxxxxxxx6\nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload\nX-Content-Type-Options: nosniff\nWWW-Authenticate: REDACTED\nDate: Wed, 12 Jan 2022 15:42:19 GMT\nContent-Length: 225\nContent-Type: application/json\n"
at Azure.AI.Language.Conversations.ConversationAnalysisRestClient.AnalyzeConversation(String projectName, String deploymentName, AnalyzeConversationOptions conversationAnalysisOptions, CancellationToken cancellationToken)\n at Azure.AI.Language.Conversations.ConversationAnalysisClient.AnalyzeConversation(AnalyzeConversationOptions options, CancellationToken cancellationToken)\n at Azure.AI.Language.Conversations.ConversationAnalysisClient.AnalyzeConversation(String projectName, String deploymentName, String query, CancellationToken cancellationToken)\n at SuperBall.Program.Main(String[] args) in /Volumes/Macintosh HD - Data/Arbeit/WorkDirectory/VixConsoleApp/SuperBall/Program.cs:15
```

Here is the code 

```
using System;
using Azure;
using Azure.AI.Language.Conversations;

namespace SuperBall
{
    class Program
    {
        static void Main(string[] args)
        {
            Uri endpoint = new Uri("https://westus2.api.cognitive.microsoft.com/");
            AzureKeyCredential credential = new AzureKeyCredential("{xxxxxxxxxxxxxxx}");
            ConversationAnalysisClient client = new ConversationAnalysisClient(endpoint, credential);

            Response<AnalyzeConversationResult> response = client.AnalyzeConversation("xxx", "xxxx", "Sure");
        }
    }
}
```

### Expected behavior

For it to work. Documentation to be more accurate

### Actual behavior

401

### Reproduction Steps

Run code in visual studio

### Environment

both mac dotnet and windows visual studio

**Comment by jsquire** [comment]
//cc: @heaths

**Comment by AhmedLeithy** [comment]
Hey @xtianus79, thanks for your feedback. I would be glad to enhance the documentation to be easier to use, but I'm having trouble understanding what the current issue is.

The error message states that API Endpoint or the subscription key is invalid. Were you able to find the endpoint and key for your language resource using either [the portal](https://portal.azure.com/) or Azure CLI? It looks like you're using the endpoint `https://westus2.api.cognitive.microsoft.com/`, are you sure this is the correct endpoint for your resource?

**Comment by jsquire** [comment]
Hi @xtianus79.  Thank you for reaching out and we regret that you're experiencing difficulties.   In your snippet, you mention that you're creating the `AzureKeyCredential` using this pattern:

```csharp
credential = new AzureKeyCredential("{xxxxxxxxxxxxxxx}");
```

I would not expect the key to have curly braces, based on the pattern of keys normally generated by the Cognitive Services offerings, and should look similar to:

```csharp
credential = new AzureKeyCredential("xxxxxxxxxxxxxxx");
```

Would you be so kind as to confirm that your code is using the key as a direct match to the one that is displayed in the Azure portal?

**Comment by xtianus79** [comment]
hi @jsquire that is how it is in the documentation { } and thought that was a little odd. I think perhaps it could be a combination of both comments to get the right URL with the right key. I will review and comment back.

**Comment by xtianus79** [comment]
@jsquire  I have change to this and it is still giving 404

```
namespace SuperBall
{
    class Program
    {
        static void Main(string[] args)
        {
            Uri endpoint = new Uri("https://westus2.api.cognitive.microsoft.com/language/:analyze-conversations?projectName=xxxxxIVR&deploymentName=production&api-version=2021-11-01-preview");
            AzureKeyCredential credential = new AzureKeyCredential("xxxxxxxxxxxxxxxxx4932");
            ConversationAnalysisClient client = new ConversationAnalysisClient(endpoint, credential);

            Response<AnalyzeConversationResult> response = client.AnalyzeConversation("xxxxx", "xxxxx", "Sure");

            Console.WriteLine($"Top intent: {response.Value.Prediction.TopIntent}");
        }
    }
}
```

```
"Resource not found\nStatus: 404 (Resource Not Found)\nErrorCode: 404\n\nContent:\n{\"error\":{\"code\":\"404\",\"message\": \"Resource not found\"}}\n\nHeaders:\napim-request-id: ba0df87b-8ca7-4ca2-91f4-8d2e9a4db2b3\nStrict-Transport-Security: max-age=31536000; includeSubDomains; preload\nX-Content-Type-Options: nosniff\nDate: Wed, 19 Jan 2022 21:34:12 GMT\nContent-Length: 56\nContent-Type: application/json\n"
```

**Comment by heaths** [comment]
You should only pass the service host, not the entire endpoint as you're doing here:

```csharp
Uri endpoint = new Uri("https://westus2.api.cognitive.microsoft.com/language/:analyze-conversations?projectName=xxxxxIVR&deploymentName=production&api-version=2021-11-01-preview")
```

Instead, this should simply be:

```csharp
Uri endpoint = new Uri("https://westus2.api.cognitive.microsoft.com/");
```

See [our README](https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.Language.Conversations_1.0.0-beta.1/sdk/cognitivelanguage/Azure.AI.Language.Conversations/README.md#create-a-conversationanalysisclient) for an example, and a link to more samples.

**Comment by xtianus79** [comment]
/unresolve 

This does not work either way @heaths I have tried that link and a 1000 variations thereafter it doesn't work, i continue to get the 404/401 error. As stated in my first sentence, which includes the link you have provided in your post... it doesn't work. 

This is the error per this response: 

```
using System;
using Azure;
using Azure.AI.Language.Conversations;

namespace SuperBall
{
    class Program
    {
        static void Main(string[] args)
        {
            Uri endpoint = new Uri("https://westus2.api.cognitive.microsoft.com/");
            AzureKeyCredential credential = new AzureKeyCredential("xxxxxxxxxxxxx");
            ConversationAnalysisClient client = new ConversationAnalysisClient(endpoint, credential);

            Response<AnalyzeConversationResult> response = client.AnalyzeConversation("xxxxxx", "xxxxxxx", "Sure");

            Console.WriteLine($"Top intent: {response.Value.Prediction.TopIntent}");
        }
    }
}
```

error

```
using System;
using Azure;
using Azure.AI.Language.Conversations;

namespace SuperBall
{
    class Program
    {
        static void Main(string[] args)
        {
            Uri endpoint = new Uri("https://westus2.api.cognitive.microsoft.com/");
            AzureKeyCredential credential = new AzureKeyCredential("67152d9077974ccfb558b1bc02624932");
            ConversationAnalysisClient client = new ConversationAnalysisClient(endpoint, credential);

            Response<AnalyzeConversationResult> response = client.AnalyzeConversation("OptumTestIVR", "OptumTestIVR", "Sure");

            Console.WriteLine($"Top intent: {response.Value.Prediction.TopIntent}");
        }
    }
}
```

**Comment by heaths** [comment]
Your original post did include just the host name also used the wrong key format which is likely why you got the 401. It wasn't clear from your subsequent messages that you tried with the right host name and the right key format.

Using a slight change of your code above to use environment variables:

```csharp
using Azure;
using Azure.AI.Language.Conversations;

Uri endpoint = new Uri(Environment.GetEnvironmentVariable("CONVERSATIONS_URI"));
AzureKeyCredential credential = new AzureKeyCredential(Environment.GetEnvironmentVariable("CONVERSATIONS_KEY"));
ConversationAnalysisClient client = new ConversationAnalysisClient(endpoint, credential);

Response<AnalyzeConversationResult> response = client.AnalyzeConversation(
        Environment.GetEnvironmentVariable("CONVERSATIONS_PROJECT"),
        "production",
        "Sure");

Console.WriteLine($"Top intent: {response.Value.Prediction.TopIntent}");
```

I was able to repro the 401 if I was using the wrong `projectName` or `deploymentName`. In our case, our model was deployed to "production" (the default). Have you double checked that both the `projectName` and `deploymentName` arguments (in that order) are correct?

As for the host - though this doesn't seem to matter for now - Cognitive Lanugage services will be using a different host format like "https://{resource name}.cognitiveservices.azure.com". You can find this in the Portal:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/1532486/150406528-f9f79136-4659-4729-b840-2bef267b6714.png">

One of our test resources was also deployed to westus2, so "https://westus2.api.cognitive.microsoft.com/" also worked for me, but I'm not sure if that will be deprecated at some point in the future. I would use whatever the Portal says to use for the endpoint.

**Comment by xtianus79** [comment]
@heaths Hey thanks, so that worked.. the <production> parameter was it. What's confusing in the docs is that it's the project name but not the deployed name. do you see what i mean? or vice versus for us because i used the same name but point is its one or the other not both.

**Comment by heaths** [comment]
Sorry, not sure what you mean. Could you clarify? The parameters are named `projectName` and `deploymentName` and we have XML doc comments for both, or are you saying something in the Portal or Language Studio is confusing? I'd like to clear up any confusion, but not quite sure what that might be.
