### ISSUE TITLE
Purview dotnet client: Wrong Uri: Doc bug with bad params: Doc bug with undocumented param

### ISSUE THREAD

**Issue by marktayl1** [Azure/azure-sdk-for-net#26325]
### Library name and version

"Azure.Analytics.Purview.Catalog" Version="1.0.0-beta.2"

### Describe the bug

Tried the example here : https://docs.microsoft.com/en-us/dotnet/api/overview/azure/analytics.purview.catalog-readme-pre
- The Url parameter should be Uri
- The GetAllTypeDefinitionsAsync call takes a new param called Azure.RequestOptions that seems to be an undocumented type
- The call fails with a request to the http://management-babylon-eastus.catalog.clouddatahub.net/catalog/api/atlas/v2/types/typedefs URI, tried the non async version as well with the same result

### Expected behavior

retrieve types

### Actual behavior

Exception has occurred: CLR/Azure.RequestFailedException
An unhandled exception of type 'Azure.RequestFailedException' occurred in Azure.Analytics.Purview.Catalog.dll: 'Service request failed.
Status: 404 (Not Found)

Content:
{"requestId":"e09eae06-39b0-4a09-98da-db898555e547","errorCode":"RequestUriNotFound","errorMessage":"null for uri: http://management-babylon-eastus.catalog.clouddatahub.net/catalog/api/atlas/v2/types/typedefs"}

### Reproduction Steps

Just follow the steps in the getting started doc: https://docs.microsoft.com/en-us/dotnet/api/overview/azure/analytics.purview.catalog-readme-pre

### Environment

Windows 10 64-bit working through VSCode with all updates

**Comment by SaurabhSharma-MSFT** [comment]
@marktayl1 I have checked this, and I see the same behavior.  I am checking internally and get back to you.

**Comment by SaurabhSharma-MSFT** [comment]
@marktayl1 You need to use `https://{Account Name}.purview.azure.com` endpoint to get the results back.  I have tried this and it worked fine.  
![image](https://user-images.githubusercontent.com/38112130/149982362-d458000c-5ed4-4099-bd50-98e43e09ab0c.png)
I will work internally on the documentation update, meanwhile, you can try and let me know in case you see any issues.

Thanks
Saurabh

**Comment by marktayl1** [comment]
I was doing it with our account name.

var client = new PurviewCatalogClient(new Uri(https:/redacted_my_account_name.catalog.purview.azure.com<https://purview-to-adb-purview.catalog.purview.azure.com>), credential);

That is not the issue.  Someone already repoed this, I am confused by this response.

Thanks,

Mark

**Comment by SaurabhSharma-MSFT** [comment]
@marktayl1  When calling Purview account url you need to pass -  `https:/redacted_my_account_name.purview.azure.com` instead of using `https:/redacted_my_account_name.catalog.purview.azure.com`.

**Comment by marktayl1** [comment]
Okay, thanks.  Sorry, misunderstood.  That worked.

From: Mark Taylor (PIHV)
Sent: Tuesday, January 18, 2022 9:20 AM
To: Azure/azure-sdk-for-net ***@***.***>; Azure/azure-sdk-for-net ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [Azure/azure-sdk-for-net] Purview dotnet client: Wrong Uri: Doc bug with bad params: Doc bug with undocumented param (Issue #26325)

I was doing it with our account name.

var client = new PurviewCatalogClient(new Uri(https:/redacted_my_account_name.catalog.purview.azure.com<https://purview-to-adb-purview.catalog.purview.azure.com>), credential);

That is not the issue.  Someone already repoed this, I am confused by this response.

Thanks,

Mark

**Comment by SaurabhSharma-MSFT** [comment]
@marktayl1 Great. Thanks for the confirmation.  We will proceed with the closure of this issue.

Thanks
Saurabh
