### ISSUE TITLE
What does "for the current environment" mean

### ISSUE THREAD

**Issue by boylec** [Azure/azure-sdk-for-net#26331]
This method creates a cookie with properties that have no setters.

The comment about CreateNew says it creates a cookie "for the current environment". The meaning of this is non-obvious.

The Append method's comment states: "To create a cookie, you can use the Microsoft.Azure.Functions.Worker.Http.HttpCookies.CreateNew method." This appears to be false because creating a cookie using this method doesn't appear to allow me to set the cookie's value or other attributes due to the lack of setters on the resulting IHttpCookie object.

What gives?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 81095906-a34f-1cef-f357-d86000f9ac0e
* Version Independent ID: 640580c2-e54e-0e75-ff39-3233a8a7b2af
* Content: [HttpCookies.CreateNew Method (Microsoft.Azure.Functions.Worker.Http) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.functions.worker.http.httpcookies.createnew?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Functions.Worker.Http/HttpCookies.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Functions.Worker.Http/HttpCookies.xml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Functions.Worker` package is maintained as [#775](https://github.com/Azure/azure-functions-dotnet-worker/issues/775).
