### ISSUE TITLE
[LLC/Data Plane Client] Tests slow down in playback mode beyond timeout limit

### ISSUE THREAD

**Issue by AhmedLeithy** [Azure/azure-sdk-for-net#26334]
Hey all, 
The tests with issues are 
@christothes, @pakrym, @heaths have worked with me on debugging this issue. Our findings are as follows:

- The [following test](https://github.com/AhmedLeithy/azure-sdk-for-net/blob/c68c6fa530e71d93ee56858e82685f4009bc5ce7/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/tests/QuestionAnsweringProjectsClientLiveTests.cs#L134) is severely slowed down if `waitForCompletion` is set to true.
- The same applies for the [following sample](https://github.com/AhmedLeithy/azure-sdk-for-net/blob/c68c6fa530e71d93ee56858e82685f4009bc5ce7/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/tests/Samples/Sample5_UpdateKnowledgeSources.cs#L196).
- However, for [the sync version of the previous sample](https://github.com/AhmedLeithy/azure-sdk-for-net/blob/c68c6fa530e71d93ee56858e82685f4009bc5ce7/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/tests/Samples/Sample5_UpdateKnowledgeSources.cs#L49), the test is significantly slowed regardless of whether the `waitForCompletion` flag is set to true or false.

@christothes believes this may have to do with instrumentation not correctly handling scenarios where the operation is being returned by a helper class rather than the client itself.

**Comment by christothes** [comment]
I think more likely that this is a problem with how we proxy Operations. We currently transform the return value by instrumenting the returned operation. However, in the case of `waitForCompletion: true`, the operation is waited prior to it being returned by the method. 

I think we should explore a different approach to how we instrument operations to handle this case.

**Comment by heaths** [comment]
Agreed. Perhaps there is something deeper down the stack we can do that would work for both this new LLC `waitForCompletion` pattern as well as existing `Operation`/`Operation<T>` classes.

**Comment by christothes** [comment]
I haven't investigated the feasibility of this yet - but one idea I had was to somehow instrument all constructors of types based on Operation<T>

**Comment by heaths** [comment]
When instrumenting the client, could we use Castle (what Moq uses) to generate/cache a proxy and override any such method wrap/whatever we need to do?

**Comment by JoshLove-msft** [comment]
This was fixed in https://github.com/Azure/azure-sdk-for-net/pull/30112
