### ISSUE TITLE
[Identity] Sparse checkout repositories failing intermittently in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#26354]
Identity nightly test runs are failing with:

> Starting: Sparse checkout repositories
> ==============================================================================
> Task         : PowerShell
> Description  : Run a PowerShell script on Linux, macOS, or Windows
> Version      : 2.194.0
> Author       : Microsoft Corporation
> Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/powershell
> ==============================================================================
> Generating script.
> ========================== Starting Command Output ===========================
> /usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/__w/_temp/9cea2d7c-90aa-4e11-a318-eb2dfa064e4b.ps1'
> 
>     Directory: /__w/1
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> d----           1/14/2022  6:01 AM                s
> Repository Azure/azure-sdk-for-net is being initialized.
> git clone --no-checkout --filter=tree:0 https://github.com/Azure/azure-sdk-for-net .
> git: /__w/_temp/9cea2d7c-90aa-4e11-a318-eb2dfa064e4b.ps1:18
> Line |
>   18 |        git clone --no-checkout --filter=tree:0 https://github.com/$($r …
>      |        ~~~
>      | The term 'git' is not recognized as a name of a cmdlet,
>      | function, script file, or executable program. Check the
>      | spelling of the name, or if a path was included, verify that
>      | the path is correct and try again.
> 
> ##[error]PowerShell exited with code '1'.

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1295826&view=results

@jsquire for notification.

**Comment by kurtzeborn** [comment]
It says "git" does not exist!?
