### ISSUE TITLE
[BUG] Explicit ITableEntity implementation does not work

### ISSUE THREAD

**Issue by ssa3512** [Azure/azure-sdk-for-net#26363]
### Library name and version

Azure.Data.Tables 12.4.0

### Describe the bug

I have a model that implements ITableEntity as such:
```cs
public class BasicModel : ITableEntity
{
    public string Category { get; set; }
    public string Name { get; set; }
    public int Priority { get; set; }

    string ITableEntity.PartitionKey
    {
        get => Category;
        set => Category = value;
    }

    string ITableEntity.RowKey
    {
        get => Name;
        set => Name = value;
    }

    public DateTimeOffset? Timestamp { get; set; }
    public ETag ETag { get; set; }
}
```

When I query items from the table, Category/PartitionKey and Name/RowKey are null, despite being populated in the table. Using auto properties for PartitionKey/RowKey works, but I do not want to expose these as named on the model (hence the explicit interface implementation)

### Expected behavior

RowKey/PartitionKey are populated when explicit interface implementation of `ITableEntity` is used

### Actual behavior

RowKey/PartitionKey are not populated when explicit interface implementation of `ITableEntity` is used

### Reproduction Steps

Create model as shown and add rows to table, run `tableClient.QueryAsync<BasicModel>()`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
This is currently a limitation of the implementation we use for serialization of entity types in Azure.Data.Tables. I've created feature https://github.com/Azure/azure-sdk-for-net/issues/26514 to track this.
