### ISSUE TITLE
Release stable version Azure.ResourceManager SDK

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#26388]

**Comment by jamesstanleystewart** [comment]
Hi @ArthurMa1978 Is there a targeted date for the stable releases of the SDK packages?

**Comment by ArthurMa1978** [comment]
> Hi @ArthurMa1978 Is there a targeted date for the stable releases of the SDK packages?

Just released 2 core libs, and others are ongoing.
