### ISSUE TITLE
Avro schema registry not fully compatible with azure function event hub trigger 

### ISSUE THREAD

**Issue by jkmbowachas** [Azure/azure-sdk-for-net#26409]
The Avro schema serializer "SchemaRegistryAvroObjectSerializer" is not fully compatible with Azure function event hub trigger, when an Avro payload contains a type long it fails to deserialize the long value and ends up returning random a value.

Unit Test
`
        [Fact(Skip = "WIP")]
        public async Task ProcesslongEventAsync()
        {
            await _eventProcessorEndpoint.Run(new []
            {
                "\0\0\0\097165111ca0540c3ac73197b45ec9304Hc8901ed9-5136-4377-8c73-062cebb4368cHd0279904-b6ae-423a-95f2-89a2a0d2aac4��������\u0011\u0014InProgress"
            });
        }
`

Avro Schema
`
[
  {
    "name": "ProductItem",
    "namespace": "CHAS.Payments.Integrations",
    "type": "record",
    "fields": [
      {
        "name": "ProductId",
        "type": "string"
      },
      {
        "name": "Quantity",
        "type": "int"
      }
    ]
  },
  {
    "name": "MembershipItem",
    "namespace": "CHAS.Payments.Integrations",
    "type": "record",
    "fields": [
      {
        "name": "ProductId",
        "type": "string"
      },
      {
        "name": "Expiration",
        "type": "long"
      }
    ]
  },
  {
    "name": "PaymentCompletedEvent",
    "type": "record",
    "namespace": "CHAS.Payments.Integrations",
    "fields": [
      {
        "name": "ContractorId",
        "type": "string"
      },
      {
        "name": "Timestamp",
        "type": "long"
      },
      {
        "name": "LineItems",
        "type": {
          "type": "array",
          "items": [ "ProductItem", "MembershipItem" ]
        }
      }
    ]
  }
]
`

SUT
`
    public class EventProcessorEndpoint
    {
        private readonly EventProcessor _eventProcessor;
        private readonly SchemaRegistrySettings _settings;

        public EventProcessorEndpoint(EventProcessor eventProcessor, SchemaRegistrySettings settings)
        {
            _eventProcessor = eventProcessor;
            _settings = settings;
        }

        [Function("EventProcessorEndpoint")]
        public async Task Run([EventHubTrigger("ops", Connection = "OperationsEvents")] string[] input)
        {
            var eventsData = input.Select(x => new EventData(x)).ToList();
            var client = new SchemaRegistryClient(_settings.Endpoint, new DefaultAzureCredential());

            var serializer = new SchemaRegistryAvroObjectSerializer(client, _settings.GroupName, new SchemaRegistryAvroObjectSerializerOptions { AutoRegisterSchemas = false });
            foreach (var eventData in eventsData)
            {
                var eventRecord = (PaymentCompletedEvent)await serializer.DeserializeAsync(eventData.BodyAsStream, typeof(ISpecificRecord), CancellationToken.None);
                await Process(eventRecord);
            }
        }

        private async Task Process(PaymentCompletedEvent paymentCompleted)
        {
            var dateTimeTest = new DateTime(membershipItem.Expiration);
        }
    }
`
When the process function is called an exception is called stating DateTime should be in min value and max value. This is due to Expiration being long type and being deserialized incorrectly.

**Comment by JoshLove-msft** [comment]
Hi @jkmbowachas,
The issue here is that since you are binding to a string, the payload is assumed to be UTF-8 bytes, which is not the case when dealing with an Avro payload. You can instead bind directly to the EventData instead of a string.

You might also want to try using the latest [beta](https://www.nuget.org/packages/Microsoft.Azure.Data.SchemaRegistry.ApacheAvro/1.0.0-beta.5), which simplifies the process of encoding/decoding when using Event Hubs. For this integration, you will also need to use the latest Event Hubs [beta](https://www.nuget.org/packages/Azure.Messaging.EventHubs/5.7.0-beta.2).

**Comment by jkmbowachas** [comment]
/unresolve I have updated the library and this has got my tests working. However when trying to pull the message from event hubs this message is returned by the azure function. The producer also uses the same library as the consumer
"System.Private.CoreLib: Exception while executing function: Functions.EventProcessorEndpoint. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'eventsData'. Microsoft.Azure.WebJobs.Host: Binding parameters to complex objects (such as 'Object') uses Json.NET serialization"

**Comment by JoshLove-msft** [comment]
Can you please let us know what versions you are using of the extension package? Also, can you include the updated function?

**Comment by jkmbowachas** [comment]
The library used are
* Microsoft.Azure.Functions.Worker.Extensions.EventHubs 5.0.0-beta.6 
* Microsoft.Azure.Functions.Worker 1.6.0
* Microsoft.Azure.Functions.Worker.Sdk 1.3.0

Please see the function below
```
    public class EventProcessorEndpoint
    {
        private readonly SchemaRegistryAvroEncoder _avroEncoder;

        public EventProcessorEndpoint(SchemaRegistryAvroEncoder avroEncoder)
        {
            _avroEncoder = avroEncoder;
        }

        [Function("EventProcessorEndpoint")]
        public async Task Run([EventHubTrigger("operations", Connection = "OperationsEvents")] EventData[] eventsData)
        {
            foreach (var eventData in eventsData)
            {
                var eventRecord = (GenericRecord)await _avroEncoder.DecodeMessageDataAsync(eventData, typeof(GenericRecord));
            }
        }
    }
```

**Comment by JoshLove-msft** [comment]
I see - you are using the Isolated Worker model so binding to EventData is not supported. Can you try binding to a byte array?

**Comment by JoshLove-msft** [comment]
I found this related issue - https://github.com/Azure/azure-functions-dotnet-worker/issues/525

**Comment by JoshLove-msft** [comment]
> I see - you are using the Isolated Worker model so binding to EventData is not supported. Can you try binding to a byte array?

Actually, since your function is receiving a batch of events, you would need to try an array of byte arrays, i.e. `byte[][]`
