### ISSUE TITLE
[BUG] Cannot set `User-Agent` header in track2 SDK

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-net#26406]
### Library name and version

Azure.ResourceManager

## Description

The following code snippet (copied from https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Pipeline.md#implementing-a-synchronous-policy) doesn't work.

```csharp
public class CustomRequestPolicy : HttpPipelineSynchronousPolicy
{
    public override void OnSendingRequest(HttpMessage message)
    {
        message.Request.Headers.Add("User-Agent", "abc");
    }
}
```

The root cause is that we have an internal override https://github.com/Azure/azure-sdk-for-net/blob/d269eede20a23edec101477601a2b90bee54e690/sdk/resourcemanager/Azure.ResourceManager/src/Internal/MgmtTelemetryPolicy.cs#L21
So external users cannot simply set `User-Agent` by `Headers.Add()` or `Headers.Set()`.

### Expected behavior

The following code snippet should add a `User-Agent` header value.

```csharp
public class CustomRequestPolicy : HttpPipelineSynchronousPolicy
{
    public override void OnSendingRequest(HttpMessage message)
    {
        message.Request.Headers.Add("User-Agent", "abc");
    }
}
```

### Actual behavior

`User-Agent` header value cannot be modified through `Headers.Add()` or `Headers.Set()`.

### Reproduction Steps

Try the code snippet at the beginning.

**Comment by archerzz** [comment]
I think we need to make a decision: shall we allow users to modify `User-Agent`? We could change the logic in `MgmtTelemetryPolicy.cs` to add (v.s. set) the value passed by `UserAgentOverride`, which will make sure the `User-Agent` set by each SDK will be passed to back-end.

**Comment by archerzz** [comment]
Or, if we allow users to set the value (e.g. `Headers.Set()`), then we can:

1. remove the `MgmtTelemetryPolicy.cs`
2. change `autorest.csharp` to generate code to simply `request.Headers.Add("User-Agent", _userAgent);`, instead of 
https://github.com/Azure/azure-sdk-for-net/blob/d269eede20a23edec101477601a2b90bee54e690/sdk/compute/Azure.ResourceManager.Compute/src/Generated/RestOperations/CloudServicesRestOperations.cs#L63

**Comment by ArthurMa1978** [comment]
I think user can the `set` but can `add`

**Comment by BethanyZhou** [comment]
``` message.SetProperty("UserAgentOverride", _userAgent)``` will override the user-agent information about azsdk-net-ResourceManager.KeyVault/1.0.0-beta.5
![image](https://user-images.githubusercontent.com/19869716/149864369-9d3c7209-430d-4823-bf4c-9461a44226ea.png)
**After:**
![image](https://user-images.githubusercontent.com/19869716/149864150-efdf4924-b67d-450f-b895-10d191b3c2db.png)

**Comment by archerzz** [comment]
`Message.SetProperty("UserAgentOverride", _userAgent)` is an internal method, which:
- better not be used outside of Azure .Net SDK
- will override any other `user-agent` values including `user-agent` of SDK, which is not good for telemetry

However, after discussion, it seems not good to allow multiple `user-agent` as well, because back-end analytics might not be able to correctly handle the case that `user-agent` is an array. Some may only pick up the first one, and all the remaining is lost.

A better solution is to merge all `user-agent` header values into one, separated by space. That seems a best practice which has been used in browsers for many years, like `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36`

**Comment by archerzz** [comment]
I checked with Powershell team. And it looks like the backend analytics can support long strings. So appending custom `user-agent` headers seems the best option, e.g. the final header value will look like:

> azsdk-net-ResourceManager.Tests/1.0.0-alpha.20220124.1 (.NET Framework 4.8.4420.0; Microsoft Windows 10.0.19043 ) AzurePowershell/v6.6.0 Az.KeyValue/4.1.0 PSVersion/v7.1.3

**Comment by archerzz** [comment]
Besides, in Powsershell + track1 SDK, the `User-Agent` is like below:

> User-Agent: FxVersion/6.0.21.52210 OSName/Windows OSVersion/Microsoft.Windows.10.0.19044 Microsoft.Azure.Management.ResourceManager.Version2021.01.01.SubscriptionClient/1.3.53 AzurePowershell/v0.0.0 Az.Accounts/2.7.0 PSVersion/v7.2.1

Note:
- In track1, we support `AddHeader`
- In track1, the custom header is appended, instead of generating an array
