### ISSUE TITLE
[FEATURE REQ] Please add method RenewMessageLockAsync to ServiceBusMessageActions

### ISSUE THREAD

**Issue by StannieV** [Azure/azure-sdk-for-net#26402]
### Library name

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Please describe the feature.

Greetings,

I'm looking into the code to switch my application from 'Microsoft.Azure.ServiceBus' to 'Azure.Messaging.ServiceBus' by updating the package 'Microsoft.Azure.WebJobs.Extensions.ServiceBus' to version 5.2.0.

In my Azure functions, we use the 'MessageReceiver' from the binding and use the 'RenewLockAsync' method. In the new available binding types, I saw that there is a 'ServiceBusMessageActions' that can be used in the bindings and can perform several actions on the message. Unfortunately, there is no method 'RenewMessageLockAsync'. Would it be possible to add this method? Or are there alternatives?

Until now I've come with the following "solution":

1. Bind to the 'ServiceBusClient'
2. Create a new messageReceiver with the CreateReceiver method
3. Use RenewMessageLockAsync of the messageReceiver.

The downside of this is that the CreateReceiver method requires the queue name as a parameter, and the queue name can not be resolved via a binding. This would mean I have to retrieve it from a config value of hardcode it. This wouldn't be my preferred solution. 

Thanks in advance!

**Comment by JoshLove-msft** [comment]
Hi @StannieV,
Does your function receive a single message at a time? If so, can you use the maxAutoLockRenewalDuration setting - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#additional-settings-for-version-5x

**Comment by StannieV** [comment]
Hello @JoshLove-msft,

Thanks for your input, but in my scenario I still need/want to renew the lock.

Our AzureServiceBus queues are configured with a lock duration of 5min (max value). When a ServiceBus triggered Azure Function throws an exception, we renew the lock. This way the message will not be handled for another 5 min before it's retried. 
Without this, the message will be moved back right away to the queue and other instances of the function will do the retry within a very short time and moved to the deadletter queue. This is not desired because there could be a temporary issue with an external API or a database connection. By doing it like this, we can spread the number of retries over a longer period. So with a delivery count of 10, it will be tried 10 times in a timespan of 50 minutes. Which makes it more likely that an external issue is solved before the message is moved to the deadletter queue.

**Comment by JoshLove-msft** [comment]
Thanks for that additional information. We can look into exposing this method.

**Comment by AbhishekTripathi** [comment]
I added my comment on another thread. We also require the manual lock renewal. I think the exposed APIs should not suddenly be deprecated and if at all it happens, it should be documented with the workaround to achieve old behavior.

https://github.com/Azure/azure-sdk-for-net/issues/25375#issuecomment-1023357266

**Comment by dionoid** [comment]
One of the products which my team is building also depends on calls to RenewMessageLockAsync, because in our case the default "baked in" lock renewal-algorithm (= renewing max 10 seconds before the lock times out) is not working.
Please allow access to renewing the lock token from ServiceBusMessageActions.

**Comment by JoshLove-msft** [comment]
Note to self - in order to expose this in MessageActions, we'd need to expose it in the Service Bus SDK in ProcessMessageEventArgs as well.

**Comment by Stolpe** [comment]
@JoshLove-msft, this sounds related to my feature request from a while back. You helped me to find a workaround that time, but I don't think that workaround is a good way forward here: https://github.com/Azure/azure-sdk-for-net/issues/24874

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft, this sounds related to my feature request from a while back. You helped me to find a workaround that time, but I don't think that workaround is a good way forward here: #24874

Thanks for the reminder! Yes, that workaround would be viable here and is actually mentioned by @StannieV in the issue description.

**Comment by ramonsmits** [comment]
> One of the products which my team is building also depends on calls to RenewMessageLockAsync, because in our case the default "baked in" lock renewal-algorithm (= renewing max 10 seconds before the lock times out) is not working. Please allow access to renewing the lock token from ServiceBusMessageActions.

@dionoid Renewing just in time just 10 seconds before the lock times out is not recommended. It that renew attempt fails there will be no time to renew again. This can especially happen when the system is very busy.

A better approach is to renew at a certain renewal interval which is 1/5th, 1/4th, 1/3th, or 1/2 of the lock duration.  This way you get a much more fine grained sliding renewal which allows for the renewal to occasionally fail when the system is very busy or network conditions are flaky (assume no reliable network).

For example, lock duration is 5 minutes, renew the lock every minute. This is much safer and better.

**Comment by alexkarcher-msft** [comment]
🎉🎊🥳🎉🍾🎉🎊
