### ISSUE TITLE
[QUESTION] How to create objects / mocks for Azure.ResourceManager.Resources (preview)

### ISSUE THREAD

**Issue by DOMZE** [Azure/azure-sdk-for-net#26417]
### Library name and version

Azure.ResourceManager.Resources 1.0.0-beta.5

### Query/Question

In the article you guys provided, that is https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/, you said that the libraries include Factory classes to create objects to be used in unit testing. I am looking for a way to create ResourceGroups (ResourceGroupData even).

There doesn't seem to be a way to create those currently and no factory is available for that.

Please advise on the proper way to do this.

Thank you

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by DOMZE** [comment]
Any updates on this or guidance?

**Comment by HarveyLink** [comment]
The document is not fully fit for the current MGMT SDK design, you could reference this article to build the mock test: https://github.com/azure/autorest.csharp/issues/1631

**Comment by DOMZE** [comment]
What is the expected timeline on getting this up to par with the other SDKs?

**Comment by DOMZE** [comment]
@HarveyLink Currently we use the actual model objets as a reference in our domain objets, so we need to be able to create them.
Why are the constructors internal? making them public would pretty much solve the problem.

I dont want to mock the actual call to the client, but want to be able to create resource objects, i.e. a ResourceGroupData using it's internal constructor:
```csharp
internal ResourceGroupData(ResourceIdentifier id, string name, ResourceType resourceType, SystemData systemData, IDictionary<string, string> tags, AzureLocation location, ResourceGroupProperties properties, string managedBy) : base(id, name, resourceType, systemData, tags, location)
{
	Properties = properties;
	ManagedBy = managedBy;
}
```

What are you guys take on that?

**Comment by HarveyLink** [comment]
Hi @DOMZE , we're working on adding model factroy for mock test, it will be added in next few weeks.

**Comment by NateB2** [comment]
Any update on this?  We also need the model factory for our unit tests.

**Comment by juliusl** [comment]
An easy way to get around this is to use Newtonsoft.Json to Deserialize the type you want. For example if you're using Moq, 

```
    class MockAzureQueueResponse : Mock<Azure.Response<SendReceipt>> { 
    
        public MockAzureQueueResponse() {
            var sendReceipt = JsonConvert.DeserializeObject<SendReceipt>(@"{ ""MessageId"": ""Test"", ""PopReceipt"": ""Test"" }");
            SetupGet(r => r.Value).Returns(sendReceipt);
        }
    }
```

**Comment by JakobGSvendsen** [comment]
Any update on this? We cannot use the new library as our company rules requires unit testing of all code. We have to write new code (today) that uses the deprecated library due to this

**Comment by ArthurMa1978** [comment]
The [model factory](https://github.com/azure/autorest.csharp/issues/2112) is in our Oct. planning

**Comment by jhested** [comment]
Hi @ArthurMa1978 ,

Looking at the pull requests, it seems like they have been abandoned?
https://github.com/Azure/autorest.csharp/pull/2107
https://github.com/Azure/autorest.csharp/pull/2441

Is this going to be added in october?
It is such a pain to work with the SDK since everything is absurdly difficult to mock.

With the old IAzure client we were able to mock everything using interfaces, but since this is becoming obsolete, we prefer not to add anything new to our code base based on that.

However with the new SDK we are spending at least 3-4 times as much work on trying to mock methods and classes than we did before. 

Our company policy says that we need at least 80% code coverage, but for the moment we find it very difficult to do that for every code path that touches the sdk in some way.

I would be very happy to provide you with a few scenarios if you require that, and I wouldn't mind contributing if you can point me in the right direction.

**Comment by shschwar** [comment]
Hi @ArthurMa1978 . @HarveyLink 

Is there news regarding this feature request?
Currently I really can create mock object for testing, and it's pretty hard to work in that way.
Thanks

**Comment by jhested** [comment]
Any update on this?

**Comment by patelh24** [comment]
Any update on this?

**Comment by patelh24** [comment]
an update would be great.

**Comment by jhested** [comment]
Should we go back to using the old mockable sdk or what is the time frame here? 

Any response is greatly appreciated!

**Comment by ArthurMa1978** [comment]
We're working on the new feature https://github.com/Azure/autorest.csharp/issues/2112 which will provide the capability soon

**Comment by ArthurMa1978** [comment]
Close it as this is tracked by the feature https://github.com/Azure/autorest.csharp/issues/2112
