### ISSUE TITLE
[BUG] GetGenericResource Method of Azure.ResrouceManager.ArmClient returns 'invalid resource id was given' for valid resource

### ISSUE THREAD

**Issue by asmithgt** [Azure/azure-sdk-for-net#26415]
### Library name and version

Azure.ResourceManager 1.0.0-beta.7

### Describe the bug

On instance of Azure.ResourceManager.ArmClient attempting to execute method GetGenericResource using a ResourceIdentifier object as input a return object of GenericResource is expected, yet am given the error: 
`System.Private.CoreLib: Exception while executing function: ActivityTagging. Azure.ResourceManager: An invalid resouce id was given /subscriptions/<redacted-guid>/resourceGroups/AZNCPOCMTC_POC01/providers/MICROSOFT.COMPUTE/VIRTUALMACHINES/TESTVM`

### Expected behavior

Return an object of type GenericResource.

### Actual behavior

Exception encountered with error message:
`System.Private.CoreLib: Exception while executing function: ActivityTagging. Azure.ResourceManager: An invalid resouce id was given /subscriptions/<redacted-guid>/resourceGroups/AZNCPOCMTC_POC01/providers/MICROSOFT.COMPUTE/VIRTUALMACHINES/TESTVM`

### Reproduction Steps

Using .Net 6 and built as an Azure Function with function runtime 4.0 include the following in you code:

```
ArmClient` armClient = new ArmClient(new DefaultAzureCredential());

string testMe = "/subscriptions/<redacted-guid>/resourceGroups/AZNCPOCMTC_POC01/providers/MICROSOFT.COMPUTE/VIRTUALMACHINES/TESTVM";
ResourceIdentifier testId = new ResourceIdentifier(testMe);

GenericResource testres = await armClient.GetGenericResource(testId)
         .GetAsync();
```
Of course use a valid GUID on a valid subscription with a VM titled "TESTVM" or something similar.  In doing so, the final line to GetGenericResource will generate exception.

### Environment

Using Latest Stable VSCode with Azure Functions and C# extensions.

VSCode Info:

```
Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043
```

DotNet Environment:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.101     
 Commit:    ef49f6213a  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19043
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by archerzz** [comment]
@asmithgt I could not reproduce the error. However, it seems that there is an issue in the resource id: /subscriptions/<redacted-guid>/resourceGroups/AZNCPOCMTC_POC01/providers/**MICROSOFT.COMPUTE/VIRTUALMACHINES**/TESTVM

See the corresponding API definition: https://github.com/Azure/azure-rest-api-specs/blob/ac0ab10f7605f63dfb8854fede1dbf6daa9df825/specification/compute/resource-manager/Microsoft.Compute/stable/2021-07-01/compute.json#L2990

Use the following pattern:
> string testMe = "/subscriptions/<redacted-guid>/resourceGroups/AZNCPOCMTC_POC01/providers/Microsoft.Compute/virtualMachines/TESTVM"

Also make sure you have the correct access privilege to the target VM under the current credential.

**Comment by asmithgt** [comment]
Thank you @archerzz - This is curious as the example value that I'm using is actually pulled directly from Azure Activity Logs.  I'm writing an event driven Azure Function to assist in managing our Azure environment so it ingests logs via EventHub.  See the screenshot below with two different versions of the Resource ID that I found from the EventHub Message Data:
![image](https://user-images.githubusercontent.com/48996971/150778843-545804eb-1cf2-4da4-b044-d5b05aaa0827.png)

And yep... It appears to work when using the more "Nested" ID, though I must say it's a bit misleading to have the one that is incorrectly formatted at a higher level.

As a side note, I am unsure how to determine from the link you sent as to what is case sensitive and what is not.

Regardless, thank you for looking into this.

-Adam

**Comment by archerzz** [comment]
@asmithgt I think it would be better to honor the standard. URL case is a hot problem, see https://webmasters.stackexchange.com/questions/90339/why-are-urls-case-sensitive:
> So, the scheme and host are case-insensitive.
> The rest of the URL is case-sensitive.

The `recordId` property returned from Azure Activity Logs are not correctly formatted. It makes every letter upper case. That looks like a bug to me.

**Comment by ankushbindlish2** [comment]
Try **ResourceIdentifier.Parse(id)** instead of **new ResourceIdentifier(id)**
