### ISSUE TITLE
Update Sample Code that are currently using fluent SDK to T2 SDK- Compute

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-net#26424]
Azure-Samples/compute-dotnet-create-virtual-machines-across-regions-in-parallel
Azure-Samples/compute-dotnet-create-virtual-machines-from-generalized-image-or-specialized-vhd
Azure-Samples/compute-dotnet-list-compute-skus
Azure-Samples/compute-dotnet-list-vm-extension-images
Azure-Samples/compute-dotnet-list-vm-images
Azure-Samples/compute-dotnet-manage-availability-sets
Azure-Samples/compute-dotnet-manage-managed-disks
Azure-Samples/compute-dotnet-manage-resources-from-vm-with-msi-in-aad-group
Azure-Samples/compute-dotnet-manage-user-assigned-msi-enabled-virtual-machine
Azure-Samples/compute-dotnet-manage-virtual-machine-scale-sets
Azure-Samples/compute-dotnet-manage-virtual-machine-scale-sets-async
Azure-Samples/compute-dotnet-manage-virtual-machine-scale-set-with-unmanaged-disks
Azure-Samples/compute-dotnet-manage-virtual-machines-in-parallel
Azure-Samples/compute-dotnet-manage-virtual-machines-with-network-in-parallel
Azure-Samples/compute-dotnet-manage-virtual-machine-using-vm-extensions
Azure-Samples/compute-dotnet-manage-virtual-machine-with-disks
Azure-Samples/compute-dotnet-manage-virtual-machine-with-unmanaged-disks
Azure-Samples/compute-dotnet-manage-vm
Azure-Samples/compute-dotnet-manage-vm-async
Azure-Samples/compute-dotnet-manage-vm-from-vm-with-msi-credentials
Azure-Samples/compute-dotnet-manage-vms-in-availability-zones
Azure-Samples/compute-dotnet-manage-vmss-in-availability-zones

**Comment by pallavit** [comment]
@ArthurMa1978 is this still a valid concern?
