### ISSUE TITLE
Update Sample Code that are currently using fluent SDK to T2 SDK- CosmosDB

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-net#26423]
Azure-Samples/cosmosdb-dotnet-create-cosmosdb-and-configure-for-high-availability
Azure-Samples/cosmosdb-dotnet-create-cosmosdb-and-configure-for-eventual-consistency
Azure-Samples/cosmosdb-dotnet-create-cosmosdb-and-configure-firewall
Azure-Samples/cosmosdb-dotnet-create-table-with-virtual-network-rule
Azure-Samples/cosmosdb-dotnet-create-cosmosdb-and-get-mongodb-connection-string

**Comment by pallavit** [comment]
@ArthurMa1978 is this still valid?

**Comment by pallavit** [comment]
@ArthurMa1978 is this still a valid concern?
