### ISSUE TITLE
Error : Event Hub Trigger  The response ended prematurely, with at least 156 additional bytes expected.

### ISSUE THREAD

**Issue by emrekara37** [Azure/azure-sdk-for-net#26434]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventHubs 4.3.0

### Query/Question

Hi,
i created basic event hub trigger function but i am getting this error. 

Event hub namespace tier is basic and have 2 event hub 

![image](https://user-images.githubusercontent.com/17519791/149901211-df345bef-658a-4348-a5af-a18bfc3a3131.png)

![image](https://user-images.githubusercontent.com/17519791/149901305-9d4d2de4-9095-4682-b3a5-b20e1a89e638.png)

### Environment

.net core 3.1

.net sdk functions 3.0.13

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.WebJobs.Extensions.EventHubs` package is maintained for versions earlier than 5 as [#103](https://github.com/Azure/azure-functions-eventhubs-extension/issues/103).
