### ISSUE TITLE
Environment variable evaluation should be standardized in Azure.Core

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#26437]
### Library name

Azure.Core

### Please describe the feature.

This would enable consistent logging, and possibly API change evaluation.

**Comment by pakrym** [comment]
Consider banning Environment.GetEnvironemtVariable and forcing everyone through a common helper.

**Comment by pallavit** [comment]
@christothes is this still a valid concern? Can you please share what kind of inconsistencies are we talking about here?

**Comment by christothes** [comment]
> @christothes Christopher Scott FTE is this still a valid concern? Can you please share what kind of inconsistencies are we talking about here?

Yes - the goal here would be to standardize so that environment variable configuration can be treated as part of the public API surface and all that comes along with that.
