### ISSUE TITLE
Add documentation on how to write an autorest.md file for LLC

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#26449]
This should cover:
- What to do for LLC
- What options are available as configuration to the generator
- A mention of swagger transforms we add to these files

**Comment by annelo-msft** [comment]
@AlexanderSher, @ShivangiReja, @m-nash, do any of you know if we already have this?

**Comment by pallavit** [comment]
@lirenhe could you please route this to the right person if this is still valid.

**Comment by lirenhe** [comment]
We are now prioritizing the work for TypeSpec => DPG so in the future, we don't expect service teams that would still leverage authoring autorest.md for onboarding.  
Close this one but I am fine to revisit it if we got more asks from service team.
