### ISSUE TITLE
[QUERY] Clarification on Snapshot propery in BlobItem

### ISSUE THREAD

**Issue by afink-osi** [Azure/azure-sdk-for-net#26446]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Query/Question

**Background**
We are currently working on migrating a Service Fabric application from Azure Storage SDK 11.x to make use of the updated Azure Storage SDK 12.x.  This application is responsible for various tasks including copying blob snapshots to different storage accounts, as well as being able to select a specific snapshot to restore.  

In the past, the [CloudBlob.SnapshotTime ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblob.snapshottime?view=azure-dotnet-legacy) was represented as a DateTime offset and we stored this DateTime in SQL for future reference for restoration.  Now, there is the [BlobItem.Snapshot](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobitem.snapshot?view=azure-dotnet#azure-storage-blobs-models-blobitem-snapshot) property which is of type string but represents the DateTime of the snapshot, seemingly according to [ISO8610](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)). 

**Question**
Is it safe to interpret this string as a DateTime type object and store it as a DateTime, so long as we reformat the DateTime to the correct string format when attempting to access a specific snapshot?  Is it expected for this string formatting for the Snapshot property to change often?

### Environment

Windows 10
Visual Studio 17.0.5

**Comment by amishra-dev** [comment]
@jaschrep-msft can you please look into this?

**Comment by jaschrep-msft** [comment]
The snapshot property reflects the snapshot ID as defined by the service. [The service assigns snapshot IDs as a datetime](https://docs.microsoft.com/en-us/rest/api/storageservices/creating-a-snapshot-of-a-blob). I would consider it safe to interpret this string as such.
