### ISSUE TITLE
[QUERY] - Guidance on generating models to interact with Purview API

### ISSUE THREAD

**Issue by upton2805** [Azure/azure-sdk-for-net#26447]
### Library name and version

Azure Purview Catalog client library for .NET

### Query/Question

Is there any guidance on how to generate request and response models to interact with Purview API? Current documentation contains json schema but that is not very helpful.

**Comment by SaurabhSharma-MSFT** [comment]
@upton2805 Can you please share the documentation which you are talking about. Also, could you please check [this](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/analytics.purview.catalog-readme-pre) document for using Azure Purview Catalog client.
