### ISSUE TITLE
Make Always Encrypted Azure Key Vault Provider .NET Core Compatible

### ISSUE THREAD

**Issue by moraleslos** [Azure/azure-sdk-for-net#2644]
I'm trying to use the Always Encrypted feature of SQL Server 2016 with .NET Core and seems like it can not be used (yet). When trying to import the `Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider` from Nuget, I get an error stating it is not compatible:

`Package Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider 1.0.201501028 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6)`

Looks like it is dependent on the old Microsoft.Azure.KeyVault 1.0.0, which is incompatible. However the latest version of Microsoft.Azure.KeyVault is 2.0.6, which is compatible with NetStandard. Is it possible to update your provider library to use Microsoft.Azure.KeyVault 2.0.6 so that it is .NET Core compatible?

**Comment by NikhilVithlaniMicrosoft** [comment]
Always Encrypted is currently not supported on .Net Core
You can find the list of supported frameworks [here 
](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-client-development)

Adding Support for .NET core is on our roadmap, we do not have timeline for it yet

**Comment by jaszymas** [comment]
Here is the Connect suggestion we use to track this work item: https://connect.microsoft.com/SQLServer/feedback/details/3116315/a-net-core-compatible-version-library-for-always-encrypted.
Please submit your vote there - this will help us prioritize this investment.

**Comment by Ian1971** [comment]
Any movement on this issue yet? MS is keen to get everyone on to Core and .Net standard but here is yet another blocker that stops us.

**Comment by Architekt909** [comment]
Any update on this? I can't update to Azure Functions v2 because of this. I don't see how we're supposed to use the new runtime if this isn't ever going to be updated.

**Comment by David-Engel** [comment]
Just FYI, [Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient) public preview was announced Monday and adds Always Encrypted support against .NET Core 2.1+. This should enable the team that owns Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider to add support for .NET Core.

**Comment by Ian1971** [comment]
@David-Engel Hallelujah!

**Comment by dbogatov** [comment]
What's the status so far?

**Comment by SgtSpamCan** [comment]
Status Please?   Critical for anyone using Always Encrypted in an App Service with .Net Core

**Comment by David-Engel** [comment]
@SgtSpamCan We have an open issue in the SqlClient repo to track the status. The latest update:
https://github.com/dotnet/SqlClient/issues/111#issuecomment-524434137

**Comment by jeroenterheerdt** [comment]
closing this issue as other tracking issue has been resolved.

**Comment by jeroenterheerdt** [comment]
@jaredmoo please go ahead an close this.
