### ISSUE TITLE
Update LLC documents in the azure-sdk-for-net repo

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#26454]
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/ProtocolMethods.md - is this up to date with recommended best practices?
- Contributing.md - point to Data Plane Code Generation getting started docs
- https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core#key-concepts: Add RequestContext

**Comment by archerzz** [comment]
- [ ] https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/ProtocolMethods.md - is this up to date with recommended best practices?
- [ ] Contributing.md - point to Data Plane Code Generation getting started docs
- [x] https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core#key-concepts: Add RequestContext

**Comment by archerzz** [comment]
close since all sub-tasks are complted.
