### ISSUE TITLE
Prevent build breaks from source shared from non-Core libraries

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#26482]
From this PR (https://github.com/Azure/azure-sdk-for-net/pull/26480) we learned that we should run pipelines for any libraries that use shared source from a given library.

We should update CIs to run pipelines for any libraries that depend on shared source from a given library across the repo, to prevent this class of build breaks.

**Comment by christothes** [comment]
FYI - I created a script a while back that builds up a solution containing all the projects referencing changes to shared source from core. Perhaps it would be useful for however we decide to solve this problem.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/generate_shared_ref_solution.ps1

**Comment by annelo-msft** [comment]
@JoshLove-msft, could you help us understand why we're doing this for Storage/EG?

**Comment by JoshLove-msft** [comment]
The Storage functions extensions leverage event grid for their trigger. The code that is shared shouldn't be public as customers wouldn't need to use it. I'd agree that this is an unusual scenario, but I don't think we need to disallow it. If we are able to figure out how to fail the pipeline when cross-service shared code is encountered, that means we could just take one more step and run the pipeline for the library that is using the shared code.

**Comment by jsquire** [comment]
Couldn't we elevate it to part of Core/Shared?   I would imagine that the "uses Event Grid for trigger" scenario won't be unique to Storage?

**Comment by JoshLove-msft** [comment]
Technically, this could apply to regular package dependencies between libraries as well. Although we already have validation to prevent API breaks, there could be a behavior change that would break a dependent library, which wouldn't be caught until that library's pipeline is run.

**Comment by JoshLove-msft** [comment]
> Couldn't we elevate it to part of Core/Shared? I would imagine that the "uses Event Grid for trigger" scenario won't be unique to Storage?

It has a bunch of Event Grid dependencies in it, so not really.

**Comment by christothes** [comment]
Are there other EventGrid extension types that are commonly shared? Perhaps as a convention we should place these types in /Shared/ folder just to be explicit that it is intended to be shared.

**Comment by JoshLove-msft** [comment]
> > Couldn't we elevate it to part of Core/Shared? I would imagine that the "uses Event Grid for trigger" scenario won't be unique to Storage?
> 
> It has a bunch of Event Grid dependencies in it, so not really.

I suppose we can just remove the shared files from being built in Azure.Core, but it still seems odd to have a random file like this in there.

**Comment by JoshLove-msft** [comment]
> Are there other EventGrid extension types that are commonly shared? Perhaps as a convention we should place these types in /Shared/ folder just to be explicit that it is intended to be shared.

It is just these, but that is a good point, we can at least move them into a Shared folder. That might be an easy convention to enforce in the pipeline as well - only using files from other libraries if they are in a Shared folder.

**Comment by jsquire** [comment]
The folder convention is a good start.  At least that acts as a signal that the author of shared files is aware that there may be external dependencies that rely on them.   I still find the concept concerning, and I think we need a good way to answer the question "who is using this file that I shared."
