### ISSUE TITLE
[BUG] Serialization bug in ResourceIdentity model

### ISSUE THREAD

**Issue by arjunbalgovind** [Azure/azure-sdk-for-net#26489]
### Library name and version

Azure.ResourceManager 1.0.0-beta.7, Azure.ResourceManager.Compute 1.0.0-beta.5

### Describe the bug

The ResourceIdentity model has a serialization bug which results in BadRequest errors if a VM Update operation is executed which involves a change in its **Identity** member. I came across this bug while migrating some code that was written in the Compute.Fluent library to the Azure.ResourceManager.Compute library (because the Fluent libraries use API versions from 2020). 

I was able to trace the request through Fiddler and this was what the request body looks like for the VM Update request. It appears that "identity" appears twice, which is what is causing the failure.

`PATCH /subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.Compute/virtualMachines/<REDACTED>?api-version=2021-03-01 HTTP/1.1`

```
{"identity":{"identity":{"principalId":"<REDACTED>","tenantId":"<REDACTED>","type":"SystemAssigned, UserAssigned","userAssignedIdentities":{"/subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<REDACTED>":{}"/subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<REDACTED>":{}}}},"properties":{}}
```

Unrelated, but another observation was that the API version is 2021-03-01 even though there is a 2021-07-01 REST API available. When would this likely be updated?

### Expected behavior

VM Update request that contains a change in Identity should be successful and not have serialization errors.

### Actual behavior

Azure.RequestFailedException: 'The request content was invalid and could not be deserialized: 'Could not find member 'identity' on object of type 'ResourceIdentity'. Path 'identity.identity', line 1, position 24.'.
Status: 400 (Bad Request)
ErrorCode: InvalidRequestContent

Content:
{"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Could not find member 'identity' on object of type 'ResourceIdentity'. Path 'identity.identity', line 1, position 24.'."}}

### Reproduction Steps

The following code snippet can be used as a repro.
```
ResourceGroup resourceGroup = await subscription.GetResourceGroups().GetAsync(rgName);
VirtualMachineCollection vmCollection = resourceGroup.GetVirtualMachines();
VirtualMachine vm = vmCollection .Get(vmName);
VirtualMachineUpdate updateParameters = new VirtualMachineUpdate();

updateParameters.Identity = vm.Data.Identity;

// Even if you run UpdateAsync without making a change to the Identity member, the error can be reproduced. A real world example though is to remove a user assigned identity.
// updateParameters.Identity.UserAssignedIdentities.Remove(new ResourceIdentifier(userAssignedIdToRemove));
await vm.UpdateAsync(updateParameters);
```

### Environment

Windows 10, .NET 5.0.13
Visual Studio 17.0.0 Preview

**Comment by ArcturusZhang** [comment]
We are changing the implementation of this in the resourcemanager now. cc @fengzhou-msft

**Comment by fengzhou-msft** [comment]
It's renamed to ManagedServiceIdenity which follows the common type [definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/managedidentity.json). The fix will be released with Azure.ResourceManager 1.0.0-beta.8 and Azure.ResourceManager.Compute 1.0.0-beta.6.

**Comment by fengzhou-msft** [comment]
> It's renamed to ManagedServiceIdentity which follows the common type [definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/common-types/resource-management/v4/managedidentity.json). The fix will be released with Azure.ResourceManager 1.0.0-beta.8 and Azure.ResourceManager.Compute 1.0.0-beta.6.

The fix is released. Please try them and let us know if you still meet issues.
