### ISSUE TITLE
[QUERY] how to use FindBlobsByTags correctly in CSharp

### ISSUE THREAD

**Issue by ksaye** [Azure/azure-sdk-for-net#26481]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Query/Question

I am trying to query Block Blobs that are newer than a date.  I thought the FindBlobsByTags() using the Property LastModified would work, but it does not seem to work.  Is there an example somewhere?

My attempt:
```
            BlobServiceClient blobServiceClient = new BlobServiceClient(ConnectionString);

            //Pageable<TaggedBlobItem> aa = blobServiceClient.FindBlobsByTags("LastModified > '2022-01-01'");

            foreach (TaggedBlobItem aa in blobServiceClient.FindBlobsByTags("LastModified > '2022-01-01 20:51:26Z'"))
            {
                Console.WriteLine(aa.BlobName + " ==> " + aa.Tags.ToString());
            }
```

Clearly this will work, but it must iterate through the blocks client side:
```
  foreach (BlobItem blob in blobContainerClient.GetBlobs().OfType<BlobItem>().Where(item=>item.Properties.CreatedOn.Value >= DateTimeOffset.Now.AddDays(-30)))
            //foreach (BlobItem blob in blobContainerClient.GetBlobs())
            {
                Console.WriteLine(blob.Name + " => " + blob.Properties.CreatedOn.Value);
            }
```

### Environment

.Net 3.1
Visual Studio 16

**Comment by PramodValavala-MSFT** [comment]
@ksaye Looks like this is [only for index tags](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal#choosing-between-metadata-and-blob-index-tags) and doesn't work for metadata or system properties.

Apart from looping over the blobs on the client end, the best approach seems to be updating a tag with the last modified timestamp manually to use for querying later. Another option seems to be [using Azure Search for Blobs](https://docs.microsoft.com/en-us/azure/search/search-howto-indexing-azure-blob-storage) which can index [standard metadata](https://docs.microsoft.com/en-us/azure/search/search-howto-indexing-azure-blob-storage#indexing-blob-metadata) as well.

**Comment by PramodValavala-MSFT** [comment]
@ksaye Just following up here... Hope my previous comment clears things up.

**Comment by ksaye** [comment]
@PramodValavala-MSFT, yes thanks for the comments.  I will review both options, closing for now.
