### ISSUE TITLE
[BUG] Text Analytics: Feature Availability

### ISSUE THREAD

**Issue by BaherAbdullah** [Azure/azure-sdk-for-net#26501]
### Library name and version

Azure.AI.TextAnalytics 5.1.X

### Describe the bug

I am trying to use this library with custom NER and classification, but its not working, only version 5.2.0-beta.2 is working. If this is the case, please call it out in the file to guide the users. 

### Expected behavior

It should work

### Actual behavior

Its now working with 5.1.X version

### Reproduction Steps

see description

**Comment by jsquire** [comment]
Hi @BaherAbdullah.   Thank you for reaching out and we regret that you're experiencing difficulties.  I'm afraid that I'm not able to follow the scenario that you're describing.    Can you help me to understand how you're using the Text Analytics client library and which documentation you believe has a gap?    Would you also please clarify your statement in the "Actual behavior" section?   The text "Its now working with 5.1.x version" seems to imply that there is no longer an issue?

**Comment by BaherAbdullah** [comment]
Hello @Jesse ***@***.***>,

So I want trying to use the Text Analytics client library, but I noticed that for Custom Text classification and Custom Text Extraction, I need version 5.2.0-beta 2, but this is not clear in the documentation. So can we kindly add this part to helps the users know which version they should use?

Best,
Baher

**Comment by jsquire** [comment]
Hi @BaherAbdullah.   Can you share a pointer to the documentation that you're referencing?

**Comment by BaherAbdullah** [comment]
HYG, azure-sdk-for-net/README.md at main * Azure/azure-sdk-for-net (github.com)<https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/README.md>

**Comment by jsquire** [comment]
Hi @BaherAbdullah.  Thank you for the additional context, and apologies for the confusion.  Generally speaking, we'd recommend referencing documentation via the MS Docs site.  This will always refer to the latest GA package and the "Overview" section reflects the content from that README.   For example, the [Text Analytics Overview](https://docs.microsoft.com/dotnet/api/overview/azure/ai.textanalytics-readme?view=azure-dotnet) reflects v5.1.1 as the latest GA package.

What you're seeing for README content in that URL is correct; `main` represents the current state in the repository.   The README content in the repository for the specific version of a package should be referenced from the tag for that package.  For example, v5.1.1 is available [here](https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.TextAnalytics_5.1.1/sdk/textanalytics/Azure.AI.TextAnalytics/README.md).  The correct README for each package version is linked in its NuGet page in the "Project Website" in the right-hand column and is now also appearing in full in the NuGet README tab.

The approach that we use for documenting when features are added to the package is its [change log](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/CHANGELOG.md).  In addition to the repository, these details are also available on the NuGet page for Azure SDK packages in the "Release Notes" tab.
