### ISSUE TITLE
[QUERY] Front Door RulesEngine Rule creation: @odata.type InvalidResource

### ISSUE THREAD

**Issue by coppercosmo** [Azure/azure-sdk-for-net#26503]
### Library name and version

Microsoft.Azure.Management.FrontDoor 4.0.0

### Query/Question

When trying to create a RulesEngine Rule Action, and I use this json block:
`              
"rulesEngineRules": [
                {
                  "name": "rulesEngine1",
                  "priority": 1,
                  "matchProcessingBehavior": "Continue",
                  "action": {
                    "routeConfigurationOverride": {
                      "@odata.type": "#Microsoft.Azure.FrontDoor.Models.FrontdoorForwardingConfiguration",
                      "backendPool": {
                        "id": "string"
                      },
                      "cacheConfiguration": {
                        "dynamicCompression": "string",
                        "queryParameterStripDirective": "string"
                      },
                      "customForwardingPath": "string",
                      "forwardingProtocol": "string"
                    },
                    "requestHeaderActions": [
                      {
                        "headerActionType": "string",
                        "headerName": "string",
                        "value": "string"
                      }
                    ],
                    "responseHeaderActions": [
                      {
                        "headerActionType": "string",
                        "headerName": "string",
                        "value": "string"
                      }
                    ]
                  },
                  "matchConditions": [
                    {
                      "negateCondition": "bool",
                      "rulesEngineMatchValue": [ "string" ],
                      "rulesEngineMatchVariable": "string",
                      "rulesEngineOperator": "string",
                      "selector": "string",
                      "transforms": [ "string" ]
                    }
                  ]
                }
              ]
`

The error response I'm receiving says: `"{\n  \"error\": {\n    \"code\": \"InvalidResource\",\n    \"message\": \"Invalid @odata.type property value.\"\n  }\n}"`

I am using this documentation to follow the Rules Engine Rule creation: docs.microsoft.com/en-us/azure/templates/microsoft.network/2020-05-01/frontdoors/rulesengines?tabs=json

Am I doing something wrong here?

### Environment

.NET Core 3.1
VS Enterprise 2022 17.0.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by coppercosmo** [comment]
@Yao725 Any update on this?

**Comment by coppercosmo** [comment]
@Yao725 ?

**Comment by Yao725** [comment]
Hey @coppercosmo , sorry for the delay response, I just come back from the vacation. The link you pasted [here](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/2020-05-01/frontdoors/rulesengines?tabs=json) is using `Bicep` or `ARM template` to deploy the resource. If you follow this doc, I believe you should use `Deployment` in the library resources with corresponding template file.

If you want to use Microsoft.Azure.Management.FrontDoor to create RulesEngine Rule, you can take this [test](https://github.com/Azure/azure-sdk-for-net/blob/43283052ee86842bd1cc2a8efb700ecd78becee1/sdk/frontdoor/Microsoft.Azure.Management.FrontDoor/tests/ScenarioTests/FrontDoorTests.cs#L298) as an example.

If these can not resolve your problem, could you paste the code snipper here so I can try to find what happened.
