### ISSUE TITLE
Cannot get the creation time of a stream by azure-data-lake-store-net

### ISSUE THREAD

**Issue by mrzr1024** [Azure/azure-sdk-for-net#26519]
Hi, anybody could tell me how to get the creation time of a stream by this SDK, I haven't found this property yet.

[DirectoryEntry](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.datalake.store.directoryentry?view=azure-dotnet)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3cbd16-1895-b8cb-916e-c55873ab0b9f
* Version Independent ID: 87b9c89e-ecc4-b236-c988-71c14f258c80
* Content: [Microsoft.Azure.DataLake.Store Namespace - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.datalake.store?view=azure-dotnet)
* Content Source: [xml/ns-Microsoft.Azure.DataLake.Store.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.Azure.DataLake.Store.xml)
* Service: **data-lake-store**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by mrzr1024** [comment]
> Label prediction was below confidence level `0.6` for Model:`ServiceLabels`: 'Data Lake Storage Gen2:0.36103934,Storage:0.12264548,Managed Identity:0.08426343'

Not Data Lake Storage Gen2, but the data-lake-store Gen1

[azure-data-lake-store-net](https://github.com/Azure/azure-data-lake-store-net)
[azure.datalake.store reference](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.datalake.store?view=azure-dotnet)

**Comment by SaurabhSharma-MSFT** [comment]
@mrzr1024 What do you mean by stream. Do you mean creation time of adls output or the actual data being written to adls through output stream?.

**Comment by mrzr1024** [comment]
The stream I mentioned is a file. I need to get the creation time of the file stored in adls.

**Comment by SaurabhSharma-MSFT** [comment]
@mrzr1024 You can use [GetPropertiesAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakefileclient.getproperties?view=azure-dotnet) to get the creation time of a file.  This function returns `CreatedOn` property which can refer in your code as shown below.
![image](https://user-images.githubusercontent.com/38112130/153970360-c6a2dee2-0f9e-4c4f-b50c-937197335000.png)

**Comment by mrzr1024** [comment]
@SaurabhSharma-MSFT  Thank you, but could you tell me where I could get the method GetPropertiesAsync() of DataLakeFileClient? I just found the method GetFileProperties() of [AdlsClient](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.datalake.store.adlsclient?view=azure-dotnet).

**Comment by mrzr1024** [comment]
It seems that the method GetPropertiesAsnyc()  belongs to the Azure.Storage SDK which used for accessing to the ADLS Gen2. So do you mean I could just leverage this SDK to access to ADLS Gen1?

**Comment by SaurabhSharma-MSFT** [comment]
@mrzr1024 Sorry my bad :( .  I checked for ADLS Gen2.  I will check on your ask and get back to you.

**Comment by SaurabhSharma-MSFT** [comment]
@mrzr1024 Just to let you know that after 29 February 2024, you will not be able to create or manage Azure Data Lake Storage Gen1 accounts.  Please see the official announcement over [here](https://azure.microsoft.com/en-us/updates/action-required-switch-to-azure-data-lake-storage-gen2-by-29-february-2024/)
So, is there any specific reason you are trying to get a creation time for ADLS Gen1?

**Comment by mrzr1024** [comment]
Yeah, for compliance purpose, I need to calculate the implicit expiry time by adding the retention days to the creation time for a stream without explicit expiry time.

**Comment by SaurabhSharma-MSFT** [comment]
@mrzr1024 Have you looked at [this](https://github.com/Azure-Samples/data-lake-store-adls-dot-net-get-started/blob/master/AdlsSDKGettingStarted/Program.cs) sample.  It uses FileSystemClient with `PathProperties` to get the `CreatedOn` if this helps to achieve what you are looking for.
![image](https://user-images.githubusercontent.com/38112130/158277404-18b71dc0-d3fa-4fcb-973f-148abc0b22bc.png)
