### ISSUE TITLE
[BUG][ACR] Some constructor overloads of ContainerRegistryClient are invalid

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#26510]
### Library name and version

Azure.Containers.ContainerRegistry

### Describe the bug

If we create a [`ContainerRegistryClient`](https://github.com/Azure/azure-sdk-for-net/blob/dcac296df717dbb75fcc50648c2132d47cd413f2/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/ContainerRegistryClient.cs#L13) with a ctor overload that does not take in a [`ContainerRegistryClientOptions`](https://github.com/Azure/azure-sdk-for-net/blob/dcac296df717dbb75fcc50648c2132d47cd413f2/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/ContainerRegistryClientOptions.cs#L12) object, that overload creates a new instance of `ContainerRegistryClientOptions` and delegates to the ctor that expects the options object to be passed in.
That ctor method body [verifies that](https://github.com/Azure/azure-sdk-for-net/blob/dcac296df717dbb75fcc50648c2132d47cd413f2/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/ContainerRegistryClient.cs#L75) the `Audience` of the options is not null. But, with this call-chain `Audience` will be null and initialization of the object will fail.

### Expected behavior

All ctors should result in successful creation of the object.

### Actual behavior

Constructor [throws ](https://github.com/Azure/azure-sdk-for-net/blob/dcac296df717dbb75fcc50648c2132d47cd413f2/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/ContainerRegistryClient.cs#L77)an `InvalidOperationException`.

### Reproduction Steps

Create an instance of `ContainerRegistryClient` using [this](https://github.com/Azure/azure-sdk-for-net/blob/dcac296df717dbb75fcc50648c2132d47cd413f2/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/ContainerRegistryClient.cs#L31) ctor.

**Comment by annelo-msft** [comment]
This is by design.  At least currently, Audience is required to create an instance of the client, and the overload taking ContainerRegistryClientOptions is the only way to provide that value.  We are currently investigating options to provide a good default value - when we do, we will enable creating via the specified constructor.
