### ISSUE TITLE
[TextAnalytics] AnalyzeHealthcareEntities_Cancellation failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#26522]
TextAnalytics runs are failing with:

> Error message
> Azure.RequestFailedException : Failed to cancel job with job id 07fc2546-2650-4720-932f-aec164c25cb5 as its already completed.
> Status: 400 (Bad Request)
> ErrorCode: InvalidRequest
> 
> Content:
> {"error":{"code":"InvalidRequest","message":"Failed to cancel job with job id 07fc2546-2650-4720-932f-aec164c25cb5 as its already completed."}}
> 
> Headers:
> Transfer-Encoding: chunked
> x-envoy-upstream-service-time: 10
> apim-request-id: e5778255-cd4d-4610-bc6b-1002f659d112
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Thu, 20 Jan 2022 02:53:39 GMT
> Content-Type: application/json; charset=utf-8
> 
> 
> Stack trace
>    at Azure.AI.TextAnalytics.TextAnalyticsRestClient.CancelHealthJob(Guid jobId, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Generated\TextAnalyticsRestClient.cs:line 307
>    at Azure.AI.TextAnalytics.AnalyzeHealthcareEntitiesOperation.Cancel(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\AnalyzeHealthcareEntitiesOperation.cs:line 246
>    at Azure.AI.TextAnalytics.Samples.TextAnalyticsSamples.AnalyzeHealthcareEntities_Cancellation() in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\tests\samples\Sample7_AnalyzeHealthcareEntities_Cancellation.cs:line 41

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1314633&view=results

@jsquire for notification.

**Comment by maririos** [comment]
closing in favor of https://github.com/Azure/azure-sdk-for-net/issues/26528
