### ISSUE TITLE
[Form Recognizer] CopyModel(False) failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#26525]
Form Recognizer runs are failing with:

> Error message
> System.InvalidOperationException : The requested operation requires an element of type 'String', but the target element has type 'Number'.
> 
> 
> Stack trace
>    at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
>    at Azure.AI.FormRecognizer.Models.FormRecognizerError.DeserializeFormRecognizerError(JsonElement element) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/Models/FormRecognizerError.Serialization.cs:line 23
>    at Azure.AI.FormRecognizer.Models.V2AnalyzeResult.DeserializeV2AnalyzeResult(JsonElement element) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/Models/V2AnalyzeResult.Serialization.cs:line 85
>    at Azure.AI.FormRecognizer.Models.AnalyzeOperationResult.DeserializeAnalyzeOperationResult(JsonElement element) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/Models/AnalyzeOperationResult.Serialization.cs:line 46
>    at Azure.AI.FormRecognizer.FormRecognizerRestClient.GetAnalyzeFormResultAsync(Guid modelId, Guid resultId, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/FormRecognizerRestClient.cs:line 395
>    at Azure.AI.FormRecognizer.Models.RecognizeCustomFormsOperation.Azure.Core.IOperation<Azure.AI.FormRecognizer.Models.RecognizedFormCollection>.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient/RecognizeCustomFormsOperation.cs:line 187
>    at Azure.Core.OperationInternal`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 186
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 173
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 80
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 142
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 167
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 145
>    at Azure.AI.FormRecognizer.Models.RecognizeCustomFormsOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient/RecognizeCustomFormsOperation.cs:line 77
>    at Azure.AI.FormRecognizer.OperationExtensions.WaitForCompletionAsync(Task`1 operation, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/OperationExtensions.cs:line 66
>    at Azure.AI.FormRecognizer.Samples.FormRecognizerSamples.OutputModelsTrainedWithoutLabels() in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/samples/V3.1/Sample10_DifferentiateOutputModelsTrainedWithAndWithoutLabels.cs:line 97
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at Sy

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1312168&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1317623&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1314894&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1312168&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
The errors we were getting from `CopyModel` were actually transient 404s ([example here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1314894&view=logs&j=08af5c03-6468-51ed-963e-298c94b195d6&t=88296259-5329-5043-7ea9-783f2d6eb7f0&l=38)) that don't seem to be happening anymore. The error described in this issue comes from the v3.1 `Sample10_DifferentiateOutputModelsTrainedWithAndWithoutLabels` sample. This error is being tracked here: https://github.com/azure/azure-sdk-for-net/issues/28556, so closing this issue.
