### ISSUE TITLE
[Run .Net CI Script] Ref docs issue

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#26529]
Error:

> ##[error]mdoc: System.Exception: Error on 'D:\a\1\s\target_repo\xml\Azure.Core\ClassifiedResponse.xml': See InnerException for details. ---> System.ComponentModel.Win32Exception: The parameter is incorrect
>    --- End of inner exception stack trace ---
>    at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
>    at SchwabenCode.QuickIO.QuickIOFile.OpenFileStream(QuickIOPathInfo pathInfo, FileAccess fileAccess, FileMode fileOption, FileShare shareMode, Int32 buffer)
>    at Mono.Documentation.MDocUpdater.OpenWrite(String path, FileMode mode)
>    at Mono.Documentation.MDocUpdater.<>c__DisplayClass100_1.<CleanupFiles>b__1()
>    at Mono.Documentation.MDocUpdater.CleanupFiles(String dest, HashSet`1 goodfiles)
>    at Mono.Documentation.MDocUpdater.DoUpdateAssemblies(String source, String dest)
>    at Mono.Documentation.MDocUpdater.Run(IEnumerable`1 args)
>    at Mono.Documentation.MDoc.Main(String[] args)

For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=273202&view=results
- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=272936&view=results

@danieljurek for notification.

**Comment by danieljurek** [comment]
This was a regression on the docs side. Switching docs build to `feature/comet` branch mitigates the issue for now.
