### ISSUE TITLE
[TextAnalytics] AnalyzeOperationConvenienceAsync failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#26521]
TextAnalytics runs are failing with:

> Error message
> Azure.RequestFailedException : Requests to the Get analysis status and results Operation under Text Analytics API (v3.2-preview.2) have exceeded rate limit of your current TextAnalytics S pricing tier. Please retry after 1 second. Please contact Azure support service if you would like to further increase the default rate limit.
> Status: 429 (Too Many Requests)
> ErrorCode: 429
> 
> Content:
> {"error":{"code":"429","message": "Requests to the Get analysis status and results Operation under Text Analytics API (v3.2-preview.2) have exceeded rate limit of your current TextAnalytics S pricing tier. Please retry after 1 second. Please contact Azure support service if you would like to further increase the default rate limit."}}
> 
> Headers:
> Retry-After: 1
> apim-request-id: f30f8d12-f2a6-4b18-a1c5-ae1ae7a7796c
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> policy-id: REDACTED
> Date: Thu, 20 Jan 2022 02:54:31 GMT
> Content-Length: 336
> Content-Type: application/json
> 
> 
> Stack trace
>    at Azure.AI.TextAnalytics.TextAnalyticsRestClient.AnalyzeStatusAsync(String jobId, Nullable`1 showStats, Nullable`1 top, Nullable`1 skip, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Generated\TextAnalyticsRestClient.cs:line 151
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.Azure.Core.IOperation<Azure.AsyncPageable<Azure.AI.TextAnalytics.AnalyzeActionsResult>>.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\AnalyzeActionsOperation.cs:line 313
>    at Azure.Core.OperationInternal`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 186
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 173
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 80
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 142
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 167
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 145
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\AnalyzeActionsOperation.cs:line 229
>    at Azure.AI.TextAnalytics.Samples.TextAnalyticsSamples.AnalyzeOperationConvenienceAsync() in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\tests\samples\Sample_AnalyzeOperationConvenienceAsync.cs:line 48
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1314633&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Fixed by https://github.com/Azure/azure-sdk-for-net/pull/26418.
