### ISSUE TITLE
How I can manage count of Outbound connections in azure function? [QUERY]

### ISSUE THREAD

**Issue by tkachuk2222** [Azure/azure-sdk-for-net#26532]
### Library name and version

Microsoft.Azure.ServiceBus 5.1.3 Azure.Messaging.ServiceBus 7.2.1

### Query/Question

I have an azure function service bus trigger. With some periodicity, I have a lot of incoming messages into the service bus queue. Azure Function triggers by each new message. And because of a lot of messages I have troubles with Outbound connections -> other azure functions (f.e. time trigger) that want to create a new connection can't do it and they fail with a message "An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full"
 
How can I fix the problem with connections?

![image](https://user-images.githubusercontent.com/20381930/150533141-c1d0397e-0411-42ab-a890-cb6c0cabaa26.png)

### Environment

OS Windows
Azure Functions
.net 6.0.100 (but pushed version is .net 5.0)

Microsoft.Azure.ServiceBus 5.1.3 
Azure.Messaging.ServiceBus 7.2.1
Microsoft.Azure.Functions.Worker.Sdk 1.0.4
Microsoft.Azure.Functions.Worker.Extensions.ServiceBus 4.2.1
Azure.Security.KeyVault.Keys 4.2.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Can you clarify how you are using the Service Bus SDK here. It looks like you are referencing two different SB libraries:
Microsoft.Azure.ServiceBus 5.1.3
Azure.Messaging.ServiceBus 7.2.1

The worker extension you are using corresponds to the Microsoft.Azure.ServiceBus library.
