### ISSUE TITLE
Possibility to extend the IQueueProcessorFactory 

### ISSUE THREAD

**Issue by plamber** [Azure/azure-sdk-for-net#26530]
### Library name

Microsoft.Azure.WebJobs.Extensions.Storage.Queues

### Please describe the feature.

Based on the original conversation in this [repository](https://github.com/Azure/azure-webjobs-sdk/issues/2810#issue-1082890667)

Hi there!
I recently upgraded from Azure Functions v3 to Azure Functions v4. During this upgrade, I had to update Microsoft.Azure.WebJobs.Extensions.Storage.Queues assembly to Version 5.0.0.0.

In the previous version, it was possible to implement the interface IQueueProcessorFactory and modify in code the processor options (MaxPolilingInterval, MaxDequeueCount, VisibiltyTimeout). This allowed us to apply different values for each queue based on our business requirements. 

With the latest version of the assembly, the QueueProcessor class became a protected internal class, making it impossible to return a new instance of this object. 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/18241305/146490891-f43d882b-a633-4eac-acd3-f4946953de2a.png">

I haven't seen a way to configure individual values for each queue. Maybe there is a more elegant way to do this.

#### Expected behavior
Allow creating an instance of the QueueProcessor class in other assemblies. Make the constructor public.

#### Actual behavior
It is not possible to instantiate a dedicated instance of QueueProcessor

#### Known workarounds
Not aware of other workarounds. As far as I know, it is only possible to specify a central set of settings for all queues in the host.json.

Thank you for your feedback.

**Comment by SaurabhSharma-MSFT** [comment]
@plamber We are looking this and get back to you for any questions.

**Comment by SatishBoddu-MSFT** [comment]
Hello @plamber Thanks for submitting this feature request as per the previous conversation on [Link](https://github.com/Azure/azure-webjobs-sdk/issues/2810#issuecomment-1018356532)

We are routing this to the Service team to further review.

**Comment by KayMKM** [comment]
Hi @SatishBoddu-MSFT my team met the same issue, any updates about it?

**Comment by wouter-b** [comment]
I'm facing the same difficulties, any updates on the issue?

**Comment by superjulius** [comment]
Would be great to get a status indeed. We are stuck to 4.x and cannot upgrade our WebJobs to 5.x without losing the ability to configure queue options per queue. This is very useful for instance to configure different BatchSize / MaxDequeueCount.

Else it would mean having one webjob per queue, which would be overkill

**Comment by zzzachzzz** [comment]
Are you kidding me? I just upgraded to Azure Functions v4

**Comment by wouter-b** [comment]
We solved this issue with a custom queue processor factory:

inherrit from the existing QueueProcessor
````csharp
public class QueueProcessorWrapper : QueueProcessor
{
    public QueueProcessorWrapper(QueueProcessorOptions queueProcessorOptions) : base(queueProcessorOptions)
    {
    }
}
````

```csharp
internal class CustomQueueProcessorFactory : IQueueProcessorFactory
{
    private readonly string _fiberFitMeasurementTaskQueueName;
    public CustomQueueProcessorFactory(IConfiguration configuration)
    {
        _fiberFitMeasurementTaskQueueName = configuration.GetValue<string>("Queues:FiberFitMeasurementTask");
    }
    public QueueProcessor Create(QueueProcessorOptions queueProcessorOptions)
    {
        if (queueProcessorOptions.Queue.Name.Equals(_fiberFitMeasurementTaskQueueName, StringComparison.OrdinalIgnoreCase))
            queueProcessorOptions.Options.BatchSize = 1;

        return new QueueProcessorWrapper(queueProcessorOptions);
    }
}
```

And register it in the DI container
```csharp
builder.Services.AddSingleton<IQueueProcessorFactory, CustomQueueProcessorFactory>();
```

**Comment by superjulius** [comment]
Thanks @wouter-b for sharing! We were already using a factory IQueueProcessorFactory but the issue was that the QueueProcessor class was internal protected. So the trick seems to simply create a wrapper around it. 

Feeling ashamed if this is that simple :-)

```
public class QueueProcessorWrapper : QueueProcessor
{
    public QueueProcessorWrapper(QueueProcessorOptions queueProcessorOptions) : base(queueProcessorOptions)
    {
    }
}
```

**Comment by plamber** [comment]
This @wouter-b,
thank you. I haven't thought about it. I am going to use this workaround.

I am going to close the issue.

Cheers
