### ISSUE TITLE
[FEATURE REQ] Merge RawRequestUriBuilder into RequestUriBuilder

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#26534]
### Library name

Azure.Core

### Please describe the feature.

The RawRequestUriBuilder shared code hasn't changed for a long time and the feature it brings is pretty uncontroversial.

**Comment by annelo-msft** [comment]
Closing as duplicate of https://github.com/Azure/azure-sdk-for-net/issues/32006
