### ISSUE TITLE
The permissions parameter description is wrong.

### ISSUE THREAD

**Issue by jimt4593** [Azure/azure-sdk-for-net#26543]
[Enter feedback here]
The permissions parameter description incorrectly duplicates the expiresOn parameter description.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30d49f9c-4722-9d8e-0cbc-9f7dd7f7a7d2
* Version Independent ID: 4a433799-1586-9819-9496-9de9d23001db
* Content: [QueueSasBuilder Constructor (Azure.Storage.Sas) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.sas.queuesasbuilder.-ctor?view=azure-dotnet#azure-storage-sas-queuesasbuilder-ctor(azure-storage-sas-queueaccountsaspermissions-system-datetimeoffset))
* Content Source: [xml/Azure.Storage.Sas/QueueSasBuilder.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Sas/QueueSasBuilder.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@jimt4593 Thanks for reporting this issue. I have created a [PR](https://github.com/Azure/azure-docs-sdk-dotnet/pull/2118) for the same and updated content owners to look into this. We will keep you posted about the progress.

**Comment by navba-MSFT** [comment]
PR #26571

**Comment by navba-MSFT** [comment]
@jimt4593 The PR #26571 has been approved and merged with the main branch. So [this](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.sas.queuesasbuilder.-ctor?view=azure-dotnet#azure-storage-sas-queuesasbuilder-ctor(azure-storage-sas-queueaccountsaspermissions-system-datetimeoffset) docs should be updated automatically when we have a new .NET SDK release. So we will now proceed with the closure of this github issue.

If you have any questions on this, please feel free to reopen this issue. We would be happy to address your questions.
