### ISSUE TITLE
Incorrect description for the permissions parameter.

### ISSUE THREAD

**Issue by jimt4593** [Azure/azure-sdk-for-net#26542]
[Enter feedback here]
The permissions parameter description incorrectly repeats the description of the expiresOn parameter. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af699d50-6ad8-f434-c93b-86e350520d7c
* Version Independent ID: 030b007d-8a0f-70f3-0d65-144e06eee25a
* Content: [BlobSasBuilder Constructor (Azure.Storage.Sas) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.sas.blobsasbuilder.-ctor?view=azure-dotnet#azure-storage-sas-blobsasbuilder-ctor(azure-storage-sas-blobcontainersaspermissions-system-datetimeoffset))
* Content Source: [xml/Azure.Storage.Sas/BlobSasBuilder.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Sas/BlobSasBuilder.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@jimt4593 Thanks for reporting this issue. I have created a [PR](https://github.com/Azure/azure-docs-sdk-dotnet/pull/2119) for the same and updated content owners to look into this. We will keep you posted about the progress.

**Comment by navba-MSFT** [comment]
@jimt4593 The PR #26570 has been approved and merged with the main branch. So [this](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.sas.blobsasbuilder.-ctor?view=azure-dotnet#azure-storage-sas-blobsasbuilder-ctor(azure-storage-sas-blobcontainersaspermissions-system-datetimeoffset) docs should be updated automatically when we have a new .NET SDK release. So we will now proceed with the closure of this github issue.

If you have any questions on this, please feel free to reopen this issue. We would be happy to address your questions.
