### ISSUE TITLE
[QUERY] add ip to SQL Server firewall 

### ISSUE THREAD

**Issue by unruledboy** [Azure/azure-sdk-for-net#26555]
### Library name and version

Microsoft.Azure.Management.Network.Fluent 1.38 

### Query/Question

Hi,

I noticed the documentation of Microsoft.Azure.Management.Network.Fluent (https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.network.fluent.iazurefirewallsoperations?view=azure-dotnet) has mentioned ip firewall rule, but it does not tell us exactly how to use it to add a server IP rule to the SQL Server. 

Then I thought it should be related to Microsoft.Azure.Management.Sql.Fluent.SqlFirewallRule.Update, but I could not find related document to it.

I could not find any related doc about this after repeated googling.

Can you please advise?

Thanks.

### Environment

Hosting platform or OS and .NET runtime version: Windows 10, .NET Core 3.1
IDE and version: Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by unruledboy** [comment]
Turned out we can use SqlManagementClient.FirewallRules.CreateOrUpdate to achieve it.

Thanks.
