### ISSUE TITLE
Default value of ServiceBusProcessor.PrefetchCount?

### ISSUE THREAD

**Issue by amit-batra** [Azure/azure-sdk-for-net#26557]
[Enter feedback here]
Can you specify the **default value** of this property?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 67eef76a-11a2-81c8-b598-492e195b2839
* Version Independent ID: 6279f681-15a5-d1fc-1374-39c9644c54a0
* Content: [ServiceBusProcessor.PrefetchCount Property (Azure.Messaging.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusprocessor.prefetchcount?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.ServiceBus/ServiceBusProcessor.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus/ServiceBusProcessor.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @amit-batra.   Thank you for reaching out and we regret that you're experiencing difficulties.   The prefetch count defaults to 0.   Setting the value is done using the `ServiceBusProcessorOptions`, and its default value is documented as part of the [ServiceBusProcessorOptions.PrefetchCount](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusprocessor.prefetchcount?view=azure-dotnet) member.   

I can see how that may not be clear when looking at the processor member; I've opened #26563 to improve that.
