### ISSUE TITLE
[BUG] Singleton queue processing

### ISSUE THREAD

**Issue by HugoMatte** [Azure/azure-sdk-for-net#26551]
### Library name and version

Microsoft.Azure.Webjobs.Extensions.Storage 5.0.0

### Describe the bug

I wish to run Blob Trigger Function to run one after another (not in parallel). I edit the host.json file to set "batchSize": 1. Work correclty in Microsoft.Azure.Webjobs.Extensions.Storage 4.0.5 but not on 5.0.0.  I also tried to add NewBatchThreshold=0 and I observe no differences.

See an old discussion on similar topic, gives some background: https://github.com/Azure/azure-webjobs-sdk/issues/1568

I will revert back to 4.0.5. for now.

### Expected behavior

Successfull Singleton Queue processing

### Actual behavior

Run in parralel

### Reproduction Steps

{
  "version": "2.0",
  "extensions": {
    "queues": {
      "batchSize": 1
    }
  },
  "logging": {
    "applicationInsights": {
      "samplingSettings": {
        "isEnabled": true,
        "excludedTypes": "Request"
      }
    }
  }
}

### Environment

I did my tests usting .Net 6.0 and the azurite emulator. I have not tried to experience the behavior on azure directly.

Visual studio 17.1.0 Preview 1.0

**Comment by MughundhanRaveendran-MSFT** [comment]
@HugoMatte , Thanks for reporting this issue. I will look into this issue and get back to you. In the meantime, could you please try deploying the function to Azure Functions runtime directly and see if the issue is seen there as well?

**Comment by MughundhanRaveendran-MSFT** [comment]
@HugoMatte , I am able to reproduce this issue at my end as well. I will check this internally and let you know

**Comment by navba-MSFT** [comment]
@ahmedelnably, @fabiocav Could you please provide an update on this once you get a chance ?

**Comment by nakah** [comment]
Any update on this issue ? It’s really impacting for my application where I call a downstream API for each message in the queue. 
Each Function App instance is getting 16 messages every time without taking into account batchSize property in host.json 
This generates huge load on target API server which cannot handle the load.
I’m also using the latest sdk available on NuGet.

**Comment by navba-MSFT** [comment]
@HugoMatt @ahmedelnably, @fabiocav Could you please look into this issue on priority ? Thanks in advance.

**Comment by nakah** [comment]
Quick update, it seams that I was using host.json file incorrectly. 
"queues" settings were at the root of host.json instead being nested inside "extensions" node.
Now it's working as expected :)
