### ISSUE TITLE
[QUERY] Register an original ServiceBusReceiver to a DI Container for a ServiceBus-triggered WebJob

### ISSUE THREAD

**Issue by PhilipLipnitskiNipo** [Azure/azure-sdk-for-net#26565]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.2.0.0

### Query/Question

I have a WebJob with a ServiceBusTrigger.

In Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.*.*.* package it was possible to get a `MessagingProvider` and retrieve an original `MessageReceiver` which received a message to register it to DI Container.
``` c#
var messagingProvider = services.GetService<MessagingProvider>();
application.Container.Register(() => messagingProvider.CreateMessageReceiver(configuration[ServiceBusQueueName], configuration[ServiceBusConnectionString]));
```

With a package update `MessagingProvider` methods became protected internal, so the code above is not working anymore.

Is it possible in the latest version of the package to get an original `ServiceBusReceiver` that received a message to register it to DI Container?

### Environment

Azure AppService (WebJob)
.NET SDK 6.0.101

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @PhilipLipnitskiNipo,
Can you tell us a bit more about what you need the receiver for? Also, as a workaround, you could subclass the MessagingProvider and thereby have access to the receiver.
