### ISSUE TITLE
[BUG] generate.ps1 is behaving unexpectedly

### ISSUE THREAD

**Issue by arpja** [Azure/azure-sdk-for-net#26562]
### Library name and version

https://www.nuget.org/packages/Microsoft.Azure.Management.RecoveryServices.Backup/4.3.0-preview

### Describe the bug

We are seeing unexpcted behavior from the generate.ps1 in our recoveryservice.backup repo.
For multi-api packages the generate.ps1 is generating same clients for both packages which is leads to an compilation failure.

![image](https://user-images.githubusercontent.com/46751982/150794223-9c389788-1396-4827-893f-714b28f0f479.png)

### Expected behavior

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/recoveryservices-backup/Microsoft.Azure.Management.RecoveryServices.Backup/src/recoveryservicesbackup/Generated/SdkInfo_RecoveryServicesBackupClient.cs

### Actual behavior

![image](https://user-images.githubusercontent.com/46751982/150794514-58451562-de25-4fa2-80eb-c62ef9bd4489.png)

Generated client version if wrong.

### Reproduction Steps

Fork the azure sdk for net repo and run the script
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/recoveryservices-backup/Microsoft.Azure.Management.RecoveryServices.Backup/src/generate.ps1

### Environment

N/A

**Comment by arpja** [comment]
tagging @pratimaupadhyay02 for FYI

**Comment by pratimaupadhyay02** [comment]
Hi @ArthurMa1978 can you please help with the issue

**Comment by arpja** [comment]
Turns out this was due to a typo in the path that we added for our passive stamp package.
Correcting the name help resolve the issue, closing this bug.
