### ISSUE TITLE
[QUERY] Support API Management Services (APIM)

### ISSUE THREAD

**Issue by unruledboy** [Azure/azure-sdk-for-net#26589]
### Library name and version

Microsoft.Azure.Management.Fluent 1.0.0.70

### Query/Question

I could not find the support of API Management Services. Currently I need to use `IAzure.GenericResources` to workaroud it, just to obtain the generic object. But it would be great if we have native support of the Azure API Management services.

### Environment

Hosting platform or OS and .NET runtime version: Windows 10, .NET Core 3.1
IDE and version : Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by unruledboy** [comment]
Currently I need to use `IAzure.GenericResources` to workaroud it, just to obtain the generic object. But it would be great if we have native support of the Azure API Management services.

**Comment by ArthurMa1978** [comment]
Thank you for reaching us, @HarveyLink  please help on this issue.

**Comment by HarveyLink** [comment]
Hi @unruledboy , there is no Flunt SDK support for APIManagement.
However, we do have a APIManagement SDK, just not in flunt way : https://www.nuget.org/packages/Microsoft.Azure.Management.ApiManagement/8.0.0-preview
If possible, you could use it as the replacement. 
Feel free to reach us if you have any questions.

**Comment by unruledboy** [comment]
Thanks Harvey!
