### ISSUE TITLE
[QUERY] bad request while creating Active Directory application

### ISSUE THREAD

**Issue by unruledboy** [Azure/azure-sdk-for-net#26586]
### Library name and version

Microsoft.Azure.Management.Fluent 1.0.0.70

### Query/Question

We try to create an Azure AD app registration with the sample code in https://stackoverflow.com/questions/45392618/how-can-i-create-an-azure-ad-application-using-the-fluent-api   with some minor change due to API changes:

```
var url = "http://adfei.onmicrosoft.com/appFluent";
    var id = "abc";
    var secret = "secret";
    var applicationName = "appFluent";
    var credFile = new AzureCredentials(new UserLoginInformation
    {
        ClientId = "{appId of native application}",
        UserName = "{userName}",
        Password = "{password}"
    },
        "adfei.onmicrosoft.com", AzureEnvironment.AzureGlobalCloud);
    IAzure azure = Azure.Authenticate(credFile).WithDefaultSubscription();
    var application = azure.AccessManagement.ActiveDirectoryApplications.Define(applicationName)
    .WithSignOnUrl(url)
    .WithIdentifierUrl(url)
    .WithAvailableToOtherTenants(false)
    .DefinePasswordCredential(id)
      .WithPasswordValue(secret)
      .Attach()
    .Create();
```

It gave the following error:

> Microsoft.Azure.Management.Graph.RBAC.Fluent.Models.GraphErrorException: 'Operation returned an invalid status code 'BadRequest''

I tried quite a few other combinations, like removing "WithIdentifierUrl", or changing the secret value etc. Still the same issue. The app running the logic has Application Administrator role already.

I even tried to simplify it:

```
var url = "http://adfei.onmicrosoft.com/appFluent";
    var id = "abc";
    var applicationName = "appFluent";
    var credFile = new AzureCredentials(new UserLoginInformation
    {
        ClientId = "{appId of native application}",
        UserName = "{userName}",
        Password = "{password}"
    },
        "adfei.onmicrosoft.com", AzureEnvironment.AzureGlobalCloud);
    IAzure azure = Azure.Authenticate(credFile).WithDefaultSubscription();
    var application = azure.AccessManagement.ActiveDirectoryApplications.Define(applicationName)
    .WithSignOnUrl(url)
    .Create();
```

Still does not work, with the same error.

Do we have a way to find out why exactly it failed (as in the details of "bad request")?

### Environment

Hosting platform or OS and .NET runtime version: Windows 10, .NET Core 3.1
IDE and version : Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by unruledboy** [comment]
any update on this please?

**Comment by unruledboy** [comment]
Finally figured it out how to create one based on https://stackoverflow.com/questions/54825934/how-to-read-domain-of-azure-active-directory

```
                string defaultDomain = "foo.com";
                string identiferUri = string.Format("https://{0}/myuniqueapp1", defaultDomain);
                var app = azure.AccessManagement.ActiveDirectoryApplications
                    .Define(appName)
                    .WithSignOnUrl("http://localhost")
                    .WithAvailableToOtherTenants(false)
                    .WithIdentifierUrl(identiferUri)
                    .DefinePasswordCredential(CredentialKey)
                    .WithPasswordValue(clientSecret)
                    .WithDuration(TimeSpan.FromDays(100))
                    .Attach()
                    .Create();
```

There are two mandatory things:

- WithAvailableToOtherTenants, whether true or false
- WithIdentifierUrl, which is not ideal, as we don't want to use a domain in this case. If we create one in Azure portal, it does not require it, and when we expose an API, it would just be:

> api://THE-APPLICATION-ID-HERE/YourScope
