### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cstfr** [Azure/azure-sdk-for-net#26596]
### Library name and version

Cognitive - Form Recognizer V2 and V3

### Describe the bug

This happens with the preview version as well as the stable version.
Last line  with one cell in a table is missing

### Expected behavior

The last row of the table contains only one cell. nevertheless it should belong to the table detected by FormReconizer.

### Actual behavior

Last line  with one cell in a table is missing

### Reproduction Steps

File to submit to Form Recognizer Studio

[Table2.pdf](https://github.com/Azure/azure-sdk-for-net/files/7936098/Table2.pdf)

### Environment

Using Form Recognizer Studio, Layout or General document.

**Comment by jsquire** [comment]
Hi @cstfr.  Thank you for reaching out and we regret that you're experiencing difficulties.   Unfortunately, this repository is only able to assist with packages for the Azure SDK for .NET.   Form Recognizer Studio is not something that we have insight into.   I'd recommend opening an [Azure Support Ticket](https://docs.microsoft.com/azure/active-directory/fundamentals/active-directory-troubleshooting-support-howto) which would be the best path for assistance.

I'm going to close this out, but please feel free to unresolve if I've misunderstood what help you're seeking.
