### ISSUE TITLE
Need an example for how to implement this

### ISSUE THREAD

**Issue by norton287** [Azure/azure-sdk-for-net#26602]
[Enter feedback here]

Is there an example of using this somewhere?  Or can one be provided?

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 918d059f-8e92-166e-e98d-f89a097c67f8
* Version Independent ID: 2a956f03-1dbe-086a-9b07-0ae1217c50fb
* Content: [BlobContainersOperationsExtensions.SetLegalHold(IBlobContainersOperations, String, String, String, IList&lt;String&gt;, Nullable&lt;Boolean&gt;) Method (Microsoft.Azure.Management.Storage) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.blobcontainersoperationsextensions.setlegalhold?view=azure-dotnet-preview#microsoft-azure-management-storage-blobcontainersoperationsextensions-setlegalhold(microsoft-azure-management-storage-iblobcontainersoperations-system-string-system-string-system-string-system-collections-generic-ilist((system-string))-system-nullable((system-boolean))))
* Content Source: [xml/Microsoft.Azure.Management.Storage/BlobContainersOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Storage/BlobContainersOperationsExtensions.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amishra-dev** [comment]
@vinjiang / @blueww can you please look into this ask.

**Comment by blueww** [comment]
@norton287 
Do you want to know how to set legalhold on blob container?
Please refer the sample test case: https://github.com/Azure/azure-sdk-for-net/blob/4728a100239be4ac61f990dda90ee76ec88e69cb/sdk/storage/Microsoft.Azure.Management.Storage/tests/Tests/BlobServiceTests.cs#L327

**Comment by norton287** [comment]
The storage management client signature is different when looked at by intelligence from what is in the test. The test signature for the storage management client is invalid when I try it. Also, looking at the current documentation for Azure.Storage.Management shows a different signature for it as well.  

John


From: Wei Wei ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: January 27, 2022 at 10:00:23 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Need an example for how to implement this (Issue #26602)

**Comment by blueww** [comment]
@norton287 
If you have not used storage management plane SDK before, you can start with 
https://azure.microsoft.com/da-dk/resources/samples/storage-dotnet-resource-provider-getting-started/

**Comment by norton287** [comment]
I have it configured in my solution and it tries to work but it says I do not have permissions to the storage. How do I assign permission to my app to allow actions on my storage account?  

John


From: Wei Wei ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: February 6, 2022 at 10:23:41 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Need an example for how to implement this (Issue #26602)

**Comment by blueww** [comment]
@norton287 
You need to assign an azure role to your service principle, see details in https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage
Like for owner role, it has full permission for the subscription.

**Comment by norton287** [comment]
The example code authenticates as an AD Application, how would I authenticate to the storagemanagementclient as my user account?

John


From: Wei Wei ***@***.***>
Reply: Azure/azure-sdk-for-net ***@***.***>
Date: February 8, 2022 at 9:53:23 PM
To: Azure/azure-sdk-for-net ***@***.***>
Cc: John Norton ***@***.***>, Mention ***@***.***>
Subject:  Re: [Azure/azure-sdk-for-net] Need an example for how to implement this (Issue #26602)  

@norton287
You need to assign an azure role to your service principle, see details in https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage
Like for owner role, it has full permission for the subscription.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.  
You are receiving this because you were mentioned.

[ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "https://github.com/Azure/azure-sdk-for-net/issues/26602#issuecomment-1033316559", "url": "https://github.com/Azure/azure-sdk-for-net/issues/26602#issuecomment-1033316559", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by norton287** [comment]
That works perfectly!  

Could it be possible to update the solution to the latest nugets at some point?


From: Wei Wei ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: February 8, 2022 at 9:53:12 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Need an example for how to implement this (Issue #26602)

**Comment by blueww** [comment]
@norton287 
Thanks for the confirmation!
Could you please clarify what do you mean by "update the solution to the latest nugets"?

**Comment by norton287** [comment]
Most of the SDK packages are out of date in respect to what is currently available.


From: Wei Wei ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: February 9, 2022 at 11:26:23 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Need an example for how to implement this (Issue #26602)

**Comment by blueww** [comment]
@norton287 
Would you please give details for "Most of the SDK packages are out of date in respect to what is currently available."?
What do you mean by "our of date"?
And what 's the update you would like to add ?

**Comment by norton287** [comment]
Here is the package listing for the sample with all the different SDKs in use and the Nuget Package Versions:

 


 


 

<packages>

	
  <package id="Microsoft.Azure.Management.Storage" version="14.2.0" targetFramework="net48" />

	
  <package id="Microsoft.Azure.ResourceManager" version="1.0.0-preview" targetFramework="net45" />

	
  <package id="Microsoft.IdentityModel.Clients.ActiveDirectory" version="5.2.4" targetFramework="net48" />

	
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.21" targetFramework="net48" />

	
  <package id="Microsoft.Rest.ClientRuntime.Azure" version="3.3.19" targetFramework="net48" />

	
  <package id="Newtonsoft.Json" version="12.0.3" targetFramework="net48" />

	
  <package id="System.IO" version="4.3.0" targetFramework="net48" />

	
  <package id="System.Net.Http" version="4.3.4" targetFramework="net48" />

	
  <package id="System.Runtime" version="4.3.1" targetFramework="net48" />

	
  <package id="System.Security.Cryptography.Algorithms" version="4.3.1" targetFramework="net48" />

	
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net48" />

	
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net48" />

	
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.2" targetFramework="net48" />

	
</packages>

 

The current version of Microsoft.Azure.Management.Storage is 23.1.0.

The current version of Microsoft.IdentityModel.Clients.ActiveDirectory is 5.2.9

The current version of Microsoft.Rest.ClientRuntime is 2.3.23.

 

These are the ones that are out of date, especially Microsoft.Azure.Management.Storage by a great deal!  There have been many releases since the sample was done.

 

John

**Comment by blueww** [comment]
@norton287

So I get what you mean is to update the sample in the doc: https://azure.microsoft.com/da-dk/resources/samples/storage-dotnet-resource-provider-getting-started/

@tamram
Would you please help to look at the doc update request?

**Comment by norton287** [comment]
@blueww Could this possibly utilize Authentication methods that work on Mobile Platforms?  My app is a cross-platform mobile app and the newer Azure.Identity methods of authentication do not work on mobile platforms at all.  Not sure why they coded them that way but it is sad.

If it is possible an authentication method that utilizes a service principle would be great!

John

**Comment by blueww** [comment]
@norton287 
For Mobile Platforms, this looks a new request, would you please open a new issue for this?
Besides that, the authentication way is aligned for all .net SDK, not only for Storage. So the new issue should not be a storage only issue.

**Comment by norton287** [comment]
@blueww Done

**Comment by blueww** [comment]
@norton287 
I see you open an issue to following up both doc update and mobile. 
This might need be follow up by different teams.
Please use one issue to follow one item. 
So the issue https://github.com/Azure/azure-sdk-for-net/issues/27155 is mainly for doc update, would you please update it only for doc, then open a new issue for mobile?

**Comment by blueww** [comment]
@norton287 
I will close this issue, as the original issue (example for set legalhold) is already resolved.
For doc update, I see https://github.com/Azure/azure-sdk-for-net/issues/27155 is already fixed.
For the Mobile Platforms, I see https://github.com/Azure/azure-sdk-for-net/issues/27156 is opened.

Feel free to contact us is need any further support on .net SDK.

**Comment by norton287** [comment]
The only issue I have found after updating my local packages was the following statement in the sample was obsolete.  

var result = await context.AcquireTokenAsync(“https://managment.azure.com/“,, cc).ConfigureAwait(false);  

I had to use the [Obsolete] attribute to work around it.  

I’m still processing the updates but that’s it so far.  

John


From: Tamra Myers ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: February 24, 2022 at 8:25:46 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Need an example for how to implement this (Issue #26602)

**Comment by blueww** [comment]
@norton287 
To avoid confuse, it's better to use the doc issue https://github.com/Azure/azure-sdk-for-net/issues/27155 to follow up the doc problem.

**Comment by norton287** [comment]
Cannot that issue is closed now.


From: Wei Wei ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: February 24, 2022 at 9:11:59 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Need an example for how to implement this (Issue #26602)

**Comment by blueww** [comment]
@tamram , @ norton287

Just a kind remind.
Please use the doc issue https://github.com/Azure/azure-sdk-for-net/issues/27155 to track the doc package update, for a better tracking.

**Comment by norton287** [comment]
reopen it so I can move the comment then please @bluww


From: Wei Wei ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: February 24, 2022 at 9:14:54 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Need an example for how to implement this (Issue #26602)

**Comment by blueww** [comment]
@norton287 
This is also closed. 
If you think that issue should be reopen, you can reopen it.

**Comment by norton287** [comment]
ok


From: Wei Wei ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: February 24, 2022 at 9:17:37 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Need an example for how to implement this (Issue #26602)

**Comment by tamram** [comment]
@norton287 - you can continue to post on a closed issue. we will still get the notifications.
