### ISSUE TITLE
[QUERY] Do Storage.Blobs clients auto refresh ClientCertificateCredential token on expiry?

### ISSUE THREAD

**Issue by Hossam-Hazem** [Azure/azure-sdk-for-net#26616]
### Library name and version

Azure.Storage.Blobs 12.10.0, Azure.Data.Tables 12.3.0

### Query/Question

I didn't find this info mentioned explicitly any where in the docs so I wanted to double check if we need to handle the token renewer and refresh mechanism ourselves like in SDK V11 or is it provided by default by the storage SDKs?

**Comment by SaurabhSharma-MSFT** [comment]
@Hossam-Hazem When you say refresh ClientCertificateCredential, do you mean to get token while certificates are getting rotated during process execution? If that's the case, then certification rotation is not supported, and you need to implement your own logic to get the refreshed certificate.  Please refer to [documentation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientCertificateCredentialSamples.md#implicit-rotation). 

Thanks
Saurabh

**Comment by Hossam-Hazem** [comment]
@SaurabhSharma-MSFT I mean refresh on token expiry the certificates are not getting rotated in this scenario.

**Comment by SaurabhSharma-MSFT** [comment]
@Hossam-Hazem Ok, I will check on this and get back to you. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@xgithubtriage As per internal discussion @Hossam-Hazem wants to know if ClientCertificateCredential created a new token that expires in 2 hours. In that case, will the storage SDK generate a new token after 2 hours when the first token expires?

**Comment by amishra-dev** [comment]
@Hossam-Hazem tokens are refreshed automatically if you use any of the TokenCredential classes, the Azure.Core package should take care of refresh. In this case you need https://docs.microsoft.com/en-us/dotnet/api/azure.identity.clientcertificatecredential?view=azure-dotnet
