### ISSUE TITLE
[FormRecognizer] Migrate to test-proxy

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#26612]
We needed to revert part of the changes introduced in https://github.com/Azure/azure-sdk-for-net/pull/25879 because tests using the `DisableRequestBodyRecording` scope would fail in Record mode (even though they work just fine when running Live).

Now we need to understand what exactly is causing the problem, fix it, and remove the `useLegacyTransport: true` argument we pass in the `DocumentAnalysisLiveTestBase` and `FormRecognizerLiveTestBase` constructors.

Note: the constructor changes mentioned above have only been applied in the `feature/formrecognizer/v400b3` feature branch of the private repo for now. It will eventually be merged into the public repo.

Related discussion (private repo): https://github.com/Azure/azure-sdk-for-net-pr/pull/1562/files#r792266132

**Comment by JoshLove-msft** [comment]
I can re-migrate once https://github.com/Azure/azure-sdk-tools/issues/2434 is addressed in Test Proxy.
