### ISSUE TITLE
[FEATURE REQ] Restore metadata in track 2 PartitionData Class

### ISSUE THREAD

**Issue by alexkarcher-msft** [Azure/azure-sdk-for-net#26629]
### Library name

Azure.Messaging.EventHubs.Consumer

### Please describe the feature.

In the track 2 version of the PartitionData class there is no longer any of the metadata present in the track 1 version of that same class. Specifically, we are in need of access to the event hub path, which has been removed.

[Track 1 Partition Data](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.eventhubs.processor.partitioncontext?view=azure-dotnet)
[Track 2 Partition Data](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.consumer.partitioncontext?view=azure-dotnet)

I work on Logic apps, built on top of Azure Functions, and the functions runtime handles all event hub message receiving. They only pass back to us the received EventData objects and the PartitionContext object. This used to be sufficient, but now is lacking that necessary event hub path metadata that we use to look up the correct connection string, since each app can be receiving events from multiple hubs.

[Data available for binding in Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=csharp#event-metadata)

Thanks!

**Comment by jsquire** [comment]
Thanks, @alexkarcher-msft, for opening this request; I'll use it to drive internal discussion and follow-up when more information is available.

**Comment by jsquire** [comment]
For some reason, the .NET implementation was missing some metadata present in our other languages, including the name of the Event Hub.   I've added these in #26737 which should be included in our next release.

**Comment by alexkarcher-msft** [comment]
Woo! Thanks a ton Jesse!
