### ISSUE TITLE
No support for Virtual Directories in SDK despite JSON receiving them

### ISSUE THREAD

**Issue by josemaia** [Azure/azure-sdk-for-net#2662]
http://stackoverflow.com/questions/29000178/using-the-azure-api-how-do-i-list-and-add-virtual-directories-to-a-website

This StackOverflow issue has an example where the user manually compiled the code to expose the VirtualDirectories object so he could create the application he needed. It should not be necessary to do so. See issue https://github.com/Azure/azure-sdk-for-net/issues/2063 for another example of the same problem.

EDIT: Tested in Microsoft.WindowsAzure.Management.WebSites/4.0.0

**Comment by adrianhall** [comment]
Is this still an issue in Azure App Service?  (I don't think app service supports virtual directories, so I don't think so)

**Comment by josemaia** [comment]
> Is this still an issue in Azure App Service? (I don't think app service supports virtual directories, so I don't think so)

I haven't worked with app service in a while, so I will not be able to check. Presumably it can be closed.
