### ISSUE TITLE
Examples section is not formatted or valid.

### ISSUE THREAD

**Issue by ShriGrover** [Azure/azure-sdk-for-net#26634]
![image](https://user-images.githubusercontent.com/25351278/151270533-a7d89109-6b6a-493c-ab49-fb8a075a360e.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f818233-3780-fec6-3d5b-e0f69d35bf6f
* Version Independent ID: 1c3c2e48-d050-05a9-c7a1-8f3292f9c62a
* Content: [UniqueKeyPolicy Class (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.uniquekeypolicy?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/UniqueKeyPolicy.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/UniqueKeyPolicy.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@ShriGrover Thanks for the feedback! We will work to fix this.

**Comment by PramodValavala-MSFT** [comment]
@ShriGrover Turned out this was coming from older source code of the same class. This has since been removed. Closing.
