### ISSUE TITLE
Microsoft Avro library getting deprecated?

### ISSUE THREAD

**Issue by javierholguera** [Azure/azure-sdk-for-net#2663]
It looks like all code for Azure Service Management is getting deprecated in in favour of Azure Resource Management alternatives.

However, I haven't found any for the Avro library inside ASM group. Any plans to have something like that in ARM? What would be the state for Avro support in that case?

Thanks!

**Comment by chuanboz** [comment]
quote from [Serialize data in Hadoop with the Microsoft Avro Library](https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/apache-hadoop-dotnet-avro-serialization)

Note

The Avro SDK is no longer supported by Microsoft. The library is open source community supported. The sources for the library are located in [GitHub](https://github.com/Azure/azure-sdk-for-net/tree/master/src/ServiceManagement/HDInsight/Microsoft.Hadoop.Avro).

**Comment by tylerfox** [comment]
That's correct. The Avro SDK is no longer supported by Microsoft.
