### ISSUE TITLE
Spelling errors in Azure.Identity Troubleshooting Guide

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#26632]
There are spelling errors in the sdk/identity/Azure.Identity/TROUBLESHOOTING.md file, like "Mananged" and "Authenticaiton". Headers and links will need to be adjusted.

The Microsoft Docs pack is also reporting duplicate headers, which can generate ambiguous bookmarks.

Given that generated header stubs would change and you'd have to add a `<a name="{old header stub}"></a>` to retain them, now might be a good idea to have unique IDs we can link to.

**Comment by scottaddie** [comment]
Thanks for reporting this, @heaths! I'll take care of it.

**Comment by heaths** [comment]
@schaabs is actually working on changes right now. To avoid conflicts, might be best to coordinate with him.
