### ISSUE TITLE
ArmClientOptions should be updated to take Audience rather than Scope

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#26635]
The Azure SDK has a pattern for how to configure the authentication for services using distinct scopes for sovereign clouds. This entails including an `Audience` property in the client options, exposing an extensible enum which defines the audience for all well-known clouds, then finally using the configured audience to construct the scope inside the client. Taking only the audience rather than the full scope allows for better forward compatibility in the case the service begins using different scopes for different operations.

- [ ] Add an extensible enum `ArmAudience` to Azure.ResourceManaged which defines the ARM audience for each cloud. See [ContainerRegistryAudience](https://github.com/Azure/azure-sdk-for-net/blob/a0e4df83833f85cad0ca823cd8fb98835ba36e37/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Models/ContainerRegistryAudience.cs) as an example.
- [ ] Rename [Scope](https://github.com/Azure/azure-sdk-for-net/blob/a0e4df83833f85cad0ca823cd8fb98835ba36e37/sdk/resourcemanager/Azure.ResourceManager/src/ArmClientOptions.cs#L27) in `ArmClientOptions` to `Audience` with the type `ArmAudience`
- [ ] Update the [`ArmClient` constructor](https://github.com/Azure/azure-sdk-for-net/blob/a0e4df83833f85cad0ca823cd8fb98835ba36e37/sdk/resourcemanager/Azure.ResourceManager/src/ArmClient.cs#L114) to construct the default scope using the `Audience` option. See [ContainerRegistryClient](https://github.com/Azure/azure-sdk-for-net/blob/a0e4df83833f85cad0ca823cd8fb98835ba36e37/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/ContainerRegistryClient.cs#L87) as an example.

**Comment by archerzz** [comment]
@schaabs To get the scope, shall we always append `/.default` to the given audience? I found this [article](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#trailing-slash-and-default), and it seems like the scope should be `https://management.azure.com//.default` which contains two continuous `/`.
