### ISSUE TITLE
[QUERY] ServiceBus Request-Response pattern resulting in exception "Operation is not valid due to the current state of the object."

### ISSUE THREAD

**Issue by davidwoodward** [Azure/azure-sdk-for-net#26630]
### Library name and version

Azure.Messaging.ServiceBus 7.5.1

### Query/Question

This is a 2 fold question and/or issue.  I have a request response pattern implementation that is behaving odd.  The processor receive mode is PeekLock.  And the response queue is a session enabled queue.  

When run through without calling CompleteMessageAsync, the messages are removed from the queue.  If I call CompleteMessageAsync AFTER I send the response message is sent, I get an exception in the error handler.  Could for sure be something I've done incorrectly.  I've created a test app and replicated the behavior.  This is using .Net 6 and Azure.Messaging.Services 7.5.1.

**My main process looks like this:**  

`    Main Process
     
    using Azure.Messaging.ServiceBus;

    string connectionString = "Endpoint=andSoOn";
    string queueName = "posearch";

    ServiceBusClient client = new ServiceBusClient(connectionString);
    TestHandler._serviceBusClient = client;

    ServiceBusProcessorOptions sbpo = new ServiceBusProcessorOptions()
    {
        ReceiveMode = ServiceBusReceiveMode.PeekLock
    };
    ServiceBusProcessor processor = client.CreateProcessor(queueName, sbpo);

    processor.ProcessMessageAsync += TestHandler.MessageHandler;
    processor.ProcessErrorAsync += TestHandler.ErrorHandler;

    await processor.StartProcessingAsync();

    Console.WriteLine($"Press Enter key to end");
    Console.ReadLine();`

**The TestHandler looks like the following:**

`    TestHandler

    public class TestHandler
    {
        public static ServiceBusClient _serviceBusClient;

        public static async Task MessageHandler(ProcessMessageEventArgs args)
        {
            string body = args.Message.Body.ToString();
            string responseQueueName = args.Message.ReplyTo;
            string responseSessionId = args.Message.MessageId;

            ServiceBusSender sender = _serviceBusClient.CreateSender(responseQueueName);

            var message = new ServiceBusMessage(body)
            {
                SessionId = responseSessionId
            };

            try
            {
                await sender.SendMessageAsync(message);
                //_ = args.CompleteMessageAsync(args.Message);    <<<<<<<<<
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Send Exception: {ex.Message}");
            }
        }

        public static Task ErrorHandler(ProcessErrorEventArgs args)
        {
            Console.WriteLine($"ErrorHandler Exception: {args.Exception.Message}");

            return Task.CompletedTask;
        }
    }`

As shown, Error Handler is not called, however the entry in the receivequeue is removed. 

With the commented out call to CompleteMessageAsync complied in, ErrorHandler is called and the exception is "Operation is not valid due to the current state of the object."

With the commented out call to CompleteMessageAsync before the call to SendMessageAsync everything behaves as I would expect it to.  But I do not want to complete the message until after the response is successfully sent.

### Environment

Occurring on my Windows 10 development machine.  .Net 6 build with VS 2022 Version 17.0.4.

**Comment by JoshLove-msft** [comment]
Are you awaiting the call to CompleteAsync? If not, then my guess is we are exiting your handler and attempting to autocomplete the message while your complete call is still in-flight, which may be causing this error.

**Comment by JoshLove-msft** [comment]
> Yes, that was it. Was hoping to not await as CompleteMessage is expensive.

With the processor programming model, you'll need to await the completion, as there is an assumption that you are done with the message once your handler returns.

**Comment by JoshLove-msft** [comment]
> > Yes, that was it. Was hoping to not await as CompleteMessage is expensive.
> 
> With the processor programming model, you'll need to await the completion, as there is an assumption that you are done with the message once your handler returns.

If you want to avoid awaiting the completion, you can try setting AutoCompleteMessages to false so that the processor will not do anything on your behalf once your handler returns.
