### ISSUE TITLE
If-Match header inconsistency between frameworks

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#26639]
In .NET Core 3.1, empty If-Match headers are propagated through in the request.
In .NET Framework and .NET 6.0, they are removed.
We should evaluate what the correct behavior is here and standardize on it.

**Comment by JoshLove-msft** [comment]
Chatted with @pakrym about this - this seems like less of a concern than the other normalization fixes that we did because specifying an empty string for a header is not really a valid use case.

**Comment by pallavit** [comment]
@JoshLove-msft given your above comment do you see us fixing this issue?
