### ISSUE TITLE
[QUERY] Retrieval of VMSS VMs properties using new Azure.ResourceManager libraries

### ISSUE THREAD

**Issue by peterboba** [Azure/azure-sdk-for-net#26646]
### Library name and version

Azure.ResourceManager.Compute Version="1.0.0-beta.5" Azure.ResourceManager.Network Version=1.0.0-beta.5

### Query/Question

I have questions about the new resource manager libraries:

1. How can I retrieve a public IP of a running VMSS instance? Tried various things without any luck. 
2. How can I retrieve all the running (or deallocated) instances in VMSS? Came up with this, but it seems very cryptic to me:
 ```
 var vms = vmCollection.GetAllAsync(filter: "startswith(instanceView/statuses/code, 'PowerState') eq true", select: "instanceView/statuses", expand: "instanceView");
var filtered = vms.Where(ins => ins.Data.InstanceView.Statuses[0].Code == "PowerState/running");
```

### Environment

Platform: Windows
Microsoft Visual Studio Professional 2019
Version 16.10.0
```
.NET SDK (reflecting any global.json):
 Version:   5.0.300
 Commit:    2e0c8c940e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.300\

Host (useful for support):
  Version: 5.0.6
  Commit:  478b2f8c0e

.NET SDKs installed:
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.514 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]
  5.0.300 [C:\Program Files\dotnet\sdk]
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by peterboba** [comment]
Thanks @jsquire

**Comment by peterboba** [comment]
Any help would be appreciated here

**Comment by ArthurMa1978** [comment]
@Yao725 please help on it

**Comment by peterboba** [comment]
Thank you @Yao725 . Do you have any idea when will `GetVirtualMachineScaleSetPublicIPAddresses` be released?

**Comment by Yao725** [comment]
> Thank you @Yao725 . Do you have any idea when will `GetVirtualMachineScaleSetPublicIPAddresses` be released?

Sorry, there is no specific date yet.

**Comment by egraff** [comment]
@Yao725 I've noticed that Azure.ResourceManager.Compute has moved out of preview. Is there any update on this issue?

**Comment by Yao725** [comment]
> @Yao725 I've noticed that Azure.ResourceManager.Compute has moved out of preview. Is there any update on this issue?

These methods are still not available currently but will be good to go soon.

**Comment by egraff** [comment]
@Yao725 how is this issue currently tracking?

**Comment by HarveyLink** [comment]
Hi All, we have get public IP addresses method available in: https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.network.virtualmachinescalesetvmnetworkresource.getallpublicipaddressdata?view=azure-dotnet. Please take a look.
