### ISSUE TITLE
[BUG] [Azure.ResourceManager] Method 'AsPages' in type 'FuncAsyncPageable`1' does not have an implementation on pwsh 7.2.1

### ISSUE THREAD

**Issue by BethanyZhou** [Azure/azure-sdk-for-net#26641]
### Library name and version

Azure.ResourceManager 1.0.0-beta.7/Azure.ResourceManager.KeyVault 1.0.0-beta.5

### Describe the bug

I'm writing a cmdlet by c# code. When I get return objects from armClient and convert Pageable<Vault> as IEnumerable<Vault>. it said that Azure.ResourceManager  does not have an implementation about method 'AsPages' in type 'FuncAsyncPageable. This issue appears on pwsh 7.2.1 but disappear on pwsh 7.1.5.

![image](https://user-images.githubusercontent.com/19869716/151301810-12ec88a3-08cd-4f7a-9bea-ba0e282d4abb.png)

### Expected behavior

AsPages() is actually a public method for Pageable object, I expect we can invoke it successfully.

### Actual behavior

it said that Azure.ResourceManager  does not have an implementation about method 'AsPages' in type 'FuncAsyncPageable

### Reproduction Steps

```c#
        private ResourceGroup GetResourceGroup(string resourcegroup) =>
            _armClient.GetResourceGroup(new ResourceIdentifier(
                string.Format("/subscriptions/{0}/resourceGroups/{1}", _subscription, resourcegroup)));

        public IEnumerable<Vault> ListVaults(string resourcegroup) =>
            GetResourceGroup(resourcegroup).GetVaults().GetAll();

            var response = Track2KeyVaultManagementClient.ListVaults(resourcegroup);
```

### Environment

dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.416
 Commit:    8d3765c609

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.416\

Host (useful for support):
  Version: 3.1.22
  Commit:  35fa579a30

.NET Core SDKs installed:
  3.1.412 [C:\Program Files\dotnet\sdk]
  3.1.416 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@archerzz  please help to check this issue
