### ISSUE TITLE
What are the format/contents of the ContentRange string

### ISSUE THREAD

**Issue by billti** [Azure/azure-sdk-for-net#26640]
It would be helpful if this page described the format for this string. Just saying it's a string isn't that valuable.

Looking at the code in `sdk\storage\Azure.Storage.Blobs\src\Models\ContentRange.cs` I see the below comments, so I assume this is the format. 

To be extra helpful, it would also be good to know if Azure Blob Storage ever does return `*` for the blob size, of if you can reliably get the size in bytes of the blob from this field when requesting ranges.

```
            /* Parse header value (e.g. "<unit> <start>-<end>/<blobSize>")
             * Either side of the "/" can be an asterisk, so possible results include:
             *   [<unit>, <start>, <end>, <blobSize>]
             *   [<unit>, "*", <blobSize>]
             *   [<unit>, <start>, <end>, "*"]
             *   [<unit>, "*", "*"] (unsure if possible but not hard to support)
             * "End" is the inclusive last byte; e.g. header "bytes 0-7/8" is the entire 8-byte blob
             */
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5018390-040d-4f72-84b5-f8262968e0d4
* Version Independent ID: 5bbaf33b-8f4b-3858-278e-63b222b81dc5
* Content: [BlobDownloadDetails.ContentRange Property (Azure.Storage.Blobs.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobdownloaddetails.contentrange?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Models/BlobDownloadDetails.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Models/BlobDownloadDetails.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@billti Thanks for your suggestion. I am redirecting this to service team to help adding additional details to the documentation. 
Also, I believe blob sizes returned can be `*` but I will let service team confirm on the same. 

Thanks
Saurabh

**Comment by amishra-dev** [comment]
@billti Bill, have you looked at https://docs.microsoft.com/en-us/rest/api/storageservices/specifying-the-range-header-for-blob-service-operations
This should help explain the REST API behavior, we will look into improving the docs

**Comment by amnguye** [comment]
Looks like this comment in the ContentRange code you found is more relating to the format that RFC defines Content Range to come back as in the Response.

For Content Range you can expect to receive a start, end and blobsize as the value. The service does not utilize passing back a * in the content range.

We will look to specify in the XML documentation that the Content Range can come back as
```
/* Parse header value (e.g. "<unit> <start>-<end>/<blobSize>")
             * Either side of the "/" can be an asterisk, so possible results include:
             *   [<unit>, <start>, <end>, <blobSize>]
             * "End" is the inclusive last byte; e.g. header "bytes 0-7/8" is the entire 8-byte blob
             */
```

**Comment by billti** [comment]
Thanks @amnguye  . So to clarify, as of today, the content-range header returned is always of the format "bytes x-y/z", where x, y, and z are integers? The code comment you included in your post still states `Either side of the "/" can be an asterisk`, but your wording also states `The service does not utilize passing back a * in the content range`, which seems contradictory.

**Comment by amnguye** [comment]
Hi, sorry about that, I think I was quick editting it and missed that part.

The following documentation won't exactly look this but should look something similar like this. This might change depending on feedback during code review.
```
/* Parse header value (e.g. "<unit> <start>-<end>/<blobSize>")
* "End" is the inclusive last byte; e.g. header "bytes 0-7/8" is the entire 8-byte blob
*/
```
I might have to update this further once I gather more information and feedback.
