### ISSUE TITLE
HDInsightManagementClient constructor does not check if the passed SubscriptionCloudCredentials has a non empty SubscriptionId

### ISSUE THREAD

**Issue by aaneja** [Azure/azure-sdk-for-net#2664]
Since all operations would need a non empty SubscriptionId for any ClusterOperation a string.isNullOrEmpty check should be performed on credentials.SunbscrptionId

**Comment by idear1203** [comment]
We now do not pass `subscriptionId` through `SubscriptionCloudCredentials`. Please check the [Azure HDInsight SDK for .NET](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/hdinsight?view=azure-dotnet) for usage details
