### ISSUE TITLE
Unclear, if this has to be set manually

### ISSUE THREAD

**Issue by torbennehmer** [Azure/azure-sdk-for-net#26643]
Please clarify the documentation regarding this property, it is not clear if and how it has to be set. 

Use Case: You're implementing an Integration in an app, where you have to do the integration manually (for whatever reasons) based on the information in https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics.

However, it is unclear to me if I have to add a sequence number manually or if the framework does so in all cases. If it has to be added manually, some guidelines in https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-custom-events-metrics would be welcome.

Thank you!

Best regards
Torben

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8271b93-6546-1494-56fe-eabf116e1976
* Version Independent ID: b88b8bd1-eb5a-193c-efbe-cce816b30dae
* Content: [ITelemetry.Sequence Property (Microsoft.ApplicationInsights.Channel) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.channel.itelemetry.sequence?view=azure-dotnet)
* Content Source: [xml/Microsoft.ApplicationInsights.Channel/ITelemetry.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights.Channel/ITelemetry.xml)
* Service: **application-insights**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@torbennehmer I believe you need to implement this in your code, however, rerouting this to another team to confirm back and update the documentation if require.
