### ISSUE TITLE
Authenticating via Visual Studio only seems to work if the TenantId is supplied -- is that correct?

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-sdk-for-net#26652]
With regard to Visual Studio credentials -- see my StackOverflow post at:

[https://stackoverflow.com/questions/70869615/visual-studio-2019-tokenservice-exe-has-failed-with-unexpected-error-ts003-err](https://stackoverflow.com/questions/70869615/visual-studio-2019-tokenservice-exe-has-failed-with-unexpected-error-ts003-err)

I would like some clarification in the documentation with regard to what values (if any) are required when using the [DefaultAzureCredentialOptions.](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredentialoptions?view=azure-dotnet)  class, specifically with the [ExcludeVisualStudioCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredentialoptions.excludevisualstudiocredential?view=azure-dotnet).

In my scenario, I was trying to use the Visual Studio credential in order to use Azure KeyVault.  According to the docs, the credentials **should be picked up automatically** after logging into Azure via Visual Studio.  Experience to date indicates this is not the case as the ONLY way I can seem to make this option work is by setting the VisualStudioTenantId property manually as shown in my StackOverflow post.

If someone could provide a code sample using the Visual Studio credential WITHOUT having to set the TenantId manually (or update the docs to indicate the TenantId MUST be specified for this option), that would be most helpful.

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 615f84d6-1fac-9689-3c60-320ba71885f7
* Version Independent ID: ad90a58b-2120-b876-8f3c-0bffe298c158
* Content: [DefaultAzureCredentialOptions.VisualStudioTenantId Property (Azure.Identity) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredentialoptions.visualstudiotenantid?view=azure-dotnet)
* Content Source: [xml/Azure.Identity/DefaultAzureCredentialOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Identity/DefaultAzureCredentialOptions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Could you try this with the latest beta KeyVault package version? It has a new feature that will attempt to perform tenant discovery.  https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/4.3.0-beta.4

**Comment by bdcoder2** [comment]
Christopher – I can confirm that after installing the Azure.Security.KeyVault.Secrets  4.3.0-beta.4 package, the Visual Studio credentials are picked up WITHOUT the need to include the Tenant ID.

 

Currently my project was using the following NuGet packages:

 

Azure.Extensions.AspNetCore.Configuration.Secrets

Azure.Identity

 

I can see that Azure.Extensions.AspNetCore.Configuration.Secrets depends on Azure.Extensions.AspNetCore.Configuration.Secrets (>= 4.0.2); hopefully, the Azure.Extensions.AspNetCore.Configuration.Secrets package will be updated soon to include the beta update.

 

Thanks!

**Comment by bdcoder2** [comment]
From Stackoverflow:

Chistothes: Note this feature was added to the Key Vault SDK here github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/… in combination with the >=1.5.0 version of Azure.Identity

bdcoder: Strange, I am using Azure.Identity 1.5.0 -- but if I remove the Azure.Security.KeyVault.Secrets 4.3.0-beta.4 package, the VisualStudio credentails are NOT picked up (as per the original post).

**Comment by christothes** [comment]
Yes, both are needed together.

**Comment by bdcoder2** [comment]
@christothes - sorry for being slow here, but I have 3 NuGet packages installed currently:

- Azure.Extensions.AspNetCore.Configuration.Secrets 1.2.1
- Azure.Identity 1.5.0
- Azure.Security.KeyVault.Secrets 4.3.0-beta.4

When the above are used, everything works.

I was under the impression that only two of the packages (**Azure.Extensions.AspNetCore.Configuration.Secrets** and **Azure.Identity**) should be required because of the comment "this feature was added to the Key Vault SDK here github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/… in combination with the >=1.5.0 version of Azure.Identity".   

So to clarify -- all THREE packages are required?

**Comment by bdcoder2** [comment]
@christothes - Thank-you again! - makes sense.
