### ISSUE TITLE
BUG In Azure Function Trigger with Managed Identity

### ISSUE THREAD

**Issue by LRomano72** [Azure/azure-sdk-for-net#26663]
I think there is a bug in the use of Azure Function Trigger Bindings on the Connection value when a Managed Identity is used.

We are using Managed Identity with Consumption based Function App to receive events from the EventHub. As per the Microsoft documentation: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=csharp#identity-based-connections
we are using the following connection string in the EventHub trigger: 

`EhubSaaSSecConnection__fullyQualifiedNamespace: [[ REDACTED ]].servicebus.windows.net`

Here’s the Function App signature: 
```csharp
[FunctionName("EventHub-To-EventHubFunction")]
public static async Task Run(
// SaaS EH Trigger - Receives events from source EH
[EventHubTrigger(Constants.SaasEHName, Connection = Constants.SaasEHConnectionName)] EventData[] events,
// QRadar EH Output binding - Sends events to dest EH
[EventHub(Constants.QRadarEHName, Connection = Constants.QRadarEHConnectionName)] IAsyncCollector<string> outputEvents, ILogger log)
```

Here are the constants:
```csharp
public const string SaasEHConnectionName = "EhubSaaSSecConnection";
public const string QRadarEHConnectionName = "EhubQRadarConnection";
```
The function EventHub-To-EventHubFunction is getting triggered without any exception when the Azure portal is open, but the trigger gets hibernated afterward and does not activate even if events queued up in the Event Hub. Upon the troubleshooting, we found the following errors in Scale Controller which is preventing the function to scale up when there’s an event. 
After you enable the logging of the Scale Controller Logs you can use the Kusto query:
traces   
| extend CustomDimensions = todynamic(tostring(customDimensions))  
| where CustomDimensions.Category == "ScaleControllerLogs"  
| order by timestamp desc  

You'll see logs as the following:
Specified  connection string is null or empty for connection: EhubSaaSSecConnection.   Invalid connection.

More Information below from a different thread: 
https://github.com/Azure/azure-sdk-for-net/issues/12657#issuecomment-1011820099
All credits to @Swing0601 
https://github.com/Swing0601:
I got the same error message, and looked into the source code, finally figured it out. Hope it will be helpful.

here is the source code, there is condition whether get the connection with Identity or Shared Access
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Config/EventHubClientFactory.cs
![image](https://user-images.githubusercontent.com/20235713/149273362-9a73ad5f-a733-4921-875b-33db2995257c.png)

Identity-based connections require "<CONNECTION_NAME_PREFIX>__fullyQualifiedNamespace" property. 
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-trigger?tabs=csharp#identity-based-connections

My issue is caused by CONNECTION_NAME_PREFIX is not correct, the format is AzureWebJobs + connectionName, here is an example, CONNECTION_NAME_PREFIX is "AzureWebJobsmyEventHubConnectionString", then "<CONNECTION_NAME_PREFIX>__fullyQualifiedNamespace" value is "AzureWebJobsmyEventHubConnectionString___fullyQualifiedNamespace"

function.json:
![image](https://user-images.githubusercontent.com/20235713/149271683-15fff968-f407-41b4-8159-ade541b6b6f7.png)

BTW, my develop language is Python, 

CONNECTION_NAME_PREFIX source code:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Microsoft.Azure.WebJobs.Extensions.Clients/src/Shared/WebJobsConfigurationExtensions.cs
 
![image](https://user-images.githubusercontent.com/20235713/149272768-556987ca-7602-4c7e-ad46-9477268c3f97.png)

Good Luck!!!

_Originally posted by @Swing0601 in https://github.com/Azure/azure-sdk-for-net/issues/12657#issuecomment-1011820099_

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by LRomano72** [comment]
Just providing an update to this and yes there is a bug and to resolve it, you need to create the AppSettings for the Connection value with: "AzureWebJobs" + <your connection value>

In my example, adding this to the AppSettings in the Azure Function fixed the problem:
OLD AppSettings Name:
EhubSaaSSecConnection__fullyQualifiedNamespace: [[ REDACTED ]].servicebus.windows.net

New AppSettings Name that works:
**AzureWebJobs**EhubSaaSSecConnection__fullyQualifiedNamespace: [[ REDACTED ]].servicebus.windows.net

Just had to restart the function app to force it to pick up the changes and the error in the Scale Controller logs are gone and everything is working.

**Comment by LRomano72** [comment]
Just reviewing the Unit Tests for Event Hubs here: 
https://github.com/Azure/azure-functions-eventhubs-extension/blob/2e30273447f7d845328bbedca1180af86cf2131c/test/Microsoft.Azure.WebJobs.Extensions.EventHubs.Tests/EventHubEndToEndTests.cs

You can see that the test case is the Happy Happy Path: https://github.com/Azure/azure-functions-eventhubs-extension/blob/2e30273447f7d845328bbedca1180af86cf2131c/test/Microsoft.Azure.WebJobs.Extensions.EventHubs.Tests/EventHubEndToEndTests.cs#L21
E.g.
        private const string TestHub2Connection = "AzureWebJobsTestHubConnection2";
and Includes the prefix constant. Suggest a new unit test to remove this requirement and show it works, and/or update all the documentation to ensure that this constant value is required for these scenario's.

Thank you

**Comment by JoshLove-msft** [comment]
Thanks for filing this issue @LRomano72. I will try to repro it on my end and get back to you.

**Comment by LRomano72** [comment]
Just to update everyone on this. The fix of adding "AzureWebJobs" to the connection variable name in AppSettings did not fix the issue. MSFT is reaching out to the Scale Controller team as they must be an issue there when working with Managed Identity.

As a work around that removes the Scale Controller but will cost you more, is to create an App Service Plan - Standard (min) and then deploy your Function App into that and enable the "Always On" setting so you don't have cold starts issues and the FApp is warm.

Someone else was doing the IaC and we had thing up and running in less then an hours, no changes to any resource names and we had to whitelist all the new IPs to the Event Hub Namespace for security reasons. In general, this scenario will cost you CAD $100/month if you don't have a spare App Service Plan. 

MSFT will continue to work on the issue as FApp Consumption plan tier was designed for this scenario so they will make it work.

**Comment by JoshLove-msft** [comment]
I believe the bug here has been tracked down to an issue in the scale controller that the service team is aware of and the workaround is to prepend "APPSETTING_" to your connection setting.
/cc @karshinlin

**Comment by brennfoster** [comment]
Just leaving this here for anyone else experiencing this and not able to see in their logs where the exception is coming from. It requires a special app setting to enable these logs     

```
"name": "SCALE_CONTROLLER_LOGGING_ENABLED",
"value": "AppInsights:Verbose"
```


Scale Controller is definitely the problem.

```
An error occurred while setting up blob references. Exception: 'System.ArgumentException: ServiceBus Namespace not found.
   at Microsoft.Azure.AppService.ScaleController.Extension.ActivationTasks.EventHubActivationTask.GetServiceBusNamespace(SiteMetadata siteInfo, String connectionName, Guid activationTaskId)
   at Microsoft.Azure.AppService.ScaleController.Extension.ActivationTasks.EventHubActivationTask.TryCreate(ScaleControllerConfiguration config, SiteMetadata siteInfo, TriggerConfiguration trigger, Guid activationTaskId, ActivationTask& eventHubActivationTask, List`1& activationErrors)'
```

**Comment by snekkermoen** [comment]
any updates on this?
prefixing with "AzureWebJobs" does not solve this issue. Basically, consumption plan triggers using MID-authentication basically doesnt work - i'll have to rollback to connection strings before this is solved.. or are there any other workarounds?

**Comment by LRomano72** [comment]
> 

@snekkermoen, there is not fix at this time and the only option is to deploy your function app into an App Service Plan which will then allow the FApp to use the MI correctly. See comments above. MSFT still working on this from email we got from Microsoft reps in Canada.

**Comment by snekkermoen** [comment]
@LRomano72 thanks.
fwiw, this issue looks similar or equal: https://github.com/Azure/azure-functions-host/issues/8241

**Comment by mlowijs** [comment]
Bumping.

**Comment by mlowijs** [comment]
Any update?

**Comment by karshinlin** [comment]
> Any update?

This should be resolved now. Please let us know if you are still observing any issues.

**Comment by mlowijs** [comment]
Right, thanks! I set up the Azure Function app configuration like so, I'll monitor it and see if it works correctly!

![image](https://user-images.githubusercontent.com/2751421/176021776-06517c8d-25c3-4936-b6b0-183d5148a737.png)
