### ISSUE TITLE
Add troubleshooting guide or sample about multi-tenant authentication

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#26669]
Add section to the Identity troubleshooting guide or a sample about multi-tenant authentication, like how whatever tenant you set is the home tenant ID, but auto-discovery works with 1.5.0 or newer of Azure.Identity.

Once done, be sure to update:

* [ ] https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/TROUBLESHOOTING.md
* [ ] https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/TROUBLESHOOTING.md

**Comment by pallavit** [comment]
@heaths multi-tenant authentication section in identity mentions allowedTenantDiscovery starting 1.7.0? Is that what you had in mind for TSG or were you thinking of something else?

**Comment by heaths** [comment]
Looks like we already did this and just didn't associate the PRs or forgot about this tracking issue.
