### ISSUE TITLE
[BUG] Azure Identity 1.5 - ChainedTokenCredential will throw when work with ClientCertificateCredential

### ISSUE THREAD

**Issue by iqoOopi** [Azure/azure-sdk-for-net#26660]
### Library name and version

Azure Identity v1.5

### Describe the bug

var certificate = store.Certificates.Cast<X509Certificate2>()
                    .FirstOrDefault(cert => cert.Thumbprint == "XXXX");

var credential = new ChainedTokenCredential(new ClientCertificateCredential(tenantId, clientId, certificate), new VisualStudioCredential());

Hi there,  if I chain **ClientCertificateCredential** with **VisualStudioCredential**. It will throw if the certificate is null instead of trying the second method (VS credential). Usually, the certificate only exists for prod and it should be null when debugging locally.

### Expected behavior

If the certificate is null, then try the second method to authenticate.

### Actual behavior

If will throw {"Value cannot be null.\r\nParameter name: certificate"} and stop autenticating with other methods.

### Reproduction Steps

var store = new X509Store(StoreName.My, StoreLocation.LocalMachine);

store.Open(OpenFlags.ReadOnly);

var certificate = store.Certificates.Cast<X509Certificate2>()
                    .FirstOrDefault(cert => cert.Thumbprint == "XXXX");

store.Close();

var credential = new ChainedTokenCredential(new ClientCertificateCredential(tenantId, clientId, certificate), new VisualStudioCredential());

make sure you do not have a matching certificate in your local store

### Environment

VS 2022 - windows 11

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @iqoOopi  - The `ClientCertificateCredential` won't accept a null argument, but since you are already dynamically building the chain, you could do this instead:

```c#
var certificate = store.Certificates.Cast()
    .FirstOrDefault(cert => cert.Thumbprint == "XXXX");

var credential = certificate != null ? 
    new ClientCertificateCredential(tenantId, clientId, certificate) : 
    new VisualStudioCredential();
```

If you really did prefer a chain, you could do the same and switch between two different chains - one with and one without ClientCertificateCredential
