### ISSUE TITLE
Telemetry contains redundant sdk info 

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#26677]
The [TelemetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/Internal/TelemetryPolicy.cs) and [MgmtTelemetryPolicy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/Internal/MgmtTelemetryPolicy.cs) both affect the User-Agent telemetry data generation which causes redundant sdk info sending to service.

We should short the string.

**Comment by archerzz** [comment]
There are a few options here:

1. We just let the duplicated information, if it won't impact the analytics or we can update our analytics.
2. Roll back the changes in #26406, and let powershell do the property trick.
3. Try to dismiss the default telemtry in `Azure.Core`: https://github.com/Azure/azure-sdk-for-net/blob/fd977cc4164664f424c3fb86aa78b484b9cc5f4d/sdk/core/Azure.Core/src/Pipeline/HttpPipelineBuilder.cs#L118

**Comment by Yao725** [comment]
Fixed by #27553 and the `MgmtTelemetryPolicy` has been removed.
