### ISSUE TITLE
[BUG] Error: Dependency loop detected for package 'Azure.Messaging.EventHubs' in PowerShell

### ISSUE THREAD

**Issue by milope** [Azure/azure-sdk-for-net#26695]
### Library name and version

Azure.Messaging.EventHubs version 5.6.2

### Describe the bug

Using PowerShell to create a simple Event sender, I start my cmdlet by checking if the package is installed and if not, install it using the following:

```
$packageName = "Azure.Messaging.EventHubs"
$packageSource = "https://www.nuget.org/api/v2"
Install-Package -Name $packageName -Source $packageSource -Force -ErrorAction SilentlyContinue
```

This returns an error stating as follows: "Dependency loop detected for package 'Azure.Messaging.EventHubs'."

### Expected behavior

The package 'Azure.Messaging.EventHubs' version 5.6.2 should be installed as a package in PowerShell. Then we can proceed to reference Event Hub objects.

### Actual behavior

PowerShell throws an error stating that there is a "Dependency loop detected for package 'Azure.Messaging.EventHubs'." No stack trace, HResult: -2146233088

### Reproduction Steps

In either PowerShell 5 or 7, run the following:

```
$packageName = "Azure.Messaging.EventHubs"
$packageSource = "https://www.nuget.org/api/v2"
Install-Package -Name $packageName -Source $packageSource -Force -ErrorAction SilentlyContinue
```

### Environment

OS: Windows 11 Version 21H2 (OS Build 22000.434)
PowerShell 7: 7.2.1
Windows PowerShell: 5.1.22000.282 (CLR: 4.0.30319.4200)

**Comment by jsquire** [comment]
Hi @milope.   Thank you for reaching out and we regret that you're experiencing difficulties.   This appears to be related to a conflict somewhere in `Azure.Core`, which is a dependency of the Event Hubs package.   We'll investigate further.

**Comment by milope** [comment]
Hello @jsquire. No worries and thank you. I realize I can just download the package and extract it via code, but I am looking to avoid that if I can, to craft a more simplified event producer and event receiver via PowerShell for troubleshooting purposes.

**Comment by milope** [comment]
> Hi @milope. Thank you for your patience and apologies for the delay. We were able to discuss with some folks from the PowerShell team and gain some insight.
> 
> The root cause is that the `PackageManagement` module to which the `Install-Package` cmdlet belongs is deprecated and hasn't been in active development for a fair bit of time. My understanding is that `PackageManagement` relies on references to some framework assemblies like `System.Text.Json` and `System.Web.Http` that are already loaded into the PowerShell environment for newer versions. When it attempted to resolve the dependency graph for a NuGet package, it used the intrinsic version of those framework assemblies which causes the dependency loop.
> 
> Unfortunately, the guidance that we received was to advise against using `Install-Package`, instead using `nuget.exe` or the NuGet API directly to resolve the packages, and then load them into the context using `Add-Type`, `Assembly.LoadFrom`, or a custom `AssemblyLoadContext`. The PowerShell team recommended [this article](https://docs.microsoft.com/powershell/scripting/dev-cross-plat/resolving-dependency-conflicts?view=powershell-7.2) as a reference for loading the package assemblies and avoiding version conflicts.
> 
> The Azure SDK libraries are used by Azure Management cmdlets and dependencies are coordinated with the PowerShell team; to our knowledge, there should be no conflicts with framework assemblies using them. I tested loading the `Azure.Messaging.EventHubs` dll using `Add-Type` in PSCore 7 and was able to do so without error.

I can give this a try. It's a much better workaround than to manually decompressing the file and adding what's needed. Thank you for the findings.
