### ISSUE TITLE
[BUG] Serious performance regression using SecretClient with ChainedTokenCredential

### ISSUE THREAD

**Issue by NeilMacMullen** [Azure/azure-sdk-for-net#26709]
### Library name and version

Azure.Security.KeyVault.Secrets 4.2.0 (Net6) 

### Describe the bug

Using this code:

```
 var vault = new Uri(vaultName);
 var client = new SecretClient(vault,
                new ChainedTokenCredential(
                    new ManagedIdentityCredential(),
                    new AzureCliCredential()));

 var secret = await client.GetSecretAsync(secretName);
```

It takes 92 (yes, NINETY-TWO) seconds for GetSecretAsync to return when calling from a desktop app.  The issue appears to be caused by the inclusion of the ManagedIdentifyCredential call in the chain.  If I drop this, the response is not delayed.  Previous versions (running on Net5 did not suffer this problem.

I'm using a ChainedTokenCredential because the code is expected to work in one of two environments:
1. A deployed function or web api when a managed-identity will be provided. (ManagedIdentityCredential)
2. On a local PC where developer credentials will be used (AzureCliCredentials)

Maybe there is a "new" way to do this now?  The code is based on the examples from the first SDK releases so may be out of date.

### Expected behavior

Previous versions of the library were far more performant and would return a secret in under a second.

### Actual behavior

Unacceptable ninety second (seems suspiciously like a hard-coded timeout?) delay.

### Reproduction Steps

See code in description

### Environment

```
11:38/Backend>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.200-preview.22055.15
 Commit:    a3c3a2bf3b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200-preview.22055.15\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.200-preview.22055.15 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

VS 2022 Preview

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by NeilMacMullen** [comment]
@christothes Ah - super.  WiIl close this as dup
