### ISSUE TITLE
[QUERY] Storage:  Long latencies for HEAD requests to non-existent blobs

### ISSUE THREAD

**Issue by sgryt** [Azure/azure-sdk-for-net#26707]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Query/Question

We are experiencing surprisingly large number of requests with very long client-side latencies for HEAD requests to non-existing blobs.

We _do not_ see the same behavior in the corresponding raw storage service metrics.

Log-scale response time histogram as reported by the Application Insights module:
<img width="1682" alt="image" src="https://user-images.githubusercontent.com/1608003/151770389-db2a5a22-6135-4017-879e-be7679b02f47.png">

Histogram data are for `HTTP HEAD` requests (24 hour interval), all with `toint(resultCode) == 404` to our storage account (on `.blob.core.windows.net`). 

The first cluster of records is expected (response times less than approx. 25 ms). This cluster is consistent with the metrics we have available in the raw storage service.

What we find strange are the clusters around 50ms, 100ms, 1000ms and 2000ms.

We are not setting a secondary geo-rendundant connection string.

Please advise on how to proceed - are there some settings we can tweak on the client side to control this behavior ?

### Environment

Our client code runs in a Linux container in Azure App Service, using .NET 5.0.

IDE: Visual Studio Version 16

**Comment by SaurabhSharma-MSFT** [comment]
@sgryt Are you always getting this issue? Have you tried with any other storage accounts? You may need to go through a support ticket route so that engineers could look into your environment to identify the root cause.  Please let me know if you need any help creating a support ticket.

**Comment by sgryt** [comment]
@SaurabhSharma-MSFT We have only observed it for one of our services, but it has been consistent there. 

I was asked by the Azure support team to raise the issue here, we have already had a fairly lenghty dialog about it.

**Comment by SaurabhSharma-MSFT** [comment]
@sgryt ok. I am redirecting this to service team to help you.

**Comment by richmms** [comment]
@SaurabhSharma-MSFT @xgithubtriage - has this issue been fixed?
