### ISSUE TITLE
[FEATURE REQ] Support for ListVirtualMachineScaleSetNetworkInterfacesAsync() in Azure.ResourceManager.Network

### ISSUE THREAD

**Issue by itai** [Azure/azure-sdk-for-net#26708]
### Library name

Azure.ResourceManager.Network

### Please describe the feature.

Azure.ResourceManager.Network (version 1.0.0-beta.5) does not contain an equivalent of [NetworkInterfacesOperationsExtensions.ListVirtualMachineScaleSetNetworkInterfacesAsync()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.network.networkinterfacesoperationsextensions.listvirtualmachinescalesetnetworkinterfacesasync?view=azure-dotnet), which is found in Microsoft.Azure.Management.Network.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by omri-muszkal** [comment]
Hey @jsquire, @ArthurMa1978  any update on this?

**Comment by jsquire** [comment]
Hi @omri-muszkal.  Unfortunately, my role for this was only to perform initial triage; I don't have insight into its status. I'll need to defer to @ArthurMa1978.

**Comment by ArthurMa1978** [comment]
@itai  this method is move back to [compute](https://docs.microsoft.com/en-us/dotnet/api/azure.resourcemanager.compute.virtualmachinescaleset.getasync?view=azure-dotnet-preview) now.

**Comment by omri-muszkal** [comment]
@ArthurMa1978 is what @itai saying can be found anywhere?

**Comment by ArthurMa1978** [comment]
We have updated the beta sdk, and try to provide new experience of vmss, @fengzhou-msft please help on to provide a sample

**Comment by omri-muszkal** [comment]
Hi @ArthurMa1978, I saw that there now information about the NIC configuration but not the actual settings :(

If I am wrong please point me in the right direction

**Comment by fengzhou-msft** [comment]
@omri-muszkal we've decided to add the `ListVirtualMachineScaleSetNetworkInterfaces` operation which has a dependency between network and compute after GA. We have this issue to track the feature: https://github.com/Azure/azure-sdk-for-net/issues/28185

**Comment by paupal1** [comment]
This is also a blocker for me - I will need to use old package until this information is accessible.

**Comment by s20leems** [comment]
@fengzhou-msft , I reviewed the feature you tagged in here, but I couldn't find a way to retrieve the VMSS VM public IP address from its NetworkInterface. Could you share an example of how to retrieve Public IP address from Microsoft.Compute? Currently, the only way to retrieve is to use the older version of the ListVirtualMachineScaleSetNetworkInterfacesAsync.

**Comment by fengzhou-msft** [comment]
It looks like the partial resource feature is ready, but we'll need to regen the Network SDK. @ArcturusZhang to help.

**Comment by itai** [comment]
When do you expect to regenerate the SDK?

**Comment by ArthurMa1978** [comment]
We're still working on the partial resource and here is issue https://github.com/Azure/azure-sdk-for-net/issues/35717 to track the progress.

**Comment by ArthurMa1978** [comment]
We have released new [version](https://www.nuget.org/packages/Azure.ResourceManager.Network/1.6.0-beta.1) for the VMSS.
