### ISSUE TITLE
[BUG] Web PubSub functions bindings ignores CancellationToken

### ISSUE THREAD

**Issue by skystedt** [Azure/azure-sdk-for-net#26704]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.WebPubSub 1.1.0

### Describe the bug

Using the example from here: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSub#functions-that-uses-web-pubsub-output-binding

When adding a CancellationToken to the call `action.AddAsync`, it will be ignored.

### Expected behavior

The CancellationToken should be used.

### Actual behavior

The CancellationToken is ignored.

### Reproduction Steps

Use the code from: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/webpubsub/Microsoft.Azure.WebJobs.Extensions.WebPubSub#functions-that-uses-web-pubsub-output-binding
Add a CancellationToken.

Sample code:
```
public static class WebPubSubOutputBindingFunction
{
    [FunctionName("WebPubSubOutputBindingFunction")]
    public static async Task RunAsync(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequest req,
        [WebPubSub(Hub = "hub", Connection = "<connection-string>")] IAsyncCollector<WebPubSubAction> action)
    {
        using var cts = new CancellationTokenSource(5000);
        await action.AddAsync(WebPubSubAction.CreateSendToAllAction("Hello Web PubSub!", WebPubSubDataType.Text), cts.Token);
    }
}
```

### Environment

Azure Functions with .NET 6

**Comment by SaurabhSharma-MSFT** [comment]
@skystedt Are you following any other documentation which talks about using CancellationToken in Web PubSub service ?

**Comment by JialinXin** [comment]
Thanks for reporting the issue! The output binding missed to respect user's cancellation token when calling Rest Client. See above PR for the fix.
