### ISSUE TITLE
VirtualMachineScaleSetImpl bug

### ISSUE THREAD

**Issue by johnbirdau** [Azure/azure-sdk-for-net#2671]
public VirtualMachineScaleSetImpl WithOverProvision(bool enabled)
        {
            this.Inner
                    .OverProvision = enabled;
            return this;
        }

        public VirtualMachineScaleSetImpl WithoutOverProvisioning()
        {
            return this.WithOverProvision(true); // **should be false**
        }

        public VirtualMachineScaleSetImpl WithOverProvisioning()
        {
            return this.WithOverProvision(false); // **should be true**
        }

**Comment by martinsawicki** [comment]
oops. I'll take this. (it looks like it's correct on the Java side, so typos introduced during the conversion)

**Comment by martinsawicki** [comment]
fix submitted (https://github.com/Azure/azure-sdk-for-net/pull/2669/commits/d119f6742aa56759c0f70c2d29153024eb2329b9)

**Comment by hovsepm** [comment]
Fixed in Fluent branch. Will be shipped with beta4.1 this week.
