### ISSUE TITLE
[Feature Request] No AzureProgress option for Async Downloads 

### ISSUE THREAD

**Issue by rozeboosje** [Azure/azure-sdk-for-net#26712]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Describe the bug

Uploading asynchronously to Blob Storage with a progress indicator is pretty easy

```
Dim oOptions As Azure.Storage.Blobs.Models.BlobUploadOptions
oOptions = New Azure.Storage.Blobs.Models.BlobUploadOptions

oOptions.ProgressHandler = ..... (created progress handler class to deal with this)

Await blockSourceBlob.UploadAsync(content:=FileStream, options:=oOptions)
```

This works fine.

However, for Downloading I find there is no such thing as an Azure.Storage.Blobs.Model.BlobDownloadOptions and as a result there is no overload of DownloadToAsync that allows me to keep track of progress. This used to be possible in the old Microsoft.WindowsAzure.Storage API so an equivalent thereof needs to be reinstated.

### Expected behavior

API needs to expose a way to track progress of downloads from Blobs

### Actual behavior

API does not expose a mechanism for this as far as I was able to figure out

### Reproduction Steps

n/a

### Environment

n/a

**Comment by SaurabhSharma-MSFT** [comment]
@rozeboosje Thanks for your feedback. `ProgressHandler` is avaialble for upload only and thus redirecting this to services team as this looks like a feature request.

**Comment by rozeboosje** [comment]
I would argue that this is more than just a "feature request". This functionality was available through the Microsoft.WindowsAzure.Storage API. We were then notified that that API had been deprecated and this new API was presented as the replacement for the deprecated API. It is not really acceptable, in that case, for the new API not to have a replacement for functionality that was available in the old, deprecated API.

**Comment by amishra-dev** [comment]
@rozeboosje i agree with you. That is just a classification we use. @jaschrep-msft, @amnguye could you please get back to @rozeboosje with a workaround, if none exists let plan to get this feature in.

**Comment by jaschrep-msft** [comment]
@rozeboosje this appears to be a clone of #8506. Closing this issue and redirecting you there for tracking purposes.

I have recently started working on this issue.
