### ISSUE TITLE
Feature to add auxiliary authorization header

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-for-net#26719]
### Library name

resource

### Please describe the feature.

We have auxiliary authorization header support for Java.

Azure/azure-libraries-for-java#884

Let's also add the support in .net to keep them consistent.

**Comment by nvigne** [comment]
#8544

**Comment by thomas-hammond** [comment]
I need this same feature. After looking at the BearerTokenAuthenticationPolicy, it looks like all it would need is a way to tell it which header to set. You could simply add a new instance of this same class, but tell it to use the "x-ms-authorization-auxiliary" header name.
