### ISSUE TITLE
[BUG]Time trigger function suddenly stops firing

### ISSUE THREAD

**Issue by tkachuk2222** [Azure/azure-sdk-for-net#26710]
### Library name and version

Microsoft.Azure.Functions.Worker 1.5.1

### Describe the bug

I have an azure function (hosted on ASP P1v3) that has near 20 time trigger functions and near 20 service bus functions. From time to time timer trigger functions stops firing. 

What can I do? 

Option 'Always on' is set to 'On'

### Expected behavior

Timer trigger azure functions firing

### Actual behavior

Timer trigger azure functions not firing

### Reproduction Steps

I don't know how to reproduce. I just have azure functions with service bug trigger, timer trigger and http trigger
there are next schedules:
0 */15 * * * *
0 1 * * * *
0 */15 * * * *
0 */5 * * * *
0 */8 * * * *
0 */6 * * * *
0 0 * * * *
0 */1 * * * *
*/1 * * * *
*/1 * * * *
0 10 0 * * *
0 1 0 * * *
0 0 */2 * * *
0 0 6 * * *
0/40 * * * * *
0 */1 * * * *
0 0 1 * * *
0 */5 * * * *
0/5 * * * *
0 0 2 * * *

### Environment

App Service Plan P1v3: 1
OS Windows
Azure function runtime version: 3
.NET 5.0
Worker runtime: dotnet-isolated
Microsoft.Azure.Functions.Worker.Extensions.Time 4.1.0
Microsoft.Azure.Functions.Worker.Sdk 1.0.4
Microsoft.Azure.Functions.Worker 1.5.1

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Functions.Worker` package is maintained as [#793](https://github.com/Azure/azure-functions-dotnet-worker/issues/793).

**Comment by tkachuk2222** [comment]
@jsquire maybe it's not package related issue? 
I see a lot of references regarding timer trigger functions in the Microsoft documentation, but no one topic did help me. I saw the information in the Azure function app diagnostic tools that can be an issue when I have more than one timer trigger function (but what is the maximum recommended count of timer trigger functions?). There are also some recommendations regarding timer trigger function, but they are not fully understandable for fixing this issue. 
Also, it's too complicated I can't open Timer Trigger Issue Analysis in the azure function diagnostic tool 
![image](https://user-images.githubusercontent.com/20381930/152777174-6afaab7e-9e3b-48a4-8c5d-709cb35a0326.png)

**Comment by tkachuk2222** [comment]
@jsquire can you reopen the issue?
