### ISSUE TITLE
[How to migrate language studio project along with blob content from one environment (DEV/QA) to another(QA/PROD)]

### ISSUE THREAD

**Issue by bibhutimoharana** [Azure/azure-sdk-for-net#26726]
### Library name and version

azure.ai.textanalytics.5.2.0-beta.2

### Query/Question

We have created a "Custom Named Entity Recognition ( Custom NER)" project in Language Studio. We are using the Text Analytics SDK version (azure.ai.textanalytics.5.2.0-beta.2). We are trying to migrate the language studio project from one environment(DEV/QA) to another(QA/PROD) along with its blob contents. 

Is there any way available to migrate the projects from one environment (DEV/QA) to another(QA/PROD) along with its blob contents ?

Note : - we are using the below mentioned block of codes to analyze the text from the document.
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/tests/samples//Sample9_RecognizeCustomEntitiesAsync.cs

### Environment

We are hosting our application in Azure and using dot net 5 version to build our application along with Azure AI form recognizer 3.1.1 and Azure AI Text Analytics 5.2 beta 2.

**Comment by jsquire** [comment]
Hi @bibhutimoharana.   Thank you for reaching out and we regret that you're experiencing difficulties.   Apologies, but I'm not sure that I understand your scenario.  When you say "migrate from one environment to another" - are you talking about exporting the project and then importing from another Azure subscription?

Can you talk a bit more about the details of what you'd like to do so that I can better understand?

**Comment by bibhutimoharana** [comment]
> Hi @bibhutimoharana. Thank you for reaching out and we regret that you're experiencing difficulties. Apologies, but I'm not sure that I understand your scenario. When you say "migrate from one environment to another" - are you talking about exporting the project and then importing from another Azure subscription?
> 
> Can you talk a bit more about the details of what you'd like to do so that I can better understand?

Hi jsquire,

Thanks for your quick response. 

In our project we are using the Azure AI Text Analytics SDK to extract the SKU codes embeded in descriptions of the user's PO files.

Before this we are following these below mentioned steps.
**Step 1-> Creating storage account for different environment.
Step 2->Creating container inside the storage account.
Step 3->uploading the text files having different SKU codes inside the container.
Step 4->Creating a language studio and pointing to the created container.
Step 5->Creating a new project inside the language studio.
Step 6->Mapping SKU codes present inside the text files within the container.** 

After these steps only our application will be able to recognize those mapped and similar type SKU codes.  

While deploying our application in different environment (QA and PROD), we need to migrate those above mentioned (Step1-Step6) in QA and PROD. This migration should get automated so that there will not be any manual task. 

Is there any way available that we can migrate those steps (Step1-Step6) in QA and PROD ?
Is there any way to do this migration using the Devops Pipeline Powershell script ?

Please guide us on this.

**Comment by vhhughes** [comment]
@jsquire, do we know whether the MSFT product teams has plans for GA to include either a export/import option or a "migrate" from one Text Analytics resource to another (as with Form Recognizer) option? This seems an obvious "must" for it to be productionalized.

**Comment by jsquire** [comment]
@vhhughes - I do not have that insight, unfortunately.   I can only speak to the SDK.  As mentioned above, your best path to an answer to that would be opening a support request so that the folks best positioned to answer roadmap questions for Language Studio and the service can assist.
