### ISSUE TITLE
Need more explanation about Tags being deprecated

### ISSUE THREAD

**Issue by Qythyx** [Azure/azure-sdk-for-net#26727]
The page says the Tags property is deprecated, but it should say more, like what the recommended alternative is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a166671a-58ff-28c0-9dd0-034f618f2acf
* Version Independent ID: 547abe8c-ce47-fb4b-e7b7-01014d11eb18
* Content: [InstallationTemplate.Tags Property (Microsoft.Azure.NotificationHubs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.installationtemplate.tags?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.NotificationHubs/InstallationTemplate.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.NotificationHubs/InstallationTemplate.xml)
* Service: **notification-hubs**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@Qythyx Thanks for the feedback. I am checking internally for any alternatives and get back to you on the same.

**Comment by SaurabhSharma-MSFT** [comment]
@Qythyx Here is the idea behind deprecating the Tags from Templates -
In the registration model, each template is separate and has its own set of tags. One control’s which template is targeted by setting tags appropriately.
In the Installation model, the idea is that the Installation itself owns the set of tags. The template is a child resource that inherits all of the tags from the installation. Targeting is provided by further providing the name of the template. For that reason, one should use the tags associated with the [Installation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.notificationhubs.installation.tags?view=azure-dotnet), not individual templates on Installations.

Please let me know if you have any other questions.

Thanks
Saurabh

**Comment by Qythyx** [comment]
@SaurabhSharma-MSFT , thanks for the explanation. I think this makes sense, but I could not find any documentation that explained it clearly.
