### ISSUE TITLE
[BUG] TableEntity.GetString throwing method not found error

### ISSUE THREAD

**Issue by saipramod** [Azure/azure-sdk-for-net#26721]
### Library name and version

Azure.Data.Tables:12.3.0

### Describe the bug

```
         if (lastProcessedEntry == null)
            {
                var firstEntry = new TableEntity(partitionKey, rowKey)
                {
                    { LastProcessedEntry, lastProcessedTime.ToString("s", System.Globalization.CultureInfo.InvariantCulture) },
                };

                await tableClient.UpsertEntityAsync<TableEntity>(firstEntry);
            }
            else
            {
                var entryIsNotNull = !string.IsNullOrEmpty(lastProcessedEntry.GetString("LastProcessedEntry"));
                if (entryIsNotNull)
                {
                    lastProcessedTime = DateTime.Parse(lastProcessedEntry.GetString("LastProcessedEntry"));
                }
            }

```
Above is the code snippet to retrieve a table entity and further retrieve "LastProcessedEntry" column. This works locally and has been working in azure until recently. This code was touched in over 6 months.

Below is the error thrown :
Method not found: 'Void System.BinaryData..ctor(System.Object, System.Text.Json.JsonSerializerOptions, System.Type)'.

### Expected behavior

To return the value in the column as a string

### Actual behavior

Exception is thrown - Method not found: 'Void System.BinaryData..ctor(System.Object, System.Text.Json.JsonSerializerOptions, System.Type)'.

### Reproduction Steps

I am not sure how to reproduce this as this doesnot  / never happens locally. 

### Environment

Production

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @saipramod - Could you provide the full stack trace from the exception? Also, could you provide any details about the environment where the code is deployed that is throwing this error?
