### ISSUE TITLE
Add note that DeleteItemAsync() ignores ItemRequestOptions.EnableContentResponseOnWrite 

### ISSUE THREAD

**Issue by colgreen** [Azure/azure-sdk-for-net#26739]
This is a follow on from  https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3011

When setting ItemRequestOptions.EnableContentResponseOnWrite = true, this has no effect when calling DeleteItemAsync(), because the underlying Cosmos DB API does not support returning the deleted resource. See:

https://docs.microsoft.com/en-us/rest/api/cosmos-db/delete-a-document#body

The APi is a little misleading/confusing, because the return type is `Task<ItemResponse<T>>`, where `T` is the resource type; but ItemResponse.Resource will always be null regardless.

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea1d216a-5adc-ec81-3272-e7c3ce41450c
* Version Independent ID: f12b659b-5a79-73dc-5746-67b6673d5b70
* Content: [Container.DeleteItemAsync&lt;T&gt;(String, PartitionKey, ItemRequestOptions, CancellationToken) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.deleteitemasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@colgreen Thanks for the feedback! We will review and update accordingly.
