### ISSUE TITLE
[QUERY] Obtaining the workspace id and authentication id of a log analytics instance

### ISSUE THREAD

**Issue by unruledboy** [Azure/azure-sdk-for-net#26735]
### Library name and version

Microsoft.Azure.Management.Fluent 1.0.0.70

### Query/Question

In order to set the configuration for log analytics of our projects, we would need to obtain the workspace id and authentication id of any specific log analytics instance.

We noticed there is https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.containerinstance.fluent.models.loganalytics?view=azure-dotnet which it mentions workspace id and workspace key, and it looks like what we are after. But the ContainerInstanceManagementClient in ContainerInstance does not seem right. And we could not find out how exactly to obtain that LogAnalytics object.

In Azure portal, it is like this:

![image](https://user-images.githubusercontent.com/682883/152056902-7cfd2ed7-d1db-46df-97bb-5ac5cd7fb642.png)

### Environment

Hosting platform or OS and .NET runtime version: Windows 10, .NET Core 3.1
IDE and version : Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by unruledboy** [comment]
hi @ArthurMa1978  do you have any idea on this? thx

**Comment by unruledboy** [comment]
I finally figured it out after finding this https://stackoverflow.com/questions/56881373/how-to-get-the-workspace-id-of-an-azure-log-analytics-workspace-via-c-sharp.

Basically we will use `OperationalInsightsManagementClient`:

```
var client = new OperationalInsightsManagementClient(your_credentials) { SubscriptionId = "your subscription id" };
var workspace = await client.Workspaces.GetAsync("your-resource-group", "name of workspace");
Console.WriteLine(workspace.CustomerId);
var keys = await client.SharedKeys.GetSharedKeysAsync("your-resource-group", "name of workspace);
Console.WriteLine(keys.PrimarySharedKey);
```
