### ISSUE TITLE
[QUERY] Is Azure Front Door Standard/Premium (Preview) available in the sdk yet?

### ISSUE THREAD

**Issue by coppercosmo** [Azure/azure-sdk-for-net#26732]
### Library name and version

Microsoft.Azure.Management.FrontDoor 4.0.0

### Query/Question

Is Azure Front Door Standard/Premium (Preview) available in the sdk yet? It seems when I create a Front Door with the above library's version it defaults to creating it as a Classic Front Door, and there is no option (as of 02/01/2022) to create the Standard or Premium Front Doors.

### Environment

Azure Front Door
Visual Studio Enterprise 2022 17.0.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by coppercosmo** [comment]
@ArthurMa1978 any update on this?

**Comment by ArthurMa1978** [comment]
@coppercosmo the new https://www.nuget.org/packages/Azure.ResourceManager.Cdn/ support them
