### ISSUE TITLE
[QUERY] Migrating from .NET Core 3.1 to .NET 6, Functions v3 to v4, RenewLockAsync indicates "The supplied lock is invalid"

### ISSUE THREAD

**Issue by Prinsn** [Azure/azure-sdk-for-net#26733]
### Library name and version

Azure.Messaging.ServiceBus 7.5.1

### Query/Question

I might be missing something here as to how you cross migrate a "receiver" but the rest of the code appears to work up to this, where it always seems to fail to renew the message lock.

Looked at documentation regarding setting for host/startup options for `MaxAutoLockRenewalDuration`, but the documentation indicates that it is for batch message receivers (these handle one at a time), and should be set _higher_ than the lock duration, where as we previously had to rely on a keep alive strategy because max lock duration setting we could achieve was a 5 minute lock, where as we can have functions that run atomic DB operations that can take over 15 minutes, so we have a task running to just ping the server to say "yeah, we're still working on it"

Appears to happen locally as well as in deployed to Azure (both communicate with the ServiceBus backing Queue in Azure)

# 3.1 / Microsoft Azure
```cs
        [FunctionName(FUNCTION_NAME)]
        public async Task Run(
            [ServiceBusTrigger(TOPIC_NAME, SUBSCRIPTION_NAME, Connection = SB_CONN_STR)]
            string mySbMsg,
            MessageReceiver messageReceiver,
            string lockToken)
        {
```
Renew
```cs
protected void SetupAutoLockRenewal(MessageReceiver messageReceiver, string lockToken)
{
    await messageReceiver.RenewLockAsync(lockToken).ConfigureAwait(false);
}
```
# 6 / Azure Messaging
Function 
```cs
        [FunctionName(FUNCTION_NAME)]
        public async Task Run(
            [ServiceBusTrigger(TOPIC_NAME, SUBSCRIPTION_NAME, Connection = SB_CONN_STR)]
            ServiceBusReceivedMessage mySbMsg,
            ServiceBusMessageActions messageActions)
        {
```
Renew
```cs
protected void SetupAutoLockRenewal(ServiceBusReceivedMessage msg)
{
    var options = new ServiceBusClientOptions { TransportType = ServiceBusTransportType.AmqpWebSockets };
    await using var serviceBusReceiver = new ServiceBusClient(serviceBusConnectionString, options)
        .CreateReceiver(topic, subscription);
    await serviceBusReceiver.RenewMessageLockAsync(msg).ConfigureAwait(false);
}
```

Thrown Exception
```
 Azure.Messaging.ServiceBus.ServiceBusException
  HResult=0x80131500
  Message=The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:e486c410-a481-4804-af48-9073cce3c8ac, TrackingId:d4d5cdee-2f0a-4866-9275-b351bb7efa6f_B32, SystemTracker:*:Topic:*.func.import, Timestamp:2022-02-01T20:16:33 (MessageLockLost)
  Source=Azure.Messaging.ServiceBus
  StackTrace:
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<RenewMessageLockInternalAsync>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<RenewMessageLockAsync>b__57_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<RenewMessageLockAsync>d__57.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<RenewMessageLockAsync>d__62.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<RenewMessageLockAsync>d__61.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  ```

### Environment

Azure Function App
Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Prinsn** [comment]
I'm not certain what the failure point is here, exactly, as we have evidence (still working on reproduction) that the message was unlocked and returned to the queue and picked up by another trigger instance which caused something to break.

**Comment by JoshLove-msft** [comment]
It looks like you are trying to create a new client and a new receiver to renew the message lock, which won't work. We will be adding the ability to renew the message lock from the actions in an upcoming release.
https://github.com/Azure/azure-sdk-for-net/issues/26402

**Comment by Prinsn** [comment]
@JoshLove-msft Noted, but is there a mitigation strategy?  I was pointed to the setting mentioned above which does not sound like it does what is needed based on the documentation, both suggesting batch message handling and wanting it to be set higher than the lock duration.

**Comment by Prinsn** [comment]
@JoshLove-msft I've tried using the option to set the MaxAutoLockRenewalDuration and remove the manual method and I stll sometimes see this error, and there is evidence that the messages are being consumed multiple times instead of being retained.

**Comment by Prinsn** [comment]
It appears to be coming from
`await messageActions.DeadLetterMessageAsync(msg, props).ConfigureAwait(false);` 
in our error handler

**Comment by JoshLove-msft** [comment]
As stated in the docs, MaxAutoLockRenewalDuration doesn't apply

> The primary page for host.json states
> 
> > This only applies for functions that receive a batch of messages.
> 
> Our functions consume one message per triggered instance, and the topic / queue receives singular messages. Not certain what is or is not a batch in this context.

This is backwards - the setting applies only to functions that receive a single message, as noted in the ref docs - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Config/ServiceBusOptions.cs#L75. I will get the host.json doc updated. Thanks for pointing this out.

**Comment by JoshLove-msft** [comment]
> It appears to be coming from `await messageActions.DeadLetterMessageAsync(msg, props).ConfigureAwait(false);` in our error handler
> 
> @JoshLove-msft The specific case this was just observed at is the exact case that we are trying to solve with the manual unlocking that the suggested fix does not appear to address.
> 
> 1. Service Bus has message added
> 2. Function consumes message
> 3. Function calls SQL
> 4. SQL times out
> 5. Error handler catches timeout exception
> 6. Error handler attempts to deadletter the message
> 7. Deadletter is rejected due to lock expiration
> 
> And now the message is retried instead of put into our deadletter handler.

Since your function only accepts a single message, using the MaxAutoLockRenewalDuration _should_ work. Are you seeing the error occur before this amount of time has elapsed?

**Comment by Prinsn** [comment]
I'm going to be taken away from this upgrade to work on bugs, so I can't
verify, but since it's a SQL call timeout, I'm assuming.

It's possible there are missing settings changes we need to implement,
because what we have now was the solution to long running SQL (not even
timeouts) over running the lock, and losing it.

I have the auto lock set to 1 minute, and I know the SQL timeout isn't that
short.

**Comment by JoshLove-msft** [comment]
> I have the auto lock set to 1 minute, and I know the SQL timeout isn't that
short.

If the timeout is longer, can you try setting the MaxAutoLockRenewalDuration to a larger value?

**Comment by Prinsn** [comment]
@JoshLove-msft I'll give this a try when I can, but am I intuiting correctly that the behavior of this setting is that "if this is set, automatically renew lock, and do so up until this duration" rather than it being an instruction of how often to auto renew?

I'm not sure if we determined there was any specific value to having a shorter renew period at this point (two years ago decision that went untouched afterward)

**Comment by Prinsn** [comment]
Okay, I assumed so and bumped it way up, coworker said he was going to try
to test it while I'm on stuff.

Is there any issue with having it set arbitrarily high?

**Comment by JoshLove-msft** [comment]
The main risk with having it be arbitrarily high is that depending on your function's dependencies and how it is implemented, you could end having the message be locked for an arbitrarily long time, if some downstream dependency is taking an arbitrarily long time. If you have other consumers of the queue, they would not be able to process the message. If you don't have other consumers, then I don't think there would be much downside to setting it this way, as the lock renewal will stop once your function returns control.

**Comment by Prinsn** [comment]
Okay, cool, we will proceed with the understanding that this should solve
the problem.

Our function executions are largely atomic, so they need to handle their
own failure and not time out, so that seems like we would have no negative
interactions

**Comment by Prinsn** [comment]
I am not certain how to isolate it, but it appears the locks are not being
honored.

One long running consumer has been shown to trigger a second instance of
the function, which is causing it to do duplicate work over top of itself
and fail.

Is there any way to debug this or any other steps to check?

I can solve this with good ol fashion elcode grease, but I feel like it
isn't working not that it needs fixing

**Comment by Prinsn** [comment]
@JoshLove-msft  This is a bit concerning.  In continuing testing by killing the duplicate function calls, I've gotten it to "keep going" but then this:

The function runs for 30 minutes and fails
`[2022-02-03T00:42:45.220Z] Timeout value of 00:30:00 exceeded by function '*' (Id: '2c5ac0d3-dc9d-42f0-8f16-57999773da27'). Initiating cancellation.`

Now, I am assuming I can increase this timeout value by some mechanism, but the problem is that this failure kills the entire debug instance (which is a web project + 2 function projections).  This is unrelated to the issue presented (so can spin off into anything else), but it seems like an extreme and ungraceful exception, and does not appear to allow for any handling to be done on part of the code.

**Comment by Prinsn** [comment]
Looking around for settings, it appears that a Topic Subscription's `Max Lock Duration` setting is capped at 5 minutes.

My coworker who did a bulk of the work fiddling with the functions before says that this setting stands for the maximum amount of times a message lock will stand before renewing, but we were using manual renewal to manage this.

How do we even investigate the "automatic behavior" before reporting any kind of bug?  Presentationally, it currently seems that the auto locking behavior specified by `MaxAutoLockRenewalDuration` either does not do anything, requires a paired setting to be abled, or ceases to auto renew as of the normal lock duration.

**Comment by Prinsn** [comment]
For a conventional client https://stackoverflow.com/questions/63585687/azure-service-bus-how-to-renew-lock/67837282#67837282 shows the inclusion of an async lambda, no idea if it is significant in any way, but I don't know that there's an analog here.
```cs
processor.ProcessMessageAsync += async arg =>
{
    //process your message
    await Task.Delay(Timeout.Infinite);
};
```

**Comment by Prinsn** [comment]
This auto lock renewal stuff is super fishy.  All the similar SO posts related to it are basically "it doesn't work" "oh wait okay it works now" with no known changes.  It was still happening today but then it seems to have stopped happening with no code changes to cause it to happen.

This unreliableness is extremely concerning.

**Comment by JoshLove-msft** [comment]
> One long running consumer has been shown to trigger a second instance of
the function, which is causing it to do duplicate work over top of itself
and fail.

Can you clarify what you mean here? Are you saying that the function is being triggered with the same message that you thought was already locked in another invocation? Do the messages have the same sequenceNumber?

**Comment by JoshLove-msft** [comment]
> Looking around for settings, it appears that a Topic Subscription's `Max Lock Duration` setting is capped at 5 minutes.

This is the max lock duration without any lock renewal. You can keep renewing the lock for as long as you'd like.

**Comment by JoshLove-msft** [comment]
> For a conventional client https://stackoverflow.com/questions/63585687/azure-service-bus-how-to-renew-lock/67837282#67837282 shows the inclusion of an async lambda, no idea if it is significant in any way, but I don't know that there's an analog here.
> 
> ```cs
> processor.ProcessMessageAsync += async arg =>
> {
>     //process your message
>     await Task.Delay(Timeout.Infinite);
> };
> ```

I think the post is just highlighting that you can set the max auto lock renewal duration to infinite, and providing this message handler is a way to verify that it is working. You wouldn't want to have this in your message handler in practice, but rather whatever your processing logic is.

**Comment by Prinsn** [comment]
> > One long running consumer has been shown to trigger a second instance of
> > the function, which is causing it to do duplicate work over top of itself
> > and fail.
> 
> Can you clarify what you mean here? Are you saying that the function is being triggered with the same message that you thought was already locked in another invocation? Do the messages have the same sequenceNumber?

I am debugging and testing with exactly one message through a pipeline of consumers that should basically hand off work as they complete it, and nothing else should happen.

After multiple failed debug sessions, I've put breakpoints at the start of the `Run` function so that I can be absolutely sure when things are triggered, and the function will trigger a second time while the first one is running.  I have not interrogated the messages for their own information, but they contain the same internal GUID we use, which implies either A) the message was generated twice (this has been verified as false in Azure for the subscription, it is shown to contain only one message) or B) that it is the same message.

**Comment by Prinsn** [comment]
As of somewhere around 1-2 PM EST, it seems to suddenly be working, and I'm only getting a duplicate trigger instance at basically the exact moment of function timeout (which is acceptable.

However, since this behavior has been implicitly observed in the deployed testing environment (errors produced that only happen when automatic lock renewal fails) it's going to be hard to sign off on that the upgrade to .NET 6 is stable.

**Comment by Prinsn** [comment]
`host.json`
`functionTimeout` setting set to `-1` does not appear to work, still getting the default behavior of 30 minutes.

Is there some issue with the consumption of these settings to that there are cached values that are overwriting the programmatic/configuration settings that lead to these strange behaviors?

**Comment by Prinsn** [comment]
Continued oddities:

I added in a log for elapsed time to execute every 10 seconds so that I'd be able to better observe what was happening.

despite having an hour long timeout set in host.json, we're still seeing 30 second default being used...

But the function was only running for 21 minutes when the entire function host was violently terminated due to the Console App throwing its own unhandle-able exception outside of my code (as mentioned above).

**Comment by JoshLove-msft** [comment]
Would you be able to share your host.json file (omitting any potentially sensitive information)?

**Comment by Prinsn** [comment]
@JoshLove-msft 
This is as is, nothing to redact
```json
{
  "functionTimeout": "01:00:00",
  "version": "2.0",
  "logging": {
    "logLevel": {
      "Azure.Messaging.ServiceBus": "Warning",
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Warning"
    }
  }
}
```

**Comment by Prinsn** [comment]
I'm being told by a coworker that the host.json setting hasn't ever worked and that the `local.setting.json` has to have the proprety
`AzureFunctionsJobHost__functionTimeout`

**Comment by Prinsn** [comment]
Okay, so, upside, whatever issues were being caused in either case regarding the auto lock appear to have all shaken out.  I'm not sure if there's anything to even look into for the team, but it is very suspicious that anyone that seems to have problems with the auto locking observes it, then it eventually resolves itself.

It is a bugbear of a problem because there's no way to really report it other than as described, and unless there's just glaringly obvious code that could cause it to happen, I cannot imagine trying to trace it down, as anyone trying to help anyone with the problem cannot reproduce it.
