### ISSUE TITLE
[QUERY] How to stop function log spam in console app for .NET 6 / V4 functions

### ISSUE THREAD

**Issue by Prinsn** [Azure/azure-sdk-for-net#26740]
### Library name and version

Azure.Messaging.ServiceBus 7.5.1

### Query/Question

Previous version (NET Core 3.1), we could watch the consoles and follow app behavior, now almost all of the console output is functionally spam.

I want to filter out
```
[2022-02-01T23:49:22.524Z] topic/Subscriptions/function-480d862d-84c0-4355-b2ca-3617ee49eb8f: ReceiveBatchAsync done. Received '0' messages. LockTokens =
[2022-02-01T23:49:23.876Z] topic/Subscriptions/function-480d862d-84c0-4355-b2ca-3617ee49eb8f: ReceiveBatchAsync start. MessageCount = 1
```
Which occur at least 100 per function
and
```
[2022-02-01T23:52:30.582Z] Request [1a524b29-cbb5-4e18-aa28-cc84d04e08b0] PUT http://127.0.0.1:10000/devstoreaccount1/azure-webjobs-hosts/locks/user-858520082/host?comp=lease
[2022-02-01T23:52:30.587Z] x-ms-lease-action:renew
[2022-02-01T23:52:30.587Z] x-ms-lease-id:0000000000000000000000002C8741E3
[2022-02-01T23:52:30.588Z] x-ms-version:2020-08-04
```
which is less frequent but still relatively significant pollution.

I've tried modifying the host.json from Default "debug", to only display information
```json
  "logging": {
    "logLevel": {
      "Default": "Information",
      "System": "Information",
      "Microsoft": "Warning"
    }
  }
```
and it didn't reduce logging, and I'm afraid that if we reduce the logging level further that we're just going to be obfuscating the information we want, because we used to be able to see when a function picked up a message and then when it marked it as complete, as well as internal logging data.

### Environment

.NET 6
VS 2022

**Comment by jsquire** [comment]
Hi @Prinsn.  Thank you for reaching out.   To change the log detail that you're seeing for Service Bus or other Azure SDK packages, you'll need to configure their levels independently.   For example, if you wanted to restrict Service Bus to just warnings and errors, you'd use something similar to:

```json
"Logging": {
  "LogLevel": {
    "Default": "Information",
    "System": "Information",
    "Microsoft": "Warning"
    "Azure.Messaging.ServiceBus": "Warning"
  }
}
```

There's a bit more context in the discussion on #25865, if you're interested.

**Comment by Prinsn** [comment]
You and Josh are really doing serious work with this repo.

**Comment by ben-002** [comment]
Hello!
I've noticed that upgrading the Microsoft.Azure.WebJobs.Extensions.ServiceBus NuGet package version affects my service bus triggered function live Monitor logs.
Starting the 5.0.0. version, the live stream is either slow or incomplete if I select the **ApplicationInsights** logs. However, when using **FileSystem** logs, they are fine, the stream of logs is live and complete.
Additionally, if I look in what Application Insights resource actually stores, the logs are present. It doesn't look like a logging level matter, more like a display in live Monitor(Application Insights logs) one.

I've open a ticket here: [Microsoft.Azure.WebJobs.Extensions.ServiceBus](https://github.com/Azure/Azure-Functions/issues/2151) but discovered later on that this may have something to do with the package version.

Is this something known? Or solvable?
