### ISSUE TITLE
The `Message` class is part of `Microsoft.Azure.ServiceBus` which is now deprecated what replaces the Message class?

### ISSUE THREAD

**Issue by sumitkm** [Azure/azure-sdk-for-net#26751]
I keep going round in circles when upgrading Microsoft.Azure.WebJos.Extensions to 4.0.1. It says `Message` not found for the following code that was working with version `Microsoft.Azure.WebJos.Extensions` v3.x.y (where x.y is the last latest version) 

```

namespace My.Function.Timers
{
    using System;
    using System.Text;

    using Microsoft.Azure.ServiceBus;
    using Microsoft.Azure.WebJobs;
    using Microsoft.Azure.WebJobs.ServiceBus;
    using Microsoft.Extensions.Logging;
    using Microsoft.Extensions.Options;

    using My.App.Models.Domain.MessageBus;
    using My.Function.Models;
    using My.Function.Settings;

    using Newtonsoft.Json;

    public class AsynchronousTasksExpiredLocks
    {


        [FunctionName("AsynchronousTasksExpiredLocks")]
        public void Run([TimerTrigger("%my_TimerCronAsynchronousTasksExpiredLocks%", RunOnStartup = false, UseMonitor = false)]TimerInfo myTimer,
            [ServiceBus(Settings.ScheduledTaskQueue, Connection = "my_MyBus", EntityType = ServiceBusEntityType.Queue)] out Message sbQueue, ILogger log)
        {
            var functionName = "AsynchronousTasksExpiredLocks";
            log.LogInformation($"Azure Timer trigger function {functionName} called at: {DateTime.UtcNow}");
            var message = new ScheduledTask { TaskType = ScheduledTaskType.AsynchronousTasksExpiredLocks };
            var payload = JsonConvert.SerializeObject(message);
            var body = Encoding.UTF8.GetBytes(payload);
            var msg = new Message(body);
            msg.UserProperties.Add("Serializer", "json");
            sbQueue = msg;
        }
    }
}
```

I filed an issue with the code samples repository and it was closed as won't fix. Almost like packages have been deprecated but no one at Microsoft wants to touch the samples or documentation because it is too much work!

Someone please point me to the latest code amongst the millions of "open source" repositories that supposedly has Azure SDK documentation!!!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1f3b7b45-dd75-5704-45f9-df02956bebca
* Version Independent ID: 2e7ff35c-3c1d-901d-22cc-1e5726f061db
* Content: [Message Class (Microsoft.Azure.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.message?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.ServiceBus/Message.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.ServiceBus/Message.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @sumitkm.  Thank you for reaching out and we regret that you're experiencing difficulties.   Can you please share what version of the `Microsoft.Azure.Webjobs.Extensions.ServiceBus` package you're using?

**Comment by sumitkm** [comment]
I think I found it... https://docs.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre 

Someone update it from pre to live please.

My above code can be modified to the following to get it compiling with latest `Microsoft.Azure.Webjobs.Extensions.ServiceBus` `v5.2.0`. I'll test to see if it runs as expected or not.

`Message` has be replaced with `ServiceBusMessage` and needs to use `Azure.Messaging.Service` (the library is imported as part of `Micrsoft.Azure.Webjobs.Extensions`. 

```

namespace My.Function.Timers
{
    using Azure.Messaging.ServiceBus;
    using Microsoft.Azure.WebJobs;
    using Microsoft.Azure.WebJobs.ServiceBus;
    using Microsoft.Extensions.Logging;
    using My.App.Models.Domain.MessageBus;
    using My.Function.Settings;
    using Newtonsoft.Json;
    using System;
    using System.Text;

    public class AsynchronousTasksExpiredLocks
    {
        [FunctionName("AsynchronousTasksExpiredLocks")]
        public void Run([TimerTrigger("%my_TimerCronAsynchronousTasksExpiredLocks%", RunOnStartup = false, UseMonitor = false)]TimerInfo myTimer,
            [ServiceBus(Settings.ScheduledTaskQueue, Connection = "my_MyBus", EntityType = ServiceBusEntityType.Queue)] out ServiceBusMessage serviceBusMessage, ILogger log)
        {
            var functionName = "AsynchronousTasksExpiredLocks";
            log.LogInformation($"Azure Timer trigger function {functionName} called at: {DateTime.UtcNow}");
            var message = new ScheduledTask { TaskType = ScheduledTaskType.AsynchronousTasksExpiredLocks };
            var payload = JsonConvert.SerializeObject(message);
            var body = Encoding.UTF8.GetBytes(payload);
            var msg = new ServiceBusMessage(body);
            msg.ApplicationProperties.Add("Serializer", "json");
            serviceBusMessage = msg;
        }
    }
}
```

Thanks @jsquire .
