### ISSUE TITLE
Publish to App Service freezes when using parallell build

### ISSUE THREAD

**Issue by Turochamp** [Azure/azure-sdk-for-net#2675]
Publish to Azure App Service freezes during the build when using parallel builds.

**Recreate:**
1. Publish to MS Azure App Service in Visual Studio.
2. Web Publish Activity will freeze
3. Cancel button in panel is ignored, instead cancel with "Ctril+Break". 

**Workaround:**
Avoid project freeze by either: 
1) Disable parallel building by setting "Maximum number of parallel builds" to 1
or
2) Enable verbose logging

**Comment by shahabhijeet** [comment]
@Turochamp can you provide us some more specific information.
Can you provide the name of the SDK (dll name that you are using, this helps in routing to the right team)
Can you also provide more granular steps for reproducing this issue (e.g. what project type in Visual Studio, anything specific to Azure settings that we might want to know before publishing to Azure)

**Comment by markcowl** [comment]
Closing for lack of clarification.  Also, the VS tools are not shipped from this repository
