### ISSUE TITLE
[QUERY] adding application permission to an active directory application

### ISSUE THREAD

**Issue by unruledboy** [Azure/azure-sdk-for-net#26769]
### Library name and version

Microsoft.Azure.Management.Fluent 1.0.0.70

### Query/Question

Hi,

With IAzure.AccessManagement.ActiveDirectoryApplications, we can create the active directory application via the code in (#26586  ), but when we try to add an application permission, we could not find the interface. The IActiveDirectoryApplication interface only returns a readonly list of application permission via ApplicationPermissions property.

But in IActiveDirectoryApplication.Update(), it does not have option to add application permission. Does it support so?

I noticed there is IActiveDirectoryApplication.Inner.Oauth2Permissions.Add(permission) function, but if I do like below, still nothing happens. I think it's not working like I expected because I believe there should be a subsequent function to apply the changes:

```
app.Inner.Oauth2Permissions.Add(permission);
await existingApp.Update()
          .ApplyAsync();
```

Then I found out that we could use PatchAsync:

```
var oauth2Permissions = fooListOfOAuth2Permission;
await azure.AccessManagement.ActiveDirectoryApplications.Inner.PatchAsync(appObjectId, new ApplicationUpdateParameters(oauth2Permissions: oauth2Permissions));
```

But it gave bad request error, without any details:

> Microsoft.Azure.Management.Graph.RBAC.Fluent.Models.GraphErrorException: 'Operation returned an invalid status code 'BadRequest''

We know for powershell, we can use https://docs.microsoft.com/en-us/powershell/module/azuread/new-azureadapplication?view=azureadps-2.0 by passing Oauth2Permissions the parameter to achieve this. Just not sure how to do so with the Azure SDK.

Thanks,
Wilson

### Environment

Hosting platform or OS and .NET runtime version: Windows 10, .NET Core 3.1
IDE and version : Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by unruledboy** [comment]
Ok, after a few more rounds of test, I figured it out:

- We have to pass all the existing API scopes (oauth2 permission)
- We have to set the consent display name & description for user & admin if the type is user.

Like this:
```

                const string ApiPermissionTypeUser = "User";
                var oauth2Permissions = new List<OAuth2Permission>(app.Inner.Oauth2Permissions);
                oauth2Permissions.AddRange(apiScopes.Select(x => new OAuth2Permission
                {
                    IsEnabled = true,
                    Type = ApiPermissionTypeUser,
                    Value = x.Scope,
                    UserConsentDisplayName = x.Title,
                    UserConsentDescription = x.Title,
                    AdminConsentDescription = x.Title,
                    AdminConsentDisplayName = x.Title,
                    Id = SdkContext.RandomGuid()
                }));

                await azure.AccessManagement.ActiveDirectoryApplications.Inner.PatchAsync(app.Id, new ApplicationUpdateParameters(oauth2Permissions: oauth2Permissions));

```
