### ISSUE TITLE
Flakey Timeout Tests: Azure.Monitor.OpenTelemetry.Exporter.OfflineStorageTests

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#26783]
### Library name

Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

Azure.Monitor.OpenTelemetry.Exporter.OfflineStorageTests.FailureResponseCode206
Azure.Monitor.OpenTelemetry.Exporter.OfflineStorageTests.FailureResponseCode429
Azure.Monitor.OpenTelemetry.Exporter.OfflineStorageTests.Success200

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1344288&view=ms.vss-test-web.build-test-results-tab

**Comment by christothes** [comment]
In addition some of these tests contain long sleeps that should be avoided.

**Comment by annelo-msft** [comment]
This is failing the Azure.Core release pipeline, so I will disable these temporarily.

**Comment by TimothyMothra** [comment]
I think this work item can be closed.
I refactored these tests in #28664
