### ISSUE TITLE
❓Survey: Your experience in this repo

### ISSUE THREAD

**Issue by lilyjma** [Azure/azure-sdk-for-net#26789]
Whether you're a frequent visitor or a relatively new visitor of the repo, please tell us about your experience with our issue support and/or PR contribution process. The survey should only take a few minutes, and you can answer for up to 3 repos:

https://www.surveymonkey.com/r/8QTQTGJ?Source=azure-sdk-for-net

**Comment by AlexGhiondea** [comment]
Please let this issue pinned on this repo.

**Comment by lilyjma** [comment]
Thank you for your interest in the experience survey. The survey has been closed.
