### ISSUE TITLE
[QUERY] Set platform / reply url type for Active Directory application

### ISSUE THREAD

**Issue by unruledboy** [Azure/azure-sdk-for-net#26796]
### Library name and version

Microsoft.Azure.Management.Fluent 1.0.0.70

### Query/Question

In the manifest of Azure AD application, we can see reply url supports (platform) type:
```
	"replyUrlsWithType": [
		{
			"url": "https://foo-url.azurewebsites.net/swagger/oauth2-redirect.html",
			"type": "Web"
		},
		{
			"url": "http://localhost",
			"type": "Web"
		}
	],
```

And the Azure portal would show like this:

![image](https://user-images.githubusercontent.com/682883/152491536-94ecbddd-b5d5-4858-90e6-7378dc7162d9.png)

Related to #26586 ,  while creating an Active Directory application, or updating it, how can we specify the (platform) type of the reply url?

I tried to do like this while updating the application, it does not support specifying the type.

```
                var appUpdate = app.Update();
         
                foreach (var replyUrl in replyUrls)
                {
                    appUpdate = appUpdate.WithReplyUrl(replyUrl.Url);
                }

                await appUpdate.ApplyAsync();
```

According to https://stackoverflow.com/questions/58685870/how-to-specify-replyurlswithtype-programmatically , looks like I need to use the graph API to do the patch.

### Environment

Hosting platform or OS and .NET runtime version: Windows 10, .NET Core 3.1
IDE and version : Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by unruledboy** [comment]
Finally, based on https://docs.microsoft.com/en-us/graph/api/application-update?view=graph-rest-1.0&tabs=csharp, I had to use graph api to achieve this:

```
var graphClient = new GraphServiceClient(you_auth_provider);
var newApplication = new Graph.Application
                {
                    Spa = new Graph.SpaApplication { RedirectUris = spaUrls },
                    Web = new Graph.WebApplication { RedirectUris = webUrls }
                };

await graphClient.Applications["id-of-the-application"]
            .Request()
            .UpdateAsync(newApplication);
```
