### ISSUE TITLE
[BUG] SAS does not work for Table Storage

### ISSUE THREAD

**Issue by vinodshinde** [Azure/azure-sdk-for-net#26791]
### Library name and version

Azure.Data.Tables

### Describe the bug

SAS Generated for Table Storage does not work. It gives following error.

**Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.**

Please check attached code sample.

### Expected behavior

Generated SAS should be accepted and it should return entities from the Table Storage.

### Actual behavior

Following error is thrown.
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:76394065-8002-00f4-5668-190393000000
Time:2022-02-04T01:45:12.7943495Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed

Content:
{"odata.error":{"code":"AuthenticationFailed","message":{"lang":"en-US","value":"Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:76394065-8002-00f4-5668-190393000000\nTime:2022-02-04T01:45:12.7943495Z"}}}

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 76394065-8002-00f4-5668-190393000000
x-ms-error-code: REDACTED
Date: Fri, 04 Feb 2022 01:45:12 GMT
Content-Length: 299
Content-Type: application/json

### Reproduction Steps

Please run code below. It's a .Net 6 console app.
Use your table storage account and keys.

````
// See https://aka.ms/new-console-template for more information
using Azure.Data.Tables;
using Azure.Data.Tables.Sas;

Console.WriteLine("Hello, World!");

//This is legacy Azure Table Storage account and NOT CosmosDb Table account
// I am trying to migrate from deprecated WindowsAzure.Storage SDK 
string accountName = "table-storage-account-name";
Uri endPointUri = new Uri("https://table-storage-account-name.table.core.windows.net");
string accountKey = "ACCESS KEY FOR ACCOUNT";
string tableName = "MyTableName";

var credential = new TableSharedKeyCredential(accountName, accountKey);

var tableClient = new TableClient(endPointUri, tableName, credential);

var tableSasBuilder = tableClient.GetSasBuilder(TableSasPermissions.Read | TableSasPermissions.Update | TableSasPermissions.Add | TableSasPermissions.Delete,
                                                DateTime.UtcNow.AddMinutes(30));
tableSasBuilder.PartitionKeyStart = "MyPartitionKey";
tableSasBuilder.PartitionKeyEnd = "MyPartitionKey";

var tableSasUri = tableClient.GenerateSasUri(tableSasBuilder);

var tableClientWithSas = new TableClient(tableSasUri);

var items = tableClientWithSas.Query<TableEntity>();

foreach (var item in items)
{
    System.Diagnostics.Debug.WriteLine(item.PartitionKey);
}

````

### Environment

Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @vinodshinde - The problem here seems to be with the casing of the table name. If you change your tableName to "tablename" the query will succeed. Although the service [treats table names as case-insensitive] (https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#table-names) I believe any representation of the name in the SAS creation must be lower case. I'll look into a proper fix, but in the meantime, using lowercase table names should allow you to work around the problem.

**Comment by vinodshinde** [comment]
Hello @christothes - Changing the table name to lower case resolved the issue. Thanks for your help.
