### ISSUE TITLE
Support Azure SDK conventions in Azure Monitor OTel exporter

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#26797]
### Library name

Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

Azure Monitor exporter should support Azure SDK conventions for messaging services.

Mappings to Microsoft common-schema are defined here  
https://github.com/microsoft/common-schema/blob/main/Mappings/AzureSDKs.md

**Comment by vishweshbankwar** [comment]
This is completed.
