### ISSUE TITLE
Need to add missing AzureLocation static references into Azure.Core

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#26809]
### Library name

Azure.Core

### Please describe the feature.

We need to add the remaining AzureLocation static instances to Azure.Core so we can get rid of the RegionalAuthority class in Azure.Identity and use the common definition in Azure.Core.

Related PR for the Azure.Identity changes https://github.com/Azure/azure-sdk-for-net/pull/26322

**Comment by christothes** [comment]
closed via #27283
