### ISSUE TITLE
Consolidate IsSample and IsSamplesProject

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#26814]
I don't think we need both of these properties.
https://github.com/Azure/azure-sdk-for-net/search?q=issample
https://github.com/Azure/azure-sdk-for-net/search?q=issamplesproject

**Comment by pallavit** [comment]
@JoshLove-msft do you know why we have 2 in the first place? Was it just a natural progression, looking at the build props file, I think both are pretty interchangeable.

**Comment by JoshLove-msft** [comment]
IsSamples was used by KeyVault and then copied by Service Bus. IsSamplesProject is the common eng sys value.
