### ISSUE TITLE
[Question]What's the meaning of "The link 'xxx' force detached. Code: publisher(linkxxx). Details: AmqpMessagePublisher.IdleTimerExpired: Idle timeout: 00:10:00"

### ISSUE THREAD

**Issue by QiangL** [Azure/azure-sdk-for-net#26824]
### Library name and version

Microsoft.Azure.ServiceBus 5.0.0

### Query/Question

Hi, azure-sdk-for-net friends

We use Azure service bus and recently we got a error message which need your help to understand better. thank you.

The error message like this:
```
Failed to send message to Service Bus due to exception: 
The link 'G4:9962303:88e1bcd9-360e-47ee-9625-3fb0286a4c2d;28:57:58:source(address:*outTopicAddress*):*outTopicName*' 

**is force detached**. Code: publisher(link2207). Details: AmqpMessagePublisher.IdleTimerExpired: Idle timeout: 00:10:00**., 

stack:   
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)

// delete some stack message
```

I searched and found this page https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-troubleshoot#link-is-closed

It tell me that the error is a standard behaviors, but I'm still confused.
The troubleshoot say
> You can avoid them by making send/receive calls on the connection/link, which automatically recreates the connection/link.

At first, I thought the exception is only a "warning", service bus will send message successfully for me, but then I realized
as the exception throw out, I have to retry by myself and then the message will send successfully.

I'm confused, as this exception can avoid after retry(Do I understand right?), why need customer code do that rather than handle the exception inside service bus sdk?

What's the meaning when exception `The link 'xxx' force detached. Code: publisher(linkxxx). Details: AmqpMessagePublisher.IdleTimerExpired` happen, does it means something wrong in my code, and what should I do to avoid this kind of exception or just retry is enough?

Thanks for your help!

### Environment

Hosting platform linux
.NET version: dotnetcoreapp3.1

**Comment by MughundhanRaveendran-MSFT** [comment]
@QiangL , Thanks for reaching out. I will check and get back to you.

**Comment by QiangL** [comment]
genteelly ping, any update?

**Comment by MughundhanRaveendran-MSFT** [comment]
@QiangL , Thanks for the follow-up. I will provide an update tomorrow

**Comment by MughundhanRaveendran-MSFT** [comment]
@QiangL , Thanks for your patience.

As mentioned in the article, it is a standard behavior and you can avoid them by making send/receive calls on the connection/link, which automatically recreates the connection/link.

Sometimes sending a message could fail which is a rare edge scenario and a transient one. You will have to retry the send message. If you see the link becoming idle and sending messages fails consistently, then please let me know.

**Comment by QiangL** [comment]
Thanks your reply.
In my case yes,  it's a transient  failure.
So nothing but retry I can do when getting such exception.

But if the exception can simply avoid by a retry, could it done by Service Bus library instead of our customer code in future ?

**Comment by MughundhanRaveendran-MSFT** [comment]
@QiangL , Thanks for the update. Actually, the exception can be avoided by sending the message. What you experienced was a transient issue ( common in the Cloud world) that would be resolved by a retry. Retry should be done from the client side.

I hope this helps.

**Comment by MughundhanRaveendran-MSFT** [comment]
Closing this issue. Feel free to reopen if you have any further queries
