### ISSUE TITLE
[BUG] Service Bus Extensions: Potential issue with entity path for subscriptions

### ISSUE THREAD

**Issue by superwalnut** [Azure/azure-sdk-for-net#26837]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.1

### Describe the bug

I have created a web job function for service bus topic trigger ,as I obtain the connection string from azure (the connection string will contain a entity path).

I have looked into the source code of service bus and found out, during the `ServiceBusTriggerAttributeBindingProvider` is creating `ServiceBusListener`, it is using `EntityNameFormatter.FormatSubscriptionPath(topicName, subscriptionName)` to build a entity path in a format of "{topic-name}/Subscription/{subscription-name}"

so I trace it back to this method `CreateBatchMessageReceiver()` is having the issue, when it is creating the `client.CreateReceiver(entityPath, options))`, 

if you look at the override of that method, it treats the `entitypath` as queue name.

Shouldn't it be using 

`CreateReceiver(string topicName, string subscriptionName, ServiceBusReceiverOptions options);`

### Expected behavior

`CreateReceiver(string topicName, string subscriptionName, ServiceBusReceiverOptions options);`

### Actual behavior

`CreateReceiver(string queueName, ServiceBusReceiverOptions options);`

### Reproduction Steps

as described in the description

### Environment

windows 10, dotnet 6

**Comment by jsquire** [comment]
Hi @superwalnut.  Thank you for your feedback and we regret that you're experiencing issues.  Apologies, but I'm not sure from your description what issue you're observing with your Function.  I believe that you may be saying that you aren't seeing the trigger not invoke your Function when messages are available for the subscription.  Is that correct?  If not, can you please help us understand the behavior that you're seeing that you believe is a problem?

**Comment by JoshLove-msft** [comment]
Hi @superwalnut,
Can you include the signature of your function so that we can help diagnose the issue?

**Comment by superwalnut** [comment]
sorry I forgot to mention the symptoms, so basically I have the signature of using ServiceBusReceivedMessage[] and it actually throwed exception somewhere and got swallowed by WebJob.

This my function signature. Hope that helps.

Thank you for spending time and look into this.

        public async Task ProcessArticleDeltaRetryMessage(
            [ServiceBusTrigger("%ServiceBusWebJobOption:TopicName%", "%ServiceBusWebJobOption:SubscriptionName%", Connection = "ServiceBusWebJobOption:ConnectionString")]
            ServiceBusReceivedMessage[] messages,
            ServiceBusMessageActions messageActions,
            [ServiceBus("%ServiceBusWebJobOption:TopicName%", ServiceBusEntityType.Topic, Connection = "ServiceBusWebJobOption:ConnectionString")] IAsyncCollector<ServiceBusMessage> messageSender
            )

**Comment by JoshLove-msft** [comment]
Could you share what the exception is?

**Comment by superwalnut** [comment]
there isn't actually an exception (I was suspecting the exception was thrown and swallowed). 

And exactly like jsquire said, we aren't seeing the trigger invoke the Function when messages are available for the subscription. but instead if we replace it with single message ServiceBusReceivedMessage, it triggers just fine.

And the above description is what I have traced back to.

**Comment by JoshLove-msft** [comment]
> there isn't actually an exception (I was suspecting the exception was thrown and swallowed).
> 
> And exactly like jsquire said, we aren't seeing the trigger invoke the Function when messages are available for the subscription. but instead if we replace it with single message ServiceBusReceivedMessage, it triggers just fine.
> 
> And the above description is what I have traced back to.

Can you enable Verbose logging and include the output? If there is an exception being thrown somewhere it should be getting logged.

**Comment by superwalnut** [comment]
Nope, I didn't catch anything.

Could you try to reproduce it by creating a topic, and copy the connection string from your azure portal (include the entitypath), then create your webjob trigger function and listening to the batch messages, i.e. ServiceBusReceivedMessage[], you will notice, you are not getting any messages.

Pretty straight forward if you would like to try that.

**Comment by JoshLove-msft** [comment]
I was able to repro the issue - it looks like it is related to the call that you pointed out @superwalnut. Since we use the receiver overload for creating the message receiver, we end up validating that the subscription name is the same as the topic name from the entityPath section of the connection string, which of course it isn't. As a workaround, you can remove the entityName from your connection string. Thanks for reporting this!

**Comment by superwalnut** [comment]
Thank you Josh for fixing it up. At the mean time we will be using the single message trigger, till you guys address this issue. The connection string is from terraform directly obtained from azure key vault, so for the best  not to fiddle with the connection string manually.
