### ISSUE TITLE
[Text Analytics] Prototype Abstraction for Interactions with Generated Code

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#26856]
# Summary

The Text Analytics service is being reorganized, resulting in breaking changes which will be organized into two distinct sets of endpoints.  In order for the client library to support these changes in a non-breaking manner, it will need the ability to interact with both the old and new service endpoints based on the version requested for the `TextAnalyticsClient`.    

In support of this, the Text Analytics client library will need:

- The ability to interact with the client API without a hard dependency on any types specific to a single service version.
- Support for two generated layers, one for each set of service endpoints, living side-by-side and scoped for non-public visibility.
- An abstraction allowing the client API to perform version-specific translations and invoke the correct generated client for the service version.

# Scope of Work

- Prototype an approach for abstracting calls between the two generated layers; using the requested service version, the `TextAnalyticsClient` should be able to select the needed generated layer and interact with it a neutral way that does not require insight into the specific implementation.

- Apply the abstraction layer to the generated code for the old service endpoints.

- Refactor the `TextAnalyticsClient` to make use of the abstraction layer when interacting with the old service endpoints.

# Out of Scope

- Abstracting the new generated layer; the client will continue to be make use of the old generated layer via the abstraction.

- Incorporating the new endpoint or interacting with the new generated layer.

- Updating tests to target both the old and new service endpoints.

# Success Criteria

- The `TextAnalyticsClient` has been updated to work with the abstraction, making use of the generated layer for the old service endpoints without being strongly bound to the generated API.

- No changes to the public API were detected.

- Any new tests needed for validation have been created, produce deterministic results, and pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

**Comment by maririos** [comment]
@jsquire If I understand this issue correctly, this is what you are currently working on, right?
