### ISSUE TITLE
getQueueRuntimeProperties 

### ISSUE THREAD

**Issue by 23min** [Azure/azure-sdk-for-net#26852]
When using `GetQueueRuntimeProperties` on a `Microsoft.Azure.ServiceBus.Management.ManagementClient`, I receive a `runtimeInfo` object with the following properties:

![image](https://user-images.githubusercontent.com/1111124/153026061-60f29a2a-ee1d-4703-b76f-aa0591753116.png)

I expect the MessageCount property to equal the sum of the counts in MessageCountDetails.

The query is performed on a Premium Service Bus resource. 
"Microsoft.Azure.ServiceBus" Version="5.1.3"
The messages are created 2021-01-26

Service Bus Explorer shows the same discrepancy:

![image](https://user-images.githubusercontent.com/1111124/153030152-b58cdefc-ae4b-44b5-98a9-a0a44fd919e9.png)

On another entity, it is correct:

![image](https://user-images.githubusercontent.com/1111124/153027985-626ea2a3-9ca8-402f-870e-24c3663140e0.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c44bf4d1-ff3c-ce52-7079-7af4284276a9
* Version Independent ID: 3fb992f8-25a9-699b-79a4-a01dc850f810
* Content: [QueueRuntimeInfo Class (Microsoft.Azure.ServiceBus.Management) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.management.queueruntimeinfo?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.ServiceBus.Management/QueueRuntimeInfo.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.ServiceBus.Management/QueueRuntimeInfo.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SatishBoddu-MSFT** [comment]
Hello @23min Thanks for the feedback,

I have tried "Microsoft.Azure.ServiceBus" **Version="5.2.0"**, Just FYI, this Package is Deprecated!

![image](https://user-images.githubusercontent.com/62923178/153096953-af7ad43a-c661-4e3d-b5da-210ab72825ef.png)


I have used the managementClient.**GetQueueRuntimeInfoAsync**("queueName");
And I don't see any differences in my entity, with respect to the Queue Message Count!!! even the Service Bus Explorer was also showing the same count!

![image](https://user-images.githubusercontent.com/62923178/153097399-058f36e9-ab08-4f22-b39e-b18b98467e85.png)

Is there any difference between the 2 Queues which you are using? You may want to share if this issue is consistent with both the Queues? or it may be inconsistent.

Similar SO thread for Reference: [Difference between Messages and Active Messages in Azure Service bus](https://stackoverflow.com/questions/62393341/difference-between-messages-and-active-messages-in-azure-service-bus)

> Message count - total messages in the queue with various statuses (scheduled, deferred, dead-lettered, in transfer, transfer dead-lettered). Active messages - messages available for receiving and processing.

Please let us know if this helps or do you need further help in this regard!

**Comment by paolosalvatori** [comment]
@clemensv is there anyone in the Service Bus team that can look into this? This issue clearly is due to the client library and not to the Service Bus Explorer. Thanks

**Comment by 23min** [comment]
When I go into the Azure Portal for the resource and use the Service Bus Explorer (preview), all message counts are zero. 
When I use the library or the desktop Service Bus explorer, MessageCount > 0 while the other counts are 0.
And when I consume from the entity, I can receive the messages! 

This is a resource we use for testing that I need to take down, but I feel that it contains valuable state right now that may be needed for troubleshooting. There are a number of entities with discrepancies (either on the resource or incorrectly reported by the library). 

I can send a resource Id in case someone wants to take a look.

**Comment by 23min** [comment]
Another clue is that at one point in time, ActiveMessageCount equaled the current value in MessageCount.
Seems like the value is cached somewhere on the resource. The API exist for performance reasons iirc, så I would guess there is back-end support for it.

**Comment by 23min** [comment]
@SatishBoddu-MSFT 
> Is there any difference between the 2 Queues which you are using? You may want to share if this issue is consistent with both the Queues? or it may be inconsistent.

All entities are set up identically with default properties.

**Comment by SatishBoddu-MSFT** [comment]
Hello @23min Thanks for the detailed information on this.

We are now routing this to the right team for further action!!!

**Comment by jsquire** [comment]
Hi @23min.  Initial investigation determined that the behavior that this inquiry is regarding is not one under the influence or control of the Service Bus client library - it is that of Service Bus itself.  Unfortunately,  this repository is focused on the Azure SDK for .NET and we're unable to assist with other Azure issues.  

The service team does not monitor nor respond to issues here; though we've made them aware of this issue, we won't see updates here.  Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

Apologies for the long delay, the correct process was not followed for assisting with this issue; it should not have been left waiting after it was determined that this was a service issue.  I'm going to close this out, as there is no way to assist further from this repository.
