### ISSUE TITLE
Propose design for Delay concept type to be used by all wait centric types

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#26851]
### Library name

Azure.Core

### Please describe the feature.

See https://github.com/Azure/azure-sdk/issues/3841#issuecomment-1029433201 for details.

**Comment by annelo-msft** [comment]
@christothes, can we close this now that we have [DelayStrategy](https://apiview.dev/Assemblies/Review/77bdbcef49a3465fa96fac3fb745bf57#Azure.Core.DelayStrategy)?

**Comment by christothes** [comment]
yes!
