### ISSUE TITLE
It should be noted ReadManyItemsStreamAsync is unordered

### ISSUE THREAD

**Issue by brianasu-notdoppler** [Azure/azure-sdk-for-net#26878]
[Enter feedback here]
It should be noted ReadManyItemsStreamAsync is unordered. It will not match the order of the list passed in,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 819245a4-835a-64aa-d195-60871cacc13c
* Version Independent ID: 5cabd119-cec0-b932-0311-cb739ac51939
* Content: [Container.ReadManyItemsStreamAsync(IReadOnlyList&lt;ValueTuple&lt;String,PartitionKey&gt;&gt;, ReadManyRequestOptions, CancellationToken) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.readmanyitemsstreamasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@brianasu-notdoppler Yes, you are correct, the results give the items in the ordered it is stored in Cosmos DB.
