### ISSUE TITLE
How to generate a non-SAS uri with custom Content-disposition in a public access container

### ISSUE THREAD

**Issue by Brutiquzz** [Azure/azure-sdk-for-net#26885]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Query/Question

Lets say we have a public container in which we store files where each blob is a file. 
Because we don't want to prompt the user every time they collide with another user's filename then we store the stream of data under a generated GUID BlobName and not the actual filename. We however upload the file with a custom content-disposition
so that the user will be able to recognize his or her file when downloading it.
```
var blobClient = _containerClient.GetBlobClient(blobName);
var blobUploadOptions = new BlobUploadOptions()
{
   HttpHeaders = new BlobHttpHeaders() { ContentDisposition = "attachment; filename=\"" + $"{blobName}.{extension}" + "\"; filename*=UTF-8''" + Uri.EscapeDataString($"{fileName}.{extension}") }
};

await blobClient.UploadAsync(stream, blobUploadOptions);
```

Since we don't want our system to be the middle- man of downloading the file and then passing it on to the user then we want to construct a Uri with direct access to the blob in Azure blob storage and respects the custom content-disposition. This URI we 
then pass on to the user. 

However, using the Uri property of the BlobClient won't respect the custom content-disposition. 
```
var blobClient = _containerClient.GetBlobClient(blobName);
return blobClient.Uri.ToString();
```
This is odd though because retrieving the custom content-disposition after it has been uploaded yields the correct result.
![image](https://user-images.githubusercontent.com/33770011/153208508-c98e3e75-ef15-47af-b852-25b47f39b5e0.png)
As you can see in this picture the custom content-disposition is known to Azure blob storage but why is it not getting respected then? 

Is there really not a way to generate a non-SAS uri that will respect the custom content-disposition?

We have had success generating SAS Uris respecting the custom content-disposition in the past but in this case where the container is of blob public access type then generating shared access tokens is not what we want. 

### Environment

.NET 6

**Comment by SatishBoddu-MSFT** [comment]
Hello @Brutiquzz Thanks for the query.
We are routing this to the Service team to address the question.

**Comment by amnguye** [comment]
I'm confused what the whole scenario is, so apologies in advance for any assumptions I have made.

The storage service supports what you're looking for, due to limitations of how a REST call is supposed to function. The Content Disposition value is not supposed to be apart of the URL.

The Content Disposition is a request header field is separate from the URL
https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#request-headers-all-blob-types

and can be grabbed from doing a GetProperties or Download Blob
![image](https://user-images.githubusercontent.com/48961492/158460210-3f541335-1c0d-42b9-91a3-4e9caa344b7e.png)

I'm having trouble understanding this part of your statement
"..downloading the file and then passing it on to the user then we want to construct a Uri with direct access to the blob in Azure blob storage and respects the custom content-disposition. "

What do you mean respecting the content disposition?

**Comment by Brutiquzz** [comment]
For private containers  we create SAS Uris like this and forward to the user

```
BlobSasBuilder sasBuilder = new()
{
     BlobContainerName = blobClient.BlobContainerName,
     BlobName = blobClient.Name,
     Resource = "b",
     StartsOn = DateTimeOffset.UtcNow,
     ExpiresOn = DateTimeOffset.UtcNow.AddSeconds(10),
     IPRange = ipAddressRange,
     ContentDisposition = "attachment; filename=\"" + $"{blobName}.{extension}" + "\"; filename*=UTF-8''" + Uri.EscapeDataString($"{fileName}.{extension}")
};

sasBuilder.SetPermissions(BlobSasPermissions.Read);

var uri = blobClient.GenerateSasUri(sasBuilder);
```

In regards to ContentDisposition how will you achieve something similar for the public container. Creating SasUris with a lifetime of 900 years doesn't seem like an ideal approach. 

The `BlobUriBuilder` class doesn't seem to offer support for setting the ContentDisposition. 


I think one of my confusions is what is the point of uploading a ContentDisposition to Azure blob storage if it is not getting used ? My expectation was that from hence forth when getting a URI through a `BlobClient` then it would be one where the uploaded ContentDisposition was used.

Hope this clearifies things a little

**Comment by karol-gro** [comment]
Is there any update on this? Apparently, it's a property of the blobs which has been there for years and no documentation mentions it (see https://stackoverflow.com/questions/54207583/azure-blob-storage-v2-does-not-deliver-content-disposition-header-any-more )

So, is this the result of some decision (if so, why is this and will this be documented? Or is it a defect in Azure Blob Storage (if so, when can we expect it to be fixed)?
