### ISSUE TITLE
[BUG] ApplicationTokenProvider should reuse HttpClientHandler instead of creating it on every call

### ISSUE THREAD

**Issue by Obi-Dann** [Azure/azure-sdk-for-net#26884]
### Library name and version

Microsoft.Rest.ClientRuntime.Azure.Authentication 2.4.1

### Problem 

Every call to `ApplicationTokenProvider.LoginSilentAsync` creates a new `HttpClientHandler` that will only be used only for the duration of the call. 

This can easily lead to socket/port exhaustion.

The issue frequently creating and disposing `HttpClientHandler` explained in detail in [the official Microsoft docs](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net)
They mention `HttpClient`, but essentially the issue is with the `HttpClientHandler` that is created in `HttpClient` default constructor
> Though this class implements IDisposable, declaring and instantiating it within a using statement is not preferred because when the HttpClient object gets disposed of, the underlying socket is not immediately released, which can lead to a socket exhaustion problem. For more information about this issue, see the blog post [You're using HttpClient wrong and it's destabilizing your software](https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/).

**After `HttpClientHandler` is disposed, the underlaying socket connections are still active for some time.**

This issue caused (or contributed to) socket exhaustion on one of our production instances.
I also found a [related unanswered stackoverlfow issue](https://stackoverflow.com/questions/52727331/outbound-tcp-connection-issue-cause-be-sending-data-to-event-hub-and-data-lake-f) describing exactly that problem.

### Proposed solution

Most of the other azure sdk libraries provide a way to pass your own `HttpClient`. In our case, we use the default `HttpClientFactory` from ASP.NET that managers the lifetime of `HttpClientHandler` and clients.

There should be a way to pass `HttpClient` or `HttpManager` or something like that to `ApplicationTokenProvider.LoginSilentAsync` call.

The currently referenced version of `Microsoft.IdentityModel.Clients.ActiveDirectory` (4.3.0) does not support using IHttpClientFactory, [the creation of `HttpClientHandler` is hard coded](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/ced389750ba8a1e51ebef6fd9c5ec9c2fd70a526/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Internal/Http/AdalHttpMessageHandlerFactory.cs#L48)

However, an option to pass `IHttpClientFactory` was introduced from [version 5.0.1-preview](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/ADAL-v5.0.1-preview)

Here's a link to the instructions on [how to use `IHttpClientFactory` with ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Providing-an-HttpClient):
```cs
IHttpClientFactory myHttpClientFactory = new MyHttpClientFactory();

AuthenticationContext authenticationContext = new AuthenticationContext(
     authority: "https://login.microsoftonline.com/common",
     validateAuthority: true,
     tokenCache: <some token cache>,
     httpClientFactory: myHttpClientFactory);
```

That probably means changes to the following code and its callers to be able to pass `IHttpClientFactory`.
https://github.com/Azure/azure-sdk-for-net/blob/f9858eac647b7f48bf63c8fb87defa656e759147/sdk/mgmtcommon/Auth/Az.Auth/Az.Authentication/ApplicationTokenProvider.cs#L678-L687

### Workaround

I think I can replicate the behaviour of [this `ApplicationTokenProvider.LoginSilentAsync` overload](https://github.com/Azure/azure-sdk-for-net/blob/f9858eac647b7f48bf63c8fb87defa656e759147/sdk/mgmtcommon/Auth/Az.Auth/Az.Authentication/ApplicationTokenProvider.cs#L573-L583) in our codebase to be able to pass `HttpClientFactory` to `AuthenticationContext`, but it should be fixed at the package level.

### Expected behavior

It should be possible to pass `HttpClient` to `ApplicationTokenProvider.LoginSilentAsync` or to configure `ApplicationTokenProvider` to reuse `HttpClientHandler` to prevent socket exhaustion

### Actual behavior

It should not possible to pass `HttpClient` to `ApplicationTokenProvider.LoginSilentAsync` or to configure `ApplicationTokenProvider` to reuse `HttpClientHandler` to prevent socket exhaustion.
And it caused (or contributed to) a socket exhaustion in our production instance

### Reproduction Steps

Here's an example `Program.cs` that runs `LoginSilentAsync` in a loop and reports the count of active Tcp connections before and after each call.
Please note, the count always increases, the connections are not even released on application stop.

<details>
<summary>Program.cs</summary>

```cs
using System;
using System.Threading.Tasks;
using Microsoft.IdentityModel.Clients.ActiveDirectory;
using Microsoft.Rest.Azure.Authentication;

namespace HttpClientTestingTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var clientCredential = new ClientCredential("123", "345");

            for (var i = 0; i < 10; i++)
            {
                try
                {
                    ReportConnectionCount($"Before {i}");
                    await ApplicationTokenProvider.LoginSilentAsync("http://localhost/test", clientCredential, ActiveDirectoryServiceSettings.Azure);
                }
                catch
                {
                    ReportConnectionCount($"After {i}");
                }
            }
        }

        static void ReportConnectionCount(string info)
        {
            var properties = System.Net.NetworkInformation.IPGlobalProperties.GetIPGlobalProperties();
            Console.WriteLine($"ConnectionCount: {properties.GetActiveTcpConnections().Length} - {info}");
        }
    }
}
```

</details>

### Environment

The production issue was happening in Azure App Service
The reproduction on MacOS using netcore 3.1 and .NET 5.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by jsquire** [comment]
//fyi:  @ArthurMa1978

**Comment by anaismiller** [comment]
Thank you for sharing @Obi-Dann and in great detail! Code referenced does not belong to the AppAuthentication Library (our code is [here](https://github.com/Azure/azure-sdk-for-net/tree/f9858eac647b7f48bf63c8fb87defa656e759147/sdk/mgmtcommon/AppAuthentication). @jsquire to re-assign.

**Comment by Obi-Dann** [comment]
Hi @christothes, we're using `Microsoft.Azure.Management.Media` v2, but I believe the latest v3 also requires `ApplicationTokenProvider.LoginSilentWithCertificateAsync` according to the [How-To docs](https://docs.microsoft.com/en-us/azure/media-services/latest/configure-connect-dotnet-howto). The client requires an instance of `ServiceClientCredentials` in the constructor. 
I can probably migrate to use `Azure.Identity`... Probably, I'd need to manually assign authorization header on a custom HttpClient to pass it to `AzureMediaServicesClient` 🤔

**Comment by ArthurMa1978** [comment]
Unfortunate the ClientRuntime is in maintenance mode , we will not do any changes except security issue.
So I encourage to use our new track 2 sdk which the namespace starts from 'Azure.ResourceManager' which is a brand new design and much [better](https://devblogs.microsoft.com/azure-sdk/introducing-the-new-azure-sdk-resource-management-libraries-for-net/) than the old track 1 sdk .  Currently it's  still beta but will go GA soon.
