### ISSUE TITLE
Blob tests not running on Net461

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#26881]
During the Build & Test step, I see this error:
   NUnit failed to load D:\a\_work\1\s\artifacts\bin\Azure.Storage.Blobs.Tests\Release\net461\Azure.Storage.Blobs.Tests.dll
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1353384&view=logs&j=45f79b3a-2624-51cc-bc09-5c8a7cc7b4c9&t=a5b29a05-b133-5d99-2802-d1ab9b116429&l=120

You can see from the dashboard, that 3k fewer tests are running for Net461:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1353384&view=ms.vss-test-web.build-test-results-tab

I'd expect that the test run would fail if one of the assemblies failed to load, but it is still marked as passing.

**Comment by weshaggard** [comment]
@JoshLove-msft Yes that definitely seems odd. It looks like it failed to load the test assembly, not sure why, and that caused Nunit to not find and run any tests. I suspect they don't fail on assembly loads but perhaps they should cases like this. I don't have any experience with this particular issue so I suggest you dig in a little further to see if you can track down what is happening.

**Comment by JoshLove-msft** [comment]
I haven't been able to repro this locally. I wonder if it could be related to the agents used on CI and the sheer number of tests in the blobs assembly.
