### ISSUE TITLE
[QUERY] How does ServiceBusClient coorespond with "Active Connections" in Azure Metrics

### ISSUE THREAD

**Issue by chris-skuvault** [Azure/azure-sdk-for-net#26886]
### Library name and version

Azure.Messaging.ServiceBus 7.5.1

### Query/Question

I have a question about the "Active Connections" metric that I see about service bus. From my understanding a ServiceBusClient should open 1 Active AMPQ connection. Our implementation is using 11 clients. 2 for receiving and 9 for sending. In the metrics I often see connections opening and closing sometimes the Active Connections gets up to 11 as expected but a lot of the time they are lower around 9 or 10. 

I'd like to know a little more about how the ServiceBusClient opens a connection. Does it close them due to inactivity or something like that? Trying to understand what we are seeing with respect to "Active Connections" metrics in Azure.

### Environment

.net 5

**Comment by jsquire** [comment]
Hi @chris-skuvault.   Thank you for reaching out.   I can't speak to metrics reported by the Service Bus service, but I'm happy to discuss the client behavior.   You're correct in that each `ServiceBusClient` represents a connection which is shared by any senders, receivers, or processors spawned from it.   This is not true of the `ServiceBusAdministrationClient` which uses an HTTP-based API.

Instantiating a client does not establish a connection immediately; connections are lazily initialized, created or reconnected when a call is made the requires a network operation.   In the case that a connection is faulted or closed, the Service Bus clients will implicitly attempt to reconnect when a network operation is required.  As a general rule, if a `ServiceBusClient` or a sender, receiver, or processor spawned from it is actively being used, a connection to the service will actively be maintained - though you should expect to see some open/close activity.

The Service Bus clients have an idle timeout of 60 seconds, which is used to configure the .NET networking stack.  Behavior differs per framework and operating system; in some cases, like netcoreapp3.1 on Linux, the connection is closed when idle.  On others, it is not.   I can't speak to the specifics in-depth, as it is a behavior of the host environment and not part of the SDK.

The Service Bus service also performs some connection management activities; these are service implementation details that can change, and my knowledge may not be completely accurate as a result.   The service will force-close connections that have been idle for a period of time; to my knowledge, this is 20 minutes.  Every ~30 minutes, the service will force-close connections whether active or not and require the client to reconnect.  I believe there are some heuristics associated to ensure that high-throughput scenarios aren't disrupted.
