### ISSUE TITLE
[QUERY] Service Bus:  Message `Size` property

### ISSUE THREAD

**Issue by yogirajdeshpande** [Azure/azure-sdk-for-net#26880]
### Library name and version

Azure.Messaging.ServiceBus 7.5.1

### Query/Question

Hi Team,
  Why Size property is removed from 7.0.0-preview.3 versions and not documented anywhere. It is not available in 7.5.1 the latest version. How to get the total size of the message body in bytes?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
While I don't have insight to answer the first part of your question, measuring the size of a message body can be done by:

```csharp
var sizeInBytes = messgage.Body.ToMemory().Length;
```

I'm not sure what your intent is, but it is important to note that the size of the payload is not equivalent to the size of a message.  The size of a message depends on its AMQP-serialized format and isn't something that can reliably be estimated by an application.  If you're looking to understand if a message is too large to send, or are trying to group messages together to reduce the number of sends, the [ServiceBusMessageBatch](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusmessagebatch) exists for this purpose.  Its [TryAdd](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusmessagebatch.tryaddmessage) method will perform the needed measurement and return a boolean to indicate whether or not adding the message would exceed the size allowed by Service Bus.   A message batch is created by calling [CreateMessageBatchAsync](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebussender.createmessagebatchasync) on your sender.

**Comment by yogirajdeshpande** [comment]
Thank You! I just wanted to push Message size to the collection.
