### ISSUE TITLE
Default value for TableClient.Query maxPerPage?

### ISSUE THREAD

**Issue by Davidsv** [Azure/azure-sdk-for-net#26888]
How many entities are retrieved per page by default if maxPerPage is not specified? And what is the maximum per page?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7039465b-7064-61e8-a67a-d76b7d560fde
* Version Independent ID: 0339dba9-29e7-a70d-3a62-97f70175d9a5
* Content: [TableServiceClient.Query Method (Azure.Data.Tables) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.data.tables.tableserviceclient.query?view=azure-dotnet)
* Content Source: [xml/Azure.Data.Tables/TableServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Data.Tables/TableServiceClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by christothes** [comment]
Sure - we could do that. Out of curiosity, is there a scenario you ran into where understanding these defaults and limits was necessary? If the limits are exceeded, I believe you'll get immediate feedback as a 401 response from the service.

**Comment by Davidsv** [comment]
Thanks! In particular I'm worried whether the default value yields less entities per page than the maximum allowed by the service. This could potentially have affected performance and cost due to increased number of network transactions. Also it could affect the cost because each transaction is billed.

**Comment by christothes** [comment]
> Thanks! In particular I'm worried whether the default value yields less entities per page than the maximum allowed by the service. This could potentially have affected performance due to increased number of network transactions. Also it could affect the cost because each transaction is billed.

I see. The default value imposes no restriction on the items per page, and so the maximum allowed by the service will be sent. Perhaps this is a better clarification to add to the client docs?

**Comment by Davidsv** [comment]
Yes, unless the service itself decides to send something else than the maximum when there is no value specified. If that won't happen in practice, I think it would be good enough.
