### ISSUE TITLE
[BUG] AzureCliCredential incorrectly says that user is not logged in when authorizing without consent

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#26894]
### Library name and version

Azure.Identity

### Describe the bug

1. Create Web API app in non-Microsoft tenant 
2. Register the app in the tenant, but do not grant consent to authorize
2. Login into Azure CLI
3. Call AzureCLiCreddential.GetToken (with the non-Microsoft tenantId)

Result: the call fails with 
Azure.Identity.CredentialUnavailableException
HResult=0x80131500
Message=Please run 'az login' to set up account"

Now do:
az account get-access-token --output json --resource api://<app_id>

You will get:
AADSTS65001: The user or administrator has not consented to use the application with ID '<app_id>' named 'Microsoft Azure CLI'. Send an interactive authorization request for this user and resource.

### Expected behavior

Expected:
the error from GetToken should say something about the consent issue, not about login.

### Actual behavior

Azure.Identity.CredentialUnavailableException

### Reproduction Steps

see above

**Comment by swettstein** [comment]
any update on this? would be nice to get this prioritized
