### ISSUE TITLE
Missing point about Sessions?

### ISSUE THREAD

**Issue by LeszekKalibrate** [Azure/azure-sdk-for-net#26919]
This page does not show an example to code a trigger with Session enabled.
In version 4.x
        public async Task Run([ServiceBusTrigger("%QueueName%", Connection = "QueueConnectionString", IsSessionsEnabled = true)] Message message, IMessageSession messageSession, ILogger logger)
        
How to migrate it to new 5.2  with Azure.Messanging.Servicebus 7.5.x?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dab2626a-9579-fe2b-f11b-0ffec8666fcf
* Version Independent ID: 9f48d2bc-eda0-57e8-1ecd-a2489f1cb862
* Content: [Azure WebJobs Service Bus client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre)
* Content Source: [api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre.md)
* Service: **webjobs**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Related issue - https://github.com/Azure/azure-sdk-for-net/issues/24642
