### ISSUE TITLE
BlobClient page shows a method which is not in the method details page.

### ISSUE THREAD

**Issue by anandnara** [Azure/azure-sdk-for-net#26938]
[BlobClient ](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient?view=azure-dotnet) page shows a method DownloadContent(BlobDownloadOptions, CancellationToken) which has BlobDownloadOptions param but the [details ](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.downloadcontent?view=azure-dotnet#azure-storage-blobs-specialized-blobbaseclient-downloadcontent(azure-storage-blobs-models-blobdownloadoptions-system-threading-cancellationtoken)) page does not show up that method.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3653ab58-62b8-9eac-d2e5-b444c3e1da56
* Version Independent ID: c2c0cf2a-8e2a-d769-eada-fb4943e0db02
* Content: [BlobBaseClient.DownloadContent Method (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.downloadcontent?view=azure-dotnet#azure-storage-blobs-specialized-blobbaseclient-downloadcontent(azure-storage-blobs-models-blobdownloadoptions-system-threading-cancellationtoken))
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SatishBoddu-MSFT** [comment]
Hello @anandnara Thanks for the query!

The package documentation is under the beta version! I hope this helps!

[Azure SDK Releases](https://azure.github.io/azure-sdk/releases/latest/all/dotnet.html)

[Azure.Storage.Blobs.Models](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Storage.Blobs/12.11.0-beta.3/api/Azure.Storage.Blobs.Models.html)[BlobDownloadOptions](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Storage.Blobs/12.11.0-beta.3/api/Azure.Storage.Blobs.Models/Azure.Storage.Blobs.Models.BlobDownloadOptions.html)
![image](https://user-images.githubusercontent.com/62923178/153649461-7b2751bc-e447-42cb-b008-4682aa6481ee.png)

[Docs .NET API Reference Storage Blobs Azure.Storage.Blobs.Models BlobDownloadOptions](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobdownloadoptions?view=azure-dotnet-preview)

![image](https://user-images.githubusercontent.com/62923178/153649487-cbb023d7-9cb9-44b8-bede-849a6186f2bb.png)

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
