### ISSUE TITLE
Compute Module Documentation Incorrect Parsing of Line Endings and Breaks.

### ISSUE THREAD

**Issue by haagha** [Azure/azure-sdk-for-net#26937]
In the Az.Compute Module there are a lot of instances of incorrectly escaped line endings and breaks showing up as **&lt;li&gt**

This is showing up in documentation and has been pointed out to us by various customers. Please advise us on if this is a Swagger issue, and how we can fix this?

https://github.com/Azure/azure-docs-sdk-dotnet/blob/e6d5d173ebe06623700c29d06272e649f385be71/xml/Microsoft.Azure.Management.Compute.Models/VirtualMachine.xml#L622

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
The docs team need to fix it, will check with docs team later.
