### ISSUE TITLE
[BUG] Azure.ResourceManager.Sql build error with Azure.ResourceManager

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-sdk-for-net#26953]
### Library name and version

Azure.ResourceManager.Sql 1.0.0-beta.2

### Describe the bug

Azure.ResourceManager 1.0.0-beta.8 moved ResourceIdentifier to Azure.Core(https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager_1.0.0-beta.8/sdk/resourcemanager/Azure.ResourceManager/CHANGELOG.md), code uses Azure.ResourceManager.Sql now build error with Azure.ResourceManager 1.0.0-beta.8, the error is **Reference to type 'ResourceIdentifier' claims it is defined in 'Azure.ResourceManager', but it could not be found**

### Expected behavior

We can build code successfully with Azure.ResourceManager.Sql and latest Azure.ResourceManager

### Actual behavior

Build error: **Reference to type 'ResourceIdentifier' claims it is defined in 'Azure.ResourceManager', but it could not be found**

### Reproduction Steps

Create a .net 6.0 console app, add package Azure.ResourceManager 1.0.0-beta.8 and Azure.ResourceManager.Sql 1.0.0-beta.2, build following code.
```
var client = new ArmClient(new DefaultAzureCredential());
client.GetSqlServer(new ResourceIdentifier(""));
```

### Environment

.net 6.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
we didn't refresh the sql sdk to support beta.8 ResourceManager lib, will refresh all libs include sql soon.

**Comment by zhiweiv** [comment]
@ArthurMa1978 
Any timeline to share? We have used this sdk in some workloads, it is quite a problem for us now.

**Comment by zhiweiv** [comment]
Any update?

**Comment by zhiweiv** [comment]
New version released.
