### ISSUE TITLE
What are the plans for TimeSeriesInsights .NET library

### ISSUE THREAD

**Issue by Lillskogen** [Azure/azure-sdk-for-net#26954]
### Library name and version

Azure.IoT.TimeSeriesInsights 1.0.0-beta.1

### Query/Question

Hi,

We are currently using Time Series Insights Gen 1 and are planning on switching to Gen 2.
The .NET library for this (https://www.nuget.org/packages/Azure.IoT.TimeSeriesInsights/1.0.0-beta.1) has not been updated in 8 months and still is in beta.  Are there any plans on going beyond a pre-release?

What are your recommendations for integrating agains TSI Gen 2 with regards to feature support and long term maintainability. We are in a pure .NET environment and would welcome a .NET library but could also consume the REST API directly.

Best Regards,
Henrik

### Environment

Azure AppService with net6.0. Currently on windows but  moving to linux.
Visual Studio 17.0.4.

**Comment by SatishBoddu-MSFT** [comment]
Hello @Lillskogen Thanks for the query!

Indeed this is a great question, let me check with my team on this and get back with details on the Feature comparison at least I can help with...!

**Comment by SatishBoddu-MSFT** [comment]
Hello @Lillskogen

Please follow this official [Azure Updates page](https://azure.microsoft.com/en-us/updates/?category=iot&query=TSI) for further notifications on TSI.

[Azure Time Series Insights](https://azure.microsoft.com/en-us/services/time-series-insights/#product-overview)

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
