### ISSUE TITLE
[Form Recognizer] StartTrainingCanAuthenticateWithTokenCredential failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#26958]
Form Recognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Invalid model created with ID 9a3de5a4-105a-4fcd-9acb-829a1173b9ff
> Status: 200 (OK)
> ErrorCode: 2012
> 
> Additional Information:
> error-0: 2012: Managed Identity credential was rejected by the storage service.
> 
> Content:
> 
> Headers:
> ms-azure-ai-errorcode: REDACTED
> x-envoy-upstream-service-time: 29
> apim-request-id: 4965bb47-1544-4345-ad9b-3f7494069cbd
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Thu, 10 Feb 2022 07:03:34 GMT
> Content-Length: 335
> Content-Type: application/json; charset=utf-8
> 
> Data:
> error-0: 2012: Managed Identity credential was rejected by the storage service.
> 
> 
> Stack trace
>    at Azure.Core.OperationInternalBase.ApplyStateAsync(Boolean async, Response response, Boolean hasCompleted, Boolean hasSucceeded, RequestFailedException requestFailedException, Boolean throwIfFailed) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 207
>    at Azure.Core.OperationInternal`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 191
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 173
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 80
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 142
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 167
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 145
>    at Azure.AI.FormRecognizer.Training.CreateCustomFormModelOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormTrainingClient/CreateCustomFormModelOperation.cs:line 73
>    at Azure.AI.FormRecognizer.Tests.FormTrainingClientLiveTests.StartTrainingCanAuthenticateWithTokenCredential() in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormTrainingClient/FormTrainingClientLiveTests.cs:line 48
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1358155&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1354599&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1351376&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1347705&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Error still happening (2022/Feb/28): https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1399446&view=logs&j=75bb6cb8-85fe-5b08-10aa-320cf6c5cc8f&t=b18a6ae3-fe77-5f49-ecb4-5d3125e0bf5e&l=86713

**Comment by kinelski** [comment]
This error was transient and is not happening anymore. Closing this issue.
