### ISSUE TITLE
[QUERY] How to work with multiple subscriptions in Azure CLI when using DefaultAzureCredentials?

### ISSUE THREAD

**Issue by ProgrammingAwayOk** [Azure/azure-sdk-for-net#26964]
### Library name and version

Azure.Identity

### Query/Question

I am using DefaultAzureCredentials to get access to Azure Resources through my Azure CLI credentials.

It works fine for the Key Vault in Tenant A but when I need to access Graph API in a B2C tenant (that has also been created in Tenant A), the Graph API token seems to be generated for Tenant A, i.e. the Graph API can find users in Tenant A but not in the B2C tenant. 

This is happening despite me explicitly setting the  B2C tenant id when requesting the token. Note that if I manually change the default subscription in Azure CLI to the B2C tenant then the Graph API correctly works with the B2C tenant but the authentication to the Key Vault then fails.

Code for requesting Graph API token for B2C tenant:
```
var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { ExcludeSharedTokenCacheCredential = true });
var scopes = new[] { "https://graph.microsoft.com/.default" };
var token = credential.GetToken(new Azure.Core.TokenRequestContext(scopes, null, null, b2cTenantId));
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by ProgrammingAwayOk** [comment]
Hi, just wondering if there were any updates on this, please?

This seems like a fairly common requirement whenever you use a B2C tenant but I am struggling to find any relevant material.

**Comment by christothes** [comment]
Hi @ProgrammingAwayOk  - In your scenario, how are you calling `GetToken` yourself for KeyVault? When using one of the Azure.Security.KeyVault.*` clients, it should handle OAuth challenges properly, which includes discovering the correct tenantId.
