### ISSUE TITLE
[QUERY] Custom Vision: Is there a way to avoid uploading images that were already uploaded?

### ISSUE THREAD

**Issue by nikoliano** [Azure/azure-sdk-for-net#26971]
### Library name and version

Azure.CognitiveServices.Vision.CustomVision

### Query/Question

Hi All, 

I am trying to use the available APIs to upload training images to be used with the customvision.ai website. I am wondering if there is a way to upload only images that are not currently uploaded to my custom vision project on customvision.ai? I would like to start the upload with all my available images but omit the upload for images that have already been uploaded in the past to customvision.ai. Thank you.

**Comment by SaurabhSharma-MSFT** [comment]
@nikoliano I don't think that is possible. Do you want to upload the images individually or in a batch?
