### ISSUE TITLE
Smoke Tests failing in release pipeline on AMQP dependency

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#26975]
See warning during Update script: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1363033&view=logs&j=89e62377-9e04-50bb-9899-0c18e3d4a884&t=7978ce10-122f-59be-b217-4ac0e9724e2f&l=23

Error message: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1363033&view=logs&j=89e62377-9e04-50bb-9899-0c18e3d4a884&t=3114b5f9-f077-51f2-8057-84079f417ac5&l=13

```
##[error]common/SmokeTests/SmokeTest/SmokeTest.csproj(0,0): Error NU1605: Detected package downgrade: Microsoft.Azure.Amqp from 2.5.10 to 2.5.6. Reference the package directly from the project to select a different version. 
```

Another package in the dependencies might be moving AMQP up and causing this conflict. 
 

This did not block the release.

**Comment by jsquire** [comment]
Closed by #26984
