### ISSUE TITLE
Update Version of Azure.Management.ManagementGroups to latest API version (04-01-2021)

### ISSUE THREAD

**Issue by git-thomasdolan** [Azure/azure-sdk-for-net#26978]
### Library name and version

Azure.Management.ManagementGroups

### Query/Question

Hello,

I am working on updating the PowerShell modules for Management Groups to use the latest API version. Upon looking at the [PS repo](https://github.com/Azure/azure-powershell/tree/main/src/Resources/Resources/ManagementGroups), it points to the dotnet SDK for Management Groups which looks like it hasn't been updated in a while. Can this be bumped up to the latest version? I can do it myself if I can be pointed in the right direction.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@git-thomasdolan contact the ManagementGroups team to ask for a upgrade

**Comment by ArthurMa1978** [comment]
The ManagementGroups is moved to https://www.nuget.org/packages/Azure.ResourceManager/
