### ISSUE TITLE
[QUERY] WhatIf deployments in new SDK

### ISSUE THREAD

**Issue by JayDZimmerman** [Azure/azure-sdk-for-net#26979]
### Library name and version

Azure.ResourceManager.Resources 1.0.0-beta.6

### Query/Question

In previous versions of the SDK, it was possible to create a "WhatIf" deployment and execute it, as below:

```
ResourcesManagementClient client = ...

var whatIf = new DeploymentWhatIf(
    new DeploymentWhatIfProperties(DeploymentMode.Incremental)
    {
        Template = "Template stuff here"
    }
);

await (await client.Deployments.StartWhatIfAsync("MyResourceGroup", "MyDeployment", whatIf)).WaitForCompletionAsync();
```

Does the newer version of the SDK have a similar mechanism?  I have found similar deployment classes, but they appear to be internalized.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you for reaching us, @Yao725  please take a look of this issue

**Comment by Yao725** [comment]
Hi @JayDZimmerman , we have provide the method `WhatIf` in this new package.

You can use it to test the deployment at the different scope, here is the sample code of the resource group:
```csharp
ArmClient armClient = new ArmClient(new DefaultAzureCredential());
Subscription subscription = await armClient.GetDefaultSubscriptionAsync();
ResourceGroup rg = (await subscription.GetResourceGroups().CreateOrUpdateAsync(true, "testRg", new ResourceGroupData(AzureLocation.EastUS))).Value;
DeploymentInput deploymentData = new DeploymentInput(new DeploymentProperties(DeploymentMode.Incremental)
{
    TemplateLink = new TemplateLink
    {
        Uri = "https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/azure-resource-manager/what-if/what-if-before.json"
    }
});
Deployment deployment = (await rg.GetDeployments().CreateOrUpdateAsync(true, "testDeployment", deploymentData)).Value;
DeploymentWhatIfProperties deploymentWhatIfProperties = new DeploymentWhatIfProperties(DeploymentMode.Incremental)
{
    TemplateLink = new TemplateLink
    {
        Uri = "https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/azure-resource-manager/what-if/what-if-after.json"
    }
};
var deploymentWhatIfOperation = await deployment.WhatIfAsync(true, string.Empty, deploymentWhatIfProperties);
```

In the above code snippet, I set the second parameter `location` of method `WhatIfAsync` to be `string.Empty` because this property is not allowed at resource group scope, but in other scopes like tenant it is required. You might need to pay attention to the value of this property at different scope.

By the way, if you want to use Template instead of TemplateLink, you can set its value like this:
```csharp
Template = JsonDocument.Parse(templateString).RootElement
```

**Comment by JayDZimmerman** [comment]
@Yao725 On line #11 of your example, does the deployment get executed?  Or is it merely creating the deployment, which can be executed at a later time?  That may be the root of my confusion:  my assumption was that calling "CreateOrUpdateAsync" on a deployment would initiate the deployment (which I didn't want since I was simply looking to generate the "WhatIf" scenario information).

**Comment by Yao725** [comment]
@JayDZimmerman Yes, on line 11 the deployment will get executed, I use this because I want to get the `WhatIf` info which comparing to an existing deployment. For you scenario, I think you can take following code in which no deployments get executed as example:
```csharp
ArmClient armClient = new ArmClient(new DefaultAzureCredential());
Subscription subscription = await armClient.GetDefaultSubscriptionAsync();
ResourceGroup rg = (await subscription.GetResourceGroups().CreateOrUpdateAsync(true, "testRg", new ResourceGroupData(AzureLocation.EastUS))).Value;
ResourceIdentifier deploymentIdentifier = Deployment.CreateResourceIdentifier(rg.Id.ToString(), "testDeployment");
Deployment deployment = armClient.GetDeployment(deploymentIdentifier);
DeploymentWhatIfProperties deploymentWhatIfProperties = new DeploymentWhatIfProperties(DeploymentMode.Incremental)
{
    TemplateLink = new TemplateLink
    {
        Uri = "https://raw.githubusercontent.com/Azure/azure-docs-json-samples/master/azure-resource-manager/what-if/what-if-after.json"
    }
};
var deploymentWhatIfOperation = await deployment.WhatIfAsync(true, string.Empty, deploymentWhatIfProperties);
```

**Comment by JayDZimmerman** [comment]
@Yao725 That took care of it.  The secret sauce was the "CreateResourceIdentifier" method, which solved my primary issue of not knowing how to create a deployment (without executing it as well).  Thanks for your help.
