### ISSUE TITLE
[BUG] Not able to create IPv6 with ServicePublicIPAddress property

### ISSUE THREAD

**Issue by rajdhandus** [Azure/azure-sdk-for-net#26982]
### Library name and version

Azure.ResourceManager.Network

### Describe the bug

Running the below code throws an error.

```
public static async Task CreatePublicIPv6Address(string ipv6AddressName, string servicePublicIPAddress, string resourceGroupName, string subscriptionId)
        {
            ArmClient armClient = new ArmClient(new DefaultAzureCredential());
            Subscription subscription = await armClient.GetSubscriptions().GetAsync(subscriptionId).ConfigureAwait(false);
            ResourceGroupCollection resourceGroupCollection = subscription.GetResourceGroups();

            ResourceGroup resourceGroup = await resourceGroupCollection.GetAsync(resourceGroupName).ConfigureAwait(false);

            PublicIPAddressCollection publicIPAddressCollection = resourceGroup.GetPublicIPAddresses();

            PublicIPAddressData publicIPInput = new PublicIPAddressData()
            {
                Location = resourceGroup.Data.Location,
                Sku = new PublicIPAddressSku()
                {
                    Name = "Standard",
                },
                PublicIPAddressVersion = IPVersion.IPv6,
                PublicIPAllocationMethod = IPAllocationMethod.Static,
                ServicePublicIPAddress = new PublicIPAddressData()
                {
                    Id = servicePublicIPAddress,
                },
            };

            PublicIPAddress publicIPAddress = await publicIPAddressCollection.CreateOrUpdate(ipv6AddressName, publicIPInput, true).WaitForCompletionAsync().ConfigureAwait(false);
            Console.WriteLine($"Created a public IP address {publicIPAddress.Id}");

        } 
```

If I comment out ServicePublicIPAddress section - it works.

```
public static async Task CreatePublicIPv6Address(string ipv6AddressName, string servicePublicIPAddress, string resourceGroupName, string subscriptionId)
        {
            ArmClient armClient = new ArmClient(new DefaultAzureCredential());
            Subscription subscription = await armClient.GetSubscriptions().GetAsync(subscriptionId).ConfigureAwait(false);
            ResourceGroupCollection resourceGroupCollection = subscription.GetResourceGroups();

            ResourceGroup resourceGroup = await resourceGroupCollection.GetAsync(resourceGroupName).ConfigureAwait(false);

            PublicIPAddressCollection publicIPAddressCollection = resourceGroup.GetPublicIPAddresses();

            PublicIPAddressData publicIPInput = new PublicIPAddressData()
            {
                Location = resourceGroup.Data.Location,
                Sku = new PublicIPAddressSku()
                {
                    Name = "Standard",
                },
                PublicIPAddressVersion = IPVersion.IPv6,
                PublicIPAllocationMethod = IPAllocationMethod.Static,
                //ServicePublicIPAddress = new PublicIPAddressData()
                //{
                //    Id = servicePublicIPAddress,
                //},
            };

            PublicIPAddress publicIPAddress = await publicIPAddressCollection.CreateOrUpdate(ipv6AddressName, publicIPInput, true).WaitForCompletionAsync().ConfigureAwait(false);
            Console.WriteLine($"Created a public IP address {publicIPAddress.Id}");

        }
```

### Expected behavior

We should be able to create an IPv6 Static Public IP address with a Service Public IP Address.

### Actual behavior

Not able to create an IPv6 Static Public IP Address with a Service Public IP Address

### Reproduction Steps

Run the above given code.

### Environment

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.2.2" />
		<PackageReference Include="Azure.ResourceManager.Compute" Version="1.0.0-beta.5" />
		<PackageReference Include="Azure.ResourceManager.Network" Version="1.0.0-beta.5" />
	</ItemGroup>

</Project>
```

VS2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@archerzz  please help to check this issue

**Comment by mcgallan** [comment]
@rajdhandus In response to your question, there's one thing I think you need to know first, the value required for the property 'Id' in the PublicIPAddressData class is the resource ID, not the name of the public IP address, the resource ID does not need to and cannot be assigned by you, if you want to create a PublicIPAddress class, you can refer to the following code: 

            string resourceGroupName = Recording.GenerateAssetName("csmrg");
            string location = TestEnvironment.Location;
            var resourceGroup = await CreateResourceGroup(resourceGroupName);

            string publicIpName = Recording.GenerateAssetName("ipname");
            string domainNameLabel = Recording.GenerateAssetName("domain");

            var publicIp = new PublicIPAddressData()
            {
                Location = location,
                Tags = { { "key", "value" } },
                PublicIPAllocationMethod = NetworkIPAllocationMethod.Dynamic,
                DnsSettings = new PublicIPAddressDnsSettings()
                {
                    DomainNameLabel = domainNameLabel
                }
            };

            var publicIPAddressCollection = resourceGroup.GetPublicIPAddresses();
            var putPublicIpAddressResponseOperation = await publicIPAddressCollection.CreateOrUpdateAsync(WaitUntil.Completed, publicIpName, publicIp);

**Comment by admin-01-web** [comment]
On Wed, Nov 23, 2022, 1:41 AM macmillan ***@***.***> wrote:

> }@ <https://github.com/rajdhandus>™[∆] In response to your question,
> there's one thing I think you need to know first, the value required for
> the property 'Id' in the class is the resource ID, not the name of the
> public IP address, the resource ID does not need to and cannot be assigned
> by you, if you want to create a Published class, you can refer to the
> following code:
>
>         string resourceGroupName =r
>
>  "Recording.GenerateAssetName("cosmos");
>         string location = TestEnvironment.Location;
>         var resourceGroup =
>
>
 await CreateResourceGroupresource
>
> Group
>
> Name);
>
>         string  = Recording.GenerateAssetName("if name");
>         string Unmanageable Recording.GenerateAssetName("domain");
>
>         var publicIp = new PublicIPAddressData()
>
>
> 5

> {     Location
>
> (0000)

> = location,
>
>             Tags = { { "key", "value" } },
>             PublicIPAllocationMethod = NetworkIPAllocationMethod.Dynamic,
>             DnsSettings = new PublicIPAddressDnsSettings()
>             {
>                 DomainNameLabel = domainNameLabel
>             }
>         };
>
>    https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Seriennummer.JPG/220px-Seriennummer.JPG
>
>
(Collection) = resourceGroup.GetPublicIPAddresses();
>         var put
>
> Probably 3

> Public
>
>
IpAddressResponseOperation =it
pIPAddressCollection.CreateOrUpdateAsync(WaitUntil.Completed,
publicIpName, publicIp);
