### ISSUE TITLE
Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1

### ISSUE THREAD

**Issue by jrockfl** [Azure/azure-sdk-for-net#26987]
I have created an Azure Function App with .NET Framework 4.71 and I'm receiving the following exception.

Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Function1 ---> System.IO.FileNotFoundException : Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.\r\n   at System.MemoryExtensions.AsSpan(String text)

`var resourceIdentifier = new ResourceIdentifier("/subscriptions/00000000-0000-0000-0000-000000000000");`

![image](https://user-images.githubusercontent.com/1075542/153767973-1cc7e061-4276-480f-ba41-7db0a17d69cb.png)

I have also set this up in a Console App .NET Framework 4.7.1 without any issues. 

![image](https://user-images.githubusercontent.com/1075542/153767868-40f21050-ecff-432f-b76d-01b07f33036b.png)

What can I do to resolve this issue?

**Comment by ArthurMa1978** [comment]
Thank you for reaching us, @archerzz  please check if this is the mgmt issue.

**Comment by jrockfl** [comment]
Yes, I added Azure.Core. It was in the nuget package.
Loading Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1 is something different.
 
I was able to get this to work with a console app but not Azure Function. 
 
 
-----Original Message-----

**Comment by DomCotton** [comment]
Hi, I have exactly the same issue after migrating from Microsoft.Azure.ServiceBus to Azure.Messaging.ServiceBus.  When I run my solution locally, it executes.  However deploying the solution onto a Windows Server 2019 it fails with the following:

[E] 8:58:25 AM: Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Threading.Tasks.ValueTask`1.get_IsCompleted()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<ReceiveMessagesAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<ReceiveMessagesAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ReceiverManager.<ReceiveAndProcessMessagesAsync>d__13.MoveNext()

Not sure if its related or helps resolve... 

Thanks

**Comment by jfeller403** [comment]
I had this exact error message when I tried to use Azure in my project.  I searched for the .dll on my computer and found the correct version. Added it to the GAC using gacutil -i . Seemed to solve that issue but then it threw the same error with a new assembly name.

**Comment by archerzz** [comment]
@jrockfl @DomCotton @jfeller403 This should be a binding redirect problem. Try to explicitly upgrade `Unsafe` to latest version, or try binding redirect as indicated [here](https://github.com/StackExchange/StackExchange.Redis/issues/1128#issuecomment-501728242).
