### ISSUE TITLE
[Functions] Investigate additional extension error logging for cases where underlying library throws

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#26981]
For situations where the underlying library throws an exception, the exception may not contain enough information to help users easily troubleshoot. Since the extensions have additional context around the library call being made, they are in a good position to offer additional information via logging. One example is around the authentication that needs to happen involving the storage queue libraries when using blob triggers. Right now the only error logging comes from the storage library and can be confusing for users who were not even aware that queues were being used under the hood.

**Comment by jsquire** [comment]
This is a good idea, but not something that we're likely to invest in as an end-to-end effort.  We'll continue to monitor customer feedback and address on a case-by-case basis when exceptions are reported to be confusing.
