### ISSUE TITLE
[FEATURE REQ] Building Custom Models with Multiple pages

### ISSUE THREAD

**Issue by castasint** [Azure/azure-sdk-for-net#26995]
### Library name and version

Azure.AI.FormRecognizer

### Query/Question

I'd like to build a custom model which should be able to process multiple pages in a document. 

To better illustrate,  when a person needs to submit his pay stubs for say 3-6 months, he could very well create a pdf document with paystubs for 6 months placed in it. Think of it like a collection of (strongly typed - as in same type) documents inside a big document.

Is it achievable using Form Recognizer? I understand it may not be available right now, but is it in plans for the future releases? If so, when can I expect this feature?

### Environment

Dot Net 5.x, Windows Server 2019 and VS - 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
@ctstone Could you help answering this question about the service's capabilities?

**Comment by kinelski** [comment]
Ping @ctstone

**Comment by kinelski** [comment]
@ctstone @anrothMSFT @vkurpad Could you take a look at this question?

**Comment by anrothMSFT** [comment]
Hi! I've joined a new team. I've pointed the team to this thread on an offline mail.

**Comment by vkurpad** [comment]
Hi @castasint, currently the model will only process a single page within a document that matches a template. The feature you need is to split a file into multiple documents and then process each of the documents. This is in our roadmap and you should expect to see it by the end of the year.

**Comment by Stephen-Zealous** [comment]
This feature is highly important to my team, we've had to develop around it. Is it possible there is a roadmap regarding this and other features?

**Comment by kinelski** [comment]
@Stephen-Zealous As @vkurpad mentioned, the requested feature is in the service's roadmap and it's expected to be available by the end of the year. I'm leaving this issue closed since the question has been answered, but if you feel you have more questions, feel free to open a new issue.
