### ISSUE TITLE
Doc request

### ISSUE THREAD

**Issue by EfimenkoAndrew** [Azure/azure-sdk-for-net#26994]
[Enter feedback here]
The doc is completely useless. It is absolutely not helpful. How am I supposed to register my own implementation to ASP.NET Core DI? Where are meaningful code examples? What problems does it solve? How to use it? How to use a serializer? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 748e01f3-19cf-5c5a-ac3b-0308e93ae3fd
* Version Independent ID: b3821ee6-bdab-d7ee-7d5a-6fcdd629fe13
* Content: [CosmosSerializer Class (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosserializer?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/CosmosSerializer.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/CosmosSerializer.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@EfimenkoAndrew An instance of your custom derived class must be set in a [`CosmosClientOptions`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions?view=azure-dotnet) instance, which then must be passed in when creating a [`CosmosClient`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclient?view=azure-dotnet) object.

Check out [this official sample](https://github.com/Azure/azure-cosmos-dotnet-v3/tree/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson) on how to implement your own.

**Comment by PramodValavala-MSFT** [comment]
@EfimenkoAndrew We have listed this sample as part of [the samples page in the official docs](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/sql-api-dotnet-v3sdk-samples) to make it more discoverable. It should reflect in a couple of hours. Closing.
