### ISSUE TITLE
Allow dynamically generated <package_name>/<package_version> portion of User-Agent header values per HttpMessage

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#26999]
### Library name

Azure.Core

### Please describe the feature.

# Summary
The format of the UserAgent header is as follows : `[<application_id> ]azsdk-<sdk_language>-<package_name>/<package_version> <platform_info>`. Management plane clients, for example, have a requirement to dynamically set the  `<package_name>/<package_version>` portion of the UserAgent header value per service call, depending on which Resource Providers (RP) is being interacted with. In addition, it needs to support customers adding in their own user agents without overwriting the RP specific header value. Storage clients have a similar example with `BlobChangeFeedClient` which is really a `BlobClient` under the covers.

This might normally be accomplished by simply adding an additional pipeline policy that calls `message.Request.Headers.Add(HttpHeader.Names.UserAgent, ...` with any custom values required. However, this only adds an additional value to the UserAgent header array, rather than setting the current value, or appending the value to the current single-string value. In addition this can result in duplicate package name values being added to the header value.

Because it's common that Azure services only recognize the first value of the UserAgent header values in such cases rather than interpreting the array of values, the solution should avoid relying on setting multiple values in favor of a single value that concatenates all required values.

## Challenges

- One of the challenges with the current `TelemetryPolicy` is that it determines the name of parent assembly for the instance of ClientOptions passed to PipelineBuilder [uses that value](https://github.com/Azure/azure-sdk-for-net/blob/502161f5ad3c721f8aba00d0afb477be0d77f187/sdk/core/Azure.Core/src/Pipeline/HttpPipelineBuilder.cs#L177) to construct a string which will be used in the UserAgent header for every request. For Management Plane clients, this assembly name is always `Azure.ResourceManager`, which is not correct for many scenarios. For example, each RP is broken up into sub clients but only one public Client / ClientOptions is exposed. If one were to construct an ArmClient and create a Virtual Machine, for instance, you would end up using 3 separate RPs requiring 3 separate user agents for various calls during that process.
- Any dynamic header value calculation would be in the hot path (every request) and must be very efficient.
- Ideally only the `<package_name>/<package_version>` portion is configurable, so that the formatting of the UserAgent header can be preserved.

## FAQ

**Why can't [ClientOptions.Diagnostics.ApplicationId](https://github.com/Azure/azure-sdk-for-net/blob/502161f5ad3c721f8aba00d0afb477be0d77f187/sdk/core/Azure.Core/src/Pipeline/HttpPipelineBuilder.cs#L203) be leveraged for this?**

- This value is static per Client assembly and is not dynamic per request. In addition, the current implementation or ARM and how it interprets UserAgent values requires that the ResourceManager assembly name not be in the value. ApplicationId is just prepended to the existing assembly name based value.

**Why can't a policy be added to the pipeline that adds all the additional UserAgent values that we need to be represented rather than changing how `TelemetryPolicy` does it**

- The usage data only recognizes the first value of the header and so subsequent values may not be counted as expected.
- The presence of the default value calculated by `TelemetryPolicy` is often incorrect for Management Plane service calls and would cause incorrect usage data.
- Even if all the values could aggregate appropriately, the presence of the default value is often wrong and unnecessary, creating unwanted overhead.

## Resources

- [Telemetry Policy Guidelines](https://azure.github.io/azure-sdk/general_azurecore.html#telemetry-policy)

cc @m-nash @KrzysztofCwalina @AlexGhiondea

**Comment by JoshLove-msft** [comment]
@tg-msft mentioned that this might impact Storage as well as they are looking for this feature for BlobChangeFeed.

**Comment by tg-msft** [comment]
The `BlobChangeFeedClient` makes all of its calls via `BlobClient` under the hood, but that means we can't get any Change Feed telemetry.  The Storage team would like a way to customize the assembly portion of the `User-Agent` so it says `Storage.Blobs.ChangeFeed` instead of just `Storage.Blobs`.
