### ISSUE TITLE
AzureCredentials.FromServicePrincipal does not support certificate authentication

### ISSUE THREAD

**Issue by flytzen** [Azure/azure-sdk-for-net#2700]
ServicePrincipals *can* use keys - but it's often a bad idea.
A better idea is to use a certificate to authenticate a service principal - see https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-authenticate-service-principal.

Alas, AzureCredentials.FromServicePrincipal only works with keys, making it unsuitable for a number of scenarios.

**Comment by pbolduc** [comment]
The could be extended simply. Add class CertificateLoginInformation,

    using System.Security.Cryptography.X509Certificates;

    public class CertificateLoginInformation
    {
        public CertificateLoginInformation()
        {            
        }

        public CertificateLoginInformation(string clientId, X509Certificate2 certificate)
        {
            ClientId = clientId;
            Certificate = certificate;
        }

        public string ClientId { get; set; }
        public X509Certificate2 Certificate { get; set; }
    }

Then create ClientAssertionCertificate and use ApplicationTokenProvider to get the credentials 

    var clientAssertion = new ClientAssertionCertificate(_certificateLoginInformation.ClientId, _certificateLoginInformation.Certificate);
    var credentials = await ApplicationTokenProvider.LoginSilentAsync(TenantId, clientAssertion, settings, TokenCache.DefaultShared);

**Comment by lishuode** [comment]
Also need that feature. It is important for a cloud app. We need a proper certificate auth and login.

**Comment by hovsepm** [comment]
Supported starting from v1.0
