### ISSUE TITLE
Managed Identity token lifetime

### ISSUE THREAD

**Issue by Pikabanga** [Azure/azure-sdk-for-net#27019]
Hi,

We are using the [DefaultAzureCredential class](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) along with the environment variable `AZURE_CLIENT_ID` to acquire an oauth token for the function app's user assigned managed identity, which is then passed on when making calls to other API:s within the system. This works fine, except for that the token has a lifetime of 24 hours and 5 minutes. 

This causes a lot of problems when we want to change the claims of this managed identity (for example add or remove an AD group membership), and we have to wait up to 24 hours for the change to take effect. Stopping and starting the function app does nothing, the same token will be returned. The only workaround I've found is via the very brute force approach of removing the managed identity, create it again, set up permissions all over again, etc. I have not found a way to explicitly ask for a new token ("force refresh"), or any settings in the AD that controls the lifetime of these tokens.

So my questions are:

- Is it possible to explicitly ask for a new token?
- Is it possible to control what the lifetime of these tokens should be?

Please let me know if you require any additional information!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 414d8832-9224-3bb5-2bf4-1197c41fdedf
* Version Independent ID: 02d95dd6-bf1b-5cef-bc94-ac187b133c45
* Content: [DefaultAzureCredential Class (Azure.Identity) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet)
* Content Source: [xml/Azure.Identity/DefaultAzureCredential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Identity/DefaultAzureCredential.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @Pikabanga - The cache lifetime of the token issued by a Managed Identity endpoint is controlled by the service provider, and unfortunately it appears that there is no way to force the refresh.

See the following documentation: 
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/managed-identities-faq#are-tokens-cached-after-they-are-issued-for-a-managed-identity

https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/managed-identity-best-practice-recommendations#limitation-of-using-managed-identities-for-authorization
