### ISSUE TITLE
[BUG] Deserializing ManagedServiceIdentity in GetGenericResourcesAsync

### ISSUE THREAD

**Issue by omri-muszkal** [Azure/azure-sdk-for-net#27025]
### Library name and version

Azure.ResourceManager 1.0.0-beta.8

### Describe the bug

Calling the function GetGenericResourcesAsync on Subscription, 
the sdk deserializing ManagedServiceIdentity object and throws FormatException.

After some digging around we found the the reason is that the retuned json has this format: 
`"identity": {
        "principalId": "",
        "tenantId": "",
        "type": "None"
      }`

https://github.com/Azure/azure-sdk-for-net/blob/4cd85e6dd23569269ccb6db92b813e0a394ee69d/sdk/resourcemanager/Azure.ResourceManager/src/Common/Generated/Models/ManagedServiceIdentity.Serialization.cs#L46-L55

the GetGuid() throws the format exception.

This happen as of now only in Microsoft.DevTestLab/labs generic resource with api-version 2018-10-15-preview
in the api-version 2018-09-15 of Microsoft.DevTestLab/labs, the property identity is not returned.

### Expected behavior

The code should handle cases where principalId and tenantId are null

### Actual behavior

The code does not handle cases where principalId and tenantId are null

### Reproduction Steps

unfortunately we cannot reproduce this behavior with new resources.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
This issue might have been fixed, @fengzhou-msft  please help to confirm it

**Comment by fengzhou-msft** [comment]
Route to service team as the service should not return an empty string for principalId and tenantId.

**Comment by fengzhou-msft** [comment]
We've added a patch on the client side and the fix will be released in the next version of `Azure.ResourceManager` (likely `1.5.0`).
