### ISSUE TITLE
Non working example in documentation for ReadManyItemsStreamAsync in CosmosDB C# SDK

### ISSUE THREAD

**Issue by TwoPatient** [Azure/azure-sdk-for-net#27024]
The worked example is incomplete. There is no hint at to where response comes from.

`IReadOnlyList<(string, PartitionKey)> itemList = new List<(string, PartitionKey)>
{
    ("Id1", new PartitionKey("pkValue1")),
    ("Id2", new PartitionKey("pkValue2")),
    ("Id3", new PartitionKey("pkValue3"))
};

using (ResponseMessage responseMessage = await this.Container.ReadManyItemsStreamAsync(itemList))
{
    using (Stream stream = response.ReadBodyAsync())
    {
        //Read or do other operations with the stream
        using (StreamReader streamReader = new StreamReader(stream))
        {
            string content = streamReader.ReadToEndAsync();
        }
    }
}`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 819245a4-835a-64aa-d195-60871cacc13c
* Version Independent ID: 5cabd119-cec0-b932-0311-cb739ac51939
* Content: [Container.ReadManyItemsStreamAsync(IReadOnlyList&lt;ValueTuple&lt;String,PartitionKey&gt;&gt;, ReadManyRequestOptions, CancellationToken) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.readmanyitemsstreamasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@TwoPatient Thanks for your feedback. I have submitted a [PR](https://github.com/Azure/azure-docs-sdk-dotnet/pull/2107) to update the example.

Thanks
Saurabh

**Comment by TwoPatient** [comment]
Thank you 👍
