### ISSUE TITLE
SignalR documentation is not linked

### ISSUE THREAD

**Issue by ronaldpschutte** [Azure/azure-sdk-for-net#27026]
There is no documentation for the management of SignalR resources, even though there is: https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Microsoft.Azure.Management.SignalR/1.0.1/api/Microsoft.Azure.Management.SignalR.html

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 830061e1-ba1a-c827-b771-32cf0c7f8d68
* Version Independent ID: 25076747-6298-f738-7e46-b30d8f687075
* Content: [API Reference - Azure for .NET Developers](https://docs.microsoft.com/en-gb/dotnet/api/overview/azure/?view=azure-dotnet)
* Content Source: []()
* Git Login: **rloutlaw**
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Here you are https://learn.microsoft.com/en-gb/dotnet/api/overview/azure/signalr?view=azure-dotnet
