### ISSUE TITLE
[QUERY] [EventHub] PartitionKey HashCode Generation

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#27030]
### Library name and version

Azure.Messaging.EventHubs

### Query/Question

When converting [PartitionResolver.ComputeHash](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/PartitionResolver.cs#L123) to span and BinaryPrimitives it would be possible to squeeze out some perf. See the below benchmark

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
11th Gen Intel Core i7-1185G7 3.00GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.102
  [Host]     : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT
  DefaultJob : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT


```
|                  Method |     Mean |     Error |   StdDev |    StdErr |   Median |      Min |       Q1 |        Q3 |      Max |          Op/s | Ratio | RatioSD |
|------------------------ |---------:|----------:|---------:|----------:|---------:|---------:|---------:|----------:|---------:|--------------:|------:|--------:|
| ComputeHashBitConverter | 9.599 ns | 0.3469 ns | 1.007 ns | 0.1022 ns | 9.421 ns | 7.989 ns | 8.835 ns | 10.279 ns | 12.61 ns | 104,174,105.6 |  1.00 |    0.00 |
|         ComputeHashSpan | 8.792 ns | 0.4335 ns | 1.216 ns | 0.1274 ns | 8.444 ns | 6.987 ns | 7.875 ns |  9.409 ns | 12.60 ns | 113,736,404.7 |  0.93 |    0.16 |

Is that something you'd be interested in?

Another thing. I noticed currently it is required to allocate a byte array to compute the hash and the size of the byte array is proportional to the size of the partition key. I see the following options:

- Pool the buffer
- Stackalloc the buffer for short string and for longer pool the buffer
- If the `EnqueueEventOptions` are most likely to be reused per partition, it would be possible to turn the partition key into bytes there and the just pass those bytes into `ComputeHash` method (then the options act as sort of root for the byte array)

Just as an example, pooling the byte array there is slightly slower but gets rid of all the allocations on that path.

``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
11th Gen Intel Core i7-1185G7 3.00GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.102
  [Host]     : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT
  DefaultJob : .NET 6.0.2 (6.0.222.6406), X64 RyuJIT


```
|    Method |     Mean |    Error |   StdDev |   StdErr |      Min |       Q1 |   Median |       Q3 |      Max |         Op/s | Ratio | RatioSD |  Gen 0 | Allocated |
|---------- |---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|-------------:|------:|--------:|-------:|----------:|
|    Pooled | 67.84 ns | 1.171 ns | 1.038 ns | 0.277 ns | 66.13 ns | 67.12 ns | 67.67 ns | 68.67 ns | 69.39 ns | 14,740,063.2 |  1.15 |    0.09 |      - |         - |
| NonPooled | 55.45 ns | 1.686 ns | 4.892 ns | 0.497 ns | 47.37 ns | 51.71 ns | 54.57 ns | 58.57 ns | 68.62 ns | 18,033,322.7 |  1.00 |    0.00 | 0.0102 |      64 B |

**Comment by danielmarbach** [comment]
The question is about EventHubs and not ServiceBus. The bot is drunk ;)

**Comment by jsquire** [comment]
> Is that something you'd be interested in?

Yes.  😄   Attempting to revisit and optimize this is something that is on my "when I get a chance" list.   The key will be ensuring that we preserve the existing behavior.  We borrowed that implementation from the service to try and keep the client behavior consistent.  While we can deviate if we have the need to do so, we'll have to coordinate across languages, as the results from the buffered producer in each language must align.

**Comment by jsquire** [comment]
To put things in perspective, partition keys are probably the 30-40% case when publishing.   So, we'll see non-trivial use of these code paths, but the round-robin case will be the most prevalent.

**Comment by danielmarbach** [comment]
Cool will think about it and once I have sufficient time I'll send a PR

**Comment by jsquire** [comment]
As always, thank you, @danielmarbach.    I'm going to mark this one as addressed, but feel free to reach out if there's any additional context that I can help with.

**Comment by danielmarbach** [comment]
Here we go, a draft PR to get the discussion started

https://github.com/Azure/azure-sdk-for-net/pull/27598
