### ISSUE TITLE
Encoding issue with the documentation paragraph

### ISSUE THREAD

**Issue by william-li-nintex** [Azure/azure-sdk-for-net#27039]
[Enter feedback here]
Seems to have an encoding issue per below
![image](https://user-images.githubusercontent.com/89058536/154234409-7f72e38f-3ebf-4afb-8570-e83c8a76f960.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c89f7c02-ca6c-3a95-b967-b8ca3e80e269
* Version Independent ID: d1c50b62-bbc7-304f-1313-65266458bdaa
* Content: [Site.ClientAffinityEnabled Property (Microsoft.Azure.Management.WebSites.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.site.clientaffinityenabled?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.WebSites.Models/Site.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/Site.xml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
//fyi CXP:  Routing this to `Service`, as the adjustment needs to be made in the swagger for the REST endpoint.

**Comment by mmacy** [comment]
@jsquire This might actually be AutoRest: https://github.com/Azure/autorest.csharp/issues/208

**Comment by mmacy** [comment]
> @jsquire
> Currently, because there's a lack of support for embedded HTML, the recommendation for similar issues has been to adjust the swagger content and avoid using HTML tags to provide a more expedient resolution.

While avoiding HTML in _new_ Swagger files might be the most expedient for new specs, it's certainly not the _best_ resolution. Both OpenAPI 2.0 and 3.0 support HTML and Markdown  in their description fields, so the right thing to do would be to support that in our code generator.

I've updated the original bug on this with additional information and a proposed solution in https://github.com/Azure/autorest.csharp/issues/208#issuecomment-1046056381.

HOWEVER, I just found that which whichever AutoRest version being used to generate the preview management libraries no longer encodes the characters.

Docs still isn't rendering it correctly, though - it's rendering the raw HTML tags. :(

https://docs.microsoft.com/en-us/dotnet/api/azure.resourcemanager.compute.models.osprofile.adminpassword?view=azure-dotnet-preview#azure-resourcemanager-compute-models-osprofile-adminpassword

![image](https://user-images.githubusercontent.com/13394541/154814908-7a3d3a37-2369-48cc-a75e-55d7c59a7206.png)

**Comment by huangmin-ms** [comment]
> 

@mmacy  you can use **<br/>** for the line break.

**Comment by mmacy** [comment]
@huangmin-ms Thanks. Unfortunately, I don't have time to test this. The source for this is here - maybe someone on your team can test?

https://github.com/Azure/azure-rest-api-specs/blob/c537f5a7853766a7946863dd9b0303773b488eff/specification/compute/resource-manager/Microsoft.Compute/stable/2022-03-01/ComputeRP/computeRPCommon.json#L1362-L1365

**Comment by huangmin-ms** [comment]
@mmacy  just ignore this, after talked to Autorest team, we will do decoding only for azure sdk on the docs site.

**Comment by mmacy** [comment]
@huangmin-ms OK, thanks. This issue is still a problem, then - is that correct?
