### ISSUE TITLE
[BUG] GetGenericResourcesAsync wrong deserialization  for Microsoft.ContainerService/managedClusters

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-net#27044]
### Library name and version

Azure.ResourceManager 1.0.0-beta.8

### Describe the bug

When querying GetGenericResourcesAsync, for some resources in Microsoft.ContainerService/managedClusters it returns wrong data for Identity property which causes the deserialize to behave in a strange way.

You can see in the summary that principalId and tenantId should only be present when the type is SystemAssigned but in our case, both of these fields are presnet even though the type is UserAssigned.

https://github.com/Azure/azure-sdk-for-net/blob/4cd85e6dd23569269ccb6db92b813e0a394ee69d/sdk/resourcemanager/Azure.ResourceManager/src/Common/Generated/Models/ManagedServiceIdentity.cs#L28-L40

We assume this is caused by using an outdated api-version for the internal implementation because when I query the resource directly with api-version between 2022-01-02-preview and 2020-04-01(not included), we get this object:
`"identity": {
    "type": "UserAssigned",
    "userAssignedIdentities": {
      "<REDACTED>": {
        "clientId": "<REDACTED>",
        "principalId": "<REDACTED>"
      }
    }
  }`

but when querying with 2020-04-01 we get this reponse:
`"identity": {
    "principalId": "<REDACTED>",
    "tenantId": "<REDACTED>",
    "type": "UserAssigned"
  }`

### Expected behavior

PrincipalId and TenantId should be null and UserAssignedIdentities be populated with the correct values.

### Actual behavior

PrincipalId and TenantId are not null and UserAssignedIdentities is empty

### Reproduction Steps

unfortunately we were not able to reproduce this behavior with .net sdk/console access.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by live1206** [comment]
Requires change of the service response from service team, nothing we can do in SDK, move back to backlog.
