### ISSUE TITLE
[QUERY] Azure Communication Service .Net SDK: Is it possible to get participant's audiostream during video call?

### ISSUE THREAD

**Issue by h0las-dev** [Azure/azure-sdk-for-net#27049]
### Library name and version

Azure.Communication.Calling 1.0.0-beta.29

### Query/Question

I've started to investigate this SDK recently and I've stucked with a problem: I want to get audio stream from remote participant during video call and pass this stream to another service, make some analysis (convert audio to text and show like dynamic speech transcript for example. I want to use Azure Speech service for that). The problem is I don't know how to get audio stream from video stream or from call in this SDK.

I found only 1 example of usage Azure Communication Service in .Net here: https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-video-calling?pivots=platform-windows

It works, however I didn't see anything connected with audio here or somewhere else.

So, if anyone knows how to get audiostream using this SDK, it will really helpful for me. Also I will happy if someone can share any other usage examples video (or even audio calling) for .Net using this SDK because I found only 1 example and it's pretty poor. Thank you!

### Environment

Windows 10 OS Build 17763.2565
Microsoft.NETCore.UniversalWindowsPlatform version 6.2.13
Microsoft Visual Studio Community 2022 (64-bit) Version 17.0.4

**Comment by SatishBoddu-MSFT** [comment]
Related: Q&A: [Azure Communication Service - Access to audio stream and pass it into Speech-To-Text service in real time](https://docs.microsoft.com/en-us/answers/questions/736185/azure-communication-service-access-to-audio-stream.html )

**Comment by h0las-dev** [comment]
Got answer here: https://docs.microsoft.com/en-us/answers/questions/736185/azure-communication-service-access-to-audio-stream.html
Thank you!
