### ISSUE TITLE
[BUG] Service Bus: Received messages do not have a valid Lock Until property when sessions are enabled

### ISSUE THREAD

**Issue by dean-dot-git** [Azure/azure-sdk-for-net#27057]
### Library name and version

Azure.Messaging.ServiceBus v7.6.0

### Describe the bug

When used in conjunction with Azure Functions v4.0.1 and creating a version 2.0 **session enabled** service bus trigger, the ServiceBusReceivedMessage object, "LockUntil" property does not have a valid date.  In a Azure Function service bus trigger, it is potentially not possible to determine what the session lock time out is (at least intuitively).  I am assuming the trigger is creating the lock on the session Id, so trying to create another session receiver by acquiring another lock on the session Id won't work as it is locked already by the trigger?  The lock information is on the session receiver, which we can't inject in the trigger, so we need to be able to get it off the message as all messages of the same session lock should have the same lock until date as the session receiver.

### Expected behavior

It should contain the session lock until date as set by the receiver.  I would assume that would be derived from the queue lock duration.

Alternative is to allow the injection of the ServiceBusSessionReceiver to be injected and obtain the session lock date from it.

### Actual behavior

It results in a maximum value (or near maximum value) of a date/time object.

### Reproduction Steps

- Create a service bus with a session enabled queue in Azure.  Set the lock on the queue to max of 5 minutes to ensure a noticeable difference.
- Create an service bus trigger Azure Function in Visual Studio 2022, use v4.0.3971 of the Azure Function core tools on .NET 6.0.
- enable sessions by specifying the "IsSessionsEnabled" property of the trigger.
- inject the ServiceBusReceivedMessage as one of the parameters to the trigger.
- Add a message to the service bus queue.
- Debug the trigger in visual studio.
- inspect "message.LockUntil" when the trigger fires.

### Environment

C#

.NET Runtime 6.0 on Windows

Visual Studio 2022 (17.0.2)

v4.0.3971 of the Azure Function core tools

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @dean-dot-git,
As you mentioned, the lock is managed at the session level rather than the message level when using sessions. Can you clarify what you wish to use the SessionLockedUntil value for?

**Comment by dean-dot-git** [comment]
> Hi @dean-dot-git, As you mentioned, the lock is managed at the session level rather than the message level when using sessions. Can you clarify what you wish to use the SessionLockedUntil value for?

Hi @JoshLove-msft ,
I am using it to validate when the Session is locked until.  When we have code that executes on the trigger, maybe it fails, it would be nice to know how much time is left on the lock to determine what actions we can take when we have a retry configured to fire.  It just needs to be an accurate date time so business decisions can be made.

**Comment by JoshLove-msft** [comment]
I've added SessionLockedUntil property to ServiceBusSessionMessageActions. Please let us know if there are any issues with that approach.
