### ISSUE TITLE
[BUG] Nuget official package of Microsoft.Azure.Management.Consumption is not in sync with GitHub code

### ISSUE THREAD

**Issue by DOMZE** [Azure/azure-sdk-for-net#27058]
### Library name and version

Microsoft.Azure.Management.Consumption 3.0.2

### Describe the bug

The code on the repository (https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/consumption/Microsoft.Azure.Management.Consumption/src/Generated/UsageDetailsOperationsExtensions.cs) contains the scope parameter but the nuget package officially release does not:

Code in GitHub
```csharp
public static async Task<IPage<UsageDetail>> ListAsync(this IUsageDetailsOperations operations, string scope, string expand = default(string), string filter = default(string), string skiptoken = default(string), int? top = default(int?), string metric = default(string), CancellationToken cancellationToken = default(CancellationToken))
{
	using (var _result = await operations.ListWithHttpMessagesAsync(scope, expand, filter, skiptoken, top, metric, null, cancellationToken).ConfigureAwait(false))
	{
		return _result.Body;
	}
}
```

SDK:

![image](https://user-images.githubusercontent.com/8238156/154344279-a5ac42df-bc7b-4fb3-a80d-d036719d1357.png)

This has been almost 1yr and 4 months since this has been asked by the community here. https://github.com/Azure/azure-sdk-for-net/issues/14602

What's going on?
This needs to be released ASAP . 1yr and 4 months later and the code is not in sync with the current official latest release.

Please advise ASAP.

### Expected behavior

The nuget package contains the source code that is shown on the repository.

### Actual behavior

The code released in the nuget package does not contains the scope.

### Reproduction Steps

in a console
```
dotnet new console --name Demo
dotnet add package Microsoft.Azure.Management.Consumption --version 3.0.2
```

In the code:

```csharp
using Microsoft.Azure.Management.Consumption;
using Microsoft.Rest;

var credentials = new TokenCredentials(string.Empty);
var client = new ConsumptionManagementClient(credentials);
await client.UsageDetails.ListAsync();
```

intellisense doesn't show the scope parameter.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
The consumption service owns it, that can help to solve this issue

**Comment by DOMZE** [comment]
@mrlepat any news? 20 days since your reply and no news....

**Comment by tujamg** [comment]
Consumption cmdlet version update is in our backlog. Will update this issue once we release a new version.

**Comment by tujamg** [comment]
Consumption cmdlet version update is in our backlog. Will update this issue once we release a new version.

**Comment by DOMZE** [comment]
@tujamg Seems kind of long to release things that are already committed in the main branch...
