### ISSUE TITLE
[BUG] Listeners may be Disposed before StopAsync() is called

### ISSUE THREAD

**Issue by cachai2** [Azure/azure-sdk-for-net#27056]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0

### Describe the bug

In Track1 of the Event Hubs extension, the check for `_started` in `FunctionListner` is not synchronized across `StartAsync()` and `StopAsync()` calls (https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Listeners/FunctionListener.cs#L139). This may need to be resolved in Track 2.

Relevant Track 1 issues:
- https://github.com/Azure/azure-functions-eventhubs-extension/issues/66
- https://github.com/Azure/azure-webjobs-sdk/issues/2823
- https://github.com/Azure/azure-functions-eventhubs-extension/issues/104

Track 1 PR:
- https://github.com/Azure/azure-functions-eventhubs-extension/pull/105

### Expected behavior

Have the EH Listener also stop itself on the call to Dispose() (and skip checkpointing if disposed) is the safest path.

### Actual behavior

This means that the following scenario can result in a `Listener` being disposed before it is stopped:

> 1. Initial call to `StartAsync()` fails, resulting in the retry `Task` being started.
> 2. While in the middle of a retry (calling `StartAsync()`, but `_started` is still `false), the host is shut down, meaning StopAsync()` is called.
> 3. The call to `StopAsync()` returns quickly without doing anything, meaning the `Listener` can now be disposed.
> 4. The `StartAsync()` completes and calls `StopAsync()` here: https://github.com/Azure/azure-webjobs-sdk/blob/dev/src/Microsoft.Azure.WebJobs.Host/Listeners/FunctionListener.cs#L119

If a Listener doesn't anticipate this, it is possible that it can invoke some functions on a disposed host, resulting in a `HostDisposedException`. This happens to the EventHub trigger, for example, because it doesn't seem to do anything in `Dispose`: https://github.com/Azure/azure-functions-eventhubs-extension/blob/dev/src/Microsoft.Azure.WebJobs.Extensions.EventHubs/Listeners/EventHubListener.cs#L72.

### Reproduction Steps

See `Relevant Track 1 Issues` in `Describe the bug`

**Comment by jsquire** [comment]
@JoshLove-msft:  I assigned this over based on the assumption that if you slotted into this milestone you were planning on picking it up.   Feel free to reslot if that's not the case.

**Comment by JoshLove-msft** [comment]
Yep, I hadn't self assigned it yet because I was actually going to check with you to see if you were interested in fixing it 😄
