### ISSUE TITLE
More Clarity needed: How to set up the Managed Identity so a developer can connect local Azure Func app to CosmosDB on Azure

### ISSUE THREAD

**Issue by PingPongSet** [Azure/azure-sdk-for-net#27077]
Great post below. But I need more information on how to set up the Managed Identity so a developer can connect a local Azure Func app to a CosmosDB on Azure

https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f73df56-2312-5851-7b59-3dfb766e5f66
* Version Independent ID: 31be349e-063e-6696-bc5f-752c413fa079
* Content: [Azure Identity client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet)
* Content Source: [api/overview/azure/identity-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/identity-readme.md)
* Service: **identity**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by christothes** [comment]
Hi @PingPongSet -  Unfortunately, we don't have a new WebJob extension library in this repository that integrates with Azure.Identity. However, does the following documentation help at all? https://docs.microsoft.com/en-us/azure/cosmos-db/managed-identity-based-authentication#assign-a-system-assigned-managed-identity-to-a-function-app

**Comment by PingPongSet** [comment]
> Hi @PingPongSet - Unfortunately, we don't have a new WebJob extension library in this repository that integrates with Azure.Identity. However, does the following documentation help at all? https://docs.microsoft.com/en-us/azure/cosmos-db/managed-identity-based-authentication#assign-a-system-assigned-managed-identity-to-a-function-app

Hi @christothes 
The content in that link is not working. 
As part of this document, it should have provided at least a link to show how to set up the relevant Managed Identity.
Out of curiosity, why did you need a WebJob extension library to add a link to this document if that document is already available?

**Comment by christothes** [comment]
> Hi @christothes The content in that link is not working. 

Could you clarify what specifically did not work? What problem or error did you run into?
