### ISSUE TITLE
[QUERY] Why is key auth authentication slow in Azure?

### ISSUE THREAD

**Issue by lukos** [Azure/azure-sdk-for-net#27075]
### Library name and version

Azure.Identity 1.5.0.0

### Query/Question

We are running microservices in AKS and these services need to connect to Azure Key Vault to retrieve secrets. However, I am seeing excessive latency around the AD calls to make this work.

I setup the `SecretClient` like this:

```c#
var kvClient = new SecretClient(new Uri(url), new ClientSecretCredential(tenantId, clientId, clientSecret));
```

but when calling a method which access the key vault, I see times like these:

![image](https://user-images.githubusercontent.com/581018/154461945-10a38590-5d7d-4c8e-808c-d1449c46ebdb.png)

It all works OK but just seems a very slow and clunky way of accessing something when I am passing clientid and secret directly to the key vault client. Sometimes it is quick but this extra dependency would really hurt performance at scale. Is this just something that happens once or could it happen each time we make a call to the key vault?

### Environment

Microservices are dotnet core 3.1 running on AKS v 1.21.9

**Comment by christothes** [comment]
Hi @lukos  - What you are seeing is most likely delay from AAD itself, rather than something the client is doing. However, the token should be cached for all subsequent requests. Please let us know if that is not the case.

**Comment by lukos** [comment]
I'm seeing quite a lot of variation but still getting 100ms response times from the key vault, which isn't amazing (I am fetching secrets, not keys). In comparison, calls to an Azure database are between 2 and 12ms.

Due to the level of traffic, I think I might just re-architect it to store the secrets in the DB and forgo the key vault completely. I might also try some short-term caching but since these are DKIM keys, they can be updated in a non-deterministic way so I won't be able to cache them for too long.

**Comment by christothes** [comment]
Hi @lukos That makes sense. According to the [Key Vault documentation](https://docs.microsoft.com/en-us/azure/key-vault/general/overview-throttling), caching is recommended rather than using it as a real-time database.
