### ISSUE TITLE
[FEATURE REQ] Be able to configure in AddAzureClients method some initialization for Azure service clients.

### ISSUE THREAD

**Issue by TechWatching** [Azure/azure-sdk-for-net#27085]
### Library name

Microsoft.Extensions.Azure

### Please describe the feature.

When using `Microsoft.Extensions.Azure` package to register a ****ServiceClient it would be grate to be able to have some overrides on the methods that register the clients to provide a lambda that gets executed once a client is first instantiated.

For instance let's say I am using `AddAzureClients` to register a TableServiceClient and that I want a specific table to be created if it does not yet exists. I don't want to to call `client.CreateTableIfNotExistsAsync` in each methods of the service where the `TableServiceClient` will be injected. And I don't want to new up a `TableServiceClient` in Startup.cs/Program.cs while I register another one with `AddAzureClients`.

So what I would need is something like this : 
```csharp
services.AddAzureClients(builder =>
{
    builder.AddTableServiceClient(connectionString, async tableServiceClient =>
    {
        await tableServiceClient.CreateTableIfNotExist("table");
    });
});
```
The lambda would be executed once the client is first instanciated.
This is an example with TableServiceClient but would be great for other clients (for blobs when you need to create a container if it does not yet exists for isntance).

**Comment by pallavit** [comment]
@christothes is this still valid and something you see us doing in the near future?
