### ISSUE TITLE
Is it possible to instantiate an ArmClient instance with only an access token?

### ISSUE THREAD

**Issue by cveld** [Azure/azure-sdk-for-net#27081]
I am looking for an example how we can instantiate an ArmClient instance with only an access token on the bearer header.
We see many ways to create a TokenCredential instance, but no option to instantiate one based on an access token.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08c655e7-2704-ae65-5566-66e81f8325cc
* Version Independent ID: df24bcf7-705f-c374-fc9c-bae7f0529a9d
* Content: [ArmClient Class (Azure.ResourceManager) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.resourcemanager.armclient?view=azure-dotnet-preview)
* Content Source: [xml/Azure.ResourceManager/ArmClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager/ArmClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by liurunliang** [comment]
Hi @cveld, you can instantiate an ArmClient instance with a customized ```TokenCredential```. Here is an example for you.
```
public class BearerTokenCredential : Azure.Core.TokenCredential
{

    /// <param name="token">The bearer access token value.</param>
    /// <param name="dateTimeOffset">The bearer access token expiry date.</param>
    public BearerTokenCredential(string token,DateTimeOffset dateTimeOffset)
    {
        accesstoken = new AccessToken(token, dateTimeOffset);
    }

    private AccessToken accesstoken;

    public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken) => accesstoken;

    public override ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken) => new ValueTask<AccessToken>(accesstoken);
}
```
Then instantiate ArmClient class with ```CustomizedTokenCredential``` .
```
var credential = new BearerTokenCredential("bearer access token value", DateTimeOffset.Now.AddSeconds(3600));
ArmClient client = new ArmClient(credential);
```

**Comment by cveld** [comment]
Would be cool if the "logistics" part of the thread could be separated out from the Q&A part of the thread :-) Anyways your answer was really helpful! I will close the issue.

**Comment by anshulahuja98** [comment]
Had a similar requirement, thanks for sharing this.
