### ISSUE TITLE
[EventHub] Deploy test resources failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#27098]
EventHub nightly test runs are failing with:

> VERBOSE: Running registered exit actions
> VERBOSE: Logging out of service principal '***'
> VERBOSE: Performing the operation "New-TestResources.ps1" on target "***".
> Write-Error: /mnt/vss/_work/1/s/eng/common/TestResources/New-TestResources.ps1:732
> Line |
>  732 |          $deployment = Retry {
>      |                        ~~~~~~~
>      | Exception calling "Invoke" with "0" argument(s): "The running
>      | command stopped because the preference variable
>      | "ErrorActionPreference" or common parameter is set to Stop:
>      | 20:43:24 - The deployment 't59743865b5e14c63' failed with
>      | error(s). Showing 1 out of 1 error(s). Status Message:
>      | Namespace status can only be changed to Active Or Disabled.
>      | (Code:BadRequest)  CorrelationId:
>      | a1efffa0-24c0-46a4-a7c0-4c6cb2ccd88f"
> 
> ##[error]PowerShell exited with code '1'.

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1374880&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1371624&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
There is a service deployment issue in the Canary environment.   This is not under our control; we can only wait for a new deployment from the service team.  Closing this out.
