### ISSUE TITLE
[FEATURE REQ] Push message to the back of the queue

### ISSUE THREAD

**Issue by preardon** [Azure/azure-sdk-for-net#27118]
### Library name

Azure,Messaging.ServiceBus

### Please describe the feature.

When using the ServiceBusReceiver Peak Message there are the follow options

- Abandon (release lock and put back up for processing)
- Complete (Ack off the Queue)
- Dead Letter (Send to the Dead letter sub queue)
- Defer (defer for processing later and don't re appear on the queue)

Ideally when I have a transient failure what I would like is a way to Say "Go to the Back of the Queue" or "Hide on the queue for x Timespan the re appear as an unprocessed message"

At the moment the best option I have is to use a ServiceBusSender to Post the message as a new message onto the Topic (potentially with a delay) which means

- In my Message Pump I need to provide both a sender and receiver
- I need to give my Message pump Permissions to both Send and Receive (instead of just receive)
- All other subscriptions also receive this new delayed message (Which if there is a wider transient issue is going to cause somewhat of a storm (I do limit my max retries via a custom header))

Please let me know what you think, and I am happy to pitch in a write a PR for this (with any guidance) if this is something you would like

**Comment by jsquire** [comment]
Hi @preardon.   Thank you for your feedback.   Unfortunately, this feature is something that would require service support to accomplish.   In a purely client-side implementation, the client would need to take the same steps that you describe above and require the same permissions to do so.   

I've transferred this to the [Azure\azure-service-bus](https://github.com/Azure/azure-service-bus) repository, where the service team tracks feature requests, as [#464](https://github.com/Azure/azure-service-bus/issues/464).  Should the functionality be added to the Service Bus service, the client library will support it.

**Comment by preardon** [comment]
@jsquire thanks for pointing me in the right direction
