### ISSUE TITLE
Unify behavior of clientId and resourceId

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-for-net#27112]
Recently we added the ability to set both a `clientId` and `resourceId` for user assigned managed identity lookups. This exposes the problem that if an environment sets `AZURE_CLIENT_ID` while the deployed code sets `resourceId` we'll hit an exception.

The work item here is two parts:
- [ ] decide what the correct behavior is when the environment variable is set. Do we throw? Do we always prefer the code value?
- [ ] Ensure that behavior across all languages.

**Comment by joshfree** [comment]
Related

- https://github.com/Azure/azure-sdk-for-java/issues/27213
- https://github.com/Azure/azure-sdk-for-js/issues/20461
- https://github.com/Azure/azure-sdk-for-python/issues/23142

**Comment by joshfree** [comment]
note from standup: If both fields are configured then we should throw
