### ISSUE TITLE
Please explain what a query string for this method can look like

### ISSUE THREAD

**Issue by BitBender1** [Azure/azure-sdk-for-net#27114]
this documentation page should maybe explain what the query-string can actually be, or point to another page that explains the possible query syntax. I am new to this function I have no idea what a query against a datalake-file could actually be or what syntax it could have. there is no chance I will randomly guess a working query, so there should be more information about the query string beyond it beeing a string and it beeing a query
Thank you :)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08afb360-f71f-5667-d695-546e531313ac
* Version Independent ID: 3ca63d38-4be0-5e83-3100-265697dece59
* Content: [DataLakeFileClient.Query(String, DataLakeQueryOptions, CancellationToken) Method (Azure.Storage.Files.DataLake) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakefileclient.query?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Files.DataLake/DataLakeFileClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.DataLake/DataLakeFileClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@BitBender1 Apologies for the late reply. Thanks for the feedback. We have created a PR Azure/azure-docs-sdk-dotnet#2141 to address this issue. It is currently pending on review.
