### ISSUE TITLE
[FEATURE REQ] DocumentAnalysisClient - Support extensions Dependency Injection

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-sdk-for-net#27123]
### Library name

Azure.AI.FormRecognizer

### Please describe the feature.

Many of the new Azure SDKs add extension method support for ease of dependency injection registration. This actually already exists in this library but only for [`AddFormRecognizerClient`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClientBuilderExtensions.cs)

Given the new clients releases as part of 4.0.0-beta.3, it would be great to have this consistent for the new `DocumentAnalysisClient`, hopefully following on in the similar mantra of `AddDocumentAnalysisClient`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @wahyuen.

In response to your feedback, we have added the requested `AddDocumentAnalysisClient` extension methods to our library (PR is here: https://github.com/Azure/azure-sdk-for-net/pull/27168). It will become available in our next beta release, but we don't have a release date yet. I'll keep this issue open and let you know once we have the package out.

If this is blocking you, you can try using our [NuGet Package Dev Feed](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#nuget-package-dev-feed) to consume the alpha package containing this feature. I suggest targeting version `4.0.0-alpha.20220223.2`.

**Comment by kinelski** [comment]
Azure.AI.FormRecognizer 4.0.0-beta.4 is out ([package here](https://www.nuget.org/packages/Azure.AI.FormRecognizer/4.0.0-beta.4)). Closing this issue since the requested feature has shipped. Feel free to open a new issue if you have further questions.
