### ISSUE TITLE
[FEATURE REQ] Support binding to a specific 'SessionId' property in ServiceBusTrigger

### ISSUE THREAD

**Issue by olitomlinson** [Azure/azure-sdk-for-net#27120]
### Library name

Microsoft.Azure.Webjobs

### Please describe the feature.

My use case is I'm using Azure Functions runtime as part of an ACI deployment. 

Each tenant in my multi-tenant system gets their own ACI instance. I want to use Session affinity to route & queue work to the correct ACI instance for each tenant.

To achieve this I want to use `ServiceBusTrigger` with a binding to a **specific** `SessionId`. At the moment this feature is not available on the trigger.

Example : _assume the tenant Id is 123._

```c#
 public static void Run([ServiceBusTrigger(queueName: "myQueue", sessionId: "123", Connection = "ServiceBusConnection")]string myQueueItem, ILogger log)
 {
      log.LogInformation($"C# ServiceBus queue trigger function processed message: {myQueueItem}");
 }
```

In reality, I would make this binding read its value from configuration

```c#
 sessionId:"%sessionId%"
```

**Notes**

I already have the ACI lifecycle managed via Durable Functions.

**Alternatives**

- Do not use Azure Functions Runtime, but use the QueueClient directly. Not terribly attractive as I want to make use of other binding types when handling a service bus message
- Use Queue per tenant, rather than Session per tenant. Not attractive as I don't want to programmatically/dynamically manage queue infrastructure.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @olitomlinson,
Can you clarify what version of the Service Bus extension you are using?

**Comment by olitomlinson** [comment]
@JoshLove-msft 

```xml
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.2.0" />
<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.6.0" />
```

**Comment by sonic1981** [comment]
Can we get some feedback as to why this and the related feature have been closed? Is this done or is this not going to be done? It did have milestones and now it doesn't so some update as to what is going on would be nice @JoshLove-msft ?

**Comment by olitomlinson** [comment]
Keep alive
