### ISSUE TITLE
Setting Timestamp does not publish custom metric at datetime set in Timestamp property

### ISSUE THREAD

**Issue by a30006441** [Azure/azure-sdk-for-net#27128]
Setting Timestamp does not publish custom metric at datetime set in Timestamp property

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15654394-9de6-0024-2e9b-727f09ff03a0
* Version Independent ID: a2554ff1-4e4a-c042-3072-f4b1a75fd47b
* Content: [MetricTelemetry.Timestamp Property (Microsoft.ApplicationInsights.DataContracts) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.metrictelemetry.timestamp?view=azure-dotnet)
* Content Source: [xml/Microsoft.ApplicationInsights.DataContracts/MetricTelemetry.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights.DataContracts/MetricTelemetry.xml)
* Service: **application-insights**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@a30006441 I am not able to reproduce the issue and I could see `timestamp` being sent to Cutom Metric.  See below 
![image](https://user-images.githubusercontent.com/38112130/155242303-5df5da9c-8537-42c2-bb64-b466fb01a15c.png)

**Comment by SaurabhSharma-MSFT** [comment]
@a30006441 We are proceeding with the closure of this issue as we haven't received any response. Please feel free to open a new issue for any other issues.
