### ISSUE TITLE
[BUG] ReceiveDeferredMessageAsync with PeekLock doesn't renew lock

### ISSUE THREAD

**Issue by serge-portima** [Azure/azure-sdk-for-net#27130]
### Library name and version

Azure.Messaging.ServiceBus 7.6.0

### Describe the bug

When calling DeferMessageAsync on a ServiceBusReceiver, the lock of the message you retrieve isn't renewed.
Meaning if the lock duration is expired one will not be able to acknowledge the message has been "Completed".

### Expected behavior

The lock was renewed and one can Complete the message.

### Actual behavior

The lock is not renewed and trying to Complete the message will throw
"The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance. (MessageLockLost)".

### Reproduction Steps

Create a deferred message, **wait for its lock to expires** then run the following:
```csharp
    async Task ProcessDeferred(int maximumMessageToSearch)
    {
        var messages = await receiver.PeekMessagesAsync(maximumMessageToSearch);

        if (messages != null && messages.Any())
        {
            foreach (var deferred in messages.Where(m => m.State == ServiceBusMessageState.Deferred))
            {
                Console.WriteLine($"Processing deferred message {deferred.MessageId}");
                var message = await receiver.ReceiveDeferredMessageAsync(deferred.SequenceNumber);

                // { add you processing here }

                await receiver.CompleteMessageAsync(message);

                Console.WriteLine($"Deferred message {deferred.MessageId} has been processed.");
            }
        }
    }
    
    await ProcessDeferred(10);
```

### Environment

.Net 6

**Comment by JoshLove-msft** [comment]
@serge-portima can you clarify how long your processing is taking? The messages received using the ServiceBusReceiver (whether active or deferred) won't have their locks renewed automatically, so if your processing is taking longer than the queue's lock duration, the lock will be lost.

**Comment by serge-portima** [comment]
> @serge-portima can you clarify how long your processing is taking? The messages received using the ServiceBusReceiver (whether active or deferred) won't have their locks renewed automatically, so if your processing is taking longer than the queue's lock duration, the lock will be lost.

Not long, the processing time doesn't matter, one could retrieve a message and try to complete is as next operation it will fail as the lock of a deferred message you retrieve is not acquired/renewed.

The step to reproduce the bug is:


Imagine your topic lock duration is set to 5 seconds:

- Send a message
- Receive it
- Defer it
- Wait for 6 (5 + 1) seconds
- Receive the deferred message (lock not acquired/renewed)
- Try to complete it

**Comment by serge-portima** [comment]
Here a complete example on how to reproduce the issue.

`using Azure.Identity;
using Azure.Messaging.ServiceBus;

const string ToDefer = nameof(ToDefer);
const string UnDefer = nameof(UnDefer);

const string TopicName = "demo-deferred-sj";
const string ServiceBusNamespace = "#######";
const string SubscriptionName = "all";

var oneSecondMoreThanLockDuration = TimeSpan.FromSeconds(6);

var userName = System.Environment.GetEnvironmentVariable("USERNAME");

var serviceBusClient = new ServiceBusClient(
    $"{ServiceBusNamespace}.servicebus.windows.net",
    new VisualStudioCredential()
);

var sender = serviceBusClient.CreateSender(TopicName);
var processor = serviceBusClient.CreateProcessor(TopicName, SubscriptionName, new ServiceBusProcessorOptions
{
    AutoCompleteMessages = false
});
var receiver = serviceBusClient.CreateReceiver(TopicName, SubscriptionName);

async Task SendMessagesAsync(string kind, string param = "", DateTimeOffset? scheduleTime = null)
{
    var messageId = $"{kind}|{userName}|{param}|{Guid.NewGuid()}";
    Console.WriteLine($"Sending {messageId}"
        + (scheduleTime.HasValue ? $" scheduled for {scheduleTime}" : "")
    );
    var serviceBusMessage = new ServiceBusMessage()
    {
        MessageId = messageId
    };
    if (scheduleTime.HasValue)
    {
        serviceBusMessage.ScheduledEnqueueTime = scheduleTime.Value;
    }
    await sender.SendMessageAsync(serviceBusMessage);
}

async Task ProcessMessageAsync(ProcessMessageEventArgs args)
{
    Console.WriteLine($"Handling {args.Message.MessageId} ");

    var messageParts = args.Message.MessageId.Split('|');
    var kind = messageParts[0];
    var user = messageParts[1];
    var param = messageParts[2];

    if (user != userName)
    {
        Console.WriteLine($"Caution handling message of another user: {user}");
    }

    switch (kind)
    {
        case ToDefer:
            await args.DeferMessageAsync(args.Message);
            var scheduleTime = args.Message.EnqueuedTime + oneSecondMoreThanLockDuration;
            await SendMessagesAsync(UnDefer, args.Message.SequenceNumber.ToString(), scheduleTime);
            break;
        case UnDefer:
            var deferredMessage = await receiver.ReceiveDeferredMessageAsync(long.Parse(param));
            Console.WriteLine($"Deferd message {deferredMessage.MessageId} processed");
            await args.CompleteMessageAsync(args.Message);
            try
            {
                // THIS WOULD DELETE THE MESSAGE IF THE LOCK WAS STILL ON
                await receiver.CompleteMessageAsync(deferredMessage);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Ignoring {ex.Message}");
            }

            break;
    }
}

processor.ProcessMessageAsync += ProcessMessageAsync;
processor.ProcessErrorAsync += eventArgs =>
{
    Console.WriteLine(eventArgs.Exception.Message);

    return Task.CompletedTask;
};

var cancellationTokenSource = new CancellationTokenSource();
await processor.StartProcessingAsync(cancellationTokenSource.Token);

await SendMessagesAsync(ToDefer);

Console.ReadKey();
cancellationTokenSource.Cancel();`

**Comment by JoshLove-msft** [comment]
I've only been able to repro the issue when I put a breakpoint and intentionally wait for the lock duration to expire. When receiving the deferred messages using the receiver, there is no automatic lock renewal happening, so you would need to complete the message within 5 seconds. If I let the application run without breaking, it completes the deferred message without throwing an exception. Can you try increasing the lock duration to see if you are still seeing the issue?

**Comment by serge-portima** [comment]
> I've only been able to repro the issue when I put a breakpoint and intentionally wait for the lock duration to expire. When receiving the deferred messages using the receiver, there is no automatic lock renewal happening, so you would need to complete the message within 5 seconds. If I let the application run without breaking, it completes the deferred message without throwing an exception. Can you try increasing the lock duration to see if you are still seeing the issue?

Did you adapt the value of "oneSecondMoreThanLockDuration" to match your topic's subscription settings? You wouldn't need to set a breakpoint if you did. At least that's how it behave on my side.

**Comment by JoshLove-msft** [comment]
> > I've only been able to repro the issue when I put a breakpoint and intentionally wait for the lock duration to expire. When receiving the deferred messages using the receiver, there is no automatic lock renewal happening, so you would need to complete the message within 5 seconds. If I let the application run without breaking, it completes the deferred message without throwing an exception. Can you try increasing the lock duration to see if you are still seeing the issue?
> 
> Did you adapt the value of "oneSecondMoreThanLockDuration" to match your topic's subscription settings? You wouldn't need to set a breakpoint if you did. At least that's how it behave on my side.

Yes, I actually updated the lock duration to be 5 seconds to match your description.

**Comment by serge-portima** [comment]
Here's my configuration, maybe there something in there which leads to this undesirable behavior.
![Topic](https://i.ibb.co/5j2yKFF/topic.png)
![subscription](https://i.ibb.co/86bwFGR/Subscription.png)

And with that I always get the same result
![console](https://i.ibb.co/xCGqcBZ/Console.png)
