### ISSUE TITLE
[QUERY]How to replace IMessageSession.ReceiveAsync() in new Azure.Messaging.ServiceBus?

### ISSUE THREAD

**Issue by caiyiJu** [Azure/azure-sdk-for-net#27138]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.2.0

### Query/Question

Hi,
When trying to update code that use Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.1" to new 5.2.0. There are some differences.

code when using version 4.1.1
```csharp
public async static Task RunAsync([ServiceBusTrigger("%queuename%", Connection = "ServiceBusStorageConnectionString", IsSessionsEnabled = true)]
        Message message, IMessageSession messageSession, 
            ILogger log)
        {
            var msgs=await messageSession.ReceiveAsync(10);
```

code when using version 5.2.0

```csharp
public async static Task RunAsync([ServiceBusTrigger("%queuename%", Connection = "ServiceBusStorageConnectionString", IsSessionsEnabled = true)]
        ServiceBusReceivedMessage message, ServiceBusSessionMessageActions messageSession,
            ILogger log)
```

How to call: messageSession.ReceiveAsync() now?

### Environment

Net core 3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by caiyiJu** [comment]
Hello team, could we have an update for this?

**Comment by JoshLove-msft** [comment]
@caiyiJu, can you explain why you want to receive another message from your function? The function already executes whenever a message is received.

**Comment by caiyiJu** [comment]
@JoshLove-msft As batch and concurrent session cannot be used together per [the documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus). Will it be more efficient if we receive another message at the same time? By the way, could you explain why the method is removed if there is no such method in the new version? This will also be helpful to understand the usage.
<html>
<body>


maxConcurrentSessions | 8 | The maximum number of sessions that can be handled concurrently per scaled instance. This setting only applies for functions that receive a single message at a time.
-- | -- | --



</body>
</html>

**Comment by JoshLove-msft** [comment]
I think using the function in that way to receive additional messages is a workaround for what you would really want - session concurrency when using batch receive, right? If that's the case, I'd rather attempt to address this by extending maxConcurrentSessions to work for functions that take an array of messages.

**Comment by caiyiJu** [comment]
@JoshLove-msft  Thanks for your update. If session concurrency when using batch receives is possible, it would be great. If not, please help to explain how to receive additional messages in the new sdk version. Or why it is removed from the new sdk version.

**Comment by caiyiJu** [comment]
@JoshLove-msft Hello, is there any update?

**Comment by JoshLove-msft** [comment]
Hi @caiyiJu,
We are investigating how best to implement this feature. We will either add the concurrency support for batch receiving or expose the receive method. We are planning to work on this in March and hope to ship an update in April.

**Comment by grzegorz-w13** [comment]
@[JoshLove-msft](https://github.com/JoshLove-msft) I've forgotten to tag You. Can You provide me an answer?

**Comment by JoshLove-msft** [comment]
Still investigating this. We may need to expose the receive method here.

**Comment by JoshLove-msft** [comment]
@grzegorz-w13 @caiyiJu - would you expect that the options configured for the processor also apply to messages that are received here? For instance, should messages be received from within your function also have the message locks autorenewed and be autocompleted? Or do you expect that these should be managed independently?

**Comment by grzegorz-w13** [comment]
@JoshLove-msft 
If there is an option of autorenew and autocompletion it would be great! Currently I have to do it manually and it would be perfect to have it given out of the box. In my process I'd like to treat them in more-less transactional way. If I'm not able to get them all before timeout - abandon them all and try again later - if I receive them all I can process them and complete them once function ends.

**Comment by grzegorz-w13** [comment]
@JoshLove-msft 
Hi!
Is it possible that ServiceBusTrigger which uses sessions and ServiceBusReceivedMessage[] in future will be executed in parallel? 
Since we can have multiple active sessions at the same time why we cannot have concurrent function calls for them at the same time?
