### ISSUE TITLE
Reference page for "EnvironmentCredential Class" showing new beta feature and old package version

### ISSUE THREAD

**Issue by dujiulun** [Azure/azure-sdk-for-net#27133]
Hi,

[The reference page for "`EnvironmentCredential` Class"](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet#feedback) is showing a new environment variable `AZURE_CLIENT_SEND_CERTIFICATE_CHAIN`, which is added in `1.6.0-beta1` and [not present in `1.5.0`](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Identity_1.5.0/sdk/identity/Azure.Identity/src/EnvironmentCredential.cs). However the line "Package: Azure.Identity v1.5.0" is shown on the same page, which might cause a misconception that the feature is present in that version of the package.

![image](https://user-images.githubusercontent.com/5555270/154983146-14c36c3b-22de-4c4e-a537-20cc797ac29f.png)

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 746a0917-2bf5-6156-dcd6-b8e151de2319
* Version Independent ID: 449899e0-1e82-9375-9494-09c884627199
* Content: [EnvironmentCredential Class (Azure.Identity) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet)
* Content Source: [xml/Azure.Identity/EnvironmentCredential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Identity/EnvironmentCredential.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.
