### ISSUE TITLE
Variable name inconsistent

### ISSUE THREAD

**Issue by henrybeen** [Azure/azure-sdk-for-net#27135]
All examples use a variable named cosmosClient to instantiate the CosmosClient, but the next line expects a variable called client. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 518ce5b7-5bf3-c3f7-8706-f02de23a1477
* Version Independent ID: 0e97660f-aceb-2e01-cbbc-9f69cd0f3bbf
* Content: [CosmosClient Class (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclient?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/CosmosClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/CosmosClient.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@henrybeen Apologies for the late reply. the above PR Azure/azure-cosmos-dotnet-v3#3046 has been filed to address this issue. It is currently pending under review. In the meantime, if you have any questions, please feel free to ask.
