### ISSUE TITLE
Custom endpoint for connection establishment 

### ISSUE THREAD

**Issue by Joseandresc** [Azure/azure-sdk-for-net#27143]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

Currently there is no way to specify an endpoint other than the FQDN of the namespace, specificying a custom endpoint is useful in scenarios where customers might not to connect through a custom domain that points to a Firewall, proxy, waf, etc. 
This feature was implemented in the Event Hubs SDK https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubConnectionOptions.cs#L108, would be great to also implement such feature within the Service Bus SDK.

**Comment by jsquire** [comment]
//fyi:  @ramya-rao-a

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
This has been addressed and will be available in an upcoming release.
