### ISSUE TITLE
Not All Valid String Values are Listed For ContentType

### ISSUE THREAD

**Issue by jonlave** [Azure/azure-sdk-for-net#27151]
The page shows an example value of "text/plain" for a password, but certificates are also used in the parent class KeyvaultSecret, and through debugging, I found that the content type can be "application/x-pem-file" or "application/x-pkcs12". These should be listed in the documentation.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c07a8a21-3e21-c2ca-86de-060d6bcda6c9
* Version Independent ID: 1cd6cd94-2651-754c-d993-f0bca2358d2f
* Content: [SecretProperties.ContentType Property (Azure.Security.KeyVault.Secrets) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.security.keyvault.secrets.secretproperties.contenttype?view=azure-dotnet#azure-security-keyvault-secrets-secretproperties-contenttype)
* Content Source: [xml/Azure.Security.KeyVault.Secrets/SecretProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Security.KeyVault.Secrets/SecretProperties.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
"text/plain" is typical for most secrets. If you choose to store a certificate yourself using secrets instead of the Azure.Security.KeyVault.Certificates SDK to manage certificates, you can choose whatever content type you like. As the documentation states, "text/plain" is only an example.
