### ISSUE TITLE
Mobile authenIcarian is limited when authenticating using the Azure.Identity methods

### ISSUE THREAD

**Issue by norton287** [Azure/azure-sdk-for-net#27156]
[Enter feedback here]

---
#### Document Details
Can more mobile friendly authentication methods be provided in the documentation?

A majority of the Azure.Identity methods used in the docs are restricted from use on mobile.

A goodvexample is ClientSecretCredential method which should be allowed on mobile platform development.

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 918d059f-8e92-166e-e98d-f89a097c67f8
* Version Independent ID: 2a956f03-1dbe-086a-9b07-0ae1217c50fb
* Content: [BlobContainersOperationsExtensions.SetLegalHold(IBlobContainersOperations, String, String, String, IList&lt;String&gt;, Nullable&lt;Boolean&gt;) Method (Microsoft.Azure.Management.Storage) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.blobcontainersoperationsextensions.setlegalhold?view=azure-dotnet-preview#microsoft-azure-management-storage-blobcontainersoperationsextensions-setlegalhold(microsoft-azure-management-storage-iblobcontainersoperations-system-string-system-string-system-string-system-collections-generic-ilist((system-string))-system-nullable((system-boolean))))
* Content Source: [xml/Microsoft.Azure.Management.Storage/BlobContainersOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Storage/BlobContainersOperationsExtensions.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@norton287 Redirecting this to relevant team to update the documentation accordingly.
