### ISSUE TITLE
[FEATURE REQ] Support for Azure Workload Identity Federation

### ISSUE THREAD

**Issue by konidev20** [Azure/azure-sdk-for-net#27159]
### Library name

Azure.Identity

### Please describe the feature.

Request to add support for environment variables supported by Azure Workload Identity Federation for Kubernetes service accounts and other providers.

My Use case:
Using the federated token to authenticate with Azure services from Azure Kubernetes Service. This I believe is possible through [Ref.1].

The environment variables I mentioned above is linked to [Ref.2] which speaks about the mutation webhook controller installed on Kubernetes to use the token.

[Ref.1] https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation
[Ref.2] https://blog.baeke.info/2022/01/31/kubernetes-workload-identity-with-aks/

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by mnj** [comment]
I have been running into this as well, it works with the old Microsoft.Identity package, but not Azure.Identity, when using Azure.Identity I get the attached stack trace, which is not expected, the sample from the azure workload identity (which is the supposed "new" replacement for Azure AD Pod Identity)

The environment variables exposed to the container are:
 Environment:
      ASPNETCORE_ENVIRONMENT:      Development
      AZURE_CLIENT_ID:             <SP/App registration>
      AZURE_TENANT_ID:             <tenent-id>
      AZURE_FEDERATED_TOKEN_FILE:  /var/run/secrets/azure/tokens/azure-identity-token
      AZURE_AUTHORITY_HOST:        https://login.microsoftonline.com/
    Mounts:
      /var/run/secrets/azure/tokens from azure-identity-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pxtnm (ro)

This is a ASP.NET Core Web API app, using .NET 6 Core LTS.

[stack-trace.txt](https://github.com/Azure/azure-sdk-for-net/files/8634964/stack-trace.txt)

**Comment by konidev20** [comment]
@jsquire I found that ManagedIdentityCredential class actually has a method which finds the Environment Variables associated with Workload Identities. 

I believe there's no sufficient documentation available for this integration with Azure Kubernetes Service yet.

**Comment by christothes** [comment]
closing since this feature request is being tracked by 31465
