### ISSUE TITLE
Can this be updated to the latest packages and updated with the new method signatures

### ISSUE THREAD

**Issue by norton287** [Azure/azure-sdk-for-net#27155]
[Enter feedback here]
The provided example for using this has out of date SDK packages.  Can they be updated?  Also if you can use mobile friendly authentication would be nice as Azure.Identity has most methods excluded from mobile.

Refer to this for background

Isuue #26602 

[https://azure.microsoft.com/da-dk/resources/samples/storage-dotnet-resource-provider-getting-started/](url)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 918d059f-8e92-166e-e98d-f89a097c67f8
* Version Independent ID: 2a956f03-1dbe-086a-9b07-0ae1217c50fb
* Content: [BlobContainersOperationsExtensions.SetLegalHold(IBlobContainersOperations, String, String, String, IList&lt;String&gt;, Nullable&lt;Boolean&gt;) Method (Microsoft.Azure.Management.Storage) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.blobcontainersoperationsextensions.setlegalhold?view=azure-dotnet-preview#microsoft-azure-management-storage-blobcontainersoperationsextensions-setlegalhold(microsoft-azure-management-storage-iblobcontainersoperations-system-string-system-string-system-string-system-collections-generic-ilist((system-string))-system-nullable((system-boolean))))
* Content Source: [xml/Microsoft.Azure.Management.Storage/BlobContainersOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Storage/BlobContainersOperationsExtensions.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@norton287 We are routing this to services team to look into.

**Comment by tamram** [comment]
@norton287 - I've updated the sample with the latest packages.

**Comment by tamram** [comment]
@norton287 - Per @blueww comment on https://github.com/Azure/azure-sdk-for-net/issues/26602, please open another issue for mobile.

#please-close

**Comment by norton287** [comment]
This issue still viable I have already created another issue


From: Tamra Myers ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: February 24, 2022 at 12:39:50 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Can this be updated to the latest packages and updated with the new method signatures (Issue #27155)

**Comment by norton287** [comment]
@tamram  Do not close this as this still needs to be done and is an issue.  I have already opened all the issues @blueww requested.  Do NOT CLOSE THIS AS IT IS NEEDED TO BE DONE!

**Comment by tamram** [comment]
@norton287 - I'm sorry, what still needs to be done here? I've updated the packages in the sample application. What else are you looking for?

**Comment by norton287** [comment]
Update the method signatures for the updated packages


From: Tamra Myers ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: February 24, 2022 at 4:38:13 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Can this be updated to the latest packages and updated with the new method signatures (Issue #27155)

**Comment by tamram** [comment]
The project compiles as is. Which method signatures need to be updated?

**Comment by norton287** [comment]
Ok if it compiles fine go ahead and close. I was confused,. Wei wei has me opening so many issues I'm not sure which is which.


From: Tamra Myers ***@***.******@***.***)
Reply: Azure/azure-sdk-for-net ***@***.******@***.***)
Date: February 24, 2022 at 4:45:36 PM
To: Azure/azure-sdk-for-net ***@***.******@***.***)
CC: John Norton ***@***.******@***.***), Mention ***@***.******@***.***)
Subject: Re: [Azure/azure-sdk-for-net] Can this be updated to the latest packages and updated with the new method signatures (Issue #27155)

**Comment by tamram** [comment]
#please-close

**Comment by blueww** [comment]
Close this issue as the doc is updated to the latest package.
