### ISSUE TITLE
[BUG] Disabling cookies causes DPG tests to fail

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#27166]
### Library name and version

Azure.Core 1.23.0-20220121.1

### Describe the bug

When cookies are disabled, the following tests fail in the autorest.csharp `AutoRest.TestServerLowLevel.Tests` project:

![image](https://user-images.githubusercontent.com/21269347/155375941-7b425d31-f577-4e0b-98d4-6e065cc5565d.png)

#### HttpInfrastructureTests
![image](https://user-images.githubusercontent.com/21269347/155376029-002c548b-ad39-4b4a-a24a-2ceb8990f7c3.png)

#### Paging Tests
![image](https://user-images.githubusercontent.com/21269347/155376109-262f59a9-5555-4215-88a9-87794603e5fd.png)

#### LroTest
The LRO tests hang indefinitely.

![image](https://user-images.githubusercontent.com/21269347/155376240-a1cc3fa8-a0a9-41d8-99d9-8e437c664dbe.png)

### Expected behavior

All tests complete and pass.

### Actual behavior

When cookies are disabled, the following tests fail in the autorest.csharp `AutoRest.TestServerLowLevel.Tests` project:

![image](https://user-images.githubusercontent.com/21269347/155375941-7b425d31-f577-4e0b-98d4-6e065cc5565d.png)

#### HttpInfrastructureTests
![image](https://user-images.githubusercontent.com/21269347/155376029-002c548b-ad39-4b4a-a24a-2ceb8990f7c3.png)

#### Paging Tests
![image](https://user-images.githubusercontent.com/21269347/155376109-262f59a9-5555-4215-88a9-87794603e5fd.png)

#### LroTest
The LRO tests hang indefinitely.

![image](https://user-images.githubusercontent.com/21269347/155376240-a1cc3fa8-a0a9-41d8-99d9-8e437c664dbe.png)

### Reproduction Steps

Change core package version in AutoRest.CSharp.sln projects to 
    `<PackageReference Include="Azure.Core" Version="1.23.0-alpha.20220223.2" />`

Run AutoRest.TestServerLowLevel.Tests => tests should fail.

Enabling cookies makes tests succeed.

**Comment by annelo-msft** [comment]
It would be ideal if we could add relevant tests to the Azure.Core project to detect this kind of break earlier as part of the fix.

**Comment by christothes** [comment]
I discovered the cause of this issue and it is related to the autorest.testserver npm package that is used for these DPG tests. 

The test server internally uses cookies to track state for retries and LRO status check iterations:
https://github.com/Azure/autorest.testserver/blob/8f0c493a1bb7b99ba19df65226f15734940179a6/legacy/routes/httpResponses.js#L190-L198

The implementation for tests in the autorest.csharp project happens to be different for HLC and DPG client tests which is why only DPG is affected. We still need to investigate why these changes exist and how they are relevant.

**Comment by annelo-msft** [comment]
Thanks so much, @christothes for this investigation!!

**Comment by m-nash** [comment]
Is the implication here @christothes that if a customer is using cookies they will also be broken by design and must explicitly turn the setting on?

**Comment by christothes** [comment]
> Is the implication here @christothes that if a customer is using cookies they will also be broken by design and must explicitly turn the setting on?

More likely, this would be an issue if an Azure service required cookies. As far as we know this shouldn't be required by any service.

**Comment by m-nash** [comment]
> > Is the implication here @christothes that if a customer is using cookies they will also be broken by design and must explicitly turn the setting on?
> 
> More likely, this would be an issue if an Azure service required cookies. As far as we know this shouldn't be required by any service.

Are we relying on live test runs to validate this assumption?

**Comment by m-nash** [comment]
BTW can someone at Github please add the ability to reply directly to a top level comment instead of random quote replies all over the place?

**Comment by christothes** [comment]
> > > Is the implication here @christothes that if a customer is using cookies they will also be broken by design and must explicitly turn the setting on?
> > 
> > 
> > More likely, this would be an issue if an Azure service required cookies. As far as we know this shouldn't be required by any service.
> 
> Are we relying on live test runs to validate this assumption?

That and the fact that cookies have always been disabled for framework. It just so happens that autorest.csharp only builds and tests against netcoreapp3.1.
