### ISSUE TITLE
[QUERY] What is the difference between BeginUpdateAsync and UpdateAsync for update Mysql Flexible server configurations

### ISSUE THREAD

**Issue by wimeling** [Azure/azure-sdk-for-net#27162]
### Library name and version

Microsoft.Azure.Management.MySQL  1.0.0

### Query/Question

What is the difference between calling Configurations.BeginUpdateAsync and Configurations.UpdateAsync. I am confused at to what is the difference when using this for updating configurations on the MySql flexible server

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by liurunliang** [comment]
Hi @wimeling, the method without "Begin" will check the response and throw exception when the response shows something is wrong(such as The value 'A' for configuration 'audit_log_enabled' is not valid. The allowed values are 'ON,OFF'.), the method started with "Begin" doesn't.

**Comment by wimeling** [comment]
Thank you for your reply that clears it up. Is this knowledge that I could also have found in the documentation ?

**Comment by liurunliang** [comment]
I think not, I got it by diving into the source code.
