### ISSUE TITLE
[BUG] Service Bus Message receiver removes message from queue but message is not received

### ISSUE THREAD

**Issue by m-carter1** [Azure/azure-sdk-for-net#27163]
### Library name and version

Azure.Messaging.ServiceBus 7.6.0

### Describe the bug

If there is already a message in the queue **before the app starts** the message is removed from the queue when ReceiveMessageAsync is called but the message is not returned so it is lost!

Subsequent messages are received. 

This happens with all versions. It works fine locally.

Using Microsoft.Azure.ServiceBus also works fine. 

### Expected behavior

Message should be received

### Actual behavior

Message is lost

### Reproduction Steps

c# console app in kubernetes v1.21.7

add a message to the queue before the app is running

```
var _serviceBusClient = new ServiceBusClient(serviceBusConnectionString);
var _messageReceiver = _serviceBusClient.CreateReceiver(queuename);
var message = await _messageReceiver.ReceiveMessageAsync();
```

### Environment

Azure Kubernetes v 1.21.7
.net 6 (same issue netcore3.1)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by m-carter1** [comment]
Update

The deprecated library  Microsoft.Azure.ServiceBus started having the same issue. 

Going back to Azure.Messaging.ServiceBus, regenerating new access keys gets it working again (i.e. will pick up the 1st message on startup) and after more testing it appears that the issue starts to happen if ServiceBusClient isn't disposed of

Exiting the app and deleting the pod doesn't appear to be enough, it needs disposing.
Does this sound right?

**Comment by JoshLove-msft** [comment]
Hi @m-carter1,
Are you able to include a full repro? I have not seen the issue using the code provided.

**Comment by m-carter1** [comment]
@JoshLove-msft  please see repo here: https://github.com/m-carter1/MessageReceiverTest

It's a basic console app that waits (default time) for a message then stops. 

Once it starts, if you send a message with contents "1" (for example) then straight after send another message "2" you will see 1 appear in the logs of the app but message 2 is de-queued **and not processed**.

Be sure to set the container registry address, ServiceBusConnectionString and QueueName in the chart MessageReceiverTest.yaml

It works fine locally but the issues are present when deployed to azure kubernetes (v1.21.7)

**Comment by priyankar-dutta** [comment]
+ 1 facing same issue

**Comment by HarishMattaparthi** [comment]
+1 facing the same issue.

**Comment by JoshLove-msft** [comment]
> Going back to Azure.Messaging.ServiceBus, regenerating new access keys gets it working again (i.e. will pick up the 1st message on startup) and after more testing it appears that the issue starts to happen if ServiceBusClient isn't disposed of
Exiting the app and deleting the pod doesn't appear to be enough, it needs disposing.

So are you saying the issue only happens when stopping and restarting the app? Or does it happen even during a single run?

In general, you should dispose the ServiceBusClient in your applications. You can also dispose the ServiceBusReceiver when you are done using. 

I've seen similar issues due to the fact that we don't "drain" excess credits with the receiver. What may be happening is that if one of your receive attempts doesn't get back a message (because there are no messages in the queue), but you later send a message to the queue and start a new application instance, that first receiver that was not shut down cleanly gets the message delivered to it. I'd recommend disposing the ServiceBusClient and ServiceBusReceiver to see if that resolves the issue.

**Comment by JoshLove-msft** [comment]
Also, it would help to see the SDK logs, which you can enable by adding:
```c#
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
```
to the start of your program.

**Comment by m-carter1** [comment]
> > Going back to Azure.Messaging.ServiceBus, regenerating new access keys gets it working again (i.e. will pick up the 1st message on startup) and after more testing it appears that the issue starts to happen if ServiceBusClient isn't disposed of
> > Exiting the app and deleting the pod doesn't appear to be enough, it needs disposing.
> 
> So are you saying the issue only happens when stopping and restarting the app? Or does it happen even during a single run?
> 
> In general, you should dispose the ServiceBusClient in your applications. You can also dispose the ServiceBusReceiver when you are done using.
> 
> I've seen similar issues due to the fact that we don't "drain" excess credits with the receiver. What may be happening is that if one of your receive attempts doesn't get back a message (because there are no messages in the queue), but you later send a message to the queue and start a new application instance, that first receiver that was not shut down cleanly gets the message delivered to its receive link. I'd recommend disposing the ServiceBusClient and ServiceBusReceiver at the end of your program to see if that resolves the issue.

Yes the issue happens when an app has exited without disposing the ServiceBusClient/ServiceBusReceiver and a new app is started, where a new message is created in between the exit of the 1st app and the start of the new one.

We run 1 pod per message as a kubernetes scaled job. So when a message is created in the queue a scaled job will be created, it will process the message then close down. This is working fine now by ensuring that ServiceBusClient/ServiceBusReceiver are disposed of.

**Comment by JoshLove-msft** [comment]
Sounds good. I will go ahead and close this issue out. Please let feel free to reopen if you would like to discuss further.

**Comment by et1975** [comment]
I don't think it's a reasonable expectation - a host can always crash even if developer makes an effort to dispose... which also shouldn't be required, I'd expect the finalizer to do it.

**Comment by JoshLove-msft** [comment]
To be clear, the message wouldn't be "lost" unless receiving in ReceiveAndDelete mode. If receiving in PeekLock mode, it would still be delivered to one of the receivers.

**Comment by et1975** [comment]
> If receiving in PeekLock mode, it would still be delivered to one of the receivers.

Even if MaxDeliveryCount is reached?

**Comment by JoshLove-msft** [comment]
If the receiver is actively receiving messages, then the DeliveryCount will be incremented as the receiver is able to settle the message. If the link is just open, but no receives are happening, the message will be released when it is delivered and it will not impact the delivery count.
