### ISSUE TITLE
Retrieve the expiry date of the client secret

### ISSUE THREAD

**Issue by clement911** [Azure/azure-sdk-for-net#27176]
### Library name and version

Azure.Identity

### Query/Question

We use `ClientSecretCredential` to use the `ArmClient`, which works well so far.

However, we are concerned that the client secret has an expiry date. We'd like to generate some sort of warning if the client secret expires soon.
How can we use the SDK to fetch the expiry date of our app client secret?

![image](https://user-images.githubusercontent.com/3426504/155437216-d074508c-56d3-455f-bd01-5a07cc397396.png)

### Environment

Azure app service

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @clement911  - This information is not possible to retrieve with the Azure.Identiy client, however I believe this information can be queried with the [Graph API](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0).

**Comment by clement911** [comment]
That worked thanks.
```
var graphClient = new GraphServiceClient(creds);
var apps = await graphClient.Applications.Request().GetAsync();
var app = apps.Single(a => a.AppId == appId);
app.PasswordCredentials.First().EndDateTime;
```
