### ISSUE TITLE
[QUERY] Who is creating the Queue Message | servicebus dependency metric?

### ISSUE THREAD

**Issue by bh3605** [Azure/azure-sdk-for-net#27170]
### Library name and version

Azure.Messaging.Servicebus 7.4.0

### Query/Question

I'm investigating dependency metrics in our AI instance for the purpose of identifying and filtering out dependencies that provide us no value. One of the dependencies I'm seeing I believe is from the Azure.Messaging.Servicebus package. It's this "Queue Message | servicebus" dependency type. Who is sending this and what is it for? We use NServiceBus heartbeats and the ServiceBusSender, ServiceBusReciever, and Queue Message dependencies are contributing to our usage maxing out.

### Environment

N/A

**Comment by jsquire** [comment]
Hi @bh3605.   Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, I'm not sure what it is that you're referencing.  In order to make sure that we can get this to the right folks to assist, can you help me understand where you're looking in AI and what you're seeing?   If possible, a screenshot or exact message text would be the most helpful.

**Comment by bh3605** [comment]
Certainly! In fact here's a screenshot from an error this morning. It shows a POST action, the ServiceBusSender.Send metric which comes from Azure.Messaging.Servicebus and this Queue Message | servicebus metric whose origin I hope you can figure out.
![Message Metric AI Screenshot](https://user-images.githubusercontent.com/3073436/155573649-bda0530c-938d-44d5-abd4-b02d7882c129.PNG)

**Comment by jsquire** [comment]
Thank you for the additional context.  This is not something that the Service Bus client library directly controls.   We'll need to route this over to the Azure Montor team for their insights.

**Comment by jsquire** [comment]
@lmolkova: Do you have any thoughts?

**Comment by bh3605** [comment]
We use NServicBus which doesn't utilize any batch api that may exist in the SDK. It utilizes transactions, but you can be selectively on whether you want to send a message right this instant (using `Send(msg).ConfigureAwait(false);`) or remove the `ConfigureAwait()` to have it send when it gets a chance. Which is kind of like batching.

- We don't use any batching
- Visual noise is the main driver, and the current properties of the telemetry are not discrete enough. It's very general. It doesn't have the sender and receiver, and I also don't see them correlated to each other. I have written telemetry correlation for inbound and outbound messages. It provides the message headers in the custom properties and the message receive dependency is properly correlated to the correct message send dependency. You can actually imagine that relationship in the picture I attached above. If that wasn't a message send failure you would see a NServiceBus.Receive dependency under the scope of the NServiceBus.Send dependency.
- If I did use batching then I would want them to be traced independently

I wrote the telemetry correlation because I had no way to correlate a message to anything. AppInsights just showed these dependencies to the service bus. Being able to correlate is amazing. I can see the message type in the custom properties and everything my message handler did is correlated to the sender. The problem I have now, and I couldn't think of a good solution at the time, is I can't discern what queue is sending/receiving what message types. I just have a couple thousand NServiceBus.Send and Recieves laying around and zero clue what queue is sending/receiving or even what message type it is. I have to look at a database dependency and do a rough estimate of the time. I bring this up because I'm seeing you guys are going that exact same route that I'm heading, and I would rather you skip the headache I'm currently having.

It would be ideal if you gave this out of the box
A) Correlate downstream telemetry properly. If that would create a hard dependency on something that's undesirable then that's fair.
B) Specify message name or provide an adapter to allow devs to append the message type to the ServiceBusSender/Receiver/Complete dependencies.
C) Generate a possible telemetry item that says what queue received or sent a given message. "Queue.Send:Message Type" for example.

I implemented my message correlation using [NSB's tracing sample](https://docs.particular.net/samples/tracing/)
