### ISSUE TITLE
[QUERY]When using DI to create clients (via Microsoft.Extensions.Azure), should we try to use .NET's IHttpClientFactory for the underlying HttpClient?

### ISSUE THREAD

**Issue by mikequ-taggysoft** [Azure/azure-sdk-for-net#27188]
### Library name and version

Azure.Storage..., Azure.Messaging...

### Query/Question

The recommended pattern to obtain various kinds of Azure service clients (`QueueServiceClient`,  `EventHubProducerClient` etc) in modern .NET applications is to use DI registered via helper methods provided by `Microsoft.Extensions.Azure` such as:

```
services.AddAzureClients(builder =>
{
     builder.AddQueueServiceClient(uri)
          .WithCredential(...)
        //...other options
}             
```
Looking through the documentation, it seems the SDKs internally use shared singleton `HttpClient` instances, though they do expose the `Transport` property on client config options to pass in custom `HttpClient`.

Given the known drawbacks of regular singleton `HttpClient`, is it worth the effort of using .NET's `IHttpClientFactory` to create named `HttpClient` and pass them to `Transport` when configuring these SDKs via DI?

Or these SDKs have sufficient internal optimization on client management etc that in majority cases we probably don't need to bother?

**Comment by jsquire** [comment]
Hi @mikequ-taggysoft.  Thank you for your feedback.   There has been a lot of focus on ensuring that the `Azure.Core` pipeline works efficiently and performantly across a variety of scenarios.   Generally, we'd recommend registering the clients and allowing the clients to manage their `HttpClient` instances unless there is a scenario in your application that requires you to explicitly mange it.
