### ISSUE TITLE
"Deploy an SSH-enabled VM with a Template with .NET" gives 404 Error

### ISSUE THREAD

**Issue by simratsatia** [Azure/azure-sdk-for-net#27216]
Clicking on the provided 2 links in the page: [Deploy an SSH-enabled VM with a Template with .NET](https://azure.microsoft.com/resources/samples/resource-manager-dotnet-template-deployment/) and [Create and manage virtual machines](https://docs.microsoft.com/en-us/dotnet/azure/dotnet-sdk-azure-virtual-machine-samples) point to a page that doesn't exist.

![image](https://user-images.githubusercontent.com/28175383/155766757-62771580-b204-407a-aed9-ac7c9e2331fc.png)

![image](https://user-images.githubusercontent.com/28175383/155766484-ac515493-b32f-4bb8-9f4d-cdf7f782c279.png)

Please provide the correct links in the documentation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2b138b-2471-5e90-0a7d-07f8ba5e7ce3
* Version Independent ID: 695b4a2a-7975-075d-db2c-c16250098824
* Content: [Azure compute libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/virtualmachines?view=azure-dotnet)
* Content Source: [api/overview/azure/virtualmachines.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/virtualmachines.md)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@simratsatia  as we are in between the process of GA our new version of Azure .NET SDK, we'll update this whole page with new SDK code, for now you can refer to this https://github.com/Azure-Samples/azure-samples-net-management/tree/master/samples/compute/manage-virtual-machine to understand how to use our new version SDK to manage VMs on Azure
