### ISSUE TITLE
Azure Resource Manager Cosmos DB Readme issues

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#27210]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB#install-the-package):

![image](https://user-images.githubusercontent.com/65581162/155691340-abc0fca0-c564-4a0b-8ec3-858202d5d6c2.png)
Suggestion: 
Update package version to [1.0.0-beta.3](https://www.nuget.org/packages/Azure.ResourceManager.CosmosDB/1.0.0-beta.3)

2.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB#contributing):
![image](https://user-images.githubusercontent.com/65581162/155691621-0f847817-83d3-4d83-b92b-85f83ca4a4b1.png)

Suggestion: 

1. Add Link:  https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/CONTRIBUTING.md
2. Add Link: https://opensource.microsoft.com/codeofconduct/
3. Add Link: https://opensource.microsoft.com/codeofconduct/faq/

@scottaddie ,@AlexGhiondea,@kyle-patterson and @KrzysztofCwalina for notification.

**Comment by archerzz** [comment]
We've already update to `beta.3`. Fixing the links.
