### ISSUE TITLE
Claim values are truncated at first comma 

### ISSUE THREAD

**Issue by jasmcc** [Azure/azure-sdk-for-net#27225]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.SignalRService 1.6.0

### Describe the bug

It appears that claim values when populated into InvocationContext are incorrectly truncated if they contain a comma.  We noticed this looking at the name claim for a user; one had like so:
FirstName LastName (Company, Inc.)

What actually gets into the name claim is:
FirstName LastName (Company,

This appears to be because https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/src/TriggerBindings/Utils/SignalRTriggerUtils.cs line 39 is splitting on all commas, not just the first.

### Expected behavior

Claim values end up in InvocationContext without modification.

### Actual behavior

Claim values are truncated at the first embedded comma.

### Reproduction Steps

Pass a claim with a comma in the value.

### Environment

.NET Core 3.1
Visual Studio 2019

**Comment by SaurabhSharma-MSFT** [comment]
@jasmcc Thanks for sharing details.  We are looking into it and get back to you for any questions.

**Comment by chenkennt** [comment]
@Y-Sindo please take a look

**Comment by Y-Sindo** [comment]
Currently we use commas as a separator for different claims in the HTTP request header (see [serverless protocol](https://docs.microsoft.com/en-us/azure/azure-signalr/concept-upstream#request-header) for more details), which seems problematic. We plan to add a new HTTP header which contains the base64 encoded claims to solve the problem.  Before that fix is released, you could try to encode your claim values with base64 yourself as a mitigation.
