### ISSUE TITLE
[QUERY] Azure Table Storage: Use existing properties as PartitionKey and RowKey

### ISSUE THREAD

**Issue by mathiasi** [Azure/azure-sdk-for-net#27244]
### Library name and version

Azure.Data.Tables 12.4.0

### Query/Question

I have a model where existing fields already fits quite nicely for RowKey and PartitionKey but I don't know how to assign them and not have duplicate data. Consider this example:
```c-sharp
public class ClassA : ITableEntity
{
    // My existing fields
    public string Id { get; set; }
    public string Receiver { get; set; }
    public DateTimeOffset? Received { get; set; }

    // ITableEntity fields
    public string PartitionKey { get => Receiver; set => Receiver = value; }
    public string RowKey { get => Id; set => Id = value; }
    public DateTimeOffset? Timestamp { get => Received; set => Received = value; }
    public ETag ETag { get; set; }
}
```
This works but we get duplicate data as expected. Then I tried to add [IgnoreDataMember] to Id, Receiver and Received but then I cannot query using TableClient.QueryAsync(x => x.Id == "...").

Is there a way I can map the ITableEntity to my exisiting fields so I:
1. Avoid having duplicate data
2.  Can query using my exisiting fields

I'm using Azure.Data.Tables Version 12.4.0

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.200
 Commit:    4c30de7899

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.200\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.2.402 [C:\Program Files\dotnet\sdk]
  3.0.100 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @mathiasi 
You can rename fields for serialization using the `[DataMember(Name = "renamed_property")]` attribute, however I don't think this is helpful for your specific scenario. Since `PartitionKey` and `RowKey` are required properties, you can't avoid having them be part of the entity. Also, in order to query by a field name, it must be present in the service side column list of the entity. 

However, if you want to avoid sending the duplicate data to the client when querying, the `select` parameter can be used. See this example : https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md#query-entities-with-select

That would allow you to send only the query by PartitionKey and RowKey, but exlcude them from the result since your model uses the `Id` and `Receiver` values for them.

**Comment by mathiasi** [comment]
Thanks, I tried DataMember and you are completely right: it does solve my data duplication issue however I cannot query them. I don't mind having the properties on my object, it was more a matter of saving the data twice.
But I have made a custom implementation on top of this that handles it and it seems to work OK in my use-case, so I think we can close this issue :)
