### ISSUE TITLE
Examples.ListAsync yields JsonReaderException: JSON integer 9563023914 is too large or small for an Int32.

### ISSUE THREAD

**Issue by devwheel** [Azure/azure-sdk-for-net#27245]
` var ex2 = await client.Examples.ListAsync(appId, "0.1", 0, 1, false);`

Payload from fiddler:

[{"id":9563023914,"text":"did you like the movie jumanji","intentLabel":"Movie.GetSynopis","tokenizedText":["did","you","like","the","movie","jumanji"],"entityLabels":[{"entityName":"Movie Name","startTokenIndex":5,"endTokenIndex":5,"role":null,"roleId":null,"children":[]}],"intentPredictions":[{"name":"Movie.GetSynopis","score":0.89573246},{"name":"Help.GetAVHelp","score":0.020255238},{"name":"Movie.GetActors","score":0.015203057},{"name":"Weather.GetForecast","score":0.011653704},{"name":"Room.FindRoom","score":0.0072823907},{"name":"Stock.RequestQuote","score":0.0056160297},{"name":"Places.FindFood","score":0.0054717823},{"name":"Joke.TellJoke","score":0.00501483},{"name":"Time.GetTime","score":0.00401146},{"name":"Customer.FindCustomer","score":0.0025244155},{"name":"None","score":0.002017464}],"entityPredictions":[{"entityName":"Movie Name","startTokenIndex":5,"endTokenIndex":5,"phrase":"jumanji","entityType":1,"role":""}],"multiIntentPredictions":null}]

**Comment by jsquire** [comment]
Hi @devwheel.  Thank you for reaching out and we regret that you're experiencing difficulties.   Unfortunately, I'm not able to infer from context how to best refer you for assistance.   Would you be so kind as to let us know which SDK package you're using and help us understand more about the scenario that you're discussing?
