### ISSUE TITLE
Cannot Add Immutability Policy With Active Directory

### ISSUE THREAD

**Issue by JsAndDotNet** [Azure/azure-sdk-for-net#27243]
### Library name and version

Azure.Storage.Blobs version 12.10.0

### Describe the bug

When I run code using a SAS token, I am able to upload a blob to storage with an Immutability Policy.

However, when I try to run the same code, but using Azure Active Directory (AAD), the following is noted:
1. OK - I CAN upload a document WITHOUT an Immutability Policy (so AAD must be working?)
2. ERROR - I CANNOT upload a document WITH an Immutability Policy

Code for Repro and error in following sections.

I am logged into Visual Studio 2022 Community Edition (17.1.0) as myself and using Tools > Options > Azure Service Authentication have logged in.

In the the Azure Portal, Access Control (IAM), I have the following roles - excessive, as I've been trying to get this to work.
- Owner
- Resource Policy Contributor
- Storage Blob Data Contributor
- Storage Queue Data Contributor

### Expected behavior

Expect to be able to upload using AAD with Immutability Policy

### Actual behavior

ERROR WHEN TRYING TO UPLOAD USING AAD WITH IMMUTABILITY POLICY:

> This request is not authorized to perform this operation using this permission.
> RequestId:...
> Time:2022-02-28T09:29:46.6433702Z
> Status: 403 (This request is not authorized to perform this operation using this permission.)
> ErrorCode: AuthorizationPermissionMismatch
> 
> Content:
> <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
> RequestId:634e7b9c-601e-0051-0c85-2c0056000000
> Time:2022-02-28T09:29:46.6433702Z</Message></Error>
> 
> Headers:
> Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
> x-ms-request-id: 634e7b9c-601e-0051-0c85-2c0056000000
> x-ms-client-request-id: e5fbc21b-c0c1-4293-867b-0c0191651ce3
> x-ms-version: 2020-10-02
> x-ms-error-code: AuthorizationPermissionMismatch
> Date: Mon, 28 Feb 2022 09:29:46 GMT
> Content-Length: 279
> Content-Type: application/xml
> '

### Reproduction Steps

```
        public async Task UploadFileAsync(string fileAsEncryptedString, string fileName, DateTime expiryDate)
        {
            try
            {
                string accountName = "<mystorageaccount>";
                string containerName = "<mycontainer>";

                // WORKING SAS TOKEN WAY
                //BlobServiceClient blobServiceClient = new BlobServiceClient($"BlobEndpoint=https://{accountName}.blob.core.windows.net/;QueueEndpoint=https://{accountName}.queue.core.windows.net/;FileEndpoint=https://{accountName}.file.core.windows.net/;TableEndpoint=https://{accountName}.table.core.windows.net/;SharedAccessSignature=sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2029-02-28T16:59:50Z&st=2022-02-28T08:59:50Z&spr=https&sig=REMOVED");
                //BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);

                // FAILING AAD WAY
                Uri accountUri = new Uri($"https://{accountName}.blob.core.windows.net/");
                BlobServiceClient blobServiceClient = new BlobServiceClient(accountUri, new DefaultAzureCredential());
                BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);


                // Create the container if it does not exist - this is just here to ensure connection works
                await containerClient.CreateIfNotExistsAsync();

                // Not optimal, just like this so can inspect content.
                var bytes = Encoding.UTF8.GetBytes(fileAsEncryptedString);
                BinaryData binaryData = new BinaryData(bytes);

                BlobClient blobClient = containerClient.GetBlobClient(fileName);
                BlobUploadOptions options1 = new BlobUploadOptions();
                options1.ImmutabilityPolicy = new BlobImmutabilityPolicy();
                options1.ImmutabilityPolicy.ExpiresOn = DateTime.Now.AddSeconds(60); // expiryDate
                options1.ImmutabilityPolicy.PolicyMode = BlobImmutabilityPolicyMode.Unlocked;
                //await blobClient.UploadAsync(binaryData);
                await blobClient.UploadAsync(binaryData, options1);

                binaryData = null;

            }
            catch (RequestFailedException e)
            {
                Console.WriteLine(e.Message);
                Console.ReadLine();
                throw;
            }
        }
```

### Environment

Visual Studio 2022 Community Edition (17.1.0)
Dotnet SDK Version: 6.0.200

**Comment by SaurabhSharma-MSFT** [comment]
@JsAndDotNet I am able to reproduce this issue and getting the same error as yours while uploading blob with an immutable policy. 
![image](https://user-images.githubusercontent.com/38112130/156089584-04c65d35-2d17-491a-8c0b-0ee02ad6200d.png)
I am redirecting this to services team to look into.

Thanks
Saurabh

**Comment by seanmcc-msft** [comment]
@JsAndDotNet, Immutable Storage With Version must be enabled on the parent container in order to set an Immutability Policy on a Blob.  You can see an example of how to enabled this feature on a container in our unit tests - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/tests/ImmutableStorageWithVersioningTests.cs
