### ISSUE TITLE
[FEATURE REQ] OpenTelemetry exporter is not reporting the Application Version

### ISSUE THREAD

**Issue by baseballbrad3** [Azure/azure-sdk-for-net#27269]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.3

### Describe the bug

The OpenTelemetry property [`service.version`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#service) is not being displayed as "[Application Version](https://docs.microsoft.com/en-us/azure/azure-monitor/app/data-model-context#application-version)" (nor by a custom `service.version` property) in Application Insights while other OpenTelemetry exporters (Console and Jaeger, for example) do report `service.version`.

### Expected behavior

Application Insights should report the `service.version` property as "Application Version" (or as a custom property).

### Actual behavior

"Application Version" is always `<empty>` in the transaction search filter and "Application Version" doesn't show up when looking at a request's details.

### Reproduction Steps

Configure a .NET web application with OpenTelemetry (we're using version `1.1.0`). When setting up the `ResourceBuilder`, ensure that `AddService` is called with a `serviceVersion`.

```csharp
serviceCollection.AddOpenTelemetryTracing(builder =>
{
    builder.SetResourceBuilder(
        ResourceBuilder
            .CreateDefault()
            .AddService("application name here", serviceVersion: "1.2.3.4")
    );
}
```

Also ensure that `OpenTelemetry.Instrumentation.AspNetCore` is configured to capture traces for web requests.

Issue a web request to the application and find it in Application Insights. The "Application Version" property is always `<empty>` in the transaction search filter and "Application Version" doesn't show up when looking at a request's details.

### Environment

The project using the library is a .NET 6 project.

```
❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    02d5242ed7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19041
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.102\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec
```

**Comment by SaurabhSharma-MSFT** [comment]
@baseballbrad3 I am redirecting this to services team to investigate and provide a fix as required.

**Comment by TimothyMothra** [comment]
This is on our backlog. Need to discuss with all languages.
