### ISSUE TITLE
[FEATURE REQ]RESILIENCY: GA Support ESTS-R in Azure.Identity SDK

### ISSUE THREAD

**Issue by tommymarkmamake** [Azure/azure-sdk-for-net#27281]
### Library name

Azure.Identity SDK

### Please describe the feature.

Library or service name.
What library or service is this request related to? [e.g. Azure.Storage.Blobs]

Azure.Identity SDK

Is your feature request related to a problem? Please describe.
What feature would you like to get added? What problem is it solving?

Our 1st party app Dev is blocked for using Azure. Identity SDK to adopt ESTS-R, due to the lack of autodetect region in GA. partner could not use the global environment variable due to many reasons, so they would still need this API for GA.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
The region selection feature is only currently available to 1st party applications so we currently have no plans to add this to the upcoming Azure.Identity GA.

**Comment by scottaddie** [comment]
At this time, there are no plans to GA this support in the library. Doing so would introduce additional public API surface that doesn't apply to 3rd parties. It's the team's goal to optimize the developer experience for 3rd parties.

Our internal guidance for 1st parties has been published to [this page](https://review.docs.microsoft.com/identity/microsoft-identity-platform/msal-net-regional-adoption?branch=main#providing-a-region-with-azureidentity). Two different approaches are outlined there. One involves setting an environment variable. The other approach involves creating a custom token credential type. 1st parties should be able to use one of these two approaches.
