### ISSUE TITLE
[BUG]  Azure Monitor Query Visualization not working

### ISSUE THREAD

**Issue by seijimorimoto** [Azure/azure-sdk-for-net#27286]
### Library name and version

Azure.Monitor.Query 1.1.0

### Describe the bug

I'm running locally an Azure Function App that uses the Azure.Monitor.Query package for querying logs. One of the queries the App executes has a `render timechart with (ymax = 2500)` statement at the end, because I want the output of that query to be visualized as a chart. From looking at the [Query API](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/monitor/query?view=azure-dotnet), I figured I had to pass a `LogsQueryOptions` object with the `IncludeVisualization` property set to true when adding the query to the batch query. However, even after doing this, I can't get a proper output image.

### Expected behavior

When running the query directly through Azure Portal via the browser, this is the resulting chart.

![image](https://user-images.githubusercontent.com/7454295/156272107-c57f59d6-250a-4534-afad-8a91d003b8ca.png)

### Actual behavior

When calling the HTTP endpoint of the Function App via the browser, the browser renders the resulting image as the following (clearly not the expected chart).

![image](https://user-images.githubusercontent.com/7454295/156272362-9e76d576-f1c1-44db-a010-58c67934013d.png)

### Reproduction Steps

1. Create an Azure Function App project in Visual Studio. Here is a [guide](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio) for doing that.
2. Install the Azure Monitor Query client library for .NET.

`dotnet add package Azure.Monitor.Query`

3. Copy this function into your main class. This is a simplified version of my code. I have verified that this version produces the same results as the one in my project.

```csharp
[FunctionName("ExecuteQuery")]
public async Task<IActionResult> ExecuteQuery(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = null)] HttpRequest request,
    ILogger logger)
{
    logger.LogInformation("HTTP request received for '{0}' API", request.Path);

    string workspaceId = "<your_workspace_id>";
    string query = "<your_query>";

    var startDate = new DateTimeOffset(2021, 11, 29, 0, 0, 0, TimeSpan.Zero);
    var endDate = new DateTimeOffset(2021, 12, 05, 0, 0, 0, TimeSpan.Zero);
    var timeRange = new QueryTimeRange(startDate, endDate);

    var client = new LogsQueryClient(new InteractiveBrowserCredential());
    var batch = new LogsBatchQuery();
    var queryOptions = new LogsQueryOptions
    {
        IncludeVisualization = true
    };

    var queryId = batch.AddWorkspaceQuery(workspaceId, query, timeRange, queryOptions);

    Response<LogsBatchQueryResultCollection> response = await client.QueryBatchAsync(batch);
    LogsBatchQueryResult result = response.Value.GetResult(queryId);

    BinaryData binaryData = result.GetVisualization();
    byte[] imageBytes = binaryData.ToArray();

    // Also tried writing to a file and then exploring that file on my PC. When trying to open the file on my default image viewer app, it says that the file format is not supported.
    // string filePath = Path.Combine(Directory.GetCurrentDirectory(), "latencyGet.jpeg");
    // File.WriteAllBytes(filePath, imageBytes);
    
    return new FileContentResult(imageBytes, "image/jpeg");
}
```

4. Run your Function App locally and trigger the above function by going to [http://localhost:7071/api/ExecuteQuery](http://localhost:7071/api/ExecuteQuery) in your browser.

**Comment by SaurabhSharma-MSFT** [comment]
@seijimorimoto I am able to reproduce this issue and redirecting this to services team to look into.
![image](https://user-images.githubusercontent.com/38112130/156670316-e685e218-8fcf-49af-a0b0-8340c2f78888.png)

Thanks
Saurabh

**Comment by seijimorimoto** [comment]
Thank you @SaurabhSharma-MSFT, hopefully this issue can be fixed soon

**Comment by seijimorimoto** [comment]
@scottaddie, per the updated README sections, it seems that the `GetVisualization()` method of the `LogsQueryResult` class returns a JSON containing the structure of the visualization and not the actual image. What is the recommended way of creating a an image from these data? Is there a library for doing this?
