### ISSUE TITLE
[FEATURE REQ] Writable Model class properties, or move Model classes into a new package

### ISSUE THREAD

**Issue by franklixuefei** [Azure/azure-sdk-for-net#27298]
### Library name

Azure.ResourceManager

### Please describe the feature.

We are currently implementing a new resource provider for Azure, and were looking into existing ARM model classes for constructing our response models. However, for some model classes, like `ErrorDetail`, their properties are marked as `{get;}`, without the `{set;}`, and the constructors that could take parameters are maked as `internal`. We would like to see that at some point, these model classes could be published as a separate nuget package so we could leverage it easily.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hi @franklixuefei, mainly 2 reason:
- the model is only used to retrieve data from service side
- this is a collection, then you can just add an element to the collection instead of assign a new collection

And your ask is great, so we will provide some factory helper later which can support initial these kind of models.

**Comment by dgcaron** [comment]
I am struggling with a similar question. I am trying to write a unit test and need to instantiate a SubscriptionData instance. but there is no way of doing this currently.  Any advice other than wrapping the implementation into your own classes?

**Comment by sdib** [comment]
same here for ArmApplicationData

**Comment by jokarl** [comment]
Same here, it is very difficult to properly test anything as I can't inherit and property is `get` only. Many classes are not inheritable either, and provide no constructors.

**Comment by ArthurMa1978** [comment]
The modelfactory feature has been enabled for the latest Azure.ResourceManager lib.
