### ISSUE TITLE
[QUERY] Maintenance deadline for this library

### ISSUE THREAD

**Issue by hqibec** [Azure/azure-sdk-for-net#27296]
### Library name and version

Microsoft.Azure.ServiceBus 5.2.0

### Query/Question

The NuGet package `Microsoft.Azure.ServiceBus` was deprecated and needs to be migrated to `Azure.Messaging.ServiceBus`.

I've looked at the relevant documents, for `Microsoft.Azure.ServiceBus`
(1) what is the planned last maintenance deadline?
(2) will there be ongoing maintenance for security issues?

Thank you!

From the [NuGet page ](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus)

> While this package will continue to receive critical bug fixes, we strongly encourage upgrading for new development. Please see the migration guide for more details.

From the [migration guide ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md#migration-benefits)

> While we believe that there is significant benefit to adopting the new Service Bus library Azure.Messaging.ServiceBus, it is important to be aware that the previous two versions WindowsAzure.ServiceBus and Microsoft.Azure.ServiceBus have not been officially deprecated. They will continue to be supported with security and bug fixes as well as receiving some minor refinements. However, in the near future they will not be under active development and new features are unlikely to be added to them.

**Comment by EldertGrootenboer** [comment]
@hqibec We don't have a maintenance deadline yet, however we do suggest moving to the new SDK as soon as possible. As it mentions, because this is a deprecated package, we only provide critical security and maintenance fixes. All the new features will be implemented on the latest SDK. Once we have an official deadline, this will be published ahead of time in the regular communication channels.

**Comment by hqibec** [comment]
> @hqibec We don't have a maintenance deadline yet, however we do suggest moving to the new SDK as soon as possible. As it mentions, because this is a deprecated package, we only provide critical security and maintenance fixes. All the new features will be implemented on the latest SDK. Once we have an official deadline, this will be published ahead of time in the regular communication channels.

@EldertGrootenboer, Thank you!
 
Best wishes to the team
