### ISSUE TITLE
How do I manage Cloud Services with the new REST client / AutoRest SDK?

### ISSUE THREAD

**Issue by Jehoel** [Azure/azure-sdk-for-net#2729]
The `AutoRest` branch in this repo no-longer includes the `ServiceManagement` client and types, only the `ResourceManagement` REST client, while it still exists in the `master` branch.

I appreciate that Cloud Services (`HostedServices`) are almost-deprecated and only accessible through the older ServiceManagement API, but there doesn't seem to be any maintained client for that API - NuGet has `Microsoft.WindowsAzure.Management.Compute` - which is based on the old `Microsoft.WindowsAzure.*` code instead of the newer `Microsoft.Azure.*` code.

I see the Azure PowerShell module still references the older `Microsoft.WindowsAzure.Management.Compute` assembly for its tasks - what will the PowerShell module - and my own projects - use to manage Cloud Services if they want to use the latest SDKs?

**Comment by hovsepm** [comment]
@Jehoel Azure PowerShell has 2 modules as well. RDFE aka ServiceManagement cmdlets and ARM aka ResourceManagement cmdlets. You can browse them here - https://github.com/Azure/azure-powershell/tree/dev/src

**Comment by hovsepm** [comment]
@Jehoel your usage depends on your scenarios, but we strongly suggest considering ARM (which is ResourceManager and has [verb]-*AzureRM*[cmdlet] syntax in Powershell) and AutoRest generated SDKs

**Comment by Jehoel** [comment]
But how do I use the AutoRest-generated clients to manipulate Cloud Services then? There's no `HostedServicesOperations` type available in that library.
