### ISSUE TITLE
With Azure Monitor Query, how do we query classic Resource Mode AppInsights?

### ISSUE THREAD

**Issue by stowen-msft** [Azure/azure-sdk-for-net#27290]
hi!

I want to integrate querying my app's AppInsight's directly into a monitoring service that watches my app.  I saw the code samples for how to query using the LogsQueryClient exposed in Azure.Monitor.Query and was able to setup a credential and get that working.

However our org hasn't migrated to the newer Resource Model, and still see this in our Application Insight's Properties tab.

![image](https://user-images.githubusercontent.com/69686895/156284131-8a9a9e9b-fbf6-49dd-9220-17347f205b7b.png)

I poked around in the surface area of the AzureMonitorQuery nuget package but couldn't figure it out.  Is it possible?

We could just query the Rest API but so far have been successful integrating using the SDKs for Azure Resource Manager, etc.

**Comment by SatishBoddu-MSFT** [comment]
Hello @stowen-msft thanks for the feedback! wanted to understand the actual issue over here...

Are you trying to migrate and not able to use REST API?
![image](https://user-images.githubusercontent.com/62923178/156453229-9bf191f2-fdcf-408e-b931-2e78f392a94e.png)

Are you trying to use the REST API before migration and trying to do a log search?

Please add more details to the issue, such as any error logs or screenshots/

**Comment by SatishBoddu-MSFT** [comment]
Hello @stowen-msft ,
Thanks for the response!
Please have a look at the below code snippet, might be helpful with your initial query!
using Microsoft.Azure.ApplicationInsights.Query;

```
public async Task<string> GetRecordCount(string OrderID, string environment, string keyVaultName)
        {

            string applicationId = KeyVaultService.GetKeyFromKeyVault(keyVaultName, "AIAppId-" + environment);
            string key = KeyVaultService.GetKeyFromKeyVault(keyVaultName, "AIAppSecretKey-" + environment);
           
            var credentials = new ApiKeyClientCredentials(key);
            var applicationInsightsClient = new ApplicationInsightsDataClient(credentials);
            var query = $"traces" +
                        $"| where customDimensions.prop__OrderID has " + "\"" + OrderID + "\"" +
                        $"| project " +
                        $"OrderID = tostring(customDimensions.prop__OrderID)" +
                        $"| summarize ['Count']= dcount(OrderID)";
            var response = await applicationInsightsClient.Query.ExecuteWithHttpMessagesAsync(applicationId, query);
            string count = "";
            // Parse result 
            if (response.Response.IsSuccessStatusCode)
            {
                var result = await response.Response.Content.ReadAsStringAsync();
                var data = JsonConvert.DeserializeObject<Rootobject>(result);
                count = data.Tables[0].Rows[0][0].ToString();
            }
            return count;
        }
```
 
You need not make any changes to your application . Sending your Application Insights telemetry to a common Log Analytics workspace brings full access to all the features of Log Analytics while keeping application, infrastructure, and platform logs in a single consolidated location. [Referece](https://github.com/MicrosoftDocs/azure-docs/issues/82105#issuecomment-946658583)

Few related documents which I can suggest for the Workspace-based Application Insights resources!
[Migrate to workspace-based Application Insights resources](https://docs.microsoft.com/en-us/azure/azure-monitor/app/convert-classic-resource#new-capabilities)

[Troubleshooting](https://docs.microsoft.com/en-us/azure/azure-monitor/app/convert-classic-resource#troubleshooting)

[Code-based application monitoring](https://docs.microsoft.com/en-us/azure/azure-monitor/app/create-workspace-resource#code-based-application-monitoring) might give some help on the code examples.

**Comment by SatishBoddu-MSFT** [comment]
As per our offline conversation with @stowen-msft , below is the summary.

> We could migrate easily, There was no work needed to make our servers keep sending the data. Can easily query.

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.

**Comment by stowen-msft** [comment]
We migrated and that was completely painless!
