### ISSUE TITLE
[QUERY] How to get the TraceRecords from a query to ApiManagementGatewayLogs

### ISSUE THREAD

**Issue by tracker1** [Azure/azure-sdk-for-net#27309]
### Library name and version

Azure.Monitor.Query 1.1.0

### Query/Question

I'm using `LogsQueryClient` to query `ApiManagementGatewayLogs`, I am seeing most row data without issue... however I'm unable to figure out how to get data out of the `TraceRecords` column in the rows... when serializing to JSON output for viewing in logs, it prints `{}` for the TraceRecords field.

Can someone provide an example of how to read this data out?

### Environment

I'm using VS Code, with `dotnet run` in the terminal window.

OS: Windows 10 21H2

❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by tracker1** [comment]
Apparently `row["TraceRecords"].ToString()` will give me the `TraceRecords` as a string containing a JSON array of entries.  Was able to get/parse the message data from there... still, feels like a really sloppy interface.

Should probably provide an example in both the API documentation as well as the library documentation.

Not sure if other BinaryData perform the same, or if there are issues with this path.

**Comment by PramodValavala-MSFT** [comment]
@tracker1 I can confirm that values that have varied structure based on the query, `BinaryData` is returned which is just serialized JSON data. Parsing this string is the expected way to consume this data.

I will work with the concerning team to add this to [the packages' README](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.Query#readme).

**Comment by tracker1** [comment]
@PramodValavala-MSFT thank you for confirming this... it was just kind of difficult to determine for me, since looking at the inspector in VS didn't reveal anything, and it just wasn't clear from the docs.

Glad it's getting documented.
