### ISSUE TITLE
Any breaking dependencies when upgrading from v1.0.0 to latest 3.0.5 via nuget in VS2017?

### ISSUE THREAD

**Issue by mushu999** [Azure/azure-sdk-for-net#27305]
### Library name and version

Microsoft Azure Key Vault Core Class Library

### Query/Question

There are vulnerabilities in the version 1.0.0 of Microsoft Azure Key Vault Core Class Library so want to upgrade my project. Need to know if there are any code changes needed if I just use nuget to update to v3.0.5 or not?

### Environment

Visual Studio 2017, Windows 10 Pro, large C# MVC web project.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Very likely, but Microsoft.Azure.KeyVault is deprecated in favor of:

* Azure.Security.KeyVault.Secrets
* Azure.Security.KeyVault.Keys
* Azure.Security.KeyVault.Certificates

One goal with these new packages - all our Azure.* packages - is no breaking changes. So not only is development, bug fixes, etc., active on those packages, but if you make the move now (see our migration guides e.g., https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/MigrationGuide.md), you shouldn't have to worry about subsequent breaking changes.
