### ISSUE TITLE
[BUG] Communication Network Traversal: Example references unsupported version

### ISSUE THREAD

**Issue by Dale-Burmeister** [Azure/azure-sdk-for-net#27302]
### Library name and version

Azure.Communication.NetworkTraversal -Version 1.0.0

### Describe the bug

in the example here https://www.nuget.org/packages/Azure.Communication.NetworkTraversal/
They are calling Response<CommunicationRelayConfiguration> turnTokenResponse = await relayClient.GetRelayConfigurationAsync(identity);
that is throwing this error
+		$exception	{"The HTTP resource that matches the request URI 'https://global.auth.prod.communication.microsoft.com/networkTraversal/:issueRelayConfiguration' does not support the API version '2022-02-01'.\r\nStatus: 400 (Bad Request)\r\nErrorCode: UnsupportedApiVersion\r\n\r\nContent:\r\n{\"error\":{\"code\":\"UnsupportedApiVersion\",\"message\":\"The HTTP resource that matches the request URI 'https://global.auth.prod.communication.microsoft.com/networkTraversal/:issueRelayConfiguration' does not support the API version '2022-02-01'.\"}}\r\n\r\nHeaders:\r\nRequest-Context: REDACTED\r\nMS-CV: t9I1vgbCAkaB5b2zukySJg.0\r\nStrict-Transport-Security: REDACTED\r\nx-ms-client-request-id: 3bae34a4-5785-490e-8bd1-e7bebae75566\r\napi-supported-versions: REDACTED\r\nX-Processing-Time: REDACTED\r\nX-Cache: REDACTED\r\nX-Azure-Ref: REDACTED\r\nDate: Wed, 02 Mar 2022 14:03:13 GMT\r\nContent-Length: 245\r\nContent-Type: application/json; charset=utf-8\r\n"}	Azure.RequestFailedException

### Expected behavior

to return json data that can this code and view and not error out.

DateTimeOffset turnTokenExpiresOn = relayConfiguration.Value.ExpiresOn;
IReadOnlyList<CommunicationIceServer> iceServers = relayConfiguration.Value.IceServers;
Console.WriteLine($"Expires On: {turnTokenExpiresOn}");
foreach (CommunicationIceServer iceServer in iceServers)
{
    foreach (string url in iceServer.Urls)
    {
        Console.WriteLine($"ICE Server Url: {url}");
    }
    Console.WriteLine($"ICE Server Username: {iceServer.Username}");
    Console.WriteLine($"ICE Server Credential: {iceServer.Credential}");
    Console.WriteLine($"ICE Server RouteType: {iceServer.RouteType}");
}

### Actual behavior

throwing this error
+		$exception	{"The HTTP resource that matches the request URI 'https://global.auth.prod.communication.microsoft.com/networkTraversal/:issueRelayConfiguration' does not support the API version '2022-02-01'.\r\nStatus: 400 (Bad Request)\r\nErrorCode: UnsupportedApiVersion\r\n\r\nContent:\r\n{\"error\":{\"code\":\"UnsupportedApiVersion\",\"message\":\"The HTTP resource that matches the request URI 'https://global.auth.prod.communication.microsoft.com/networkTraversal/:issueRelayConfiguration' does not support the API version '2022-02-01'.\"}}\r\n\r\nHeaders:\r\nRequest-Context: REDACTED\r\nMS-CV: t9I1vgbCAkaB5b2zukySJg.0\r\nStrict-Transport-Security: REDACTED\r\nx-ms-client-request-id: 3bae34a4-5785-490e-8bd1-e7bebae75566\r\napi-supported-versions: REDACTED\r\nX-Processing-Time: REDACTED\r\nX-Cache: REDACTED\r\nX-Azure-Ref: REDACTED\r\nDate: Wed, 02 Mar 2022 14:03:13 GMT\r\nContent-Length: 245\r\nContent-Type: application/json; charset=utf-8\r\n"}	Azure.RequestFailedException

### Reproduction Steps

run the example here https://www.nuget.org/packages/Azure.Communication.NetworkTraversal/

### Environment

C:\Windows\System32>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  5.0.200 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by Dale-Burmeister** [comment]
This looks verify similar https://github.com/Azure/azure-sdk-for-js/issues/20542

**Comment by SatishBoddu-MSFT** [comment]
Hello @Dale-Burmeister thanks for the feedback!
Routing this to the service team's attention!

**Comment by AriZavala2** [comment]
Hello, 
I clicked the provided link(https://www.nuget.org/packages/Azure.Communication.NetworkTraversal/) to Nuget and it is correctly pointing to the last version. 

I'll close this issue. 

Thanks!
![image](https://user-images.githubusercontent.com/77034370/157559046-6be65502-44c4-4ce7-98e4-3b4f3baa7519.png)
