### ISSUE TITLE
[QUERY] [AzureResourceManager] [ARM-Template] [Az.Resources] SDK function for ARM template deployments 

### ISSUE THREAD

**Issue by hiaga** [Azure/azure-sdk-for-net#27300]
### Library name and version

Azure Resource Manager (need help here)

### Query/Question

We have a requirement to create Arm Template Deployments using .Net SDK. I need help on which .Net SDK and version to use for this. Please Help !

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
@hiaga Thank you for reaching us.
For your request of creating a ARM Deployment Template, you could use our newly released sdk : [Azure.ResourceManager.Resources](https://www.nuget.org/packages/Azure.ResourceManager.Resources/).
For the detailed steps, you could refer to this [test sample](https://github.com/Azure/azure-sdk-for-net/blob/8b9ea1ab81b6a12cbf6a73f3bac7441675b430ba/sdk/resources/Azure.ResourceManager.Resources/tests/Scenario/DeploymentCollectionTests.cs#L52).
