### ISSUE TITLE
[FEATURE REQ] bicep files as an alternative to ARM templates

### ISSUE THREAD

**Issue by ranul-pallemulle** [Azure/azure-sdk-for-net#27306]
### Library name

Azure.ResourceManager.Resources

### Please describe the feature.

At the moment it seems I have the option to create a deployment by specifying a JSON template like this:
`
new DeploymentProperties(DeploymentMode.Incremental)
{
    Template = "{}" // well-formatted JSON here
}
`

Would it be possible to add bicep support? I know it's possible to convert from bicep to ARM but I would rather just keep the bicep file and not also its corresponding ARM template in source control.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by shanonbearyglobal** [comment]
When will this be looked at? Or if possible at all?

Will be a great feature to have and support bicep across the board.

**Comment by ArcturusZhang** [comment]
Hi @ranul-pallemulle thanks for this request, but I do not think the SDK is going to support this at least recently.
The SDK is generated from the swagger and the swagger only accepts arm template in JSON.

As a workaround, you could always use external tools like [this](https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-cli#decompile) to decompile bicep into JSON arm template and then pass the json into the SDK.
