### ISSUE TITLE
[FEATURE REQ] ClientCertificateCredential should support certificate store

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#27315]
### Library name

Azure.Identity

### Please describe the feature.

This is a feature request on behalf of @abatishchev.

In track 1 the AppAuthentication library supported loading authentication certificates from the certificate store directly by specifying either the thumbprint or subject name and issuer via its connection string. It also supported refreshing the certificate from the store in the SNI case to enable seamless certificate rolling.

In track 2 we have the `ClientCertificateCredential` which only supports a pre-loaded certificate, or loading a certificate from disk, and doesn't support rolling the certificate. While we have some track 2 [samples](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientCertificateCredentialSamples.md#loading-certificates-from-an-x509store) which demonstrate how an application might achieve this behavior, there are no built-in credential types which users can use out of the box.

Given that using of the certificate store, and automatic rolling of certificates are security best practices, it would be good to enable these behaviors directly in Azure.Identity, or possibly a plugin library, so that users aren't left to implementing them in their applications.

**Comment by abatishchev** [comment]
Thanks, @schaabs ! I couldn't phase it better.

Just for the reference, here's another feature request, for support of connection string exactly: #17652. I think it'd be better to implement this feature though.

**Comment by JaredShaver** [comment]
How would clients specify the certificate?  Would it be possible to have EnvironmentCredential check for a thumbprint or certificate name environment variable?

**Comment by abatishchev** [comment]
In my mind that should be a set of a environment variables, like what `EnvironmentCredential` currently does but with the support for Subject Name and Issuer and other modern, secure practices.
Or a subset of an Auth Connecting String, a subset only to support the most modern and secure options.

**Comment by JaredShaver** [comment]
This request has been opened several times in multiple repositories so I don't remember who suggested it, but an idea presented by another user was to use the PowerShell CertificateProvider syntax for the certificate path (ex. set AZURE_CLIENT_CERTIFICATE_STORE \LocalMachine\My\52A149D0393CE8A8D4AF0B172ED667A9E3A1F44E ).
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/about/about_certificate_provider?view=powershell-7.2
https://github.com/PowerShell/PowerShell/blob/b46ac16e09dce433dbc1ecb19ab949754eef4978/src/Microsoft.PowerShell.Security/security/CertificateProvider.cs#L1223

**Comment by iinuwa** [comment]
+1 for using the `Cert:\` syntax for specifying certificates in the store. That could specified as an environment variable pretty easily.

**Comment by wg-davegriffiths** [comment]
Yes, that cert:\ suggestion was by me.     https://github.com/Azure/azure-sdk-for-net/issues/25360#issuecomment-1024276460 
A few related issues have suggested the reason for holdup of implementing this is cross-platform reasons, but appears there is already some cross-platform support for mapping cert store locations to file paths in linux too: https://github.com/dotnet/runtime/issues/27658

**Comment by pallavit** [comment]
@christothes is this still valid?

**Comment by abatishchev** [comment]
Yes, it is. Doesn't seem anything has changed since it was filed 1.5 years ago.
