### ISSUE TITLE
[BUG] New .NET test framework does not run tests in Record or Playback mode with Fiddler running.

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#27316]
### Library name and version

Azure.Core.TestFramework

### Describe the bug

New .NET test framework does run tests in Record or Playback mode with Fiddler running.

Work around:

https://github.com/Azure/azure-sdk-for-net/blob/edee9bbff84e4cf09091e3e0537d72b10e2bee88/sdk/core/Azure.Core.TestFramework/src/ProxyTransport.cs#L163
Updated to `request.Uri.Host = "localhost.fiddler"; `
https://github.com/Azure/azure-sdk-for-net/blob/edee9bbff84e4cf09091e3e0537d72b10e2bee88/sdk/core/Azure.Core.TestFramework/src/TestProxy.cs#L27
Update to `public const string DevCertIssuer =  "CN=DO_NOT_TRUST_FiddlerRoot, O=DO_NOT_TRUST, OU=Created by http://www.fiddler2.com/";` 

### Expected behavior

I expect to be able to run tests and Fiddler at the same time.

### Actual behavior

I am not able to run tests in Playback or Record mode with Fiddler running.

### Reproduction Steps

Run tests in Playback or Record mode with Fiddler enabled.

### Environment

Windows 10.

**Comment by kurtzeborn** [comment]
Possibly related to: https://github.com/Azure/azure-sdk-for-net/issues/27307
