### ISSUE TITLE
[FormRecognizer] Remove DocumentTableCell private properties workaround when `x-ms-client-default` is supported

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#27319]
We added a workaround in code in order to set default values for three properties in `DocumentTableCell` (PR: https://github.com/Azure/azure-sdk-for-net/pull/27317). These default values should actually be defined in the swagger by the `x-ms-client-default` properties, but they seem to make generated code that fails when building.

This possible bug was reported in https://github.com/Azure/autorest.csharp/issues/2015. When this autorest issue has been fixed, we should:
- Remove the workaround introduced in the aforementioned PR by removing the helper properties: `RowSpanPrivate`, `ColumnSpanPrivate`, and `KindPrivate`.
- Regenerate code.
- If [#27318](https://github.com/Azure/azure-sdk-for-net/issues/27318) has been fixed, we don't need to do anything else.
  - Otherwise, we need to add a transform that adds `rowSpan`, `columnSpan`, and `kind` to the required properties and set their `x-ms-client-default` values until the service team updates the swagger.

**Comment by pallavit** [comment]
@kinelski can this be closed?
