### ISSUE TITLE
Can't add various Microsoft.Azure nuget packages in VS2017RC

### ISSUE THREAD

**Issue by schnitty** [Azure/azure-sdk-for-net#2732]
Visual Studio Version: version: VisualStudio/public.d15rel/15.0.26020.0
When I try to add the nuget package to an empty .NET Core Console application I get the following error:

```
PM> Install-Package Microsoft.Azure.Search
  GET https://api.nuget.org/v3/registration1-gz/microsoft.azure.search/index.json
  OK https://api.nuget.org/v3/registration1-gz/microsoft.azure.search/index.json 290ms
Restoring packages for C:\Development\Sandbox\vs2017search\vs2017search\vs2017search.csproj...
Install-Package : Package Microsoft.Spatial 6.15.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Spatial 6.15.0 supports:
  - dnx451 (DNX,Version=v4.5.1)
  - dnxcore50 (DNXCore,Version=v5.0)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
At line:1 char:1
+ Install-Package Microsoft.Azure.Search
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.1.
At line:1 char:1
+ Install-Package Microsoft.Azure.Search
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'vs2017search'.
At line:1 char:1
+ Install-Package Microsoft.Azure.Search
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
```
 
If I do this from VS2015 with .NET Core Console app with .NET Core 1.1 it works ok.

**Comment by brjohnstmsft** [comment]
To clarify, the issue appears to affect Microsoft.Spatial when imported in isolation. Microsoft.Spatial is a dependency of Microsoft.Azure.Search.

**Comment by brjohnstmsft** [comment]
@schnitty I'm borrowing your notes from StackOverflow that characterize the scope of the issue; Hope you don't mind.

> I get the same or similar error when I add the following:
> - Microsoft.Azure.NotificationHubs 1.0.7
> - Microsoft.Azure.Management.Resources v2.20.1-preview
> - Microsoft.Spatial v7.0.0
> - Microsoft.Azure.Management.Storage.Fluent v1.0.0-beta4-1
> The following work:
> - Micsosoft.Azure.Management.Storage v6.0.0-preview
> - Microsoft.Azure.Management.Authorization v2.4.2-preview
> - ... (others removed for brevity)
> - Microsoft.Azure.DocumentDB.Core v1.0.0 

I'm not sure what the underlying cause is. In the case of Microsoft.Azure.Search specifically, one of its dependencies, Microsoft.Spatial, also fails. Issue tracking that is here: https://github.com/OData/odata.net/issues/751

**Comment by hovsepm** [comment]
@schnitty, @brjohnstmsft 
FYI, Fluent libraries starting from beta50 has been fixed (i.e. Microsoft.Azure.Management.Storage.Fluent) and published to nuget.

**Comment by markcowl** [comment]
This is also fixed for the ARM management packages.  Closing
