### ISSUE TITLE
Page provides link to Microsoft.Azure.WebJobs.Host.Scale.ConcurrencyOptions.DynamicConcurrencyEnabled that doesn't work.

### ISSUE THREAD

**Issue by GilbertLittle** [Azure/azure-sdk-for-net#27339]
There is no documentation anywhere for Microsoft.Azure.WebJobs.Host.Scale.ConcurrencyOptions.DynamicConcurrencyEnabled despite the batchsize section referring to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42ce1380-ad8b-b823-736a-41449276cf90
* Version Independent ID: 7e8aa6aa-2ed5-3ea0-9820-54544bc2224f
* Content: [QueuesOptions Class (Microsoft.Azure.WebJobs.Host) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.host.queuesoptions?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.WebJobs.Host/QueuesOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.WebJobs.Host/QueuesOptions.xml)
* Service: **azure-functions**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.WebJobs` package is maintained as [#2837](https://github.com/Azure/azure-webjobs-sdk/issues/2837).
