### ISSUE TITLE
[BUG] Azure Storage Blob Copy across containers, doesn't work with M.I.

### ISSUE THREAD

**Issue by aeaov** [Azure/azure-sdk-for-net#27358]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Describe the bug

Using the following method to copy blobs from one location to another. The method works when I copy blobs within the same account, but when I attempt to copy to another account I receive a 401 error with the following 

```
Azure.RequestFailedException: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:fb222ea8-001e-0045-79e8-2f3812000000
Time:2022-03-04T16:51:34.6883284Z
Status: 401 (Server failed to authenticate the request. Please refer to the information in the www-authenticate header.)
ErrorCode: CannotVerifyCopySource
```

I am a storage account contributor and Storage Blob Data Owner on both accounts. The following works when I use a SAS generated URI, but the client cannot generate a SAS URI when generated via DefaultAzureCredential();

The method I am using is in the reproduction steps.

### Expected behavior

When I call StartCopyFromUriAsync() with the URI, the blob should copy successfully from container A to container B.

### Actual behavior

I recieve a 401 error when attempting the copy.

### Reproduction Steps

Using the following method, attempt to copy a file from source to destination, in which the destination is a different account than the source.

```
public async Task<bool> CopyBlockBlobAsync(string sourceAccountName, string sourceContainerName, string sourceBlobName,
            string destAccountName, string destContainerName, string destBlobName)
        {
            // Construct the blob container endpoint from the arguments.
            string sourceContainerEndpoint = string.Format("https://{0}.blob.core.windows.net/{1}",
                                                        sourceAccountName,
                                                        sourceContainerName.ToLower());

            string destContainerEndpoint = string.Format("https://{0}.blob.core.windows.net/{1}",
                                                        destAccountName,
                                                        destContainerName.ToLower());


            // Get a credential and create a service client object for the blob container.
            BlobContainerClient sourceContainerClient = new BlobContainerClient(new Uri(sourceContainerEndpoint),
                                                                            new DefaultAzureCredential());

            BlobContainerClient destContainerClient = new BlobContainerClient(new Uri(destContainerEndpoint),
                                                                           new DefaultAzureCredential());


            try
            {
                // Create the container if it does not exist.
                await destContainerClient.CreateIfNotExistsAsync();

                var sourceBlobClient = sourceContainerClient.GetBlobClient(sourceBlobName);
                var destBlobClient = destContainerClient.GetBlobClient(destBlobName);

                var x = sourceContainerClient.CanGenerateSasUri;
                
                await destBlobClient.StartCopyFromUriAsync(sourceBlobClient.Uri);

            }
            catch (RequestFailedException e)
            {
                if (e.Status == StatusCodes.Status404NotFound)
                    return false;

                Console.WriteLine(e.Message);
                throw e;
            }
            return true;
        }
```

### Environment

.NET 6 Running locally in VS 2022 for Mac

Also when deployed to an App Service

**Comment by amnguye** [comment]
Hi this scenario is not supported by the storage service.

`A source blob in the same storage account can be authorized via Shared Key. However, if the source is a blob in another account, the source blob must either be public or must be authorized via a shared access signature. If the source blob is public, no authorization is required to perform the copy operation.`
From: https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob
We cited this documentation in our `StartCopyFromUri` Documentation as well.
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.startcopyfromuri?view=azure-dotnet
