### ISSUE TITLE
[Form Recognizer] Timeout on China cloud.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-sdk-for-net#27355]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
We have updated TimeoutInMinutes from 180 minutes to 400 minutes, but all tests on China cloud are running slowly causing timeout.
The pipeline result is at [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1403284&view=results).
![image](https://user-images.githubusercontent.com/81678720/156740319-5f1a16fc-ede2-499c-a067-e6e890e24438.png)

**Expected Behavior:**
All tests can be finished in the pipeline.

Shall we increase more time to run the tests, or do you have any better suggestions?

@scottaddie , @AlexGhiondea, @benbp , @maririos, @meeraharidasa , @mayurid   for notification.

**Comment by zedy-wj** [comment]
@scottaddie , @AlexGhiondea, @benbp , @maririos, @meeraharidasa , @mayurid, @jsquire - Do you have any suggestion?

**Comment by benbp** [comment]
@zedy-wj I think this issue may be waiting to be picked up in the backlog by the NET team?

**Comment by v-xuto** [comment]
@AlexGhiondea, @benbp , @maririos, @meeraharidasa , @mayurid, @jsquire - Do you have any plans or progress about this issue?

**Comment by v-xuto** [comment]
@scottaddie , @AlexGhiondea, @maririos, @meeraharidasa , @mayurid, @jsquire - There has been no update on this issue for a month. Do you have any plans or progress about this issue?

**Comment by jsquire** [comment]
@v-xuto:  We have no updates at this time.   This issue is being prioritized against the other commitments in this space.  We'll provided updates once someone has bandwidth to pick this up.
