### ISSUE TITLE
The "Methods" table is too wide

### ISSUE THREAD

**Issue by adriancuadrado** [Azure/azure-sdk-for-net#27369]
The "Methods" table is too wide and is awkward. This is because there is a row that has a word that is extremely large and without spaces. It is the row of the "StartCopyFromUriAsync" method. This is the word that is too large and without spaces:
```
Azure.Storage.Blobs.Specialized.BlobBaseClient.StartCopyFromUri(System.Uri,System.Collections.Generic.IDictionary{System.String,System.String},System.Nullable{Azure.Storage.Blobs.Models.AccessTier},Azure.Storage.Blobs.Models.BlobRequestConditions,Azure.Storage.Blobs.Models.BlobRequestConditions,System.Nullable{Azure.Storage.Blobs.Models.RehydratePriority},System.Threading.CancellationToken)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21c7de47-139d-9d7e-dc6e-66b1d68dab54
* Version Independent ID: 60bb6574-ef51-f313-c40c-64d9034c661b
* Content: [BlobClient Class (Azure.Storage.Blobs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient?view=azure-dotnet#methods)
* Content Source: [xml/Azure.Storage.Blobs/BlobClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs/BlobClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@adriancuadrado We will check what can be done to fix the formatting and let you know.

**Comment by seanmcc-msft** [comment]
This issue has been resolved - https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient?view=azure-dotnet#methods
