### ISSUE TITLE
Failed to add reference. The package 'AppForSharePointOnlineWebToolkit' tried to add a framework reference to 'Microsoft.IdentityModel' which was not found in the GAC. this is possibly a bug in the package. Please contact package owners for assistance.

### ISSUE THREAD

**Issue by Omii27** [Azure/azure-sdk-for-net#27374]
### Library name and version

AppForSharePointOnlineWebToolkit v3.1.5

### Query/Question

I wanted to authenticate to SharePoint from .NET application with help of CSOM but failed to add "AppForSharePointOnlineWebToolkit" package

### Environment

.NET 4.5 
IDE Visual Studio 19

**Comment by jsquire** [comment]
This issue has been transferred to the repository where issues for the Sharepoint Framework are tracked as [#7786](https://github.com/SharePoint/sp-dev-docs/issues/7786).
