### ISSUE TITLE
Follow guidelines for ToString hiding

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#27387]
The guidelines state the [following](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-service-editor-browsable-state):
YOU SHOULD apply the [EditorBrowsable(EditorBrowsableState.Never)] attribute to methods on the model type that the user isn’t meant to call.

Adding this attribute will hide the methods from being shown with IntelliSense. A user will almost never call GetHashCode() directly. Equals(object) is almost never called if the type implements IEquatable<T> (which is preferred). **Hide the ToString() method if it isn’t overridden.**

We should consider going through all libraries to implement this guidance and adding an analyzer to prevent new instances from cropping up once we have a baseline.

**Comment by JoshLove-msft** [comment]
Should this apply only to model types, or client types as well?

/cc @KrzysztofCwalina @tg-msft

**Comment by annelo-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/12831

It would be good to land the guidelines on ToString() before doing an overhaul of the SDK on it.
