### ISSUE TITLE
Update the DPG Quickstart Guide

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#27395]
In order to set partner teams up for success, the DPG Quickstart Guide should describe a process that prepares the service team for the first arch board meeting.  This issue will track the work to improve the documentation in ways we discover by working with service teams on creating DPG libraries

- [x] Add a section on uploading to APIView
- [x] Remove the dependency on Azure.Core.Experimental from the template: See [this APIView](https://apiview.dev/Assemblies/Review/fe482cb7d6b549ee83b36915d9fcd417)
- [x] Clarify information about the `-inputfiles` argument to the generation script -- if the service has a readme.md with tags for client generation, this should be specified to the generation script.

**Comment by chunyu3** [comment]
Hi @annelo-msft 
 < Clarify information about the -inputfiles argument to the generation script -- if the service has a readme.md with tags for client generation, this should be specified to the generation script.

I don't quite understand. Do you mean our script will support both inputfiles and readme.md to generate client library?

**Comment by annelo-msft** [comment]
@lmazuel can you clarify regarding our policy to take the readme.md from azure-rest-api-specs repo instead of a .json file directly?
