### ISSUE TITLE
GetEntityOrNullAsync

### ISSUE THREAD

**Issue by fabiomaulo** [Azure/azure-sdk-for-net#27419]
### Library name

Azure.Data.Tables

### Descrption

The matter that we have an `Azure.RequestFailedException` in front of an unexistent entity sounds like a regression to the dawn of Azure SDK.
You already have a 404 but, when I'm trying to read the value you throw me an exception with the status-code 404.
My use-case has some write-once properties so I can´t use Upsert with the merge.
A `GetEntityOrNull`, and its pair `GetEntityOrNullAsync`, would be very useful to avoid the noise of `try-catch` and the performance issue of throwing the exception (and its call-stack).
Thanks

**Comment by fabiomaulo** [comment]
An alternative could be an extension method as `TryGetEntity` with the behavior similar to the `IDictionary<T>.TryGetValue`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Duplicate of #25626
