### ISSUE TITLE
[QUERY] How to call unsupported APIs

### ISSUE THREAD

**Issue by thegrahamking** [Azure/azure-sdk-for-net#27412]
### Library name and version

Microsoft.Azure.Management.Websites 3.1.2

### Query/Question

There are now ARM APIs for managing Azure Function keys (function, master and system).

I don't believe the official docs include them yet but it's documented in https://github.com/Azure/azure-functions-host/issues/3994#issuecomment-507693624 and my colleague blogged about them [here](https://www.markheath.net/post/managing-azure-functions-keys-2).

How can we use Microsoft.Azure.Management.Websites or similar to call these APIs given that there are no .NET methods.  Does the SDK provide a convenient method to provide a URI, HTTP method and payload etc and it handles the API version, authentication etc?

Thank you

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@thegrahamking  thank you for reaching us, all our sdks are writing / generating according to the swagger files that describes the officially supported capabilities,  so unfortunately we can't support any unsupported / internal APIs.

**Comment by ArthurMa1978** [comment]
I flip it to `Service Attention`, which the website service can help on this
