### ISSUE TITLE
[BUG] Frequent Azure.RequestFailedException messages from Functions when trying to access Azure Storage Blobs and Queues due to expired authentication tokens

### ISSUE THREAD

**Issue by AlexPiksel** [Azure/azure-sdk-for-net#27416]
### Library name and version

Azure.Storage.Blobs 12.10.0, Azure.Storage.Queues 12.8.0, Azure.Identity 1.5.0

### Describe the bug

This has already been raised with Azure Support as ticket 2201190050001832. Despite the fact that this looks environmental, only affecting a single Azure region, they have insisted that this must be raised with the development team, as they cannot see what is causing the problem after some weeks of investigation.

We have a production deployment using a Live/Live approach, with identical code and resources in the West Europe and North Europe regions. Both regions read and write data to a single Azure Storage account, which is a Standard_GRS account with the primary in West Europe, and the secondary in North Europe.

This setup has been working without problem for over a year. However, following our last release we started to see regular `Azure.RequestFailedException` messages from multiple Azure Functions in the West Europe region when trying to perform storage operations, for both Blob Storage and Storage Queues. There are **no** issues in the North Europe region. Both regions are using the same Service Principal.

We can see these same problems in our pre-production environment, which is also live/live in West Europe/North Europe, and again the exceptions are **only** occurring in the West Europe region. This environment also uses the same service principal for both regions, although this is separate from the production Service Principal.

Sample exceptions are attached, one relating to Blob Storage and one to Queue Storage. Both refer to the request failing due to the use of expired credentials.

[blob_exception.txt](https://github.com/Azure/azure-sdk-for-net/files/8207102/blob_exception.txt)
[queue_exception.txt](https://github.com/Azure/azure-sdk-for-net/files/8207111/queue_exception.txt)

In terms of frequency, there have been 30 instances in production in the last 48hrs. These seem to happen at regular times past the hour throughout the day - in the last 48hrs the Queue Storage exceptions have been typically occurring at xx:05, while the Blob Storage exceptions have been occurring at xx:45. However, these do not occur every hour. These times are very likely connected to the cron expressions of timed functions, which run every 10 minutes.

Our authentication is all out-of-the-box - we are using Azure AD Service Principals, and constructing `ClientSecretCredential` objects using their client id, tenant id and client secret. We then pass these into the `BlobServiceClient(Uri serviceUri, TokenCredential credential, BlobClientOptions options = null)` constructor to create a BlobServiceClient, and the `QueueServiceClient(Uri serviceUri, TokenCredential credential, QueueClientOptions options = null)` constructor to create a QueueServiceClient. My understanding is that this approach should handle all necessary renewing of the AAD tokens without us having to manually manage these. Note that we are only constructing each service client once per endpoint, then maintaining this as a property of a singleton class for the lifetime of the function.

I have noted the current version of the Blob, Queue and Identity libraries above - these are the latest releases. Prior to our most recent release, we were using the same versions of the Storage libraries, but with Azure.Identity 1.4.1 rather than 1.5.0. 

### Expected behavior

Azure Storage libraries will manage the expiry and renewal of all authentication tokens, and no exceptions will occur due to expired tokens, regardless of region.

### Actual behavior

Frequent exceptions from Functions in the West Europe when talking to Blob and Queue storage, due to expired authentication tokens.

### Reproduction Steps

While I have not had a chance to build a toy project to confirm this, these steps match our production and pre-prod environment.

- Deploy a Standard_GRS V2 Storage account with the primary in West Europe, the secondary in North Europe
- Create a V3 Azure Function, .NET Core, using `ClientSecretCredential` and an AD Service Principal to build a `BlobServiceClient`/`QueueServiceClient`, maintaining this in a singleton class.
- Set a 'TimerTrigger' to Read/write from the blob storage/queue every 10 minutes.
- Deploy to both North Europe and West Europe regions, and leave to soak for 24hrs.
- Check for exceptions in West Europe region.

### Environment

Built using .NET Core 3.1.416
Functions are 64-bit, V3, Always On, running on a Windows App Service Plan (S1:1)

**Comment by SaurabhSharma-MSFT** [comment]
@AlexPiksel Apologies for your trouble.  I am redirecting this to services team to investigate it further and help you with the resolution.
