### ISSUE TITLE
[BUG] BlobClient Download methods not returning the right results

### ISSUE THREAD

**Issue by GCoding83** [Azure/azure-sdk-for-net#27424]
### Library name and version

Azure.Storage..Blobs 12.7.0

### Describe the bug

I have a model that contains two lists of interfaces:

```
public class MyClass
{
     public List<MyFirstInterface> FirstList { get; set; }

     public List<MySecondInterface> SecondList { get; set; }
}
```
I serialize the model and upload it to my Azure Blob Storage account. When I try to retrieve the blob content, one of my two lists is null, even though it should not be.

The weird part is that if I retrieve the blob using a blob-triggered Azure Function, the retrieved content is correct. My two lists are non-null and non-empty. But when I try to retrieve the blob myself using the BlobClient class of Azure.Sotrage.Blobs, I get one of the two lists null.

I have tried 2 different methods for retrieving the content of my blob as a string. First, I have used the DownloadToAsync(stream) method:

          
                using (var stream = new MemoryStream())
                {
                    await blobClient.DownloadToAsync(stream);
                    var bytes = stream.ToArray();
                    string content = Encoding.UTF8.GetString(bytes);
                }
                

Second, I have used the DownloadAsync() method:

              
                var response = await blobClient.DownloadAsync();
                string content = "";

                using (var streamReader = new StreamReader(response.Value.Content))
                {
                    while (streamReader.EndOfStream == false)
                    {
                        content += streamReader.ReadLine();
                    }
                }

Both methods return the model with one of my two lists null. I don't know what else to try at this point. Like I said, the returned model has the right values when I use an Azure Function with a blob trigger, but I cannot get the right content through the download methods of BlobClient, which is really odd.

Any suggestions or explanations?

### Expected behavior

The two download methods should return the right serialized values when I call one of the Download methods.

### Actual behavior

It returns the wrong value: one of my two lists is null, when it shouldn't.

### Reproduction Steps

I use a model with two non-empty lists of interfaces:

public class MyClass
{
     public List<MyFirstInterface> FirstList { get; set; }

     public List<MySecondInterface> SecondList { get; set; }
}

I serialize my model and upload it my Azure Blob Storage

I then try to retrieve the content as a string using any one of two Download methods of my blob client. First:

               using (var stream = new MemoryStream())
                {
                    await blobClient.DownloadToAsync(stream);
                    var bytes = stream.ToArray();
                    string content = Encoding.UTF8.GetString(bytes);
                }
                
Second:
              
                var response = await blobClient.DownloadAsync();
                string content = "";

                using (var streamReader = new StreamReader(response.Value.Content))
                {
                    while (streamReader.EndOfStream == false)
                    {
                        content += streamReader.ReadLine();
                    }
                }

### Environment

.NET 6.0, in C#. I have a class library that retrives blobs by their IDs. I am on Visual Studio 2022 17.10, 64bits.

**Comment by PramodValavala-MSFT** [comment]
@GCoding83 Does the string have the right content before deserializing? Also, do you see the content as expected when checking the blob from the portal?

**Comment by GCoding83** [comment]
Thanks for the help. I actually realized that the problem was with my blob-retrieval logic. There is no real bug on your end. Sorry ab out that!
