### ISSUE TITLE
[BUG][Azure.Core.TestFramework] The new TestFramework hide exception and finished the call statement without error

### ISSUE THREAD

**Issue by aim-for-better** [Azure/azure-sdk-for-net#27440]
### Library name and version

Azure.Core.TestFramework

### Describe the bug

The new test framework will handle exception and close the scope immediately instead of throw the exception, which makes me be confused. For example, I call a get resource API, if the resource doesn't exist it will return 404 and some SDK will throw exception.
But test framework hide this exception and finish the call statement, and my test stuck in the running. This is not clear
This is just an example, all the exception in during call services SDKs which will be hided

### Expected behavior

Throw the exception, don't  hide it and finish the test with Failed.

### Actual behavior

Hide exception and return without error

### Reproduction Steps

write the test case and use other azure services' SDK with the condition that SDK will throw exception

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by JoshLove-msft** [comment]
Hi @aim-for-better, 
This is certainly not the intent to hide any exceptions triggered by your library. Can you please include a specific test that can be run in order to reproduce the behavior?

**Comment by aim-for-better** [comment]
You can run any test which will throw exception during call SDK. For example try to get a non-existing resource. I am sorry that I can not upload my test cases now.

**Comment by JoshLove-msft** [comment]
> You can run any test which will throw exception during call SDK. For example try to get a non-existing resource. I am sorry that I can not upload my test cases now.

I don't think this is correct. Many tests throw an exception after the service response is returned and they are all working correctly. If you can provide a specific example, we can investigate further.
