### ISSUE TITLE
[FEATURE REQ] Azure.Core.TestFramework support to use with Fiddler

### ISSUE THREAD

**Issue by aim-for-better** [Azure/azure-sdk-for-net#27443]
### Library name

Azure.Core.TestFramework 

### Please describe the feature.

Hi team,
I find that Azure.Core.TestFramework can not run test with the fiddler, is it by design? Fiddler is a very useful tool to debug when testing SDK? Do we have a plan to support to run test during the fiddler is running?

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by JoshLove-msft** [comment]
Hi @aim-for-better,
This can be enabled using the AZURE_ENABLE_FIDDLER env var or the EnableFiddler runsettings param:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/README.md#misc

**Comment by aim-for-better** [comment]
> Hi @aim-for-better, This can be enabled using the AZURE_ENABLE_FIDDLER env var or the EnableFiddler runsettings param: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/README.md#misc

Thanks for your reply.

**Comment by aim-for-better** [comment]
Reopen this issue, the method in this doc does not work

**Comment by aim-for-better** [comment]
System.AggregateException : Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.)
  ----> Azure.RequestFailedException : The SSL connection could not be established, see inner exception.
  ----> Azure.RequestFailedException : The SSL connection could not be established, see inner exception.
  ----> Azure.RequestFailedException : The SSL connection could not be established, see inner exception.
  ----> Azure.RequestFailedException : The SSL connection could not be established, see inner exception.
  ----> System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
  ----> System.Security.Authentication.AuthenticationException : The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
  ----> System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
  ----> System.Security.Authentication.AuthenticationException : The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
  ----> System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
  ----> System.Security.Authentication.AuthenticationException : The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
  ----> System.Net.Http.HttpRequestException : The SSL connection could not be established, see inner exception.
  ----> System.Security.Authentication.AuthenticationException : The remote cer

**Comment by JoshLove-msft** [comment]
If you are using the environment variable, please make sure to restart your IDE.

**Comment by aim-for-better** [comment]
> If you are using the environment variable, please make sure to restart your IDE.

Hi @JoshLove-msft  Thanks for your reminder, I am sure that after I ran the command "Set AZURE_ENABLE_FIDDLER=true" in cmdlet I restarted my visual studio.
And I also tried to modify the [runsetting](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/nunit.runsettings), and rebuild the solution, but failed.

My env is visual studio 2022, I set the env in cmdlet and  start visual studio from cmdlet.

I understand your point, I am sure that the env can be load by visual studio.  Could you please help double confirm this?

**Comment by JoshLove-msft** [comment]
Ok thank you - the error seems to indicate that the cert issuer is not matching what we'd expect from Fiddler.
Can you try putting a breakpoint here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/ProxyTransport.cs#L44

And try to see what the value is for `certificate.Issuer`?

**Comment by aim-for-better** [comment]
> Ok thank you - the error seems to indicate that the cert issuer is not matching what we'd expect from Fiddler. Can you try putting a breakpoint here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/ProxyTransport.cs#L44
> 
> And try to see what the value is for `certificate.Issuer`?

Sure, I will try and update it later, today I have another work to do.
