### ISSUE TITLE
 AutoRest.ClientRuntime Install fails for UWP

### ISSUE THREAD

**Issue by daronyondem** [Azure/azure-sdk-for-net#2744]
Getting the error below trying to add the AutoRest.ClientRuntime v.2.3.4 package into a UWP app targeting Build 14393. I have been told dotnet rest runtime client is owned sdk-for-net project.  https://github.com/Azure/autorest/issues/1737#issuecomment-273825921

Restoring packages for C:\path\project.json...
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x64-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x64-aot).
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-x86-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-x86-aot).

This looks related; https://github.com/StefH/System.Linq.Dynamic.Core/issues/33

**Comment by markcowl** [comment]
This should be fixed in the latest runtime packages.

**Comment by daronyondem** [comment]
It is fixed! Thanks.
