### ISSUE TITLE
[FEATURE REQ] DownloadToByteArray for partial load of header information of big file from storage

### ISSUE THREAD

**Issue by agravity-philipp** [Azure/azure-sdk-for-net#27442]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

In the v11 there was this option to partially load data from storage with given length:

`
var maxHeaderBytes = Math.Min(blobProperties.ContentLength, QueueUtils.GetMaxFileSize(context));
            byte[] originalBlobBytes = new byte[maxHeaderBytes];
            await blob.DownloadRangeToByteArrayAsync(originalBlobBytes, 0, 0, maxHeaderBytes).ConfigureAwait(false);
`

What would be the equivalent to v12? Could not find any method which solves this. I don't want to download the whole (big) file to Azure Function to read out the header information.

I only found another request in that direction on another forum: https://quabr.com/59995185/download-only-the-first-few-bytes-of-an-azure-blob

**Comment by SatishBoddu-MSFT** [comment]
hello @agravity-philipp We are routing this query to Service Team's Attention.
