### ISSUE TITLE
All pages' "View and Submit Feedback for This Product" links are broken

### ISSUE THREAD

**Issue by jmal1** [Azure/azure-sdk-for-net#27450]
For example on [this page](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/data.appconfiguration-readme?view=azure-dotnet), the "This Product" button at the bottom leads to[ this unknown page](https://feedback.azure.com/forums/170031-sdk-and-tools). 

Repro'd in several other products

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3628e326-be45-e441-eb62-627b721d3e70
* Version Independent ID: e4e26910-eda8-a7f8-de42-150232c24a8b
* Content: [Azure Application Insights libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/insights?view=azure-dotnet)
* Content Source: [api/overview/azure/insights.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/insights.md)
* Service: **application-insights**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@danieljurek Can you please help on this.

**Comment by danieljurek** [comment]
Thanks for the report! It looks like we can change the URL here -- https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/docfx.json#L71 ... 

The question becomes: to what do we change this URL? @scottaddie

**Comment by scottaddie** [comment]
@danieljurek Please review this PR ☝️
