### ISSUE TITLE
Add guidance for writing samples to DPG docs

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#27452]
Basic samples guidance is  illustrated in: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/template/Azure.Template/samples.

Key features of Azure SDK .NET Samples include:

- `samples` directory: `azure-sdk-for-net/tree/main/sdk/<service>/<library>/samples`: see [example](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/template/Azure.Template/samples)
- `README.md` providing a TOC for all available samples under `<library>/samples`: see [example](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/template/Azure.Template/samples/README.md)
- `Sample<i>_<scenario>.md` files describing the scenario the sample is illustrating under `<library>/samples`: see [example](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/template/Azure.Template/samples/Sample1_HelloWorld.md)
- `test/samples` directory: `azure-sdk-for-net/tree/main/sdk/<service>/<library>/tests/samples`: see [example](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/template/Azure.Template/tests/Samples)
- tests inheriting from TestFramework `SamplesBase` that implement all sample code under `<library>/tests/samples`: see [example](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/template/Azure.Template/tests/Samples/MiniSecretClientSamples.HelloWorld.cs#L13)
- **snippet regions** identifying snippets to show in README and Samples files: see [example](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/template/Azure.Template/tests/Samples/MiniSecretClientSamples.HelloWorld.cs#L21-L30)

A nice example of a service library that follows the .NET samples guidance is MetricsAdvisor: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/metricsadvisor/Azure.AI.MetricsAdvisor

**Comment by annelo-msft** [comment]
Please put the documentation under: https://github.com/Azure/azure-sdk-for-net/tree/main/doc/Data%20Plane%20Code%20Generation

**Comment by annelo-msft** [comment]
> Is this a must? The metrics advisor samples does not follow this. It just inherits TestEnvironment.

It is definitely a best practice.  @kinelski, is there a reason Metrics Advisor needed to inherit from TestEnvironment and not SamplesBase?

According to the Test Documentation:
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/README.md#test-environment-and-live-test-resources
- https://github.com/Azure/azure-sdk-pr/blob/main/training/azure-sdk-quality/tutorials/writing-tests/functional-tests/functional-tests-dotnet.md#create-the-testenvironment-class

The environment represents the environment you set up with the `New-TestResources.ps1` script.  Classes like SamplesBase, LiveTestBase, and RecordedTestBase all add features that are needed for the different types of tests.  For example, SamplesBase adds a credential that prevents a bug with Azure.Identity caching credentials.

You can see that most HLC libraries [use SamplesBase for their samples](https://grep.app/search?q=%3A%20SamplesBase&filter[repo][0]=Azure/azure-sdk-for-net&filter[path][0]=sdk/).  Those that don't won't get the benefits of the features in this class.

Thanks!

**Comment by kinelski** [comment]
@annelo-msft We had no particular reason other than my lack of understanding about how the Test Framework works. I created an issue to track this work: https://github.com/Azure/azure-sdk-for-net/issues/27590

**Comment by annelo-msft** [comment]
We don't need to block on [Consolidate smoke tests and best practices with DPG partner tools](https://github.com/Azure/azure-sdk-for-net/issues/26345) - we can loop back and update this after that merges.
