### ISSUE TITLE
Synapse: Rename types that overlap with Azure.ResourceManager types.

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#27463]
[Duplicates.txt](https://github.com/Azure/azure-sdk-for-net/files/8219052/Duplicates.txt)

Synapse.Artifacts has many types that have duplicate names as in ARM libraries.  We will need to give these types different names or move to DPG clients to prevent naming conflicts.

**Comment by pallavit** [comment]
@annelo-msft is this still valid?

**Comment by annelo-msft** [comment]
I no longer work on this library, so it might be better to check in with someone who does.  IIRC, the concern that motivated filing this issue was that type names were in conflict with existing types in the related ARM library, and as such violated design guidelines.  If that's still the case, they would need to be renamed before GA.
