### ISSUE TITLE
Improve operation instrumentation during tests

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#27461]
Discussing PR #27399, we realized some improvements could be made to avoid tests doing the wrong thing. To unblock the PR and help unblock some occasionally-failed tests in Core, we made a few localized changed toward this end.

For long-term support, however, we discussed a few ideas I'm listing below for posterity. We should explore these and other ideas and make sure there's no negative ramifications of changes that might regress other tests.

Numbered only for easy reference - not intended as priority or preference order, or are these all necessarily alternatives. Some are just related ideas.

1. Since the default delay is conceptually tied to the transport e.g., `HttpClientTransport` (live), 'ProxyTransport' (recorded), `MockTransport`, etc., we could define a default delay strategy appropriate for each. This delay strategy would be used by the OperationInterceptor.
2. In the PR, we pass a `RecordedTestMode`. For `ClientTestBase` we are currently assuming `Playback`, though there might be some benefit to add a `Mock` value and check against both that and `Playback` in `OperationInterceptor`'s constructor. We'd want to think about ramifications, like the fact that we can read (and do for some live tests) the value from environment variables. Whether that matters may be purely hypothetical, though. I simply raise that as an example of adding to the enum.

/cc @m-nash @JoshLove-msft

**Comment by pallavit** [comment]
@heaths do you still see value in implementing this? What scenario would this benefit?

**Comment by heaths** [comment]
So much has changed with the existing support since I opened this, I don't think it's worth keeping open. Maybe be useful to reference if we have issues in the future, though. /cc @JoshLove-msft
