### ISSUE TITLE
[BUG] DefaultAzureCredential and Visual Studio debugging fails in AWS EC2 Instance

### ISSUE THREAD

**Issue by ForteUnited** [Azure/azure-sdk-for-net#27477]
### Library name and version

Azure.Identity 1.5.0

### Describe the bug

Attempting to use DefaultAzureCredential when debugging locally and when running inside an AWS EC2 instance fails with the following exception:

Message: 
Microsoft.Graph.ServiceException : Code: generalException
Message: An error occurred sending the request.

---- Azure.Identity.AuthenticationFailedException : ManagedIdentityCredential authentication failed: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
-------- System.Text.Json.JsonReaderException : '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.

With an inner stack trace of:

    ----- Inner Stack Trace -----
ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
Utf8JsonReader.ConsumeValue(Byte marker)
Utf8JsonReader.ReadFirstToken(Byte first)
Utf8JsonReader.ReadSingleSegment()
Utf8JsonReader.Read()
JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
**ImdsManagedIdentitySource.HandleResponseAsync**(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)

![image](https://user-images.githubusercontent.com/8826876/157711656-feee550c-9405-4327-aa21-65cfe4f031a1.png)

ImdsManagedIdentitySource.HandleResponse seems to check for a few HTTP error codes. In my current EC2 instance the call to http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=https%3A%2F%2Fgraph.microsoft.com responds with a 404 Not Found and some HTML content. This error code is not being handled explicitly the same way 400, 502, and 504 codes are handled and then it all goes off the rails.

I'm not even sure why this call is being made to a 169 address to begin with but it behaves the same way everywhere I have checked.

### Expected behavior

DefaultAzureCredential when using Visual Studio and debugging will work as expected and either use my VS signed in credentials or open an interactive browser session to login.

### Actual behavior

Exception thrown and program and integration test harness fails.

### Reproduction Steps

Run this on an EC2 instance with who knows what corporate specific virtual network settings and EC2 CIS controls installed.

**Comment by ForteUnited** [comment]
This is the code that I want to say has a bug. It is not handling the 404 and is trying to parse the HTML content of the not found page that is returned.

![image](https://user-images.githubusercontent.com/8826876/157713332-e9b87af9-a9e0-4916-8f81-4dccbabb781b.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @ForteUnited  - This should be resolved in version [1.6.0-beta.2](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#160-beta2-unreleased) - would you mind trying that to validate?

**Comment by ForteUnited** [comment]
I don't see a beta.2 in the nuget.org feed. I tried with the beta.1 version and I'm getting fundamentally the same error:

![image](https://user-images.githubusercontent.com/8826876/157728340-76c58af2-ea52-4021-85ad-ea3b27eec7de.png)

**Comment by christothes** [comment]
Oh sorry, I meant beta.1. Yes, this fix only eliminates the unhandled json parsing error. 

Looking at the error again, I see the actual issue is that the EC2 VM is responding on the Managed Identity endpoint and returning content. This should be treated as a `CredentialUnavailableException` rather than an `AuthenticationFailedException`. However, in the meantime, you can work around this by disabling the `ManagedIdentityCredential` via this option:

https://github.com/Azure/azure-sdk-for-net/blob/1645ea51d73e7b4ec240cbdb88f99ae2039a7ccb/sdk/identity/Azure.Identity/src/DefaultAzureCredentialOptions.cs#L80
