### ISSUE TITLE
Autorest.CSharp version is not comparable with Azure.Core version

### ISSUE THREAD

**Issue by chunyu3** [Azure/azure-sdk-for-net#27471]
The SDK generated by Autorest.CSharp is not comparable with Azure.Core. Need to upgrade Autorest.CSharp version together with the correct/comparable Azure.Core version

**Comment by chunyu3** [comment]
When we upgrade Autorest.Csharp version which is based on the latest Azure.Core, but Azure.Core may not release the new version. As a result, it will fail to build the SDK.

**Comment by pallavit** [comment]
@chunyu3 is this still a valid concern.

**Comment by chunyu3** [comment]
> When we upgrade Autorest.Csharp version which is based on the latest Azure.Core, but Azure.Core may not release the new version. As a result, it will fail to build the SDK.

@pallavit This issue is resolved I think. We can close it. Thanks

**Comment by pallavit** [comment]
Sounds good. Thank you for taking a look at it. Closing it.
