### ISSUE TITLE
[Synapse] TestSparkSessionJob failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#27499]
Synapse runs are failing with:

> Error message
> Session: 4 did not return success. Current job state: dead. Actual result: Failed. Error (if any): Azure.Analytics.Synapse.Spark.Models.SparkServiceError
> Expected: True
> But was:  False
> 
> 
> Stack trace
>    at Azure.Analytics.Synapse.Spark.Tests.SparkSessionClientLiveTests.TestSparkSessionJob() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Spark/tests/SparkSessionClientLiveTests.cs:line 54
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1424892&view=results

@jsquire for notification.

**Comment by annelo-msft** [comment]
@v-xuto, @pshao25 is taking ownership of this library.  Thanks!

**Comment by jsquire** [comment]
Given the age of this issue, I'm going to close it as stale.  If tests continue to fail, please file a new issue.

**Comment by pshao25** [comment]
This seems a random issue and cannot be reproed. It does not fail in the following builds.
