### ISSUE TITLE
Support custom error data extraction in RequestFailedException

### ISSUE THREAD

**Issue by AlexanderSher** [Azure/azure-sdk-for-net#27490]
`ClientDiagnostics` type has a virtual method that can be overridden: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs#L52 
If `ExtractFailureContent` is overridden in derived type, there is no way to use it when we call `RequestFailedException` constructor directly. We need some way to inject custom error data extraction logic into `RequestFailedException`

**Comment by annelo-msft** [comment]
Related to https://github.com/Azure/azure-sdk-for-net/issues/24031
