### ISSUE TITLE
Using Service Principal to update service bus yields "ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription."

### ISSUE THREAD

**Issue by andrerav** [Azure/azure-sdk-for-net#2749]
Hi,

I am using the Azure SDK and the management API in C# to update a service bus namespace. The API is accessed using a service principal and an Azure AD application that has been granted access to the Azure Service Management API. However, as soon as I try the following:

`nsClient.Namespaces.List(); // nsClient is a ServiceBusManagementClient instance`

I receive the following error: 

> "ForbiddenError: The server failed to authenticate the request. Verify that the certificate is valid and is associated with this subscription."

Does the service principal need to be a co-admin on this subscription to use the ASM, [as indicated here](https://github.com/Azure/azure-xplat-cli/issues/2040)?

**Comment by markcowl** [comment]
@andrerav No.  co-admin is a concept for RDFE, the old management APIs corresponding to the old portal.     If you are using this library:   https://www.nuget.org/packages/Microsoft.Azure.Management.ServiceBus/0.0.1-preview   you are using the new ARM management APIs and you can use ServicePrincipal credentials, you just need to make sure the servicePrincipal is granted the appropriate RBAC role to the subscription or resource group containing the namespace for the level of access you want (read, write, admin, etc.).

If you are using this library:  https://www.nuget.org/packages/Microsoft.WindowsAzure.Management.ServiceBus/0.19.0-preview 

Then you are interacting with old RDFE management APIs, and ServicePrincipal cannot be used, you would need to use client certificate authentication, or grant co-admin access to a user principal and use user principal credentials.  There is no way to assign co-admin access to a service principal in RDFE.

**Comment by markcowl** [comment]
@andrerav BTW, I would highly suggest you use the ARM APIs, if that is an option for you.

**Comment by markcowl** [comment]
Closing for lack of response.  Please file a new issue if you see this error in an ARM client
