### ISSUE TITLE
[Synapse] Azure.Analytics.Synapse.Artifacts has types object needing change to BinaryData

### ISSUE THREAD

**Issue by pshao25** [Azure/azure-sdk-for-net#27495]
### Library name

Azure.Analytics.Synapse.Artifacts

### Please describe the feature.

Azure.Analytics.Synapse.Artifacts has many types of object, which is a user-defined JSON. We plan to change this type to BinaryData. And Uri, EncryptedCredential as well. 
We need to add appropriate [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)] in DPG release.

See details in In https://github.com/Azure/azure-sdk-for-net/pull/27326

**Comment by pallavit** [comment]
@pshao25 is this still a valid concern?

**Comment by pshao25** [comment]
> @pshao25 is this still a valid concern?

I think so, and sounds dynamic json is a candidate solution? @annelo-msft

**Comment by pallavit** [comment]
@pshao25 can you please help me understand how dynamic json is a solution here?
