### ISSUE TITLE
Tag nuget packages with service/api-version

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2750]
### Description  
To support AzureStack, add tags to nuget definition to include latest service and api-version.  Include automation to build a map (service, api-version) => package .This includes the following tasks:

- [ ]  Figure out how to extract service and api-version metadata from generated code for a library
- [ ] Automatically update the tag in the library to match the correct service/api version
- [ ] Communicate with AzureStack team to tag older packages containing the APIs they use for TP3
- [ ] Create a central profile map defining the function (service, api-version) -> package name + version
- [ ] Create automation to update this map when / after packages are published

### Cost: 4

**Comment by shahabhijeet** [comment]
@markcowl this was fixed around Dec 2017 timeframe.
Closing this issue.
