### ISSUE TITLE
[QUERY] Delay after setting the response/mock in ApiManagement

### ISSUE THREAD

**Issue by schw3de** [Azure/azure-sdk-for-net#27501]
### Library name and version

Microsoft.Azure.Management.ApiManagement 

### Query/Question

We use the Api Management to mock endpoints. We set mock endpoints during tests and depending on which test is running, we change the mock.

With help of `PolicyContract` we set our mocked content:
```
<policies>
    <inbound>
        <base />
        <return-response>
            <set-status code="200" />
            <set-header name="Content-Type" exists-action="override">
                <value>text/xml</value>
            </set-header>
            <set-body template="liquid">
               <mockedcontent>content</mockedcontent>
            </set-body>
        </return-response>
    </inbound>
    <backend>
        <base />
    </backend>
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
    </on-error>
</policies>
```

In code we use the nuget package `Microsoft.Azure.Management.ApiManagement` to set the `PolicyContract`. When we call the `IApiOperationPolicyOperations.CreateOrUpdateWithHttpMessagesAsync` the operation is successful and afterwards `IApiOperationPolicyOperations.GetWithHttpMessagesAsync` returns new updated `PolicyContract`. But here comes the problem. The mocked endpoint itself doesn't return the set mocked content directly. There is a delay before the endpoint is being updated. Currently we have code to check if the endpoint is updated. But this is creating other problems in our architecture.

Is this behavior attended? Should the method `IApiOperationPolicyOperations.CreateOrUpdateWithHttpMessagesAsync` not return successful first when the endpoint is returning the updated value?

Is there another way how to detect if the mock endpoint has `really` updated?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@Yao725  please help to check if this is happened on sdk side or a service delay

**Comment by schw3de** [comment]
I checked this behavior on https://portal.azure.com and could also reproduce this issue. If I set the response in the Design tab and afterwards quickly go to the Test tab it do not always show directly the new response. 
![image](https://user-images.githubusercontent.com/1119882/158521790-85226288-4508-4ba6-84ba-8eba1494a791.png)
![image](https://user-images.githubusercontent.com/1119882/158522286-c540379f-ee83-4ac9-923d-9ba8063f35ba.png)
In this case I have to execute test again to get the correct value.

**Comment by Yao725** [comment]
Hi @schw3de, per your description, I think it is a service-related issue because our SDK worked as expected but there is a delay between setup and status update. I tagged this issue with `service attention` and hope we can get some help from the service team.

**Comment by schw3de** [comment]
@Yao725 Thanks for the update!

**Comment by Yao725** [comment]
Hi @schw3de, sorry I haven't updated this issue for a long time, it seems the service team will not respond here. Do you resolve this issue? If not, maybe you can open an ICM to get more assistances.

**Comment by schw3de** [comment]
Hi @Yao725,

Thanks for your reply. No, the issue could not be fixed. Sorry to hear that the service team will not respond.
We will not continue to investigate the issue further with an ICM issue, because of resources.

Too bad the issue can not be resolved, but I guess there are just not enough people interested in this topic.

I wish you all the best!

**Comment by Yao725** [comment]
Thanks for your reply. For your issue, it's hard for us to do something in SDK side to fix it, really sorry for that.

**Comment by Yao725** [comment]
Will close this issue, feel free to open new issues if you have problems with SDK, thanks.
