### ISSUE TITLE
[BUG] Outlook Channel Not Available in Azure Bot Service SDK

### ISSUE THREAD

**Issue by MuyangAmigo** [Azure/azure-sdk-for-net#27503]
Hi there,

We found that in the Dot Net SDK for Azure Bot Service, the Outlook Channel isn't available there: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/botservice/Microsoft.Azure.Management.BotService/src/Generated/Models/ChannelName.cs

![image](https://user-images.githubusercontent.com/11220663/157854017-0bdb6703-483b-4e6f-9f8c-7939482137ee.png)

But this can be configured via Azure Portal:

![image](https://user-images.githubusercontent.com/11220663/157853893-85151179-c2de-437d-887d-bae2d5b3c414.png)

Can this be added into the SDK so that we can programmatically configure it via code?

Thanks!

**Comment by ArthurMa1978** [comment]
Check the https://github.com/Azure/azure-rest-api-specs/blob/main/specification/botservice/resource-manager/Microsoft.BotService/stable/2021-03-01/botservice.json#L2863-L2886 there is no 'Outlook' channel, and also the preview  version is same, please check with Bot Service team for more information
