### ISSUE TITLE
Better Examples for Cosmos Container.ReadItemAsync

### ISSUE THREAD

**Issue by kharlamov** [Azure/azure-sdk-for-net#27514]
Clearer example of the `partitionKey` value

Instead of:
```c#
public class ToDoActivity{
    public string id {get; set;}
    public string status {get; set;}
}

ToDoActivity toDoActivity = await this.container.ReadItemAsync<ToDoActivity>("id", new PartitionKey("partitionKey"));
```

Potential Suggestion:

```c#
var todoActivity = new TodoActivity("item1", "complete");
```

```c#
public class TodoActivity
{
    public string id {get; set;}
    public string status {get; set;}
}

ToDoActivity toDoActivity = await this.container.ReadItemAsync<ToDoActivity>("item1", new PartitionKey("item1"));
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78c49c42-9f71-8275-4d4c-b5c38175cf5d
* Version Independent ID: e7668b21-8894-5f28-8fbf-a029dfd82079
* Content: [Container.ReadItemAsync&lt;T&gt;(String, PartitionKey, ItemRequestOptions, CancellationToken) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.readitemasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@kharlamov We will take a look at your code and see what we can do here.

**Comment by SaurabhSharma-MSFT** [comment]
@kharlamov Why are you are trying to add a var declaration and an assignment using `var todoActivity = new TodoActivity("item1", "complete");` .
Isn't `ToDoActivity toDoActivity = await this.container.ReadItemAsync<ToDoActivity>("item1", new PartitionKey("item1"));` taking care of creating and assigning a variable ?
