### ISSUE TITLE
[BUG] WaitForCompletionAsync can throw InvalidOperationException when copy operation completed but failed

### ISSUE THREAD

**Issue by afink-osi** [Azure/azure-sdk-for-net#27516]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Describe the bug

We have an application that is responsible for copying blobs as part of backup and restore operations.  We use [WaitForCompletionAsync()](https://github.com/Azure/azure-sdk-for-net/blob/8020a5625ef576231e961acab1e442ab3b5abefa/sdk/core/Azure.Core/src/Shared/OperationPoller.cs#L69) and are seeing `System.InvalidOperationException : The operation has not completed yet.` being thrown when the copy operation fails.

WaitForCompletionAsync() periodically calls [UpdateStatusAsync()](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/storage/Azure.Storage.Blobs/src/Models/CopyFromUriOperation.cs#L155).  UpdateStatusAsync() will check if the operation completed, and if the status is not pending then will set `_hasCompleted` appropriately.  Then, it checks if the copy was successful.  If so, then `_value` is set [but if the copy was not successful, `_value` is not set](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/storage/Azure.Storage.Blobs/src/Models/CopyFromUriOperation.cs#L183).  Finally, if the task completed, `WaitForCompletionAsync()` then [tries to access the value but throws](https://github.com/Azure/azure-sdk-for-net/blob/8020a5625ef576231e961acab1e442ab3b5abefa/sdk/core/Azure.Core/src/Shared/OperationPoller.cs#L77) the `InvalidOperationException` because it is not set if the operation failed.

### Expected behavior

`InvalidOperationException` should not be thrown when the operation completes but with a failure

### Actual behavior

System.InvalidOperationException at Azure.Core.OperationHelpers.GetValue

assembly:
Azure.Storage.Blobs, Version=12.10.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxx
	
method:	
Azure.Core.OperationHelpers.GetValue
	
outerType:	
System.InvalidOperationException
	
outerMessage:	
The operation has not completed yet.

### Reproduction Steps

```
var copyInfo = await blobClient.StartCopyFromUriAsync(sourceUriBuilder.ToUri(), null, cancellationToken);
await copyInfo.WaitForCompletionAsync(pollingInterval, cancellationToken);
```

### Environment

Visual Studio 2022 Enterprise
Version 17.1.1

Windows 10.0.19042

**Comment by SaurabhSharma-MSFT** [comment]
@afink-osi I am redirecting this to respective team to investigate.

**Comment by asrivastava0308** [comment]
Hi Team, I am facing the similar issue. May i know what the correct way is to solve this problem.

**Comment by amnguye** [comment]
@seanmcc-msft @jaschrep-msft could one of you look into this?

**Comment by amnguye** [comment]
@afink-osi @asrivastava0308 

Could one of you provide logs?
https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging

This is so we can check the GetProperties call that is coming back from the service to make sure the completion status is being set to failed.

**Comment by asrivastava0308** [comment]
@afink-osi - We only have app insight enabled , So i can only provide call stack logs 

`System.InvalidOperationException:
   at Azure.Core.OperationHelpers.GetValue (Azure.Storage.Blobs, Version=12.10.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxx)
   at Azure.Storage.Blobs.Models.CopyFromUriOperation.get_Value (Azure.Storage.Blobs, Version=12.10.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxx)
   at Azure.Core.OperationHelpers+<DefaultWaitForCompletionAsync>d__6`1.MoveNext (Azure.Storage.Blobs, Version=12.10.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxx)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxx)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxx)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxx)
   at Microsoft.Docs.VideoEncoding.Shared.BlobAccessor+<CopyResource>d__38.MoveNext (Microsoft.Docs.VideoEncoding.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null: C:\__w\1\s\src\Shared\DataAccessor\BlobAccessor.cs:319)`

**Comment by amnguye** [comment]
What's the blocker from enabling client side SDK logging?

**Comment by asrivastava0308** [comment]
The response code which we got is 405 Method Not Allowed. 
`Response status code does not indicate success: 405 (Method Not Allowed)`

**Comment by amnguye** [comment]
We're going to need the x-ms-request-id (not x-ms-client-request-id) from the response from the GetProperties call. This error code does not mean necessarily that the copy failed, it means that the the resource does not support the HTTP verb being sent from the client. Which means the request itself is not allowed, or the storage service is returning the incorrect error code.
https://docs.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes

In any case we're going to need verbose logging from the SDK with details of the requests and responses that were sent by the SDK, or else we won't know what is being sent in correctly.

Again, What's the blocker from enabling client side SDK logging?

**Comment by amishra-dev** [comment]
@amnguye they are using async copy API, the customer should not be able to wait for the completion. I think we just need to give them a sample that shows how to check for progress.

**Comment by ani2** [comment]
I'm still seeing this exact same issue on Azure.Storage.Blobs, Version=12.13.0. @afink-osi Did updating to 12.12.0 fix the issue for you?
