### ISSUE TITLE
[BUG] Azure.ResourceManager.CosmosDB has no CosmosDBManagementClient

### ISSUE THREAD

**Issue by EnenDaveyBoy** [Azure/azure-sdk-for-net#27526]
### Library name and version

Azure.ResourceManager.CosmosDB 1.0.0-beta.3

### Describe the bug

this is no CosmosDBManagementClient so there is no way to perform an management operation, 

the microsoft docss say it should have

https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-vm-managed-identities-cosmos?tabs=azure-portal

while I like the ArmClient it doesn't have any option for creating databases and containers

### Expected behavior

have a client and be able to create a database and container

### Actual behavior

lack of client and unable to create database and container

### Reproduction Steps

load the sdk

### Environment

c#

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
In the new sdk there only have one armclient, and for other resource can be created under the corresponding resource collection, @archerzz please help to provide some samples according to @EnenDaveyBoy 's question

**Comment by EnenDaveyBoy** [comment]
I understand the move to the armclient,which I prefer.  However the MS docs have no knowledge of it, and there are no option for cosmos db types excelt sql so gremlin for example ismissing.

Plus the old sdk is hidden.

**Comment by CFUserForBug** [comment]
Hi, sorry for my ignorance, I'm looking for sample C# code on CosmosDBManagementClient and facing the similar issues while following the below article. Can someone pls share what need to be done here to get this piece of code running. thanks! 

https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-vm-managed-identities-cosmos?tabs=azure-portal#access-data

**Comment by EnenDaveyBoy** [comment]
you'd be better asking on stackoverflow and with a specific problem, on the tabs under the resource manager template are code samples. But you also need to know if your testing locally or in the portal and how your managing authentication which needs to be setup in addition.

(if your just just using the Db as a Db then just use the Microsoft.Azure.Cosmos;.CosmosClient, if your wanting to manage resources eg delete and create containers in code then use the Azure.ResourceManager.CosmosDB.CosmosDBManagementClient) 

There would be a lot to understand which you haven't posted and this isn't the correct place for people to be here to help you.

**Comment by CFUserForBug** [comment]
thanks for the details ! 

As I'm looking to perform CosmosDBManagementClient operations, can you please point me to the doc to get the package "Azure.ResourceManager.CosmosDB.CosmosDBManagementClient is 1.0.0-preview.1" as it's different one in nuget page. thanks in advance!

**Comment by EnenDaveyBoy** [comment]
the docs arn't upto date, there also a new version been launched a few weeks ago, but i can't figure it out.

Try posting on stackoverflow you might get luck

**Comment by CFUserForBug** [comment]
Managed to get this running. Sharing the github link (successfully tested) here in case it's helpful. 

https://github.com/CFUserForBug/cosmos/tree/main/azure-cosmos-sp/Azure-Cosmos-Management-api-Dotnet-CreateDB%26Container
