### ISSUE TITLE
[QUERY] / [BUG] 5.0 Connection String Issue

### ISSUE THREAD

**Issue by scottkuhl** [Azure/azure-sdk-for-net#27531]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage 5.0.0

### Query/Question

I started getting this on application startup on my local machine in an Azure Function app after updating the Microsoft.Azure.WebJobs.Extensions.Storage NuGet package from 4.0.5 to 5.0.0.

```
[2022-03-12T22:13:26.596Z] A host error has occurred during startup operation '9624398c-810f-4633-8140-c0e3c8764d8f'.
[2022-03-12T22:13:26.597Z] Microsoft.Azure.WebJobs.Script.WebHost: Secret initialization from Blob storage failed due to missing both an Azure Storage connection string and a SAS connection uri. For Blob Storage, please provide at least one of these. If you intend to use files for secrets, add an App Setting key 'AzureWebJobsSecretStorageType' with value 'Files'.
[2022-03-12T2
```

Rolling back the NuGet package fixes it, so I seem to have found a breaking change.
My connection string is set:

`"AzureStorage": "UseDevelopmentStorage=true"`

### Environment

IDE: 
Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.2.0 Preview 1.0

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.200 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by SaurabhSharma-MSFT** [comment]
@scottkuhl We are looking into it and get back to you for any additional information.

**Comment by SatishBoddu-MSFT** [comment]
Hello @scottkuhl Thanks for the feedback.

On Microsoft Visual Studio Enterprise 2022 (64-bit), with Azure Blob Storage triggered Function App and the Nuget Package was upgraded to 5.0.0 and the functionality was working, Could you please try updating the VS 2022 or please try on other versions? Please let us know if you need further help in this matter!

![image](https://user-images.githubusercontent.com/62923178/158326123-ba5c54d8-9e86-4dbc-8bae-dabfec766924.png)

![image](https://user-images.githubusercontent.com/62923178/158326208-5e842753-874e-4d6e-b46b-0a749490d26d.png)

![image](https://user-images.githubusercontent.com/62923178/158326354-48858e6f-e916-409d-a381-cc0eef4854d7.png)

**Comment by scottkuhl** [comment]
Have you tried changing the connection string to this:

"AzureStorage": "UseDevelopmentStorage=true"

I can only recreate the problem using that connection string used for local development.

**Comment by SatishBoddu-MSFT** [comment]
> Have you tried changing the connection string to this:
> 
> "AzureStorage": "UseDevelopmentStorage=true"
> 
> I can only recreate the problem using that connection string used for local development.


Yeah,,I tried the "AzureStorage": "UseDevelopmentStorage=true" ans started the code debug,,,

![image](https://user-images.githubusercontent.com/62923178/158703843-9ea87e19-e4a2-4d3d-9526-39028b93f95d.png)

**Comment by scottkuhl** [comment]
Ok, I will update my machine as you suggested and try again this weekend.  Thanks

Scott Kuhl
O’Fallon, Illinois, USA, Earth
________________________________

**Comment by scottkuhl** [comment]
I was able to recreate the issue on my machine and another developer machine even when downgrading to v4.  I don't think this is an issue in v5 specifically, so it is unlikely a bug introduced in the Azure SDK.  I am closing this issue and we will look into it further on our end.  Thanks for the help.
