### ISSUE TITLE
Pageable not found

### ISSUE THREAD

**Issue by sayedimac** [Azure/azure-sdk-for-net#27534]
### Library name and version

azure.data.tables and azure.core

### Query/Question

Hi - I have the following code but I am getting an error around the pageable statement. I am not sure what I am doing wrong here - looks like I have all the references, but still an error?

using System;
using Azure.Data.Tables;
using Azure.Data.Tables.Models;
using Azure.Core;

namespace tableclientcmd
{
    class Program
    {
        public static string storageUri = "";
        public static string accountName = "";
        public static string storageAccountKey = "";
        static void Main(string[] args)
        {

            var serviceClient = new TableServiceClient(
                new Uri(storageUri),
                new TableSharedKeyCredential(accountName, storageAccountKey));
            string tableName = "dotnettable";
            TableItem table = serviceClient.CreateTableIfNotExists(tableName);
            Console.WriteLine($"The created table's name is {table.Name}.");

            Pageable<TableItem> queryTableResults = serviceClient.Query(filter: $"TableName eq '{tableName}'");

I am getting a Type or Namespace not found, but if I look at documentation, it looks like I just a reference to Azure.core for pageable to work?
Would appreciate some help here... I am probably doing something silly wrong, but cannot find the solution on the internet.

### Environment

vscode

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
I am not able to reproduce this with the below code. Does it reproduce for you without the explicit Azure.Core reference? It shouldn't be required. 

csproj:
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.5.0" />
  </ItemGroup>

</Project>
```

Code:
```c#
using Azure;
using Azure.Data.Tables.Models;
using Azure.Data.Tables;

string storageUri = "";
string accountName = "";
string storageAccountKey = "";
var serviceClient = new TableServiceClient(
            new Uri(storageUri),
            new TableSharedKeyCredential(accountName, storageAccountKey));
string tableName = "dotnettable";
TableItem table = serviceClient.CreateTableIfNotExists(tableName);
Console.WriteLine($"The created table's name is {table.Name}.");

Pageable<TableItem> queryTableResults = serviceClient.Query(filter: $"TableName eq '{tableName}'");
```
