### ISSUE TITLE
[QUERY] Zero downtime Event Hub processor migration from v4 to v5

### ISSUE THREAD

**Issue by rzepinskip** [Azure/azure-sdk-for-net#27542]
### Library name and version

Azure.Messaging.EventHubs 5.6.2

### Query/Question

Is it possible to achieve zero-downtime migration of Event Hub consumers using v4 (Microsoft.Azure.EventHubs) to v5 (Azure.Messaging.EventHubs)? If not, do you have any tips on minimizing the downtime?

The breaking change in checkpoint format is a major problem in migration. Currently we have following plan:
1. Use custom `EventProcessor<TPartition>` which is able to read legacy checkpoints (in `OnInitializingPartitionAsync`).
2. The old consumers are running on side A.
3. Deploy new code to side B. Events are not consumed here since v5 SDK uses epoch value `0` and consumers are endlessly restarting due to encountering "epoch exception" [1].
4. Disconnect old consumers by stopping side A.
5. New consumers start consuming events in side B.

There is a possibility of downtime between steps 4 and 5 (depending on how fast you can stop old consumers + how fast Azure Event Hub service detects the disconnects + how fast new consumers detect the disconnects). Are there any settings in SDK or Azure portal that would allow to minimize that? 

The best option would be to pass higher epoch in v5 SDK (forcing old consumers to disconnect) but it is not possible - the `0` value is hardcoded in [EventProcessor](https://github.com/Azure/azure-sdk-for-net/blob/0f1df13425aa2488303a3867691d85301e6d1320/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L563) class.

[1] 
```
Exception Message	"Receiver 'e69d42ae-72a6-418e-be1f-4d388a390188' with a higher epoch '2' already exists. Receiver 'P1-b47177da-cf2b-46f0-8cd1-dfa007165fd9' with epoch 0 cannot be created. Make sure you are creating receiver with increasing epoch value to ensure connectivity, or ensure all old epoch receivers are closed or disconnected.
```

**Comment by jsquire** [comment]
Hi @rzepinskip.   Thank you for your feedback.   

> Is it possible to achieve zero-downtime migration of Event Hub consumers using v4 (Microsoft.Azure.EventHubs) to v5 (Azure.Messaging.EventHubs)? If not, do you have any tips on minimizing the downtime?

It's theoretically possible, but it's not a scenario that was optimized for - we would have to get a bit creative.   The thought that occurs to me is to do some spinning in the `OnInitializingPartitionAsync` method to detect the legacy processor relinquishing ownership.

- The current processor awaits `OnInitializingPartitionAsync` in the background task that is responsible for processing that partition

- Blocking in `OnInitializingPartitionAsync` should not impact the health of the processing task nor the load balancing loop  _(theoretical; this needs to be tested)_

- The legacy processor holds a blob lease for each partition that is owned

- If your code in `OnInitializingPartitionAsync` attempted to acquire the lease for the legacy blob and did not return until it was able to, that would signify that no legacy processor owned the partition. 

- Once you're able to acquire the lease, you should be able to convert the legacy checkpoint and move forward.   

- If you hold the lease for some period, then you know that no legacy processor can claim ownership.  _(theoretical; this will need to be tested)_

**Comment by jsquire** [comment]
>There is a possibility of downtime between steps 4 and 5 (depending on how fast you can stop old consumers + how fast Azure Event Hub service detects the disconnects + how fast new consumers detect the disconnects). Are there any settings in SDK or Azure portal that would allow to minimize that?

Because the legacy and current generations manage ownership differently, each processor believes that they have ownership.   Each tick of the load balancing loop will detect that the owned partitions are in a faulted state (due to losing the epoch war) and attempt to restart processing for them.  The [EventProcessorOptions.LoadBalancingInterval](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessoroptions.loadbalancingupdateinterval?view=azure-dotnet#azure-messaging-eventhubs-primitives-eventprocessoroptions-loadbalancingupdateinterval) setting controls how frequently load balancing runs.   

In v5.6.2, the default is 10 seconds.    It's important to consider that increasing the frequency of that loop will cause increased resource usage and result in more Storage requests/costs.

**Comment by jsquire** [comment]
> The best option would be to pass higher epoch in v5 SDK (forcing old consumers to disconnect) but it is not possible - the 0 value is hardcoded in [EventProcessor](https://github.com/Azure/azure-sdk-for-net/blob/0f1df13425aa2488303a3867691d85301e6d1320/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L563) class.

It is intended that the processor will yield to an `EventHubConsumerClient` or `PartitionReceiver` that was created with exclusive access.   

Even if it were possible to customize the epoch value, passing a higher epoch wouldn't solve the problem.   The legacy processor would continue to believe that it owned the partition and would fight for it, increasing its own epoch value each time it lost.

**Comment by rzepinskip** [comment]
> It's theoretically possible, but it's not a scenario that was optimized for - we would have to get a bit creative. The thought that occurs to me is to do some spinning in the OnInitializingPartitionAsync method to detect the legacy processor relinquishing ownership.

> Because the legacy and current generations manage ownership differently, each processor believes that they have ownership. Each tick of the load balancing loop will detect that the owned partitions are in a faulted state (due to losing the epoch war) and attempt to restart processing for them. The [EventProcessorOptions.LoadBalancingInterval](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.primitives.eventprocessoroptions.loadbalancingupdateinterval?view=azure-dotnet#azure-messaging-eventhubs-primitives-eventprocessoroptions-loadbalancingupdateinterval) setting controls how frequently load balancing runs.

What is the benefit of "creative" approach over "wait for load balancing"? In "creative" we do not start processing in new consumers until blob lease on partition in old consumers expires; in "wait for load balancing" we may process some events and checkpoint them in new consumer before load balancing kicks in and aborts processing due to ownership lost?

> Even if it were possible to customize the epoch value, passing a higher epoch wouldn't solve the problem. The legacy processor would continue to believe that it owned the partition and would fight for it, increasing its own epoch value each time it lost.

Unless we use very high epoch value in new consumers and disconnect old ones before they reach it through increments? (Very ugly, just want to understand more)

**Comment by jsquire** [comment]
> What is the benefit of "creative" approach over "wait for load balancing"?

Timing and resource use; if you're waiting on the blob lease, then you know exactly when it's safe to start processing that partition.   In the "wait for load balancing",  you're starting a task, the consumer is denied access, the task faults, and then you wait for the next load balancing cycle before trying again.

My understanding of your scenario is that you were attempting to minimize the delay between the old and new processor hand-off.   If you're comfortable having a window of potentially `LoadBalancingInterval * 2` in the worst case for that transition to happen, then letting load balancing naturally resolve ownership is likely a better approach.

> Unless we use very high epoch value in new consumers and disconnect old ones before they reach it through increments?

Yes, that's a true statement.   That opens the door for potential behavioral oddities in your new processor cluster that you'd have to be aware of and manage.  For example, let's assume that you set an epoch for that processor instance to some arbitrarily high number.   You never stop the processor and later you scale up by deploying a new processor instance.   If you don't configure the new instance to have the exact same epoch value, the processors could be unable to properly share work.  

Let's say that we work around that by doing something similar to the legacy processor, where we continue to increase the epoch for each attempt to claim ownership - now we end up with the potential for a zombie instance to win the battle of the higher epoch by hitting `long.MaxValue` first, blocking any other attempts to read.

Granted, these aren't scenarios that we should see when everything is working as it should, but they are redundant guards against intermittent networking and storage failures which we believe are important to harden the processor to be as resilient as possible.

**Comment by rzepinskip** [comment]
Ok, I think all clear now:
1. We should be fine with `LoadBalancingInterval * 2` (deployment-related delays easily outweigh that) and resource-usage increase is temporary(during migration) so also not a problem.
2. Exposing epoch is public interface change so requires long timeline + there may be a lot of intricacies around that we would have to consider.

Thanks for your help. Feel free to close the issue.
