### ISSUE TITLE
[Question] Low performance when using OpenReadAsync

### ISSUE THREAD

**Issue by IgorKharkv** [Azure/azure-sdk-for-net#27557]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Query/Question

My application till this day was working with local zip files, meaning I was using a direct return new FileStream() in the application and the local zip file that was located on the SDD/Network drive path (**zip files can be hundreds of GB**).

I configured the application to work with Azure Blob Storage, meaning each FileStream that was returned in now return as the Azure Blob SDK method:

 BlobClient blob = blobServiceClient.GetBlobContainerClient(containerName)
                        .GetBlobClient(blobName);
return await blob.**OpenReadAsync**().ConfigureAwait(false);

I uploaded some zip files to a container in the blob storage and set the connection string in the application to work with that storage account.

The application was deployed and running on a virtual windows machine located in the same region of the Azure Storage Blob.

Note: This is a private cloud network.

When the app is streaming the zip file on Azure blob storage it seems that the performance has decreased by at least 8-9 times (problematic with hundreds of GB).

Note: This happens when I use the SDK function **OpenReadAsync**

Speed comparison is between local C: drive on the same windows virtual machine that the application is running on an Azure Storage account which is located in the same region.

Note: NW Bandwidth - is 50 GB on the VM on azure

Solutions that I tried:

Azure blob Premium Performance storage - Didn’t improve performance
.Net Core - advantage of performance enhancements (we work with .Net framework so this is irrelevant).
Network File System (NFS) 3.0 performance considerations in Azure Blob storage - (Does not work with private cloud).
Hot, Cool, and Archive access tiers for blob data - The default is Hot so we already tried this scenario with no improvements.
Solutions I want to try:

Azure Files Share Storage as a cache solution
.Net Framework configuration - lists several quick configuration settings that you can use to make significant performance improvements
Question:

Does anyone have any suggestions on how can I optimize the streaming in front of the Azure Storage Blob?

Note: I cannot download the zips locally because they are very large, I need to stream directly to the blob storage.

### Environment

.Net Framework 4.6.2

**Comment by SaurabhSharma-MSFT** [comment]
@IgorKharkv Thanks for your feedback.  Rerouting this to respective team to look into and provide suggestions.

**Comment by amishra-dev** [comment]
Hi @IgorKharkv, 
Network upload compared to a straight disk/CPU operation is expected. To optimize to not have such a large regression might be to parallelize. Operate on each file with multiple threads using the TransferOptions and see if that help. 
You can use azcopy benchmark tool to see what is the best perf you can expect.

**Comment by seanmcc-msft** [comment]
Hi @IgorKharkv,

The default buffer size for Open Write is 4 MB, this value can be specified with the `BlobWriteOptions.BufferSize` property.  I recommend trying larger values to see if you get better performance.  16 MB might be a good value to true.
