### ISSUE TITLE
Missing class methods for VirtualMachineScaleSet and its child resources.

### ISSUE THREAD

**Issue by pareshverma91** [Azure/azure-sdk-for-net#27555]
Hi,
We were looking to consume the api https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-scale-set-vms/list using C# sdk, but the documentation at https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.virtualmachinescaleset?view=azure-dotnet fails to call out the method to invoke. It seems the documentation doesn't list any methods at all. Azure Storage's c# sdk documentation looks so much better (https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient?view=azure-dotnet) and clearly calls out methods directly. Please consider updating the Compute documentation to highlight the necessary methods correctly.

We were unable to unblock ourselves by looking at the github repo for Azure's C# sdk at https://github.com/Azure/azure-sdk-for-net/blob/0b1bdb6b57a6ffe4d4665e0a5726d15ab7d7d016/sdk/compute/Azure.ResourceManager.Compute/src/Generated/RestOperations/VirtualMachineScaleSetVMsRestOperations.cs#L667, but it would be great to have the documentation pointed out inline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3ece48b-bf59-5e31-8eb3-173674cc1420
* Version Independent ID: 2c9f4c14-62cf-7a57-c641-03e2463a13ef
* Content: [VirtualMachineScaleSet Class (Microsoft.Azure.Management.Compute.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.virtualmachinescaleset?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/VirtualMachineScaleSet.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/VirtualMachineScaleSet.xml)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@HarveyLink please check if the sdk is using the latest swagger
