### ISSUE TITLE
Unable to install Microsoft.Rest.Azure.Authentication

### ISSUE THREAD

**Issue by brunoklein99** [Azure/azure-sdk-for-net#2755]
I was following [this tutorial](https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal) and followed up with [this example](https://github.com/Azure-Samples/resource-manager-dotnet-resources-and-groups). The example required the use of `Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider`. But I am unable to install `Microsoft.Rest.Azure.Authentication` because of the following:

**Unable to find a version of 'Microsoft.Rest.ClientRuntime' that is compatible with 'Microsoft.Rest.ClientRuntime.Azure.Authentication 0.11.3 constraint: Microsoft.Rest.ClientRuntime (>= 1.3.0 && < 2.0.0)'.**.

Unfortunately, I am unable to add an older version of `Microsoft.Rest.ClientRuntime`, since the one I am currently using is required by one of my dependencies.

Is there any other way I can authenticate given my already obtained credentials? (tenantId, clientId and secret)

**Comment by brunoklein99** [comment]
My bad. I didn't realize there were preview versions of the package.

**Comment by hovsepm** [comment]
@brunoklein99 sorry we do not support ClientRuntime < 2.0.0 anymore.
