### ISSUE TITLE
[FEATURE REQ] BlobServiceClient as Bindable Input in Az Functions (or other options) to allow search by tag easy

### ISSUE THREAD

**Issue by drdamour** [Azure/azure-sdk-for-net#27571]
### Library name

Microsoft.Azure.WebJobs.Extensions.Clients

### Please describe the feature.

I would like to be able to bind a BlobServiceClient as input, but i understand it doesn't really make sense with the [Blob] attribute since it's not container specific.  Could just ignore the container param (set it to blank or null), it's the connection ones that are oh so important to me.

I want this because i want to query the service for blobs by tag...i guess if those functions were just on BlobContainerClient my issue would ALSO be solved..not sure why they only exist on BlobServiceClient..probably because the results are across the entire account.

Another option would be to let me get a BlobServiceClient from a BlobContainerClient...i know you can construct clients from left to right but right to left would help for this scenario.

**Comment by PramodValavala-MSFT** [comment]
@drdamour You can [bind to the `BlobContainerClient` class](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs#accessing-blob-container) which has the [`FindBlobsByTagsAsync` method](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.findblobsbytagsasync?view=azure-dotnet).

**Comment by drdamour** [comment]
@PramodValavala-MSFT ah yes there is, i missed i was on 12.10 and not 12.11 which it exists! sweet. thanks.

Is there any better way for me to track updates of Azure.Storage.Blobs stuff than watch the releases of this project?  there's a LOT of projects i'm not as interested in and it's hard to pick and choose what i'm after

**Comment by PramodValavala-MSFT** [comment]
@drdamour Sorry for not getting back to you on this one. I suppose the best place to keep track of changes in SDKs would be to check their respective CHANGELOG.MD file like this for the [storage binding extension](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/CHANGELOG.md).

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.
