### ISSUE TITLE
Unable to query Resources by Resource Type and Tag Name/Value

### ISSUE THREAD

**Issue by JoeBrockhaus** [Azure/azure-sdk-for-net#2757]
Using ResourceManagementClient 1.4.0-preview, but afaik this has been broken for years(!!).

for instance, I'm getting: 

> Invalid $filter 'resourceType eq 'Microsoft.Compute/virtualMachines' and tagName eq 'myTagName' and tagValue eq 'myTagValue'' specified in the query string."

I've tried passing the filter string created manually, as well as by using the lamda syntax ctor for `ODataQuery<GenericResourceFilter>(..)` but both return the same error. 

---

I'm also curious if common odata operators like `tolower()` are supported, to overcome case sensitivity issues with tag names & values (and the mysterious case-switching that sometimes occurs).

(fwiw,  `x=> x.Tagname.ToLower() == "myTagName"` results in `ToLower() eq 'myTagName'` )

**Comment by JoeBrockhaus** [comment]
In the Azure-Powershell repo, this has been noted in the past, and the fix seems to be escaping the `$filter` querystring parameter. 

https://github.com/Azure/azure-powershell/issues/1920#issuecomment-275282417

**Comment by TarasRoshko** [comment]
I also want to stress on the error message #2819

I tried to get resources by name, always get 0 results. Can you confirm this ever worked? I can't quite understand how this is even possible

**Comment by SeryioGonzalez** [comment]
Also failing

az resource list --tag --resource-type "Microsoft.Compute/virtualMachines" --tag "role=master"
Invalid $filter 'resourceType eq 'Microsoft.Compute/virtualMachines' and tagname eq 'role' and tagvalue eq 'master'' specified in the query string.

**Comment by adrianhall** [comment]
Is this still an issue?
