### ISSUE TITLE
Calling Server Outbound Calls and Direct Routing

### ISSUE THREAD

**Issue by SilvioHuckel** [Azure/azure-sdk-for-net#27585]
### Library name and version

Azure.Communication.CallingServer 1.0.0-beta.3

### Query/Question

Hello.

I am working on a telephony bot using the **Bot Framework**. The bot runs exclusively on **SBC** connectivity through **Direct Routing** (no phone numbers in the Communication Service Resource).
This works fine as the bot is triggered through inbound calls. But in one particular case, I need to make an outbound call (not a call transfer).
So I came across the **Azure.Communication.CallingServer** library and the **CreateCallConnectionAsync** method. I was wondering if this library supports **Direct Routing**.
Here is what I did:

```
var callingServerClient = new CallingServerClient("xxx");
var client = new CommunicationIdentityClient(connectionString);
var userResponse = await client.CreateUserAsync();

var createCallOption = new CreateCallOptions(
new Uri("https://xxx.ngrok.io/api/callingserver?secret=xxxx"),
       new[] { MediaType.Audio },
       new[]
       {
              EventSubscriptionType.ParticipantsUpdated,
              EventSubscriptionType.DtmfReceived
       }
)
//{
//    AlternateCallerId = new PhoneNumberIdentifier("+33xxx")   // <-- using AlternateCallerId raises error: 403 Forbidden. Not allowed to impersonate.
//}
;

var callConnection = await callingServerClient.CreateCallConnectionAsync(
       source: new CommunicationUserIdentifier(userResponse.Value.Id),
       //source: new PhoneNumberIdentifier("+33xxx"),                // <-- error: 403 Forbidden. Invlalid source identity.
       targets: new List<CommunicationIdentifier>() { new PhoneNumberIdentifier("+33xxx") }, 
       options: createCallOption
);

```

As a result, I see a **"callConnectionState":"connecting"** in the first callback request.
Immediately followed by second request with **"callConnectionState":"disconnected"**

Any assistance would be greatly appreciated
Cheers.

### Environment

- Azure.Communication.CallingServer 1.0.0-beta.3
- .NET Core 3.1
- Windows 10 Enterprise

**Comment by SaurabhSharma-MSFT** [comment]
@SilvioHuckel We are looking into it and get back to you.

**Comment by SatishBoddu-MSFT** [comment]
Hello @SilvioHuckel '

Have you referred to this documentation: [Session Border Controllers and voice routing](https://docs.microsoft.com/en-us/azure/communication-services/concepts/telephony/direct-routing-provisioning)

[List of Session Border Controllers certified for Azure Communication Services direct routing](https://docs.microsoft.com/en-us/azure/communication-services/concepts/telephony/certified-session-border-controllers)

**Comment by s1lv1o** [comment]
Hello @SatishBoddu-MSFT,
Yes I have. As mentionned, my project (which is a Bot) already works fine using **Direct Routing**. That is for inbound calls and call transfers. What I'm struggling with is outbound calls. From what I understand, **Azure.Communication.CallingServer** could be the way to go.
Thanks.

**Comment by SilvioHuckel** [comment]
> Hello @SatishBoddu-MSFT, Yes I have. As mentionned, my project (which is a Bot) already works fine using **Direct Routing**. That is for inbound calls and call transfers. What I'm struggling with is outbound calls. From what I understand, **Azure.Communication.CallingServer** could be the way to go. Thanks.

Sorry, I wasn't signed in with the correct user account.
