### ISSUE TITLE
[FormRecognizer] Add namespace imports section to samples

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#27607]
Don't forget old `FormRecognizerClient` and `FormTrainingClient` samples. Follow the pattern introduced in: https://github.com/Azure/azure-sdk-for-net/pull/27547/files

This is based on Text Analytics UX feedback we got from users having trouble to figure out which namespaces were required to run the samples.

**Comment by pallavit** [comment]
@kinelski can this issue be closed?
