### ISSUE TITLE
Add documentation for DPG Credentials

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#27612]
We have guidance for service teams regarding how to configure credentials for DPG clients in two places right now:
- https://github.com/Azure/autorest.csharp/blob/feature/v3/docs/protocol_method_client.md
- https://github.com/Azure/azure-sdk-for-net/blob/main/doc/Data%20Plane%20Code%20Generation/AzureSDKCodeGeneration_DataPlane_Quickstart.md#create-starter-package (see `-securityScope`)

Part of: https://github.com/azure/autorest.csharp/issues/1945

Let's make sure this is consolidated somewhere under: https://github.com/Azure/azure-sdk-for-net/blob/main/doc/Data%20Plane%20Code%20Generation

### Success Criteria
Service team can generate a DPG with the appropriate credentials for their service without reaching out to members of the Azure SDK team regarding which credential type to use, how to configure it to be generated, what to do if none of the types supported by the generator works for them.

- [x] The two referenced documents link to each other
- [x] Service team partners know how to choose the credential type from reading the docs
- [x] Service team partners know how to pass in authentication values like default scope from reading the docs
- [x] Service team partners know what to do if neither of the two supported authentication approaches applies to their service.

This has historically been a challenging area for library authors, so we should do our best to support them in this.

**Comment by archerzz** [comment]
close as all sub-tasks are completed.
