### ISSUE TITLE
[Flaky Test Timeout] Azure.ResourceManager.DeviceUpdate.Tests.InstanceCollectionTests(False).CreateOrUpdate()

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#27616]
### Library name

Azure.ResourceManager.DeviceUpdate

### Please describe the feature.

This test is commonly running for over 5 seconds and averages around 3. 

![image](https://user-images.githubusercontent.com/1279263/158895316-ceb9eba8-cbc8-4d71-a85f-6cadfcf5fd3a.png)

**Comment by jsquire** [comment]
//cc: @ArthurMa1978

**Comment by ArthurMa1978** [comment]
We can't repo this issue, so close this issue.
If encounter again then please file another new issue.
