### ISSUE TITLE
Make the default BaseUri https (SSL)

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/azure-sdk-for-net#2761]
https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/PowerBIEmbedded/Microsoft.Azure.Management.PowerBIEmbedded/Generated/PowerBIEmbeddedManagementClient.cs#L285

Please regenerate all clients to use https, not http

**Comment by hovsepm** [comment]
@mikeblakeuk thanks for reporting. The issue comes from swagger and should be fixed there first. https://github.com/Azure/azure-rest-api-specs/blob/master/arm-powerbiembedded/2016-01-29/swagger/powerbiembedded.json#L11

**Comment by adrianhall** [comment]
This has been fixed (even though the issue was never updated).  See https://github.com/Azure/azure-rest-api-specs/blob/master/specification/powerbiembedded/resource-manager/Microsoft.PowerBI/stable/2016-01-29/powerbiembedded.json#L9 

If this is not the case, please re-open.
