### ISSUE TITLE
[BUG] InvalidOperationException: Timeouts are not supported on this stream.

### ISSUE THREAD

**Issue by Benknightdark** [Azure/azure-sdk-for-net#27622]
### Library name and version

Azure.Storage.Files.Shares 12.9.0

### Describe the bug

I  use Azure.Storage.Files.Shares  to download file from Minial Api endpoint, But it throw the **nvalidOperationException: Timeouts are not supported on this stream.**

![image](https://user-images.githubusercontent.com/5799487/158916935-ce34f9c8-2ef9-44c2-9106-65acd04265f3.png)

### Expected behavior

I want to use Minial Api to download the Azure Storage File from the browser.

### Actual behavior

The Api doesn't download the file , but throw the **nvalidOperationException: Timeouts are not supported on this stream.**.

### Reproduction Steps

here is my project repository => https://github.com/Benknightdark/AzureFileDownloadApi

### Environment

![image](https://user-images.githubusercontent.com/5799487/158916867-533542db-fc40-43b6-99ed-a27899a8d22a.png)

**Comment by SaurabhSharma-MSFT** [comment]
@Benknightdark We are looking into it and get back to you.  Thanks.

**Comment by SatishBoddu-MSFT** [comment]
Hello @Benknightdark 

Have you referred to below code snippet? Try the below snippet from a console app and let us know if you face any issues/

[Download a File: Sample snippet ](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.files.shares-readme#download-a-file)

```
string connectionString = "<connection_string>";

// Name of the share, directory, and file we'll download from
string shareName = "sample-share";
string dirName = "sample-dir";
string fileName = "sample-file";

// Path to the save the downloaded file
string localFilePath = @"<path_to_local_file>";

// Get a reference to the file
ShareClient share = new ShareClient(connectionString, shareName);
ShareDirectoryClient directory = share.GetDirectoryClient(dirName);
ShareFileClient file = directory.GetFileClient(fileName);

// Download the file
ShareFileDownloadInfo download = file.Download();
using (FileStream stream = File.OpenWrite(localFilePath))
{
    download.Content.CopyTo(stream);
}
```

![image](https://user-images.githubusercontent.com/62923178/159199484-5e82e1ad-8327-47b9-a13f-1c056eb0242b.png)

Also please refer to : [Azure Files scalability and performance targets](https://docs.microsoft.com/en-us/azure/storage/files/storage-files-scale-targets)

**Comment by Benknightdark** [comment]
Hello @SaurabhSharma-MSFT ,
We don't need to save the file , We just need to download the file from Minal web api or MVC API endpoint from browser.
you can excute the sample code from this [repository](https://github.com/Benknightdark/AzureFileDownloadApi), and open the browser via http://localhost:5007 or https://localhost:7007

**Comment by SatishBoddu-MSFT** [comment]
Hello @Benknightdark I did use your code base and below are the suggestions!

1) Properly Manage your memory stream.
2) Make use of the Results.File as shown in the code snippet.

```
        await Task.Yield();
        var connectionString = "DefaultEndpointsProtocol=https;AccountName=tEndpointSuffix=core.windows.net";
        string shareName = "todeldir";
        string fileName = "HeloWorld.pdf";
        ShareClient share = new ShareClient(connectionString, shareName);
        ShareDirectoryClient directory = share.GetDirectoryClient("mydir");
        ShareFileClient file = directory.GetFileClient(fileName);
        ShareFileDownloadInfo download = await file.DownloadAsync();
        var stream = new MemoryStream() { Position = 0 };
        await download.Content.CopyToAsync(stream);
        MemoryStream outputStream = new MemoryStream();
        byte[] byteInfo = stream.ToArray();
        outputStream.Write(byteInfo, 0, byteInfo.Length);
        outputStream.Position = 0;

        return Results.File(outputStream, contentType: "application/pdf", fileDownloadName: fileName);
```


![image](https://user-images.githubusercontent.com/62923178/160699769-760bbe42-f298-4ad8-a77f-dfa618aa3045.png)

**Comment by Benknightdark** [comment]
Hello, @SaurabhSharma-MSFT , the code snippet that you proffered helped us to solve the problem , thansk for your help.
