### ISSUE TITLE
[BUG]  Azure.Core.dll!Azure.Response<bool>.ToString() - NullReferenceException

### ISSUE THREAD

**Issue by ayeltsov** [Azure/azure-sdk-for-net#27626]
### Library name and version

Azure.Core.dll 1.2200.22.6212

### Describe the bug

When checking for existence of non-existing blob, the Response object throw when one calls .ToString() on it:

```
// bcc is BlobContainerClient to some container
BlobClient bc = bcc.GetBlobClient("NonExistingBlob");
Response<bool>? nonExistingBlobResponse = await bc.ExistsAsync(); <-- .Value is false indicating that blob does not exist, and GetRawResponse() is null

// This will throw System.NullReferenceException: 'Object reference not set to an instance of an object.'
string s = nonExistingBlobResponse.ToString(); 
```

Disassembly shows that .ToString() makes assumption that GetRawResponse() returns non-null.

```
        public override string ToString()
        {
            return $"Status: {GetRawResponse().Status}, Value: {Value}"; // seems like simple fix - change it to GetRawResponse()?.Status 
        }
```

### Expected behavior

.ToString() does not throw

### Actual behavior

.ToString() throws

### Reproduction Steps

See description

### Environment

.NET 6.0

Microsoft Visual Studio Enterprise 2022
Version 17.1.1
VisualStudio.17.Release/17.1.1+32228.430

**Comment by SaurabhSharma-MSFT** [comment]
@ayeltsov We are looking into it and get back to you.  Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@ayeltsov Can you please try using the below code to check the existence of a blob instead of using `Response<bool>`
This will return either true or false depending on whether the blob is available or not.

```
public bool IsBlobExists(string containerName, string blobName)
{
var containerClient = this.blobServiceClient.GetBlobContainerClient(containerName);
var blobClient = containerClient.GetBlobClient(blobName);
return blobClient.Exists();
}
```

**Comment by ayeltsov** [comment]
> Can you please try using the below code

Hi, thank you @SaurabhSharma-MSFT . 
To clarify, I'm not looking for workaround in this case. Just reporting a bug with .ToString() implementation and suggesting that bug is fixed.

**Comment by SaurabhSharma-MSFT** [comment]
@ayeltsov sure. Redirecting this to services team to look into and provide a fix for the same.

**Comment by seanmcc-msft** [comment]
Hi @ayeltsov, thanks for reporting this.  I've routed this issue to Azure.Core.

**Comment by annelo-msft** [comment]
It looks like this may have been fixed in https://github.com/Azure/azure-sdk-for-net/pull/31790, but I have created https://github.com/Azure/azure-sdk-for-net/pull/37085 to address a related issue.
