### ISSUE TITLE
[FEATURE REQ] Enable Track 2 .NET CodeGen for SDK Automation in Swagger PR pipeline

### ISSUE THREAD

**Issue by lirenhe** [Azure/azure-sdk-for-net#27628]
### Library name

Swagger PR pipeline for SDK automation

### Please describe the feature.

Today, for mgmt. SDK,  the SDK automation for .NET is still using the old version of CodeGen in Swagger PR pipeline.
It would cause a lot of confusion for people who view the PR of the generated SDK. 
And we should avoid customers to use nuget that is generated by pervious version.

Please enable the latest version of .NET mgmt codeGen in SDK automation.

**Comment by fengzhou-msft** [comment]
@lirenhe can this issue be closed as we now support `azure-sdk-for-net-track2` SDK generation in swagger pipeline?

**Comment by lirenhe** [comment]
Thanks for enabling that.
