### ISSUE TITLE
Azure Germany/Management API: The subscription '[…]' could not be found

### ISSUE THREAD

**Issue by andrerav** [Azure/azure-sdk-for-net#2762]
I have created a subscription with Azure Germany, and now I am attempting to deploy my application topology there using the Azure Management API and a service principal. 

Deployment works fine towards the regular Azure cloud, however when I attempt to deploy towards my subscription in Azure Germany, I get the following error message: **The subscription '[...]' could not be found**.

I am able to successfully acquire an authentication token using `AuthenticationContext.AcquireTokenAsync()`, and I am using "https://login.microsoftonline.de/[directoryId]" as *authority* and "https://management.core.cloudapi.de/" as *resource*. Additionally, I am using "Germany Northeast" as *location/region*.

The error occurs as soon as I attempt to perform a typical management task, such as creating a resource group.

I have checked the following things:

 - App registration settings 
 - App permissions (Windows Azure Active
   Directory + Windows Azure Service Management API)
 - Correctness of
   subscription id, app id, and app secret/key

I am at a loss at what could be wrong. What could be causing this error message?

**Comment by markcowl** [comment]
You need to make sure that the subscription is in the same directory as the application you are using for authentication, that the application is authorized to use resource manager APIs, and that the application has been assigned a role that provides it access to the subscription (at leasr reader, but you probably want it to have Contributor or Owner access).

If you think that all this is the case, then getting the request/response traces for your calls would help to diagnose the issue.  You can use the Log4Net extension library: https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Log4Net/ to get Log4Net logs of the traces, or you can attach your own tracing interceptor to ServiceClientTracing here:  https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ClientRuntime/Microsoft.Rest.ClientRuntime/ServiceClientTracing.cs#L81

**Comment by shahabhijeet** [comment]
@andrerav hope our suggestion resolved your issue. Closing this issue.

**Comment by vhe1** [comment]
Found it: For some reason the ResourceManagementClient doesn't use the Environment settings of the AzureEnvironment from the AzureCredentials object it gets in the constructor.
Therefore it accesses the wrong management endpoint and doesn't find anything of course.

**Comment by lowerpuppet** [comment]
@vhe1 How did you work around that issue?  I'm running into that myself.
