### ISSUE TITLE
[Service Bus] Retry Guidance for Transactions Sample

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#27637]
Due to the way that transactions work with Service Bus, retries for service operations cannot be performed when there is an active ambient transaction. We should add a section to the [transactions sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample06_Transactions.md) that highlights this.

**Comment by jsquire** [comment]
Prerequisite:  #27931

**Comment by JoshLove-msft** [comment]
Closing as this has been added to the troubleshooting guide - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/TROUBLESHOOTING.md#operations-in-a-transaction-are-not-retried
