### ISSUE TITLE
[FEATURE REQ] Enable Azure Table Storage cross-tenant support

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-sdk-for-net#27636]
### Library name

Azure.Data.Tables

### Please describe the feature.

Customer description of issue:

We are trying to enable cross-tenant OAuth based access to customer Azure Tables from our application. As of now, to enable OAuth based Table access between cross-tenant Storage Accounts would require prior knowledge of both tenants. However, with Tenant Discovery enabled for Tables we wouldn’t need the prior tenant context and could leave that up to the SDK to resolve.

**Comment by pallavit** [comment]
@mario-guerra, @christothes is this still valid?

**Comment by mario-guerra** [comment]
@pallavit according to the email I dug up on this topic, the work was done in this PR:
https://github.com/Azure/azure-sdk-for-net/pull/28195

**Comment by pallavit** [comment]
Awesome, thank you @mario-guerra. Given your recent finding I will go ahead and close this issue. @christothes please feel free to reopen if you think this is still relevant.
