### ISSUE TITLE
[QUERY] Document how to reference blobs starting or ending with slash ('/')

### ISSUE THREAD

**Issue by ayeltsov** [Azure/azure-sdk-for-net#27638]
### Library name and version

Azure.Storage.Blobs 12.11.0

### Query/Question

The [blob naming documentation ](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata) is wishy-washy about blobs that start with or end with "/", it just says 

`Avoid blob names that end with a dot (.), a forward slash (/), or a sequence or combination of the two. No path segments should end with a dot (.).`

Examples:

```
normalblob
/avoidthis
avoidthis/
```

Current situation leaves developers in a bit of a vacuum: such blobs can and do exist, yet .NET SDK does not handle them.
I noticed that if I create blob client line this:
```
BlobClient blobClient = blobContainerClient.GetBlobClient("/avoidthis");
or
BlobClient blobClient = blobContainerClient.GetBlobClient("avoidthis/");
```

The resulting blobClient.Uri will be silently "normalized", and will point to blob without the slashes.

I'm not sure what's the best way of dealing with this. I had to work with such blobs because they were already created, so I had to manually construct URI for each of such blobs:
```
Uri adjusted = new Uri(blobContainerClient.Uri.AbsoluteUri + "/" + blobName);
BlobClient = new BlobClient(uri, storageSharedKeyCredential)  // unfortunate need to have credentials at this level
```

I personally think it's not a good idea to silently normalize the blob name. This can result in unfortunate incidents where wrong blob would be acted upon (note: listing the blobs gives their non-normalized names)

So what's the ask?

1) document what might happen with such poorly named blobs
2) change SDK behavior on poorly named blobs. I personally would love default behavior to reject such blobs (throw exception), but allow boolean override to accept blob names as is. If we do not want to change behavior, add documentation and workaround.

### Environment

.net 6

**Comment by PramodValavala-MSFT** [comment]
@ayeltsov Thanks for the feedback! Looks like the SDK, Portal, and Storage Explorer all remove slashes like you've observed. We are routing this to the concerning team to provide more insights.
