### ISSUE TITLE
How to convert Microsoft.Identity.Web to Azure.Core?

### ISSUE THREAD

**Issue by zhenlan** [Azure/azure-sdk-for-net#27642]
@v-kentro commented on [Tue Mar 15 2022](https://github.com/Azure/AppConfiguration/issues/621)

How can I use a token retrieved using the Microsoft.Identity.Web library (TokenAcquisition.GetAuthenticationResultForUserAsync) to authenticate an Azure.Data.AppConfiguration.ConfigurationClient? It seems to only accept implementations of Azure.Core.TokenCredential, but I don't see a way of creating one of the provided implementations with the data I have.

_Originally posted by @AerikAwesome in https://github.com/Azure/AppConfiguration/issues/338#issuecomment-712657628_

---

@v-kentro commented on [Tue Mar 15 2022](https://github.com/Azure/AppConfiguration/issues/621#issuecomment-1068562557)

The more general question is where to find an implementation of `TokenCredential` that uses the Microsoft identity platform.

---

@storms-lab commented on [Thu Mar 17 2022](https://github.com/Azure/AppConfiguration/issues/621#issuecomment-1071054598)

I think we are having a similar issue. We are wanting to authenticate with App Configuration as well as several other Azure services, but it is not as simple as adding another scope in our MSAL authentication flow because then we loose the ability to use the [AddAzureAppConfiguration method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.azureappconfigurationextensions.addazureappconfiguration?view=azure-dotnet#microsoft-extensions-configuration-azureappconfigurationextensions-addazureappconfiguration(microsoft-extensions-configuration-iconfigurationbuilder-system-action((microsoft-extensions-configuration-azureappconfiguration-azureappconfigurationoptions))-system-boolean)) because it doesn't take in the token type returned by MSAL. The reason we want to use AddAzureAppConfiguration is because it allows us to use [IConfiguration.Get](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.configuration.configurationbinder.get?view=dotnet-plat-ext-6.0) to handle mapping the configuration to our data class.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by v-kentro** [comment]
I think you missed the point. You just told us how to achieve similar results. We are looking for how to explicitly wire in dependencies. In a situation where somebody _already has_ MSAL credential providers, how does that person re-use the existing credential providers instead of instantiating all-new ones that duplicate the same work?

Wrapping MSAL to provide "helpful abstractions" is counter-productive in a lot of cases, because it prevents code sharing and re-use.

**Comment by christothes** [comment]
> I think you missed the point. You just told us how to achieve similar results. We are looking for how to explicitly wire in dependencies. In a situation where somebody _already has_ MSAL credential providers, how does that person re-use the existing credential providers instead of instantiating all-new ones that duplicate the same work?
> 
> Wrapping MSAL to provide "helpful abstractions" is counter-productive in a lot of cases, because it prevents code sharing and re-use.

Hi @v-kentro  - I was responding based on the issue description of wanting some guidance on how to implement `TokenCredential` when you are acquiring the token using some other mechanism. To do that one would simply wrap their current implementation with a `TokenCredential`.

If this is not what you are trying to achieve, could you clarify what problem you are trying to solve and what you feel the correct solution looks like?

**Comment by v-kentro** [comment]
This is the original question:

``` csharp
Microsoft.Identity.Web.ITokenAcquisition tokenAcquisition = ...;
Microsoft.Identity.Client.AuthenticationResult authenticationResult = await tokenAcquisition.GetAuthenticationResultForUserAsync(...);

Azure.Core.TokenCredential tokenCredential = // TODO: What goes here?
System.Uri appConfigurationEndpoint = ...;
Azure.Data.AppConfiguration.ConfigurationClient configurationClient = new(appConfigurationEndpoint, tokenCredential);
```

Alternative form:

``` csharp
Microsoft.Identity.Client.IPublicClientApplication app = ...;
Microsoft.Identity.Client.AuthenticationResult authenticationResult = await app.AcquireTokenByIntegratedWindowsAuth(...)
    .ExecuteAsync();

Azure.Core.TokenCredential tokenCredential = // TODO: What goes here?
System.Uri appConfigurationEndpoint = ...;
Azure.Data.AppConfiguration.ConfigurationClient configurationClient = new(appConfigurationEndpoint, tokenCredential);
```

We do not want "guidance on how to implement". This should already be implemented. How do we use Microsoft libraries to translate `Microsoft.Identity.Client` objects into `Azure.Core` objects?

**Comment by christothes** [comment]
Hi @v-kentro - We do not have implementations of `TokenCredential` that use the specific libraries in your example. Most developers would utilize one of our implementations that I linked to above. If you want full control over the implementation, you must implement the abstract `TokenCredential` class. Please see [this sample ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/DefiningCustomCredentialTypes.md#authenticating-with-the-confidential-client)

**Comment by v-kentro** [comment]
I am disappointed in this answer. The purpose of this issue was to request a standard vendor-supplied way to achieve commonly-needed functionality. I guess I find a response of "write it yourself" to be dismissive and a little bit insulting.

**Comment by christothes** [comment]
Hi @v-kentro I did a bit more digging and I think this may be closer to what you are looking for

https://github.com/AzureAD/microsoft-identity-web/wiki/Web-App-Samples

Particularly - 
 [Azure Storage sample](https://github.com/Azure-Samples/storage-dotnet-azure-ad-msal). See in particular the [controller](https://github.com/Azure-Samples/storage-dotnet-azure-ad-msal/blob/master/Controllers/HomeController.cs), as well as the [TokenAcquisitionTokenCredential](https://github.com/Azure-Samples/storage-dotnet-azure-ad-msal/blob/master/TokenAcquisitionTokenCredential.cs) class which adapts a ITokenAcquisition to an Azure SDK TokenCredential.
