### ISSUE TITLE
Azure SDK for .NET 4.7.2 with CSPack

### ISSUE THREAD

**Issue by UnoSD** [Azure/azure-sdk-for-net#27658]
### Library name and version

Azure SDK 2.9

### Query/Question

I have a client that is using the Azure SDK 2.9 to create `cspkg` to deploy applications to classic Cloud Services.

Their current version of the SDK only supports OS Family 4 and they would like to upgrade to enable support for 6.

They are constrained to stay on .NET 4.7.2 for now, so they may not be able to use newer libraries.

Can you please let me know where they can download the latest version of the Azure SDK compatible with .NET 4.7.2 that contains the CSPack tool? (According to the docs, the latest "legacy" SDK is 3.0 and it is compatible with 4.6 and can deploy to OS Family 6, but I'm having difficulties finding it; if a different, newer SDK is available, they are happy to migrate).

Thank you.

### Environment

.NET Framework 4.7.2

**Comment by SatishBoddu-MSFT** [comment]
Hello @UnoSD What was the documentation which you have referred?

**Comment by UnoSD** [comment]
https://docs.microsoft.com/en-us/previous-versions/azure/reference/dn479282(v=azure.100)
and
https://docs.microsoft.com/en-us/azure/cloud-services/cloud-services-guestos-update-matrix#sdk-support

**Comment by UnoSD** [comment]
Hi @SatishBoddu-MSFT ,

unfortunately the NuGet packages will not help here. They do not contain the CSPack tool and there is no package that is specific to cloud services.

However, I was able to find the response somewhere else: the CSPack tool is included in the Visual Studio installation installing the `Azure Workload`. Legacy Azure SDK installers are integrated into VS and no longer distributed independently.
