### ISSUE TITLE
Update nuget package reference from beta

### ISSUE THREAD

**Issue by phatcher** [Azure/azure-sdk-for-net#27653]
Probably should update the client library reference from 4.0.0-beta.4 to something like 4.9.0

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e236e89-a929-1c68-0dee-246b2a5b4a5f
* Version Independent ID: 99f80e40-5907-c1b4-4da2-24830f53d3ba
* Content: [Azure Event Grid client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/messaging.eventgrid-readme-pre)
* Content Source: [api/overview/azure/messaging.eventgrid-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/messaging.eventgrid-readme-pre.md)
* Service: **eventgrid**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by jsquire** [comment]
Hi @phatcher.  Thank you for your feedback.   The version of the page that you're referencing is the pre-release version _(note the -pre in the URL)_, so the package reference is correct.   The stable version of that page is available [here](https://docs.microsoft.com/dotnet/api/overview/azure/messaging.eventgrid-readme) and also appears as the [Event Grid overview](https://docs.microsoft.com/dotnet/api/overview/azure/eventgrid) and default [NuGet ReadMe](https://www.nuget.org/packages/Azure.Messaging.EventGrid/).

I don't believe there's any action needed; I'm going to mark this as addressed.  Please feel free to unresolve if you would like to continue discussing.
