### ISSUE TITLE
How to rename duplicates when they share same/similar definition

### ISSUE THREAD

**Issue by Yao725** [Azure/azure-sdk-for-net#27662]
When I go through all the duplicated items, there are a special scenario to note, where the duplicated models share same or similar definition. Furtherly, this scenario can be divided into two more specific cases, and the details are as follows.

> Mgmt. plane vs Data plane
> | Class | Mgmt. plane | Data plane |
> | :------ | :------ | :------ |
> | AccessRights | [Azure.ResourceManager.ServiceBus](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.ResourceManager.ServiceBus/src/Generated/Models/AccessRights.cs) | [Azure.Messaging.ServiceBus](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Administration/AccessRights.cs) |
> | AzureEntityResource | [Azure.ResourceManager.Storage](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.ResourceManager.Storage/src/Generated/Models/AzureEntityResource.cs) | [Azure.Analytics.Synapse.Artifacts](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/Models/AzureEntityResource.cs) |
> | LeaseState| [Azure.ResourceManager.Storage](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.ResourceManager.Storage/src/Generated/Models/LeaseState.cs) | [Azure.Storage.Blobs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/Models/LeaseState.cs) |
> | LeaseStatus| [Azure.ResourceManager.Storage](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.ResourceManager.Storage/src/Generated/Models/LeaseStatus.cs) | [Azure.Storage.Blobs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/Models/LeaseStatus.cs) |

> Azure.ResourceManager.Cosmos vs Azure.Cosmos
> | Class | SDK 1 | SDK 2 |
> | :------ | :------ | :------ |
> | IndexingMode | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/IndexingMode.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingMode.cs) |
> | CompositePath | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/CompositePath.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/CompositePath.cs) |
> | ConflictResolutionPolicy | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/ConflictResolutionPolicy.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/ConflictResolutionPolicy.cs) |
> | ConflictResolutionMode | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/ConflictResolutionMode.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/ConflictResolutionMode.cs) |
> | ExcludedPath | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/ExcludedPath.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/ExcludedPath.cs) |
> | IncludedPath | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/IncludedPath.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/IncludedPath.cs) |
> | IndexingPolicy | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/IndexingPolicy.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs) |
> | UniqueKey | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/UniqueKey.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/UniqueKey.cs) |
> | UniqueKeyPolicy | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/UniqueKeyPolicy.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/UniqueKeyPolicy.cs) |
> | CompositePathSortOrder | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/CompositePathSortOrder.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/CompositePath.cs) |
> | DataType | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/DataType.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/DataType.cs) |
> | IndexKind | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/IndexKind.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/IndexKind.cs) |
> | SpatialType | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/SpatialType.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/SpatialType.cs) |
> | TriggerOperation | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/TriggerOperation.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/TriggerOperation.cs) |
> | TriggerType | [Azure.ResourceManager.Cosmos](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/Generated/Models/TriggerType.cs) | [Azure.Cosmos](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Resource/Settings/TriggerType.cs) |
> 
> Remark: `Azure.Cosmos` should be the .net SDK that written and owned by cosmos team themselves and now it's package name has changed to `Microsoft.Azure.Cosmos`.

**Comment by Yao725** [comment]
For both of the above cases, I'd prefer to keep their names unchanged, thus ensuring the friendly consistency in use.

**Comment by ArthurMa1978** [comment]
The become mandatory step for release
