### ISSUE TITLE
[WebSites] BackupSchedule needs default values for FrequencyInterval and KeepAtLeastOneBackup properties

### ISSUE THREAD

**Issue by Nking92** [Azure/azure-sdk-for-net#2766]
The FrequencyInterval and KeepAtLeastOneBackup properties were nullable in previous versions of the WebSItes SDK, but null values are actually invalid. We need to add default values in the Swagger spec and SDK code.

**Comment by Nking92** [comment]
Opened a pull request for the Swagger update: https://github.com/Azure/azure-rest-api-specs/pull/888

**Comment by hovsepm** [comment]
Fixed in Master branch.
