### ISSUE TITLE
[BUG] Azure .net SDK is not treating resource tag value as opaque string

### ISSUE THREAD

**Issue by seromsft** [Azure/azure-sdk-for-net#27669]
### Library name and version

Microsoft.Azure.Management.Sql.dll, any version

### Describe the bug

Strings which look like timestamp (for example "2022-03-04T19:33:18.9373462Z"), when used as resource tag value, may not survive a roundtrip if Azure .net SDK is used to set tag on a resource and read it back.

Example (sorry, picture)
![image](https://user-images.githubusercontent.com/102064925/159335491-dce1f6ec-c709-433e-98fe-4940f277cecb.png)

With additional checks (checking raw content of response body) it was determined that value change occurred in the SDK after Database.GetAsync() call was done.

Property Tags is defined in the parent class TrackedResource in this way:
database resource is inherited from “TrackedResource”, where Tags are declared as follows, which is likely the reason of the described behavior.
                             [JsonProperty(PropertyName = "tags")]
                             public IDictionary<string, string> Tags
                             {
                                           get;
                                           set;
                             }

### Expected behavior

Retrieved resource should have tags values same (as string) as were previously set using update call. In the example above, value read back should be "2022-03-04T19:33:18.9373462Z".

### Actual behavior

Timestamp-like values may be reformatted on read in certain way to represent approximately same time value. Result will be different as a string.

### Reproduction Steps

using Microsoft.Azure.Management.Sql;
using System;
using System.Collections.Generic;
using Microsoft.Rest;
using Microsoft.Rest.Azure.Authentication;
using Microsoft.Azure.Management.Sql.Models;
using System.Threading;

namespace DbTags
{
    class Program
    {
        static void Main(string[] args)
        {
            SynchronizationContext.SetSynchronizationContext(new SynchronizationContext());
            ActiveDirectoryClientSettings settings = ActiveDirectoryClientSettings.UsePromptOnly("1950a258-227b-4e31-a9cf-717495945fc2", new Uri("urn:ietf:wg:oauth:2.0:oob"));
            ServiceClientCredentials cred = UserTokenProvider.LoginWithPromptAsync(settings).Result;

            string resourceGroupName = "<resource group name>";
            string serverName = "<logical server name>";
            string databaseName = "<database name>";

            using (var client = new SqlManagementClient(cred))
            {
                client.SubscriptionId = "<subscription id>";
                Database d = client.Databases.GetAsync(resourceGroupName, serverName, databaseName).Result;

                Dictionary<string, string> tags = new Dictionary<string, string>();
                tags.Add("provisionTime", "2022-03-04T19:33:18.9373462Z");

                var dbProps = new Database
                {
                    Location = d.Location,
                    Tags = tags,
                };

                client.Databases.CreateOrUpdateAsync(resourceGroupName, serverName, databaseName, dbProps).Wait();

                Database d1 = client.Databases.GetAsync(resourceGroupName, serverName, databaseName).Result;

                foreach (KeyValuePair<string, string> tag in d1.Tags)
                {
                    Console.WriteLine("{0}: {1}", tag.Key, tag.Value); // check against value set above
                }
            }
        }
    }
}

### Environment

Windows 11
.Net Framework 4.7.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ericshape** [comment]
@jsquire  this issue is filed from SQL. We need to request .NET SDK team to fix it in the platform.

**Comment by dvbb** [comment]
Due to track1 SDK has been deprecated, please use [Azure.ResourceManager.Sql](https://www.nuget.org/packages/Azure.ResourceManager.Sql) that has not occurred this issue
Sample: [Managing the ManagedDatabases](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/sqlmanagement/Azure.ResourceManager.Sql/samples/Sample2_ManagingManagedDatabases.md)
