### ISSUE TITLE
[BUG] Virtual machine images API seems to be missing

### ISSUE THREAD

**Issue by stishkin** [Azure/azure-sdk-for-net#27671]
### Library name and version

Azure.ResourceManager.Compute 1.0.0-beta.6

### Describe the bug

Virtual machine images API seems to be missing

https://docs.microsoft.com/en-us/rest/api/compute/virtual-machine-images?msclkid=135771a5a93b11ec879f70d381374990

### Expected behavior

API is not missing

### Actual behavior

API is missing

### Reproduction Steps

Attempt to get a VM image using ARM Client

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by stishkin** [comment]
I found the APIs they are located in  ArmClient().GetSubscrption(...) object
