### ISSUE TITLE
[BUG] Need to investigate tests that were able to pass based on CompareBodies bug

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#27688]
The default value of CompareBodies was inadvertently changed from `true` to `false` in https://github.com/Azure/azure-sdk-for-net/commit/96fc90ab44dc63a4194a28ba80fa12dc1616da58.

As a result, some tests have been recorded between the time that was merged and now, that no longer pass when fixing the bug.
The tests are in Key Vault, Form Recognizer, and Synapse. 
In order to prevent more broken tests from being recorded I am going to flip back the value and set CompareBodies to false in these specific libraries. This issue will track the work needed to investigate and fix the affected tests.

**Comment by JoshLove-msft** [comment]
Found while working on https://github.com/Azure/azure-sdk-for-net/pull/27687

**Comment by kinelski** [comment]
The Form Recognizer part has been fixed (https://github.com/Azure/azure-sdk-for-net/pull/28151).
