### ISSUE TITLE
[BUG] AzureCliCredential.GetToken() fails if $PATH environment variable is longer than 8191 characters

### ISSUE THREAD

**Issue by ajuch** [Azure/azure-sdk-for-net#27691]
### Library name and version

Azure.Identity 1.5.0

### Describe the bug

When the `PATH` environment variable is longer than 8191 characters, `cmd.exe` ignores it. The reason for a long PATH can be e.g. using fsi with some references (in my case 22 are sufficient). They are added to the path and make it grow quite fast. This behavior is documented [here](https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation#more-information).

Azure.Identity uses cmd.exe to launch `az` and even [provides a default value](https://github.com/Azure/azure-sdk-for-net/blob/59ff37b3bdf7c9cb59314dbe7d3c51430d2176e2/sdk/identity/Azure.Identity/src/Credentials/AzureCliCredential.cs#L70) for empty PATH. This doesn't have the expected effect in case of environment variables longer than 8191 characters. They are [passed to cmd.exe](https://github.com/Azure/azure-sdk-for-net/blob/59ff37b3bdf7c9cb59314dbe7d3c51430d2176e2/sdk/identity/Azure.Identity/src/Credentials/AzureCliCredential.cs#L175), which ignores it. I'd suggest using the default value if it's null or empty or longer than 8191 characters; as it should work for most people. Maybe a warning would be apropriate too...

### Expected behavior

A token should be returned.

### Actual behavior

Exception, see below...

### Reproduction Steps

This script triggers the bug:

``` fsharp
#r "nuget: Azure.Identity, 1.5.0"
#r "nuget: Microsoft.Rest.ClientRuntime, 2.3.23"

open Azure.Identity
open Azure.Core

let authenticateWithPath (path: string) =
    System.Environment.SetEnvironmentVariable("PATH", path)
    printfn $"Trying with a path length of {path.Length}..."
    AzureCliCredential()
        .GetToken(new TokenRequestContext([| "https://management.azure.com/.default"|]) , System.Threading.CancellationToken.None)
    |> ignore

let fillPathWithSemicolons (path: string) desiredLength =
    let nrOfSemicolons = desiredLength - path.Length
    let semicolons = String.replicate nrOfSemicolons ";"
    $"{path}+{semicolons}"

let originalPath = System.Environment.GetEnvironmentVariable("PATH")

printfn "With original path..."
authenticateWithPath originalPath

printfn "With some semicolons added..."
authenticateWithPath (fillPathWithSemicolons originalPath 8190)

printfn "With one character too much..."
authenticateWithPath (fillPathWithSemicolons originalPath 8191)
```

The output on my machine is as follows:

`Der Befehl "az" ist entweder falsch geschrieben oder konnte nicht gefunden werden.` means "command az mistyped or not found".

```
With original path...
Trying with a path length of 2108...
With some semicolons added...
Trying with a path length of 8191...
With one character too much...
Trying with a path length of 8192...
Azure.Identity.AuthenticationFailedException: Azure CLI authentication failed due to an unknown error. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/azclicredential/troubleshoot Der Befehl "az" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
   at Azure.Identity.AzureCliCredential.RequestCliAccessTokenAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.AzureCliCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.AzureCliCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Identity.AzureCliCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at FSI_0003.authenticateWithPath(String path)
   at <StartupCode$FSI_0003>.$FSI_0003.main@()
Aufgrund eines Fehlers beendet
```

### Environment

* Windows 10
* .Net Core 6.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.
