### ISSUE TITLE
Add Service Bus Performance Tests using Performance Framework

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-net#27694]
### Library name

Azure Service Bus

### Please describe the feature.

Add the performance tests for Service Bus SDK using the newly added framework support.
Key scenarios to be covered:
1. Sending Messages (Single and Batch).
2. Receiving Messages (Single and Batch).
3. Receiving Messages via Processor.

**Comment by jsquire** [comment]
Closing as a duplicate of  #20100

**Comment by JoshLove-msft** [comment]
Perf tests have already been added for Track 2 - https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus/perf/Scenarios
