### ISSUE TITLE
[BUG] The value for one of the HTTP headers is not in the correct format. x-ms-version: 2021-04-10

### ISSUE THREAD

**Issue by JoeRobich** [Azure/azure-sdk-for-net#27727]
### Library name and version

Azure.Storage.Blobs 12.11.0

### Describe the bug

Upgrading dependency from 12.10.0 to 12.11.0 to get the new implicit dependency on System.Text.Encodings.Web 4.7.2, causes failures in tests.

### Expected behavior

The requests to be successful. Especially given that 2021-04-10 is the recommended current version https://docs.microsoft.com/en-us/rest/api/storageservices/previous-azure-storage-service-versions.

### Actual behavior

```
  Error Message:
   Azure.RequestFailedException : The value for one of the HTTP headers is not in the correct format.
RequestId:19911bc0-5a01-4bef-8acc-1195c629319d
Time:2022-03-22T00:52:32.621Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Additional Information:
HeaderName: x-ms-version
HeaderValue: 2021-04-10
```

### Reproduction Steps

Code causing the failure:
```csharp
internal BlobContainerClient CreateBlobClient() => new("UseDevelopmentStorage=true", this.containerName);
```

**Comment by rossdargan** [comment]
I had the same issue. Had to revert to 12.10.0

**Comment by SaurabhSharma-MSFT** [comment]
@JoeRobich I am not able to reproduce this issue and it BlobClient is working fine while returning `2021-04-10`
![image](https://user-images.githubusercontent.com/38112130/159998964-786948be-c8bb-4395-ae6e-dc8be093f523.png)

Could you please provide more details and code snippet if possible to reproduce.
Thanks
Saurabh

**Comment by amnguye** [comment]
@rossdargan could you provide the `RequestId` like the original person did in their post?

**Comment by JoeRobich** [comment]
Thanks for investigating. Looks like they have a bug open for this problem (https://github.com/Azure/Azurite/issues/1404) and a possible fix in the works (https://github.com/Azure/Azurite/pull/1393).
