### ISSUE TITLE
[BUG] AzureCliCredential and VisualStudioCredential often times-out when run in parallel

### ISSUE THREAD

**Issue by fabicz** [Azure/azure-sdk-for-net#27722]
### Library name and version

Azure.Identity 1.5.0

### Describe the bug

I very often get `AuthenticationFailedException: Azure CLI authentication timed out` for `AzureCliCredential` and `Azure.Identity.CredentialUnavailableException: 'Process "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed to get access token in 30 seconds.'` for `VisualStudioCredential` when fetching multiple tokens at the same time.

The issue has around 90% reproducibility when 8 parallel requests are made.

### Expected behavior

When tokens are fetched in parallel, the token credential doesn't time out.

### Actual behavior

Token credential is timing out.

### Reproduction Steps

Code to reproduce:
```cs
var credential = new DefaultAzureCredential(); // using either AzureCliCredential or VisualStudioCredential

var tasks = new List<Task>();
for (int i = 0; i < 10; i++)
{
  tasks.Add(Task.Run(async () => await credential.GetTokenAsync(new TokenRequestContext(new[] { "https://vault.azure.net/.default" }))));
}
Task.WaitAll(tasks.ToArray()); // Fails here
```

when I run the same code in serial 
```cs
var credential = new DefaultAzureCredential(); // using either AzureCliCredential or VisualStudioCredential

for (int i = 0; i < 10; i++)
{
  credential.GetToken(new TokenRequestContext(new[] { "https://vault.azure.net/.default" }));
}
```
then everything works. 

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.300-preview.22154.4
 Commit:    1eb22793b6

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300-preview.22154.4\

Host (useful for support):
  Version: 6.0.2
  Commit:  839cdfb0ec

az version
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}

VS Version 17.2.0 Preview 2.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @fabicz - I think this issue is highly dependent on the environment. For example, it doesn't reproduce in my local testing of your example code. However, this is reproducible without `TokenCredential`s involved using Task.Run and cancellation tasks while running under the debugger.

Do you have a real-world scenario where you are seeing these timeouts? If so could you provide more details?

**Comment by fabicz** [comment]
> Hi @fabicz - I think this issue is highly dependent on the environment. For example, it doesn't reproduce in my local testing of your example code. 
It's definitely environment and/or user specific. I guess I'm part of the bigger tenant or have many rights. I know other people on my team not having issue with that use case. 

>However, this is reproducible without `TokenCredential`s involved using Task.Run and cancellation tasks while running under the debugger.
> Do you have a real-world scenario where you are seeing these timeouts? If so could you provide more details?
What do you mean by that? Can you share the example? `Task.Delay` in place of 1GetTokenAsync` won't take any issue. And yes this is real life scenario. We fetch during startup of our application multiple certificates and secrets from KV. I oversimplified in my example to get particular piece that's failing. 

Looking at [similar issue ](https://github.com/Azure/azure-sdk-for-net/issues/14691) I see that there is `ProcessRunner` that I dont know much about. But that might be the culprit that it locks the execution for each token request sequentially and thus if one response to get token on average takes 4s then total will be over 30s timeout interval. And on testing sequentially I can tell that the average was around 4s.

So my wild guess would be that there is something locking the parallel execution.

**Comment by fabicz** [comment]
> Here is an example I contrived just to demonstrate that with enough threads trying to execute at the same time with a time limit, timeouts are always possible

Don't understand how it relates. Because not sure how DefaultAzureCredential utilizes CancellationToken and so on. But if you are sure its related, can you write example where you have only 10 concurrent tasks, with whatever timeout, to be on par with my example? Thank you

> Are you able to reliably reproduce this if you set

What is the point of disabling Azure CLI credential if Im pointing at the issue within them? Yes setting `ExcludeAzureCliCredential` to true, will skip Azure CLI and error will turn into not auth method available:
```
DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
- ManagedIdentityCredential authentication unavailable. Multiple attempts failed to obtain a token from the managed identity endpoint.
- Process "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS001: This account 'marekn_debug@prdtrs01.prod.outlook.com' needs re-authentication. Please go to Tools->Options->Azure Services Authentication, and re-authenticate the account you want to use..
- Stored credentials not found. Need to authenticate user in VSCode Azure Account. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/vscodecredential/troubleshoot
- PowerShell is not installed.
```

**Comment by fabicz** [comment]
> Internally, this is conceptually similar to how AzureCliCredential and VisualStudioCredential are invoked as external processes.

Thanks, makes sense. 

> Sorry if I misunderstood. You mentioned the issue occurred with VisualStudioCredential also, so I was curious if it would reproduce with CLI out of the loop.

Oh ok, yep, disabling Azure CLI, while having `VisualStudioCredential` credential ready will end up with 
```
CredentialUnavailableException: Process "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed to get access token in 30 seconds.
```

> It may be that the best way to circumvent these class of issues is to make the process timeout configurable for these credentials that launch external processes.

I understand limitations behind the hood and I think this is feasible solution and its fair to make timeout configurable. Another option is to limit number of parallel invokes to get token from our code. But I was looking if there is anything better we can do about it. Timeout setting would do.

**Comment by christothes** [comment]
Timeouts are now configurable as of 1.9.0-beta.1 
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#190-beta1-2022-10-13
