### ISSUE TITLE
When using CloudBlob.DownloadRangeToByteArrayAsync (byte[] target, int index, long? blobOffset, long? length)  to download, each How many http connections are used in one call?

### ISSUE THREAD

**Issue by FisherMS** [Azure/azure-sdk-for-net#27733]
### Library name and version

Microsoft.Azure.Storage.Blob, Version=11.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

### Query/Question

When using CloudBlob.DownloadRangeToByteArrayAsync (byte[] target, int index, long? blobOffset, long? length)  to download, each How many http connections are used in one call?

### Environment

Core3.1
Ubuntu 18.4   VM(IOT device 1Core + 1G)

**Comment by SaurabhSharma-MSFT** [comment]
@Fisher-Joe We are looking into it and get back to you for any questions.

**Comment by Fisher-Joe** [comment]
![image](https://user-images.githubusercontent.com/12068896/160356233-a12adb90-9159-4e28-946f-accd7ded42ef.png)

The actual Http connections   is 6 for 3 threads, that is, 2 Http connections are used per thread.
Are these two Http connections, one is the seeking of  stream position, and the other is the download? Or are both used for download?

**Comment by navba-MSFT** [comment]
@FisherMS Apologies for the late reply. Could you please share your sample code ? 

I used the below sample code and I could see just 2 HTTP requests done to the storage account. One for FetchAttributesAsync() and one for DownloadRangeToByteArrayAsync().

```
 class Program
    {
        static async Task Main(string[] args)
        {
            // Parse the connection string for the storage account
            var storageAccount = CloudStorageAccount.Parse("MyStorageConnectionString");

            // Create a blob client
            var blobClient = storageAccount.CreateCloudBlobClient();

            // Get a reference to the blob
            var container = blobClient.GetContainerReference("MyContainer");
            var blob = container.GetBlockBlobReference("MyBlobName");

            // fetch the blob metadata properties
            await blob.FetchAttributesAsync();
            var blobLen = blob.Properties.Length;

            byte[] buffer = new byte[512 * 1024];

            // Download the range of bytes to a byte array
            var bytes = await blob.DownloadRangeToByteArrayAsync(buffer, 0, 0, buffer.Length);

            Console.WriteLine(bytes);
            Console.ReadLine();
        }
    }
```

//This code gets a reference to the specified blob in the "MyContainer" container and sets the range of bytes to download. It //then uses the DownloadRangeToByteArrayAsync method to download the range of bytes to a byte array.
//Note that this example uses the Result property to synchronously wait for the task returned by //DownloadRangeToByteArrayAsync to complete. In a production application, you may want to use asynchronous programming //patterns to avoid blocking the current thread.
