### ISSUE TITLE
Azure ResourceManager Hci Readme Issue

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#27736]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/azurestackhci/Azure.ResourceManager.Hci#contributing):
![image](https://user-images.githubusercontent.com/76771069/159632768-8249e713-c143-496f-af7f-a8d449676941.png)

Suggestion: 
1.Add Link:  https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/CONTRIBUTING.md
2.Add Link: https://opensource.microsoft.com/codeofconduct/
3.Add Link: https://opensource.microsoft.com/codeofconduct/faq/

@scottaddie and @archerzz for notification.

**Comment by Yao725** [comment]
Fixed: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/azurestackhci/Azure.ResourceManager.Hci/README.md#contributing
