### ISSUE TITLE
Azure ResourceManager DnsResolver Readme Issue

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#27735]
1.
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/Azure.ResourceManager.DnsResolver_1.0.0-beta.1/sdk/dnsresolver/Azure.ResourceManager.DnsResolver#contributing):
![image](https://user-images.githubusercontent.com/76771069/159632102-d09b3fd7-33d5-49c8-9765-6be5ff12188a.png)

Suggestion: 
1.Add Link:  https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/CONTRIBUTING.md
2.Add Link: https://opensource.microsoft.com/codeofconduct/
3.Add Link: https://opensource.microsoft.com/codeofconduct/faq/

@scottaddie and @archerzz for notification.

**Comment by ArthurMa1978** [comment]
same as https://github.com/azure/azure-sdk-for-net/issues/27736

**Comment by Yao725** [comment]
Fixed: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/dnsresolver/Azure.ResourceManager.DnsResolver/README.md#contributing
