### ISSUE TITLE
Correct way to support tokens which need a frequent refresh in a fault tolerant way

### ISSUE THREAD

**Issue by coonmoo** [Azure/azure-sdk-for-net#2773]
Hello,

I'm currently implementing a client for our REST API based on Microsoft.Rest.ClientRuntime, to support AutoRest generation.
Our API requires the client to refresh the initial acquired token every 30 minutes.

The process of refreshing the token should be transient. So the client should a) refresh when 30min passed b) refresh when the service returns an error "token expired"

My initial idea was to use a custom ServiceClientCredentials and acquire a refresh token in ProcessHttpRequestAsync. That'll work except in some cases, when the server returns "token expired".

For the RetryStrategy I have the possibility to specify IsTransient=true, when the token expired is experienced. But I have no option to make it call the ProcessHttpRequestAsync again.

How would you solve this kind of requirement?

Kind regards

**Comment by shahabhijeet** [comment]
@coonmoo we provide Microsoft.Rest.ClientRuntime.Azure.Authentication to address the same scenario you just mentioned.
http://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.Authentication/

Please let us know if this does not address your requirement. Please open a new issue and let us know the scenario under which the current package does not work.

**Comment by CreepyGnome** [comment]
@shahabhijeet Why no response? Pointing to a NuGet package doesn't tell anyone how to use that package. Where are the docs and samples for how to use it to manage the RefreshToken in a transient manner? As stated in the original message here. This should not have been closed as no solution to the issue was provided.

@Porges if you figured this out I would love to know if you found the samples or how to use the package provided for RefreshToken handling.

**Comment by OzBob** [comment]
This [aspnet sample by @pavandv](https://github.com/pavandv/DotNetExamples/tree/3f34254d5ebec499ba8bc470544c7d401f379406/Samples/WebApi/Todo) is a bit old, but he is on the aspnet team and knows what he's doing.

I found it works as a guide for using 'DelegatingHandler' pattern to solve the 'Expiry workflow problem': which I'm defining as:

1. New Client:
2. Make Api call
3. No Token set: get Token, set auth_token, set refresh_token
4. Fail with 401 (assume Auth_Token expired)
5. Get new Auth_Token with Refresh_Token
6. Fail with 401 (assume Refresh_Token expired)
7. Get new Tokens
8. Retry API call

@coonmoo does this sound like the scenario you are interested in?

**Comment by Porges** [comment]
@CreepyGnome no, I never figured this out. We ended up using the ADAL JS library to handle everything around token refresh and just use the provided tokens on the backend (with `AcquireTokenAsync`).
