### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#27746]
Core Ship Sequence (draft)
Legend:
- diamond shapes == Phase
- hexagonal shapes == Sub Step

```mermaid
flowchart TD
    A{Feature Definition} --> B{{Feature Triage}}
    B -->|Committed| SelS{{Select Shipping Sprint}}
    SelS --> AtS{{Add Issue to Sprint Plan}}
    AtS --> DI{Design and<Br/> Implementation}
    DI --> DDes{{Document Design}}
    DDes --> Cost{{Costing of Feature}}
    Cost --> DDec{{Document Decisions}}
    DDec --> AP{Approval Phase}
    AP --> Arch{{Arch Board}}
    Arch --> DocCh{{Document any Changes}}
    DocCh --> ApplyFB{{Apply Feedback}}
    ApplyFB --> Merge{{Merge to Main}}
    Merge --> FinalApp{{Final APIView Approval}}
    FinalApp --> RP{Release Phase}
    RP --> Ship{{Ship Package}}
    Ship --> Refs{{Fixup Core References}}
    Refs --> Clear{{Dependent Clients<Br/> Ready to Ship}}

    B -->|Won't Do| E{{Issue Closed}}

    B -->|Deferred| D{{Add to Backlog}}
    D --> FC{{Future Consideration}}
    FC -.-> B
```

**Comment by annelo-msft** [comment]
How is document design different from document decisions?
![image](https://user-images.githubusercontent.com/21269347/160887193-19238b56-b80a-4044-98e8-dc17942ac818.png)

**Comment by annelo-msft** [comment]
Does "Document any Changes" mean write down what changes the arch board recommends/requires?

![image](https://user-images.githubusercontent.com/21269347/160887389-bdfa809d-92c2-418b-ae29-bc37fdb6f9bf.png)

**Comment by annelo-msft** [comment]
We probably want an arrow back from API approval to making a new PR and merging to main, since this part almost always results in additional work.

![image](https://user-images.githubusercontent.com/21269347/160887646-e440a8a2-2a8e-49ad-a08d-723979cc55c4.png)

**Comment by annelo-msft** [comment]
We're working with @AlexGhiondea on an approach to DPG where there is never a project reference to Core from DPG clients -- they can only ever depend on a released version of Azure.Core.  Would we want to take the same approach for existing HLCs?  If so, the "Fixup Core References" and "Dependent Clients Ready to Ship" steps would go away.  If not, I'd be interested in understanding how HLC (Gen 1 HLC) and DPG differ in this case, because I think it will be interesting as we consider how DPGs evolve into Gen 2 HLCs.

![image](https://user-images.githubusercontent.com/21269347/160887930-faa2bab6-0119-469c-8c46-c833d4081938.png)

**Comment by christothes** [comment]
> How is document design different from document decisions? 
Design == initial design 
Decisions == Changes along the way

**Comment by christothes** [comment]
> Is "Arch Board" the monthly Arch Board Meeting for Azure.Core? Might make sense to add "meeting" to clarify, because sometimes this is done over email. 

Fair, I'll add that

> Does "Document any Changes" mean write down what changes the arch board recommends/requires?

👍

**Comment by christothes** [comment]
> We probably want an arrow back from API approval to making a new PR and merging to main, since this part almost always results in additional work.
> 

The intent was for this "Final APIView Approval" to be the one that is purely a formality after all reviews and iterations are complete. Essentially clicking the approve button.

**Comment by annelo-msft** [comment]
How do we decide amongst the Azure.Core team who will own which features from the perspective of:
- Design
- Development
- PR approval
- API approval
- Other?

?

**Comment by christothes** [comment]
> How do we decide amongst the Azure.Core team who will own which features from the perspective of:
> 
> * Design
> * Development
> * PR approval
> * API approval
> * Other?
> 
> ?

Good question, but I'd consider that beyond the scope of this document.

**Comment by christothes** [comment]
Moving this to #27853
