### ISSUE TITLE
CosmosDB SqlRoleAssignment

### ISSUE THREAD

**Issue by repne** [Azure/azure-sdk-for-net#27743]
### Library name and version

Azure.ResourceManager.CosmosDB

### Describe the bug

It is not currently possible to configure SQL Role Assignments using the SDK. 

[This issue](https://github.com/Azure/azure-rest-api-specs/issues/16560), which is currently closed, is mentioned in the source code in [commented out tests](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/tests/ScenarioTests/SqlRoleAssignmentTests.cs#L13) and in the [autorest file](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cosmosdb/Azure.ResourceManager.CosmosDB/src/autorest.md?plain=1#L299).

### Expected behavior

The RBAC functionality of CosmosDB is exposed through the SDK.

### Actual behavior

The generation has been commented out pending an issue, which is now closed.

### Reproduction Steps

-

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by archerzz** [comment]
@repne Thanks for your feedback. We'll enable this API in the coming release.

**Comment by archerzz** [comment]
Role assignment API has been added, waiting for release which hopefully can come in 1 or 2 weeks.

**Comment by repne** [comment]
Thanks for this, looking forward to it!

**Comment by archerzz** [comment]
@repne Sorry for the late response. The RBAC API should have been added quite long time ago. Check the latest version: https://www.nuget.org/packages/Azure.ResourceManager.CosmosDB/1.3.0

Here is the corresponding docs: https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.cosmosdb.cosmosdbsqlroleassignmentresource?view=azure-dotnet

Thanks.
