### ISSUE TITLE
[Metrics Advisor]GetAllFeedbackAsync failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#27751]
Metrics Advisor nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 404 (Not Found)
> 
> Content:
> {"code":"NotFound","message":null}
> 
> Headers:
> X-Request-ID: a3ebd6a7-3384-42ad-bb7e-1841cb89655a
> x-envoy-upstream-service-time: 1178
> apim-request-id: a3ebd6a7-3384-42ad-bb7e-1841cb89655a
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Thu, 24 Mar 2022 12:51:31 GMT
> Content-Length: 34
> Content-Type: application/json; charset=utf-8
> 
> 
> Stack trace
>    at Azure.AI.MetricsAdvisor.MicrosoftAzureMetricsAdvisorRestAPIOpenAPIV2RestClient.ListMetricFeedbacksAsync(MetricFeedbackFilter body, Nullable`1 skip, Nullable`1 maxpagesize, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/Generated/MicrosoftAzureMetricsAdvisorRestAPIOpenAPIV2RestClient.cs:line 2144
>    at Azure.AI.MetricsAdvisor.MetricsAdvisorClient.<>c__DisplayClass15_0.<<GetAllFeedbackAsync>g__FirstPageFunc|0>d.MoveNext() in /Users/runner/work/1/s/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/src/MetricsAdvisorClient.cs:line 576
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() in /_/microsoft.azure.autorest.csharp/3.0.0-beta.20220322.3/content/Generator.Shared/PageableHelpers.cs:line 187
>    at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core/src/AsyncPageable.cs:line 103
>    at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core/src/AsyncPageable.cs:line 103
>    at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Azure.AI.MetricsAdvisor.Samples.MetricsAdvisorSamples.GetAllFeedbackAsync() in /Users/runner/work/1/s/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/Samples/Sample11_FeedbackCrudOperations.cs:line 122
>    at Azure.AI.MetricsAdvisor.Samples.MetricsAdvisorSamples.GetAllFeedbackAsync() in /Users/runner/work/1/s/sdk/metricsadvisor/Azure.AI.MetricsAdvisor/tests/Samples/Sample11_FeedbackCrudOperations.cs:line 122
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1457881&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Given the age of this issue, I'm going to close it as stale.  If tests continue to fail, please file a new issue.
