### ISSUE TITLE
Run Recorded Tests against Azure?

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-sdk-for-net#2776]
What are the explicit goals of the recorded tests? Are they to ensure that the SDK makes the exact same HTTP traffic, or is it to test some sort of functionality of the deployed services?

If it's the former, I guess we can stop reading and close this out.

If it's the latter, then I feel like there is a slight gap here. The tests that are run automatically are not validating that the Swagger is right. They're not validating that the SDK operates correctly. They're only validating that the SDK network traffic is the same as the last time someone recorded the tests.

So what does it mean if the playback tests match the recorded tests.... but those same tests fail when run against a live Azure instance? (this is happening with the Compute SDK as far as I can tell for a subset of tests)

**Comment by markcowl** [comment]
So, what youre describing would seem like a P0 service issue.  The API-Version is a contract, if the pattern  of calls change without a change in API-Version, that is a P0 service bug.

If the API-Version does change, then tests need to be re-recorded, and the playback system is explicitly designed to require forcing re-recording of tests when the api-version changes.

**Comment by colemickens** [comment]
Okay, thanks.
