### ISSUE TITLE
Add Token Caching Support for Managed Identity

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#27778]
**Intro**
When application developers use the developer SDKs and libraries provided by Azure to build apps that run on Azure, they expect built-in support for common and repeatable tasks. From Azure’s perspective, adding support to common patterns helps increase the resilience of the apps running on Azure.  Managed Identity token caching is a common task that’s currently missing in the Azure Identity client libraries. The Azure Identity libraries are used by all Track 2 Azure SDKs to support the use of [Managed Identities for Azure resources](https://aka.ms/azuremanagedidentity). This is causing each developer to add their own code for token caching.  

What is token caching? When a client receives a token from Azure AD, it’s highly recommended to cache the token to improve app resilience by avoiding repeated token requests to Azure AD. In user authentication flows, a cached [refresh token](https://docs.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens) allows the client code to silently request new access tokens without causing the users to be prompted for authentication. In an app-only flow, a refresh token isn’t involved, and an access token is issued. Client code must cache the access tokens for the same reasons. 

The Azure Identity client library has implemented detection and support for multiple Azure resource providers.  It provides an abstraction _DefaultAzureCredential_ and _ManagedIdentityCredential_ classes so that developers can write consistent code that does not need to change based on the resource provider used.

**Feature**
Collaborate with the MSAL team to design, prototype, and then productize a solution across MSAL and Azure Identity SDKs to provide _ManagedIdentity_ token caching support at the MSAL/SDK layer so that applications can be resilient and performant with managed identity token caching and automatic cache refreshes.

Related:
- https://github.com/Azure/azure-sdk-for-net/issues/18938

**Comment by Licantrop0** [comment]
For reference, this is the code I use to cache the token on Windows from an `InteractiveBrowserCredential` auth method:

```
private const string _tokenPath = "authToken.bin";
private readonly string[] _scopes = { "Directory.Read.All" };

private InteractiveBrowserCredential GetBrowserCredential(string clientId)
{
    var credentialOptions = new InteractiveBrowserCredentialOptions
    {
        ClientId = clientId,
        TokenCachePersistenceOptions = new TokenCachePersistenceOptions() { UnsafeAllowUnencryptedStorage = true }
    };

    if (!File.Exists(_tokenPath))
    {
        // this code path happens on first execution
        var browserCredential = new InteractiveBrowserCredential(credentialOptions);
        var tokenRequestContext = new TokenRequestContext(_scopes);
        var authRecord = browserCredential.Authenticate(tokenRequestContext);
        using var authRecordStream = File.OpenWrite(_tokenPath);
        authRecord.Serialize(authRecordStream);
        return browserCredential;
    }
    else
    {
        // this code path happens on following executions
        using var authRecordStream = File.OpenRead(_tokenPath);
        var authRecord = AuthenticationRecord.Deserialize(authRecordStream);
        credentialOptions.AuthenticationRecord = authRecord;
        return new InteractiveBrowserCredential(credentialOptions);
    }
}
```

I would really love to have this implemented out-of-the-box.

**Comment by yogilad** [comment]
Hi, 

We have a Kusto customer who's hitting Service Fabric 429 throttle errors when attempting to acquire a managed identity token.
The Kusto library uses ManagedIdentityCredential under the hood.

Is there a plan to add a built in Cache to the class, or create a wrapper class which caches results in the near future?

**Comment by scottaddie** [comment]
Fixed via https://github.com/Azure/azure-sdk-for-net/pull/30432. Token caching for the `ManagedIdentityCredential` shipped in this week's v1.7.0-beta.1 release of the _Azure.Identity_ package. Please give it a try, and leave your feedback here.

**Comment by scottaddie** [comment]
This feature will ship in October's GA release of the Azure Identity library. Please open a GitHub issue if you experience any problems with the feature.

**Comment by afscrome** [comment]
@scottaddie  Has this been released, or is it coming in October?  The blog post at https://devblogs.microsoft.com/azure-sdk/azure-sdk-release-august-2022/ suggests this has already been released.

**Comment by fowl2** [comment]
@afscrome [Azure.Identity 1.7.0-beta.1 on nuget.org](https://www.nuget.org/packages/Azure.Identity/1.7.0-beta.1) includes this according to the [changelog](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#170-beta1-2022-08-09).

**Comment by scottaddie** [comment]
**UPDATE**: The GA of this feature has slipped to November's 1.8.0 release.

**Comment by scottaddie** [comment]
@afscrome The 1.8.0 GA release shipped today. Give it a try and let me know if you have any questions.
