### ISSUE TITLE
Add Windows Web Account Manager (WAM) Brokered Authentication Support

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#27779]
This is a tracking work item for creating/finishing the new Azure.Identity.BrokeredAuthentication client library (separate package from the existing Azure Identity client library).

Related:
- https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity.BrokeredAuthentication/README.md

Dependencies:
- MSAL WAM is supported (Beta) in .NET and Python today
- MSAL WAM support (Beta) for Java and Javascript is not yet available but is expected to be available in time for this scheduled development milestone.

**Comment by maisarissi** [comment]
Hey folks. Just saw this was moved from 2022-08 to 2022-09 milestone. We are pending this work to get WAM support in the Graph PowerShell SDK.
Can we get an ETA for this to be available for us?
