### ISSUE TITLE
Incorrectly HTML encoded text in the description of this property

### ISSUE THREAD

**Issue by DavidHomerOxford** [Azure/azure-sdk-for-net#27782]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 134deede-600a-05a1-07a3-861652c44284
* Version Independent ID: ae907bbd-e90c-7846-3f32-8bbacef5f03c
* Content: [Site.Enabled Property (Microsoft.Azure.Management.WebSites.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.site.enabled?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.WebSites.Models/Site.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/Site.xml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ArthurMa1978** [comment]
This is ref doc which auto-gen by docs team
