### ISSUE TITLE
Add first class support for sharing HttpClients in AutoRest-generated client

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2779]
### Description
Since HttpClient is a fairly heavyweight artifact, many customers will want to create an HttpClient once and share it across their AutoRest and other clients.

Provide a new constructor that allows passing in an HttpClient and the corresponding pointers into the delegating handler stack.  Ensure that no changes are made to the HttpClient after this is done.

This will likely mean adding new constrctor that takes an HttpClient and using this constructor in the existing constructors for ServiceClient.  This will also require changing the current default initialization path, which calls ```InitializeHttpClient``` into a factory for the default HttpClient, which the other constructors can pass into the new constructor as a default value.

i.e
```c#
public HttpClient CreateDefaultHttpClient(ClientHandler rootHandler, params DelegatingHandler[] handlers)


```

The new constructor should look like this:

```c#
public ServiceClient(HttpClient client)
```

Note that InitializeHttpClient will need to remain to avoid a breakign change, however, this method should be refactored to use the new CreateDefaultHttpClient method.

- [ ] Refactor the client as specified
- [ ] Add tests to verify using HttpClients for real calls across multiple clients
- [ ] Update documentation to include the new constructor

### Cost: 4

**Comment by markcowl** [comment]
Fixed.

**Comment by groege** [comment]
Any idea when this fix will be available with VS2017?
It's not only a heavyweight artifact --> If I try to make a request with a second instance of HttpClient (even if I dispose of the first one), i run into an exception - so I'm actually forced to use only one instance...
Thanks!

**Comment by abatishchev** [comment]
@markcowl hi, you said this is fixed but I don't see HttpClient at https://github.com/Azure/autorest.csharp/blob/master/src/vanilla/Templates/Rest/Client/ServiceClientBodyTemplate.cshtml
How can I reuse an instance of HttpClient now days?

**Comment by abatishchev** [comment]
@markcowl so was this done, and was then where the source code was changed?

**Comment by abatishchev** [comment]
hi @markcowl, please take a look

**Comment by abatishchev** [comment]
hi @markcowl, please take a look

**Comment by abatishchev** [comment]
hi @markcowl, please take a look
