### ISSUE TITLE
[QUERY] Error: "404 The specified queue does not exist" after upgrade

### ISSUE THREAD

**Issue by lisamariet** [Azure/azure-sdk-for-net#27792]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage.Queues 5.0.0

### Query/Question

After upgrading from version 4.0.4 to 5.0.0 it seems that perhaps the QueueTrigger outputs an exception if it does not find the queue? 
I am not sure what exactly is reporting not finding queue, but can't think of anything else but the QueueTriggers. There was no coding change and the error comes in the output console window when doing func start. 

It is true that this queue does not exist in this environment, nor do we want it to. But now these error our outputed continously n the console output, making impossible to see anything else in the console output. So how can we stop that?

Example:
<img width="991" alt="image" src="https://user-images.githubusercontent.com/5948299/160390584-b0087acc-1bd7-468c-afad-616567b4f56a.png">

We have log level set to INFORMATION on local development... so I am guess it has something to do with this? How to set log level to ERROR for only 'Microsoft.Azure.WebJobs.Extensions.Storage.Queues' ?

### Environment

Azure Function v3 on .net core 3.1
Windows 10 pro
Visual Studio Code v1.65.2

**Comment by SaurabhSharma-MSFT** [comment]
@lisamariet We are looking into it and get back to you for any additional information.

**Comment by lisamariet** [comment]
So I manged to turn it off by setting up logging like this: 
```
"logging": {
    "logLevel": {
      "default": "Information",
      "Azure": "Error"
    }
  },
```

**Comment by SatishBoddu-MSFT** [comment]
Hello @lisamariet Thanks for reaching out on this query!
Yes, we can control the level of verbosity from the host.json file settings related to 'Logging'

[host.json reference for Azure Functions 2.x and later](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#:~:text=6%2C%0A%20%20%20%20%20%20%20%20%22counterThreshold%22%3A%200.80%0A%20%20%20%20%7D%2C%0A%20%20%20%20%22-,logging,-%22%3A%20%7B%0A%20%20%20%20%20%20%20%20%22fileLoggingMode%22%3A%20%22debugOnly%22%2C%0A%20%20%20%20%20%20%20%20%22logLevel)

Please let us know if you need further help in this matter and if we can close this issue? Happy to help further!

**Comment by lisamariet** [comment]
Yes, but I do think that you should change the logging to only appear on verbose... and not on debug. As it clutters the Azure Functions output to much it is impossible to see anyting else in the output window. It did not use to be there. It only started logging once we upgraded.

**Comment by SatishBoddu-MSFT** [comment]
Hello @lisamariet Thanks for the feedback!

For any further ideas to improve the product features, please log your ideas on this portal!
https://feedback.azure.com/d365community/search/?q=function+app

![image](https://user-images.githubusercontent.com/62923178/163654304-8bf8e887-f1d9-488d-bffe-ef2cdd8eebfb.png)

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
