### ISSUE TITLE
Add sample for using Monitor Query library's visualization data in graph

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-net#27807]
### Library name

Azure.Monitor.Query

### Please describe the feature.

Customers need guidance on how to use the visualization JSON with a graphing library (D3.js, Kendo UI, etc.). Add a code sample that shows how to accomplish this. Related comment: https://github.com/Azure/azure-sdk-for-net/issues/27286#issuecomment-1068575952

**Comment by pallavit** [comment]
@nisha-bhatia this may be a good idea to finish during MQ.
