### ISSUE TITLE
Can you include some small, standalone code samples?  

### ISSUE THREAD

**Issue by rfernand2** [Azure/azure-sdk-for-net#27809]
[Enter feedback here]

The API often doesn't work as one expects and we have to guess at different approaches to get them to work.  A few small working python code samples would go a long way here.  
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e750387f-720c-4aab-f628-de36ad7af62c
* Version Independent ID: 5b2a3206-3840-a4a5-6b22-7bbd50bf04e6
* Content: [InteractiveBrowserCredential Class (Azure.Identity) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.interactivebrowsercredential?view=azure-dotnet)
* Content Source: [xml/Azure.Identity/InteractiveBrowserCredential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Identity/InteractiveBrowserCredential.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @rfernand2  - Do you have any specific scenarios for which you'd like to see more samples? Just in case you haven't seen them, we have a few [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md) .

**Comment by rfernand2** [comment]
Hi @christothes.  I spent a considerable amount of time trying to get this API call to correctly cache my credentials across subsequent runs of my app.  I think this could have been avoided if the doc page had a runnable code sample. 

I waiting until today to respond to your request for suggestions here; I understand this API better now, thanks to working with @xiangyan99.  I recommend him for verification of technical facts involved below.
  
I'd like to suggest several things that could make [this page](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.interactivebrowsercredential?view=azure-python) more useful to readers:

1. Add an example of importing the class right under the page title (it would be be great if you could do this for all SDK Class pages):
```
from azure.identity import InteractiveBrowserCredential
```
This saves the user from having to do a additional web search just to find how to import the class.

2. fix "<xref:azure.identity.get_token>" that currently shows in 2nd line of page. 

3. In the first paragraph, you mention "with the authorization code flow".  I imagine that there are many users/developers (like myself) who don't know what this is.  Can you provide a hyperlink for this term that leads to a definition?

4. In the same paragraph: "PKCE (Proof Key for Code Exchange) internally to protect the code." I'm not sure but this might be too much information for someone wanting to understand the API itself, but if you are going to include it, please use a hyperlink for this also.

5. On each parameter in the Parameters section, can you indicate if the parameter is required or optional?  I know in this case, they all seem to be optional, but this would be great best practice for the API docs.  And in the case where it is optional, can you list, in a standard format, the default value and/or action.  I see this for some of the parameters, but not all of them, and they are in different formats.

6. "authentication_record".  Can you include text here to explain that this must be specified, along with a value for the "cache_persistence_options" if Azure is going to cache credentials across multiple runs of the app.  I suggest explaining its purpose as providing the context for the caching, so that Azure can select the correct cached credential for the user.

7. "cache_persistence_options" - this should also cross-reference "authentication_record".

8. Include a runnable code sample for the simple use of this API:
```
# simple_creds_test.py: test out ability to use authenticate user in Browser (without credential caching)
from azure.identity import InteractiveBrowserCredential

credential = InteractiveBrowserCredential()

# prove the credential is valid
scope = "https://management.core.windows.net/.default"
token = credential.get_token(scope)
print(token)
```
9. Include a runnable code sample that shows how an app can enable credential caching over subsequent app runs by serializing the authentication context (which contains no secrets), enabling Azure to cache the credentials on its behalf:
```
# creds_cache_test.py: test out ability to use cached creds to avoid authenticating on every run
import os
from azure.identity import InteractiveBrowserCredential, AuthenticationRecord, TokenCachePersistenceOptions 

# actual credential caching is handling by azure, but our app must supply the authentication record 
# which identifies the tentant_id, username, etc.
fn = "cred_cache.txt"
deserialized_record = None

if os.path.exists(fn):
    # read serialized authentication_record from local file
    with open(fn, "rt") as infile:
        cred_json = infile.read()
        deserialized_record = AuthenticationRecord.deserialize(cred_json)

cpo = TokenCachePersistenceOptions()
credential = InteractiveBrowserCredential(cache_persistence_options=cpo,
    authentication_record=deserialized_record)

if not os.path.exists(fn):
    # serialize authentication_record to local file
    record = credential.authenticate()
    cred_json = record.serialize()

    with open(fn, "wt") as outfile:
        outfile.write(cred_json)

# prove the credential is valid
scope = "https://management.core.windows.net/.default"
token = credential.get_token(scope)
print(token)
```
10. Include the [link you specified above](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md) as the first topic in the "Recommended content".  This is a great resource!

11. Lastly, as a catch-all for issues that fall outside of the formal description of the API, include a FAQ that helps users resolve common problems.  Here is my suggestion for this topic:

**Frequently Asked Questions about using this API**
    a. I am supplying the recommended parameters (authentication_record and cache_persistence_options, but my app keeps going thru the browser authentication every time it is run.
    **Answer**: This API does not validate parameter names, so misspelled parameters names will not be flagged as an error.  Check your spelling of each name

   b. Once I have created a InteractiveBrowserCredential object, how can I use it to access Azure resources?
   **Answer**: See this page for details of using an Authentication object to access resources: <some URL that shows this>

   c. I want to use this on an app that sometimes runs on computers without browsers.  How can I authenticate the user in these situations?
   **Answer**: Your app can detect if it is running on a "headless" system and, in that case, it can use the alternative [DeviceCodeCredential ](https://docs.microsoft.com/en-us/python/api/azure-identity/azure.identity.devicecodecredential?view=azure-python) class to authenticate the user.

**Comment by pallavit** [comment]
@christothes is this still valid?
