### ISSUE TITLE
[QUERY] Does the Azure SDK currently support retrieving network interfaces for VMSSVMs

### ISSUE THREAD

**Issue by DizzyDeveloper** [Azure/azure-sdk-for-net#27811]
### Library name and version

Azure.ResourceManager.Compute/1.0.0-beta.5

### Query/Question

Hi hopefully simply question.
Does the Azure SDK support the route defined on this page.

[NetworkInterface In VMSS - List Virtual Machine Scale Set VM Network Interfaces](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/network-interface-in-vm-ss/list-virtual-machine-scale-set-vm-network-interfaces#networkinterfaceipconfiguration)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by archerzz** [comment]
@DizzyDeveloper We don't support it in `Azure.ResourceManager.Compute` or `Azure.ResourceManager.Network` yet. We're investigating how to support that API.

**Comment by DizzyDeveloper** [comment]
Hi @archerzz,
Thanks mate, I figured it wasn't supported yet, but thought I might just check. I have rolled by own that works for me in my case that I can just make use of until support get adds at some stage future. Thanks :)
