### ISSUE TITLE
TableClient.CreateIfNotExists should not return null

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#27821]
### Library name

Azure.Data.Tables

### Please describe the feature.

Currently CreateIfNotExists returns null when the table already exists. This causes a NullReferenceException when an implict cast is attempted by Response<T>.

related to #25434

**Comment by Trapulo** [comment]
How can I know if a table has been created or not?

And all documentation still reports that "If the table does not already exist, a Response<T>. If the table already exists, null." !
https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclient.createifnotexistsasync?view=azure-dotnet
