### ISSUE TITLE
[Test Framework] Add live tests for Test Proxy integration

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#27834]
We should have "live" tests for the Test Framework that validate Test Proxy usage. We should exercise all of the different sanitization/matching options.

**Comment by pallavit** [comment]
@JoshLove-msft do we have any testing at all against the test proxy?

What scenarios do you have in mind here?

**Comment by pallavit** [comment]
@JoshLove-msft given we have migrated all our service test cases to test proxy - do you still see value in doing this? If anything were to be amiss we would be testing it through our service testcases.

**Comment by JoshLove-msft** [comment]
Agreed that there isn't much value in this at this point.
