### ISSUE TITLE
FetchAttributes usage not well defined in doc

### ISSUE THREAD

**Issue by kganesan1** [Azure/azure-sdk-for-net#27837]
This page document should explain what exceptions are thrown and how to catch exception to determine if blob does not exist (404). 
Also, this involves a network call. If someone wants to fetch blob and etag (property), the alternate methods should be referenced in this doc (DownloadToStreamAsync - that page doc also has issues). I want to fetch blob with etag so that I can update conditionally. FetchAttributes followed by download blob does not guarantee etag is still same. I can use access condition with etag fetched to ensure that I get blob with that etag. If etag changed, I have to start all over again. These complexities are hard to handle without proper documentation and hints.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 99c274d1-8571-8c6a-d467-7240d9bb4b6e
* Version Independent ID: 88fc1b7f-a79d-be39-250c-607bb58672d9
* Content: [CloudBlob.FetchAttributesAsync Method (Microsoft.Azure.Storage.Blob) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblob.fetchattributesasync?view=azure-dotnet-legacy)
* Content Source: [xml/Microsoft.Azure.Storage.Blob/CloudBlob.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.Blob/CloudBlob.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@kganesan1 Thanks for your feedback. I am redirecting this to respective team to look into this and update the document accordingly.

**Comment by seanmcc-msft** [comment]
Unfortunately, that version of the SDK was deprecated in 2020 and is no longer supported - https://github.com/Azure/azure-storage-net/blob/master/README.md 

We highly recommend upgrading to Azure.Storage.Blobs v12.x, which is a different NuGet package.

Here is our migration guide - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md
