### ISSUE TITLE
[FEATURE REQ] Container Groups - Support for setting managed identity in ImageRegistryCredential

### ISSUE THREAD

**Issue by LeMaciek** [Azure/azure-sdk-for-net#27846]
### Library name

Microsoft.Azure.Management.ContainerInstance.Fluent

### Please describe the feature.

Current azure rest api (2021-09-01) supports creation with imageRegistryCredentials with manged identities (property: identity) see: https://docs.microsoft.com/en-us/rest/api/container-instances/container-groups/create-or-update#imageregistrycredential. However it's not possible with Microsoft.Azure.Management.ContainerInstance.Fluent version 1.38.0. 
It would be nice to have this possibility...

**Comment by HarveyLink** [comment]
@LeMaciek Thank you for reaching us.
Current Fluent SDK doesn't support creation with imageRegistryCredentials with manged identities (property: identity). 
Add @weidongxu-microsoft for confirmation.
But we do have .NET Track1 SDK suppoort for this function, please check: [Microsoft.Azure.Management.ContainerInstance](https://www.nuget.org/packages/Microsoft.Azure.Management.ContainerInstance/)

**Comment by weidongxu-microsoft** [comment]
.NET Fluent SDK is in maintenance mode and no new feature will be added.

Please check track2 SDK here https://aka.ms/azsdk/dotnet/mgmt

**Comment by LeMaciek** [comment]
Hi, thanks for your response, I was expecting more or less this answer...

1. @HarveyLink doing it without the fluent api would require a rewrite just for this... I've managed to inject the credentials with identity, but then the fluent version is using the old apiversion... so, it failed in the end.... No mangedidentity for me for this moment.
2. @weidongxu-microsoft I know there is new sdk coming but there is nothing about one for the container instances... and moreover, according to this:
https://azure.github.io/azure-sdk/releases/latest/all/dotnet.html
![image](https://user-images.githubusercontent.com/1091052/164717347-cc4d72bb-5009-4456-81b9-2033b6d1799a.png)
Library is in active support, so new features should be added... According to this:
https://azure.github.io/azure-sdk/policies_support.html
![image](https://user-images.githubusercontent.com/1091052/164718797-a846e673-aa7c-425d-8916-4cc20d86772b.png)

The newest version of Microsoft.Azure.Management.ContainerInstance.Fluent uses api version: "2018-10-01" when communicating with container group azure rest api, whereas the current is 2021-09-01, so it's seems like it's at least in deprected mode since September...

**Comment by weidongxu-microsoft** [comment]
@xboxeer for estimated release of new SDK on Azure container instance (ACI).

@LeMaciek 
2018-10-01 is stable api-version and hence it will not be deprecated any time soon.

If you are interested, you can use `azure.GenereicResources.define(...)...create()` to do this. (basically it sends a request at your specified api-version and request body)
Example https://github.com/Azure/azure-libraries-for-net/blob/master/Tests/Fluent.Tests/ResourceManager/GenericResourcesTests.cs#L34-L42

ARM template via `azure.Deployments` should work as well.
