### ISSUE TITLE
[BUG] Azure.Storage.Blob throws exception: Calculated MD5 does not match existing property

### ISSUE THREAD

**Issue by Krusty93** [Azure/azure-sdk-for-net#27847]
### Library name and version

Microsoft.Azure.Storage.Blob 11.1.7

### Describe the bug

We are facing an unexpected issue in production where a service and a function app work together.
To keep the scenario simplest as possible, a web service running on AKS exposes a REST API that uploads some documents to Azure Storage as blobs. Then, a function app is triggered through the service bus and downloads the documents previously uploaded by the service.

However, in the last month we found a lot of failures (100 out of 2300 successfully runs) in the function app logs like this:
`Calculated MD5 does not match existing property`

The code is quite straightforward:
Service running on Azure.Storage.Blobs 12.8.1:
```csharp
foreach (...)
{
    var cloudBlobContainer = _blobServiceClient.GetBlobContainerClient(containerName);
    await cloudBlobContainer.CreateIfNotExistsAsync();
    var destBlob = cloudBlobContainer.GetBlobClient(blobName);
    await destBlob.StartCopyFromUriAsync(sourceUri);
}
```

Function app running on Microsoft.Azure.WebJobs.Extensions.Storage 4.0.3 (that internally refers to Microsoft.Azure.Storage.Blob 11.1.7)
```csharp
// function code
public static async Task<Message> Run(..)
{
    var blobHelper = BlobStorageHelper.Create(<connection string and stuff>);
    
    foreach (CloudBlockBlob blob in blobHelper.GetBlobsFromFolder(path))
    {
       byte[] templateContents = await blobHelper.DownloadBlobBytesAsync(documentBlob);
       ...
    }
}

// BlobStorageHelper
public class BlobStorageHelper
{
    private readonly CloudBlobContainer _container;
    
    public BlobStorageHelper(CloudBlobContainer container, ILogger logger)
    {
        _container = container;
        _logger = logger;
    }
    
    public static BlobStorageHelper Create(string connectionString, string containerName, ILogger logger)
    {
        var account = CloudStorageAccount.Parse(connectionString);
        var blobContainer = account.CreateCloudBlobClient().GetContainerReference(containerName);    
        if (!blobContainer.Exists())
            blobContainer.Create();
    
        return new BlobStorageHelper(blobContainer, logger);
    }
    
    public async Task<byte[]> DownloadBlobBytesAsync(CloudBlockBlob blob)
    {
        await blob.FetchAttributesAsync();
        long fileByteLength = blob.Properties.Length;
        Byte[] contents = new Byte[fileByteLength];
        await blob.DownloadToByteArrayAsync(contents, 0);
        return contents;
    }
}
```

We checked that blob files had been uploaded properly to the storage and we haven't found any issue with them. Content-MD5 property is set correctly as well according to the Azure Portal.

I understand that upgrading the function NuGet package would be the safest thing to do, but unfortunately there are a lot of breaking changes and we need a hotfix right now. We don't plan to deliver the new SDK in the next couple of months at least.

Meanwhile, we are introducing more logging to better understand if for some reason the Content-MD5 property is set to null before or after `await blob.FetchAttributesAsync();`. As soon as we have more info, I will keep you up to date

### Expected behavior

We expect that the following code does not throw any exception
```csharp
byte[] contents = new byte[fileByteLength];
await blob.DownloadToByteArrayAsync(contents, 0); 
```

### Actual behavior

The following code throws an exception 'Calculated MD5 does not match existing property'
```csharp
await blob.FetchAttributesAsync();
long fileByteLength = blob.Properties.Length;
Byte[] contents = new Byte[fileByteLength];
await blob.DownloadToByteArrayAsync(contents, 0);
return contents;
```

### Reproduction Steps

We couldn't reproduce the bug on purpose, even stressing the service. We just found it in the FunctionApp logs.

### Environment

Service is on AKS.
FunctionApp is hosted on Windows, v3.
Both of them are running on Net Core 3.1.

Just for sake, here the list of Azure packages used by the FunctionApp:
```xml
<PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.1.0" />
<PackageReference Include="Microsoft.Azure.Cosmos" Version="3.23.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.2.0" />
<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.3" />
<PackageReference Include="Microsoft.Data.SqlClient" Version="2.1.1" />
<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
```

**Comment by SaurabhSharma-MSFT** [comment]
@Krusty93 `Microsoft.Azure.Storage.Blob` is a deprecated package. 
![image](https://user-images.githubusercontent.com/38112130/161160797-4552c598-0551-4735-9786-640f633b4a95.png)
Can you please try with the latest package?  Also, you could refer to similar issue discussed over [here ](url)with the workaround if this helps to resolve your issue.

**Comment by Krusty93** [comment]
As explained above, it's hard to upgrade from v11 to v12 in a production environment in a hurry, due to a lot of breaking SDK changes.

However, we understood that sometimes the document copy between different storage accounts (both SKU standard in the same region, the premium is not available as GRS) takes more than 20 seconds, so when the function app is triggered it downloads an empty file where the MD5 is obviously wrong.

Then, my question is if it is ok that the copy takes that long for documents under 30kb? To work around this, we switched from `StartCopyFromUriAsync` to `SyncCopyFromUriAsync` API to be sure that the copy completes **in a reasonable time (e.g. less than 20 seconds)** before returning the result to the client. Is it a good assertion to do?

**Comment by amnguye** [comment]
This is a Storage Related Query regarding Copy SLA, not about the SDK.
We cannot document storage service SLA in the Storage SDK.

For general storage issues please open up a support ticket
https://azure.microsoft.com/en-us/support/create-ticket/
For other queries
https://techcommunity.microsoft.com/

Also the customer is using the v11 deprecated version, which all queries should be in the deprecated repo
https://github.com/Azure/azure-storage-net/issues

Thanks. Closing the issue.
