### ISSUE TITLE
Recurring ResponseDelay warnings from Azure.Core

### ISSUE THREAD

**Issue by andyhammar** [Azure/azure-sdk-for-net#27842]
### Library name and version

azurefunctions: 4.1.3.17473

### Describe the bug

When our system is under load we get high response times for Azure SDK requests and with that ResponseDelay warnings.
Is this a problem or just expected from the high number of requests and it being the internet?
It's a bit worrying when e.g. acquire a lease, write a checkpoint has longer delays.

We have a function app, heavy use of event-hub and durable functions/entities.

Thanks! 

Some logs statistics from the past 2 days, most requests are fast - but a smaller set are slow.
![image](https://user-images.githubusercontent.com/1713268/160798578-b5e996f3-46ab-4264-9c75-e52fbd9d9aac.png)

Here's an example:
![image](https://user-images.githubusercontent.com/1713268/160800719-6326e3b9-ac51-4da9-8d26-4c5d8b247d79.png)

### Expected behavior

To not get warnings for expected behaviour

### Actual behavior

Daily warning that we're unsure if we need to act upon or not

### Reproduction Steps

-

### Environment

An EP3 function app, with scale-out to 10 instances

**Comment by jsquire** [comment]
Hi @andyhammar.   Thank you for the additional context.  If you're not seeing logs with the error or warning category, there isn't anything failing that would require critical remediation on your part.  However, the lag in those responses certainly does reflect potential performance concerns.    

Purely from the Event Hubs perspective, I don't see anything that would be actionable on your part.  Normally when a processor bogs down, it is because it is responsible for too many partitions and the thread pool is contented.  In this case, you've got a small number of partitions and plenty of cores for them with an EP3.

Unfortunately, the logs that you're hooking are emitted by Azure.Core, which underpins most libraries in the Azure SDK.   Outside of Event Hubs, are there any Azure SDK client libraries that your application is using directly, or is it safe to assume that these slow requests are all related to Storage?

**Comment by andyhammar** [comment]
Hi again @jsquire . But that's the thing, the sevLevel "2" that's highlighted with the red rectangle is a warning, and it causing our prod alert system to fire.

That warning is sent from here: https://github.com/Azure/azure-sdk-for-net/blob/4c2daf356a3745a7cae5cea97a6dea8ad9e91067/sdk/core/Azure.Core/src/Pipeline/Internal/LoggingPolicy.cs#L125
And sent when a response has taken more than 3s

**Comment by jsquire** [comment]
Understood; our best bet is going to be to pull in the team that owns the particular SDK that is the main source of those messages to help troubleshoot.   To do that, I'll need to know, outside of Event Hubs, are there any Azure SDK client libraries that your application is using directly, or is it safe to assume that these slow requests are all related to Storage?

**Comment by andyhammar** [comment]
Ok thanks @jsquire. I'd like to answer yes, mostly related to Storage.
Check this out.
We are using both DataLake and CosmosDb from this function app. Looking at some stats.

Looking at all outgoing requests from "Azure.Core", the majority is for blob storage:
![image](https://user-images.githubusercontent.com/1713268/161001884-5f162f71-b73f-4122-9aa3-a4eaa01bc476.png)

Filtering on the slow responses only (>3s), Blob accounts for roughly 10x as many as DataLake:

![image](https://user-images.githubusercontent.com/1713268/161002094-5a6c37fb-d10b-4ec2-b4a2-6165e70ed103.png)

So factoring in the number of requests, looks like Blob and DataLake have about as many slow request ratio - 1 in 10k
Not too bad IMO, but the DataLake I'd expect to be slow from time to time, but the built-in checkpoint/lease requests for Storage are harder to say - is it a symptom of a real problem?

Thanks!

**Comment by jsquire** [comment]
> the built-in checkpoint/lease requests for Storage are harder to say - is it a symptom of a real problem?

That is my question as well.   The Event Hubs processor is very chatty with Blob Storage and makes frequent calls.  If the delays were impacting the processor's health, it would begin to emit warnings, so we know that impact is performance-related there.   

However, I can't speak to the larger question of "is this a normal pattern for Storage under load or is this a symptom."   For that, we'll need insight from the Storage team.   I'm going to transfer this to their attention and keep monitoring.

**Comment by navba-MSFT** [comment]
@andyhammar Apologies for the late reply. Could you please let me know if you are still facing this issue related to the high latency from Azure Storage? 

If Yes, Could you please check in the Storage metrics if the latency is from the Server latency / E2e Latency ?

![image](https://user-images.githubusercontent.com/57353862/167601099-12fff855-6c09-4041-8c85-134858d67182.png)

You can further isolate the latency based on the operations by selecting the **Transactions** metric and Applying the Splitting based on the **Response Type** as shown below:

![image](https://user-images.githubusercontent.com/57353862/167601763-83f86257-147d-4230-83c0-aef060a2bf77.png)

This will help us identify the latency trend for any Storage operations.

I am sharing the performance and scalability [checklist article](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist) for Blob storage and the [article to design ](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-latency)your blob storage for low latency.

If you have any questions on this, please get back to me. I would be happy to help.

**Comment by andyhammar** [comment]
Thanks @navba-MSFT 

I haven't gone through all the link information yet, but here are some metrics from the account.
Anything obvious?
Is it expected that **Server** Max latency has the same (and as high) spikes as E2E?

Server vs E2E Latency looks like this - AVG:
![image](https://user-images.githubusercontent.com/1713268/168007845-cf0fcb72-d8a7-4e95-b2ab-86ed5e6959e4.png)

Same, but MAX shows that both of the metrics sometimes go to the >15s, and when they do it's both of them.
![image](https://user-images.githubusercontent.com/1713268/168007759-e794c1d0-cf75-4115-90b8-ba25a46e9ad3.png)

MAX Server Latency by operation name looks like this:
![image](https://user-images.githubusercontent.com/1713268/168008051-547d83fc-3d3a-4adb-8a21-91f562b70026.png)

**Comment by navba-MSFT** [comment]
@andyhammar Thanks for getting back. Focusing on the average value would make more sense than the max. Sharing the below to give you an idea of what those 2 metrics mean:

E2ELatency (duration): The total time in milliseconds taken to complete a request in the Windows Azure Storage Service. This value includes the required processing time within Windows Azure Storage to read the request, send the response, and receive acknowledgement of the response.

Server Latency (duration): The total processing time in milliseconds taken by the Windows Azure Storage Service to process a request. This value does not include the network latency specified in E2E Latency.

Looking at the above screenshot, I see the average latency metrics is less than 10 milli seconds. 

If you want to check the details about the Max Latency, then you can check the corresponding API Name in the last screenshot that resulted in the latency and check if that is related to your issue.

Sharing the performance and scalability [checklist article](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist) for Blob storage and the [article to design ](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blobs-latency)your blob storage for low latency again if that helps.
