### ISSUE TITLE
Add `NullableResponse<T>` that `Response<T>` inherits from

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#27852]
`Response<T>` requires that `T Value` is not null.  When we want to work around that and return a `Response<T>` with no `Value` _(like conditional requests that return 3XX, batching requests that haven't been sent to the service yet, DPG errors that were classified as success, ...)_ we usually `throw` when accessed.  See [NoBodyResponse](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Shared/NoBodyResponseOfT.cs) and [ErrorResponse](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/ErrorResponse.cs) as examples.

While that _technically_ meets the contract for `Response<T>`, it doesn't match the spirit of it.  We'd like to introduce a `NullableResponse<T>` that we can start using for this case.  To avoid a bifurcated response hierarchy, we'd like to make the existing `Response<T>` inherit from it.  Here's a rough example of what the API might look like:

```C#
public abstract class NullableResponse<T> {
    public abstract bool HasValue { get; }
    public abstract T Value { get;  }
    public abstract Response GetRawResponse() {}
}
 
public abstract class Response<T> : NullableResponse<T> {
     [EditorBrowsable(EditorBrowsableState.Never)]
     public override bool HasValue => true;
     public static implicit operator T(Response<T> response)
}
```

We also want to evaluate whether DPG protocol methods (and anything accepting `RequestContext`) should return this `NullableResponse<T>` instead of regular `Response<T>`.

**Comment by annelo-msft** [comment]
> We also want to evaluate whether DPG protocol methods (and anything accepting `RequestContext`) should return this `NullableResponse<T>` instead of regular `Response<T>`.

DPG protocol methods only return `Response,` not `Response<T>`.  It is the responsibility of the protocol method caller if they pass a response classifier saying errors are acceptable to check `Response` for errors in order to return a value that correctly matches the Convenience API return type without throwing an exception.

**Comment by annelo-msft** [comment]
Per offline conversation, this isn't required for DPG GA.  We'll address it once we start adding the `Get<Resource>IfExists` methods to the management plane (after v1 GA) or to DPG.

**Comment by christothes** [comment]
Note: This could affect any extensions to Response<T>
guidelines 
  - use nullableResponse<T> when mainline scenario may not return a value
  - ETag scenarios : it depends
