### ISSUE TITLE
[QUERY] Using the Azure C# SDK - How can I query the organizations AzureDevOps Nuget Artifact Feed?

### ISSUE THREAD

**Issue by jeffward01** [Azure/azure-sdk-for-net#27866]
### Library name and version

Microsoft.VisualStudio.Services.Client

### Query/Question

Hello,

My question is regarding the C# Azure DevOps SDK.  I am unsure of which 'Library' I am referring to, and this is my question.

I see many tutorials and documentations online on how to query the Artifact Feed: https://docs.microsoft.com/en-us/rest/api/azure/devops/artifacts/feed-management/create-feed?view=azure-devops-rest-6.0 

My goal is to use the C# SDK to query Azure Artifact feed details, delete artifacts, and get meta-data information about the artifacts.

Specifically, I am looking for a list of 'Versions' that I can query (see last screenshot).

Here is a screenshot from the UI of what I am looking for:

![image](https://user-images.githubusercontent.com/12589359/160970760-c73b9f12-8046-4c4a-8f4a-ef9e718847a5.png)

![image](https://user-images.githubusercontent.com/12589359/160970804-3ce841d6-777b-4f9e-9443-c355d6c3fa16.png)

![image](https://user-images.githubusercontent.com/12589359/160970845-b7643464-78d4-4d0d-8f8b-e153759b75c4.png)

-----

I know that this is possible using the Azure REST API and manual HTTP requests.

My question is, how can I accomplish this using one of the C# SDK Libraries found here:  https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops

### Environment

Windows 10, net 6.0 VS2022

**Comment by jsquire** [comment]
Hi @jeffward01.   Thank you for reaching out and we regret that you're experiencing difficulties.   Unfortunately, the Azure DevOps libraries are not maintained in this repository and do not appear to have a public repository where we can transfer this to help you find assistance.

There are a couple of options mentioned on the [Azure DevOps Support](https://azure.microsoft.com/support/devops/) page, the most expedient one being to [open a support request in the Azure Portal](https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/overview).  I'm sorry that we're not able to help you find an answer.

I'm going to close this out, but if I've misunderstood or you'd like to continue the discussion, please feel free to unresolve.
