### ISSUE TITLE
[Question] How to throttle upload bandwidth for blob storage?

### ISSUE THREAD

**Issue by NJ261** [Azure/azure-sdk-for-net#27863]
### Library name and version

Azure.Storage.Blob 11.2.3

### Query/Question

I have this code to upload the files to blob storage. When multiple file uploads are going on, it occupies the whole bandwidth and leaves nothing for the remaining applications. I was wondering how can we throttle the bandwidth here. Is there an inbuilt option here in the SDK? Appreciate your help. Thanks!

```cs
var cloudBlobClient = CreateBlobClient(connectionString);
var cloudBlobContainer = cloudBlobClient.GetContainerReference(container);
var cloudBlockBlob = cloudBlobContainer.GetBlockBlobReference(filename);

await cloudBlockBlob.UploadFromFileAsync(localFilename, null, options, null, progressHandler, cancellationToken);
```

### Environment

Azure.Storage.Blob - 11.2.3
Azure.Storage.Common - 11.2.3

**Comment by SaurabhSharma-MSFT** [comment]
@NJ261 We are looking into it and get back to you.  Thanks.

**Comment by SatishBoddu-MSFT** [comment]
Hello @NJ261 

Please refer to this documentation and the sample code snippet to [Upload large amounts of random data in parallel to Azure storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-scalable-app-upload-files?tabs=dotnet11#run-the-application)

  // Define the BlobRequestOptions on the upload.
        // This includes defining an exponential retry policy to ensure that failed connections
        // are retried with a back off policy. As multiple large files are being uploaded using
        // large block sizes, this can cause an issue if an exponential retry policy is not defined.
        // Additionally, parallel operations are enabled with a thread count of 8.
        // This should be a multiple of the number of processor cores in the machine.
        // Lastly, MD5 hash validation is disabled for this example, improving the upload speed.

```
 // Iterate through the files
        foreach (string path in Directory.GetFiles(uploadPath))
        {
            var container = containers[count % 5];
            string fileName = Path.GetFileName(path);
            Console.WriteLine("Uploading {0} to container {1}", path, container.Name);
            CloudBlockBlob blockBlob = container.GetBlockBlobReference(fileName);

            // Set the block size to 100MB.
            blockBlob.StreamWriteSizeInBytes = 100 * 1024 * 1024;

            await sem.WaitAsync();

            // Create a task for each file to upload. The tasks are
            // added to a collection and all run asynchronously.
            tasks.Add(blockBlob.UploadFromFileAsync(path, null, options, null).ContinueWith((t) =>
            {
                sem.Release();
                Interlocked.Increment(ref completed_count);
            }));

            count++;
        }

        // Run all the tasks asynchronously.
        await Task.WhenAll(tasks);
```

We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
