### ISSUE TITLE
DefaultAzureCredential: How to know which credential was used internally?

### ISSUE THREAD

**Issue by martijnvanschie** [Azure/azure-sdk-for-net#27872]
### Library name and version

Azure.Identity 1.6.0-beta.1

### Query/Question

I love the flexibility of `DefaultAzureCredential`. I use it in many applications, for instance to support different credentials for my local debugging, during workflows or in production without the need for code changes or a factory pattern.

So i know that the `DefaultAzureCredential` sequentially calls `GetToken()` on all the included credentials. The order is clearly specified in the documentation.

My use case was that is got different behavior for my xUnit test running from the command line or from VS Test Explorer. It turned out the command line used the `AzureCliCredential` and the Test Explorer used the `VisualStudioCredential`. 

It took me a while to figure this out and if i could log this in my code that would have helped a lot.

So I was wondering how i can verify which credential was actually used for the token by `DefaultAzureCredential`. This could be informative and for instance used in debug logging.

Regards,
Martijn

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.103 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by martijnvanschie** [comment]
Thanx @christothes ... those settings should do the job...

And I learned about ChainedTokenCredential which could be handy 😀

**Comment by martijnvanschie** [comment]
So i tried the logging today and i does print out the authentication flow in order so this is informative. Although it is also very excessive information so i would not use this besides debugging.

I was also looking onto below option as reported on the referred page but i cannot find the `IsAccountIdentifierLoggingEnabled` on the Diagnostics property, and also not in the documentation.

```csharp
DefaultAzureCredentialOptions options = new DefaultAzureCredentialOptions
{
    Diagnostics =
    {
        LoggedHeaderNames = { "x-ms-request-id" },
        LoggedQueryParameters = { "api-version" },
        IsAccountIdentifierLoggingEnabled = true 
    }
};
```
/unresolved

**Comment by martijnvanschie** [comment]
Oke, did some more reading and found a customization option for logging. I tried this and that seems to be a viable option for me :). This cleans up the logs a bit so i get only the relevant information from the identity logging.

Below is an example if someone finds this useful.

```csharp
using AzureEventSourceListener listener = new AzureEventSourceListener((e, message) =>
{
    if (e.EventSource.Name == "Azure-Identity")
    {
        logger.LogInformation(message);
    }
},
System.Diagnostics.Tracing.EventLevel.LogAlways);
```

Source:
https://docs.microsoft.com/en-us/dotnet/azure/sdk/logging#configure-custom-logging

**Comment by martijnvanschie** [comment]
Oke, thanks for informing me. I'll check out the next release when it comes out.
Closing this issue as my questions have been addressed.
