### ISSUE TITLE
[Service Bus Extension] Support binding to ServiceBusReceivedMessage and POCO in the same function

### ISSUE THREAD

**Issue by VanessaRussell** [Azure/azure-sdk-for-net#27926]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.3.0

### Query/Question

I have code that was written using Microsoft.Azure.WebJobs.Extensions.ServiceBus v4.3.0 that was dead lettering the message if it didn't pass validation:
``` csharp
    internal sealed class ProcessEventFunction
    {
        private readonly MyEventValidator eventValidator;

        public ProcessEventFunction(MyEventValidator? eventValidator)
        {
            this.eventValidator = eventValidator ?? throw new ArgumentNullException(nameof(eventValidator));
        }

        [Disable("DisableFunctions")]
        [FunctionName(nameof(ProcessEventAsync))]
        public Task ProcessEventAsync(
            [ServiceBusTrigger("%EventTopicName%", "%SubscriptionName%", Connection = "ServiceBusConnection")]
                MyEvent myEvent,
            MessageReceiver messageReceiver, 
            string lockToken
        )
        {
                    ValidationResult validationResult = eventValidator.Validate(myEvent);

                    if (!validationResult.IsValid)
                    {
                        await messageReceiver.DeadLetterAsync(lockToken);
                        return;
                    }

                    // Process event
        }
    }
```
Note the use of the strongly typed message.

I am struggling to figure out how to migrate this to v5.3.0 while also still using strongly typed messages.

As #26564 rightly points out, there is currently nothing in the migration document that mentions sending messages to the Dead Letter Queue.

I did manage to find the [Message Settlement section](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus#message-settlement) within the package's readme file.  Unfortunately, the mentioned ServiceBusMessageActions DeadLetterMessageAsync() method seems to only take a ServiceBusReceivedMessage and not a strongly typed message.

Can you please provide guidance on how to send a strongly typed message to the Dead Letter Queue using the v5.3.0 package?

### Environment

Win64 Azure Function using .NET 6 in process model
Visual Studio 17.1.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
> I did manage to find the [Message Settlement section](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus#message-settlement) within the package's readme file. Unfortunately, the mentioned ServiceBusMessageActions DeadLetterMessageAsync() method seems to only take a ServiceBusReceivedMessage and not a strongly typed message.

Can you clarify what you mean by the method not taking a strongly typed message? ServiceBusReceivedMessage is the strongly typed message that the Service Bus library exposes.

**Comment by VanessaRussell** [comment]
> Can you clarify what you mean by the method not taking a strongly typed message? ServiceBusReceivedMessage is the strongly typed message that the Service Bus library exposes.

In the sample code I provided, I am binding directly to `MyEvent` instead of working with `ServiceBusReceivedMessage` and manually deserializing its body into an instance of `MyEvent`.  As such, I don't have an instance of `ServiceBusReceivedMessage` to pass into the `DeadLetterMessageAsync` method.  I only have the `MyEvent` instance.

**Comment by JoshLove-msft** [comment]
> > Can you clarify what you mean by the method not taking a strongly typed message? ServiceBusReceivedMessage is the strongly typed message that the Service Bus library exposes.
> 
> In the sample code I provided, I am binding directly to `MyEvent` instead of working with `ServiceBusReceivedMessage` and manually deserializing its body into an instance of `MyEvent`. As such, I don't have an instance of `ServiceBusReceivedMessage` to pass into the `DeadLetterMessageAsync` method. I only have the `MyEvent` instance.

I see, in that case you would need to bind to the `ServiceBusReceivedMessage` as well instead of binding to the lockToken string.

**Comment by VanessaRussell** [comment]
Hmmz, I tried that but I'm receiving this error message:

[2022-04-01T22:03:52.006Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'GenerateEmailsAsync'.
Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'message' to type ServiceBusReceivedMessage. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).


This is my function definition:
``` csharp
    [Disable("DisableFunctions")]
    [FunctionName(nameof(GenerateEmailsAsync))]
    public Task GenerateEmailsAsync(
        [ServiceBusTrigger("%TopicName%", "%SubscriptionName%", Connection = "ServiceBusConnection")]
            StatusChangeEvent statusChangeEvent,
        [ServiceBus("%SendEmailTopicName%", Connection = "ServiceBusConnection", EntityType = ServiceBusEntityType.Topic)]
            IAsyncCollector<SendEmailEvent> topicCollector,
        ServiceBusReceivedMessage message,
        ServiceBusMessageActions messageActions,
        CancellationToken cancellationToken
    )
    {
        return cancellationToken.IsCancellationRequested
            ? Task.FromCanceled(cancellationToken)
            : ProcessEventAsync(
                statusChangeEvent,
                () => InvalidateEventAsync(message, messageActions),
                (statusChangeEvent, requestTelemetry) => GenerateEmailAsync(statusChangeEvent, requestTelemetry, topicCollector)
            );
    }
```

**Comment by JoshLove-msft** [comment]
The parameter needs to go after the ServiceBusTrigger attribute. Right now it is after the ServiceBus attribute so it is getting associated with the wrong one.

**Comment by VanessaRussell** [comment]
I tried that but now the error message is for my strongly typed Message record:

2022-04-04T17:11:22.736Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'GenerateRSCEmailsAsync'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'statusChangeEvent' to type StatusChangeEvent. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

This makes me believe that you can only input bind to one message class per function.  As such, my original question stands as I want to bind to my `StatusChangeEvent` class and not the sdk's `ServiceBusReceivedMessage` class.

How do I keep using my `StatusChangeEvent` class as the message class while still being able to dead letter it on demand in v5.3.0 like I could in v4.3.0?

**Comment by JoshLove-msft** [comment]
Ah I see. I will look into what we can do to improve this. In the meantime, you can either handle the deserialization into your model within the function body, or alternatively, you can use a workaround to create a ServiceBusReceivedMessage instance in your function body by passing in the lockToken into the [ServiceBusModelFactory.ServiceBusReceivedMessage](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmodelfactory.servicebusreceivedmessage?view=azure-dotnet) method.

**Comment by VanessaRussell** [comment]
> or alternatively, you can use a workaround to create a ServiceBusReceivedMessage instance in your function body by passing in the lockToken into the [ServiceBusModelFactory.ServiceBusReceivedMessage](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmodelfactory.servicebusreceivedmessage?view=azure-dotnet) method.

Sounds like the [ServiceBuseMessageActions.DeadLetterMessageAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.servicebus.servicebusmessageactions.deadlettermessageasync?view=azure-dotnet#microsoft-azure-webjobs-servicebus-servicebusmessageactions-deadlettermessageasync(azure-messaging-servicebus-servicebusreceivedmessage-system-collections-generic-idictionary((system-string-system-object))-system-threading-cancellationtoken)) method should have an overload that takes in the lockTokenGuid instead of the ServiceBusReceivedMessage to do this behind the scenes 😀

I'll work on verifying that this resolves my issue.

**Comment by marnoot** [comment]
If we carry the original ServiceBusReceivedMessage around in our code it doubles our memory footprint over when we could just carry around the locktoken, which is a big problem. 

The ServiceBusModelFactory workaround _works_, but it's awkward. Could the reason for making the locktoken overloads internal-only be shared?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft If we carry the original ServiceBusReceivedMessage around in our code it doubles our memory footprint over when we could just carry around the locktoken, which is a big problem.
> 
> The ServiceBusModelFactory workaround _works_, but it's awkward. Could the reason for making the locktoken overloads internal-only be shared?

Do you need to carry it around beyond the function invocation? Even if you only bind to the locktoken, the extension still creates the ServiceBusReceivedMessage so that memory is still being allocated.

In terms of the reasoning for the locktoken removal, see https://github.com/Azure/azure-sdk-for-net/issues/10852#issuecomment-679859788

**Comment by janus007** [comment]
It seems like a mess to me. Why are you making it so hard to handle Service Bus Messaging?
Hours and hours are running through dev teams each day trying to bend everything into a soft six pence.

Very annoying :(

**Comment by Dmo16** [comment]
Found this GitHub issue after more digging than I'd like to admit.

Based on this comment by @JoshLove-msft :

https://github.com/Azure/azure-sdk-for-net/issues/27926#issuecomment-1086424433

I tried using `ServiceBusReceivedMessage` in my function and placing it directly under the attribute

```csharp    [FunctionName("CreateSeasonTrigger")]
    public async Task RunAsync(
        [ServiceBusTrigger("season_service_create_request", Connection = Constants.ServiceBusConnectionString)] string seasonJson,
        ServiceBusReceivedMessage message,
        ServiceBusMessageActions messageReceiver,
        ILogger log,
        string replyTo,
        string messageId
        )
```

Doing this gives me this error:

`Microsoft.Azure.WebJobs.Host: Error indexing method 'CreateSeasonTrigger'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'message' to type ServiceBusReceivedMessage.`

I'm also running an in process function, like OP.

I tried doing this same thing in an isolated function just as a test, in case it was only available in isolated functions.

To my amusement, the isolated function does run, but my received message is null:

![Screen Shot 2022-08-27 at 3 29 39 PM](https://user-images.githubusercontent.com/45639728/187046030-7374c1bf-91d5-4938-8cf5-84222bc8f6ae.png)

I'm late to the party when it comes to Az Functions, but it would _appear_ as though we used to be able to manually dead letter messages and now, it seems there isn't a straight forward way to do this?

All I'm looking to do is this:

If any of my own logic throws exceptions based on my business logic, I want to dead letter the message so that 1) I can customize the headers for debugging and 2) There's no need to keep retrying the message if I'm throwing an exception from say, the database entry or something.

Am I overlooking something really simple here? 

This seems like a feature that anyone developing a microservice with even basic business logic would want to be able to have access to.

**Comment by JoshLove-msft** [comment]
You can still manually dead letter messages, you would just need to remove the `string seasonJson` parameter and instead get the Json from the ServiceBusReceivedMessage.Body property.

**Comment by Dmo16** [comment]
Hey Josh,

Thanks for the tip, and for commenting on the weekend, much appreciated!

That did fix the in process function for me and I'm now able to dead letter just fine.

I tried the same thing with the isolated function though, to see if I could figure out why the message was null and I received this error:

`Exception: Microsoft.Azure.Functions.Worker.FunctionInputConverterException: Error converting 1 input parameters for Function 'CreateSeasonTrigger': Cannot convert input parameter 'message' to type 'Azure.Messaging.ServiceBus.ServiceBusReceivedMessage' from type 'System.String'. `

I'll need to scour the docs again to find the right way to handle this with isolated functions as we will be migrating to them with .NET 7 this fall.

**Comment by JoshLove-msft** [comment]
Sorry, to clarify, manual dead lettering is only currently supported for in process functions. Adding support for isolated functions is actively being investigated.

**Comment by Dmo16** [comment]
Gotcha, thanks for the info, Josh.

**Comment by schneidenbach** [comment]
> Sorry, to clarify, manual dead lettering is only currently supported for in process functions. Adding support for isolated functions is actively being investigated.
> 
> Along the same lines, binding to the ServiceBusReceivedMessage is only available right now for in-process, but is also being investigated for isolated functions.

@JoshLove-msft consider this a vote for support for SDK types in Isolated Functions.

**Comment by jsquire** [comment]
The core feature request being made in this issue is to include support for completing messages using just the lock token.  After further discussion, this is not a feature that we will be moving forward with at present.  As was mentioned earlier, the rationale for the original decision can be found in [#10852](https://github.com/Azure/azure-sdk-for-net/issues/10852#issuecomment-679859788).

With respect to the orthogonal discussion around isolated worker support that appears in later comments - this is work in progress.  Currently, it is now possible to bind to SDK types in the isolated Functions context.  We are continuing to collaborate with the Functions runtime team to enable a communications channel that will allow us to support operations like completing messages, though the timeline for this remains unknown.

Closing this out.
