### ISSUE TITLE
So what are the possible values for the content types? Why not list them

### ISSUE THREAD

**Issue by FanJiangCa** [Azure/azure-sdk-for-net#27927]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 07b1f22d-9cef-a2ca-edd2-3094d81f73a5
* Version Independent ID: 285b2f60-7604-6090-fa7e-21848beb025f
* Content: [BlobProperties.ContentType Property (Microsoft.Azure.Storage.Blob) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobproperties.contenttype?view=azure-dotnet-legacy#microsoft-azure-storage-blob-blobproperties-contenttype)
* Content Source: [xml/Microsoft.Azure.Storage.Blob/BlobProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.Blob/BlobProperties.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@FanJiangCa This can be any [MIME Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) based on the content of the blob, which is up to your scenario. Refer [this SO post](https://stackoverflow.com/q/23714383/10417839) that lists out some common types.
