### ISSUE TITLE
[BUG] Azure.Identity 1.4- SharedTokenCacheCredential no longer works when used in DefaultAzureCredentialOptions

### ISSUE THREAD

**Issue by ayeltsov** [Azure/azure-sdk-for-net#27920]
### Library name and version

Azure.Identity 1.5

### Describe the bug

Pardon the title gore.

This commit https://github.com/Azure/azure-sdk-for-net/commit/215a57637d0b115b4231c47b7df37452ff0772a2 changed how we hook up TokenCache:

https://github.com/Azure/azure-sdk-for-net/blame/6401d15192237dcdbc1e5daf17075ed1aa3cd8a0/sdk/identity/Azure.Identity/src/MsalClientBase.cs#L64-L72

The effect is that it broke silent authentication from token cache that was working with Azure.Identity 1.3

Here is the code:
```
const string akv = "https://MyKeyVault.vault.azure.net/";
string secretName = "MySecret";

const string MicrosoftTenantId = "72f988bf-86f1-41af-91ab-2d7cd011db47";

DefaultAzureCredentialOptions credentialOptions = new()
{
    // We only want Shared Token Cache and Interactive credential for MFA authentication
    ExcludeSharedTokenCacheCredential = false,  // <-- no longer works with 1.5, always falls through to next credential in the chain
    ExcludeInteractiveBrowserCredential = false,

    // We explicitly exclude all other credential types.
    ExcludeAzureCliCredential = true,
    ExcludeEnvironmentCredential = true,
    ExcludeManagedIdentityCredential = true,
    ExcludeVisualStudioCodeCredential = true,
    ExcludeVisualStudioCredential = true,
    ExcludeAzurePowerShellCredential = true,

    // Resources are in Microsoft tenant (as opposed to say AME).
    // Making it explicit just in case (to prevent potential conflict with user having authenticated to another tenant)
    InteractiveBrowserTenantId = MicrosoftTenantId,
    SharedTokenCacheTenantId = MicrosoftTenantId,
};

TokenCredential userCredentials = new DefaultAzureCredential(credentialOptions);

SecretClient sc = new SecretClient(new Uri(akv), userCredentials);
KeyVaultSecret kvs = sc.GetSecret(secretName, version: null, CancellationToken.None); // <-- prompts once with 1.3; always prompts in 1.5. If you inspect private properties of userCredentials, only in 1.3 SharedTokenCacheCredential is used.

```

What I found in debugger is SharedTokenCacheCredential not able to use cache because TokenCache is null below, hence it does not find any cached accounts and passes control to the next credential in chain:

```
//C:\Users\ayeltsov\AppData\Local\SourceServer\ec994ec8e5e8a8720a9c1a17f5a92aeb5df39eca966203725c5cc67aadc2988b\sdk\identity\Azure.Identity\src\MsalClientBase.cs

        protected async ValueTask<TClient> GetClientAsync(bool async, CancellationToken cancellationToken)
        {
            using var asyncLock = await _clientAsyncLock.GetLockOrValueAsync(async, cancellationToken).ConfigureAwait(false);
            if (asyncLock.HasValue)
            {
                return asyncLock.Value;
            }

            var client = await CreateClientAsync(async, cancellationToken).ConfigureAwait(false);

            if (TokenCache != null)  // <-- this is null
            {
                await TokenCache.RegisterCache(async, client.UserTokenCache, cancellationToken).ConfigureAwait(false);

                if (client is IConfidentialClientApplication cca)
                {
                    await TokenCache.RegisterCache(async, cca.AppTokenCache, cancellationToken).ConfigureAwait(false);
                }
            }

            asyncLock.SetValue(client);
            return client;
        }

```

I did not find how to initialize DefaultAzureCredentialOptions / DefaultAzureCredential so that TokenCache for SharedTokenCacheCredential gets populated.

Am I missing anything?
Even if I do please note this is a breaking change resulting in authentication prompt being presented to the user every time they run the tool.

### Expected behavior

Prompt for credentials once, then use cached credentials

### Actual behavior

Prompt for credentials every time

### Reproduction Steps

See description

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.103
 Commit:    2d7bc7059f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.103\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @ayeltsov - Sorry you are hitting this issue. Version 1.4 made [some changes ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#140-beta5-2021-04-06)to how `TokenCache` works. Please see the following samples for using the `TokenCachePersistenceOptions` to persist cache across client instances. 

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md#silent-authentication-with-authenticationrecord-and-tokencachepersistenceoptions

**Comment by ayeltsov** [comment]
I think I need to clarify the exact question I'm asking, because the links do not answer that specific question.

Statement: I'm observing that 1.4 broke silent authentication when using DefaultAzureCredentialOptions / DefaultAzureCredential. The DefaultAzureCredentialOptions internally uses SharedTokenCacheCredential, but with 1.4 it's initialized without TokenCache, making it useless.

Question: how to tell DefaultAzureCredentialOptions to enable token cache for SharedTokenCacheCredential? I don't see a way to do this currently, and if so, this is a degradation from earlier version.

**Comment by christothes** [comment]
Hi @ayeltsov - You are correct that there was a breaking change to change the default caching behavior of the `SharedTokenCacheCredential` as well as disabling it by default from the `DefaultAzureCredential`. I looked more closely at this and it seems we don't even enable a way to set the `TokenCachePersistenceOptions` for sub-credentials of `DefaultAzureCredential`.  However, that said, if the behavior you want is to prompt the user for credentials interactively the first time and authenticate silently each time after that, you should be able to do that with the sample I mentioned earlier:

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md#silent-authentication-with-authenticationrecord-and-tokencachepersistenceoptions

The `SharedTokenCacheCredential` actually doesn't add anything here, since the `TokenCachePersistenceOptions` along with an `AuthenticationRecord` specified will enable silent auth after the first time we cache credentials.

**Comment by ayeltsov** [comment]
Wanted to step back a bit. 
I think we're in agreement that there's a breaking change, and there's no way of enabling cache with `DefaultAzureCredential`.

This was the bug I'm reporting and asking to be fixed. 

As to workaround - thank you for the links, I also found a workaround that that works for me and subjectively it looks simpler since it does not need to be aware of AuthenticationRecord - https://github.com/Azure/azure-sdk-for-net/issues/23896#issuecomment-1085047864

**Comment by ayeltsov** [comment]
> need to worry about the AuthenticationRecord if you need the credentials to persist across runs of the application

Actually I'm saying that workaround I used in https://github.com/Azure/azure-sdk-for-net/issues/23896#issuecomment-1085047864 works across application runs and multiple applications without having to worry about AuthenticationRecord
