### ISSUE TITLE
[FEATURE REQ] Support WithClientCapabilities() by MsalConfidentialClient 

### ISSUE THREAD

**Issue by dingmeng-xue** [Azure/azure-sdk-for-net#27929]
### Library name

Azure.Identity

### Please describe the feature.

`MsalPublicClient` already supports `WithClientCapabilities()` with `CP1` during client building. We hope the parity feature on `MsalConfidentialClient`

**Comment by jsquire** [comment]
//fyi:  @christothes, @schaabs

**Comment by christothes** [comment]
Hi @dingmeng-xue  I could be wrong, but I believe CP1 is only supported by `PublicClientApplicationBuilder`.

**Comment by dingmeng-xue** [comment]
HI, @christothes , I added it just for tracking.

**Comment by bgavrilMS** [comment]
@christothes - does Azure SDK not support `AcquireTokenOnBehalfOf` ? I think CAE makes sense in web api scenario (OBO).
