### ISSUE TITLE
Azure Service Bus - random deserialization issues

### ISSUE THREAD

**Issue by Celtas6655** [Azure/azure-sdk-for-net#27939]
I've been recently having problems with my Service Bus queue. Random messages (one can pass and the other not) are placed on the deadletter queue with the error message saying:

```
"DeadLetterReason": "Moved because of Unable to get Message content There was an error deserializing the object of type System.String. The input source is not correctly formatted."
"DeadLetterErrorDescription": "Des"
```
This happens even before my consumer has the chance to receive the message from the queue.

The weird part is that when I requeue the message through Service Bus Explorer it passes and is successfully received and handled by my consumer.

I am using the same version of Service Bus either for sending and receiving the messages:

`Azure.Messaging.ServiceBus, version: 7.3.0`
My message is being sent like this:

 ```
       await using var client = new ServiceBusClient(connString);
        var sender = client.CreateSender(endpointName);
        var message = new ServiceBusMessage(serializedMessage);
        await sender.SendMessageAsync(message).ConfigureAwait(true);
```

**Comment by jsquire** [comment]
Hi @Celtas6655.  Thank you for reaching out and we regret that you're experiencing difficulties.   To help us reproduce, would you be able to share an example of a message that has this issue?   It would also be helpful if you're able to collect SDK logs for the application attempting to consume the message.   Information on capturing logs can be found [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.Messaging.ServiceBus#logging-and-diagnostics).
