### ISSUE TITLE
[BUG] Microsoft.Azure.Management.ApiManagement.Models.ProductContract "Product was not creating with spaces"

### ISSUE THREAD

**Issue by PrathipatiHari** [Azure/azure-sdk-for-net#27956]
### Library name and version

Microsoft.Azure.Management.ApiManagement(8.0.0 - Preview)

### Describe the bug

using the Azure SDK, Microsoft.Azure.Management.ApiManagement.Models.ProductContract model not allowing spaces while creating new Product. 

Please find the below example.
Ex: (Product Name) - Not allowed to create a product with spaces. 

But, when we try to create a product from Azure portal. it is allowing Product name with spaces (Ex: Product Name). And when we save the changes Product ID is getting created as (Ex: product-name). 

But this was not same behavior while creating a product from Azure SDK.

Question:
Is this the expected behavior from Azure SDK or we have to pass any parameters ?

### Expected behavior

when we try to create a product from Azure portal. it is allowing Product name with spaces (Ex: Product Name). And when we save the changes Product ID is getting created as (Ex: product-name). 

### Actual behavior

using the Azure SDK, Microsoft.Azure.Management.ApiManagement.Models.ProductContract model not allowing spaces while creating new Product. 

Please find the below example.
Ex: (Product Name) - Not allowed to create a product with spaces. 

### Reproduction Steps

In the Azure SDK, Microsoft.Azure.Management.ApiManagement.Models.ProductContract model, Pass DisplayName  value as "Product Name" to reproduce the issue. 

### Environment

.NET Core 3.1
IDE : Visual studio 2019.
Version 16.11.11

**Comment by HarveyLink** [comment]
Hi @PrathipatiHari ,
Thank you for using Azure SDK for .NET.
For the issue you metioned:
I can't repro on my side, with following code, the displayname could be created with space:
```
ProductContract productContract = new ProductContract() { DisplayName = "sdk withspace" };
await apiManagementClient.Product.CreateOrUpdateAsync("sdktestrg", "sdktest", "sdk-withspace", productContract);
```
![image](https://user-images.githubusercontent.com/30464227/174959836-cd609424-0d5d-442d-8a65-30e5f0bdd0d6.png)
The sdk version is `8.0.0-preview`.
Please confrim that this issue still exists on your side and please provide more information if possible.
