### ISSUE TITLE
[BUG] FindBlobsByTagsAsync() using BlobContainerClient keeps running till timeout

### ISSUE THREAD

**Issue by dilisha** [Azure/azure-sdk-for-net#27953]
### Library name and version

Azure.Storage.Blobs 12.11.0

### Describe the bug

FindBlobsByTagsAsync() using BlobContainerClient does not return any results.
(ref : https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.findblobsbytagsasync?view=azure-dotnet)
This keeps running for a while and times out.

I am using the same expression with FindBlobsByTagsAsync() using BlobServiceClient and it works perfectly fine.
I also tried using @container attribute in the sqlExpression to point to the same container and that also works fine. 

Unable to figure out what is wrong when using FindBlobsByTagsAsync() with BlobContainerClient

### Expected behavior

Expecting FindBlobsByTagsAsync() using BlobContainerClient to behave same as FindBlobsByTagsAsync() using BlobServiceClient with @container attribute. It should return the blobs with tags as per sql expression

### Actual behavior

The function keeps running for sometime and times out eventually giving the error : 
{"code":"InternalServerError","details":null,"message":"Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry. (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (The operation was cancelled because it exceeded the configured timeout of 0:01:40. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.) (An error occurred while sending the request.)","target":null}

### Reproduction Steps

`           
          
           var sqlExpression = $"\"{key}\"='{value}'";

          // case 1 : using serviceClient - works fine
          
            var tasks = new List<Task<T>>();

            var sqlExpressionWithContianer = $"@container = '{containerName}' and {sqlExpression}";

            await foreach (TaggedBlobItem taggedBlobItem in serviceClient.FindBlobsByTagsAsync(sqlExpressionWithContianer))
            {
                tasks.Add(GetItem<T>(taggedBlobItem.BlobName)); // get item from blobname
            }
            var results = await Task.WhenAll(tasks);
             
           // case 2 : using containerClient - keeps running till timeout 

            var tasksNew = new List<Task<T>>();

            await foreach (TaggedBlobItem taggedBlobItem in containerClient.FindBlobsByTagsAsync(sqlExpression))
            {
                tasksNew.Add(GetItem<T>(taggedBlobItem.BlobName)); // get item from blobname
            }
            var resultsNew = await Task.WhenAll(tasksNew);

`

### Environment

net6.0
IDE and version : Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.1.1

**Comment by SaurabhSharma-MSFT** [comment]
@dilisha We are looking into it and get back to you for any additional information.

**Comment by SatishBoddu-MSFT** [comment]
Hello @dilisha 
yes this is working for only `BlobContainerClient`

Reference: https://github.com/Azure/azure-sdk-for-net/issues/27610

Redirecting to the Service team's attention

**Comment by dilisha** [comment]
@SatishBoddu-MSFT, the issue you linked is different from the one I am facing.
I am not able to use FindBlobsByTagsAsync() with BlobContainerClient using a simple "TagKey" = 'TagValue' query itself. It keeps running continuously without giving any results and times out.

**Comment by SatishBoddu-MSFT** [comment]
> @SatishBoddu-MSFT Satish Boddu FTE, the issue you linked is different from the one I am facing. I am not able to use FindBlobsByTagsAsync() with BlobContainerClient using a simple "TagKey" = 'TagValue' query itself. It keeps running continuously without giving any results and times out.

Hello @dilisha Thanks, it's related with implementation of BlobContainerClient  so we linked the issue!

I agree with your scenario, as we did tested it and the BlobContainerClient\thread goes into an infinite loop ending with timeout, which needs Service Team's attention and we have routed it accordingly!

**Comment by drdamour** [comment]
we're getting this today too

**Comment by seanmcc-msft** [comment]
Hi everyone, this is a known issue in the service.  A fix is rolling out, and this issue should stop reproducing in the next few weeks.

**Comment by aaron-cardoz** [comment]
@seanmcc-msft  Has this issue being fixed?
We are also facing the same issue for our storage accounts and I have raised a support ticket.

**Comment by navba-MSFT** [comment]
@dilisha @aaron-cardoz Apologies for the late reply. I will update this thread once I have more information on this.

**Comment by Ghyath-Serhal** [comment]
@seanmcc-msft. Any updates about this issue? Is it solved or still pending?

**Comment by seanmcc-msft** [comment]
This issue has been resolved in the service.
