### ISSUE TITLE
[QUERY] If Azure file share opeations are atomic? 

### ISSUE THREAD

**Issue by xichenAiguang** [Azure/azure-sdk-for-net#27951]
### Library name and version

Azure.Storage.Files.Shares 12.9.0

### Query/Question

Hi, My app will use File Share (ADLS Gen2) to store data, and  I'd like to use api to create share client/ create share directory client/ delete file, etc. I am wondering if these  opeations are atomic, thanks

### Environment

.net 6.0

**Comment by SatishBoddu-MSFT** [comment]
Hello @xichenAiguang 

I hope you have already visited this doc : [One service, multiple concepts](https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-introduction#one-service-multiple-concepts)

![image](https://user-images.githubusercontent.com/62923178/162885105-2fca25b9-bfb8-4c5f-a048-8c92b865ad32.png)

**Comment by SatishBoddu-MSFT** [comment]
Hello @xichenAiguang 
Just checking back, could you please let us know if you need further help in this matter.

**Comment by SatishBoddu-MSFT** [comment]
We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.
