### ISSUE TITLE
Distributed traces need to be added to ServiceBus extension

### ISSUE THREAD

**Issue by alrod** [Azure/azure-sdk-for-net#27969]
[CRI](https://portal.microsofticm.com/imp/v3/incidents/details/271092446/home)

**Comment by jsquire** [comment]
As Josh mentioned, this issue is external to the Service Bus extension and is being tracked by AppInsights in [#2151](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2151).   Closing this out as a duplicate.
