### ISSUE TITLE
Instance CognitiveServicesManagementClient with DefaultAzureCredential

### ISSUE THREAD

**Issue by vdimov-gcmlp** [Azure/azure-sdk-for-net#27964]
Documentation on javascript client suggests instancing CognitiveServicesManagementClient with DefaultAzureCredential. Are there plans to Azure dotnet sdk supporting DefaultAzureCredential?

https://docs.microsoft.com/en-us/javascript/api/overview/azure/arm-cognitiveservices-readme?view=azure-node-latest#create-and-authenticate-a-cognitiveservicesmanagementclient

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f10a28d-9339-3d78-5f08-64e8f4d3c575
* Version Independent ID: b3810d01-13ed-a3e6-b14b-5ac01cf36479
* Content: [CognitiveServicesManagementClient Class (Microsoft.Azure.Management.CognitiveServices) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.cognitiveservices.cognitiveservicesmanagementclient?view=azure-dotnet&viewFallbackFrom=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Azure.Management.CognitiveServices/CognitiveServicesManagementClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.CognitiveServices/CognitiveServicesManagementClient.xml)
* Service: **cognitive-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment]
> Are there plans for Azure.Identity to support the creation of instances of CognitiveServicesManagementClient?

Add @ArthurMa1978  for confirmation.

**Comment by HarveyLink** [comment]
Currently, we don't support `DefaultAzureCredential` from `Azure.Identity` in `Microsoft.Azure.Management.CognitiveServices`.
We have this auth type supported in new designed SDK. We're expanding the coverage of the Azure service. You could waiting for the new CognitiveServices SDK.
