### ISSUE TITLE
Unable to change Transport type to AmqpWebSockets for ServiceBus trigger

### ISSUE THREAD

**Issue by YevhenSemikon** [Azure/azure-sdk-for-net#27967]
In order to use **ServiceBusMessageActions** we need to update Microsoft.Azure.WebJobs.Extensions.ServiceBus to version 5.1.0 or higher, but due to organization restrictions we could not connect using default transport type (AmqpTcp) during development. Is there a possibility to change TransportType on ServiceBus trigger?

**Used versions**
- Function App version 2.
- Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.1.0 or 5.2.0

**Steps to reproduce**
Create a new function app with a ServiceBus Queue trigger and try to connect behind a firewall that blocks non https outbound ports and compile and run the local app.

**Expected behavior**
It will be nice if we have TransportType as an extension like here (https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#hostjson-settings) or previous workaround with connection string.

**Actual behavior**
I am not able to change the default Transport Type and as a result, every time I do development I end up with an error:
An exception occurred while creating receive link for Identifier: ***. Error Message: 'System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Known workarounds**
1. Turn off firewall that blocks outbound ports.
2. For Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.1.0 adding ";TransportType=AmqpWebSockets" to the connection. (unfortunately is not working for versions 5.1.0 or 5.2.0) [Previous issue](https://github.com/Azure/azure-functions-servicebus-extension/issues/36)

**Comment by jsquire** [comment]
Hi @YevhenSemikon.   Thank you for reaching out and we regret that you're experiencing difficulties.  The [documentation](https://docs.microsoft.com/azure/azure-functions/functions-bindings-service-bus?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#hostjson-settings) for the Service Bus extension `host.json` settings has been updated to include details for setting the transport type.
