### ISSUE TITLE
.NET: Service Bus extension 5.0.0-beta.2: host.json settings as instructed per the documentation has no effect

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-sdk-for-net#27972]
I am experimenting with .NET Azure Functions [**Service Bus Extension**: **5.0.0-beta.2**](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.0.0-beta.2). I am consuming messages from Session enabled queue and in the Function `ServiceBusTrigger`, `IsSessionsEnabled` is set to `true`.

.csproj,
```
Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.0.0-beta.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>
```
According to the documentation ([https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#hostjson-settings](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus#hostjson-settings)),
![image](https://user-images.githubusercontent.com/5653381/117219760-09d25100-ae5a-11eb-9642-235fa4a98cfd.png)

When I have the settings defined insider `serviceBusOptions` property, it doesn't seem to have an affect. For an example,
following host.json,
```
{
    "version": "2.0",
    "logging": {
        ...
    },
    "extensions": {
        "serviceBus": {
            "serviceBusOptions": {
                "retryOptions": {
                    "mode": "exponential",
                    "tryTimeout": "00:00:10",
                    "delay": "00:00:00.80",
                    "maxDelay": "00:01:00",
                    "maxRetries": 4
                },

                // These DOES NOT affect
                "autoCompleteMessages": false,
                "maxConcurrentSessions": 1
            }
        }
    }
}
```
Gives me something like this.
![image](https://user-images.githubusercontent.com/5653381/117220014-849b6c00-ae5a-11eb-9e97-4c22d6bce968.png)

So as you can see, even though I have specified `"maxConcurrentSessions": 1`, it's processing multipe sessions at a time.

But if I do something like this,
```
{
    "version": "2.0",
    "logging": {
        ...
    },
    "extensions": {
        "serviceBus": {
            "autoCompleteMessages": false,
            "maxConcurrentSessions": 1
        }
    }
}
```
It gives the expected output.
![image](https://user-images.githubusercontent.com/5653381/117220231-e956c680-ae5a-11eb-9e1a-14752d6f848c.png)

So I am thinking, either the documentation is incorrect or there is a bug.

Any help is appreciated!

**Comment by jsquire** [comment]
The referenced documentation appears to have been updated at some point and is now correct.   Closing this out.
