### ISSUE TITLE
Unable to set custom headers when sending POCO

### ISSUE THREAD

**Issue by RiverPhillips** [Azure/azure-sdk-for-net#27978]
Currently you cannot return an object of type T if you want to set user properties. It would be ideal if you could use the automatic serialisation implemented here and also set the user properties by optionally providing a Dictionary<string, object>.

**Comment by jsquire** [comment]
//fyi:  @JoshLove-msft

**Comment by JimSuplizio** [comment]
Hi @RiverPhillips, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
