### ISSUE TITLE
ServiceBus function trigger, managed identity and local development issues

### ISSUE THREAD

**Issue by mark-r-cullen** [Azure/azure-sdk-for-net#27970]
Hi,

I am trying to switch from using shared access keys in connection strings to MI using function triggers. Currently using Microsoft.Azure.ServiceBus 5.1.3 (deprecated I know) and Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.3.0, it works using ;Authentication=ManagedIdentity once deployed to Azure but I am having trouble getting this to work trying to run it on my own machine.

From what I can see it seems like to make this work I will need to switch to use Azure.Messaging.ServiceBus and Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0 (higher than beta 2) so that I can do the ConnectionString__fullyQualifiedNamespace thing in local.settings.json. I've given this a go, and I can see lots of debug output suggesting it has got a token from both VisualStudio and Azure CLI, but I still get "Listen" (the function is receiving messages) access denied errors. 

I have tried adding my user as both Contributor and as Service Bus Data Owner on the service bus resource but this made no difference. The role assignment has been done at the topic / queue level, not the namespace issue (but this is working once deployed). I'm not sure if that would have anything to do with it.

`VisualStudioCredential.GetToken succeeded. Scopes: [ https://servicebus.azure.net/.default ] ParentRequestId:  ExpiresOn: 2021-09-29T15:42:17.0000000+00:00
[2021-09-29T14:42:18.775Z] DefaultAzureCredential.GetToken succeeded. Scopes: [ https://servicebus.azure.net/.default ] ParentRequestId:  ExpiresOn: 2021-09-29T15:42:17.0000000+00:00
[2021-09-29T14:42:19.617Z] An exception occurred while creating receive link for Identifier: xxxxxx/Subscriptions/xxxxxx-a785584c-2cd7-4df2-87fe-3caea8358d88. Error Message: 'Microsoft.Azure.Amqp.AmqpException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://xxxxxxx.servicebus.windows.net/xxxxxx/subscriptions/xxxxxx'. TrackingId:7ac1e8eee3074057b4a231085e7ce1e6_G26, SystemTracker:gateway7, Timestamp:2021-09-29T14:42:19`

Any idea what I might be doing wrong here? Appreciate this might not be enough info, let me know if you need anything more specific.

**Comment by ahsanhabib91** [comment]
Actually, I also experienced the same issue but with **EventHub output binding** until I added **AZURE_TENANT_ID** as @willyt150 suggests. Thanks for that !!! 
However, I wonder, this is not mentioned in the documentation. Before adding **AZURE_TENANT_ID** I did logout and login locally several times and set the correct account subscription through `az account set --subscription "<subscription_name>"`. Still didn't work. Here is the error:

`System.Private.CoreLib: Put token failed. status-code: 401, status-description: InvalidIssuer: Token issuer is invalid. TrackingId:4d0c9bf1-374a-4d2f-b8b3-09ffc61366c3, SystemTracker:NoSystemTracker, Timestamp:2022-04-26T18:23:09.`

Although I have added the Role assignments through Azure Portal, not through **az cli** as @JoshLove-msft  suggested. Could this be the reason for failure? If so, then I guess, this is not mentioned in the Documentation as well If I am not wrong !!! or does it?

**Comment by JoshLove-msft** [comment]
This documentation is included in the trigger docs now - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=in-process%2Cextensionv5&pivots=programming-language-csharp#grant-permission-to-the-identity
