### ISSUE TITLE
replyToSessionId binding data

### ISSUE THREAD

**Issue by chanes-cds** [Azure/azure-sdk-for-net#27977]
Can this be added to ServiceBusTriggerBindingStrategy.cs?  </br>
I am currently doing

`const replyToSessionId = context.bindingData.userProperties.replyToSessionId;`

as a work around but would be happy to see official support for this attribute in the future.

**Comment by JoshLove-msft** [comment]
Related change was made for SessionId in https://github.com/Azure/azure-sdk-for-net/pull/28277
