### ISSUE TITLE
ContentSourceNotAccessible Content is not accessible: Could not retrieve build data within 60 seconds.

### ISSUE THREAD

**Issue by omidchini** [Azure/azure-sdk-for-net#27988]
No matter how I try to build a custom model, it always fails with: ContentSourceNotAccessible
Content is not accessible: Could not retrieve build data within 60 seconds.

and I have tried it over 20 times now.

Request:
`{
  "modelId": "TestModelName",
  "description": "Something",
  "buildMode": "neural",
  "azureBlobSource":
  {
    "containerUrl": "https://***.blob.core.windows.net/***",
    "prefix": ""
  },
  "tags": {
    "createdBy": "Me"
  }
}`

Result in the Operation:
`{
    "operationId": "31517210447_ad4c457c-9a26-410b-b4b4-4d6cea9ddba1",
    "kind": "documentModelBuild",
    "status": "failed",
    "createdDateTime": "2022-04-05T11:19:12Z",
    "lastUpdatedDateTime": "2022-04-05T11:20:13Z",
    "resourceLocation": "https://francecentral.api.cognitive.microsoft.com/formrecognizer/documentModels/TestModelName?api-version=2022-01-30-preview",
    "percentCompleted": 100,
    "error": {
        "code": "InvalidRequest",
        "message": "Invalid request.",
        "details": [
            {
                "code": "ContentSourceNotAccessible",
                "message": "Content is not accessible: Could not retrieve build data within 60 seconds."
            }
        ]
    },
    "tags": {
        "createdBy": "string"
    }
}`

**Comment by jsquire** [comment]
Hi @omidchini.   Thank you for reaching out and we regret that you're experiencing difficulties.   Unfortunately, we're don't have enough information to understand what library you're using and in what scenario you're encountering the behavior that you're describing.   

Would you please be so kind as to let us know the package, including version, that you're using and provide a brief summary of how to reproduce your issue?

**Comment by jsquire** [comment]
Thank you for the additional context, @omidchini.   Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @omidchini. It seems the service is not being able to access your container. How are you generating your Blob SAS URL? I can't tell how yours look like exactly since you have redacted it, but it should look similar to this: `https://{blobStore}.blob.core.windows.net/{blobResource}?sp={...}&st={...}&se={...}&spr={...}&sv={...}&sr={...}&sig={...}`
