### ISSUE TITLE
Please document the minimum value of Delay property

### ISSUE THREAD

**Issue by acrov** [Azure/azure-sdk-for-net#27989]
Please document the minimum value of Delay property so that people can avoid getting the following

```
Value is less than the minimum allowed. (Parameter 'Delay') System.ArgumentOutOfRangeException at Azure.Messaging.ServiceBus.ServiceBusRetryOptions.set_Delay
```

Looking at the source the valid range is 1 millisecond to 5 minutes.

Similar documentation for the limits of other properties are also missing and are:
MaxRetries: 0 to 100
MaxDelay: not negative
TryTimeout: 0 to 1 hour

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4926f1b-a35b-4eff-6ee0-c0978b5a97b7
* Version Independent ID: 4e7e6dda-3494-a19c-3ebd-bfb933b9ab93
* Content: [ServiceBusRetryOptions Class (Azure.Messaging.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusretryoptions?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.ServiceBus/ServiceBusRetryOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus/ServiceBusRetryOptions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
