### ISSUE TITLE
[QUERY] Azure Search Results Boosting

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#27990]
### Library name and version

Azure Search

### Query/Question

This is in continuation of closed query #27574 where I had asked some questions and got some nice feedback from @dereklegenzoff. I tried in my local but couldn't get the expected results

Our requirement is that we have to do a fuzzy search, partial term search and exact matches where we should order search results in way that we should first display exact matches (if any), then partial term matches and then fuzzy search results. We were given the suggestion of using Term Boosting but unfortunately, it is not working out as expected.

Following are the two examples/search queries we are trying:

(Ben~) OR (/.*Ben.*/^3) OR "Ben"^4

(Jeferson~ Medical~ Center~) OR (Jeferson^2 Medical^2 Center^2) OR (/.*Jeferson.*/^3 /.*Medical.*/^3 /.*Center.*/^3) OR "Jeferson Medical Center"^4

I am setting searchMode to all and queryType to full in our search query syntax.

There is a possibility I might be doing something wrong for which I am curious to know how to correct it.

**Comment by dereklegenzoff** [comment]
@ssghoda - could you clarify what isn't working as expected?

The only issue i see off the bat is that you should be using `/.*Ben.*/` rather than `/.Ben./`

**Comment by ssghoda** [comment]
Oh I think it removed the "*" in my post. I should have wrapped that line in code tag.

Following are the two examples/search queries we are trying:

`(Ben~) OR (/.*Ben.*/^3) OR "Ben"^4`

`(Jeferson~ Medical~ Center~) OR (Jeferson^2 Medical^2 Center^2) OR (/.*Jeferson.*/^3 /.*Medical.*/^3 /.*Center.*/^3) OR "Jeferson Medical Center"^4`

Our requirement is that we have to do a fuzzy search, partial term search and exact matches where we should order search results in way that we should first display exact matches (if any), then partial term matches and then fuzzy search results.

So in the case of `(Ben~) OR (/.*Ben.*/^3) OR "Ben"^4`, we should get all the Ben at the top in Azure Search API response, following them all the names containing "Ben" in it such as Benjamin and then fuzzy searches such as Bean.

We were given the suggestion of using Term Boosting but unfortunately, it is not working out as expected. So wanted to know if I am doing something wrong, or something else we have to do here.

**Comment by dereklegenzoff** [comment]
Got it. So it sounds like you're just not getting the results in the expected order.

One thing you're potentially running into is that partial term searches always contribute a consistent amount to the query score while typical term searches will contribute a particular amount based off of BM25:

> An example illustrates why this matters. Wildcard searches, including prefix searches, are ambiguous by definition because the input is a partial string with potential matches on a very large number of disparate terms (consider an input of "tour*", with matches found on “tours”, “tourettes”, and “tourmaline”). Given the nature of these results, there is no way to reasonably infer which terms are more valuable than others. For this reason, we ignore term frequencies when scoring results in queries of types wildcard, prefix and regex. In a multi-part search request that includes partial and complete terms, results from the partial input are incorporated with a constant score to avoid bias towards potentially unexpected matches.

That snippet comes from this doc: [Full text search in Azure Cognitive Search](https://docs.microsoft.com/en-us/azure/search/search-lucene-query-architecture#stage-4-scoring)

With this, you could consider trying to experiment with a higher boost for the exact term matches. You also have the ability to tweak some of the parameters that impact BM25 scoring. More details on that [here](https://docs.microsoft.com/en-us/azure/search/index-ranking-similarity). You could tweak the k1 and b parameters to try to make the score from the term matches more comparable to the partial term search matches.

**Comment by ssghoda** [comment]
I see. So changing k1 and b values would change the way search scores are computed and we will get results in expected order which is first all full name matches, then partial term matches and then fuzzy matches?

**Comment by dereklegenzoff** [comment]
What I'd recommend trying first is adding a stronger boost to the exact term queries--that's probably the simplest approach. If you still can't get that to work as expected, then you could start to mess around with k1 and b parameters.

**Comment by ssghoda** [comment]
That information was very helpful. Giving a stronger boost seems to be working and giving expected results. I changed our search query as follows:

`(Ben~) || (/.*Ben.*/^80) || 'Ben'^90`

We will try some more examples like this and see if we need to raise the boost factor even higher. If not, we will discuss k1 and b parameters.
