### ISSUE TITLE
SharedTokenCacheCredential cannot get credential for Azure.Identity 1.4 while works for 1.3

### ISSUE THREAD

**Issue by yunxzhan** [Azure/azure-sdk-for-net#28029]
Using DefaultAzureCredential and seems breaks after upgrading Azure.Identity from 1.3.0 to 1.4.0
SharedTokenCacheCredential is getting the following error:
**CredentialUnavailableException
SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.**
Any ideas what has been changed for SharedTokenCacheCredential?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.
