### ISSUE TITLE
[BUG] [EventGrid] Cloud event time serialization

### ISSUE THREAD

**Issue by a-dovgal** [Azure/azure-sdk-for-net#28022]
### Library name and version

Azure.Messaging.EventGrid

### Describe the bug

Hello

When I publish cloud events with time in the UTC format - I see time with offset but [should be](https://docs.microsoft.com/azure/event-grid/cloud-event-schema) without offset, just with Z in the end.
Could you please add a custom serialization or make this field virtual or string or something else?

Thank you, best regards.

### Expected behavior

`"time": "2022-04-05T19:19:42.58Z"`

### Actual behavior

`"time": "2022-04-05T19:19:42.5805717+00:00"`

### Reproduction Steps

Publish cloud events with time in the UTC format.

**Comment by a-dovgal** [comment]
Hi @JoshLove-msft,
Yes, you're right. But in all cases, all examples time with "Z". Also, in the EventGridEvent, received data and in unit-tests.

**Comment by JoshLove-msft** [comment]
Since they are equivalent, either one should be fine. It would be tricky to change the format at this point.
