### ISSUE TITLE
Replace convenience APIs for HEAD operations with generated code

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#28032]
Once https://github.com/Azure/autorest.csharp/issues/2148 has completed, we can remove the manually-written convenience APIs in WebPubSub with generated code by setting `head-as-default: true` in the autorest.md.

This applies to:
- [ ] [GroupExists](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/webpubsub/Azure.Messaging.WebPubSub/src/WebPubSubServiceClient_extensions.cs#L296)
- [ ] [UserExists](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/webpubsub/Azure.Messaging.WebPubSub/src/WebPubSubServiceClient_extensions.cs#L314)
- [ ] [ConnectionExists](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/webpubsub/Azure.Messaging.WebPubSub/src/WebPubSubServiceClient_extensions.cs#L332)
- [ ] [CheckPermission](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/webpubsub/Azure.Messaging.WebPubSub/src/WebPubSubServiceClient_extensions.cs#L396)

**Comment by annelo-msft** [comment]
Dependent on: https://github.com/Azure/autorest.csharp/issues/2148

**Comment by pallavit** [comment]
@lirenhe could you please help route this to the right person in case this is still a valid concern.
