### ISSUE TITLE
Demonstrate how to mutate message body via plugin

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#28037]
Ok I think we can take this as feedback to add samples demonstrating how one would mutate the message body in a plugin.

_Originally posted by @JoshLove-msft in https://github.com/Azure/azure-sdk-for-net/issues/12943#issuecomment-1090902140_

**Comment by SeanFeldman** [comment]
Any updates?

**Comment by JoshLove-msft** [comment]
> Any updates?

I've added this to the November milestone.

**Comment by jsquire** [comment]
This is covered by the claims check example.   Closing this out.
