### ISSUE TITLE
Missing info regarding the usage of method GetAccessTokenForUserAsync

### ISSUE THREAD

**Issue by MarcoEnxuto** [Azure/azure-sdk-for-net#28051]
By using .Net 5/6 ASP.NET webAPI apps, and adding DistributedCache to its service. I found out the method flow goes first to the cache to obtain the Access Token. If the cache does not have the object, it acquires the token on login.microsoftonline.com.

This means, it works just like ConfidencialClientApplication.AcquireTokenSilent method, am i right?
At least i got it work that way, so i just don't need Microsoft.Identity.Client anymore, and i use Microsoft.Identity.Web by DI.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 712b76af-89ea-f3a8-1efc-eef633348d92
* Version Independent ID: 8e15c5d3-3129-889f-587d-34f30a6d4de0
* Content: [ITokenAcquisition.GetAccessTokenForUserAsync Method (Microsoft.Identity.Web) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.web.itokenacquisition.getaccesstokenforuserasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Identity.Web/ITokenAcquisition.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Web/ITokenAcquisition.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Identity.Web` package is maintained as [#1696](https://github.com/AzureAD/microsoft-identity-web/issues/1696).
