### ISSUE TITLE
[BUG] Azure.Storage.Blobs throws internal exception when etag matches IfNoneMatch value

### ISSUE THREAD

**Issue by michsco** [Azure/azure-sdk-for-net#28059]
### Library name and version

Azure.Storage.Blobs 12.11.0

### Describe the bug

When retrieving blobs from storage with `DownloadStreamingAsync` when the etag value matches the `IfNoneMatch` value, the code should throw a `RequestFailedException` with a status code of 304. Instead, it throws an internal exception with a `Status` of 304, which makes it impossible to distinguish this property.
```csharp
BlobRequestConditions conditions = new();
conditions.IfNoneMatch = new ETag(etag);

Response<BlobDownloadStreamingResult> blobDataStream = await blob.DownloadStreamingAsync(
    range: range,
    conditions: conditions,
    cancellationToken: cancellationToken);
```

### Expected behavior

`RequestFailedException` should be thrown with a status code of 304

### Actual behavior

Internal exception is thrown with a status code of 304 that can only be extracted via reflection. Internal exception is `ResponseBodyNotFoundException` (see [here](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/core/Azure.Core/src/Shared/NoBodyResponseOfT.cs))

### Reproduction Steps

1. Setup a blob and retrieve the etag.
2. Set the `etag` variable to the blob's etag.
3. Run this code:
```csharp
BlobRequestConditions conditions = new();
conditions.IfNoneMatch = new ETag(etag);

Response<BlobDownloadStreamingResult> blobDataStream = await blob.DownloadStreamingAsync(
    range: range,
    conditions: conditions,
    cancellationToken: cancellationToken);
```

### Environment

*Hosting Platform*: Windows or Linux
*IDE*: Visual Studio 17.1

**Comment by SaurabhSharma-MSFT** [comment]
@michsco We are looking into it and get back to you for any additional information.

**Comment by petsve** [comment]
Any update on this?
As a workaround I call GetRawResponse() and then check if the Status is 304, but that is not a nice addition to our codebase.

**Comment by seanmcc-msft** [comment]
This issue was fixed by https://github.com/Azure/azure-sdk-for-net/pull/22647

We now have a unit test for DownloadStreaming and 304s - https://github.com/Azure/azure-sdk-for-net/blob/f0d1a30fc0164389c137b8c782901cb214c3c623/sdk/storage/Azure.Storage.Blobs/tests/BlobBaseClientTests.cs#L1750.

I also tried this with IfNoneMatch and the ETag from the last upload to confirm this was fixed.
