### ISSUE TITLE
[Text Analytics] Design Error Experience for Unsupported Fields and Operations in Legacy Versions

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#28060]
# Summary

With the Text Analytics client supporting the legacy Text Analytics REST API and new Language REST API, there will be operations, analysis types, and model fields not supported/recognized by the legacy version.   A design is needed for a consistent developer experience and an understanding of when to allow the service to perform validation and when client-side validation is needed.

# Scope of Work

- Understand the API gaps between the REST APIs and test service behavior for common scenarios

- Analyze service behavior and identify how they can be used in a consistent and clear developer experience

- Propose a design for addressing gaps and unsupported members across languages

# Success Criteria

- The design has been discussed with the feature team and feedback has been incorporated

- The design has been documented appropriate for discussion with the architects

- Architect discussions have been scheduled

**Comment by maririos** [comment]
PR #28809 introduces new properties only supported in the Language client which are:
- `FhirVersion` input property
- `FhirBundle` output property.

I followed what we have done in this library when a new property is added that is only supported in specific versions and does not affect behavior of older version output properties:
- We add that information to docstrings for both input and output property.
- Input property:
  - If the property is a query parameter, we send it to the service and let them manage it.
  - If the property is a body parameter, we drop it.
- Output property: Value is always empty Dict even when targeting older versions

If as a result of the work in this issue, the guidance is different, please modify `Fhir` behavior

**Comment by heaths** [comment]
Just to clarify, the output property will be the default value unless a collection/dictionary, in which case it's an empty collection/dictionary.

**Comment by heaths** [comment]
Python errs when trying to use newer properties against older versions using decorators. Similar idea with attributes for .NET could work here.

**Comment by heaths** [comment]
Could also just throw exceptions in either the _Transform.cs_ or _Transform.Legacy.cs_ files for newly-added model properties not updated to the legacy swagger. It really only matters in these cases anyway.
