### ISSUE TITLE
[Text Analytics] Add Missing Bespoke Methods

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#28067]
# Summary

Each analysis task that can be performed should have a set of bespoke methods so that the API surface is consistent, and some tasks are not hidden from developers.  The missing bespoke methods are for the extractive summarization and custom text tasks (custom entities, single/multi classification). 

# References and Resources

- [Python API analysis](https://gist.github.com/kristapratico/b70f6513e25d4f4af5b9866cf278d240#adding-bespoke-methods-on-client)

**Comment by heaths** [comment]
Basically, for each batch operation action the client can use, there should be a corresponding method for an individual operation. Check the Python issue for a good list.
