### ISSUE TITLE
[FEATURE REQ] Support for Docker image 

### ISSUE THREAD

**Issue by ThomasPe** [Azure/azure-sdk-for-net#28068]
### Library name

Vision.CustomVision.Prediction

### Please describe the feature.

We would like to use the Vision.CustomVision.Prediction package to quickly switch between requests against the online & local docker version.

Currently, the SDK sets the BaseUri like this in line 180 of https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitiveservices/Vision.CustomVision.Prediction/src/Generated/CustomVisionPredictionClient.cs:

```BaseUri = "{Endpoint}/customvision/v3.1/prediction";```

That means this is also not editable from the outside to adjust the route.
Unfortunately this path is also not covered by the auto-created docker image that CustomVision.ai lets us download:

```
# Like the CustomVision.ai Prediction service /image route handles either
#     - octet-stream image file 
#     - a multipart/form-data with files in the imageData parameter
@app.route('/image', methods=['POST'])
@app.route('/<project>/image', methods=['POST'])
@app.route('/<project>/image/nostore', methods=['POST'])
@app.route('/<project>/classify/iterations/<publishedName>/image', methods=['POST'])
@app.route('/<project>/classify/iterations/<publishedName>/image/nostore', methods=['POST'])
@app.route('/<project>/detect/iterations/<publishedName>/image', methods=['POST'])
@app.route('/<project>/detect/iterations/<publishedName>/image/nostore', methods=['POST'])
```
 
It would be great if either the docker image was adjusted to route the request correctly that is being created by the SDK or the SDK gives a bit more freedom to the dev to adjust the BaseUrl without hardcoding the version.

**Comment by SaurabhSharma-MSFT** [comment]
@ThomasPe We are looking into it and get back to you for any additional information.

**Comment by SatishBoddu-MSFT** [comment]
Hello @ThomasPe Thanks for reaching out on this topic!

Routing this to service teams' attention!
