### ISSUE TITLE
Unable touse GetDateTime method on an azure table entity

### ISSUE THREAD

**Issue by Jack-e-metron** [Azure/azure-sdk-for-net#28062]
[Enter feedback here]
Method does not function. 
         6 example = table_client.get_entity(partition_key='4_2022',row_key='1009764')
----> 7 example.GetDateTime()

causes error:
AttributeError: 'TableEntity' object has no attribute 'GetDateTime'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 109e3e16-9a14-fcc1-8202-a9ab7e6534a3
* Version Independent ID: b3424377-a692-de47-4ee9-dafb10883ff7
* Content: [TableEntity.GetDateTime(String) Method (Azure.Data.Tables) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.data.tables.tableentity.getdatetime?view=azure-dotnet#azure-data-tables-tableentity-getdatetime(system-string))
* Content Source: [xml/Azure.Data.Tables/TableEntity.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Data.Tables/TableEntity.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @Jack-e-metron.  Thank you for reaching out and we regret that you're experiencing difficulties.   The code snippet that you've shared appears to be Python, as does the error message.   The documentation that you're referencing is for the .NET client library.    Python returns a dict when `get_entity` is called, as described in the [Python docs](https://docs.microsoft.com/python/api/azure-data-tables/azure.data.tables.tableclient?view=azure-python#azure-data-tables-tableclient-get-entity) which would not have a `GetDateTime` method and would surface the error that you're seeing.   

Is it possible that you're referencing the API documentation for the wrong language?
