### ISSUE TITLE
[QUERY] If I use InteractiveBrowserCredentials in my ASP.NET application, why doesn't it pops up the system browser allowing user to select account?

### ISSUE THREAD

**Issue by Trivedi-Ashish** [Azure/azure-sdk-for-net#28076]
### Library name and version

Azure.Identity(1.5.0)

### Query/Question

hi, I have an ASP.NET core application in which I am trying to get browser pop-up to allow user interactively select account.
I am calling InteractiveBrowserCredential.GetToken().
It works in debug mode but when I deploy the application in IIS, it doesn't pops up the browser.

I am wondering if InteractiveBrowserCredential in Azure SDK for .NET is only for WPF, Winform applications?
Is there any way to use it in ASP.NET applications as well?

### Environment

Dev environment:
OS: Windows 10
IDE: Visual Studio 2019 with .net6
Project Type: ASP.NET application
Deployed on IIS

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @Trivedi-Ashish - Yes, interactive credentials like this are meant to be run from client-side applications. Assuming your web application is making calls to other services, there are usually a few different credential models that a web application would employ after the [user authenticates the web app. via AAD](https://docs.microsoft.com/en-us/azure/app-service/configure-authentication-provider-aad) 
- The web application uses its own credentials to make trusted calls to other services
- The web application uses a [managed Identity ](https://docs.microsoft.com/en-us/azure/app-service/tutorial-connect-msi-sql-database?tabs=windowsclient%2Cef%2Cdotnet)to make trusted calls to other services
- The web application uses the logged in user's credentials to make calls to other services in an [On Behalf Of flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)

In the above models, if you want to have users authenticate to your web app as their AAD identities,
