### ISSUE TITLE
[QUERY] Tables CreateIfNotExists Error Logs

### ISSUE THREAD

**Issue by FabianTrottmann** [Azure/azure-sdk-for-net#28084]
### Library name and version

Azure.Data.Tables 12.5.0

### Query/Question

Why does the following code, throw a 409 (conflict) if the table exists. The purpose of this call is to create a table if it dosn't exists. This is not an exception case. It leads to a ton of error messages in application insight (dependency Exceptions). It seems that it is handled by the library, so it does not throw it to the client but it sillt fills the logs. Is this fixed in a further release?

      
`tableClient = new TableClient(new Uri("tableuri"), "mytablename", new DefaultAzureCredential());
        await tableClient.CreateIfNotExistsAsync()
            .ConfigureAwait(false);`

### Environment

Azure Functions dotnet 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @FabianTrottmann  - This is a known issue and is being tracked by https://github.com/Azure/azure-sdk-for-net/issues/25626

We expect to address this in a future release.
