### ISSUE TITLE
[FEATURE REQ] Query to support parameters

### ISSUE THREAD

**Issue by YujunXieODA** [Azure/azure-sdk-for-net#28092]
### Library name

Azure.Monitor.Query

### Please describe the feature.

Use [QueryWorkspaceAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.monitor.query.logsqueryclient.queryworkspaceasync?view=azure-dotnet) as an example, it only accepts a query string.
When I create my query and pass my parameters into a query, I have to do verification to make sure the parameter is valid and basically to avoid a query injection attack(not sure if that's a thing, but you know, this is a query)
Is it possible to implement an overload method to take parameters?
I am seeing some examples here but not for Azure.Monitor.Query
https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/queryparametersstatement?pivots=azuredataexplorer

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by scottaddie** [comment]
The library can't support this feature because the underlying REST API doesn't support query parameters. I've discussed it with the Log Analytics service team that owns the REST API. There are currently no plans to support this feature.
