### ISSUE TITLE
RequestOption can't be found when using Azure Purview Catalog client library for .NET - Version 1.0.0-beta.3

### ISSUE THREAD

**Issue by upton2805** [Azure/azure-sdk-for-net#28117]
I tried to update the Catalog client library to version 1.0-beta.3 but my code is breaking because RequestOption class is not available in Azure.Core or Azure.Core.Experimental libraries.

**Comment by SaurabhSharma-MSFT** [comment]
@upton2805 We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@upton2805 Can you please share the code snippet you are using which breaks with beta3 version ?

**Comment by SaurabhSharma-MSFT** [comment]
@upton2805 Can you please share the required information with code snippet, so that we can look into it. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@upton2805 We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
