### ISSUE TITLE
Enable tracing spans names from convenience methods for LROs

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#28125]
We are confident that this issue for pageables (https://github.com/Azure/azure-sdk-for-net/issues/28124) is applicable to LROs as well.  Desired traces are discussed here.  We need a way to wrap LRO network call spans in a span with the name of the outermost convenience method, to achieve the spans described in https://github.com/azure/autorest.csharp/issues/2136

If it turns out we already have this functionality, we can just close this issue.

**Comment by AlexanderSher** [comment]
Closed by https://github.com/Azure/autorest.csharp/pull/2211
