### ISSUE TITLE
Support for aeg-channel-name header in Azure.Messaging.EventGrid

### ISSUE THREAD

**Issue by mradulmodi** [Azure/azure-sdk-for-net#28126]
Partner Events in Event Grid recommend routing via Channels - https://docs.microsoft.com/en-us/azure/event-grid/partner-events-overview-for-partners#channel. Routing via Channels is to be supported via HTTP Header `aeg-channel-name`

The Microsoft API documentation also mentions use of `aeg-channel-name` in request header for publishing to partner namespaces 
https://docs.microsoft.com/en-us/rest/api/eventgrid/dataplane/publish-cloud-event-events/publish-cloud-event-events

However I wasn't able to see support for specifying this header while creating `EventGridPublisherClient` (https://github.com/Azure/azure-sdk-for-net/tree/Azure.Messaging.EventGrid_4.10.0/sdk/eventgrid/Azure.Messaging.EventGrid). Is this header not yet supported in SDK, if not when is the plan to implement it's support.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
This is available in beta version 4.11.0-beta.1 - https://www.nuget.org/packages/Azure.Messaging.EventGrid/4.11.0-beta.1 via the SendCloudEventOptions.
