### ISSUE TITLE
Avro Serializer Null values issue.

### ISSUE THREAD

**Issue by ArslanAli7** [Azure/azure-sdk-for-net#2812]
Hello there i am new to Avro format, i am using data factory to copy azure sql database data to data lake but i am facing issues when i try to extract the data from an avro file with the column which contains null values inside it, for a while  i searched on the internet and tried AvroSampleOverview sample provided and i tried to change Location data member to accept null values i.e int? with value as null but i faced this exception shouldnt avro support null values is i am doing something wrong here following is the exception i faced `An unhandled exception of type 'System.Runtime.Serialization.SerializationException' occurred in Microsoft.Hadoop.Avro.dll

Additional information: Unexpected null value for the object of type 'System.Nullable`1[System.Int32]'. Please check the schema.`

**Comment by treziac** [comment]
Your schema must be an union of null and int

If you use ReflectionSchemaBuilder to de/serialize, you have to mark your int? as [NullableSchema], it should look like

```
[DataMember]
[NullableSchema]
public int? Value {get; set; }
```

(and optionally [DefaultValue(null)])

which will give the schema
`{"name":"Value","type":["null","int"],"default":null}`

**Comment by ArslanAli7** [comment]
i dont know what schema does Azure Data factory uses for Avro format, but my data is a union of null and int,please let me know if you need some code to have an overview and maybe you can point me out my mistake.

**Comment by tylerfox** [comment]
The Avro SDK is no longer supported by Microsoft.

**Comment by marcwittke** [comment]
if someone stumbles on this, the `AvroPublicMemberContractResolver` has an overload to enable the expected nullable behavior

```csharp
var settings = new AvroSerializerSettings() {
  Resolver = new AvroPublicMemberContractResolver(allowNullable: true) // <---- here
};
var writer = AvroContainer.CreateWriter<T>(stream, settings, Codec.Null);
```
