### ISSUE TITLE
Applying Scopes to TableClient with TokenCredential

### ISSUE THREAD

**Issue by ordinaryorange** [Azure/azure-sdk-for-net#28132]
### Library name and version

Azure.Data.Tables 12.5.0

### Query/Question

Table client constructor has an overload that takes a [TokenCredential](https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet) but I cannot see a best practice way to pass in alternative Authentication Scopes.

**Background** : I'm working on a blazor WASM application which uses [MSAL ](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-overview) for user authentication.
The app uses several API's and so I cannot set multiple default scopes in MSAL, and must request separate tokens for each service.
By using the above mentioned overload, I can delegate the token requesting process to MSAL during service creation.

At the moment I have this working by implementing a custom `TokenCredential` which takes an [IAccessTokenProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.components.webassembly.authentication.iaccesstokenprovider?view=aspnetcore-6.0) the scopes and which overrrides the `GetTokenAsync` method as below.

```
class MsalTokenCredential : TokenCredential
    {
        IAccessTokenProvider _provider = null!;
        string[] scopes = null!;

   public MsalTokenCredential(IAccessTokenProvider MsalProvider, string[] Scopes)
        {
            _provider = MsalProvider;
            scopes = Scopes;
        }

        public override ValueTask<Azure.Core.AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
        {
            var getter = async () =>
            {
                var tro = new AccessTokenRequestOptions();
                tro.Scopes = scopes;
                var atr = await _provider.RequestAccessToken(tro);
                if (atr.TryGetToken(out var token))
                {
                    return new Azure.Core.AccessToken(token!.Value, token!.Expires);
                }
                throw new ApplicationException("Unable to get token for Azure tables");
            };
            return new ValueTask<Azure.Core.AccessToken>(getter());
        }
    }
```
However this discards the `TokenRequestContext` passed to the overload. 

Looking though the source of `TableClient` it appears that internally the scope is defaulted to ["https://storage.azure.com/.default"](https://github.com/Azure/azure-sdk-for-net/blob/0bd2abbf2a07593b3a8605a928ada2184fb7f6b3/sdk/tables/Azure.Data.Tables/src/TableConstants.cs#L10) and so dropping the passed in `TokenRequestContext` is not a huge issue if the above implementation is used.

The only other way I could see of solving the problem was to provide a `Transport` in the [TableClientOptions](https://docs.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclientoptions?view=azure-dotnet) but I didn't attempt that as directly modifying the HttpMessage smelt worse that the above solution.

Whilst the above works for my situation, it feels hacky and leaves me thinking there should be a neater approach. Is there  ?

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Visual Studio 17.1.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ordinaryorange** [comment]
I'm using authentication in Blazor per this [document ](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/standalone-with-microsoft-accounts?view=aspnetcore-6.0).

 I also need to register a couple of services during ASPNET core start up which provide HTTP API access. One of these being Azure tables, another msgraph, and other custom ones. Each needing their own authentication tokens supplied from AzureAD.

 I could not see a way to have `Azure.Data.Tables` silently use underlying MSAL service once the use was logged in. I did have a look at the Azure.Identity implementations but I could not see how to integrate.
I found this [doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/additional-scenarios?view=aspnetcore-6.0). Which suggests injecting an `IAccessTokenProvider` to the service but those token types are not directly consumable from `TableClient` so I wrap it.

Am I doing it all wrong ?

**Comment by christothes** [comment]
Looking again at your example, assuming you already can acquire tokens with your instance of `IAccessTokenProvider` you should be able to grab and use the scope passed by the `TokenRequestContext` as follows:

```c#
var tro = new AccessTokenRequestOptions();
tro.Scopes = requestContext.Scopes;
```

The `TableClient` constructed with your instance of `MsalTokenCredential` will call `GetTokenAsync` with its scopes set and will also handle caching of that token until expiration.

**Comment by ordinaryorange** [comment]
Yes you are correct I can acquire tokens from the `IAccessToeknProvider`. It is supplied from the service container, and initialised into the service container by MSAL during startup.
I can get any token I need from the `IAccessTokenProvider` by giving it a scope, MSAL handles the rest.

The `TableClient` internally will default to a scope of "https://storage.azure.com/.default" so when it calls `GetTokenAsync` the `requestContext` will have that scope.
However I need the scope to be "https://storage.azure.com/user_impersonation"

So that's what I'm doing in in my custom `TokenCredential`. I drop the scope given to me by `TableClient` when it calls `GetTokenAsync` and use the correct scope provided from the ctor of my custom `TokenCredential`
I don't care about the scope from `TableClient` so doing `tro.Scopes = requestContext.Scopes;` as suggested makes no sense.
I very much appreciate the feedback, but I don't feel the issue is understood.

Per my initial query, this all just feels hacky, and my gut tells me there is better way to have `TableClient` interop with the MSAL namespace.
Again, maybe I don't even need to use MSAL and can drop in Azure.Identity to do all the Authentication functions in Blazor but that is not obvious.
Having to use both MSAL and Azure.Identity within the same app also feels like overkill.

**Comment by christothes** [comment]
My apologies for not fully understanding the problem. To clarify, is you app currently configured similar to what is described in [this sample](https://docs.microsoft.com/en-us/aspnet/core/blazor/security/webassembly/hosted-with-azure-active-directory?view=aspnetcore-6.0) and you want to be able to make requests from the server to the Tables service in an [OnBehalfOf flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow)?

**Comment by ordinaryorange** [comment]
Yes my app is configured basically the same as the link you refer to. I'm WASM SPA only (no server), but client side is more or less configured the same in the startup and by using the Authenication components such as `AuthorizeView`.
I'm not well versed in the delineation of the various authentication flows, but [Auth code grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) better describes my scenario here.

**Comment by Roneri75** [comment]
What is the status on this?
Is there a workaround or is it solved in later version of .Net 6?

**Comment by girlpunk** [comment]
@ordinaryorange Thanks for your workaround on this one, do you remember how you got an instance of `IAccessTokenProvider`? Trying to request one from the builder using the code below gives a `Cannot resolve scoped service 'Microsoft.AspNetCore.Components.WebAssembly.Authentication.IAccessTokenProvider' from root provider` exception.

```csharp
builder.Services.AddAzureClients(
    clientsBuilder => clientsBuilder.UseCredential(
            s => new MsalTokenCredential(
                s.GetRequiredService<IAccessTokenProvider>(),
                new[] { "https://storage.azure.com/user_impersonation" }
            )
        )
        .AddTableServiceClient(new Uri("https://mystorageaccount.table.core.windows.net/"))
);
```

**Comment by girlpunk** [comment]
For anyone else finding this issue, don't use AddAzureClients (as that makes a singleton that can't be user-specific). Instead, register like this:

```csharp
builder.Services.AddTransient(
    s => new MsalTokenCredential(
        s.GetRequiredService<IAccessTokenProvider>(),
        new[]
        {
            "https://storage.azure.com/user_impersonation",
        }
    )
);

builder.Services.AddTransient(
    static s =>
        new TableServiceClient(
            new Uri("https://xxx.table.core.windows.net/"),
            s.GetRequiredService<MsalTokenCredential>()
        )
);
```

You can then inject a `TableServiceClient` as usual

**Comment by pallavit** [comment]
@christothes  I am not sure if this is widely used scenario but do you think we should add a sample for this in the SDK?

Given @girlpunk shared the solution here, I will mark this as issue_addressed.
