### ISSUE TITLE
DownloadDirectoryAsync() failure

### ISSUE THREAD

**Issue by UsamaRaf** [Azure/azure-sdk-for-net#28143]
TransferManager.DownloadDirectoryAsync Method to download an Azure file directory from Azure File Storage, always returns status.NumberOfFilesFailed = 'totalNoofFiles'. Even though I can see the files downloaded successfully in the provided destination directory.

Take below code snippet as an example:

// Get temp dir.
string tempDir = "Some Path"';

// Destination directory.
CloudFileDirectory vaultAppLogsDir = "Destination directory";

// Create transfer context.
DirectoryTransferContext directoryTransferContext = new DirectoryTransferContext();

// Create CancellationTokenSource used to cancel the transfer
CancellationTokenSource cancellationSource = new CancellationTokenSource();

// Transfer app logs directory to a local temp folder.
DateTime timeStarted = DateTime.UtcNow;
TransferStatus status = await TransferManager.DownloadDirectoryAsync( destDir, tempDir,
		new DownloadDirectoryOptions() { Recursive = true }, directoryTransferContext,
		cancellationSource.Token );

After executing above code snippet, status.NumberOfFilesFailed always results in 'Total number of files in the directory'. Even though the files are actually downloaded in the tempDir and can be seen with Windows explorer.

**Comment by SaurabhSharma-MSFT** [comment]
@UsamaRaf We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@UsamaRaf I am able to reproduce this and `NumberofFilesFailed` is getting populated even though transfer was successful.
![image](https://user-images.githubusercontent.com/38112130/163080431-26834833-688a-4d1d-8440-fa1de5233088.png)
I am redirecting this to services team to look into this issue.
