### ISSUE TITLE
Confidential Ledger should support auth via with certificates that were used while creating the ledger (non-AAD)

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#28147]
### Library name

Azure.Security.ConfidentialLedger

### Please describe the feature.

Currently the client only supports AAD auth. We should also support simple Certificate auth as described in [this python example](https://github.com/Azure/azure-sdk-for-python/tree/b8a947329a3c5f9578a7b1f7a345d654b76bdce2/sdk/confidentialledger/azure-confidentialledger#using-certificate-authentication)

**Comment by pallavit** [comment]
Assigning this to the confidential ledger team to triage as they see fit.
