### ISSUE TITLE
Semi-optional CancellationToken

### ISSUE THREAD

**Issue by DavidCameron33** [Azure/azure-sdk-for-net#28144]
Whilst I can get it to work in C# _without_ the Token, it seems that it is necessary in VB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddcbc767-2ed7-b376-51fe-34c13fe7b391
* Version Independent ID: 86e0dc6a-aea6-5baa-c6a2-d016ffd7445a
* Content: [BlobContainerClient.Exists(CancellationToken) Method (Azure.Storage.Blobs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.exists?msclkid=27313e0eb99f11ec976b308d9169c6d8&view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs/BlobContainerClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs/BlobContainerClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@DavidCameron33 We are looking into it and get back to you for any additional information.

**Comment by SatishBoddu-MSFT** [comment]
Hello @DavidCameron33 Thanks for the info!

Please add more information on the VB, if any snippets or logs showing the error?

Routing to the Service team for further action!

**Comment by seanmcc-msft** [comment]
@DavidCameron33, we have overloads for every Storage SDK API where CancellationToken is option.  For example - https://github.com/Azure/azure-sdk-for-net/blob/f0d1a30fc0164389c137b8c782901cb214c3c623/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L1573
