### ISSUE TITLE
[QUERY] How to use Azure.Identity instead of AppAuthentication in ADF SDK?

### ISSUE THREAD

**Issue by callmewhy** [Azure/azure-sdk-for-net#28164]
### Library name and version

Microsoft.Azure.Management.DataFactory v5.4.0

### Query/Question

Hi team, recently we are using latest ADF SDK to manage our ADF pipelines.

We hope to use ManagedIdentity to do the auth, and it works with Microsoft.Azure.Services.AppAuthentication, which is legacy already. 

I tried to migrate from AppAuthentication to Azure.Identity according to this doc: [App Authentication to Azure Identity Migration Guidance - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration), but it failed with unknown exception.

Does ADF SDK support Azure.Identity? It would be great if we have some sample code for auth with MI using Azure.Identity.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment]
Hi, @callmewhy 

The Azure.Identity does not support the direct creation of a DataFactoryManagementClient, but it can be built via Microsoft.Rest. Here is an example of using Microsoft.Rest to manage an ADF pipeline.

``` c#
using Azure.Core;
using Azure.Identity;
using Microsoft.Azure.Management.DataFactory;
using Microsoft.Rest;
using NUnit.Framework;
using System;
using System.Threading.Tasks;
```

``` c#
string tenantId = "";
string clientId = "";
string clientSecret = "";
string subscription = "";

// Get AccessToken with Azure.Identity
ClientSecretCredential clientSecretCredential = new ClientSecretCredential(tenantId, clientId, clientSecret);
string[] scopes = { "https://management.core.windows.net/.default" };
TokenRequestContext tokenRequestContext = new TokenRequestContext(scopes, "");
var response = await clientSecretCredential.GetTokenAsync(tokenRequestContext);
string accessToken = response.Token;

// Get an existing ADF pipeline
TokenCredentials bauthCredentials = new TokenCredentials(accessToken);
ServiceClientCredentials credentials = bauthCredentials;
string rgName = "";
string factoryName = "";
string pipelineName = "";
var client = new DataFactoryManagementClient(credentials)
{
    SubscriptionId = subscription
};
var pipeline = await client.Pipelines.GetAsync(rgName, factoryName, pipelineName);
Console.WriteLine(pipeline.Name);
Console.WriteLine(pipeline.Id);
```

**Comment by callmewhy** [comment]
Great, thanks! Do you have a plan to deprecate the usage of AppAuthentication and support Azure.Identity in the future?

**Comment by dvbb** [comment]
> Great, thanks! Do you have a plan to deprecate the usage of AppAuthentication and support Azure.Identity in the future?

Hi, @ArthurMa1978 Can you answer this question?
