### ISSUE TITLE
[QUERY] Load AnalyzedResults with a given a Form Recognizer operation location

### ISSUE THREAD

**Issue by gsandorx** [Azure/azure-sdk-for-net#28165]
### Library name and version

 Azure.AI.FormRecognizer 4.0.0-beta.3

### Query/Question

Hello team! 

Is there a way to send a document processing request (which returns a location URI) and then load the populate an AnalyzedResults object using that URI at a later point or event from a different process? 

Here's my concrete problem:
1. Trigger a document processing request 
2. Send an event/message via a message broker system (e.g. Event Hub or Service Bus). The results URI is passed in the event
3. On the receiving side of the event (which runs on a totally different app), load an AnalyzedResults object with the URI passed via the event (assuming that the document processing operation was completed).  Using the AnalyzedResults class is easier than working with the raw JSON 

I'm looking for a way to implement step 3

Thanks

### Environment

.NET 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @gsandorx. From my understanding, you're trying to start a long-running operation using the service's REST API but you want to consume the result using the .NET SDK.

If that's the case: yes, that's possible. The location URI has the following format:
```
https://{resource-name}.cognitiveservices.azure.com/formrecognizer/documentModels/{model-id}/analyzeResults/{result-id}?api-version={api-version}
```

In the SDK, we store the `{model-id}/analyzeResults/{result-id}` substring as the operation ID. You can extract it and instantiate a new `AnalyzeDocumentOperation` instance like this:

```cs
var operationId = "{model-id}/analyzeResults/{result-id}";
var client = new DocumentAnalysisClient(<resource_uri>, <credential>);
var operation = new AnalyzeDocumentOperation(operationId, client);

// Use it as any other long-running operation
await operation.WaitForCompleteAsync();

AnalyzeResult result = operation.Value;
```

Please let me know if you have any other questions.

**Comment by gsandorx** [comment]
Thanks @kinelski .. this is useful indeed.

Now, just to clarify: I'm looking to start the operation AND consume the results from the .NET SDK. It would just be from two separate processes/tasks. Is that still possible?

**Comment by kinelski** [comment]
@gsandorx Yes, this is actually easier. You won't need to parse the ID. For example, in process 1 you can get the ID directly from the `AnalyzeDocumentOperation` instance:
```cs
var client = new DocumentAnalysisClient(<resource_uri>, <credential>);
var operation = client.StartAnalyzeDocument(...);
string operationId = operation.Id;

// Send 'operationId' to another process/task
```

In process 2, you can do the same I suggested above:
```cs
var operationId = /*Get ID from another process*/;
var client = new DocumentAnalysisClient(<resource_uri>, <credential>);
var operation = new AnalyzeDocumentOperation(operationId, client);

// Use it as any other long-running operation
await operation.WaitForCompleteAsync();

AnalyzeResult result = operation.Value;
```

Does this solve your problem?

**Comment by gsandorx** [comment]
Yes, it does. Thanks so much!

(it may be worth adding these code snippets as examples in the official doc. I'm sure more ppl will have the same question)
