### ISSUE TITLE
[BUG] graphClient.Subscriptions

### ISSUE THREAD

**Issue by Vevish** [Azure/azure-sdk-for-net#28166]
### Library name and version

Microsoft Graph 4.24

### Describe the bug

GraphServiceClient graphClient = new GraphServiceClient( authProvider );
var subscriptions = await graphClient.Subscriptions
	.Request()
	.GetAsync();

returns subscriptions as null 

### Expected behavior

Should list all subscriptions 

### Actual behavior

@odata.context=https://graph.microsoft.com/v1.0/$metadata#subscriptions
value

### Reproduction Steps

GraphServiceClient graphClient = new GraphServiceClient( authProvider );
var subscriptions = await graphClient.Subscriptions
	.Request()
	.GetAsync();

### Environment

Console Core application
Azure Identity 1.6.0
Microsoft Graph 4.24
dotnet 6.0 Windows 10

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Graph` package is maintained as [#1309](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1309).

**Comment by Stordlord** [comment]
It under review
