### ISSUE TITLE
[Investigate]: Republish Hyak ClientRuntime and tools to target .Net Core (NetStandardLibrary 1.6.1) 

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2816]
### Description

Locally rebuild and republish runtime packages and one Hyak library (HDInsight) to support .NetCore build.

Verify that these packages can be consumed in a NetCore VS2017 app.

If this works, publish the libraries and update the netcore libraries to match

**Comment by cormacpayne** [comment]
List of services to update:
- Automation
- HDInsight
- SiteRecovery
- Sql**
- StreamAnalytics

** - maybe

**Comment by cormacpayne** [comment]
Packages to update:

- Hyak.Common
    - [Azure/hyak-common](https://github.com/Azure/hyak-common)
    - Latest version: [1.1.0](https://www.nuget.org/packages/Hyak.Common/)
- Microsoft.Azure.Common
    -[Azure/azure-sdk-for-net (master)](https://github.com/Azure/azure-sdk-for-net/tree/master)
    - Latest version: [2.1.0](https://www.nuget.org/packages/Microsoft.Azure.Common/)

**Comment by cormacpayne** [comment]
Changes merged into `HyakNETCore` branch and published to NuGet.
