### ISSUE TITLE
Set custom domain for app service

### ISSUE THREAD

**Issue by joostmeijles** [Azure/azure-sdk-for-net#28168]
### Library name and version

Azure.ResourceManager.AppService

### Query/Question

How do I add a custom domain to an app service?

The corresponding URL in the Azure portal is: `https://portal.azure.com/<my>.onmicrosoft.com/resource/subscriptions/<id>/resourceGroups/<resource group>/providers/Microsoft.Web/sites/<app name>/domainsandssl`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
@joostmeijles Thank you for reaching us.
For your request of add a custom domain to an app service,you could use our newly released sdk :
[Azure.ResourceManager.AppService](https://www.nuget.org/packages/Azure.ResourceManager.AppService/1.0.0-beta.2).
For the detailed steps, you could refer to this 
![image](https://user-images.githubusercontent.com/88413158/164413715-eb0208a3-eefd-45a5-9daf-21dc3c326977.png)
GetBasicAppServiceDomainData just like this:
![image](https://user-images.githubusercontent.com/88413158/164414295-4046ae67-c63f-4a07-96af-f3423b5ae25b.png)

**Comment by joostmeijles** [comment]
@jsquire @mcgallan any update on an ETA?

**Comment by mcgallan** [comment]
Thank you for your feedback. I'm sorry to reply to you after such a long time. For the two questions you mentioned,
1.You can add a DNS record as follows:
![image](https://user-images.githubusercontent.com/88413158/167377505-46b7324f-2cb5-42e4-8fb0-0d309fd57601.png)
in AppServiceDomainData, there is ManagedHostNames 
![image](https://user-images.githubusercontent.com/88413158/167375471-04d79a98-b3ad-4974-8e92-11ccb7ff9dda.png)
for HostName, 
![image](https://user-images.githubusercontent.com/88413158/167376171-978c5bcf-6605-4f81-af72-ad9701ca2ffa.png)
2.For how to create a SSL binding for a certain subdomain on your app service, you could refer to this
ArmClient client = new ArmClient(new DefaultAzureCredential());
var subscription = (await client.GetSubscriptions().GetAsync("subid")).Value;
var resourceGroup = (await subscription.GetResourceGroups().GetAsync("appservicetest")).Value;
var website = (await resourceGroup.GetWebSiteAsync("28168")).Value;

var bindingCollection = website.GetSiteHostNameBindings();
var data = new HostNameBindingData()
{
SiteName = "SiteName",
DomainId = "Domain Id",
AzureResourceName = "ResourceName",
AzureResourceType = Azure.ResourceManager.AppService.Models.AzureResourceType.Website,
CustomHostNameDnsRecordType = Azure.ResourceManager.AppService.Models.CustomHostNameDnsRecordType.CName,
HostNameType = Azure.ResourceManager.AppService.Models.HostNameType.Verified,
SslState = Azure.ResourceManager.AppService.Models.SslState.IPBasedEnabled,
Thumbprint = "Thumbprint",
};
var binding = (await bindingCollection.CreateOrUpdateAsync(Azure.WaitUntil.Completed, "hostname", data).ConfigureAwait(false)).Value;
I hope my reply can help you
