### ISSUE TITLE
Connect to KeyVault in Azure China

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-sdk-for-net#28170]
### Library name and version

Azure.Security.KeyVault.Certificates 4.2.0

### Query/Question

I use this code for Azure KeyVault Service and it works well with a regular Azure

```
    ClientSecretCredential clientCredential = new(options.KeyVaultTenantId, options.KeyVaultClientId, options.KeyVaultClientSecret);
    KeyVaultCertificateWithPolicy rootCertificate = new CertificateClient(vaultUri, _clientCredential).GetCertificate(_rootCertificateId).Value;
```

however, I need to connect to Azure China. The code fails with message:

> AADSTS90002: Tenant 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' not found.
> Check to make sure you have the correct tenant ID and are signing into the correct cloud. 
> Check with your subscription administrator, this may happen if there
> are no active subscriptions for the tenant

I found [this][1] but I don't know where to set `ActiveDirectoryServiceSettings.AzureChina` in my code. Please suggest

```
    <PackageReference Include="Azure.Identity" Version="1.5.0" />
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.2.0" />
    <PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.2.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.2.0" />
```

  [1]: https://chowdera.com/2021/01/20210120055654842j.html

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
You'll want to set the `ClientSecretCredentialOptions.AuthorityHost` when creating the credential like so:

```csharp
ClientSecretCredential clientCredential = new(options.KeyVaultTenantId, options.KeyVaultClientId, options.KeyVaultClientSecret)
{
  AuthorityHost = AzureAuthorityHosts.AzureChina,
};
```

See https://docs.microsoft.com/dotnet/api/azure.identity.tokencredentialoptions.authorityhost?view=azure-dotnet#azure-identity-tokencredentialoptions-authorityhost for more information.

**Comment by Marusyk** [comment]
@heaths thanks but
![image](https://user-images.githubusercontent.com/9221694/163046125-c6e95a9c-7c10-4feb-8d11-cba1ac2e1640.png)

**Comment by heaths** [comment]
Apologies, but I gave you the wrong code. It should be:

```csharp
ClientSecretCredential clientCredential = new(
    options.KeyVaultTenantId,
    options.KeyVaultClientId,
    options.KeyVaultClientSecret,
    new ClientSecretCredentialOptions()
    {
        AuthorityHost = AzureAuthorityHosts.AzureChina,
    });
```

**Comment by Marusyk** [comment]
It works. Thank you.
Is it documented somewhere?

**Comment by heaths** [comment]
In the link I provided above: https://docs.microsoft.com/dotnet/api/azure.identity.tokencredentialoptions.authorityhost?view=azure-dotnet#azure-identity-tokencredentialoptions-authorityhost

Using a different environment (cloud) is similar across our different language SDKs. Everything defaults to AzureCloud because that is, by far, the most used cloud. Same for the `az` CLI and `Az` PowerShell cmdlets.
