### ISSUE TITLE
Batch complete not available

### ISSUE THREAD

**Issue by FireAndIceFrog** [Azure/azure-sdk-for-net#28199]
I am trying to use the ServiceBusReceiver from the packages [here ](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceiver.completemessageasync?view=azure-dotnet) and Ive noticed there is no batch operations except for read and send.

Is there a reason we arent given this option? 

Ive tried several methods, but the underlying problem is that the requests only ever send one message (for a batch of 9k messages this is 9k queries!) so its very slow.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0adc2721-d8e1-adb7-d99f-a6307882e3c4
* Version Independent ID: f7c2edbf-0b8a-ec2f-e0e8-26d896a21f60
* Content: [ServiceBusReceiver.CompleteMessageAsync(ServiceBusReceivedMessage, CancellationToken) Method (Azure.Messaging.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceiver.completemessageasync?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.ServiceBus/ServiceBusReceiver.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus/ServiceBusReceiver.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by JoshLove-msft** [comment]
This is not included in the library because the service (when using AMQP) doesn't actually support batch completion. Please see https://github.com/Azure/azure-sdk-for-net/issues/7921 for more details.
