### ISSUE TITLE
[QUERY] Which AccessTiers are queried by the FindBlobsByTagsAsync method on the BlobContainerClient

### ISSUE THREAD

**Issue by apoutney** [Azure/azure-sdk-for-net#28205]
### Library name and version

Azure.Storage.Blobs 12.11.0

### Query/Question

Does the FindBlobsByTagsAsync method return results for blobs in the archive tier?  And if so is there anyway to filter those out?

**Comment by SaurabhSharma-MSFT** [comment]
@apoutney We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@apoutney Result includes Archive tier blobs however I do not think it can be filtered.

@blueww Do you have any idea on this one.

**Comment by seanmcc-msft** [comment]
This API doesn't filter by Access Tier.

**Comment by SaurabhSharma-MSFT** [comment]
Thanks @seanmcc-msft.
@apoutney Please let us know if you have any questions else we will proceed with the closure of this issue. 
Thanks,
Saurabh

**Comment by SaurabhSharma-MSFT** [comment]
@apoutney We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
