### ISSUE TITLE
Poor List API design in ResourceManagementClient

### ISSUE THREAD

**Issue by TarasRoshko** [Azure/azure-sdk-for-net#2820]
`List(Async)` returns a page but does not accept a page hence can not be used by itself to fetch all the pages, requires to use `List(Async) `+ separate while loop with `ListNext(Async)`

1) `List` should be single API accepting a page, `Page.Start/First` (preferably) or `null` for first page, previous result allows to loop
2) Should provide an overload returning `IEnumerable` fetching page by page so every single person using this API does not have to re implement this common operation

`Microsoft.Azure.Management.ResourceManager version=1.4.0-preview`

**Comment by hovsepm** [comment]
@TarasRoshko This is by design. Please re-open this issue in https://github.com/Azure/autorest since it is a part of auto generated logic and is common for all the SDK packages.
