### ISSUE TITLE
[BUG] Tables: Query with a Type that contains a decimal returns an incorrect value

### ISSUE THREAD

**Issue by Looooooka** [Azure/azure-sdk-for-net#28208]
### Library name and version

Azure.Data.Tables 12.5.0.0

### Describe the bug

Using Query or QueryAsync with a Type that contains a decimal returns an instance with that decimal property being set to 0.
Writing it works as expected and the value can be seen with azure storage explorer.

If I change the type to double and request the existing record(which was saved with a decimal property type) the instance contains the expected value.

### Expected behavior

Querying should return an instance of the object with the same values as they were written to the datatable

### Actual behavior

Querying returns an instance of the object where decimal properties are set to 0

### Reproduction Steps

class sample:
```c#
internal class CustomTableEntity : Azure.Data.Tables.ITableEntity
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; }


        public CustomTableEntity() { }

    }

    internal class ForexEntity : CustomTableEntity
    {
        public string Currency { get; set; }
        public decimal ForexRate { get; set; }
        public DateTime? ForexTimestamp { get; set; }
        public DateTime? recDateTime { get; set; }
        public ForexEntity() { }

    }
```

code sample:

```c#
            var tableClient = tableServiceClient.GetTableClient(forexTable);

            var status = tableClient.CreateIfNotExists();
            var result = tableClient.Query<ForexEntity>(filter: $"PartitionKey eq '{partitionKey}'").FirstOrDefault();
```

Tested with unit under Net6 and Net 4.6.2
Decimals worked just fine with the old API (Microsoft.WindowsAzure.Storage).
Is there some magic serialization option one needs to turn on?
Because the odata response seems perfectly ok:
            
```c#
{"odata.metadata":"https://lukadevelopment.table.core.windows.net/$metadata#Forex","value":[{"odata.etag":"W/\"datetime'2022-04-14T13%3A29%3A03.0553874Z'\"","PartitionKey":"EUR","RowKey":"2517523578601951356","Timestamp":"2022-04-14T13:29:03.0553874Z","Currency":"EUR","ForexRate":1.1,"recDateTime@odata.type":"Edm.DateTime","recDateTime":"2022-04-14T13:28:57.8103894Z"}]}
```
          

### Environment

Visual studio 2022 (64-bit) Version 17.1.3
Windows 11 Pro 21H2 22000.593
Tested with Net 6 and Net 4.6.2

**Comment by Looooooka** [comment]
Looking at the code at
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/src/Extensions/TablesTypeBinder.cs
it appears the TableTypebinder implementation doesn't support decimal at all so the only fix right now is to query using Azure.Data.Tables.TableEntity Type and then manually set the fields using the keys in the dictionary, but then you have to pretty much handle conversions from DateTimeOffset to Datetime and everything else this library does.
Hopefully, decimal support gets added.

**Comment by christothes** [comment]
Hi @Looooooka The table storage service doesn't explicitly support decimal values and stores them as `double`. Although we could handle converting them under the covers, we'd potentially lose precision on roundtripping the values. 

For example, if you set a value of decimal.MaxValue (79228162514264337593543950335) it goes to the service as `7.9228162514264338E+28`

So I'm not sure we could properly support decimal values with this limitation of the service itself.

**Comment by Looooooka** [comment]
> Hi @Looooooka The table storage service doesn't explicitly support decimal values and stores them as `double`. Although we could handle converting them under the covers, we'd potentially lose precision on roundtripping the values.
> 
> For example, if you set a value of decimal.MaxValue (79228162514264337593543950335) it goes to the service as `7.9228162514264338E+28`
> 
> So I'm not sure we could properly support decimal values with this limitation of the service itself.

I understand. Luckily we just use this part for weiting/fetching so worst case scenario we can save it as a string and handle the conversion on our side.
Thank you for the update.

**Comment by Looooooka** [comment]
Just adding this if anyone else stumbles upon this issue.

The old NET Api seem to store decimals as strings and the conversion back seems to work as well:

User-Agent: Azure-Storage/9.3.2 (.NET CLR 4.0.30319.42000; Win32NT 10.0.22000.0)
{"Currency":"CCC","ForexTimestamp":"2022-04-15T10:51:32.7954931Z","ForexTimestamp@odata.type":"Edm.DateTime","recDateTime":"2022-04-15T10:51:33.2747770Z","recDateTime@odata.type":"Edm.DateTime","ForexRate":"79228162514264337593543950335"}


and it is returned as a string as well:

{"odata.metadata":"https://lukadevelopment.table.core.windows.net/$metadata#Forex","value":[{"odata.etag":"W/\"datetime'2022-04-15T10%3A51%3A34.8811723Z'\"","PartitionKey":"CCC","RowKey":"2517522809067252229","Timestamp":"2022-04-15T10:51:34.8811723Z","Currency":"CCC","ForexRate":"79228162514264337593543950335","ForexTimestamp@odata.type":"Edm.DateTime","ForexTimestamp":"2022-04-15T10:51:32.7954931Z","recDateTime@odata.type":"Edm.DateTime","recDateTime":"2022-04-15T10:51:33.274777Z"}]}

serialization/deserialization just works

The new one posts it as numeric
User-Agent: azsdk-net-Data.Tables/12.5.0 (.NET Framework 4.8.4470.0; Microsoft Windows 10.0.22000 )

{"Currency":"CCC","ForexRate":79228162514264337593543950335,"ForexTimestamp":"2022-04-15T10:56:49.8992092Z","ForexTimestamp@odata.type":"Edm.DateTime","recDateTime":"2022-04-15T10:56:49.9002045Z","recDateTime@odata.type":"Edm.DateTime","PartitionKey":"CCC","RowKey":"2517522805900997954"}

and returns it as a double and then fails to properly convert it to a decimal(which would fail because of the accuracy anyway)
{"odata.metadata":"https://lukadevelopment.table.core.windows.net/$metadata#Forex","value":[{"odata.etag":"W/\"datetime'2022-04-15T10%3A56%3A51.9184491Z'\"","PartitionKey":"CCC","RowKey":"2517522805900997954","Timestamp":"2022-04-15T10:56:51.9184491Z","Currency":"CCC","ForexRate":7.9228162514264338E+28,"ForexTimestamp@odata.type":"Edm.DateTime","ForexTimestamp":"2022-04-15T10:56:49.8992092Z","recDateTime@odata.type":"Edm.DateTime","recDateTime":"2022-04-15T10:56:49.9002045Z"}]}

I'm thinking fixing the libraries to post decimals as text would be the best fix since that appears to be what the old libraries were doing. 
For me...I'm just going to use a string backingfield marked with datamembers and add ignoredatamember to the decimal fields for now

**Comment by christothes** [comment]
> I'm thinking fixing the libraries to post decimals as text would be the best fix since that appears to be what the old libraries were doing.

The problem with this approach is that queries for the value would be for the wrong type. The filter syntax for a string value differs from a numeric value (ex. filter `Currency eq '1,23'` vs `Currency eq 1.23`), so if developers didn't know that decimals were opaquely being converted to and from string, it would cause lots of confusion.

The problem is even worse with the filter expression syntax, because there is no obvious way to work around this:

`Query<Foo>(r => r.Currency == 1.23)` gets translated to `Currency eq 1.23` which will never return a result.

If the code outside the client does this conversion then at least it is clear what is happening.

**Comment by Looooooka** [comment]
> > I'm thinking fixing the libraries to post decimals as text would be the best fix since that appears to be what the old libraries were doing.
> 
> The problem with this approach is that queries for the value would be for the wrong type. The filter syntax for a string value differs from a numeric value (ex. filter `Currency eq '1,23'` vs `Currency eq 1.23`), so if developers didn't know that decimals were opaquely being converted to and from string, it would cause lots of confusion.
> 
> The problem is even worse with the filter expression syntax, because there is no obvious way to work around this:
> 
> `Query<Foo>(r => r.Currency == 1.23)` gets translated to `Currency eq 1.23` which will never return a result.
> 
> If the code outside the client does this conversion then at least it is clear what is happening.

Which now makes me wonder what filtering did when one tried filtering decimals with the old version...
"luckily" we're not so a backing text field is a fix for our current problem and I just told everyone to mind the issues with decimals if they're working with azure datatables.
Seeing as how the api throws an exception when one tries using datetime not in UTC format perhaps throwing an exception with decimals might be acceptable as well since it would force the developer to use doubles if possible or use a similar cheap trick I used if filtering by that field wasn't a requirement.
