### ISSUE TITLE
Adding a metadata value with space at start causes Blob upload to fail with authentication error - MAC signature found in the HTTP request is not the same as any computed signature

### ISSUE THREAD

**Issue by ak37165** [Azure/azure-sdk-for-net#28211]
When uploading a blob using a metadata value that has spaces at start (such as using code below):

```
// blobName is any valid blobname such as "sample.txt" and fileStream is some stream with some valid blob content (say text)
BlobClient blobClient = container.GetBlobClient(blobName);
var headers = new BlobHttpHeaders
                {
                    ContentType = "application/octet-stream"            
                };

var blobUploadOptions = new BlobUploadOptions
            {
                HttpHeaders = headers,
                Metadata = new Dictionary<string, string>({"keyname", "  value with space at start"});
            };

            await blobClient.UploadAsync(fileStream, blobUploadOptions);
```

the upload fails with error:
```
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
		ErrorCode: AuthenticationFailed
		
		Additional Information:
AuthenticationErrorDetail: The MAC signature found in the HTTP request 'Q0NXCFOX0S/0KbIYEmwBdma1cf+42H420hxijpw43kg=' is not the same as any computed signature.
```

**Using Azure.Storage.Blobs 12.8.3**

We encountered this error because we were storing a user assigned file name in the blob metadata (the blob-name itself did not use the user assigned file name) and Mac users sometimes have spaces in the file name at the beginning.

**Comment by SaurabhSharma-MSFT** [comment]
@ak37165 We are looking into it and get back to you for any additional information.

**Comment by SatishBoddu-MSFT** [comment]
Hello @ak37165 Thanks for reaching out on this issue!

Looks like the Azure portal is not allowing any Values starting with spaces/// , It will allow the users to enter the values starting with space but after saving the record--> the service is trimming white spaces!!!!

So the Azure portal clearly shows that the key Values can't start with white spaces!
![image](https://user-images.githubusercontent.com/62923178/163495128-c2f1913f-98f2-41c2-91a8-ff001c6dce98.png)

![image](https://user-images.githubusercontent.com/62923178/163494954-fb384cbd-fa93-47be-97ad-6fe53b3279c4.png)
Yes, the SDK throws the error and this error message is not particularly helpful for debugging this issue, but I think the White Spaces are not allowed in leading or Trailing positions.[Ref1 ](https://github.com/Azure/azure-storage-net/issues/950), [Ref2](https://github.com/Azure/azure-storage-java/issues/341#issuecomment-405406833)

![image](https://user-images.githubusercontent.com/62923178/163495302-b4305413-7d40-4df5-9e1e-8d2601327dc4.png)

**Workaround:**
Please convert your Metadata value to base64 Encoded form while writing and Decode them when you are reading!
Encoding & Decoding preserves the white spaces!
![image](https://user-images.githubusercontent.com/62923178/163496117-b257f8be-0139-4d5a-87fe-f78ec9136d20.png)

**Comment by ak37165** [comment]
Thank you for the suggestion. However, it’s worth noting that the Azure JavaScript SDK does not have this issue. We can set metadata values with spaces when uploading directly from the browser (using SAS tokens issued by the server). 

For some of our scenarios the browser must upload to our server and then the server uploads to the Azure blob storage (using the .net SDK). Here the spaces cause an issue (maybe because the MAC computed by the sdk does not include the spaces while the server computed MAC does).

**Comment by compgumby** [comment]
This bit me too setting the metadata through Azure.Storage.Blobs. Took FOREVER to figure out why... ended up being a trailing space in the value of one of my key/value properties. Hard to spot when you don't know to look for it.
