### ISSUE TITLE
[Text Analytics] Updates/Renames for Custom Text and Language

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk-for-net#28213]
### Library name

Azure.AI.TextAnalytics

### Please describe the feature.

The service team requested the updates/renames documented in https://github.com/Azure/azure-sdk-for-js/issues/21406#issue-1204786325

**Comment by heaths** [comment]
Double check that these are still accurate. Sounds like there might have been since changes since this was filed. Talk with others in the v-team. Could we add the `x-ms-client-name` and/or `x-ms-enum` so it's available to everyone.

**Comment by heaths** [comment]
Having checked over all those renames from the comment and based on internal conversations - specifically, we'll stick with "CustomEntities" not "CustomNamedEntities" (cc @kristapratico @mssfang) - all these are already complete with many done in swagger itself.
