### ISSUE TITLE
Microsoft.Identity.Client or Azure.Identity

### ISSUE THREAD

**Issue by GermanEZI** [Azure/azure-sdk-for-net#28222]
Do we keep using Microsoft.Identity.Client or are we intended to migrate to Azure.Identity in the future?

I've found configuring my Graph API apps using Azure.Identity to be a simpler process.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cc2d3b0-630d-0634-81de-510e05141e3e
* Version Independent ID: 95854434-cd66-df0e-9070-dd01be52f7c9
* Content: [Microsoft.Identity.Client Namespace - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client?view=azure-dotnet)
* Content Source: [xml/ns-Microsoft.Identity.Client.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.Identity.Client.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Azure.Identitiy uses Microsoft.Identitiy.Client internally but provides a set of abstractions that are consistent among all of the [latest Azure SDK client packages.](https://azure.github.io/azure-sdk/#net)

**Comment by GermanEZI** [comment]
> Azure.Identitiy uses Microsoft.Identitiy.Client internally but provides a set of abstractions that are consistent among all of the [latest Azure SDK client packages.](https://azure.github.io/azure-sdk/#net)

Thanks!  Exactly what I needed.

**Comment by GermanEZI** [comment]
Thanks.  I'm switching to Azure.Identity.  It's much easier to use.
