### ISSUE TITLE
[BUG] Random exceptions: Unauthorized access. 'Listen' claim(s) are required to perform this operation. 

### ISSUE THREAD

**Issue by bbieniek** [Azure/azure-sdk-for-net#28223]
### Library name and version

SDK: azurefunctions: 4.1.3.17473

### Describe the bug

Hi,

We have a few ServiceBus triggers that listen to Subscriptions on two separate Service Buses.
We use ManagedIdentity authentication with correct roles: Sender, Receiver set.
The triggers work fine in general.
It just happens that randomly, out of a sudden, the Service Bus triggers cause exceptions.
This burst of exceptions can be between 10 to 500.

### Expected behavior

No random exceptions

### Actual behavior

Random exceptions:
Unauthorized access. 'Listen' claim(s) are required to perform this operation. 
![image](https://user-images.githubusercontent.com/10694177/163586219-5b9d9a67-2eff-4863-b358-e10a2852d7ab.png)
![image](https://user-images.githubusercontent.com/10694177/163586270-f5ebfc76-c8af-4eec-a6b6-3c65ed00256f.png)

### Reproduction Steps

.NET 6.0 Project
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="4.2.1" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />

### Environment

Azure Dotnet Isolated project
Azure SDK: azurefunctions: 4.1.3.17473
.NET SDK: 6.0.200

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @bbieniek,
To help us troubleshoot this issue, can you include the version of the Service Bus extension you are using? The logs seem to indicate that you are using version 7.3.0 of Azure.Messaging.ServiceBus, but version 5.0.0 of Microsoft.Azure.WebJobs.Extensions.ServiceBus depends on 7.4.0 or higher. So I'm curious what the version story is here.

Also, it would be helpful if you could include your function code as well.

**Comment by bbieniek** [comment]
Function code:

```
[Function("DownloadDocuments")]
    public async Task RunAsync(
        [ServiceBusTrigger(Constants.DownloadDocumentQueueName, Connection = Constants.ConnectionString)]
        DownloadDocumentsDto message)
    {
        var command = new DownloadDocumentsCommand(message);

        var commandResult = await ExecuteCommand(command);

        if (commandResult.IsFailed)
            await DispatchErrors(command.GetType().ToString(), message.ApplicationId, commandResult.Errors);
    }
```

I was surprised by the 7.3.0 version of the Azure.Messaging.ServiceBus package.
We don't reference it anywhere on our code and I thought that this may be a reference of Azure.Sdk?

**Comment by JoshLove-msft** [comment]
Thanks for that information. I'm still not seeing the version of the extensions package that you are using. That would be the Microsoft.Azure.WebJobs.Extensions.ServiceBus package. Can you let us know what version you are using?

**Comment by joymnd** [comment]
@JoshLove-msft azure function prj has the following list of dependencies. Please let me know if that helps 
![image](https://user-images.githubusercontent.com/44874461/164306336-b93d2b0c-2924-4dd8-9b7f-adcb3ce3d6ca.png)

**Comment by bbieniek** [comment]
@JoshLove-msft as mentioned above, we do not use WebJobs. This is dotnet-isolated project, so we use Microsoft.Azure.Functions.Worker.* packages.

**Comment by bbieniek** [comment]
@JoshLove-msft OK, looks like we have found the issue.
When creating the Function App, we granted permission to the Function App itself and to the service bus (Sender, Receiver) roles.
We first deploy the app to the rollback slot.
Then the slot is swapped to the production slot.
The rollback slot service bus triggers are disabled on the rollback slot via Configuration setting.

After we have granted the permission of Sender, Receiver to the Function App rollback slot, we no longer receive the exception.
I think that the scenario was that:
1) The configuration settings are swapped between production and rollback slot.
2) The service bus trigger is activated.
3) The managed identity is updated.
For a few hundred milliseconds, the service bus trigger was running on the old identity and therefore we have been receiving lots of exceptions that were logged every few milliseconds.

This was pretty difficult to find and doesn't seem to be documented well.

There are remaining questions though:
1) Can the documentation be updated to remind us to assign the necessary permissions to the slots as well.
2) Does the service bus trigger have to log the exceptions every few milliseconds? In one instance, it has logged over 2 million exceptions, resulting in reaching the capacity of app insights.
3) When the slot swap operation occurs, can the managed identity be handled in a 'smart' way so that it does not log hundreds of exceptions?

**Comment by JoshLove-msft** [comment]
Thanks for that information @bbieniek!

To answer your questions:
1. Yes, we can improve the managed identity docs to refer to the fact that permissions need to account for different deployment slots as well.
2 & 3. Are you using very high concurrency (MaxConcurrentCalls option)? That could explain the number of exceptions you are seeing. I think we could potentially handle this error scenario better so that when we get a flood of this specific exception, we back off for a longer time, and scale down the concurrency temporarily.

**Comment by bbieniek** [comment]
1. In our case, there are two slots of the function app. Production and rollback. The issue occurred when the 'rollback' slot was not granted the roles to access Service bus. The identity of the function app had the roles assigned correctly.

This is the code that uses FluentAPI to grant the roles to the slot:
```
private static async Task AssignRoleToSlot(IAzure azureConnection, IFunctionDeploymentSlot slot, IServiceBusNamespace serviceBusNamespace, string roleName)
    {
        var accessManagement = azureConnection.AccessManagement;

        var roleDefinitions = await accessManagement.RoleDefinitions
            .ListByScopeAsync(serviceBusNamespace.Id);

        var requestedRole = roleDefinitions.SingleOrDefault(x => x.RoleName == roleName);
        if (requestedRole is null)
        {
            throw new ArgumentException("Role definition not found", nameof(roleName));
        }

        if (!accessManagement.RoleAssignments.ListByScope(serviceBusNamespace.Id)
                .Any(x => x.PrincipalId == slot.SystemAssignedManagedServiceIdentityPrincipalId
                          && x.RoleDefinitionId == requestedRole.Id))
        {
            var slotServicePrincipal = await accessManagement.ServicePrincipals
                .GetByIdAsync(slot.SystemAssignedManagedServiceIdentityPrincipalId);

            await accessManagement.RoleAssignments
                .Define(Guid.NewGuid().ToString())
                .ForServicePrincipal(slotServicePrincipal)
                .WithRoleDefinition(requestedRole.Id)
                .WithScope(serviceBusNamespace.Id)
                .CreateAsync();
        }
    }
```

This is how it looks in IAM:
![image](https://user-images.githubusercontent.com/10694177/165595047-e70104bd-2c91-4011-955a-9c8e56c1b2da.png)


3. No, we do not use this option. Backing off sounds like a great idea.

**Comment by JoshLove-msft** [comment]
Created https://github.com/Azure/azure-sdk-for-net/issues/29290 to track the enhancement to back off retries for these errors.
