### ISSUE TITLE
Ensure new release of WebJobs SDK with property shadowing fix is released

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#28235]
Need to update the repo dependencies to be on a version of Microsoft.Azure.WebJobs that contains this fix - https://github.com/Azure/azure-webjobs-sdk/commit/9cce286297db88dadefabb0284bb085add50bcec

Tested 3.0.32 and it does not seem to contain the fix.

**Comment by jsquire** [comment]
According to the Functions team, this is expected to be included in the 3.0.33 release.   _([ref](https://github.com/Azure/azure-webjobs-sdk/pull/2831#issuecomment-1051117450))_
