### ISSUE TITLE
Enable setting trace suppression via ClientDiagnostics

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#28240]
Call through to ClientOptions.DiagnosticOptions.IsNestedTraceSuppressionEnabled

 https://github.com/Azure/azure-sdk-for-net/pull/28066/files#diff-be372afcb3d72f4c9117fde61c8892937a9481d845e10ffdc08360e6744a3d6fR35

**Comment by lirenhe** [comment]
Close as this is already completed
