### ISSUE TITLE
.NET Core v2 Azure Function EventHub PartitionKey doesn't seem to work

### ISSUE THREAD

**Issue by josh-endries** [Azure/azure-sdk-for-net#28245]
I'm unable to effectively set the PartitionKey property when using an Azure Function v2 (.NET Core).

Firstly, I am unsure *how* I am correctly supposed to set the PartitionKey property. I initially used the new Microsoft.Azure.WebJobs.Extensions.EventHubs package and its Microsoft.Azure.EventHubs.EventData class, however there is no PartitionKey property on that class. There is a PartitionKey property in the SystemProperties member on EventData, however SystemProperties and its PartitionKey property are both read-only, so I can't figure out how to set it from that package. Using the "old" Microsoft.ServiceBus.Messaging.EventData class, I can set PartitionKey on the object, however it doesn't seem to have any effect.

I'm assuming that I am doing something wrong but I can't figure out what. I am expecting that when I set the same PartitionKey value, it gets hashed and modded or something and should cause the message to be assigned to the same partition every time (as described in the documentation).

This is the Function code (using the "old" EventData class):

    public static class Function1
    {
        [FunctionName("Function1")]
        public static async Task Run(
            [TimerTrigger("0 */1 * * * *")] TimerInfo myTimer,
            [EventHub("events", Connection = "ConnectionString")] IAsyncCollector<EventData> results,
            CancellationToken token,
            TraceWriter log
        )
        {
            var ed1 = new EventData(Encoding.UTF8.GetBytes("test"));
            ed1.PartitionKey = "0";
            await results.AddAsync(ed1);
        }
    }

I've tried various partition keys (non-numeric, long, short, ...) but that didn't make a difference. The function runs every minute, es expected, but this is what I see in my client, which just dumps out the metadata:

![untitled](https://user-images.githubusercontent.com/1500571/37915204-fc669ad8-30e6-11e8-9c32-c5c6ae8a0e67.png)

This shows two Function invocations a minute apart. Note that the first line of each list item includes the partition on which the message was received, and that it alternates from partition 1 to partition 0, even though the PartitionKey property is always "0". If I change PartitionKey to "1", it updates in the data and stays consistent, but the reader-partition reporting the event keeps alternating the same as it does in the image. I would expect these partition IDs to remain the same if the messages were received on the same partition.

This is the code that displays the messages:

    public async Task ProcessEventsAsync(PartitionContext context, IEnumerable<EventData> messages) {
        await processor.ProcessEventsAsync(context, messages);

        foreach (EventData eventData in messages) {
            string data = Encoding.UTF8.GetString(eventData.GetBytes());
            var obj = JsonConvert.DeserializeObject(data);
            var c = JsonConvert.SerializeObject(obj, Formatting.Indented);
            await window.Dispatcher.InvokeAsync(() => window.viewModel.log.Add($"Message received (partition {context.Lease.PartitionId}): {c}"));
        }
    }

This is currently displaying the lease partition, but I later added the runtime partition and they were always the same (both partition IDs 1 or both 0) and kept alternating with subsequent Function invocations.

**Comment by jsquire** [comment]
This has been addressed via #33858.   A new overload for `IAsyncCollector<EventData>` has been added to allow specifying a partition key to accompany the event.   

```csharp
[FunctionName("BindingToCollector")]
public static async Task Run(
    [TimerTrigger("0 */5 * * * *")] TimerInfo myTimer,
    [EventHub("<event_hub_name>", Connection = "<connection_name>")] IAsyncCollector<EventData> collector)
{
    // When no partition key is used, partitions will be assigned via round-robin.
    await collector.AddAsync(new EventData($"Event 1 added at: {DateTime.Now}"));
    await collector.AddAsync(new EventData($"Event 2 added at: {DateTime.Now}"));

    // Using a partition key will help group events together; events with the same key will always be
    // assigned to the same partition.
    await collector.AddAsync(new EventData($"Event 3 added at: {DateTime.Now}"), "sample-key");
    await collector.AddAsync(new EventData($"Event 4 added at: {DateTime.Now}"), "sample-key");
}
```

The release for this is tracked in #33919 and has been tentatively scheduled for our March window.   Assuming that nothing requires the release to be rescheduled, the updated package should be available in the second week of March.
