### ISSUE TITLE
[BUG] Using storage table int properties starting with lowercase will crash your app

### ISSUE THREAD

**Issue by gitcte** [Azure/azure-sdk-for-net#28255]
### Library name and version

Azure.Data.Tables 12.5.0

### Describe the bug

If you have in your storage table and your model a property that is int and starts with lower case, your query on it will crash with "System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 'System.Int32'.'"

If you change your model and put the first letter of your property name with upper case there will be no error, but the value of that field will be 0 (because there is no match in the column name from the table).

If you change the table also and put the property name with first letter uppercase, everything works normal.

If you use TableEntity instead of a model (like T), you can access the property with ["propertyName"] and everything works.

### Expected behavior

You can use table storage properties starting with lowercase and uppercase.

### Actual behavior

The application crashes with "System.InvalidCastException: 'Unable to cast object of type 'System.String' to type 'System.Int32'.'"

### Reproduction Steps

Have a model class:
![image](https://user-images.githubusercontent.com/103987732/163945302-ae26a136-d77d-4fc0-958b-87c4a11e256f.png)

In the storage have like this for example:
![image](https://user-images.githubusercontent.com/103987732/163945189-ef33edb4-2d12-4657-ad66-fec3129bd97f.png)

Using the following ways to read the storage table will crash:
![94fe34be-2e37-4105-a68f-b7cc29973970](https://user-images.githubusercontent.com/103987732/163944420-6b42acf7-de19-4169-a3dc-5293504da663.jpg)
or
![78168488-ec37-4faf-bc07-431a934de18f](https://user-images.githubusercontent.com/103987732/163944435-a10e07d4-8e27-4224-93f7-387e5ee976ff.jpg)

### Environment

Windows 11, C#, .NET6, Visual Studio Professional 2022 (17.1.3)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @gitcte - I am not able to reproduce this. Are you sure your table didn't contain a row containing where the int property was typed as a string? 

If I upload an entity with a lowercase int property, then change its type to string in the portal, I also get the exception you are describing.

**Comment by gitcte** [comment]
After i checked more then 500 records, i've found one with this situation:
![image](https://user-images.githubusercontent.com/103987732/164195018-0adeafd8-b145-4d64-b7da-b72aade645bf.png)

Before Azure.Data.Tables we used Microsoft.Azure.Cosmos.Table (1.0.8) and we had no problem with that record (it is in the table for a long time).

Knowing that, should this situation end with an error? IMO it should only throw an error if the string can't be cast to int.

**Comment by christothes** [comment]
The error in this scenario sounds correct to me, since using a strongly typed model means that we will attempt to deserialize according to the types specified in the model. In this case, it seems that finding a record with inconsistent schema was unexpected. However, if it is expected, this is when it would be better to use the `TableEntity` type, as it is schema agnostic.
