### ISSUE TITLE
[BUG] Default TableClientOptions have incorrect LoggedQueryParameters

### ISSUE THREAD

**Issue by tompazourek** [Azure/azure-sdk-for-net#28257]
### Library name and version

Azure.Data.Tables 12.5.0

### Describe the bug

In the [TableClientOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/src/TableClientOptions.cs#L64) file, the default settings are as follows:

```csharp
internal static TableClientOptions DefaultOptions => new()
{
    Diagnostics =
    {
        LoggedHeaderNames = { "x-ms-request-id", "DataServiceVersion" },
        LoggedQueryParameters = { "api-version", "format", "filter" }
    }
};
```

However, the `format` and `filter` query parameters are actually called `$format` and `$filter` (notice they are prefixed by `$`).

Should they be fixed here so they wouldn't be redacted during logging?

btw. I think it would also be good to include the `$select` and `$top` query parameters that aren't listed there at all.

### Expected behavior

The query parameters logged by default are `$format`, `$filter`, `$select`, `$top`.

### Actual behavior

The query parameters `$format`, `$filter`, `$select`, `$top` are redacted from logging, and instead non-existent parameters `format` and `filter` are configured.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
