### ISSUE TITLE
[FEATURE REQ] Revert back to strongly-typed query responses

### ISSUE THREAD

**Issue by stijnmoreels** [Azure/azure-sdk-for-net#28254]
### Library name

Arcus.Monitor.Query

### Please describe the feature.

**Is your feature related to a problem? Please describe.**
The previous versions where using typed responses from the Application Insights API. As in: the response was different when calling dependencies, requests... while now it returns a generic table. This is probably due to the fact that you now can pass in your own Kusto query and the implementation doesn't now what types to return, but this greatly reduces the user experience as (not like before) every column now has to be cast the necessary type. Making it very unstable, I think. In any case, having a generic table with no context is not helpful if one wants to verify the actual content. It seems that it would only be useful for visualisation.

**What solution do you want?**
Revert back to typed responses. This will probably not work for every call, as custom Kusto queries will still need this generic response.

**Comment by SaurabhSharma-MSFT** [comment]
@stijnmoreels We are looking into it and get back to you for any additional information.

**Comment by SatishBoddu-MSFT** [comment]
Hello @stijnmoreels Thanks for the discussion on this topic and the related Github link!

Could you please add any code snippet of strongly typed query\responses and the current release behavior, so that the community and the readers would find it helpful and we can better triage it?

**Comment by stijnmoreels** [comment]
> Hello @stijnmoreels Thanks for the discussion on this topic and the related Github link!
> 
> Could you please add any code snippet of strongly typed query\responses and the current release behavior, so that the community and the readers would find it helpful and we can better triage it?

Sure!

Previous functionality:
```csharp
var clientCredentials = new ApiKeyClientCredentials("<api-key>");
var client = new ApplicationInsightsDataClient(clientCredentials);

EventsResults<EventsCustomEventResult> results = await client.Events.GetCustomEventsAsync("<application-id>", "PT30M");
foreach (EventsCustomEventResult result in results.Value)
{
    string eventName = result.CustomEvent.Name;
    result.CustomDimensions.TryGetValue("<name>", out string value);
   var timestamp = result.Timestamp;
   var count = result.Count;
}
```

Current version:
```csharp
var client = new LogsQueryClient(new DefaultAzureCredential());
string workspaceId = "<workspace_id>";

 var logsBatchQuery = new LogsBatchQuery();
 logsBatchQuery.AddWorkspaceQuery("<app-id>",
    "events",
    new QueryTimeRange(TimeSpan.FromMinutes(30)));

Response<LogsBatchQueryResultCollection> batch = cli.QueryBatch(logsBatchQuery);

foreach (LogsBatchQueryResult result in batch.Value)
{
    IReadOnlyList<LogsTableColumn> logsTableColumns = result.Table.Columns;
}
```

As you can see, one has to know beforehand whant name and type the collumns of the query result should be, instead of strongly-typed like before.
