### ISSUE TITLE
Attestation Readme Issue

### ISSUE THREAD

**Issue by hongli750210** [Azure/azure-sdk-for-net#28283]
1.
**Section** [link](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/attestation/azure-security-attestation#examples)
![image](https://user-images.githubusercontent.com/74638143/164135857-8750ba0f-79ef-47e4-bde9-5bbd3b423aa3.png)

**Suggestion:**
1. Change text to `Create a synchronous attestation client`
2. Change text to `Retrieve Token Certificates`
3. Change text to `Create a synchronous administrative client`
4. Change text to `Retrieve current attestation policy for OpenEnclave`
5. Change text to `List attestation signing certificates`
6. Change text to `Add attestation signing certificate`
7. Add link `- [Remove attestation signing certificate](#remove-attestation-signing-certificate)`

joshfree, lmazuel and LarryOsterman for notification.

**Comment by SaurabhSharma-MSFT** [comment]
@hongli750210 We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@hongli750210 I have submitted a pull request to update the documentation.

**Comment by v-xuto** [comment]
@SaurabhSharma-MSFT Sorry, this is a Java issue, we opened in the wrong repo, we will close it.
