### ISSUE TITLE
Error message for setting Azure.Messaging.ServiceBus.Administration.CreateSubscriptionOptions.MaxDeliveryCount to less than 1 is incorrectly using the name of another property

### ISSUE THREAD

**Issue by MikalJ** [Azure/azure-sdk-for-net#28289]
Setting the `MaxDeliveryCount` property on an instance of `Azure.Messaging.ServiceBus.Administration.CreateSubscriptionOptions` to a value less than 1, results in an `System.ArgumentOutOfRangeException` with `ParamName` set to "AutoDeleteOnIdle", which is the name of another property on `CreateSubscriptionOptions`.

`ParamName` should be set to "MaxDeliveryCount"

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Administration/CreateSubscriptionOptions.cs#L185

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
