### ISSUE TITLE
Add Healthcare action into the AnalyzeActions endpoint

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#28295]
We need to expose this new action added [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/Language/preview/2022-03-01-preview/textanalytics.json#L254). It should follow the design we had for other actions in the [TextAnalyticsActions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/src/TextAnalyticsActions.cs) class

**Comment by heaths** [comment]
This should be called `TextAnalyticsActions.AnalyzeHealthcareEntitiesActions`.
