### ISSUE TITLE
[BUG] SDK does not generate valid SAS URL for a BLOB with Azurite

### ISSUE THREAD

**Issue by DumasDED** [Azure/azure-sdk-for-net#28293]
### Library name and version

Azure.Storage.Blobs 12.11.0

### Describe the bug

A SAS URL generated in code against an Azurite instance using the Azure SDK consistently produces an unauthorized response from the browser, irrespective of the method used to generate it.

This appears to be specific to version 12.11.0 of the SDK. Version 12.10.0 does not have this problem - the same code example provided works as expected.

### Expected behavior

A SAS URL generated against an Azurite instance using the SDK successfully retrieves the corresponding BLOB resource in the browser.

### Actual behavior

The URL returns an unauthorized response indicating the signature is malformed.

### Reproduction Steps

Using the default well-known account name and key for Azurite:

```       
public Uri GetSharedKeySasUrl()
{
    var client = new BlobServiceClient(
        new Uri("http://127.0.0.1:10000/devstoreaccount1/"),
        new StorageSharedKeyCredential(
            "devstoreaccount1",
            "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
        )
    );

    var containerClient = client.GetBlobContainerClient("sample-container");

    var blobClient = containerClient.GetBlobClient("sample-image.jpg");

    var sasBuilder = new BlobSasBuilder(BlobSasPermissions.Read, DateTimeOffset.Now.AddHours(1))
    {
        BlobContainerName = blobClient.BlobContainerName,
        BlobName = blobClient.Name,
        Resource = "b"
    };

    Uri sasUrl = blobClient.GenerateSasUri(sasBuilder);

    Debug.WriteLine("SAS URI for blob is: {0}", sasUrl);

    return sasUrl;
}
```

### Environment

- Windows 10
- Dotnet 6.0.3
- Azure.Storage.Blobs 12.11.0
- Visual Studio 17.1.1

**Comment by RakeshMohanMSFT** [comment]
@DumasDED Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@DumasDED Closing this as the bug is being tracked/fixed on the Azurite side: https://github.com/Azure/Azurite/issues/1404
