### ISSUE TITLE
docs/test(dpg): generate `PetStoreClient` from swagger

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-net#28315]
## Description

Currently the `PetStoreClient` is manually written, which causes a few issues:

- Codes of `PetStoreClient` are not fully aligned with real generated codes.
  - We're running risks that the code snippets in the documents could be out-of-date easily.
- Some code references in the documents are not accurate.

To solve this problem, we should generate `PetStoreClient` from the swagger file. Here are work items:
- [ ] generate `PetStoreClient` from swagger
- [ ] update corresponding documents
- [ ] update test cases

**Comment by lirenhe** [comment]
@archerzz, is this item still valid?  Does the CADL file for petstore meet the requirments?

**Comment by archerzz** [comment]
> @archerzz, is this item still valid? Does the CADL file for petstore meet the requirments?

@lirenhe I'm referring to test clients in `Azure.Core` https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core/tests/TestClients/LowLevelClient I think we still need to generate that client, whether from CADL or from Swagger.
