### ISSUE TITLE
[FEATURE REQ] Peek scheduled messages.

### ISSUE THREAD

**Issue by MikalJ** [Azure/azure-sdk-for-net#28317]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

I'm not sure if this should be a bug instead. Feel free to change this as necessary.

In the previous iterations of the Azure Services Bus client libraries for .NET (WindowsAzure.ServiceBus and Microsoft.ServiceBus.Messaging) it was possible to peek scheduled messages with `TopicClient.Peek()` and `TopicClient.PeekAsync()`

According to this [previously closed issue](https://github.com/MicrosoftDocs/azure-docs/issues/59641):
> Scheduled messages reside in the topic until the scheduled time, and users should peek into the topic if they want to see the scheduled messages. Scheduled Messages can not be peeked from a subscription since they are not present in the subscription.

(strangely, the information added to the docs in this issue, seems to be gone again)

However in Azure.Messaging.ServiceBus, there is no equivalent to `TopicClient`, Instances of `ServiceBusReceiver` are always configured to a subscription on a topic, and never directly to the topic. Thus there is no way to peek scheduled messages, using Azure.Messaging.ServiceBus, despite the [documentation here](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussender.schedulemessageasync?view=azure-dotnet#remarks) stating so.

Seeing as the the service bus API's and earlier .NET client libraries support peeking scheduled messages directly on a topic, Azure.Messaging.ServiceBus should as well.

**Comment by MikalJ** [comment]
If it is to any help, I'd like to elaborate on my use case.

I'm currently in the process of upgrading some software from .NET framework to .NET core. The software used WindowsAzure.Servicebus to interact with an Azure service bus ressource. However, that package is not usable in .NET core, so the obvious choice was to upgrade to the newest iteration of service bus client library, Azure.Messaging.ServiceBus.

One of the things the software does; is to enqueue a scheduled message, that will be consumed by another service to perform some work. The message contains the parameters for the work to be done, and these are not stored elsewhere. Through user interactions SOME of the parameters for the work, may change before the scheduled time. We used the ability to peek scheduled messages to retrieve the values that would not change, cancel the original scheduled message, and enqueue an updated message.

**Comment by jsquire** [comment]
Thank you for the additional context, @MikalJ.   Just to give you an update, we're still working with our service team partners to understand why this was removed in the previous SDK generation and whether there are limitations that we need to be aware of.

**Comment by JoshLove-msft** [comment]
Hi @MikalJ,
Although this is not currently documented, you should be able to pass in the name of your topic that you wish to peek from into the CreateReceiver method. Doing this will allow you to peek scheduled messages from the topic. Note, that none of the other receiver functionality will work as all of that functionality is tied to a subscription. Since we think this is a viable workaround, and it is an observable behavior that we will never break, we don't think it is necessary to introduce additional APIs to peek from a topic.
