### ISSUE TITLE
[FEATURE REQ] Add Priority Property to CloudTask Class

### ISSUE THREAD

**Issue by scottbright22** [Azure/azure-sdk-for-net#28318]
### Library name

Microsoft.Azure.Batch

### Please describe the feature.

Add Priority Property to CloudTask Class.
Tasks with Higher priority would all run before tasks with lower priority get scheduled and run.
DependsOn would be followed as it currently is.

Currently, we see no way to specify some tasks should be run before others without the dependson property.
We are try to get the most efficient use of all the nodes and cores by letting tasks that finish quickly grab another smaller slice of work to do. With a priority property, we could mark a set of smaller job slices as low priority so they do not get run before the large ones.

**Comment by SaurabhSharma-MSFT** [comment]
@scottbright22 We are looking into it and get back to you for any additional information.

**Comment by paterasMSFT** [comment]
This is not a feature that we plan to provide at this time. We hope to in the future, but at the moment Task Dependencies are the only available option.
