### ISSUE TITLE
Allow prefetched messages to be processed after ReleaseSession() is called

### ISSUE THREAD

**Issue by therealrss** [Azure/azure-sdk-for-net#28322]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

When using PrefechCount > 0 on a ServiceBussSessionProcessor in C#, prefetched messages do not appear to be consumed after calling ReleaseSession().

A combination of calling ReleaseSession() with optimistic PrefetchCount is desired to achieve higher throughput in a scenario where cardinality of unique SessionIds in the queue is higher can number of concurrent receivers threads currently consuming. In order for threads to not idle locked on a session that has no further events (information not known upfront), ReleaseSession() will be invoked to allow for fast switch. But at current implementation, this causes all prefetched messages already received to be disregarded.

Any solution that will allow leveraging PrefetchCount with |SessionId| >>> |processing threads| is welcomed.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
@therealrss, if there are already prefetched messages, then I'd expect them to be received quickly by the processor. How are you determining when to call ReleaseSession?

**Comment by therealrss** [comment]
@JoshLove-msft I am calling ReleaseSession() at the end of processing the first message in the session. AutoComplete=true. Is there a way to peek the memory buffer to know how many items are left. If that would be available, then I can condition the ReleaseSession() only when memory buffer is empty.

Also, will a ServiceCall preload messages atomically (framed message for entire batch) or they can arrive one at a time ?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft I am calling ReleaseSession() at the end of processing the first message in the session. AutoComplete=true. Is there a way to peek the memory buffer to know how many items are left. If that would be available, then I can condition the ReleaseSession() only when memory buffer is empty.
> 
> Also, will a ServiceCall preload messages atomically (framed message for entire batch) or they can arrive one at a time ?

There isn't a way to query the amount of messages in prefetch currently. The messages can arrive one at a time.

We have an upcoming feature implemented in https://github.com/Azure/azure-sdk-for-net/pull/28230 that will allow you to receive messages from the callback. Once that is available you can attempt to "drain" the prefetch queue by passing a maxWaitTime of TimeSpan.Zero, after calling ReleaseSession. 
Would that help?

**Comment by therealrss** [comment]
I see, so steps would be

1. ReleaseSession() at first message
2. Call ReceiveMessages(maxWaitTime=TimeSpan.Zero) to drain potentially in memory items

Can step 2 be invoked from inside the callback of the first message ?

I will give it a try once the change you pointed out ships. It might be just what we need.

**Comment by JoshLove-msft** [comment]
> I see, so steps would be
> 
> 1. ReleaseSession() at first message
> 2. Call ReceiveMessages(maxWaitTime=TimeSpan.Zero) to drain potentially in memory items
> 
> Can step 2 be invoked from inside the callback of the first message ?
> 
> I will give it a try once the change you pointed out ships. It might be just what we need.

Yes, exactly - the receive would need to be called from the callback as the args cannot be held onto outside of the callback.
