### ISSUE TITLE
Is it possible to get at the raw JSON from client operations, or easily serialize the objects?

### ISSUE THREAD

**Issue by solvingJ** [Azure/azure-sdk-for-net#2833]
For example:

NetworkInterface myInterface = await client.NetworkInterfaces.GetAsync(resourceGroup, integrationTestInterface)

I would like to be able to print/save the raw text output from this operation to a text file.  

Alternatively,  I would like to know the best way to get a serialized version of myInterface if possible. I've searched through the repo and tried some things, and haven't found a way.

Thanks!

**Comment by solvingJ** [comment]
Based on this: 

https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/NetworkInterfacesOperations.cs


Microsoft.Rest.Serialization.SafeJsonConvert.SerializeObject(testInt, new JsonSerializerSettings())

There must be something with the JsonTransformer annotations and serializer settings, but I can't figure it out.

```json
{
    "properties.virtualMachine": null,
    "properties.networkSecurityGroup": null,
    "properties.ipConfigurations": [
        {
            "properties.applicationGatewayBackendAddressPools": null,
            "properties.loadBalancerBackendAddressPools": null,
            "properties.loadBalancerInboundNatRules": null,
            "properties.privateIPAddress": "10.1.0.5",
            "properties.privateIPAllocationMethod": "Dynamic",
            "properties.privateIPAddressVersion": "IPv4",
            "properties.subnet": {
                "properties.addressPrefix": null,
                "properties.networkSecurityGroup": null,
                "properties.routeTable": null,
                "properties.ipConfigurations": null,
                "properties.resourceNavigationLinks": null,
                "properties.provisioningState": null,
                "name": null,
                "etag": null,
                "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resource-group-01/providers/Microsoft.Network/virtualNetworks/aa-vnet-01/subnets/default"
            },
            "properties.primary": true,
            "properties.publicIPAddress": null,
            "properties.provisioningState": "Succeeded",
            "name": "ipconfig1",
            "etag": "W/\"/00000000-0000-0000-0000-000000000000\"",
            "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resource-group-01/providers/Microsoft.Network/networkInterfaces/integration-test-interface/ipConfigurations/ipconfig1"
        }
    ],
    "properties.dnsSettings": {
        "dnsServers": [],
        "appliedDnsServers": [],
        "internalDnsNameLabel": null,
        "internalFqdn": null,
        "internalDomainNameSuffix": "12345657898.gx.internal.cloudapp.net"
    },
    "properties.macAddress": null,
    "properties.primary": null,
    "properties.enableAcceleratedNetworking": false,
    "properties.enableIPForwarding": false,
    "properties.resourceGuid": "/00000000-0000-0000-0000-000000000000",
    "properties.provisioningState": "Succeeded",
    "etag": "W/\"/00000000-0000-0000-0000-000000000000\"",
    "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resource-group-01/providers/Microsoft.Network/networkInterfaces/integration-test-interface",
    "name": "integration-test-interface",
    "type": "Microsoft.Network/networkInterfaces",
    "location": "centralus",
    "tags": null
}

**Comment by markcowl** [comment]
You can get the raw response from the operation using client.NetworkInterfaces.GetAsync(resourceGroup, integrationTestInterface)   This returns a structure that copntaisn the raw request, respoinse, and the deserialized NIC.

**Comment by solvingJ** [comment]
Thats literally the operation I started with, and what I get is a strongly typed object: NetworkInterface.  

I'm asking HOW do I get the raw request out of it?

**Comment by solvingJ** [comment]
For posterity and future enthusiasts, here is how :
           
    
            var SerializationSettings = new JsonSerializerSettings
            {
                Formatting = Formatting.Indented,
                DateFormatHandling = DateFormatHandling.IsoDateFormat,
                DateTimeZoneHandling = DateTimeZoneHandling.Utc,
                NullValueHandling = NullValueHandling.Ignore,
                ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
                ContractResolver = new ReadOnlyJsonContractResolver(),
                Converters = new List<JsonConverter>
                    {
                        new Iso8601TimeSpanConverter(),
                        new TransformationJsonConverter()
                    }
            };

           NetworkInterface testInt = new NetworkInterface();
           Microsoft.Rest.Serialization.SafeJsonConvert.SerializeObject(testInt, SerializationSettings )


The above produces the JSON that SHOULD be compatible with that in the example seen here, haven't tested yet: 

https://docs.microsoft.com/en-us/rest/api/network/create-or-update-a-network-interface-card


Below is the file from which I took the serialization settings in case the above stops working in the future due to change: 

https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/NetworkManagementClient.cs
