### ISSUE TITLE
Azure.ResourceManager.Network Sample issue

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#28344]
1. Section [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/network/Azure.ResourceManager.Network/samples/Sample1_ManagingVirtualNetworks.md):
    ![image](https://user-images.githubusercontent.com/76771069/164651648-4a252765-e376-4bdd-ad26-bd53ef6098bd.png)

    Suggestion:
    Update to the following code:
    ```
    AddressPrefixes = { "10.0.0.0/16", },
    DhcpOptionsDnsServers = { "10.1.1.1", "10.1.2.4" },
    ```
2. Section [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/network/Azure.ResourceManager.Network/samples/Sample2_ManagingNetworkInterfaces.md)
    ![image](https://user-images.githubusercontent.com/76771069/164652497-b050499b-e1ae-4b7b-ab03-73656427f028.png)
    Suggestion:
    Add the following code after '`PublicIPAddressResource publicIPAddress = await publicIPAddressCollection.CreateOrUpdate(WaitUntil.Completed, publicIPAddressName, publicIPInput).WaitForCompletionAsync();`'

    ```
    VirtualNetworkCollection virtualNetworkCollection = resourceGroup.GetVirtualNetworks();

    string vnetName = "myVnet";

    // Use the same location as the resource group
    VirtualNetworkData input = new VirtualNetworkData()
    {
        Location = resourceGroup.Data.Location,
        AddressPrefixes = { "10.0.0.0/16", },
        DhcpOptionsDnsServers = { "10.1.1.1", "10.1.2.4" },
        Subnets = { new SubnetData() { Name = "mySubnet", AddressPrefix = "10.0.1.0/24", } }
    };

    VirtualNetworkResource virtualNetwork = await virtualNetworkCollection.CreateOrUpdate(WaitUntil.Completed, vnetName, input).WaitForCompletionAsync();
    ```

3. Section [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/network/Azure.ResourceManager.Network/samples/Sample2_ManagingNetworkInterfaces.md)
    ![image](https://user-images.githubusercontent.com/76771069/164665639-508d09c7-4712-4bde-86aa-7d96c7df497b.png)

    Suggestion:
    1.Update `virtualNetwork` to `networkInterface`
    2.Update `virtualNetwork` to `networkInterface`

4. Section [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/network/Azure.ResourceManager.Network/samples/Sample2_ManagingNetworkInterfaces.md)
    ![image](https://user-images.githubusercontent.com/76771069/164669454-278b0c2d-7961-4b75-8ce6-e3ded009c86e.png)

    Suggestion:
    1.Update `virtualNetwork` to `networkInterface`
    2.Update `virtualNetwork` to `networkInterface`
    3.Update `myVnet` to `myNetworkInterface`

5. Section [link](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/network/Azure.ResourceManager.Network/samples/Sample2_ManagingNetworkInterfaces.md)
    ![image](https://user-images.githubusercontent.com/76771069/164672260-f4081a81-211d-4630-9eff-cad77007b702.png)

    Suggestion:
    1.Update `virtualNetwork` to `networkInterface`
    2.Update `virtualNetwork` to `networkInterface`
    3.Update `myVnet` to `myNetworkInterface`

@scottaddie and @archerzz for notification.

**Comment by v-xuto** [comment]
Close this issue, due to PR(#30308) merged.
