### ISSUE TITLE
[BUG] Unable to Fetch results of custom Question answering within a Orchestration Workflow in Language Studio

### ISSUE THREAD

**Issue by nisarkhan916** [Azure/azure-sdk-for-net#28342]
### Library name and version

Azure.AI.Language.Conversation v1.0.0-beta.2 (pre-release)

### Describe the bug

After creating a Orchestration Workflow in language studio, Getting the below exception while fetching the results from Orchestrator workflow.
Specifically whenever we are trying to fetch results from Custom question answering (CQA) of Orchestrator, we are facing **BadRequest: One or more errors occurred. Corresponding activity ID: d72d64e8-cdf0-4ad3-8d22-d0e3b11ce883.**  

Also sometimes when we are trying to fetch results from Conversation language understanding(CLU) of Orchestrator we are facing again the same issue.

Note: Attached the screenshot related to the exceptions faced.

Thanks in advance...

![MicrosoftTeams-image (32)](https://user-images.githubusercontent.com/64094893/164646789-71795d4c-0f38-425c-9d0c-7a0e2f99ea60.png)

### Expected behavior

As mentioned in Language studio documentation, we should get results from orchestration workflow containing CLU intent/QnA  question along with scores.

### Actual behavior

Specifically whenever we are trying to fetch results from Custom question answering (CQA) of Orchestrator, we are facing **BadRequest: One or more errors occurred. Corresponding activity ID: d72d64e8-cdf0-4ad3-8d22-d0e3b11ce883.*
![MicrosoftTeams-image (32)](https://user-images.githubusercontent.com/64094893/164646821-9faf645e-a301-4539-9e46-f277637c73be.png)
*

### Reproduction Steps

AzureKeyCredential credential = new AzureKeyCredential("{LanguageServiceSubcriptionKey}");
Uri endpoint = new Uri("https://{Endpoint}.cognitiveservices.azure.com");
ConversationAnalysisClient client = new ConversationAnalysisClient(endpoint, credential);
ConversationsProject orchestrationProject = new ConversationsProject("OrchestrationTestProject", "OrchestratornewModel");
Response<AnalyzeConversationResult> response = await client.AnalyzeConversationAsync({Query}, orchestrationProject);
//Getting the Predicted Response
OrchestratorPrediction orchestratorPrediction = response.Value.Prediction as OrchestratorPrediction;

### Environment

VS-2019 .Net 3.1

**Comment by unicornlab-nithinb** [comment]
Facing the same issue. Any updates?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
There were quite a few changes to the models and generated code. Please upgrade to our beta 3 package we just released earlier this week and see if the problem still reproduces.

**Comment by unicornlab-nithinb** [comment]
@heaths - I'm using the beta 3 library and still facing the same issue. I'm not able to test the deployed model through the language studio as well. 

I'm using this package - Azure.AI.Language.Conversations 1.0.0-beta.3

**Comment by heaths** [comment]
Adding the service people since you're getting the same issue in Language Studio. Would it be acceptable to share an example query? Given it's a `BadRequest`, this may be helpful.

**Comment by unicornlab-nithinb** [comment]
> Adding the service people since you're getting the same issue in Language Studio. Would it be acceptable to share an example query? Given it's a `BadRequest`, this may be helpful.
> 
> /cc @ChongTang

Not sure what you mean by the query? OP @nisarkhan916 has already mentioned the screenshots of the language studio. 

When I tried to inspect the call from Language Studio, it looks like it is also doing the same Rest API call and getting the same error we get through the SDK/Rest API.

**Comment by ChongTang** [comment]
There is an issue with the back-end service. The fix will be deployed next week. Will update this thread.

**Comment by ChongTang** [comment]
Hello @nisarkhan916 . This has been fixed already. Can you try again?

**Comment by nisarkhan916** [comment]
Thanks @ChongTang , its working now.
