### ISSUE TITLE
Text Analytics: Consider Supporting Operation Result Serialization 

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#28358]
# Summary

The Text Analytics service team has been receiving customer feedback indicating that scenarios involving the ability to serialize, store, and deserialize results from Text Analytics operations are becoming a mainstream scenario.   Because guaranteeing serialization compatibility across arbitrary types is very difficult problem, the .NET SDKs have chosen not to explicitly support serialization/deserialization of our model types to date.

Given the strong customer feedback for Text Analytics in this area, we should consider whether it is possible to support serialization and deserialization of the model types returned as the result of operations from the `TextAnalyticsClient`.  

# Scope of Work

- Explore ideas for safely supporting serialization/deserialization of result model types that would allow us to guarantee compatibility across service and client library versions.   Ideas brought up in early discussion were:
  - Exposing custom `JsonConverter` types that customers could use in their application.   _(Krzysztof)_
  - Asking customers to store the raw response stream and exposing new public APIs to parse the stream int othe models.  _(Kryzstof)_

- Determine recommendations for whether it is feasible to support this scenario.
  - If so, prepare a design proposal for discussion
  - If not, capture the rationale behind the recommendation for discussion

# Success Criteria

- We have an understanding of the challenges supporting serialization/deserialization of the result-focused model types.

**--EITHER--**
- We have a recommendation to support the scenario and a design proposal for discussion

**OR**

- We have a recommendation **_NOT_** to support the scenario and have the rationale for discussion

**Comment by molesmoke** [comment]
Interesting, I just started looking at migrating some workloads to the Azure dotnet API and was pondering this exact problem but for ComputerVisionClient. I was wondering if there was some policy on what types of changes occurred between API revisions that we could use in planning? (i.e. would attributes be purely additive but the model hierarchy remain the same?).

It's currently already pretty straightforward to grab the JSON response and store/parse it later into the provided model. However, if the raw response were stored, what guarantees might we have that this could be handled by a later SDK release? I'd need to be sure that responses from multiple API revisions could be deserialized with one SDK release. The current SDK looks like only the latest (v3.2) is handled, with no backwards compatibility for older major revisions.

Currently, I'm considering copying out the generated models and adding serialization support to it via attributes or other means. I'm not sure the SDK could be a good arbiter of an appropriate serialization mechanism. For us, JSON is fine over-the-wire, but a binary representation seems like it would be better choice for long term storage and processing scenarios (faster and less storage space).

**Comment by maririos** [comment]
The services follow the [Microsoft Azure REST API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md) where you can see what type of changes are allowed. Note that breaking changes are highly discouraged and avoided as much as possible.
The SDKs follow them and also the [Azure SDK Guidelines](https://azure.github.io/azure-sdk/general_introduction.html). One of our main design principles is to ensure our libraries are dependable and have 100% backward compatibility

**Comment by molesmoke** [comment]
@maririos Perfect, thanks!
