### ISSUE TITLE
[BUG] Azure Function using new EventHubTrigger extension (5.1.0) fails indexing and gets disabled due to missing SupportsRetryAttribute type

### ISSUE THREAD

**Issue by david-eagles** [Azure/azure-sdk-for-net#28357]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventHubs 5.1.0

### Describe the bug

After upgrading to the latest (5.1.0) Microsoft.Azure.WebJobs.Extensions.EventHubs package released yesterday, Azure Functions (.net6 with functions runtime v4) that use an EventHubTrigger are now failing to be indexed and are disabled when run (locally, using the Azure Functions Core Tools with VS2022):

[2022-04-23T00:54:40.247Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'StoreEventInCosmosDb'. System.Private.CoreLib: Could not load type 'Microsoft.Azure.WebJobs.Host.SupportsRetryAttribute' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.31.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2022-04-23T00:54:40.282Z] Error indexing method 'StoreEventInCosmosDb'
[2022-04-23T00:54:40.285Z] Microsoft.Azure.WebJobs.Host: Error indexing method 'StoreEventInCosmosDb'. System.Private.CoreLib: Could not load type 'Microsoft.Azure.WebJobs.Host.SupportsRetryAttribute' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.31.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
[2022-04-23T00:54:40.287Z] Function 'StoreEventInCosmosDb' failed indexing and will be disabled.

Upgrading Microsoft.Azure.WebJobs.Extensions.EventHubs from 5.0.1 -> 5.1.0 also upgraded the following packages

Microsoft.Azure.WebJobs 3.0.31 -> 3.0.32
Microsoft.Azure.WebJobs.Core 3.0.31 -> 3.0.32

Reverting to 5.0.1 (and the associated 3.0.31 WebJobs assemblies) resolves the issue.

### Expected behavior

Functions with EventHubTrigger bindings should be indexed and run correctly.

### Actual behavior

Functions with EventHubTrigger bindings failed to be indexed due to the SupportsRetryAttribute symbol not being found.

### Reproduction Steps

Add an Azure Function with the following definition

[FunctionName("EventHubTrigger")]
public async Task EventHubTrigger(
    [EventHubTrigger("hubname", Connection = "EventHubConnectionString", ConsumerGroup = "$Default")] EventData[] events,
    ILogger log)
{
    ...
}

### Environment

Visual Studio 2022
.Net 6 Azure Function Apps v4 runtime project

**Comment by JoshLove-msft** [comment]
Hi @david-eagles,
I reproed this issue with core tools version 4.0.3971.

Upgrading to the [latest version](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#install-the-azure-functions-core-tools) - 4.0.4483 seems to fix it. 

Can you try upgrading?

**Comment by david-eagles** [comment]
Ok, I’ll give it a go.  I did notice Visual Studio automatically check for the latest version and report it was already up to date, but I’ll check what version it’s using and if I can manually upgrade…

Sent from my iPhone

On 23 Apr 2022, at 14:37, JoshLove-msft ***@***.***> wrote:

﻿

Hi @david-eagles<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavid-eagles&data=05%7C01%7Cdavid.eagles%40ivolve.com%7Cd66f015c6a5c490a3ba808da24e2f547%7C04e47901d8654d30b9f13ef738326046%7C0%7C0%7C637862854447127834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SaBoENXXVoSRYoRaYpS88o2iy4pcj5Glv7TxybgHAjg%3D&reserved=0>,
I reproed this issue with core tools version 4.0.3971.

Upgrading to the latest version<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fazure-functions%2Ffunctions-run-local%3Ftabs%3Dv4%252Cwindows%252Ccsharp%252Cportal%252Cbash%23install-the-azure-functions-core-tools&data=05%7C01%7Cdavid.eagles%40ivolve.com%7Cd66f015c6a5c490a3ba808da24e2f547%7C04e47901d8654d30b9f13ef738326046%7C0%7C0%7C637862854447127834%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Maur9AVxfeNxb0agQ7MxHS%2FDTls79tcfixEGmNa5fWs%3D&reserved=0> - 4.0.4483 seems to fix it.

Can you try upgrading?

**Comment by david-eagles** [comment]
Hi Josh

I am using the built-in VS tooling - I'm running the most recent VS 2022 update (17.1.5), which was released only 4 days ago.  I've confirmed that includes Core Tools v4.0.3971.

Since there doesn't appear to be any major changes or critical fixes between 5.0.1 and 5.1.0, I've reverted for now and can wait for the next VS update.  Hopefully the actual Azure Functions runtime doesn't have this same issue...

**Comment by JoshLove-msft** [comment]
> Hi Josh
> 
> I am using the built-in VS tooling - I'm running the most recent VS 2022 update (17.1.5), which was released only 4 days ago. I've confirmed that includes Core Tools v4.0.3971.
> 
> Since there doesn't appear to be any major changes or critical fixes between 5.0.1 and 5.1.0, I've reverted for now and can wait for the next VS update. Hopefully the actual Azure Functions runtime doesn't have this same issue...

Sounds good. The functions runtime does indeed have the correct dependency of the Microsoft.Azure.WebJobs library (3.0.32).

**Comment by tgutzler** [comment]
Hi,
I'm getting the same issue as @david-eagles with Microsoft.Azure.WebJobs.Extensions.EventHubs 5.1.0 but I've upgraded all the way from functions v3 on netcore3.1 with EventHubs 4.20.
Unfortunately, downgrading EventHubs to 5.0.1 and Microsoft.Azure.WebJobs to 3.0.31 did not resolve the problem.
Neither did downgrading to 5.0.0 and 3.0.30

**Comment by david-eagles** [comment]
Not sure if this is the problem, but from memory to upgrade to .Net 6 you need to make two changes to the Functions runtime configuration.  One was done via a simple change to one of the environment variables (changing the runtime version from ~3 to ~4), but the other step required using the Azure CLI and using the “az” command to also change one or two settings.

Sent from my iPad

On 18 May 2022, at 09:15, tgutzler ***@***.***> wrote:

﻿

Hi,
I'm getting the same issue as @david-eagles<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdavid-eagles&data=05%7C01%7Cdavid.eagles%40ivolve.com%7C854163ef8bdc42e4202108da385b1fc7%7C04e47901d8654d30b9f13ef738326046%7C0%7C0%7C637884261273216200%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kfWM3QBjvn7fnRLkLB9In5kzWJ9R3mAE7JMB6N%2F2fJY%3D&reserved=0> with Microsoft.Azure.WebJobs.Extensions.EventHubs 5.1.0 but I've upgraded all the way from functions v3 on netcore3.1 with EventHubs 4.20.
Unfortunately, downgrading EventHubs to 5.0.1 and Microsoft.Azure.WebJobs to 3.0.31 did not resolve the problem.
Neither did downgrading to 5.0.0 and 3.0.30

**Comment by tgutzler** [comment]
I ended up going back to EventHubs 4.3.1, which works fine locally and in the cloud. I'll delay the update of that package to later.
There is a project setting <AzureFunctionsVersion> I had to change to v4. This updates the app setting when you deploy from VS.
No need to run az commands.

**Comment by connershoop** [comment]
This is still an issue that requires downgrading `Microsoft.Azure.WebJobs.Extensions.EventHubs` to `5.0.1` .  

While using latest Visual Studio Core tools from [here ](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#install-the-azure-functions-core-tools)and `Microsoft.Azure.WebJobs.Extensions.EventHubs 5.1.1`, running an Eventhub Trigger function (`Runtime Version: ~4`, `net6.0`) locally, I get error: ` Could not load type 'Microsoft.Azure.WebJobs.Host.SupportsRetryAttribute' from assembly 'Microsoft.Azure.WebJobs.Host, Version=3.0.31.0`.  

Downgrading to `Microsoft.Azure.WebJobs.Extensions.EventHubs` to `5.0.1` solves the issue as @david-eagles suggests.

Reopen this? `/unresolve`
