### ISSUE TITLE
[BUG] Question Answering Project Rest API are malfunctioning

### ISSUE THREAD

**Issue by nisarkhan916** [Azure/azure-sdk-for-net#28366]
### Library name and version

Cognitive Services- API version: 2021-10-01

### Describe the bug

Question Answering Projects - Update Qnas [Rest API](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/questionanswering/question-answering-projects/update-qnas). 

Issue faced
1. Replace feature -- When replace query is executed without answer parameter, We found that the Particular QnA pair itself is getting deleted from the data.
Example Query: [
    {
    "op": "replace",
    "value": {
      "id": 16,
      "source": "Editorial",
      "questions": [
        "question 3.1",
        "question 3.2"
      ],
      "dialog": {
        "isContextOnly": false
      }
    }
  }
]
 
2. Update Feature Request - There is no option to update questions, Meta data, Prompts  w.r.t  QnA pair ID, Is there any chance we will be getting this in future.

### Expected behavior

It is expected to update the question or at least replace the questions when the QnA ID is provided.

### Actual behavior

Complete QnA pair itself is getting deleted when replace feature is executed with only QnA pair id and the questions to be replaced.

### Reproduction Steps

1. [Rest API URL](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/questionanswering/question-answering-projects/update-qnas)

2. Replace Feature Body -- [
    {
    "op": "replace",
    "value": {
      "id": 16,
      "source": "Editorial",
      "questions": [
        "question 3.1",
        "question 3.2"
      ],
      "dialog": {
        "isContextOnly": false
      }
    }
  }
]

3. Did not find update feature in Custom question answering Project(CQA) like we have it for [QnA maker](https://docs.microsoft.com/en-us/rest/api/cognitiveservices-qnamaker/qnamaker4.0/knowledgebase/update#metadata) --- Here we are able to update respective parameters(questions, prompts, metadata.)

### Environment

- Visual Studio 19
- Dot Net
- [Language Studio Portal](https://language.cognitive.azure.com/home)

**Comment by SaurabhSharma-MSFT** [comment]
@nisarkhan916 We are looking into it and get back to you for any additional information.

**Comment by nisarkhan916** [comment]
Hey @SaurabhSharma-MSFT , is there any update on the feature ?
