### ISSUE TITLE
[BUG] Azure.Storage.Blob 12.11.0 Exception: InvalidHeaderValue

### ISSUE THREAD

**Issue by ToddEvansHome** [Azure/azure-sdk-for-net#28381]
### Library name and version

Azure.Storage.Blob 12.11.0

### Describe the bug

When installing Azure.Storage.Blob 12.11.0 into Class Project that is used by an Azure Function project.  The following exception occurs.

![image](https://user-images.githubusercontent.com/43685731/165204994-13b809ec-b9ed-4841-85e9-937b315a8ca1.png)

### Expected behavior

Be able to have an Azure Function reference another project that contains a reference to Azure.Storage.Blob 12.11.0

### Actual behavior

The Azure Functions starts up but immediately throws the below exception.

![image](https://user-images.githubusercontent.com/43685731/165205242-4f2ac482-5900-4433-8e4f-0b7b7e2de344.png)

### Reproduction Steps

- Create an  Azure Function Project using the Azure Function template.  Add a simple  Azure Function like the following

```
public class Function1
    {
        [FunctionName("BlobTriggerStart")]
        public static async Task BlobTriggerClientFunction(
            [BlobTrigger("{AddContainerName}/{name}", Connection = "{AddConnectionString}")] BlobClient blobClient, string name,
            ILogger log, [DurableClient] IDurableOrchestrationClient starter)
        {
            try
            {
                log.LogInformation($"Started orchestration trigged by BLOB trigger. A blob item with name = '{name}'");
                log.LogInformation($"BLOB Name {blobClient.Name}");

            }
            catch (Exception ex)
            {
                log.LogError("Something went wrong. Error : " + ex.InnerException);
                throw;
            }
        }
    }

```
- Run the Azure Function: The project should run like normal

- Create a Class Project and reference the Azure.Storage.Blob Nuget 12.11.0
  - Note: No other code is needed.  Just a reference to the NuGet package.

- In the Azure Function Project, reference the Class Project
- Run the Azure Function: The Exception should occur
- In the Class Project, down grade Azure.Storage.Blob to 12.10.0
  - Run the Azure Function.  The project should run like normal

### Environment

Windows 10
.NET 6
Visual Studio 17.1.5

**Comment by SaurabhSharma-MSFT** [comment]
@ToddEvansHome We are looking into it and get back to you for any additional information.

**Comment by SatishBoddu-MSFT** [comment]
Hello @ToddEvansHome Thanks for reaching out on this forum.

Could you please try creating a new sample project with the Azure Storage Blobs Nuget 12.11.0. I see no errors reproduced when we call a class library from the Azure Function Blob trigger! if there is any GitHub (dummy sample)  location where you can point us, then we can take a look at your code snippet quickly.

Ref: [Download a blob](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-dotnet?tabs=environment-variable-windows#download-a-blob)
![image](https://user-images.githubusercontent.com/62923178/165411938-74ac04da-5a1e-4388-b7db-f947d8d3590d.png)

**Comment by SatishBoddu-MSFT** [comment]
Hello @ToddEvansHome 
Just checking back! Please let us know if you need further help.

Please also do visit [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/index.html) the home for technical questions and answers at Microsoft.

**Comment by FarshanAhamed** [comment]
I'm also facing the same issue when I updated the NuGet from 12.10.0 to 12.11.0 with the local setup (Azurite). When using an actual azure storage connection string, it is working fine.

**Comment by SatishBoddu-MSFT** [comment]
Hello @FarshanAhamed Do you have any Github public code(sanitized) branch where i can take a look at the code snippet quickly for testing from my side?

**Comment by ToddEvansHome** [comment]
I was able to successfully(unfortunately) create a new project from an Azure Function template and repo the failure
Originally the project was an HTTPTrigger, but when I changed it to BlobTrigger and added Azure.Storage.Blobs 12.11.0, that is when I received the same error message.
There is no need for a second project.
I have attached a zipped up project.

Please let me know if you have any questions.


Todd Evans

Senior Software Developer

***@***.******@***.***>
Missouri
530 Maryville Centre Dr., Suite 50, St. Louis, MO 63141, USA
Tel +1 (636) 812-0117

________________________________

**Comment by ToddEvansHome** [comment]
Todd Evans has shared a OneDrive for Business file with you. To view it, click the link below.
<https://ebiquityplc365-my.sharepoint.com/:u:/g/personal/todd_evans_ebiquity_com/Ef8R6qguMV9NlRrr2GYEdowB8UVpmSZAaXmMSXR0cCzvTA>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://ebiquityplc365-my.sharepoint.com/:u:/g/personal/todd_evans_ebiquity_com/Ef8R6qguMV9NlRrr2GYEdowB8UVpmSZAaXmMSXR0cCzvTA>
FunctionApp3.zip<https://ebiquityplc365-my.sharepoint.com/:u:/g/personal/todd_evans_ebiquity_com/Ef8R6qguMV9NlRrr2GYEdowB8UVpmSZAaXmMSXR0cCzvTA>

I was able to successfully(unfortunately) create a new project from an Azure Function template and repo the failure
Originally the project was an HTTPTrigger, but when I changed it to BlobTrigger and added Azure.Storage.Blobs 12.11.0, that is when I received the same error message.
There is no need for a second project.
I have attached a zipped up project.

Please let me know if you have any questions.


Todd Evans

Senior Software Developer

***@***.******@***.***>
Missouri
530 Maryville Centre Dr., Suite 50, St. Louis, MO 63141, USA
Tel +1 (636) 812-0117

________________________________

**Comment by SatishBoddu-MSFT** [comment]
Hello @ToddEvansHome Could you please confirm what format are you using for the Blob storage connection string?

"DefaultEndpointsProtocol=https;AccountName=storageaccountName;AccountKey=hfWME5pQ+789knrhcwjJ/g==;EndpointSuffix=core.windows.net"

**Comment by SatishBoddu-MSFT** [comment]
Routing to the service team's attention for further action on this issue!

**Comment by navba-MSFT** [comment]
@ToddEvansHome Could you please share the code again ? I can look at the backend logs and help you with the fix. Awaiting your reply.

PS: the link sample code link which you have shared is failing for some reason.

**Comment by ToddEvansHome** [comment]
Here is the project
[FunctionApp3.zip](https://github.com/Azure/azure-sdk-for-net/files/8662801/FunctionApp3.zip)

**Comment by navba-MSFT** [comment]
@ToddEvansHome Thanks for sharing your project. I was able to reproduce the same issue. After doing some debugging, I was able to identify the cause. The 400 error with Invalid Header was due to the `x-ms-version: 2021-06-08` being sent by the Blob Storage SDK wasn't matching the version used by the SDK. 

This is a known issue and it is documented [here](https://github.com/Azure/Azurite#api-version-compatible-strategy).

>If an incoming request has a higher API version than Azurite, Azurite will return a InvalidHeaderValue error for x-ms-version (HTTP status code 400 - Bad Request).

You can run the below command to find the version of Azurite.

>azurite.exe --version

**Below are the steps that I followed to fix this issue:**
I deleted the contents of the below folder.

C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator>azurite.exe --version
3.14.1

I upgraded my Azurite version to the most recent version [3.17.1](https://github.com/Azure/Azurite/releases/tag/v3.17.1) and that resolved the issue.

>npm i azurite@3.17.1

Launch Visual Studio again and test the FunctionApp. Hope this helps.  Please let me know if you still face this issue. Awaiting your reply.

**Comment by ToddEvansHome** [comment]
That worked.  Great!  Thank you!

**Comment by navba-MSFT** [comment]
@ToddEvansHome Thanks for getting back. We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
