### ISSUE TITLE
[Question] Migration from Microsoft.Azure.Cosmos.Table and IQueryable

### ISSUE THREAD

**Issue by xDDDx** [Azure/azure-sdk-for-net#28389]
### Library name and version

Azure.Data.Tables

### Query/Question

`Microsoft.Azure.Cosmos.Table` is deprecated and we try to migrate to `Azure.Data.Tables`. 

The big problem is, that we use `IQueryable` and `LINQ` to create the query dynamicly. It was possible to do that by using `query.AsTableQuery()` and execute the query. 

Now we have to pass `Expression<Func<T, bool>>` as parameter into `tableClient.Query<T>()` method. How we create this Expression dynamicly?

We need this, because the query depends on, e.g. current logged in user.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @xDDDx  Please see the following sample https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md#linq-expression

**Comment by xDDDx** [comment]
Hi @christothes ,  

sorry, but this does not help. I give you an example what we are doing. This is a small simple example, so it can be more complicated.

We are creating some query first 
```
var query = _table.CreateQuery<SomeEntity>().Where(x => x.PartitionKey == "key")
if(!user.IsAdmin)
    query = query.Where(x => x.Company = user.Company)

var results = await query.ExecuteQueryAsync();
```
Migrate this example to current approach means we need two different `table.Query()` calls like this.
```
if(user.IsAdmin)
   results = await _table.Query<SomeEntity>(x => x.PartitionKey == "key");
else
   results = await _table.Query<SomeEntity>(x => x.PartitionKey == "key" && x.Company == user.Company);
```
this is the simple example. Like I said our queries are more complex and are depends on also e.g. user permissions or some other properties

**Comment by christothes** [comment]
Hi @xDDDx  Expressions can still be combined. Please see the example mentioned in this related issue https://github.com/Azure/azure-sdk-for-net/issues/24033#issuecomment-927378891

**Comment by xDDDx** [comment]
I think I will try to migrate to `Expression` based approach. Thank's for your help. Below you can see our current query approach.

```
// ------------------- interface, implemented for azure tables and cosmos db
    public interface IQueryableRepository<TResult, in TIdentifier> : IDeletableRepo, IRepository<TResult, TIdentifier> where TResult : class, IEntity
    {
        Task<int> CountRecords();
        IQueryable<TResult> AsQueryable();
        IQueryable<TResult> AsQueryableWithDeleted();
    }

// ------------------ create query
        public IQueryable<TResult> AsQuery()
        {
            var query = _table.Value.CreateQuery<TResult>();
            return query;
        }

// ----------------- define query
        public async Task<bool> IsDocumentAnInvoiceAsync(IUserBasedStrategy userStrategy, string documentId, string repositoryId)
        {
            var query = from v in _baseRepository.AsQueryable()
                        where v.InvoiceId == documentId && v.InvoiceRepositoryId == repositoryId
                        select v;

// extend query here
            var queries = userStrategy.ExtendQuery(query);
// execute query
            var result = await queries.QueryAsync();

            return result.Any();
        }

// -------------- one of the user strategies
        public static IEnumerable<IQueryable<T>> ExtendQuery<T>(this IQueryable<T> query) where T : IAzureTableEntity
        {
            if (_user.SupplierIdentifier.SupplierId.IsSet())
                yield return query.Where(x => x.PartitionKey == supplier.SupplierId);

            if (_user.SupplierIdentifier.BusinessPartnerId.IsSet())
                yield return query.Where(x => x.PartitionKey == supplier.BusinessPartnerId);
        }

// ---------- execute query
        /// <summary>
        /// Executes the specified query.
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="query">The query.</param>
        /// <returns></returns>
        public async Task<IEnumerable<T>> Execute<T>(IQueryable<T> query)
        {
            TableContinuationToken token = null;
            var docQuery = query.AsTableQuery();
            var take = TryGetTakeParameterFromQuery(docQuery);
            var batches = new List<IEnumerable<T>>();
            do
            {
                var result = await docQuery.ExecuteSegmentedAsync(token);
                token = result.ContinuationToken;
                batches.Add(result.Results);
                if (take.HasValue && batches.Count >= take)
                    break;
            }
            while (token != null);

            return batches.SelectMany(b => b);
        }
```

**Comment by xDDDx** [comment]
@christothes I created an extension, that converts `IQueryable<T>` into `Expression<Func<T, bool>>`. That works for us till now. I'm also able to extrakt `Take()` from the query. What is not working, is to extract the columns by e.g. `Select(x => new { x.Col1, x.Col2 }). Not sure how to deal with that, because the return type is different. But it's ok for us at the moment.

If you want, I can share the code. It is very simple and, I'm sure, not complete yet. Maybe it will be some day a part of the SDK

**Comment by christothes** [comment]
You should post it in a Gist.

**Comment by xDDDx** [comment]
@christothes here we are ;)
https://gist.github.com/xDDDx/368ffdb0b90016bc346970c5b42d7405

Thank you for your support!

**Comment by Arithmomaniac** [comment]
@xDDDx for an off-the-shelf solution to your "Dynamic `Where`" problem, are you familiar with the predicate-composition features of [LinqKit](https://github.com/scottksmith95/LINQKit#predicatebuilder) and [NeinLinq](https://github.com/axelheer/nein-linq/blob/main/src/NeinLinq/PredicateTranslator.cs)?
