### ISSUE TITLE
[QUERY] Can the migration guide from Microsoft.Azure.Storage.Blob to Azure.Storage.Blobs be added to nuget.org?

### ISSUE THREAD

**Issue by nimsilva** [Azure/azure-sdk-for-net#28393]
### Library name and version

Microsoft.Azure.Storage.Blob 11.2.3

### Query/Question

Hi,

Can the migration guide from Microsoft.Azure.Storage.Blob to Azure.Storage.Blobs that is here:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md
be added to the [nuget.org Microsoft.Azure.Storage.Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/) deprecation warning?

A similar message to this one below would save a lot of time searching 🙂 
See https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md for Migration guide and more details.

Thank you 🙂

**Comment by SaurabhSharma-MSFT** [comment]
@nimsilva We have redirected this issue to services team to help you with your ask.

**Comment by nimsilva** [comment]
Thank you for the feedback, I have filled the issue with nuget.org directly 🙂 
Closing the issue.
