### ISSUE TITLE
cloudtable does not contain a definition for.ExecuteQuery

### ISSUE THREAD

**Issue by GerFVersteegGitHub** [Azure/azure-sdk-for-net#2840]
Have a nice day,

Cloudtable.ExecuteQuery(Query, .. is in error.
'Cloudtable' does not contain a definition for 'ExecuteQuery' ...

This is in Visual Studio 2017 Asp.Net Core 
Nuget: WindowsAzure.Storage v8.10

Can any one give a tip what to do with this problem.

Thanks in advence Ger Versteeg
![executequery](https://cloud.githubusercontent.com/assets/13047756/23135400/c26943f4-f798-11e6-86f9-f68a2b2f91b5.png)

**Comment by markcowl** [comment]
@GerFVersteegGitHub Despite the title of the repo, WindowsAzure.Storage does not reside here.  Can you post this question to the forums, or the github repo for windowsazure.storage: https://github.com/Azure/azure-storage-net
