### ISSUE TITLE
[QUESTION] Is there no Purge feature for Key Vaults in the new Management SDK for .net? 

### ISSUE THREAD

**Issue by abmis-mi** [Azure/azure-sdk-for-net#28412]
### Library name and version

Azure.ResourceManager.KeyVault v1.0.0-beta.8

### Query/Question

We want to Purge the keyvault resource using SDK but we are not able to find the required method in the current SDK for .net. Is there a plan to add it?  

### Environment

Hosting platform or OS and .NET runtime version :
Azure AppService DotNet Core 5

IDE and version : 
Version 17.2.0 Preview 5.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@abmis-mi support purge, please check `DeletedVaultResource.PurgeDeleted`.
Before purge a vault, please make sure its purge protection is turned off.
