### ISSUE TITLE
SiteConfig.WindowsFxVersion Property: Please Provide Information about Possible Values

### ISSUE THREAD

**Issue by bdbvb** [Azure/azure-sdk-for-net#28415]
SiteConfig.WindowsFxVersion Property: Please Provide Information about Possible Values

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fcedf032-16cc-cff2-0c0c-bb6b6c94872c
* Version Independent ID: bcbb8f8e-ddac-29c8-85d4-24e0f00b0e75
* Content: [SiteConfig.WindowsFxVersion Property (Microsoft.Azure.Management.AppService.Fluent.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.appservice.fluent.models.siteconfig.windowsfxversion?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.AppService.Fluent.Models/SiteConfig.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.AppService.Fluent.Models/SiteConfig.xml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ArthurMa1978** [comment]
This need to be fixed from upstream swagger file
