### ISSUE TITLE
[QUERY] Does Azure Function Isolated Process support Identity-based connections?

### ISSUE THREAD

**Issue by ahsanhabib91** [Azure/azure-sdk-for-net#28413]
### Library name and version

Microsoft.Azure.Functions.Worker.Extensions.EventHubs

### Query/Question

Hello Team !!!
So I have a simple **Azure Function Isolated process** with **HttpTrigger** which sends data to **EventHub** through **output binding**. [I have completed all the instructions as the documentation suggested](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs-output?tabs=in-process%2Cfunctionsv2%2Cextensionv5&pivots=programming-language-csharp#identity-based-connections). But I got the following error whenever I run the function:

> [2022-04-27T12:11:14.902Z] System.Private.CoreLib: Exception while executing function: Functions.ManagedIdentitiesFunction. Microsoft.Azure.WebJobs.Host: Unable to resolve the value for property 'EventHubAttribute.Connection'. Make sure the setting exists and has a valid value.

I have provided all the necessary permissions of my **Function App Managed Identity** inside the **Azure EventHub**. But still not working. I have created a similar function app with **InProcess** mechanism. It seems to be **working** with that. Also the documentation has not mentioned clearly whether it should work with **Isolated Process** or not If I am not wrong !!!

**Now My question is:** Does Azure Function **Isolated Process** support **Identity-based connections**? If not, then **when will it be supported**?

### Environment

**dotnet --info:**
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.201 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by JoshLove-msft** [comment]
Hi @ahsanhabib91,
Yes, the isolated worker supports using Identity-based connections. From the exception message, it appears that extension is not able to find your connection setting. If you are running locally, you would need to define the connection setting in local.settings.json. If in a deployed app, it would need to be in your App Settings. Can you confirm that you have defined the connection setting?

**Comment by JoshLove-msft** [comment]
Are you specifying "EventHubConnectionString" for the Connection property in your function?

**Comment by JoshLove-msft** [comment]
Can you let me know which version of the worker extension you are using?

**Comment by ahsanhabib91** [comment]
@JoshLove-msft Here are the packages:
```
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.EventHubs" Version="4.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.3.0" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.6.0" />
```

**Comment by JoshLove-msft** [comment]
Ah ok - the issue is that you are using 4.x of the worker extension for Event Hub, you would need to use the 5.x version - https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.EventHubs/5.0.0-beta.6 as this has the Identity support.

**Comment by ahsanhabib91** [comment]
@JoshLove-msft Thanks !!! I will give a try. If it works, then I will close the issue. 

By the way, is it ok to use the **beta** in **production**?

**Comment by JoshLove-msft** [comment]
It should be okay, note we are planning to ship GA versions soon. The gaps are documented in https://github.com/Azure/azure-functions-dotnet-worker/issues/863

**Comment by ahsanhabib91** [comment]
@JoshLove-msft Thank you very much for your input !!! Works fine now !!! Closing the issue !!!
