### ISSUE TITLE
[BUG] Unable to import any Knowledge base via the custom question answering Import API

### ISSUE THREAD

**Issue by nisarkhan916** [Azure/azure-sdk-for-net#28411]
### Library name and version

Cognitive Services - 2021-10-01

### Describe the bug

The Question Answering Projects - [Import](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/questionanswering/question-answering-projects/import#format) is not uploading the file instead giving **Response Code: 202** and when checked for the import [status](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/questionanswering/question-answering-projects/get-import-status#code-try-0) then getting the below error

 ```
{
  "createdDateTime": "2022-04-27T10:59:38+00:00",
  "expirationDateTime": "2022-04-27T16:59:38+00:00",
  "jobId": "xx365d1f-xxxx-xxx-xxx-xxxxx",
  "lastUpdatedDateTime": "2022-04-27T10:59:38+00:00",
  "status": "failed",
  "errors": [
    {
      "code": "Unspecified",
      "message": "Something happened. Please retry after some time."
    }
  ]
}
```

Note:
1. Tried to upload tsv, xlsx, tsv as Zip, xlsx as Zip. 
2. Tried to upload file which is exported from Language studio Custom question answering (attaching the screenshot below)
![image](https://user-images.githubusercontent.com/64094893/165508094-1c5b4e07-5997-4e66-8dfb-391babfde57a.png)

### Expected behavior

It should upload the Excel or tsv file which contains the QnA pairs and the QnA pairs should be reflected in Language Studio Custom question answering project.

### Actual behavior

Import 
`Response Code: 202`

Import Job Status
`{
  "createdDateTime": "2022-04-27T10:59:38+00:00",
  "expirationDateTime": "2022-04-27T16:59:38+00:00",
  "jobId": "xxxxxx-xxxx-xxxx-xxx-xxxxxxx",
  "lastUpdatedDateTime": "2022-04-27T10:59:38+00:00",
  "status": "failed",
  "errors": [
    {
      "code": "Unspecified",
      "message": "Something happened. Please retry after some time."
    }
  ]
}`

### Reproduction Steps

**Import CURL**
 `curl -X POST -H "Ocp-Apim-Subscription-Key: {API-KEY}" -H "Content-Type: application/json" -d '{
      "ImportJobOptions": {"fileUri": "FILE-URI-PATH"}
  }' -i 'https://{ENDPOINT}.api.cognitive.microsoft.com/language/query-knowledgebases/projects/{PROJECT-NAME}/:import?api-version=2021-10-01&format=tsv'`

**Import Status CURL**
`curl -X GET -H "Ocp-Apim-Subscription-Key: {API-KEY}" -H "Content-Type: application/json" -d '' 'https://southcentralus.api.cognitive.microsoft.com/language/query-knowledgebases/projects/{PROJECT-NAME}/import/jobs/{JOB-ID-GUID}?api-version=2021-10-01'`

### Environment

- VS 19
- Dot Net
- Language Studio Portal

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Plese note this repo is for Azure SDK-related questions. @rokulka could you take a look at this and suggest where customers might submit service/portal feedback for a direct response from the service team / customer support?

**Comment by nisarkhan916** [comment]
@rokulka 
Yes i am trying to upload the file in correct format. The same file is uploaded Successfully via the Language Studio Portal with a **200 OK** status Code. But when same file is been uploaded via API it throws **202 Accepted** Status Code and the file does not upload.

I have Compared the Portal browser logs, the API call details are same as the portal browser logs.

Here is the following asked :
1. Resource Name -- BCV4-ITBOT-LS
2. Region -- westus2

-- Please get back to us with the solution

Thanks

**Comment by Amar92nath** [comment]
@rokulka and @jsquire any update on this issue?

**Comment by rokulka** [comment]
@nisarkhan916 , @Amar92nath - Apologies for the delay. I've looked at the logs and find that the request made to the Import API call has some issue. Please share the request body so that we can take a look.

I would also suggest creating a support ticket via the Azure Portal for the Cognitive Service, so that the Cognitive Services Support team would get involved and could track this issue till closure.

**Comment by nisarkhan916** [comment]
@rokulka, Yes in my case i've been trying to upload a public uri itself and that same file is uploaded Successfully via the Language Studio Portal.
Attaching the CURL for your reference, Please let me know about the API issue.
`curl --location --request POST 'https://xyz-xyz-zyz.cognitiveservices.azure.com/language/query-knowledgebases/projects/TestQnA/:import?api-version=2021-10-01&format=tsv' \
--header 'Ocp-Apim-Subscription-Key: xxxxxad1xxxxxx88xxxx7xxxxxx' \
--header 'Content-Type: application/json' \
--data-raw '{
      "ImportJobOptions": {"fileUri": "https://storageaccountbcv4ib7d4.blob.core.windows.net/document/TestQnA.zip"}
  }'`
  
  
 Thanks

**Comment by nisarkhan916** [comment]
@rokulka -- As you suggested. I've tried with this `https://storageaccountbcv4ib7d4.blob.core.windows.net/document/Test-QnA.zip`

But still getting the same error when checked for  [import job status](https://docs.microsoft.com/en-us/rest/api/cognitiveservices/questionanswering/question-answering-projects/get-import-status)
`{
    "createdDateTime": "2022-05-24T07:58:22+00:00",
    "expirationDateTime": "2022-05-24T13:58:22+00:00",
    "jobId": "7fd86d39-2dbb-4576-8627-517c5adcfc0a",
    "lastUpdatedDateTime": "2022-05-24T07:58:23+00:00",
    "status": "failed",
    "errors": [
        {
            "code": "Unspecified",
            "message": "Something happened. Please retry after some time."
        }
    ]
}`

**Comment by rokulka** [comment]
@nisarkhan916 - Sorry, one more correction I see when I look at the above request. From where did you get figure out that the request JSON should contain `ImportJobOptions` object, it is not needed. Your request JSON should only contain `{"fileUri": "https://storageaccountbcv4ib7d4.blob.core.windows.net/document/TestQnA.zip"}`

**Comment by nisarkhan916** [comment]
Hey @rokulka, Thanks a lot it is working when i remove the `ImportJobOptions`.
I had referred CURL from the  [Authoring API](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/how-to/authoring) and this has the `ImportJobOptions` object in the JSON.

**Comment by rokulka** [comment]
@nisarkhan916 , apologies for that. When you earlier mentioned that you are using the same request body which is you identified from the Language Studio network trace, I didn't suspect that there could be something wrong with that. Anyway, the documentation has a bug from our side. I will create a task item to fix that. Glad to know that it you got it working.

**Comment by nisarkhan916** [comment]
Thanks for the time and help @rokulka & @heaths.
