### ISSUE TITLE
[QUESTION] Does the Test framework support executing tests in parallel?

### ISSUE THREAD

**Issue by dagoroz** [Azure/azure-sdk-for-net#28426]
### Library name and version

Microsoft.Rest.ClientRuntime.Azure.TestFramework 1.7.7

### Query/Question

I am currently using the framework to test the latest SDK generated by autorest and I've noticed that if I click "run all tests in view" in the test explorer I usually get an error like the one bellow. I'm curious whether I'm using the framework in a way that is not intended or if I might have misconfigured something.

worth noting tests behave normally if ran one by one

```
System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.) (The following constructor parameters did not have matching fixture data: TestExecutionContext context)
---- System.NullReferenceException : Object reference not set to an instance of an object.
---- The following constructor parameters did not have matching fixture data: TestExecutionContext context
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  3.1.418 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  
  
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.1.5

**Comment by JoshLove-msft** [comment]
Looks like this issue is about the https://www.nuget.org/packages?q=Microsoft.Rest.ClientRuntime.Azure.TestFramework package, and not our internal Azure.Core.TestFramework library.
