### ISSUE TITLE
Dispose JsonDocument

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#28429]
The following usages of JsonDocument were found where the instance was not being disposed. These should be updated to use the "using" keyword or otherwise call Dispose as needed.

Regex: ^((?!using).)*JsonDocument
Instances (including tests and samples):

azure-sdk-for-net\sdk\agrifood\Azure.Verticals.AgriFood.Farming\README.md
  88,1: var responseDocument = JsonDocument.Parse(response.Content);

azure-sdk-for-net\sdk\monitor\Azure.ResourceManager.Monitor\src\Generated\Models\MultiMetricCriteria.Serialization.cs
  54,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(item.Value.ToString()).RootElement);

azure-sdk-for-net\sdk\personalizer\Azure.AI.Personalizer\src\Models\PersonalizerRankableAction.Serialization.cs
  18,1:             JsonDocument.Parse(JsonSerializer.Serialize(Features)).WriteTo(writer);

azure-sdk-for-net\sdk\personalizer\Azure.AI.Personalizer\src\Models\PersonalizerRankMultiSlotOptions.Serialization.cs
  18,1:                 JsonDocument.Parse(JsonSerializer.Serialize(ContextFeatures)).WriteTo(writer);

azure-sdk-for-net\sdk\personalizer\Azure.AI.Personalizer\src\Models\PersonalizerRankOptions.Serialization.cs
  18,1:                 JsonDocument.Parse(JsonSerializer.Serialize(ContextFeatures)).WriteTo(writer);

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Account\README.md
  68,1: var responseDocument = JsonDocument.Parse(response.Content);

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Account\tests\AccountsClientTest.cs
  26,1:             JsonElement fetchBodyJson = JsonDocument.Parse(GetContentFromResponse(fetchResponse)).RootElement;
  40,1:             JsonElement upateBodyJson = JsonDocument.Parse(GetContentFromResponse(updateRespons)).RootElement;
  55,1:             JsonElement genKeyBodyJson = JsonDocument.Parse(GetContentFromResponse(genResponse)).RootElement;
  69,1:             JsonElement genKeyBodyJson = JsonDocument.Parse(GetContentFromResponse(genResponse)).RootElement;
  72,1:             JsonElement listKeyBodyJson = JsonDocument.Parse(GetContentFromResponse(listKeysResponse)).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Account\tests\CollectionsClientTest.cs
  36,1:             JsonElement createBodyJson = JsonDocument.Parse(GetContentFromResponse(createResponse)).RootElement;
  42,1:                 JsonElement getBodyJson = JsonDocument.Parse(GetContentFromResponse(getResponse)).RootElement;
  65,1:             JsonElement getBodyJson = JsonDocument.Parse(GetContentFromResponse(getResponse)).RootElement;
  71,1:                 JsonElement getJson = JsonDocument.Parse(GetContentFromResponse(getRes)).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Administration\README.md
  70,1: var responseDocument = JsonDocument.Parse(response.Content);
  83,1:     JsonElement fetchBodyJson = JsonDocument.Parse(item).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Administration\tests\AccountsClientTest.cs
  26,1:             JsonElement fetchBodyJson = JsonDocument.Parse(GetContentFromResponse(fetchResponse)).RootElement;
  40,1:             JsonElement upateBodyJson = JsonDocument.Parse(GetContentFromResponse(updateRespons)).RootElement;
  55,1:             JsonElement genKeyBodyJson = JsonDocument.Parse(GetContentFromResponse(genResponse)).RootElement;
  69,1:             JsonElement genKeyBodyJson = JsonDocument.Parse(GetContentFromResponse(genResponse)).RootElement;
  72,1:             JsonElement listKeyBodyJson = JsonDocument.Parse(GetContentFromResponse(listKeysResponse)).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Administration\tests\CollectionsClientTest.cs
  36,1:             JsonElement createBodyJson = JsonDocument.Parse(GetContentFromResponse(createResponse)).RootElement;
  42,1:                 JsonElement getBodyJson = JsonDocument.Parse(GetContentFromResponse(getResponse)).RootElement;
  65,1:             JsonElement getBodyJson = JsonDocument.Parse(GetContentFromResponse(getResponse)).RootElement;
  71,1:                 JsonElement getJson = JsonDocument.Parse(GetContentFromResponse(getRes)).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Administration\tests\MetadataPolicyClientTest.cs
  24,1:             JsonElement fetchBodyJson = JsonDocument.Parse(GetContentFromResponse(fetchResponse)).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Administration\tests\MetadataRolesClientTest.cs
  26,1:                 JsonElement fetchBodyJson = JsonDocument.Parse(item).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Catalog\README.md
  72,1: var responseDocument = JsonDocument.Parse(response.Content);

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Catalog\tests\CatalogClientTest.cs
  29,1:             JsonElement fetchBodyJson = JsonDocument.Parse(GetContentFromResponse(fetchResponse)).RootElement;
  43,1:             JsonElement fetchBodyJson = JsonDocument.Parse(GetContentFromResponse(fetchResponse)).RootElement;
  57,1:             JsonElement fetchBodyJson = JsonDocument.Parse(GetContentFromResponse(fetchResponse)).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Catalog\tests\GlossaryClientTest.cs
  27,1:             JsonElement fetchBodyJson = JsonDocument.Parse(GetContentFromResponse(fetchResponse)).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Scanning\README.md
  72,1: var responseDocument = JsonDocument.Parse(response.Content);

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Scanning\tests\ClassificationRuleClientTest.cs
  69,1:             JsonElement getBodyJson = JsonDocument.Parse(GetContentFromResponse(getResponse)).RootElement;
  74,1:             JsonElement getVersionBodyJson = JsonDocument.Parse(getVersionResponseList.Current).RootElement;
  77,1:             JsonElement getSecondVersionBodyJson = JsonDocument.Parse(getVersionResponseList.Current).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Scanning\tests\DataSourceClientTest.cs
  45,1:             JsonElement getBodyJson = JsonDocument.Parse(GetContentFromResponse(getResponse)).RootElement;
  57,1:             JsonElement fetchBodyJson = JsonDocument.Parse(fetchResponseList.Current).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Scanning\tests\ScanClientTest.cs
  47,1:             JsonElement fetchBodyJson = JsonDocument.Parse(GetContentFromResponse(getResponse)).RootElement;
  61,1:             JsonElement getScanRunListBodyJson = JsonDocument.Parse(getScanRunListResponseList.Current).RootElement;
  130,1:             JsonElement getBodyJson = JsonDocument.Parse(GetContentFromResponse(getResponse)).RootElement;

azure-sdk-for-net\sdk\purview\Azure.Analytics.Purview.Scanning\tests\ScanningServiceClientTest.cs
  26,1:             JsonElement fetchBodyJson = JsonDocument.Parse(fetchResponseList.Current).RootElement;
  37,1:             JsonElement fetchWithTypeBodyJson = JsonDocument.Parse(GetContentFromResponse(fetchWithTypeResponse)).RootElement;
  42,1:             JsonElement fetchWithTypeVersionBodyJson = JsonDocument.Parse(GetContentFromResponse(fetchWithTypeVersionResponse)).RootElement;
  47,1:             JsonElement fetchWithTypeLatestVerBodyJson = JsonDocument.Parse(GetContentFromResponse(fetchWithTypeLatestVerResponse)).RootElement;
  52,1:             JsonElement fetchWithTypeforListBodyJson = JsonDocument.Parse(fetchWithTypeforListResponseList.Current).RootElement;
  75,1:             JsonElement getBodyJson = JsonDocument.Parse(GetContentFromResponse(getResponse)).RootElement;
  88,1:             JsonElement fetchBodyJson = JsonDocument.Parse(fetchResponseList.Current).RootElement;
  98,1:             JsonElement fetchBodyJson = JsonDocument.Parse(fetchResponseList.Current).RootElement;
  136,1:             JsonElement getBodyJson = JsonDocument.Parse(GetContentFromResponse(getResponse)).RootElement;

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\src\Resources\Generated\Models\ArmPolicyParameter.Serialization.cs
  34,1:                     JsonSerializer.Serialize(writer, JsonDocument.Parse(item.ToString()).RootElement);
  45,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(DefaultValue.ToString()).RootElement);

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\src\Resources\Generated\Models\ArmPolicyParameterValue.Serialization.cs
  25,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Value.ToString()).RootElement);

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\src\Resources\Generated\Models\GenericResourceData.Serialization.cs
  33,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Properties.ToString()).RootElement);

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\src\Resources\Generated\Models\ParameterDefinitionsValueMetadata.Serialization.cs
  46,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(item.Value.ToString()).RootElement);

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\src\Resources\Generated\Models\PolicyAssignmentData.Serialization.cs
  76,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Metadata.ToString()).RootElement);

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\src\Resources\Generated\Models\PolicyDefinitionData.Serialization.cs
  50,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(PolicyRule.ToString()).RootElement);
  59,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Metadata.ToString()).RootElement);

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\src\Resources\Generated\Models\PolicySetDefinitionData.Serialization.cs
  45,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Metadata.ToString()).RootElement);

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\tests\Unit\GenericResourceDataTests.cs
  64,1:             JsonElement element = JsonDocument.Parse(json).RootElement;
  75,1:             JsonElement element = JsonDocument.Parse(json).RootElement;

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\tests\Unit\JsonAsserts.cs
  48,1:             return JsonDocument.Parse(memoryStream.ToArray()).RootElement;

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\tests\Unit\ManagedServiceIdentityTest.cs
  21,1:             JsonDocument document = JsonDocument.Parse(json);
  81,1:             JsonDocument document = JsonDocument.Parse(json);

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\tests\Unit\PlanTests.cs
  144,1:             JsonElement element = JsonDocument.Parse(json).RootElement;
  154,1:             JsonElement element = JsonDocument.Parse(json).RootElement;

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\tests\Unit\SkuTests.cs
  170,1:             JsonElement element = JsonDocument.Parse(json).RootElement;
  180,1:             JsonElement element = JsonDocument.Parse(json).RootElement;

azure-sdk-for-net\sdk\resourcemanager\Azure.ResourceManager\tests\Unit\WritableSubResourceTests.cs
  19,1:             var json = JsonDocument.Parse(jsonString).RootElement;

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\samples\Sample2_ManagingDeployments.md
  93,1: var parameters = JsonDocument.Parse(parametersString).RootElement;

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\src\Generated\Models\ArmApplicationData.Serialization.cs
  72,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Parameters.ToString()).RootElement);

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\src\Generated\Models\ArmApplicationDefinitionData.Serialization.cs
  92,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(MainTemplate.ToString()).RootElement);
  101,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(CreateUiDefinition.ToString()).RootElement);

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\src\Generated\Models\ArmApplicationPatch.Serialization.cs
  74,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Parameters.ToString()).RootElement);

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\src\Generated\Models\ArmDeploymentProperties.Serialization.cs
  24,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Template.ToString()).RootElement);
  38,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Parameters.ToString()).RootElement);

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\src\Generated\Models\ArmDeploymentWhatIfProperties.Serialization.cs
  29,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Template.ToString()).RootElement);
  43,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Parameters.ToString()).RootElement);

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\src\Generated\Models\LinkedTemplateArtifact.Serialization.cs
  25,1:             JsonSerializer.Serialize(writer, JsonDocument.Parse(Template.ToString()).RootElement);

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\src\Generated\Models\TemplateSpecData.Serialization.cs
  53,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Metadata.ToString()).RootElement);

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\src\Generated\Models\TemplateSpecVersionData.Serialization.cs
  58,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Metadata.ToString()).RootElement);
  67,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(MainTemplate.ToString()).RootElement);
  76,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(UiFormDefinition.ToString()).RootElement);

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\src\Generated\RestOperations\DeploymentsRestOperations.cs
  912,1:             JsonSerializer.Serialize(content0.JsonWriter, JsonDocument.Parse(template.ToString()).RootElement);

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\tests\ResourcesTestBase.cs
  127,1:             var parameters = JsonDocument.Parse(parametersString).RootElement;

azure-sdk-for-net\sdk\resources\Azure.ResourceManager.Resources\tests\Samples\Sample2_ManagingDeployments.cs
  65,1:             var parameters = JsonDocument.Parse(parametersString).RootElement;

azure-sdk-for-net\sdk\search\Azure.Search.Documents\src\SearchClient.cs
  1357,1:                             await JsonDocument.ParseAsync(message.Response.ContentStream, default, cancellationToken).ConfigureAwait(false) :
  1358,1:                             JsonDocument.Parse(message.Response.ContentStream, default);

azure-sdk-for-net\sdk\search\Azure.Search.Documents\src\Models\SearchResults.cs
  183,1:                 await JsonDocument.ParseAsync(json, cancellationToken: cancellationToken).ConfigureAwait(false) :
  184,1:                 JsonDocument.Parse(json);

azure-sdk-for-net\sdk\search\Azure.Search.Documents\src\Models\SuggestResults.cs
  70,1:                 await JsonDocument.ParseAsync(json, cancellationToken: cancellationToken).ConfigureAwait(false) :
  71,1:                 JsonDocument.Parse(json);

azure-sdk-for-net\sdk\search\Azure.Search.Documents\tests\DocumentOperations\IndexingTests.cs
  855,1:             JsonElement errorElement = JsonDocument.Parse(errorJsonContent).RootElement.GetProperty("error");

azure-sdk-for-net\sdk\search\Azure.Search.Documents\tests\Models\CorsOptionsTests.cs
  15,1:             JsonDocument doc = JsonDocument.Parse(@"{

azure-sdk-for-net\sdk\search\Azure.Search.Documents\tests\Models\EdgeNGramTokenFilterTests.cs
  33,1:             JsonDocument jsonDoc = JsonDocument.Parse(jsonContent);
  51,1:             jsonDoc = JsonDocument.Parse(stream);

azure-sdk-for-net\sdk\search\Azure.Search.Documents\tests\Models\IndexingParametersConfigurationTests.cs
  65,1:             JsonDocument doc = JsonDocument.Parse(json);

azure-sdk-for-net\sdk\search\Azure.Search.Documents\tests\Models\KeywordTokenizerTests.cs
  32,1:             JsonDocument jsonDoc = JsonDocument.Parse(jsonContent);
  49,1:             jsonDoc = JsonDocument.Parse(stream);

azure-sdk-for-net\sdk\search\Azure.Search.Documents\tests\Models\LuceneStandardTokenizerTests.cs
  31,1:             JsonDocument jsonDoc = JsonDocument.Parse(jsonContent);
  47,1:             jsonDoc = JsonDocument.Parse(stream);

azure-sdk-for-net\sdk\search\Azure.Search.Documents\tests\Models\NGramTokenFilterTests.cs
  32,1:             JsonDocument jsonDoc = JsonDocument.Parse(jsonContent);
  49,1:             jsonDoc = JsonDocument.Parse(stream);

azure-sdk-for-net\sdk\search\Azure.Search.Documents\tests\Models\PathHierarchyTokenizerTests.cs
  34,1:             JsonDocument jsonDoc = JsonDocument.Parse(jsonContent);
  54,1:             jsonDoc = JsonDocument.Parse(stream);

azure-sdk-for-net\sdk\storage\Azure.Storage.Blobs.ChangeFeed\src\ChangeFeedFactory.cs
  98,1:             JsonDocument jsonMetaSegment;
  101,1:                 jsonMetaSegment = await JsonDocument.ParseAsync(
  108,1:                 jsonMetaSegment = JsonDocument.Parse(blobDownloadInfo.Content);

azure-sdk-for-net\sdk\storage\Azure.Storage.Blobs.ChangeFeed\src\SegmentFactory.cs
  55,1:             JsonDocument jsonManifest;
  59,1:                 jsonManifest = await JsonDocument.ParseAsync(blobDownloadStreamingResult.Content).ConfigureAwait(false);
  63,1:                 jsonManifest = JsonDocument.Parse(blobDownloadStreamingResult.Content);

azure-sdk-for-net\sdk\storage\Azure.Storage.Common\src\Shared\StorageClientDiagnostics.cs
  62,1:                     JsonDocument json = JsonDocument.Parse(content);

azure-sdk-for-net\sdk\storage\Azure.Storage.Files.DataLake\src\ErrorExtensions.cs
  37,1:                 JsonDocument json = JsonDocument.Parse(body);

azure-sdk-for-net\sdk\synapse\Azure.Analytics.Synapse.AccessControl\README.md
  113,1: JsonDocument roleDefinitionsJson = JsonDocument.Parse(roleDefinitionsContent.ToMemory());
  140,1: JsonDocument addedRoleAssignmentJson = JsonDocument.Parse(addedRoleAssignmentContent.ToMemory());
  151,1: JsonDocument roleAssignmentJson = JsonDocument.Parse(roleAssignmentContent.ToMemory());
  164,1: JsonDocument roleAssignmentsJson = JsonDocument.Parse(roleAssignmentsContent.ToMemory());

azure-sdk-for-net\sdk\synapse\Azure.Analytics.Synapse.AccessControl\samples\Sample1_HelloWorld.md
  24,1: JsonDocument roleDefinitionsJson = JsonDocument.Parse(roleDefinitionsContent.ToMemory());
  51,1: JsonDocument addedRoleAssignmentJson = JsonDocument.Parse(addedRoleAssignmentContent.ToMemory());
  62,1: JsonDocument roleAssignmentJson = JsonDocument.Parse(roleAssignmentContent.ToMemory());
  75,1: JsonDocument roleAssignmentsJson = JsonDocument.Parse(roleAssignmentsContent.ToMemory());

azure-sdk-for-net\sdk\synapse\Azure.Analytics.Synapse.AccessControl\tests\samples\Sample1_HelloWorld.cs
  38,1:             JsonDocument roleDefinitionsJson = JsonDocument.Parse(roleDefinitionsContent.ToMemory());
  71,1:             JsonDocument addedRoleAssignmentJson = JsonDocument.Parse(addedRoleAssignmentContent.ToMemory());
  79,1:             JsonDocument roleAssignmentJson = JsonDocument.Parse(roleAssignmentContent.ToMemory());
  88,1:             JsonDocument roleAssignmentsJson = JsonDocument.Parse(roleAssignmentsContent.ToMemory());

azure-sdk-for-net\sdk\webpubsub\Azure.Messaging.WebPubSub\src\WebPubSubServiceClient_helpers.cs
  110,1:                 token = JsonDocument.Parse(clientTokenResponse.Content).RootElement.GetProperty(ClientTokenResponseTokenPropertyName).GetString();

azure-sdk-for-net\sdk\webpubsub\Microsoft.Azure.WebPubSub.Common\src\Internal\BinaryDataJsonConverter.cs
  35,1:             var doc = JsonDocument.ParseValue(ref input);

azure-sdk-for-net\sdk\webpubsub\Microsoft.Azure.WebPubSub.Common\src\Internal\ConnectEventRequestJsonConverter.cs
  15,1:             var element = JsonDocument.ParseValue(ref reader).RootElement;

azure-sdk-for-net\sdk\webpubsub\Microsoft.Azure.WebPubSub.Common\src\Internal\DisconnectedEventRequestJsonConverter.cs
  14,1:             var element = JsonDocument.ParseValue(ref reader).RootElement;

azure-sdk-for-net\sdk\webpubsub\Microsoft.Azure.WebPubSub.Common\src\Internal\WebPubSubClientCertificateJsonConverter.cs
  14,1:             var element = JsonDocument.ParseValue(ref reader).RootElement;

azure-sdk-for-net\sdk\webpubsub\Microsoft.Azure.WebPubSub.Common\src\Shared\ConnectionStatesConverter.cs
  29,1:                 var element = JsonDocument.ParseValue(ref reader).RootElement;

azure-sdk-for-net\sdk\websites\Azure.ResourceManager.AppService\src\Generated\Models\ContinuousWebJobData.Serialization.cs
  84,1:                     JsonSerializer.Serialize(writer, JsonDocument.Parse(item.Value.ToString()).RootElement);

azure-sdk-for-net\sdk\websites\Azure.ResourceManager.AppService\src\Generated\Models\FunctionEnvelopeData.Serialization.cs
  69,1:                 JsonSerializer.Serialize(writer, JsonDocument.Parse(Config.ToString()).RootElement);

azure-sdk-for-net\sdk\websites\Azure.ResourceManager.AppService\src\Generated\Models\StackMajorVersion.Serialization.cs
  75,1:                     JsonSerializer.Serialize(writer, JsonDocument.Parse(item.Value.ToString()).RootElement);
  90,1:                     JsonSerializer.Serialize(writer, JsonDocument.Parse(item.Value.ToString()).RootElement);

azure-sdk-for-net\sdk\websites\Azure.ResourceManager.AppService\src\Generated\Models\TriggeredWebJobData.Serialization.cs
  84,1:                     JsonSerializer.Serialize(writer, JsonDocument.Parse(item.Value.ToString()).RootElement);

azure-sdk-for-net\sdk\websites\Azure.ResourceManager.AppService\src\Generated\Models\WebJobData.Serialization.cs
  69,1:                     JsonSerializer.Serialize(writer, JsonDocument.Parse(item.Value.ToString()).RootElement);

_Originally posted by @JoshLove-msft in https://github.com/Azure/azure-sdk-for-net/pull/28425#issuecomment-1111593787_

**Comment by levimatheri** [comment]
@JoshLove-msft I'd be interested in taking this up.

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft I'd be interested in taking this up.

Thanks @levimatheri! Please let me know if you have any questions!

**Comment by levimatheri** [comment]
@JoshLove-msft I'm assuming this needs to be done for generated code examples as well, like here? https://github.com/Azure/azure-sdk-for-net/blob/588b4e4063b8453f89758d49014c1fbc9684580d/sdk/agrifood/Azure.Verticals.AgriFood.Farming/src/Generated/AttachmentsClient.cs#L83

**Comment by JoshLove-msft** [comment]
I think that should also be updated, but it doesn't need to be addressed as part of this issue. @AlexanderSher do you know where the code that generates the above code sample lives?
