### ISSUE TITLE
[Question] How to identify which ETag belongs to which entity on SubmitTransactionAsync. 

### ISSUE THREAD

**Issue by xDDDx** [Azure/azure-sdk-for-net#28439]
### Library name and version

Azure.Data.Tables 12.0.3

### Query/Question

We have some batch operations and we need the new `ETag` value after an update. The Response of an update is `No Content` with an `ETag` header. That's okay for a single operation. We can just update the entity. 

But how to assigne the `ETag` to correct entity after a batch `SubmitTransactionAsync` operation?

**Comment by christothes** [comment]
Hi @xDDDx  - The result from `SubmitTransactionAsync` is a list of responses and each Response has a standard set of named headers.

https://github.com/Azure/azure-sdk-for-net/blob/57955d89d59e50dffa5e18786d37f090d8298964/sdk/tables/Azure.Data.Tables/src/TableClient.cs#L1381

Here is how you'd get the ETag for the nth element in the batch:

```C#
var batchResponse = await client.SubmitTransactionAsync(batch);
var myEtag = batchResponse.Value[n].Headers.ETag;
```

**Comment by xDDDx** [comment]
@christothes but how I identify which ETag belongs to which entity?
```
private async Task<IEnumerable<TResult>> ExecuteAsBatchAsync(TableTransactionActionType tableOperation, List<TResult> entities)
{

    List<TableTransactionAction> batch = new List<TableTransactionAction>();
    entities.ForEach(x => batch.Add(new TableTransactionAction(tableOperation, x, ETag.All)));
    var response = await _table.Value.SubmitTransactionAsync(batch);
    foreach (var item in response.Value)
    {
        var headersETag = item.Headers.ETag;
        // TODO: find entity
        entities.First(x => ???)
    }
    return entities;
}
```

**Comment by christothes** [comment]
> @christothes but how I identify which ETag belongs to which entity?

The responses are in the same order as the input `batch`

**Comment by xDDDx** [comment]
Okay, Thanks!
