### ISSUE TITLE
[BUG] Not receving knowledge base answers from Custom Question Answering with an Orchestration Workflow using SDK

### ISSUE THREAD

**Issue by rliberoff** [Azure/azure-sdk-for-net#28434]
### Library name and version

Azure.AI.Language.Conversations 1.0.0-beta.3

### Describe the bug

When using the ConversationAnalysisClient to retrieve predictions from an Orchestrator connected to a Custom Question Answering (CQA), and giving a valid question message, the result successfully predicts the CQA intent, however the answers collection is empty when it should contain the expected answer of the question.

### Expected behavior

As it is documented in GitHub [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples/Sample2_AnalyzeConversation_OrchestrationPrediction.md#question-answering), if the given question is valid, the Orchestration should return the answer for the question within the prediction result.

### Actual behavior

When using the ConversationAnalysisClient and giving a valid question, the prediction is correct but the answers collection is empty.

### Reproduction Steps

```
var endpoint = new Uri(@"https://<language_studio_name>.cognitiveservices.azure.com");
var credential = new AzureKeyCredential("<primary_key>");
var conversationAnalysisClient = new ConversationAnalysisClient(endpoint, credential);

var input = new TextConversationItem(participantId: "1", id: "1", text: message)
{
    Language = "es"
};

var opt = new AnalyzeConversationOptions(input);

Response<AnalyzeConversationTaskResult> response = 
    await _conversationAnalysisClient.AnalyzeConversationAsync(message, _conversationsProject, opt);

var customConversationalTaskResult = response.Value as CustomConversationalTaskResult;
var orchestratorPrediction = customConversationalTaskResult.Results.Prediction as OrchestratorPrediction;
var targetIntentResult = orchestratorPrediction.Intents[orchestratorPrediction.TopIntent];
var questionAnsweringTargetIntentResult = targetIntentResult as QuestionAnsweringTargetIntentResult;

KnowledgeBaseAnswers knowledgeBaseAnswers = questionAnsweringTargetIntentResult.Result;
var answers = knowledgeBaseAnswers.Answers; // THIS IS EMPTY, HOWEVER THERE SHOULD BE ANSWERS!!!
```

### Environment

Windows 10
.NET 6.0
Visual Studio 2022 17.1.5

**Comment by rliberoff** [comment]
A bit more of information in this screenshot:

![image](https://user-images.githubusercontent.com/5644891/165709127-26ec7e0d-a6bf-44e8-8b71-bb18bf345979.png)

We really appreciate your help!

Thank you!

**Comment by rliberoff** [comment]
A bot more information. When calling the REST API, it looks correct, so We think that the issue might be in the SDK when parsing the response from the service.

For example, for the following request:

```
POST /language/:analyze-conversations?api-version=2022-03-01-preview HTTP/1.1
Host: <language_studio_name>.cognitiveservices.azure.com
Ocp-Apim-Subscription-Key: <primary_key>
Content-Type: application/json
Content-Length: 398

{
    "analysisInput": {
        "conversationItem": {
            "text": "Hola",
            "participantId": "1",
            "id": "1",
            "language": "es",
            "modality": "text"
        }
    },
    "parameters": {
        "projectName": "Orquestador",
        "deploymentName": "production",
        "verbose": false
    },
    "kind": "CustomConversation"
}
```

We get a correct response which includes the answer. However, at SDK level with the C# code, the answers collection is empty 🤨

```
{
    "kind": "CustomConversationResult",
    "results": {
        "query": "Hola",
        "prediction": {
            "topIntent": "KB",
            "projectKind": "workflow",
            "intents": {
                "KB": {
                    "confidenceScore": 0.99789613,
                    "targetKind": "question_answering",
                    "result": {
                        "responseBody": {
                            "answers": [
                                {
                                    "questions": [
                                        "Hey, ¿qué tal?",
                                        "Hi",
                                        "Ey",
                                        "Hey, ¿qué dices?",
                                        "Hola, ¿qué te cuentas?"                                        
                                    ],
                                    "answer": "Hola",
                                    "confidenceScore": 1.0,
                                    "id": 53,
                                    "source": "ChitChat",
                                    "metadata": {
                                        "editorial": "chitchat"
                                    },
                                    "dialog": {
                                        "isContextOnly": false,
                                        "prompts": []
                                    }
                                }
                            ]
                        }
                    }
                },
                "None": {
                    "confidenceScore": 0,
                    "targetKind": "non_linked"
                }
            }
        }
    }
}
```

We really need help with this, and also really appreciate your support!

Thank you!

**Comment by rliberoff** [comment]
BTW, this also happens with the previos version of the SDK -> Azure.AI.Language.Conversations 1.0.0-beta.2

**Comment by Sergio-QA** [comment]
The same is happening to me

**Comment by CrespoColeto** [comment]
I was going crazy, I finally see what is the problem. Hope they fix it soon!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by rliberoff** [comment]
Thank you @jsquire. We really need help with this issue. Much appreciated.

**Comment by heaths** [comment]
Thank you for reporting this issue.

@ChongTang the service is returning an invalid response:

```
                    "result": {
                        "responseBody": {
                            "answers": [
```

Per the [specification](https://github.com/Azure/azure-rest-api-specs/blob/c24e31390f7bde23664f43190d9184f5fbbbd24f/specification/cognitiveservices/data-plane/Language/preview/2022-03-01-preview/analyzeconversations.json#L1410-L1414), `answer` should be nested directly within `result`, as defined in the [target model specification](https://github.com/Azure/azure-rest-api-specs/blob/c24e31390f7bde23664f43190d9184f5fbbbd24f/specification/cognitiveservices/data-plane/Language/preview/2021-07-15-preview/questionanswering.json#L230-L243).

/cc @annatisch @ZulaMostafa @mshaban-msft

**Comment by ChongTang** [comment]
@heaths , the issue should be fixed. Can you try again?

**Comment by rliberoff** [comment]
Hi @ChongTang!

Please allow me to answer you tomorrow. Today is a festive day in Spain, and nobody is working. Tomorrow, first time in the morning, my team will test this and verify everything is working as expected.

Thank you.

**Comment by rliberoff** [comment]
Hi @ChongTang!

The issue is fixed. Everything seems to be working as expected. This bug can be closed.

Thank you all for the great support and your help.

**Comment by ChongTang** [comment]
Glad to help. @heaths, I don't have permission to close it. Can you help me?

**Comment by heaths** [comment]
Will do. Thanks, @ChongTang!
