### ISSUE TITLE
Can't set secret and its value using Azure.Security.KeyVault.Secrets SDK

### ISSUE THREAD

**Issue by alexwilsh** [Azure/azure-sdk-for-net#28455]
I'm using Azure.Security.KeyVault.Secrets v4.3.0 and the method SetSecretAsync of SecretClient. It's failing with following error:

```
System.TypeInitializationException: "The type initializer for 'Azure.Security.KeyVault.Secrets.KeyVaultSecret' threw an exception." ---> System.IO.FileNotFoundException: "Could not load file or assembly 'System.Text.Encodings.Web, Version=4.0.5.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.\n"
  --- End of inner exception stack trace ---
  at at Azure.Security.KeyVault.Secrets.KeyVaultSecret.WriteProperties(Utf8JsonWriter json)
```
I'm using Visual Studio Community 2019 for Mac, Version 8.10.22 (build 11).
The project is Azure Functions application. I'm debugging it locally using Azure Functions tools.
I cleared up the NuGet cache, removed all stalled System.Text.Encodings.Web assemblies on my Mac.

Here is the list of references across 4 different projects within the solution that reference each other:
```
project 1:
<ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.24.0" />
    <PackageReference Include="Azure.Security.KeyVault.Certificates" Version="4.3.0" />
    <PackageReference Include="Azure.Security.KeyVault.Keys" Version="4.3.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.3.0" />
    <PackageReference Include="FluentValidation" Version="10.4.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="10.4.0" />
    <PackageReference Include="Microsoft.FeatureManagement" Version="2.5.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="3.1.24" />
    <PackageReference Include="Azure.ResourceManager.KeyVault" Version="1.0.0-beta.6" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.1" />
    <PackageReference Include="AutoMapper" Version="10.1.1" />
  </ItemGroup>

project 2:
<ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.23" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="4.0.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.13" />
    <PackageReference Include="Microsoft.FeatureManagement.AspNetCore" Version="2.4.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.1.0" />
  </ItemGroup>

project 3:
<ItemGroup>
    <PackageReference Include="Azure.Data.Tables" Version="12.5.0" />
    <PackageReference Include="Azure.Storage.Queues" Version="12.9.0" />
  </ItemGroup>

project 4:
<ItemGroup>
    <PackageReference Include="Microsoft.Azure.Management.Fluent" Version="1.38.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="3.1.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.20" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.1.20" />
    <PackageReference Include="Azure.Identity" Version="1.6.0" />
    <PackageReference Include="Azure.ResourceManager" Version="1.0.0-beta.8" />
  </ItemGroup>
```

Project 4 from the list above has the code that is failing. It references project 1. Project 1 references project 3.
Project 2 (main project) references project 4 and project 1.

Looks like some package is messing everything up or this is the bug in Azure.Security.KeyVault.Secrets.
Do you have any guidance about Azure SDK on which versions of mentioned packages can be used together? 

Thanks in advance.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
This is likely due to an older copy the Azure Functions SDK copied to output. Update to the latest Microsoft.NET.Sdk.Functions and, if that still repos, find and delete any copies of System.Text.Encodings.Web, then build again and deploy.

For more information, please see #23902.

**Comment by alexwilsh** [comment]
Thanks for replying back.
Yeah, I did that many times: removed bin & obj, cleared NuGet caches, I also removed all assemblies I could find on my machine.
As for SDK, I'm using Microsoft.NET.Sdk.Functions, Version="3.1.0". Are you saying that this SDK is not valid anymore and I have to switch to version 4?

I also tried setting the property you mentioned - it didn't work. Same issue.

**Comment by alexwilsh** [comment]
After multiple tries to pick up a correct combination of versions I found that it's working without TypeInitializationException with "Microsoft.NET.Sdk.Functions" Version="3.0.11".
I'll stick with this old version for now.

**Comment by heaths** [comment]
I've started a thread with the Azure Functions SDK team and we'll work to resolve this. Could you tell me the file version of System.Text.Encodings.Web you found that is getting loaded?

**Comment by alexwilsh** [comment]
Thanks for working on this.
I saw 4.7.2 version of System.Text.Encodings.Web and it was referenced by multiple packages including "Azure.Security.KeyVault.Secrets" one.

Btw, it's not that easy to investigate this type of issues with Visual Studio for Mac :)

**Comment by pallavit** [comment]
@heaths was there any follow-up with the function team here?

**Comment by heaths** [comment]
Sorry, but this seems to have slipped through the cracks. Was this still a problem? Dependencies across the Azure Functions runtime, PowerShell support, etc., have all since been updated so I'm hopeful this is no longer a problem.

**Comment by alex-zar** [comment]
yeah, this was more than a year ago :)
I bet we already migrated to a newer .NET version and newer runtime since then. I haven't heard about such issues tbh. Let's consider this as addressed. I will reach out if it is not.
