### ISSUE TITLE
[QUERY] How do you Mock a ResourceGroupResource?

### ISSUE THREAD

**Issue by ealsur** [Azure/azure-sdk-for-net#28453]
### Library name and version

Azure.ResourceManager 1.0.0

### Query/Question

I want to Mock a ResourceGroupResponse and set a particular provisioning state and tags to the ResourceGroupData:

```
Mock<ResourceGroupResource> rg= new Mock<ResourceGroupResource>();
rg.Setup(r => r.Id).Returns(ResourceGroupResource.CreateResourceIdentifier("subId", "name");
rg.Setup(r => r.HasData).Returns(true);
Mock<ResourceGroupData> rgData= new Mock<ResourceGroupData>(AzureLocation.AustraliaCentral);
rgData.Setup(d => d.ResourceGroupProvisioningState).Returns("Deleting");
rgData.Setup(d => d.Tags).Returns(new Dictionary<string, string>() { { "tagName", "tagValue" } });
rg.Setup(r => r.Data).Returns(rgData.Object);
```

But ResourceGroupProvisioningState cannot be mocked:

```
Non-overridable members (here: ResourceGroupData.get_ResourceGroupProvisioningState) may not be used in setup / verification expressions.
```

The code depends on Properties, but Properties can only be set through the Internal constructor.

The same problem happens if I try to Mock the Tags:

```
Non-overridable members (here: TrackedResourceData.get_Tags) may not be used in setup / verification expressions.
```

What is the recommended approach to mock the ResourceGroupData?

**Comment by ealsur** [comment]
Hi @ArthurMa1978, is there a way to Mock these types or another way to simulate this content (ResourceGroupData) in a ResourceGroupResource for testing purposes?

**Comment by ArthurMa1978** [comment]
@ealsur thank you for reaching us,  due to the internal / private constructor design all models can be mocked now, but we will provide a model fatory feature to provide mock capability, here is the https://github.com/azure/autorest.csharp/issues/2112 opened

**Comment by ArthurMa1978** [comment]
Close as feature task created
