### ISSUE TITLE
Check PiiEntities options.CategoriesFilter

### ISSUE THREAD

**Issue by nisha-bhatia** [Azure/azure-sdk-for-net#28465]
We need to check to see if there is content in the options.Categories array. We don't want to pass the service an empty list.

Legacy code had https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/src/TextAnalyticsClient.cs#L1005

**Comment by heaths** [comment]
_Transforms.Legacy.cs_ has:
```C#
            if (action.CategoriesFilter.Count > 0)
            {
                parameters.PiiCategories = new List<Legacy.Models.PiiEntityLegacyCategory>(action.CategoriesFilter.Count);

                foreach (var category in action.CategoriesFilter)
                {
                    parameters.PiiCategories.Add(new Legacy.Models.PiiEntityLegacyCategory(category.ToString()));
                }
            }
```
Also, by default, it's assigned a `ChangeTrackingList` so empty collections won't be serialized by default.

**Comment by heaths** [comment]
Checking recorded sessions proves an empty collection is not sent to the service as well. Closing.
