### ISSUE TITLE
[BUG] ##[error]ASPNETCOMPILER(0,0): Error ASPRUNTIME: Type is not resolved for member 'Azure.Identity.CredentialUnavailableException,Azure.Identity, Version=1.5.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'.

### ISSUE THREAD

**Issue by tegrit-joe-trupiano** [Azure/azure-sdk-for-net#28479]
### Library name and version

Azure.Identity 1.5.0.0

### Describe the bug

When using the build solution task in azure pipelines I get this error. If I remove /p:PrecompileBeforePublish=true from the build args it will build fine. Also if I remove the `<connectionStrings configBuilders="AzureKeyVault">` from the web config it will build fine.

location ---------------------
-azure devops
-piplines
-build solution task

ms build args----
/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\" /p:PrecompileBeforePublish=true /p:UseMerge=true /p:SingleAssemblyName=CompiledViews

### Expected behavior

Does not throw an error in the "Visual Studio build" task when using azure devops - pipelines

### Actual behavior

thorws this error for every project that uses the azure.identity

##[error]ASPNETCOMPILER(0,0): Error ASPRUNTIME: Type is not resolved for member 'Azure.Identity.CredentialUnavailableException,Azure.Identity, Version=1.5.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'.

### Reproduction Steps

Set up a pipeline in azure devops that uses the 'Visual Studio build' task and build a project that uses keyvaults from the web config using these msbuild args

ms build args----
/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\" /p:PrecompileBeforePublish=true /p:UseMerge=true /p:SingleAssemblyName=CompiledViews

### Environment

Windows 10
.Net Framework 4.7.2
Microsoft Visual Studio Enterprise 2019-Version 16.11.11
Azure devops Pipeline

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by Saurabhsrikant** [comment]
@tegrit-joe-trupiano 
Are you able to figure out the problem?
Please share fix details.

**Comment by tegrit-joe-trupiano** [comment]
> @tegrit-joe-trupiano Are you able to figure out the problem? Please share fix details.

I did not, Sorry

**Comment by 42jdg** [comment]
@tegrit-joe-trupiano Any update?

**Comment by christothes** [comment]
Hi @tegrit-joe-trupiano - This issue looks similar, do any of the workarounds or suggestions there work for you? #17216

**Comment by tegrit-joe-trupiano** [comment]
> @tegrit-joe-trupiano Any update?

Nope nothing yet

**Comment by tegrit-joe-trupiano** [comment]
> Hi @tegrit-joe-trupiano - This issue looks similar, do any of the workarounds or suggestions there work for you? #17216

None of the work arounds worked for me as we are using devops/piplelines. I opened this issue because 17216 was closed and nothing in it was helpful for my case.

**Comment by christothes** [comment]
@tegrit-joe-trupiano - Is it possible that the build is either finding an older version of Azure.Identiy, or cannot find it at all? Does you build output show which version is being found?

**Comment by tegrit-joe-trupiano** [comment]
> @tegrit-joe-trupiano - Is it possible that the build is either finding an older version of Azure.Identiy, or cannot find it at all? Does you build output show which version is being found?

It only happens when ms build arg p:PrecompileBeforePublish=true. I had to disable this param for every build and it slows down our production sites on startup without it.

**Comment by christothes** [comment]
> > @tegrit-joe-trupiano - Is it possible that the build is either finding an older version of Azure.Identiy, or cannot find it at all? Does you build output show which version is being found?
> 
> It only happens when ms build arg p:PrecompileBeforePublish=true. I had to disable this param for every build and it slows down our production sites on startup without it.

Understood - but I'm curious which version of Azure.Identity your build is resolving in that case.

**Comment by christothes** [comment]
Can you confirm that you are unable to reproduce the error with the same build command locally (with the paths fixed up to be correct for local)?

**Comment by tegrit-joe-trupiano** [comment]
> Can you confirm that you are unable to reproduce the error with the same build command locally (with the paths fixed up to be correct for local)?
I just tested this and Yes I still get the same error locally running the same command from developer command prompt

**Comment by 42jdg** [comment]
@tegrit-joe-trupiano At least in my case, It looks like the process needs to connect to Azure, but it doesn't connect using TLS1.2
I apply the suggested changes to the windows registry: https://learn.microsoft.com/en-us/dotnet/framework/network-programming/tls
After this, the compilation was successful without the parameter "/p:PrecompileBeforePublish=true"

Additionally, I added the enviroment's variables AZURE_CLIENT_ID, AZURE_CLIENT_SERCRET, and AZURE_TENANT_ID (added to my pipeline variables)

**Comment by tegrit-joe-trupiano** [comment]
> @tegrit-joe-trupiano At least in my case, It looks like the process needs to connect to Azure, but it doesn't connect using TLS1.2 I apply the suggested changes to the windows registry: https://learn.microsoft.com/en-us/dotnet/framework/network-programming/tls After this, the compilation was successful without the parameter "/p:PrecompileBeforePublish=true"
> 
> Additionally, I added the enviroment's variables AZURE_CLIENT_ID, AZURE_CLIENT_SERCRET, and AZURE_TENANT_ID (added to my pipeline variables)

Hi, looks like adding the environment variables for key vault to the pipeline variables did the trick. I was 99% sure I had already tried that, but I guess not. Thanks for the help!

**Comment by grammophone** [comment]
The exact problem happens to me within Visual Studio 2019 and 2022 publishing with precompiling enabled. The registry update didn't fix it. I have been revisiting the problem for months, updating libraries, to no avail. Again, if I turn off precompiling, it works. Setting azure keys in environment variables of development machines is off the question for obvious reasons.
