### ISSUE TITLE
spelling mistake "deault" should be default

### ISSUE THREAD

**Issue by HHK01** [Azure/azure-sdk-for-net#28482]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6fb2304-2d8f-f8ca-f52e-a93e96591cc3
* Version Independent ID: b2da20b0-27c6-06fd-e181-b6af7ffbc4b4
* Content: [RequestOptions.SessionToken Property (Microsoft.Azure.Documents.Client) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.sessiontoken?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Documents.Client/RequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents.Client/RequestOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SatishBoddu-MSFT** [comment]
Hello @HHK01 
Thanks for the feedback! We are currently investigating and will update you shortly.
