### ISSUE TITLE
Support Azure.Monitor.OpenTelemetry.Exporter with .NET 6

### ISSUE THREAD

**Issue by christiannagel** [Azure/azure-sdk-for-net#28483]
### Library name

Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

The latest version of Azure.Monitor.OpenTelemetry.Exporter (1.0.0-beta.3) has a dependency with Microsoft.Extensions.Logging >= 2.1.0 && < 6.0.0. 

Using EF Core 6, the dependency to Microsoft.Extensions.Logging is >= 6.0.0.

This results in a version conflict compiler error with the information to directly reference Microsoft.Extensions.Logging 6.0.0. However, this fails because Azure.Monitor.OpenTelemetry.Exporter requires a version smaller than 6.0.0.

Is there a different solution to use this package with .NET 6? When can we expect the next version?

**Comment by SatishBoddu-MSFT** [comment]
Hello @christiannagel 
Thanks for the feedback! We are currently looking into this and will update you shortly.

**Comment by cijothomas** [comment]
The limitation/restriction is *NOT* from this library, but *was* from OpenTelemetry SDK itself. You can update OpenTelemetry nuget package to 1.2, and this issue should be gone.
(The upcoming release of Azure.Monitor.OpenTelemetry.Exporter will pick OpenTelemetry 1.2 automatically, so you can simply wait for that release also.)
