### ISSUE TITLE
[BUG] VirtualMachineScaleSetResource.UpdateInstancesAsync should allow update of a VM with new VirtualMachineScaleSetVmResource data

### ISSUE THREAD

**Issue by stishkin** [Azure/azure-sdk-for-net#28491]
### Library name and version

1.0.0.0-beta.8

### Describe the bug

Calling VirtualMachineScaleSetResource.UpdateInstanceAsync currently causes upgrade to the latest OS and does permit update of VM settings (for example changing ProtectionFromScaleIn).

This seems to be a duplicate behavior as VirtualMachineScaleSetResource.Reimage

### Expected behavior

Calling VirtualMachineScaleSetResource.UpdateInstanceAsync accepts a parameter with updated VirtualMachineScaleSetVmResource  values and sets those on specified VMs

### Actual behavior

There is none

### Reproduction Steps

Try to set new VirtualMachineScaleSetVmProtectionPolicy, and there is no way to do it.

var newProtectionPolicy = new VirtualMachineScaleSetVmProtectionPolicy() { ProtectFromScaleIn = true };

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
@stishkin can you use the following code to achieve the same purpose?
`virtualMachineScaleSetResource.GetVirtualMachineScaleSetVms().CreateOrUpdateAsync();` where you can pass in a `VirtualMachineScaleSetVmData` containing the updated `VirtualMachineScaleSetVmProtectionPolicy`.

Refer to the API below:
https://github.com/Azure/azure-sdk-for-net/blob/1e11c266329079133cdb62c7fe9738068002c529/sdk/compute/Azure.ResourceManager.Compute/src/Generated/VirtualMachineScaleSetVmCollection.cs#L68

**Comment by stishkin** [comment]
@fengzhou-msft  - thank you, that worked !
