### ISSUE TITLE
Consider adding explicit net6.0 targetFramework outputs for all clients

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#28492]
### Library name

Azure.Core

### Please describe the feature.

From [this customer issue](https://github.com/Azure/azure-sdk-for-net/issues/28477#issuecomment-1115123289)

Consider targeting newer frameworks to reduce client dependency sets. For any packages which have been absorbed into the framework this is safe and compatible. We can also potentially benefit by using the new API and functionality available in those new frameworks.

PS: The only place to be careful about this is with packages like Microsoft.BCL.AsyncInterfaces -- those were not absorbed by the framework and need to remain exposed -- or even better if you ever use them try to avoid exposing them by using PrivateAssets="Compile"

**Comment by AraHaan** [comment]
Sad we cant look into alternatives to ``Microsoft.BCL.AsyncInterfaces`` that are built into the framework.

**Comment by AraHaan** [comment]
Oh interesting:
![image](https://user-images.githubusercontent.com/15173749/166338136-cb567c49-fdb2-4929-8b3d-6ed38e903cb1.png)

**Comment by ViktorHofer** [comment]
> I guess for .NET an experiment could be done to see if the Azure SDK will compile without the reference on .NET Core/5 and 6+ TFMs. That dependency might just be adding type forwards to everything in it to things in System.Runtime.

Correct. Microsoft.Bcl.AsyncInterfaces is just a facade when used on any tfm that's compatible with netstandard2.1 (.NETCoreApp mainly): https://github.com/dotnet/runtime/blob/e3860440c151897968eca2227ae98c1912580c44/src/libraries/Microsoft.Bcl.AsyncInterfaces/src/Microsoft.Bcl.AsyncInterfaces.csproj#L15.

I don't have full context on what your clients currently target but the Microsoft.Bcl.AsyncInterfaces package should only be required when targeting .NETFramework or .NETStandard < 2.1.

**Comment by pallavit** [comment]
@christothes given our latest conversation on target frameworks - do you still see this as a valid concern?
