### ISSUE TITLE
[BUG] `SearchDocument.ToString()` does not properly serialize collection properties

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#28500]
### Library name and version

Azure.Search.Documents

### Describe the bug

See reproduction steps.

### Expected behavior

See reproduction steps.

### Actual behavior

See reproduction steps.

### Reproduction Steps

Create a new `SearchDocument` from the below string as - 
```
string jsonDocument = "
{
  \"@search.score\":1.0,
  \"r\":4,
  \"c\":
  [
    {
      \"Key\":\"TestKey\",
      \"Value\":\"TestValue001\"
    }
  ]
}";
SearchDocument searchDocument = new SearchDocument(JsonConvert.DeserializeObject<Dictionary<string, object>>(jsonDocument));
```

Extract the property `c` and try to serialize it using `ToString()` -
```
searchDocument.TryGetValue("c", out object collection); 
string s = collection.ToString();
```

**Expected**: `s` should be the serialized string representation of the array property `c`.
**Actual**: `s` is an empty collection object

**Comment by Mohit-Chakraborty** [comment]
As per @tg-msft - "this is because `JsonConvert.Deserialize()` with a `Dictionary<string, object>` isn’t going to recurse and our code doesn’t correctly handle Newtonsoft’s JArray.  We should consider yanking the [client’s object serializer](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/SearchDocument/SearchDocument.cs#L198) to use when we’re returning a `SearchDocument`.  We could also look at whether Newtonsoft types implement standard .NET collection interfaces in a way we could light up (I’m going to guess things like `IList` instead of `IList<object>` would make a difference)."

**Comment by pallavit** [comment]
This was the bug I was talking about for serialization for search. @tg-msft , @ShivangiReja

**Comment by ShivangiReja** [comment]
Based on the provided reproduction steps, it seems that the `s` is not serialized as an empty object. Instead, it appears to contain the string representation of the array property `c`:
![image](https://github.com/Azure/azure-sdk-for-net/assets/45216704/efcfbf00-6908-4993-aaa1-14c4f5ad6f87)
