### ISSUE TITLE
[QUERY]Documentation on using Template specs with Azure Sdk for .Net

### ISSUE THREAD

**Issue by wimeling** [Azure/azure-sdk-for-net#28505]
### Library name and version

Azure.ResourceManager.Resources

### Query/Question

Hello,

I am searching for documentation on how to use Azure Template Specs. I have found some unit tests to guide me in a direction. But I cannot find any documentation on how to use Template Specs together with c# to create a Azure Deployment. Can anybody point me in the right direction?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
Hi @wimeling we have a sample program here that might help you: https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template
