### ISSUE TITLE
OSType is coming as  "NotSpecified"

### ISSUE THREAD

**Issue by PawarAjay8487** [Azure/azure-sdk-for-net#28503]
When we try to get ACI capabilities for particular OS, in some locations we get OSType as 'NotSpecified' which is not helping the cause of this command. could you please look into this.

here is the output of graph api for ukwest location.

GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.ContainerInstance/locations/ukwest/capabilities?api-version=2021-09-01

resourceType  : containerGroups
osType        : NotSpecified
location      : ukwest
ipAddressType : Public
gpu           : None
capabilities  : @{maxMemoryInGB=16.0; maxCpu=4.0; maxGpuCount=0}

resourceType  : containerGroups
osType        : NotSpecified
location      : ukwest
ipAddressType : Private
gpu           : None
capabilities  : @{maxMemoryInGB=16.0; maxCpu=4.0; maxGpuCount=0}

##########################################################################

Here is the output from PowerShell Command

Get-AzContainerInstanceCapability -Location 'ukwest'

Gpu  IPAddressType Location OSType       ResourceType
---  ------------- -------- ------       ------------
None Public        ukwest   NotSpecified containerGroups
None Private       ukwest   NotSpecified containerGroups

Could you please fix this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1545d8bf-3b59-bbae-6608-c208e3fe98de
* Version Independent ID: b49fc6ed-8a2a-5e81-0845-1179ff24973d
* Content: [ContainerGroup.OsType Property (Microsoft.Azure.Management.ContainerInstance.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.containerinstance.models.containergroup.ostype?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.ContainerInstance.Models/ContainerGroup.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ContainerInstance.Models/ContainerGroup.xml)
* Service: **container-instances**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by dvbb** [comment]
Hi, @PawarAjay8487 

The [NotSpecified] means you are free to choose OS type, including Linux and Windows

For example, to get eastus capabilities

``` PowerShell
> Get-AzContainerInstanceCapability -Location 'eastus'
```

|Gpu | IPAddressType| Location| OSType  |     ResourceType|
|  ----  | ----  | ----  | ----  | ----  |
| None | Public  |   eastus |  NotSpecified | containerGroups |
| None | Private |   eastus |  NotSpecified | containerGroups |
| K80  | Public  |   eastus |  Linux        | containerGroups |
| P100 | Public  |   eastus |  Linux        | containerGroups |
| V100 | Public  |   eastus |  Linux        | containerGroups |
| None | Public  |   eastus |  Linux        | containerGroups |
| None | Private |   eastus |  Linux        | containerGroups |
| None | Public  |   eastus |  Windows      | containerGroups |

The form means that the specified GPU, such as K80, is only supported for Linux.
