### ISSUE TITLE
Page needs clarification on 'only accessible via API management process'

### ISSUE THREAD

**Issue by arcesso** [Azure/azure-sdk-for-net#28516]
It is unclear what 'only accessible via API management process' means. Please clarify. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d141300-f812-2678-6dbd-3095b18ba06b
* Version Independent ID: ec62e5b2-64a8-6d99-7df2-987dc78b2707
* Content: [SitePatchResource.HostNamesDisabled Property (Azure.ResourceManager.AppService.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.resourcemanager.appservice.models.sitepatchresource.hostnamesdisabled?view=azure-dotnet-preview)
* Content Source: [xml/Azure.ResourceManager.AppService.Models/SitePatchResource.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.AppService.Models/SitePatchResource.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
