### ISSUE TITLE
[QUERY] Unable to create event subscription for system topics

### ISSUE THREAD

**Issue by jwxd** [Azure/azure-sdk-for-net#28523]
### Library name and version

Microsoft.Azure.Management.EventGrid 7.0.0

### Query/Question

Hi, I'm trying to use EventGrid sdk to create event subscription on ACR ImagePush Events programmatically using the sdk.
More specifically I'm using [EventGridManagementClient ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.eventgrid.eventgridmanagementclient?view=azure-dotnet) client to create event subscription. 
I have seem many other client class such as SecretClient has adopted Azure Identity sdk using DefaultAzureCredential for authentication.
Do you know if it's possible to do the same for EventGridManagementClient or if there's other work around instead of using  `ServiceClientCredentials` ? 
It would be nice if we can just pass Credential class directly like this
`
var client = new EventGridManagementClient(new DefaultAzureCredential()) 
`

### Environment

netcoreapp3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jwxd** [comment]
Update I'm able to get the authentication working with this piece code.
```
var credential = new DefaultAzureCredential();
var token = credential.GetToken(new TokenRequestContext(new[] { "https://management.azure.com/.default" }));
var tokenCredential = new TokenCredentials(token.Token);
var eventGridManagementClient = new EventGridManagementClient(tokenCredential);
```
However I'm running into another issue. 
```
var scope = "/subscriptions/*********/resourceGroups/********/providers/Microsoft.EventGrid/systemTopics/STG-SCAN"
EventSubscription createdEventSubscription = await eventGridMgmtClient.EventSubscriptions.CreateOrUpdateAsync(scope, eventSubscriptionName, eventSubscription);

```
I got this error `Microsoft.Rest.Azure.CloudException: This event subscription operation is not supported using this API call. Please use the proper API and try again.
`
But it works when I use try to create event subscription for a Event Grid Topics using scope like this
`/subscriptions/********/resourceGroups/********/providers/Microsoft.EventGrid/topics/Test`

Is event subscription creation not supported for system topics? Or am I doing it wrong.

**Comment by jwxd** [comment]
Nevermind, I found out that I was using the wrong subclass in the client.
[SystemTopicEventSubscription](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.eventgrid.eventgridmanagementclient.systemtopiceventsubscriptions?view=azure-dotnet#microsoft-azure-management-eventgrid-eventgridmanagementclient-systemtopiceventsubscriptions) is the correct one to use.
