### ISSUE TITLE
AutomationManagementClient parameter marshalling differs from Azure portal

### ISSUE THREAD

**Issue by sopelt** [Azure/azure-sdk-for-net#2852]
We are issuing Azure Automation **Jobs** (runbook execution requests) via **AutomationManagementClient**. There **Parameters** are provided via a `Dictionary<string, string>` as [described in the documentation](https://docs.microsoft.com/en-us/azure/automation/automation-runbook-input-parameters#assign-values-to-input-parameters-in-runbooks). We noticed, that some of our parameter strings that happened to contain numbers seem to **lose leading zeros** (e.g. `0815` results in `815`). We do not get this behavior if the runbook is interactively triggered via the Azure portal.

After some investigation we noticed that in the job run logs input section shows the input value in quotes (e.g. `"0815"`) for interactively triggered jobs and without quotes (e.g. `0815`) for requests issued through the SDK. It looks as if the client does not marshal the parameters in the same way (or at all) as the Azure portal.

A basic runbook to show this behavior:

```
param (
	[Parameter(Mandatory=$false)]
	[string] 
	$TenantIdentifier
)

Write-Output "Creating tenant '$TenantIdentifier'"
```

When triggered through the SDK via 

```
var parameters = new Dictionary<string, string>();
parameters.Add("TenantIdentifier", "0815");

var authority = "...";
var clientId = "...";
var secret = "...";
var subscriptionId = "...";
var resourceGroupName = "...";
var automationAccount = "...";
var runbook = "...";

var ctx = new AuthenticationContext(authority);
var result =
    await ctx.AcquireTokenAsync("https://management.core.windows.net/", new ClientCredential(clientId, secret));
var token = result.CreateAuthorizationHeader().Substring("Bearer ".Length);
var credentials = new TokenCloudCredentials(subscriptionId, token);
var client = new AutomationManagementClient(credentials);
var cancellationToken = new CancellationToken();
var job = await client.Jobs.CreateAsync(resourceGroupName, automationAccount, new JobCreateParameters
{
    Properties = new JobCreateProperties(new RunbookAssociationProperty
    {
        Name = runbook
    })
    {
        Parameters = parameters
    }
}, cancellationToken);
```

the resulting output is 

```
Creating tenant '815'
```

instead of the expected

```
Creating tenant '0815'
```

This looks somewhat like there is some serialization/deserialization with included type guessing going on which causes the number-like string provided by the client to be interpreted as a number. We were unable to find documentation hinting at that behavior and given that [the property Parameters of JobCreateProperties](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Automation/AutomationManagement/Generated/Models/JobCreateProperties.cs#L27) is of type `IDictionary<string, string>` it is not intuitive to have to add additional escaping on the client side.

Thank you in advance for looking into this.

**Comment by markcowl** [comment]
@safeermohammed @eamonoreilly Looks like an API modeling issue, can you take a look?

**Comment by adrianhall** [comment]
Is this still an issue?

**Comment by sopelt** [comment]
I can't say that we had a lot of pain with this due to the value ranges we are currently having in the actual project.
But yes, the issue is still present using a fresh .NET 2.2 app using `<PackageReference Include="Microsoft.Azure.Management.Automation" Version="2.0.7" />` and also `<PackageReference Include="Microsoft.Azure.Management.Automation" Version="3.8.1-preview" />`.

If the parameter is a string within a string as in `parameters.Add("TenantIdentifier", "\"0815\"");` it seems to work but as I said this doesn't seem intuitive/documented enough if expected.
I had a quick look at the documentation and the source but couldn't find any documentation/explanation for the behavior.

**Comment by adrianhall** [comment]
Thanks for the update.

**Comment by andyw248** [comment]
Closing as this doesn't appear to be a high priority issue, and according to the description can be worked around.
