### ISSUE TITLE
[QUERY] documentation of properties State and ProvisioningState in IotHubProperties

### ISSUE THREAD

**Issue by DOliana** [Azure/azure-sdk-for-net#28530]
### Library name and version

Microsoft.Azure.Management.IotHub v4.2.0

### Query/Question

I would like to understand what information is available in the properties ProvisioningState & State.

The IoT-Hub SDK allows to get an Object of the type `IotHubDescription` which contains the property `IotHubProperties`. This Property contains the string Properties State & ProvisioningState. To me it is not clear what these properties mean and how they can be used to react to certain states.

The current documentation reads as follows (with not very meaningful descriptions as "Gets the state"):
```
        //     Gets the hub state.
        [JsonProperty(PropertyName = "state")]
        public string State
        {
            get;
            private set;
        }

        //     Gets the provisioning state.
        [JsonProperty(PropertyName = "provisioningState")]
        public string ProvisioningState
        {
            get;
            private set;
        }
```

Specifically its about properties in this class: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.iothub.models.iothubproperties?view=azure-dotnet

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @DOliana , The `provisioning state` is a common state for a ARM resource, this property shows the status of a user-initiated, control-plane operation on the service, like under creation, succeed, under deletion and other status.
On other hand, the `state` shows the current status of this resource, is it turned on, or off, or others. It's usually controlled by user self.

**Comment by DOliana** [comment]
Hi @HarveyLink,
Okay, good to know but shouldn't this be reflected in the documentation of the class somewhere?
We are having sporadic issues with an IoT-Hub where we implemented a custom autoscale functionality. Sometimes it goes into an undefined state which we have to correct manually (and cannot leave for further analysis since it only occurs in production). I was hoping to get some more information from the provisioning state but do not know which values it can have.

**Comment by HarveyLink** [comment]
Add @xboxeer , @ArthurMa1978 for FYI, we need to improve our documents.

**Comment by xboxeer** [comment]
> Add @xboxeer , @ArthurMa1978  for FYI, we need to improve our documents.
These 2 properties are defined in swagger file https://github.com/Azure/azure-rest-api-specs/blob/2f2b633d940230cbbd5bcf1339a2e1c48674e4a2/specification/iothub/resource-manager/Microsoft.Devices/stable/2021-07-02/iothub.json#L2334 while we are generating the SDK and References, we do not know there values and they are pure string.
