### ISSUE TITLE
Search SDK: Highlights == null when it shouldn't.

### ISSUE THREAD

**Issue by tlangreh** [Azure/azure-sdk-for-net#2853]
I'm having an issue with the SDK where Highlights is null in in the results in some cases and I can't figure out why. The Highlight field names and pre/post tags are being specified and I'm getting a valid array of Highlights on the index with most results, but even though the content contains the text and the field containing the search term is requested via the Highlighted fields property on the search parameters object, some of the results have Highlights == null.  Can anyone shed any light on this?

I can reproduce this with the following test content on a searchable field and using the search term "pe". I'm also seeing it when I have results with the word "comment" in them and using the search term "comm".

"The persimmon tree (do they grow on trees?) is dropping persimmons in my pool - please move it to the treeline so it will drop persimmons all over my neighbor's yard (I really don't like the guy).  Thanks!"

Thanks!

**Comment by tlangreh** [comment]
So, on the "comm" search it actually seems to be when the content has the word "communication" in it, not "comment".  Another example of content causing this issue: 

"Southside Electrical is going to meet Cory at the farm Tuesday, December 13 at 9:00. Corey and I have been in communication about this. "

**Comment by brjohnstmsft** [comment]
@tlangreh Can you provide some code showing how you're setting up your Search request?

**Comment by tlangreh** [comment]
Hi Bruce,

Here is a code sample that I hope will be useful for reproducing the problem. Our code is actually quite different because we are using inheritance for several aspects of this, but in the end, this is basically what it comes down to. I also want to mention that we weren't seeing this issue when we were on the free version, but only since we moved to the S1 level and uploaded nearly 7 million documents. Not sure if that is just because we didn't have as much varied content to search before or.....

Thanks for taking a look :)

`
public DocumentSearchResult<IndexDocument> performQuery()
{
 DocumentSearchResult<IndexDocument> queryResults;
 SearchParameters parameters;
 string formattedQueryText;

 // setup parameters
parameters = new SearchParameters();
 parameters.HighlightFields = new string[] { "Content" };
 parameters.HighlightPreTag = "<span class='searchHighlightMatchClass'>";
 parameters.HighlightPostTag = "</span>";
 parameters.Select = GetSearchFields();
 parameters.Top = 9;
 parameters.Filter = "SearchLevelType eq 1 and SearchLevelId eq 12345";
 
formattedQueryText = "comm*";
 
 // run query
queryResults = indexClient.Documents.Search<IndexDocument>(formattedQueryText,																								parameters);

 return queryResults;										
}					
										
protected virtual string[] GetSearchFields()
{
  List<string> fieldList = null;
  PropertyInfo[] propertiesArray = null;

  fieldList = new List<string>();
  propertiesArray = typeof(IndexDocument).GetProperties();

  foreach (PropertyInfo propertyInfoData in propertiesArray)
  {
	fieldList.Add(propertyInfoData.Name);
  }

  return fieldList.ToArray();
}
`

**Comment by brjohnstmsft** [comment]
@tlangreh Thanks for the code. I shared this with Nate and based on the parameters in the request, we agree this is an instance of the highlighting issue that he described in [this MSDN thread](https://social.msdn.microsoft.com/Forums/azure/en-US/f56c5a84-369c-4c2c-ad6f-81698c55cca8/highlights-null-in-search-results?forum=azuresearch). Since that issue is in the REST API and not our .NET SDK, I'm going to close this issue.

Nate suggested a workaround on the MSDN thread; Hopefully that works for you. Please leave any follow up questions or comments there.
