### ISSUE TITLE
[FEATURE REQ] DocumentTranslationInput does not allow to specify categoryId in DocumentTranslationInput constructor

### ISSUE THREAD

**Issue by sabbadino** [Azure/azure-sdk-for-net#28531]
### Library name

Azure.AI.Translation.Document

### Please describe the feature.

DocumentTranslationInput does not allow to specify categoryId in DocumentTranslationInput constructor

**Comment by maririos** [comment]
Thanks @sabbadino for reporting this. We will include it in our next release

**Comment by maririos** [comment]
Hi @sabbadino, a way to currently add `CategoryId` is to do:
```
           var source = new TranslationSource(new Uri("http://localhost"));
            var target = new TranslationTarget(new Uri("http://localhost"), "en")
            {
                CategoryId = "myCategoryId"
            };
            var input = new DocumentTranslationInput(source, new List<TranslationTarget>() { target });
```

I'm also working on adding it to the `AddTarget()` method under the `DocumentTranslationInput` class so it is easily discoverable. 
Let me know what you think

**Comment by sabbadino** [comment]
Thanks, i had missed that possibility.

**Comment by maririos** [comment]
We've also added it to the `DocumentTranslationInput.AddTarget` method. You will see it in our next release.
Thank you for your feedback!
