### ISSUE TITLE
DPG reference docstrings are formatted badly

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#28536]
See: https://docs.microsoft.com/en-us/dotnet/api/azure.security.confidentialledger.confidentialledgerclient.createorupdateuser?view=azure-dotnet-preview#remarks

The [\<code\> tag](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#d33-code) is not rendered as code.

**Comment by sima-zhu** [comment]
Could you please point out which part has been removed? 
I am checking [github io](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Security.ConfidentialLedger/1.0.0-beta.2/api/Azure.Security.ConfidentialLedger/Azure.Security.ConfidentialLedger.ConfidentialLedgerClient.html) which seems the same as docs.ms

**Comment by annelo-msft** [comment]
Link to PR that introduced these docstrings: https://github.com/Azure/autorest.csharp/pull/1495
@fengzhou-msft, did you validate the output?  If so, this could be a regression.

**Comment by fengzhou-msft** [comment]
@annelo-msft the doc is for `Azure.Security.ConfidentialLedger v1.0.0-beta.2`, which was published before my doc format changes. I confirmed with Matt that we decided not to refresh the docs for a package until we publish the next version of the package. Here is an example of the new doc format: https://docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdate?view=azure-dotnet-preview#remarks

**Comment by annelo-msft** [comment]
@christothes, per @fengzhou-msft's comments, could you help us find the latest docs for Confidential Ledger?  Or help us understand the plan to get a more recently generated version of the docs?

**Comment by christothes** [comment]
As I understand @fengzhou-msft 's comments, we'll need to publish a new release to fix this.

**Comment by pshao25** [comment]
@annelo-msft if that is the case, do we need to release a new package for confidential ledger. As what I understand, this issue should not only target to confidential ledger, but all the SDKs which happen to release when the tool was broken. Now the tool seems already fixed now. Is it OK to release a new version of confidential ledger when there is no change?

**Comment by fengzhou-msft** [comment]
Based on the [release pipeline yaml](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/pipelines/templates/stages/archetype-net-release.yml), we should be able to skip the publish step (skipPublishPackage=true) and just update the doc with a previous release tag of code base. But considering that the main branch has at least code changes caused by generator updates, I would suggest to release a new version of package.

**Comment by lirenhe** [comment]
> The task `PublicDocsMS` depends on `PublishPackage`, therefore we have to publish a new package to update the MS doc.

let me check with docs team.

**Comment by annelo-msft** [comment]
I recommend coordinating with @christothes on this -- @christothes, given all the swagger updates, was the Confidential Ledger team planning to ship another preview before GA?  I think it would be good to have updated docs the architects can review at the Confidential Ledger GA-approval arch board.

@lirenhe, we may be making changes to docs generation as part of the DPG GA work -- if there's a way to update the docs independently from shipping a package, that would be ideal, as we might want to update them more than once.

**Comment by sima-zhu** [comment]
If we just want to check the format before GA, we can check over daily review docs.
https://review.docs.microsoft.com/en-us/dotnet/api/azure.security.confidentialledger.confidentialledgerclient.createorupdateuser?branch=daily%2F2022-05-18-ci-succeeded&view=azure-dotnet-preview#remarks

Is this what you expect to see?

**Comment by pshao25** [comment]
@annelo-msft My understanding is: after the new package releases, we need to validate the updated doc. After that, we could close.

**Comment by annelo-msft** [comment]
Ok, thanks @pshao25.  If that is the criteria for closing the issue, then this issue blocks Confidential Ledger GA, but not DPG GA, because we are confident that we will solve this as part of solving https://github.com/Azure/autorest.csharp/issues/2239, and that it may be solved already but we don't yet have validation of that (unless you tell me otherwise.)

**Comment by pshao25** [comment]
@annelo-msft Correct.

Close by cut (as we have new format in https://github.com/Azure/autorest.csharp/issues/2239).
