### ISSUE TITLE
Incorrect constructor and properties

### ISSUE THREAD

**Issue by arrowhead900** [Azure/azure-sdk-for-net#28537]
The actual class in the SDK looks like this:

public class RunCommandInput : IUtf8JsonSerializable
{
    public RunCommandInput(string commandId);
    public string CommandId { get; }
    public IList<string> Script { get; }
    public IList<RunCommandInputParameter> Parameters { get; }
}

Parameters are get only, and constructor only accepts CommandId string as input. I assume this was a mistake in the SDK, if not it is unclear how this class will ever get instantiated properly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 401548e7-0b9a-a328-b84d-c1ca74501ebd
* Version Independent ID: 888b1e46-bf00-5f0b-c396-03906ce0d336
* Content: [RunCommandInput Constructor (Microsoft.Azure.Management.Compute.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.runcommandinput.-ctor?view=azure-dotnet-preview#microsoft-azure-management-compute-models-runcommandinput-ctor(system-string-system-collections-generic-ilist((system-string))-system-collections-generic-ilist((microsoft-azure-management-compute-models-runcommandinputparameter))))
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/RunCommandInput.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/RunCommandInput.xml)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
