### ISSUE TITLE
The description of the methods cut off from the page

### ISSUE THREAD

**Issue by Dimeji98** [Azure/azure-sdk-for-net#28552]
The description of the methods cut off from the page

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e480de06-b14a-5c82-73dc-65dbc3ecd03f
* Version Independent ID: c0e88ab1-ef73-3f0b-3a35-ee5d201b1486
* Content: [BlockBlobClient Class (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blockblobclient?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlockBlobClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlockBlobClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This is being tracked in the MS Docs repository as [#89783](https://github.com/MicrosoftDocs/azure-docs/issues/89783).   I've linked this issue there to unify tracking and am going to close this out.
