### ISSUE TITLE
More information needed

### ISSUE THREAD

**Issue by neilrudd** [Azure/azure-sdk-for-net#28551]
Hi

Would it be possible to add more information regards to the different PatchOperations similar to https://github.com/AzureCosmosDB/PatchPrivatePreviewFeedbackGroup/issues/2

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4297f7a5-e3a7-5d4d-879a-a359fc93a5ac
* Version Independent ID: 7985d3d9-1cf5-f3ab-495e-ea6acfce4170
* Content: [PatchOperation Class (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.patchoperation?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/PatchOperation.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/PatchOperation.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@neilrudd Thank you for reaching out, we are looking into it.
