### ISSUE TITLE
[BUG] ManagedIdentityCredential authentication failed: Status: 410 (Gone)

### ISSUE THREAD

**Issue by zhiweiv** [Azure/azure-sdk-for-net#28568]
### Library name and version

Azure.Identity 1.6.0

### Describe the bug

Sometimes managed identity authentication failed due to 410 error from IMDS.

### Expected behavior

Per https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=linux#frequently-asked-questions

> Why am I getting the error 500 Internal Server Error or 410 Resource Gone?
> 
> Retry your request. For more information, see [Transient fault handling](https://docs.microsoft.com/en-us/azure/architecture/best-practices/transient-faults). If the problem persists, create a support issue in the Azure portal for the VM.

410 is a retriable error, Azure.Identity should retry for better stability. I guess it is probably here:
https://github.com/Azure/azure-sdk-for-net/blob/068b3debe69ef448c43e7e3f50da28ceeae4e0b4/sdk/identity/Azure.Identity/src/ManagedIdentitySource.cs#L151-L162
### Environment

.net 6.0 console app in AKS Linux container

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by SKUD201** [comment]
Hello,

We had the exact same issue in the same environment. Being on version 1.5.0, it triggerred an exception similar to https://github.com/Azure/azure-sdk-for-net/issues/24158.

We will update to 1.6.0 in the meantime.
Thanks.

**Comment by semornas** [comment]
> Hello,
> 
> We had the exact same issue in the same environment. Being on version 1.5.0, it triggerred an exception similar to #24158.
> 
> We will update to 1.6.0 in the meantime. Thanks.

Hi there,
Any news regarding this issue? We have a bug in our backlog that is blocked because of this :(
Any help would be appreciated!

**Comment by devlie** [comment]
@christothes is there any plan to fix this?

IMDS can return HTTP 410 by design and their documentation requires caller to retry up to 70 secs, but ManagedIdentityCredential does not retry even once. Worse, because we don't retrieve the token ourselves (Storage/Cosmos clients do that automatically), we can't really retry the error ourselves without polluting our business layer which has no business of knowing which auth is used.

**Comment by christothes** [comment]
Just out of curiosity - how often are you seeing failures due to this error code (410)? I would think that it's rare.

**Comment by devlie** [comment]
> Just out of curiosity - how often are you seeing failures due to this error code (410)? I would think that it's rare.

@christothes, not super high rate, but enough to cause us troubles. It caused our services to have four sev3 incidents in the past 2 weeks alone.

**Comment by christothes** [comment]
> > Just out of curiosity - how often are you seeing failures due to this error code (410)? I would think that it's rare.
> 
> @christothes, not super high rate, but enough to cause us troubles. It caused our services to have four sev3 incidents in the past 2 weeks alone.

That's way more frequently than I would have guessed! We can add status 410 to the rety statuses, however we wouldn't want to extend the default retry timeout to accommodate the 70 second delay. The main reason being that in a local development scenario, we need the endpoint failure to fail fast. 

There is a workaround, however. You could supply a custom retry policy to the credentialOptions and customize the behavior for your specific scenario. See [these docs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#setting-a-custom-retry-policy) for details

**Comment by tjrobinson** [comment]
@christothes Thanks for getting this change in. Do you know if there's a target date/release for this yet?

**Comment by christothes** [comment]
It should be released on the next monthly release, which is early next month.
