### ISSUE TITLE
[Core] Investigate implications of adding explicit net6.0 targets for all clients

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#28577]
### API Change Needed

No

### Background and motivation

Related to #28492 

If an explicit net6.0 target for all clients were added, how would this affect usage of newer framework features and existing `#if NET6_0_OR_GREATER` blocks.

### API / Feature Proposal

n/a

### Time Constraints and Dependencies

n/a

**Comment by AraHaan** [comment]
I will check into this myself as well by checking out the codebase and experimenting with it locally.

**Comment by christothes** [comment]
> I will check into this myself as well by checking out the codebase and experimenting with it locally.

Here is where to start if you are interested in experimenting with this change: 

https://github.com/Azure/azure-sdk-for-net/blob/1abed9d3f215982af84ec671fdbf0a2541a12762/eng/Directory.Build.Common.props#L119

**Comment by AraHaan** [comment]
It seems that with the changes above that these would have to be changed as well (where ever the code to System.Memory.Data is located at):
![image](https://user-images.githubusercontent.com/15173749/168142381-809d087f-6e65-4cc0-a726-4dd9bbed1f02.png)

After those 2 are removed from System.Memory.Data and the other packages from the first issue that I highlighted for Azure.Identity it should then be simpler.

In the mean time I am about to continue my experiment. Sadly it seems there is no root level solution file that I can open all projects in mass with Visual Studio to view them all at once (that excludes the tests from it).

**Comment by AraHaan** [comment]
A lot of errors is from CancelationToken based things not being passed to certain async apis that are being used by the Azure SDK.

Before .NET 6 can be added those issues need fixed.

**Comment by AraHaan** [comment]
Anyone here able to grab the CancellationToken related compile errors?

**Comment by AraHaan** [comment]
I have opened an draft pr because it will require more changes inside of other azure repos first.

**Comment by annelo-msft** [comment]
Adding a note to include https://github.com/Azure/azure-sdk-for-net/issues/30685#issuecomment-1225947517 in the considerations when this investigation takes place.
