### ISSUE TITLE
[BUG] : SQL connection pool issue when using the MSI token for SQL generated with Azure.Identity

### ISSUE THREAD

**Issue by RanjanMishra92** [Azure/azure-sdk-for-net#28572]
### Library name and version

Azure.Identity 1.5.0

### Describe the bug

We migrated our solution from ADAL to MSAL , and in our code we were using Microsoft.Azure.Services.AppAuthentication which was used to get the MSI token and that token was used by SQL (entity framework core) to authenticate. As this Microsoft.Azure.Services.AppAuthentication package has a dependency on ADAL we have replaced it with Azure.Identity 1.5.0.
So when we use the MSI token generated for SQL with Azure.Identity , SQL connection pooling seems to be broken , as we started getting below error related to the SQL connection pool.
Error : 
Resource ID : 2. The session limit for the elastic pool is 30000 and has been reached. See '[http://go.microsoft.com/fwlink/?LinkId=267637'](http://go.microsoft.com/fwlink/?LinkId=267637%27) for assistance.
Changed database context to ''.
Changed language setting to us_english.

when we keep all settings same and switch back to old code which was using MSI tokens generated from : Microsoft.Azure.Services.AppAuthentication we do not see this error on same load test execution.

### Expected behavior

The expected behavior is that it should not break the SQL connection pooling with MSI token generated with Azure.Identity.

### Actual behavior

We are getting SQL connection pooling error with MSI token generated with Azure.Identity, 

**Error :** 
Resource ID : 2. The session limit for the elastic pool is 30000 and has been reached. See '[http://go.microsoft.com/fwlink/?LinkId=267637'](http://go.microsoft.com/fwlink/?LinkId=267637%27) for assistance.
Changed database context to ''.
Changed language setting to us_english.

### Reproduction Steps

1) Generate the MSI token for SQL resource 
var tokenCredential = new Azure.Identity.DefaultAzureCredential();
var managedIdentityTokenForSql = tokenCredential.GetToken(
                                    new Azure.Core.TokenRequestContext(
                                    new[] { "https://database.windows.net/.default" }, tenantId: "your_tenantId")).Token;

2) Now use this token and pass to the entity framework core :
               var connection = Database.GetDbConnection() as SqlConnection;
                if (connection != null)
                {
                    connection.AccessToken = managedIdentityTokenForSql;
                }

3) perform load test on this where more number of transactions are executed against SQL DB.

### Environment

1) The Server API Layer which interacts with DB through Entity framework code is deployed to Azure Web App service.
2) Managed identity is enabled on the that Azure App service.
3) The web app is built using .NET core 3.1 version. 
4) EF core Version=3.1.7.0 .

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by ShivangiReja** [comment]
If you want to use `DefaultAzureCredential`, you can pass `Authentication=Active Directory Default` in your connection string. You can refer the docs [here](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15#using-active-directory-default-authentication) to see how to pass it.

**Comment by ShivangiReja** [comment]
@RanjanMishra92 Looking at release notes [Active Directory Default authentication support](https://docs.microsoft.com/en-us/sql/connect/ado-net/introduction-microsoft-data-sqlclient-namespace?view=sql-server-ver16#active-directory-default-authentication-support) is added in [Microsoft.Data.SqlClient 3.0](https://docs.microsoft.com/en-us/sql/connect/ado-net/introduction-microsoft-data-sqlclient-namespace?view=sql-server-ver16#release-notes-for-microsoftdatasqlclient-30)

**Comment by ShivangiReja** [comment]
@RanjanMishra92 Looking at release notes [Active Directory Default authentication support](https://docs.microsoft.com/en-us/sql/connect/ado-net/introduction-microsoft-data-sqlclient-namespace?view=sql-server-ver16#active-directory-default-authentication-support) is added in [Microsoft.Data.SqlClient 3.0](https://docs.microsoft.com/en-us/sql/connect/ado-net/introduction-microsoft-data-sqlclient-namespace?view=sql-server-ver16#release-notes-for-microsoftdatasqlclient-30) 

CC: @cheenamalhotra, @johnnypham

**Comment by cheenamalhotra** [comment]
@DavoudEshtehari 
cc @David-Engel

**Comment by cheenamalhotra** [comment]
Adding context, [EntityFrameworkCore.SqlServer v3.1.7](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/3.1.7) depends on Microsoft.Data.SqlClient v1.1.3.
This issue regarding connection pooling with access token was fixed in v2.x of SqlClient (ref: https://github.com/dotnet/SqlClient/pull/443)

**Comment by David-Engel** [comment]
To explain a little bit how connection pooling works in SqlClient with regard to access tokens, each different access token will have a different pool in SqlClient. So if you are stress testing and generating a new access token for 30,000 connections, you will get 30,000 connections against the database and 30,000 _different_ connection pools.

From your repro steps, I can't tell if you are performing steps 1 and 2 for each connection, or if you are using the same access token (just step 2) for all connections. Based on the results, it sounds like you are doing the former. The latter would result in a connection pool with only the number of physical database connections up to [MaxPoolSize](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.maxpoolsize?view=sqlclient-dotnet-standard-4.1).

Either way, upgrading to a newer version of Microsoft.Data.SqlClient that supports Authentication = "Active Directory Managed Identity" or "Active Directory Default" will work much better as SqlClient will handle token acquisition and renewal for you (you won't need step 1 at all). You will just need the Authentication option in your connection string.
