### ISSUE TITLE
[QUERY] Inconveniences of mocking methods to get parent clients

### ISSUE THREAD

**Issue by Archomeda** [Azure/azure-sdk-for-net#28575]
### Library name and version

Azure.Storage.Blobs 12.11.0

### Query/Question

I'm questioning why the issue described in #22679 has such an inconvenient solution.

I'm using NSubstitute instead of Moq, which to my knowledge doesn't provide a way to mock methods by name. This limits my ability to mock this method.
And at the same time, why does the extension method GetParentBlobContainerClient (among others) exist when they are just single-line wrappers around their Core equivalents?
https://github.com/Azure/azure-sdk-for-net/blob/fdd82bfc752d856ac868e251350a2f0b8737df85/sdk/storage/Azure.Storage.Blobs/src/BlobBaseClient.cs#L6490-L6501

Instead, why aren't the Core methods public and virtual so that mocking them is easy, like most other methods under the blob classes?

**Comment by PramodValavala-MSFT** [comment]
@Archomeda Thanks for the feedback! We will review and update accordingly.
