### ISSUE TITLE
[Search] AutoFlushInterval_FullBatchTest failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#28570]
Search nightly test runs are failing with:

> Error message
> Expected: 256
> But was:  255
> 
> 
> Stack trace
>    at Azure.Search.Documents.Tests.BatchingTests.AutoFlushInterval_FullBatch() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 618
>    at Azure.Search.Documents.Tests.BatchingTests.AutoFlushInterval_FullBatch() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 621
>    at Azure.Search.Documents.Tests.BatchingTests.AutoFlushInterval_FullBatch() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 621
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1547903&view=results

@jsquire for notification.

**Comment by ShivangiReja** [comment]
Nightly tests are running without any errors in the past 2-3 weeks, so closing this issue.

For more details see here: https://dev.azure.com/azure-sdk/internal/_build?definitionId=1594&_a=summary

Please create a new issue, if the tests are started to fail again.
