### ISSUE TITLE
[QUERY] Prewarm link to ServiceBus 

### ISSUE THREAD

**Issue by bbieniek** [Azure/azure-sdk-for-net#28576]
### Library name and version

Azure.Messaging.ServiceBus 7.7.0

### Query/Question

Hi,

I noticed that when the first message is sent to the Service Bus queue, it takes significant (~3-5s) time to send the message.
The next messages are sent pretty fast.
I am using managed identity to connect to the service bus.
I am guessing that when the message is first sent, you establish a link to the Service Bus and obtaining the identity token takes a major portion of the time.
The question is:
Is there a way to prewarm the link so that the first message is sent quickly?

This was also mentioned in:
https://github.com/Azure/azure-sdk-for-net/issues/13010

### Environment

Azure Function with latest SDK (4.3.*)

**Comment by jsquire** [comment]
Hi @bbieniek.  Thank you for reaching out and we regret that you're experiencing difficulties.   Your observation is correct; the first service operation that is requested establishes the connection, which is then used by subsequent operations.   Calling for any service operation on the client prior to sending messages would warm that up; in the case of the sender, [SendBatchAsync](https://docs.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebussender.createmessagebatchasync?view=azure-dotnet#azure-messaging-servicebus-servicebussender-createmessagebatchasync(system-threading-cancellationtoken)) would do so without sending any data.

It is important to note that there is an idle timeout at ~20 minutes, after which the client will need to reconnect.   The client also needs to reconnect after any network events that interrupt the connection.   Those reconnects also happen only when a service operation is requested.
