### ISSUE TITLE
Update developer-driven evolution doc with LRO grow-up guidance

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#28583]
We closed https://github.com/azure/autorest.csharp/issues/1945#issuecomment-1063241796 for developer-driven evolution without adding guidance for growing up LROs.  This issue tracks the work to add that guidance.

Include note that: We will not add convenience API method if no modifications are needed to the method signature.

**Comment by pshao25** [comment]
@annelo-msft 

> Include note that: We will not add convenience API method if no modifications are needed to the method signature.

This one looks not only applies to LRO. I think it should apply to all the methods whose signature don't need change.

**Comment by annelo-msft** [comment]
> This one looks not only applies to LRO. I think it should apply to all the methods whose signature don't need change.

Yes, this is correct.  I haven't seen any other examples where the signature doesn't need to change at all ... can you think of one?

**Comment by annelo-msft** [comment]
Per @lmazuel and @KrzysztofCwalina, GA requirement is for partner docs is only "how to create the MVP". That makes this issue something we can bring in after v1.0.

**Comment by pallavit** [comment]
@pshao25 is this still a valid concern?
