### ISSUE TITLE
Improve docs for distributed tracing

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#28588]
- when and how are event source logs funneled to Application insights?
- how to use the various internal types to create scopes
- what validation is there from Test Framework
- talk about ActivitySource vs DiagnosticActivity

**Comment by JoshLove-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-net/issues/8744

**Comment by annelo-msft** [comment]
Related: https://github.com/Azure/azure-sdk-for-net/issues/27828

**Comment by adamsitnik** [comment]
I would like to use the provided `ActivitySource` in a non-preview component library. It has been marked "experimental" in the docs for almost two years now:

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#activitysource-support

Are there any plans to get it out of the experimental mode?

cc @lmolkova @eerhardt

**Comment by lmolkova** [comment]
> I would like to use the provided `ActivitySource` in a non-preview component library. It has been marked "experimental" in the docs for almost two years now:
> 
> https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#activitysource-support
> 
> Are there any plans to get it out of the experimental mode?
> 
> cc @lmolkova @eerhardt

We're waiting for [OTel HTTP semconv](https://github.com/open-telemetry/semantic-conventions/blob/098db1ca510da01fe941f6c6308aad5000def910/docs/http/http-spans.md) to stabilize (and actively helping them stabilize). The expectation is that they go stable within a few months and then we'll adopt the stable version and remove the switch ASAP.  OTel currently does NOT recommend stabilizing anything until Oct 1st 2023.
