### ISSUE TITLE
[QUESTION] Why does TextAnalytics SDK not return same results as Language Studio?

### ISSUE THREAD

**Issue by Ansiem** [Azure/azure-sdk-for-net#28598]
### Library name and version

Azure.AI.TextAnalytics 5.1.1

### Query/Question

Hi there,

I am currently writing an Azure function in C# which uses the TextAnalytics SDK to detect IBAN values. 
To detect these values I am using the following code:

```csharp

 var client = new TextAnalyticsClient(new Uri(endpoint), new AzureKeyCredential(apiKey));

            var options = new RecognizePiiEntitiesOptions();
            options.CategoriesFilter.Add(PiiEntityCategory.InternationalBankingAccountNumber);

            var piiResponse = await client.RecognizePiiEntitiesAsync(myQueueItem, "en");

            PiiEntityCollection piiEntities = piiResponse.Value;

```

myQueueItem is a string that contains multiple sample IBANs. This is the following string:

NL24 ABNA 4047 6339 76 NL61 INGB 0003 3505 63 NL18RABO0123459876 NL98INGB0003856625 
NL98ABNA0416961347 NL98UGBI0771565860 NL98TRIO0254712320 NL98SNSB0908532792 
NL97DEUT0265134951 NL97BNPA0227673409 NL97BNGH0285061917 NL97BOFA0266546412

The problem is that not all the IBANs are detected, however when I am testing this same string with Language Studio all the IBANs do get detected.

C# SDK Results:

![C_Sharp_Results](https://user-images.githubusercontent.com/19479222/167313609-64faab8b-11a9-4f4b-9281-d9621d362b00.PNG)

Language Studio Results:

![Language_Studio_Results](https://user-images.githubusercontent.com/19479222/167313611-550acb89-e7d7-473a-91ca-47299e570795.PNG)

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

IDE Version: 17.1.6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by maririos** [comment]
Hi @Ansiem , do you happen to know which is the version of the Language studio instance you are using?

**Comment by Ansiem** [comment]
Hi @maririos, where can I find the version of the Language studio instance?

**Comment by maririos** [comment]
At the top of the page, underneath the name of the functionality you are using. For example: 

<img width="428" alt="image" src="https://user-images.githubusercontent.com/9868623/167461546-548a28f7-8ddb-4d0b-8b85-2f3cdc0857ce.png">

**Comment by Ansiem** [comment]
@maririos I am using Version 3.1.

**Comment by Ansiem** [comment]
Thanks for the help! The problem was indeed the way the content of myQueueItem was handled. I passed the entire myQueueItem instead of the property that I'd wanted to be analyzed.

**Comment by maririos** [comment]
I'm glad it all worked out. Let us know if you have feedback or find any other issues
