### ISSUE TITLE
[QUERY] Service Bus messaging sessions billable operations

### ISSUE THREAD

**Issue by apivkine** [Azure/azure-sdk-for-net#28603]
### Library name and version

Azure.Messaging.ServiceBus 7.7.0

### Query/Question

Hello!

It is unclear from the available documentation whether Service Bus message sessions incur any billable operations when performing **Session Accept** and **Session Lock Renew** operations. The documentation does state that **Message Lock Renew** operations do incur billable operations, however nothing is said in regards to sessions. It is also stated specifically that Session State operations are counted as well, but nothing about other session operations.

What is the best practice to wait for a message on a specific Messaging Session? Currently, the following seems to be the pattern:

1. Accept Session with a specific Session Id (does not wait). This is not the "[Get Next Session Operation](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusclient.acceptnextsessionasync?view=azure-dotnet)", but rather "[Get Session with a Specific Id](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusclient.acceptsessionasync?view=azure-dotnet)".
2. Receive Message (wait for specified period of time less than session lock duration)
3. Renew the lock to keep the session active and go to step 2 **OR** close the session and go to to step 1.

However, if Session Accept or Renew Session Lock incur a billable operation, these can add up pretty quickly.

Also, if this pattern is correct, is there a limit to how many sessions can be active with receive operations waiting for messages at the same time?

Thank you! 

### Environment

.NET 6, Linux (mcr.microsoft.com/dotnet/aspnet:6.0 docker container)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by EldertGrootenboer** [comment]
1. Session Accept and Session Lock Renew operations use credits, however these are not billed.
2. 5000 sessions can be active per queue or topic (across all subscriptions).
