### ISSUE TITLE
Batch: Unclear what happens when a job does not exist

### ISSUE THREAD

**Issue by marcelvb** [Azure/azure-sdk-for-net#28600]
Please specify what will be returned if a job with the given job id does not exist. Will it return `null` or an exception?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6d288cdf-ad13-52bc-195c-1f103324b78c
* Version Independent ID: 1524bf6d-f7fa-f8d8-69c9-5e754583f402
* Content: [JobOperations.GetJobAsync(String, DetailLevel, IEnumerable&lt;BatchClientBehavior&gt;, CancellationToken) Method (Microsoft.Azure.Batch) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.joboperations.getjobasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Batch/JobOperations.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Batch/JobOperations.xml)
* Service: **batch**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@marcelvb Thank you for reaching out, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@marcelvb You will get "BatchErrorException: Operation returned an invalid status code 'NotFound'" exception.

**Comment by marcelvb** [comment]
Thanks for the information. I was expecting the information to be added in the docs at https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.joboperations.getjobasync?view=azure-dotnet.
