### ISSUE TITLE
[QUERY] Documentation Request for Send and Receive a ServiceBusMessage for a POCO

### ISSUE THREAD

**Issue by granadacoder** [Azure/azure-sdk-for-net#28606]
### Library name and version

Azure.Messaging.ServiceBus Version="7.7.0"

### Query/Question

Would you please add an example in the documentation that is a simple POCO (and not only a string).
If everything has to be json'fied as a string please explicitly say so.

Existing example:

```
string connectionString = "<connection_string>";
string queueName = "<queue_name>";
// since ServiceBusClient implements IAsyncDisposable we create it with "await using"
await using var client = new ServiceBusClient(connectionString);

// create the sender
ServiceBusSender sender = client.CreateSender(queueName);

// create a message that we can send. UTF-8 encoding is used when providing a string.
ServiceBusMessage message = new ServiceBusMessage("Hello world!");

// send the message
await sender.SendMessageAsync(message);

```

Add a basic POCO

```
public class MyPoco
{
  public string MyFirstString {get;set;} = "Howdy";
  public boolean MyFirstBoolean {get;set;} = true;
  public int MyFirstInt {get;set;} = 333;
  public DateTimeOffset MyFirstDateTimeOffset {get;set;} = DateTimeOffset.Now;

}
```

and the "Send"

```
MyPoco mp = new MyPoco();

ServiceBusMessage message = new ServiceBusMessage(mp);
```

???

And reciprocate the "Receive" example

```
// Or receive using the receiver
var receiver = new MessageReceiver(connectionString, queueName);
var receivedMessage = await receiver.ReceiveAsync();
MyPoco receivedMyPoco = receivedMessage.Body (???) ; 
await receiver.CompleteAsync(receivedMessage);

```

If the only option is to json'fy everything to a string, please explicitly say so.

The "old" libraries had generic's support for POCO's.

  Old library reference : https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.brokeredmessage.getbody?view=azure-dotnet#microsoft-servicebus-messaging-brokeredmessage-getbody-1

`public T GetBody<T> ();`

and the constructor accepting a "T".

https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.brokeredmessage.-ctor?view=azure-dotnet#microsoft-servicebus-messaging-brokeredmessage-ctor(system-object)

Thank you.

### Environment

DotNet-Core on Mac-Catalina.

**Comment by granadacoder** [comment]
Any advice (as a comment on this issue) on this "how do do POCO" question ...  in the short term?

**Comment by JoshLove-msft** [comment]
Sure, take a look at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Message/MessageLiveTests.cs#L267-L280.
This shows how to serialize and deserialize a POCO to JSON.

**Comment by granadacoder** [comment]
Thanks.
