### ISSUE TITLE
[QUERY] - Azure.ResourceManager - could we have an example of making an Arm Deployment with the new Track II SDK?

### ISSUE THREAD

**Issue by stowen-msft** [Azure/azure-sdk-for-net#28607]
### Library name and version

Azure.ResourceManager

### Query/Question

Hi!

 I am trying to migrate from Microsoft.Azure.ResourceManager to the new Azure.ResourceManager package, as I want to migrate away from ADAL and to MSAL for organizational requirements.  I am trying to understand how to perform these operations with the new Azure.ResourceManager SDK.

```csharp
//whatIf at ResourceGroup scope
var whatIfResponse = await client.Deployments.WhatIfAsync(resourceGroupName, deploymentName, deploymentWhatIf);

//whatIf at subscription Scope
var whatIfResponse = await client.Deployments.WhatIfAtSubscriptionScopeAsync(deploymentName, deploymentWhatIf);

//deployment at scope 
var deploymentResponse = await client.Deployments.CreateOrUpdateAtScopeAsync(spec.Scope, spec.Name, deployment);
````

I have looked through the source code on the repo and do not understand the structure used.

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.104

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.1.6

**Comment by ArthurMa1978** [comment]
@stowen-msft here your https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template

**Comment by stowen-msft** [comment]
Thank you, Arthur :)

**Comment by david-jarman** [comment]
@ArthurMa1978, thanks for the link, however the code sample does not address the original question which is how to perform a "what-if" before a deployment is actually created. The linked example creates an incremental resource group deployment, and actually creates the resource.

Could you re-open this issue and provide a code example for what-if deployments?
