### ISSUE TITLE
Correct LRO Implementation for PostLedgerEntry

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#28614]
[ConfidentialLedgerClient.PostLedgerEntry](https://apiview.dev/Assemblies/Review/7e9dd9920e324259b8a3653c313b0c7f#Azure.Security.ConfidentialLedger.ConfidentialLedgerClient) does not meet the following LRO requirements:

- [ ] ~~PostLedgerEntry returning `Response` should return `Operation` - should mark operation as with `x-ms-long-running-operation` in OpenAPI spec~~
- [ ] ~~PostLedgerEntry returning `PostLedgerEntryOperation` should not both take a `RequestContext` and return a manually-written subclass of `Operation`.~~
- [ ] Verify distributed tracing output is correct (write tests) per https://github.com/Azure/autorest.csharp/issues/2136

**Comment by christothes** [comment]
This is not an actual LRO, but a convenience "pseudo LRO", so the swagger is correct.

Will discuss with the .NET architect to ensure we are doing the right thing here.

**Comment by christothes** [comment]
Looked into this a bit and I believe we are conforming to the Short-LRO pattern here https://github.com/Azure/azure-sdk/issues/3263

**Comment by annelo-msft** [comment]
In the 05/13 DPG C# design discussion, architects decided:
-	Use [C# code generator customizations](https://github.com/Azure/autorest.csharp#customizing-the-generated-code) to generate the protocol `PostLedgerEntry` method returning Response as internal.
-	Manually add a protocol `PostLedgerEntry` method that returns `Operation`
-	Manually add a convenience `PostLedgerEntry` method that returns `PostLedgerEntryOperation` subtype of `Operation`, that takes WaitUntil as the first parameter and CancellationToken as the last.
-	Retain the protocol `GetTransactionStatus` method, since there is a use case for it.
