### ISSUE TITLE
Add missing LoggedQueryParameters

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#28610]
With the addition of the Language API, we want to make sure we are logging all the parameters that the service now expects.
From the list, I see that some that are missing are:
- api-version
- top
- skip

This s needs to happen in the [ClientOptionsExtensions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/src/ClientOptionsExtensions.cs#L20) class.

**Comment by JoshLove-msft** [comment]
FYI `api-version` is logged by default - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/DiagnosticsOptions.cs#L72, so there is no need to add that one.

**Comment by maririos** [comment]
@JoshLove-msft cool!! thank you for the pointer!!
