### ISSUE TITLE
ConfigureFunctionWorkerDefaults not found in Microsoft.Extensions.Hosting 5.0

### ISSUE THREAD

**Issue by megangerfen2** [Azure/azure-sdk-for-net#28618]
Trying to upgrade durable functions from .net core 3.1 to  net 6  and 
have added reference to package  Microsoft.Azure.WebJobs.Extensions.Storage

but this function is not available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ef3e2a02-640c-c537-48bb-e8f1b26c7b5d
* Version Independent ID: 3f8a0a7b-7d1e-735f-3098-cebc82e980df
* Content: [WorkerHostBuilderExtensions.ConfigureFunctionsWorkerDefaults Method (Microsoft.Extensions.Hosting) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.workerhostbuilderextensions.configurefunctionsworkerdefaults?view=azure-dotnet&preserve-view=true#Microsoft_Extensions_Hosting_WorkerHostBuilderExtensions_ConfigureFunctionsWorkerDefaults_Microsoft_Extensions_Hosting_IHostBuilder_)
* Content Source: [xml/Microsoft.Extensions.Hosting/WorkerHostBuilderExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Extensions.Hosting/WorkerHostBuilderExtensions.xml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the durable function extensions are maintained as [#2170](https://github.com/Azure/azure-functions-durable-extension/issues/2170).
