### ISSUE TITLE
Invoke-DataPlaneGenerateSDKPackage.ps1 will fail the first time

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-net#28627]
## Problem

If you specify a relative path in `-sdkPath`, the `Invoke-DataPlaneGenerateSDKPackage.ps1` will fail the first time. But it can succeed in the next trial.

**Comment by chunyu3** [comment]
resolved in PR https://github.com/Azure/azure-sdk-for-net/pull/28595
