### ISSUE TITLE
Re-record SQL tests

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-sdk-for-net#28621]
The Azure.Resourcemanager.Sql SDK has updated API versions for some resources but the tests are not re-recorded. It's not caught in CI as the tests are marked with `RunTestFrequency.Manually` and skipped in CI tests. We should re-record the tests before GA.

**Comment by mcgallan** [comment]
The tests re-record finished [branch](https://github.com/mcgallan/azure-sdk-for-net/tree/SqlTest_Record2022.05) and [pr](https://github.com/Azure/azure-sdk-for-net/pull/29148)
