### ISSUE TITLE
Cdn review comments that need service team confirmation

### ISSUE THREAD

**Issue by Yao725** [Azure/azure-sdk-for-net#28622]
1. Why is this [provisioningState](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/cdn.json#L5519) a string instead of enum? We saw that some of the `provisioningState` definitions are enum but others are string, so I'm wondering if we can unify the type.
2. Is this [validationData](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/cdn.json#L5515) a [BinaryData](https://docs.microsoft.com/en-us/dotnet/api/system.binarydata?view=dotnet-plat-ext-6.0)?
3. Some models seem to have the similar even same definitions. One example is `operator`, you can see [ClientPortOperator](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/cdn.json#L4012-L4030), [CookiesOperator](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/cdn.json#L3864-L3882), [HostNameOperator](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/cdn.json#L4120-L4138) and other operators almost share the same definition. The question here is why we have to repeat the definition multiple times. Is it possible to define a common extensible enum in this scenario?
4. Can we change the type of [unit](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/cdn.json#L5873-L5877) to extensible enum so it can keep consistency with [UsageUnit](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L5847-L5856) in afdx?
5. Is the `groupId` in [SharedPrivateLinkResourceProperties](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L4910-L4912) a [ResourceIdentifier](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/ResourceIdentifier.cs) like `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}`? Same question in [keyId](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L4631-L4634).
6. Why is [this](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L4245-L4255) called `AfdMinimumTlsVersion` instead of `AfdTlsVersion`? What's the meaning of `Minimum`? Same question in [cdn MinimumTlsVersion](https://github.com/azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/cdn.json#L5580-L5591).
7. Why all these operations have the same description?

> https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L90
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L929
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L1353
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L2308

**Comment by ChenglongLiu** [comment]
3. Some operators have different definitions, also different operators may extend different property
6. AfdMinimumTlsVersion means the minimum TLS version to support, all TLS versions greater or equal to AfdMinimumTlsVersion are supported

**Comment by t-bzhan** [comment]
For question 5: 

> Is the groupId in [SharedPrivateLinkResourceProperties](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L4910-L4912) a [ResourceIdentifier](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/ResourceIdentifier.cs) like /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}? Same question in [keyId](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L4631-L4634).

Both properties are not Resource Identifiers, [groupId](https://docs.microsoft.com/en-us/cli/azure/network/private-endpoint?view=azure-cli-latest#:~:text=of%20edge%20zone.-,%2D%2Dgroup%2Did,the%20supported%20group%20ids.%20You%20must%20provide%20this%20except%20for%20PrivateLinkService.,-%2D%2Dgroup%2Dids) is a concept used by private link, it means the ID of the group obtained from the remote resource that this private endpoint should connect to.  The value  is like:
```
 az network private-link-resource list -g bogroup -n boplstest --type Microsoft.Storage/storageAccounts --query "[*].properties.groupId"
Resource ID will be ignored since other three arguments have been provided.
[
  "blob",
  "blob_secondary",
  "table",
  "table_secondary",
  "queue",
  "queue_secondary",
  "file",
  "web",
  "web_secondary",
  "dfs",
  "dfs_secondary"
]
```
The keyId is not referring any azure resource.

**Comment by t-bzhan** [comment]
For question 2:

> Is this [validationData](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/cdn.json#L5515) a [BinaryData](https://docs.microsoft.com/en-us/dotnet/api/system.binarydata?view=dotnet-plat-ext-6.0)?

It is just plain string.

**Comment by t-bzhan** [comment]
For question 1:

> Why is this [provisioningState](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/cdn.json#L5519) a string instead of enum? We saw that some of the provisioningState definitions are enum but others are string, so I'm wondering if we can unify the type.

Yes, we should unify the type.

For question 4

> Can we change the type of [unit](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/cdn.json#L5873-L5877) to extensible enum so it can keep consistency with [UsageUnit](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cdn/resource-manager/Microsoft.Cdn/stable/2021-06-01/afdx.json#L5847-L5856) in afdx?

Yes, we should reuse the model.

For question 7

> Why all these operations have the same description?

Those are copy typos, we should change the description accordingly.

**Comment by Yao725** [comment]
Thanks @ChenglongLiu and @t-bzhan for the update, it helps a lot!

**Comment by ChenglongLiu** [comment]
@Yao725 Question 7 has been fixed

**Comment by ChenglongLiu** [comment]
Question 1 and 4 have been fixed

**Comment by Yao725** [comment]
Close this one as the comments have been resolved and we have released the stable version for Cdn.
