### ISSUE TITLE
[QUERY] Routing messages to the same runned consumers

### ISSUE THREAD

**Issue by verdysh** [Azure/azure-sdk-for-net#28633]
### Library name and version

Azure.Messaging.ServiceBus 7.7.0

### Query/Question

I had that scenario in Kafka and now I want accomplish similar behavior with Service bus.

I have topic and subscription on it. Every message in this topic have some key which is customer id. If I run few consumers, every consumer will consume some message randomly, but it's not I really want.

What I want. I have customers with id 1,2,3,4,5,6. I run 2 consumers and send 6 messages every of which contains customer id 1-6. In perfect case I want consumer1 and consumer2 will receive 3 messages each. It doesn't matter what exactly id they receive, important if I send the same messages again, consumer1 and consumer 2 will receive the same messages. It will be okay if consumer1 receives messages with customer id 1-4, consumer 2 with 5-6. I mean it's not required every consumer receive exactly the same count of messages. But it's really highly desirable that each consumer receive more or less similar count of messages.

If I add third consumer I want each of three consumers to receive ~2 messages each. And it also doesn't matter who receive specific messages. It's important each of them receives messages with id which doesn't receive any other consumer.

I have read about sessions. It seems like session is purposed for my scenario. But there are some unpleasant moments:

1. With sessions you have to set session for consumer before start receiving. First, in my case I will have thousands of sessions and this looks strange to me. Second, there will be new customers that don't yet have an ID at the time the consumers are launched.
2. I have read somewhere that you should close sessions explicitly when receive last message in the session. In my case session can live infinity time and I don't know if it already finished yet or not.

Considering that 2 points I think sessions doesn't suitable for my scenario.

In Kafka, you can implement this scenario with partitions. Each message with specified key will be sent to one specific partition. Every consumer reads from particular partition and you don't have to think about all that because all that is implemented at the Kafka's protocol level. Knowing that I also tried use partitions in Service bus when was creating a topic and passing PartitionKey in every message. But consumers still receive messages randomly.

How can I achieve different consumers don't receive messages with the same key given that amount of keys is large and at starting moment I even don't know all possible keys?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
I think sessions should work for your scenario.

> With sessions you have to set session for consumer before start receiving. First, in my case I will have thousands of sessions and this looks strange to me. Second, there will be new customers that don't yet have an ID at the time the consumers are launched.

You don't have to specify the session that you want to receive from. When using the [ServiceBusSessionProcessor](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample05_SessionProcessor.md), the next available session will be processed by default. For customers that don't yet have an ID, you could just treat this as a separate session that contains yet to be initialized customers. I assume you would need to receive and complete these messages, initialize the customer somehow, and then resend a new message with the customer ID set. When the customer is uninitialized, the session ID could just be an empty string. Alternatively, you could use a separate queue (and processor) for these uninitialized customers so that these get processed independently of the initialized customers. 

> I have read somewhere that you should close sessions explicitly when receive last message in the session. In my case session can live infinity time and I don't know if it already finished yet or not.

This is not really true. Sessions are designed to be potentially long-living. From the [docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions#first-in-first-out-fifo-pattern):
> On session-aware queues or subscriptions, sessions come into existence when there's at least one message with the session ID. Once a session exists, there's no defined time or API for when the session expires or disappears. Theoretically, a message can be received for a session today, the next message in a year's time, and if the session ID matches, the session is the same from the Service Bus perspective. Typically, however, an application has a clear notion of where a set of related messages starts and ends. Service Bus doesn't set any specific rules.

The last line is saying that although sessions can live forever, in practice, there is usually some defined end of the session for the application scenario. In the case of customers, I would imagine the session would end if the customer deleted their account or something like that. However, whether or not there is a defined endpoint for the session is irrelevant as far as Service Bus is concerned. As mentioned in the docs, if a message shows up years later with the same sessionId, it will be treated as being part of the same session.

**Comment by verdysh** [comment]
@JoshLove-msft , thanks for the answer!

I took a closer look on ServiceBusSessionProcessor.

It is doing almost what I want. But there is a little issue.
When you add new consumers they will not receive messages related to sessions which already were received some of current consumers.

Example. You have 2 running consumer. Something have happened and load began to increase sharply. Sessions in messages are the same, but there are more messages itself. Your current 2 instances don't make it to process messages on time. If you add two more instances and load balance this way your system will meet requirements.

The issue is if you add more instances rebalancing won't happens and your additional instances will idle and current instances will not have time to process messages on time. New consumers might only receive messages with new sessions.

In Kafka when you add new consumer it starts process called "rebalancing" and after that delivers messages between all consumers including you just added.

In case of Service bus it seems some rebalancing happens only when consumer disconnects. Is it possible to achieve rebalancing when adding new consumer? Or the only option for that is to down all current consumers and then start up new number of instances?

**Comment by JoshLove-msft** [comment]
If you want to configure how much processing occurs within each session, you can set the 
[MaxConcurrentCallsPerSessionProperty](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussessionprocessoroptions.maxconcurrentcallspersession?view=azure-dotnet). You can also change the concurrency while the processor is running using the [UpdateConcurrency](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussessionprocessor.updateconcurrency?view=azure-dotnet) method.

**Comment by verdysh** [comment]
For example I have messages with sessions from 1 to 30 000. Remember session = customer. I know one my consumer can handle messages from about 10 000 sessions without latency. I know it because I made some tests. I understand that from different customers I can receive different amount of messages. But empirically I know that one consumer will successfully handle messages from about 10 000 customers. So I run 3 consumers and I want each consumer consume about ~10 000 customers each.

Count of customers become bigger, let's say 31 000. I want each customer already handles about ~10 333 sessions WITHOUT any reconfiguration and restarts. Then let's say I discovered there are already 35 000 customers. I want just add one more consumer for purpose each consumer become to cunsume about 8 750 sessions. I.e. make less loading on each consumer. When customers count will become ~40 000 I want each consumer handles ~10 000 sessions. I would want all this things work WITHOUT manually intervention into consumer's configuration or relaunching.

I.e. I want to have really scalable (add/remove consumers when I need) and reliable (I dont want to restart anything) system. I did similar solution with Kafka and hoped I could make it with Service bus.

**Comment by JoshLove-msft** [comment]
The UpdateConcurrency method allows you to tweak the concurrency at runtime, but you would need to apply some heuristic to determine when to change concurrency. 

If you want this to be more automatic, you could consider using the [Service Bus trigger in Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp). You can still configure the max concurrent sessions, but the functions runtime will handle automatically scaling up/down the number of functions instances based on the amount of messages in the queue and how quickly they are being consumed.
