### ISSUE TITLE
UploadRange should not complain about a stream with length larger than 4MB

### ISSUE THREAD

**Issue by ross-perry-epm-home** [Azure/azure-sdk-for-net#28636]
### Library name

Azure.Storage.Files

### Please describe the feature.

very odd, the UploadRangeAsync fails if the stream used has a length > the 4mb limit.
The method should read what is specified in the range, not how long the supplied stream is. If the range specifies more than 4MB then throw the error.

**Comment by PramodValavala-MSFT** [comment]
@ross-perry-epm-home Based on the [parameter description](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharefileclient.uploadrangeasync?view=azure-dotnet), the stream should be just one with the range to upload. For uploading a complete stream, the [`UploadAsync`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharefileclient.uploadasync?view=azure-dotnet) method is better suited.

This [SO Post](https://stackoverflow.com/q/6949441/10417839) has an approach for getting a substream, that you could use.
