### ISSUE TITLE
[QUERY] Restoring a SqlDatabase using Azure.ResourceManager SDK

### ISSUE THREAD

**Issue by glaidler** [Azure/azure-sdk-for-net#28641]
### Library name and version

Azure.ResourceManager.Sql 1.0.0-beta 4

### Query/Question

I can't seem to find the way to restore an existing database with a point in time.  The REST endpoint uses "CreateOrUpdate" which has CreateMode options, but this isn't reflected in the SqlDatabaseCollection.

Am I missing something?

### Environment

.net 6.0 windows64

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by cmeyertons** [comment]
This is still an issue in `1.0.0-beta.5` :/

**Comment by fengzhou-msft** [comment]
[SqlDatabaseData](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/sqlmanagement/Azure.ResourceManager.Sql/src/Generated/SqlDatabaseData.cs#L188-L207) which is needed as input parameter for `SqlDatabaseCollection.CreateOrUpdate` has a property called `CreateMode`. Therefore, I believe you can also restore an existing database with a point in time with the .NET SDK.

**Comment by fengzhou-msft** [comment]
Close due to inactivity. Please try with above instructions and let us know if it still doesn't work for you.
