### ISSUE TITLE
Support Service Bus transactions

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-sdk-for-net#28650]
Service Bus SDK provides a pattern to lock a message, and then send a message - and it completes the message when you successful send the message.  Would be good to have this pattern in our binding so you could do a service bus TRIGGER and service bus OUTPUT BINDING and associate the output binding with the trigger lock using the transaction feature in their SDK

**Comment by jsquire** [comment]
@JoshLove-msft:  Would you please triage and advise?

**Comment by JimSuplizio** [comment]
Hi @jeffhollan, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
