### ISSUE TITLE
Support for returning HTTP status code from EventGrid-triggered function

### ISSUE THREAD

**Issue by kzu** [Azure/azure-sdk-for-net#28659]
According to the [docs on delivery and retries](https://docs.microsoft.com/en-us/azure/event-grid/delivery-and-retry#failure-codes) 
for EventGrid, the returned HTTP status code can have a significant (and useful!) effect on the retry policy. It would be quite useful 
for a function using the EventGrid binding to be able to report such status codes, yet the documentation only showcases `void` 
returning implementations.

How would a function, for example, report a `503 Service Unavailable` for a downstream processor so that the `Retry after 30 seconds 
or more` applies automatically?

- Function App version: 2.0
- C# web app. 

NOTE: trying to return `Task<IActionResult>` or `Task<HttpResponseMessage>` results in an error like:

```
The '[NAME]' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method '[NAME]'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter '$return' to type [TYPE]&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
```
(where `[NAME]` is the name of the function and `[TYPE]` is either `HttpResponseMessage` or `IActionResult`). 

> NOTE: for `IActionResult`, I did add a call to `Configure` to add MVC:

```
        public void Configure(IWebJobsBuilder builder)
        {
            ...
            builder.Services.AddMvcCore();
        }
```

#### Repro steps

Provide the steps required to reproduce the problem:

1. Create an Azure Functions app in VS
2. Select an EventGrid trigger function and replace the code with:

```
        [FunctionName("return-status-code")]
        public static Task<HttpResponseMessage> RunAsync([EventGridTrigger] EventGridEvent e)
            => Task.FromResult(new HttpResponseMessage(HttpStatusCode.ServiceUnavailable));
```

3. F5 and see the error:

```
[10/6/2020 18:46:02] Microsoft.Azure.WebJobs.Host: Error indexing method 'return-status-code'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter '$return' to type HttpResponseMessage&. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
[10/6/2020 18:46:02] Error indexing method 'return-status-code'
```

#### Expected behavior

Things just work, EventGrid gets the status code from the response and uses that to apply the retry policy as documented.

#### Known workarounds

Use a webhook subscription/function instead of an EventTrigger function :(

**Comment by linfengslalom** [comment]
Any updates on this?...

**Comment by JimSuplizio** [comment]
Hi @kzu, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
