### ISSUE TITLE
Support ReceiveAndDelete mode

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-sdk-for-net#28651]
Customer (from CSE) requested ability to change the trigger mode to receive and delete.  They understand messages may be lost but want the higher throughput that pattern can create.

**Comment by JimSuplizio** [comment]
Hi @jeffhollan, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
