### ISSUE TITLE
Forward along the header values to the azure function

### ISSUE THREAD

**Issue by edouardpoitras** [Azure/azure-sdk-for-net#28658]
I would like to use the delivery properties feature of an EventGrid Subscription. This is the documentation provided in the Azure portal:

```
Properties Sent on Event Delivery
Define headers that are included with the request sent to the destination. For example, you may want to set a fixed value for the Authorization header to be sent with the request. Alternatively, you can set the value as a JsonPath reference to an existing envelope property or to any property in the event data. For more information, consult Event Grid documentation.
Valid dynamic header source fields for currently selected event schema:

    id, topic, subject, eventtype, dataversion
    Custom properties inside the data payload, using "." as the nesting separator. (e.g. data, data.key, data.key1.key2)
```

This is great! However, I need a way to retrieve those header values on my Azure EventGrid Trigger Function.
I tried binding the HttpRequestMessage object in the function parameters which didn't work:

```
Microsoft.Azure.WebJobs.Host: Error indexing method 'ProcessingFunctionTrigger'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'req' to type HttpRequestMessage. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
```

I'm clearly not grasping the inner workings here :)

In any case, I was browsing the source code and noticed the headers are not being passed along to the listener function in the `Task<HttpResponseMessage> ProcessAsync(HttpRequestMessage req)` method.

Am I missing something here? Is there a way to retrieve the headers without passing them to the listener function explicitly?

Thanks!

**Comment by antonGritsenko** [comment]
Is there any update on this topic? This is really pain to handle different events with the same function without having access to the headers.
