### ISSUE TITLE
Webhook should return immediately, without blocking on user code.

### ISSUE THREAD

**Issue by MikeStall** [Azure/azure-sdk-for-net#28669]
Currently, the http handler blocks on dispatching to the user code. 
https://github.com/Azure/azure-functions-eventing-extension/blob/c6abcec4689a0d78044df181242238d342058123/src/EventGridExtension/EventGridExtensionConfig.cs#L86-L102 

It should queue up dispatch to happen in the background and then return.  We may need some support from SDK to enable this properly.   The queue must be durable (ie, Azure Queue), and the message must be queued before returning success to the webhook.

**Comment by JimSuplizio** [comment]
Hi @MikeStall, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
