### ISSUE TITLE
Use an intermediary queue between host receive and process

### ISSUE THREAD

**Issue by jeffhollan** [Azure/azure-sdk-for-net#28667]
Customers today are unable to use event grid directly for executions that last longer than 30 seconds as Event Grid only waits 30 seconds for a response.  In addition, retries are only handled by the Event Grid service

We've discussed adding event grid messages to an intermediary queue (similar to how we do blobs) so they can be retried or processed async.  The host would return a 202 to Event Grid right away after queue creation and the host could take from there.

Related to Azure/azure-sdk-for-net#28669

**Comment by jsquire** [comment]
@JoshLove-msft:  Would you please triage and advise?

**Comment by JimSuplizio** [comment]
Hi @jeffhollan, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
