### ISSUE TITLE
Listener Stop Handling improvements

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-sdk-for-net#28668]
In the listener [here](https://github.com/Azure/azure-functions-eventgrid-extension/blob/332f71b9104b3eefbe1131c877800011d925418a/src/EventGridExtension/EventGridListener.cs#L27), Stop/Cancel/Dispose are noops and there is a TODO in the code.

When the listener is stopped, shouldn't the listener be removed from the listener store?

Also thinking of this in the context of https://github.com/Azure/azure-functions-host/issues/2497. We've added listener retries - if a listener throws on Start, we'll retry. Doesn't look like your listener store Add call is likely to throw, but if it does, it has to be prepared to be called again.

**Comment by JimSuplizio** [comment]
Hi @mathewc, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
