### ISSUE TITLE
Fix summary for JsonObjectSerializer

### ISSUE THREAD

**Issue by JosefPihrt** [Azure/azure-sdk-for-net#28662]
Hi,

I think that at the beginning of the document there should be

A [ObjectSerializer](https://docs.microsoft.com/en-us/dotnet/api/azure.core.serialization.objectserializer?view=azure-dotnet) implementation that uses [JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer) to for serialization/deserialization.

instead of 

A [JsonObjectSerializer](https://docs.microsoft.com/en-us/dotnet/api/azure.core.serialization.jsonobjectserializer?view=azure-dotnet) implementation that uses [JsonSerializer](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsonserializer) to for serialization/deserialization.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 036a6ed6-845f-3653-b8fa-aeb89c6b38c6
* Version Independent ID: 217c7551-7c44-6e3a-249d-e859361e24c7
* Content: [JsonObjectSerializer Class (Azure.Core.Serialization) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.core.serialization.jsonobjectserializer?view=azure-dotnet)
* Content Source: [xml/Azure.Core.Serialization/JsonObjectSerializer.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Core.Serialization/JsonObjectSerializer.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.
