### ISSUE TITLE
What kind of algorithm this token handler able to support?

### ISSUE THREAD

**Issue by hieunguyenmsft** [Azure/azure-sdk-for-net#28665]
Hi, just for my learning, can you help to list out the algorithms this token handler can support to decrypt a JWE?
The specific setup I'm looking for is:
EC key family:
crv: P-256 (SecP256r1)
enc: A256GCM
alg: ECDH-ES
kdf: ConcatKDF (https://datatracker.ietf.org/doc/html/rfc7518#section-4.6.2 which links to 6.2.2.2 of https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-56Ar2.pdf)

Sample of JOSE Header:
{
  "alg":"ECDH-ES",
  "enc":"A256GCM",
  "epk":
       {   
        "kty":"EC",
        "crv":"P-256",
        "x":"EUA2cFR9ZrGJozbkwYeyBrbrG3p4ChHBQu_sWem2sgM",
        "y":"n6WQz7uMkIALgLM5xriANs5VXKy_2Q71jetoI6Pzojk",
       }
}

Thank you,
Hieu

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc093f76-fb52-48ad-af16-e448451081df
* Version Independent ID: 33f601dc-c687-b975-a877-93be1858581e
* Content: [JwtSecurityTokenHandler.DecryptToken(JwtSecurityToken, TokenValidationParameters) Method (System.IdentityModel.Tokens.Jwt) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtsecuritytokenhandler.decrypttoken?view=azure-dotnet#system-identitymodel-tokens-jwt-jwtsecuritytokenhandler-decrypttoken(system-identitymodel-tokens-jwt-jwtsecuritytoken-microsoft-identitymodel-tokens-tokenvalidationparameters))
* Content Source: [xml/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `System.Identityodel.Tokens.Jwt` package is maintained as [#1855](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1855).
