### ISSUE TITLE
Manage claim required errors

### ISSUE THREAD

**Issue by oionut** [Azure/azure-sdk-for-net#28670]
I have the following setup:
    - azure function with a ServiceBus trigger (topic subscription)
    - for authentication I'm using the ManagedIdentity approach and for this I assigned the _"Azure Service Bus Data Receiver"_ role to the MI for that specific topic subscription
    - the function is using the dotnet runtime with Microsoft.Azure.WebJobs.Extensions.ServiceBus nuget version used is 5.3.0
    - the function runtime version is 4 (dotnet 6)

The documentation states the following regarding the Access attribute and Manage access permission:
"Access rights for the connection string. Available values are manage and listen. The default is manage, which indicates that the connection has the Manage permission. If you use a connection string that does not have the Manage permission, set accessRights to "listen". Otherwise, the Functions runtime might fail trying to do operations that require manage rights. In Azure Functions version 2.x and higher, this property is not available because the latest version of the Service Bus SDK doesn't support manage operations."
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=in-process%2Cextensionv5&pivots=programming-language-csharp#attributes
My understanding is that Manage claim in not supported for version 2 or higher.

The issue:
    I can see a constant stream of _"Manage,EntityRead claims required for this operation."_ errors in Service Bus AzureDiagnostics logs.
    The function on the other side is triggered and there are no logs on its side complaining about any kind of ServiceBus access.
What would be the cause of this? Is Manage still required?

**Comment by jsquire** [comment]
@JoshLove-msft:  Would you please be so kind as to triage?

**Comment by JoshLove-msft** [comment]
Hi @oionut, 
The docs are a bit misleading as the section you are referring to contains information about the 4.x version of the extension, but you are using 5.x. I will see about getting this fixed up.

I think the issue you are hitting is that the operations that are being used to gather metrics needed for scaling by the extension _do_ require manage claims. In order to avoid these errors you would need to grant the [Azure Service Bus Data Owner](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#azure-service-bus-data-owner) role to your managed identity.

**Comment by oionut** [comment]
Hi @[JoshLove-msft](https://github.com/JoshLove-msft). Thanks for replying and for the clarifications.
I can confirm that with the [Azure Service Bus Data Owner](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#azure-service-bus-data-owner) role assigned the service bus errors and function warnings are gone.

Regarding the documentation, I think this should be updated as well: https://docs.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2#configure-your-service-bus-trigger-with-a-managed-identity
