### ISSUE TITLE
Question: Why is there no way to get resources used by LogsBatchQuery?

### ISSUE THREAD

**Issue by loudar** [Azure/azure-sdk-for-net#28681]
MetricsQueryResult has the property Cost, but there seems to be no way to get how resource-intensive a LogsBatchQuery was. Is this a technical limitation or just not implemented? Would love to use it and I think it could benefit many others.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3e61d94-77d2-c317-8968-5591758e549b
* Version Independent ID: 37aa7885-d115-139a-bb1a-27c3eb32b9de
* Content: [LogsBatchQueryResult Class (Azure.Monitor.Query.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.monitor.query.models.logsbatchqueryresult?view=azure-dotnet)
* Content Source: [xml/Azure.Monitor.Query.Models/LogsBatchQueryResult.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Monitor.Query.Models/LogsBatchQueryResult.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
//cc: @pallavit

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nisha-bhatia** [comment]
@loudar We currently do not support cost for LogsBatchQuery and are not planning on adding it at the moment. Thank you.

**Comment by loudar** [comment]
Thank you for the info! Would love to see it in the future :)

**Comment by scottaddie** [comment]
@loudar Would you expect to see a cost per query or a total cost for the entire batch of queries?
