### ISSUE TITLE
[QUERY] The library is not published to nuget gallery

### ISSUE THREAD

**Issue by shrohilla** [Azure/azure-sdk-for-net#28682]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Kafka 3.3.3

### Query/Question

I tried with partner pipeline and it was published to the blob of drop-signed, but from there it didn't reached to the nuget gallery.
Please have a look at this

**Comment by weshaggard** [comment]
I'm working with @shrohilla offline to resolve this issue so closing this.
