### ISSUE TITLE
Typo in a property description

### ISSUE THREAD

**Issue by Kor-Hal** [Azure/azure-sdk-for-net#28684]
Hello,

The "ChangedOn" property description says : "The time this time was changed."
I think it should say "The time this item was changed."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0225e72-abaf-d92b-0fa6-59541a11ae21
* Version Independent ID: 3af7b75d-3365-2312-5fac-bcb390e9d83c
* Content: [ShareFileItemProperties Class (Azure.Storage.Files.Shares.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.models.sharefileitemproperties?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Files.Shares.Models/ShareFileItemProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.Shares.Models/ShareFileItemProperties.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@Kor-Hal Thanks for reaching out to us and sharing this feedback. I am looking into this issue. I will get back with an update once I have more details.

**Comment by navba-MSFT** [comment]
@Kor-Hal The above PR has been filed to address this issue. It is currently under review phase. In the meantime, if you have any questions please feel free to ask.

**Comment by Kor-Hal** [comment]
Adding comment to avoid bot closing the issue (no question to ask).
