### ISSUE TITLE
Upgrade the swagger review pipeline to support mgmt .net track 2

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#28690]

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/18996

**Comment by fengzhou-msft** [comment]
The support for mgmt .net track 2 in swagger pipeline was in place and I have updated the settings for all the resource providers that with at least beta version track 2 SDKs to generate track 2 SDKs during swagger review in https://github.com/Azure/azure-rest-api-specs/pull/18996.
