### ISSUE TITLE
RequestContext is not passed to LRO Update operations

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#28696]
### Problem

For an LRO, we don't send a RequestContext when sending update requests.  This means customers cannot modify the pipeline for these operations they way they can for other protocol methods.

### Implementation Details
In DPG, in [LowLevelOperationHelpers](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/LowLevelOperationHelpers.cs#L29), we pass request context to ProcessMessage for the initial start request.  LowLevelFuncOperation wraps NextLinkOperationImplementation, which [passes just CancellationToken to ProcessMessage](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/NextLinkOperationImplementation.cs#L232).  LowLevelFuncOperation will need to persist the request context to use it in update operations, and NextLinkOperationImplementation will need to be updated to take the request context.

If there is a need to customize the requests separately, we should allow this via [manual polling of the operation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/LongRunningOperations.md#manually-updating-the-status).  In the linked sample, both the start method and the update method should take a RequestContext parameter.

**Comment by annelo-msft** [comment]
This is a DPG v1.1 feature.  @KrzysztofCwalina FYI.

**Comment by lirenhe** [comment]
@AlexanderSher,  some of the links in the task are already out of data, but as this is related to Azure Core, could you help to check whether there are still some action needed?  Thanks

**Comment by pallavit** [comment]
@AlexanderSher , @lirenhe is this issue still valid?

**Comment by lirenhe** [comment]
@ArcturusZhang, could you take a look at this issue?  There are some update about the LRO handling in TypeSpec path, so is this issue still valid?  Thanks

**Comment by ArcturusZhang** [comment]
This has been fixed. In our currently used helpers, the request context is passing along the way down to the HttpPipeline:
https://github.com/Azure/autorest.csharp/blob/aa49fb51be4a35ba9d823b6172bf79b2d7fa7cf7/src/assets/Azure.Core.Shared/ProtocolOperationHelpers.cs#L21
https://github.com/Azure/autorest.csharp/blob/aa49fb51be4a35ba9d823b6172bf79b2d7fa7cf7/src/assets/Azure.Core.Shared/HttpPipelineExtensions.cs#L16
Therefore I believe this issue has been resolved. Closing
