### ISSUE TITLE
[FormRecognizer] Re-enable AdminOps test

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#28705]
Test fails with the following error:

```
Error Message:
     Expected: not null
  But was:  null
```

Error happens at:
https://github.com/Azure/azure-sdk-for-net/blob/24554f0fca46d54584e3d609510313c2754af7ec/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/DocumentModelAdministrationClient/DocumentModelAdministrationClientLiveTests.cs#L226-L233

Example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1551570&view=logs&j=75bb6cb8-85fe-5b08-10aa-320cf6c5cc8f&t=b18a6ae3-fe77-5f49-ecb4-5d3125e0bf5e&l=275

Test behavior is flaky, which means that sometimes we get no `DocumentModelInfo` instances back. Could this be caused by a race condition on the service side (`GetModelAsync` request arrives before list of models being updated)?

**Comment by pallavit** [comment]
@kinelski is this issue still present?

**Comment by kinelski** [comment]
Test has been re-enabled weeks ago and we haven't seen this issue again. Closing this.
