### ISSUE TITLE
[Sample Update] MicrosoftDocs/mslearn-access-blob-storage-metrics-from-code

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-net#28721]
Azure Monitor, Monitor mgmt  SDK(C# T1, hold for track2);
Azure Rest Authentication, Rest Authentication SDK(C# T1, hold for track2);

https://github.com/MicrosoftDocs/mslearn-access-blob-storage-metrics-from-code

**Comment by pallavit** [comment]
@xboxeer is this still valid?

/cc: @ArthurMa1978 as FYI
