### ISSUE TITLE
[Sample Update]Getting Started with Azure Storage Resource Provider in .NET

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-net#28722]
Azure Resource, resource mgmt sdk(C# T1,hold for GA);
Azure Storage, storage mgmt sdk(C# T1,hold for GA);
Azure Identity(C# T1)
https://github.com/MicrosoftDocs/samples/blob/master/Azure-Samples/storage-dotnet-resource-provider-getting-started/storage-dotnet-resource-provider-getting-started/index.yml

**Comment by pallavit** [comment]
@xboxeer is this still valid?

/cc: @ArthurMa1978 as FYI
