### ISSUE TITLE
[Sample Update] Azure-Samples/service-bus-dotnet-management

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-net#28720]
Azure Resource, Resource mgmt SDK (C# T1, Hold for GA)
Azure ServiceBus, ServiceBus mgmt SDK (C# T1, Hold for GA)

https://github.com/Azure-Samples/service-bus-dotnet-management

**Comment by pallavit** [comment]
@xboxeer is this still valid?
