### ISSUE TITLE
[BUG] ResourceManager.Sql Errors

### ISSUE THREAD

**Issue by markblue777** [Azure/azure-sdk-for-net#28730]
### Library name and version

Azure.ResourceManager.Sql (1.0.0-beta4)

### Describe the bug

Calling 
`var resdb = _sqlServerResource .GetSqlDatabase("dbname);`

returns an exception of the following when the database name exists within the SqlServerResource

`System.InvalidOperationException: 'The requested operation requires an element of type 'Number', but the target element has type 'String'.'`

If call the endpoint with a database that does not exist it returns the following exception

`Azure.RequestFailedException: 'The Resource 'Microsoft.Sql/servers/testertenanta-sql-dev-uks/databases/testertenanbta-db-dev-uks' under resource group 'vf-rg-dev-uks' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix`

### Expected behavior

`var resdb = _sqlServerResource .GetSqlDatabase("dbname);` 

should return a SqlDatabaseResource

### Actual behavior

Calling 
`var resdb = _sqlServerResource .GetSqlDatabase("dbname);`

returns an exception of the following when the database name exists within the SqlServerResource

`System.InvalidOperationException: 'The requested operation requires an element of type 'Number', but the target element has type 'String'.'`

If call the endpoint with a database that does not exist it returns the following exception

`Azure.RequestFailedException: 'The Resource 'Microsoft.Sql/servers/testertenanta-sql-dev-uks/databases/testertenanbta-db-dev-uks' under resource group 'vf-rg-dev-uks' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix`

### Reproduction Steps

Calling 
`var resdb = _sqlServerResource .GetSqlDatabase("dbname);`

returns an exception of the following when the database name exists within the SqlServerResource

`System.InvalidOperationException: 'The requested operation requires an element of type 'Number', but the target element has type 'String'.'`

If call the endpoint with a database that does not exist it returns the following exception

`Azure.RequestFailedException: 'The Resource 'Microsoft.Sql/servers/testertenanta-sql-dev-uks/databases/testertenanbta-db-dev-uks' under resource group 'vf-rg-dev-uks' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
The same issue was reported in #28387 and resolved.

**Comment by fengzhou-msft** [comment]
Please try with [Azure.ResourceManager.Sql 1.0.0-beta.5](https://www.nuget.org/packages/Azure.ResourceManager.Sql/1.0.0-beta.5).
