### ISSUE TITLE
ListGeoRegionsAsync() fails due to using wrong HTTP verb (POST when it should be GET)

### ISSUE THREAD

**Issue by exzachtly1** [Azure/azure-sdk-for-net#2873]
When calling extension method ListGeoRegionsAsync using WebsiteManagementClient, I am receiving an error that the method does not exist on the API. This is because it attempts to call the API method using POST instead of GET. It should issue a GET request at the following resource:

https://management.azure.com/subscriptions/[subid]/providers/Microsoft.Web/geoRegions?api-version=2015-08-01

The generated code for this is in WebSiteManagementClient.ListGeoRegionsWithHttpMessagesAsync(). I'm not familiar enough with AutoRest to know why this might be happening in the gen'd code, but wanted to report the issue either way.

**Comment by adrianhall** [comment]
Is this still an issue with App Services?  If so, please provide the .NET library you are using and version.
