### ISSUE TITLE
Consider adding EntityPath and FullyQualifiedNamespace to the various processor event args

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#28769]
Currently, these are only available in [ProcessErrorEventArgs](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.processerroreventargs?view=azure-dotnet), but it can be helpful to have it on all event args if customers are reusing the same handler for various entities.

**Comment by KrzysztofCwalina** [comment]
if possible, can we also add Topic and Subscription properties?

**Comment by JoshLove-msft** [comment]
> if possible, can we also add Topic and Subscription properties?

In the case of subscriptions, the EntityPath would be {Topic}/Subscriptions/{Subscription}.
