### ISSUE TITLE
[FEATURE REQ] Managing Role Assignments in Azure.ResourceManager

### ISSUE THREAD

**Issue by mathiasi** [Azure/azure-sdk-for-net#28797]
### Library name

Azure.ResourceManager

### Please describe the feature.

I'm using Microsoft.Azure.Management.Fluent to manage Role Assignments however the docs tell me to migrate to Azure.ResourceManager however I can't seem to find a way to manage Role Assignments in that library? Is it missing or did I not find the right documentation?

**Comment by ArthurMa1978** [comment]
@fengzhou-msft  Please help on this

**Comment by mathiasi** [comment]
I think this is a duplicate of #26110

**Comment by fengzhou-msft** [comment]
Please use `Azure.ResourceManager.Authorization`.
