### ISSUE TITLE
[BUG] Issue with updating custom domain in route - Azure Front Door (Premium/Standard)

### ISSUE THREAD

**Issue by baskaranauc** [Azure/azure-sdk-for-net#28793]
### Library name and version

Azure.ResourceManager.Cdn v1.0.0-beta.5

### Describe the bug

There is no option to update a created custom domain in an existing route in Azure Front Door (Premium/Standard)

### Expected behavior

the property `CustomDomains` in `AfdRoutePatch` should have read and write access.

### Actual behavior

In REST API, I am able to update a route with a newly added custom domain - https://docs.microsoft.com/en-us/rest/api/frontdoor/azurefrontdoorstandardpremium/routes/updat

but using C# library (Azure.ResourceManager.Cdn v1.0.0-beta.5), the custom domain property is read-only so the `CustomDomains`  cannot be set.

### Reproduction Steps

1. Create a custom domain in an Azure Front Door profile.
`customDomains.CreateOrUpdateAsync()`

2. Try to add the created custom domain in an existing route.
`route.UpdateAsync(WaitUntil.Completed, new AfdRoutePatch { _CustomDomains_ = customDomains });`

### Environment

.NET SDK (reflecting any global.json):
 Version:   5.0.406
 Commit:    3a48fd6fe5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.406\

Host (useful for support):
  Version: 5.0.15
  Commit:  3065735be7

.NET SDKs installed:
  5.0.406 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @baskaranauc , it's not the bug. `CustomDomains` is a list and we use `ChangeTrackingList` to initialize it in the [ctor](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cdn/Azure.ResourceManager.Cdn/src/Generated/Models/AfdRoutePatch.cs#L20). And then you can use `list.Add()` or `list = { }` to set its value.

Here is the sample code:
```csharp
var lro = await route.UpdateAsync(WaitUntil.Completed, new AfdRoutePatch
  {
    CustomDomains = { new ActivatedResourceReference { Id = customDomain.Id } }
  });
AfdRouteResource updatedRoute = lro.Value;
```

**Comment by baskaranauc** [comment]
Hi @Yao725 , Thank you. It's working as expected.

**Comment by Yao725** [comment]
Np, will close this issue as it's resolved, feel free to reopen it or open a new one if you still have problem.
