### ISSUE TITLE
Generate pagination code with a Transformation

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#28807]
For TextAnalytics REST API, we had a [transformation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics.Legacy.Shared/src/autorest.md#add-x-ms-paths-section-if-not-exists) that was in charge of generating the Pagination code for both Healthcare and AnalyzeActions functionalities.

Applying a similar transformation against the Language REST API code fails. Because of time constraints, for the May release, we are adding the code manually under an Internal `MicrosoftCognitiveLanguageServiceRestClient`. Note that the code is the same that codegeneration is supposed to generate.

The goal of this issue is to be able to generate the pagination code with a transformation, instead of us maintaining it to take full advantage of codegen.

**Comment by heaths** [comment]
@m-nash does this sound like anything we still need for TypeSpec codegen? Otherwise, we can probably just close this. /cc @pallavit (this is a code gen issue, so I've removed Service Attention).
