### ISSUE TITLE
[Text Analytics] Revisit the values for the extensible enum FhirVersion

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-for-net#28811]
Decide on a more friendly name for `FhriVersion.Four01` :)

**Comment by heaths** [comment]
It's also in the wrong namespace. There's no .Models namespace.

**Comment by deyaaeldeen** [comment]
In JS, [I am using the full version as the key](https://github.com/Azure/azure-sdk-for-js/blob/e0451efa327c944d3536e528d40ba50e2d90c0a5/sdk/textanalytics/ai-text-analytics/src/models.ts#L147-L150).

**Comment by heaths** [comment]
That's not a valid identifier in .NET. Like our ServiceVersions, we could maybe do "V4_0_1". What do others think? /cc @kristapratico

**Comment by kristapratico** [comment]
We just exposed a string in Python. Note that this was removed in the GA swagger, but we should revisit this issue in the post-GA beta when FHIR is re-introduced.

**Comment by deyaaeldeen** [comment]
For the record, the type of the parameter itself is also a string: https://github.com/Azure/azure-sdk-for-js/blob/e0451efa327c944d3536e528d40ba50e2d90c0a5/sdk/textanalytics/ai-text-analytics/src/generated/models/index.ts#L1535-L1542

The type I linked to in my previous comment is the enum of known values that customers could use to discover some known values.

**Comment by heaths** [comment]
In cases when we expect a lot of use, we typically use a "*WellKnownValues" static class of public constant values, which is idiomatic to .NET if an enum isn't appropriate.

**Comment by heaths** [comment]
I've done similar to JS but defined a `WellKnownFhirVersions` static class, since "WellKnown" is a common prefix for usage like this. The value itself is defined as `V4_0_1` which matches the pattern for our client options' `ServiceVersion`.

**Comment by heaths** [comment]
Punting to next version. `FhirVersion` was actually removed from `HealthcareTaskParameters` in 2022-05-01.

**Comment by heaths** [comment]
Pushing out since this isn't added back in till the next version of the service will we'll use after we GA TA.
