### ISSUE TITLE
[BUG] Unable to TxtRecord value

### ISSUE THREAD

**Issue by joostmeijles** [Azure/azure-sdk-for-net#28827]
### Library name and version

Microsoft.Azure.Management.Dns 1.0.0-preview1

### Describe the bug

There is no setter on the API for the TxtRecord value which makes it impossible to set a value.

See https://github.com/Azure/azure-sdk-for-net/blob/e44c3829c349b85e666d8b63ffa79bef6527d8a0/sdk/dns/Azure.ResourceManager.Dns/api/Azure.ResourceManager.Dns.netstandard2.0.cs#L195

### Expected behavior

Setter for TxtRecord value on public Api.

### Actual behavior

No setter on public api.

### Reproduction Steps

See above and https://github.com/Azure/azure-sdk-for-net/blob/e44c3829c349b85e666d8b63ffa79bef6527d8a0/sdk/dns/Azure.ResourceManager.Dns/api/Azure.ResourceManager.Dns.netstandard2.0.cs#L195

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@joostmeijles thank you for reaching us, I think the sdk you tried is Azure.ResourceManager.Dns 1.0.0-preview1?
This is beta sdk will be deprecated soon, and will have new package for you.
@HarveyLink  please help to confirm the new sdk support setter for TxRecord.

**Comment by HarveyLink** [comment]
Hi @joostmeijles 
Thank you for using Azure SDK for .NET.
For the question you mentioned:
Have you try to use `TxtRecord.Value.Add(string)` to set the value?
