### ISSUE TITLE
[BUG] Azure Cognitive Service for Language & Language Studio fails to correctly update during ARM deployment

### ISSUE THREAD

**Issue by rliberoff** [Azure/azure-sdk-for-net#28829]
### Library name and version

Azure.AI.Language.Conversations 1.0.0-beta.3

### Describe the bug

Hello,

We are provisioning the Azure Cognitive Service for Language using ARM templates. Everything works as expected the first time the service is provisioned.

Then We create some knowledge bases (Custom Question Answering projects) and connect them using an Orquestrator. Everything works as expected.

However, if We re-execute the ARM deployment, even when the process is successful without any errors, the Custom Question Answering projects(the knowledge bases) disappears from the Language Studio. 

We notice that the knowledge bases still exists correctly in the associated Azure Cognitive Search, but for some reason the Language Studio is not reading them.

BTW, the Orquestrator and other resources like Custom Language Understanding projects are not affected; only the Custom Question Answering projects.

### Expected behavior

Multiple executions of the ARM templates to deploy the Azure Cognitive Service for Language should no affect the projects in the Language Studio, in this particular case, the Custom Question Answering projects.

### Actual behavior

After a second ARM deployment, any Custom Question Answering project disappears and becomes unavailable.

### Reproduction Steps

1. Deploy an Azure Cognitive Service for Language using its default and standard ARM template that can be obtained when provisioning the resource.
2. Create a few Custom Question Answering projects in Language Studio. 
3. Create an Orquestrator and connect it to the Custom Question Answering projects from the previous step.
4. Deploy each project.
5. Re-deploy the Azure Cognitive Service for Language using the very same ARM template used in the first step.
6. Access the Language Studio. The Custom Question Answering projects are missing.

### Environment

Windows 10
Visual Studio 2022 - 17.1.6
.NET 6

**Comment by rliberoff** [comment]
BTW, I had also asked this same issue here: https://docs.microsoft.com/en-us/answers/questions/842231/knowledge-bases-are-missing-from-language-studio-c.html

There hasn't been any answer yet 😓

This is becoming an issue on out CI/CD pipelines.

Please advise!

Thank you.

**Comment by CrespoColeto** [comment]
I've been having the same problem for days, and I thought I had something wrong, but from what I see and what you say, it seems to be a bug.

I hope they give an answer or fix it soon.

**Comment by Sergio-QA** [comment]
I have been experiencing the same. Would it be to have it fixed.
