### ISSUE TITLE
Documentation unclear: what happens when there is no item in the queue

### ISSUE THREAD

**Issue by knightmeister** [Azure/azure-sdk-for-net#28839]
The documentation for the Peek family of methods is unclear.

What happens when there is nothing in the queue? I assume `null` is returned, but this should be formally documented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7941efb-f3cd-99a5-cc9b-ee44365ca516
* Version Independent ID: 18dc449f-76e7-cb7a-5a09-694c96e24cc1
* Content: [QueueClient.PeekMessageAsync(CancellationToken) Method (Azure.Storage.Queues) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient.peekmessageasync?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Queues/QueueClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Queues/QueueClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@knightmeister Thanks for reaching out to us and sharing this feedback. We are looking into this issue. We will provide an update once we have more details.

**Comment by navba-MSFT** [comment]
@knightmeister Thanks again for this feedback. The above PR has bene filed to address this. The PR is currently under review. In the meantime if you have any questions, please feel free to ask.
