### ISSUE TITLE
[BUG] EnableCustomHttpsAsync throws an serialization exception

### ISSUE THREAD

**Issue by joostmeijles** [Azure/azure-sdk-for-net#28830]
### Library name and version

Azure.ResourceManager.Cdn 1.0.0-beta5

### Describe the bug

Its not possible to enable custom https using:
```
await cdnCustomDomain.EnableCustomHttpsAsync(new CustomDomainHttpsContent(ProtocolType.ServerNameIndication)
        {
            MinimumTlsVersion = MinimumTlsVersion.Tls12
        });
```

This results in the following exception:
```
Exception of type 'Newtonsoft.Json.JsonSerializationException' was thrown. The parameters field is required.
Status: 400 (Bad Request)
ErrorCode: InvalidResource

Content:
{"error":{"code":"InvalidResource","message":"Exception of type 'Newtonsoft.Json.JsonSerializationException' was thrown. The parameters field is required.","target":null}}
```

This is likely due to the fact that CertificateSource is null (and cannot be set because its an internal scoped property). The serialization code throws the error:
```
void IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("certificateSource");
            writer.WriteStringValue(CertificateSource.ToString()); // <-- CertificateSource is null
            ...
        }
```

### Expected behavior

Enable custom https without errors.

### Actual behavior

Unable to enable custom https.

### Reproduction Steps

Add a custom domain to a cdn profile endpoint and execute the following code:

```
await cdnCustomDomain.EnableCustomHttpsAsync(new CustomDomainHttpsContent(ProtocolType.ServerNameIndication)
        {
            MinimumTlsVersion = MinimumTlsVersion.Tls12
        });
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @joostmeijles, actually `CustomDomainHttpsContent` is a base class and `CdnManagedHttpsContent` and `UserManagedHttpsContent` are the derived classes. `CertificateSource` is a discriminator to distinguish between these derived classes. When you call the API, please pass the derived class to make the request work as expected.

Here is the sample code:
```csharp
CdnManagedHttpsOptions customDomainHttpsOptions = new CdnManagedHttpsOptions(ProtocolType.ServerNameIndication, new CdnCertificateSourceParameters(CdnCertificateSourceParametersTypeName.CdnCertificateSourceParameters, CertificateType.Dedicated));
CdnCustomDomainResource enabledCdnCustomDomain = await cdnCustomDomain.EnableCustomHttpsAsync(customDomainHttpsOptions);
```

Sorry again for that the SDK didn't explain this usage clearly, we already have a plan to update the parameter description to improve the experience.

**Comment by joostmeijles** [comment]
Thanks, that works!
