### ISSUE TITLE
[Functions] Add ability to specify that System.Text.Json should be used for POCO bindings

### ISSUE THREAD

**Issue by VanessaRussell** [Azure/azure-sdk-for-net#28838]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.3.0

### Query/Question

How do I configure the ServiceBus bindings to use System.Text.Json rather than the unexpected default of Newtonsoft.Json?

I created a POCO message class using `JsonElement` like this:
``` csharp
using System.Text.Json;

namespace MyNamespace;

public sealed record GenericSendRealTimeEventPayload
{
    public JsonElement? EventData { get; init; }
    public string? EventTarget { get; init; }
    public EventTargetTypes? EventTargetType { get; init; }
}
```
and then spent the next couple hours tracking down why the Model Binding was not populating the JsonElement property like the [System.Text.Json docs state](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-handle-overflow?pivots=dotnet-6-0#deserialize-into-jsonelement-or-jsonnode).  This was especially confusing as my unit test:
``` csharp
    [Fact]
    public void DeserializesAsExpected()
    {
        string jsonEventData = JsonSerializer.Serialize(ModelMocks.ValidEventData);
        GenericSendRealTimeEventPayload expectedPayload = new GenericSendRealTimeEventPayload
        {
            EventData = JsonDocument.Parse(jsonEventData).RootElement,
            EventTarget = ModelMocks.ValidPayload.EventTarget,
            EventTargetType = ModelMocks.ValidPayload.EventTargetType,
        };
        string jsonPayload = JsonSerializer.Serialize(ModelMocks.ValidPayload);

        GenericSendRealTimeEventPayload? actualPayload = JsonSerializer.Deserialize<GenericSendRealTimeEventPayload>(jsonPayload);

        Assert.Equal(expectedPayload.ToString(), actualPayload?.ToString());
    }
```
is passing as expected.

I finally discovered this repo and that the default json serializer is still unexpectedly Newtonsoft.Json.  Unfortunately, I can't seem to find any documentation mentioning how to change it (or even what the default is).

Could you please help me understand what I need to do to enable System.Text.Json serializer for my SreviceBus bindings?

### Environment

    <PropertyGroup>
        <AzureFunctionsVersion>v4</AzureFunctionsVersion>
        <PublishReadyToRun>true</PublishReadyToRun>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    </PropertyGroup>

Developing locally on Win 10 using Visual Studio 2022 (17.2.0) and .NET 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @VanessaRussell,
Currently it is not possible to configure a different serialization library to be used for binding to POCOs. You can customize the NewtonSoft.Json settings by modifying the [JsonSerializerSettings](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.servicebus.servicebusoptions.jsonserializersettings?view=azure-dotnet#microsoft-azure-webjobs-servicebus-servicebusoptions-jsonserializersettings) property on the ServiceBusOptions. 

The simplest way to use System.Text.Json would be to just bind to the ServiceBusReceivedMessage, and then deserialize to your POCO by interacting with the BinaryData Body property, e.g.:
```c#
var employee = message.Data.ToObjectFromJson<Employee>();
```

**Comment by VanessaRussell** [comment]
mmm.... ic.  Is there an eta on when System.Text.Json support for binding to/from POCO will be available?  This caught me off guard as System.Text.Json has been the default json serializer for the last three ASP.NET releases (.NET 3.1, .NET 5, .NET 6).

Thanks for the example on how to manually deserialize into the POCO from the ServiceBusReceivedMessage.  Could you also supply an example on how to manually serialize the POCO using System.Text.Json before sending it to the Output Binding?

**Comment by JoshLove-msft** [comment]
> /unresolve
> 
> mmm.... ic. Is there an eta on when System.Text.Json support for binding to/from POCO will be available? This caught me off guard as System.Text.Json has been the default json serializer for the last three ASP.NET releases (.NET 3.1, .NET 5, .NET 6).
> 
> Thanks for the example on how to manually deserialize into the POCO from the ServiceBusReceivedMessage. Could you also supply an example on how to manually serialize the POCO using System.Text.Json before sending it to the Output Binding?

I'm not aware of any current plans to add built-in System.Text.Json support for the bindings - cc @mattchenderson

For the output binding, you could just use the constructor of BinaryData that takes an object:
```c#
message = new ServiceBusMessage(new BinaryData(employee));
```

**Comment by VanessaRussell** [comment]
> I'm not aware of any current plans to add built-in System.Text.Json support for the bindings - cc @mattchenderson

That's quite surprising and a bit disappointing given that System.Text.Json is the default ASP.NET serializer.

> For the output binding, you could just use the constructor of BinaryData that takes an object:
> 
> ```cs
> message = new ServiceBusMessage(new BinaryData(employee));
> ```
In this example, is the `employee` already serialized to json or are you saying that `BinaryData` uses System.Text.Json internally to do the json serialization?

**Comment by JoshLove-msft** [comment]
> In this example, is the `employee` already serialized to json or are you saying that `BinaryData` uses System.Text.Json internally to do the json serialization?

`employee` would be an instance of a POCO type Employee. BinaryData uses System.Text.Json internally.

**Comment by VanessaRussell** [comment]
> `employee` would be an instance of a POCO type Employee. BinaryData uses System.Text.Json internally.

Thanks for confirming.  I just happened to stumble upon the source code for `BinaryData` within the System.Memory.Data package as well.  Tbh, it's another reason why the default in the bindings should be System.Text.Json and not Newtonsoft.

**Comment by JoshLove-msft** [comment]
> > `employee` would be an instance of a POCO type Employee. BinaryData uses System.Text.Json internally.
> 
> Thanks for confirming. I just happened to stumble upon the source code for `BinaryData` within the System.Memory.Data package as well. Tbh, it's another reason why the default in the bindings should be System.Text.Json and not Newtonsoft.

The decision was made to leave Newtonsoft as the default for backwards compatibility with prior versions of the extensions. I think we can take the idea of providing configurability here as a feature request for the extensions.

**Comment by jsquire** [comment]
After further discussion, this is not a feature that we'll be moving forward with at present.  If, in the future, the Functions platform moves its standard away from Newtonsoft, the Service Bus extensions will follow.   Mitigation is to bind to `ServiceBusReceivedMessage` and perform deserialization of the payload directly.   Closing this out.
