### ISSUE TITLE
Sample: Working with Cloud Events

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#28835]
# Summary

With `CloudEvent` being added as a common abstraction in `Azure.Core`, it provides a neutral type for working with event data across the Azure messaging services.  It would be helpful to have a set of samples fore core Event Hubs scenarios that demonstrate translating between `CloudEvent` and `EventData`.

# Scope of Work

- A sample for `Azure.Messaging.EventHubs` focused on interacting with `CloudEvent` and Event Hubs should be written, covering:
  - Translating between `CloudEvent` and `EventData`, including where commonly used data/attributes map between them
  - Using `CloudEvent` with the `EventHubProducerClient` and `EventHubBufferedProducerClient` for publishing data
  - Using `CloudEvent` with the `EventHubConsumerClient` and `EventProcessorClient` for consuming data

- A sample for `Azure.Messaging.EventHubs.Processor` focused on interacting with `CloudEvent` and Event Hubs should be written, covering:
  - Using `CloudEvent` with `EventProcessorClient` for consuming data

# Out of Scope

- Demonstrating interactions between Event Hubs and other messaging libraries using `CloudEvent` as an intermediate format; this would cross library boundaries and should be considered as a stand-alone sample in the [common samples](https://github.com/Azure/azure-sdk-for-net/tree/main/samples) area of the repository.

- Demonstrating use in an Azure Functions context; that should be considered as a stand-alone effort for the extensions package.

# Success Criteria

- The topics detailed by the scope have been documented in the samples.

- All code in the samples are snippet-driven, with the code being built and smoke tested as part of nightly runs.

- The existing samples have been reviewed for accuracy and are in a good state for release of the Event Hubs client libraries.

- The tests necessary for sample validation have been created or adjusted and pass reliably.

- The existing test suite continues to produce deterministic results and pass reliably.

# References and Resources

- [Cloud Event source](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Azure.Core/src/Messaging)

**Comment by ruvyas** [comment]
Hello, I would like to work on this. Any guidance is appreciated.

**Comment by jsquire** [comment]
Hi @ruvyas.   It's a pleasure to make your acquaintance and thank you for your interest in helping to improve the Azure SDK experience.   We'd love to have you pick this issue up, and I'm happy to serve as your contact for doing so.    

A good place to get started would be to look through our [contributing guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/CONTRIBUTING.md) for Event Hubs; that will help you get a development environment set up and links out to other important sources, such as the main repository contributing guide.    Since our samples are structured as markdown files with code snippets injected from tests, the [Updating Sample Snippets](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#updating-sample-snippets) section would also be helpful.

For Event Hubs, the samples themselves can be found in the [samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Azure.Messaging.EventHubs/samples) directory, and code is injected from snippets created in the [tests/Snippets](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Azure.Messaging.EventHubs/tests/Snippets) area of the project.   We'll probably want to look at this as a new sample rather than trying to integrate the content into an existing one.   Please feel free to create a new file for the markdown and tests.   Otherwise, just following the patterns from the other samples so that things are consistent in presentation would by my biggest thought.

As you're looking through things, please feel free to ping me with any questions or blockers for working in the repository, and as a reviewer for PRs.

**Comment by ruvyas** [comment]
@jsquire Thank you for the above information. I have few clarifying questions. 

> Using CloudEvent with the EventHubProducerClient and EventHubBufferedProducerClient for publishing data

I don't see any overloads that accepts `CloudEvent` for publishing events. Does this mean we have to create a sample `CloudEvent` json, convert/map it to `EventData` then publish the event?

> Using CloudEvent with the EventHubConsumerClient and EventProcessorClient for consuming data

Similarly, for Consumer we read `EventData`  and convert/map it to `CloudEvent`?

**Comment by jsquire** [comment]
> I don't see any overloads that accepts CloudEvent for publishing events. Does this mean we have to create a sample CloudEvent json, convert/map it to EventData then publish the event?
> Similarly, for Consumer we read EventData and convert/map it to CloudEvent?

Yes.  I'd start with `Azure.Messaging.CloudEvent` from `Azure.Core` - whether you pull that in from JSON or create it directly - and map that to/from `EventData`.

**Comment by jsquire** [comment]
Revisiting - this is not a scenario for which we've received much customer interest and doesn't fit the current direction of the Event Hubs product.  Closing this out.
