### ISSUE TITLE
Samples:  Add a Table of Contents

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#28841]
# Summary

The Event Hubs samples are organized into markdown files by high-level scenario.  This organization helps reduce the number of files, but increases the amount of content and density in each file.  It would be helpful if there was a table of contents available for each sample to make finding information and navigation easier.

# Scope of Work

- Add a table of contents to each markdown sample found in the [Event Hubs samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Azure.Messaging.EventHubs/samples) area.

- Add a table of contents for each markdown sample found in the [Event Hubs Processor samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples) area.

- Add a simplified listing of topics available in the Event Hubs core samples in the [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/README.md).

- Add a simplified listing of topics available in the Event Hubs processor samples in the [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/README.md).

# Success Criteria

- The content outlined in the scope of work has been added to the samples.

- The existing test suite continues to produce deterministic results and pass reliably.

**Comment by chadvidovcich** [comment]
Hello! I'm a new developer looking to branch out to more open-source. Can I take on this issue? Do you have any special guidelines for this project?

**Comment by jsquire** [comment]
Hi @chadvidovcich.   It's a pleasure to make your acquaintance and thank you for your interest in helping to improve the Azure SDK experience.   We'd love to have you pick this issue up, and I'm happy to serve as your contact for doing so.    

I don't think there's much by way of special guidelines; our goal is just to try and improve discoverability and navigation for developers looking at our samples.   The organization that we've chosen for Event Hubs is helpful to find the general area that you're interested in but has some challenges in finding specific topics in that area.   I don't have a strong vision for what things should look like, but our [Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md) may be helpful as an example of prior art.

As you're looking through things, please feel free to ping me with any questions or blockers for working in the repository, and as a reviewer for PRs.   I'm happy to work in the way that best suits your style, whether iteratively or as a single unit.

**Comment by chadvidovcich** [comment]
Hi @jsquire and thank you for the warm welcome. I've looked over the example migration guide and have a clear path forward on the work required. Glad to be able to help. 

I have 2 (hopefully) easy questions for you; 

    1) How many commits would you like to see on the PR? Should I submit all changes on 1 commit or take a more atomic approach? 

    2) Once complete, should I PR my forked branch to the Main branch here? Or is there another development branch?

Cheers!

**Comment by Soheilafsha** [comment]
> سلام! من یک توسعه دهنده جدید هستم که به دنبال انشعاب به منبع بازتر هستم. آیا می توانم این موضوع را قبول کنم؟ آیا دستورالعمل خاصی برای این پروژه دارید؟

صد درصد وجود دارد، از دستورالعملهای موجود پییروی کن و به دانش خود بیفزایید، قطعا به یادگیری و درک بیشتر به شما کمک خواهد کرد، بستگی داره اشتیاق به یادگیری شما چقدر باشد.😃

**Comment by jsquire** [comment]
@chadvidovcich.  Awesome!   To answer your questions:

> 1) How many commits would you like to see on the PR? Should I submit all changes on 1 commit or take a more atomic approach? 

I leave that to your discretion, I'm good either way.  I typically walk file-by-file when reviewing while looking at all commits, so the general structure isn't important.   It can be helpful to push changes as a new commit after the initial PR, just to make it easier to identify new changes.

> 2) Once complete, should I PR my forked branch to the Main branch here? Or is there another development branch?

Opening a PR from your forked branch to `main` is the way to go!  Generally, all of the work in this repo is done against `main`.
