### ISSUE TITLE
[FEATURE REQ] StorageMover, target public preview SDK release 7/5

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#28854]
### Library name

RP Name: Microsoft.StorageMover, 
SDK Name: in discussion with SDK team

##### Feature doc:
https://microsoft.sharepoint.com/:w:/r/teams/AzureStorageMigration/_layouts/15/Doc.aspx?sourcedoc=%7B34B68371-4359-4821-A644-2234678AE055%7D&file=Azure%20Data%20Mover%20Resource%20Provider%20Design%20and%20Use%20Cases.docx&action=default&mobileredirect=true&share=IQFxg7Y0WUMhSKZEIjRniuBVAQENHVNHc6Uznb-8w1epIEM

##### Private swagger 
PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/5203

Still in private swagger repo, Pending for public swagger.
Per agreement with feature team, swagger will be merged to public repo at least 2-3 weeks before PSH/CLI release for public preview.

##### release schedule
Currently target public preview on 7/8. PSH/CLI release can target 7/5.

**Comment by ArthurMa1978** [comment]
Spec not ready, postpone it

**Comment by ArthurMa1978** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/31780 new item to track this request
