### ISSUE TITLE
[BUG] [Stroage mgmt Track2] New "AccountImmutabilityPolicyProperties" with null ImmutabilityPolicyState  get exception

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#28853]
### Library name and version

Azure.ResourceManager.Storage 1.0.0-beta.9

### Describe the bug

New "AccountImmutabilityPolicyProperties" , when ImmutabilityPeriod has value, while ImmutabilityPolicyState is null, different code will have different behaviors. Explicitly setting ImmutabilityPolicyState to null will result in errors

The following code will result in error:
 
![image](https://user-images.githubusercontent.com/6926193/169017762-4915446c-f1ee-4f0d-acb0-17cfc4d1ba54.png)

Error message: 
 
![image](https://user-images.githubusercontent.com/6926193/169017784-8583b5d7-146e-4f32-8874-1154049050fc.png)

While the following code works just fine: 
 
![image](https://user-images.githubusercontent.com/6926193/169017809-106f2639-81e8-48e2-b862-a6f9cdf0af8d.png)

### Expected behavior

All works fine.

### Actual behavior

Error message: 
 
![image](https://user-images.githubusercontent.com/6926193/169017784-8583b5d7-146e-4f32-8874-1154049050fc.png)

### Reproduction Steps

New "AccountImmutabilityPolicyProperties" , when ImmutabilityPeriod has value, while ImmutabilityPolicyState is null, different code will have different behaviors. Explicitly setting ImmutabilityPolicyState to null will result in errors

The following code will result in error:
 
![image](https://user-images.githubusercontent.com/6926193/169017762-4915446c-f1ee-4f0d-acb0-17cfc4d1ba54.png)

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  3.1.419 [C:\Program Files\dotnet\sdk]
  6.0.105 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by ArcturusZhang** [comment]
The above proposal should be a breaking change and we might not be able to adopt that.
Considering that, we could make the constructor of `AccountImmutabilityPolicyState` to accept null value and change the serializer and deserializer correspondingly to make sure a `AccountImmutabilityPolicyState` with `_value=null` works exactly the same as a `(AccountImmutabilityPolicyState?)null`
