### ISSUE TITLE
EventHubTrigger failed to Start - Microsoft.Azure.WebJobs.Extensions.EventHubs - 5.1.0

### ISSUE THREAD

**Issue by Vivek-Negi-GL** [Azure/azure-sdk-for-net#28850]
![image](https://user-images.githubusercontent.com/79299663/168998416-9aa5674b-53d9-467d-ae70-b5b623efcd99.png)

EventHubTrigger failed to Start due to the following error message in the screenshot.

 **_The 'PrintEventHubTrigger' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'PrintEventHubTrigger'. Microsoft.Azure.WebJobs.Host: Multiple properties named 'ContentType' found in type 'EventData'._**

**Microsoft.Azure.WebJobs.Extensions.EventHubs  - 5.1.0**

**Comment by Vivek-Negi-GL** [comment]
![image](https://user-images.githubusercontent.com/79299663/168999351-65d33538-057a-4586-817f-afd4d2a16802.png)

**Comment by jsquire** [comment]
Hi @Vivek-Negi-GL.   Thank you for reaching out and we regret that you're experiencing difficulties.    This is the result of a dependency in the Functions tooling which was updated in the Azure hosts but has not yet updated in the Functions Core Tools.   The error will occur when running with the function tools locally if your application directly references v5.7.0 of the `Azure.Messaging.EventHubs` package.  Remediation would be to move to v5.6.2 until the function tools package v4.1.3.17473 is released.   

More information can be found in [#2830](https://github.com/Azure/azure-webjobs-sdk/issues/2830#issuecomment-1125326012) in the WebJobs repository.  I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by Vivek-Negi-GL** [comment]
This issue is fixed with new version of azure function core tools v4.0.4544

**Comment by aardrasystems** [comment]
Hi How to update the core tools
My PC is running 

Core Tools Version:       4.0.3928

I am getting the same error
