### ISSUE TITLE
EventHubTrigger failed to Start 

### ISSUE THREAD

**Issue by Vivek-Negi-GL** [Azure/azure-sdk-for-net#28851]
[EventHubTrigger failed to Start due to the following error message in the screenshot.

The 'PrintEventHubTrigger' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'PrintEventHubTrigger'. Microsoft.Azure.WebJobs.Host: Multiple properties named 'ContentType' found in type 'EventData'.

Microsoft.Azure.WebJobs.Extensions.EventHubs - 5.1.0]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c0920fd-950b-1473-c8de-10204dca2fbd
* Version Independent ID: e66c4847-14aa-5f33-db91-92cb5b7895aa
* Content: [EventData.ContentType Property (Azure.Messaging.EventHubs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventdata.contenttype?view=azure-dotnet#azure-messaging-eventhubs-eventdata-contenttype)
* Content Source: [xml/Azure.Messaging.EventHubs/EventData.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.EventHubs/EventData.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @Vivek-Negi-GL.   Thank you for reaching out and we regret that you're experiencing difficulties.    This is the result of a dependency in the Functions tooling which was updated in the Azure hosts but has not yet updated in the Functions Core Tools.   The error will occur when running with the function tools locally if your application directly references v5.7.0 of the `Azure.Messaging.EventHubs` package.  Remediation would be to move to v5.6.2 until the function tools package v4.1.3.17473 is released.   

More information can be found in [#2830](https://github.com/Azure/azure-webjobs-sdk/issues/2830#issuecomment-1125326012) in the WebJobs repository.  I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
