### ISSUE TITLE
[BUG] Model Id Type in the SDK does not match Studio

### ISSUE THREAD

**Issue by Pepsi1x1** [Azure/azure-sdk-for-net#28858]
### Library name and version

Azure.AI.FormRecognizer 3.1.1

### Describe the bug

Hi,

In Form Recognizer .NET SDK the method StartRecognizeCustomFormsAsync expects a Guid as the model id for Custom Models. When creating custom models in the Form Recognizer Studio it there is no such restriction on the model id and these can be named as any string of text, for example “completed_model_2”.

![image](https://user-images.githubusercontent.com/293292/169045425-37eca5d9-fdfd-44a3-a862-75ee59d45038.png)

When passing this to the SDK:

![image](https://user-images.githubusercontent.com/293292/169047019-87ae4c21-257c-41cc-bdcf-e90381d3e7a6.png)
![image](https://user-images.githubusercontent.com/293292/169047160-49d4cc39-2617-4268-9cb7-bd622a05301a.png)

The following error is thrown 

FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

It’s possible to use the REST API directly and pass in these model ids, however it would be preferable to consume the SDK rather than re-implementing the functionality built by Microsoft and this is a blocker for adoption for us also I’m sure will be a source of confusion for other customers.

I’m seeing the same behaviour in both the current stable 3.1.1 and the latest preview 4.0.0-beta.3 of the .NET SDK.

### Expected behavior

A string modelid that is not restricted to a Guid is accepted

### Actual behavior

An ArgumentException is thrown

### Reproduction Steps

```
RecognizeCustomFormsOptions recognizeContentOptions = new RecognizeCustomFormsOptions { ContentType = FormContentType.Png};
AzureKeyCredential credential = new AzureKeyCredential("YOUR KEY");
FormRecognizerClient client = new FormRecognizerClient(new Uri("YOUR ENDPOINT"), credential);
Azure.Response<RecognizedFormCollection> formPages = await client
                    .StartRecognizeCustomFormsAsync("completed-model-2", document.Content, recognizeContentOptions).WaitForCompletionAsync().ConfigureAwait(false);
```

### Environment

Windows 10 .NET 6

**Comment by Pepsi1x1** [comment]
Potentially related, I'm also seeing no models returned from the training client when calling GetCustomModels or GetCustomModelsAsync

**Comment by maririos** [comment]
Hi @Pepsi1x1 . From the images you are sharing from the Form Recognizer Studio, it looks like you are targeting the `2022-01-30` API version. 
The `Azure.AI.FormRecognizer 3.1.1` doesn't target that API version. See here https://docs.microsoft.com/en-us/dotnet/api/overview/azure/ai.formrecognizer-readme?view=azure-dotnet#getting-started or here https://docs.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.formrecognizerclientoptions.serviceversion?view=azure-dotnet.


If you would like to use the SDK against the `2022-01-30` API version, I suggest you use our latest beta release [Azure.AI.FormRecognizer 4.0.0-beta.3](https://www.nuget.org/packages/Azure.AI.FormRecognizer/4.0.0-beta.3) and follow the documentation [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/formrecognizer/Azure.AI.FormRecognizer#getting-started) as there were major changes in between versions.

**Comment by Pepsi1x1** [comment]
Thanks @maririos that is indeed what I needed and the linked documentation is clear.

**Comment by maririos** [comment]
Let us know if you have feedback when using this beta release. :)

**Comment by pluservice** [comment]
Error is still  present 
System.ArgumentException: 'The modelId must be a valid GUID. Arg_ParamName_Name'

Form Recognizer Studio generated code (C#) does not work

Validation still check fora a valid GUID 
https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.FormRecognizer_4.0.0-beta.4/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ClientCommon.cs

**Comment by kinelski** [comment]
> Error is still present System.ArgumentException: 'The modelId must be a valid GUID. Arg_ParamName_Name'
> 
> Form Recognizer Studio generated code (C#) does not work
> 
> Validation still check fora a valid GUID see code Line 23 https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.FormRecognizer_4.0.0-beta.4/sdk/formrecognizer/Azure.AI.FormRecognizer/src/ClientCommon.cs

The validation code you linked is only called if you're using the old `FormRecognizerClient`, which targets old service versions that only support GUID model IDs. In order to use the newest service version, the `DocumentAnalysisClient` must be used. Please check our documentation [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/formrecognizer/Azure.AI.FormRecognizer#getting-started) for more information.

If you still think there's a bug in the SDK, please feel free to open a new issue.
