### ISSUE TITLE
PurviewScanClient.CreateOrUpdateAsync() throws exception instead of returning valid Response when collection is not found.

### ISSUE THREAD

**Issue by martijnvanschie** [Azure/azure-sdk-for-net#28855]
When creating a new Purview scan using Postman with a collection referenceName name that does not exist i get a 403 Forbidden containing the following body. The body represents the Schema for Response Error as described on the documentation page.

```json
{
    "error": {
        "code": "Unauthorized",
        "message": "Not authorized to access account"
    }
}
```

When performing the same call from the Azure SDK i get a `RequestFailedException()` with `Status` 403 (same status) but there is no way to access the content of the response because the exception object has no reference to the `body` or `content` of the response. This masks the actual underlying error which can be beneficial for logging and analysis.

The exceptions `message` property also does not contain the full error response message from the Postman example as show below.

```
Azure.RequestFailedException : Service request failed.
Status: 403 (Forbidden)

Headers:
Date: Wed, 18 May 2022 09:52:31 GMT
Transfer-Encoding: chunked
Strict-Transport-Security: REDACTED
x-ms-correlation-request-id: REDACTED


Stack Trace: 
HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, ClientDiagnostics clientDiagnostics, RequestOptions requestOptions, CancellationToken cancellationToken)
PurviewScanClient.CreateOrUpdateAsync(RequestContent content, RequestOptions options)
ScansClient.CreateOrUpdateScanAsync(PurviewScan scan) line 78
ScansClientTests.Should_Return_Null_On_None_Valid_Collection() line 38
--- End of stack trace from previous location ---
```

Also, the documentation does not state this exception as an expected response. The documentation does state that a `Task<Response>` will be returned. 

Another issue is that the error message is misleading in general making the user (like me) search for access control issues instead of a missing collection name. 403 feels like a higher-level error on transport level.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 25bce72f-c954-1e41-765f-c4313caa1028
* Version Independent ID: 7b31d8c8-6300-ebdc-df9a-1cc1ce9b527d
* Content: [PurviewScanClient.CreateOrUpdateAsync(RequestContent, RequestOptions) Method (Azure.Analytics.Purview.Scanning) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdateasync?view=azure-dotnet-preview)
* Content Source: [xml/Azure.Analytics.Purview.Scanning/PurviewScanClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Analytics.Purview.Scanning/PurviewScanClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@martijnvanschie Thank you for reaching out, we are looking into it.

**Comment by navba-MSFT** [comment]
@martijnvanschie We need to assign the service principal Purview Data Curator role at collection level. For more information, please refer to this doc: [Create and manage collections in Microsoft Purview](https://docs.microsoft.com/en-us/azure/purview/how-to-create-and-manage-collections)

You will have to assign the following roles to the service principal to access various data planes in Microsoft Purview.

- Data Curator role to access Catalog Data plane.
- Data Source Administrator role to access Scanning Data plane.
- Collection Admin role to access Account Data Plane and Metadata policy Data Plane.

NOTE: Please note that only members of the Collection Admin role can assign data plane roles in Microsoft Purview.

To explore about the Access control in the Microsoft Purview Data Map please refer to this doc: [Microsoft Purview - Who should be assigned to what role?](https://docs.microsoft.com/en-us/azure/purview/catalog-permissions#who-should-be-assigned-to-what-role)

![image](https://user-images.githubusercontent.com/57353862/178895783-743d14e2-86dc-41ff-a3be-5bef2f700e7e.png)


![image](https://user-images.githubusercontent.com/57353862/178895831-f17362be-7438-4e39-bac6-96240a008ac2.png)


![image](https://user-images.githubusercontent.com/57353862/178895902-5b6e65b9-4c00-4c77-bfdd-e3c39f6382ba.png)

Below is an important note from product team when you use existing service principals for calling Azure Purview REST APIs

![image](https://user-images.githubusercontent.com/57353862/178895983-36d8be25-c4ee-4fbb-9512-51f73b9b15fb.png)


More Info [here](https://docs.microsoft.com/en-us/answers/questions/861441/index.html). Hope this helps.

**Comment by martijnvanschie** [comment]
Hello @navba-MSFT . Thank you for the response. 

To be honest, i have already gone through all the authorization options and my account has full control on the Purview test account. Your answer actually indicates that the error response is indeed unclear and does not represent the error that is actually going on.

To summarize the issue:

_The response code 403, in my opinion, is not applicable. It has nothing to do with authorization. The problem is that I'm adding a scan to a non-existent collection. Adding a scan to an existing collection works fine with the same account._

Also, the fact that I receive a 403 and that the dotnet SDK does not give access to the response messsage (or stream object) makes it hard to debug the error.

Any thoughts on this.

Regards,
Martijn

**Comment by navba-MSFT** [comment]
@martijnvanschie Thanks for getting back. I am adding Service team to look into this issue and provide an update.
