### ISSUE TITLE
EventGridManagementClient does not inherit credential's properties for National Clouds

### ISSUE THREAD

**Issue by jcbrooks92** [Azure/azure-sdk-for-net#28873]
EventGridManagementClient does not inherit the base URL specified in the credential object when passed. When trying to connect to the Azure government cloud this causes the connection to attempt to query resources in the Azure Commercial cloud instead of cloud specified in the credential object. It seems like management.azure.com is hard coded as the base URL requiring setting it explicitly for the EventGridManagmentClient.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.eventgrid.eventgridmanagementclient?view=azure-dotnet

**Packages**
![image](https://user-images.githubusercontent.com/18233035/169188634-c15bcfb8-8ca2-4ac0-a70a-400f51ba0557.png)

**Screenshots showing properties**

![image](https://user-images.githubusercontent.com/18233035/169188565-a12c506b-9e4d-41c1-a79b-9ed09e24716b.png)

![image](https://user-images.githubusercontent.com/18233035/169188395-f23aeb32-f9a5-491f-b145-9c74cdfe5894.png)

**Sample source code**
`using Microsoft.Azure.Management.EventGrid;
using Microsoft.Azure.Management.EventGrid.Models;
using Microsoft.Azure.Management.ResourceManager.Fluent.Authentication;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace EventgridSubCreation
{
    internal class Program
    {
        static async Task Main(string[] args)
        {

            var principalLogin = new ServicePrincipalLoginInformation();

            principalLogin.ClientId = "xxx";

            principalLogin.ClientSecret = "xxx";

            string tenantId = "xxx";

            string subscriptionId = "xxx";

            string resourceGroupName = "xxxx";

            var credentials = new AzureCredentials(principalLogin, tenantId, Microsoft.Azure.Management.ResourceManager.Fluent.AzureEnvironment.AzureUSGovernment);

            EventGridManagementClient eventGridManagement = new EventGridManagementClient(credentials);

            List<string> eventTypes = new List<string>();

            eventTypes.Add("Microsoft.Storage.BlobCreated");

            eventTypes.Add("Microsoft.Storage.BlobDeleted");

            var endPoint = "xxxxx";

            var deadLetterDestinationResourceId = $"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.Storage/storageAccounts/xxxx";

            string scope = $"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/microsoft.Storage/storageAccounts/xxxx";

            EventSubscription eventSubscription = new EventSubscription()
            {
                Destination = new WebHookEventSubscriptionDestination()
                {
                    EndpointUrl = endPoint

                },
                // The below are all optional settings
                EventDeliverySchema = EventDeliverySchema.EventGridSchema,

                Filter = new EventSubscriptionFilter()
                {
                    // By default, "All" event types are included
                    IsSubjectCaseSensitive = false,
                    SubjectBeginsWith = "",
                    SubjectEndsWith = "",
                    IncludedEventTypes = eventTypes

                },

                DeadLetterDestination = new StorageBlobDeadLetterDestination()
                {
                    ResourceId = deadLetterDestinationResourceId,
                    BlobContainerName = "deadletter-events",
                },

            };
            eventGridManagement.BaseUri.
            EventSubscription createdEventSubscription = await eventGridManagement.EventSubscriptions.CreateOrUpdateAsync(scope, "test", eventSubscription);

            Console.WriteLine("Hello World!");
        }
    }
}
`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @jcbrooks92, we don't extract the URL specified in the credential, in contrast, we provide a public ctor for you to specify the base URL. Please change you ctor to:
```csharp
EventGridManagementClient eventGridManagement = new EventGridManagementClient(new Uri("https://management.usgovcloudapi.net"), credentials);
```
Please let me if this could resolve your issue.

**Comment by Yao725** [comment]
Close this issue as we already have the ctor that you want. Feel free to reopen it if you still have problem.
