### ISSUE TITLE
[Key Vault] Ensure port numbers are preserved in vault URLs parsed from IDs

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-for-net#28887]
See https://github.com/Azure/azure-sdk-for-python/issues/24446 for issue context, and https://github.com/Azure/azure-sdk-for-python/pull/24466 for Python's fix.

**Comment by heaths** [comment]
.NET client suse the `System.Uri` class which already retains the port. The only place we parse a URI is in our identity types, so I added some tests to make sure it works and keeps working.
