### ISSUE TITLE
[QUERY] Mechanism for adapting TokenCredential (newer SDKs) to ServiceTokenCredential (older management SDKs)

### ISSUE THREAD

**Issue by WhitWaldo** [Azure/azure-sdk-for-net#28880]
### Library name and version

Azure.Identity 1.6.0, Microsoft.Azure.Management.ServiceFabricManagedClusters 1.0.0

### Query/Question

The newer management SDKs utilize the TokenCredential from Azure.Identity and this makes it really easy to handle chained auth scenarios like Visual Studio tokens (during debug), managed identities and a fallback to certificate authentication.

The older management SDK style used a ServiceClientCredential which was generally provisioned via Microsoft.Rest.ClientRuntime.Azure.Authentication via ADAL. Given that there are a still a few of the management SDKs out there (such as Microsoft.Azure.Management.ServiceFabricManagedClusters) that use this older mechanism, I'm writing to see if there's some easy way to migrate a provisioned TokenCredential to a valid ServiceClientCredential so I might continue to use a consistent means of authenticating with Azure without having to support a second authentication approach for these other SDKs.

Thank you!

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @WhitWaldo - Could you clarify what you mean by a "provisioned TokenCredential"? Are you looking for guidance for implementing a `ServiceTokenCredential` using an existing implementation of `TokenCredential` or something different?

**Comment by WhitWaldo** [comment]
@christothes It's been a little while since I shared this feedback and I know several new releases of the Azure mgmt packages have since been released, so I'm not entirely sure if the ask is still relevant. I'll poke around my code and see if it's still an outstanding inquiry and get back to you in a few days.
