### ISSUE TITLE
[BUG][STORAGE]Deleted Containers go to immediate delete status even though they are not truly deleted for around 10 minutes

### ISSUE THREAD

**Issue by norton287** [Azure/azure-sdk-for-net#28897]
### Library name and version

Azure Storage SDK .NET V12

### Describe the bug

The container takes around 10 minutes to fully delete yet it's status goes immediately to deleted.  So when you query for deleted Containers and there is a freshly deleted one it will be caught up in this list.  So if you are building a list of Containers to restore there is no way to filter out this newly deleted container and if the user taps it to try to recover it then an exception will occur if the proper amount of time has not gone by.

### Expected behavior

The container should not reflect as being deleted until it is really and truly deleted.

### Actual behavior

It throws a request failed exception if you try to recover it.  Also, this time window is no where in the SDK documentation that I have found.

### Reproduction Steps

Delete a container, do a query for deleted Containers and then from that try to immediately recover it.

### Environment

Android, iOS, UWP WPF

.Net standard 2.1
.Net 6

Visual Studio 2022

**Comment by navba-MSFT** [comment]
@norton287  Thanks for reaching out to us and sharing this feedback. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@norton287 I have a couple of questions on this. 

1. What is the the UsedCapacity (size) of your container ? Do you see the longer time for delete operation on Containers that have _very few blobs_ inside it ?

2. How are you trying to restore the containers ? Are you using the Container Soft delete feature ? 

3. Did you check the behavior from the Azure portal blade if the same issue resurfaces ? or is this behavior seen only from the .NET SDK ?

Sharing some points here: 
The Delete Container operation marks the specified container for deletion. The container and any blobs contained within it are later deleted during garbage collection. 

The deletion will take time depending on the size and number of blobs. Moreover the garbage collection is non-deterministic you cannot forcefully trigger it from your end.

As per [this](https://docs.microsoft.com/en-us/rest/api/storageservices/delete-container) documentation, When a container is deleted, a container with the same name cannot be created for at least 30 seconds; the container may not be available for more than 30 seconds if the service is still processing the request. 

While the container is being deleted, attempts to create a container of the same name will fail with status code 409 (Conflict), with the service returning additional error information indicating that the container is being deleted. All other operations, including operations on any blobs under the container, will fail with status code 404 (Not Found) while the container is being deleted. Hope this helps.

**Comment by norton287** [comment]
It is the same from the portal and the SDK,  If the container were put into a different status other than deleted (which is done IMMEDIATELY) I can filter them out from the list of truly deleted containers  But in both the SDK and the Portal it is taking around 10 minutes for the complete deletion process to occur before they can be restored.  It does not depend on the number of blobs within the container, the container can have 4 or 4000 blobs in it, both take the same amount of time.

If the status cannot be changed then there needs to be a way to filter these just deleted containers out from the really and truly deleted containers so a proper list of restorable containers is shown to the user.

**Comment by navba-MSFT** [comment]
@norton287 Thanks for getting back. I am adding the Service team to take a look into this ask.

@xgithubtriage Could you please look into this ask and provide an update on this ?

**Comment by norton287** [comment]
Have you guys done any tweaking on this?  Because it is down from 10 minutes to about 1 to 2 minutes on restores now.  Just curious.  

Also, the exception message verbiage has changed greatly as far as reporting the time delay in restoring the container.

**Comment by Oliver-Piorun** [comment]
> If the status cannot be changed then there needs to be a way to filter these just deleted containers out from the really and truly deleted containers so a proper list of restorable containers is shown to the user.

Hi! We are encountering the same issues. Would love to have an API where you could simply check if a blob container is still being deleted. We are forced to add artificial delays to our code because there is no way to query this info. Same goes for tables btw.

Thanks ~

**Comment by norton287** [comment]
@Oliver-Piorun Add your voice to the choir as they do not seem in a hurry to fix this issue.
