### ISSUE TITLE
[BUG] Azure Tables SDK documentation is missing information regarding GUID prefix 

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-sdk-for-net#28902]
### Library name and version

Azure.Data.Tables 12.5.0

### Describe the bug

Azure Tables SDK documentation is missing information regarding the GUID prefix and its use in queries. Refer to this tweet for more context:
https://twitter.com/sfeldman/status/1527735127148666880

### Expected behavior

The Azure Tables SDK documentation needs updating to include the relevant information. 

### Actual behavior

The Azure Tables SDK documentation does not include information about the GUID prefix. 

### Reproduction Steps

N/A

### Environment

N/A

**Comment by christothes** [comment]
`TableClient.CreateQueryFilter` will convert a string based query filter to its escaped format. We have a sample to illustrate this. However, we might be able to have this happen automatically if a `FormattableString` is passed to the `Query` method. 

BTW, here's the sample for `TableClient.CreateQueryFilter` https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md#odata-formatted-string

**Comment by SeanFeldman** [comment]
Thank you for the information, @christothes.
I'll have a look into that. My original point still holds though. Documentation should be available. Samples markdown is nice to link to but shouldn't be the primary source of information. Especially for a service/SDK as old as Storage Tables.

**Comment by christothes** [comment]
Yes, this is a tricky one since the syntax is just odata, but most people don't need to deal with it enough to know the gotchas. We tried to make these helpers available to allow developers to avoid the syntax if they wanted, while not getting in the way if they want full control. This is why most people prefer the expression/Linq syntax. 

BTW, if you want the best of both worlds, you can actually use the expression syntax to produce string based odata filters:

```C#
var newFilter = TableClient.CreateQueryFilter<OfficeSupply>(e => e.PartitionKey == "Marker's" && e.RowKey == "A1" );
Console.WriteLine(newFilter); //(PartitionKey eq 'Marker''s') and (RowKey eq 'A1')
```

**Comment by SeanFeldman** [comment]
Expression syntax does look good 👍
It would probably help avoiding mistakes when constructing filters using POCOs but it won't help with the scenarios when an expression option is not possible.

I'd really love to see documentation surfacing outside of this mono repo and be discoverable when searching. BTW, this is an issue not just with Tables SDK.

**Comment by christothes** [comment]
Closing, as I think the docs are sufficient for the majority of use cases, and the service documentation explains the low level protocol syntax https://learn.microsoft.com/en-us/rest/api/storageservices/querying-tables-and-entities#filtering-on-guid-properties
