### ISSUE TITLE
Swapped arguments in code sample

### ISSUE THREAD

**Issue by ChristianHPedersen** [Azure/azure-sdk-for-net#28906]
It looks to me like the id and partition key arguments are swapped in the code sample. It should be id, partitionkey, not vice versa, right?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea1d216a-5adc-ec81-3272-e7c3ce41450c
* Version Independent ID: f12b659b-5a79-73dc-5746-67b6673d5b70
* Content: [Container.DeleteItemAsync&lt;T&gt; Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.deleteitemasync?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.Azure.Cosmos.Container.DeleteItemAsync%2560%25601)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@ChristianHPedersen Thanks for reaching out to us and reporting this issue. We are looking into this issue. We will get back on this thread with an update shortly.

**Comment by navba-MSFT** [comment]
@ChristianHPedersen The above PR has been filed to address this. It is currently under review. In the meantime, if you have any questions, please feel free to ask.
