### ISSUE TITLE
Obsolete SDK - Microsoft.Azure.Management.ResourceManager.Fluent

### ISSUE THREAD

**Issue by prachita-mane** [Azure/azure-sdk-for-net#28919]
[Enter feedback here]
Does not specify if this nuget package is actively being developed or in maintenance mode, and what the replacement is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 54b34178-4c56-b4e0-8775-2bab5f2b1a36
* Version Independent ID: 203f9bf5-e743-871e-8b35-8d037d2bd431
* Content: [AzureCredentialsFactory Constructor (Microsoft.Azure.Management.ResourceManager.Fluent.Authentication) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.authentication.azurecredentialsfactory.-ctor?view=azure-dotnet#microsoft-azure-management-resourcemanager-fluent-authentication-azurecredentialsfactory-ctor)
* Content Source: [xml/Microsoft.Azure.Management.ResourceManager.Fluent.Authentication/AzureCredentialsFactory.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ResourceManager.Fluent.Authentication/AzureCredentialsFactory.xml)
* Service: **azure-resource-manager**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
