### ISSUE TITLE
[Service Bus] Consider adding a ServiceCommunicationException type

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#28910]
Customers have expressed that they intend to handle this class of errors in a specific way. Currently, they would need to fish out the [Reason](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusexception.reason?view=azure-dotnet) property from the `ServiceBusException` and check if the reason is `ServiceCommunicationProblem`.

The suggestion is to introduce a new exception type deriving from `ServiceBusException` that we would throw for this failure reason.

**Comment by jsquire** [comment]
What scenarios do we have for how this would be handled by applications?

**Comment by JoshLove-msft** [comment]
An application may want to take some action if they are experiencing network issues, such as triggering an alarm. This issue can be used to collect additional scenarios/votes to help inform whether this feature request.

**Comment by jsquire** [comment]
As this has been open for nearly a year with no additional discussion nor requests, I don't believe that we have justification to revisit the error hierarchy.   Closing this out.
