### ISSUE TITLE
Automation script does not support to use readme files in azure-rest-api-specs-pr private repo

### ISSUE THREAD

**Issue by chunyu3** [Azure/azure-sdk-for-net#28920]
When use readme.md file in azure-rest-api-specs-pr private repo, it failed to generate the code.
The root cause is when autorest try to load swagger json files according to the readme.md files, it will failed because of permission issue.

e.g.
when require 
https://github.com/Azure/azure-rest-api-specs-pr/blob/c2820d17c45444d200e701e5dbb631f49befe2dc/specification/deviceupdate/data-plane/readme.md
or
https://raw.githubusercontent.com/Azure/azure-rest-api-specs-pr/c2820d17c45444d200e701e5dbb631f49befe2dc/specification/deviceupdate/data-plane/readme.md?token=GHSAT0AAAAAABRWK4DQPCHARZ4K3SU4LOHKYULF5AA

**Comment by chunyu3** [comment]
autorest should keep the token and use it for other files it loads.
There are two approach to authenticate: 
https://github.com/Azure/autorest/blob/7bc20465c3eb2d00aa8e8deef5977600936d3610/docs/user/command-line-interface.md#authentication

**Comment by weshaggard** [comment]
@chunyu3 do we have a strategy for handling this authentication issue yet?

**Comment by pallavit** [comment]
@chunyu3 is this still a valid concern? Is automation script expected to work on the pr repo? Or perhaps you want to expose an argument where the token can be provided - given the authentication issue that @weshaggard mentioned.

**Comment by chunyu3** [comment]
@jsquire This issue still exists.  I think CI pipeline need to find a way to get the authentication token, and the script will accept this token to update readme files to include it.

**Comment by weshaggard** [comment]
We usually don't support generation from the private specs repo because of automation. I suspect there isn't a good way to pull individual files throughout our tool chain. If we really want to seriously support this scenario it will be a larger work item.
