### ISSUE TITLE
[QUERY] PluggableCheckpointStoreEventProcessor constantly close and re-open partitions

### ISSUE THREAD

**Issue by amshalev** [Azure/azure-sdk-for-net#28950]
### Library name and version

Azure.Messaging.EventHubs 5.7.0

### Query/Question

Hi,
I built a custom event processor very similar to the example [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample08_CustomEventProcessor.md#building-the-custom-event-processor)

I see the processor successfully read data and doing checkpoints. However, i see that the partitions are constantly closed and re-opened due to ProcessingStoppedReason.OwnershipLost. 
There is only one machine that runs the processor, and this machine is the only reader of the EH. 
When I switched back to the old Microsoft.Azure.EventHubs client, and read from the same EH - I don't see this behavior.

I'll appreciate your help with understand this issue.

Thanks,
Amit

**Comment by amshalev** [comment]
Thanks for the quick reply!
The SDK logs for the processor helped me to find and fix the issue!
It indeed was due to unhandled exception from the event processing handler.

Thanks a lot for the help and for the detailed documentation of PluggableCheckpointStoreEventProcessor and SDK logs!

**Comment by jsquire** [comment]
My pleasure; I'm glad we were able to get you unblocked.
