### ISSUE TITLE
Live Key Vault samples still sometimes failing with 409s

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#28953]
The `[IgnoreServiceError]` on `KeysTestBase` is working, but the samples like `OctEncryptDecryptSync` neither derive from `KeysTestBase` nor use `[RecordedTest]` since they aren't recorded. Instead, see about incorporating some of what `IgnoreServiceErrorAttribute` and friends do directly into the `SampleFixture` used by Keys samples.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/32792
```

**Comment by pallavit** [comment]
@heaths - what would be the benefit of doing this?

**Comment by pallavit** [comment]
Is the proposal here to have a way to run samples in recorded mode?

**Comment by heaths** [comment]
Samples would have to be rewritten as recorded tests. It's a pre-req to doing this work.

**Comment by pallavit** [comment]
Given our direction do you think we should prioritize this work? If not, do you think we should close the issue?

**Comment by heaths** [comment]
Let's close for now. If anything, I haven't seen this in a while and if it happens again consecutively I'm likely just to fix it one-off like I have for other such issues with pipeline test passes.
