### ISSUE TITLE
DeviceUpdate client constructors take string endpoints instead of Uris

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#28952]
The constructors for `DeploymentsClient` and `DevicesClient` take string `accountEndpoint` parameters.  According to the .NET Azure SDK guidelines, [these parameters should be of type `Uri`](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-primitives-uri).

There is a [forthcoming linter rule](https://github.com/Azure/azure-openapi-validator/issues/303) that will validate that `host` parameters be called `endpoint` and use `format: uri`, but it may take some time to complete.  Please update the Device Update REST API to comply with this guidance in the meantime.

---

Update from [06/16/2022 arch board meeting](https://github.com/Azure/azure-sdk/issues/4256):
- `endpoint` format must be specified as `url` not `uri`.

**Comment by devlie** [comment]
Hi @annelo-msft, unfortunately my colleague David has left Microsoft so we aren't aware of this open issue. Since this is one year old, is it still blocking any release? Thanks.

**Comment by annelo-msft** [comment]
It looks like this was fixed without being closed: https://apiview.dev/Assemblies/Review/d8425ea2f8bd4d9eb58b27062f0b0a50
Thanks!
