### ISSUE TITLE
[BUG] Custom Model - Table Field - Document.Fields.X.ArrayValue is empty on Json serialization

### ISSUE THREAD

**Issue by rutter-foremostgolf** [Azure/azure-sdk-for-net#28972]
### Library name and version

Azure.AI.FormRecognizer 4.0.0-beta.3

### Describe the bug

I've created a custom model with a table property.
These values are displayed in the Result pane of the  form recognizer studio test function.

`"Items": {
						"type": "array",
						"valueArray": [
							{
								"type": "object",
								"valueObject": {
									"Quantity": {
										"type": "string",
										"valueString": "1.00",
										"content": "1.00",
										"boundingRegions": [
											{
												"pageNumber": 1,
												"boundingBox": [
													1.18,
													4.33,
													1.4,
													4.33,
													1.4,
													4.425,
													1.18,
													4.425
												]
											}
										],
										"spans": [
											{
												"offset": 476,
												"length": 4
											}
										]
									},`

But the payload that's been returned from the StartAnalyzeDocumentAsync method doesn't contain these values.

`"Items": {
          "ValueType": 6,
          "Content": null,
          "BoundingRegions": [
          ],
          "Spans": [
          ],
          "Confidence": null
        }`

I'm using System.Text.Json.JsonSerializer.Serialize() with the default configuration.

Other objects, properties and values have bound. So I'm able to get the data from the models string properties.
 
I think I have the same issue as this person: "[[BUG] BoundingBox is empty on Json serialization](https://github.com/Azure/azure-sdk-for-net/issues/28886)" 

### Expected behavior

When using the same document.
I would like the json object displayed in the "form recognizer studio - results pane" to match the serialized payload. 

### Actual behavior

Properties are not being bound.

### Reproduction Steps

Add a custom table field the custom model and train.
Ensure that a test of the model returns results (In Form Recognizer Studio)
Use Nuget package to call API and save serialization of AnalyzeDocumentOperation.Value to file.
Inspect file. 

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
//fyi: @pallavit

**Comment by kinelski** [comment]
Hello @rutter-foremostgolf,

Unfortunately the .NET SDK has not been designed with (de)serialization in mind, specially because we would need to come up with a cross-version compatibility strategy. For now we recommend copying the properties into a custom class and serializing it. For deserialization, you can use our `DocumentAnalysisModelFactory` to instantiate our models since they don't have public constructors.

It's good to hear that's not blocking you, but I agree it can be inconvenient. Serialization support is a request we received a lot in the last months and, if possible, we would like to support it, but it's still not part of our roadmap. I'll keep this issue open for now since the feedback can prove to be useful if we decide to implement this feature in the future.

**Comment by rutter-foremostgolf** [comment]
Hi @kinelski,
Thanks for the information.
I have used the .AsList() and .AsDictionary() of the provided DcoumentField to populate a local custom class and serialized\deserialized it.

**Comment by kinelski** [comment]
@ss-proc Just letting you know we released 4.0.0-beta.5 yesterday. This version exposes the `BoundingPolygon.Length` property we discussed.

I'm closing the issue since the original question seems to be addressed, but feel free to open a new one if you have further questions.
