### ISSUE TITLE
[QUERY] Participate in deserialization in Azure.Data.Tables

### ISSUE THREAD

**Issue by marklio** [Azure/azure-sdk-for-net#28975]
### Library name and version

Azure.Data.Tables 12.6.0-beta.1

### Query/Question

I'm moving a bunch of code from older storage SDKs, and I'm finding alot of missing features in the latest packages. Chief among them is the ability to participate in deserialization. ITableEntity previously had ReadEntity and WriteEntity that allowed you to participate in deserialization. There seems to be a fully-internal implementation in TableTypesBinder, with no obvious way to participate as a consumer of the library. Is that correct? Is there a plan to expose similar functionality? Or a different approach that would let me deserialize to "plain old classes"?

### Environment

.NET 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by marklio** [comment]
It looks like the only option is to use TableEntity as the entity and do my own unpacking of the data. It's unfortunate that I can't leverage the property mapping and conversion logic quite as nicely as before.

**Comment by pallavit** [comment]
@christothes as FYI
