### ISSUE TITLE
[BUG] When a ServiceBus trigger in functions gets a message with a string body an extra double quote gets added at the start and end of the string

### ISSUE THREAD

**Issue by mligtenberg** [Azure/azure-sdk-for-net#28983]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.5.0

### Describe the bug

When a message is placed on a service bus queue. And the message is formatted as a string and not a byte array (this happens when the message is sent via the Azure Portal). The Service bus trigger will place 2 extra double quotes around the string.

For example, via the azure portal send:
```json
{
   "demo": "just see"
}
```

### Expected behavior

The message will be injected via the service bus trigger as as-is without changes
So it would be the same value as the following C# assignment
```Csharp
var jsonString = "{\n  \"demo\":\"just see\"\n}";
```

### Actual behavior

The message will be altered, a double quote will be placed at the start and end of the string
So it would be the same value as the following C# assignment
```Csharp
var jsonString = "\"{\n  \"demo\":\"just see\"\n}\"";
```

### Reproduction Steps

1. Create a barebone servicebus trigger function via the functions cli, botnet cli or visual studio
2. Place a breakpoint on the first line of function execution
3. Connect it to a service bus in azure via local.settings.json
4. via the azure portal send the following

```json
{
   "demo": "just see"
}
```

### Environment

- Functions V3
- Tested on Windows and Mac
- Tested in Visual Studio and Rider

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @mligtenberg,
Can you include your function signature so we can understand how you are binding to the message?

**Comment by mligtenberg** [comment]
Hi Josh,

No problem, here it is:
```csharp
        [FunctionName(nameof(ServiceBusReceiver))]
        public async Task RunAsync([ServiceBusTrigger("%QueueName%", Connection = "ServiceBusConnection")] string sbMessage,
            IDictionary<string, object> userProperties,
            ILogger log)
```

**Comment by mligtenberg** [comment]
Hi Josh,

I'm closing this issue. I cannot reproduce it anymore via the portal.
I am able to reproduce it by sending it via the JS SDK. But I actually see the quotes in the message over there.
So if there is a bug somewhere it is probably in the JS SDK.

Sorry for wasting your time.

**Comment by JoshLove-msft** [comment]
No worries at all. Please let us know if you run into this again and can provide a repro.

**Comment by deyaaeldeen** [comment]
Hi @mligtenberg, if you interested, would you mind sharing a repro for the JS SDK? I am happy to help resolving the JS issue.
