### ISSUE TITLE
Couldn't attach Vnet to IAzureBeta.ContainerGroups.Define.WithNetworkProfileId

### ISSUE THREAD

**Issue by tsowrirajan-deloitte** [Azure/azure-sdk-for-net#28994]
### Library name and version

Microsoft.Azure.Management.Fluent 1.38.0

### Query/Question

I have an existing Vnet and a subnet under that. While creating an ACI programmatically using .Net SDK, While using the code below, I could not successfully attach the Vnet to the ACI that was created. 

The container instance is created successfully and the container also runs and able to make a connection to a Http Url. 

However, my ultimate goal is to be able to create and run this ACI under this specific VNet & Subnet which is not happening.

`IContainerGroup containerGroup = await azure.ContainerGroups.Define(aciName)
	.WithRegion(region)
	.WithExistingResourceGroup(resourceGroupForContainers)
	.WithLinux()
	//.WithPublicImageRegistryOnly()
	.WithPrivateImageRegistry(acrServer, config.ImgRegistryUsername, config.ImgRegistryPassword)
	.WithoutVolume()
	.DefineContainerInstance(aciName + "-1")
		.WithImage(fqdnImageName)
		.WithExternalTcpPort(80)
		.WithCpuCoreCount(1)
		.WithMemorySizeInGB(4)
		.WithEnvironmentVariables(envVars)
		.Attach()
	.WithRestartPolicy(ContainerGroupRestartPolicy.Never)
	//.WithDnsPrefix(aciName)
	.WithNetworkProfileId(azure.SubscriptionId, resourceGroupForContainers, "networkprofilename")
	.CreateAsync();`

### Environment

Azure ACI - Windows 10 - netcoreapp3.1 - Microsoft Visual Studio Professional 2019 (3) Version 16.10.4

.NET SDK (reflecting any global.json):
 Version:   5.0.303
 Commit:    6409b42649

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.303\

Host (useful for support):
  Version: 5.0.15
  Commit:  3065735be7

.NET SDKs installed:
  2.2.110 [C:\Program Files\dotnet\sdk]
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.212 [C:\Program Files\dotnet\sdk]
  5.0.302 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @tsowrirajan-deloitte ,
Thank you for using Azure SDK for .NET.
[Network profiles](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-virtual-network-concepts#network-profile) have been deprecated as of the 2021-07-01 API version.
We can assign network profile using old API version and the SDK, but the service is no longer accept this.
For the result you would like to achieve, we suggest you that could move to our new SDK: [Azure.ResourceManager.Network ](https://www.nuget.org/packages/Azure.ResourceManager.Network/1.0.0-beta.7).
It's under public review now, will soon release a GA version.
