### ISSUE TITLE
[QUERY] What is the syntax for creating generic resources?

### ISSUE THREAD

**Issue by ar1950** [Azure/azure-sdk-for-net#28993]
### Library name and version

Azure.ResourceManager 1.0.0

### Query/Question

The way I did this on the old fluent API:

>             var insights = await ResourceManager
>           .Configure()
>           .Authenticate(creds).WithSubscription(subscriptionName)
>           .GenericResources.Define(deploymentName)
>           .WithRegion(regionName)
>           .WithExistingResourceGroup(rgName)
>           .WithResourceType("typeOfRg")
>           .WithProviderNamespace("Microsoft.XXX")
>           .WithoutPlan()
>           .WithApiVersion("2020-06-01-preview")
>          .WithProperties(propertiesJSON)
>          .CreateAsync();

I am unable to figure out how to do this on this new API version and have been trying to guess how to do it. The closest I could find was this file https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resources/Microsoft.Azure.Management.Resource/src/Customizations/Models/GenericResource.cs 

>         /// <summary>
>         /// Initializes a new instance of the GenericResource class.
>         /// </summary>
>         /// <param name="id">Resource ID</param>
>         /// <param name="name">Resource name</param>
>         /// <param name="type">Resource type</param>
>         /// <param name="location">Resource location</param>
>         /// <param name="tags">Resource tags</param>
>         /// <param name="plan">The plan of the resource.</param>
>         /// <param name="properties">The resource properties.</param>
>         /// <param name="kind">The kind of the resource.</param>
>         /// <param name="managedBy">ID of the resource that manages this
>         /// resource.</param>
>         /// <param name="sku">The SKU of the resource.</param>
>         /// <param name="identity">The identity of the resource.</param>

But I can't determine what the one to one mapping is from the old API to this new one. I also can't find any examples of this in the repo. Can someone please assist?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @ar1950, sorry for the delayed response. For GenericResource in Azure.ResourceManager 1.0.0, you can find the corresponding source code for create method [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/GenericResourceCollection.cs#L91).

Here is the sample code to use this method to create a Vnet:
```csharp
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Azure.Core;
using Azure;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Resources;
using JsonObject = System.Collections.Generic.Dictionary<string, object>;

ArmClient armClient = new ArmClient(new DefaultAzureCredential());
SubscriptionResource subscription = await armClient.GetDefaultSubscriptionAsync();
var lroRg = await subscription.GetResourceGroups().CreateOrUpdateAsync(WaitUntil.Completed, "testRg", new ResourceGroupData(AzureLocation.WestUS));
ResourceGroupResource rg = lroRg.Value;
GenericResourceData input = new GenericResourceData(AzureLocation.WestUS2)
{
    Properties = BinaryData.FromObjectAsJson(
        new JsonObject()
        {
            {"addressSpace", new JsonObject()
                {
                    {"addressPrefixes", new List<string>(){"10.0.0.0/16" } }
                }
            }
        })
};
ResourceIdentifier vnId = rg.Id.AppendProviderResource("Microsoft.Network", "virtualNetworks", "testVnet");
var lroGenericResource = await armClient.GetGenericResources().CreateOrUpdateAsync(WaitUntil.Completed, vnId, input);
GenericResource genericResource = lroGenericResource.Value;
```
