### ISSUE TITLE
[DPG Libraries] Investigate if we can move API docs to a seperate file

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#28999]
We are planning to add https://github.com/Azure/autorest.csharp/issues/2239 API docs for the protcol methods which will be generated something like [this](https://review.docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdate?view=azure-dotnet-preview&branch=ShivangiTestBranchWithoutFiles). 

Today all the API docs live in the same file as source code and if we add API docs like [these](https://github.com/ShivangiReja/azure-sdk-for-net/blob/SampleAPIDocs/sdk/purview/Azure.Analytics.Purview.Scanning/src/Generated/PurviewScanClient.cs#L429-L888) for each method, it would be really hard to read the [source code](https://github.com/ShivangiReja/azure-sdk-for-net/blob/SampleAPIDocs/sdk/purview/Azure.Analytics.Purview.Scanning/src/Generated/PurviewScanClient.cs#L889-L905).

It would be great if we can somehow separate the docs from the code to make it easy to read the code. We need to investigate if we can create a separate xml file for the docs.

- [ ] Investigate how to separate API docs from the code
- [ ] Provide one working sample class

References:
StringBuilder.Remove(Int32, Int32) Method -
https://docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdate?view=azure-dotnet-preview
API docs -
https://github.com/mono/mono/blob/main/mcs/class/corlib/Documentation/en/System.Text/StringBuilder.xml#L3254
Method definition -
https://github.com/microsoft/referencesource/blob/master/mscorlib/system/text/stringbuilder.cs#L865

CC: @annelo-msft, @lirenhe

**Comment by archerzz** [comment]
One thing to mention is that we have to keep part of API docs in source code file, like `<param>` and `<exception>` otherwise there will be compilation errors.

More precisely speaking, we want some essential API docs still kept in the codes and we would like to have a separate file which contains full API docs.

**Comment by archerzz** [comment]
From what I can see, there are two options:

## Option 1

Provide a prune script to remove the sections we don't want to keep in source codes.

**Prons**
- mdoc has already done a great job to parse the source codes and generate the XML file which will be consumed by doc system. We don't want to duplicate the efforts on generating the XML output.
- Developers can choose whether they want to keep the full API docs in source codes or not. Some team may prefer to keep.

**Crons**
- Developers have to remember to run the script every time they generate the codes.
  - We can add a check in CI, like `Export-API.ps1`

## Option 2

Implement our own writer to generate the exact output we want.

**Prons**
- No intermediate step.

**Crons**
- Take time to implement.

**Comment by ShivangiReja** [comment]
Thank you so @archerzz for this investigation!

Our aim is to generate docs like [these](https://review.docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdate?view=azure-dotnet-preview&branch=ShivangiTestBranchWithoutFiles) in the exact same format whether we use Option 1 or Option 2.

I see [docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/dotnet-api-docs-migration#supported-by-standard-auto-generation-tooling) also uses [mdoc](https://github.com/mono/api-doc-tools) to generate all .NET Reference documentation. If we choose Option 1, then I have few questions:
* Can we generate xml files for API docs as a part of `dotnet build /t:GenerateCode` command in the `.../src/Generated` folder? so that SDK devs won't have to run 2 commands, first command to generate code and second command to generate the docs. If we can't do this by Option 1, then I think we have to implement Option 2.
* Do you know how .NET types docs are generated? do they also use mdoc?
 Example: For [System.Text.StringBuilder.Remove(Int32, Int32) Method](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.remove?view=net-6.0) API doc, [here](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/text/stringbuilder.cs#L865) is the method definition and [here](https://github.com/mono/mono/blob/main/mcs/class/corlib/Documentation/en/System.Text/StringBuilder.xml#L3254) is the xml file.
* Could you please use a class from any sdk in [azure-sdk-for-net repo](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk) and use mdoc tool to generate an xml file and create a sample draft PR? so that we can see how it looks like.

**Comment by ShivangiReja** [comment]
Thank you so much @archerzz for this investigation!

Our aim is to generate docs like [these](https://review.docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdate?view=azure-dotnet-preview&branch=ShivangiTestBranchWithoutFiles) in the exact same format whether we use Option 1 or Option 2.

I see [docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/dotnet-api-docs-migration#supported-by-standard-auto-generation-tooling) also uses [mdoc](https://github.com/mono/api-doc-tools) to generate all .NET Reference documentation. If we choose Option 1, then I have few questions:
* Can we generate xml files for API docs as a part of `dotnet build /t:GenerateCode` command in the `.../src/Generated` folder? so that SDK devs won't have to run 2 commands, first command to generate code and second command to generate the docs. If we can't do this by Option 1, then I think we have to implement Option 2.
* Do you know how the xml files are generated for .NET types? do they also use mdoc?
 Example: For [System.Text.StringBuilder.Remove(Int32, Int32) Method](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.remove?view=net-6.0) API doc, [here](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/text/stringbuilder.cs#L865) is the method definition and [here](https://github.com/mono/mono/blob/main/mcs/class/corlib/Documentation/en/System.Text/StringBuilder.xml#L3254) is the xml file.
* Could you please use a class from any sdk in [azure-sdk-for-net repo](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk) and use mdoc tool to generate an xml file and create a sample draft PR? so that we can see how it looks like.

**Comment by archerzz** [comment]
> Thank you so much @archerzz for this investigation!
> 
> Our aim is to generate docs like [these](https://review.docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.createorupdate?view=azure-dotnet-preview&branch=ShivangiTestBranchWithoutFiles) in the exact same format whether we use Option 1 or Option 2.
> 
> I see [docs.microsoft.com](https://docs.microsoft.com/en-us/teamblog/dotnet-api-docs-migration#supported-by-standard-auto-generation-tooling) also uses [mdoc](https://github.com/mono/api-doc-tools) to generate all .NET Reference documentation. If we choose Option 1, then I have few questions:
> 
> * Can we generate xml files for API docs as a part of `dotnet build /t:GenerateCode` command in the `.../src/Generated` folder? so that SDK devs won't have to run 2 commands, first command to generate code and second command to generate the docs. If we can't do this by Option 1, then I think we have to implement Option 2.
> * Do you know how the xml files are generated for .NET types? do they also use mdoc?
>   Example: For [System.Text.StringBuilder.Remove(Int32, Int32) Method](https://docs.microsoft.com/en-us/dotnet/api/system.text.stringbuilder.remove?view=net-6.0) API doc, [here](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/text/stringbuilder.cs#L865) is the method definition and [here](https://github.com/mono/mono/blob/main/mcs/class/corlib/Documentation/en/System.Text/StringBuilder.xml#L3254) is the xml file.
> * Could you please use a class from any sdk in [azure-sdk-for-net repo](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk) and use mdoc tool to generate an xml file and create a sample draft PR? so that we can see how it looks like.

@ShivangiReja 

* We could add doc generation in `GeneratedCode` target. But that target is used by track2 mgmt plane as well. So either we get confirmation with Michael, or we should probably create a new target `GenerateCodeAndDoc`.
* I think the XML files for .Net types are generated by mdoc. But I think mdoc has more features besides generating docs from comments. So the contents of the XML files should have various sources. Let's take StringBuilder as an example.
  * Here is the [corresponding XML file](https://github.com/dotnet/dotnet-api-docs/blob/main/xml/System.Text/StringBuilder.xml), as you can see the contents are exactly the same as shown in ms doc site.
  * Check its [change history](https://github.com/dotnet/dotnet-api-docs/commits/main/xml/System.Text/StringBuilder.xml), and I'm pretty sure it is generated by mdoc.
  * However, if you check the publicly available [source codes](https://github.com/dotnet/corert/blob/master/src/System.Private.CoreLib/shared/System/Text/StringBuilder.cs), [docs](https://github.com/dotnet/docs/blob/main/docs/standard/base-types/stringbuilder.md) and [samples](https://github.com/dotnet/docs/tree/main/samples/snippets/csharp/VS_Snippets_CLR/Conceptual.StringBuilder/cs), you'll realize that the XML is definitely not generated from any of them directly. The some of the comments/text in those files contribute to part of the XML. But the XML file should have been generated in a different way (though still using mdoc).
  * There is little doc I can find about `mdoc`. It's not clear to me how the doc of `StringBuilder` is generated. I guess the doc team might have a private doc repo which hosts the real documents (with anchors to the contents in source codes, other documents and examples, etc). More important, the contents of the documents do not look like being automatically generated. At least part of them is manually written.
  *

**Comment by ShivangiReja** [comment]
>* We could add doc generation in GeneratedCode target. But that target is used by track2 mgmt plane as well. So either we get confirmation with Michael, or we should probably create a new target GenerateCodeAndDoc.

All the track-2 SDKs use GeneratedCode and if introduce a new target, then we have to let all the SDK devs/partners know the new way of generation. Also, we have to update a lot of docs. So I think we should use GeneratedCode target instead of adding a new target. 
Can we add a `Condition` like [this](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/build/CodeGeneration.targets#L71) and generate docs in xml files for DPG for now? this way if we decide to generate xml files for management plane and HLC libraries in future, we can just remove the condition and generate the xml files for all the track-2 libraries.


> * I think mdoc cannot generate doc XML for a single class. We need to compile the project into DLL, give mdoc the DLL and mdoc will generate the XML files for all classes in it..

Do you know if we can achieve this by adding [`<DocumentationFile>path/to/file.xml</DocumentationFile>`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#documentationfile)?

> * Here is the trial to use a modified script to generate the XML files from source codes: https://github.com/Azure/azure-sdk-for-net/pull/29045

I looked at your PR. It looks like it is generating xml files but it is not removing the docs from the .cs files. We want to move the docs to xml files. We don't want 2 copies. Our aim here is to make our code easily readable as it will be difficult if we have [these](https://github.com/ShivangiReja/azure-sdk-for-net/blob/SampleAPIDocs/sdk/purview/Azure.Analytics.Purview.Scanning/src/Generated/PurviewScanClient.cs#L429-L888) super big docs in the .cs files.

**Comment by ShivangiReja** [comment]
>* We could add doc generation in GeneratedCode target. But that target is used by track2 mgmt plane as well. So either we get confirmation with Michael, or we should probably create a new target GenerateCodeAndDoc.

All the track-2 SDKs use GeneratedCode and if introduce a new target, then we have to let all the SDK devs/partners know the new way of generation. Also, we have to update a lot of docs. So I think we should use GeneratedCode target instead of adding a new target. 
Can we add a `Condition` like [this](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/build/CodeGeneration.targets#L71) and generate docs in xml files for DPG for now? this way if we decide to generate xml files for management plane and HLC libraries in future, we can just remove the condition and generate the xml files for all the track-2 libraries.


> * I think mdoc cannot generate doc XML for a single class. We need to compile the project into DLL, give mdoc the DLL and mdoc will generate the XML files for all classes in it..

Do you know if we can achieve this by adding [`<DocumentationFile>path/to/file.xml</DocumentationFile>`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#documentationfile)?

> * Here is the trial to use a modified script to generate the XML files from source codes: https://github.com/Azure/azure-sdk-for-net/pull/29045

I looked at your PR. It looks like it is generating XML files but it is not removing the docs from the .cs files. We want to move the docs to XML files. We don't want 2 copies. Our aim here is to make our code easily readable as it will be difficult if we have [these](https://github.com/ShivangiReja/azure-sdk-for-net/blob/SampleAPIDocs/sdk/purview/Azure.Analytics.Purview.Scanning/src/Generated/PurviewScanClient.cs#L429-L888) large sets of comments intended for users which clutters the source code in the .cs files.

One way is to generate XML file like [this](https://github.com/ShivangiReja/azure-sdk-for-net/blob/SampleAPIDocs/sdk/purview/Azure.Analytics.Purview.Scanning/src/Generated/docs/PurviewScanClient.xml) using autorest.csharp generator and use [`<include>`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#include) tag to reference an XML file.

**Comment by archerzz** [comment]
> > * We could add doc generation in GeneratedCode target. But that target is used by track2 mgmt plane as well. So either we get confirmation with Michael, or we should probably create a new target GenerateCodeAndDoc.
> 
> All the track-2 SDKs use GeneratedCode and if introduce a new target, then we have to let all the SDK devs/partners know the new way of generation. Also, we have to update a lot of docs. So I think we should use GeneratedCode target instead of adding a new target. Can we add a `Condition` like [this](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/AutoRest.CSharp/build/CodeGeneration.targets#L71) and generate docs in xml files for DPG for now? this way if we decide to generate xml files for management plane and HLC libraries in future, we can just remove the condition and generate the xml files for all the track-2 libraries.
> 
> > * I think mdoc cannot generate doc XML for a single class. We need to compile the project into DLL, give mdoc the DLL and mdoc will generate the XML files for all classes in it..
> 
> Do you know if we can achieve this by adding [`<DocumentationFile>path/to/file.xml</DocumentationFile>`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/output#documentationfile)?
> 
> > * Here is the trial to use a modified script to generate the XML files from source codes: [docs(dpg): experimental api gen #29045](https://github.com/Azure/azure-sdk-for-net/pull/29045)
> 
> I looked at your PR. It looks like it is generating XML files but it is not removing the docs from the .cs files. We want to move the docs to XML files. We don't want 2 copies. Our aim here is to make our code easily readable as it will be difficult if we have [these](https://github.com/ShivangiReja/azure-sdk-for-net/blob/SampleAPIDocs/sdk/purview/Azure.Analytics.Purview.Scanning/src/Generated/PurviewScanClient.cs#L429-L888) large sets of comments intended for users which clutters the source code in the .cs files.
> 
> One way is to generate XML file like [this](https://github.com/ShivangiReja/azure-sdk-for-net/blob/SampleAPIDocs/sdk/purview/Azure.Analytics.Purview.Scanning/src/Generated/docs/PurviewScanClient.xml) using autorest.csharp generator and use [`<include>`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags#include) tag to reference an XML file into `.cs` file.

- We can add the `Condition` in `GenerateCode` task, but we should take care that originally `GenerateCode` do not run `dotnet build` (it only run `autorest`)
- We can use `<DocumentationFile>`. I talked with Shanghai doc team, and the output can be consumed. I think it's better than `mdoc` approach which requires: a) building DLL and its dependencies b) install external tool
- I think we can combine `<DocumentationFile>` and `<include>` tag together. See my updated PR [2nd commit](https://github.com/Azure/azure-sdk-for-net/pull/29045/commits/665d0bb33ab53e51086c8e95a40a2b35cf7db08d)
  - Generator will still generate some basic comments along with the codes
  - Generator will write extra contents into separate XML files.
  - Generator will add `/// <include>` in the codes
  - The project should enable `<DocumentationFile>` or even only [`<GenerateDocumentationFile>`](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#generatedocumentationfile) if write to the default XML file.
  - Then a simple `dotnet build/pack` will generate/pack the documents with dll.

**Comment by archerzz** [comment]
`<DocumentationFile>` has been verified in PR #29045 which moves `<remarks>` section of `PurviewScanClient.GetPropertiesAsync(RequestContext)` method into a separate XML file `Docs/PurviewClassificationRuleClient.xml`.

- Corresponding special build of `Azure.Analytics.Purview.Scanning` is [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1619831)
- Corresponding branch on `azure-docs-sdk-dotnet` is [MingzheTestBranch](https://github.com/Azure/azure-docs-sdk-dotnet/blob/MingzheTestBranch/xml/Azure.Analytics.Purview.Scanning/PurviewScanClient.xml)
- Docs team helped to kick off the build [here](https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=297226&view=logs&s=96ac2280-8cb4-5df5-99de-dd2da759617d)
- And the final preview doc is [here](https://review.docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.scanning.purviewscanclient.getpropertiesasync?branch=MingzheTestBranch&view=azure-dotnet-preview). Note that the `<remarks>` section is still in the doc.

I think this is the approach we want to adopt:
- requires minimal change to existing build process
- can be consumed easily with doc team pipeline
- the only change is that we need an XML file writer to export corresponding contents to external XML files

**Comment by lirenhe** [comment]
cc @annelo-msft

**Comment by ShivangiReja** [comment]
>`<DocumentationFile>` has been verified in PR https://github.com/Azure/azure-sdk-for-net/pull/29045 which moves <remarks> section of PurviewScanClient.GetPropertiesAsync(RequestContext) method into a separate XML file Docs/PurviewClassificationRuleClient.xml.

@archerzz I think we decided that we will not use `<DocumentationFile>` to generate an XML file, instead we will write an XML file writer in the generator and add `/// <include>` tag in the source code?

>* requires minimal change to existing build process

What changes we need to do in the existing build process?

https://github.com/Azure/azure-sdk-for-net/pull/29045 PR looks great to me and looks exaclty what we need to do in the generator.  I think our plan is to follow below steps in the generator:
*  We will write an XML file writer in the generator which will include examples and remarks.
* Generator will add `/// <include>` tag in the source code to include an XML file.
* We will keep the basic tags like summary, params, exception..etc with the source code.

Please let me know if the steps above look good to you or I'm missing anything

**Comment by archerzz** [comment]
> @archerzz I think we decided that we will not use `<DocumentationFile>` in `.csproj` to generate an XML file, instead we will write an XML file writer in the generator and add `/// <include>` tag in the source code?
- I made a mistake, it's not `<DocumentationFile>` but [`<GenerateDocumentationFile`](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#generatedocumentationfile) which is already set in common build props. That will generate the final XML file which will be consume by doc team to update the doc site. The XML file referenced by `/// <include>` is generated by our XML writer.

---

> What changes we need to do in the existing build process?
- Right now, there is no change. But I use `minimal` here just in case.

---

> #29045 PR looks great to me and looks exaclty what we need to do in the generator. I think our plan is to follow below steps in the generator:
> 
> * We will write an XML file writer in the generator which will include examples and remarks.
> * Generator will add `/// <include>` tag in the source code to include an XML file.
> * We will keep the basic tags like summary, params, exception..etc with the source code.
> 
> Please let me know if the steps above look good to you or I'm missing anything
- This is exactly what we want :)

**Comment by ShivangiReja** [comment]
Thanks for the clarification!
