### ISSUE TITLE
Provide information to tell which shared source code needed in the SDK

### ISSUE THREAD

**Issue by chunyu3** [Azure/azure-sdk-for-net#28990]
Currently, we have a set of shared source code needed to add into SDK Client Library project. Different SDK package may need add different shared source code, otherwise it will fail to compile the project.

We need to provide a doc to tell customer which shared sources do we provide and what set of shared code do they need to add to their project.

In future, we may need to automatically figure out which shared sources are needed in codegen and add those to the sdk project files automatically.

**Comment by pallavit** [comment]
@chunyu3 - is this still valid?

**Comment by chunyu3** [comment]
@pallavit Yes. this issue still exists. When the needed shared code is not included in project file(.csproj), the build will fail. And this will break CI automation.

**Comment by pallavit** [comment]
Got it, thanks for checking @chunyu3
