### ISSUE TITLE
[BUG] DataLakePathClient.Rename(..) does not pass the SAS when authenticated with AzureSasCredential, only when passed with the Uri

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#29002]
### Library name and version

Azure.Storage.Blobs, Azure.Storage.DataLake

### Describe the bug

When authenticating a client with a URI appended with a SAS to any DataLake Storage Client will successfully make a Rename Call.

However if a client is authenticated with a `AzureSasCredential` the source is not appended with the SAS signature from the `AzureSasCredential`.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakePathClient.cs#L2160

This is the same for any DataLake Parent Storage Client that passes a credential to the DataLake Child Storage Client. The credential gets passed but if it's with a `AzureSasCredential` it will not append the SAS to the source. Only if authenticated with a Uri appended with a SAS that it will be passed.

### Expected behavior

When authenticating with a `AzureSasCredential` a SAS will be appended to the source path when calling rename.

### Actual behavior

The SAS is not appended from `AzureSasCredential` to the source path when calling `DataLakePathClient.Rename(...)`.

### Reproduction Steps

**//Repro:**
AzureSasCredential **sourceCredential** = new AzureSasCredential(<Valid SAS>);
var sourceDirectoryClient = new DataLakeDirectoryClient(sourceUri, **sourceCredential**);
await sourceDirectoryClient.RenameAsync(destinationPath.FileName, destinationPath.FileSystem, null, requestConditions, cancellationToken).ConfigureAwait(false);

//Same with:
AzureSasCredential **sourceCredential** = new AzureSasCredential(<Valid SAS>);
var fileSystemClient = new DataLakeFileSystemClient(sourceUri, **sourceCredential**);
var sourceDirectoryClient = fileSystemClient.GetDirectoryClient(directoryPath);
await sourceDirectoryClient.RenameAsync(destinationPath.FileName, destinationPath.FileSystem, null, requestConditions, cancellationToken).ConfigureAwait(false);

**//Mitigation:**
var sourceDirectoryClient = new DataLakeDirectoryClient(**sourceUri + sourceSas**);
await sourceDirectoryClient.RenameAsync(destinationPath.FileName, destinationPath.FileSystem, null, requestConditions, cancellationToken).ConfigureAwait(false);

// OR
var fileSystemClient = new DataLakeFileSystemClient(**sourceUri + SasToken**);
var sourceDirectoryClient = fileSystemClient.GetDirectoryClient(directoryPath);
await sourceDirectoryClient.RenameAsync(destinationPath.FileName, destinationPath.FileSystem, null, requestConditions, cancellationToken).ConfigureAwait(false);

**Comment by amnguye** [comment]
We're looking into the issue right now.

**Comment by amnguye** [comment]
We should also look into other cases where `AzureSasCredential` is not passing the SAS for other areas where we append on the SAS from the URL

**Comment by amnguye** [comment]
I've noted a mitigation in the github description. Thanks for your patience.

**Comment by khandelwalankit04** [comment]
@amnguye : Is there an update on this issue ? Are we still on schedule to release it with upcoming version of library?
