### ISSUE TITLE
[BUG] Azure.ResourceManager.Network 1.0.0-beta7 does not allow create new nsg using SourceAddressPrefixes

### ISSUE THREAD

**Issue by gui28347** [Azure/azure-sdk-for-net#29004]
### Library name and version

Azure.ResourceManager.Network 1.0.0-beta7

### Describe the bug

    var nsg = await resourceGroup.GetNetworkSecurityGroups().CreateOrUpdateAsync(Azure.WaitUntil.Completed, $"newnsg", new NetworkSecurityGroupData
                    {
                        Location = "WestUS2",
                        SecurityRules = {
                         new SecurityRuleData {
                         **SourceAddressPrefixes** = ,(Property is read-only
                         },

 This bug makes harder to add a list of ranges, because the only other way is creating one rule per range using SourceAddressPrefix which allow property to be set.

### Expected behavior

Allow set SourceAddressPrefixes of NetworkSecurityGroupData. Currently only SourceAddressPrefix can be used.

### Actual behavior

SourceAddressPrefixes is configured as read-only property.

### Reproduction Steps

Use latest beta version of Azure.ResourceManager.Network 1.0.0-beta7 and try to create a NSG using the property SourceAddressPrefixes

### Environment

Visual Studio 2022
Win10

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
