### ISSUE TITLE
Uber

### ISSUE THREAD

**Issue by daleksandrov-qontigo** [Azure/azure-sdk-for-net#29006]
There is a sentence on the page:

> This exception type is thrown when the *uber* request on a batch is successful but one or more of the sub requests has failed.

Is it *uber* by intension or it should be *upper* here?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8bc09c7e-a6dc-487a-ac01-14896d1a7879
* Version Independent ID: 7c6f8312-8ff4-f41d-4921-b4c3af7639fc
* Content: [BlobBatchException Class (Microsoft.Azure.Storage.Blob) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.blobbatchexception?view=azure-dotnet-legacy&viewFallbackFrom=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Storage.Blob/BlobBatchException.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.Blob/BlobBatchException.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amnguye** [comment]
I also believe it's upper.

This routed to the wrong version of the library, this is for a v11 version of the library which is deprecated. So we are not looking to make any updates to the v11 documentation that's minor. All v11 issues should be routed to github.com/azure/azure-storage-net
