### ISSUE TITLE
[QUERY]How to implement putBlocks Azure.Storage.Blobs using 12.10.0

### ISSUE THREAD

**Issue by Shyam268** [Azure/azure-sdk-for-net#29008]
### Library name and version

Azure.Storage.Blobs using 12.10.0 and  Using dotnet6.0

### Query/Question

we are planning to replace deprecated` WindowsAzure.Storage` package with `Azure.Storage.Blobs`. But i dont find any methods to support putBlock functionality which is available in the deprecated package .
please let me know how to achieve this functionality and also list the committed and uncommitted blocks.

**Comment by Shyam268** [comment]
> Thank you for your feedback. This has been routed to the support team for assistance.

Thanks you

**Comment by amnguye** [comment]
Put Block should be the equivalent as Stage Block
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blockblobclient.stageblockasync?view=azure-dotnet

We have a tiny sample here
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md#transactional-md5-and-crc64

**Comment by PramodValavala-MSFT** [comment]
@Shyam268 Just following up here... Hope the previous comment clears things up.

**Comment by Shyam268** [comment]
Yes this example works fine for me and is there any way to get committed blocks and uncommitted blocks details?

**Comment by amnguye** [comment]
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blockblobclient.getblocklistasync?view=azure-dotnet-preview

And if you specify the https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blocklisttypes?view=azure-dotnet-preview when calling the API you can get the uncommited blocks.

Closing the github issue as the original post has been resolved.
