### ISSUE TITLE
Azure.RequestFailedException: Service request failed.  Status: 407 (Proxy Authentication Required)

### ISSUE THREAD

**Issue by Shankaranand-m** [Azure/azure-sdk-for-net#29011]
### Library name and version

Azure.AI.FormRecognizer

### Query/Question

Trying to call Invoice API using .dotnetSDK 

RecognizeInvoicesOperation operation = await client.StartRecognizeInvoicesAsync(stream, options);
Response<RecognizedFormCollection> operationResponse = await operation.WaitForCompletionAsync();

getting
 
Azure.RequestFailedException: Service request failed.  Status: 407 (Proxy Authentication Required) 
Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.
incorrect username and/or password, but could also be caused by network problems.

 credentials are fine.  

### Environment

Windows 2012 Server

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Shankaranand-m** [comment]
any updates

**Comment by kinelski** [comment]
Hello @Shankaranand-m 

1. Could you tell us what method of authentication you're trying to use?
2. What's the service and SDK version you're using?
3. The complete error message includes an error header called `apim-request-id` to help us debugging the issue on the service side. Could you share it with us? Example:

```
Headers:
apim-request-id: fde39ce8-cdd8-4498-9674-4be81364f116
Content-Length: 224
Content-Type: application/json
Date: Mon, 20 Jun 2022 21:39:21 GMT
```
