### ISSUE TITLE
When cloning the repo git warns that a json file path is too long (part of the test json data).

### ISSUE THREAD

**Issue by AraHaan** [Azure/azure-sdk-for-net#29023]
![image](https://user-images.githubusercontent.com/15173749/170829436-12284ac8-889b-43a8-aef9-7f64669d897d.png)

This then results in git thinking that the file was deleted as well.
![image](https://user-images.githubusercontent.com/15173749/170829476-3b576c99-3467-448b-bd6b-cc5df50a74d8.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AraHaan** [comment]
cc: @JoshLove-msft

**Comment by JoshLove-msft** [comment]
I believe you can try adding the following when cloning:
```
git clone -c core.longpaths=true 
```
