### ISSUE TITLE
[BUG] Word level timestamps not In Translation Results after setting it to true in SpeechTranslationConfig

### ISSUE THREAD

**Issue by xXBasti** [Azure/azure-sdk-for-net#29027]
### Library name and version

Microsoft.CognitiveServices.Speech 1.21.0.28

### Describe the bug

In the Library  there seems to be mix up in the inheritance structure between the SpeechRecognizer  and the TranslationRecognizer. 
In the creation, the TranslationRecognizer get SpeechTranslationConfig, which inherits from SpeechConfig. 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.translation.translationrecognizer.-ctor?view=azure-dotnet#microsoft-cognitiveservices-speech-translation-translationrecognizer-ctor(microsoft-cognitiveservices-speech-speechtranslationconfig)

The Config "SpeechTranslationConfig" contains therefore the method [RequestWordLevelTimestamps()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.requestwordleveltimestamps?view=azure-dotnet#microsoft-cognitiveservices-speech-speechconfig-requestwordleveltimestamps), which enabled the SpeechRecognizer to provide Results (SpeechRecognitionResults) containing the Best() method with word level timestamps as requested with the config.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognitionresult?view=azure-dotnet

Interestingly, regardless of providing the field in the config the TranslationRecognitionResult does not contain word level timestamps nor the field best. It just contains the text results from the SpeechRecognitionResults, which does not make sense, as the translation is performed based on the transcription. ### 

### Expected behavior

TranslationRecognitionResult should contain word level timestamps as it is set to true in the SpeechTranslationConfig.

### Actual behavior

TranslationRecognitionResult does not contain the method Best() or any other additional field containing word level timestamps.

### Reproduction Steps

Comparing the docs for example as it seems to be a problem in the inheritance logic of  the config or the results.
Result containing the field:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechrecognitionresult?view=azure-dotnet
Results should containing the field:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.translation.translationrecognitionresult?view=azure-dotnet
Config which sets the word level:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechtranslationconfig?view=azure-dotnet

### Environment

Microsoft.CognitiveServices.Speech.csharp, Version=1.21.0.28
net461
Windows 10

**Comment by MaslinuPoimal** [comment]
This is indeed a very confusing issue. Word-level translation timestamps seem like a very helpful feature to me. It is unfortunate that this use case is not supported yet. Hopefully Microsoft can help soon.
