### ISSUE TITLE
[BUG] TableEntity.GetBinaryData does not return the correct data after downloading the entity

### ISSUE THREAD

**Issue by alennartz** [Azure/azure-sdk-for-net#29029]
### Library name and version

Azure.Data.Tables 12.5.0

### Describe the bug

Calling [`BinaryData TableEntity.GetBinaryData(string key)`](https://github.com/Azure/azure-sdk-for-net/blob/02c3ba28187ce4bc478072e1ca98d25949c75125/sdk/tables/Azure.Data.Tables/src/TableEntity.cs#L114) returns the incorrect data when the underlying property dictionary contains a `byte[]` (which is the case after downloading the entity).  This happens because the  code in [`object TableEntity.GetValue(string key, Type type = null)`](https://github.com/Azure/azure-sdk-for-net/blob/02c3ba28187ce4bc478072e1ca98d25949c75125/sdk/tables/Azure.Data.Tables/src/TableEntity.cs#L250) passes the value typed as `object` to the `BinaryData` constructor instead of casting it to `byte[]` first. This results in the constructor for json objects being matched and the underlying byte array representing the json serialization of the actual array object.

WORKAROUND: Use `byte[] TableEntity.GetBinary(string key)`

### Expected behavior

Get a BinaryData object containing the same array of bytes which was stored in the TableEntity

### Actual behavior

Returns a BinaryData object containing an array of bytes different to the one that was stored.

### Reproduction Steps

repro can be seen simply by adding a `byte[]` to a table entity then asking for it back as `BinaryData`
```c#
TableEntity te = new TableEntity();
byte[] array = new byte[] {1, 2, 3, 4, 5};
te.Add("key", array);
byte[] roundTrip = te.GetBinaryData("key").ToArray();
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  2.1.809 [C:\Program Files\dotnet\sdk]
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.302 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
