### ISSUE TITLE
Page title refers to the previous package

### ISSUE THREAD

**Issue by jeffputz** [Azure/azure-sdk-for-net#29025]
The page title refers to the old package, and should instead refer to Azure.Extensions.AspNetCore.DataProtection.Blobs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a336573a-2f87-6ed2-e1d6-148d803cd599
* Version Independent ID: f8cf3bc6-d05f-bd30-e791-b20061b9e25f
* Content: [Azure Storage Blob Key Store for Microsoft.AspNetCore.DataProtection - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/extensions.aspnetcore.dataprotection.blobs-readme)
* Content Source: [api/overview/azure/extensions.aspnetcore.dataprotection.blobs-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/extensions.aspnetcore.dataprotection.blobs-readme.md)
* Service: **extensions**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by jsquire** [comment]
Hi @jeffputz.   Thanks for letting us know.   We'll get this fixed up.

**Comment by jsquire** [comment]
After looking into this, the title is correct.  The package in question is an extension to the `Microsoft.AspNetCore.DataProtection` which enables using Blob Storage for keys.

**Comment by jeffputz** [comment]
@jsquire you're right, but it's confusing because there's a package previously dependent on this that was deprecated with a similar name, and that was `Microsoft.AspNetCore.DataProtection.AzureStorage`, instead of the current `Azure.Extensions.AspNetCore.DataProtection.Blob`. My _opinion_ is that it might be clearer if there was a call-out box about the deprecated package since the name is so similar. /unresolve
<img width="545" alt="image" src="https://user-images.githubusercontent.com/2114255/171005212-da2e4b29-624f-4020-a52f-1bba3316b319.png">

**Comment by jsquire** [comment]
That's an interesting thought @jeffputz.   Where would you think that call out should appear and what content would be helpful for it to contain?

**Comment by jeffputz** [comment]
I would put it near the top, maybe before the "getting started" header, and call out something like:

> The `Azure.Extensions.AspNetCore.DataProtection.Blobs` package replaces `Microsoft.AspNetCore.DataProtection.AzureStorage`, which has been deprecated. Both packages have a dependency on `Microsoft.AspNetCore.DataProtection`, which is still supported.

I _think_ the API is the same, but I'm not sure. I would append the above with whether or not that's true, and if it's not maybe the differences.

**Comment by jsquire** [comment]
After discussion, the page has been updated to call out the current version in the overview and also appears in the `Add this package` section.  The Azure SDK deprecation strategy is to call attention to deprecation on the legacy package and call out the current version.   As we do not want to highlight deprecated packages in the current documentation and potentially cause confusion, we won't be adding the callout that was discussed.
