### ISSUE TITLE
OfficeSupplyEntity not specified in doc examples

### ISSUE THREAD

**Issue by popokatapepel** [Azure/azure-sdk-for-net#29040]
In the examples section you give the following example for querying the data using linq

`double priceCutOff = 6.00;
Pageable<OfficeSupplyEntity> queryResultsLINQ = tableClient.Query<OfficeSupplyEntity>(ent => ent.Price >= priceCutOff);`

However, the examples do not clarify  how to define the class OfficeSupplyEntity, maybe this can be added.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7139f609-fc7c-361d-ab81-bd8c15be23c4
* Version Independent ID: 5a22db59-9012-23a0-5139-00ef98214928
* Content: [Azure Tables client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/Data.Tables-readme-pre)
* Content Source: [api/overview/azure/data.tables-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/data.tables-readme-pre.md)
* Service: **tables**
* GitHub Login: @christothes
* Microsoft Alias: **chriss**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @popokatapepel  - The readme demonstrates the use of the OfficeEntity class as a high-level overview, but the class is defined in the strongly typed entity sample here https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample2CreateDeleteEntities.md#strongly-typed-entity

**Comment by popokatapepel** [comment]
Hi @christothes,
thanks for your feedback. Creating a strongly typed entity solved my problem. However, this post was more a feedback on the docs, since its a little frustrating when I can't work through a Tutorial.  
Maybe it would help others if you include the link in the docs or if you put a block in the docks where you define the local entity.
