### ISSUE TITLE
[BUG] DiskData class PropertyUpdatesInProgressTargetTier property throws NullReferenceException

### ISSUE THREAD

**Issue by omri-muszkal** [Azure/azure-sdk-for-net#29046]
### Library name and version

Azure.ResourceManager.Compute 1.0.0-beta.8

### Describe the bug

When trying to access the "PropertyUpdatesInProgressTargetTier" property, the code does not check if the property "PropertyUpdatesInProgress" is null before trying the acces the inner property "TargetTier".

we can see that here:
https://github.com/Azure/azure-sdk-for-net/blob/873de4b2fa081a2653b10527e1bfd190f4c8d496/sdk/compute/Azure.ResourceManager.Compute/src/Generated/DiskData.cs#L174-L179

When searching the code, I came across a place where this check is being preformed which is here:
https://github.com/Azure/azure-sdk-for-net/blob/263ceae389f53ff6ff19666ead5b6cd1faba59d6/sdk/compute/Azure.ResourceManager.Compute/src/Generated/Models/ManagedDiskPatch.cs#L69-L74

### Expected behavior

The code should return null if the "PropertyUpdatesInProgress" property is null before trying the access the inner property

### Actual behavior

The code throws NullReferenceException.

### Reproduction Steps

List Disks in a subscription and trying to get the property

**Comment by omri-muszkal** [comment]
Just saw that this PR  #28327 fixes this issue, any idea when we will get a new version of Azure.ResourceManager.Compute ?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
This should have been fixed in the latest version (since 1.0.0): https://github.com/Azure/azure-sdk-for-net/blob/bfd8241c110c14bc43d8731e5492e5fef5fe91a2/sdk/compute/Azure.ResourceManager.Compute/src/Generated/ManagedDiskData.cs#L169
Closing the issue
