### ISSUE TITLE
[Form Recognizer] Unstable tests on China cloud.

### ISSUE THREAD

**Issue by zedy-wj** [Azure/azure-sdk-for-net#29044]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

**Error Description:**
There are some unstable tests always failed on `China` cloud in [weekly pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1607741&view=results). After investigation, the main errors and failed tests are as follows:

**1.Azure.RequestFailedException : Download failed. Please check your input URL.**

- CheckFormTypeinSubmodelAndRecognizedForm
- StartRecognizeCustomFormsWithoutLabels

**2.Azure.RequestFailedException : Generic error during prediction.**

- StartRecognizeCustomFormsWithLabels
- StartRecognizeCustomFormsWithLabelsCanParseMultipageForm
- StartRecognizeCustomFormsWithLabelsCanParseMultipageFormWithBlankPage
- CheckFormTypeinSubmodelAndRecognizedForm

**3.System.AggregateException : Retry failed after 4 tries.**

- StartRecognizeCustomFormsWithLabels 
- RecognizeContentFromUri 
- CheckFormTypeinSubmodelAndRecognizedForm
- StartAnalyzeDocumentWithCustomModel

**Expected behavior:**
These tests can pass stably every time on `China` cloud in the pipeline.

@scottaddie , @AlexGhiondea, @benbp , @maririos, @meeraharidasa , @mayurid for notification.

**Comment by jsquire** [comment]
//fyi: @pallavit

**Comment by v-xuto** [comment]
@kinelski  Is there any progress on this issue? If there is any progress, please keep us informed. Thanks a lot.

**Comment by kinelski** [comment]
Unfortunately we've been seeing the same errors in the public cloud for a long time. They appear to be service-related. We have notified the service team about it but we still don't have an estimate of when they'll be fixed.

**Comment by kinelski** [comment]
My understanding is that the issues are the same we're seeing in the public one. Issues already being tracked by https://github.com/Azure/azure-sdk-for-net/issues/31914. Feel free to reopen this or create a new issue if we have extra issues not seen in the public cloud.
