### ISSUE TITLE
Azure.Search.Documents Guides and Samples Updates

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-net#29047]
The guides and samples for `Azure.Search.Documents` should include new features such as:

- [x] Using AAD for authentication
- [x] Querying with semantic search
- [ ] Resetting documents and skills

**Comment by pallavit** [comment]
/cc: @ShivangiReja was this covered as part of the last release?

**Comment by ShivangiReja** [comment]
No, we need to add these docs in the readme and samples.

**Comment by ShivangiReja** [comment]
No, we need to add these features in the readme and samples.
