### ISSUE TITLE
Non-Public Members only on IPublishingProfile (via GetPublishingProfile)

### ISSUE THREAD

**Issue by christophwille** [Azure/azure-sdk-for-net#2904]
With Microsoft.Azure.Management.AppService.Fluent version 1.0.0-beta50

https://github.com/Azure/azure-sdk-for-net/blob/Fluent/src/ResourceManagement/AppService/Microsoft.Azure.Management.AppService.Fluent/Domain/IPublishingProfile.cs

I can access those via Reflection, yes, but aren't those intended to be public?

Further observations:

Why is WebDeploy information the publishing profile missing?
Is this intentionally not also available as Async method?

**Comment by jianghaolu** [comment]
Hi @christophwille, thanks for reporting this. This is a mistake. We will fix them in this month's release.

Which WebDeploy support are you looking for? The file upload in Kudu?

**Comment by jianghaolu** [comment]
Hi @christophwille 

According to https://docs.microsoft.com/en-us/dotnet/articles/csharp/programming-guide/classes-and-structs/access-modifiers, interface members are always public.
