### ISSUE TITLE
[QUERY] Setting the "Prefer: return-content" header when inserting data into Table Storage

### ISSUE THREAD

**Issue by pingzing** [Azure/azure-sdk-for-net#29054]
### Library name and version

Azure.Data.Tables v12.2.5.0

### Query/Question

I have two questions about how to work with the "Prefer: return-content" header with the Table Storage SDK. 

First: is there any way to do this on a per-request basis? Currently, my solution is rather heavy handed--I create an `HttpPipelinePolicy` for my TableServiceClient that intercepts all HTTP Requests, and glues the `"Prefer": "return-content"` header onto them. It's not exactly elegant. Is there a cleaner way to do this?

Second: Because of the limitations of my above approach, it doesn't really work when sending up a batch Insert transaction. Is there currently any way _at all_ to specify that I'd like to receive my content back when performing a batch operation?

~~(A bit of explanation as to why: I have a data structure made up of a list of entities. I create them, but then I need to store their freshly-generated ETags. I need to do _this_ because I also have an operation that performs a batch `UpdateMerge` on all of the entities. But if I don't send up an ETag, and the update contains entities with Parition Keys that don't exist in the list, instead of erroring, it will create _new_ rows, which I'd like to avoid.)~~
Actually, scratch this particular justification, I think the behavior I was seeing was user error. Still interested to know if getting content back is possible though.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
> Still interested to know if getting content back is possible though.

We don't currently expose this and adding it would introduce some challenges with how we handle return types of methods today. That said, if there are some compelling scenarios driving this need, we'd be happy to consider it.
