### ISSUE TITLE
[BUG] SQLDatabaseCollection.CreateOrUpdate throws exception when SqlDatabaseData has ElasticPoolId value set

### ISSUE THREAD

**Issue by jbailey-limgeomatics** [Azure/azure-sdk-for-net#29055]
### Library name and version

Azure.ResourceManager.Sql 1.0.0-beta.4

### Describe the bug

When calling SQLDatabaseCollection.CreateOrUpdate to create a new database, and when the SqlDatabaseData parameter has its ElasticPoolId parameter set to a valid elastic pool ID, an exception is thrown.

### Expected behavior

The database should be created in the specified elastic pool.

### Actual behavior

The call to SqlDatabaseCollection.CreateOrUpdate() fails with the following exception:

Azure.RequestFailedException
  HResult=0x80131500
  Message=Service request failed.
Status: 400 (Bad Request)

Content:
{"code":"BadRequest","message":"An error occurred while processing this request.","target":null,"details":[],"innererror":[]}

Headers:
Cache-Control: no-store, no-cache
x-ms-request-id: bb17ee49-d051-4661-b849-215894842993
X-Content-Type-Options: REDACTED
DataServiceVersion: REDACTED
Strict-Transport-Security: REDACTED
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Date: Tue, 31 May 2022 20:37:41 GMT
Content-Length: 125
Content-Type: application/json

  Source=Azure.ResourceManager.Sql
  StackTrace:
   at Azure.ResourceManager.Sql.DatabasesRestOperations.CreateOrUpdate(String subscriptionId, String resourceGroupName, String serverName, String databaseName, SqlDatabaseData data, CancellationToken cancellationToken)
   at Azure.ResourceManager.Sql.SqlDatabaseCollection.CreateOrUpdate(WaitUntil waitUntil, String databaseName, SqlDatabaseData data, CancellationToken cancellationToken)
   at REDACTED
   at REDACTED

  This exception was originally thrown at this call stack:
    [External Code]
    REDACTED
    REDACTED

### Reproduction Steps

When running the following code, 

SqlServerResource sqlServer = _armClient.GetSqlServerResource(new ResourceIdentifier($"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{sqlServerName}"));
            ElasticPoolCollection elasticPools = sqlServer.GetElasticPools();
            ElasticPoolResource elasticPool = elasticPools.Get($"{elasticPoolName}");
            SqlDatabaseCollection sqlDatabaseCollection = sqlServer.GetSqlDatabases();
            SqlDatabaseData sqlDatabaseData = new SqlDatabaseData(new AzureLocation("Canada Central"));
            sqlDatabaseData.ElasticPoolId = elasticPool.Id;
            try
            {
                sqlDatabaseCollection.CreateOrUpdate(Azure.WaitUntil.Completed, $"{databaseName}", sqlDatabaseData);
            }
            catch (InvalidOperationException invalidOperationException)
            {
                Console.WriteLine(invalidOperationException.Message);
            }

an exception is thrown at the call to CreateOrUpdate(). Commenting the line that sets the ElasticPoolID property results in the database being created successfully. I've verified that the database does not exist prior to calling CreateOrUpdate(), and that the elastic pool ID is valid.

### Environment

Windows 10 .NET Core 3.1
Visual Studio 17.2.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jbailey-limgeomatics** [comment]
The same behaviour also occurs if I try to set the Sku property on the SqlDatabaseData:

            SqlDatabaseData sqlDatabaseData = new SqlDatabaseData(new AzureLocation("Canada Central"));
            //sqlDatabaseData.ElasticPoolId = elasticPool.Id;
            SqlSku sqlSku = new SqlSku("Basic")
            {
                Tier = "Basic",
                Capacity = 5
            };
            sqlDatabaseData.Sku = sqlSku;
            try
            {
                sqlDatabaseCollection.CreateOrUpdate(Azure.WaitUntil.Completed, $"sqldb{tenantShortName}fgp{shortEnvironment}", sqlDatabaseData);

            }
            catch (InvalidOperationException invalidOperationException)
            {
                Console.WriteLine(invalidOperationException.Message);
            }

**Comment by jbailey-limgeomatics** [comment]
The same behaviour also occurs if I call SqlDatabaseResource.Update() on an existing database passing a SqlDatabasePatch object with the ElasticPoolId property set.

**Comment by fengzhou-msft** [comment]
The wrong service API version may be related to https://github.com/Azure/azure-sdk-for-net/issues/28387#issuecomment-1118685224.

**Comment by fengzhou-msft** [comment]
Please try with [Azure.ResourceManager.Sql 1.0.0-beta.5](https://www.nuget.org/packages/Azure.ResourceManager.Sql/1.0.0-beta.5).

**Comment by jbailey-limgeomatics** [comment]
That fixed it. Thanks.
