### ISSUE TITLE
Please add an explaination to the behavior of the property.

### ISSUE THREAD

**Issue by Andrey-Anatolyevich** [Azure/azure-sdk-for-net#29056]
Please add an explicit explanation of what happens when the end of data is reached (aka, the last page)
Would the token be null? Would it be an empty string? Would it be set to some predefined value?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2847b0da-5f3d-98bb-1a8f-5b09f8378c1c
* Version Independent ID: 6a00d35e-f9e5-5c64-e09b-bbb7654f0276
* Content: [ResponseMessage.ContinuationToken Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.responsemessage.continuationtoken?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/ResponseMessage.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/ResponseMessage.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by RakeshMohanMSFT** [comment]
@Andrey-Anatolyevich Thank you for reaching out, we are looking into it.

**Comment by jay-most** [comment]
@Andrey-Anatolyevich Thanks for reaching out. Can you describe in more detail your ask?

**Comment by Andrey-Anatolyevich** [comment]
@RakeshMohanMSFT @jay-most 
Sure.

In the team we had lack of clarity what happens to the returned ContinuationToken when there is no more data to read.
One of the team members brought up some concern that the value of the ContinuationToken might be set to some predefined constant value as he saw in some API documentation (At least that is what he believes in).

So the ask is to include in the documentation page an explicit statement specifying what value the ContinuationToken will have when there is no more data available.
For example:
`When there is no more data available, the value of the ContinuationToken is NULL.` / `empty string` / whatever the value will be.

I believe you'll figure a better wording, but I hope the ask is clear.
