### ISSUE TITLE
Problem with security in Microsoft.Azure.Management.DataLake.Store

### ISSUE THREAD

**Issue by petermzg** [Azure/azure-sdk-for-net#2905]
When I try to use Microsoft.Azure.Management.DataLake.Store from AppDomain, I get error:

> 'Microsoft.Azure.Management.DataLake.Store.Models.AdlsErrorException.GetObjectData(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)'. Security accessibility of the overriding method must match the security accessibility of the method being overriden.

For AppDomain I have next permissions:
```
var permisions = new PermissionSet(PermissionState.None);
permisions.AddPermission(new ReflectionPermission(ReflectionPermissionFlag.MemberAccess));
permisions.AddPermission(new FileIOPermission(PermissionState.Unrestricted));
permisions.AddPermission(new WebPermission(PermissionState.Unrestricted));
permisions.AddPermission(new EnvironmentPermission(PermissionState.Unrestricted));
permisions.AddPermission(new SecurityPermission(PermissionState.Unrestricted));
permisions.AddPermission(new SmtpPermission(PermissionState.Unrestricted));
```

**Comment by markcowl** [comment]
@begoldsm please take a look

**Comment by begoldsm** [comment]
@petermzg Just to make sure I understand correctly, the error is when attempting to load that type:
`'Microsoft.Azure.Management.DataLake.Store.Models.AdlsErrorException`, correct?
If this is the case, I will need some help from @markcowl, since this is a class generated by AutoRest which has the following attribute at the top layer:
`[System.Serializable]`

**Comment by petermzg** [comment]
@begoldsm Yes! Problem with security attribute [SecurityPermission] on method GetObjectData (Microsoft.Azure.Management.DataLake.Store.Models.AdlsErrorException).  And several other classes also contain this attribute.

**Comment by markcowl** [comment]
Yes, looks like the ```GetObjectData``` override needs a ```SecurityCritical``` attribute, and the corresponding serialization constructor may slso need a ```SecuritySafeCritical``` attribute.  Of course this means the method will not be usable under partial trust.

**Comment by markcowl** [comment]
Is this in runtime or generated code? What are the actual requirements for partial trust of these libraries?

**Comment by petermzg** [comment]
In my app (WebJob on Azure) I load modules to AppDomain. One of modules uses Microsoft.Azure.Management.DataLake.Store

**Comment by shahabhijeet** [comment]
@petermzg can your code run outside webjob scenario?
By design WebJob runs in FullTrust. So at this point could you provide a repro where I can repro the full call stack at my end.

**Comment by shahabhijeet** [comment]
Please reactivate this issue or open a new issue if this is still a problem
Closing.
