### ISSUE TITLE
[QUERY] Cannot locate class "QuestionAnsweringProjectsClient" in NuGet package "Azure.AI.Language.QuestionAnswering"

### ISSUE THREAD

**Issue by rliberoff** [Azure/azure-sdk-for-net#29051]
### Library name and version

Azure.AI.Language.QuestionAnswering 1.1.0-beta.1

### Query/Question

Based on the documentation found [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering), in order to interact with the Question Answering service, I just need to create an instance of the [QuestionAnsweringProjectsClient](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/src/Generated/QuestionAnsweringProjectsClient.cs) for managing projects.

However, after adding the corresponding NuGet package [Azure.AI.Language.QuestionAnswering](https://www.nuget.org/packages/Azure.AI.Language.QuestionAnswering/1.1.0-beta.1), the mentioned class cannot be found.

The same applies to the current non-beta version.

Where can we find the [QuestionAnsweringProjectsClient](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/src/Generated/QuestionAnsweringProjectsClient.cs) class?

Thank you!

### Environment

Windows 11
.NET 6
Visual Studio 2022 17.2.2
Azure.AI.Language.QuestionAnswering 1.1.0-beta.1
Azure.AI.Language.QuestionAnswering 1.0.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
The `QuestionAnsweringProjectsClient` was [added in 1.1.0-beta.1](https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.Language.QuestionAnswering_1.1.0-beta.1/sdk/cognitivelanguage/Azure.AI.Language.QuestionAnswering/CHANGELOG.md). Did you add `using Azure.AI.Lanugage.QuestionAnswering.Projects` to your source file? It's in a separate namespace.

**Comment by rliberoff** [comment]
Excellent! Found it! 

Thank you.
