### ISSUE TITLE
[BUG] AppendBlobClient.AppendBlockFromUri() with no options argument throws NullReferenceException

### ISSUE THREAD

**Issue by n0idea** [Azure/azure-sdk-for-net#29062]
### Library name and version

Azure.Storage.Blobs 12.12.0

### Describe the bug

Omitting the `AppendBlobAppendBlockFromUriOptions options` argument or passing it as `null` in  

```
AppendBlobClient.AppendBlockFromUri(
        Uri sourceUri, 
        AppendBlobAppendBlockFromUriOptions options = default, 
        CancellationToken cancellationToken = default)
```
throws a `System.NullReferenceException`.

### Expected behavior

Omitting or passing the `options` argument as `null` should pick up default values (as options properties are optional)

### Actual behavior

The `AppendBlobClient.AppendBlockFromUri()` method call throws a `System.NullReferenceException` when `options` argument is `null`

### Reproduction Steps

```
appendBlobClient.AppendBlockFromUri(uri);
```

### Environment

```
.NET SDK
        Version:   6.0.300
        Commit:    8473146e7d

Runtime environment:
        OS Name:     Mac OS X
        OS Version:  12.2
        OS Platform: Darwin
        RID:         osx.12-x64
        Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
        Version: 6.0.5
        Commit:  70ae3df4a6
```

**Comment by amnguye** [comment]
Sorry for the late reply.

I can reproduce the issue you're facing and you're correct, that line is not correctly null checking. It should be options?.SourceRange (and more). Will look to make a PR to resolve this issue soon.

Thanks for bringing this to our attention.
