### ISSUE TITLE
[QUERY] When is the next scheduled release of Azure.Monitor.OpenTelemetry.Exporter lib

### ISSUE THREAD

**Issue by franklixuefei** [Azure/azure-sdk-for-net#29078]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.3.0-beta

### Query/Question

It's been a while since the last release of this package. I wonder when is the next scheduled release? Our team really needs the latest release.
Thanks!

**Comment by reyang** [comment]
@mattmccleary who is working on the release schedule for the OpenTelemetry exporters.

**Comment by mattmccleary** [comment]
Hi @franklixuefei thx for reaching out. What specifically are you looking for in the next release?

**Comment by mmisztal1980** [comment]
@mattmccleary I for one am interested in adaptive sampling & metrics

**Comment by mattmccleary** [comment]
@mmisztal1980 We're working on metrics! Sampling is on the roadmap too.

@ciwchris We haven't published a timeline yet, but you're correct that we are working on metrics. Feel free to send me an email at mmcc@microsoft.com. If I understand your situation a bit more, I might be able to give a bit more info to help you make a decision.

**Comment by cijothomas** [comment]
If you want to try out the latest builds and share early feedbacks, you may use the daily build nugets from https://github.com/Azure/azure-sdk-for-net/blob/main/NuGet.Config#L7 . It'd be faster than cloning and building locally.

(Note that this is just for testing/exploring. The official nugets published to nuget.org are the only ones supported.)

**Comment by bartbovendeerdt** [comment]
@cijothomas there are no newer packages on that feed for the `Azure.Monitor.OpenTelemetry.Exporter`. Is that correct?

![image](https://user-images.githubusercontent.com/7485108/177529804-d61bef4d-9b49-408a-97aa-428adc6abcc9.png)

**Comment by cijothomas** [comment]
Pick the latest based on today. eg: 1.0.0-alpha.20220706.1

(this is not officially released nugets, so it does not really follow semver hence nuget does not know which one is actually the newest!)

**Comment by bartbovendeerdt** [comment]
@cijothomas Still curious to know when a new release is planned. We want to adopt OpenTelemetry based on Application Insights but it is hard to plan without a clear schedule.

**Comment by reyang** [comment]
> @cijothomas Still curious to know when a new release is planned. We want to adopt OpenTelemetry based on Application Insights but it is hard to plan without a clear schedule.

@mattmccleary would you follow up?

**Comment by cijothomas** [comment]
https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.Exporter/1.0.0-beta.4

**Comment by cijothomas** [comment]
^ new release
