### ISSUE TITLE
[mgmt]: reconsider lro polling strategy to honour user input

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-net#29072]
## Problem

We already have a customer issue regarding LRO in track1. The root cause is on the server side which doesn't return the correct `Retry-After`. However, retrospecting our track2 LRO implementation, there is one issue found: we totally ignore user input interval, thus in such cases there is no way for customers to work around.

Here is the `RetryAfterDelayStrategy`: https://github.com/Azure/azure-sdk-for-net/blob/8914c0e7076f82a95efa8a1d6cc955dd69b04c05/sdk/core/Azure.Core/src/Shared/RetryAfterDelayStrategy.cs#L41-L58

We choose the max value of `Retry-After` header and the fall-back strategy. And for mgmt, the fall-back strategy is `ExponentialDelayStrategy`: https://github.com/Azure/azure-sdk-for-net/blob/8914c0e7076f82a95efa8a1d6cc955dd69b04c05/sdk/core/Azure.Core/src/Shared/ExponentialDelayStrategy.cs#L40-L44

which ignores the user input. So there is no way for users to impact the polling interval, thus they lose the capability to remediate some cases.

**Comment by archerzz** [comment]
After discussion, we recommend resolving the issue by polling control in client side. Below is an example.

```csharp

var operation = await virtualNetworkCollection.CreateOrUpdateAsync(WaitUntil.Started, vnetName, vnet);
while (true)
{
    Thread.Sleep(TimeSpan.FromSeconds(30));
    await operation.UpdateStatusAsync();
    if (operation.HasCompleted)
    {
        break;
    }
}
```

One advantage of this solution is that for those sophisticated cases, simply honouring a constant value might not solve the problem. We already provide the API for developers to implement their own polling control. So probably the suggested changes above are not necessary.

**Comment by archerzz** [comment]
we could enhance the doc here: https://github.com/Azure/autorest.csharp/issues/2286#issuecomment-1149540473

**Comment by annelo-msft** [comment]
Has this issue been approved by .NET architects/Azure.Core team for use in data plane?
