### ISSUE TITLE
[Form Recognizer] StartRecognizeCustomFormsWithLabels(False,False) failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29086]
Form Recognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Invalid model created with ID 933ee55a-9c6a-4247-94dc-6f6e26565c81
> Status: 200 (OK)
> ErrorCode: 2011
> 
> Additional Information:
> error-0: 2011: Could not access Azure blob storage account.
> 
> Content:
> 
> Headers:
> ms-azure-ai-errorcode: REDACTED
> x-envoy-upstream-service-time: 100
> apim-request-id: 55bf965a-634b-4ff6-82c3-565f2d61aede
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Thu, 02 Jun 2022 05:56:58 GMT
> Content-Length: 296
> Content-Type: application/json; charset=utf-8
> 
> Data:
> error-0: 2011: Could not access Azure blob storage account.
> 
> 
> Stack trace
>    at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 295
>    at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 0
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 80
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 79
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 192
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 117
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 178
>    at Azure.AI.FormRecognizer.Training.CreateCustomFormModelOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\src\FormTrainingClient\CreateCustomFormModelOperation.cs:line 73
>    at Azure.AI.FormRecognizer.Tests.DisposableTrainedModel.TrainModelAsync(FormTrainingClient trainingClient, Uri trainingFilesUri, Boolean useTrainingLabels, String modelName) in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\tests\Infrastructure\DisposableTrainedModel.cs:line 56
>    at Azure.AI.FormRecognizer.Tests.FormRecognizerLiveTestBase.CreateDisposableTrainedModelAsync(Boolean useTrainingLabels, ContainerType containerType, String modelName) in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\tests\Infrastructure\FormRecognizerLiveTestBase.cs:line 133
>    at Azure.AI.FormRecognizer.Tests.RecognizeCustomFormsLiveTests.StartRecognizeCustomFormsWithLabels(Boolean useStream, Boolean includeFieldElements) in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\tests\FormRecognizerClient\RecognizeCustomFormsLiveTests.cs:line 90
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1615115&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Issue is still present but has been moved to https://github.com/Azure/azure-sdk-for-net/issues/31914.
