### ISSUE TITLE
[EventHub] CanSendAndReceive_BlobServiceUri_InConfiguration failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29085]
EventHub nightly test runs are failing with:

> Error message
> Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException : The listener for function 'EventHubTestSingleDispatchJobWithConnection.ProcessSingleEvent' was unable to start.
> ----> Azure.RequestFailedException : The value for one of the HTTP headers is not in the correct format.
> RequestId:2062737d-701e-0076-2ea5-72afe1000000
> Time:2022-05-28T15:12:43.8893240Z
> Status: 400 (The value for one of the HTTP headers is not in the correct format.)
> ErrorCode: InvalidHeaderValue
> 
> Additional Information:
> HeaderName: x-ms-version
> HeaderValue: 2021-08-06
> 
> Content:
> 
> <Error>InvalidHeaderValue<Message>The value for one of the HTTP headers is not in the correct format.
> RequestId:2062737d-701e-0076-2ea5-72afe1000000
> Time:2022-05-28T15:12:43.8893240Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2021-08-06</HeaderValue></Error>
> 
> Headers:
> Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
> x-ms-request-id: 2062737d-701e-0076-2ea5-72afe1000000
> Date: Sat, 28 May 2022 15:12:43 GMT
> Content-Length: 329
> Content-Type: application/xml
> 
> Data:
> HeaderName: x-ms-version
> HeaderValue: 2021-08-06
> 
> 
> Stack trace
>    at Microsoft.Azure.WebJobs.Host.RecoverableException.TryRecover(ILogger logger) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Exceptions\RecoverableException.cs:line 81
>    at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken, Boolean allowRetry) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 79
>    at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.StartAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 61
>    at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.StartAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\CompositeListener.cs:line 39
>    at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\ListenerFactoryListener.cs:line 47
>    at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.StartAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\ShutdownListener.cs:line 29
>    at Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 99
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.WebJobsEventHubTestBase.BuildHost[T](Action`1 configurationDelegate, Action`1 preStartCallback) in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/WebJobsEventHubTestBase.cs:line 92
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.AssertCanSendReceiveMessage(Action`1 hostConfiguration) in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubEndToEndTests.cs:line 248
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.CanSendAndReceive_BlobServiceUri_InConfiguration() in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubEndToEndTests.cs:line 208
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> --RequestFailedException
>    at Azure.Storage.Blobs.ContainerRestClient.CreateAsync(Nullable`1 timeout, IDictionary`2 metadata, Nullable`1 access, String defaultEncryptionScope, Nullable`1 preventEncryptionScopeOverride, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/storage/Azure.Storage.Blobs/src/Generated/ContainerRestClient.cs:line 94
>    at Azure.Storage.Blobs.BlobContainerClient.CreateInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken, String operationName) in /Users/runner/work/1/s/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs:line 1166
>    at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExistsInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs:line 1064
>    at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExistsAsync(Pub

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1604942&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Closing; this is due to an issue with the current Storage deployment in the canary environment.
