### ISSUE TITLE
[QUERY] Does the Function App’s Blob Trigger support reading from the secondary location automatically?

### ISSUE THREAD

**Issue by springcomp** [Azure/azure-sdk-for-net#29097]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage 5.0.1

### Query/Question

Does the blob trigger fails over the secondary read-only location if the storage account is a RA-GRS or RA-GZRS account?
If not:

- Are there any plans to include this feature?
- Are there any guidelines or pointers to simulate this ourselves?

**Comment by amnguye** [comment]
Sorry for the late response.

If a failover were to happen, then the secondary will be called.

Is the question to automatically go to the secondary instead of the primary? I believe you would have to specify the secondary instead of the primary in that case.
