### ISSUE TITLE
[BUG] Azure.Data.Tables incorrectly throws an exception when performing an UpdateEntityAsync with TableUpdateMode.Merge and "Prefer: return-content" set

### ISSUE THREAD

**Issue by pingzing** [Azure/azure-sdk-for-net#29093]
### Library name and version

Azure.Data.Tables v12.2.5.0

### Describe the bug

I made a call to `tableClient.UpdateEntityAsync()` call with `TableUpdateMode.Merge` specified. In addition, when registering the Table Client, I've specified a custom policy, that simply forces every call the TableClient includes to include a `Prefer: return-content` header, like so:

```csharp
public class PreferReturnContentPolicy : HttpPipelineSynchronousPolicy
{
    public override void OnSendingRequest(HttpMessage message) => message.Request.Headers.Add("Prefer", "return-content");
}
```

Unfortunately, it appears that in the `TableRestClient`'s `MergeEntityAsync()` method in the SDK, when it reads the response from the Table, it does not expect the `200 OK` status code that the table returns in this scenario. Instead, it only checks for `204 No Content`, and Instead of returning the successful response plus my content, throws an exception.

### Expected behavior

When updating an entity with `Prefer: return-content` enabled, I would expect to get back a success response, and not an exception.
Bonus points for also returning the contents of my update as returned by the table.

### Actual behavior

An exception is thrown.

### Reproduction Steps

When registering the TableClient:

In Program.cs
```csharp
builder.Services.AddAzureClients(clientBuilder =>
{
    clientBuilder
        .AddTableServiceClient("connectionStringGoesHere")
        .ConfigureOptions(opts =>
        {
            // Add a policy that adds the "Prefer: return-content" header so that we
            // get inserted entities back in the response.
            opts.AddPolicy(new PreferReturnContentPolicy(), Azure.Core.HttpPipelinePosition.PerRetry);
        });
});
```

PreferReturnContentPolicy.cs
```csharp
public class PreferReturnContentPolicy : HttpPipelineSynchronousPolicy
{
    public override void OnSendingRequest(HttpMessage message) => message.Request.Headers.Add("Prefer", "return-content");
}
```

SomeRepositoryClassYouDefine.cs
```csharp
// Obtain a TableServiceClient somehow...
var tableClient = TableServiceClient("SomeTableName");
var entity = new TableEntity("SomePartitionKey", "SomeRowKey") { { "SomeColumnName", "SomeColumnValue" } };
var response = await tableClient.UpdateEntityAsync(entity, ETag.All, TableUpdateMode.Merge, CancellationToken.None);
// Pow! Exception.
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @pingzing - Sorry you are encountering this issue. Although I understand the issue you are describing, could you provide an example of when you'd want the full echo response from these methods? 

For example, assuming you had previously queried the model being updated, the echo response wouldn't provide any additional data that isn't already in the client app that executed the update. The one exception is the ETag value, and that comes back in the response header.

```c#
var response = await tableClient.UpdateEntityAsync(entity, ETag.All, TableUpdateMode.Merge, CancellationToken.None);
var newETag = response.Headers.ETag
```

**Comment by pingzing** [comment]
Hi @christothes,

I can't think of any example of my use case where I'd use the returned information. However, until there is some way to set the `Prefer: no-content` header at the request level, the only way to work around this is to either
a)  Create a second TableServiceClient without the PreferReturnContentPolicy, and use that secondary client only when an update request is made
b)  Catch and swallow exceptions if the response code is `200 OK`.

I think that both of these workarounds, as well as the notion that the library throws an exception on valid input (that the underlying service acknowledges as valid), strongly violates the principle of least surprise.

If it's decided that SDK doesn't want to support this scenario, I would expect it to throw on input, rather than output.

**Comment by christothes** [comment]
Hi @pingzing 
Apologies if I missed something in your description, but could you explain why you need to set the Prefer header? It sounds like you don't need the echo content that comes with setting `return-content` and the current default is not returning content.

**Comment by pingzing** [comment]
Ah, right, I guess I never stated it outright. I'm using one `TableServiceClient` for all the requests I make to Table Storage, and I use the `Prefer` head for several other Insert/Upsert requests. Since the only way to set the header is per-`TableServiceClient` at the moment, I wind up stuck with this behavior whenever I perform a Merge Update.

As I said, I could use separate `TableServiceClient`s for different kinds of operations but that feels... silly.

**Comment by christothes** [comment]
> Ah, right, I guess I never stated it outright. I'm using one `TableServiceClient` for all the requests I make to Table Storage, and I use the `Prefer` head for several other Insert/Upsert requests. 

Why do you set the Prefer header in these cases?

**Comment by pingzing** [comment]
Two reasons:
 - So I can return an up-to-date `Timestamp` value, as generated at insert-time.
 - It often leads to simpler-to-understand control flow, rather than creating an entity at the top of the method, then returning it on success.

**Comment by christothes** [comment]
OK - I'll log this as a feature request to expose the response preference for the operations that support it, as it is not technically a bug. 

If the Prefer header is set through the parameter to the RestClient (which we don't currently expose), it will handle the response properly. In the case of MergeEntity, the spec doesn't support the Prefer header, so this sounds like a strange quirk of the service itself. [According to the REST API docs](https://docs.microsoft.com/en-us/rest/api/storageservices/setting-the-prefer-header-to-manage-response-echo-on-insert-operations), only `CreateTable` and `InsertEntity` support the Prefer header.

**Comment by pingzing** [comment]
Thanks! Glad to hear it.

> An entity's ETag provides default optimistic concurrency for update operations. The ETag value is opaque and should not be read or relied upon.

Noted! Though, given [the docs](https://docs.microsoft.com/en-us/rest/api/storageservices/update-entity2#remarks) state that "An entity's ETag provides default optimistic concurrency for update operations. The ETag value is opaque and should not be read or relied upon." I'd be a little hesitant to start interpreting the ETag like so.

**Comment by christothes** [comment]
> Thanks! Glad to hear it.
> 
> > An entity's ETag provides default optimistic concurrency for update operations. The ETag value is opaque and should not be read or relied upon.
> 
> Noted! Though, given [the docs](https://docs.microsoft.com/en-us/rest/api/storageservices/update-entity2#remarks) state that "The ETag value is opaque and should not be read or relied upon." I'd be a little hesitant to start interpreting the ETag like so.

Yes, you are totally correct. There is no guarantee that the ETag will always be the TimeStamp.  It just happens to have been that for the whole history of the service (which is a very long history 😄 )

**Comment by christothes** [comment]
closing in favor of #29105
