### ISSUE TITLE
[BUG] AzureCliCredential - Misleading error message when blocked because of conditional access policy

### ISSUE THREAD

**Issue by asanjabi** [Azure/azure-sdk-for-net#29109]
### Library name and version

Azure.Identity 1.6

### Describe the bug

If retrieving a token is blocked by conditional access policy, error message provided to the user _("Please run 'az login' to set up account")_ is misleading. In my case I can reproduce this running in a docker container and using scope "https://database.windows.net", running equivalent CLI command produces the following error message:

> : az account get-access-token --output json --resource https://database.windows.net
AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.
Trace ID: c5188e27-f425-45a3-97ba-770db9cc3e00
Correlation ID: 52fa0a7c-384c-4f38-8138-992023c79a9f
Timestamp: 2022-06-03 22:26:04Z
To re-authenticate, please run:
az login --scope https://database.windows.net/.default

The last line matches the logged in check in the code.

### Expected behavior

Better error message to help user diagnose the problem.

### Actual behavior

Exception text says "Please run 'az login' to set up account"
See bug description

### Reproduction Steps

Environment dependent,
Try getting a token that is blocked by conditional access policy.

### Environment

In my scenario:
Image: mcr.microsoft.com/dotnet/aspnet:6.0
Azure.Identity 1.6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
