### ISSUE TITLE
Integrate license header checker into build process 

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-sdk-for-net#2910]
We should fail a PR if any of the cs files miss License header.

**Comment by markcowl** [comment]
### Decsription

Add license header check to repo.

- [ ] Create license header check tool that checks c# files for license comment
- [ ] Run against the repo and fix any errors
- [ ] Add automation to execute and fail the ci build if any cs file fails the license check

### Cost: 4

**Comment by Petermarcu** [comment]
@weshaggard  @chidozieononiwu  is this already something that is covered now?

**Comment by chidozieononiwu** [comment]
This should be getting enforced by StyleCop https://github.com/Azure/azure-sdk-for-net/blob/master/eng/stylecop.json
Do you have an example where the license header is not present.

**Comment by weshaggard** [comment]
I think this work is done at least for the projects (track 2) that are opted into our StyleCheck.
