### ISSUE TITLE
[BUG] CosmosDB trigger function seems to hang and stops processing events when authenticating via MSI

### ISSUE THREAD

**Issue by Francisco-Gamino** [Azure/azure-sdk-for-net#29104]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.CosmosDB

### Describe the bug

This issue was reported by a customer. The problem started after the customer updated their app to authenticate with CosmosDB using an MSI instead of a connection string. According to the customer, the function seems to hang and stop processing events. To mitigate this issue, the customer had to manually restart the app, and after this, the app would go back to working as expected until the issue manifest it again. 

I reviewed the function executions for the function with the issue and it looks like the invocations were successful. I also reviewed the CPU usage and SNAT port exhaustion for the times when the customer had to manually restart the app from 5/30/22 18:45 to 6/2/22 18:29, and everything seems to be working as expected. For more information, please see [CRI ](https://portal.microsofticm.com/imp/v3/incidents/details/308705579/home) notes for the analysis. 

Given that MSI authentication is a preview feature, I will recommend the customer to move back to using the connection string to authenticate with CosmosDB. 

When getting ready to GA the MSI feature offering, please make sure that we do exhaustive testing for this scenario for all hosting offerings: Consumption and Dedicated (App Service Plan and Premium).

### Expected behavior

N/A

### Actual behavior

N/A

### Reproduction Steps

N/A

### Environment

N/A

**Comment by jsquire** [comment]
@Francisco-Gamino :  Please clarify the package.   This issue references the Event Hubs extensions, but the context provided here and in the IcM appears limited to CosmosDB.

**Comment by Francisco-Gamino** [comment]
> @Francisco-Gamino : Please clarify the package. This issue references the Event Hubs extensions, but the context provided here and in the IcM appears limited to CosmosDB.

Hello @jsquire -- I have added the correct package name. Thank you.

**Comment by jsquire** [comment]
Thank you for clarifying, @Francisco-Gamino.   The CosmosDB extension isn't part of this repository; I've transferred this over to where it's maintained as [#779](https://github.com/Azure/azure-webjobs-sdk-extensions/issues/779).
