### ISSUE TITLE
AZURE_REGIONAL_AUTHORITY_NAME won't work after updating to 1.6 (works in 1.5)

### ISSUE THREAD

**Issue by sadjadbp** [Azure/azure-sdk-for-net#29112]
I'm following the example [here](https://review.docs.microsoft.com/en-us/identity/microsoft-identity-platform/msal-net-regional-adoption?branch=main#providing-a-region-with-azureidentity)

```csharp
var previousRegionValue = Environment.GetEnvironmentVariable("AZURE_REGIONAL_AUTHORITY_NAME");
var regionValue = Config.AzureRegion ?? RegionalAuthority.AutoDiscoverRegion;
Environment.SetEnvironmentVariable("AZURE_REGIONAL_AUTHORITY_NAME", regionValue);

var credential = new ClientCertificateCredential(tenantId, clientId, certificate,
    new ClientCertificateCredentialOptions
    {
        AuthorityHost = PublicCloudAuthority,
        SendCertificateChain = true,
    });
Environment.SetEnvironmentVariable("AZURE_REGIONAL_AUTHORITY_NAME", previousRegionValue);
```

With Azure.Identity 1.5+MSAL 4.44.0 it works fine and if I check credentials.Client.RegionalAuthority it is set to the AzureRegion like 'westus', but if I use Azure.Identity 1.6+MSAL 4.44.0 that credentials.Client.RegionalAuthority would be null. I have tried all below combination and looks like the only culprit is Azure.Identity 1.6

1.5+4.42.1 worked
1.5+4.43.0 worked
1.5+4.43.1 worked
1.5+4.43.2 worked
1.5+4.44.0 worked

1.6+4.42.1 didn't work
1.6+4.43.0 didn't work
1.6+4.43.1 didn't work
1.6+4.43.2 didn't work
1.6+4.44.0 didn't work

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
