### ISSUE TITLE
Typo "Github"→"GitHub"

### ISSUE THREAD

**Issue by hyoshioka0128** [Azure/azure-sdk-for-net#29111]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.staticsitearmresource.repositorytoken?view=azure-dotnet

![image](https://user-images.githubusercontent.com/40815708/171974431-7f48889a-371f-4ce7-b98c-4e083666c1a1.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6011ebae-174e-945d-288d-eee66dd1f46e
* Version Independent ID: 1212bc62-a667-14db-585b-c9bec71111af
* Content: [StaticSiteARMResource.RepositoryToken Property (Microsoft.Azure.Management.WebSites.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.staticsitearmresource.repositorytoken?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.WebSites.Models/StaticSiteARMResource.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/StaticSiteARMResource.xml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Service team need to update the swagger spec for the fixing from source
