### ISSUE TITLE
[FEATURE REQ] - Completion and Complete on ServiceBusProcessor

### ISSUE THREAD

**Issue by Rayzbam** [Azure/azure-sdk-for-net#29125]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

I'm quite a big user of the TPL library because it served a lot of my issues and problematics.
Is there any possibility to have any clue on what's happening on the ServiceBusProcess instances ?

I mean, it's possible to call "StopProcessingAsync" to stop receiving messages, but what happen if it still were messages processing asynchronously (MaxConcurrentCall > 1) ? 
When i try to gracefully shutdown my service, what i would do is : 
- Stop Processing (stop receiving messages)
- Wait for processor messages that are still in progress in background
- Dispose Processors resources

In TPL library, what you can do is simply :

```
actionBlock.Complete(); // Equivalent of StopProcessingAsync on ServiceBusProcessor
await actionBlock.Completion;
```

Found an issue, which seems linked to my request : [https://github.com/Azure/azure-sdk-for-net/issues/21869](https://github.com/Azure/azure-sdk-for-net/issues/21869)

Is it embedded in the StopProcessingAsync ? The doc doesn't mention anything about work in progress, i can only see "The method will cause the receivers to stop receiving" not "and finish its work in progress".

Any thoughts ?

**Comment by JoshLove-msft** [comment]
Hi @Rayzbam,
Calling StopProcessingAsync or CloseAsync will allow in-flight processing to complete. The difference between the two methods is that StopProcessingAsync will leave the links open (in case you want to resume processing), so you would still want to call CloseAsync at some point when shutting down.

**Comment by JoshLove-msft** [comment]
Sorry if I wasn't clear, but StopProcessingAsync/CloseAsync will not return until all of your in-flight processing has completed, so there is no need to track the asks yourself.

**Comment by JoshLove-msft** [comment]
> Is that possible to add a few words in the documentation to explain that in-flight processing messages are awaited too ?

Absolutely - I will submit a PR to improve the ref docs for these methods.
