### ISSUE TITLE
should not trigger pipeline on an template file

### ISSUE THREAD

**Issue by chunyu3** [Azure/azure-sdk-for-net#29123]
Pipeline generation tool found the ci.yml file under “sdk/template/.content/testResource/ci.yml” so it created this pipeline for it. Actually the “sdk/template/.content/testResource/ci.yml”  is just template file and it is not related to an resource, so it should not trigger a pipeline.

**Comment by chunyu3** [comment]
#29122

**Comment by weshaggard** [comment]
Thanks for fixing. I deleted the pipelines that were created for this.
