### ISSUE TITLE
[BUG] Error when deserializing JWT header

### ISSUE THREAD

**Issue by mattabb** [Azure/azure-sdk-for-net#29128]
### Library name and version

System.IdentityModel.Tokens.Jwt

### Describe the bug

During JWT Token Validation, (ValidateToken function), the JSON Deserializer is throwing the following error while deserializing the JWT Header:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. File name: 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' at Microsoft.IdentityModel.Json.Serialization.JsonTypeReflector.get_DynamicCodeGeneration() at Microsoft.IdentityModel.Json.Serialization.JsonTypeReflector.get_ReflectionDelegateFactory() at Microsoft.IdentityModel.Json.Serialization.DefaultContractResolver.GetDefaultCreator(Type createdType) at Microsoft.IdentityModel.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract) at Microsoft.IdentityModel.Json.Serialization.DefaultContractResolver.CreateDictionaryContract(Type objectType) at Microsoft.IdentityModel.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType) at System.Collections.Concurrent.ConcurrentDictionary2.GetOrAdd(TKey key, Func2 valueFactory) at Microsoft.IdentityModel.Json.Utilities.ThreadSafeStore`2.Get(TKey key) at Microsoft.IdentityModel.Json.Serialization.DefaultContractResolver.ResolveContract(Type type) at Microsoft.IdentityModel.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(Type type) at Microsoft.IdentityModel.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Microsoft.IdentityModel.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Microsoft.IdentityModel.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType) at Microsoft.IdentityModel.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Microsoft.IdentityModel.Json.JsonConvert.DeserializeObject(String value, Type type) at System.IdentityModel.Tokens.Jwt.JsonExtensions.DeserializeJwtHeader(String jsonString) at System.IdentityModel.Tokens.Jwt.JwtHeader.Base64UrlDeserialize(String base64UrlEncodedJsonString) at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.Decode(String[] tokenParts, String rawData)

This is occurring despite the fact that I have System.Security.Permissions Version 6.0.0 as a NuGet package for my project.

The header of the JWT in question is as follows (Kid value is slightly changed):

{
  "alg":"RS256",
  "kid":"b8417q79-0b06-42n8-8r69-a839669f74b9",
  "typ":"JWT"
}

### Expected behavior

At a complete level, the ValidateToken function should return valid or invalid.  At a more specific level, the deserializer should correctly deserialize the JWT Header into an object.

### Actual behavior

The deserializer returns the error:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

The Decode function inside of JwtSecurityToken.cs catches the error and returns the IDX12729 message along with the above error.

### Reproduction Steps

Validate a token with the IssuerSigningKey being a RsaSecurityKey object relating to a public key, with a KeyId attached.

### Environment

Windows 11 .NET Framework 4.8

    Dependencies:
        System.Security.Permissions v6.0.0
        Microsoft.IdentityModel.Tokens v6.18.0
        
Rider 2022.1.2

**Comment by brentschmaltz** [comment]
@mattabb it seems odd to me the version is specified as 0.0.0.0. How is that getting set?

> System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified. File name: 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' at
