### ISSUE TITLE
[QUERY] Create Custom Topic with Identity via 

### ISSUE THREAD

**Issue by codeputer** [Azure/azure-sdk-for-net#29134]
### Library name and version

Microsoft.Azure.Management.EventGrid.Models.Topic

### Query/Question

I'm creating an EventGrid Topic via the EventGridManagementClient using Managed Identity (proud of that actually :)  However, I want to create it now with the user assigned managed identity....

I'm attempting to use the  Identity property on the Topic model to assign a Managed User Id to create the Topic with this all configured.  Is that possible using the latest SDK (Preview).  I noticed the documentation states the Idenity property may not be fully baked yet?

Hee is my code base:

`    static async Task CreateEventGridTopicAsync(string rgname, string topicName, EventGridManagementClient EventGridMgmtClient)
    {
      Console.WriteLine("Creating an EventGrid topic...");

      Dictionary<string, string> defaultTags = new Dictionary<string, string>
            {
                {"key1","value1"},
                {"key2","value2"}
            };

      var userIdentfierProperty = new UserIdentityProperties(clientId: "/subscriptions/xxxx/resourceGroups/EventGridTest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/EventGridManagedIdentity");
      Dictionary<string, UserIdentityProperties> userIdentityProperties = new Dictionary<string, UserIdentityProperties>();
      userIdentityProperties.Add("EventGridManagedIdentity", userIdentfierProperty);

      //add the managed user Id...
      IdentityInfo managedUserIdentityInfo = new(type: "UserAssigned", tenantId: tenantId, userAssignedIdentities: userIdentityProperties);
      managedUserIdentityInfo.TenantId = tenantId;

      Topic topic = new Topic()
      {
        Tags = defaultTags,
        Location = DefaultLocation,
        InputSchema = InputSchema.EventGridSchema,
        InputSchemaMapping = null,
        Identity = managedUserIdentityInfo
      };

      Topic createdTopic = await EventGridMgmtClient.Topics.CreateOrUpdateAsync(rgname, topicName, topic);
      Console.WriteLine("EventGrid topic created with name " + createdTopic.Name);
    }`

### Environment

local development - windows x64

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @codeputer ,
Thank you for using Azure SDK For .NET.
For the question you asked:
The latest `Microsoft.Azure.Management.EventGrid 8.0.0-preview` version support UserAssigned Identity.
There are several point in your sample need to update inorder to make it work.
```
static async Task CreateEventGridTopicAsync(string rgname, string topicName, EventGridManagementClient EventGridMgmtClient)
{
Console.WriteLine("Creating an EventGrid topic...");

  Dictionary<string, string> defaultTags = new Dictionary<string, string>
        {
            {"key1","value1"},
            {"key2","value2"}
        };

// 1. ClientId is not resource id, it is another property of the UserAssigned Identity
// 2. The proper format should be key: id, value: null 
// var userIdentfierProperty = new UserIdentityProperties(clientId: "/subscriptions/xxxx/resourceGroups/EventGridTest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/EventGridManagedIdentity");
  string id = "/subscriptions/xxxx/resourceGroups/EventGridTest/providers/Microsoft.ManagedIdentity/userAssignedIdentities/EventGridManagedIdentity"
  Dictionary<string, UserIdentityProperties> userIdentityProperties = new Dictionary<string, UserIdentityProperties>();
  userIdentityProperties.Add(id , new UserIdentityProperties());

  //add the managed user Id...
 // TenantId should be null or empty
  // IdentityInfo managedUserIdentityInfo = new(type: "UserAssigned", tenantId: tenantId, userAssignedIdentities: userIdentityProperties);
  IdentityInfo managedUserIdentityInfo = new(type: "UserAssigned", userAssignedIdentities: userIdentityProperties);
  //managedUserIdentityInfo.TenantId = tenantId;

  Topic topic = new Topic()
  {
    Tags = defaultTags,
    Location = DefaultLocation,
    InputSchema = InputSchema.EventGridSchema,
    InputSchemaMapping = null,
    Identity = managedUserIdentityInfo
  };

  Topic createdTopic = await EventGridMgmtClient.Topics.CreateOrUpdateAsync(rgname, topicName, topic);
  Console.WriteLine("EventGrid topic created with name " + createdTopic.Name);
}
```
