### ISSUE TITLE
[FEATURE REQ] Storage extensions should leverage RequestContext.ErrorOptions

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#29132]
### Library name

Microsoft.Azure.WebJobs.Extensions.Storage.*

### Please describe the feature.

Template Azure Functions with Storage bindings report a lot of log warnings at startup and in every trigger call for 404 requests. Such logs should probably have info severity.  

![MicrosoftTeams-image](https://user-images.githubusercontent.com/2347409/172234956-769b3ae0-dec6-4870-bd9a-9366a7cee666.png)

Tracing calls for Exists that end up with 404 are also represented as failures 

![image](https://user-images.githubusercontent.com/2347409/172235475-6374bf15-d529-424d-b9b0-05a4d9169e9c.png)

**Once RequestContext.ErrorOptions are implemented in Storage SDKs, WebJob extensions should leverage it to indicate when such errors should have lower log severity and no error on the tracing side.**

Related: #21511, #27645, #27792, #26327, #9934, #9908, #8320, and many other including 404/409/412 responses on blob locks, etag checks and exists calls

**Comment by lmolkova** [comment]
Related:
#27792, #26327, #9934, #9908, https://github.com/Azure/azure-functions-host/issues/8320

and many other including 404/409/412 responses on blob locks, etag checks and exists calls

**Comment by jsquire** [comment]
//cc: @kasobol-msft

**Comment by kasobol-msft** [comment]
Related:
https://github.com/Azure/azure-sdk-for-net/issues/21511
https://github.com/Azure/azure-sdk-for-net/pull/27645

**Comment by SeanFeldman** [comment]
Just a suggestion: to have a "Related issues" section under the issue description and keep all the related items right there, along with the main description of the problem.
