### ISSUE TITLE
[Flaky Test] Azure.Monitor.OpenTelemetry.Exporter.Tests.AzureMonitorExporterEventSourceTests.VerifyEventSource_Error_WithAggregateException

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#29146]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1622893&view=ms.vss-test-web.build-test-results-tab&runId=32288564&resultId=115491&paneView=debug

**Comment by TimothyMothra** [comment]
@JoshLove-msft this should be resolved now.
Please let me know if you see any more issues.

Thanks!

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft this should be resolved now. Please let me know if you see any more issues.
> 
> Thanks!

Thank you for the quick fix!
