### ISSUE TITLE
[FEATURE REQ] Refine the xml document by adding `cref` for those that are referencing something in our code

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-net#29145]
### Library name

Azure.*

### Please describe the feature.

We have quite a few cases in our xml document which is referencing something in our code, but not using the `cref`, like this:
https://github.com/Azure/azure-sdk-for-net/blob/1660eec291fea10fb590eee75eacbdeeb6f20675/sdk/anomalydetector/Azure.AI.AnomalyDetector/src/Generated/AnomalyDetectorModelFactory.cs#L40
The `LastDetectResponse` in this line is actually a name of a class in another namespace (`Models`) which should be referenced here using `cref`.

### Solution

I opened a PR in autorest.csharp [here](https://github.com/Azure/autorest.csharp/pull/2268) to solve this issue.
This PR adds `cref` in three different places.
1. It adds `cref` in the xml document of the constructor of all models, like this:
![image](https://user-images.githubusercontent.com/10554446/172521296-a54208be-df80-46d0-896b-3762a7ba1650.png)
2. It adds `cref` for all entries in the model factory:
![image](https://user-images.githubusercontent.com/10554446/172521453-040c943c-5e94-4924-9f54-c2360a163710.png)
3. It adds `cref` to the xml document of a parameter if the corresponding swagger parameter does not have a description
![image](https://user-images.githubusercontent.com/10554446/172523476-6e358b4d-8b74-448b-95b2-aecdbb5c8991.png)

I regenerate the changes, please check them out in these PRs: 
https://github.com/Azure/azure-sdk-for-net/pull/29171
https://github.com/Azure/azure-sdk-for-net/pull/29172
https://github.com/Azure/azure-sdk-for-net/pull/29173
https://github.com/Azure/azure-sdk-for-net/pull/29174
https://github.com/Azure/azure-sdk-for-net/pull/29175
https://github.com/Azure/azure-sdk-for-net/pull/29176
https://github.com/Azure/azure-sdk-for-net/pull/29177

**Comment by jsquire** [comment]
Since there haven't been objections noted and the change is non-invasive, let's move forward with this.
