### ISSUE TITLE
Duplicate H1s Conflict for system.memory.data-readme

### ISSUE THREAD

**Issue by v-alje** [Azure/azure-sdk-for-net#29199]
The following articles created from readme files are using the same H1 title header. Docs reports warnings when there are two articles with the same H1 text. This is happening because both the preview and release versions of the Docs articles were imported from the same readme: sdk/core/System.Memory.Data/README.md

https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/system.memory.data-readme-pre.md
https://github.com/Azure/azure-docs-sdk-dotnet/blob/main/api/overview/azure/system.memory.data-readme.md

One solution would be to append something like (Preview) to the end of the H1 for the preview topic when imported to Docs.

**Comment by jsquire** [comment]
Related:
- #29199  (System.Memory.Data)
- #29200 (Microsoft.Azure.Core.Spatial)
- #29201 (Microsoft.Core.Spatial)
- #29202 (Microsoft.Extensions.Azure)
- #29203 (Microsoft.Core.Spatial.NewtonsoftJson)
- #29204 (Microsoft.Batch)

**Comment by jsquire** [comment]
@danieljurek:  This seems like it would fall under the Docs export pipeline.   Would you be so kind as to triage?

**Comment by danieljurek** [comment]
These were opened to improve the quality of our docs repo by addressing warnings coming from OPS publishing. 

Our metadata publishing [already does alter the H1 content](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/common/scripts/Update-DocsMsMetadata.ps1#L98) in the readme.md files but only if it matches a [specific regex pattern](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/common/scripts/Update-DocsMsMetadata.ps1#L78): 

```regex
(\#\s+(?<filetitle>Azure .+? (?:client|plugin|shared) library for (?:JavaScript|Java|Python|\.NET|C)))
```

In these cases the H1s do not match this expression so there will be no variation by version number... 

A couple possible solutions: 

* Update the H1s in these articles to match the regex 
* Add other expressions to `Update-DocsMsMetadata.ps1` which accommodate this scenario. We'll need to know what those values are (e.g. "___ support for ____ for ___" or something like that) 

@v-alje -- do you know if we'll see this error if the duplications are across monikers? I want to know if we still need to fix this in a docs repo that uses monikers in the same way that the rest of our Azure SDK docs repos use monikers.

**Comment by sima-zhu** [comment]
The reason for the duplication like this is because it does not publish through our release pipeline. Our pipeline will add version info into title.

I manually fix the error in docs repo. We need to handle not active packages in another way, but it is not in scope of cleaning up validation errors.
