### ISSUE TITLE
Document AddAzureClientsCore extension method

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-net#29205]
### Library name

Microsoft.Extensions.Azure

### Please describe the feature.

The [`AddAzureClientsCore` extension method](https://github.com/Azure/azure-sdk-for-net/blob/583db2ec6e0083196a9db2c5c606cfb5d8ae1013/sdk/extensions/Microsoft.Extensions.Azure/src/AzureClientServiceCollectionExtensions.cs#L33) is part of the public API surface and should therefore be documented. Let's add something to the README that answers these questions:

1. What's the difference between `AddAzureClients` and `AddAzureClientsCore`?
1. When should I call one method instead of the other?

See https://github.com/bradygaster/FileNewBlazorServerToAzureContainerApps/pull/1 for a related PR from @jsquire that calls `AddAzureClientsCore`.

**Comment by JoshLove-msft** [comment]
AddAzureClientsCore can be used if you want to enable SDK logging, but you are not actually registering any clients. The more common scenario is to call AddAzureClients and configure clients that you will be using.

**Comment by jsquire** [comment]
Agreed, @JoshLove-msft.    The "logging without adding clients" was the scenario that I used it in.

**Comment by scottaddie** [comment]
@JoshLove-msft @jsquire Please review the linked docs PR ^
