### ISSUE TITLE
Fetching the highest value from CosmosDb table

### ISSUE THREAD

**Issue by woefienaam** [Azure/azure-sdk-for-net#29214]
### Library name and version

Azure.Data.Tables 12.4.0

### Query/Question

With the SDK of Azure.Data.Tables I’m trying to write a query that groups the data and fetches the highest value from each group. Is there a way to achieve this?

Currently I’m fetching all the data and executing the following LINQ query:

```
    public class SomeClass
    {
        public string CompanyName { get; set; }
        public long SomeValue { get; set; }
        public string ProperyAttribute1 { get; set; }
        public string ProperyAttribute2 { get; set; }
        public long ProperyAttribute3 { get; set; }
    }

    List<SomeClass> someList = FetchingDataFromCosmosDbTableStorage(); //fetching all the data
    var result = someList.GroupBy(x => x.CompanyName)
                         .Select(y => y.OrderByDescending(i => i.SomeValue).First())
                         .ToList();
```

Instead of filtering all the data in my application I would prefer to write a query to get the same result from CosmosDb Table.

### Environment

Hosting platform: netcoreapp3.1
IDE: Rider 2022.1.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
>     List<SomeClass> someList = FetchingDataFromCosmosDbTableStorage(); //fetching all the data
>     var result = someList.GroupBy(x => x.CompanyName)
>                          .Select(y => y.OrderByDescending(i => i.SomeValue).First())
>                          .ToList();
> ```
> 
> Instead of filtering all the data in my application I would prefer to write a query to get the same result from CosmosDb Table.

The Tables API doesn't offer any kind of query functionality around grouping or ordering. If you go to full Cosmos DB though, I believe you can do these kinds of queries.
