### ISSUE TITLE
[FEATURE REQ] Pemanent delete Blob (include blob version)

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#29213]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

For soft deleted blob, user can set deletetype = permanent to permanent delete the blob, see https://docs.microsoft.com/en-us/rest/api/storageservices/delete-blob
V12 SDK doesn't have an API to support this function (v11 SDK has the API.)

Sometimes user would like to permanent delete the blobs for some reason, like billing.
We have already get customer ask for this like Incident 311972550.
If .net sdk support it, PSH can also easily to support it.

**Comment by jsquire** [comment]
//cc: @kasobol-msft

**Comment by brainded** [comment]
+1 This would be really useful for Blob management, I don't have a way via the SDK to do this and am incurring additional costs. My specific scenario is I need to convert Append Blobs to Block Blobs to utilize Block Block lifecycle management. I still have the file so I am not concerned with keeping the original.

**Comment by seanmcc-msft** [comment]
@blueww, the Azure Arch board choice not to include Permanant Delete in the SDKs several years ago.  A very common call customers make to customer support is to undelete accidently-deleted blobs.  The Arch Board was really concerned that customers would call permanent delete by accident, and then have no way to recover their blobs.
