### ISSUE TITLE
[BUG][Storage mgmt Track2] RestoreBlobRanges' output TimeToRestore is always 1/1/0001 12:00:00 AM +00:00

### ISSUE THREAD

**Issue by yifanz0** [Azure/azure-sdk-for-net#29212]
### Library name and version

Azure.ResourceManager.Storage 1.0.0-beta.9

### Describe the bug

In RestoreBlobRanges' output, no matter what the user input of TimeToRestore is, the output TimeToRestore's value is always 1/1/0001 12:00:00 AM +00:00. This happens no matter if we put WaitUtil.Started or WaitUtil.Completed when calling the method.

### Expected behavior

For RestoreBlobRanges, the TimeToRestore in the output BlobRestoreStatus object should be the same as the TimeToRestore value specified in BlobRestoreContent object when calling RestoreBlobRanges. Say the input is 1/1/2022 15:23:03 AM +00:00, then the output should be the same. 

### Actual behavior

RestoreBlobRanges' output TimeToRestore is 1/1/0001 12:00:00 AM +00:00, but the input is not. 

![image](https://user-images.githubusercontent.com/100746763/172806392-55ef1f22-f427-4777-bd87-06450deacf7e.png)

The response returned by the server seems to be correct and has the right time:
```
GET https://management.azure.com/subscriptions/***/providers/Microsoft.Storage/locations/eastus2euap/asyncoperations/97cea899-6954-400d-8ac0-5bbbc547ff10?monitor=true&api-version=2021-08-01 HTTP/1.1
CommandName: Restore-AzStorageBlobRange
ParameterSetName: AccountName
x-ms-client-request-id: ea2a7a0a-d3aa-4912-b4ac-ce1169dc6363
x-ms-return-client-request-id: true
Authorization: Bearer ***
Host: management.azure.com


HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 277
Content-Type: application/json
Expires: -1
x-ms-client-request-id: ea2a7a0a-d3aa-4912-b4ac-ce1169dc6363
x-ms-request-id: 0818c420-1797-4b42-af4e-c0fd775fc311
Strict-Transport-Security: max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-reads: 11990
Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
x-ms-correlation-request-id: 81c45bec-795f-490f-9564-a2463e1e3e6f
x-ms-routing-request-id: SOUTHEASTASIA:20220609T080208Z:81c45bec-795f-490f-9564-a2463e1e3e6f
X-Content-Type-Options: nosniff
Date: Thu, 09 Jun 2022 08:02:07 GMT

{"status":"Complete","restoreId":"97cea899-6954-400d-8ac0-5bbbc547ff10","parameters":{"timetoRestore":"2022-06-09T07:57:41.3435008Z","blobRanges":[{"startRange":"container1/blob1","endRange":"container2/blob2"},{"startRange":"container3/blob3","endRange":"container4/blob4"}]}}
```

### Reproduction Steps

```
var restoreLro = account.RestoreBlobRanges(
                        WaitUntil.Started,
                        new Track2Models.BlobRestoreContent(
                            this.TimeToRestore,
                            PSBlobRestoreRange.ParseBlobRestoreRanges(this.BlobRestoreRange))
                        );

// Wait for result to be returned and check for TimeToRestore value. 
var result = restoreLro.WaitForCompletion().Value;
```
This is the code we use to reproduce the bug - first call the method with `WaitUtil.Started`, and then `WaitForCompletion`. However, if we use `WaitUtil.Completed`, the bug still exists. Thus it can also be reproduced by 
```
// Wait for it to return and check for TimeToRestore value 
var restoreLro = account.RestoreBlobRanges(
                        WaitUntil.Completed,
                        new Track2Models.BlobRestoreContent(
                            this.TimeToRestore,
                            PSBlobRestoreRange.ParseBlobRestoreRanges(this.BlobRestoreRange))
                        );
```

**Comment by Yao725** [comment]
Hi @yifanz0, I have double checked this issue. The root cause is that in swagger the name of this property is [timeToRestore](https://github.com/Azure/azure-rest-api-specs/blob/409af02e5ca217c7e7ec2acf50f4976c053496f8/specification/storage/resource-manager/Microsoft.Storage/stable/2021-08-01/storage.json#L4020), but the name of this property in response is `timetoRestore`, you can see that the second `t` is not capital in response so our deserialization code can't find the corresponding key value pair.

I think the best fix is to unify the behavior between backend service response and swagger spec. However, we can also consider introducing some customized code from SDK side as a temporary workaround. Feel free to leave your comments, thanks.

**Comment by blueww** [comment]
@Yao725 
Thanks for the investigation!
This works in Track1 SDK, so hope there can be some way to make this also works in Track2.
Besides that, we will inform SRP server team about this unalignement.

**Comment by Yao725** [comment]
@blueww, this can work in track 1 SDK because in track 1 we use Newtonsoft.Json, which is case-insensitive by default. We have changed the SDK code to use `timetoRestore` in serialization and deserialization and the test record prove it can work. Hope we can resolve this issue in swagger side ASAP.
