### ISSUE TITLE
Any way to use ApplicationInsights API Key to authenticate LogsQueryClient?

### ISSUE THREAD

**Issue by groogiam** [Azure/azure-sdk-for-net#29218]
### Library name and version

Azure.Monitor.Query 1.1.0

### Query/Question

I am attempting to migrate from [Microsoft.Azure.ApplicationInsights.Query](https://www.nuget.org/packages/Microsoft.Azure.ApplicationInsights.Query/) to [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query/) 

In the old library there was a authentication mechanism to use an application insights api key which could be created from the application insights api access blade. I was wondering if there is a similar mechanism to create a key for the new LogsQueryClient?

The migration guide seems to indicate we can only use an azure credential.

https://github.com/Azure/azure-sdk-for-net/issues/new?assignees=&labels=&template=03_question.yml&title=%5BQUERY%5D

Thanks.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by cairus18** [comment]
I'm on the same boat hopefully we can get an answer quickly  thanks

**Comment by ArkeBcacy** [comment]
Running into this as well. Hopefully an answer comes.

**Comment by scottaddie** [comment]
API key auth isn't supported in Log Analytics; it's an App Insights concept only. The Log Analytics team also has no plan or desire to support API keys. Customers are asked to use the newer token-based auth approach via the _Azure.Identity_ client library. For a list of supported _Azure.Identity_ token credential types, see [Credential Classes](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#credential-classes).

I'll update the migration guide to make this auth requirement clearer.

**Comment by cairus18** [comment]
Hi Scott, it would be great if you update the migration guide because the actual one isn't clear that's why it's leading us to confusion.

Thanks.

**Comment by scottaddie** [comment]
@cairus18 It's been updated. Let me know if that updated guidance is helpful.
