### ISSUE TITLE
Point to steps for resolving queue encoding issues with Functions

### ISSUE THREAD

**Issue by mattchenderson** [Azure/azure-sdk-for-net#29216]
### Library name

Microsoft.Azure.WebJobs.Extensions.Storage.Queues

### Please describe the feature.

Microsoft.Azure.WebJobs.Extensions.Storage.Queues v4 (built on v11 storage SDK) assumes a base64 encoding as this was the behavior of the QueueClient at that time.

However, the current QueueClient [defaults to no encoding](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.Storage.Queues#message-encoding), but the new v5 Functions extension for Queues still expects base64. This means that there are scenarios where there will be an encoding mismatch. We should catch that error, and when surfacing it to the user, we should point to documentation that describes the valid setups and what change they might need to make.

This is most commonly seen with a QueueTrigger responding to messages that have been written by a QueueClient, both at latest versions. The remediation then would be a host.json configuration flag on the Functions side to work with no encoding, or to change `QueueClientOptions.MessageEncoding` on the sender side.

**Comment by jsquire** [comment]
//cc: @seanmcc-msft
