### ISSUE TITLE
[Service Bus] ClaimCheck failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29226]
Service Bus nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : The value for one of the HTTP headers is not in the correct format.
> RequestId:ca74310c-901e-00e0-16eb-7b75b8000000
> Time:2022-06-09T10:29:58.0456994Z
> Status: 400 (The value for one of the HTTP headers is not in the correct format.)
> ErrorCode: InvalidHeaderValue
> 
> Additional Information:
> HeaderName: x-ms-version
> HeaderValue: 2021-08-06
> 
> Content:
> 
> <Error>InvalidHeaderValue<Message>The value for one of the HTTP headers is not in the correct format.
> RequestId:ca74310c-901e-00e0-16eb-7b75b8000000
> Time:2022-06-09T10:29:58.0456994Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2021-08-06</HeaderValue></Error>
> 
> Headers:
> x-ms-request-id: ca74310c-901e-00e0-16eb-7b75b8000000
> Content-Length: 329
> Content-Type: application/xml
> Date: Thu, 09 Jun 2022 10:29:57 GMT
> Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
> 
> Data:
> HeaderName: x-ms-version
> HeaderValue: 2021-08-06
> 
> 
> Stack trace
>    at Azure.Storage.Blobs.ContainerRestClient.<CreateAsync>d__8.MoveNext() in D:\a\_work\1\s\sdk\storage\Azure.Storage.Blobs\src\Generated\ContainerRestClient.cs:line 94
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.Storage.Blobs.BlobContainerClient.<CreateInternal>d__53.MoveNext() in D:\a\_work\1\s\sdk\storage\Azure.Storage.Blobs\src\BlobContainerClient.cs:line 1192
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.Storage.Blobs.BlobContainerClient.<CreateIfNotExistsInternal>d__52.MoveNext() in D:\a\_work\1\s\sdk\storage\Azure.Storage.Blobs\src\BlobContainerClient.cs:line 1082
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.Storage.Blobs.BlobContainerClient.<CreateIfNotExistsAsync>d__50.MoveNext() in D:\a\_work\1\s\sdk\storage\Azure.Storage.Blobs\src\BlobContainerClient.cs:line 938
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Azure.Messaging.ServiceBus.Tests.Samples.Sample10_ClaimCheck.<ClaimCheck>d__0.MoveNext() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Samples\Sample10_ClaimCheck.cs:line 25
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Messaging.ServiceBus.Tests.Samples.Sample10_ClaimCheck.<ClaimCheck>d__0.MoveNext() in D:\a\_work\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Samples\Sample10_ClaimCheck.cs:line 87
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1630399&view=results

@jsquire for notification.

**Comment by JoshLove-msft** [comment]
Seems to be related to the new service version for Storage that is not yet rolled out to all regions. This error should resolve itself once the service rolls out to all regions.

**Comment by JoshLove-msft** [comment]
This is no longer occuring.
