### ISSUE TITLE
Method documentation incorrect for polymorphic input

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#29229]
Using my DPG-generated client, the method documentation only lists the discriminator for the input:

<img width="519" alt="image" src="https://user-images.githubusercontent.com/1532486/172986985-6072d371-5fcd-489b-819e-7ffc56ba4bb3.png">

Using swagger https://raw.githubusercontent.com/Azure/azure-rest-api-specs/e7f37e4e43b1d12fd1988fda3ed39624c4b23303/specification/cognitiveservices/data-plane/Language/preview/2022-05-15-preview/analyzeconversations-authoring.json.

**Comment by annelo-msft** [comment]
This will be addressed as part of https://github.com/Azure/autorest.csharp/issues/2288.

**Comment by heaths** [comment]
Just my $0.02 from an objective user perspective, but this might be good to try to fix before DPG 1.0 GA since we don't yet generate models and this documentation will be even more important. Alternatively, if the `input-file`(s) are URIs, is it possible we could determine what the REST API docs URI would be (there is a pattern - I'm not just sure it's good enough off hand) and at least include a link to it as "More Information" or something?

**Comment by annelo-msft** [comment]
Yes, https://github.com/Azure/autorest.csharp/issues/2288 blocks DPG 1.0 GA.

Links to REST API docs is a requirement of the larger GA-blocking issue: https://github.com/Azure/autorest.csharp/issues/2239

**Comment by chunyu3** [comment]
Hi @heaths , the swagger used should be https://raw.githubusercontent.com/Azure/azure-rest-api-specs/e7f37e4e43b1d12fd1988fda3ed39624c4b23303/specification/cognitiveservices/data-plane/Language/preview/2022-05-15-preview/analyzeconversations.json right?

And this issue will be resolved in https://github.com/Azure/autorest.csharp/issues/2288. PR https://github.com/Azure/autorest.csharp/pull/2305

**Comment by heaths** [comment]
Looking at `main`, I don't see the expected change. In various places, it's still just the base properties including - and sometimes limited to - the discriminator:

https://github.com/Azure/azure-sdk-for-net/blame/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/Generated/ConversationAuthoringClient.cs#L2538

/cc @annelo-msft

**Comment by chunyu3** [comment]
> Looking at `main`, I don't see the expected change. In various places, it's still just the base properties including - and sometimes limited to - the discriminator:
> 
> https://github.com/Azure/azure-sdk-for-net/blame/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/Generated/ConversationAuthoringClient.cs#L2538
> 
> /cc @annelo-msft

Hi @heaths current we only support the top-level polymorphic, which is that the polymorphic of request/response schema payload. So the problem you mentioned in the issue has resolved.
But there is a field 'prediction' of request/response which is polymorphic, it is the inner polymorphic, we does not support to spread the inner polymorphic.
@annelo-msft  Shall we support inner-polymorphic spread? if so, we need to define the layout since it is a field of the request/response payload.

**Comment by lirenhe** [comment]
I suggest the support for inner-polymorphic could be an improvement in DPG 1.1 as we need to design how the layout would be.
I remove the label of 'DPG/RLC 1.0' and @annelo-msft, please let me know if you have any comments. Thanks

**Comment by annelo-msft** [comment]
Yes, defining the requirements for nested polymorphic types is a v1.1 feature.  https://github.com/Azure/azure-sdk-for-net/issues/28962#issue-1247187851

**Comment by lirenhe** [comment]
Based on today's discussion, we will move the support for nested polymorphic types out of v1.1

**Comment by pallavit** [comment]
@lirenhe not sure if this issue is still valid, could you please help triage.

**Comment by lirenhe** [comment]
@pshao25, could you take a look?

**Comment by pshao25** [comment]
The schema part was removed on My 6th 2023. So this is not valid.
