### ISSUE TITLE
[Core] Windows2019_NET60_PackageRef_Debug failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29224]
Core nightly test runs are failing with:

>Error message
 [error]The job running on agent azsdk-pool-mms-win-2019-general 33 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1630457&view=results

@jsquire for notification.

**Comment by annelo-msft** [comment]
Closing, as this pipeline is no longer included in the Core standard pipelines.
