### ISSUE TITLE
[QUERY] Create a managed disk with ARM64 architecture

### ISSUE THREAD

**Issue by kiryvl** [Azure/azure-sdk-for-net#29235]
### Library name and version

Azure.ResourceManager.Compute 1.0.0-beta.8 

### Query/Question

Hi,
Are there any plans to add support for ARM64 architecture while creating a managed disk?
Or is there any workaround to accomplish this?

It's possible to do with Az PowerShell like:
`New-AzDiskConfig -Architecture Arm64 <...>`
But I need to do this with the SDK for .NET.

### Environment

Azure Functions App

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@kiryvl, yes, it will be supported in the new version which will be released in this month

**Comment by ArthurMa1978** [comment]
The new lib is here https://www.nuget.org/packages/Azure.ResourceManager.Compute

**Comment by kiryvl** [comment]
@ArthurMa1978 I integrated the new version and it solved the problem. Thank you!
