### ISSUE TITLE
[QUERY] Correlating Blob Storage EventGrid Events with SAS Token

### ISSUE THREAD

**Issue by stephanrettberg** [Azure/azure-sdk-for-net#29239]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Query/Question

Is there a mechanism currently available to correlate Blob Storage EventGrid events with the SAS token that generated the event? 

Our system allows users to upload data directly to cloud storage and we need to track their actions. Ideally we would be able to set a unique identifier when generating a SAS token that would be present in the event payload whenever the token is used.

CorrelationId seemed like it may be an option, but I'm not seeing how to get that into the event payload. Is there a way to set ClientRequestId?

**Comment by stephanrettberg** [comment]
Any update? This is currently blocking us.

**Comment by amnguye** [comment]
Thanks for your patience.

I'm unsure how Event Grid interacts with Azure Storage and how to apply the Correlation Id parameter of the SAS from Event Grid.

You can set the correlation id from the SDK via the BlobSasBuilder
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.sas.blobsasbuilder.correlationid?view=azure-dotnet

I don't believe that the client request id would be a good fit for your scenario, considering that the client request id is not signed in the string to sign for the SAS.

**Comment by PramodValavala-MSFT** [comment]
@stephanrettberg I suppose if you use the same ID both in the `CorrelationId` property and as the Client Request ID (by setting the `x-ms-client-request-id` header), you could link the event back to the SAS provider. @amnguye Could you confirm if that is an option?

**Comment by stephanrettberg** [comment]
@amnguye We've tried setting the CorrelationId. The problem is that this value is not present in the Blob Storage Event Grid payload, so there's no way for us to tell who generated the event. Is there anyone from the Storage or Event Grid teams that can confirm if the correlationId can be included in the Event Grid payload or accessed by some other means?

@PramodValavala-MSFT Are you saying that our clients should set the `x-ms-client-request-id` when using the SAS? This is not ideal because we'd be relying on them to set headers properly in order for us to track their actions.

**Comment by amnguye** [comment]
@jsquire Can you help us find someone that can chime in about Event Grid here and this customer's scenario?

**Comment by jsquire** [comment]
I believe that @jfggdl would be the right contact for Event Grid.

**Comment by jfggdl** [comment]
@amnguye, it seems that @stephanrettberg wants to track who uploaded, updated, etc. to an Azure Blob by means of using Shared Access Signatures (SAS) tokens that represent the identity of that "who/org". There is a need to track that through Event Grid.  That is, an attribute should be present as a context attribute or in the [event data or event object](https://learn.microsoft.com/en-us/azure/event-grid/event-schema-blob-storage?tabs=event-grid-event-schema#event-properties). Event Grid can be thought of a pipe. It delivers what it receives as HTTP payload. I believe that a solution that is not dependent on the user setting some id (the tracking would depend on the accuracy of that gesture) should come in the form of  Azure Storage adding some ID that can enable the tracking according to the SAS identify provided when they interacted with Azure Storage. Then, update the event data for Blob events or add a new extension attribute on the event.  I am available if we want to meet with @stephanrettberg  to confirm requirements and potential solution.

**Comment by amnguye** [comment]
Rereading through this github issue, this issue / query is unrelated to the Storage SDK. It's more of an ask / query on the Storage Service / Event Grid.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

@stephanrettberg  @jfggdl feel free to follow up offline to talk through the scenario and a potential solution.

Closing this issue.

**Comment by amnguye** [comment]
Reopening issue.
