### ISSUE TITLE
[FEATURE REQ] Please add more control over entity serialization/deserialization in Azure.Data.Tables

### ISSUE THREAD

**Issue by matty-hall** [Azure/azure-sdk-for-net#29257]
### Library name

Azure.Data.Tables

### Please describe the feature.

The current pattern for entity serialization/deserialization (to and from requests) is substantially less powerful that it was in the older library (i.e. via EntityResolver<T>). Trying to approximate that approach using the new model results in a number of allocations, which really add up when reading/writing a lot of entities. As an example, here's the current flow for reading:

1. Create a JsonDocument to read the response
2. Create a Dictionary<string, object> into which the JSON properties and their values are read
3. Allocate a TableEntity (and its backing Dictionary<string, object>)
4. Walk the JSON dictionary, removing the OData annotations and copying from the JSON dictionary into TableEntity's own dictionary
5. Allocate a non-TableEntity domain object
6. Dig into the TableEntity's dictionary to find and materialize the things you need onto your non-TableEntity domain object

In an ideal world, the methods that read entities could be passed an interface that converted from JsonDocument directly to a T (with no need for type constraints on T at all). This would remove two dictionary allocations and the allocation of TableEntity itself.

A similar thing exists in reverse when writing entities for Add/Update/Upsert/etc.

1. Allocate a non-TableEntity domain object
2. Allocate a TableEntity (and its backing Dictionary<string, object>) and call a method on your domain object to serialize itself to a TableEntity.
3. Allocate a second Dictionary<string, object>
4. Walk the key value pair in the TableEntity's dictionary, ignoring things like ETag/Timestamp, converting the values, and adding OData annotations.
5. Write to JSON in the request

Here again, an interface that took the domain object directly and wrote out its JSON would avoid the same allocations (two dictionaries and the TableEntity itself).

All of this could be accomplished with something as simple as the following (with overloads to Get/Query/Add/Update/Upsert that took them), neither of which require any type constraints on their T's:

```
public interface ITableEntityDeserializer<T>
{
      T Deserialize(JsonDocument document);
}

public interface ITableEntitySerializer<T>
{
    void Serialize(Utf8JsonWriter jsonWriter, T entity);
}
```

Another nice thing about this approach is that it's much easier to support polymorphic entity types (so long as they share some base class T). During deserialization, an implementation of ITableEntityDeserializer can inspect the properties of the object as part of its decision about which type to return, which requires far more effort with the current API. This could also be done without changing the current API since the steps I outlined above could be entirely hidden behind an implementation of those interfaces that the existing methods use. If you're uncomfortable with the JSON details leaking into the interface, I'd even be happy with a similar approach that change the signature to use Dictionary's since that would at least allow me to skip the TableEntity and its internal dictionary allocation entirely.

**Comment by Pablo1q** [comment]
Hey.. I Just try other way for see about my job. /, its very slow now!!,
So ; did you fix everything?

**Comment by Pablo1q** [comment]
Work is serious. Can you manage again?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @matty-hall - Thanks for the feedback.

Is the primary motivation driving the need for customizable serialization to decouple your model types from `ITableEntity` or are there other reasons driving the need to control serialization? It would be greatly appreciated if you could describe how you would use it or how you used it previously in the old SDK.
