### ISSUE TITLE
[BUG] Azure.Data.Tables.TableOdataFilter has incorrect handling for binary data

### ISSUE THREAD

**Issue by matty-hall** [Azure/azure-sdk-for-net#29256]
### Library name and version

Azure.Data.Tables

### Describe the bug

The implementation of Azure.Data.Tables.TableOdataFilter.Create has incorrect handling for binary data. It formats such values as:

X'[data]'

Where "data" is concatenation of calls of ToString("D2") on the bytes in the incoming data. This serializes the bytes a decimal values rather than hexadecimal, which is incorrect (the X prefix is the indicator that it should be in hex and this is the behavior of the old library)

### Expected behavior

The output should be hexadecimal digits

### Actual behavior

The output is instead decimal digits.

### Reproduction Steps

byte[] buffer = new byte[] { 0x00, 0x01, 0xA0, 0xFF };
string foo = TableClient.CreateQueryFilter($"{buffer}");

The output of this is: X'0001160255'
The output should be: X'0001A0FF'

**Comment by X-GitHub-De1ivery** [comment]
Wow

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
