### ISSUE TITLE
[BUG] Azure.Data.Tables.TableConstants.Odata.EdmBoolean's definition has a typo

### ISSUE THREAD

**Issue by matty-hall** [Azure/azure-sdk-for-net#29255]
### Library name and version

Azure.Data.Tables 12.6.0

### Describe the bug

Azure.Data.Tables.TableConstants.Odata.EdmBoolean is defined as:

internal const string EdmBoolean = "E**md**.Boolean";

Notice that it's "Emd" rather than "Edm"

### Expected behavior

It should be defined as "Edm.Boolean"

### Actual behavior

It's incorrectly defined as "Emd.Boolean"

### Reproduction Steps

Look at the source

### Environment

N/A

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
