### ISSUE TITLE
[FEATURE REQ] Consider adding a convenience layer to preprocess parameters in deployment

### ISSUE THREAD

**Issue by Yao725** [Azure/azure-sdk-for-net#29261]
### Library name

Azure.ResourceManager.Resources

### Please describe the feature.

See the details in this issue: https://github.com/Azure/azure-sdk-for-net/issues/29090

**Comment by ucheNkadiCode** [comment]
I do believe this would be a nice touch to add especially for someone's pipeline and to clean up code to grab the "parameters" key out of ARM-schema files

**Comment by Yao725** [comment]
We decided to respect the requirements from the [API spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json#L4570-L4573) and not to support it in .NET SDK.
