### ISSUE TITLE
CertificateCloudCredentials lost in Microsoft.Azure.Common v2.1.1

### ISSUE THREAD

**Issue by schuettecarsten** [Azure/azure-sdk-for-net#2926]
Type CertificateCloudCredentials is lost in Microsoft.Azure.Common v2.1.1 without any information?

**Comment by cormacpayne** [comment]
@schuettecarsten Hey Carsten, we are tracking the status of this problem in issue https://github.com/Azure/azure-sdk-for-net/issues/2931

I'm going to close this issue in favor of the one we have opened. Please let me know if you have any other questions or concerns.
