### ISSUE TITLE
Allow doc additions to DPG-generated methods

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#29277]
For protocol methods like in PR #29144, we'd like to document that clients should always set the `stringIndexType` property to "Utf16CodePoint" for .NET strings. We can do this with models, but if they don't do it for .NET the string offset and length may not come back correctly.

It would be great if we could somehow add a `<remarks>` section, which the generator doesn't generate now (just summary, param, and exception sections). Off hand, I don't have any ideas. At worst, maybe an `x-ms-remarks` extension for autorest.csharp?

Even when we have models and default this for .NET - either with `x-ms-client-default` or like we did for the Question Answering HLC SDK  - this would still be important for the protocol methods.

**Comment by pallavit** [comment]
@heaths do you still see value is doing this?

**Comment by heaths** [comment]
Yes, and I think we need a TypeSpec way to do this as well, though maybe client TSPs can accomplish that. @m-nash? For context, basically I want to be able - through client customizations or something - "attach" language-specific (or even generic, non-REST) docs without having to override the method just to add my own documentation.
