### ISSUE TITLE
[FEATURE REQ] Support multiple host names on Application Gateway listeners

### ISSUE THREAD

**Issue by donald93** [Azure/azure-sdk-for-net#29270]
### Library name

Microsoft.Azure.Management.Fluent 1.38.1

### Please describe the feature.

 Azure App Gateway listeners support the ability to add multiple host names to a single listener.

![image](https://user-images.githubusercontent.com/2908344/173437566-79a5fc12-02a8-463b-b2f1-fcefc49995b3.png)

Right now it's only possible to add a single host name to a listener via the `WithHostName` function. I'd like to be able to create more advanced listeners that use multiple host names to support my applications.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @donald93 
Azure Fluent is SDK is under low maintenance, you could migrate to our new .NET SDK https://www.nuget.org/packages/Azure.ResourceManager.Network
