### ISSUE TITLE
RecoveryServicesClient methods are internal.

### ISSUE THREAD

**Issue by johnwc** [Azure/azure-sdk-for-net#2928]
The constructors for [RecoveryServicesClient](https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/RecoveryServices/Microsoft.Azure.Management.RecoveryServices/Generated/RecoveryServicesClient.cs) are all marked as internal, so they can't be used at all.  Is this on purpose?

**Comment by cormacpayne** [comment]
@johnwc Hey John, this is a known issue that is currently being worked on by the RecoveryServices team.

I will assign this to @dragonfly91 for future updates.

**Comment by pvrk** [comment]
@Siddharth7 to take a look

**Comment by pvrk** [comment]
@AdityaTulasi to take a look

**Comment by adrianhall** [comment]
Is this still an issue?
