### ISSUE TITLE
Remove deprecated track 1 Search packages from builds and live testing

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#29299]
### Library name

Azure.Search

### Please describe the issue.

Since Track-1 Search packages are deprecated, remove them from builds and live testing.

For more details see - https://www.nuget.org/packages/Microsoft.Azure.Search
![image](https://user-images.githubusercontent.com/45216704/173664984-6aa1f0dd-e05a-4770-8086-223c337ebf32.png)

Update https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/service.projects file
Refer - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/service.projects

**Comment by pallavit** [comment]
Related #29190
