### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by kennetherland** [Azure/azure-sdk-for-net#29304]
### Library name and version

Azure.AI.Language.Conversations 1.0.0-beta.3

### Query/Question

I'm reading the README.md here:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples/Sample1_AnalyzeConversation_ConversationPrediction.md

I installed Azure.AI.Language.Conversations 1.0.0-beta.3

Sample has as such:
`
Response response = await client.AnalyzeConversationAsync(RequestContent.Create(data));
`

but package has as such:

`
public virtual Task<Response<AnalyzeConversationTaskResult>> AnalyzeConversationAsync(string utterance, ConversationsProject project, AnalyzeConversationOptions options = null, CancellationToken cancellationToken = default);
`

Please advise.  Thanks.

### Environment

 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

**Comment by kennetherland** [comment]
Realized the api has evolved away from raw json to strongly typed parameters.  Just need to update your docs.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
For all our SDKs, the documentation in main may not - and in this case doesn't - match the currently published documentation; however, the documentation link from the nuget package and page *should* take you to the appropriately tagged documentation  but I see it doesn't. All the links in the README reference the `main` branch.

I'll open a separate issue to track this for all our SDKs. In the meantime, please see https://github.com/Azure/azure-sdk-for-net/tree/Azure.AI.Language.Conversations_1.0.0-beta.3/sdk/keyvault/Azure.Security.KeyVault.Secrets/samples. We'll be publishing new packages soon as well, so for some functionality - like the APIs in this 1.0.0 package - will be fixed and immutable going forward. Still, new APIs like we've added to our 1.1.0 beta (that `main` shows now) could change so all our packages should linked to appropriate documentation.
