### ISSUE TITLE
Dependency diagnostics comes as Traces with severity level normal in Application Insights

### ISSUE THREAD

**Issue by marksolbergerbjorkerot** [Azure/azure-sdk-for-net#29312]
### Library name and version

Azure.Data.Tables 12.5.0

### Query/Question

This question pertains the use of logging to Application Insights through DiagnosticSource in the new Data/Storage SDKs and how logs are defined in Application Insight.

I have an Azure Functions running as a .NET Core 3.1 app on runtime-version 3 using the legacy Microsoft.Azure.Storage-client libraries for table/queue/blob operations. In this application runtime state, all operations on these infrastructure services where logged as Dependencies in the connected Application Insights.

After upgrading the use of client-libraries to the new Azure.Storage.Blob/Queue and Azure.Data.Tables SDKs, the operations no longer are shown as Dependencies but only comes as Traces with Severity level Information. All other things as configuration on the function host regarding logging is unchanged.

Is there a setting/SDK dependency that could be reason for this behaviour?

### Environment

Azure Function
Function runtime version: 3.7.1.0
App .NET version: .NET Core 3.1

**Comment by jsquire** [comment]
@lmolkova:  Would you be so kind as to offer your thoughts and redirect as needed?

**Comment by lmolkova** [comment]
@marksolbergerbjorkerot, thank you for reporting this!

Can you please add a few more details
- versions of all dependencies
- AppInsights configuration in host.json
- do you have any additional ApplicationInsights configuration at startup?
- how do you configure logging?
 
Or perhaps you can share the repro app?

I tried to repro, but it works for me for template BlobTrigger with Table output: I can see requests and dependencies to blobs and tables reported properly

Here's how my Function looks like:

**Azure dependencies:**
```xml
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Blobs" Version="5.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Tables" Version="1.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
  </ItemGroup>
```

**Function:**

```csharp
[FunctionName("Function1")]
[return: Table("func")]
public static MyPoco Run([BlobTrigger("samples/{name}")]Stream myBlob, string name, ILogger log)
{
    log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
    return new MyPoco
    {
        PartitionKey = "Http",
        RowKey = Guid.NewGuid().ToString(),
        Text = name
    };
}
```

**host.json**
```json
"logging": {
        "applicationInsights": {
            "samplingSettings": {
                "isEnabled": true,
                "excludedTypes": "Request"
            }
        }
    }
```

**Here's what I see in AppInsights:**

![image](https://user-images.githubusercontent.com/2347409/173906145-313fda61-f9cb-44fc-8bb5-e5cd1644cd97.png)

**Comment by marksolbergerbjorkerot** [comment]
Thank you so much for a quick response and sorry for my late one.

Comparing your setup to ours, they are quite similar, however one difference is that there are only use of the SDK Queue-trigger/bindings on the function, and other SDK use of table/blob functionality is done by data/table persistence logic through regular data services/repository classes.

**The azure dependencies for the function are:**

```

    <PackageReference Include="Azure.Identity" Version="1.6.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="5.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage.Queues" Version="5.0.1" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.11" />

```

**host.json**
The logging configuration difference here is that we have not done a explicit configuration of the applicationInsights.isEnabled value, since the default through AF is true.
We don't do any other additional ApplicationInsights configuration at startup and logging levels are configured in host.json.

```
"logging": {
    "logLevel": {
      "default": "Information",
      "Host.Results": "Information",
      "Function": "Information",
      "Host.Aggregator": "Trace"
    }
  }
```

One note: we have converted another very similar AF with identical logging configuration and use of storage logic in the SDK (.NET Core 3.1 app on runtime-version 3)  to .NET 6 and runtime version  4, and here the logging becomes correct.
![image](https://user-images.githubusercontent.com/51411869/176427330-0b0f4f83-f930-4c57-a49b-8af308400d6b.png)

**Comment by lmolkova** [comment]
@marksolbergerbjorkerot 

> No - we don't see any trigger dependencies (like from the function queue-binding trigger).

The trigger telemetry for Azure Storage Queues is coming from Azure Function/WebJobs itself, which means that telemetry collection is broken between Application Insights and Functions. It may happen because of some configuration or dependencies that you have. I'm going to transfer this issue to [webjobs repo](https://github.com/Azure/azure-webjobs-sdk).

The traces (logs) that you see are info logs from Azure SDKs that are written for HTTP requests. you can control them with log level `Azure.Core`, so this seems fine.

**Comment by lmolkova** [comment]
@RohitRanjanMS can you please take a look from the Functions/WebJobs perspective?

Summary:
- Function v3 doesn't report requests or dependencies to Application Insights, however, traces (logs) come through
- It used to work with legacy extensions, but with new extensions and new Azure Storage Queue/Tables bindings, it doesn't work anymore. However, the queue trigger requests are not instrumented by SDK and come from Functions alone. 
- Based on the info provided so far, I couldn't repro the issue, so I suspect there might be some extra dependency or some unrelated configuration that breaks tracing.

**Comment by RohitRanjanMS** [comment]
Thanks @lmolkova I will have a look at this today.

**Comment by pallavit** [comment]
@RohitRanjanMS given the above comments , I am marking the issue addressed. Please let us know if you need further assistance.
