### ISSUE TITLE
Fixes to Hyak-based Azure Common libraries

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2931]
- [ ] Verify and fix the net45 target
- [ ] Assess Microsoft.Azure.Common.NetFramework library and decide whether classes are necessary,, and for necessary classes, wheether they can be moved into the Microsoft.Azure.Common library

### Cost: 4

**Comment by TheTrench** [comment]
Can the 2.1.1 release be removed from NuGet since the loss of CertificateCloudCredentials breaks working code?

**Comment by markcowl** [comment]
This is fixed in 2.1.2
