### ISSUE TITLE
[Service Bus Extension] PeekMessage method on ServiceBusReceiveActions

### ISSUE THREAD

**Issue by akakaule** [Azure/azure-sdk-for-net#29313]
### Library name

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Please describe the feature.

I have library code written using Microsoft.Azure.WebJobs.Extensions.ServiceBus v4.1.0 that need to be able to recieve and/or peek a deferred message to check if it does exists or not. All the primitives needed was accessible from IMessageSession. 

With Microsoft.Azure.WebJobs.Extensions.ServiceBus v5.5.1 I can use ServiceBusReceiveActions to recieve a deferred message, but there's no method for peeking a method. Instead one need create a ServiceBusReceiver that have the PeekMessageAsync method. 

I would suggest that the ServiceBusRecieveActions had an PeekMessage method added.

Code using v4.1.0

```
[FunctionName("ReceiveMessage")]
public async Task Run([ServiceBusTrigger(queueName, queueName, Connection = "AzureWebJobsServiceBus", IsSessionsEnabled = true)]
	Message message, 
	IMessageSession messageSession)
{
	try
	{
		var deferredMessage = await messageSession.ReceiveDeferredMessageAsync(<sequenceNumber>);
		// Handle deferred message
	}
	catch (Exception ex)
	{
		var peekDeferred = await messageSession.PeekBySequenceNumberAsync(<sequenceNumber>);¨
		// Check to see if method does exists and locked by another process
	}
	await messageSession.CompleteAsync(message.SystemProperties.LockToken);
}
```

Code using v5.5.1

```
[FunctionName("ReceiveMessage")]
public async Task Run([ServiceBusTrigger(queueName, queueName, Connection = "AzureWebJobsServiceBus", IsSessionsEnabled = true)]
	ServiceBusReceivedMessage message,
	ServiceBusSessionMessageActions sessionActions,
	ServiceBusReceiveActions receiveActions)
{
	await using var client = new ServiceBusClient(connectionString);
	ServiceBusReceiver serviceBusReceiver = client.CreateReceiver(queueName, queueName);	
	try
	{
		var receivedDeferredMessages = await receiveActions.ReceiveDeferredMessagesAsync(new long[] { <sequenceNumber> });
		var deferredMessage = receivedDeferredMessages.ToList().FirstOrDefault();
		// Handle deferred message
	}
	catch (Exception ex)
	{
		var peekDeferred = await serviceBusReceiver.PeekMessageAsync(<sequenceNumber>);
		// Check to see if method does exists and locked by another process
	}
	await sessionActions.CompleteMessageAsync(message);
}
```

The variable queueName is a const with the name of a topic / subscription. < sequenceNumber > is the sequence number of a deferred message in that subscription.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by aliqaryan2** [comment]
I have the same problem with the new package and `ServiceBusReceiveActions` binding parameter. Are there any updates on this? PLEASE

**Comment by jsquire** [comment]
Related: #30887
