### ISSUE TITLE
Documentation links in packages' READMEs, samples should reference tagged locations

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#29327]
Related to https://github.com/Azure/azure-sdk-for-net/issues/29304#issuecomment-1156802781, our links to samples in our language repo from both the nuget.org-rendered README as well as the samples browser all reference the `main` branch. For beta features, this can present a lot of confusion since the samples may not match the currently-published package (release or beta).

Could we do a local edit during the build pipeline to used tagged links before `dotnet pack` and during docs ingestion, for example?

/cc @scbedd @weshaggard

**Comment by weshaggard** [comment]
cc @sima-zhu 

We do a main replace with release tag link in our documentation publishing process but we have been hesitant to mutate files going into our packages as part of the process. If we mutate them as part of our release process then folks building our packages locally will get a different result. I realize these are just side files but it is generally a good practice to not mutate these files that are going into our shipping artifacts. There is also the smaller challenge that we will need to guess at what the release links before they actually exist so there will always be a risk they don't exist and they will definitely be at least some time where they will be invalidate until the full release has completed.

**Comment by heaths** [comment]
Thanks for clarity on mutation files in the packages. Makes sense.

Samples browser's README.md also has links to `main`, though: https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azureailanguageconversations-samples/

**Comment by heaths** [comment]
Thinking about this more, perhaps samples browser is the solution: as long as the links get fixed there (if they can even be versioned), our Samples link we have in all our READMEs could point to that instead of GitHub. Delegate the version handling (if even possible) to Samples Browser.

**Comment by heaths** [comment]
Do we have a contact we can ping?

**Comment by scbedd** [comment]
@heaths I'll ping an email to you offline.
