### ISSUE TITLE
Verify runtime fixes for protected model property setters in autoirest-generated clients

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2932]
The PR here: https://github.com/Azure/azure-sdk-for-net/pull/2915 fixes the issue

- [x] Verify the fix with an end-to-end test using get -> put for VMs in the latest compute library - add this as a test to existing compute tests
- [x] Once verified, merge the changes (along with these changes:https://github.com/Azure/azure-sdk-for-net/pull/2855 ) and publish the library

**Comment by shahabhijeet** [comment]
PR# https://github.com/Azure/azure-sdk-for-net/pull/2945
Waiting for the PR to be merged. But consider this done.
