### ISSUE TITLE
Determine when and when not to generate `Get*Status` methods for LROs/VLROs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#29332]
Based on feedback highlighted in #29331, the archboard gave feedback on LROs and, with @annelo-msft and @mikekistler, we decided to - for now, at least - use the old autorest method of documenting both the HTTP 200 and 202 status codes for LROs so that autorest / DPG knows whether to generate an LRO method to return an `Operation` or `Operation<T>`. I downloaded our [GA swagger](https://github.com/Azure/azure-rest-api-specs/blob/725f4ca360426a32d20e81eb945065e62c285d6a/specification/cognitiveservices/data-plane/Language/stable/2022-05-01/analyzeconversations-authoring.json) and made local edits to add the HTTP 200 responses. See attached for the full swagger, and the diff below to see my changes.

[analyzeconversations-authoring.zip](https://github.com/Azure/azure-sdk-for-net/files/8915766/analyzeconversations-authoring.zip)

```diff
diff --git a/sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/analyzeconversations-authoring.json b/sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/analyzeconversations-authoring.json
index 0b016d073c..3042c96d3f 100644
--- a/sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/analyzeconversations-authoring.json
+++ b/sdk/cognitivelanguage/Azure.AI.Language.Conversations/src/analyzeconversations-authoring.json
@@ -176,6 +176,12 @@
                     }
                 ],
                 "responses": {
+                    "200": {
+                        "description": "The project deletion job result.",
+                        "schema": {
+                            "$ref": "#/definitions/ConversationalAnalysisAuthoringProjectDeletionJobState"
+                        }
+                    },
                     "202": {
                         "description": "A successful call results with an Operation-Location header used to check the status of the job.",
                         "headers": {
@@ -229,6 +235,12 @@
                     }
                 ],
                 "responses": {
+                    "200": {
+                        "description": "The status of the long running operation.",
+                        "schema": {
+                            "$ref": "#/definitions/ConversationalAnalysisAuthoringExportProjectJobState"
+                        }
+                    },
                     "202": {
                         "description": "A successful call results with an Operation-Location header used to check the status of the job.",
                         "headers": {
@@ -284,6 +296,12 @@
                     }
                 ],
                 "responses": {
+                    "200": {
+                        "description": "The details of the long running operation.",
+                        "schema": {
+                            "$ref": "#/definitions/ConversationalAnalysisAuthoringImportProjectJobState"
+                        }
+                    },
                     "202": {
                         "description": "A successful call results with an Operation-Location header used to check the status of the job.",
                         "headers": {
@@ -336,6 +354,12 @@
                     }
                 ],
                 "responses": {
+                    "200": {
+                        "description": "The training job result.",
+                        "schema": {
+                            "$ref": "#/definitions/ConversationalAnalysisAuthoringTrainingJobState"
+                        }
+                    },
                     "202": {
                         "description": "A successful call results with an Operation-Location header used to check the status of the job.",
                         "headers": {
@@ -437,6 +461,12 @@
                     }
                 ],
                 "responses": {
+                    "200": {
+                        "description": "The swap deployment job result.",
+                        "schema": {
+                            "$ref": "#/definitions/ConversationalAnalysisAuthoringDeploymentJobState"
+                        }
+                    },
                     "202": {
                         "description": "A successful call results with an Operation-Location header used to check the status of the job.",
                         "headers": {
@@ -529,6 +559,12 @@
                     }
                 ],
                 "responses": {
+                    "200": {
+                        "description": "The deployment job result.",
+                        "schema": {
+                            "$ref": "#/definitions/ConversationalAnalysisAuthoringDeploymentJobState"
+                        }
+                    },
                     "202": {
                         "description": "A successful call results with an Operation-Location header used to check the status of the job.",
                         "headers": {
@@ -570,6 +606,12 @@
                     }
                 ],
                 "responses": {
+                    "200": {
+                        "description": "The deployment job result.",
+                        "schema": {
+                            "$ref": "#/definitions/ConversationalAnalysisAuthoringDeploymentJobState"
+                        }
+                    },
                     "202": {
                         "description": "A successful call results with an Operation-Location header used to check the status of the job.",
                         "headers": {
@@ -1076,6 +1118,12 @@
                     }
                 ],
                 "responses": {
+                    "200": {
+                        "description": "The training job result.",
+                        "schema": {
+                            "$ref": "#/definitions/ConversationalAnalysisAuthoringTrainingJobState"
+                        }
+                    },
                     "202": {
                         "description": "A successful call results with an Operation-Location header used to check the status of the job.",
                         "headers": {
```

Upon regeneration using Microsoft.Azure.AutoRest.CSharp version 3.0.0-beta.20220607.2 the only changes to source where documentation of the final result object i.e., methods still returned an `Operation<BinaryData>` and the implementation created a "200202" classifier, which was to be expected with both HTTP status codes present.

The operations affected (all LROs) are, in swagger document order:

* ConversationalAnalysisAuthoring_DeleteProject
* ConversationalAnalysisAuthoring_Export
* ConversationalAnalysisAuthoring_Import
* ConversationalAnalysisAuthoring_Train
* ConversationalAnalysisAuthoring_SwapDeployments
* ConversationalAnalysisAuthoring_DeployProject
* ConversationalAnalysisAuthoring_DeleteDeployment
* ConversationalAnalysisAuthoring_CancelTrainingJob

Also, the following changes should also be made based on archboard feedback and current .NET SDK guidelines:

- [ ] `Get*Status` should also not be generated, but apparently this is tied to other Operation work.

/cc @annelo-msft @chunyu3

**Comment by heaths** [comment]
Moved the pageable tasks to #29342

**Comment by annelo-msft** [comment]
@heaths, could you clarify what the ask for the DPG generator is in this issue?
If `Get*Status` should not be generated, I believe you will need to manually suppress generation of this method in the client's partial class.

**Comment by heaths** [comment]
@KrzysztofCwalina and @tg-msft said the `Get*Status` methods shouldn't be generated in favor of LROs. We also need a way so we don't have to specify both HTTP 200 and 202 which is a violation of our LRO guidelines. You said you were talking with @mikekistler on possible solutions. Maybe this is DPG 1.1, though, but I'll let you triage appropriate. Sounded like rehydratable LROs was a later feature, and @tg-msft mentioned we should then probably stop generating these `Get*Status` messages then.

**Comment by heaths** [comment]
On a related note, #29347 might also be a related issue that needs to be resolved.

**Comment by annelo-msft** [comment]
@heaths, yes we still need to drive guidance on when and when not to generate the `Get*Status` methods, and this should not block DPG v1.0 GA.  Please use [C# transforms](https://github.com/Azure/autorest.csharp#customizing-the-generated-code) to make these methods internal so they don't appear in the public API for CLU.

**Comment by annelo-msft** [comment]
REST API guidance requested here: https://github.com/microsoft/api-guidelines/issues/373#issue-1277379278

**Comment by heaths** [comment]
> Please use [C# transforms](https://github.com/Azure/autorest.csharp#customizing-the-generated-code) to make these methods internal so they don't appear in the public API for CLU.

As I remember from the archboard review, we should leave them for now, right @KrzysztofCwalina @tg-msft?

**Comment by pallavit** [comment]
@lirenhe to help triage. Tagging and routing to the correct project so it can be tracked correctly.

**Comment by lirenhe** [comment]
@chunyu3, could you take a look? thanks

**Comment by chunyu3** [comment]
As @annelo-msft mentioned we will write `c# transforms` to internal those `Get*Status` method for LRO for swagger. For typespec, we will not generate those methods by default.
Close this since it is already answered.
