### ISSUE TITLE
Secrets in environment variables

### ISSUE THREAD

**Issue by jrmcdona** [Azure/azure-sdk-for-net#29330]
### Library name and version

Azure.Identity latest

### Query/Question

Is it fairly safe to keep the secret in the system environment variables?  I am doing this for local development.  Our Azure subscription is behind protected Torus tenant so I cannot use Visual Studio account to authenticate. 

The entire team will need to have a secret in their system env variables.

Thanks

### Environment

Windows 11
Visual Studio 2022 v17.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @jrmcdona  - Are you able to use `AzureCliCredential` or `InteractiveBrowserCredential` instead? Those would avoid having to store and distribute secrets.
