### ISSUE TITLE
[BUG] Duplicated tags for Elastic Pools and Servers

### ISSUE THREAD

**Issue by mbaranovych** [Azure/azure-sdk-for-net#29336]
### Library name and version

Azure.ResourceManager.Sql 1.0.0-beta.5

### Describe the bug

When I use `subscription.GetSqlServers()` or `server.GetElasticPools()` methods, it returns data with duplicate tags that looks like this:
`{ "tag1" : "value", "Tag1" : "value", "tag2" : "value", "Tag2" : "value"}`
The only difference between duplicate tags is first letter (either capital or not).  Also some tags in the response don't have duplicates. 
So response can look like:
`{ "tag1" : "value", "Tag1" : "value", "tag2" : "value", "Tag2" : "value", "tag3" : "value"}`

In Azure portal there are no duplicate tags (and it's not possible to create those as tag names are case-insensitive).
Not sure what the root cause is, but definitely something is wrong.

Thanks in advance for any help you could provide.

### Expected behavior

Response data does not contain duplicate tags.

### Actual behavior

Response data contains duplicate tags.

For example:
`{ "tag1" : "value", "Tag1" : "value", "tag2" : "value", "Tag2" : "value", "tag3" : "value"}`

### Reproduction Steps

List<SqlServerResource> dbServers = subscription.GetSqlServers().ToList(); // Contains duplicate tags
foreach (SqlServerResource server in dbServers)
{
   var elasticPools = server.GetElasticPools().ToList(); // Contains duplicate tags
}

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
@mbaranovych I cannot reproduce your issue locally. Can you share how the server and elastics pools are created and how the tags are added?

**Comment by mbaranovych** [comment]
Shared details with fengzhou last year in a private discussion, last message was sent on July 11, 2022. As I haven't heard back anything I'll close this issue.
