### ISSUE TITLE
[BUG] It is not possible ot specify Aggregations on using QueryResourceAsync on a MetricsQueryClient

### ISSUE THREAD

**Issue by adymorz** [Azure/azure-sdk-for-net#29334]
### Library name and version

Azure.Monitor.Query

### Describe the bug

It is not possible to specify Aggregations on using QueryResourceAsync on a MetricsQueryClient instance.

### Expected behavior

The MetricsQueryOptions class does provide a setter for the property for Aggregations.

### Actual behavior

The MetricsQueryOptions class does **not** provide a setter for the property for Aggregations.

### Reproduction Steps

```
var response = await _metricsQueryClient.QueryResourceAsync(
    _logAnalyticsWorkspaceResourceId,
    new[] { MetricConstants.SomeKeyForAValue},
    new MetricsQueryOptions
    {
        MetricNamespace = DiagnosticsClient.MetricNamespace,
        TimeRange = new QueryTimeRange(queryTime),
        Granularity = _granularityForMetrics
        // the setter for Aggregations is missing here
    }).ConfigureAwait(false);
  ```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.420 [C:\Program Files\dotnet\sdk]
  5.0.401 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
//cc: @pallavit

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by scottaddie** [comment]
@adymorz You can set the aggregations as follows:

```csharp
// code omitted for brevity

    new MetricsQueryOptions
    {
        MetricNamespace = DiagnosticsClient.MetricNamespace,
        TimeRange = new QueryTimeRange(queryTime),
        Granularity = _granularityForMetrics
        Aggregations =
        {
            MetricAggregationType.Average,
            MetricAggregationType.Maximum,
        }
    }).ConfigureAwait(false);
```

**Comment by adymorz** [comment]
How could this bug be solved while `MetricsQueryOptions.Aggregations` does not have a setter and no other way is available to set the property?

https://github.com/Azure/azure-sdk-for-net/blob/6a1cc106049be9890d521d3448ba9d7ed1e97e1b/sdk/monitor/Azure.Monitor.Query/src/MetricsQueryOptions.cs#L31

**Comment by adymorz** [comment]
@jsquire, @scottaddie This issue is not resolved yet. Could you please reopen it?

**Comment by scottaddie** [comment]
@adymorz Thanks for getting back to me and for creating this issue. I'm glad you were able to figure this out.
