### ISSUE TITLE
How do I create an SSL binding when the certificate is already installed?

### ISSUE THREAD

**Issue by j055** [Azure/azure-sdk-for-net#2935]
I have a wildcard certificate installed in the webapp. How do I create an SSL Binding to a certificate which is already installed? I was expecting to specify the thumbprint but it looks like I have to upload the cert every time I create a binding.

```
app1 = app1.Update()
                                .WithManagedHostnameBindings(domain, app1Name)
                                .DefineSslBinding()
                                    .ForHostname(app1Name + "." + domainName)
                                    .WithPfxCertificateToUpload("Asset/" + pfxPath, CertificatePassword)
                                    .WithSniBasedSsl()
                                    .Attach()
                                .Apply();
```

Thanks
Andrew

**Comment by jianghaolu** [comment]
I'll add support for this in the next release.

**Comment by jianghaolu** [comment]
This is supported in v1.1.0.

**Comment by j055** [comment]
How do we use this? I tried the following:

```
           _webApp.Update()
                .WithClientCertEnabled(true)
                .DefineHostnameBinding()
                .WithThirdPartyDomain(domain)
                .WithSubDomain(subDomain)
                .WithDnsRecordType(CustomHostNameDnsRecordType.CName)
                .Attach()
                .Apply();
```

ALL CERTIFICATES stop working in the site including site.azurewebsites.net. The browser presents a 'Select a Certificate' dialog with 403 error saying the site is stopped when in fact it isn't:

![diag](https://user-images.githubusercontent.com/6011428/27346473-40eaba00-55e5-11e7-8251-2b96ed92456f.png)

The Azure portal shows everything working normally even though the certs are broken.

The WebApp needs deleting and recreating to fix it.

**Comment by hovsepm** [comment]
@jianghaolu please followup with the sample link.

**Comment by j055** [comment]
I had to fix the site this happened on. Can you tell me what you want which will help?

**Comment by j055** [comment]
This is easily reproducible:

1. Create a web app (I used a basic app service plan)
2. Add a CName record in your DNS to point to myapp.azurewebsites.net
3. Execute the following:

```
	webApp.Update()
				.WithClientCertEnabled(true)
				.DefineHostnameBinding()
				.WithThirdPartyDomain("mydomain.com")
				.WithSubDomain("test1")
				.WithDnsRecordType(CustomHostNameDnsRecordType.CName)
				.Attach()
				.Apply();
```
The site now returns HTTP 403 forbidden.

**Comment by Dona278** [comment]
@j055 To add a certificate binding to an existing web app i used:
```csharp
await azure.WebApps.Inner
       .CreateOrUpdateHostNameBindingAsync(
                RESOURCE_GROUP_NAME,
                WEB_APP_NAME,
                EXISTING_BINDED_TO_WEB_APP_HOSTNAME,
                new HostNameBindingInner(
                      azureResourceType: AzureResourceType.Website,
                      hostNameType: HostNameType.Verified,
                      customHostNameDnsRecordType: CustomHostNameDnsRecordType.CName // or A depends on the type of hostname,
                      sslState: SslState.SniEnabled,
                      thumbprint: CERTIFICATE_THUMBPRINT));
```

**Comment by j055** [comment]
@Dona278. Thanks. in v1.3 ```CreateOrUpdateHostNameBindingAsync``` changed to ```CreateOrUpdateHostNameBindingWithHttpMessagesAsync```

```
await azure
    .WebApps
    .Inner
    .CreateOrUpdateHostNameBindingWithHttpMessagesAsync(
        resourceGroupName, 
        webAppName, 
        domain,
		new HostNameBindingInner(
                    azureResourceType: AzureResourceType.Website,
                    hostNameType: HostNameType.Verified,
                    customHostNameDnsRecordType: CustomHostNameDnsRecordType.CName,
                    sslState: SslState.SniEnabled,
                    thumbprint: thumbprint));
```

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#61
