### ISSUE TITLE
[Translation] Deploy test resources failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29351]
Translation nightly test runs are failing with:

> Error message
> DEBUG: 14:06:03 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
> VERBOSE: Running registered exit actions
> VERBOSE: Logging out of service principal '***'
> VERBOSE: Performing the operation "New-TestResources.ps1" on target "***".
> Write-Error: /mnt/vss/_work/1/s/eng/common/TestResources/New-TestResources.ps1:721
> Line |
>  721 |          $deployment = Retry {
>      |                        ~~~~~~~
>      | Exception calling "Invoke" with "0" argument(s): "The running
>      | command stopped because the preference variable
>      | "ErrorActionPreference" or common parameter is set to Stop:
>      | 14:06:03 - Error: Code=InvalidTemplateDeployment; Message=The
>      | template deployment 't6cdb147895974349' is not valid according
>      | to the validation procedure. The tracking id is
>      | 'b4e5cc33-2014-445d-ae85-1fc360bb9aa0'. See inner errors for
>      | details. "
> 
> ##[error]PowerShell exited with code '1'.
> 

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1647003&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
//fyi: @pallavit
