### ISSUE TITLE
[QUERY] Why does TableClient.UpdateEntity need a dedicated ETag argument?

### ISSUE THREAD

**Issue by Aleksey-Kudryavtsev** [Azure/azure-sdk-for-net#29369]
### Library name and version

Azure.Data.Tables 12.6.0

### Query/Question

Why does [TableClient.UpdateEntity](https://docs.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclient.updateentity) have a dedicated ETag argument when it's already part of the entity argument (T:[ITableEntity](https://docs.microsoft.com/en-us/dotnet/api/azure.data.tables.itableentity.etag?view=azure-dotnet#azure-data-tables-itableentity-etag))?

Does this extra argument mean that TableClient.UpdateEntity() ignores ITableEntity.ETag?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
> Does this extra argument mean that TableClient.UpdateEntity() ignores ITableEntity.ETag?

Yes, the value on the model it ignored for that purpose. The reason being that the ETag property is not actually writeable. The model has a setter for serialization purposes, but it is not intended to be modified or used as the `if-match` header value.
