### ISSUE TITLE
Visual Studio 2017 Azure Mobile Apps Table Controller Scaffold Error

### ISSUE THREAD

**Issue by scout208** [Azure/azure-sdk-for-net#2936]
I have created a .NET Mobile App Backend by following the guide as shown [here](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-dotnet-backend-how-to-use-server-sdk#a-namedefine-table-controllera-how-to-define-a-table-controller). This worked wihout a problem in Visual Studio 2015, but once I loaded the project in Visual Studio 2017, I had the following issue:

1. Right-click on the Controllers folder and select **Add** > **Controller**....

![image](https://cloud.githubusercontent.com/assets/9426329/23923201/bb9b28ac-08d3-11e7-8a30-92a91b20e73f.png)

2. Select the **Azure Mobile Apps Table Controller** option, then click Add

![image](https://cloud.githubusercontent.com/assets/9426329/23923180/a5fd56b4-08d3-11e7-8edd-127cb52f2454.png)

Visual Studio give me the following error, and I think it's a problem with the new SDK in VS 2017, but I'm not entirely sure:

![image](https://cloud.githubusercontent.com/assets/9426329/23922766/a2552eda-08d1-11e7-8e08-f0a2e0d097a7.png)

The specific error is 'A TwoWay or OneWayToSource binding cannot work on the read-only property 'EntityTypes' or type 'Microsoft.Cct.MobileApps.WebExtensions.Scaffolding.MobileAppsTableViewControllerViewModel'.

**Comment by shahabhijeet** [comment]
@scout208 this feature is not hosted on this particular repo (azure sdk repo)
Please go to the below website and ask question
https://azure.microsoft.com/en-us/support/forums/
