### ISSUE TITLE
IKubernetesCluster.ProvisioningState - which strings are returned from this property?

### ISSUE THREAD

**Issue by georgeatkins1** [Azure/azure-sdk-for-net#29389]
I'm working with a team to deploy Kubernetes clusters for our customers to use.
We are working TDD and we want to test against possible states returned from this property. In other ProvisioningState properties I have seen, Enums are used to make default returns easy to predict.

I'd expect in the docs for there to be 'predictable returns'. For example, is the succeeded state "Succeeded" or "Successful", or even "success". Same for 'failed' state, and potentially 'accepted' state and 'updating' state etc.

Please input expected returned strings into the Microsoft docs page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5191d207-da68-486f-551b-45b713367c8b
* Version Independent ID: d37eaf4e-43d4-2e71-e895-0a3e8faade60
* Content: [IKubernetesCluster.ProvisioningState Property (Microsoft.Azure.Management.ContainerService.Fluent) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.containerservice.fluent.ikubernetescluster.provisioningstate?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.Management.ContainerService.Fluent/IKubernetesCluster.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ContainerService.Fluent/IKubernetesCluster.xml)
* Service: **container-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @georgeatkins1 ,
Thank you for using Azure SDK for .NET.
For the quetion you mentioned:
I'm afraid that we don't have full documents for ProvisioningState.
We have 3 pre-defined ProvisioningState, please check [ProvisioningState property](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#provisioningstate-property).
The service team could also define their own values. These are their domain knowledge.
