### ISSUE TITLE
[FEATURE REQ] Track2 SDK  method with customHeader 

### ISSUE THREAD

**Issue by grizzlytheodore** [Azure/azure-sdk-for-net#29380]
### Library name

Azure.Compute

### Please describe the feature.

For Track 1 .NET SDK, method had a parameter "customHeader".  
For example, shown in this [page:](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.ivirtualmachinesoperations.createorupdatewithhttpmessagesasync?view=azure-dotnet)
`Task<AzureOperationResponse<VirtualMachine>> CreateOrUpdateWithHttpMessagesAsync(string resourceGroupName, string vmName, VirtualMachine parameters, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default);`

Right now, track 2 SDK does not have a way to use the customHeader, and this parameter is used is several cases in Compute.

**Comment by heng-liu** [comment]
Thanks! Found an example at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/appconfiguration/Azure.Data.AppConfiguration/src/CustomHeadersPolicy.cs
