### ISSUE TITLE
Microsoft.Rest.ClientRuntime net45 is referencing Newtonsoft 6

### ISSUE THREAD

**Issue by johnwc** [Azure/azure-sdk-for-net#2939]
The two .NetStandard's reference Newtonsoft v9, but net45 references v6. Was this overlooked or on purpose? It is causing reference issues with Azure SDKs that reference this along with Netwonsoft v9.

**Comment by shahabhijeet** [comment]
@johnwc we have taken dependency on v6 for .net 45.
We are looking to updating to v9 in future release.

**Comment by johnwc** [comment]
Why is it closed, it is causing a reference issue with the rest of the Azure SDKs.  Shouldn't this be left open and marked closed once the issue is resolved?  

In the work that I am doing, I have no control of the assembly redirection in the .config files. So we can not simply redirect the assembly. ( Orchestrator )

**Comment by AzureBinkie** [comment]
This issue is only getting worse as Newtonsoft.Json is now at version 10 and now no frameworks support the latest.

**Comment by cleverguy25** [comment]
Agree this should not be closed.  This is blocking install of latest SDK.

**Comment by johnwc** [comment]
@shahabhijeet can you please change this back to open, this is a real issue and it is not resolved.
