### ISSUE TITLE
SecretClient overrides local files (secret.json, appsettings.*.json)

### ISSUE THREAD

**Issue by mrhub** [Azure/azure-sdk-for-net#29390]
### Library name and version

Azure.Security.KeyVault.Secrets 4.2.0

### Query/Question

I have a SecretClient injected to fetch some values from keyvault, but in the dev environment, I want to override some settings (local db and so on), and would like to use either secrets.json or appsettings.development.json to do that, but that do not seems to work.
Or am I doing it wrong?
Should local config files (secret.json, appsettings.*.json) override the SecretClient ?

Example code:
```
var builder = WebApplication.CreateBuilder(args);
var config = builder.Configuration;

var secretClient = new SecretClient(
    new Uri(config["KeyVault:Uri"]),
    new DefaultAzureCredential());
config.AddAzureKeyVault(secretClient, new KeyVaultSecretManager());

builder.Services.AddControllersWithViews();
builder.Services.AddDbContext<MyDbContext>(
    x => x.UseSqlServer(config["Db:ConnectionString"])
);
```

If I comment out the "AddAzureKeyVault", the connectionstring is read from the local files, but as is, the connectionstring is read from keyvault...

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
