### ISSUE TITLE
WebApps.ListByGroup crashing/never returning

### ISSUE THREAD

**Issue by abergs** [Azure/azure-sdk-for-net#2940]
Hi,

I'm trying to use ` azure.WebApps.ListByGroup(resourceGroup);` but it never returns or crashes.
Fetching individual websites work however.

What more information would you need in order to investigate?

**Comment by jianghaolu** [comment]
Hi @abergs 
Are you working with an IDE like Eclipse or IntelliJ IDEA? If so, do you think you can debug and pause when the process hangs?

**Comment by abergs** [comment]
No I'm using it VS. Unfortunately I've since moved on and won't be able to investigate further myself.

**Comment by hovsepm** [comment]
@abergs could you upgrade Fluent SDK to the latest available version (1.1.1) and post here if it still hangs forever?

**Comment by hovsepm** [comment]
Please create new issue if this still happens in v1.1.2
