### ISSUE TITLE
[BUG] ScoringFunctions property in ScoringProfile class cannot be set.

### ISSUE THREAD

**Issue by hsirtl** [Azure/azure-sdk-for-net#29419]
### Library name and version

Azure.Search.Documents.Indexes.Models 11.3.0

### Describe the bug

In the current implementation of the ScoringProfile class, the property Functions is read-only. As I haven't found any other way of setting ScoringFunctions in a ScoringProfile class (its constructor doesn't accept an IList<ScoringFunction>), I assume this is a bug. I also haven't found any documentation that would describe how to set ScoringFunctions in v11. In earlier SDK-versions this was an easy thing to do as the property was writable.

### Expected behavior

Make the ScoringFunctions property writable ({ get; set; }). Or document any other way to set scoring functions (my goal is to rank newer items higher than older items).

### Actual behavior

ScoringFunctions property is read-only. No other way of setting it is documented.

### Reproduction Steps

This implementation is documented here: https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.indexes.models.scoringprofile.functions?view=azure-dotnet#azure-search-documents-indexes-models-scoringprofile-functions

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
