### ISSUE TITLE
[Core] Documentation of Default Retry Policies and how we could customize it

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-net#29413]
### API Change Needed

No

### Background and motivation

As far as we know, the retry policy in `Azure.Core` is different from the policy we are using in the old generation of the SDK (track 1). Therefore could we introduce some documents with details about what is the default behavior of the current retry policy?
For instance, in which occasion will we retry? How many times do we retry by default? How long is the delay? If we configured the retry options, how those configurations will change the default behavior?

And for advance topics, is it possible that we could define our own retry policy to replace this default [`RetryPolicy`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/Internal/RetryPolicy.cs)?

### API / Feature Proposal

No API changes

### Time Constraints and Dependencies

No dependencies

**Comment by pallavit** [comment]
@jsquire where do we generally add such documentation - in the reference docs or general docs?

**Comment by jsquire** [comment]
This would probably fall under the Core samples docs for the longer-form discussion.    We'll also want to double-check the doc comments to be sure that we've got the right level of information there.

**Comment by JoshLove-msft** [comment]
Addressed in https://github.com/Azure/azure-sdk-for-net/pull/31187

**Comment by t-test-t** [comment]
4Yesdr
 -ng(d\BngcjwhJoshLove-msft ***@***.***>
.r
