### ISSUE TITLE
Resolve the `identity` issue in `Azure.ResourceManager.DesktopVirtualization` sdk

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-net#29412]
The swagger of `desktopvirtualization` is using the resource model defined [here](https://github.com/Azure/azure-rest-api-specs/blob/eb606ec7a7abadc78ded1423ddbea9e8f49e72c3/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/stable/2021-07-12/desktopvirtualization.json#L2568) from common-type v1: https://github.com/Azure/azure-rest-api-specs/blob/9d789cce9038ba5b5fc34ffb16c566373b18655c/specification/common-types/resource-management/v1/types.json#L95
In common type v1, [the identity](https://github.com/Azure/azure-rest-api-specs/blob/9d789cce9038ba5b5fc34ffb16c566373b18655c/specification/common-types/resource-management/v1/types.json#L245) is defined with only one possible value of type: `SystemAssigned`. But our common model in resource manager to replace the `identity` all at least have two values: `None` and `SystemAssigned`.

We need to 
1. Verify if the `type` in the identity of `desktopvirtualization` could accept a type of `None`.
2. If so, this indicates their swagger is not correct (a valid value is not documented), the corresponding service team needs to update their swagger so that the swagger matches its actual behavior.
If not, we need to come up with a solution with the fact that the Identity in `desktopvirtualization` RP cannot be replaced by the one in resourcemanager.

**Comment by ArcturusZhang** [comment]
This is a related issue with the managed service identity, therefore I assigned this to you @fengzhou-msft .
I assume once that issue is resolved, this will be resolved automatically

**Comment by fengzhou-msft** [comment]
With ##29924, the identity in desktopvirtualization will be replaced whether it supports `None` as type or not. It will just affect the property description about the supported types.

**Comment by ArcturusZhang** [comment]
this has been resolved by https://github.com/Azure/azure-sdk-for-net/pull/29924
