### ISSUE TITLE
[FEATURE REQ] complete QueueClient.ReceiveMessages documentation about expected exceptions

### ISSUE THREAD

**Issue by ChangeTheCode** [Azure/azure-sdk-for-net#29410]
### Library name

Azure.Storage.Queues

### Please describe the feature.

Would be really nice to have an complete documentation about exceptions, at least on the Microsoft docs. Also nice would it if the SKD code has the complete documentation for this method as xml comments. 
Currently it is not transparent which exceptions can be expected from the method ´QueueClient.ReceiveMessages´

[Official Microsoft docs](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient.receivemessages?view=azure-dotnet)

Criteria: 
- List of excepted exceptions 
- opt: adapt xml comments in code so the sdk also provides these infromation

**Comment by ChangeTheCode** [comment]
potentially this is the answer but I am not 100% sure. 

´All Azure Storage Queue service operations will throw a [RequestFailedException](https://github.com/Azure/azure-sdk-for-net/tree/Azure.Storage.Queues_12.11.0-beta.1/sdk/core/Azure.Core/src/RequestFailedException.cs) on failure with helpful [ErrorCodes](https://docs.microsoft.com/en-us/rest/api/storageservices/queue-service-error-codes). Many of these errors are recoverable.´ 
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.queues-readme-pre#troubleshooting

**Comment by PramodValavala-MSFT** [comment]
@ChangeTheCode Yes. That is the correct document to refer to for handling exceptions and the list of error codes that you can expect.

**Comment by ChangeTheCode** [comment]
@PramodValavala-MSFT for my point of view it would make sense at least to link this https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.queues-readme-pre#troubleshooting documentation in the documentation of the doc to have a direct link
