### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by et1975** [Azure/azure-sdk-for-net#29421]
Link to https://msdn.microsoft.com/en-us/library/azure/mt639399.aspx is broken, other pages of the client docs probably have the same issue.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e94883e1-ad75-2c8a-86ba-4d618c12f918
* Version Independent ID: 06b0be07-4181-a8b8-f587-82e104915bf3
* Content: [TopicsOperationsExtensions.GetAsync Method (Microsoft.Azure.Management.ServiceBus.Fluent) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.servicebus.fluent.topicsoperationsextensions.getasync?view=azure-dotnet#microsoft-azure-management-servicebus-fluent-topicsoperationsextensions-getasync(microsoft-azure-management-servicebus-fluent-itopicsoperations-system-string-system-string-system-string-system-threading-cancellationtoken))
* Content Source: [xml/Microsoft.Azure.Management.ServiceBus.Fluent/TopicsOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ServiceBus.Fluent/TopicsOperationsExtensions.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
this is old msdn doc, assign to docs team for further investigation

**Comment by jsquire** [comment]
Closing; the MSDN documentation is no longer under active maintenance.
