### ISSUE TITLE
[QUERY] Returning a list of Snapshots as Pages

### ISSUE THREAD

**Issue by Burlinn** [Azure/azure-sdk-for-net#29423]
### Library name and version

Azure.Storage.Blobs v12.11.0

### Query/Question

Hello! I'm working on a process that has the potential to produce a lot of blob snapshots so I'm hoping to fetch the snapshots as pages. But I'm running into an issue. When I run this code:

```
IAsyncEnumerable<Page<BlobItem>> resultSegment = _blobContainerClient
  .GetBlobsAsync(
    prefix: prefix,
    states: BlobStates.Snapshots,
    cancellationToken: cancellationToken)
  .AsPages(
    continuationToken: continuationToken,
    pageSizeHint: pageSize);
```
And then try to return the first blobPage.ContinuationToken, the ContinuationToken seems to just be the name of the blob I'm trying to fetch. Then when I use that ContinuationToken the next time around the process returns an empty enumerable.

Filing this as a query because I'm almost positive I'm doing something wrong. Am I using the continuation token correctly?

### Environment

Windows in Visual Studio 17.2.4

**Comment by Burlinn** [comment]
Hi Pramod, I think I figured out what's going on. The continuationToken seemed to only be having trouble when testing locally with the Azurite storage emulator. When I hooked it up to my dev storage account, the continuationToken worked just fine. Thanks for the assist!

**Comment by PramodValavala-MSFT** [comment]
@Burlinn Glad to hear that! Closing this out.
