### ISSUE TITLE
[QUERY] Azure WebJobs Event Hubs client library & migrating EventProcessorHost checkpoints

### ISSUE THREAD

**Issue by christophwille** [Azure/azure-sdk-for-net#29436]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventHubs 4.0.1

### Query/Question

Currently, I have a netcoreapp3.1 Azure Functions v3 that uses Microsoft.Azure.WebJobs.Extensions.EventHubs 4.0.1. The intention is to upgrade to net6.0 Azure Functions v4 with latest (5.x) of Microsoft.Azure.WebJobs.Extensions.EventHubs.

In migrating other parts of the applications from old and deprecated packages I came across https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/MigrationGuide.md#migrating-eventprocessorhost-checkpoints regarding checkpoint persistence changes. Given that EH WebJobs 4 and 5 differ in exactly those client libraries, is there a place where the upgrade behavior is documented? (I intend to deploy the upgraded v4 Functions app into the same slot as the current v3 one) Does it (WebJobs EH extension) migrate the checkpoints? Does it delete and start from the beginning of the EH?

**Comment by christophwille** [comment]
I sort of expected this behavior. 

So the following will also be true: once we have rolled out the very first deployment of the v4 service, there is no going back (ie rollback to the old v3 version because something went terribly bad with the v4 one)

**Comment by jsquire** [comment]
You'd be able to roll back the code, but the new checkpoint data would not be used; whatever last existed in the v4 format would be used for reading.

**Comment by christophwille** [comment]
Yes, I meant that the checkpoint data would have been converted and that the v3/4.0.1 would no longer be able to read it.
