### ISSUE TITLE
DPG code gen comments should follow best practices

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#29445]
Generated code for .NET SDKs should follow recommended practices like consumers see in .NET Framework or Core documentation, such as "Gets or sets ..." for get/set properties, or just "Gets ..." for read-only properties. Being consistent with other .NET documentation should make using the Azure SDKs for .NET seamless and consistent.

One way to ensure this is to make sure we enable stylecop and run it for generated code until we can clear it. Take, for example,

* [SA1623](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1623.md) for properties.
* [SA1642](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1642.md) for constructors.

[SA1600-](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/DocumentationRules.md) covers documentation and would be good to review.

**Comment by pallavit** [comment]
@lirenhe to help triage the issue. Tagging and routing to the correct project.

**Comment by lirenhe** [comment]
@chunyu3, could you take a look?

**Comment by chunyu3** [comment]
DPG codegen has already implemented this. close this issue.
