### ISSUE TITLE
`AZURE_AUTHORITY_HOST` could be an optional variable in `TestEnvironment.Credential`

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#29447]
Since `ClientSecretCredentialOptions.AuthorityHost` is optional, shouldn't `AZURE_AUTHORITY_HOST` use `GetOptionalVariable` instead of `GetVariable`? Was a bit of a surprise when I was missing an env var trying to run tests against static test resources.

**Comment by heaths** [comment]
This was initially added as written now, though there was a question about it that leads me to believe @pakrym might have had the same question: https://github.com/Azure/azure-sdk-for-net/pull/23141/files#r684503662

For SDKs with static resources, running `New-TestResources.ps1` isn't always necessary, as in the case with _sdk/cognitivelanguage_. I don't see a reason to make this environment variable mandatory.

**Comment by Pablo1q** [comment]
Good
