### ISSUE TITLE
[QUERY]Concurrency limitations in OpenWriteAsync()

### ISSUE THREAD

**Issue by khandelwalankit04** [Azure/azure-sdk-for-net#29451]
### Library name and version

Azure.Storage.Files.DataLake : 12.10.0

### Query/Question

There seems to be limitations to number of OpenWriteAsync() requests that can be triggered concurrently. This limitation is not explicitly known to the clients. For example when opening 1000 streams concurrently we see below as frequency distribution of response times from my local machine: 

|    TimeToResponse(mm:ss) |                                No of Requests |
|------------------------- |---------------------------------------------- |
|                    03:20 |                                           207 |
|                    03:21 |                                           196 |
|                    03:19 |                                           159 |
|                    00:01 |                                            72 |
|                    03:22 |                                            62 |
|                    01:01 |                                            46 |
|                    01:02 |                                            13 |
|                    03:23 |                                            10 |
|                    ...   |                                          < 10 |

As per this data more than 60% of streams took more than 3 minutes to respond.

While when i did add a semaphore around number of streams that can be opened at a time to 64 , i see below response times for 1000 concurrent requests : 

|    TimeToResponse(mm:ss) |                                No of Requests |
|------------------------- |---------------------------------------------- |
|                    00:07 |                                           139 |
|                    00:06 |                                           131 |
|                    00:05 |                                           128 |
|                    00:08 |                                           117 |
|                    00:01 |                                           114 |
|                    00:03 |                                           115 |
|                    00:04 |                                           104 |
|                    00:02 |                                            81 |
|                    00:09 |                                            55 |

On further analysis : it seems the default array pool size that is being used is 128 MB (Ref: https://github.com/Azure/azure-sdk-for-net/blob/Azure.Storage.Files.DataLake_12.10.0/sdk/storage/Azure.Storage.Common/src/Shared/PooledMemoryStream.cs#L20) and each OpenWriteAsync() with default options would draw atleast 1MB (ref: https://github.com/Azure/azure-sdk-for-net/blob/Azure.Storage.Files.DataLake_12.10.0/sdk/storage/Azure.Storage.Common/src/Shared/StorageWriteStream.cs#L58)

This suggests that there is a problem around how ArrayPool is being used here. I have two questions or suggestion here : 

1. If there is such limitation , i think sdk should take care of handling it better so that clients do not have to add additional handling around it. What are your thoughts?
2. The array pool size should be exposed during configuration so that systems can set arraypool size they want.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this ask.

@sumantmehtams Could you please look into this request and provide an update ?
