### ISSUE TITLE
[Search] Behavior_RetryDelay failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29462]
Search nightly test runs are failing with:

> Error message
> Expected a delay between 2000ms and 10000ms, not 219733
> Expected: True
> But was:  False
> 
> 
> Stack trace
>    at Azure.Search.Documents.Tests.BatchingTests.Behavior_RetryDelay() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 1314
>    at Azure.Search.Documents.Tests.BatchingTests.Behavior_RetryDelay() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 1321
>    at Azure.Search.Documents.Tests.BatchingTests.Behavior_RetryDelay() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 1321
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1659589&view=results

@jsquire for notification.

**Comment by ShivangiReja** [comment]
Nightly tests are running without any errors in the past 2-3 weeks, so closing this issue.

For more details see here: https://dev.azure.com/azure-sdk/internal/_build?definitionId=1594&_a=summary

Please create a new issue, if the tests are started to fail again.
