### ISSUE TITLE
 Azure.AI.FormRecognizer.DocumentAnalysis.AnalyzeResult.Documents does not output tables

### ISSUE THREAD

**Issue by chrisnelmes** [Azure/azure-sdk-for-net#29476]
### Library name and version

Azure.AiFormRecognizer 4.0.0-Beta.4

### Describe the bug

Azure.AI.FormRecognizer.DocumentAnalysis.AnalyzeResult.Documents does not output tables.

AI Model contains a table (see definition below), however values are not provided in the Analyze Result Object.

Analyzing the same document using REST API provides the correct result

Definition of Table from AI Model
"definitions": {
		"Instruments_object": {
			"fieldKey": "Instruments_object",
			"fieldType": "object",
			"fieldFormat": "not-specified",
			"fields": [
				{
					"fieldKey": "Fund Short Name",
					"fieldType": "string",
					"fieldFormat": "not-specified"
				},
				{
					"fieldKey": "Currency",
					"fieldType": "string",
					"fieldFormat": "not-specified"
				},
				{
					"fieldKey": "StartShares",
					"fieldType": "string",
					"fieldFormat": "not-specified"
				},
				{
					"fieldKey": "Start NAV Per Share",
					"fieldType": "string",
					"fieldFormat": "not-specified"
				},
				{
					"fieldKey": "Start Market Value",
					"fieldType": "string",
					"fieldFormat": "not-specified"
				},
				{
					"fieldKey": "ActivityShares",
					"fieldType": "string",
					"fieldFormat": "not-specified"
				},
				{
					"fieldKey": "ActivityValue",
					"fieldType": "string",
					"fieldFormat": "not-specified"
				},
				{
					"fieldKey": "EndShares",
					"fieldType": "string",
					"fieldFormat": "not-specified"
				},
				{
					"fieldKey": "EndNAVperShare",
					"fieldType": "string",
					"fieldFormat": "not-specified"
				},
				{
					"fieldKey": "EndMarketValue",
					"fieldType": "string",
					"fieldFormat": "not-specified"
				}
			]
		}
	}

Result with Correct Value from Rest API
 "Instruments": {
          "type": "array",
          "valueArray": [
            {
              "type": "object",
              "valueObject": {
                "Fund Short Name": {
                  "type": "string",
                  "valueString": "Redacted",
                  "content": "Redacted",
                  "boundingRegions": [
                    {
                      "pageNumber": 1,
                      "polygon": [
                        0.51,
                        4.055,
                        1.345,
                        4.055,
                        1.345,
                        4.12,
                        0.51,
                        4.12
                      ]
                    }
                  ],
                  "spans": [
                    {
                      "offset": 414,
                      "length": 21
                    }
                  ]
                },
                "Currency": {
                  "type": "string",
                  "valueString": "Redacted",
                  "content": "Redacted",
                  "boundingRegions": [
                    {
                      "pageNumber": 1,
                      "polygon": [
                        1.865,
                        4.055,
                        2.02,
                        4.055,
                        2.02,
                        4.12,
                        1.865,
                        4.12
                      ]
                    }
                  ],
                  "spans": [
                    {
                      "offset": 436,
                      "length": 3
                    }
                  ]
                },
                "StartShares": {
                  "type": "string",
                  "valueString": "Redacted",
                  "content": "Redacted",
                  "boundingRegions": [
                    {
                      "pageNumber": 1,
                      "polygon": [
                        2.55,
                        4.055,
                        2.935,
                        4.055,
                        2.935,
                        4.135,
                        2.55,
                        4.135
                      ]
                    }
                  ],
                  "spans": [
                    {
                      "offset": 440,
                      "length": 9
                    }
                  ]
                },
                "Start NAV Per Share": {
                  "type": "string",
                  "valueString": "Redacted",
                  "content": "Redacted",
                  "boundingRegions": [
                    {
                      "pageNumber": 1,
                      "polygon": [
                        3.325,
                        4.055,
                        3.685,
                        4.055,
                        3.685,
                        4.12,
                        3.325,
                        4.12
                      ]
                    }
                  ],
                  "spans": [
                    {
                      "offset": 450,
                      "length": 8
                    }
                  ]
                },
                "Start Market Value": {
                  "type": "string",
                  "valueString": "Redacted",
                  "content": "Redacted",
                  "boundingRegions": [
                    {
                      "pageNumber": 1,
                      "polygon": [
                        4.115,
                        4.055,
                        4.55,
                        4.055,
                        4.55,
                        4.135,
                        4.115,
                        4.135
                      ]
                    }
                  ],
                  "spans": [
                    {
                      "offset": 459,
                      "length": 10
                    }
                  ]
                },
                "ActivityShares": {
                  "type": "string",
                  "valueString": "Redacted",
                  "content": "Redacted",
                  "boundingRegions": [
                    {
                      "pageNumber": 1,
                      "polygon": [
                        5.285,
                        4.055,
                        5.54,
                        4.055,
                        5.54,
                        4.12,
                        5.285,
                        4.12
                      ]
                    }
                  ],
                  "spans": [
                    {
                      "offset": 470,
                      "length": 6
                    }
                  ]
                },
                "ActivityValue": {
                  "type": "string",
                  "valueString": "Redacted",
                  "content": "Redacted",
                  "boundingRegions": [
                    {
                      "pageNumber": 1,
                      "polygon": [
                        6.135,
                        4.055,
                        6.465,
                        4.055,
                        6.465,
                        4.135,
                        6.135,
                        4.135
                      ]
                    }
                  ],
                  "spans": [
                    {
                      "offset": 477,
                      "length": 8
                    }
                  ]
                },
                "EndShares": {
                  "type": "string",
                  "valueString": "Redacted",
                  "content": "Redacted",
                  "boundingRegions": [
                    {
                      "pageNumber": 1,
                      "polygon": [
                        7.125,
                        4.055,
                        7.505,
                        4.055,
                        7.505,
                        4.135,
                        7.125,
                        4.135
                      ]
                    }
                  ],
                  "spans": [
                    {
                      "offset": 486,
                      "length": 9
                    }
                  ]
                },
                "EndNAVperShare": {
                  "type": "string",
                  "valueString": "Redacted",
                  "content": "Redacted",
                  "boundingRegions": [
                    {
                      "pageNumber": 1,
                      "polygon": [
                        7.93,
                        4.055,
                        8.285,
                        4.055,
                        8.285,
                        4.12,
                        7.93,
                        4.12
                      ]
                    }
                  ],
                  "spans": [
                    {
                      "offset": 496,
                      "length": 8
                    }
                  ]
                },
                "EndMarketValue": {
                  "type": "string",
                  "valueString": "Redacted",
                  "content": "Redacted",
                  "boundingRegions": [
                    {
                      "pageNumber": 1,
                      "polygon": [
                        8.755,
                        4.055,
                        9.185,
                        4.055,
                        9.185,
                        4.135,
                        8.755,
                        4.135
                      ]
                    }
                  ],
                  "spans": [
                    {
                      "offset": 505,
                      "length": 10
                    }
                  ]
                }
              }
            }
        }    
    }
  ]
}}

Value from SDK (null)
<HTML>
<head>
<title>Document</title></head>
<body>

  | Name | Value | Type
-- | -- | -- | --
◢ | [22] | {[Instruments, {DocumentField: ValueType=List, AsList()=>Value}]} | System.Collections.Generic.KeyValuePair<string, Azure.AI.FormRecognizer.DocumentAnalysis.DocumentField>

</body>
</HTML>

### Expected behavior

Table data provided in result

### Actual behavior

null value provided instead of table

### Reproduction Steps

Create an AI Model including a table as a field in Form Recognizer Studio.

Use the following code to submit the document for analysis. 

Look for the table output in operation.Value.Documents[0].Fields

C# Code
using Azure;
using Azure.AI.FormRecognizer.DocumentAnalysis;
using System;
using System.Threading.Tasks;
using System.Windows;
using System.IO;
string endpoint = "";
string key = "";
AzureKeyCredential credential = new AzureKeyCredential(key);
DocumentAnalysisClient client = new DocumentAnalysisClient(new Uri(endpoint), credential, new DocumentAnalysisClientOptions(DocumentAnalysisClientOptions.ServiceVersion.V2022_06_30_preview));
String filename = @"";
FileStream DocumentStream = File.Open(filename, FileMode.Open);

AnalyzeDocumentOperation operation = await client.StartAnalyzeDocumentAsync("MODEL", DocumentStream);

await operation.WaitForCompletionAsync();

AnalyzeResult result = operation.Value;

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @chrisnelmes,

Based on the REST API result you shared, the fields you want to extract are inside an object field, and that object field is inside an array field called "Instruments".

Have you tried accessing them like this:
```cs
var fields = operation.Value.Documents[0].Fields;
var instrumentsList = fields["Instruments"].AsList();
var instrumentsFields = instrumentsList[0].AsDictionary();

DocumentField activityShares = instrumentsFields["ActivityShares"];
DocumentField activityValue = instrumentsFields["ActivityValue"];
// etc...
```
Our [Analyze a document with a prebuilt model sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/formrecognizer/Azure.AI.FormRecognizer/samples/Sample_AnalyzeWithPrebuiltModel.md#use-a-prebuilt-model-to-analyze-a-document-from-a-uri) has examples of the recommended approach for field extraction.

Please let me know if this solves your problem.

**Comment by chrisnelmes** [comment]
Thank you! That works perfectly.

**Comment by FarhanAkhtar121** [comment]
Hello there! Can you show how to save the extracted data from custom form recognizer model as JSON file in blob storage.
Thanks in advance.
