### ISSUE TITLE
Exception: Could not load file or assembly 'Newtonsoft.Json' adding a REST API Client

### ISSUE THREAD

**Issue by mredison** [Azure/azure-sdk-for-net#2947]
Hello, I am working a support case with a customer. 

- Customer is trying to accomplish the following article: https://docs.microsoft.com/en-us/azure/app-service-api/app-service-api-dotnet-get-started

- I was able to add a REST API Client without issues using Visual Studio 2015 and Azure SDK v2.9.1.

- My customer is using v2.9.6 and she is receiving the following error:
Exception: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

- I updated Azure SDK to the lastest version 3.0 recently released and I am getting the same error:

> Generating client code and adding to project started
> Generate client code for REST API with following parameters:
> REST API Name: edisga-api, Base namespace: ToDoListAPI, Metadata file path: C:\Users\edisga\AppData\Local\Temp\WebToolsAutoRest\edisga-api\201703161806560658\swagger.json
> Exception: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
> Generating client code and adding to project failed
> Adding REST API client for failed

-The problem is that if we follow this solution http://stackoverflow.com/questions/41373912/add-rest-api-client-command-fails-in-vs2015 to copy this dll into IDE file system, we are able to download the REST API definition from swagger but this not generating a class in code called ToDoItemCollection.

`    public static partial class ToDoItemCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ToDoItem> DeserializeJson(JToken inputObject)
        {
            IList<ToDoItem> deserializedObject = new List<ToDoItem>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ToDoItem toDoItem = new ToDoItem();
                toDoItem.DeserializeJson(iListValue);
                deserializedObject.Add(toDoItem);
            }
            return deserializedObject;
        }
    }`

- This class is successfully generated using just Azure SDK v2.9.1

**Could you please review why is this failing?**

Thanks

**Comment by mredison** [comment]
Hello, the action plan that worked for me was:

- Uninstall Azure SDK 2.9.6 or 3.0 and install the 2.9.1.

- I chose just the installer WebToolsAzure2015.exe from version 2.9.1 on this page: https://azure.microsoft.com/en-gb/downloads/archive-net-downloads

And that solved the issue. 

Can you please review the lastest Azure SDK why there are not finding Newtonsoft.Json and cant generate the client code?

**Comment by sphibbs** [comment]
https://azure.microsoft.com/en-us/support/forums/ is the place for *that* .net sdk. I will reach out internally and help you find the right contacts.

**Comment by ChrisSfanos** [comment]
We've identified the proper team for this and created a bug for a future Azure SDK for .NET release

**Comment by bruceyclee** [comment]
@mredison , this bug has been fixed and the fix will get released with the next version of Azure SDK for Visual Studio 2015.
