### ISSUE TITLE
MessagingEntityNotFound is a value of an Enum, but it was listed under the Exceptions list of GetTopicAsync

### ISSUE THREAD

**Issue by TechInceptions** [Azure/azure-sdk-for-net#29487]
MessagingEntityNotFound is a value of an Enum, but it was listed under the Exceptions list of GetTopicAsync, in this documentation, there's is no clear connection between this value, and the exception that contains this value 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 831d6edc-0980-003e-6d09-3edf1a6a1058
* Version Independent ID: 6eb61345-d2b2-68ab-a0a6-75bca7051085
* Content: [ServiceBusAdministrationClient.GetTopicAsync Method (Azure.Messaging.ServiceBus.Administration) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient.gettopicasync?view=azure-dotnet#azure-messaging-servicebus-administration-servicebusadministrationclient-gettopicasync(system-string-system-threading-cancellationtoken))
* Content Source: [xml/Azure.Messaging.ServiceBus.Administration/ServiceBusAdministrationClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus.Administration/ServiceBusAdministrationClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
