### ISSUE TITLE
[BUG] Session concurrency not firing concurrently with service bus azure function trigger

### ISSUE THREAD

**Issue by LouisGordon** [Azure/azure-sdk-for-net#29505]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.5.1

### Describe the bug

The session concurrency functionality for a service bus triggered function does not appear to be behaving as I'd expect. What I'm seeing in my testing is that it will receive for a single session in the correct order (FIFO), once all of the messages for that session have processed and the receive link for that session closes (after a minute), it will pick up the next session.  I'd expect that these sessions would process concurrently based on my settings.

I'm wondering if there is some problem with how I have configured my function and/or settings. This is a new project, we have a lot of volume on SQL Service Broker we're looking to eventually migrate onto service bus via service bus triggered functions with concurrent session processing.

### Expected behavior

Sessions are processed concurrently up to the number set by the maxConcurrentSessions value

### Actual behavior

Sessions are handled one after another, not at the same time. Messages within a session are processed in the correct order.

### Reproduction Steps

I've included a sln with a function and a sender.  

- You'll need to set the service bus conn str in the sender Program.cs, and the SessionFunction > local.settings.json
- The sender sends messages interleaved for one of two sessions (odd, even)
- The function receives all for odd first, a minute passes for the receive lock to release, then the even session messages are handle
[SessionConcurrency.zip](https://github.com/Azure/azure-sdk-for-net/files/8995501/SessionConcurrency.zip)
d

### Environment

Windows Azure Function
Reproducible locally with Function Runtime Version: 4.5.2.18383

**Comment by JoshLove-msft** [comment]
Hi @LouisGordon,
Unfortunately the concurrency options are not supported when using functions that receive a batch of messages.
See https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.servicebus.servicebusoptions.maxconcurrentsessions?view=azure-dotnet#microsoft-azure-webjobs-servicebus-servicebusoptions-maxconcurrentsessions for more info.

**Comment by LouisGordon** [comment]
Thanks for the quick response.
