### ISSUE TITLE
[QUERY] object ref from BlobClient.OpenWrite

### ISSUE THREAD

**Issue by rogerreynolds** [Azure/azure-sdk-for-net#29511]
### Library name and version

Azure.Storage.Blobs 12.12.0

### Query/Question

I must be doing something stupid. (calling it a question and not a bug because i'm pretty sure i'm just doing something wrong)

I have a sas uri to a blob that does not exist. The sas uri includes Write permission.
I can use the Upload method to create it like so it like so
```
            var blobClient = new BlobClient(blobUri);
            blobClient.Upload(stream);
```

And that works fine, but what i actually want to do is open a stream for writing to the blob.  Something like this:
```
            using (var fsw = blobClient.OpenWrite(true))
                 stream.CopyTo(fsw);
```

But, the call to OpenWrite fails with a NullReferenceException.
Stack trace is

   at Azure.Storage.Blobs.Models.BlobOpenWriteOptionsExtensions.ToBlockBlobOpenWriteOptions(BlobOpenWriteOptions options)
   at Azure.Storage.Blobs.BlobClient.<OpenWriteInternal>d__45.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Storage.Blobs.BlobClient.OpenWrite(Boolean overwrite, BlobOpenWriteOptions options, CancellationToken cancellationToken)

Am i doing something wrong here?
Thanks in advance.
roger

### Environment

dotnet info:

.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.420 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by marklio** [comment]
I think this needs to be re-opened. While @rogerreynolds has found a workaround, the bug is that the default value for a parameter yields a null ref exception. This should be fixed.

**Comment by rogerreynolds** [comment]
I would certainly agree. 
I reopened, changed the name to BUG

**Comment by marklio** [comment]
It looks like this was possibly fixed in #28870. I'm testing it now.

**Comment by marklio** [comment]
I have confirmed that this is fixed in latest beta (I tested Azure.Storage.Blobs 12.13.0-beta.1). The fix comes primarily from the PR I referenced above (#28870) where it uses ?. to call the extension method that is throwing null ref. This prevents it from being called in the null case, and null appears to propagate correctly through the rest of the call chain. You can close this. Sorry for the extra noise here, but hopefully the extra context helps someone else who might be hitting this and finds this issue.

**Comment by rogerreynolds** [comment]
Thanks.
