### ISSUE TITLE
[BUG] BlockBlobClient OpenWriteAsync creates empty blob whilst upload is in flight

### ISSUE THREAD

**Issue by neilrees** [Azure/azure-sdk-for-net#29518]
### Library name and version

Azure.Storage.Blobs 12.12.0

### Describe the bug

When calling `OpenWriteAsync` on a new block blob a 0 byte empty blob is created in the blob container.
The producer then writes to the stream and the data is uploaded into new blocks as required, when the writer is finished the stream is disposed, the block list is committed and the new blob now contains data.
There is no way for a blob reader to know that a blob is still in the process of being uploaded.

This is also a change in behavior from `Microsoft.Azure.Storage.Blob`  11.2.3 where it is possible to upload a blob in it's entirety atomically.  This issue has been discussed previously https://github.com/Azure/azure-sdk-for-net/issues/18797 but the suggestion to use `UploadAsync` is not suitable when the producer writes more data than can be held in memory.

The empty blob appears to be created here https://github.com/Azure/azure-sdk-for-net/blob/fdd82bfc752d856ac868e251350a2f0b8737df85/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs#L2792 

Could this behavior be fixed to match v11 (or at the very least made configurable) as we have a large codebase that is not expecting to encounter partially written blobs in storage?  

### Expected behavior

After calling `OpenWriteAsync` the new blob should not be visible to blob readers until the writer has finished writing and the stream is disposed.

### Actual behavior

Blob readers can see an empty blob and can read from it whilst the writer is still writing.

If a blob reader calls `OpenReadAsync` and obtains a read stream:
If the read completes before the writer completes the read of an empty blob is successful.
If the writer completes before the reader reads from the stream the reader received a `412 Precondition Failed`

### Reproduction Steps

Setup:
```
const string storageAccountName = "[storage-account-name]";
const string azureStorageScope = "https://storage.azure.com//.default";
const string blobContainerName = "[container-name]";

var serviceUri = new Uri($"https://{storageAccountName}.blob.core.windows.net");
var tokenCredential = new DefaultAzureCredential();
```

Example using `Azure.Storage.Blobs` 12.12.0:
```
var blobServiceClient = new BlobServiceClient(serviceUri, tokenCredential);
var blobContainerClient = blobServiceClient.GetBlobContainerClient(blobContainerName);
var blockBlobClient = blobContainerClient.GetBlockBlobClient("v12");
await using var stream = await blockBlobClient.OpenWriteAsync(true);

Console.WriteLine("v12 stream created, press enter to write data");
Console.ReadLine();
// There's an empty blob visible to readers in the blob container at this point

var buffer = System.Text.Encoding.UTF8.GetBytes("Hello world!");
await stream.WriteAsync(buffer);
```

Whilst waiting for the writer the blob is visible to readers:
![image](https://user-images.githubusercontent.com/282424/176143554-28f4b7df-a372-4713-b9fe-d60d2a445ab0.png)

Example using `Microsoft.Azure.Storage.Blob` 11.2.3:
```
var accessToken = await tokenCredential.GetTokenAsync(new TokenRequestContext(new[] { azureStorageScope }));

var storageAccount = new CloudStorageAccount(new StorageCredentials(new TokenCredential(accessToken.Token)), storageAccountName, null, true);
var blobClient = storageAccount.CreateCloudBlobClient();
var container = blobClient.GetContainerReference(blobContainerName);
var blob = container.GetBlockBlobReference("v11");
await using var stream = await blob.OpenWriteAsync();

Console.WriteLine("v11 stream created, press enter to write data");
Console.ReadLine();
// The blob is not visible to readers in storage at this point

var buffer = System.Text.Encoding.UTF8.GetBytes("Hello world!");
await stream.WriteAsync(buffer);
```

Whilst waiting for input no blob is visible to readers:
![image](https://user-images.githubusercontent.com/282424/176143737-64552589-6e97-4e1a-9333-c5152ccd57e7.png)

**Comment by navba-MSFT** [comment]
Adding Service team to look into this. 

@xgithubtriage could you please look into this issue ?

**Comment by amnguye** [comment]
I think as explained [here](https://github.com/Azure/azure-sdk-for-net/issues/18797#issuecomment-780042389) in the github issue referenced, that OpenWrite is supposed to mimic the [System.IO File.OpenWrite](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.openwrite?view=net-6.0). Even though this is different than the v11 behavior, it's the behavior that it should have been in the first place.

However I do empathize with the difference with the behavior change, and looks like we may need to create another API or options bag to cover the scenario. Though we may have to look into if there's another reason why we create the blob then start performing the stage blocks (in the case this is preventing a different problem from occurring).

Marking as a feature request.

@seanmcc-msft Feel free to chime in.

The only mitigation I can see around this is that there has to be a lot of code written around a Stream and doing manual stage blocks, loading each chunk data into the stream and doing a commit block.
