### ISSUE TITLE
[FEATURE REQ] Support batch message receives with session concurrency

### ISSUE THREAD

**Issue by LouisGordon** [Azure/azure-sdk-for-net#29525]
### Library name

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Please describe the feature.

As noted in this [issue](https://github.com/Azure/azure-sdk-for-net/issues/29505) session concurrency is not supported when messages are received in a batch.

We have a use case for this in our current usage with SQL Server Service Broker that we are needing to replace with another messaging solution.  We receive an extremely high volume of messages that is best received and processed in batches in order to keep the throughput manageable. Sessions are utilized because processing the messages in order is a requirement, and to provide some customer segregation to minimize any product wide impact in the event of an unexpected queue backup.

**Comment by adamyager** [comment]
@JoshLove-msft  @jsquire 
All, I would appreciate some eyes on this one if possible.  This feature was removed in the 7.x releases. Not having it is preventing us from moving to the modernized Library Azure.Messaging.ServiceBus .  At this time we are stuck at Microsoft.Azure.ServiceBus - 5.1.3

We cannot be the only ones so I do ask you help us out by getting some attention on this.

Thanks and let me know if you have any questions!

- Adam

**Comment by JoshLove-msft** [comment]
@adamyager, can you clarify which feature was removed? The Service Bus extension has never supported session concurrency with batches as far as I'm aware.

**Comment by JoshLove-msft** [comment]
As a workaround, you can define your function to receive a single message, and then receive more messages within your function body by binding to the `ServiceBusReceiveActions` as shown in this [sample](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus#binding-to-receiveactions).
