### ISSUE TITLE
[FEATURE REQ] Adding managed RunCommand capabilities

### ISSUE THREAD

**Issue by samir-puranik** [Azure/azure-sdk-for-net#29534]
### Library name

Azure.ResourceManager.Compute

### Please describe the feature.

There is an Azure Compute feature in public preview right now which allows naming of RunCommand execution and retrieval of the status of the RunCommand. [https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command-managed](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/run-command-managed). 

1. Currently, there is no method from `VirtualMachineResource` to deploy a managed run command (hitting the `PUT /subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.Compute/virtualMachines/<vmName>/runcommands/<runCommandName>` endpoint). **I would like to request this feature to be added as an instance method to VirtualMachineResource.**

2. The current `GetVirtualMachineRunCommand` and `GetVirtualMachineRunCommandAsync` methods can properly retrieve the status of the managed RunCommand. These methods can also expand the instanceView which contains the execution output results as long as the `expand` argument is equal to `"instanceView"`. I saw this after sending my own PUT request to the endpoint I mentioned in point (1) using `"TestingRunCommand"` as the runCommandName and `"echo 'Hello'"` as the script in the request body.

    However, the plural method `GetVirtualMachineRunCommands` has no expand parameter and there is no `GetVirtualMachineRunCommandsAsync` method at all. **I would like to request that the expand parameter be added and that GetVirtualMachineRunCommandsAsync be added as well.**

I am in need of this feature as I am building a DevOps service for the Azure Postgres team which will deploy and retrieve the status of these managed scripts. It is necessary for the service to know whether the script execution succeeded and the output of the script execution; this data is contained in the expanded instanceView portion of the `GetVirtualMachineRunCommand` data. However, it is important that deploying the RunCommand and retrieiving the status can be done asynchronously in case of a server failure. Currently, if the RunCommand is executed, but the service fails there is no way of knowing whether a particular virtual machine executed the RunCommand. We are trying to keep this DevOps service stateless, so enabling these features would be very helpful.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hi @samir-puranik , yes, we will support it soon in the stable release this month.

**Comment by samir-puranik** [comment]
Hi @ArthurMa1978, even after stable release I'm still unsure how to deploy named RunCommands to the VM using the SDK. How can I run a *named* RunCommand? I still see that the only parameters for Azure.ResourceManager.Compute.Models.RunCommandInput are:
- CommandId (not the same as name)
- Script (script to run)
- Parameters (parameters to script, if there are any)

**Comment by ArthurMa1978** [comment]
Use the `VirtualMachineRunCommandCollection.CreateOrUpdate`
