### ISSUE TITLE
[FEATURE REQ] Implement ScaleController's Burst Scale Mode Feature

### ISSUE THREAD

**Issue by Tonewall** [Azure/azure-sdk-for-net#29536]
### Library name

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Please describe the feature.

ICM regarding slow scale out: https://portal.microsofticm.com/imp/v3/incidents/details/316361790/home
Need burst scale mode feature implemented to runtime scale monitoring. The ScaleController is already capable of this [ScaleController Logic](https://msazure.visualstudio.com/One/_git/AAPT-Antares-ScaleController?path=/src/Microsoft.Azure.AppService.ScaleController.Extension/ScalerBase.cs&version=GBv2.x&line=290&lineEnd=318&lineStartColumn=12&lineEndColumn=14&lineStyle=plain&_a=contents).
Just need the above logic to be implemented in the ServiceBusScaleMonitor.cs [GetScaleStatusCore()](https://github.com/Azure/azure-sdk-for-net/blob/fcee313b5ecf26d5d3de37dd56d32fd115ee498f/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusScaleMonitor.cs#L206)

**Comment by jsquire** [comment]
@JoshLove-msft :  Would you please triage to add costing and share your thoughts?

**Comment by JoshLove-msft** [comment]
@Tonewall can you please point us to the burst scale mode implementation that you reference?

**Comment by JoshLove-msft** [comment]
> @Tonewall can you please point us to the burst scale mode implementation that you reference?

Nevermind, I see it is in the summary!

**Comment by JoshLove-msft** [comment]
This seems like it should be fairly straightforward. We are already collecting the QueueTime. It would just be a matter of checking the last TriggerMetric instances QueueTime like they do on the host.

**Comment by danielmarbach** [comment]
I'd be happy to give this a go but I would require a bit more insights. Based on the current description that also links to some internal repo that I don't have access to, I'm not sure if there is much I can do

**Comment by jsquire** [comment]
With the target-based scaling improvements and (forthcoming?) efforts to move the scale controller into the extension entirely, I don't believe this is relevant any longer.   I'm going to close this out.   @alrod, @chiangvincent, if you're still planning on this, please reopen.
