### ISSUE TITLE
Update repo structure to support Multiple Profile side-by-side for sdk packages in the default branch

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#2954]
Restructure the repository to allow building multiple profiles of modules side-by-side
- [ ] Update folder structure in the src directory and build components as follows:
   - ClientRuntime
  - (Service)
    - Common
      - library (src files included in packages projects)
      - Tests (src files included in tests)
    - Api-Version[s]
      - (Package-Name)
      - Tests
 

- [ ] Create a profile targets file that allows listing groups of modules by profile.  Predefined profiles will include (stack, latest, latest-stable)
- [ ] Create a solution or proj file with modules and tests for a profile
- [ ] Update msbuild artifacts to allow building modules using a new profile specifier from the targets file
- [ ] Update msbuild artifacts to allow building a particular package by api-version - when no version is specified, the latest version should be built
- [ ] Create documentation for  the following in the documentation repo and replace in the wiki
	- Addign new sdk
	- Adding sdks for a new api version
	- Updating sdks in an existing api-version

**Comment by shahabhijeet** [comment]
This is done for 9 RPs and have been checked into a separate branch.
We need more information on what exactly needs to happen as the plans have changed recently for profiles.
Closing this issue, will either reopen or create a new issue with new information on the task
