### ISSUE TITLE
Document bug: maxRetryWaitTimeOnThrottledRequests is TimeSpan , not seconds

### ISSUE THREAD

**Issue by emreaydinceren** [Azure/azure-sdk-for-net#29567]
It is not in seconds, it is TimeSpan.

maxRetryWaitTimeOnThrottledRequests
[TimeSpan](https://docs.microsoft.com/en-us/dotnet/api/system.timespan)
The maximum retry time **in seconds** for the Azure Cosmos DB service. Any interval that is smaller than a second will be ignored.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 467fedcc-02e5-1451-c190-fce85a13f92d
* Version Independent ID: bef0159c-252b-5ac0-aab7-b9ebc58e0135
* Content: [CosmosClientBuilder.WithThrottlingRetryOptions(TimeSpan, Int32) Method (Microsoft.Azure.Cosmos.Fluent) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.fluent.cosmosclientbuilder.withthrottlingretryoptions?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.Cosmos.Fluent/CosmosClientBuilder.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos.Fluent/CosmosClientBuilder.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@emreaydinceren We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@emreaydinceren The PR for the fix has been created and it will be merged once approved. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
