### ISSUE TITLE
[FEATURE REQ] Manage the registry

### ISSUE THREAD

**Issue by crgarcia12** [Azure/azure-sdk-for-net#29573]
### Library name

Azure.Containers.ContainerRegistry

### Please describe the feature.

It would be very useful to be able to query the private endpoints and replicas associated with a registry.
This is needed, for example, to be able to configure DNS entries when new registries are created, or to configure image scanning services via EventGrid triggers

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by annelo-msft** [comment]
@crgarcia12, would you please provide more information regarding specifically which ACR REST endpoints you would like to call with the SDK and what is failing for you?  Thanks!
