### ISSUE TITLE
[QUERY] QueueMessage sample for complex types

### ISSUE THREAD

**Issue by svrooij** [Azure/azure-sdk-for-net#29579]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage.Queues 5.0.1

### Query/Question

We are currently using the `IAsyncCollector<SomeType>` to push message the a regular storage queue. This works great, but we want to control the `VisibilityTimeout`. So we want to migrate to the `QueueClient` binding, which provides us with the `queueClient.SendAsync(BinaryData data, TimeSpan? visibilityTimeout)` method.

How do we serialize SomeType (complex object) to `BinaryData`, in such a way we don't need to change the processing function, which uses `[QueueTrigger("queue-name", Connection = "AzureWebJobsStorage")] SomeType queueItem,`.

Is it JSON? Newtonsoft vs System.Text.JSON
Or something else (MessagePack, XML)?
Default serializer settings?

I've checked the [examples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues#examples) but the only show how to relay messages from one queue to the next and not how to push messages with the visibility timeout or even how to create the binary data for the queues

Providing this as an extension would also be great, that way people can use all the goodies with the QueueClient, without the complexity of serializing, since that would be done by the same version of the library. Something like:

```csharp
queueClient.SendMessage<T>(T complexObject, TimeSpan? visibilityTimeout = null, TimeSpan? timeToLive = null, CancellationToken cancellationToken = default); 
```

### Environment

Hosting in Azure Functions (4.6.1.18388), .NET 6

**Comment by SaurabhSharma-MSFT** [comment]
@svrooij We are looking into it and get back to you for any additional information.

**Comment by RakeshMohanMSFT** [comment]
@svrooij [UpdateMessageAsync](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient.updatemessageasync)  method can change a message's visibility timeout and contents.


The below article has sample code that updates the queue message with new contents, and sets the visibility timeout to extend another 60 seconds.

https://docs.microsoft.com/en-us/azure/storage/queues/storage-dotnet-how-to-use-queues?tabs=dotnet#change-the-contents-of-a-queued-message

Let me get back to you regarding complex object to binarydata question shortly.

**Comment by svrooij** [comment]
@RakeshMohanMSFT it's NOT about updating a message it's about creating a new message and sending it to the queue. Someone else already told me you're using Newtonsoft.Json so it would be nice to have an extension that does the serialization.

```csharp
queueClient.SendMessage<T>(T complexObject, TimeSpan? visibilityTimeout = null, TimeSpan? timeToLive = null, CancellationToken cancellationToken = default); 
```

**Comment by svrooij** [comment]
@RakeshMohanMSFT something like:

```csharp
// Im not sure what it should return probably the same as SendMessageAsync
public static Task<?> SendMessageAsync<T>(this QueueClient client, T complexObject, TimeSpan? visibilityTimeout = null, TimeSpan? timeToLive = null, CancellationToken cancellationToken = default) {
  BinaryData data = .... // Serialize complexObject to BinaryData in the way the library does
  return client.SendMessageAsync(data, visibilityTimeout, timeToLive, cancellationToken);
}
```

**Comment by benjaminsampica** [comment]
You can use `BinaryData.FromObjectAsJson<T>()` to at least make it work similarly. Example:

```
BinaryData.FromObjectAsJson(new Todo { Title = "Title" });
```

**Comment by svrooij** [comment]
@benjaminsampica thanks for the answer, will check this out soon. Not sure if it was available when I asked the question.
