### ISSUE TITLE
Update Key Vault documentation

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-net#29589]
### Library name

Azure.Security.KeyVault.Keys

### Please describe the feature.

We need to update the Key Vault documentation in a few places:

- [ ] **Authentication in Samples:** Our samples should show the use of Managed Identity instead of Service Principals with Client Secrets as the default authentication method. We can still show how to use the former for scenarios where the use of Managed Identity is not possible.
- [x] **Cryptographic operations using CBC and CBCPAD:** We should make it clear that there are some considerations to have when using these algorithms for local cryptographic operations using our clients:
  - We should add a notice similar to the following:
    > Microsoft recommends you not use CBC without first ensuring the integrity of the ciphertext using an HMAC, for example. See https://docs.microsoft.com/dotnet/standard/security/vulnerabilities-cbc-mode for more information.
  - When it comes to a user provided IV, we should make it clear that if they pass their own IV, they need to make sure they use a cryptographically random, non-repeating IV. Here's an example:
    > Optional initialization vector (IV). If you pass your own IV, make sure you use a cryptographically random, non-repeating IV. If null, a cryptographically random IV will be choosing using {RandomNumberGenerator | whatever cryptorng your language provides}.
- [x] **`ExpiresIn` in [`KeyRotationPolicy`](https://github.com/Azure/azure-sdk-for-net/blob/f4aff97fe7323c18deb6956846cee793da048274/sdk/keyvault/Azure.Security.KeyVault.Keys/src/KeyRotationPolicy.cs):** Currently, the docstring for this parameter makes it sound like it pertains to the expiration time of the key rotation policy, when it should refer to the expiration of a newly rotated key, as rotation policies don't actually expire. [Here](https://github.com/Azure/azure-rest-api-specs/blob/4df2a54d4876b69703bff4ab6651f7f5f5761ea7/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.3/keys.json#L2222)'s what the swagger documentation says about the `expiryTime` parameter. We can also refer to the verbiage used in [Java](https://github.com/Azure/azure-sdk-for-java/blob/8d85737b76966168786f5f062af87bf9e3e5b80a/sdk/keyvault/azure-security-keyvault-keys/src/main/java/com/azure/security/keyvault/keys/models/KeyRotationPolicy.java#L66), [Python](https://github.com/Azure/azure-sdk-for-python/blob/1081acd696bb5d2eb563d2071060d8f86e823603/sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py#L328) or [Javascript](https://github.com/Azure/azure-sdk-for-js/blob/6647fb87d59ae4d479f033bb53258dccc6e5347b/sdk/keyvault/keyvault-keys/src/keysModels.ts#L634).

**Comment by heaths** [comment]
For the last 2 bullets can we just do that as a change to the swagger docs? It's non-breaking. I've already approved and merged a couple of doc updates for @chlowell for Go, for example.

**Comment by vcolin7** [comment]
> For the last 2 bullets can we just do that as a change to the swagger docs? It's non-breaking. I've already approved and merged a couple of doc updates for @chlowell for Go, for example.

That should be fine, although for the last bullet the swagger already mentions the expiration time refers to the key, as opposed to what .NET does

**Comment by heaths** [comment]
.NET isn't generated, but I usually took the string from swagger. Interesting. I'll be sure to update it, though.

**Comment by vcolin7** [comment]
I actually noticed that all languages have their own flavor for the `expiresIn` docstring, which makes me think our public layer is not auto-generated for any language.

**Comment by vcolin7** [comment]
You can refer to [this Java PR](https://github.com/Azure/azure-sdk-for-java/pull/29996) for the second item (CBC crypto).
