### ISSUE TITLE
Failed to find metric configuration for provider

### ISSUE THREAD

**Issue by ArkeBcacy** [Azure/azure-sdk-for-net#29584]
### Library name and version

Azure.Monitor.Query 1.1.0

### Query/Question

I'm attempting to use the MetricQueryClient with a resource id, but I'm only getting the following error:

Service request failed.
Status: 400 (Failed to find metric configuration for provider: microsoft.operationalinsights, resource Type: workspaces, metric: PublicationView, Valid metrics: Average_% Free Inodes,Average_% Free Space,Average_% Used Inodes,Average_% Used Space,Average_Disk Read Bytes/sec,Average_Disk Reads/sec,Average_Disk Transfers/sec,Average_Disk Write Bytes/sec,Average_Disk Writes/sec,Average_Free Megabytes,Average_Logical Disk Bytes/sec,Average_% Available Memory,Average_% Available Swap Space,Average_% Used Memory,Average_% Use)

Content:
{"code":"BadRequest","message":"Failed to find metric configuration for provider: microsoft.operationalinsights, resource Type: workspaces, metric: PublicationView, 
Valid metrics: Average_% Free Inodes,Average_% Free Space,Average_% Used Inodes,Average_% Used Space,Average_Disk Read Bytes/sec,Average_Disk Reads/sec,Average_Disk Transfers/sec,
Average_Disk Write Bytes/sec,Average_Disk Writes/sec,Average_Free Megabytes,Average_Logical Disk Bytes/sec,Average_% Available Memory,Average_% Available Swap Space,
Average_% Used Memory,Average_% Used Swap Space,Average_Available MBytes Memory,Average_Available MBytes Swap,Average_Page Reads/sec,Average_Page Writes/sec,Average_Pages/sec,
Average_Used MBytes Swap Space,Average_Used Memory MBytes,Average_Total Bytes Transmitted,Average_Total Bytes Received,Average_Total Bytes,Average_Total Packets Transmitted,
Average_Total Packets Received,Average_Total Rx Errors,Average_Total Tx Errors,Average_Total Collisions,Average_Avg. Disk sec/Read,Average_Avg. Disk sec/Transfer,
Average_Avg. Disk sec/Write,Average_Physical Disk Bytes/sec,Average_Pct Privileged Time,Average_Pct User Time,Average_Used Memory kBytes,Average_Virtual Shared Memory,Average_% DPC Time,
Average_% Idle Time,Average_% Interrupt Time,Average_% IO Wait Time,Average_% Nice Time,Average_% Privileged Time,Average_% Processor Time,Average_% User Time,Average_Free Physical Memory,
Average_Free Space in Paging Files,Average_Free Virtual Memory,Average_Processes,Average_Size Stored In Paging Files,Average_Uptime,Average_Users,Average_Current Disk Queue Length,
Average_Available MBytes,Average_% Committed Bytes In Use,Average_Bytes Received/sec,Average_Bytes Sent/sec,Average_Bytes Total/sec,Average_Processor Queue Length,Heartbeat,Update,Event"}

Headers:
Cache-Control: no-cache
x-ms-request-id: {f45ceb4e-9258-437e-b430-15bb73ca4a49}
Request-Context: REDACTED
Access-Control-Expose-Headers: REDACTED
Server: Microsoft-IIS/10.0
X-AspNet-Version: REDACTED
X-Powered-By: REDACTED
x-ms-ratelimit-remaining-subscription-reads: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Wed, 29 Jun 2022 21:07:44 GMT
Content-Length: 1760
Content-Type: application/json

A similar query is run with the LogsQueryClient and there are no issues with that.

Is there something I need to configure in the client or workspace to query "AppMetrics"?

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.420 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.106 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Visual Studio 2022 64-bit 17.2.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by scottaddie** [comment]
>Is there something I need to configure in the client or workspace to query "AppMetrics"?

@ArkeBcacy To query the _AppMetrics_ table in the Log Analytics workspace, you'll need to use the `LogsQueryClient`. `MetricsQueryClient` is intended for fetching specific metrics on an Azure resource. For example, fetching the "ServiceApiLatency", "Availability", "SaturationShoebox", etc. metrics from an Azure Key Vault resource. Does that help?

**Comment by ArkeBcacy** [comment]
@scottaddie Yes, this got resolved using the LogsQueryClient instead of MetricsQueryClient. Thank You!
