### ISSUE TITLE
[QUERY] ProcessingStoppedReason for DeveloperCodeException / EventHubsException

### ISSUE THREAD

**Issue by rzepinskip** [Azure/azure-sdk-for-net#29581]
### Library name and version

Azure.Messaging.EventHubs 5.7.0

### Query/Question

Hi! Is there any reason why `ProcessingStoppedReason` is set to `OwnershipLost` when partition processing task was faulted due to exception thrown in user code (`DeveloperCodeException`) or because particular consumer group does not exists (`EventHubsException`)? I find it a little misleading. What about having another value (`UnhandledProcessingError`?) for that case?

I think it is caused by [partitionProcessor.ProcessingTask.IsCompleted](https://github.com/Azure/azure-sdk-for-net/blob/c729d6528a5361141cf225247d38df6b96c5d926/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L1673) check.

**Comment by jsquire** [comment]
I confirmed that changing the reason would be considered a behavioral breaking change, despite it being fairly low risk.  I don't think there's enough value in the proposed change for me to justify driving a breaking change exception request across all languages.  The reason will need to remain "OwnershipLost" for now.

To help better detect the scenario where the event processing handler is not following guidance and exceptions are allowed to propagate, I added a new warning that will be surfaced to the processor error handler that describes the scenario and offers guidance for mitigation.  This should give better visibility to the scenario for applications that are not capturing/monitoring SDK logs.

I also fixed the oversight on validation at startup; the processor will now refuse to start if the consumer group is not valid.  

I'm going to mark this as addressed; please feel free to unresolve if you'd like to discuss further.
