### ISSUE TITLE
remarks should include supported types

### ISSUE THREAD

**Issue by drdamour** [Azure/azure-sdk-for-net#29587]
i believe the remarks section should list the supported types for serialization similar to how https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.message.userproperties?view=azure-dotnet#remarks does

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b3d2174c-94d8-708b-a44e-730fb9da960a
* Version Independent ID: d946b2ec-e2ed-7247-738f-adf24a3703ba
* Content: [EventData.Properties Property (Azure.Messaging.EventHubs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventdata.properties?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.EventHubs/EventData.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.EventHubs/EventData.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @drdamour.   Thank you for your feedback.   I think this is a good idea; I'll get it added in.
