### ISSUE TITLE
[Container Registry] CanUploadOciManifest failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29605]
Container Registry nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 400 (Bad Request)
> 
> Content:
> {"errors":[{"code":"MANIFEST_BLOB_UNKNOWN","message":"blob unknown to registry","detail":"sha256:d25b42d3dbad5361ed2d909624d899e7254a822c9a632b582ebd3a44f9b0dbc8"}]}
> 
> Headers:
> Server: openresty
> Date: Thu, 30 Jun 2022 18:39:30 GMT
> Connection: keep-alive
> Access-Control-Expose-Headers: REDACTED
> Docker-Distribution-Api-Version: REDACTED
> Strict-Transport-Security: REDACTED
> X-Content-Type-Options: REDACTED
> X-Ms-Client-Request-Id: 278258d4-aabf-4f5d-9cf1-99faeeeab1ce
> X-Ms-Correlation-Request-Id: REDACTED
> X-Ms-Request-Id: af953710-a8f7-46a2-b8bd-c259a6448256
> Content-Type: application/json; charset=utf-8
> Content-Length: 166
> 
> 
> Stack trace
>    at Azure.Containers.ContainerRegistry.ContainerRegistryRestClient.CreateManifest(String name, String reference, Stream payload, String contentType, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Generated/ContainerRegistryRestClient.cs:line 256
>    at Azure.Containers.ContainerRegistry.Specialized.ContainerRegistryBlobClient.UploadManifest(OciManifest manifest, UploadManifestOptions options, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ContainerRegistryBlobClient.cs:line 150
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 166
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRegistryBlobClientLiveTests.CanUploadOciManifest() in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRegistryBlobClientLiveTests.cs:line 59
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1678136&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
This is likely related to the [Azure Networking incident](https://portal.microsofticm.com/imp/v3/incidents/details/317207710/home) impacting Storage.   Closing this out for now, if tests continue to fail we can revisit.
