### ISSUE TITLE
[App Configuration] GetIfChangedSettingModified failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29603]
App Configuration nightly test runs are failing with:

> Error message
> Expected: True
> But was:  False
> 
> 
> Stack trace
>    at Azure.Data.AppConfiguration.Tests.ConfigurationLiveTests.GetIfChangedSettingModified() in /Users/runner/work/1/s/sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationLiveTests.cs:line 792
>    at Azure.Data.AppConfiguration.Tests.ConfigurationLiveTests.GetIfChangedSettingModified() in /Users/runner/work/1/s/sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationLiveTests.cs:line 797
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1677469&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
No changes were made to AppConfig since Feb 2022.   This may be related to the [Azure Networking incident](https://portal.microsofticm.com/imp/v3/incidents/details/317207710/home) or may be the result of service changes.  We'll continue to monitor for now, if tests continue to fail next week, we'll follow-up.

**Comment by jsquire** [comment]
Looks like this is unrelated to the outage;  @DivineNwaokocha, since you're working in AppConfig, do you mind taking a look at the tests and seeing if there's something that needs adjustment?


//cc: @ShivangiReja
