### ISSUE TITLE
[Container Registry] CanDeleteRepository failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29604]
Container Registry nightly test runs are failing with:

> Error message
> Expected: <Azure.RequestFailedException>
> But was:  null
> 
> 
> Stack trace
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRepositoryLiveTests.CanDeleteRepository() in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRepositoryLiveTests.cs:line 118
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRepositoryLiveTests.CanDeleteRepository() in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRepositoryLiveTests.cs:line 127
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1678136&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
This is likely related to the [Azure Networking incident](https://portal.microsofticm.com/imp/v3/incidents/details/317207710/home) impacting Storage.   Closing this out for now, if tests continue to fail we can revisit.
