### ISSUE TITLE
Automatically deprecate new package publishes if the package is already deprecated

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#29611]
If we deprecate a package and all its versions but we need to publish a servicing fix for it we want to have the publishing step automatically deprecate this new published version as well. Currently nuget doesn't support this feature natively but there are some potential rest APIs we can use to see if the current versions are deprecated and if so we can deprecate the new release. Whoever picks up this work please talk with @weshaggard to get some pointers.

**Comment by weshaggard** [comment]
Yes these are usually security type fixes and this has happened a few times for older cosmos packages for example.

**Comment by pallavit** [comment]
Do we have to do security fixes to a deprecated packages always or until the 3 year mark?

**Comment by weshaggard** [comment]
Yes unfortunately we do in some cases. It isn't super clear the exact timelines but it is generally driven by support contracts.

**Comment by weshaggard** [comment]
The core logic to automatically deprecate packages has been added in https://github.com/Azure/azure-sdk/pull/5808 thansk @mario-guerra. We still need to get it enabled to run periodically that is work left for me to do and is tracked by this issue.
