### ISSUE TITLE
Azure.AI.Personalizer is using a newer version of System.Text.Json

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#29613]
_sdk/personalizer/Azure.AI.Personalizer/src/Azure.AI.Personalizer.csproj_ is using a `@VersionOverride` for _System.Text.Json_ which can prevent customers from using this on older versions of .NET. Note that our [guidelines state you must target `netstandard2.0`](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-build-net-standard), and using _System.Text.Json_ 6.0.1 can hinder this.

Looking at the build errors if you remove `@VersionOverride`, it seems you're relying on a new attribute property that should be unnecessary because collection properties should never be null:

* [❌ DO NOT return null values from collection properties or from methods returning collections. Return an empty collection or an empty array instead](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#:~:text=DO%20NOT%20return%20null%20values%20from%20collection%20properties)

And if you haven't GA'd yet, note that we also have a guideline to use interfaces for collection properties:

* [☑️ YOU SHOULD use the following collection types for properties of model types ...](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-service-return-model-collections)

We have helper classes we use internally for generated code - which we generally recommend you use anyway - but you can use these manually as well. See the following source files for an example:

* https://github.com/Azure/azure-sdk-for-net/blob/350e1ce4fbdf59af14d6df7a991d71ac79666d19/sdk/keyvault/Azure.Security.KeyVault.Administration/src/Generated/Models/KeyVaultRoleDefinition.cs#L57
* https://github.com/Azure/azure-sdk-for-net/blob/350e1ce4fbdf59af14d6df7a991d71ac79666d19/sdk/keyvault/Azure.Security.KeyVault.Administration/src/Generated/Models/KeyVaultRoleDefinition.Serialization.cs#L36-L45

**Comment by pallavit** [comment]
This issue has been fixed - https://github.com/Azure/azure-sdk-for-net/blob/64386052196f8f8293367c8b24dc42ae48d8a7fc/sdk/personalizer/Azure.AI.Personalizer/src/Azure.AI.Personalizer.csproj#L25. Please feel free to reopen if you think otherwise.
