### ISSUE TITLE
[QUERY] Tables: Enum storage and query differences

### ISSUE THREAD

**Issue by RDavis3000** [Azure/azure-sdk-for-net#29623]
### Library name and version

Azure.Data.Tables 12.4.0.0

### Query/Question

I have an ITableEntity which contains an enum field:

```
public enum InstanceStates
    {
        Running,
        Closed,
        Faulted
    }

 public class InstanceTableEntity : ITableEntity
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; }
        public Guid IngestionRequestId { get; set; }
        public string Description { get; set; }
        public InstanceStates State { get; set; }
}
```

When I store it using :

```
                var tableClient = GetTableClient(tableName);
                var response = await tableClient.AddEntityAsync<T>(tableEntity);
```
It appears in Storage Explorer as a string value (e.g. "Running"), and when I retrieve the record, the enum is properly typed and appears in the debugger as a string (ide sugar?).

But when I am querying the table using:

```
Guid someGuid;
Expression<Func<StepTableEntity, bool>> query = (a) => a.PartitionKey == someGuid.toString() && (a.State == InstanceStates.Closed || a.State == InstanceStates.Faulted);
var tableClient = GetTableClient(tableName);
var queryResults = tableClient.QueryAsync<T>(query,null,null);
```

My results are always empty. Looking at the debugView of the query expression:
.Lambda #Lambda1<System.Func`2[LXRP.RIM.Ingestion.Shared.IngestionOperations.StepTableEntity,System.Boolean]>(LXRP.RIM.Ingestion.Shared.IngestionOperations.StepTableEntity $a)
{
    $a.PartitionKey == .Call (.Constant<LXRP.RIM.Ingestion.Console.Program+<>c__DisplayClass0_0>(LXRP.RIM.Ingestion.Console.Program+<>c__DisplayClass0_0).someGuid).ToString()
    && ((System.Int32)$a.State == 1 || (System.Int32)$a.State == 2)
}

No combination of casting/converting/toString() that I can think of has worked.
It looks like the underlying integer and the string representation are getting mixed up somewhere maybe? Or am I just doing it wrong? What's the right way to query against enums in this situation?

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.420 [C:\Program Files\dotnet\sdk]
  5.0.409 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Visual Studio 

Microsoft Visual Studio Community 2022
Version 17.2.5
VisualStudio.17.Release/17.2.5+32616.157
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools 2019   17.2.393.26812
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   17.2.393.26812
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.2.393.26812
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.2.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.0.0.2218101+885a343b00bcab620a90c1550c37dafd730ce984
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62204.01010
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10418.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.2.0-4.22281.5+8d3180e5f00d42f0f0295165f756f368f0cbfa44
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22274.4+211fd760c2315d73cfa0d375fe64abb346bc1096
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

**Comment by RDavis3000** [comment]
Ok so this works, but its not nice. 
I think the == operator is borked for enum in this instance

`Expression<Func<StepTableEntity, bool>> query = (a) => a.PartitionKey == someGuid.ToString() && a.State.Equals(InstanceStates.Closed.ToString()); `

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Tracking this as a feature request in #29644
