### ISSUE TITLE
The response of ListAsync has no link to the next page

### ISSUE THREAD

**Issue by sheiwangwo** [Azure/azure-sdk-for-net#29626]
We are using ListAsync to get job list, but the response contains 300 items at most(When we are sure the number of jobs is more than 300). 

The docs of this api shows that "the response includes a link to the next page of results, if any."(https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datalake.analytics.joboperationsextensions.listasync?view=azure-dotnet). 
But the link to the next page is "null" in fact, is there any problem here?

Could you please help us find the way to get the job list with more than 300 items by the ADLA api?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7866947b-2e10-0703-2e36-2191dbf25ae7
* Version Independent ID: fcea1d2a-d7b3-a25c-1188-e2b6096deee7
* Content: [JobOperationsExtensions.ListAsync Method (Microsoft.Azure.Batch.Protocol) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.protocol.joboperationsextensions.listasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Batch.Protocol/JobOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Batch.Protocol/JobOperationsExtensions.xml)
* Service: **batch**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@sheiwangwo I could see the same behavior in my local environment and checking internally on the same.  
![image](https://user-images.githubusercontent.com/38112130/180893340-08d04e00-99bc-4cd9-b2bc-8934e03f5e29.png)
