### ISSUE TITLE
[FEATURE REQ] Tables filter expressions should automatically translate `enum` typed properties to their string value

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#29644]
### Library name

Azure.Data.Tables

### Please describe the feature.

Given an entity type with an enum typed member as below, filter expression queries do not translate automatically to their expected string format.

ex.
```c#
public enum MyEnum
    {
        Zero,
        One
    }

 public class MyEntity: ITableEntity
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; }
        public MyEnum EnumProperty { get; set; }
}
```

The following filter expression 
```c#
ent => ent.MyFoo == Foo.One)
```
produces the filter `EnumProperty eq 1`.

The expected filter should be: `EnumProperty eq 'One'`

In order to create the correct query filter today, the following query must be written: 
```c#
ent => ent.EnumProperty.Equals(Foo.One.ToString());
```

**Comment by SlyckLizzie** [comment]
It's 2024 now. Any update on the progress?

**Comment by christothes** [comment]
Looking at this again, my concern is that this would be a behavioral breaking change for any code that relies on the current behavior.

**Comment by SlyckLizzie** [comment]
So it won't get fixed because the problem is a breaking change?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
