### ISSUE TITLE
Unable to add FieldMappings to a new SearchIndexer object

### ISSUE THREAD

**Issue by williamBurgeson** [Azure/azure-sdk-for-net#29640]
I am upgrading a library for my current company from .net core 3.1 to .net 6.0, and as part of that upgrade I have swapped out the old Azure lib `Microsoft.Azure.Search` for the new one `Azure.Search.Documents` (v11). I am currently attempting to migrate a block of code which built an Indexer object (now SearchIndexer) however I find that I am unable to either add or initialise any FieldMappings, which the existing code does contain.
Looking at the documentation and also Github repo for the component I see that the setter was removed for the FieldMappings collection however there doesn't seem to be any way now to add Field Mappings, which as far as I can tell *are* supported when using raw JSON.
Here is the original code
```
var indexer = new Indexer
            {
                Name = blobIndexerName,
                DataSourceName = dataSourceName,
                TargetIndexName = $"{AzureSearch.IndexName}-{env}",
                Schedule = new IndexingSchedule(TimeSpan.FromMinutes(5)),
                Parameters = new IndexingParameters
                {
                    Configuration = new Dictionary<string, object>
                    {
                        { "excludedFileNameExtensions", ".pdf" },
                        { "skipContent", false },
                        { "useJsonParser", false },
                        { "failOnUnprocessableDocument", false },
                        {
                           "indexStorageMetadataOnlyForOversizedDocuments",
                           true
                        }
                    }
                },
                FieldMappings = new List<FieldMapping>
                {
                    new FieldMapping("metadata_storage_name", "id"),
                    new FieldMapping("metadata_storage_name", "storage_name"),
                    new FieldMapping(
                       "metadata_storage_last_modified",
                       "storage_last_modified")
                }
            };
```

I also noticed under the `Configuration` property I do not seem to be able to set all of the sub properties (`skipContent` and `useJsonParser` although I'm not 100% sure if this matters.

**Comment by jsquire** [comment]
Hi @williamBurgeson.   Thank you for reaching out and we regret that you're experiencing difficulties.   The Azure SDK pattern for collection types is that they read-only and initialized with an empty collection that can be modified.  This is based on the [Framework Design Guidelines - Guidelines for Collections](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values).   

These properties can be set by either using the initializer syntax or adding items to the collection.   From your example, using the initializer syntax would require just removing the `new` expression for the collections and look similar to:

```csharp
var indexer = new Indexer
{
    Name = blobIndexerName,
    DataSourceName = dataSourceName,
    TargetIndexName = $"{AzureSearch.IndexName}-{env}",
    Schedule = new IndexingSchedule(TimeSpan.FromMinutes(5)),
    Parameters = new IndexingParameters
    {
        Configuration = 
        {
            { "excludedFileNameExtensions", ".pdf" },
            { "skipContent", false },
            { "useJsonParser", false },
            { "failOnUnprocessableDocument", false },
            {"indexStorageMetadataOnlyForOversizedDocuments", true }
        }
    },
    FieldMappings = 
    {
        new FieldMapping("metadata_storage_name", "id"),
        new FieldMapping("metadata_storage_name", "storage_name"),
        new FieldMapping("metadata_storage_last_modified", "storage_last_modified")
    }
};
```

Alternatively, it is possible to manipulate the existing collection:

```csharp
var indexer = new Indexer
{
    Name = blobIndexerName,
    DataSourceName = dataSourceName,
    TargetIndexName = $"{AzureSearch.IndexName}-{env}",
    Schedule = new IndexingSchedule(TimeSpan.FromMinutes(5)),
    Parameters = new IndexingParameters(),
};

indexer.Parameters.Configuration["excludedFileNameExtensions"] = ".pdf";
indexer.Parameters.Configuration["skipContent"] = false;
// ... SNIP ...

indexer.FieldMappings.Add(new FieldMapping("metadata_storage_name", "id"));
indexer.FieldMappings.Add(new FieldMapping("metadata_storage_name", "storage_name"));
// ... SNIP ...
```

**Comment by jsquire** [comment]
I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by williamBurgeson** [comment]
Thank you for this. Could you consider mentioning this in the docs as I'm sure there will be other people with similar issues where they need to upgrae legacy code and would be used to the pattern of being able to use the standard initialiser for a complex object.
