### ISSUE TITLE
[QUERY] Fetching a schema by a consistent identifier

### ISSUE THREAD

**Issue by remoba** [Azure/azure-sdk-for-net#29647]
### Library name and version

Azure.Data.SchemaRegistry 1.2.0

### Query/Question

According to the docs, retrieving a schema from the schema registry can only be done by using the schema Id. As far as I understand the schema Id is assigned by the schema registry upon creation, and will be different per environment. 

My service is deployed in a number of different environments, and I don't want to be dependent on the Id that the schema registry generated in each such environment. Therefore I would like to use a shared identifier that would be consistent across the different environments.

Is there a way for me to retrieve a schema by it's group name + name? Alternatively, can I control / set the schema Id during schema creation?

**Comment by jsquire** [comment]
Hi @remoba.   Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, what you're looking to do are limited by the available service operations and are not behaviors that the client has control over.  If you're curious about the details, the API spec for the service can be found [here](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/schemaregistry/data-plane/Microsoft.EventHub/stable/2021-10).   

To answer your specific questions:

  > I understand the schema Id is assigned by the schema registry upon creation, and will be different per environment

  Assuming each environment is using a different Schema Registry resource, this is correct.

> Is there a way for me to retrieve a schema by it's group name + name

If there is not.   If you have the content of the schema, you can query the id by using the content, group name, name, and format.   _([example](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/schemaregistry/Azure.Data.SchemaRegistry#retrieve-a-schema-id))_

> can I control / set the schema Id during schema creation?

This is not something that can be provided; the service will always generate the Id.

**Comment by stavavram** [comment]
Hi @jsquire 
I noticed that these APIs we need exist

Examples:
- Get schema content by schema group, schema name, and version

`https://stav-test.servicebus.windows.net/$schemagroups/<SCHEMA_GROUP>/schemas/<SCHEMA_NAME>/versions/<VERSION>?api-version=2020-09-01-preview`

- Get all schemas in schema group 
https://stav-test.servicebus.windows.net/$schemagroups/<SCHEMA_GROUP>/schemas?api-version=2020-09-01-preview

Is there a reason that they are not exposed in the schema registry client?

**Comment by jsquire** [comment]
@stavavram:  I don't have historical context, but the endpoints that you've referenced do not exist in the [REST API spec](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/schemaregistry/data-plane/Microsoft.EventHub/stable/) that the client is based on.  It appears that the last update to the spec was back in November via #15855.

@hmlam, @nickghardwick, @kasun04 - Do you folks have any insight into these endpoints and why they're not included in the API spec?

**Comment by jsquire** [comment]
> We just want to know if we can use them or if you intend to support them in Azure.Data.SchemaRegistry client in the near future?

The client cannot support service endpoints without an approved REST API specification.   Without understanding service plans, I can't offer insight here.   We'll need the folks that I pinged above for that information.

**Comment by stavavram** [comment]
@hmlam , @nickghardwick, @kasun04, @jsquire  - Are you familiar with these endpoints? Can we use them?
