### ISSUE TITLE
Configuring EventProcessorHost registration timeouts

### ISSUE THREAD

**Issue by vincent-partusch-aveva** [Azure/azure-sdk-for-net#29642]
### Library name and version

Microsoft.Azure.EventHubs.Processor 4.3.2

### Query/Question

We have been intermittently running into SocketExceptions in our application when registering EventProcessors. When we register our EventProcessors by calling _eventProcessorHost.RegisterEventProcessorAsync  we pass in an EventProcessorOptions object with the RecieveTimeout property set to 10 seconds. This is because we want to invoke the processor after 10 seconds regardless of whether there are any events (InvokeProessorAfterReceiveTimeout = true). However, it seems that this ReceiveTimeout property is also being used for the timeout when making registration calls (see: [azure-sdk-for-net/EventProcessorHost.cs at main · Azure/azure-sdk-for-net · GitHub](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fblob%2Fmain%2Fsdk%2Feventhub%2FMicrosoft.Azure.EventHubs.Processor%2Fsrc%2FEventProcessorHost.cs%23%3A~%3Atext%3D%2F%2F%2520Override%2520operation%2C.ReceiveTimeout%253B&data=05%7C01%7CMVANHORN%40microsoftsupport.com%7Cc0198697aa5c4e8e6fa208da59f624c7%7Cb4c546a47dac46a6a7dded822a11efd3%7C0%7C0%7C637921210971660487%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dfibFVCmVu5gW47cF5mVUwf9Rqf5f8RFDH7%2BIx5usvY%3D&reserved=0)). When I change that parameter to something larger like a minute, the SocketExceptions stop happening.

It seems to me that these two timeouts (the receive timeout and timeout for registration operations) are logically distinct and should be configurable separately. Is there a reason that these are being set to the same thing? Is there any workaround to still have the processor be invoked at least every 10 seconds while allowing for a longer timeout on other operations?

### Environment

Our application runs in a Service Fabric cluster on a vm scale set.

**Comment by SaurabhSharma-MSFT** [comment]
@vincent-partusch-aveva I am routing this to services team to provide answer to your ask.

**Comment by vincent-partusch-aveva** [comment]
@SaurabhSharma-MSFT  Hi, has someone been able to look into this issue?

**Comment by jsquire** [comment]
Because the `Microsoft.Azure.EventHubs.Processor` library has been deprecated, it is only receiving critical fixes.  This has been confirmed as not meeting that bar.  The recommended mitigation is to migrate to the `Azure.Messaging.EventHubs` family of packages.
