### ISSUE TITLE
[QUERY] Non-read SDK API may lead to unexpected exception when transient error happens? 

### ISSUE THREAD

**Issue by rmt2021** [Azure/azure-sdk-for-net#29673]
### Library name and version

Azure.Storage 12.2.0

### Query/Question

When a non-read Storage SDK API is called (HTTP method is not GET, e.g., `DeleteQueueMessage` of Queue service will send a DELETE request to the cloud), it is possible for transient errors (e.g., timeout or package drop) to happen, and the response will not arrive at the client on time, so the SDK will send a retry request again. However, if the effect of the first request has already taken place, the retry request would lead to an unexpected exception. For instance:

1. `DeleteQueueMessage` sends a deletion request to delete a Queue message
2. The request arrives the remote, and the message has been successfully deleted
3. A response will be returned to the client but it never arrives the client due to the transient error (e.g., timeout), or the effect actually happens in the remote but the HTTP status code is 500 Internal Server Error 
4. SDK will send another retry request to delete the message again 
5. Since the message has already been deleted successfully in the first request, a 404 MessageNotFound will be thrown in the `RequestFailedException`. 

Similar cases also happen when using other non-read APIs, and other error codes may appear (409, 400 or 412) due to the transient error. We wonder whether there is a way to handle the transient error better instead of blindly retrying for these non-idempotent SDK APIs.

Also, how could we distinguish the cases led by contention error or transient error? For example, a 409 may be led either by multiple instances competing for the resource or the retry after transient error.  
 

### Environment

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.407\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

@xgithubtriage Could you please look into this issue once you get a chance ?

**Comment by yinfangchen** [comment]
@seanmcc-msft any progress/explanation for this issue?
