### ISSUE TITLE
No info on running test from multiple locations in availabilitytelemetry.runlocation

### ISSUE THREAD

**Issue by MantriKarthik** [Azure/azure-sdk-for-net#29685]
[Enter feedback here]
 I want to availability test from 5 different locations but runlocation does not support that, so I want to know how to run the test from different locations. But there is no info on that in this document

Thank you in advance

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee9c6226-f05e-cb2f-b828-fbd83fc22343
* Version Independent ID: aee9ec31-a2a4-0b5f-9dc6-2e4d2fc15e41
* Content: [AvailabilityTelemetry.RunLocation Property (Microsoft.ApplicationInsights.DataContracts) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.datacontracts.availabilitytelemetry.runlocation?view=azure-dotnet)
* Content Source: [xml/Microsoft.ApplicationInsights.DataContracts/AvailabilityTelemetry.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights.DataContracts/AvailabilityTelemetry.xml)
* Service: **application-insights**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@MantriKarthik Thanks for your feedback! We will investigate and update as appropriate.

**Comment by SaurabhSharma-MSFT** [comment]
@MantriKarthik We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
