### ISSUE TITLE
[BUG] dotnet asking for MacOS KeyChain admin access every time SecretClient.GetSecretAsync() is called

### ISSUE THREAD

**Issue by alastairanderson** [Azure/azure-sdk-for-net#29699]
### Library name and version

Azure.Security.KeyVault.Secrets 4.3.0

### Describe the bug

On MacOS, whenever SecretClient.GetSecretAsync() is called dotnet is requesting administrative access to update the KeyChain.

### Expected behavior

No request to modify the KeyChain, given that it should be a GET request from the KeyVault, I'm not sure what modifications would be required that requires admin access.

### Actual behavior

On MacOS, whenever SecretClient.GetSecretAsync() is called dotnet is requesting administrative access to update the KeyChain. This is happening on every run of the application.

Even if dotnet required to update the KeyChain, I would perhaps expect it on the first time around to get the access required, write the value, then on the second run, perform a check of KeyChain to see if the value it is looking for is present, and do a read without the credentials required for modification.

### Reproduction Steps

1. Prereqs
i. Create a key vault with a test secret in Azure
ii. Create an AAD app registration that gives RBAC access to the new key vault
iii. Generate a new certificate, install it locally (in KeyChain) and upload the cert to the AAD app from the previous step.

2. Create a new .NET 6 console application with the .csproj as follows:

```<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RootNamespace>net6_keychain_access</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Core" Version="1.25.0" />
    <PackageReference Include="Azure.Identity" Version="1.6.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.3.0" />
  </ItemGroup>
</Project>
```

3. The Program.cs with the following code + inserting the appropriate values into the variables at the top:

```
using System.Security.Cryptography.X509Certificates;
using Azure.Core;
using Azure.Identity;
using Azure.Security.KeyVault.Secrets;

var certThumbprint = "";      // KeyChain access > find cert > double-click > SHA-1 value
var tenantId = "";            // Azure Portal > AAD > App Registrations > <app name> > Directory (tenant) ID
var clientId = "";            // Azure Portal > AAD > App Registrations > <app name> > Application (Client) ID
var uri = "";                 // Azure Portal > Key Vault > Overview > Vault URI
var keyVaultTestKeyName = ""; // Azure Portal > Key Vault > Secrets > <secret name>

SecretClientOptions options = new SecretClientOptions()
{
    Retry =
    {
        Delay= TimeSpan.FromSeconds(2),
        MaxDelay = TimeSpan.FromSeconds(16),
        MaxRetries = 5,
        Mode = RetryMode.Exponential
    }
};

X509Store userCertificateStore = new X509Store(StoreName.My, StoreLocation.CurrentUser);
X509Store compCertificateStore = new X509Store(StoreName.My, StoreLocation.LocalMachine);
userCertificateStore.Open(OpenFlags.ReadOnly);
compCertificateStore.Open(OpenFlags.ReadOnly);

X509Certificate2Collection certs = userCertificateStore.Certificates.Find(X509FindType.FindByThumbprint, certThumbprint, false);

// If cert not found in currentuser then try finding in LocalMachine store.
if (certs.Count < 1)
    // Search in local machine store - NOTE: This will access the KeyChain here.
    certs = compCertificateStore.Certificates.Find(X509FindType.FindByThumbprint, certThumbprint, false);

if (certs.Count < 1)
    throw new ArgumentException(string.Format("Certificate with thumbprint: {0} is not present in cert stores.",certThumbprint));

X509Certificate2 certificate = certs[0];
TokenCredential tokenCredential = new ClientCertificateCredential(tenantId, clientId, certificate);

SecretClient secretClient = new SecretClient(new Uri(uri), tokenCredential, options);
var response = await secretClient.GetSecretAsync(keyVaultTestKeyName);
var keyVaultTestKeyValue = response.Value.Value;

Console.WriteLine($"{keyVaultTestKeyValue}");

```

The above code should replicate the issue. I added in some [diagnostics logging](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging) to see what else is going on, and the following (summarised) telemetry is what I found when I run it:

```
[Informational] Azure-Core: Request [d7f712cd-d043-45f1-a736-ebf47491129a] GET https://<kv-name>.vault.azure.net/secrets/DocumentDbDatabase/?api-version=7.3
...
client assembly: Azure.Security.KeyVault.Secrets

[Warning] Azure-Core: Error response [d7f712cd-d043-45f1-a736-ebf47491129a] 401 Unauthorized (01.1s)
Cache-Control:no-cache

[Informational] Azure-Core: Error response [d7f712cd-d043-45f1-a736-ebf47491129a] content: {"error":{"code":"Unauthorized","message":"AKV10000: Request is missing a Bearer or PoP token."}}
[Informational] Azure-Identity: ClientCertificateCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: d7f712cd-d043-45f1-a736-ebf47491129a

[Informational] Azure-Identity: False ...
=== AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

[Informational] Azure-Identity: False...
=== Request Data ===
Authority Provided? - True
Scopes - https://vault.azure.net/.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - cb371423-0125-4cfa-95d2-48fc61c9d8d8
UserAssertion set: False
LongRunningOboCacheKey set: False

[Informational] Azure-Identity: False ...
=== Token Acquisition (ClientCredentialRequest) started:
	 Scopes: https://vault.azure.net/.default
	Authority Host: login.microsoftonline.com

[Informational] Azure-Identity: False ... [Region discovery] Not using a regional authority. 

[Informational] Azure-Identity: False ...
Fetching instance discovery from the network from host login.microsoftonline.com. 

[Informational] Azure-Core: Request [f50388f1-cb54-4ba0-a4d0-2cc49889aae2] GET https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=REDACTED

[Informational] Azure-Identity: False ... Authority validation enabled? True. 
[Informational] Azure-Identity: False ... Authority validation - is known env? True. 
```

At this point the dialog box pops up with `dotnet wants to use the "System" keychain`

Having looked at the diagnostic data I tried one last thing, to run `az login` in the VSCode terminal and authenticated as the user that has access to the key vault etc, in case that was needed to be done in order to cache the validation - but it still resulted in the same issue of the dialog box appearing requesting admin creds.

### Environment

MacOS (v12.4.0)
.NET (6.0.301, and also checked with 6.0.106)
Azure.Security.KeyVault.Secrets (4.3.0)
---- other ----
Azure.Core (1.25.0)
Azure.Identity (1.6.0)
Visual Studio Code (1.68.1)

**Comment by jsquire** [comment]
@schaabs:  I'd also appreciate your thoughts on this one.  Is it possible that it's the Identity credential that's the root of this behavior?

**Comment by heaths** [comment]
I believe this is an Identity issue (or at least behavior - may indeed be by design for the selected credential provider), not a Key Vault issue. It's happening during authentication. `SecretClient.GetSecretAsync()` is just a network call to get an opaque value.

From the logs, it seems the `ClientSecretCredential` is being used when the prompt occurs, which makes me think the client secret - potentially even the client ID - is stored in Mac's KeyChain. As a test, you could force the `AzureCliCredential` (which uses `az login` cached credentials) by just passing that as the `credential` argument or exclude the `ClientSecretCredential` using a `DefaultAzureCredentialOptions` passed to `DefaultAzureCredential`, if using that.

**Comment by schaabs** [comment]
Seems like the System.KeyChain is being invoked to access the private key of the certificate you're passing to the `ClientCertificateCredential`. The private key is necessary to sign the assertion that gets sent to the STS to get a token. I'm not sure if there is a way to forgo this KeyChain dialog. Using the `AzureCliCredential` to authenticate a user which has access to the vault is a possible work around. You could also possibly export the certificate from the KeyChain, but obviously this will make the certificate vulnerable to export off the machine.

**Comment by alastairanderson** [comment]
Thanks for spending the time to look into this @schaabs, @heaths, @jsquire

I went with the `AzureCliCredential` for the development path through the code, and have actually converted the staging/production path to use `ManagedIdentityCredential` - so I've removed the need for certificates altogether.

Using `AzureCliCredential` has gotten around the issue of the constant dialogs at startup, so thank you.
