### ISSUE TITLE
[BUG] Query 'Properties' returns 0 results

### ISSUE THREAD

**Issue by ArkeBcacy** [Azure/azure-sdk-for-net#29707]
### Library name and version

Azure.Monitor.Query 1.1.0

### Describe the bug

I'm attempting to use the LogsQueryClient to pull data from a Log Analytics workspace and having issues with the query.

Using the following queries I'm getting inconsistent results when the 'Properties' field is used in a Kusto query:

AppMetrics | where Name == 'PublicationView' and Properties has 'R2P9780986027956' => returns 0 results with LogsClientQuery.QueryWorkspaceAsync / Log query in Azure workspace returns 174 results with same query

AppMetrics | where Name == 'PublicationView' and Properties has 'R2P9780986027956' and TimeGenerated between (datetime('2022-07-01 00:00:00') .. datetime('2022-07-06 23:59:59')) => returns 0 results with LogsClientQuery.QueryWorkspaceAsync / Log query in Azure workspace returns 42 results with same query

AppMetrics | where Name == 'PublicationView' and TimeGenerated between (datetime('2022-07-01 00:00:00') .. datetime('2022-07-06 23:59:59')) => returns 716 results with LogsClientQuery.QueryWorkspaceAsync / Log query in Azure workspace returns 716 results with same query

### Expected behavior

Using the following code, the LogsQueryClient should return 42 results.

`var query = $"AppMetrics | where Name == '{metricType}' and Properties has '{metricNamespace}'";`
`var response = await _logsQueryClient.QueryWorkspaceAsync(_workspaceId, query, new QueryTimeRange(startDate, endDate));`

metricType = PublicationView
metricNamespace = 'R2P9780986027956'
startDate = '2022-07-01 00:00:00'
endDate = '2022-07-06 23:59:59'

### Actual behavior

0 results are returned. 
Removing " and Properties has '{metricNamespace}'" does return results but any usage of Properties in the query returns 0 results
![PropertiesInAzure](https://user-images.githubusercontent.com/98779849/177881665-989c4de8-00a6-4a8d-81e7-3f2ea9bd2562.png)
.

### Reproduction Steps

` var credential = new ClientSecretCredential(tenantId, clientId, clientSecret);
        _logsQueryClient = new LogsQueryClient(credential);

var startDate = DateTime.Parse("2022-07-01 00:00:00");
var endDate = DateTime.Parse("2022-07-06 23:59:59");
var metricType = "PublicationView";
var metricNamespace = "R2P9780986027956";

var query = $"AppMetrics | where Name == '{metricType}' and Properties has '{metricNamespace}'";
var response = await _logsQueryClient.QueryWorkspaceAsync(_workspaceId, query, new QueryTimeRange(startDate, endDate));
`

### Environment

Visual Studio 2022 (17.2.5)

.NET SDK (reflecting any global.json):
 Version:   6.0.301
 Commit:    43f9b18481

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.301\

Host (useful for support):
  Version: 6.0.6
  Commit:  7cca709db2

.NET SDKs installed:
  3.1.420 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.106 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by scottaddie** [comment]
I'm unable to reproduce this issue. @nisha-bhatia Can you please dig into this one?

**Comment by ArkeBcacy** [comment]
@scottaddie Here is the requested screenshot. IsError does say false and Status does return 200.
Let me know if I can provide you any additional information.

![GetMetricIssue](https://user-images.githubusercontent.com/98779849/178837982-b65a0e0b-704a-469c-8793-dcb3018fd1b7.PNG)

**Comment by scottaddie** [comment]
@ArkeBcacy Can you please enable logging and then try running the app again? We'll need to see the HTTP request body to determine what's being sent to the service itself. You can enable console logging with [these instructions](https://docs.microsoft.com/dotnet/api/overview/azure/Monitor.Query-readme#set-up-console-logging).

/cc: @srnagar

**Comment by ArkeBcacy** [comment]
@scottaddie Here is the output from console logger for the function call to get the data:

`[2022-07-18T22:04:54.848Z] Executing 'GetMetrics' (Reason='This function was programmatically called via the host APIs.', Id=985bebd3-1ae2-48b5-a48a-e9e664919faa)
[Informational] Azure-Identity: ClientSecretCredential.GetToken invoked. Scopes: [ https://api.loganalytics.io//.default ] ParentRequestId: 03375a35-f408-4089-a172-d9ab1f24e348
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:54.96 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] MSAL MSAL.NetCore with assembly version '4.39.0.0'. CorrelationId(1f042ac8-fa7f-4517-9854-06b92c84ae19)
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:54.97 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:54.98 - 1f042ac8-fa7f-4517-9854-06b92c84ae19]
=== Request Data ===
Authority Provided? - True
Scopes - https://api.loganalytics.io//.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 1f042ac8-fa7f-4517-9854-06b92c84ae19
UserAssertion set: False
LongRunningOboCacheKey set: False

[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:54.99 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] === Token Acquisition (ClientCredentialRequest) started:
         Scopes: https://api.loganalytics.io//.default
        Authority Host: login.microsoftonline.com
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.01 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] [Region discovery] Not using a regional authority.
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.02 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] Fetching instance discovery from the network from host login.microsoftonline.com.
[Informational] Azure-Core: Request [5a8026bb-91d9-45a5-bac1-59726e0357b5] GET https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=REDACTED
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:5a8026bb-91d9-45a5-bac1-59726e0357b5
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.6.0,(.NET 6.0.6; Microsoft Windows 10.0.19044)
client assembly: Azure.Identity
[Informational] Azure-Core: Request [eed09e3c-97aa-471d-b6eb-f31844406f22] GET https://{REMOVED}.queue.core.windows.net/events-aggregation/messages?numofmessages=10&visibilitytimeout=600
x-ms-version:2018-11-09
Accept:application/xml
x-ms-client-request-id:eed09e3c-97aa-471d-b6eb-f31844406f22
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Queues/12.8.0,(.NET 6.0.6; Microsoft Windows 10.0.19044)
x-ms-date:Mon, 18 Jul 2022 22:04:55 GMT
Authorization:REDACTED
client assembly: Azure.Storage.Queues
[Informational] Azure-Core: Response [5a8026bb-91d9-45a5-bac1-59726e0357b5] 200 OK (00.3s)
Cache-Control:max-age=86400, private
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Access-Control-Allow-Origin:REDACTED
Access-Control-Allow-Methods:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:0e0933f8-64a5-4a8e-aa26-ea7343ab9300
x-ms-ests-server:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:Mon, 18 Jul 2022 22:05:34 GMT
Content-Type:application/json; charset=utf-8
Content-Length:980

[Informational] Azure-Core: Response [eed09e3c-97aa-471d-b6eb-f31844406f22] 200 OK (00.0s)
Cache-Control:no-cache
Transfer-Encoding:chunked
Server:Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:9d4df49f-a003-003a-55f2-9a4f85000000
x-ms-version:2018-11-09
Date:Mon, 18 Jul 2022 22:05:35 GMT
Content-Type:application/xml

[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.44 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] Authority validation enabled? True.
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.44 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] Authority validation - is known env? True.
[Informational] Azure-Core: Request [1a842534-e3ab-47d5-b795-93951ccb34f5] POST https://login.microsoftonline.com/80dddcec-f312-4134-9db4-364b5c2421e0/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:1a842534-e3ab-47d5-b795-93951ccb34f5
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.6.0,(.NET 6.0.6; Microsoft Windows 10.0.19044)
Content-Type:application/x-www-form-urlencoded
client assembly: Azure.Identity
[Informational] Azure-Core: Request [ebd4b142-08c7-410c-8eee-37374f777dfe] GET https://{REMOVED}.queue.core.windows.net/metrics-aggregation/messages?numofmessages=10&visibilitytimeout=600
x-ms-version:2018-11-09
Accept:application/xml
x-ms-client-request-id:ebd4b142-08c7-410c-8eee-37374f777dfe
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Queues/12.8.0,(.NET 6.0.6; Microsoft Windows 10.0.19044)
x-ms-date:Mon, 18 Jul 2022 22:04:55 GMT
Authorization:REDACTED
client assembly: Azure.Storage.Queues
[Informational] Azure-Core: Response [ebd4b142-08c7-410c-8eee-37374f777dfe] 200 OK (00.0s)
Cache-Control:no-cache
Transfer-Encoding:chunked
Server:Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:9d4df547-a003-003a-2ef2-9a4f85000000
x-ms-version:2018-11-09
Date:Mon, 18 Jul 2022 22:05:35 GMT
Content-Type:application/xml

[Informational] Azure-Core: Response [1a842534-e3ab-47d5-b795-93951ccb34f5] 200 OK (00.2s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:2006c838-a19a-4efc-aa8a-7a4afba24700
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:Mon, 18 Jul 2022 22:05:34 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:1320

[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.65 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] ScopeSet was missing from the token response, so using developer provided scopes in the result.
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.65 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] Checking client info returned from the server..
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.65 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] Saving token response to cache..
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.67 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] ID Token not present in response.
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.67 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] Cannot determine home account id - or id token or no client info and no subject
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.67 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] Saving AT in cache and removing overlapping ATs...
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.68 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] Looking for scopes for the authority in the cache which intersect with https://api.loganalytics.io//.default
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.68 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] Intersecting scope entries count - 0
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.69 - 1f042ac8-fa7f-4517-9854-06b92c84ae19] Fetched access token from host login.microsoftonline.com.
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.69 - 1f042ac8-fa7f-4517-9854-06b92c84ae19]
        === Token Acquisition finished successfully:
[Informational] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.6 Microsoft Windows 10.0.19044 [07/18 22:04:55.70 - 1f042ac8-fa7f-4517-9854-06b92c84ae19]  AT expiration time: 7/18/2022 11:04:54 PM +00:00, scopes https://api.loganalytics.io//.default source IdentityProvider from login.microsoftonline.com appHashCode 27741726
[Informational] Azure-Identity: ClientSecretCredential.GetToken succeeded. Scopes: [ https://api.loganalytics.io//.default ] ParentRequestId: 03375a35-f408-4089-a172-d9ab1f24e348 ExpiresOn: 2022-07-18T23:04:54.6784061+00:00
[Informational] Azure-Core: Request [03375a35-f408-4089-a172-d9ab1f24e348] POST https://api.loganalytics.io/v1/workspaces/2f48cb40-8957-4146-8e57-d6ae731c5eab/query
Accept:application/json
x-ms-client-request-id:03375a35-f408-4089-a172-d9ab1f24e348
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Monitor.Query/1.1.0,(.NET 6.0.6; Microsoft Windows 10.0.19044)
Authorization:REDACTED
Content-Type:application/json
client assembly: Azure.Monitor.Query
[Informational] Azure-Core: Response [03375a35-f408-4089-a172-d9ab1f24e348] 200 OK (00.2s)
Date:Mon, 18 Jul 2022 22:05:35 GMT
Connection:keep-alive
Vary:REDACTED
Strict-Transport-Security:REDACTED
Via:REDACTED
X-Content-Type-Options:REDACTED
Access-Control-Allow-Origin:REDACTED
Access-Control-Expose-Headers:REDACTED
Age:REDACTED
Content-Type:application/json; charset=utf-8
Content-Length:1315

[2022-07-18T22:04:55.963Z] Executed 'GetMetrics' (Succeeded, Id=985bebd3-1ae2-48b5-a48a-e9e664919faa, Duration=1170ms)`

**Comment by scottaddie** [comment]
@ArkeBcacy A couple more things:

1. I noticed in the log you provided that you're calling `GetMetrics`. We'll need to see the log for `QueryWorkspaceAsync` instead.
1. To include the request and response bodies in the log, you'll need to pass `EventLevel.Verbose` to `CreateConsoleLogger`. You'll also need to set the `Diagnostics.IsLoggingContentEnabled` property to `true`. For example:

    ```csharp
    using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Verbose);

    var client = new LogsQueryClient(
        new DefaultAzureCredential(),
        new LogsQueryClientOptions
        {
            Diagnostics = { IsLoggingContentEnabled = true }
        });
    ````

**Comment by scottaddie** [comment]
@ArkeBcacy Nothing that I'm aware of has changed in the service or client library. I'll close this issue for now, but please let me know if you see this issue again.
