### ISSUE TITLE
[Search] UpdateIndex failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29716]
Search nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : The request is invalid. Details: index : The property 'normalizer' does not exist on type 'Microsoft.Azure.Search.V2020_06_30.SchemaField'. Make sure to only use property names that are defined by the type.
> 
> Status: 400 (Bad Request)
> 
> Content:
> {"error":{"code":"","message":"The request is invalid. Details: index : The property 'normalizer' does not exist on type 'Microsoft.Azure.Search.V2020_06_30.SchemaField'. Make sure to only use property names that are defined by the type.\r\n"}}
> 
> Headers:
> Cache-Control: no-cache
> Pragma: no-cache
> client-request-id: e21629c5-1ab1-4f88-b425-cb36feab6845
> x-ms-client-request-id: e21629c5-1ab1-4f88-b425-cb36feab6845
> request-id: e21629c5-1ab1-4f88-b425-cb36feab6845
> elapsed-time: 4
> OData-Version: 4.0
> Preference-Applied: REDACTED
> Strict-Transport-Security: REDACTED
> Date: Thu, 07 Jul 2022 16:43:15 GMT
> Content-Type: application/json; odata.metadata=minimal
> Content-Language: REDACTED
> Expires: -1
> Content-Length: 244
> 
> 
> Stack trace
>    at Azure.Search.Documents.IndexesRestClient.Create(SearchIndex index, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/src/Generated/IndexesRestClient.cs:line 113
>    at Azure.Search.Documents.Indexes.SearchIndexClient.CreateIndex(SearchIndex index, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/src/Indexes/SearchIndexClient.cs:line 393
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 166
>    at Azure.Search.Documents.Tests.SearchIndexClientTests.UpdateIndex() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/SearchIndexClientTests.cs:line 188
>    at Azure.Search.Documents.Tests.SearchIndexClientTests.UpdateIndex() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/SearchIndexClientTests.cs:line 229
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1691382&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
@v-xuto:  Please leave unassigned for triage; this is not the Mohit that you intended.  😄

**Comment by ShivangiReja** [comment]
This issue is fixed here - https://github.com/Azure/azure-sdk-for-net/pull/29702.

Keeping this issue to track https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1694718&view=results nightly run failure
