### ISSUE TITLE
[Synapse] AddAndRemoveRoleAssignmentSync failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29717]
Synapse nightly test runs are failing with:

> Error message
> System.InvalidOperationException : Sequence contains no matching element
> 
> 
> Stack trace
>    at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Azure.Analytics.Synapse.AccessControl.Samples.Sample1_HelloWorld.AddAndRemoveRoleAssignmentSync() in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.AccessControl\tests\samples\Sample1_HelloWorld.cs:line 40

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1692176&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
@v-xuto: Please leave unassigned for triage.

**Comment by v-xuto** [comment]
> @v-xuto: Please leave unassigned for triage.

Got it. I will leave unassigned for triage.
