### ISSUE TITLE
[Tables] InsertOverPartitionLimit failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29718]
Tables nightly test runs are failing with:

> Error message
> Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: InsertOverPartitionLimitProgram.Call
> ----> Azure.Data.Tables.TableTransactionFailedException : Message: {"Errors":["Request rate is large. More Request Units may be needed, so no changes were made. Please retry this request later. Learn more: http://aka.ms/cosmosdb-error-429"]}
> ActivityId: a748956a-71e4-4e49-962c-a89848104bd3, Request URI: /apps/8f6f2c5f-73de-4946-b724-a8b868e9aa89/services/5e267f73-ac8f-4054-9cb4-1b73671687f1/partitions/1e1287e9-38cd-4bf2-bec4-06471c64b1ad/replicas/133016559039519406p/, RequestStats:
> RequestStartTime: 2022-07-07T08:27:34.2754123Z, RequestEndTime: 2022-07-07T08:27:34.2768236Z,  Number of regions attempted:1
> {"systemHistory":[{"dateUtc":"2022-07-07T08:26:40.7595316Z","cpu":22.800,"memory":350484516.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0607,"availableThreads":32762,"minThreads":20,"maxThreads":32767},"numberOfOpenTcpConnection":688},{"dateUtc":"2022-07-07T08:26:50.7709389Z","cpu":20.250,"memory":350569544.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.057,"availableThreads":32766,"minThreads":20,"maxThreads":32767},"numberOfOpenTcpConnection":701},{"dateUtc":"2022-07-07T08:27:00.7998148Z","cpu":20.506,"memory":350579692.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0618,"availableThreads":32763,"minThreads":20,"maxThreads":32767},"numberOfOpenTcpConnection":709},{"dateUtc":"2022-07-07T08:27:10.8147059Z","cpu":21.778,"memory":350583864.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0294,"availableThreads":32760,"minThreads":20,"maxThreads":32767},"numberOfOpenTcpConnection":719},{"dateUtc":"2022-07-07T08:27:20.8284843Z","cpu":26.291,"memory":350630428.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.2025,"availableThreads":32759,"minThreads":20,"maxThreads":32767},"numberOfOpenTcpConnection":724},{"dateUtc":"2022-07-07T08:27:30.8384299Z","cpu":28.378,"memory":350607964.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0071,"availableThreads":32764,"minThreads":20,"maxThreads":32767},"numberOfOpenTcpConnection":729}]}
> RequestStart: 2022-07-07T08:27:34.2756471Z; ResponseTime: 2022-07-07T08:27:34.2768236Z; StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westus1-fd72.documents.azure.com:14087/apps/8f6f2c5f-73de-4946-b724-a8b868e9aa89/services/5e267f73-ac8f-4054-9cb4-1b73671687f1/partitions/1e1287e9-38cd-4bf2-bec4-06471c64b1ad/replicas/133016559039519406p/, LSN: 139, GlobalCommittedLsn: 139, PartitionKeyRangeId: , IsValid: True, StatusCode: 429, SubStatusCode: 3200, RequestCharge: 0.38, ItemLSN: -1, SessionToken: , UsingLocalLSN: False, TransportException: null, BELatencyMs: , ActivityId: a748956a-71e4-4e49-962c-a89848104bd3, RetryAfterInMs: 24, TransportRequestTimeline: {"requestTimeline":[{"event": "Created", "startTimeUtc": "2022-07-07T08:27:34.2756489Z", "durationInMs": 0.0028},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2022-07-07T08:27:34.2756517Z", "durationInMs": 0.1295},{"event": "Pipelined", "startTimeUtc": "2022-07-07T08:27:34.2757812Z", "durationInMs": 0.1065},{"event": "Transit Time", "startTimeUtc": "2022-07-07T08:27:34.2758877Z", "durationInMs": 0.4504},{"event": "Received", "startTimeUtc": "2022-07-07T08:27:34.2763381Z", "durationInMs": 0.1628},{"event": "Completed", "startTimeUtc": "2022-07-07T08:27:34.2765009Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":1,"openConnections":1},"connectionStats":{"waitforConnectionInit":"False","callsPendingReceive":0,"lastSendAttempt":"2022-07-07T08:27:34.2679640Z","lastSend":"2022-07-07T08:27:34.2680070Z","lastReceive":"2022-07-07T08:27:34.2730130Z"},"requestSizeInBytes":604,"requestBodySizeInBytes":154,"responseMetadataSizeInBytes":127,"responseBodySizeInBytes":174};
> ResourceType: StoredProcedure, OperationType: ExecuteJavaScript
> , SDK: documentdb-dotne
> 
> 
> Stack trace
>    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 368
>    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 158
>    at Microsoft.Azure.WebJobs.Host.Executors.ExceptionDispatchInfoDelayedException.Throw() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ExceptionDispatchInfoDelayedException.cs:line 29
>    at Microsoft.Azure.WebJobs.JobHost.CallAsyncCore(IFunctionDefinition function, Object functionKey, IDictionary`2 arguments, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 266
>    at Microsoft.Azure.WebJobs.JobHost.<CallAsync>g__CallAsyncAwaited|29_0(MethodInfo method, IDictionary`2 arguments, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 207
>    at Microsoft.Azure.WebJobs.Extensions.Tables.Tests.TablesLiveTestBase.CallAsync(Type funcType, String methodName, Object arguments, Action`1 configure) in D:\a\_work\1\s\sdk\tables\Microsoft.Azure.WebJobs.Extensions.Tables\tests\TablesLiveTestBase.cs:line 116
>    at Microsoft.Azure.WebJobs.Extensions.Tables.Tests.TablesLiveTestBase.CallAsync[T](String methodName, Object arguments, Action`1 configure) in D:\a\_work\1\s\sdk\tables\Microsoft.Azure.WebJobs.Extensions.Tables\tests\TablesLiveTestBase.cs:line 97
>    at Microsoft.Azure.WebJobs.Extensions.Tables.Tests.EntityBindingLiveTests.InsertOverPartitionLimit() in D:\a\_work\1\s\sdk\tables\Microsoft.Azure.WebJobs.Extensions.Tables\tests\EntityBindingLiveTests.cs:line 1357
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> --TableTransactionFailedException
>    at Azure.Data.Tables.TableRestClient.SendBatchRequestAsync(HttpMessage message, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\tables\Azure.Data.Tables\src\TableRestClient.cs:line 88
>    at Azure.Data.Tables.TableClient.SubmitTransactionInternalAsync(IEnumerable`1 transactionalBatch, Guid batchId, Guid changesetId, Boolean async, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\tables\Azure.Data.Tables\src\TableClient.cs:line 1498
>    at Azure.Data.Tables.TableClient.SubmitTransactionAsync(IEnumerable`1 transactionActions, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\tables\Azure.Data.Tables\src\TableClient.cs:line 1400
>    at Microsoft.Azure.WebJobs.Extensions.Tables.TableEntityWriter.FlushPartitionAsync(Dictionary`2 partition, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\tables\Microsoft.Azure.WebJobs.Extensions.Tables\src\TableEntityWriter.cs:line 122
>    at Microsoft.Azure.WebJobs.Extensions.Tables.TableEntityWriter.FlushAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\tables\Microsoft.Azure.WebJobs.Extensions.Tables\src\TableEntityWriter

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1690955&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
It appears that the Function instance is triggering throttles consistently for this test over the last few days; unsure if that is the intent of the test and a response changed or if we need to consider some kind of back-off.

**Comment by christothes** [comment]
We already have a backoff, but apparently, it's not enough :/

https://github.com/Azure/azure-sdk-for-net/blob/c8eca54dd656fbf3d617ad4133eef11801c4ddd9/sdk/tables/Microsoft.Azure.WebJobs.Extensions.Tables/tests/EntityBindingLiveTests.cs#L1368-L1382
