### ISSUE TITLE
[Core] Ubuntu2004_NETCore31_PackageRef_Debug failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29714]
Core nightly test runs are failing with:

> [error]The job running on agent azsdk-pool-mms-ubuntu-2004-general 83 ran longer than the maximum time of 60 minutes. For more information, see https://go.microsoft.com/fwlink/?linkid=2077134

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1691218&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
@v-xuto:  Josh Free is not the correct person to assign here.   Please leave unassigned for triage.

**Comment by jsquire** [comment]
Timeout issue in the pipeline is known and mitigation is in progress.
