### ISSUE TITLE
[BUG] BlobBatchClient.DeleteBlobs fails with 404 when a blob versionid is provided

### ISSUE THREAD

**Issue by kostasvl** [Azure/azure-sdk-for-net#29737]
### Library name and version

Azure.Storage.Blobs.Batch 12.9.0, Azure.Storage.Blobs 12.12.0

### Describe the bug

My ultimate goal is to code a loop that will delete the previous versions of about one million deleted blobs (we have versioning and soft-delete enabled). I'm hoping this will improve the directory browsing experience in AZ Storage Explorer.

First, I feel I shouldn't have to do this. Why is AZ SE slow to list just the non-deleted blobs, even when it defaults to "Active blobs"? Anyway, this is probably the wrong place for that.

Deleting the blobs' versions one by by one (via blobContainerClient.GetBlobClient(blob.Name).WithVersion(blob.VersionId).DeleteAsync) is very slow, so I tried the batching API. This is how I'm doing it:

```
BlobServiceClient blobServiceClient = new(
        new Uri("https://XXXXXXXXX.blob.core.windows.net"),
        new BearerTokenCredential(authenticationResult));
				
BlobContainerClient blobContainerClient = blobServiceClient.GetBlobContainerClient(containerName);

var blobs = blobContainerClient.GetBlobsAsync(BlobTraits.None, BlobStates.Version, prefixOfBlobsToBeDeleted);

List<BlobItem> blobsToBeDeleted = new();

await foreach (BlobItem blob in blobs)
{
	blobsToBeDeleted.Add(blob);
}

BlobBatchClient blobBatchClient = blobServiceClient.GetBlobBatchClient();

foreach (BlobItem[] chunkOfBlobsToDelete in blobsToBeDeleted.Chunk(256))
{
	Response[] responses = await blobBatchClient.DeleteBlobsAsync(chunkOfBlobsToDelete.Select(
		blob => blobContainerClient.GetBlobClient(blob.Name).WithVersion(blob.VersionId).Uri));
}
```

This returns an aggregate exception, containing 256 404s:

The specified blob does not exist.
RequestId:...
Time:...
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound

It obviously works when I try the above with base (aka root, aka non-deleted) blobs (ie without calling WithVersion).

### Expected behavior

It should delete the specific blob versions I'm asking it to.

### Actual behavior

404 (The specified blob does not exist.)

### Reproduction Steps

See above code example. It should mostly compile.

### Environment

TargetFramework: net6.0-windows10.0.17763.0
Visual Studio 2022

**Comment by SaurabhSharma-MSFT** [comment]
@kostasvl We are looking into it and get back to you for any additional information.

**Comment by seanmcc-msft** [comment]
Related - https://github.com/Azure/azure-sdk-for-net/issues/40849
Resolved by https://github.com/Azure/azure-sdk-for-net/pull/41084, this feature will ship with our next release in early March.
