### ISSUE TITLE
[BUG] Use DefaultAzureCredential with serviceconnection in ado pipeline receive 401

### ISSUE THREAD

**Issue by RetYn** [Azure/azure-sdk-for-net#29769]
### Library name and version

Azure.Identity 1.6.0

### Describe the bug

I use DefaultAzureCredential to init CosmosClient  
new CosmosClient(endpoint, new DefaultAzureCredential(), options)
in a c# console app, and run the app in ado pipeline with a service connection.
Sometimes it will get 401 error with the following error message:
Provided AAD token was issued by the authority [72f988bf-86f1-41af-91ab-2d7cd011db47] which is not trusted by this database account.
The pipeline can be retried successfully after serval changes.

From the error message， it seems defaultAzurecredential does not use the service connection defined in ado pipeline to get AAD which is in another AAD
tenant (which is should not be 72f988bf-86f1-41af-91ab-2d7cd011db47)
### Expected behavior

CosmosClient should have authority to perform action.

### Actual behavior

Provided AAD token was issued by the authority [72f988bf-86f1-41af-91ab-2d7cd011db47] which is not trusted by this database account.

### Reproduction Steps

In descirbe.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by egorshulga** [comment]
I believe this issue also affects Azure Pipelines (the issue is discussed here: actions/virtual-environments#5908)

**Comment by christothes** [comment]
Hi @RetYn - `DefaultAzureCredential` is not aware of the service connection, so you'd need to either pass it to the credential in code, or have the pipeline stash the service connection secrets into the environment such that the credential can find them. See the docs here for details:

https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#environment-variables
