### ISSUE TITLE
Enable national cloud support for Azure Search SDK 

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#29779]
Search SDK currently hard codes the audience to the public cloud. We need to enable the support for multiple audience to target non public clouds by the SDK.

**Comment by ShivangiReja** [comment]
Duplicate: https://github.com/Azure/azure-sdk-for-net/issues/30306

This feature has been implemented here: https://github.com/Azure/azure-sdk-for-net/pull/30316
