### ISSUE TITLE
Regenerate Key for documentDb account

### ISSUE THREAD

**Issue by v-xiaze** [Azure/azure-sdk-for-net#2977]
Hi,

I found that there are functions for Redis and storageaccount to RegenerateKey(primary or secondary) since they both have .net management library, but I didn't find any function in Microsoft.Azure.Management.Resources to do the same thing for documentdb account. Can you please point me to the correct function in this library? I need to used .net api not rest api.

**Comment by sphibbs** [comment]
DocDB is not in this repository. Closing
