### ISSUE TITLE
[FEATURE REQ] Add Integrated Windows Authentication support within TokenCredential interface

### ISSUE THREAD

**Issue by greatvovan** [Azure/azure-sdk-for-net#29784]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

I am running into this issue with `Azure.Storage.Blobs` but I believe this will be the case for other libraries accepting [`TokenCredential`](https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokencredential?view=azure-dotnet) as well. I tried to make it work with Integrated Windows Authentication but failed to find the appropriate descendant of `TokenCredential` to supply into the [constructor](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.-ctor?view=azure-dotnet#azure-storage-blobs-blobcontainerclient-ctor(system-uri-azure-core-tokencredential-azure-storage-blobs-blobclientoptions)) of `BlobContainerClient`. After asking a question on StackOverflow I was pointed to the [migration guide](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration) where IWA is marked is not supported.

I am not sure why Integrated Windows Authentication is not supported. This must be pretty popular demand in the Enterprise world.

I ended up writing my own implementation of `TokenCredential` interface:

```
internal class IwaCredential : TokenCredential
{
    private readonly IPublicClientApplication _application;
    private readonly string[] _scopes;

    public IwaCredential(IPublicClientApplication app, string[] scopes)
    {
        _application = app;
        _scopes = scopes;
    }

    private async Task<AuthenticationResult> AuthenticateAsync()
    {
        AuthenticationResult? result = null;
        var accounts = await _application.GetAccountsAsync();

        if (accounts.Any())
        {
            try
            {
                result = await _application.AcquireTokenSilent(_scopes, accounts.FirstOrDefault()).ExecuteAsync();
            }
            catch (MsalUiRequiredException)
            {
            }
        }

        if (result == null)
        {
            result = await _application.AcquireTokenByIntegratedWindowsAuth(_scopes).ExecuteAsync();
        }

        return result;
    }

    private async Task<AccessToken> GetAccessTokenAsync()
    {
        var authResult = await AuthenticateAsync();
        return new AccessToken(authResult.AccessToken, authResult.ExpiresOn);
    }

    public override AccessToken GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
    {
        return GetAccessTokenAsync().GetAwaiter().GetResult();
    }

    public override ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
    {
        return new ValueTask<AccessToken>(GetAccessTokenAsync());
    }
}
```

Now we are able to supply it into `BlobContainerClient` (or other):

```
var appOptions = new PublicClientApplicationOptions
{
    ClientId = "...",
    TenantId = "...",
};
var app = PublicClientApplicationBuilder.CreateWithApplicationOptions(appOptions).Build();
var cred = new IwaCredential(app, new string[] { "https://storage.azure.com/user_impersonation" });
var client = new BlobContainerClient(new Uri("https://foobar.blob.core.windows.net/upload"), cred);
// obtain your file...
var res = await client.UploadBlobAsync("prefix/my.file", file);
Console.WriteLine(res);
}
```

**I ask you to please include an equivalent of `IwaCredential` above into the standard of Azure.Identity.**

See also [my question on StackOverflow](https://stackoverflow.com/questions/72917738/how-to-authenticate-in-azure-blob-storage-through-integrated-windows-authenticat) (and comments).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @greatvovan - The reason we don't have a credential that supports IWA is that, generally, the other implementations of `TokenCredential` are cross-platform.

**Comment by greatvovan** [comment]
I understand @christothes. Any plans for including this functionality into other (Windows-related) packages? I think there should be an official implementation from Microsoft for this part as it might be not obvious how to proceed from IWA to token auth.

**Comment by christothes** [comment]
If you are wanting to do interactive windows based login support, this [Azure.Identity.BrokeredAuthentication](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity.BrokeredAuthentication) may be closer to what you are looking for.

**Comment by snakefoot** [comment]
See also #12219 where you promise to close the gap to AppAuthentication. Funny that Microsoft abandons their own enterprise platform.
