### ISSUE TITLE
The request content is not valid and could not be deserialized: 'Could not find member 'variables' on object of type 'FlowTemplate'

### ISSUE THREAD

**Issue by danielok1993** [Azure/azure-sdk-for-net#2979]
Hello,

I am getting an error when trying to update the Logic App. The initial deployment which creates the logic app with the connector works fine. However, when I change one of the parameters and call Deployments.CreateOrUpdate I am getting Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'Failed'. Then, in the deployment within Azure Portal I can see the connector gets updated correctly, but when it tries to update the logic app it says:

{
  "error": {
    "code": "InvalidRequestContent",
    "message": "The request content is not valid and could not be deserialized: 'Could not find member 'variables' on object of type 'FlowTemplate'. Path 'properties.definition.variables', line 1, position 1677.'."
  }
}

I have added the variables in that path, but it still complains about the member missing.

I have also tried using Workflows.Update, but I still get the same exception.

**Comment by markcowl** [comment]
@pankajsn can you take a look?

**Comment by pankajsn** [comment]
Can you please assign this to @Tony Tang<mailto:tonytang@microsoft.com> ?

**Comment by pankajsn** [comment]
@Mark Cowlishaw<mailto:Mark.Cowlishaw@microsoft.com> , Can you please assign this to @Tony Tang<mailto:tonytang@microsoft.com> ?

**Comment by danielok1993** [comment]
Hello,

I believe you can close the ticket, it seems that the smallest variation from the correct template will break the deployment. e.g. if you add variables object in the wrong path. I believe this should be ignored or the error should be more meaningful pointing to the mistake. 

Thank you,

Daniel

**Comment by adrianhall** [comment]
Closing per request (2 years ago now) from the OP.
