### ISSUE TITLE
Get latest timestamp file from container/blob

### ISSUE THREAD

**Issue by ilantom** [Azure/azure-sdk-for-net#29796]
### Library name and version

Azure Storage Blob 12.2.0

### Query/Question

How do I get the latest modified file from a Blob?

I have a  container in which there is a blob named cache:

[![enter image description here][1]][1]

I have the following code where I’m trying to get the latest modified file from the container:

```
using Azure.Identity;
using Azure.Storage.Blobs;

var storageAccountName = "storageAccountName";
var containerName = "containerName"];
var containerUrl = $"https://{storageAccountName}.blob.core.windows.net/{containerName}";
var containerClient = new BlobContainerClient(new Uri(containerUrl), new DefaultAzureCredential());

public async Task GetBlobItems()
{         
            foreach (var blobItem in containerClient.GetBlobs())
            {
                var blobClient = _containerClient.GetBlobClient(blobItem.Name);
                var blobExists = await blobClient.ExistsAsync();
                if (blobExists)
                {
                    var properties = await blobClient.GetPropertiesAsync();
                    var lastModified = properties.Value.LastModified;
                }
            }
}
```

How do I get the latest modified file from 'cache' blob? Please note that I need the latest modified file from 'cache' blob.

  [1]: https://i.stack.imgur.com/rKiD5.png

**Comment by SaurabhSharma-MSFT** [comment]
@ilantom We are looking into it and get back to you for any additional information.

**Comment by ilantom** [comment]
@SaurabhSharma-MSFT Thank you! How do I download the content of that latest modified blob? Please let me know.

**Comment by SaurabhSharma-MSFT** [comment]
@ilantom Use `.FirstOrDefault()` method instead. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@ilantom We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
