### ISSUE TITLE
[FEATURE REQ] Setting DisplayName for an activity does not work in Monitor.OpenTelemetry.Exporter 

### ISSUE THREAD

**Issue by ardacetinkaya** [Azure/azure-sdk-for-net#29807]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 

### Query/Question

I am using `Azure.Monitor.OpenTelemetry.Exporter` to export trace data to Application Insights. Everything works fine, at least as expected for my main requirements. 

I am doing some enrichment and set display name for my operations. So far, also all output is as expected in `Jaeger` when I use different exporter. I need to have same output also in `Application Insights`.

But when I set the .DisplayName of an activity, the output in `Application Insights` is not as expected.

When I also checked the code; https://github.com/Azure/azure-sdk-for-net/blob/92a2d1de842ddfbffb9abbcaf6e0e7c1c1ce2ee4/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/TraceHelper.cs#L150

I realized that even if I set the `.DisplayName` there is some condition to check a tag value("HTTP" method)

```csharp
var httpMethod = AzMonList.GetTagValue(ref MappedTags, SemanticConventions.AttributeHttpMethod)?.ToString();
if (!string.IsNullOrWhiteSpace(httpMethod))
{
    var httpRoute = AzMonList.GetTagValue(ref MappedTags, SemanticConventions.AttributeHttpRoute)?.ToString();
    // ASP.NET instrumentation assigns route as {controller}/{action}/{id} which would result in the same name for different operations.
    // To work around that we will use path from httpUrl.
    if (!string.IsNullOrWhiteSpace(httpRoute) && !httpRoute.Contains("{controller}"))
    {
        return $"{httpMethod} {httpRoute}";
    }
    var httpUrl = AzMonList.GetTagValue(ref MappedTags, SemanticConventions.AttributeHttpUrl)?.ToString();
    if (!string.IsNullOrWhiteSpace(httpUrl) && Uri.TryCreate(httpUrl.ToString(), UriKind.RelativeOrAbsolute, out var uri) && uri.IsAbsoluteUri)
    {
        return $"{httpMethod} {uri.AbsolutePath}";
    }
}

return activity.DisplayName;
```

Is there a specific reason for this? I am handling this issue by removing built-in HTTP method tag in my enrichment. But I am not sure if that tag is required for internals or not.

**Comment by SaurabhSharma-MSFT** [comment]
@ardacetinkaya I am redirecting this to services team to look into.

**Comment by BenjaBobs** [comment]
Any news on this?

**Comment by TimothyMothra** [comment]
This is on our backlog. No ETA yet.

**Comment by BenjaBobs** [comment]
Can you confirm that this is indeed the cause of the #23266 issue? The appearance of `<Empty>` instead of the actual operation name is causing quite a bit of extra work in terms of actually getting an overview of what's going on. It's basically a bit of a blocker for my team.
