### ISSUE TITLE
[BUG] Cognitive Language Conversations rejecting input

### ISSUE THREAD

**Issue by chrisbardon** [Azure/azure-sdk-for-net#29812]
### Library name and version

Azure.AI.Language.Conversations 1.1.0-beta.1

### Describe the bug

I'm trying to test the new Conversation Summarization feature documented [here](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/summarization/quickstart?tabs=conversation-summarization&pivots=programming-language-csharp), but even calling it with the sample input is coming back with a 400 (Unsupported feature).  I've created a language resource in EastUS in my Azure tenant, and it's set to Standard pricing-is there something else that I might be missing here?  I've got the 1.1.0-beta1 nuget package installed.

### Expected behavior

Summary should return

### Actual behavior

Call returns a 400 (invalid operation)

### Reproduction Steps

Repros with sample code here: https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/summarization/quickstart?tabs=conversation-summarization&pivots=programming-language-csharp

### Environment

.net 6, win 11 21h2, vs 2022 Enterprise 17.2.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Not all regions support conversational summarization and PII. I'll get someone from the service team that can better help you.

**Comment by cahann** [comment]
Conversation summarization is gated you need to fill in onboarding form to get whitelisted

**Comment by wangyuantao** [comment]
From your link, I found the link to the form: https://aka.ms/applyforconversationsummarization/
<img width="578" alt="image" src="https://user-images.githubusercontent.com/98181/178852437-6e127174-8408-466d-b0f9-813b9fa410ca.png">

**Comment by wangyuantao** [comment]
@chrisbardon I tested from the same region (East US) and see the form URL is contained in the error message as well.

![image](https://user-images.githubusercontent.com/98181/178876399-ec6824cc-9594-498d-93fc-0f096db7d0bd.png)
PS D:\TestLanguageServiceSDK> dotnet run
Unhandled exception. Azure.RequestFailedException: Invalid request has been sent.
Status: 400 (Unsupported Feature)
ErrorCode: InvalidRequest

Content:
{"error":{"code":"InvalidRequest","message":"Invalid request has been sent.", "innererror":{"code" : "UnsupportedFeature", "message":"The conversation summarization is a gated public preview. To request access please fill out this form  [https://aka.ms/applyforconversationsummarization."}}](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fapplyforconversationsummarization.%2522%257d%257d&data=05%7C01%7Cyuantw%40microsoft.com%7C8bedd016b76543d5232008da65322781%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637933563398929721%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AiEGXxeLcVrNBrE6Cvlw7bpI3ppt3%2F2Po77vKAn7CIQ%3D&reserved=0)}

Headers:
apim-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Thu, 14 Jul 2022 00:39:53 GMT
Content-Length: 290
Content-Type: application/json

   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.ProtocolOperationHelpers.ProcessMessageAsync[T](HttpPipeline pipeline, HttpMessage message, ClientDiagnostics clientDiagnostics, String scopeName, OperationFinalStateVia finalStateVia, RequestContext requestContext, WaitUntil waitUntil, Func`2 resultSelector)
   at Azure.AI.Language.Conversations.ConversationAnalysisClient.StartAnalyzeConversationAsync(WaitUntil waitUntil, RequestContent content, RequestContext context)
   at Azure.AI.Language.Conversations.ConversationAnalysisClient.AnalyzeConversationAsync(WaitUntil waitUntil, RequestContent content, RequestContext context)
   at Program.<Main>$(String[] args) in D:\TestLanguageServiceSDK\Program.cs:line 68
   at Program.<Main>(String[] args)
PS D:\TestLanguageServiceSDK>

**Comment by chrisbardon** [comment]
So it is- I have no idea how I missed that.  Filling out form now.
