### ISSUE TITLE
[BUG] - Azure Search DataSource connection with Managed Identity

### ISSUE THREAD

**Issue by gregoks** [Azure/azure-sdk-for-net#29813]
### Library name and version

Azure.Search.Documents 11.4.0-beta.8

### Describe the bug

Hi!

I'm trying to create datasource connection in my search index using managed identity. I followed this guide - https://docs.microsoft.com/en-us/azure/search/search-howto-managed-identities-cosmos-db

This is the code that I'm using (CosmosDB):

```
var connectionString =
                    "ResourceId=/subscriptions/<guid>/resourceGroups/mp-mprp-dev-df-global-rg/providers/Microsoft.DocumentDb/databaseAccounts/<dbName>";
                var ds = new SearchIndexerDataSourceConnection("dsName", SearchIndexerDataSourceType.CosmosDb, connectionString, searchIndexerDataContainer)
                {
                    DataChangeDetectionPolicy = new HighWaterMarkChangeDetectionPolicy(SearchIndexConstants.HighWaterMarkColumnName),
                    DataDeletionDetectionPolicy = new SoftDeleteColumnDeletionDetectionPolicy
                    {
                        SoftDeleteColumnName = SearchIndexConstants.SoftDeleteColumnName,
                        SoftDeleteMarkerValue = SearchIndexConstants.SoftDeleteMarkerValue
                    },
                    Identity = new SearchIndexerDataUserAssignedIdentity("/subscriptions/<guid>/resourcegroups/mp-sch-dev-df-eastus-rg/providers/microsoft.managedidentity/userassignedidentities/mp-sch-identity")
                };
```

but im getting the following error:

```
The request is invalid. Details: dataSource : A type named 'Microsoft.Azure.Search.SearchIndexerDataUserAssignedIdentity' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.
Status: 400 (Bad Request)Content:
{"error":{"code":"","message":"The request is invalid. Details: dataSource : A type named 'Microsoft.Azure.Search.SearchIndexerDataUserAssignedIdentity' could not be resolved by the model. When a model is available, each type name must resolve to a valid type."}}Headers:
Cache-Control: no-cache
Pragma: no-cache
client-request-id: 9b24fd07-fcb8-47f4-8be8-546c205a8f97
x-ms-client-request-id: 9b24fd07-fcb8-47f4-8be8-546c205a8f97
request-id: 9b24fd07-fcb8-47f4-8be8-546c205a8f97
elapsed-time: 5
Preference-Applied: REDACTED
Strict-Transport-Security: REDACTED
Date: Tue, 12 Jul 2022 14:25:54 GMT
Content-Type: application/json; charset=utf-8
Content-Language: REDACTED
Expires: -1
Content-Length: 263
```

Would appreciate any assistance 

### Expected behavior

The API should return 200 and create data source connection using managed identity

### Actual behavior

There is an error:

The request is invalid. Details: dataSource : A type named 'Microsoft.Azure.Search.SearchIndexerDataUserAssignedIdentity' could not be resolved by the model. When a model is available, each type name must resolve to a valid type.
Status: 400 (Bad Request)Content:
{"error":{"code":"","message":"The request is invalid. Details: dataSource : A type named 'Microsoft.Azure.Search.SearchIndexerDataUserAssignedIdentity' could not be resolved by the model. When a model is available, each type name must resolve to a valid type."}}Headers:
Cache-Control: no-cache
Pragma: no-cache
client-request-id: 9b24fd07-fcb8-47f4-8be8-546c205a8f97
x-ms-client-request-id: 9b24fd07-fcb8-47f4-8be8-546c205a8f97
request-id: 9b24fd07-fcb8-47f4-8be8-546c205a8f97
elapsed-time: 5
Preference-Applied: REDACTED
Strict-Transport-Security: REDACTED
Date: Tue, 12 Jul 2022 14:25:54 GMT
Content-Type: application/json; charset=utf-8
Content-Language: REDACTED
Expires: -1
Content-Length: 263

### Reproduction Steps

Try to create data source connection to search index using managed identity

### Environment

IDE - Visual Studio 17.2.4
Windows
DotNet 6

**Comment by gmndrg** [comment]
@gregoks This has been identified as a preview feature bug. This has been filed and will be fixed on best effort. Thank you so much for reporting this!

**Comment by ShivangiReja** [comment]
This issue has been fixed [here](https://github.com/Azure/azure-rest-api-specs/pull/20376). 

We have also updated SDK code as a part of [this](https://github.com/Azure/azure-sdk-for-net/pull/31176) PR. We will release this bug fix in our next beta version.

Thanks @gregoks for filing this issue!
