### ISSUE TITLE
NuGet Package restore failed for project: Unable to find version '1.0.1' of package 'Microsoft.Azure.Common.Dependencies'

### ISSUE THREAD

**Issue by YunLi1988** [Azure/azure-sdk-for-net#2983]
Error message:

Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project: Unable to find version '1.0.1' of package 'Microsoft.Azure.Common.Dependencies'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Microsoft.Azure.Common.Dependencies.1.0.1' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  C:\Program Files\Microsoft SDKs\Service Fabric\packages\: Package 'Microsoft.Azure.Common.Dependencies.1.0.1' is not found on source 'C:\Program Files\Microsoft SDKs\Service Fabric\packages\'.
  https://api.nuget.org/v3/index.json: Package 'Microsoft.Azure.Common.Dependencies.1.0.1' is not found on source 'https://api.nuget.org/v3/index.json'.

Also is not Microsoft.Azure.Common.Dependencies recently updated as WindowAzure.Common.Dependencies?

**Comment by markcowl** [comment]
All of the checked-in references to Microsoft.Azure.Common.Dependencies are referring to 1.0.0, which is available here: https://www.nuget.org/packages/Microsoft.Azure.Common.Dependencies/1.0.0
