### ISSUE TITLE
Mark .NET fluent APIs with "beta" of some sort

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-net#2985]

**Comment by martinsawicki** [comment]
For v1.0.0, we used &lt;remarks&gt; for the lack of an attribute-based mechanism analogous to Java SDK's annotation based mechanism (`@Beta`). But <remarks> still has lousy discoverability as it doesn't show up in the tooltip, only in the object browser, and you cannot discover it programmatically (e.g. via reflection).

Now exploring another mechanism - based on a base `IBeta` interface. It is easy to imagine how to use a `IBeta` to indicate entire Beta types:

```
interface IApplicationGateway : IBeta, ...
{...} 
```

In the case of individual methods being in Beta, on a type that is otherwise GA, they would be flagged as Beta by deriving a model-specific interface from the Beta-indicating interface and putting those model-specific Beta methods on that instead.

For example:
```
/// <summary>
/// Types deriving from this interface have at least some members that are in Beta.
/// </summary>
interface IBeta { }

/// <summary>
/// Members of this interface are in Beta and as such are subject to removal or change in
/// non-backwards compatible ways in the future regardless of the compatibility implications 
/// of the containing library's version number.
/// </summary>
interface IVirtualMachineBetaMembers : IBeta
{
    /// <summary>
    /// This does something.
    /// </summary>
    void SomeBetaMethod();

    /// <summary>
    /// This returns something.
    /// </summary>
    string SomeBetaProperty { get; }
}

/// <summary>
/// The client-side representation of an Azure virtual machine.
/// </summary>
interface IVirtualMachine : IVirtualMachineBetaMembers, ...
{
    // GA'd members only
    ...
}
```

The `IBeta` interface would be the empty interface that all the model-specific Beta interfaces would inherit from, so that there is just one common Beta “flag”. GA’ing a member would mean moving it from the `I*BetaMembers` interface to the model interface proper.

The same mechanism could be used on shared base interfaces (`ISupportsListing`, etc) – just splitting the Beta members out into separate Beta interfaces.

Some advantages of the interface-based approach include:

- The Beta status of a member would be much more discoverable – you’d see an indication of it right in the tooltip in VS
- The Beta status would be discoverable programmatically – which is an advantage the `@Beta` annotation in Java also possesses, but &lt;remarks&gt; don’t. You could have tools that discover all the references to Beta members or types in user code via reflection.

**Comment by jaimetotal** [comment]
Strolling to the issues to pick something when I found this one.

Have you consider a BettaAttribute (which I find it similiar to Java annotation) that can be used for both Interface, Class and Method?

I find it cleaner to read, easier on the conflicts as it usually won't have other attributes affecting it.
Regarding the others Acceptance Criterias: reflection, check; tooltip, not sure. You mean intellisense?

**Comment by martinsawicki** [comment]
the idea of a Beta attribute is what we started with, because `@Beta` is what we're doing in Java, but it doesn't quite work that way in .NET because of the other reasons: no tooltip indication, no object browser visibility - basically completely undiscoverable for the user. And the main goal of this is to show which APIs are in Beta for the user.

**Comment by martinsawicki** [comment]
the Azure SDK has adopted the approach described here, so closing this.
