### ISSUE TITLE
Can't update Microsoft.Azure.Common: The package tried to add a framework reference to 'System.Threading' which was not found in the GAC.

### ISSUE THREAD

**Issue by abatishchev** [Azure/azure-sdk-for-net#2987]
When I try to update Microsoft.Azure.Common from 2.1.1 to 2.1.2 I'm getting the following error:

>Failed to add reference. The package 'Microsoft.Azure.Common' tried to add a framework reference to 'System.Threading' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

**Comment by abatishchev** [comment]
Any response, please?

**Comment by markcowl** [comment]
The new version of Microsoft.AzureCommon supports net45 only, retarget your solution at .net 4.5 and you should be fine.  Otherwise, you will need to use an earlier version.

**Comment by abatishchev** [comment]
Does it mean it doesn't supper net46?

**Comment by enihcam** [comment]
@markcowl The issue still exists for net45

**Comment by laurence73** [comment]
issue still exists...

**Comment by abatishchev** [comment]
@markcowl please reopen? Why it was closed?

**Comment by BrainSlugs83** [comment]
Still happens with 2.1.3 and .NET 4.5.2 -- This should not be closed.

**Comment by BrainSlugs83** [comment]
2.1.1 installs fine, by the way.

**Comment by abatishchev** [comment]
Please post in the newly opened issue
