### ISSUE TITLE
[BUG] When using ServiceBusSessionProcessor If OnSessionInitializingAsync throws an exception messages are still processed

### ISSUE THREAD

**Issue by asanjabi** [Azure/azure-sdk-for-net#29889]
### Library name and version

Azure.Messaging.ServiceBus 7.9.0

### Describe the bug

If user code throws an exception in `OnSessionInitializingAsync`, the processor still continues with processing messages even though initialization failed.

### Expected behavior

If user code throws an exception during initialization seems like the right thing to do is to cancel processing that session.

### Actual behavior

During the [session initialization step](https://github.com/Azure/azure-sdk-for-net/blob/5aee4c5f0b72d3bc3ff0bf36f0c194e2cd800465/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L124), if the code throws an exception, it is caught at the [end of ReceiveAndProcessMessagesAsync ](https://github.com/Azure/azure-sdk-for-net/blob/5aee4c5f0b72d3bc3ff0bf36f0c194e2cd800465/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L311) which only logs the event.

Unfortunately, the finally clause only cleans up if the call [was successful?](https://github.com/Azure/azure-sdk-for-net/blob/5aee4c5f0b72d3bc3ff0bf36f0c194e2cd800465/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L341)  `CloseReceiverIfNeeded` won't clean this up properly anyhow since `_threadCount `only gets incremented if call [to initialize succeeds](https://github.com/Azure/azure-sdk-for-net/blob/5aee4c5f0b72d3bc3ff0bf36f0c194e2cd800465/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L85), which gets skipped and during [clean-up it will be -1](https://github.com/Azure/azure-sdk-for-net/blob/5aee4c5f0b72d3bc3ff0bf36f0c194e2cd800465/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L183).

Since [call to `CreateReceiver`](https://github.com/Azure/azure-sdk-for-net/blob/5aee4c5f0b72d3bc3ff0bf36f0c194e2cd800465/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L113) happens before the user code `_receiver `is already assigned.  

When the next thread starts, the call to [initialization is skipped](https://github.com/Azure/azure-sdk-for-net/blob/5aee4c5f0b72d3bc3ff0bf36f0c194e2cd800465/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L81) which causes messages to be processed even though the user code is not initialized properly.

### Reproduction Steps

1. Use `ServiceBusSessionProcessor` to listen to a session enabled queue.
1. Throw an exception during `SessionInitializingAsync` event.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @asanjabi,
OnSessionInitializingAsync is meant to be a hook where you can run logic before processing a session. I think it would be too opinionated of the SDK to assume that an unhandled exception means the session should be skipped. You can catch the exception in your event handler and call ReleaseSession if you want to avoid processing the session. But as you've noted, ReleaseSession is not currently available in the relevant event args. I will submit a PR to fix this.
