### ISSUE TITLE
Latest VM scale sets are not available in the ContainerServiceVMSizeTypes.cs 

### ISSUE THREAD

**Issue by chamathwijeweera** [Azure/azure-sdk-for-net#29892]
### Library name and version

ContainerServiceVMSizeTypes.cs latest version

### Describe the bug

New VM scale sets are missing.

I am looking for v5 version of VM scale sets. When I tryout using Azure Rest api,
**GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Compute/locations/{location}/vmSizes?api-version=2022-03-01**,
Ex :- {
      "name": "Standard_D2_v5",
      "numberOfCores": 2,
      "osDiskSizeInMB": 1047552,
      "resourceDiskSizeInMB": 0,
      "memoryInMB": 8192,
      "maxDataDiskCount": 4
    },
 I found the required versions are available, but not in the Azure fluent sdk. Will this be available on 
 after adding those VM information to this class?

### Expected behavior

Having latest VM scale sets 

### Actual behavior

 Since 2019 ContainerServiceVMSizeTypes class has not update, so latest VM scale are not available.

### Reproduction Steps

Compare the response from the Azure REST api VM scale sets and Azure SDK class ContainerServiceVMSizeTypes for the difference.

### Environment

.net Framework 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by chamathwijeweera** [comment]
Hello,

Any updates on this request, or is there any workaround that I can follow to full fill my requirement.

Thank you.

**Comment by cmnawagamuwa** [comment]
The same issue happened to me

**Comment by venujakasun** [comment]
Hi All,

The same issue happened to me is there any workaround that I can follow to full fill my requirement?

Thank you.
