### ISSUE TITLE
[QUERY] ARM scopes in non-public clouds

### ISSUE THREAD

**Issue by pharring** [Azure/azure-sdk-for-net#29891]
### Library name and version

Azure.Identity

### Query/Question

In Azure.Identity , AzureAuthorityHosts.cs lists the default scopes to use for ARM in various clouds:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/AzureAuthorityHosts.cs#L47

Note that these scopes all have a double slash.

However, in Azure.ResourceManager, we have a list of ARM endpoints and their audiences (derived from ARM metadata).
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/ArmEnvironment.cs

Note that only the public cloud audience has a trailing slash, which will result in the double slash for DefaultScope.

One of these probably needs to be changed. I'm inclined to go with ArmEnvironment.cs since it's derived from ARM metadata: i.e. only AzurePublicCloud should have the double-slash.

I can also believe that both forms work in the known clouds, but I recommend we be consistent.

**Comment by schaabs** [comment]
@pharring I believe you're correct that both the single and double trailing slashes will work. At one point I believe the second trailing slash was required, as the audience needed to exactly match the app registration, but the STS updated to accept either. I agree we should be consistent here, we can follow up with the ARM team to determine which is "more correct" and update accordingly.
