### ISSUE TITLE
[Container Registry] CanGetManifestsOrdered failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29896]
Container Registry nightly test runs are failing with:

> Error message
> Microsoft.Rest.Azure.CloudException : Long running operation failed with status 'BadRequest'.
> 
> 
> Stack trace
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.CheckErrorStatusAndThrowAsync(HttpRequestMessage request, HttpResponseMessage response)
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.GetRawAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.UpdateResourceFromPollingUri(Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.Poll(Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.StartPollingAsync()
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.BeginLROAsync()
>    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody,THeader](IAzureClient client, AzureOperationResponse`2 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody](IAzureClient client, AzureOperationResponse`1 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.Azure.AzureClientExtensions.GetPostOrDeleteOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ContainerRegistry.RegistriesOperations.ImportImageWithHttpMessagesAsync(String resourceGroupName, String registryName, ImportImageParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ContainerRegistry.RegistriesOperationsExtensions.ImportImageAsync(IRegistriesOperations operations, String resourceGroupName, String registryName, ImportImageParameters parameters, CancellationToken cancellationToken)
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRegistryRecordedTestBase.ImportImageAsync(String registry, String repository, List`1 tags) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRegistryRecordedTestBase.cs:line 198
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRegistryRecordedTestBase.ImportImageAsync(String registry, String repository, String tag) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRegistryRecordedTestBase.cs:line 169
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRepositoryLiveTests.CanGetManifestsOrdered() in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRepositoryLiveTests.cs:line 245
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRepositoryLiveTests.CanGetManifestsOrdered() in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRepositoryLiveTests.cs:line 269
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1706472&view=results

@jsquire for notification.

**Comment by ArthurMa1978** [comment]
@jsquire check the log this is dataplane sdk

**Comment by jsquire** [comment]
@v-xuto:  Please leave test issues unassigned and tagged with "needs-team-triage" so that we can include them in our daily triage process.

**Comment by v-xuto** [comment]
@jsquire Got it. When test issues are unassigned, I will add the tag "needs-team-triage".

**Comment by ShivangiReja** [comment]
Now the pipeline is green - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1865663&view=results!
