### ISSUE TITLE
Diagnostics is not setting the Activity ParentId for OpenTelemetry tracing

### ISSUE THREAD

**Issue by rineshpk** [Azure/azure-sdk-for-net#29907]
### Library name and version

Azure.Messaging.ServiceBus  7.9.0

### Query/Question

When receiving a message through the Azure Service Bus, the **parent id** for the current activity is **null** and I could see the id received in the metadata in the '**Diagnostic-Id**' field is set as a **Link** for the current activity. When I export the traces, it is not producing the correct trace chain (exported as two separate traces for send and receive). 

If we create one activity manually and set the '**Diagnostic-Id**' to the parent id on the receiver side, exported traces chain is displayed in the correct hierarchy(send and the custom activity created at the receiver side in a single trace). 

Why diagnostics extension is not setting the **parent id** and what is the use of **Link** if it's not useful in chaining the trace?

**Comment by jsquire** [comment]
@lmolkova : You may have the best perspective on this.  Would you be so kind as to share your thoughts?

**Comment by JoshLove-msft** [comment]
@lmolkova, is this dependent on the App Insights fix here - https://github.com/microsoft/ApplicationInsights-dotnet/pull/2593?
How would customers consume the fix?

**Comment by rineshpk** [comment]
@JoshLove-msft I don't think it depends on App Insight fix as I'm not using App Insight here. I've integrated OpenTelemetry/ActivitySource (as in described [here ](https://devblogs.microsoft.com/azure-sdk/introducing-experimental-opentelemetry-support-in-the-azure-sdk-for-net/#get-started)) and exported the traces to Jaeger.

**Comment by lmolkova** [comment]
@rineshpk 

[Links](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#links-between-spans) is OpenTelemetry concept that allows connecting spans without introducing parent-child relationship between them. This is necessary in batching scenarios - they're recommended by OTel [messaging spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md).

Jaeger supports links to some extent - you should be able to see linked traces when looking into consumer (processing) spans:

![image](https://user-images.githubusercontent.com/2347409/179277399-63a88f85-d9e2-4142-9497-3cd196627dca.png)

**Comment by JoshLove-msft** [comment]
The new library uses links to connect the individual message activities with the parent send activity, as per the OTel messaging spec linked above. This was a conscious decision and a departure from the previous library that set diagnostic-Id to the parent activity. As far as I can tell, all of the relationships are there, but it may be that Jaeger does not support visualizing the relationships in the way that you prefer. It might be worth raising this as an enhancement request to the Jaeger folks - https://github.com/jaegertracing/jaeger

**Comment by rineshpk** [comment]
@JoshLove-msft Thank you for the clarification. I understood the concept of 'Links' for connecting the spans in the case of batch processing of messages. But, in the below examples from, [OTel message spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#examples).

![image](https://user-images.githubusercontent.com/52862975/179473191-dcf173d2-67a0-489d-8301-a8163fc91751.png)

and,
![image](https://user-images.githubusercontent.com/52862975/179473442-31e95254-d9b8-4e22-ae28-40936294b278.png)

The parent is there. I tried the same example scenarios with the current Azure.Messaging.ServiceBus which is setting the links only not the parent. 

![image](https://user-images.githubusercontent.com/52862975/179474185-acee8bbb-ad73-4d52-9a8f-870d18946a68.png)

**Comment by lmolkova** [comment]
@rineshpk OTel messaging spec is going through a stabilization process that will change the above examples and the relationship between receive and processing spans. Here are more detals https://github.com/open-telemetry/oteps/pull/192

Note that also the parent is the spec is a different span (one created for 'receive' operation and not 'send'). 
Unfortunately, the above examples are not feasible to achieve in ServiceBus SDK at this point.  We'll wait for the next version of OTel spec.

If you're willing to add a bit of manual instrumentation, you can create a processing span manually and make it a child of producer span (as Microsoft.Azure.ServiceBus did).

You can use [ActivitySource.StartActivity](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activitysource.startactivity?view=net-6.0#system-diagnostics-activitysource-startactivity(system-string-system-diagnostics-activitykind-system-string-system-collections-generic-ienumerable((system-collections-generic-keyvaluepair((system-string-system-object))))-system-collections-generic-ienumerable((system-diagnostics-activitylink))-system-datetimeoffset)) overload that takes string parentId and pass content of `Diagnostic-Id` header as parent.

You'd need your own ActivitySource for it and you can use [OTel docs](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/README.md#activity-source) for how to configure it.

**Comment by rineshpk** [comment]
@lmolkova Got it, thank you!
