### ISSUE TITLE
Incomplete code example

### ISSUE THREAD

**Issue by JoeyJaySWE** [Azure/azure-sdk-for-net#29901]
[Enter feedback here]
Build fail with code snippet from [Code Example]( https://docs.microsoft.com/en-us/dotnet/api/overview/azure/virtualmachines#code-example)

It might be that I'm missing some step or doing something wrong (this is my first time attempting this), 
but I was merely using the information provided by the page. If you manage to find what I did wrong,
please consider including the reply as additional instructions for the page to help clarify the steps for future visitors :)

## Steps to reproduce:

1. run in powershell
 ``` 
dotnet new console
```

2. install NuGet package according to page [.NET Cli](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/virtualmachines#code-example)
```
dotnet add package Microsoft.Azure.Management.Compute.Fluent
```

3. Remove the commented namespaces from Program.cs
```c#
using Microsoft.Azure.Management.Compute.Fluent;
using Microsoft.Azure.Management.Compute.Fluent.Models;
using Microsoft.Azure.Management.ResourceManager.Fluent.Core;


IVirtualMachine windowsVM = azure.VirtualMachines.Define("MyVirtualMachine")
    .WithRegion(Region.USEast)
    .WithNewResourceGroup("MyResourceGroup")
    .WithNewPrimaryNetwork("10.0.0.0/28")
    .WithPrimaryPrivateIPAddressDynamic()
    .WithNewPrimaryPublicIPAddress("MyIPAddressLabel")
    .WithPopularWindowsImage(KnownWindowsVirtualMachineImage.WindowsServer2012R2Datacenter)
    .WithAdminUsername("UserName")
    .WithAdminPassword("Password")
    .WithSize(VirtualMachineSizeTypes.StandardD3V2)
    .Create();
 ```

4. Run the code with
```
dotnet run
```

5. Receive the following error message in the console:
```
~\Program.cs(6,29): error CS0103: The name 'azure' does not exist in the current context.
The build failed. Fix the build errors and run again.
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2b138b-2471-5e90-0a7d-07f8ba5e7ce3
* Version Independent ID: 695b4a2a-7975-075d-db2c-c16250098824
* Content: [Azure compute libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/virtualmachines)
* Content Source: [api/overview/azure/virtualmachines.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/virtualmachines.md)
* Service: **virtual-machines**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by JoeyJaySWE** [comment]
Hi @scottaddie If I read you right, I need to include the Azure Authentication as they did in the link provided:
```c#
IAzure azure = Azure.Authenticate(credFile).WithDefaultSubscription();
```
Well, after attempting to install Microsoft.Azure.Management.Fluent package (like shown in step 2 of my recreation guide), I got 3 new errors I need to figure out.

1. The namespace for getting the `IAzure` interface
2. The namespace for getting the `Azure`
3. How the `credFile` should be structured, as it currently doesn't mention any references in the provided link.

I wanna include that these are problems while using .NET CLI and VSC. 
Thankfully, If I open Visual Studios instead, then I get some help with the namespaces and learn that I need to include
```c#
using Microsoft.Azure.Management.Fluent;
```
This solved problems 1. and 2. from my list, but might be a good idea to include for any potential VSC users reading through the documentation. Sadly I'm still stuck on question 3.

Thanks for the help so far though!

**Comment by scottaddie** [comment]
For question 3, you can create a JSON file containing the following fields:

1. subscription
2. tenant
3. client
4. key
5. managementURI
6. baseURL
7. authURL

The `credFile` parameter represents the path to the JSON file on disk. Note there are 2 other `Authenticate` method overloads that you can use instead: https://github.com/Azure/azure-libraries-for-net/blob/026c759303f9f4eb2c68c456cccdb56d64edb294/src/ResourceManagement/Azure.Fluent/Azure.cs#L736-L755

**Comment by JoeyJaySWE** [comment]
@scottaddie Sorry for the late reply,
Thanks for the extra details and structure.
Could please include it in the documentation as well?
Might be able to prevent more devs from reopening a similar question in the future.

**Comment by xboxeer** [comment]
@scottaddie this example is still using our track 1 SDK, I'd like update this page to use our track 2 SDK, how do you think?

**Comment by scottaddie** [comment]
@xboxeer This page is intended to describe an API in the Track 1 package. For that reason, it wouldn't make sense to replace the code sample with the equivalent Track 2 package sample. Until the Track 1 package is officially deprecated, we'll need to provide a working sample on this API ref page.

**Comment by xboxeer** [comment]
Track 2 SDK for compute already released and track 1 is deprecating, how about we add both?

**Comment by xboxeer** [comment]
Close this one, docs updated with auth part
