### ISSUE TITLE
[FEATURE REQ] Allow a callback for SessionInitializingAsync for SB functions

### ISSUE THREAD

**Issue by asanjabi** [Azure/azure-sdk-for-net#29917]
### Library name

 Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.5.1

### Please describe the feature.

The extension already allows a call back for [`ProcessErrorAsync` in the options](https://github.com/Azure/azure-sdk-for-net/blob/19b4e800e3711e6cb0c925d60df4a4aa957eed92/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Config/ServiceBusOptions.cs#L131)  it would be helpful to also expose `SessionInitializingAsync`, and `SessionClosingAsync` using the same pattern.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by danielmarbach** [comment]
I have given this a quick attempt. See https://github.com/Azure/azure-sdk-for-net/pull/29945
