### ISSUE TITLE
[Container Registry] Does not support import operation

### ISSUE THREAD

**Issue by crgarcia12** [Azure/azure-sdk-for-net#29913]
### Library name

Container Registry

### Please describe the feature.

az cli and PowerShell support image import:
https://docs.microsoft.com/en-us/azure/container-registry/container-registry-import-images?tabs=azure-cli

```
az acr import \
  --name myregistry \
  --source mysourceregistry.azurecr.io/aci-helloworld:latest \
  --image aci-helloworld:latest
```

The DotNet SDK `ContainerRegistryClient` does not have an Import method

**Comment by pallavit** [comment]
Adding /cc: @ShivangiReja to the thread. 

Thank you for reporting the issue. The preview version of the library supports upload/download of a blob using the BlobClient - https://github.com/Azure/azure-sdk-for-net/blob/18698f41971993527b0dba1e7e64e394fdbb4b4a/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ContainerRegistryBlobClient.cs#L309. Please let us know if it helps you with your scenario.
