### ISSUE TITLE
Enable username/password login scenario in Testframework

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#2993]
https://github.com/Azure/azure-sdk-for-net/commit/c456f0b0bf1fb5239873ee7fb924ea234d328e5a
The above commit disabled username/password scenario for .net core.
This was always enabled for .net core. Only interactive login is supported in .NET 45.
Login using username/password should be enable for .net core scenarios.

**Comment by hovsepm** [comment]
this is by design. http://stackoverflow.com/questions/39407952/adal-net-core-nuget-package-does-not-support-userpasswordcredential
