### ISSUE TITLE
[BUG] Inconsistent ETag results in Storage Blob SDK GetPropertiesAsync and GetBlobsAsync and ETag documentation issue

### ISSUE THREAD

**Issue by Schmaga** [Azure/azure-sdk-for-net#29942]
### Library name and version

Azure.Storage.Blobs 12.13.0

### Describe the bug

Hi Azure SDK Team.

I noticed some inconsistent ETag documentation and corresponding inconsistent behavior of ETag usage in at least two Azure Blob Storage APIs. I initially thought it would be two issues, but I think they are so related enough to be included in this one. Hope that is fine for you and does not produce any tracking issues.

Let me start with the documentation of the `ToString` method in the official documentation: 
https://docs.microsoft.com/de-de/dotnet/api/azure.etag.tostring?view=azure-dotnet#azure-etag-tostring(system-string)
The following example is provided:
```csharp
ETag tag = ETag.Parse("\"sometag\"");
Console.WriteLine(tag.ToString("G"));
// Displays: sometag
Console.WriteLine(tag.ToString("H"));
// Displays: "sometag"
```
This example cannot be used by external code, because the `Parse` method is internal. If I now use similar code, but initialize the Etag with the constructor that is public, the results will be wrong:
```csharp
ETag tag = new ETag("\"sometag\"");
Console.WriteLine(tag.ToString("G"));
// Displays: "sometag"
Console.WriteLine(tag.ToString("H"));
// Displays: "sometag"
```
The results are wrong because the `Parse` method does trim the quotes during initialization, the constructor does not. For anyone using the API from the outside, this behavior is not obvious and lead to bugs in our code and possibly the inconsistent behavior of the two sdk methods provided in the reproduction steps.

### Expected behavior

It would be a good thing to either make the `ETag.Parse` method publicly available, change the documentation to be more clear about quote behavior, or have the constructor behave the same way as the method.

I guess making the constructor behavior similiar could also immediately resolve the problem with creation of ETags, but is considerably more breaking.

Also, `BlobClient.GetPropertiesAsync` and `BlobContainerClient.GetBlobsAsync` should produce a consistent behavior of ETag formats.

### Actual behavior

`ETag.Parse` is not public, and using the constructor results in a different behavior than stated in the documentation

`BlobClient.GetPropertiesAsync` and `BlobContainerClient.GetBlobsAsync` property results produce different ETag formats for the same Blob when formatted with `ToString`.

I noticed this behavior after updating from 12.10.0 to 12.13.0, which broke quite a few of our tests that assert on the ETags. This would have resulted in wrong ETag comparison behavior if it had slipped into production.

We currently work around it by always trimming all outer quotes from ETags whenever we load them from blob storage. This solution only works as long as we do not use Weak ETags.

### Reproduction Steps

The two different ways of creating an ETag probably lead to the following inconsistent behavior of Storage SDK Methods `BlobClient.GetPropertiesAsync` and `BlobContainerClient.GetBlobsAsync`. If you fetch a Blob's metadata using these two different approaches:
```csharp
// fetching metadata for the single blob
props1 = await blobClient.GetPropertiesAsync(conditions: null, cancellationToken);
var etag1 = props1.ETag.ToString("G"); // produces "\"0xabcd1234\""

// fetching metadata for the blob as part of a batch
var blobs = _blobContainerClient.GetBlobsAsync(
            prefix: blobPrefix,
            traits: BlobTraits.Metadata,
            cancellationToken: cancellationToken);

await foreach (var blob in blobs.WithCancellation(cancellationToken))
{
     var etag2 = blob.Properties.ETag!.Value.ToString("G") // produces "0xabcd1234"
}
```
The blob ETag format is different, and a comparison of the two ETags `ToString` Calls would result in non-comparable data.

### Environment

- .NET 6.0.7 on Windows
- IDE: VS Prof. 17.2.5

**Comment by SaurabhSharma-MSFT** [comment]
@Schmaga Thanks for your feedback. Redirecting this to services team to look into.

**Comment by amnguye** [comment]
This is a duplicate issue.
https://github.com/Azure/azure-sdk-for-net/issues/16920

For a quick summary, we actually can't make the suggested change because of the breaking change. Some customers might expect the quotations on the respective ETag value.

**Comment by Schmaga** [comment]
Thank you, sorry that my initial research did not find the above mentioned issue. But even if it is a breaking change, wouldn't it be possible to update the behavior in a future major release, with deprecation or other notices up front? Or at least update the documentation to mention this flaw. The way it is now is very error-prone to use.

**Comment by agr** [comment]
What's worse, `ETag` produced by `Parse` and the one produced by calling constructor return false when compared for equality even when values are the same:

```C#
var cred = new DefaultAzureCredential();
var client = new BlobServiceClient(new Uri("https://storageaccount.blob.core.windows.net/"), cred);
var cont = client.GetBlobContainerClient("somecontainer");
var blob = cont.GetBlockBlobClient("test.txt");
const string content = "content";
var uploadResult = await blob.UploadAsync(new MemoryStream(Encoding.UTF8.GetBytes(content)), options: null);
var readStream = new MemoryStream();
var downloadResult = await blob.DownloadToAsync(readStream);

var uploadETag = uploadResult.Value.ETag;
var downloadETag = downloadResult.Headers.ETag.Value;
bool same = uploadETag == downloadETag;
Console.WriteLine("Same ETag: {0}", same);

var ueStr = uploadETag.ToString();
var deStr = downloadETag.ToString();
same = ueStr == deStr;
Console.WriteLine("Same ETag.ToString(): {0}", same);

var uehStr = uploadETag.ToString("H");
var dehStr = downloadETag.ToString("H");
same = uehStr == dehStr;
Console.WriteLine("Same ETag.ToString(\"H\"): {0}", same);
```

prints
```
Same ETag: False
Same ETag.ToString(): False
Same ETag.ToString("H"): True
```

I'm not sure this behavior is expected.
