### ISSUE TITLE
[BUG] New SDK blocks HTTP spans

### ISSUE THREAD

**Issue by MatisseHack** [Azure/azure-sdk-for-net#29955]
### Library name and version

Azure.Core 1.24.0

### Describe the bug

I use the [OpenTelemetry.Instrumentation.Http](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Http) package to trace requests made by my app. I was able to see traffic generated by the older `Microsoft.Azure.` management libraries, but the newer `Azure.` packages seem to block HTTP spans. I don't see a way to enable HTTP logging with the new libraries.

### Expected behavior

HTTP spans should not be suppressed by the Azure SDK or there should be an option to turn off suppression.

### Actual behavior

HTTP spans from [OpenTelemetry.Instrumentation.Http](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Http) are not available.

As a workaround, `Azure.Core.Http` spans are available after enabling `Azure.Experimental.EnableActivitySource`, but these spans are not as flexible and are not consistent with the other HTTP spans in my app.

### Reproduction Steps

1. Use the new `Azure.` management libraries
2. Enable [OpenTelemetry HttpClient instrumentation](https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/src/OpenTelemetry.Instrumentation.Http)

### Environment

Azure AppService using .NET 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by MatisseHack** [comment]
Any spans produced by [OpenTelemetry.Instrumentation.Http](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Http) within the Azure SDK are missing. Here is a simple example:

```
Activity.Id:          00-22cd49f5eea075f87ef9b72a3816d34b-0f63c7cb033b9e00-01
Activity.ParentId:    00-22cd49f5eea075f87ef9b72a3816d34b-703f7f713b1665ad-01
Activity.ActivitySourceName: OpenTelemetry.Instrumentation.Http
Activity.DisplayName: HTTP PUT
Activity.Kind:        Client
Activity.StartTime:   2022-07-18T19:50:22.1475110Z
Activity.Duration:    00:00:01.1814120
Activity.TagObjects:
    http.method: PUT
    http.host: management.azure.com
    http.url: https://management.azure.com/subscriptions/[subscription-id]/resourcegroups/[rg-name]?api-version=2021-04-01
    http.status_code: 200
    otel.status_code: UNSET
Resource associated with Activity:
    service.name: [service-name]
    service.instance.id: 353a1a26-930f-4d16-a51b-0609f745b4de
```

We use `OpenTelemetry.Instrumentation.Http` because we call multiple different APIs and it's easier to query our telemetry data if all HTTP spans are in a consistent format. Using `OpenTelemetry.Instrumentation.Http` is also more powerful because we can enrich the HTTP spans with extra information when needed. I don't think there is anything similar available for the `Azure.Core.Http` spans, right?

I do see spans for individual method calls now (e.g. `ResourceGroupCollection.CreateOrUpdate`), which is a great addition! I think these method spans provide plenty of information for most projects, but ideally it would still be possible to use `OpenTelemetry.Instrumentation.Http`.

**Comment by JoshLove-msft** [comment]
Have you followed one of the set up steps outlined [here](https://devblogs.microsoft.com/azure-sdk/introducing-experimental-opentelemetry-support-in-the-azure-sdk-for-net/#get-started)?

Since the OpenTelemetry support is still experimental, you need to set a flag to enable it.

**Comment by MatisseHack** [comment]
Yes, I have enabled the experimental OpenTelemetry support. Those spans do work!

The issue is not that I cannot get telemetry from the Azure SDK; the issue is that the Azure SDK suppresses telemetry spans produced by [`OpenTelemetry.Instrumentation.Http`](https://www.nuget.org/packages/OpenTelemetry.Instrumentation.Http).

The `Azure.Core.Http` spans are a helpful alternative, but are not sufficient for some use cases and are not consistent with the `OpenTelemetry.Instrumentation.Http` based HTTP spans I collect from other SDKs in my project.

**Comment by JoshLove-msft** [comment]
Hi @MatisseHack,
Since the Azure.Core library creates its own HTTP spans, the Otel library automatically suppresses creation of these same spans. If you don't want the spans from Azure.Core, you can specify the specific library that you want to collect spans from, e.g.:
```c#
AddSource("Azure.ResourceManager.*")
```
instead of using `"Azure.*"`

Can you tell us more about what is missing from the Azure.Core HTTP spans?

**Comment by MatisseHack** [comment]
> Since the Azure.Core library creates its own HTTP spans, the Otel library automatically suppresses creation of these same spans.

Yes exactly. I would like an option to turn this behavior off so that I can collect standard HTTP spans instead of the Azure SDK's custom implementation.

> If you don't want the spans from Azure.Core, you can specify the specific library that you want to collect spans from

I do want HTTP spans. I would prefer to use spans from `OpenTelemetry.Instrumentation.Http`, but they aren't available so spans from `Azure.Core.Http` are my only option.

> Can you tell us more about what is missing from the Azure.Core HTTP spans?

There are two reasons I prefer `OpenTelemetry.Instrumentation.Http` over `Azure.Core.Http`:

1. It's an inconvenience to have multiple types of HTTP spans in my app. If every SDK in my app produced their own custom HTTP spans, I'd have an unintelligible mess of HTTP spans that would be difficult to query. The spans from `OpenTelemetry.Instrumentation.Http` provide a uniform implementation that works everywhere except the Azure SDK.

2. The main blocker for my team is that the Azure SDK does not support enriching HTTP spans. `OpenTelemetry.Instrumentation.Http` provides a [convenient mechanism](https://github.com/open-telemetry/opentelemetry-dotnet/blob/131b350d95c6688b1364f174270787656cc9c746/src/OpenTelemetry.Instrumentation.Http/HttpClientInstrumentationOptions.cs#L38-L63) to enrich HTTP spans with extra information that is not collected by default. I don't see an equivalent capability for `Azure.Core.Http`.

**Comment by MatisseHack** [comment]
To illustrate my desired behavior, take a look at the AWS SDK, which is a good example of how HTTP spans could work in the Azure SDK. By default, the AWS SDK doesn't produce any spans of its own and `OpenTelemetry.Instrumentation.Http` spans work normally. After adding an [instrumentation library](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/tree/main/src/OpenTelemetry.Contrib.Instrumentation.AWS), the AWS SDK produces the equivalent of Azure's `Azure.ResourceManager.*` spans and suppresses `OpenTelemetry.Instrumentation.Http` spans. I'm not sure suppressing child spans by default is the best choice, but at least there is a [configuration option](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/ff47b5aa9f2ce0e03cd219ea029687e229baa195/src/OpenTelemetry.Contrib.Instrumentation.AWS/AWSClientInstrumentationOptions.cs#L27) to disable suppression of child spans entirely.

I would like the Azure SDK to work in a similar way. If `Azure.Experimental.EnableActivitySource` is disabled, `OpenTelemetry.Instrumentation.Http` spans should not be suppressed. When `Azure.Experimental.EnableActivitySource` is enabled, downstream spans should still be accessible (potentially behind a configuration option).

**Comment by JoshLove-msft** [comment]
@MatisseHack, the Azure library is not suppressing the OpenTelemetry spans, but rather the OpenTelemetry library is not creating duplicate HTTP spans. My question was more around why do you prefer the OpenTelemetry HTTP spans to the Azure.Core Http spans?

**Comment by MatisseHack** [comment]
It definitely makes sense that I need to opt in to collecting `Azure.*` spans! I'd just like to minimize interference with with other telemetry sources I've subscribed to. e.g. `builder.AddSource("OpenTelemetry.Instrumentation.Http")`. However, I'm not too concerned about default behavior as long as it's configurable.

**Comment by JoshLove-msft** [comment]
> As for adding hooks to enrich Azure.Core HTTP spans, I will follow up on this.

@lmolkova do you know if this is possible?

**Comment by JoshLove-msft** [comment]
@MatisseHack, if you don't opt in to collecting the "Azure.*" spans, don't you get the Http spans as you are expecting?

**Comment by MatisseHack** [comment]
Yes, after updating .NET and the OpenTelemetry and Azure SDKs I'm now getting the `OpenTelemetry.Instrumentation.Http` spans again! Not sure exactly which update did the trick, but it's working as expected now. Thanks for the discussion and help!
