### ISSUE TITLE
Expose Test Proxy TransportCustomizations in TestFramework

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#29959]
### Library name

Azure.Core.TestFramework

### Please describe the feature.

Recently, [support was added to the TestProxy ](https://github.com/Azure/azure-sdk-tools/pull/3490)to allow transport customization related to TLS cert configurations.

This support needs to be plumbed into TestFramework to allow tests to take advantage of this new feature.

This should be configurable as some kind of options for the recording session.

**Comment by JoshLove-msft** [comment]
This was addressed in https://github.com/Azure/azure-sdk-for-net/pull/30030
