### ISSUE TITLE
[FEATURE REQ] Add more filter to BlobContainerClient.GetBlobs( )

### ISSUE THREAD

**Issue by Dan127001** [Azure/azure-sdk-for-net#29961]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

We have a Storage Account where we save blobs generated by multiple devices and download the changed ones.

To get the delta (blobs that changed by other PCs since last check)

Right now:
- we call BlobContainerClient.GetBlobs( ) and get all blobs locally
- filter **already locally fetched BlobItem** by: later than DateTime XY

What we would like to do:
- give additional parameter(s) to the BlobContainerClient.GetBlobs( ) method, or have a similar method where we can filter by those parameter(s)
-> this way many blobs could be filtered within the StorageAccount before returning to the client

In this case:
- ByDateTime (later than a given UTC-DateTime)

Another usefull filter would be:

ByMetaData
> contains or does not contain
-> a {Key,Value]-Pair or
-> a [List of Values] for a Key in MetaData

**Comment by navba-MSFT** [comment]
@Dan127001 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Dan127001 If you would like to use the Powershell script to achieve this ask you can use below:

```
$StorageAccountName = "AccountName" 
$StorageAccountKey = "What_ever_your_key_is_123asdf5524523A=="
$Context = New-AzureStorageContext -StorageAccountName $StorageAccountName -StorageAccountKey $StorageAccountKey
$ContainerName = "Container"

$Blobs = Get-AzureStorageBlob -Container $ContainerName -Context $Context `
| Where-Object{$_.LastModified.DateTime -gt (Get-Date).Date}
```
You can then use the functions on Get-Date cmdlet to further narrow down the timeframe as below.

```
$Blobs = Get-AzureStorageBlob -Container $ContainerName -Context $Context `
| Where-Object{$_.LastModified.DateTime -gt ((Get-Date).Date).AddDays(-1)}
```

I could find a java sample as well to achive this. There should be a similar one in >NET too.

```
BlobServiceClient blobServiceClient = new BlobServiceClientBuilder().endpoint("https://youraccount.blob.core.windows.net").sasToken("yourtoken").buildClient();
BlobContainerClient blobContainerClient = blobServiceClient.getBlobContainerClient("yourcontainer");

BlobListDetails details = new BlobListDetails().setRetrieveMetadata(true);
ListBlobsOptions options = new ListBlobsOptions().setPrefix("yourprefix").setDetails(details);

blobContainerClient.listBlobs(options, null).stream().filter(blob ->  blob.getProperties().getLastModified().isAfter(OffsetDateTime.now().minusDays(1))).forEach(blob -> System.out.printf("Name: %s %s%n", blob.getName(), blob.getProperties().getLastModified()));
```


Reference for more Info [here](https://stackoverflow.com/a/55394440) and [here](https://stackoverflow.com/a/71025640).

**Comment by navba-MSFT** [comment]
@Dan127001 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you have any questions on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Dan127001 The action is currently pending on you to check the above suggestion and see if that helps. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.

**Comment by Dan127001** [comment]
Thanks for the reply, however I cannot see the ListBlobs Method.

This method is not available within the new Azure.Storage.Blobs Package.
(https://github.com/Azure/azure-sdk-for-net/tree/Azure.Storage.Blobs_12.13.0/sdk/storage/Azure.Storage.Blobs)

The ListBlobs method you are referring to is from the depricated Microsoft.Azure.Storage.Blob Package.
(https://github.com/Azure/azure-storage-net)

Am I missing something here?

**Comment by jsquire** [comment]
@navba-MSFT:  Please do not close out issues tagged with `needs-author-feedback` directly.  There are automation rules to manage closure and ensure that folks opening the issue have time to respond before abrupt closure.

**Comment by navba-MSFT** [comment]
@Dan127001 and @jsquire I have taken the ownership of the newly created issue. Azure/azure-sdk-for-net/issues/30184 I will update my findings on that thread.
