### ISSUE TITLE
[BUG] Method SecretClient.GetPropertiesOfSecretsAsync is not awaitable in Azure.Security.KeyVault.Secrets

### ISSUE THREAD

**Issue by marvin-garcia** [Azure/azure-sdk-for-net#29965]
### Library name and version

Azure.Security.KeyVault.Secrets 4.3.0

### Describe the bug

I am trying to use the method **SecretClient.GetPropertiesOfSecretsAsync** in .NET Core and noticed it is not awaitable. 

### Expected behavior

Method should support the use of await operator.

### Actual behavior

The method behaves as a synchronous process.

### Reproduction Steps

The code below will not run:

```
var secretClient = new SecretClient(new Uri(keyVaultEndpoint), keyVaultCredential);
var secrets = await secretClient.GetPropertiesOfSecretsAsync();
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  3.1.421 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Hi @marvin-garcia.   Thank you for reaching out and we regret that you're experiencing difficulties.  `GetPropertiesOfSecretsAsync` returns an [AsyncPagable](https://docs.microsoft.com/en-us/dotnet/api/azure.asyncpageable-1) instance, which is typically used like a standard `AsyncEnumerable`, as it abstracts the explicit async calls needed to load pages.    

For example:

```csharp
var client = new SecretClient(new Uri(keyVaultEndpoint), keyVaultCredential);

await foreach (SecretProperties secret in client.GetPropertiesOfSecretsAsync())
{
    Console.WriteLine(secretProperties.Name);
}
```

More examples and context can be found in the [KeyVault Overview](https://docs.microsoft.com/dotnet/api/overview/azure/security.keyvault.secrets-readme?view=azure-dotnet#list-secrets-asynchronously) docs.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
