### ISSUE TITLE
[TestFramework][FormRecognizer] Speed up LRO polling for new LRO pattern

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#29966]
## Description

Check https://github.com/Azure/azure-sdk-for-net/pull/29914 for more information about the new LRO pattern that uses the `WaitUntil` enum.

Our Test Framework has some kind of logic to speed up the polling process of LROs in playback mode. For some reason, this logic does not seem to work with the new LRO pattern in Form Recognizer. This is causing the `StartBuildModelWithNeuralBuildMode` and `StartAnalyzeDocumentCanParseMultipageInvoice` tests to time out, so we disabled them for the time being.

Multiple tests were affected in the Form Recognizer test project, but currently the tests mentioned above are the only ones timing out.

## Action Items

- Investigate and fix the issue so that LRO polling takes no extra time with the new pattern.
- Re-enable `StartBuildModelWithNeuralBuildMode` and `StartAnalyzeDocumentCanParseMultipageInvoice`.
- Ensure Form Recognizer ci stays green.

**Comment by JoshLove-msft** [comment]
The issue seems to be that instrumenting the operation doesn't help because we don't get back the operation instance to instrument until after we've already polled for the operation completion.

**Comment by JoshLove-msft** [comment]
@m-nash informed me that this is already solved for mgmt plane by changing the argument to WaitUntil.Started, instrumenting the LRO, and then calling WaitForCompletion with the ZeroPoller in the interceptor - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/Instrumentation/ManagementInterceptor.cs#L41
