### ISSUE TITLE
Can you please document the default visibility timeout?[QUERY]

### ISSUE THREAD

**Issue by VPriya6** [Azure/azure-sdk-for-net#30008]
### Library name and version

Assembly Microsoft.WindowsAzure.Storage, Version=9.3.2.0

### Query/Question

There is no documentation of what the default visibility timeout for the queue message is.

**Comment by VPriya6** [comment]
is it 30 secs?

**Comment by navba-MSFT** [comment]
@VPriya6 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@VPriya6 The default value of visibility timeout has been documented here under the [Get-messages REST API docs](https://docs.microsoft.com/en-us/rest/api/storageservices/get-messages):

Parameter | Description
-- | --
visibilitytimeout | Optional. Specifies the new visibility timeout value, in seconds, relative to server time. The default value is 30 seconds.A specified value must be larger than or equal to 1 second, and cannot be larger than 7 days, or larger than 2 hours on REST protocol versions prior to version 2011-08-18. The visibility timeout of a message can be set to a value later than the expiry time.

Hope this helps.

**Comment by navba-MSFT** [comment]
@VPriya6 I hope you had a chance to look above comment and the documentation link shared. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
