### ISSUE TITLE
[QUERY] AcceptNextSessionAsync customize timeout period

### ISSUE THREAD

**Issue by hgjura** [Azure/azure-sdk-for-net#30003]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

While using AcceptNextSessionAsync to get a new session receiver, I have a use case when I need to customize the timespan between when no new session is available and when this throws a ServiceBusException with reason ServiceBusFailureReason.ServiceTimeout. It seems that this is always 1 minute, and would like to make it shorter or longer. 

Also, why the reason this particular method needs to throw an error when it can't find any new session, instead of returning null like in line with how the various receivers are designed? it seems out of place on how it works with the rest of similar methods in the library.

Thanks

**Comment by JoshLove-msft** [comment]
Hi @hgjura, just to better understand your scenario, will you need to use different durations for different calls with the same client? 

The value used is based on the TryTimeout that can be specified in the client's RetryOptions, but this would impact all operations, not just accept session, so we may want to consider adding a parameter to this method, or an additional options property.

In terms of why we throw here, you are correct that it is a bit inconsistent with ReceiveMessageAsync which returns null when there are no messages available. However, we felt that it would be more awkward to potentially return null from a method that should be returning what is essentially a client (ServiceBusSessionReceiver), than having a null message. Throwing an exception with reason of ServiceTimeout seems to better communicate what happened - we tried to accept a session, but we timed out as there were no sessions available. This, along with having continuity with the prior Service Bus library which also throws, led to the decision.

**Comment by hgjura** [comment]
@JoshLove-msft  Thanks for your reply. I was able to use your information and come up with a workable solution. However, here is some feedback:
- Throwing an exception to use it as conditional workflow, I believe it was used awhile back (I remember using like a decade ago) but I don't think is used any longer. I bet most (including myself) have created a side function that catches the exception and returns null, so they can do something like  <pseudo code>_getNextSessionAsync()?. ReceiveMessagesAsync() </pseudo code>. Instead, quite a bot of code needs to be written to get to the same results. Backward compatibility with older library is understandable, but the rest of the library is not much backward-compatible either.
- The timeout is another headscratcher. I was expecting that the MaxWaitTime, which customizable and passed in as a parameter. As you said TryTimeout overrides everything. In the case when you are using this scenario (sessions) the MaxWaitTime becomes irrelevant. I got around this, by passing a cancellation token and have it cancelled at a predefined/custom time, but it is less desirable as it throws a Task Cancellation exception that I need to unnecessarily handle. 

If you find this feedback useful you may want to consider these improvements.

**Comment by JoshLove-msft** [comment]
> * Throwing an exception to use it as conditional workflow, I believe it was used awhile back (I remember using like a decade ago) but I don't think is used any longer. I bet most (including myself) have created a side function that catches the exception and returns null, so they can do something like  _getNextSessionAsync()?. ReceiveMessagesAsync() </pseudo code>. Instead, quite a bot of code needs to be written to get to the same results. Backward compatibility with older library is understandable, but the rest of the library is not much backward-compatible either.

This is a fair point. Since the library is already generally available, we can't change the behavior now. The only thing we could do would be to add a new method that returned null instead of throwing. I'm not sure that this would improve the situation given the potential confusion it would add, but it is something we can consider. 


> * The timeout is another headscratcher. I was expecting something like the MaxWaitTime, which customizable and passed in as a parameter. As you said TryTimeout overrides everything. In the case when you are using this scenario (sessions) the MaxWaitTime becomes irrelevant, because the longer session timeout always win. I got around this, by passing a cancellation token and have it cancelled at a predefined/custom time, but it is less desirable as it throws a Task Cancellation exception that I need to unnecessarily handle.

TryTimeout doesn't override everything, but it is the fall back that we use. If you specify MaxWaitTime while receiving, that value will be used rather than TryTimeout. Initially when we were developing this library, the underlying AMQP library did not have support for cancellation tokens, so we could not rely fully on this. Now that there is cancellation token support, cancelling using the cancellation token is the recommended way to handle this.
