### ISSUE TITLE
Azure.Storage.Blobs.ChangeFeed UpdatedBlobProperties seems to be always null

### ISSUE THREAD

**Issue by quality-leftovers** [Azure/azure-sdk-for-net#30002]
When receiving feed events using the `BlobChangeFeedClient` I only get null values for `UpdatedBlobTags` (in `EventData <type: BlobChangeEventData>`).

This applies to the `BlobChangeFeedEventType.BlobPropertiesUpdated` events and all other Events.

Is this a limitation of the preview version? Or should this be working?

Update: Got the Properties now. But still missing the tags.

**Comment by navba-MSFT** [comment]
@quality-leftovers Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@quality-leftovers The[ BlobTagsChange Class ](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.changefeed.blobtagschange?view=azure-dotnet-preview)provides the Blob tags that were updated as part of the change feed event. 

NewTags | [New Tags.](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.changefeed.blobtagschange.newtags?view=azure-dotnet-preview#azure-storage-blobs-changefeed-blobtagschange-newtags). It has the below properties too:
-- | --
OldTags | [Previous Tags.](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.changefeed.blobtagschange.oldtags?view=azure-dotnet-preview#azure-storage-blobs-changefeed-blobtagschange-oldtags)

Hope this helps.

**Comment by navba-MSFT** [comment]
@quality-leftovers I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@quality-leftovers The action is currently pending on you to try the above suggestion. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
