### ISSUE TITLE
NuGet Microsoft.Azure.Management.Resources error

### ISSUE THREAD

**Issue by AlexGevorkyan** [Azure/azure-sdk-for-net#3001]
Hi guys! I have read the closed issue 
https://github.com/Azure/azure-sdk-for-net/issues/1988
and still have to write my question.

In accordance with the article
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-get-started-csharp
I try to add the package Microsoft.Azure.Management.ResourceManager to my solution.

I used both variants to install it:
Install-Package Microsoft.Azure.Management.ResourceManager -Pre
and
Install-Package Microsoft.Azure.Management.Resources -Version 2.20.0-preview -Pre
They both failed with message:
"Install-Package : An error occurred while retrieving package metadata for 'Microsoft.Azure.Management.Sql.1.2.0-preview' ..."
I use VS2015.
Could you tell me what is wrong please.

**Comment by shahabhijeet** [comment]
@AlexGevorkyan can you specify as to what version of nuget are you using.
Nuget 3.x should solve this problem.
Let me know if you see the same error after you upgrade to Nuget 3.x

**Comment by markcowl** [comment]
Closing for lack of response.  If this recurs, please reopen this, or open a new issue
