### ISSUE TITLE
can't find a constructor for the Azure Mobile Service Client

### ISSUE THREAD

**Issue by rensohollhumer** [Azure/azure-sdk-for-net#30016]
When calling our Azure API endpoint UserController.CurrentUser() action, it uses the Azure MobileServiceClient  assembly. However sometimes it generates and error message is basically that it can't find the method on the Azure MobileServiceClient class and the method it's looking for is the constructor for the MobileServiceClient that takes in a string URL and a list of HttpMessageHandlers. The use the latest version of the MobileServiceClient assebly version 4.2.

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the Azure Mobile Apps packages are maintained as [#441](https://github.com/Azure/azure-mobile-apps/issues/441).
