### ISSUE TITLE
ProxyTransport should handle double instrumentation scenarios without re-using the current TestRecordingInstance

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#30029]
### Library name

Azure.Core.TestFramework

### Please describe the feature.

Currently, when it is detected that a client has "double instrumented" an instance of ClientOptions (this occurs when an instance of ClientOptions is reused across multiple test runs), the current instance of the `ProxyTransport` is reused rather than constructing a new instance. This results in the `TestRecording` instance set on the original `ProxyTransport` to be re-used (with stale information).

Code in question is here:

https://github.com/Azure/azure-sdk-for-net/blob/85ef148e6c1e0c566c2047d5fa59adff1b7d6463/sdk/core/Azure.Core.TestFramework/src/TestRecording.cs#L257-L260

**Comment by JoshLove-msft** [comment]
Rather than returning the current transport, we should throw an exception. We would need to fix any tests that are broken by this change.

**Comment by JoshLove-msft** [comment]
This came up again recently. It would be good to throw here.
