### ISSUE TITLE
Update Newtonsoft.Json version in Microsoft.Azure.KeyVault.WebKey

### ISSUE THREAD

**Issue by JunTaoLuo** [Azure/azure-sdk-for-net#3003]
Not sure if this would be considered as a duplicate of #3002 but we are running into an issue with the Microsoft.Azure.KeyVault package. The dependency Microsoft.Azure.KeyVault.WebKey dependency has restricted the Newtonsoft.Json dependency to be < 10.0.0 and we have updated our stack in ASP.NET Core to 10.0.1. We consume this package so I'm wondering if the dependency will be updated soon?

cc @Eilon

**Comment by markcowl** [comment]
@JunTaoLuo This would be a separate, but related issue.

**Comment by JunTaoLuo** [comment]
Any ETA on when this will be fixed?

cc @Eilon

**Comment by kyschouv** [comment]
An ETA would be appreciated - we're currently dealing with the version conflicts created by consuming this package in addition to other ASP.NET Core packages.

**Comment by jjdoo** [comment]
Please also update Newtonsoft.Json dependecy for net45 which current only support version 6.0.8.

**Comment by aajmot** [comment]
One of my existing project using NewronSoft 4.5 and I cannot update the version but needs to implement the key vault encryption in file upload which version of key vault nuget to use?
it's not throwing the error at compile time but failed at runtime, what to do?

**Comment by dagavriliu** [comment]
how exactly was the ver cap removed in https://github.com/Azure/azure-sdk-for-net/pull/3146
?
