### ISSUE TITLE
Support Azure Automation in Azure.Identity package 

### ISSUE THREAD

**Issue by namrataguptams** [Azure/azure-sdk-for-net#30031]
Support Managed Identity for Azure Automation in Azure.Identity package -  doc can be seen at https://docs.microsoft.com/en-us/azure/automation/enable-managed-identity-for-automation

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@namrataguptams  thank you for reaching us, can you please provide more information about question

**Comment by ArthurMa1978** [comment]
@jsquire  this is a ask for Azure.Identity package, I think this own by your team, right?

**Comment by jsquire** [comment]
The way that I read it, it's an ask to support `Azure.Identity` in the Automation library.   Managed Identity is already supported by `Azure.Identity`.    @namrataguptams :  Would you please be so kind as to confirm your intent with this request?

**Comment by namrataguptams** [comment]
Azure.Identity supports managed identity but in azure automation scenario. Had a chat with @Scott ***@***.***> for the same and he asked to file feature request

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by namrataguptams** [comment]
Azure.Identity already supports Managed Identity but it does not support managed Identity for Automation scenarios. I had a discussion with Scott Schaab asked me to file this feature request
