### ISSUE TITLE
Values InvokedByType can take

### ISSUE THREAD

**Issue by praveench02** [Azure/azure-sdk-for-net#30062]
Could you pls elaborate on the values "InvokedByType" can take  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7192a737-84ab-45ce-4644-9af69c04fd94
* Version Independent ID: d2b86151-1d6e-fec8-551d-f8935dcfdf10
* Content: [PipelineRunInvokedBy.InvokedByType Property (Microsoft.Azure.Management.DataFactory.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.pipelineruninvokedby.invokedbytype?view=azure-dotnet#microsoft-azure-management-datafactory-models-pipelineruninvokedby-invokedbytype)
* Content Source: [xml/Microsoft.Azure.Management.DataFactory.Models/PipelineRunInvokedBy.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.DataFactory.Models/PipelineRunInvokedBy.xml)
* Service: **data-factory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
