### ISSUE TITLE
Absolute & Relative path handling in the SDK

### ISSUE THREAD

**Issue by sarangan12** [Azure/azure-sdk-for-net#3007]
If the base url is something like: "http://m.yahoo.com/v1/api" and the path url is:

1. "/subscriptions/...." 
2. "/operations"

The resulting url to be hit will be 

1. http://m.yahoo.com/v1/api/subscriptions/... and
2. http://m.yahoo.com/v1/api/operations

But, this does not give me the option to hit a url such as http://m.yahoo.com/operations? This needs to be fixed in the sdk. (i.e. the sdk should enable us to handle absolute and relative paths).

**Comment by shahabhijeet** [comment]
@sarangan12 as we discussed offline, this logic is being added in the generated code and currently the logic is simply to add the trailing slash if it's missing. Incase if you think this logic is not right for CSharp, this change will have to be made in the autorest tool.

**Comment by sarangan12** [comment]
Based on offline discussion closing this.
