### ISSUE TITLE
"This value starts at 1." should be clarified

### ISSUE THREAD

**Issue by rmjcsltd** [Azure/azure-sdk-for-net#30095]
The page says "This value starts at 1." - this should be clarified. The value starts at zero. When a receiver receives the message the received message DeliveryCount will be 1 or more. When a receiver abandons or fails a message then the subscription message will have it's DeliveryCount incremented.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f54ee0d-4a21-4e76-b6e1-f1e7f518c9a4
* Version Independent ID: b75735b5-4f6d-0027-3998-46e59e873fe1
* Content: [Message.SystemPropertiesCollection.DeliveryCount Property (Microsoft.Azure.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.message.systempropertiescollection.deliverycount?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.ServiceBus/Message+SystemPropertiesCollection.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.ServiceBus/Message+SystemPropertiesCollection.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@rmjcsltd Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@rmjcsltd I was exploring retries recently and can confirm the first number you will see in Delivery Count is 1. So it is not Zero.
 
[Here](https://github.com/ricardocovo/AzurePlayground/tree/main/ServiceBus-Retries) is a dotnet sample code if you want a starting point for your testing.

It's the first delivery that reaches the client and therefore the count should be 1. When the message sits in "available" state, the count is 0. It is incremented when the message state is turned to "acquired", which is "locked" in SB parlance. Hope this clarifies.
