### ISSUE TITLE
[Feature Request] Add overload of AddAzureClientsCore that allows enabling logging

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-net#30105]
### Library name and version

Azure.Core 1.25.0

### Describe the bug

Azure.Core logs aren't printed to the console. I'm either missing a step, or this is a bug.

### Expected behavior

Azure.Core logs should be printed to the console. I expected to see the HTTP request and response bodies there. Instead, I saw no logs.

### Actual behavior

Azure.Core logs aren't printed to the console.

### Reproduction Steps

1. Create a new ASP.NET Core 6.0 Razor Pages app via the project template in VS 2022.
1. Add the following code to *Program.cs*:

    ```csharp
    builder.Services.AddAzureClientsCore();
    ```
1. In the `OnGet` method of *Index.cshtml.cs*, add Azure SDK library client code that initiates an HTTP request. Ensure the options object's `Diagnostics.IsLoggingContentEnabled` property is set to `true`. For example, using v1.1.0 of the Monitor Query library:

    ```csharp
                var client = new LogsQueryClient(
                    new DefaultAzureCredential(),
                    new LogsQueryClientOptions
                    {
                        Diagnostics = { IsLoggingContentEnabled = true }
                    });

                var startDate = DateTime.Parse("2022-07-12 00:00:00");
                var endDate = DateTime.Parse("2022-07-14 23:59:59");
                var metricType = "HeartbeatState";
                var metricNamespace = "netstandard2.0";

                var query = $"AppMetrics | where Name == '{metricType}' and Properties has '{metricNamespace}'";
                Response<LogsQueryResult> response = await client.QueryWorkspaceAsync(
                    "<log_analytics_workspace_id>", query, new QueryTimeRange(startDate, endDate));

                LogsTable table = response.Value.Table;
                Console.WriteLine(table.Rows.Count);
    ```

1. In *appsettings.Development.json*, add the following inside of `Logging:LogLevel`:

    ```json
    "Azure.Core": "Debug",
    ```

1. Run the app using the default launch profile in VS 2022.

### Environment

**VS info:**

Microsoft Visual Studio Enterprise 2022
Version 17.3.0 Preview 4.0
VisualStudio.17.Preview/17.3.0-pre.4.0+32714.290
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Enterprise

**dotnet --info output:**

.NET SDK (reflecting any global.json):ddie/app-insights-query]> do
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  C:\git\Azure\azure-sdk-for-net\global.json

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  2.1.818 [C:\Program Files\dotnet\sdk]
  3.1.421 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.400-preview.22330.6 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by JoshLove-msft** [comment]
The issue is that when using AddAzureClientsCore, you need to also start the logforwarder. I'm not sure why this was not necessary in https://github.com/bradygaster/FileNewBlazorServerToAzureContainerApps/pull/1, but I just tested it out and it works when starting the log forwarder. When using AddAzureClients, the log forwarder is started when a client gets created based on the user callback - https://github.com/Azure/azure-sdk-for-net/blob/e475cb6de873a1404008ce479e56a447b45a823d/sdk/extensions/Microsoft.Extensions.Azure/src/Internal/AzureClientFactory.cs#L21.

Usage in Program.cs:
```c#
builder.Services.AddAzureClientsCore();
using var forwarder = builder.Services.BuildServiceProvider().GetService<AzureEventSourceLogForwarder>();
forwarder.Start();
```

**Comment by scottaddie** [comment]
Adding those 2 lines to start the log forwarder does solve the problem for me. And yes, I agree we should make this fix.

**Comment by jsquire** [comment]
Seems like a good idea to me... I'm not sure why we didn't start this by default.   My best guess is that we never actually intended the method to be public and only chained by adding Azure clients.

**Comment by scottaddie** [comment]
The team discussed this issue offline. We decided to:

- Update the XML docs for the [existing `AddAzureClientsCore` extension method](https://github.com/Azure/azure-sdk-for-net/blob/2fff1bac9927c7c2ef85e28dfcc43a93be85fea1/sdk/extensions/Microsoft.Extensions.Azure/src/AzureClientServiceCollectionExtensions.cs#L33). State that log forwarding won't be started.
- Add a new `AddAzureClientsCore` method overload. The overload will accept a bool indicating whether log forwarding should be started.

**Comment by scottaddie** [comment]
@JoshLove-msft As discussed, this new overload isn't working as I'd expect. See the sample project I sent you on Teams.

**Comment by JoshLove-msft** [comment]
It looks like this may not be feasible with how the method signature is defined. The problem is that the user still needs to either inject the log forwarder or get it from the service collection in order to trigger the callback defined here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Microsoft.Extensions.Azure/src/AzureClientServiceCollectionExtensions.cs#L53

We can't create the forwarder outside of the callback, as we would have no way of getting the logger factory. We could create the logger factory ourselves if we were to add a dependency on Microsoft.Extensions.Logging, but I'm not sure if it is worth it for this feature.

**Comment by JoshLove-msft** [comment]
We can define a new overload that takes an ILoggerFactory, and then the user code would look like this:

```c#
builder.Services.AddAzureClientsCore(builder.Services.BuildServiceProvider().GetRequiredService<ILoggerFactory>());
```

Either way we should hide the newly released overload as users would still need to inject the forwarder or otherwise grab it from the service collection. It saves them the step of having to call start, but I think it would just cause more confusion.

**Comment by scottaddie** [comment]
@JoshLove-msft Please review my linked PR with the doc updates. ☝️

**Comment by KrzysztofCwalina** [comment]
We never just remove APIs. It can have very severe consequences, e.g. it can break customers even if they don't call the APIs. 
I am afraid we need to just hide it and possibly obsolete it.

**Comment by JoshLove-msft** [comment]
I think hiding it is sufficient. We've updated the docs to explain the limitations and hopefully no one will use it.

**Comment by scottaddie** [comment]
Sounds good. Thanks to both of you for your input!

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft Please review my linked PR with the doc updates. ☝️

Thanks @scottaddie - I've added a few comments. I've also submitted https://github.com/Azure/azure-sdk-for-net/issues/30728 to track the task of creating E2E tests for the extensions.
