### ISSUE TITLE
[QUERY] Does the EventProcessorClient automatically checkpoint?

### ISSUE THREAD

**Issue by minascasiou** [Azure/azure-sdk-for-net#30115]
### Library name and version

Azure Event Hubs - New EventProcessrClient  - StopProcessingAsync

### Query/Question

Hi,  would like to know if this method also updates the checkpoint status for all partitions.

**Comment by jsquire** [comment]
Hi @minascasiou.   Thank you for reaching out.   The answer to your question is no.   No checkpointing is performed automatically by the processor; in order for checkpoints to be written the application needs to call `UpdateCheckpointAsync` on the `ProcessEventArgs` instance passed to the handler.

**Comment by minascasiou-ingeniifin** [comment]
Hi & thank you for the response. 

I'm looking to add a checkpoint after a few seconds of inactivity and before exiting.
Not sure how to do this without (inefficiently) Checkpointing after every single event.
The ProcessEventArgs.UpdateCheckpointAsync() method doesn't cater for this requirement. 

Not sure whether to /unresolve as maybe this should be directed to another forum?

Thank you
Cheers, Minas

**Comment by jsquire** [comment]
There's a couple of options that I see for that scenario:

1) Cache the most recent `ProcessEventArgs` for each partition and invoke the method when idle/stopping.

2) Create an instance of the [BlobCheckpointStore](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.primitives.blobcheckpointstore) using the same `BlobContainerClient` that you're passing the processor.   Cache the most recent offset/sequence number for each partition and call [UpdateCheckpointAsync](https://docs.microsoft.com/dotnet/api/azure.messaging.eventhubs.primitives.blobcheckpointstore.updatecheckpointasync) on the store when idle/stopping.

3) Extend `EventProcessorClient`, cache the most recent offset/sequence number for each partition and call the protected [UpdateCheckpointAsync](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L794 method when idle/stopping.

4) Bypass `EventProcessorClient` and extend `PluggableCheckpointStoreEventProcessor`, which requires following the same general path as the previous idea, but in a more natural way.   _([sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample07_BatchProcessing.md))_

**Comment by minascasiou** [comment]
Excellent, thank you Jesse 
Will look into those options!

Cheers, Minas
