### ISSUE TITLE
[BUG] EventHub memory leak on EventHandlers

### ISSUE THREAD

**Issue by unaizorrilla** [Azure/azure-sdk-for-net#30119]
### Library name and version

5.7.1

### Describe the bug

Just deployed a simple EventHub EventProcessorClient into AKS to manage event hub messages and we see a contantly increase of the memory process from 75 MB up to 500 MB ( the limit of the pod ).

The code is very simple, a method to register event processor and errors and the event process it self

  ```csharp
       public async Task StartAsync(CancellationToken cancellationToken = default)
        {
            _diagnostics.HubProcessorStart();

            _eventProcessorClient.ProcessEventAsync += ProcessEvent;
            _eventProcessorClient.ProcessErrorAsync += ProcessError;

            await _eventProcessorClient.StartProcessingAsync(cancellationToken);
        }


      private async Task ProcessEvent(ProcessEventArgs arg)
        {
            if ( arg.HasEvent)
            {
              
                foreach (var item in _hubMessagesProcessor)
                {
                    await item.ProcessAsync(arg, arg.CancellationToken);
                }

                var currentProcessedMessages = _checkpointPartitions.AddOrUpdate(
                    key: arg.Partition.PartitionId,
                    addValue: 1,
                    updateValueFactory: (_, currentValue) => ++currentValue);

                if (currentProcessedMessages > _messagingOptions.EventHubNumberOfMessagesPerPartitionBeforeCheckpoint)
                {
                    await CheckpointPartition(arg);
                }
            }
        }

        private Task ProcessError(ProcessErrorEventArgs arg)
        {
            _diagnostics.HubProcessorError(arg.Operation, arg.Exception);
            return Task.CompletedTask;
        }
```

After dump the process and examine it with dotnet-dump I notice some strange elements...

- A lot of EventHandlers

00007eff89faa450    99423      6363072 System.EventHandler

The GCROOT of one of them show 

 00007EFE39023C20 System.Threading.TimerQueueTimer
            ->  00007EFE39369328 System.Threading.TimerQueueTimer
            ->  00007EFE31C51518 System.Threading.TimerQueueTimer
            ->  00007EFE331785D8 System.Threading.TimerQueueTimer
            ->  00007EFE39FD5058 System.Threading.TimerQueueTimer
            ->  00007EFE30B5FB08 System.Threading.TimerQueueTimer
            ->  00007EFE34E71EE8 System.Threading.TimerQueueTimer
            ->  00007EFE369ACAC8 System.Threading.TimerQueueTimer
            ->  00007EFE31627630 System.Threading.TimerQueueTimer
            ->  00007EFE39B36C78 System.Threading.TimerQueueTimer
            ->  00007EFE30215E80 System.Threading.TimerQueueTimer
            ->  00007EFE38CCC020 System.Threading.TimerQueueTimer
            ->  00007EFE38DDFA38 System.Threading.TimerQueueTimer
            ->  00007EFE34A1FAF0 System.Threading.TimerQueueTimer
            ->  00007EFE335F0B88 System.Threading.TimerQueueTimer
            ->  00007EFE319C0210 System.Threading.TimerQueueTimer
            ->  00007EFE3BD754E0 System.Threading.TimerQueueTimer
            ->  00007EFE365C0900 System.Threading.TimerQueueTimer
            ->  00007EFE35409D78 System.Threading.TimerQueueTimer
            ->  00007EFE34348058 System.Threading.TimerQueueTimer
            ->  00007EFE3764A728 System.Threading.TimerQueueTimer
            ->  00007EFE3328DC70 System.Threading.TimerQueueTimer
            ->  00007EFE3648CF88 System.Threading.TimerQueueTimer
            ->  00007EFE388C9710 System.Threading.TimerQueueTimer
            ->  00007EFE365E0B50 System.Threading.TimerQueueTimer
            ->  00007EFE32187D78 System.Threading.TimerQueueTimer
            ->  00007EFE3BD25A80 System.Threading.TimerQueueTimer
            ->  00007EFE3BD25A28 System.Threading.TimerCallback
            ->  00007EFE3BD25660 Azure.Messaging.EventHubs.Core.TransportProducerPool
            ->  00007EFE3BD25840 Azure.Messaging.EventHubs.Amqp.AmqpProducer
            ->  00007EFE3BD25990 Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1[[Microsoft.Azure.Amqp.SendingAmqpLink, Microsoft.Azure.Amqp]]
            ->  00007EFE3BD259E8 System.EventHandler

Also the dumpheap -stat show different instances of EventHubProducerClient on the LOH

Fragmented blocks larger than 0.5 MB:
            Addr     Size      Followed by
00007EFE3A3220F0    2.6MB         00007EFE3A5B8568 System.Tuple`2[[Microsoft.Win32.SafeHandles.SafeX509StackHandle, System.Security.Cryptography.X509Certificates],[Microsoft.Win32.SafeHandles.SafeX509StackHandle, System.Security.Cryptography.X509Certificates]]
00007EFE3A711AB8    0.6MB         00007EFE3A79F0C8 Azure.Messaging.EventHubs.Producer.EventHubProducerClient
00007EFE3A90D1A8    0.5MB         00007EFE3A98DB80 Azure.Messaging.EventHubs.Producer.EventHubProducerClient
00007EFE3AA29F00    0.8MB         00007EFE3AAF64C0 Azure.Messaging.EventHubs.Producer.EventHubProducerClient
00007EFE3AC33DD0    0.5MB         00007EFE3ACB52B8 System.SByte[]
00007EFE3AE2F428    0.6MB         00007EFE3AEC5288 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Int32, System.Private.CoreLib],[System.Net.Security.SslStream+<EnsureFullTlsFrameAsync>d__186`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security]], System.Net.Security]]
00007EFE3AEE4298    0.5MB         00007EFE3AF6B340 Azure.Messaging.EventHubs.Producer.EventHubProducerClient

And a lot of instances of some elements

00007eff89012e78    33146      2121344 System.Threading.TimerCallback
00007eff8a4ed488    33106      2383632 Azure.Messaging.EventHubs.Producer.EventHubProducerClient
00007eff87415290    99921      2398104 System.Object
00007eff8a4ef188    33106      2648480 System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[Azure.Messaging.EventHubs.Producer.PartitionPublishingOptions, Azure.Messaging.EventHubs]]
00007eff886609d8    33401      2672080 System.Uri+UriInfo
00007eff87746ca0     3989      3122148 System.Byte[]
00007eff89012d38    33309      3197664 System.Threading.TimerQueueTimer
00007eff8741b0f8    81745      3368544 System.Object[]
00007eff89fdc938    33112      3708544 Azure.Messaging.EventHubs.Amqp.AmqpClient
00007eff8a500838    33106      3972720 Azure.Messaging.EventHubs.Amqp.AmqpProducer
00007eff89f922d8    66220      4238080 Azure.Messaging.EventHubs.EventHubConnectionOptions
00007eff89fdcfc8    33112      4238336 Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope

### Expected behavior

Not leak memory

### Actual behavior

Leaking memory

### Reproduction Steps

Just use the code on the explanation

### Environment

- Hosting Plattform Azure AKS

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by unaizorrilla** [comment]
Just to add more information, obviously the class to  manage the EventProcessorClient is singleton and only one instance of the EventProcessorClient is on the dump

**Comment by jsquire** [comment]
Hi @unaizorrilla.  Thank you for reaching out and we regret that you're experiencing difficulties.   In order to help, I'm going to need to understand a bit more about the end-to-end scenario.   For example, the types you're listing from your dump would seem to correlate to an `EventHubProducerClient` being used to send directly to ~28 partitions and managing the pool of transport types needed to do so.   The code snippet doesn't illustrate anything use of a producer, so there would seem to be relevant context missing from elsewhere in the application and/or handlers.

Is it possible for you to share a small self-contained reproduction of the behavior that you're seeing?   Barring that, seeing the source for the application would be helpful.   

It would also be helpful to understand some basics for the environment:

- What tier is the associated Event Hubs namespace?
- How many partitions does the Event Hub have?
- How many processors are running in the consumer group?
- What kind of activity is being observed by the Error, PartitionInitializing, and PartitionStopping handlers?

**Comment by unaizorrilla** [comment]
Hi @jsquire 

I just curious about the same, why EventHubProducerClient is here, the message is note related with that class (obviously ) 

   ```csharp
internal class OnvifEvent
    {
        [JsonPropertyName("mac")]
        public string Mac { get; set; }
        [JsonPropertyName("hw_id")]
        public string HwId { get; set; }
        [JsonPropertyName("timestamp")]
        public string Timestamp { get; set; }
        [JsonPropertyName("message_type")]
        public string MessageType { get; set; }
        [JsonPropertyName("event_type")]
        public EventType EventType { get; set; }
    }

    internal class EventType
    {
        [JsonPropertyName("motion")]
        public int Motion { get; set; }
        [JsonPropertyName("noise")]
        public int Noise { get; set; }
        [JsonPropertyName("pir")]
        public int PIR { get; set; } // Passive Infrared sensors
    }
```


After some investigation I think the issue (leak) is on a Service HealthCheck for EventHub.. but let me finish my investigation, is is related with that i close the issue... 

Thanks @jsquire  for help here!

**Comment by unaizorrilla** [comment]
Hi!

Closed because the leak is not on the EventHub library, after some investigation, the leak are on the EventHub healtchck and  because a transient creation of EventHubProducerClient... I fixed that with this PR 

https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/pull/1361
