### ISSUE TITLE
Investigate failure cases with swapping LRO args

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#30130]
@christothes I changed the implementation of the test to pass WaitUntil.Started, and then call WaitForCompletion separately. Otherwise InstrumentResultInterceptor would swap out Completed for Started and then after invoking the method would call WaitForCompletion (as per the changes in this PR), but we would then hit a failure in the Diagnostic Scope validation because the scope would not be marked as failed. This points to a more general issue where this swapping mechanism doesn't play nice with tests that expect a failure. Since this was the only such test, and it is not actually even a live test, I figured it was probably fine to just change the test rather than trying to figure out a way to support the test in its original implementation.

_Originally posted by @JoshLove-msft in https://github.com/Azure/azure-sdk-for-net/pull/30112#discussion_r930279309_

**Comment by pallavit** [comment]
@JoshLove-msft could you please provide more details on what this issue is tracking?

**Comment by JoshLove-msft** [comment]
In order to avoid polling delays when in playback mode, the Test Framework will swap out any WaitUntil.Completed arguments used in a test with separate calls passing WaitUntil.Started and then WaitUntil.Completed. This works fine for most tests, but for tests that expect an exception, this strategy doesn't work. This issue is tracking this known issue and can be resolved once we figure out how to make this work for tests expecting an exception, or if we decide that this will not be supported.

**Comment by pallavit** [comment]
> This works fine for most tests, but for tests that expect an exception, this strategy doesn't work. This issue is tracking this known issue and can be resolved once we figure out how to make this work for tests expecting an exception, or if we decide that this will not be supported.

Does this mean the tests that test for exception fail today? If not, how do they work today? And if they continue to work does this need to be supported for those scenarios?

**Comment by JoshLove-msft** [comment]
> Does this mean the tests that test for exception fail today? If not, how do they work today? And if they continue to work does this need to be supported for those scenarios?

There are no tests that would expect exceptions today because they would not work. This is essentially a feature request to allow writing tests like https://github.com/Azure/azure-sdk-for-net/pull/30112/files#diff-d142cee4ce83a2f7a9fc80171c3062bba5d9f3e45fd8dc0910a1640d43ddb434L59 that could run in playback mode without causing large delays due to the polling.
