### ISSUE TITLE
[QUERY] How to get TenantId property from TokenCredential

### ISSUE THREAD

**Issue by Danieladu** [Azure/azure-sdk-for-net#30144]
### Library name and version

Azure.Identity

### Query/Question

Originally ,we use [Microsoft.Azure.Services.AppAuthentication](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication) to get the accesstoken and then use the token to build AzureCredentials (from : Microsoft.Azure.Management.ResourceManager.Fluent.Authentication)

The question is, Originally, we could get tenant Id from azureServiceTokenProvider.PrincipalUsed.TenantId, How could we get this value from Azure.Identity? (the Credential is DefaultAzureCredential)

Thanks!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Danieladu** [comment]
Close it. Finally we find that we should deprecate the "AzureCredentials" in namespace "Microsoft.Azure.Management.ResourceManager.Fluent.Authentication", which is used to passed to "RedisManager".
Now, we replace it with passing "TokenCredential" directly with [Azure.ResourceManager.Redis](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/redis/Azure.ResourceManager.Redis)

Close it. Thanks all.
