### ISSUE TITLE
Page should specify that this is the same as the Content-MD5 field described in the docs

### ISSUE THREAD

**Issue by atif1996** [Azure/azure-sdk-for-net#30141]
This field is called Content-MD5 in much of the api documentation and its not clear until you use the API that this function gets you that Content-MD5.  Mention on the Content-MD5 on this page may make it easier for users to find this function.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 37926450-0532-1f12-3483-9b8b76e34c64
* Version Independent ID: 6e4fc166-2106-a0cf-b7bd-35da0773974a
* Content: [BlobItemProperties.ContentHash Property (Azure.Storage.Blobs.Models) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobitemproperties.contenthash?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Models/BlobItemProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Models/BlobItemProperties.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@atif1996 I see Content-MD5 is mentioned on this page.
![image](https://user-images.githubusercontent.com/38112130/181374571-2fcb721f-b066-4d2c-9e86-26aceeb74db4.png)
