### ISSUE TITLE
[BUG] Azure Identity not able to connect to Key Vault using System Managed identity of Virtual machine Scale set

### ISSUE THREAD

**Issue by guruvonline** [Azure/azure-sdk-for-net#30162]
### Library name and version

Azure.Identity 1.2.0

### Describe the bug

We have been using the Azure.identity to use Managed identity to connect to key vault. but after upgrading the storage library , the Azure.identity is not able to connect to Key vault and fails with attached exception. (same version of package was working earlier but now it has stopped working)

```
Azure.Identity.AuthenticationFailedException: DefaultAzureCredential failed to retrieve a token from the included credentials.
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
- ManagedIdentityCredential authentication failed: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry.
- SharedTokenCacheCredential authentication unavailable. No accounts were found in the cache.
- Visual Studio Token provider can't be accessed at C:\Windows\system32\config\systemprofile\AppData\Local\.IdentityService\AzureServiceAuth\tokenprovider.json
- VisualStudioCodeCredential authentication failed: CredRead has failed but error is unknown.
- Azure CLI not installed
   at Azure.Identity.DefaultAzureCredential.<GetTokenFromSourcesAsync>d__14.MoveNext()

```
troubleshooting tried
•	From VM we can get MI token using the Powershell command
•	Other Apps running on the same Service fabric cluster and VMs can connect to Key Vault.
•	Tried adding logging as mentioned in [doc,](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fblob%2FAzure.Identity_1.6.0%2Fsdk%2Fidentity%2FAzure.Identity%2FTROUBLESHOOTING.md%23enabling-and-configuring-logging&data=05%7C01%7Cabhis%40microsoft.com%7C3e944017008341660dac08da6fed406f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637945362021357284%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7xR%2F3G1HoCxzWcnlY9cQn8P7%2Bam7sCJnXfGPSFLsqfw%3D&reserved=0) but nothing is getting logged and none of the exception messages mentioned in doc matches with what we are getting.

### Expected behavior

System assigned managed identity should work.

### Actual behavior

getting attached exception

### Reproduction Steps

```
var credential = new DefaultAzureCredential(options);
var client = new SecretClient(new Uri(configuration.Endpoint), credential);

var secret = await client.GetSecretAsync(key);

```

### Environment

Azure Service Fabric, VMSS VM

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
The version of Azure.Identity you mentioned is quite a few versions old. Are you able to try with the latest version?

**Comment by ryan-adler** [comment]
@christothes  Please reopen this - it seems that this is still an issue.  We are having this when running build agents on the latest version of the Microsoft runner-images scripted image.
