### ISSUE TITLE
[FEATURE REQ] Implement tracing in ServiceBus WebJobs Extension for batch processing

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#30161]
### Library name

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Please describe the feature.

There is [nothing in the extension](https://github.com/azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs) that traces servicebus batch receive .

We don't need it in EventHubs extension because EventHubs processor does it [here in SDK](https://github.com/azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L590)

And here's  how it's done for EventGrid in [WebJobs extension](https://github.com/azure/azure-sdk-for-net/blob/main/sdk/eventgrid/Microsoft.Azure.WebJobs.Extensions.EventGrid/src/EventGridExtensionConfigProvider.cs#L187)

**Comment by JoshLove-msft** [comment]
We have a scope for the received messages here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs#L308-L334

Would you suggest that we reuse the same activity that we use for the processor case, which only applies for single message functions? https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs#L93-L96

**Comment by lmolkova** [comment]
Receive scope ends as soon as messages are received and does not allow correlating received messages to function execution. I suggest we create a new Activity similarly to EventGrid extension - it starts after messages are received, ends after they are settled and has links that point to received messages.

**Comment by JoshLove-msft** [comment]
> Receive scope ends as soon as messages are received and does not allow correlating received messages to function execution. I suggest we create a new Activity similarly to EventGrid extension - it starts after messages are received, ends after they are settled and has links that point to received messages.

This is what we do in the Processor already. Should we use the same scope name?

**Comment by lmolkova** [comment]
> This is what we do in the Processor already. Should we use the same scope name?

Yes, but only for single dispatch, for batch dispatch we'd need to wrap 

https://github.com/Azure/azure-sdk-for-net/blob/832e54ecdcd8cebcdd2f273396374ba8b7dac87f/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs#L415

  into a new scope, we'd need another `DiagnosticScopeFactory` - in EventGrid I used same name as SDK uses. For ServiceBus I'd use `Azure.Messaging.ServiceBus` namespace and `ServiceBusProcessor.ProcessMessages` or `ServiceBusProcessor.ProcessBatch` scope name.

Also, there are few other things to take care of - https://gist.github.com/lmolkova/e4215c0f44a49ef824983382762e6b92#processing-messages

**Comment by JoshLove-msft** [comment]
> > This is what we do in the Processor already. Should we use the same scope name?
> 
> Yes, but only for single dispatch, for batch dispatch we'd need to wrap

Understood - my question was around whether we should reuse the same name for the processing span, which you have answered 😄 
Thank you!
