### ISSUE TITLE
List methods exposed from Fluent API are not fully LAZY and do call the first page during initialization.

### ISSUE THREAD

**Issue by hovsepm** [Azure/azure-sdk-for-net#3017]
Instead we can think about ways to have fully LAZY collection that will do first page call only when caller will start iteration over the collection. 

From internal discussion: 
One of the design goal of foreach specifically handle this case i.e. iterating a source where data is not immediately available. Think about doing foreach on IEnumerable/IQuerable returned by SQL SELECT query, user knows that data can possibly reach page by page from SQL server and foreach iteration may block. And in this case query executes only when user iterate through the list or apply any LINQ operator that need data (e.g. First())

Between there is async enumerable in C# https://github.com/Reactive-Extensions/Rx.NET/tree/develop/Ix.NET . We should consider this after GA.

**Comment by martinsawicki** [comment]
not sure there is still something noteworthy to improve here after the work we did a while back, so parking for now..

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#60
