### ISSUE TITLE
SDK for management of log analytics workspaces

### ISSUE THREAD

**Issue by gskyu** [Azure/azure-sdk-for-net#30183]
Hi, 

I cannot seem to find the right SDK to manage my log analytics worspaces using dotnet 6 and the latest azure identity sdk (Azure.Core.Identity). 

I found an sdk named Azure.ResourceManager.Insights exposing a client allowing to retrieve information about a log analytics workspace. However, a comment on [this issue](https://github.com/Azure/azure-sdk-for-net/issues/26254) indicates this sdk is going to be deprecated. Another comment on the same issue says it is going to be replaced by the sdk named Azure.ResourceManager.Monitor but I can't find any method or client in this sdk allowing me to at least retrieve data about log analytics worspace resources.

Any information on this matter would be welcome.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@ArcturusZhang please help to check if the new Azure.ResourceManager.Monitor is good for this

**Comment by gskyu** [comment]
@ArcturusZhang
