### ISSUE TITLE
Azure Blob Service Library - ListBlob with Filter

### ISSUE THREAD

**Issue by Dan127001** [Azure/azure-sdk-for-net#30184]
Thanks for the reply, however I cannot see the ListBlobs Method.

This method is not available within the new Azure.Storage.Blobs Package.
(https://github.com/Azure/azure-sdk-for-net/tree/Azure.Storage.Blobs_12.13.0/sdk/storage/Azure.Storage.Blobs)

The ListBlobs method you are referring to is from the depricated Microsoft.Azure.Storage.Blob Package.
(https://github.com/Azure/azure-storage-net)

Am I missing something here?

_Originally posted by @Dan127001 in https://github.com/Azure/azure-sdk-for-net/issues/29961#issuecomment-1194123153_

**Comment by navba-MSFT** [comment]
@Dan127001 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Dan127001 Since your requirement is to get the delta (blobs that changed by other PCs) since last check, Did you explore the  **changefeed feature** of Azure Blob Storage ? Change feed provides transaction logs of all the changes that occur to the blobs and the blob metadata in your storage account. [This](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-change-feed-how-to) article shows you how to read change feed records by using the .NET blob change feed processor library.

More Info [here](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage.blobs.changefeed-readme-pre).

**Comment by Dan127001** [comment]
This looks like the thing we need! Also with a cursor functionality - very nice.

However, I see it is still in preview.
Is there a timeline on the first release / stable version?

**Comment by navba-MSFT** [comment]
@Dan127001 The feature itself is GA. I am checking internally on the Azure.Storage.Blobs.ChangeFeed library's stable version release.  I will keep you posted.

**Comment by navba-MSFT** [comment]
@Dan127001 I have heard back from the Product Owners. They have informed that they do not have a timeline for the Change Feed library GA.  We will consider creating this timeline if there is sufficient customer demand. Hope this answers.

**Comment by Dan127001** [comment]
/unresolve

I now took a look at the library. It seems like the ChangeFeed is only available for the whole storage and not on container level.

Is it possible to get a ChangeFeed (cursor or filter by date) on container level?

**Comment by navba-MSFT** [comment]
@Dan127001 You are right. This is available only at the account level and not at the container level. 

Change event records use the [Apache Avro 1.8.2](https://avro.apache.org/docs/1.8.2/spec.html)  format so the log file has the .avro file extension. 
Your client applications can consume the change feed by using the blob change feed processor library that is provided with the change feed processor SDK. See [Process change feed logs in Azure Blob Storage](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-change-feed-how-to).

So if you are concerned about a particular container only you need to write that logic within your application to fikter those events only and fetch the required details. Here's an example of a log file and you can see the **apitestcontainerver** container data:

{
     "schemaVersion": 1,
     "topic": "/subscriptions/XXXXXXXXXXXX/resourceGroups/sadodd/providers/Microsoft.Storage/storageAccounts/SADODD-DEV-09",
     "subject": "/blobServices/default/containers/**apitestcontainerver**/blobs/F_0003",
     "eventType": "BlobCreated",
     "eventTime": "2022-08-11T18:12:01.079Z",
     "id": "55e5531f-8006-0000-00da-ca3467000000",
     "data": {
         "api": "PutBlob",
         "clientRequestId": "edf598f4-e501-4750-a3ba-9752bb22df39",
         "requestId": "00000000-0000-0000-0000-000000000000",
         "etag": "0x8D698F13DCB47F6",
         "contentType": "application/octet-stream",
         "contentLength": 128,
         "blobType": "BlockBlob",
         "url": "",
         "sequencer": "000000000000000100000000000000060000000000006d8a",
         "storageDiagnostics": {
             "bid": "11cda41c-13d8-49c9-b7b6-bc55c41b3e75",
             "seq": "(6,5614,28042,28038)",
             "sid": "591651bd-8eb3-c864-1001-fcd187be3efd"
         }
  }
}

Hope this answers.

**Comment by Dan127001** [comment]
/unresolve

Thanks for your answer.

I thought about writing server-side code to filter the ChangeLog before giving it to a client. However, this would result in heavy load on our backend, which we want to avoid.
Also, the transmission and RAM of our Backend would spike -> every time a client requests the changelog the backend goes through all clients changes since cursor X and then after filtering all of this, transmits the filtered results to the client.

Filtering on the client end would be unsecure, since the client would then have access to all the changelogs of different containers (in our case container other account’s data).

Our goal is to handle the access to containers within a blob storage in our backend (with an authenticated user) and then handle the following tasks regarding delta checks and downloads between the client and storage, without blocking / using many resources at our backend.

Those are my thoughts on why filtering is not a valid option for us.
I hope you understand where we are coming from and why we want to achieve this.

**Comment by navba-MSFT** [comment]
@Dan127001 Thanks for getting back. We hear you and understand your concern. I had reached out to the Product Owners too to get their pointers. Unfortunately, there is currently no option to filter the changefeed to a specific container. The changefeed for the entire storage account is stored in a specific container `$blobchangefeed
 `in the storage account.  To process the changefeed, the SDK has to download the changefeed for the entire storage account for a specific time period.

The only way I see for your scenario to filter the changefeed by a container would be to implement a filter on top of the SDK in their code. Hope this answers.
