### ISSUE TITLE
[FEATURE REQ] Expose Identity Client and Identity Url Option

### ISSUE THREAD

**Issue by deer-prudence** [Azure/azure-sdk-for-net#30192]
### Library name

Azure.Security.ConfidentialLedger

### Please describe the feature.

I noticed that the .NET data plane SDK does not expose the ledger identity endpoint to the user. Could we expose this endpoint in the next release? Also, could we offer the user a `ConfidentialLedgerIdentityServiceClient` that allows them to define the ledger identity endpoint? Thank you!

Update (3 August, 2022): Additionally, it looks like in the move to 1.0.0, the `PostLedgerEntryOperation` response model was removed. This is the response model we use to retrieve the transaction id after a call to `ledgerClient.CreateLedgerEntryAsync()`. It is extremely useful! Would it be possible to add it back in? As Lyndon pointed out to me, the documentation does [reference](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/confidentialledger/Azure.Security.ConfidentialLedger#ledger-entries) it. Thanks again.

**Comment by jsquire** [comment]
//cc: @christothes, @KrzysztofCwalina, @tg-msft

**Comment by christothes** [comment]
> Update (3 August, 2022): Additionally, it looks like in the move to 1.0.0, the `PostLedgerEntryOperation` response model was removed. This is the response model we use to retrieve the transaction id after a call to `ledgerClient.CreateLedgerEntryAsync()`. It is extremely useful! Would it be possible to add it back in? As Lyndon pointed out to me, the documentation does [reference](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/confidentialledger/Azure.Security.ConfidentialLedger#ledger-entries) it. Thanks again.

This was intentional. The TransactionId is still available in the header of the RawResponse of the Operation. The reason the more specific operation type was removed was to confirm to the DPG operation pattern.

**Comment by christothes** [comment]
implemented in #30399
