### ISSUE TITLE
Search SDK: Can't add Microsoft. Azure. Search

### ISSUE THREAD

**Issue by deonvisser** [Azure/azure-sdk-for-net#3019]
I have a Xamarin Project running VS 2017 Community. Packages install goes through all the motions and then just stops and exits. No error messages. Just does not install.

Azure.Storage installs fine.

**Comment by brjohnstmsft** [comment]
Possibly related: https://github.com/Azure/azure-sdk-for-net/issues/2732 https://github.com/OData/odata.net/issues/751

@deonvisser There's a bunch of work going on right now to make the Azure .NET SDKs play nice with VS2017. I don't have an ETA for the Search SDK yet, but we are working on it.

**Comment by alataffective** [comment]
When trying to add Microsoft.Azure.Search 3.0.3 to a .NET Standard 1.1 (or any other version) class library I get:

Package Microsoft.Spatial 6.15.0 is not compatible with netstandard1.1 (.NETStandard,Version=v1.1). Package Microsoft.Spatial 6.15.0 supports:
  - dnx451 (DNX,Version=v4.5.1)
  - dnxcore50 (DNXCore,Version=v5.0)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)

Is this the right place to mention this or should I raise a different issue?

**Comment by brjohnstmsft** [comment]
@alataffective Yes, this is the right place. We have netstandard1.1 versions of the GA and preview Search SDKs in the works right now. They should be released in the next few days. I'll update this issue when that happens.

**Comment by tutike2000** [comment]
Yeah, simmilar error:

```
Installing Microsoft.Azure.Search 4.0.0-preview.
Package Microsoft.Spatial 6.15.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Spatial 6.15.0 supports:
  - dnx451 (DNX,Version=v4.5.1)
  - dnxcore50 (DNXCore,Version=v5.0)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
  - portable-net45+win8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile111)
```

**Comment by brjohnstmsft** [comment]
This is now fixed. You can grab the latest NuGet packages here:

- GA SDK: https://www.nuget.org/packages/Microsoft.Azure.Search/3.0.4
- Preview SDK: https://www.nuget.org/packages/Microsoft.Azure.Search/4.0.1-preview
