### ISSUE TITLE
[Form Recognizer] TrainingOps(False,False) failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#30208]
Form Recognizer nightly test runs are failing with:

> Error message
> Expected: Succeeded
> But was:  Failed
> 
> 
> Stack trace
>    at Azure.AI.FormRecognizer.Tests.FormTrainingClientLiveTests.TrainingOps(Boolean labeled, Boolean useTokenCredential) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormTrainingClient/FormTrainingClientLiveTests.cs:line 352
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1743865&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
After investigating, this is the assertion that failed:
```cs
Assert.AreEqual(TrainingStatus.Succeeded, rm.Status);
```

One of the provided forms failed in the model training step, but others succeeded. We haven't seen this error before, and it happened only once in the last nightly run. This makes me think that it's a transient error, so I'll close this issue.

We can reopen it if we see it again in the next couple of days.
