### ISSUE TITLE
Test Runner dump collection failing on netcoreapp3.1

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#30207]
Containe Rregistry nightly test runs are failing with:

> Data collector 'Blame' message: Could not start process dump: System.PlatformNotSupportedException: Unsupported operating system: Linux 5.15.0-1014-azure #17~20.04.1-Ubuntu SMP Thu Jun 23 20:01:51 UTC 2022, and framework: .NETCoreApp,Version=v3.1.
>    at Microsoft.TestPlatform.Extensions.BlameDataCollector.CrashDumperFactory.Create(String targetFramework)
>    at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcessDumpUtility.CrashDump(Int32 processId, String tempDirectory, DumpTypeOption dumpType, String targetFramework, Boolean collectAlways)
>    at Microsoft.TestPlatform.Extensions.BlameDataCollector.ProcessDumpUtility.StartTriggerBasedProcessDump(Int32 processId, String testResultsDirectory, Boolean isFullDump, String targetFramework, Boolean collectAlways)
>    at Microsoft.TestPlatform.Extensions.BlameDataCollector.BlameCollector.TestHostLaunchedHandler(Object sender, TestHostLaunchedEventArgs args).
> Data collector 'Blame' message: All tests finished running, Sequence file will not be generated.
>   Passed SetImagePropertiesAsync [10 s]
> Results File: /mnt/vss/_work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/TestResults/_94d97172c00001J_2022-07-28_18_38_27.trx

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1742767&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
@JoshLove-msft :  This looks like the runner crashed on `netcoreapp3.1` and the commands to capture a dump aren't supported.   Should we consider unhooking it for < `net6`?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft : This looks like the runner crashed on `netcoreapp3.1` and the commands to capture a dump aren't supported. Should we consider unhooking it for < `net6`?

We could, or we could just ignore this error as it is not actually failing the build.

**Comment by jsquire** [comment]
> We could, or we could just ignore this error as it is not actually failing the build.

No objections to that either.   I'll defer to your judgement.

**Comment by JoshLove-msft** [comment]
Closing as this is not impacting the build. We can reconsider if this causes confusion.
