### ISSUE TITLE
Long running operations should return Location status code if available

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-sdk-for-net#3020]
If a long-running operation returns Azure-AsyncOperation header, then it is preferentially polled instead of Location header (https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure/AzureClientExtensions.cs#L111).

When the operation succeeds, if Azure-AsyncOperation was polled then the resource is retrieved in order to populate the response body (https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ClientRuntime/Microsoft.Rest.ClientRuntime.Azure/AzureClientExtensions.cs#L132)

Here's the problem: if the operation was a PUT and the resource was created, then the response code for the long-running operation should be Created. However because the *resource* is retrieved at the end (which should return OK) the operation will ultimately return OK response code - which is incorrect, it should be Created.

This is problematic for our e2e tests because we want to test whether the PUT api returned Created (for creates) vs OK (for updates), but GetLongRunningOperationResultAsync only ever returns OK.

If Azure-AsyncOperation was polled and the operation succeeded then the Location header should be retrieved (if possible) in order to get the correct response code.

**Comment by jaredmoo** [comment]
There is a similar problem for delete requests. When Azure-AsyncOperation completes, I want to differentiate between OK (deleted) and NoContent (resource didn't exist), which can only be determined by getting Location.

**Comment by sphibbs** [comment]
This is part of planned changes to our overall async pattern. Currently looking at mid summer.

**Comment by shahabhijeet** [comment]
@jaredmoo this was fixed starting ClientRuntime.Azure version 3.3.12.
Please open a new issue if your issue has not be solved yet.
