### ISSUE TITLE
Typo in overview title

### ISSUE THREAD

**Issue by w-azure** [Azure/azure-sdk-for-net#30227]
[Enter feedback here]
I just noticed this in the Bing search engine. A space should be added between "Azure IoT Hub" and "is". Otherwise it reads "Azure IoT Hubis".

![typo](https://user-images.githubusercontent.com/103003808/181866975-4ab9ac92-6752-4d49-9b39-3f0d471e9d7d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3e1ca1e2-e65a-121e-efc7-d3c7209e54d5
* Version Independent ID: b75c32e7-42c2-0ea2-3f37-851976095ae2
* Content: [Azure IoT libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/iot)
* Content Source: [api/overview/azure/iot.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/iot.md)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @w-azure.  Thank you for your feedback.   This appears to either have already been corrected or an error in Bing's rendering.   The [source](https://raw.githubusercontent.com/Azure/azure-docs-sdk-dotnet/master/api/overview/azure/iot.md) for that page contains the proper spacing.
