### ISSUE TITLE
[BUG] Typo for the error code "IncrementalCopyOfEarlierVersionSnapshotNotAllowed"

### ISSUE THREAD

**Issue by DarknessChen** [Azure/azure-sdk-for-net#30229]
### Library name and version

Azure.Storage.Blobs

### Describe the bug

**Describe the bug**
I think the error code "IncrementalCopyOf**Eralier**VersionSnapshotNotAllowed" here has a typo right? It should be "IncrementalCopyOf**Earlier**VersionSnapshotNotAllowed".

https://github.com/Azure/azure-sdk-for-net/blob/dd888a2ba93810b191d160c846f237ec5b70af57/sdk/storage/Azure.Storage.Blobs/src/Generated/Models/BlobErrorCode.cs#L87
If the user uses it to parse the error code, they will never get it if the server sends a correctly spelled error.

- **Package Name**:  Azure Blob Storage

### Expected behavior

Correct spelling.

Does even the server-side implement it wrongly?

### Actual behavior

Typo

### Reproduction Steps

Use the error code to parse.

**Comment by SaurabhSharma-MSFT** [comment]
@DarknessChen We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@DarknessChen It looks like issue at the service end as well.  I have submitted a PR for the fix.

**Comment by SaurabhSharma-MSFT** [comment]
@DarknessChen The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
