### ISSUE TITLE
Missing documentation for GetTokenAsync method using tenantId

### ISSUE THREAD

**Issue by azerios** [Azure/azure-sdk-for-net#30231]
Dear,

I'm currently trying to replace the use of Microsoft.Azure.Services.AppAuthentication and replacing it by Azure.Identity inside my application.

As I'm new in Azure world, I'm wondering what are all requirements to get the token of an SQL database.

I don't know if using the method
var accessToken = await new DefaultAzureCredential().GetTokenAsync(
new TokenRequestContext(new[] { {"https://database.windows.net/"}, tenantId: _tenantId) { }
            ).ConfigureAwait(false);
use the AzureAD tenantId or the SQL Server details itself.

My point is that I can't find any documentation to know how to configure an environment to be able to use this method correctly.

Is it possible to share any link(s) available or create this missing documentation ?

Regards

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f73df56-2312-5851-7b59-3dfb766e5f66
* Version Independent ID: 31be349e-063e-6696-bc5f-752c413fa079
* Content: [Azure Identity client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme)
* Content Source: [api/overview/azure/identity-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/identity-readme.md)
* Service: **identity**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @schaabs
* Microsoft Alias: **sschaab**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @azerios 
SQLClient supports [DefaultAzureCredential directly](https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16#using-active-directory-default-authentication). Does this address your scenario?
