### ISSUE TITLE
[BUG] Custom Models Requires GUID to call StartRecognizeCustomFormsFromUriAsync

### ISSUE THREAD

**Issue by paragongithub** [Azure/azure-sdk-for-net#30238]
### Library name and version

Azure.AI.FormRecognizer version 4.0.x

### Describe the bug

When calling `client.StartRecognizeCustomFormsFromUriAsync`  I am getting an error returned advising that ModelID should be a Guid.  I am unable to track down the GUID via the Azure Portal.   

If however you call the REST endpoint, `https://xxxxxformrecogniserinstance.cognitiveservices.azure.com/formrecognizer/documentModels/**tmwOcrModel**:analyze?api-version=2022-06-30-preview`

We are able to pass through the Model ID as a string.

Additionally if you use a predefined form, you can pass through the modelID as as string.

`client.StartAnalyzeDocumentFromUriAsync("prebuilt-document", fileUri);`

### Expected behavior

Ability to call StartRecognizeCustomFormsFromUriAsync by passing through the ModelID as a string rather than a GUID

### Actual behavior

Error thrown  System.ArgumentException: 'The modelId must be a valid GUID. Arg_ParamName_Name'

### Reproduction Steps

Create Console Application

Install the Nuguet package.

```csharp
using Azure;
using Azure.AI.FormRecognizer.DocumentAnalysis;
using Azure.AI.FormRecognizer;
using Azure.AI.FormRecognizer.Models;

string endpoint = "https://xxxx.cognitiveservices.azure.com/";
string apiKey = "xxxx";
var credential = new AzureKeyCredential(apiKey);
DocumentAnalysisClient client = new DocumentAnalysisClient(new Uri(endpoint), credential);

string modelId = "tmwOcrModel";

Uri formUri = new Uri("https://xxxxx.blob.core.windows.net/tmw2807blob/20220721_094536.jpg");
var options = new RecognizeCustomFormsOptions() { IncludeFieldElements = true };

var client2 = new FormRecognizerClient(new Uri(endpoint), credential);

RecognizeCustomFormsOperation operation = await client2.StartRecognizeCustomFormsFromUriAsync(modelId, formUri, options);`
```

### Environment

Azure West Europe

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @paragongithub,

The client you're trying to use, `FormRecognizerClient`, only supports old versions of the Form Recognizer service and, therefore, can only accept GUIDs as model IDs. If you use the `DocumentAnalysisClient` you showed in your snippet, it should work as expected:

```cs
using Azure;
using Azure.AI.FormRecognizer.DocumentAnalysis;

string endpoint = "https://xxxx.cognitiveservices.azure.com/";
string apiKey = "xxxx";
var credential = new AzureKeyCredential(apiKey);
DocumentAnalysisClient client = new DocumentAnalysisClient(new Uri(endpoint), credential);

string modelId = "tmwOcrModel";
Uri formUri = new Uri("https://xxxxx.blob.core.windows.net/tmw2807blob/20220721_094536.jpg");

AnalyzeDocumentOperation operation = await client.StartAnalyzeDocumentFromUriAsync(modelId, formUri);
```

Please let me know if that solves your problem.

**Comment by paragongithub** [comment]
Thank you for your response, I can confirm that works.
