### ISSUE TITLE
[QUERY] Azure.ResourceManager.KeyVault - Removed methods , GetSecrets, GetVaultKeys

### ISSUE THREAD

**Issue by gui28347** [Azure/azure-sdk-for-net#30246]
### Library name and version

Azure.ResourceManager.KeyVault 1.0.0

### Query/Question

After migrating from Azure.ResourceManager.KeyVault (1.0.0-beta8) to Azure.ResourceManager.KeyVault (1.0.0) I see a bunch of renames (no problem, easy to fix) and as well some methods were removed, like : 

vault.Value.**GetVaultKeys**().CreateOrUpdate(WaitUntil.Completed, "XXX", new VaultKeyCreateOrUpdateContent(new KeyProperties() { KeySize = 2048, CurveName = JsonWebKeyCurveName.P256, Kty = JsonWebKeyType.RSA }));

vault.**GetSecrets**().CreateOrUpdate(WaitUntil.Started, $"XXX", new SecretCreateOrUpdateContent(new SecretProperties() { Value = "ZZZ" }) { });

I tried search for renamed methods, but looks like these ones are really removed. 

My question is, if they are renamed what are new names, if they were removed what is replacement for them ?

The other possibility I see is migrating from Azure.Resource.Keyvault from regular KeyVault library(Azure.Security.KeyVault.Secrets), the issue is that regular keyvault has issue when KeyVault has IP Restrictions in place it prevent the api calls to work, while in Azure.Resource.Keyvault it still just works fine.

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.1.818 [C:\Program Files\dotnet\sdk]
  3.1.421 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@gui28347 you can find changelogs of keyvault here https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.ResourceManager.KeyVault/CHANGELOG.md

**Comment by gui28347** [comment]
keyvault.Value.**GetVaultKeys().**CreateOrUpdate is part of  (From Change Logs -> Type **KeyVaultResourceData** was removed.) ?

If so it means that using Azure.ResourceManager.Keyvault you can't manage secrets anymore? What is your recommendation?

**Comment by xboxeer** [comment]
> 

You can check this sample of how to use ResourceManager to manage keyvault, https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.ResourceManager.KeyVault/samples/Sample1_ManagingKeyVaults.md

`Secrets` are defined in `KeyVaultAccessPolicy.Permission`

**Comment by xboxeer** [comment]
@gui28347 this part of feature has been moved to Azure data plane SDK, for keyvault, they are now in the package of `Azure.Security.KeyVault.Keys`, and `Azure.Security.KeyVault.Secrets`
You can find samples of how to use these 2 libraries here: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/keyvault/samples

**Comment by gui28347** [comment]
I already migrated to new library, just was trying to understand the reason the removal. Thanks
