### ISSUE TITLE
[BUG] Managed Disk SetTag broken in latest stable version of Azure.ResourceManager.Compute

### ISSUE THREAD

**Issue by gui28347** [Azure/azure-sdk-for-net#30245]
### Library name and version

Azure.ResourceManager.Compute 1.0.0

### Describe the bug

After upgrading from latest beta version to stable version, the ManagedDisk SetTag method is broken.

### Expected behavior

SetTags method work as before.

### Actual behavior

SetTags returning an exception and don't apply any tag in resource

### Reproduction Steps

Run this code using the latest beta version (it will work) and run the same piece of code using the latest stable version it will fail.
var osDisk = resourceGroup.GetManagedDisk($"MyTest");
IDictionary<string, string> iDictionary = new Dictionary<string, string>();
iDictionary.Add("mytag","tag1");
osDisk.Value.SetTags(iDictionary);

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.1.818 [C:\Program Files\dotnet\sdk]
  3.1.421 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by gui28347** [comment]
Calling rest api directly without using nuget, works as workaround. Previous version of nuget also works. The issue is just stable version 1.0.0

**More details about exception:** 

EXP: Azure.RequestFailedException: Service request failed.
Status: 202 (Accepted)

Headers:
Cache-Control: no-cache
Pragma: no-cache
Location: REDACTED
x-ms-ratelimit-remaining-subscription-deletes: REDACTED
x-ms-request-id: 5f06febc-2709-4ddc-b5f0-053bb5f69290
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Sun, 31 Jul 2022 01:34:07 GMT
Expires: -1
Content-Length: 0

   at Azure.ResourceManager.Resources.TagsRestOperations.DeleteAtScope(String scope, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.TagResource.Delete(WaitUntil waitUntil, CancellationToken cancellationToken)
   at Azure.ResourceManager.Compute.ManagedDiskResource.SetTags(IDictionary`2 tags, CancellationToken cancellationToken)

**Comment by xboxeer** [comment]
I tried on my side the beta.9 version seeing the same issue, do you mind sharing your managed disk creation template so that i can make sure we operating on the same kind resource

**Comment by gui28347** [comment]
vmconfig.StorageProfile = new VirtualMachineStorageProfile
                {
                    OSDisk = new VirtualMachineOSDisk(DiskCreateOptionType.FromImage)
                    {
                        Name = $"{machine}-{instance}-OsDisk",
                        Caching = CachingType.ReadWrite,
                        OSType = SupportedOperatingSystemType.Windows,
                        ManagedDisk = new VirtualMachineManagedDisk { StorageAccountType = StorageAccountType.StandardLrs }
                    },
                    ImageReference = new ImageReference
                    {
                        Publisher = "MicrosoftWindowsServer",
                        Offer = "WindowsServer",
                        Sku = "2022-datacenter-g2",
                        Version = "latest"
                    }
                };

  Using API directly works, so this is definitely a bug in nuget.

**Comment by xboxeer** [comment]
> vmconfig.StorageProfile = new VirtualMachineStorageProfile { OSDisk = new VirtualMachineOSDisk(DiskCreateOptionType.FromImage) { Name = $"{machine}-{instance}-OsDisk", Caching = CachingType.ReadWrite, OSType = SupportedOperatingSystemType.Windows, ManagedDisk = new VirtualMachineManagedDisk { StorageAccountType = StorageAccountType.StandardLrs } }, ImageReference = new ImageReference { Publisher = "MicrosoftWindowsServer", Offer = "WindowsServer", Sku = "2022-datacenter-g2", Version = "latest" } };
> 
> Using API directly works, so this is definitely a bug in nuget.

This is a swagger issue that the tag operation under managed disk returns status 202 but SDK is expecting 200 response based on swagger definition, corresponding issue opened here: https://github.com/Azure/azure-rest-api-specs/issues/20267

**Comment by gui28347** [comment]
any update?

**Comment by Yao725** [comment]
Sorry for the delayed response, we are working on it, will update later.

**Comment by ArcturusZhang** [comment]
@gui28347 I believe this should have been fixed in one or two versions ago therefore if you have a try on the latest version of `Azure.ResourceManager.Compute`, it is fixed.
I am using `v1.2.0-beta.1` of `Azure.ResourceManager.Compute`:
```csharp
var group = client.GetResourceGroupResource(groupId);

ManagedDiskResource disk = group.GetManagedDisk("myDisk");

Console.WriteLine(disk.Id);

ManagedDiskResource newDisk = disk.SetTags(new Dictionary<string, string>
{
    ["my"] = "test"
});

Console.WriteLine(newDisk.Id);
Console.WriteLine(newDisk.Data.Tags.Count); // 1
Console.WriteLine(newDisk.Data.Tags["my"]); // test
```
