### ISSUE TITLE
[BUG] Unable to use AuthorizationManagementClient due to preview api use

### ISSUE THREAD

**Issue by azurecoder** [Azure/azure-sdk-for-net#30248]
### Library name and version

Microsoft.Azure.Management.Authorization 2.0.13.preview

### Describe the bug

Trying to add a role assignment but unable to use AuthorizationManagementClient to do anything.

The library has been in preview for the last 5 years and each preview release used a release of the Azure preview API which subsequently got dropped in lieu of a properly dated library version. 

If I drop to 2.0.1 which is the last stable release from 2017 I can't use with .net core.

Can you let me know when there will be another stable release of this library? For now I'm dropping back to the REST API. 

### Expected behavior

Adds role assignment to an Azure object

### Actual behavior

Response produces:

_{"error":{"code":"InvalidApiVersionParameter","message":"The api-version '2020-08-01-preview' is invalid. The supported versions are '2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."}}_

### Reproduction Steps

Something like this.

1. Generate a bearer token 
2. Use the AuthorizationManagementClient
3. Assign a role definition (contributor used below)
4. Watch is blow up with: "code":"InvalidApiVersionParameter","message":"The api-version '**2020-08-01-preview**' is invalid

var credentials = new TokenCredentials(await GetAccessTokenFor(resourceUriAzure,_tenantName, _tenantId, _clientId, _clientSecret));
var client = new AuthorizationManagementClient(credentials);
var assignment = await client.RoleAssignments.CreateByIdAsync(resourceId, new Microsoft.Azure.Management.Authorization.Models.RoleAssignmentCreateParameters()
  {
     PrincipalId = userName,
     PrincipalType = "User",
     RoleDefinitionId = "b24988ac-6180-42a0-ab88-20f7382dd24c"
  });

### Environment

.net 6
windows 11
Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
@azurecoder please try with our new generation of .NET SDK: https://www.nuget.org/packages/Azure.ResourceManager.Authorization/1.0.0
Here is a quick start guide: https://github.com/Azure/azure-sdk-for-net/blob/main/doc/dev/mgmt_quickstart.md
