### ISSUE TITLE
[QUERY] How do i access the network interface configuration of a machine in virtual scaleset ? 

### ISSUE THREAD

**Issue by chkeita** [Azure/azure-sdk-for-net#30253]
### Library name and version

Azure.Management.Compute

### Query/Question

I am trying to access [this request](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/network-interface-in-vm-ss/get-virtual-machine-scale-set-network-interface?tabs=HTTP)  from the api. 

The closest i could get was with this query
```C#
var scalesetId = new ResourceIdentifier("...");
client.GetVirtualMachineScaleSetResource(scalesetId).GetVirtualMachineScaleSetVm("0").Value.Data.NetworkProfile;
```
but I can only get the the resourceId of the network interface  from there and it looks like there is no ay to retrieve the actual interface data. 

Am i missing something ?

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@chkeita you need to call `client.GetVirtualMachineScaleSetResource(scalesetId).GetVirtualMachineScaleSetVm("0").Get()` before you try to get the `.Value`, the `GetVirtualMachineScaleSetVm` does not actually made any request to Azure so the data is null.

**Comment by chkeita** [comment]
@xboxeer i dont have any issue accessing the result of that query. My problem is that i want to access the network configuration properties. 
The query i provided only gives me access to the resourceId of network interface. I am looking for  a way to access the result of [this request](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/network-interface-in-vm-ss/get-virtual-machine-scale-set-network-interface?tabs=HTTP)

**Comment by xboxeer** [comment]
@chkeita  the rest api you referred is a network RP api not a compute RP API, but due to some naming issue we have not implemented that API in SDK yet, we already have an issue looking into it: https://github.com/Azure/azure-sdk-for-net/issues/28185
Back to your question, if you try this code
```csharp
 var vmss = this._client.GetDefaultSubscription().GetResourceGroup(resourceGroupName).Value.GetVirtualMachineScaleSet("elendil-test-vmss").Value;
var networkProfile = vmss.Data.VirtualMachineProfile.NetworkProfile;
```
you should be able to get the result as below, is this what you are looking for?
![image](https://user-images.githubusercontent.com/5089150/186122826-063579a4-94d5-4635-b39c-4272e61c9d1d.png)

**Comment by jallirs** [comment]
I'm facing the same issue. I need to get the private ip address of a vmss instance, as well as the mac address. What's pasted above doesn't provide that. Is there a workaround?

**Comment by s20leems** [comment]
@xboxeer, I'm also having the same issue. Even if you can get the NetworkProfile from VMSS VM, there's no public IP address that I can take from it. Even in the IPConfigurations that you expanded in the screenshot, there's no public IP address. 

Does anyone know a proper way to retrieve the information?
