### ISSUE TITLE
[QUERY] Deferred messages in session-enabled queue

### ISSUE THREAD

**Issue by hgjura** [Azure/azure-sdk-for-net#30252]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

I have a scenario where in a queue, which is session-enabled, I need to defer some messages for later processing. However, in rare circumstances, the process loses track of the sessions, and the messages seem to remain trapped for eternity. I need to accomplish one of the these two things:
- Be able to iterate through the deferred messages. If this message wasnt session-enabled I would be able to get all messages and inspect their state. However, the AcceptNextSessionAsync() it never goes through the deferred messages, but rather throws ServiceTimeout exception as sessions do not exist. How do I get to these messages, in a session enabled queue?
- Be able to expire them and send them to DLQ after a certain period of time. I was expecting the deferred messages to go to DLQ just like the regular expired messages, but that does not seem the case. Is there a way I can accomplish this?

Thanks.

**Comment by JoshLove-msft** [comment]
If you know the specific session that the message is in, you can use the AcceptSessionAsync method and pass in the sessionId. 
In order to receive deferred messages you need to know the specific sequence numbers. If you prefer something like a deadletter queue, you can use the DeadLetterMessageAsync method instead of DeferMessageAsync.

**Comment by JoshLove-msft** [comment]
> Can you confirm, that without the session id or sequence ids, the messages in the deferred list are stuck/lost forever, and there is no way of getting them out (short of deleting and recreating the queue)?

Yes, you need the sequence Ids to receive deferred messages, and in the case of using sessions, you need the session Id if you don't still have the receiver instance that originally received the messages. You can peek messages to attempt to find the deferred messages as these messages will have the [State property](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessagestate?view=azure-dotnet) set to deferred.

> Also, that the stuck messages in the Deferred List do not expire, like messages in the regular queue do, and hence do never go into the DLQ?

Correct, this is called out in the docs - https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-deferral

> If this the case for both, than this solution should come with a bold disclaimer, as this may result with unintentional data loss.

Agreed - take a look at the docs here - https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-deferral#retrieving-deferred-messages

**Comment by hgjura** [comment]
@JoshLove-msft  thanks for the clarification.
The docs mentions this "Deferred messages can be discovered via [message browsing](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-browsing) if an application loses track of them." I am assuming that in case when I don't have a valid session id I cannot "browse" the messages as I cant call AcceptSessionAsync and AcceptNextSessionAsync will always timeout. Is that correct?

**Comment by JoshLove-msft** [comment]
You should be able to use a regular ServiceBusReceiver when peeking (aka browsing) since there is no need for a lock when peeking. I just tested this out and it works.

**Comment by hgjura** [comment]
When I try with a regular receiver I get an error about the queue needing a ServiceBusSessionReceiver since the queue is session-enabled. The regular ServiceBusReceiver throws an error for me. Can you paste some working code to see if I get it right?

**Comment by JoshLove-msft** [comment]
```c#
  var regularReceiver = client.CreateReceiver(scope.QueueName);
  // verify peeked == send
  var ct = 0;
  foreach (ServiceBusReceivedMessage peekedMessage in await regularReceiver.PeekMessagesAsync(
      messageCt,
      sequenceNumber))
  {
...
  }

**Comment by hgjura** [comment]
@JoshLove-msft  Thanks for this. It set me in the right direction. At the end I was able to accomplish what I was expecting to do. 
However, I run into an unexpected behavior, that would like to bring to your attention.

This is finally the code that does it all for me. I wanted to get Deferred messages that have ExpiresAt past due. And process them differently or send them to DLQ for alternative processing. This code does that. 
However, the line ``` session.ReceiveDeferredMessagesAsync(seqs)``` throws an error and doesnt find the message because the system throws it directly into DLQ before you retrieve it. I was expecting to get the message, and than send it myself to DLQ.

```csharp
            //list of sequence numbers / sessions
            var sessionids = new Dictionary<long, string>();

            //here I am collecting all deferred messages that are past expiration time/
            //I am collecting their sequence numbers and their session id
            // >> in my test I get 3 messages that fit this criteria 
            // >> sessionid: ffcb549a-437a-4357-a238-f2837708879b sequencenumbers: 67, 69, 70
            foreach (ServiceBusReceivedMessage m in await resp_receiver.PeekMessagesAsync(1000))
            {
                if (m.State == ServiceBusMessageState.Deferred && m.ExpiresAt <= DateTime.UtcNow)
                {
                    sessionids.Add(m.SequenceNumber, m.SessionId);
                }
            }

            //getting a distinct session values
            // >> in my tests, single value: ffcb549a-437a-4357-a238-f2837708879b
            var ids =  sessionids.Values.Distinct().ToList();

            foreach (var id in ids)
            {

                //this is a custom method. it returns a Session Receiver with the given id : ffcb549a-437a-4357-a238-f2837708879b
                var session = await _getSessionAsync(q_name_resp, id, new CancellationTokenSource(TimeSpan.FromMinutes(1)).Token);

                if (session != null)
                {
                    //this aggregates the sequence numbers
                    // >> in my tests a list of 67, 69, 70
                    var seqs = sessionids.Where(s=>s.Value == id).Select(s=>s.Key).ToList();
                    try
                    {
                        // this one fails: Failed to lock one or more specified messages. Either the message is already locked or does not exist. ... (MessageNotFound)
                        // It fails because before even returning the messages, behind the scenes it expeires them and sends them to DLQ. Hence, ReceiveDeferredMessagesAsync() throws errors becuase messages are already in DLQ.
                        // Enexpected behavior, but it does exactly what I wanted to do.
                        var msgs = await session.ReceiveDeferredMessagesAsync(seqs);
                    }
                    catch (ServiceBusException ex)
                    {
                        if (ex.Reason != ServiceBusFailureReason.MessageNotFound) throw;                       
                    }
                }
            }
```

**Comment by JoshLove-msft** [comment]
Are you deferring the messages after they have already been deadlettered? Can you share the deferral code?

**Comment by hgjura** [comment]
No the message is send to Deferred list immediately after it is read. The choices are: if message is next in line to be processed, process it, otherwise defer it. It expires while it is in the deferred list, when the message prior in the processing order never makes it.

The code is rather complex, but here is a simplified version of it that tells the sequence of events.

```csharp
var state_data = await reqs_receiver_session.GetSessionStateAsync();
var session_state = state_data != null ? state_data.ToObjectFromJson<SessionStateManager>() : new SessionStateManager();

if (order == session_state.LastProcessedCount + 1)  //check if message is next in the sequence
{    
    // process message here

    if (!isLast)    
    {        
        session_state.LastProcessedCount = order;
        await reqs_receiver_session.SetSessionStateAsync(new BinaryData(session_state, null, typeof(SessionStateManager)));    
    }    
    else    
    {        
        await reqs_receiver_session.SetSessionStateAsync(null);    
    }
    
    await _processDeferredListAsync(session_state, reqs_receiver_session, _executeCommandMessageAsync);
}
else
{    
    await _addMessageToDeferredListAsync(session_state, order, item, reqs_receiver_session);
}

```

**Comment by hgjura** [comment]
In hindsight, this seems like a bug. The ExpireAt trigger should expire a message regardless of its state, either being Active or Deferred. 

In case of Deferred, it seem to place it in this limbo state, where it has expired but is not in the DLQ. It is still in the Deferred list, and you can Peek it, but you can't read it as when try to read it, and only then, it jumps into the DLQ, before you can actually read it. It is in this you can see it but you cant read it mode. Which is not helpful.

You can try this by defer a message with a shorter ExpiryAt period, and you will see it that is stays in the list, you can see it by Peek-ing at it, but when retrive it only then goes to DLQ and you get an exception. Try this in a session-enabled queue, as that is where I see this.

**Comment by JoshLove-msft** [comment]
I'll try to reproduce this and then follow up with the service team regarding the expected behavior here.

**Comment by JoshLove-msft** [comment]
> In hindsight, this seems like a bug. The ExpireAt trigger should expire a message regardless of its state, either being Active or Deferred.

As noted in the [docs](https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-deferral), this behavior is by design. I will need to follow up on the behavior once the expiration has past.

**Comment by JoshLove-msft** [comment]
I've confirmed with the service team that what you are seeing is the expected behavior:

Deferred messages will not be automatically moved to the DLQ on expiry. However, once they are expired and you try to receive them, they will be moved to the DLQ at that time. They informed me that they would update the docs to clarify this.
