### ISSUE TITLE
[Synapse] QuerySessions failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#30262]
Synapse nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 400 (Bad Request)
> 
> Content:
> {
> "code": "BadRequest",
> "message": "Creating debug session failed: Not able to start cluster.",
> "target": null,
> "details": null,
> "error": null
> }
> 
> Headers:
> Server: Kestrel,Microsoft-HTTPAPI/2.0
> Strict-Transport-Security: REDACTED
> x-ms-correlation-request-id: REDACTED
> x-ms-request-id: b8c61e61-251e-4205-80cc-c44c8b07af1b
> x-ms-client-request-id: cbef4c07-f293-44c0-8a1d-95b75243fa10
> Date: Mon, 01 Aug 2022 19:14:42 GMT
> Content-Length: 154
> Content-Type: application/json; charset=utf-8
> 
> 
> Stack trace
>    at Azure.Analytics.Synapse.Artifacts.DataFlowDebugSessionRestClient.DeleteDataFlowDebugSessionAsync(DeleteDataFlowDebugSessionRequest request, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/DataFlowDebugSessionRestClient.cs:line 267
>    at Azure.Analytics.Synapse.Artifacts.DataFlowDebugSessionClient.DeleteDataFlowDebugSessionAsync(DeleteDataFlowDebugSessionRequest request, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/DataFlowDebugSessionClient.cs:line 109
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 166
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.DisposableDataFlowDebugSession.DisposeAsync() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/DataFlowDebugSessionClientLiveTests.cs:line 51
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.QuerySessions() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/DataFlowDebugSessionClientLiveTests.cs:line 103
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.QuerySessions() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/DataFlowDebugSessionClientLiveTests.cs:line 103
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1749598&view=results

@jsquire for notification.

**Comment by yanjungao718** [comment]
This is not repro when investigating, looks like a random issue.

**Comment by yanjungao718** [comment]
close it now, please feel free to open it if repro again.
