### ISSUE TITLE
[Translation] GetTranslationStatusesFilterByStatusTest failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#30264]
Translation nightly test runs are failing with:

> Error message
> Expected: True
> But was:  False
> 
> 
> Stack trace
>    at Azure.AI.Translation.Document.Tests.DocumentTranslationClientLiveTests.GetTranslationStatusesFilterByStatusTest() in D:\a\_work\1\s\sdk\translation\Azure.AI.Translation.Document\tests\GetAllTranslationsFilterTests.cs:line 114
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1749123&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
//fyi:  @pallavit

**Comment by pallavit** [comment]
@mayurid who would be the right person to loop in for translation SDK?

**Comment by jsquire** [comment]
@v-xuto:  May I ask why you're adding "needs-team-triage" back after we've triaged?   😄

**Comment by v-xuto** [comment]
@jsquire I added "needs-team-triage" based on this [comments](https://github.com/Azure/azure-sdk-for-net/issues/29896#issuecomment-1198575018) of yours, am I understanding it wrong?

**Comment by jsquire** [comment]
@v-xuto:  You added it correctly, then we triaged.   Then you added it back, sending it back to triage.   The "needs-team-triage" label should be applied when the issue is originally filed, which makes it visible to our triage team.   Once we triage to the right place, we remove it.

**Comment by v-xuto** [comment]
@jsquire Got it. We will only add the "needs-team-triage" label when the issue is originally filed.
