### ISSUE TITLE
[BUG] Creating Scaleset with Extensions thrown a null value exception

### ISSUE THREAD

**Issue by phmcder** [Azure/azure-sdk-for-net#30266]
### Library name and version

Azure.ResourceManager.Compute 1.0.0

### Describe the bug

I'm trying to deploy a Virtual Machine Scale Set that requires some extensions to be loaded. I create the extensions using the `VirtualMachineScaleSetExtensionData(string name)` constructor. However when I run the function `resourceGroup.GetVirtualMachineScaleSets().CreateOrUpdateAsync` a null value exception is thrown.

`at Azure.ResourceManager.Compute.VirtualMachineScaleSetExtensionData.Azure.Core.IUtf8JsonSerializable.Write(Utf8JsonWriter writer) in C:\azure-sdk-for-net2\sdk\compute\Azure.ResourceManager.Compute\src\Generated\Models\VirtualMachineScaleSetExtensionData.Serialization.cs:line 75`

The issue is that the property `ProvisionAfterExtensions` is null and the check `Optional.IsCollectionDefined(ProvisionAfterExtensions)` is returning `true` causing subsequent code to throw the exception.

I have tried to work around this issue but have been unsuccessful. `ProvisionAfterExtensions` is read-only so I am unable to create the collection. The collection is only created when using the parameterless constructor for `VirtualMachineScaleSetExtensionData()`, however, Azure then throws an exception because no name has been assigned to the extension. Extension name can only be set using the constructor which does not set `ProvisionAfterExtensions`

### Expected behavior

Creating a scalset extension with the property `ProvisionAfterExtensions` set to null should not throw an exception. 

### Actual behavior

Creating a scalset extension with the property `ProvisionAfterExtensions` set to null throws an exception. 

### Reproduction Steps

1. Create a scaleset extension using the constructor `VirtualMachineScaleSetExtensionData(string name)`
2. Add properties but make sure `ProvisionAfterExtensions` is null
3. Add the above extension to a new `VirtualMachineScaleSetData` instance
4. Call `resourceGroup.GetVirtualMachineScaleSets().CreateOrUpdateAsync` to create the ScaleSet

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.104
 Commit:    915d644e45

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.104\

**Comment by lk668** [comment]
I also faced the same issue.  
I use the parameterless constructor `VirtualMachineScaleSetExtensionData()` to initialize `VirtualMachineScaleSetExtensionData` object as a workaround. Actually, the name here is a custom name (you can set it to anything) instead of the extension name. You need to configure `ExtensionType` as extension name in `VirtualMachineScaleSetExtensionData`. It will work well.

**Comment by phmcder** [comment]
> I also faced the same issue. I use the parameterless constructor `VirtualMachineScaleSetExtensionData()` to initialize `VirtualMachineScaleSetExtensionData` object as a workaround. Actually, the name here is a custom name (you can set it to anything) instead of the extension name. You need to configure `ExtensionType` as extension name in `VirtualMachineScaleSetExtensionData`. It will work well.

Thanks for the reply but I wasn't able to replicate your success. If I use the parameter less constructor I receive the following error on commit 

`The entity name 'extensionName' is invalid according to its validation rule: ^[^_\W][\w-._]{0,79}(?<![-.])$.
Status: 400 (Bad Request)
ErrorCode: InvalidParameter

Content:
{
  "error": {
    "code": "InvalidParameter",
    "message": "The entity name 'extensionName' is invalid according to its validation rule: ^[^_\\W][\\w-._]{0,79}(?<![-.])$.",
    "target": "extensionName"
  }
}

Headers:
Pragma: no-cache
x-ms-ratelimit-remaining-resource: REDACTED
Strict-Transport-Security: REDACTED
x-ms-request-id: 1707257e-98e1-4ccc-a705-196de380aab8
x-ms-client-request-id: 0d03e25b-cf60-41bb-82f7-9d757158825a
Content-Length: 217
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Server: Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
X-Content-Type-Options: REDACTED
Date: Wed, 24 Aug 2022 11:04:34 GMT`

**Comment by lk668** [comment]
> Thanks for the reply but I wasn't able to replicate your success. If I use the parameter less constructor I receive the following error on commit
> 
> `The entity name 'extensionName' is invalid according to its validation rule: ^[^_\W][\w-._]{0,79}(?<![-.])$. Status: 400 (Bad Request) ErrorCode: InvalidParameter
> 
> Content: { "error": { "code": "InvalidParameter", "message": "The entity name 'extensionName' is invalid according to its validation rule: ^[^_\\W][\w-._]{0,79}(?<![-.])$.", "target": "extensionName" } } `

You missed the `extensionName` in the `resourceGroup.GetVirtualMachineScaleSets().CreateOrUpdateAsync` function? Here I use the same name as `ExtensionType`.

**Comment by phmcder** [comment]
Hi @lk668 

If I do the below to configure a CustomScriptExtension then I get the error about missing extensionName.

`	
        var extensions = new VirtualMachineScaleSetExtensionProfile();
	extensions.Extensions.Add(
	new VirtualMachineScaleSetExtensionData()
	{
		Publisher = "Microsoft.Compute",
		ExtensionType = "CustomScriptExtension",
		TypeHandlerVersion = "1.10",
		AutoUpgradeMinorVersion = true,
		Settings = scriptPublicSettings,
		ProtectedSettings = scriptPrivateSettings
	}
`

ExtensionName is not a property of VirtualMachineScaleSetExtensionData. There is a property of Name but that is read only and can only be set in the constructor.

If I do the following to fix the above error I get the originally reported null serialization exception

`       
        var extensions = new VirtualMachineScaleSetExtensionProfile();
	extensions.Extensions.Add(
	new VirtualMachineScaleSetExtensionData("myextension")
	{
		Publisher = "Microsoft.Compute",
		ExtensionType = "CustomScriptExtension",
		TypeHandlerVersion = "1.10",
		AutoUpgradeMinorVersion = true,
		Settings = scriptPublicSettings,
		ProtectedSettings = scriptPrivateSettings
	}
`

Am I missing something else?

**Comment by lk668** [comment]
> Hi @lk668
> 
> If I do the below to configure a `CustomScriptExtension` then I get the error about missing `extensionName`.
> 
> ```
>         var extensions = new VirtualMachineScaleSetExtensionProfile();
> 	extensions.Extensions.Add(
> 	new VirtualMachineScaleSetExtensionData()
> 	{
> 		Publisher = "Microsoft.Compute",
> 		ExtensionType = "CustomScriptExtension",
> 		TypeHandlerVersion = "1.10",
> 		AutoUpgradeMinorVersion = true,
> 		Settings = scriptPublicSettings,
> 		ProtectedSettings = scriptPrivateSettings
> 	}
> ```
> 
> `ExtensionName` is not a property of `VirtualMachineScaleSetExtensionData`. There is a property of `Name` but that is read only and can only be set in the constructor.
> 
> If I use the constructor with the `name` parameter to fix the above error I get the originally reported null serialization exception due to null `ProvisionAfterExtensions`
> 
> ```
>         var extensions = new VirtualMachineScaleSetExtensionProfile();
> 	extensions.Extensions.Add(
> 	new VirtualMachineScaleSetExtensionData("myextension")
> 	{
> 		Publisher = "Microsoft.Compute",
> 		ExtensionType = "CustomScriptExtension",
> 		TypeHandlerVersion = "1.10",
> 		AutoUpgradeMinorVersion = true,
> 		Settings = scriptPublicSettings,
> 		ProtectedSettings = scriptPrivateSettings
> 	}
> ```
> 
> Am I missing something else?

Seems our scenario is not the same, I use `VirtualMachineScaleSetExtensionCollection.CreateOrUpdateAsync` function to add extension to an existed vmss. I init the `VirtualMachineScaleSetExtensionData` this way. It can work well.
```
var azSecPackVmssExtension = new VirtualMachineScaleSetExtensionData()
            {
                TypeHandlerVersion = version,
                ExtensionType = AzSecPackExtensionConstants.AzSecPackExtensionName,
                Publisher = AzSecPackExtensionConstants.AzSecPackExtensionPublisher,
                EnableAutomaticUpgrade = true,
                Settings = BinaryData.FromString("{\"enableGenevaUpload\":true}"),
 };
```

**Comment by ArcturusZhang** [comment]
Hey @phmcder sorry for the delay of response, this has been fixed in a recent patch version of the compute SDK, please have a try: https://www.nuget.org/packages/Azure.ResourceManager.Compute/1.0.1
