### ISSUE TITLE
Documentation: pros and cons of Amqp vs AmqpWebSockets

### ISSUE THREAD

**Issue by tomeberhard** [Azure/azure-sdk-for-net#30270]
So that help page describes what to use:

- Amqp | 0 | Uses AMQP over TCP. This is the default value. It runs on port 5671. (ok that's kinda good to know)
- AmqpWebSockets | 1| uses it over webSockets. (also kinda obvious from the name)

What's missing is a bit of an explanation of the pros and cons of using one or the other. When should we use Amqp, and when should we use AmqpWebSockets. What are the implications. If it requires more than a paragraph to get the gist of the difference, please link to a longer blog entry or similar.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fc77eef1-62e7-007a-20bc-94c9a22b4f93
* Version Independent ID: 26fa7c4a-b015-ac4b-340f-cc531e53d638
* Content: [TransportType Enum (Microsoft.Azure.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.transporttype?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.ServiceBus/TransportType.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.ServiceBus/TransportType.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@tomeberhard There are mentions of the difference in this [protocol guide doc](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide).

The main difference is that WebSockets are used for underlying connection which is over port 443. This could be useful in cases where networks where the clients are running block all other ports for security reasons.

Apart from the underlying connection, the AMQP aspects are still the same.
