### ISSUE TITLE
Regenerate C# Data Factories using the latest AutoRest

### ISSUE THREAD

**Issue by mikeblakeuk** [Azure/azure-sdk-for-net#3031]
- [ ] Recreate the Microsoft.Azure.Management.DataFactories nuget package with the latest swagger spec AutoRest
- [ ] Microsoft.Azure.Common
- [ ] Remove Hyak.Common

**Comment by sphibbs** [comment]
@mikeblakeuk Are you talking about the .Net SDK's or Node. Just want to clarify since this is the .Net repo and the subject has (node).

**Comment by mikeblakeuk** [comment]
.NET, using the Node version of AutoRest

**Comment by mikeblakeuk** [comment]
Any news on this. we really want to remove Hyak, Azure.common and Microsoft.Build from our solution

**Comment by mikeblakeuk** [comment]
Any news on this?

**Comment by hvermis** [comment]
@mikeblakeuk ADF swagger has been added to github for a while now:
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/datafactory/resource-manager
And we regularly release our nuget packages:
https://www.nuget.org/packages/Microsoft.Azure.Management.DataFactory

**Comment by hvermis** [comment]
Please note that the swagger and nuget are for ADF V2. We do not plan to add ADF V1.
