### ISSUE TITLE
[BUG] Updates and publishing QuestionAnswering APIs too slow

### ISSUE THREAD

**Issue by tung238** [Azure/azure-sdk-for-net#30332]
### Library name and version

Azure.AI.Language.QuestionAnswering 1.1.0-beta.2

### Describe the bug

We are using Azure QuestionAnswering for our product and recently we saw that all QuestionAnswering's APIs we used to update QnA, Source, and publish Knowledgebase become too slow, previously it usually takes 5 seconds but now takes ~30 seconds to complete.
APIs which we notice the slowness in QuestionAnsweringProjectsClient:
UpdateSourcesAsync
UpdateQnasAsync
DeployProjectAsync

This is a sample result of API call:
```
{{
  'createdDateTime': '2022-08-03T08:31:27+00:00',
  'expirationDateTime': '2022-08-03T14:31:27+00:00',
  'jobId': '9cbe1191-248d-422f-9736-162b6af11d58',
  'lastUpdatedDateTime': '2022-08-03T08:31:35+00:00',
  'status': 'succeeded',
  'resultUrl': '/knowledgebases/TrabbleKnowledgebase'
}}
```

It looks like azure takes 7 seconds to complete but my side only receives this 30 seconds after trigger request. This happens even with our staging environment on azure so it is not an internet connectivity issue. 
The issue also happened with Azure.AI.Language.QuestionAnswering library version 1.1.0-beta.1

Time running the benchmark:
``` ini

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
11th Gen Intel Core i7-11800H 2.30GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK=6.0.201
  [Host]     : .NET 6.0.3 (6.0.322.12309), X64 RyuJIT
  DefaultJob : .NET 6.0.3 (6.0.322.12309), X64 RyuJIT


```
|             Method |    Mean |   Error |  StdDev |
|------------------- |--------:|--------:|--------:|
| UpdateSourcesAsync | 30.44 s | 0.082 s | 0.069 s |
|    UpdateQnasAsync | 30.44 s | 0.111 s | 0.098 s |
| DeployProjectAsync | 30.36 s | 0.048 s | 0.037 s |

### Expected behavior

APIs should complete in ~5 seconds

### Actual behavior

APIs take ~30 seconds to complete

### Reproduction Steps

I created  a minimal project for reproducing the issue
`https://github.com/tung238/QuestionAnsweringIssue`

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  3.1.416 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  6.0.102 [C:\Program Files\dotnet\sdk]
  6.0.200 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
@rokulka can you take a look? Our default polling is every 1s if the service doesn't send back a `Retry-After` header, so any change to timing is not likely the SDK.

**Comment by heaths** [comment]
I have verified that the service is sending back a `Retry-After: 00:00:30` header, which the newer SDKs honor. @peytonfraser @rokulka this might be something for the service to consider.

**Comment by jasondotackmanatjenzabardotcom** [comment]
This is a major issue for our products that use QuestionAnswering as well. And ideas if/when this may be resolved? @peytonfraser @rokulka
