### ISSUE TITLE
[FEATURE REQ] Support decrypting queue messages on function trigger

### ISSUE THREAD

**Issue by elarrieux** [Azure/azure-sdk-for-net#30363]
### Library name

Azure.WebJobs.Extensions.Storage.Queues

### Please describe the feature.

Client-side encrypted queue messages can't be decrypted with Azure Functions Queue trigger without manually implementing decryption mechanisms.

It would be great if we can configure the trigger to use the same key that was used for client-side encryption and let the SDK handle it.

**Comment by navba-MSFT** [comment]
@elarrieux Thanks for reaching out to us and sharing this feedback. Could you please try to create a [QueueEncryptionPolicy](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.queue.queueencryptionpolicy?view=azure-dotnet-legacy) object and set it in the request options (per API or at a client level by using DefaultRequestOptions). The encryption / decryption will be done be implicitly done by the client library SDK implicitly. 

```
// Create the IKey used for encryption.
 RsaKey key = new RsaKey("private:key1" /* key identifier */);

// Create the encryption policy to be used for upload and download.
 QueueEncryptionPolicy policy = new QueueEncryptionPolicy(key, null);

// Add message
 QueueRequestOptions options = new QueueRequestOptions() { EncryptionPolicy = policy };
 queue.AddMessage(message, null, null, options, null);

// Retrieve message
 CloudQueueMessage retrMessage = queue.GetMessage(null, options, null);
```

Hope this helps.

**Comment by elarrieux** [comment]
Your solution requires to create a QueueClient, which I don't have as I'm using the Azure Function Queue Trigger. 

Also, I'm using v12 SDK with ClientSideEncryptionVersion.V2_0

I'm looking for a way to configure the trigger with the same SpecializedQueueClientOptions as I configured the application that writes to the queue.

**Comment by navba-MSFT** [comment]
@elarrieux Thanks for getting back. Could you please try to use the test case sample provided [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Queues/tests/ClientSideEncryptionTests.cs) and see if that helps ?

**Comment by elarrieux** [comment]
@navba-MSFT There is no decryption code in the test case sample you provided but that is not what I am looking for, I already have the code to do the decryption.

My feature request is that there should be an easier way to configure the trigger instead of copying and pasting the decryption code from the SDK source.

I shouldn't be copying values like nonce length or tag size. There should be a simpler way to do this.

**Comment by navba-MSFT** [comment]
@elarrieux Thanks for clarifying. I am doing some research on this. I will get back to you once I have more info on this.

**Comment by navba-MSFT** [comment]
@elarrieux I am adding the service team to look into this ask and feasibility of implementing this. 

@xgithubtriage Could you please look into this ask and provide an update once you get a chance?
