### ISSUE TITLE
[BUG] Cannot list role assignments directly from a resource scope 

### ISSUE THREAD

**Issue by shareonline** [Azure/azure-sdk-for-net#30367]
### Library name and version

Azure.ResourceManager.Authorization 1.0.0-beta.1

### Describe the bug

When retrieving a generic ArmResource with the ArmClient, the extention method call to list all RoleAssignments on that resource are not working.

`var ResourceIdentifier = new Azure.Core.ResourceIdentifier(ResourceId);`
`ArmResource armResource = await armClient.GetGenericResource(ResourceIdentifier).GetAsync();`
`AsyncPageable<RoleAssignmentResource> roleAssignments = armResource.GetRoleAssignments().GetAllAsync($"atScope()");`

It works fine when trying to list role assignments for a ResourceGroupResource. so i believe this to be a bug?

### Expected behavior

expected to retrive a list of role assignments directly assigned on that resource (`List of AsyncPageable<RoleAssignmentResource>`)

### Actual behavior

throws the following error "Value cannot be empty or contain only white-space characters. (Parameter 'resourceType')"

### Reproduction Steps

`var ResourceIdentifier = new Azure.Core.ResourceIdentifier(ResourceId);`
`ArmResource armResource = await armClient.GetGenericResource(ResourceIdentifier).GetAsync();`
`AsyncPageable<RoleAssignmentResource> roleAssignments = armResource.GetRoleAssignments().GetAllAsync($"atScope()");`

### Environment

.NET 6.0 
Visual Studio 2022 (17.2.5)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
I tried with `Azure.ResourceManager.Authorization 1.0.0` and cannot reproduce the issue. Please use the stable version and try again.
