### ISSUE TITLE
[FEATURE REQ] Add X509Certificate support to ArmClient

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#30364]
### Library name

Azure.ResourceManager

### Please describe the feature.

We want to add another overload the ArmClient ctor which takes in an `X509Certificate2` instead of a `TokenCredetial` similar to [Confidential Ledger](https://github.com/Azure/azure-sdk-for-net/blob/9297e2e0c0879e3e274837585b186243dd9a40d9/sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/ConfidentialLedgerClient.cs#L37). 

We then need to construct the pipeline in the appropriate way depending on which ctor was used [similar to this](https://github.com/Azure/azure-sdk-for-net/blob/9297e2e0c0879e3e274837585b186243dd9a40d9/sdk/confidentialledger/Azure.Security.ConfidentialLedger/src/ConfidentialLedgerClient.cs#L66-L79).

**Comment by welovej** [comment]
Hi @m-nash , this feature already supported, please check the [link ](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.clientcertificatecredential?view=azure-dotnet).  Create a  ClientCertificateCredential instance  which is a child class of TokenCredential, then pass it as a parameter of ArmClient.  Thanks.
