### ISSUE TITLE
[QUERY] How do I DELETE a role assignment using Azure.ResourceManager?

### ISSUE THREAD

**Issue by laserPointerFocus** [Azure/azure-sdk-for-net#30362]
How should I delete role assignments using the new Azure.ResourceManager instead of the previous Microsoft.Azure.Management package? I'm struggling to find documentation to perform this action.

**Comment by m-redding** [comment]
Thanks for opening an issue - we will get back to you shortly.

**Comment by xboxeer** [comment]
@laserPointerFocus  you should import the `Azure.ResourceManager.Authorization` package (It is still in preview stage) and use below code to delete role assignment(Delete on a resource group as an example)
```csharp
public void DeleteRoleAssignment(string resourceGroupName)
        {
            var resourceGroups = this.client.GetDefaultSubscription().GetResourceGroups();
            var rg=resourceGroups.Get(resourceGroupName).Value;

            rg.GetRoleAssignment("test").Value.Delete(Azure.WaitUntil.Completed);
        }
```
