### ISSUE TITLE
Get Cosmos Consumption RU value

### ISSUE THREAD

**Issue by kranthikumar-kvs-by** [Azure/azure-sdk-for-net#30385]
### Library name and version

Microsoft.Azure.Cosmos 3.29.0

### Query/Question

I am trying to get the current RU consumption value on Cosmos but I don't see any API to get this value.
I have gone through this API but it doesn't provide the current RU consumption value, it gives the current RU value configured on the container.

Container.ReadThroughputAsync
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.readthroughputasync?view=azure-dotnet

Is there any way I can get the live RU consumption value when hit to a container through an API?

**Comment by SaurabhSharma-MSFT** [comment]
@kranthikumar-kvs-by You can try checking the `RequestCharge` property as mentioned in [Request unit charge for operations in Azure Cosmos DB SQL API](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/find-request-unit-charge?tabs=dotnetv3) document to get cost of all database operations.

**Comment by kranthikumar-kvs-by** [comment]
@SaurabhSharma-MSFT, I am not looking for the RU's of a given request, I am aware of that, it is already present.
As stated earlier I am looking to know the RU's consumption at the DB when I make a call with an API.

For an example if the throughput configured on the Cosmos with Autoscaling option enabled is set with 5000 then the total RU's consumed would range between 500 to 5000 based on load on the Cosmos by hitting many request.

In this scenario when there are too many request hit on Cosmos, at any point of time if I want to know what is the overall consumption of RU's on Cosmos, I don't have any API to know that.

My request is that I want to know the **total current consumption of RU's** at any point of time by using any API.

**Comment by kranthikumar-kvs-by** [comment]
@SaurabhSharma-MSFT, any update on this pl.

**Comment by SaurabhSharma-MSFT** [comment]
@kranthikumar-kvs-by sorry for the delay.  I believe the you can use the Azure Monitor REST API to query the “TotalRequestUnits” metric.  Please refer to [Database - List Metrics](https://docs.microsoft.com/en-us/rest/api/cosmos-db-resource-provider/2021-04-01-preview/database/list-metrics?tabs=HTTP).  Please let me know.

**Comment by kranthikumar-kvs-by** [comment]
@SaurabhSharma-MSFT, I have gone through the List Metric documentation you shared and formed this request -

https://management.azure.com/subscriptions/29dcf6d6-4c5c-4cd6-8198-c70cc7e368fb/resourceGroups/p-catman-pd-psr03-us-staging/providers/Microsoft.DocumentDB/databaseAccounts/o5319onx3642yef8lj6ughak/databases/sa-document-db/metrics?api-version=2021-04-01-preview&$filter=$filter=(name.value eq 'Total Requests')

But everytime I get BadRequest, please can you suggest what's wrong in this URL -

Error -
{
    "code": "BadRequest",
    "message": "Failed to parse query $filter=(value eq 'total requests')\r\nActivityId: f248684e-35e0-4be1-b006-99ddd3f9c82b, Microsoft.Azure.Documents.Common/2.14.0"
}

![image](https://user-images.githubusercontent.com/60686473/187480264-b80bfe58-08ae-4104-80e8-56c2cf3c9393.png)

Also please suggest how to get the "Normalized RU Consumption" value from this API call.

**Comment by SaurabhSharma-MSFT** [comment]
@kranthikumar-kvs-by Can you please use `name.value` i.e. `$filter=(name.value eq 'Total Requests')` and let me know if you still still have any problems.

**Comment by kranthikumar-kvs-by** [comment]
@SaurabhSharma-MSFT, I have used the same filter earlier as well and see the same error again.

`https://management.azure.com/subscriptions/29dcf6d6-4c5c-4cd6-8198-c70cc7e368fb/resourceGroups/p-catman-pd-psr03-us-staging/providers/Microsoft.DocumentDB/databaseAccounts/o5319onx3642yef8lj6ughak/databases/sa-document-db/metrics?api-version=2021-04-01-preview&$filter=$filter=(name.value eq 'Total Requests')`

![image](https://user-images.githubusercontent.com/60686473/189337377-3b97f640-866b-4abb-bf3f-513429f4446e.png)

Please suggest how to get the "Normalized RU Consumption" value from this API call.

**Comment by SaurabhSharma-MSFT** [comment]
@kranthikumar-kvs-by I could see the same happening for me as well. I am checking internally and get back to you.

**Comment by SaurabhSharma-MSFT** [comment]
@kranthikumar-kvs-by We have identified that when you pass - 

`(name.value eq 'Total Requests') and timeGrain eq duration'PT5M' and startTime eq '2022-09-20T00:00:00Z' and endTime eq '2022-09-21T00:00:00Z'`
into the $filter field, the command runs successfully. However, if I only specify the name.value part and omit timeGrain, it fails with bad syntax.  
I have escalated this internally to cosmosdb monitoring team to look into, however, you can continue using the REST endpoint with timeGrain to get the required results.  
Please let me know if you see any issues.  Thanks.

**Comment by kranthikumar-kvs-by** [comment]
This discuss was started to get the "Normalized RU Consumption" value from this API call. Which still I don't have. The one we discussed above was exploring the metric API.

Please suggest how to the get the "Normalized RU Consumption" using metric API.

**Comment by SaurabhSharma-MSFT** [comment]
@kranthikumar-kvs-by 
You can retrieve Normalized RU Consumption from the Metrics API as follows:
Go to [Metrics - List - REST API (Azure Monitor)](https://learn.microsoft.com/en-us/rest/api/monitor/metrics/list?tabs=HTTP#code-try-0) and click on Try It (in green). Fill in value for resource id of your Cosmos DB account and add header metricnames and set its value to "NormalizedRUConsumption". You may add other optional headers such as timespan, interval etc.
Example:
![image](https://user-images.githubusercontent.com/38112130/193662602-6fca4a5c-59f0-410f-82a2-fe66848652fb.png)
Hope this helps. Thanks.
