### ISSUE TITLE
[QUERY] What is the SDK equivalent of Set-AzWebApp?

### ISSUE THREAD

**Issue by josephsctan** [Azure/azure-sdk-for-net#30386]
### Library name and version

Azure.ResourceManager.AppService 1.0.0-beta-3

### Query/Question

Hi there,

I'am trying to attach a custom domain name to a App Service. 

In Powershell, this is how I would do it:

Set-AzWebApp -Name customdnsdev  -ResourceGroupName  TESTRESOURCE   -HostNames @('site1.contoso.com','customdnsdev.azurewebsites.net')

How do I do this using  Azure.ResourceManager.AppService?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
hi @josephsctan, you can achieve the custom binding by the following code
```csharp
  public void UpdateWebSiteCustomDomain(string resourceGroupName)
        {
            var resourceGroup = this.client.GetDefaultSubscription().GetResourceGroup(resourceGroupName).Value;
            var website = resourceGroup.GetWebSite("your website name").Value;
            HostNameBindingData data = new HostNameBindingData()
            {
                
            };
            var binding=website.GetSiteHostNameBindings().CreateOrUpdate(Azure.WaitUntil.Completed, "your domain", data).Value;

        }
```
Is this domain you purchased from external or from azure app service domain?

**Comment by josephsctan** [comment]
Thanks. The domain is external.

**Comment by xboxeer** [comment]
@josephsctan is there any other issue you have with the sample code? If no, feel free to let us know your overall feelings about our SDK in this [Survey](https://www.surveymonkey.com/r/YSYFMFF), thanks!

**Comment by josephsctan** [comment]
All good thanks. 

The SDK  pattern   [ GetXXXX().CreateOrUpdate() ] certainly takes some getting used to!
