### ISSUE TITLE
Typo in code sample

### ISSUE THREAD

**Issue by DominicArchual** [Azure/azure-sdk-for-net#30381]
The first line of the code sample should be changed from:
```
ItemRequestOption requestOptions = new ItemRequestOptions() { EnableContentResponseOnWrite = false };
```
To the following; noting the pluralization of `ItemRequestOptions`:
```
ItemRequestOptions requestOptions = new ItemRequestOptions() { EnableContentResponseOnWrite = false };
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e13fa94-4f50-b8bc-7789-681c6d3784e7
* Version Independent ID: 8c7f62fa-23bc-19d2-704d-0ef97264a6a7
* Content: [ItemRequestOptions.EnableContentResponseOnWrite Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.itemrequestoptions.enablecontentresponseonwrite?view=azure-dotnet#microsoft-azure-cosmos-itemrequestoptions-enablecontentresponseonwrite)
* Content Source: [xml/Microsoft.Azure.Cosmos/ItemRequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/ItemRequestOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@DominicArchual We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@DominicArchual The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
