### ISSUE TITLE
[QUERY] OrderBy support when migrating from Microsoft.Azure.Cosmos.Table package to Azure.Data.Tables

### ISSUE THREAD

**Issue by ashwinmayya** [Azure/azure-sdk-for-net#30423]
### Library name and version

Azure.Data.Tables 12.6.1

### Query/Question

We have been using Cosmos DB Table API in our .NET Core service for a while now. Recently we began looking into migrating from using the Microsoft.Azure.Cosmos.Table package to Azure.Data.Tables since the former has been deprecated.
However, it appears to us that OrderBy support is not available in the newer package, even though the older package and indeed the CosmosDb Table API itself appears to support it - see [here](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tablequery.orderby?view=azure-dotnet). This is a big issue for us as we are looking to add server-driven pagination support to some of our service APIs. We need our service APIs to return paginated responses containing entities in the order requested by the client.

Is there a way around this?

**Comment by jsquire** [comment]
Hi @ashwinmayya.  Thank you for reaching out and we regret that you're experiencing difficulties.  The Cosmos Table REST API that is used by `Azure.Data.Tables` does not support any kind of query functionality around grouping or ordering.  The legacy package made use of the Cosmos-specific binary API, which gives it access to functionality that is available only through that path.  

Unfortunately, using that in `Azure.Data.Tables` is not something that we'll be considering, as it would create a disparity in functionality between the Storage Tables and Cosmos Tables endpoints.

**Comment by ashwinmayya** [comment]
Thanks @jsquire. Do you have any recommendations on making this scenario work with Table API? Or is it just not the right choice for this scenario?

**Comment by jsquire** [comment]
The only thought that I'd have is to either keep using the Cosmos library or move away from the Tables API on Cosmos - which would basically obviate moving to the Cosmos library.
