### ISSUE TITLE
ACR: add troubleshooting guide

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#30426]
### Library name

Azure.Containers.ContainerRegistry

### Please describe the feature.

Add troubleshooting guide for ACR. 

Here's [Java TSG](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/containerregistry/azure-containers-containerregistry/TROUBLESHOOTING.md).

**Comment by pallavit** [comment]
@lmolkova thank you for creating the issue. 

@ShivangiReja TSGs have been added for all GA SDKs and .NET ACR SDK does not yet have it. Liudmila recently added them for Java and so it would be good to add them for .NET as well.

**Comment by ShivangiReja** [comment]
Sure! I'll add a TSG for .NET ACR.
