### ISSUE TITLE
Remove "ServiceToTest" parameters from pipeline

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-for-net#30433]
We currently use the params `ServiceToTest` for distinguishing the core and other pipelines, since we have to run all packages depends on core as well.

We have introduced a way to dynamically collect all packages which has dependency on target service. So the parameters are no longer needed.

The issue is to clean up the use of "ServiceToTest" 
The identified usages, mainly used for `CodeCheck.ps1`
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/ci.yml#L38
https://github.com/Azure/azure-sdk-for-net/blob/main/eng/pipelines/templates/stages/archetype-sdk-client.yml#L24
https://github.com/Azure/azure-sdk-for-net/blob/main/eng/pipelines/templates/stages/archetype-sdk-client.yml#L68
https://github.com/Azure/azure-sdk-for-net/blob/main/eng/pipelines/templates/jobs/ci.yml#L17
https://github.com/Azure/azure-sdk-for-net/blob/main/eng/pipelines/templates/jobs/ci.yml#L199

**Comment by pallavit** [comment]
> We have introduced a way to dynamically collect all packages which has dependency on target service. 

Curious - how do we identify it now? Is this based on assembly reference? I am curious if this also solves the problem where we were running track1 tests as part of the core pipeline which may not always be necessary.

**Comment by pallavit** [comment]
/cc: @sima-zhu does this also solves the following - #29271

**Comment by sima-zhu** [comment]
> /cc: @sima-zhu does this also solves the following - #29271

Yes, @pallavit We have excluded track 1 packages running the azure-core pipeline. 
For core pipeline, we implemented a new msbuild [target](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/service.proj#L84). Basically, the packages we fetched now satisfy two things:
1. The test package has a dependency on core.
2. The test package is client library.

I think we can close the https://github.com/Azure/azure-sdk-for-net/issues/29271, as it is being addressed by the PR: https://github.com/Azure/azure-sdk-for-net/pull/29957

**Comment by pallavit** [comment]
Thank you for sharing the details. I have closed the issue this your PR has now been merged.
