### ISSUE TITLE
[QUERY] FormRecognizer Key-Value-Pair with New Line

### ISSUE THREAD

**Issue by fugaku** [Azure/azure-sdk-for-net#30445]
### Library name and version

Azure.AI.FormRecognizer 4.0.0-beta.4

### Query/Question

I'm trying to use the Form Recognizer for my PDF files.
Currently using this with the "General Document" type.

It is detecting values, but when I try to access it using the SDK from the `DocumentKeyValuePair`, and accessing the `.Value.Content` property, I'm getting the content concatenated with spaces even though it is supposed to be several lines.

Can I get the content that is separated by new lines (`\n`) instead of concatenated by space ?

### Environment

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pallavit** [comment]
@kinelski please take a look.
