### ISSUE TITLE
[Core] Delete ConditionalRequestOptionsExtensions

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#30441]
[This code](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/core/Azure.Core/src/Shared/ConditionalRequestOptionsExtensions.cs) is made obsolete by the [ETag.ToString method](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/ETag.cs#L101) that has a format parameter. The ETag method is more robust as it handles weak ETag references as well as checking if the ETag value is already quoted before wrapping in quotes.

We should switch over any users of ConditionalRequestOptionsExtensions to instead use ETag.ToString("H") and then delete this class.
Currently App Configuration is the only SDK that uses this.

**Comment by pallavit** [comment]
Do we know who all use it today? It would be good the SDKs in the bug and add appropriate labels.

Also, curious - what are weak ETag references?

**Comment by JoshLove-msft** [comment]
> Do we know who all use it today? It would be good to add those SDKs in the bug and add appropriate labels.
> 
> Also, curious - what are weak ETag references?

I believe it is just App Config. That is why I added the App Config label which has since been removed.. 😆

**Comment by JoshLove-msft** [comment]
> Also, curious - what are weak ETag references?

My understanding is that weak ETags are used to represent semantic equivalence rather than byte for byte equality.

https://en.wikipedia.org/wiki/HTTP_ETag#Strong_and_weak_validation

**Comment by pallavit** [comment]
> I believe it is just App Config. That is why I added the App Config label which has since been removed.. 😆

Oops!

> My understanding is that weak ETags are used to represent semantic equivalence rather than byte for byte equality.

TIL, thanks!
