### ISSUE TITLE
[QUERY] TypeLoadException while using blobclientOptions.AddPolicy on Xamarin.iOS

### ISSUE THREAD

**Issue by bonniemathew** [Azure/azure-sdk-for-net#30444]
### Library name and version

Azure.Storage.Blobs 12.12.0

### Query/Question

Hi, 

I am trying to use the Azure Blob Storage SDK to list the contents of a directory on Xamarin.iOS. 

The following code fails. 
```
            var blobClientOptions = new BlobClientOptions(BlobClientOptions.ServiceVersion.V2021_06_08);
            try
            {
                HttpPipelinePolicy policy = new AuthTokenHttpPipelinePolicy(restApiClient);
                blobClientOptions.AddPolicy(policy, HttpPipelinePosition.PerRetry);
                blobClientOptions.AddPolicy(new ApimTracingHttpPipelinePolicy(restApiClient), HttpPipelinePosition.PerRetry);
                blobClientOptions.AddPolicy(new SasTokenHttpPipelinePolicy(sasCache), HttpPipelinePosition.PerRetry);
            } catch(Exception e)
            {
                Console.WriteLine(" Caught in exception, " + e.ToString());
            }
```

But the line
blobClientOptions.AddPolicy(policy, HttpPipelinePosition.PerRetry) fails on Xamarin.iOS. Its working fine on Xamarin.Android. 

This is the exception that I am getting. 

![](https://docs.microsoft.com/answers/storage/attachments/218877-image.png)

### Environment

Xamarin.iOS

**Comment by amnguye** [comment]
BlobClientOptions inherits the `AddPolicy` method from `ClientOptions` from the Azure.Core package.

Adding tag for Core

Also could you define what's occurring in your custom class for `AuthTokenHttpPipelinePolicy`, that doesn't seem like that belongs to Azure.Core or any of our other SDKs

**Comment by jsquire** [comment]
@bonniemathew:  I'm unable to reproduce this with the latest VS for Mac, XCode, and Blob Storage package.   As @amnguye mentioned, it would be very helpful to understand the code in your `AuthTokenHttpPipelinePolicy` implementation.
