### ISSUE TITLE
[BUG] Azure Function: AmpqException in logs for ServiceBus trigger

### ISSUE THREAD

**Issue by LwsSt** [Azure/azure-sdk-for-net#30464]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.5.1

### Describe the bug

Occasionally we're seeing a log message similar to the following in our logs:
```
An exception occurred while creating receive link for Identifier: {topic-name}/Subscriptions/{subscription-name}-{guid}. Error Message: 'Microsoft.Azure.Amqp.AmqpException: The service was unable to process the request; please retry the operation...'
```

There doesn't seem to be any pattern to when the error appears;
- The function app has a number of triggers listening to different Topics on the same Service Bus namespace - the log can appear on any of triggers
- Most are setup with a ConnectionString, one is setup using Managed Identities - the log can appear on either of them
- All Service Bus triggers in turn start a Durable task orchestration

The log message doesn't appear to count as a function execution (i.e. there's no AppInsights execution trigger around the time of the log).
Upon retrying, the triggers to appear to be processing the messages, and there aren't any messages appearing in the Deadletter queue.

### Expected behavior

Trigger does not log errors when operating normally

### Actual behavior

Full log message:

```
An exception occurred while creating receive link for Identifier:{topic-name}/Subscriptions/{subscription-name}-{guid}. Error Message: 'Microsoft.Azure.Amqp.AmqpException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:82beb435854845a5a9766c1c72ebba09_G7, SystemTracker:gateway7, Timestamp:2022-07-21T19:48:30
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenAmqpObjectAsync(AmqpObject target, TimeSpan timeout, CancellationToken cancellationToken, String entityPath)
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)'
```

### Reproduction Steps

The function is similar to this. However, it happens randomly. 
```cs
[FunctionName("MyFunctionName")]
public async Task MyServiceBusTriggerAsync(
	[ServiceBusTrigger("topic-name", "subscription-name", Connection = "ServiceBusConnection")]
	string myEvent,
	string correlationId,
	[DurableClient(TaskHub = "%HubName%")] IDurableOrchestrationClient client)
{
    await client.StartNewAsync("MyOrchestrationName", Guid.NewGuid().ToString());
}

```

### Environment

Azure Function App - Windows - Consumption Plan

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
This should probably be logged as verbose since it occurs within the scope of a retriable operation. If retries are exhausted, it would be logged as an error already.

**Comment by LwsSt** [comment]
@JoshLove-msft Thanks for your reply. 

Sounds like you're saying this is expected behaviour?

Can I just confirm that there's nothing we need to do, and we haven't configured anything incorrectly?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft Thanks for your reply.
> 
> Sounds like you're saying this is expected behaviour?
> 
> Can I just confirm that there's nothing we need to do, and we haven't configured anything incorrectly?

Yes, what you are seeing is expected from time to time, but I think we can change the log level for this event so that it is not logged as an error.

**Comment by JoshLove-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/31477
