### ISSUE TITLE
AzureCredentials should implement an interface.

### ISSUE THREAD

**Issue by twitchax** [Azure/azure-sdk-for-net#3046]
Developers may have other means of authentication, such as an access token.

As of today, `Azure.Authenticate` takes an instance of `AzureCredentials`.  The pertinent functionality of `AzureCredentials` should be abstracted to an interface so developers can implement the functionality themselves.

**Comment by martinsawicki** [comment]
fair point, actually this is already possible in Java, we didn't completely port it to .NET

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#58
