### ISSUE TITLE
[QUERY] How to specify maxMessages for ServiceBusProcessor?

### ISSUE THREAD

**Issue by bastyuchenko** [Azure/azure-sdk-for-net#30466]
### Library name and version

Azure.Messaging.ServiceBus 7.9.0

### Query/Question

Hi,
It is possible to specify _maxMessages_ if we use ServiceBusReceiver/ServiceBusSessionReceiver

```
ServiceBusReceiver receiver = client.CreateReceiver(queueName);
IReadOnlyList<ServiceBusReceivedMessage> receivedMessages = await receiver.ReceiveMessagesAsync(maxMessages: 2);
```

But I haven't found a way to specify _maxMessages_ for ServiceBusProcessor/ServiceBusSessionProcessor.
Why this option is not available for ServiceBusProcessor/ServiceBusSessionProcessor?

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
maxMessages cannot be configured when using the processor, as messages are delivered one at a time to your message handler. You can control the throughput by changing the maxConcurrentCalls value.
