### ISSUE TITLE
[FEATURE REQ] TokenCredentialOptions initialization from IConfiguration

### ISSUE THREAD

**Issue by smichtch** [Azure/azure-sdk-for-net#30499]
### Library name

Azure.Identity

### Please describe the feature.

Various `TokenCredentialOptions` implementations like `DefaultAzureCredentialOptions` should have an option to initialize from an `Microsoft.Extensions.Configuration.IConfiguration` instance instead of always calling the static `Environment.GetEnvironmentVariable()` method. Replacing the static environment variable container with injected dependencies would improve testability for application authors.

To do this today applications code needs to reference the environment variables explicitly which increases coupling:
```
new DefaultAzureCredential(new DefaultAzureCredentialOptions
{
    ManagedIdentityClientId = configuration["AZURE_CLIENT_ID"],
    ...
})
```

To avoid adding new dependency (`Microsoft.Extensions.Configuration.Abstractions`) in `Azure.Identity` the library could use a generic delegate like `Func<string, string> readEnvironmentVariable` instead of `IConfiguration`.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by slaneyrw** [comment]
Not sure if this is related or not, but when I use a ServiceBus trigger with a fullyQualifiedNamespace setting, all the internal dependency injection ( which I cannot influence ) ends up using the default DefaultAzureCredential ( from Microsoft.Extensions.Azure.AzureClientsGlobalOptions ).

When doing this from a local development instance, the default chain uses a set of hardcoded TokenCredential sources, most of which fail until I get to the one that works... in our case the VisualStudioCredential or AzureCliCredential ( depending on whether we're running inside or outside VS ).

I want to be able to control which credential token we call by setting the DefaultAzureCredentialOptions.

My native approach would be to check the default AzureClientsGlobalOptions.CredentialFactory to resolve the default DefaultAzureCredential from the service provider, or to resolve/inject IOptions<DefaultAzureCredentialOptions> at either the AzureClientsGlobalOptions or Microsoft.Extensions.Azure.AzureComponentFactoryImpl level.  Both are internal so no API change it required.

On a separate note, it's frustrating for libraries to use the DI system, but then give no way of consumers to alter the behaviour.  You might as well hardcode the dependency graph!
