### ISSUE TITLE
[BUG] ReceiveMessageAsync may skip first queue item after PeekMessagesAsync

### ISSUE THREAD

**Issue by Crossbow78** [Azure/azure-sdk-for-net#30492]
### Library name and version

Azure.Messaging.ServiceBus 7.8.1

### Describe the bug

In our use-case we _peek_ the queue to find the cut-off point of the messages that we want to _receive_.

So our application has the following structure:
* Instantiate a `ServiceBusClient` and a `ServiceBusReceiver`
* Call `PeekMessageAsync` to receive a batch of 64 items
* Call `ReceiveMessageAsync` repeatedly to process exactly the right number of items

Generally this works perfectly, but we sometimes™ observe that the first call to `ReceiveMessageAsync` receives the _second_ item in the queue, based on its sequence number.

As an example: if the queue contains items with the following sequence numbers: 1, 2, 3, 4
Our peek would see items 1, 2, 3, 4, and we would then process (receive) messages 2, 3, 4, thus leaving item 1 on the queue. From a _queue_ philosophy this shouldn't be possible.

![ServiceBusReceiver-bug](https://user-images.githubusercontent.com/7549753/184368606-6d3af0d0-81f1-4834-8160-548537de7df7.png)

### Expected behavior

ReceiveMessageAsync always receives the 'earliest' item from the queue.

### Actual behavior

ReceiveMessageAsync occassionally skips the first item, and returns the second item instead.

### Reproduction Steps

```
var client = new ServiceBusClient(_configuration.ConnectionString);
var receiver = client.CreateReceiver(_configuration.TriggerPoisonQueue, new ServiceBusReceiverOptions
            {
                ReceiveMode = ServiceBusReceiveMode.PeekLock,
                PrefetchCount = 1,
            })

var peekedMessages = await receiver.PeekMessagesAsync(64);
var receivedMessage = await receiver.ReceiveMessageAsync(TimeSpan.FromSeconds(1));

// Repeat, and each time assert that peekedMessages.First().SequenceNumber == receivedMessage.SequenceNumber
```

### Environment

* .NET 6
* Azure Function v4 (also reproducible with the local function host from Azure Function Core Tools)

**Comment by jsquire** [comment]
Hi @Crossbow78.   Thank you for reaching out and we regret that you're experiencing difficulties.

Does this behavior repro when you're not setting the `PrefetchCount`?

**Comment by Crossbow78** [comment]
I tried reproducing this with the `PrefetchCount` set to either 0 or 8, but was unable to with 30+ attempts. It's always hard to draw solid conclusions with these "random" occurrences, but when I change it back to 1, it occurs fairly reliably within the first 10 attempts.

You actually made me wonder why we set it to 1 anyway, since that value doesn't make much sense.

We'll leave it to 0 in our configuration, but I feel the issue still applies if the library allows this configuration.

**Comment by C485** [comment]
Hi all,

I've almost same issue with PeekMessageAsync. 
Sometimes it skips newly added messages(they just sit there ...), I can see them in ServiceBusExplorer(I've looked in Service Bus Explorer and it uses old lib for Service Bus).
I don't know about OP service bus configuration but I have topics with:
1. Batched Operations
2. Partitioning
and subscription has:
1. Batched Operations
2. Requires session

Code is super simple:

https://pastebin.com/raw/U0LGGXCF

What I tried without success:
1. setting PrefetchCount to zero, to number like 600 or completely removing it.
3. skipped sequence number.
4. changed code to create Session receiver and receiving messages from this object instead aka AcceptNextSessionAsync.

There is no information about any errors or something, it just returns null from PeekMessageAsync.
5. changed code to use PeekMessagesAsync
6. recreated ServiceBusClient and ServiceBusReceiver only keeping SequenceNumber without restarting program

What is funny is that it sometimes works.
Message is finally received in this scenarios:
1. Program restart

It looks like there is something that skips these messages.

Library name: Azure.Messaging.ServiceBus
Version: 7.10.0

@jsquire

**Comment by C485** [comment]
You'll not believe in it but I managed to make it work, by increasing pooling rate in my class from 3000ms to 300ms.
It looks like when PeekMessageAsync is not called by some time it kills the connection or something, but in this case we should get an exception, right?

**Comment by JoshLove-msft** [comment]
Regarding the initial issue here, what might be happening is that the receiver is timing out before the message reaches the client. This would cause it to be locked on the service but not get delivered in order as the receiver has already stopped waiting. When using Prefetch, additional messages are not requested until you complete or otherwise settle the received message. So that could be causing issues. It is hard to tell without a complete repro of the issue that shows how messages are being received and settled.

**Comment by JoshLove-msft** [comment]
@C485, are you essentially peeking messages across different sessions with a `ServiceBusReceiver`? I'm not sure if FIFO is guaranteed across sessions.
