### ISSUE TITLE
Determining servicebus connection at runtime

### ISSUE THREAD

**Issue by phatcher** [Azure/azure-sdk-for-net#30509]
We deploy our function apps as docker containers and store secrets/connection string in a key vault, associating each environment's key vault to the function app in `ConfigureAppConfiguration`.

However, with the managed identity configuration the required name is "*servicebus*__fullyQualifiedNamespace" and "_" is not a valid character in a key vault secret name.

What is the recommended solution to configuring the service bus connection string at runtime?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dab2626a-9579-fe2b-f11b-0ffec8666fcf
* Version Independent ID: 9f48d2bc-eda0-57e8-1ecd-a2489f1cb862
* Content: [Azure WebJobs Service Bus client library for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre)
* Content Source: [api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre.md)
* Service: **webjobs**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @phatcher,
When using Key Vault you would need to use ':' or '/' in place of the underscore. This [doc](https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=blob#connection-values) provides more details.
