### ISSUE TITLE
[QUERY]POSThttps://management.azure.com/subscriptions/8ec2a5ad-1b40-4ce4-972d-c6fc70a3e299/providers/Microsoft.Devices/checkNameAvailability?api-version=2022-04-30-preview

### ISSUE THREAD

**Issue by firstaye-zz** [Azure/azure-sdk-for-net#30500]
### Library name and version

Microsoft.devices api-version=2022-04-30-preview

### Query/Question

When using the SDK sending the request to `/subscriptions/8ec2a5ad-1b40-4ce4-972d-c6fc70a3e299/providers/Microsoft.Devices/checkNameAvailability?api-version=2022-04-30-preview`
It will throw the exception says `System.Collections.Generic..KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /subscriptions/8ec2a5ad-1b40-4ce4-972d-c6fc70a3e299/providers/Microsoft.Devices/checkNameAvailability?api-version=2022-04-30-preview'. Calling method Item().`

But it only works when I send the request as version 2021-07-01.

### Environment

Visual Studio Version 17.3.0

Hosting platform or OS and .NET runtime version:
global.json file:
  C:\Users\huangc\source\repos\azure-sdk-for-net\global.json

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  6.0.303 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Hi @firstaye-zz.  Thank you for reaching out and we regret that you're experiencing difficulties.   Unfortunately, I'm not able to determine how we can help from your description.   Would you please let us know which Azure SDK package and version your using?   Could you also please include a snippet of your code to demonstrate how you're using the SDK?

**Comment by jsquire** [comment]
Due to the missing information, this is not actionable and cannot be triaged.   Closing.
