### ISSUE TITLE
Database.ReadAsync page could be clearer about how the DatabaseResponse returned is implicitly converted to a DatabaseProperties object

### ISSUE THREAD

**Issue by AnotherSadGit** [Azure/azure-sdk-for-net#30503]
The Database.ReadAsync Docs page appears contradictory and confusing.  The summary states:

> Reads a DatabaseProperties from the Azure Cosmos service as an asynchronous operation.

However, the definition shows the ReadAsync method returning a DatabaseResponse object, not a DatabaseProperties object:

`public abstract System.Threading.Tasks.Task<Microsoft.Azure.Cosmos.DatabaseResponse> ReadAsync(...)`

And the example on the page also shows ReadAsync returning a DatabaseResponse object:

`DatabaseResponse response = await database.ReadAsync();`

After some digging into Docs pages for DatabaseResponse and Response<T> I can see there is an implicit operator that converts from DatabaseResponse to DatabaseProperties, which explains the apparent contradiction in the ReadAsync Docs page.  

I think it would be useful to add a note to the ReadAsync page explaining this implicit conversion from DatabaseResponse to DatabaseProperties, or to modify the example to something like:

```
// ReadAsync returns a DatabaseResponse object.  However, there is an implicit conversion from 
// DatabaseResponse to DatabaseProperties.
DatabaseProperties properties = await database.ReadAsync();
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a56cb2c-be4c-b94d-baa7-5f497bb4e147
* Version Independent ID: 4bf1e5fa-29f6-b7b2-dce4-d431f8868587
* Content: [Database.ReadAsync(RequestOptions, CancellationToken) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.database.readasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Database.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Database.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@AnotherSadGit We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@AnotherSadGit The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
