### ISSUE TITLE
IDatabases.List() hangs

### ISSUE THREAD

**Issue by mloeffen** [Azure/azure-sdk-for-net#3050]
I'm trying to manage azure databases from our own application targeting .NET Framework 4.6.2 using Microsoft.Azure.Management.Sql.Fluent nuget package version 1.0.0-beta50. When trying to access the databases to check if a database already exists, it just hangs.

var sqlServer = azure.SqlServers.List().FirstOrDefault(.....); // works
var databases = sqlServer.Databases.List(); // **hangs**
await sqlServer.Databases.Define(databaseName).CreateAsync(); // works
await sqlServer.Databases.DeleteAsync(databaseName); // works

For logging into Azure I've added an auth-file with a service-principle which is (for now) Owner to the subscription. Any idea what's going on here?

**Comment by martinsawicki** [comment]
after enhancing the [unit test for CRUDing Databases](https://github.com/Azure/azure-sdk-for-net/pull/3148/files#diff-3fc360f44e7e85bdac4989bbd2e762b2), I don't see a problem with `.List()` so either this got fixed in the latest v1.0.0 (not beta) release, or we need a more specific repro.
