### ISSUE TITLE
Incorrect casing in deserialize SubnetData for property "applicationGatewayIpConfigurations"

### ISSUE THREAD

**Issue by techrazor** [Azure/azure-sdk-for-net#30516]
Hello, when using the Azure.ResourceManager.Network sdk to list Virtual Networks, the sdk is not deserializing the applicationGatewayIPConfigurations property on the Virtual Network Subnet.

Example:
```c#
foreach (var virtualNetwork in azureSubscription.GetVirtualNetworks())
{
    foreach (var subnet in virtualNetwork.Data.Subnets)
    {
        // The subnet.ApplicationGatewayIPConfigurations property is empty because it is looking for an invalid case.
        // incorrect: "applicationGatewayIpConfigurations" vs  correct: "applicationGatewayIPConfigurations"
        foreach (var agwipc in subnet.ApplicationGatewayIPConfigurations)
        {
            Console.WriteLine(agwipc.Id);
        }
    }
}
```

https://github.com/Azure/azure-sdk-for-net/blob/204ffa2e23e4bfde995ced0c846c53ef9ea68402/sdk/network/Azure.ResourceManager.Network/src/Generated/Models/SubnetData.Serialization.cs#L424

Here is a snippet from the Azure REST API showing the current casing in use:
```json
{
  "name": "subnet-agw",
  "id": "/subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.Network/virtualNetworks/<vnet-name>/subnets/subnet-agw",
  "properties": {
      "applicationGatewayIPConfigurations": [
          {
              "id": "/subscriptions/<sub-id>/resourceGroups/<rg-name>/providers/Microsoft.Network/applicationGateways/<agw-name>/gatewayIPConfigurations/appGatewayIpConfig"
          }
      ]
  },
  "type": "Microsoft.Network/virtualNetworks/subnets"
}
```

**Comment by pallavit** [comment]
Thank you for reporting the issue, routing it to the team member best able to assist you.
/cc: @ArthurMa1978

**Comment by xboxeer** [comment]
@james-daugherty thanks for reporting this, this is a swagger issue and raised issue in swagger repo https://github.com/Azure/azure-rest-api-specs/issues/20256

**Comment by james-daugherty** [comment]
Thank you @xboxeer

**Comment by techrazor** [comment]
@xboxeer, do you know why they cancelled your open issue in the Azure/azure-rest-api-specs repo?

**Comment by xboxeer** [comment]
> @xboxeer Elendil Zheng FTE, do you know why they cancelled your open issue in the Azure/azure-rest-api-specs repo?

closed by an internal eng system issue, I've reopened that issue.

**Comment by dvbb** [comment]
We now have a PR to fix this: https://github.com/Azure/azure-rest-api-specs/pull/22875/files

**Comment by dvbb** [comment]
This issue has been fixed in the latest release version `Azure.ResourceManager.Network 1.2.0`
