### ISSUE TITLE
[QUERY] Normalizers are not working with SearchFields

### ISSUE THREAD

**Issue by irrinna1** [Azure/azure-sdk-for-net#30528]
### Library name and version

Azure.Search.Documents 11.4.0-beta9

### Query/Question

Normalizers are not applied when SearchFields are used, ex.

SearchOptions options = new SearchOptions()
{
    Filter = filter,
    SearchMode = SearchMode.All,
    QueryType = SearchQueryType.Simple
};
options.SearchFields.Add("searchableTitle");

If SearchFields are not added and azure search is working with the deafult selected in the indexer (Content and Metadata), then normalizer is working fine. If SearchFields are used, then the normalizer is no longer applied.

Could you please help resolve the issue?

### Environment

Windows 10 .NET 6
Visual Studio 17.1.0 Preview 1.1

**Comment by ShivangiReja** [comment]
Hi @irrinna1 - I added [this](https://github.com/ShivangiReja/azure-sdk-for-net/blob/Test_SearchField/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchTests.cs#L274-L290) test case for normalizer with SearchField and it is working fine for me.

In my test case, I added normalizer for [address/city](https://github.com/ShivangiReja/azure-sdk-for-net/blob/Test_SearchField/sdk/search/Azure.Search.Documents/tests/Utilities/SearchResources.Data.cs#L54) field and added filter `"address/city eq 'New york'"` with SearchField  `address/city`. It gives the correct result with [HotelId:5](https://github.com/ShivangiReja/azure-sdk-for-net/blob/Test_SearchField/sdk/search/Azure.Search.Documents/tests/Utilities/SearchResources.Data.cs#L183) where city name is `"NEW YORK"` and [HotelId:9](https://github.com/ShivangiReja/azure-sdk-for-net/blob/Test_SearchField/sdk/search/Azure.Search.Documents/tests/Utilities/SearchResources.Data.cs#L225) where city name is `"New York"`.

**Comment by irrinna1** [comment]
/unresolve Hi @ShivangiReja, thank you for your answer. I have a specific case that I noticed it is not working for.
I use Elision normalizer on a searchable field, to be more concrete the field has this options -  [SearchableField(AnalyzerName = LexicalAnalyzerName.Values.EnMicrosoft, NormalizerName = LexicalNormalizerName.Values.Elision), SimpleField(IsFilterable = true, IsSortable = true, IsFacetable = true), JsonPropertyName("searchableTitle")]. In the index json it looking like this:
 {
      "name": "searchableTitle",
      "type": "Edm.String",
      "searchable": true,
      "filterable": true,
      "retrievable": true,
      "sortable": true,
      "facetable": true,
      "key": false,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "analyzer": "en.microsoft",
      "normalizer": "elision",
      "synonymMaps": []
    },
    If I search for word "d'octobre", then it finds successfully results containg both "d'octobre" and "octobre" in searchableTitle field and content metadata. But if I search only in searchableTitle field (options.SearchFields.Add("searchableTitle")) for "d'octobre", then it doesn`t find "octobre", finds only "d'octobre".
Could you please advise if there is something with the provided settings? Thank you in advance.

**Comment by ShivangiReja** [comment]
@irrinna1 - Thank you for providing the sample!

I tried to reflect your case and it worked fine for me. Here are steps I followed:
* In my "hotelName" field, I've applied the similar attributes as your sample. Please check the attributes [here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/9deb5001131e9611171d14cd3a829bc6cc4f7c77/sdk/search/Azure.Search.Documents/tests/Utilities/SearchResources.Data.cs#L38).
* I've updated "HotelName" for "[HotelId:5](https://github.com/ShivangiReja/azure-sdk-for-net/blob/9deb5001131e9611171d14cd3a829bc6cc4f7c77/sdk/search/Azure.Search.Documents/tests/Utilities/SearchResources.Data.cs#L171)" as `d'octobre` and "[HotelId:9](https://github.com/ShivangiReja/azure-sdk-for-net/blob/9deb5001131e9611171d14cd3a829bc6cc4f7c77/sdk/search/Azure.Search.Documents/tests/Utilities/SearchResources.Data.cs#L211)" as `octobre`.
* [Here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/9deb5001131e9611171d14cd3a829bc6cc4f7c77/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchTests.cs#L275) I added a test case with `Filter = "hotelName eq 'd''octobre'"` which results [HotelId:5 and HotelId:9](https://github.com/ShivangiReja/azure-sdk-for-net/blob/9deb5001131e9611171d14cd3a829bc6cc4f7c77/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchTests.cs#L285) as expected.
* [Here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/9deb5001131e9611171d14cd3a829bc6cc4f7c77/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchTests.cs#L292) I added one more test case with `Filter = "hotelName eq 'd''octobre'"` and `SearchFields = new[] { "hotelName" }` and it gives the same result as above test case, which is [HotelId:5 and HotelId:9](https://github.com/ShivangiReja/azure-sdk-for-net/blob/9deb5001131e9611171d14cd3a829bc6cc4f7c77/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchTests.cs#L303).

Please let me know if this reflects your case or I'm missing something.

**Comment by ShivangiReja** [comment]
ohhh, so you're not using filters...Normalizers only work if you apply filters, facets or orderby in a field. That's the reason my samples are working as I suggested [here](https://github.com/Azure/azure-sdk-for-net/issues/30528#issuecomment-1239797758). For more details on normalizers, please refer the documentation https://docs.microsoft.com/en-us/azure/search/search-normalizers.

[Here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/c81ae3b6fdc5dbe0999752026f3d44a1fd03a1a0/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchTests.cs#L310-L344) are test cases which reflect your case - If I don't use filter and call search method with serachText `"d'octobre"`, then both the test cases returns HotelId:5 which has HotelName `d'octobre` and this is expected . It really doesn't make any difference in the result whether you pass `SearchFields = new[] { "hotelName" }` ot not.

**Comment by ShivangiReja** [comment]
In case you don't want to use filter, then normalizers won't work but you can apply custom analyzer. Normalizers and analyzers are very similar but analyzers work on searches and normalizers work on filtering/faceting/sorting.
 
There's also an elision token filter you could apply as part of a custom analyzer: [Add custom analyzers to string fields - Azure Cognitive Search | Microsoft Docs](https://docs.microsoft.com/en-us/azure/search/index-add-custom-analyzers). This would be how you could use the same analyzer but also include the token filter:

```json
    "analyzers": [
        {
            "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
            "tokenizer": "microsoft_language_stemming_tokenizer",
            "tokenFilters": ["elision"],
            "name": "elision-analyzer"
        }
    ],
```

For your reference - [here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/e9b26a2531d4f2c907d6c3b2659a096bf96e0dac/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchTests.cs#L311-L350) is the test case for custom analyzer and [here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/e9b26a2531d4f2c907d6c3b2659a096bf96e0dac/sdk/search/Azure.Search.Documents/tests/DocumentOperations/SearchTests.cs#L353-L393) is the test case for custom analyzer with SearchField both returns hotelId:5 and HotelId:9.

**Comment by irrinna1** [comment]
Hi @ShivangiReja, thank you for the explanation. I have managed to make it working using custom analyzer with elision token filter.
Thanks again!
