### ISSUE TITLE
Fix create-GithubRelease job

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#3052]
### Description

Create-GithubRelease should be creating releases for each publishing job.  It looks like it last worked on 2/17.  Need to fix it and ensure that, if it fails, the build fails.

Consider wihether to backfill releases based on tag information in the publish jobs.

### Cost: 2

**Comment by cormacpayne** [comment]
Script and configurations have been updated to fix this problem. Still need to consider whether or not we need to backfill releases that were missed.

**Comment by markcowl** [comment]
Fixed.
