### ISSUE TITLE
[QUERY] How to deploy an application to an App Service using the new Management libraries?

### ISSUE THREAD

**Issue by TechWatching** [Azure/azure-sdk-for-net#30520]
### Library name and version

Azure.ResourceManager.AppService 1.0.0

### Query/Question

I have packaged a .NET application (in a zip file) that I want to deploy to an existing App Service. For that, I want to use the new Azure Management libraries in .NET.

I have the following code that retrieve my existing App Service:

```csharp
 var client = new ArmClient(new DefaultAzureCredential());
 var resource = client.GetWebSiteResource(new ResourceIdentifier("/subscriptions/xxx/resourceGroups/xxxx/providers/Microsoft.Web/sites/xxxxx");
 WebSiteResource webSite = await resource.GetAsync();
```` 

But I can't find a method "Deploy" or something like that to do the web deploy or the zip deploy of my package.
How can I do that with the new Management Libraries?

With the previous SDK, I found some [sample](https://github.com/Azure-Samples/app-service-dotnet-configure-deployment-sources-for-web-apps) showing how to use a `Deploy` method but I can't find anything on the objects of the new SDK.

**Comment by pallavit** [comment]
Thank you for reaching out. I have routed your question to the team member best able to assist you. /cc: @ArthurMa1978

**Comment by xboxeer** [comment]
Hi @TechWatching I suppose you are going to use FTP deployment since you mentioned there is a zip file in your local, am I right? If you look at the sample, it does nothing more but uploading a local zip file to the web apps, [Utilities.UploadFileToFTP](https://github.com/Azure-Samples/app-service-dotnet-configure-deployment-sources-for-web-apps/blob/master/Common/Utilities.cs#L2824), and this method relies on a 3rd party FTP library. So that's why you are unable to find a "deploy through a local zip" method directly in SDK
Since this local zip file upload to FTP deploy is totally nothing to do with SDK itself, you can directly use the sample code to upload your zip file to your web apps FTP endpoint without any dependency on azure SDK

**Comment by TechWatching** [comment]
Not necessarily, I don't really care about the deployment method (FTP, zip deploy, web deploy) but I want to be able to deploy my zip package to the web app and run it from package. I am interested in using Azure SDK because I am automating that using C# code, and it means I can use things like `new DefaultAzureCredentials()` from Azure.Identity.  In the previous Azure Management library, from what I understand from the sample, there was methods to deploy a package using web deploy:

![image](https://user-images.githubusercontent.com/15186176/184900700-898c8b96-65bd-4540-b075-9ea33e06d8c4.png)

If I use Azure CLI,  I can deploy using the following command: `az webapp deployment source config-zip --resource-group <group-name> --name <app-name> --src <filename>.zip` so I was expecting do be able to do the same thing using the new Azure Management libaries.

Same, if I use the AzureWebApp task from Azure DevOps in a CI/CD pipeline, it will deploy for me my package. I understand that behind the scenes it is is calling the Azure APIs (Kudu and everything). So I don't min having to write some C# lines to do the deployment or to restart the app when it's deployed but I would expect the management library to help me with that, with authentication and everything, and not manually make the HTTP requests.

To give you a bit of context I am using [Nuke buil](https://github.com/nuke-build/nuke) to build and deploy my code using C#. That is why Azure Management libraries seem an excellent fit to handle the deployment part.

**Comment by xboxeer** [comment]
@TechWatching the sample uses fluent style SDK while in our new SDK we do not support the fluent SDK anymore -> See our new SDK design guidance here: https://azure.github.io/azure-sdk/general_introduction.html 
AppService SDK is still evolving so the sample is not ready yet, I've created a new [issue](https://github.com/Azure/azure-sdk-for-net/issues/30577) to track this. Meanwhile, feel free to let us know what other samples you think is necessary for using the new SDK, or if you have any other general feedback to our SDK, let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)

**Comment by TechWatching** [comment]
Submitting the survey does not work :(
![image](https://user-images.githubusercontent.com/15186176/185484281-5658391a-9084-4e72-a1a2-c47a5dd48bab.png)

**Comment by xboxeer** [comment]
> Submitting the survey does not work :( ![image](https://user-images.githubusercontent.com/15186176/185484281-5658391a-9084-4e72-a1a2-c47a5dd48bab.png)

I've made some updates and that question should not block you now

**Comment by Yao725** [comment]
Close this issue as we already have #30577 to track this.
