### ISSUE TITLE
[QUERY] FunctionApp doesnt complete Polly retry

### ISSUE THREAD

**Issue by RDavis3000** [Azure/azure-sdk-for-net#30524]
### Library name and version

Microsoft.NET.Sdk.Functions 4.1.9

### Query/Question

Hi,
I have a function app writing to MS SQL with a Polly retry wrapper for Timeouts (and other errors).
Running the Kusto in Logs:
```

// All telemetry for Operation ID: fb7ad9d18e6a90befd4cab0b8330bd2b
union *
// Apply filters
| where timestamp > datetime("2022-08-14T08:00:00.000Z") and timestamp < datetime("2022-08-17T08:10:00.000Z")
| where operation_Id == "fb7ad9d18e6a90befd4cab0b8330bd2b"
```

Isolates an example of the issue I am experiencing.
The function invocation is running fine, hits a 1:33s timeout at 2022-08-15T08:07:17.5303591Z, and then just never comes back.

Thousands of these are running fine, I've confirmed that other function invocations were running and retrying at about the same time and completed ok, so I don't think its my implementation.

I checked into the function host and the last trace I can find is 2022-08-15T08:08:41.3915566Z, which seems to suggest that the host was shutdown before the retry timer was due to end at approx. 2022-08-15T08:08:50.5303591Z

Can you tell me what happened to my invocation and how to prevent it happening again? 
In this instance would the function retry? (I have retry configured in host.json)
Having done some more reading, it seems like I should implement graceful shutdown code leveraging the cancellation token passed to the function, does that sound correct?

### Environment

Project Assemblies:
Microsoft.Azure.Webjobs.Extensions.EventGrid 3.1.0
Microsoft.NET.Sdk.Functions 4.1.9
Microsoft.Azure.Functions.Extensions 1.1.0

Running Azure Functions runtime ~4

dotnet --info
.NET SDK (reflecting any global.json):
Version: 6.0.303
Commit: 7494fee64a

Runtime Environment:
OS Name: Windows
OS Version: 10.0.22000
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.303\

global.json file:
Not found

Host:
Version: 6.0.8
Architecture: x64
Commit: 55fb7ef977

.NET SDKs installed:
3.1.422 [C:\Program Files\dotnet\sdk]
5.0.409 [C:\Program Files\dotnet\sdk]
6.0.301 [C:\Program Files\dotnet\sdk]
6.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the Azure Functions host and associated extensions are maintained as [#8714](https://github.com/Azure/azure-functions-host/issues/8714).
