### ISSUE TITLE
[BUG] Custom Model - Table Field - Multiple pages returning fieldname_{Guid} and some tables are missing

### ISSUE THREAD

**Issue by rutter-foremostgolf** [Azure/azure-sdk-for-net#30535]
### Library name and version

Azure.AI.FormRecognizer 4.0.0-beta.3

### Describe the bug

I've created a custom model with a table property.
I've trained the model with multiple page documents.
I've tested a multiple page document with a table that spans multiple pages.
In the studio all the tables come together under the custom property name.
That works well.
![image](https://user-images.githubusercontent.com/105347135/184905999-7198d510-a57a-4935-b384-d0f941c6a138.png)

But when the document is processed by the API I get two fields with a suffixed Guid.
And only two not seven.
![image](https://user-images.githubusercontent.com/105347135/184906551-e5d72bc3-9d94-43f6-8bf0-792e8a18e7e2.png)

There are seven tables in the AnalyzeResult model
![image](https://user-images.githubusercontent.com/105347135/184906828-3f2a22af-2991-45e8-82ff-5084ee52f77b.png)

### Expected behavior

When using the same document.
The API found the same amount of tables as the studio and combined the tables into one property.

### Actual behavior

The Studio response is different and tables are missing

### Reproduction Steps

Add a custom table field the custom model and train.
Ensure that a test of the model returns results (In Form Recognizer Studio)
Use Nuget package to call API and inspect values.

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.303
 Commit:    7494fee64a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.303\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  3.1.422 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.409 [C:\Program Files\dotnet\sdk]
  6.0.301 [C:\Program Files\dotnet\sdk]
  6.0.303 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by rutter-foremostgolf** [comment]
Just saw another post and someone was referring to Beta.5
I've updated to that version and the issue has gone.

All my items appear under one property and will the expected number of lines in the table.
![image](https://user-images.githubusercontent.com/105347135/185071296-771f7785-004d-442a-a872-6c5f0553e438.png)

Thank you. I'll close this issue.
