### ISSUE TITLE
[BUG] Using batch delete on a blob with more than 1 version fails when there is a lease present

### ISSUE THREAD

**Issue by RohanRao27** [Azure/azure-sdk-for-net#30537]
### Library name and version

Azure.Storage.Blobs 12.13.0 & Azure.Storage.Blobs.Batch 12.10.0

### Describe the bug

If you call the batch DeleteBlob() with the specified LeaseID for the file, there is an exception thrown after the batch is submitted:

`Status: 412 (There is currently no lease on the blob.)`

### Expected behavior

Delete should succeed, with no exceptions thrown

### Actual behavior

Delete fails with Status 412 (There is currently no lease on the blob)

### Reproduction Steps

1. Upload a new file to Blob Storage
2. Create a new version of the file (in this case, I updated the metadata, by adding a key/value pair)
3. Acquire a Lease on the File
4. Use the BlobBatchClient to batch delete this file with the lease ID:
```
BlobBatchClient batchClient = _client.GetBlobBatchClient();
BlobBatch batch = batchClient.CreateBatch();
batch.DeleteBlob(blobUri, conditions: new BlobRequestConditions()
                    {
                        LeaseId = leaseId
                    });
await batchClient.SubmitBatchAsync(batch, throwOnAnyFailure: true);
```

The exception thrown is as follows:

```
System.AggregateException: '1 batch operation(s) failed. (There is currently no lease on the blob.
RequestId:07579938-a01e-003f-807b-b1c9ba1e3472
Time:2022-08-16T14:21:07.9125816Z
Status: 412 (There is currently no lease on the blob.)
ErrorCode: LeaseNotPresentWithBlobOperation
```

Note: Using the same steps 1-3 but using the regular delete API (non-batching) with the lease ID, the call succeeds, and the file is deleted.

### Environment

OS: Windows 10, .NET 6
IDE: Visual Studio Professional 2022 Version 17.2.5

**Comment by amnguye** [comment]
Sorry for the late reply. Does not look like an SDK bug because this is a specific scenario regarding versioning and leases.

Looks like the SDK is sending the request correctly with the lease id on a version blob. The only difference is that the blob has more than one version.

Will follow up on the github issue after more information is found with the possible service issue.

**Comment by navba-MSFT** [comment]
@RohanRao27 I was able to get this working. I am sending you the sample code along with the package versions used. Hope this helps.

>Azure.Storage.Blobs --> 12.14.1
Azure.Storage.Blobs.Batch --> 12.11.0


```
            BlobServiceClient client = new BlobServiceClient(accountUri, sharedKeyCredential);
            BlobContainerClient container = client.GetBlobContainerClient("MyContainerName");
            BlobClient blobName = container.GetBlobClient("MyBlobName");

            BlobBatchClient batchClient = client.GetBlobBatchClient();

            BlobBatch blobBatch = batchClient.CreateBatch();

            try
            {
                blobBatch.DeleteBlob(blobName.Uri, conditions: new BlobRequestConditions()
                {
                    LeaseId = "6860da6e-8757-4b83-b42b-68ba9fccba72"
                });
                await batchClient.SubmitBatchAsync(blobBatch, throwOnAnyFailure: true);
            }

            catch (AggregateException)
            {
                // An aggregate exception is thrown for all the individual failures
                // Check ex.InnerExceptions for RequestFailedException instances
            }
               
```

**Comment by navba-MSFT** [comment]
@RohanRao27 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.
