### ISSUE TITLE
[QUERY] Function App Event Hub Trigger and Output binding to the same Event Hub

### ISSUE THREAD

**Issue by gelihu** [Azure/azure-sdk-for-net#30533]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0

### Query/Question

Is it possible to create a trigger and an output binding to the same event hub?

I would like to enqueue faulty messages(events with exceptions) to the same event hub with a different partition key so that a different action can be taken on the faulty/failed messages.

```csharp
[FunctionName("EH2EH")]
public static async Task Run(
    [EventHubTrigger("trunk", Connection = "EventHubConnectionAppSetting")] EventData[] events,
    [EventHub("trunk", Connection = "EventHubConnectionAppSetting")]IAsyncCollector<string> outputEvents,
    ILogger log)
{
    foreach (EventData eventData in events)
    {
        // do some processing:
        try {
            var myProcessedEvent = DoSomething(eventData);
        } catch (Exception) {
             // push the failed message back to the queue.
             await outputEvents.AddAsync(eventData.Body.ToString());
        }
    }
}
```

### Environment

Azure AppService

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @gelihu,
Yes this is possible. Have you run into any issues when doing this?
