### ISSUE TITLE
Visibility timeout mentioned in description for all overloads.

### ISSUE THREAD

**Issue by pavelisaev-ms** [Azure/azure-sdk-for-net#30546]
[Enter feedback here]
Hi,

Some overloads of SendMessage method have visibilityTimeout parameter, while other don't, however in the description for all methods visibility timeout mentioned. ("The visibility timeout specifies how long the message should be invisible to Dequeue and Peek operations.")
It is somehow confusing, also it is not clear what will be actual visibility timeout for messages sent using the overloads where the visibilityTimeout is not in parameters?

Thanks in advance,
Pavel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b8218d6-a69d-a829-2d5c-fb7b3b58ccb8
* Version Independent ID: a38ce876-a8b5-c54d-9442-a4ba15777ebf
* Content: [QueueClient.SendMessage Method (Azure.Storage.Queues) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient.sendmessage?view=azure-dotnet#azure-storage-queues-queueclient-sendmessage(system-string))
* Content Source: [xml/Azure.Storage.Queues/QueueClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Queues/QueueClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@pavelisaev-ms Thanks for the feedback! We will work to update them to remove that information for those overloads where it isn't appropriate.

The default value however is always `TimeSpan.Zero`, meaning the message will be visible as soon as it is received in the queue.
