### ISSUE TITLE
Question about documentation for Container.ReplaceItemAsync<T>

### ISSUE THREAD

**Issue by yuxzha** [Azure/azure-sdk-for-net#30541]
Hi, can I ask for clarification about the Container.ReplaceItemAsync<T> Method? The provided example shows:
await this.container.ReplaceItemAsync<ToDoActivity>(test, test.id, new PartitionKey(test.status));

But I'm not sure if the test object is an existing item in cosmosdb or not? If it's an existing item, which makes more sense because the doc also mentioned the id should be a Cosmos item id of the existing item, could you please provide a better example? Currently the example shows the test object is a new object with a random Guid id.

I want to utilize this method in this way:
Let's say the test object is already existing. Now I want to replace it with a new object:
ToDoActivity test2 = new ToDoActivity()
{
   id = Guid.NewGuid().ToString(),
   status = "InProgress"
};
await this.container.ReplaceItemAsync<ToDoActivity>(test2, test.id, new PartitionKey(test.status));

Can I use the existing test.id and the existing partitionKey to locate the original test object, and replace it with the new test2 object, even if test2 has a new id?

I tested the above way in cosmosdb and succeeded. But wanted to confirm is it allowed to replace the id? Apparently id is not immutable here.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0286f791-878d-c285-c0d2-ebdfc02470be
* Version Independent ID: c8f1d594-e500-eb4b-50b5-8ec04724c482
* Content: [Container.ReplaceItemAsync&lt;T&gt; Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.replaceitemasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@yuxzha Yes. That is valid.

The main difference between upsert (update or insert) vs replace is that for replace to work, the item should already exist, hence requires the id property to be passed to the method.

**Comment by yuxzha** [comment]
Thanks @PramodValavala-MSFT! I would recommend making the provided example a little clearer:

Currently it's confusing because in
ToDoActivity test = new ToDoActivity()
{
   id = Guid.NewGuid().ToString(),
   status = "InProgress"
};
ItemResponse item = await this.container.ReplaceItemAsync<ToDoActivity>(test, test.id, new PartitionKey(test.status));

The test.id is a NewGuid. But we are replacing item with that. Can we clarify the test.id is already existing? And maybe replace with another item?

ToDoActivity test2 = new ToDoActivity()
{
id = Guid.NewGuid().ToString(),
status = "InProgress"
};
await this.container.ReplaceItemAsync(test2, test.id, new PartitionKey(test.status));
