### ISSUE TITLE
[BUG] [Azure.ResourceManager.Authorization] REST API-Version is overdue.

### ISSUE THREAD

**Issue by gongpx20069** [Azure/azure-sdk-for-net#30549]
### Library name and version

Azure.ResourceManager.Authorization 1.0.0-beta.1

### Describe the bug

When I used the function RoleAssignmentCollection.CreateOrUpdate(), the program reported an error. The error is following:

`Unhandled exception. Azure.RequestFailedException: Assignments to roles with DataActions and NotDataActions are not supported on API version '2015-07-01'. The minimum required API version for this operations is '2018-01-01-preview'.
Status: 400 (Bad Request) ErrorCode: UnsupportedApiVersionForRoleDefinitionHasDataActions`

It seems that the RoleAssignment-Create REST API-Version is overdue. So, can you update the package of RoleAssignment?

### Expected behavior

Identity was successfully assigned a role with access to Azure resources.

### Actual behavior

The program is broken. 

### Reproduction Steps

[program.txt](https://github.com/Azure/azure-sdk-for-net/files/9356565/program.txt)

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.400     
 Commit:    7771abd614  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
same issue: https://github.com/Azure/azure-sdk-for-go/issues/18674 
@navba-MSFT any feedback from service team?

**Comment by navba-MSFT** [comment]
@xboxeer I have followed up with them yesterday regarding https://github.com/Azure/azure-sdk-for-go/issues/18674 and currently waiting for their reply. I don't have any ETA on when I will hear back from them.

**Comment by xboxeer** [comment]
@gongpx20069 we'll release a new SDK based on a later version of swagger soon.
If you have any other feedback to Azure SDK, feel free to let us know in this [Survey](https://www.surveymonkey.com/r/YSYFMFF)

**Comment by gongpx20069** [comment]
OK, thanks. 

> @gongpx20069 we'll release a new SDK based on a later version of swagger soon. If you have any other feedback to Azure SDK, feel free to let us know in this [Survey](https://www.surveymonkey.com/r/YSYFMFF)
