### ISSUE TITLE
[QUERY] How to retrieve the content of queue message between Microsoft.WindowsAzure.Storage.Queue and Azure.Storage.Queue

### ISSUE THREAD

**Issue by haoozhang** [Azure/azure-sdk-for-net#30550]
### Library name and version

Azure.Storage.Queues 12.11.0

### Query/Question

We are working on the Azure storage queue SDK upgrade from `Microsoft.WindowsAzure.Storage.Queue` (v9) to `Azure.Storage.Queue` (v12), and we need to achieve the compatibility with bi-direction, i.e., a message inserted by v9 SDK can be retrieved by v9 and v12 SDK, also a message inserted by v12 SDK can be retrieved by v9 and v12 SDK. This is because that we insert  messages in our project, and those messages will be retrieved and consumed by external component (which is NOT controlled by us, and they still use older SDK).

Obviously, the message inserted by v9 SDK can be consumed by v9 SDK (get message content via `CloudQueueMessage.AsString`), the message inserted by v12 SDK can also be consumed by v12 SDK (get message content via `QueueMessage.Body?.ToString()`). However, another two cases can NOT work.

Case1:  a message inserted by v9 SDK can NOT be retrieved by v12 SDK
```c#
class TestMessage
{
    public string PropertyA { get; set; }
    public int PropertyB { get; set; }
    public DateTime PropertyC { get; set; }
    public Guid PropertyD { get; set; }
}

[Test]
public async Task TestAddMessageWithV9AndGetWithV12()
{
    var msg = JsonConvert.SerializeObject(new TestMessage());

    // add with queue v9
    await QueueV9.AddMessageAsync(msg, null);
    // get with queue v12
    var messages = await QueueV12.GetMessagesAsync(5, null);
    Assert.AreEqual(1, messages.Count());
    QueueMessage message = messages.First();

    // msg is the raw string with json format, but the message content is Base64 encoded
    Assert.AreEqual(msg, message.Body?.ToString());
    
    // delete with queue v9
    await QueueV9.DeleteMessageAsync(message.MessageId, message.PopReceipt);
    // get with queue v12, should be empty
    messages = await QueueV12.GetMessagesAsync(5, null);
    Assert.AreEqual(0, messages.Count());
}
```
![image](https://user-images.githubusercontent.com/23452564/185038547-8685956b-0d36-4663-9a1d-174bc79d46e3.png)

Case2: a message inserted by v12 SDK can NOT retrieved by v9 SDK
```c#
[Test]
public async Task TestAddMessageWithV12AndGetWithV9()
{
    var msg = JsonConvert.SerializeObject(new TestMessage());

    // add with queue v12
    await QueueV12.AddMessageAsync(msg, null);
    // get with queue v9
    var messages = await QueueV9.GetMessagesAsync(5, null);
    Assert.AreEqual(1, messages.Count());
    CloudQueueMessage message = messages.First();

    // msg is the raw string with json format, but the message.AsString throws FormatException
    // because `MessageType=Base64Encoded` but `RawString=<raw json string, not base64 encoded string>`
    Assert.AreEqual(msg, message.AsString);

    // delete with queue v12
    await QueueV12.DeleteMessageAsync(message.Id, message.PopReceipt);
    // get with queue v9, should be empty
    messages = await QueueV9.GetMessagesAsync(5, null);
    Assert.AreEqual(0, messages.Count());
}
```

![image](https://user-images.githubusercontent.com/23452564/185039965-06d1598d-9bbf-4459-af61-940c9e06d503.png)

Following the implementation of `AsString` in v9 SDK, if the message type is Base64Encode, its RawString should contain base64-encoded string, so that the message content can be decoded and returned, as follows.
```c#
public string AsString
{
    get
    {
        if (MessageType == QueueMessageType.RawString)
        {
            return RawString;
        }
        if (MessageType == QueueMessageType.Base64Encoded)
        {
            byte[] array = Convert.FromBase64String(RawString);
            return utf8Encoder.GetString(array, 0, array.Length);
        }
        return utf8Encoder.GetString(RawBytes, 0, RawBytes.Length);
    }
}
```

So my question is that are they expected behaviors, or bugs need to be fixed for above scenarios? If they are bugs, may I ask when it can be resolved. Or if they are expected behaviors, could you please help to provide a detailed migration guide for these scenarios, thanks!

### Environment

IDE: 
- Visual Studio

SDK version: 
- Azure.Storage.Queues 12.11.0
- Microsoft.WindowsAzure.Storage.Queue 9.3.3

**Comment by PramodValavala-MSFT** [comment]
@haozhangms I believe you can use the [`QueueClientOptions.MessageEncoding`](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclientoptions.messageencoding?view=azure-dotnet#azure-storage-queues-queueclientoptions-messageencoding) property to automatically handle the base64 content in the newer SDK. By default, they don't do those transformations anymore.

**Comment by haozhangms** [comment]
@PramodValavala-MSFT Thanks for your reply. Maybe you are not get my concern, my focus is that the incompatibility between v9 SDK and v12 SDK for retrieving the content of a message, i.e., the message inserted by v12 SDK can not retrieved content directly by v9 SDK, and vice versa. Could you please help to provide a guide that how to migrate v9 to v12 SDK smoothly? thanks!

**Comment by haozhangms** [comment]
@PramodValavala-MSFT @m-redding 
could you please provide some feedback for this question when you are free, thanks!

**Comment by mkhodos** [comment]
> @PramodValavala-MSFT Thanks for your reply. Maybe you are not get my concern, my focus is that the incompatibility between v9 SDK and v12 SDK for retrieving the content of a message, i.e., the message inserted by v12 SDK can not retrieved content directly by v9 SDK, and vice versa. Could you please help to provide a guide that how to migrate v9 to v12 SDK smoothly? thanks!

I am having the same issues... any ideas how to migrate?

**Comment by haozhangms** [comment]
@mkhodos Finally I add two extension methods to get message content between these different SDKs for work around.
You can just call `GetMessageContent` method.

```c#
    public static class CloudQueueMessageExtensions
    {
        // This method is to make compatible for v1 retrieve message: 
        // 1) for the message inserted with v1 SDK, 'message.AsString' can return normal message text.
        // 2) for the message inserted with v2 SDK, messageType = Base64Encoded but RawString = messageText,
        //    so use reflect to access 'RawString' (private property) and return message text.
        public static string GetMessageContent(this CloudQueueMessage message)
        {
            try
            {
                return message.AsString;
            }
            catch (FormatException ex) when (IsBase64StringException(ex.Message))
            {
                var propertyInfo = message.GetType().GetProperty("RawString", BindingFlags.NonPublic | BindingFlags.Instance);
                return propertyInfo.GetValue(message).ToString();
            }
        }

        public static bool IsBase64StringException(string message)
        {
            Regex regex = new Regex(@"[Bb]ase[- ]64");
            return regex.IsMatch(message);
        }
    }
```

```c#
    public static class QueueMessageExtensions
    {
        // This method is to make compatible for v2 retrieve message: 
        // 1) for the message inserted with v2 SDK, 'message.Body?.ToString()' can return normal message text.
        // 2) for the message inserted with v1 SDK, it will be encoded as Base64 string,
        //    so use Convert to get normal message text.
        public static string GetMessageContent(this QueueMessage message)
        {
            string messageBody = message.Body?.ToString();
            if (IsJsonFormat(messageBody))
            {
                return messageBody;
            }
            else
            {
                byte[] array = Convert.FromBase64String(messageBody);
                return Encoding.UTF8.GetString(array, 0, array.Length);
            }
        }

        // check if a string is valid json format
        public static bool IsJsonFormat(string strInput)
        {
            try
            {
                var result = JsonConvert.DeserializeObject(strInput);
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
    }
```
