### ISSUE TITLE
Is it right to call this method (TableClient.QueryAsync) xxxAsync?

### ISSUE THREAD

**Issue by Bellarmine-Head** [Azure/azure-sdk-for-net#30556]
I thought the norm was that methods named `xxxAsync` returns `Task`s and were awaitable.

I keep sticking `await` before my calls to `TableClient.QueryAsync` and then getting very confused as to the red squiggly line and the error message.

I think that if I had written this method I would not have called it `xxxAsync`, but something else that denotes its asynchronousness yet also denotes that it doesn't return a `Task`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73b5d036-c2df-203c-f426-5e65fbf87b5b
* Version Independent ID: 8ab169e5-cd67-456e-a5d1-0ab9ae1119c3
* Content: [TableClient.QueryAsync Method (Azure.Data.Tables) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclient.queryasync?view=azure-dotnet)
* Content Source: [xml/Azure.Data.Tables/TableClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Data.Tables/TableClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Bellarmine-Head** [comment]
It's too late now, of course, but how about something like: `QueryAsyncSetup` ?

**Comment by christothes** [comment]
Hi @Bellarmine-Head - This is typical for methods that return an `IAsyncEnumerable`. [Here ](https://docs.microsoft.com/en-us/archive/msdn-magazine/2019/november/csharp-iterating-with-async-enumerables-in-csharp-8#a-tour-through-async-enumerables)is some more information about the pattern -
