### ISSUE TITLE
ServiceBusTrigger - receive message in all running instances of service

### ISSUE THREAD

**Issue by ruthoferroman** [Azure/azure-sdk-for-net#30558]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.5.1.0

### Query/Question

I have a Azure Functions App with a ServiceBusTrigger Function which is connected to a ServiceBus Queue.

Now I want to publish a Message to that Servicebus Queue which is received (and therefor triggers the function) on any currently running instance of the Azuer Functions App.

Is there a way to do this?

the function looks like this:
```
[FunctionName("MappingCreatedIntegrationEventHandler")]
        public Task Run(
                    //trigger
                    [ServiceBusTrigger(nameof(MappingCreatedIntegrationEvent), Constants.SUBSCRIPTION_NAME, Connection = "ServiceBusConnectionString")] MappingCreatedIntegrationEvent[] events, 
            ILogger log)
    {
        log.LogInformation("MappingCreatedIntegrationEventHandler {@events}",events);
        objectQueries.ResetCache();
        propertyMappingQueries.ResetCache();

        return Task.CompletedTask;
    }
```

### Environment

Azure Functions App (Windows Host)
.NetFramework 6.0

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
It would trigger the function on one of the instances. Are you saying you want it to trigger all instances?

**Comment by ruthoferroman** [comment]
@JoshLove-msft  Yes, exactly. I need it to trigger all instances

**Comment by ruthoferroman** [comment]
I need to keep some configuration in cache for performance issues. When i update the config, i want to notify all instances about the new config.

**Comment by JoshLove-msft** [comment]
> I need to keep some configuration in cache for performance issues. When i update the config, i want to notify all instances about the new config.

I don't think Service Bus is the right mechanism for something like this as it . I think you could probably achieve this with the [EventGrid trigger](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid-trigger?tabs=in-process%2Cextensionv3&pivots=programming-language-csharp) since it is just a webhook under the hood. I believe each running instance of your function app would be triggered when an event is delivered to your topic.
