### ISSUE TITLE
[FEATURE REQ] Set the TTL (Time to Live) of a container/table via the newest CosmosDB Tables API SDK (Azure.Data.Tables).

### ISSUE THREAD

**Issue by Phoenix359** [Azure/azure-sdk-for-net#30559]
### Library name

Azure.Data.Tables

### Please describe the feature.

We would like a way to set the TTL (Time to Live) of a container/table via the newest Tables API SDK (Azure.Data.Tables).
This setting was available on an older (now deprecated) SDK, but there it complains about TTL not being available for serverless accounts:

**Microsoft.Azure.Cosmos.Table v1.0.8** 
CloudTable table = tableClient.GetTableReference(tableName);
table.CreateIfNotExists(defaultTimeToLive: 2592000);

The TTL feature is available on Azure (even for serverless) and we could set the TTL in the portal. 
This works, it removes all the old records from the table, **but** we create multiple tables per customer on the fly through the SDK and our devop guys would need to periodically check each and every container/table on all environments and set the TTL when missing. This is very tedious and error prone. (What if they set it on the wrong table by accident)
![image](https://user-images.githubusercontent.com/7901130/185114737-6da5732a-85ee-478c-acf3-98c33ca7382f.png)

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Thanks for the feedback, @Phoenix359 - I've tagged the service team on this issue since this feature requires a change to the Cosmos Tables API to be possible in the SDK.

**Comment by Phoenix359** [comment]
You're all welcome. It has been a couple of weeks since my original post. Any comments on if this feature will be included in a future release and if so, is there a rough estimate on when?

**Comment by Phoenix359** [comment]
Its been 3 months now, is there any update?

**Comment by LastTribunal** [comment]
its a serious disability to not have TTL on table storage.. makes me regret using it for prod
