### ISSUE TITLE
[BUG] Naming of Media Services objects needs to be adjusted

### ISSUE THREAD

**Issue by johndeu** [Azure/azure-sdk-for-net#30563]
### Library name and version

Azure.ResourceManager.Media

### Describe the bug

The naming of the objects in Azure.ResourceManager.Media does not match the service naming. 

One annoyance is that the library mixes different cases for Media Services (likely due to some legacy issues with the Swagger file), for example:

The “GetMediaserviceResource” uses a lower case “s” in “services” - it should be GetMediaServicesResource
The “Azure.ResourceManager.Media.MediaServiceData” class uses an upper case “S” in “Services” - which is correct. 
 

Could all of these be updated to use an upper-case “S” in “Services” to be consistent across all uses? That would also match to the product name which is the plural form - Azure Media Services 

### Expected behavior

Naming of objects should be consistent with the service naming of Azure Media Services. 
Use MediaServices and not Mediaservices 
Use plural form and not MediaService - unless referring to a single account in Media Services.

### Actual behavior

See above 

### Reproduction Steps

See above

**Comment by giakas** [comment]
@ArthurMa1978 since you are tracking the Track 2 release. let me know if we can add overrides to fix this in the new SDK. I am hoping to fix this before we release a non- beta version (to avoid breaking changes)

**Comment by ArthurMa1978** [comment]
Hey @johndeu , thank you for your great feedback.

1. We already fixed the lower case issue, you can check the latest API shape here https://apiview.dev/Assemblies/Review/7a469a61bf8c4d8cb52cc70027dfe0c4.
2. The namespace is follow the same as Track 1, so if need to change from `Media` to `MediaServices`, then need have a meeting with archboard.
3. Class name is not same as service name, so we think here the resource `MediaService` should be singular which represent one instance.

**Comment by johndeu** [comment]
Check that grammar

I disagree on your #3 - you are not using proper style for plural of "Media Services".  The brand name is "Media Services", and the entity is Account. 

I disagree with item 3.
Plural:                   Media Services Accounts
Singular:               Media Services Account

In both cases the shortened singular name should be “Media Services”.

**Comment by ArthurMa1978** [comment]
> Check that grammar
> 
> I disagree on your #3 - you are not using proper style for plural of "Media Services". The brand name is "Media Services", and the entity is Account.
> 
> I disagree with item 3. Plural: Media Services Accounts Singular: Media Services Account
> 
> In both cases the shortened singular name should be “Media Services”.

So all `MediaService` definition in swagger need to be renamed to `MediaServicesAccount`?

**Comment by johndeu** [comment]
+ @Girish ***@***.***> - appears to be a problem we have had for longer than I thought.
________________________________
