### ISSUE TITLE
[FEATURE REQ] Samples for AppService Deployment

### ISSUE THREAD

**Issue by xboxeer** [Azure/azure-sdk-for-net#30577]
### Library name

Azure.ResourceManager.AppService

### Please describe the feature.

We have [samples](https://github.com/Azure-Samples/app-service-dotnet-configure-deployment-sources-for-web-apps/blob/master/Program.cs) for website deployment in Track 1 SDK, that is based on a fluent style SDK, it is very important to have the same samples for track 2 given the fact that deploy an webapp in appserivce is  a hero scenario and little bit complex by directly calling our SDK

**Comment by TechWatching** [comment]
Do you have a first example to share or not yet?

**Comment by xboxeer** [comment]
@TechWatching  we released our first stable version of AppService package last month and we decide to have some wrapped method for the deployment, it is in discussion and our samples would base on that

**Comment by TechWatching** [comment]
@xboxeer Are the new wrapped methods for deployment available or not yet?

**Comment by xboxeer** [comment]
@TechWatching not yet implemented since there is some higher priority features in our todo list. meanwhile we are also batch generating SDK samples and publishing them in Azure Rest API reference site, for example: https://learn.microsoft.com/en-us/rest/api/cdn/endpoints/create?tabs=dotnet#examples, you can search in this site to find the samples

**Comment by alexandraei** [comment]
I have been trying to figure out how to deploy to an existing app service as well, is this something that is being worked on and when do you expect it to be available?

**Comment by TechWatching** [comment]
@xboxeer Any news? Are the new wrapped methods for deployment in the backlog?
