### ISSUE TITLE
[QUERY] How to mock GetArmDeployments

### ISSUE THREAD

**Issue by amsoedal** [Azure/azure-sdk-for-net#30587]
### Library name and version

Azure.ResourceManager.Resources 1.1.0

### Query/Question

We're deploying an arm template using the Azure.ResourceManager packages, like so: 

```
ResourceGroupResource resourceGroup = armClient.GetResourceGroupResource(resourceGroupId);
await resourceGroup.GetArmDeployments().CreateOrUpdateAsync(WaitUntil.Completed, CommonConstants.DeploymentName, content);
```
However, we're running into issues with unit testing this code, as GetArmDeployments() is a static method which cannot be mocked. Is there any guidance or documentation on how to work around this? I found a similar question here: https://github.com/Azure/azure-sdk-for-net/issues/28861, and I'm wondering if there's a factory we need to use. 

### Environment

Windows 10 .NET 6.0
Visual Studio 17.3.0

**Comment by xboxeer** [comment]
Mock of current version of mgmt. SDK is still in development phase, I'd suggest that instead of trying to mock extension method, a better way is put this extension method in a none-static method of your class than mock that none-static method

**Comment by adstep** [comment]
Are there any updates on mocking the mgmt. SDK?

**Comment by Yao725** [comment]
Sorry for the delayed response, we already have an internal discussion about mocking extension methods and now I'm working on it.

**Comment by jnlycklama** [comment]
+1 to this issue. Would love to be able to mock out these static methods for Azure.ResourceManager.* packages. Is there any update on this @Yao725 ?

**Comment by amsoedal** [comment]
Hi @Yao725, has this update been released?

**Comment by ArcturusZhang** [comment]
Hey sorry for the delay of response. This feature is actively tracking here: https://github.com/Azure/autorest.csharp/issues/3493
