### ISSUE TITLE
please add a link to the acceptable values for regions

### ISSUE THREAD

**Issue by ejsealms** [Azure/azure-sdk-for-net#30619]
Some services use regions in the format "useast", some do "eastus", some require different casing, etc. Please either give some examples of the expected format or provide a link to another page that does that. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c3e4213-e406-00c7-b714-e298ad007044
* Version Independent ID: 70ca5d39-7326-b225-4334-9bb3e37dc419
* Content: [CosmosClientOptions.ApplicationRegion Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.applicationregion?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@ejsealms The Cosmos DB SDK has a [Regions static class](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.regions?view=azure-dotnet) with string value properties that you should be able to use in such places.
