### ISSUE TITLE
[QUERY] Which SDK should we use to create tables, queues, containers, ... in Azurite?

### ISSUE THREAD

**Issue by TechWatching** [Azure/azure-sdk-for-net#30624]
### Library name and version

Azure.ResourceManager.Storage 1.0.0-beta12

### Query/Question

I am using IaC (Pulumi or Terraform depending on projects) to manage my Azure Resources and in particular my Azure Storage. However when I want to debug my application locally, I use Azurite to emulate my storage account. However I need to manually create everything I created using IaC (queues, tables, containers, import static data, ...) for my application to work like in Azure. My idea was to use Azure SDK to do that but I don't know if I should use Azure.ResourceManager.Storage or the Azure.Storage.* SDK. Which one do you recommand? The SDK should be able to connect to Azurite from its connection string in order to create the tables and everything.

**Comment by navba-MSFT** [comment]
@TechWatching Thanks for reaching out to us. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@TechWatching You can leverage the [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs), [Azure.Storage.Queues](https://www.nuget.org/packages/Azure.Storage.Queues) SDK for this. 

**Azure Blob Storage:** You can then instantiate a BlobContainerClient, BlobServiceClient, or BlobClient.
```
// With container URL and DefaultAzureCredential
var client = new BlobContainerClient(
    new Uri("https://127.0.0.1:10000/devstoreaccount1/container-name"), new DefaultAzureCredential()
  );

// With connection string
var client = new BlobContainerClient(
    "DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=https://127.0.0.1:10000/devstoreaccount1;", "container-name"
  );

// With account name and key
var client = new BlobContainerClient(
    new Uri("https://127.0.0.1:10000/devstoreaccount1/container-name"),
    new StorageSharedKeyCredential("devstoreaccount1", "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==")
  );
```

**Azure Queue Storage:** You can also instantiate a QueueClient or QueueServiceClient.
```
// With queue URL and DefaultAzureCredential
var client = new QueueClient(
    new Uri("https://127.0.0.1:10001/devstoreaccount1/queue-name"), new DefaultAzureCredential()
  );

// With connection string
var client = new QueueClient(
    "DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;QueueEndpoint=https://127.0.0.1:10001/devstoreaccount1;", "queue-name"
  );

// With account name and key
var client = new QueueClient(
    new Uri("https://127.0.0.1:10001/devstoreaccount1/queue-name"),
    new StorageSharedKeyCredential("devstoreaccount1", "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==")
  );
```

**Azure Table Storage:** You can also instantiate a TableClient or TableServiceClient.

```// With table URL and DefaultAzureCredential
var client = new Client(
    new Uri("https://127.0.0.1:10002/devstoreaccount1/table-name"), new DefaultAzureCredential()
  );

// With connection string
var client = new TableClient(
    "DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;TableEndpoint=https://127.0.0.1:10002/devstoreaccount1;", "table-name"
  );

// With account name and key
var client = new TableClient(
    new Uri("https://127.0.0.1:10002/devstoreaccount1/table-name"),
    new StorageSharedKeyCredential("devstoreaccount1", "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==")
  );
```
Support for tables in Azurite is currently in preview. For more information, see the [Azurite V3 Table](https://github.com/Azure/Azurite/wiki/Azurite-V3-Table) project.

**Comment by TechWatching** [comment]
I guess that If I want to create a container, a table, or a queue I can do that also with the SDK. Thanks, I will give it a try.

**Comment by navba-MSFT** [comment]
Sure @TechWatching . If you face any issues, please reach out to us and we will be happy to help.

**Comment by xboxeer** [comment]
> I guess that If I want to create a container, a table, or a queue I can do that also with the SDK. Thanks, I will give it a try.

You can refer to this document [Resource Management with SDK](https://docs.microsoft.com/en-us/dotnet/azure/sdk/resource-management?tabs=PowerShell) for the overall guidance of how to use mgmt. plane SDK to CRUD resource. Sometimes it would be difficult to figure out the right resource in SDK to use(due to some renaming policy), I'd suggest you can export the ARM template in Portal to understand what is the resource you need in creating some complex resource

**Comment by navba-MSFT** [comment]
Thanks @xboxeer 
@TechWatching I wanted to do quick follow-up to check if you had any update for us. Awaiting your reply.

**Comment by TechWatching** [comment]
Yes this issue is addressed. Thank you

**Comment by navba-MSFT** [comment]
@TechWatching Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
