### ISSUE TITLE
[BUG]The JsonPathSanitizers defined in the test do not work

### ISSUE THREAD

**Issue by dvbb** [Azure/azure-sdk-for-net#30631]
### Library name and version

Azure.ResourceManager.DataFactory

### Describe the bug

The JsonPathSanitizers defined in the test don't work for some reason.

### Expected behavior

The defined JsonPathSanitizers will sanitize sensitive information based on the path

### Actual behavior

Both the REST API return value and the defined Sanitizer remain unchanged, but the Sanitizer does not work and still retains sensitive information in the record file

### Reproduction Steps

1. azure-sdk-for-net\sdk\datafactory\Azure.ResourceManager.DataFactory\Azure.ResourceManager.DataFactory.sln
2. Run any cases under LinkedServiceResourceTest.cs
3. check record files

**Comment by ArthurMa1978** [comment]
Enable `JsonPathSanitizers` in the ctor can fix it

**Comment by ArthurMa1978** [comment]
The `JsonPathSanitizers` should be called before any recording happened.
