### ISSUE TITLE
[QUERY]

### ISSUE THREAD

**Issue by srishanth071221** [Azure/azure-sdk-for-net#30630]
### Library name and version

Azure.Communication.Identity 1.1.0

### Query/Question

Hi, 

 We are developing WPF based chat application using below packaged
1. Azure.Communication.Chat (1.1.0)
2. Azure.Communication.Common(1.1.0)
3. Azure.Communication.Identity(1.1.0)
4. Azure.Core (1.25)

While running the application at this step,

var   communicationIdentityClient = new CommunicationIdentityClient(_connectionString);

It is thowing below exception:  
(I suspect Azure.Communication.Identity is looking for the specific lower version of the Azure.Communication.Common.dll)

Could not load file or assembly 'Azure.Communication.Common, Version=1.0.1.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies.

When we manually copy the Azure.Communication.Common, 1.0.1.0 dll then it is throwing an exception
![image](https://user-images.githubusercontent.com/10192345/185591327-cfc8a06e-89c7-4c45-a75e-fa4044622655.png)

We are keeping all 4 dlls in same location but Azure.Communication.Identity not able to resolve the dependency of  Azure.Communication.Common.

Below are screenshots from the ILSpy
![image](https://user-images.githubusercontent.com/10192345/185591605-2fad0781-bada-48ef-835e-8a663f026965.png)

Azure.Communication.Chat  is able to load the Azure.Communication.Common dll without any issue
![image](https://user-images.githubusercontent.com/10192345/185592138-e8892b4f-3d6d-42be-804c-7e34047e5a61.png)

Can anyone help us in this situation?

### Environment

Windows 10 OS.
WPF .NET FRAMWORK APPLICATION 4.8
REFERENCED communication dlls from the our WPF APP.
VS2022

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.
