### ISSUE TITLE
GetEntitiesByUniqueAttributes Method does not work for multiple qualified names.

### ISSUE THREAD

**Issue by pratikrane-ms** [Azure/azure-sdk-for-net#30649]
I tried calling GetEntitiesByUniqueAttributes() as below:

_GetEntitiesByUniqueAttributes(typename, false, false, "attr_0:qualifiedName=q1&attr_1:qualifiedName=q2")_

But it returns empty result;
The request in fiddler looks as below:
api/atlas/v2/entity/bulk/uniqueAttribute/type/{typeName}?minExtInfo=false&ignoreRelationships=false&**attr_N:qualifiedName=attr_0:qualifiedName=q1&attr_1:qualifiedName=q2**

Please help, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3fc329f6-bdb6-62bc-682f-8ea97bbc5f08
* Version Independent ID: 10984d66-84e3-bbee-5806-255cc27d4027
* Content: [PurviewEntities.GetEntitiesByUniqueAttributes Method (Azure.Analytics.Purview.Catalog) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.catalog.purviewentities.getentitiesbyuniqueattributes?view=azure-dotnet-preview)
* Content Source: [xml/Azure.Analytics.Purview.Catalog/PurviewEntities.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Analytics.Purview.Catalog/PurviewEntities.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@pratikrane-ms We are looking into it and get back to you for any additional information.

**Comment by pratikrane-ms** [comment]
@SaurabhSharma-MSFT Is there any update on this?

**Comment by SaurabhSharma-MSFT** [comment]
@pratikrane-ms I am seeing the same behavior and checking internally with the products team on the same.

**Comment by SaurabhSharma-MSFT** [comment]
@pratikrane-ms sorry for the delay. 
You need to pass the qualified names something like below to get the results back- 
`attr_0:qualifiedName=https://{}.blob.core.windows.net/adftutorial/dbo.Sampleddata.txt&attr_1:qualifiedName=https://{}.blob.core.windows.net/adftutorial/input/book.fmt&api-version=2022-03-01-preview`
I am able to identity the issue that I was passing the wrong value in `TypeName` and thus not getting the results back as for the above entities I passed `azure_storage_account` which was incorrect, and the correct type was `azure_blob_path`.

Please check the correct type of the file by using [getbyguids](https://learn.microsoft.com/en-us/dotnet/api/azure.analytics.purview.catalog.purviewentities.getbyguids?view=azure-dotnet-preview) or [Entity - Get By Guid](https://learn.microsoft.com/en-us/rest/api/purview/catalogdataplane/entity/get-by-guid?tabs=HTTP).  You need to get the Guid and Qualified Name from Purview Governance portal as shown below -
![image](https://user-images.githubusercontent.com/38112130/193938720-2f972a5b-1973-45d2-9b35-47ff533be5c1.png)
Please let me know if you have any other questions.

**Comment by SaurabhSharma-MSFT** [comment]
@pratikrane-ms Please let me know if you have any questions else, we will proceed with the issues closure.

**Comment by SaurabhSharma-MSFT** [comment]
@pratikrane-ms We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
