### ISSUE TITLE
[BUG] No way to initialize RunCommand with a script/parameters in the SDK

### ISSUE THREAD

**Issue by abhay-raizada** [Azure/azure-sdk-for-net#30640]
### Library name and version

Azure.ResourceManager.Compute

### Describe the bug

I want to run a script on the VM resource via the RunCommand action provided in the SDK, i see the way to provide it in the SDK is through the `RunCommandInput` Model. However the `RunCommandInput` model in the new version of the SDK only takes the commandId parameter, hence not providing any way to initialize the `Script` and `Parameters` properties that are present in the class, but unreachable. 
```
public RunCommandInput(string commandId)
```

The Old SDK had the constructor which took all 3 values: 
```
RunCommandInput(string commandId, IList<string> script = null, IList<RunCommandInputParameter> parameters = null)
```

This looks like a bug/missing feature, but please do provide a way to provide script and parameters if there exists a different solution.
![image](https://user-images.githubusercontent.com/8532031/185693939-091d3a83-4f00-47de-8e89-6aed5aa3a724.png)

Also looks like https://github.com/Azure/azure-sdk-for-net/issues/26013 is related. 

### Expected behavior

Expected behavior is for the the `RunCommandInput` model to accept all 3 parameters like in the Old SDK.

### Actual behavior

as pointed out in the description.

### Reproduction Steps

can be reproduced by trying to run The following code:
```
VirtualMachineResource vm = //any vm
List<string> script = new List<string> { "Write-Host 'hello, world'"};
List<RunCommandInputParameter> parmaeters = new List<RunCommandInputParameter> { new RunCommandInputParameter("arg1", "value1") };
RunCommandInput commandInput = 
                new RunCommandInput("RunPowershellScript", script: script, parameters: parmaeters);
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

**Comment by xboxeer** [comment]
Hi @abhay-raizada 
you can refer to the below code to run command
```csharp
public void RunCommand(string resourceGroupName)
        {
            var vm = this._client.GetDefaultSubscription().GetResourceGroup(resourceGroupName).Value.GetVirtualMachine("vmName").Value;
            var cmdInput = new RunCommandInput("testId");
            cmdInput.Parameters.Add(new RunCommandInputParameter("parameter1", "value1"));
            cmdInput.Parameters.Add(new RunCommandInputParameter("parameter2", "value2"));
            cmdInput.Script.Add("test scrtipt");
            var runResult = vm.RunCommand(WaitUntil.Completed, cmdInput).Value;
            Console.Write(runResult.Value); 
        }
```

The parameters and script parameter in RunCommandInput is not assignable, they are initialized along with the RunCommandInput itself
```csharp
public RunCommandInput(string commandId)
        {
            if (commandId == null)
            {
                throw new ArgumentNullException("commandId");
            }

            CommandId = commandId;
            Script = new Azure.Core.ChangeTrackingList<string>();
            Parameters = new Azure.Core.ChangeTrackingList<RunCommandInputParameter>();
        }
```
So you just need to add script and parameter to this 2 list, no need to create your own

**Comment by abhay-raizada** [comment]
Hi @xboxeer thank you for your reply, this absolutely works!, maybe we should update the doc, to make it clearer? 
thank you so much for the response!

**Comment by xboxeer** [comment]
> Hi @xboxeer thank you for your reply, this absolutely works!, maybe we should update the doc, to make it clearer? thank you so much for the response!
Yes exactly, the new SDK is still envolving so we are still optmizing it. if you have any overall feedback to our .net SDK, feel free to fill a [survey](https://www.surveymonkey.com/r/YSYFMFF), that will help us a lot!
