### ISSUE TITLE
[QUERY] Using the management libraries to work with Function Apps?

### ISSUE THREAD

**Issue by CodeCapitalist** [Azure/azure-sdk-for-net#30658]
### Library name and version

Azure.ResourceManager

### Query/Question

I'm attempting to setup a pipeline for provisioning a function app and its dependencies. Although I'm not seeing any libraries for Azure Function Apps. Can someone please let me know if this feature needs to be requested, or what library I'll be able to find that in?

**Comment by xboxeer** [comment]
@CodeCapitalist function app is a kind of azure website resource, you should use the AppService package, here is a very simple sample of how to create a function app using SDK, note this sample code only specifies the website we'd like to create is a function app, there are some required parameters not specified yet in this code sample
```csharp
public void CreateNewFunctionApp(string resourceGroupName)
        {
            var resourceGroup=this.client.GetDefaultSubscription().GetResourceGroup(resourceGroupName).Value;
            var webSiteData= new WebSiteData(AzureLocation.WestUS2)
            {
                Kind="functionapp"
            };
            var webSite = resourceGroup.GetWebSites().CreateOrUpdate(Azure.WaitUntil.Completed, "test", webSiteData);
        }
```
A very good way to tell which package to use in SDK when creating resource, is create that resource in portal, and check the automation template 
![image](https://user-images.githubusercontent.com/5089150/186126349-df1b3638-b450-47c6-ad55-150eff4cf3ff.png)
You should than being able to see what properties should be assigned when creating that resource 
![image](https://user-images.githubusercontent.com/5089150/186126556-16ec5c2a-8d12-42dd-b030-49c77643779b.png)
Please note AppService package is still evolving, we'll addressing some issues to make it more friendly for developers. If you have any feedback to our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)
