### ISSUE TITLE
[FEATURE REQ] ServiceBus receiver spans should be correlated to producer

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#30656]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

ServiceBus Receiver client does not correlate receive/settle activities to message context. 
We should do it in the following way:
- Batch receive: add links to contexts of received messages. Links could only be added at the start time, so we should create receive span after messages are received, but set the correct start time
- Async iterator: create receive span per message and add single link to the received context
- Settle:  create span per message  and add a single link to the context in the message

Related issue: https://github.com/microsoft/ApplicationInsights-dotnet/issues/2656

**Comment by lmolkova** [comment]
related issue: https://github.com/microsoft/ApplicationInsights-dotnet/issues/2656

**Comment by JoshLove-msft** [comment]
We are correlating the receive span with the individual messages spans - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs#L333

I think what is missing is the correlation for the settlement methods.

**Comment by JoshLove-msft** [comment]
As @lmolkova mentioned, there is an issue with the receive spans for OpenTelemetry as links need to be added before the span is started. We can consider branching on whether Activity source is enabled, and if so, start the span after the receive is completed and backdate the time as suggested.

**Comment by JoshLove-msft** [comment]
Settlement spans have been added. The receiver spans part is waiting on guidance from @lmolkova.

**Comment by lmolkova** [comment]
Thank you @JoshLove-msft!! 

Regarding receiver: or better or for worse AI SDK ignores links created after activity starts: https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/WEB/Src/DependencyCollector/DependencyCollector/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L73, i.e. this does not work for old `DiagnsoticSource` path either

**Comment by JoshLove-msft** [comment]
> Regarding receiver: or better or for worse AI SDK ignores links created after activity starts: https://github.com/microsoft/ApplicationInsights-dotnet/blob/main/WEB/Src/DependencyCollector/DependencyCollector/Implementation/AzureSdk/AzureSdkDiagnosticsEventHandler.cs#L73, i.e. this does not work for old `DiagnsoticSource` path either

Yep, that matches what I was seeing with how the `Links` property is set in the DiagnosticActivity.
