### ISSUE TITLE
Could not find info regarding possible exceptions

### ISSUE THREAD

**Issue by UmbrellaCorpAgent** [Azure/azure-sdk-for-net#30679]
[It would be very useful to see what exceptions can be thrown. If it exist, maybe it should be easier to find. I think this is relevant infos...]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5330d01-b6f6-80b1-d93a-5bc538261379
* Version Independent ID: df047e90-b65b-b835-02f8-ed59c613c636
* Content: [BlobServiceClient Class (Azure.Storage.Blobs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs/BlobServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs/BlobServiceClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@UmbrellaCorpAgent Most operations raise a [RequestFailedException](https://docs.microsoft.com/en-us/dotnet/api/azure.requestfailedexception?view=azure-dotnet) and the references for the methods mention the same in the remarks section like [this](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.createblobcontainer?view=azure-dotnet#remarks). You should be able to identify the exact problem by cross referencing the error code with the ones [documented](https://docs.microsoft.com/en-us/rest/api/storageservices/status-and-error-codes2).
