### ISSUE TITLE
[BUG] The claims for verification control have not been verified (B2C login)

### ISSUE THREAD

**Issue by wstaelens** [Azure/azure-sdk-for-net#30675]
### Library name and version

Microsoft.AspNetCore.Authentication 6.0.6 (not sure if this is even correct?)

### Describe the bug

My client receives "The claims for verification control have not been verified" on the B2C login.

see: https://github.com/azure-ad-b2c/samples/issues/293  and https://docs.microsoft.com/en-us/answers/questions/934866/error-34the-claims-for-verification-control-have-n.html 

difference between pressing enter and clicking with mouse in Azure B2C login.

(not sure if this is the appropriate place (don't know where to post), but a ticket was not made for it).

### Expected behavior

don't see the error message.

### Actual behavior

error message: "The claims for verification control have not been verified"

### Reproduction Steps

https://docs.microsoft.com/en-us/answers/questions/934866/error-34the-claims-for-verification-control-have-n.html

see: https://github.com/azure-ad-b2c/samples/issues/293 
but there was not a ticket made for it in Azure, so here it is.

### Environment

Visual Studio 2022
.net 6, Azure, B2C login, Blazor server side app.

**Comment by m-redding** [comment]
I don't believe this bug is related to the Azure SDK. Is this what you're looking for? https://docs.microsoft.com/en-us/azure/active-directory-b2c/find-help-open-support-ticket#open-a-support-ticket

**Comment by m-redding** [comment]
Closing this as we are unable to help since this is not an issue related to the Azure SDK.

**Comment by wstaelens** [comment]
In case anyone comes here by accident... according @thesheebs it has been fixed:

`Alas, after more than a year and a lot of persistence, Microsoft has fixed the bug.
SelfAsserted 2.1.17 and UnifiedSSP 2.1.8 are now available.`

https://github.com/azure-ad-b2c/samples/issues/293#issuecomment-1310662126
