### ISSUE TITLE
PurviewEntities.CreateOrUpdateEntitiesAsync does not update classifications for existing entity in purview

### ISSUE THREAD

**Issue by pratikrane-ms** [Azure/azure-sdk-for-net#30699]
For an already existing entity in purview, If I call CreateOrUpdateEntitiesAsync() with new classifications in request body, then this method does not update classificiation tags in purview. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 60dc0816-e226-c23b-b960-59280d96b354
* Version Independent ID: 1233eebf-b6cf-eb9d-4e20-48e35be13ef5
* Content: [PurviewEntities.CreateOrUpdateAsync(RequestContent, RequestContext) Method (Azure.Analytics.Purview.Catalog) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.analytics.purview.catalog.purviewentities.createorupdateasync?view=azure-dotnet-preview)
* Content Source: [xml/Azure.Analytics.Purview.Catalog/PurviewEntities.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Analytics.Purview.Catalog/PurviewEntities.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by pratikrane-ms** [comment]
@jsquire Can you please help with this issue? Is there any update ?

**Comment by jsquire** [comment]
@pratikrane-ms:  There's not much help that I can offer, my role for this is only triage.   The Purview team owns this library and I have no insight.
