### ISSUE TITLE
[FEATURE REQ] Support for 2022-08-31

### ISSUE THREAD

**Issue by DSCmattb** [Azure/azure-sdk-for-net#30704]
### Library name

Azure.AI.FormRecognizer

### Please describe the feature.

Hi Team,

I can see that the form recognizer studio has a new general availability version. Any idea when this will be available via the net sdk?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @DSCmattb,

We plan to release an SDK version targeting 2022-08-31 in early September. Feel free to reopen the issue if you have further questions.
