### ISSUE TITLE
Microsoft.Azure.Management.ServiceBus: Outdated MSDN links

### ISSUE THREAD

**Issue by andreyshv** [Azure/azure-sdk-for-net#30706]
[Enter feedback here]

This page contain outdated msdn links like this one https://msdn.microsoft.com/en-us/library/azure/mt639400.aspx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 185a6eb9-ef6c-65e1-db8e-b8cb75c80e57
* Version Independent ID: 96615291-a287-2f41-89ef-1e50de535137
* Content: [SubscriptionsOperationsExtensions Class (Microsoft.Azure.Management.ServiceBus) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.servicebus.subscriptionsoperationsextensions?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.ServiceBus/SubscriptionsOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.ServiceBus/SubscriptionsOperationsExtensions.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
Hi @andreyshv , the Microsoft.Azure.Management.* is our old SDK and we are recommending our customer using our new SDK with namespace Azure.ResoureceManager.*, you can refer to this document for more detail [Resource Management](https://docs.microsoft.com/en-us/dotnet/azure/sdk/resource-management?tabs=PowerShell)

**Comment by andreyshv** [comment]
Hi @xboxeer, thanks for reply! You wright, my mistake. It would by handy to separate old SDK docs from the new ones.

**Comment by xboxeer** [comment]
> 

Thank you @andreyshv  for the confirming, If you have any other feedback to our new SDK, feel free to fill the [survey](https://www.surveymonkey.com/r/YSYFMFF)
