### ISSUE TITLE
[QUERY]

### ISSUE THREAD

**Issue by kazirahiv** [Azure/azure-sdk-for-net#30703]
### Library name and version

Microsoft.Azure.Management.Fluent:1.38.1

### Query/Question

How to upload docker-compose file for the multi-container web app in azure app services through C# SDK ?

**Comment by xboxeer** [comment]
Hi @kazirahiv, Microsoft.Azure.Management.* is our old SDK and we are recommending developers migrate to our new SDK, you can refer to [Resource Management](https://docs.microsoft.com/en-us/dotnet/azure/sdk/resource-management?tabs=PowerShell) for more detail.
Regarding App Service deployment, the SDK for App Service is still evolving, and we already have an issue tracking it https://github.com/Azure/azure-sdk-for-net/issues/30577
We are open to any comments to our SDK, feel free to fill the [survey](https://www.surveymonkey.com/r/YSYFMFF) to let us know your overall feelings of Azure SDK

**Comment by xboxeer** [comment]
@kazirahiv 
You can use this code to deploy a multi-container apps to app service,

```csharp
public void NewMultiContainerApps(string resourceGroupName)
        {
            string composeFilePath="your compose file path";
            string appServicePlanName="app service plan name";
            string appServiceName="app service name";
            var resourceGroup = this.client.GetDefaultSubscription().GetResourceGroup(resourceGroupName).Value;
            var appServicePlanData = new AppServicePlanData("centralus");
            appServicePlanData.Sku = new Azure.ResourceManager.AppService.Models.SkuDescription();
            appServicePlanData.Sku.Name = "S1";
            appServicePlanData.Sku.Tier = "Standard";
            appServicePlanData.Sku.Size = "S1";
            appServicePlanData.Sku.Family = "S";
            appServicePlanData.Sku.Capacity = 1;
            appServicePlanData.Kind = "linux";            
            appServicePlanData.MaximumElasticWorkerCount = 1;
            appServicePlanData.Reserved = true;
            var appServicePlan = resourceGroup.GetAppServicePlans().CreateOrUpdate(Azure.WaitUntil.Completed, appServicePlanName, appServicePlanData);

            var websiteData = new WebSiteData("centralus");    
            websiteData.ServerFarmId = appServicePlan.Value.Id;
            var composeFile = File.ReadAllText(composeFilePath);
            var base64ComposeFile = Convert.ToBase64String(Encoding.Default.GetBytes(composeFile));
            websiteData.SiteConfig = new Azure.ResourceManager.AppService.Models.SiteConfigProperties();
            websiteData.SiteConfig.LinuxFxVersion = $"COMPOSE|{base64ComposeFile}";
            websiteData.SiteConfig.NetFrameworkVersion = "v4.6";
            websiteData.SiteConfig.AlwaysOn = true;
            websiteData.SiteConfig.LocalMySqlEnabled = false;
            websiteData.SiteConfig.Http20Enabled = true;
            websiteData.SiteConfig.AppSettings = new List<Azure.ResourceManager.AppService.Models.NameValuePair>();
            websiteData.ScmSiteAlsoStopped = false;
            websiteData.HttpsOnly = false;
            websiteData.IsXenon = false;
            websiteData.HyperV = false;
            websiteData.Reserved = false;
            var website = resourceGroup.GetWebSites().CreateOrUpdate(Azure.WaitUntil.Completed, appServiceName, websiteData);

        }
```
 note I get this multi-compose deployment detail from this [Tutorial](https://docs.microsoft.com/en-us/azure/app-service/tutorial-multi-container-app), you can change the parameters of creating app service plan and app service. Key point of deploying a multi-container app is setup the `websiteData.SiteConfig.LinuxFxVersion` property, it should start with "COMPOSE|" and end with a base64 encoded docker-compose file content. When you don't know how to setup a resource in Azure using sdk, always try to go to the portal, and go to its Automation section, export template item
<img width="205" alt="image" src="https://user-images.githubusercontent.com/5089150/187080056-60f43a23-cd68-40a0-8dc1-5786714ef994.png">
then you'll get everything you want
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/5089150/187080263-ba744d4c-d73c-46d7-a079-b12485c566d8.png">

**Comment by kazirahiv** [comment]
Thank you very much for your efforts, Surely will give it a try @xboxeer !

**Comment by Yao725** [comment]
I'm going to close this issue as it has been answered, feel free to reopen it if you still have problems, thanks.
