### ISSUE TITLE
[Core] Introduce JsonData type in Azure.Core

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#30717]
### API Change Needed

Yes

### Background and motivation

The JsonData type provides a dynamic layer for accessing JSON and is intended to improve the developer experience, over JsonDocument which we recommend to users today, when working with protocol methods.  This type will improve usability for raw JSON that comes back from protocol methods as BinaryData.

#### Goals
- Make samples showing clients with protocol methods look like .NET codecode calling protocol methods easier to read.
- Make code reading semi-structured data, e.g. code reading storage table data, easier to read.
- Make it easy easier for customers to update code when Azure SDK-supported models are added to library in a later version

#### Scenarios
- Use content from a protocol method’s response through a dynamic layer, as though it were a model type
- Use content from a pageable service method, treating each element in a returned collection as an individual dynamic, e.g. `Pageable<dynamic>`
- Use content from an LRO, treating the final returned value as the dynamic content, e.g. Operation<dynamic>
- Round-tripping is possible, i.e. get payload from response, update a value in payload, send in request.
- Read storage table data using readable syntax. See [CloudMachine/DatabaseTests.cs at main · KrzysztofCwalina/CloudMachine (github.com)](https://github.com/KrzysztofCwalina/CloudMachine/blob/main/Tests/DatabaseTests.cs#L24)

##### Samples
- [Example motivating scenario](https://gist.github.com/tg-msft/9831ac8e943fa041d2ee952b24cbe015) per @tg-msft 
- [Same scenario using JsonNode](https://gist.github.com/JoshLove-msft/34897c9f5d3250e8b23167ce5c01c2b6) per @JoshLove-msft
- https://github.com/Azure/azure-sdk-for-net/pull/31769
    - Description includes initial requirements
    - Provides illustration of use in CLU and Confidential Ledger samples
- https://github.com/Azure/azure-sdk-for-net/pull/32501
    - Explores making properties settable for round-tripping

#### Notes
In the past, we could not finalize the prototype of JsonData in Azure.Core.Experimental because we tried to make it read-write.  If we scope the problem to just parsing responses, we think we can provide it as a useful type for customers of DPG clients.

#### Creation

- [x] Can get dynamic from Response, e.g. response.Content.ToDynamic();
- [x] Internal API allows JsonData to be constructed from BinaryData
- [ ] Internal API allows JsonData to be constructed from object (e.g. from anonymous type)

#### Serialization/Deserialization

- [x] Serialize JsonData instance to JSON UTF8/bytes
- [x] Deserialize to any type supported by JsonSerializer using explicit cast

#### Usage as output model

- If current node is a leaf node (not an array or an object)
    - [x] Can use a cast to type where either cast or conversion is supported by language, e.g. (DateTime)json
    - [x] Throws if you try to access a member, e.g. json.Property
    - [x] Throws if you try to use an indexer, e.g. json[0] or json[“$foo”]

- If current node is an array node
     - [x] Can get length via Length property, e.g. json.Length
     - [x] Can foreach over, e.g. foreach (int i in json) { }
     - [x] Can access values using indexer that takes int, e.g. json[0]

- If current node is an object
  - [x] Can get and set properties as dynamic members, e.g. json.Property
  - [x] Can cast to model to any type that JsonSerializer can deserialize to
  - [x] Getting a property that isn’t in the JSON returns null and doesn’t throw (this mirrors behavior in Azure SDK model “optional properties”)
  - [x] Can access properties whose names have legal JSON, but illegal C#, characters in them

#### Other
- [x] Can configure type so properties can be read as PascalCase
- [x] Good debugging experience
- [ ] Reasonable performance, i.e. dymanic has perf overhead, and it’s OK because it’s “transparent”. What we don’t want is “hidden” costs, e.g. setting a property results in disproportionally large allocation.
- [x] Extensibility for arbitrary data formats, e.g. XML.

##### Prior Description
- [Current prototype](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.Experimental/src/JsonData.cs) (read/write) per @ellismg 
- [API View of an immutable surface + constructors](https://apiview.dev/Assemblies/Review/3846e6ba641e41a5a3068a417dffcf2c)
- [Proposed updates](https://github.com/jsquire/azure-sdk-for-net/blob/spike/jsondata/sdk/core/Azure.Core.Experimental/src/JsonData.cs) (read only) per @jsquire 

### Time Constraints and Dependencies

If possible, we would like to have this type by late September (@KrzysztofCwalina to comment on timeline needs)

### Stakeholders

@KrzysztofCwalina, DPG customers

**Comment by JoshLove-msft** [comment]
I guess the obvious question is why this belongs in Azure.Core. There doesn't seem to be anything specific to Azure here, and seems like it belongs in the BCL.

**Comment by ellismg** [comment]
Some historical context - when we originally designed `JsonData`, the `JsonNode` type did not exist.   We actually spent one or two meetings talking with the BCL team as they were working on early `JsonNode` designs but I am not sure we ever went back to look at the final design and see if we could use it over our handcrafted `JsonData` (I'm certain that I did not do this exercise).

Another thing pushing the custom time at the time were schedule concerns from our end (ameliorated now as they've shipped) and there was also at the time some concern about having a type that was Net Standard 2.0 compatible (or whatever the minimum version of NS that the Azure SDKs are targeting these days).

**Comment by JoshLove-msft** [comment]
Ah that makes sense given the timelines. JsonNode was added pretty recently. Regarding the minimum version considerations, since STJ is shipped as an OOB package, I wonder if we could consider upgrading the central repo dependency considering that this is a BCL library that has very strong guarantees when it comes to compatibility. That is, if this type actually addresses our needs from the SDK side.

**Comment by annelo-msft** [comment]
@KrzysztofCwalina, do you have a clear set of requirements for your current need for JsonData?  Would JsonNode suffice for those purposes?

**Comment by KrzysztofCwalina** [comment]
Does JsonNode support dynamic?

**Comment by JoshLove-msft** [comment]
> Does JsonNode support dynamic? I don't think so, but if it does, we could use it.

It doesn't look like it does, but it has indexers so you could do things like:
```c#
JsonNode json = JsonNode.Parse(response.ContentStream);
Console.WriteLine(json["foo"]);
Console.WriteLine(json["foo"]["bar"]);
```

**Comment by KrzysztofCwalina** [comment]
The casts and array accessors look good, but I think the property access syntax is so much messier. We might want to do a user study to compare these two.

**Comment by JoshLove-msft** [comment]
JsonNode usage example with TextAnalytics - https://gist.github.com/JoshLove-msft/34897c9f5d3250e8b23167ce5c01c2b6

**Comment by JoshLove-msft** [comment]
Agreed that anonymous types are easier for input, especially when not roundtripping. I don't see how using JsonNode for return types would preclude using anonymous types for input.

**Comment by annelo-msft** [comment]
@JoshLove-msft, I made the same point.  @KrzysztofCwalina's perspective was that we either embrace JsonNode for the full round-trip, or we go with the JsonData/Merge/anonymous type story.  It's true that anonymous types could still be used for input with JsonNode, but if round-tripping requires using JsonNode for input, it's not clear why we would write DPG docs and samples using JsonNode for output and not input.  So the argument was largely driven around the usability of anonymous types over JsonNode for input, not the comparison of JsonNode to JsonData.

As we mentioned earlier, @KrzysztofCwalina did also feel that we need more analysis of JsonData/anonymous types vs. JsonNode for complex types and advanced scenarios - that's work I haven't done yet that remains to be filled in before either approach would be greenlighted.

**Comment by JoshLove-msft** [comment]
> but if round-tripping requires using JsonNode for input, it's not clear why we would write DPG docs and samples using JsonNode for output and not input

I think it depends on the scenario. For the initial request you can use anonymous types or JsonNode. When you get back a JsonNode, and you need to send it back to the service, you would use JsonNode.

**Comment by annelo-msft** [comment]
Sure.  I think the overarching concern there is that we'd like consistency in the documentation around DPG, and not to have to special case things too much, since DPG is going to be advanced enough as it is.

**Comment by JoshLove-msft** [comment]
I wonder if making JsonNode more anonymous type friendly would be an option?
If there was a Parse overload that took an object, that seems like it would get us almost the same experience as JsonData.

**Comment by JoshLove-msft** [comment]
But thinking about this more, I'm not sure I understand the argument around anonymous types for input. For JsonData, I assume we would use anonymous types for input only + JsonData for round-tripping, right? Or am I missing the end-to-end flow here?

**Comment by jsquire** [comment]
> would the Merge just ignore any missing properties

I believe it should follow the HTTP PATCH semantics - keep the existing data and overwrite anything that is provided when calling `Merge`.   

Therre's precedent for this kind of pattern if you consider C# and F# records and the `with` syntax - though those create copies rather than in-place mutation.  _([example](https://learn.microsoft.com/dotnet/csharp/language-reference/builtin-types/record#nondestructive-mutation))_

**Comment by annelo-msft** [comment]
> If there was a Parse overload or even a constructor (similar to how BinaryData works) that took an object, that seems like it would get us almost the same experience as JsonData.

@JoshLove-msft, this makes me curious about the [BinaryData API](https://learn.microsoft.com/en-us/dotnet/api/system.binarydata?view=dotnet-plat-ext-7.0).  Do you know why some conversions to BinaryData are handled as constructors and some as FromXx static methods?

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft, this makes me curious about the [BinaryData API](https://learn.microsoft.com/en-us/dotnet/api/system.binarydata?view=dotnet-plat-ext-7.0). Do you know why some conversions to BinaryData are handled as constructors and some as FromXx static methods?

I believe there are static methods and constructors for each conversion with the exception of streams.  The static methods allow you to use async. IIRC we didn't add a stream constructor because it would seem to imply that we are wrapping the stream, when in reality, we would be consuming it and storing the bytes in memory.

**Comment by JoshLove-msft** [comment]
> I believe it should follow the HTTP PATCH semantics - keep the existing data and overwrite anything that is provided when calling `Merge`.

This makes sense - I suppose we don't really need the ability to remove properties for DPG as you would generally be getting and then updating data with the same JSON schema.

**Comment by annelo-msft** [comment]
> I believe there are static methods and constructors for each conversion with the exception of streams. The static methods allow you to use async.

Can you say more about why we had the constructors?  Neither JsonNode nor JsonDocument have constructors, so I'm wondering what the semantics of the constructor imply that is different from the Parse method, to understand whether we would want a constructor from object on JsonData.  

@ellismg, do you know the .NET convention around this?

**Comment by JoshLove-msft** [comment]
IIRC the thinking was that constructors are more discoverable,  but we also needed at least some static methods to support async operations, i.e. FromStreamAsync.

**Comment by ellismg** [comment]
What @JoshLove-msft said tracks with my understanding.

**Comment by annelo-msft** [comment]
Released in https://www.nuget.org/packages/Azure.Core/1.33.0
