### ISSUE TITLE
[QUERY] What does the `visibilitytimeout` mean in the Storage Queue

### ISSUE THREAD

**Issue by rmt2021** [Azure/azure-sdk-for-net#30716]
### Library name and version

Azure.Storage.Queue

### Query/Question

There are SDK APIs that use the `visibilityTimeout` like `ReceiveMessage` and `SendMessage`:
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient.receivemessageasync?view=azure-dotnet
https://docs.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient.sendmessage?view=azure-dotnet

In the `SendMessage`, it says: 
> "Adds a new message to the back of a queue. The visibility timeout specifies how long the message should be invisible to Dequeue and Peek operations."

and the default value is 0, which means by default, the message can be immediately enqueued right?

However, for `ReceiveMessage`, the default value for `visibilityTimeout` is 30 seconds. 

- What does the `visibilityTimeout` mean here?
- Is `ReceiveMessage` a dequeue operation? Or it just sets the queue message invisible? Will the queue message appear after the timeout?

Thanks!

**Comment by PramodValavala-MSFT** [comment]
@rmt2021 Here are the answers to your questions

> and the default value is 0, which means by default, the message can be immediately dequeued right?

Yes

> However, for ReceiveMessage, the default value for visibilityTimeout is 30 seconds.
>
> What does the visibilityTimeout mean here?

The new visibility timeout which makes the queue message invisible for some time (while it is being processed essentially) and would be made visible after this time.

> Is ReceiveMessage a dequeue operation? Or it just sets the queue message invisible? Will the queue message appear after the timeout?

Yes, its a dequeue operation. The message will appear again after the visibility timeout if the message is not deleted or the visibility timeout isn't updated.

The SDK builds upon the underlying REST API. You can read more about he [send](https://docs.microsoft.com/en-us/rest/api/storageservices/put-message#remarks) and [receive](https://docs.microsoft.com/en-us/rest/api/storageservices/get-messages#remarks) behaviors in their REST API reference docs as well.
