### ISSUE TITLE
[QUERY] Download a blob with conditions

### ISSUE THREAD

**Issue by lumalav** [Azure/azure-sdk-for-net#30710]
### Library name and version

Azure.Storage.Blobs 12.13.1

### Query/Question

I've been having trouble assigning read conditions on blobs when trying to download them when using the Azure SDK for .NET

Basically, what I am trying to do goes like this:

1) Upload a blob (**WORKS**)
2) Download the blob (**WORKS**)
3) Get the Etag of the blob with `blobRef.GetProperties().Etag` (**WORKS**)
4) Use the Etag to try to download the blob again expecting a `RequestFailedException e` where the `e.ErrorCode == ConditionNotMet` (**FAILS**)

**Note:**
When I try to compare the Etag fetched from step 3 (which is converted to a string) with the one I am sending in step 4, it returns they are the same ` blobRef.GetProperties().Etag == new Azure.Etag(blobRef.GetProperties().Etag.ToString())` -> `true`

This is the code:

    var condition = new Azure.Storage.Blobs.Models.BlobRequestConditions
    {
        IfNoneMatch = new Azure.ETag(previousEtagString),
    };

    //blobRef is a valid instance of Azure.Storage.Blobs.BlobClient
    //target is the filePath

    blobRef.DownloadTo(target, conditions: condition); // this should throw RequestFailedException

**UPDATE**:
  1. [Someone](https://stackoverflow.com/a/73476463/1188208) at stackoverflow mentioned that if a blob is not modified, its Etag won't be updated. Is this behavior new? I believe that wasn't the case with version 11.

  2. For version 11, we have passing testcases that were using the `CloudBlockBlob` and called `OpenRead()` with `AccessCondition.GenerateIfNoneMatchCondition(eTag)` and would throw `StorageException`

 3. Passing test cases with v11:
```
 var blobRef = _blobContainer.GetBlockBlobReference(identifier);
 blobRef.DownloadTo(target, AccessCondition.GenerateIfNoneMatchCondition(stringEtag)); //throws StorageException
```

 4. Just noticed that the blob downloaded the second time, does not contain any data. It's empty. The first one has data. Maybe the read condition is partially working?

![image](https://user-images.githubusercontent.com/2550063/186485041-3fbd2c16-97ed-4e04-87c4-a64d442484db.png)

Thanks

### Environment

Hosting Platform and .NET runtime version: Windows 11 .NET Framework 4.6.1
IDE and version: Visual Studio 2019

**Comment by amnguye** [comment]
The stackoverflow comment regarding ETags not changing if the blob has not been modified is correct. If the blob has not been modified it makes sense for the ETag also not to be modified as per definition of an ETag (e.g. The value of an ETag is an identifier that represents a specific version of the resource).

What's the scenario where you require the ETag to update every time you read it? Is there a case where `LastModified` or storing a metadata value would be more helpful?

I don't get what happened in #4, and how it's relevant to the ETag. Are you saying the download fails when you attempt to read a blob the second time? Can you attach SDK client side logs that the blob is not getting downloaded?

**Comment by amnguye** [comment]
Sorry ignore the last part of what I said, I'm going to post that in the other issue linked here, so we're not trying to talk about two issues at once.
