### ISSUE TITLE
Remove tag in autorest.md if it is the same as the default tag in the required swagger readme.md

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-sdk-for-net#30721]
Having the tag in autorest.md will cause the SDK automation pipeline in the swagger PR of updating the default tag to still generate the .NET SDK with the old tag version.

As the swagger readme.md is forced to be referenced with a commit hash in autorest.md, removing the tag in autorest.md should have no impact in future regeneration if the specified tag is the same with the default tag in the swagger readme.md of the commit. We should only add a tag in autorest.md if we don't want to use the default tag from swagger readme.md.

**Comment by jsquire** [comment]
@fengzhou-msft :  I'm not sure how to triage this;  can you provide more context on what you're asking for here?   Is this a change to how the generator parses these files or something else?

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft : I'm not sure how to triage this; can you provide more context on what you're asking for here? Is this a change to how the generator parses these files or something else?

The request comes from service team when they update swaggers with a new default tag of api version, the SDK automation pipeline in swagger CI should generate a preview .NET SDK based on the new default tag. But currently for many SDKs, a specific tag is added in autorest.md, therefore, the generator will use the specified tag instead of the default tag in swagger readme.md.

The generator does not need to change. We need to remove the specified tag in autorest.md if it is the same as the default tag in swagger readme.md.
