### ISSUE TITLE
Error in documentation for DatabaseProperties.Id Property

### ISSUE THREAD

**Issue by pveliz** [Azure/azure-sdk-for-net#30727]
Hey guys, is this still valid?

"You can override this auto Id generation by setting the disableAutomaticIdGeneration parameter on the Microsoft.Azure.Cosmos.DocumentClient instance to true. This will prevent the SDK from generating new Ids."

Package: Microsoft.Azure.Cosmos v3.30.0 doesn't has Microsoft.Azure.Cosmos.DocumentClient and also I'm looking for how to pass this parameter disableAutomaticIdGeneration  to Container.CreateItemAsync method.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b89e8cf-de95-6c72-24db-2e74969d6f08
* Version Independent ID: f7f6267d-3e27-f2f9-7ac5-3fd6ec6b298b
* Content: [DatabaseProperties.Id Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.databaseproperties.id?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/DatabaseProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/DatabaseProperties.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@pveliz Thanks for catching that! This has been changed in the v3 SDK and documented in [this migration doc](https://docs.microsoft.com/en-us/azure/cosmos-db/sql/migrate-dotnet-v3?tabs=dotnet-v3#changes-to-item-id-generation).

We will work on updating this description from the docs.
