### ISSUE TITLE
[BUG] GetPropertiesOfKeys and GetPropertiesOfSecrets returns certificates

### ISSUE THREAD

**Issue by keodime** [Azure/azure-sdk-for-net#30734]
### Library name and version

Azure.Security.KeyVault.Keys AND Azure.Security.KeyVault.Secrets 4.3.0

### Describe the bug

When called GetPropertiesOfKeys/GetPropertiesOfSecrets certificates are returned.

### Expected behavior

When called GetPropertiesOfKeys/GetPropertiesOfSecrets certificates shouldnt be returned

### Actual behavior

When called GetPropertiesOfKeys/GetPropertiesOfSecrets certificates are returned.

### Reproduction Steps

            IAsyncEnumerable<Page<KeyProperties>> asyncPages _client.GetPropertiesOfKeysAsync(cancellationToken).AsPages(continuationToken);

            await foreach (Page<KeyProperties> page in asyncPages.WithCancellation(cancellationToken))
            {
                foreach (KeyProperties properties in page.Values)
                {
                   //put break point here...
                }
            }

### Environment

net6.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
This is by design. If you don't want to see them, filter out `Managed` e.g.,

```c#
    await foreach (var secret in secretClient.GetPropertiesOfSecretsAsync())
    {
        if (secret.Managed) continue;
        Console.WriteLine(secret.Name);
    }
```

All keys and secrets are returned for flexibility. You can assert business logic atop those results as needed. In some use cases, managed keys and secrets are useful.
