### ISSUE TITLE
Please provide a definition for 'scopes' that does not use the word 'scope'

### ISSUE THREAD

**Issue by ejsealms** [Azure/azure-sdk-for-net#30731]
It is very unhelpful and I still don't know what a scope is. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2086405-ef16-89f4-6308-b015fed23c8f
* Version Independent ID: e5c04494-8e45-2942-0c1f-f2029ae2450a
* Content: [TokenRequestContext.Scopes Property (Azure.Core) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.core.tokenrequestcontext.scopes?view=azure-dotnet)
* Content Source: [xml/Azure.Core/TokenRequestContext.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Core/TokenRequestContext.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
@christothes :  Would you mind taking a look?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
@scottaddie  What are your thoughts on this? The definition of scope in the oauth context may be too large to add in the doc comments, but perhaps we can link to something like this? https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent

**Comment by scottaddie** [comment]
@christothes I propose that we link directly to this section: https://docs.microsoft.com/azure/active-directory/develop/v2-permissions-and-consent#scopes-and-permissions

**Comment by christothes** [comment]
Updated link to scopes and permissions is here: https://learn.microsoft.com/azure/active-directory/develop/scopes-oidc
