### ISSUE TITLE
[BUG] `ArmClient.GetManagementGroups().ExistsAsync()` fails unexpectedly with incorrect error message

### ISSUE THREAD

**Issue by steven-hyland** [Azure/azure-sdk-for-net#30752]
### Library name and version

Azure.Core 1.25.0.0
Azure.ResourceManager 1.2.1.0

### Describe the bug

Calling `ArmClient.GetManagementGroups().ExistsAsync()` returns a 403 Forbidden error when called with a scope that the relevant credentials have read permissions on. In addition, the reported scope in the error message is malformed or doesn't match the given argument.

### Expected behavior

The method properly considers the scope and returns `true` or `false` appropriately.

### Actual behavior

The following code (called within a ASP.NET6 controller action):
```
logger.LogInformation(scopeIdentifier);
result.Exists = await _armClient.GetManagementGroups().ExistsAsync(scopeIdentifier);
```
Produces this output and exception (trimmed down from the full output):
```
...
info: application.Controllers.AzureManagementController[0]
      /providers/Microsoft.Management/managementGroups/NonProduction
fail: application.Controllers.AzureManagementController[0]
      Failed Azure request - most likely the given scope is valid, but the resource it points to does not exist.
      Azure.RequestFailedException: The client '<my AAD account>' with object id '<my AAD object ID>' does not have authorization to perform action 'Microsoft.Management/managementGroups/Microsoft.Management/NonProduction/read' over scope '/providers/Microsoft.Management/managementGroups/providers/Microsoft.Management/managementGroups' or the scope is invalid. If access was recently granted, please refresh your credentials.
      Status: 403 (Forbidden)
      ErrorCode: AuthorizationFailed
...
```
Note that the scope in the error message - `/providers/Microsoft.Management/managementGroups/providers/Microsoft.Management/managementGroups` - is two copies of the first three segments of the given scope argument appended together. In my opinion, this is not a reasonable scope to deduce from the argument value.

The type of `scopeIdentifier` is `Azure.Core.ResourceIdentifier`, so maybe something is going on with its implicit `string` conversion operator in this scenario.

`az account management-group show --name NonProduction` works just fine with the same credentials:

![image](https://user-images.githubusercontent.com/62666811/186987406-06b0e823-e71f-4e1d-acce-3efeed13cd1e.png)

### Reproduction Steps

Repro code is above.

### Environment

VS code version information:

![image](https://user-images.githubusercontent.com/62666811/186986064-b3db548a-c9f1-4708-a784-693c163bbe9e.png)

Output of `dotnet --info`:

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  2.1.818 [C:\Program Files\dotnet\sdk]
  3.1.418 [C:\Program Files\dotnet\sdk]
  5.0.411 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by steven-hyland** [comment]
To add some additional context - to workaround the above error, I am using this call:
```
var existsTest = await _armClient.GetManagementGroupResource(scopeIdentifier).GetAsync();
result.Exists = existsTest != null;
```
This produces the same exception and 403 Forbidden error if the management group does not exist, but if it does exist, the call completes successfully. Again, same credentials and everything.

**Comment by steven-hyland** [comment]
Okay, so after running into a similar issue with a different call and finally finding and reading [this documentation](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.ResourceManager/1.3.1/api/Azure.ResourceManager.ManagementGroups/Azure.ResourceManager.ManagementGroups.ManagementGroupCollection.html#collapsible-Azure_ResourceManager_ManagementGroups_ManagementGroupCollection_ExistsAsync_System_String_System_Nullable_Azure_ResourceManager_ManagementGroups_Models_ManagementGroupExpandType__System_Nullable_System_Boolean__System_String_System_String_System_Threading_CancellationToken_), this appears to be user error. I guess I got confused about which methods/API calls take full resource identifiers and which ones just take the id because they already have the scope or can infer it.
