### ISSUE TITLE
[QUERY] Azurite Test Utilities Release Plans

### ISSUE THREAD

**Issue by kaylumah** [Azure/azure-sdk-for-net#30751]
### Library name and version

Azure.Storage.Blobs 12.2.0

### Query/Question

Hi

The sdk offers a `AzuriteFixture` at `azure-sdk-for-net-main/sdk/storage/Azure.Storage.Common/tests/Shared` with useful extension methods at `AzuriteFixtureExtensions` (`azure-sdk-for-net-main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/tests/Shared`) which allows us to run Azure in unit tests.

Since this fixture also takes care of SSL it would be very useful to have.

(note came here because I did not manage to get this sample working https://docs.microsoft.com/en-us/azure/storage/blobs/use-azurite-to-run-automated-tests#run-tests-on-azure-pipelines), I managed to get a ssl running using mkcert but ofcourse the CA certificate is not trusted.

This helper would come a long way in setting stuff up.

Are there any plans to release these test utilities / helpers on nuget?

Thanks
Max

**Comment by amnguye** [comment]
There's no intention to releasing our test utilities on nuget.
