### ISSUE TITLE
[BUG] `BlobServiceClient.GetAccountInfo` fails when using `DefaultAzureCredential`

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-net#30761]
### Library name and version

Azure.Storage.Blobs 12.13.1

### Describe the bug

`BlobServiceClient.GetAccountInfo` works when using a connection string, but fails when using `DefaultAzureCredential`.

### Expected behavior

The account info is returned.

### Actual behavior

Service responds with a HTTP 404 and an exception is thrown.

### Reproduction Steps

Program.cs
``` csharp
using Azure.Identity;
using Azure.Storage.Blobs;

// GetAccountInfo works using a connection string.
{
    var storageConnectionString = Environment.GetEnvironmentVariable("STORAGE_CONNECTION_STRING");
    var serviceClient = new BlobServiceClient(storageConnectionString);
    var accountInfo = serviceClient.GetAccountInfo();
    Console.WriteLine(accountInfo.Value.SkuName);
}

// GetBlobContainers works using DefaultAzureCredential.
{
    var storageAccountName = Environment.GetEnvironmentVariable("STORAGE_ACCOUNT_NAME");
    var accountUri = new Uri($"https://{storageAccountName}.blob.core.windows.net/");
    var serviceClient = new BlobServiceClient(accountUri, new DefaultAzureCredential());
    foreach (var container in serviceClient.GetBlobContainers())
    {
        Console.WriteLine(container.Name);
    }
}

// GetAccountInfo fails with an HTTP 404 Not Found using DefaultAzureCredential.
{
    var storageAccountName = Environment.GetEnvironmentVariable("STORAGE_ACCOUNT_NAME");
    var accountUri = new Uri($"https://{storageAccountName}.blob.core.windows.net/");
    var serviceClient = new BlobServiceClient(accountUri, new DefaultAzureCredential());
    var accountInfo = serviceClient.GetAccountInfo();
    Console.WriteLine(accountInfo.Value.SkuName);
}
```

csproj
``` xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.6.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.13.1" />
  </ItemGroup>

</Project>
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

---
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.3.0

**Comment by PramodValavala-MSFT** [comment]
@cataggar According to [this permission table for data operations](https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory#permissions-for-calling-data-operations), looks like Get Account Information isn't supported.

The same is called out in the [REST API reference](https://docs.microsoft.com/en-us/rest/api/storageservices/get-account-information#authorization) for the underlying request being made.

**Comment by cataggar** [comment]
Thanks @PramodValavala-MSFT. The see it is not supposed to work.
