### ISSUE TITLE
Hyak Latest Version (1.1.3) restricts to Newtonsoft.Json < 10.0.0 (REOPEN Issue #3002 )

### ISSUE THREAD

**Issue by matthewacme** [Azure/azure-sdk-for-net#3080]
#3002 
was marked closed, but this issue has not been fixed! 

The Hyak dependency still depends on a Max Newtonsoft.Json library version of 9.x. Newtonsoft is now up to 10.

The difference between Newtonsoft 9.x and 10.x is the removal of a section of the Newtonsoft Library that was marked as Deprecated 2 YEARS AGO. 

Either make the Hyak Common Library work with the current version of Newtonsoft supported features, or remove the dependency on Hyak Common Library from the Microsoft.Azure.Common dependency.

**Comment by GeekActual** [comment]
@markcowl the problem is that the entire library of Microsoft.Azure.Common depends on Hyak. what library should I use in place of all the areas where Microsoft.Azure.Common is required. 

I don't mean to be snarky (or at least not much..) but isn't something called "Azure.Common" kinda, well Commonly used?  If it has a dependency on a Library that will not be maintained shouldn't a new version of something called "common" be updated to no longer require that deprecated library (like Hyak)?

**Comment by markcowl** [comment]
Microsoft.Azure.Common is the name of the old common library.  The new one, on which almost all ARM clients is based is Microsoft.Rest.ClientRuntime.

Which package are you using that requires this, and why were you unable to move to a later version that depends on Microsoft.Rest.ClientRuntime?

**Comment by GeekActual** [comment]
We are using it for two purposes, 
one is for checking the infrastructure of the Cloud Service we are running on 
And the second is for reading from the Role Environment `RoleEnvironment.GetConfigurationSettingValue( "overrideSlot" ) `

**Comment by markcowl** [comment]
- [ ] Update .NetCore version of Hyak.Core to remove upper limit on Newtonsoft.Json
- [ ] Verify no test issues with remaining 5 packages

### Cost: 2

**Comment by Petermarcu** [comment]
At this point I understand there are no plans to update Hyak, the recommendation is to move forward to new versions of these libraries. Moving forward, the Azure SDK is planning to remove references to JSON.NET to avoid pinning dependencies like this. It will take time to get through all the different places where this dependency exists but over time, the pain should go away. We want people to be able to use whatever JSON.NET version they want without the Azure SDK causing problems.

You can get a glimpse of the first wave of libraries doing this here: https://azure.microsoft.com/en-in/blog/previewing-azure-sdks-following-new-azure-sdk-api-standards/
