### ISSUE TITLE
[QUERY] Backward compatibility for Azure Search .NET SDK

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#30823]
### Library name and version

Azure.Search.Documents 11.3.0

### Query/Question

Azure.Search.Documents V11.3 SDK for .NET is very different from deprecated Microsoft.Azure.Search 10.1.0 SDK for .NET. Some of the differences I noticed are as follows:

SearchAsync doesn't deserialize result into T appropriately unlike the previous version. For example, If there is an Azure Index field titled "id" and T has a property titled "Id" then it doesn't get deserialized. I was told to use JsonPropertyName attribute for all such fields in response class for deserialization but shouldn't this package upgrade have backward compatibility and support existing way of deserialization?

SearchOptions doesn't let us set properties for Select, SearchFields, OrderByFields, HighlightFields, Facets, ScoringParameters unlike in the previous version. It is using only Get accessor of IList for these properties unlike previous version where we could set them with a list of strings. So now, we have to go through each field name and add them one by one.

There was a discussion and a ticket was created with a possible solution at https://github.com/Azure/autorest.csharp/issues/1296 but there was little progress on it.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
We do support feature parity with deprecated `Microsoft.Azure.Search` library and provide all the features that service offers but we don't guarantee backward compatibility. We have created a new `Azure.Search.Documents` library based on https://azure.github.io/azure-sdk/dotnet_introduction.html guidelines which introduces breaking changes and doesn't guarantee backward compatibility with `Microsoft.Azure.Search` library.

We are tracking the issue [here](https://github.com/Azure/autorest.csharp/issues/1296) to support `AddRange()` method on collection properties. I've added [a comment](https://github.com/Azure/autorest.csharp/issues/1296#issuecomment-1232030340) and I'll work with other folks in the team and try to resolve this issue.

Please see [this](https://github.com/Azure/azure-sdk-for-net/issues/20276) issue you created where @Mohit-Chakraborty already responded to all the concerns listed in this issue.

**Comment by ssghoda** [comment]
Yup, I have been following that issue as well where they mentioned their first preference will be to make collection properties settable rather than AddRange extension method but its fine.

Regarding backward compatibility, Mohit suggested that I use JsonPropertyName attribute which works for the most part. However, we are also using Microsoft.Azure.Cosmos.Spatial for one of our fields and using JsonPropertyName for that (previously I was using Newtonsoft.Json when I was using deprecated Microsoft.Azure.Search) gives me serialization error:

"Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Microsoft.Azure.Cosmos.Spatial.Point'. Path: $.address.location | LineNumber: 0 | BytePositionInLine: 371."

**Comment by ShivangiReja** [comment]
I don't think we support `Microsoft.Azure.Cosmos.Spatial` library and we don't have json converter for it. I wonder where did you get this library? I couldn't find it on nuget.

For `Azure.Search.Documents` library, we support [Microsoft.Azure.Core.Spatial](https://www.nuget.org/packages/Microsoft.Azure.Core.Spatial/1.2.0-beta.1) and it contains `MicrosoftSpatialGeoJsonConverter` converter which converts between <c>Microsoft.Spatial</c> objects and Geo-JSON. Please see the [readme](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Microsoft.Azure.Core.Spatial/README.md) for more details.

[Here](https://github.com/Azure/azure-sdk-for-net/blob/cb35f4bfee6fde241921c092af5a1503faea67a6/sdk/search/Azure.Search.Documents/tests/Utilities/SearchResources.Data.cs#L343-L345) is an example of `MicrosoftSpatialGeoJsonConverter`.

**Comment by ssghoda** [comment]
Thanks a lot for this awesome information. So I am guessing we should now use `Microsoft.Spatial.GeographyPoint` for a location field.

We also connect to some Cosmos Db databases in our app for which I was using that Cosmos package `Microsoft.Azure.Cosmos`. I was able to use  `Microsoft.Azure.Cosmos.Spatial.Point` class for location fields while using deprecated `Microsoft.Azure.Search` package along with `Newtonsoft.Json` for deserialization. It was working fine until then so I didn't touch it :) but it stopped working after I upgraded to `Azure.Search.Documents`

**Comment by ShivangiReja** [comment]
Yes, `Microsoft.Spatial.GeographyPoint` should work for location field as shown in [this](https://github.com/Azure/azure-sdk-for-net/blob/cb35f4bfee6fde241921c092af5a1503faea67a6/sdk/search/Azure.Search.Documents/tests/Utilities/SearchResources.Data.cs#L343-L345) example. Please let us know if you see any issue using `MicrosoftSpatialGeoJsonConverter`.

**Comment by ShivangiReja** [comment]
Since your question is resolved, I'm going to close this issue. Feel free to open a new issue if you find any issue using [Microsoft.Azure.Core.Spatial](https://www.nuget.org/packages/Microsoft.Azure.Core.Spatial/1.2.0-beta.1).
