### ISSUE TITLE
Client-side validation for API versions

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#30852]
We want to improve how client-side validation of APIs added in different service versions are done, at least for those SDKs that want to. The idea is that perhaps we move this to shared source - maybe even use it for DPG - but for now want to use Text Analytics as a test.

See [comments](https://github.com/Azure/azure-sdk-for-net/pull/30753#pullrequestreview-1089242767) for a discussion of ideas, but to highlight a few of the larger suggestions (in no particular order but numbered for referential convenience):

1. Check versions only in response to a service error e.g., HTTP 400. We might want to consider tying this in with response classifiers - or using a similar pattern - since different services or even endpoints might respond differently. In fact, without a swagger (or Cadl) defining the specific error pattern, should we take a dependency on the pattern? Perhaps this is something we need to mandate in guidelines.
2. Define some internal interface we can implement explicitly that an analyzer can check. In any public client method, any type used must have its validation method e.g., `IVersionValidation.CheckVersion` called.
3. Related to 2 above (and this was raised for DPG w.r.t. to Cadl), we should consider attributing members with a data-only attribute. An analyzer could use this along with the validation check above to potentially assert at compile time that you're using something that will not work, according to swagger/Cadl. Catching these errors earlier may be a better developer experience.
4. We could support passing in an `IComparer<T>` to support atypical version comparisons, but given how we typically declare service versions for .NET, the default (or no) comparer will suffice.
5. We should also consider using source generators to take declared versions and just write out the public APIs with checks that then call the actual implementation (which would then have to be internal or private). This would make high-level methods easier to implement without all the overhead of writing out the version checks.

**Comment by annelo-msft** [comment]
And none of this is needed if the API Board can [fix service errors](https://github.com/microsoft/api-guidelines/issues/395) :)

**Comment by annelo-msft** [comment]
> Related to 2 above (and this was raised for DPG w.r.t. to Cadl), we should consider attributing members with a data-only attribute. An analyzer could use this along with the validation check above to potentially assert at compile time that you're using something that will not work, according to swagger/Cadl. Catching these errors earlier may be a better developer experience.

Could these attributes drive Intellisense, so we wouldn't show operations/properties/enum values to clients that targeted non-latest service api-versions?
