### ISSUE TITLE
[QUERY] Is there a roadmap for when Azure.Communication.Email will reach GA?

### ISSUE THREAD

**Issue by memoryhash** [Azure/azure-sdk-for-net#30858]
### Library name and version

Azure.Communication.Email 1.0.0-beta1

### Query/Question

Is there a roadmap for when Azure.Communication.Email will reach GA? This library fully meets our needs, and we would like to deploy this to production once it reaches GA. Any sort of time range (even if its very rough, like "Q1 2023" etc) would be great to know. Thanks!

**Comment by PramodValavala-MSFT** [comment]
@memoryhash We have routed this query to the concerning team to share more insights.

**Comment by yk-kd** [comment]
@PramodValavala-MSFT Is there any update on this?

**Comment by DominikMe** [comment]
@memoryhash Email has reached GA in March/April 2023 and the C# SDK lib is now at stable 1.0.0.
Announcement blog: https://techcommunity.microsoft.com/t5/azure-communication-services/simpler-faster-azure-communication-services-email-now-generally/ba-p/3788541
