### ISSUE TITLE
AnalyzeConversation: The specfied deployement cannot be found within the provided subscription

### ISSUE THREAD

**Issue by rajeeshmenoth** [Azure/azure-sdk-for-net#30856]
### Library name and version

Azure.AI.Language.Conversations 1.0.0

### Describe the bug

Hi,

We are facing an issue while connecting custom question answering through the instruction mentioned in the following document : [AnalyzeConversation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples/Sample1_AnalyzeConversation_ConversationPrediction.md).

I am getting the following error message.

![image](https://user-images.githubusercontent.com/8437883/187679487-98b5c9e1-503f-4f77-830e-80ddd70dab93.png)

### Expected behavior

It should display correct answerthe 

### Actual behavior

The specfied deployement cannot be found within the provided subscription

### Reproduction Steps

1. Created custom question answering in Language Studio.
2. Clicked on the "Deploy knowledge base" tab and deployed the knowledge base.
3. Clicked on "Get prediction Url" and copied projectName & deploymentName.
4. Added projectName & deploymentName in the code mentioned in the above document.
5. Copied endpoint & keys from Language Service ( The same language service we have created custom question answering )
6. Location / Region of Language Service is "westeurope".

**Note:** The above code and service credentials are working in Orchestrator flow.

### Environment

Microsoft Visual Studio Enterprise 2019 Version 16.11.4

Microsoft .Net Framework Version 4.8.04084

.Net Core 3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Could you show me your exact snippet? In the sample, this takes advantage of a C# feature where the property name of the anonymous type matches the local. If you called your local variable "myDeploymentName", for example, JSON would contain `"myDeploymentName": "whatever"` which would return an HTTP 400. If this is the case, just be explicit and I should do the same for the sample as well.

**Comment by rajeeshmenoth** [comment]
Hi @heaths,

As I mentioned above, We are facing an issue while connecting custom question answering through the instruction mentioned in the following document : [AnalyzeConversation](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples/Sample1_AnalyzeConversation_ConversationPrediction.md).

The same document code I am using it.

**API Cred:**
```
Uri endpoint = new Uri("https://myaccount.cognitive.microsoft.com");
AzureKeyCredential credential = new AzureKeyCredential("{api-key}");
```

**Implementation Code:**

ConversationAnalysisClient client = new ConversationAnalysisClient(endpoint, credential); 

```
string projectName = "custompoc";
string deploymentName = "production";

var data = new
{
    analysisInput = new
    {
        conversationItem = new
        {
            text = "Send an email to Carol about tomorrow's demo",
            id = "1",
            participantId = "1",
        }
    },
    parameters = new
    {
        projectName,
        deploymentName,

        // Use Utf16CodeUnit for strings in .NET.
        stringIndexType = "Utf16CodeUnit",
    },
    kind = "Conversation",
};

Response response = client.AnalyzeConversation(RequestContent.Create(data));

using JsonDocument result = JsonDocument.Parse(response.ContentStream);
JsonElement conversationalTaskResult = result.RootElement;
JsonElement conversationPrediction = conversationalTaskResult.GetProperty("result").GetProperty("prediction");

Console.WriteLine($"Top intent: {conversationPrediction.GetProperty("topIntent").GetString()}");`
```

**Comment by heaths** [comment]
If you connect to Language Studio via https://language.cognitive.azure.com/, can you run the same query against the project and deployment names as specified above? At least against our project this code works, as all our sample snippets are run as part of nightly live testing.

**Comment by rajeeshmenoth** [comment]
> If you connect to Language Studio via https://language.cognitive.azure.com/, can you run the same query against the project and deployment names as specified above? At least against our project this code works, as all our sample snippets are run as part of nightly live testing.

Yes, The project name and deployment name I have copied from Langauge studio itself.

Also, one more question is there any SDK available for this implementation similar to luisrecognizer / qnamaker recognizer and qnamaker dialog?

**Comment by heaths** [comment]
Can you use `curl` to send the following, replacing `{api-key}` with your actual API key and `{host}` with the host name you're using:
```bash
curl -v -H "Ocp-Apim-Subscription-Key: {api-key}" -H "Content-Type: application/json" "https://{host}.cognitiveservices.azure.com/language/:analyze-conversations?api-version=2022-05-01" --data-raw '{"analysisInput":{"conversationItem":{"text":"Send an email to Carol about tomorrows demo","id":"1","participantId":"1"}},"parameters":{"projectName":"custompoc","deploymentName":"production","stringIndexType":"Utf16CodeUnit"},"kind":"Conversation"}'
```
We do have a Question Answering (formerly QnA Maker) SDK available, yes: https://www.nuget.org/packages/Azure.AI.Language.QuestionAnswering
