### ISSUE TITLE
[BUG] BlobContainerClient throws Azure.RequestFailedException 409 if container already exists but account disallows public access

### ISSUE THREAD

**Issue by Aussiemon** [Azure/azure-sdk-for-net#30864]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Describe the bug

Attempting to run this snippet on an existing container in a storage account that disallows public access:

`BlobContainerClient cloudBlobContainer = this.BlobServiceClient.GetBlobContainerClient(strContainerName);`
`await cloudBlobContainer.CreateIfNotExistsAsync(PublicAccessType.Blob);`

throws an Azure.RequestFailedException: "409: Public access is not permitted on this storage account".

![BlobContainerClient409](https://user-images.githubusercontent.com/13663574/187789345-6303bbdd-216f-45e7-a990-8e1ce68d21f9.png)

![BlobContainerClient409-2](https://user-images.githubusercontent.com/13663574/187789338-e2e86f3b-5fa2-4015-9c77-1bdc8c62ecbc.png)

![BlobContainerClient409-3](https://user-images.githubusercontent.com/13663574/187789342-adb6fff3-5521-477c-8c93-4d8aba14b0c6.png)

### Expected behavior

The method should end execution if the container exists without throwing an Azure.RequestFailedException due to public access level settings.

### Actual behavior

The method throws an Azure.RequestFailedException at the Create step, although the container already exists.

### Reproduction Steps

1. Set a storage account to disallow public access.
2. Call CreateIfNotExistsAsync with PublicAccessType.None on a container that already exists within the storage account; set to private access only.

### Environment

Code written in package targeting .NET Standard 2.0

Used in Azure function hosted in Windows
Runtime 3.13.1.0

Developed in Visual Studio 17.3.1

**Comment by Aussiemon** [comment]
Related to #28549, but is failing for different reasons.

**Comment by Aussiemon** [comment]
@PramodValavala-MSFT The storage account already exists, so no further execution is necessary. After this point, whether or not public access is disabled shouldn't be a factor in the success of the method. Additionally, this exception breaks execution, it isn't just a silent exception in Insights.

This is a CreateIfNotExistsAsync 409 error when the container already exists:
![BlobContainerClient409-4](https://user-images.githubusercontent.com/13663574/187985113-17239e8a-ad4f-4347-9d1e-ae20b87a7aab.png)

This is a CreateIfNotExistsAsync 409 error when the container already exists and disallows public access:
![BlobContainerClient409](https://user-images.githubusercontent.com/13663574/187985202-6aac0d11-b0b1-49ab-abe6-7ed26022996e.png)

The former has a successful call status and the latter has a failed call status.

**Comment by amnguye** [comment]
Throwing the `RequestFailedException` is correct in this scenario. The `CreateIfNotExists` is a convenience method that catches the specific error codes `ContainerAlreadyExists` when the container exists.

This error `Public access is not permitted on this storage account` does not tell us if the container exists or not. It tells us that the request does not have the authorization to make the call it's attempting to. `CreateIfNotExists` throwing the `RequestFailedException` is correct in this scenario.

I recommend doing the try catch block to catch this specific exception if this is an exception you expect to happen and expect your application to ignore.

**Comment by Aussiemon** [comment]
This may be as-designed, but it is not intuitive behavior. The method name suggests the first condition is the container's existence. The public access level check and resulting RequestFailedException should only occur when the container does not exist and needs to be created.

Without this change, the flow seems out of order:

`Can we create -> Do we need to create -> Create container`

but the expected flow is:

`Do we need to create -> `Can we create -> Create container`

Perhaps this is a difference of opinion though, so I'm closing the bug.

**Comment by amnguye** [comment]
That's a security issue. Authorization should always be checked over performing the action.

If someone can check the existence of a container, without having the authorization, then anyone publicly poke at storage account to see if a container exists.

**Comment by Aussiemon** [comment]
Good point!
