### ISSUE TITLE
VMSS WithUpgradeMode Fluent Method throws null reference exception

### ISSUE THREAD

**Issue by thrnto** [Azure/azure-sdk-for-net#3086]
When creating a virtual machine scale set, if the WithUpgradeMode method is used, a null reference exception is thrown inside VirtualMachineScaleSetImpl.

Are there specific requirements in the definition that I might not be meeting in order to set the upgrade policy this way?

**Comment by cormacpayne** [comment]
@singhkays Hey Kay, would you mind taking a look at this issue?

**Comment by martinsawicki** [comment]
I see a missing null check on the inner `.UpgradePolicy`. Not sure what circumstances it'd be null under, but it seems possible. Same problem appears to exist on the Java SDK side.
Fixing for the next release.

**Comment by hovsepm** [comment]
@thrnto PR with the fix is merged. It will be available in the next release.
