### ISSUE TITLE
.ResourceGroups.CreateOrUpdateAsync(.. silently fails with no error or exception.

### ISSUE THREAD

**Issue by dawitmarkos** [Azure/azure-sdk-for-net#3088]
Creating resource group with ResourceGroups.CreateOrUpdateAsync fails with no error or exception. Below is a sample code that's failing for me. The sync version works fine.   Am I missing something here?      

           var resourceManagementClient = new ResourceManagementClient(credential)
            {
                SubscriptionId = subscriptionId
            };

            Console.WriteLine("Creating the resource group...");
            var resourceGroup = new ResourceGroup { Location = location };
           **return await resourceManagementClient.ResourceGroups.CreateOrUpdateAsync(groupName, resourceGroup);**

**Comment by adrianhall** [comment]
Is this still failing?  If so, can you please provide the .NET library and version you are using in your app?
