### ISSUE TITLE
No AnalyticsClient class (referenced in code example) found in Microsoft.Azure.Management.DataLake.Analytics

### ISSUE THREAD

**Issue by jteves** [Azure/azure-sdk-for-net#30895]
I am using the Microsoft.Azure.Management.DataLake.Analytics sdk, and noticed this readme has outdated info regarding the AnalyticsClient class. Please remove this example or at least specify what version of the sdk supports this class.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2266caf8-d69d-e287-366d-e6b00e5856ac
* Version Independent ID: fec13271-648c-f227-b0cc-e91b5f6417e8
* Content: [Azure Data Lake Analytics libraries for .NET - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/data-lake-analytics?view=azure-dotnet)
* Content Source: [api/overview/azure/data-lake-analytics.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/data-lake-analytics.md)
* Service: **data-lake-analytics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
