### ISSUE TITLE
[FormRecognizer] Consider adding a perf test for DocumentLines.GetWords

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#30914]
Perf of this method strongly depends on the implementation used. Currently we just do a brute force search across spans, but we could eventually implement a binary search if the need arises.

**Comment by pallavit** [comment]
@kinelski  Do we already have a perf test for this scenario? If not, should we create one? Also you mention we may have to move this to binary search - do we have any benchmarks we want to keep track of to know when this would be the right thing to do?
