### ISSUE TITLE
[FEATURE REQ] Provide an option for disabling authority validation and instance metadata discovery for disconnected environments

### ISSUE THREAD

**Issue by bganapa** [Azure/azure-sdk-for-net#30916]
### Library name

Azure.Identity

### Please describe the feature.

Azure.Core.TokenCredential and all other derived classes should provide an easy interface to disable authority validation and instance discovery.

MSAL is working on a solution tracked via https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3242 . 
The solution could be to provide an option to allow list the known authority hosts instead of disabling and to skip instance metadata discovery.

The option could be exposed via TokenCredentialOptions

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by bganapa** [comment]
@schaabs Can you please take this into your radar and possibly provide a timeline? This will be a requirement for all the disconnected clouds

**Comment by logangeorge01** [comment]
I believe this issue can be closed with new method [WithInstanceDiscovery(Boolean) ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.abstractapplicationbuilder-1.withinstancediscovery?view=msal-dotnet-latest#microsoft-identity-client-abstractapplicationbuilder-1-withinstancediscovery(system-boolean))
