### ISSUE TITLE
[BUG] stale documentation for In-Process Functions Service Bus message dispositioning

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#30921]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Describe the bug

[`ServiceBusMessageActions`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Primitives/ServiceBusMessageActions.cs) is the way to perform manual message disposition with In-Process Functions but the official documentation is still [suggesting  `MessageReceiver`](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger).

Update documentation to fix this specific document and provide guidance/samples how to perform message disposition to [help developers](https://stackoverflow.com/q/73582927/59563) trying to use the latest In-Process SDK.

### Expected behavior

Be able to find the needed information in the official Microsoft documentation for Azure Functions.

### Actual behavior

Information is either missing or not discoverable.

### Reproduction Steps

Search Microsoft documentation

### Environment

n/a

**Comment by jsquire** [comment]
Hi @SeanFeldman.  I've transferred this to the MS Docs repository as [#97964](https://github.com/MicrosoftDocs/azure-docs/issues/97964) so that team that owns that documentation can assist.

**Comment by SeanFeldman** [comment]
Thank you, @jsquire.
