### ISSUE TITLE
Please make DocumentFields usable as part of external unit tests

### ISSUE THREAD

**Issue by zebslc** [Azure/azure-sdk-for-net#30928]
I am attempting to write unit tests for code that uses the form recogniser, I can obviously mock and wrap the actual extraction part. What I cannot do is anything with these fields as they only have internal constructors and can't be inherited from to create wrappers around.  

_I want to be able to create an instance of one of these fields with a simulated content 
In order that I can test the logic in my application which receives an analysed document and make sure it is using the extracted field values correctly._

Perhaps I am missing something in which case I would love to know the best way of adding tests that include these fields or mocking them in a more appropriate way.

If there is no more appropriate way, please can you make them testable as I am now missing important logic from my coverage with no easy way I can see to achieve that.

![image](https://user-images.githubusercontent.com/3459059/188423925-debd44dd-1217-45da-83b1-8feddb600970.png)

**Comment by jsquire** [comment]
Hi @zebslc.  Thank you for reaching out and we regret that you're experiencing difficulties.   The Form Recognizer output model types can be created for testing using one of the model factory classes in the package.  In this case, the [DocumentAnalysisModelFactory](https://docs.microsoft.com/dotnet/api/azure.ai.formrecognizer.documentanalysis.documentanalysismodelfactory?view=azure-dotnet-preview) offers various ways to construct a `DocumentField` for testing purposes.   More discussion of the approach used by the Azure SDK to support unit testing can be found in [this article](https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/) and our [mocking sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Mocking.md).

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by zebslc** [comment]
Thank you for this - please can you add it to your formal documentation - particularly in the DocumentField section as testing is so important?
