### ISSUE TITLE
[FEATURE REQ] Search: Allow participation/override of document serialization

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [Azure/azure-sdk-for-net#30920]
### Library name

Azure.Search.Documents

### Please describe the feature.

As I don't have complete control over my POCOs that I need to index, I would like to serialize them myself to eg. skip properties or otherwise customize the serialization of the uploaded documents.

Right now I resort to batch uploading dicitonaries of string,object ... it's fine I guess. But no doubt, I would have been able to skip a lot of the meta programming if we had a bit more ways of plugging into this.

```
            var batch = IndexDocumentsBatch.Create(documents.Select(d => IndexDocumentsAction.Upload(d.Properties.ToDictionary(p => p.Name, p => p.Value))).ToArray());

            await SearchClient.IndexDocumentsAsync(batch);

```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
//fyi:  @tg-msft, @KrzysztofCwalina, @pallavit

**Comment by tg-msft** [comment]
You can control serialization by setting [SearchClientOptions.Serializer](https://docs.microsoft.com/en-us/dotnet/api/azure.search.documents.searchclientoptions.serializer?view=azure-dotnet#azure-search-documents-searchclientoptions-serializer) on the options you pass into your `SearchClient` .ctor.

- By default it's configured for `System.Text.Json` so you can [use its attributes to customize serialization](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to) of your objects.
  - You can take  this further by creating a new instance of [`JsonObjectSerializer`](https://docs.microsoft.com/en-us/dotnet/api/azure.core.serialization.jsonobjectserializer?view=azure-dotnet) that allows you to customize how the underlying `JsonSerializer` works - including providing additional converters for types that weren't already annotated. 

- You can also make all this work [with Newtonsoft as well](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/core/Microsoft.Azure.Core.NewtonsoftJson) if you're migrating a legacy application.

- And if you want to do something more elaborate, you can implement your own derived [`ObjectSerializer`](https://docs.microsoft.com/en-us/dotnet/api/azure.core.serialization.objectserializer?view=azure-dotnet) for complete control.
