### ISSUE TITLE
Error when updating:  Failed to add reference. The package 'Microsoft.Azure.Common' tried to add a framework reference to 'System.Threading' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.

### ISSUE THREAD

**Issue by btrabucco** [Azure/azure-sdk-for-net#3093]
Same as issue: https://github.com/Azure/azure-sdk-for-net/issues/2987

Still an issue - don't know why the previous one was closed.

**Comment by abatishchev** [comment]
Thanks for opening another one, was going to do the same since the issue persists and that one was improperly closed without explanation and followups.

**Comment by markcowl** [comment]
What build are you targeting?  The Microsoft.Azure.Common framework does not support .net 4.0 builds, as the previous version did.  If you think you are targeting 4.5 or later and seeing this issue, please let us know what you are targeting

**Comment by Sephiroth018** [comment]
I'm targeting 4.5 and have the same issue.

**Comment by hakwes** [comment]
I have also the same problem. I'm targeting 4.5.2. 2.1.0 installed fine.

**Comment by markcowl** [comment]
Verified.  For some reason this did not show up in testing the package.  Candidate fix for this is here: https://github.com/Azure/azure-sdk-for-net/pull/3136

**Comment by markcowl** [comment]
This should be fixed here: https://www.nuget.org/packages/Microsoft.Azure.Common/2.1.4
