### ISSUE TITLE
[Tables] Support geo-redundancy for Cosmos and Storage

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-sdk-for-net#30943]
Add support for Geo-redundancy in the Tables SDK.
This is supported by Cosmos as multiple failover regions for both read and write.

Initial proposal suggests exposing two client configuration settings:
- `read_regions`: A list of strings with the regional account URLs, in the order that they will be attempted. 
- `write_regions`: Same but for write operations.

This should likely be implemented as a custom retry policy.
For SDKs that expose direct configuration of, or replacement of the existing policy - it will need to be investigated how the proposed changes would affect those customers.

The failover strategy _should_ also be adaptable to the Storage failover "secondary" region - which is effectively a single read region. So this implementation should be tested in that context as well.

We will need to document best practice in conjunction with manual failover - i.e. if a customer triggers a manual failover from the Azure portal, this effectively means the primary region now becomes a secondary region, and the account URL will point to the previously secondary region.

Initial implementation will be simplistic, with room for evolution. Examples of further development:
- Region cooldown period - if a region is considered unreachable, we don't attempt to contact it again for a configurable period.
- Automatic region detection - if the service exposes an API we can automatically detect which regions to retry against.
- Better automation around the manual-failover scenario above.

Sample implementation for context:
https://gist.github.com/christothes/ae5bc0c2ea1e0c7495875a6c7e940297

**Comment by christothes** [comment]
For cosmos scenarios, we need to support scenarios where the write and read regions do not overlap, and therefore the policy needs to manage the hostname of the initial request as well as fallbacks.
