### ISSUE TITLE
[QUERY] Is ProcessEventAsync & ProcessErrorAsync is thread safe?

### ISSUE THREAD

**Issue by akshay-zz** [Azure/azure-sdk-for-net#30951]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.7.2

### Query/Question

I was thinking of using **EventProcessorClient** as a singleton. It is mentioned [here](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/messaging.eventhubs.processor-readme#client-lifetime) 

> The EventProcessorClient is safe to cache and use as a singleton for the lifetime of the application, which is best practice when events are being read regularly. The clients are responsible for efficient management of network, CPU, and memory use, working to keep usage low during periods of inactivity. Calling StopProcessingAsync or StopProcessing on the processor is required to ensure that network resources and other unmanaged objects are properly cleaned up.

Just wanted to make sure that **ProcessEventAsync** & **ProcessErrorAsync** will be thread-safe. Or they will be shared by the thread?

**Comment by jsquire** [comment]
Hi @akshay-zz.   Each Event Hubs client is, itself, safe to interact with from multiple threads.  When it comes to the `EventProcessorClient`, those interactions would be limited to starting/stopping processing as once it is running, it is running and calls back into the handler implementation that you specify.

The handlers are invoked concurrently, up to once-per-partition owned by the processor.  Ensuring that the handler code is thread-safe is an application responsibility, as the application owns/provides the implementation.   More information can be found in the [Event Processor Handlers sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample03_EventProcessorHandlers.md).
