### ISSUE TITLE
[ResourceMover] The operation MoveCollections_Delete can't work

### ISSUE THREAD

**Issue by Yao725** [Azure/azure-sdk-for-net#30952]
Our implementation will use a field called [_nextRequestUri](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/NextLinkOperationImplementation.cs#L30) to poll the LRO status. This field will be updated with this [method](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/NextLinkOperationImplementation.cs#L106) every time after we get the response from the backend service during the polling.

The original response of operation MoveCollections_Delete contains the [Azure_AsyncOperation header](https://github.com/Yao725/azure-sdk-for-net/blob/3a421a283acdbd0ffcad8aaa9a5567c98db704ab/sdk/resourcemover/Azure.ResourceManager.ResourceMover/tests/SessionRecords/MoverResourceSetTests/Delete().json#L182) and we will use this Uri to retrieve the LRO status. However, when we use this Uri to poll for the first time, the [Azure_AsyncOperation header](https://github.com/Yao725/azure-sdk-for-net/blob/3a421a283acdbd0ffcad8aaa9a5567c98db704ab/sdk/resourcemover/Azure.ResourceManager.ResourceMover/tests/SessionRecords/MoverResourceSetTests/Delete().json#L212) of the returned response will be different from the original response. At the next poll, we will use this different Uri, while the server will return [404](https://github.com/Yao725/azure-sdk-for-net/blob/3a421a283acdbd0ffcad8aaa9a5567c98db704ab/sdk/resourcemover/Azure.ResourceManager.ResourceMover/tests/SessionRecords/MoverResourceSetTests/Delete().json#L238-L269) and our LRO will throw exception, which means that this operation can not work as excepted with our existing implementation.

**Comment by HarveyLink** [comment]
Close as issue fixed
