### ISSUE TITLE
[BUG] Azure.Storage.Blobs V12 is taking very long to upload large file compare to v11.

### ISSUE THREAD

**Issue by TimMalik** [Azure/azure-sdk-for-net#30953]
### Library name and version

Azure.Storage.Blobs v12

### Describe the bug

For Large files which are > 500MB there is a significant upload time in v12.

The problem is with the UploadAsync method in the blob storage library package. 

This was working fine in V11 but in V12, the file upload for large files (>1GB) is taking a lot longer. 

[BlobClient.UploadAsync Method (Azure.Storage.Blobs) - Azure for .NET Developers | Microsoft Docs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdotnet%2Fapi%2Fazure.storage.blobs.blobclient.uploadasync%3Fview%3Dazure-dotnet&data=05%7C01%7Ctaimurmalik%40microsoft.com%7Cc3c2e3b12be2473b045d08da8be801d9%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637976125865718343%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=F9HiEjpa4GdcucWAZJNuvRmrbh93uz%2FFRGN6ZWEjNm8%3D&reserved=0)

### Expected behavior

V11 file upload for a 1GB file takes 1 minute to upload. 
V12 should also upload a 1GB file in approximately the same time. 

### Actual behavior

V12 is taking up to 16 minutes to upload a 1GB file. 

### Reproduction Steps

Using this method
 await destinationFile.UploadAsync(stream);

### Environment

.NET

**Comment by navba-MSFT** [comment]
@TimMalik Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@TimMalik To upload a single large blob quickly, a client application can upload its blocks or pages in parallel, being mindful of the [scalability targets](https://docs.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json) for individual blobs and the storage account as a whole. The Azure Storage client libraries support uploading in parallel. For example, you can use the following properties to specify the number of concurrent requests permitted in .NET.

Within the [UploadAsync function](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet#azure-storage-blobs-blobclient-uploadasync(system-binarydata-azure-storage-blobs-models-blobuploadoptions-system-threading-cancellationtoken)), you can leverage the  [BlobUploadOptions](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobuploadoptions?view=azure-dotnet) parameter.

The [BlobUploadOptions.TransferOptions](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.storagetransferoptions?view=azure-dotnet#properties) property helps to configure parallel transfer behavior.

Hope this helps.

**Comment by navba-MSFT** [comment]
@TimMalik I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you  had any questions on this. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@TimMalik I hope you had a chance to look at the above comment. The action is pending on you to test the above plan. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
