### ISSUE TITLE
Source Code Samples

### ISSUE THREAD

**Issue by shudson302** [Azure/azure-sdk-for-net#30950]
Can we have some source code examples for BlobServiceClient and the other classes in Azure.Storage.Blobs?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 89c05068-e1cc-31a0-fca8-83a43ced33ef
* Version Independent ID: 46795e3e-ff28-fe54-e2a7-fab4d9677d4c
* Content: [BlobContainerClient.CreateIfNotExists Method (Azure.Storage.Blobs) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.createifnotexists?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs/BlobContainerClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs/BlobContainerClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@shudson302 You can find [samples](https://docs.microsoft.com/azure/storage/common/storage-samples-dotnet?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json) in the official docs for all supported languages.

**Comment by shudson302** [comment]
I cannot find a sample for how to query blobs by index tags from code.  I only see how to do it via REST.  Does that sample exist?

Summer

**Comment by PramodValavala-MSFT** [comment]
@shudson302 Looks like there isn't a sample for this yet but you can refer to [this unit test](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L3712) in the meantime.

**Comment by PramodValavala-MSFT** [comment]
@shudson302 Just checking in to see if the unit test case code shared above helps

**Comment by shudson302** [comment]
@PramodValavala-MSFT   Yes.  Thank you!

**Comment by PramodValavala-MSFT** [comment]
Glad to hear that!
