### ISSUE TITLE
Cosmos: Explain semantics of the different PatchOperationTypes

### ISSUE THREAD

**Issue by dotpaul** [Azure/azure-sdk-for-net#30972]
It'd be really helpful if the reference documentation here could link to https://docs.microsoft.com/en-us/azure/cosmos-db/partial-document-update#supported-operations, which explains the semantics in detail. Or have the reference documentation explain the semantics in detail.

Same with most of the PatchOperation methods (e.g. PatchOperation.Add())

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4228262e-9067-8ed3-d14f-5329e6ea395e
* Version Independent ID: 0f6e384d-d3a3-88ec-842f-7f1ee9a9447e
* Content: [PatchOperationType Enum (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.patchoperationtype?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/PatchOperationType.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/PatchOperationType.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@dotpaul Thanks for the feedback! We will review and update accordingly.
