### ISSUE TITLE
Azure Batch File Conventions does not support .Net Core

### ISSUE THREAD

**Issue by svick** [Azure/azure-sdk-for-net#3097]
The Azure Batch File Conventions library (Microsoft.Azure.Batch.Conventions.Files) does not currently support .Net Core (or rather, .Net Standard).

Both of its dependencies support .Net Standard, so seemingly this should not be an issue.

I want this so that I can easily persist the output of Batch jobs running on Ubuntu VMs.

**Comment by svick** [comment]
As a start, here are my changes that make the code compile: https://github.com/svick/azure-sdk-for-net/commit/ac5fb7de6472db771fc7411f803ff1bb4ee7fa7c. I have not verified they actually work and some of those changes are probably not appropriate for production code.

**Comment by matthchr** [comment]
@svick - This was implemented on 5/25/2017, but I missed closing this issue at that time.

@shahabhijeet can we close this issue? This package supports netstandard1.4 now.
