### ISSUE TITLE
[QUERY] How do we query the TOP record in Azure.Data.Tables

### ISSUE THREAD

**Issue by Sandeep7OnShell** [Azure/azure-sdk-for-net#30985]
### Library name and version

Azure.Data.Tables 12.6.1

### Query/Question

With Microsoft.WindowsAzure.Storage.Table, we used to do as below:
```
var query = new TableQuery<TEntity>()
            .Where(partitionFilter)
            .Take(limit);
return await ExecuteQuery(table, query);
```

How do we achieve the same using Azure.Data.Tables. For now, we are getting all the data and then doing top in-memory but that seems to be problematic as the data grows.

### Environment

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.2.6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
> How do we achieve the same using Azure.Data.Tables. For now, we are getting all the data and then doing top in-memory but that seems to be problematic as the data grows.

Hi @Sandeep7OnShell  - the equivalent is the maxPerPage parameter. Here is a sample illustrating its use - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md#query-entities-with-maxperpage

**Comment by fhtino** [comment]
@christothes If I remember correctly, the old WindowsAzure.Storage.Table Take only queried and returned the requested number of elements.  With the new Azure.Data.Tables if I specify maxPerPages it only limits the number of elements of **each** rest api call.  E.g. If I have a table with 1 million items and I specify 50, I will get all the elements, running 20.000 api call to azure table rest api.

If I really want to fetch only required data, I must do something like this:
```
            int? maxPerPages = (topN.HasValue && topN < 1000) ? topN : null;
            var result = tableClient.Query<T>(filter, maxPerPages);
            var buffer = new List<T>();
            foreach (var page in result.AsPages())
            {
                buffer.AddRange(page.Values);
                if (topN.HasValue && buffer.Count >= topN.Value)
                    break;
            }
            if (topN.HasValue)
                buffer = buffer.Take(topN.Value).ToList();
            return buffer;
```

I think the library should implement a "TopN" feature. Many users are not aware of the behavior of the underlying rest api.

**Comment by Sandeep7OnShell** [comment]
@fhtino I am aligned with your observation and ask. We should have a mechanism to get topN records instead of clients implementing the same.

@christothes Can we have this considered as a feature?

**Comment by christothes** [comment]
Hi @fhtino - It appears that in your example, you are needing to page through each "topN" set of results until you find a particular item. Could you provide an example of how you would re-write the example above if you had the "TopN" feature?

As far as the current behavior goes, the API documentation is pretty explicit about this. Do you have any recommendations for making this clearer?

https://github.com/Azure/azure-sdk-for-net/blob/da47271b8faabc1b61d419b9d0741061154c0482/sdk/tables/Azure.Data.Tables/src/TableServiceClient.cs#L375-L377

**Comment by fhtino** [comment]
Hi @christothes, regarding the documentation, you linked a different API. However the point is the same: "maxPerPage". In your case "tables", in my case "entities".  In my opinion the documentation is clear and also the parameter name "maxPerPage" is correct.  Instead this issue discuss the lack of a "TopN" functionality. It would be very usesul to have a Query<T>(filter,  . . . . . , topN)

My local implementation (wrapper), that cover my needs is:

```
public List<T> RunQuery<T>(Expression<Func<T, bool>> filter, int? topN = null) where T : class, ITableEntity, new()
{
    // Currently Azure.Data.Tables does not implement "TopN"
    // https://github.com/Azure/azure-sdk-for-net/issues/30985

    if (filter == null)
    {
        // this generates a query without a "where" condition
        filter = item => true;
    }

    TableClient tableClient = this.GetAzureTableClient<T>();

    // Remember: every underlying REST API call returns 1000 items (maximum).
    // Giving an explicit maxPerPages is not strictly required.
    // But if TopN < 1000, it would be a waste of resource retrieving more items than required.            
    int? maxPerPages = (topN.HasValue && topN < 1000) ? topN : null;

    var query = tableClient.Query<T>(filter, maxPerPages);

    var outputBuffer = new List<T>();

    foreach (var page in query.AsPages())
    {
        outputBuffer.AddRange(page.Values);

        if (topN.HasValue && outputBuffer.Count >= topN.Value)
            break;
    }

    if (topN.HasValue)
        outputBuffer = outputBuffer.Take(topN.Value).ToList();

    return outputBuffer;
}
```

**Comment by aleksandervalle** [comment]
Hi @christothes, seems like this issue was closed on March 23th, but latest available available sdk version is from February 8th. Is a solution coming in the next release?

I need to get to top N entries from a table partition. This is how I'm trying to do it:

```
var filter = TableClient.CreateQueryFilter($"PartitionKey eq '{this.partitionKey}'");
var result = this.tableClient.QueryAsync<TableEntity>($"{filter}&$top={n}");
```

I have no idea whether or not this will work, as the name of the first argument of `QueryAsync` is "filter". Is it specifically designed for odata $filter, or is it possible to include $top with it? I think it's a problem that this is not obvious.

As mentioned above, using the `maxPerPage` argument will not do, according to the documentation. I don't want to fetch 100k rows, then select my top 10 rows in-memory.

**Comment by christothes** [comment]
Correct - `maxPerPage` is the only support offered by the service. Your example looks correct to me. More details can be found in [this post](https://stackoverflow.com/a/74240385/1346)
