### ISSUE TITLE
[QUERY] How to create/upload a file to Azure Files in an atomic way

### ISSUE THREAD

**Issue by yuretz** [Azure/azure-sdk-for-net#30980]
### Library name and version

Azure.Storage.Files.Shares 12.11.0

### Query/Question

Is it possible to create and upload a new file in an atomic way? Since a lease could only be acquired on an existing file, it's not exactly clear how can we synchronize a concurrent access to it in the time interval between it is created and a lease is acquired?

**Comment by PramodValavala-MSFT** [comment]
@yuretz There are a fews to tackle this and are covered in detail in [the official docs](https://docs.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet).

**Comment by yuretz** [comment]
In order to upload a new file to Azure Files, you need to
1. [Create a file](https://docs.microsoft.com/en-us/rest/api/storageservices/create-file), which creates an empty file
2. [Write a range of bytes to it](https://docs.microsoft.com/en-us/rest/api/storageservices/put-range)

To implement pessimistic concurrency, according to the official docs, you need to lock a file by [acquiring a lease on it](https://docs.microsoft.com/en-us/rest/api/storageservices/lease-file), which could only be done on an existing files, meaning *you cannot do it before step 1*, only after, making the upload operation non-atomic and therefore prone to creating race conditions. For example, a competing process could manage to delete a created empty file before the lease is taken, which will make the file upload to fail. 

The official docs (that are about blobs, not files BTW) that you kindly direct me to, do not seem to address this scenario. Or did I miss something?

**Comment by yuretz** [comment]
@PramodValavala-MSFT Thank you for the clarifications.
Here is an actual scenario with our production system. There are two services: a producer and a consumer. The producer generates files with a specific content and puts them in an Azure Files shared directory for the consumer (interfacing with a legacy 3rd party application) to access and process. The 3rd party app also deletes files after they are processed. What we are trying to avoid is a situation when the consumer gets to process to an empty file, while it's just about to get filled with actual content, but from what you are saying, it looks like there is currently no straightforward approach to achieve this. Is it correct?

**Comment by PramodValavala-MSFT** [comment]
@yuretz Yes. Looks like that is the case today for Files. It would be best to create a feature request on our [feedback portal](https://feedback.azure.com/d365community/forum/a8bb4a47-3525-ec11-b6e6-000d3a4f0f84).

In the meantime, I suppose your consumer could try to acquire the lease of the file and check the size before processing. So, even if the race condition does occur, the consumer would defer processing.

**Comment by yuretz** [comment]
OK, thanks. We are going to investigate the solution you suggest. Alternatively, acquiring a lease on a specially-created lock file might work for our scenario as well.
