### ISSUE TITLE
Error processing method: 'System.Void Microsoft.AspNetCore.SignalR.HubConnectionContext/<WriteHandshakeResponseAsync>d__47::MoveNext()' in assembly: 'Microsoft.AspNetCore.SignalR.Core.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.ReadOnlyMemory`1<System.Byte> #3022[BUG]

### ISSUE THREAD

**Issue by aproko234** [Azure/azure-sdk-for-net#30986]
### Library name and version

Microsoft.AspNetCore.SignalR.Core.dll 6.0.0

### Describe the bug

I am having this issue when trying to archive my android project in VS 17.3.1:

[Project.zip](https://github.com/Azure/azure-sdk-for-net/files/9506677/Project.zip)

This is what @vitek-karas posted about the issue in another github forum:

The problem is a large version mismatch in resolved dependencies.
The project AbuseAlert references Microsoft.AspNetCore.SignalR.Client version 6.0.8 - which brings in Microsoft.AspNetCore.SignalR.Common.dll version 6.0.0.
The project AbuseAlert also referenced Microsoft.Azure.WebJobs.Extensions.SignalRService version 1.8.0 which eventually references Microsoft.AspNetCore.SignalR.dll version 1.0.0 which in turn has a reference to Microsoft.AspNetCore.SignalR.Common.dll version 1.0.0. But due to the above, it's resolved as version 6.0.0. Apparently there have been public API breaking changes in that assembly between versions 1.0.0 and 6.0.0, one such example is that version 1.0.0 had a field HandshakeProtocol.SuccessHanshakeData but version 6.0.0 doesn't have it.

I don't know what would be the best way to resolve this honestly, it's a version mismatch between dependencies which are not backward compatible.

The main problem is with Microsoft.Azure.WebJobs.Extensions.SignalRService which has a dependency on Microsoft.AspNetCore.SignalR package which has been deprecated. But as far as I can tell, there's no higher version available. https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/signalr/Microsoft.Azure.WebJobs.Extensions.SignalRService/src/Microsoft.Azure.WebJobs.Extensions.SignalRService.csproj

Other things to consider:

The Mono.Android toolchain could be made resilient to unresolved references (maybe the code path is never executed in the app, and thus it could still work). But it's using a rather old version, which we're unlikely to fix. - maybe somebody from the Mono.Adroid team would be able to suggest a solution.

### Expected behavior

This project compiles and runs successfully (in debug mode) before I attempted to archive it (in release mode). It gives the afore-mentioned error.

### Actual behavior

Severity Code Description Project File Line Suppression State
Error Mono.Linker.MarkException: Error processing method: 'System.Void Microsoft.AspNetCore.SignalR.HubConnectionContext/d__47::MoveNext()' in assembly: 'Microsoft.AspNetCore.SignalR.Core.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.ReadOnlyMemory`1<System.Byte> Microsoft.AspNetCore.SignalR.Protocol.HandshakeProtocol::SuccessHandshakeData
at Mono.Linker.Steps.MarkStep.HandleUnresolvedField(FieldReference reference)
at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
at Mono.Linker.Steps.MarkStep.ProcessQueue()
--- End of inner exception stack trace ---
at Mono.Linker.Steps.MarkStep.ProcessQueue()
at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
at Mono.Linker.Steps.MarkStep.Process()
at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
at Mono.Linker.Pipeline.Process(LinkContext context)
at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/runner/work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17

### Reproduction Steps

Download and load the attached project in VS 17.3.3. Compile in Release Mode and the issue will come up.

### Environment

Windows 10 64-bit.
 .NET 6.0/SDK Version: 6.0.400.
Visual Studio 17.3.3.

**Comment by Y-Sindo** [comment]
@aproko234  @markmercer10 Could you share more information about why you have `Microsoft.AspNetCore.SignalR.Core` and `Microsoft.Azure.WebJobs.Extensions.SignalRService` in the same project? I'm wonder if this [Azure SignalR management SDK](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md) could replace the `Microsoft.Azure.WebJobs.Extensions.SignalRService` package as the former one is the base of the latter one and provides all the functionalities of the latter one.
