### ISSUE TITLE
Which method is the equivalent of 'Put Blob'?

### ISSUE THREAD

**Issue by jacobslusser** [Azure/azure-sdk-for-net#30998]
### Library name and version

Azure.Storage.Blobs 12.13.1

### Query/Question

https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob

If my reading of the Blob Service REST API is correct, a block blob can be created/uploaded in a single request using the Put Blob semantics, e.g. `PUT https://myaccount.blob.core.windows.net/mycontainer/myblob`

I'm looking for the SDK method which does the same, however, everything I've tried so far seems to be behaving like a Put **Block** operation, resulting in more than one IO call, e.g. `PUT https://myaccount.blob.core.windows.net/mycontainer/myblob?comp=block&blockid=id`

So far I've tried `BlobClient.UploadAsync` and `BlobClient.OpenWriteAsync`.

Which method will get what I'm looking for? I'm sure I'm just missing something and would appreciate some help.

### Environment

Test stream is 1.73 MB of `image/jpeg` data.

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.3.2

`dotnet --info`
```
.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977
```

**Comment by PramodValavala-MSFT** [comment]
@jacobslusser The `Upload(Async)` and `UploadBlob(Async)` methods on the `BlobClient` and `BlobContainerClient` respectively are the ones you are looking for.

In the case of overwriting, there is an Boolean argument that you can pass as `true` for it. While the REST API is the same for both, the SDK [sets a condition](https://github.com/Azure/azure-sdk-for-net/blob/bfbf35588396fd01966d734d218f80e1ee8b8597/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L736) to not overwrite by default.

**Comment by amnguye** [comment]
If you're looking to avoid the multi stage block scenario I would recommend to adjusting the [StorageTransferOptions.InitialTransferSize](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.storagetransferoptions.initialtransfersize?view=azure-dotnet#azure-storage-storagetransferoptions-initialtransfersize) to ensure that the put blob operation gets sent over the preferred method of doing stage blocks and a final commit block.

**Comment by jacobslusser** [comment]
The behavior I'm seeing appears to be tied to whether the stream is seekable. To recreate:

```cs
public static async Task Main(string[] args)
{
    Console.WriteLine("Hello World");

    var connectionString = "<your_connection_string>"
    var blobServiceClient = new BlobServiceClient(connectionString);
    var containerClient = blobServiceClient.GetBlobContainerClient("documents");
    var blobClient = containerClient.GetBlobClient(Guid.NewGuid().ToString("D"));

    var options = new BlobUploadOptions
    {
        HttpHeaders = new BlobHttpHeaders
        {
            ContentType = "image/jpeg"
        },
        Metadata = new Dictionary<string, string>
        {
            { "originalfilename", "2c7evceneqr51.jpg" }
        }
    };

    using var stream = File.OpenRead("C:\\2c7evceneqr51.jpg");
    using var unseekableStream = new UnseekableMemoryStream();
    await stream.CopyToAsync(unseekableStream);
    unseekableStream.Position = 0;

    var response = await blobClient.UploadAsync(unseekableStream, options);
}

private class UnseekableMemoryStream : MemoryStream
{
    public override bool CanSeek => false;
}
```
If you run this code as is, you'll see two API calls in Fiddler, one Put Block and one Put Block List.

However, if you comment out the `UnseekableMemoryStream` and pass the (seekable) `FileStream` directly to `UploadAsync` you'll get the single Put Blob call.

That's not an issue per se, it might need to be better documented though. Additionally, it implies that the unseekable stream is getting buffered entirely into memory so that the SDK can set the `Content-Length` header of the request.

Please confirm if my understanding is correct, namely
- The `UploadAsync` API will use Put Blob when the stream is seekable and Put Block (List) when it is not seekable.
- Unseekable streams will be buffered into memory to compute their `Content-Length` up to the limit specified in the storage transfer limits.

**Comment by amnguye** [comment]
I believe there was a previous github issue regarding unseekable streams, but I will try to summarize it. When I find the duplicate github issue I will link it here.

>The UploadAsync API will use Put Blob when the stream is seekable and Put Block (List) when it is not seekable.

Yes if the stream is unseekable, it makes it difficult to determine the length of the stream because what if the `stream.Position` is not at 0. Then the size of the blob is the `stream.Length - stream.Position`, however we can't call position if the stream isn't seekable.
(https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.canseek?view=net-6.0#remarks)

>Unseekable streams will be buffered into memory to compute their Content-Length up to the limit specified in the storage transfer limits.

Yes that's what will happen, we will buffer till the end of the stream which is why you see the two requests (e.g. the put block then commit block list).

**Comment by jacobslusser** [comment]
Closing this because the question has been answered.
