### ISSUE TITLE
Incorporate Monitor Ingestion Beta UX study feedback

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-net#31008]
Tracking issue to update the next Azure Monitor Ingestion release to incorporate UX study feedback.

Action items:
- *README* file changes:
  - [ ] Add a “Handle logs ingestion response” section that shows the response object hierarchy. See [Handle logs query response](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/monitor/azure-monitor-query/README.md#handle-logs-query-response) for an example of this idea in the Monitor Query library’s README. Include a blurb about whether there can be more than 1 error message associated with a failed log.
  - [ ] Add guidance on factors to consider when setting the maximum concurrency level.
  - [x] Add a “Retrieve logs” section that links to the Azure Monitor Query library’s README file.
- API changes:
  - [x] Add an `UploadLogsOptions` class in which you allow for setting of the max concurrency level via the constructor.
  - [x] Update XML docs for the `UploadLogsResult.Errors` property to indicate whether a null or an empty list is returned when no errors are present.
  - [x] Add an `IServiceCollection` extension method, named `AddLogsIngestionClient`, to support registering a client in the DI container. See example at https://github.com/Azure/azure-sdk-for-net/blob/bfbf35588396fd01966d734d218f80e1ee8b8597/sdk/keyvault/Azure.Security.KeyVault.Secrets/src/SecretClientBuilderExtensions.cs.

**Comment by nisha-bhatia** [comment]
Also add to ReadMe: ClientBuilderExtensions class sample
