### ISSUE TITLE
Wrong type for RegistryUri on ContainerRegistryImportSource

### ISSUE THREAD

**Issue by nickverschueren** [Azure/azure-sdk-for-net#31007]
### Library name and version

Azure.ResourceManager.ContainerRegistry 1.0.0

### Describe the bug

The API of the Container Registry expects something like "mcr.microsoft.com" or "docker.io", however the type on the ContainerRegistryImportSource is System.Uri, which always has a scheme like http:// or https://. So when you try to submit a request you always get the following error: 

Invalid value https://docker.io/ for property parameters.Source.RegistryUri for resource name ******. For more information, please visit https://aka.ms/acr/import.
Status: 400 (Bad Request)
ErrorCode: InvalidImportImageParameter

Content:
{"error":{"code":"InvalidImportImageParameter","message":"Invalid value https://docker.io/ for property parameters.Source.RegistryUri for resource name ******. For more information, please visit https://aka.ms/acr/import."},"status":"Failed"}

### Expected behavior

Allow a source registry uri without a schems, e.g. docker.io

### Actual behavior

Only a uri with scheme can be given

### Reproduction Steps

Try to import an image from a public registry into an ACR like in this example: https://docs.microsoft.com/en-us/azure/container-registry/container-registry-import-images?tabs=azure-cli#import-from-docker-hub, but using the .NET SDK.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
Thanks @nickverschueren for reporting this issue, I have tried on my side and identified it seems like the RegistryUri could just be a string instead of Uri class. add @fengzhou-msft to fix this issue and release a new version of ContainerRegistry
If you have any other feedback to our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)

**Comment by fengzhou-msft** [comment]
Fixed in `Azure.ResourceManager.ContainerRegistry 1.0.2`
