### ISSUE TITLE
[BUG] CVE in System.Security.Cryptography.xml dependency of Azure.Extensions.AspNetCore.DataProtection.Blobs

### ISSUE THREAD

**Issue by SymbioticKilla** [Azure/azure-sdk-for-net#31006]
### Library name and version

Azure.Extensions.AspNetCore.DataProtection.Blobs 1.2.2

### Describe the bug

Azure.Extensions.AspNetCore.DataProtection.Blobs uses Microsoft.AspNetCore.DataProtection (>= 2.1.0).
Dotnet restore creates lock file with 2.1.0 dependency which has vulnerable System.Security.Cryptography.xml.

### Expected behavior

Update Microsoft.AspNetCore.DataProtection and release a new version

### Actual behavior

![image](https://user-images.githubusercontent.com/59652865/189119026-f8a5168d-1dda-4377-9b0a-f51414a3cba9.png)

### Reproduction Steps

-

**Comment by jsquire** [comment]
@JoshLove-msft:  Looks like we need a dependency version bump for `Microsoft.AspNetCore.DataProtection`.  I don't have historical context on how we chose 2.1.0.  It looks like [6.0.8](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/6.0.8) supports a `netstandard2.0` target.    [3.1.2](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/3.1.2) seems to be our lowest version bump that avoids a vulnerable cryptography package.

Would you please take a look?

**Comment by jsquire** [comment]
Hi @SymbioticKilla.  Thank you for reaching out.  We'll review and adjust dependencies.   In the meantime, we suggest adding a direct reference on `System.Security.Cryptography.Xml` version 4.7.1 or higher in your application.  This will hoist the dependency version and mitigate the vulnerability.

**Comment by pallavit** [comment]
@jsquire do these also get fagged in component governance?

**Comment by jsquire** [comment]
This one did not, for some reason.   They normally do.

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft: Looks like we need a dependency version bump for `Microsoft.AspNetCore.DataProtection`. I don't have historical context on how we chose 2.1.0. It looks like [6.0.8](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/6.0.8) supports a `netstandard2.0` target. [3.1.2](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/3.1.2) seems to be our lowest version bump that avoids a vulnerable cryptography package.
> 
> Would you please take a look?

I also don't have context on the choice. I think we can bump to 3.1.2.

**Comment by JoshLove-msft** [comment]
> > @JoshLove-msft: Looks like we need a dependency version bump for `Microsoft.AspNetCore.DataProtection`. I don't have historical context on how we chose 2.1.0. It looks like [6.0.8](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/6.0.8) supports a `netstandard2.0` target. [3.1.2](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/3.1.2) seems to be our lowest version bump that avoids a vulnerable cryptography package.
> > Would you please take a look?
> 
> I also don't have context on the choice. I think we can bump to 3.1.2.

Actually, all the way back to 3.0.0 depends on 4.6 of the crypto library. Though any versions prior to 6.x are marked as deprecated.

**Comment by JoshLove-msft** [comment]
Nevermind - I see 3.1.2 is the earliest non-deprecated version.
