### ISSUE TITLE
[BUG] StreamingJobResource.GetStreamingJobInputs throws exception

### ISSUE THREAD

**Issue by benjaminheld** [Azure/azure-sdk-for-net#31011]
### Library name and version

Azure.ResourceManager.StreamAnalytics (1.0.0-beta.2)

### Describe the bug

When a Stream Analytics job with a SQL Reference Data Input is created and the refresh rate is set e.g. to 1 day, then the call StreamingJobResource.GetStreamingJobInputs for this job fails with the exception 

'property0.Value.GetDateTimeOffset()' löste eine Ausnahme des Typs 'System.FormatException' aus
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233033
    HelpLink: null
    InnerException: null
    Message: "One of the identified items was in an invalid format."
    Source: "System.Text.Json"
    StackTrace: "   bei System.Text.Json.JsonElement.GetDateTimeOffset()"
    TargetSite: {System.DateTimeOffset GetDateTimeOffset()}

The issue seems to be in the following line: https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.StreamAnalytics_1.0.0-beta.2/sdk/streamanalytics/Azure.ResourceManager.StreamAnalytics/src/Generated/Models/SqlReferenceInputDataSource.Serialization.cs#L137
The property value is for example: "00:15:00", which cannot be parsed into a DateTimeOffset. I would expect it to be of type TimeSpan.

### Expected behavior

No Exception is thrown and the SqlReferenceInputDataSource is returned correctly.

### Actual behavior

The following exception is thrown:
'property0.Value.GetDateTimeOffset()' löste eine Ausnahme des Typs 'System.FormatException' aus
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233033
    HelpLink: null
    InnerException: null
    Message: "One of the identified items was in an invalid format."
    Source: "System.Text.Json"
    StackTrace: "   bei System.Text.Json.JsonElement.GetDateTimeOffset()"
    TargetSite: {System.DateTimeOffset GetDateTimeOffset()}

### Reproduction Steps

1. Create an Azure SQL Database and create a table
2. Create a Stream Analytics Job
3. Configure a Reference data input to the SQL DB with a refresh rate (e.g. set it to 1 day)

Write code similar to the following:

	SubscriptionResource subscription = await client.GetSubscriptions().GetAsync(subscriptionId);
	ResourceGroupResource resourceGroup = await subscription.GetResourceGroupAsync(resourceGroupName);
	var jobs = resourceGroup.GetStreamingJobs();
	foreach(var job in jobs){
		try
		{
			foreach (var input in job.GetStreamingJobInputs())
			{
				//
			}
		}catch(FormatException ex){
			Console.WriteLine(ex);
		}
	}

### Environment

.NET 6.0.400

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@benjaminheld yes you are right, i can reproduce your issue in both our preview version and stable version SDK, the root cause is refreshRate returned by azure is  "1.00:00:00" but SDK treat RefreshRate property as DateTimeOffset type, that's why we can not json deserialize it. We'll provide a fix to it.
Any other feedback to SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)

**Comment by xboxeer** [comment]
CC: @ArthurMa1978 @ArcturusZhang

**Comment by ArthurMa1978** [comment]
Fixed in [1.1.0](https://www.nuget.org/packages/Azure.ResourceManager.StreamAnalytics/1.1.0)
