### ISSUE TITLE
[TextanAlytics] SingleLabelClassifyBatchTest failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#31034]
TextanAlytics nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Internal server error
> Status: 500 (Internal Server Error)
> ErrorCode: InternalServerError
> 
> Content:
> {"error":{"code":"InternalServerError","innerError":{"requestId":"7a52849f-c578-474b-83a1-5c9004dcada8"},"message":"Internal server error"}}
> 
> Headers:
> Transfer-Encoding: chunked
> x-envoy-upstream-service-time: 130
> apim-request-id: 7a52849f-c578-474b-83a1-5c9004dcada8
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Fri, 09 Sep 2022 02:21:27 GMT
> Content-Type: application/json; charset=utf-8
> 
> 
> Stack trace
>    at Azure.AI.TextAnalytics.MicrosoftCognitiveLanguageServiceTextAnalysisRestClient.AnalyzeBatchJobStatusAsync(Guid jobId, Nullable`1 showStats, Nullable`1 top, Nullable`1 skip, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/Generated/MicrosoftCognitiveLanguageServiceTextAnalysisRestClient.cs:line 239
>    at Azure.AI.TextAnalytics.ServiceClients.LanguageServiceClient.AnalyzeStatusAsync(String jobId, Nullable`1 showStats, Nullable`1 top, Nullable`1 skip, IDictionary`2 idToIndexMap, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/ServiceClients/LanguageServiceClient.cs:line 1646
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.Azure.Core.IOperation<Azure.AsyncPageable<Azure.AI.TextAnalytics.AnalyzeActionsResult>>.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/AnalyzeActionsOperation.cs:line 287
>    at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 260
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 87
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 79
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 202
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 242
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 198
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/AnalyzeActionsOperation.cs:line 226
>    at Azure.AI.TextAnalytics.Tests.TextAnalyticsClientLiveTestBase.PollUntilTimeout[T](Operation`1 operation, Int32 timeoutInMinutes) in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/Infrastructure/TextAnalyticsClientLiveTestBase.cs:line 72
>    at Azure.AI.TextAnalytics.Tests.SingleLabelClassifyTests.SingleLabelClassifyBatchTest() in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/SingleLabelClassifyTests.cs:line 177
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1840014&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment]
This problem was reported back to the service team. They said it was something that they were aware of, and they resolved it earlier last month. It hasn't repro since then, so I'm now closing this issue.
