### ISSUE TITLE
[BUG] net - resourcemanager - mgmt - ci does not run all steps for all mgmt plane

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#31039]
### Library name and version

Azure.ResourceManager

### Describe the bug

We recently updated the ci for mgmt to only run `net - resourcemanager - mgmt - ci` for all mgmt plane libraries instead of individual ci's due to performance reasons.  [Commit is here](https://github.com/Azure/azure-sdk-for-net/commit/37a52408a8229376d4d2da066ca2e1c0e24d37f5).  In the latest run [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1841778&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=d155e9a2-7cbb-5b0e-f3c1-03b63fe55961) I noticed that the analyze step is only running for Azure.ResourceManager and NOT all of the other mgmt projects.

Our analyze step is able to deal with `*` as a ServiceDirectory and auto-expand we probably need to adjust that to treat `resourcemanager` as a wild card as well and run each mgmt library.

To find all mgmt projects we can use this code [here](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/Update-Mgmt-CI.ps1#L3).  This excludes Azure.ResourceManager which we probably want to include when running analyze so just remove the extra `.` at the end of the filter.

### Expected behavior

All mgmt plane libraries have their analyze step run

### Actual behavior

only resourcemanager library has its analyze step run

### Reproduction Steps

run the net - resourcemanager - mgmt - ci

**Comment by m-nash** [comment]
For now @ArthurMa1978  please run `/azp prepare net - [ServiceDirectory]- mgmt - ci` for each rp one at a time to not clog the build system but still get the coverage

**Comment by weshaggard** [comment]
For triggering the pipeline manually run `/azp run net - [ServiceDirectory] - mgmt` instead.

@sima-zhu once you get the work done to run the core pipeline code gen step in parallel done, can you also please do the same for the resourcemanager pipeline?

**Comment by weshaggard** [comment]
After further conversation we did not end up enabling this for the core pipeline because it turns out it is not needed so we removed the `*` from there. I was thinking we would do the same thing (i.e. not enable this) for resourcemanager however I just realized we disabled all the individual mgmt pipelines from triggering so we probably do still need this support for resourcemanager. 

@sima-zhu can you use your work you did for core and try enabling it for resourcemanager pipeline as we do need to check all the mgmt libraries in this case.

**Comment by sima-zhu** [comment]
Analyze Step 
- [ ] Sparse-checkout (Java has the same [setting](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1876114&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2102385d-609d-5572-64d2-932661c7902f))
- [ ] Link verification 
- [ ] Verify sample metadata
- [ ] Verify Readmes
- [ ] Analyze Path Lengths
- [ ] Verify generated code
- [ ] validate-filename

**Comment by sima-zhu** [comment]
Further categorizations:
1. Taking project list:
    - Verify generated code
    - Build snippet
2. Taking changed files:
    - Check file case duplicates
    - Link verification
    - Validate any change in `eng/common`
    - Spell checking
3. Taking multiple directories:
    - Sparse-checkout
    - Verify sample 
    - Verify readme
4. Taking single directory:
    - Analyze Path Lengths

**Comment by sima-zhu** [comment]
The steps in `Build`
1. Taking project list:
  - Build and Package: Taking project list
  - Detect API changes: Taking the artifacts from build package steps. Condition on: 1. artifact is newsdk and 2. changed files are in artifacts.
 - Build DocFx Documenttion Site
2. Single service directory:
 - Update package properties with dev version

**Comment by sima-zhu** [comment]
The steps in `Compliance`:
1. The job is scan against changed files in PR.

**Comment by m-nash** [comment]
@sima-zhu and @weshaggard The original intention of this issue is now complete.  Are we using this issue to track follow up work as well or is it safe to close this?

**Comment by weshaggard** [comment]
I'd like to keep this open for now because what we have is still in testing from my perspective.

**Comment by weshaggard** [comment]
@benbp this is a case study when you start thinking about the pipeline changes.
