### ISSUE TITLE
[BUG] Microsoft.Azure.Management.ContainerInstance.Models.InstanceView.CurrentState.State is always empty 

### ISSUE THREAD

**Issue by lidong-zhao** [Azure/azure-sdk-for-net#31058]
### Library name and version

Assembly Microsoft.Azure.Management.ContainerInstance, Version=7.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35

### Describe the bug

I am trying to get the state of a Azure Container Group's container, here is my code: 

`
 IAzure azure = Microsoft.Azure.Management.Fluent.Azure.Authenticate(azureCredential).WithSubscription(_containerOptions.AzureSubscriptionId);
            var response = (await client.ContainerGroups.ListByResourceGroupWithHttpMessagesAsync(_containerOptions.ResourceGroup));

            foreach (var containerGroup in response.Body.Where(cg=>cg.ProvisioningState == "Succeeded" && 
                cg.Name.StartsWith(_containerOptions.AzureContainerPrefix, StringComparison.InvariantCultureIgnoreCase)))
            {
                If (containerGroup.Containers[0].InstanceView.CurrentState.State == "something")
                {
                       do something
                }
`
           

### Expected behavior

Microsoft.Azure.Management.ContainerInstance.Models.InstanceView.CurrentState.State should return actual state of a container, such as Running, Failed, Terminated, etc

### Actual behavior

It returns empty string

### Reproduction Steps

deploy a container instance, using helloworld image.
use the code above to get the state of that container

### Environment

I run that code in Azure function

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by lidong-zhao** [comment]
The same issue happens to Azure.ResourceManager.ContainerInstance 1.0.0 as well.

**Comment by xboxeer** [comment]
> The same issue happens to Azure.ResourceManager.ContainerInstance 1.0.0 as well.

@lidong-zhao  can you share your code using the Azure.ResourceManager.ContainerInstance library?  We are deprecating  Microsoft.Azure.Management.ContainerInstance and we recommand developers migrate to Azure.ResourceManager.* as soon as possible.

**Comment by lidong-zhao** [comment]
@xboxeer here is my code:
`
 var resourceGroupId = ResourceGroupResource.CreateResourceIdentifier(_containerOptions.AzureSubscriptionId, _containerOptions.ResourceGroup);
            var rg = armClient.GetResourceGroupResource(resourceGroupId);
            var containerGroups = rg.GetContainerGroups();
foreach (var containerGroup in containerGroups)
{
    // try to read container's state, see the screenshot for detail
}
`
I was expecting the containerGroup.Data.Containers[0].InstanceView can give the state of that container, but it is always null: 
![image](https://user-images.githubusercontent.com/73622279/204617840-754b7644-15de-412b-8ea4-83f324d82692.png)

**Comment by jaltin** [comment]
I am also trying to find the state of the ContainerGroup, and just like @lidong-zhao I have InstanceView null (see attached screenshot). 

Is there another way to find the state of a container group? I personally only need to know on container group level, so if that is possible to check without having to look at the individual containers in the group, then that would be great. 

![Screenshot 2023-04-24 at 12 28 28](https://user-images.githubusercontent.com/2103778/233971455-2ca5d52a-6c3d-46ff-9042-9ae21f56b569.jpg)

**Comment by gb-8** [comment]
Any update on this? I have the same issue using Azure.ResourceManager.ContainerInstance 1.0.1.
How can I get the status of individual containers in a group?

Code to repro:

```
            string resourceGroupName = "xxxx";
            var client = new ArmClient(new AzureCliCredential());
            var subscription = await client.GetSubscriptions().GetAsync("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx", CancellationToken.None);
            var resourceGroup = await subscription.Value.GetResourceGroups().CreateOrUpdateAsync(
                WaitUntil.Completed,
                resourceGroupName,
                new ResourceGroupData(AzureLocation.BrazilSouth)
            );
            var containerGroups = resourceGroup.Value.GetContainerGroups();
            var instanceView = containerGroups.First().Data.InstanceView;
            if (instanceView == null)
            {
                Console.WriteLine("How do I get the instance view?");
            }

```

**Comment by xboxeer** [comment]
@ArthurMa1978

**Comment by jaltin** [comment]
Any update on this from MS peole?

Thx :)

**Comment by jaltin** [comment]
I think I found the solution to this in another issue (https://github.com/Azure/azure-sdk-for-net/issues/35764#issuecomment-1557153832).

@gb-8, can you try this? I am just typing here in github so haven't tested it is 100% syntactically correct, but you get the idea: 

```
string resourceGroupName = "xxxx";
var client = new ArmClient(new AzureCliCredential());
var subscription = await client.GetSubscriptions().GetAsync("xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx", CancellationToken.None);
var resourceGroup = await subscription.Value.GetResourceGroups().CreateOrUpdateAsync(
    WaitUntil.Completed,
    resourceGroupName,
    new ResourceGroupData(AzureLocation.BrazilSouth)
);
var containerGroups = resourceGroup.Value.GetContainerGroups();

var firstContainerGroup = containerGroups.First();

// Getting container group state works as expected
var containerGroupState = firstContainerGroup.Data.ProvisioningState;

// Won't work as instanceView is null
var firstContainerInstanceView = firstContainerGroup.Data.Containers[0].InstanceView;

// Get access to the container data by using GetAsync()
var firstRetreivedContainerGroup = await firstContainerGroup.GetAsync()

// This will work, you can read state from the InstanceView or do whatever else you need from it
var retrievedFirstContainerInstanceView = firstRetreivedContainerGroup.Value.Data.Containers[0].InstanceView;
var containerState = retrievedFirstContainerInstanceView.CurrentState;

```

The key here is to call `.GetAsync()` on the containerGroup to load the full data. 

I hope it works for you!
