### ISSUE TITLE
[BUG] EmailRecipients constructor - BCC null check is wrong

### ISSUE THREAD

**Issue by jakubornass** [Azure/azure-sdk-for-net#31054]
### Library name and version

Azure.Communication.Email 1.0.0-beta.1

### Describe the bug

The referred constructor: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/communication/Azure.Communication.Email/src/Models/EmailRecipients.cs

In line 35 you can see that BCC collection is initialized only if the following condition is met: `if (cc != null)`. The `bcc` parameter should be checked instead.

There are at least 2 consequences for that:
1. you will get `NullReferenceException` on `bcc.ToList()` if you pass `cc` list and do not provide `bcc`
2. `BCC` list will not be initialized at all if you won't pass any `cc` value

### Expected behavior

`CC` and `BCC` initialization should work separately without issues.

### Actual behavior

`CC` and `BCC` are bound to each other. You actually need to provide both or none of them. If you provide only one, you will fail.

### Reproduction Steps

1st scenario mentioned in description:
`var recipients = new EmailRecipients(new[] {new EmailAddress("")}, cc: Array.Empty<EmailAddress>());`

2nd scenario:
`var recipients = new EmailRecipients(new[] {new EmailAddress("")}, bcc: new[] {new EmailAddress("")});`

**Comment by PramodValavala-MSFT** [comment]
@jakubornass Thanks for catching that! We will work up a PR to update accordingly.
