### ISSUE TITLE
[BUG] Service Bus - Renew Message Lock Exception

### ISSUE THREAD

**Issue by gt-adam** [Azure/azure-sdk-for-net#31053]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.7.0
Azure.Messaging.ServiceBus 7.10.0

### Describe the bug

An unexpected error occurs terminating the process whilst attempting to renew a message lock within a V4 Azure Function (.NET 6 in process) using the Service Bus Queue Trigger.

Using the following libraries and their versions:
Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.7.0
Azure.Messaging.ServiceBus 7.10.0

### Expected behavior

The message lock is renewed for the duration set for the service bus queue.

### Actual behavior

An error occurs whilst attempting to renew the message lock throwing an exception with the following message: 

`System.Private.CoreLib: Exception while executing function: ImportServiceBus. System.Private.CoreLib: Could not find the resource "Azure.Messaging.ServiceBus.Resources.resources" among the resources "" embedded in the assembly "Microsoft.Azure.WebJobs.Extensions.ServiceBus", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.`

The actual exception is:
`System.Resources.MissingManifestResourceException`

### Reproduction Steps

To reproduce, it requires the following:

- Azure Service Bus Queue (in the example code below, this queue is called 'import queue') with sessions enabled
- V4 Azure Function (in process .NET 6) using the service bus queue trigger
- Add aforementioned packages (in bug description) to project using Nuget
- Use the following code below to replace the pre-existing run method for the function.

`public async Task Run([ServiceBusTrigger("import-queue", Connection = "ConnectionString", IsSessionsEnabled = true)] ServiceBusReceivedMessage message, ServiceBusSessionMessageActions sessionActions, ServiceBusReceiveActions receiveActions)  
{  
await sessionActions.RenewMessageLockAsync(message);
return;}`

- Run the function
- Send a message to queue and an error occurs when attempting to call the renew message lock

### Environment

Windows 10 .NET 6 (6.0.302)
Microsoft Visual Studio Community 2022 (64-bit) 17.2.6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @gt-adam, 
Thanks for filing this issue. There was a problem with how we were using shared resource strings in the Service Bus extension library. We will get this fixed, which would prevent the error you are seeing from occurring. Instead, you would see the actual contents of the resource string corresponding to the exception that the library is attempting to throw. You are attempting to renew the message lock for a session enabled entity, which is not allowed. Instead, you'd need to renew the session lock by calling [RenewSessionLockAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.webjobs.servicebus.servicebussessionmessageactions.renewsessionlockasync?view=azure-dotnet#microsoft-azure-webjobs-servicebus-servicebussessionmessageactions-renewsessionlockasync(system-threading-cancellationtoken)).

**Comment by gt-adam** [comment]
Hi @JoshLove-msft,

I had figured that was the case not long after submitting the ticket and it makes total sense after viewing the documentation link that you sent. I wasn't able to find any examples of it being used (only the RenewMessageLockAsync) on GitHub and was following the older approach to session-based queues from the Microsoft.Azure.ServiceBus library that we are upgrading from.

Many thanks!

Adam
