### ISSUE TITLE
[FEATURE REQ] Multiple feature requests to improve overall usability of Azure Search SDK

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#31055]
### Library name

Azure.Search.Documents 11.3.0

### Please describe the feature.

I am just reiterating the closed issues just in case someone can help us with any of them. It would help us with overall usability of Azure Search and its SDK.

https://github.com/Azure/azure-sdk-for-net/issues/20350

https://github.com/Azure/azure-sdk-for-net/issues/23569

In addition to this, it would be great if Azure Search also starts supporting hard deletes for documents. Currently it only supports Soft Delete Detection policy.

**Comment by pallavit** [comment]
Thank you for the feedback. These features are currently not supported by the search service and so are not available in the SDK.

Looping in @dereklegenzoff from the search service team to see if they have suggestions here.
/cc: @ShivangiReja

**Comment by dereklegenzoff** [comment]
Hi @ssghoda thanks for flagging these feature requests again. Rest assured that we've seen your requests and are considering them for future releases. Unfortunately, to be fully transparent with you, I can tell you that I don't expect that we'll have either of these features available for customers in the near future. I'm certainly happy to discuss workarounds with you in the interim though.

Regarding workarounds, https://github.com/Azure/azure-sdk-for-net/issues/23569 already captures the best workarounds there. For https://github.com/Azure/azure-sdk-for-net/issues/20350, you'd currently need to pull in a separate library that can compute distances between geo points and use that to augment your results. This [API from Azure Maps looks promising]( https://docs.microsoft.com/en-us/rest/api/maps/spatial/get-great-circle-distance?tabs=HTTP).

**Comment by ssghoda** [comment]
Hi @dereklegenzoff I understand. You had suggested those workarounds and I am following the same. It's just that to calculate distance from a given point or to select sub-documents you have to go though all results and perform that action. So it would be great to do this at Data level than Application level, something that we are able to do with Azure Cosmos Db. Thanks for your response though. I was just checking if there was any movement on this. :)

**Comment by weitang-work** [comment]
Glad to see ppl raising these feature requests again. Really need this feature to actually adapt Azure Cognitive Search in the project.

**Comment by a2741890** [comment]
Glad to see ppl raising these feature requests again. Really need this feature to actually adapt Azure Cognitive Search in the project.

**Comment by ShivangiReja** [comment]
This feature request is specifically for the service team, and the SDK can only incorporate features that are supported by the service. If you have any questions related to the search service, please raise an issue at [Azure Search · Community](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8). For any SDK-related questions, feel free to create issues on [Azure SDK for .NET Github](https://github.com/Azure/azure-sdk-for-net/issues).
