### ISSUE TITLE
Azure Identity October Release Doc Consistency Review

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#31064]
tracking item for README, Samples, TROUBLESHOOT, and Changelog consistency review

**Comment by pvaneck** [comment]
Notable consistency updates:

### README

- As a part of https://github.com/Azure/azure-sdk-for-net/issues/27777, in the ["DefaultAzureCredential"](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#defaultazurecredential) key concept section, add a disclaimer about `VisualStudioCodeCredential` and remove VSCodeCredential from diagram and list.


#### General consistency + issues

- [ ] Add a "Cloud configuration" section ([Example](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/identity/azure-identity#cloud-configuration))
- [ ] Provide or link to example for `ManagedIdentityCredential` in ["Managed Identity Support"](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#managed-identity-support) section.
- [ ] Add a "Reference" column to ["Credential Class"](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#managed-identity-support) tables. See this [example](https://github.com/Azure/azure-sdk-for-python/blob/2fd92599e4af672199a5119c0a238c6e1547552b/sdk/identity/azure-identity/README.md#credential-classes)
-

### TROUBLESHOOTING

- [ ] Update wording in ["Troubleshoot Multi Tenant Authentication Issues"](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/TROUBLESHOOTING.md#troubleshoot-multi-tenant-authentication-issues)
     - "This error was added as part of ~~functional~~ a breaking change to multi tenant authentication..."
- [ ] Update ["Troubleshoot environment credential authentication issues"](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/TROUBLESHOOTING.md#troubleshoot-environmentcredential-authentication-issues) section to include a reference to `AZURE_CLIENT_CERTIFICATE_PASSWORD`.
  - "...ensure the variables `AZURE_CLIENT_ID`, `AZURE_TENANT_ID`, `AZURE_CLIENT_CERTIFICATE_PATH`, and optionally `AZURE_CLIENT_CERTIFICATE_PASSWORD` are properly set."
- [ ] Create a **"Troubleshoot `ClientAssertionCredential` Authentication Issues"** section which was added by JS a few months ago.
    - [Reference](https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/identity/identity/TROUBLESHOOTING.md#client-assertion-credential-issues)

### Samples
 - .NET seems to be the only SDK without Redis samples.

**Comment by pvaneck** [comment]
FYI, Reference readme + troubleshooting has been merged: https://github.com/Azure/azure-sdk-for-python/pull/26483 
I have notated the majority of the changes that should be made in the above comment. Let me know if additional assistance is needed.
