### ISSUE TITLE
[BUG] Cannot Get Data Factory Pipeline Run Status

### ISSUE THREAD

**Issue by Shamister** [Azure/azure-sdk-for-net#31085]
### Library name and version

Microsoft.Azure.Management.DataFactory

### Describe the bug

This throws an error

var run = client.Pipelines.CreateRunWithHttpMessagesAsync(_dataFactory.ResourceGroupName, _dataFactory.FactoryName, _dataFactory.StartPipelineName, parameters: parameters).Result.Body;

### Expected behavior

Return the Response object instead

### Actual behavior

throw an error

Microsoft.Rest.Azure.CloudException: 'Api version '2018-06-01' is not available for your subscription. Please contact customer support for assistance with this feature: https://azure.microsoft.com/support/options/'

### Reproduction Steps

var provider = _tokenProviderService.GetProvider();
var token = provider.GetAccessTokenAsync("https://management.azure.com", _dataFactory.TenantId);

ServiceClientCredentials credentials = new TokenCredentials(token.Result);
DataFactoryManagementClient client = new DataFactoryManagementClient(credentials);

client.SubscriptionId = _dataFactory.SubscriptionId;

var parameters = new Dictionary<string, object>{};

var run = client.Pipelines.CreateRunWithHttpMessagesAsync(_dataFactory.ResourceGroupName, _dataFactory.FactoryName, _dataFactory.StartPipelineName, parameters: parameters).Result.Body;

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Shamister** [comment]
Hi @jsquire thanks for your reply

Somehow it is working now, I could not figure out what happened
