### ISSUE TITLE
[QUERY] Spatial Anchors cannot locate assembly

### ISSUE THREAD

**Issue by YaYaxueYu0** [Azure/azure-sdk-for-net#31084]
### Library name and version

Microsoft.Azure.SpatialAnchors.AnchorLocateCriteria..ctor 

### Query/Question

DllNotFoundException: AzureSpatialAnchors assembly:<unknown assembly> type:<unknown type> member:(null) 
Microsoft.Azure.SpatialAnchors.AnchorLocateCriteria..ctor () (at Library/PackageCache/com.microsoft.azure.spatial-anchors-sdk.windows@62b3e83507a2/Runtime/AzureSpatialAnchorsBridge_Windows.cs:1938) 
AnchorModuleScript. Start () (at Assets/MRTK.Tutorials.AzureSpatialAnchors/Scripts/AnchorModuleScript.cs:42)

**Comment by navba-MSFT** [comment]
@YaYaxueYu0 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. 

Could you please check if the plan suggested in [this](https://github.com/Azure/azure-spatial-anchors-samples/issues/23#issuecomment-487812797) and [this](https://github.com/MicrosoftDocs/azure-docs/issues/46193#issuecomment-575258546) comment helps ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@YaYaxueYu0 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.
