### ISSUE TITLE
[BUG] Null reference exception in isolated Function application

### ISSUE THREAD

**Issue by torepaulsson** [Azure/azure-sdk-for-net#31094]
### Library name and version

Azure.Messaging.ServiceBus, v. 7.10.0.0/omewhere it uses 7.8.0.0

### Describe the bug

I've noticed that my out-of-process Azure Function app fail sometime with a LOT of NullReferenceException that are thrown from `Azure.Mesaging.ServiceBus.ReceiverManager.RenewMessageLockAsync`.

Checking the logs in log analytics I get a long list of exceptions:
![image](https://user-images.githubusercontent.com/10498076/189899837-7a262b21-c029-4c43-81ee-180816a13c04.png)
For some reason the logs also come from the same operationid, this error is *logged around 7600 times*.

My function app use 7.10.0.0 but it seems the version 7.8.0.0 is used somewhere (since that is in the stack trace).

Call stack:
```
System.NullReferenceException:
   at Azure.Messaging.ServiceBus.ReceiverManager+<RenewMessageLockAsync>d__18.MoveNext (Azure.Messaging.ServiceBus, Version=7.8.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8)
```

FormattedMessage:
```
Message processing error (Action=RenewLock, EntityPath=<subscription>, Endpoint=<servicebus-endpoint>)
```

At the top of the execution a TaskCanceledException is thrown. I wonder if this has to do with when a instance is being terminated?

### Expected behavior

No NullReferenceException is thrown.

### Actual behavior

NullReferenceException is thrown.

### Reproduction Steps

* Create a out of process function app with a service bus trigger to a topic with subscription.
* Trigger the function app 50 times per second (could vary from 30-60 requests per second).
* See the error (hopefully) occurs, I see it around after 20 minutes.

### Environment

Windows
dotnet6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
@torepaulsson,
This NullReferenceException was an issue in 7.8.0 that was fixed in 7.8.1. Can you include your projects dependencies so we can try to understand where this version is getting pulled in?

**Comment by JoshLove-msft** [comment]
I think this may be due to how dependencies work when using isolated functions. I've reached out to the Functions team for more info.

**Comment by JoshLove-msft** [comment]
It looks like we will need a new version of the isolated worker to be shipped. I'm transferring this issue over to repo that has the worker project.

**Comment by JoshLove-msft** [comment]
Issue moved to [Azure/azure-functions-dotnet-worker #1031](https://github.com/Azure/azure-functions-dotnet-worker/issues/1031) via [**Zenhub**](https://www.zenhub.com/)
