### ISSUE TITLE
The example does not show how to actually create a new serializer

### ISSUE THREAD

**Issue by gorygregory** [Azure/azure-sdk-for-net#31114]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bcf65e06-a315-9182-3fb6-a2926733ad10
* Version Independent ID: e2e4e384-de01-a52e-5c00-f49fd8561a0f
* Content: [CosmosClientOptions.Serializer Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.cosmosclientoptions.serializer?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/CosmosClientOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@gorygregory We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@gorygregory You can refer to [CosmosSystemTextJsonSerializer.cs](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs) get sample serializer code. Thanks.

**Comment by SaurabhSharma-MSFT** [comment]
@gorygregory We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
