### ISSUE TITLE
[QUERY] Dynamic Spark pool allocation

### ISSUE THREAD

**Issue by LuminousFish** [Azure/azure-sdk-for-net#31119]
### Library name and version

Azure.Analytics.Synapse.Artifacts 1.0.0-preview.15

### Query/Question

I would like to find which Spark Pool is being used, and which has free resources, in order to choose a pool dynamically at runtime, based on availability.

I do not believe [BigDataPoolResourceInfo](https://docs.microsoft.com/en-us/dotnet/api/azure.analytics.synapse.artifacts.models.bigdatapoolresourceinfo?view=azure-dotnet-preview) can tell us that?

Thank you

### Environment

Microsoft Visual Studio Enterprise 2022 (64-bit) - Version 17.2.7
.Net 6.0

**Comment by SaurabhSharma-MSFT** [comment]
@LuminousFish We are looking into it and get back to you for any additional information.

**Comment by LuminousFish** [comment]
Thank you @SaurabhSharma-MSFT ,

in addition to the above, does [BigDataPoolsClient](https://docs.microsoft.com/en-us/dotnet/api/azure.analytics.synapse.artifacts.bigdatapoolsclient?view=azure-dotnet-preview) support creating a pool ?

**Comment by SaurabhSharma-MSFT** [comment]
@LuminousFish Regarding your first ask - Currently this scenario is not supported through .net sdk, but you can use the below REST API endpoint to get the details about all spark pools in your workspace along with other details like size, numberofactiveinstances, cpuallocation, etc. `https://{synapseworkspace}.dev.azuresynapse.net/monitoring/workloadTypes/spark/sparkpools?api-version=2020-10-01-preview`
Also, BigDataPoolsClient does not support creating a pool.
Please let me know if you have any other questions, else we will proceed with the issue closure. Thanks

**Comment by LuminousFish** [comment]
Thank you @SaurabhSharma-MSFT for your time.
