### ISSUE TITLE
[Service Bus] Consider converting resource strings into shared constants

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#31124]
We currently define a `resx` file in the Service Bus project. This cannot easily be shared across libraries, so we are not able to reuse it in the Functions extensions. There isn't really any reason to have the resx files as we have no plans to localize these strings. We could instead just define anything that needs to be reused in a constants file, or for one-off errors, just define the message inline.

**Comment by jsquire** [comment]
I'm going to close the tracking item out for this.   I have a feeling that if we do it, it will be a spontaneous effort because the resx file annoys someone trying to do something unrelated.
