### ISSUE TITLE
[BUG] Search: Protocol validation prevents use with local emulator

### ISSUE THREAD

**Issue by justinmchase** [Azure/azure-sdk-for-net#31123]
### Library name and version

Azure.Search.Documents

### Describe the bug

On this line:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/SearchClient.cs#L196

Its throwing an error if the endpoint isn't `https`. I am using an emulator for local development and it is `http` instead. This class shouldn't attempt to validate the scheme, it's not really its concern.

### Expected behavior

I expect it to _not_ throw an exception when provided an `http` scheme endpoint url.

### Actual behavior

It throws an `ArgumentException` saying the scheme must be `https`.

### Reproduction Steps

```
new SearchClient("http://localhost:8080", "test", null);
```

### Environment

```
> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.5
 OS Platform: Darwin
 RID:         osx.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  5.0.400 [/usr/local/share/dotnet/sdk]
  6.0.200 [/usr/local/share/dotnet/sdk]
  6.0.201 [/usr/local/share/dotnet/sdk]
  6.0.202 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by ShivangiReja** [comment]
By default, we do secure communication (https) over the wire. Even [service throws exception](https://docs.microsoft.com/en-us/rest/api/searchservice/http-status-codes#common-http-status-codes) if we send http request:
<body>


502 Bad Gateway | This error occurs when you enter HTTP instead of HTTPS in the connection.
-- | --



</body>
</html>


I believe If you're using an emulator for local development, you can add HTTP support for our clients with a custom pipeline policy. Here’s how you can add:
```csharp
SearchClientOptions options = new();
options.AddPolicy(new UnsafeForceHttpPolicy(), HttpPipelinePosition.PerCall);
Uri endpoint = new Uri("https://<resource-name>.search.windows.net");
SearchClient client = new SearchClient(endpoint, indexName, new AzureKeyCredential("<PrimaryApiKey>"), options);

public class UnsafeForceHttpPolicy : HttpPipelineSynchronousPolicy
{
    public override void OnSendingRequest(HttpMessage message) => message.Request.Uri.Scheme = "http";
}
```

In this sample, `https` endpoint will let it get past the validation in the [constructor](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/SearchClient.cs#L196)  but the pipeline will flip it to `http` before we send anything.

**Comment by justinmchase** [comment]
@ShivangiReja That is very clever thanks.

The actual url I need would be `localhost` instead of `<resource-name>.search.windows.net` could I change the host to be `localhost` in that same policy in that same way as well? Seems like it should work.

**Comment by ShivangiReja** [comment]
If you just want to pass the different host, then you can pass it to the client directly like:
```csharp
SearchClientOptions options = new();
options.AddPolicy(new UnsafeForceHttpPolicy(), HttpPipelinePosition.PerCall);
Uri endpoint = new Uri(""https://localhost:8080"");
SearchClient client = new SearchClient(endpoint, indexName, new AzureKeyCredential("<PrimaryApiKey>"), options);

public class UnsafeForceHttpPolicy : HttpPipelineSynchronousPolicy
{
    public override void OnSendingRequest(HttpMessage message) => message.Request.Uri.Scheme = "http";
}
```

But if you want to update the whole uri and not include the path, api version.. etc for the method which we set in the SDK, then you can update the uri using the custom scheme like:

```csharp
    public class UnsafeForceHttpPolicy : HttpPipelineSynchronousPolicy
    {
        public override void OnSendingRequest(HttpMessage message)
        {
            var uri = new RawRequestUriBuilder();
            uri.AppendRaw("http://localhost:8080", false);
            message.Request.Uri = uri;
        }
    }
```

**Comment by ShivangiReja** [comment]
@justinmchase If you just want to pass the different host, then you can pass it to the client directly like:
```csharp
SearchClientOptions options = new();
options.AddPolicy(new UnsafeForceHttpPolicy(), HttpPipelinePosition.PerCall);
Uri endpoint = new Uri(""https://localhost:8080"");
SearchClient client = new SearchClient(endpoint, indexName, new AzureKeyCredential("<PrimaryApiKey>"), options);

public class UnsafeForceHttpPolicy : HttpPipelineSynchronousPolicy
{
    public override void OnSendingRequest(HttpMessage message) => message.Request.Uri.Scheme = "http";
}
```

But if you want to update the whole uri and not include the path, api version.. etc for the method which we set in the SDK, then you can update the uri using the custom scheme like:

```csharp
    public class UnsafeForceHttpPolicy : HttpPipelineSynchronousPolicy
    {
        public override void OnSendingRequest(HttpMessage message)
        {
            var uri = new RawRequestUriBuilder();
            uri.AppendRaw("http://localhost:8080", false);
            message.Request.Uri = uri;
        }
    }
```

**Comment by ShivangiReja** [comment]
@justinmchase Yes, you can update the host using the custom policy but If you just want to pass the different host, then you can pass it to the client directly like:
```csharp
SearchClientOptions options = new();
options.AddPolicy(new UnsafeForceHttpPolicy(), HttpPipelinePosition.PerCall);
Uri endpoint = new Uri("https://localhost:8080");
SearchClient client = new SearchClient(endpoint, indexName, new AzureKeyCredential("<PrimaryApiKey>"), options);

public class UnsafeForceHttpPolicy : HttpPipelineSynchronousPolicy
{
    public override void OnSendingRequest(HttpMessage message) => message.Request.Uri.Scheme = "http";
}
```

If you want to update the whole uri and not include the path, api version.. etc for the method which we set in the SDK, then you can update the uri using the custom policy like:

```csharp
    public class UnsafeForceHttpPolicy : HttpPipelineSynchronousPolicy
    {
        public override void OnSendingRequest(HttpMessage message)
        {
            var uri = new RawRequestUriBuilder();
            uri.AppendRaw("http://localhost:8080", false);
            message.Request.Uri = uri;
        }
    }
```

**Comment by ShivangiReja** [comment]
Closing this issue as I believe it has been addressed. @justinmchase please feel free to reopen this issue or create a new one if you have any further questions. Thanks you!
