### ISSUE TITLE
[QUERY] How to retrieve stdout after execute a RunCommand?

### ISSUE THREAD

**Issue by dmattoninnovtech** [Azure/azure-sdk-for-net#31136]
### Library name and version

Azure.ResourceManager.Compute 1.0.0

### Query/Question

Hello,

I try to work with the new NuGet packages (Azure.ResourceManager, Azure.ResourceManager.Compute,...).
Right now, I can create or update a RunCommand on a Linux Virtual Machine. And I think, I can execute it.

But, I don't know how to retrieve the stdout of the RunCommand. For the moment, RunCommand execute _ifconfig_.

Extract of my code:
```csharp
var virtualMachineRunCommandResourceId = VirtualMachineRunCommandResource.CreateResourceIdentifier(_subscriptionId, _resourceGroupName, _vmName, runCommandName);
var virtualMachineRunCommand = _armClient.GetVirtualMachineRunCommandResource(virtualMachineRunCommandResourceId);

var result = virtualMachineRunCommand.GetAsync();
result.Wait();
var resourceData = result.Result.Value.Data;
```

When I check _resourceData_, I don't find anything interesting.

Packages:

- Azure.ResourceManager v1.3.1
- Azure.ResourceManager.Compute v1.0.0

Thanks for your help

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@dmattoninnovtech to run a command, you should use below code
```csharp
public void RunCommand(string resourceGroupName)
        {
            var vm = this._client.GetDefaultSubscription().GetResourceGroup(resourceGroupName).Value.GetVirtualMachine("elendiltest").Value;
            var cmdInput = new RunCommandInput("RunShellScript");
            cmdInput.Script.Add("ls");
            var runResult = vm.RunCommand(WaitUntil.Completed, cmdInput).Value;
            Console.Write(runResult.Value); 
        }
```
you can find out the stdout and stderr in `Message` property
![image](https://user-images.githubusercontent.com/5089150/192232162-0ce8d5a3-070e-47b3-b749-9b945341bc35.png)

**Comment by dmattoninnovtech** [comment]
Thanks @xboxeer, it works perfectly.

But how can I retrieve the stdout/stderr from my own command ?

**Comment by xboxeer** [comment]
@dmattoninnovtech by looking at this document, this seems to be a by design https://learn.microsoft.com/en-us/azure/virtual-machines/linux/run-command#available-commands
SDK team usually do not have a full picture of certain azure product, I think you can submit your feature request here https://feedback.azure.com/d365community/forum/ec2f1827-be25-ec11-b6e6-000d3a4f0f1c so that the product team can take it into consideration. 
If you have any more feedback to our SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)

**Comment by dmattoninnovtech** [comment]
OK, thanks!
