### ISSUE TITLE
Page should define MSAPassThrough

### ISSUE THREAD

**Issue by edwardskrod** [Azure/azure-sdk-for-net#31140]
I came to the page to figure out what this property does and is used for.  The current description didn't help much.  What is MSA? Why do Legacy Applications need it?  

More information to help the developer make an informed decision would be super useful.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af97da54-d81f-8cc1-8a1a-ba10ed5dc41b
* Version Independent ID: c82c4c28-89a1-950f-2b58-b1795045f54c
* Content: [WindowsBrokerOptions.MsaPassthrough Property (Microsoft.Identity.Client) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.windowsbrokeroptions.msapassthrough?view=azure-dotnet)
* Content Source: [xml/Microsoft.Identity.Client/WindowsBrokerOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Client/WindowsBrokerOptions.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Identity.Client` is maintained as [#3670](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3670).
