### ISSUE TITLE
Integrate travis with .NET SDK new vs17Dev CI jobs

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3115]
Travis has not been integrated with CI jobs on the new vs17Dev branch.
I tried adding the new script (already checked in the branch) recommended by .NET Core team.
I had enabled it for a day and jobs has been failing since.

**Comment by shawns1** [comment]
The 2 scripts in question are dotnet-install.sh and testSdkOnLinux.sh

**Comment by shahabhijeet** [comment]
Done
https://github.com/Azure/azure-sdk-for-net/pull/3169
