### ISSUE TITLE
[QUERY] When Is the Azure.Maps.Routing being released to nuget

### ISSUE THREAD

**Issue by samwdp** [Azure/azure-sdk-for-net#31152]
### Library name and version

Azure.Maps.Routing 1.0.0-beta

### Query/Question

When will this be released. There seems to be Azure.Maps packages being released. The readme's need to be updated to say if they are not released.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dubiety** [comment]
Hi @samwdp ,

Thank you for asking. We have published Azure Maps .NET SDK. 

| Nuget Links  | README | Samples |
|-------------|-----------|----------|
|[Azure.Maps.Search](https://www.nuget.org/packages/Azure.Maps.Search)| [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/maps/Azure.Maps.Search/README.md) | [Samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/maps/Azure.Maps.Search/samples)
|[Azure.Maps.Routing](https://www.nuget.org/packages/Azure.Maps.Routing) | [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/maps/Azure.Maps.Routing/README.md) | [Samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/maps/Azure.Maps.Routing/samples)
|[Azure.Maps.Rendering](https://www.nuget.org/packages/Azure.Maps.Rendering) | [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/maps/Azure.Maps.Rendering/README.md) | [Samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/maps/Azure.Maps.Rendering/samples)
|[Azure.Maps.Geolocation](https://www.nuget.org/packages/Azure.Maps.Geolocation) | [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/maps/Azure.Maps.Geolocation/README.md) | [Samples](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/maps/Azure.Maps.Geolocation/samples)

You can also refer to all Azure Maps REST SDK on [Microsoft Learn](https://learn.microsoft.com/en-us/azure/azure-maps/rest-sdk-developer-guide) and [C# SDK Developer Guide](https://learn.microsoft.com/en-us/azure/azure-maps/how-to-dev-guide-csharp-sdk). Welcome to give us any feedback or fire bugs. Thank you so much!
