### ISSUE TITLE
[BUG] [UWP] CallAgent.OnIncoming event is not fired up in UWP app

### ISSUE THREAD

**Issue by KamN-99** [Azure/azure-sdk-for-net#31167]
### Library name and version

Azure.Communication.Calling 1.0.0-beta.32 Azure.Communication.Identity 1.1.0

### Describe the bug

CallAgent.OnIncoming event is not fired up in UWP app. No information about incoming calls are available. I need to create an application which should capture Teams user incoming calls and send this information to other system depends on our company flows. I've based on quickstart example project: https://docs.microsoft.com/pl-pl/azure/communication-services/quickstarts/voice-video-calling/getting-started-with-calling?pivots=platform-windows. Unfortunately my app it's not working properly in case of capturing incoming calls events.  I think that Teams user access token used by me for my tests should be correct. My test app can make a call to other Teams user. I've also checked it by using it in quickstart example: https://docs.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-voice-video-calling-custom-teams-client. The JavaScript example works fine with same token (OnIncoming events are received when I call from test Teams user to user which access token is provided to example app).

### Expected behavior

CallAgent.OnIncoming event is fired up in UWP app.

### Actual behavior

CallAgent.OnIncoming event is not fired up in UWP app. No information about incoming calls are available. No errors were captured.

### Reproduction Steps

1. Create UWP project
2. Add Capabilities in appxmanifest: Microphone, Webcam, Internet (Client))
3. Add nuget packages: Azure.Communication.Calling, Azure.Communication.Identity
4. Add code below.
5. Change value of a accessToken variable to valid Teams user access token.
6. Build and run app.
7. Call from different Teams user to Teams user which access token provided in code.
8. Check if OnIncoming event was fired up.

```
using Azure.Communication;
using Azure.Communication.Calling;
	
public sealed partial class MainPage : Page
{

        CallAgent oCallAgent = null;
        CallClient oCallClient = null;
        IncomingCall oCall = null;

        public MainPage()
        {
            this.InitializeComponent();
            Init();            
        }

        public async Task Init()
        {
            string accessToken = "user access token";
            oCallClient = new CallClient();
                 
            CallAgentOptions callAgentOptions = new CallAgentOptions
            {
                DisplayName = "Test user"
            };
            

            CommunicationTokenCredential credentials = new CommunicationTokenCredential(accessToken);
            oCallAgent = await oCallClient.CreateCallAgent(credentials, callAgentOptions);
            oCallAgent.OnIncomingCall += OnIncoming;
            oCallAgent.OnCallsUpdated += OnStateChange;

            return;            
        }

        private void OnIncoming(object sender, IncomingCall incomingCall)
        {
			oCall = incomingCall
        }
        
        private void OnStateChange(object sender, CallsUpdatedEventArgs args)
        {

        }
}
```

### Environment

UWP project target: 
- min: Windows 10, version 1809 (10.0; Build 17763)
- target Windows 11 (10.0; Build 22000)

Microsoft Visual Studio Community 2019 Version 16.11.14

Microsoft Windows [Version 10.0.22000.856]
(c) Microsoft Corporation. Wszelkie prawa zastrzeżone.

dotnet --info
Zestaw .NET SDK (odzwierciedlenie dowolnego pliku global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Srodowisko uruchomieniowe:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.300 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by navba-MSFT** [comment]
Involving Service team to look into this.

@acsdevx-msft Could you please look into this and provide an update ? Thanks in advance.

**Comment by KamN-99** [comment]
Hi,
Is any progress in this case?
Best Regards

**Comment by jowang-msft** [comment]
@wladimir-k-m , looking at your message on 8/3, I see you have switched to our newer SDKs, which is good. So the code snippet you posted earlier was a bit old as it was based on previously deprecated beta SDKs. Just to make sure we understand the current issue you are facing, do I get it right that you are able to receive incoming call events with ACS to ACS calls, but not between PSTN? Is that right?

**Comment by wladimir-k-m** [comment]
@jowang-msft, Yes this is correct, Incoming call events for ACS audio calls are working (I didn't test video) but the events aren't fired for PSTN calls. I didn't post any code snippets so I'm assuming you are referring to the code of the OP but the code I was using is similar.

We are using the JavaScript SDK now since everything is working there quite well.
