### ISSUE TITLE
Diagram in ProvisioningServiceClient page isn't rendering properly

### ISSUE THREAD

**Issue by devlie** [Azure/azure-sdk-for-net#31173]
The diagram in the `Remarks` section of this page is not comprehensible due to improper rendering. Something's wrong in the markdown.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b12039a8-e5ea-15f2-c5b9-98e7b373e92a
* Version Independent ID: 870ace1b-4689-9e7d-42f7-443c414105d1
* Content: [ProvisioningServiceClient Class (Microsoft.Azure.Devices.Provisioning.Service) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.provisioning.service.provisioningserviceclient?view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Azure.Devices.Provisioning.Service/ProvisioningServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices.Provisioning.Service/ProvisioningServiceClient.xml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Devices.Provisioning.Service` library is maintained as [#2695](https://github.com/Azure/azure-iot-sdk-csharp/issues/2695).
