### ISSUE TITLE
Deeper investigation of Scope validation

### ISSUE THREAD

**Issue by schaabs** [Azure/azure-sdk-for-net#31170]
- Confirm definitive list of acceptable scope characters, and update `ScopeUtilities.ValidiateScope` accordingly
- Ensure all credentials passing scope to subprocesses are properly validating it.

**Comment by christothes** [comment]
It seems that ensuring we are isolating the parameters passed to the command line would be sufficient. Would it be enough to only disallow double quotes and ensure we are wrapping the argument to the process with double quotes?

**Comment by christothes** [comment]
Discussed this a bit more and we'll leave validation as is and amend as necessary, rather than trying to be proactively more permissive.
