### ISSUE TITLE
[BUG] Azure.Identity - ChainedTokenCredential gives up after encountering error with expired cert

### ISSUE THREAD

**Issue by ayeltsov** [Azure/azure-sdk-for-net#31175]
### Library name and version

Azure.Identity 1.6.1

### Describe the bug

To rotate certificates without downtime, we always download two latest certificates to the client machine and build ChainedTokenCredential with two ClientCertificateCredential:

```
	List<TokenCredential> credentials = new List<TokenCredential>();
<...>
			foreach (X509Certificate2 certificate in certicateCandidates)
			{
				credentials.Add(new ClientCertificateCredential(TenantId, ApplicationId, certificate, new ClientCertificateCredentialOptions() { SendCertificateChain = false }));
			}
<...>
	ChainedTokenCredential chainedTokenCredential = new ChainedTokenCredential(credentials.ToArray());
```

However, if first credential is "bad" (e.g. expired), ChainedTokenCredential does not try the other credential.

### Expected behavior

ChainedTokenCredential tries provided TokenCredential in sequence, giving up only when all fail

### Actual behavior

ChainedTokenCredential gives up if first TokenCredential in sequence is invalid

### Reproduction Steps

Set up AAD app with cert auth, and have 2 certificates - one expired and one unexpired.

Linqpad script I used:
```
#define TRACE

const string KeyVaultUrl = "https://***.vault.azure.net";
const string SubjectName = "***";
public const string TenantId = "***";
const string ApplicationId = "***"; 


void Main()
{
	TokenCredential tokenCredential;
	SecretClient secretClient;
	
	try
	{
		// This is the "happy" case where we get unexpired certificate first
		tokenCredential = BuildTokenCredential(latestFirst: true);
		secretClient = new SecretClient(new Uri(KeyVaultUrl), tokenCredential);

		KeyVaultSecret secret = secretClient.GetSecret("boo");
	}
	catch(Exception e)
	{
		e.Dump();
	}

	try
	{
		// This is the "unhappy" case where we get expired certificate first
		tokenCredential = BuildTokenCredential(latestFirst: false);
		secretClient = new SecretClient(new Uri(KeyVaultUrl), tokenCredential);

		KeyVaultSecret secret = secretClient.GetSecret("boo");
	}
	catch (Exception e)
	{
		e.Dump();
	}
}

private TokenCredential BuildTokenCredential(bool latestFirst)
{
	List<TokenCredential> credentials = new List<TokenCredential>();

	using (X509Store store = new X509Store(StoreName.My, StoreLocation.LocalMachine))
	{
		store.Open(OpenFlags.ReadOnly | OpenFlags.OpenExistingOnly);
		{
			// Devnote: "validOnly: false" is correct setting - whether client trusts the certificates is orthogonal to ability to authenticate with it
			IEnumerable<X509Certificate2> certicateCandidates =
				store.Certificates.Find(X509FindType.FindBySubjectName, SubjectName, validOnly: false)
				.OfType<X509Certificate2>();
				
			certicateCandidates = latestFirst ? certicateCandidates.OrderByDescending(certificate => certificate.NotBefore) : certicateCandidates.OrderBy(certificate => certificate.NotBefore);

			foreach (X509Certificate2 certificate in certicateCandidates)
			{
				Trace.TraceInformation(KeyVaultUrl, nameof(BuildTokenCredential),
					$"Will attempt to use certificate thumbprint {certificate.Thumbprint}, subject {certificate.Subject}, issuer {certificate.Issuer}, not after {certificate.NotAfter} with ApplicationId {ApplicationId}");
				credentials.Add(new ClientCertificateCredential(TenantId, ApplicationId, certificate, new ClientCertificateCredentialOptions() { SendCertificateChain = false }));
			}
		}
	}

	ChainedTokenCredential chainedTokenCredential = new ChainedTokenCredential(credentials.ToArray());
	return chainedTokenCredential;
}
```

In first case, I get `A secret with (name/id) boo was not found in this key vault` - which means authentication worked.

In second case, I get `ClientCertificateCredential authentication failed: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS700027: The certificate with identifier used to sign the client assertion is expired on application. [Reason - The key used is expired.`

### Environment

Windows 11, dotnet 5

**Comment by ayeltsov** [comment]
Some thoughts about potential suggestions.

Suggestion: "just add OrderByDescending by NotBefore"
Answer: 
1) not very discoverable. We experienced production downtime to learn about this. Other customers may have to go through something similar to re-discover.
2) this will expose similar issue at the beginning of certificate's lifetime when new cert is created but not yet granted permissions to all AAD apps

Suggestion: "filter out expired certificates"
Answer: same as "1)" above - it needs to be discovered

Suggestion: "do not let certificates expire, even the older version"
Answer: In ideal world all certs are auto-rotated well before expiration, and enabled for SN+I authentication. Unfortunately this is not always possible or will take time to get there.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @ayeltsov - Would it be better if you could instead refresh the certificate being used by the current credential in use at runtime? This is not possible currently, but it's a feature we are considering.

**Comment by christothes** [comment]
Discussed offline - The recommended approach here is to implement a custom `TokenCredential` to handle the cascading behavior requirements for this scenario.
