### ISSUE TITLE
[QUERY] How to query by Timestamp in Azure.Data.Tables?

### ISSUE THREAD

**Issue by oh-yeah** [Azure/azure-sdk-for-net#31171]
### Library name and version

Azure.Data.Tables 12.6.1.0

### Query/Question

I'm sure I'm just missing something here, but I'm having an issue trying to query entities from my tables when filtering only by Timestamp.  I've tried the following filter conditions to retrieve data:

**Expression Filter**
`var results = table.Query<TableEntity>(x => x.Timestamp >= DateTime.Parse("2021-09-10T14:26:22.251Z"))`
**OData Filter**
`var results = table.Query<TableEntity>(filter: "Timestamp ge datetime'2021-09-10T14:26:22.251Z'");`

As previously mentioned, both queries do not return any results. I've verified there's data in my table that satisfies this condition by running a  query that filters by a PartitionKey and inspecting the return data.  I'm on a fairly tight deadline for this work, so any help would be greatly appreciated!

### Environment

OS: Windows - net4.8
IDE: Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.3.4

**Comment by christothes** [comment]
Hi @oh-yeah  - Are you querying against a Cosmos table API?

**Comment by christothes** [comment]
Assuming you mean specifically the Cosmos Table API (as opposed to the storage tables API), this is a known issue of the service itself that is not currently documented. If your use case requires the ability to perform the Timestamp filter on the service side rather than client side, the workaround is to define an additional value to represent the TimeStamp value and query with that.

**Comment by oh-yeah** [comment]
Thanks for the quick response and your assumption is correct, I'm using the Cosmos Table API.  Is there any plans on addressing this issue?  The previous package that was deprecated, Microsoft.Azure.Cosmos.Table, supported filtering by Timestamp.

**Comment by christothes** [comment]
I'm not aware of any plans to address this issue. The reason this worked in the older package is that it utilized the Cosmos "direct mode" API under the covers, which was able to translate the Timestamp query to the Cosmos native `_ts` property.

**Comment by oh-yeah** [comment]
Thanks for the additional info.  I truly regret taking the time to upgrade to the "supported" Cosmos Table packages now.  I guess I'll either have to alter an unknown number of records across tens of thousands partitions for the suggested workaround :-1: or use the deprecated packages :+1:, easy choice.

**Comment by christothes** [comment]
@oh-yeah - I agree this is not a great experience - I did find that it is actually documented [here](https://docs.microsoft.com/en-us/azure/cosmos-db/table/tutorial-query-table#query-by-using-an-odata-filter) . That said, I'll relay the feedback.
