### ISSUE TITLE
After calling builder.AddAzureKeyVault() custom function route Prefix is reset to default

### ISSUE THREAD

**Issue by JSCProjects** [Azure/azure-sdk-for-net#31193]
### Library name and version

Azure.Extensions.AspNetCore.Configuration.Secrets 1.2.2

### Describe the bug

I've configured my prefix in the host.json file to routePrefix = "", but after calling AddAzureKeyVault and registering the configuration as IConfiguration as singleton my http functions are not accessible on the my route. 

```
configurationBuilder.AddAzureKeyVault(
    new Uri("url to keyvault"),
    new DefaultAzureCredential());

IConfiguration configuration = configurationBuilder.Build();
builder.Services.AddSingleton(configuration);
```

All my functions are now only accessible with the "api" prefix.

### Expected behavior

When I have a custom routePrefix configured in the host.json it should still respect that setting. 

### Actual behavior

I've configured my prefix in the host.json file to routePrefix = "", but after calling AddAzureKeyVault and registering the configuration as IConfiguration as singleton my http functions are not accessible on the my route. 

```
configurationBuilder.AddAzureKeyVault(
    new Uri("url to keyvault"),
    new DefaultAzureCredential());

IConfiguration configuration = configurationBuilder.Build();
builder.Services.AddSingleton(configuration);
```

All my functions are now only accessible with the "api" prefix.

### Reproduction Steps

See code above

### Environment

azure functions

**Comment by JSCProjects** [comment]
Seems to be related to https://github.com/Azure/azure-functions-host/issues/4363

**Comment by JoshLove-msft** [comment]
@JSCProjects have you tried the workaround mentioned here - https://github.com/Azure/azure-functions-host/issues/4363#issuecomment-634556821?

Since this appears to be a known issue and it is already filed with the correct team, I think we can probably close this as a duplicate.
