### ISSUE TITLE
[BUG] Azure.Storage.Blobs 12.13.1 - Azure.RequestFailedException: The value for one of the HTTP headers is not in the correct format.

### ISSUE THREAD

**Issue by aarondandy** [Azure/azure-sdk-for-net#31205]
### Library name and version

Azure.Storage.Blobs 12.13.1

### Describe the bug

When interacting with azurite 3.15.0 ~3.19.0~ using Azure.Storage.Blobs 12.13.1 I get an Azure.RequestFailedException while 12.13.0 works correctly. This may be related to https://github.com/Azure/Azurite/issues/1682 and https://github.com/Azure/Azurite/issues/1483 .

### Expected behavior

Connect to and interact with Azurite 3.15.0 ~3.19.0~ .

### Actual behavior

```
Azure.RequestFailedException: The value for one of the HTTP headers is not in the correct format.
RequestId:10b40cca-cf05-4423-9f3d-63e7a3216182
Time:2022-09-16T18:50:04.673Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Additional Information:
HeaderName: x-ms-version
HeaderValue: 2021-08-06

Content:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>InvalidHeaderValue</Code>
  <Message>The value for one of the HTTP headers is not in the correct format.
RequestId:10b40cca-cf05-4423-9f3d-63e7a3216182
Time:2022-09-16T18:50:04.673Z</Message>
  <HeaderName>x-ms-version</HeaderName>
  <HeaderValue>2021-08-06</HeaderValue>
</Error>

Headers:
Server: Azurite-Blob/3.15.0
x-ms-error-code: InvalidHeaderValue
x-ms-request-id: 10b40cca-cf05-4423-9f3d-63e7a3216182
Date: Fri, 16 Sep 2022 18:50:04 GMT
Connection: keep-alive
Keep-Alive: REDACTED
Transfer-Encoding: chunked
Content-Type: application/xml
```

### Reproduction Steps

1. Create a .NET application using Azure.Storage.Blobs 12.13.1 and connect to Azurite 3.15.0 ~3.19.0~ using `UseDevelopmentStorage=true`
2. Do azure bloby stuff.

### Environment

- Windows 10
- Azurite 3.15.0 ~3.19.0~
- dotnet 6
- Azure.Storage.Blobs 12.13.1

### Fix

Upgrade to azurite 3.19.0 or newer.

**Comment by jsquire** [comment]
//cc: @jongio for potential Azurite insights.

**Comment by blueww** [comment]
@aarondandy 

The API version "2021-08-06" is supported in Azurite from Azurite 3.18.0.
But you are using Azurite 3.15.0 (get it from the header `Server: Azurite-Blob/3.15.0`), so it still not support API version "2021-08-06".

Please either upgrade to latest Azurite (make sure you are running Azurite 3.19.0), or start Azurite with parameter "--skipApiVersionCheck" to make Azurite skip reporting error when API version no supported.

**Comment by aarondandy** [comment]
I was sure I checked the version with `azurite --version` inside the running container but I guess I confused myself. I updated to version 12.13.1 of the package again and it seems to be working fine with azurite 3.19.0 for me now. Somebody else out there running 3.15.0 is probably going to run into this, should I edit my issue and fix my versions?

**Comment by aarondandy** [comment]
I fixed the issue up to reduce confusion for other people who may encounter this.
