### ISSUE TITLE
Improve creation of VirtualMachine by providing a less verbose constructor or allowing Resources to be set

### ISSUE THREAD

**Issue by awesley** [Azure/azure-sdk-for-net#3120]
Hi,

This improvement request is for the following class

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.virtualmachine?view=azuremgmtcompute-14.1.0-prerelease

In a situation where you want to create a VirtualMachine and specify some resource (e.g. a Virtual Machine Extension) at the same time, you end up writing a lot of code due to the fact that Resources set' accessor is protected.

If it's unreasonable to change the accessibility of this property, perhaps consider a less verbose constructor.  Currently there are two - the default and one exposing parameters for each property.  As a result of these two situations (protected set and a verbose constructor), you may end up writing code like the following.

Without understanding why the property is read-only in the first place, making it settable seems more desirable than adding another constructor, as the argument can be made that that it's impossible to know which set of params are truly needed in a "less verbose" constructor.

```
            var vm = new VirtualMachine(
                         location,
                         null,
                         vmName,
                         null,
                         null,
                         null,
                         hardwareProfile,
                         storageProfile,
                         osProfile,
                         networkProfile,
                         null,
                         null,
                         null,
                         null,
                         null,
                         null,
                         new List<VirtualMachineExtension>
                         {
                             new VirtualMachineExtension
                             {
                                 Location = location,
                                 Settings = settings,
                                 ProtectedSettings = protectedSettings
                             }
                         });
```

**Comment by markcowl** [comment]
@awesley The low-level APIs are meant to mirror the actual REST API calls.  For a more directed experience at creating VMS, you might try the fluent libraries: https://www.nuget.org/packages/Microsoft.Azure.Management.Compute.Fluent/

**Comment by awesley** [comment]
@markcowl That makes sense and, like you say, is coherent with https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/virtualmachines-create-or-update

Thank you, I'll look at the Fluent APIs.
