### ISSUE TITLE
[BUG] Invalid format of value when trying to instantiate a generic implementation of Microsoft.Rest.ServiceClient

### ISSUE THREAD

**Issue by humbertosantiago** [Azure/azure-sdk-for-net#31249]
I'm trying to instantiate an generic implementation of class which inherits from ServiceClient class. 

**Message:** 
_Test method Datora.Proxies.SAPServiceLayer.Client.Test.EntityUnit.Query threw exception: 
System.FormatException: The format of value 'Datora.Proxies.SAPServiceLayer.Client.SAPSLEntityProxy`1[[Datora.Proxies.SAPServiceLayer.Entities.BusinessPartner, Datora.Proxies.SAPServiceLayer.Entities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=0020583cc5375c52]]' is invalid._

**Stack Trace:** 
`HeaderUtilities.CheckValidToken(String value, String parameterName)
ProductHeaderValue.ctor(String name, String version)
ServiceClient'1.InitializeHttpClient(HttpClientHandler httpClientHandler, DelegatingHandler[] handlers)
ServiceClient'1.ctor(HttpClientHandler rootHandler, DelegatingHandler[] handlers)
ServiceClient'1.ctor()
ProxyBase.ctor() line 24
ProxyBase.ctor(IBasicClientConfigEntry _configuration) line 28
SAPSLProxyBase.ctor(SAPSLClientConfig _config) line 17
SAPSLEntityProxy'1.ctor(SAPSLClientConfig _config) line 15
SAPSLClient.GetEntityProxy[TEntity]() line 43
EntityUnit.Query() line 30
ThreadOperations.ExecuteWithAbortSafety(Action action)`

I could see in ServiceClient source code that in InitializeHttpClient method the entry type name is used to fill _ProductInfoHeaderValue_ instance which will be added as _UserAgent_ client header.

What would be the issue here ? The length of full type name ? Is there a way to avoid this kind of issue without giving up a generic approach ?

**Comment by jsquire** [comment]
Hi @humbertosantiago.   Would you please be so kind as to provide the name and version of the Azure SDK package that you're using?

**Comment by humbertosantiago** [comment]
Hi @jsquire , I'm using the package Microsoft.Rest.ClientRuntime 3.0.3.

**Comment by jsquire** [comment]
@xboxeer, @m-nash:  The class in question appears to be related to the `mgmtcommon` area in the v3 codegen.   Would you please be so kind as to take a look and offer your thoughts?

**Comment by jsquire** [comment]
Thank you, @humbertosantiago.   I've looped in the team members best able to assist.

**Comment by HarveyLink** [comment]
Hi @humbertosantiago , this package will deprecate from this Sept, could you please try our latest Track2 SDK.
You could get start with: https://github.com/Azure/azure-sdk-for-net/blob/main/doc/dev/mgmt_quickstart.md
