### ISSUE TITLE
Enable OcrSkill and ImageAnalysisSkill and move to the latest preview swagger version in the search SDK

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#31248]
Swagger version - 
1. https://raw.githubusercontent.com/Azure/azure-rest-api-specs/904899a23a417768ce1ec1d5f89f33817f8ef8ad/specification/search/data-plane/Azure.Search/preview/2021-04-30-Preview/searchservice.json

2. https://raw.githubusercontent.com/Azure/azure-rest-api-specs/932e261a870475e1a29115f62def7bb84e4d7b38/specification/search/data-plane/Azure.Search/preview/2021-04-30-Preview/searchindex.json

Moving to this version also fixes the data connection issue reported by the customer here - https://github.com/Azure/azure-sdk-for-net/issues/29813 and the swagger change for this is at https://github.com/Azure/azure-rest-api-specs/pull/20376

**Comment by ShivangiReja** [comment]
This has been already implemented here: https://github.com/Azure/azure-sdk-for-net/pull/31176
