### ISSUE TITLE
Add samples for BinaryData

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#31273]
1. To serialize/deserialize from response.Content for dynamic cases

**Comment by tg-msft** [comment]
I basically want to do something like https://github.com/Azure/azure-sdk-for-net/pull/30167#discussion_r932613004 once we figure out the `dynamic` case with `JsonData`.

**Comment by jsquire** [comment]
This was added as part of the DynamicData work:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/DynamicContent.md
