### ISSUE TITLE
No guidelines regarding the lifecycle of the client

### ISSUE THREAD

**Issue by DimitrisK5** [Azure/azure-sdk-for-net#31282]
Creating a new instance of `HttpClient` on every request can lead to socket exhaustion. If the `DocumentAnalysisClient` uses an `HttpClient` or similar internally, creating a new instance of `DocumentAnalysisClient` on every request can also lead to socket exhaustion.

It would be nice to point out in this page or elsewhere in the documentation what are the recommended guidelines regarding the client. Should we use a single instance (or a few instances) for the entire lifecycle of our app? Is it ok to create a new instance each time?

On a related note, if a single instance is recommended, are the client methods thread-safe?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 85001c09-27e6-e148-5636-466cee185617
* Version Independent ID: e858d687-fa9e-1916-c5a6-a26eda23aeda
* Content: [DocumentAnalysisClient Class (Azure.AI.FormRecognizer.DocumentAnalysis) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.ai.formrecognizer.documentanalysis.documentanalysisclient?view=azure-dotnet)
* Content Source: [xml/Azure.AI.FormRecognizer.DocumentAnalysis/DocumentAnalysisClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.AI.FormRecognizer.DocumentAnalysis/DocumentAnalysisClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @DimitrisK5.  Thank you for reaching out and we regret that you're experiencing difficulties.  In short, the Azure SDK clients are intended to be treated as singletons.   They also share a single `HttpClient` instance unless your application is overriding the defaults and providing a custom `HttpClient` instance.

Client lifetime guidance is discussed [here](https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/) and is referenced from the [Overview](https://learn.microsoft.com/dotnet/api/overview/azure/ai.formrecognizer-readme?view=azure-dotnet#additional-concepts)/README for each Azure SDK library.

**Comment by DimitrisK5** [comment]
Thank you for the comprehensive answer! I have missed this section of the Overview page entirely.
