### ISSUE TITLE
[BUG] NotificationHubResource 'DebugSend' throws an exception with a successful notification when the status in not 201

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-net#31318]
### Library name and version

Azure.ResourceManager.NotificationHubs 1.0.0

### Describe the bug

When calling the DebugSend/DebugSendAsync on the NotificationHubResource, an exception is thrown. However, the contents of the exception indicate that the push was successful. Additionally, the exception includes which push notifications were successfully sent (gcm, apple, etc).

`Service request failed.\r\nStatus: 200 (OK)\r\n\r\nContent:\r\n{\"properties\":{\"success\":10,\"failure\":0,\"results\":[{\"applicationPlatform\":\"gcm\",\"outcome\":\"The Notification was successfully sent to the Push Notification System\"},`

There is an optional parameter for the DebugSend/DebugSendAsync that supplies content to the request. Regardless of whether  it is supplied, a 200 is returned.

![image](https://user-images.githubusercontent.com/92872703/191507400-aea817cb-569c-46f3-9984-96421df3a037.png)

In NotificationHubsRestOperations, the DebugSend that is called by the NotificationHubResource throws an exception for any status other than 201:

![image](https://user-images.githubusercontent.com/92872703/191509137-d2492a09-3394-4b47-826a-0cd6b42e419d.png)

### Expected behavior

`NotificationHubRestOperations` would not throw an exception for a 200 if the push notifications are successful or depending on the expected results of the Azure Management API, `NotificationHubResource` would not allow an optional parameter if an error would be thrown regardless.

The SDK expects a 201, which makes sense for a POST. So, I initially assumed it was related to a serialization issue of content that was passed to the API, but in that case, I would also expect the API to return a status code other than 200.

### Actual behavior

Without the message supplied to `NotificationHubResource DebugSend` and with a message supplied that was successfully used in the Azure Portal for testing, an error is thrown with a 200 status with the number of successful devices is supplied. 

### Reproduction Steps

Here is a small test snippet without the message passed:

`var client = new ArmClient(new DefaultAzureCredential());`
`var subscription = await client.GetDefaultSubscriptionAsync(token);`
`var resourceGroups = subscription.GetResourceGroups();`
`var resourceGroup = await resourceGroups.GetAsync(this.resourceGroupName, token);`
`var notificationNamespace = await resourceGroup.Value.GetNotificationHubNamespaceAsync(this.notificationHubNamespace,token);`
`var hubResource = await notificationNamespace.Value.GetNotificationHubAsync(this.notificationHubName, token);`
`var result = hubResource.Value.DebugSendAsync(cancellationToken: token);`

### Environment

.NET 6.0
Visual Studio Version 17.0.12

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
This bug has been fixed
      


            string serverName = Recording.GenerateAssetName("sql-server-");

            var sqlServer = await CreateDefaultSqlServer(serverName, AzureLocation.EastUS, _resourceGroup);
            var collection = sqlServer.GetSqlDatabases();

            string databaseName = Recording.GenerateAssetName("sql-database-");

            // 1.CreateOrUpdate
            SqlDatabaseData data = new SqlDatabaseData(AzureLocation.EastUS) { };
            var dataBase = await collection.CreateOrUpdateAsync(WaitUntil.Completed, databaseName, data);
            var metricDefinitionsList = dataBase.Value.GetMetricDefinitionsAsync();`

**Comment by ArthurMa1978** [comment]
Since this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
