### ISSUE TITLE
azure service bussss session processor

### ISSUE THREAD

**Issue by lifejoyforpy** [Azure/azure-sdk-for-net#31316]
### Library name and version

 Azure.Messaging.ServiceBus   7.5.1

### Describe the bug

i use    c#   7.5.1  Azure.Messaging.ServiceBus  sdk , use session queue consumer message . language is c#  .aspnetcore web .
  cause Azure.Messaging.ServiceBus.ServiceBusException: The session lock has expired on the MessageSession. Accept a new MessageSession. 
this exception cause my new message cannot consumer( some new message cannot execute by MessageHandler ) . how to consumer this message .

### Expected behavior

1

### Actual behavior

Azure.Messaging.ServiceBus.ServiceBusException: The session lock has expired on the MessageSession. Accept a new MessageSession. 

### Reproduction Steps

1

### Environment

aspnet core web  3.1
![1663758280226](https://user-images.githubusercontent.com/38183800/191488692-c595b06f-a2fc-4c77-8041-377d1baeb60b.jpg)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by lifejoyforpy** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lifejoyforpy** [comment]
![image](https://user-images.githubusercontent.com/38183800/191517736-0d98f652-60ae-4c9d-8378-643c93f959ba.png)

**Comment by JoshLove-msft** [comment]
This means that the session lock has expired. The session processor will eventually attempt to receive from the same session again. The reason for this happening could be that processing took longer than the configured [MaxAutoLockRenewalDuration](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussessionprocessoroptions.maxautolockrenewalduration?view=azure-dotnet#azure-messaging-servicebus-servicebussessionprocessoroptions-maxautolockrenewalduration), or there may have just been a transient network outage that caused the link to be lost. You can find more info about possible exceptions here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/TROUBLESHOOTING.md#find-information-about-a-servicebusexception.
