### ISSUE TITLE
Cosmos: Wrong Sample

### ISSUE THREAD

**Issue by dechev** [Azure/azure-sdk-for-net#31319]
The sample at the bottom of the page is for another extension.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 012cc796-3c1c-8a69-3051-2e4426caaa34
* Version Independent ID: fc75d957-b301-e3a6-5564-8a2bab1a2abc
* Content: [CosmosLinqExtensions.ToStreamIterator&lt;T&gt;(IQueryable&lt;T&gt;) Method (Microsoft.Azure.Cosmos.Linq) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.linq.cosmoslinqextensions.tostreamiterator?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos.Linq/CosmosLinqExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos.Linq/CosmosLinqExtensions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@dechev We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@dechev The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
