### ISSUE TITLE
[BUG] WaitForCompletionResponseAsync on ComputeArmOperation seems to be stuck in infinite loop

### ISSUE THREAD

**Issue by jonganej** [Azure/azure-sdk-for-net#31346]
### Library name and version

Azure.ResourceManager.Compute 1.0.0

### Describe the bug

When calling (and awaiting) `VirtualMachineResource.PowerOnAsync(Azure.WaitUntil.Completed)`, or `VirtualMachineResource.PowerOnAsync(Azure.WaitUntil.Started)` and then `ArmComputeOperation.WaitForCompleteResponseAsync()` thereafter, it seems the operation does not complete in a foreseeable amount of time. 

Specifically, my underlying (Linux) VM is already good and ready to go (SSH-able) in around 1-2min but the operation can go on for more than 5 minutes without any response. 

### Expected behavior

`PowerOnAsync(Azure.WaitUntil.Completed)` should return once the VM has started (usually not more than 1-2 min).

### Actual behavior

`PowerOnAsync(Azure.WaitUntil.Completed)` stays in an infinite loop as seen in `WaitForCompletionAsync(bool async, OperationInternalBase operation, TimeSpan? suggestedInterval, CancellationToken cancellationToken)` in `OperationPoller.cs`

### Reproduction Steps

Calling `PowerOnAsync(Azure.WaitUntil.Completed)` on `VirtualMachineResource`.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @jonganej , Thank you for using Azure SDK for .NET.
We can't repro your issue on our machine with following code: 
```
    var rg = (await sub.GetResourceGroups().GetAsync("rgName")).Value;
    var collection = rg.GetVirtualMachines();
    var vm = (await collection.GetAsync("vmName")).Value;
    await vm.PowerOffAsync(WaitUntil.Completed);
    Console.WriteLine("PowerOff");
    await vm.PowerOnAsync(WaitUntil.Completed);
    Console.WriteLine("PowerOn");
```
Please try the latest package and see if the issue is resloved.
