### ISSUE TITLE
[QUERY] IotHubDescriptionResource should be named IotHubResource

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-sdk-for-net#31348]
### Library name and version

Azure.ResourceManager.IotHub 1.0.0

### Query/Question

For me all classes and models in the Azure.ResourceManager.IotHub library have wrong namings.

Why are there always a `*Description` suffix?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@cmenzi  The Azure SDK method name and property name comes from their underlying Swagger definition, for IoTHub, they are defined here: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/iothub/resource-manager/Microsoft.Devices/stable/2021-07-02/iothub.json 
I can see we do have some member named with Description suffix, but if you look at the description, there is reason behind that, for example: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/iothub/resource-manager/Microsoft.Devices/stable/2021-07-02/iothub.json#L146 
IotHubResource_CreateOrUpdate method, it says for IoTHubDescription, it means The IoT hub metadata and security metadata. 
You can search in the swagger file to see other members named with description suffix for more details

**Comment by cmenzi** [comment]
True. Then the Api team of IoTHub just did it differently than any other team. It just felt different on this. 

I don't CreateOrUpdate a IoTHubDescription.

**Comment by xboxeer** [comment]
> True. Then the Api team of IoTHub just did it differently than any other team. It just felt different on this.
> 
> I don't CreateOrUpdate a IoTHubDescription. 😅
> 
> But I can live with it. Maybe it could also added to those rename mappings you have when generating the clients

That's true, we SDK team are also building this mapping between swagger and SDK naming but that will bring in breaking changes if the SDK libraries are released. 
We'd like to hear user voices regarding Azure SDK, if you have any feedback, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)

**Comment by live1206** [comment]
Issue has been clarified.
