### ISSUE TITLE
[FEATURE REQ] ApplicationInsightsResource

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-sdk-for-net#31350]
### Library name

Azure.ResourceManager.ApplicationInsights

### Please describe the feature.

Currently, It's not possible to create an ApplicationInsights component via the SDK.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
Thanks @cmenzi , AppInsights SDK is in our plan 
CC @ArthurMa1978 , can we have a beta version released for AppInsight?

**Comment by BastienPerdriau** [comment]
Hi,

Do you have any news on this particular SDK ?
It would be great to have a stable 1.0 with ApplicationInsightsResource management.

**Comment by fengzhou-msft** [comment]
The beta version is here: https://www.nuget.org/packages/Azure.ResourceManager.ApplicationInsights/1.0.0-beta.1

**Comment by cmenzi** [comment]
@fengzhou-msft  This is still the same package. It does not provide any capabilities to create an `ApplicationInsightsResource`

![image](https://user-images.githubusercontent.com/1763806/217184731-b131a207-ea84-4b03-b3cc-5cd8ded3b0a4.png)

**Comment by fengzhou-msft** [comment]
Got it. We need to use a more useful version tag to generate the SDK. Currently, it's using [package-2020-03-01-preview](https://github.com/Azure/azure-rest-api-specs/blob/b3a0c8c84015cc8a1f4bef06ce579ba2f32d4ece/specification/applicationinsights/resource-manager/readme.md#tag-package-2020-03-01-preview) with only one resource.

**Comment by cmenzi** [comment]
@fengzhou-msft Are going to change the version those api-specs in near future? Currently, I use `GenericResource` for reading and have to use the azure-cli for creating an updating.

**Comment by cmenzi** [comment]
@fengzhou-msft  @ArcturusZhang Any updates on this?

**Comment by cmenzi** [comment]
@fengzhou-msft @ArcturusZhang @xboxeer 

Hey just wanted to ping you again.

Is there a way to accelerate this? Or is there a way to escalate this via a Support Ticket?

Regarding to discussions above, it's just changing 
the version and regenerate.

**Comment by jsquire** [comment]
Unfortunately, beyond initial triage, I have no insight.   @ArthurMa1978:  Would you please share your thoughts?

**Comment by cmenzi** [comment]
Thanks @jsquire. I seems you are very responsive. I really hope now, that this not take another month until somebody reacts.

**Comment by ArthurMa1978** [comment]
@cmenzi we planned to release a new version in this month that will solve your problem

**Comment by RodgeFu** [comment]
@cmenzi , I am now working on the next release of ApplicationInsights and would like to confirm with you that the support you are looking for is to be able to Create/Read/Update an ApplicationInsight resource, right? thanks.

**Comment by RodgeFu** [comment]
@cmenzi, we have released a new version of applicationinsights. You may give it a try and let us know if there are further questions. And please be aware that there are some breaking changes in it and you can check the changelog for detail. Thanks.

https://github.com/Azure/azure-sdk-for-net/releases/tag/Azure.ResourceManager.ApplicationInsights_1.0.0-beta.3
https://www.nuget.org/packages/Azure.ResourceManager.ApplicationInsights/1.0.0-beta.3

**Comment by cmenzi** [comment]
@RodgeFu Yes, this is exactly I've looking for. Many thanks!

**Comment by BastienPerdriau** [comment]
A quick question : Do you have an ETA on releasing a stable version of the NuGet package, not only a preversion ?
