### ISSUE TITLE
[QUERY] What is the value of using ModelFactory classes over interfaces?

### ISSUE THREAD

**Issue by FBryant87** [Azure/azure-sdk-for-net#31353]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

Out of curiosity, could anyone please help us understand the value of this ModelFactory class giving us real implementation objects for testing purposes, as opposed to the objects themselves implementing interfaces? (which makes them easily mockable)

Take SubscriptionProperties for example, if this class simply implemented an interface we could mock it in a single line of code.

Instead we need to use a static ModelFactory class to new it up, and give it all the min/max values it needs even if they're not relevant to our test, for our test to then run the real implementation code for SubscriptionProperties.

https://github.com/Azure/azure-sdk-for-net/blob/62f2223e46c33825628443d11b8267de4e72a1c6/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusModelFactory.cs

**Comment by jsquire** [comment]
Hi @FBryant87.   Thank you for your feedback.   With respect to interfaces, the Azure SDKs have a goal of strict backwards compatibility with a very high bar for any breaking changes.  With that in mind, the use of an interface makes evolving over time difficult; any change to the public API surface represented in an interface becomes a breaking change for anyone who has implemented it - including when we want to add new members.  

Adding more interfaces to define new members (much like native COM interfaces do in Windows) is possible but becomes burdensome.  While default interface implementation makes this easier, it is not supported in all of the frameworks that we target.  As a result, we intentionally avoid using interfaces outside of special circumstances.

The Azure SDK guidelines pertaining to mocking can be found [here](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking).  For more discussion and details around the philosophy and approach to unit testing and mocking the Azure SDKs, I'd recommend [this](https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/) post from the Azure SDK blog.  

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by FBryant87** [comment]
Thank you for your response @jsquire
