### ISSUE TITLE
Typo on "BlobBaseClient.DownloadStreamingAsync Method" page

### ISSUE THREAD

**Issue by JonathanBordeleau** [Azure/azure-sdk-for-net#31352]
Typo in the Remarks section : **DownloadContentAsyncas** a prefered way of downloading small blobs that can fit into memory
Suggestion : **DownloadContentAsync as** a prefered way of downloading small blobs that can fit into memory

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1354b554-ae68-0675-bbb3-82a058c20b15
* Version Independent ID: 58b92e4c-0ad2-f9bf-fa97-fcde27cb291e
* Content: [BlobBaseClient.DownloadStreamingAsync Method (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.downloadstreamingasync?view=azure-dotnet-preview)
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@JonathanBordeleau We are looking into it and get back to you for any additional information.

**Comment by seanmcc-msft** [comment]
It appears this issue has been resolved - https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.downloadstreamingasync?view=azure-dotnet-preview
