### ISSUE TITLE
[FEATURE REQ] LogAnalyticsWorkspaceResource

### ISSUE THREAD

**Issue by cmenzi** [Azure/azure-sdk-for-net#31351]
### Library name

Azure.ResourceManager.LogAnalytics? (Not Existing, yet)

### Please describe the feature.

Currently, it's not supported to create a LogAnalyticsWorkspace.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
Please use `Azure.ResourceManager.OperationalInsights 1.0.0` and the Log Analytics Workspace resource is named `OperationalInsightsWorkspaceResource`.

**Comment by cmenzi** [comment]
Works 💪
