### ISSUE TITLE
[BUG] AddAzureMonitorLogExporter is not available with latest Azure.Monitor.OpenTelemetry.Exporter version 1.0.0-beta.3

### ISSUE THREAD

**Issue by hejingkan2005** [Azure/azure-sdk-for-net#31370]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.3

### Describe the bug

Get the same extension method AddAzureMonitorLogExporter() resolving issue as reported in #22077, I've imported the latest NuGet package Azure.Monitor.OpenTelemetry.Exporter version 1.0.0-beta.3, however it reports the same as it's internal class:
![image](https://user-images.githubusercontent.com/14071136/191881988-67b8c8f8-896b-4708-bcff-e89444e8328a.png)

### Expected behavior

Should resolve the method without error

### Actual behavior

Can not resolve the method

### Reproduction Steps

Sample code
```c#
builder.Logging.AddOpenTelemetry(loggerOptions =>
{
    loggerOptions.AddAzureMonitorLogExporter();
});
```
loggerOptions.AddAzureMonitorLogExporter() can not be resolved successfully.

### Environment

Windows 10 .net 6.0
Visual Studio 17.3.4

**Comment by hejingkan2005** [comment]
Link to #22077

**Comment by TimothyMothra** [comment]
Beta4 was just released. It generally takes nuget an hour to make a new package available.
https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.Exporter/1.0.0-beta.4
