### ISSUE TITLE
Fail to retrieve user info using AAD's graph client library if there is single quote in the user's email address

### ISSUE THREAD

**Issue by jasonjyy** [Azure/azure-sdk-for-net#3138]
We use AAD Graph client library to retrieve user info using get user operation. When there is single quote in the user's email address, it'll fail with below exception. The log shows 2 single quotes in the user's email address, maybe an encoding issue in the AAD Graph library?

Microsoft.Data.OData.ODataErrorExceptionResource jason''stest@SCCAlerts1.onmicrosoft.com' does not exist or one of its queried reference-property objects are not present.Microsoft.Data.OData.ODataErrorException: Resource 'jason''stest@SCCAlerts1.onmicrosoft.com' does not exist or one of its queried reference-property objects are not present. ---> System.Data.Services.Client.DataServiceQueryException: An error occurred while processing this request. ---> System.Data.Services.Client.DataServiceClientException: {"odata.error":{"code":"Request_ResourceNotFound","message":{"lang":"en","value":"Resource 'jason''stest@SCCAlerts1.onmicrosoft.com' does not exist or one of its queried reference-property objects are not present."}}} at System.Data.Services.Client.BaseAsyncResult.EndExecute[T](Object source, String method, IAsyncResult asyncResult) at System.Data.Services.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult) --- End of inner exception stack trace --- at System.Data.Services.Client.QueryResult.EndExecuteQuery[TElement](Object source, String method, IAsyncResult asyncResult) at System.Data.Services.Client.DataServiceRequest.EndExecute[TElement](Object source, DataServiceContext context, String method, IAsyncResult asyncResult) at System.Data.Services.Client.DataServiceQuery`1.EndExecute(IAsyncResult asyncResult) at Microsoft.Azure.ActiveDirectory.GraphClient.Extensions.DataServiceContextWrapper.<>c__DisplayClass25`2.<ExecuteSingleAsync

We are using Microsoft.Azure.ActiveDirectory.GraphClient.dll v2.0.7, we also tried 2.1.11 and no luck. and the graph explore works fine for this test user

**Comment by markcowl** [comment]
@jasonjyy Unfortunately, the AD Graph library does not reside here.  Please submit this request to one of the azure AD support forums, as specified here:  https://azure.microsoft.com/en-us/support/forums/
