### ISSUE TITLE
[Search] CreateAzureBlobIndexer failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#31384]
Search nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Concurrency conflict when attempting to start the indexer run. This may be because another indexer invocation is currently in progress; concurrent invocations are not allowed.
> Status: 409 (Conflict)
> 
> Content:
> {"error":{"code":"","message":"Concurrency conflict when attempting to start the indexer run. This may be because another indexer invocation is currently in progress; concurrent invocations are not allowed."}}
> 
> Headers:
> Pragma: no-cache
> client-request-id: 502eda79-b706-42b0-ad5d-4f2efbbc811f
> x-ms-client-request-id: 502eda79-b706-42b0-ad5d-4f2efbbc811f
> request-id: 502eda79-b706-42b0-ad5d-4f2efbbc811f
> elapsed-time: 71
> Preference-Applied: REDACTED
> Strict-Transport-Security: REDACTED
> Cache-Control: no-cache
> Date: Wed, 21 Sep 2022 15:21:35 GMT
> Content-Length: 209
> Content-Language: REDACTED
> Content-Type: application/json; charset=utf-8
> Expires: -1
> 
> 
> Stack trace
>    at Azure.Search.Documents.IndexersRestClient.Run(String indexerName, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\src\Generated\IndexersRestClient.cs:line 237
>    at Azure.Search.Documents.Indexes.SearchIndexerClient.RunIndexer(String indexerName, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\src\Indexes\SearchIndexerClient.cs:line 866
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<ValidateDiagnosticScope>d__6`1.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 178
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Azure.Search.Documents.Tests.SearchIndexerClientTests.<CreateAzureBlobIndexer>d__3.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\SearchIndexerClientTests.cs:line 100
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Search.Documents.Tests.SearchIndexerClientTests.<CreateAzureBlobIndexer>d__3.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\SearchIndexerClientTests.cs:line 111
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action a

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1864983&view=results

@jsquire for notification.

**Comment by ShivangiReja** [comment]
There was a concurrency conflict for this test failure. It is passing in the older/newer runs. Also, this test failed only one time in one os environment.

 I reran the test again and it passed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1864983&view=results

Please file an issue if you see a failure pattern or a same test fails in 2 or more continuous runs. Thanks!
