### ISSUE TITLE
[FormRecognizer] CreateComposedModelOperationCanPollFromNewObject failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#31383]
FormRecognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Invalid model created with ID 046c569a-8a2a-43d0-b934-8bad2d6e7127
> Status: 200 (OK)
> ErrorCode: 3014
> 
> Additional Information:
> error-0: 3014: Generic error during training.
> 
> Content:
> 
> Headers:
> ms-azure-ai-errorcode: REDACTED
> x-envoy-upstream-service-time: 30
> apim-request-id: eda4204c-3432-4ea2-a056-990b795bd631
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Fri, 23 Sep 2022 04:20:08 GMT
> Content-Length: 282
> Content-Type: application/json; charset=utf-8
> 
> Data:
> error-0: 3014: Generic error during training.
> 
> 
> Stack trace
>    at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 290
>    at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 273
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 87
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 79
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 202
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 242
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 177
>    at Azure.AI.FormRecognizer.Training.CreateCustomFormModelOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormTrainingClient/CreateCustomFormModelOperation.cs:line 73
>    at Azure.AI.FormRecognizer.Tests.DisposableTrainedModel.TrainModelAsync(FormTrainingClient trainingClient, Uri trainingFilesUri, Boolean useTrainingLabels, String modelName) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/Infrastructure/DisposableTrainedModel.cs:line 56
>    at Azure.AI.FormRecognizer.Tests.FormRecognizerLiveTestBase.CreateDisposableTrainedModelAsync(Boolean useTrainingLabels, ContainerType containerType, String modelName) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/Infrastructure/FormRecognizerLiveTestBase.cs:line 133
>    at Azure.AI.FormRecognizer.Tests.FormRecognizerOperationsLiveTests.CreateComposedModelOperationCanPollFromNewObject() in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerModels/FormRecognizerOperationsLiveTests.cs:line 136
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1870314&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Issue is part of https://github.com/Azure/azure-sdk-for-net/issues/31914.
