### ISSUE TITLE
[BUG] Microsoft.Azure.WebJobs.Extensions.ServiceBus >= 5.0.0 doesn't respect TransportType in ASB connectionstring.

### ISSUE THREAD

**Issue by JarkoDubbeldam** [Azure/azure-sdk-for-net#31389]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0

### Describe the bug

In Microsoft.Azure.WebJobs.Extensions.ServiceBus 4.3.0 it is possible to configure a ServiceBusTrigger to communicate with the servicebus using port 443 by specifying `TransportType=AmqpWebSockets` in the connectionstring.

From 5.0.0 onwards, this does not work anymore. 

For local development in networks where AMQP ports 5671/5672 are restricted, this makes local development impossible.

### Expected behavior

When setting `TransportType=AmqpWebSockets` in the ASB connection string I expect the function to communicate with the servicebus using a websocket on port 443.

### Actual behavior

Instead, the options revert back to `AmqpTcp` with seemingly no way to override this:

Output of the function when run with `--verbose`
```
[2022-09-23T08:21:37.330Z] ServiceBusOptions
[2022-09-23T08:21:37.334Z] {
[2022-09-23T08:21:37.345Z]   "ClientRetryOptions": {
[2022-09-23T08:21:37.352Z]     "Mode": "Exponential",
[2022-09-23T08:21:37.366Z]     "TryTimeout": "00:01:00",
[2022-09-23T08:21:37.372Z]     "Delay": "00:00:00.8000000",
[2022-09-23T08:21:37.389Z]     "MaxDelay": "00:01:00",
[2022-09-23T08:21:37.393Z]     "MaxRetries": 3
[2022-09-23T08:21:37.397Z]   },
[2022-09-23T08:21:37.403Z]   "TransportType": "AmqpTcp",
[2022-09-23T08:21:37.407Z]   "WebProxy": "",
[2022-09-23T08:21:37.417Z]   "AutoCompleteMessages": true,
[2022-09-23T08:21:37.420Z]   "PrefetchCount": 0,
[2022-09-23T08:21:37.424Z]   "MaxAutoLockRenewalDuration": "00:05:00",
[2022-09-23T08:21:37.430Z]   "MaxConcurrentCalls": 128,
[2022-09-23T08:21:37.433Z]   "MaxConcurrentSessions": 8,
[2022-09-23T08:21:37.437Z]   "MaxMessageBatchSize": 1000,
[2022-09-23T08:21:37.454Z]   "SessionIdleTimeout": ""
[2022-09-23T08:21:37.457Z] }
```

### Reproduction Steps

https://github.com/JarkoDubbeldam/NServiceBus.Functions.WebSockets.Repro/tree/master/FunctionsSDK

With `local.settings.json` as follows:

```
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
    "AzureWebJobsServiceBus": "Endpoint=sb://<REDACTED>.servicebus.windows.net/;SharedAccessKeyName=<REDACTED>;SharedAccessKey=<REDACTED>;TransportType=AmqpWebSockets"
  }
}
```

The project linked uses 4.3.0 of the package. [This](https://github.com/JarkoDubbeldam/NServiceBus.Functions.WebSockets.Repro/tree/5.0.0/FunctionsSDK) branch uses 5.0.0 of the package.

### Environment

```
.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  2.1.505 [C:\Program Files\dotnet\sdk]
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

Visual Studio Enterprise 2022 17.2.6

**Comment by jsquire** [comment]
Hi @JarkoDubbeldam.  Thank you for reaching out and we regret that you're experiencing difficulties.   The behavior that you're describing is by design; `TransportType` is not a valid token for the connection string and is ignored.  

Connection strings are supported only in the form published by the Azure portal. These are intended to provide basic location and shared key information only. Configuring behavior is done through its options in `host.json`.  Previous generations of the Service Bus clients allowed for some behavior to be configured by adding key/value components to a connection string. These components are no longer recognized and have no effect on client behavior.

To use the web socket transport in your Function, the easiest way is to specify it in your `host.json`:
```json
{
  "extensions": {
    "serviceBus": {
      "transportType" : "amqpWebSockets"          
  }
}
```

The full set of configuration available can be found in [Azure Service Bus bindings for Azure Functions](https://learn.microsoft.com/azure/azure-functions/functions-bindings-service-bus?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#hostjson-settings).

**Comment by JarkoDubbeldam** [comment]
@jsquire, thank you very much. That does indeed solve my problems.
