### ISSUE TITLE
Remove compiler constants from Batch.csproj

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-net#3139]
We have `PORTABLE` defined right now in `Batch.csproj` -- once AutoRest fixes [this](https://github.com/Azure/autorest/issues/2218) we can remove the IFDEF stuff.

**Comment by shahabhijeet** [comment]
@matthchr what is the current status of this. Can we do this in Aug?

**Comment by matthchr** [comment]
Sorry I missed this, was on vacation.

I will have to take a look, but I think that yes, we can probably remove this. I am not sure it will happen by the end of Aug though, maybe first week of Sept?

I'll take a look and if updating AutoRest version is really easy and just fixes it maybe I can sneak it in here before the end of the month...

**Comment by matthchr** [comment]
I worked on this but got blocked by this: https://github.com/Azure/autorest/issues/2558

**Comment by matthchr** [comment]
This is fixed now
