### ISSUE TITLE
[FormRecognizer][FEATURE REQ]Link DocumentKeyValuePair to AnalyzedDocument in AnalyzeResult

### ISSUE THREAD

**Issue by vldmr-bus** [Azure/azure-sdk-for-net#31394]
### Library name

Azure.AI.FormRecognizer

### Please describe the feature.

In the current API the values in KeyValuePairs of AnalyzeResult do not provide any means to find out which of the AnalyzedDocument  in the field Documents would contain the value in case of multiple documents. Please provide either PageNumber or DocumentNumber field in the DocumentKeyValuePair object that would allow to associate the object with the document.

The use case for this is when a prebuilt model fails to map a scanned document field due to unsupported wording of the label, then KeyValuePairs can be scanned to custom mapping for that field in post-processing of the recognized results.

**Comment by pallavit** [comment]
/cc: @kinelski could you share the feedback with the service team and see if there is anything we can do in the SDK independently ?
