### ISSUE TITLE
Support projects targetting something other than net452 + netstandard1.4

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-net#3140]
For SDK projects it's fine to only build those 2, but for supporting projects that we have (listed below) we sometimes have to target other frameworks.

**Here is this list of projects which I would like built but not packaged (tests need not be run either) – note paths are all in my latest PR not in vs17Dev yet:**
src\SDKs\Batch\DataPlane\Azure.Batch.IntegrationTests -- targets net452 only because it uses some Certificate stuff that isn't supported in netstandard
src\SDKs\Batch\DataPlane\Azure.Batch.ProtocolTests -- Could maybe port this to target netstandardapp1.1
src\SDKs\Batch\DataPlane\TestCommon\IntegrationTestCommon -- targets net452 only because it uses some Certificate stuff that isn't supported in netstandard
src\SDKs\Batch\DataPlane\Tools\ObjectModelCodeGeneration\* -- targets net46 because it uses some Roslyn stuff which only works against net46
src\SDKs\Batch\DataPlane\Tools\ConfigureAwaitAnalyzer – This one you can omit from the build entirely actually, it should only get built if another project references it.

**Comment by shahabhijeet** [comment]
Fixing title

**Comment by matthchr** [comment]
@shahabhijeet I'm just wondering, do you have an idea/plan for dealing with this case?

**Comment by matthchr** [comment]
@shahabhijeet - Do you have an ETA on when you will support this?

When this work is done, we should make sure to enable the scenario we have with the ConfigureAwaitChecker, where we have a netstandard1.4 Roslyn analyzer which is consumed by our Azure.Batch project (as a development dependency). The analyzer doesn't have a net452 target at all.

**Comment by shahabhijeet** [comment]
@matthchr This is under testing and should be done today.

**Comment by shahabhijeet** [comment]
Done
https://github.com/Azure/azure-sdk-for-net/pull/3209
