### ISSUE TITLE
[BUG] Tracing: support non-string types and fix http.status_code

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#31438]
### Library name and version

Azure.Core

### Describe the bug

http.status_code has to be `int` according to hotel and  [Azure SDK](https://github.com/Azure/azure-sdk/blob/main/docs/tracing/distributed-tracing-conventions.yml#L46) conventions.

Changing it for DiagnosticSource path would be breaking, but for OTel path, we should be able to change it.

To  do it we'd need to change 
https://github.com/Azure/azure-sdk-for-net/blob/f4b6edc0de76a5fda06644c2ac495941d5b070a0/sdk/core/Azure.Core/src/Pipeline/Internal/RequestActivityPolicy.cs#L83

to pass status as is and  support adding (at least) long attributes in DiagnosticScope

https://github.com/Azure/azure-sdk-for-net/blob/f4b6edc0de76a5fda06644c2ac495941d5b070a0/sdk/core/Azure.Core/src/Shared/DiagnosticScope.cs#L88-L95

`Activity.AddTag(String, Object)` was [added in .NET 5](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.addtag?view=net-6.0#system-diagnostics-activity-addtag(system-string-system-object)) so we need to do our regular reflection hack.

### Expected behavior

`http.status_code` has long or int type

### Actual behavior

`http.status_code` is a string which breaks azure SDK integration with otel-compatible backends

### Reproduction Steps

1. create HttpPipeline, send request to any endpoint
2. enable Opentelemetry
3. export traces to AzMon, Jaeger or console

**Comment by JoshLove-msft** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/33960
