### ISSUE TITLE
[BUG] Problem after upgrading Azure.ResourceManager.Monitor from 1.0.0 (Beta 3) to 1.0.0

### ISSUE THREAD

**Issue by gui28347** [Azure/azure-sdk-for-net#31458]
### Library name and version

Azure.ResourceManager.Monitor 1.0.0

### Describe the bug

I have one project working with no issues using Azure.ResourceManager.Monitor 1.0.0-beta3 after upgrading it today to 1.0.0 it introduce one problem 

<img width="823" alt="image" src="https://user-images.githubusercontent.com/8279438/192438158-1046de8c-142b-4ef7-8a27-e713795470a5.png">

st.GetBlobService().**GetDiagnosticSettings().**CreateOrUpdate(WaitUntil.Completed, "DIAG", new DiagnosticSettingData()
st.GetFileService().**GetDiagnosticSettings()**.CreateOrUpdate(WaitUntil.Completed, "DIAG", new DiagnosticSettingData()

### Expected behavior

Work as usual or at least if some breaking changes introduce document it in CHANGELOG.

ChangeLog -> https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.Monitor_1.0.0/sdk/monitor/Azure.ResourceManager.Monitor/CHANGELOG.md

### Actual behavior

Failing to find GetDiagnosticSetting

### Reproduction Steps

Use GetDiagnosticSetting using package Azure.ResourceManager.Monitor 1.0.0-beta3 and update it to Azure.ResourceManager.Monitor 1.0.0

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  2.1.526 [C:\Program Files\dotnet\sdk]
  2.1.818 [C:\Program Files\dotnet\sdk]
  3.1.423 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@gui28347 , sorry this is something we missed in our change log. In the stable version we decide to move those cross-service RP operations from RP level to `ArmClient` level, the reason is that we can not 100% sure if all the RP support this kind of capability. 
You can use the code below to achieve the same 
```csharp
armClient.GetDiagnosticSettings(RP.Id).CreateOrUpdate(param....)
```
We'll update our change log to include this breaking change.
CC @ArthurMa1978
