### ISSUE TITLE
Investigate using Newtonsoft.Json 10 with generated code and republish packages

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#3145]
### Description
- [ ] Update minimum version in clientruntime to NewtonSOft.Json 10 (private package)
- [ ] Update ClientRuntime depenedncy (and newtonsoft.json dependency)in AutoRest acceptance tests and verify no issues with Newtonsoft.Json 10
- [ ] Update ClientRuntime tests to use newtonsoft.Json 10 and verify no issues
- [ ] Update management packages and tests to Newtonsoft.Json 10 and verify no issues
- [ ] Send notice to customers about republishing packages with Newtonsoft.Json 10
- [ ] Move packages into PowerShell and verify no issues
- [ ] Publish runtime packages with updated Newtonsoft.Json minimum dependency
- [ ] Update management package withupdated Newtonsoft.Json 10 depednency (add explicit depednecy to package)
- [ ] Publish management packages

### Cost: 10

**Comment by shahabhijeet** [comment]
This workItem has been put off for future.
Closing it for now.
