### ISSUE TITLE
[BUG] Apostrophe not escaped in TableClient.DeleteEntity rowKey parameter

### ISSUE THREAD

**Issue by romisak** [Azure/azure-sdk-for-net#31464]
### Library name and version

Azure.Data.Tables 12.6.1

### Describe the bug

When trying to delete a record that has an apostrophe in the row key the operation fails. A similar problem is for the partition key.

### Expected behavior

Delete the record.

### Actual behavior

Azure.RequestFailedException: 'There is an unterminated string literal at position 37 in 'PartitionKey='one',RowKey='two'three''.
RequestId:af62187c-4002-0000-7874-d2cf2b000000
Time:2022-09-27T13:27:43.3829315Z
Status: 400 (Bad Request)
ErrorCode: InvalidInput

Content:
{"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"There is an unterminated string literal at position 37 in 'PartitionKey='one',RowKey='two'three''.\nRequestId:af62187c-4002-0000-7874-d2cf2b000000\nTime:2022-09-27T13:27:43.3829315Z"}}}

Headers:
Transfer-Encoding: chunked
Server: Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: af62187c-4002-0000-7874-d2cf2b000000
x-ms-client-request-id: 7a863db4-4d84-4769-914f-87b82f912f6d
x-ms-version: REDACTED
X-Content-Type-Options: REDACTED
Date: Tue, 27 Sep 2022 13:27:42 GMT
Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8
'

### Reproduction Steps

```csharp
using Azure;
using Azure.Data.Tables;
using System.Globalization;

namespace DeleteEntitySpike
{
    internal class Program
    {
        static void Main(string[] args)
        {
            const string connectionString = "";
            const string tableName = "TestTable";
            const string partionKey = "one";
            const string rowKey = "two'three";
            TableClient tableClient = new TableClient(connectionString, tableName);
            tableClient.CreateIfNotExists();
            tableClient.AddEntity(new Model { PartitionKey = partionKey, RowKey = rowKey });
            tableClient.DeleteEntity(partionKey, rowKey);
        }

        class Model : ITableEntity
        {
            public string PartitionKey { get; set; }
            public string RowKey { get; set; }
            public DateTimeOffset? Timestamp { get; set; }
            public ETag ETag { get; set; }
        }
    }
}
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @romisak - The best way to handle filter query escaping for string-based filters is to utilize the helper methods in the client, such as `TableClient.CreateQueryFilter`. See [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample4QueryEntities.md#odata-formatted-string) for more information.

**Comment by romisak** [comment]
Hi @christothes

I can add the escaping, that's easy.

However, when I call GetEntity I don't need to escape the partition key or row key.
Model model = tableClient.GetEntity<Model>(partitionKey, rowKey); // this works OK

Therefore I would expect that I shouldn't escape it for the DeleteEntity too.
tableClient.DeleteEntity(partitionKey, rowKey); // this throws exception

Should I do the escaping for DeleteEntity in my code, or are you planning to change this in future versions of the library?

Regards, Roman

**Comment by christothes** [comment]
Thanks for clarifying - I misunderstood initially. Yes, we should handle this case for `DeleteEntity` as well.
