### ISSUE TITLE
Enable proactive renewal of Managed Identity tokens

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-net#31469]
**Intro:**
Refreshing the tokens with half lifetime would improve resiliency for clients if there's an ESTS outage while fetching a token. 

**Acceptance Criteria:**
All MSI tokens are refreshed at least half lifetime token request is made after half lifetime

MSI has token lifetime of 24 hours. Refresh the tokens if `refresh_in` is passed from ESTS or at half lifetime if `refresh_in` isn't passed. For tokens which have lifetime of less than 2 hours, there are no changes to be made.

**Comment by christothes** [comment]
MSAL will handle this - marking as done
