### ISSUE TITLE
[BUG] blob.CreateIfNotExistsAsync(); creates a blob but throws an exception hence doesnt append anything to it as intented

### ISSUE THREAD

**Issue by jay-aplan** [Azure/azure-sdk-for-net#31496]
### Library name and version

Azure.Storage.Blobs 12.13.1

### Describe the bug

1. Following code doesnt work for the first time i.e when the blob doesnt exist. this code only creates an empty blob without appending the content. From next time onwards it appends the content as expected.

BlobContainerClient containerClient = new BlobContainerClient(_connectionString, container);
            await containerClient.CreateIfNotExistsAsync();

                // take Blob's reference to modify
                var blob = containerClient.GetAppendBlobClient(fileName);

                // if blob doesn't exist, the system will create it
                if (!blob.Exists())
                {
                    **// this works but no code after this line executed.**
                    await blob.CreateIfNotExistsAsync();
                    blob = containerClient.GetAppendBlobClient(fileName);
                    blob.SetTags(AddTags(new Dictionary<string, string> { { "Id", quoteRequestReference } }));
                }

                var data = "somedata";
                var bytes = Encoding.UTF8.GetBytes(data);
                var stream = new MemoryStream(bytes);
                blob.SetTags(AddTags(new Dictionary<string, string> { { "Id", "someid"} }));

               **// this doesn't execute or work for the first time.**
                **await blob.AppendBlockAsync(stream);**

### Expected behavior

The await blob.CreateIfNotExistsAsync();  and await blob.AppendBlockAsync(stream); should both work when function gets called and blob doesnt exists

### Actual behavior

The await blob.CreateIfNotExistsAsync(); -- creates an empty blob

await blob.AppendBlockAsync(stream); this doesnt get executed first time when blob gets created by a statement above

### Reproduction Steps

1. Run the function with container present but blob not present
2. When called first time, the blob gets created with no contents in it
3. When called second time, the contents gets appended to the blob properly

**Comment by SaurabhSharma-MSFT** [comment]
@jay-aplan I have tried your code block, but I do not see any issues with it in the first run.  The data "some-data" is getting appended to the blob in the first run itself.

**Comment by jay-aplan** [comment]
I found a workaround for this. I think the async method has some issue with it "CreateIfNotExistsAsync". I replaced that with "Create" and it worked fine for me.
