### ISSUE TITLE
What is the process to log out when using token caching

### ISSUE THREAD

**Issue by calebkiage** [Azure/azure-sdk-for-net#31498]
### Library name and version

Azure.Identity 1.7.0

### Query/Question

When authenticating with the credential classes and token caching, how does one log out so that the cached tokens cannot be accessed?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
We don't currently expose any APIs to do this. We'll use this issue to gauge interest.

**Comment by baywet** [comment]
Having the ability to sign out properly sounds like a basic security requirement for any native application. How does the azure CLI handle this today then? Do they orchestrate MSAL directly?
This would allow us to complete authentication scenarios for the Microsoft Graph CLI. Could this get prioritized please?

**Comment by christothes** [comment]
Closing this issue and will track this feature request in the linked issue. Please add any feedback for support of us prioritizing this feature there.

**Comment by vladimir-sironja** [comment]
looks like msalInstance utilization can help to logout "from behind":
see https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/logout.md
