### ISSUE TITLE
[BUG] Invalid URI Error when retrieving backups for WebSiteResource

### ISSUE THREAD

**Issue by d-tayl** [Azure/azure-sdk-for-net#31504]
### Library name and version

Azure.ResourceManager.AppService 1.0.0-beta.4

### Describe the bug

When calling webSiteResource.GetSiteBackups() or webSiteResource.GetSiteBackup(backupId) (or the async version) I get an Invalid URI Error. I'm guessing it's the storageAccountUrl as it seems to be the only URI in the BackupItemData class.  I've tested it both during the backup process and on a completed process and I get the same result.

The storage details are configured when viewed through the Azure portal. I'm assuming the backupId as an int is correct, though the parameter expects a string and I get a Not Found response when using the resource ID.

Returning the configuration for backups works and the storage URI is populated there, though when setting up the schedule through the SDK, the SAS URL property is called [IsEnabled](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.appservice.models.backuprequest.isenabled?view=azure-dotnet-preview#azure-resourcemanager-appservice-models-backuprequest-isenabled
) (someone renamed the wrong field I guess). I'm not sure if that's related at all.

### Expected behavior

The call to return a list or single instance of a backup for a given WebSiteResource.

### Actual behavior

`Invalid URI: The URI is empty. - stack trace: at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions) at System.Uri..ctor(String uriString) at Azure.ResourceManager.AppService.BackupItemData.DeserializeBackupItemData(JsonElement element) at Azure.ResourceManager.AppService.WebAppsRestOperations.GetBackupStatus(String subscriptionId, String resourceGroupName, String name, String backupId, CancellationToken cancellationToken) at Azure.ResourceManager.AppService.SiteBackupCollection.Get(String backupId, CancellationToken cancellationToken) at Azure.ResourceManager.AppService.WebSiteResource.GetSiteBackup(String backupId, CancellationToken cancellationToken) 
`

### Reproduction Steps

```
var resourceGroupIdentifier = ResourceGroupResource.CreateResourceIdentifier(subId, resourceGroup);
ResourceGroupResource resourceGroup = armClient.GetResourceGroupResource(resourceGroupIdentifier);
WebSiteCollection webSiteCollection = resourceGroup.GetWebSites();
WebSiteResource webSiteResource = await webSiteCollection.GetAsync(appName);
var backup = (await webSiteResource.GetSiteBackupAsync(backupId.ToString())).Value;

```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by live1206** [comment]
It will be fixed in next release version.
