### ISSUE TITLE
Description property always null when using IConnectionOperations.ListAsync to retrieve connection details.

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#3150]
The value of the Description property in the response from the IConnectionOperations.ListAsync in method in IAutomationManagementClient is always null, even for connection assets known to have a non-empty description.

**Comment by ikanni** [comment]
Thank for reporting this. I am sorry you are hitting this issue. 

Today the list operation returns the minimal properties. As a workaround to get the description, please do another IConnectionOperations.GetAsync  call to retrieve the description. 

I am sorry, we won't be fixing this issue. I am closing this request.

**Comment by adrianhall** [comment]
Per @ikanni, this is something that won't be fixed.  This is normal in cloud operations - the list operation returns minimal information and you need to perform a get to get the full record.
