### ISSUE TITLE
Using ODataQuery with ITagOperations.ListByServiceAsync returns no results

### ISSUE THREAD

**Issue by MarkMiddlemist** [Azure/azure-sdk-for-net#31500]
I'm trying to check whether a tag already exists with a specific display name, using the ODataQuery query parameter 

```
ODataQuery<TagContract> NameCheckQuery = new ODataQuery<TagContract>(x => x.DisplayName == tagDisplayName);
IPage<TagContract> TagResponse = await this.ManagementClient.Tag.ListByServiceAsync(this.ResourceGroup, this.ServiceName, NameCheckQuery);

```
The call returns an empty collection despite the fact I have verified that that the combination of Resource Group, Service Name, and Display Name should return 1 result.

This is using v7.0.0-preview of Microsoft.Azure.Management.ApiManagement talking to a standard scale API Management instance

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
@MarkMiddlemist the track 1 SDK `Microsoft.Azure.Management.ApiManagement` is deprecated, please use its track 2 package https://www.nuget.org/packages/Azure.ResourceManager.ApiManagement/1.0.0
