### ISSUE TITLE
[BUG] Querying table storage produces ArgumentNullException if Int32 value is deserialized to Int64 model property

### ISSUE THREAD

**Issue by gplwhite** [Azure/azure-sdk-for-net#31517]
### Library name and version

Azure.Data.Tables v12.6.1

### Describe the bug

We have some existing data in a table that was originally stored as a Int32 value. 

Over time, the values stored in the table have grown and we've had to migrate the data model to support Int64 values. 

Now, when querying for an instance of the table entity, using the data model class with the property defined as Int64, a ArgumentNullException is raised when querying entities that contain an Int32 version of the property.

The root cause seems to be that the TablesTypeBinder assumes that the source value for an Int64 property will always be serialized as a string, and hence it only supports deserializing a string value. 

https://github.com/Azure/azure-sdk-for-net/blob/52e8e285a91573844beddc0c5e5a3f3c36b817a3/sdk/tables/Azure.Data.Tables/src/Extensions/TablesTypeBinder.cs#L88

Would there be any harm in adding support for deserializing int32 source values too. 

### Expected behavior

Int32 values should be able to be deserialized to a Int64 property without error.

### Actual behavior

Exception:

System.ArgumentNullException: Value cannot be null.
Parameter name: String
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
at Azure.Data.Tables.TablesTypeBinder.TryGet[T](BoundMemberInfo memberInfo, IDictionary`2 source, T& value)

### Reproduction Steps

```

public class LongEntity : ITableEntity
{
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; }
       
        public long Value { get; set; }
}

public class IntEntity : ITableEntity
{
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public DateTimeOffset? Timestamp { get; set; }
        public ETag ETag { get; set; }
       
        public int Value { get; set; }
}


public void DeserializeInt64()
{
            var connectionString = "UseDevelopmentStorage=true";
            var table = new TableServiceClient(connectionString).GetTableClient("LongTest");
            table.CreateIfNotExists();

            var intEntity = new IntEntity
            {
                PartitionKey = "",
                RowKey = "Test",
                Value = 123
            };

            table.UpsertEntity(intEntity, TableUpdateMode.Replace);
            var longEntity = table.Query<LongEntity>().First();

            Debug.Assert(longEntity.Value == 123);
}


```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @gplwhite Although we could handle this specific case, the problem would actually be possible for any of incompatible type swap.

Would it be possible to temporarily utilize the `TableEntity` type until you've migrated your values to the new data type? 

for example:

```c#
public void DeserializeInt64()
{
    var connectionString = "UseDevelopmentStorage=true";
    var table = new TableServiceClient(connectionString).GetTableClient("LongTest");
    table.CreateIfNotExists();

    var intEntity = new IntEntity
    {
        PartitionKey = "",
        RowKey = "Test",
        Value = 123
    };

    table.UpsertEntity(intEntity, TableUpdateMode.Replace);
    var tableEntity = table.Query<TableEntity>().First();
    var longEntity = new()
    {
        PartitionKey = tableEntity.PartitionKey,
        RowKey = tableEntity.RowKey,
        TimeStamp = tableEntity.TimeStamp,
        ETag = tableEntity.ETag,
        Value = tableEntity.GetInt64("Value")
    };

    Debug.Assert(longEntity.Value == 123);
}
```

**Comment by gplwhite** [comment]
Hi @christothes.

I wasn't actually planning to migrate the existing stored data - the values don't actually need to change. The only reason to migrate the stored datatypes is because the client library doesn't currently handle the conversion.

While I agree that a similar problem would occur with any incompatible datatype conversion and I'm not advocating for automatic conversions in general, I'm still of the opinion that this specific case should be handled by the client library - an Int32 value is not conceptually incompatible with Int64 and I think most people would expect an implicit conversion to occur.

If you're not comfortable with building this implicit conversion directly into the client library, would you consider some form of extensibility point that would allow custom conversions to be introduced from the outside? This could be a better option anyway as it could satisfy some general data-migration scenarios.

One final grumble about the current implementation is the misleading error messaging when the datatypes are incompatible - receiving an ArgumentNullException lead me to believe there was missing data - not that the data wasn't directly compatible.

**Comment by christothes** [comment]
> Hi @christothes.
> 
> I wasn't actually planning to migrate the existing stored data - the values don't actually need to change. The only reason to migrate the stored datatypes is because the client library doesn't currently handle the conversion.

I thought the reason you need to change the type in general was because they may overflow the int value. 

> While I agree that a similar problem would occur with any incompatible datatype conversion and I'm not advocating for automatic conversions in general, I'm still of the opinion that this specific case should be handled by the client library - an Int32 value is not conceptually incompatible with Int64 and I think most people would expect an implicit conversion to occur.

My main concern with the implicit conversion is the roundtrip scenario. Because Int64 is both serialized and stored differently on the service, it has side effects that may not be intended.

> If you're not comfortable with building this implicit conversion directly into the client library, would you consider some form of extensibility point that would allow custom conversions to be introduced from the outside? This could be a better option anyway as it could satisfy some general data-migration scenarios.

We don't currently support full participation in the serialization process, but there are a handful of workarounds. 

> One final grumble about the current implementation is the misleading error messaging when the datatypes are incompatible - receiving an ArgumentNullException lead me to believe there was missing data - not that the data wasn't directly compatible.

That's good feedback and I think we should improve the error here.

**Comment by gplwhite** [comment]
> I thought the reason you need to change the type in general was because they may overflow the int value.

Yes and no. We're saving new data as Int64, however all of the older/legacy data that is already stored is remaining as Int32 and theoretically doesn't need to be migrated as the Int32 values are not changing.

> My main concern with the implicit conversion is the roundtrip scenario. Because Int64 is both serialized and stored differently on the service, it has side effects that may not be intended.

Yep good point. Although I'm not sure roundtripping back to a Int32 would be required - if someone is using a data model with an Int64 property I think its a reasonable expectation that the value would be serialized back to the service as Int64. 

> We don't currently support full participation in the serialization process, but there are a handful of workarounds.

Other than the example you gave above, is there any documentation/examples you can point me to for workarounds on customizing the serialization/deserialization process?

Thanks for your time on this...

**Comment by christothes** [comment]
> Other than the example you gave above, is there any documentation/examples you can point me to for workarounds on customizing the serialization/deserialization process?

I think the best workaround for this specific scenario would be the one I mentioned above using TableEntity to deserialize in a type agnostic way.
