### ISSUE TITLE
Frequently receiving exceptions when using ListAsync methods in IAutomationManagementClient.

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#3151]
We use a number of ListAsync and ListNextAsync methods to retrieve automation asset information from Azure (i.e. runbooks, connections, variables, etc.) on a regular 30 second interval. Recently we have started to observe intermittent exceptions when calling ListAsync. We have observed a couple of different exceptions, including "A task was cancelled" and "Unable to connect to remove server/No connection could be made because the target machine actively refused it".

**Comment by shahabhijeet** [comment]
@davecader I understand this is intermittent right now, but would like to get some repro and as well as traces.
Adding folks from Automation who can help.

**Comment by adrianhall** [comment]
Services commonly protect themselves from abuse by requiring back off or throttling.  I suspect this is what you are experiencing.  A peek at the response to see what the HTTP status code and message is should confirm this.

However, this is an old issue.  If this is still an issue, please re-open with the following information:

* .NET Library and version being used.
* The HTTP response (status code, message, and headers) that are returned.

Thanks,
