### ISSUE TITLE
Clarification of AppServicePlan.MaximumElasticWorkerCount property

### ISSUE THREAD

**Issue by vhhughes** [Azure/azure-sdk-for-net#31528]
This needs at least some minimal clarification of how this property relates to the AppServicePlan.MaximumElasticWorkerCount Property. I cannot find any documentation that clarifies it, and looking at properties on my Elastic App Service Plan to try to infer its use or meaning hasn't gotten anywhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: af1d6c28-0206-83cb-5200-efe7c5625831
* Version Independent ID: 918ddb5b-27e8-19e6-5c78-698b5347266f
* Content: [AppServicePlan.MaximumNumberOfWorkers Property (Microsoft.Azure.Management.WebSites.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.appserviceplan.maximumnumberofworkers?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.WebSites.Models/AppServicePlan.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/AppServicePlan.xml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
Route to service team to clarify about the relations between `AppServicePlan.MaximumNumberOfWorkers` and `AppServicePlan.MaximumElasticWorkerCount`.
