### ISSUE TITLE
[BUG] Deserialization problem on Azure.ResourceManager.Redis.RedisResource.GetAsync()

### ISSUE THREAD

**Issue by aj9411** [Azure/azure-sdk-for-net#31536]
### Library name and version

Azure.ResourceManager.Redis 1.0.0

### Describe the bug

Hey guys,

this code of mine:

```
ArmClient armClient = new ArmClient(new ManagedIdentityCredential(clientId: {clientId of the app associated to my AKS cluster}));
RedisResource redisResource = armClient.GetRedisResource(this.redisResourceIdentifier); // well-built resource id, verified in logs, I can query metrics from azure monitor with this same resource id, so I don't think a misstructured resource id is the problem
redisResource = await redisResource.GetAsync(cancellationToken);
```

is throwing the following exception:

`System.InvalidOperationException: The requested operation requires an element of type 'Boolean', but the target element has type 'String'.\n   at System.Text.Json.JsonElement.GetBoolean()\n   at Azure.ResourceManager.Redis.Models.RedisCommonConfiguration.DeserializeRedisCommonConfiguration(JsonElement element)\n   at Azure.ResourceManager.Redis.RedisData.DeserializeRedisData(JsonElement element)\n   at Azure.ResourceManager.Redis.RedisRestOperations.GetAsync(String subscriptionId, String resourceGroupName, String name, CancellationToken cancellationToken)\n   at Azure.ResourceManager.Redis.RedisResource.GetAsync(CancellationToken cancellationToken)\n`

I it was working well until around 9/20, I could get the redis resource, I am interested specifically in the SKU. Then, without a change on my part, I started seeing the exception above _in the cloud_, sadly I can't repro locally. The code that is failing is all part of the SDK, so I can't do much debugging via print statements or what not. Looks like some property that the SDK expects to be a boolean was passed as a string by the server.

### Expected behavior

Not seeing the deserialization exception.

### Actual behavior

Nothing to add to what I shared in the description.

### Reproduction Steps

Shared code in the description.

### Environment

in the cloud, it's a .NET 6 app running on Linux/AKS

locally, I'm on Windows 11, Visual Studio version 17.3.5

**Comment by aj9411** [comment]
Ok, I think I might have figured it out. Actually, there was a change on our ARM template for our Redis deployments, which doesn't apply for the Redis cache that we deploy to debug our app locally. Anyways, this was the piece added:
```

"redisConfiguration": {
          "notify-keyspace-events": "EA",
          **"rdb-backup-enabled": "[if(parameters('redis_az_enabled'), true(), json('null'))]",**
          "rdb-backup-frequency": "[if(parameters('redis_az_enabled'), 15, json('null'))]",
          "rdb-backup-max-snapshot-count": "[if(parameters('redis_az_enabled'), 1, json('null'))]",
          "rdb-storage-connection-string": "[if(parameters('redis_az_enabled'), concat('DefaultEndpointsProtocol=https;AccountName=', variables('primaryStorageAccountName'), ';AccountKey=', listKeys(resourceId(resourceGroup().name,'Microsoft.Storage/storageAccounts', variables('primaryStorageAccountName')), variables('apiVersions').storage).keys[0].value,';EndpointSuffix=', environment().suffixes.storage), json('null'))]"
        }
```

Looking https://github.com/Azure/azure-sdk-for-net/blob/49d50b33ccb348eb665cb3e27428ad095e09b449/sdk/redis/Azure.ResourceManager.Redis/src/Generated/Models/RedisCommonConfiguration.Serialization.cs#L92

the only two properties that might throw the exception `System.InvalidOperationException: The requested operation requires an element of type 'Boolean', but the target element has type 'String'.\n   at System.Text.Json.JsonElement.GetBoolean()\n` are rdb-backup-enabled or aof-backup-enabled. Looks like json('null') is being treated as a string, I'll try with false().

Also, from the deserialization function on the link above, we see rdb-backup-enabled or aof-backup-enabled are meant to be booleans, which makes sense. So, why is the documentation here saying these are strings? https://learn.microsoft.com/en-us/azure/templates/microsoft.cache/redis?pivots=deployment-language-arm-template#rediscommonpropertiesredisconfiguration-1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by aj9411** [comment]
Submitted https://github.com/Azure/azure-sdk-for-net/pull/31571 after a short sync with @ArthurMa1978, I hope this fixes it. I modeled my pull request after https://github.com/Azure/azure-sdk-for-net/pull/31425

**Comment by aj9411** [comment]
PR was merged, I am using the new package version and I see my application is working well again.
