### ISSUE TITLE
Documenting Admin features for Jenkins Adminstration

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3153]
- Document what are some of the hooks, settings that are configured that will allow a stuck Jenkins job to be kicked off.
- In general document Jenkins configuration guide.

From: Mark Cowlishaw 
Sent: Tuesday, May 2, 2017 11:47 AM
Subject: FW: Update Microsoft.Azure.KeyVault.WebKey dependency on JSON.NET to unblock ASP.NET Core 2.0 preview1

It looks like there was a separate configuration for the BUILD triggers for this job, so that it wasn’t kicking off with your comments.  I added you, so you should be able to kick things off with github comments now.  I had previously added you to the global list, but that apparently did not percolate to this project.

If you notice that the ‘test this please’ comments are not working for any project in the future, lmk and I will show you how to add yourself.

**Comment by shawns1** [comment]
Ack.  I am going to put this documentation in our team OneNote.

**Comment by shawns1** [comment]
Docs around debugging are complete.  Now working on finishing up docs on setting up workers.

**Comment by shawns1** [comment]
This should be all documented in the team OneNote.  If there is anything missing, we can add it there.
