### ISSUE TITLE
[Translation] DocumentTranslationWithGlossary failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#31547]
Translation nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : The specified container already exists.
> RequestId:dd29ea2b-301e-0028-7c48-d32669000000
> Time:2022-09-28T14:43:46.6620455Z
> Status: 409 (The specified container already exists.)
> ErrorCode: ContainerAlreadyExists
> 
> Content:
> 
> 
> <Error>ContainerAlreadyExists<Message>The specified container already exists.
> RequestId:dd29ea2b-301e-0028-7c48-d32669000000
> Time:2022-09-28T14:43:46.6620455Z</Message></Error>
> 
> Headers:
> Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
> x-ms-request-id: dd29ea2b-301e-0028-7c48-d32669000000
> x-ms-client-request-id: cee02178-8582-410f-8c86-e1e6b6e8c01e
> x-ms-version: 2020-04-08
> x-ms-error-code: ContainerAlreadyExists
> Date: Wed, 28 Sep 2022 14:43:45 GMT
> Content-Length: 230
> Content-Type: application/xml
> 
> 
> Stack trace
>    at Azure.Storage.Blobs.ContainerRestClient.CreateAsync(Nullable`1 timeout, IDictionary`2 metadata, Nullable`1 access, String defaultEncryptionScope, Nullable`1 preventEncryptionScopeOverride, CancellationToken cancellationToken)
>    at Azure.Storage.Blobs.BlobContainerClient.CreateInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken, String operationName)
>    at Azure.Storage.Blobs.BlobContainerClient.CreateAsync(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, CancellationToken cancellationToken)
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 166
>    at Azure.AI.Translation.Document.Tests.DocumentTranslationLiveTestBase.CreateContainerAsync(String name, List`1 documents) in /Users/runner/work/1/s/sdk/translation/Azure.AI.Translation.Document/tests/Infrastructure/DocumentTranslationLiveTestBase.cs:line 155
>    at Azure.AI.Translation.Document.Tests.DocumentTranslationLiveTestBase.CreateTargetContainerWithClientAsync(List`1 documents) in /Users/runner/work/1/s/sdk/translation/Azure.AI.Translation.Document/tests/Infrastructure/DocumentTranslationLiveTestBase.cs:line 131
>    at Azure.AI.Translation.Document.Tests.TranslationOperationLiveTests.DocumentTranslationWithGlossary() in /Users/runner/work/1/s/sdk/translation/Azure.AI.Translation.Document/tests/TranslationOperationLiveTests.cs:line 422
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1881315&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Translation is owned by the service team, who are flagged on multiple test issues.   I'm going to close this out, as I don't think we need to track each failure individually.
