### ISSUE TITLE
[QUERY] How to create a long running polling object from uri

### ISSUE THREAD

**Issue by PepijnGramberg** [Azure/azure-sdk-for-net#31549]
### Library name and version

Azure.ResourceManagement.Sql 1.0.0

### Query/Question

When using `SqlDatabaseResource.ExportAsync(WaitUntil.Started,....)` it returns `ArmOperation<ImportExportOperationResult>` which can be used to update the status periodically to poll whether the export is completed. 

However in our architecture, we would like to do the polling from another (distributed) service, the polling object does expose `.Id` which should give an uri that can be used to poll, but how would that be used in combination with the ArmClient? Or do you have to start doing low level http calls yourself, including dealing with all authentication issues?

This might be a more generic problem/feature for all kinds of long polling situations.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@PepijnGramberg 
We are working on a new feature https://github.com/Azure/autorest.csharp/issues/2158 that will address your concern, right now this is something that our SDK cannot help
CC: @ArthurMa1978 @m-nash

**Comment by ArthurMa1978** [comment]
This is a new feature we are working with, currently no workaround, and we planned to ship this feature by the end of this year, maybe next month.

**Comment by ArthurMa1978** [comment]
Close this as we have created the [Rehydration](https://github.com/Azure/autorest.csharp/issues/2158) issue to track this feature.
