### ISSUE TITLE
[Search] GetAsyncTest failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#31546]
Search nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Operation would exceed 'standard' tier service quota. You are using 12 out of 12 'standard' tier service quota. If you need more quota, please submit a quota increase request with issue type 'Service and subscription limits (quota)' and quota type 'Search' following https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-quota-errors. RequestId: d7cbfeb2-57e6-4dba-8311-286b3fc22500
> Status: 409 (Conflict)
> ErrorCode: ServiceQuotaExceeded
> 
> Content:
> {
> "error": {
> "code": "ServiceQuotaExceeded",
> "message": "Operation would exceed 'standard' tier service quota. You are using 12 out of 12 'standard' tier service quota. If you need more quota, please submit a quota increase request with issue type 'Service and subscription limits (quota)' and quota type 'Search' following https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-quota-errors. RequestId: d7cbfeb2-57e6-4dba-8311-286b3fc22500"
> }
> }
> 
> Headers:
> Cache-Control: no-cache
> Pragma: no-cache
> client-request-id: REDACTED
> x-ms-client-request-id: be9b64ed-f788-4098-8e42-b761dd2307c6
> x-ms-request-id: be9b64ed-f788-4098-8e42-b761dd2307c6
> request-id: be9b64ed-f788-4098-8e42-b761dd2307c6
> elapsed-time: REDACTED
> Strict-Transport-Security: REDACTED
> x-ms-ratelimit-remaining-subscription-writes: REDACTED
> x-ms-correlation-request-id: REDACTED
> x-ms-routing-request-id: REDACTED
> X-Content-Type-Options: REDACTED
> Date: Thu, 29 Sep 2022 17:15:16 GMT
> Content-Length: 490
> Content-Type: application/json; charset=utf-8
> Content-Language: REDACTED
> Expires: -1
> 
> 
> Stack trace
>    at Azure.ResourceManager.Search.ServicesRestOperations.CreateOrUpdate(String subscriptionId, String resourceGroupName, String searchServiceName, SearchServiceData data, SearchManagementRequestOptions searchManagementRequestOptions, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/search/Azure.ResourceManager.Search/src/Generated/RestOperations/ServicesRestOperations.cs:line 116
>    at Azure.ResourceManager.Search.SearchServiceCollection.CreateOrUpdate(WaitUntil waitUntil, String searchServiceName, SearchServiceData data, SearchManagementRequestOptions searchManagementRequestOptions, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/search/Azure.ResourceManager.Search/src/Generated/SearchServiceCollection.cs:line 113
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.InstrumentResultInterceptor.InstrumentOperationInterceptor[T](IInvocation invocation, Func`1 innerTask) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/InstrumentResultInterceptor.cs:line 105
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 166
>    at Azure.ResourceManager.Search.Tests.SearchServiceCollectionTests.GetAsyncTest() in /Users/runner/work/1/s/sdk/search/Azure.ResourceManager.Search/tests/Tests/SearchServiceCollectionTests.cs:line 69
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1885071&view=results

@jsquire for notification.

**Comment by ShivangiReja** [comment]
Fix: https://github.com/Azure/azure-sdk-for-net/pull/31589

Pipeline is now green - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1894931&view=results
