### ISSUE TITLE
What is the default values for start and end time? Additionally, setting the start and end doesn't actually filter the results.

### ISSUE THREAD

**Issue by jteves** [Azure/azure-sdk-for-net#31572]
I have zero clue what the default period of search [PipelineOperationsExtensions.List API](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datalake.analytics.pipelineoperationsextensions.list?view=azure-dotnet) filters on. Additionally, when I call this with the start and end time values set, the results (# of jobs ran for each pipeline) does not change at all to filter on time. Why does this happen?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 587d1cd5-c16d-f2cd-2b78-592c5246f512
* Version Independent ID: aa1ac54e-8090-0287-7b3c-ad74e8ffeec4
* Content: [PipelineOperationsExtensions.List Method (Microsoft.Azure.Management.DataLake.Analytics) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datalake.analytics.pipelineoperationsextensions.list?view=azure-dotnet#feedback)
* Content Source: [xml/Microsoft.Azure.Management.DataLake.Analytics/PipelineOperationsExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.DataLake.Analytics/PipelineOperationsExtensions.xml)
* Service: **data-lake-analytics**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Based on the discussion in the ICM, this issue is not related with the SDK, therefore I will close it. Feel free to reopen it if you still have problem.
