### ISSUE TITLE
[BUG] Azure Form Recognizer Prebuilt Business Card Template code.

### ISSUE THREAD

**Issue by rvinothrajendran** [Azure/azure-sdk-for-net#31573]
### Library name and version

Azure Form Recognizer (2022-08-31) (GA)

### Describe the bug

Template Prebuilt Business Card operations with the Azure Form Recognizer client library code a bug 
AsList() , AsDictionary() , AsString()

example 

**ContactNamesField.AsList()**
**contactNameField.AsDictionary();**
**firstNameField.AsString();**

```
foreach (DocumentField contactNameField in **ContactNamesField.AsList()**)

  if (contactNameField.**ValueType** == DocumentFieldType.Dictionary)                
{
                    IReadOnlyDictionary<string, DocumentField> contactNameFields = **contactNameField.AsDictionary();**

                    if (contactNameFields.TryGetValue("FirstName", out DocumentField firstNameField))
                    {
                        if (firstNameField.ValueType == DocumentFieldType.String)
                        {
                            string firstName **= firstNameField.AsString();**
```

### Expected behavior

Template Prebuilt Business Card operations with the Azure Form Recognizer client library code must be changed as  
AsList() , AsDictionary() , AsString() convert from Value field.

**ContactNamesField.Value.AsList()
contactNameField.Value.AsDictionary()
firstNameField.Value.AsString()**

```
 foreach (DocumentField contactNameField in **ContactNamesField.Value.AsList()**)
                        {
                            Console.WriteLine("Contact Name: ");

                            if (contactNameField.FieldType == DocumentFieldType.Dictionary)
                            {
                                IReadOnlyDictionary<string, DocumentField> contactNameFields = **contactNameField.Value.AsDictionary()**;

                                if (contactNameFields.TryGetValue("FirstName", out DocumentField firstNameField))
                                {
                                    if (firstNameField.FieldType == DocumentFieldType.String)
                                    {
                                        string firstName = **firstNameField.Value.AsString()**;
                                    }
                                }

```

### Actual behavior

https://formrecognizer.appliedai.azure.com/studio/prebuilt?formType=businessCard

### Reproduction Steps

https://formrecognizer.appliedai.azure.com/studio/prebuilt?formType=businessCard

Refer Code area and select C#

### Environment

https://formrecognizer.appliedai.azure.com/studio/prebuilt?formType=businessCard

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @rvinothrajendran, and thanks for reporting this issue. The samples in Form Recognizer Studio are a bit outdated and don't use the latest API of the SDK. We'll work on updating those and I'll let you know once it's done.

**Comment by pallavit** [comment]
@kinelski Is this something that the service team owns? Can we create a follow-up bug in their system and close this one?

**Comment by kinelski** [comment]
@pallavit Yes, this is owned by the service team. I already notified them about what needs to be changed to update the samples, so we can't do much on the SDK side anymore. I'll check how to create an issue in their system and close this.

**Comment by adreno-abhi** [comment]
Hi. Is there an update on this?
I am facing the same issue on the business card model sample code in aslist(), asdictionary(), AsPhoneNumber

**Comment by kinelski** [comment]
@rvinothrajendran @adreno-abhi The samples in Form Recognizer Studio have been fixed. Feel free to update this issue if you think we missed anything.
