### ISSUE TITLE
[FEATURE REQ] Add ability to register ArmClient to DI via AddAzureClients

### ISSUE THREAD

**Issue by Stolpe** [Azure/azure-sdk-for-net#31579]
### Library name

Azure.ResourceManager

### Please describe the feature.

I would like to be able to register an `ArmClient` via `AddAzureClients` from Microsoft.Extensions.Azure.

The reason I want to do this is to be able to create my `TokenCredential` from configuration, an approach I use in order to be able to use different credential types locally and when deployed to Azure, without any code changes. Also, it helps a lot to be able to mock my client and insert it to the constructor of what ever service I'm currently unit testing.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@Stolpe , you can use the below code to register ArmClient in DI
```csharp
using IHost host = Host.CreateDefaultBuilder(args)
   .ConfigureServices((context,services) =>
   {
       services.AddAzureClients(builder =>
       {
           
           builder.AddClient<ArmClient, ArmClientOptions>(options =>
           {
               options.Environment = ArmEnvironment.AzurePublicCloud;
               options.Diagnostics.IsLoggingContentEnabled=true;
               options.Diagnostics.IsLoggingEnabled=true;
               var client = new ArmClient(new DefaultAzureCredential(
                   new DefaultAzureCredentialOptions() 
                   { VisualStudioTenantId=context.Configuration.GetValue<string>("VisualStudioTenantId") }),
                   context.Configuration.GetValue<string>("DefaultSubscriptionId"),
                   options);
               
               return client;                
           });

       });
       services.AddScoped<VirtualMachineCollection>((sp) =>
       {
           var armClient = sp.GetService<ArmClient>();
           return armClient?.GetDefaultSubscription().GetResourceGroup(RESOURCE_GROUP_NAME).Value.GetVirtualMachines();
       });
}
```
I have some more comments regarding the scenario you are sharing in this issue
`an approach I use in order to be able to use different credential types locally and when deployed to Azure, without any code changes` -> You can actually use DefaultAzureCredential in your code 
The order and locations in which DefaultAzureCredential looks for credentials is shown in the diagram and table below.
![image](https://user-images.githubusercontent.com/5089150/194686058-2074c51e-a056-471e-a667-71dbfab13dcf.png)

` it helps a lot to be able to mock my client and insert it to the constructor of what ever service I'm currently unit testing.` ->
Please be careful that lot of method of ArmClient is extend method imported from other Azure SDK package and those method can not be mocked,

**Comment by Stolpe** [comment]
Thank you for your reply,

In my use-case, in Azure, we use an app service using several user assigned identities. In our enterprise environment, some shared resources have predefined identities with correct privileges (eg logging using an EventHub), that app services etc can use.

In order to be able to select which authentication method to use for a particular client, we make use of the `credential` configuration key used by the ClientFactory in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Microsoft.Extensions.Azure/src/Internal/ClientFactory.cs#L87-L213, a method mentioned indirectly in https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Microsoft.Extensions.Azure/README.md. When the code is run in Azure (which we set as an environment, thus appending configuration using an _appsettings.Azure.json_ file), we set the `credential` value to `managedidentity`, together with a `clientId`. This allows us to make use of several different authentication methods in **a unified way**, with very simple code on our side.

As an example, here is a part of our appsettings.json
```json
{
  "Azure": {
    "ServiceBus": {
      "fullyQualifiedNamespace": "namespace.servicebus.windows.net"
    }
}
```
and in appsettings.Azure.json, we have
```json
{
  "Azure": {
    "ServiceBus": {
      "credential": "managedidentity",
      "clientId": ""
    }
}
```
where `clientId` is replaced in the deployment.

To add the client, we simply run
```csharp
.AddAzureClients(builder =>
    builder.AddServiceBusClient(configuration.GetSection("Azure:ServiceBus")))
```

This is a pattern that works very well for us (having finally dug up how `credential` works), and it can be applied to (almost) all SDK clients. One exception is the ArmClient, which is what I try to amend here.

**Comment by xboxeer** [comment]
@Stolpe I believe for ArmClient, you don't necessary to write an appsettings.json file to tell DefaultCredential to use env var in local and use managed identity in Azure Hosted env, DefaultCredential handles all these things for you automatically, you can find details in this [document](https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication?tabs=command-line#exploring-the-sequence-of-defaultazurecredential-authentication-methods)
```csharp
services.AddAzureClients(builder =>
       {
           
           builder.AddClient<ArmClient, ArmClientOptions>(options =>
           {
               options.Environment = ArmEnvironment.AzurePublicCloud;
               options.Diagnostics.IsLoggingContentEnabled=true;
               options.Diagnostics.IsLoggingEnabled=true;
               var client = new ArmClient(new DefaultAzureCredential(options);               
               return client;                
           });
       });
```

**Comment by xboxeer** [comment]
@Stolpe I agree with you that DefaultAzureCredential does not take an ArmClientOption, but if you look at the code that i shared before, you can find out that read credential information from appsettings.json is still available 
```csharp
using IHost host = Host.CreateDefaultBuilder(args)
   .ConfigureServices((context,services) =>
   {
       services.AddAzureClients(builder =>
       {
           
           builder.AddClient<ArmClient, ArmClientOptions>(options =>
           {
               options.Environment = ArmEnvironment.AzurePublicCloud;
               options.Diagnostics.IsLoggingContentEnabled=true;
               options.Diagnostics.IsLoggingEnabled=true;
               var client = new ArmClient(new DefaultAzureCredential(
                   new DefaultAzureCredentialOptions() 
                   { VisualStudioTenantId=context.Configuration.GetValue<string>("VisualStudioTenantId") }),
                   context.Configuration.GetValue<string>("DefaultSubscriptionId"),
                   options);
               
               return client;                
           });

       });
       services.AddScoped<VirtualMachineCollection>((sp) =>
       {
           var armClient = sp.GetService<ArmClient>();
           return armClient?.GetDefaultSubscription().GetResourceGroup(RESOURCE_GROUP_NAME).Value.GetVirtualMachines();
       });
}
```

The 
```csharp
context.Configuration.GetValue<string>("VisualStudioTenantId") }),
                   context.Configuration.GetValue<string>("DefaultSubscriptionId")
```
Is trying to get tenanted and subscriptionid from appsettings.json
```json
{
  "VisualStudioTenantId": "xxxxx-xxxxx",
  "DefaultSubscriptionId": "xxxxx-xxxxxxx"
}
```
You can change these keys to what you are currently using for other azure sdk clients. 
To add direct support for direct ArmClient in DI, like `builder.AddArmClient`, I'd like to have an internal discussion with SDK team to see what's the impact.

**Comment by Stolpe** [comment]
Hi,

Yes, my point isn't that it is not possible to register an `ArmClient` into DI using configuration from appsettings.json (or whichever source you may use). My point is that it not possible to use the extensions from `Microsoft.Extensions.Azure` to do it, so you will have to write your own custom format for how this is parsed. I don't mean to say that this is complicated, but since every other client from the new Azure SDK I have used so far can use this method, and `ArmClient` cannot, it is not bound to the same rules as the other clients.

Also, although not explicitly stated, the guidelines for the SDK mentions the missing constructor overload needed for the `Microsoft.Extensions.Azure` method to work, which is also an argument for including it.

I understand that this is probably a low priority issue, which is why I wrote the code myself, and submitted a PR.

**Comment by ArcturusZhang** [comment]
This issue has been fixed by https://github.com/Azure/azure-sdk-for-net/pull/35898
Therefore closing
