### ISSUE TITLE
[QUERY] Breaking changes in non-major package version updates

### ISSUE THREAD

**Issue by JoasE** [Azure/azure-sdk-for-net#31583]
### Library name and version

Azure.Identity 1.7.0

### Query/Question

It's common practice to do a major version number bump when breaking changes have been published.
Why does the Azure.Identity package deviate from this?
An breaking change was introduced in 1.7.0. the version should have been bumped up to 2.0.0
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/BREAKING_CHANGES.md#170

### Environment

does not apply

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jovinson-ms** [comment]
Also, the same document lists `1.4` as a breaking change that didn't have a major version bump.

**Comment by christothes** [comment]
We generally avoid major version bumps in the .NET SDKs unless there are very fundamental changes to the design of the library. Breaking changes are generally rare but are documented in the changelog when necessary.

Note: The guidelines linked above state that a breaking change "might" involve a major version bump. 

> Stable Release: Some languages bump the minor and others bump the patch version please see specific guidelines below based on your language. Breaking changes _**(which might increment the major version number)**_ are not allowed after a stable release without an exception and review by the architecture board.
