### ISSUE TITLE
Management library guidance is for a deprecated library

### ISSUE THREAD

**Issue by kimjamia** [Azure/azure-sdk-for-net#31592]
The management library section suggests to install [Microsoft.Azure.Management.Sql.Fluent](https://www.nuget.org/packages/Microsoft.Azure.Management.Sql.Fluent/) which has been deprecated.

Apparently the replacement library is: [Azure.ResourceManager.Sql](https://www.nuget.org/packages/Azure.ResourceManager.Sql/).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4a2ee884-131a-5641-b433-3a305239f3a4
* Version Independent ID: 90f66938-afd9-1ffe-69ab-9ccf244e2956
* Content: [Azure SQL Database APIs for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/sql)
* Content Source: [api/overview/azure/sql.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/sql.md)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
