### ISSUE TITLE
Make troubleshooting guides consistent across our track2 SDKs 

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#31597]
Most of our track2 data plane SDKs troubleshooting guides are inconsistent in what sections are available, whether we include general core errors or just SDK specific errors, include samples or not.

It would be good to have some level of consistency just like we have on readmes. The exact information in them differs but having a general theme would create uniformity.

**Comment by heaths** [comment]
Just for context, when we first started TSGs, we decided not to duplicate information from Core because it'd be harder to keep up to date. Would be great to more formalize the general structure.

**Comment by heaths** [comment]
If we're going to link to specific sections per #31598 we should probably use explicit `<a name=""></a>` bookmarks for sections since section titles could change - especially from this effort here.
