### ISSUE TITLE
[FEATURE REQ] Ability to track database import progress: return operation id from import action

### ISSUE THREAD

**Issue by tbolon** [Azure/azure-sdk-for-net#31607]
### Library name

Azure.ResourceManager.Sql

### Please describe the feature.

When running a database import operation `SqlDatabaseResource.Import()` with `Azure.WaitUntil.Started` we have no details about the started operation. The json returned by the response does not contains data about the operation id: `{"operation":"Import","startTime":"2022-10-05T15:25:48.9506752Z"}`.

We can't obtain the operation id, since the `Id` property throw a `NotImplementedException`.

When calling `UpdateStatus` method, the json returned contains the operation id: `{"name":"f2d498c4-2f32-44e2-bca9-3f41bf29f59f","status":"InProgress","startTime":"2022-10-05T15:25:48Z"}`.

I would like to use `SqlDatabaseResource.GetDatabaseOperations()` to track the import progress, but the only way is to manually parse the json after the UpdateStatus() to obtain the operation id.

Could the `ArmOperation<ImportExportOperationResult>` expose the operation id when calling `Import` with `Azure.WaitUntil.Started` ?

**Comment by xboxeer** [comment]
@tbolon  Similar issue here https://github.com/Azure/azure-sdk-for-net/issues/31549 , we are working on a new feature to fix this https://github.com/Azure/autorest.csharp/issues/2158 
CC: @ArthurMa1978 @m-nash 

If you have any other feedback regarding our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)

**Comment by ArthurMa1978** [comment]
Close this as we have created the [Rehydration](https://github.com/Azure/autorest.csharp/issues/2158) issue to track this feature.
