### ISSUE TITLE
Microsoft.Azure.Management.ResourceManager invalid version 

### ISSUE THREAD

**Issue by Elodie-D** [Azure/azure-sdk-for-net#3160]
Here is the message I get when I try to use the latest version of the api : 
The api-version '2017-05-10' is invalid. The supported versions are '2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

**Comment by adrianhall** [comment]
Is this still an issue?

If it is, please re-open with the following information:

1) The .NET library that you are using (and version)
2) The code that generates the error

Thanks,
