### ISSUE TITLE
Resolve inaccurate validation failures for conflicting dependencies between Azure SDKs and PS

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#31604]
Aggregate reports has been failing for some time with the following errors

WARNING: For [System.Security.Cryptography.Xml] AzureSDK requires higher version [4.0.3.1] then what PS has [4.0.3.0]
WARNING: For [System.Security.Principal.Windows] AzureSDK requires higher version [5.0.0.0] then what PS has [4.1.3.0]
WARNING: For [System.Security.AccessControl] AzureSDK requires higher version [5.0.0.0] then what PS has [4.1.3.0]
WARNING: For [System.IO.FileSystem.AccessControl] AzureSDK requires higher version [5.0.0.0] then what PS has [4.0.5.0]

As a follow up we need to understand why we needed more recent versions and either get them downgraded or move PS to more recent versions.

**Comment by pallavit** [comment]
@jsquire has PS upgraded their dependencies?

**Comment by jsquire** [comment]
They did, but there's something in their servicing release that is still flagging; I haven't had a chance to follow-up with Heath on what the differences are with those files and why we're validating the way we are.

**Comment by jsquire** [comment]
These are not actual failures, but validation issues due to very, very outdated configuration files.
