### ISSUE TITLE
DataLakeLeaseClientExtensions isn't testable

### ISSUE THREAD

**Issue by amoghnatu** [Azure/azure-sdk-for-net#31605]
Can this extension class be coded in a way such that it is testable? Mainly when the main datalakeleaseclient class is mocked, it is impossible right now to mock this method since it is an extension method. If there is some way I can inject the mocked extended type, that'd be great.

thanks,
Amogh.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a82a9820-00b6-3148-41d0-8b6b4d2750bb
* Version Independent ID: 522043e2-1400-c6e3-e62e-434b1253d021
* Content: [DataLakeLeaseClientExtensions Class (Azure.Storage.Files.DataLake) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.files.datalake.datalakeleaseclientextensions?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Files.DataLake/DataLakeLeaseClientExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.DataLake/DataLakeLeaseClientExtensions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by navba-MSFT** [comment]
@sumantmehtams Could you please look into this and provide an update ? Thanks in advance.
