### ISSUE TITLE
[BUG] Incorrect PrincipalID data type in C# Kusto Management Library

### ISSUE THREAD

**Issue by NateB2** [Azure/azure-sdk-for-net#31618]
### Library name and version

Azure.ResourceManager.Kusto 1.0.0

### Describe the bug

In the Kusto management library Track 1 SDK, when creating a database principal assignment, the "PrincipalID" parameter was a string type, and according to the documentation, could be a user email, application ID, or security group name.  On the [REST API documentation page](https://learn.microsoft.com/en-us/rest/api/azurerekusto/database-principal-assignments/create-or-update?tabs=HTTP), it says the same thing.

However, in the new Track 2 C# SDK, a guid is required for that parameter, which obviously won't work for an email address, which is our scenario:
![image](https://user-images.githubusercontent.com/1522539/194195014-dc45e37e-a91c-4e68-9b5d-4309ca2cf467.png)

Note that the description of that parameter says that an email address is an accepted type.

### Expected behavior

We're able to create a database principal assignment using an email address.

### Actual behavior

Cannot pass in an email address in the "principalId" parameter.

### Reproduction Steps

Create the following object while using the "Azure.ResourceManager.Kusto" 1.0.0 nuget package:

```
string emailAddress = "a@example.com";
new KustoDatabasePrincipalAssignmentData()
{
    PrincipalId = emailAddress
};
```

It will throw an error at the line where it's assigning the email address to the PrincipalId parameter.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@Yao725 please help on this issue

**Comment by Yao725** [comment]
Will take a look, thank you for the feedback.

**Comment by Yao725** [comment]
Hi @NateB2, we have released a new version [1.0.1](https://www.nuget.org/packages/Azure.ResourceManager.Kusto/1.0.1). In this release we introduced a new property named `DatabasePrincipalId` to fix this issue.

**Comment by NateB2** [comment]
Awesome, thanks!

**Comment by Yao725** [comment]
Close this issue as we have fixed it, feel free to reopen it or open a new issue if you still have problem, thanks.
