### ISSUE TITLE
[QUERY] Use AzureCredentials with token from Authorization Code Flow

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-net#31613]
### Library name and version

Microsoft.Azure.Management.ResourceManager.Fluent.Authentication

### Query/Question

We are attempting to use this package in our SaaS. Process as follows:

- customer logs in to their Azure AD account from our SaaS using the OAuth 2.0 Authorization Code Flow
- we receive the user token
- we use that token to authenticate against the user's Azure environment and are able to "GET Subscriptions" for example (or GET Azure VMs or any other Azure APIs really).

Right now we are struggling to create/use `AzureCredentials` with a bearer token obtained via OAuth 2.0 Authorization Code Flow.
Is this possible? If yes, do you have a working code sample for this?
If no, what else can we do if we want to give the user the above UX?

Thanks, David

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by alexguevara** [comment]
I'd be interested in this as well. 
I tried 
` var tokenCredentials = new TokenCredentials(token);
            var azureCredentials = new AzureCredentials(
                tokenCredentials,
                tokenCredentials,
                tenantId,
                AzureEnvironment.AzureGlobalCloud);
            return Authenticate(azureCredentials);`
but that didn't work.

**Comment by davidobrien1985** [comment]
@xboxeer any insights here to get this working?

**Comment by Petermarcu** [comment]
Hi @davidobrien1985 , 

The package you are using has been deprecated in favor of new libraries for doing Azure resource management. What you are trying to do was actually one of the key features that was added in the new libraries which are backed by [Azure.Identity](https://www.nuget.org/packages/Azure.Identity/) and [MSAL](https://www.nuget.org/packages/Microsoft.Identity.Client).

These are the two new packages for managing Azure Resources that I think you want to be using:

[Azure.ResourceManager](https://www.nuget.org/packages/Azure.ResourceManager/)
[Azure.ResourceManager.Resources](https://www.nuget.org/packages/Azure.ResourceManager.Resources/)

Here is an example that I think will help:
https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemanager/Azure.ResourceManager#resourcedatacs

If your application has already auth'ed the user and acquired a token on their behalf, you can use DelegatedTokenCredential from Azure.Identity in lieu of DefaultAzureCredential in those code examples. 

Something like this:
`var client = new ArmClient(DelegatedTokenCredential.Create((_, _) => token);`

**Comment by Petermarcu** [comment]
@schaabs
