### ISSUE TITLE
How to specify folder name inside container while querying blobs by tags 

### ISSUE THREAD

**Issue by Shyam268** [Azure/azure-sdk-for-net#31620]
I am using FindBlobsByTagsAsync to retrieve the necessary blobs. The problem is that this will search through entire blob container. But I just need to search through a specific folder

**Question**: Is there a way to search through a specific folder to retrieve the necessary blobs using Blob Tags?

Here is my azure container structure. All the blobs are tagged by date time.  if we query by Datetime tag it will list the all the blobs from all the folder.  but i want to query from one folder(container/folder-2) using datetime tag.? is it possible without adding additional tag folder name to the blob?

  **Container Name**

     Folder-1
           file1.json
           file2.json
     Folder-2
          file1.json
          file2.json
    Folder-3
         file1.json

**Question**: Also how to find the untagged blobs from container?

**Comment by SaurabhSharma-MSFT** [comment]
@Shyam268 We are looking into it and get back to you.

**Comment by SaurabhSharma-MSFT** [comment]
@Shyam268 Yes, I don't think there is any other way to get the folder names other than using creating a folder name tag. However, I am redirecting this to services team to look into and provide any alternatives, if any.

**Comment by seanmcc-msft** [comment]
@Shyam268, unfortunately this is not possible, as it is not supported by the underlying [Find Blobs by Tag REST API](https://learn.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags-container?tabs=microsoft-entra-id).
