### ISSUE TITLE
[BUG] MessageToPocoConverter overrides any custom ServiceBusReceivedMessage open converters

### ISSUE THREAD

**Issue by pposps** [Azure/azure-sdk-for-net#31623]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.7.0

### Describe the bug

Hey,

As in title, I'm trying to add my custom open converter for `ServiceBusReceivedMessage`:

```cs
...
context.AddOpenConverter<ServiceBusReceivedMessage, MessageEnvelope<OpenType>>(typeof(GenericMessageEnvelopeConverter<>));
...
```

also tried with `OpenType.Poco`
```cs
...
context.AddOpenConverter<ServiceBusReceivedMessage, MessageEnvelope<OpenType.Poco>>(typeof(GenericMessageEnvelopeConverter<>));
...
```
Here is my open converter:
```cs
internal class GenericMessageEnvelopeConverter<T> : IConverter<ServiceBusReceivedMessage, MessageEnvelope<T>>
```

### Expected behavior

My custom open converter is called instead of `MessageToPocoConverter`.

### Actual behavior

Every time when queue triggers:
```cs
 [FunctionName(nameof(ServiceBusStart))]
        public async Task ServiceBusStart(
            [ServiceBusTrigger("%queueName%", Connection = "SbConnString")] MessageEnvelope<MyCustomType> msg,
            [DurableClient] IDurableOrchestrationClient starter)
```
it calls `MessageToPocoConverter` - which is added in [ServiceBusExtensionProvider](https://github.com/Azure/azure-sdk-for-net/blob/ae550cb5d4be459e61d0f42f46c00033b0fc9a83/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Config/ServiceBusExtensionConfigProvider.cs#L99)  - well I am not 100% it calls `MessageToPocoConverter`, but I get this [error ](https://github.com/Azure/azure-sdk-for-net/blob/a5774982b37d5e67fd3fe536e5a5f5e5172427f4/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Triggers/MessageToPocoConverter.cs#L89) when using `MessageEnvelope` without parameterless constructor .

I believe that I've wired up everything correctly since when I change my custom converter from open to regular one:
```cs
...
context.AddConverter<ServiceBusReceivedMessage, int>(new GenericMessageEnvelopeConverter());
...
```
the converter is called as expected

### Reproduction Steps

Create custom `ServiceBusReceivedMessage` open converter and trigger it with message.

### Environment

local machine Windows 10, netcoreapp3.1, VS 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @pposps,
I imagine that both your open converter and the library open converter would match, but the library converter is used because it is added first. Would it be possible to not use generics in your message type so that you can use a regular converter?

If that is not feasible, we may need to submit this as a feature request to the WebJobs repo to add more intelligent matching when using open converters.

**Comment by JoshLove-msft** [comment]
Fair enough, in that case I will move this over to the WebJobs SDK for consideration.

**Comment by JoshLove-msft** [comment]
Issue moved to [Azure/azure-webjobs-sdk #2925](https://github.com/Azure/azure-webjobs-sdk/issues/2925) via [**Zenhub**](https://www.zenhub.com/)
