### ISSUE TITLE
[BUG] AppService ResourceManager: Unexpected nulls

### ISSUE THREAD

**Issue by Vevish** [Azure/azure-sdk-for-net#31638]
### Library name and version

Azure.ResourceManager.AppService

### Describe the bug

Azure.ResourceManager.AppService Versions 1.0.0-beta.4 and 1.0.0. Site configuration tls version and ftp state returning nulls
Part code below. Client is Authenticated and receiving values for other parts of the App service. Code and response attached

### Expected behavior

Should return app configuration values of the app services such as TLS version, FTP state etc. 

### Actual behavior

returning nulls withing the Json Text 

### Reproduction Steps

using Azure.ResourceManager;
using Azure.ResourceManager.AppService;
using Azure.ResourceManager.Compute;
using Azure.ResourceManager.Consumption;
using Azure.ResourceManager.KeyVault;
using Azure.ResourceManager.Kusto;
using Azure.ResourceManager.Network;
using Azure.ResourceManager.Resources;
using Azure.ResourceManager.Sql;

Svar ArmClient = MainAuth.GetArmClient(Credentials); //Authenticates custom arm client use any arm client from here 

SubScriptions TheSubscriptions = new SubScriptions();

var AppServices = ArmClient.GetSubscriptions().GetAll();
var Subs = AppServices.ToList(); //Gets AppServices based on Auth Information 

var FirstSub = Subs.FirstOrDefault();

foreach (var r in Subs) // going through Subs
{
    var RSGs = r.GetResourceGroups().GetAll();

    foreach (var rg in RSGs) // going through resource groups
    {
        var AppPlans = rg.GetAppServicePlans().GetAll(); //goiung through app services 
        foreach (var appPlan in AppPlans)
        {
            Console.WriteLine(appPlan.Id);
            Console.WriteLine(appPlan.Data.Name);
            Console.WriteLine(appPlan.Data.Kind);

            var theApps = appPlan.GetWebApps().ToList();

            foreach (var app in theApps)
            {
                Console.ReadLine();
                var FullAppCOnfig = appPlan.GetWebApps(app.Name, rg.Data.Name).FirstOrDefault(); //returns nulls also although other values are populated in this data

                try
                {
                    Console.WriteLine(FullAppCOnfig.SiteConfig.MinTlsVersion);
                }
                catch
                {

                }
                try
                {
                    var siteconf = app.SiteConfig;
                    Console.WriteLine(siteconf.MinTlsVersion.Value); //returns nulls also although other values are populated in this data 
                }
                catch
                {

                }
            }

        }

    }
}
[
[response.txt](https://github.com/Azure/azure-sdk-for-net/files/9729223/response.txt)
](url)

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.400
 Commit:    7771abd614

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

global.json file:
  Not found

Host:
  Version:      6.0.8
  Architecture: x64
  Commit:       55fb7ef977

.NET SDKs installed:
  6.0.201 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
PM>

**Comment by xboxeer** [comment]
@Vevish
Your code 
`var FullAppCOnfig = appPlan.GetWebApps(app.Name, rg.Data.Name).FirstOrDefault(); //returns nulls also although other values are populated in this data
` 
is pass in app.Name and rg.Data.Name while the GetWebApps are expecting `skipToken` and `filter` as its method signature suggested
`public virtual Pageable<WebSiteData> GetWebApps(string skipToken = null, string filter = null, string top = null, CancellationToken cancellationToken = default(CancellationToken))`
that's why that line of code returns null
For the other issue in your code 
```csharp
var siteconf = app.SiteConfig;
Console.WriteLine(siteconf.MinTlsVersion.Value); //returns nulls also although other values are populated in this data 
```
I do noticed this `MinTlsVersion` is returning null and the raw responses also show MinTlsVersion returned is null, so SDK is accurately reflect what is returned from AppService, may I know how did you config this TlsVersion in actual?

**Comment by Vevish** [comment]
> @Vevish Your code `var FullAppCOnfig = appPlan.GetWebApps(app.Name, rg.Data.Name).FirstOrDefault(); //returns nulls also although other values are populated in this data ` is pass in app.Name and rg.Data.Name while the GetWebApps are expecting `skipToken` and `filter` as its method signature suggested `public virtual Pageable<WebSiteData> GetWebApps(string skipToken = null, string filter = null, string top = null, CancellationToken cancellationToken = default(CancellationToken))` that's why that line of code returns null For the other issue in your code
> 
> ```cs
> var siteconf = app.SiteConfig;
> Console.WriteLine(siteconf.MinTlsVersion.Value); //returns nulls also although other values are populated in this data 
> ```
> 
> I do noticed this `MinTlsVersion` is returning null and the raw responses also show MinTlsVersion returned is null, so SDK is accurately reflect what is returned from AppService, may I know how did you config this TlsVersion in actual?
Hi There
The Tls version, is set to 1.2 and even the Ftp config has values. Both these methods tried to fetch the same data with nulls. Am I supposed to do something different to return other values? Parts of the JSON response has values so the query is working in both instances

**Comment by ArthurMa1978** [comment]
Add @HarveyLink, please try this case and make sure this is service issue or usage issue.

**Comment by HarveyLink** [comment]
This is a service issue. Verified with both SDK and RestAPI, the TLS value inside site config is null.
Portal:
![image](https://user-images.githubusercontent.com/30464227/194808719-9a916780-4fd8-4150-866b-429f851709d2.png)
SDK with Fiddler:
![image](https://user-images.githubusercontent.com/30464227/194808819-c500db37-fe73-40ea-8df6-2a220e2e7536.png)
Rest API:
![image](https://user-images.githubusercontent.com/30464227/194808869-892937a3-93fe-4919-8ac0-c8e8cfa91e27.png)

**Comment by Vevish** [comment]
Hello any feedback on this one thanks?

**Comment by Vevish** [comment]
Hello do i need to log a call somewhere else with Microsoft Azure ?

**Comment by HarveyLink** [comment]
Hi @Vevish , our service team will check the Github issue time to time. Meantime, if you have other feedback channels, you could try to request their help on it.
