### ISSUE TITLE
[BUG] Empty policySetDefinitionId throws 'resourceId' null error in Azure.ResourceManager.PolicyInsights when loading PolicyStates

### ISSUE THREAD

**Issue by lukerogers** [Azure/azure-sdk-for-net#31633]
### Library name and version

Azure.ResourceManager.PolicyInsights 1.0.0

### Describe the bug

When loading the PolicyState for anything, if the "policySetDefinitionId" is null, it throws an error saying the resourceId is null. This field isn't required as a policy might not have a definition associated with it. 

I believe the issue is that the type is a ResourceIdentifier and that object throws an error is the string is null or empty

### Expected behavior

PolicyState is able to be loaded if policySetDefinitionId is empty

### Actual behavior

System.ArgumentException: 'Value cannot be an empty string. (Parameter 'resourceId')' is thrown when the policySetDefinitionId is null.

In [PolicyState.Serialization.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/policyinsights/Azure.ResourceManager.PolicyInsights/src/Generated/Models/PolicyState.Serialization.cs) (194), it passes an empty string to the contructor of the ResourceIdentifier object.

Here is the constructor for ResourceIdentifer
```
public ResourceIdentifier(string resourceId)
{
  Argument.AssertNotNullOrEmpty(resourceId, nameof(resourceId));

  _stringValue = resourceId;

  if (resourceId.Length == 1 && resourceId[0] == Separator)
  {
    //this is the same as Root but can't return that since this is a ctor
    Init(null, ResourceType.Tenant, string.Empty, false, SpecialType.None);
    return;
  }
}
```
I can't figure out what needs to change to made this work. Obviously a if(!string.IsNullOrEmpty(property.Value.GetString())) check in PolicyState.Serialization.cs before loading the ResourceIdentifier would work, but I don't know how to handle this with Autorest.

### Reproduction Steps

Here is one of my payloads that is throwing the error with personal info removed:

```
{
  "@odata.id": null,
  "@odata.context": "https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.PolicyInsights/policyStates/$metadata#latest/$entity",
  "timestamp": "2022-10-06T03:15:53.8325601Z",
  "resourceId": "/subscriptions/{subscriptionId}/resourcegroups/{resourceGroup}/providers/microsoft.web/sites/{someSiteName}",
  "policyAssignmentId": "/providers/microsoft.management/managementgroups/{guid}/providers/microsoft.authorization/policyassignments/102",
  "policyDefinitionId": "/providers/microsoft.management/managementgroups/{guid}/providers/microsoft.authorization/policydefinitions/102",
  "effectiveParameters": "",
  "isCompliant": true,
  "subscriptionId": "{subscriptionId}",
  "resourceType": "Microsoft.Web/sites",
  "resourceLocation": "eastus2",
  "resourceGroup": "{resourceGroup}",
  "resourceTags": "tbd",
  "policyAssignmentName": "102",
  "policyAssignmentOwner": "tbd",
  "policyAssignmentParameters": "",
  "policyAssignmentScope": "/providers/Microsoft.Management/managementgroups/cfa5342f-a686-4a51-9d41-3736c6ba8c2e",
  "policyDefinitionName": "102",
  "policyDefinitionAction": "auditifnotexists",
  "policyDefinitionCategory": "tbd",
  "policySetDefinitionId": "",
  "policySetDefinitionName": "",
  "policySetDefinitionOwner": "",
  "policySetDefinitionCategory": "",
  "policySetDefinitionParameters": "",
  "managementGroupIds": "{guids}",
  "policyDefinitionReferenceId": "",
  "complianceState": "Compliant",
  "policyDefinitionGroupNames": [ "" ],
  "policyDefinitionVersion": "1.0.0",
  "policySetDefinitionVersion": "",
  "policyAssignmentVersion": "",
  "complianceReasonCode": ""
}
```
Try to deserialize that and it will throw the error.

### Environment

I'm running this on Windows 11 with .NET version 6.0.9 and Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Thanks for reaching out to us, created this [issue](https://github.com/Azure/autorest.csharp/issues/3064) to track the progress and we will discuss how to handle this case.

**Comment by ArthurMa1978** [comment]
@live1206 please help to confirm whether is issue has been fixed.

**Comment by lukerogers** [comment]
Any idea when a release will be created?

**Comment by live1206** [comment]
> Any idea when a release will be created?

Should be within this week, will update here once it's out.

**Comment by live1206** [comment]
Fix released in [Azure.ResourceManager.PolicyInsights/1.2.0-beta.1](https://www.nuget.org/packages/Azure.ResourceManager.PolicyInsights/1.2.0-beta.1)
