### ISSUE TITLE
"Callback invoked to tell whether a transfer should be done." Does Microsoft mean "to check"?

### ISSUE THREAD

**Issue by sijucm** [Azure/azure-sdk-for-net#31647]
What does Microsoft mean by "to tell" 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ceca8bae-57ee-ea98-3ae6-7b4f54a2411c
* Version Independent ID: 9e8bb125-1320-4862-930c-f3fe650e0b14
* Content: [ShouldTransferCallbackAsync Delegate (Microsoft.Azure.Storage.DataMovement) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.datamovement.shouldtransfercallbackasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Storage.DataMovement/ShouldTransferCallbackAsync.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Storage.DataMovement/ShouldTransferCallbackAsync.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@sijucm Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@sijucm The above PR has been filed to address the description of this delegate and it is currently under review.

**Comment by navba-MSFT** [comment]
@sijucm I have been informed by the Product Owners that, We’re not taking any changes to this repository. We’ve already put up the deprecation notice on the README, that only changes we’re taking are security issues or data integrity issues. I understand documentation issues are important however it’s important we don’t take any changes unless they’re absolutely necessary.

To answer your question, in [this](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.datamovement.shouldtransfercallbackasync?view=azure-dotnet) article “to tell” means “to check” means you can use the ShouldTransferCallbackAsync call to check the status of the transfer. 

Hope this clarifies. If you have any further further queries, please feel free to reopen this issue. We would be happy to assist you.
