### ISSUE TITLE
Cannot find API doc for "AzureServiceTokenProvider"

### ISSUE THREAD

**Issue by sijucm** [Azure/azure-sdk-for-net#31645]
It is not in the list of token providers. Please, please, please put some link to API reference when adding code. It is not hello-world we have to create

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 56851479-9543-a30c-37da-a1852def3797
* Version Independent ID: 4b2f90e7-dbfb-a811-64ff-9eea8b5b7443
* Content: [App Authentication client library for .NET - version 1.6.0 - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication)
* Content Source: [api/overview/azure/service-to-service-authentication.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/service-to-service-authentication.md)
* Product: **azure**
* GitHub Login: @jlichwa
* Microsoft Alias: **jalichwa**

**Comment by jsquire** [comment]
//cc: @anaismiller

**Comment by anaismiller** [comment]
Thanks @sijucm for flagging this issue. We do not have a specific API page as far as I am aware. I agree with you that this is a limitation. 
If you are looking for the connection string options, [this section](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication#connection-string-support) on the page may help.

In case you were not aware, "Microsoft.Azure.Services.AppAuthentication is no longer recommended to use with new Azure SDK. It is replaced with new Azure Identity client library available for .NET, Java, TypeScript and Python and should be used for all new development. Information about how to migrate to Azure Identitycan be found here: [AppAuthentication to Azure.Identity Migration Guidance](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration)."
As such, I am closing this issue with won't fix.
