### ISSUE TITLE
[Query] Which dependency type is this using?

### ISSUE THREAD

**Issue by bh3605** [Azure/azure-sdk-for-net#31640]
# Description
I've been migrating projects from Microsoft.Azure.ServiceBus to Azure.Messaging.ServiceBus and upgrading some other projects already using Azure.Messaging.Servicebus. My telemetry is showing different dependency types for the same dependency name. I'll focus on ServiceBusSender.Send.

Some of them have the type being Azure Service Bus. Others have the type as servicebus.

What package or version is specifying the type as Azure Service Bus? I know Azure.Messaging.ServiceBus has the type as a constant defined here: https://github.com/Azure/azure-sdk-for-net/blob/62f2223e46c33825628443d11b8267de4e72a1c6/sdk/servicebus/Azure.Messaging.ServiceBus/src/Diagnostics/DiagnosticProperty.cs#:~:text=public%20const%20string%20ServiceBusServiceContext%20%3D%20%22servicebus%22%3B

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Can you provide a little more detail, such as a screenshot of the issue you are seeing? Also, what is the version of the Application Insights SDK that you are using?

 When testing, I always see Azure Service Bus for ServiceBusSender.Send.

**Comment by JoshLove-msft** [comment]
There was an update in 2.21.0 that fixed an issue with dependency tracking for Service Bus. Can you make sure you are using that version and try?

**Comment by bh3605** [comment]
Can you tell me which Type I'm suppose to be looking for? Azure Service Bus or servicebus?

**Comment by JoshLove-msft** [comment]
> Can you tell me which Type I'm suppose to be looking for? Azure Service Bus or servicebus?

I would expect the dependency type to be Azure Service Bus if you are using the latest App Insights SDK version 2.21.0.
