### ISSUE TITLE
Distributed tracing [Zn] uber-task: GA OTel support in Azure.Core

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#31650]
### Library name

Azure.Core

### Please describe the feature.

Here's a list of prereqs for GA on .NET

- [x] Support configurable OpenTelemetry [schema version](https://opentelemetry.io/docs/reference/specification/schemas/overview/#schema-version-number)
  - Stamp it on `az.schema_url` attribute on Activities reported via ActivitySource only
  - Support 1.17.0 initially only (TBD - will switch to latest by GA)
  - Map attribute names reported by SDKs to corresponding ones in configured schema version. Here's the current list https://github.com/Azure/azure-sdk/blob/main/docs/tracing/distributed-tracing-conventions.yml
  - We'll add new versions every once in a while and users will be able to configure them.
  - Don't change anything for the DiagnosticSource path

- [x] Cleanups and breaking changes
  - Propagate context using  `traceparent` in addition to `Diagnostic-Id` on AMQP SDKs 
  - https://github.com/Azure/azure-sdk-for-net/issues/31771
  - Enable nested scope suppression by default
  - http.status_code to int https://github.com/Azure/azure-sdk-for-net/issues/31438
  - investigate if "kind" and "otel.status_code" attributes  are needed on the ActivitySource path (use ActivityKind and Status enum if possible)
  - [x] https://github.com/Azure/azure-sdk-for-net/issues/33080

- [ ]  Testing
  - Retry tests: Activity per try and failed status
  - Perf testing: e.g. run storage perf tests with tracing enabled.
  - Update line-counter sample will latest and greatest OTel and AzMon exporter
  - [nice-to-have] Stress: e.g. enable tracing in stress tests

- [ ] Misc
  - Remove Experimental context switch

context: 
- https://github.com/microsoft/common-schema/pull/336/files
- https://gist.github.com/lmolkova/605bbf779d5599e8f01fd2c2e38f036e

**Comment by JoshLove-msft** [comment]
Current version is 1.17.0

**Comment by annelo-msft** [comment]
@lmolkova, is this work complete?  Can the issue be closed?

**Comment by lmolkova** [comment]
I don't think we completed all the individual work items listed in the description. Let's keep it open for now and I'll check what's remaining.

**Comment by lmolkova** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-for-net/issues/46018
