### ISSUE TITLE
[BUG] Azure.AI.Language.Conversations Sample code cannot compile

### ISSUE THREAD

**Issue by wangyuantao** [Azure/azure-sdk-for-net#31653]
### Library name and version

Azure.AI.Language.Conversations 1.0.0

### Describe the bug

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples/Sample6_AnalyzeConversation_ConversationSummarization.md

This sample code cannot compile

Suggestion: explicitly clarify lib version must be in prerelease 1.1.0-beta.1, the stable sdk version 1.0.0 cannot compile with sample code
```
    <PackageReference Include="Azure.AI.Language.Conversations" Version="1.1.0-beta.1" />
```

must check this:
![image](https://user-images.githubusercontent.com/98181/194651776-21bc98ab-9cd0-42ae-9aa4-1614021b4d07.png)

### Expected behavior

can compile and run

### Actual behavior

1>d:\TestSDK\Program.cs(71,89,71,106): error CS1503: Argument 1: cannot convert from 'Azure.WaitUntil' to 'Azure.Core.RequestContent'
1>d:\TestSDK\Program.cs(71,108,71,135): error CS1503: Argument 2: cannot convert from 'Azure.Core.RequestContent' to 'Azure.RequestContext'

### Reproduction Steps

follow the instruction copy the sample code to visual studio and build

### Environment

visual studio 17.3.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Thank you for the feedback; however, samples found in the main branch are always using the code currently in the main branch as well. All active development is in the main branch and may be out of sync with packages on nuget. Closing this in favor of #29327 which is tracking the general problem of docs, samples specifying untagged locations. /cc @scbedd @weshaggard
