### ISSUE TITLE
[BUG] ASP.net with Connected Services for Azure Storage gives a Header error.

### ISSUE THREAD

**Issue by ziron999o365** [Azure/azure-sdk-for-net#31663]
### Library name and version

Azure.Storage.Queues 12.11.1

### Describe the bug

I have been unable to get the QueueClient object to work on Restful API both locally and on an app service.

### Expected behavior

Expecting connected services setup for ASP.net to work upon starting initialization.

### Actual behavior

When running the ASP.net locally the error is:
RequestFailedException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:**
Time:2022-10-08T10:32:05.0353431Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed

Additional Information:
AuthenticationErrorDetail: Issuer validation failed. Issuer did not match.

When running on the App Service:
An unhandled exception occurred while processing the request.
ArgumentNullException: Value cannot be null. (Parameter 'connectionString')

### Reproduction Steps

The way it is being initialized:
builder.Services.AddAzureClients(clientBuilder =>
{
    clientBuilder.AddQueueServiceClient(builder.Configuration["SMSGet:queue"], preferMsi: true);
});

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error");
    // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
    app.UseHsts();
}

Then I just create a model that does this:
        public TestModel(ILogger<TestModel> logger, QueueServiceClient graphServiceClient)
        {
            _logger = logger;
            _graphServiceClient = graphServiceClient; ;
        }

        public async Task OnGet()
        {
            var queueClient = _graphServiceClient.GetQueueClient("queuenamehere");

### Environment

.net 6 both on app services and locally on windows 11 with visual studio 2022

**Comment by navba-MSFT** [comment]
@ziron999o365 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ziron999o365 Could you please confirm if you are using the local Storage emulator ? Or using Azure Storage ?
Also please check if you have the right connection string used ? Refer the .Net Sample code for queue operation [here](https://learn.microsoft.com/en-us/azure/storage/queues/storage-dotnet-how-to-use-queues?tabs=dotnet#get-your-storage-connection-string). Awaiting your reply.

**Comment by navba-MSFT** [comment]
@ziron999o365 I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.
