### ISSUE TITLE
[BUG] Spelling error in tracing logs

### ISSUE THREAD

**Issue by idotColinBlair** [Azure/azure-sdk-for-net#31679]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Describe the bug

https://github.com/Azure/azure-sdk-for-net/blob/8947cc941137289363569dbeef191cb0e7b911e4/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs#L119

Code is logging "enityPath" instead of "entityPath". e n i t y instead of e n t i t y

### Expected behavior

Should be outputting "entityType"

### Actual behavior

Is outputting "enityType"

### Reproduction Steps

Use a batched Service Bus Trigger and look at the logs.

**Comment by jsquire** [comment]
Hi @idotColinBlair.  Thank you for bringing this to our attention.   I've got #31689 out to fix this.
