### ISSUE TITLE
Deprecate Microsoft.OpenTelemetry.Exporter.AzureMonitor

### ISSUE THREAD

**Issue by benbhall** [Azure/azure-sdk-for-net#31674]
From a search, we can land on either of:

- https://learn.microsoft.com/en-us/dotnet/api/overview/azure/monitor.opentelemetry.exporter-readme-pre
- https://learn.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.opentelemetry.exporter.azuremonitor-readme-pre

They document installing _different_ NuGet packages for a OpenTelemetry exporter to Azure Monitor:

- `Microsoft.OpenTelemetry.Exporter.AzureMonitor`
- `Azure.Monitor.OpenTelemetry.Exporter`

It looks like `Microsoft.OpenTelemetry.Exporter.AzureMonitor` is no longer supported but this is not obvious.

We should:

- Deprecate the `Microsoft.OpenTelemetry.Exporter.AzureMonitor` NuGet package, pointing to `Azure.Monitor.OpenTelemetry.Exporter`
- Update the [documentation on MS Learn for the former](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.opentelemetry.exporter.azuremonitor-readme-pre)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3bad2986-d394-d855-d7c4-edc5bb2383e4
* Version Independent ID: 4230a46b-a708-0f69-d4ed-8e6600e7b712
* Content: [Azure Monitor Exporter client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.opentelemetry.exporter.azuremonitor-readme-pre)
* Content Source: [api/overview/azure/microsoft.opentelemetry.exporter.azuremonitor-readme-pre.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/microsoft.opentelemetry.exporter.azuremonitor-readme-pre.md)
* Service: ****
* Product: **azure**
* Technology: **azure**
* GitHub Login: @ramya-rao-a
* Microsoft Alias: **ramyar**

**Comment by SaurabhSharma-MSFT** [comment]
@benbhall Thanks for your feedback! We will investigate and update as appropriate.

**Comment by cijothomas** [comment]
https://www.nuget.org/packages/Microsoft.OpenTelemetry.Exporter.AzureMonitor/1.0.0-beta.1 this is already marked deprecated. Closing this issue.
