### ISSUE TITLE
Timeline for Microsoft.Azure.Management.Monitor to GA

### ISSUE THREAD

**Issue by shschwar** [Azure/azure-sdk-for-net#31704]
### Library name and version

Microsoft.Azure.Management.Monitor, 0.28.0-preview

### Query/Question

Hi
I like to use _Microsoft.Azure.Management.Monitor_ but it correctly in preview.
Is there any timeline for the GA version of this library?
In advanced, it seems that it's not sync with the latest version of the _Microsoft.Azure.Management.Monitor (preview) API_.

Thanks
Shay

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by shschwar** [comment]
Can anyone response?
Maybe @xboxeer?
Thanks

**Comment by xboxeer** [comment]
Hi @shschwar ,
Microsoft.Azure.Management.Monitor is our legacy Azure SDK and we won't provide none-security fix/update for it anymore, check our [deprecation announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/).  you can try our new version SDK [Azure.ResourceManager.Monitor](https://www.nuget.org/packages/Azure.ResourceManager.Monitor/) as a replacement

**Comment by shschwar** [comment]
Thanks @xboxeer 
I will use this one,

**Comment by Yao725** [comment]
I'm going to close this issue, feel free to reopen it or open a new one if you have more questions.

If you have any other feedback to our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF).

**Comment by shschwar** [comment]
Thank you
