### ISSUE TITLE
[Extensions] Clean up Microsoft.Azure.WebJobs.Extensions.Clients

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#31717]
This is currently a library directory, but we don't actually ship this as a library. It just contains shared source use by other extensions libraries. We can probably delete this directory and move under Microsoft.Extensions.Azure to avoid confusion.

**Comment by scottaddie** [comment]
@JoshLove-msft Does the `Microsoft.Azure.WebJobs.Extensions.AuthTokens` library fall into this same category?

**Comment by JoshLove-msft** [comment]
The AuthEvents library is shipped by the auth events team - [Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents/1.0.0-beta.1)

**Comment by scottaddie** [comment]
> I'm not familiar with this library. Can you provide a link?
There's an entry for it in the .NET CSV. When I go to the source repo, I cannot find it.

**Comment by JoshLove-msft** [comment]
My guess is the entry is incorrect and should be referring to the AuthenticationEvents library - t

**Comment by ronniegeraghty** [comment]
> My guess is the entry is incorrect and should be referring to the AuthenticationEvents library - https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/entra/Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents

Interesting. I'm pulling both `Microsoft.Azure.WebJobs.Extensions.AuthTokens` and `Microsoft.Azure.WebJobs.Extensions.AuthenticationEvents` from the release CSVs. I don't think `AuthTokens` should be on the list since it was never released publicly.

@weshaggard Do you know how a .NET package could get on the CSV if it's not on Nuget?

**Comment by scottaddie** [comment]
@ronniegeraghty See my linked PR ☝️ to remove the AuthTokens entry from the CSV.

**Comment by weshaggard** [comment]
The package was release but later unlisted see https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.AuthTokens.

**Comment by ronniegeraghty** [comment]
> The package was release but later unlisted see https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.AuthTokens.

Should we have some type of distinction in the CSV like "unlisted" when this happens?

**Comment by weshaggard** [comment]
I'm not sure there is a great way to detect that in our automation and even if there is I'm not sure it is worth annotating it. I would prefer we remove these from the csv.
