### ISSUE TITLE
Add live test support to Azure.Monitor.Ingestion with bicep file

### ISSUE THREAD

**Issue by nisha-bhatia** [Azure/azure-sdk-for-net#31730]
After this is completed we can separate out the monitor pipeline by SDK for live tests

**Comment by vishweshbankwar** [comment]
@nisha-bhatia - will this resolve https://github.com/Azure/azure-sdk-for-net/issues/31727?

**Comment by nisha-bhatia** [comment]
> 

Yes it should.

**Comment by vishweshbankwar** [comment]
> > 
> 
> Yes it should.

Would you be able to disable the ingestion live tests in the meantime since it fails the entire pipeline?

**Comment by nisha-bhatia** [comment]
The live test pipeline has been created
