### ISSUE TITLE
Add 'DeleteAfter' tag on all RG for test

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#31738]
Some live tests now involve mgmt. plane, unfortunately some mgmt. tests can't clean up all resources which caused resource leaks.
So the solution is adding a `DeleteAfter` tag on the test resource group, then the Engsys will [remove these resource group automatically](https://github.com/Azure/azure-sdk-tools/blob/main/doc/engsys_resource_management.md#full-resource-management-specification).

Here is the list of the prefix name for knowing resource groups existing in the live tests, we should fix the corresponding RPs first:

- MediaServiceRG
- EventGridRG
- testRG-
- AzureBackupRG_westus
- sdktest-

The steps should be:

- [x] Add the function to the test framework which enable add `DeleteAfter` tag when creating a new resource group (default is disabled which can avoid re-record all tests)
- [x] Enable `DeleteAfter` for MediaService
- [x] Enable `DeleteAfter` for EventGrid
- [ ] Enable `DeleteAfter` for RecoveryServicesBackup
- [ ] Enable `DeleteAfter` for other SDKs

**Comment by HarveyLink** [comment]
Closed as completed

**Comment by benbp** [comment]
Thank you so much @HarveyLink!
