### ISSUE TITLE
Wrong namespace in swagger dotnet track 2 SDK automation

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-sdk-for-net#31747]
This issue is found in test environment with this [PR](https://github.com/openapi-env-test/azure-rest-api-specs/pull/3589).

`marketplaceordering` has track2 SDK generated before in https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/marketplaceordering/Azure.ResourceManager.MarketplaceOrdering.

But in the SDK automation of the above PR, the generated namespace for `marketplaceordering` mgmt plane SDK become `Azure.ResourceManager.marketplaceordering` (see [PR](https://github.com/openapi-env-test/azure-sdk-for-net/pull/1255#discussion_r993069663)). Then it's treated as a new SDK with a new `autorest.md`. As it failed to use the existing `autorest.md` from `azure-sdk-for-net` repo, the generated SDK failed to build.

The automation pipeline should have a way to discover the correct namespace.

**Comment by chunyu3** [comment]
resolved.
