### ISSUE TITLE
Azure.ResourceManager.Media - creating media asset creates blob container, but doesn't set its name in the asset

### ISSUE THREAD

**Issue by Bellarmine-Head** [Azure/azure-sdk-for-net#31752]
### Library name and version

Azure.ResourceManager.Media 1.0.0

### Describe the bug

I create a new media asset resource using the description and storage account name of an existing one...

```csharp
                var assetData = new MediaAssetData
                {
                    // these are the only settable properties
                    AlternateId = null,         // not used
                    Description = mediaAssetResource.Data.Description,
                    Container = null,           // specified below, once we know the new asset's GUID-based id
                    StorageAccountName = mediaAssetResource.Data.StorageAccountName
                };

                // Create the new media asset (this also creates its blob container).
                ArmOperation<MediaAssetResource>? operation;
                try
                {
                    operation = await mediaServices.GetMediaAssets().CreateOrUpdateAsync(Azure.WaitUntil.Completed,
                        newMediaAssetName, assetData);
                }
                catch
                {
                    operation = null;
                }
```

I'm not setting the `Container` name in the `MediaAssetData` because the name used will be based on the assigned asset id.

The `GetMediaAssets().CreateOrUpdateAsync` method will assign the GUID-based asset id, and create the blob container based on that id (which is understandable, but slightly unexpected since the SourceLink documentation doesn't mention anything about creating this container).

So after the above code runs, the blob container is created, but the returned media asset resource's `MediaAssetData` object still has a `null` container name.

So I've had to update this manually...

```csharp
                /* Update the new media asset with its blob container name */

                // Set the media asset resource's container name.
                // e.g. "asset-baa266b0-3363-4317-9114-a35b0e84108a"
                // although creating the media asset has created the underlying blob container(!!) it seems that we have to
                // update the media asset resource with the container name
                var newContainerName = $"asset-{newMediaAssetResource.Data.AssetId}";
                assetData.Container = newContainerName;
                Azure.Response<MediaAssetResource>? response;
                try
                {
                    response = await newMediaAssetResource.UpdateAsync(assetData);
                }
                catch
                {
                    response = null;
                }
```

Should not the call to create the media asset (which creates the blob container) fill in the container name?

### Expected behavior

The call to create the media asset (which creates the blob container) fills in the container name without the caller having to do this step manually.

### Actual behavior

The call to create the media asset (which creates the blob container) doesn't fill in the container name.

### Reproduction Steps

See code above

### Environment

Visual Studio 2022 17.3.6
.NET 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Sanjidhalim** [comment]
Thanks for identifying this issue! This is a server-side bug. We will fix it soon and provide an update here.

**Comment by HarveyLink** [comment]
Hi @Bellarmine-Head , Thank you for using Azure SDK for .NET.
This issue has been fixed on the service side. You could retry it.
