### ISSUE TITLE
How to clone media asset + blobs and give it a new streaming locator using Azure.ResourceManager.Media?

### ISSUE THREAD

**Issue by Bellarmine-Head** [Azure/azure-sdk-for-net#31750]
### Library name and version

Azure.ResourceManager.Media 1.0.0

### Query/Question

Using the new `Azure.ResourceManager.Media` package I can do these hops quite nicely (for reading):-

> streaming locator id -> streaming locator -> media asset -> storage container uri -> blobs

This is for a video.

What I have now been tasked to do is *clone* the media asset and its blobs, and give it a new streaming locator id.  (The blobs representing VTT subtitles files will then probably get updated with new content.  The original media asset and its blobs must never be modified.)

Is such a cloning possible?  wise?  supported?

If yes, is there documentation to show how to do this?

### Environment

Visual Studio 17.3.6
.NET 6
Hosting: Azure

**Comment by Bellarmine-Head** [comment]
It may be a simple job of:-

* create empty media asset
* copy the blobs over
* create a new streaming locator for the media asset

but I'd like to know if there's an gotchas to be aware of, existing sample code that does it, etc.

Thanks.

**Comment by Bellarmine-Head** [comment]
Yes, it *is* just a case of:-

* create empty media asset resource
* copy the blobs over to its associated blob container
* create a new streaming locator for the media asset resource

Our tests indicate that it works fine.  The original MP4 (not present in the blob container) wasn't required at all.


1) Start...

```csharp
var armClient = new ArmClient(new DefaultAzureCredential());
var resourceId = MediaServicesAccountResource.CreateResourceIdentifier(SubscriptionId, ResourceGroup, AccountName);
var mediaServices = armClient.GetMediaServicesAccountResource(resourceId);
```

2) Obtain a reference to media asset resource you are going to clone, from the asset name....

```csharp
await mediaServices.GetMediaAssetAsync(assetName);
```

3) Get read access to its blob container...

```csharp
// Get a list of storage container URLs with shared access signatures (SAS) for reading.
var sasContentRequest = new MediaAssetStorageContainerSasContent
{
    Permissions = MediaAssetContainerPermission.Read,
    ExpireOn = DateTime.UtcNow.AddMinutes(10.0)
};
var assetContainerSasUris = mediaAssetResource.GetStorageContainerUris(sasContentRequest);

// Extract the first storage container URI (there seem to be usually two for some reason).
var assetContainerSasUri = assetContainerSasUris.FirstOrDefault();
if (assetContainerSasUri == null)
    return;

var blobContainerClient = new BlobContainerClient(assetContainerSasUri);
```

4) Get the name for the cloned media asset resource from the existing resource, and modify it for uniqueness...

```csharp
var newMediaAssetName = mediaAssetResource.Data.Name;
// now modify for uniqueness; e.g. remove existing guid or datetime and append new one
```

5) Create the new media asset resource (the clone)...

```csharp
var assetData = new MediaAssetData
{
    // these are the only settable properties
    AlternateId = null,         // don't know what this is
    Description = mediaAssetResource.Data.Description,
    Container = null,           // specified below, once we know the new asset's GUID-based id
    StorageAccountName = mediaAssetResource.Data.StorageAccountName
};

// Create the new media asset (this also creates its blob container).
ArmOperation<MediaAssetResource>? operation;
try
{
    operation = await mediaServices.GetMediaAssets().CreateOrUpdateAsync(Azure.WaitUntil.Completed,
        newMediaAssetName, assetData);
}
catch
{
    // blah
}
```

6) Gotcha number 1... the current version of the package doesn't seem to set the container name, so we do it...

```csharp
var newContainerName = $"asset-{newMediaAssetResource.Data.AssetId}";
assetData.Container = newContainerName;
Azure.Response<MediaAssetResource>? response;
try
{
    response = await newMediaAssetResource.UpdateAsync(assetData);
}
catch
{
    // blah
}
```

7) As per step 3 above, get access to the new media asset resource's underlying blob container (this time with `ReadWrite` access)

8) Copy blobs from source to target; https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-copy?tabs=dotnet is a good reference.  I filtered out deleted blobs.  Plus I didn't bother with the `lease` stuff because our blobs are strictly readonly.

9) Create a new streaming locator for the new media asset resource (afterwards extract its streaming locator id if you need it)...

```csharp
ArmOperation<StreamingLocatorResource>? operationSlr;
try
{
    var newStreamingLocatorData = new StreamingLocatorData
    {
        AssetName = newMediaAssetName,   // must be specified
        StreamingPolicyName = sld.StreamingPolicyName  // must be specified; copied over from original streaming locator
    };
    var newStreamingLocatorName = newMediaAssetName;
    operationSlr = await streamingLocators.CreateOrUpdateAsync(Azure.WaitUntil.Completed, newStreamingLocatorName,
        newStreamingLocatorData);
}
catch
{
    // blah
}
```

**Comment by Yao725** [comment]
Sorry for the slow response and I am glad to see that you have solved the problem by yourself.

If you have any other feedback to our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF).
