### ISSUE TITLE
Improve test coverage for LROs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#31760]
Long-running operations are varied and complicated, and in recent discussions e.g., Azure/autorest.csharp#2728, we can get blocked on making changes to unblock other releases due to lack of coverage.

We know data plane LROs are varied and often don't implement even old standards correctly (see current standards [here](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#long-running-operations--jobs)), but management plane LROs may be more varied that expected as well.

I recommend that we improve DP LROs for all assemblies. Since MP is mostly/all generated, we should make sure that all variations are covered across the assemblies, if not be able to generate them such that all variations across all assemblies are covered.

To note, LRO test coverage should test all terminal cases e.g., `Failed`, `Succeeded`, and `Canceled` (even these state values vary by case or even values e.g., older Cognitive LROs may use `completedSuccessfully` instead of `Succeeded`), and should assert intermediate states like `NotStarted` and `Running`. This may mean, in some cases, LROs have to use mocks since getting one to fail or cancel in time before succeeding may be difficult. See https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/textanalytics/Azure.AI.TextAnalytics/tests/MockTests/OperationsMockTests.cs for some examples.

**Comment by pallavit** [comment]
@heaths can you please help me understand this a bit more. 

Are you suggesting we should test all the different states of LRO in data plane SDKs for each LRO operation? The autorest issue linked was potentially an interim bug which has now been fixed?

**Comment by heaths** [comment]
In https://github.com/Azure/autorest.csharp/pull/2728 we had a long discussion - and an even longer thread/investigation offline with @johanste et. al. - about the varied ways LROs are implemented. There's a lot of context in there I didn't want to repeat, but to summarize: yes, I think we should at least test all the various ways LROs are used centrally, such that each and every library doesn't have to keep testing the same things over and over. Some LROs e.g., certificate merging in KV, require manual effort or can take a very long time to run - longer than we might want live tests running.
