### ISSUE TITLE
Consider supporting AZURE_CLIENT_CERTIFICATE_PASSWORD config in Extensions

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#31763]
@christothes 
> Looks good - Do you think we should also update the readme examples to mention this new environment variable and possibly the troubleshooting doc also? Needs a changelog entry too.

Updated.

@JoshLove-msft 
> Should we consider exposing this in Extensions?

Possibly if it's only settable through string configuration. Notice we only updated the `EnvironmentCredential` to support taking a password, not the `ClientCertififcateCredential` where they can pass an `X509Certificate2` instance and hence can handle any password protection themselves.

_Originally posted by @schaabs in https://github.com/Azure/azure-sdk-for-net/issues/31472#issuecomment-1260046400_

**Comment by jsquire** [comment]
It is possible to configure `ClientCertififcateCredential ` directly when registering clients.   For example:
```csharp
builder.Services.AddAzureClients(clientBuilder =>
{
    // Add a KeyVault client
    clientBuilder.AddSecretClient(builder.Configuration.GetSection("KeyVault"));

    // Use ClientCertificateCredentail with custom options
    var certificate = new X509Certificate2("./certs/cert-password-protected.pfx", "password");
    clientBuilder.UseCredential(new ClientCertificateCredential("<< TENANT >>", "<< CLIENT >>", certificate));

    // Set up any default settings
    clientBuilder.ConfigureDefaults(builder.Configuration.GetSection("AzureDefaults"));
});

builder.Services.AddControllers();
```
More information can be found in [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection).

Closing this out.
