### ISSUE TITLE
[FEATURE REQ] ServiceBus and EventHubs processing: use parent instead of link when possible

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#31771]
### Library name

Azure.Messaging.ServiceBus, Azure.Messaging.EventHubs

### Please describe the feature.

When we trace EH/SB.Process call, we create a link in all cases, even when one message is received. We receive feedback indicating that links are confusing, e.g.
https://github.com/Azure/azure-functions-dotnet-worker/issues/1089 and through support channels.

The suggestion here is that if we process one message/event, we should use the incoming message context as a parent for the new span rather than a link. With this, the producer and consumer will have one trace-id - it's supported by all tracing backends and easy to query.

This is not breaking as all tracing backends should support parent-child relationships.

**Comment by JoshLove-msft** [comment]
Here is the current structure for Service Bus:
```
Receiver.Receive --Link to Message
|
Processor.Process --Link to Message
```
@lmolkova are you saying it should be 
```
Message
|
Receiver.Receive
|
Processor.Process
```

**Comment by lmolkova** [comment]
I think today it's:
Trace0: Message
Trace1: Receiver.Receive --Link to Message
Trace2: Receiver.Process --Link to Message

But should rather be

Trace0: Message
Trace1: Receiver.Receive -- Link to Message
Trace0: Receiver.Process, child of Message


(for single message case)
