### ISSUE TITLE
[BUG] Cannot log in to Dogfood tenants with `ClientCertificateCredential`

### ISSUE THREAD

**Issue by shenglol** [Azure/azure-sdk-for-net#31777]
### Library name and version

Azure.Identity 1.7.0

### Describe the bug

I was trying to connect to the Dogfood cloud with `ClientCertificateCredential`, but I got the following error when acquiring authentication token:

```
Microsoft.Identity.Client.MsalServiceException : AADSTS700016: Application with identifier '<REDACTED>' was not found in the directory 'Microsoft Services'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
```

### Expected behavior

The authentication should succeed.

### Actual behavior

The authentication failed.

### Reproduction Steps

The following code can be used to reproduce the error:

```C#
var certificate = GetCertificate();
var options= new  ClientCertificateCredentialOptions
{
    AuthorityHost = new Uri("https://login.windows-ppe.net/organizations/"),
    SendCertificateChain = true,
};

var credential = ClientCertificateCredential("<TENAND_ID>", "<CLIENT_ID>", options);
var environment = new AzureEnvironment("https://api-dogfood.resources.windows-int.net", "https://management.core.windows.net/");
var armClient = new ArmClient(credential, "<SUBSCRIPTION_ID>", environment);

var subscription = await armClient.GetDefaultSubscriptionAsync(); // AADSTS700016
```

Looking at [MsalConfidentialClient](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/MsalConfidentialClient.cs), there is no call to `ConfidentialClientApplicationBuilder.WithTenantId()`, which seems to be the root cause.

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by schaabs** [comment]
@shenglol I think the issue might be that you're including the `organizations` path on the authority host. I believe the `AuthorityHost` should be only contain the host:

```c#
var options= new  ClientCertificateCredentialOptions
{
    AuthorityHost = new Uri("https://login.windows-ppe.net/"),
    SendCertificateChain = true,
};
```

Could you give that a try?

**Comment by shenglol** [comment]
@schaabs That worked. Thanks for pointing that out! I missed the fact that it should only contain the host.

Closing the issue.
