### ISSUE TITLE
[BUG] SearchIndexerClient class's GetSkillsets return "Invalid URI: The URI is empty." if the entitiesDefinitionUri is null in CustomEntityLookupSkill 

### ISSUE THREAD

**Issue by yuhaii** [Azure/azure-sdk-for-net#31781]
### Library name and version

Azure.Search.Documents 11.4.0

### Describe the bug

SearchIndexerClient class's GetSkillsets return "Invalid URI: The URI is empty." if the entitiesDefinitionUri is null in CustomEntityLookupSkill .

Below is the exception and call stack:
"System.UriFormatException: Invalid URI: The URI is empty.\r\n   
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)\r\n   
at System.Uri..ctor(String uriString)\r\n   
at Azure.Search.Documents.Indexes.Models.CustomEntityLookupSkill.DeserializeCustomEntityLookupSkill(JsonElement element)\r\n   
at Azure.Search.Documents.Indexes.Models.SearchIndexerSkill.DeserializeSearchIndexerSkill(JsonElement element)\r\n   
at Azure.Search.Documents.Indexes.Models.SearchIndexerSkillset.DeserializeSearchIndexerSkillset(JsonElement element)\r\n   
at Azure.Search.Documents.Indexes.Models.ListSkillsetsResult.DeserializeListSkillsetsResult(JsonElement element)\r\n   
at Azure.Search.Documents.SkillsetsRestClient.List(String select, CancellationToken cancellationToken)\r\n   
at Azure.Search.Documents.Indexes.SearchIndexerClient.GetSkillsets(CancellationToken cancellationToken)\r\n   
at AzSearchLab.Models.SearchIndexModel.GetSkillSet(String searchName, String apiKey) in D:\\yuehai\\AzSearchLab\\AzSearchLabSrc\\AzSearchLab\\Models\\SearchIndexModel.cs:line 50"

From call stack and source code. I can see it is because the entitiesDefinitionUri is empty in skill definition. 
https://github.com/Azure/azure-sdk-for-net/blob/Azure.Search.Documents_11.4.0/sdk/search/Azure.Search.Documents/src/Generated/Models/CustomEntityLookupSkill.Serialization.cs#L164 

### Expected behavior

It should not raise exception if the entitiesDefinitionUri is null in CustomEntityLookupSkill. Becasue the inlineEntitiesDefinition is not null. 

And according to our document below, The parameter inlineEntitiesDefinition supersedes the entitiesDefinitionUri parameter if present.
https://learn.microsoft.com/en-us/azure/search/cognitive-search-skill-custom-entity-lookup#skill-parameters.

### Actual behavior

It raise exception if the entitiesDefinitionUri is null in CustomEntityLookupSkill.  

### Reproduction Steps

1. Add below skill in skill set 

{
      "@odata.type": "#Microsoft.Skills.Text.CustomEntityLookupSkill",
      "name": "#7",
      "description": "extract custom entities",
      "context": "/document/merged_content",
      "defaultLanguageCode": "en",
      "entitiesDefinitionUri": "",
      "globalDefaultCaseSensitive": true,
      "globalDefaultAccentSensitive": true,
      "globalDefaultFuzzyEditDistance": 0,
      "inputs": [
        {
          "name": "text",
          "source": "/document/merged_content"
        }
      ],
      "outputs": [
        {
          "name": "entities",
          "targetName": "features"
        }
      ],
      "inlineEntitiesDefinition": [
        {
          "name": "city",
          "description": null,
          "type": null,
          "subtype": null,
          "id": null,
          "caseSensitive": false,
          "accentSensitive": null,
          "fuzzyEditDistance": null,
          "defaultCaseSensitive": false,
          "defaultAccentSensitive": null,
          "defaultFuzzyEditDistance": null,
          "aliases": []
        },
        {
          "name": "breakfast",
          "description": null,
          "type": null,
          "subtype": null,
          "id": null,
          "caseSensitive": false,
          "accentSensitive": null,
          "fuzzyEditDistance": null,
          "defaultCaseSensitive": false,
          "defaultAccentSensitive": null,
          "defaultFuzzyEditDistance": null,
          "aliases": []
        },
        {
          "name": "restaurant",
          "description": null,
          "type": null,
          "subtype": null,
          "id": null,
          "caseSensitive": false,
          "accentSensitive": null,
          "fuzzyEditDistance": null,
          "defaultCaseSensitive": false,
          "defaultAccentSensitive": null,
          "defaultFuzzyEditDistance": null,
          "aliases": []
        },
        {
          "name": "clean",
          "description": null,
          "type": null,
          "subtype": null,
          "id": null,
          "caseSensitive": false,
          "accentSensitive": null,
          "fuzzyEditDistance": null,
          "defaultCaseSensitive": false,
          "defaultAccentSensitive": null,
          "defaultFuzzyEditDistance": null,
          "aliases": []
        },
        {
          "name": "free parking",
          "description": null,
          "type": null,
          "subtype": null,
          "id": null,
          "caseSensitive": false,
          "accentSensitive": null,
          "fuzzyEditDistance": null,
          "defaultCaseSensitive": false,
          "defaultAccentSensitive": null,
          "defaultFuzzyEditDistance": null,
          "aliases": []
        },
        {
          "name": "budget",
          "description": null,
          "type": null,
          "subtype": null,
          "id": null,
          "caseSensitive": false,
          "accentSensitive": null,
          "fuzzyEditDistance": null,
          "defaultCaseSensitive": false,
          "defaultAccentSensitive": null,
          "defaultFuzzyEditDistance": null,
          "aliases": []
        },
        {
          "name": "luxury",
          "description": null,
          "type": null,
          "subtype": null,
          "id": null,
          "caseSensitive": false,
          "accentSensitive": null,
          "fuzzyEditDistance": null,
          "defaultCaseSensitive": false,
          "defaultAccentSensitive": null,
          "defaultFuzzyEditDistance": null,
          "aliases": []
        }
      ]
    },

2. Run below code. it will raise exception {"Invalid URI: The URI is empty."}

            string searchServiceUri = "https://" + searchName + ".search.windows.net";
            var indexerClient = new SearchIndexerClient(new Uri(searchServiceUri), new AzureKeyCredential(apiKey));

            List<string> apiSkills = new List<string>();
            try
            {
                var skillsetstest = indexerClient.GetSkillsets();
            }
            catch (Exception e)
            {
                var exceptionMsg = e.ToString();
                var msgEx = e.Message;
                var innerEx = e.InnerException;
            }

### Environment

Azure.Search.Documents 11.4.0

**Comment by yuhaii** [comment]
From source code : https://github.com/Azure/azure-sdk-for-net/blob/Azure.Search.Documents_11.4.0/sdk/search/Azure.Search.Documents/src/Generated/Models/CustomEntityLookupSkill.Serialization.cs#L159

We can see it dose not check whether the entitiesDefinitionUri value is "", it only check whether it is null. It caused such exception. Please fix this issue.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yuhaii** [comment]
Hello @ShivangiReja , if you check the document https://learn.microsoft.com/en-us/azure/search/cognitive-search-skill-custom-entity-lookup#skill-parameters . There are two parameter in this skill entitiesDefinitionUri and inlineEntitiesDefinition. The document indicates that if the inlineEntitiesDefinition is NOT empty, the entitiesDefinitionUri  can be "" or null.  

![image](https://user-images.githubusercontent.com/39817657/195730171-ca10ac52-6e10-48b1-81be-48bd6e452a92.png)

And your SDK code also checked whether it is null, but it didn't check whether it is "". 

![image](https://user-images.githubusercontent.com/39817657/195730276-670a2579-9007-4d5c-bc60-2cd42a76928d.png)

So please change code from "if (property.Value.ValueKind == JsonValueKind.Null)" to "if (property.Value.ValueKind == JsonValueKind.Null **|| property.Value.ValueKind == ""** )" to mitigate the issue. 
https://github.com/Azure/azure-sdk-for-net/blob/Azure.Search.Documents_11.4.0/sdk/search/Azure.Search.Documents/src/Generated/Models/CustomEntityLookupSkill.Serialization.cs#L159

**Comment by ShivangiReja** [comment]
Hi @yuhaii, IMO [documentation](https://learn.microsoft.com/en-us/azure/search/cognitive-search-skill-custom-entity-lookup#skill-parameters) doesn't mention anywhere that `entitiesDefinitionUri` can be empty. It says that if `inlineEntitiesDefinition` is present, then it supersedes the `entitiesDefinitionUri` parameter.


---
<html>
<body>


Parameter name | Description
-- | --
entitiesDefinitionUri | Path to an external JSON or CSV file containing all the target text to match against. This entity definition is read at the beginning of an indexer run; any updates to this file mid-run won't be realized until subsequent runs. This file must be accessible over HTTPS. See Custom Entity Definition Format below for expected CSV or JSON schema.
inlineEntitiesDefinition | Inline JSON entity definitions. This parameter supersedes the entitiesDefinitionUri parameter if present. No more than 10 KB of configuration may be provided inline. See Custom Entity Definition below for expected JSON schema.


</body>
</html>

---
@dereklegenzoff and @gregoks -- Could you please clarify that `entitiesDefinitionUri` can be empty or not? In SDK, we have only null check for `entitiesDefinitionUri` as mentioned in the swagger definition [here](https://github.com/Azure/azure-rest-api-specs/blob/904899a23a417768ce1ec1d5f89f33817f8ef8ad/specification/search/data-plane/Azure.Search/preview/2021-04-30-Preview/searchservice.json#L8729).


@yuhaii for your reference, @dereklegenzoff and @gregoks work on Search service.

**Comment by gmndrg** [comment]
I will double check and confirm. Thanks!

**Comment by gmndrg** [comment]
Hello @ShivangiReja you're right. As per https://learn.microsoft.com/en-us/azure/search/cognitive-search-skill-custom-entity-lookup#skill-parameters, `entitiesDefinitionUri `is not an optional parameter. Parameters that are optional have "(Optional)" in the description accordingly. 
@yuhaii You need to make sure that this parameter always has a value for either JSON or CSV file path. Thanks a lot for looking into this.

**Comment by gmndrg** [comment]
#please-close

**Comment by ShivangiReja** [comment]
Thank you @gmainar for the confirmation!
