### ISSUE TITLE
USP error: timeout waiting for the first audio chunk

### ISSUE THREAD

**Issue by daimig** [Azure/azure-sdk-for-net#31786]
[Enter feedback here]

CANCELED: Reason=Error
CANCELED: ErrorCode=ServiceTimeout
CANCELED: ErrorDetails=[USP error: timeout waiting for the first audio chunk]

¿what does this error mean ? , I am consuming the api from c#, CognitiveServices.Speech. previously everything was fine from one moment to another that error came out.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 52987a51-b478-a25d-fb5c-ff9b82d937be
* Version Independent ID: 1e641ee3-40e0-82ff-603c-4fca6f2552de
* Content: [CancellationDetails.Reason Property (Microsoft.CognitiveServices.Speech) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.cancellationdetails.reason?view=azure-dotnet)
* Content Source: [xml/Microsoft.CognitiveServices.Speech/CancellationDetails.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.CognitiveServices.Speech/CancellationDetails.xml)
* Service: **cognitive-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by francescoStrada** [comment]
Same problem here, refer to this thread for further details https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1692

**Comment by navba-MSFT** [comment]
@daimig  Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Our Service team is aware of this issue and multiple issues have been reported for the same. I am sharing the current update on this:

- This is a known issue on Windows 10 and Windows 11 stemming from the latest Tuesday patches this week
- Windows is aware of and actively working on the problem, though no ETA Is yet available
- Rolling back KB5018427/KB5018418 or forcing TLS 1.2 in a client's OS settings may work around the issue

Similar issue is reported [here](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1692), [here](https://learn.microsoft.com/en-us/answers/questions/1046682/text-to-speech-usp-error-timeout-waiting-for-the-f.html) and [here](https://learn.microsoft.com/en-us/answers/questions/1047034/text-to-speech-usp-error-timeout-waiting-for-the-f-1.html).

**Comment by navba-MSFT** [comment]
@daimig Please refer [this comment ](https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1692#issuecomment-1282899176)for the resolution. Please test it and let us know. Awaiting your reply.

**Comment by HEXtoDEC** [comment]
how to fix on windows10? i cant install KB5020436

**Comment by HEXtoDEC** [comment]
> how to fix on windows10? i cant install KB5020436

Never mind, I used the RESTFULLAPI solution to solve the problem.
