### ISSUE TITLE
[FEATURE REQ] Azure.ResourceManager.ApiManagement API resources should support exporting OpenApi or GraphQL files

### ISSUE THREAD

**Issue by colincmac** [Azure/azure-sdk-for-net#31798]
### Library name

Azure.ResourceManager.ApiManagement

### Please describe the feature.

Both the REST API (https://learn.microsoft.com/en-us/rest/api/apimanagement/current-preview/api-export/get?tabs=HTTP#exportformat) 
and the previous `Microsoft.Azure.Management.ApiManagement` library
(https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/apimanagement/Microsoft.Azure.Management.ApiManagement/src/Generated/ApiExportOperations.cs) 
support exporting an API as an OpenApi specification file.

I cannot find a way to do this through the `Azure.ResourceManager.ApiManagement` library. 
A more general fix would be allowing any `Azure.ResourceManager` sdk resource to append custom query parameters to the `Get` operations.

**Comment by colincmac** [comment]
This came about internally investigating whether we could utilize the [ApiOps](https://github.com/Azure/apiops) libraries as a future [Bicep extensibility provider](https://github.com/Azure/bicep-extensibility)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by colincmac** [comment]
We can talk internally if needed as well @jsquire

**Comment by xboxeer** [comment]
> We can talk internally if needed as well @jsquire Jesse Squire FTE

Agree, I think we should have a conversation internally and get to know more details about this.

**Comment by colincmac** [comment]
Updated the title to include GraphQL exports. However, this could be out of scope. 
Currently GraphQL api's don't seem to have any Operation Resources, but use a [Schema Resource](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Generated/ApiSchemaResource.cs) to provide both object and request operations.

Fortunately, it seems that we can use this for GraphQL schemas since it's a string property on the SchemaResource. Open API based Schema Resources only save the definitions of the object's (request & response types), but not the full Open API spec for the resource, unlike the GraphQL Schema resource.

I noticed that the REST API for exporting API files and the associated legacy sdk class [ApiExport](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/apimanagement/Microsoft.Azure.Management.ApiManagement/src/Generated/ApiExportOperations.cs)   doesn't support GraphQL

**Comment by xboxeer** [comment]
There is an issue seems related to this one https://github.com/Azure/autorest/issues/4652, @ArthurMa1978  can you help assign someone to check?  I don't see an export method in our SDK for APIM Library

**Comment by dldldlepl** [comment]
This is a feature, which was available in the deprecated library `Microsoft.Azure.Management.ApiManagement`. With the old library I was able to get the OpenApi with the following code, by setting the Accept header:

```C#
var openApiResponse = await this.apiManagementClient.Api.GetWithHttpMessagesAsync(
    resourceGroup, serviceName, apiId,
    new Dictionary<string, List<string>>
    {
        ["Accept"] = new() { "application/vnd.oai.openapi+json" }
    }, cancellationToken);
var openApi = await openApiResponse.Response.Content.ReadAsStringAsync(cancellationToken);
```

**Comment by live1206** [comment]
@colincmac 
I had a look at the generation logic and found that the swagger is not as the generator expected. 
There are 2 issues in [ApiExport_Get](https://github.com/Azure/azure-rest-api-specs/blob/0724e72994ed3c77f76ed0bfa2df3b1f0c33a41b/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L4413):
- The generator expects only 1 get method from `ApiResource`, [Api_Get](https://github.com/Azure/azure-rest-api-specs/blob/0724e72994ed3c77f76ed0bfa2df3b1f0c33a41b/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L160) already exist. So, `ApiExport_Get` will be ignored. `get` method needs to be changed to `head`.
- The [request path](https://github.com/Azure/azure-rest-api-specs/blob/0724e72994ed3c77f76ed0bfa2df3b1f0c33a41b/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L4412C5-L4412C154) is conflicting with [Api_GetEntityTag](https://github.com/Azure/azure-rest-api-specs/blob/0724e72994ed3c77f76ed0bfa2df3b1f0c33a41b/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L113), please notice that query will be ignored from the request path.

Not sure why Track 1 SDK generated it though, maybe it was not strict as Track 2, which seems more correct. Please share your thoughts with us.

**Comment by colincmac** [comment]
> @colincmac 
> I had a look at the generation logic and found that the swagger is not as the generator expected. 
> There are 2 issues in [ApiExport_Get](https://github.com/Azure/azure-rest-api-specs/blob/0724e72994ed3c77f76ed0bfa2df3b1f0c33a41b/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L4413):
> - The generator expects only 1 get method from `ApiResource`, [Api_Get](https://github.com/Azure/azure-rest-api-specs/blob/0724e72994ed3c77f76ed0bfa2df3b1f0c33a41b/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L160) already exist. So, `ApiExport_Get` will be ignored. `get` method needs to be changed to `head`.
> - The [request path](https://github.com/Azure/azure-rest-api-specs/blob/0724e72994ed3c77f76ed0bfa2df3b1f0c33a41b/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L4412C5-L4412C154) is conflicting with [Api_GetEntityTag](https://github.com/Azure/azure-rest-api-specs/blob/0724e72994ed3c77f76ed0bfa2df3b1f0c33a41b/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimapis.json#L113), please notice that query will be ignored from the request path.
> 
> Not sure why Track 1 SDK generated it though, maybe it was not strict as Track 2, which seems more correct. Please share your thoughts with us.

I'll have to reacquaint myself with this issue. I'm not sure what specific thoughts you're interested in. The ability to do an API export via interesting as code, would remove the need for custom code solutions like API Ops. So I'd say exposing it in ARM/Bicep has a lot of benefits.

**Comment by colincmac** [comment]
@live1206 Sorry, I see now. Give me a bit to review, but you're insights seem correct.

**Comment by live1206** [comment]
Close this issue since this requires service team to update the swagger for `ApiExport_Get` properly.
@colincmac Please feel free to reopen it if you come up with other thoughts.
