### ISSUE TITLE
[BUG] Test Framework ResponseNullFilterPolicy incorrectly doing a regex replace when filtering null values

### ISSUE THREAD

**Issue by pahnallan** [Azure/azure-sdk-for-net#31806]
### Library name and version

Azure.ResourceManager.TestFramework 

### Describe the bug

The [ResponseNullFilterPolicy](https://github.com/Azure/azure-sdk-for-net/blob/923810b60b9923ab41b2cf83fb458b3cf818ec33/common/ManagementTestShared/Redesign/ResponseNullFilterPolicy.cs#L24) class in the TestShared folder is incorrectly filtering null values if they're already escaped. The regex is getting partially applied to the contents of the response and breaking the format, thus making the entire content of the response unparsable. 

### Expected behavior

Below is a snippet of a string that has been escaped twice due to being serialized previously:

`"\\\"configurationVersion\\\":\\\"1\\\",\\\"id\\\":null,\\\"type\\\":\\\"Microsoft.StorageSync/storageSyncServices/HybridMonitoringConfiguration\\\""`

I am expecting the regular expression [located here](https://github.com/Azure/azure-sdk-for-net/blob/923810b60b9923ab41b2cf83fb458b3cf818ec33/common/ManagementTestShared/Redesign/ResponseNullFilterPolicy.cs#L24) to filter the \\\\\\"id\\\\\\":null and produce the results below

`"\\\"configurationVersion\\\":\\\"1\\\",\\\"type\\\":\\\"Microsoft.StorageSync/storageSyncServices/HybridMonitoringConfiguration\\\""`

### Actual behavior

Below is the actual result when filtering the  \\\\\\"id\\\\\\":null

`\\\"configurationVersion\\\":\\\"1\\\",\\\\\"type\\\":\\\"Microsoft.StorageSync/storageSyncServices/HybridMonitoringConfiguration\\\`

There are 5 backslashes prefixing type when it should be 3. I believe the additional 2 were leftover due to the regular expression not fully capturing the nested escaped characters.

### Reproduction Steps

The following code demonstrates how the current regular expression doesn't account for null key/value pairs that are part of a serialized json which has an additional layer of escaped characters. 

`        var content = "\\\"id\\\":null";
        var fiteredContent = Regex.Replace(content, "(,?)\\s*\\\"[^\\\"]*\\\":null,?|,(})", "$1$2")
        Console.WriteLine(fiteredContent);
`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
@pahnallan Thank you for the feedback.
I have a questions here for the fix: Is there possible for the service to return muliple times escaped backslash?
If so, I'd like to apply:
`Regex.Replace(jsonString, "(,?)\\s*\\\\+\"[^\\\\+\"]*\\\\+\":null,?|,(})", "$1$2");`
to handle any number of backslash

**Comment by pahnallan** [comment]
@HarveyLink 

Yep it's possible that the service could return escaped backslashes multiple times. Thanks for taking a look.

**Comment by HarveyLink** [comment]
Fixed
