### ISSUE TITLE
[QUERY] Client Mocking for Azure.ResourceManager.Monitor

### ISSUE THREAD

**Issue by eltonchan0128** [Azure/azure-sdk-for-net#31805]
### Library name and version

Azure.ResourceManager 1.0.0

### Query/Question

I've been writing unit tests for the Azure.ResourceManager armClient where I've been trying to mock the GetAutoscaleSettingAsync() function. The function is an extension method that leads eventually calls a static method. Will this function be mockable in the future?

Thanks

### Environment

Azure.ResourceManager Version=1.0.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
Hi @eltonchan0128 we are internally having a design session to support mock in SDK 
If you have any other feedback regarding Azure SDK For .NET, kindly let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF).

**Comment by Yao725** [comment]
These kinds of methods will be mockable and we already have planned to implement this feature.

**Comment by ArthurMa1978** [comment]
Relate to the feature https://github.com/Azure/autorest.csharp/issues/1900

**Comment by ArthurMa1978** [comment]
Close as dup
