### ISSUE TITLE
[FormRecognizer] CopyModelWithLabelsAndModelName failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#31813]
FormRecognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Could not retrieve authorization metadata. If this issue persists use a different target model to copy into.
> Status: 200 (OK)
> ErrorCode: 2024
> 
> Additional Information:
> error-0: 2024: Could not retrieve authorization metadata. If this issue persists use a different target model to copy into.
> 
> Content:
> 
> Headers:
> ms-azure-ai-errorcode: REDACTED
> x-envoy-upstream-service-time: 22
> apim-request-id: 1a027a10-963d-425b-817f-ca27afb89ddc
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> x-content-type-options: nosniff
> Content-Length: 399
> Content-Type: application/json; charset=utf-8
> Date: Fri, 14 Oct 2022 04:35:29 GMT
> 
> Data:
> error-0: 2024: Could not retrieve authorization metadata. If this issue persists use a different target model to copy into.
> 
> 
> Stack trace
>    at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 290
>    at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 278
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternalBase.<UpdateStatusAsync>d__13.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 87
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 79
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 212
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__19.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 242
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__15.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 177
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.AI.FormRecognizer.Training.CopyModelOperation.<WaitForCompletionAsync>d__19.MoveNext() in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\src\FormTrainingClient\CopyModelOperation.cs:line 144
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.AI.FormRecognizer.Tests.FormTrainingClientLiveTests.<CopyModelWithLabelsAndModelName>d__16.MoveNext() in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\tests\FormTrainingClient\FormTrainingClientLiveTests.cs:line 448
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.AI.FormRecognizer.Tests.FormTrainingClientLiveTests.<CopyModelWithLabelsAndModelName>d__16.MoveNext() in D:\a\_work\1\s\sdk\f

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1919042&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
One week later, we haven't seen this failure again, which makes me think it was a transient issue. Closing this until we see it again.
