### ISSUE TITLE
Calling GetSecretsAsync doesn't include the version Id

### ISSUE THREAD

**Issue by saguiitay** [Azure/azure-sdk-for-net#3181]
There's no way of getting the version Id of the latest version, other than retrieving all the versions of the secret, sorting them by Attribute.Updated, and take the last one.

I would expect GetSecretsAsync() to be able to return the version Id of the secret.

**Comment by hovsepm** [comment]
@saguiitay please provide which package and package version information that you refer to.

**Comment by saguiitay** [comment]
<package id="Microsoft.Azure.Management.KeyVault" version="2.1.0-preview" targetFramework="net462" />

**Comment by saguiitay** [comment]
Package id="Microsoft.Azure.Management.KeyVault" version="2.1.0-preview" targetFramework="net462"

**Comment by pomortaz** [comment]
@saguiitay if you don't specify the version, the latest version of the secret will be returned. Version is part of secret ID.

**Comment by saguiitay** [comment]
When placing the secret ID in an ARM template to be added as secrets in a Virtual Machine Scale Set, the "full" ID, including the version is required (see https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/virtualmachinescalesets#VaultCertificate). Since I want the VMSS to use the latest version, I need to find that latest version by iterating over all the versions, sort them based on Updated attribute (since the GetSecretVersionsAsync method returns the versions sorted by the version, which is "random"), and take the latest one.

If my secret has a lot of versions, and if I have many secrets, I'm ending up making a lot of requests to keyvault...

**Comment by adrianhall** [comment]
Hello,

Is this still an issue?

Have you reproduced with the latest .NET SDK? See https://aka.ms/azure-sdk-preview2-net 

Thanks,
