### ISSUE TITLE
[FEATURE REQ] Provide a property in client option to bypass HTTPS hardening for TokenCredential

### ISSUE THREAD

**Issue by bnmaa** [Azure/azure-sdk-for-net#31817]
### Library name

Azure.Storage.Files.DataLake

### Please describe the feature.

I know that this restriction is enforced by #8810, but let me try to explain the FEATURE REQUEST.

We're building our service with below topology:
1. Our main application - Which would send excessive amount of DownloadFile and GetProperties requests to ADLS gen2
2. A local DataLake proxy server - Which supports DataLake File API transparently with its own cache layer
    - Getting sasuri for a filesystem and actively cache&reuse it by analyzing the File Uri requested by our main application
    - Potentially also cache partial file content so that it can efficiently serve fragmented range file requests without too many actual requests being sent to ADLS gen2
    - supports HTTP/HTTPS, HTTP is preferred, because 
        - the main application and the proxy server run on the same node, they communicate through the machine's loopback interface, there's no security concern
        - By using HTTP, we don't need to afford extra encryption/decryption when this proxy server pipes the file content back to our main application. Because that is causing tremendous extra computing resources.
3. A real ADLS gen2 storage

Node Boundary{ Main App <===HTTP===> Local Proxy server} <===HTTPS===> ADLS gen2

This topology works when we use azure-sdk-for-cpp under some high-concurrency scenario, because there's no symmetric restriction in azure-sdk-for-cpp.
We totally agree that this should be enforced by default.
Our request is -- can SDK team provide a client option so that we can bypass this check?

**Comment by navba-MSFT** [comment]
Adding Service team to look into this feature request.

@xgithubtriage Could you please look into this and provide an update once you get a chance ? Thanks in advance.
