### ISSUE TITLE
Create documentation for Identity credential cache

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-for-net#31810]
Our current documentation for how our SDK interacts with the MSAL token cache is insufficient. We need to doc:

- What scenarios caching is useful for
- How caching is exposed from our library
- What expectations should be when caching is used (performance, throttling)
- How the disk cache is secured when used

**Comment by jkommeren** [comment]
This would be great as it seems the WinUI Maui flavor (.net for windows) apparently does not store msal credentials outside of the app instance, when used with graph API client 5.0 for example.

In other words they're gone after app restarts. Android is fine.

**Comment by scottaddie** [comment]
Fixed in https://github.com/Azure/azure-sdk-for-net/pull/35661
