### ISSUE TITLE
[ServiceBus] CanUseMassiveSessionConcurrencyWithoutCausingThreadStarvation failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#31814]
ServiceBus nightly test runs are failing with:

> Error message
> Multiple failures or warnings in test:
> 
> Error source: AcceptSession, Exception: System.InvalidOperationException: Cannot open log for source 'Microsoft.ServiceBus'. You may not have write access.
> For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
> at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 185
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenLinkAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1410
> at Azure.Messaging.ServiceBus.ServiceBusReceiver.OpenLinkAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs:line 507
> at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.CreateSessionReceiverAsync(String entityPath, ServiceBusConnection connection, ServiceBusSessionReceiverOptions options, String sessionId, CancellationToken cancellationToken, Boolean isProcessor) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusSessionReceiver.cs:line 78
> at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.CreateSessionReceiverAsync(String entityPath, ServiceBusConnection connection, ServiceBusSessionReceiverOptions options, String sessionId, CancellationToken cancellationToken, Boolean isProcessor) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusSessionReceiver.cs:line 100
> at Azure.Messaging.ServiceBus.SessionReceiverManager.CreateReceiver(CancellationToken processorCancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:line 132
> at Azure.Messaging.ServiceBus.SessionReceiverManager.CreateAndInitializeSessionReceiver(CancellationToken processorCancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:line 113
> at Azure.Messaging.ServiceBus.SessionReceiverManager.EnsureCanProcess(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:line 83
> at Azure.Messaging.ServiceBus.SessionReceiverManager.ReceiveAndProcessMessagesAsync(CancellationToken processorCancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:line 260
> Error source: AcceptSession, Exception: System.InvalidOperationException: Cannot open log for source 'Microsoft.ServiceBus'. You may not have write access.
> For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
> at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Primitives/ServiceBusRetryPolicy.cs:line 185
> at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenLinkAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Amqp/AmqpReceiver.cs:line 1410
> at Azure.Messaging.ServiceBus.ServiceBusReceiver.OpenLinkAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Receiver/ServiceBusReceiver.cs:line 507
> at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.CreateSessionReceiverAsync(String entityPath, ServiceBusConnection connection, ServiceBusSessionReceiverOptions options, String sessionId, CancellationToken cancellationToken, Boolean isProce
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.SessionErrorHandler(ProcessErrorEventArgs args) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/SessionProcessorLiveTests.cs:line 2420
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs:line 546
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args)
>    at Azure.Messaging.ServiceBus.ServiceBusSessionProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusSessionProcessor.cs:line 160
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ServiceBusSessionProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args)
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:line 400
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs)
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.ReceiveAndProcessMessagesAsync(CancellationToken processorCancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:line 323
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.SessionErrorHandler(ProcessErrorEventArgs args) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/SessionProcessorLiveTests.cs:line 2420
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs:line 546
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args)
>    at Azure.Messaging.ServiceBus.ServiceBusSessionProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusSessionProcessor.cs:line 160
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.ServiceBusSessionProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args)
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:line 400
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.RaiseExceptionReceived(ProcessErrorEventArgs eventArgs)
>    at Azure.Messaging.ServiceBus.SessionReceiverManager.ReceiveAndProcessMessagesAsync(CancellationToken processorCancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs:line 323
>    at Azure.Messaging.ServiceBus.Tests.Processor.SessionProcessorLiveTests.SessionErrorHandler(ProcessErrorEventArgs args) in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Processor/SessionProcessorLiveTests.cs:line 2420
>    at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessErrorAsync(ProcessErrorEventArgs args) in /Use

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1916773&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
This is an issue in the `Microsoft.Azure.Amqp` library, tracked in their repository.
