### ISSUE TITLE
Azure.Communication.Email - Release date?

### ISSUE THREAD

**Issue by sujayvsarma** [Azure/azure-sdk-for-net#31825]
### Library name and version

Azure.Communication.Email

### Query/Question

This library has been in "preview" mode for ages. When is this scheduled to be "released" ?

**Comment by navba-MSFT** [comment]
@sujayvsarma Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@sujayvsarma While I get you the requested details, Could you please provide more details about your use case ? What functionality of this library are you trying to use ?

**Comment by sujayvsarma** [comment]
Huh? This library is used to send e-mail via the Azure Communication Service and this is the official SDK to that library.

**Comment by navba-MSFT** [comment]
@sujayvsarma We are in public preview and getting ready for GA targeting CYQ12023. Hope this answers your question.

**Comment by sujayvsarma** [comment]
That's a LONG time to GA. Do you know why it is going to take more than a full year for that? Changes to underlying Azure Communication Services (an Azure service) APIs? Team capacity? Low priority?

**Comment by navba-MSFT** [comment]
@sujayvsarma CYQ123 is couple months away not LONG time to GA. Could you please clarify why do we believe it is full year?

**Comment by sujayvsarma** [comment]
Sorry my bad. I misread the designator (`CYQ12023`). This is fine.
