### ISSUE TITLE
Make the management and data plane test pipelines separate by default

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#31820]
Today we need to do extra work in the service directory to split the 2 pipelines. It would be beneficial to make it as a default.

@weshaggard - we spoke offline about it.

**Comment by weshaggard** [comment]
I will take a look and see what we can do. I will work with @hallipr if it requires a larger amount of changes.

**Comment by pallavit** [comment]
@weshaggard, @hallipr is there any recommendation for the SDKs where we have a combined test pipelines? I would ideally like to preemptively split them to ensure health and easy tracking but wanted to check if there are any side affects of this approach. 

Also, is this process going to be manual or are there ways to make it more efficient?

**Comment by weshaggard** [comment]
For now I think creating a tests.mgmt.yml similar to the ci.mgmt.yml with a service.project in the directory is the best option for now. I will definitely take a closer look at both ci and tests once I get some time to do some prototyping here.

**Comment by heaths** [comment]
This came up again w.r.t. snippets. I wonder if we could make use of what we already have by default. As with the recent perf discussions about not wanting to add yet more files e.g., service.project, I think we could solve this similar to samples, stress, perf, tests, etc.

_eng/Directory.Common.Build.props_
```diff
<PropertyGroup>
    <IsClientLibrary Condition="'$(IsClientLibrary)' == '' and $(MSBuildProjectName.StartsWith('Azure.'))">true</IsClientLibrary>
+   <IsManagementLibrary Condition="'$(IsClientLibrary)' == '' and $(MSBuildProjectName.StartsWith('Azure.ResourceManager'))">true</IsClientLibrary>
</PropertyGroup>
```

_eng/service.proj_
```diff
<PropertyGroup>
    <IncludeTests Condition="'$(IncludeTests)' == ''">true</IncludeTests>
+   <IncludeMgmt Condition="'$(IncludeMgmt)' == ''">true</IncludeTests>
</PropertyGroup>

<ItemGroup>
    <ProjectReference Include="@(TestProjects)" Exclude="@(MgmtExcludePaths)" Condition="'$(IncludeTests)' == 'true'" />
+   <ProjectReference Include="@(MgmtProjects)" Condition="'$(IncludeMgmt)' == 'true'" />
</ItemGroup>
```

_(In this case, most of these exclude mgmt projects already, so maybe we can make those exclusions conditional with an intermediate item group.)_

_sdk/*/ci.mgmt.yml_
```diff
extends:
  template: /eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: keyvault
+   IncludeMgmt: true
```

_eng/pipelines/templates/stages/archetype-sdk-client.yml_
```diff
parameters:
  - name: Artifacts
    type: object
    default: []
+ - name: IncludeMgmt
+   type: boolean
+   default: false
```

Then when we call `dotnet build` or `dotnet test`, etc., we pass the parameter through like we do for samples, etc.

Just a thought. Names certainly subject to change.
