### ISSUE TITLE
[QUERY] Availability of such capability by Azure.Data.Tables

### ISSUE THREAD

**Issue by Sandeep7OnShell** [Azure/azure-sdk-for-net#31826]
### Library name and version

Azure.Data.Tables 12.6.1

### Query/Question

I am looking to wite an application that can read all ATS tables with their metadata if any, their properties, the EDM types, etc.
Then I need to write some code that will do some operations on the tables retrieved, access properties, their values, types etc.

Questions: Are there any API's which I can use to get the information needed?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @Sandeep7OnShell - The `TableServiceClient` and `TableClient` types should have all the APIs you need to perform those tasks. If there is there something more specific you have been unable to retrieve using these APIs, I'd be happy to help point you in the right direction.

**Comment by Sandeep7OnShell** [comment]
@christothes  I would need the edm types for the properties in the entities and I don't see anything such in either TableClient or TableEntity. Possible to get that information somehow?

**Comment by Sandeep7OnShell** [comment]
@christothes  I am creating/updating entities using a library https://github.com/sebagomez/azurestorageexplorer and fount out that it always inserts type as a string and I tried to make changes to have right edm types but could not. 
So, the use case is to insert/update entities with right edm types.

**Comment by christothes** [comment]
The SDK removes them since they are redundant after de-serialization. The only reason they are needed is when the json payload is the only type information available.

**Comment by Sandeep7OnShell** [comment]
@christothes On your answer: "The SDK removes them since they are redundant after de-serialization. The only reason they are needed is when the json payload is the only type information available."
I don't that should be the case. Imagine a requirement wherein I need to take the backup of entities into a table(the backup table will have string as default types for all properties) and then restore that data in original table(that does have different edm types for different properties). Unless I know the edm types, I will have problems doing the restore as edm types for new and existing types will never match.

Any other way to get the same info?

**Comment by christothes** [comment]
> Imagine a requirement wherein I need to take the backup of entities into a table(the backup table will have string as default types for all properties) and then restore that data in original table(that does have different edm types for different properties). Unless I know the edm types, I will have problems doing the restore as edm types for new and existing types will never match.
> 
> Any other way to get the same info?

A table backup to another table should never be serialized as string unconditionally. I'd consider this to be data corruption unless conversion to string in intended to be permanent. Table entities don't persist edm type data to the table. It is added by the service and the SDK as type hints during serialization for the values that can only be serialized as string in json, or serialize as string due to the service behavior (Int64). Once a table entity is persisted to the service with a property that has been converted to string, the type information is lost forever. 

> Any other way to get the same info?

Assuming you have a table entity that has been fetched from the service that was persisted as the correct types, the edm type hints can be inferred from the types of the de-serialized model properties.

**Comment by Sandeep7OnShell** [comment]
Agreed for the most part. I was trying to get data using TableEntity.Keys and since its a keys collection a dictionary it can't have edm type preserved.

The only possible way would be to deserialize the entity to a type and then get the type as inferred by properties of that entity.

**Comment by christothes** [comment]
> The only possible way would be to deserialize the entity to a type and then get the type as inferred by properties of that entity.

You can also use `TableEntity` and type check the Values. But if you know the type ahead of time and it is consistent in the table, a discrete model type is best (assuming the table still has the entity with full type information).

**Comment by Sandeep7OnShell** [comment]
The discrete model is what I was trying to go away from. And type-checking the values from TableEntity.Keys are a challenge as different types could be inferred from string(e.g: 1 can be inferred as string and boolean).

Stuck with the problem for now.

**Comment by christothes** [comment]
Yeah, all bets are off if you saved them to the service as string. Otherwise, the `TableEntity` type checks will work.

**Comment by Sandeep7OnShell** [comment]
@christothes One thing for sure, [Azure.Data.Tables](https://www.nuget.org/packages/Azure.Data.Tables/) doesn't look like an improved version of https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table as mentioned at https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table.

Microsoft.Azure.Cosmos.Table had DynamicTableEntity and we had EdmType via EntityProperty, so that could solve all issues.
Azure.Data.Tables don't have any replacement of DynamicTableEntity, hance we loose out on that information. Not sure how this seems better to MS.
Just imagine people doing migration to Azure.Data.Tables when they were using DynamicTableEntity, EdmType in old library(Microsoft.Azure.Cosmos.Table).
Soo poor.

@azure-sdk

**Comment by christothes** [comment]
> Microsoft.Azure.Cosmos.Table had DynamicTableEntity and we had EdmType via EntityProperty, so that could solve all issues. Azure.Data.Tables don't have any replacement for DynamicTableEntity, hence we lose out on that information. Not sure how this seems better to MS. Just imagine people doing a migration to Azure.Data.Tables when they were using DynamicTableEntity, and EdmType in the old library(Microsoft.Azure.Cosmos.Table). Soo poor. https://stackoverflow.com/questions/72560230/what-is-the-relevance-of-the-dynamictableentity-class for more information and struggle.

Thanks for the feedback. While the EDM type information is not explicitly available on the `TableEntity`, the information is obtainable via the values in the dictionary. While I understand this is not as simple, it should unblock this edge case secenario.

```c#
TableEntity entity = new("partitionValue", Guid.NewGuid().ToString())
{
    { "Column1", Guid.NewGuid() },
    { "Column2", 1234 },
    { "Column3", (Int64)5678 },
};

foreach (var kvp in entity)
{
    string edm = kvp.Value switch {
        int i => "Edm.Int32",
        Int64 i64 => "Edm.Int64",
        Guid g => "Edm.Guid",
        // etc.
        => "Edm.String"
    };
    Console.WriteLine($"property {kvp.Key} is {edm}");
    // output :   
    // property PartitionKey is Edm.String
    // property RowKey is Edm.String
    // property Column1 is Edm.Guid
    // property Column2 is Edm.Int32
    // property Column3 is Edm.Int64
}
```

**Comment by Sandeep7OnShell** [comment]
@christothes  The issue is reading the information from the existing entity and then preserving the same while doing updates.

**Comment by Sandeep7OnShell** [comment]
@christothes Looks like we will have to continue using the old SDK(Microsoft.Azure.Cosmos.Table) unless we have something like DynamicTableEntity in the new one([Azure.Data.Tables](https://www.nuget.org/packages/Azure.Data.Tables/)).
Hope the old one is just deprecated but not getting decommissioned soon.

https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table

**Comment by christothes** [comment]
Hi @Sandeep7OnShell - Explicitly exposing EDM type information in the client API is something we have no plans to do. There are a handful of workarounds for the specific scenario you raised, so I'm going to close out this issue. If you still feel strongly that exposing EDM type information on the API surface would be valuable feature, please open a new feature request issue that summarizes the request and any scenarios that require it.
