### ISSUE TITLE
Is there a way to update the retention period of an SQL database?

### ISSUE THREAD

**Issue by julienFlexsoft** [Azure/azure-sdk-for-net#31829]
### Library name and version

Microsoft.Azure.Management.Sql 1.0.0.71

### Query/Question

Is there a way to update the retention period of an SQL database? I can't find any documentation showing an update at all. Where can I look or how can I do it?

### Environment

.NET 6
Microsoft.Azure.Management.Fluent 1.38.1
Microsoft.Azure.Management.Sql 1.0.0.71

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@julienFlexsoft Microsoft.Azure.Management.Sql 1.0.0.71 is our old version SDK, you should switch to our new SDK [Azure.ResourceManager.Sql](https://www.nuget.org/packages/Azure.ResourceManager.Sql)
When you are saying retention period, are you referring to long term retention policy or backup short term retention policy? I can see in our SDK there is 2 retention policy for a SQL database
![image](https://user-images.githubusercontent.com/5089150/196381552-4f667cd1-93fd-4c40-a62f-71b1aba581b7.png)

**Comment by julienFlexsoft** [comment]
Thank you for your answer, I looked into it and the SDK I use is indeed marked as deprecated. I am migrating to the newer SDK for our whole app.
Regarding the retention period: I want to create databases with a PITR period of 31 days (7 days is the default) and also update existing databases to a PITR period of 31 days. Is this something I can update with this SDK?

**Comment by julienFlexsoft** [comment]
Thank you for your answer. our work on this was delayed and is currently scheduled for the current sprint, so this is perfect timing! I'll try this out in the coming days, thank you.
