### ISSUE TITLE
Long term solution for re-enable .Net Track 1 pipeline for swagger PRs

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-sdk-for-net#31839]
A short term solution is applied with https://github.com/Azure/azure-sdk-for-net/issues/31161 by dowgrading the CI agent system to Ubuntu 18.04. 

For a long term solution, we may need to release a new autorest.csharp V2 version to work with a newer .NET core version like 6.0 to unblock the upgrade of CI agent system.

**Comment by live1206** [comment]
The end of life for ubuntu 18.04 is April 30th, not April 1st. https://computing.cs.cmu.edu/news/2022/eol-ubuntu-1804
We have more time to work on this.
