### ISSUE TITLE
[BUG] WAM Account Picker works just once

### ISSUE THREAD

**Issue by FehintolaObafemi** [Azure/azure-sdk-for-net#31844]
### Library name and version

Azure.Identity.BrokeredAuthentication 1.0.0-beta.3

### Describe the bug

WAM Account picker fails to open up more than once.

When WAM was incorporated into our module, we expect to be able to sign in using WAM any number of times without fail. What we have come to realize is that WAM allows just one sign in per session meaning once the module has been loaded, the WAM account picker works just once and stops working after that

### Expected behavior

- Sign-In through WAM
- Sign out
- Sign-In through WAM
- Sign out

### Actual behavior

- Sign-In through WAM
- Sign out
- Sign-In through WAM (doesn't work)

### Reproduction Steps

https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/1344

- .\tools\GenerateAuthenticationModule.ps1 -Build -Run (Build and install module on local device)
- Connect-MgGraph -SignInUI Native (Sign in using WAM now works as expected).
- Disconnect-MgGraph (Sign out of account)
- Connect-MgGraph -SignInUI Native (Sign in again using WAM fails to open WAM account picker).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by FehintolaObafemi** [comment]
Here is a link to the implementation line

https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/eb0f42e4f01aecece5abe75b5129936c094c7e24/src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs#L109
