### ISSUE TITLE
[FEATURE REQ] Support for managing Event Hubs using connection strings

### ISSUE THREAD

**Issue by ErikMogensen** [Azure/azure-sdk-for-net#31848]
### Library name

Event Hubs

### Please describe the feature.

According to [the official Event Hubs management libraries article](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-management-libraries) you have to use AAD for managing Event Hubs. I would like to be able to manage Event Hubs with connection strings just like it is possible to manage Service Bus queues and topics with connection strings using the [ServiceBusAdministrationClient class](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient?view=azure-dotnet) 

Since this is possible using [the old WindowsAzure SDK](https://learn.microsoft.com/en-us/dotnet/api/microsoft.servicebus.namespacemanager.createeventhub?view=azure-dotnet) it looks like the backend service support is there.

**Comment by jsquire** [comment]
Hi @ErikMogensen.  Thank you for your inquiry.   This isn't something that we plan to add to the Event Hubs client library.  

The Azure security model separates resource management operations from those that interact with the data stored in those resources.  The management operations use [RBAC](https://learn.microsoft.com/azure/role-based-access-control/overview) permissioning to allow for more granular control, better traceability, and similar benefits.  Any management operations that take place for the Azure Resource Manager (ARM) providers must comply.

The older generation WindowsAzure package makes use of an ATOM-based API for management that predates ARM, supports a subset of management functionality, and does not adhere to ARM security guidance.  An exemption was also granted for the Service Bus library to include it for compatibility reasons, due overwhelming demand.  There has not been the same level of demand for inclusion in Event Hubs.   The legacy ATOM API is [public and documented](https://learn.microsoft.com/rest/api/eventhub/event-hubs-management-rest) should you wish to call it from your application.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by ErikMogensen** [comment]
Thank you @jsquire for the quick and great answer. It makes sense.
