### ISSUE TITLE
Missing critical information about serialization

### ISSUE THREAD

**Issue by pettys** [Azure/azure-sdk-for-net#31862]
This page should describe or have a link to a page that describes the details of how implementations of ITableEntity are handled by this library. For example:

- What types of properties can be automatically serialized to/from table storage?
- If I have properties of my ITableEntity that I want the SDK to ignore when serializing/deserializing, can I do that?

I've hunted through the documentation at least three separate times for quite a while each time and cannot find the information. In general for any library that serializes/deserialized C# objects, it is critical to have an overview about how the constraints, expectations, and configurability of that serialization work.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 96c66b59-7f5c-84db-a4da-8cb27a786f5f
* Version Independent ID: f78c6c9a-1e69-1ff0-de2e-7d1689fa3eed
* Content: [ITableEntity Interface (Azure.Data.Tables) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.itableentity?source=recommendations&view=azure-dotnet)
* Content Source: [xml/Azure.Data.Tables/ITableEntity.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Data.Tables/ITableEntity.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Thanks for the feedback - This information should definitely be better documented. 

In the meantime, here is a sample that demonstrates how to ignore and rename entity properties for during serialization. 

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/tests/samples/Sample8_CustomizingSerialization.cs

**Comment by pettys** [comment]
@christothes thanks so much for the comment. The link you sent was helpful. I had looked over all of these samples, searching for the answer:

https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/tables/Azure.Data.Tables/samples

I didn't realize there were more samples here:
https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/tables/Azure.Data.Tables/tests/samples

Definitely looks like there's some overlap in those sample sets... seems odd. Also, for what it's worth, this rework of the tables SDK is missing a lot of the serialization flexibility that the previous versions I've used had -- kinda a bummer, but I can work around it.

Anyway, thanks for the quick response, it's very much appreciated!

**Comment by christothes** [comment]
Thanks, @pettys,

We are aware of the current gaps in serialization customization and have been compiling the most important user scenarios to inform any possible future enhancements. Would you mind describing your current use cases as well as any info you'd be willing to share about your workarounds?

**Comment by pettys** [comment]
@christothes Thanks for asking and sorry for the delay in the response. I would reiterate that my main request with this issue would be to have the documentation about the serialization more discoverable -- if a developer knows what there is to work with up front, and especially the limitations, then that developer can decide how to build the objects accordingly.

The particular case I was trying to figure out this go around was a basic composition - completely analogous to serializing a Person with an Address property, where Address is class with Line1, Line2, City, State, Zip. When I was digging through the open odata serialization code, I thought maybe the serializer would flatten the composition, which would have been just fine, or maybe the column names would have been PersonId, PersonName, Address.Line1, Address.Line2, etc.

Once I understood the limitations of the serialization from your quick responses (again, thank you for that) I decided to separate the domain/business logic classes from the serialization classes -- that is to say, if I save a Person, the storage code will copy the Person object data into a separate PersonTableRecord object, which is then tuned to serialize.

I think with a little more control over the serialization, that extra layer and repetitive property-copying code wouldn't be necessary. It just took me a while to decide to bite the bullet and add that in because I couldn't tell what was going to be possible.
