### ISSUE TITLE
[QUERY] Is the BlobServiceClient Method GetBlobContainerClient() is supposed to create container on not finding one ?

### ISSUE THREAD

**Issue by Kinaetron** [Azure/azure-sdk-for-net#31863]
### Library name and version

Azure.Storage.Blobs 12.11.0

### Query/Question

I've written the code 

```C# code
var serviceClient = new BlobServiceClient(connectionString);
var containerClient = serviceClient.GetBlobContainerClient(containerName);
```

From what the documentation I've read this seems to not supposed to create a container if there isn't one already, but for some reason it does create a container. I'm I missing something ?

### Environment

Windows 10
Visual Studio 2019
.NET 5.0
Azurite using Docker

**Comment by navba-MSFT** [comment]
@Kinaetron Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by Kinaetron** [comment]
I tried it with a real azure account and the same issue happened
