### ISSUE TITLE
Deprecated package in documentation, please update

### ISSUE THREAD

**Issue by Aileron79** [Azure/azure-sdk-for-net#31860]
On this page you recommend using the Microsoft.Azure.Management.Sql.Fluent package. However, when trying to install it, it says the package is deprecated:
![image](https://user-images.githubusercontent.com/16278437/196355555-d8d599e9-b125-4e22-a1db-e0ebcef936d0.png)

Azure.ResourceManager.Sql is recommended as a replacement, but I cannot find documentation on how to scale databases using that package. 

I opened a quesion [about this yesterday](https://github.com/Azure/azure-sdk-for-net/issues/31838) that has not been answered so far, but, this is just a reminder to please update your documentation accordingly as it recommends using a deprecated package.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a8015762-a2f1-e3b0-3b4c-1234b1097024
* Version Independent ID: c49582ae-0a9f-79d3-e01c-e26ed1520bbb
* Content: [Azure SQL Database APIs for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/sql?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/sql.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/sql.md)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by fengzhou-msft** [comment]
@xboxeer for awareness on doc update.

**Comment by ArthurMa1978** [comment]
This still not fixed and pending on the doc release pipeline change
