### ISSUE TITLE
[BUG] Cannot get lease on container - HTTP 400 returned on header value

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-sdk-for-net#31866]
### Library name and version

Azure.Storage.Blobs 12.14.0

### Describe the bug

I'm using this code:

```csharp
var cred = new ChainedTokenCredential(new EnvironmentCredential(), new VisualStudioCredential(), new AzureCliCredential(), new AzurePowerShellCredential(), new InteractiveBrowserCredential());
var container = new BlobContainerClient(new Uri($"https://{input.AccountName}.blob.core.windows.net/{input.ContainerName}"), cred, options: retryOptions);

Console.WriteLine("Connecting to container...");
if (!container.Exists())
{
    Console.Error.WriteLine($@"Container '{input.ContainerName}' does not exist in storage account '{input.AccountName}'!");
    return;
}

BlobLease? lease = null;
try
{
    lease = container.GetBlobLeaseClient().Acquire(TimeSpan.FromMinutes(10)).Value;

...
```

to attempt to get a lease on a container while I do things in it.

When I attempt to do this, the SDK throws an HTTP 400 error stating the header is in an incorrect format:
```
Azure.RequestFailedException
  HResult=0x80131500
  Message=The value for one of the HTTP headers is not in the correct format.
RequestId:a5fa6167-401e-00e6-4912-e32aa7000000
Time:2022-10-18T16:57:22.2360552Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Additional Information:
HeaderName: x-ms-lease-duration
HeaderValue: 600

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.
RequestId:a5fa6167-401e-00e6-4912-e32aa7000000
Time:2022-10-18T16:57:22.2360552Z</Message><HeaderName>x-ms-lease-duration</HeaderName><HeaderValue>600</HeaderValue></Error>

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: a5fa6167-401e-00e6-4912-e32aa7000000
x-ms-client-request-id: 01415325-0997-4c8d-90e6-07d8ba1803ed
x-ms-version: 2021-10-04
x-ms-error-code: InvalidHeaderValue
Date: Tue, 18 Oct 2022 16:57:21 GMT
Content-Length: 328
Content-Type: application/xml

  Source=Azure.Storage.Blobs
  StackTrace:
   at Azure.Storage.Blobs.ContainerRestClient.AcquireLease(Nullable`1 timeout, Nullable`1 duration, String proposedLeaseId, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, CancellationToken cancellationToken) in /_/sdk/storage/Azure.Storage.Blobs/src/Generated/ContainerRestClient.cs:line 882
   at Azure.Storage.Blobs.Specialized.BlobLeaseClient.<AcquireInternal>d__26.MoveNext() in /_/sdk/storage/Azure.Storage.Blobs/src/BlobLeaseClient.cs:line 365
   at Azure.Storage.Blobs.Specialized.BlobLeaseClient.Acquire(TimeSpan duration, RequestConditions conditions, CancellationToken cancellationToken) in /_/sdk/storage/Azure.Storage.Blobs/src/BlobLeaseClient.cs:line 183
```

### Expected behavior

A lease object is returned for the desired timespan

### Actual behavior

No lease can be obtained, an exception is thrown

### Reproduction Steps

Use the above code against a General Purpose storage account's blob container

### Environment

Using .NET 6.0, latest

**Comment by navba-MSFT** [comment]
@brandonh-msft Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@brandonh-msft I found the below from our documentation:


x-ms-lease-duration: -1 ¦ N | Version 2012-02-12 and newer. Only allowed and required on an acquire operation. Specifies the duration of the lease, in seconds, or negative one (-1) for a lease that never expires. **A non-infinite lease can be between 15 and 60 seconds**. A lease duration cannot be changed using renew or change.
-- | --

Could you please try to reduce the lease duration in seconds to between 15 and 60 seconds and check if that helps ?

**Comment by brandonh-msft** [comment]
> @brandonh-msft Brandon Hurlburt FTE I found the below from[ our documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/lease-blob):
> 
> x-ms-lease-duration: -1 ¦ N	Version 2012-02-12 and newer. Only allowed and required on an acquire operation. Specifies the duration of the lease, in seconds, or negative one (-1) for a lease that never expires. **A non-infinite lease can be between 15 and 60 seconds**. A lease duration cannot be changed using renew or change.
> Could you please try to reduce the lease duration in seconds to between 15 and 60 seconds and check if that helps ?

Thanks for that - I see it as a XML comment on the API as well. (We should have a Roslyn analyzer that highlights this as an Error for our developers, or at least throw an `ArgumentOutOfRangeException`).
At any rate what I'd prefer, then, is `Infinite` in this case. But how can I get -1 thru to that API using the SDK if the SDK wants a non-nullable `TimeSpan` object?

**Comment by navba-MSFT** [comment]
@brandonh-msft Thanks for your reply. Did you add the necessary changes in your code and check if that helps? Please let us know if you had any updates on this. Awaiting your reply.

**Comment by brandonh-msft** [comment]
I'll go ahead and close, but would really like to see one of my suggestions above implemented.
