### ISSUE TITLE
[Monitor] Query live tests take over an hour to run and get canceled

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#31871]
I suspect it may be due to this test taking a long time - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.Query/tests/LogsQueryClientClientLiveTests.cs#L614

**Comment by nisha-bhatia** [comment]
Also update the pipeline page to show separated monitor pipelines - Ingestion, Query, and OpenTelemetryExporter

**Comment by nisha-bhatia** [comment]
pipeline issues have been resolved
