### ISSUE TITLE
Usage of Authorization method GetAzurePermissionsForResources (or GetAzurePermissionsForResourcesAsync)

### ISSUE THREAD

**Issue by ritchiehughes** [Azure/azure-sdk-for-net#31870]
### Library name and version

Azure.ResourceManager.Authorization 1.0.0

### Query/Question

I'm unsure how we're supposed to use `AuthorizationExtensions.GetAzurePermissionsForResourcesAsync(this ResourceGroupResource resourceGroupResource, string resourceProviderNamespace, string parentResourcePath, string resourceType, string resourceName, CancellationToken cancellationToken = default)`

There are two problems:

* The 4 required parameters (resourceProviderNamespace, parentResourcePath, resourceType, resourceName) don't map naturally to a ResourceId with 3 path components in the form "providers/resourceProviderNamespace/resourceType/resourceName", such as "providers/Microsoft.Storage/storageAccounts/MYACCOUNT"
* The SDK appears to be trying to use API version `2022-04-01` but the regions I'm targeting only support '2015-06-01' and below.

I'm currently trying variations of:

```csharp
var pages = arm
    .GetResourceGroupResource(rgId)
    .GetAzurePermissionsForResourcesAsync(targetId.ResourceType.Namespace, NOT_SURE_HERE, targetId.ResourceType.Type, targetId.Name);
```

Can you provide an example of how this SDK method should be use, or an alternative SDK method that provides the same functionality (list the calling principal's permissions for a specific resource ID).

Thanks!

### Environment

.NET 6.0 on Linux

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ritchiehughes** [comment]
I was able to work-around the first problem by passing either an empty string or a hacky relative path ('../providerNamespace'). The API version mismatch is still blocking thought. I assume the autorest clients were generated from a spec version that hasn't been deployed to all prod regions yet?

**Comment by xboxeer** [comment]
> I was able to work-around the first problem by passing either an empty string or a hacky relative path ('../providerNamespace'). The API version mismatch is still blocking thought. I assume the autorest clients were generated from a spec version that hasn't been deployed to all prod regions yet?

the API version we release is on behalf of service team's ask, that means Authorization RP asks us to release 2022-4-1 version. I'd say we need service team's explanation that why for certain region the API version mismatches azure global.

**Comment by dagoroz** [comment]
We have taken notice of the latest api version not being exposed properly.
We have a fix for that and it should roll out over the next couple of weeks.

Regarding the parent resource type, that argument can be "" as it is optional. Unfortunately by the nature of how SDKs are produced, the fix for that one will take longer but I assure you that we have taken notice of that and will be fixed for the next api-version + SDK release
