### ISSUE TITLE
[BUG]ReceiveMessageAysnc set in 2s and message locked cannot process

### ISSUE THREAD

**Issue by Scarlettliuyc** [Azure/azure-sdk-for-net#31883]
### Library name and version

Azure.Messaging.ServiceBus --version 7.11.0

### Describe the bug

**Background**:
We are using this function https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusreceiver.receivemessageasync?view=azure-dotnet-preview#parameters
await ReceiveMessageAysnc(maxWaitTime )
The maxWaitTime set in 2s, 5s. And the message volume like 2000 pre second then it would have chance for 20-30 messages locked.
Lock duration 2 minutes 
Sypthom:
The message was locked with out any error. 
For example:
•	Message ID : xxxxxxxxxxxxxxx
•	Sent to topic: 10/10/2022 6:20:44 AM
•	Lock first time: 10/10/2022 6:20:44 AM
•	Send back to queue: 10/10/2022 6:22:44 AM due to abandon
•	Then lock again. The consumer received it at 10/10/2022 6:22:44 AM.

However based on our consideration the **ReceiveMessageAysnc** timeout, it would send timeout for this message and a log in the client. 
It's await function, it needs to have return then lock the message or if this function timeout, it would return back and retry again. However it stay in 2 minutes in lock without any log and then after this lock expired it send back to queue and delivery again.
But there isn't any issue when maxWaitTime  set as 60 s follow the default value

### Expected behavior

When ReceiveMessageAysnc timeout, it needs to have log to the code and retry again.

### Actual behavior

ReceiveMessageAysnc might timeout, but the message lock in Service Bus in 2 minutes and next time lock it again and deliver it. 

### Reproduction Steps

Set ReceiveMessageAysnc maxWaitTime  2s, Lock duration 2 minutes
Then receive more than 2000 messages pre second in Service Bus.
There are multiple threads after call ReceiveMessageAysnc, but even use 1 thread the issue still occured 

### Environment

.Net Core 6.0

**Comment by jsquire** [comment]
Hi @Scarlettliuyc.  Thank you for reaching out and we regret that you're experiencing difficulties.   I'm not sure that I understand what you're describing.   I believe what you're asking is "does the maxWaitTime instruct the server to hold a lock on the message for that duration?"    If I'm incorrect, please let us know.

The `maxWaitTime` does not have any influence or impact on message locks.   That parameter is the amount of time that the client will wait for a message to be available to be read.   If no messages can be read in that interval, the `ReceiveMessageAsync` call will return without a message.   However, once a message is read, the call will return it immediately.   

For PeekLock mode, when `ReceiveMessageAsync` returns a message, the server has locked it according to the duration configured for the queue/subscription.   The lock duration is a service value and not something that client controls.   Abandoning a message releases the lock and the message is available immediately to be read.

**Comment by Scarlettliuyc** [comment]
Thanks @jsquire, but from the log the message was locked in 2 minutes event though no Lock lost exception. 
It looks like the message has locked in the service bus server, however the ReceiveMessageAsync didn't response anything for 2 minutes even set the maxWaitTime  to 2s.

**Comment by jsquire** [comment]
Thank you for the clarification, @Scarlettliuyc.   It sounds like what you're seeing is that the service locks a message, but the client never receives it.    If the `ReceiveMessageAsync` call didn't return for 2 minutes, there's a good chance that it was performing retries for an exception that it encountered.   I wonder if the link that the lock was associated with faulted and when retries were able to establish a new link, the service did not return the message.

A couple of follow-up questions:

- Did you see an exception from `ReceiveMessageAsync` or did it just return no message?   
- Are you able to reproduce this and [capture SDK logs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging) for a 5-minute period around the behavior?


@JoshLove-msft : Would you please take point for digging into this?

**Comment by Scarlettliuyc** [comment]
Thanks @jsquire 
Did you see an exception from ReceiveMessageAsync or did it just return no message?
No exception, there was a log in ReceiveMessageAsync when it first return. But no log, no exceptions in the client.
Are you able to reproduce this and [capture SDK logs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging) for a 5-minute period around the behavior?
Yes, it always possible to be reproduce when set the maxWaittime to 2s or 5s. And receive more than 20000 messages each time.

**Comment by JoshLove-msft** [comment]
We are discussing this offline.

**Comment by JoshLove-msft** [comment]
The issue is that the in-flight messages remain locked after the receiver is closed. I filed a [feature request](https://github.com/Azure/azure-amqp/issues/229) to have Drain support in the AMQP library, and am testing out a workaround in the Service Bus library.
