### ISSUE TITLE
[Service Bus] Add stress tests

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#31880]

**Comment by pallavit** [comment]
Do we have a stress infrastructure in place?

**Comment by JoshLove-msft** [comment]
Yes, @m-redding has already implemented stress tests using the Eng Sys infrastructure for Event Hubs.

**Comment by m-redding** [comment]
Summary:
Use the Eng Sys [azure-sdk-chaos](https://github.com/Azure/azure-sdk-tools/blob/main/tools/stress-cluster/chaos/README.md) stress test framework to deploy stress tests for Service Bus. Use the infrastructure that is already in place for Event Hubs as a starting point.

Roles:
- Sender
- Session sender
- Receiver
- Session receiver
- Processor

Scenarios:
- SendReceive
- SessionSendReceive
- SendProcess

Will update the above as more tests are developed
