### ISSUE TITLE
[Event Grid] Split client and management test pipelines

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#31881]
Since the mgmt tests were merged in https://github.com/Azure/azure-sdk-for-net/commit/0ea6efbe000c1d3a3a16719c85ebf83230ae555f, the live test runs have been timing out. We should either split into two separate pipelines and use an adequate timeout for the mgmt pipeline, or disable the mgmt live tests if they cannot be run in a reasonable amount of time.

**Comment by jsquire** [comment]
Let's please split the pipelines.

**Comment by pallavit** [comment]
I thought we made a broad stroke change to split all the pipelines? I am curious why this was missed and if there are others that may be in the same boat.

**Comment by JoshLove-msft** [comment]
> I thought we made a broad stroke change to split all the pipelines? I am curious why this was missed and if there are others that may be in the same boat.

I think the change was to split CI pipelines. This issue is about splitting test pipelines.

**Comment by pallavit** [comment]
> > I thought we made a broad stroke change to split all the pipelines? I am curious why this was missed and if there are others that may be in the same boat.
> 
> I think the change was to split CI pipelines. This issue is about splitting test pipelines.

My bad. I think then we need to do this across SDKs too! I will talk to the engsys team and see how best to do it.

**Comment by pallavit** [comment]
I had created a work-item to make the split the default so we don't accrue any unintentional debt  - https://github.com/Azure/azure-sdk-for-net/issues/31820 but looks like we have some clean up to do here.

**Comment by ArthurMa1978** [comment]
I have a PR https://github.com/Azure/azure-sdk-for-net/pull/31927 here to split the test pipelines for EventGrid
