### ISSUE TITLE
ReadToken function documentation should make it clear that the function provides no security validations on the token

### ISSUE THREAD

**Issue by Velby** [Azure/azure-sdk-for-net#31896]
ReadToken function documentation should make it clear that the function provides no security validations on the token. A warning should be clearly visible telling developpers that this function should never be used to authenticate/authorize users

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34dd478c-66e2-e9aa-38b4-893a664cd024
* Version Independent ID: 702be51f-a3ff-833e-c60c-524715f02649
* Content: [JwtSecurityTokenHandler.ReadToken Method (System.IdentityModel.Tokens.Jwt) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtsecuritytokenhandler.readtoken?view=azure-dotnet)
* Content Source: [xml/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `System.IdentityModel.Tokens.Jwt` library is maintained as [#1950](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1950).
