### ISSUE TITLE
"Returns" description not matching actual return type

### ISSUE THREAD

**Issue by qbqaf** [Azure/azure-sdk-for-net#31891]
For the `GetSyncTable<T>()` method, the description says the method "Returns a [IMobileServiceTable<T>](https://learn.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.mobileservices.imobileservicetable-1?view=azure-dotnet) instance", but the "Returns" section shows it returns the type "[IMobileServiceSyncTable<T>](https://learn.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.mobileservices.sync.imobileservicesynctable-1?view=azure-dotnet)", which is the **Sync** version of the type mentioned.

Should be an easy fix, simply add **Sync** to the return type in the description.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7dcece93-fa05-e81e-c681-83f8c78352c6
* Version Independent ID: e7c85e82-5019-fc0c-2613-8ae833927f03
* Content: [IMobileServiceClient.GetSyncTable Method (Microsoft.WindowsAzure.MobileServices) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.mobileservices.imobileserviceclient.getsynctable?view=azure-dotnet#microsoft-windowsazure-mobileservices-imobileserviceclient-getsynctable-1)
* Content Source: [xml/Microsoft.WindowsAzure.MobileServices/IMobileServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.MobileServices/IMobileServiceClient.xml)
* Service: **app-service-mobile**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the MS Docs repository as [#100154](https://github.com/MicrosoftDocs/azure-docs/issues/100154)
