### ISSUE TITLE
Adding a certificate to the library which isn't bound to a host name

### ISSUE THREAD

**Issue by ajit-kolathur** [Azure/azure-sdk-for-net#3190]
Hi,

We use a certificate for client certificate authentication, the cert needs to be installed but it isn't bound to any host name. I noticed that the management library doesn't support adding a certificate which isnt bound to a host name. The azure portal supports this by having two separate features, adding a certificate and binding a certificate. Are there plans to support simple install of cert without biding?

Thanks

**Comment by Dona278** [comment]
@ajit-kolathur Have you tried add a certificate to an existing web app using:
```csharp
// webApp: IWebApp
// certificate: X509Certificate2
await webApp.Manager.AppServiceCertificates
                    .Define(string.Format("{0}##{1}#", certificate.Thumbprint, webApp.Region.Name))
                    .WithRegion(Region.EuropeWest)
                    .WithExistingResourceGroup(webApp.ResourceGroupName)
                    .WithPfxByteArray(certificateBytes)
                    .WithPfxPassword(certificatePass)
                    .CreateAsync();
```

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#56
