### ISSUE TITLE
Test failed in net - resourcemanager - mgmt - ci due to project reference

### ISSUE THREAD

**Issue by Yao725** [Azure/azure-sdk-for-net#31905]
In the tests of Azure.ResourceManager.EventHubs, we have a package reference to [Azure.ResourceManager.ManagedServiceIdentitie](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.ResourceManager.EventHubs/tests/Azure.ResourceManager.EventHubs.Tests.csproj#L9). But our pipeline will take turns using project reference and package reference for tests and EventHubs just happens to belong to the group that used project reference.

Currently we have a PR https://github.com/Azure/azure-sdk-for-net/pull/31887 to upgrade the API version for ManagedServiceIdentitie and it will cause the failure of EventHubs tests because of the API version mismatch in the test recording. Considering that we have a GAed Azure.ResourceManager.ManagedServiceIdentitie, we should probably respect the package reference in test project because instead of using project reference to override the settings.

**Comment by ArthurMa1978** [comment]
> If the package reference works the project reference should work as well otherwise there is likely a breaking change which is exactly why we do this check in CI.

The scenario is:  sdk **A** need upgrade to new version and have a PR for review, the test of sdk **B** depends on sdk **A**, then the ci `net - resourcemanage - mgmt - ci` check will failed for sdk **A**'s when running tests for sdk **B** because the REST API version in recorded test data is still old but expect new version.

**Comment by weshaggard** [comment]
Is this only about a test recording mis-match? Seems so based on what I see at https://dev.azure.com/azure-sdk/public/_build/results?buildId=1929795&view=ms.vss-test-web.build-test-results-tab&runId=36123710&resultId=103310&paneView=debug. Is there any reason we need the api-version in the name of the recorded test?

**Comment by ArthurMa1978** [comment]
Will fix the tests that will not record the setup steps
