### ISSUE TITLE
[QUERY] Conversations not working with proxy

### ISSUE THREAD

**Issue by Gdelly** [Azure/azure-sdk-for-net#31912]
### Library name and version

Azure.Ai.Language.Conversations 1.0.0

### Query/Question

I have written code nearly exactly as described in the sample code posted by Microsoft [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples/Sample1_AnalyzeConversation_ConversationPrediction.md). This works fine when I deploy the code to Azure. However , when running it in debug mode in VS Code behind our corporate proxy it throws an exception on line:

```C#
Response response = await client.AnalyzeConversationAsync(RequestContent.Create(data));
```

with the message "GSSAPI operation failed with error - An. invalid name was supplied (Configuration file does not specify default realm)."  

We have http_proxy and https_proxy env variables set to correct proxy settings , however this suggests to me that the function is not using them.

Is there anything in the implementation of _ConversationAnalysisClient.AnalyzeConversationAsync()_ that would cause this to be an issue? 

Interesting to note that we have implemented Custom Question Answering code similar to this example [here](https://github.com/microsoft/BotBuilder-Samples/blob/main/samples/csharp_dotnetcore/12.customQABot/Bots/CustomQABot.cs).  The call to language studio there:

_customQuestionAnswering.GetAnswersAsync_ 

uses the same host uri and the same azure key but has no issues.

### Environment

.NET Core 3.1.423

Runtime Environment:
OS Name: ubuntu
OS Version: 20.04
OS Platform: Linux

.NET Core runtimes installed:
Microsoft.AspNetCore.App 3.1.29
Microsoft.NETCore.App 3.1.29

VS Code 1.72.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Interesting. We do support `http_proxy` and `https_proxy` environment variables in our pipeline: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/Internal/HttpEnvironmentProxy.cs. Stepping through the code, we do hit this code path and attempt to create a proxy. The GSSAPI error suggests you use an authenticated proxy. Is that correct? Can you either share an anonymized example of your proxy environment variable or debug your app and step through `Azure.Core.Pipeline.HttpEnvironmentPRoxy.TryCreate` to see where it fails?
