### ISSUE TITLE
[BUG] No ARM template Validate() fn in Azure.ResourceManager

### ISSUE THREAD

**Issue by johncrim** [Azure/azure-sdk-for-net#31915]
### Library name and version

Azure.ResourceManager 1.3.1

### Describe the bug

Since [Microsoft.Azure.Management.ResourceManager](https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceManager) is deprecated, I tried to migrate code from `Microsoft.Azure.Management.ResourceManager` to `Azure.ResourceManager` using:
* https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md
* https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template/blob/main/Program.cs
* and inspecting the source code in this repo

I cannot find a way to implement template validation using the Azure.ResourceManager 1.3.1 lib.

Here's a snippet of the old code that is blocked on migration:

```cs
       private async Task<bool> ValidateArmTemplate(DeploymentProperties toValidate,
                                                     string resourceGroupName,
                                                     string deploymentName)
        {
            ResourceManagementClient client = GetResourceManagementClient();
            var validateResult = await client.Deployments.ValidateAsync(resourceGroupName,
                                                                        deploymentName,
                                                                        new Deployment(toValidate),
                                                                        _cancellationToken);
            if (validateResult.Error != null)
            {
                // Report validation error
                return false;
            }
            // ... other result reporting
        }

```

I have identified methods like `ArmDeploymentResource.ValidateAsync()`, which looks like what I want, but I can't figure out a way to create an `ArmDeploymentResource` without deploying it. For example, this code:

https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template/blob/main/Program.cs

Deploys the template; and there is no equivalent method for either creating an `ArmDeploymentResource` without deploying it, or just validating the `ArmDeploymentContent`.

### Expected behavior

An implementation is provided in the new library for key functionality in the old library, before deprecating the old library.

### Actual behavior

Blocked on migration.

### Reproduction Steps

Try writing code to validate this example without deploying it:

https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template/blob/main/Program.cs

using Azure.ResourceManager and Azure.ResourceManager.Resources

### Environment

❯ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.400     
 Commit:    7771abd614  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19044
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.400\

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by johncrim** [comment]
Hi - I figured out a way to do this, so I'll leave a short example (in case it helps anyone) and close the issue. 

Here's a code snippet that shows how to validate a template:

```cs
        var credential = new DefaultAzureCredential();
        var subscriptionId = Environment.GetEnvironmentVariable("AZURE_SUBSCRIPTION_ID");
        var client = new ArmClient(credential, subscriptionId);

       var deploymentContent = new ArmDeploymentContent(new ArmDeploymentProperties(ArmDeploymentMode.Incremental)
                {
                    Template = BinaryData.FromString(templateContent),
                    Parameters = BinaryData.FromObjectAsJson(new
                    {
                        hostingPlanName = new
                        {
                            value = hostingPlanName
                        },
                        webSiteName = new
                        {
                            value = webAppName
                        },
                        skuName = new
                        {
                            value = webSkuName
                        },
                        skuCapacity = new
                        {
                            value = webSkuCapacity
                        },
                    })
                });

        var resourceGroupId = ResourceGroupResource.CreateResourceIdentifier(SubscriptionId!, resourceGroupName);
        // This ArmDeploymentResource resource may or may not exist, but it doesn't matter - it's just a placeholder for validation
        var deploymentResourceId = ArmDeploymentResource.CreateResourceIdentifier(resourceGroupId, deploymentName);
        var armDeployment = client.GetArmDeploymentResource(deploymentResourceId);

        var validateOperation = await armDeployment.ValidateAsync(WaitUntil.Completed, toValidate, _cancellationToken);

        var validateResult = validateOperation.Value;
        if (validateResult.Error != null)
        {
            _logger.LogEndOperation(loggerOpKey, false, validateResult.Error.Message ?? "Validation errored");
            _logger.LogError(JsonConvert.SerializeObject(validateResult.Error, Formatting.Indented));
            return false;
        }

        // Log this if you want:
        string deploymentDetails = $"Deployment: {deploymentName} ProvisioningState:{validateResult.Properties.ProvisioningState}\n"
                                   + $"    started:{validateResult.Properties.Timestamp} duration:{validateResult.Properties.Duration}\n"
                                   + $"    correlationId:{validateResult.Properties.CorrelationId}\n"
                                   + $"    outputs:{JsonConvert.SerializeObject(validateResult.Properties.Outputs)}";
        bool succeeded = validateResult.Properties.ProvisioningState == "Succeeded";
        return succeeded;
```
