### ISSUE TITLE
[BUG] EventHubs processor creates one span for batch and then calls process for each message

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-for-net#31922]
### Library name and version

Azure.Messaging.EventHubs

### Describe the bug

We create `EventHubs.Process` scope here:

https://github.com/Azure/azure-sdk-for-net/blob/ff5de97ef0e11af6e5bf3d61cccf9b5d6cc0602d/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L590

and then call into 

https://github.com/Azure/azure-sdk-for-net/blob/ff5de97ef0e11af6e5bf3d61cccf9b5d6cc0602d/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L622

Then in the `EventProcessorClient` we dispatch individual messages:

https://github.com/Azure/azure-sdk-for-net/blob/ff5de97ef0e11af6e5bf3d61cccf9b5d6cc0602d/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClient.cs#L973

As a result, aspecially in high-scale scenarios where messages are delivered in batches, users get one Process span for unrelated messages and all individual message processing are done in scope of it. It results in broken tracing  and Process spans that last for hours, e.g. like here:
(`ProcessEventHandler` is a manual span that represents individual message)

<img width="960" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/2347409/197080500-525fb6be-6a57-4d7e-8e4e-f484019b2e05.png">

### Expected behavior

We should have one Process span per message for single-dispatch case in `EventHubProcessorClient`.
 
If we remove tracing from `EventProcessor`, it might affect tracing in function extension, perhaps we should do tracing there or find other creative ways to control tracing behavior in EventProcessor.

### Actual behavior

If multiple messages are received from `await consumer.ReceiveAsync(EventBatchMaximumCount, Options.MaximumWaitTime, cancellationSource.Token)` in `EventProcessor`, it creates one `Process` span per batch.

Then we call into `EventHubProcessorClient` that processes individual messages in scope of one span.

### Reproduction Steps

1. Create application that receives a lot of events from EH
2. Set high `EventBatchMaximumCount`
3. Enable OTel or ApplicationInsights SDK

**Comment by JoshLove-msft** [comment]
@jsquire do you think we can use the same approach we took in https://github.com/Azure/azure-sdk-for-net/pull/28341 and essentially treat https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventprocessorclientoptions.cacheeventcount?view=azure-dotnet#azure-messaging-eventhubs-eventprocessorclientoptions-cacheeventcount as always 1? Or perhaps we can use this value to tweak the PrefetchCount, i.e. Add the CacheEventCount value to PrefetchCount so we maintain the same throughput.

If we can't do this, are we able to move the scope creation out of EventProcessor and into EventProcessorClient? I would think removing from EventProcessor would break custom implementers.

**Comment by jsquire** [comment]
> essentially treat [CacheEventCount](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventprocessorclientoptions.cacheeventcount?view=azure-dotnet#azure-messaging-eventhubs-eventprocessorclientoptions-cacheeventcount) as always 1

We could potentially do that for the processor client.   Though it reads in batches (CacheEventCount == batch size for reads) it will always dispatch to the handler 1-by-1.     We definitely don't want to alter the value of the batch size itself, as it's a valuable knob for performance tuning and reading in batches of 1 is not a great idea across scenarios.

> https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventprocessorclient.onprocessingeventbatchasync?view=azure-dotnet#azure-messaging-eventhubs-eventprocessorclient-onprocessingeventbatchasync(system-collections-generic-ienumerable((azure-messaging-eventhubs-eventdata))-azure-messaging-eventhubs-primitives-eventprocessorpartition-system-threading-cancellationtoken)

Also true.

> If we can't do this, are we able to move the scope creation out of EventProcessor and into EventProcessorClient? I would think removing from EventProcessor would break custom implementers, so this doesn't seem like a viable option either.

Agreed; we can't move it exclusively to the client.

> Another idea would be to expose this [method](https://github.com/Azure/azure-sdk-for-net/blob/ff5de97ef0e11af6e5bf3d61cccf9b5d6cc0602d/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs#L573) so it can be overriden by EventProcessorClient.

That method is intentionally infrastructure.   I don't believe it's appropriate to expose it for all custom implementations and I'd prefer not to do that.


I think our best bet will be to create some set of `protected` methods that can be overridden to control things.    I'd need to dig in and think about it to have something fleshed out.

**Comment by JoshLove-msft** [comment]
> That method is intentionally infrastructure. I don't believe it's appropriate to expose it for all custom implementations and I'd prefer not to do that.
> 
> I think our best bet will be to create some set of `protected` methods that can be overridden to control things. I'd need to dig in and think about it to have something fleshed out.

Sure, I should have said that we would need to expose some hook (not necessarily that method as-is) where implementers can implement their own tracing.

**Comment by jsquire** [comment]
> Sure, I should have said that we would need to expose some hook (not necessarily that method as-is) where implementers can implement their own tracing.

All good, that was what I was thinking.   It'll be interesting to brainstorm what kind of hooks we can add specific to this.   I think it may be the first time we've had to think about how to influence this kind of behavior.

**Comment by lmolkova** [comment]
It can be as simple as a flag on `EventProcessorOptions`, which implementations can pass in when they create `EventProcessor`. I assume `EventHubProcessorClient` can change the value of this flag.

E.g. `EventProcessorOptions.DisableTracing` (false by default).

**Comment by JoshLove-msft** [comment]
> It can be as simple as a flag on `EventProcessorOptions`, which implementations can pass in when they create `EventProcessor`. I assume `EventHubProcessorClient` can change the value of this flag.
> 
> E.g. `EventProcessorOptions.DisableTracing` (false by default).

IMO, it should be more hidden than a public option considering that the main use case would be to set the option in one of our types, i.e. not really a customer use case. A protected method would be more hidden from users.
