### ISSUE TITLE
[FormRecognizer] StartRecognizeInvoicesCanParseMultipageForm(True) failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#31934]
FormRecognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
> Status: 401 (PermissionDenied)
> ErrorCode: 401
> 
> Content:
> {"error":{"code":"401","message":"Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}
> 
> Headers:
> apim-request-id: 71097d57-d3c6-4632-b099-9d68c5e7e25c
> Date: Thu, 20 Oct 2022 06:48:01 GMT
> Content-Length: 224
> Content-Type: application/json
> 
> 
> Stack trace
>    at Azure.AI.FormRecognizer.FormRecognizerRestClient.GetAnalyzeInvoiceResultAsync(Guid resultId, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/FormRecognizerRestClient.cs:line 1106
>    at Azure.AI.FormRecognizer.Models.RecognizeInvoicesOperation.Azure.Core.IOperation<Azure.AI.FormRecognizer.Models.RecognizedFormCollection>.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient/RecognizeInvoicesOperation.cs:line 153
>    at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 260
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 87
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 79
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 202
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 242
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 177
>    at Azure.AI.FormRecognizer.Models.RecognizeInvoicesOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient/RecognizeInvoicesOperation.cs:line 111
>    at Azure.AI.FormRecognizer.Tests.RecognizeInvoicesLiveTests.StartRecognizeInvoicesCanParseMultipageForm(Boolean useStream) in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/RecognizeInvoicesLiveTests.cs:line 297
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1931885&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Transient issue. Not happening anymore.
