### ISSUE TITLE
[Eventhub] ConsumerCanReadFromEnqueuedTime failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#31933]
Eventhub nightly test runs are failing with:

> Error message
> The event with custom identifier [60b0e740-353e-4fc4-89a7-e7c4e2a78f56] was not processed.
> Expected: True
> But was:  False
> 
> 
> Stack trace
>    at Azure.Messaging.EventHubs.Tests.EventHubConsumerClientLiveTests.ConsumerCanReadFromEnqueuedTime() in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Consumer/EventHubConsumerClientLiveTests.cs:line 900
>    at Azure.Messaging.EventHubs.Tests.EventHubConsumerClientLiveTests.ConsumerCanReadFromEnqueuedTime() in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Consumer/EventHubConsumerClientLiveTests.cs:line 903
>    at Azure.Messaging.EventHubs.Tests.EventHubConsumerClientLiveTests.ConsumerCanReadFromEnqueuedTime() in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Consumer/EventHubConsumerClientLiveTests.cs:line 906
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1932630&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
This is known and already being investigated.
