### ISSUE TITLE
[ContainerRegistry] CanGetManifestListProperties failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#31932]
ContainerRegistry nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 404 (Not Found)
> 
> Content:
> {"errors":[{"code":"TAG_UNKNOWN","message":"the specified tag does not exist"}]}
> 
> Headers:
> Connection: keep-alive
> Access-Control-Expose-Headers: REDACTED
> Docker-Distribution-Api-Version: REDACTED
> Strict-Transport-Security: REDACTED
> X-Content-Type-Options: REDACTED
> X-Ms-Correlation-Request-Id: REDACTED
> Content-Length: 81
> Content-Type: application/json; charset=utf-8
> Date: Wed, 19 Oct 2022 18:43:58 GMT
> Server: openresty
> 
> 
> Stack trace
>    at Azure.Containers.ContainerRegistry.ContainerRegistryRestClient.<GetTagPropertiesAsync>d__35.MoveNext() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Generated\ContainerRegistryRestClient.cs:line 749
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.Containers.ContainerRegistry.RegistryArtifact.<GetDigestAsync>d__17.MoveNext() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Artifact\RegistryArtifact.cs:line 107
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.Containers.ContainerRegistry.RegistryArtifact.<GetManifestPropertiesAsync>d__15.MoveNext() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Artifact\RegistryArtifact.cs:line 81
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.<CanGetManifestListProperties>d__2.MoveNext() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\tests\RegistryArtifactLiveTests.cs:line 30
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1930373&view=results

@jsquire for notification.

**Comment by pallavit** [comment]
Closing this issue against - https://github.com/Azure/azure-sdk-for-net/issues/32948 to fix the race conditions we have.
