### ISSUE TITLE
[QUERY] No Clear path to create a Function app in Azure.ResourceManager.AppService

### ISSUE THREAD

**Issue by BrettGoreham** [Azure/azure-sdk-for-net#31931]
### Library name and version

 Azure.ResourceManager.AppService

### Query/Question

Hello, Is it possible to create a function app in this library as it was in the library it replaced (Microsoft.Azure.Management.AppService.Fluent;)

the sample of the project online do not cover the usecase of creating an app service or a function app 
both here https://github.com/Azure-Samples/azure-samples-net-management/tree/master/samples
and
https://learn.microsoft.com/en-us/samples/browse/?branch=master&languages=csharp&term=managing%20using%20Azure%20.NET%20SDK&terms=managing%20using%20Azure%20.NET%20SDK

lack the information that used to be found here 
https://github.com/Azure/azure-libraries-for-net/blob/master/Samples/AppService/ManageFunctionAppBasic.cs

Thanks for any tips or help!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @BrettGoreham, sorry for the slow response. You can use this [method](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/websites/Azure.ResourceManager.AppService/src/Generated/WebSiteCollection.cs#L75) to create the function app if you are using Azure.ResourceManager.AppService. And back to the sample question, we are still working on providing more samples in our SDK, sorry for your inconvenience.
