### ISSUE TITLE
[BUG] x-ms-version header not supported by Blob Service

### ISSUE THREAD

**Issue by UnleashMayhem** [Azure/azure-sdk-for-net#31940]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Describe the bug

After updating from version 12.13.0 to 12.14.1, our calls to all blob containers in one resource group are failing. There are no problems when reverting to 12.13.0

The same package works correctly for other storage accounts in different resource groups.

Appears similar to this issue: #29098

Is it possible the latest Storage service version is not rolled out to all Storage Accounts in Azure?

### Expected behavior

I would expect the call to not fail due to a package update.

### Actual behavior

Error in FunctionApp:

![image](https://user-images.githubusercontent.com/963489/197176557-32d54b9e-4f6a-4788-a3d6-61148e00d032.png)

Plain text error message (from AppService):

The value for one of the HTTP headers is not in the correct format.
RequestId: 6eab0834-301e-00de-2824-e592af000000
Time: 2022-10-21T08:08:11.5522799Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Additional Information:
HeaderName: x-ms-version
HeaderValue: 2021-10-04

InvalidHeaderValue
The value for one of the HTTP headers is not in the correct format.
RequestId: 6eab0834-301e-00de-2824-e592af000000
Time: 2022-10-21T08:08:11.5522799Z
x-ms-version 2021-10-04

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 6eab0834-301e-00de-2824-e592af000000
Date: Fri, 21 Oct 2022 08:08:10 GMT
Content-Length: 329
Content-Type: application/xml

### Reproduction Steps

Sample code:

```
var blobContainerClient = new BlobContainerClient(settings.ConnectionString, settings.ContainerName, new BlobClientOptions());
await blobContainerClient.CreateIfNotExistsAsync();
```

### Environment

.NET 6 AppService and Function App

IDE(s) Occurs when debugging in VS2022 and JetBrainsRider, and in the cloud environment

**Comment by Etiennepicard** [comment]
I had the same issue when running my project's tests  (which calls azurite) after trying to update from 12.12.0 to 12.14.1

**Comment by amnguye** [comment]
For the original poster, looks like on the storage service side we need to check if that version hasn't reached that storage account / resource group. We are in contact with the service to make sure that this gets resolved soon.

As for those using Azurite, looks like this is has been an issue before where the SDK updated the service version before Azurite did.

As for both issues, a mitigation we recommend downgrading to 12.13.0 to prevent the `InvalidHeaderValue` error from popping up. I would recommend opening up an issue in Azurite as they need to eventually support this service version.
https://github.com/Azure/Azurite/issues
cc @blueww for Azurite.

Apologies for any inconvenience this may have caused.

**Comment by navba-MSFT** [comment]
@UnleashMayhem Could you please confirm if your storage account region is West Europe ? If Yes, I tried to re-create the same issue by using the `x-ms-version: 2021-10-04` and it worked fine for Blob operations. Could you please confirm if you are still facing the same issue ? Awaiting your reply.

**Comment by amnguye** [comment]
The issue has been resolved on the storage service side, please tag my github alias if we should unresolve.

As for the Azurite issue, we saw that they already support service version 2021-10-04 in the latest version of Azurite so please let us know if there's an issue with Azurite still.

**Comment by blueww** [comment]
@Etiennepicard 

Azurite already support API version 2021-10-04 on 3.19.0 and later, about 2 months ago.
Please check the Azurite version, and upgrade it if necessary.

BTW, you can also start Azurite with `--skipApiVersionCheck`, so Azurite will fail since API version not support. See more details in https://github.com/Azure/azurite#skip-api-version-check

**Comment by seanmcc-msft** [comment]
@UnleashMayhem, would it be possible for you to provide the storage account name?  We would like to verify that this issue has been fixed.
