### ISSUE TITLE
[QUESTION] Claiming partition delayed by ~2.5min

### ISSUE THREAD

**Issue by MO2k4** [Azure/azure-sdk-for-net#31941]
### Library name and version

Microsoft.Azure.WebJobs.SDK.EventHubs.Extension 5.1.2

### Query/Question

Hey 👋

we have noticed a delay when we're deploying our application. We deploy our app to a cluster, were it is currently running as a single instance and handles two partitions. When the new instance comes up, it claims one partition. After roughly 2.5min the second partition is claimed. We are seeing the same behavior if the function is scaled.

We are working in a real time scenario, where we need the messages to be processed as fast as possible. 

1. Is there a way to get this process speed up?
2. How can we configure PartitionOwnershipExpirationInterval?
3. Is there a way to recognize, if a partition is currently claimed by a dead instance?
4. Is there a way to release the partition ownership on function shutdown in scale down?

### Environment

Azure AKS
KEDA for scaling dependent on message count

**Comment by jsquire** [comment]
Hi @MO2k4.   Thank you for reaching out and we regret that you're experiencing difficulties.    What I believe that you're seeing is that the old instance was not stopped and, therefore, did not surrender ownership.  The other processors will continue to see it as active and honor it's partition ownership until the `PartitionOwnershipInterval` has elapsed.   After that period, the old instance will be viewed as "dead" and its work will be redistributed.

To answer your questions:

1. Yes.  If you explicitly stop the old processor by calling `StopProcessingAsync`, it will relinquish ownership and allow the new instance to understand what partitions are unowned and that it should claim them.

2. Please see: [Event Processor Configuration](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/samples/Sample02_EventProcessorConfiguration.md#influencing-load-balancing-behavior).

3. Yes.  The best way to do this is to explicitly invoke `StopProcessingAsync` on the "dead" instance; that will cause it to surrender ownership.  For a processor that is not stopped, this is governed by the `PartitionOwnershipInterval`.   For a processor to be considered "dead" is must own no partitions where the ownership has been renewed more recently than the ownership expiration interval.    

4. Yes.  When `StopProcessingAsync` is invoked, the processor will surrender ownership of all partitions.  This allows other instances to immediately see them as unowned and begin claiming them.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by MO2k4** [comment]
Thanks for the fast response @jsquire 

How can we call this StopProcessingAsync on a container run Azure Function which is scaled via KEDA?

We did tried another approach:

Scale to one instance and wait for this instance to retrieve both partitions.

But then this happened:

| timestamp | message |
| ---------- | --------- |
| 10/21/2022, 2:58:57.542 PM | Starting a new event processor instance with identifier 'a0137509-e682-44ff-9412-604e4755ac4e' for Event Hub: hub-name and Consumer Group: $Default. |
| 10/21/2022, 2:58:59.294 PM | Current ownership count is 0. (Identifier: 'a0137509-e682-44ff-9412-604e4755ac4e') |
| 10/21/2022, 2:58:59.295 PM |Unclaimed partitions: '0, 1'. |
| 10/21/2022, 2:58:59.300 PM | Attempting to claim ownership of partition '1'. |
| 10/21/2022, 2:58:59.794 PM | The new event processor instance with identifier 'a0137509-e682-44ff-9412-604e4755ac4e' for Event Hub: hub-name and Consumer Group: $Default has c ompleted starting. |
| 10/21/2022, 2:58:59.892 PM | Current ownership count is 1. (Identifier: 'a0137509-e682-44ff-9412-604e4755ac4e') |
| 10/21/2022, 2:58:59.893 PM |Unclaimed partitions: '0'. |
| 10/21/2022, 2:58:59.893 PM | Attempting to claim ownership of partition '0'. |
| 10/21/2022, 2:58:59.999 PM | Current ownership count is 2. (Identifier: 'a0137509-e682-44ff-9412-604e4755ac4e') |
| 10/21/2022, 2:59:22.770 PM | An exception occurred while receiving events for Event Hub: hub-name (Consumer Group: '$Default', Partition Id: '1'); Operation Id: '9703fa0e-48e2-4 26b-a2b6-7eb2a47a5c81'. Error Message: 'New receiver 'P1-9107a2bd-8160-4b6a-a4d6-ee3add60d903' with higher epoch of '0' is created hence current receiver  'P1-a0137509-e682-44ff-9412-604e4755ac4e' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:c28ba34700006a42001a24d663529793_G9_B1, SystemTracker:eh-name:eventhub:hub-name~32766|$default, Timestamp:2022-10-21T12:59:22 (hub-name)' |
| 10/21/2022, 2:59:22.772 PM |An exception occurred while processing events for partition '1' by processor instance with identifier 'a0137509-e682-44ff-9412-604e4755ac4e' for Event Hub: hub-name and Consumer Group: $Default. Error Message: 'New receiver 'P1-9107a2bd-8160-4b6a-a4d6-ee 3add60d903' with higher epoch of '0' is created hence current receiver 'P1-a0137509-e682-44ff-9412-604e4755ac4e' with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:c28ba34700006a42001a24d663529793_G9_B1, SystemTracker:eh-name:eventhub:hub-name~32766|$default, Timestamp:2022-10-21T12:59:22 (hub-name)' |
| 10/21/2022, 2:59:29.943 PM |Current ownership count is 1. (Identifier: 'a0137509-e682-44ff-9412-604e4755ac4e') |
| 10/21/2022, 2:59:59.943 PM |Current ownership count is 1. (Identifier: 'a0137509-e682-44ff-9412-604e4755ac4e') |
| 10/21/2022, 3:00:29.946 PM | Current ownership count is 1. (Identifier: 'a0137509-e682-44ff-9412-604e4755ac4e') |
| 10/21/2022, 3:01:29.943 PM | Current ownership count is 1. (Identifier: 'a0137509-e682-44ff-9412-604e4755ac4e') |
| 10/21/2022, 3:01:29.975 PM | Current ownership count is 2. (Identifier: 'a0137509-e682-44ff-9412-604e4755ac4e') |

**Comment by jsquire** [comment]
That pattern of logs confirms there are two processors actively running.  Both partitions were owned by one instance and then the second stole one.   The last entry makes me wonder if they're fighting over a partition, which would happen if they were not configured to use the same Storage container.

> How can we call this StopProcessingAsync on a container run Azure Function which is scaled via KEDA?

That is not a question that I can answer.   The Event Hubs trigger will explicitly call `StopProcessingAsync` on its processor when the trigger itself is stopped.   The Functions runtime is responsible for doing this and does so when running in the Azure Functions environment.   I cannot speak to how KEDA and Kubernetes interact with the runtime, nor the Functions runtime itself.

@alrod, @mattchenderson :  Do you have insight that you're able to share, or a suggestion where we could seek further assistance?

**Comment by MO2k4** [comment]
Strange i am very sure, that at this time there was only one scaled instance running :-/

**Comment by jsquire** [comment]
Is it possible that there's another processor instance running somewhere else that is pointed at the same Event Hub and uses the $Default consumer group?

**Comment by jsquire** [comment]
That seems to point to the other Function instance still running and would seem to support the theory that something in the infrastructure is not calling `StopAsync` on the trigger's listener.   The folks that I looped in above from the Functions team will hopefully be able to shed some light there.

**Comment by MO2k4** [comment]
I think i got it now working

1. Use CancellationToken for correct shutdown of the host
2. Use FixedDelayRetry for correct handling of the checkpoints
3. Configure LoadBalancingUpdateInterval through host.json to 20sec instead of 30sec, so that the load balancing is faster triggered

I will try tomorrow again to see if anything else is popping up. Thanks for your help @jsquire

**Comment by MO2k4** [comment]
We finally got it! The azure function running inside a AKS in a docker container don't recognize the termination.

Thanks for your help, i will open a new ticket in the docker image repository

**Comment by jsquire** [comment]
Glad to hear that you were able to get to the bottom of things!

**Comment by MO2k4** [comment]
i anyone lands here via google the final result is here => [azure-functions-docker/#677](https://github.com/Azure/azure-functions-docker/issues/677)

1. Add CancellationToken
2. Add FixedDelayRetry
3. Add custom start.sh
4. Adapt Dockerfile

hf :-)

this way there is no need to configure the intervals for load balancing or partition expiration 8-)
