### ISSUE TITLE
Accessing connection string via key vault

### ISSUE THREAD

**Issue by phatcher** [Azure/azure-sdk-for-net#31962]
To use managed identity to authenticate to ServiceBus, the connection string is of the form "<connectionname>__fullyQualifiedNamespace".

For deployment, best practice is to put sensitive items such as connection string into key vault, which doesn't support underscore as a valid secret name character (see [Secret Names do not support special characters](https://feedback.azure.com/d365community/idea/8b46339b-f624-ec11-b6e6-000d3a4f0da0)) - this has been open since 2020.

Can we have additional support for "-" e.g.  "<connectionname>-fullyQualifiedNamespace" (not -- since this is used as a hierarchy separator in key vault)

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6c3abb07-f36b-422e-49e9-c35ac5aeed91
* Version Independent ID: 0fc730dd-f0d9-c9d0-fdb0-57de237dad7c
* Content: [Azure WebJobs Service Bus client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-gb/dotnet/api/overview/azure/Microsoft.Azure.WebJobs.Extensions.ServiceBus-readme?view=azure-dotnet#managed-identity-authentication)
* Content Source: [api/overview/azure/latest/microsoft.azure.webjobs.extensions.servicebus-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/microsoft.azure.webjobs.extensions.servicebus-readme.md)
* Service: **servicebus**
* GitHub Login: @JoshLove-msft
* Microsoft Alias: **jolov**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @phatcher,
You should be able to use `:` or `/` as a separator in the key name.
This is mentioned in the [Note](https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2#connect-to-service-bus-in-your-function-app) in the Functions Identity docs.

**Comment by t-test-t** [comment]
xF#+

**Comment by phatcher** [comment]
/unresolve

@JoshLove-msft But key vault only allows names with `[0-9a-zA-Z-]`, so I can't use either `:` or `\` as part of the secret name.

Thought of the standard `--` separator, but this represents hierarchy, so I don't imagine it working.

**Comment by JoshLove-msft** [comment]
Have you tried using the Key Vault hierarchy separator, `--`? The idea is that the double underscore is supposed to represent a sub setting of the connection, e.g.:
```
Connection__fullyQualifiedNamespace: 
Connection__credential: 
```

So I think the equivalent for KeyVault would be:
```
Connection--fullyQualifiedNamespace: 
```

**Comment by phatcher** [comment]
@JoshLove-msft Thanks, that works

**Comment by JoshLove-msft** [comment]
Glad to hear it. I'll close out the issue now - feel free to reopen if you have further questions.
