### ISSUE TITLE
[BUG] "Azure.Storage.Files.Shares 12.12.0" will download Azure file to a local empty file, if "ChecksumAlgorithm=Auto"

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#31960]
### Library name and version

Azure.Storage.Files.Shares 12.12.0

### Describe the bug

Use following code to dowload an azure file to local file, the local file will be 0 size no matter how big the Azure file is.
This issue happen when use `ShareFileDownloadOptions.TransferValidation.ChecksumAlgorithm=Auto`, it doesn't happen when not set `ShareFileDownloadOptions.TransferValidation`.

After look at SDK code, it looks the error should be related with https://github.com/Azure/azure-sdk-for-net/blob/0abd3494404325324d1f06a19b842bd4e2f64d87/sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs#L2252
When enable AutoValidateChecksum, the downloaded content (stream) to be copied to readDestStream, so the position of the download output stream is changed. I notice the  readDestStream will be set to stream later, but not work so well. In my test when copy the downloaded content from the download output, will still get empty content.

##### repro code
```c#
ShareFileClient fileClientToDownload = <code to prepare the file client>;
string targetFile = @"c:\temp\tempfile";

using (FileStream stream = System.IO.File.OpenWrite(targetFile))
                            {
                                stream.SetLength(0);
                                long contentLenLeft = fileClientToDownload.GetProperties().Value.ContentLength;
                                long downloadOffset = 0;
                                ShareFileDownloadOptions downloadOptions = new ShareFileDownloadOptions()
                                {
                                    TransferValidation = new global::Azure.Storage.DownloadTransferValidationOptions()
                                    {
                                        ChecksumAlgorithm = global::Azure.Storage.StorageChecksumAlgorithm.Auto
                                    }
                                };
                                while (contentLenLeft > 0)
                                {
                                    long contentSize = contentLenLeft < size4MB ? contentLenLeft : size4MB;
                                    downloadOptions.Range = new HttpRange(downloadOffset, contentSize);
                                    ShareFileDownloadInfo download = fileClientToDownload.Download(downloadOptions);
                                    download.Content.CopyTo(stream);
                                    downloadOffset += contentSize;
                                    contentLenLeft -= contentSize;
                                }
                            }
```

### Expected behavior

The Azure file can be downloaded to a local file with same content successfully.

### Actual behavior

the downloaded file is always empty (size = 0)

### Reproduction Steps

See the above code.

### Environment

d:\code\PSH_Dev>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.402\

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  3.1.424 [C:\Program Files\dotnet\sdk]
  6.0.110 [C:\Program Files\dotnet\sdk]
  6.0.305 [C:\Program Files\dotnet\sdk]
  6.0.402 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.
