### ISSUE TITLE
[BUG] client_filters missing null check on FeatureFlagConfigurationSetting json deserialization

### ISSUE THREAD

**Issue by walterstypula** [Azure/azure-sdk-for-net#31969]
### Library name and version

Azure.Data.AppConfiguration 1.2.0

### Describe the bug

When a feature flag has client_filters set to null. It will not deserialize the FeatureFlagConfigurationSetting and throw an InvalidOperationException.  This prevent further traversing of the configuration collection.

This defect also impacts the az cli.

![image](https://user-images.githubusercontent.com/1973060/197576398-93958cd4-3efc-4266-8c85-2732f024c04f.png)

This can happen when a 3rd party tool publishes feature flag. For example terraform.
https://github.com/hashicorp/terraform-provider-azurerm/issues/16329

### Expected behavior

A null value for client_filters should not prevent deserialization.

### Actual behavior

A null value for client_filters for any featureflag breaks deserialization preventing return any of azure application configuration setting using GetConfigurationSettings from traversing those feature flags.

### Reproduction Steps

1) Navigate to FeatureFlags within a target Azure App Configuration
2) Select any feature, and Click Advanced edit.
3) Set the client_filters json value to null.
4) Save your modification.
5) Access the target Azure App Configuration using ConfigurationClient.
6) Use the GetConfigurationSettings method to get a Pageable<ConfigurationSetting> object instance.
7) Call GetEnumerator() on the instance.

![image](https://user-images.githubusercontent.com/1973060/197576861-bb49f55a-7803-4aeb-ad36-377d9ea35c05.png)

**Comment by jsquire** [comment]
Hi @walterstypula.   Thank you for reaching out and we regret that you're experiencing difficulties.   I'm unclear from the issue which package is causing the error that you're seeing.   Would you be so kind as to share a small snippet of how you're creating the client?

**Comment by walterstypula** [comment]
Hi @jsquire, the source of the problem is in this file. 

[https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/appconfiguration/Azure.Data.AppConfiguration/src/FeatureFlagConfigurationSetting.cs line](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/appconfiguration/Azure.Data.AppConfiguration/src/FeatureFlagConfigurationSetting.cs#L239)

TryGetProperty returns the client_filters property with a value of null, which is expected per the setup for this bug. However, there's no null check on the value stored within clientFiltersProperty before calling EnumerateArray().

This is our code. As soon as we call any method that needs to iterate through the pageable it throws an invalid operation exception.
![image](https://user-images.githubusercontent.com/1973060/197646743-d4125766-aca0-4c21-9fcf-32cf508d3995.png)

Additional Info:
![image](https://user-images.githubusercontent.com/1973060/197647533-ce4dcd3a-7f39-4c27-a1e1-feb5cc0e5838.png)
![image](https://user-images.githubusercontent.com/1973060/197647751-b9f4fed6-7072-468a-860d-aa8821668618.png)

**Comment by jsquire** [comment]
Thank you for the additional context, @walterstypula.   I've triaged this over to the team member best able to assist.

**Comment by walterstypula** [comment]
I was about to open a PR with the following change.

if (conditionsProperty.TryGetProperty("client_filters", out var clientFiltersProperty) **&& clientFiltersProperty.ValueKind == JsonValueKind.Array**)

**Comment by nisha-bhatia** [comment]
Hi @walterstypula, a PR has been opened here (https://github.com/Azure/azure-sdk-for-net/pull/32253) to resolve this issue. In the Azure Portal, client_filters can be set to null. ![Screenshot 2022-11-01 220627](https://user-images.githubusercontent.com/67986960/199576134-3cec05df-7a52-4ff8-afdc-a0b72cc6863f.jpg)
A warning is shown but the value is accepted which later throws an exception in the deserialization. ![Screenshot 2022-11-02 113657](https://user-images.githubusercontent.com/67986960/199575361-1a4201a0-16e7-48c7-9f88-213e69c4006b.jpg) The PR adds a check for this case. Thanks

**Comment by ShivangiReja** [comment]
This issue has been fixed here: https://github.com/Azure/azure-sdk-for-net/pull/32253
