### ISSUE TITLE
How to use OR operator when querying blobs by tags / Find blobs by tags

### ISSUE THREAD

**Issue by cahribeiro** [Azure/azure-sdk-for-net#31963]
### Library name and version

Azure.Storage.Blobs 12.14.0.0

### Query/Question

I am trying to filter blobs by tags in Azure Blob storage using rest API with SAS token. 
I am able to retrieve the blobs with query using AND operator, but doesn't work with OR operator.
Error message:
```
<Code>InvalidQueryParameterValue</Code>
    <Message>Error parsing query at or near character position 43: unexpected &apos;OR&apos;
RequestId:db72bd27-801e-0060-5596-e773d3000000
Time:2022-10-24T10:48:23.2546238Z</Message>
```
the filter in "where" parameter is = 
@container='namecontainer' AND fieldTag1='A' AND fieldTag2='B' AND (fieldTag3='131' OR fieldTag3='158' OR fieldTag3='132')
note = the query is url encoded.

without the OR I am able to retrieve the blobs normally. 
Is there any available way to list the blobs by tag with conditional operator "OR" ?

**Comment by SaurabhSharma-MSFT** [comment]
@cahribeiro We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@cahribeiro I believe you are trying to use `FindBlobsByTagsAsync`  with expression filter.  
If that's the case OR is not supported in the expression filter.  Please refer to the documentation at [tagFilterSqlExpression](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.findblobsbytagsasync?view=azure-dotnet#parameters) 
> 
![image](https://user-images.githubusercontent.com/38112130/202184788-046600f7-c0e6-4a18-96dc-9d4d026d5bd1.png)

**Comment by SaurabhSharma-MSFT** [comment]
@cahribeiro We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
