### ISSUE TITLE
The remote server returned an error: (504) Gateway Timeout

### ISSUE THREAD

**Issue by abergs** [Azure/azure-sdk-for-net#3197]
Hey,
I think I ran into a throttle when using the Fluent Api.
Now i'm unable to authenticate, I instead receive the error above.

I'm running this code:
`
 IAzure azure = Azure
                .Configure()
                .Authenticate(auth)
                .WithSubscription("xxxx");
`

Should I save the IAzure instance as a Singleton? Now i'm creating new ones for different actions.
I'm running this code in a webapi, so every request generates about 1-5 new authentications depending on the call tree.

**Comment by martinsawicki** [comment]
probably an ASP.nET issue actually - there was a big fix that may have addressed this in v1.2 - pls reopen this issue if it still reproduces in the latest SDK.
