### ISSUE TITLE
[QUERY] Update Application Gateway with new SDK

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-net#31986]
### Library name and version

Azure.ResourceManager.Network 1.0.1

### Query/Question

How do I update an existing Application Gateway?

```
 ArmClient armClient = new(credentials);
            ResourceIdentifier resourceIdentifier = new ResourceIdentifier($"/subscriptions/{detection.ConnectionId}/resourceGroups/{detection.ResourceGroup}/providers/Microsoft.Network/applicationGateways/{detection.Name}");
            ApplicationGatewayResource applicationGatewayResource =
                armClient.GetApplicationGatewayResource(resourceIdentifier);
            applicationGatewayResource.Data.WebApplicationFirewallConfiguration.Enabled = true;
            applicationGatewayResource.Data.WebApplicationFirewallConfiguration.FirewallMode = ApplicationGatewayFirewallMode.Prevention;
await applicationGatewayResource.UpdateAsync(applicationGatewayResource);
```

This is the only `Update` method I can find anywhere related to app gateways, but this seems to only apply to updating tags on the resource expecting a `NetworkTagsObject`.

Any idea how I can update this Application Gateway?

### Environment

net6
Visual Studio 2022

**Comment by davidobrien1985** [comment]
The same also applies to `VirtualNetworkResource`. Only seems to update tags, nothing else.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by davidobrien1985** [comment]
Okay, figured it out.
It seems as if all the `CreateOrUpdate` methods have moved to the `...Collection` classes.

```
ApplicationGatewayCollection applicationGatewayCollection = armClient.GetResourceGroupResource(resourceGroupId).GetApplicationGateways();
            await applicationGatewayCollection.CreateOrUpdateAsync(WaitUntil.Started, applicationGatewayResource.Data.Name, applicationGatewayResource.Data);
```
