### ISSUE TITLE
Very slow: azure.WebApps.ListByResourceGroupAsync(resourceGroup) 

### ISSUE THREAD

**Issue by abergs** [Azure/azure-sdk-for-net#3199]
Calling the azure.WebApps.ListByResourceGroupAsync(resourceGroup) method is extremely slow?

Even though my code is running in Azure, it can easily take about 1-4 minutes to load. We have about 50 websites in that resource group.

What could be the cause of this?

**Comment by jianghaolu** [comment]
This is because when we load web apps, we also load app settings, connection strings, configurations that are attached to them. They are unfortunately all different API calls. So 50 websites would be at least 200 rest calls.

**Comment by abergs** [comment]
I see @jianghaolu. Is there anyway to speed this up? In many cases I'm just interested in the site existence and it's state and sometimes the appsettings.

**Comment by martinsawicki** [comment]
@jianghaolu sounds similar to an issue we discussed recently on the java side - is there an opportunity to load some of these things more lazily...

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#14
