### ISSUE TITLE
Monitor Readme issues

### ISSUE THREAD

**Issue by blow-hey** [Azure/azure-sdk-for-net#31994]
Section [link](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter#prerequisites)
![image](https://user-images.githubusercontent.com/112381413/197703777-b9bf23ef-a85b-40b0-aafc-db78d16cb053.png)

Reason: 
Clicking link `create an account` goes to a page that says: "This portal has been retired".
![image](https://user-images.githubusercontent.com/112381413/197704101-9a42d3b4-f70e-4b31-bb7e-5d22eccbedb0.png)

Suggestion:
 Replace with this link for "create an account" [link](https://azure.microsoft.com/en-us/get-started/azure-portal/)

@scottaddie , @jsquire ,@SameergMS, @srnagar for notification.

**Comment by t-test-t** [comment]
Xpf
