### ISSUE TITLE
[QUERY] How to update Network Security Group with new SDK

### ISSUE THREAD

**Issue by davidobrien1985** [Azure/azure-sdk-for-net#31996]
### Library name and version

Azure.ResourceManager.Network 1.0.1

### Query/Question

How are we supposed to update a network security group with a list of `DestinationAddressPrefixes`, `DestinationPortRanges`, `SourceAddressPrefixes` or `SourcePortRanges`?

This was possible in the old SDK, but now those properties seem to be `get` only.

### Environment

net6
VS2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @davidobrien1985, according to the [.NET design guideline](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values), we don't provide setter for the collection type, please call the Add() method to add values, you can see more details [here](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-collection-read-only-property-initialization) about how to initialize the collection read-only property.
