### ISSUE TITLE
VirtualMachines.List()/.ListByResourceGroup() timeout on Windows Server 2012 R2

### ISSUE THREAD

**Issue by allyjweir** [Azure/azure-sdk-for-net#3200]
# Problem Statement
Using certain methods in the Azure Fluent API only fail when we test against Windows Sever 2012 R2 hosted on Azure.

# Context
Trying to debug a suite of tests that interact with Azure's Compute services. The full suite works on developer's machines (tested across 3 Win10Pro machines). The tests however fail when run on our build machine (Server 2012R2 on Azure). The tests also fail on a fresh Server 2012R2 server on Azure.

We found that the following worked on both Win10 and Server 2012R2:
1. Creating an `IAzure` instance
2. Checking existance of Resource Groups using `ResourceGroups.CheckExistence(string)`
3. PowerShell `Get-AzureRmVm` command successfully lists VMs using the same credentials 

The following **did not** work on Server 2012R2:
1. Listing VMs using `VirtualMachines.ListByResourceGroup(string)`
2. Listing all VMs using `VirtualMachines.List()`

# Steps to reproduce

**I have created a minimum reproduction which can be found in [this repo](https://github.com/allyjweir/list-azure-vms).**

## On a Windows 10 machine
1. Clone minimum reproduction repository
2. Add required values in ListAzureVMs.cs and AzureHelper.cs (can find them all by searching for `secretvaluehere` and replacing as appropriate.)
3. Build
4. Run the test
5. See passing test

## On a Windows Server 2012 R2 machine
1. Repeat steps 1-4 followed previously on the Windows 10 machine.
2. See failing test

Any insight on this would be greatly appreciated!

**Comment by allyjweir** [comment]
Did some further research:

In our codebase, the xUnit test that checks retrieves the list of VMs (as replicated in the repo in initial issue) passes on our development machines. However, calling the _exact_ same code from a WebAPI Controller method (running IIS Express) and it times out.

We used Fiddler to intercept the HTTPS traffic and it shows by both methods that the correct response it actually received! However, the WebAPI controller method never returns successfully.

**Comment by martinsawicki** [comment]
@anuchandy my hunch right now is that that it's related to threading. We may have seen other similar "hangs" in an ASP.NET context, or other contexts with multi-threading restrictions. Could this be the same problem?

**Comment by allyjweir** [comment]
Perhaps worth clarifying how we are running the tests on the Windows Server 2012 R2 machine.

We are running them from inside Visual Studio 2017 using Test Explorer (connected to xunit.runners.visualstudio), so very similar (if not exact) as the dev environment on Windows 10 (where it passes).

Have also tried running the tests using `VSTest.exe` through VSTS's Build Pipelines, these also hang.

**Comment by martinsawicki** [comment]
there was a significant fix for multi-threaded ASP.NET scenarios done in v1.2 (fixing a bunch of hang situations), so pls see if this is still reproducible in the latest and reopen the issue as needed. Thanks!
