### ISSUE TITLE
Adding Test Coverage to DevTestLab SDK

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3201]
Add scenario tests for DevTestLabs, that will tests
- Operations for devTestLabs
- Models for devTestLabs

Test coverage is required prior to release of the SDK.

**Comment by joerage** [comment]
The Azure Lab Services team is tracking this work internally. We will be adding scenario tests along with our new SDK version once we publish it.

**Comment by AlexGhiondea** [comment]
Closing this for now. Feel free to re-open.
