### ISSUE TITLE
UpdateAsync try to re-add nested object

### ISSUE THREAD

**Issue by JordaanMe** [Azure/azure-sdk-for-net#3202]
I have a data model that consists of appointments, and patients. Every appointment has a patient property. When I make a change to an appointment and then call UpdateAsync, I get the following error:

The operation failed due to a conflict: 'Violation of PRIMARY KEY ...' . Cannot insert duplicate key in object

It's pretty clear that azure is trying to re-add the patient to the patients table whenever I modify the appointment. Why? How do I avoid this?

**Comment by shahabhijeet** [comment]
@JordaanMe Can you give me a repro that I can see this particular error.
For e.g. give us the code as well as which Azure SDK library you are trying to use.

**Comment by markcowl** [comment]
Closing for lack of response.  @JordaanMe  Please reopen if this recurs and include a repro
