### ISSUE TITLE
.PersistKeysToAzureBlobStorage() (& .ProtectKeysWithAzureKeyVault()) should follow the options pattern

### ISSUE THREAD

**Issue by lakeman** [Azure/azure-sdk-for-net#32020]
### Library name

Azure.Extensions.AspNetCore.DataProtection.Blobs

### Please describe the feature.

The current api design of `PersistKeysToAzureBlobStorage` requires creating a `BlobClient` before building the application host. eg in `ConfigureServices`. 

Every asp.net service that follows the [options pattern](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-6.0) allows for lazy configuration on first use, perhaps based on other end user services. 

For example, I might wish to define my own configuration service like;
```c#
public class ConfigureDataProtection : IConfigureOptions<KeyManagementOptions>
{
    public ConfigureDataProtection(... dependencies ...)
    {
        // TODO
    }

    public void Configure(KeyManagementOptions options)
    {
        var blobClient = // use some other service to obtain configuration
        options.XmlRepository = new AzureBlobXmlRepository(blobClient);
    }
}
```
But `AzureBlobXmlRepository` is internal. The only public api is `AzureStorageBlobDataProtectionBuilderExtensions.PersistKeysToAzureBlobStorage` which forces me to create and configure the blob client before building the generic host.

Even if my use case doesn't involve starting the host. For example, reusing EF Core configuration & services to migrate a database using the same executable.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
At its core, this request seems to be "can we please make the `AzureBlobXmlRepository` type public, which is something being explored in #37526.  We'll leave this as a backlog item for now, pending the outcome of that pull request.

**Comment by jsquire** [comment]
@AlexanderSher:  This is another example of an extensions type that we should consider opening up to `public`

**Comment by AlexanderSher** [comment]
Hi @lakeman, there is a new overload that doesn't force you to create a `BlobClient` immediately. Will it work in your case:
```cs
services
    .AddDataProtection()
    .PersistKeysToAzureBlobStorage(_ => /*Create blob client*/);
```
