### ISSUE TITLE
Expose an API to log out the current account and clean up any related cached credential

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#32048]
related to #31498
related to https://github.com/Azure/azure-sdk-for-net/issues/31844

**Comment by calebkiage** [comment]
Hello @christothes, will confidential clients like client certificate have support for log out as well?

**Comment by calebkiage** [comment]
@christothes, I think this is a different scenario. The original request was about clearing the on-disk cache. The API could be named something different that communicates the behavior. Is the policy something an SDK user sets or is it an internal implementation detail?

**Comment by christothes** [comment]
Are you referring to a scenario where the credential is constructed with [TokenCachePersistenceOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md#using-the-default-token-cache) ?

**Comment by calebkiage** [comment]
@christothes, yes. That's right. having a way to tell Azure Identity that the token cache should be cleared would be useful for the product I'm working on. At the moment, I've had to apply a hack of constructing an MSAL public client, registering a token cache that matches what Azure Identity creates and removing accounts from it.

**Comment by christothes** [comment]
Given that you are going to re-construct the token to clear it, would using the [named token cache work](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/TokenCache.md#using-a-named-token-cache)? When re-creating the credential, you would just choose a new unique name.

**Comment by calebkiage** [comment]
We use a named token cache already. Won't creating new named caches every time litter the user's folder with unused token cache files?

**Comment by FehintolaObafemi** [comment]
#31844 
 
 Here is the link to the line of code referenced in this issue.
 
 https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/eb0f42e4f01aecece5abe75b5129936c094c7e24/src/Authentication/Authentication.Core/Utilities/AuthenticationHelpers.cs#L109

**Comment by FehintolaObafemi** [comment]
#31844

**Comment by christothes** [comment]
> We use a named token cache already. Won't creating new named caches every time litter the user's folder with unused token cache files?

Actually - thinking about this further - as long as we aren't passing an `AuthenticationRecord` to the new credential instance, it should be fine that there is still a cache file present. Without the record, the interactive flow should be taken even with a populated cache.
