### ISSUE TITLE
Azure.Data.Tables, Azure Cosmos DB for Table, and AAD authentication [BUG]

### ISSUE THREAD

**Issue by seesharprun** [Azure/azure-sdk-for-net#32058]
### Library name and version

Azure.Data.Tables 12.6.1

### Describe the bug

The steps outlined in the [samples content of the Azure.Data.Tables library](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample0Auth.md#tokencredential) do not work. Specifically, I have been unable to use **Azure.Identity** classes as a tokenCredential with either the **TableServiceClient** or **TableClient** classes.

For example, I cannot use **DefaultAzureCredential** or other credential classes like **AzureCliCredential** as the tokenCredential classes when connecting to or creating a table in Azure Cosmos DB for Table.

I did notice that the Markdown file mentions Azure Storage quite a bit, so it may have been unintentionally copied from Azure Storage to the Azure Cosmos DB variant of the library. I couldn't find anything explicitly stated if AAD auth is supported or not for the SDK or the server-side service.

### Expected behavior

Azure Cosmos DB for Table SDK allows AAD authentication as outlined on the [relevant Markdown file](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample0Auth.md).

### Actual behavior

Requests fail with this error:

```
Unhandled exception. Azure.RequestFailedException: Authorization header doesn't confirm to the required format. Please verify and try again.
ActivityId: 1002b36f-d524-4a68-8c3f-fd3f59dc3175, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.19041.0
RequestID:1002b36f-d524-4a68-8c3f-fd3f59dc3175

Status: 401 (Unauthorized)
ErrorCode: Unauthorized

Content:
{"odata.error":{"code":"Unauthorized","message":{"lang":"en-us","value":"Authorization header doesn't confirm to the required format. Please verify and try again.\r\nActivityId: 1002b36f-d524-4a68-8c3f-fd3f59dc3175, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.19041.0\nRequestID:1002b36f-d524-4a68-8c3f-fd3f59dc3175\n"}}}


Headers:
Date: Thu, 27 Oct 2022 12:50:57 GMT
Transfer-Encoding: chunked
Content-Type: application/json; odata=fullmetadata

   at Azure.Data.Tables.TableServiceClient.CreateTableIfNotExistsAsync(String tableName, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\username\Demos\project\Program.cs:line 11
   at Program.<Main>(String[] args)
```

### Reproduction Steps

1. Ensure you have .NET 6 or later installed: ``dotnet --version``
1. Ensure that you already have an Azure Cosmos DB for Table account.
1. Create a new .NET project: ``dotnet new console``
1. Add relevant NuGet projects: ``dotnet add package Azure.Identity`` & ``dotnet add package Azure.Data.Tables``
1. In the **Program.cs** file, replace the contents with this code:
    ```csharp
    using Azure.Identity;
    using Azure.Data.Tables;
    
    string accountName = "<cosmos-db-api-for-table-account-name>";
    
    TableServiceClient client = new(
        endpoint: new Uri($"https://{accountName}.table.cosmos.azure.com:443/"),
        tokenCredential: new DefaultAzureCredential()
    );
    
    await client.CreateTableIfNotExistsAsync("cosmicworks");
    
    TableClient tableClient = new TableClient(
        endpoint: new Uri($"https://{accountName}.table.cosmos.azure.com:443/"),
        tableName: "adventureworks",
        tokenCredential: new DefaultAzureCredential()
    );
    
    await tableClient.CreateIfNotExistsAsync();
    ```
1. Replace the placeholder for the account name with the name of your account.
1. Run the project: ``dotnet run``
1. Observe the error message.

### Environment

| | |
| --- | --- |
| **Host OS** | Windows 11 Enterprise Version 22H2 |
| **.NET Runtime** | 6.0.305 |
| **IDE** | Visual Studio Code Version 1.72.2 |

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @seesharprun - TokenCredential authentication only works with Azure Storage table endpoints. The sample does state this, however, perhaps it could be more prominent. 

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/tables/Azure.Data.Tables/samples/Sample0Auth.md#tokencredential

> Azure Tables provides integration with Azure Active Directory (Azure AD) for identity-based authentication of requests to the Table service when targeting a **_Storage endpoint_**.

**Comment by seesharprun** [comment]
This helps a bit. You are right that the sample states "targeting a Storage endpoint," but it's pretty easy for someone like myself to not infer that it means a negative that the sample does not support Azure Cosmos DB. 

Thanks for clearing that up.
