### ISSUE TITLE
Support running test projects targetting multiple frameworks

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-net#3205]
Since libraries target net452 and netstandard1.4, we should have tests that exercise both of these codepaths. Especially in cases where `#if` was used in the code.

The test pass on the CI job should support and run tests with multiple framework targets. So for example if a test targets `net452` and `netcoreapp1.1` and has 17 tests, the test pass should run 17 x 2 = 34 tests.

My team recently had a bug because we didn't catch an issue in our `netstandard` that wasn't there in the `net452` implementation (even though the code was exactly the same and in this case we didn't even have `#if` in the code.

**Comment by matthchr** [comment]
See #3170 for more details about the issue we found.

**Comment by matthchr** [comment]
@shahabhijeet

**Comment by shahabhijeet** [comment]
Done
#3209
