### ISSUE TITLE
Missing pipeline coverage for autorest.csharp updates

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#32064]
#31790 broke Key Vault's sample, "sharelink". @weshaggard, @sima-zhu, @JoshLove-msft I know you've been making changes with the pipelines, but seems in those changes we no longer build as much - like the Key Vault samples that used to build. Once this change was merged, the `net - keyvault` and `net - keyvault - tests` pipelines started breaking. Maybe autorest updates should still be running all pipelines before merging? Seems we're missing coverage.

_Originally posted by @heaths in https://github.com/Azure/azure-sdk-for-net/issues/31790#issuecomment-1293937879_

**Comment by weshaggard** [comment]
We have switched to running the tests for all things that directly depend on Azure.Core in the core pipeline but we are not currently running samples there. I'm not entirely sure if we want to do that or not perhaps a conversation for the owners of core.

**Comment by heaths** [comment]
It may be rare enough not to worry about it, but probably worth a conversation with @JoshLove-msft, @christothes, and @m-nash. Not a high priority, here. I was more concerned about a lack of coverage, but you said it was just samples so I'm less concerned.

**Comment by jsquire** [comment]
//fyi:  @JimSuplizio.    I'm not sure if this is covered in the AutoRest CI validation that we've been discussing for Zinc.

**Comment by weshaggard** [comment]
That Autorest CI automation will be worked on by @hallipr not @JimSuplizio. However I don't think building samples is currently in scope for that work either.
