### ISSUE TITLE
Update packageref to Azure.Core in sharelink sample

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#32065]
PR #31790 added types which haven't shipped in Azure.Core yet. I was able to update the sharelink sample so that it at least builds in the repo using a `ProjectReference` to Azure.Core, but the out-of-repo configuration in _sharelink.csproj_ will need to be updated to the latest Azure.Core with the require `NullResponse<T>` once shipped.

**Comment by heaths** [comment]
Pulling back since Azure.Core should be shipping early November.

**Comment by heaths** [comment]
Might also consider switching back to a `PackageReference` for Azure.Core then as well, though this problem could happen again. That said, this problem hasn't happened before - at least, not in a long time that I can recall. @christothes, @JoshLove-msft what do you think? When building the sample in our repo e.g., nightlies, think it's better to use a ProjectReference?

**Comment by pallavit** [comment]
@heaths can we close this now? Nullable<T> has been released.

**Comment by heaths** [comment]
The work still needs to be done.
