### ISSUE TITLE
[BUG] Should print error and warning in sample code

### ISSUE THREAD

**Issue by wangyuantao** [Azure/azure-sdk-for-net#32067]
### Library name and version

Azure.AI.Language.Conversations

### Describe the bug

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/samples/Sample6_AnalyzeConversation_ConversationSummarization.md

The example code should handle the task/job success but no summary - has error/warning scenario.

![image](https://user-images.githubusercontent.com/98181/198383662-9013b3b4-36ab-4b38-8028-0147e0e6fad8.png)

### Expected behavior

The example code should handle the task/job success but no summary - has error/warning scenario.

### Actual behavior

Current sample code only print summary

### Reproduction Steps

send some invalid transcript so AI cannot generate summary

**Comment by wangyuantao** [comment]
Example of invalid transcript - just make it too short:
```
Agent: Hello, you're
```

result:

```json
{
    "jobId": "18bdd9f1-ef28-4cf1-9de7-0efafe764dbf",
    "lastUpdatedDateTime": "2022-10-27T19:53:06Z",
    "createdDateTime": "2022-10-27T19:53:05Z",
    "expirationDateTime": "2022-10-28T19:53:05Z",
    "status": "succeeded",
    "errors": [],
    "displayName": "Demo portal conversation analysis job",
    "tasks": {
        "completed": 1,
        "failed": 0,
        "inProgress": 0,
        "total": 1,
        "items": [
            {
                "kind": "conversationalSummarizationResults",
                "taskName": "ConversationalSummarizationTask task",
                "lastUpdateDateTime": "2022-10-27T19:53:06.2628173Z",
                "status": "succeeded",
                "results": {
                    "conversations": [
                        {
                            "summaries": [],
                            "id": "input_0",
                            "warnings": [
                                {
                                    "code": "GenerationFailure",
                                    "message": "Insufficient content to generate summary."
                                },
                                {
                                    "code": "GenerationFailure",
                                    "message": "No relevant summary could be generated."
                                },
                                {
                                    "code": "GenerationFailure",
                                    "message": "Insufficient content to generate summary."
                                },
                                {
                                    "code": "GenerationFailure",
                                    "message": "No relevant summary could be generated."
                                }
                            ]
                        }
                    ],
                    "errors": [],
                    "modelVersion": "latest"
                }
            }
        ]
    }
}
```

**Comment by heaths** [comment]
Could you clarify: on Teams, you said the customer wanted an example of error handling. Are you saying in this bug, though, that the sample code actually returns errors? If so, this was fixed a while ago in which the sample was updated to include the `role` and the recordings file from that sample/test shows it: https://github.com/Azure/azure-sdk-for-net/pull/31901/files#diff-9ed1b633a655be9976ea44349d9d7f5093c52756e8ca310b27c0dc97f4f3b4f8

Note, though: if you include `role` but hit an older version of the service, the same errors/warnings happen. This is a service problem, since the service should be ignoring properties it doesn't know about on older API versions.

**Comment by wangyuantao** [comment]
See Python SDK sample code do print out the errors and warnings:

https://github.com/Azure/azure-sdk-for-python/pull/27122/files

```
        # view result
        result = await poller.result()
        task_results = result["tasks"]["items"]
        for task in task_results:
            print(f"\n{task['taskName']} status: {task['status']}")
            task_result = task["results"]
            if task_result["errors"]:
                print("... errors occurred ...")
                for error in task_result["errors"]:
                    print(error)
            else:
                conversation_result = task_result["conversations"][0]
                if conversation_result["warnings"]:
                    print("... view warnings ...")
                    for warning in conversation_result["warnings"]:
                        print(warning)
                else:
                    summaries = conversation_result["summaries"]
                    print("... view task result ...")
                    for summary in summaries:
                        print(f"{summary['aspect']}: {summary['text']}")
```

while C# sample code only print summary:
```
foreach (JsonElement task in jobResults.GetProperty("tasks").GetProperty("items").EnumerateArray())
{
    JsonElement results = task.GetProperty("results");

    Console.WriteLine("Conversations:");
    foreach (JsonElement conversation in results.GetProperty("conversations").EnumerateArray())
    {
        Console.WriteLine($"Conversation: #{conversation.GetProperty("id").GetString()}");
        Console.WriteLine("Summaries:");
        foreach (JsonElement summary in conversation.GetProperty("summaries").EnumerateArray())
        {
            Console.WriteLine($"Text: {summary.GetProperty("text").GetString()}");
            Console.WriteLine($"Aspect: {summary.GetProperty("aspect").GetString()}");
        }
        Console.WriteLine();
    }
}
```

**Comment by wangyuantao** [comment]
> Could you clarify: on Teams, you said the customer wanted an example of error handling. Are you saying in this bug, though, that the sample code actually returns errors? If so, this was fixed a while ago in which the sample was updated to include the `role` and the recordings file from that sample/test shows it: https://github.com/Azure/azure-sdk-for-net/pull/31901/files#diff-9ed1b633a655be9976ea44349d9d7f5093c52756e8ca310b27c0dc97f4f3b4f8
> 
> Note, though: if you include `role` but hit an older version of the service, the same errors/warnings happen. This is a service problem, since the service should be ignoring properties it doesn't know about on older API versions.

The data in the sample code is good. Customer just need C# sample code print the errors/warnings for their bad data input, like Python SDK sample code.

**Comment by heaths** [comment]
I will try to get to it before we release, but it's not as high a priority. Fortunately, our samples are rendered from `main` so we can always update them later. We'd also accept a PR if your team wants to make the changes. They won't really differ from Python's.
