### ISSUE TITLE
[EventGrid]Microsoft.Azure.EventGrid.Tests.ScenarioTests.ScenarioTests.PublishEventsToTopic failing in nightly runs

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-net#32088]
EventGrid nightly test runs are failing with:

> Error message:
> System.NotSupportedException : Interactive Login is supported only in NET452 and above projects
> 
> Stack trace:
>  at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.Login() in /Users/runner/work/1/s/sdk/mgmtcommon/TestFramework/ClientRuntime.Azure.TestFramework/TestEnvironment.cs:line 327
>    at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.RecorderModeSettings() in /Users/runner/work/1/s/sdk/mgmtcommon/TestFramework/ClientRuntime.Azure.TestFramework/TestEnvironment.cs:line 251
>    at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment..ctor(String connectionString) in /Users/runner/work/1/s/sdk/mgmtcommon/TestFramework/ClientRuntime.Azure.TestFramework/TestEnvironment.cs:line 124
>    at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.get_TestFxEnvironment() in /Users/runner/work/1/s/sdk/mgmtcommon/TestFramework/ClientRuntime.Azure.TestFramework/MockContext.cs:line 44
>    at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.GetServiceClient[T](Boolean internalBaseUri, DelegatingHandler[] handlers) in /Users/runner/work/1/s/sdk/mgmtcommon/TestFramework/ClientRuntime.Azure.TestFramework/MockContext.cs:line 97
>    at Microsoft.Azure.EventGrid.Tests.TestHelper.EventGridManagementHelper.GetResourceManagementClient(MockContext context, RecordedDelegatingHandler handler) in /Users/runner/work/1/s/sdk/eventgrid/Microsoft.Azure.EventGrid/tests/TestHelper/EventGridManagementHelper.cs:line 57
>    at Microsoft.Azure.EventGrid.Tests.ScenarioTests.ScenarioTests.InitializeClients(MockContext context) in /Users/runner/work/1/s/sdk/eventgrid/Microsoft.Azure.EventGrid/tests/Tests/ScenarioTests.cs:line 28
>    at Microsoft.Azure.EventGrid.Tests.ScenarioTests.ScenarioTests.PublishEventsToTopic() in /Users/runner/work/1/s/sdk/eventgrid/Microsoft.Azure.EventGrid/tests/Tests/ScenarioTests.PublishEvents.cs:line 25

For more details check here:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1949636&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
This is a track one SDK which has been deprecated and is unlikely to be fixed.
