### ISSUE TITLE
[ContainerRegistry]CanGetManifestsOrdered failing in nightly runs

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-net#32087]
ContainerRegistry nightly test runs are failing with:

> Error message:
> Microsoft.Rest.Azure.CloudException : Long running operation failed with status 'BadRequest'.
> 
> Stack trace:
>  at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.CheckErrorStatusAndThrowAsync(HttpRequestMessage request, HttpResponseMessage response)
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.GetRawAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.UpdateResourceFromPollingUri(Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.Poll(Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.StartPollingAsync()
>    at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.BeginLROAsync()
>    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody,THeader](IAzureClient client, AzureOperationResponse`2 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody](IAzureClient client, AzureOperationResponse`1 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Rest.Azure.AzureClientExtensions.GetPostOrDeleteOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ContainerRegistry.RegistriesOperations.ImportImageWithHttpMessagesAsync(String resourceGroupName, String registryName, ImportImageParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
>    at Microsoft.Azure.Management.ContainerRegistry.RegistriesOperationsExtensions.ImportImageAsync(IRegistriesOperations operations, String resourceGroupName, String registryName, ImportImageParameters parameters, CancellationToken cancellationToken)
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRegistryRecordedTestBase.ImportImageAsync(String registry, String repository, List`1 tags) in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\tests\ContainerRegistryRecordedTestBase.cs:line 198
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRegistryRecordedTestBase.ImportImageAsync(String registry, String repository, String tag) in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\tests\ContainerRegistryRecordedTestBase.cs:line 169
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRepositoryLiveTests.CanGetManifestsOrdered() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\tests\ContainerRepositoryLiveTests.cs:line 245
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRepositoryLiveTests.CanGetManifestsOrdered() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\tests\ContainerRepositoryLiveTests.cs:line 269
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1949412&view=results

@jsquire for notification.

**Comment by pallavit** [comment]
Closing this issue against - https://github.com/Azure/azure-sdk-for-net/issues/32948 to fix the race conditions we have.
