### ISSUE TITLE
Synonym format documentation incorrectly renders => as =&gt;

### ISSUE THREAD

**Issue by danglund** [Azure/azure-sdk-for-net#32084]
In the Properties section, the table rows for Expand and Synonyms incorrectly render the synonym format specifier for one-way synonyms. The expected format is 

`incredible, unbelievable, fabulous => amazing`

The documentation unexpectedly presents it as

`incredible, unbelievable, fabulous =&gt; amazing`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 115ac1aa-9b64-52a5-fd41-2f8c17395148
* Version Independent ID: a45df9b6-f0e6-9714-e35d-858513fc53e7
* Content: [SynonymTokenFilter Class (Microsoft.Azure.Search.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.search.models.synonymtokenfilter?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Search.Models/SynonymTokenFilter.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Search.Models/SynonymTokenFilter.xml)
* Service: **search**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by pallavit** [comment]
@danglund can you please share where you are seeing this issue so we can help appropriately resolve?

**Comment by ShivangiReja** [comment]
Hi @danglund,  It appears that you're utilizing the [Microsoft.Azure.Search.Service](https://www.nuget.org/packages/Microsoft.Azure.Search.Service) library. Unfortunately, we cannot provide support for this library.

After looking through the dependencies, we noticed that you're using the Search package, `Microsoft.Azure.Search.Service`, which was officially deprecated on 07/07/2020 and is no longer maintained or monitored.  As a result, this package is no longer published nor supported by Microsoft.  We strongly recommend that you consider upgrading to its replacement, [Azure.Search.Documents](https://www.nuget.org/packages/Azure.Search.Documents/).

Here are some useful resources for your migration:
- [Azure Search Migration Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/MigrationGuide.md)
- [Retirement announcement](https://azure.microsoft.com/en-us/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/)
