### ISSUE TITLE
Create task-based container group package is deprecated

### ISSUE THREAD

**Issue by keyvanshahrdarlsus** [Azure/azure-sdk-for-net#32081]
Here is the link to a page that shows the user how to create a task-based container group using asp.net c#: https://learn.microsoft.com/en-us/dotnet/api/overview/azure/containerinstance?view=azure-dotnet#create-task-based-container-group

The package the article states to use is deprecated: Install-Package Microsoft.Azure.Management.ContainerInstance.Fluent

If you try to update the package, it asks to use the following package: Azure.ResourceManager.

When a user tries to use the new package and then tries to instantiate IAzure, it asks to load the deprecated package.

Certain aspects of the code do not work with the deprecated package, such as: 

```
var containerGroup = azure.ContainerGroups.Define(containerGroupName)
        .WithRegion(azureRegion)
        .WithExistingResourceGroup(resourceGroupName)
        .WithLinux()
        .WithPublicImageRegistryOnly()
        .WithoutVolume()
        .DefineContainerInstance(containerGroupName + "-1")
            .WithImage(containerImage)
            .WithExternalTcpPort(80)
            .WithCpuCoreCount(1.0)
            .WithMemorySizeInGB(1)
            .WithStartingCommandLines(startCommandLine.Split())
            .WithEnvironmentVariables(envVars)
            .Attach()
        .WithDnsPrefix(containerGroupName)
        .WithRestartPolicy(ContainerGroupRestartPolicy.Never)
        .Create();

```
The .WithStartingCommandLines() is not available and not in its context when used with the deprecated package. .WithStartingCommandLine() is available, but unfortunately I cannot split the startCommandLine because it only accepts string whereas a Split() is an array.

Do you have a similar code that works with the package: Azure.ResourceManager?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @keyvanshahrdarlsus, sorry for the delayed response, you can use [Azure.ResourceManager.ContainerInstance](https://www.nuget.org/packages/Azure.ResourceManager.ContainerInstance/1.0.1) to create the container group, and here is the auto-generated [sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerinstance/Azure.ResourceManager.ContainerInstance/samples/Generated/Samples/Sample_ContainerGroupCollection.cs#L480-L608) about how to create this resource. And you can specify the command by setting this [property](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerinstance/Azure.ResourceManager.ContainerInstance/src/Generated/Models/ContainerInstanceContainer.cs#L67).
