### ISSUE TITLE
[FormRecognizer]StartRecognizeBusinessCardsFromUriThrowsForNonExistingContent failing in nightly runs

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-net#32090]
FormRecognizer nightly test runs are failing with:

> Error message:
> Expected string length 21 but was 12. Strings differ at index 0.
> Expected: "FailedToDownloadImage"
> But was:  "InvalidImage"
> -----------^
> 
> Stack trace:
> at Azure.AI.FormRecognizer.Tests.RecognizeBusinessCardsLiveTests.StartRecognizeBusinessCardsFromUriThrowsForNonExistingContent() in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/RecognizeBusinessCardsLiveTests.cs:line 351

For more details check here:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1950979&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
This issue seems to be caused by a change in the behavior of the service. They changed the error code returned in a particular scenario, making our tests fail.

The service team has already been notified and we're waiting for their response.
