### ISSUE TITLE
HttpRecorder optimization

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3213]
Optimize HttpRecorder recording to:
- Remove redundant entries
- HttpRecorder should allow you to cleanup/cleanse data post recording

This is especially important as we are asking to re-record tests using latest nugets as part of moving away from old ResourceManager/Storage nugets.
If we fix HttpRecorder now, all new recordings will benefit from this.

Cost: 6

**Comment by sphibbs** [comment]
Investigate what to cleanup/cleanse.

**Comment by shahabhijeet** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/4597
