### ISSUE TITLE
Tag modules for api-version

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#3215]
### Description

- [ ] Query bala for updated sdk versions used in AzureStack
- [ ] Tag existing Nuget packageswith <namespace>:<api-version>, for example ```Microsoft.Compute:2017-05-01```
- [ ] Add the corresponding tag into each existing csproj for ARM packages, and add checking the value to the PR review checklist

### Cost: 2

**Comment by shahabhijeet** [comment]
This work will benefit from the below issue
https://github.com/Azure/autorest/issues/2434

**Comment by shahabhijeet** [comment]
This is no longer the case, we are not doing any work for AzureStack.
Rather we have a different workItem for addering profiles for the entire SDK and not just AzureStack
