### ISSUE TITLE
Please detail the purpose and nuances of ValidateIssuerSigningKey

### ISSUE THREAD

**Issue by atrauzzi** [Azure/azure-sdk-for-net#32178]
It's unclear to me if ValidateIssuerSigningKey impacts JWKS at all, a manually provided key, or a key embedded in the JWT.

There's some ambiguity.

Particularly: If I set ValidateIssuerSigningKey to false, will the JWT system still perform JWKS validation?

See: https://stackoverflow.com/questions/74195977/does-setting-validateissuersigningkey-to-false-disable-jwks

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42945161-9bd6-f8c0-ffda-b0fa03ec59fb
* Version Independent ID: 869eaee1-613a-b50a-0f18-8512dae792bd
* Content: [TokenValidationParameters.ValidateIssuerSigningKey Property (Microsoft.IdentityModel.Tokens) - Azure for .NET Developers](https://learn.microsoft.com/en-ca/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.validateissuersigningkey?view=azure-dotnet)
* Content Source: [xml/Microsoft.IdentityModel.Tokens/TokenValidationParameters.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Tokens/TokenValidationParameters.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.IdentityModel.Tokens.Jwt` library is maintained as [#1957](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1957).
