### ISSUE TITLE
Explore using Azure.Core for KeyVaultSetting

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#32174]
Currently, we plan to ship `KeyVaultSetting` as an immutable type so that we can better control what values we accept as input (output/response is open) since we need to set the type. For GA, we should explore using [`Azure.Value`](https://apiview.dev/Assemblies/Review/b67e68cfee4841bda045f895c90ad383#Azure.Value) ([source](https://github.com/Azure/azure-sdk-for-net/blob/bee533f734a513ee039c5b299d7572ddffb298ba/sdk/core/Azure.Core.Experimental/src/Variant/Value.cs)) which is basically like a COM `VARIANT`.

If we did that, we could make `KeyVaultSetting` mutable but need to make sure that the user doesn't change the `Value` type. Ultimately, it won't much matter since the service won't allow changing the type anyway. Also, the typed stored has to be serializable as a string.

**Comment by pallavit** [comment]
@heaths  Is this something we still want to explore for GA given we are mostly code-complete?

**Comment by heaths** [comment]
That's more of a question for @KrzysztofCwalina and @tg-msft. Are we ready to push `Azure.Value` to Azure.Core GA?

**Comment by pallavit** [comment]
Do we have a tracking issue to evaluate Azure.Value for Azure.Core?

**Comment by heaths** [comment]
I don't see anything currently. @KrzysztofCwalina is there anything tracking release of `Azure.Value`?

**Comment by KrzysztofCwalina** [comment]
I don't think we have anything.

**Comment by heaths** [comment]
Tracking in #32978. I optimistically added it to the 2023-01 milestone. Feel free to update pragmatically.

**Comment by heaths** [comment]
`KeyVaultSetting` GA'd, so this is no longer relevant.
