### ISSUE TITLE
Classes for new Azure Savings Plans for Compute

### ISSUE THREAD

**Issue by stdistef** [Azure/azure-sdk-for-net#32188]
Is this the page that should be updated to include the new Azure Savings Plans for Compute?
Today, to pull the RI data for VMs, the Cx is using the ConsumptionManagementClient – Service azure.mgmt.consumption
•	reservation_recommendations.list
•	usage_details.list -- > they apply various filters to this to get the overall usage, amortized usage, refunds, & reservation purchases

What will they use to get Savings Plan data?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2f39a9e4-aee4-008b-3257-8da653a88f2e
* Version Independent ID: 53f30330-23f9-2b36-0700-765468560605
* Content: [Microsoft.Azure.Management.Consumption Namespace - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.consumption?view=azure-dotnet)
* Content Source: [xml/ns-Microsoft.Azure.Management.Consumption.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Microsoft.Azure.Management.Consumption.xml)
* Service: **cost-management-billing**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @stdistef, sorry for the slow response, Microsoft.Azure.Management.Consumption is deprecated now and please use  [Azure.ResourceManager.Consumption](https://www.nuget.org/packages/Azure.ResourceManager.Consumption/1.0.0) instead.

For your question, could you please provide more specific details here?

**Comment by stdistef** [comment]
Just want to make sure customers can use this to pull savings plan usage in their tenant?

**Comment by ArcturusZhang** [comment]
We should have those APIs in the new costmanagement SDK: https://www.nuget.org/packages/Azure.ResourceManager.CostManagement/1.0.0-beta.1

**Comment by stdistef** [comment]
Not sure what it is you want me to tell you besides what I originally asked?

**Comment by ArcturusZhang** [comment]
@stdistef hi sorry my last reply might be misleading.
For the two things you listed in your description:
- reservation_recommendations.list
- usage_details.list
We have two dotnet equivalents (both in [`Azure.ResourceManager.Consumption`](https://www.nuget.org/packages/Azure.ResourceManager.Consumption/1.1.0-beta.1)):
- reservation_recommendations.list: `ComsumptionExtensions.GetConsumptionReservationRecommendations(Async)` method which is an extension method of `ArmClient`
- usage_details.list: `ComsumptionExtensions.GetConsumptionUsageDetails(Async)` method which is an extension method of `ArmClient`

From the REST API doc of [`usage_details.list`](https://learn.microsoft.com/en-us/rest/api/consumption/usage-details/list?tabs=HTTP), it says the usage_details.list operation is deprecating and please use a [new operation](https://learn.microsoft.com/en-us/rest/api/cost-management/generate-cost-details-report/create-operation?tabs=HTTP) in costmanagement instead, and dotnet SDK should support the new operation in `Azure.ResourceManager.CostManagement`. But we have some issues on that right now and will resolve it when we GA this new library.

cc @dvbb we should try to remove those removal of operations and introduce them back: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/costmanagement/Azure.ResourceManager.CostManagement/src/autorest.md?plain=1#L123
