### ISSUE TITLE
[ADLS] Make ToDfsUri and ToBlobUri methods public

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/azure-sdk-for-net#32189]
https://github.com/Azure/azure-sdk-for-net/blob/b7a58d2226b6318eac81a39a6e56e8ea1fe98857/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeUriBuilder.cs#L304

There are cases (e.g. signing URIs to be used by Azcopy) where the different URI endpoints are not interchangeable. It would be nice to not have to use reflection or code copying to get to these pre-existing methods.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this issue.
