### ISSUE TITLE
[QUERY] Mocking Monitor.Query Objects

### ISSUE THREAD

**Issue by contactkanika12** [Azure/azure-sdk-for-net#32187]
### Library name and version

azure.monitor.query

### Query/Question

Hi, I am using Azure.monitor.query and in my source code i am using function 
 var queryResponse = await this.logAnalyticsClient.QueryWorkspaceAsync(workspaceId, query2, new QueryTimeRange(TimeSpan.FromDays(7)));
 
 I want to create a mock of LogAnalyticsClient in my tests, so i have created it like Substitute.For<LogsQueryClient>()
 I want to know how do i mock the response of function QueryWorkspaceAsync() ??
 
 If you have any reference please share
  Thanks

**Comment by jsquire** [comment]
Hi @contactkanika12.  Thank you for your inquiry.  Model types that have no public constructor can be created using the [MonitorQueryModelFactory](https://learn.microsoft.com/dotnet/api/azure.monitor.query.models.monitorquerymodelfactory?view=azure-dotnet) class.  More information on the approach used for mocking support in the Azure SDK packages can be found in [this article](https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/) and [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Mocking.md).

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
