### ISSUE TITLE
Clarify what a 'redeployment' means in this context

### ISSUE THREAD

**Issue by kegregoi** [Azure/azure-sdk-for-net#32194]
This article mentions that the 'AutoUpgradeMinorVersion' property will take effect when an extension is redeployed. For extensions, any time the extension config is updated is considered a redeployment. IE: If a customer updates tags then that is technically an update on the extension config and the extension redeploys. 

It will be helpful to change the wording to something like this:
Once deployed, however, the extension will not upgrade minor versions unless **it is redeployed or has its configuration updated**, even with this property set to true.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8a1ce2e3-e09a-c035-19f5-49c90c5c3d88
* Version Independent ID: d6e635aa-d004-5e90-385a-6b313fc06a61
* Content: [VirtualMachineExtension.AutoUpgradeMinorVersion Property (Microsoft.Azure.Management.Compute.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.virtualmachineextension.autoupgrademinorversion?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/VirtualMachineExtension.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/VirtualMachineExtension.xml)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by Yao725** [comment]
Routed to compute team as this issue is related to the swagger spec update.

**Comment by Drewm3** [comment]
@GabstaMSFT, could you take a look at the suggested update and then work with the team to update the Swagger spec as you determine is needed?

**Comment by GabstaMSFT** [comment]
@kegregoi, I am reviewing for an update to swagger.

**Comment by GabstaMSFT** [comment]
@kegregoi , swagger update is in the works, will update you once it goes live.

**Comment by GabstaMSFT** [comment]
@kegregoi this update has completed an is now live.
