### ISSUE TITLE
TabularTranslator physicalType property

### ISSUE THREAD

**Issue by 1ool** [Azure/azure-sdk-for-net#32209]
There is 'physicalType' property in 'mappings.source/sink' properties.
What is the meaning of it and why is this not in the documentation? 
Please find an extract from Synapse Copy Activity below.
`
{
    "type": "TabularTranslator",
    "mappings": [
            {
                    "source": {
                            "name": "key",
                            "type": "String",
                            "physicalType": "varchar"
                    },
                    "sink": {
                            "name": "key",
                            "type": "String",
                            "physicalType": "varchar"
                    }
            }
    ]
}`
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ab58a9b-db71-31a3-d48c-862c2800bce3
* Version Independent ID: db59c73d-1a80-79e2-455b-465f6ad9eefb
* Content: [TabularTranslator.Mappings Property (Azure.Analytics.Synapse.Artifacts.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.analytics.synapse.artifacts.models.tabulartranslator.mappings?view=azure-dotnet-preview#feedback)
* Content Source: [xml/Azure.Analytics.Synapse.Artifacts.Models/TabularTranslator.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Analytics.Synapse.Artifacts.Models/TabularTranslator.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@1ool Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@1ool This property is only for UI display purpose, which provides the source and sink column type information to customers. We don’t have document for this and we don’t expect customer to edit it as well. Hope this answers.
