### ISSUE TITLE
Move Snippet Generator to .NET 6

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#32227]
# Summary

The [snippet generator](https://github.com/Azure/azure-sdk-tools/tree/main/tools/snippet-generator) tool currently targets `netcoreapp3.1` which reaches end-of-life in December, 2022.   The target framework should be updated to `net6.0` and the associated [Update-Snippet script](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/Update-Snippets.ps1) should be updated to reference the new version.

**Comment by heaths** [comment]
This was done in https://github.com/Azure/azure-sdk-tools/pull/4937
