### ISSUE TITLE
[FEATURE REQ] Provide option to exclude `UsernamePasswordCredential` from `EnvironmentCredential`

### ISSUE THREAD

**Issue by peombwa** [Azure/azure-sdk-for-net#32228]
### Library name

Azure.Identity

### Please describe the feature.

`EnvironmentCredential` uses a `ClientSecretCredential`, `ClientCertificateCredential`, or `UsernamePasswordCredential` to perform the authentication. For our scenario, we don't support `UsernamePasswordCredential` and we strongly encourage customers not to use password grant type for auth. To support our scenario, it would be nice to provide an option to exclude `UsernamePasswordCredential` from `EnvironmentCredential` as we do not support it.

**Comment by scottaddie** [comment]
@peombwa Could you use [ChainedTokenCredential](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#define-a-custom-authentication-flow-with-chainedtokencredential) instead of `EnvironmentCredential`? With it, you can form your own custom credential chain, thereby excluding `UsernamePasswordCredential`.

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by peombwa** [comment]
> @peombwa Could you use [ChainedTokenCredential](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#define-a-custom-authentication-flow-with-chainedtokencredential) instead of `EnvironmentCredential`? With it, you can form your own custom credential chain, thereby excluding `UsernamePasswordCredential`.

Thanks for the response. Using `ChainedTokenCredential` would require us to write our own implementation of environment variable credential as we will need to read the environment variables ourselves to set them to the right `TokenCredential` classes. It also adds a maintenance cost as we will need to keep up with new environment variables added in the future.

Using the existing `EnvironmentCredential` implementation works well for us, we'd just like to have the option to exclude `UsernamePasswordCredential` from the list of TokenCredentials used to acquire a token. This would be something like `Exclude*` properties in [DefaultAzureCredentialOptions](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredentialoptions?view=azure-dotnet#properties).
