### ISSUE TITLE
Azure Monitor OTel Exporter Missing Dimensions [BUG]

### ISSUE THREAD

**Issue by reynoldsa** [Azure/azure-sdk-for-net#32223]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.4

### Describe the bug

We’ve had `Azure.Monitor.OpenTelemetry.Exporter` in Prod for over a week now, and it’s working very well. I did notice that dimensions emitted from our OTel instruments aren’t making it to Azure Monitor – they do show up in Jarvis, as well as on the Console exporter, so we know they’re being emitted. I confirmed this by making a Sample app that emits a histogram metric every ~1.5 seconds or so with one dimension, and it’s not selectable as a split on Azure Monitor:

![image](https://user-images.githubusercontent.com/7054971/199330568-de88d917-9923-4a9a-adbc-9b08d6f130c5.png)

### Expected behavior

Dimensions show up.

### Actual behavior

Dimensions don't show up.

### Reproduction Steps

Set up a minimal .NET app emitting `Histogram<double>` metrics via a `Meter`, upload it to Application Insights via the library. Then, in the `Metrics` tab on Portal, as above, observe that you cannot split by dimension.

@TimothyMothra tagged per request.

**Comment by vishweshbankwar** [comment]
@reynoldsa Do you see the dimensions in customMetrics table under logs?

**Comment by reynoldsa** [comment]
@vishweshbankwar they do show up there, yes.

**Comment by vishweshbankwar** [comment]
@reynoldsa - Please check this https://learn.microsoft.com/en-us/azure/azure-monitor/app/tutorial-asp-net-custom-metrics#multi-dimensional-metrics

**Comment by reynoldsa** [comment]
My bad then, thanks for checking on it and for the information 😄
