### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by SimonLopez-Volue-MarketServices** [Azure/azure-sdk-for-net#32239]
[Sending and Receiving Messages](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_HelloWorld.md)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bff0d5e0-fa82-3c93-de88-41270ca813ac
* Version Independent ID: daae1611-8473-b884-e54e-44199a6168dd
* Content: [Azure Service Bus libraries for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/service-bus?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/service-bus.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/service-bus.md)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @SimonLopez-Volue-MarketServices.  Thank you for reaching out and thank you for letting us know.  It appears that the overview did not track a rename; the update has been made and we'll get this deployed early next week as part of our monthly release.   In the meantime, the sample from that link can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample01_SendReceive.md).
