### ISSUE TITLE
[BUG] ManagementClient use of HttpClient  (track one)

### ISSUE THREAD

**Issue by andre-laskawy** [Azure/azure-sdk-for-net#32240]
### Library name and version

Microsoft.Azure.ServiceBus

### Describe the bug

Inside the ManagementClient a new HttpClient is created and stored as a private variable, which will eventually cause the garbage collector to dispose the HTTP Client, e.g. if the ManagementClient is created as Transient. 
See also https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines

Offending code: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Management/ManagementClient.cs

### Expected behavior

Use a static HttpClient or use HTTP Factory and create the client on demand.

### Actual behavior

Http Client is created inside the constructor one time and stored as a private variable.

### Reproduction Steps

Create a Class as Transient which is containing the ManagmentClient. The Http Client will get disposed at some point and null reference exception will occur.

### Environment

Both .NET Fwk and .NET Classic

**Comment by jsquire** [comment]
Hi @andre-laskawy.  Thank you for reaching out and we regret that you're experiencing difficulties.   The `Microsoft.Azure.ServiceBus` library is deprecated and only receiving critical bug and security fixes.   We strongly recommend moving to the `Azure.Messaging.ServiceBus` package, which is the current generation.
