### ISSUE TITLE
[QUERY] Trying to figure out how to access storage account and set alert rule

### ISSUE THREAD

**Issue by Shubham7054** [Azure/azure-sdk-for-net#32250]
### Library name and version

Azure.ResourceManager.Monitor

### Query/Question

Hi,
I'm trying to access Input/Output per second for [StorageAccount resource](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-overview) in azure portal through code and send an alert every time it crosses a threshold. We can do [something similar](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-create-new-alert-rule?tabs=metric) but we wanted to do via code. 

I came across [this](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-create-new-alert-rule?tabs=metric) documentation and we can see it could access all VMs for a given subscription, wanted to check if we could access storage account like this or not?

FYI, I am planning to use [AzureRuleCollection](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.monitor.alertrulecollection?view=azure-dotnet) and [AzureRuleResource](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.monitor.alertruleresource?view=azure-dotnet) classes in the same nuget to set alert rule for my storage account.

Thanks,
Shubham

**Comment by Yao725** [comment]
Marked as `Service Attention` as this issue requires specific service domain knowledge.
