### ISSUE TITLE
[QUERY] Help creating a batch pool with the T2 management libraries

### ISSUE THREAD

**Issue by pangit1** [Azure/azure-sdk-for-net#32254]
### Library name and version

Azure.ResourcManager 1.3.1

### Query/Question

Hi, is it possible to Create a Batch pool with user-assigned managed identities using Azure.ResourcManager libraries? I need to do the following but Microsoft.Azure.Manager library is deprecated: 
https://learn.microsoft.com/en-us/azure/batch/managed-identity-pools

Really appreciate your help.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pangit1** [comment]
Found the solution.
