### ISSUE TITLE
[QUERY] Driving Directions

### ISSUE THREAD

**Issue by scsJames** [Azure/azure-sdk-for-net#32256]
### Library name and version

azure-sdk-for-net

### Query/Question

Hello .. 
We are working on fleet management system that use Console map for drivers and this consoles are connected to central unit which dispach routes and waypoints for each day .. our question is how we can render the routing api result on map and display it as Driving mode with instructions, we looked into azure maps sample sdk but no example for it founded unfortunately
our goal is get the route results and render it with instruction when driver start working on it.

if we are missing some thing please let us know 
( The Console app is will be builded with Blazor MAUI .Net 6 and will run on Android Tablet as Hybrid app ) 

there is some pictures explain our goal as an attachment
![8](https://user-images.githubusercontent.com/47700345/199606498-cdfa011d-3373-4bfd-bc4f-a8aac8d5a9b9.PNG)
![9](https://user-images.githubusercontent.com/47700345/199606510-43749a9f-130b-44f7-b7f0-7287271fefde.PNG)

Best Regard's

### Environment

.NET Core 5 / 6
Blazor WASM
Blazor MAUI

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by dubiety** [comment]
Hi @scsJames ,
Currently Azure Maps is unable to do turn by turn navigation. This is not supported yet. Not sure this answers your question or not?
