### ISSUE TITLE
Remove links to test sources from sample markdowns

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#32264]
Some samples' markdown files include links to the source files, but these add no value and may only confuse customers, leading to them think they may need to set up their functions similarly. Remove any links to such source files across all SDKs.

**Comment by heaths** [comment]
Can find quite a few with:

```powershell
dir sdk | dir -filter *.md -recurse -include *sample* | where { $_.FullName -match '\\Azure\.' } | sls -simple '.cs'
```

Easy enough to automate removal beyond that.

@jsquire @pallavit what do you think? We don't really want customers finding our tests-as-samples sources anyway, and combined with #32267 we can at least make the raw sources a little less discoverable.

**Comment by jsquire** [comment]
Makes sense to me, if our goal is to lower discoverability of the test source.

**Comment by heaths** [comment]
Should call this out in [guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-samples) as well.
