### ISSUE TITLE
[BUG] unable to filter log records exported to Azure Monitor

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-net#32276]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.4

### Describe the bug

I want to prevent logs from being sent to Azure.Monitor. Based on the [filtering processor example](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/extending-the-sdk/README.md#filtering-processor), I created:

``` fsharp
open System.Diagnostics
open OpenTelemetry
open OpenTelemetry.Logs

/// Remove Heartbeat from Host.Results
type HeartbeatLogFilter() =
    inherit BaseProcessor<LogRecord>()
    override _.OnEnd log =
        if log.CategoryName = "Host.Results" then
            let fullName =
                log.StateValues |> Seq.tryPick(fun kv ->
                    if kv.Key = "FullName" then
                        Some kv.Value
                    else
                        None
                )
            if fullName = Some "Heartbeat" then
                log.TraceFlags <- log.TraceFlags &&& ~~~ ActivityTraceFlags.Recorded
```

It removes `ActivityTraceFlags.Recorded` from the `LogRecord.TraceFlags`. 

### Expected behavior

I was expecting the log records with `ActivityTraceFlags.Recorded` removed to not be exported to Azure Monitor.

### Actual behavior

The log records still end up in Azure Monitor.

### Reproduction Steps

Please see the Microsoft [internal pull request](https://dev.azure.com/msazure/One/_git/Azure-Dedicated-AVS/pullrequest/7065047).

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/extending-the-sdk/README.md#filtering-processor is only applicable for Traces, not logs.

OpenTelemetry Logging is based on `ILogger`, and the filtering capabilities provided by `ILogger` itself can be used to filter logs.
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/customizing-the-sdk#log-filtering

**Comment by cijothomas** [comment]
We can close this. This is not an issue/questions specific to AzureMonitor.

**Comment by cataggar** [comment]
Thank you @cijothomas 🥇

**Comment by cataggar** [comment]
Unfortunately, the `ILogger` filters are limited to filtering by category and level only. I need to filter based on `log.StateValues`. Can the filtering processor be made applicable for logs too please.

**Comment by vishweshbankwar** [comment]
@cataggar There is no recommended way to filter out logs based on ActivityTraceFlags. Since this is not Azure Monitor specific question, Could you please open an issue here https://github.com/open-telemetry/opentelemetry-dotnet.

**Comment by vishweshbankwar** [comment]
Closing this as the issue is related to OTel Sdk.

**Comment by cataggar** [comment]
I opened https://github.com/open-telemetry/opentelemetry-dotnet/issues/3918.

**Comment by cataggar** [comment]
>  You can write own FilteringProcessor wrapping the exporting processor, but that'll only work if the Exporter being target has public ctor.
https://github.com/open-telemetry/opentelemetry-dotnet/issues/3918#issuecomment-1318088857

Can class `AzureMonitorLogExporter` please be made public so that it can be wrapped in a `FilteringProcessor`? It is currently `internal`:

https://github.com/Azure/azure-sdk-for-net/blob/c3fc45c5d59afcadca84e49e291d33ff439751a0/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/AzureMonitorLogExporter.cs#L15-L24

**Comment by navba-MSFT** [comment]
Adding Service team to answer the above question:

https://github.com/Azure/azure-sdk-for-net/issues/32276#issuecomment-1355544087

**Comment by cijothomas** [comment]
> > You can write own FilteringProcessor wrapping the exporting processor, but that'll only work if the Exporter being target has public ctor.
> > [open-telemetry/opentelemetry-dotnet#3918 (comment)](https://github.com/open-telemetry/opentelemetry-dotnet/issues/3918#issuecomment-1318088857)
> 
> Can class `AzureMonitorLogExporter` please be made public so that it can be wrapped in a `FilteringProcessor`? It is currently `internal`:
> 
> https://github.com/Azure/azure-sdk-for-net/blob/c3fc45c5d59afcadca84e49e291d33ff439751a0/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/AzureMonitorLogExporter.cs#L15-L24

@rajkumar-rangaraj Did we discuss/decide about making the Exporter public?

**Comment by zyofeng** [comment]
At least in beta 3 release this was still public, alternatively it would be good to provide some kind of filtering logic in AzureMonitorExporterOptions,

something like 
public Func<Activity, bool> Filter { get; set; }

**Comment by cataggar** [comment]
It looks like `AzureMonitorLogExporter` is still `internal`. Can it be made `public`?

**Comment by cataggar** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/35568 will make it public.

**Comment by cataggar** [comment]
I am hesitant to close those this. I was able to find a workaround for the logs created in this case. Hopefully, better ILogger filtering support will be possible generically for .NET.
