### ISSUE TITLE
[FEATURE REQ] ServiceBusProcessor with lock renewal ability to get notified of lock lost

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#32271]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

The `ServiceBusProcessor` abstraction has the feature of lock renewal that manages things behind the scenes. This is great. There is one caveat, though. When the processing takes long inside the processing handler and the lock cannot be renewed due to a lock lost, there is no way to correlate the error handler invocation to the currently processed handler executions. 

Ideally I would envision something like this

```csharp
ProcessMessageEventArgs
{
        /// <summary>
        /// The <see cref="System.Threading.CancellationToken"/> instance is cancelled when the lock renewal failed to renew the lock.
        /// </summary>
        public CancellationToken LockLostToken { get; }
}
```

with that in place, it would be possible to create a linked token source like this

```csharp
using var linkedCts =
              CancellationTokenSource.CreateLinkedTokenSource(args.LockLostToken, args.CancellationToken)
```

and then the processing handler could simply forward that linked token to the code that is executed in the handler. When the lock is lost, the "behind the scenes receive manager" could cancel the token source linked to the `LockLostToken` which then also give the handler execution code the ability to cancel long-running operations because it is guaranteed the message cannot be completed since the lock is already lost.

## Stack Trace

```
The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:74632f26-cf9e-4b0b-91e4-6fcfca76010a, TrackingId:faed8392-a4d2-4898-9736-42e98af9ad8e_B5, SystemTracker:servicebusplaygrounddaniel:Queue:samples.asbs.sendreply.endpoint2, Timestamp:2022-11-03T15:54:02 (MessageLockLost). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.RenewMessageLockInternalAsync(Guid lockToken, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<RenewMessageLockAsync>b__60_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.RenewMessageLockAsync(Guid lockToken, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.RenewMessageLockAsync(Guid lockToken, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.RenewMessageLockAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ReceiverManager.RenewMessageLockAsync(ServiceBusReceivedMessage message, CancellationTokenSource cancellationTokenSource)
```

**Comment by jsquire** [comment]
Thank you for the suggestion, @danielmarbach.   Routing over to Josh for consideration.

**Comment by JoshLove-msft** [comment]
I think it is a good idea, but the part that is tricky is how we would know that the lock was lost. Using the expiry time seems like it will be error prone, and at least for sessions, the service doesn't always enforce the expiry time exactly, e.g. if you are actively receiving messages for a session, the service will not enforce the lock expiration - I'm not sure if there is an equivalent for messages, but even if not this will be tricky to implement in a robust way. Also, the user can always check the Lock Expiry time themselves if they want to use this.

If we are thinking of restricting this to LockLostExceptions that we get from renew message lock failures as shown in the issue call stack, then I would agree that this would be a nice feature.

**Comment by danielmarbach** [comment]
> If we are thinking of restricting this to LockLostExceptions that we get from renew message lock failures as shown in the issue call stack, then I would agree that this would be a nice feature.

That was my idea.

**Comment by JoshLove-msft** [comment]
> > If we are thinking of restricting this to LockLostExceptions that we get from renew message lock failures as shown in the issue call stack, then I would agree that this would be a nice feature.
> 
> That was my idea.

Sounds good - I think if we could do it over this would be baked into the existing CancellationToken, but I don't think we can safely make that change now.

**Comment by danielmarbach** [comment]
Why into the existing token? LockRenewal is not something that is mandatory. Wouldn't it be the safer approach to make this token a dedicated property as I suggested and then leave it up to the users to decide whether it should be combined with the stop token or not?

Otherwise it would require to repurpose an existing token that is documented to only trigger in a specific scenario and I guess a lot of code relies on that. So if you want to make it a combined token by default you would have to introduce a new one that combines the two cases and then start obsoleting the old one. Then the question is though how you would name this new token. Any suggestions?

**Comment by JoshLove-msft** [comment]
Yeah, we can't change it now, but I was just thinking it would have been simpler if we could do this via one token. But you raise a good point that users might actually prefer having these two concerns split out in separate tokens.

**Comment by kevinharing** [comment]
I just want to add that I'm missing this functionality as well. I currently don't see a(n easy) way to cancel a (long) running operation when a lock is lost.

**Comment by danielmarbach** [comment]
@JoshLove-msft 

> I think it is a good idea, but the part that is tricky is how we would know that the lock was lost. Using the expiry time seems like it will be error prone, and at least for sessions, the service doesn't always enforce the expiry time exactly, e.g. if you are actively receiving messages for a session, the service will not enforce the lock expiration - I'm not sure if there is an equivalent for messages, but even if not this will be tricky to implement in a robust way. Also, the user can always check the Lock Expiry time themselves if they want to use this.

I have some questions regarding the above comment. 

> Also, the user can always check the Lock Expiry time themselves if they want to use this.

wouldn't that mean for sessions this property value cannot be trusted like you just explained?

I'm thinking about this because I was trying to put some rough code into the `ProcessorReceiveActions` that would do something like

```csharp
            _lockExpiredCancellationSource = new CancellationTokenSource();
            if (triggerMessage.LockedUntil != default)
            {
                // Is this true for sessions?
                _lockExpiredCancellationSource.CancelAfter(triggerMessage.LockedUntil - DateTimeOffset.UtcNow);
            }
```

and then or auto-renewal prolong the cancellation of that token source for every renewal or cancel it when the lock is lost. This code would though apply for both the processor and the session processor so I'm worried based on the comment you made if that is a feasible approach. What do you think?

By looking at the `ProcessorReceiveActions` I realized it would be possible for tracked messages to manage token sources expose tokens for those advanced use cases if needed. So for example it would be possible to do something like

```csharp
var receiveActions = processorEventArgs.GetReceiveActions();
var receivedMessages = await receiveActions.ReceiveMessagesAsync();
foreach(var message in receivedMessages) {
   var lockLostLoken = receiveActions.GetLockLostToken(message);
}
```

**Comment by somehowadev** [comment]
Would love this! Been burned before by lock lost on long running jobs.

Even if it were restricted to LockLostExceptions, would be very useful.

**Comment by danielmarbach** [comment]
@somehowadev I wanted to contribute this at some point but got a bit side tracked recently with other stuff.

**Comment by jupiter19914** [comment]
I also have a customer missing this functionality. They see the errors indicating that the lock renewal failed, but don’t have a way to stop processing the original message. The message handler and error handler are distinct “events” with no correlation evident in the args provided. So in their case they continue to do work for a message for 10 minutes after the lock renewal failed.

**Comment by danielmarbach** [comment]
I have sent in a first draft as a community contribution

https://github.com/Azure/azure-sdk-for-net/pull/36253

Got a bit rusty around some of the edge cases of the lib so please be patient with me ;)
