### ISSUE TITLE
Latest Microsoft.Hadoop.Avro

### ISSUE THREAD

**Issue by riccardone** [Azure/azure-sdk-for-net#3227]
Can you please point me to the latest source code for the C# Avro library Microsoft.Hadoop.Avro (currently version="1.5.6")?

I have issues using valid schemas with a ParseNull function that is not considering default values

Thanks

**Comment by markcowl** [comment]
@riccardone Please try looking here: https://docs.microsoft.com/en-us/azure/#pivot=get-started&panel=get-started1

**Comment by chrisxue815** [comment]
It's in the master branch: https://github.com/Azure/azure-sdk-for-net/tree/master/src/ServiceManagement/HDInsight/Microsoft.Hadoop.Avro
