### ISSUE TITLE
[ContainerRegistry] CanGetManifestProperties failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32295]
ContainerRegistry nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 404 (Not Found)
> 
> Content:
> {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown"}]}
> 
> Headers:
> Server: openresty
> Date: Wed, 02 Nov 2022 18:43:50 GMT
> Connection: keep-alive
> Access-Control-Expose-Headers: REDACTED
> Docker-Distribution-Api-Version: REDACTED
> Strict-Transport-Security: REDACTED
> X-Content-Type-Options: REDACTED
> X-Ms-Correlation-Request-Id: REDACTED
> Content-Type: application/json; charset=utf-8
> Content-Length: 70
> 
> 
> Stack trace
>    at Azure.Containers.ContainerRegistry.ContainerRegistryRestClient.GetManifestPropertiesAsync(String name, String digest, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Generated\ContainerRegistryRestClient.cs:line 1083
>    at Azure.Containers.ContainerRegistry.RegistryArtifact.GetManifestPropertiesAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\src\Artifact\RegistryArtifact.cs:line 77
>    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.CanGetManifestProperties() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\tests\RegistryArtifactLiveTests.cs:line 63
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1962023&view=results

@jsquire for notification.

**Comment by pallavit** [comment]
Closing this issue against - https://github.com/Azure/azure-sdk-for-net/issues/32948 to fix the race conditions we have.
