### ISSUE TITLE
[Synapse] ExecuteSparkStatementSync failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32297]
Synapse nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 400 (Bad Request)
> 
> Content:
> {"TraceId":"68e828e7-170b-473b-8671-03a626bc2366 | client-request-id : 432c5f66-abe4-4fd6-877e-f741b29df771","Message":"Session 2 of workspace workspacet17f9e2bc1a174666 on pool sparkt17f9e2bc1 is not running. It is either completed or not fully yet ready. Scheduler state : Ended. Plugin state : Ended. Livy state : killed."}
> 
> Headers:
> Cache-Control: no-store, no-cache
> Pragma: no-cache
> Transfer-Encoding: chunked
> Server: Kestrel,Microsoft-HTTPAPI/2.0
> Strict-Transport-Security: REDACTED
> x-ms-activity-id: REDACTED
> x-ms-client-request-id: 432c5f66-abe4-4fd6-877e-f741b29df771,432c5f66-abe4-4fd6-877e-f741b29df771
> x-ms-request-id: 57ad47ec-0434-4037-8687-570055055896
> Date: Tue, 01 Nov 2022 19:48:56 GMT
> Content-Type: application/json
> Expires: -1
> 
> 
> Stack trace
>    at Azure.Analytics.Synapse.Spark.SparkSessionRestClient.CreateSparkStatement(Int32 sessionId, SparkStatementOptions sparkStatementOptions, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Spark/src/Generated/SparkSessionRestClient.cs:line 508
>    at Azure.Analytics.Synapse.Spark.SparkSessionClient.StartCreateSparkStatementInternal(Boolean async, Int32 sessionId, SparkStatementOptions sparkStatementOptions, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Spark/src/Customization/SparkSessionClient.cs:line 68
>    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 33
>    at Azure.Analytics.Synapse.Spark.SparkSessionClient.StartCreateSparkStatement(Int32 sessionId, SparkStatementOptions sparkStatementOptions, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Spark/src/Customization/SparkSessionClient.cs:line 53
>    at Azure.Analytics.Synapse.Spark.Samples.Sample2_ExecuteSparkStatement.ExecuteSparkStatementSync() in /Users/runner/work/1/s/sdk/synapse/Azure.Analytics.Synapse.Spark/tests/samples/Sample2_ExecuteSparkStatement.cs:line 67

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1959064&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Closing; Synapse is owned by the service team and has multiple tracking issues for test defects.  No need to track each test separately.
