### ISSUE TITLE
[BUG] Request to fetch Traffic Manager Profile resource fails due to API version mismatch

### ISSUE THREAD

**Issue by peterbergman** [Azure/azure-sdk-for-net#32327]
### Library name and version

Azure.ResourceManager.Resources 1.3.0

### Describe the bug

Getting `400 BadRequest` when fetching Traffic Manager Profiles resource through `GetAsync()` on `GenericResource`.

### Expected behavior

Should fetch the resource by ID.

### Actual behavior

Request fails with `400 BadRequest` and response body:
```
{
    "code": "BadRequest",
    "message": "'2022-04-01-preview' is not a supported API version. Supported version are 2015-04-28-preview, 2015-11-01, 2017-03-01, 2017-05-01, 2017-09-01-preview, 2018-02-01, 2018-03-01, 2018-04-01, 2018-08-01, 2020-12-01-preview, 2022-04-01."
}
```

### Reproduction Steps

1. Create Traffic Manager Profile resource in subscription (below steps assumes single subscription and single resource within)
2. Create ARM client:
```
var armClient = new ArmClient(new ClientSecretCredential("tenant", "clientID", "clientSecret"));
```
3. Fetch subscription:
```
var subscription = armClient.GetSubscriptions().First();
```
4. Fetch resources:
```
var resources = subscription.GetGenericResources().First();
```
5. Fetch Traffic Manager Profile resource:
```
var resource = await genericResource.GetAsync();
```

### Environment

```
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @peterbergman, sorry for the delayed response, it looks like that `2022-04-01-preview` is already supported by the backend service now, could you please try this method again?
![image](https://user-images.githubusercontent.com/65993944/212249821-a926488a-904b-4414-8065-af47364ae33f.png)

**Comment by peterbergman** [comment]
Hi @Yao725, tested it again and it works as expected now. Thanks for the update!
