### ISSUE TITLE
[QUERY] Include properties when listing resources

### ISSUE THREAD

**Issue by peterbergman** [Azure/azure-sdk-for-net#32328]
### Library name and version

Azure.ResourceManager.Resources 1.3.0

### Query/Question

Is there any way to include all or a subset of properties when listing resources through the `GetGenericResources()`-method?

### Environment

```
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c

.NET SDKs installed:
  6.0.401 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@peterbergman may i know the reason you want all the subset properties included in the generic resource? you should be able to get the raw response and have all the information in there
code sample:
```csharp
var resourceIdentifier = ServiceBusQueueResource.CreateResourceIdentifier(client.GetDefaultSubscription().Data.SubscriptionId, resourceGroupName, serviceBusName, queueName);
var genericResource = client.GetGenericResource(resourceIdentifier).Get();
var raw = genericResource.GetRawResponse().Content.ToString();
```

**Comment by peterbergman** [comment]
Thanks @xboxeer, I was thinking if there was a way to include additional properties in the list response already so that one could avoid making additional calls to fetch each resource.

**Comment by Yao725** [comment]
If you are using generic resource, all the properties of the resource that are returned by the backend service are [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/GenericResourceData.cs#L87). And I'm afraid not there is no way to include additional properties if I understand correctly, this is not supported by the REST API of generic resource, which means we cannot do that in SDK.

**Comment by peterbergman** [comment]
Ok, I see. Then I need to make additional calls to get each resource as a generic resource. Thanks for looking in to it.
