### ISSUE TITLE
[FEATURE REQ] Add timeout support for QueueClient methods.

### ISSUE THREAD

**Issue by AchoArnold** [Azure/azure-sdk-for-net#32336]
### Library name

Azure.Storage.Queues

### Please describe the feature.

According to the [Azure documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/setting-timeouts-for-queue-service-operations) Storage Queue Operations allow to pass an optional timeout parameter. Unfortunately, none of the f QueueClient methods exposes this parameter to the user. This means I'm not able to implement any kind of server timeout operations.

There already is an optional timeout parameter, in the internal `MessagesRestClient` class

Related to #30079

**Comment by navba-MSFT** [comment]
@AchoArnold Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@AchoArnold You can try the below approach to set the timeout property using the [Transport property ](https://learn.microsoft.com/en-us/dotnet/api/azure.core.clientoptions.transport?view=azure-dotnet#azure-core-clientoptions-transport)of the QueueClientOptions class.

```
        // We'll need a connection string to your Azure Storage account.
       string connectionString = "<connection_string>";

       // Name of an existing queue we'll operate on
        string queueName = "sample-queue";

        // Timeout set to 30 seconds
        HttpClient httpClient = new HttpClient()
        {
            Timeout = TimeSpan.FromMilliseconds(30000)
        };
        
        var transport = new HttpClientTransport(httpClient);
       
        QueueClientOptions queueClientOptions = new QueueClientOptions()
        {
            Transport = transport,
        };

        // Get a reference to a queue 
        QueueClient queueClient = new QueueClient(connectionString, queueName, queueClientOptions);

```

**Comment by AchoArnold** [comment]
Hello @navba-MSFT 

The example above sets the timeout on the client side, i.e http client. I want the timeout to be done on the server side.

For example, say for instance the timeout is 100ms, If I try to enqueue an item, after 100ms, the http client will throw the exception but the server may still end up enqueuing the item since it wion't see this timeout set.

**Comment by navba-MSFT** [comment]
@AchoArnold Thanks for your reply. Have you tried injecting a custom [HttpPipelinePolicy](https://learn.microsoft.com/en-us/dotnet/api/azure.core.pipeline.httppipelinepolicy?view=azure-dotnet) and append the query string parameter there before the request gets processed?

https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclientoptions?view=azure-dotnet

https://learn.microsoft.com/en-us/dotnet/api/azure.core.clientoptions.addpolicy?view=azure-dotnet#azure-core-clientoptions-addpolicy(azure-core-pipeline-httppipelinepolicy-azure-core-httppipelineposition)

**Comment by AchoArnold** [comment]
Hey @navba-MSFT , No I haven't tried the customer HttpPipelinePolicy method.

**Comment by navba-MSFT** [comment]
@AchoArnold Could you please try it and let me know if that helps ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@AchoArnold I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.

**Comment by AchoArnold** [comment]
Hello @navba-MSFT, It will take me a while to test this pipeline policy.
Thanks.

**Comment by navba-MSFT** [comment]
@AchoArnold Thanks for your reply. Please take your time in testing the above suggestion and if you face any challenges do reach out to us again. We would be happy to help.
