### ISSUE TITLE
Fix the wrong format for some properties in Kusto lib

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#32331]
Not all `url` and `id` are the real `Url` and `Guid` format, we need to revisit and fix them.

**Comment by Yao725** [comment]
There are 6 Urls and 8 Guids in Azure.ResourceManager.Kusto 1.0.1, here are the details.
Uri

- [ ] KustoClusterData.ClusterUri
- [ ] KustoClusterData.DataIngestionUri
- [ ] KustoScriptData.ScriptUri
- [ ] KustoClusterPatch.DataIngestionUri
- [ ] KustoClusterPatch.Uri
- [ ] KustoKeyVaultProperties.KeyVaultUri

Guid

- [ ] KustoClusterPrincipalAssignmentData.AadObjectId
- [ ] KustoClusterPrincipalAssignmentData.PrincipalId
- [ ] KustoClusterPrincipalAssignmentData.TenantId
- [ ] KustoDatabasePrincipalAssignmentData.AadObjectId
- [ ] KustoDatabasePrincipalAssignmentData.PrincipalId(Already marked as obsolete)
- [ ] KustoDatabasePrincipalAssignmentData.TenantId
- [ ] KustoEventGridDataConnection.ManagedIdentityObjectId
- [ ] KustoEventHubDataConnection.ManagedIdentityObjectId
