### ISSUE TITLE
Indicate what the String parameter is

### ISSUE THREAD

**Issue by Vaccano** [Azure/azure-sdk-for-net#32346]
This delegate takes a SecurityToken and a String and then returns a String.

It is fairly clear from the context that the return value is the "Name".  And the SecurityToken is the token we are parsing out.  But what is the other parameter (the String).  

It would be nice if the documentation indicated what this String parameter holds.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3d8aae3d-f1ac-c816-a575-ac9b73289464
* Version Independent ID: 295f2425-7dd3-5d28-a534-fcba0f4ade73
* Content: [TokenValidationParameters.NameClaimTypeRetriever Property (Microsoft.IdentityModel.Tokens) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identitymodel.tokens.tokenvalidationparameters.nameclaimtyperetriever?view=azure-dotnet)
* Content Source: [xml/Microsoft.IdentityModel.Tokens/TokenValidationParameters.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.IdentityModel.Tokens/TokenValidationParameters.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.IdentityModel.Tokens` package is maintained as [#1959](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1959).
