### ISSUE TITLE
Unable to specify the operator, columns dynamically in the filter string in TableClient.CreateQueryFilter() 

### ISSUE THREAD

**Issue by yashpatel-iisc** [Azure/azure-sdk-for-net#32347]
### Library name and version

Azure.Data.Tables version 12.6.1

### Query/Question

Please guide how can I generate the expected valid value of _filterCondition that can be used in the QueryAsync method for reading the data from the table.

**Summary of the issue:**

Expected value of _filterCondition = "CreatedDateTime ge datetime'00/08/2022 0 XXXXX'"

This is working: 
_filterCondition = TableClient.CreateQueryFilter($"CreatedDateTime ge {((DateTimeOffset)filterExpression.Value)");

This isnt working:
_filterConditionWrong = TableClient.CreateQueryFilter($"{filterExpression.PropertyName} {operation} {(DateTimeOffset)filterExpression.Value}");
where filterExpression.PropertyName = "CreatedDateTime", 
operation = "ge"

Where as the value in _filterConditionWrong = "'CreatedDateTime' 'ge' datetime'00/08/2022 0 XXXXX'"

There are some extra single quotes are getting added in the filter string that which is not a valid filter for the QueryAsync method

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by RSHalo** [comment]
> ```cs
> TableClient.CreateQueryFilter($"{filterExpression.PropertyName} ")
> ```

Is this first usage of TableClient.CreateQueryFilter required? I think this would still be surrounding the property _name_ with quotes.

**Comment by RSHalo** [comment]
> CreateQueryFilter escapes every interpolated value as if it were an odata property name. One way you could deal with this is as follows:
> 
> ```cs
> var filterConditionWrong = TableClient.CreateQueryFilter($"{filterExpression.PropertyName} ") + operation + TableClient.CreateQueryFilter($" {(DateTimeOffset)filterExpression.Value}"
> ```

Is the first usage of TableClient.CreateQueryFilter required? I think this would still be surrounding the property _name_ with quotes. I think only the property _value_ should be surrounded with quotes.
