### ISSUE TITLE
[BUG]ErrorResponseException's body isn't printed in ToString()

### ISSUE THREAD

**Issue by rachelxj-ms** [Azure/azure-sdk-for-net#32361]
### Library name and version

Microsoft.Azure.Management.Authorization:2.13.0

### Describe the bug

https://github.com/Azure/azure-powershell/issues/19605, New-AzRoleAssignment doesn't return error other than status code.
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/authorization/Microsoft.Azure.Management.Authorization/src/Generated/Models/ErrorResponseException.cs
The detailed error message is set in body, but ToString() is not overwritten in the class. It seems it's a common issue. It's better SDK can print all error messages.

### Expected behavior

Expected the error details will be printed.

New-AzRoleAssignment: Operation returned an invalid status code 'Conflict'. {"code":"RoleAssignmentExists","message":"The role assignment already exists."}

In this case, Body.Error.ToJson() is {"code":"RoleAssignmentExists","message":"The role assignment already exists."}

### Actual behavior

It only prints error code.
New-AzRoleAssignment: Operation returned an invalid status code 'Conflict'

### Reproduction Steps

Grant the permissions on an Azure subscription to a certain user, group, or service principal
Run a command to grant the permissions again
New-AzRoleAssignment -ObjectId $id -RoleDefinitionName $role -Scope "/subscriptions/$sub"

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@rachelxj-ms the library you are using is our track 1 SDK and it is deprecated, please check our [deprecation announcement](https://azure.microsoft.com/en-us/updates/update-your-azure-sdk-libraries-of-net-and-golang-by-30-september-2023/).
As a replacement, you can use this package: https://www.nuget.org/packages/Azure.ResourceManager.Authorization

**Comment by rachelxj-ms** [comment]
I searched ErrorResponseException in this repository. There are 1408 code results in [Azure/azure-sdk-for-net](https://github.com/Azure/azure-sdk-for-net). It's implemented in multiple library. Are those libraries deprecated? It's a common issue, not only in Microsoft.Azure.Management.Authorization.

**Comment by xboxeer** [comment]
as long as the namespace start with Microsoft.Azure.Management, they are deprecated

**Comment by rachelxj-ms** [comment]
Please check this: https://github.com/Azure/azure-sdk-for-net/search?q=ErrorResponseException
It means other libraries have the same issue. ErrorResponseException doesn't overwrite ToString() to print body as well.

**Comment by xboxeer** [comment]
@rachelxj-ms I checked the other issue you mentioned in azure powershell repo and indeed we have a long story with powershell team regarding the new SDK vs old SDK, since Powershell will go to provide a fix without touching SDK, are we cool to close this issue?

**Comment by rachelxj-ms** [comment]
It's not just one module. One simple fix can fix a lot of copy/paste fixes. Feel free to close the ticket.
