### ISSUE TITLE
Documentation page displays special characters unnecessarily 

### ISSUE THREAD

**Issue by dikadali-MSFT** [Azure/azure-sdk-for-net#32386]
This page displays special characters unnecessarily in the first few lines as shown in the snippet below.
===============
Gets or sets specifies how the virtual machine should be created.&lt;br&gt;&lt;br&gt; Possible values are:&lt;br&gt;&lt;br&gt; Attach \u2013 This value is used when you are using a specialized disk to create the virtual machine.&lt;br&gt;&lt;br&gt; FromImage \u2013 

Source: https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.datadisk.createoption?view=azure-dotnet
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c04b601d-23cb-4a45-f011-be4c354b03f3
* Version Independent ID: 1149b72b-9982-7cc4-eec3-d3b27354e491
* Content: [DataDisk.CreateOption Property (Microsoft.Azure.Management.Compute.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.datadisk.createoption?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/DataDisk.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/DataDisk.xml)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Related:  https://github.com/Azure/autorest.csharp/issues/208

**Comment by jsquire** [comment]
//cc: @danieljurek.

**Comment by HarveyLink** [comment]
Issue fixed.
