### ISSUE TITLE
[QUERY] How to "Create App Service Managed Certificate" in code with nuget package Azure.ResourceManager.AppService

### ISSUE THREAD

**Issue by gergroen** [Azure/azure-sdk-for-net#32387]
### Library name and version

Azure.ResourceManager.AppService

### Query/Question

I cannot find a example or documentation how to "Create App Service Managed Certificate" in code with nuget package Azure.ResourceManager.AppService. Can someone provide me a example?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @gergroen, this is our [sample code](https://github.com/Azure/azure-sdk-for-net/blob/e2598c5271915079b4bdd1e7cf8ca1eaf69fa6a6/sdk/websites/Azure.ResourceManager.AppService/samples/Generated/Samples/Sample_AppCertificateCollection.cs#L117-L153) about how to create the certificate. Please let me know if it could help.
