### ISSUE TITLE
Resources. ListByTag expects values to be in '*'

### ISSUE THREAD

**Issue by nicksav** [Azure/azure-sdk-for-net#3239]
This will add tag to resource:
`                   resourceGroup.Update()
                              .WithTag("dealerID", "20")
                              .Apply();`

To be able to get resources by TagName need to add '' for the values:
`azure.ResourceGroups.ListByTag("'dealerID'", "'20'").ToList()`

I would expect it to be without ''

**Comment by martinsawicki** [comment]
interesting catch. I'm surprised as well.

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#55
