### ISSUE TITLE
[QUERY] Kusto query, summarize by one property, have legend/key with a different property

### ISSUE THREAD

**Issue by kylemccullen** [Azure/azure-sdk-for-net#32391]
### Library name and version

Microsoft.ApplicationInsights.WorkerService 2.21.0

### Query/Question

I have a azure functions project using durable functions fan-in / fan-out. There are three orchestrators batching and passing data off to each activity. I set up custom event logging to monitor performance in app insights. At the start and end of each activity custom event telemetry is logged.

I have a Kusto query to retrieve and display the data but don't have the exact look I want. Here is how it looks
```kusto
customEvents
| where customDimensions["FileName"] == "..."
| extend Key = strcat(tostring(customDimensions["Name"]), ' ', tostring(customDimensions["InvocationId"]))
| summarize sum(todecimal(customDimensions["BatchId"])) by Key, bin(timestamp, 1s)
| render timechart
```
![image](https://user-images.githubusercontent.com/110685100/200869373-f210703d-e15e-454f-a39e-d2e235f1bfdb.png)

Logs are summarized by InvocationId so we can see the time each invocation started and completed. Is there a way to summarize by one property (InvocationId), but have the legend/color code be by a different property (Name)?

Something like this

![image](https://user-images.githubusercontent.com/110685100/200872748-c1bff801-5a14-40bc-8b5c-7e580073ea87.png)

Activity Example
```cs
public class MyActivity
{
    private readonly TelemetryClient _telemetryClient;

    public MyActivity(TelemetryClient telemetryClient)
    {
        _telemetryClient = telemetryClient;
    }


    [FunctionName("My-Activity")]
    public async Task RunAsync(
            [ActivityTrigger] BaseInput input,
            ExecutionContext executionContext,
            ILogger logger,
            CancellationToken cancellationToken)
    {
        try
        {
            _telemetryClient.TrackEvent($"{input.FileName} | {executionContext.FunctionName} | Started",
                    new Dictionary<string, string>
                    {
                        { "FileName", input.FileName },
                        { "InvocationId", executionContext.InvocationId.ToString("D") },
                        { "BatchId", input.BatchId.ToString() },
                        { "Name", executionContext.FunctionName }
                    });

            // Business Logic ....
        }
        finally
        {
            _telemetryClient.TrackEvent($"{input.FileName} | {executionContext.FunctionName} | Completed",
                    new Dictionary<string, string>
                    {
                        { "FileName", input.FileName },
                        { "InvocationId", executionContext.InvocationId.ToString("D") },
                        { "BatchId", input.BatchId.ToString() },
                        { "Name", executionContext.FunctionName }
                    });
            await _telemetryClient.FlushAsync(cancellationToken);
        }
    }
}
```

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.ApplicationInsights.WorkerService` package is maintained as [#2710](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2710).
