### ISSUE TITLE
RequestFailedException due to authentication error excludes helpful www-authenticate response header value.

### ISSUE THREAD

**Issue by jimmyca15** [Azure/azure-sdk-for-net#32394]
### Library name and version

Azure.Data.AppConfiguration 1.2.0

### Query/Question

Recently received the following exception when reaching out to Azure App Configuration due to an authenticate error.

```
Configuration refresh failed from secondary configuration store with exception Azure.RequestFailedException: Service request failed.
Status: 401 (Unauthorized)



Headers:
Connection: keep-alive
Content-Length: 0
Date: Tue, 08 Nov 2022 21:44:30 GMT
Server: openresty/1.17.8.2
WWW-Authenticate: REDACTED
x-ms-request-id: 35950586-3cb4-4706-87e0-5a2f9d7151fd
x-ms-client-request-id: 00c334c5-cc56-4a4d-b545-08901f2362dd
x-ms-correlation-request-id: 35950586-3cb4-4706-87e0-5a2f9d7151fd
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: REDACTED
Strict-Transport-Security: max-age=15724800; includeSubDomains
```

Azure App Configuration [returns helpful errors ](https://learn.microsoft.com/en-us/azure/azure-app-configuration/rest-api-authentication-azure-ad#errors) in the WWW-Authenticate header to help describe any common authentication issue. The problem is that the value of WWW-Authenticate is redacted. How can I make the value appear in the exception?

**Comment by jsquire** [comment]
Redacted headers can be opted into via the [DiagnosticsOptions](https://learn.microsoft.com/dotnet/api/azure.core.diagnosticsoptions) available from the [Diagnostics](https://learn.microsoft.com/dotnet/api/azure.core.clientoptions.diagnostics?view=azure-dotnet#azure-core-clientoptions-diagnostics) property of `ConfigurationClientOptions`.   Configuring for specific headers is discussed in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging-redacted-headers-and-query-parameters) and should look something like:

```csharp
var options = new ConfigurationOptions
{
    Diagnostics =
    {
        LoggedHeaderNames = { "WWW-Authenticate" }
    }
};
```

**Comment by jimmyca15** [comment]
@jsquire 

Perfect, and just to confirm these diagnostic settings apply to the messages inside thrown exceptions as well?

**Comment by jimmyca15** [comment]
Validated that it works as expected. Thanks, resolving.
