### ISSUE TITLE
[BUG] EntityQueryItem is represented twice in the SDK

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#32395]
### Library name and version

Azure.ResourceManager.SecurityInsights

### Describe the bug

In this library is that the [EntityQueryItem](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-08-01-preview/Entities.json#L1005) is a resource so it becomes [EntityQueryData](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/securityinsights/Azure.ResourceManager.SecurityInsights/src/Generated/EntityQueryData.cs) in the SDK, however we also have it as an [EntityQueryItem](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/securityinsights/Azure.ResourceManager.SecurityInsights/src/Generated/Models/EntityQueryItem.cs) model class also.  This seems incorrect to me can we dig into why this is the case?

### Expected behavior

We represent the model from the spec once

### Actual behavior

we represent it twice

### Reproduction Steps

None

**Comment by fengzhou-msft** [comment]
`EntityQueryItem` came from [Entities.json](https://github.com/Azure/azure-rest-api-specs/blob/53b1affe357b3bfbb53721d0a2002382a046d3b0/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-08-01-preview/Entities.json#L1005), `EntityQueryData` came from [EntityQueries.json](https://github.com/Azure/azure-rest-api-specs/blob/53b1affe357b3bfbb53721d0a2002382a046d3b0/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-08-01-preview/EntityQueries.json#L267) and has an extra `Etag` property based on swagger definition. We can check the real service response to confirm whether they're really different.

**Comment by Yao725** [comment]
Close this issue as we have upgraded the API version to `2022-11-01` and these two models don't exist anymore.
