### ISSUE TITLE
Action Microsoft.Sql/locations/shortTermRetentionPolicyAzureAsyncOperation/read does not exist

### ISSUE THREAD

**Issue by simader** [Azure/azure-sdk-for-net#32411]
Hello,

I have the following code, which works with my Admin Account. 
![grafik](https://user-images.githubusercontent.com/34918640/201088896-fafa630e-fcfe-4a8c-bcfd-9afa4106a577.png)

However if a try a user with limited permission i get the following error message 403
`
The client '----' with object id '---' does not have authorization to perform action 'Microsoft.Sql/locations/shortTermRetentionPolicyAzureAsyncOperation/read' over scope '/subscriptions/---/resourceGroups/r---/providers/Microsoft.Sql/locations/westeurope/shortTermRetentionPolicyAzureAsyncOperation/0a84c678-f877-4f13-9241-3d4a8eb91cfb' or the scope is invalid. If access was recently granted, please refresh your credentials.`

When i try to find this right to add it to my role it says it does not exist. 

![grafik](https://user-images.githubusercontent.com/34918640/201089639-4c21b0a1-9505-4bfa-9d24-15569e8c407f.png)

I only can find :"Microsoft.Sql/locations/shortTermRetentionPolicyOperationResults/read" However this does not help. 

Please Advice.

**Comment by jsquire** [comment]
Thank you for reaching out and we regret that you're experiencing difficulties.   Would you please provide the name and version of the Azure SDK package that you're using?

**Comment by simader** [comment]
Azure.ResourceManager.Sql in Version 1.0.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by navba-MSFT** [comment]
@simader Thanks for reaching out to us and reporting this issue. Could you please try adding `Microsoft.Sql/locations/*/read`  permissions to that user and try again after sometime ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@simader Thanks for your reply. I have tested the [above action plan](https://github.com/Azure/azure-sdk-for-net/issues/32411#issuecomment-1357025229) and it did work fine at my end. Could you please test the same and share an update ?

**Comment by simader** [comment]
Yes, I can confirm that "Microsoft.Sql/locations/*/read" helps. However the error message still tells that 'Microsoft.Sql/locations/shortTermRetentionPolicyAzureAsyncOperation/read' is missing.

**Comment by navba-MSFT** [comment]
@simader Thanks for getting back. I did some research on this and found that there is an RBAC action   `Microsoft.Sql/locations/shortTermRetentionPolicyOperationResults/read`, this is deceptively similar to shortTermRetentionPolicyAzureAsyncOperation. So creating a custom role with this action should also help.
