### ISSUE TITLE
Add CLU example to assign deployment resources

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#32427]
See here: https://github.com/Azure/azure-sdk-for-python/pull/27237

This might be a good time to start dynamic test resources. We can create a _test-resources.bicep_ (I recommend over ARM JSON) and eventually use this for more tests. For now, we just need to create an account and maybe a project in which we deploy?

/cc @kristapratico

**Comment by TeddMcAdams** [comment]
@heaths I noticed that documentation related to assigning deployment resources seems to have been dropped between `2022-10-01-preview` and `2023-04-01` ?  Can you add any clarity on what is going on here?

**Comment by heaths** [comment]
@TeddMcAdams please open a separate issue so we can triage it to the service team.
