### ISSUE TITLE
[BUG] IAppServicePlansOperations.CreateOrUpdateWithHttpMessagesAsync Method getting 'Unauthorized' when location is different

### ISSUE THREAD

**Issue by casouzaa** [Azure/azure-sdk-for-net#32424]
### Library name and version

Microsoft.Azure.Management.Websites v4.0.0

### Describe the bug

We have a Function App to scale out/in some App Service plans. This is the code:
![image](https://user-images.githubusercontent.com/117948474/201209107-4a0aa532-b83a-4540-8590-8deae6a4423c.png)

We use the same App registration to get the credential token for all the App Service plans we want to scale, and the role of this App registration is the same in all the App Service plans ('Contributor'). However, AppServicePlans.CreateOrUpdateWithHttpMessagesAsync() fails - Operation returned an invalid status code 'Unauthorized' - when we try to scale some of the App Service plans. Investigating the issue, it seems to be related to the region where the App Service are located. If the App Service plan is located in a different region than the Function App, we get the 'Unauthorized' response, but it works just fine if the region is the same. ListByResourceGroupWithHttpMessagesAsync() works fine in both cases.

### Expected behavior

AppServicePlans.CreateOrUpdateWithHttpMessagesAsync() returns 200

### Actual behavior

AppServicePlans.CreateOrUpdateWithHttpMessagesAsync() returns 400 - Operation returned an invalid status code 'Unauthorized'

### Reproduction Steps

![image](https://user-images.githubusercontent.com/117948474/201209107-4a0aa532-b83a-4540-8590-8deae6a4423c.png)

### Environment

Azure FunctionApp V4 (.net6)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Based on the issue description, it looks like a service issue, so added the `Service Attention` label to look for the answer from service team.

By the way, Microsoft.Azure.Management.Websites is already deprecated, [Azure.ResourceManager.AppService](https://www.nuget.org/packages/Azure.ResourceManager.AppService/) is our new designed package for Azure AppService.

**Comment by casouzaa** [comment]
After updating to [Azure.ResourceManager.AppService](https://www.nuget.org/packages/Azure.ResourceManager.AppService/) I was able to figure out the issue was with the quota restriction for that specific region.
