### ISSUE TITLE
[FormRecognizer] CopyModelToAsync failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32435]
FormRecognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Invalid request.
> Status: 400 (Bad Request)
> ErrorCode: InvalidRequest
> 
> Content:
> {
> "error": {
> "code": "InvalidRequest",
> "message": "Invalid request.",
> "innererror": {
> "code": "ContentSourceNotAccessible",
> "message": "Content is not accessible: Invalid data URL"
> }
> }
> }
> 
> Headers:
> Transfer-Encoding: chunked
> x-envoy-upstream-service-time: 60187
> apim-request-id: 600f7b3e-9a71-4344-accd-e3037d3ebe67
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> x-ms-region: REDACTED
> Date: Thu, 10 Nov 2022 04:55:57 GMT
> Content-Type: application/json
> 
> 
> Stack trace
>    at Azure.AI.FormRecognizer.DocumentAnalysis.DocumentAnalysisRestClient.BuildDocumentModelAsync(BuildDocumentModelRequest buildRequest, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/DocumentAnalysisRestClient.cs:line 347
>    at Azure.AI.FormRecognizer.DocumentAnalysis.DocumentModelAdministrationClient.BuildDocumentModelAsync(WaitUntil waitUntil, Uri blobContainerUri, DocumentBuildMode buildMode, String modelId, String prefix, BuildDocumentModelOptions options, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/DocumentModelAdministrationClient.cs:line 274
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Samples.DocumentAnalysisSamples.CopyModelToAsync() in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/samples/Sample_CopyModelToAsync.cs:line 35
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1979098&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Already tracked by https://github.com/Azure/azure-sdk-for-net/issues/31914. Closing this one.
