### ISSUE TITLE
[Tables] GetPropertiesReturnsProperties failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32436]
Tables nightly test runs are failing with:

> Error message
> Expected: False
> But was:  True
> 
> 
> Stack trace
>    at Azure.Data.Tables.Tests.TableServiceClientLiveTests.CompareServiceProperties(TableServiceProperties expected, TableServiceProperties actual) in /Users/runner/work/1/s/sdk/tables/Azure.Data.Tables/tests/TableServiceClientLiveTests.cs:line 347
>    at Azure.Data.Tables.Tests.TableServiceClientLiveTests.GetPropertiesReturnsProperties() in /Users/runner/work/1/s/sdk/tables/Azure.Data.Tables/tests/TableServiceClientLiveTests.cs:line 333
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 
> 1)    at Azure.Data.Tables.Tests.TableServiceClientLiveTests.CompareServiceProperties(TableServiceProperties expected, TableServiceProperties actual) in /Users/runner/work/1/s/sdk/tables/Azure.Data.Tables/tests/TableServiceClientLiveTests.cs:line 347
>    at Azure.Data.Tables.Tests.TableServiceClientLiveTests.GetPropertiesReturnsProperties() in /Users/runner/work/1/s/sdk/tables/Azure.Data.Tables/tests/TableServiceClientLiveTests.cs:line 333
> 

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1976645&view=results

@jsquire for notification.

**Comment by christothes** [comment]
transient error that can occur when the service is slow to respond.
