### ISSUE TITLE
EUAP region pages should contain EUAP "Early Updates Access Program" meaning or mention that they are canary regions

### ISSUE THREAD

**Issue by vs-li** [Azure/azure-sdk-for-net#32456]
The pages for CentralUSEUAP and EastUS2EUAP should contain some short description that they are canary regions or "Early Updates Access Program" regions.

Ex. instead of "Name of the Azure Central US EUAP region in the Azure Cosmos DB service." have "Name of the Azure Central US Early Updates Access Program (EUAP) region in the Azure Cosmos DB service."

See: https://stackoverflow.com/questions/50647007/what-is-an-euap-region-in-azure

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1dbf611e-ee34-9f8d-f9de-df57119912f7
* Version Independent ID: a2e6ff2e-62f5-e4f8-f167-df8e2280b82a
* Content: [LocationNames.CentralUSEUAP Field (Microsoft.Azure.Documents) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.locationnames.centraluseuap?view=azure-dotnet&source=docs)
* Content Source: [xml/Microsoft.Azure.Documents/LocationNames.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Documents/LocationNames.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@vs-li Thanks for the feedback! We will update accordingly.
