### ISSUE TITLE
Custom Script Extension protected settings not working for fileUris property.

### ISSUE THREAD

**Issue by vikramdadwal** [Azure/azure-sdk-for-net#32459]
### Library name and version

Azure.ResourceManager.Compute 1.0.0.0

### Query/Question

How to create Virtual Machine extension using new SDK?

The sample provided use ComputeManagementClient to get the extension collection. But this class does not exists in the NuGet package ?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by vikramdadwal** [comment]
So I am able to create the extension, but facing problem in providing Protected settings, I need to pass the fileUrls parameters

I am using a Dictionary as mentioned in this example here: [example](https://github.com/Azure-Samples/azure-samples-net-management/blob/master/samples/compute/manage-virtual-machine-extension/Program.cs)

![image](https://user-images.githubusercontent.com/10174566/201822716-7e82e048-1a9e-4531-952b-85c5a5684808.png)

Now in my code I am passing the dictionary as 

![image](https://user-images.githubusercontent.com/10174566/201822959-efaccd57-0579-486e-a385-7ad9b2bd8973.png)

But extension throws the following exception

![image](https://user-images.githubusercontent.com/10174566/201823033-eee92bf1-7686-4c5f-8bbf-2412560981eb.png)


Please assist. 

NOTE: Normal "string" params are working fine.

**Comment by vikramdadwal** [comment]
@jsquire : Any update on this one?

**Comment by jsquire** [comment]
My role for this was only to triage;  we'll need @xboxeer for insight into the status.

**Comment by ArthurMa1978** [comment]
@vikramdadwal can you provide the code snippet?

**Comment by fengzhou-msft** [comment]
Please try with `extensionData.ProtectedSettings = BinaryData.FromObjectAsJson(task.Settings.ProtectedSettings);`

**Comment by fengzhou-msft** [comment]
From the error message, it looks like service treats the value of `fileUris` as string while the [doc](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows#property-values) says it's an array and that's what the SDK sent.

**Comment by fengzhou-msft** [comment]
@Drewm3 @avirishuv from the `Error Message: Error reading string. Unexpected token: StartArray. Path 'fileUris[0]', line 1, position 14`. It looks like service is treating `ProtectedSettings.fileUris` as string instead of array. Please help confirm.

**Comment by jaylabell** [comment]
@Drewm3 Do you mind taking a look at this issue?

**Comment by jaylabell** [comment]
@MsGabsta Do you mind taking a look at this extension issue?

**Comment by MsGabsta** [comment]
@jaylabell I will take a look at this.

**Comment by jscalev** [comment]
The fileUris don't appear to be in the correct format. They are serializing as this:

"settings": {"fileUris":[["[https://blah.blob.core.windows.net/customscript/blah.ps1"]]}

But the extension is expecting this:

"settings": {"fileUris":["https://blah.blob.core.windows.net/customscript/blah.ps1"]}

For multiple scripts:

"settings": {"fileUris":["https://blah.blob.core.windows.net/customscript/blah.ps1", "https://blah.blob.core.windows.net/customscript/blah2.ps1"]}

**Comment by vikramdadwal** [comment]
@fengzhou-msft : Do I need to wait for the fix here?

**Comment by Drewm3** [comment]
@MsGabsta, could you take this one with the CSE dev owners to see what is occurring here?

**Comment by fengzhou-msft** [comment]
I tested locally with below code and the request content sent by the client has a stream that can be converted to a string containing `\"protectedSettings\":{\"fileUris\":[\"https://blah.blob.core.windows.net/customscript/blah.ps1\"],\"commandtoExecute\":\"Powershell.exe SomeCommand\"}` which looks correct.

``` C#
Dictionary<string, object> dict = new Dictionary<string, object>();
dict["fileUris"] = new List<string>() { "https://blah.blob.core.windows.net/customscript/blah.ps1" };
dict["commandtoExecute"] = "Powershell.exe Command";
...
extensionData.ProtectedSettings = BinaryData.FromObjectAsJson(dict);
...
```

@vikramdadwal can you double confirm the type of `fileUris` in your code is an array/list?

**Comment by vikramdadwal** [comment]
@fengzhou-msft : Yes I can confirm that this is a list of string as shown in below snapshot:

![image](https://user-images.githubusercontent.com/10174566/206560402-4b20a638-28b9-4321-912c-e454782b62bc.png)

**Comment by vikramdadwal** [comment]
@fengzhou-msft @Drewm3 @MsGabsta : Really appreciate any update on this issue. Thanks

**Comment by fengzhou-msft** [comment]
@vikramdadwal could you please add the following option to your `ArmClient` and run in debug mode to print out the request payload in Output tab? Then we can check whether the format is correct from client side:

``` C#
            ArmClientOptions options = new ArmClientOptions()
            {
                Diagnostics =
                {
                    IsLoggingContentEnabled = true
                }
            };
            var client = new ArmClient(credential, defaultSubscriptionId, options);
```

**Comment by MsGabsta** [comment]
@vikramdadwal have you been able to get the output requested previously?

**Comment by GabstaMSFT** [comment]
@vikramdadwal are you still experiencing this issue?  Have you been able to get the requested output?

**Comment by vikramdadwal** [comment]
@GabstaMSFT : Yes still facing the same issue:

```
Error message: "Failed to decode the protected settings string. Error Message: Unexpected character encountered while parsing value: [. Path 'fileUris', line 1, position 14."

More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot 
Status: 200 (OK)
ErrorCode: VMExtensionProvisioningError

Content:
{
  "startTime": "2023-02-18T21:39:33.9345419+00:00",
  "endTime": "2023-02-18T21:39:54.2626834+00:00",
  "status": "Failed",
  "error": {
    "code": "VMExtensionProvisioningError",
    "message": "VM has reported a failure when processing extension 'PasswordSetAndFlushDNS'. Error message: \"Failed to decode the protected settings string. Error Message: Unexpected character encountered while parsing value: [. Path 'fileUris', line 1, position 14.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot "
  },
  "name": "27fa28c9-9cd4-40d2-888d-3aa5ee4b56c1"
}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-ratelimit-remaining-resource: REDACTED
Strict-Transport-Security: REDACTED
x-ms-request-id: 407269f9-d7be-44d2-ba82-6afaa448218a
x-ms-client-request-id: 95046565-05cb-4b8d-8a69-516326e86700
Server: Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-reads: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
X-Content-Type-Options: REDACTED
Date: Sat, 18 Feb 2023 21:40:07 GMT
Content-Length: 628
Content-Type: application/json; charset=utf-8
Expires: -1
```

**Comment by vikramdadwal** [comment]
@GabstaMSFT : Yes, this is resolved for me. I noticed the type of FileUris was going as JArray instead of List<string>. I fixed this and things are working as expected. 

Please close this issue. Thanks for all the support.
