### ISSUE TITLE
[QUERY] Why does Beta5 version has strict dependency on 1.4.0-beta.2 of OpenTelemetry?

### ISSUE THREAD

**Issue by object** [Azure/azure-sdk-for-net#32469]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.5

### Query/Question

Until the latest beta Azure.Monitor.OpenTelemetry.Exporter NuGet package had a greater-or-equal dependency on OpenTelemetry NuGet packages, for example 1.0.0-beta.4 version had a condition "OpenTelemetry >= 1.3.1".

The latest (1.0.0-beta.5) version of Azure.Monitor.OpenTelemetry.Exporter has a strict dependecy on OpenTelemetry 1.4.0-beta.2, which is not even the latest beta of OpenTelemetry. This is very inconvenient and prevents from upgrading OpenTelemetry packages. Are there any practical reasons for such strict dependency?

**Comment by vishweshbankwar** [comment]
@object Please take a look at this https://github.com/Azure/azure-sdk-for-net/pull/32073
We will remove this once the stable version of OpenTelemetry (1.4.0) is released.
