### ISSUE TITLE
[BUG] new BlobClient does not use the AccountName in the connection string

### ISSUE THREAD

**Issue by skywalkerisnull** [Azure/azure-sdk-for-net#32464]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Describe the bug

With Azure Blob IoT behind a proxy with a custom domain, we use something similar to:

```C#
var connectionString = "DefaultEndpointsProtocol=https;BlobEndpoint=https://blob02.blob<custom-domain>/devstoreaccount1;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;";
var containerName = "eba1f944-2109-483c-bfd2-e3e2fd23b428";
var fileNameWithDirectory = "3b/83/c1/bb/e9b0bf08-443c-46a6-bf2f-023a6bf79cba.jpg";

var blobClient = new BlobClient(connectionString, containerName, fileNameWithDirectory);
```

And then we inspect the `blobClient.AccountName` and we get a fragment of the URL, not the account name that is in the connection string.
![image](https://user-images.githubusercontent.com/7260106/201580573-846af8d8-deda-46d3-acfc-8b570e9e4a57.png)

### Expected behavior

The SDK to use the connection strings explict key value pair for the Account Name. Not parse the URL to "guess" the account name.

### Actual behavior

The SDK is parsing the URL and extracting the first portion of the FQDN and assuming that is the account name

### Reproduction Steps

```C#
var connectionString = "DefaultEndpointsProtocol=https;BlobEndpoint=https://blob02.blob<custom-domain>/devstoreaccount1;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;";
var containerName = "eba1f944-2109-483c-bfd2-e3e2fd23b428";
var fileNameWithDirectory = "3b/83/c1/bb/e9b0bf08-443c-46a6-bf2f-023a6bf79cba.jpg";

var blobClient = new BlobClient(connectionString, containerName, fileNameWithDirectory);```

### Environment

dotnet 7 ubuntu container

**Comment by skywalkerisnull** [comment]
Seems to come back to this area: https://github.com/Azure/azure-sdk-for-net/blob/e8a5de34a2c8bd899dca6e12a7d783dffb255139/sdk/storage/Azure.Storage.Blobs/src/BlobUriBuilder.cs#L186 where it is parsing the URI, but not taking into consideration if it is not an IP address (localhost, custom FQDN, or another custom domain format).

**Comment by skywalkerisnull** [comment]
Further, the documentation has that the AccountName is in the connection string: https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#configure-a-connection-string-for-an-azure-storage-account and going into the Azure Portal to grab the connection string, the AccountName is also in the connection string generated by Azure:

![image](https://user-images.githubusercontent.com/7260106/201783282-5a5a9393-c75e-481c-929c-683273501368.png)

**Comment by PramodValavala-MSFT** [comment]
@skywalkerisnull Thanks for the feedback and sharing your research! The code seems to be ignore it by default unless if the host is an IP Address. I believe this does work when the blob service is hosted at one [these ports](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Common/src/Shared/Constants.cs#L636) though which seems to be the ones used for path style addressing.

I will investigate further and see how best we can identify the type of endpoint when using custom domains.

**Comment by skywalkerisnull** [comment]
@PramodValavala-MSFT for identifying what type of service, I think that would also already be part of the connection string? `BlobEndpoint`, `QueueEndpoint`, `TableEndpoint`, `FileEndpoint`

https://learn.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string#create-a-connection-string-using-a-shared-access-signature

**Comment by PramodValavala-MSFT** [comment]
@skywalkerisnull Yes. That is correct. The problem here is that the URI in this case is a Path Style URI, i.e., the account name is part of the path, contrary to the regular URIs where it is part of the sub-domain instead like `https://storagesample.blob.core.windows.net`.

I am checking with the concerned team if this is a supported scenario for the SDK. In the meantime, I believe you could use [this constructor](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.-ctor?view=azure-dotnet#azure-storage-blobs-blobclient-ctor(system-uri-azure-storage-storagesharedkeycredential-azure-storage-blobs-blobclientoptions)) of BlobClient instead which requires directly providing the full URI to the blob and the credentials, skipping the inference made by SDK today.

**Comment by skywalkerisnull** [comment]
@PramodValavala-MSFT I am not sure that that constructor will work:
>A [Uri](https://learn.microsoft.com/en-us/dotnet/api/system.uri) referencing the blob that includes the name of the account, the name of the container, and the name of the blob. This is likely to be similar to "https://{account_name}.blob.core.windows.net/{container_name}/{blob_name}".

I will attempt try this out either today or tomorrow, but then will be on holidays for a month and will have to give it a go early next year. I will let you know of the results after I have tested and played with it.

**Comment by skywalkerisnull** [comment]
@PramodValavala-MSFT that constructor that you have linked to does work. Just needed to play with the URI a little to make it work:
```C#
  static BlobClient GetBlobClient(string accountName, string containerName, string fileNameWithDirectory, string accountKey)
  {
      var blobUri = new Uri($"https://<custom-domain>/{accountName}/{containerName}/{fileNameWithDirectory}");
      var credentials = new StorageSharedKeyCredential(accountName, accountKey);
      var blobClientOptions = new BlobClientOptions();
      var blobClient = new BlobClient(blobUri, credentials, blobClientOptions);
      return blobClient;
  }
```

**Comment by PramodValavala-MSFT** [comment]
@skywalkerisnull Glad to hear that!

This approach does requires you to manually build the full URI to the blob. Sorry I missed providing an example of such a URI earlier to be more clear.

**Comment by PramodValavala-MSFT** [comment]
@skywalkerisnull The work to address this will be tracked in the linked feature request above since inference of path style URIs outside of IP-style hosts is currently not supported.

The workaround in the meantime is to use [an alternate constructor](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.-ctor?view=azure-dotnet#azure-storage-blobs-blobclient-ctor(system-uri-azure-azuresascredential-azure-storage-blobs-blobclientoptions)) which doesn't require a connection string. Closing this in favor of the feature request.
