### ISSUE TITLE
[QUERY]How to delete Qna Pair in Azure.AI.Language.QuestionAnswering

### ISSUE THREAD

**Issue by Unders0n** [Azure/azure-sdk-for-net#32470]
### Library name and version

Azure.AI.Language.QuestionAnswering.Authoring

### Query/Question

In old version of lib and rest api for QNAMaker we could delete a qna pair, but in this lib i can't find such method.
Have to say i can't also find it in pure rest api of new language api. SO the question is - is that possible at all (preferably by lib, but if not - mb with rest api) Thank you.

### Environment

.net 6, Azure.AI.Language.QuestionAnswering 1.1.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Unders0n** [comment]
UPDATE: i was able to reverse-engineer post requests from laguage studio and can see that it sends calls with "delete" in it, can be reproed with lib in code like:
`RequestContent updateQnasRequestContent = RequestContent.Create(
                new[] {
                    new {
                        op = "delete",
                        value = new
                        {
                            id = 7
                        }
                    }
                });`
But what is the best way to cleanup all pairs in needed KB?

**Comment by heaths** [comment]
@Unders0n from the [OpenAPI definition](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/Language/stable/2021-10-01/questionanswering-authoring.json) it seems there's no way to delete all pairs apart from getting a list of all of them and sending a request to delete each one.

@kayousef @rokulka do you think adding a sample for this would be useful?

/cc @kristapratico
