### ISSUE TITLE
What value should people put for partitionKey and rowKey?

### ISSUE THREAD

**Issue by chanmmn** [Azure/azure-sdk-for-net#32485]
[Enter feedback here]
What value should people put for partitionKey and rowKey?
Can you explain in the page?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 577bf9ad-b1b2-f48d-88bf-425ef7f9004c
* Version Independent ID: 3fb63a45-2bc7-408e-7365-cb7f9fefc8c7
* Content: [Azure Tables client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/data.tables-readme?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/data.tables-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/data.tables-readme.md)
* Service: **tables**
* GitHub Login: @christothes
* Microsoft Alias: **chriss**

**Comment by christothes** [comment]
Hi @chanmmn - Thanks for the feedback. Could you be more specific about which section of the readme you are referring to? Are you looking for information about which values are not allowed?

**Comment by chanmmn** [comment]
Hi @christothes  , thanks for the reply. At the section "Add table entities". I believe we need to know at least what data type partitionKey and rowKey is without going to find it somewhere else.
