### ISSUE TITLE
Move FormRecognizer test recordings out of the repo

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#32490]
As we get ready to migrate test recordings outside the .NET repo - we have been trying to hand-pick a few SDKs before we do the mass migration. Form Recognizer is would be a good candidate here.

Questions I would like us to follow-up on? 
1. Once, recordings are out of the repo how are we supposed to file bugs, issues if we see any?
2. What is the SLA on those issues?
3. If we find irrecoverable issues, I am hoping we can reverse and move the recordings back-in if needed :)

**Comment by kinelski** [comment]
Recordings have been migrated.
