### ISSUE TITLE
[BUG] GetDenyAssignments() throws an exception for GenericResource

### ISSUE THREAD

**Issue by sergiygetlin** [Azure/azure-sdk-for-net#32503]
### Library name and version

Azure.ResourceManager.Authorization, v1.0.0

### Describe the bug

I am using following client library "Azure.ResourceManager.Authorization, v1.0.0" to retrieve deny assignments for a resource.
Following code throws exception at return line:

```
public Pageable<DenyAssignmentResource> GetDenyAssignmentsForResource(GenericResource ga)
{
        DenyAssignmentCollection data = ga.GetDenyAssignments();
        return data.GetAll();
}

```
The error message is following: "Value cannot be empty or contain only white-space characters. (Parameter 'resourceType')". In fact, 'resourceType' is not null. 

### Expected behavior

Should return deny assignments specific to a resource.

### Actual behavior

GetAll() in DenyAssignmentCollection throws an exception with the following message: "Value cannot be empty or contain only white-space characters. (Parameter 'resourceType')". It looks like it happened on this [line](https://github.com/Azure/azure-sdk-for-net/blob/a1d2a65005df37e018d927ce3cf300e734b8923e/sdk/authorization/Azure.ResourceManager.Authorization/src/Generated/DenyAssignmentCollection.cs#L343). It tries to create ResourceType based on empty string value for comparison and fails due to validation.

### Reproduction Steps

1. Retrieve list of resources for a given resource group:

```
ArmClient _armClient; //should be initialized

string resourceGroupName = "RESOURCE_GROUP_NAME";
var subscriptions = _armClient.GetSubscriptions();
SubscriptionResource subscription = subscriptions.Get(subscriptionId);

ResourceGroupCollection resGroupCollection = subscription.GetResourceGroups();
ResourceGroupResource resourceGroupResource = resGroupCollection.Get(resourceGroupName);

Pageable<GenericResource> resources = resourceGroupResource.GetGenericResources();
```

2. Run following code for a given resource
```
public Pageable<DenyAssignmentResource> GetDenyAssignmentsForResource(GenericResource ga)
{
        DenyAssignmentCollection data = ga.GetDenyAssignments();
        return data.GetAll();
}
```

### Environment

dotnet --info:

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Thanks for reaching out to us, confirmed this is a bug, will fix it.

**Comment by xpandax76** [comment]
I run into similar issues when trying to get deny assignments for a specific management group as well
var denyAssignments = armClient.GetDenyAssignments(new Azure.Core.ResourceIdentifier("/providers/Microsoft.Management/managementGroups/Test")).GetAll();

Is there any workaround for this?

**Comment by mcgallan** [comment]
> I run into similar issues when trying to get deny assignments for a specific management group as well var denyAssignments = armClient.GetDenyAssignments(new Azure.Core.ResourceIdentifier("/providers/Microsoft.Management/managementGroups/Test")).GetAll();
> 
> Is there any workaround for this?

I think the scope you provided in GetDenyAssignments is wrong，You can try 
`GetDenyAssignments(new Core.ResourceIdentifier("/subscriptions/{subscriptionId}/resourcegroups/{resourceGroupName}")).GetAll()` as an alternative

**Comment by mcgallan** [comment]
This BUG has been fixed, you can try it out with the [new version](https://www.nuget.org/packages/Azure.ResourceManager.Authorization)
