### ISSUE TITLE
Update app service plan sku

### ISSUE THREAD

**Issue by AndresPita** [Azure/azure-sdk-for-net#32517]
### Library name and version

Azure.ResourceManager.AppService 1.0.0

### Query/Question

Hi. Is it possible to update the sku of an app service plan using your newest SDK?
I can't seem to find the sku property under "AppServicePlanPatch" in the update method.
As far as I can see it's the only one missing.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by iliosana** [comment]
@jsquire Any update on this issue?

**Comment by AndresPita** [comment]
@iliosana I ended up finding another way to accomplish this using the same package.
Have a look [here](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.appservice.appserviceplancollection.createorupdateasync?view=azure-dotnet).

**Comment by iliosana** [comment]
@AndresPita I got it to work. Thank you very much for your help!

For others: here is how I ended up updating the SKU of an app service plan (P1v2 in this case):

```c#
string subscriptionId = "YOUR-SUBSCRIPTION-ID";
string resourceGroupName = "THE-NAME-OF-THE-RESOURCE-GROUP-THE-APP-SERVICE-PLAN-IS-IN";
string appServicePlanResourceName = "YOUR-APP-SERVICE-RESOURCE-NAME";

// client
ArmClient client = new ArmClient(new DefaultAzureCredential());

// get resource group object
SubscriptionCollection subscriptions = client.GetSubscriptions();
SubscriptionResource sub = subscriptions.Get(subscriptionId);
ResourceGroupResource resourceGroup = sub.GetResourceGroup(resourceGroupName);

// create updated service plan object
AppServicePlanData newAppServicePlanData = new AppServicePlanData(AzureLocation.WestEurope);
newAppServicePlanData.Kind = "app";
newAppServicePlanData.Sku = new AppServiceSkuDescription();
newAppServicePlanData.Sku.Name = "P1v2";
newAppServicePlanData.Sku.Tier = "PremiumV2";
newAppServicePlanData.Sku.Size = "P1v2";
newAppServicePlanData.Sku.Family = "P";
newAppServicePlanData.Sku.Capacity = 1;

// get service plan
AppServicePlanCollection collection = resourceGroup.GetAppServicePlans();

// update service plan
var result = collection.CreateOrUpdate(
    waitUntil: Azure.WaitUntil.Completed, 
    name: appServicePlanResourceName, 
    data: newAppServicePlanData
);
```

**Comment by xboxeer** [comment]
close this one as it is resolved
