### ISSUE TITLE
[BUG] ResourceManager.Network type is not mockable

### ISSUE THREAD

**Issue by HWouters** [Azure/azure-sdk-for-net#32515]
### Library name and version

Azure.ResourceManager.Network 1.1.0

### Describe the bug

ResourceGroupResourceExtensionClient has a protected constructor for mocking, but the class itself is internal. This makes it impossible to mock some methods for unit testing.

### Expected behavior

ResourceGroupResourceExtensionClient  is public

### Actual behavior

ResourceGroupResourceExtensionClient  is internal

### Reproduction Steps

https://github.com/Azure/azure-sdk-for-net/blob/923dc96a481a4234bb87dec21f052ac51f1b70e3/sdk/signalr/Azure.ResourceManager.SignalR/src/Generated/Extensions/ResourceGroupResourceExtensionClient.cs#L17

**Comment by Yao725** [comment]
Thanks for reaching out to us, will investigate this issue.

**Comment by live1206** [comment]
Covered in https://github.com/Azure/autorest.csharp/issues/3493

**Comment by ArthurMa1978** [comment]
Close as dup
