### ISSUE TITLE
[BUG] BlobClient.UploadAsync with ClientSideEncryptionVersion.V2_0 throws exception when uploading an empty file.

### ISSUE THREAD

**Issue by SamiSuhail** [Azure/azure-sdk-for-net#32511]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Describe the bug

We changed from ClientSideEncryptionVersion.V1_0 to ClientSideEncryptionVersion.V2_0 and are no longer able to upload empty files to blob storage. No other changes were made to the code. I checked in the active issues and the only one related to the ClientSideEncryption is #27793 but it doesn't seem to have much to do with this issue. I tried changing the constructor I am using just in case and the issue persisted.

Thanks in advance for the assistance.

### Expected behavior

The BlobClient.UploadAsync method should be able to upload an encrypted file to storage, even if the original unencrypted content was an empty stream. I went through the #28870 PR and at a glance it seems as though that new behaviour is not something we were aiming for, but please do correct me if I am wrong and missing something. 

### Actual behavior

The following exception is received:
```
System.ArgumentException: Cannot read a non-positive number of bytes.
 Stack Trace: 
  PooledMemoryStream.ReadLoopInternal(Stream stream, Byte[] buffer, Int32 offset, Int32 minCount, Int32 maxCount, Boolean async, CancellationToken cancellationToken)
  PooledMemoryStream.BufferStreamPartitionInternal(Stream stream, Int64 minCount, Int64 maxCount, Int64 absolutePosition, ArrayPool`1 arrayPool, Nullable`1 maxArrayPoolRentalSize, Boolean async, CancellationToken cancellationToken)
  PartitionedUploader`2.UploadInternal(Stream content, Nullable`1 expectedContentLength, TServiceSpecificData args, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)
  BlobClient.StagedUploadInternal(Stream content, BlobUploadOptions options, Boolean async, CancellationToken cancellationToken)
  TaskExtensions.EnsureCompleted[T](Task`1 task)
  BlobClient.Upload(Stream content, BlobHttpHeaders httpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, IProgress`1 progressHandler, Nullable`1 accessTier, StorageTransferOptions transferOptions, CancellationToken cancellationToken)
```

### Reproduction Steps

1) Initialize a BlobContainerClient
2) Initialize a BlobClient
`BlobClient blob = container.GetBlobClient(blobName);`
3) Add ClientSideEncryptionOptions with V2_0:
```
ClientSideEncryptionOptions encryptionOptions = new ClientSideEncryptionOptions(ClientSideEncryptionVersion.V2_0)
{
    KeyEncryptionKey = rsaEncryptionKey,
    KeyResolver = keyResolver,
    KeyWrapAlgorithm = "RSA-OAEP"
};
blob = blob.WithClientSideEncryptionOptions(encryptionOptions);
```
4) UploadAsync with empty stream
`await blob.UploadAsync(new MemoryStream());`

### Environment

$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.102
 Commit:    02d5242ed7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.102\

**Comment by RakeshMohanMSFT** [comment]
@SamiSuhail Thank you reaching out, we are looking into it.

**Comment by yotkoKanchev** [comment]
Hey guys, is there any progress here?

**Comment by AKermanov** [comment]
We have the same problem, is there any progress regarding this issue?
