### ISSUE TITLE
ListPools() hangs for integrated, Universal MFA and Password based batch client

### ISSUE THREAD

**Issue by hakzhyena** [Azure/azure-sdk-for-net#32510]
### Library name and version

Microsoft.Azure.Batch.dll, Version 14.0.0.0

### Describe the bug

I have implemented new ways of authentications in addition to 'Shared Key' authentication for Azure Batch services in my application. The new ways of authentications are AAD username/password based, integrated and universal MFA. 

 So, the `batchClient` is created in the following way.

```
// Create an instance of the Batch Client.
                lock (batchClientLocker)
                {
                    if (authMode == 1)
                    {
                        BatchSharedKeyCredentials cred = new BatchSharedKeyCredentials(azureAccountUrl, azureAccountName, azureAccountKey);
                        batchClient = BatchClient.Open(cred);
                    }
                    else
                    {
                        Func<Task<string>> tokenProvider = () => GetAuthenticationTokenAsync(authMode, azureAccountUserName, azureAccountPassword);
                        batchClient = BatchClient.Open(new BatchTokenCredentials(azureAccountUrl, tokenProvider));
                    }
                }
```

After this I do `ListPools()` in a different call. And when this call is made from the test application ( WPF based app) in succession to open() it goes into hanging state only for integrated, universal MFA and Username/Password authentication modes. With Shared Key authentication the batch pools are fetched as expected although with the delay of around 30 seconds.

```
lock (batchClientLocker)
                {
                    batchPoolList = batchClient.PoolOperations.ListPools().ToListAsync().Result;
                }
```

The token is acquired using following ways in the abovementioned modes:

Integrated: `result = await application.AcquireTokenSilent(scopes, accountToLogin).ExecuteAsync();`
Universal MFA: `result = await application.AcquireTokenInteractive(scopes).ExecuteAsync(CancellationToken.None);`
Username/Password based: `result = await application.AcquireTokenByUsernamePassword(scopes, azureAccountUserName, securePassword).ExecuteAsync();`

I created a dump file and when debugged the breakpoint is at following location. 
![callstack](https://user-images.githubusercontent.com/4454537/202105817-5e4f8bc4-30f1-4a9e-97c5-852372f6f31f.png)

Can you please confirm if it is a known bug or if I am missing something?

### Expected behavior

ListPools() should return the pools in less that 30 seconds at least if successful.

### Actual behavior

Call to ListPools() with certain batchClients is hanging.

### Reproduction Steps

1. Create batchClients with different ways.
2. Make a call to ListPools().

Both these steps are explained above in the Bug Description.

### Environment

Windows 10 64-bit.
Target Framework: .NET Framework 4.8 on Test application.
Target Framework:: NET Framework 4.7.2 on class library.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

@paterasMSFT, @dpwatrous, @wiboris, @mksuni, @bgklein Could you please look into this once you get a chance ?
