### ISSUE TITLE
Improve logging for Azure WebJobs Extensions storage account resolution

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-sdk-for-net#32521]
### Library name and version

Azure.Storage.Blobs 5.0.0

### Describe the bug

To aid in CRI investigations we need to log the name of the storage account we resolve and use for functions. The Azure Functions programming model allows customers to specify [binding expression patterns](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns#binding-expressions---app-settings) that allow them to separate config from code, with the storage account used being resolved at runtime from app settings. We get many CRIs where customers mess up their deployments such that the wrong environment variables are deployed and the functions are targeting the incorrect storage account leading to errors/confusion. I was just investigating a multi-day CRI where it ended up being the customer was deploying the wrong code/config. Having logs would make these cases much faster to resolve. As it stands, we have to get access to customer app settings as well as decompile binaries to figure it out.

For example, in the blob trigger case, the code [here](https://github.com/Azure/azure-sdk-for-net/blob/bfd3109d0f9afa763131731d78a31e39c81101b3/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Blobs/src/Triggers/BlobTriggerBinding.cs#L192) starts the listener using a resolved BlobContainerClient. We could simply log the AccountName along with the function name. We'd want to do a similar thing for QueueTrigger, as well as for input/output bindings, looking to see if we can somehow centralize this code to make it easier to apply in all the cases.

Other non-storage extensions would benefit from such logs as well, so once we establish a pattern here, we should do the same for other extensions.

### Expected behavior

Logs should clearly show the storage account being used for function bindings.

### Actual behavior

We don't currently log this information, making diagnosing problems difficult.

### Reproduction Steps

See recent ICM https://portal.microsofticm.com/imp/v3/incidents/details/348978764.

### Environment

All environments.

**Comment by jsquire** [comment]
//cc: @seanmcc-msft, @amnguye
