### ISSUE TITLE
Looking for exception throwned on operation fail

### ISSUE THREAD

**Issue by byBobo** [Azure/azure-sdk-for-net#32535]
Does SetSecretAsync throw an exception if the secret creation fails? How can I check if the secret has been added to the vault, without directly read it in another operation (as a last chance)?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c536dd25-1fd1-a53b-96f2-0cc17104befa
* Version Independent ID: c6b1cc8a-30b3-e73a-c5e5-c76367cbb7e3
* Content: [KeyVaultClientExtensions.SetSecretAsync Method (Microsoft.Azure.KeyVault) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.keyvaultclientextensions.setsecretasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.KeyVault/KeyVaultClientExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.KeyVault/KeyVaultClientExtensions.xml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
All our client methods could throw a `RequestFailedException` that include details from the server. This is documented for our `SecretClient` methods: https://learn.microsoft.com/en-us/dotnet/api/azure.security.keyvault.secrets.secretclient.setsecretasync?view=azure-dotnet#:~:text=%3CKeyVaultSecret%3E%3E-,Exceptions,-ArgumentException

Note that the package you're using now - `Microsoft.Azure.KeyVault` - has been deprecated for a while and will receive no further support. You should switch to `Azure.Security.KeyVault.Secrets`, for which we have a [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/MigrationGuide.md).
