### ISSUE TITLE
[QUERY] TableClient DeleteEntity using ITableEntity 

### ISSUE THREAD

**Issue by fhtino** [Azure/azure-sdk-for-net#32549]
### Library name and version

Azure.Data.Tables 12.7.0

### Query/Question

TableClient.DeleteEntity accepts 2 parameters: partition key and row key.
Is there a reason why there is not an overload accepting an ITableEntity instance?
E.g. `myclient.DeleteEntity(myEntity);`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JonathanCrd** [comment]
Hi @fhtino, is there any scenario you are facing in which passing the whole entity would be more helpful than passing the properties?

For example, with the current method, you could use this:
```
myclient.DeleteEntity(myEntity.partitionKey, myEntity.rowKey);
```

**Comment by fhtino** [comment]
@JonathanCrd there is no technical issue to pass partionkey and rowkey as separated items.  In my opinion, a DeleteEntity accepting a ITableEntity item is more concise, clean and no risk of swapping rowkey with partitionkey.

E.g. `myclient.DeleteEntity(myEntity);`
