### ISSUE TITLE
[QUERY] Add example Event Hubs namespace hostname in Schema Registry client creation example

### ISSUE THREAD

**Issue by nickghardwick** [Azure/azure-sdk-for-net#32542]
### Library name and version

Azure.Data.SchemaRegistry 1.3.0

### Query/Question

In the [Getting Started example](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/schemaregistry/Azure.Data.SchemaRegistry) for using Azure.Data.SchemaRegistry, there is a guide to create a `SchemaRegistryClient` for interacting with the schema registry service in the `README.md` file. In that example, there is no sample value given for the `fullyQualifiedNamespace` that is required to construct a client. This can cause confusion on the format of the Host name from the Event Hubs service itself, especially regarding fact that the scheme ("https://") part of the Host name should _not_ be included as a parameter. Doing so causes a parsing error when trying to register a schema after the client is created.

An example can be formatted similar to `{hostname}.servicebus.windows.net`.

**Comment by AldrinSeanPereira** [comment]
I'd like to help out (although as a beginner) :) 
Could you assign this bug to me?
