### ISSUE TITLE
[ServiceBus] ReceiverDrainsOnClosing failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32559]
ServiceBus nightly test runs are failing with:

> Error message
> Expected: 1
> But was:  2
> 
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.<>c__DisplayClass2_1.<<ReceiverDrainsOnClosing>g__Receive|0>d.MoveNext() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 108
> --- End of stack trace from previous location ---
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.<>c__DisplayClass2_1.<<ReceiverDrainsOnClosing>g__Receive|0>d.MoveNext() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 110
> --- End of stack trace from previous location ---
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.ReceiverDrainsOnClosing() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 96
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.ReceiverDrainsOnClosing() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 96
>    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.ReceiverDrainsOnClosing() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 123
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
> 
> 1)    at Azure.Messaging.ServiceBus.Tests.Receiver.ReceiverLiveTests.<>c__DisplayClass2_1.<<ReceiverDrainsOnClosing>g__Receive|0>d.MoveNext() in /Users/runner/work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/Receiver/ReceiverLiveTests.cs:line 108

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1996052&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
No longer failing consistently
