### ISSUE TITLE
[ContainerRegistry] CanGetManifests(False) failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32556]
ContainerRegistry nightly test runs are failing with:

> Error message
> Expected: not null
> But was:  null
> 
> 
> Stack trace
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRepositoryLiveTests.CanGetManifests(Boolean anonymous) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRepositoryLiveTests.cs:line 153
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 
> 1)    at Azure.Containers.ContainerRegistry.Tests.ContainerRepositoryLiveTests.CanGetManifests(Boolean anonymous) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRepositoryLiveTests.cs:line 153

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1993502&view=results

@jsquire for notification.

**Comment by pallavit** [comment]
Closing this issue against - https://github.com/Azure/azure-sdk-for-net/issues/32948 to fix the race conditions we have.
