### ISSUE TITLE
[Eventhub] ConsumerCanReadFromAllPartitionsStartingWithLatest failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32557]
Eventhub nightly test runs are failing with:

> Error message
> The cancellation token should not have been signaled.
> Expected: False
> But was:  True
> 
> 
> Stack trace
>    at Azure.Messaging.EventHubs.Tests.EventHubConsumerClientLiveTests.ConsumerCanReadFromAllPartitionsStartingWithLatest() in D:\a\_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs\tests\Consumer\EventHubConsumerClientLiveTests.cs:line 2305
>    at Azure.Messaging.EventHubs.Tests.EventHubConsumerClientLiveTests.ConsumerCanReadFromAllPartitionsStartingWithLatest() in D:\a\_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs\tests\Consumer\EventHubConsumerClientLiveTests.cs:line 2314
>    at Azure.Messaging.EventHubs.Tests.EventHubConsumerClientLiveTests.ConsumerCanReadFromAllPartitionsStartingWithLatest() in D:\a\_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs\tests\Consumer\EventHubConsumerClientLiveTests.cs:line 2317
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
> 
> 1)    at Azure.Messaging.EventHubs.Tests.EventHubConsumerClientLiveTests.ConsumerCanReadFromAllPartitionsStartingWithLatest() in D:\a\_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs\tests\Consumer\EventHubConsumerClientLiveTests.cs:line 2305

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1996003&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
This is a service timeout; they're intermittent but expected.
