### ISSUE TITLE
Spaces in Connection String leads to unexpected behaviour

### ISSUE THREAD

**Issue by aakashpahwa-msft** [Azure/azure-sdk-for-net#32561]
As mentioned in the documentation, connection strings defined in the format of "RunAs=xxx; yyy" - the space causes the connection string to not work as tested locally (Visual Studio credential vs AzureCLI scenario being tested locally).

We were setting AzureCLI connection string "RunAs=Developer; DeveloperTool=AzureCli" but it was picking up Visual Studio credential.

Removing the space did the trick.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fe303b99-ea26-a458-6f98-2f93465fb346
* Version Independent ID: 1acbd255-4c40-4f9f-7205-3fcdcc1a527b
* Content: [App Authentication client library for .NET - version 1.6.0 - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/service-to-service-authentication?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/service-to-service-authentication.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/service-to-service-authentication.md)
* Product: **azure**
* GitHub Login: @jlichwa
* Microsoft Alias: **jalichwa**

**Comment by jsquire** [comment]
//cc: @nonik0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by anaismiller** [comment]
Thanks for sharing @aakashpahwa-msft. I created a PR [here ](https://github.com/Azure/azure-docs-sdk-dotnet/pull/2255) with the fix to the documentation

This was the section in [code](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/mgmtcommon/AppAuthentication/Azure.Services.AppAuthentication/AzureServiceTokenProviderFactory.cs#L70-L90). I would have thought an error would have been triggered.
