### ISSUE TITLE
[QUERY] Use EventProcessorClient to connect from an application with a valid oauth 2.0 token?

### ISSUE THREAD

**Issue by Protheon** [Azure/azure-sdk-for-net#32565]
### Library name and version

Azure.Messaging.EventHubs 5.7.3

### Query/Question

Hi, in all .NET examples I have seen, to connect to eventhub the connectionstring is always used. 
Can you provide instructions or an example on how to connect with EventProcessorClient using an application's oauth 2.0 token?

From the list of available constructors the only possibility is:
EventProcessorClient(checkpointStore,  consumerGroup, fullyQualifiedNamespace, eventHubName, TokenCredential , EventProcessorClientOptions)

TokenCredential is abstract and I see no implementation. Should I build my own TokenCredential or is there a default implementation?

An example would be great!

**Comment by jsquire** [comment]
Can you help me understand what the "application's oauth 2.0 token" refers to in this context?   Is this an AAD token obtained externally, or something else?   

The Azure.Messaging.EventHubs library, like all of the current generation of Azure SDK packages, is intended to work with the [Azure.Identity](https://www.nuget.org/packages/Azure.Identity) library.  Responsibility for token acquisition and management is delegated to `Azure.Identity`.   If you're looking to pass an already acquired AAD token, you'll want to follow the Azure.Identity sample for [Authenticating with a prefetched access token](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/DefiningCustomCredentialTypes.md#authenticating-with-a-prefetched-access-token).

**Comment by Protheon** [comment]
hi @jsquire. Thanks for the feedback. I'm using Microsoft.Identity.Client to get the token. I've followed the steps here https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Client-credential-flows 

Through here, I have no way of feeding the token to EventProcessorClient directly. What I am testing right now is to create an instance of AccessToken with the tokenresult and overriding TokenCredential to pass in the token. Is this a valid approach?

**Comment by jsquire** [comment]
Thank you for the clarification.   Your approach is valid and is illustrated by the Azure.Identity sample that I linked above.

**Comment by Protheon** [comment]
Tyvm! good to hear. I will close the question. Have a great weekend!
