### ISSUE TITLE
[QUERY] ServiceBus ReceiveManager CloseReceiverIfNeeded forceClose has no effect

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#32571]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

`ServiceBusProcessor` calls in `CloseAsync` on the `ReceiverManager` the method `CloseReceiverIfNeeded` which passes `forceClose: true` but this parameter has no effect. Should this be cleaned up?

see https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ServiceBusProcessor.cs#L1016-L1018
and https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/ReceiverManager.cs#L64

in contrast the `SessionProcessor` passes the value forward and is respected.

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Processor/SessionReceiverManager.cs#L160-L164

**Comment by jsquire** [comment]
Looks like the parameter is needed because the session version uses it via override.  @JoshLove-msft would have better context.

**Comment by JoshLove-msft** [comment]
> Looks like the parameter is needed because the session version uses it via override. @JoshLove-msft would have better context.

Yeah that's correct. This can probably be cleaned up, but for the non-session manager we always close the receiver when CloseReceiverIfNeeded is called.

**Comment by danielmarbach** [comment]
for the base method on the `ReceiveManager` would `forceClose` with `false` mean that it should respect the cancellation token and therefore call `CloseAsync(cancellationToken)` instead of directly `DisposeAsync` since then the token would be forwarded and can't be considered a "force close"?

**Comment by JoshLove-msft** [comment]
The forceClose has no meaning for the base method - it only there for the derived method, which does make use of it.

**Comment by danielmarbach** [comment]
It looks like it is a bit of a leaky abstraction in my view. You can also see that the processor has to cast to the `SessionProcessor` when adjusting the number of sessions.

**Comment by JoshLove-msft** [comment]
> It looks like it is a bit of a leaky abstraction in my view. You can also see that the processor has to cast to the `SessionProcessor` when adjusting the number of sessions.

Sure, that is why I mentioned this can probably be cleaned up 😄 
I'm just explaining what the intended semantics are, but I agree the implementation can probably be improved.

**Comment by danielmarbach** [comment]
Something like this? https://github.com/Azure/azure-sdk-for-net/pull/32575

**Comment by jsquire** [comment]
Fixed by #32575; closing this out.
