### ISSUE TITLE
[BUG] Azure.ResourceManager.KeyVault's KeyVaultData type not usable with JSON deserialization

### ISSUE THREAD

**Issue by AtOMiCNebula** [Azure/azure-sdk-for-net#32584]
### Library name and version

Azure.ResourceManager.KeyVault 1.0.0

### Describe the bug

The `KeyVaultData` class in the `Azure.ResourceManager.KeyVault` SDK has a single public constructor that throws an exception if a null `KeyVaultProperties` instance is passed in, which is what both `Newtonsoft.Json` and `System.Text.Json` do when trying to create an instance for deserialization purposes.  This effectively prevents you from deserializing either of these types from JSON.

https://github.com/Azure/azure-sdk-for-net/blob/2cbcfd0af4ffab269ea8aafc664362fc39da2464/sdk/keyvault/Azure.ResourceManager.KeyVault/src/Generated/KeyVaultData.cs#L19-L28

This doesn't appear to be the case for other types in `Azure.ResourceManager.*` SDKs, but I don't understand why the code generation for the KeyVault management SDK is different:
* https://github.com/Azure/azure-sdk-for-net/blob/2cbcfd0af4ffab269ea8aafc664362fc39da2464/sdk/compute/Azure.ResourceManager.Compute/src/Generated/VirtualMachineScaleSetData.cs#L20-L25
* https://github.com/Azure/azure-sdk-for-net/blob/2cbcfd0af4ffab269ea8aafc664362fc39da2464/sdk/servicebus/Azure.ResourceManager.ServiceBus/src/Generated/ServiceBusNamespaceData.cs#L19-L24
* https://github.com/Azure/azure-sdk-for-net/blob/2cbcfd0af4ffab269ea8aafc664362fc39da2464/sdk/storage/Azure.ResourceManager.Storage/src/Generated/StorageAccountData.cs#L20-L25

### Expected behavior

Structure deserialized, no exception

### Actual behavior

Exception thrown:
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'properties')
  Source=Azure.ResourceManager.KeyVault
  StackTrace:
   at Azure.ResourceManager.KeyVault.KeyVaultData..ctor(AzureLocation location, KeyVaultProperties properties)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
[...]
```

### Reproduction Steps

Minimal example:
```csharp
KeyVaultData data = JsonConvert.DeserializeObject<KeyVaultData>("{}");
```

Thing I was actually trying to do:
```csharp
ArmClient client = new(credential);
TenantCollection tenants = client.GetTenants();
await foreach (TenantResource tenant in tenants)
{
    QueryContent query = new(@"
Resources
| where type == ""microsoft.keyvault/vaults""
| order by name asc
");
    QueryResponse response = await tenant.ResourcesAsync(query);
    IList<KeyVaultData> vaultData = response.Data.ToObjectFromJson<IList<KeyVaultData>>();
}
```

### Environment

.NET 6.0, Visual Studio 17.4.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@AtOMiCNebula this is by design, the service team has defined its [swagger ](https://github.com/Azure/azure-rest-api-specs/blob/e0aca4c32155a2568fdad5cb91028206930f0053/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2022-07-01/keyvault.json#L1582-L1584) here so the keyvaultdata ctor method has this properties parameter

**Comment by AtOMiCNebula** [comment]
@xboxeer, this still seems like a poor design choice, regardless.  What's the right way to engage the KeyVault team on this?  Open a new issue in the `azure-rest-api-specs` repo?

**Comment by AtOMiCNebula** [comment]
Actually, this is probably a closer fit to either #25699 or #25045.

For now, I'm hacking around this with `KeyVaultData` with the following (the `Write` implementation wasn't strictly needed, but why not 😄):

```csharp
public class AzureJsonConverter<T> : JsonConverter<T>
{
    public override T? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
    {
        MethodInfo? deserializer = typeof(T).GetMethod($"Deserialize{typeof(T).Name}", BindingFlags.NonPublic | BindingFlags.Static);
        if (deserializer == null)
        {
            throw new NotImplementedException();
        }

        using JsonDocument document = JsonDocument.ParseValue(ref reader);
        object? result = deserializer.Invoke(null, new object?[] { document.RootElement });
        return (T)result!;
    }

    public override void Write(Utf8JsonWriter writer, T value, JsonSerializerOptions options)
    {
        MethodInfo? serializer = typeof(T).GetMethod("Azure.Core.IUtf8JsonSerializable.Write", BindingFlags.NonPublic | BindingFlags.Instance);
        if (serializer == null)
        {
            throw new NotImplementedException();
        }

        serializer.Invoke(value, new object?[] { writer });
    }
}
```
```csharp
JsonSerializerOptions options = new() { Converters = { new AzureJsonConverter<KeyVaultData>() } };
IList<KeyVaultData> vaultData = response.Data.ToObjectFromJson<IList<KeyVaultData>>(options);
```
