### ISSUE TITLE
[QUERY] SAS Token with IPv6 as IpRange not working

### ISSUE THREAD

**Issue by ferchoMancini** [Azure/azure-sdk-for-net#32580]
### Library name and version

Azure.Storage.Blobs 12.13.0

### Query/Question

I'm trying to generate SAS token assigning an IPv6 as IpRange. I don't get any error when I generate the token and build the url on the code. But then when I try to navigate to the blob's URL I'm getting a HTTP 403 (Forbidden). It works perfectly when I use IPv4 though.

Do you know if IPv6 is supported?

```
var blobSasBuilder = new BlobSasBuilder
{
	ExpiresOn = expires,
	Resource = "b",
	BlobContainerName = blob.BlobContainerName,
	BlobName = blob.Name,
	Protocol = SasProtocol.Https,
	IPRange = new SasIPRange(IPAddress.Parse("MyIPv6Address")),
};
```

On the other hand, when I try to build a SAS token throught the Azure Portal, it won't let me assign an IPv6 here. My 2 cents, IPv6 is not allowed, but I didn't find any documentation that says that explicitly.

![image](https://user-images.githubusercontent.com/5026203/202861314-98d9db5e-b2b8-4318-9d3a-418e42a3a1ec.png)

Any help would be much appreciated!

### Environment

net5.0; Azure Portal

**Comment by RakeshMohanMSFT** [comment]
@ferchoMancini Thank you for reaching out to us, we are looking into it.

**Comment by RakeshMohanMSFT** [comment]
@ferchoMancini Yes, its not supported for [signed IP](https://learn.microsoft.com/en-us/rest/api/storageservices/create-account-sas#specify-an-ip-address-or-ip-range), but you are correct we should explicitly call out. Will raise a request to get the document updated.

**Comment by ferchoMancini** [comment]
Thanks @RakeshMohanMSFT . Do you know if supporting IPv6 is in the roadmap? or we should consider another alternative.
