### ISSUE TITLE
Client APIs button gets to 404 page

### ISSUE THREAD

**Issue by sergiosolorzano** [Azure/azure-sdk-for-net#32583]
Client APIs button doesn't work
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16bf8678-793d-e39c-2edc-c149e866a353
* Version Independent ID: 9c634f1d-6a4a-020d-563b-64bbe5eef97e
* Content: [Azure Service Fabric libraries for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/service-fabric?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/service-fabric.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/service-fabric.md)
* Service: **service-fabric**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@sergiosolorzano Thanks for the feedback! We will review and update accordingly.

In the meantime, the [`FabricClient`](https://learn.microsoft.com/en-us/dotnet/api/system.fabric.fabricclient?view=azure-dotnet-legacy) seems to be just part of the Comman Package itself, which should serve as the reference for the supported APIs.
