### ISSUE TITLE
Move required TFMs to net7.0, net6.0

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#32596]
With netcoreapp3.1 falling out of support soon, move to the latest version - net7.0 - and the latest LTS - net6.0.

- [x] Update _eng/Directory.Build.Common.props_ for `RequiredTargetFrameworks`
- [x] Update _globa.json_ to require 7.0.101 (fix for microsoft/vstest#4014)
- [x] Add _.vsconfig_ to recommend installing net6.0 targeting pack and net7.0 SDK

**Comment by heaths** [comment]
@KrzysztofCwalina @tg-msft @pallavit @jsquire should we alert partners before or after we make this change. This also means updating global.json to require it. I can also add a .vsconfig to have VS suggest installing both net7.0 and net6.0 targeting packs if not installed.

**Comment by heaths** [comment]
Yes, there are changes to the pipelines but not that hard. Basically just need to update the same files I'm doing in #32598.

**Comment by danielmarbach** [comment]
Was just about to comment that it might make sense to drop the no longer supported netcoreapp3.1 in the required target frameworks

https://github.com/Azure/azure-sdk-for-net/blob/main/eng/Directory.Build.Common.props#L126
