### ISSUE TITLE
Running Static analysis build tools

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3260]
Currently we analysis tools but that increases time for build.
Run all the tools in parallel.
For e.g.
CredScan
BinScope
Policheck
Static Analysis tool

Cost: 8

**Comment by sphibbs** [comment]
We should also look into what we run the tools against. Do run against the entire repo if only compute has changed.

**Comment by pakrym** [comment]
This seems to be obsolete considering new engeenering system,
