### ISSUE TITLE
[BUG] Reusing an HttpClient across multiple instances of ServiceClient can cause corruption of HttpClient.DefaultRequestHeaders 

### ISSUE THREAD

**Issue by EranGon** [Azure/azure-sdk-for-net#32602]
### Library name and version

Microsoft.Rest.ClientRuntime 2.3.24

### Describe the bug

The ctor for ServiceClient ends up calling [SetDefaultAgentInfo()](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/mgmtcommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L563) which sets a few User Agent values.
This ends up updating HttpClient.DefaultRequestHeaders in [AddUserAgentEntry()](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/mgmtcommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L563) under a lock.

However - the [lock](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/mgmtcommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L34) used to safeguard updating HttpClient.DefaultRequestHeaders is an instance member, and if the multiple instances of ServiceClient are created concurrently with the same HttpClient - this can cause corruption of the HttpClient.DefaultRequestHeaders dictionary.
We've experienced this in our production service (started getting ArgumentNullException when sending requests to Azure Resource Graph)

### Expected behavior

Creating multiple instances of ServiceClient concurrently with the same HttpClient should work

### Actual behavior

In some cases, the HttpClient.DefaultRequestHeaders get corrupted due to concurrent modifications

### Reproduction Steps

This is a sporadic issue, and I don't have a constant repro for it

### Environment

.NET Framework 4.8

**Comment by jsquire** [comment]
@AlexanderSher:  Would you please take a look and offer your thoughts?


//fyi: @m-nash

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
The legacy Rest Client Runtime reached end-of-life in September and is no longer under support.  Closing.
