### ISSUE TITLE
IsBatched missing?

### ISSUE THREAD

**Issue by sadiqkhoja** [Azure/azure-sdk-for-net#32619]
Hi,

Following document mentions of `IsBatch` but I can't find it in attribute class

https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger?tabs=in-process%2Cextensionv5&pivots=programming-language-csharp#attributes

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @sadiqkhoja, 
IsBatched is not a property of the attribute, and hasn't been for several major versions. @shreyabatra4 are you able to help get these docs updated?

**Comment by jsquire** [comment]
This issue has been transferred to the repository of the team best able to assist with documentation updates as [#223](https://github.com/Azure/azure-functions-servicebus-extension/issues/223)
