### ISSUE TITLE
Make TestFx documentation robust

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3261]
There are still scenarios where testFx needs to show exception message that are clear, so that user can take further action.
This in includes linking error messages to documentation (need to try out how this will pan out)
Also making sure the documentation for TestFx is robust
Also making sure if we can have a migration guide from old testFx to new testFx

Research as to how can we get users off old TestFx and create set of guidelines
Make sure all the updates (build script related) are reflected in Repo-Tasks.psd1

Cost: 4

**Comment by sphibbs** [comment]
add test for repo-tasks.psd1

Also update powershelll test help for the hybrid scenario of two test FX. Add a task.

**Comment by shahabhijeet** [comment]
Migration Guide:
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/Documentation/AuthConflictsBetweenSDKs.md

We are no longer advocating users use RepoTask.psd1 (we have deprecated this module), we will be eventually in our next build tools updates.

https://github.com/Azure/azure-sdk-for-net/pull/4407
