### ISSUE TITLE
ServiceBusReceiveActions Azure function binding parameter missing `Peek` method.

### ISSUE THREAD

**Issue by aliqaryan2** [Azure/azure-sdk-for-net#32618]
the current version of `ServiceBusReceiveActions` binding parameter has the ability to receive additional messages according to this example:
[ServiceBusReceiveActions
](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus#binding-to-receiveactions)
```
// attempt to receive additional messages in this session
await receiveActions.ReceiveMessagesAsync(maxMessages: 10); 
```

It would be very helpful if we had to `PeekMessagesAsync()` method that could also check `Scheduled` messages.

**Comment by jsquire** [comment]
Hi @aliqaryan2.   Starting in version 5.8.0 of the `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package, peeking is supported by `ServiceBusReceiveActions` and will include scheduled messages when peeking a queue.
