### ISSUE TITLE
[Core] VirtualMachineScaleSetResource is not completely Mockable

### ISSUE THREAD

**Issue by desokey** [Azure/azure-sdk-for-net#32610]
### API Change Needed

Yes

### Background and motivation

while we can get an initialized object of VirtualMachineScaleSetResource using GetVirtualMachineScaleSeResource , its Data property is read only and also null. so, we cannot have a fully Mocked of this class. 

### API / Feature Proposal

while we can get an initialized object of VirtualMachineScaleSetResource using GetVirtualMachineScaleSeResource , its Data property is read only and also null. so, we cannot have a fully Mocked of this class. 

### Time Constraints and Dependencies

i think making the Data property writable will solve the issue.

**Comment by jsquire** [comment]
@desokey:  Please do not assign engineers or labels when opening issues.   This hinders our triage process.

**Comment by desokey** [comment]
I did not , i think it is automated !

**Comment by desokey** [comment]
> @desokey: Please do not assign engineers or labels when opening issues. This hinders our triage process.

I did not , i think it is automated !

**Comment by jsquire** [comment]
![image](https://user-images.githubusercontent.com/913445/203408655-478fc534-6603-479b-9f05-81f70f2c2468.png)

**Comment by jsquire** [comment]
Apologies, this is my error.  It seems there's a Core Feature Request template that was configured for this.

**Comment by xboxeer** [comment]
@desokey  we have a new feature called model factory that is in progress to fix this issue: https://github.com/Azure/autorest.csharp/pull/2947

**Comment by HarveyLink** [comment]
Hi @desokey ModelFactory feature has been enabled for all services, refer this [document](https://aka.ms/azsdk/net/mocking) for more details.
