### ISSUE TITLE
Support for Authenticating Event grid using Managed Identity for the Azure functions handler.

### ISSUE THREAD

**Issue by rakhshandakhan** [Azure/azure-sdk-for-net#32620]
As per the document we still don’t have the support for the Azure Functions handler for the authenticating through Manage Identity. Can we have a support for the Azure functions handler? [https://learn.microsoft.com/en-us/azure/event-grid/security-authentication]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Addressed in https://github.com/Azure/azure-sdk-for-net/pull/36484
