### ISSUE TITLE
Synchronize Publishing and creating release

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3262]
Currently there can be cases where you can fail to publish a nuget package, but you can still create a release.
Need to synchrozing both task (publishing and creating GitHub release) as one operation or at least let creating GitHub release fail if publishing fails.
Investigate how can we flag, releases as pre-release/release

Cost: 4

**Comment by sphibbs** [comment]
If publish fails don't create tag
if publish succeeds ensure the tag is created. 

We need to figure out a queue strategy

**Comment by shahabhijeet** [comment]
Currently we cannot create a queue strategy because we don't have a build service running on publishing machine.
Unless we have build component running as a service on CI machines, this cannot be enabled the way it was mentioned below.
The entire purpose of this task is not to go ahead and create a tag if for some reason any of the pieces in the entire pipeline fails.
Lately with the addition of nuget signing, we were creating tags without ever successfully signing nuget package.
But now we will stop creating tags once nuget signing fails and that is the only purpose of this task.

**Comment by shahabhijeet** [comment]
Experimenting with Octokit library for automating github tasks.
Found out the library is unsigned and will have to rethink how can we use this without relaxing SN verification.
This task is done as we sync'd the release using the Jenkins job instead of msbuild task.
This task will be revisited once the library issues are resolved that we want to use for interacting with github.
Current work is being done in a separate [syncRelease branch](https://github.com/shahabhijeet/azure-sdk-for-net/commit/18317acfdf6db064ea6d94d414f0955c76cdad41)
