### ISSUE TITLE
QueueTrigger RTS improvements

### ISSUE THREAD

**Issue by mathewc** [Azure/azure-sdk-for-net#32634]
We should consider adding the new QueueTrigger scale heuristics that were added to ScaleController to the RTS logic. These ScaleController changes were made after the initial version of RTS was released.

Those ScaleController changes also apply to ServiceBus, so if we do this we should also do it for ServiceBusTrigger.

**Comment by jsquire** [comment]
@alrod, @mathewc:  There's not enough context and background present in the discussion for me to understand what actions need to be taken for the extensions packages.   Can you please provide further detail around this so that it can be triaged?
