### ISSUE TITLE
CreateOrReplace operation possible for Azure Table Storage binding?

### ISSUE THREAD

**Issue by mpseidel** [Azure/azure-sdk-for-net#32637]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Use table storage output binding in node function in App Service plan

2. Output table item with existing RowKey, setting Etag: "*"

#### Expected behavior

A upsert operation is executed as mentioned [here](https://stackoverflow.com/a/55527201)

#### Actual behavior

Function fails with: `The specified entity already exists.`

The docs state that upsert is not supported but there seems to be something here that should do the trick? https://github.com/Azure/azure-webjobs-sdk/blob/ea55e6ef5439b1059b43825cb9d40cc12ae219bc/src/Microsoft.Azure.WebJobs.Extensions.Storage/Tables/TableEntityWriter.cs#L100

**Comment by christothes** [comment]
Does this issue reproduce with the newer version of this extension? https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Tables

**Comment by mfmevans** [comment]
The issue here is with Node so the above suggested package isnt relevant is it?
