### ISSUE TITLE
Use changefeed when available for Blob triggers

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/azure-sdk-for-net#32630]
The current strategy for blob storage triggers is `ScanBlobScanLogHybridPollingStrategy`, which involves using storage logs as a de facto changefeed.

Using the the _actual_ blob changefeed when available (especially with [a cursor](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-change-feed-how-to#resume-reading-records-from-a-saved-position)) would be much simpler and more performant.

**Comment by jsquire** [comment]
//cc: @seanmcc-msft, @amnguye
