### ISSUE TITLE
requiredScope Any or All check for scopes

### ISSUE THREAD

**Issue by 1Jesper1** [Azure/azure-sdk-for-net#32647]
Does the requiredScope attribute do an Any or All check for the scopes?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eea099b1-d4fe-5ec7-71e3-e4f79e972be0
* Version Independent ID: 935de5b5-6042-4514-3688-cb794d3a9eed
* Content: [RequiredScopeAttribute Class (Microsoft.Identity.Web.Resource) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.web.resource.requiredscopeattribute?view=azure-dotnet)
* Content Source: [xml/Microsoft.Identity.Web.Resource/RequiredScopeAttribute.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Web.Resource/RequiredScopeAttribute.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Identity.Web` package is maintained as [#1977](https://github.com/AzureAD/microsoft-identity-web/issues/1977).
