### ISSUE TITLE
[Monitor] Nightly test failures

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#32649]
### Library name

Azure.Monitor.Query

### Please describe the feature.

`Azure.Monitor.Query` nightly tests are failing with `The operation was canceled.` [error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2005159&view=logs&j=a3682114-3f18-57fc-5b36-0513d1624e30&t=6a4dc7eb-a623-51f6-667a-b67692526197&l=55):

![image](https://user-images.githubusercontent.com/45216704/203619843-469f8ab1-e607-4d5c-84bd-ecc384ef7550.png)

For more details see the pipeline here: https://dev.azure.com/azure-sdk/internal/_build?definitionId=5650&_a=summary

**Comment by nisha-bhatia** [comment]
pipeline failures have been resolved
