### ISSUE TITLE
[BUG] Creation of StorageAccount throws 'System.InvalidOperationException: The operation has not completed yet.' when using WaitUntil.Started

### ISSUE THREAD

**Issue by Zijian-Ju** [Azure/azure-sdk-for-net#32659]
### Library name and version

Azure.ResourceManager.Storage

### Describe the bug

When creating storage using CreateOrUpdate method with WaitUntil.Created flag, an exception throws. Most of my code is the same as the official example except for the WaitUntil flag. My code is here: 
```
ArmClient armClient = new ArmClient(new DefaultAzureCredential());
var subscriptions = armClient.GetSubscriptions();

var subscription = (await subscriptions.GetAsync("<my sub ID>")).Value;

string rgName = "myRgName";
AzureLocation location = AzureLocation.EastUS;
ArmOperation<ResourceGroupResource> operation = await subscription.GetResourceGroups().CreateOrUpdateAsync(WaitUntil.Completed, rgName, new ResourceGroupData(location));
ResourceGroupResource resourceGroup = operation.Value;


StorageSku sku = new StorageSku(StorageSkuName.StandardZrs);
StorageKind kind = StorageKind.Storage;
StorageAccountCreateOrUpdateContent parameters = new StorageAccountCreateOrUpdateContent(sku, kind, location);


StorageAccountCollection accountCollection = resourceGroup.GetStorageAccounts();
string accountName = "<account name>";
ArmOperation<StorageAccountResource> accountCreateOperation = await accountCollection.CreateOrUpdateAsync(WaitUntil.Started, accountName, parameters);

StorageAccountResource storageAccount = accountCreateOperation.Value;
```

### Expected behavior

The storage starts creation and return

### Actual behavior

I download the SDK code locally and this is the stack trace for exception:

Unhandled exception. System.InvalidOperationException: The operation has not completed yet.                                at Azure.Core.OperationInternal`1.get_Value() in D:\PersonalWorkPlace\azure-sdk-for-net\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 157                                                                                         at Azure.ResourceManager.Storage.StorageArmOperation`1.get_Value() in D:\PersonalWorkPlace\azure-sdk-for-net\sdk\storage\Azure.ResourceManager.Storage\src\Generated\LongRunningOperation\StorageArmOperationOfT.cs:line 47                     at Program.<Main>$(String[] args) in D:\PersonalWorkPlace\azure-sdk-for-net\sdk\storage\Azure.ResourceManager.Storage\StorageTEst\Program.cs:line 29                                                                                            at Program.<Main>(String[] args) 

### Reproduction Steps

The code I provided.

And seems like the exception throws here
![image](https://user-images.githubusercontent.com/53360473/203690000-c8803824-8d50-4d43-9fe5-0b2580db8394.png)

### Environment

Dotnet

**Comment by blueww** [comment]
@ArthurMa1978 , @ArcturusZhang 
Do you have any idea why this error is reported from SDK?
The related rest API is a long-running API.

@Zijian-Ju 
Would you please give more details, like:
1. do you wait a long time on the accountCollection.CreateOrUpdateAsync() API before it failed?
2. If possible, could you give the network trace for the failed request (hide credential), or at least storage account name, region, time and better with request ID. We need these information to do more investigation.

**Comment by Zijian-Ju** [comment]
> @ArthurMa1978 , @ArcturusZhang Do you have any idea why this error is reported from SDK? The related rest API is a long-running API.
> 
> @Zijian-Ju Would you please give more details, like:
> 
> 1. do you wait a long time on the accountCollection.CreateOrUpdateAsync() API before it failed?
> 2. If possible, could you give the network trace for the failed request (hide credential), or at least storage account name, region, time and better with request ID. We need these information to do more investigation.

Thanks @blueww for your reply.

1. No, it returned immediately
2. I just repro the issue here is response headers
- ClientRequestId: <HTML>
<head>
<title>Document</title></head>
<body>



  | Name | Value | Type
-- | -- | -- | --
◢ | RawResponse | {StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: <null>, Headers: {   Cache-Control: no-cache   Pragma: no-cache   x-ms-client-request-id: d3bb880c-55b0-4702-baab-18ce79e22219   x-ms-request-id: 949173e1-8e7c-4b13-a669-8d6d38f3d33d   Strict-Transport-Security: max-age=31536000; includeSubDomains   Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0   x-ms-ratelimit-remaining-subscription-writes: 1198   x-ms-correlation-request-id: 91b3c57b-bec5-40f0-b5b5-13b6f3826535   x-ms-routing-request-id: SOUTHEASTASIA:20221124T054305Z:91b3c57b-bec5-40f0-b5b5-13b6f3826535   X-Content-Type-Options: nosniff   Date: Thu, 24 Nov 2022 05:43:05 GMT }} | Azure.Response {Azure.Core.Pipeline.HttpClientTransport.PipelineResponse}



</body>
</HTML>


The account name is '**zijianjtest11sd223sdd1**' in **EastUS**

**Comment by blueww** [comment]
@Zijian-Ju 
Thanks for the reply!

I have searched the server log with the info from you. 
The request is a success PutStorageAccountOperation. 
Something looks a little abnormal to me is the request should be a longrunning request (which means first request should return 202 with a link, and the following request should the link until return 200), but it seems the first PutStorageAccountOperation with orignal Uri returns 200.

@ArthurMa1978 , @ArcturusZhang, would you please see why SDK report error when server success to create the account? And is there any way to fix it?

**Comment by jsquire** [comment]
```csharp
ArmOperation<StorageAccountResource> accountCreateOperation = await accountCollection.CreateOrUpdateAsync(WaitUntil.Started, accountName, parameters);
```

From the code snippet, the Storage call appears to be using `WaitUntil.Started` rather than `WaitUntil.Completed`.

**Comment by blueww** [comment]
@Zijian-Ju 
Would you please try the above suggestion and see if the issue can be resolved?

**Comment by Zijian-Ju** [comment]
> @Zijian-Ju @blueww as @jsquire says, the `Operation<T>.Value` property is only available when the long running operation is done. In your code, you just started the LRO and immediately called the `.Value` property. It is not finished therefore an `InvalidOperationException` is thrown and it is telling you as the message says "the operation is not completed"
> 
> If you just want the creation result, you have the following options:
> 
> 1. please use `WaitUntil.Completed` instead of `WaitUntil.Started`. In this way, the SDK will wait the operation for you.
> 2. call `Operation<T>.WaitForCompletion(CancellationToken)` method before you get the `Value`. This ensures you that the operation is completed.

@ArcturusZhang  Thanks for your reply. Just for clarification. Does this mean we are waiting the creation of the storage to complete or just the ARM operation itself? I mean, is there any chance when Operation<T>.WaitForCompletion(CancellationToken) is returned, the provisioning State of the storage account is inProgress or something similiar?

**Comment by ArcturusZhang** [comment]
> > @Zijian-Ju @blueww as @jsquire says, the `Operation<T>.Value` property is only available when the long running operation is done. In your code, you just started the LRO and immediately called the `.Value` property. It is not finished therefore an `InvalidOperationException` is thrown and it is telling you as the message says "the operation is not completed"
> > If you just want the creation result, you have the following options:
> > 
> > 1. please use `WaitUntil.Completed` instead of `WaitUntil.Started`. In this way, the SDK will wait the operation for you.
> > 2. call `Operation<T>.WaitForCompletion(CancellationToken)` method before you get the `Value`. This ensures you that the operation is completed.
> 
> @ArcturusZhang Thanks for your reply. Just for clarification. Does this mean we are waiting the creation of the storage to complete or just the ARM operation itself? I mean, is there any chance when Operation.WaitForCompletion(CancellationToken) is returned, the provisioning State of the storage account is inProgress or something similiar?

This is exactly how LRO works. `Operation.WaitForCompletion` is polling until the operation is done.

If this is happening
> I mean, is there any chance when Operation.WaitForCompletion(CancellationToken) is returned, the provisioning State of the storage account is inProgress or something similiar?
there must be a bug in the service side.

**Comment by Zijian-Ju** [comment]
> > > @Zijian-Ju @blueww as @jsquire says, the `Operation<T>.Value` property is only available when the long running operation is done. In your code, you just started the LRO and immediately called the `.Value` property. It is not finished therefore an `InvalidOperationException` is thrown and it is telling you as the message says "the operation is not completed"
> > > If you just want the creation result, you have the following options:
> > > 
> > > 1. please use `WaitUntil.Completed` instead of `WaitUntil.Started`. In this way, the SDK will wait the operation for you.
> > > 2. call `Operation<T>.WaitForCompletion(CancellationToken)` method before you get the `Value`. This ensures you that the operation is completed.
> > 
> > 
> > @ArcturusZhang Thanks for your reply. Just for clarification. Does this mean we are waiting the creation of the storage to complete or just the ARM operation itself? I mean, is there any chance when Operation.WaitForCompletion(CancellationToken) is returned, the provisioning State of the storage account is inProgress or something similiar?
> 
> This is exactly how LRO works. `Operation.WaitForCompletion` is polling until the operation is done. The operation is done when the service returns a terminal state, therefore if this is happening
> 
> > I mean, is there any chance when Operation.WaitForCompletion(CancellationToken) is returned, the provisioning State of the storage account is inProgress or something similiar?
> 
> there must be a bug in the service side.

Thanks for the clarification. I am happy with closing this issue

**Comment by ArcturusZhang** [comment]
Closing since resolved
