### ISSUE TITLE
[QUERY] Azure.ResourceManager missing ArmDeploymentResource Object

### ISSUE THREAD

**Issue by WayneAASPLLC** [Azure/azure-sdk-for-net#32653]
### Library name and version

Azure.ResourceManager 1.3.2

### Query/Question

I am seeing no way to do ARM deployments in C# currently.
Intellisense is finding no objects with the word "deploy" in any of these resources. It is simply missing
New system that seems to be pushed has no way to create resources either. 
For example, most resources only allow update:
ArmClient.GetSubscriptionResource().GetCommunicationServiceResources().ToList()[0].Update <--- no way to create?

Is ArmClient.GetGenericResources().CreateOrUpdate now the only possibility to do this?

### Environment

VS 2022

Host:
  Version:      6.0.10
  Architecture: x64

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.402\

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by WayneAASPLLC** [comment]
I have found ways to do this now.
