### ISSUE TITLE
Azure.RequestFailedException RequestBodyTooLarge is thrown for message that is only 300 bytes

### ISSUE THREAD

**Issue by ursforrer** [Azure/azure-sdk-for-net#32663]
### Library name and version

Azure.Storage.Queues, Version=12.12.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8

### Describe the bug

Message to be enqueue: 

`{"type":"BlueprintFilesGroupUploaded","data":"{\"uploaderUserId\":\"0a70911e57becee32c7208d9143fbee9\",\"projectId\":\"de6b1c8b2c40cc73c0b408d916ad6c47\",\"groupId\":\"f322d1f6226c45f0af4b493f53231ca5\",\"containerId\":\"6cf9a4fb32eec2c5c6e908dacc908c1e\"}","targetId":"NotifyContainerViewerUsersOfUploadedBlueprintFilesGroupEventHandler"}`

Exception wo has be thrown.: 
The request body is too large and exceeds the maximum permissible limit.
RequestId:c11352d9-d003-0062-1442-f5c0cd000000
Time:2022-11-10T20:26:31.7360826Z
Status: 413 (The request body is too large and exceeds the maximum permissible limit.)
ErrorCode: RequestBodyTooLarge

Additional Information:
MaxLimit: 131584

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>RequestBodyTooLarge</Code><Message>The request body is too large and exceeds the maximum permissible limit.
RequestId:c11352d9-d003-0062-1442-f5c0cd000000
Time:2022-11-10T20:26:31.7360826Z</Message><MaxLimit>131584</MaxLimit></Error>

Headers:
Server: Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: c11352d9-d003-0062-1442-f5c0cd000000
x-ms-version: 2018-11-09
x-ms-error-code: RequestBodyTooLarge
Date: Thu, 10 Nov 2022 20:26:31 GMT
Content-Length: 287
Content-Type: application/xml

### Expected behavior

- Message could be enqued without any problems.

### Actual behavior

- Exception Azure.RequestFailedException is thrown with the Reason RequestBodyTooLarge

`The request body is too large and exceeds the maximum permissible limit.
RequestId:c11352d9-d003-0062-1442-f5c0cd000000
Time:2022-11-10T20:26:31.7360826Z
Status: 413 (The request body is too large and exceeds the maximum permissible limit.)
ErrorCode: RequestBodyTooLarge

Additional Information:
MaxLimit: 131584

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>RequestBodyTooLarge</Code><Message>The request body is too large and exceeds the maximum permissible limit.
RequestId:c11352d9-d003-0062-1442-f5c0cd000000
Time:2022-11-10T20:26:31.7360826Z</Message><MaxLimit>131584</MaxLimit></Error>

Headers:
Server: Windows-Azure-Queue/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: c11352d9-d003-0062-1442-f5c0cd000000
x-ms-version: 2018-11-09
x-ms-error-code: RequestBodyTooLarge
Date: Thu, 10 Nov 2022 20:26:31 GMT
Content-Length: 287
Content-Type: application/xml`

### Reproduction Steps

Could not be supplied. Happens randomly in our application. 

### Environment

dotnet 6 in a Docker Container hosted in the Azure App Service

**Comment by navba-MSFT** [comment]
@ursforrer Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ursforrer As per our docs, for Queue Storage [PUT Message operation](https://learn.microsoft.com/en-us/rest/api/storageservices/put-message), the encoded message can be up to 64 KiB in size for versions 2011-08-18 and newer, or 8 KiB in size for previous versions. 

Could you please share the `x-ms-request-id `of the most recent issue occurrence (not older than 2 days) of this issue ?  We will look at the backend logs for the cause of this issue. Awaiting your reply.
