### ISSUE TITLE
Performance difference in calling GetEntity and QueryAsync for PartitionKey and RowKey

### ISSUE THREAD

**Issue by yashpatel-iisc** [Azure/azure-sdk-for-net#32668]
### Library name and version

Azure.Data.Tables version 12.6.1

### Query/Question

Want to understand the performance difference between the below mentioned 2 scenarios:

First:
await tableClient.GetEntityAsync<TableEntity>(key.PartitionKey, key.RowKey)

Second:
tableClient.QueryAsync<TableEntity>(filter: "PartitionKey eq 'partition_key' and RowKey eq 'row_key'" );

Does both have them will perform equally for one is better than the other?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @yashpatel-iisc  - They should be roughly equivalent but, as with most performance specific questions, the best I can recommend is to test for your specific environment.
