### ISSUE TITLE
[TextAnalytics] RecognizeEntitiesBatchWithResolutionsTest failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32679]
TextAnalytics nightly test runs are failing with:

> Error message
> Expected: True
> But was:  False
> 
> 
> Stack trace
>    at Azure.AI.TextAnalytics.Tests.RecognizeEntitiesTests.RecognizeEntitiesBatchWithResolutionsTest() in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/RecognizeEntitiesTests.cs:line 327
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 
> 1)    at Azure.AI.TextAnalytics.Tests.RecognizeEntitiesTests.RecognizeEntitiesBatchWithResolutionsTest() in /Users/runner/work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/RecognizeEntitiesTests.cs:line 327

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2008006&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment]
This was fixed by the following pull request: https://github.com/Azure/azure-sdk-for-net/pull/32652
