### ISSUE TITLE
Re-record SQL tests with ResourceManager client 1.6

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-sdk-for-net#3267]

**Comment by jaczhan** [comment]
AzureRmSqlServerActiveDirectoryAdministrator API PR
https://github.com/Azure/azure-sdk-for-net/pull/3196

**Comment by shahabhijeet** [comment]
@jaredmoo Hopefully this can be done before next PR from SQL.
As we talked offline, either have a tiered approach as to all the tests that are part of PR needs new resource manager or re record all SQL tests with new Resource manager.
We are also going to push or taking a second look at all skipped SQL tests (if any)

**Comment by nathannfan** [comment]
@shahabhijeet  Please look at the PR asap.  We have two others also doing .NET work who should pick up this change.

**Comment by jaredmoo** [comment]
Done in #3272
