### ISSUE TITLE
[Search] AutoFlushInterval_FullBatch failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32678]
Search nightly test runs are failing with:

> Error message
> Expected: 256
> But was:  255
> 
> 
> Stack trace
>    at Azure.Search.Documents.Tests.BatchingTests.<AutoFlushInterval_FullBatch>d__25.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 618
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Search.Documents.Tests.BatchingTests.<AutoFlushInterval_FullBatch>d__25.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 621
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Search.Documents.Tests.BatchingTests.<AutoFlushInterval_FullBatch>d__25.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 621
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 
> 1)    at Azure.Search.Documents.Tests.BatchingTests.<AutoFlushInterval_FullBatch>d__25.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 618

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2002160&view=results

@jsquire for notification.

**Comment by ShivangiReja** [comment]
It was just a one time failure in one OS environment. Reran the pipeline and it's passing.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2002160&view=results
