### ISSUE TITLE
BlobContainerClient.StartCopyFromUriAsync doesn't copy Tags

### ISSUE THREAD

**Issue by romisak** [Azure/azure-sdk-for-net#32684]
Hi,

I'm using net6.0 and Azure.Storage.Blobs library, version 12.4.1 to copy a blob. 

Although I'm using BlobCopyFromUriOptions.CopySourceTagsMode = BlobCopySourceTagsMode.Copy the tags are not copied.
My code is below. Have I misunderstood the docs? Or is there a bug in the library?

Thanks, Roman Skrabis

using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;

const string connectionString = "";
const string containerName = "test";
const string path1 = "blob10";
const string path2 = "blob11";

BlobContainerClient blobContainerClient = new(connectionString, containerName);

await blobContainerClient.CreateIfNotExistsAsync();

BlobClient blobClient1 = blobContainerClient.GetBlobClient(path1);

// create original blob with tags
MemoryStream memoryStream = new(new byte[] { 1, 2, 3 });
BlobUploadOptions blobUploadOptions = new()
{
    Tags = new Dictionary<string, string> { { "tagname", "tagvalue" } }
};
await blobClient1.UploadAsync(memoryStream, blobUploadOptions);

// get tags for the original blob to make sure they are set OK
Azure.Response<GetBlobTagResult> tags1 = await blobClient1.GetTagsAsync();
foreach (KeyValuePair<string, string> tag in tags1.Value.Tags)
{
    Console.WriteLine($"Original: {tag.Key} = {tag.Value}");
}

BlobClient blobClient2 = blobContainerClient.GetBlobClient(path2);

// copy blob to path2, use options to specify that the tags should be copied 
BlobCopyFromUriOptions options = new()
{
    CopySourceTagsMode = BlobCopySourceTagsMode.Copy,
};
CopyFromUriOperation operation = await blobClient2.StartCopyFromUriAsync(blobClient1.Uri, options);
await operation.WaitForCompletionAsync();

// get tags for the copied blob, they should be the same, but they are empty
Azure.Response<GetBlobTagResult> tags = await blobClient2.GetTagsAsync();
foreach (KeyValuePair<string, string> tag in tags.Value.Tags)
{
    Console.WriteLine($"Copy: {tag.Key} = {tag.Value}");
}

**Comment by navba-MSFT** [comment]
@romisak Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@romisak Could you please use the below sample code snippet and check if that helps ?

```
                    BlobClient blobClient1 = containerClient.GetBlobClient("source.txt");
                    BlobClient destinationClient = containerClient.GetBlobClient("destination.txt");

                   // Create / upload the source blob with tags
                    MemoryStream memoryStream = new MemoryStream(new byte[] { 1, 2, 3 });
                    BlobUploadOptions blobUploadOptions = new BlobUploadOptions
                    {
                        Tags = new Dictionary<string, string> { { "tagname", "tagvalue" } }
                    };

                    await blobClient1.UploadAsync(memoryStream, blobUploadOptions);


                    // Copy source blob to destination blob with Blob Tags by passing an instance of BlobCopyFromUriOptions 
                    BlobCopyFromUriOptions options = new BlobCopyFromUriOptions
                    {
                        Tags = blobUploadOptions.Tags
                    };

                    // copy source blob with tags 
                    CopyFromUriOperation operation = await destinationClient.StartCopyFromUriAsync(blobClient1.Uri, options);
                    await operation.WaitForCompletionAsync();
```

More Info [here](https://github.com/Azure/azure-sdk-for-net/blob/20f0666f629ed9e09f4ae0acacaa1d155d5d13f8/sdk/storage/Azure.Storage.Blobs/tests/BlobBaseClientTests.cs#L1871).

**Comment by navba-MSFT** [comment]
@romisak Thanks for getting back. The BlobCopyFromUriOptions.Tags Property is the Options tags to set on the destination blob. Not valid if [CopySourceTagsMode](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobcopyfromurioptions.copysourcetagsmode?view=azure-dotnet#azure-storage-blobs-models-blobcopyfromurioptions-copysourcetagsmode) is set to [Copy](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobcopysourcetagsmode?view=azure-dotnet#azure-storage-blobs-models-blobcopysourcetagsmode-copy).

The [BlobCopySourceTagsMode](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobcopysourcetagsmode?view=azure-dotnet) enum says.
-- | -- | --
Copy | 1 | The tags on the source blob will be copied to the destination blob. Not compatible with Tags.
-- | -- | --
Replace | 0 | Default. The tags on the destination blob will be set to Tags.

Did you check the sample test case here to perform the same operation [here](https://github.com/Azure/azure-sdk-for-net/blob/20f0666f629ed9e09f4ae0acacaa1d155d5d13f8/sdk/storage/Azure.Storage.Blobs/tests/BlobBaseClientTests.cs#L1871) ?

**Comment by romisak** [comment]
@navba-MSFT The test is checking only the case when the CopySourceTagsMode is set to Replace (the default). You need one more test when the CopySourceTagsMode is set to Copy. This is where the bug is.

I found another test StartCopyFromUriAsync_Tags that is checking method SyncCopyFromUriAsync and this method is working OK with both versions of CopySourceTagsMode.

Roman

**Comment by navba-MSFT** [comment]
@romisak Thanks for getting back. I am trying to create a repro at my end. I will keep you posted.

In the meantime, Could you confirm if you have tried with [SyncCopyFromUriAsync_copyTags( ) ](https://github.com/Azure/azure-sdk-for-net/blob/20f0666f629ed9e09f4ae0acacaa1d155d5d13f8/sdk/storage/Azure.Storage.Blobs/tests/BlobBaseClientTests.cs#L3118)?

**Comment by romisak** [comment]
Yes, I can confirm that for the SyncCopyFromUriAsync method the options work as expected.

Roman

**Comment by navba-MSFT** [comment]
@romisak StartCopyFromUri and SyncCopyFromUri both share the BlobCopyFromUriOptions options bag. Copying tags is only applicable to SyncCopyFromUri.

**Comment by romisak** [comment]
Thanks for the explanation, I probably overlooked this in the docs.

**Comment by navba-MSFT** [comment]
@romisak Do you have any follow-up questions on this or are we good to close this out ?

**Comment by romisak** [comment]
@navba-MSFT Let's close it. Thanks for your help.

**Comment by markheath10** [comment]
Have just run into this. It's very non-intuitive. I think the documentation for CopySourceTagsMode & BlobCopyFromUriOptions  should be updated to make this explicit
