### ISSUE TITLE
[QUERY] Why is there a length limit on `MessageId`, `SessionId`, `PartitionKey`, `ReplyToSessionId`

### ISSUE THREAD

**Issue by minghuaw** [Azure/azure-sdk-for-net#32689]
### Library name and version

Azure.Messaging.ServiceBus - 7.12.0-beta.1

### Query/Question

This is just a general inquiry on why there are length limits for the `MessageId`, `SessionId`, `PartitionKey`, `ReplyToSessionId` fields in  `ServiceBusMessage`? It doesn't seem like there is such limits in the go-lang sdk?

**Comment by jsquire** [comment]
The length is limited on the service-side.   My assumption is that we're validating client-side for two reasons - parity with the legacy packages and to help improve the developer experience.   For example, consider the scenario where a developer is building up a batch of 100 messages.   One of those messages has a `MessageId` that is too long.   When publishing the batch, the entire batch is rejected and the developer has to go through the batch to figure out which messages is causing the failure.

@JoshLove-msft is likely to have more context and can validate my assumption.

**Comment by JoshLove-msft** [comment]
> The length is limited on the service-side. My assumption is that we're validating client-side for two reasons - parity with the legacy packages and to help improve the developer experience. For example, consider the scenario where a developer is building up a batch of 100 messages. One of those messages has a `MessageId` that is too long. When publishing the batch, the entire batch is rejected and the developer has to go through the batch to figure out which messages is causing the failure.
> 
> @JoshLove-msft is likely to have more context and can validate my assumption.

Yes, this is mostly meant to have these long standing service limits validated up front to avoid creating invalid messages that will not be able to be sent. @richardpark-msft did we decide not to do this validation in Go?

**Comment by richardpark-msft** [comment]
Just to complete the loop, the Go SDKs prefer to let the service validate parameters when it makes sense. So even without client-side validation you won't be able to send messages with a >128 byte message ID.
