### ISSUE TITLE
Adding Support for using Raw Tokens for Authentication

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3274]
There are still scenarios where you need to use username/password for performing certain tasks that cannot be done using Service Principal.
One such task is to delete group in graph where delete rights are commonly associated/usually assigned to MSID/username.
https://github.com/Azure/azure-sdk-for-net/pull/3273

Cost: 2

**Comment by markcowl** [comment]
@shahabhijeet We already had support for this in the test framework, is this somethign that has regressed recently?

**Comment by shahabhijeet** [comment]
The work has been done.
Need to write test that will test against Graph Token.
Management Token has been tested and tests are in place.
