### ISSUE TITLE
Missing in 2022 Nuget

### ISSUE THREAD

**Issue by WayneAASPLLC** [Azure/azure-sdk-for-net#32754]
Package: Azure.ResourceManager.Applications.Containers v1.0.0-beta.1 does not appear to exist

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fdc40d36-a477-fc74-891b-b02b5e083cc9
* Version Independent ID: ae34dfe7-a54c-36ef-f0b6-6d411d7e9d12
* Content: [GitHubProvider Class (Azure.ResourceManager.Applications.Containers.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.applications.containers.models.githubprovider?view=azure-dotnet-preview)
* Content Source: [xml/Azure.ResourceManager.Applications.Containers.Models/GitHubProvider.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Applications.Containers.Models/GitHubProvider.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by WayneAASPLLC** [comment]
There was another way to do this where this missing package is not needed.
