### ISSUE TITLE
[BUG] Azure Function Trigger with Managed Identity intermittently working on consumption plan

### ISSUE THREAD

**Issue by josdeweger** [Azure/azure-sdk-for-net#32751]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.8.1

### Describe the bug

We followed the following documentation to use Managed Identity in combination with a ServiceBus trigger in our Azure Function running on a consutmpion plan (Y1): https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2. The functions Managed Identity has the DataReader role on a specific ServiceBus topic.

Our trigger looks like this:

```
[FunctionName(nameof(MyConsumer))]
[ExponentialBackoffRetry(MaxRetryCount, MinimumBackoffRetryInterval, MaximumBackoffRetryInterval)]
public async Task Run([ServiceBusTrigger("%SomeTopicName%", "%SomeSubscriptionName%", Connection = "ServiceBusConnection")]   
    string myMessage, 
    int deliveryCount,
    string messageId)
    { ... }
```

In our appsettings.{environment}.json we have the following setting:
```
"ServiceBusConnection": {    
    "fullyQualifiedNamespace": "{name}.servicebus.windows.net"  
}
```

We load the appsettings.{environment}.json file on function startup like this:
```
builder.AddJsonFile(Path.Combine(context.ApplicationRootPath, $"appsettings.{context.EnvironmentName}.json"), optional: true, reloadOnChange: false);
```

Initially this works, the function triggers when a new message is put on the topic. However, after a while the trigger stops working intermittently. Sometimes for a couple of seconds, sometimes for minutes, but we have seen cases where after a weekend messages were still sitting on the servicebus topic.

It looks similar to the following (fixed) issue: https://github.com/Azure/azure-sdk-for-net/issues/26663
Based on that I played with the following setting to get ScaleController logs:
```
"name": "SCALE_CONTROLLER_LOGGING_ENABLED","value": "AppInsights:Verbose"
```

Soon enough we saw logs like: `Specified connection string is null or empty for connection: ServiceBusConnection. Invalid connection.`

Based on this I got the hunch that maybe the appsetting from the json file was not available anymore, so I added the `ServiceBusConnection__fullyQualifiedNamespace` setting to the appsettings in the Configuration blade of the function, and the ScaleController logs changed to: 
`Created ServiceBusClient with ManagedIdentity`

After this everything worked as expected.

### Expected behavior

I would expect the appsettings.json settings to be used, also on a Consumption Plan. But maybe this assumption is wrong and this is by design, and the AppSettings on the Configuration blade of the Function App should always be used?

### Actual behavior

See: Describe the bug

### Reproduction Steps

Create a Function App with a ServiceBus trigger on a Consumption plan. Provide the Azure ServiceBus DataReader role on the topic to the Function Apps Identity. Provide the ServiceBusConnection__fullyQualifiedNamespace in the appsettings and load them on Startup. Send a couple of messages to the SB, wait for 10 minutes, send some more messages. The trigger is not fired.

### Environment

Serviceplan Y1 on windows
Function app: net6.0
Microsoft.Azure.Functions.Extensions: 1.1.0
Microsoft.Azure.WebJobs.Extensions.ServiceBus: 5.8.1
Microsoft.NET.Sdk.Functions: 4.1.3

**Comment by jsquire** [comment]
@JoshLove-msft:  I'm not sure if this is something that would be related to the bindings or the runtime.   Would you please help triage and transfer this to the Functions repo if needed?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
For deployed function apps, the connection settings are meant to be included in the Application settings as you have mentioned. This is not specific to the Service Bus extension.
The link you [referenced ](https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2#connect-to-service-bus-in-your-function-app) mentions the expected configuration steps.
