### ISSUE TITLE
[BUG] GetExperimentAsync throws String was not recognized as a valid TimeSpan

### ISSUE THREAD

**Issue by marcelohazuma** [Azure/azure-sdk-for-net#32756]
### Library name and version

Azure.ResourceManager.Chaos 1.0.0-beta.1

### Describe the bug

I'm trying to read an Experiment using GetExperimentAsync and getting a System.FormatException with the message "String was not recognized as a valid TimeSpan.".

I believe the issue is related to the how the Duration property is parsed, since the content is "PT10M" and the SDK is mapping it to a TimeSpan.

### Expected behavior

GetExperimentsAsync should return the ExperimentResource object, as declared.

### Actual behavior

I'm able to see the call in Fiddler, and the request and response messages are ok, the issue happens during the Json parsing.

### Reproduction Steps

Below is the sequence of commands in use:

```
TokenCredential azureCredential = new DefaultAzureCredential();
ArmClient armClient = new ArmClient(azureCredential);
SubscriptionResource subscription = await armClient.GetDefaultSubscriptionAsync().ConfigureAwait(false);
ResourceGroupResource resourceGroup = await subscription.GetResourceGroupAsync(resourceGroupName).ConfigureAwait(false);
ExperimentResource experiment = await resourceGroup.GetExperimentAsync(experimentName).ConfigureAwait(false);
```

This is the Experiment:
```
{"type":"Microsoft.Chaos/experiments","id":"/subscriptions/abe76e3f-76b7-4c70-9f9c-16686b969eae/resourceGroups/chaoslab/providers/Microsoft.Chaos/experiments/ChaosLab-VMSS","name":"ChaosLab-VMSS","systemData":{"createdAt":"2022-11-29T15:09:32.5573287+00:00","lastModifiedAt":"2022-11-29T15:44:16.1147069+00:00","createdByType":"User"},"identity":{"type":"SystemAssigned","principalId":"11f30c36-c8ce-4400-bec3-31eed5efc85a","tenantId":"7e1fdf9f-3251-4552-aea8-a9cff7a5a149"},"location":"eastus","properties":{"selectors":[{"type":"List","id":"Selector1","targets":[{"id":"/subscriptions/abe76e3f-76b7-4c70-9f9c-16686b969eae/resourceGroups/ChaosLab/providers/Microsoft.Compute/virtualMachineScaleSets/CLVMSS/providers/Microsoft.Chaos/targets/Microsoft-VirtualMachineScaleSet","type":"ChaosTarget"}]}],"steps":[{"name":"Step1","branches":[{"name":"Branch1","actions":[{"type":"continuous","selectorId":"Selector1","duration":"PT10M","parameters":[{"key":"abruptShutdown","value":"true"},{"key":"instances","value":"[\"1\"]"}],"name":"urn:csci:microsoft:virtualMachineScaleSet:shutdown/1.0"}]}]}]}}
```

### Environment

.NET Framework 4.7.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by brrusino** [comment]
This is a known issue that stems from AutoRest V3's managing of all duration strings as `TimeSpan` types automatically, which presented problems without some additional configuration on our end to correctly serialize/deserialize our expected ISO8601 duration strings. This fix has been checked in and not yet published, but there is [another active bug that we have against AutoRest](https://github.com/Azure/autorest.csharp/issues/2921) which blocks a key part of our resource provider's functionality currently. Short term mitigation of both issues would be to use the older ChaosManagementClient until the linked AutoRest bug is fixed.

**Comment by live1206** [comment]
[DelayAction.Duration](https://github.com/Azure/azure-sdk-for-net/blob/92b8f64359a75d97ff9fc1ddb7bd3ebeedaa9c68/sdk/chaos/Azure.ResourceManager.Chaos/src/Generated/Models/DelayAction.cs#L39) and [ContinuousAction.Duration](https://github.com/Azure/azure-sdk-for-net/blob/92b8f64359a75d97ff9fc1ddb7bd3ebeedaa9c68/sdk/chaos/Azure.ResourceManager.Chaos/src/Generated/Models/ContinuousAction.cs#L51) are defined as `TimeSpan`, but the service responses are not. 
We need to update the type to `string` and mitigate the breaking change.

**Comment by live1206** [comment]
This has been fixed in https://github.com/Azure/azure-sdk-for-net/pull/32905/files#diff-5a0032be1399909cf3474a0a10d7a54213410a05335205e4bfce6d374f03e355.
@marcelohazuma Please help to verify this works for you now.
