### ISSUE TITLE
Examples should be in a Code Block

### ISSUE THREAD

**Issue by anime-shed** [Azure/azure-sdk-for-net#32752]
![image](https://user-images.githubusercontent.com/67512697/204537894-cb4c5e9a-05df-46c3-8a32-4622969ff782.png)

Should be in a code block for easier understanding, similar to:

![image](https://user-images.githubusercontent.com/67512697/204538152-7ac3b9d8-dfaa-493f-8c60-6c435b40f585.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e02c19ec-2424-6359-a4cd-ad061f2c3180
* Version Independent ID: 5421a6b4-8c29-2143-1df5-7bd90375437f
* Content: [CosmosClientOptions Class (Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.cosmos.cosmosclientoptions?view=azure-dotnet-preview#feedback)
* Content Source: [xml/Azure.Cosmos/CosmosClientOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Cosmos/CosmosClientOptions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Azure.Cosmos` package is maintained as [#3591](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3591).
