### ISSUE TITLE
Document for Microsoft.Azure.Management.WebSites.Models

### ISSUE THREAD

**Issue by wrharper-AASP** [Azure/azure-sdk-for-net#32757]
How do you use this? There are no instructions in the docs saying what the (string, string) is in the IDictionary. What do you put in these fields? How can I add the downloaded content files to a deployment function? This is he depreciated version of the namespace but this part is the same in the latest version, still no info on how the Files in FunctionEnvelopeData works.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3c775e17-037c-763b-3c17-7b3e1c5b04c1
* Version Independent ID: b30456cc-43b8-7501-5855-4650dc844245
* Content: [FunctionEnvelope.Files Property (Microsoft.Azure.Management.WebSites.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.functionenvelope.files?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.WebSites.Models/FunctionEnvelope.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/FunctionEnvelope.xml)
* Service: **app-service**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by WayneAASPLLC** [comment]
It is hard to understand why C# can't just do it as easy as PowerShell: Publish-AzWebapp -ResourceGroupName <group-name> -Name <app-name> -ArchivePath <zip-file-path> 
This is an issue because I have built an entire deployment system, and this is the only thing missing now. I have no way to publish upon deployment.

**Comment by WayneAASPLLC** [comment]
I mimicked PowerShell's REST call to do this but this should be possible so I am hoping to keep this open so this can be implemented into the correct library properly.

`using (var s = File.OpenRead(json.WhatsAppFunctionZipDeployPath))
            {
                HttpClient client = new HttpClient();
                var byteArray = Encoding.ASCII.GetBytes(user.Data.PublishingUserName + ":" + user.Data.PublishingPassword);
                client.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("Basic", Convert.ToBase64String(byteArray));
                HttpContent fileContent = new StreamContent(s);
                fileContent.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/zip");
                r = client.PostAsync(deployUrl, fileContent).Result;

                int NumStatusChecks = 600;
                int numChecks = 0;
                while (r.StatusCode == HttpStatusCode.Accepted && numChecks < NumStatusChecks)
                {
                    await Task.Delay(2000);
                    r = client.GetAsync(deploymentStatusUrl).Result;
                    numChecks++;
                    form.OutputRT.Text += ", " + numChecks.ToString();
                }
            }`

**Comment by HarveyLink** [comment]
Hi @wrharper-AASP , Thank you for using Azure SDK for .NET.
The package: `Microsoft.Azure.Management.WebSites` you are using has been deprecated.
We suggest to use new SDK: [Azure.ResourceManager.AppService](https://www.nuget.org/packages/Azure.ResourceManager.AppService/1.1.0-beta.4)
For the document and sample, you could refer to: 
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md
https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/websites/Azure.ResourceManager.AppService/samples/Generated/Samples
