### ISSUE TITLE
[MQ] Provide a general guidance and best practice guide to mitigate the breaking changes in dotnet libraries

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-net#32769]
### Information

We have plenty ways to mitigate the breaking changes, but we do not have a detailed guidance or best practice documentation yet. We need to have that so that one could have a clear guide and know what they could do when facing breaking changes.

**Comment by live1206** [comment]
https://github.com/Azure/autorest.csharp/pull/3276/files
