### ISSUE TITLE
Expose GenericResources.deleteById()

### ISSUE THREAD

**Issue by martinsawicki** [Azure/azure-sdk-for-net#3277]
apparently porting this special case logic from the java SDK was missed

**Comment by hovsepm** [comment]
@martinsawicki are you talking about this? https://github.com/Azure/azure-sdk-for-net/blob/Fluent/src/ResourceManagement/ResourceManager/Core/GroupableResources.cs#L101

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#13
