### ISSUE TITLE
We are seeing renew session locks every couple of milliseconds

### ISSUE THREAD

**Issue by stoepa** [Azure/azure-sdk-for-net#32777]
### Library name and version

Azure.Messaging.ServiceBus 7.11.1

### Query/Question

We are seeing some very weird behavior and not sure what is causing it. There is an unusual amount of the following log entries.

Azure.Messaging.ServiceBus: Information: identityemailqueue-9cafe985-fac3-4c10-a838-613e10c18cbe-STHEUNISDebug: RenewSessionLockAsync done. SessionId = THEUNISDebug
Azure.Messaging.ServiceBus: Information: identityemailqueue-9cafe985-fac3-4c10-a838-613e10c18cbe: Processor RenewSessionLock complete. SessionId = THEUNISDebug
Azure.Messaging.ServiceBus: Information: identityemailqueue-9cafe985-fac3-4c10-a838-613e10c18cbe: Processor RenewSessionLock start. SessionId = THEUNISDebug
Azure.Messaging.ServiceBus: Information: identityemailqueue-9cafe985-fac3-4c10-a838-613e10c18cbe-STHEUNISDebug: RenewSessionLockAsync start. SessionId = THEUNISDebug

This process occurs the whole time.

Setup is the following:

```
// DI portion
services.AddAzureClients(builder =>
                {
                    builder.AddServiceBusClient(appSettings.AzureServiceBus.ConnectionString);
                });

// Resolved serviceBusClient withing IHostedService via constructor injection.
this.serviceBusProcessor = serviceBusClient.CreateSessionProcessor(appSettings.AzureServiceBus.ProcessorQueueName, new ServiceBusSessionProcessorOptions()
            {
                ReceiveMode = ServiceBusReceiveMode.PeekLock,
                SessionIds = { sessionId.Id }
            });```

// Called within StartAsync method
serviceBusProcessor.ProcessMessageAsync += ProcessMessage;
            serviceBusProcessor.ProcessErrorAsync += ServiceBusProcessor_ProcessErrorAsync;

            serviceBusProcessor.SessionClosingAsync += ServiceBusProcessor_SessionClosingAsync;
            serviceBusProcessor.SessionInitializingAsync += ServiceBusProcessor_SessionInitializingAsync;

            await serviceBusProcessor.StartProcessingAsync(cancellationToken);

```

There are not exceptions being emitted, but we see that their is like > 25K requests to the Azure service bus. It seems to stop after some interval, assume it is the MaxAutoLockRenewalDuration which seems to correlate to the 5mins of activity.

Any ideas why this would be happening. We investigated other clients, and the same behaviour was not found.

### Environment

Dotnet 6.
Windows 11.
Service Fabric 9.0.1028.9590
Visual Studio 17.4.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Can you share the logs with timestamps? If you are passing in one session Id, then there shouldn't be any concurrency happening. I would expect to see the session lock renewed based on the configured LockDuration for the queue. Can you share what the LockDuration is?

**Comment by stoepa** [comment]
Hi @JoshLove-msft 

The lock duration is set on the Azure Service Bus queue, and is currently set to 30 seconds.

![image](https://user-images.githubusercontent.com/6512585/204980889-2dc5dd9c-c752-4683-91eb-a46fb78bfde4.png)

No configuration is done on client side in terms of durations or timings.

I will attach the logs here as well, but now I am stumped. It's seems as if the issue went away, I am testing from a different machine and network today, so it might now point to either network or machine, but really not sure what is going on, for reference I am also adding this image to show the spike for yesterday.

![image](https://user-images.githubusercontent.com/6512585/204981645-c472a831-6685-4f67-bcf5-4f280e7d7fcc.png)

I will have to monitor it to see what is happening.
[logs.txt](https://github.com/Azure/azure-sdk-for-net/files/10129922/logs.txt)

**Comment by JoshLove-msft** [comment]
Are the attached logs from when the issue was happening or are they from the latest run where it is not happening? 

Can you confirm whether or not any exceptions were being logged when the issue was occurring? From looking at the code, the only way I can see something like this happening is if the renew session calls are failing and we keep retrying. I do think this could happen if there is a network issue, but the fact that requests made it to the service indicates that it is unlikely that it was a network issue.

**Comment by stoepa** [comment]
The logs are from now, as I am working remotely today, so I am not able to provide logs on the "affected network".

There were no exceptions being thrown at all, just a flood of renew sessions.

I will try and get the logs from someone at the office, to see if we can pinpoint the issue, and will upload them as soon as I receive them.

**Comment by JoshLove-msft** [comment]
> There were no exceptions being thrown at all, just a flood of renew sessions.

To clarify I'm asking if there are exceptions being logged, not actually being thrown. The log would include this:

"Processor RenewSessionLock Exception:"

**Comment by stoepa** [comment]
Apologies, I use the terms interchangeably, there were no exceptions in the logs, literally these lines were being outputted every couple of milliseconds.

```
Azure.Messaging.ServiceBus: Information: identityemailqueue-9cafe985-fac3-4c10-a838-613e10c18cbe-STHEUNISDebug: RenewSessionLockAsync done. SessionId = THEUNISDebug
Azure.Messaging.ServiceBus: Information: identityemailqueue-9cafe985-fac3-4c10-a838-613e10c18cbe: Processor RenewSessionLock complete. SessionId = THEUNISDebug
Azure.Messaging.ServiceBus: Information: identityemailqueue-9cafe985-fac3-4c10-a838-613e10c18cbe: Processor RenewSessionLock start. SessionId = THEUNISDebug
Azure.Messaging.ServiceBus: Information: identityemailqueue-9cafe985-fac3-4c10-a838-613e10c18cbe-STHEUNISDebug: RenewSessionLockAsync start. SessionId = THEUNISDebug
```

**Comment by JoshLove-msft** [comment]
I don't see how this could happen outside of there being an issue with the service not actually renewing the lock but having no exceptions. Would you be able to file a support ticket in the portal so that the service team can review the server logs?
