### ISSUE TITLE
No added useful information

### ISSUE THREAD

**Issue by RichardMcCormack** [Azure/azure-sdk-for-net#32771]
This document may as well not exist - it provides NO useful information above what is available from browsing the source code.
FFS: Document extract is only useful when useful information has been added to get extracted.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4cc93970-33b4-6d42-93f5-17ecda242b65
* Version Independent ID: eb2fb4dd-15c5-4a6a-6969-4c8c22279b2c
* Content: [BackupLongTermRetentionPolicyInner.RecoveryServicesBackupPolicyResourceId Property (Microsoft.Azure.Management.Sql.Fluent.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.sql.fluent.models.backuplongtermretentionpolicyinner.recoveryservicesbackuppolicyresourceid?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Sql.Fluent.Models/BackupLongTermRetentionPolicyInner.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Sql.Fluent.Models/BackupLongTermRetentionPolicyInner.xml)
* Service: **sql-database**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ArthurMa1978** [comment]
This is a reference doc that auto-generated from swagger spec, should be improved from source that service team can add more info.
