### ISSUE TITLE
Wrong NuGet package name "Azure.Batch"

### ISSUE THREAD

**Issue by svdHero** [Azure/azure-sdk-for-net#32779]
In the Section "Client library" the installation instructions for the NuGet package are either

```
Install-Package Azure.Batch
```
or
```
dotnet add package Azure.Batch
```

However, the NuGet package "Azure.Batch" does not exist in NuGet, see [search results](https://www.nuget.org/packages?q=azure.batch). Should this read "Microsoft.Azure.Batch" or what is the latest NuGet package for using Azure Batch?

It confuses me, because Azure Storage for example changed its NuGet package name from "WindowsAzure.Storage" to "Microsoft.Azure.Storage" to "Azure.Storage". However, I cannot find "Azure.Batch" as explained above.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 529f9779-84e2-535c-bb64-a7655325e6c2
* Version Independent ID: d8f819df-2e27-f6cb-81aa-05b81cbc6e5f
* Content: [Azure Batch SDK for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/batch?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/batch.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/batch.md)
* Service: **batch**
* GitHub Login: @paterasMSFT
* Microsoft Alias: **mipatera**

**Comment by jsquire** [comment]
@scottaddie:  It looks like this package was unlisted, based on its [NuGet page](https://www.nuget.org/packages/Azure.Batch).   Can you help determine what the right course of action is here?

**Comment by SaurabhSharma-MSFT** [comment]
@scottaddie Can you please help here.
