### ISSUE TITLE
[FEATURE REQ] Expand the sparse matrix for core and mgmt core tests

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#32785]
Right now the sparse matrix pins each project to either package reference or project reference.  We saw recently with this issue https://github.com/Azure/azure-sdk-for-net/issues/32733 that this can allow bugs to get checked into main which make debugging and finding the issue a lot more difficult.  It would be better to catch these at PR time so we can fix them and disrupt everyone in the repo.

One option is to expand the parse matrix slightly so that every library runs on both project and package reference variants and it would be very useful if both of those could pick different platforms to take advantage of the free extra coverage since we already need to run it twice.

**Comment by weshaggard** [comment]
@hallipr we should try to update the matrix such that the project vs package reference is included for all the projects not just some sparse ones. @benbp any easy way to do that in the matrix file?

**Comment by benbp** [comment]
@weshaggard The easy way is to pass `-NonSparseParameters AdditionalTestArguments` but that will double the number of test jobs. Right now we set `NumberOfTestProjectsPerJob` to 20, which ends up creating 12 test jobs. We only have 6 OS/framework combinations, so we won't get any "free extra coverage." We could double the test projects per job count, which would give us 6 test jobs, which we will then double back to 12 with both non-sparse reference types.

So I think the options here are: double the number of dependency test jobs or double the time of the core pipeline, unless there's a better way to validate project and package references without having to run the full test suite.

**Comment by weshaggard** [comment]
@benbp I think doubling the time for core pipeline for now will be fine. We can also consider adding more agents as well.

**Comment by weshaggard** [comment]
@m-nash another option we could choose here is to only use ProjectReferences for these tests as the main point of them is to test out the core changes you are making to ensure they don't break others. Using the PackageReference in this larger test runs isn't as useful in the core pipelines. I will give this a little more thought.
