### ISSUE TITLE
[BUG] DataLake Upload can remove content of the blob if exception is thrown

### ISSUE THREAD

**Issue by tovyhnal** [Azure/azure-sdk-for-net#32780]
### Library name and version

Azure.Storage.Files.DataLake 12.12.1

### Describe the bug

Since Upload is [multi request process](https://github.com/Azure/azure-sdk-for-net/issues/31836), it can happen that if something wrong happens in the middle, blob content will be completely removed.

Upload consist of following requests
1. PUT (test.json?resource=file) - creates file (and replace existing one if exists)
2. PATCH (test.json?action=append&position=0) - upload actual data to blob
3. PATCH (test.json?action=flush&position=42) - flush the file

The problems happens if we execute step 1, but do not execute step 2 -> we loose the blob content.

This can happen for multiple reason as we see in our logs
- CancellationToken is fired
- Pod is being restarted. Process is getting terminated ....
- Some network transient issue.

### Expected behavior

Blob content is not deleted during upload operation

### Actual behavior

Blob content is deleted and completely lost during Upload operation in some scenarios desribed above.

### Reproduction Steps

```
        var config = SetConfiguration();

        // Get the instance of DataLakeFileClient for some file.
        DataLakeFileClient client = await GetFileClient(config);

        // Make sure blob is always there.
        await client.UploadAsync(BinaryData.FromObjectAsJson(new DataLakeItem()
        {
            Number = 0
        }).ToStream(), true, default);

        for (int i = 1; i <= 10; i++)
        {
            // Simulate pod restart/process termination. You can tune the number
            var cts = new CancellationTokenSource(20);

            Stopwatch sw = Stopwatch.StartNew();
            try
            {
                // Upload file again
                await client.UploadObject(new DataLakeItem()
                {
                    Number = i
                }, true, cts.Token);
            }
            catch (Exception e)
            {
                // Here it may happen then not all http requests finished.
                Console.WriteLine($"{i}: Exception thrown after {sw.ElapsedMilliseconds}ms");
            }

            // Read the file, which should be ALWAYS present.
            var dlItem = await client.ReadAsync();

            if (dlItem.Value.ContentLength == 0)
            {
                // How come we got empty blob if we never delete it????
                Console.WriteLine($"{i}: Empty object return, which should never happen!");
            }
            else
            {
                Console.WriteLine($"{i}: Object returned");
            }
        }
```

### Environment

C:\repo\CXP-Main>dotnet --info
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  6.0.306 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

**Comment by SaurabhSharma-MSFT** [comment]
@tovyhnal We are looking into it and get back to you for any additional information.
