### ISSUE TITLE
[QUERY] Mocking for ReservationQuotaCollection and SubscriptionResource methods

### ISSUE THREAD

**Issue by Launcelot555** [Azure/azure-sdk-for-net#32790]
### Library name and version

Azure.ResourceManager.Reservations 1.1.0

### Query/Question

I'm implementing the following extension methods to automate quota requests:

ReservationQuotaCollection:
- CreateOrUpdateAsync
- GetAsync

SubscriptionResource:
- GetAllReservationQuota

Additionally, mocking the ArmClient and its methods are tricky due to the extension methods it implements.

It's unclear how to mock these methods for unit testing -- documentation seems to suggest using ImplementationClient, but there aren't really any useful examples. 

Do you have any suggestions on how to proceed here?

### Environment

- Azure App Service
- VS Code IDE

**Comment by ArthurMa1978** [comment]
Thank you @Launcelot555 for reaching us.
For your question, it will be supported by https://github.com/Azure/autorest.csharp/issues/2112， please follow that issue and we planned to release it by the end of this month.
