### ISSUE TITLE
Validate that nuget packages to be released have symbols

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#32791]
To make sure we have proper source links and packages will have proper symbols when debugging, getting stack traces, etc., we should validate the symbols and compiler flags have been properly set. These appear as the bottom 3 checks in NuGet Package Explorer:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/1532486/204943808-a7aa2346-67c2-41de-a667-b619c5e81e39.png">

While working on PR #32598 I learned that in order for NuGet Package Explorer to show proper source link information, the symbols (_.pdb_s) have to be in the _.nupkg_, the symbol package (_.snupkg_) has to be **next** to the _.nupkg_, or the symbol package has to be published. Until we release, the latter won't happen and we don't package _.pdb_s into the _.nupkg_, so we'll need to download artifacts with the _.nupkg_ and _.snupkg_ together to verify.

**Comment by pallavit** [comment]
Is this something we will have to do manually in our release pipelines before the package release step?

**Comment by heaths** [comment]
Yes, this is something people should manually be doing now. We should be able to automate it.
