### ISSUE TITLE
Key Vault samples should be rewritten as recorded tests

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#32792]
Now that we have the `SNIPPET` symbol on which to condition snippets vs. running samples, we should rewrite the Key Vault samples - at least Keys - using the `RecordedTestBase`. This is because Managed HSM tests - which also run the Keys packages tests - can occasionally fail because a backup/restore job is running and there's no effective way to make sure those run serially: tests are `[NonParallelizable]`, but assemblies run in parallel because that's how we run them upstream via _eng/service.proj_.

To best take advantage of the `[IgnoreServiceError]` attribute we need to use recorded tests. It's not worth porting to support non-recorded tests, probably, since doing recorded tests may give us a little more coverage anyway. At the very least it'll better test PRs.

The `[IgnoreServiceError]` assembly can and should be put on the `SampleFixture` base class so any keys method that fails with those specific-as-possible errors are ignored (or marked inconclusive).

**Comment by pallavit** [comment]
I think this issue is similar to issue #28953 and something that we can address as part of the test initiative we are taking with KV

**Comment by heaths** [comment]
This is separate. The samples aren't recorded and would need some fundamental rewrites. It's not expensive, but just hasn't been priority. It'll take some work, though, as they predate most of our contemporary samples procedures.
