### ISSUE TITLE
[BUG] Blob client does not work correctly with Azurite

### ISSUE THREAD

**Issue by Jejuni** [Azure/azure-sdk-for-net#32809]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Describe the bug

The blob client and related types (`BlobServiceClient`, `BlobContainerClient`, `BlobClient`) do not work correctly locally.

Given the following connection string: `"DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:51264/devstoreaccount1"`

With an Azurite container listening on the specified port `51264` and started via `docker run --rm -p 51264:10000 mcr.microsoft.com/azure-storage/azurite:3.20.1 azurite-blob --blobHost 0.0.0.0` 

The URI built set when a `BlobClient` is created is missing the containerName part and thus the request fails.

### Expected behavior

URIs should be created correctly and the BlobClient work with a local Azurite container.

### Actual behavior

Client crashes with the following Exception:

![image](https://user-images.githubusercontent.com/33608497/205106200-864e542e-d30c-47fe-929b-94222d3d6e3d.png)

### Reproduction Steps

Via terminal start an Azurite container: `docker run --rm -p 51264:10000 mcr.microsoft.com/azure-storage/azurite:3.20.1 azurite-blob --blobHost 0.0.0.0` (if port 51264 is not available choose any other and adapt connection string below)

Run the following code:

```cs
const string blobPort = "51264";
const string connectionString =
    "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://localhost:" +
    blobPort + "/devstoreaccount1";

var blobServiceClient = new BlobServiceClient(connectionString);
var blobContainerName = Guid.NewGuid().ToString("D");

BlobContainerClient blobContainerClient = await blobServiceClient.CreateBlobContainerAsync(blobContainerName);

var blobClient = blobContainerClient.GetBlobClient("data");

_ = await blobClient.UploadAsync(new MemoryStream(new byte[] { 0 }), true);

BlobDownloadInfo download = await blobClient.DownloadAsync();
```

Observe the line `_ = await blobClient.UploadAsync(new MemoryStream(new byte[] { 0 }), true);` throwing an exception.
Inspect the URI property on the clients. The `blobClient` is missing the containerName part in the URI.

### Environment

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

Visual Studio: 17.4.2

**Comment by navba-MSFT** [comment]
@Jejuni  Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Jejuni  I used the same above code to upload the blob to the local Azurite and it worked fine. The issue seems to be occurring only while I ran it from the docker azurite. I am checking this further and I will get back to you with an update.

**Comment by navba-MSFT** [comment]
@Jejuni The issue seems to be occurring only with blobPort = "51264". As a workaround, Could you please try with `const string blobPort = "10000";`  ? Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Jejuni @HofmeisterAn Thanks for getting back Please update your code as below and it should work for port `51264` too.

```
// var blobClient = blobContainerClient.GetBlobClient("data");  // Comment this line and use below instead

var blobClient = new BlobClient(new Uri(blobContainerClient.Uri.ToString() + "/data"),
                                new StorageSharedKeyCredential("devstoreaccount1", "Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="));
                                
   ```
   
Hope this helps.

**Comment by HofmeisterAn** [comment]
> Please update your code as below and it should work for port 51264 too.

Well, that is what I wrote [here](https://github.com/testcontainers/testcontainers-dotnet/issues/682#issuecomment-1323350706). Chaning the `GetBlobClient("testdata")` to `GetBlobClient(containerName + "/testdata")` "works", but is probably not intended.

**Comment by navba-MSFT** [comment]
@HofmeisterAn I agree. Seems like a Bug with BlobContainerClient. I am adding the Service team to look into this further.

CC: @xgithubtriage @seanmcc-msft @amnguye

**Comment by PramodValavala-MSFT** [comment]
@Jejuni @HofmeisterAn When using a connection string, the SDK checks against [this list of ports](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Common/src/Shared/Constants.cs#L638) or checks if the hostname is an IP address to determine if its a Path Style URI (account name in the path instead of subdomain).

This is why `127.0.0.1` or the port `10000` works. The only workaround at the moment is to use the alternate constructor shared by @navba-MSFT [here](https://github.com/Azure/azure-sdk-for-net/issues/32809#issuecomment-1336809353).
