### ISSUE TITLE
QueryWorkspaceAsync returns 401 [Azure.Monitor.Query]

### ISSUE THREAD

**Issue by GiovanniCafasso** [Azure/azure-sdk-for-net#32807]
### Library name and version
Azure.Monitor.Query 1.1.0

### Query/Question
I'm trying to get data from the workspace using Azure Functions, but ```LogsQueryClient.QueryWorkspaceAsync``` returns status code 401.
I tried giving *'read'* and *'contributor'* permissions to my Functions, but it doesn't work.

To authenticate the client I used ```var client = new LogsQueryClient(new DefaultAzureCredential());```

Any suggestions?

### Environment
Azure

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by GiovanniCafasso** [comment]
Problem solved.
I probably should have waited a few hours after assigning permissions.
