### ISSUE TITLE
Sample code for IndexDocumentAsync 

### ISSUE THREAD

**Issue by kspoojary** [Azure/azure-sdk-for-net#32801]
Is there any sample example how to use this searchindexingbufferedsender.IndexDocumentAsync()? 
What happens if there is any error in one of documents? entire request will be failed or only invalid docs? How to track the error/ failed docs?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 94bb8cc1-97c3-3914-3dcc-27dcdeeecd61
* Version Independent ID: c0980e51-67e4-a170-a06c-ac73c9dee39d
* Content: [SearchIndexingBufferedSender&lt;T&gt;.IndexDocumentsAsync Method (Azure.Search.Documents) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.searchindexingbufferedsender-1.indexdocumentsasync?view=azure-dotnet)
* Content Source: [xml/Azure.Search.Documents/SearchIndexingBufferedSender`1.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Search.Documents/SearchIndexingBufferedSender`1.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Hi @kspoojary, [here](https://github.com/Azure/azure-sdk-for-net/blob/ea21301b056e34188213b92b7f159d7c38d11d12/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs#L910-L922) is an example of using `SearchIndexingBufferedSender.IndexDocumentsAsync` method. For more details on `SearchIndexingBufferedSender`, see the sample code [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/samples/Sample05_IndexingDocuments.md#searchindexingbufferedsender).

>What happens if there is any error in one of documents? entire request will be failed or only invalid docs?

Only the invalid document fails.  Depending on the type of failure, it will automatically be retried in subsequent batches several times.  If we still don't succeed or the original failure wasn't retriable, a failure event is raised that customers can handle. 

>How to track the error/ failed docs?

[Here](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.searchindexingbufferedsender-1?view=azure-dotnet#events) are the list of events that are raised. For the failure, `ActionFailed` event is raised whenever an indexing action failed. [IndexActionFailedEventArgs<T>](https://learn.microsoft.com/en-us/dotnet/api/azure.search.documents.models.indexactionfailedeventargs-1?view=azure-dotnet#properties) shows what you can use with it and and the `Action` contains the original document.

[Here's](https://github.com/Azure/azure-sdk-for-net/blob/ea21301b056e34188213b92b7f159d7c38d11d12/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs#L78-L88) an example of how to add handler and track the failures and [here's](https://github.com/Azure/azure-sdk-for-net/blob/ea21301b056e34188213b92b7f159d7c38d11d12/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs#L867) the usage.
