### ISSUE TITLE
All Arm related objects are missing in nuget install for Azure.ResourceManager

### ISSUE THREAD

**Issue by WayneAASPLLC** [Azure/azure-sdk-for-net#32806]
To reproduce just install nuget package of Azure.ResourceManager and you will see there is no GetArmDeployments when defining a resource group even though you can define Azure.ResourceManager.Resources. Others have noticed this too: https://stackoverflow.com/questions/72160922/armdeploymentcollection-not-in-azure-resourcemanager-resources-namespace this makes using JSON files impossible.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 22d57016-8442-5701-3d4f-b143a33e12e3
* Version Independent ID: 50028143-084f-c0de-4969-75bbfacc026e
* Content: [Azure.ResourceManager.Resources Namespace - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources?view=azure-dotnet)
* Content Source: [xml/ns-Azure.ResourceManager.Resources.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/ns-Azure.ResourceManager.Resources.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by WayneAASPLLC** [comment]
I have found the problem.
It looks like Azure.ResourceManager from nuget comes with Resources but it doesn't work even though you can reference it.
You have to install Azure.ResourceManager.Resources as a different nuget. Weird... why would a namespace that does nothing be in Azure.ResourceManager base nuget?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by WayneAASPLLC** [comment]
Actually, it looks like this is still an issue:
https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template/blob/main/Program.cs
If you look at this example, Template and Parameters does not exist in ArmDeploymentContent even when adding Azure.ResourceManager.Resources specifically.

**Comment by xboxeer** [comment]
@WayneAASPLLC Azure.ResourceManager is the base of all Azure.ResourceManger.XXXX packages,  it actually plays the role of Azure core in our SDK, you can refer to this [document](https://azure.github.io/azure-sdk/general_azurecore.html) to understand why this package is here.
