### ISSUE TITLE
Nuget package installing Microsoft.Azure.Management.Fluent 1.0.0 not working for VS2012

### ISSUE THREAD

**Issue by tkumark** [Azure/azure-sdk-for-net#3280]
Hi

In VS2012 when I run `Install-Package Microsoft.Azure.Management.Fluent` on a newly create 4.5 Console application. I got the following error

> PM> Install-Package Microsoft.Azure.Management.Fluent Attempting to resolve dependency 'Microsoft.Azure.Management.AppService.Fluent (≥ 1.0.0 && < 2.0.0)'. Attempting to resolve dependency 'Microsoft.Rest.ClientRuntime.Azure (≥ 3.3.5 && < 4.0.0)'. Install-Package : 'Microsoft.Rest.ClientRuntime.Azure' already has a dependency defined for 'NETStandard.Library'. At line:1 char:1 + Install-Package Microsoft.Azure.Management.Fluent + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : NotSpecified: (:) [Install-Package], InvalidOperationException + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

I do not face this issue with VS2017

**Comment by hovsepm** [comment]
@tkumark please check if you have updates for VS2012 Nuget manager that are not installed.

**Comment by hovsepm** [comment]
Please update your package reference to v1.1.2. Reopen this bug if it will still happen afterwards.
