### ISSUE TITLE
[QUERY] Is OperationContext to correlate Storage logs and Application Insights telemetry Available in Azure.Storage.Queue v12

### ISSUE THREAD

**Issue by pbiasotti** [Azure/azure-sdk-for-net#32812]
### Library name and version

Azure.Storage.Queues v12.12.0

### Query/Question

I see that the [sample for tracking enqueue operations](https://learn.microsoft.com/en-us/azure/azure-monitor/app/custom-operations-tracking#enqueue) to storage is using the Azure SDK v11 (Microsoft.Azure.Storage.Queue) using `CloudQueue.AddMessage (....)`. In v12 (Azure.Storage.Queues) there is QueueServiceClient.SendMessageAsync(....) but I couldn't find the way to send the correlation Id as this line explains

```
        // Add operation.Telemetry.Id to the OperationContext to correlate Storage logs and Application Insights telemetry.
        OperationContext context = new OperationContext { ClientRequestID = operation.Telemetry.Id };
```

Is there an equivalent using the Azure SDK v12? (Azure.Storage.Queues)?

**Comment by navba-MSFT** [comment]
@pbiasotti Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@pbiasotti Apologies for the late reply. There is a feature in `Azure.Core` that allows you to set the `client request id`.

[https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#setting-x-ms-client-request-id-value-sent-with-requests](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#setting-x-ms-client-request-id-value-sent-with-requests)

Please remember to replace `SecretClient` with `QueueClient`. Hope this helps.
