### ISSUE TITLE
[FEATURE REQ] Auto upgrade emitter version when emitter is published

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#32816]
### Library name

Azure.Core

### Please describe the feature.

Similar to how we update Packages.Data.Props each time we publish a new version of autorest.csharp we should update this file https://github.com/Azure/azure-sdk-for-net/blob/main/eng/csharp-emitter-package.json when we publish a new version of @azure-tools/cadl-csharp npm package.

**Comment by m-nash** [comment]
@archerzz I think this was already done can you confirm / close if that is the case?

**Comment by archerzz** [comment]
@m-nash That's true. Closing.
