### ISSUE TITLE
[BUG]Azure.Identity not working with Powershell module .net framework project running in windows powershell

### ISSUE THREAD

**Issue by lnga2001** [Azure/azure-sdk-for-net#32817]
### Library name and version

Azure.Identity 1.8.0

### Describe the bug

I have a .net framework c# project implementing powershell module.  I'm trying to migrate from Microsoft.Azure.Services.AppAuthenication to Azure.Identity.  Everything works fine with AppAuthenication; however, once Iperformed the migration, we got the following error during runtime

Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

I checked all the references in the solution, and there's no references to version 4.0.4.1.  Also, the bindingRedirect is setup correctly.   Somehow, it's still trying to use 4.0.4.1

<dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>

I also attempt to perform the bindingRedirect manually through powershell script (*.psm1), which also doesn't help

$Unsafe = [reflection.assembly]::LoadFrom((Join-Path $PSScriptRoot System.Runtime.CompilerServices.Unsafe.dll)) 

$OnAssemblyResolve = [System.ResolveEventHandler] {
  param($sender, $e)

  if ($e.Name -eq "System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a") { return $Unsafe }

  foreach($a in [System.AppDomain]::CurrentDomain.GetAssemblies())
  {
    if ($a.FullName -eq $e.Name)
    {
      return $a
    }
  }
  return $null
}

[System.AppDomain]::CurrentDomain.add_AssemblyResolve($OnAssemblyResolve)

### Expected behavior

System.Runtime.CompilerSerivces.Unsafe should use the redirect version (6.0.0.0) during runtime

### Actual behavior

Getting the following message during runtime 

Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### Reproduction Steps

public static async Task<string> AcquireTokenAsync(string resourceId, string tenantId, CancellationToken cancellationToken = default)
        {
            var tokenCredential = new DefaultAzureCredential();
            var tokentRequestContext = new TokenRequestContext(scopes: new string[] { resourceId + "/.default" }, tenantId: tenantId) { };
            var token = await tokenCredential.GetTokenAsync(tokentRequestContext, cancellationToken).ConfigureAwait(false);
            return token.Token;
        }

fail at GetTokenAsync

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
This sounds similar to this issue - does this approach for setting up the binding redirect help in your case? https://github.com/Azure/azure-sdk-for-net/issues/21361#issuecomment-849634754

**Comment by lnga2001** [comment]
@christothes, the solution you refer to doesn't work with ours. However, i implemented something similar to the AssemblyBindingRedirectHelper
`    public class ModuleInitializer : IModuleAssemblyInitializer
    {
        public void OnImport()
        {
            var list = AppDomain.CurrentDomain.GetAssemblies()
       .Select(a => a.GetName())
       .OrderByDescending(a => a.Name)
       .ThenByDescending(a => a.Version)
       .Select(a => a.FullName)
       .ToList();

            AppDomain.CurrentDomain.AssemblyResolve += (sender, args) =>
            {
                var requestedAssembly = new AssemblyName(args.Name);
                foreach (string asmName in list)
                {
                    if (asmName.StartsWith(requestedAssembly.Name + ","))
                    {
                        return Assembly.Load(asmName);
                    }
                }
                return null;
            };
        }
    }`

then i noticed System.Runtime.CompilerServices.Unsafe is not in the assemblies list.  That might be why it's not binding redirect correctly.  I ended up adding the dll directly in the our *.psm1 file along with this ModuleInitializer, then everything works!

`## Set Strict Mode for Module. https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/set-strictmode
Set-StrictMode -Version Latest

try {
    Add-Type -AssemblyName System.Configuration
    Add-Type -Path (Join-Path $PSScriptRoot System.Runtime.CompilerServices.Unsafe.dll)
    Add-Type -Path (Join-Path $PSScriptRoot System.Buffers.dll)
    Add-Type -AssemblyName System.Data -ErrorAction Stop
}
catch {
    $PSCmdlet.ThrowTerminatingError($_)
}`

Thanks for your help!
