### ISSUE TITLE
[FEATURE REQ] Better distinction between async and blocking operations

### ISSUE THREAD

**Issue by MatisseHack** [Azure/azure-sdk-for-net#32833]
### Library name

Azure.ResourceManager.* (although I think others are affected as well)

### Please describe the feature.

I think the Azure management SDKs are very intuitive to use, but I consistently find one aspect rather confusing: the inclusion of both asynchronous and blocking versions of every function. e.g.

```csharp
var s1 = armClient.GetSubscriptions().Get("00000000-0000-0000-0000-000000000000");
var s2 = await armClient.GetSubscriptions().GetAsync("00000000-0000-0000-0000-000000000000");
```

The subtle (but important!) distinction between these methods has tripped up both junior and senior developers on my team. The methods are particularly confusing for developers that are newer to C# or less familiar with asynchronous patterns. The inclusion of blocking methods right alongside async methods makes it too easy to unknowingly introduce performance issues.

It is even more confusing for listing operations because there are four different ways to list many resources. e.g.

```csharp
foreach(var sub in armClient.GetSubscriptions().GetAll()) {}
await foreach(var sub in armClient.GetSubscriptions().GetAllAsync()) {}

foreach(var sub in armClient.GetSubscriptions()) {}
await foreach(var sub in armClient.GetSubscriptions()) {}
```

Making the `SubscriptionCollection` implement `IEnumerable` and `IAsyncEnumerable` is kinda cool, but adds to the confusion and makes it even easier to mess up. Having  `GetAll`, `GetAllAsync`, and other methods defined on this collection doesn’t help.

I realize that providing both asynchronous and synchronous method implementations is part of the [Azure SDK design guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#sync-and-async). Changing the SDK’s API surface would also be a prohibitively large breaking change. However, in an ideal world, I think the best solution would be to separate the asynchronous and synchronous APIs into a separate NuGet packages.

Since such a large change is impractical at this point, I wonder if a more reasonable improvement would be to add an analyzer that suggests converting synchronous calls into asynchronous calls. Such an analyzer could be disabled entirely by teams that can’t use asynchronous APIs whereas I could set it to throw a compilation error, thereby protecting my codebase from performance issues that too easily slip through code reviews.

**Comment by jsquire** [comment]
//cc: @m-nash, @KrzysztofCwalina, @tg-msft for pattern/analyzer discussions.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@MatisseHack async and await is a common pattern in .NET world, the analyzer you are suggesting is something that should built inside VS and developers can turn on and turn off by some config in VS. it is out of SDK's scope
