### ISSUE TITLE
[FormRecognizer] TrainingOps(True,False) failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32835]
FormRecognizer nightly test runs are failing with:

> Error message
> System.AggregateException : One or more errors occurred. (An error occurred trying to get models. Retry the operation or contact service administrator if the issue persists.
> Status: 500 (Internal Server Error)
> ErrorCode: 1999
> 
> Content:
> {"error":{"code":"1999","message":"An error occurred trying to get models. Retry the operation or contact service administrator if the issue persists."}}
> 
> Headers:
> x-envoy-upstream-service-time: 193
> apim-request-id: 01eb3cc1-aea5-4ba3-9258-6954ebf28d31
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> x-ms-region: REDACTED
> Date: Thu, 01 Dec 2022 05:20:08 GMT
> Content-Length: 153
> Content-Type: application/json; charset=utf-8
> )
> ----> Azure.RequestFailedException : An error occurred trying to get models. Retry the operation or contact service administrator if the issue persists.
> Status: 500 (Internal Server Error)
> ErrorCode: 1999
> 
> Content:
> {"error":{"code":"1999","message":"An error occurred trying to get models. Retry the operation or contact service administrator if the issue persists."}}
> 
> Headers:
> x-envoy-upstream-service-time: 193
> apim-request-id: 01eb3cc1-aea5-4ba3-9258-6954ebf28d31
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> x-ms-region: REDACTED
> Date: Thu, 01 Dec 2022 05:20:08 GMT
> Content-Length: 153
> Content-Type: application/json; charset=utf-8
> 
> 
> Stack trace
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at System.Threading.Tasks.Task`1.get_Result()
>    at Azure.AI.FormRecognizer.Tests.FormTrainingClientLiveTests.TrainingOps(Boolean labeled, Boolean useTokenCredential) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormTrainingClient/FormTrainingClientLiveTests.cs:line 371
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> --RequestFailedException
>    at Azure.AI.FormRecognizer.FormRecognizerRestClient.ListCustomModels(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/FormRecognizerRestClient.cs:line 1810
>    at Azure.AI.FormRecognizer.Training.FormTrainingClient.<>c__DisplayClass18_0.<GetCustomModels>g__FirstPageFunc|0(Nullable`1 pageSizeHint) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormTrainingClient/FormTrainingClient.cs:line 521
>    at Azure.Core.PageableHelpers.<>c__DisplayClass5_0`1.<CreateEnumerable>b__0(String continuationToken, Nullable`1 pageSizeHint) in /_/microsoft.azure.autorest.csharp/3.0.0-beta.20221123.2/content/Generator.Shared/PageableHelpers.cs:line 45
>    at Azure.Core.PageableHelpers.FuncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() in /_/microsoft.azure.autorest.csharp/3.0.0-beta.20221123.2/content/Generator.Shared/PageableHelpers.cs:line 220
>    at Azure.Core.TestFramework.UseSyncMethodsInterceptor.SyncPageableWrapper`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/UseSyncMethodsInterceptor.cs:line 263
>    at Azure.Core.TestFramework.UseSyncMethodsInterceptor.SyncPageableWrapper`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.<>c__DisplayClass6_0.<<AsPages>b__0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 304
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 201
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 302
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 302
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.DiagnosticScopeValidatingAsyncEnumerable`1.AsPages(Stri

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2023938&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Seems to be transient. Will wait a few more days before closing this.

**Comment by kinelski** [comment]
Not seeing this error anymore. Closing the issue.
