### ISSUE TITLE
[ContainerRegistry] CanGetTagsOrdered(False) failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32837]
ContainerRegistry nightly test runs are failing with:

> Error message
> Expected: True
> But was:  False
> 
> 
> Stack trace
>    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.CanGetTagsOrdered(Boolean anonymous) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/RegistryArtifactLiveTests.cs:line 279
>    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.CanGetTagsOrdered(Boolean anonymous) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/RegistryArtifactLiveTests.cs:line 277
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 
> 1)    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.CanGetTagsOrdered(Boolean anonymous) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/RegistryArtifactLiveTests.cs:line 279

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2022809&view=results

@jsquire for notification.

**Comment by pallavit** [comment]
Opportunistically closing these for a blanket issue - #32948 to fix the race conditions we have.
