### ISSUE TITLE
[TextAnalytics] AnalyzeOperationExtractSummaryWithAutoDetectedLanguageTest failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32838]
TextAnalytics nightly test runs are failing with:

> Error message
> System.InvalidOperationException : The requested operation requires an element of type 'Object', but the target element has type 'String'.
> 
> 
> Stack trace
>    at System.Text.Json.JsonElement.EnumerateObject()
>    at Azure.AI.TextAnalytics.Models.DetectedLanguageInternal.DeserializeDetectedLanguageInternal(JsonElement element) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Generated\Models\DetectedLanguageInternal.Serialization.cs:line 53
>    at Azure.AI.TextAnalytics.Models.ExtractedSummaryDocumentResultWithDetectedLanguage.DeserializeExtractedSummaryDocumentResultWithDetectedLanguage(JsonElement element) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Generated\Models\ExtractedSummaryDocumentResultWithDetectedLanguage.Serialization.cs:line 65
>    at Azure.AI.TextAnalytics.Models.ExtractiveSummarizationResult.DeserializeExtractiveSummarizationResult(JsonElement element) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Generated\Models\ExtractiveSummarizationResult.Serialization.cs:line 57
>    at Azure.AI.TextAnalytics.Models.ExtractiveSummarizationLROResult.DeserializeExtractiveSummarizationLROResult(JsonElement element) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Generated\Models\ExtractiveSummarizationLROResult.Serialization.cs:line 47
>    at Azure.AI.TextAnalytics.Models.AnalyzeTextLROResult.DeserializeAnalyzeTextLROResult(JsonElement element) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Generated\Models\AnalyzeTextLROResult.Serialization.cs:line 46
>    at Azure.AI.TextAnalytics.Models.AnalyzeTasks.DeserializeAnalyzeTasks(JsonElement element) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Generated\Models\AnalyzeTasks.Serialization.cs:line 55
>    at Azure.AI.TextAnalytics.Models.AnalyzeTextJobState.DeserializeAnalyzeTextJobState(JsonElement element) in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Generated\Models\AnalyzeTextJobState.Serialization.cs:line 34
>    at Azure.AI.TextAnalytics.MicrosoftCognitiveLanguageServiceTextAnalysisRestClient.<AnalyzeBatchJobStatusAsync>d__14.MoveNext() in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\Generated\MicrosoftCognitiveLanguageServiceTextAnalysisRestClient.cs:line 235
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.AI.TextAnalytics.ServiceClients.LanguageServiceClient.<AnalyzeStatusAsync>d__83.MoveNext() in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\ServiceClients\LanguageServiceClient.cs:line 1659
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.<Azure-Core-IOperation<Azure-AsyncPageable<Azure-AI-TextAnalytics-AnalyzeActionsResult>>-UpdateStateAsync>d__55.MoveNext() in D:\a\_work\1\s\sdk\textanalytics\Azure.AI.TextAnalytics\src\AnalyzeActionsOperation.cs:line 287
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 278
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugger

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2020906&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment]
This has already been fixed in the following PR: https://github.com/Azure/azure-sdk-for-net/pull/32768
