### ISSUE TITLE
[BUG] Function [XYZ]: cannot find value named 'ServiceBusConnection' in local.settings.json that matches 'connection' property set on 'serviceBusTrigger'

### ISSUE THREAD

**Issue by petrkoutnycz** [Azure/azure-sdk-for-net#32840]
### Library name and version

microsoft.azure.webjobs.extensions.servicebus 5.8.1

### Describe the bug

I was trying to enable Managed Identity together with `ServiceBusTrigger` in my Azure Function according to the official guide here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2. 

### Expected behavior

There is no MSBuild warning regarding missing setting in `local.settings.json` when using Managed Identity for Azure Functions.

### Actual behavior

There is a warning `Function [XYZ]: cannot find value named 'ServiceBusConnection' in local.settings.json that matches 'connection' property set on 'serviceBusTrigger' `. This warning is misleading since according to the guide, there should not even be a setting like that since there is a `ServiceBusConnection__fullyQualifiedNamespace` present.

### Reproduction Steps

Prepare an Azure Function based on the official page here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2.

### Environment

- macOS Ventura 13.0.1
- .NET SDK 6.0.403
- IDE: both Rider and Visual Studio

**Comment by michaeldwood** [comment]
This is also true for any function trigger that supports the "__fullyQualifiedNamespace" connection property (hack).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
I believe the issue here is related to the version of the Core Tools being used. Can you try using the [latest](https://learn.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=v4%2Cwindows%2Ccsharp%2Cportal%2Cbash#install-the-azure-functions-core-tools)?

**Comment by petrkoutnycz** [comment]
@JoshLove-msft will give it a shot, thanks

**Comment by kristinannabel** [comment]
/unresolve

I also get this isse. Instaling latest Core Tools locally did nothing for me.
I also get this warning on the build agent.

`public async Task DoSomething([ServiceBusTrigger("%QueueName%", Connection = "ServiceBusConnection")] ServiceBusReceivedMessage message, CancellationToken cancellationToken)`

In local.settings.json:
`      "Values": {
    "ServiceBusConnection:ConnectionStringWithoutSecret": "Endpoint=etc...",
    "ServiceBusConnection:fullyQualifiedNamespace": "namespace.servicebus.windows.net",
    "ServiceBusConnection:HostAddress": "sb://servicebus.servicebus.windows.net",
}`
