### ISSUE TITLE
[FEATURE REQ] Provide a way to extract verbose PII logs from MSAL 

### ISSUE THREAD

**Issue by bgavrilMS** [Azure/azure-sdk-for-net#32848]
### Library name

Azure Identity

### Please describe the feature.

Azure Identity should provide a mechanism to extract verbose logs with PII from MSAL. 

# Verbosity

Azure SDK has mostly the same verbosity levels as MSAL (verbose, info, warning, error). The same level of log verbosity should be set on both Azure SDK and MSAL, to allow MSAL developers to inspect logs in case of problems.

# PII

There should be a way to enable MSAL PII logs. Ideally the PII flag in Azure SDK should be set in MSAL as well, and any differences in classification should be discussed (but not on GitHub, as the actual classification if confidential). 

Note: this is consistency item across all other Azure Identity SDKs.

CC: @KarishmaGhiya who helped with verbosity on MSAL Js and @schaabs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
resolved in https://github.com/Azure/azure-sdk-for-net/pull/37463
