### ISSUE TITLE
Questiong about how to upload Video File in Azure Media Services, using MediaAssetData

### ISSUE THREAD

**Issue by Gabrycloud** [Azure/azure-sdk-for-net#32842]
### Library name and version

Azure.Resourcemanager.Media 1.0.0

### Query/Question

Hi, I'd like to know how could I create an asset with a video file, through code, to Azure Media Services, using Azure.Resourcemanager.Media
I have found no documentation about it and I don't like deprecated libraries like Microsoft.WindowsAzure.MediaServices.Client

### Environment

.NET Framework 4.8
Visual Studio 2019

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@johndeu and @giakas can you help on this question

**Comment by johndeu** [comment]
The AMS team is still working on migrating our code samples to the newer .NET Track 2 SDK. 
You can see all of our .NET samples up here - https://github.com/Azure-Samples/media-services-v3-dotnet/tree/track2 but not all of them are fully migrated over to track2 yet.  

If you can use the 6.0 version of the SDK, (which is still supported),  you can use the samples in the main branch 
https://github.com/Azure-Samples/media-services-v3-dotnet/tree/main

Start with the simple encoding samples - https://github.com/Azure-Samples/media-services-v3-dotnet/tree/main/VideoEncoding/Encoding_H264

**Comment by johndeu** [comment]
@FYI @giakas @jonpayne  - we have to get these track 2 samples migrated soon...

**Comment by Gabrycloud** [comment]
Hi, thank you for your answer, but unfortunately my boss doesn't want me to use Microsoft.Azure.Management.Media . Isn't there a way to reach the goal through Azure.Resourcemanager.Media 1.0.0 ?

**Comment by jonpayne** [comment]
Hi @Gabrycloud,

We are still working on the samples for the `Azure.ResourceManager.Media` SDK. In the meantime, here is some sample code showing how to upload a local file to a Media Services Asset:

```csharp
using Azure;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Media;
using Azure.ResourceManager.Media.Models;
using Azure.Storage.Blobs;

var videoPath = @"C:\Media\bbb_sunflower_1080p_30fps_normal.mp4";   // set this to the path to your video

var armClient = new ArmClient(new DefaultAzureCredential());

var mediaServicesAccountIdentifier = MediaServicesAccountResource.CreateResourceIdentifier(
    subscriptionId: "00000000-0000-0000-0000-000000000000",         // update this to your subscription ID
    resourceGroupName: "myresources",                               // update the resource group
    accountName: "mymedia");                                        // update the account name

MediaServicesAccountResource mediaServices =
    await armClient.GetMediaServicesAccountResource(mediaServicesAccountIdentifier).GetAsync();

// Create an asset
var asset = (await mediaServices.GetMediaAssets().CreateOrUpdateAsync(
    WaitUntil.Completed,
    $"my-asset",
    new MediaAssetData())).Value;

// Get a URL for uploading content to the asset
var assetSas = await asset.GetStorageContainerUrisAsync(
    new MediaAssetStorageContainerSasContent
    {
        ExpireOn = DateTime.UtcNow.AddHours(1),
        Permissions = MediaAssetContainerPermission.ReadWriteDelete
    }).FirstOrDefaultAsync();

// Upload a file to the asset
var inputAssetContainer = new BlobContainerClient(assetSas);
var inputAssetBlob = inputAssetContainer.GetBlobClient("input.mp4");
await inputAssetBlob.UploadAsync(videoPath);
```
