### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by frblondin** [Azure/azure-sdk-for-net#32844]
The _Explorer the client APIs_ link is broken.

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour learn.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 2ba68873-71aa-9f3a-f558-5b1a81296560
* Version Independent ID: fe6ec9de-d30e-f8f5-d86e-49af8f7e8fc1
* Content: [Azure Cosmos DB libraries for .NET - Azure for .NET Developers](https://learn.microsoft.com/fr-fr/dotnet/api/overview/azure/cosmosdb?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/cosmosdb.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/cosmosdb.md)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@frblondin Thanks for catching that! We have worked up a PR to fix it. [Here](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/cosmosdb/documentdb?view=azure-dotnet) is the link for the Client APIs for reference.
