### ISSUE TITLE
What exceptions does this method throw?

### ISSUE THREAD

**Issue by jkindwall** [Azure/azure-sdk-for-net#32852]
I'm trying to update some code that tries authenticating with a primary secret, then if it catches an exception with a 401 status code it retries with a secondary secret.  However It's really frustrating that this documentation does not say what exception types could be thrown by the ExecuteAsync() method, so I can't easily check for a 401 response.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f1ae4360-83b4-7a26-9084-4adbb38be682
* Version Independent ID: 3424525b-7769-d7ec-cb65-8ce8d87a6367
* Content: [AbstractAcquireTokenParameterBuilder&lt;T&gt;.ExecuteAsync Method (Microsoft.Identity.Client) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.abstractacquiretokenparameterbuilder-1.executeasync?view=azure-dotnet#microsoft-identity-client-abstractacquiretokenparameterbuilder-1-executeasync)
* Content Source: [xml/Microsoft.Identity.Client/AbstractAcquireTokenParameterBuilder`1.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Identity.Client/AbstractAcquireTokenParameterBuilder`1.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Identity.Client` package is maintained as [#3847](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3847).
