### ISSUE TITLE
[FEATURE REQ] Improve Path Style URI Inference

### ISSUE THREAD

**Issue by PramodValavala-MSFT** [Azure/azure-sdk-for-net#32884]
### Library name

Azure.Storage.Common

### Please describe the feature.

The Storage SDK determines if Path Style URIs should be built when initializing the client with a connection string. This is based on the checks done [here](https://github.com/Azure/azure-sdk-for-net/blob/757543613a8393726436bc149603b19f0da04dac/sdk/storage/Azure.Storage.Common/src/Shared/UriExtensions.cs#L114), which are

- If host is an IP Address
- If port specified is one present in [this list](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Common/src/Shared/Constants.cs#L638)

There are certain scenarios where this fails and requires [using an alternate constructor](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.-ctor?view=azure-dotnet#azure-storage-blobs-blobclient-ctor(system-uri-azure-azuresascredential-azure-storage-blobs-blobclientoptions)) which doesn't take a connection string. A few cases where this has come up is

- Azure Blob Storage on IoT Edge
   - #27126 
   - #32464
- Azurite running on custom port
   - #32809

**Comment by mattiasnordqvist** [comment]
This makes it impossible to use azurite in a testcontainer, in case you need to use 'host.docker.internal' as  TESTCONTAINERS_HOST_OVERRIDE
