### ISSUE TITLE
Azure file SDK - Put Range method cannot be modified to add content-type header 

### ISSUE THREAD

**Issue by mahmoudsamy27** [Azure/azure-sdk-for-net#32909]
### Package Name:

Azure.Storage.Files.Shares,  version 12.12.17

### Details:

When putting Azure File endpoint behind Azure App gateway WAF, the requests must have content-type as multipart/form-data to be identified as a legit upload. 

Looking at https://learn.microsoft.com/en-us/rest/api/storageservices/put-range, there is no support for modifying the content-type header as it will always be octet-stream. 

I understand that content-type can be modified while creating the file but AppGW needs the subsequent Put Range API call to have content-type as multipart as wel..

**Comment by jsquire** [comment]
Hi @mahmoudsamy27.  Thank you for reaching out and we regret that you're experiencing difficulties.   Would you please share the Azure SDK package that you're using and its version?

**Comment by mahmoudsamy27** [comment]
This is the SDK version https://www.nuget.org/packages/Azure.Storage.Files.Shares/12.12.1?_src=template - .NET SDK.

**Comment by navba-MSFT** [comment]
@mahmoudsamy27 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@mahmoudsamy27 If the `content-type` isn't specified at the time of creating the file, it will default to `application/octet-stream`. When you call Create File, you only initialize the file. To add content to a file, you call the Put Range operation. 

Content-Type or x-ms-content-type | Optional. The MIME content type of the file. The default type is application/octet-stream.
-- | --

I tried to do a repro using Azure Portal and Storage explorer and they all behave as per the design. Content-type appears only during create and not for Put range operation. 

If you would still like to change the content-type of the file after uploading it to the storage account, you could go to tyhe properties and change it type as shown below:

![image](https://user-images.githubusercontent.com/57353862/207296358-90845ddf-e05e-49ee-b0ff-35893a5ff1ba.png)


Note: I am using[ storage explorer ](https://azure.microsoft.com/en-us/products/storage/storage-explorer/)here to edit the file properties.
