### ISSUE TITLE
[BUG] Docs should clarify that AccessTier for V1 storage accounts is null

### ISSUE THREAD

**Issue by Archomeda** [Azure/azure-sdk-for-net#32910]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Describe the bug

Blobs that are stored in V1 storage accounts don't have an access tier. This is all fine and well, until you forget about this and try to get the blob properties to get the access tier, don't expect a null value and try to convert it to an AccessTier type via the implicit string operator.

### Expected behavior

Either make the BlobProperties.AccessTier property nullable, or at least clarify in the documentation that the value can be null for V1 storage accounts.

The first option is the best because nullables exist for a reason, and will allow for code analysis to pick this up.
The second option is good enough if the first one is not feasible, because then it's at least clarified in the documentation.

### Actual behavior

The BlobProperties.AccessTier property is not marked as nullable, nor is it clarified that the value can be null.

Documentation currently states:
> The tier of page blob on a premium storage account or tier of block blob on blob storage LRS accounts. For a list of allowed premium page blob tiers, see [https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage#features](https://learn.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage#features). For blob storage LRS accounts, valid values are Hot/Cool/Archive.

### Reproduction Steps

Have a V1 storage account, and run the following snippet with the BlobClient referencing a blob in that storage account.

```cs
using Azure.Storage.Blobs;

var blob = new BlobClient(...);
var properties = await blob.GetPropertiesAsync();

Console.WriteLine(properties.Value.AccessTier); // is null

AccessTier accessTier = properties.Value.AccessTier; // ArgumentNullException
```

**Comment by navba-MSFT** [comment]
@Archomeda Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
