### ISSUE TITLE
[BUG] BlobErrorCode type doesn't contain BlobAccessTierNotSupportedForAccountType

### ISSUE THREAD

**Issue by Archomeda** [Azure/azure-sdk-for-net#32914]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Describe the bug

Azure.Storage.Blobs.Models.BlobErrorCode doesn't contain the BlobAccessTierNotSupportedForAccountType error code that occurs when setting an AccessTier when writing a new blob to a V1 storage account.

### Expected behavior

Azure.Storage.Blobs.Models.BlobErrorCode contains BlobAccessTierNotSupportedForAccountType 

### Actual behavior

Azure.Storage.Blobs.Models.BlobErrorCode doesn't contain BlobAccessTierNotSupportedForAccountType 

### Reproduction Steps

Run the following code with a custom file path and source data (or stream) and observe that the request fails with a RequestFailedException and the error code BlobAccessTierNotSupportedForAccountType.

```cs
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;

var uploadOptions = new BlobUploadOptions
{
    AccessTier = AccessTier.Hot
};
var blob = new BlobClient(...);
await blob.UploadAsync(..., options: uploadOptions);
```

**Comment by navba-MSFT** [comment]
@Archomeda Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@Archomeda I am able to run the below sample code successfully and it worked just fine. Could you please let us know the Storage Account kind ? This is present in the Azure Storage portal blade within the configuration section as shown below:

![image](https://user-images.githubusercontent.com/57353862/206126527-454eff2c-e265-4c46-b5fa-99238298bd1e.png)

The Access Tiers are supported for general-purpose v2 or Blob Storage account types. Please check the type of your storage account.

**Sample Code:**
```
            string connectionString = "Storage Account - Connection String";

            // Create a BlobServiceClient object which will be used to create a container client
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);

            //Create a unique name for the container
            string containerName = "MyContainerName" + Guid.NewGuid().ToString();

            // Create the container and return a container client object
            BlobContainerClient containerClient = await blobServiceClient.CreateBlobContainerAsync(containerName);


            // Create a local file in the ./data/ directory for uploading and downloading
            string localPath = "./data/";
            string fileName = "MyBlob.txt";
            string localFilePath = Path.Combine(localPath, fileName);

            // Write text to the file
            await File.WriteAllTextAsync(localFilePath, "HelloWorld");

            // Get a reference to a blob
            BlobClient blobClient = containerClient.GetBlobClient(fileName);

            var uploadOptions = new BlobUploadOptions
            {
                AccessTier = AccessTier.Hot
            };

            await blobClient.UploadAsync(localFilePath, options: uploadOptions);

```

**Comment by Archomeda** [comment]
@navba-MSFT The sample is just about reproducing that ErrorCode when writing to V1 storage accounts, as I've mentioned in the bug description. That V1 storage accounts do not support AccessTiers, is understandable, but the BlobErrorCode type should at least contain that error code definition as well.

**Comment by navba-MSFT** [comment]
@Archomeda Thanks for clarifying this. We will update our documentation to include this information.

**Comment by navba-MSFT** [comment]
@Archomeda PR to update the docs is now merged https://github.com/Azure/azure-sdk-for-net/pull/32968. See the other thread https://github.com/Azure/azure-sdk-for-net/issues/32910

**Comment by Archomeda** [comment]
@navba-MSFT This is a different issue. This is about the BlobErrorCode class missing the BlobAccessTIerNotSupportedForAccountType string, and not about the documentation not clarifying that the AccessTier can be null.

**Comment by navba-MSFT** [comment]
Thanks for clarifying. I am adding service team to look into this.

**Comment by navba-MSFT** [comment]
@xgithubtriage Could you please look into this request ?

**Comment by seanmcc-msft** [comment]
This is a simple fix, we should take this.
