### ISSUE TITLE
Function could not load type Azure.NullableResponse1

### ISSUE THREAD

**Issue by denniselit** [Azure/azure-sdk-for-net#32936]
### Library name and version

Azure.Storage.Blobs 12.4.1

### Query/Question

Hi,

I get this error:
"Could not load type 'Azure.NullableResponse`1' from assembly 'Azure.Core, Version=1.25.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'.":"Azure.NullableResponse`1"

From this method (data is a valid xml where mime is application/xml):
```
public async Task<Response<BlobContentInfo>> UploadTextAsync(BlobClient blobReference, string data, string mime)
        {
            MemoryStream stream = new MemoryStream(Encoding.UTF8.GetBytes(data));

            return await blobReference.UploadAsync(stream, new BlobHttpHeaders { ContentType = mime });
        }
```

Let me know if you need anything else!

### Environment

Additional info: Azure Function HttpTrigger version 4 running on .NET 6 
IDE: Visual Studio 17.4.2

**Comment by SaurabhSharma-MSFT** [comment]
@denniselit Good to hear that you are unblocked. We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
