### ISSUE TITLE
wordcount sample with map reduce locally

### ISSUE THREAD

**Issue by msngithub** [Azure/azure-sdk-for-net#3293]
Hello guys,
i've installed Microsoft HDInsight Emulator For Windows Azure
i want test a simple project with map reduce technique like wordcount or sqrt in HDInsight Emulator
i program with c#
thanks guys.

**Comment by shahabhijeet** [comment]
@msngithub will this help to get you started
https://docs.microsoft.com/en-us/azure/hdinsight/

**Comment by msngithub** [comment]
i want a simple project with this dll ( https://github.com/Azure/azure-sdk-for-net ) and with HDInsight Emulator
i found a video that show , how to implement a simple project , but this video is not related to last Emulator and dll
https://www.youtube.com/watch?v=uyi41nrhlhw

can any body help me ?
i want a simple project with hdinsight in last HDInsight Emulator with this dll
thank you

**Comment by msngithub** [comment]
if you have a simple map reduce project with this dll and last emulator version , please put your project and source code , or if you have a learning video please put your video link here 
thank you

**Comment by idear1203** [comment]
It is not a SDK related issue
