### ISSUE TITLE
URL to RFC section should be "4-1-6" instead of "4.1.6"

### ISSUE THREAD

**Issue by pianofu** [Azure/azure-sdk-for-net#32946]
The link below should use "-" between section names, instead of "." The current link (first link) with dots doesn't work. But searching for the section 4.1.6, and clicking on that takes you to the link with the "-" (second link below).
1) https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.6
should be
2) https://datatracker.ietf.org/doc/html/rfc7515#section-4-1-6

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f483b27b-f25a-8f55-8c13-7137815892bd
* Version Independent ID: f969f69d-ce86-f57b-194f-a649f37c132d
* Content: [JwtHeaderParameterNames.X5c Field (System.IdentityModel.Tokens.Jwt) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtheaderparameternames.x5c?view=azure-dotnet)
* Content Source: [xml/System.IdentityModel.Tokens.Jwt/JwtHeaderParameterNames.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/System.IdentityModel.Tokens.Jwt/JwtHeaderParameterNames.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `System.IdentityModel.Tokens.Jwt` package is maintained as [#1979](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1979).
