### ISSUE TITLE
Get the Container Registry test pipelines green.

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#32948]
This is a follow-up issue to get the ACR test pipelines green.

**Comment by annelo-msft** [comment]
Since some of the failures are non-deterministic, tracking successful runs to evaluate success of interventions:

- 12/16: Green - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2061934&view=results

**Comment by annelo-msft** [comment]
Use this approach: https://github.com/Azure/azure-sdk-for-net/pull/33829#discussion_r1094748921
