### ISSUE TITLE
[QUERY] Azure Function V4 Upgrade

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#32944]
### Library name and version

Azure Function

### Query/Question

I am migrating Azure Function from .net core 3.1 to .net 6 and V4. My function is a durable function triggered by Cosmos Trigger. While running it in local, I am getting following error:

The function is in error: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.

Can someone guide me on how to resolve this?

**Comment by jsquire** [comment]
This issue has been transferred to the Azure Functions repository as [#2311](https://github.com/Azure/Azure-Functions/issues/2311).
