### ISSUE TITLE
Explore the Management APIs Link is not working 

### ISSUE THREAD

**Issue by ketan-chawda-msft** [Azure/azure-sdk-for-net#32967]
Explore the Management APIs button Link throwing 404

![image](https://user-images.githubusercontent.com/59500871/206390890-19c6b4a5-bb55-451b-a2fa-4be3772f6802.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 553fc3f5-7bb0-db05-00e8-e18c550c2869
* Version Independent ID: 219ec4a2-b185-2c5b-0174-c8577f3f894e
* Content: [Azure Resource Manager SDK for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resource-manager?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/resource-manager.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/resource-manager.md)
* Service: **resourcemanager**
* GitHub Login: @pallavit
* Microsoft Alias: **pallavit**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
This is the old fluent .Net Sdk is being deprecated, we need to take down this doc @xboxeer

**Comment by xboxeer** [comment]
@scottaddie @sima-zhu this is an ask that we shall replace all track 1 SDK samples in .NET SDK reference book, do we have a plan on that?

**Comment by sima-zhu** [comment]
@ArthurMa1978 @xboxeer I am not aware of any work for this. Can we have a meeting for details?

For track 1 which are deprecated, we are currently proposing to add `(deprecated)` besides of display name. 
![Screenshot 2022-12-16 112735](https://user-images.githubusercontent.com/48036328/208174807-b53fad78-1b03-4b02-80e5-5224018c8606.jpg)
