### ISSUE TITLE
ISqlServers has no firewall option to allow access to Azure services

### ISSUE THREAD

**Issue by mloeffen** [Azure/azure-sdk-for-net#3296]
The fluent api seems to have no option to allow Azure services to access the server. Sample code:
```cs
ISqlServer sqlServer = await azure.SqlServers
    .Define(this.sqlServerName)
    .WithRegion(Region.EuropeWest)
    .WithExistingResourceGroup(this.resourceGroupName)
    .WithAdministratorLogin(AdministratorLogin)
    .WithAdministratorPassword(administratorPassword)
    .WithNewFirewallRule(this.firewallRuleIpAddress)
    .WithFirewallAllowAccessToAzureServices(true) // <-- missing something like this
    .CreateAsync(token);
```

![2017-05-30 11_34_39-firewall settings - microsoft azure](https://cloud.githubusercontent.com/assets/986351/26577361/73a79ad6-452c-11e7-969a-211ecd98477d.png)

**Comment by DimitriBerman** [comment]
Any news about this ?

**Comment by milismsft** [comment]
@jaredmoo I did a quick check and this particular setting is not captured in the version 2014-04-01 version of the Swagger specs (see firewallRules.json). Any ideas where I might find it?

**Comment by jaredmoo** [comment]
See documentation at https://docs.microsoft.com/en-us/rest/api/sql/FirewallRules/CreateOrUpdate#firewallrules_createorupdate_request_body :)

**Comment by milismsft** [comment]
I see now, you have to pass in the "magic" ip address "0.0.0.0" to get the Azure Portal setting ;-)

@DimitriBerman, can you please try adding another Firewall Rule in your ISqlServer create sequence with the IP set to "0.0.0.0" and see if that resolves your issue?

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#12
