### ISSUE TITLE
Update remarks for StorageExtensions.CreateServiceTimeoutScope(Nullable<TimeSpan>) method to clarify SDK vs service behavior

### ISSUE THREAD

**Issue by schoag-msft** [Azure/azure-sdk-for-net#32973]
The current statement in the remarks:

"Consider passing a [CancellationToken](https://learn.microsoft.com/en-us/dotnet/api/system.threading.cancellationtoken) to client methods and properly sizing [NetworkTimeout](https://learn.microsoft.com/en-us/dotnet/api/azure.core.retryoptions.networktimeout?view=azure-dotnet#azure-core-retryoptions-networktimeout) when configuring storage clients as prefered way of enforcing upper boundary of execution time."

should be updated as it is referring to the operation time of the application method end to end, since the server timeout does not account for network travel time. We should clarify when this method should be used vs a servertimeout.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e47a75c3-baae-1e5e-fd7c-10399f51f45b
* Version Independent ID: ebc023a8-d605-2917-c049-e70b5660dbb4
* Content: [StorageExtensions.CreateServiceTimeoutScope(Nullable&lt;TimeSpan&gt;) Method (Azure.Storage) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.storageextensions.createservicetimeoutscope?view=azure-dotnet#remarks)
* Content Source: [xml/Azure.Storage/StorageExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage/StorageExtensions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
//cc: @amnguye, @seanmcc-msft
