### ISSUE TITLE
[FEATURE REQ] Supports "expandChildren": true in Azure ML SDK

### ISSUE THREAD

**Issue by zmvictor** [Azure/azure-sdk-for-net#32998]
### Library name

Azure.ResourceManager.MachineLearning

### Please describe the feature.

- Request
Provide parameter `bool? expandChildren ` in 
-- `Azure.ResourceManager.MachineLearning.MachineLearningExtensions.GetMachineLearningUsages()`
-- `Azure.ResourceManager.MachineLearning.MachineLearningExtensions.GetMachineLearningQuotas()`
to return workspace/deployment quota usage. Current SDK only returns to parent level: region. 

- Why
-- This parameter is supported in REST API service
-- Similar parameter is supported by other SDK like `Azure.ResourceManager.Sql`: https://github.com/Azure/azure-sdk-for-net/search?q=expandChildren
-- Python AML SDK already supports it by having kways `params={'expandChildren': 'true'}` in `AzureMachineLearningWorkspaces.usages.list()`
-- Our service needs to identity sub->region->workspace quota usage before starting the deployments

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Need service team to add this feature
