### ISSUE TITLE
[BUG] Duplicate Request when calling UpdateEntityAsync()

### ISSUE THREAD

**Issue by isaacrlevin** [Azure/azure-sdk-for-net#32995]
### Library name and version

Azure.Data.Tables 12.5.0

### Describe the bug

Getting the below exception calling `UpdateEntityAsync()` from an Azure Function that has a input Azure Storage Table binding

> System.Private.CoreLib: Exception while executing function: ShortenUrl. Microsoft.Azure.WebJobs.Host: Error while handling parameter keyTable after function returned:. Azure.Data.Tables: The update condition specified in the request was not satisfied.

I believe the issue is related to the input binding being fired when the table is being updated. This issue does not happen in older versions of this app. I am trying to update to the latest v4 Azure Functions with .NET 6.

**Environment that does not have issue**
.NET Core 3.1
Azure Functions v3
```xml
	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.0.0" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.5" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.6" />
		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.1" />
	</ItemGroup>
```

**Environment that has issue**
.NET 6
Azure Functions v4
```xml
	<ItemGroup>
		<PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="4.0.0" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.1" />
		<PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Tables" Version="1.0.0" />
		<PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.3" />
	</ItemGroup>
````

### Expected behavior

For record to update without issue and not throw an exception

### Actual behavior

`UpdateEntityAsync()` method in TableClient.cs is called twice, the 2nd not having an ETag of *, instead it is an invalid ETag, causing an `UpdateConditionNotSatisfied` to be thrown. Wrapping a try {} catch{} around the call does not resolve the issue. 

### Reproduction Steps

- Clone this repo 

```bash
git clone https://github.com/isaacrlevin/AzureTableFunctionIssue.git
```

- Point at existing Azure Storage account
- Run App locally in Visual Studio
- Submit POST to endpoint

POST http://localhost:7289/api/ShortenUrl
```json
{
  "shortCode":"","input":"https://microsoft.com"
}

````
See that `UpdateConditionNotSatisfied` exception is thrown

### Environment

Windows 11
Latest Visual Studio Preview
Azure Functions Project
.NET 6 and 7 installed

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
I took a look at this and it appears that the input binding for the table is performing an implicit `UpdateEntity` after the execution of the function which uses the ETag value of the incoming entity. This explains the error we are seeing.

I'll investigate further as to why this is occurring in the extension.

**Comment by christothes** [comment]
Looks like this is expected behavior of the new extension as the distinct input and output bindings were collapsed into the single binding. Output is implied if the entity being bound to is modified in the function. Here are some details https://devblogs.microsoft.com/azure-sdk/whats-new-in-the-azure-functions-tables-extension-for-net-beta/#update-entity

**Comment by christothes** [comment]
Discussed offline and the blog documented behavior works as expected. Opened a tracking issue to improve docs on this behavior.
