### ISSUE TITLE
[FEATURE REQ] maxPollingInterval Per Queue or QueueTriggered Function 

### ISSUE THREAD

**Issue by phil000** [Azure/azure-sdk-for-net#33000]
### Library name

azure-sdk-for-net

### Please describe the feature.

Hello,
We have some queue-triggered azure functions running on .NET 7 in isolated mode.

We have set some custom properties in host.json file:
```
"extensions": {
      "queues": {
         "maxPollingInterval": "00:00:05",
         "visibilityTimeout": "00:15:00",
         "batchSize": 4,
         "maxDequeueCount": 16,
         "newBatchThreshold": 2,
         "messageEncoding": "base64"
      }
   }
```
However, these settings are not appropriate for all functions. In fact they really should differ quite a lot between functions\queues.

Is it possible to have these types of values _per queue or per queue-triggered function_, so that each can have their own:

1. Polling interval
2. Visibility Timeout
3. Max Dequeue Count

Less important per queue:
1. BatchSize
2. NewBatchThreshold

**Comment by phil000** [comment]
see also #31611

**Comment by jsquire** [comment]
Thank you for reaching out and we regret that you're having some difficulties.   Would you please let us know which Azure SDK package and version you're referring to so that we can triage this to the right folks to assist?

**Comment by phil000** [comment]
@jsquire 
Microsoft.Azure.Functions.Worker.Sdk 1.7.0
Microsoft.Azure.Functions.Worker 1.10.0
Microsoft.Azure.Functions.Worker.Extensions.Storage 5.0.1

**Comment by navba-MSFT** [comment]
@phil000 Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@phil000 To set the Polling Interval, Visibility Timeout and Dequeue Count, You can use the [QueueClient ](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient?view=azure-dotnet)class to manipulate the Azure Storage Queue. Please find the sample code [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.Storage.Queues/samples).

**Comment by phil000** [comment]
If we were interacting with the queues manually perhaps we could do that.

However, we are using queue triggered functions, so a lot of that is taken out of our hands. See the host.json configuration I posted.

e.g.
We are fed queue messages at a function entry point:
```
[Function("SendSmsMessage")]
public async Task Run([QueueTrigger(Queues.Outbox)] string message, string id, int dequeueCount, etc)
```

We are happy to be using queue triggered functions and it works well for us. We just need some more control over the interaction parameters for each function\queue, especially: 

- Polling interval
- Visibility Timeout
- Max Dequeue Count

**Comment by phil000** [comment]
I will also point out:

- This issue was created as a feature request
- We are using queue triggered functions in .NET 
- We will continue to use queue triggered functions
- We are hosting many different function apps on an *app service plan*
- Each function app has many functions
- We have overridden some properties in host.json to control queue interaction
- As there are many functions - but only 1 global setting we can change - the setting value is a _compromise_
- This feature of more control over individual function\queue interaction is definitely missing for us as the number and variability of functions grows

**Comment by navba-MSFT** [comment]
@phil000 Thanks for clarifying. I am adding Service team to look into this. 

@xgithubtriage Could you please look into this ?

**Comment by ArtyomYatskevich** [comment]
Hey guys, any updates regarding this feature request ?
