### ISSUE TITLE
[BUG]EventHubProducerClient SendAsync is not a synchronous call.

### ISSUE THREAD

**Issue by QingLu12345** [Azure/azure-sdk-for-net#33021]
### Library name and version

Azure.Messaging.EventHubs 5.7.5

### Describe the bug

I use EventHubProducerClient.SendAsync to send about 50,000 messages one by one. I use `await this.Client.SendAsync(batch);`  
It returns quickly. But I found that event hub sends message in background. It works like EventHubBufferedProducerClient.

### Expected behavior

Event hub completed to send message when SendAsync returns.

### Actual behavior

Event hub didn't complete to send message when SendAsync returns.

### Reproduction Steps

Use EventHubProducerClient.SendAsync to send 10,000 messages one by one and await it. It will return quickly.

### Environment

Windows 10, .NET 6.0
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.4.1

**Comment by jsquire** [comment]
Hi @QingLu12345.   Thank you for reaching out and we regret that you're experiencing difficulties.   Your information is not correct; events are placed on the outgoing AMQP link at the time `SendAsync` is called and the call completes after the service acknowledges receipt.  Event Hubs is an AMQP-based service and uses a persistent connection and does not have a request/response cycle and the associated overhead that an HTTP-based service call would.  

 It is also important to note that when the service acknowledges receipt of events for `SendAsync`, it signifies that the service has assumed responsibility for them.   At this point, they have not yet been committed to a partition and are not available to be read.  There will be some delay for that process to take place, and it is not one that the Event Hubs service offers an SLA for.   Generally, it takes a few milliseconds, but may take longer.   For example, if the target partition is migrating to a new host, events cannot be committed to its log until that process is complete.

**Comment by QingLu12345** [comment]
> Hi @QingLu12345. Thank you for reaching out and we regret that you're experiencing difficulties. Your information is not correct; events are placed on the outgoing AMQP link at the time `SendAsync` is called and the call completes after the service acknowledges receipt. Event Hubs is an AMQP-based service and uses a persistent connection and does not have a request/response cycle and the associated overhead that an HTTP-based service call would.
> 
> It is also important to note that when the service acknowledges receipt of events for `SendAsync`, it signifies that the service has assumed responsibility for them. At this point, they have not yet been committed to a partition and are not available to be read. There will be some delay for that process to take place, and it is not one that the Event Hubs service offers an SLA for. Generally, it takes a few milliseconds, but may take longer. For example, if the target partition is migrating to a new host, events cannot be committed to its log until that process is complete.

hi @jsquire , it delays too much time. I send about 5 MB data. After putting original data to EventDataBatch, the data size increase to about 200 MB. My network throughout is about 1M/s. I call SendAsync to send data, the call returns within 10 seconds. But actually it takes about 4 minutes. I want to make sure my data has been sent to partition. Do I have to use buffer publisher and receive the success event to confirm it?

**Comment by jsquire** [comment]
The `EventHubProducerClient` and `EventHubBufferedProducerClient` use the same transport underneath, and both receive the same acknowledgement from the service.   There will be no difference to the client-side behavior, other than when the client invokes the service operation.

The delay that you're inquiring about is server-side and not something that the SDK can influence or control.   If you'd like to discuss that further, I'd suggest that you [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for the Event Hubs service team.

**Comment by QingLu12345** [comment]
got it, thank you!
