### ISSUE TITLE
[FEATURE REQ] Add single SQL database to failover group

### ISSUE THREAD

**Issue by rbe-planday** [Azure/azure-sdk-for-net#33029]
### Library name

Azure.ResourceManager.Sql

### Please describe the feature.

I'm migrating from using the older, fluent library and missing a method to add a single database to an existing Failover Group. 

[Like used in this sample](https://github.com/Azure/azure-libraries-for-net/blob/fcc1e5b00376634dc8f675e655bffc76c1cf0e20/Samples/Sql/ManageSqlFailoverGroups.cs#L113)

Is there anything similar in this SDK besides the `FailoverGroupPatch` where the complete list of databases has to be provided?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hi @rbe-planday , the [FailoverGroupPatch.Databases](https://learn.microsoft.com/es-mx/dotnet/api/azure.resourcemanager.sql.models.failovergrouppatch.databases?view=azure-dotnet#azure-resourcemanager-sql-models-failovergrouppatch-databases) is a list, you can use its [Add](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.icollection-1.add?view=net-7.0#system-collections-generic-icollection-1-add(-0)) method to add a single database.

**Comment by rbe-planday** [comment]
@ArthurMa1978 Sorry, didn't specifiy my request fully. My scenario is that the Failover Group already has some databases, and I need to add another database to the group. 

Using the `FailoverGroupPatch` I also need to also add the existing databases to the  from [FailoverGroupData.Databases](https://learn.microsoft.com/es-mx/dotnet/api/azure.resourcemanager.sql.failovergroupdata.databases?view=azure-dotnet#azure-resourcemanager-sql-failovergroupdata-databases) as well as my new database.

It's not a big deal, just the convenience method `.WithNewDatabaseId(db.Id)` that used to exist in the old SDK.

**Comment by Yao725** [comment]
Hi @rbe-planday, Azure.ResourceManager.Sql is a totally re-designed SDK when compared with the fluent SDK, so we will not provide this kind of convenient method. Sorry for your inconvenience.
