### ISSUE TITLE
[QUERY] Publishing of Azure.Data.Tables to SQLUnified is outdated

### ISSUE THREAD

**Issue by wudragonfly** [Azure/azure-sdk-for-net#33020]
### Library name and version

Azure.Data.Tables

### Query/Question

It looks Azure.Data.Tables NuGet in SqlUnified is out of date. Any one here is in charge of the publishing? https://msdata.visualstudio.com/Database%20Systems/_artifacts/feed/SqlUnified/NuGet/Azure.Data.Tables/overview/12.0.1

**Comment by jsquire** [comment]
Hi @wudragonfly.   I'm not sure what that feed  is, but it is not one that the Azure SDK team owns or maintains.   Our packages are published to NuGet and our [development feed](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#nuget-package-dev-feed) only.   As a result, we're unable to assist with this; you'll need to reach out to the owner of that feed.
