### ISSUE TITLE
[QUERY] How does partition key work?

### ISSUE THREAD

**Issue by QingLu12345** [Azure/azure-sdk-for-net#33022]
### Library name and version

Azure.Messaging.EventHubs 5.7.5

### Query/Question

I have many messages which has a user id. I need to consume the messages which have the same user id in an instance. The simple solution is set partition key with user id. But I use the EventHubProducerClient SendAsync. The EventBatch can only set a partition key. So, I want to set partition key with 'UserId mod 10', it will be [0,9]. Does it work?

### Environment

Windows 10, .NET 6.0
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.4.1

**Comment by jsquire** [comment]
A partition key is recommended when you'd like to group related events together but do not need to control the exact partition that they are assigned to.   The Event Hubs service owns responsibility for providing a stable mapping from partition key to partition, such that events published with the same partition key will always end up in the same partition.  

In your scenario, I'd suggest just using the entire `UserId` as the partition key.   There's no benefit to applying the mod and having a wider range of values used as the partition key will help to ensure that you have more even distribution between partitions.

**Comment by QingLu12345** [comment]
> 

Thanks for replying. I want to send many messages in a batch. For example, I have 1 million messages with different user id. If I set the partition key with user id, I have to send only one message in an EventDataBatch. Can I get the partition id by partition key? If I can get partition id, then I can send the messages with the same partition id in a batch.

**Comment by jsquire** [comment]
You cannot resolve a partition id from the key.  If this is a requirement for your application, I'd suggest you perform the mapping of a user id to partition and then publish the batch for a specific partition id instead of using the key.

**Comment by QingLu12345** [comment]
Got it, thank you :)
