### ISSUE TITLE
[QUERY] Models from Compute like ManagedDiskData cannot be used in mocking, because you cannot add the properties you need

### ISSUE THREAD

**Issue by SavaDragos** [Azure/azure-sdk-for-net#33030]
### Library name and version

Azure.ResourceManager.Compute

### Query/Question

I am trying as part of testing to use some test instances for 'ManagedDiskData'. But I cannot actually give it a 'Name' because that property has no public set. (as an example we need the names to do some filtering)
I looked to see if factories to create instances for this models exist, but found nothing.
Other solutions to try and do this,  complicates the code a lot on my side (and feels wrong). 

What is the proposed solution?
I clearly read this should replace the old Compute resources, but those could be mocked, this stuff can't.
Yes, in some cases like: ManagedDiskCollection.GetManagedDisks() we can put another class between and that one can return the managed disks instead of the manageddiskcollection (by mocking). 
But for the models I  am not certain what to do.

Going and generating my own models, doesn't feel as a correct way of doing this.

### Environment

VS 17; .net 6;
Azure Functions that manages resources in Azure

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@SavaDragos we're working on the model factory for mocking test, you can follow https://github.com/Azure/autorest.csharp/issues/2112.
