### ISSUE TITLE
[QUERY] Store complex property type

### ISSUE THREAD

**Issue by VolvoTruckExpress** [Azure/azure-sdk-for-net#33032]
### Library name and version

Azure.Data.Table 12.7.1

### Query/Question

Is there any way to store a complex datatype in the Azure.Data.Tables library? There were ways in the WindowsAzure.Storage.Table library.

I am working on migrating existing code from Microsoft.WindowsAzure.Storage.Table.TableEntity(WindowsAzure.Storage) to Azure.Data.ITableEntity(Azure.Data.Tables). However there are a few issues. Consider the following Azure Table Entity:
```
public class WorkstationInfoTableEntity : Azure.Data.Tables.ITableEntity
{
    //ITableEntity
    public string PartitionKey { get; set; }
    public string RowKey { get; set; }
    public DateTimeOffset? Timestamp { get; set; }
    public ETag ETag { get; set; }

    public string CustomerId { get; set; }
    
    public string ReleaseChannelVersionsXml { get; set; }

    public ReleaseChannelVersionDTO[] ReleaseChannelVersions
    {
        get
        {
            return this.ParseReleaseChannelVersionsXml(this.ReleaseChannelVersionsXml);
        }
        set
        {
            this.ReleaseChannelVersionsXml = this.ConvertReleaseChannelVersionsToXml(value);
        }
    }
    ...
}
```

This code crashes:
```
var workstation = await WorkstationsManager.GetWorkstationInfoAsync(...., ....);
await table.UpsertEntityAsync(workstation);
```
The error is: "`An error occurred while processing this request.`" , because the `ReleaseChannelVersionDTO `class is not supported. The old library (i.e Microsoft.WindowsAzure.Storage.Table.TableEntity) simply ignored that property. There where even ways to handle the serialization/deserialization of properties in that old library ([example here](https://blog.bitscry.com/2019/04/12/adding-complex-properties-of-a-tableentity-to-azure-table-storage/)). There is no equivalent in the new one.

Is there any way way to solve the issue? Note that I cannot use the` [IgnoreDataMember] `attribute because the ReleaseChannelVersions property because it is used between multiple services and each one expects it to be filled/set.

### Environment

Windows 10, Net Framework 4.7.2
Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @VolvoTruckExpress - We don't currently support this type of customization to serialization, although we may add support for it in the future.

Just to clarify, are you intending to have the table ignore this property or flatten/serialize it to the table?

**Comment by christothes** [comment]
Thanks for the context. If the complex entity serialization is your goal, we are tracking this request here #27132 . Please feel free to vote it up in order to help us prioritize this feature.
