### ISSUE TITLE
Documentation & examples use deprecrated "windowsazure.mediaservices" & "Microsoft.Azure.Management.Media""

### ISSUE THREAD

**Issue by TheAustinG** [Azure/azure-sdk-for-net#33048]
This is honestly pretty frustrating but maybe I'm looking in the wrong places too.

I am attempting to migrate from v2 to v3 of the Media Service API but the documentation and code examples use deprecated packages so I have no idea where to begin.

[windowsazure.mediaservices](https://www.nuget.org/packages/windowsazure.mediaservices/) is deprecated and says to use [Microsoft.Azure.Management.Media](https://www.nuget.org/packages/Microsoft.Azure.Management.Media/) which is also deprecated and says to use [Azure.ResourceManager.Media](https://www.nuget.org/packages/Azure.ResourceManager.Media/).

The issue with all of this is that I can find no examples of how to use the latest SDK nuget package (Azure.ResourceManager.Media) to connect to & interact with Media Services now.

Any guidance would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82f63abe-8f7d-b896-4826-1d9d335e365b
* Version Independent ID: 4d137a8f-0e3f-ddc3-237b-2c64927232c3
* Content: [Azure Media Services SDK for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/media-services?view=azure-dotnet&preserve-view=true)
* Content Source: [api/overview/azure/latest/media-services.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/media-services.md)
* Service: **mediaservices**
* GitHub Login: @pallavit
* Microsoft Alias: **pallavit**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hi @TheAustinG , there is the general [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md) for Track 1 to Track 2.

The AMS team is still working on migrating our code samples to the newer .NET Track 2 SDK.
You can see all of our .NET samples up here - https://github.com/Azure-Samples/media-services-v3-dotnet/tree/track2 but not all of them are fully migrated over to track2 yet.

If you can use the 6.0 version of the SDK, (which is still supported), you can use the samples in the main branch
https://github.com/Azure-Samples/media-services-v3-dotnet/tree/main

Start with the simple encoding samples - https://github.com/Azure-Samples/media-services-v3-dotnet/tree/main/VideoEncoding/Encoding_H264

Please let us know if you have any other asks.

Add @johndeu  and @giakas for awareness .

**Comment by TheAustinG** [comment]
@ArthurMa1978 Thank you! I did not originally see the general migration guide that you have linked to, but that should help out quite a bit.

Looking forward to seeing all of the examples migrated over to Track 2.

**Comment by johndeu** [comment]
@TheAustinG  - There is a track2 branch in the sample repo for .NET that is in-progress work... We are chipping away at it when we have time. https://github.com/Azure-Samples/media-services-v3-dotnet/tree/track2 

Not many have been moved over, but you can look at the live and accounts samples to get the idea.
