### ISSUE TITLE
[BUG] Function App consumes only 8 messages per minute from Service Bus with Sessions Enabled topic

### ISSUE THREAD

**Issue by FBryant87** [Azure/azure-sdk-for-net#33046]
### Library name and version

Azure.Messaging.ServiceBus

### Describe the bug

After consuming 8 messages from service bus, our function app sits idle for the remainder of the minute and does nothing. It consistently consumes 8 messages per minute and no more, despite there being hundreds of messages on the subscription  containing hundreds of different SessionIds. 

This appears related to the 'MaxConcurrentSessions' configuration which defaults to 8. This configuration seems to be ignored in the host.json, but when setting it in the functions app settings we saw a brief improvement (64 messages per minute when the configuration was set to 64), and then a reduction back to 8 after half an hour. There is something at play which is pulling this back to 8 per minute every time.

Attached logs show a delay of 60 seconds between 2 messages (there was thousands of messages on this subscription at this point in time):

```
2022-12-14T15:20:40Z   [Information]   Executing 'MyEventHandler' (Reason='(null)', Id=799aa6c4-5ebe-4bad-9084-80869a8591c3)
2022-12-14T15:21:40Z   [Information]   Executing 'MyEventHandler' (Reason='(null)', Id=03415959-0d4a-46fd-8acd-6411bded1150)
```

[delay_between_consumed_messages.txt](https://github.com/Azure/azure-sdk-for-net/files/10229519/delay_between_consumed_messages.txt)

### Expected behavior

We've made an additional simple test ServiceBusTrigger function app which simply waits for a second and exits. We would expect to see around 60 messages consumed a minute, but instead we see 8 consistently.

### Actual behavior

Function Apps only consume 8 messages per minute from session enabled Service Bus topics.

### Reproduction Steps

Create a Linux consumption plan function app, and have it consume messages from a session enabled subscription with a high number of messages.

This is the function and startup we have in the simple test app (which is also limited to 8 messages per minute):
```

public class EventHandler
{
    [FunctionName("EventHandler")]
    public async Task Run([ServiceBusTrigger(TopicName,
            SubscriptionName,
            Connection = "ServiceBusConnectionString",
            IsSessionsEnabled = true)]
        ServiceBusReceivedMessage serviceBusReceivedMessage,
        ILogger logger)
    {
        logger.LogInformation("Consumed message!");

        await Task.Delay(1000);
    }
}

public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var config = new ConfigurationBuilder()
                .SetBasePath(Environment.CurrentDirectory)
                .AddEnvironmentVariables()
                .Build();

            builder.Services.AddLogging();
            builder.Services.AddSingleton<IConfiguration>(config);
        }
    }
```

### Environment

This is a v4 function app running on .net 6
Linux consumption plan
Using the latest stable version of all nuget packages.

**Comment by jsquire** [comment]
Additional context:  https://stackoverflow.com/questions/74797482/function-app-consumes-only-8-messages-per-minute-from-service-bus-with-sessions

**Comment by jsquire** [comment]
@FBryant87: Thanks for shifting over to an issue.   To start, it would be helpful to grab a +/- 10-minute slice of the Service Bus SDK logs so that we can better understand what the internals are seeing.  These logs take the form of an ETW event source named "Azure-Messaging-ServiceBus" and are automatically forwarded to Application Insights for an Azure Function.   Seeing information, warnings, and errors would be a good start.   

It is also possible to capture these manually in your application code using the `AzureEventSourceListener` from Azure.Core.  Additional information can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging), should you decide to do so.

**Comment by jsquire** [comment]
@JoshLove-msft:  Would you please take point?   This initially looked like to me like it was related to the fix from #33035, but after discussion, I'm not so sure.   The differentiator appears to be that there were a good number of messages available to read in the subscription when the session lock was acquired.

**Comment by JoshLove-msft** [comment]
Can you let us know how many messages there are per session? If each session only has a single message then you would be limited by the MaxConcurrentSessions settings. To allow the processor to switch more quickly to different sessions, you can adjust the "sessionIdleTimeout" value in host.json.

**Comment by FBryant87** [comment]
In the scenarios we're looking at, there are around 500 messages on the subscription with messages containing around 450 different SessionIds. So despite there being numerous sessions to pick from, the function app consistently pulls ~8 per minute. This appears to be directly tied to the MaxConcurrentSessions default limit of 8:

https://i.ibb.co/kDF7JZw/upload2.png

What I've thus far been unable to explain, is that when we forced the app to respect this limitation by putting the below config in the app settings:

`AzureFunctionsJobHost__extensions__serviceBus__sessionHandlerOptions__maxConcurrentSessions 64`

We saw the issue successfully resolve itself. Unfortunately it only lasted for around half an hour, then it dropped back to the default of 8:

https://i.ibb.co/5TpnJMY/upload1.png

There appears to be something very strange going on with that MaxConcurrentSessions configuration. Changing the sessionIdleTimeout doesn't appear to have much impact in our case.

**Comment by FBryant87** [comment]
Reproduced on an entirely separate environment with a different function app and premium service bus. Throwing hundreds of messages onto the subscription again originally results in excellent performance, but then always drops back to the standard 8 per minute (without any changes to the app).

Here the hundreds of messages all have a unique sessionId (a GUID). Is it possible the function app consumption plan is enforcing a limit after a period of time?

https://i.ibb.co/T85LgKW/upload3.png

**Comment by FBryant87** [comment]
From the results I'm currently seeing, this does seem to be caused by too many unique SessionIds across messages. I may try hashing the message SessionIds to reduce this to 10 unique sessions.

**Comment by JoshLove-msft** [comment]
That makes sense - you can also try significantly reducing the sessionIdleTimeout setting to allow the processor to more quickly pick up new sessions.

**Comment by FBryant87** [comment]
Thank you!
