### ISSUE TITLE
ServiceClient.Dispose method disposes HttpClients passed in through constructor overload

### ISSUE THREAD

**Issue by markcowl** [Azure/azure-sdk-for-net#3305]
### Description

This code: https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SdkCommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L376 will automatically dispose an HttpClient, even if it is supplied in the constructor.

Need branching logic to differentiate between HttpClients created as part of construction and HttpClients passed in to the constructor, and only dispose the HttpClients we create.

- [ ] Conditional dispose of HttpClient depending on whether it was passed in to constructor
- [ ] Test to verify HttpClient reuse after a serviceClient dispose

### Cost: 4

**Comment by shahabhijeet** [comment]
@markcowl our only option is to Clone the httpClient.
But what I am not sure is, any reason we want to support this feature.
We are disposing ServiceClient and it's properties.
If the caller wants httpClient beyond ServiceClient, they should DeepCopy the client and save a copy.
The bottom line is, we are disposing ServiceClient and that will dispose all it's properties which being HttpClient.

**Comment by markcowl** [comment]
@shahabhijeet Yes, the entire idea is httpclient reuse.  HttpClient is a hewvyweight artifcat which is expensive to clone.  This is a specific ask of teams that use our clients in the portal, and is a reason they have not moved from Hyak to AutoRest

**Comment by markcowl** [comment]
Here is a simple repro:

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApplication3
{
    public class DummyClient : ServiceClient<DummyClient>
    {
        public DummyClient(HttpClient httpClient) : base(httpClient)
        {

        }
    }
    class Program
    {
        public static void Main(string[] args)
        {
            using (var httpClient = new HttpClient())
            {
                using (var client = new DummyClient(httpClient))
                {
                    var ua = client.UserAgent;
                }
                // the following line throws an ObjectDisposedException
                var response = httpClient.SendAsync(new HttpRequestMessage(HttpMethod.Get, "http://www.microsoft.com")).GetAwaiter().GetResult();
            }

            Console.ReadLine();
        }
    }
```
