### ISSUE TITLE
How does one create API connections needed for Logic apps?

### ISSUE THREAD

**Issue by gorygregory** [Azure/azure-sdk-for-net#33064]
### Library name and version

Azure.ResourceManager.Logic.1.0.0

### Query/Question

How does one go about creating the connections needed to provision a logic app using this nuget package? I don't see any ways to do that using this nuget. None of the other Azure.ResourceManager.* nuget packages seem to expose this capability.

In general, the documentation for creation of LogicApps using this SDK is fairly lacking in samples/examples. It would be good to have common connections to event hub/service bus etc.. documented with all their authentication types.

**Comment by ArthurMa1978** [comment]
Thank you for your feedback, @HarveyLink please help on this question.

**Comment by dvbb** [comment]
The SDK(Rest API) Azure.ResourceManager.Logic does not support creating a connection with event hubs or other resources. Although [CreateOrUpdate](https://learn.microsoft.com/en-us/rest/api/logic/workflows/create-or-update?tabs=HTTP) method allows adding definition payload, the definition only allows an existing connection like that:
```json
{
  "definition": {
    "$schema": "https://schema.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {},
    "triggers": {},
    "actions": {
      "Response": {},
      "Send_event": {
        "runAfter": {
          "Response": [
            "Succeeded"
          ]
        },
        "type": "ApiConnection",
        "inputs": {
          "host": {
            "connection": {
              "name": "@parameters('$connections')['eventhubs']['connectionId']"
            }
          },
          "method": "post",
          "path": "/@{encodeURIComponent('hub1')}/events"
        }
      }
    },
    "outputs": {}
  }
}
```
