### ISSUE TITLE
Azure Event Hub - How to consume events with EventProcessorClient and save them on Sql Server

### ISSUE THREAD

**Issue by pampua84** [Azure/azure-sdk-for-net#33067]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.7.5

### Query/Question

Hi, 
reading a response to post on StackOverflow by @jsquire ( [https://stackoverflow.com/questions/69133480/azure-event-hub-how-to-consume-events-parallelly-using-the-official-sdk](url) ), I thought I could ask for some help here so I could fix a problem. 
I have an application in .NET 7, precisely a Worker that should infinitely read events (log in json format) from Azure Event Hub and write them to Sql Server. For the implementation I chose to use the EventProcessorClient, as it has to read from 3 partitions and I can use the Azure Blob Storage for checkpointing.
Reading the official documentation and following the examples I wrote the following code:

```csharp
public class LogProcessorBackgroundService : BackgroundService
{
    // Omit configuration and initialization of objects

    private readonly ConcurrentDictionary<Guid, KeyValuePair<DateTime, ClientEvent>> _clientEvents = new();

    private readonly ILogger<LogProcessorBackgroundService> _logger;
    private readonly IServiceProvider _serviceProvider;

    public LogProcessorBackgroundService(ILogger<LogProcessorBackgroundService> logger,
        IServiceProvider serviceProvider)
    {
        Guard.Against.Null(logger);
        Guard.Against.Null(serviceProvider);

        _logger = logger;
        _serviceProvider = serviceProvider;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        try
        {
            var storageClient = new BlobContainerClient(StorageConnectionString, BlobContainerName);

            var processor = new EventProcessorClient(
                storageClient, ConsumerGroup, EventHubConnectionString, EventProcessorClientOptions);

            processor.ProcessEventAsync += OnProcessEvent;
            processor.ProcessErrorAsync += OnProcessError;

            await processor.StartProcessingAsync(stoppingToken);
        }
        catch (TaskCanceledException e)
        {
            _logger.LogError(e.Demystify(), "Task was canceled");
        }
        catch (Exception e)
        {
            _logger.LogError(e.Demystify(), "An unhandled exception has occurred");
        }
    }

    private Task OnProcessError(ProcessErrorEventArgs errorEventArgs)
    {
        _logger.LogError(errorEventArgs.Exception, "OnProcess error");

        return Task.CompletedTask;
    }

    private async Task OnProcessEvent(ProcessEventArgs eventArgs)
    {
        try
        {
            if (eventArgs.Data?.EventBody is null ||
                eventArgs.Data.EventBody.ToString().Contains(Constants.EventType.Failure))
                return;
            
            var logAudit = JsonSerializer.Deserialize<LogAuditRoot>(eventArgs.Data.EventBody.ToString(),
                SerializerOptions);

            var clientEvent = logAudit.ClientEvent;

            if (_clientEvents.TryGetValue(clientEvent.ClientId, out var item))
            {
                if (item.Key > clientEvent.TimeStamp)
                    return;

                _clientEvents.Remove(clientEvent.ClientId, out _);
            }

            _clientEvents.TryAdd(clientEvent.ClientId,
                new KeyValuePair<DateTime, ClientEvent>(clientEvent.TimeStamp, clientEvent));

            if (_clientEvents.Count == 100)
            {
                await UpsertDataOnDatabase();
                eventArgs.UpdateCheckpointAsync(eventArgs.CancellationToken);
                _clientEvents.Clear();
            }
        }
        catch (Exception e)
        {
            _logger.LogError(e, "ProcessEventHandler exception");
        }
    }

    private async Task UpsertDataOnDatabase()
    {
        using var scope = _serviceProvider.CreateScope();

        var repository = scope.ServiceProvider.GetRequiredService<IRepository>();

        _logger.LogInformation("Count: {Count}", _clientEvents.Count.ToString());

        foreach (var item in _clientEvents)
        {
           // Some logic to update or insert data into sql server
        }

        await repository.SaveChangesAsync();
    }
}
```
As reported by Jesse Squire however the processor '"For each partition owned by the processor, an independent background task works to read events from Event Hubs and dispatch them to your handler." so I used a ConcurrentDictionary and implemented this logic to checkpoint every certain number of events, but it doesn't work correctly. Could you please help me understand if I'm on the right track or where I'm wrong and tell me what changes to make. 
Sorry for writing here, but unfortunately on the internet I have not found advanced examples on how to handle it, but only the basic ones.
I hope you can help me. Thank you

### Environment

- OS:  Windows 11, Windows Server 2016
- Runtime: .NET  7.0.0
- Project type: Worker project
- Database: SqlServer 2016

**Comment by pampua84** [comment]
Hi @jsquire, first of all thank you very much for the answer, I will start by making the change you indicated and doing some tests to understand if the rest of the implementation can work or not, or given the concurrency that I can't manage precisely it is better that i use the PartitionReceiver and create different workers each managing their own partition?

**Comment by jsquire** [comment]
Whether you use the processor or the receiver, you'd still need to manage the same amount of information to achieve the functionality that you're looking for.   Both types could be used for the scenario that you've described here and on the linked StackOverflow question, it's a matter of choosing which set of trade-offs work better for you.   I'd suggest reading the [Event Hubs clients sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample02_EventHubsClients.md), which details the client hierarchy and provides some context around their target scenarios.

**Comment by pampua84** [comment]
Hi @jsquire, thanks a lot for the suggestions, by making changes to my application I was able to record the events on the DB and then in a second step I was able to process them following the set logic. Thank you
