### ISSUE TITLE
Documentation for UploadAsync(BinaryData) is wrong

### ISSUE THREAD

**Issue by Bouke** [Azure/azure-sdk-for-net#33071]
The documentation for [UploadAsync(BinaryData)](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet#azure-storage-blobs-blobclient-uploadasync(system-binarydata)) states:

> or updates the content of an existing block blob

but that's not true; it'll throw if the blob exists, so it should read instead:

> or throws if the blob already exists

There are possibly other overloads with the same issue, like [UploadAsync(Stream)](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet#azure-storage-blobs-blobclient-uploadasync(system-io-stream)).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84dd6a0a-8ef5-bb23-6498-a6a6b75995c7
* Version Independent ID: 236218cc-38cb-0067-5cbf-1d36f63bbddf
* Content: [BlobClient.UploadAsync Method (Azure.Storage.Blobs) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/Azure.Storage.Blobs.BlobClient.UploadAsync?view=azure-dotnet&viewFallbackFrom=netstandard-2.0)
* Content Source: [xml/Azure.Storage.Blobs/BlobClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs/BlobClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@Bouke Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.
