### ISSUE TITLE
[FEATURE REQ] Self-descriptive custom exception for case with message that is already being cancelled

### ISSUE THREAD

**Issue by VolodymyrKLymenko** [Azure/azure-sdk-for-net#33077]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

I have small app where some of the messages are scheduled in service bus and there is scenario when some of that messages might be cancelled from scheduling by calling `CancelScheduledMessageAsync()` method in `ServiceBusSender` from SDK.

And there are few cases when same message in ServiceBus is attempted to cancel from several different places almost simultaneously. One request to cancel is succesfull and another causes the exceptions.

It's expected but the problem is when I am trying to catch and handle that exception.

As I want to track only this specific cases with simultaneous cancelling of same message.
But I am getting general `InvalidOperationException` and the only place there what can be used for identifying this case is exception's message field (which is sth. like: `The scheduled message with SequenceNumber = 125125 is already being cancelled....`

![image](https://user-images.githubusercontent.com/19861807/207918921-0406f1b8-5931-4df7-ad13-77b08653911a.png)

But using of exception's `message` field in `catch (...) { ... }` is not convenient and not beautifully)

**Possible solution:**
It would be nice to have some custom client exception here.
As an idea maybe it would be good to throw `ServiceBusException` here like it is done for case when message was already cancelled but with different value of `ServiceBusFailureReason` enum for this case.

Then it would be possible to do sth. like this:

![image](https://user-images.githubusercontent.com/19861807/207915942-9977c74f-63f7-45ac-926e-a8b9be615f21.png)

But with different `ServiceBusFailureReason`

**Comment by jsquire** [comment]
Hi @VolodymyrKLymenko.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this is not a change that can be made for a couple of reasons:

- The failure occurs in the Service Bus service, which returns an AMQP error code that corresponds to "Not Allowed."   The client has no insight into the why the error occurred, it simply knows that the service failed the operation. 

- The exception message is intended by the service to be informational, and its format/verbiage may change.  Having the client attempt to determine context and reclassify the failure based on the informational text would be a brittle approach and potentially create non-deterministic behavior for callers.

- Altering the type of exception surfaced for an operation is a breaking change, which we do not make.  This kind of change would break applications that rely on an `InvalidOperationException` in this scenario to trigger logic.

As a work-around and an alternative to having your application take the brittle approach of parsing the exception message, you may want to consider wrapping the call such that you prevent concurrent attempts to cancel a given sequence number.  In basic form, this may look something like:

```csharp
[Serializable]
public class ConcurrentCancelException : Exception
{
    public ConcurrentCancelException() : base() { }
    public ConcurrentCancelException(string message) : base(message) { }
    public ConcurrentCancelException(string message, Exception inner) : base(message, inner) { }
}

public static class ServiceBusSenderExtensions
{
    // There's no concurrent hashset, so we'll abuse the dictionary instead.

    private static ConcurrentDictionary<long, byte> activeCancellations = new();
    
    public static async Task CancelScheduledMesssageAsync(
        this ServiceBusSender sender,
        long sequenceNumber,
        CancellationToken cancellationToken = default)
    {
        if (!activeCancellations.TryAdd(sequenceNumber, 0))
        {
            // There's already someone cancelling; throw a failure.
            
            throw new ConcurrentCancelException(
                $"Sequence number {sequenceNumber} is already being cancelled");
        }

        try
        {
            await sender.CancelScheduledMessageAsync(
                sequenceNumber, 
                cancellationToken)
            .ConfigureAwait(false);
        }
        catch
        {
            // Add any logic for tracking failures, if needed.  
        }
        finally
        {
            // Success or failure, there's no longer anything in progress.
            
            activeCancellations.TryRemove(sequenceNumber, 0);
        }
    }
}
```

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
