### ISSUE TITLE
InteractiveBrowserCredential raises exception if https://localhost is configured as redirect uri

### ISSUE THREAD

**Issue by Trivedi-Ashish** [Azure/azure-sdk-for-net#33070]
I have a .NET core 3.1 application, which uses Interactive Authentication flow from Azure.Identity SDK to get an access token. I am getting below exception if I configure https://localhost as redirect uri.

_Unhandled exception. Azure.Identity.AuthenticationFailedException: InteractiveBrowserCredential authentication failed: Only http uri scheme is supported, but https was found. Configure http://localhost or http://localhost:port both during app registration and when you create the PublicClientApplication object. See https://aka.ms/msal-net-os-browser for details
 ---> MSAL.NetCore.4.46.0.0.MsalClientException:
        ErrorCode: loopback_redirect_uri_

So, it does not support https uri scheme but Azure/Microsoft recommends secure https uri scheme for configuring redirect uri.
https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url
I do not understand this probable contradiction. 

Testing Platform: Windows 11 OS
Application targets .NET Core 3.1
Azure.Identity SDK: 1.8.0
Code snippet used:

```
      var options = new InteractiveBrowserCredentialOptions
      {
        ClientId = "<ClientId>",
        TenantId = "<TenantId>",
        RedirectUri = new Uri("https://localhost")
      };

      var tokenRequestContext = new TokenRequestContext(new[] { "<scope>" });
      string token = new InteractiveBrowserCredential(options).GetToken(tokenRequestContext).Token;
```

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @Trivedi-Ashish - This error [comes from MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/35287730c8a55092e707ef024af38daed88d2773/src/client/Microsoft.Identity.Client/Platforms/Features/DefaultOSBrowser/DefaultOsBrowserWebUi.cs#L108-L110). Would you mind [opening up an issue there](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues) for this?

**Comment by jsquire** [comment]
> Is it possible to route this current issue to MSAL team?

Unfortunately, it is not.   Because the repositories are under different GitHub organizations, a direct issue transfer is not possible.   Your best bet for doing so would be to copy the body of this issue to a new one.
