### ISSUE TITLE
[BUG] Communication.Email is impossible to use just with to and cc recipients

### ISSUE THREAD

**Issue by frasparacio** [Azure/azure-sdk-for-net#33074]
### Library name and version

Azure.Communication.Email_1.0.0-beta.1

### Describe the bug

In line 35 there is a bug in if condition which make the constructor of EmailRecipients fails if you use just To and Cc.

https://github.com/Azure/azure-sdk-for-net/blob/Azure.Communication.Email_1.0.0-beta.1/sdk/communication/Azure.Communication.Email/src/Models/EmailRecipients.cs

I saw this is already solved in main branch, please a new release of the package might fix it! 

### Expected behavior

Constructor working correctly

### Actual behavior

Exception 

### Reproduction Steps

var recipients = new EmailRecipients(to, cc);

**Comment by PramodValavala-MSFT** [comment]
@frasparacio Thanks for the feedback! We will check with the concerning team and get back to you.

**Comment by PramodValavala-MSFT** [comment]
@frasparacio Quick Update - There would be a new release of the SDK later this month
