### ISSUE TITLE
[BUG] Azure.Monitor.OpenTelemetry.Exporter is referencing OpenTelemetry-1.4.0-beta.2 which is not compatible with OpenTelemetry 1.4.0-beta.3 or 1.4.0-rc.1.

### ISSUE THREAD

**Issue by nickeeex** [Azure/azure-sdk-for-net#33081]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.5

### Describe the bug

Unable to log metrics to app insights with Azure.Monitor.OpenTelemetry.Exporter

```
OpenTelemetry-AzureMonitor-Exporter - EventId: [2], EventName: [WriteError], Message: [FailedToExport - System.MissingMethodException: Method not found: 'Boolean OpenTelemetry.Metrics.MetricPoint.HasMinMax()'.
   at Azure.Monitor.OpenTelemetry.Exporter.Models.MetricDataPoint..ctor(Metric metric, MetricPoint metricPoint)
   at Azure.Monitor.OpenTelemetry.Exporter.Models.MetricsData..ctor(Int32 version, Metric metric, MetricPoint metricPoint)
   at Azure.Monitor.OpenTelemetry.Exporter.Internals.MetricHelper.OtelToAzureMonitorMetrics(Batch`1 batch, String roleName, String roleInstance, String instrumentationKey)
   at Azure.Monitor.OpenTelemetry.Exporter.AzureMonitorMetricExporter.Export(Batch`1& batch)]
```

Was guided to report the issue here.

https://github.com/open-telemetry/opentelemetry-dotnet/issues/4012#issuecomment-1352996802

### Expected behavior

Metrics should be exporter to azure app insights

### Actual behavior

Can't export metrics to azure app insights

### Reproduction Steps

Using OpenTelemetry 1.4.0-beta.3 or 1.4.0-rc.1. with Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.5

### Environment

`Windows 10 dotnet7.0`

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by cijothomas** [comment]
_Using OpenTelemetry 1.4.0-beta.3 or 1.4.0-rc.1. with Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.5_

^ How is this possible? 1.0.0-beta.5 of AzureMonitor exporter only works with 1.4.0-beta.2 of OpenTelemetry, as indicated in nuget dependency :  https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.Exporter/1.0.0-beta.5#dependencies-body-tab
