### ISSUE TITLE
[ContainerRegistry] CanGetManifestProperties failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33099]
ContainerRegistry nightly test runs are failing with:

> Error message
> Expected: arm64
> But was:  null
> 
> 
> Stack trace
>    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.<CanGetManifestProperties>d__3.MoveNext() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\tests\RegistryArtifactLiveTests.cs:line 70
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 
> 1)    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.<CanGetManifestProperties>d__3.MoveNext() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\tests\RegistryArtifactLiveTests.cs:line 70

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2059130&view=results

@jsquire for notification.

**Comment by annelo-msft** [comment]
This is a known service regression, and being addressed by https://github.com/Azure/azure-sdk-for-net/pull/33105
