### ISSUE TITLE
[Core] VerifyRetryAfterSasCredentialUpdateOperation failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33100]
Core nightly test runs are failing with:

> Error message
> Expected string length 35 but was 61. Strings differ at index 13.
> Expected: "?foo=bar&sig=second_signature_value"
> But was:  "?foo=bar&sig=first_signature_value&sig=second_signature_value"
> ------------------------^
> 
> 
> Stack trace
>    at Azure.Core.Tests.AzureSasCredentialSynchronousPolicyTests.<>c__DisplayClass5_0.<VerifyRetryAfterSasCredentialUpdateOperation>b__0(MockRequest req) in D:\a\_work\1\s\sdk\core\Azure.Core\tests\AzureSasCredentialSynchronousPolicyTests.cs:line 117
>    at Azure.Core.TestFramework.MockTransport.<>c__DisplayClass14_0.<.ctor>b__0(HttpMessage req) in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\MockTransport.cs:line 41
>    at Azure.Core.TestFramework.MockTransport.<ProcessCore>d__20.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\MockTransport.cs:line 93
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Azure.Core.TestFramework.MockTransport.<ProcessAsync>d__19.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\MockTransport.cs:line 72
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Core.Pipeline.HttpPipelineTransportPolicy.<ProcessAsync>d__4.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Pipeline\Internal\HttpPipelineTransportPolicy.cs:line 27
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Pipeline\RetryPolicy.cs:line 87
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Pipeline\RetryPolicy.cs:line 159
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
>    at Azure.Core.Pipeline.HttpPipeline.<SendRequestAsync>d__18.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Pipeline\HttpPipeline.cs:line 202
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.Tests.AzureSasCredentialSynchronousPolicyTests.<VerifyRetryAfterSasCredentialUpdateOperation>d__5.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\tests\AzureSasCredentialSynchronousPolicyTests.cs:line 130
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Awai

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2058338&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
//cc: @annelo-msft, @christothes, @JoshLove-msft, @AlexanderSher

**Comment by christothes** [comment]
I've been chasing this down and thought I resolved it yesterday. Will investigate.

**Comment by christothes** [comment]
Actually this test ran before my fix here #33078
