### ISSUE TITLE
[BUG] - SessionLockLost on throttled requests

### ISSUE THREAD

**Issue by Rayzbam** [Azure/azure-sdk-for-net#33104]
### Library name and version

Azure.Messaging.ServiceBus 7.10.0

### Describe the bug

We encoutered a lot of "SessionLockLostException" where the SessionLockUntilUtc is not reached.

I read other bugs complaining about this issue and thought i had the same issue.
After that, i checked on Azure the namespace health and i saw many throttled requests : 

![Azure-SB](https://user-images.githubusercontent.com/52962035/208076442-62dbad98-6853-4470-9049-b21732045a6e.png)

All these throttled requests are on the queue working with session.
We have 4 nodes handling this queue with "MaxConcurrentSessions" setted to 100. 
Of course we have a lot of other things on this namespace.

I have 2 issues :
- If the namespace is throttled, why is there only my session processor throttling ? I mean other simple queues should throttled too ? Is there any different RetryPolicy ?
- Why the only error i get is this "SessionLockLostException", whereas the main information here is the throttled of my namespace that seems to be silent due to this. 

I would like to know that my namespace is throttling thanks to my exception handling.

To be honest, the SessionLockLostException seems to be well handled and messages being processed are not sent to the deadletter or something and just treated later.
But we're spamming our logs with a "SessionLockLostException" which is not the source exception here, it's not helping to resolve the root cause.

### Expected behavior

Catching the ThrottledException in the Message processing of a SessionProcessor.

The previous SDK had a much better handling of this case, when these situations happened we had these kind of logs :

![AppInsights](https://user-images.githubusercontent.com/52962035/208082296-271a9cd6-cdcf-4ae7-b346-679cf0cde1dd.png)

### Actual behavior

Catching a "SessionLockLostException" which is simply a consequence of the throttling.

### Reproduction Steps

It's pretty hard to have a good reproduction workflow to be honest, but we just throttled our namespace in our Production environment (see the image)

### Environment

Windows 2019
.net framework 4.7.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
This sounds similar to the issue here https://github.com/Azure/azure-sdk-for-net/issues/25275. The underlying issue there is that when the service throttles a request it ends up releasing the lock for any delivered but unsettled messages. This seems like it could be the same underlying issue but with session locks. 

Another possibility is that if your session lock duration is low, the automatic backoff applied by the library of 10 seconds could cause the session lock to be lost. Can you let us know what your session lock duration is? 

As for reporting the throttling exceptions, are you saying that you are not seeing these in error logs? You should still be seeing these in error logs in App Insights. The subsequent errors are not really able to be tied back to the fact that you were throttled previously. 

As for why you are only being throttled on one entity, you are correct that throttling applies to the whole namespace as described [here](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-throttling), but is it possible that the part of your app using the session processor is making much more requests than other parts of your app dealing with other queues?

**Comment by JoshLove-msft** [comment]
I did find a loophole where we would incorrectly log retriable exceptions as verbose instead of warnings which I am fixing here - https://github.com/Azure/azure-sdk-for-net/pull/33106

**Comment by Rayzbam** [comment]
@JoshLove-msft Our lockDuration is 5minutes on all our queues.
For this queue, we renew the session lock every time we receive a message and the "SessionLockedUntil" is about to expire in 1minute or less.
I'm pretty sure we still have the lock for all the session when this issue happens.

I can confirm that we don't have the throttled error through the delegate provided by the SessionProcessor for handling errors. Maybe we can have it adding some verbose logs but imo it should not be required to see a major issue like a throttle exception.

You're right, this processor is making much more requests than other queues on this namespace but we still have some work everytime in a day tbh .. But i guess i can agree with that, and i'm glad it's not happening on our others queues :)

I don't understand your change. i mean a ThrottleException seems to be a "retriable exception" so yes i would like to "hide" these logs, but my exception is a "SessionLockException" which is not a "retriable exception".

To add some details, we migrated to the new SDK few weeks ago, and the old SDK threw this "ThrottleException" so i don't think it's a normal behavior

**Comment by Rayzbam** [comment]
> In that case, this suggests there is a bug in the service that is causing the lock to be lost when a request is throttled, this is similar to the existing issue (#25275) in which the message lock is lost for unsettled messages when a request is throttled for non-session queues.
Is this bug on your priority list ?

> These would be logged as Warning, not Verbose.

Warning logs are not passed to the processor delegate right ? Only errors ones ? So yeah it should not affect my usecase here.

> The exception would only be thrown, in both old and new SDK, if all retries are exhausted. It shouldn't be thrown if there are still retries remaining. Instead it would be logged as a Warning.

Can i presume that the default retry policy between those 2 SDKs is just different ? I mean i configured the retryPolicy on the new SDK but i never thought it was applied on these kinds of errors.

I still don't understand how i can get "SessionLockException" without having deadletters message. I mean when i lost the lock, i shouldn't able to complete or abandon any message. Unless all these SessionLockLost are only on the "AcceptMessageSession" before locking any message of the session ..

**Comment by JoshLove-msft** [comment]
Is this bug on your priority list ?
> @EldertGrootenboer is there any update on https://github.com/Azure/azure-sdk-for-net/issues/25275? We seem to be seeing a similar issue but with session locks here.

Warning logs are not passed to the processor delegate right ? Only errors ones ? So yeah it should not affect my usecase here.
> No logs are passed to the delegate. Only exceptions that are thrown and not handled by the retry policy propagate to the delegate.

Can i presume that the default retry policy between those 2 SDKs is just different ? I mean i configured the retryPolicy on the new SDK but i never thought it was applied on these kinds of errors.
> I don't think the policy is different. This is considered a retriable error in both the old and new SDK.

I still don't understand how i can get "SessionLockException" without having deadletters message. I mean when i lost the lock, i shouldn't able to complete or abandon any message. Unless all these SessionLockLost are only on the "AcceptMessageSession" before locking any message of the session ..
> The messages wouldn't necessarily be deadlettered, but the delivery count would be increased if the session lock expired - https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-sessions#impact-of-delivery-count.

**Comment by Rayzbam** [comment]
@JoshLove-msft Is there any possibility to track the "Credit count" on a namespace ? I just divide by 2 the MaxConcurrentSession and still got the "SessionLockLostException".

Here is how i setup my session processor (with a MaxConcurrentSessions setted to 50 instead of 100 yesterday) :

`Client.CreateSessionProcessor(targetQueue, new ServiceBusSessionProcessorOptions
                {
                    AutoCompleteMessages = false,
                    ReceiveMode = ServiceBusReceiveMode.PeekLock,
                    MaxConcurrentSessions = Math.Max(options.MaxConcurrentTasks ?? 0, 1),
                    SessionIdleTimeout = TimeSpan.FromSeconds(5)
                });`

> The messages wouldn't necessarily be deadlettered, but the delivery count would be increased if the session lock expired

Sorry, i don't give you all the information here. All our MaxDeliveryCount are setted to 1.

**Comment by JoshLove-msft** [comment]
No it isn't possible to get this information from the client library. You could open a support ticket in the Azure Portal, and the service team will be able to take a look at the server logs to help understand why you are being throttled.

**Comment by Rayzbam** [comment]
I'm closing the issue and trying to follow the #25275 issue. Thanks for your help @JoshLove-msft
