### ISSUE TITLE
[Search] CreateAzureBlobIndexer failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33101]
Search nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : The precondition given in one of the request headers evaluated to false. No change was made to the resource from this request.
> Status: 412 (Precondition Failed)
> 
> Content:
> {"error":{"code":"","message":"The precondition given in one of the request headers evaluated to false. No change was made to the resource from this request."}}
> 
> Headers:
> Cache-Control: no-cache
> Pragma: no-cache
> client-request-id: 730c9280-e5d9-4053-808b-1818cd06d29d
> x-ms-client-request-id: 730c9280-e5d9-4053-808b-1818cd06d29d
> request-id: 730c9280-e5d9-4053-808b-1818cd06d29d
> elapsed-time: 1306
> Preference-Applied: REDACTED
> Strict-Transport-Security: REDACTED
> Date: Thu, 15 Dec 2022 17:52:35 GMT
> Content-Type: application/json; charset=utf-8
> Content-Language: REDACTED
> Expires: -1
> Content-Length: 160
> 
> 
> Stack trace
>    at Azure.Search.Documents.IndexersRestClient.CreateOrUpdateAsync(String indexerName, SearchIndexer indexer, String ifMatch, String ifNoneMatch, Nullable`1 skipIndexerResetRequirementForCache, Nullable`1 disableCacheReprocessingChangeDetection, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/src/Generated/IndexersRestClient.cs:line 311
>    at Azure.Search.Documents.Indexes.SearchIndexerClient.CreateOrUpdateIndexerAsync(SearchIndexer indexer, Boolean onlyIfUnchanged, Nullable`1 ignoreCacheResetRequirements, Nullable`1 disableCacheReprocessingChangeDetection, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/src/Indexes/SearchIndexerClient.cs:line 406
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 120
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 171
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 201
>    at Azure.Search.Documents.Tests.SearchIndexerClientTests.CreateAzureBlobIndexer() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/SearchIndexerClientTests.cs:line 93
>    at Azure.Search.Documents.Tests.SearchIndexerClientTests.CreateAzureBlobIndexer() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/SearchIndexerClientTests.cs:line 111
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2058509&view=results

@jsquire for notification.

**Comment by ShivangiReja** [comment]
It was just a one time failure in one OS environment. Reran the pipeline and it's passing.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2058509&view=results
