### ISSUE TITLE
[ServiceBus] CustomMessageProcessorTest failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33102]
ServiceBus nightly test runs are failing with:

> Error message
> System.AggregateException : One or more hosted services failed to stop. (Multiple failures or warnings in test:
> 
> Expected: less than 2022-12-15 14:26:37.2254
> But was:  2022-12-15 14:26:38.2
> 
> Expected: 1
> But was:  2
> 
> Expected: 1
> But was:  3
> 
> Expected: 1
> But was:  4
> 
> Expected: 1
> But was:  5
> 
> Expected: 1
> But was:  6
> 
> Expected: 1
> But was:  7
> 
> Expected: 1
> But was:  8
> 
> Expected: 1
> But was:  9
> 
> Expected: 1
> But was:  10
> 
>  at Microsoft.Azure.WebJobs.ServiceBus.MessageProcessor.CompleteProcessingMessageAsync(ServiceBusMessageActions actions, ServiceBusReceivedMessage message, FunctionResult result, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Primitives/MessageProcessor.cs:line 77
> at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.CustomMessagingProvider.CustomMessageProcessor.<>n__1(ServiceBusMessageActions actions, ServiceBusReceivedMessage message, FunctionResult result, CancellationToken cancellationToken)
> at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.CustomMessagingProvider.CustomMessageProcessor.CompleteProcessingMessageAsync(ServiceBusMessageActions actions, ServiceBusReceivedMessage message, FunctionResult result, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusEndToEndTests.cs:line 1782
> at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.ProcessMessageAsync(ProcessMessageEventArgs args) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs:line 291
> at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessMessageAsync(ProcessMessageEventArgs args)
> at Azure.Messaging.ServiceBus.ReceiverManager.OnMessageHandler(EventArgs args)
> at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage triggerMessage, CancellationToken cancellationToken),   at Microsoft.Azure.WebJobs.ServiceBus.MessageProcessor.CompleteProcessingMessageAsync(ServiceBusMessageActions actions, ServiceBusReceivedMessage message, FunctionResult result, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Primitives/MessageProcessor.cs:line 77
> at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.CustomMessagingProvider.CustomMessageProcessor.<>n__1(ServiceBusMessageActions actions, ServiceBusReceivedMessage message, FunctionResult result, CancellationToken cancellationToken)
> at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.CustomMessagingProvider.CustomMessageProcessor.CompleteProcessingMessageAsync(ServiceBusMessageActions actions, ServiceBusReceivedMessage message, FunctionResult result, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusEndToEndTests.cs:line 1782
> at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.ProcessMessageAsync(ProcessMessageEventArgs args) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs:line 291
> at Azure.Messaging.ServiceBus.ServiceBusProcessor.OnProcessMessageAsync(ProcessMessageEventArgs args)
> at Azure.Messaging.ServiceBus.ReceiverManager.OnMessageHandler(EventArgs args)
> at Azure.Messaging.ServiceBus.ReceiverManager.ProcessOneMessage(ServiceBusReceivedMessage triggerMessage, CancellationToken cancellationToken),7d5a9974-52ca-FixtureSetUp-0b62c7bc-2508-41fe-8b3c-30d7f006abb6: User message handler complete: Message: SequenceNumber: 1, Exception: Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: ServiceBusTestJobs.SBQueue2SBQueue
> ---> NUnit.Framework.A
> 
> 
> Stack trace
>    at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.ServiceBusEndToEndInternal[T](IHost host) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusEndToEndTests.cs:line 829
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.CustomMessageProcessorTest() in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusEndToEndTests.cs:line 146
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> --AssertionException
>    at NUnit.Framework.Assert.ReportFailure(String message)
>    at NUnit.Framework.Assert.ReportFailure(ConstraintResult result, String message, Object[] args)
>    at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
>    at NUnit.Framework.Assert.IsEmpty(IEnumerable collection, String message, Object[] args)
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.WebJobsServiceBusTestBase.ServiceBusEndToEndTestService.StopAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/WebJobsServiceBusTestBase.cs:line 327
>    at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
> 1)    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.ServiceBusTestJobs.SBQueue2SBQueue(String body, Int32 deliveryCount, String lockToken, String deadLetterSource, DateTime expiresAtUtc, DateTimeOffset expiresAt, DateTime enqueuedTimeUtc, DateTimeOffset enqueuedTime, String contentType, String replyTo, String to, String subject, String label, String correlationId, String sessionId, String replyToSessionId, IDictionary`2 applicationProperties, IDictionary`2 userProperties, ServiceBusMessageActions messageActions, ServiceBusSender messageSender) in /Users/runner/work/1/s/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/tests/ServiceBusEndToEndTests.cs:line 1024
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.ServiceBusEndToEndTests.ServiceBusTestJobs.SBQueue2SBQueue(String body, Int32 deliveryCount, String lockToken, String deadLetterSource, DateTime expiresAtUtc, DateTimeOffset expiresAt, DateTime enqueuedTimeUtc, DateTimeOffset enqueuedTime, String contentType, String replyTo, String to, String subject, String label, String correlationId, String sessionId, String replyToSessionId, IDictionary`2 applicationProperties, IDictionary`2 userProperties, ServiceBusMessageActions messageActions, ServiceBusSender messageSender)
>    at lambda_method(Closure , ServiceBusTestJobs , Object[] )
>    at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\VoidTaskMethodInvoker.cs:line 20
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
>    at Microsoft.Azure.WebJobs.Host.Executors.VoidTaskMethodInvoker`2.InvokeAsync(TReflected instance, Object[] arguments)
>    at Microsoft.Azure.

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2058291&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Transient issue in the Functions host; closing.
