### ISSUE TITLE
How to set the timeout value of Queue/Topic Client 

### ISSUE THREAD

**Issue by wstest123** [Azure/azure-sdk-for-net#33143]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

When we use the **Microsoft.Azure.ServiceBus，Microsoft.Azure.ServiceBus.Management sdk**, we can set the timeout value of queue or tipic client, attached the sample code:
`_logoutDelQueueClient = new QueueClient(config.ServiceBusConnectionString, config.LogoutDelOmcTokenQueueName); _logoutDelQueueClient.OperationTimeout = TimeSpan.FromSeconds(config.ServiceBusOperationTimeout); _omcUserTopicClient = new TopicClient(config.ServiceBusConnectionString, config.OMCUserInfoTopic); _omcUserTopicClient.OperationTimeout = TimeSpan.FromSeconds(config.ServiceBusOperationTimeout);`

When we use the **Azure.Messaging.ServiceBus sdk**, we can not find the OperationTimeout properties, could you please help advice is there any way to setup the timeout for Queue/Topic Client based on the Azure.Messaging.ServiceBus sdk?
```
var client = azureClientFactory.CreateClient("OauthServiceBus"); 
adminHelper.CreateQueueIfNotExist(config.DelAllTokensQueueName); 
_delAllTokesQueueSender = client.CreateSender(config.DelAllTokensQueueName); adminHelper.CreateTopicIfNotExist(config.OmcTokenTopic); 
_omcTokenTopicSender = client.CreateSender(config.OmcTokenTopic); 
```

**Comment by jsquire** [comment]
Hi @wstest123.  Thank you for reaching out and we regret that you're experiencing difficulties.   The `TryTimeout` in the retry options is the equivalent of the `OperationTimeout` in legacy packages.   The `TryTimeout` is set via the options passed when creating the `ServiceBusClient`.    Doing so is demonstrated in the [Advanced configuration](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample13_AdvancedConfiguration.md#customizing-the-retry-options) sample and would look something like:

```csharp
var client = new ServiceBusClient("<< CONNECTION STRING >>, new ServiceBusClientOptions
{
    RetryOptions = new ServiceBusRetryOptions
    {
        TryTimeout = TimeSpan.FromSeconds(60)  // This is the default value
    }
});
```

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by wstest123** [comment]
@jsquire  Thanks so much for your clarify!  My understanding is that only when I set the MaxRetries values in RetryOptions, will the retry policy triggered. If I only set the TryTimeout value, it will not trigger the retry policy and it is equivalent of the OperationTimeout . Please correct me if I am wrong, thanks so much.

**sample 1:(trigger retry polocy)**
```
var client = new ServiceBusClient(connectionString, new ServiceBusClientOptions
{
    RetryOptions = new ServiceBusRetryOptions
    {
        TryTimeout = TimeSpan.FromSeconds(60),
        MaxRetries = 3,
        Delay = TimeSpan.FromSeconds(.8)
    }
});
```
sample2 not trigger retry policy:
```
var client = new ServiceBusClient(connectionString, new ServiceBusClientOptions
{
    RetryOptions = new ServiceBusRetryOptions
    {
        TryTimeout = TimeSpan.FromSeconds(60),
    }
});
```

**Comment by jsquire** [comment]
@wstest123:  That is correct.   In your second snippet, you're only adjusting the `TryTimeout` and the other retry parameters will keep their default values.

The `TryTimeout` controls the amount of time that an operation (or "try") can take.  This applies to the initial attempt for an operation as well as any retries that take place - each try of an operation is allowed this munch time.

**Comment by wstest123** [comment]
@jsquire Thanks so much for your advice! As my understanding, once we set the TryTimeout for ServiceBusClient, all of the ServiceBusClient and operations would be the same timeout value. If I want to use different timeout value for different QueueClient and TopicClient, how to set this value?
And if we hope to set different timeout for special operations, how to set this value? Thanks in advance!

**Comment by jsquire** [comment]
> If I want to use different timeout value for different QueueClient and TopicClient, how to set this value?

The connection and its configuration are owned by the `ServiceBusClient` instance; any child types spawned from it share that connection.  For your scenario, you would need to create two instances of `ServiceBusClient`. 

> And if we hope to set different timeout for special operations, how to set this value?

For dynamic values that may change per-operation, your best bet would be to pass a cancellation token into the operation itself.   When the token requests cancellation, it signals that the operation should stop if/when it is safe to do so.     For example:

```csharp
// NOTE: 
//    This snippet is for demonstration only; applications should consider the ServiceBusClient
//    a long-lived type and treat it as a singleton for the life of the application.

await using var client = new ServiceBusClient("<< CONNECTION STRING >>");
await using var sender = client.CreateSender(queueName);

using var cancellationSource = new CancellationTokenSource();
cancellationSource.CancelAfter(TimeSpan.FromSeconds(45));

var message = new ServiceBusMessage("Hello world!");
await sender.SendMessageAsync(message, cancellationSource.Token);
```
