### ISSUE TITLE
[Storage] Dependency timestamps not accurate on .NET Framework

### ISSUE THREAD

**Issue by Basvg** [Azure/azure-sdk-for-net#33146]
I have upgraded our Azure storage packages to v12. However I have noticed that with the new version, the reported timestamps of the dependency tracking in Application Insights are not accurate. On our staging server, it shows a huge increase in duration:

![afbeelding](https://user-images.githubusercontent.com/2334483/208925073-33e1fc25-d40a-44be-8dcf-49af70c7c944.png)

This is not accurate however, because in reality they don't take that long. The duration of the operation itself is much shorter, as can be seen here:

![afbeelding](https://user-images.githubusercontent.com/2334483/208931321-62856fad-4df4-4f84-8f4f-b7085859b720.png)

I have set up a test API call like this:

    public async Task<long> Test()
    {
        var storageClient = new BlobServiceClient("connection string");
        var blobClient = storageClient.GetBlobContainerClient("test").GetBlobClient("test");

        var watch = new System.Diagnostics.Stopwatch();
        watch.Start();
        var test = await blobClient.ExistsAsync();
        watch.Stop();

        return watch.ElapsedMilliseconds;
    }

The duration as shown in Application Insights is often much longer than the duration as measured by the stopwatch.

I have done some more testing by setting up a completely new project with just storage and application insights packages, and uploaded this to a new Azure App service.

Although the reported durations are not as high as in our actual application, the timestamps are still not accurate:

![afbeelding](https://user-images.githubusercontent.com/2334483/208927363-282424ab-9bb1-4dce-8cfd-107d5a726575.png)

This only happens on .NET Framework 4.8, not on .NET 7. All packages were updated to their latest versions.

I have tried downgrading to older versions, and the problem also occurs in Azure.Storage.Blobs 12.0.0 using Azure.Core 1.0.0.

It seems like it happens with the Tables package as well, but I have not done any specific testing for that one.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

@xgithubtriage Could you please look into this once you get a chance ?
