### ISSUE TITLE
When is Azure.Identity 1.9.0-beta.2 being released?

### ISSUE THREAD

**Issue by Matthewsre** [Azure/azure-sdk-for-net#33154]
### Library name and version

Azure.Identity 1.9.0-beta.2

### Query/Question

I've been stuck on Azure Identity 1.6.0 for a while since there is a change in 1.7.0 that broke how MSI retrieval and how the fallback logic works. My scenario is a Developer environment running Visual Studio on an AVD Workstation.

I believe that issue is finally fixed in the 1.9.0-beta.2, but it has been sitting in there since early November:

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#190-beta2-unreleased

Would really appreciate if beta2 could be released to nuget so I could validate this resolves the issue or file an issue. When should I expect for this to be released?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Matthewsre** [comment]
@jsquire , still looks unreleased, any updates?

**Comment by scottaddie** [comment]
@Matthewsre Apologies for the delay. You can expect v1.9.0-beta.2 to ship this week.
