### ISSUE TITLE
Azure.Messaging.ServiceBus migration guide does not mention breaking changes to correlation

### ISSUE THREAD

**Issue by simonness** [Azure/azure-sdk-for-net#33159]
The [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md) for migrating to `Azure.Messaging.ServiceBus` from `Microsoft.Azure.ServiceBus`, does not mention some important breaking changes to correlation, should this be mentioned and is there general advice how best to maintain this functionality?

In `Microsoft.Azure.ServiceBus` a `Correlation-Context` header flowed between sender and receiver, a list of key value pairs representing activity baggage (see [Microsoft.Azure.ServiceBus/src/Extensions/MessageDiagnosticsExtensions.cs](https://github.com/Azure/azure-sdk-for-net/blob/4162f6fa2445b2127468b9cfd080f01c9da88eba/sdk/servicebus/Microsoft.Azure.ServiceBus/src/Extensions/MessageDiagnosticsExtensions.cs)). This automatic behaviour was incredibly useful in distributed architectures that typically use Azure Service Bus as telemetry in the Application Insights for the message receiver would automatically have Custom Properties that give context to the message (any activity baggage items added upstream by the sender).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please be aware that responses will be delayed due to the US holidays.

**Comment by JoshLove-msft** [comment]
Hi @simonness,
Thanks for raising this issue. In the new library, our plan is to adhere to the Open Telemetry semantics. As such, there are some changes to how telemetry works from the legacy library. We will update our migration guide to include this information.
