### ISSUE TITLE
[FEATURE REQ] Ability to target different tenants with ArmClient

### ISSUE THREAD

**Issue by amsoedal** [Azure/azure-sdk-for-net#33163]
### Library name

Azure.ResourceManager 1.3.2

### Please describe the feature.

Our team is using the ArmClient to build a resource provider. We need the ability to target different tenants within ArmClient. Right now I can see ArmClient has an internal TenantResource, but it's impossible to change it. This is a key scenario us and it would help a lot if we could target customer tenants from our RP.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
Current SDK design is for single tenant, you can use multiple ArmClient to target different tenants

**Comment by amsoedal** [comment]
@xboxeer I don't see the option to set the tenant when I construct a new ArmClient. How does the "_tenant" value get set?

**Comment by xboxeer** [comment]
@amsoedal  you should set tenant on the credential object that you passed to your armclient
```csharp
var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions() { TenantId = "" });
               var armclient = new ArmClient(credential);
```

every time you want switch to a new tenant, you should have a new armclient with new credential 
This is by design

**Comment by stevebelton** [comment]
It's how we do it also Michelle, connecting with clientId and clientSecret (as you know for a "cheat" way around testing provisioning using our RP without a proper roledefinition) :  

                var tc = new ClientSecretCredential(tenantId, clientId, clientSecret);
                var armClient = new ArmClient(tc);

Then pass armClient into a helper method for deploying.

**Comment by amsoedal** [comment]
Thank you for the help @xboxeer and @stevebelton! Closing this issue as that makes sense!
