### ISSUE TITLE
[Search] Behavior_Split failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33172]
Search nightly test runs are failing with:

> Error message
> Expected: 10
> But was:  11
> 
> 
> Stack trace
>    at Azure.Search.Documents.Tests.BatchingTests.Behavior_Split() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 1066
>    at Azure.Search.Documents.Tests.BatchingTests.Behavior_Split() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 1095
>    at Azure.Search.Documents.Tests.BatchingTests.Behavior_Split() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 1095
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 
> 1)    at Azure.Search.Documents.Tests.BatchingTests.Behavior_Split() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 1066

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2070666&view=results

@jsquire for notification.

**Comment by ShivangiReja** [comment]
This test failed only one time in one os environment. All the previous and future runs are passing for this test case.

I reran the test and it passed: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2070666&view=results

Please file an issue if you see a failure pattern or a same test fails in 2 or more continuous runs. Thanks!
