### ISSUE TITLE
I think the code samples will be very helpful

### ISSUE THREAD

**Issue by kormanm** [Azure/azure-sdk-for-net#33195]
Nothing too critical, but this page is not useful without sample code

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 24234c5d-638c-4374-e7a5-af08f8d9202a
* Version Independent ID: e7982719-db65-e91a-6bc8-c027bd74ccfb
* Content: [StorageSharedKeyCredential Class (Azure.Storage) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.storagesharedkeycredential?view=azure-dotnet)
* Content Source: [xml/Azure.Storage/StorageSharedKeyCredential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage/StorageSharedKeyCredential.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@kormanm We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@kormanm Thanks for your feedback.  You can find the sample to use StorageSharedKeyCredential over [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/samples/Sample02_Auth.cs).
