### ISSUE TITLE
Why only 1 answer returns from Custom Question Answering project through Orchestration

### ISSUE THREAD

**Issue by DDavaa** [Azure/azure-sdk-for-net#33197]
### Library name and version

Azure.AI.Language.Conversations 1.0.0

### Query/Question

I have Orchestration workflow that contains "Conversational language understanding" and "Custom question answering" projects. After I ask question through the Orchestration, if my top intent is selected from "Custom question answering", I can see there is property called "Answers" which supposed to be list of answers, however, it always returns only 1 answer versus I can see multiple intents from "Conversational language understanding" if my topIntent is selected with that project. 
How can I get multiple answers from the "Custom question answering" project through Orchestration? Or will it be available sometime soon?

I am using Azure.AI.Language.Conversations 1.0.0 and calling AnalyzeConversation from ConversationAnalysisClient.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please expect delayed responses due to the US holidays.

**Comment by dasvictor** [comment]
Please take a look at: https://learn.microsoft.com/en-us/rest/api/language/2022-05-01/conversation-analysis-runtime/analyze-conversation?tabs=HTTP

You can add the "targetProjectParameters" and specify the "top" value as mentioned below (please replace the query and intent name) to get more CQA results.

```
var data = new
{
    analysisInput = new
    {
        conversationItem = new
        {
            text = "<your query>",
            id = "1",
            participantId = "1",
        }
    },
    parameters = new
    {
        projectName,
        deploymentName,

        stringIndexType = "Utf16CodeUnit",
        targetProjectParameters = new {
            <intent_name>= new {
                targetProjectKind = "QuestionAnswering",
                callingOptions = new {
                  top = 3
                }
            }
        }
    },
    kind = "Conversation",
};
```

**Comment by DDavaa** [comment]
Thank you for the information @dasvictor !
I tried the data filter before but the filter was not working specially with my provided info. After seeing your response, I actually double checked again and the reason was my intent/project name for the Custom Question Answering had dashes. 

![image](https://user-images.githubusercontent.com/32198944/212419497-0b7bfddf-2745-43ce-bcec-f1ff5ea44600.png)

So I recreated my project without any dashes and that worked as expected!

![image](https://user-images.githubusercontent.com/32198944/212419733-eaad248e-4fcd-4eef-a1e7-d69d86b95cbb.png)

Just curiosity, do you know why the data filter wouldn't accept the dash if the language studio lets us create the name with other symbols?


Thanks,
Davaa
