### ISSUE TITLE
TableQuery.OrderBy(String)

### ISSUE THREAD

**Issue by sfjuocekr** [Azure/azure-sdk-for-net#33211]
[Enter feedback here]
I'm trying to do a sort based on a column like this, but I can not figure out how to do this and the documentation on this function is non-existent at best. The docs do state "Only applied to Cosmos Table Endpoint", but I have tried with and without. The result is always the same, either the OrderBy method doesn't do anything or I don't understand what the string part is supposed to contain.

I use myquery.OrderBy("score");

I have a table with five values under score: 3, 5, 2, 1, 4

When I order by score I expect a table that has its elements sorted by score, but nothing actually changes.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a20dc69d-0406-e78f-cefc-9a32a924671d
* Version Independent ID: 723b184c-16da-819b-d827-a7163796d289
* Content: [TableQuery.OrderBy(String) Method (Microsoft.Azure.Cosmos.Table) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tablequery.orderby?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos.Table/TableQuery.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos.Table/TableQuery.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by sfjuocekr** [comment]
Oke for those struggling with the same problem as I did, you need to add (which I had forgotten): using System.Linq;

And then you need to call OrderBy or OrderByDescending on your ExecuteQuery passing a delegate function like this: entity => entity.yourproperty

It would also be nice if the pages for ExecuteQuery and TableQuery.GenerateFilterCondition would contain examples like they do for DataContext.ExecuteQuery.

I think there should be more examples on how to use these operations, at least ChatGPT was able to help me out :D

**Comment by sfjuocekr** [comment]
Funny enough ChatGPT came up with this solution:

```
List<T> results = (from e in _cloudTable.CreateQuery<T>().AsEnumerable()
                        orderby e.propertyName
                        select e).ToList<T>();
```

Where it notes:

```
Note that this approach will execute the entire query in memory, so it may not be suitable for very large tables or for queries that return a large number of results.
```

But for my approach it notes:

```
This approach has the advantage of executing the query directly on the server, which can be more efficient than retrieving all the results in memory and sorting them using LINQ. It also allows you to use paging to retrieve the results in smaller chunks, if needed.
```

And then spits out code to implement: await _cloudTable.ExecuteQuerySegmentedAsync(_query, continuationToken);

Call me impressed, I bashed my head for hours on this!

**Comment by navba-MSFT** [comment]
@sfjuocekr Thanks for reaching out to us and reporting this issue. Could you please let me know if you are still looking for some assistance on this ?

**Comment by navba-MSFT** [comment]
@sfjuocekr I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.
