### ISSUE TITLE
[ContainerRegistry] CanDeleteRegistryArtifact failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33248]
ContainerRegistry nightly test runs are failing with:
 
> Error message
> Expected: <Azure.RequestFailedException>
> But was:  null
> 
> 
> Stack trace
>    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.CanDeleteRegistryArtifact() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\tests\RegistryArtifactLiveTests.cs:line 156
>    at Azure.Containers.ContainerRegistry.Tests.RegistryArtifactLiveTests.CanDeleteRegistryArtifact() in D:\a\_work\1\s\sdk\containerregistry\Azure.Containers.ContainerRegistry\tests\RegistryArtifactLiveTests.cs:line 164
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2082983&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Issue #32948 is tracking test stability all-up for Container Registry.  There is no need to open issues for individual tests.   Closing.
