### ISSUE TITLE
Does ShardMap support Microsoft.Data.SqlClient package ?[QUERY]

### ISSUE THREAD

**Issue by aditi9212** [Azure/azure-sdk-for-net#33247]
### Library name and version

Microsoft.Data.SqlClient

### Query/Question

I have an .net core 6.0 entityframework application and want to connect to SQL Database through Azure Active Directory from the application. The code to connect to SQL Database through Azure Active Directory uses Microsoft.Data.SqlClient as the package. We also have usage of ShardMap in the same DbContext where we are connecting to the database. The ShardMap does not support Microsoft.Data.SqlClient and needs System.Data.SqlClient as the package. Does, ShardMap support Microsoft.Data.SqlClient package ?

Below is piece of code from the DbContext where I am getting the error:

```
SqlConnection conn = null; //uses Microsoft.Data.SqlClient as the package
  try{   
   var shardMap = GetShardMapManager(Constants.Settings.ShardMapName, configuration);
   var connStringBuilder = new SqlConnectionStringBuilder
   {
      UserID = userId,
      Password = password,
      ApplicationName = "ABC"
   };
        
  conn = shardMap.OpenConnectionForKey(shardingKey, connStringBuilder.ConnectionString, ConnectionOptions.Validate);\
         
   //Gives error at the above line: "Cannot convert source type 'System.Data.SqlClient.SqlConnection' to target type 'Microsoft.Data.SqlClient.SqlConnection'"
   /* If the above SqlConnection uses System.Data.SqlClient.SqlConnection as the package, the error does not come up. But, in that case, we cannot use Authentication in the GetDatabaseConnection method.
   */
   }
  catch (Exception e) 
  {
  ......
  }
 
 private static ShardMap GetShardMapManager(string shardMapName, IConfiguration configuration)
  {
      var dbConnectionString = GetDatabaseConnectionString(configuration);
      var shardMapManager = ShardMapManagerFactory.GetSqlShardMapManager(dbConnectionString, ShardMapManagerLoadPolicy.Lazy);
      var shardMap = shardMapManager.GetListShardMap<int>(shardMapName);
      return shardMap;
  }
```

//The method below needs Microsoft.Data.SqlClient to use Authentication=Active Directory Service Principal;

```
public static string GetDatabaseConnection(IConfiguration config)
  {
   return
                  $"Server=tcp:{config["SERVERNAME"]},1433; Authentication=Active Directory Service Principal; " +
                  $"Encrypt=True; Database={config[DATABASENAME]}; User Id = {clientId}; Password = {password} ";
        
   var connection = new SqlConnection(ConnectionString);
      connection.Open();
  }
```

### Environment

EF Core 6.0
IDE: JetBrains Rider 2022.3.1

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.SqlDatabase.ElasticScale.Client` package is maintained as [#225](https://github.com/Azure/elastic-db-tools/issues/225).
