### ISSUE TITLE
[ServiceBus] DefaultFilter failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33250]
ServiceBus nightly test runs are failing with:

> Error message
> Expected string length 4 but was 3. Strings differ at index 0.
> Expected: "blue"
> But was:  "red"
> -----------^
> 
> 
> Stack trace
>    at Azure.Messaging.ServiceBus.Tests.RuleManager.RuleManagerLiveTests.ReceiveAndAssertMessages(ServiceBusClient client, String topicName, String subscriptionName, IEnumerable`1 expectedOrders) in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/RuleManager/RuleManagerLiveTests.cs:line 638
>    at Azure.Messaging.ServiceBus.Tests.RuleManager.RuleManagerLiveTests.DefaultFilter() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/RuleManager/RuleManagerLiveTests.cs:line 145
>    at Azure.Messaging.ServiceBus.Tests.RuleManager.RuleManagerLiveTests.DefaultFilter() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/RuleManager/RuleManagerLiveTests.cs:line 145
>    at Azure.Messaging.ServiceBus.Tests.RuleManager.RuleManagerLiveTests.DefaultFilter() in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/RuleManager/RuleManagerLiveTests.cs:line 150
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
> 
> 1)    at Azure.Messaging.ServiceBus.Tests.RuleManager.RuleManagerLiveTests.ReceiveAndAssertMessages(ServiceBusClient client, String topicName, String subscriptionName, IEnumerable`1 expectedOrders) in /mnt/vss/_work/1/s/sdk/servicebus/Azure.Messaging.ServiceBus/tests/RuleManager/RuleManagerLiveTests.cs:line 638

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2082426&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
No longer failing consistently
