### ISSUE TITLE
[Translation] GetTranslationStatusesFilterByStatusTest failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33251]
Translation nightly test runs are failing with:

> Error message
> System.AggregateException : One or more errors occurred.
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOperationException : Cancellation not propagated to all documents
> ----> System.InvalidOper
> 
> 
> Stack trace
>    at Azure.Core.TestFramework.TestRetryHelper.<RetryAsync>d__2`1.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\TestRetryHelper.cs:line 48
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Azure.AI.Translation.Document.Tests.DocumentTranslationClientLiveTests.<CreateTranslationJobsAsync>d__12.MoveNext() in D:\a\_work\1\s\sdk\translation\Azure.AI.Translation.Document\tests\GetAllTranslationsFilterTests.cs:line 79
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Azure.AI.Translation.Document.Tests.DocumentTranslationClientLiveTests.<GetTranslationStatusesFilterByStatusTest>d__13.MoveNext() in D:\a\_work\1\s\sdk\translation\Azure.AI.Translation.Document\tests\GetAllTranslationsFilterTests.cs:line 92
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> --InvalidOperationException
>    at Azure.AI.Translation.Document.Tests.DocumentTranslationClientLiveTests.<>c__DisplayClass11_1.<<WaitForJobCancellation>b__0>d.MoveNext() in D:\a\_work\1\s\sdk\translation\Azure.AI.Translation.Document\tests\GetAllTranslationsFilterTests.cs:line 42
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.Core.TestFramework.TestRetryHelper.<RetryAsync>d__2`1.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\TestRetryHelper.cs:line 37
> --InvalidOperationException
>    at Azure.AI.Translation.Document.Tests.DocumentTranslationClientLiveTests.<>c__DisplayClass11_1.<<WaitForJobCancellation>b__0>d.MoveNext() in D:\a\_work\1\s\sdk\translation\Azure.AI.Translation.Document\tests\GetAllTranslationsFilterTests.cs:line 42
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.Core.TestFramework.TestRetryHelper.<RetryAsync>d__2`1.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\TestRetryHelper.cs:line 37
> --InvalidOperationException
>    at Azure.AI.Translation.Document.Tests.DocumentTranslationClientLiveTes

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2080984&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Translation is owned by the service team and already has multiple test quality issues open; there's no value in tracking each individual test failure.   Closing.
