### ISSUE TITLE
[QUERY] Azure Search Index Alias

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#33260]
### Library name and version

Azure.Search.Documents 11.3.0

### Query/Question

Recently I came across this article which mentioned that we can create an Index Alias and use it to query documents. Alias is very helpful to avoid downtime when we have to change Index definition and to do that we need to drop and recreate index. 
https://learn.microsoft.com/en-us/azure/search/search-how-to-alias?tabs=rest

However, this Index Alias feature is only available in Public Preview and can only be used by REST API using api-version 2021-04-30-preview.

We are using Azure.Search.Documents NuGet Package and there is no option to use this api-version in it and hence to use Index Alias for our document operations. So it would be great if there was an option in this NuGet package/SDK to use this api-version while connecting to a Search Service Client.

Additionally, I also wanted to know if we can use this feature of Index Alias in our sites like any other feature or not, what SLAs or restrictions are and so on.

**Comment by jsquire** [comment]
Hi @ssghoda.  Thank you for reaching out and we regret that you're experiencing difficulties.   REST API preview versions can only be used with beta versions of Azure SDK packages.  In this case, REST API version 2021-04-30-preview is supported by `Azure.Search.Documents` [11.5.0-beta.2](https://www.nuget.org/packages/Azure.Search.Documents/11.5.0-beta.2).

With respect to your question around SLAs and restrictions, there are none on the Azure SDK package - though we discourage using beta packages in a production environment.  We cannot answer this question with respect to the REST API itself.  Your best path for that information would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for the Search service team.

I'm going to mark this as addressed; please feel free to unresolve if you'd like to continue the discussion.

**Comment by ssghoda** [comment]
Thank you @jsquire for such a nice and quick response. I understand and agree with your discouragement to use beta package in a production environment. Well, then I will just have to wait for this preview feature to become a permanent one. Because this feature will help a lot of people like me who have to drop and recreate an index to change its definition and have to worry about downtime.
