### ISSUE TITLE
[Bug] New-TestResources.ps1 Scripts fails when $BaseName > 24 characters

### ISSUE THREAD

**Issue by NiveditJain** [Azure/azure-sdk-for-net#33261]
While working with Azure Loadtestservice SDK, script New-TestResource.ps1 was failing as $BaseName for me was, "niveditjainloadtestservice" which is greater than 24 characters. It was showing this behaviour because Azure KeyVault Resource should have a name between 3 and 24 Characters as mentioned [here](https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.KeyVault.Name/).

Screenshot of the error:
![too long issue SS](https://user-images.githubusercontent.com/40313233/210198333-e59450c5-9a3d-4c90-8b9f-eb1d1827f40b.png)

**Comment by benbp** [comment]
Fixed by https://github.com/Azure/azure-sdk-tools/pull/5242
