### ISSUE TITLE
Token for Storage Account- Managed Identity

### ISSUE THREAD

**Issue by pradeepkumarms** [Azure/azure-sdk-for-net#33271]
### Library name and version

Azure.Identity Version=1.5.0.0

### Query/Question

We are looking for an option to a get new token for each request.

Currently, if a token is issued and there are any further requests to get token till the time first token is valid, we are getting the same token that was issued earlier.

```
 var authResult = new DefaultAzureCredential(true).GetToken(new TokenRequestContext(
            new[] { "https://storage.azure.com/.default" })); 

```
We are using below 

Azure.Identity Version=1.5.0.0
Microsoft.Azure.Storage.Common, Version=11.2.3.0

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.  Please expect delayed responses due to the US holidays.
