### ISSUE TITLE
Migration from Microsoft.Azure.Cosmos.Table and IQueryable

### ISSUE THREAD

**Issue by keshari** [Azure/azure-sdk-for-net#33273]
Hi Team,

We have a repository code written where Something like 

TableEntityResult  CreateQuery(Iqueryable query) is there abstracting underlying storage. The current implementation, uses query to build various clauses with where , Take,Top  and finally   query.AsTableQuery() and then execute it.

As TableQuery is deprecated, what is the way forward?
I see the same issue being discussed https://github.com/Azure/azure-sdk-for-net/issues/28389 . But the solution unfortunately https://gist.github.com/xDDDx/368ffdb0b90016bc346970c5b42d7405  does not solve it for us.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.   Please expect delayed responses due to the US holidays.

**Comment by christothes** [comment]
Hi @keshari - unfortunately, we don't have any samples for this. That said, Take and Top are both not directly supported natively by the service API, so other than for migration purposes, I wouldn't recommend implementing those in general.
