### ISSUE TITLE
[QUERY] [MySQL] Not able to set up Authentication when using MySql SDK 

### ISSUE THREAD

**Issue by wimeling** [Azure/azure-sdk-for-net#33292]
### Library name and version

Azure.ResourceManager.MySql 1.0.0

### Query/Question

When creating a MySql Flexible Server via de SDK in c#. I should be able to set the following settings: 

<img width="559" alt="image" src="https://user-images.githubusercontent.com/81306726/210524121-866ded43-930a-4e4e-8190-6bc0ce1b350d.png">

I am using the CreateOrUpdateAsync method to create a Mysql Flexible server, As you can see in the code I add a user assigned managed identity when creating the database. But the problem is that when creating the database there is no option to set the option _Assign access to_ and this is also not set the right way when creating the database with user assigned managed identity in the call.

Another issue is that there does not seem to be an option to set the _Azure Active Directory Administrators (Azure AD Admins)_  via the code. I have looked at the azure cli option for create a MySql Flexible server and there is the option to do `az mysql flexible-server ad-admin create` But I cannot find any option when using the SDK 
 
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/81306726/210525123-5a576ac1-0552-4249-b585-3ce814cb16d5.png">

Can you assist me in making sure the settings for Authentication can be set through the c# sdk 

### Environment

.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

IDE: Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview Version 17.5.0 Preview 1.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
Hi @wimeling , I'm not seeing this page in Azure portal
![image](https://user-images.githubusercontent.com/5089150/210948005-6c4a6b9a-fa76-4aae-b47d-1869b4b15f74.png)
there is only user assigned identity setting in portal when creating my sql flexible server
![image](https://user-images.githubusercontent.com/5089150/210948289-e9735087-c027-4d1b-8a45-021d03d13799.png)

may I know in which page you are seeing the  authentication?

**Comment by wimeling** [comment]
The page I am talking about can be found here:

<img width="208" alt="image" src="https://user-images.githubusercontent.com/81306726/210954744-6a07f068-5759-4298-a1de-9f1bbab8d80c.png">

And I would like to know how to enable the settings on this page via the SDK in C# code.

**Comment by xboxeer** [comment]
The assign access to is a UI convenience option in portal, it does not have a corresponding property in SDK or REST API level. You can validate it by assigning a user assigned managed identity in the authentication page, retrieve that mysql resource in SDK and check the Data.Identity property

**Comment by wimeling** [comment]
Hi xboxeer,

So if I understand correctly for this part of the UI, there is no way to programmatically adjust this setting to _MySql and Azure Active Directory authentication_? Is this something I can expect in the future? 

<img width="553" alt="image" src="https://user-images.githubusercontent.com/81306726/211487528-a6e88f80-4fdd-4297-b94d-58551babfd27.png">

For this part of the UI I have found the code to update the setting, I can use the Identity property in the 

<img width="577" alt="image" src="https://user-images.githubusercontent.com/81306726/211493622-02bb2c09-48ed-4042-844f-6010dfdceb65.png">

That leaves me with the last part of my question and that is how to set _Azure Active Directory Administrators_ part. Like I told you in the original question it seems that there is a `az mysql flexible-server ad-admin create` option in the Azure CLI which uses the Azure ResourceManager api if I am correct. So my question still is how can I set this part through code via de SDK? 

<img width="547" alt="image" src="https://user-images.githubusercontent.com/81306726/211494067-0fcacbe8-d36a-4349-895d-04861a955456.png">

**Comment by wimeling** [comment]
Hello, can I maybe get some more assistance on this issue?

**Comment by wimeling** [comment]
I have checked the azure cli command `az mysql flexible-server ad-admin create` and this creates the following call: PUT /subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.DBforMySQL/flexibleServers/{server}/administrators/ActiveDirectory?api-version=2021-12-01-preview So the call seems to be available in the api. Can you tell me when this will be available in the sdk for the MySql Flexible server?

**Comment by Yao725** [comment]
Hi @wimeling, sorry for the delay of response and thanks for your finding. Currently the API version of the `FlexibleServer` in our SDK is `2021-05-01` and the feature that you are asking is introduced in [2021-12-01-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/mysql/resource-manager/Microsoft.DBforMySQL/preview/2021-12-01-preview/AzureADAdministrator.json#L37), which means we need an update in SDK side. I'm working on the API version bump and I assume the release should be early Feb.

**Comment by HarveyLink** [comment]
Hi @wimeling , the feature for MySQL SDK has been released, please check the leatest version.
