### ISSUE TITLE
[QUERY] Documenting SymmetricSecurityKey size requirements

### ISSUE THREAD

**Issue by vcsjones** [Azure/azure-sdk-for-net#33300]
### Library name and version

Microsoft.IdentityModel.Tokens 6.25.1

### Query/Question

A customer for `dotnet/runtime` [reported](https://github.com/dotnet/runtime/issues/80180) an issue with `HMACSHA256` that turned out to be a non-issue, and just some uncertainty around the required key size for `SymmetricSecurityKey`. They were attempting to use a 96-bit key, where instead, there is a 128-bit minimum.

As far as I can tell, these key size requirements for `SymmetricSecurityKey` are not documented. Is this intentional? If not, do we think it makes sense to document them?

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.IdentityModel.Tokens` library is maintained as [#1995](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1995).
