### ISSUE TITLE
Ability to restore a database - is this available?

### ISSUE THREAD

**Issue by glaidler** [Azure/azure-sdk-for-net#3332]
ISqlDatabase has a list of IRestorePoint, but I can't find a way to restore a database.  Is this currently supported?

**Comment by hovsepm** [comment]
@glaidler are you using Fluent or auto-generated sdk? Fluent does not support it.

**Comment by glaidler** [comment]
Fluent.  Would be great if it did! :)

**Comment by hovsepm** [comment]
Restore point in time feature is not yet in the Fluent Azure Management Libraries. Recently, this feature arrived in SQL Database Swagger and is in the library backlog. We are planning to work on it in the in late Summer.

**Comment by hovsepm** [comment]
@glaidler as a workaround you can use AutoGenerated SQL library for that part https://www.nuget.org/packages/Microsoft.Azure.Management.Sql
