### ISSUE TITLE
[QUERY] Which of the Nuget Packages for Azure.ResourceManager.*** is used for Azure Functions?

### ISSUE THREAD

**Issue by pedrohugorm** [Azure/azure-sdk-for-net#33323]
### Library name and version

Azure.ResourceManager 1.3.2

### Query/Question

I'm trying to get more information about Azure Functions on my Azure Environment, but I can only use GenericResource.
Is there a nuget package to include for Function Apps?

I'm trying to obtain the list of functions available in a given function app.

### Environment

.NET6
Azure Cloud

**Comment by pedrohugorm** [comment]
> [ArthurMa1978](/ArthurMa1978)

Indeed. But there are no methods to find the function list inside a function app on AppService AFAIK. Or are there?

**Comment by Yao725** [comment]
Hi @pedrohugorm, this [method](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/websites/Azure.ResourceManager.AppService/src/Generated/SiteFunctionCollection.cs#L187) will list the functions for a web site or a deployment slot. Please let me know if it could help.

**Comment by pedrohugorm** [comment]
> Hi @pedrohugorm, this [method](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/websites/Azure.ResourceManager.AppService/src/Generated/SiteFunctionCollection.cs#L187) will list the functions for a web site or a deployment slot. Please let me know if it could help.

Got it. Thanks!

**Comment by Yao725** [comment]
Thanks for your feedback. If you have any other feedback to our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF).
