### ISSUE TITLE
Update Microsoft.Azure.KeyVault to support .NET Standard 2.0

### ISSUE THREAD

**Issue by natemcmaster** [Azure/azure-sdk-for-net#3333]
Currently, there are some APIs in Microsoft.Azure.KeyVault only available when targeting .NET Framework, for instance Microsoft.Rest.Azure.Authentication.ClientAssertionCertificate. With the thousands of new APIs available in .NET Standard 2.0 (compared to netstanard1.5), this restriction may not be necessary anymore.

FYI - upstream, we've converted Microsoft.Extensions.Configuration.AzureKeyValue to .NET Standard 2.0. This is the only API missing from the .NET Standard build, which means we also have to cross-compile for .NET Framework.

**Comment by shahabhijeet** [comment]
@natemcmaster we have another [issue ](https://github.com/Azure/azure-sdk-for-net/issues/3438)tracking this move.
We need to plan this and will keep you updated.

**Comment by natemcmaster** [comment]
Ping. Any updates to your plans?

**Comment by komaflash** [comment]
Ping. Any updates to your plans?

**Comment by garfbradaz** [comment]
Any news?

**Comment by adrianhall** [comment]
The latest SDK is compatible with .NET Standard 2.0 - see https://aka.ms/azure-sdk-preview2-net
