### ISSUE TITLE
[FEATURE REQ] Azure.ResourceManager.ServiceBus : Manage minimum TLS version with SDK

### ISSUE THREAD

**Issue by BastienPerdriau** [Azure/azure-sdk-for-net#33333]
### Library name

Azure.ResourceManager.ServiceBus

### Please describe the feature.

Hi,

When creating a service bus with the newer SDK, we have to fill a ServiceBusNamespaceData object.
However, this class doesn't allow us to manage Properties for the namespace, including the minimum TLS version.

For reference with CLI, PowerShell module and ARM template :
https://learn.microsoft.com/en-us/azure/service-bus-messaging/transport-layer-security-configure-minimum-version

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @BastienPerdriau, thanks for reaching out to us, currently the API version of Azure.ResourceManager.ServiceBus is `2021-11-01` and the setting of minimum TLS version was introduced from `2022-10-01-preview`. I will upgrade the API version later.

**Comment by Yao725** [comment]
Hi @BastienPerdriau, we have released a new beta version for [Azure.ResourceManager.ServiceBus](https://www.nuget.org/packages/Azure.ResourceManager.ServiceBus/1.1.0-beta.1), now you could manage the TLS version in SDK, please have a try, thanks!

By the way, if you have any other feedback to our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)

**Comment by BastienPerdriau** [comment]
Hi @Yao725 , it seems ok to me, I ran some tests with it.

Looking forward to have a stable version of this, it's better for us in our internal version management.

**Comment by Yao725** [comment]
Glad to know it works. And we will release a stable version once the latest API version becomes stable.
