### ISSUE TITLE
[QUERY] Azure Search Service Distinct keyword

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#33342]
### Library name and version

Azure.Search.Documents 11.3.0

### Query/Question

Is there a way to get distinct results in results of document operations of a Azure Search Service? This question is for multiple APIs such as Search/SearchAsync, Suggest/SuggestAsync.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Hi @ssghoda, could you give an example of the distinct results you're expecting from the document operations?

**Comment by ssghoda** [comment]
Hi @ShivangiReja, I mean the way we have DISTINCT keyword in T-SQL which returns distinct values in result set, I was wondering if there was something similar for Azure Search to select distinct documents/subdocuments in response.

For example, think of an Index of all hotels across USA and each Hotel document having a field name "City". And if you wanted to select distinct City values across whole index or with some filters/search terms and so on. Let's say, for some filters/search terms there are 5 hotels in my Index belonging to "Washington DC" but I want "Washington DC" to appear only once in API response.

Currently, I am getting all such select responses from Azure Search and doing this distinct in-memory but I was wondering if this was available in Azure Search itself.

**Comment by ShivangiReja** [comment]
@ssghoda unfortunately Azure search APIs do not support operators like distinct or group-by and [this](https://stackoverflow.com/questions/57159447/azure-search-group-by-or-distinct-in-odata-context-query#:~:text=Azure%20Search%20does%20not%20support%20operators%20like%20distinct,resource%20instead%20of%20a%20revision%20of%20a%20resource.) still remains true at this point.
