### ISSUE TITLE
How to created SSL binding for a webapp with Azure.ResourceManager library

### ISSUE THREAD

**Issue by nguyenvuduc** [Azure/azure-sdk-for-net#33348]
I use this piece of code to define ssl binding for my webapp with `Microsoft.Azure.Management.Fluent`
```
await webApp.Update().DefineSslBinding()
                .ForHostname(request.Fqdn)
                .WithPfxByteArrayToUpload(File.ReadAllBytes(pkcs12FilePath, "mypassword")
                .WithSniBasedSsl()
                .Attach()
                .ApplyAsync();
```

However, `Microsoft.Azure.Management.Fluent` is deprecated with this new library.
I couldn't find any equivalent methods in `Azure.ResourceManager.AppService`. How can I do it with this library?

**Comment by m-redding** [comment]
Thank you for your feedback. Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Thanks for reaching out to us, will dig into this issue.

**Comment by Yao725** [comment]
You can call [this method](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/websites/Azure.ResourceManager.AppService/src/Generated/WebSiteResource.cs#L1555) to update the existing web app and manage the SSL binding by specifying [HostNameSslStates](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/websites/Azure.ResourceManager.AppService/src/Generated/Models/SitePatchInfo.cs#L162).

By the way, if you want to create certificate, you can call [AppCertificateCollection.CreateOrUpdateAsync](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/websites/Azure.ResourceManager.AppService/src/Generated/AppCertificateCollection.cs#L75).
