### ISSUE TITLE
[QUERY] Azure Cosmos Db Distinct values across all pages

### ISSUE THREAD

**Issue by ssghoda** [Azure/azure-sdk-for-net#33341]
### Library name and version

Microsoft.Azure.Cosmos 3.30.0

### Query/Question

Is there a way to get distinct values for a field/subdocument in a partition across all pages? I have been using DISTINCT keyword in our queries but since the documents volume is high in our Cosmos Db Container, we get same values more than once. Any help/pointers would be very helpful.

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` package is maintained as [#3634](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3634).
