### ISSUE TITLE
[BUG] Deserializing ManagedServiceIdentity in GetGenericResourcesAsync

### ISSUE THREAD

**Issue by int292** [Azure/azure-sdk-for-net#33388]
### Library name and version

Azure.ResourceManager v1.3.2

### Describe the bug

Calling the function GetGenericResourcesAsync on Subscription,
the sdk deserializing ManagedServiceIdentity object and throws FormatException

When doing the call "await subscription.GetGenericResourcesAsync()" an exception is throwing with 

*Message*:     

System.Text.Json.JsonException : The JSON value could not be converted to Azure.ResourceManager.Models.ManagedServiceIdentity. Path: $ | LineNumber: 0 | BytePositionInLine: 46

*Exception type*:	

System.FormatException	

*Failed method*:	

Azure.ResourceManager.Models.ManagedServiceIdentity.DeserializeManagedServiceIdentity

This happen as of now only in Microsoft.DevTestLab/labs generic resource with api-version 2018-10-15-preview

In the api-version 2018-09-15 of Microsoft.DevTestLab/labs the property identity is not returned at all.

### Expected behavior

The call "await subscription.GetGenericResourcesAsync()" is not throwing FormatException

### Actual behavior

The GetGenericResource method throws System.FormatException: The JSON value could not be converted to Azure.ResourceManager.Models.ManagedServiceIdentity.

### Reproduction Steps

Unfortunately we cannot reproduce this behavior with new resources.

**Comment by Yao725** [comment]
Hi @int292, I'm trying to reproduce this issue and will investigating possible solutions once the reproduction is done. By the way, I will appreciate if you could provide the log of the call `await subscription.GetGenericResourcesAsync()`.

Sample code about how to enable logging:
```csharp
using Azure.Identity;
using Azure.ResourceManager;
using Azure.Core.Diagnostics;

using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Verbose);
ArmClientOptions options = new ArmClientOptions()
{
    Diagnostics =
    {
        IsLoggingContentEnabled = true
    }
};
ArmClient armClient = new ArmClient(new DefaultAzureCredential(), options);
```

**Comment by int292** [comment]
Thank you for the reply! The logging is enabled. The body content is on this moment truncated. Sample part in end of response is: {"id":"/subscri
Do you have maybe (more) suggestions for logging?

**Comment by int292** [comment]
Found that Resourcetype Microsoft.DevTestLab/labs returns this information as part of the json.

```
		"type": "Microsoft.DevTestLab/labs",
			"location": "westeurope",
			"identity": {
				"principalId": "",
				"tenantId": "",
				"type": "None"
			},
```

**Comment by Yao725** [comment]
FYI, we have created this [feature request](https://github.com/Azure/autorest.csharp/issues/2802) for this kind of issue. Will discuss to finalize the solution.

**Comment by int292** [comment]
@Yao725 This is indeed working for the armClient. Thank you for the support on this issue!
