### ISSUE TITLE
[QUERY]How do I send the body when I use LogicWorkflowTriggerResource.Run?

### ISSUE THREAD

**Issue by yk-kd** [Azure/azure-sdk-for-net#33385]
### Library name and version

Azure.ResourceManager.Logic 1.0.0

### Query/Question

I believe you can specify a body for the workflow trigger, but let me know if I'm wrong.

### Environment

Target framework .NET 6

**Comment by Yao725** [comment]
Hi @yk-kd, this method has no body parameter definition in the [REST API spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/logic/resource-manager/Microsoft.Logic/stable/2019-05-01/logic.json#L1107-L1135), which means we don't need to send the body when we call this method. Could you help me understand why you need the body? Thanks.

**Comment by yk-kd** [comment]
Thank you for your reply @Yao725

Sorry. I mistakenly thought this could call a Request(HTTP) trigger.

**Comment by Yao725** [comment]
Np. By the way, if you have any other feedback to our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF).
