### ISSUE TITLE
[BUG] Getting SlotConfigResource results in exception

### ISSUE THREAD

**Issue by dumonjorne** [Azure/azure-sdk-for-net#33384]
### Library name and version

Azure.ResourceManager.AppService

### Describe the bug

I am trying to get the list SlotConfigNames (the appsettings with the tick next to "slotsetting") to be able to update them later on. 
When trying to get them, you get an exception that the resource id cannot be null. 

`await resource.GetSlotConfigNamesResource().GetAsync();` 
_Where resource is a WebSiteResource._ 

When looking into this, I noticed that the REST API returns null for the id. Which makes sense, because it is not really a resource in itself. 

### Expected behavior

The method returns the SlotConfigResource as expected and doesn't throw exceptions. 

Any idea about a workaround? Currently the only thing I see is to call the REST Api myself. 

### Actual behavior

An ArgumentNullException with stacktrace:

>    at Azure.Core.Argument.AssertNotNullOrEmpty(String value, String name)
   at Azure.Core.ResourceIdentifier..ctor(String resourceId)
   at Azure.ResourceManager.AppService.SlotConfigNamesResourceData.DeserializeSlotConfigNamesResourceData(JsonElement element)
   at Azure.ResourceManager.AppService.WebAppsRestOperations.<ListSlotConfigurationNamesAsync>d__138.MoveNext()
   at Azure.ResourceManager.AppService.SlotConfigNamesResource.<GetAsync>d__14.MoveNext()

### Reproduction Steps

Run following code on a `WebSiteResource`:
`await resource.GetSlotConfigNamesResource().GetAsync();`

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @dumonjorne, I'm trying to reproduce this issue, and unfortunately currently there is no good workaround for this issue.

And one more thing about this issue is that it is more like a service-side problem. In the [REST API spec definition](https://github.com/Azure/azure-rest-api-specs/blob/35f8a4df47aedc1ce185c854595cba6b83fa6c71/specification/web/resource-manager/Microsoft.Web/stable/2021-02-01/WebApps.json#L25447), this is marked as `resource`, which means a valid ID should be returned by the backend service.

**Comment by Yao725** [comment]
Sorry for the delayed response, we don't have good ways to accelerate the fix of this bug. Could you please try this workaround?

- Define the policy that will assign a valid value to the id property.

```csharp
	public class InvalidPropertyFilterPolicy : HttpPipelineSynchronousPolicy
	{
	    public override void OnReceivedResponse(HttpMessage message)
	    {
	        if (message.Request.Method != RequestMethod.Put || message.Response.ContentStream == null) // Change here to get the expected response
	        {
	            return;
	        }
	 
	        var reader = new StreamReader(message.Response.ContentStream);
	        var content = reader.ReadToEnd().Replace("", ""); // Assign a valid value to the property id
	        var jsonDocument = JsonDocument.Parse(content);
	        var stream = new MemoryStream();
	        var writer = new Utf8JsonWriter(stream);
	        jsonDocument.WriteTo(writer);
	        writer.Flush();
	        message.Response.ContentStream = stream;
	        message.Response.ContentStream.Position = 0;
	    }
	}
```

- Register the policy in the ArmClientOptions

```csharp
	options.AddPolicy(new InvalidPropertyFilterPolicy(), HttpPipelinePosition.PerRetry);
```

**Comment by dumonjorne** [comment]
Hi,

Thanks for the response. I will try this approach.
I had worked around it using a custom REST client, but with this approach I would be able to use the SDK, so that would have my preference.

**Comment by dumonjorne** [comment]
Hi, 

Based on the above proposed workaround I was able to get slot config names and update them using the SDK. 
``` csharp
class SlotConfigNamesEndpointFilter : HttpPipelineSynchronousPolicy
    {
        public override void OnReceivedResponse(HttpMessage message)
        {
            if (!message.Request.Uri.Path.EndsWith("slotconfignames", StringComparison.OrdinalIgnoreCase) || message.Response.ContentStream == null) // Change here to get the expected response
            {
                return;
            }
            var reader = new StreamReader(message.Response.ContentStream);
            var content = reader.ReadToEnd().Replace("\"id\":null", $"\"id\":\"{message.Request.Uri.Path}\""); // Assign a valid value to the property id
            var jsonDocument = JsonDocument.Parse(content);
            var stream = new MemoryStream();
            var writer = new Utf8JsonWriter(stream);
            jsonDocument.WriteTo(writer);
            writer.Flush();
            message.Response.ContentStream = stream;
            message.Response.ContentStream.Position = 0;
        }
    }
```

**Comment by Yao725** [comment]
Close this issue as it is resolved.

If you have any other feedback to our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF).
