### ISSUE TITLE
[QUERY] Where do GroupIds for PrivateLinkServiceConnection come from?

### ISSUE THREAD

**Issue by rguthriemsft** [Azure/azure-sdk-for-net#33397]
### Library name and version

Microsoft.Azure.Management.Network.Models 0.28.0-preview

### Query/Question

I'm trying to deploy a PrivateEndpoint (from the namespace Microsoft.Azure.Management.Network.Models) to Azure Portal using C#. It will be connected to an Azure Monitor Private Link Scope (AMPLS), which is connected to a Log Analytics Workspace. The PrivateEndpoint class contains a required attribute IList<string> groupIds (hierarchy shown below). I currently have the groupIds I need hardcoded in, and I would like to know where this value should come from so that it can be determined at runtime. I originally thought it might come from the AMPLS, but that class doesn't seem to contain a groupIds attribute.

`var privateEndpoint = new PrivateEndpoint(
                ...
                privateLinkServiceConnections: new List<PrivateLinkServiceConnection>()
                {
                    new PrivateLinkServiceConnection(
                        ...
                        groupIds: new List<string>()
                        {
                            "azuremonitor"
                        })
                });`

### Environment

Visual Studio 2022
netcoreapp6.0
C# Web Api 
Microsoft.Azure.Management.Network.Models 0.28.0-preview

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by foode222** [comment]
> ### Library name and version
> 
> Microsoft.Azure.Management.Network.Models 0.28.0-preview
> 
> ### Query/Question
> 
> I'm trying to deploy a PrivateEndpoint (from the namespace Microsoft.Azure.Management.Network.Models) to Azure Portal using C#. It will be connected to an Azure Monitor Private Link Scope (AMPLS), which is connected to a Log Analytics Workspace. The PrivateEndpoint class contains a required attribute IList<string> groupIds (hierarchy shown below). I currently have the groupIds I need hardcoded in, and I would like to know where this value should come from so that it can be determined at runtime. I originally thought it might come from the AMPLS, but that class doesn't seem to contain a groupIds attribute.
> 
> 
> 
> `var privateEndpoint = new PrivateEndpoint(
> 
>                 ...
> 
>                 privateLinkServiceConnections: new List<PrivateLinkServiceConnection>()
> 
>                 {
> 
>                     new PrivateLinkServiceConnection(
> 
>                         ...
> 
>                         groupIds: new List<string>()
> 
>                         {
> 
>                             "azuremonitor"
> 
>                         })
> 
>                 });`
> 
> ### Environment
> 
> Visual Studio 2022
> 
> netcoreapp6.0
> 
> C# Web Api 
> 
> Microsoft.Azure.Management.Network.Models 0.28.0-preview

**Comment by Yao725** [comment]
This need to be answered by the service team, added the service attention label.

**Comment by foode222** [comment]
> Hi @rguthriemsft.  Thank you for opening this issue and giving us the opportunity to assist.  We believe that this has been addressed.  If you feel that further discussion is needed, please add a comment with the text “`/unresolve`” to remove the “issue-addressed” label and continue the conversation.
