### ISSUE TITLE
[QUERY] Does QueueClient.SendMessage API perform internal retries

### ISSUE THREAD

**Issue by thbui-msft** [Azure/azure-sdk-for-net#33401]
### Library name and version

Azure.Storage.Queues v12.12.0

### Query/Question

We had previously been using the old WindowsAzure.Storage SDK for using Azure Storage Queues. We are currently in the process of migrating to use the new SDK with the Azure.Storage.Queues v12.12.0 library.

Previously, we had used the [CloudQueue.AddMessage API](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.queue.cloudqueue.addmessage?view=azure-dotnet) to add messages to Azure Storage Queues, using QueueRequestOptions  to specify an exponential backoff policy for retrying this request.

In the new SDK, we see the [QueueClient.SendMessage API](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient.sendmessage?view=azure-dotnet) which does not appear to have any way to specify request options like with QueueRequestOptions class previously.

We have 2 main questions:
1. Does QueueClient.SendMessage have any internal retries configured by default?
2. Is there any way to specify request options for QueueClient.SendMessage?

**Comment by PramodValavala-MSFT** [comment]
@thbui-msft You can pass [`QueueClientOptions`](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclientoptions?view=azure-dotnet) when creating a [`QueueServiceClient`](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueserviceclient.-ctor?view=azure-dotnet#azure-storage-queues-queueserviceclient-ctor(system-string-azure-storage-queues-queueclientoptions)) or [`QueueClient`](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.queues.queueclient.-ctor?view=azure-dotnet#azure-storage-queues-queueclient-ctor(system-uri-azure-storage-queues-queueclientoptions)) object which sets the retry policy.
