### ISSUE TITLE
[BUG] Inconsistency in EnvironmentCredential class implementation for .Net and Java azure sdk

### ISSUE THREAD

**Issue by indrajitjadeja** [Azure/azure-sdk-for-net#33413]
### Library name and version

Azure.Identity 1.8.0

### Describe the bug

for .Net,
based on parameters configured, EnvironmentCredential class constructs credential class in below order,
1. ClientSecretCredential
2. UsernamePasswordCredential
3. ClientCertificateCredential

But for Java,
EnvironmentCredential class constructs credential class in below order,
1. ClientSecretCredential
2. ClientCertificateCredential
3. UsernamePasswordCredential

With this difference in implementation order, when user configures the same parameters, we are having inconsistency in our .Net and Java application authentication behavior.

### Expected behavior

In order to have consistent functional behavior of our Java and .Net applications, we are expecting a consistent function behavior between both .Net and java azure SDK.

### Actual behavior

With same parameters set on environment,
.Net application authenticates using below order
 ClientSecretCredential
UsernamePasswordCredential
ClientCertificateCredential

But Java application authenticates using below order
ClientSecretCredential
ClientCertificateCredential
UsernamePasswordCredential

java sdk
https://github.com/Azure/azure-sdk-for-java/blob/aa4a16a76ef7433953951f186c8a23dce1bda32d/sdk/identity/azure-identity/src/main/java/com/azure/identity/EnvironmentCredential.java#L72

.net sdk
https://github.com/Azure/azure-sdk-for-net/blob/59a1f21f37ce826dc75b3d355b63bd26d39dd472/sdk/identity/Azure.Identity/src/Credentials/EnvironmentCredential.cs#L101

### Reproduction Steps

Configure below environment variables
AZURE_TENANT_ID
AZURE_CLIENT_ID
AZURE_CLIENT_CERTIFICATE_PATH
AZURE_USERNAME
AZURE_PASSWORD

Run .Net application that uses EnvironmentCredential class to get the Azure AD access token
Run Java application that uses EnvironmentCredential class to get the Azure AD access token

.Net application will get token using AZURE_USERNAME, AZURE_PASSWORD environment values
Java application will get token using AZURE_CLIENT_CERTIFICATE_PATH environment value

### Environment

OS: Windows 10
.Net SDK: 7.0.100
.Net runtime version: Microsoft.NETCore.App 6.0.11
IDE: Visual Studio 17.4.0

**Comment by jsquire** [comment]
//cc: @christothes, @billwert, @scottaddie

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
*Related:* https://github.com/Azure/azure-sdk-for-net/issues/33414

**Comment by christothes** [comment]
Hi @indrajitjadeja - thanks for pointing this out. While we look at this across all languages, I'm curious if you could describe the scenario that requires setting both username/password environment variables and certificate environment variables at the same time.

**Comment by christothes** [comment]
Just for reference - the other languages all order discovery the same as Java, so .NET is the odd one out.

**Comment by indrajitjadeja** [comment]
@christothes I was testing the default authentication flow using DefaultAzureCredentials class and when I tried setting both username/password and certificate environment variables, I noticed the difference in functional behavior for .Net and Java applications.

**Comment by indrajitjadeja** [comment]
Since #33414 is closed, there are two issues to look at:

1. Why is Client secret given higher precedence than Client certificate?  #33414
2. Priority order not in sync with java azure sdk #33413

**Comment by christothes** [comment]
> @christothes I was testing the default authentication flow using DefaultAzureCredentials class and when I tried setting both username/password and certificate environment variables, I noticed the difference in functional behavior for .Net and Java applications.

Thanks - So just to clarify, your application has no need to set both, this was just an inconsistency you discovered while testing?

**Comment by indrajitjadeja** [comment]
> > @christothes I was testing the default authentication flow using DefaultAzureCredentials class and when I tried setting both username/password and certificate environment variables, I noticed the difference in functional behavior for .Net and Java applications.
> 
> Thanks - So just to clarify, your application has no need to set both, this was just an inconsistency you discovered while testing?

I am developing a library and it is up to the user how to use it.
So, it is possible that the user might decide to set both, username/password and client secret environment variables and find out that there is inconsistency in my .NET library compared to the Java library.

**Comment by indrajitjadeja** [comment]
@christothes from the fix in pull request https://github.com/Azure/azure-sdk-for-net/pull/33551 
I can only see this #33413 is getting resolved,

But for #33414 it has different scenario related to precedence should be given to client certificate first and then client secret.

Please could you confirm, is it the valid issue to be fixed across all languages?
