### ISSUE TITLE
[FEATURE REQ] Interface for Azure.Communication.Email.EmailClient

### ISSUE THREAD

**Issue by humanitnz** [Azure/azure-sdk-for-net#33419]
### Library name

Azure.Communication.Email

### Please describe the feature.

Please provide an interface for the class `Azure.Communication.Email.EmailClient`. Suggestion: `IEmailClient`.

This would help consuming applications make dependency injection easier and allow for more straightforward swaps of email clients such as for unit testing.

**Comment by jsquire** [comment]
Hi @humanitnz.  Thank you for your feedback.   Unfortunately, this is not a request that we're able to consider.  

The Azure SDKs have a goal of strict backwards compatibility with a very high bar for any breaking changes.  With that in mind, the use of an interface makes evolving over time difficult; any change to the public API surface represented in an interface becomes a breaking change for anyone who has implemented it - including when we want to add new members.  

Adding more interfaces to define new members (much like native COM interfaces do in Windows) is possible, but becomes burdensome.  While default interface implementation makes this easier, they're not supported in all of the frameworks that we target.  Our classes and their virtual members can still be mocked and do not have this problem.  As a result, we intentionally avoid using interfaces outside of special circumstances.

Support for mocking and unit testing is one of the core goals of the new Azure SDKs, and the details of the approach that we use are discussed in the [Azure SDK Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking).  All of the public members of the client types are `virtual` or settable, the class is not sealed, and a parameterless constructor is available to ensure that it is usable with a mocking framework such as Moq or FakeItEasy.   You should be able to mock any client using the same approach that you prefer for other types, whether with a mocking framework or inheriting from the class and creating your own mock type, using the model factory to simulate behavior.

For model types that are returned by service operations, a factory class exists to enable creating them for testing.  In the case of `Azure.Communication.Email`, the [CommunicationEmailModelFactory](https://learn.microsoft.com/dotnet/api/azure.communication.email.communicationemailmodelfactory) would be the place to look.

For more discussion and details around unit testing and mocking the Azure SDKs, I'd recommend [this](https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/) post from the Azure SDK blog.

I'm going to mark this as addressed, but please feel free to unresolve should you wish to discuss further.
