### ISSUE TITLE
[BUG] SqlDatabaseResource GetMetricDefinitions fails with "Invalid URI: The format of the URI could not be determined."

### ISSUE THREAD

**Issue by tdraganidis** [Azure/azure-sdk-for-net#33415]
### Library name and version

Azure.ResourceManager.Sql 1.1.0

### Describe the bug

Trying to get the metric definitions for a SqlDatabase using SqlDatabaseResource.GetMetricDefinitions (the same happens also in Async variant of the method) gets me an exception with the message "Invalid URI: The format of the URI could not be determined."

### Expected behavior

The actual list with the Sql Metric Definition should be returned.

### Actual behavior

Trying to get the metric definitions for a SqlDatabase using SqlDatabaseResource.GetMetricDefinitions (the same happens also in Async variant of the method) gets me an exception with the message "Invalid URI: The format of the URI could not be determined."

Rest API with the same arguments used in code when tested either in [Microsoft site](https://learn.microsoft.com/en-us/rest/api/sql/2014-04-01/databases/list-metric-definitions) or using Postman is working as expected. 

Debugging a little bit makes me believe that the issue is in SqlMetricDefinition.DeserializeSqlMetricDefinition and more specifically to this code, which tries to deserialize the request Uri:

```c#
if (((JsonProperty)(ref current)).NameEquals("resourceUri"))
{
  value = ((JsonProperty)(ref current)).get_Value();
  if ((int)((JsonElement)(ref value)).get_ValueKind() == 7)
  {
	  optional3 = null;
	  continue;
  }
  value = ((JsonProperty)(ref current)).get_Value();
  optional3 = (Azure.Core.Optional<Uri>)new Uri(((JsonElement)(ref value)).GetString());
}
```
The main issue is that the request Uri is not a complete uri as it's missing the first part (https:\\management..).
Here's an example of the Rest API result, which is the same with the one returned from the SDK:  
```
<d:resourceUri>/subscriptions/{subscriptionId}/resourceGroups/{resourceName}/providers/Microsoft.Sql/servers/{server-name}/databases/{databaseName}</d:resourceUri>
``` 

### Reproduction Steps

```c#
var resourceManager =  new ArmClient(new DefaultAzureCredential());
var resourceId = SqlServerResource.CreateResourceIdentifier(
				aValidSubscriptionId,
				aValidResourceGroupName,
				anExistingSqlServerName);
var server = _resourceManager.GetSqlServerResource(resourceId);
var sqlDatabase = server.GetSqlDatabase(aValidDatabaseName);
var metricDefinitionsList = sqlDatabase.Value.GetMetricDefinitions().ToList();
```

### Environment

- Windows 10
- Microsoft.NETCore.App 7.0.2
- Visual Studio 17.4.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @tdraganidis, thanks for your finding, I will reproduce this issue and fix it after the reproduction.

**Comment by mcgallan** [comment]
This bug has been fixed
      


            string serverName = Recording.GenerateAssetName("sql-server-");

            var sqlServer = await CreateDefaultSqlServer(serverName, AzureLocation.EastUS, _resourceGroup);
            var collection = sqlServer.GetSqlDatabases();

            string databaseName = Recording.GenerateAssetName("sql-database-");

            // 1.CreateOrUpdate
            SqlDatabaseData data = new SqlDatabaseData(AzureLocation.EastUS) { };
            var dataBase = await collection.CreateOrUpdateAsync(WaitUntil.Completed, databaseName, data);
            var metricDefinitionsList = dataBase.Value.GetMetricDefinitionsAsync();`

**Comment by mcgallan** [comment]
fixed with [this PR](https://github.com/Azure/azure-sdk-for-net/pull/36523)
