### ISSUE TITLE
[QUERY] ETag.All when converted into a string to be put into the HTTP request header is not returned as quoted

### ISSUE THREAD

**Issue by abhipsaMisra** [Azure/azure-sdk-for-net#33435]
### Library name and version

Azure.Core latest

### Query/Question

`ETag.ToString()` when formatted as a header evaluates the following:
https://github.com/Azure/azure-sdk-for-net/blob/9c6238e0f0dd403d6583b56ec7902c77c64a2e37/sdk/core/Azure.Core/src/ETag.cs#L101-L114

where `IsValidQuotedFormat` is:
https://github.com/Azure/azure-sdk-for-net/blob/9c6238e0f0dd403d6583b56ec7902c77c64a2e37/sdk/core/Azure.Core/src/ETag.cs#L137-L140

Since `ETag.All` is returned as a valid quoted format, the `ToSTring("H")` simply returns "*" (without the enclosing quotes).
This is not an acceptable value for [EntityTagHeaderValue](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.headers.entitytagheadervalue?view=net-7.0), which then throws an exception.

Shouldn't `ETag.All` resolve to quote enclosed * (`"\"*\""`) when formatted as a header?

### Environment

```powershell
> dotnet --info

.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
```

Visual Studio 17.4.3

**Comment by jsquire** [comment]
//cc: @annelo-msft, @christothes, @JoshLove-msft, @tg-msft, @KrzysztofCwalina

**Comment by jsquire** [comment]
@AlexanderSher:  Would you please take point on this one?

**Comment by abhipsaMisra** [comment]
@AlexanderSher Any update on this? This seems to be too common a scenario for it to be a bug that was undiscovered until now, so I wonder if I'm missing something at my end with its intended usage.

**Comment by abhipsaMisra** [comment]
@AlexanderSher Any update on this?

**Comment by AlexanderSher** [comment]
`EntityTagHeaderValue` doesn't allow `*` as a value:
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/Headers/GenericHeaderParser.cs#L98
https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/tests/UnitTests/Headers/EntityTagHeaderValueTest.cs#L214

However, `*` is a valid value for `If-Match` / `If-None-Match`: https://www.rfc-editor.org/rfc/rfc7232#section-3.1

@tg-msft, @KrzysztofCwalina - do you know anything about it?

**Comment by AlexanderSher** [comment]
Closing since original IoT issue is resolved: https://github.com/Azure/azure-iot-sdk-csharp/pull/3066
