### ISSUE TITLE
Status of Azure.Communication.Email

### ISSUE THREAD

**Issue by duanepfeiffer** [Azure/azure-sdk-for-net#33452]
### Library name and version

Azure.Communication.Email 1.0.0-beta.1

### Query/Question

Using this sdk looks a lot less compilcated then using MS Graph to send mail from my Azure Functions and other .net projects.  However, I'm a bit concerned as it appears nothing has happened with the git repository since May 2022.  Will this sdk ever be released?

Thanks, Duane

### Environment

Azure functions, .net 6, Blazor, iOS/SwiftUI

**Comment by navba-MSFT** [comment]
@duanepfeiffer Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@duanepfeiffer We are in public preview and getting ready for GA targeting CYQ12023. Hope this helps.
