### ISSUE TITLE
[Synapse]CreateAndUploadNotebook failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33469]
Synapse nightly test runs are failing with:

> Error message
> System.Text.Json.JsonException : A property 'targetSparkConfiguration' defined as non-nullable but received as null from the service. This exception only happens in DEBUG builds of the library and would be ignored in the release build
> 
> 
> Stack trace
>    at Azure.Core.JsonElementExtensions.ThrowNonNullablePropertyIsNull(JsonProperty property) in /_/microsoft.azure.autorest.csharp/3.0.0-beta.20230111.1/content/Generator.Shared/JsonElementExtensions.cs:line 97
>    at Azure.Analytics.Synapse.Artifacts.Models.Notebook.DeserializeNotebook(JsonElement element) in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.Artifacts\src\Generated\Models\Notebook.Serialization.cs:line 123
>    at Azure.Analytics.Synapse.Artifacts.Models.NotebookResource.DeserializeNotebookResource(JsonElement element) in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.Artifacts\src\Generated\Models\NotebookResource.Serialization.cs:line 59
>    at Azure.Analytics.Synapse.Artifacts.NotebookCreateOrUpdateNotebookOperation.Azure.Core.IOperationSource<Azure.Analytics.Synapse.Artifacts.Models.NotebookResource>.CreateResultAsync(Response response, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.Artifacts\src\Generated\NotebookCreateOrUpdateNotebookOperation.cs:line 79
>    at Azure.Core.NextLinkOperationImplementation.OperationToOperationOfT`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /_/microsoft.azure.autorest.csharp/3.0.0-beta.20230111.1/content/Generator.Shared/NextLinkOperationImplementation.cs:line 0
>    at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 260
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 87
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 79
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 202
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 242
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 177
>    at Azure.Analytics.Synapse.Artifacts.Samples.Sample2_HelloWorldNotebook.CreateAndUploadNotebook() in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.Artifacts\tests\samples\Sample2_HelloWorldNotebook.cs:line 49
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformW

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2112771&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Synapse is owned by the service team; multiple issues for test quality are already open.   Closing this out as there's no benefit to tracking each test individually.

**Comment by v-xuto** [comment]
@jsquire So about this service `Synapse`, we don't need to issue issues for it?
