### ISSUE TITLE
[Search]Options failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33468]
Search nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Invalid expression: Could not find a property named 'Rating' on type 'search.document'.
> Parameter name: $orderby
> Status: 400 (Bad Request)
> 
> Content:
> {"error":{"code":"","message":"Invalid expression: Could not find a property named 'Rating' on type 'search.document'.\r\nParameter name: $orderby"}}
> 
> Headers:
> Cache-Control: no-cache
> Pragma: no-cache
> client-request-id: c4305361-4d38-4575-a7f0-4e03b10900de
> x-ms-client-request-id: c4305361-4d38-4575-a7f0-4e03b10900de
> request-id: c4305361-4d38-4575-a7f0-4e03b10900de
> elapsed-time: 93
> Preference-Applied: REDACTED
> Strict-Transport-Security: REDACTED
> Date: Sat, 07 Jan 2023 14:30:40 GMT
> Content-Type: application/json; charset=utf-8
> Content-Language: REDACTED
> Expires: -1
> Content-Length: 149
> 
> 
> Stack trace
>    at Azure.Search.Documents.SearchClient.SearchInternal[T](SearchOptions options, String operationName, Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/src/SearchClient.cs:line 898
>    at Azure.Search.Documents.SearchClient.SearchInternal[T](String searchText, SearchOptions options, Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/src/SearchClient.cs:line 851
>    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 33
>    at Azure.Search.Documents.SearchClient.Search[T](String searchText, SearchOptions options, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/src/SearchClient.cs:line 772
>    at Castle.Proxies.Invocations.SearchClient_Search.InvokeMethodOnTarget()
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Azure.Core.TestFramework.InstrumentResultInterceptor.Intercept(IInvocation invocation) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/InstrumentResultInterceptor.cs:line 100
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.Intercept(IInvocation invocation) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 57
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Azure.Core.TestFramework.GetOriginalInterceptor.Intercept(IInvocation invocation) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/GetOriginalInterceptor.cs:line 28
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Castle.Proxies.SearchClientProxy.Search[T](String searchText, SearchOptions options, CancellationToken cancellationToken)
>    at Azure.Search.Documents.Tests.Samples.Readme.Options() in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/tests/Samples/Readme.cs:line 177
>    at Azure.Search.Documents.Tests.Samples.Readme.Options() in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/tests/Samples/Readme.cs:line 177
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2099511&view=results

@jsquire for notification.

**Comment by ShivangiReja** [comment]
Duplicate issue - https://github.com/Azure/azure-sdk-for-net/issues/33356 and it's been fixed here - https://github.com/Azure/azure-sdk-for-net/pull/33364
