### ISSUE TITLE
[Translation]GetDocumentStatusesFilterByCreatedAfter failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#33470]
Translation nightly test runs are failing with:

> Error message
> Expected: 3
> But was:  2
> 
> 
> Stack trace
>    at Azure.AI.Translation.Document.Tests.DocumentTranslationClientLiveTests.GetDocumentStatusesFilterByCreatedAfter() in /Users/runner/work/1/s/sdk/translation/Azure.AI.Translation.Document/tests/GetAllDocumentsFilterTests.cs:line 106
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 
> 1)    at Azure.AI.Translation.Document.Tests.DocumentTranslationClientLiveTests.GetDocumentStatusesFilterByCreatedAfter() in /Users/runner/work/1/s/sdk/translation/Azure.AI.Translation.Document/tests/GetAllDocumentsFilterTests.cs:line 106

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2112185&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Translation is owned by the service team.  There are multiple test quality issues currently open.  Closing this out; there's no benefit to tracking each test individually.

**Comment by v-xuto** [comment]
@jsquire So about this service `Translation`, we don't need to issue issues for it?

**Comment by jsquire** [comment]
@v-xuto:  Correct;  there's a few libraries owned by service teams that are not actively working with GitHub issues nor monitoring their test runs.   There's little value in having multiple issues open for them, as they're just going to sit and rot.    Translation is one of these.
