### ISSUE TITLE
[BUG] Azure Portal still suggests you use the deprecated package Microsoft.Azure.Cosmos.Table instead of Azure.Data.Tables

### ISSUE THREAD

**Issue by samsmithnz** [Azure/azure-sdk-for-net#33495]
### Library name and version

Azure.Data.Tables12.7.1

### Describe the bug

[BUG] Azure Portal still suggests you use the deprecated package Microsoft.Azure.Cosmos.Table instead of Azure.Data.Tables

![image](https://user-images.githubusercontent.com/8389039/212574370-32571d06-b39e-456f-af79-2720e52c09d3.png)

### Expected behavior

The examples are recommendations for the Azure.Data.Tables package

### Actual behavior

the examples are recommendations for the Microsoft.Azure.Cosmos.Table package

### Reproduction Steps

Create a new CosmosDB resource in the Azure Portal. After creation the message in the screenshot above is shown

**Comment by SaurabhSharma-MSFT** [comment]
@samsmithnz We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@samsmithnz Thanks Sam for reporting this issue. I have started a conversation internally with the products team and they will try to get that updated as soon as possible.  I will update you once I receive any news.

**Comment by jsquire** [comment]
Closing this out, as the Cosmos service team does not provide support from this repository and they will not be updating this issue.  I've confirmed that this is an active request being tracked by the service team, though they have no public tracking item to share.
