### ISSUE TITLE
remove docs for services such as serviceclient that are outdated.

### ISSUE THREAD

**Issue by ranjith-t** [Azure/azure-sdk-for-net#33498]
There are services which are outdated in Azure IOT SDK such as serviceclient, but the documentation still exists. This is confusing for the both existing users as well as new users. Request you to remove such documents or clearly put a header note mentioning that the service has outdated and kept for reference purpose only?.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: aca599e4-372d-0b9f-a4b4-7fc74e281f83
* Version Independent ID: b0145584-6942-fef0-089e-e05d0d290f94
* Content: [ServiceClient Class (Microsoft.Azure.Devices) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.serviceclient?view=azure-dotnet&viewFallbackFrom=azure-dotnet-legacy)
* Content Source: [xml/Microsoft.Azure.Devices/ServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Devices/ServiceClient.xml)
* Service: **iot-hub**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@ranjith-t Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@ranjith-t The [IoT .NET ServiceClient](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.serviceclient?view=azure-dotnet) has not been deprecated yet.

Could it be that the original post is looking for the ServiceClient under azure-dotnet-legacy, and being unable to find it thinks that the ServiceClient has been deprecated. See the URL:

> https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.serviceclient?view=azure-dotnet& **viewFallbackFrom=azure-dotnet-legacy**

<img width="504" alt="image" src="https://user-images.githubusercontent.com/57353862/215957235-187526eb-5c1d-497f-802e-e9ce9633c886.png">

 Our GA'd APIs can be found under azure-dotnet (latest). See here: https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.devices.serviceclient?view=azure-dotnet
