### ISSUE TITLE
Azure.AI.TextAnalytics SDK / AnalyzeHealthcareEntities

### ISSUE THREAD

**Issue by ahmadbjanthala** [Azure/azure-sdk-for-net#33509]
Package Name: Azure.AI.TextAnalytics
Package Version: 5.2.0
Operating System: Windows
.NET runtime version: .NET6
Visual Studio Enterprise 2022 version: 17.4.4
Region: WestEroup

await healthOperation.WaitForCompletionAsync();
suddenly stop working!
no response

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ahmadbjanthala** [comment]
> Thank you for your feedback. Tagging and routing to the team member best able to assist.

I create a new one with the Region EastUs  and its work fine now 
but the WestEroup still not working

**Comment by joseharriaga** [comment]
Thank you for reporting this issue, @ahmadbjanthala. We have identified a problem related to healthcare analysis in the West Europe region and are currently investigating.

**Comment by joseharriaga** [comment]
Hello, @ahmadbjanthala. The issue has been mitigated and healthcare analysis operations in the West Europe region should be back to normal.

**Comment by ahmadbjanthala** [comment]
> Hello, @ahmadbjanthala. The issue has been mitigated and healthcare analysis operations in the West Europe region should be back to normal.

@joseharriaga thanks but what was the issue and will that happen again? 
because i also faced the same issue for APIM in west Europe region but that issue solved almost within one hour! 

for now I'm using the east us region instead, do you recommend me to get back to west Europe or start using different region?

**Comment by joseharriaga** [comment]
@ahmadbjanthala: The issue was very specific to healthcare text analysis, so the hiccup with APIM was probably something different. Aside from that, if the East US region satisfies all your needs, then it is perfectly fine for you to keep using it, and you do not need to switch to another region. 

Once again, thank you for reporting this issue!

**Comment by ahmadbjanthala** [comment]
This issue happened again! 
now in  the East US region
