### ISSUE TITLE
[FEATURE REQ] InboundNatRuleData should contain a BackendAddressPool property

### ISSUE THREAD

**Issue by itai** [Azure/azure-sdk-for-net#33513]
### Library name

Azure.ResourceManager.Network v1.1.0

### Please describe the feature.

[InboundNatRuleData](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.network.inboundnatruledata?view=azure-dotnet) is missing a BackendAddressPool property.

This is found in the [REST API](https://learn.microsoft.com/en-us/rest/api/load-balancer/inbound-nat-rules/get?tabs=HTTP#backendaddresspool).

It also provided by the deprecated [Microsoft.Azure.Management.Network package](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.network.models.inboundnatrule.backendaddresspool?view=azure-dotnet#microsoft-azure-management-network-models-inboundnatrule-backendaddresspool).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
The [REST API doc](https://learn.microsoft.com/en-us/rest/api/load-balancer/inbound-nat-rules/get?tabs=HTTP) is based on API version `2022-07-01` while the [Azure.ResourceManager.Network v1.1.0](https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.Network_1.1.0/sdk/network/Azure.ResourceManager.Network/src/autorest.md#tag-package-track2-preview) SDK is based on `2021-02-01`. Therefore, we need to bump the API version to support the `BackendAddressPool` property in `InboundNatRuleData`.

**Comment by ArthurMa1978** [comment]
The new version was released @itai, please try the latest version from nuget.
