### ISSUE TITLE
[FEATURE REQ] Allow modification of permission scopes

### ISSUE THREAD

**Issue by sarbos** [Azure/azure-sdk-for-net#33537]
### Library name

Azure.ResourceManager.Storage

### Please describe the feature.

StorageAccountLocalUserCollection.CreateOrUpdate should allow modification of permission scopes. 

Currently the PermissionScopes list on StorageAccountLocalUserData is read only, meaning that there is no way to set permissions for the user. The REST api supports it, it is just not exposed through this function. 

This feature would be necessary to allow container based access for SFTP local users, which is my specific use case. 

Thanks!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
- The SDK follows the .NET design guideline to [not provide settable collection properties](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values).  

- The read-only list properties can be initialized by omitting the `new List<T>` as instructed in the guide [here](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-collection-read-only-property-initialization). 

- Or you can get the list properties directly (they are implemented with [ChangeTrackingList](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/ChangeTrackingList.cs) and will always be instantiated in the constructor of the containing type, in this case in [StorageAccountLocalUserData](https://github.com/Azure/azure-sdk-for-net/blob/f856281e40d1c6dcb11116595c0e7bf011929b6c/sdk/storage/Azure.ResourceManager.Storage/src/Generated/StorageAccountLocalUserData.cs#L21)), then just add elements to the list.

**Comment by sarbos** [comment]
Thank you, that is exactly what I needed to know!
