### ISSUE TITLE
[Bug] Azure.AI.TextAnalytics / WestEroup 

### ISSUE THREAD

**Issue by ahmadbjanthala** [Azure/azure-sdk-for-net#33538]
- **Package Name**: Azure.AI.TextAnalytics
- **Package Version**: 5.2.0
- **Operating System**: Windows
- **.NET runtime version**: .NET6
- **Visual Studio Enterprise 2022 version**: 17.4.4

await healthOperation.WaitForCompletionAsync(); 

it was working fine but before two days it stopped without any change in the code or the SDK 
and there is no response for this line of code!

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

Language Quickstart Feedback
* Content: [Quickstart: Using Text Analytics for health client library and REST API - Azure Cognitive Services](https://learn.microsoft.com/azure/cognitive-services/language-service/text-analytics-for-health/quickstart?pivots=programming-language-csharp)
* Content Source: [articles/cognitive-services/language-service/text-analytics-for-health/quickstart.md](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/cognitive-services/language-service/text-analytics-for-health/quickstart.md)
* Section: **Clean-up-resources**
* Service: **cognitive-services**
* Sub-service: **language-service**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by joseharriaga** [comment]
Thank you for reporting this issue! We have identified a problem related to healthcare analysis in the West Europe region and are currently investigating.

**Comment by joseharriaga** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/33509
