### ISSUE TITLE
[QUERY] How to use InteractiveBrowserCredential with Azure AD B2C User Flows

### ISSUE THREAD

**Issue by codeminic** [Azure/azure-sdk-for-net#33542]
### Library name and version

Azure.Identity 1.8.1

### Query/Question

Is it possible to use `InteractiveBrowserCredential` with Azure AD B2C User Flows?

This is the code i'm using at the moment:
```csharp
var options = new InteractiveBrowserCredentialOptions
{
    RedirectUri = new Uri("http://localhost:5678")
};
var identity = new InteractiveBrowserCredential("mytenant.onmicrosoft.com", "myClientId", options);
var tokenRequestContext = new TokenRequestContext(new[] { "myScope" });
var tokenResponse = await identity.GetTokenAsync(tokenRequestContext);
```

However, I see no way to define for e.g. the `SignUpSignInPolicyId`. When calling `GetTokenAsync`, I get the standard AD login screen - as expected.

Is it somehow possible to define the Policies needed for ADB2C authentication? 

Thank your for your help!

### Environment

.NET 7
Visual Studio 17.5.0

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Sorry, B2C is not currently supported. It's mentioned in the [Known Issues](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#known-issues) section of the readme.
