### ISSUE TITLE
[BUG] Missing Metadata in SiteConfigProperties

### ISSUE THREAD

**Issue by christophwille** [Azure/azure-sdk-for-net#33569]
### Library name and version

Azure.ResourceManager.AppService 1.0.0

### Describe the bug

Basically same as https://github.com/Azure/azure-rest-api-specs/issues/12412

We need to set CURRENT_STACK "dotnet" in config/metadata because otherwise v4.0 stack isn't properly registered (empty stack dropdown in Azure Portal).

### Expected behavior

Have a Metadata property on SiteConfigProperties so I can set the CURRENT_STACK

### Actual behavior

Simply impossible to properly create a ASP.NET 4.8 Web site.

### Reproduction Steps

F12 on the class

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
This requires app service team add this property in their swagger, SDK does not have the ability to do it, you can submit your feature request in this page: https://feedback.azure.com/d365community/forum/b09330d1-c625-ec11-b6e6-000d3a4f0f1c

**Comment by christophwille** [comment]
Done at https://feedback.azure.com/d365community/idea/ca687b53-cd97-ed11-a81b-000d3ae49307

But don't get me wrong... there should be an avenue here for you to directly forward swagger bugs to the respective teams. That disconnect in communcation is ... awkward.

**Comment by live1206** [comment]
> Done at https://feedback.azure.com/d365community/idea/ca687b53-cd97-ed11-a81b-000d3ae49307
> 
> But don't get me wrong... there should be an avenue here for you to directly forward swagger bugs to the respective teams. That disconnect in communcation is ... awkward.

SDK team is not in charge of this kind of change. 
If we browse the linking issue https://github.com/Azure/bicep/issues/784, https://github.com/Azure/bicep/issues/784#issuecomment-1414357241 points to a proper entry for such issues.
It would get a bigger chance to get it resolved by raising it there, close this issue in SDK.
