### ISSUE TITLE
[BUG] Unable to deserialize GetActivityLogs() : System.FormatException: One of the identified items was in an invalid format at System.Text.Json.JsonElement.GetGuid()

### ISSUE THREAD

**Issue by tbolon** [Azure/azure-sdk-for-net#33572]
### Library name and version

Azure.ResourceManager.Monitor 1.0.0

### Describe the bug

When calling SubscriptionResource.GetActivityLogs().ToList() with a basic filter (eventTimestamp) and no select, I receive the following error:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.FormatException: One of the identified items was in an invalid format.
   at System.Text.Json.JsonElement.GetGuid()
   at Azure.ResourceManager.Monitor.Models.EventDataInfo.DeserializeEventDataInfo(JsonElement element)
   at Azure.ResourceManager.Monitor.Models.EventDataCollection.DeserializeEventDataCollection(JsonElement element)
   at Azure.ResourceManager.Monitor.ActivityLogsRestOperations.List(String subscriptionId, String filter, String select, CancellationToken cancellationToken)
   at Azure.ResourceManager.Monitor.SubscriptionResourceExtensionClient.<>c__DisplayClass75_0.<GetActivityLogs>g__FirstPageFunc|0(Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.FuncPageable`1.<AsPages>d__4.MoveNext()
   at Azure.Pageable`1.<GetEnumerator>d__8.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

I don't have access to the json source anymore, but I will try to 

### Expected behavior

The json should be deserialized.

### Actual behavior

The methods throws an exception

### Reproduction Steps

```csharp
SubscriptionResource subscription;
// ... 
var date = DateTime.UtcNow;
var resourceId = "...";
var filter = $"eventTimestamp ge '{date.AddHours(-hours):o}' and eventTimestamp le {date:o} and resourceUri eq '{resourceId}'";
var logs = subscription.GetActivityLogs(filter).ToList();
```

### Environment

.NET Framework 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
you can enable source json in log by set options of new ArmClient as below
```csharp
var options = new ArmClientOptions()
options.Diagnostics.IsLoggingContentEnabled=true;
               options.Diagnostics.IsLoggingEnabled=true;
               var client = new ArmClient(new DefaultAzureCredential(),options);
```
kindly share your raw json so that we can understand which field is triggering this issue

**Comment by fengzhou-msft** [comment]
The error is thrown in `EventDataInfo.DeserializeEventDataInfo()`. The only `Guid` in `EventDataInfo` is `TenantId`. Please help get the raw json response as @xboxeer mentioned and check if any `tenantId` is not a valid Guid/uuid.

**Comment by tbolon** [comment]
I am sorry but I am unable to reproduce the problem for now. I ran the exact same filter on a custom console app and I did not raise any exception.

I will try again on monday, and if I can't reproduce it I will close this issue.

**Comment by tbolon** [comment]
@fengzhou-msft I was able to dump a full json dump. Can you provide me an email ?

**Comment by tbolon** [comment]
I have simply detected cases where the tenantId is empty (I have edited the sensitive ids):

```json
{
    "channels": "Admin, Operation",
    "correlationId": "3e84620f-38cd-4d5b-8b55-965356e1f74b",
    "description": "",
    "eventDataId": "fa74d33c-34ac-4b6c-9144-bdbe044a7ed9",
    "eventName": {
        "value": "",
        "localizedValue": ""
    },
    "category": {
        "value": "ResourceHealth",
        "localizedValue": "Resource Health"
    },
    "id": "/SUBSCRIPTIONS/00000000-0000-4E34-0000-00008AF10000/RESOURCEGROUPS/MYRESOURCEGROUP/PROVIDERS/MICROSOFT.SQL/SERVERS/MYSQLSERVER/DATABASES/MYDATABASE/events/fa74d33c-34ac-4b6c-9144-bdbe044a7ed9/ticks/638106425059531945",
    "level": "Informational",
    "resourceGroupName": "MYRESOURCEGROUP",
    "resourceProviderName": {
        "value": "Microsoft.Resourcehealth/healthevent/action",
        "localizedValue": "Microsoft.Resourcehealth/healthevent/action"
    },
    "resourceId": "/SUBSCRIPTIONS/00000000-0000-4E34-0000-00008AF10000/RESOURCEGROUPS/MYRESOURCEGROUP/PROVIDERS/MICROSOFT.SQL/SERVERS/MYSQLSERVER/DATABASES/MYDATABASE",
    "resourceType": {
        "value": "MICROSOFT.SQL/SERVERS/DATABASES",
        "localizedValue": "MICROSOFT.SQL/SERVERS/DATABASES"
    },
    "operationId": "",
    "operationName": {
        "value": "Microsoft.Resourcehealth/healthevent/Resolved/action",
        "localizedValue": "Health Event Resolved"
    },
    "properties": {
        "title": "Unknown",
        "details": "Unknown",
        "currentHealthStatus": "Available",
        "previousHealthStatus": "Degraded",
        "type": "Unknown",
        "cause": "Unknown"
    },
    "status": {
        "value": "Resolved",
        "localizedValue": "Resolved"
    },
    "subStatus": {
        "value": "",
        "localizedValue": ""
    },
    "eventTimestamp": "2023-01-30T02:28:25.9531945Z",
    "submissionTimestamp": "2023-01-30T02:28:25.9531945Z",
    "subscriptionId": "00000000-0000-4E34-0000-00008AF10000",
    "tenantId": ""
}
```

**Comment by fengzhou-msft** [comment]
@tbolon thanks for the investigation. As expected, the non-guid `tenantId` caused the deserialization issue. We will work with service team on a fix.

**Comment by fengzhou-msft** [comment]
@sameergMS @dadunl in the returned ActivityLogs, the `tenantId` property may be an empty string. .NET SDK treats `TenantId` as `Guid` type. Therefore it cannot store the value of an empty string. Does it make sense and won't cause any problems if we treat empty string tenantId as null in our deserialization?

**Comment by leeyyi** [comment]
Hi, still get the same error in the 1.3.0 version.

**Comment by leeyyi** [comment]
Hi, here's a bug here. At your EventDataInfo.Serialization.cs, a empty string doesn't mean the null kind here. 
<img width="317" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/90611250/e57b7c5e-f3cf-45a3-b9c3-fe37e8f3d631">
Demo with a small code snippet.
<img width="498" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/90611250/1c4e216d-2722-4de4-8b22-0655a5e549c0">.

**Comment by leeyyi** [comment]
Why filter on level is not supported? As azure portal can do that 
<img width="670" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/90611250/3b828e4c-70cd-47b9-952a-23501606197d">

**Comment by melina5656** [comment]
The same issue occurred in #43151 and has been fixed.
