### ISSUE TITLE
[BUG] Microsoft.Azure.WebJobs.Extensions.Tables not working with output binding for Azure Functions

### ISSUE THREAD

**Issue by chschulsie** [Azure/azure-sdk-for-net#33570]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Tables 1.0.0

### Describe the bug

When using Output bindings with Azure Tables using Managed Identity for authentication, the Output binding always throws an error when trying to add an entity. 

> Error message: 
> 2023-01-18T09:06:48.599 [Error] Executed 'Functions.writeTableTest' (Failed, Id=97c74ddb-19ce-41a9-9f28-65f8f9b4f703, Duration=47ms)**'' is not a valid value for a partition key or row key.**

Code used from sample provided in docs: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table-output?tabs=in-process%2Cstorage-extension&pivots=programming-language-powershell 

```
param($InputData, $TriggerMetadata)


foreach ($i in 1..10) {
    Push-OutputBinding -Name TableBinding -Value @{
        PartitionKey = 'Test'
        RowKey = "$i"
        Name = "Name $i"
    }
}
```

Notes: 
Input bindings works fine with the same setup. 
Permissions are assigned properly (table contributor, reader)

As package must be added manually, this is what the extension.csproj shows: 
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
	<WarningsAsErrors></WarningsAsErrors>
	<DefaultItemExcludes>**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Tables" Version="1.0.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator" Version="1.1.3" />
  </ItemGroup>
</Project>
```

### Expected behavior

Output binding to work with Managed Identity. 

### Actual behavior

When using MI with output binding for tables, the following error throws: 

Error message: 
2023-01-18T09:06:48.599 [Error] Executed 'Functions.writeTableTest' (Failed, Id=97c74ddb-19ce-41a9-9f28-65f8f9b4f703, Duration=47ms)**'' is not a valid value for a partition key or row key.**

### Reproduction Steps

Create new function app in Visual Studio Code. 
PowerShell version 7.2

Install required packages manually:
dotnet nuget add source --name nuget.org https://api.nuget.org/v3/index.json
func extensions install --package Microsoft.Azure.WebJobs.Extensions.Tables --version 1.0.0

- Create output binding referencing app setting
- Add app settings referencing the storage account for table service: <storageaccoutname>__tableServiceUri
- Enable Managed Identity for the function app
- Grant MI permissions to the storage account

More information here: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-table-output?tabs=in-process%2Cstorage-extension&pivots=programming-language-powershell#identity-based-connections

### Environment

Azure Function runtime: PowerShell 7.2
netcoreapp3.1 (as in extensions.csproj)
IDE: visual studio code

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by jsquire** [comment]
@christothes : Do you mind taking the first look and if this is something specific to the bindings, looping Josh in?

**Comment by chschulsie** [comment]
Hi! Any updates on this? @christothes - Did you have time to look into this. 
Unfortunately, this is blocking a use case on our side at the moment.

**Comment by christothes** [comment]
Sorry for the delay - Just to clarify, does this work as expected when using another credential type? Would you happen to have a simple repro sample application in GitHub somewhere that reproduces this just to ensure that I am using the exact same config?
