### ISSUE TITLE
ServiceBus no way to manage Rules on Subscriptions?

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#3358]
`SubscriptionCreateOrUpdateParameters` doesn't have Rules part.
From browsing the code could find anything that would hint at how to do it.

**Comment by jaredwri** [comment]
A problem for me as well.

**Comment by shahabhijeet** [comment]
@SeanFeldman thank you for reporting this.
@sazeesha can you please respond if there anyway Rules can be provided during update

**Comment by SeanFeldman** [comment]
Any updates on this one? Thank you.

**Comment by SeanFeldman** [comment]
I see there's a way to do it using `ServiceBusManagementClient.Rules.CreateOrUpdateAsync()`

**Comment by SeanFeldman** [comment]
And there's a way to manage rules with the new client as well based on the [PR](https://github.com/Azure/azure-service-bus-dotnet/pull/70) and confirmation [here](https://github.com/Azure/azure-service-bus-dotnet/issues/246#issuecomment-320057086).

Very disappointing to see that @shahabhijeet and @sazeesha from MSFT could not find the time two months to discuss this and update the issue 😞
