### ISSUE TITLE
Exception: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__45.MoveNext()

### ISSUE THREAD

**Issue by sadviramana** [Azure/azure-sdk-for-net#33591]
Facing this exact issue as mentioned in [https://github.com/Azure/azure-service-bus/issues/361](https://github.com/Azure/azure-service-bus/issues/361) as I am trying to migrate from WindowsAzure.Servicebus to Microsoft.Azure.Servicebus

**Comment by jsquire** [comment]
Please note that `Microsoft.Azure.ServiceBus` is a deprecated package and receiving only critical security and bug fixes.   It is recommended that you consider migrating to `Azure.Messaging.ServiceBus` instead, as this is the current generation package and under active development.

**Comment by SaurabhSharma-MSFT** [comment]
@sadviramana As mentioned above did you try using Azure.Messaging.ServiceBus instead? And can you please share your code snippet which is throwing error. Thanks
