### ISSUE TITLE
[FEATURE REQ] Please add ability to specify if a client-side feature is being used in User-Agent strings

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#33598]
### Library name

Azure.Core

### Please describe the feature.

We would like to append the User-Agent strings in the Storage SDKs to indicate if a customer is using client-side encryption. This ask is coming out of an MSRC case where we had a security vulnerability in our client-side encryption, but we were unable to tell which SDK customers were using the feature.

https://github.com/Azure/azure-sdk/issues/5401

**Comment by jsquire** [comment]
Moving to the backlog, pending discussion in the linked issue from the main Azure SDK repository.   This is something that would need discussion among all architects and a common format decided upon.

**Comment by jsquire** [comment]
After discussion and planning, this is not a feature that will be added to Core.   Closing this out.
