### ISSUE TITLE
[BUG] ErrorCode: InvalidQueryParameterValue

### ISSUE THREAD

**Issue by Grozniq** [Azure/azure-sdk-for-net#33590]
### Library name and version

Azure.Storage.Files.DataLake 12.12.1

### Describe the bug

Trying to load a file from Data Lake : 
```
var fileSystemClient = new DataLakeFileSystemClient(
        new Uri(this.configuration.GetDataLakeBaseUrl()),
        this.GetSharedKeyCredentials());
var directoryClient = fileSystemClient.GetDirectoryClient(directoryName);
...
var fileClient= directoryClient.GetFileClient(fileName)))
var downloadResponse = await fileClient.ReadAsync();
...
```
Like described here : https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-dotnet#download-from-a-directory

Directory and File exist on Azure. I double checked the account key and we seem to be authorized but we get the following error:

```
Value for one of the query parameters specified in the request URI is invalid.
RequestId:fa87970f-b01e-003e-540a-2c4808000000
Time:2023-01-19T13:30:55.2058024Z
Status: 400 (Value for one of the query parameters specified in the request URI is invalid.)
ErrorCode: InvalidQueryParameterValue

Additional Information:
QueryParameterName: comp
QueryParameterValue: 
Reason: 

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:fa87970f-b01e-003e-540a-2c4808000000
Time:2023-01-19T13:30:55.2058024Z</Message><QueryParameterName>comp</QueryParameterName><QueryParameterValue /><Reason /></Error>

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: fa87970f-b01e-003e-540a-2c4808000000
x-ms-client-request-id: 61e83173-d45d-498f-9506-d2e549e05ab2
x-ms-error-code: InvalidQueryParameterValue
Date: Thu, 19 Jan 2023 13:30:55 GMT
Content-Length: 351
Content-Type: application/xml
```

### Expected behavior

200 OK

### Actual behavior

400 Bad Request

### Reproduction Steps

1. Create Data Lake Storage Account
2. Create Directory
3. Create File
4. Download File via Code as described above

### Environment

.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  3.1.406 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]
  **6.0.405 [C:\Program Files\dotnet\sdk]**
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  **Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]**
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by SaurabhSharma-MSFT** [comment]
@Grozniq We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@Grozniq I am not able to reproduce this issue and Azure.Storage.Files.DataLake version 12.12.1 worked fine for me.
