### ISSUE TITLE
[Identity]Deploy test failing in nightly runs

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-net#33606]
Identity nightly test runs are failing with:

> Error message:
> VERBOSE: Running registered exit actions
> VERBOSE: Logging out of service principal '***'
> VERBOSE: Performing the operation "New-TestResources.ps1" on target "***".
> Compress-Archive: /mnt/vss/_work/1/s/sdk/identity/test-resources-post.ps1:13
> Line |
>   13 |  Compress-Archive -Path "$workingFolder/Pub/*" -DestinationPath "$work …
>      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | The path '/mnt/vss/_work/Pub' either does not exist or is not a valid
>      | file system path.
> 
> ##[error]PowerShell exited with code '1'.

For more details check here:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2129968&view=results

@jsquire for notification.

**Comment by schaabs** [comment]
@christothes can you take a look at this since you added the test resources script for identity?

**Comment by christothes** [comment]
transient error
