### ISSUE TITLE
[Question] AADSTS7000213: Invalid certificate chain

### ISSUE THREAD

**Issue by shanuwed** [Azure/azure-sdk-for-net#33608]
### Library name and version

Azure.Security.KeyVault.Certificates 4.4.0

### Query/Question

I'm migrating from Microsoft.Azure.KeyVault 3.0 to Azure.Security.KeyVault.Certificates 4.4.0. After the migration one of the unit tests started to fail. The exception I get is this:
"Azure.Identity.AuthenticationFailedException: ClientCertificateCredential authentication failed: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000213: Invalid certificate chain.
Timestamp: 2023-01-20 06:53:09Z ---> Microsoft.Identity.Client.MsalServiceException: A configuration issue is preventing authentication - check the error message from the server for details. You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details.  Original exception: AADSTS7000213: Invalid certificate chain.

I'd like to understand what AADSTS7000213 is and how to go about debugging the failure. The same unittest runs without an issue under the old Microsoft.Azure.KeyVault 3.0. What are the things I should be checking, and to look for?

### Environment

.NET 4.7 on Win 10 
Visual Studio 2019

**Comment by jsquire** [comment]
Hi @shanuwed.  Thanks for reaching out and we regret that you're experiencing difficulties.  The error that you're seeing comes from the MSAL library used by Azure.Identity.   To ensure that we get this in front of the right folks to assist, I've transferred this to the repository where the MSAL library is maintained as [#3909](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3909)
