### ISSUE TITLE
[BUG] Verbose logging introduced in Azure functions v4 + Extensions.Storage.Blobs v5.0.0

### ISSUE THREAD

**Issue by d4046949** [Azure/azure-sdk-for-net#33626]
### Library name and version

Extensions.Storage.Blobs v5.0.0, Azure Functions V4

### Describe the bug

We've just upgraded our functions runtime to v4 and had to upgrade the Blobs storage library to v5.

Now we've got a lot more logging going into app insights....

2023-01-21T09:39:14Z [Information] Executing 'Function1' (Reason='This function was programmatically called via the host APIs.', Id=0395c4e5-442c-42b1-98af-e587449f3d16)
2023-01-21T09:39:14Z [Information] C# HTTP trigger function processed a request.
2023-01-21T09:39:14Z [Information] Request [<redacted>] PUT https://<redacted>.blob.core.windows.net/provider-data/test.txt
x-ms-blob-type:BlockBlob
If-None-Match:*
x-ms-version:2020-10-02
Accept:application/xml
x-ms-client-request-id:<redacted>
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Blobs/12.10.0,(.NET 6.0.11; Microsoft Windows 10.0.14393)
x-ms-date:Sat, 21 Jan 2023 09:39:13 GMT
Authorization:REDACTED
Content-Length:11
Content-Type:application/octet-stream
client assembly: Azure.Storage.Blobs
2023-01-21T09:39:14Z [Warning] Error response [<redacted>] 409 The specified blob already exists. (00.0s)
Server:Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id:<redacted>
x-ms-client-request-id:<redacted><redacted>
x-ms-version:2020-10-02
x-ms-error-code:BlobAlreadyExists
Date:Sat, 21 Jan 2023 09:39:12 GMT
Content-Length:220
Content-Type:application/xml
2023-01-21T09:39:14Z [Error] Executed 'Function1' (Failed, Id=<redacted>, Duration=11ms)

The error and the warnings are correct, I just don't want the verbose details going in to insights. This wasn't an issue prior to upgrading

Function:

```
[FunctionName("Function1")]
 public static async Task<IActionResult> Run(
 [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
 [Blob(FILE_PREFIX, Connection = "myconn")] BlobContainerClient bc,
 ILogger log)
 {
 log.LogInformation("C# HTTP trigger function processed a request.");

 bc.UploadBlob("test.txt", BinaryData.FromString("hello world"));
 
 
 return new OkObjectResult(new { });

```
My host Json file:
```
{
 "version": "2.0",
 "logging": {
 "applicationInsights": {
 "samplingExcludedTypes": "Request",
 "samplingSettings": {
 "isEnabled": true
 }
 },
 "logLevel": {
 "default": "Warning",
 "Host.Results": "Warning",
 "Function": "Warning",
 "Function.GetVersion": "Trace",
 "Host.Aggregator": "Warning",
 "azure.storage": "Warning",
 "Azure": "Warning",
 "azure": "Warning",
 "azure.storage.common.storageclient": "Warning",
 "azure.core.pipeline.policies.http_logging_policy": "Warning"
 }
 }
}

```
### Expected behavior

No verbose logging should appear unless requested. 

### Actual behavior

Cannot remove the verbose and excess logging after upgrading.

### Reproduction Steps

Create a new function app
Install the Blob extensions library
Make a request to Blob and notice the verbose output

### Environment

Azure App Service Consumption plan

**Comment by jsquire** [comment]
I'd suggest adding a log filter for the `Azure.Core` source, which is the source of most of the informational entries from your example.

```json
"logLevel": {
    "Azure.Core" : "Warning"
}
```

**Comment by d4046949** [comment]
Thanks for the suggestion, I've updated the host.json file to look like this now
```

{
  "version": "2.0",
  "Logging": {
    "LogLevel": {
      "Default": "Warning"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Azure.Core": "Warning",
        "Default": "Warning",
        "TableStorageWithAZFunc": "Information"
      }
    }
  }
}
```

However, when deployed to a Consumption app service plan,  Function > Monitor you can still see the verbose information logging.

**Comment by RohitRanjanMS** [comment]
Hi @d4046949 do you see these logs in the Application Insights? 

Function -> Monitor blade shows log streamed by the AI SDK; these logs are not stored in AI. We don't apply any filter for log streaming while logs ingested in AI are filtered based on your configuration. 
There's no cost associated with log streaming.

**Comment by sodablue** [comment]
I seem to be fighting this issue now.  I also migrated a function app from v3 to v4.

I don't understand why you would purposefully break this, and trying to look at logs in AI is not an improved experience.   If I want to see the current state of the system, I'm going to be looking at the Log Stream.   If I want to see past exceptions, then I'll go to AI.

I was able to calm it down somewhat by setting `"enableDependencyTracking": false`, but as it is the amount of verbose logging just increases the noise level so high it's impossible to use the monitoring tools.

**Comment by pjmvp** [comment]
Also racking up noise and costs due to this bug.

As seen above, I mentioned it in

- https://github.com/Azure/azure-functions-host/issues/8973

Getting a lot of verbose logs like

```
Request [5c30e4c2-30ef-4c60-89e7-c8c850f1b597] PUT https://(REDACTED)
x-ms-lease-action:renew
x-ms-lease-id:d011227a-a939-9337-ebd1-9480e1eb64be
x-ms-version:2021-08-06
Accept:application/xml
x-ms-client-request-id:0000e4c2-30bf-4960-89e7-c8c850f1b111
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Blobs/12.13.0,(.NET 6.0.13; Microsoft Windows 10.0.14393)
x-ms-date:Tue, 07 Mar 2023 19:56:17 GMT
Authorization:REDACTED
client assembly: Azure.Storage.Blobs
```

...and no way of turning them off!

**Comment by surgupta-msft** [comment]
The issue has been fixed. Please refer https://github.com/Azure/azure-functions-host/issues/8973#issuecomment-1636192111 and https://github.com/Azure/azure-functions-host/issues/9408 for more information.
