### ISSUE TITLE
Fluent: problems upgrading to 1.1.0 from 1.0.0 (System.Runtime not in GAC?)

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#3362]
Using .net framework 4.5.2 as project target and.. the -IgnoreDependencies flag (because anything else is too slow).

`Update-Package Microsoft.Azure.Management.ResourceManager.Fluent -IgnoreDependencies

Package 'Microsoft.Azure.Management.ResourceManager.Fluent 1.0.0' already exists in folder 'C:\repo\cp\packages'
Added package 'Microsoft.Azure.Management.ResourceManager.Fluent 1.0.0' to 'packages.config'
Removing package 'Microsoft.Azure.Management.ResourceManager.Fluent 1.1.0' from folder 'C:\repo\cp\packages'
Removed package 'Microsoft.Azure.Management.ResourceManager.Fluent 1.1.0' from folder 'C:\repo\cp\packages'
Executing nuget actions took 28.63 sec
Update-Package : Failed to add reference. The package 'Microsoft.Azure.Management.ResourceManager.Fluent' tried to add a framework reference 
to 'System.Runtime' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
  Error HRESULT E_FAIL has been returned from a call to a COM component.
At line:1 char:1
+ Update-Package Microsoft.Azure.Management.ResourceManager.Fluent -IgnoreDependen ...`

**Comment by hovsepm** [comment]
@TimLovellSmith thanks for reporting. We are working on the hotfix.

**Comment by hovsepm** [comment]
Hotfix published to nuget. Please upgrade to version 1.1.1.
