### ISSUE TITLE
[QUERY] Storage: usage assistance

### ISSUE THREAD

**Issue by shahedaAnsari** [Azure/azure-sdk-for-net#33651]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Query/Question

I want to get the sum of blobs size between two date range. I want to apply filter on Lastmodified date.
Can you please help me on this

### Environment

.Net 6
Visual studio 22

**Comment by SaurabhSharma-MSFT** [comment]
@shahedaAnsari We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@shahedaAnsari You can use the something below to get the SUM of blobs size.

```
string accountName = "storage_account";
string containerName = "myContainer";

BlobContainerClient container = new BlobContainerClient(CONNECTION_STRING, containerName);

// Set the start and end date range
DateTime startDate = new DateTime(2022, 3, 18);
DateTime endDate = new DateTime(2022, 3, 19);

// Filter the blobs by date range
var filteredBlobs = container.GetBlobs().Where(b => b.Properties.LastModified >= startDate && b.Properties.LastModified <= endDate).ToList();

// Get the sum of the blobs size
long sum = (long)filteredBlobs.Sum(b => b.Properties.ContentLength);

Console.WriteLine("Total Size : " + sum);
```
Please let me know if you have any questions.
