### ISSUE TITLE
Add Azure Search support to Fluent API 

### ISSUE THREAD

**Issue by olegburov** [Azure/azure-sdk-for-net#3365]
It would be handy if [Azure Management Libraries for .NET](https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/) (aka Fluent API) supported [Azure Search](https://azure.microsoft.com/en-us/services/search/) service.

Please consider to bring support for it, since this is what we are heavily using.

**Comment by brjohnstmsft** [comment]
@olegburov Thanks for the feedback. I will check with the folks working on the Fluent SDKs to see if supporting Azure Search is on their near-term roadmap.

**Comment by olegburov** [comment]
@brjohnstmsft thanks for the update.

Just for the record, I've contacted az-libs-for-net@microsoft.com and @selvasingh said the following:

> We plan to add support for search.

If you could provide any ETA or at least a Fluent version number when it's coming, that would be useful for my team. Thank you!

**Comment by brjohnstmsft** [comment]
@olegburov I haven't synced up with @selvasingh yet, so I don't know what the ETA for Azure Search support is in the Fluent libraries, but I'll update this issue when I have more information.

**Comment by hovsepm** [comment]
@olegburov we are planning to include it in v1.2 which is the next release cycle.

**Comment by olegburov** [comment]
@hovsepm, great! Thank you for the update.

**Comment by martinsawicki** [comment]
support for Search in the fluent API was released in v1.2
