### ISSUE TITLE
[QUERY] ArmClient subscription scopes

### ISSUE THREAD

**Issue by shareonline** [Azure/azure-sdk-for-net#33650]
### Library name and version

Azure.ResourceManager.ResourceGraph 1.0.0

### Query/Question

Is it somehow possible to set multiple subscriptions as scope in a ResourceGraph query like it was with the old SDK and the rest api?

I can't seem to figure it out, and i think the possibility is missing..
Subscriptions is read only:

<img width="756" alt="image" src="https://user-images.githubusercontent.com/17081368/214298484-fbbef01e-072d-4d3d-aa03-dc55bd742062.png">

### Environment

.Net 7.0
Visual Studio 17.4.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by shareonline** [comment]
> (not on the team, but...)
> 
> The `Subscriptions` collection/list cannot be replaced with your own (which makes sense especially with your nullable input list and the non-null base list), but the list itself is mutable and you can add entries to it.
> 
> ```cs
> if (SubscriptionIds != null)
> {
>     foreach (string SubscriptionId in SubscriptionIds)
>     {
>         Querytest.Subscriptions.Add(SubscriptionId);
>     }
> }
> ```

I truly have no words right now.. Can't believe i missed this :) Thank you @AtOMiCNebula!
