### ISSUE TITLE
ApplicationTokenProvider.LoginSilentWithCertificateAsync is missing an overload that allows both ActiveDirectoryServiceSettings and TokenCache to be provided

### ISSUE THREAD

**Issue by matt1883** [Azure/azure-sdk-for-net#3366]
Re: Microsoft.Rest.ClientRuntime.Azure.Authentication NuGet package, v2.3.1:

The method ``ApplicationTokenProvider.LoginSilentWithCertificateAsync`` is missing an overload that allows both ``ActiveDirectoryServiceSettings`` and ``TokenCache`` to be provided. Here are the three options that exist today in ``ApplicationTokenProvider``:

    public static Task<ServiceClientCredentials> LoginSilentWithCertificateAsync(string domain, ClientAssertionCertificate certificate);
    
    public static Task<ServiceClientCredentials> LoginSilentWithCertificateAsync(string domain, ClientAssertionCertificate certificate, 
       ActiveDirectoryServiceSettings settings);
    
    public static Task<ServiceClientCredentials> LoginSilentWithCertificateAsync(string domain, ClientAssertionCertificate certificate, 
       TokenCache cache);

For context, ``UserTokenProvider`` and non-cert ``ApplicationTokenProvider`` support the use of both ``ActiveDirectoryServiceSettings`` and ``TokenCache`` today:

    // from UserTokenProvider:
    public static Task<ServiceClientCredentials> LoginWithPromptAsync(string domain, ActiveDirectoryClientSettings clientSettings, 
       ActiveDirectoryServiceSettings serviceSettings, 
       TokenCache cache);
    
    // from ApplicationTokenProvider:
    public static Task<ServiceClientCredentials> LoginSilentAsync(string domain, string clientId, string secret, 
       ActiveDirectoryServiceSettings settings, 
       TokenCache cache);

Supporting both of these parameters is important for scenarios where, for example, a non-default token audience needs to be used in conjunction with a token cache.

**Comment by abatishchev** [comment]
Any update on this, please?

**Comment by MurrayFoxcroft** [comment]
Any update on this again - I have the same issue.

**Comment by ravicini** [comment]
When I update `Microsoft.Rest.ClientRuntime.Azure.Authentication` from 2.3.2 to 2.3.3 or 2.3.4 I run in a similar error.

We use `Microsoft.Azure.Management.Fluent.Azure.Configure().Authenticate(azureCredentials);` to authenticate on azure.

```
var result = await ac.AcquireTokenAsync(
                managementApiResource,
                clientId,
                new Uri(redirectUri),
                new PlatformParameters(PromptBehavior.Auto));

var tokenCredentials = new TokenCredentials(result.AccessToken, result.AccessTokenType);
return new AzureCredentials(tokenCredentials, tokenCredentials, clientId, AzureEnvironment.AzureGlobalCloud);
```

On 2.3.1 we successful authenticate.

Any newer version results in the following exception:
```
Unhandled Exception: System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Rest.ServiceClientCredentials> Microsoft.Rest.Azure.Authentication.UserTokenProvider.LoginSilentAsync(System.String, System.String, System.String, System.String, Microsoft.Rest.Azure.Authentication.ActiveDirectoryServiceSettings, Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache)'.
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.SubscriptionsOperations.<ListWithHttpMessagesAsync>d__7.MoveNext()
```

**Comment by ravicini** [comment]
Today I updated the libraries
- `Microsoft.Rest.ClientRuntime.Azure.Authentication` to 2.3.4
- `Microsoft.Rest.ClientRuntime.Azure.Authentication` to 1.15.1

My case seems to be resolved.
