### ISSUE TITLE
Consider upgrading DiagnosticSource dependency to 5.0

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#33683]
We are currently using 4.6.0 for compatibility with V2 functions. At this point, almost all customers are on V3. In V3, the function host uses 5.0.0, so we _should_ be able to safely upgrade from a functions perspective at least. There may also be a dependency consideration for PowerShell integration with our libraries, but would need to investigate the details there.

**Comment by JoshLove-msft** [comment]
This would also help with testing the ActivitySource path. Otherwise test projects need to explicitly add a 5.0.0 dependency.

**Comment by lmolkova** [comment]
It would also allow us to do this: https://github.com/Azure/azure-sdk/issues/3319

**Comment by fowl2** [comment]
I would hope there there would at least be deprecation warning before dropping support for Azure Functions v1! .NET Framework support for v4 only went GA very recently and it takes time to port.

**Comment by m-redding** [comment]
Linking some old issues for additional context: #8739 #25824 #7166

**Comment by lmolkova** [comment]
thanks for digging up the old issues, @m-redding! 

I think https://github.com/Azure/azure-sdk-for-net/issues/8739  is really relevant , AFAIK PowerShell 6 is no longer supported and PowerShell 7 should have the right version of DiagnosticSource:

```powershell
PS> [System.AppDomain]::CurrentDomain.GetAssemblies().where({$_.FullName -match "DiagnosticSource"}) | Select FullName "DiagnosticSource"}) | Select FullName
```


FullName
--------
System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51


Perhaps, we can test if doing something simple in powershell with azure SDK works (if we update DS to 5.0.0)
As a precaution, I wonder if we could guard tracing code with a runtime check that would disable all instrumentation if DS version is lower than expected (or multiple of  DS assemblies are loaded as it happens on Functions).


@fowl2 I believe we won't stop support Frunction v1 with this, but would stop supporting distributed tracing in newish Azure SDK  on Functions v1 with such a change.

**Comment by fowl2** [comment]
> @fowl2 I believe we won't stop supporting Functions v1 with this, but would stop supporting distributed tracing in newish Azure SDK  on Functions v1 with such a change.

@lmolkova @m-redding could you confirm this won't break Azure Functions v1 (see https://github.com/Azure/azure-sdk-for-net/issues/33683#issuecomment-1527117254) / if it is, it's clear in the release notes. Thanks!

**Comment by m-redding** [comment]
Hi @fowl2! I had some discussions with the Functions team, and we don't believe this will break Functions V1 compatibility. The upgraded System.Diagnostics.DiagnosticSource package is compatible with .NET Framework 4.8. There's a chance you may get a warning from the compiler depending on how your project is configured, but the tracing code will continue to work as it did before.
