### ISSUE TITLE
[BUG] TableClient.CreateIfNotExistsAsync creates entry for failed request in Application Insights if table already exists

### ISSUE THREAD

**Issue by thomasneubergersdx** [Azure/azure-sdk-for-net#33690]
### Library name and version

Azure.Data.Tables 12.6.1

### Describe the bug

If I call TableClient.CreateIfNotExistsAsync() for an existing table, a request is sent to create it and the resulting exception is caught and dismissed. 

### Expected behavior

The call to the table storage to create the table is not logged by Application Insights as a failed request.

### Actual behavior

The failed call to the table storage should not be logged by Application Insights, because it is expected and dealt with.

At least, there should be an option to turn on this behavior.

### Reproduction Steps

var tableServiceClient = new TableServiceClient(connectionString);
var tableClient = tableServiceClient.GetTableClient(tableName);
await tableClient.CreateIfNotExistsAsync();

### Environment

Azure App Service, Linux x64, .NET 6

**Comment by jsquire** [comment]
Hi @thomasneubergersdx.  Thank you for reaching out and we regret that you're experiencing difficulties.   This is a known behavior of the Storage library, and one that a fix is planned for.   This work is tracked under #9934.    I'm going to link this to that issue and close out as a duplicate.
