### ISSUE TITLE
YIQI S.A BOT 

### ISSUE THREAD

**Issue by TheBaiter** [Azure/azure-sdk-for-net#33705]
- **Package Name**: 
- **Package Version**: 
- **Operating System**: 
- **.NET runtime version**: 

[Enter feedback here]

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

Language Quickstart Feedback
* Content: [Quickstart: Entity Linking using the client library and REST API - Azure Cognitive Services](https://learn.microsoft.com/azure/cognitive-services/language-service/entity-linking/quickstart?pivots=programming-language-csharp)
* Content Source: [articles/cognitive-services/language-service/entity-linking/quickstart.md](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/cognitive-services/language-service/entity-linking/quickstart.md)
* Section: **Set-up-the-environment**
* Service: **cognitive-services**
* Sub-service: **language-service**

**Comment by jsquire** [comment]
Reported and closing as spam.
