### ISSUE TITLE
Poblem Uploadng 

### ISSUE THREAD

**Issue by eduardoagr** [Azure/azure-sdk-for-net#33708]
### Which service(blob, file, queue, table) does this issue concern?

Blob

### Which version of the SDK was used?

Azure Storage Blobs client library for .NET

### Which platform are you using? (ex: .NET Core 2.1)

wpf - net6.0

### What problem was encountered?

Ok so I was trying to implement the windows ten share UI in WPF, and because is a pain and I need it to be backward compatible with Win 7. I am trying another approach

I create a new Container in azure

The new container name is "share" and is public

And here is the URI

https://transcribemedocs.blob.core.windows.net/share

So, I am using this method to upload it

 public async Task<Uri> UploadToAzureBlobStorage(string FilePath) {

            ContainerClient = new BlobContainerClient(ConectionString,
                ConstantsHelpers.AZURE_DOWNLOAD_SHARE_DOCUMENTS);

            var blob = ContainerClient.GetBlobClient(Path.GetFileName(FilePath));
            await blob.UploadAsync(FilePath, true);

            return new Uri($"{ConstantsHelpers.AZURE_DOWNLOAD_SHARE_DOCUMENTS}");
        }

        public const string AZURE_DOWNLOAD_SHARE_DOCUMENTS = "https://transcribemedocs.blob.core.windows.net/share";

And I use it like this

  var uri = await azureStorage.UploadToAzureBlobStorage(file.FilePath);

But I get this error

Azure.RequestFailedException: 'The specifed resource name contains invalid characters.

RequestId:d42d17f4-801e-0058-1ea9-31d585000000

Time:2023-01-26T17:13:37.0752800Z

Status: 400 (The specifed resource name contains invalid characters.)

ErrorCode: InvalidResourceName

Content:

<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidResourceName</Code><Message>The specifed resource name contains invalid characters.

RequestId:d42d17f4-801e-0058-1ea9-31d585000000

Time:2023-01-26T17:13:37.0752800Z</Message></Error>

Headers:

Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

x-ms-request-id: d42d17f4-801e-0058-1ea9-31d585000000

x-ms-client-request-id: 2f18698f-d34e-4a9e-bef8-23af87d7c775

x-ms-version: 2021-10-04

x-ms-error-code: InvalidResourceName

Date: Thu, 26 Jan 2023 17:13:36 GMT

Content-Length: 243

Content-Type: application/xml

'

I do not understand, I am able to upload it to my other containers

If you want to see more detail check 

Share URL of files

https://learn.microsoft.com/en-us/answers/questions/1164573/share-url-of-files?comment=question

### How can we reproduce the problem in the simplest way?

Try to upload something, using this 

public const string AZURE_DOWNLOAD_SHARE_DOCUMENTS = "https://transcribemedocs.blob.core.windows.net/share";

### Have you found a mitigation/solution?

no

**Comment by navba-MSFT** [comment]
@eduardoagr  Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@eduardoagr I looked at the backend logs for the failing request ID `d42d17f4-801e-0058-1ea9-31d585000000`. The Request URL that was used here is below:
"https:// transcribemedocs.blob.core.windows.net:443/**https:**/Cuentos%20Infantiles%20La%20ratita%20presumida%20En%20Espaol.docx"

The container name is appearing as `Container=https:` This is resulting in the error `InvalidResourceName `. So you need to debug the application code and check if you are sending the right blob request URL. Hope this helps.
