### ISSUE TITLE
[BUG] ResourceManager.Compute: Cannot set Script property

### ISSUE THREAD

**Issue by Hoezer** [Azure/azure-sdk-for-net#33704]
### Library name and version

Azure.ResourceManager.Compute

### Describe the bug

The parameter Script is not accepted because it is only a Get argument the summary looks different.
/// <summary> Optional. The script to be executed.  When this value is given, the given script will override the default script of the command. </summary>
var runCommandInput = new RunCommandInput("RunPowerShellScript")
{
Script = "Write-host 'Hello World'",
};

### Expected behavior

var runCommandInput = new RunCommandInput("RunPowerShellScript")
{
Script = "Write-host 'Hello World'",
};
This to work becouse as a overwite

### Actual behavior

Error	CS0200	Property or indexer 'RunCommandInput.Script' cannot be assigned to -- it is read only

### Reproduction Steps

Script above

### Environment

.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Hoezer** [comment]
Does anyone have a workaround to the issue? Or a different method to run a PowerShell script and get the output of the script back as a result.

**Comment by fengzhou-msft** [comment]
@Hoezer The `Script` property is of `IList<string>` type. Please use below code:

```
var runCommandInput = new RunCommandInput("RunPowerShellScript")
{
    Script = {"Write-host 'Hello World'"},
};
```
You can learn more about the initialization of read-only list property [here](https://learn.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-collection-read-only-property-initialization).

**Comment by Hoezer** [comment]
> @Hoezer The `Script` property is of `IList<string>` type. Please use below code:
> 
> ```
> var runCommandInput = new RunCommandInput("RunPowerShellScript")
> {
>     Script = {"Write-host 'Hello World'"},
> };
> ```
> 
> You can learn more about the initialization of read-only list property [here](https://learn.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-collection-read-only-property-initialization).

Thanks
