### ISSUE TITLE
[Container Registry]CanUploadAndDownloadLargeBlob failing in nightly runs

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-net#33721]
Container Registry nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 404 (Not Found)
> Content:
> {"errors":[{"code":"BLOB_UPLOAD_INVALID","message":"blob upload invalid"}]}
> Headers:
> Server: openresty
> Date: Fri, 27 Jan 2023 19:42:10 GMT
> Connection: keep-alive
> Access-Control-Expose-Headers: REDACTED
> Docker-Distribution-Api-Version: REDACTED
> Strict-Transport-Security: REDACTED
> X-Content-Type-Options: REDACTED
> X-Ms-Client-Request-Id: 1e8f196e-c293-4cfd-a531-49538053171c
> X-Ms-Correlation-Request-Id: REDACTED
> X-Ms-Request-Id: 21b6790c-c743-4739-a12c-63865d5174de
> Content-Type: application/json; charset=utf-8
> Content-Length: 76
> 
> Stack trace
>    at Azure.Containers.ContainerRegistry.ContainerRegistryBlobRestClient.UploadChunk(String nextLink, Stream value, String contentRange, String contentLength, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Generated/ContainerRegistryBlobRestClient.cs:line 495
>    at Azure.Containers.ContainerRegistry.Specialized.ContainerRegistryBlobClient.UploadInChunksInternalAsync(String location, Stream stream, Int32 chunkSize, Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ContainerRegistryBlobClient.cs:line 418
>    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 33
>    at Azure.Containers.ContainerRegistry.Specialized.ContainerRegistryBlobClient.UploadBlob(Stream stream, UploadBlobOptions options, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ContainerRegistryBlobClient.cs:line 324
>    at InvokeStub_ContainerRegistryBlobClient.UploadBlob(Object, Object, IntPtr*)
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 120
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 171
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 201
>    at Azure.Containers.ContainerRegistry.Tests.ContainerRegistryBlobClientLiveTests.CanUploadAndDownloadLargeBlob() in /mnt/vss/_work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRegistryBlobClientLiveTests.cs:line 611
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2144515&view=results

@jsquire for notification.

**Comment by annelo-msft** [comment]
This work is tracked by https://github.com/Azure/azure-sdk-for-net/issues/32948.  Closing as duplicate.
