### ISSUE TITLE
[Form Recognizer] AnalyzeDocumentCanParseMultipageInvoice(True) failing in nightly runs

### ISSUE THREAD

**Issue by zzhxiaofeng** [Azure/azure-sdk-for-net#33723]
Form Recognizer nightly test runs are failing with:

> Error message
> Expected: 2
> But was:  1
> 
> Stack trace
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DocumentAnalysisClientLiveTests.AnalyzeDocumentCanParseMultipageInvoice(Boolean useStream) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/DocumentAnalysisClient/DocumentAnalysisClientLiveTests.cs:line 1013
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 
> 1)    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DocumentAnalysisClientLiveTests.AnalyzeDocumentCanParseMultipageInvoice(Boolean useStream) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/DocumentAnalysisClient/DocumentAnalysisClientLiveTests.cs:line 1013

For more details check here:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2145601&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Test has been disabled for now. The behavior is deterministic and was caused by an update in one of the service's prebuilt models. The task of reenabling it and fixing the issue is being tracked by https://github.com/Azure/azure-sdk-for-net/issues/35570.
