### ISSUE TITLE
[Test Framework] Prompt to redeploy test resources if RESOURCE_GROUP is gone

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#33725]
When running a live test run locally, the absence of a required env var will trigger a prompt to deploy the necessary test resources based on the test-resources.json file. One common pain point is that because the resources are automatically deleted based on the delete after tag, the Test Framework may still find the env var, but it points to a deleted resource group. One easy improvement would be to check if the resource group still exists as part of the [WaitForEnvironmentAsync](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/TestEnvironment.cs#L244). If it doesn't, we can launch the prompt to deploy test resources. The downside is that users might still have all other env vars as valid, and may not even need the RG env var, but it would hopefully serve as a good proxy for whether their other vars are up-to-date. Worst case, they can just re-run the script and the prompt will stop after they get a fresh resource group. The old one would get deleted anyway after the expiration.

**Comment by pallavit** [comment]
> When running a live test run locally, the absence of a required env var will trigger 

Curious about the flow here. I have in the past always run the New-TestResources script before running an SDK test in live test mode. From this description looks like there is an auto-detect mode as well? Could you share what flow is that? Any links that I can read and play with?
