### ISSUE TITLE
Azure.ResourceManager.CosmosDB no way to create a database

### ISSUE THREAD

**Issue by EnenDaveyBoy** [Azure/azure-sdk-for-net#33727]
### Library name and version

Azure.ResourceManager.CosmosDB 1.2.0

### Query/Question

How do you actually create a database using this, using the previou version 1.0.0-preview.1 I had  but this isn't in v1.2.0 and the arm client doesn't have any docs for id that doesn't relate to generic arm docs, however looking at the arm docs for other products it doesn't match any of the flows i have looked where you get a collection and the CreateOrUpdate the collection, v1.2.0 doesn't have access to collections.

So how to i add a database? and where to i find docs?

### Environment

VS Code
c# net6.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by EnenDaveyBoy** [comment]
I have this sorted will post code in a bit.

**Comment by EnenDaveyBoy** [comment]
var subscriptionId = "<SubscriptionId>";
            var resourceGroupName = "<resourceGroupName>";
            var location = "<location>>";
            var accountName = "<accountName>";
            var databaseName = "<databaseName>";
            var containerName = "<containerName>";
            var partitionKeyPath = "<partitionKeyPath>";

            var client = new ArmClient(new DefaultAzureCredential());

            var resourceGroup = client.GetResourceGroupResource(new ResourceIdentifier($"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}"));

            CosmosDBAccountResource resource = resourceGroup.GetCosmosDBAccount(accountName);

            CosmosDBSqlDatabaseCollection account = resource.GetCosmosDBSqlDatabases();

            var info = new Azure.ResourceManager.CosmosDB.Models.CosmosDBSqlDatabaseResourceInfo(databaseName);   
            var database = await account.CreateOrUpdateAsync(WaitUntil.Completed, databaseName, new CosmosDBSqlDatabaseCreateOrUpdateContent(new AzureLocation(location), info));

            CosmosDBSqlContainerCollection container = database.Value.GetCosmosDBSqlContainers();
            
            var indexPolicy = new Azure.ResourceManager.CosmosDB.Models.CosmosDBIndexingPolicy();
            indexPolicy.IndexingMode = new CosmosDBIndexingMode("consistent");

            var partitionKey = new CosmosDBContainerPartitionKey();
            partitionKey.Paths.Add(partitionKeyPath);

            var containerInfo = new CosmosDBSqlContainerResourceInfo(containerName);
            containerInfo.IndexingPolicy = indexPolicy;
            containerInfo.PartitionKey = partitionKey;

            var result = await container.CreateOrUpdateAsync(WaitUntil.Completed, containerName, new CosmosDBSqlContainerCreateOrUpdateContent(new AzureLocation(""), containerInfo));
