### ISSUE TITLE
Release Azure.ResourceManager.ContainerInstance

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#33739]
Link: https://github.com/Azure/azure-rest-api-specs/pull/21530
Readme Tag: package-preview-2022-10
Target release date: No later than 2023-01-27

**Comment by ArthurMa1978** [comment]
Here is a pr https://github.com/Azure/azure-sdk-for-net/pull/33426 for Track 1.
Track 2 need extra work.

**Comment by fengzhou-msft** [comment]
Track 2 released with https://github.com/Azure/azure-sdk-for-net/pull/33586.
