### ISSUE TITLE
Release Azure.ResourceManager.DataProtectionBackup

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#33731]
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/dataprotection/resource-manager
Readme Tag: package-2023-01

No later than 2023-02-24

**Comment by Yao725** [comment]
Close this one as [Azure.ResourceManager.DataProtectionBackup](https://www.nuget.org/packages/Azure.ResourceManager.DataProtectionBackup/1.1.0) is released.
