### ISSUE TITLE
[BUG] Failure to Retry on 503s

### ISSUE THREAD

**Issue by MBSolomon** [Azure/azure-sdk-for-net#33761]
### Library name and version

Azure.Data.AppConfiguration Version=1.2.0

### Describe the bug

Sent a GET request. Returned 503 and did not retry.

### Expected behavior

On receiving 503 we expect SDK to retry the request

### Actual behavior

We sent a GET request to our configuration store to retrieve a key value. 503 was returned to us and no retry occurred.
Same thing happens with POST request. Screenshots shown below

### Reproduction Steps

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/89044647/215561503-b834efc6-e699-4caa-a24b-e4a10c832d6d.png)

{"Method":"POST","RequestUri":"https://api-dogfood.resources.windows-int.net/subscriptions/05890f38-7eb9-4027-9ba6-33439d2cb482/resourceGroups/CoreRGdogfoodEastUS/providers/Microsoft.AppConfiguration/configurationStores/CoredogfoodEUS/listKeys?api-version=2022-03-01-preview","ClientRequestId":"d4d0e971-9e4d-474e-b388-0fb61b8259e8","Duration":30051,"StatusCode":503}

![Screenshot 2023-01-30 failedPOST](https://user-images.githubusercontent.com/89044647/215562594-2792d8dd-d19d-46cf-bb2b-d65c478c9a12.png)

### Environment

.NET SDK version: 6.0

Hosting platform: geneva synthetics

**Comment by jsquire** [comment]
Hi @MBSolomon.  Thank you for reaching out and we regret that you're experiencing difficulties.  Retries are implicit and exceptions will not surface unless all attempts were exhausted without success.  Can you help me understand why you believe that retries are not occurring for you?   

I'd also appreciate if you could share a snippet of how you're creating and configuring your client.   The URL in the images that you've shared is calling API version "2022-03-01" but v1.2.0 of Azure.Data.AppConfiguration only supports API version "1.0" - is there something happening at the service level to implicitly map and rewrite the request URL?

**Comment by jsquire** [comment]
//cc: @ShivangiReja
