### ISSUE TITLE
[QUERY] Proper Behavior of baseBlobClient.Exists() when Container or Blob Does Not Exist

### ISSUE THREAD

**Issue by danieloh1** [Azure/azure-sdk-for-net#33779]
### Library name and version

Azure.Storage.Blobs 12.14.0

### Query/Question

What is the proper behavior of BaseBlobClient.Exists() when the container or blob does not exist? In the API, it says that it should return a boolean and that if a RequestFailedException is raised, then the exception should be thrown. 

In the case where a container or blob does not exist and a 404 error is caught, should the Exists() call result in a ResultFailedException getting thrown or should it return false and not throw the exception?

With Azure Storage Emulator, we are seeing Exists() throw a 404 error in this scenario but with Azurite, it is returning false and not throwing the 404 error. 

### Environment

- .NET Core SDK Version: 3.1.420
- Visual Studio 17.4.4

**Comment by SaurabhSharma-MSFT** [comment]
@danieloh1 We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@danieloh1 I have tried using Azure Emulator but unable to reproduce this issue and the code doesn't throw 404.  Please find below the sample code snippet and the response.
![image](https://user-images.githubusercontent.com/38112130/218331664-72651fed-9ef0-470b-bf03-420bb03966d7.png)

**Comment by danieloh1** [comment]
We are

**Comment by danieloh1** [comment]
We are creating a BlobServiceClient with the "UseDevelopmentStorage=true"
`private static readonly BlobServiceClient client = new BlobServiceClient(StorageEmulator.ConnectionString);`

We then check the following and it throws 404 with Azure Storage Emulator.
<img width="501" alt="image" src="https://user-images.githubusercontent.com/105062615/218544873-22d60c85-6fed-498d-b724-75e2820f6dc7.png">

We are noticing with Azurite that this behavior is different and instead returning false. Is the Azurite behavior the correct one?

**Comment by danieloh1** [comment]
Any updates on whether this behavior is expected or not? In Azure Storage Emulator, this was throwing a 404 error instead. If this behavior was changed for Azurite to more closely align with Azure Storage, then we can make the appropriate changes.

**Comment by amnguye** [comment]
I believe Azure Storage Emulator was deprecated. Even so we don't take Azure Storage Emulator issues here either.

You should be following what behavior Azurite does. Which is if a 404 (BlobNotFound) is seen, then the `Exists` will return false. If a different exception other than that occurs, an exception will be thrown.
