### ISSUE TITLE
[FEATURE REQ] Improve README Azure.AI.OpenAI

### ISSUE THREAD

**Issue by jpalvarezl** [Azure/azure-sdk-for-net#33789]
### Library name

Azure.AI.OpenAI

### Please describe the feature.

Address outstanding PR comments issues from the [PR](https://github.com/Azure/azure-sdk-for-net/pull/33691#pullrequestreview-1277920588) introducing feedback from the board meeting.

Links to the comments:
- [x] https://github.com/Azure/azure-sdk-for-net/pull/33691#discussion_r1092410332
- [x] https://github.com/Azure/azure-sdk-for-net/pull/33691#discussion_r1092413439 ⚠️
- [x] https://github.com/Azure/azure-sdk-for-net/pull/33691#discussion_r1092424635 ⚠️
- [x] https://github.com/Azure/azure-sdk-for-net/pull/33691#discussion_r1092425256 ⚠️
- [x] https://github.com/Azure/azure-sdk-for-net/pull/33691#discussion_r1092425781 ⚠️
- [x] https://github.com/Azure/azure-sdk-for-net/pull/33691#discussion_r1092429140
- [x] https://github.com/Azure/azure-sdk-for-net/pull/33691#discussion_r1092473460
- [x] https://github.com/Azure/azure-sdk-for-net/pull/33691#discussion_r1092476061

**Comment by m-nash** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/33691#discussion_r1088385129

**Comment by jpalvarezl** [comment]
We forked this comment to a separate issue: https://github.com/Azure/azure-sdk-for-net/issues/33815
