### ISSUE TITLE
[BUG] ApiManagement - outdated generated code from rest specification - missing bug fixes

### ISSUE THREAD

**Issue by AdamCoulterOz** [Azure/azure-sdk-for-net#33794]
### Library name and version

Azure.ResourceManager.ApiManagement 1.0.0

### Describe the bug

Outdated generated code from rest specification - missing bug fixes.

There are a few updates in the API Management Open API Specifications to fix the `createOrUpdate` operations for both `ContentType` and `ContentItem` types, where they weren't updating the content. Can I ask for the AutoRest Code Generator be re-run for the Azure.ResourceManager.ApiManagement nuget package? Is there a process to trigger this when the underlying rest specification is updated for the given package?

Here is the bug which was fixed in the underlying rest API spec:

https://github.com/Azure/azure-rest-api-specs/issues/21849

I can see there is something linked to updating this here?

https://github.com/Azure/azure-rest-api-specs/pull/21875#issuecomment-1348104732
https://apiview.dev/Assemblies/Review/54e0f7a832694ff4abbc5119865b73b5

I don't have access to look at that though.

### Expected behavior

N/A

### Actual behavior

N/A

### Reproduction Steps

N/A

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Thanks for reaching out to us, we will start arranging for the upgrade of ApiManagement.

**Comment by live1206** [comment]
@AdamCoulterOz The SDK has been re-generated, please let us know if you have further problem on this.
