### ISSUE TITLE
Azure Resource Manager libraries for .NET references a deprecated version of the SDK.

### ISSUE THREAD

**Issue by tinodo** [Azure/azure-sdk-for-net#33814]
The page [Azure Resource Manager libraries for .NET](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resource-manager?view=azure-dotnet) references the [Microsoft.Azure.Management.ResourceManager.Fluent](https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceManager.Fluent) SDK. This package is **deprecated** and replaced with [Azure.ResourceManager](https://www.nuget.org/packages/Azure.ResourceManager/).

As per notes on the nuget page:
_This package will continue to be supported for a period of time and will stop receiving support based on the dates listed on [https://aka.ms/azsdk/deprecated](https://aka.ms/azsdk/deprecated)._

Can this documentation please be updated to use the newer, supported, version of the SDK?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 553fc3f5-7bb0-db05-00e8-e18c550c2869
* Version Independent ID: 219ec4a2-b185-2c5b-0174-c8577f3f894e
* Content: [Azure Resource Manager SDK for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resource-manager?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/resource-manager.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/resource-manager.md)
* Service: **resourcemanager**
* GitHub Login: @pallavit
* Microsoft Alias: **pallavit**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Fixed
