### ISSUE TITLE
Need to disable some tests in ExpressRoute.Tests.csproj

### ISSUE THREAD

**Issue by vinayada1** [Azure/azure-sdk-for-net#3382]
Tests need re-recording but the .csproj does not compile and cannot re-record

**Comment by shahabhijeet** [comment]
@vinayada1 please close if you are not planning to fix this issue.

**Comment by EvgenyAgafonchikov** [comment]
@vinayada1, could you please check if this need to be closed?
AFAIK requirement to add SDK tests was removed some time ago

**Comment by vinayada1** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/3382

**Comment by vinayada1** [comment]
These were legacy issues that we found with our Hydra SDK. However, since that is frozen for any further development, I think these can be closed.

**Comment by dsgouda** [comment]
Thanks @vinayada1
