### ISSUE TITLE
[BUG] EventHubClient .NET - Not refreshing token

### ISSUE THREAD

**Issue by yaronpri** [Azure/azure-sdk-for-net#33845]
### Library name and version

Microsoft.Azure.EventHubs 4.3.2

### Describe the bug

When creating EventHubClient with CreateWithTokenProvider, the callback function which was provided is not used when the token is going to expired, causing a failure to call the client method like: GetRuntimeInformationAsync.

In order to workaround this issue, you need to implement the mechanism of calculating the token expiration and creating NEW eventhub client before expiration.

It's expected that the SDK will handle this.

### Expected behavior

Same EventHubClient will keep working and the refresh token will be done in the background by the SDK

### Actual behavior

You need to implement the mechanism of calculation of expiring token and must create a new EventHubClient before expired

### Reproduction Steps

1. Create a EventHubclient with CreateWothTokenProvider 
2 Create a while true loop - in the loop use the EventHubClient.GetRuntimeInformationAsync method
3. After a while (can be hours), depends on the token expiration, you will get exception. 

### Environment

Any environment

**Comment by jsquire** [comment]
Hi @yaronpri.  Please be aware that the `Microsoft.Azure.EventHubs` package is deprecated and no longer under active development.  We do not recommended using it for new development.   The `Azure.Messaging.EventHubs` package is the current generation Event Hubs client library.

I've triaged this to the support team who will make the determination on whether this issue meets the criteria for a critical fix.

**Comment by navba-MSFT** [comment]
Adding Service team to comment on the supportability aspect and fix for a deprecated library.

**Comment by jsquire** [comment]
Due to the `Microsoft.Azure.EventHubs` package being deprecated, only critical fixes are being made.   This has been confirmed as not meeting that bar.   Migration to the `Azure.Messaging.EventHubs` package is the recommended mitigation.
