### ISSUE TITLE
Add Azure Application Insights support to Fluent API (aka Monitor)

### ISSUE THREAD

**Issue by olegburov** [Azure/azure-sdk-for-net#3384]
It would be handy if [Azure Management Libraries for .NET](https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/) (aka Fluent API) supported [Azure Application Insights](https://azure.microsoft.com/en-us/services/application-insights/) service.

**Comment by fbertilsson** [comment]
Second that :)

**Comment by tomkerkhove** [comment]
Is there an update on this @hovsepm?

**Comment by martinsawicki** [comment]
something we've been investigating..

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#10

**Comment by olegburov** [comment]
@hovsepm It's unclear if you're going to add this feature only to Java lib or both Java and .NET libs. I need it in .NET first.

**Comment by tomkerkhove** [comment]
Wow that was quick. I'm with @olegburov here and doesn't really make sense if it would only be supported in the Java SDK..

**Comment by veikkoeeva** [comment]
This does not appear to be in the .NET fluent library. Is this an oversight? @hovsepm, do you know?

**Comment by hovsepm** [comment]
@veikkoeeva it seems so. Please add the request for App Insights for Fluent in https://github.com/Azure/azure-libraries-for-net repo since we moved there long time ago.

**Comment by tomkerkhove** [comment]
Looks like @veikkoeeva beat me to it, thanks!
