### ISSUE TITLE
ServiceBusReceiver stucks

### ISSUE THREAD

**Issue by verdysh** [Azure/azure-sdk-for-net#33851]
### Library name and version

Azure.Messaging.ServiceBus 7.8.1

### Query/Question

I read messages through ServiceBusReceiver:

`var messages = await _receiver.ReceiveMessagesAsync(_config.MaxMessages, _config.MaxWaitTimeout);`

I want to read messages by batches and you can see above that I use relevant parameters while ReceiveMessagesAsync call. In my case "MaxMessages" = 500, "MaxWaitTimeout" = "00:00:03".

It works until some time. Few times a receiver has stuck there. I have a log next to the line above:
```
_logger.LogDebug(
	"Topic {topic}, subscription {subscription}, have read {count} messages, maxMessages {maxMessages}; it took {totalMilliseconds}, maxWaitTimeout {maxWaitTimeout}",
	_config.Topic, _subscription, messages.Count, _config.MaxMessages, stopwatch.Elapsed.TotalMilliseconds, _config.MaxWaitTimeout
);
```

When the receiver is stuck I see in the logs that it received 0 messages for 3 seconds, although there are messages in the subscription. Here is a graph of Active messages in topic:

![image](https://user-images.githubusercontent.com/21305997/216289877-3e74d2eb-6041-40d4-85a8-68441e978caf.png)

You can see, starting from some point the number of messages is increased. Only after I restart the app, receiver starts to receive messages. From the logs and other metrics I don't see any anomalies.

What can cause this stuck and how can I fix it?

### Environment

Azure AppService on Linux

Host:
  Version:      6.0.12
  Architecture: x64
  Commit:       02e45a41b7

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by jsquire** [comment]
Hi @verdysh.  Thank you for reaching out and we regret that you're experiencing difficulties.   The 3 seconds that you've specified as the wait time is very low and likely the cause of the behavior that you're seeing.   That you're seeing 0 messages returned indicates that client was unable to stream any messages in before your specified wait time was exhausted.   

The time needed to do so will vary based on a number of factors including the host environment, network conditions, message size, Service Bus SKU, and whether retries were needed.  On the first service operation and when error recovery is needed, the client will also need to establish a connection to Service Bus, create a link, and perform authorization before it can signal that it would like to stream in messages.  

I would suggest testing with different wait times that allow for longer periods and see what works best in your environment.  If you have unusual needs for a very small wait time such as this, you may want to consider setting a [PrefetchCount](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusreceiver.prefetchcount?view=azure-dotnet) or performing a service operation such as peeking a message periodically in the background to help keep the connection active.

If you'd like to confirm read activity and understand the client's perspective, I'd suggest gathering [SDK logs](https://github.com/Azure/azure-sdk-faor-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging) at the verbose level for a +/- 5-minute time slice around the behavior.   That will show us any background activities, retries, and what the service return was.

**Comment by jsquire** [comment]
I need to make one correction to my initial response - we're not using the wait time for connection management; I traced the wrong variable.  

> I believe it is used only while receiving data. 

It is passed as a timeout value to the AMQP link when requesting messages.   Internally, the transport library manages the state of that link and will reset/recover if the link state requires doing so to allow credits to be placed on the link.

> Also, I expect there will be some errors/warnings in the logs if something happens that requires the receiver to be restored, but I don't see anything in my logs. Am I incorrect?

Retries are implicit; you would see them surface in the SDK logs but your code would not see an exception unless all retries have been exhausted.   So the answer to this depends on how you're capturing your logs.

To understand what you're seeing, we'll need the slice of SDK logs that I asked for.

**Comment by verdysh** [comment]
> To understand what you're seeing, we'll need the slice of SDK logs that I asked for.

I've looked at documentation you pointed at. As I understand I can do something like this but using ILogger object to write data into ApplicationInsights:

```
using AzureEventSourceListener listener = new AzureEventSourceListener(
    (args, message) => Console.WriteLine("[{0:HH:mm:ss:fff}][{1}] {2}", DateTimeOffset.Now, args.Level, message),
    level: EventLevel.Verbose);
```

Could you tell me please what exactly I should log (how should I filter logs) in order to have little amount of logs as possible but in the same time having all the needed logs for investigation this issue. I need to do that because I have 1Gb limit per day for logs in ApplicationInsights and I'm worry if I start writing all the logs I will exceed this limit very fast.

Also docs says:

> Logging in ASP.NET Core applications
> If your are using Azure SDK libraries in ASP.NET Core application consider using the Microsoft.Extensions.Azure package that provides integration with Microsoft.Extensions.Logging library. See [Microsoft.Extensions.Azure readme](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Microsoft.Extensions.Azure/README.md) for more details.

I've looked there too. Bu I didn't find example how to use it for logging of AzureSDK package.

**Comment by jsquire** [comment]
We need only a 5 minute slice of logs, and it would be best if we could collect all Verbose logs for that interval so that we can understand the client perspective.  If you're worried about volume in AppInsights, I'd suggest disposing the listener after that time, which will stop log collection even if your application is still running.   If you feel like you must filter, the most important things we're after are:

- All warnings
- All errors
- Id: 7 (ReceiveMessageStart)
- Id: 8 (ReceiveMessageComplete)
- Id: 9 (ReceiveMessageError)
- Id: 37 (LinkStateLost)
- Id: 38 (ReceiveLinkClosed)
- Id: 39 (AmqpLinkRefreshStart)
- Id: 40 (AmqpLinkRefreshComplete)
- Id: 41 (AmqpLinkRefreshError)
- Id: 43 (RunOperationError)
- Id: 101 (ManagementLinkClosed)
- Id: 114 (RunOperationVerboseError)
- 

When using the Extensions package, the listener is automatically attached for all Azure SDK libraries and forwards to the `ILogger` instance.   To set forwarding without using the client registration for DI, you'd so something like:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    // ... <SNIP> ...
    services.AddAzureClientsCore(enableLogForwarding: true);
    // ... <SNIP> ...
}
```

**Comment by verdysh** [comment]
@jsquire will the logs be useful for investigation if I turn them on and collect after receiver is already stuck? I thought I need to collect the logs all the time in order to see what happened at the exact moment when receiver starts to stuck.

**Comment by jsquire** [comment]
It should be good for getting started.  My working assumption is that the receive loop is still in a good state, it's not getting messages returned.   We want to see what's eating up the time.

One thing that I should have noticed earlier - you're using a very old version of the library that is missing some key fixes.  On note is a bump to our AMPQ transport dependency which contains a fix that resolves a connection getting into an undetectable bad state.  

Before we capture logs, we should bump the version of the Service Bus package that you're using to the latest.

**Comment by verdysh** [comment]
I've updated Azure.Messaging.ServiceBus to version 7.12.0 and created the next logger class:

```
public class AzureEventSourceLogger
{
	private readonly int[] _eventIds = new[] { 7, 8, 9, 37, 38, 39, 40, 41, 43, 101, 114 };

	private readonly ILogger<AzureEventSourceLogger> _logger;
	private AzureEventSourceListener _azureEventSourceListener;

	public AzureEventSourceLogger(ILogger<AzureEventSourceLogger> logger)
	{
		_logger = logger;
		TurnOn();
	}

	public void TurnOn()
	{
		if (_azureEventSourceListener is not null)
			return;

		_azureEventSourceListener = new AzureEventSourceListener((args, message) =>
		{
			if (!(args.Level == EventLevel.Error || args.Level == EventLevel.Warning))
				return;

			if (!_eventIds.Contains(args.EventId))
				return;

			if(args.Level == EventLevel.Error)
				_logger.LogError(message);
			else if (args.Level == EventLevel.Warning)
				_logger.LogWarning(message);

		}, EventLevel.LogAlways);
	}

	public void TurnOff()
	{
		if (_azureEventSourceListener is null)
			return;

		_azureEventSourceListener.Dispose();
		_azureEventSourceListener = null;
	}
}
```

I will watch and let you know if the receiver gets stuck or if I see anything interesting in the logs.

Thank you for your time!

**Comment by verdysh** [comment]
Now I'm observing, this issue had occurred once per few weeks.

**Comment by JoshLove-msft** [comment]
As an FYI, there is a recent service fix that is being rolled out over the next few weeks that may address this issue.

**Comment by jsquire** [comment]
Removing stale tagging; log capture is still ongoing for an intermittent issue.

**Comment by verdysh** [comment]
Looking at logs there are some errors and warnings. Most are warnings, only a little are errors. Since I updated the package, there has been no processing stuck. I continue to observe.

**Comment by jsquire** [comment]
Thanks for the update, @verdysh.   We'll leave this in a pending state for a bit longer to see if things repro.

**Comment by verdysh** [comment]
Since I updated the library it works fine!

@jsquire thanks for your help!
@JoshLove-msft thanks for your answer too! Maybe it was fixed by what you said.

But maybe it hasn't been fixed yet and it is waiting for me to close the issue to appear and spoil my mood. 😁
Anyway, thanks for the help! I'm closing the issue, if something breaks again I'll open this one or create new one.
