### ISSUE TITLE
[QUERY] How to create SecurityInsightsScheduledAlertRule with CustomDetails?

### ISSUE THREAD

**Issue by amih90** [Azure/azure-sdk-for-net#33852]
### Library name and version

Azure.ResourceManager.SecurityInsights Version="1.0.0"

### Query/Question

Trying to create Azure Sentinel SecurityInsightsScheduledAlertRule (Azure.ResourceManager.SecurityInsights.Models.SecurityInsightsScheduledAlertRule) via dotnet sdk.
Is there any better option rather than reflection to set `customDetails` property? why it has no setter?
Currently, `customDetails` is being set only inside the constructor of SecurityInsightsScheduledAlertRule,
`CustomDetails = new ChangeTrackingDictionary<string, string>();`
and the setter `public IDictionary<string, string> CustomDetails { get; }`

My full example is:
```
OperationalInsightsWorkspaceSecurityInsightsResource operationalInsightsWorkspaceSecurityInsightsResource = armClient.GetOperationalInsightsWorkspaceSecurityInsightsResource(resourceIdentifier);
SecurityInsightsAlertRuleCollection securityInsightsAlertRuleCollection = operationalInsightsWorkspaceSecurityInsightsResource.GetSecurityInsightsAlertRules();

string ruleId = Guid.NewGuid().ToString();

SecurityInsightsScheduledAlertRule securityInsightsScheduledAlertRule = new SecurityInsightsScheduledAlertRule()
{
    Query = "MyTable\r\n| where TimeGenerated > ago(1d) \r\n| project Name",
    QueryFrequency = TimeSpan.Parse("00:05:00"),
    QueryPeriod = TimeSpan.Parse("05:00:00"),
    DisplayName = $"My Rule {ruleId}",
    Description = "",
    Severity = SecurityInsightsAlertSeverity.High,
    TriggerOperator = SecurityInsightsAlertRuleTriggerOperator.GreaterThan,
    TriggerThreshold = 0,
    EventGroupingAggregationKind = EventGroupingAggregationKind.SingleAlert,
    IsEnabled = true,
    SuppressionDuration = TimeSpan.Parse("05:00:00"),
    IsSuppressionEnabled = false,
    AlertDetailsOverride = new SecurityInsightsAlertDetailsOverride()
    {
        AlertDisplayNameFormat = "My Alert {{Name}}",
        AlertDescriptionFormat = "Alert generated by Analytics scheduled rule"
    }
};
var customDetailsProperty = typeof(SecurityInsightsScheduledAlertRule).GetField("<CustomDetails>k__BackingField", BindingFlags.Instance | BindingFlags.NonPublic);
customDetailsProperty.SetValue(securityInsightsScheduledAlertRule, new Dictionary<string, string>()
{
    { "Name",  "Name" }
});


var newRule = await securityInsightsAlertRuleCollection.CreateOrUpdateAsync(
            waitUntil: WaitUntil.Completed,
            ruleId: ruleId,
            data: securityInsightsScheduledAlertRule);
```

### Environment

Windows

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hi @amih90, we don't provide setter for the collection property according to [framework design guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/guidelines-for-collections#collection-properties-and-return-values), you can use `alertRule.CustomDetails.Add()` to add the new contents. This [link](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/object-and-collection-initializers#object-initializers-with-collection-read-only-property-initialization) provides more details about how to initialize the collection read-only property.
