### ISSUE TITLE
Simplify the initial development experience for the OpenTelemetry SDK

### ISSUE THREAD

**Issue by samsp-msft** [Azure/azure-sdk-for-net#33865]
### Library name

Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

The patterns to use this SDK compared to the previous .NET SDK are orders of magnitude more complex than before:

- You need to configure each type of exporter explicitly
- The builder pattern is using objects across a range of libraries/namespaces which are not included by default
- The current API requires explicit setting of all properties

I would suggest the following changes:

- Create a crawl/walk/run scenario focus for the APIs. The current patterns probably best fit into the "run" scenario.
  - "crawl" should be something like:

 ```c#
 builder.Services.AddApplicationInsightsOpenTelemetry();
```

   Which will
    - Use the environment for the connection string
    - Enable Logs, Metrics & Distributed Tracing
    - Include platform defaults for what platform metrics to include.
 
  - "walk" includes more customization options, without needing to delve into all the open telemetry builder:

```c#
 builder.Services.AddApplicationInsightsOpenTelemetry(options =>
{
  options.ConnectionString = app.Configuration["APPLICATIONINSIGHTS_CONNECTION_STRING"];
  options.CollectLogs = true;
  options.CollectMetrics = false;
  options.CollectFromNamespacePrefix("mynamespace");
  options.SendDebugOutputToConsole = true;
}
```

  The options are all optional, and will use the same defaults as the crawl scenario, but it enables you to customize what is necessary, with good intellisense completion because it has a strongly typed options object. 

  The `CollectFromNamespacePrefix` is to make collection easier for larger projects, so you don't have to enumerate every `Metric` or `ActivitySource` in the initialization, and can use a namespace prefix to collect all the data. It will encourage the best practice of using namespace names for these identifiers.

- "Run" uses the open telemetry sdk builder pattern

- As this is for use with application insights, use the environment variables already supplied by the primary Azure PAAS services to supply default information such as the connection string and resource attributes for distributed tracing.
- Add references to all the relevant open telemetry packages as part of your sdk. I shouldn't have to go delving through nuget to find the different packages that provide common functionality like console output, or enrichments.

**Comment by rajkumar-rangaraj** [comment]
Initial work is in progress on #33762

**Comment by TimothyMothra** [comment]
I think this issue can be closed. We've worked closely with Sam in building both the Exporter and Distro.
