### ISSUE TITLE
[QUERY] Azure App Configuration token error

### ISSUE THREAD

**Issue by joshdanko** [Azure/azure-sdk-for-net#33869]
### Library name and version

Azure.Identity 1.8.0

### Query/Question

I have created an issue in the Azure App Configuration github.  However, since the stack trace mentioned OnChangeTokenRegistration i figured I would post it here to see if anyone else has had a similar issue.  We have only seen this happen one time in a few months, but it was an unrecoverable error that required a restart of the pod. 

Cannot create instance of type 'System.String' because it is missing a public parameterless constructor.

Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.CreateInstance","level":0,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance","level":1,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindDictionary","level":2,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance","level":3,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty","level":4,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar","level":5,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance","level":6,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindProperty","level":7,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindNonScalar","level":8,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance","level":9,"line":0}
{"assembly":"Microsoft.Extensions.Configuration.Binder, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Configuration.ConfigurationBinder.Bind","level":10,"line":0}
{"assembly":"Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Options.OptionsFactory`1.Create","level":11,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Lazy`1.ViaFactory","level":12,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Lazy`1.ExecutionAndPublication","level":13,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Lazy`1.CreateValue","level":14,"line":0}
{"assembly":"Microsoft.Extensions.Options, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Options.OptionsMonitor`1.InvokeChanged","level":15,"line":0}
{"assembly":"Microsoft.Extensions.Primitives, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60","method":"Microsoft.Extensions.Primitives.ChangeToken+ChangeTokenRegistration`1.OnChangeTokenFired","level":16,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Threading.ExecutionContext.RunInternal","level":17,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw","level":18,"line":0}
{"assembly":"System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","method":"System.Threading.CancellationTokenSource.ExecuteCallbackHandlers","level":19,"line":0}

### Environment

Azure AKS service:
- .net 6 pod
- Azure App Configuration AspNetCore extensions v 5.2

Connecting to Azure App Configuration via DefaultAzureCredential with Managed IDentity using Workload Identity in AKS.

**Comment by jsquire** [comment]
Hi @joshdanko.   Thank you for reaching out and we regret that you're experiencing difficulties.   Can you help us understand why you believe this error is associated with Azure.Identity?   In looking at the stack trace, I don't see anything that references to Azure Identity or other Azure SDK packages.

**Comment by joshdanko** [comment]
Whoops, I misread the stacktrace and assumed ChangeTokenRegistration was related to identity, but it's not.  Appears to be a serialization issue within the App Configuration sdk.  Sorry, I will close this.

**Comment by jsquire** [comment]
No worries;  as requested, I'll close this out for now.
