### ISSUE TITLE
Change default BuildSnippets to check all snippets are used

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#33877]
The CI pipeline can check that all snippets are used to make sure people don't accidentally forget to use any they defined (and also makes sure any referenced are defined), but the default is turned off currently. Many SDKs have already opted in to do this check during the Analyze job, but I think we should enable that by default.

Running `eng/scripts/Update-Snippets.ps1 * -StrictMode`, I find the following SDKs still have some unreferenced snippets:

- [ ] communication
- [ ] dns
- [ ] formrecognizer
- [ ] iot
- [ ] servicebus

We should make sure that a new instance of a DPG template does not run afoul of this error as well, but given the command above didn't find any issues it should be fine. We should create an instance though and double check.

Client library authors should run `Update-Snippets.ps1 {ServiceDirectory}` to check compliance, and to make sure any README or sample markdowns are properly updated (which the Analyze step will also do or fail).

Also see related snippet clean-up issue #20431

**Comment by heaths** [comment]
If we do change the default, we can modify each of these service directories' _ci.yml_ files to pass `BuildSnippet: false`. See https://github.com/Azure/azure-sdk-for-net/blob/269268d85446e562a97b6c850a2e6e16f4825037/sdk/keyvault/ci.yml#L32 for an example. We should also go through and get rid of such lines so just so it's more obvious we check snippets by default and isn't something you need to opt into.

Also /cc @pallavit @jsquire

**Comment by m-nash** [comment]
I would be a fan of turning this on by default.  Today I have to manually check these things (didn't know about the opt in flag) and its easy to miss them.
