### ISSUE TITLE
App Config SDK Cannot Set Tags on ConfigurationSetting

### ISSUE THREAD

**Issue by KapteinBabbalas** [Azure/azure-sdk-for-net#33885]
https://github.com/Azure/azure-sdk-for-net/blob/25b8cd13eed87fd6810723a45831504e7a048f37/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationSetting.cs#L116

In the REST api it is possible to set tags, but seems to be read only in the SDK. Can we fix this?

**Comment by jsquire** [comment]
The Azure SDK conventions do not allow for settable collection properties, but a default collection is populated when the setting is created and may be mutated.    Tags can be set by adding them to the set in the following ways:

```csharp
// Set the property value directly.
var setting = new ConfigurationSetting("someKey", "someValue");
setting.Tags.Add("tagKey", "tagValue");

// Set via initializer syntax.
var setting = new ConfigurationSetting("someKey", "someValue")
{
    Tags = 
    {
        { "tagKey", "tagValue" },
        { "tagTwo", "tagValueTwo" }
    }
};
```
