### ISSUE TITLE
Document Summarization : Errors encountered 

### ISSUE THREAD

**Issue by yuvrajharsha** [Azure/azure-sdk-for-net#33886]
- **Package Name**: 
- **Package Version**: 
- **Operating System**: 
- **.NET runtime version**: 

[Enter feedback here]
Hello, 
I installed VS 17.4.4 for mac and as per instructions, given in the following link for 'Document Summarization', I ran the given C# code but encountered following 8 errors
https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/summarization/quickstart?tabs=document-summarization&pivots=programming-language-csharp
  

/Program.cs(17,17): Error CS0117: 'TextAnalyticsActions' does not contain a definition for 'ExtractSummaryActions' (CS0117) (Summarisation)
/Program.cs(50,50): Error CS0246: The type or namespace name 'ExtractSummaryAction' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Summarisation)
/Program.cs(80,80): Error CS0246: The type or namespace name 'ExtractSummaryAction' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Summarisation)
/Program.cs(37,37): Error CS0246: The type or namespace name 'ExtractSummaryActionResult' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Summarisation)
/Program.cs(98,98): Error CS1061: 'AnalyzeActionsResult' does not contain a definition for 'ExtractSummaryResults' and no accessible extension method 'ExtractSummaryResults' accepting a first argument of type 'AnalyzeActionsResult' could be found (are you missing a using directive or an assembly reference?) (CS1061) (Summarisation)
/Program.cs(26,26): Error CS0246: The type or namespace name 'ExtractSummaryActionResult' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Summarisation)
/Program.cs(30,30): Error CS0246: The type or namespace name 'ExtractSummaryResult' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Summarisation)
/Program.cs(34,34): Error CS0246: The type or namespace name 'SummarySentence' could not be found (are you missing a using directive or an assembly reference?) (CS0246) (Summarisation)

Could you please help me run the example code for Document Summarization. Looking forward to your support. Thank you.

Best regards, 

Yuvraj Harsha 

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.

Language Quickstart Feedback
* Content: [Quickstart: using document summarization and conversation summarization (preview) - Azure Cognitive Services](https://learn.microsoft.com/azure/cognitive-services/language-service/summarization/quickstart?pivots=programming-language-csharp)
* Content Source: [articles/cognitive-services/language-service/summarization/quickstart.md](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/cognitive-services/language-service/summarization/quickstart.md)
* Section: **Code-example**
* Service: **cognitive-services**
* Sub-service: **language-service**

**Comment by jsquire** [comment]
To ensure that the article author can be engaged to assist, this issue has been transferred to the Microsoft Docs repository as [#104755](https://github.com/MicrosoftDocs/azure-docs/issues/104755).
