### ISSUE TITLE
[QUERY] EventHubConsumerClient thread safety

### ISSUE THREAD

**Issue by dddat1017** [Azure/azure-sdk-for-net#33883]
### Library name and version

Azure.Messaging.EventHubs.Consumer

### Query/Question

Is EventHubConsumerClient thread-safe?

Does each thread need its own client?

Currently we use a single consumer which is being called by multiple threads. The documentation here https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.consumer.eventhubconsumerclient?view=azure-dotnet does not really mention anything about this so I’d like to confirm.

**Comment by jsquire** [comment]
Hi @dddat1017.  Thank you for reaching out.  Thread safety for the Event Hubs client library is discussed in the [Overview](https://learn.microsoft.com/dotnet/api/overview/azure/messaging.eventhubs-readme?view=azure-dotnet#thread-safety) and applies to each of the Event Hubs client types, including the consumer.   It states:

> ### Thread safety
>
> We guarantee that all client instance methods are thread-safe and independent of each other ([guideline](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-service-methods-thread-safety)). This ensures that the recommendation of reusing client instances is always safe, even across threads. 
>
> The data model types, such as `EventData` and `EventDataBatch` are not thread-safe.  They should not be shared across threads nor used concurrently with client methods.

The same guidance applies to types across the current generation of Azure SDK packages, as discussed in [Thread safety and client lifetime management for Azure SDK objects](https://learn.microsoft.com/dotnet/azure/sdk/thread-safety).   Further discussion and examples can be found in [Lifetime management for Azure SDK .NET clients
](https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/).

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.

**Comment by dddat1017** [comment]
/unresolve

Thank you for the prompt response! I did have one more question if you don't mind.

I can see here https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas#basic-vs-standard-vs-premium-vs-dedicated-tiers that the limit on "number of brokered connections per namespace" for standard tier is 5000. Does this roughly translate to "the amount of calls to read or send events at any point in time is capped at 5000"? I'm asking because I'd like to understand what is a good number of threads I should allocate to call the consumer client to read from the event hub. Thanks again!
