### ISSUE TITLE
[QUERY] ServiceBusSender Substitute is not working in test cases

### ISSUE THREAD

**Issue by Jyothsna425** [Azure/azure-sdk-for-net#33896]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

I have recently migrated azure functions to .NET 6 and also replaced servicebus package to azure.messaging.servicebus by removing deprecated ones.

After using new package of service bus Functionapp works just like before but my testcases are failing. We are using Nsubstitute for testing .I have substituted ServiceBusSender and tried to receive calls that reached sendmessagesasync.

Code used to send messages is :

public async Task Run([TimerTrigger("%Schedule%"
            #if DEBUG
                ,RunOnStartup = true
            #endif
            )] TimerInfo timer, ILogger logger)
        {
       // some code to retrieve messages from httpclient
       sender = _serviceBusClient.CreateSender(topicName);
       await sender.SendMessagesAsync(messages);
}

Here i want to check received messages in my test cases

expected: it should return number of calls made to method
actual : No call matching

Error:

**NSubstitute.Exceptions.ReceivedCallsException : Expected to receive a call matching:
	SendMessagesAsync()
Actually received no matching calls.**

Is mocking/faking is allowed on servicebussender ?

**Comment by jsquire** [comment]
Hi @Jyothsna425.  Thank you for reaching out and we regret that you're experiencing difficulties.   There's nothing in your code that appears to be mocking, so I'm unable to offer specific thoughts in this case.   Each of the Service Bus clients is mockable, including the sender.   An example of doing so when sending messages can be found [in our mocking sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample15_MockingClientTypes.md#sending-messages-to-a-queue), which also covers many of the other common usage scenarios as well.

I've left some additional context around our approach to testability below.  I'm going to mark this as addressed, but please feel free to use the "`/unresolve`" command should you wish to discuss further.

## Additional context

Support for mocking and unit testing is one of the core goals of the new Azure SDKs, and the details of the approach that we use are discussed in the [Azure SDK Design Guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking).  Each of the public members of the client types are `virtual` or settable, the class is not sealed, and a parameterless constructor is available to ensure that it is usable with a mocking framework such as Moq or FakeItEasy.  You should be able to mock any client using the same approach that you prefer for other types, whether with a mocking framework or inheriting from the class and creating your own mock type, using the model factory to simulate behavior.

For model types that are returned by service operations, a factory class exists to enable creating them for testing.  In the case of `Service Bus`, the [ServiceBusModelFactory](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.servicebusmodelfactory?view=azure-dotnet) would be the place to look.

For more discussion and general detail around unit testing and mocking the Azure SDKs, I'd recommend [this](https://devblogs.microsoft.com/azure-sdk/unit-testing-and-mocking/) post from the Azure SDK blog.

**Comment by Jyothsna425** [comment]
This did not resolve my issue ... I am particularly look whether SendMessagesAsync method has received any call or not after faking it.
Here is my code for testing:

serviceBusSender = Substitute.For<ServiceBusSender>();
//iam sending some real messages to servicebusender
 await serviceBusSender.Received()
                .SendMessagesAsync(Arg.Is<IList<ServiceBusMessage>>(messages))

whenever i run this piece of code i get no call is made

**Comment by jsquire** [comment]
Unfortunately, NSubstitute is a third-party library and I cannot speak to how it works nor what expectations it makes.  I can only confirm the design and approach for mocking in the Azure SDK.   Since it seems that NSubstitute is not working as you expect, I'd suggest engaging the NSubstitue support process for further assistance.
