### ISSUE TITLE
KeyVaultManagementClient.Vaults.ListByResourceGroup() returns only 5 vaults in the resource group

### ISSUE THREAD

**Issue by PanzerkampfwagenIII** [Azure/azure-sdk-for-net#3389]
When I try `KeyVaultManagementClient.Vaults.ListByResourceGroup(RESOURCEGROUP)`, it returns only 5 vaults, not sure if this problem only applies to Azure China which I am using.

**Comment by hovsepm** [comment]
@PanzerkampfwagenIII Please provide package nuget ID and version that you use.

**Comment by PanzerkampfwagenIII** [comment]
@hovsepm  thanks for the reply, the nuget package is **Microsoft.Azure.Management.KeyVault 2.3.0-preview**, I have also tried some older versions and got the same result. I have also tried `KeyVaultManagementClient.Vaults.ListByResourceGroup(RESOURCEGROUP, TOP)` but it returns only 5 as well. What I can do is now using `KeyVaultManagementClient.Vaults.List()` to get all vaults but I need actually only the vaults in a particular resource group.

**Comment by hovsepm** [comment]
@pomortaz could you help to investigate?

**Comment by pomortaz** [comment]
@RandalliLama can you please take a look at this issue?

**Comment by RandalliLama** [comment]
@PanzerkampfwagenIII To enumerate all of your vaults you need to use the ListByResourceGroupNext function.  See below for an example.

```cs        
       private static List<Vault> GetAllVaults(IKeyVaultManagementClient client)
        {
            var page = client.Vaults.ListByResourceGroup(resourceGroupName);
            var vaults = page.ToList();
            var nextLink = page.NextPageLink;
            while (!string.IsNullOrEmpty(nextLink))
            {
                page = client.Vaults.ListByResourceGroupNext(nextLink);
                vaults.AddRange(page.ToList());
                nextLink = page.NextPageLink;
            }

            return vaults;
        }
```

**Comment by PanzerkampfwagenIII** [comment]
@all Thanks for your help all, much appreciated, the code solves my problem perfectly.
