### ISSUE TITLE
PowerShell does not have overload method of TrackEvent() in Microsoft.ApplicationInsights.TelemetryClient

### ISSUE THREAD

**Issue by MarsWangyang** [Azure/azure-sdk-for-net#33904]
Hi all,

I was trying to use Microsoft.ApplicationInsights.TelemetryClient to send custom event to Application Insights via PowerShell. I did find TrackEvent() has overload method which might could send custom measurements. However, it said `Cannot find an overload for "TrackMetric" and the argument count: "3".` 

this is my code
```PS
$client = [Microsoft.ApplicationInsights.TelemetryClient]::new()
$p = [pscustomobject]@{
    Str = "String Test"
} | ConvertTo-Json 

$measurement = [pscustomobject]@{
    totalTime = 0.33
} | ConvertTo-Json 
$client.TrackEvent("Test Message", $p, $measurement);
```
Is there anyone know how to send the custom measurements data to the application insight?

Tks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 61c28aeb-55c8-b340-f9d1-dcbdd3404bde
* Version Independent ID: 1ff4149b-f85c-a9d7-c8b0-cbb2c5357af2
* Content: [TelemetryClient.TrackEvent Method (Microsoft.ApplicationInsights) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.telemetryclient.trackevent?view=azure-dotnet)
* Content Source: [xml/Microsoft.ApplicationInsights/TelemetryClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ApplicationInsights/TelemetryClient.xml)
* Service: **application-insights**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.ApplicationInsights` package is maintained as [#2744](https://github.com/microsoft/ApplicationInsights-dotnet/issues/2744).
