### ISSUE TITLE
Generate samples in swagger SDK automation pipeline for mgmt plane SDKs

### ISSUE THREAD

**Issue by fengzhou-msft** [Azure/azure-sdk-for-net#33936]
If an SDK has enabled generated samples, the swagger SDK automation pipeline should regenerate the sample with command `dotnet build /t:GenerateTest` to avoid possible build issues due to outdated samples.

**Comment by chunyu3** [comment]
hello @fengzhou-msft , is there any flag/options to indicate that if the SDK has enabled generated sample?

**Comment by fengzhou-msft** [comment]
If there is a `samples/Generated/Samples` folder under the `Azure.ResourceManager.XX` directory, then the generated samples are enabled.

**Comment by chunyu3** [comment]
@ArthurMa1978 mentioned not to enable this now as the CodeGen can't generate samples properly for some RPs
