### ISSUE TITLE
LRO progress checking fails if PATCH returns 201 with location header

### ISSUE THREAD

**Issue by begoldsm** [Azure/azure-sdk-for-net#3395]
PATCH operations can return 201 with a location header or azure async operation response. However, if they do the following code will result in a failure being thrown: https://github.com/Azure/azure-sdk-for-net/blob/vs17Dev/src/SdkCommon/ClientRuntime.Azure/ClientRuntime.Azure/AzureClientExtensions.cs#L443-L445

This needs to be updated to also consider PATCH+201 as a success case

**Comment by AlexGhiondea** [comment]
@begoldsm we realize it's been a long time since you opened this issue. If you still require help, please reply to this issue.

**Comment by begoldsm** [comment]
Hello, and my apologies for the delay! I don’t require any help here, I had opened this issue a few years ago to recommend an improvement to how Patch operations are handled. I am no longer working on the Azure SDK, so this isn’t an issue for me any longer, but it would be good to check and see if this is still an improvement the framework would benefit from before closing it out.

**Comment by AlexGhiondea** [comment]
Thank you. We have a new LRO model in our new libraries that should handle this. Closing the issue now.
