### ISSUE TITLE
net - core - ci pipeline should be able to run some validation for core itself

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#33968]
Certain changes trigger the `net - core - ci` pipeline which tend to build the world (track 2). For example, `/p:ServiceDirectory=*` gets passed but this means, for example, we can't build **just** _sdk/core_'s snippets. Within the same conditional blocks where we effectively change "core" to "*", we should also run these validations with just "core" still.

**Comment by annelo-msft** [comment]
We don't have a good collective memory of what this issue is asking for.  If we run across the same problem in the future, we can either reopen this issue at that point, or open a new one to track the necessary work.  @m-nash FYI.
