### ISSUE TITLE
Some ResourceManagement samples do not compile with `SNIPPET` symbol

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#33967]
We're working on turning on building snippets for all projects by default to make sure all our source from which snippets are created actually build. This was one major reason we started this project a few years ago. When doing so, however, this means some code is invalid when compiled. Consider the following sample, which I see in a few mgmt projects (networking, storage, etc.):

```c#
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#region Snippet:Changelog_New
            using Azure.Identity;
            using Azure.ResourceManager.Compute.Models;
            using Azure.ResourceManager.Network;
            using Azure.ResourceManager.Network.Models;
            using Azure.ResourceManager.Resources;
            using Azure.ResourceManager.Resources.Models;
            using Azure.Core;
            using System;
            using System.Linq;

#if !SNIPPET
using System.Threading.Tasks;
using NUnit.Framework;

namespace Azure.ResourceManager.Compute.Tests.Samples
{
    public class Changelog
    {
        [Test]
        [Ignore("Only verifying that the sample builds")]
        public async Task NewCode()
        {
#endif
            ArmClient armClient = new ArmClient(new DefaultAzureCredential());

            AzureLocation location = AzureLocation.WestUS;
            // Create ResourceGroupResource
            SubscriptionResource subscription = await armClient.GetDefaultSubscriptionAsync();
            ArmOperation<ResourceGroupResource> rgOperation = await subscription.GetResourceGroups().CreateOrUpdateAsync(WaitUntil.Completed, "myResourceGroup", new ResourceGroupData(location));
            ResourceGroupResource resourceGroup = rgOperation.Value;

```

When we pass `/p:DefineConstants=SNIPPET`, part of that source is excluded and now invalid, so the build fails. What we've done in other projects is have separate regions for `using`s and for code. Even in the sample markdown files, we typically call this out as separate sections like you can see [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/cognitivelanguage/Azure.AI.Language.Conversations/README.md#namespaces).

I recommend following a similar approach so code is always compilable regardless of symbols passed.

To test this locally, you can run the following replacing `/p:ServiceDirectory=*` for the actual service directory e.g., "network":

```bash
dotnet build eng/service.proj -warnaserror /t:rebuild /p:DebugType=none /p:SDKType=all /p:ServiceDirectory=* /p:IncludePerf=false /p:IncludeStress=false /p:PublicSign=false /p:Configuration=Release /p:EnableSourceLink=false /p:BuildSnippets=true
```

**Comment by ArcturusZhang** [comment]
This should be fixed now. We are refreshing all the mgmt plane SDKs, no such issues seen until now.
Closing...

**Comment by ArthurMa1978** [comment]
Not fixed all, reopen

**Comment by ArthurMa1978** [comment]
Fixed all bad samples
