### ISSUE TITLE
Docs should call out that Cosmos backed tables do not allow reserved property name `ResourceId` for entities

### ISSUE THREAD

**Issue by manums** [Azure/azure-sdk-for-net#33972]
### Library name and version

Azure.Data.Tables 12.7.0

### Query/Question

Is it possible to create and work on a table entity with **byte[]** or **BinaryData** typed properties using "API for table" (on cosmos db table)? 

It looks like TableClient.AddEntityAsync does not support a TableEntity that has property type as Byte[] or BinaryData. AddEntityAsync returned below exception when I tried to insert an entity with BinaryData or Byte[] properties.

```cs
    /// <summary>
    /// The task entity for asynchronous task execution.
    /// </summary>
    public class TaskEntity : AzureTableEntity
    {
        /// <summary>
        /// Gets or sets the TaskId of the task.
        /// </summary>
        public string TaskId { get; set; }

        /// <summary>
        /// Gets or sets the task name.
        /// </summary>
        public string TaskName { get; set; }

        /// <summary>
        /// Gets or sets checkpoint chunk 1.
        /// </summary>
        public BinaryData Chunk0 { get; set; }

        /// <summary>
        /// Gets or sets checkpoint chunk 2.
        /// </summary>
        public BinaryData Chunk1 { get; set; }
```

```Azure.RequestFailedException: Cannot implicitly convert type 'Newtonsoft.Json.Linq.JObject' to 'string'. An explicit conversion exists (are you missing a cast?)```

Even the UI on azure portal does not allow defining a property to be defined as Binary.

This is a seriously limitation and may block us migrating from Azure table storage to API for tables (cosmos db tables). 

![image](https://user-images.githubusercontent.com/3592179/217400064-af26a5a4-49c5-499d-b280-1c0d7f7334a1.png)

**Comment by manums** [comment]
It looks like issue here is that TaskEntity (table entity ) had a property with name: "ResourceId". and that caused an exception when trying to add task entity .

Renaming ResourceId to "ResourceIdentifier" fixed the issue. I could even get BinaryData\byte[] properties working after renaming the property from ResourceId to ResourceIdentifier.

This simple naming issue took at least few hours to identify. 

This should have been part of some "Api for Table" documentation.


 **"Do not have property ResourceId in your table entity"**! when working with Cosmos DB tables.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
I created this PR to update the documentation. https://github.com/MicrosoftDocs/azure-docs/pull/104993
