### ISSUE TITLE
Azure.Data.Tables.Tests has uncompilable snippets

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#33987]
When passing the `SNIPPET` symbol to build snippets and make sure they are valid, this project yields errors.

You can repro this issue by running:

```bash
dotnet build eng/service.proj -warnaserror /t:rebuild /p:DebugType=none /p:SDKType=all /p:ServiceDirectory=tables /p:IncludePerf=false /p:IncludeStress=false /p:PublicSign=false /p:Configuration=Release /p:EnableSourceLink=false /p:BuildSnippets=true
```

When resolved, please remove the `BuildSnippets: false` line from _sdk/tables/ci.yml_.

See #33969 for more context.

**Comment by christothes** [comment]
fixed in https://github.com/Azure/azure-sdk-for-net/pull/33998

**Comment by heaths** [comment]
I'll revert my change to set `BuildSnippets: false` in #33989. As many pipelines are impacted and as long as that PR takes to validate, I'd like to get that in first and not restart everything.
