### ISSUE TITLE
[FEATURE REQ] Provide a SHA2-supported BlobProperties.ContentHash

### ISSUE THREAD

**Issue by WilliamXieMSFT** [Azure/azure-sdk-for-net#34019]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

The current [ContentHash](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobproperties.contenthash?view=azure-dotnet) property returns an MD5 hash. Unfortunately, our internal code analysis tools flag any usage of MD5 as weak cryptography which requires lengthy exception request processes.

Would it be possible to include a new ContentHash property that uses a SHA2-based hash algorithm?
* System.Security.Cryptography.SHA256.Create()
* System.Security.Cryptography.SHA384.Create()
* System.Security.Cryptography.SHA512.Create()

**Comment by navba-MSFT** [comment]
@WilliamXieMSFT Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@WilliamXieMSFT I tried the below approach and I was able to set the Content-MD5 property on my blob using sha512 algorithm hash.

```
$hash = (Get-FileHash -Algorithm SHA512 -Path "C:\myfolder\test.txt").Hash

# upload the blob to the storage

az storage blob update --account-name MyStorageAccount  --account-key "XXXXXXXXX" --container-name MyContainer 
--name test.txt --content-md5 $hash --debug

```
Could you please let me know if this helps ?

**Comment by WilliamXieMSFT** [comment]
Hi @navba-MSFT, appreciate the reply. The workaround requires having control over uploading the dump file, and forces client apps to have additional logic checking which algorithm is used for the content hash (not to mention confusion since the name of the property mentions MD5).

Would it be possible to have both a `Content-Hash` property as well as a `Content-Hash-Algorithm` property to aid in determining which algorithm was used? 

I believe the Content-MD5 property is auto-generated by Azure Storage, and I'm sure there are historical reasons for this. The concern is that for products to meet FIPS compliance checks, any usage of MD5 will trigger blocking bugs. If there could be a way to set the default to a SHA2 algorithm instead, that would greatly reduce the number of exceptions we must file.

Thanks for the consideration.

**Comment by seanmcc-msft** [comment]
This would require support from the storage service, and is very unlikely to be prioritized.

**Comment by amnguye** [comment]
Hi since this is a storage service request, and not an SDK request we recommend discussing this among the azure support community.

https://azure.microsoft.com/en-us/support/community/

Closing this issue as this is a non-SDK issue.
