### ISSUE TITLE
Many Azure.ResourceManager.* sample projects are missing necessary package references

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#34016]
Related to #33969, many MPG sample projects are lacking references they need to actually build, such as Azure.Identity or NUnit. In fact, the fact they are using NUnit means they should be under the _tests/_ subdirectory (by convention) and have a ".Tests" suffix. See https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/Create_Samples_Guidance.md. While this mentions data plane, I see no reason management plane shouldn't be similar.

Several years ago when many of our samples didn't work or didn't even compile, several of us creating conventions and tools to make sure they are always run (at least with live tests, if not recorded) and built, and from there we get snippets. This convention is also assumed in many build files. For example, right now these source files will get included anytime `IncludeSamples=true IncludeTests=false` is passed to builds (effectively; not exact syntax) because the directories are used to determine what are tests, what are samples, etc. Conversely, all these tests that use NUnit won't get run when running many of these same commands because they are treated like samples and not tests.

As an example, in _sdk\iothub\Azure.ResourceManager.IotHub\samples\Generated\Samples\Sample_EventHubConsumerGroupInfoCollection.cs_:

```c#
using System;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.IotHub;
using Azure.ResourceManager.IotHub.Models;

namespace Azure.ResourceManager.IotHub.Samples
{
    public partial class Sample_EventHubConsumerGroupInfoCollection
    {
        // IotHubResource_ListEventHubConsumerGroups
        [NUnit.Framework.Test]
        [NUnit.Framework.Ignore("Only verifying that the sample builds")]
        public async Task GetAll_IotHubResourceListEventHubConsumerGroups()
// ...
```

Here's the project that contains that sample:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\src\Azure.ResourceManager.IotHub.csproj" />
  </ItemGroup>
</Project>
```

As you can see, there are no `PackageReference` items to _Azure.Identity_ or _NUnit.Framework_.

**Comment by heaths** [comment]
This problem was never caught because the project was never built in a CI when running `dotnet test` which runs `dotnet test eng/service.proj /p:IncludeTests=true ...` because the files are treated as tests. Not even as samples. See _eng/Directory.Common.Build.props_, which includes these selectors:

```xml
  <PropertyGroup>
    <IsMgmtLibrary Condition="'$(IsMgmtLibrary)' == '' and $(MSBuildProjectName.StartsWith('Azure.ResourceManager'))">true</IsMgmtLibrary>
    <IsMgmtSubLibrary Condition="'$(IsMgmtSubLibrary)' == '' and $(MSBuildProjectName.StartsWith('Azure.ResourceManager.'))">true</IsMgmtSubLibrary>

    <MgmtAutorestVersion>3.0.0-beta.20210504.1</MgmtAutorestVersion>

    <!-- Enable documentation for all projects unless explicitly disabled. -->
    <DocumentationFile>$(IntermediateOutputPath)$(TargetFramework)\$(MSBuildProjectName).xml</DocumentationFile>

    <!-- Client in this context is any library that is following the new Azure SDK guidelines -->
    <IsClientLibrary Condition="'$(IsClientLibrary)' == '' and $(MSBuildProjectName.StartsWith('Azure.'))">true</IsClientLibrary>

    <IsTestProject Condition="'$(IsTestProject)' == '' and $(MSBuildProjectName.EndsWith('.Tests'))">true</IsTestProject>
    <IsSamplesProject Condition="'$(IsSamplesProject)' == '' and $(MSBuildProjectName.EndsWith('.Samples'))">true</IsSamplesProject>
    <IsPerfProject Condition="'$(IsPerfProject)' == '' and $(MSBuildProjectName.EndsWith('.Perf'))">true</IsPerfProject>
    <IsStressProject Condition="'$(IsStressProject)' == '' and $(MSBuildProjectName.EndsWith('.Stress'))">true</IsStressProject>
    <IsTestSupportProject Condition="'$(IsTestSupportProject)' == '' and '$(IsTestProject)' != 'true' and ($(MSBuildProjectDirectory.Contains('/tests/')) or $(MSBuildProjectDirectory.Contains('\tests\')))">true</IsTestSupportProject>
    <IsShippingLibrary Condition="'$(IsShippingLibrary)' == '' and '$(IsTestProject)' != 'true' and '$(IsTestSupportProject)' != 'true' and '$(IsPerfProject)' != 'true' and '$(IsSamplesProject)' != 'true' and '$(IsStressProject)' != 'true'">true</IsShippingLibrary>
    <IsShippingClientLibrary Condition="'$(IsClientLibrary)' == 'true' and '$(IsShippingLibrary)' == 'true'">true</IsShippingClientLibrary>
    <TestFrameworkSupportFiles>$(MSBuildThisFileDirectory)/../sdk/core/Azure.Core.TestFramework/src/Shared/*.cs</TestFrameworkSupportFiles>

    <IncludeOperationsSharedSource Condition="'$(IncludeOperationsSharedSource)' == '' and '$(IsMgmtLibrary)' == 'true' and '$(IsTestProject)' != 'true' and '$(IsPerfProject)' != 'true'">true</IncludeOperationsSharedSource>
  </PropertyGroup>
```

**Comment by heaths** [comment]
FWIW, we do have some basic guidance on sample authoring now at https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-samples. I made some improvements - though there was significant feedback for additional work that is lower priority right now - in the following two PRs that might also help you:

* https://github.com/Azure/azure-sdk-for-net/pull/32578
* https://github.com/Azure/azure-sdk/pull/5152

**Comment by ArcturusZhang** [comment]
Hi @heaths we are able to find and fix some of them in this PR: https://github.com/Azure/azure-sdk-for-net/pull/34283

**Comment by ArthurMa1978** [comment]
Will close after remove out all failed samples

**Comment by ArthurMa1978** [comment]
Done
