### ISSUE TITLE
Device code authentication method is missing from UserTokenProvider

### ISSUE THREAD

**Issue by matt1883** [Azure/azure-sdk-for-net#3402]
``UserTokenProvider`` in Microsoft.Rest.ClientRuntime.Azure.Authentication needs to support logging in with a **device code**, like a few of the other SDK languages support.

This authentication option is important for scenarios where end-users need to log in to an application/device that can't launch a browser window.

I believe this would require upgrading the package to use a newer version of Microsoft.IdentityModel.Clients.ActiveDirectory.

**Comment by hovsepm** [comment]
@matt1883 it is supported for .Net Core platform (netstandard1.4 and greater). Not supported for .Net 4.5.2 by design.

**Comment by hovsepm** [comment]
@matt1883 we cannot upgrade ADAL for .Net 4.5.2 due to Azure PowerShell dependency.
