### ISSUE TITLE
[BUG] Null Response returned while trying to retrieve GeoReplicationStatistics property from StorageAccount

### ISSUE THREAD

**Issue by svangipurapu-msft** [Azure/azure-sdk-for-net#34043]
### Library name and version

Azure.ResourceManager.Storage v1.1.0

### Describe the bug

Hi,

I am getting null response while trying to retrieve [LastSyncTime ](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.storage.models.georeplicationstatistics.lastsyncon?view=azure-dotnet#azure-resourcemanager-storage-models-georeplicationstatistics-lastsyncon) property of a storage account. The LastSyncOn roperty is part of [GeoReplicationStatistics ](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.storage.models.georeplicationstatistics?view=azure-dotnet)class under the [StorageAccountData](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.storage.storageaccountdata?view=azure-dotnet)

I want to perform a failover action on a storage account for which I have to verify if [LastSyncOn](https://learn.microsoft.com/en-us/azure/storage/common/last-sync-time-get?tabs=azure-powershell) property is available before I trigger a failover action. But I see that GeoReplicationStats is retruned as null.

![image](https://user-images.githubusercontent.com/124931741/217941604-4ab8db16-ae9b-490a-8767-6c8d50e5c883.png)

### Expected behavior

When retrieving StorageAccountData.GeoiRelicationStats it should return an object which has information about the following properties

1. CanFailover
2. LastSyncOn
3. Status
https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.storage.models.georeplicationstatistics?view=azure-dotnet

### Actual behavior

Getting a null response while trying to retrieve StorageAccountData.GeoRelicationStats

### Reproduction Steps

For any storage account. Try accessing StorageAccountData and retrieve GeoReplicationStats propery. 

StorageAccountResource.Data.GeoReplicationStats

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by blueww** [comment]
@svangipurapu-msft 

When you retrieve the storage account from server, have you added the `StorageAccountExpand.GeoReplicationStats`.
The `GeoReplicationStats` won't be returned from server until you add this parameter like following code: 
```c#
StorageAccountResource account2 = await storageAccountCollection.GetAsync(accountName, StorageAccountExpand.GeoReplicationStats)
```

**Comment by svangipurapu-msft** [comment]
@blueww 

Thanks for the suggestion. I havent added it earlier. I modified my code and included StorageAccountExpand.GeoReplicationStats as below 

``` Response<StorageAccountResource> operationResponse = await armClient.GetStorageAccountResource(new ResourceIdentifier(targetInfo.ResourceId)).GetAsync(StorageAccountExpand.GeoReplicationStats).ConfigureAwait(false); ```

Now this is throwing an exception when running this operation on a Storage account with SKU type as Standard_LRS. Is this an expected error? 
It is working fine, when running against a Storage Account with sku type as RA_GRS. 
Is it because Geo Replication Stats are only available for GRS account types?

**Comment by blueww** [comment]
@svangipurapu-msft

Yes, Geo Replication Stats are only available for GRS account types.

**Comment by svangipurapu-msft** [comment]
Thanks for the confirmation

**Comment by blueww** [comment]
@svangipurapu-msft 

As your issue is already resolved, I will close this issue.
Feel free to contact us again if need any assistance on Azure .net SDK.
