### ISSUE TITLE
[FEATURE REQ] Support Managed Identity in GenerateSasUri()

### ISSUE THREAD

**Issue by Sebbs128** [Azure/azure-sdk-for-net#34050]
### Library name

Azure.Storage.Blobs, Azure.Storage.Queues, Azure.Data.Table

### Please describe the feature.

Currently `BlobBaseClient.GenerateSasUri()` is dependent on a `SharedKeyCredential` being set on the blob client `ClientConfiguration`. However, this is set to `null` when the constructor accepting `TokenCredential` is used (which is what we must use for Azure AD/Managed Identity authentication to the storage account).

Other clients (`QueueClient` and `TableClient`) have the same pattern. (These are the only clients being used in my particular project, but other clients that also allow SAS URI generation like ServiceBus and EventHub likely follow the same pattern too).

Subsequently, when using Managed Identity (and Azure RBAC) neither of the `GenerateSasUri()` methods on clients are usable, and workarounds (such as https://stackoverflow.com/a/75154692, taken from https://www.c-sharpcorner.com/article/generate-sas-token-for-azure-blob-storage-using-managed-identity/) must be used instead.

As Managed Identity/RBAC is becoming the/a preferred way for clients to authenticate to Azure services (especially when the client is also in Azure e.g. an App Service), I think these methods should Just Work™️ without resorting to workarounds.

**Comment by jsquire** [comment]
//fyi: @christothes

**Comment by christothes** [comment]
Hi @Sebbs128 - For Blob clients, you need to first [get a user delegation key ](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.getuserdelegationkey?view=azure-dotnet)to create a SAS when using AAD authentication. The SAS can then be generated with [this overload of ToSasQueryParameters](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.sas.blobsasbuilder.tosasqueryparameters?view=azure-dotnet#azure-storage-sas-blobsasbuilder-tosasqueryparameters(azure-storage-blobs-models-userdelegationkey-system-string)).

Unfortunately, [this applies to Blobs only](https://learn.microsoft.com/en-us/azure/storage/common/storage-sas-overview#user-delegation-sas),

**Comment by christothes** [comment]
I'm going to close this since the feature request should be directed to the service team rather than the SDK (we'll implement it if the service APIs support it). This appears to be the place to file these kinds of requests https://feedback.azure.com/d365community/forum/a8bb4a47-3525-ec11-b6e6-000d3a4f0f84
