### ISSUE TITLE
[Core]SByteCreate(sbyte.MinValue) failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#34061]
Core nightly test runs are failing with:

> Error message
> Expected: 0
> But was:  2152
> 
> 
> Stack trace
>    at Azure.MemoryWatch.Validate() in /Users/runner/work/1/s/sdk/core/Azure.Core.Experimental/tests/Variant/MemoryWatch.cs:line 92
>    at Azure.MemoryWatch.Dispose() in /Users/runner/work/1/s/sdk/core/Azure.Core.Experimental/tests/Variant/MemoryWatch.cs:line 87
>    at Azure.StoringSByte.SByteCreate(SByte testValue) in /Users/runner/work/1/s/sdk/core/Azure.Core.Experimental/tests/Variant/StoringSByte.cs:line 36
> 1) at Azure.MemoryWatch.Validate() in /Users/runner/work/1/s/sdk/core/Azure.Core.Experimental/tests/Variant/MemoryWatch.cs:line 92
>    at Azure.MemoryWatch.Dispose() in /Users/runner/work/1/s/sdk/core/Azure.Core.Experimental/tests/Variant/MemoryWatch.cs:line 87
>    at Azure.StoringSByte.SByteCreate(SByte testValue) in /Users/runner/work/1/s/sdk/core/Azure.Core.Experimental/tests/Variant/StoringSByte.cs:line 31

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2175425&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
@annelo-msft :  Not sure if this is related to the JsonData work.  Do you mind taking a look?

**Comment by annelo-msft** [comment]
It looks like it's in the `Value` type, not `DynamicJson` or related.

Since it's hasn't [reproed in a week](https://dev.azure.com/azure-sdk/internal/_build?definitionId=238&_a=summary), I'm closing, but if it comes back we can look into it more closely.
