### ISSUE TITLE
[KeyVault]Deploy test resources failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#34062]
KeyVault nightly test runs are failing with:

> Write-Error: /mnt/vss/_work/1/s/eng/common/TestResources/New-TestResources.ps1:799
> Line |
>  799 |              &$postDeploymentScript -ResourceGroupName $ResourceGroupN …
>      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Failed to export security domain data.
> 
> ##[error]PowerShell exited with code '1'.

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2175349&view=results

@jsquire for notification.

**Comment by heaths** [comment]
I already have an internal thread going on about this.
