### ISSUE TITLE
Hydra Spec and Azure-sdk-for-net repo not in sync

### ISSUE THREAD

**Issue by vinayada1** [Azure/azure-sdk-for-net#3407]
Some change in the hydra specs is causing some peering stats related files to be not generated. These files are still referenced by azure-powershell repo. Needs fixing by Express Route team

**Comment by EvgenyAgafonchikov** [comment]
@vinayada1, @dihan0604, could you please check if this still up to date?

**Comment by vinayada1** [comment]
https://github.com/Azure/azure-sdk-for-net/issues/3407

**Comment by vinayada1** [comment]
These were legacy issues that we found with our Hydra SDK. However, since that is frozen for any further development, I think these can be closed.

**Comment by dsgouda** [comment]
Thanks @vinayada1
