### ISSUE TITLE
[BUG] Obsolete "kind" attribute on OpenTelemetry Spans

### ISSUE THREAD

**Issue by pyohannes** [Azure/azure-sdk-for-net#34087]
### Library name and version

Azure.Messaging.EventHubs 5.7.0

### Describe the bug

OpenTelemetry spans submitted by Azure SDKs contain a "kind" attribute, which duplicates the span type by the [SpanKind](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spankind) property.

This is confusing. The generic attribute name also leads to conflicts in some cases. The attribute should be removed, as it doesn't provide any additional information to the already present `SpanKind`.

### Expected behavior

Don't add a "kind" attribute to spans, as it's redundant information.

### Actual behavior

An obsolete and redundant "kind" attribute is added to OpenTelemetry spans.

### Reproduction Steps

The attribute is visible on any OpenTelemetry spans emitted by the EventHubs SDK.

**Comment by lmolkova** [comment]
We can remove the attribute for `ActivitySource` path, but would need to keep populating it on `DiagnosticSource` path, where we provide stability guarantees (and keeping Application Insights SDK compatibility).

**Comment by JoshLove-msft** [comment]
Looks like the [OTel SDK](https://github.com/open-telemetry/opentelemetry-dotnet/blob/d0829fff2f229b67c884526cb4943b99f6c75f29/src/OpenTelemetry.Api/README.md?plain=1#L263-L268) automatically handles converting from ActivityKind into "spankind". So we should be able to simply remove the "kind" tag in the ActivitySource path.
