### ISSUE TITLE
[BUG] Azure.ResourceManager - No Registered Resource Provider Found

### ISSUE THREAD

**Issue by HansMusterWhatElse** [Azure/azure-sdk-for-net#34109]
### Library name and version

Azure.ResourceManager 1.4.0

### Describe the bug

Hi there,

Since a few days we experience issues with adding tags on our Cosmos DB Account.

We have tried to downgrade the NuGet package to the following versions which also appear to be broken:

- 1.32
- 1.30
- 1.21
- 1.20
- 1.10

There seems to be a general pattern that the version which is being requested, is only available with the **-preview** suffix.

```
Azure.RequestFailedException: 'No registered resource provider found for location 'westeurope' and API version '**2021-04-01**' for type 'databaseAccounts'. The supported api-versions are '2014-04-01, 2015-04-08, 2015-11-06, 2016-03-19, 2016-03-31, 2019-08-01-preview, 2019-08-01, 2019-12-12, 2020-03-01, 2020-04-01, 2020-06-01-preview, 2020-09-01, 2021-01-15, 2021-03-01-preview, 2021-03-15, **2021-04-01-preview**, 2021-04-15, 2021-05-01-preview, 2021-05-15, 2021-06-15, 2021-07-01-preview, 2021-10-15, 2021-10-15-preview, 2021-11-15-preview, 2022-02-15-preview, 2022-05-15-preview, 2022-05-15, 2022-08-15-preview, 2022-08-15, 2022-11-15, 2022-11-15-preview'. The supported locations are 'westcentralus, northcentralus, centralus, brazilsouth, canadacentral, westus2, eastus2, francecentral, japaneast, southeastasia, centralindia, southafricanorth, switzerlandnorth, uaenorth, ukwest, northeurope, westeurope, norwayeast, koreacentral, australiaeast, canadaeast, eastasia, germanywestcentral, uksouth, australiacentral, australiasoutheast, japanwest, koreasouth, southindia, westindia, westus, southcentralus, eastus, westus3, jioindiawest, swedencentral, qatarcentral'.
Status: 400 (Bad Request)
ErrorCode: NoRegisteredProviderFound

Content:
{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'westeurope' and API version '2021-04-01' for type 'databaseAccounts'. The supported api-versions are '2014-04-01, 2015-04-08, 2015-11-06, 2016-03-19, 2016-03-31, 2019-08-01-preview, 2019-08-01, 2019-12-12, 2020-03-01, 2020-04-01, 2020-06-01-preview, 2020-09-01, 2021-01-15, 2021-03-01-preview, 2021-03-15, 2021-04-01-preview, 2021-04-15, 2021-05-01-preview, 2021-05-15, 2021-06-15, 2021-07-01-preview, 2021-10-15, 2021-10-15-preview, 2021-11-15-preview, 2022-02-15-preview, 2022-05-15-preview, 2022-05-15, 2022-08-15-preview, 2022-08-15, 2022-11-15, 2022-11-15-preview'. The supported locations are 'westcentralus, northcentralus, centralus, brazilsouth, canadacentral, westus2, eastus2, francecentral, japaneast, southeastasia, centralindia, southafricanorth, switzerlandnorth, uaenorth, ukwest, northeurope, westeurope, norwayeast, koreacentral, australiaeast, canadaeast, eastasia, germanywestcentral, uksouth, australiacentral, australiasoutheast, japanwest, koreasouth, southindia, westindia, westus, southcentralus, eastus, westus3, jioindiawest, swedencentral, qatarcentral'."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-request-id: 7fdd8809-d529-4f7c-9cda-af14c9e57edd
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Mon, 13 Feb 2023 09:29:17 GMT
Content-Type: application/json; charset=utf-8
Expires: -1
Content-Length: 1193
'

```

### Expected behavior

Being able to update the tags on our CosmosDB Account.

### Actual behavior

We are getting the exception mentioned above.

### Reproduction Steps

None of the resource providers registered matches any of the requested versions:

`az provider show --namespace Microsoft.DocumentDB --query "resourceTypes[?resourceType=='databaseAccounts'].apiVersions[]"`

```
[
  "2022-11-15-preview",
  "2022-11-15",        
  "2022-08-15-preview",
  "2022-08-15",        
  "2022-05-15-preview",
  "2022-05-15",        
  "2022-02-15-preview",
  "2021-11-15-preview",
  "2021-10-15-preview",
  "2021-10-15",        
  "2021-07-01-preview",
  "2021-06-15",
  "2021-05-15",
  "2021-05-01-preview",
  "2021-04-15",
  "2021-04-01-preview",
  "2021-03-15",
  "2021-03-01-preview",
  "2021-01-15",
  "2020-09-01",
  "2020-06-01-preview",
  "2020-04-01",
  "2020-03-01",
  "2019-12-12",
  "2019-08-01-preview",
  "2019-08-01",
  "2016-03-31",
  "2016-03-19",
  "2015-11-06",
  "2015-04-08",
  "2014-04-01"
]
```

```
        private static TagResourceData CreateTagResourceData(IReadOnlyDictionary<string, string> tagArguments)
        {
            var tag = new Tag();

            foreach (var tagArgument in tagArguments)
            {
                tag.TagValues.Add(tagArgument);
            }

            return new TagResourceData(tag);
        }
```

        public async Task AddCustomTagsAsync(
            IReadOnlyDictionary<string, string> tags,
            CancellationToken cancellationToken = default)
        {
            // ... 
            // Left out for the sake of brevity
            var tagResource = _armClient.GetTagResource(cosmosDbAccountResourceIdentifier);
            var tagResourceData = CreateTagResourceData(tags);

            await tagResource.CreateOrUpdateAsync(WaitUntil.Started, tagResourceData, cancellationToken);
        }

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.308     
 Commit:    c61979521a  

Runtime Environment:    
 OS Name:     Windows   
 OS Version:  10.0.19044
 OS Platform: Windows   
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.308\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.400 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]
  6.0.308 [C:\Program Files\dotnet\sdk]
  6.0.405 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0-rc.2.22476.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0-rc.2.22472.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0-rc.2.22472.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Users\cia-agent-3432\source\repos\FitXP_Main\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
Hi @HansMusterWhatElse thanks for this issue
`TagResource` is a standalone resource, therefore it has its own resource id in this format: `{scope}/providers/Microsoft.Resources/tags/default` where `scope` is the resource id of the resource that you want to change the tags on.

Therefore in your code:
```csharp
var tagResource = _armClient.GetTagResource(cosmosDbAccountResourceIdentifier);
```
is incorrect if the value of `cosmosDbAccountResourceIdentifier` is just the resource identifier of the CosmosAccountResource. Instead, I believe you should use it this way:
```csharp
var tagResource = _armClient.GetTagResource(TagResource.CreateResourceIdentifier(cosmosDbAccountResourceIdentifier));
```
this creates an Id of the `TagResource` based on your CosmosAccount resource id.
Could you have a try on this or have a confirmation of the value of `cosmosDbAccountResourceIdentifier`?

**Comment by HansMusterWhatElse** [comment]
Hi @ArcturusZhang,

Quick update regarding the issue - it turns out that in this particular edge case we ended up sending an empty list of tags. Would it maybe be possible to update the exception to something more meaningful as not only is the exception totally misleading it also looks totally valid as the mentioned resource provider version is indeed not registered for Azure.
