### ISSUE TITLE
How to get entity list key value from azure cognitive services ( Conversational language understanding)

### ISSUE THREAD

**Issue by namanjain123** [Azure/azure-sdk-for-net#34111]
### Library name and version

Azure cognitive language

### Query/Question

I am not able to see the key of the list entity in the json returned by the conversation language understanding.

### Environment

.Net Core

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Can you provide some sample code of the endpoint request you are making?

**Comment by amberitas17** [comment]
I have the same error as @namanjain123 that I can't enter the value of the list key

https://user-images.githubusercontent.com/67531380/224478341-54c9efb4-c3b0-4fa2-8069-7488b7835a6e.mp4

**Comment by heaths** [comment]
Please note this repo is only for Azure SDK issues. If you're having a problem with the Portal, please use the feedback button in the top-right to report an issue.

**Comment by proxy-hatch** [comment]
@amberitas17 I am facing the same issue. Were you able to solve this?

**Comment by proxy-hatch** [comment]
Answering my own question, the trick is to also add synonym to make it a valid list item.
