### ISSUE TITLE
How can I get async behavior out of the Fluent SDK?

### ISSUE THREAD

**Issue by awesley** [Azure/azure-sdk-for-net#3411]
Hiya,

I'm creating VMs using the Fluent SDK.  Here's a code snippet:

```
            var vm = await this.azure

                .VirtualMachines

                .Define(vmName)

                .WithRegion(region)

                .WithExistingResourceGroup(resourceGroupName)

                .WithExistingPrimaryNetwork(network)

                .WithSubnet(subNetName)

                .WithPrimaryPrivateIPAddressDynamic()

                .WithoutPrimaryPublicIPAddress()

                .WithWindowsCustomImage(image)

                .WithAdminUsername(adminUserName)

                .WithAdminPassword(adminPassword)

                .WithSize(vmSize)

                .WithNewStorageAccount(storageAccountName)

                .WithTag(TagKeyNames.StorageAccountId, storageAccount.Id)

                .CreateAsync();
```

This task does not complete until the machine is entirely provisioned and booting - a period of over ten minutes.  That doesn't seem async to me.  Is there something I am doing wrong?  I want the call to return prior to the machine's availability.  

For comparison, when provisioning a VM on Amazon EC2 returns nearly immediately, well before the machine is fully provisioned and booted.  

I need from the call is the Id (`vm.Id`), the Primary Private IP (`vm.GetPrimaryNetworkInterface().PrimaryPrivateIP`), and the primary NIC Id (`vm.PrimaryNetworkInterfaceId`).  I do not need the machine to be ready.

Thanks!

**Comment by hovsepm** [comment]
@awesley we are working on providing callers a way to poll manually resource creation flow. Right now we do poll until resource provisioning status is succeeded or failed.

**Comment by awesley** [comment]
@hovsepm Understood.  I was able to add the multiThreaded: true arg to CreateAsync and reduce the time a bit, but my requestTimeout will still need to be extreme to manage this case (I'm using the SDK in ASP.Net Core).  

My 0.02$ on desired behavior - the call to Azure should be quick, return the information that I described above, and that I could poll if I'd like to.  

Due to the current behavior, if I spin up multiple VMs (conceptually, we could spin up 100 VMs at a time), I must introduce parallelization in my code -- which isn't a tremendous deal but an additional layer of complexity that I think could be hidden from API consumers such as myself.

Appreciate the response, feel free to close this Issue as you see fit.

**Comment by hovsepm** [comment]
@awesley did you consider to create a list of VM Creatables and then call Create on that list?
Manual polling is in the ToDo list for C# client runtime that we depend on. I should be also available in the future.

**Comment by awesley** [comment]
I have retry logic wrapping each VM creation request, so I prefer to have them as individual data structures.  That is a good suggestion though.  Thanks for the feedback!

**Comment by hovsepm** [comment]
@awesley We are looking for the ways to notify caller about resources that failed and succeed after Creatables.Create call.

**Comment by awesley** [comment]
My use case is to prepare a custom image which contains a self-announcing
service and request new VMs using that image.

Assuming that my request can be validated and that Azure returns the IDs of
all relevant resources (things created modified or otherwise used)

This ties back to polling as then I can long-poll those resource IDs as
needed (or some more sophisticated bi directional communication).

So really what I'm talking about here is to return the IDs rather than the
task object, and that I could query for each status or task object using
each ID.

In this way, consumers like me can choose to fire and forget, but if
desired could poll.

**Comment by martinsawicki** [comment]
@anuchandy another one related to the begin* pattern

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#8
