### ISSUE TITLE
[BUG] unable to peek message or receive message / program just stops

### ISSUE THREAD

**Issue by sidegence** [Azure/azure-sdk-for-net#34110]
### Library name and version

Azure.Messaging.ServiceBus 7.12.0

### Describe the bug

When using var peekedMessage = await _receiver.PeekMessageAsync(79369903); nothing will happen: No exceptions, no returned value - Excecution just stops. 

I can properly CreateProcessor and CreateSender but the _receiver just returns and stops executing 

instantiated as  _client.CreateReceiver(_queue, new ServiceBusReceiverOptions() { ReceiveMode = ServiceBusReceiveMode.PeekLock });

I tried 3 authentication variants, same result.

### Expected behavior

some form of information returned 

### Actual behavior

Nothing is returned and console execution just stops

### Reproduction Steps

            _client = new ServiceBusClient("<Cs>");
            _receiver = _client.CreateReceiver("<Q>", new ServiceBusReceiverOptions() { ReceiveMode = ServiceBusReceiveMode.PeekLock });

// here: 
var peekedMessage = await _receiver.PeekMessageAsync(1);

### Environment

Windows 11, Console Application 

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.4

.NET 6.0

**Comment by jsquire** [comment]
Hi @sidegence.  Thank you for reaching out and we regret that you're experiencing difficulties.   Can you help us understand what "just stops" and "no returned value" mean in this context?  Are you saying that your application crashes or that you get a `null` return value where you expect a message?   It would also be helpful if you could either share more of the code that illustrates the structure of the application and how the receiver is used or a small self-contained reproduction.

**Comment by sidegence** [comment]
My bad, was using it inside a Parallel.For not being waited in main thread

**Comment by jsquire** [comment]
I'm glad that you were able to get unblocked.   I'm going to close this out, but please feel free to unresolve if you'd like to continue the discussion.
