### ISSUE TITLE
[BUG] [Cost Management API - Exports] - duplicate BOM in generated *.csv files

### ISSUE THREAD

**Issue by mikeclayton** [Azure/azure-sdk-for-net#34129]
### Library name and version

Cost Management API - Exports - server side 2023/02/13

### Describe the bug

Hi,

I don't think this is a dotnet issue specifically, but maybe you can point me in the right direction.

I've created a scheduled Export of cost data using the Cost Management API which drops a *.csv file into a defined storage account on a daily basis. It looks like the exported *.csv contains **two** unicode Byte Order Markers - one at the start of the file, and one at the start of the first line of data:

**Exported \*.csv Format**
```
<<BOM>> Header1, Header2, ...
<<BOM>> DataA, DataB, ...
DataP, DataQ, ...
DataX, DataY, ...
... etc ...
```

The second BOM is being treated as data in my file import utility (using [CsvHelper](https://www.nuget.org/packages/CsvHelper/)) which means the InvoiceId  for the first row has a BOM suffix in the data:

![image](https://user-images.githubusercontent.com/1193763/218579270-93e6ec28-0564-4fa2-839f-af8ae641eb13.png)

Since the export is generated cloud-side, I don't think this is a dotnet client issue.

I've got a workaround to check the InvoiceId for the BOM prefix and remove it if it appears, but it would be nice to not have to do that :-).

If there's somewhere better to report this please let me know...

Cheers,

M

### Expected behavior

The *.csv files generated by the scheduled Export job should **not** contain a BOM at the start of the first row of data.

### Actual behavior

The *.csv files generated by the scheduled Export job **does** contain a BOM at the start of the first row of data.

### Reproduction Steps

* Create a Cost Management Export file and allow it to generate a *.csv in the target storage account.
* Download the *.csv once it's been generated and inspect the file in a hex editor
* * The file contains a unicode BOM at the start of the file, and a second BOM at the start of the first row of data.

I'm not sure if the exact schedule settings make any difference as I've not tried other settings, but the ones I'm using are:

Scope: [My Billing Account]
Metric: Amortized cost (Usage and Purchase(
Export Type: Daily export of month-to-date costs
File partitioning: Off

### Environment

Cloud-side issue - present in Cost Management API - Exports *.csv files generated as of 2023-02-13.

**Comment by jsquire** [comment]
Hi @mikeclayton.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Since what you're describing appears to be related to the REST API of the service itself and not one of the SDKs, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by mikeclayton** [comment]
@jsquire - no worries - I'll raise a support ticket. Cheers for getting back so quickly :-).
