### ISSUE TITLE
Add API to get SQL Database by ID w/o getting SQL Server first.

### ISSUE THREAD

**Issue by olegburov** [Azure/azure-sdk-for-net#3412]
In Azure portal, I can get an ID of my SQL Database, which looks like below:

- `/subscriptions/{my-subscription-id-here}/resourceGroups/{My-Resource-Group-here}/providers/Microsoft.Sql/servers/{my-sql-server-here}/databases/{my-sql-database-here}`

Using [Azure Management Libraries for .NET](https://www.nuget.org/packages/Microsoft.Azure.Management.Fluent/) (aka Fluent API) I want to get my Azure SQL Database directly by its ID without getting Azure SQL Server first. Just like I can by using [REST API](https://docs.microsoft.com/en-us/rest/api/resources/resources#Resources_GetById).

```c#
  var credentials = SdkContext.AzureCredentialsFactory.FromServicePrincipal(clientId, clientSecret, tenantId, AzureEnvironment.AzureGlobalCloud);
        
  var azure = Azure
    .Configure()
    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
    .Authenticate(credentials)
    .WithSubscription(subscriptionId);

  var database = azure.SqlServers.Databases.GetById("Sql-Database-Id-Here");
```

If the above solution doesn't look good, then maybe you can extend the `IDatabases` interface with `GetById` method:

```c#
  var sqlServer = azure.SqlServers.GetById("Sql-Server-Id-Here");
  var database = sqlServer.Databases.GetById("Sql-Database-Id-Here");
```

**Comment by martinsawicki** [comment]
@milismsft related to the long discussion we've had (for over a year) regarding direct access to children without going through the parent...

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#7

**Comment by olegburov** [comment]
@hovsepm What's about .NET lib?

**Comment by olegburov** [comment]
As far as I can see it, in `v1.11.1` (package `Microsoft.Azure.Management.Fluent`) I can do it like this:

```c#
var creds = new AzureCredentialsFactory().FromServicePrincipal(client, key, tenant, AzureEnvironment.AzureGlobalCloud);
var azure = Azure.Authenticate(creds).WithSubscription(subscriptionId);

var sqlDatabase = azure.SqlServers.Databases.GetById("/subscriptions/60987f15-2c3c-4659-aa1b-c4e87ecb8a19/resourceGroups/OBU/providers/Microsoft.Sql/servers/obu/databases/test");
```

OR

```c#
var creds = new AzureCredentialsFactory().FromServicePrincipal(client, key, tenant, AzureEnvironment.AzureGlobalCloud);
var azure = Azure.Authenticate(creds).WithSubscription(subscriptionId);

var sqlDatabase = sqlServer.Databases.GetById("/subscriptions/60987f15-2c3c-4659-aa1b-c4e87ecb8a19/resourceGroups/OBU/providers/Microsoft.Sql/servers/obu/databases/test");

```

**Comment by unruledboy** [comment]
I have similar issue, while I want to get a Sync Group, I need to do like this:

1. Auth
2. Get a SQL Server
3. Get a SQL Database 
4. Get a Sync Group

I reckon it is cumbersome as it will issue multiple calls, and the whole process takes 3-7 seconds, technically speaking we can straightaway get a Sync Group, right? So it would be way faster.
