### ISSUE TITLE
Add support for UpdateInstancesAsync and UpdateInstances to IVirtualMachineScaleSets

### ISSUE THREAD

**Issue by hrishi18pathak** [Azure/azure-sdk-for-net#3415]
Add support for UpdateInstancesAsync and UpdateInstances to IVirtualMachineScaleSets
just like other calls like ReImage, Reboot etc.
This is useful for doing manual upgrades of VMs in a scaleset (when the policy is set to manual)
Current way of achieving this:
IVirtualMachineScaleSet vmss;
var resp = await vmss.Manager.Inner.VirtualMachineScaleSets.UpdateInstancesAsync

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#6
