### ISSUE TITLE
What value is max per page if it is not specified?

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-sdk-for-net#34189]
`maxPerPage` is nullable yet docs don't say the behavior if it is left unspecified.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73b5d036-c2df-203c-f426-5e65fbf87b5b
* Version Independent ID: 8ab169e5-cd67-456e-a5d1-0ab9ae1119c3
* Content: [TableClient.QueryAsync Method (Azure.Data.Tables) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclient.queryasync?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Azure.Data.Tables.TableClient.QueryAsync%60%601)%3Bk(SolutionItemsProject)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=azure-dotnet)
* Content Source: [xml/Azure.Data.Tables/TableClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Data.Tables/TableClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
