### ISSUE TITLE
[Bug] [FEATURE REQUEST] Allowing option to specify the MaxDequeueCount to Queues underlying in Blobs

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#34269]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage.Blobs

### Query/Question

Related to https://github.com/Azure/azure-sdk-for-net/issues/33672

For poison blobs when blob trigger fails it retries 5 times by default.
https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=in-process&pivots=programming-language-csharp#poison-blobs

However in v4 when the packages were shipped together, customers were able to specify the `MaxDequeueCount` in order to specify the retry amount before the message is added to the blob trigger poison.

Since starting v5, the host.json only applies to queue triggers, and not blob triggers the following properties (including MaxDequeueCount have not been carried forward.

https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue?tabs=in-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#host-json

We need to figure out a way to expose this value without using the queues trigger settings.

**Comment by amnguye** [comment]
@liliankasem I left the issue open ended for us to decide how we wanted to resolve the issue.

I think the best way is to add the `MaxDequeueCount` to the host.json settings for blobs

**Comment by liliankasem** [comment]
> @liliankasem I left the issue open ended for us to decide how we wanted to resolve the issue.
> 
> I think the best way is to add the `MaxDequeueCount` to the host.json settings for blobs

Yup, I agree. I responded in the email thread about this

> You’ll need to update [BlobsOptions](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fblob%2Fmain%2Fsdk%2Fstorage%2FMicrosoft.Azure.WebJobs.Extensions.Storage.Blobs%2Fsrc%2FConfig%2FBlobsOptions.cs&data=05%7C01%7CLilian.Kasem%40microsoft.com%7Cc4195c5139ce4ef66f3208db8a150363%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638255595170079114%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XrJGF1aGokkQqtHRGuTbwogFEJgKXC4D8yd0buT%2BVdc%3D&reserved=0) to add a property for ‘MaxDequeueCount’ and utilize that in the extension as necessary. Any property defined in your options would automatically be exposed in host.json under the extension name.

If this is not working, let us know and we can help investigate if the right configuration pattern is being used.

**Comment by amnguye** [comment]
@liliankasem Just made the PR. If someone from your team could review it that would be great.

https://github.com/Azure/azure-sdk-for-net/pull/37836

I will also get someone from my team to review it as well.
