### ISSUE TITLE
[FEATURE REQ] Improve documentation for the AutomationRunbookResource.GetTestJobStreamsAsync method

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#34323]
### Library name

Azure.ResourceManagement.Automation

### Please describe the feature.

The AutomationRunbookResource.GetTestJobStreamsAsync method requires that you provide a filter expression, however, no the documentation does not provide any details as to how to construct this expression. In earlier versions of the Azure SDK for .NET, you would provide a date string (round-trip format) but this no longer works with an error indicating that you must provide a filter that evaluates to a boolean.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
Add service team attention since this requires service domain knowledge

**Comment by navba-MSFT** [comment]
Since service team has been involved already, I am removing the CXP attention label.
