### ISSUE TITLE
[BUG] Service Bus messages are not fetched when SessionIdleTimeout is set  to 00:00:00 and PrefetchCount > 0

### ISSUE THREAD

**Issue by jodoroth** [Azure/azure-sdk-for-net#34330]
### Library name and version

Microsoft.Azure.Extensions.ServiceBus 5.6.0

### Describe the bug

When we use built-in Service Bus trigger in Logic App Standard stateless workflow with SessionIdleTimeout set to 00:00:00 and PrefetchCount set to >0 in the  host.json file, the messages are not fetched from Service bus.  Only when we change the SessionIdletimeout  value greater than 0 (for instance 00:00:01) the messages are fetched from Service Bus.

### Expected behavior

When the SessionIdleTimeout set to 00:00:00 and Prefetch count >0, the messages are expected to be fetched from service bus
 
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  },
  "extensions": {
        "serviceBus": {
            "prefetchCount":20,
            "batchOptions":{
                "maxMessageCount":3,
                "operationTimeout":"00:01:00",
                "autoComplete":false
                    },
            "sessionIdleTimeout":"00:00:00"
                       }
                }
}
 

### Actual behavior

When we use built-in Service Bus trigger in Logic App Standard stateless workflow with SessionIdleTimeout set to 00:00:00 and PrefetchCount set to >0 in the  host.json file, the messages are not fetched from Service bus.  Only when we change the SessionIdletimeout  value greater than 0 (for instance 00:00:01) the messages are fetched from Service Bus.

Non working Scenario :

SessionIdleTimeout set to 00:00:00 and Prefetch count >0
 
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  },
  "extensions": {
        "serviceBus": {
            "prefetchCount":20,
            "batchOptions":{
                "maxMessageCount":3,
                "operationTimeout":"00:01:00",
                "autoComplete":false
                    },
            "sessionIdleTimeout":"00:00:00"
                       }
                }
}
 
Working Scenario:

SessionIdleTimeout set to any postiive value other than 0 and Prefetch count >0
 
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  },
  "extensions": {
        "serviceBus": {
            "prefetchCount":20,
            "batchOptions":{
                "maxMessageCount":3,
                "operationTimeout":"00:01:00",
                "autoComplete":false
                    },
            "sessionIdleTimeout":"00:00:01"
                       }
                }
}
 

### Reproduction Steps

In the Standard logic App Stateless workflow, we used the 'When messages are available in a topic subscription (peek-lock)' Service bus trigger with SessionEnabled property set to 'true'

<img width="748" alt="Service bus Trigger" src="https://user-images.githubusercontent.com/63275135/219721185-4b56b247-9056-4ff6-b129-541195bc5891.png">

<img width="578" alt="LogicAppServiceBus" src="https://user-images.githubusercontent.com/63275135/219721834-e20018d6-291e-4427-8cf5-78e82a5ca015.png">

The trigger is followed by Compose and 'complete the message' action. Below is the expression set on the complete the message action
triggerOutputs()?['body']?[0]?['messageId']

Unsuccessful scenario:

we have the SessionIdleTimeout set to 00:00:00 and Prefetch count >0 in the host.json file. With this configuration we do not see any messages fetched from Service Bus.
 
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  },
  "extensions": {
        "serviceBus": {
            "prefetchCount":20,
            "batchOptions":{
                "maxMessageCount":3,
                "operationTimeout":"00:01:00",
                "autoComplete":false
                    },
            "sessionIdleTimeout":"00:00:00"
                       }
                }
}
 
Working Scenario:

We have the SessionIdleTimeout set to any positive value other than 0 and Prefetch count >0 in the host.json file. With this configuration we see messages fetched from Service Bus.

 
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle.Workflows",
    "version": "[1.*, 2.0.0)"
  },
  "extensions": {
        "serviceBus": {
            "prefetchCount":20,
            "batchOptions":{
                "maxMessageCount":3,
                "operationTimeout":"00:01:00",
                "autoComplete":false
                    },
            "sessionIdleTimeout":"00:00:01"
                       }
                }
}

**Comment by JoshLove-msft** [comment]
Thinking about this a bit more, I believe this is the expected behavior. The ability to pass a maxWaitTime of 0 to a receive call allows you to empty the prefetch buffer when prefetch is enabled. However, if you were to set sessionIdleTimeout to 0 (which gets passed as the maxWaitTime in receive calls), then you are potentially not allowing the prefetch buffer to fill before closing the receiver. For this reason, you should set some minimal amount of wait time for the sessionIdleTimeout to allow messages to be received (whether using prefetch or not).
