### ISSUE TITLE
[QUERY] User assigned identity not working when system assigned identity is enabled

### ISSUE THREAD

**Issue by v-bafa** [Azure/azure-sdk-for-net#34339]
### Library name and version

Azure.Identity 1.8.1

### Query/Question

I have an azure function required system assigned identity enabled to get access to resources such as KV. Also I have a user identity assigned to the function to get access to other azure resources.
For the first purpose I use DefaultAzureCredential directly, and it works well.
For the second purpose I specified the ManagedIdentityClientId as follows, but it failed to access the resources grant access to this identity.
Looked at this [doc](https://learn.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/managed-identities-faq#what-identity-will-imds-default-to-if-dont-specify-the-identity-in-the-request), but it does not mention this situation.
 DefaultAzureCredentialOptions option = new DefaultAzureCredentialOptions
                {
                    //Use the client id of managed identity 
                    //DO NOT set AZURE_CLIENT_ID in configuration
                    ManagedIdentityClientId = "xxxx"
                };
                var credential = new DefaultAzureCredential(option);
                _armClientUAI = new ArmClient(credential, subscriptionId);

### Environment

.NET SDK:
 Version:   7.0.103
 Commit:    276c71d299

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.103\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  6.0.309 [C:\Program Files\dotnet\sdk]
  7.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

IDE: Visual Studio 2022

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @v-bafa - Please enable logging for the credential and we should get some more information about what is happening. 

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#logging

**Comment by v-bafa** [comment]
> Hi @v-bafa - Please enable logging for the credential and we should get some more information about what is happening.
> 
> https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#logging

Hello @christothes 
I added following codes but do not know where to find related logs from Az Function.

**using (AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger())**
                {
                    //Use user assigned managed identity to initial ARMClient
                    DefaultAzureCredentialOptions option = new DefaultAzureCredentialOptions
                    {
                        //Use the cliend id of managed identity 
                        //DO NOT set AZURE_CLIENT_ID in configuration
                        ManagedIdentityClientId = "xxx",
                        **Diagnostics =
                        {
                            LoggedHeaderNames = { "x-ms-request-id" },
                            LoggedQueryParameters = { "api-version" },
                            IsLoggingContentEnabled = true
                        }**
                    };
                    var credential = new DefaultAzureCredential(option);
                    _armClientUAI = new ArmClient(credential, subscriptionId);
                }

**Comment by christothes** [comment]
Assuming you have an instance of `ILogger` in the function - try this:

```c#
using AzureEventSourceListener listener = new AzureEventSourceListener(
    (args, message) => _logger.LogInformation("[{0:HH:mm:ss:fff}][{1}] {2}", DateTimeOffset.Now, args.Level, message),
    level: EventLevel.Verbose);
```
