### ISSUE TITLE
Move all SDKs to .NET Core 2.0

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3438]
Currently Azure SDK for .NET target to .NET 4.5.2 and .NET Standard 1.4
There are requests to target to .NET Core 2.0

Include: releasing nugets that are not released.

Cost: 6

**Comment by RichardAnderson** [comment]
Hi, 

Any update on this?

The azure-service-bus-dotnet package was updated 21 days ago, however the management package still does not support 2.0.

Many thanks.

**Comment by fernanev** [comment]
Hi,

Any update on this? Is there any work planned for fixing this issue?

Many thanks.

**Comment by garfbradaz** [comment]
Any news on this?
