### ISSUE TITLE
[BUG] System.UriFormatException thrown when retrieving webhooks form an Azure Automation account

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#34398]
### Library name and version

Azure.ResourceManager.Automation 1.0.0

### Describe the bug

A System.UriFormatException (Invalid URI: The URI is empty) exception is thrown when using the AutomationWebhookCollection.GetAllAsync method to retrieve webhook resources from an Azure Automation account.

Stack Trace:

at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Azure.ResourceManager.Automation.AutomationWebhookData.DeserializeAutomationWebhookData(JsonElement element)
   at Azure.ResourceManager.Automation.WebhookRestOperations.<GetAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.ResourceManager.Automation.AutomationWebhookCollection.<GetAsync>d__7.MoveNext()

### Expected behavior

No exception should be thrown.

### Actual behavior

A System.UriFormatException is thrown with the message "Invalid URI: The URI is empty).

### Reproduction Steps

private async Task<IList<AutomationWebhookData>> Test(AutomationAccountResource automationAccount)
{
    var result = new List<AutomationWebhookData>();
    var enumerator = automationAccount.GetAutomationWebhooks().GetAllAsync().GetAsyncEnumerator();

    try
    {
        while (await enumerator.MoveNextAsync().ConfigureAwait(false))
        {
            result.Add(enumerator.Current.Data);
        }

    }
    finally
    {
        await enumerator.DisposeAsync().ConfigureAwait(false);
    }

    return result;
}

### Environment

Windows 10, .NET Framework 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Thanks for reaching out to us. This is a known issue and we will fix it.

**Comment by dvbb** [comment]
This issue has been fixed in this PR: [[Automation] Fix the Uri format issue](https://github.com/Azure/azure-sdk-for-net/pull/36434)

**Comment by dvbb** [comment]
[Azure.ResourceManager.Automation 1.1.0-beta.1](https://www.nuget.org/packages/Azure.ResourceManager.Automation/1.1.0-beta.1) has been released without uri issue
