### ISSUE TITLE
Minimum async polling interval

### ISSUE THREAD

**Issue by jaredmoo** [Azure/azure-sdk-for-net#3439]
In Microsoft.Sql RP we noticed a bug in our service where we aren't setting Retry-After header in AzureAsyncOperation responses. This is causing the SDK to poll very quickly, i.e. multiple times per second. We are fixing this in the service, but it would also be wise if SDK polling code had a minimum polling interval, e.g. 1-5 seconds, in order to avoid hammering services that have such bug.

**Comment by shahabhijeet** [comment]
@jaredmoo we are getting this ask from multiple RPs.
I have created an issue to track this, as this will require us to co-ordinate all Runtime (if we decide to support this feature, ideally should be part of all SDKs .NET, Java etc.)
https://github.com/Azure/azure-sdk-for-net/issues/3447
