### ISSUE TITLE
[BUG] Service request failed error when trying to start an automation runbook job.

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#34416]
### Library name and version

Azure.ResourceManager.Automation 1.0.1

### Describe the bug

We are observing a "Service request failed" exception when attempting to start an automation runbook job. Interestingly the error message also says "Status 200 (OK)" in addition to what appears to be information about the last successful job that was run (in this case manually started from the browser).

Stack Trace:

 at Azure.ResourceManager.Automation.JobRestOperations.<CreateAsync>d__21.MoveNext()
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Azure.ResourceManager.Automation.AutomationJobCollection.<CreateOrUpdateAsync>d__5.MoveNext()

### Expected behavior

We should be able to start a runbook job without error.

### Actual behavior

The SDK request fails with "Service request failed" error

### Reproduction Steps

private async Task Test(AutomationAccountResource resource, string runbookName,
            IDictionary<string, string> parameters)
{
    var content = new AutomationJobCreateOrUpdateContent
    {
        RunbookName = runbookName,
        RunOn = string.Empty
    };

    foreach (var param in parameters)
        content.Parameters[param.Key] = param.Value;

    await _resource.GetAutomationJobs()
        .CreateOrUpdateAsync(WaitUntil.Started, runbookName, content);
}

### Environment

Windows 10, .NET Framework 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
This should be a service issue, they didn't define response 200 for this operation in the [API spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/automation/resource-manager/Microsoft.Automation/stable/2019-06-01/job.json#L360-L371).

Route to service team to have a look.
