### ISSUE TITLE
[BUG] AutomationRunookType class does not support PowerShell7 runbooks.

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#34417]
### Library name and version

Azure.ResourceManager.Automation 1.0.1

### Describe the bug

The AutomationRunookType class does not include a property for PowerShell7 runbooks, even though PowerShell7 runbook information is being returned from calls to the AutomationRunbookResource.GetAsync method. There seems to be a disconnect between the internal REST API and the current version of Azure.ResourceManager.Automation.

### Expected behavior

The AutomationRunookType class should have a property to represent PowerShell7 runbooks.

### Actual behavior

The AutomationRunookType class does not have a property to represent PowerShell7 runbooks.

### Reproduction Steps

1. Create a PowerShell7 runbook in Azure Automation
2. Retrieve the runbook using the AutomationRunbookResource.GetAsync
3. The AutomationRunbookData class RunbookType property will indicate PowerShell7, even though there is no corresponding property in the AutomationRunookType class.

### Environment

Windows 10, .NET Framework 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
I double checked the latest [API spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/automation/resource-manager/Microsoft.Automation/stable/2022-08-08/runbook.json#L1180-L1196) and it also doesn't contain `PowerShell7`. Forward this issue to service team to have a look.

**Comment by ArthurMa1978** [comment]
Unfortunately, there's no further help that we can provide.  This repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.   If further help is needed, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request), and I'm going to close this out.
