### ISSUE TITLE
GetByResourceGroupAsync - VirtualMachineScaleSets Fluent API

### ISSUE THREAD

**Issue by pppchris** [Azure/azure-sdk-for-net#3444]
var VMSS = await Repo.VirtualMachineScaleSets.GetByResourceGroupAsync(resourceGroup, id);
var VMSS = await Repo.VirtualMachineScaleSets.ListByResourceGroupAsync( resourceGroup );

The api-version '2016-04-30-preview' is invalid. The supported versions are '2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'.

Version 1.1.3

**Comment by pppchris** [comment]
OK, worked out the issue. If you send through an invalid resourceGroup Name (I was sending through the resource id for the resource group), it throws the error above.  

Should this be handled by a better exception?

**Comment by anuchandy** [comment]
Is the id in the correct arm resource id format? we can check this, if you share the invalid resource id you have used.

**Comment by martinsawicki** [comment]
the design calls for resource groups to be referenced by name throughout the SDK, not the ID.

(The error is not very useful admittedly but that's what the SDK gets from Azure and it's much broader than this specific case).
