### ISSUE TITLE
Microsoft.​Azure.​Management.​Service​Bus documentation is still at 0.1.0-preview

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3446]
@SeanFeldman reported in AutoRest branch
https://github.com/Azure/autorest/issues/2413

Creating this issue to be tracked in the right repo.
Docs are not updated and use 0.1.0-preview version.
https://docs.microsoft.com/en-us/dotnet/api/Microsoft.Azure.Management.ServiceBus

**Comment by twitchax** [comment]
Here is the link to the nuget package: https://www.nuget.org/packages/Microsoft.Azure.Management.ServiceBus/.

**Comment by SeanFeldman** [comment]
Ironically, the nuget page is the one that leads to Azure/autorest...
