### ISSUE TITLE
[BUG] Sticky bit symbolic notation is not parsed correctly

### ISSUE THREAD

**Issue by yifanz0** [Azure/azure-sdk-for-net#34463]
### Library name and version

Azure.Storage.Files.DataLake 12.13.0

### Describe the bug

Referring to the SDK code [azure-sdk-for-net/PathAccessControlExtensions.cs at main · Azure/azure-sdk-for-net (github.com)](https://github.com/azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Files.DataLake/src/Models/PathAccessControlExtensions.cs#L160), "T" is parsed to "Execute" with sticky bit set, which is opposite to the behavior in the document. 

Per the [documentation ](https://learn.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update#request-headers)"e.g. rwxrw-rw- with sticky bit is represented as rwxrw-rwT. A rwxrw-rwx with sticky bit is represented as rwxrw-rwt".

This can also result in conflicting info displayed by PSH cmdlet - 
![image](https://user-images.githubusercontent.com/100746763/220564422-c7363e85-759d-4d30-8725-9be4c9971f90.png)

### Expected behavior

"T" should be parsed to "-" + sticky bit set, and "t" should be parsed to "execute" + sticky bit set 

### Actual behavior

"T" is parsed to "execute" + sticky bit set, and "t" is parsed to "-" + sticky bit set 

### Reproduction Steps

Use the function https://github.com/azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Files.DataLake/src/Models/PathAccessControlExtensions.cs#L149 with a permission with sticky bit set, say "rwxrwxrwT"

**Comment by amnguye** [comment]
I have made a PR to address this issue.
