### ISSUE TITLE
[BUG] Blob upload progress reporting is inconsistent

### ISSUE THREAD

**Issue by mlaviexc** [Azure/azure-sdk-for-net#34469]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Describe the bug

BlobClient.UploadAsync()'s ProgressHandler shows long values which go up and down. I think this is because of a thread racing condition when when concurrent threads are used behind-the-scenes for perofrmance improvement. I guess whichever thread  touched the Total Uplaoded Bytes last determines its value

### Expected behavior

The ProgressHandler should return an always-ascending long, containing the total of all bytes uploaded so far by all concurrent threads.

### Actual behavior

THe long coung when the Progresshandler is fired goes up and down - sometimes returning to zero. SOmetimes the same number is reported twice.

### Reproduction Steps

Upload a file of at least 10 MB using BlobClient.UploadAsync() using a ProgressHandler. If you output the value of the ProgressHandler each time its fired, the number occasionally goes down to zero, or there are clearly multiple competing progress counts.

### Environment

VS 17.4.5
.NET 7
NuGet Azure.Storage.Blobs 12.14.1

**Comment by navba-MSFT** [comment]
@mlaviexc Thanks for reaching out to us and reporting this issue. Here's my 2 cents for a few potential cause of the inconsistent progress reporting:

- Concurrent uploads: If you are uploading multiple blobs concurrently, the ProgressHandler for each upload task may be updating the progress counter at different rates. This can cause the progress value to fluctuate or even return to zero, especially if one upload task completes before others. To avoid this, you could try synchronizing the progress handler across all concurrent upload tasks by using a shared [SemaphoreSlim](https://learn.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim?view=net-7.0).

Here's an example of how you could use a [SemaphoreSlim ](https://learn.microsoft.com/en-us/dotnet/api/system.threading.semaphoreslim?view=net-7.0)to synchronize progress updates across multiple concurrent upload tasks:

```
// Initialize a SemaphoreSlim with the number of concurrent uploads you want to allow
int maxConcurrentUploads = 5;
SemaphoreSlim semaphore = new SemaphoreSlim(maxConcurrentUploads);

foreach (string filePath in Directory.GetFiles(sourcePath))
{
    string fileName = Path.GetFileName(filePath);
    Console.WriteLine($"Uploading {fileName}\r\n");
    var blobClient = blobContainerClient.GetBlobClient(fileName);
    var progressHandler = new BlobUploadProgressChange(blobClient);
    progressHandler.ProgressChanged += UploadProgressChanged;

    // Wait for a slot in the semaphore before starting the upload task
    await semaphore.WaitAsync();

    var options = new BlobUploadOptions()
    {
        ProgressHandler = progressHandler
    };

    try
    {
        // Upload the blob asynchronously and release the semaphore slot when done
        await blobClient.UploadAsync(filePath, options);
    }
    finally
    {
        semaphore.Release();
    }
}

```

The sample code snippet for BlobUploadProgressChange is [here](https://stackoverflow.com/a/73291830/17951893). In this example, we use a SemaphoreSlim to limit the number of concurrent upload tasks to maxConcurrentUploads. Before starting an upload task, we call WaitAsync() on the semaphore to wait for an available slot. Once we have a slot, we create the progress handler and upload options as before, but we also wrap the UploadAsync() call in a try-finally block to ensure that we always release the semaphore slot when the upload task completes (whether it succeeds or fails). This ensures that the progress handler is only updated once per concurrent batch of uploads.

**Comment by mlaviexc** [comment]
Thank you for the fast response.

However, this happens when I am
 uploading a single file.

**Comment by mlaviexc** [comment]
My apologies - this was being caused becasue I was using async lamda expression:
IProgress<long> progressReport =new Progress<long>(async (uploadedBytes) => {...) );
and setting progressReport as ProgressHandler in the BlobUploadOptions

This was solved by instead setting ProgressHandler = a MyProgressHandler class with a Report() method, which performs the per-progress report actions.

Please close my bug report. 

Life lesson: avoid async lambda like the plague.

**Comment by navba-MSFT** [comment]
> My apologies - this was being caused becasue I was using async lamda expression:
IProgress progressReport =new Progress(async (uploadedBytes) => {...) );
and setting progressReport as ProgressHandler in the BlobUploadOptions
This was solved by instead setting ProgressHandler = a MyProgressHandler class with a Report() method, which performs the per-progress report actions.
Please close my bug report.
Life lesson: avoid async lambda like the plague.


@mlaviexc Thanks for the above update. We will proceed with closure of this GitHub thread.
