### ISSUE TITLE
[BUG] No method to list Assessments of SecurityAssessmentCollection to get SecurityAssessmentResources

### ISSUE THREAD

**Issue by TomerHadad58** [Azure/azure-sdk-for-net#34464]
### Library name and version

Azure.ResourceManager.SecurityCenter 1.1.0

### Describe the bug

In order to access the SecurityAssessmentResources of Azure Defender for Cloud, we use the SecurityAssessmentCollection Class, but there exists no method in the class to list all Assessments, only methods to fetch specific one by ResourceIdentifier.
There's also no other way to get the ResourceIdentifiers of SecurityAssessmentResources, making it impossible to access them altogether using the library.

SecurityAssessmentCollection has a private property `_securityAssessmentAssessmentsRestClient` of type `AssessmentsRestOperations`, which has the method 'ListAsync' to list all Assessments within a scope, but this class is internal and the function is not used in SecurityAssessmentCollection to provide a method of listing all Assessments within a scope.

### Expected behavior

SecurityAssessmentCollection should have a List method, utilizing the List method of `_securityAssessmentAssessmentsRestClient`, to provide a way of listing all Assessments within a scope. Or any other way to list the Assessments.

### Actual behavior

There exists no way of listing the Assessments within a scope, and therefor no way of accessing any SecurityAssessmentResource overall.

### Reproduction Steps

Nothing to reproduce.

**Comment by xboxeer** [comment]
add @ArthurMa1978 for help

**Comment by omri-muszkal** [comment]
@ArthurMa1978 any idea if this can be fixed?
