### ISSUE TITLE
[QUERY] Late ThrowIfCancellationRequested check in SendMessagesAsync

### ISSUE THREAD

**Issue by BillVolz** [Azure/azure-sdk-for-net#34472]
### Library name and version

Azure Service Bus 7.12.0

### Query/Question

I was browsing the code and noticed that this cancellation check (link below) is performed after the operation is complete.  Wouldn't this result in a successful queue of the message and a cancellation as the result?  Then may be cause someone to queue the message twice on a retry? 

https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.ServiceBus_7.12.0/sdk/servicebus/Azure.Messaging.ServiceBus/src/Sender/ServiceBusSender.cs#L255

### Environment

N/A

**Comment by jsquire** [comment]
Hi @BillVolz.  Thanks for your feedback.  That does indeed look like a bug.   We'll get this fixed up.
