### ISSUE TITLE
[QUERY] Should the UserAssertion parameter be used as part of the TokenRequestContext

### ISSUE THREAD

**Issue by andrueastman** [Azure/azure-sdk-for-net#34493]
### Library name and version

Azure.Identity

### Query/Question

When trying to use the `OnBehalfOfCredential` it looks like the `_userAssertion` property is initialized with the instance of the credential class. 

https://github.com/Azure/azure-sdk-for-net/blob/9c4203dc877e870145d7e684f0a53bc36808dfed/sdk/identity/Azure.Identity/src/Credentials/OnBehalfOfCredential.cs#L24

In the event that an application with many users, multiple instances of the `OnBehalfOfCredential` would need to be created to handle the multiple `userAssertion`s. This will in turn create [multiple clients](https://github.com/Azure/azure-sdk-for-net/blob/9c4203dc877e870145d7e684f0a53bc36808dfed/sdk/identity/Azure.Identity/src/Credentials/OnBehalfOfCredential.cs#L151) for requesting the token when it may be possible to have a single credential and have the `userAssertion` passed in the request context to avoid the multiple instances.

Is creating of new credential instances on changing `userAssertions` the desired flow and is it expected for one to keep a collection of the instances if they want to leverage the cache used in an instance?

### Environment

When trying to use the `OnBehalfOfCredential` it looks like the `_userAssertion` property is initialized with the instance of the credential class. 

https://github.com/Azure/azure-sdk-for-net/blob/9c4203dc877e870145d7e684f0a53bc36808dfed/sdk/identity/Azure.Identity/src/Credentials/OnBehalfOfCredential.cs#L24

In the event that an application with many users, multiple instances of the `OnBehalfOfCredential` would need to be created to handle the multiple `userAssertion`s. This will in turn create [multiple clients](https://github.com/Azure/azure-sdk-for-net/blob/9c4203dc877e870145d7e684f0a53bc36808dfed/sdk/identity/Azure.Identity/src/Credentials/OnBehalfOfCredential.cs#L151) for requesting the token when it may be possible to have a single credential and have the `userAssertion` passed in the request context to avoid the multiple instances.

Is creating of new credential instances on changing userAssertions` the desired flow or should one keep the instances in collection to leverage the cache in an instance?

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by andrueastman** [comment]
Hey @christothes,

Just to follow up, this means keeping a collection of credentials relative in size to the number of users. And this means multiple instances of the `MsalClient` created.

Is there a scenario where the library looks into the `userAssertion` being passable via the `TokenRequestContext` thus enabling one credential to be used for the authentication of the users?

**Comment by christothes** [comment]
> Is there a scenario where the library looks into the `userAssertion` being passable via the `TokenRequestContext` thus enabling one credential to be used for the authentication of the users?

No we don't support this today.

If your environment is asp.net, you may want to use the Microsoft.Identity.Web library, which supports the On-Behalf-Of flow https://learn.microsoft.com/en-us/azure/active-directory/develop/scenario-web-api-call-api-overview
