### ISSUE TITLE
[Azure.Developer.LoadTesting][Improvement] Add Request Payload for GetMetrics

### ISSUE THREAD

**Issue by oshadhi-liyanage** [Azure/azure-sdk-for-net#34499]
### Library name

Azure.Developer.LoadTesting

### Description

Currently, there is no request payload passed to the GetMetrics method in the sample application [Sample5_GetMetrics file ](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Developer.LoadTesting_1.0.0-beta.2/sdk/loadtestservice/Azure.Developer.LoadTesting/samples/Sample5_GetMetrics.md)

It's better to do this documentation improvement to improve the developer experience.

**Comment by SaurabhSharma-MSFT** [comment]
@oshadhi-liyanage I see that you have already submitted a PR to fix this issue which will be merged once approved.  Please let me know if you need any other help else, we will proceed with the closure of this issue.
