### ISSUE TITLE
[BUG] Visual Studio Credential fails authorization

### ISSUE THREAD

**Issue by spowser** [Azure/azure-sdk-for-net#34505]
### Library name and version

Azure.Data.AppConfiguration 1.2.0

### Describe the bug

Calling SetConfigurationSetting results in a 403 error when using the VisualStudioCredential.  The call succeeds with 200 using the AzureCliCredential.  Both credentials are using the same account. See https://github.com/Azure/azure-sdk-for-net/issues/34265 for more details.

This has also been confirmed with other members of our organization with proper permissions to the target resource.

### Expected behavior

All calls have consistent behavior regardless of the credential token used as long as the authenticating account is the same.

### Actual behavior

403 using VisualStudioCredential
200 using AzureCliCredential

### Reproduction Steps

Azure.Data.AppConfiguration: 1.2.0 and tried 1.3.0-beta.1
Azure.Identity: 1.8.2 and tried 1.9.0-beta.2
Azure.Security.KeyVault.Secrets: 4.4.0

User has been given `App Configuration Data Owner` permissions on the app config resource and All permissions on the Key Vault

```c#
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(System.Diagnostics.Tracing.EventLevel.LogAlways);

DefaultAzureCredentialOptions options = new DefaultAzureCredentialOptions
{
    Diagnostics =
        {
            IsAccountIdentifierLoggingEnabled = true,
        },
    ExcludeManagedIdentityCredential = true,
    ExcludeAzureCliCredential = true,
    ExcludeAzurePowerShellCredential = true,
    ExcludeEnvironmentCredential = true,
    ExcludeSharedTokenCacheCredential = true,
    ExcludeVisualStudioCodeCredential = true,
    //ExcludeVisualStudioCredential = true,
    ExcludeAzureDeveloperCliCredential = true,
    ExcludeWorkloadIdentityCredential = true
};

var _configUri = "https://testconfig.azconfig.io";
var kvUri = "https://testvault.vault.azure.net/";
var azureCredential = new DefaultAzureCredential(options);
var keyVaultClient = new SecretClient(new Uri(kvUri), azureCredential);
var configClient = new ConfigurationClient(new Uri(_configUri), azureCredential);

var keyVaultSecret = keyVaultClient.GetSecret("Test").Value;

SecretReferenceConfigurationSetting configReference = new("Web:Test", keyVaultSecret.Id, "MyLabel");
var addedConfigReference = configClient.SetConfigurationSetting(configReference, true).Value;
```

### Environment

Windows 10 .NET Framework 4.8 and also tested on .NET 6.0.13
IDE: Visual Studio 17.4.3

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @spowser - I'm unable to reproduce this using either `VisualStudioCredential` or `DefaultAzureCredential` configured as in your example. It works as expected for me.

**Comment by spowser** [comment]
Not sure where to go from here.  I have also cleared out the `C:\Users\*\AppData\Local\.IdentityService` directory to have Visual Studio regenerate all the tokens to make sure something old wasn't being picked up.

Any help is appreciated

**Comment by christothes** [comment]
My only suggestion is the look at the logging to see if there are any clues as to what is happening. If you are successfully acquiring a token, then the problem seems to be your RBAC configuration or the account being used is not what is expected.  The credential seems to be doing what it should be.

In my logging, everything but the ClientId is the same across both credential types.

**Comment by spowser** [comment]
I'm getting the same results in the logging.  Same credential across both types except the ClientId.  Something is fishy with the Visual Studio authentication.  It says I am logged in according to the UI and Tools => Options => Azure Service Authentication but it's not acting like it here. :(

I guess we can close this and I can start digging into how Visual Studio is authenticating or not

**Comment by spowser** [comment]
For reference, I found this for anyone else having this issue
https://developercommunity.visualstudio.com/t/Cannot-authenticate-to-Azure-services-wi/10283976?ref=native&refTime=1677260947062&refUserId=b02bda6b-8e8d-40ef-8890-98ed27b344c7

**Comment by spowser** [comment]
I attempted to update to 17.5 but still no dice.  I am going to try and get them to reopen that case since it doesn't seem to be fully resolved
