### ISSUE TITLE
Search SDK: Custom HttpClientHandler not called on Search requests

### ISSUE THREAD

**Issue by pablocastro** [Azure/azure-sdk-for-net#3451]
Using the SearchServiceClient that takes a HttpClientHandler overload, the client will invoke the handler for index management operations and for indexing operations, but not for search operations. 

SDK version 3.0.4, with Microsoft.Rest.ClientRuntime 2.3.7 and Microsoft.Rest.ClientRuntime.Azure 3.3.6.

**Comment by brjohnstmsft** [comment]
This is most likely because the handler pipeline for the `SearchServiceClient` is not propagated to the `SearchIndexClient` that is returned from the `GetClient` method. Until we fix it, the workaround is to construct the `SearchIndexClient` directly.

**Comment by brjohnstmsft** [comment]
The fix for this issue shipped with version 3.0.5 to [NuGet](https://aka.ms/search-sdk).
