### ISSUE TITLE
Add tests for GET VMSS NIC apis

### ISSUE THREAD

**Issue by DeepakRajendranMsft** [Azure/azure-sdk-for-net#3452]
Add tests for GET VMSS NIC apis

**Comment by EvgenyAgafonchikov** [comment]
It looks like it was addressed by https://github.com/Azure/azure-sdk-for-net/pull/3457
Also, tests are not required for SDK now.
@cormacpayne, @DeepakRajendranMsft, could we close this? I have no permissions to close issues in this repo.

**Comment by MikhailTryakhov** [comment]
@dsgouda  need to be closed as outdated

**Comment by dsgouda** [comment]
Closing
