### ISSUE TITLE
[Container Registry]DownloadArtifactAsync failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#34525]
Container Registry nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 404 (Not Found)
> 
> Content:
> {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest tagged by "demo" is not found","detail":{"Tag":"demo"}}]}
> 
> Headers:
> Server: openresty
> Date: Thu, 23 Feb 2023 20:24:49 GMT
> Connection: keep-alive
> Access-Control-Expose-Headers: REDACTED
> Docker-Distribution-Api-Version: REDACTED
> Strict-Transport-Security: REDACTED
> X-Content-Type-Options: REDACTED
> X-Ms-Client-Request-Id: d1406e39-3abd-49bd-802c-ff62d6d76099
> X-Ms-Correlation-Request-Id: REDACTED
> X-Ms-Request-Id: d6f7755b-092f-411f-aa25-032a59439e13
> Content-Type: application/json; charset=utf-8
> Content-Length: 118
> 
> 
> Stack trace
>    at Azure.Containers.ContainerRegistry.ContainerRegistryRestClient.GetManifestAsync(String name, String reference, String accept, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Generated/ContainerRegistryRestClient.cs:line 134
>    at Azure.Containers.ContainerRegistry.Specialized.ContainerRegistryBlobClient.DownloadManifestAsync(String tagOrDigest, Nullable`1 mediaType, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Blob/ContainerRegistryBlobClient.cs:line 535
>    at Azure.Containers.ContainerRegistry.Tests.Samples.UploadArtifactSample.DownloadArtifactAsync() in /Users/runner/work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/Samples/Sample05_UploadDownloadArtifact.cs:line 95
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2585738&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
This is being tracked;  closing as a duplicate.
