### ISSUE TITLE
[QUERY] Default retry policy for Azure.ResourceManager.ServiceBus and Azure.ResourceManager.EventHubs

### ISSUE THREAD

**Issue by linsqi** [Azure/azure-sdk-for-net#34523]
### Library name and version

Azure.ResourceManager.ServiceBus(1.0.0) and Azure.ResourceManager.EventHubs(1.0.0)

### Query/Question

We are using Azure.ResourceManager.ServiceBus and Azure.ResourceManager.EventHubs to perform namespace and entity crud and other operations, wondering if there is default retry policy integrated in the SDK? If so what is the retry policy like or is there any document regarding this so we can refer to? Thanks!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by linsqi** [comment]
any update?

**Comment by ArthurMa1978** [comment]
@linsqi yes, by default the client retry 3 times and 0.8s delay, here is the doc https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#configuring-retry-options
