### ISSUE TITLE
[BUG] sourceAddressPrefixes

### ISSUE THREAD

**Issue by AnassKartit** [Azure/azure-sdk-for-net#34532]
### Library name and version

Azure.ResourceManager.Network

### Describe the bug

unable to set sourceAddressPrefixes in SecurityRuleData , it is read only

### Expected behavior

sourceAddressPrefixes able to be set

### Actual behavior

error sourceAddressPrefixes is read only

### Reproduction Steps

create an instance of SecurityRuleData and try to fill the field:   SourceAddressPrefixes

### Environment

Windows

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AnassKartit** [comment]
i switched  my code from c# to nodejs code to bypass this limitation

**Comment by dvbb** [comment]
`SourceAddressPrefixes` is a readonly list that has been initialized in the constructor, we can update it through `Add()`, `Clear()` methods

```
var securityRule = new SecurityRuleData()
{
    Name = "rule001",
    Access = SecurityRuleAccess.Deny,
    Description = "Test outbound security rule",
};
securityRule.SourceAddressPrefixes.Add("10.10.0.1");
securityRule.SourceAddressPrefixes.Add("10.10.0.2");
securityRule.SourceAddressPrefixes.Clear();
```

**Comment by ArcturusZhang** [comment]
@AnassKartit BTW this is by-design for azure dotnet sdks. There is a quality linter rule for dotnet: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2227
The list does not have a setter but this does not mean the list is immutable, as @dvbb said you could use Add, Remove or Clear to change the content of it.
It might be inconvenient if you already have a list of items and want to put them into the list. Currently we did not provide a convenience method like `AddRange`, but you could always write an extension method by your own, something like:
```csharp
public static class IListExtensions
{
public static void AddRange<T>(this IList<T> list, IEnumerable<T> items) where T : notnull
{
foreach (var item in items)
{
list.Add(item);
}
}
}
```
