### ISSUE TITLE
[BUG] Azure.Monitor.OpenTelemetry.Exporter package dependency version lock on OpenTelemetry

### ISSUE THREAD

**Issue by pblachut** [Azure/azure-sdk-for-net#34536]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.7

### Describe the bug

The latest version of Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.7 requires exact version of OpenTelemetry dependency (= 1.4.0-rc.3).

It causes that it is not possible to use the latest versions of other open telemetry packages.

![image](https://user-images.githubusercontent.com/12517339/221196072-60d1a8bc-c303-4883-81f3-406f50fad72e.png)

### Expected behavior

Dependency should not force to use exact version number. It should be >= 1.4.0-rc.3.

### Actual behavior

Cannot use the latest version of a package together with other OpenTelemetry packages.

### Reproduction Steps

Create a project with given set of dependencies:

``` 
        <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.0.0-beta.7" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.4.0-rc.4" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.0.0-rc9.13" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.0.0-rc9.13" />

```

**Comment by vishweshbankwar** [comment]
@pblachut - We are planning to remove this in next release once stable 1.4.0 is released. (anticipated early March).
