### ISSUE TITLE
[BUG] Serialization issues in ResourceManager.Storage

### ISSUE THREAD

**Issue by AndresAlvarezEstrada** [Azure/azure-sdk-for-net#34544]
### Library name and version

"Azure.ResourceManager.Storage" Version="1.1.1"

### Describe the bug

SkuStorageName
BlobInventoryPolicyFormat
BlobInventoryPolicyObjectType
BlobInventroyPolicySchedule
BlobInventoryRuleType

and possibly more fail to serialize and deserialize properly.

### Expected behavior

A simple test like this fails for all 4 properties
```
[Test]
        public void PropertyShouldSerializeAndDeserialize()
        {
            var object = new SkuStorageName("Standard_LRS");
            var json = JsonConvert.Serialize(object);

            var deserializedObject = JsonConvert.DeserializeObject(json);

            Assert.AreEqual(object,deserializedObject);
        }
```

### Actual behavior

Due to the serialization issues, some commands off azure itself cannot be run as getting the data from azure inherently deserializes it

### Reproduction Steps

run the test above with any of the 4 classes and watch the errors fly

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @AndresAlvarezEstrada , Thank you for using Azure SDK for .NET.
This issue has been fixed in the latest packages, please take a look.
