### ISSUE TITLE
[BUG] GetMapStaticImageAsync  

### ISSUE THREAD

**Issue by rvinothrajendran** [Azure/azure-sdk-for-net#34558]
### Library name and version

Azure.Maps.Search -1.0.0-beta.3

### Describe the bug

An exception is thrown when providing the latitude and longitude as input to the GetMapStaticImageAsync function. 
However, the values passed to the ReverseSearchCrossStreetAddressAsync function are functioning properly. Further information is provided below.

**GetMapStaticImageAsync  exception**

Service request failed.
Status: 400 (Bad Request)

Content:
{"Center":["params are out of range <-180,180> and <-85,85>"]}

Headers:
x-ms-azuremaps-region: REDACTED
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
X-Cache: REDACTED
X-MSEdge-Ref: REDACTED
Date: Sat, 25 Feb 2023 14:42:40 GMT
Content-Length: 62
Content-Type: application/json; charset=utf-8

### Expected behavior

It should create an image

### Actual behavior

Throw an exception

Service request failed.
Status: 400 (Bad Request)

Content:
{"Center":["params are out of range <-180,180> and <-85,85>"]}

Headers:
x-ms-azuremaps-region: REDACTED
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
X-Cache: REDACTED
X-MSEdge-Ref: REDACTED
Date: Sat, 25 Feb 2023 14:42:40 GMT
Content-Length: 62
Content-Type: application/json; charset=utf-8

### Reproduction Steps

GeoPosition geoPosition = new GeoPosition(37.7749, -122.4194);
Pass GeoPosition to GetMapStaticImageAsync function
it throw an exception

### Environment

.NET SDK:
 Version:   7.0.200
 Commit:    534117727b

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows

**Comment by SaurabhSharma-MSFT** [comment]
@rvinothrajendran We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@rvinothrajendran I believe there is a limitation on the coordinates of the center point and thus you are getting the error.  Please see below and go through the documentation over [here](https://learn.microsoft.com/en-us/rest/api/maps/render/get-map-image?tabs=HTTP).
![image](https://user-images.githubusercontent.com/38112130/222926975-2ed1f21b-6835-4625-b3dc-28ce0aeb0828.png)
Please let me know if you have any questions.
