### ISSUE TITLE
Incorrect return type description

### ISSUE THREAD

**Issue by denistex** [Azure/azure-sdk-for-net#34560]
The **Returns** section says the return type is `Response<T>` and mentions the `Status` property which is not part of `Response<T>` but a different type `Response`. The actual return type is `Response<T>` but it is not clear how to handle the case when the table already exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 476fd277-800d-ccc5-3081-4aa0b483680c
* Version Independent ID: 42801eef-7ec7-f7a9-29fd-542c7045f51e
* Content: [TableClient.CreateIfNotExists(CancellationToken) Method (Azure.Data.Tables) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableclient.createifnotexists?view=azure-dotnet)
* Content Source: [xml/Azure.Data.Tables/TableClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Data.Tables/TableClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
