### ISSUE TITLE
Add tests for ipv6 express route

### ISSUE THREAD

**Issue by DeepakRajendranMsft** [Azure/azure-sdk-for-net#3456]

**Comment by EvgenyAgafonchikov** [comment]
Requirement to add SDK tests was dropped. @vinayada1, @DeepakRajendranMsft, could we close this?

**Comment by vinayada1** [comment]
These were legacy issues that we found with our Hydra SDK. However, since that is frozen for any further development, I think these can be closed.

**Comment by dsgouda** [comment]
Thanks @vinayada1
