### ISSUE TITLE
Incorporate semantic conventions changes in exporter

### ISSUE THREAD

**Issue by vishweshbankwar** [Azure/azure-sdk-for-net#34579]
### Library name

 Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

There have been many changes in OTel with respect to semantic conventions, specially in instrumentation libraries. We need to validate them against the exporter and make updates accordingly.

**Comment by TimothyMothra** [comment]
We've been doing the work in the OTel repo and making changes here when appropriate.
We haven't been using this issue to tag PRs so I think we can close this issue.
