### ISSUE TITLE
InteractiveBrowserCredential preference to use system browser or modal dialog

### ISSUE THREAD

**Issue by thenextman** [Azure/azure-sdk-for-net#34576]
### Library name

Azure.Identity

### Please describe the feature.

The [documentation](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.interactivebrowsercredential?view=azure-dotnet) for `InteractiveBrowserCredential` says (emphasis mine):

> launches the **system default browser** to interactively authenticate a user

In my experience, if my Windows desktop application targets .NET 6 the system browser is launched. However if we target .NET 4.8, a modal popup is shown with an embedded browser.

Using the system browser is (in my case) a better user experience, and from a cursory look it seems like this is an option in MSAL. Is it possible to get this choice exposed via the `InteractiveBrowserCredentialOptions` (or otherwise)?

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
