### ISSUE TITLE
Receiving error while using Azure.ResourceManager.Maintenance package - invalid maintenance window. error: startdatetime is not set for maintenance window

### ISSUE THREAD

**Issue by dasakhar** [Azure/azure-sdk-for-net#34604]
Hey,

I'm using the Azure.ResourceManager.Maintenance Nuget in order to create Maintenance configuration resource in Azure and assign it to VMSS in our cloud resources.

I've been working with this documentation:
https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.maintenance.maintenanceconfigurationdata?view=azure-dotnet

For some reason while trying to create the resource of Maintenance Configuration I receive an error which states that I'm missing the StartDateTime property even tough this parameter is not optional in latest version of the Nuget only in beta version.
In the latest Nuget version we need to use the StartOn property which we did but for some reason we are still receiving this error:
 invalid maintenance window. error: startdatetime is not set for maintenance window

This is our constructor definition:

        protected override async Task DeployInternalAsync(MaintenanceConfigurationConfiguration configuration, IReadOnlyCollection<IAzureResource> dependencies, CancellationToken cancellationToken)
        {
                var maintenanceConfigurationResource = await _maintenanceConfigurationCollection.CreateOrUpdateAsync(
                WaitUntil.Completed,
                Name.ToLowerInvariant(),
                new MaintenanceConfigurationData(AzureLocation.EastUS)
                {
                    MaintenanceScope = MaintenanceScope.OSImage,
                    TimeZone = "UTC",
                    RecurEvery = "1Day",
                    Duration = 6.Hours(),
                    StartOn = DateTimeOffset.UtcNow,
                });

There is no StartDateTime property for this constructor.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
We got the issue, pr is reviewing and will release hotfix soon

**Comment by ArthurMa1978** [comment]
https://www.nuget.org/packages/Azure.ResourceManager.Maintenance/1.1.1 released
