### ISSUE TITLE
[FEATURE REQ] Make the password parameter on UsernamePasswordCredential a SecureString 

### ISSUE THREAD

**Issue by userr2232** [Azure/azure-sdk-for-net#34609]
### Library name

Azure.Identity

### Please describe the feature.

The `UsernamePasswordCredential` constructor could perhaps accept the password as a `SecureString` instead of just `string`. Perhaps there is a reason behind the decision to only support `string`, but I think it would be nice to have the other type as well if possible.

**Comment by jsquire** [comment]
Hi @userr2232.  Thank you for your feedback.  This is not a feature request that we'll be moving forward with.   Official .NET guidance recommends not using `SecureString` for new development, as discussed in the [type documentation](https://learn.microsoft.com/dotnet/api/system.security.securestring#remarks) and the associated discussion in [DE001](https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md).
