### ISSUE TITLE
[QUERY] How can instances be created with ResourceManager.Sql?

### ISSUE THREAD

**Issue by Jepplar** [Azure/azure-sdk-for-net#34602]
### Library name and version

Azure.ResourceManager.Sql 1.2.0

### Query/Question

I have run into some issues when trying to create a new SQL database in another region as a secondary geo-replica of our primary databases where I haven't been able to spawn the instances. Essentially, what I want in the end is to automatically set up a replicated instance of each database that is available in our production system but in another region.

I wasn't able to find any samples on how to create the SQL instances and would appreciate any tips on how to approach it via the SDK. Thus far I have successfully run the following test code:

    string fromResourceGroupName = "";
    string fromSubscriptionId = "";
    string fromSqlServerName = "";

    string targetResourceGroupName = "";
    string targetSubscriptionId = "";
    string targetSqlServerName = "";

    DefaultAzureCredential credentials = new(includeInteractiveCredentials: true);

    ArmClient client = new(credentials);
    SubscriptionCollection subs = client.GetSubscriptions();

    // We want to create a secondary copy from these databases
    SubscriptionResource fromSubscription = subs.Get(fromSubscriptionId);
    ResourceGroupCollection fromResourceGroups = fromSubscription.GetResourceGroups();
    ResourceGroupResource fromResourceGroup = await fromResourceGroups.GetAsync(fromResourceGroupName);
    SqlServerResource fromSqlServer = fromResourceGroup.GetSqlServer(fromSqlServerName).Value;
    SqlDatabaseCollection fromDatabaseCollection = fromSqlServer.GetSqlDatabases();

    // To this SQL server instance
    SubscriptionResource targetSubscription = subs.Get(targetSubscriptionId);
    ResourceGroupCollection targetResourceGroups = targetSubscription.GetResourceGroups();
    ResourceGroupResource targetResourceGroup = await targetResourceGroups.GetAsync(targetResourceGroupName);
    SqlServerResource targetSqlServer = targetResourceGroup.GetSqlServer(targetSqlServerName).Value;

    foreach (SqlDatabaseResource? sourceIter in fromDatabaseCollection)
    {
        // What to put here?
    }

Thank you for your time

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @Jepplar , Thank you for using Azure SDK for .NET.
Inorder to create a geo replica, you just need to add some extra properties while creating a new database.
1. You need a backup server (better to locate in another region)
2. Backup database location need to be same as server location.

Sample code:
```
    var rg = (await sub.GetResourceGroups().GetAsync("YourRG")).Value;
    var serverCollection = rg.GetSqlServers();
    var mainServer = (await serverCollection.GetAsync("MainServer")).Value;
    var backServer = (await serverCollection.GetAsync("BackupServer")).Value;
    var db = (await mainServer.GetSqlDatabases().GetAsync("MainDB")).Value;
    var backupData = new SqlDatabaseData(AzureLocation.SoutheastAsia)
    {
        // These three properties are needed to create a geo replica
        SecondaryType = SecondaryType.Geo,
        CreateMode = SqlDatabaseCreateMode.Secondary,
        SourceDatabaseId = db.Id
    };
    var backup = (await backServer.GetSqlDatabases().CreateOrUpdateAsync(WaitUntil.Completed, db.Data.Name, backupData)).Value;
    db = (await mainServer.GetSqlDatabases().GetAsync("MainDB")).Value;
    await foreach (var item in db.GetSqlServerDatabaseReplicationLinks().GetAllAsync())
    {
        Console.WriteLine(item.Data.PartnerDatabase);
    }
```
