### ISSUE TITLE
Add autorest transform for ACR to remove securityDefinitions section as it is incorrect.

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#34606]
While we work with the service team and get the swagger fixed, add the autorest swagger transform to remove the section while ingestion.

**Comment by annelo-msft** [comment]
@pallavit, did we decide that each language will do this separately in their own repo?

**Comment by pallavit** [comment]
No not yet. I put this in the next month milestone since I was hoping we will know if the service team will be able to update swagger.
