### ISSUE TITLE
[FEATURE REQ] RetryPolicy / RetryOptions - configurable exponent & random boundaries and/or custom retry mode (user provided CalculateExponentialDelay)

### ISSUE THREAD

**Issue by ohads-MSFT** [Azure/azure-sdk-for-net#34611]
### Library name

Azure.Core

### Please describe the feature.

Consider the existing method for calculating exponential backoff delay: https://github.com/Azure/azure-sdk-for-net/blob/4d8a0979d83ffd6f52e97b3eeeab28858f50ccba/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs#L331

As you can see, the following are hard-coded:
1. Exponent `1 <<` basically means `Math.Pow(2, attempt - 1)` (so it's set to `2`)
2. Lower random boundary (`0.8`)
3. Upper random boundary (`1.2`)

The exponent especially can be critical to the resulting delay time series, but since exposing all the above seems very simple (basically add 3 properties to `RetryOptions`), might as well add them too.

In addition, a `RetryMode.Custom` could be added which allows setting a custom-provided `CalculateExponentialDelay`. I suppose if we have this kind of extensibility then parametrizing the above properties won't be strictly needed, but IMHO it would be nice to have all the same (e.g. the Azure.Core team might improve the method yet retain the constants used, for example guard better against overflow).

**Comment by jsquire** [comment]
//cc: @christothes, @annelo-msft

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @ohads-MSFT As of version [1.27.0](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/CHANGELOG.md#1270-2023-01-10) It is possible to [implement a custom retry policy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#setting-a-custom-retry-policy) with a [customized CalculateNextDelay](https://github.com/Azure/azure-sdk-for-net/blob/0275433e19f3ecbfc210d9eddb92126c19f3ccca/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs#L232).

Does this work for your scenario?

**Comment by ohads-MSFT** [comment]
Hi @christothes 

I'm probably missing something, but it looks like RetryPolicy is internal: https://github.com/Azure/azure-sdk-for-net/blob/0275433e19f3ecbfc210d9eddb92126c19f3ccca/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs#L17

Seems like this was intentional per the following comment from @JoshLove-msft: https://github.com/Azure/azure-sdk-for-net/pull/33281#issuecomment-1373018348

Making it public again would go a long way towards this feature request, though it would still require clients to reimplement the logic in `CalculateNextDelayInternal` (specifically the server delay override). Not a huge deal to be sure, but I maintain that the suggestions I've made above would be a bit more convenient.

**Comment by christothes** [comment]
Oh - yes, sorry. We were initially going to make it public and then delayed that. There are plans to make it public in the future.

**Comment by JoshLove-msft** [comment]
@ohads-MSFT thanks for the feedback. We will make sure to consult this as we work on the design for making RetryPolicy public.

**Comment by ohads-MSFT** [comment]
@JoshLove-msft just to clarify, IMHO my original suggestion is an easy win, potentially much cheaper than designing `RetryPolicy` (so not necessary to wait for that, if that makes sense). At the simplest, the constants (and possibly `CalculateExponentialDelay` as a delegate) could just be properties in `RetryOptions`.

**Comment by JoshLove-msft** [comment]
Thanks for the feedback. Can you provide some more information about the scenario where you want to configure these values?

**Comment by ohads-MSFT** [comment]
> In particular, I can see why one may want to configure the min/max jitter factors (.8/1.2 being the defaults), but I don't see why the factor itself would need to be configurable.

@JoshLove-msft Actually if I had to choose, I would prefer the factor to be configurable :) It has the most dramatic effect on the resulting retry time series, and ultimately only the service owners (AKA your customers) would know which series makes sense. 

For example, we want 5 retries, and there is a big difference between something like `1,2,3,6,14,21` and `1,3,8,20,75`. In our case, considering our load pattern, we much prefer the latter.

**Comment by JoshLove-msft** [comment]
You can now customize the DelayStrategy used in a RetryPolicy as described here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#setting-a-custom-retry-policy

**Comment by ohads-MSFT** [comment]
@JoshLove-msft nice, thanks!

A couple of small comments:
1. The docs you linked to use a `MyCustomDelayStrategy` but don't show its implementation (presumably subclassing `DelayStrategy`)
2. Per the discussion above, it would have been slightly nicer to be able to provide the factor to `CreateExponentialDelayStrategy` (rather than hard code it to 2)

**Comment by JoshLove-msft** [comment]
1. Ack - I will update the sample here to be more complete.
2. The decision not to expose the jitter factor in the factory method was less about perf optimization and more about not thinking this is something most users will want to do. If you need full control over the jitter factory you can implement your own custom DelayStrategy and pass in whatever jitter factor you would like to the base constructor.

**Comment by ohads-MSFT** [comment]
@JoshLove-msft just to clarify, you mean "the decision not to expose the exponent factor"?

**Comment by JoshLove-msft** [comment]
Ah my bad - you were referring to the exponent factor not the jitter factor. For that, you would need to define your own custom strategy as well.

**Comment by JoshLove-msft** [comment]
Updated sample in https://github.com/Azure/azure-sdk-for-net/pull/35654
