### ISSUE TITLE
Assembly conflict in Azure in process function v4

### ISSUE THREAD

**Issue by xztmp1** [Azure/azure-sdk-for-net#34637]
### Library name and version

Azure.Data.AppConfiguration

### Describe the bug

Azure.Data.AppConfiguration: Method 'AsPages' in type 'FuncAsyncPageable`1' from assembly 'Azure.Data.AppConfiguration, Version=1.2.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.

### Expected behavior

We are converting a .net3.1 inprocess function to .net6 function v4. 
The assembly is getting resolved properly on the localhost, but when it is deployed to Azure fails with the following error
Azure.Data.AppConfiguration: Method 'AsPages' in type 'FuncAsyncPageable`1' from assembly 'Azure.Data.AppConfiguration, Version=1.2.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.

### Actual behavior

Azure.Data.AppConfiguration: Method 'AsPages' in type 'FuncAsyncPageable`1' from assembly 'Azure.Data.AppConfiguration, Version=1.2.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.

### Reproduction Steps

These are the libraries referenced in the project file:
    "Azure.Identity" Version="1.4.1" 
     "AzureExtensions.Swashbuckle" Version="3.3.2"
     "AspNetCore.HealthChecks.CosmosDb" Version="3.1.2"
     "Elevate.CacheServices.Client" Version="1.1.1"
     "FluentValidation" Version="10.3.3"
     "Microsoft.ApplicationInsights" Version="2.20.0"
     "Microsoft.Azure.Cosmos" Version="3.22.1"
     "Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.9"
     "Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="5.2.0"
     "Microsoft.Extensions.Logging" Version="6.0.0"
     "Microsoft.Extensions.Options.DataAnnotations" Version="6.0.0"
     "Microsoft.NET.Sdk.Functions" Version="4.1.1"
     "Newtonsoft.Json" Version="13.0.1"

**Comment by xztmp1** [comment]
<PackageReference Include="AspNetCore.HealthChecks.CosmosDb" Version="3.1.2" />    
    <PackageReference Include="Azure.Identity" Version="1.4.1" />
    <PackageReference Include="AzureExtensions.Swashbuckle" Version="3.3.2" />
    <PackageReference Include="Elevate.CacheServices.Client" Version="1.1.1" />
    <PackageReference Include="FluentValidation" Version="10.3.3" />
    <PackageReference Include="Microsoft.ApplicationInsights" Version="2.20.0" />
    <PackageReference Include="Microsoft.Azure.Cosmos" Version="3.22.1" />    
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.CosmosDB" Version="3.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" Version="5.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />    
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
I found a [StackOverflow post](https://stackoverflow.com/questions/74744117/azure-function-v4-migration-could-not-load-file-or-assembly-microsoft-extensio) that describes this exact scenario and recommends adding an explicit dependency for Microsoft.Extensions.Configuration.Abstractions to 6.0.0, as the issue appears to be due to an incompatible with 7.x which is pulled in transitively via your AppConfig reference. Would you be able to try this workaround?

@fabiocav Is there any other docs we can point customers to for this issue? Is the above workaround accurate to your knowledge? I can also move this issue over to the functions host repo.

**Comment by xztmp1** [comment]
I tried as per your suggestion, but I am getting the same error:
Azure.Data.AppConfiguration: Method 'AsPages' in type 'FuncAsyncPageable`1' from assembly 'Azure.Data.AppConfiguration, Version=1.2.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' does not have an implementation.

**Comment by JoshLove-msft** [comment]
@xztmp1 could you share a minimal repo?

**Comment by xztmp1** [comment]
Sorry I won't be able to share the code as it has proprietary information. This is a simple Http trigger function

**Comment by JoshLove-msft** [comment]
Given that this appears to be an issue with the dependency resolution happening on the function host, and not locally, I will go ahead and transfer this issue to the functions host repo. The functions team should be able to debug further including having access to any server logs that may help them track down the issue.
