### ISSUE TITLE
How to close and dispose Azure ServiceBusClient and ServiceBusSender singletons asynchronously when using dependency injection

### ISSUE THREAD

**Issue by spelluru** [Azure/azure-sdk-for-net#34643]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

Copying the question from a GitHub issue in the azure-docs-pr repo. Please see the original issue here: https://github.com/MicrosoftDocs/azure-docs/issues/105917. I appreciate if you could respond when you get a chance.

---
I want to use Azure Service Bus in .NET 7 applications, such as ASP.NET Core Web API pr Worker Service, which use dependency injection.

The [official documentation](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk-2#reusing-factories-and-clients) recommends registering ServiceBusClient and ServiceBusSender as singletons:

The Service Bus objects that interact with the service, such as ServiceBusClient, ServiceBusSender, ServiceBusReceiver, and ServiceBusProcessor, should be registered for dependency injection as singletons (or instantiated once and shared).

It [also says](https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#disposal-of-services) that dependencies will and must be disposed by the containter via the singleton's IDisposable.Dispose():

The container is responsible for cleanup of types it creates, and calls Dispose on IDisposable instances. Services resolved from the container should never be disposed by the developer. If a type or factory is registered as a singleton, the container disposes the singleton automatically.

Now, the problem with ServiceBusClient and ServiceBusSender is that both do NOT implement IDisposable but IAsyncDisposable instead.
I couldn't find any documentation about whether the dependency injection container will also call (and await) IAsyncDisposable.DisposeAsync() automatically when shutting down the application.

Is that the case?

And if not, how else am I supposed to dispose the Azure Service Bus singletons when Services resolved from the container should never be disposed by the developer?

Please add some code snippets and recommendations regarding this question to the documentation.

Also note that I have also asked this question on [Stackoverflow](https://stackoverflow.com/questions/75593459/how-to-close-and-dispose-azure-servicebusclient-and-servicebussender-singletons).
---

**Comment by jsquire** [comment]
@spelluru:  It's been answered on StackOverflow as well.   In a nutshell, it happens automatically.

**Comment by jsquire** [comment]
I reflected the answer over to the MS Docs issue as well.   Closing this out.

**Comment by spelluru** [comment]
@jsquire - Oops. Sorry for the duplicate. Thank you so much!

**Comment by jsquire** [comment]
@spelluru:  No worries at all.  Better to copy/paste than miss answering one.   😄
