### ISSUE TITLE
[QUERY] WithoutAccessFromAzureServices equivalent in Azure.ResourceManager.Sql

### ISSUE THREAD

**Issue by linda-chin** [Azure/azure-sdk-for-net#34657]
### Library name and version

Azure.ResourceManager.Sql 1.2.0

### Query/Question

In the old fluent API we could create SQL server with setting `WithoutAccessFromAzureServices()`. Something like:
```
ISqlServer sqlServer = await azure.SqlServers
    .Define(sqlServerName)
    .WithoutAccessFromAzureServices() <-- this line
    .CreateAsync(token);
```

What's the equivalent of this in `Azure.ResourceManager.Sql`?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @linda-chin , Thank you for using Azure SDK for .NET.
The method you mentioned in Track1 WithoutAccessFromAzureServices() actually was a customzied method which add or remove a specified firewall rules called: "AllowAllWindowsAzureIps".
https://github.com/Azure/azure-libraries-for-net/blob/7d85e294e4e7280c3f74b1c41438e2f20bce2052/src/ResourceManagement/Sql/SqlServerImpl.cs#L500
In Track2, we have no convenience layer yet, so you have to manually add or remove those rules.
