### ISSUE TITLE
Make sure RunOnlyOnPlatforms works as expected with sparse matrix testing updates

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#34659]
The sparse matrix test updates allow the Core CI pipeline to be split amongst several sub pipelines. Each pipeline runs a subset of the tests on a specific platform, i.e. we don't run the full set of tests on each platform like we did previously or like we still do for individual library pipelines. When you combine this behavior with the RunOnlyOnPlatform attribute, you have the potential for a given test to not be run at all in a Core CI run. This is mitigated by the fact that the test should still be run as part of the library CI pipeline. However, it would be good to determine whether there is a way that the test splitting can take into account this attribute and ensure that tests using this attribute are assigned to a platform that they can actually run on.

/cc @weshaggard @m-nash

**Comment by JoshLove-msft** [comment]
This was split off from https://github.com/Azure/azure-sdk-for-net/issues/34264

**Comment by weshaggard** [comment]
@JoshLove-msft just so it is clear the Core tests should be running on the entire matrix. The tests for the tests projects that depend on core are running sparse. For this RunOnlyOnPlatforms options is it about the core tests themselves? If so I think we are good here.

**Comment by JoshLove-msft** [comment]
RunOnlyOnPlatforms is [used](https://grep.app/search?q=RunOnlyOnPlatforms) in Identity, Monitor.Query, and Key Vault so I think this is an issue still.

**Comment by weshaggard** [comment]
By why do we need to run those specific tests in the Core pipeline? Why wouldn't running them in their own pipeline be enough coverage?

**Comment by JoshLove-msft** [comment]
I guess the issue is that those pipelines will not run automatically outside of a PR that changes something. The test pipelines will run automatically, but if those are not monitored, then in theory, Azure.Core could change something that breaks one of these other libraries in a way that is not detected by the Core pipeline. I think it is probably a very unlikely scenario, but I believe it is still a gap. If it isn't worth the investment in closing the gap, I would be okay with closing the issue.

**Comment by weshaggard** [comment]
There are definitely gaps as we cannot ever test all combinations and we are simply trying to cover the common cases in the core ci. If we find more issues that we want to cover then we should figure out how to add those tests specifically to the core tests so we don't have to worry about them being caught in other library tests. 

I would suggest we accept the risk for now and add coverage if we find real issues later and just close this issue.
