### ISSUE TITLE
Where is the documentation for this?

### ISSUE THREAD

**Issue by 1TheMuffinMan** [Azure/azure-sdk-for-net#3466]
**Edit**: Can you help me find updated documentation for the lastest version of the Azure Scheduler SDK? The code sample library is a start, but the little documentation available is outdated. Please see https://github.com/Azure-Samples/scheduler-dotnet-getting-started/issues/1

**Comment by shahabhijeet** [comment]
@1TheMuffinMan there are N number of services in Azure.
Could you help us and be specific as to what service .NET SDK are you referring about?

**Comment by shahabhijeet** [comment]
@1TheMuffinMan ignore what I said, found the service.

**Comment by 1TheMuffinMan** [comment]
@shahabhijeet Looks like I forgot to update this question. The issue I'm experiencing here is for the older Azure Scheduler .NET SDK, so I've moved on to trying to get the new version working. Here's the updated question:

https://github.com/Azure-Samples/scheduler-dotnet-getting-started/issues/1

**Comment by dend** [comment]
@shahabhijeet what is the Azure Scheduler NuGet package that we can use to generate the documentation?

**Comment by 1TheMuffinMan** [comment]
@dend Here you go https://www.nuget.org/packages/Microsoft.Azure.Management.Scheduler

**Comment by 1TheMuffinMan** [comment]
Specifically, the unknown area is configuring authentication when initializing the `SchedulerManagementClient`.  https://github.com/Azure-Samples/scheduler-dotnet-getting-started/blob/master/SchedulerArmSDKTemplate/Program.cs#L25

There are two ways to authenticate:
1. Using a token (this is documented, but the documentation is old and doesn't reflect the most current Azure Portal UI https://github.com/Azure-Samples/scheduler-dotnet-getting-started/blob/master/SchedulerArmSDKTemplate/App.config#L7)
2. Using a management certificate (not documented). This way seems easiest, so I'd like to know how I can get that working.

**Comment by dend** [comment]
@1TheMuffinMan thanks for the feedback, it will be relatively straightforward to onboard the new package to the docs site.

@shahabhijeet can you confirm that the above makes sense? If it does, then we should proceed with the onboarding.
