### ISSUE TITLE
ServiceBus feedback

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#3467]
I've updated to the latest version (1.0.0) and noticed the following:

1. All Create/Update parameter classed are prefixed with `SB`. Except `Rule`.
1. When creating namespace, `SBNamespace` takes a `Sku` which has a `Name` and a `Tier`. This seems to be redundant, as it's the same thing: basic, standard, or premium. Why the two properties are needed?

**Comment by anuchandy** [comment]
These changes are coming from the swagger api spec. tagging @arundsouza [From service team] to comment.

**Comment by SeanFeldman** [comment]
ping

**Comment by SeanFeldman** [comment]
Almost 2 years 😂
Glad the .NET Standard client has added management operations.
