### ISSUE TITLE
[Data Lake Store] Empty folders should be included in recursive upload/download

### ISSUE THREAD

**Issue by matt1883** [Azure/azure-sdk-for-net#3468]
When performing a recursive upload or download, empty folders that exist in the source should be created in the destination.

Current behavior (in the upload functionality, at least) is that empty folders are ignored.

Repro using Microsoft.Azure.Management.DataLake.Store v2.2.0:
* Create a local folder with the following structure:
    ```
    C:\path\to\myData\
        emptyFolder\
            (nothing -- keep this empty)
        nonEmptyFolder\
            file1.txt
    ```

* Upload myData to ADLS using the following .NET code:

    ```csharp
    adlsFileSystemClient.FileSystem.UploadFolder(adlsAccountName, @"C:\path\to\myData", "/myData", 
    recurse: true);
    ```

* Explore the data in the ADLS account and see that the directory `/myData/emptyFolder` does not exist.

**Comment by rahuldutta90** [comment]
@ro-joowan This should be fixed in the new SDK.

**Comment by ro-joowan** [comment]
@rahuldutta90 Thanks. Closing
