### ISSUE TITLE
[QUERY] How to write test case for library built upon azure-sdk

### ISSUE THREAD

**Issue by sophiaso** [Azure/azure-sdk-for-net#34690]
### Library name and version

Azure.ResourceManager.Dns 1.0.1

### Query/Question

We are implementing our own service logic based on azure-sdk library, e.g., wrapping our own service client using dns zone sdk. 
```csharp
public Task AddDnsARecordAsync(string name, string ip, CancellationToken cancellationToken)
{
   DnsZoneResource resource = GetDnsZoneResource();
   // Build DnsARecordData aRecordData
   return resource.GetDnsARecords().CreateOrUpdateAsync(WaitUntil.Completed, name, aRecordData, ifNoneMatch: "*");
}
```

Now I want to test the `AddDnsARecordAsync` method, to test that if I add the same A record twice, the second one should fail with conflict. I tried to leverage the test framework to do the test, after checking the [test framework doc](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/README.md), seems it only supports testing sdk itself, but the framework is not released as a package. As the `DnsZoneResource` and `DnsARecordCollection` are not interfaces, which cannot be mocked for the test. Is there any recommended way to do the test?

**Comment by dvbb** [comment]
Hi @sophiaso 
Here is a sample for test DNS without TestFramework, I hope this will help

``` 
<PackageReference Include="Azure.Core" Version="1.28.0" />
<PackageReference Include="Azure.ResourceManager" Version="1.4.0" />
<PackageReference Include="Azure.Identity" Version="1.8.2" />
<PackageReference Include="Azure.ResourceManager.Dns" Version="1.0.1" />
```

```
ArmClient Client = new ArmClient(new ClientSecretCredential("tenantId", "clientId", "clientSecret"), "subscription");
ResourceGroupResource resourceGroup = (await Client.GetDefaultSubscriptionAsync().Result.GetResourceGroups().GetAsync("rgName")).Value;
DnsZoneResource dnsZone = (await resourceGroup.GetDnsZoneAsync("dnsZoneName")).Value;

DnsARecordCollection collection = dnsZone.GetDnsARecords();
DnsARecordResource aRecordResource = await collection.GetAsync("record name");
_ = await aRecordResource.UpdateAsync(new DnsARecordData()
{
    TtlInSeconds = 7200,
    DnsARecords =
    {
        new DnsARecordInfo()
        {
            IPv4Address = IPAddress.Parse("10.10.0.1")
        },
        new DnsARecordInfo()
        {
            IPv4Address = IPAddress.Parse("10.10.0.2")
        },
    }
});
```

**Comment by sophiaso** [comment]
@dvbb thanks for the reply, not sure if I didn't make the question clear. I think the code block you shared is about how to use the sdk, now what I want to do is test the code block. e.g., based on the code block you shared, if I have a method:
```csharp
public Task CreateARecordAsync()
{
ArmClient Client = new ArmClient(new ClientSecretCredential("tenantId", "clientId", "clientSecret"), "subscription");
ResourceGroupResource resourceGroup = (await Client.GetDefaultSubscriptionAsync().Result.GetResourceGroups().GetAsync("rgName")).Value;
DnsZoneResource dnsZone = (await resourceGroup.GetDnsZoneAsync("dnsZoneName")).Value;

DnsARecordCollection collection = dnsZone.GetDnsARecords();
DnsARecordResource aRecordResource = await collection.GetAsync("record name");
_ = await aRecordResource.UpdateAsync(new DnsARecordData()
{
    TtlInSeconds = 7200,
    DnsARecords =
    {
        new DnsARecordInfo()
        {
            IPv4Address = IPAddress.Parse("10.10.0.1")
        },
        new DnsARecordInfo()
        {
            IPv4Address = IPAddress.Parse("10.10.0.2")
        },
    }
});
}
```

Now I want to test this `CreateARecordAsync` method in my own unit test, e.g., some case like https://github.com/Azure/azure-sdk-for-net/blob/248db5828ac6bf4bb334447f5d40022e5040b5c7/sdk/dns/Azure.ResourceManager.Dns/tests/Scenario/RecordTest.cs#L92, the test cases for sdk leverage the sdk test framework, while in my own unit test, as I cannot reference the test framework directly, writing the test becomes difficult.

**Comment by dvbb** [comment]
If you want to use `Azure.Core.TestFramework` in an external solution, it's hard.
1. you need to build `Azure.Core.TestFramework`  source project and find its dll file in this folder( `azure-sdk-for-net\artifacts\bin\Azure.Core.TestFramework\Debug\net6.0\Azure.Core.TestFramework.dll`), so that you can reference this dll in your own test project
2. The tests for Dotnet MGMT SDK(Azure.ResourceManager.*) have some reference codes in [this folder](https://github.com/Azure/azure-sdk-for-net/tree/main/common/ManagementTestShared/Redesign), you need to copy these files into your test project and rewrite some methods (some accessibility issues)

>  As the DnsZoneResource and DnsARecordCollection are not interfaces, which cannot be mocked for the test.

If you need to mockDnsZoneResource and DnsARecordCollection,  we'll have model factory feature added in a future version.

**Comment by sophiaso** [comment]
> If you need to mockDnsZoneResource and DnsARecordCollection,  we'll have model factory feature added in a future version.
@dvbb yes, the problem is currently `DnsZoneResource` and `DnsARecordCollection` cannot be mocked, that's the reason I tried to use the test framework for the test. For the future version, so at least it will be months later?

**Comment by dvbb** [comment]
About the model factory feature in MGMT SDK stable release, Add @ArthurMa1978 for confirm

**Comment by ArthurMa1978** [comment]
The model factory will be shipped in this month, here is the issue https://github.com/Azure/azure-sdk-for-net/issues/35189.
