### ISSUE TITLE
[BUG] Updating to Visual Studio 2022 17.5.1 breaks the VisualStudioCredential for EventGrid

### ISSUE THREAD

**Issue by elias-rod** [Azure/azure-sdk-for-net#34699]
### Library name and version

Microsoft.Extensions.Azure 1.6.0

### Describe the bug

[This sample project](https://github.com/elias-rod/vsSituation/tree/main) runs correctly with Visual Studio 17.4.4 but with version 17.5.1 the VisualStudioCredential for EventGrid breaks the program. However, the project also includes ServiceBus, which takes the credentials from Visual Studio correctly with both versions.
The error says "Azure.Identity.CredentialUnavailableException: VisualStudioCredential.GetToken was unable to retrieve an access token. The JSON-RPC connection with the remote party was lost before the request could complete."

### Expected behavior

Work with Visual Studio 2022 17.5.1 by sending an Azure Eventgrid event

### Actual behavior

Breaks with Visual Studio 2022 17.5.1 with the following [errors](https://github.com/elias-rod/vsSituation/blob/main/error.txt).

### Reproduction Steps

1. Create an Azure Event Grid topic 
2. Grant the permission to your user: EventGrid Data Sender
3. Download the [repo](https://github.com/elias-rod/vsSituation/tree/main)
4. Update Program.cs with the EventGrid endpoint
5. Login in Visual Studio (not Azure CLI)
6. Run
7. Should see "Event sent" in the logs, but that never happens

Optionally
1. Create Azure Service Bus queue
2. Grant the permission to your user: Azure Service Bus Data Owner
3. Uncomment the Service Bus related lines in Program.cs and Function1.cs
4. Update Program.cs with the ServiceBus endpoint 
5. Run
6. Will see "Message sent" in the logs but still no "Event sent"

### Environment

Visual Studio 2022 17.5.1
Windows 10

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by crmann1** [comment]
This is due to VS needing to request permissions with the EventGrid team for access. This request is currently in progress. Once it is completed, no client side changes will be required
