### ISSUE TITLE
Outdated .NET package linking to Microsoft.Azure.Management.ResourceManager.Fluent

### ISSUE THREAD

**Issue by scottsauber** [Azure/azure-sdk-for-net#34711]
This [link](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resource-manager?view=azure-dotnet) still uses [Microsoft.Azure.Management.ResourceManager.Fluent](https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceManager.Fluent) which is deprecated. 

I'm willing to send a PR to update this and update the code sample.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 553fc3f5-7bb0-db05-00e8-e18c550c2869
* Version Independent ID: 219ec4a2-b185-2c5b-0174-c8577f3f894e
* Content: [Azure Resource Manager SDK for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resource-manager?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/resource-manager.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/resource-manager.md)
* Service: **resourcemanager**
* GitHub Login: @pallavit
* Microsoft Alias: **pallavit**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
Fixed by [#2285](https://github.com/Azure/azure-docs-sdk-dotnet/pull/2285).   Thank you for helping to improve the Azure SDK experience, @scottsauber!
