### ISSUE TITLE
[QUERY] Cannot create Receiver from ServiceBusClient once the client has participated in a TransactionScope

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-sdk-for-net#34714]
### Library name and version

Azure.Messaging.ServiceBus 7.12.0

### Query/Question

It seems that once a `ServiceBusSender` has participated in a `TransactionScope`, the `ServiceBusClient` used to create that `ServiceBusSender` can no longer receive messages from other entities.

For context: I have a web app that sends messages to various queues and topics. Some of my endpoints need to send messages to more than one queue/topic, and in those cases I want all of the messages to be sent or none of them, so I wrap the sending in a `TransactionScope`.

Here's a short example that demonstrates the issue. I can even reproduce it with a single sender, to make it as simple as possible:

```cs
var serviceBusClient = new ServiceBusClient("...",	new ServiceBusClientOptions
    {
        EnableCrossEntityTransactions = true,
    });

var sender = serviceBusClient.CreateSender("some_queue");

using (var ts = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
    await sender.SendMessageAsync(new ServiceBusMessage());
    ts.Complete();
}

var receiver = serviceBusClient.CreateReceiver("some_other_queue");
var receivedMessage = await receiver.ReceiveMessageAsync(); // throws System.InvalidOperationException: 'Local transactions cannot span multiple top-level entities such as queue or topic
```

If I didn't reuse `serviceBusClient` but instead created the `receiver` from a brand new instance of `ServiceBusClient` then I don't get the exception. But I thought the recommendation was to register `ServiceBusClient` as singleton? So the sending part and the receiving part of my example above might as well occur in two separate parts of the application, triggered by two different users, and the result would be the same.

In the old `Microsoft.Azure.ServiceBus` lib where you had to be more involved with specifying which transfer entity to send via, I never ran into this exception. And I've tried to read everything I can find related to doing this using the new library, but there isn't much info out there.

I would be very grateful if someone could help me out.

### Environment

.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.201\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  7.0.201 [C:\Program Files\dotnet\sdk]

**Comment by JoshLove-msft** [comment]
Hi @johnknoop,
Your observation is correct - the receiver for a different entity cannot be created from a client configured with cross-entity transactions after a sender for a different entity has already participated in a transaction. This is discussed in more detail in the [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md#cross-entity-transactions), and in our [sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample06_Transactions.md#transactions-across-entities) for cross-entity transactions. So in this case, you would need to use a separate client for your receiver that is not involved in the cross-entity transactions.

**Comment by johnknoop** [comment]
@JoshLove-msft So what is the general recommendation for managing `ServiceBusClient` instances then? I suppose I could keep two separate instances, one used for sending and one used for receiving, but I would feel much more comfortable following some sort of recommended pattern.

**Comment by JoshLove-msft** [comment]
In general, you would use a singleton as you've mentioned. You would only need to hold more instances if you are using the cross-entity transaction feature and you need to perform some operations outside transactions. In that case you would need two instances - one for your non-transaction operations, and another for your transaction operations.

**Comment by johnknoop** [comment]
Do you mean I only need two instances in total – one for transactional and one for non-transactional operations? Or will I need a unique `ServiceBusClient` for every queue that I send to as a transaction?

This is what my application looks like today, a bit simplified (there are more API endpoints and more queues):

![image](https://user-images.githubusercontent.com/3394270/222980235-32557e9f-cd74-4fda-8de0-8bbb68e50984.png)

Using the old `Microsoft.Azure.ServiceBus` I made this work with a singleton instance of `ServiceBusConnection` by leveraging the "send via" feature. But that features doesn't seem to be exposed anymore. But if you're saying I only need two instances of the client in total, then that's fine. But if you're saying I need to maintain a bunch of named instances, one for each API endpoint more or less, then I'd say that would be a blocker for me to upgrade to the new library :-/

**Comment by johnknoop** [comment]
@JoshLove-msft Thanks for the answer.

Sorry, yes, I meant completing an incoming message and sending another message within a transaction.

The first `ServiceBusClient` you refer to, the one used for all send-only transactions... would that one also be reusable for all non-transactional sending and receiving? I have a few of those as well, where it's only a single message being sent for example. In those cases I don't even wrap it in a transaction.

If I'm reading you right, this is what I would need (I've color-coded the `ServiceBusClient` instances and associated each operation with a color). Does this look correct to you?

![image](https://user-images.githubusercontent.com/3394270/223222739-d20bc7b7-c21b-47ed-aa8c-0e622be19b7d.png)

Thanks again for the help!

**Comment by JoshLove-msft** [comment]
> The first `ServiceBusClient` you refer to, the one used for all send-only transactions... would that one also be reusable for all non-transactional sending and receiving?

Technically it is usable for non-transactional sending, but it would still use the send-via entity when it doesn't actually need to, so it would be better to use a **separate client for all non-transactional operations**.

**Comment by JoshLove-msft** [comment]
> If I'm reading you right, this is what I would need (I've color-coded the `ServiceBusClient` instances and associated each operation with a color). Does this look correct to you?

Yes, this looks correct.

**Comment by johnknoop** [comment]
> > The first `ServiceBusClient` you refer to, the one used for all send-only transactions... would that one also be reusable for all non-transactional sending and receiving?
> 
> Technically it is usable for non-transactional sending, but it would still use the send-via entity when it doesn't actually need to, so it would be better to use a **separate client for all non-transactional operations**.

Ok, got it.

If I don't bother with settling messages inside the transactions, but just perform a bunch of sends inside a transaction, like this:

![image](https://user-images.githubusercontent.com/3394270/223226059-2edb3e35-a257-4e08-9c4e-7791b9f5743c.png)

...that would require two separate instances right? One for the receiving of messages and one for the transactional sending?

**Comment by JoshLove-msft** [comment]
Yes, that's right.

**Comment by johnknoop** [comment]
> Yes, that's right.

Nice!

A final question... since I've previously only had a singleton `ServiceBusConnection` which will be replaced with 3-4 separate `ServiceBusClient` instances... are there any negative side effects one to this that one might not expect? I'm guessing the performance/load impact is negligible. But do you know of any other consequences people tend to run into when migrating from a single instance to multiple? Like deadlocks because of instances waiting for each other etc?

**Comment by JoshLove-msft** [comment]
There shouldn't be a perf impact to using a handful of ServiceBusClients - there wouldn't be any locking considerations either.

**Comment by johnknoop** [comment]
Thanks

**Comment by johnknoop** [comment]
@JoshLove-msft 

I've started experiencing a different error instead. I've been trying to isolate the cause for weeks now. I'm still working on that, but I thought I might check with you as well in the meantime, in case this rings a bell for you.

I'm running a single instance of an .NET7 webapp.

This is the order of events that triggers the exception:

1. Application launches and starts listening to a queue using a dedicated instance of `ServiceBusClient`.
2. A message is received from that queue. The message handler only starts a new `TransactionScope` in which it sends a message to a different queue, using an instance of `ServiceBusClient` called `serviceBusClientForSending`.
3. An HTTP endpoint is called which executes the following pseudo code:
  a. Read from database
  b. Start a `TransactionScope`
  c. Write to database
  d. Send a message to the same queue as in step 2, using the same instance of `ServiceBusClient`
  e. Complete transaction
4. A different HTTP endpoint is called which executes the following pseudo code:
  a. Start a `TransactionScope`
  b. Send a message to the same queue as in steps 2 and 3, using the same instance of `ServiceBusClient`.
  c. Send another message to a different queue, also using the same instance of `ServiceBusClient`.

This last step (4c) results in the following error:
> Azure.Messaging.ServiceBus.ServiceBusException: Transaction hasn't been declared yet, or has already been discharged (GeneralError)

But not every time. I've written a nodejs program that executes these steps in order to reproduce the error, and sometimes I have to run it 2-3 times before I get the error. But once I get it, it does seem to happen every time after that.

I also tried creating a blank .NET console app which carries out these same steps, but I wasn't able to reproduce it. So right now I'm in the process of removing parts of my application (it's a pretty big codebase) piece by piece to see if I can isolate a minimal example that reproduces the error. But it takes time, so I thought I might just check with you as well, in case you can spot something based on my description.

**Comment by JoshLove-msft** [comment]
Hmm any chance you can include code snippets for each of the steps?
