### ISSUE TITLE
Complement to WithDnsServer() ?

### ISSUE THREAD

**Issue by CodyBatt** [Azure/azure-sdk-for-net#34751]
I see that there is a "WithDnsServer()" and the effect is additive, but it would be nice if this page explained how to REMOVE a Dns server from the list.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d68bdbc7-4212-8f18-1199-e8f92ec238b5
* Version Independent ID: f74a5671-8d63-c537-10d0-52c0de6d068d
* Content: [IUpdate Interface (Microsoft.Azure.Management.Network.Fluent.Network.Update) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.network.fluent.network.update.iupdate?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Network.Fluent.Network.Update/IUpdate.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Network.Fluent.Network.Update/IUpdate.xml)
* Service: **virtual-network**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @CodyBatt.  Thank you for your feedback.  The `Microsoft.Azure.Management.Network.Fluent` package is deprecated and receiving only critical bug and security fixes.  As we recommend preferring the [Azure.ResourceManager.Network](https://www.nuget.org/packages/Azure.ResourceManager.Network/) package as a replacement, we do not plan on adding further examples to the existing documentation.
