### ISSUE TITLE
TokenCredentials don't seem to work

### ISSUE THREAD

**Issue by olydis** [Azure/azure-sdk-for-net#3477]
@shahabhijeet, see
https://github.com/Azure/autorest/issues/2428
https://stackoverflow.com/questions/45038533/using-an-autorest-c-sharp-client-to-access-a-web-api-with-a-bearer-token-token

**Comment by bkwdesign** [comment]
One note: IDK how important the `autorest --reset` command is.. since I'm a newbie and this is a fresh installation on my machine, I presume my omission of this command is not the culprit of this issue.

**Comment by shahabhijeet** [comment]
@bkwdesign can you confirm if your Tenant behind 2FA?
Also could you try providing UserIdentifier.Any instead of initializing UserIdentity object.

**Comment by bkwdesign** [comment]
@shahabhijeet - I'm new to Azure and have not yet tried to set up multi-factor authentication

**Comment by bkwdesign** [comment]
I just re-ran my autorest command, but, this time it seems to have included the appropriate code that was missing before...

![autorest_attempt2](https://user-images.githubusercontent.com/3177513/28267654-01b38382-6ac9-11e7-86d3-bb7509e1f580.png)

I did not change anything on my machine, this is clearly user error, however.. I either:

 - perhaps ran the original command with the older `--AddCredentials` syntax
 - I did run the `autorest --reset` command this time, whereas I don't think I did originally

**Comment by olydis** [comment]
Glad it's resolved! 🙂 I'll close, please let us know if you hit further issues.
