### ISSUE TITLE
[ACR] Do not require audience on ClientOptions

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#34785]
@lmolkova is working with the service team to understand whether we will need to continue requiring callers to pass `Audience` into ACR clients, or whether we can set a default of "https://containerregistry.azure.net".

Once this is decided, implement the decided outcome.

**Comment by lmolkova** [comment]
Based on the information from the service team, we should proceed with defaulting to "https://containerregistry.azure.net/" when the audience is not set (for all clouds).

**Comment by annelo-msft** [comment]
- Update TSG with Java example as well
