### ISSUE TITLE
Tokenization Issue

### ISSUE THREAD

**Issue by afische4** [Azure/azure-sdk-for-net#34793]
### Library name and version

Azure.Search.Documents.SearchClient

### Query/Question

Why does the asterisk (*) cause the query to skip analysis and go straight to search for Japanese/Chinese/Thai? I still want the capability of partial term search so I want * on the end of the query, however I still want the query to be tokenized. This is a big problem for these three languages as they do not use spaces, so the terms are not delimited into tokens that way. So, we cannot do partial term search in these 3 languages because otherwise the search treats the entire string of characters as one token, rather than searching by word. 

### Environment

.NET SDK 7.0.200

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Adding @gmndrg from the Search Service team best able to assist you.

**Comment by gmndrg** [comment]
Hello @afische4 this is by design: https://learn.microsoft.com/azure/search/search-query-partial-matching

"For regular expression, wildcard, and fuzzy search, analyzers are not used at query time. For these query forms, which the parser detects by the presence of operators and delimiters, the query string is passed to the engine without lexical analysis. For these query forms, _the analyzer specified on the field is ignored_."

You will have to consider something like using a custom analyzer instead of using wildcard as listed under https://learn.microsoft.com/en-us/azure/search/search-query-partial-matching#solving-partialpattern-search-problems

**Comment by afische4** [comment]
I already tried the custom analyzer but suggesters aren’t supported by
custom analyzers so that doesn’t work for my project. I know that it is by
design, and it makes sense for every language that uses spaces, but it
messes up searches in Chinese, Japanese, and Thai when it skips the
analyzer because the “words” aren’t separated by spaces. To work around the
problem I was having, I just removed the * if a query came in that was in
one of those 3 languages. But that means no partial term search on the last
term unfortunately.

**Comment by afische4** [comment]
The other way I had tried to work around this problem was using the AnalyzeAsync method to get the tokens, concatenating the tokens with spaces between each one, adding a * to the last one, then using SearchAsync on that string instead. Its not ideal performance to be making two calls to acs so I went with removing the * for japanese, chinese, and thai searches..

**Comment by gmndrg** [comment]
Hello @afische4 thank you for waiting on the response. I'll let you know in a few days if there is any other workaround other than having 2 different queries for this scenario.

**Comment by gmndrg** [comment]
Hello @afische4 the workaround would be to either use 2 different queries. 
You can try the following and see if the workaround would work for you:
While custom analyzers are not available for suggesters, the suggester is mostly a custom analyzer on top of a regular search request. You can try to emulate the suggester behavior with a custom analyzer configuration. There's perhaps a combination of tokenfilters/tokenizer that would mimic what the japanese analyzer does (probably a mix of microsoft_language_tokenizer with language=japanese with some edgeNGram_v2 with option side=front).  If that's not possible, then the 2 queries would be the way to go. Unfortunately, the product up front doesn't offer a straight up solution for the behavior you need but you need a workaround instead.
Also, consider the behavior of removing the asterisk when using suggesters. The goal of the suggester API is that you don't have to use an asterisk as the text is already analyzed in a way that facilitate prefix match.
I hope this helps.

**Comment by ShivangiReja** [comment]
If you have any questions related to the search service, please raise an issue at [Azure Search · Community](https://feedback.azure.com/d365community/forum/9325d19e-0225-ec11-b6e6-000d3a4f07b8). For any SDK-related questions, feel free to create issues on [Azure SDK for .NET Github](https://github.com/Azure/azure-sdk-for-net/issues).
