### ISSUE TITLE
[BUG] TextAnalytics: AnalyzeHealthcareEntitites stops responding

### ISSUE THREAD

**Issue by ahmadbjanthala** [Azure/azure-sdk-for-net#34802]
### Library name and version

Azure.AI.TextAnalytics SDK / AnalyzeHealthcareEntities

### Describe the bug

Package Name: Azure.AI.TextAnalytics
Package Version: 5.2.0
Operating System: Windows
.NET runtime version: .NET6
Visual Studio Enterprise 2022 version: 17.4.4
Region: WestEroup

I got this issue couple of times before on the west Europe region so I change it to the east us and now it's happing again, you can check this issue id for your reference #33509

await healthOperation.WaitForCompletionAsync();
suddenly stop working!
no response

please advice !in

### Expected behavior

await healthOperation.WaitForCompletionAsync(); 
was working fine 

### Actual behavior

now not working

### Reproduction Steps

await healthOperation.WaitForCompletionAsync();

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by joseharriaga** [comment]
This was due to an issue with the service, specifically affecting Text Analytics for health. According to the service team, the problem has been mitigated.
