### ISSUE TITLE
[BUG] Azure.Messaging.EventHubs.Processor - UpdateCheckpointAsync fails with NullReferenceException

### ISSUE THREAD

**Issue by smafre** [Azure/azure-sdk-for-net#34806]
### Library name and version

Azure.Messaging.EventHubs 5.8.0

### Describe the bug

My app has always finished with this line of code after handling an event from my event hub:
`await eventArgs.UpdateCheckpointAsync(eventArgs.CancellationToken);`
 
When I upgrade to version 5.8.0 of `Azure.Messaging.EventHubs` and `Azure.Messaging.EventHubs.Processor` the very same line of code (`UpdateCheckpointAsync`) fails with this exception:

``{
    "_typeTag": "NullReferenceException",
    "TargetSite": "System.Threading.Tasks.Task UpdateCheckpointAsync(System.String, Int64, System.Nullable`1[System.Int64], System.Threading.CancellationToken)",
    "Message": "Object reference not set to an instance of an object.",
    "Data": [],
    "InnerException": null,
    "HelpLink": null,
    "Source": "Azure.Messaging.EventHubs.Processor",
    "HResult": -2147467261,
    "StackTrace": "   at Azure.Messaging.EventHubs.EventProcessorClient.UpdateCheckpointAsync(String partitionId, Int64 offset, Nullable`1 sequenceNumber, CancellationToken cancellationToken)n   at EventHandler.HandleEvent(ProcessEventArgs eventArgs) in /app/EventHandler.cs:line 67n   at EventHubProcessorService.ProcessEventHandler(ProcessEventArgs eventArgs) in /app/EventHubProcessorService.cs:line 87"
}``

If I downgrade the version of the EventHubs-nuget packages to 5.7.5 the issue goes away and the app runs happily.

### Expected behavior

Based on the changelog/release notes for version 5.8.0 of `Azure.Messaging.EventHubs` and `Azure.Messaging.EventHubs.Processor` I expect to be able to update without changing anything in my code, at least not anything regarding `await eventArgs.UpdateCheckpointAsync(eventArgs.CancellationToken);`.

### Actual behavior

The actual behavior is that my app does no longer work properly.

### Reproduction Steps

Handle any event using version 5.8.0 of `Azure.Messaging.EventHubs` and `Azure.Messaging.EventHubs.Processor` and perform `await eventArgs.UpdateCheckpointAsync(eventArgs.CancellationToken);` when event is handled.

### Environment

App is a dotnet 7 minimal API running in docker container in kubernetes. Runtime image is mcr.microsoft.com/dotnet/aspnet:7.0-alpine-amd64.

Output from `dotnet --info`:
Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by kordoulakis** [comment]
Encountering this too, fixed by going back to 5.7.5

**Comment by jsquire** [comment]
Hi @smafre.  Thank you for reaching out and we regret that you're experiencing difficulties.  I'm unable to repro in our test suite; we'll start to investigate further.  Are you able to provide the full stack trace for the exception, by chance?

**Comment by jsquire** [comment]
@JoshLove-msft:  This seems like it may be related to the OTel changes.   I'd appreciate your thoughts on whether there's a specific configuration that may help to repro.
