### ISSUE TITLE
DNS fluent refresh work items

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-for-net#3481]
Following features are requested from service team (Same for java fluent as well): 

| Issue | Resolution |
| --- | --- |
| The ability to set the TTL of a CNAME record set | Will create ‘define’ and ‘update’ flows for CNAME similar to creating A records, include support for WithTimeToLive(n) |
| The ability to enumerate all record sets in a zone independent of record type (enumeration of specific types *is* supported) | Add ‘ListRecordSets’ to IDnsZone in parallel with existing TxtRecordSets, NSRecordSets, etc |
| The ability to create multi-string TXT records (multiple strings in the same record, as opposed to multiple records per record set) | Keep existing API signature, but allow long strings in each TXT record within the record set. On create/update, each long string should be chopped up into 255-character segments, and each segment placed into a separate string within the record On get, the separate strings within each record should be concatenated and returned as a single string. All this applies within each record in the record set. The record set is still a list of records No need for validation of string length limits etc…just let the server-side limits/errors apply.  |
| The ability to specify the page size used during enumeration of zones or record sets | expose an overload of List methods in DnsZones and RecordSets that takes OData top (integer) parameter. |
| Supporting new RecordSetNameSuffix query string parameter | For each specific record sets collection model (AARecordSets, MxRecordSets etc..) expose an overload of List method that takes RecordSetNameSuffix parameter. We can also expose an overload of listRecordSets (see 2 that takes  RecordSetNameSuffix parameter. |
| Access to If-Match / If-None-Match ETAG checks for concurrency protection | By default, no etag checks (same as today) `Get: Expose Etag as property`  `Create: .WithEtagCheck()       // Enable if-none-match *`  `Update/Delete: .WithEtagCheck(etag-value)   // Enable if-match <etag-value>` `Update: .WithEtagCheck() // Enable if-match using etag value retrieved during Apply. .WithEtagCheck(etag-value)   // Enable if-match <etag-value>`  `Delete: .WithEtagCheck(etag-value)   // Enable if-match <etag-value>` No need for GET before DELETE. All above applies to both zones and record sets. |

**Comment by johanjeppson** [comment]
Any updates on this? Especially the possibility to set TTL for CNAME record sets.

**Comment by martinsawicki** [comment]
@anuchandy  wasn't this all done in v1.3?

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#50
