### ISSUE TITLE
[EventHub]FlushSendsAllEventsAndWaitsForHandlersWithDefaultOptions failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#34831]
EventHub nightly test runs are failing with:

> Error message
> System.OperationCanceledException : The operation was canceled.
> 
> 
> Stack trace
>    at System.Threading.CancellationToken.ThrowOperationCanceledException()
>    at System.Threading.CancellationToken.ThrowIfCancellationRequested()
>    at Azure.Core.Pipeline.TaskExtensions.WithCancellationTaskAwaiter.GetResult() in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 210
>    at Azure.Messaging.EventHubs.Producer.EventHubBufferedProducerClient.FlushInternalAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs:line 1347
>    at Azure.Messaging.EventHubs.Producer.EventHubBufferedProducerClient.FlushAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubBufferedProducerClient.cs:line 1023
>    at Azure.Messaging.EventHubs.Tests.EventHubBufferedProducerClientLiveTests.FlushSendsAllEventsAndWaitsForHandlersWithDefaultOptions() in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Producer/EventHubBufferedProducerClientLiveTests.cs:line 928
>    at Azure.Messaging.EventHubs.Tests.EventHubBufferedProducerClientLiveTests.FlushSendsAllEventsAndWaitsForHandlersWithDefaultOptions() in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Producer/EventHubBufferedProducerClientLiveTests.cs:line 964
>    at Azure.Messaging.EventHubs.Tests.EventHubBufferedProducerClientLiveTests.FlushSendsAllEventsAndWaitsForHandlersWithDefaultOptions() in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Producer/EventHubBufferedProducerClientLiveTests.cs:line 964
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
>    at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2618039&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
This failed due to timeouts in service operations outside of the SDK's control
