### ISSUE TITLE
[KeyVault]UpdateSettingSync failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#34832]
KeyVault nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : User triggered Restore operation is in progress. Retry after the restore operation (Activity ID: 783bde20-be77-11ed-b60f-0022488d29c2)
> Status: 409 (Conflict)
> ErrorCode: Conflict
> 
> Content:
> {"error":{"code":"Conflict","message":"User triggered Restore operation is in progress. Retry after the restore operation (Activity ID: 783bde20-be77-11ed-b60f-0022488d29c2)"}}
> 
> Headers:
> x-ms-server-latency: REDACTED
> Cache-Control: no-cache
> X-Content-Type-Options: REDACTED
> x-ms-request-id: 783bde20-be77-11ed-b60f-0022488d29c2
> Strict-Transport-Security: REDACTED
> Content-Security-Policy: REDACTED
> X-Frame-Options: REDACTED
> Content-Type: application/json; charset=utf-8
> Content-Length: 176
> 
> 
> Stack trace
>    at Azure.Security.KeyVault.Administration.SettingsRestClient.GetSetting(String vaultBaseUrl, String settingName, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/keyvault/Azure.Security.KeyVault.Administration/src/Generated/SettingsRestClient.cs:line 212
>    at Azure.Security.KeyVault.Administration.KeyVaultSettingsClient.GetSetting(String name, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/keyvault/Azure.Security.KeyVault.Administration/src/KeyVaultSettingsClient.cs:line 83
>    at Castle.Proxies.Invocations.KeyVaultSettingsClient_GetSetting.InvokeMethodOnTarget()
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Azure.Core.TestFramework.InstrumentResultInterceptor.Intercept(IInvocation invocation) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/InstrumentResultInterceptor.cs:line 100
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.Intercept(IInvocation invocation) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 57
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Azure.Core.TestFramework.GetOriginalInterceptor.Intercept(IInvocation invocation) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/GetOriginalInterceptor.cs:line 28
>    at Castle.DynamicProxy.AbstractInvocation.Proceed()
>    at Castle.Proxies.KeyVaultSettingsClientProxy.GetSetting(String name, CancellationToken cancellationToken)
>    at Azure.Security.KeyVault.Administration.Tests.Sample4_UpdateSettings.UpdateSettingSync() in /mnt/vss/_work/1/s/sdk/keyvault/Azure.Security.KeyVault.Administration/tests/samples/Sample4_UpdateSettings.cs:line 38

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2618067&view=results

@jsquire for notification.

**Comment by heaths** [comment]
This is a known issue. I monitor these pipelines every morning.
