### ISSUE TITLE
SDK info should be updated to use new MarkDown files from specs repo

### ISSUE THREAD

**Issue by sergey-shandar** [Azure/azure-sdk-for-net#3483]
SDK info should be updated to use new MarkDown files from [specs repo](https://github.com/Azure/azure-rest-api-specs).
1. Update sdkinfo.json to reference to new files.
2. Make sure sdkinfo PS scripts can work with new markdown files.

**Comment by sergey-shandar** [comment]
https://github.com/Azure/azure-storage-php

**Comment by Petermarcu** [comment]
Since this has not happened yet, I'm going to assume it is not important and am closing it.
