### ISSUE TITLE
[FEATURE REQ][Azure OpenAI] Support ChatGPT Prompt Structure Builder

### ISSUE THREAD

**Issue by Danieladu** [Azure/azure-sdk-for-net#34830]
### Library name

Azure.AI.OpenAI

### Please describe the feature.

As the Azure OpenAI said, https://learn.microsoft.com/en-us/azure/cognitive-services/openai/chatgpt-quickstart?tabs=command-line&pivots=rest-api#understanding-the-prompt-structure, Azure OpenAI now support the GPT 3.5-turbe model and ChatGPT API.
It seems that the CHATGPT API is same with other completions, so if the SDK could add some utils to help build the ChatGpt prompt structure, It would be awesome.

**Comment by trrwilson** [comment]
Hello, @Danieladu! Thanks for getting in touch about Azure OpenAI.

Today, the specifics of what's supported for Chat between public OpenAI and Azure OpenAI are a little tricky:
- (non-Microsoft) OpenAI supports the gpt-3.5-turbo model *only* via the new Chat API (`/chat/completions` REST endpoint)
- (Microsoft) Azure OpenAI supports gpt-3.5-turbo model *only* via the older `/completions` API (`GetCompletions*()` in the .NET SDK) and no `/chat/completions` equivalent exists at the time of writing

So you can use the new gpt-3.5-model today with Azure OpenAI (including via the preview .NET SDK) but not the role-assigned prompt structure (.NET or not). If and when Azure OpenAI supports the new Chat message format, the .NET SDK will adopt support for it.

But aside from that, as a non-ML-science-specialist engineer myself, I very much agree that having helpful utilities to build and maintain prompt state in a ChatGPT-style experience is something we need a lot more of. Fortunately, that's an area with an enormous amount of effort going into it (across Azure and across the industry/community as a whole), and we'll doubtlessly see a lot of movement soon!
