### ISSUE TITLE
[Text Analytics] Verify agent OS failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#34835]
Text Analytics nightly test runs are failing with:

> Generating script.
> ========================== Starting Command Output ===========================
> /usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/mnt/vss/_work/_temp/c5deb6af-74b7-4d4c-886d-7c8c9648ff5f.ps1'
> Finishing: Verify agent OS

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2620042&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment]
This was caused by an issue with the service that is now mitigated.
