### ISSUE TITLE
Make DefaultAzureCredential configurable in Azure Functions

### ISSUE THREAD

**Issue by LwsSt** [Azure/azure-sdk-for-net#34845]
When working on my company laptop, we have an annoying problem when using `DefaultAzureCredentials`, and in turn any functions that connect to Azure resources using `DefaultAzureCredentials`

My understanding of how `DefaultAzureCredentials` works is this:
1. Attempt to use `EnvironmentCredentials`.
    - If no environment variables are found move on
1. Attempt to use `ManagedIdentityCredentials`
    - Try to connect to a specific IP address. 
    - If that fails move on
 1. Attempt to try other credential methods (VisualStudio, AzureCli, etc) until one succeeds

Unfortunately, because of reasons outside of my control, `DefaultAzureCredentials` works like this on my company laptop:
1. Attempt to use `EnvironmentCredentials`.
    - If no environment variables are found move on
1. Attempt to use `ManagedIdentityCredentials`
    - Try to connect to a specific IP address.
    - Company imposed firewall (firewall? network settings?) thinks you're connecting to a malicious IP address
    - Firewall spits back HTML page
    - `ManagedIdentityCredentials` gets confused an throws an exception.
 1. Attempt to try other credential methods (VisualStudio, AzureCli, etc) until one succeeds

When using Azure Functions, it does succeed with other authentication methods, but not before spewing errors to the console.

In ASP.NET Core apps, we work around this by configuring the `DefaultAzureCredentials` when running on a devs laptop. Something akin to:
```csharp
if (env.IsLocal())
{
    services.Configure<DefaultAzureCredentialOptions>(opt => opt.ExcludeManagedIdentity = true);
}

services.AddSingleton(sp =>
{
    var opts = sp.GetService<IOptions<DefaultAzureCredentialOptions>>().Value;

    return new DefaultAzureCredentials(opts);
}
```

However, when using Azure Functions (i.e. the Service Bus Azure Functions extension) there isn't an obvious extension point which allows the `DefaultAzureCredentials` to be configured.

After much digging around in this repo, I've managed to come up with this workaround:
```csharp
class CustomAzureComponentFactory : AzureComponentFactory
{
    private readonly DefaultAzureCredentialOptions options;
    public CustomAzureComponentFactory(IOptions<DefaultAzureCredentialOptions> options) => this.options = options.Value;
    public override object CreateClient(Type clientType, IConfiguration configuration, TokenCredential credential, object clientOptions) => throw new NotImplementedException();
    public override object CreateClientOptions(Type optionsType, object serviceVersion, IConfiguration configuration) => throw new NotImplementedException();

    public override TokenCredential CreateTokenCredential(IConfiguration configuration) => new DefaultAzureCredential(options);
}

if (env.IsLocal())
{
    services.Replace(ServiceDescriptor.Singleton<AzureComponentFactory, CustomAzureComponentFactory>());
}
```

Which does work, but feels very hacky.

Can have a way of configuring the `DefaultAzureCredentials` in Azure Function Extensions? Perhaps using the Options model I've described above?
Alternatively, having `AzureComponentFactory` as an implementation with `virtual` methods, instead of being an `abstract` class would also work.

**Comment by jsquire** [comment]
//cc: @christothes, @schaabs for possible work-arounds via Azure.Identity

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @LwsSt, this is configurable via the [UseCredential](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.azure.azureclientfactorybuilder.usecredential?view=azure-dotnet) method:

```c#
services.AddAzureClients(builder => builder.UseCredential(new DefaultAzureCredential(options))
```

**Comment by slaneyrw** [comment]
> Hi @LwsSt, this is configurable via the [UseCredential](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.azure.azureclientfactorybuilder.usecredential?view=azure-dotnet) method:
> 
> ```cs
> services.AddAzureClients(builder => builder.UseCredential(new DefaultAzureCredential(options))
> ```

If you are able to control the AzureClients registration... great.  However, if you use ( for example ) ServiceBus Trigger, it configures the AzureClient itself and you have no ability to override or alter the client or the default authentication chain.

Trying to optimize the dev "inner-loop" and waiting for the token chain to eventually resolve means it can take a few minutes just to have the function app ready to respond to triggers when we want to use the developers identity to connect ( using "fullyQualifiedNamespace" setting ).  We also want to remove the connection strings with the SharedAccessKey setting from our local configuration, in the same way we use Integrated authentication to SQL.

At the moment, we are seriously considering dropping our use of the Function runtime in favour of a "normal" web host, as we can control the host/environment and just pay the cost of not being able to use the consumption plan.

**Comment by JoshLove-msft** [comment]
The Functions triggers will still fall back to the UseCredential factory if no credential-specific settings are specified via config. Can you share what your config looks like?

**Comment by slaneyrw** [comment]
> The Functions triggers will still fall back to the UseCredential factory if no credential-specific settings are specified via config. Can you share what your config looks like?

2 settings  ( usersecrets )

  "AzureWebJobsServiceBus": {
    "fullyQualifiedNamespace": "<namespace>.servicebus.windows.net"
  },
  
  local.settings.json
  
    "AzureFunctionsJobHost:extensions:serviceBus:transportType": "amqpWebSockets",
    "AzureFunctionsJobHost:extensions:serviceBus:maxConcurrentCalls": 1,
    "AzureFunctionsJobHost:extensions:serviceBus:maxConcurrentSessions": 1



The ServiceBus Trigger can only use the credential factory from the AzureComponentFactory instance... which we can't control or influence.

**Comment by slaneyrw** [comment]
The functionapp host will _eventually_ acquire a token to connect as the developer azure AD identity, but it can take a while as it fails through the credential chain

**Comment by slaneyrw** [comment]
We can, of source, replace the registered AzureComponentFactory implementation, but the we'll have to replicate all the code from AzureComponentFactoryImpl class (and it's internal dependencies )

**Comment by JoshLove-msft** [comment]
Calling UseCredential should modify the CredentialFactory used by the AzureComponentFactory, provided this is done as part of Startup as I linked in the other issue.

**Comment by slaneyrw** [comment]
> Calling UseCredential should modify the CredentialFactory used by the AzureComponentFactory, provided this is done as part of Startup as I linked in the other issue.

@JoshLove-msft Magic.  I was doing that call as part of AddServiceBusClientWithNamespace, didn't realise it was part of the root AzureClientFactoryBuilder.

Much appreciated.

Maybe an update to the doco to help those trying to do the same
[Azure Functions developer guide](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference?tabs=queue#local-development-with-identity-based-connections)
