### ISSUE TITLE
[QUERY] Why are different scopes returned by VisualStudioCredential and AzureCliCredential?

### ISSUE THREAD

**Issue by Ruud2000** [Azure/azure-sdk-for-net#34843]
### Library name and version

Azure.Identity 1.8.2

### Query/Question

I am writing an Azure Function that uses the Microsoft Graph SDK to upload small files to a MS Teams channel.

When deployed to Azure it should use the Managed Identity of the Azure Function, while running locally in Visual Studio on my machine it should use my credentials. This is why at first I decided to use `DefaultAzureCredential` as the credential to pass to my `GraphServiceClient`:

```c#
var graphServiceClient = new GraphServiceClient(
    new DefaultAzureCredential(), 
    new[] { "https://graph.microsoft.com/.default" });
```

Unfortunately this approach returns an **Access denied** when I try to upload a file running locally:

```c#
// Retrieve the files folder of the Teams channel we want to upload files to.
var filesFolder = await graphServiceClient
    .Teams["my_team_id"]
    .Channels["my_channel_id"]
    .FilesFolder
    .GetAsync();

// Create file content to upload
using var stream = new MemoryStream(Encoding.UTF8.GetBytes(@"Dummy data"));

// Upload file - throws ODataError with error message: Access denied
await graphServiceClient
    .Drives[filesFolder.ParentReference.DriveId]
    .Items[filesFolder.Id]
    .ItemWithPath("test.txt")
    .Content
    .PutAsync(stream);
```

When I inspect the scopes of the access token obtained from the `DefaultAzureCredential` I see the following scopes:
`"Application.ReadWrite.All Directory.Read.All email IdentityUserFlow.ReadWrite.All openid profile User.Read"`

Based on these scopes it makes sense the upload throws an exception, because the permission required to upload is missing.

Per my understanding the `DefaultAzureCredential` uses `VisualStudioCredential` when I run it locallly. When I change my approach and instead of `DefaultAzureCredential` use a `ChainedTokenCredential` with `ManagedIdentityCredential` and `AzureCliCredential` I am able to successfully upload a file when running locally. So apparently I get different scopes when I use Azure CLI vs Visual Studio

When I compare the scopes returned by `AzureCliCredential` vs `VisualStudioCredential` I indeed notice differences:

```
// | Scope                          | VisualStudioCredential | AzureCliCredential |
// |--------------------------------|------------------------|--------------------|
// | Application.ReadWrite.All      | x                      |                    |
// | AuditLog.Read.All              |                        | x                  |
// | Directory.Read.All             | x                      |                    |
// | Directory.AccessAsUser.All     |                        | x                  |
// | email                          | x                      | x                  |
// | Group.ReadWrite.All            |                        | x                  |
// | IdentityUserFlow.ReadWrite.All | x                      |                    |
// | openid                         | x                      | x                  |
// | profile                        | x                      | x                  |
// | User.Read                      | x                      |                    |
// | User.ReadWrite.All             |                        | x                  |
```

Why do these 2 token credential sources return different scopes? I assume I have no control over the list of scopes returned by these token credential sources, is that correct? Would it be useful to raise a feature request to align the 2 to ease using the Graph SDK with a `DefaultAzureCredential`?

**Comment by jsquire** [comment]
//cc: @schaabs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
> Why do these 2 token credential sources return different scopes? I assume I have no control over the list of scopes returned by these token credential sources, is that correct? 

This is a reflection of the permissions assigned to the client application used by these various credentials.
 The permissions (scopes) that are returned when a token is requested is related to the permissions consent granted to the client application. [This reference](https://docs.microsoft.com/en-us/graph/security-authorization) explains some of the context. From the page:

"The Azure AD tenant admin must explicitly grant consent to your application. This is required both for application-level authorization and user delegated authorization."

The reason the two credentials are different is because they are using different client application IDs, each having different permissions granted to them. Azure CLI uses application Id 04b07795-8ddb-461a-bbee-02f9e1bf7b46 (a list of first party applications can be found [here](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/verify-first-party-apps-sign-in#application-ids-for-commonly-used-microsoft-applications)) and Visual Studio Code uses the application Id aebc6443-996d-45c2-90f0-388ff96faa56.

**Comment by Ruud2000** [comment]
Thanks, your answer makes total sense. In my particular scenario I'll then continue to use a `ChainedTokenCredential`, combining the `ManagedIdentityCredential` and `AzureCliCredential`, instead of the `DefaultAzureCredential`.
