### ISSUE TITLE
Active directory dependency

### ISSUE THREAD

**Issue by vasilispantelisswo** [Azure/azure-sdk-for-net#3485]
When I try to get an Azure tenant's subscriptions through the fluent library I get this exception:

```
System.TypeLoadException: Could not load type 'Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate' from assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.13.8.999, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__21.MoveNext()
...
```

As far as I can tell the problem is the major version difference between the dependency of my project of the Microsoft.IdentityModel.Clients.ActiveDirectory package and this library's dependency (at this time 2.28.3). As it is hard to downgrade my dependency I have to ask if there are any plans on upgrading the fluent's library dependency to 3.* or if you have a different way that I can circumvent this problem.

**Comment by hovsepm** [comment]
@vasilispantelisswo what is your target framework? .Net Core or .Net 4.5.2? Could you also post here the sample code for a repro?

**Comment by hovsepm** [comment]
@vasilispantelisswo could you try to add explicated reference to nuget package [Microsoft.Rest.ClientRuntime.Azure.Authentication v 2.3.0](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure.Authentication/2.3.0)?

**Comment by vasilispantelisswo** [comment]
@hovsepm I'm targeting .Net 4.6. I tried explicit package reference but it's the same result. You can create a sample app with latest stable Microsoft.Azure.Management.Fluent package (1.1.3) and Microsoft.IdentityModel.Client.ActiveDirectory v3.13.8 and use this piece of code:

```csharp
var azureCredentials = new AzureCredentialsFactory().FromServicePrincipal(
	"AClientId",
	"AClientSecret",
	"ATenantId",
	AzureEnvironment.AzureGlobalCloud);
var subscriptions = Azure.Authenticate(azureCredentials).WithDefaultSubscription().Subscriptions.List().ToList();
```

It should fail with the aforementioned exception.

**Comment by hovsepm** [comment]
Ok. So for .Net 4.6 we do not support ADAL v 3.13.8. Instead we have a hard dependency on ADAL v 2.28.x through referenced Microsoft.Rest.ClientRuntime.Azure.Authentication library. 
Currently you can have two ways to overcome this issue:
1. Downgrade ADAL nuget package dependency to v.2.28.LATEST
2. Upgrade your project to .Net Core netstandard1.3 or higher.

**Comment by vasilispantelisswo** [comment]
OK. I wonder why NuGet did not notify that there is a hard dependency and instead went for the minimum required version of 3.13.* that was in my project, but that question is for another project, not this. 

For now I will go with the 3rd option of actually implementing the required REST calls myself and remove the reference to the Fluent library.
