### ISSUE TITLE
[QUERY] Optmiziations for Blob copy from one Storage Account to another

### ISSUE THREAD

**Issue by anukarsh22nd** [Azure/azure-sdk-for-net#34877]
### Library name and version

Azure.Storage.Blobs 12.15.0

### Query/Question

I want to copy an azure blob file(maximum size of 800 MB) from the source azure blob storage to the destination azure blob storage at after some regular intervals. Earlier, I thought of using the Azure Data Movement library([link](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-data-movement-library?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&bc=%2Fazure%2Fstorage%2Fblobs%2Fbreadcrumb%2Ftoc.json)) as it provides a single API for synchronous client-side transfer which means that the blob file will come to the client first from Source SA and then from the client, it will get uploaded to Destination SA. Since this Azure Data movement library is now available in support mode, we have shifted to Azure .NET Storage SDK. 
There is an API for doing server-to-server asynchronous data transfer, which is **StartCopyFromUriAsync** ([link](https://learn.microsoft.com/en-us/training/modules/copy-blobs-from-command-line-and-code/7-move-blobs-using-net-storage-client)). It does server to server transfer, and blob gets copied to destination SA from Source SA without coming to client.
It is too slow compared to synchronous client-side transfer(when the film comes to the client side and then gets uploaded to the destination SA). 
For Synchronous client-side transfer, there is no single API to do this. We will have to first download the file from Source SA and then upload it into destination SA using 2 different APIs. 
I am using the following code to perform the above:(OpenReadAsync for download and UploadAsync to upload)

                Func<Task<Stream>> getBlobStreamAsync = () => sourceBlobClient.OpenReadAsync(readOpt);
                stream = await getBlobStreamAsync().ConfigureAwait(false);
                await destBlobClient.UploadAsync(stream);
                
This is taking thrice the time it took for the Azure Data Movement library to copy the blob. 
Is there any better way/API to optimize download/upload, and are there any configurations we need to put in for better performance?

Note: This code will be running on an AKS cluster, and the source and destination storage accounts are in the same region.

**Comment by PramodValavala-MSFT** [comment]
@anukarsh22nd I believe you are referring to the `v2.x` versions of the library which is not going to get new features. The latest `v12.x` versions of [the library](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.Storage.DataMovement.Blobs) will be supported. @amnguye Could you confirm?

**Comment by anukarsh22nd** [comment]
@PramodValavala-MSFT I am talking about the v12.x.0 library only. [link ](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/storage?view=azure-dotnet). There is no single API for synchronous client-side copy present in this library. We have to first download a local copy in the stream and then upload it to the destination storage account. I wanted to know which APIs to use for reading and uploading for the best performance, as there are multiple APIs present. For reading, it has DownloadStreamingAsync and OpenReadAsync APIs. For upload, it has the following APIs: Upload and UploadAsync
I also want to know any configurations that we have to put in for better performance.

**Comment by anukarsh22nd** [comment]
Any updates on this?

**Comment by PramodValavala-MSFT** [comment]
@anukarsh22nd You've linked to the Blob Storage SDK. But there is a [12.x Data Movement SDK](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/storage/Azure.Storage.DataMovement.Blobs) available. Have you tried using that?
