### ISSUE TITLE
[BUG] - Closed captioning for the media asset isn't hidden on player despite has hidden visibility.

### ISSUE THREAD

**Issue by acvila-de-munte** [Azure/azure-sdk-for-net#34885]
### Library name and version

Microsoft.Azure.Management.Media 6.0.0.0

### Describe the bug

I've updated the closed captioning and updated the asset manifest via track api to make the captioning visible. It was shown on the player.
After this I used track api to hide the track and on portal I can see that visibility is hidden
![image](https://user-images.githubusercontent.com/11018110/224702372-5ef88861-517e-4201-95c1-8f9b43aeb5c5.png)

But when I try to play the video I can see the closed captioning is visible
![image](https://user-images.githubusercontent.com/11018110/224702763-71cf98d2-a1cb-4683-9662-cfc57d30e69d.png)

Here how I've used an api to make it hidden.

```
var track = new TextTrack(textTrack.FileName, textTrack.DisplayName, textTrack.LanguageCode, Visibility.Hidden, textTrack.HlsSettings);
await mediaServiceClient.Tracks.BeginUpdateAsync(_mediaServiceConfig.ResourceGroup, _mediaServiceConfig.AccountName,
						assetName, fileName, track, cancellationToken);
```

Additional settings of the text track (that i keep in textTrack.HlsSettings)
`DefaultProperty = true, Forced = true, Characteristics = "public.accessibility.transcribes-spoken-dialog"`

Could you please clarify, is it a bug or I need to change anything else?
Thank you

### Expected behavior

Text track should be hidden and not visible.

### Actual behavior

Text track isn't hidden and is visible.

### Reproduction Steps

Create an asset
Upload closed captioning file
Update manifest to have textstream section with pointing to uploaded closed captioning via azure sdk api and make it visible.
Update closed captioning visibility via azure sdk to be hidden.
User can see the closed captioning

### Environment

Azure Media service

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by acvila-de-munte** [comment]
Appears that the player has cached it somehow, after I opened it in incognito the select track dropdown was hidden as expected.
I'm going to close the ticket.
Thank you for help
