### ISSUE TITLE
Communication.Email corrupts PDF document

### ISSUE THREAD

**Issue by jantanis** [Azure/azure-sdk-for-net#34892]
### Library name and version

Azure.Communication.Email 1.0.0-beta2

### Describe the bug

When adding a PDF stream as attachment the file gets corrupted,

### Expected behavior

Same as when written to file. A non corrupted attachment.

### Actual behavior

Creates a corrupt attachment.

### Reproduction Steps

var bytes = report.ToArray();
var emailAttachment = new EmailAttachment("scan.pdf", MediaTypeNames.Application.Pdf, new BinaryData(bytes));
message.Attachments.Add(emailAttachment);

EmailSendOperation emailSendOperation = await emailClient.SendAsync(Azure.WaitUntil.Completed, message);

If you write bytes to a file you can open it. If you open it from email it says it is corrupted.

### Environment

Visual Studio Community 2022 for Mac
Version 17.5.1 (build 23)
Installation UUID: 19bb46b6-b44f-4bfc-9a84-223c4eb8b2c2

Runtime
.NET 7.0.1 (64-bit)
Architecture: Arm64
Microsoft.macOS.Sdk 12.3.2372; git-rev-head:754abbf6a3563f6267e5717ae832b4ac25b1f2fb; git-branch:release/7.0.1xx-xcode13.3

Roslyn (Language Service)
4.5.0-3.23056.2+97881342e427ff5cdcba8f12b12ff8e6f3564431

NuGet
Version: 6.4.0.117

.NET SDK (Arm64)
SDK: /usr/local/share/dotnet/sdk/7.0.201/Sdks
SDK Versions:
	7.0.201
	7.0.200
	7.0.103
	7.0.100
	6.0.406
	6.0.403
	6.0.402
	6.0.400
	6.0.300
MSBuild SDKs: /Applications/Visual Studio.app/Contents/MonoBundle/MSBuild/Current/bin/Sdks

.NET Runtime (Arm64)
Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	7.0.3
	7.0.0
	6.0.14
	6.0.11
	6.0.10
	6.0.8
	6.0.5

Xamarin.Profiler
Version: 1.8.0.49
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

Updater
Version: 11

Apple Developer Tools
Xcode: 14.2 21534
Build: 14C18

Xamarin.Mac
Not Installed

Xamarin.iOS
Version: 16.2.0.5 Visual Studio Community
Hash: 7738c90c9
Branch: xcode14.2
Build date: 2023-01-25 15:56:15-0500

Xamarin Designer
Version: 17.5.3.47
Hash: e8b5d371c3
Branch: remotes/origin/d17-5
Build date: 2023-03-02 06:10:08 UTC

Xamarin.Android
Version: 13.2.0.0 (Visual Studio Community)
Commit: xamarin-android/d17-5/797e2e1
Android SDK: /Users/jan/Library/Android/sdk
	Supported Android versions:
		12.0 (API level 31)
		11.0 (API level 30)
		10.0 (API level 29)
		9.0  (API level 28)
		13.0 (API level 33)

SDK Command-line Tools Version: 7.0
SDK Platform Tools Version: 34.0.0
SDK Build Tools Version: 32.0.0

Build Information: 
Mono: 6dd9def
Java.Interop: xamarin/java.interop/main@149d70fe
SQLite: xamarin/sqlite/3.40.0@fdc1e34
Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77

Microsoft Build of OpenJDK
Java SDK: /Library/Java/JavaVirtualMachines/microsoft-11.jdk
11.0.16.1
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Eclipse Temurin JDK
Java SDK: /Library/Java/JavaVirtualMachines/temurin-8.jdk
1.8.0.302
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

Android SDK Manager
Version: 17.5.0.33
Hash: f0c0c52
Branch: remotes/origin/d17-5~2
Build date: 2023-03-02 06:10:13 UTC

Android Device Manager
Version: 0.0.0.1245
Hash: 7f8a990
Branch: 7f8a990
Build date: 2023-03-02 06:10:13 UTC

Build Information
Release ID: 1705010023
Git revision: 4ea4e8aba0157d7f608399614482546551c0ee08
Build date: 2023-03-02 06:08:04+00
Build branch: release-17.5
Build lane: release-17.5

Operating System
Mac OS X 13.2.1
Darwin 22.3.0 Darwin Kernel Version 22.3.0
    Mon Jan 30 20:38:37 PST 2023
    root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

Enabled user installed extensions
.NET Core Extensions 0.6

**Comment by navba-MSFT** [comment]
@jantanis Thanks for reaching out to us and reporting this issue. Could you please try with the below sample snippet and check if that helps ?

We can add a PDF attachment by defining an EmailAttachment object and adding it to our EmailMessage object. Read the PDF attachment file and encode it using Base64.

```
var filePath = "C:\Users\Documents\attachment.pdf";
byte[] bytes = File.ReadAllBytes(filePath);
var contentBinaryData = new BinaryData(bytes);
var emailAttachment = new EmailAttachment("attachment.pdf", MediaTypeNames.Application.Pdf, contentBinaryData);
emailMessage.Attachments.Add(emailAttachment);
```

You can download the sample app demonstrating this from [GitHub](https://github.com/Azure-Samples/communication-services-dotnet-quickstarts/tree/main/SendEmailAdvanced/SendEmailWithAttachments)

**Comment by jantanis** [comment]
@navba-MSFT Thank you for your reply. I failed to see how your code was different from mine, but tried it anyway. Same result.

**Comment by navba-MSFT** [comment]
@jantanis Thanks for your reply. Could you test with the most recent library  Azure.Communication.Email version1.0.0-beta.3 

https://www.nuget.org/packages/Azure.Communication.Email/1.0.0-beta.3 ? Awaiting your reply.

**Comment by davide-bergamini-sevenit** [comment]
We have the same problem.
I already sent a PR that should fix the bug:
#34921
