### ISSUE TITLE
[QUERY] Export trace events as Event Telemetry

### ISSUE THREAD

**Issue by Expecho** [Azure/azure-sdk-for-net#34912]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.8

### Query/Question

In a .Net 6 Web Api controller action I added an event to the current span with the expectation it would end up as an event in Application Insights. The following code is executed

```csharp
Tracer.CurrentSpan.AddEvent("Event");
```

However, it ends up as a trace in Application Insights. Looking at the code of the exporter it seems events have no place (yet). Is this by design?

**Comment by Expecho** [comment]
@vishweshbankwar First of all, thank you for taking time to react to my query. I am sorry to see it is closed immediately as I have a follow up question. For a starter, can you explain what you mean with "**There is no equivalent** for CustomEvents available right now."?

I assume it has to do with the fact that according to the OTEL spec events are just a special type of LogRecords but in the context of Application Insights (AI) it would make sense to export them as a CustomEvents record. I have a lot of applications that are instrumented using the AI SDK. For new applications I am tempted to use the OTEL SDK as it gives us more flexibility regarding the backend of our traces.

For now we do use the Events telemetry type a lot, given the way they can be analyzed in AI. How about making it optional (and disabled by default) to export events as CustomEvents? I would be more than happy to draft out a PR to facilitate this using the `AzureMonitorExporterOptions` or any other way you might seem as a better fit.

**Comment by mattmccleary** [comment]
Hi @Expecho 

The OTel community is well along in discussions to create an events API, though as you can see it's being blocked at the moment. Either way, we do not foresee span events being the way the OTel community decides to support events.

https://github.com/open-telemetry/opentelemetry-specification/pull/3167

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/semantic_conventions/events.md

Do you have any feedback for our team or requirements we can take with us as we work with OTel to find the right path forward?
