### ISSUE TITLE
[Core] Support for 100-continue flow

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#34917]
https://github.com/Azure/azure-sdk/issues/5787

**Comment by jsquire** [comment]
Request will be costed and evaluated once archboard discussion for the linked issue has been completed.

**Comment by annelo-msft** [comment]
Is this a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/23957?  If so, it would be good to close one of them.

**Comment by jsquire** [comment]
Apparently so.   Nice find!   Feel free to kill the one of your choice.  Neither seems to have any critical context.

**Comment by jsquire** [comment]
After archboard discussions, this is not a feature that we currently plan on adding.   Closing out for now.
