### ISSUE TITLE
[FEATURE REQ] Function App key management

### ISSUE THREAD

**Issue by JDECOMBE** [Azure/azure-sdk-for-net#34915]
### Library name

Azure.ResourceManager.AppService

### Please describe the feature.

Hi,

Would it be possible to be able to Create/Set/Delete Function App keys ? For now only listing is available but the Azure CLI is able to modify those properties (`az functionapp function keys`).
I haven't found any route that would expose this logic in the Rest API so I'm guessing it's not just the client part of the SDK that needs to be implemented.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JDECOMBE** [comment]
Looking more into the code, it seems that the `WebAppsRestOperations.CreateOrUpdateHostSecretAsync` method does exactly that. 
Unfortunately, this method is broken right now. 
I've found [this PR](https://github.com/Azure/azure-rest-api-specs/issues/14557) where a similar issue was discussed (and fixed) for the Go SDK. (Link goes to the `Azure/azure-rest-api-specs` repository)

**Comment by live1206** [comment]
@JDECOMBE As I can see, the issue in swagger has not been addressed. Please check the latest stable version of [swagger](https://github.com/Azure/azure-rest-api-specs/blob/a13f142cfd0c2273b9a9d27dc82babcd91d7d1a1/specification/web/resource-manager/Microsoft.Web/stable/2022-09-01/WebApps.json#L26046).

According to https://github.com/Azure/azure-rest-api-specs/pull/17653#issuecomment-1160808901, service team will update the source to properly fix the generated swagger, which has not happened yet.

**Comment by live1206** [comment]
Thanks to @mathewc, the next version of [WebApps.json](https://github.com/Azure/azure-rest-api-specs/blob/a13f142cfd0c2273b9a9d27dc82babcd91d7d1a1/specification/web/resource-manager/Microsoft.Web/stable/2022-09-01/WebApps.json#L26046) will be fixed.

**Comment by ArthurMa1978** [comment]
Need release new sdk

**Comment by ArthurMa1978** [comment]
The release is tracked by https://github.com/Azure/azure-sdk-for-net/issues/43752
