### ISSUE TITLE
Can we cache unwrapkeyasync?

### ISSUE THREAD

**Issue by akashperfect** [Azure/azure-sdk-for-net#34916]
We are making massive number of calls to decrypt the secret. Is there a way we can cache the unwraped key, so that we dont have to make calls to KV multiple times.
Any C# example will do.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73896413-fe0d-047d-5f3b-bfc8d3ff7260
* Version Independent ID: 638fc43e-1c40-05c3-1363-6ddd8c66641e
* Content: [KeyVaultClientExtensions.UnwrapKeyAsync Method (Microsoft.Azure.KeyVault) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.keyvault.keyvaultclientextensions.unwrapkeyasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.KeyVault/KeyVaultClientExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.KeyVault/KeyVaultClientExtensions.xml)
* Service: **key-vault**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @akashperfect.  Thank you for reaching out with your question.   I've triaged this to the team member best able to assist.    In the meantime, I wanted to make you aware that the `Microsoft.Azure.KeyVault` family of packages is deprecated and will reach end-of-support on March 31, 2023.    We would strongly suggest that you move to the `Azure.Security.KeyVault` family of packages.   More information and pointers to the migration guides can be found in the [NuGet page](https://www.nuget.org/packages/Microsoft.Azure.KeyVault) for the package.

**Comment by heaths** [comment]
Our `Azure.Security.KeyVault.Keys` package - and nearly every `Azure.*` client library - support custom HTTP pipeline policies. We don't cache by default because caching is an application concern (storage, lifetime, etc.), but you can easily write your own. See my example for Key Vault (but can also work for most other GET operations in `Azure.*` client libraries): https://learn.microsoft.com/samples/azure/azure-sdk-for-net/azure-key-vault-proxy/

**Comment by akashperfect** [comment]
Thanks for your response @heaths but I am actually looking for anyway to cache or handle wrap and unwrap operations. As I am getting TooManyRequests for UnWrap and AfterAuthentication. Not sure what the latter means.
Is there a way we can do that.

**Comment by heaths** [comment]
Caching is beyond the scope of the SDK. If you're constantly wrapping and unwrapping the same key, I recommend you cache the value within your application since caching is an application concern.
