### ISSUE TITLE
Scaling AppServicePlan using storage queue length

### ISSUE THREAD

**Issue by phatcher** [Azure/azure-sdk-for-net#3494]
We get data uploaded for processing which we then schedule for execution in a webjob via putting a message into a storage account queue.  What I need to be able to do is spin up more instances of the App Service Plan if the queue length is such that it will breach our SLA for processing all the items

There doesn't seem to be a way of scaling using a custom metric so I presume the way forward is to work out the scaling logic and then use https://docs.microsoft.com/en-us/rest/api/appservice/appserviceplans#AppServicePlans_CreateOrUpdate to do the operation?

What would be nice if there was a way to publish a custom metric to be used by the standard scaling logic so that I don't have to implement the lookback/cool down logic myself. Even if it's not a in the gui, exposing the internal api for use would be good

**Comment by cormacpayne** [comment]
@phatcher Hey Paul, thanks for the feedback. Here is the corresponding call in SDK for .NET: https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/WebSites/Management.Websites/Generated/AppServicePlansOperationsExtensions.cs#L202-L208

Forwarding to the App Service team to comment on your enhancement request: @aspaan

**Comment by AlexGhiondea** [comment]
@phatcher we realize it's been a long time since you opened this issue. If you still require help, please reply to this issue.

**Comment by phatcher** [comment]
@AlexGhiondea Had a quick look and it now seems possible to scale via storage queue or ServiceBus queues so I think this is resolved.

Idea of using custom metrics would still be a good idea though

**Comment by AlexGhiondea** [comment]
Thanks @phatcher! I'm going to close this issue for now. The idea of custom metrics does sound nice. Is that something you would like to file a new issue for with additional details?

**Comment by phatcher** [comment]
@AlexGhiondea Will do
