### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by rovinbhandari** [Azure/azure-sdk-for-net#34957]
`Explore the client APIs` button results in 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ba68873-71aa-9f3a-f558-5b1a81296560
* Version Independent ID: fe6ec9de-d30e-f8f5-d86e-49af8f7e8fc1
* Content: [Azure Cosmos DB libraries for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/cosmosdb?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/cosmosdb.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/cosmosdb.md)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the Azure CosmosDB client library is maintained as [#3766](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3766).
