### ISSUE TITLE
[QUERY] Fine tune copying large blobs (5gb+)

### ISSUE THREAD

**Issue by shiafr-msft** [Azure/azure-sdk-for-net#34966]
### Library name and version

Azure.Storage.Blobs 12.15.0 and WindowsStorage.Blobs 9.3.3

### Query/Question

Hello

Am using Azure.Storage.Blobs 12.15.0 to expose an API to copy blobs from our storage to partner storage. I was able to fine tune the options to copy successfully 3gb+ file, but when we copy 5gb+ file, nothing gets copied until 15m and then we hit out client timeout and get a TaskCanceledException.

**Below is the implementation using Azure.Storage.Blobs 12.15.0.**

// Instantiate destination using SasUri and set BlockBlobOpenWriteOptions.
BlockBlobClient destinationBlockBlobClient = new BlockBlobClient(new Uri(destinationSasUri));
BlockBlobOpenWriteOptions blockBlobWriteOptions = new BlockBlobOpenWriteOptions();
blockBlobWriteOptions.BufferSize = 4194304000;
var destinationStream = await destinationBlockBlobClient.OpenWriteAsync(true, blockBlobWriteOptions, cancellationTokenSource.Token).ConfigureAwait(false))

// Set BlobDownloadToOptions from source blockBlob to destination blockBlob.
BlobDownloadToOptions blobDownloadToOptions = new BlobDownloadToOptions()
{
	TransferOptions = new StorageTransferOptions() { MaximumConcurrency = 64, InitialTransferSize = DCATBlockBlobMaxStageBlockLongBytes, MaximumTransferSize = 4194304000 },
};

// Download from source blockBlob to destination blockBlob.
await sourceBlockBlobClient.DownloadToAsync(destinationStream, blobDownloadToOptions, cancellationTokenSource.Token).ConfigureAwait(false);

**Question: Is this the recommended way to copy large blobs from one account to another?**

**Old SDK implementation:**
Initially we used the old WindowsStorage.Blobs 9.3.3 to do the same, and here the 5gb+ file copy completes in ~5m.
But, we are hitting other issues and end up waiting 15m even if the copy completed in 5m.
This most likely is an issue our code about async/await deadlock. So, we are in parallel trying to solve that as well.

**Below is the implementation using WindowsStorage.Blobs 9.3.3.**

// Instantiate destination using SasUri
CloudBlockBlob destinationBlob = new CloudBlockBlob(new Uri(destinationSasUri));
destinationBlob.StreamWriteSizeInBytes = 104857600; // Set to 100MB max.
var destinationStream = await destinationBlob.OpenWriteAsync(null, new BlobRequestOptions() { ParallelOperationThreadCount = 64 }, null, cancellationTokenSource.Token).ConfigureAwait(false))

// Download from source blockBlob to destination blockBlob.
await sourceBlob.DownloadToStreamAsync(destinationStream, null, new BlobRequestOptions() { ParallelOperationThreadCount = 64, }, null, cancellationTokenSource.Token).ConfigureAwait(false);

### Environment

Our service is running in Autopilot.

**Comment by navba-MSFT** [comment]
@shiafr-msft Apologies for the late reply. Thanks for reaching out to us and reporting this issue. You should follow the suggestions provided in the [performance checklist article](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-performance-checklist#performance-tuning-for-data-transfers).

**Comment by navba-MSFT** [comment]
@shiafr-msft I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you had any updates on this. Awaiting your reply.
