### ISSUE TITLE
[QUERY] I Can't find valueSignature

### ISSUE THREAD

**Issue by Heimidall** [Azure/azure-sdk-for-net#34960]
### Library name and version

Azure.AI.FormRecognizer 4.0.0

### Query/Question

I have a template-trained model to extract information from a document. One of the data points we're interested in extracting is the signature within the document. Therefore, we use the signature field that FormRecognizer Studio allows you to create. When testing the model, it tells me whether or not the document is signed through the valueSignature field.
![image](https://user-images.githubusercontent.com/18452593/225676935-269ca874-3eff-42c1-a795-0d5cbf831efd.png)

However, when trying to obtain it through code using AnalyzeDocumentAsync(), I am unable to access that property. The closest property to that value is one called InternalValue.

![image](https://user-images.githubusercontent.com/18452593/225679183-3ff73ff0-8d8f-48c8-8dd0-462f7a4d4dce.png)

Is there any way to access the valueSignature field?

### Environment

Windows 10 

.NET 6.0

Visual Studio 2022 17.5.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by kinelski** [comment]
Hello @Heimidall,

You need to call the `AsSignatureType` method to extract the internal value from the field. For example:
```cs
DocumentSignatureType signatureType = field.Value.AsSignatureType();
```
Feel free to reach out if you have further questions.

**Comment by Heimidall** [comment]
I understand everything now, thank you very much for the help.
