### ISSUE TITLE
Allow extraction of all MSAL logs from Azure Identity library

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-for-net#34969]
**Context:**
When customers encounter bugs in MSAL, the MSAL team needs detailed logs to diagnose the issue. The Azure Identity library doesn't have a provision to extract all these logs. In particular, we need verbose logs with PII information. For context, MSAL exposes 2 knobs for logging:

1. The log verbosity, which is very closely related to Azure SDK’s verbosity, i.e. Verbose, Info, Warning, Error.
2. A PII flag, false by default. Note: For a cheat sheet of what gets logged, see https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/PII.

The request is to allow app developers using the Azure Identity library to collect Verbose + PII logs from MSAL, on request, which are sometimes needed for supportability. The Azure Identity library exposes some knobs already, but there's no alignment over PII.

**Comment by joshfree** [comment]
Related https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1755813/?triage=true

**Comment by joshfree** [comment]
`EnableSupportLogging` is the name we're landing on.

**Comment by pvaneck** [comment]
.NET already has an internal flag [`IsLoggingPIIEnabled`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/Credentials/TokenCredentialOptions.cs#L42) and what seems to be the necessary logic to enable PII logging on MSAL. That flag's name can just be updated and made public.
