### ISSUE TITLE
[BUG] InvalidOperationException thrown while set API version in ArmClientOption

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-for-net#34973]
### Library name and version

Azure.ResrouceManager 1.4.0

### Describe the bug

When user sets Api version for specific resource type like below:
options.SetApiVersion(new ResourceType("Microsoft.Compute/test"), "2022-09-01");

It throws `InvalidOperationException` while creating GenericResource for "Microsoft.Compute/availabilitySets"

### Expected behavior

The GenericResource creation should not throw

### Actual behavior

It throws `InvalidOperationException` while creating GenericResource for "Microsoft.Compute/availabilitySets"

### Reproduction Steps

options.SetApiVersion(new ResourceType("Microsoft.Compute/test"), "2022-09-01");

Then create a generic resource for "Microsoft.Compute/availabilitySets"

**Comment by ArthurMa1978** [comment]
Pending on release new RM

**Comment by live1206** [comment]
Fix released in [Azure.ResourceManager/1.5.0](https://www.nuget.org/packages/Azure.ResourceManager/1.5.0)
