### ISSUE TITLE
[BUG] Unable to deserialize Resource Manager Kusto payload

### ISSUE THREAD

**Issue by SwamyNallamalli** [Azure/azure-sdk-for-net#34977]
### Library name and version

Azure.ResourceManager.Kusto 1.3.0.0

### Describe the bug

When accessing the principals using the code from 
https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.Kusto_1.3.0/sdk/kusto/Azure.ResourceManager.Kusto/samples/Generated/Samples/Sample_KustoDatabasePrincipalAssignmentCollection.cs
hitting the exception 

System.FormatException
  HResult=0x80131537
  Message=One of the identified items was in an invalid format.
  Source=System.Text.Json
  StackTrace:
   **at System.Text.Json.ThrowHelper.ThrowFormatException()
   at System.Text.Json.JsonElement.GetGuid()**
   at Azure.ResourceManager.Kusto.KustoDatabasePrincipalAssignmentData.DeserializeKustoDatabasePrincipalAssignmentData(JsonElement element)
   at Azure.ResourceManager.Kusto.KustoDatabasePrincipalAssignmentCollection.<GetAll>b__10_1(JsonElement e)
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetEnumerator>d__17.MoveNext()

There is no way to look at what row is causing the data or skipping that row and proceeding ahead. The specific issue seem to be other places when some guid is expected and is null, but is there a workaround?

### Expected behavior

Reading the principals using the collection should provide the enumerator with all the list of users

### Actual behavior

FormatException is getting thrown after the first user. First user is myself. The remaining users are not showing up or enumerator is not forwarding as the next entry is failing deserialization. 

### Reproduction Steps

`            
            ResourceIdentifier kustoDatabaseResourceId = KustoDatabaseResource.CreateResourceIdentifier("6c6bfab7-262d-4277-bc68-ec0fd783ba1e", "PPECommandAndControl", "ppesimselfkusto", "Logs");
            
            KustoDatabaseResource kustoDatabase = client.GetKustoDatabaseResource(kustoDatabaseResourceId);
           KustoDatabasePrincipalAssignmentCollection collection = kustoDatabase.GetKustoDatabasePrincipalAssignments();
            foreach (KustoDatabasePrincipalAssignmentResource item in collection.GetAll())
            {
                KustoDatabasePrincipalAssignmentData resourceData = item.Data;
                Console.WriteLine($"Succeeded on id: {resourceData.Id}");
            }
`

Running the above code is throwing exception

### Environment

Reading principles from Kusto database

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
