### ISSUE TITLE
Upgrade the `Azure.ResourceManager` lib to support new PolicyAssignments

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#34986]
Upgrade to latest `2022-06-01` version

**Comment by josefree** [comment]
[Feature 167364*: Make the property 'resourceSelectors' available on Azure SDK for .NET - Boards](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Funifiedactiontracker%2FTechnical%2520Feedback%2F_workitems%2Fedit%2F167364&data=05%7C01%7Cyiqiu%40microsoft.com%7C80c31f3444e44fb37ac308db26f4a0bf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638146604339688986%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nP2I0IztjcbB%2BSpeR5x5oOAp9TRo9vApK2IIf1l1xiE%3D&reserved=0)

**Comment by josefree** [comment]
PG ICM: https://portal.microsofticm.com/imp/v3/incidents/details/366190562
