### ISSUE TITLE
[QUERY] How can I configure timeout while using ContainerRegistryManagementClient

### ISSUE THREAD

**Issue by jikuma** [Azure/azure-sdk-for-net#34993]
### Library name and version

Microsoft.Azure.Management.ContainerRegistry 6.0.0

### Query/Question

We migrated our services from Net4.7.2 to dotnet core 6.0. We see the error "The request was cancelled due to the configured HttpClient.Timeout of 100 seconds elapsing."

The Kubernetes pod running this service has enough memory and CPU. The network does not seem to be an issue as the Kubernetes cluster in running on Azure and this client is trying to reach ARM.  Also, during the same time, the service can reach storage accounts. Also this is happening in multiple regions. 

I want to add a retry logic in our code. For this I want to decrease the timeout from 100sec to 15sec, but I could not find timeout setting exposed. Do I have to create my own HttpClient?

My code is really simple

```cmd
var containerRegistryManagementClient = ContainerRegistryManagementClient(resourceManagerUri, tokenCredentials) { SubscriptionId = subscriptionId };
var registry = await containerRegistryManagementClient.GetRegistryPropertiesAsync(
                subscriptionId: resource.SubscriptionId,
                resourceGroupName: resource.ResourceGroupName,
                registryName: resource.ResourceName,
                correlationId: correlationId);
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @jikuma the SDK you're using is being deprecated soon, please move to our new Azure Sdk for Container Register, and here is doc for how to config the [retry policy](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#configuring-retry-options) by using the new SDK.
