### ISSUE TITLE
[FEATURE REQ] Add Update functionality for CloudServiceRoleResource to update Sku.Capacity

### ISSUE THREAD

**Issue by rolember** [Azure/azure-sdk-for-net#34996]
### Library name

Azure.ResourceManager.Compute

### Please describe the feature.

When performing manual scaling of a Cloud Service Role, Azure portal calls PATCH operation on the CloudServiceRole resource but this API is not implemented in the CloudServiceRoleResource and there is no  other way to manually / programmatically scale a CloudServiceRole.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @rolember , Thank you for using Azure SDK for .NET.
The SDK is auto generated from the service REST API swagger. There is no PATCH operation defined in the orginal files. You could open a issue in https://github.com/Azure/azure-rest-api-specs to require that feature.
