### ISSUE TITLE
[QUERY] How to mock 'SubscriptionData' and 'ManagedByTenant' classes?

### ISSUE THREAD

**Issue by Duch003** [Azure/azure-sdk-for-net#34998]
### Library name and version

Azure.ResourceManager 1.4.0

### Query/Question

Hi,

I am creating a simple .NET Console app (.NET 6 / VS2022) to automate access validation to resources in Azure. To ensure that the code is working as intended I am writing unit test (XUnit + Moq), but found some tests impossible (at first glance) to write.

I have tried to mock 'ManagedByTenant' and provide my own objects and values to return, but I could not mock the object. Moq throws 'NotSupportedException' because properties are not virtual and it is not possible to create mock objects by inheritance, since constructor is 'internal'. I assume the same goes for 'SubscriptionData' mock object, but I see only partial class implementation of 'SubscriptionData' in Visual Studio.

I have found an issue similar to this opened by another user, which seem to be resolved? 
https://github.com/Azure/azure-sdk-for-net/issues/26417
so maybe I am simply missing something.

My question: how it is intended to mock the above classes? Are there Factories i have missed? Or interfaces/abstract classes to inherit properties from? From what I have quickly checked it does not seem to be a problem for 'ResourceGroupData' and 'GenericResourceData' classes.

Thanks in advance,
Tomasz Mankin

### Environment

.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.201\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.303 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  5.0.416 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  7.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Duch003** [comment]
As a followup to the above:

I have downloaded the Azure.ResourceManager solution and browsed the projects. I was correct about the 'SubscriptionData' class: 
Auto-generated: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/SubscriptionData.cs
Custom: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/SubscriptionData.cs

According to this guide: https://azure.github.io/azure-sdk-korean/dotnet_introduction.html it looks like the class itself has been incorrectly generated. I would like to suggest the following changes:

File: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/SubscriptionData.cs

 - Make the parameterless constructor protected, so it will be possible to mock the data manually if needed
`
        protected SubscriptionData()
        {
            ManagedByTenants = new ChangeTrackingList<ManagedByTenant>();
            Tags = new ChangeTrackingDictionary<string, string>();
        }
`

 - Make al fields virtual, so libraries like Moq will be able to work
`
        public virtual string SubscriptionId { get; }
        public virtual string DisplayName { get; }
        public virtual Guid? TenantId { get; }
        public virtual SubscriptionState? State { get; }
        public virtual SubscriptionPolicies SubscriptionPolicies { get; }
        public virtual string AuthorizationSource { get; }
        public virtual IReadOnlyList<ManagedByTenant> ManagedByTenants { get; }
        public virtual IReadOnlyDictionary<string, string> Tags { get; }
`

File: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/Models/ManagedByTenant.cs
 - As above, make the parameterless constructor protected, so it will be possible to mock the data manually if needed
`
        protected ManagedByTenant()
        {
        }
`

 - As above, make all fields virtual, so libraries like Moq will be able to work
`
        public virtual Guid? TenantId { get; }
`

I will try find other classes like those in my spare time and let you know.

**Comment by Duch003** [comment]
Another update:

I just found out that the case is the same for 'TextAnalyticsActionResult' and 'SingleLabelClassifyActionResult' of 'Azure.AI.TextAnalytics.Models', but I am not sure whether this should be raised here in the respective repository

**Comment by smflorentino** [comment]
>From what I have quickly checked it does not seem to be a problem for 'ResourceGroupData' and 'GenericResourceData' classes.

It _is_ also a problem for `GenericResourceData` right? This property in `ResourceData` is also non-virtual:
https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.models.resourcedata.name?view=azure-dotnet

 `public string Name { get; }`

**Comment by HarveyLink** [comment]
Hi @Duch003 ,Model Factory for resource manager is enable for all services.
You could refer to : https://github.com/Azure/azure-sdk-for-net/blob/9ac52a165101b727ff606dd50dd82f771ec7c710/sdk/core/Azure.Core/README.md#mocking
