### ISSUE TITLE
[QUERY] Azure .NET SDK for web app/function app creation and deployment

### ISSUE THREAD

**Issue by Arvinorange** [Azure/azure-sdk-for-net#35002]
### Library name and version

Microsoft.Azure.Management.AppService

### Query/Question

Hi, 

I would like to do the below commands from the CLI in the SDK instead. 

1. $'az functionapp create -p {_appPlanName} --name {_globalFunctionName} --resource-group {_resourceGroupName} --runtime dotnet --storage-account {_storageAccountName} --functions-version 4'

2. $'az functionapp deployment source config-zip -g {_resourceGroupName} -n {_globalFunctionName} --src {_zipName}'

Looks like there's SDK Microsoft.Azure.Management.AppService could create and deploy web app, but there's no example for this. Could you please share some example for C# SDK creation of Azure function, SDK deploy of Azure function and SDK deploy of web app 

Thanks

**Comment by live1206** [comment]
function app is one kind of web site.
Here is an [example](https://github.com/Azure/azure-sdk-for-net/blob/1669aa561ad402afad288b26fe94cddfcdf2497f/sdk/websites/Azure.ResourceManager.AppService/tests/TestsCase/SiteCollectionTests.cs#L28) of web site creation. Need to set [Kind ](https://github.com/Azure/azure-sdk-for-net/blob/1669aa561ad402afad288b26fe94cddfcdf2497f/sdk/websites/Azure.ResourceManager.AppService/src/Generated/WebSiteData.cs#L259)as `functionapp` to create a function app, and you might experiment more if you can fit the settings for function app into [WebSiteData](https://github.com/Azure/azure-sdk-for-net/blob/1669aa561ad402afad288b26fe94cddfcdf2497f/sdk/websites/Azure.ResourceManager.AppService/src/Generated/WebSiteData.cs)
I did not find any SDK regarding the deployment though.

**Comment by live1206** [comment]
It requires details of the service itself, so it would be best to involve the service team to provide a sample of the usage.

**Comment by Arvinorange** [comment]
@jsquire Could you please help route this issue to service team for further assistance?

**Comment by jsquire** [comment]
@live1206 : Service teams do not generally provide samples based on our SDKs.  This is something that our team would own and coordinate with the service team directly, if needed.    Please work with @ArthurMa1978 to determine next steps.

**Comment by jsquire** [comment]
Hi @Arvinorange.  Unfortunately, this repository is focused on the Azure SDK for .NET, service teams do not monitor these issues.  To involve the service team, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

**Comment by live1206** [comment]
> @live1206 : Service teams do not generally provide samples based on our SDKs. This is something that our team would own and coordinate with the service team directly, if needed. Please work with @ArthurMa1978 to determine next steps.

@jsquire AFAIK, The sample of how to use SDK for a specific scenario is auto-generated based on examples in Spec repo.
The service team need to provide us a detailed example of the request and response how to create a function app. 
If we take a look at the example of [CreateOrUpdateStaticSiteBuildFunctionAppSettings](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/web/resource-manager/Microsoft.Web/stable/2022-09-01/examples/CreateOrUpdateStaticSiteBuildFunctionAppSettings.json), it generated a sample [CreateOrUpdateAppSettings_CreatesOrUpdatesTheFunctionAppSettingsOfAStaticSiteBuild](https://github.com/Azure/azure-sdk-for-net/blob/77324a2cb4b9edcbc8b52cf2a80240db01c16d5a/sdk/websites/Azure.ResourceManager.AppService/samples/Generated/Samples/Sample_StaticSiteBuildResource.cs#L84), which does not provide any details regarding how to create a function app with .NET SDK. 
I have checked with @ArthurMa1978 we can't do anything here if the service team doesn't provide the scenario example with details.
