### ISSUE TITLE
[QUERY]Filtering data on sub complex objects

### ISSUE THREAD

**Issue by manojmathe85** [Azure/azure-sdk-for-net#35023]
### Library name and version

Azure.saerch.Document 11.4.0

### Query/Question

HI all
I am working with SDK and  have a complex object to filter data with, can you please guide me how to operate on this data 
 
this is my complex object
 
 customer{
name: "asdadads",
ParentLevel: new lookupreference(){ "Id" : "8dbb5abe-dc23-45f2-aa10-8b4383708bbe",ExternalId" :23 }
}

i was able to filter the data in the index through this query
$filter=ParentLevel/Id eq '8dbb5abe-dc23-45f2-aa10-8b4383708bbe'
 
but i tried with SDK i see exception like this

[02:28 am] Manoj Mathe
    HI all
I am working with SDK and  have a complex object to filter data with, can you please guide me how to operate on this data 

this is my complex object

customer{​​​​​​
name: "asdadads",
ParentLevel: new lookupreference(){​​​​​​ "Id" : "8dbb5abe-dc23-45f2-aa10-8b4383708bbe",ExternalId" :23 }​​​​​​
}​​​​​​

i was able to filter the data in the index through this query
$filter=ParentLevel/Id eq '8dbb5abe-dc23-45f2-aa10-8b4383708bbe'

but i tried with SDK i see exception like this

options.Filter ="$filter=ParentLevel/Id eq '8dbb5abe-dc23-45f2-aa10-8b4383708bbe'"
'options.Filter ="$filter=ParentLevel/Id eq '8dbb5abe-dc23-45f2-aa10-8b4383708bbe'"' threw an exception of type 'System.NullReferenceException'
    Data: {​​​​​​​System.Collections.ListDictionaryInternal}​​​​​​​
    HResult: -2147467261
    HelpLink: null
    InnerException: null
    Message: "Object reference not set to an instance of an object."
    Source: "f065a912e2564afd8ba03586c9d3e1af"
    StackTrace: "   at <>x.<>m0(<SearchDataFromAZS>d__8 <>4__this)"
    TargetSite: {​​​​​​​System.String <>m0(<SearchDataFromAZS>d__8)}​​​​​​​

Thanks in adavnce
 

### Environment

Windows 11

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
Hey @manojmathe85, I've tried to run your scenario and It is working fine for me. [Here's](https://github.com/ShivangiReja/azure-sdk-for-net/blob/CustomerTest/sdk/search/Azure.Search.Documents/tests/Samples/Readme.cs#L338-L408) the test case for your reference. Please let me know if this solves your issue.
