### ISSUE TITLE
[.NET SDK Build Issue]

### ISSUE THREAD

**Issue by lululilliancoding** [Azure/azure-sdk-for-net#35051]
### Library name and version

N/A

### Query/Question

[Q1] Do we have an official document for developer use to develop new version of SDK? May I know the link? https://learn.microsoft.com/en-us/dotnet/azure/?source=docs - this link is too big that I can't find where to start. 

[Q2] I have a problem when build. I tried to set .net sdk version to 6.0 in the global.json file and build: 
d:\azure-sdk-for-net\sdk\sqlmanagement\Microsoft.Azure.Management.Sql\src>msbuild Microsoft.Azure.Management.Sql.csproj   
This will hit error: _"Version 6.0.407 of the .NET SDK requires at least version 12.0.0of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild."_ 
 
So then I changed .NET SDK version to 5.0, above build passed. However, another build failed:
d:\azure-sdk-for-net>msbuild build.proj /t:Build /p:Scope=\SqlManagement
The error message is: _" C:\Program Files\dotnet\sdk\5.0.408\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(14
1,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 7.0.  Either target .NET 5.0 or lower, or
 use a version of the .NET SDK that supports .NET 7.0. [D:\azure-sdk-for-net\sdk\SqlManagement\Azure.ResourceManager.S
ql\tests\Azure.ResourceManager.Sql.Tests.csproj]"_
 
So, does I feel confused about what version should I use and how to make both above build pass. This was from my 3 years ago .net sdk development experience so it might out of date. 

### Environment

Windows 10. 
D:\azure-sdk-for-net>dotnet --list-sdks
3.1.426 [C:\Program Files\dotnet\sdk]
5.0.408 [C:\Program Files\dotnet\sdk]
6.0.407 [C:\Program Files\dotnet\sdk]

Above versions all don't work.

**Comment by jsquire** [comment]
Hi @lululilliancoding.   Thank you for reaching out and we regret that you're experiencing difficulties.   Please start by referencing our [Contributing Guide](https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md) and [Service Partner Onboarding Guide](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/10/Welcome-Service-Partners!) _(Microsoft Internal)_.   Those will walk you through setting up your development environment, building, and guide you through service partner onboarding.
