### ISSUE TITLE
Microsoft.Azure.Management.Fluent (Get database not working)

### ISSUE THREAD

**Issue by HeroSpha** [Azure/azure-sdk-for-net#3507]
I have a web api that uses Microsoft.Azure.Management.Fluent to copy database from Azure.
When i use console app it works fine, but on my Web api all the async methods works fine bt the Get method in databases doesnt work. The program just keeps loading there. No error is displayed

**Comment by abhi1509** [comment]
This might be related:

@hovsepm pushed 2 commits.

343580f Removed Sync method from the AutoRest generated code.
900b0dd Fixed the rest of sync over async calls and ContinueWith pattern

**Comment by HeroSpha** [comment]
I don't have AutoRest generated code.. 
Here is my code
`var catalogServer = await  azure.SqlServers.GetByResourceGroupAsync(catalogConfig.ResourceGroup, "servername");
                var tenantdb = await catalogServer.Databases.Get("basetenantdb").RefreshAsync();
                var tenantServer = await  azure.SqlServers.GetByResourceGroupAsync(catalogConfig.ResourceGroup, "tenantservername");


                var database = await tenantServer.Databases.Define(tenantName)
                    .WithSourceDatabase(tenantdb)
                    .WithMode(CreateMode.OnlineSecondary)
                    .CreateAsync();
                await  database.Update().WithExistingElasticPool("Elastic-Pool")
                    .ApplyAsync();
                return true;`

**Comment by HeroSpha** [comment]
When i deploy it online i get error Could not load file or assembly 'Microsoft.Rest.ClientRuntime, Version=2.0.0.0

**Comment by hovsepm** [comment]
@HeroSpha we base Fluent SDK on top of AutoRest generated code. We have a known bug https://github.com/Azure/azure-sdk-for-net/issues/3238 for ASP.Net targeting .Net 4.5.2 blocking calls for sync operations. Please use a separate thread for now in fluent calls (check the issue thread above) until we will ship a fix. 
Regarding ClientRuntime exceptions - could you share your project nuget package references?

**Comment by HeroSpha** [comment]
I have fixed issues by wrapping the synchronous method get with async method in Task like
`await Task.Run(async() =>
{
   var db = sqlServer.Databases.Get("dbName");
})`
