### ISSUE TITLE
[FEATURE REQ] Stuck in version 1.0.0-beta8 permanently

### ISSUE THREAD

**Issue by wrharper-AASP** [Azure/azure-sdk-for-net#35070]
### Library name

Azure.ResourceManager.KeyVault 1.0.0-beta.8

### Please describe the feature.

SelectedGroup.GetVaultAsync(desiredVault)).Value.GetSecrets().CreateOrUpdateAsync
GetSecrets() no longer exists in 1.1.0. This is required for automation with deployments in C#. I can no longer upgrade this library until this is fixed.

**Comment by HarveyLink** [comment]
Hi @wrharper-AASP ,Thank you for using Azure SDK for .NET.
With the GA version, the `GetSecrets()` is renmaned to `GetKeyVaultSecrets()`.
Please take another look, Thanks.
