### ISSUE TITLE
Sometimes ServiceBus consumers get stuck

### ISSUE THREAD

**Issue by verdysh** [Azure/azure-sdk-for-net#35074]
### Library name and version

Azure.Messaging.ServiceBus, 7.12.0

### Query/Question

Hi!

Sometimes some consumers of the topic get stuck.

Right now my clock shows 6:10 PM. If I look into some consumer in some topic, first message I see there was enqueued at 5:45:03 PM. Processing of message is just reading data from database, easy data manipulation and making some database stored procedures call.

Roughly speaking, this is 5-10 calls to the database. I have timeout set on database query execution which is 30 seconds. So if imagine that each query to database takes ~30 seconds, processing time of message can't be greater than 30 seconds * 10 queries = 300 seconds = 5 minutes. Let's triple this value, because Max delivery count for the consumer is set to 3.

But we see that first message for specific consumer isn't processed 25 minutes already.

If you go Azure portal and open the topic, you'll see the next standard graph for 1 hour:

![image](https://user-images.githubusercontent.com/21305997/226973405-9f81b074-67dd-435b-a8bd-bb8cff2dd280.png)

What I don't like on the graph is that there is 2 User errors and 525 User requests. If you look at this graph for last 6 hours, you'll see Throttled requests is 1.18K. During last hour number of throttled requests are similar to the same metric for previous 5 hours. Obviously, something weird has been happening during last hour.

While I'm writing this message, the consumer I started looking at is empty now, but the same situation I see with another consumer: it's 18:43 PM now and first message there was enqueued at 06:15:30 PM. The same situation I observed on another consumer of another topic yesterday.

I have turned on logger I created as a result of [this](https://github.com/Azure/azure-sdk-for-net/issues/33851#issuecomment-1418644531) issue. If you look at what it wrote, you can discover few common warnings:

1.
> RunOperation encountered an exception and will retry. Exception: Azure.Messaging.ServiceBus.ServiceBusException: The request was terminated because the namespace my-prod is being throttled. Error code : 50009. Please wait 2 seconds and try again. To know more visit https://aka.ms/sbResourceMgrExceptions TrackingId:5380c323000000290050fe1c641990cf_G29_B27, SystemTracker:my-prod:Topic:files, Timestamp:2023-03-22T15:58:47 (ServiceBusy). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.

2.
> Error response [51299da3-973b-4a3d-9169-9f5a50aea9ba] 503 Service Unavailable (00.2s)
> Transfer-Encoding:chunked
> ETag:637965011529870000
> Server:Microsoft-HTTPAPI/2.0
> Strict-Transport-Security:REDACTED
> Date:Wed, 22 Mar 2023 15:58:48 GMT
> Content-Type:application/xml; charset=utf-8

3.
> Response [598313c2-9b08-4e2f-8f92-3f287c11801b] took 04.1s

If you look at how the warnings were logged by minute for last hour, you'll see following:

![image](https://user-images.githubusercontent.com/21305997/226985220-55ebd33c-2081-4c34-9c03-5eee77bc7aea.png)

If to look warnings by minute and kind of "error type" you'll see following:

![image](https://user-images.githubusercontent.com/21305997/226985539-05ea30eb-a6f1-45cc-a616-48c398b68e49.png)

On screenshots above you see time 16 PM, not 18 as I said above, because the time on the screenshots is in UTC. Please notice that not every minute there were such warnings.

The question is: what's going on? Why do consumers get stuck sometimes? Is it because of ServiceBus throttling? Any other reasons? What should I do in order to get rid of this issue.

**Comment by jsquire** [comment]
Hi @verdysh.  Thank you for reaching out and we regret that you're experiencing difficulties.   If I understand correctly, what you're inquiring about is "why am I being throttled" rather than "my consumer is stuck."   At least, those are the only instances that I can see from the issue description, and the truncated query results seem to support that as well.   

Assuming that I'm not misunderstanding, then this is a service-triggered exception and not something that the SDK has influence over nor insight into.  Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) for the Service Bus service team to investigate.  You may also wish to reference the [Service Bus quotas documentation](https://learn.microsoft.com/azure/service-bus-messaging/service-bus-quotas) to help understand what limit you may be hitting.

I'm going to mark this as addressed; if I'm mistaken on your inquiry, please let us know and we'd be happy to assist further.

**Comment by verdysh** [comment]
Sorry I didn't ask a clear question an the end. The head was no longer thinking.

Having 111.67k of incoming requests, there is only 525 throttled requests. According to the total number of requests, the number of throttled requests is really small. But observing my queue I notice some consumers get stuck for a long time.

I'm asking here, because it's not clear for me if throttled requests in my particular case can be a real reason of such behavior?

**Comment by jsquire** [comment]
I am still not clear on exactly what "stuck" means in this context, but if you are being throttled frequently, you will see delays accumulate.   

The error sent by the service to indicate throttling is considered transient by the client and will be implicitly retried according to the configured retry policy.   For throttling, each retry attempt will wait an additional 10 seconds over the standard back-off.   With the default policy, if your code sees an exception, that indicates 3 retry attempts failed and 40+ seconds will have elapsed.
