### ISSUE TITLE
Can't attach CustomDomain to a web app

### ISSUE THREAD

**Issue by glaidler** [Azure/azure-sdk-for-net#3509]
Hi,

The following code won't attach a correctly set up DNS set to an existing web app:

```
.GetById(tenant.AppInstanceId).Update()
                    .DefineHostnameBinding()
                    .WithThirdPartyDomain("myapp.com")
                    .WithSubDomain("tenant")
                    .WithDnsRecordType(CustomHostNameDnsRecordType.A)
                    .Attach().Apply();
```

I have A Record pointing to the web app IP Address and a TXT record:

tenant.myapp.com > myapp.azurewebsites.net

What am I doing wrong?

**Comment by glaidler** [comment]
Ok - this looks like it doesn't like the subdomain to have underscores.

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#49
