### ISSUE TITLE
Cannot delete Azure server firewall rule using sdk

### ISSUE THREAD

**Issue by statler** [Azure/azure-sdk-for-net#35094]
### Library name and version

Azure.ResourceManager.Sql .12

### Query/Question

Referencing https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/sqlmanagement/Azure.ResourceManager.Sql/samples/Generated/Samples/Sample_IPv6FirewallRuleCollection.cs and the docs, it does not appear to be possible to remove/delete a firewall rule

Can you please advise how this is supposed to be done? It was possible with the previous library

### Environment

Windows 10 c# .Net7

**Comment by live1206** [comment]
@statler There does exist a sample to delete the firewall rule in .NET SDK Track 2, please check out https://github.com/Azure/azure-sdk-for-net/blob/4f7248dc6683ede9538a7d4538bb40218d4581be/sdk/sqlmanagement/Azure.ResourceManager.Sql/samples/Generated/Samples/Sample_IPv6FirewallRuleResource.cs#L131
