### ISSUE TITLE
Add more possible sources to second sentence 

### ISSUE THREAD

**Issue by SychevIgor** [Azure/azure-sdk-for-net#35101]
Based on code - list of supported azure compute services should be extended with arc and azure service fabric

 private static ManagedIdentitySource SelectManagedIdentitySource(ManagedIdentityClientOptions options)
 {
 return
 ServiceFabricManagedIdentitySource.TryCreate(options) ??
 AppServiceV2019ManagedIdentitySource.TryCreate(options) ??
 AppServiceV2017ManagedIdentitySource.TryCreate(options) ??
 CloudShellManagedIdentitySource.TryCreate(options) ??
 AzureArcManagedIdentitySource.TryCreate(options) ??
 TokenExchangeManagedIdentitySource.TryCreate(options) ??
 new ImdsManagedIdentitySource(options);
 }
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 42c826d6-3da7-37f3-80a4-a2bdbf3be472
* Version Independent ID: 1b1ff6a5-a8ad-8599-9644-66caad571a8a
* Content: [ManagedIdentityCredential Class (Azure.Identity) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.managedidentitycredential?view=azure-dotnet)
* Content Source: [xml/Azure.Identity/ManagedIdentityCredential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Identity/ManagedIdentityCredential.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
