### ISSUE TITLE
[QUERY] How to List releases for a specific package

### ISSUE THREAD

**Issue by A-Stapleton** [Azure/azure-sdk-for-net#35100]
### Library name and version

Azure.Identity

### Query/Question

We are looking to do some updates to things and are a few versions behind current. I was wondering if there is a way to query/list releases by package. The releases page doesn't allow us to see all release notes for one package and due to the number of different packages in this repo it's really tough to find say all releases for `Azure.identity` since 1.7.0.

I was kind of hoping it's possible somehow, does anyone know how to do this?

**Comment by jsquire** [comment]
Hi @A-Stapleton.  Our releases are published to NuGet; I'd suggest looking under the "Versions" tab for the [Azure.Identity package](https://www.nuget.org/packages/Azure.Identity#versions-body-tab) there.  That will show you the full release history.
