### ISSUE TITLE
Copy database from one server to another and rename it

### ISSUE THREAD

**Issue by HeroSpha** [Azure/azure-sdk-for-net#3511]
#Im developing a SaaS application that uses tenant per database. So whenever i provision for a new client, i have to create a new database. Im using Microsoft.Azure.Management.Fluent latest version.
For now i can copy database from one server and able to get properties and use it to create a new database. The problem im having, the schema of database (Tables) is not copied. I tried to use WithSourceDatabase that allows you to copy database, but it doesn't allow me to rename database to my liking.. What tricky can i use to copy and rename database. Or if there is a way that i can use to copy schema to my new database like im copying collation, editions etc.. Any help will be appreciated. Thanks..

**Comment by rquirante** [comment]
Hi, I’m not sure if you are still looking for an answer, but I managed to do the following and it works for me with Microsoft.Azure.Management.Fluent v1.0.2.  I've first created a template database that will be used for creating a new database with a unique name. 

See the following code for an example.

```csharp
var azure = Azure.Authenticate("authfile").WithDefaultSubscription();

//This retrieves the SQL server from the resourcegroup where the database needs to be created in
var sqlServer = azure.SqlServers.GetByResourceGroup("resourcegroup", "servername");

//This database is the template database that is used for creating a new database
var templatedb = sqlServer.Databases.Get("mytemplatedatabase");

//Create a new database based on the template database and define your name of your new database
var database = sqlServer.Databases.Define("mydatabasename")
.WithSourceDatabase(templatedb)
.WithMode(CreateMode.Copy)
.Create();
```

**Comment by martinsawicki** [comment]
seems possible using the suggested workaround so closing.
(I don't think such functionality would be built-into the SDK though, if the service doesn't expose it.)
