### ISSUE TITLE
[BUG] `BlobBaseClient.Name` doesn't reflect URI with `TrimBlobNameSlashes = false` and leading slashes

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#35121]
### Library name and version

Azure.Storage.Blobs 12.14.0

### Describe the bug

Upload a blob with Uri like "https://weirp1.blob.core.windows.net/weitest//aa/bb/cc/test.txt", note the blob name start with "/".
List the blob from the container will get BlobItem with name "/aa/bb/cc/test.txt".

But when run `BlobContainerClient.GetBlobBaseClient("/aa/bb/cc/test.txt")`, the created blobClient actually as Uri as "https://weirp1.blob.core.windows.net/weitest/aa/bb/cc/test.txt". Note the "/" in the begin of blob name disappear.

If use BlobUriBuilder to create blob Uri, by set BlobName as "/aa/bb/cc/test.txt", the created Uri will also miss the blob name first char "/". 

So the created blob Client will has wrong Uri and won't work. (since can't find the blob with the Uri on server.)

![image](https://user-images.githubusercontent.com/6926193/227414096-207239b7-b32c-4112-911a-055c62a2826f.png)

This cause Powershell bug https://dev.azure.com/msazure/One/_workitems/edit/17659911

### Expected behavior

The created Blob client should have right Uri, even the blob name is started with "/"

### Actual behavior

When blob name is started with "/", create blob Cliient with BlobContainerClient.GetBlobBaseClient(), or build blob Uri with BlobUriBuilder, the create blob client not has right URi, the first letter "/" in the blob name will disappear.

### Reproduction Steps

Upload a blob with Uri like "https://weirp1.blob.core.windows.net/weitest//aa/bb/cc/test.txt", note the blob name start with "/".

List the blob from the container will get BlobItem with name "/aa/bb/cc/test.txt".

Try to build a blob client with the listout blobitem, by running `BlobContainerClient.GetBlobBaseClient("/aa/bb/cc/test.txt")`, the created blobClient actually as Uri as "https://weirp1.blob.core.windows.net/weitest/aa/bb/cc/test.txt". Note the "/" in the begin of blob name disappear.

**Comment by jaschrep-msft** [comment]
#30271 allows blob names to begin and end with `/` given the correct flag set on configuration. Unclear from description if flag `BlobClientOptions.PreserveBlobNameSlashes` is not working or was just not known.

**Comment by blueww** [comment]
@jaschrep-msft 

Thanks for the reply!
But [BlobClientOptions](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclientoptions?view=azure-dotnet) doesn't have a property with name "PreserveBlobNameSlashes" in Azure.Storage.Blobs 12.14.0 (12.15.0 also).

However, it looks there's another option might be related.  [TrimBlobNameSlashes](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclientoptions.trimblobnameslashes?view=azure-dotnet#azure-storage-blobs-blobclientoptions-trimblobnameslashes)

I have tried to `BlobClientOptions.TrimBlobNameSlashes = false`, althrough the blob Uri it correct, but the blobClient.Name still miss the begin "/". 
Would you please help to look?

![image](https://user-images.githubusercontent.com/6926193/227702323-266c78ad-e7ee-40d2-8971-e554e12af667.png)

**Comment by jaschrep-msft** [comment]
@blueww Yes it seems that we renamed the property in a separate PR before release. You found the correct property.

It seems that while the SDK still has the correct URI setup and (presumably) is still making the expected requests, there is just the issue of the `Name` property returning the incorrect value. Updating issue title to reflect.

**Comment by blueww** [comment]
@jaschrep-msft 

Thanks for the responds!
When can we get the "name" fixed? (And could you please help to find if any other related properties need fix?)

We will update PSH after SDK is fixed.

**Comment by jaschrep-msft** [comment]
@blueww apologies if I was unclear. I had not actually validated your behavior. I was trying to better restate the bug you describe and rename the issue page.

I've just tried to reproduce this and cannot. [This test](https://github.com/Azure/azure-sdk-for-net/blob/dbdf72ecf7f994a40735cc59ebf7b5f62a6d723e/sdk/storage/Azure.Storage.Blobs/tests/BlobUriBuilderTests.cs#L979) is validating the `Name` property is as expected and it is still working. How are you constructing your blob clients to get the behavior you describe? A code sample that produces the blob client with the undesirable property name would help to debug this issue.

**Comment by blueww** [comment]
@jaschrep-msft 

I see why the issue happens on my side but not happen on yours.

- I use Azure.Storage.Blobs 12.14.0 (as the issue )
- You should use latest version.

The issue doesn't happen on the latest Azure.Storage.Blobs. 
I will upgrade to latest SDK.
Thanks for your help!
