### ISSUE TITLE
Question about system assigned identity

### ISSUE THREAD

**Issue by StefH** [Azure/azure-sdk-for-net#35128]
The example shows how the DefaultAzureCredential can be used for a **user assigned managed identity**, does the same logic apply for a **system assigned identity** ?

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 414d8832-9224-3bb5-2bf4-1197c41fdedf
* Version Independent ID: 02d95dd6-bf1b-5cef-bc94-ac187b133c45
* Content: [DefaultAzureCredential Class (Azure.Identity) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet)
* Content Source: [xml/Azure.Identity/DefaultAzureCredential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Identity/DefaultAzureCredential.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @StefH - Yes it applies to both user defined and system defined. The example in the article just happens to show the user defined scenario.
