### ISSUE TITLE
Is threshold for operation 256 MB or 256MiB

### ISSUE THREAD

**Issue by kosinsky** [Azure/azure-sdk-for-net#35139]
Document says 256MB. However, it could be a bit consusing is it actually 256 MB (256*1000*1000) or 256 MiB (256*1024*1024)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e3675f97-eaf6-3c6e-5533-bf935de7910e
* Version Independent ID: 72c75a5f-ad7f-637f-df96-276b5af503a9
* Content: [BlobBaseClient.SyncCopyFromUriAsync Method (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbaseclient.synccopyfromuriasync?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlobBaseClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@kosinsky Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@kosinsky The above PR has been filed and it is currently under review.
