### ISSUE TITLE
[BUG] FormatException in ResourceIdentifier

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-net#35154]
### Library name and version

Azure.Core 1.28.0

### Describe the bug

When a storage account network is set up with this feature [https://azure.microsoft.com/en-us/updates/storage-resource-instance-rules-preview/](url) and set up to allow 
All in current tenant or 
All in current subscription or 
All in current resource group,
the resource path that is shown in the JSON of the storage account is of the format 
"/subscriptions/\*/resourcegroups/\*/providers/Microsoft.DataFactory/factories/\*" where I assume represents the choice that has been made in the settings.

so when trying to access this property StorageAccountData.NetworkRuleSet.ResourceAccessRules[0].ResourceId (the index that the rule specified with the in its path) we get format exception because when calling the Parse function in ResourceIdentifier class which in turn calls CheckSubscriptionFormat and checks if the format is a guid format, it fails. 

https://github.com/Azure/azure-sdk-for-net/blob/bc94ecb05d18c04645b92dde10c18f2755336a46/sdk/core/Azure.Core/src/ResourceIdentifier.cs#L179-L184

### Expected behavior

ResourceIdentifier should support path with *

### Actual behavior

We get format exception

### Reproduction Steps

create storage account and add a new Resource instances in Networking tab with All in tenant

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by omri-muszkal** [comment]
@ArthurMa1978 no,
I updated the ticket without all the nonsense that was there.

With the new feature mentioned above, we get back this exact resource id
/subscriptions/\*/resourcegroups/\*/providers/Microsoft.DataFactory/factories/\*

Meaning that subscription Id, resource group name and resource name can be a wildcard.

**Comment by omri-muszkal** [comment]
Hey @ArthurMa1978, any update on this?

**Comment by ArthurMa1978** [comment]
@omri-muszkal a resource identifier cannot contain any wildcard, if contains then this is not a resource identifier but a string.
Can you let me know which SDK are you using and hit exception?

**Comment by shaneochotny** [comment]
@ArthurMa1978 it's Azure.ResourceManager.Storage

It should be treated as a string, not a resource identifier. It may contain a legitimate resource identifier, but in many cases it will have wildcards.

**Comment by HarveyLink** [comment]
Hi @shaneochotny , @ArthurMa1978 Since the original issue account is deleted, I'll reply to you two.
This feature is supported now, please use the lateste package.
```
    var storage = (await resourceGroup.GetStorageAccounts().GetAsync("rgName")).Value;
    storage.Data.NetworkRuleSet.ResourceAccessRules.Add(
        new StorageAccountResourceAccessRule() { TenantId = Guid.Parse(tenantId), ResourceId = new ResourceIdentifier("/subscriptions/*/resourcegroups/*/providers/Microsoft.Purview/Accounts/*") });
    storage = await storage.UpdateAsync(new StorageAccountPatch()
    {
        NetworkRuleSet = storage.Data.NetworkRuleSet
    });
```
