### ISSUE TITLE
Any plans to make Azure SDK for .Net available for Unity on Hololens?

### ISSUE THREAD

**Issue by joaocc** [Azure/azure-sdk-for-net#3516]
Hi,
Are there any plans to make the Azure SDK for .Net available for Unity UWP, similar to what AWS has (AWS (https://github.com/aws/aws-sdk-unity)?
For some context, pls see see https://github.com/Azure/azure-service-bus-dotnet/issues/234.
Thanks

**Comment by joaocc** [comment]
Some points which will need to be addressed:
* threading: Unity relies on it's own implementation of coroutines
* web clients: Unity uses the UnityWebRequest class instead of C# classes
* Crypto: System.Security.Cryptography.HMAC256 is not available when building for Hololens/UWP; we had to use System.Security.Cryptography.HashAlgorithm.Create("SHA-256") to make it work, which is how it seems AWS solved it in their SDK.

**Comment by cormacpayne** [comment]
@twitchax Hey Aaron, can you take a look at this issue?

**Comment by twitchax** [comment]
Hi @joaocc,

I'd like to to do some more investigation here.  What kind of Azure scenarios are you looking to implement using the Azure SDK?

**Comment by joaocc** [comment]
Hi. We are trying to connect Hololens to Azure ServiceBus for a project on assembly in manufacturing. If you want more details I can provide offline. Thx

**Comment by twitchax** [comment]
Hi @joaocc,

I think you may need support in the [Azure Service Bus Client Library](https://github.com/Azure/azure-service-bus-dotnet): the libraries here only support management scenarios (i.e., listing, creating, deleting instances).  However, it would be interesting to know if you have a management scenario in HoloLens, as well.

**Comment by joaocc** [comment]
Hi. We opened an issue there too (https://github.com/Azure/azure-service-bus-dotnet/issues/234). At this moment, we don't really have a management scenario for Hololens. Thx!
