### ISSUE TITLE
[BUG]TableClient CreateIfNotExistsAsync returns "Content-Type header value missing" intermittently

### ISSUE THREAD

**Issue by juniwang** [Azure/azure-sdk-for-net#35185]
### Library name and version

Azure.Data.Tables 12.8.0

### Describe the bug

When calling `CreateIfNotExistsAsync`, it returns "Content-Type header value missing". See details below:

 ---> Azure.RequestFailedException: Content-Type header value missing.
RequestId:a65cad2b-9002-0034-7714-616cfd000000
Time:2023-03-28T01:29:34.6706116Z
Status: 400 (Bad Request)
ErrorCode: InvalidInput

Content:
{"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"Content-Type header value missing.\nRequestId:a65cad2b-9002-0034-7714-616cfd000000\nTime:2023-03-28T01:29:34.6706116Z"}}}

Headers:
Transfer-Encoding: chunked
Server: Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: a65cad2b-9002-0034-7714-616cfd000000
x-ms-version: REDACTED
X-Content-Type-Options: REDACTED
Date: Tue, 28 Mar 2023 01:29:34 GMT
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8

at Azure.Data.Tables.TableClient.CreateIfNotExistsAsync(CancellationToken cancellationToken)
...

We are authing with managed identity. And it seems that we only see the exception after upgraded to version `12.8.0`. Not seeing any issue in previous `12.5.0`.

### Expected behavior

Not throwing exception.

### Actual behavior

Create new table if not exists, not throwing exceptions.

### Reproduction Steps

install package `<PackageReference Include="Azure.Data.Tables" Version="12.8.0" />`

code snippets:

```
var storageName = "yourStorage";
var tableName = "yourTable";
var clientOptions = new TableClientOptions();
var credential = new DefaultAzureCredential();
string tableUrl = $"https://{storageName}.table.core.windows.net/{tableName}";

var tableClient = new TableClient(new Uri(tableUrl), tableName , credential, clientOptions);
await tableClient.CreateIfNotExistsAsync(default);
```
try run multiple times.

### Environment

Windows Server 2019-Datacenter on Azure, running with .NET 6.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @juniwang I'm not able to reproduce this with your code. I get the following logging output:

```
[Informational] Azure-Core: Request [efdb9a78-8e63-4ac7-993a-c552da0c4d77] POST https://<myTable>.table.core.windows.net/Tables?$format=REDACTED
x-ms-version:REDACTED
DataServiceVersion:REDACTED
Prefer:REDACTED
Accept:application/json; odata=minimalmetadata
x-ms-client-request-id:efdb9a78-8e63-4ac7-993a-c552da0c4d77
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Data.Tables/12.8.0,(.NET 5.0.17; Microsoft Windows 10.0.22621)
Authorization:REDACTED
Content-Type:application/json; odata=nometadata
client assembly: Azure.Data.Tables
```

**Comment by juniwang** [comment]
it's also something I cannot understand. Our service calls table APIs millions of times each day. Only a small portal(around 100) failed with the exception `Content-Type header value missing`. Could it be some sort to concurrency issue?

Here is another real-world failure:
```
 ---> Azure.RequestFailedException: Content-Type header value missing.
RequestId:437d1068-3002-0040-2fd3-6106e9000000
Time:2023-03-29T00:14:58.3927644Z
Status: 400 (Bad Request)
ErrorCode: InvalidInput

Content:
{"odata.error":{"code":"InvalidInput","message":{"lang":"en-US","value":"Content-Type header value missing.\nRequestId:437d1068-3002-0040-2fd3-6106e9000000\nTime:2023-03-29T00:14:58.3927644Z"}}}

Headers:
Transfer-Encoding: chunked
Server: Windows-Azure-Table/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 437d1068-3002-0040-2fd3-6106e9000000
x-ms-version: REDACTED
X-Content-Type-Options: REDACTED
Date: Wed, 29 Mar 2023 00:14:57 GMT
Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8

   at Azure.Data.Tables.TableRestClient.UpdateEntityAsync(String table, String partitionKey, String rowKey, Nullable`1 timeout, String ifMatch, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.UpsertEntityAsync[T](T entity, TableUpdateMode mode, CancellationToken cancellationToken)
```

**Comment by christothes** [comment]
Is it possible this UpdateEntity call had an entity with no properties?

https://github.com/Azure/azure-sdk-for-net/blob/7cbac3d72de7c90d12c468063a01481e522c4d48/sdk/tables/Azure.Data.Tables/src/Generated/TableRestClient.cs#L738-L740

**Comment by juniwang** [comment]
> Is it possible this UpdateEntity call had an entity with no properties?
> 
> https://github.com/Azure/azure-sdk-for-net/blob/7cbac3d72de7c90d12c468063a01481e522c4d48/sdk/tables/Azure.Data.Tables/src/Generated/TableRestClient.cs#L738-L740

no, I'm pretty sure none of our tables entities has empty properties.

**Comment by juniwang** [comment]
Updates. Rolling Azure.Data.Tables back the version to 12.5.0 doesn't help. We are investigating the Azure.Core library. There are multiple strange behaviors that persist, it seems that **all these issues are related to http request headers**. 

Issues:
- `Response x-ms-client-request-id '2aed2c9a-4abf-45b8-8b04-0d06c4376826' does not match the original expected request id, '7f58a726-869f-400b-abcf-c148fd4f1f10`
- `Status: 400 (The value for one of the HTTP headers is not in the correct format.)`
- `Content-Type header value missing.`
- `404 (The specified resource does not exist.)`, an imediate retry succeeded which makes me believe the 404 is a false alert.

**Comment by juniwang** [comment]
Is it because of this issue: https://github.com/Azure/azure-sdk-for-net/pull/34800?

**Comment by christothes** [comment]
Upgrading to the latest Azure.Core would eliminate that as a possibility if it persists after that.

**Comment by juniwang** [comment]
Azure.Core >=1.30 fixed the issue, not seeing those strange exceptions any more. thanks.
