### ISSUE TITLE
Public release for Model Factory

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#35189]
Feature already done https://github.com/Azure/autorest.csharp/issues/2112, it'd good for us to ship it now

**Comment by heaths** [comment]
Is this also for data plane? Per [Azure SDK for .NET guidelines](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking-factory-builder), all client libraries should provide a model factory for response models.

@m-nash I thought this work was already done, or was that just for the swagger-based DPG generator?

**Comment by ArthurMa1978** [comment]
Completed this round of refresh.
