### ISSUE TITLE
Enable automation for test-proxy push

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-for-net#35208]
Currently, the `test-proxy` is installed automatically, with version pinned to [this version](https://github.com/Azure/azure-sdk-for-net/blob/0477ff753a632d691d8ab87cc276213e2cf73cde/eng/Packages.Data.props#L296).

[With a simple process start against the downloaded dll](https://github.com/Azure/azure-sdk-for-net/blob/0477ff753a632d691d8ab87cc276213e2cf73cde/sdk/core/Azure.Core.TestFramework/src/TestProxy.cs#L63).

@JoshLove-msft I believe the actual file is downloaded and unzipped by the msbuild configuration. For `python` and `js`, the downloaded exe is just placed in a local directory at the root of the repo for easy re-use. What do you think about that? Or would your recommendation be:

> Just install it for yourself

To be fair for .NET, unlike JS/Python, IS THE LANGUAGE that test-proxy was written in. That makes it a bit less out of your way to install it versus what it would be for the others.

Opening this issue to drive discussion. CC @kinelski as he brought this up in test-proxy scrum.

**Comment by JoshLove-msft** [comment]
Ideally users would not need to interact with the Test Proxy directly. If we could automatically push the assets, I think users wouldn't need to run the Test Proxy commands, right?

**Comment by scbedd** [comment]
> Ideally users would not need to interact with the Test Proxy directly. If we could automatically push the assets, I think users wouldn't need to run the Test Proxy commands, right?

How do we automatically push the assets without dramatically over-pushing to the assets repo?

**Comment by JoshLove-msft** [comment]
My suggestion was to try to use a post-commit hook.

**Comment by benbp** [comment]
I don't think making people be intentional about pushing assets is the worst outcome here, to @scbedd's point about repository over-consumption. And the more we hide operations for the user, the more edge cases we will encounter trying to make decisions about when to push.

**Comment by JoshLove-msft** [comment]
It could also be a pre-push hook so that it would only be pushed in circumstances where the user is committing and pushing it. One thing I'm not sure of is how we would otherwise prevent users from pushing recordings to the language repos going forward without something like this anyway. Are we adding some kind of CI step that checks for recordings? If it were possible for users to just use their existing workflow, and we intercept the json files behind the scenes and run the test proxy command that seems like it would be ideal.

**Comment by scbedd** [comment]
> One thing I'm not sure of is how we would otherwise prevent users from pushing recordings to the language repos going forward without something like this anyway

I don't understand this statement. Can you give me some clarity?

> Are we adding some kind of CI step that checks for recordings?

Your tests will fail without the updated recordings. You definitely won't be in a situation where code is updated and then merged without updating the assets.

**Comment by JoshLove-msft** [comment]
> I don't understand this statement. Can you give me some clarity?

Users record their tests and they have the recording files locally. What is to stop them from committing them to their branch and pushing them to the repo?

**Comment by scbedd** [comment]
> Users record their tests and they have the recording files locally. What is to stop them from committing them to their branch and pushing them to the repo?

If they have an assets.json locally...no their files will definitely not be written locally. They'll end up in the `.assets` repo at the root, gitignored from azure-sdk-for-net.

**Comment by JoshLove-msft** [comment]
> > Users record their tests and they have the recording files locally. What is to stop them from committing them to their branch and pushing them to the repo?
> 
> If they have an assets.json locally...no their files will definitely not be written locally. They'll end up in the `.assets` repo at the root, gitignored from azure-sdk-for-net.

So how are they able to inspect the recording files? They won't show up in any diff, but they will have to go to a different local repo root?

**Comment by scbedd** [comment]
> So how are they able to inspect the recording files? They won't show up in any diff, but they will have to go to a different local repo root?

It's just a git repo under there. They can go and inspect. I had other priorities dropped on me, but finishing up [this PR](https://github.com/Azure/azure-sdk-tools/pull/5552) which would enable you to just cd into the directory as a test-proxy command.

Either way.

**Comment by JoshLove-msft** [comment]
Is there any way to selectively push recordings?

**Comment by JoshLove-msft** [comment]
Chatted with @scbedd and I now have a better understanding of the user workflows. The recordings are staged locally in the assets repo and the user can interact with them via normal git commands. the test-proxy push command will commit and push everything that is staged in a new tag. 

We agreed that having a git pre-push hook along with a prompt like:
 `New recordings will be pushed to assets repo. Proceed? Y/N`
would be an acceptable path forward. @benbp, any objections to this?

**Comment by benbp** [comment]
@JoshLove-msft @scbedd I think the prompt is a good middle ground. Do you know if people run push from GUIs like VS? If so, does an interactive prompt break that? Similarly, I think we have a couple places in our automation that will push new branches (version bumps, etc.) and I don't know if we'll need to handle ignoring pre-push hooks or not depending on where this gets set up.

**Comment by JoshLove-msft** [comment]
The prompt would only occur if there are local staged changes in the assets repo so I don't think it would impact any automated pushes. In terms of the experience in VS, I think we would need to test it out to see what happens.

**Comment by JoshLove-msft** [comment]
> In the past we have generally avoided git hooks, in particular commit hooks not sure if we have tried push hooks, because they are unreliable because everyone has to set them up manually for each clone they produce which as we know doesn't end up happening.

Ah interesting, I suppose we could configure them automatically when recording tests - the hook scripts would be checked into the repo, and as part of running recorded tests we verify that they have been moved into the `hooks` folder under the `.git` directory.

> In order to have anything to push folks have to be in record mode, perhaps we can have something in the test framework that keeps reminding folks that they have un-pushed recording.

We could, but this is an effort to explore automating the process so that users don't have any additional overhead in their workflow.

**Comment by weshaggard** [comment]
I would be careful with automatically registering hooks as I mentioned the other drawback as those hooks sometimes fail or take longer than you want, and they end up blocking normal workflows.

Perhaps we could add a prompt as a post recording test run that could ask if they want to push the recordings or not.

**Comment by JoshLove-msft** [comment]
> Perhaps we could add a prompt as a post recording test run that could ask if they want to push the recordings or not.

Fair enough - I think this is a good idea.
