### ISSUE TITLE
[BUG] retrieve logs from log analytics workspace failed without any error, empty table returned.

### ISSUE THREAD

**Issue by dingjianrui** [Azure/azure-sdk-for-net#35220]
### Library name and version

Azure.Identity 1.8.2, Azure.Monitor.Query 1.1.0

### Describe the bug

I use the Azure.Monitor.Query to query the logs from log analytics workspace with "DefaultAzureCredential" or "EnvironmentCredential", by setting up the environment variables "AZURE_TENANT_ID", "AZURE_CLIENT_ID" and "AZURE_CLIENT_SECRET", it work perfectly on the laptop. here is the code:

`internal class DataRetriever
    {
        LogsQueryClient client;
        string workspaceId;
        public DataRetriever(string workspaceId) {
            this.workspaceId = workspaceId;
            var uri = new Uri("https://api.loganalytics.azure.cn");

            client = new LogsQueryClient(
                uri,
                new DefaultAzureCredential( new DefaultAzureCredentialOptions
                {
                    AuthorityHost = AzureAuthorityHosts.AzureChina
                })
                );
        }

        public async Task<LogsQueryResult> QueryAsync(string table, DateTimeOffset date, int offset)
        {
            var timeRange = new QueryTimeRange(date, date.AddMinutes(offset));
            var response = await client.QueryWorkspaceAsync(
                workspaceId,
                table,
                timeRange
                );
            return response.Value;
        }
    }`

if i run the code above in the docker container, the method "QueryAsync" return a table without any record, the point is no error throwed out.

### Expected behavior

the logs from lag analytics workspace should be returned, otherwise detailed error should be throwed out.

### Actual behavior

if the code run inside the container, no records returned and no errors.

### Reproduction Steps

Setting update the environment variables such as "AZURE_TENANT_ID", "AZURE_CLIENT_ID" and "AZURE_CLIENT_SECRET", and run the code again in the container should be able to see no records returned and no exception throwed out.

`internal class DataRetriever
    {
        LogsQueryClient client;
        string workspaceId;
        public DataRetriever(string workspaceId) {
            this.workspaceId = workspaceId;
            var uri = new Uri("https://api.loganalytics.azure.cn");

            client = new LogsQueryClient(
                uri,
                new DefaultAzureCredential( new DefaultAzureCredentialOptions
                {
                    AuthorityHost = AzureAuthorityHosts.AzureChina
                })
                );
        }

        public async Task<LogsQueryResult> QueryAsync(string table, DateTimeOffset date, int offset)
        {
            var timeRange = new QueryTimeRange(date, date.AddMinutes(offset));
            var response = await client.QueryWorkspaceAsync(
                workspaceId,
                table,
                timeRange
                );
            return response.Value;
        }
    }`

**Comment by nisha-bhatia** [comment]
Hi @dingjianrui, could you please verify that you see the expected table results in the Azure Portal on the browser? You can navigate to your Workspace -> Logs -> Custom Logs -> table. Thank you.

**Comment by scottaddie** [comment]
Ping @dingjianrui. Please see the question above. ☝️
