### ISSUE TITLE
[ACR Management Plane] CredScan failing on Azure.ResourceManager.ContainerRegistry sample

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#35227]
Please see Compliance log failure here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2665043&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=7eee3a58-6120-518b-7fcb-7e943712aa81&l=102

This is causing ACR build and CI pipeline failures for data plane pipelines:
- https://dev.azure.com/azure-sdk/public/_build/results?buildId=2665043&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2665044&view=results

We are planning to GA the data plane library this release cycle and need these pipelines green to do so.

@pallavit  FYI

**Comment by annelo-msft** [comment]
@ArthurMa1978, the data plane pipeline is still failing because of the management plane sample:
https://dev.azure.com/azure-sdk/internal/_build?definitionId=1179

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2674459&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=7eee3a58-6120-518b-7fcb-7e943712aa81&l=102

**Comment by ArthurMa1978** [comment]
@annelo-msft I have fixed the auth content in the mgmt. samples, please confirm if the dataplane pipeline is back

**Comment by annelo-msft** [comment]
Thank you @ArthurMa1978, yes, between your fix and @hallipr's work on suppression https://github.com/Azure/azure-sdk-for-net/pull/35307, the data plane pipeline is green again.  Thank you!
