### ISSUE TITLE
[BUG] CognitiveServicesAccountCollection.GetAll throws System.FormatException in case Encryption identityClientId was not set

### ISSUE THREAD

**Issue by fuliii1** [Azure/azure-sdk-for-net#35221]
### Library name and version

Azure.ResourceManager.CognitiveServices 1.2.1

### Describe the bug

I created a Cognitive Account with Terraform script. I wanted to configure Encryption with a Key Vault key. 
I configured the customer managed key with a following blocks. The identity client id is optional and I couldn't set in case of System Assigned identity.
`resource "azurerm_cognitive_account_customer_managed_key" "cacmk-bug-report" {`
`  cognitive_account_id = azurerm_cognitive_account.ca-translation.id`
`  key_vault_key_id     = azurerm_key_vault_key.kvk-translation-key.id`
`  // identity_client_id   = "" optional parameter`
`  depends_on = [`
`    azurerm_key_vault.kvbugreport,`
`    azurerm_cognitive_account.ca-translation,`
`  ]`
`}`

When I wanted to query this Cognitive Account with a following c# code I got System.FormatException because the identityClientId is empty string in api response:
`var resourceGroupName = "rg-bug-report";`
`var subscriptionId = "<your subscription>";`
`var tenantId = "<your tenant id>";`
`var clientId = "<your client id>";`
`var clientSecret = "<your client secret>";`
`var clientSecretCredential = new ClientSecretCredential(tenantId, clientId, clientSecret);`
`var armClient = new ArmClient(clientSecretCredential);`
`var subscriptionResourceId = new ResourceIdentifier($"/subscriptions/{subscriptionId}");`
`var subscription = armClient.GetSubscriptionResource(subscriptionResourceId);`
`var resourceGroups = subscription.GetResourceGroups();`
`var resourceGroup = resourceGroups.Get(resourceGroupName);`
`var cognitiveServiceAccounts = resourceGroup.Value.GetCognitiveServicesAccounts();`
`foreach (var cognitiveServiceAccount in cognitiveServiceAccounts.GetAll())`
`{`
`    Console.WriteLine(cognitiveServiceAccount.Data.Name);`
`}`

The Cognitive Account works as expected so this property really seems optional.

### Expected behavior

The `cognitiveServiceAccounts.GetAll()` read the data of the cognitive account without exception.

### Actual behavior

Throws System.FormatException in case Encryption identityClientId was not set

### Reproduction Steps

The attached a zip file contains the terraform script which create an infrastructure in azure and minimal command line application which wants to query it.

Both script uses service principal credentials for authentication

[BugReport.zip](https://github.com/Azure/azure-sdk-for-net/files/11099222/BugReport.zip)

### Environment

.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  7.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @fuliii1 , Thank you for using Azure SDK for .NET.
We can't repro your issue with the code you provide.
If possible, please capture and attach the request/response payload, it could help us to identify the issue.
