### ISSUE TITLE
[QUERY] How to set App Service CURRENT_STACK using GenericResourceData

### ISSUE THREAD

**Issue by christophwille** [Azure/azure-sdk-for-net#35238]
### Library name and version

1.4.0

### Query/Question

I asked earlier about CURRENT_STACK missing here https://github.com/Azure/azure-sdk-for-net/issues/33569. Now I tried to apply https://roanpaes.wordpress.com/2021/10/06/set-azure-app-service-stack-as-netcore-with-bicep/ using a C# approach that you can find at https://github.com/christophwille/AppServiceCurrentStackViaAzureSdk/blob/c37fad6124232e305766e6cb3d83ea74c69b06d8/Program.cs#L74

The problem is that when I try that approach - note that I verified the ResourceId (printed line 80) vs the bicep sample - I get an exception for CreateOrUpdateAsync "Invalid resource type Microsoft.Web/sites/config". I am kind of lost what I am missing at this point, or whether this is the library being smart trying to protect me from something it thinks is invalid (but actually would be valid).

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christophwille** [comment]
Any ideas what might be going on / wrong in my code?

**Comment by IanDavidJensen** [comment]
Any news on this? We are having the same issues

**Comment by christophwille** [comment]
Thanks for reminding me that this got no traction - yes, please, any ideas?

**Comment by HarveyLink** [comment]
@ArthurMa1978 Swagger issue was fixed long ago, we need to release a new version of AppService.

**Comment by HarveyLink** [comment]
Fixing has been released.

**Comment by christophwille** [comment]
And where on the object model can I find this now?

**Comment by christophwille** [comment]
is 

https://github.com/christophwille/AppServiceCurrentStackViaAzureSdk/blob/a65d8d35aa51eec3a6c93bfc06efe6eeec651ebe/Program.cs#L68-L73
![image](https://github.com/Azure/azure-sdk-for-net/assets/344208/e817ad4e-c488-4d0e-8535-779b8578e6e1)

the correct approach (GetMetadataAsync + UpdateMetadataAsync)?
