### ISSUE TITLE
Creating a Diagnostic Setting to a FunctionApp to log to a Log Analytics Workspace

### ISSUE THREAD

**Issue by richaplinvs** [Azure/azure-sdk-for-net#35240]
### Library name and version

Azure.ResourceManager.AppService 1.0.01, Azure.ResourceManager 1.4.0

### Query/Question

I want to configure the FunctionApp to log to a Log Analytics Workspace using the Diagnostic Setting. However I can't see how to do this with the Azure.ResourceManager api.

I have created a function using the following code:

    var webSiteData = new WebSiteData(location);
    webSiteData.Kind = "functionapp";
    var funcResponse = await resourceGroup.GetWebSites().CreateOrUpdateAsync(WaitUntil.Completed, functionName, webSiteData);
    var funcResource = funcResponse.Value;

There's a `GetSiteDiagnostics()` but no equivalent Update method. There's very limited samples for this API and even looking through the source code is hard as the comments are all autogenerated seem to restate class/method names - is there some other resource that would help?

Any help would be appreciated!

### Environment

.Net runtime
Visual Studio for Mac.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by melina5656** [comment]
Hi @richaplinvs Thank you for using Azure SDK for .NET.
It seems like you are looking at a wrong package. The correct package would be:[Azure.ResourceManager.Monitor](https://www.nuget.org/packages/Azure.ResourceManager.Monitor/1.3.0-beta.2)
The code sample you may refer:
```
     //Create a Diagnostic Setting
     var scope = appServicePlan.Id;
     var dsname = "ds1";
     var diagnostSettingCollection = client.GetDiagnosticSettings(scope);
     var diagnostSettingData = new DiagnosticSettingData()
     {
         WorkspaceId = new ResourceIdentifier(workspace.Id),
         StorageAccountId = new ResourceIdentifier(storageAccount.Id),
         Metrics =
         {
             new MetricSettings(true)
             {
                 Category = "AllMetrics",
             }
         }
     };
     var diagnost = await diagnostSettingCollection.CreateOrUpdateAsync(WaitUntil.Completed, dsname, diagnostSettingData);
     Console.WriteLine(diagnost.Value.Data.Id);
```
