### ISSUE TITLE
Fix Microsoft.Azure.Management.EventHub Nuget Project Url

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-sdk-for-net#3526]
The Microsoft.Azure.Management.EventHub Nuget package points to Azure/AutoRest as its project URL.

**Comment by shahabhijeet** [comment]
@dsouzaarun can someone fix this in the next release?

**Comment by v-Ajnava** [comment]
@dsgouda  URL is fixed , can you please close the issue

**Comment by dsgouda** [comment]
Closing per @v-Ajnava 's feedback
