### ISSUE TITLE
Code samples reference undefined Randomize method

### ISSUE THREAD

**Issue by jcookems** [Azure/azure-sdk-for-net#35263]
I'm trying to get started with the ADL SDK, but it is hard to find samples that compile. Ideally on this page, I could just grab the nugets, paste the examples into my code, enter my storage account name and key, and things would "just work". It would be fine to have a good default container name, default folder name, etc in the samples, and not rely on this mysterious `Randomize` method. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9835cfa1-a74f-824b-7ea7-9ffbdc95949d
* Version Independent ID: 7fb8e181-99de-0e45-0147-77e5d99b32e7
* Content: [Azure Storage Files Data Lake client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/storage.files.datalake-readme?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/storage.files.datalake-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/storage.files.datalake-readme.md)
* Service: **storage**
* GitHub Login: @seanmcc-msft
* Microsoft Alias: **seanmcc**

**Comment by jcookems** [comment]
For contrast, look at https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-directory-file-acl-dotnet. Sure, some of the methods assume you'll have a "my-image.png" in the data lake, but they at least give an idea of how it would work.

**Comment by SaurabhSharma-MSFT** [comment]
@jcookems We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@jcookems The PR for the fix has been created and it will be merged soon. Thanks again for pointing this out, I am closing the issue based on this update, please let us know if there is something else that we can help you with.
