### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mvin246** [Azure/azure-sdk-for-net#35277]
### Library name and version

Azure function apps

### Describe the bug

Our code is using UTF encoding during XML serializing and deserializing.
During azure function upgrade from V3 to V4 we observed that existing started failing and we observed that previously working XML's are failing to serialize/deserialize because BOM (???) is introduced.

To address this issue we added code to identify BOM characters and remove them while serializing.
While code _str.StartsWith(_byteOrderMarkUtf8)_ was working fine with both XML's with BOM & without BOM. We recently observed that it started failing in hosted environment ( We are using Windows App service plan), while in our local it was working fine.

Recently our local machines Windows got updated and we observed that same is reproducible in local environment as well.
Can you please help us with root cause for issue and resolve same.

In a nutshell, while str.StartsWith(_byteOrderMarkUtf8) was returning false, when XML is without BOM, currently its returning true even when XML is without BOM.
Same with below code 
string.IsNullOrWhiteSpace(_byteOrderMarkUtf8) or
string.IsNullOrEmpty(_byteOrderMarkUtf8))

Above lines of code is returning false even when the value of _byteOrderMarkUtf8 = "", which should return true.

### Expected behavior

_str.StartsWith(_byteOrderMarkUtf8) - Should return false, when XML doesn't contain BOM (in our case ???)

string.IsNullOrEmpty(_byteOrderMarkUtf8)) - Should return true when _byteOrderMarkUtf8 = "" 

string.IsNullOrWhiteSpace(_byteOrderMarkUtf8) - Should work as expected

### Actual behavior

 str.StartsWith(_byteOrderMarkUtf8) is returning true even when XML is without BOM.
Same with below code 
string.IsNullOrWhiteSpace(_byteOrderMarkUtf8) or
string.IsNullOrEmpty(_byteOrderMarkUtf8))

Above lines of code is returning false even when the value of _byteOrderMarkUtf8 = "", which should return true.

### Reproduction Steps

public static string SerializeToXmlString(object objectToSerialize)
{
    MemoryStream mem = new MemoryStream();
    XmlSerializer serializer = null;

    serializer = new XmlSerializer(objectToSerialize.GetType());

    serializer.Serialize(mem, objectToSerialize);
    byte[] bytes = mem.ToArray();
    string serializedXml = Encoding.UTF8.GetString(bytes);
 
    // Check if the serialized XML starts with the byte order mark (BOM)
    string bom = Encoding.UTF8.GetString(Encoding.UTF8.GetPreamble());
    if (serializedXml.StartsWith(bom))
    {
        // Remove the BOM from the serialized XML
        serializedXml = serializedXml.Substring(bom.Length);
    }
 
    return serializedXml;
}

Another snip
            if (!string.IsNullOrEmpty(_byteOrderMarkUtf8))
            {
                str = str.Remove(0, _byteOrderMarkUtf8.Length);
            }

### Environment

App Service Plan - Windows 
App service (Function App) - .Net,   Version ~4

Hosted environment
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86

Host:
  Version:      7.0.2
  Architecture: x86
  Commit:       d037e070eb

**Comment by jsquire** [comment]
This issue has been transferred to the Azure Functions repository as [#2361](https://github.com/Azure/Azure-Functions/issues/2361).
