### ISSUE TITLE
[FEATURE REQ] List NetworkInterfaces for VMSS

### ISSUE THREAD

**Issue by hcoona** [Azure/azure-sdk-for-net#35270]
### Library name

Azure.ResourceManager.Compute

### Please describe the feature.

I want to query VM binding private IP from a VMSS but found there's no way in our C# SDK.

Corresponding RESTful API: https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-interface-in-vm-ss/list-virtual-machine-scale-set-vm-network-interfaces?tabs=HTTP

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Related to #35717

**Comment by ArthurMa1978** [comment]
We have released new [version](https://www.nuget.org/packages/Azure.ResourceManager.Network/1.6.0-beta.1) for the VMSS.
