### ISSUE TITLE
[QUERY]: How can we use AzureEnvironment class going forward as Microsoft.Azure.Management.ResourceManager.Fluent package is deprecated ?

### ISSUE THREAD

**Issue by harshashetty67** [Azure/azure-sdk-for-net#35275]
### Library name and version

Microsoft.Azure.Management.ResourceManager.Fluent

### Query/Question

we are using **Microsoft.Azure.Management.ResourceManager.Fluent** to work with **AzureEnvironment** class, since this package is deprecated what is the alternative to continue using AzureEnvironment class (as I don't see proper replacement in the new **Azure.ResourceManager** package for AzureEnvironment) ?

**Comment by ArthurMa1978** [comment]
Hey @harshashetty67 this class has been removed from Track 2, for the auth endpoint you can find in the Identity sdk https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/AzureAuthorityHosts.cs

**Comment by jostubbl** [comment]
/unresolve I also cannot find a valid replacement for the AzureEnvironment class. How do you recommend we get the same information for each cloud (Name, AuthenticationEndpoint, ResourceManagerEndpoint, ManagementEndpoint, GraphEndpoint,, StorageEndpointSuffix, KeyVaultSuffix)?
