### ISSUE TITLE
[FormRecognizer] AnalyzePrebuiltDocumentFromFileAsync failing in nightly runs 

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#35271]
FormRecognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Resource not found
> Status: 404 (Not Found)
> ErrorCode: 404
> 
> Content:
> {"error":{"code":"404","message":"Resource not found"}}
> 
> Headers:
> Content-Length: 55
> Content-Type: application/json
> Date: Fri, 31 Mar 2023 03:59:50 GMT
> 
> 
> Stack trace
>    at Azure.AI.FormRecognizer.DocumentAnalysis.DocumentAnalysisRestClient.<DocumentModelsAnalyzeDocumentAsync>d__11.MoveNext() in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\src\Generated\DocumentAnalysisRestClient.cs:line 220
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at Azure.AI.FormRecognizer.DocumentAnalysis.DocumentAnalysisClient.<AnalyzeDocumentAsync>d__7.MoveNext() in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\src\DocumentAnalysisClient.cs:line 173
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Samples.DocumentAnalysisSamples.<AnalyzePrebuiltDocumentFromFileAsync>d__7.MoveNext() in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\tests\samples\Sample_AnalyzePrebuiltDocumentFromFileAsync.cs:line 30
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2669167&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Should be fixed by https://github.com/Azure/azure-sdk-for-net/pull/35244.
