### ISSUE TITLE
Invalid link for button.

### ISSUE THREAD

**Issue by Wei-YB** [Azure/azure-sdk-for-net#35288]
Invalid link for the Exlpore the client APIs button.
![image](https://user-images.githubusercontent.com/45348633/229268933-17173625-1dbb-4f21-825f-ac6da8045775.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bc1afc6d-893e-2658-7ba3-0bbfbd08fdae
* Version Independent ID: 23cff34d-6872-c670-c007-6f5fa1f80025
* Content: [Azure Application Insights libraries for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/insights?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/insights.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/insights.md)
* Service: **application-insights**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@Wei-YB We are looking into it and get back to you for any additional information.
