### ISSUE TITLE
Without a code example, it is not useful

### ISSUE THREAD

**Issue by nchennou** [Azure/azure-sdk-for-net#35292]
[Without a code example, it is not useful]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58442835-d11e-2643-2de2-019934bd6ef8
* Version Independent ID: 87390f29-835d-078b-4e8a-3f0ef5937e0f
* Content: [ForecastingModel.AutoArima Property (Azure.ResourceManager.MachineLearning.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.machinelearning.models.forecastingmodel.autoarima?view=azure-dotnet)
* Content Source: [xml/Azure.ResourceManager.MachineLearning.Models/ForecastingModel.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.MachineLearning.Models/ForecastingModel.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by NejibChennoufi** [comment]
If you think you answered my question then go ahead and close the issue.
I moved on because it took so much time and did not even receive a useful answer.

I was asking you to provide a small piece of code that demonstrates how you call AutoArima.
If you put an effort, I would appreciate it.

**Comment by NejibChennoufi** [comment]
/unresolve
If you think you answered my question then go ahead and close the issue.
I moved on because it took so much time and did not even receive a useful answer.

I was asking you to provide a small piece of code that demonstrates how you call AutoArima.
If you put an effort, I would appreciate it.

**Comment by NejibChennoufi** [comment]
But I am the original author!

**Comment by nchennou** [comment]
/unresolve
If you think you answered my question then go ahead and close the issue.
I moved on because it took so much time and did not even receive a useful answer.

I was asking you to provide a small piece of code that demonstrates how you call AutoArima.
If you put an effort, I would appreciate it.

**Comment by ArthurMa1978** [comment]
Hey @nchennou, this is a reference doc auto-generated from the sdk which doesn't contain any samples. 

Unfortunately, there's no further help that we can provide.  This repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues / requests.   If further help is needed, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request), and I'm going to close this out.
