### ISSUE TITLE
Would you please include a code example in C#?

### ISSUE THREAD

**Issue by nchennou** [Azure/azure-sdk-for-net#35298]
[Would you please include a code example in C#?
Thank you!]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 58442835-d11e-2643-2de2-019934bd6ef8
* Version Independent ID: 87390f29-835d-078b-4e8a-3f0ef5937e0f
* Content: [ForecastingModel.AutoArima Property (Azure.ResourceManager.MachineLearning.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.machinelearning.models.forecastingmodel.autoarima?view=azure-dotnet)
* Content Source: [xml/Azure.ResourceManager.MachineLearning.Models/ForecastingModel.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.MachineLearning.Models/ForecastingModel.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This request is tracked in #35292.   Closing this as a duplicate.
