### ISSUE TITLE
[QUERY] Equivalent of "az rest" in SDK?

### ISSUE THREAD

**Issue by gmantri** [Azure/azure-sdk-for-net#35306]
### Library name and version

Azure.ResourceManager.Resources 1.4.0 

### Query/Question

I am wondering if there is something similar to [`az rest`](https://learn.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-rest) in Azure SDK?

What I want to accomplish is to be able to make Azure REST API calls using the SDK without installing a bunch of Nuget packages. For example, I would like to get complete details about a storage account without installing Azure Storage Resource Manager Nuget.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
@gmantri Thank you for using Azure SDK for .NET.
Unfortunally the SDK doesn't support custom request for now.
If you would like to get the detail info of any type of resource, you could use `GenericResource` Type.
Sample: https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/resourcemanager/Azure.ResourceManager#get-genericresource
