### ISSUE TITLE
[Core] Make RequestFailedDetailsParser easier to use for unbuffered streams

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#35355]
Today, any implementation of RequestFailedDetailsParser where the response content is an unbuffered network stream must overwrite response.ContentStream in order to log the "Content:" portion of the RequestFailedException message.  Ideally, since any RequestFailedDetailsParser implementation must read the stream content to parse the exception, the interface would allow the caller to pass back the content it read and populate the "Content" on the message from that.

There are a couple other things that would be good to do here as well:
- We could centralize the content buffering in Core when we have an error message, so each customer parser doesn't have to do this, potentially in a different way
- We could either remove the message formatting in ClientDiagnostics entirely, in favor of the RFE implementation, or make these share common code -- currently this code is duplicated and different, so exception messages could be different depending on the code path that is followed.

Related to, and potentially could be done holistically as part of work on:
- https://github.com/Azure/azure-sdk-for-net/issues/27490
- https://github.com/Azure/azure-sdk-for-net/issues/24031
- https://github.com/Azure/azure-sdk-for-net/issues/19987 (is this complete?)
- https://github.com/Azure/azure-sdk-for-net/issues/9792

**Comment by annelo-msft** [comment]
@AlexanderSher  also made the good suggestion to consolidate buffering code to a single place in Core: https://github.com/Azure/azure-sdk-for-net/pull/35318#discussion_r1158638851

We should consider that as part of this work, and update ContainerRegistryRequestFailedDetailsParser.cs to use the common buffering code when it's available.

**Comment by AlexanderSher** [comment]
If we assume that custom `RequestFailedDetailsParser` would like to parse the content, we can ensure the content stream is buffered (when content type header is present). That way, `RequestFailedDetailsParser` can directly call `JsonDocument.Parse(response.ContentStream)`.

When `RequestFailedDetailsParser` is not specified, `RequestFailedException.GetRequestFailedExceptionContent` would call `TryExtractErrorContent`, which is not very effective (it creates readers and converts JSON input into UTF-16 string before converting it back). So using buffering code from [`ResponseBodyPolicy`](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/Internal/ResponseBodyPolicy.cs#L78-L110) can help in the default case as well.

**Comment by JoshLove-msft** [comment]
RequestFailedDetailsParser no longer operates on unbuffered content as of https://github.com/Azure/azure-sdk-for-net/pull/35716
