### ISSUE TITLE
[QUERY] Distributed tracing Activity scope for batched Service Bus Functions

### ISSUE THREAD

**Issue by jacobjmarks** [Azure/azure-sdk-for-net#35392]
### Library name and version

Azure.Messaging.ServiceBus 7.13.1
Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.9.0

### Query/Question

There currently exists discrepancies when processing Service Bus messages in either a batched versus singular fashion regarding Activity scoping and how the Functions consider incoming message `Diagnostic-Id` properties.

In my scenario, one (or many) message producers are sending Service Bus messages to a given queue/topic and each of these messages may contain different `Diagnostic-Id`s. The expectation here, is that this producer-provided trace ID is appropriately utilised within the Function when processing the message, and in turn is appropriately sent to any downstream components.

Now, when using a singular message Function (as below), this works perfectly.

``` csharp
public ProcessIncomingMessage([ServiceBusTrigger(...)] ServiceBusReceivedMessage message)
{
    // Activity "ServiceBusProcessor.ProcessMessage"
    // uses incoming `Diagnostic-Id` ✅

    DoWork(message);
}
```

When using a batched message Function, however, incoming `Diagnostic-Id`s are being somewhat "squashed" at this level; the Activity uses a new ID (which is being sent downstream), and the individual message trace IDs are added to `Activity.Links`. As below:

``` csharp
public ProcessIncomingMessages([ServiceBusTrigger(...)] ServiceBusReceivedMessage[] messages)
{
    // Activity "ServiceBusListener.ProcessMessages"
    // uses new Id; incoming `Diagnostic-Id`s added to `Activity.Links` 🤔

    foreach (var message in messages)
    {
        DoWork(message);
    }
}
```

This seems backwards, I would expect that the incoming `Diagnostic-Id`s be used as the "primary" Activity ID and the "batch" Activity is added as a Link (or equivalent).

Whether or not the message consumer processes messages in batch or singularly could be considered an implementation detail (at least in this scenario) and the message producer shouldn't care; it would expect that the `Diagnostic-Id` it provided in a given message is the trace ID used for any downstream actions performed in its processing.

Now, by this point it may seem obvious that such scoping is just not really feasible within a method written like this (with a `ServiceBusReceivedMessage[]` argument), and the workaround/solution is to simply perform this context flip manually within the batch processor:

``` csharp
foreach (var message in messages)
{
    using var activity = new Activity("ServiceBusProcessor.ProcessMessage");

    // preserve reference to the batch Activity (optional)
    activity.AddBaggage("BatchActivityId", Activity.Current.Id);

    // use incoming `Diagnostic-Id` (if present)
    if (message.ApplicationProperties.TryGetValue("Diagnostic-Id", out var value)
        && value is string diagnosticId
        && ActivityContext.TryParse(diagnosticId, null, out var parentContext))
    {
        activity.SetParentId(parentContext.TraceId, parentContext.SpanId, parentContext.TraceFlags);
    }

    activity.Start();

    DoWork(message);
}
```

I guess my main question at this point is whether or not this would be the suggested approach; or whether there's another way of implementing a batch-triggered Function such that the trace IDs are registered as I would expect them to be (per-message). The documentation I could find on this subject is rather limited.

cc @JoshLove-msft #30279

### Environment

.Net SDK 6.0.407

**Comment by jsquire** [comment]
//cc: @lmolkova

**Comment by JoshLove-msft** [comment]
Hi @jacobjmarks, 
The behavior you are describing is intentional and is based on the Open Telemetry specification - specifically the section describing [batch processing](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/messaging/#batch-processing). I believe your suggested workaround makes sense if you have a requirement that the producer span is a parent of the processing span.

**Comment by jacobjmarks** [comment]
Right. I might have been looking in the wrong places but as far as I could see there was little to no documentation which described this behaviour even at a general level; referring to Open Telemetry specifications. It was very much a case of trial and error and manual debugging to deduce how the Activities were being used when executing my Service Bus Functions. While I'm relatively new to this domain of observability and tracing, I feel as though the documentation failed to adequately inform me (or refer me to somewhere that could). Happy to close this off. Thanks for the assistance!

**Comment by JoshLove-msft** [comment]
>  I feel as though the documentation failed to adequately inform me (or refer me to somewhere that could

We do have a section in our [troubleshooting guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/TROUBLESHOOTING.md#distributed-tracing) dedicated to tracing. We can include this information over there. Out of curiosity, where were you attempting to look for docs?

**Comment by jacobjmarks** [comment]
It was mostly the various Microsoft Learn pages for Distributed Tracing/Service Bus Functions and what markdown files I could find across the Azure/dotnet GitHub orgs. Looks like I should have been more thorough as what you've linked has been helpful (although it doesn't look like there are any references to the newer `ServiceBusListener.ProcessMessages` span for batches). I feel as though a dedicated section on distributed tracing with a more detailed explanation of each span would be very helpful, and may have greatly reduced the time it took for me to ascertain what knowledge I now have.

For the most part as well, I had the mindset of "I'm using Application Insights, not Open Telemetry; I don't need to read extensive documentation (if any at all) on the latter." Though this may have obviously been a detriment.

In addition, is the `ActivitySource` support still considered experimental? I've not done any of the [configuration](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#activitysource-support) stated to be required to enable this support but from my observations, it looks to just work&trade;.

**Comment by JoshLove-msft** [comment]
I should clarify that the behavior to use links with batches applies to both ActivitySource (which is still experimental), and the GA DiagnosticSource support. However, it was influenced by the Open Telemetry spec. I will add a section into the guide that discusses the different behavior between batches/single messages.

**Comment by jacobjmarks** [comment]
In an attempt to better associate the Activity for the batch with the Activity for each message, I am looking to add the batch Activity as an `ActivityLink` on the Activity which I create to process a single message (instead of simply adding the trace ID for the batch as baggage/tags).

Now, the only way I have found to set Activity links is via methods on the `ActivitySource` instance (`CreateActivity` and `StartActivity`), however, when I attempt to create an Activity via the `Activity.Current.Source` instance, this instance is the general "static" source instance (that being with an empty name) without listeners and as such I get `null` instead of an `Activity`.

I do not want to have to create my own listener, as I've done nothing of the sort elsewhere. I want to lean on the Application Insights "bootstrapping" that is occurring behind the scenes.

Let me know if I should just forgo this and instead simply keep a reference to the batch Trace ID as baggage/tags; otherwise, how I might: 
- add a link to an Activity _without_ using `ActivitySource`, or
- get an "active" `ActivitySource` to use to create my Activity instances, or
- get the one or more active listeners which I can register to my own `ActivitySource`?

Overall I'm just looking to achieve parity with the `ServiceBusProcessor.ProcessMessage` span, as if this Function _wasn't_ batched.

**Comment by JoshLove-msft** [comment]
I suspect the ActivitySource creation doesn't work because you are not using the experimental ActivitySource support so there is no named ActivitySource as you mentioned. The process for adding links for non-activity source activities is not really supported in the APIs. If you want to move forward with links, you might want to consider trying out the ActivitySource support steps.

**Comment by JoshLove-msft** [comment]
> Are you saying that the `Activity.Source` for the `"ServiceBusListener.ProcessMessages"` Activity should be named if experimental ActivitySource support is enabled? I have just tried this — referencing `System.Diagnostics.DiagnosticSource` `6.0.1` and setting `Azure.Experimental.EnableActivitySource` via the `.csproj` `RuntimeHostConfigurationOption`s — and the `Activity.Source` is still unnamed.
> 
> Note as well that I am running this via Azure Function Core Tools `4.0.5095`, if this affects things.

You would also need an activity source listener, full steps are here - https://devblogs.microsoft.com/azure-sdk/introducing-experimental-opentelemetry-support-in-the-azure-sdk-for-net/#get-started

**Comment by jacobjmarks** [comment]
Indeed yes. After doing some observations on the Application Insights transactions I think the links on the batch activity should be enough; the batch will be included if searching for the child (despite the child not knowing about the batch).

In summary, I think I've come to an adequate solution. Where downstream activity scoping was previously squashed by the batch - as represented below ...

![before](https://user-images.githubusercontent.com/19641427/231356317-9f72b929-187a-40ee-960c-373b225dde6e.jpg)

Manual creation of child activities allows us to maintain the specific downstream scope:

![after](https://user-images.githubusercontent.com/19641427/231356343-256ba808-9594-44e3-bb10-db7089f8319f.jpg)
