### ISSUE TITLE
Docs ToC namespace generation should store namespace data separately from metadata

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-net#35403]
This is needed to better support onboarding of packages which release outside of our EngSys. 

Current code has the side effect of producing metadata JSON files which effectively "freeze" a package at a given version when producing the ToC for that package. https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/docs/Docs-ToC.ps1#L193

1. Package is in metadata CSV file in Azure/azure-sdk repo with VersionGA 1.0.0, has no metadata JSON file (did not release from our EngSys)
2. docindex pipeline runs
    1. Onboards Package@1.0.0 into `bundlepackages/azure-dotnet.csv` 
    2. Generates ToC entries for Package@1.0.0
        1. No metadata JSON file exists, begins creating one at version 1.0.0 (with version information of 1.0.0) 
        2. Downloads package, extracts namespaces, adds to "Namespaces" field in newly created metadata JSON file
        3. Writes metadata JSON file
3. Package release a new version (1.2.3) 
4. Metadata CSV in Azure/azure-sdk updates to VersionGA 1.2.3
5. docindex pipeline runs
    1. Reads metadata CSV and metadata JSON, metadata JSON reports version 1.0.0 which overrides CSV version of 1.2.3, no change is made to onboarding.
    2. Subsequent scripts run but, because they're using Package@1.0.0, no changes are made to subsequent files

Because 2.ii.c writes information which is not updated by releases from our EngSys, the package stays pinned at Package@1.0.0 until the metadata JSON is updated. 

Proposed fix: 
* Use a separate file to track namespaces for packages. Separate file should include package version information (e.g. `namespaces/Package@1.2.3.txt`) so we can infer whether the namespaces for a given package and version have been evaluated. 
* Do not write to metadata JSON files except in appropriate circumstances
    * EngSys artifacts from a release
    * Properly define how packages released external to our EngSys are tracked

**Comment by JimSuplizio** [comment]
@danieljurek, the proposed change isn't going to happen. Everything, right now, has namespaces in their package json files. For Java, the .txt files which contained namespaces were removed and the namespaces put them back into the json files.

**Comment by JimSuplizio** [comment]
@danieljurek and I chatted, as per my previous comment this issue is defunct.
