### ISSUE TITLE
[KeyVault] BackupAndRestoreMultiPartFolderName failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#35419]
KeyVault nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Invalid backup: Reason: Cannot read backup status document
> InnerError:
> Code: BadRequest
> 
> 
> Stack trace
>    at Azure.Security.KeyVault.Administration.RestoreOperationInternal`3.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/keyvault/Azure.Security.KeyVault.Administration/src/RestoreOperationInternal.cs:line 221
>    at Azure.Security.KeyVault.Administration.RestoreOperationInternal`3.UpdateStatusAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/keyvault/Azure.Security.KeyVault.Administration/src/RestoreOperationInternal.cs:line 181
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, Operation operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 65
>    at Azure.Core.OperationPoller.WaitForCompletionAsync[T](Operation`1 operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 39
>    at Azure.Core.OperationHelpers.DefaultWaitForCompletionAsync[TResult](Operation`1 operation, TimeSpan pollingInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationHelpers.cs:line 45
>    at Azure.Security.KeyVault.Administration.Tests.FullBackupClientLiveTests.BackupAndRestoreMultiPartFolderName() in /mnt/vss/_work/1/s/sdk/keyvault/Azure.Security.KeyVault.Administration/tests/FullBackupClientLiveTests.cs:line 78
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.&lt;&gt;c__DisplayClass1_0.&lt;Execute&gt;b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2683010&view=results

@jsquire for notification.

**Comment by heaths** [comment]
This is already being tracked.
