### ISSUE TITLE
[FormRecognizer] BuildClassifierOperationCanPollFromNewObject failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#35418]
FormRecognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Invalid request.
> Status: 200 (OK)
> ErrorCode: InvalidRequest
> 
> Additional Information:
> AdditionInformation: InvalidRequest: Invalid request.
> 
> Details:
> ContentSourceNotAccessible: Content is not accessible: Invalid data URL
> 
> Raw:
> {
> "code": "InvalidRequest",
> "message": "Invalid request.",
> "details": [
> {
> "code": "ContentSourceNotAccessible",
> "message": "Content is not accessible: Invalid data URL"
> }
> ]
> }
> 
> Content:
> 
> Headers:
> Transfer-Encoding: chunked
> ms-azure-ai-errorcode: REDACTED
> x-envoy-upstream-service-time: 19
> apim-request-id: 52e70713-905d-4a68-b27c-40893958a9fc
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> x-content-type-options: nosniff
> x-ms-region: REDACTED
> Content-Type: application/json; charset=utf-8
> Date: Fri, 07 Apr 2023 04:26:33 GMT
> 
> Data:
> AdditionInformation: InvalidRequest: Invalid request.
> 
> Details:
> ContentSourceNotAccessible: Content is not accessible: Invalid data URL
> 
> Raw:
> {
> "code": "InvalidRequest",
> "message": "Invalid request.",
> "details": [
> {
> "code": "ContentSourceNotAccessible",
> "message": "Content is not accessible: Invalid data URL"
> }
> ]
> }
> 
> 
> Stack trace
>    at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 290
>    at Azure.Core.OperationInternal`1.&lt;UpdateStatusAsync&gt;d__20.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 278
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternalBase.&lt;UpdateStatusAsync&gt;d__13.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 87
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationPoller.&lt;WaitForCompletionAsync&gt;d__11.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 79
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternalBase.&lt;WaitForCompletionResponseAsync&gt;d__19.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 212
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternal`1.&lt;WaitForCompletionAsync&gt;d__19.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 242
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternal`1.&lt;WaitForCompletionAsync&gt;d__15.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 177
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.AI.FormRecognizer.DocumentAnalysis.BuildDocumentClassifierOperation.&lt;WaitForCompletionAsync&gt;d__16.MoveNext() in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\src\BuildDocumentClassifierOperation.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.OperationsLiveTests.&lt;BuildClassifierOperationCanPollFromNewObject&gt;d__6.MoveNext() in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\tests\DocumentAnalysisModels\OperationsLiveTests.cs:line 147
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.OperationsLiveTests.&lt;BuildClassifierOperationCanPol

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2685224&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Will be fixed by https://github.com/Azure/azure-sdk-for-net/pull/35362.
