### ISSUE TITLE
DocumentDB: WithBoundedStalenessConsistency() parameter mixup

### ISSUE THREAD

**Issue by johnstairs** [Azure/azure-sdk-for-net#3542]
Consider this example:

```
IDocumentDBAccount account = azure.DocumentDBAccounts
    .Define("jostairs-arm-cosmos-test-5")
    .WithRegion(Region.USWest)
    .WithExistingResourceGroup("platexp-wus-rg")
    .WithKind(DatabaseAccountKind.GlobalDocumentDB)
    .WithBoundedStalenessConsistency(maxStalenessPrefix: 100, maxIntervalInSeconds: 5)
    .WithWriteReplication(Region.USWest)
    .Create();
```

When executed, the following exception is thrown:

> Microsoft.Rest.Azure.CloudException occurred
>   HResult=0x80131500
>   Message=MaxStalenessPrefix should be greater than or equal to 10 and less than or equal to 1000000
> ActivityId: 73db67f0-3dd1-447e-b9c4-3514b6da0581
>   Source=Microsoft.Azure.Management.DocumentDB.Fluent

The error is incorrect. Now if I swap the arguments:

```
IDocumentDBAccount account = azure.DocumentDBAccounts
    .Define("jostairs-arm-cosmos-test-5")
    .WithRegion(Region.USWest)
    .WithExistingResourceGroup("platexp-wus-rg")
    .WithKind(DatabaseAccountKind.GlobalDocumentDB)
    .WithBoundedStalenessConsistency(maxStalenessPrefix: 5, maxIntervalInSeconds: 100)
    .WithWriteReplication(Region.USWest)
    .Create();
```
It works, but I end up with a database account with a maxStalenessPrefix of 100, and maxIntervalInSeconds of 5.

**Comment by martinsawicki** [comment]
addressed in v1.3
