### ISSUE TITLE
[QUERY] ClientOptions - how to use it?

### ISSUE THREAD

**Issue by klnsdfjlkasdfkj** [Azure/azure-sdk-for-net#35426]
### Library name and version

Azure.Messaging.ServiceBus

### Query/Question

There is a good article that describes how to activate logging of internal trace messages
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md
I used it to activate internal information for the service bus. 
But there is a part about SecretClientOptions. I guess in the context of the service bus it will be ServiceBusAdministrationClientOptions. And it is not clear how to use/where to pass/where to setup that ClientOptions. No examples. Documentation also doesn't give an answer. Could you please provide a good example and update that Diagnostic.md file?

### Environment

Core

**Comment by jsquire** [comment]
Hi @klnsdfjlkasdfkj.   Thank you for reaching out and we regret that you're experiencing difficulties.  The `ClientSecretOptions` that you're referring to is just an example used to demonstrate setting the options.  That type is used with the `ClientSecretCredential` from `AzureIdentity`.

The properties that you're inquiring about can be found in any subtype of `ClientOptions`, which includes all of the option types for the Azure SDK clients using HTTP.   In this case,  [ServicebusAdministrationClientOptions](https://learn.microsoft.com/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclientoptions?view=azure-dotnet) is the type that you'd set them on and pass when creating your `ServiceBusAdministrationClient`.
