### ISSUE TITLE
[BUG] Different CultureInfo can cause wrong URL query in AppendQueryDelimited() in RequestUriBuilderExtensions.cs

### ISSUE THREAD

**Issue by dubiety** [Azure/azure-sdk-for-net#35431]
### Library name and version

Azure.Core latest

### Describe the bug

Recently, we were reported a bug that our query is malformed in [uri.AppendQueryDelimited() function](https://github.com/Azure/azure-sdk-for-net/blob/b4c0695df67dc44c7186076ca6d51e37d1951199/sdk/maps/Azure.Maps.Routing/src/Generated/RouteRestClient.cs#L2213)

After digging deeper, it seems our [AppendQueryDelimited() in RequestUriBuilderExtensions.cs](https://github.com/Azure/autorest.csharp/blob/d861699cd0355fdc0f0f8d646740b97893d93910/src/assets/Generator.Shared/RequestUriBuilderExtensions.cs#L4) should also applies `value.ToString(TypeFormatters.DefaultNumberFormat, CultureInfo.InvariantCulture)` to value otherwise, some culture will incorrectly delimit comma for specific region users.

The original discussion thread: https://learn.microsoft.com/en-us/answers/questions/1193753/azure-maps-routerange-api-invalid-coordinates-or-o?page=1&orderby=Helpful&comment=answer-1193064#newest-answer-comment

An example code snippet looks like below:
```csharp
using Azure;
using Azure.Maps.Routing;
using Azure.Maps.Routing.Models;
using System.Globalization;
using System.Text.Json;

namespace Program
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // Comment out the line below to repro the correct scenario
            Thread.CurrentThread.CurrentCulture = new CultureInfo("fr-FR");
            var credential = new AzureKeyCredential("<Azure Maps Credential>");
            var _routeClient = new MapsRoutingClient(credential);

            var options = new RouteRangeOptions(10.752276, 45.521535)
            {
                TimeBudget = new TimeSpan(0, 100, 0)
            };

            try
            {
                //Using the options and the route client, get route range result and serialize it as JSON.

                Response<RouteRangeResult> result = _routeClient.GetRouteRange(options);
                //Write the result to the console as JSON.
                Console.WriteLine("Route Range Result:");
                Console.WriteLine(JsonSerializer.Serialize(result.Value));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
        }
    }
}
```

Note: To make the program runnable, please install `Azure.Maps.Routing` nuget package:

```powershell
dotnet add package Azure.Maps.Routing --prerelease
```

Note 2: Create an Azure Maps account and replace line 15 `"<Azure Maps Credential>"` to your Azure Maps credential. See the instruction in the [C# Developer Guide](https://learn.microsoft.com/en-us/azure/azure-maps/how-to-dev-guide-csharp-sdk#using-a-subscription-key-credential)

### Expected behavior

A json that contains some map route result like:

```json
{
  "FormatVersion":"0.0.1",
  "ReachableRange": { ... } 
}
```

### Actual behavior

It will return 400 error code and shows:

```json
{
  "error":
  {
    "code":"400 BadRequest",
    "message":"The provided coordinates in query are invalid, out of range, or not in the expected format"
  }
}
```

### Reproduction Steps

Comment line 15: `Thread.CurrentThread.CurrentCulture = new CultureInfo("fr-FR");` to see the correct behavior.
Uncomment line 15 will show error (400 error code)

### Environment

dotnet 6.0 (or above)
IDE: Visual Studio Code (or Visual Studio)

**Comment by annelo-msft** [comment]
I'm able to repro this locally (using CultureInfo("fr-FR") first, my local culture second):

```diff
- GET https://atlas.microsoft.com/route/range/json?api-version=1.0&query=45%2C521535%2C10%2C752276&timeBudgetInSec=6000 HTTP/1.1
+ GET https://atlas.microsoft.com/route/range/json?api-version=1.0&query=45.521535%2C10.752276&timeBudgetInSec=6000 HTTP/1.1
```

**Comment by annelo-msft** [comment]
I agree with @ArcturusZhang that it would make sense to add overloads to AppendQueryDelimited() in RequestUriBuilderExtensions that take IEnumerable<> of the different number types we have AppendQuery() methods for, and call value.ToString(..., CultureInfo.InvariantCulture) on them prior to joining the values.  It looks like this was missed in [this PR](https://github.com/Azure/autorest.csharp/blob/feature/v3/src/assets/Generator.Shared/RawRequestUriBuilder.cs).
 
It would also be good to cost what it would take to move these extensions into Core (i.e. to put them on RequestUriBuilder directly), and consider addressing https://github.com/Azure/azure-sdk-for-net/issues/26534 as part of this work.

**Comment by ArcturusZhang** [comment]
This issue should have been resolved by https://github.com/Azure/autorest.csharp/pull/3311
but the SDK need to release a new version to make the fix to take effect.
@annelo-msft do you know who will take the release work of the new version?

**Comment by dubiety** [comment]
Hi @jsquire  and @annelo-msft , the PR is merged. I'd like to know it is shipped to the latest Core library? Should I release a new version for our SDK? Thank you so much!

**Comment by annelo-msft** [comment]
Hi @dubiety,

This change actually went into the `"Microsoft.Azure.AutoRest.CSharp` library, and not `Azure.Core`.  The latest version referenced by [Packages.Data.props](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/Packages.Data.props#L175) should have the fix, so I believe whenever you release a new version of `Azure.Maps.Routing` it should pick up the change. 
 Please reach out if you find that for some reason the problem has not been fixed!  Once you have confirmed it is resolved, we can close this issue.  

Thanks!

**Comment by dubiety** [comment]
The bug is fixed in [`Azure.Maps.Routing` v1.0.0-beta.2](https://www.nuget.org/packages/Azure.Maps.Routing/1.0.0-beta.2). Close the issue.
