### ISSUE TITLE
[QUERY] Unable to complete Service Bus message

### ISSUE THREAD

**Issue by tapasudenia** [Azure/azure-sdk-for-net#35436]
### Library name and version

Azure.Messaging.ServiceBus 7.13.1

### Query/Question

We are migrating to Azure.Messaging.ServiceBus from Microsoft.Azure.ServiceBus using the guide [here]
(https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md)

Nuget Package - [Azure.Messaging.ServiceBus 7.13.1](https://www.nuget.org/packages/Azure.Messaging.ServiceBus)
dotnet version on the project - 6.0

However, we are seeing the below error happening all the time, when we are trying to `_serviceBusReceiver.CompleteMessageAsync(serviceBusReceivedMessage);`.

We want to complete the message in all the scenarios whether it fails or it doesn't fail, that is why we have the CompleteMessageAsync in the `finally` block.

Things already tried.
 - Set the `ServiceBusSessionReceiverOptions ` explicitly.
 - Tried using `await receiver.ReceiveMessageAsync();` instead of `await processor.StartProcessingAsync();` to start message processing. However, the later one didn't work / receive message at all. 
 - Tried changing MaxAutoLockRenewalDuration to different values, but the message gets processed within few minutes, so it should complete the lock
 

Please suggest

**Sample Code:**
```csharp
private async Task Subscribe()
{
  try
  {
      var serviceBusConnectionString = $"some-valid-connection-string";
      var _serviceBusClient = new ServiceBusClient(serviceBusConnectionString);

      var receiverOptions = new ServiceBusReceiverOptions
      {
          ReceiveMode = ServiceBusReceiveMode.PeekLock,
          
      };
      _serviceBusReceiver = _serviceBusClient.CreateReceiver("some-valid-queue-name", receiverOptions);
      var options = new ServiceBusProcessorOptions
      {
          MaxAutoLockRenewalDuration = TimeSpan.FromMinutes(60),
          AutoCompleteMessages = false,
          MaxConcurrentCalls = 10,  
          ReceiveMode = ServiceBusReceiveMode.PeekLock
      };

      // create a processor that we can use to process the messages
      _serviceBusProcessor = _serviceBusClient.CreateProcessor("some-valid-queue-name", options);
      _serviceBusProcessor.ProcessErrorAsync += Processor_ProcessErrorAsync;
      _serviceBusProcessor.ProcessMessageAsync += Processor_ProcessMessageAsync;

      await _serviceBusProcessor.StartProcessingAsync();
  }
  catch (Exception ex)
  {
      _logger.Error(ex, "Subscribe to service bus Failed.");
      throw;
  }
}
private async Task Processor_ProcessMessageAsync(ProcessMessageEventArgs arg)
{
    try
    {
       // Some business logic to process the message            
    }
    catch (Exception e)
    {
        _logger.Error(e);
    }
    finally
    {
        await CompleteLock(arg.Message);
    }
}

 private async Task Processor_ProcessErrorAsync(ProcessErrorEventArgs arg)
 {
         _logger.Error(arg.Exception, "Service Bus Messaging Exception");
 }

private async Task CompleteLock(ServiceBusReceivedMessage serviceBusReceivedMessage)
{
    try
    {
        if (!_serviceBusReceiver.IsClosed)
        {
            await _serviceBusReceiver.CompleteMessageAsync(serviceBusReceivedMessage);
            _logger.Info("Completed lock");
        }
        else
        {
            _logger.Info("Could not complete the lock because the MessageReceiver is closing");
        }
    }
    catch (Exception e)
    {
        _logger.Error(e, "Failed to complete lock");
        throw;
    }
}
```
**ERROR**
`ERROR Failed to complete lock with Exception Azure.Messaging.ServiceBus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance. (MessageLockLost). For troubleshooting information, see https://aka.ms/azsdk/net/servicebus/exceptions/troubleshoot.
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ThrowLockLostException()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.DisposeMessageAsync(Guid lockToken, Outcome outcome, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteInternalAsync(Guid lockToken, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<CompleteAsync>b__47_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__22`1.<<RunOperation>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logTimeoutRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteAsync(Guid lockToken, CancellationToken cancellationToken)`

### Environment

Hosting Platform
```
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
```

IDE - Visual Studio 17.1.3

**Comment by jsquire** [comment]
Hi @tapasudenia.  Thank you for reaching out and we regret that you're experiencing difficulties.   You're encountering this error because you're attempting to complete a message using a different receiver than the one that read the message.  When using the processor, to explicitly settle a message, you would use the `ProcessEventArgs` instance that the handler was invoked with to settle.  In this case, by calling:

```csharp
await args.CompleteMessageAsync(args.Message);
```

More information can be found in [Using the Processor](https://learn.microsoft.com/dotnet/api/overview/azure/messaging.servicebus-readme?view=azure-dotnet#using-the-processor) or in the [Receiving messages](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/MigrationGuide.md#receiving-messages) section of the migration guide.   I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
