### ISSUE TITLE
[QUERY] When processing a message, how can I "just do nothing" with it - causing it to run into the lock timeout later?

### ISSUE THREAD

**Issue by rh78** [Azure/azure-sdk-for-net#35432]
### Library name and version

Azure.Messaging.ServiceBus 7.12.0

### Query/Question

In former times (older SDKs), when we wanted a Service Bus message to be just rescheduled later (but not immediately), we just did not perform any action on the message, but just stopped handling it.

The effect was that the message was not rescheduled until the lock timeout expired.

This avoided an overload of our infrastructure because of messages that would immediately be rescheduled as soon as we abandon them.

Is there still a way to do something like that?

### Environment

.NET Core 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
You can do the same thing with the new library - doing nothing with the message will eventually result in the lock expiring after the lock duration has passed. The one caveat is that if you are using the `ServiceBusProcessor`, the lock will be automatically renewed by default for 5 minutes. This can be configured via the [MaxAutoLockRenewalDuration](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusprocessoroptions.maxautolockrenewalduration?view=azure-dotnet#azure-messaging-servicebus-servicebusprocessoroptions-maxautolockrenewalduration) property of `ServiceBusProcessorOptions`.

**Comment by rh78** [comment]
Hello - a few remarks/questions:

1) so the lock is also renewed, if we just return from the handler, without doing anything?
2) also, in the source code of the library I see that if a message hasnt been handled in the handler, you abandon it. So this contradicts your statement
3) does this also apply to sessions? As far as I interpret the session logic, this will not work for sessions, as session locks are based on a different kind of logic, right?

**Comment by JoshLove-msft** [comment]
1. Lock renewal stops once the handler returns
2. Messages are only abandoned if an exception occurs during processing. If no exception occurs, and [AutoCompleteMessages](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusprocessoroptions.autocompletemessages?view=azure-dotnet) is false, then the message is not abandoned or completed.
3. When using sessions, the current session will be closed when no new messages are received from that session for the time configured in [SessionIdleTimeout](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebussessionprocessoroptions.sessionidletimeout?view=azure-dotnet), or when the session lock expires - whichever occurs first.

**Comment by rh78** [comment]
Ad 1 and 2) Ah great - I see now that it is controlled by "AutoCompleteMessages" - so actually the behavior is compatible to the old library - thank you so much!

Ad 3) The thing is, that if I receive a message in a session, then do nothing with it, and then again query the messages, the message will immediately be dispatched to me again - my estimation is, that the session lock is scoped to the connection ID of my client, and that's the reason why I will read it again immediately. Is there a way to disconnect/reconnect (new connection ID) so I can avoid getting the message again immediately (by "abusing" the session lock)?

**Comment by JoshLove-msft** [comment]
You shouldn't get the session message back again immediately provided that the session link remains open. You would get it back immediately if the session link closes and then reopens.

**Comment by rh78** [comment]
OK thank you very much for your help. I appreciate the speed and quality of your support! Thanks!
