### ISSUE TITLE
enableLogAccessUsingOnlyResourcePermissions is a boolean, but docs give 3 options

### ISSUE THREAD

**Issue by kewalaka** [Azure/azure-sdk-for-net#35442]
The type of this flag is a bool, but the documentation says:

```"Flag that indicate which permission to use - resource or workspace or both."```

I ***think*** the correct two options that are being referred to are:
- workspace permissions only
- workspace & resource permissions

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 974b72d0-2f8c-5aed-0b8f-d0bc3002162b
* Version Independent ID: 37578e8a-0010-0c99-2607-c9de1c4cf8db
* Content: [WorkspaceFeatures.EnableLogAccessUsingOnlyResourcePermissions Property (Azure.ResourceManager.OperationalInsights.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.operationalinsights.models.workspacefeatures.enablelogaccessusingonlyresourcepermissions?view=azure-dotnet-preview)
* Content Source: [xml/Azure.ResourceManager.OperationalInsights.Models/WorkspaceFeatures.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.OperationalInsights.Models/WorkspaceFeatures.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
The swagger spec defines this property as `boolean` type, need service team to confirm why the description is different with the property definition.
