### ISSUE TITLE
[QUERY] Can I assigning Billing Account Roles/perform Billing Account Scoped operations?

### ISSUE THREAD

**Issue by ctraftoncodes** [Azure/azure-sdk-for-net#35454]
### Library name and version

Azure.ResourceManager.Billing 1.0.1

### Query/Question

Hello,

I wanted to ask if Azure Billing Account scoped operations are available in the SDK? As an example, I would like to assign a role scoped to a billing account in Azure, I would use the following REST API endpoint:

`POST https://management.azure.com/providers/Microsoft.Billing/billingAccounts/{billingAccountName}/createBillingRoleAssignment?api-version=2019-10-01-preview`

However, upon inspection of the SDK, I did not find any BillingAccount scoped operations - but rather BillingSubscription, AccountPaymentMethod, etc. 

My questions are as follows:

**Do I have the correct SDK for these operations?**
**If the previous answer is yes, is this intentionally not in the API or will be it be sometime in the future?**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @ctraftoncodes , Thank you for using Azure SDK for .NET.
This is a feature belong to Preview API, not included in our current SDK. You could fired an issue in [this repo](https://github.com/Azure/azure-rest-api-specs) to request this feature.
