### ISSUE TITLE
[FEATURE REQ] Value of attribute deployment.environment is not being sent to app insights

### ISSUE THREAD

**Issue by nicolaslattuada** [Azure/azure-sdk-for-net#35487]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter version 1.0.0-beta.9

### Query/Question

Hello
We use open telemetry with app insights, and we would like to use the deployment.environment property in order to discriminate between our environments, and not mix metrics reported by production and test environments.

We use the following code in open telemetry: 
```
                .AddAttributes(new Dictionary<string, object>() { { "deployment.environment", "ppe or prod" } });
```
But unfortunately in the app insights customMetrics table we cannot find this value anywhere.

Please can you advise on what would be the recommended approach in that case?

**Comment by nicolaslattuada** [comment]
Ideally I would like to have the exporter library passing this value in the map of customDimensions in app insights

**Comment by navba-MSFT** [comment]
@nicolaslattuada Thanks for getting back. You can configure global tags using the [ResourceBuilder ](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Resources/ResourceBuilderExtensions.cs)object. The ResourceBuilder allows you to create a Resource object that represents the entity producing telemetry data. You can add attributes to the Resource object to represent global tags that apply to all telemetry data produced by the entity.

[Here's ](https://opentelemetry.io/docs/instrumentation/net/resources/#adding-resources-in-code)an example of how to create a Resource object with global tags. Hope this answers.

**Comment by nicolaslattuada** [comment]
yes, this is what we are doing, but my point is the values we set in attributes are not being saved in app insights.
Please re-read my initial question.

**Comment by nicolaslattuada** [comment]
And I think this should be added to the AzureMonitorMetricExporter library

**Comment by navba-MSFT** [comment]
@nicolaslattuada Thanks for clarifying the ask. I am adding the Service team to look into this further.

**Comment by navba-MSFT** [comment]
@cijothomas @reyang @rajkumar-rangaraj @TimothyMothra @vishweshbankwar Could you please look into this once you get a chance ? Thanks in advance.

**Comment by nicolaslattuada** [comment]
Hi ! any update on this?
Thanks

**Comment by cakescience** [comment]
In fact the issue seems to be for all attributes, not only `deployment.environment`. Any news?

**Comment by cakescience** [comment]
The issue comes from the exporter that creates an instance of `AzureMonitorResource` from the `OpenTelemetry.Resources.Resource`. `AzureMonitorResource` contains only the role name and the role instance. All other attributes are ignored.

https://github.com/Azure/azure-sdk-for-net/blob/460363f233c128f02bd2748eaabac9e90ad56c02/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/AzureMonitorTraceExporter.cs#L31

https://github.com/Azure/azure-sdk-for-net/blob/460363f233c128f02bd2748eaabac9e90ad56c02/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/ResourceExtensions.cs#L14-L42

(It's the same for `AzureMonitorLogExporter` and `AzureMonitorMetricExporter`)

In my opinion, `AzureMonitorResource` should also contain the rest of the attributes from the `OpenTelemetry.Resources.Resource` (with, maybe, a filter as I don't know if all attributes should be included by default).

cc @cijothomas @reyang @rajkumar-rangaraj @TimothyMothra @vishweshbankwar

**Comment by nicolaslattuada** [comment]
hi @cakescience !
at this point if you have located where the passing of the values happens, how about going ahead and sending a pull request? and add the values we need :)

**Comment by cakescience** [comment]
The goal is not to solve your specific case by adding the attributes that interest you. We need to think about a global solution that takes into account all (with a filter maybe) the attributes that are set at the resource level. We can wait for the opinion of someone from Microsoft.

**Comment by treyjones-ms** [comment]
Just submitted PR https://github.com/Azure/azure-sdk-for-net/pull/36027 to hopefully address this issue.

**Comment by erichkray** [comment]
@navba-MSFT where are we at with this?  The PR from May 4th is abandoned and closed, can we get an official update so that the Azure Monitor Exporter for .NET sends Resource attributes correctly?

**Comment by TimothyMothra** [comment]
This is on our backlog. 
It was mentioned that there may be a workaround but haven't had time to investigate.

**Comment by erichkray** [comment]
My current workaround is to use a custom Processor.

`
    public class LogResourceProcessor : BaseProcessor<LogRecord>
    {
        readonly Resource? _resource = null;

        public LogResourceProcessor(Resource resource)
        {
            _resource = resource;
        }

        public override void OnEnd(LogRecord logRecord)
        {
            if (logRecord is null)
            {
                return;
            }

            List<KeyValuePair<string, object?>> stateValues = new();
            if (logRecord.StateValues is not null)
            {
                stateValues.AddRange(logRecord.StateValues);                
            }

            if (_resource is not null && _resource.Attributes.Any())
            {
                stateValues.AddRange(_resource.Attributes.ToDictionary(k => k.Key, v=> (object?)v.Value));
                logRecord.StateValues = stateValues;
            }
        }
    }
`

**Comment by LevYas** [comment]
@TimothyMothra Are there any news? It's a pity that custom attributes are getting lost

**Comment by TimothyMothra** [comment]
No update. The bulk of our feedback has been regarding Resource Attributes. We're still discussing this internally to solve it for all languages.

cc @mattmccleary

**Comment by shuowpro** [comment]
Any update on this? we can get around with the processor with log and trace, but there is no such way in metrics.

**Comment by TimothyMothra** [comment]
I'm consolidating all issues regarding exporting custom Resource Attributes into another issue to help with tracking. https://github.com/Azure/azure-sdk-for-net/issues/46020
