### ISSUE TITLE
[FEATURE REQ] Use full Resource ID for Alerts management

### ISSUE THREAD

**Issue by lukasbrun** [Azure/azure-sdk-for-net#35486]
### Library name

Azure.ResourceManager.AlertsManagement

### Please describe the feature.

If a ServiceAlertResource is created with a Resource ID which is not scoped to the subscription, but to a single resource or resource group, this Resource ID should be used in the API calls.
Example of such a Resource ID scoped to the resource group:
```
/subscriptions/<the-subscription-id>/resourcegroups/<the-resource-group-name>/providers/Microsoft.AlertsManagement/alerts/<alert-id>
```
This allows programmatic alerts management when the alert management permissions are not assigned on a subscription level.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @lukasbrun , thank you for using Azure SDK for .NET.
Our sdk is auto generated from service RestAPI, which is not allow resourcegroup level alert management.
Current version: https://github.com/Azure/azure-rest-api-specs/blob/a3089b2764df11b10a8a43e2a5a33dbe4d3653ca/specification/alertsmanagement/resource-manager/Microsoft.AlertsManagement/preview/2019-05-05-preview/AlertsManagement.json#L102
