### ISSUE TITLE
[QUERY] What management library do I use to read cost management data?

### ISSUE THREAD

**Issue by xStin** [Azure/azure-sdk-for-net#35495]
### Library name and version

Azure.ResourceManager 1.4.0

### Query/Question

Hi
I can't find how I can get resource cost usage for specified date. Is this possible? Something like "cost management (preview)" on portal

### Environment

.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 Visual Studio 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@xStin is this https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.consumption?view=azure-dotnet good for you?

**Comment by ArthurMa1978** [comment]
@xStin looks like Azure.ResourceManager.Consumption is not good for you, the cost management is another service which provides the functionalities that you need, will release this [soon](https://github.com/Azure/azure-sdk-for-net/issues/35656).
