### ISSUE TITLE
[QUERY] How can the OpenAI client be customized?

### ISSUE THREAD

**Issue by dluc** [Azure/azure-sdk-for-net#35506]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.5

### Query/Question

I'm using the OpenAI client to use both OpenAI and Azure OpenAI. I need to inject some custom logic in the HTTP pipeline, e.g. extra headers, logging, and retry logic.

For instance OpenAI authentication requires passing an Organization ID header when using an account that belongs to multiple organizations, see https://platform.openai.com/docs/api-reference/introduction

What's the recommended solution for injecting custom HTTP clients and/or handlers?

This code seems to be hardcoded and possibly blocking customizations. Is there some option?

> _pipeline = HttpPipelineBuilder.Build(options, Array.Empty<HttpPipelinePolicy>(), new HttpPipelinePolicy[] { new AzureKeyCredentialPolicy(_keyCredential, AuthorizationHeader) }, new ResponseClassifier());

### Environment

.NET 7

**Comment by jsquire** [comment]
Hi @dluc.  Thank you for reaching out and we regret that you're having difficulty.    For discoverability, I'm reflecting a summary of our chat discussion here.   We'd appreciate understanding more about your end-to-end scenario, which would allow us to offer more specific guidance and suggestions for how to achieve it using the Azure SDK packages.

**Organization Id**

I don't have insight on this.   I'll ask that @joseharriaga take point there and redirect as needed.

**Custom HTTP Handlers**

It is possible to inject a custom `HttpClient` or handler.   This is done by configuring the [Transport](https://learn.microsoft.com/dotnet/api/azure.core.clientoptions.transport?view=azure-dotnet#azure-core-clientoptions-transport)  property of the client options.   An example can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#user-provided-httpclient-instance).
 
**Forwarding logs to `ILogger`**

All of the Azure SDK packages log via ETW, as discussed [here](https://learn.microsoft.com/en-us/dotnet/azure/sdk/logging).   To integrate with `ILogger`, those events must be listened to and forwarded.  The `Microsoft.Extensions.Azure` package includes the [AzureEventSourceLogForwarder](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.azure.azureeventsourcelogforwarder?view=azure-dotnet) to make this easier.  Details and examples for its use are included in the article that I linked.
 
**Retries**

All of the Azure SDK clients retry implicitly; there is no need for applications to handle retries.  Customization options for retry policies/strategies are discussed [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Configuration.md#azure-client-configuration-samples).

**Comment by joseharriaga** [comment]
As of version 1.0.0-beta.5, the Azure OpenAI client library does not have a direct way to pass an organization ID via the `OpenAI-Organization` header parameter, but you can create a custom pipeline policy to manually add this header as described in this sample:
🔗 [azure-sdk-for-net/Pipeline.md at main · Azure/azure-sdk-for-net (github.com)](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Pipeline.md#implementing-a-synchronous-policy)

**Comment by joseharriaga** [comment]
I'm closing this issue, but please feel free to re-open it if you have any follow-up questions. Thank you!
