### ISSUE TITLE
[BUG] extensibility for Azure.Messaging.ServiceBus 7.13.1 not working

### ISSUE THREAD

**Issue by marcdieters** [Azure/azure-sdk-for-net#35510]
### Library name and version

Azure.Messaging.ServiceBus 7.13.1

### Describe the bug

When trying to implement extensibility as described here https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample09_Extensibility.md I get the following error

![image](https://user-images.githubusercontent.com/24914093/231365451-d558d560-8c35-44a0-ac53-0491445fc4e6.png)

Error	CS0507	'PluginSessionProcessor.OnProcessSessionMessageAsync(ProcessSessionMessageEventArgs)': cannot change access modifiers when overriding 'protected internal' inherited member 'ServiceBusSessionProcessor.OnProcessSessionMessageAsync(ProcessSessionMessageEventArgs)'

When removing 'internal' the error goes away but messages are not delivered to the handler.

### Expected behavior

When sending a message to the queue, the expected behaviour is that messages arrive int the overriden ProcessMessageAsync handler.

### Actual behavior

The message resides in the queue and is not delivered

### Reproduction Steps

Following the steps in the above mentioned article will result in the described error.
I tried PluginSessionProcessor and Pluginrocessor.

I tried this in .NET 6 and .NET 7

### Environment

**Hosting platform**
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.20348
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.4
  Architecture: x64
  Commit:       0a396acafe

.NET SDKs installed:
  7.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Visual Studio**
Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.5.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
The issue here is that this sample is part of a project that has visibility into the Service Bus library internal methods via the InternalsVisibleTo attribute. Because of this, we had to define the methods in your screenshot as `protected internal` rather than just `protected`. When you try to run the sample in your own project, you won't have the same access to internal methods so you would just define the methods as `protected`. I will look into fixing up the samples so that they more accurately reflect the recommended usage.
