### ISSUE TITLE
Please consistently support .WithExistingXXX(*string resourceId*)

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#3552]
Some Fluent APIs only give you a single overload of WithExistingXXX, such as the WithExistingSubnet(INetwork network, string subnetName) for defining ILoadBalancer private frontend which requires you to pass an INetwork object. Could these 'WithExisting' please be consistently implemented with an overload that works with just the resource ID?

```
loadBalancerDefWithFrontEnd = loadBalancerDefBlank
                        .DefinePrivateFrontend("frontend")
                        .WithExistingSubnet(vnet, subnetName)
                        .WithPrivateIPAddressStatic(StaticIP)
                        .Attach();
```

Not only is it sometimes simpler to implement with a resourceId string, requiring INetwork causes worse reliability as it requires extra GET calls to ARM to get resource state as the easiest way in order to satisfy these API signatures.

And finally, in some advanced RBAC scenarios, the authentication model required to do GET IFoo and then WithExisting(IFoo) is actually an added difficulty, because 'foo' another subscription. In the worst case you might even *fail* authentication on the GET even though the PUT request could in theory succeed (due to specific RBAC permissions granted you)!

(BTW this feedback is based on "Microsoft.Azure.Management.Network.Fluent" version="1.1.2")

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#5

**Comment by TimLovellSmith** [comment]
I'm trying out 1.4.1 and looks like there is an overload which fixed this issue now. Hooray and thanks!

                        .WithExistingSubnet(vnet.Id, subnetName)
