### ISSUE TITLE
[BUG] Unable to locate System.Text.Json when using the Tables client library

### ISSUE THREAD

**Issue by digitalgym** [Azure/azure-sdk-for-net#35532]
### Library name and version

Azure.Data.Table 12.8.0

### Describe the bug

When trying to Query or Write to a table library throws an exception "Could not load file or assembly 'System.Text.Json, Version=4.0.1.2" Binding redirects have no effect, and I have also tried in the fresh core 6 project which just crashes with an access violation message.

The table creates fine but I'm not able to write to it or query it.

### Expected behavior

Able to write an entity to table and query an entity

### Actual behavior

exception "Could not load file or assembly 'System.Text.Json, Version=4.0.1.2" in a fresh core 6 project fails with an access violation message.

### Reproduction Steps

var cloudStorageAccount = new TableServiceClient(...);
var tableClient = new TableClient("...", "...");
tableClient.CreateIfNotExists();
tableClient.AddEntity(new SuburbMapping("...", "..."));

### Environment

.Net 4.8 and Core 6.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
