### ISSUE TITLE
Release Azure.ResourceManager.CostManagement first beta

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#35543]
Need check with service team if still need SDK for .Net

**Comment by ArthurMa1978** [comment]
Blocked by https://github.com/Azure/azure-rest-api-specs/issues/23704

**Comment by dvbb** [comment]
Release PR: [[CostManagement] Release beta version](https://github.com/Azure/azure-sdk-for-net/pull/35629)

**Comment by ArthurMa1978** [comment]
https://www.nuget.org/packages/Azure.ResourceManager.CostManagement/
