### ISSUE TITLE
Azure Open Telemetry - Application map drawn incorrectly

### ISSUE THREAD

**Issue by tinuverma** [Azure/azure-sdk-for-net#35559]
I initially opened issue below and that is fixed 
https://github.com/dotnet/runtime/discussions/83904

I now have another issue where the application map is being drawn incorrectly.
@tarekgh did look at it and confirmed the console logs look right.
Can someone please tell me why the map is not what I expected it to be?
Here is the sample console log

I want the hierarchy to be “backend” --> “Handle pr…e message” --> “Process person” (for each person in the message)
instead its showing up as 
“backend” --> “Handle pr…e message” 
“backend”  --> “Process person” (for each person in the message)

Activity.TraceId:          767228783960c83ed6302b9f3e97a29e
Activity.SpanId:           765c4e557c220475
Activity.TraceFlags:           Recorded
Activity.ParentSpanId:    b8985373b34f3dd6
Activity.ActivitySourceName: ProductAgreementRecordChangeHandler
Activity.DisplayName: process person
Activity.Kind:        Client
Activity.StartTime:   2023-04-12T21:01:56.2972091Z
Activity.Duration:    00:00:03.7227704
Activity.Tags:
    UniqueGuid: 99964015
    mainframeRecord found: true
    CustomerNumber: 2761221
Activity.Events:
    Call Xref start for party 99964015 [4/12/2023 9:01:56 PM +00:00]
    Call Xref end for party 99964015 [4/12/2023 9:01:59 PM +00:00]
Activity.Links:
    767228783960c83ed6302b9f3e97a29e b8985373b34f3dd6
Activity.TraceId:          767228783960c83ed6302b9f3e97a29e
Activity.SpanId:           b8985373b34f3dd6
Activity.TraceFlags:           Recorded
Activity.ActivitySourceName: ProductAgreementRecordChangeHandler
Activity.DisplayName: Handle ProductAgreementRecordChange message
Activity.Kind:        Internal
Activity.StartTime:   2023-04-12T21:01:56.2732094Z
Activity.Duration:    00:00:03.7677687
Activity.Tags:
    CertificatePolicyNumber: 12345
    SourceSystemUniqueId: 01276122102
Resource associated with Activity:
    service.name: Afc.CustomerCommunication.Backend
    service.version: 1.0.0
    service.instance.id: beb158f9-4552-4fc8-b3af-d026c880677c

**Comment by tarekgh** [comment]
CC @reyang

**Comment by tinuverma** [comment]
@reyang  sending you detailed email since I am unable to upload application map screen shot here.

**Comment by vishweshbankwar** [comment]
@tinuverma Could you share a repro app that shows this issue? It would help in understanding how you are creating the activities.

**Comment by vishweshbankwar** [comment]
Thanks! - I looked at https://github.com/dotnet/runtime/discussions/83904 and it helped clarifying the issue.

@tinuverma AppMap is a map of service connections. As per your [sample](https://github.com/dotnet/runtime/discussions/83904#discussioncomment-5468135)  here is the expected result:

1) Handle pr…e message is internal activity (This should not show up in AppMap as it is an internal operation)
2) Process Person is Client activity (This should show up in AppMap like Backend --> "Process Person")

If you check this operation in Transaction Details(End-to-End view), parent-child relationship should show up correctly ). Let me know if this is not showing correctly.


In regards to your following point

`I want the hierarchy to be “backend” --> “Handle pr…e message” --> “Process person” (for each person in the message)
instead its showing up as
“backend” --> “Handle pr…e message”
“backend” --> “Process person” (for each person in the message)`

Could you please confirm if the activity kinds are different than the ones showed [here](https://github.com/dotnet/runtime/discussions/83904#discussioncomment-5468135) for “Handle pr…e message” and “Process person”. I tried to repro this and one possible scenario is that both the activities are of type `Client`. 
Could you please confirm if that is the case?

**Comment by tinuverma** [comment]
@vishweshbankwar  the activity kind for "Handle .." is  internal and for "process person.." is Client.
I do see the relationships fine in  Transaction Details (End to End view).
I have another question...why is my "ActivityEvent" not showing up? This is how it's linked


```
                    using (var processPartyActivity = activitySource?.StartActivity("process person", ActivityKind.Client, linkedContext.Value, tags: null, links))
                    {
                        Log.Information("Process start party with GR_SSUID {GR_SSUID}", gr_ssuid);
                        processPartyActivity?.AddTag("GoldenRecordSourceSystemUniqueId", gr_ssuid);
                        processPartyActivity?.AddEvent(new ActivityEvent($"Call Xref start for party {gr_ssuid}"));
                      < more code ...>
                      }

```

**Comment by tinuverma** [comment]
Closed by mistake. Reopened it. @vishweshbankwar

**Comment by vishweshbankwar** [comment]
@tinuverma Please check https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/CHANGELOG.md#:~:text=Activity%20Events%20(SpanEvents)%2C%20except%20those%20representing%20Exception%2C%20will%20be%20exported%20to%20TraceTelemetry%20table%20(%2332980)%20Exceptions%20reported%20via%20ActivityEvents%20will%20continue%20to%20be%20exported%20to%20ExceptionTelemetry%20table
