### ISSUE TITLE
Vague description of `TargetResourceGroup` property

### ISSUE THREAD

**Issue by tom-puckett** [Azure/azure-sdk-for-net#35550]
[Enter feedback here]
Please include mention of how the target resource group is to be identified.  Is this the resource group name or ID? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ad60041-54f5-d46e-82be-33f451b6593c
* Version Independent ID: 2bc1e194-41a3-53b0-cd92-5f5983e3bccd
* Content: [ResourcesMoveContent.TargetResourceGroup Property (Azure.ResourceManager.Resources.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.resources.models.resourcesmovecontent.targetresourcegroup?view=azure-dotnet#azure-resourcemanager-resources-models-resourcesmovecontent-targetresourcegroup)
* Content Source: [xml/Azure.ResourceManager.Resources.Models/ResourcesMoveContent.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.Resources.Models/ResourcesMoveContent.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
From the description of this operation (for instance here: https://github.com/Azure/azure-rest-api-specs/blob/06042d4ffed6a1ea8319c39cd07ea21efe5d49f7/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json#L2835) the target resource group must be in another subscription, therefore despite there is no description on this property nor anything on this operation mentioned this, it should be an arm resource id of the resource group. We will follow up on this to get confirmation, and if we confirm this is an arm resource id, we will introduce a new property with the type of `ResourceIdentifier` to replace this old property to emphasize.

**Comment by ArcturusZhang** [comment]
I have confirmed that this should be an arm resource id. I will update the SDK accordingly soon
