### ISSUE TITLE
[FEATURE REQ] Configurable Connection timeout for eventhub

### ISSUE THREAD

**Issue by stefanop** [Azure/azure-sdk-for-net#35551]
### Library name

Azure.Messaging.EventHubs 5.8.1

### Please describe the feature.

Due to satellite connection and a congested network channel, we're constantly hitting an eventhub connection timeout limit.
Switching to a better connection is not a viable option.

With current version of EventHub library, there's no way to configure a custom timeout for AMQP connection setup. 
The default timeout is set to 30 seconds, but it's hardwired in property `AmqpConnectionScope.SessionTimeout` 

Manually changing just the parameter to 1 minute and recompiling the Eventhub assembly solved our problem.

Can you please make this parameter user configurable ?

Best regards,
 Stefano

**Comment by jsquire** [comment]
Hi @stefanop.  Thank you for reaching out and we regret that you're experiencing difficulties.  Can you help me understand your end-to-end scenario better?  Specifically, I'd like to see the error message and stack trace that you're running into.

All Event Hubs service operations - including establishing a connection - are intended to be governed by the `TryTimeout` of the retry policy of the client.  You're correct in that we're creating a hard-cap of 30 seconds when opening AMQP links, which I've traced back to behavior from the previous generation that we brought forward - but I honestly have no idea why.   I'm going to try to run that down and will verify with the Event Hubs service team what the impact of removing that cap would be.  

If all goes well, we'll look to either remove the cap being imposed and allow `TryTimeout` to perform its intended role or introduce a new connection option that governs just establishing connections/links.

**Comment by jsquire** [comment]
//fyi: @m-redding

**Comment by jsquire** [comment]
Hi @stefanop.   After looking things over, the 30 second cap was a mistake carried forward from the previous generation library which is not needed and runs counter to our goal of having a single timeout govern each service operation end-to-end.  We've decided to remove that 30 second cap, which will allow the retry policy's `TryTimeout` to take over.   In your scenario, if you need more than the default 60 seconds, you can extend the timeout using the `RetryOptions` when creating the client.   An example can be found [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample02_EventHubsClients.md#configuring-the-client-retry-thresholds).

The change will go out with our next release, tentatively scheduled for the second week of May.   Thanks for bringing this to our attention.   I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
