### ISSUE TITLE
[QUERY] outgoing messages higher than incoming

### ISSUE THREAD

**Issue by adeliab** [Azure/azure-sdk-for-net#35573]
### Library name and version

Azure.Messaging.EventHubs.Processor 5.9.0

### Query/Question

I have an xunit application test that publishes 5 values to event hub when executed and received those 5 events. The event hub has 1 partition with the $Default consumer group.

In the metric I see the nr of outgoing messages is higher than incoming. I expect 5 incoming and 5 outgoing in each test run. But the nr of outgoing message seems to increment by 5 every time.
![image](https://user-images.githubusercontent.com/7829826/231951482-4a719f3a-db92-409e-bc3f-ffe68891ebcd.png)

I called the UpdateCheckpointAsync method in event processing and saw that the checkpoint properties are updated in the storage. Below is the code. I've put a breakpoint in the EventHubProcessor_ProcessEventAsync and it's only hit 5 times. Where do the rest of outgoing messages go to? Is there a way to get the number the same.

```
var processor = new EventProcessorClient(storageClient, EventHubConsumerClient.DefaultConsumerGroupName, eventHubConnectionString, new EventProcessorClientOptions { Identifier = "myapplicationtest"  });
processor.ProcessEventAsync += this.EventHubProcessor_ProcessEventAsync;
processor.ProcessErrorAsync += this.EventHubProcessor_ProcessErrorAsync;
await processor.StartProcessingAsync();
await Task.Delay(TimeSpan.FromSeconds(15)); // wait for the events to be processed
try
{
    await processor.StopProcessingAsync();
}
finally
{
    // To prevent leaks, the handlers should be removed when processing is complete.
    processor.ProcessEventAsync -= EventHubProcessor_ProcessEventAsync;
    processor.ProcessErrorAsync -= EventHubProcessor_ProcessErrorAsync;
}
```

```
private async Task EventHubProcessor_ProcessEventAsync(ProcessEventArgs arg)
{
    var body = Encoding.UTF8.GetString(arg.Data.EventBody);
    try
    {
         var receivedEvents = JsonSerializer.Deserialize<List<ChangeOfValue>>(body);
         allReceivedEvents.AddRange(receivedEvents);
    }
    catch (JsonException)
    {
    }
    finally
    {
        await arg.UpdateCheckpointAsync(arg.CancellationToken);
    }
}
```

### Environment

XUnit 2.4.2
Visual Studio 17.5.2

**Comment by jsquire** [comment]
Hi @adeliab.  Thank you for reaching out and we regret that you're experiencing difficulties.   It is not unusual for the outgoing metrics to show a greater number than the incoming; Event Hubs has an at-least-once guarantee.   Common causes are transient failures that cause an implicit retry, your handler leaking exceptions that cause the partition task to fault and restart, and other readers.

As you've mentioned that your handler is only invoked 5 times, that would rule out errors leaking.  Outside of that, we'd need a slice of [SDK logs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample10_AzureEventSourceListener.md) to offer further insight.   That said, I see no indication that this is anything beyond normal behavior from the client perspective.

Those metrics are not controlled by the Event Hubs client library, nor does it influence them, so I cannot offer insight into how they're computed or what non-client scenarios may cause the drift that you're seeing.  If you're interested in digging into that further, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request), which would engage the service team.

I'm going to mark this as addressed, but please feel free to unresolve if you'd like to continue the discussion.
