### ISSUE TITLE
[BUG] Invalid resource type Microsoft.Storage/storageAccounts/blobServices/containers

### ISSUE THREAD

**Issue by jeromekol** [Azure/azure-sdk-for-net#35583]
### Library name and version

Azure.ResourceManager.Storage 1.1.1

### Describe the bug

We try to fetch a GenericResource for the type BlobContainerResource and provide a proper ResourceIdentifier by using BlobContainerResource.CreateResourceIdentifier. However, when we call Azure.ResourceManager.ArmClient.GetGenericResources().Exists(resourceIdentifier) if throws an InvalidOperationException with the error message: Invalid resource type Microsoft.Storage/storageAccounts/blobServices/containers

### Expected behavior

A proper GenericResource is returned

### Actual behavior

throws InvalidOperationException with the error message: Invalid resource type Microsoft.Storage/storageAccounts/blobServices/containers

### Reproduction Steps

Create a Storage Account and a Blob Container. Try to fetch the GenericResource with a ResourceIdentifier created from BlobContainerResource.CreateResourceIdentifier.

**Comment by blueww** [comment]
@ArthurMa1978 

The error looks is from SDK code, and is on a common API `Azure.ResourceManager.ArmClient.GetGenericResources().Exists(resourceIdentifier)`, do you have any idea?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment]
Hi @jeromekol 

`GenericReource` is from `Azure.ResourceManager.Resources` for operating all resources based on JSON data, here is some [GenericReource usage sample](https://github.com/Azure/azure-sdk-for-net/blob/866fb2c62139d8ff82bbc2303e9a8b2c7974766c/sdk/compute/Azure.ResourceManager.Compute/tests/Scenario/VirtualMachineTestBase.cs#L95) from our internal test code. 

And if you want to operate `BlobContainr`, we suggest using `BlobContainerCollection`, here are some samples hope this helps:
[Sample2_ManagingBlobContainers.md]( https://github.com/Azure/azure-sdk-for-net/blob/866fb2c62139d8ff82bbc2303e9a8b2c7974766c/sdk/storage/Azure.ResourceManager.Storage/samples/Sample2_ManagingBlobContainers.md)
