### ISSUE TITLE
[FormRecognizer] AdminOps(True) failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#35581]
FormRecognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : The request could not be completed due to a conflict with the current state of the target resource.
> Status: 409 (Conflict)
> ErrorCode: Conflict
> 
> Content:
> {
> "error": {
> "code": "Conflict",
> "message": "The request could not be completed due to a conflict with the current state of the target resource.",
> "innererror": {
> "code": "ModelExists",
> "message": "A model with the provided name already exists."
> }
> }
> }
> 
> Headers:
> Transfer-Encoding: chunked
> x-envoy-upstream-service-time: 66
> apim-request-id: 0b86ad30-42ae-4406-a70e-5a83b367ed9b
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> x-ms-region: REDACTED
> Date: Fri, 14 Apr 2023 04:47:32 GMT
> Content-Type: application/json
> 
> 
> Stack trace
>    at Azure.AI.FormRecognizer.DocumentAnalysis.DocumentAnalysisRestClient.DocumentModelsBuildModel(BuildDocumentModelRequest buildRequest, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\src\Generated\DocumentAnalysisRestClient.cs:line 504
>    at Azure.AI.FormRecognizer.DocumentAnalysis.DocumentModelAdministrationClient.BuildDocumentModel(WaitUntil waitUntil, Uri blobContainerUri, DocumentBuildMode buildMode, String modelId, String prefix, BuildDocumentModelOptions options, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\src\DocumentModelAdministrationClient.cs:line 186
>    at InvokeStub_DocumentModelAdministrationClient.BuildDocumentModel(Object, Object, IntPtr*)
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.&lt;&gt;c__DisplayClass4_0`1.&lt;&lt;WrapAsyncResultCore&gt;g__Await|0&gt;d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 120
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.InstrumentResultInterceptor.InstrumentOperationInterceptor[T](IInvocation invocation, Func`1 innerTask) in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\InstrumentResultInterceptor.cs:line 105
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.&lt;&gt;c__DisplayClass4_0`1.&lt;&lt;WrapAsyncResultCore&gt;g__Await|0&gt;d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 120
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.&lt;&gt;c__DisplayClass5_0`1.&lt;&lt;ValidateDiagnosticScopeInterceptor&gt;b__0&gt;d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 171
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 201
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DocumentModelAdministrationClientLiveTests.AdminOps(Boolean useTokenCredential) in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\tests\DocumentModelAdministrationClient\DocumentModelAdministrationClientLiveTests.cs:line 218
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.&lt;&gt;c__DisplayClass1_0.&lt;Execute&gt;b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2701607&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Closing this as we haven't seen this error recently. It was probably a transient issue.
