### ISSUE TITLE
Apply splitting to Azure Monitor metrics query with Azure.Monitor.Query

### ISSUE THREAD

**Issue by szilardd** [Azure/azure-sdk-for-net#35582]
### Library name and version

Azure.Monitor.Query 1.1.0

### Query/Question

Is it possible to do splitting with `Azure.Monitor.Query` SDK when retrieving Monitor metrics?

I'm trying to retrieve metrics for a service bus account, split by EntityName. This is possible in the portal:

![image](https://user-images.githubusercontent.com/968502/231999374-528dede0-b236-40c2-b5c4-ae1b37bf69ce.png)

This is the code that I have. I can retrieve the metrics but don't know how to apply the splitting.

```cs
var credential = new ClientSecretCredential(_tenantId, _clientId, _clientSecret);
var metricsClient = new MetricsQueryClient(credential);
var resourceId = $"/subscriptions/{_subscriptionId}/resourceGroups/{_resourceGroupName}/providers/Microsoft.ServiceBus/namespaces/{_serviceBusName}";
var metrics = new[] { "ScheduledMessages", "ActiveMessages" };

var options = new MetricsQueryOptions();
options.Aggregations.Add(MetricAggregationType.Total);
options.TimeRange = TimeSpan.FromHours(4);

var result = await metricsClient.QueryResourceAsync(resourceId, metrics, options);
```

### Environment

IDE: Visual Studio 17.5.3.

`dotnet --info` results:

```
.NET SDK:
 Version:   7.0.202
 Commit:    6c74320bc3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.202\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17
```

**Comment by blueboxes** [comment]
I am interested in the same thing, is there any update?

**Comment by ToddKingMSFT** [comment]
Good point this should be better documented. Splitting and filtering actually both use the same filter parameter the only difference is splitting is where the filter value is equal to '*'.
So an example of splitting is:
$filter=ApiName eq '*'
An example of filtering is:
$filter=ApiName eq 'GetBlob'

**Comment by scottaddie** [comment]
I'll get this documented in our README file
