### ISSUE TITLE
[QUERY] Bot Resource msappid

### ISSUE THREAD

**Issue by Solender-UK** [Azure/azure-sdk-for-net#35597]
### Library name and version

Azure.ResourceManager.BotService 1.0.1

### Query/Question

Hey,

Apologies if this is the wrong place to ask or whether this has been asked before, but i'm building a web application in .NET 6 (C#) that can on demand create a bunch of resources that you'd normally associate with a Bot Service, blob storage, question answering, analytics etc etc.

Traditionally in the Azure Portal when creating a new bot it would give me the option to generate an app id and secret automatically when the bot service was created, however when i'm trying to create this service via the Azure.ResourceManager.BotService it already seems to expect me to have a msappid and a null input when creating new BotProperties isn't allowed.

I've had a look through this library and the identity library, but cant for the life of me figure out whether there is a specific package I can use to create app registrations and obtain the relevant appid and secret or whether this is something I can just have created as part of the BotResource creation process, I dont suppose anyone can point me in the right direction can they?

This is literally the last piece of the puzzle for my application, everything else seems to work really well so i'd appreciate any assistance I can get!

Kind Regards,
Greg

### Environment

.Net 6, Visual Studio 2022

**Comment by HarveyLink** [comment]
Hi @Solender-UK , Thank you for using Azure SDK for .NET
If you mean this part of creation:
![image](https://github.com/Azure/azure-sdk-for-net/assets/30464227/bfd6f6e7-0846-4725-9976-a4e36f2e1014)
This means you need a SPN for this app, and it will create a new one if you don't provide it.
This function is provided by: https://github.com/microsoftgraph/msgraph-sdk-dotnet. not in our SDK scope, please have a try on that and you should get the app we need.
