### ISSUE TITLE
Is this namespace a bit funky?

### ISSUE THREAD

**Issue by tomgron** [Azure/azure-sdk-for-net#35592]
https://github.com/Azure/azure-sdk-for-net/blame/9623f9a36059a347fa5890ee7f2bf9165e144b62/sdk/identity/Azure.Identity/src/TokenHelper.cs

**Comment by christothes** [comment]
This was [already fixed](https://github.com/Azure/azure-sdk-for-net/blame/main/sdk/identity/Azure.Identity/src/TokenHelper.cs#L8)
