### ISSUE TITLE
Migration from IConfigurationBuilder.AddAzureKeyVault

### ISSUE THREAD

**Issue by bretthacker** [Azure/azure-sdk-for-net#35608]
Please provide information, samples, or a link to assist with migration from IConfigurationBuilder.AddAzureKeyVault to this new model.

**Comment by jsquire** [comment]
Hi @bretthacker.   Can you please help me understand which package you're moving from and which package you're moving to?

**Comment by bretthacker** [comment]
I have implemented Microsoft.Extensions.Configuration.AzrueKeyVaultConfigurationExtensions, currently on v3.1.24. When it throws, I get an error about ADAL and a recommendation to migrate to Azure.Identity. All the samples point to how to directly call a Key Vault; in this Configuration flow, I don't directly call it, the middleware calls it on my behalf to retrieve secrets during app startup. I don't see any samples talking about this.

**Comment by jsquire** [comment]
According to its [NuGet page](https://www.nuget.org/packages/Microsoft.Extensions.Configuration.AzureKeyVault), The `Microsoft.Extensions.Configuration.AzureKeyVault` is deprecated and no longer maintained. 

The suggested replacement is [Azure.Extensions.AspNetCore.Configuration.Secrets](https://www.nuget.org/packages/Azure.Extensions.AspNetCore.Configuration.Secrets), which uses packages from the current generation of the Azure SDK, including `Azure.Identity`.  Documentation for `Azure.Extensions.AspNetCore.Configuration.Secrets`, including a usage example, can be found [here](https://learn.microsoft.com/dotnet/api/overview/azure/extensions.aspnetcore.configuration.secrets-readme?view=azure-dotnet).
