### ISSUE TITLE
[BUG] Azure Storage Queue CreateIfNotExistsAsync hangs indefinitely and never returns

### ISSUE THREAD

**Issue by jetuser** [Azure/azure-sdk-for-net#35611]
### Library name and version

Azure.Storage.Queues 12.14.0

### Describe the bug

I have updated to a more recent version of the package above. And calls to queue.CreateIfNotExistsAsync() are hanging indefinitely. I do not see any outbound calls via fiddler once the call is made and as far as I can tell, nothing is ever transmitted. 

I was able to get to this line in the debugger, after which the code will indefinitely hang until I abort it (this is a test case in visual studio).
` return _pipeline.Span[0].ProcessAsync(message, _pipeline.Slice(1));`
(In HttpPipeline.cs line 141)

I also eventually see an IOException occurring in the host process but I'm not 100% sure its related.

### Expected behavior

Call will immediately return with 200 success and test execution resumes.

### Actual behavior

Test case hangs indefinitely.

### Reproduction Steps

I can reproduce locally on demand but I do not believe it will be trivial to provide a minimal debug case. I am internal to Microsoft so I can provide a walkthrough offline if necessary.

**Comment by navba-MSFT** [comment]
@jetuser Thanks for reaching out to us and reporting this issue. I am unable to reproduce this issue at my end. I was able to create the queue successfully.

```
 using Azure.Storage.Queues;

           // Define the connection string and queue name
            string connectionString = "XXXXXXXXX";
            string queueName = "myqueuedemo";

            // Create an instance of the QueueClient class
            QueueClient queueClient = new QueueClient(connectionString, queueName);

            // Create the queue if it does not exist
            await queueClient.CreateIfNotExistsAsync();

```

Please enable the client side logging with .net storage client library. More Info [here](https://learn.microsoft.com/en-us/rest/api/storageservices/client-side-logging-with-the-.net-storage-client-library).

**Comment by jetuser** [comment]
That pointer unfortunately doesnt work but I was able to attach the azure event source logger and get it to dump everything to a file. The log matches what I am seeing. I am seeing all the keyvault calls occur successfully (I redacted the url) and then there's no further outbound calls to azure storage queues when the call is made.

> Request [d3debe4f-cfb8-4ce1-85e4-313c88252780] GET https://<redacted>/secrets/CosmosDbTableAuthKey/?api-version=7.4
Content-Type:application/json
Accept:application/json
x-ms-client-request-id:d3debe4f-cfb8-4ce1-85e4-313c88252780
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Secrets/4.5.0 (.NET 6.0.16; Microsoft Windows 10.0.22621)
client assembly: Azure.Security.KeyVault.SecretsError response [d3debe4f-cfb8-4ce1-85e4-313c88252780] 401 Unauthorized (00.3s)
Cache-Control:no-cache
Pragma:no-cache
WWW-Authenticate:Bearer authorization="https://login.microsoftonline.com/975f013f-7f24-47e8-a7d3-abc4752bf346", resource="https://vault.azure.net"
x-ms-keyvault-region:South Central US
x-ms-client-request-id:d3debe4f-cfb8-4ce1-85e4-313c88252780
x-ms-request-id:f7124c1f-c3ec-4c05-9ec5-f0bbb9957dbb
x-ms-keyvault-service-version:1.9.775.1
x-ms-keyvault-network-info:conn_type=Ipv4;addr=131.107.1.184;act_addr_fam=InterNetwork;
X-Content-Type-Options:REDACTED
Strict-Transport-Security:REDACTED
Date:Tue, 18 Apr 2023 05:37:35 GMT
Content-Length:97
Content-Type:application/json; charset=utf-8
Expires:-1
ClientCertificateCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: d3debe4f-cfb8-4ce1-85e4-313c88252780False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:36Z - 0c68649c-564d-45d2-b20b-825039f4fb59] MSAL MSAL.NetCore with assembly version '4.52.0.0'. CorrelationId(0c68649c-564d-45d2-b20b-825039f4fb59)False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:36Z - 0c68649c-564d-45d2-b20b-825039f4fb59] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False
False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:36Z - 0c68649c-564d-45d2-b20b-825039f4fb59] 
=== Request Data ===
Authority Provided? - True
Scopes - https://vault.azure.net/.default
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 0c68649c-564d-45d2-b20b-825039f4fb59
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 
False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:36Z - 0c68649c-564d-45d2-b20b-825039f4fb59] === Token Acquisition (ClientCredentialRequest) started:
	 Scopes: https://vault.azure.net/.default
	Authority Host: login.microsoftonline.comFalse MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:36Z - 0c68649c-564d-45d2-b20b-825039f4fb59] [Instance Discovery] Instance discovery is enabled and will be performedFalse MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:36Z - 0c68649c-564d-45d2-b20b-825039f4fb59] [Region discovery] Not using a regional authority. False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:36Z - 0c68649c-564d-45d2-b20b-825039f4fb59] Fetching instance discovery from the network from host login.microsoftonline.com. Request [6bd5bb5a-17bb-4db2-9882-e4511ec1f459] GET https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=REDACTED
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:6bd5bb5a-17bb-4db2-9882-e4511ec1f459
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.8.2 (.NET 6.0.16; Microsoft Windows 10.0.22621)
client assembly: Azure.IdentityResponse [6bd5bb5a-17bb-4db2-9882-e4511ec1f459] 200 OK (00.4s)
Cache-Control:max-age=86400, private
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Access-Control-Allow-Origin:REDACTED
Access-Control-Allow-Methods:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:81adaf2f-fb9d-4dfe-b438-0ed9eeb10b00
x-ms-ests-server:REDACTED
Content-Security-Policy-Report-Only:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:Tue, 18 Apr 2023 05:37:35 GMT
Content-Type:application/json; charset=utf-8
Content-Length:980
False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:36Z - 0c68649c-564d-45d2-b20b-825039f4fb59] Authority validation enabled? True. False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:36Z - 0c68649c-564d-45d2-b20b-825039f4fb59] Authority validation - is known env? True. Request [4ff3d2bc-10b7-498e-acfd-08e9a586b32e] POST https://login.microsoftonline.com/975f013f-7f24-47e8-a7d3-abc4752bf346/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-CPU:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
Content-Type:application/x-www-form-urlencoded
x-ms-client-request-id:4ff3d2bc-10b7-498e-acfd-08e9a586b32e
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.8.2 (.NET 6.0.16; Microsoft Windows 10.0.22621)
client assembly: Azure.IdentityResponse [4ff3d2bc-10b7-498e-acfd-08e9a586b32e] 200 OK (00.1s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:2f0a3445-4770-4a38-9785-f581c3dffe00
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:Tue, 18 Apr 2023 05:37:36 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:1334
False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59] ScopeSet was missing from the token response, so using developer provided scopes in the result. False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59] Checking client info returned from the server..False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59] Saving token response to cache..False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59] [SaveTokenResponseAsync] ID Token not present in response. False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59] Cannot determine home account id - or id token or no client info and no subject False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59] [SaveTokenResponseAsync] Saving AT in cache and removing overlapping ATs...False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59] Looking for scopes for the authority in the cache which intersect with https://vault.azure.net/.defaultFalse MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59] Intersecting scope entries count - 0False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59] 
	=== Token Acquisition finished successfully:False MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59]  AT expiration time: 4/19/2023 5:37:36 AM +00:00, scopes: https://vault.azure.net/.default. source: IdentityProviderFalse MSAL 4.52.0.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.22621 [2023-04-18 05:37:37Z - 0c68649c-564d-45d2-b20b-825039f4fb59] Fetched access token from host login.microsoftonline.com. ClientCertificateCredential.GetToken succeeded. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: d3debe4f-cfb8-4ce1-85e4-313c88252780 ExpiresOn: 2023-04-19T05:37:36.1206652+00:00Request [d3debe4f-cfb8-4ce1-85e4-313c88252780] GET https://<redacted>/secrets/CosmosDbTableAuthKey/?api-version=7.4
Content-Type:application/json
Accept:application/json
x-ms-client-request-id:d3debe4f-cfb8-4ce1-85e4-313c88252780
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Secrets/4.5.0 (.NET 6.0.16; Microsoft Windows 10.0.22621)
Authorization:REDACTED
client assembly: Azure.Security.KeyVault.SecretsResponse [d3debe4f-cfb8-4ce1-85e4-313c88252780] 200 OK (00.1s)
Cache-Control:no-cache
Pragma:no-cache
x-ms-keyvault-region:South Central US
x-ms-client-request-id:d3debe4f-cfb8-4ce1-85e4-313c88252780
x-ms-request-id:b9a31133-13c7-4070-bb2c-760684b276d5
x-ms-keyvault-service-version:1.9.775.1
x-ms-keyvault-network-info:conn_type=Ipv4;addr=131.107.1.184;act_addr_fam=InterNetwork;
x-ms-keyvault-rbac-assignment-id:REDACTED
x-ms-keyvault-rbac-cache:REDACTED
X-Content-Type-Options:REDACTED
Strict-Transport-Security:REDACTED
Date:Tue, 18 Apr 2023 05:37:36 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:345
Request [fa549ac7-999f-42e7-a36d-a2b070ee8a94] GET https://<redacted>/secrets/StorageAccountConnectionString0/?api-version=7.4
Content-Type:application/json
Accept:application/json
x-ms-client-request-id:fa549ac7-999f-42e7-a36d-a2b070ee8a94
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Secrets/4.5.0 (.NET 6.0.16; Microsoft Windows 10.0.22621)
Authorization:REDACTED
client assembly: Azure.Security.KeyVault.SecretsResponse [fa549ac7-999f-42e7-a36d-a2b070ee8a94] 200 OK (00.1s)
Cache-Control:no-cache
Pragma:no-cache
x-ms-keyvault-region:South Central US
x-ms-client-request-id:fa549ac7-999f-42e7-a36d-a2b070ee8a94
x-ms-request-id:3494741e-6266-41b1-bc88-05f544856a28
x-ms-keyvault-service-version:1.9.775.1
x-ms-keyvault-network-info:conn_type=Ipv4;addr=131.107.1.184;act_addr_fam=InterNetwork;
x-ms-keyvault-rbac-assignment-id:REDACTED
x-ms-keyvault-rbac-cache:REDACTED
X-Content-Type-Options:REDACTED
Strict-Transport-Security:REDACTED
Date:Tue, 18 Apr 2023 05:37:36 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:456
Request [28e8ff7c-b8d9-4e3b-b7d3-780d22232649] GET https://<redacted>/secrets/CosmosDbTableAuthKey/?api-version=7.4
Content-Type:application/json
Accept:application/json
x-ms-client-request-id:28e8ff7c-b8d9-4e3b-b7d3-780d22232649
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Secrets/4.5.0 (.NET 6.0.16; Microsoft Windows 10.0.22621)
Authorization:REDACTED
client assembly: Azure.Security.KeyVault.SecretsResponse [28e8ff7c-b8d9-4e3b-b7d3-780d22232649] 200 OK (00.1s)
Cache-Control:no-cache
Pragma:no-cache
x-ms-keyvault-region:South Central US
x-ms-client-request-id:28e8ff7c-b8d9-4e3b-b7d3-780d22232649
x-ms-request-id:e24976f4-b4ef-4aea-bd18-f72904db48b2
x-ms-keyvault-service-version:1.9.775.1
x-ms-keyvault-network-info:conn_type=Ipv4;addr=131.107.1.184;act_addr_fam=InterNetwork;
x-ms-keyvault-rbac-assignment-id:REDACTED
x-ms-keyvault-rbac-cache:REDACTED
X-Content-Type-Options:REDACTED
Strict-Transport-Security:REDACTED
Date:Tue, 18 Apr 2023 05:37:36 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:345

**Comment by navba-MSFT** [comment]
@jetuser Thanks for your reply. Could you please check the network connectivity? Ensure that your network connection is stable and that there are no firewalls or proxies blocking outbound traffic to the Azure Storage service. 

You can try using a different network connection or disabling any firewalls or proxies to see if that resolves the issue.

Are you managing the Storage Account Access keys from Keyvault ? Is your storage account using Microsoft Managed encryption setting ?

**Comment by jetuser** [comment]
Network connectivity is over corpnet so it is fine. There are no proxies or firewalls in the way. Given the keyvault client is functional I question this being an issue anyway.

The access keys on the storage accounts are actually disabled and we are authenticating via a service principal and it is using microsoft managed encryption.

**Comment by navba-MSFT** [comment]
@jetuser I have changed my code to use the Service Principal and even that worked successfully. 

```
            // Define the storage account name and queue name
            string accountName = "MyAccountName";
            string queueName = "MyQueueName";

           // Create an instance of the QueueClient class using the DefaultAzureCredential
            QueueClient queueClient = new QueueClient(new Uri($"https://{accountName}.queue.core.windows.net/{queueName}"), new DefaultAzureCredential());

            // Create the queue if it does not already exist
            await queueClient.CreateIfNotExistsAsync();
```

Library used: Azure.Storage.Queues 12.14.0

- Could you make sure that the clientid, client secrets used by the app are right ? 
- Also could you try queueClient.CreateIfNotExists( ); instead of async method and check ?
- Could you share your sample code snippet ?

**Comment by jetuser** [comment]
Unfortunately changing this code would be non trivial but here's our implementation wrapper around the call. I can confirm by the stack trace we enter the call for the queue client. Authentication token is accurate as our KeyVault calls succeed. And to be 100% clear, based on telemetry I can see there is **no** outbound call by the SDK once we make the call. It disappears into the http pipeline somewhere and never returns.

```
protected async Task EnsureQueueExistsAsync(IServiceContext serviceContext)
        {
            if (_queueCreated)
            {
                return;
            }

            await _semaphoreSlim.WaitAsync(serviceContext.CancellationToken).ConfigureAwait(false);

            try
            {
                if (_queueCreated)
                {
                    return;
                }

                await serviceContext.ExecuteWithCountersAsync(async _ =>
                {
                    await _queue.CreateIfNotExistsAsync().ConfigureAwait(false);

                    if (_deadLetterQueue != null)
                    {
                        await _deadLetterQueue.CreateIfNotExistsAsync().ConfigureAwait(false);
                    }
                }, nameof(EnsureQueueExistsAsync), _queue.Uri.Host, _logger, GetDependencyProperties).ConfigureAwait(false);

                _queueCreated = true;
            }
            finally
            {
                _semaphoreSlim.Release();
            }
        }
```

**Comment by jetuser** [comment]
Also, one additional data point. There is eventually an IOException thrown in the application about a minute after the call is made from System.Net.Http which makes me wonder if the client is not gracefully handling this and returning an error when the connection is aborted. I cannot ensure this is coming from the sdk but given this is the only http call made before this bubbles up, this seems likely:

System.IO.IOException: 'Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..'

According to diagnostic view, it also does not show an outbound httpclient call to storage, but it does show our keyvault calls. I expected to see a HTTPClient call after the last breakpoint, but nothing...

![image](https://user-images.githubusercontent.com/3870233/233728808-8f565f2b-d1d3-4bf4-9be0-3e9ec1a2b7ed.png)

**Comment by jetuser** [comment]
And more information-

Debugging shows I can get as far as the RedirectPolicy's invocation of await ProcessNextAsync and then I stop being able to step into the pipeline stage executions so I suspect something is hanging between the redirect policy and the storage request validation policy just after this which seems to be holding up the request, but the debugger is acting strange so I am unable to tell whats going on after this. Any attempt to step into the ProcessNextAsync just causes execution to resume and hang spinning doing nothing until I terminate the test task.

**Comment by navba-MSFT** [comment]
@jetuser Thanks for getting back. I am adding the Service team to look into this further.

@xgithubtriage Could you please look into this once you get a chance ? Thanks in advance.

cc @amnguye @seanmcc-msft

**Comment by jetuser** [comment]
After some further digging into the task stack. We found a deadlock in our token cache that was causing the client to hang. A self inflicted problem, thanks for the attention.

**Comment by navba-MSFT** [comment]
@jetuser Thanks for the update.
