### ISSUE TITLE
Starting/Stopping web app doesn't reflect in portal

### ISSUE THREAD

**Issue by garybushey** [Azure/azure-sdk-for-net#3561]
If I get a web app using GetByResourceGroup and then either call Start() or Stop()  on it, the status is not reflected correctly in the Azure Portal.   
 
If it is running in the portal and then use code to stop it, the portal will still say running but if I try to access it via the URL I get the message that it is not running. 

Likewise if I stop it in the portal and start it in code, the portal will still say it is stopped but I can access it via the URL.

If I look at the Inner:properties.state that has the correct value.  I am using V1.1.3 of the management packages.

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#48
