### ISSUE TITLE
[DataMovement] [Blobs] Enable all Job Plan Header File Optional Parameters

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#35613]
### Library name and version

Azure.Storage.DataMovement; Azure.Storage.DataMovement.Blobs

### Describe the bug

https://github.com/Azure/azure-sdk-for-net/blob/056f7071a4b309a370c2ce7d52b2ef256f8dccf1/sdk/storage/Azure.Storage.DataMovement/src/JobPlanExtensions.cs#L161

Add API to convert the Storage Resource to a readable Header / Stream format so we can push the information into a Job Part Plan Header file to resume for. Currently it resumes only using the basic information (transfer id, source, destination etc).

### Expected behavior

n/a

### Actual behavior

n/a

### Reproduction Steps

n/a

**Comment by jalauzon-msft** [comment]
Resolved with https://github.com/Azure/azure-sdk-for-net/pull/39411
