### ISSUE TITLE
[BUG] Forbidden calls to Table Storage

### ISSUE THREAD

**Issue by BennyM** [Azure/azure-sdk-for-net#35633]
### Library name and version

Azure.Identity 1.8.0

### Describe the bug

I have an Azure AppService with managed identity enabled which loads data from table storage in a storage account. The managed identity has been assigned Storage Table Data Contributor rights. This works fine most of the time. However sometimes we get a bunch of errors. They do go away after some time, but it seems something is broken. It's a bit hard to pinpoint what the error is given there is so little info to go by.

```
This request is not authorized to perform this operation.
RequestId:2241357d-e002-004d-1e5e-71d52e000000
Time:2023-04-17T18:56:27.0461142Z
Status: 403 (Forbidden)
ErrorCode: AuthorizationFailure

Content:
{"odata.error":{"code":"AuthorizationFailure","message":{"lang":"en-US","value":"This request is not authorized to perform this operation.\nRequestId:2241357d-e002-004d-1e5e-71d52e000000\nTime:2023-04-17T18:56:27.0461142Z"}}}

Headers:
Transfer-Encoding: chunked
Server: Windows-Azure-Table/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 2241357d-e002-004d-1e5e-71d52e000000
x-ms-client-request-id: 4e295589-9ff1-4ba7-9ccd-e9d44e48ed77
x-ms-version: REDACTED
X-Content-Type-Options: REDACTED
Date: Mon, 17 Apr 2023 18:56:26 GMT
Content-Type: application/json; odata=minimalmetadata; streaming=true; charset=utf-8
```

TableService client is initialised at startup.
```
 services.AddSingleton(_ =>
        {
return new TableServiceClient(new Uri(Configuration.GetConnectionString("StorageAccount")), new DefaultAzureCredential());
        });
```

Just as the table clients.
```
        services.AddSingleton<ISettingsRepository>(sp =>
        {
            var serviceClient = sp.GetRequiredService<TableServiceClient>();
            return new MyRepository(serviceClient.GetTableClient("mytable"));
        });
```

### Expected behavior

Can perform authenticated & authorised requests to table storage.

### Actual behavior

Receiving 403 results

### Reproduction Steps

Application runs fine for weeks, then throws these errors. The stop after a couple of minutes. No specific reproduction steps.

### Environment

Azure AppService running .NET 6
Azure.Data.Tables 12.8.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @BennyM -
Which version of Azure.Identity are you using? One thing we could do to get some more info on what is happening is to enable logging for the credential.
Details on how to enable logging can be found [here.](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md)

**Comment by BennyM** [comment]
Hi @christothes 

We are using version 1.8.0. I looked trough the change log of the recente updates but saw no reference to any changes that might be related to this. I will enable the logging, might be a while before it happens again.
