### ISSUE TITLE
[QUERY] How does the MaxConcurrentCallsPerSession setting in ServiceBusSessionProcessor actually works?

### ISSUE THREAD

**Issue by dggmez** [Azure/azure-sdk-for-net#35655]
### Library name and version

Azure.Messaging.ServiceBus 7.13.1

### Query/Question

So currently we have a web app application that is creating a **non-session subscription** to a topic setting the `MaxConcurrentCalls` setting to 1. AFAIK that means that if we have 4 instances then we will have at most 4 message locks being acquired for the subscription (one for each instance). So far so good. Now we have a business requirement that will imply that we need to process the messages in order depending on some value. Fortunately we found that ASB has the perfect feature for that and that is **sessions**:

https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-sessions

Now reading the docs it seems that it is perfect for our use case: if we have the same 4 instances then it means that each one of them will acquire a **session lock**. That will guarantee that messages with the same session ID will be processed in order. "Long live sessions" we thought. We wanted to start writing the code to setup our `ServiceBusSessionProcessor` but that's when we started to have some doubts:

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/samples/Sample05_SessionProcessor.md

More specifically I saw the `MaxConcurrentCallsPerSession` setting and that's when everything I read in the docs **stopped** making sense in my head. I thought you could only process one message per session given that the processor was gonna acquire a session lock but it seems that's not true. I guess that setting `MaxConcurrentCallsPerSession` greater than 1 means that the processor will acquire a session lock, read multiple messages from that session and then it will start processing concurrently (and that would mean that messages from the same session could be processed in an out-of-order way)? If that's the case I believe the message sessions documentation should be updated to mention that is something that can be done if you want to because all that page is talking about ordered handling. But more importantly let's say that we still have the same 4 web app instances, would setting `MaxConcurrentCallsPerSession` equal to 1 **guarantee to us** that we will never see multiple messages from the same session being processed at the same time if we use the `ServiceBusSessionProcessor`?

### Environment

* Hosting platform: .NET 7
* Visual Studio 2022

**Comment by jsquire** [comment]
> I thought you could only process one message per session given that the processor was gonna acquire a session lock but it seems that's not true. 

This is not true.  Only one consumer can hold the message lock which gives that consumer exclusive access to the session.  No other consumer can read from the session while the lock is held.   The consumer holding the lock can read as many messages concurrently from the session as it would like.    That is controlled in the processor by `MaxConcurrentCallsPerSession`.

> would setting MaxConcurrentCallsPerSession equal to 1 guarantee to us that we will never see multiple messages from the same session being processed at the same time if we use the ServiceBusSessionProcessor

Yes, this is correct.   If you want only a single message at a time, you want to set the concurrent calls to 1.
