### ISSUE TITLE
[BUG] Azure Storage Queue trigger function should retry the polling after exception like "Retry failed after X tries. Retry settings can be adjusted in ClientOptions.Retry.” "

### ISSUE THREAD

**Issue by shaykchen** [Azure/azure-sdk-for-net#35650]
### Library name and version

Extension AzureStorageQueues 5.0.1.0; Azure.Storage.Queues 12.10.0.0

### The Azure Queue trigger function would stop queue triggering listener polling due to the below exception: 

**Message: Retry failed after 6 tries. Retry settings can be adjusted in ClientOptions.Retry.**

> Inner Exception: 0x000001541fd313f8
>     Stack Trace:
>     SP               IP               Function
>     000000828cfdfef0 00007ffd3b0151c1 Azure.Core.Pipeline.RetryPolicy+<ProcessAsync>d__11.MoveNext()
>     000000828cfdcdd0 00007ffd3adf8210 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     000000828cfdce00 00007ffd99021e0f System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>     000000828cfdce40 00007ffd99021dad System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>     000000828cfdce70 00007ffd3b044ceb Azure.Storage.Queues.MessagesRestClient+<DequeueAsync>d__8.MoveNext()
>     000000828cfd9d30 00007ffd3adf8210 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     000000828cfd9d60 00007ffd99021e0f System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>     000000828cfd9da0 00007ffd99021dad System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>     000000828cfd9dd0 00007ffd3b043f8c Azure.Storage.Queues.QueueClient+<ReceiveMessagesInternal>d__89.MoveNext()
>     000000828cfd41d0 00007ffd3adf8210 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     000000828cfd4200 00007ffd99021e0f System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>     000000828cfd4240 00007ffd99021dad System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>     000000828cfd4270 00007ffd3b04357d Azure.Storage.Queues.QueueClient+<ReceiveMessagesAsync>d__88.MoveNext()
>     000000828cfd10f0 00007ffd3adf8210 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     000000828cfd1120 00007ffd99021e0f System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>     000000828cfd1160 00007ffd99021dad System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>     000000828cfd1190 00007ffd3b00c334 Microsoft.Azure.WebJobs.Extensions.Storage.Common.Listeners.QueueListener+<ExecuteAsync>d__33.MoveNext()
>     000000828cfce090 00007ffd3adf8210 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>     000000828cfce0c0 00007ffd99021e0f System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>     000000828cfce100 00007ffd99021dad System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
> 000000828cfce130 00007ffd3b00987a Microsoft.Azure.WebJobs.Extensions.Storage.Common.Timers.TaskSeriesTimer+<RunAsync>d__14.MoveNext() 
> 

### Expected behavior

Queue trigger listener should retry the polling after encounter the above exception.

### Actual behavior

Queue trigger listener stopped

### Reproduction Steps

Please see CRI 380271151 and 360166995 for detailed information.

It looks like we do not consider “Retry failed after X tries. Retry settings can be adjusted in ClientOptions.Retry.” as temporary error [here ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Common/src/Shared/Queues/QueueListener.cs#L242)and throw the exception what causes the listener to be stuck.

### Environment

Azure Function C# V4 runtime, Windows Dedicated App Service Plan

**Comment by navba-MSFT** [comment]
Since CRI / ICM was filed for this and service team is involved already,  I am adding Service team to look into this. 

@xgithubtriage Could you please look into this once you get a chance ?

CC: @amnguye @seanmcc-msft

**Comment by amnguye** [comment]
The CRI was resolved with the Service team already. Closing this issue.
