### ISSUE TITLE
How to do I work with this?

### ISSUE THREAD

**Issue by JasonDWilson** [Azure/azure-sdk-for-net#35658]
Not sure how to convert BinaryData into something I can work with and the "documentation" here doesn't help.  I know from working with the rest api directly that there should be something like *Alert.Data.Properties.Context.Context.Condition.AllOf[].SearchQuery*.  A code sample of working with BinaryData would be very useful here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a4d43035-0e63-50bf-247e-a221fe71d6b6
* Version Independent ID: 28c06fba-36a6-e3bb-0b8e-389dc32f570c
* Content: [ServiceAlertProperties.Context Property (Azure.ResourceManager.AlertsManagement.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.alertsmanagement.models.servicealertproperties.context?view=azure-dotnet)
* Content Source: [xml/Azure.ResourceManager.AlertsManagement.Models/ServiceAlertProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.AlertsManagement.Models/ServiceAlertProperties.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by HarveyLink** [comment]
Hi @JasonDWilson , Thank you for using Azure SDK for .NET.
Here are some usage of `BinaryData` type. Basically, you could use them like other stream or byte type.
```
    var json = new
    {
        id = "newid",
        resourceType = "type"
    };
    BinaryData data = BinaryData.FromObjectAsJson(json);
    var newobject = data.ToObjectFromJson<TestObject>();
    var str = "somevalue";
    BinaryData data2 = BinaryData.FromString(str);
    var newstr = data2.ToString();

public class TestObject
{
    public string? Id { get; set; }
    public string? ResourceType { get; set; }
}
```
