### ISSUE TITLE
Allow setting idle timeout in ServiceBus client

### ISSUE THREAD

**Issue by lynn-orrell** [Azure/azure-sdk-for-net#35663]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

Please make available the ability to set the idle timeout of connections. It looks like this is currently set to 60 seconds which negatively affects performance in cases where the publisher or entity isn't very lively.

**Comment by jsquire** [comment]
This is exposed in Event Hubs as part of the connection options available to each client.   It looks like the equivalent would be to add this to `ServiceBusClientOptions`.

**Comment by jsquire** [comment]
This was added in #35920 and will be included in the next release.
