### ISSUE TITLE
AppService AnalyzeCustomHostname method fails

### ISSUE THREAD

**Issue by MykhayloKonopelskyy** [Azure/azure-sdk-for-net#3568]
```
IAzure.WebApps
           .Inner
           .AnalyzeCustomHostname(
"WebAppResourceGroupName",
"WebAppName",
"Hostname")
```

throws exception 
```
Unable to deserialize the response. (Inner exception - Unexpected character encountered while parsing value: <. Path '', line 0, position 0.). Because azure management api returns xml, but this fluent sdk expects json.
```

As a workaround, I can catch this SerializationException and parse manually xml from exception Content property.

Moreover, we can include Accept : "application/json" header to azure management api request and azure management api returns json, but json isn't correctly parsed by AnalyzeCustomHostnameWithHttpMessagesAsync(returned Body property has all properties with NULL values)

```
IAzure.WebApps
                .Inner
                .AnalyzeCustomHostnameWithHttpMessagesAsync(_WebAppResourceGroupName, _WebAppName, hostname, new Dictionary<string, List<string>> {{ "Accept", new List<string> { "application/json" }}}).Result;
```

I am using these packages under asp.net core (full .net targeting):
"Microsoft.Azure.Management.Fluent" Version="1.1.3"
"Microsoft.IdentityModel.Clients.ActiveDirectory" Version="2.28.4"

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#47
