### ISSUE TITLE
DataPlaneUri property doesn't have a setter?

### ISSUE THREAD

**Issue by joeleeatwork** [Azure/azure-sdk-for-net#35681]
### Library name and version

Azure.ResourceManager.LoadTesting 1.0.1

### Query/Question

Why doesn't Azure.ResourceManager.LoadTesting.LoadTestingResourceData.DataPlaneUri have a setter? I am unable to mock this response as a result.

**Comment by ArthurMa1978** [comment]
Hi @joeleeatwork , this property is defined as readonly [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/loadtestservice/resource-manager/Microsoft.LoadTestService/stable/2022-12-01/loadtestservice.json#L684).
For mocking test, actually we're working on a new [feature: Model Factory](https://github.com/Azure/azure-sdk-for-net/issues/35189) which will release it soon to support mock all these models.

**Comment by joeleeatwork** [comment]
@ArthurMa1978 Got it. Thanks for the info and look forward to it!
