### ISSUE TITLE
[Extensions] Investigate dependency version bump for DataProtection libraries

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#35707]
# Summary

The Azure SDK libraries for data protection, `Azure.Extensions.AspNetCore.DataProtection.Keys` and `Azure.Extensions.AspNetCore.DataProtection.Blobs`, have a dependency on an older version of the `Microsoft.AspNetCore.DataProtection` library, [v3.1.32](https://www.nuget.org/packages/Microsoft.AspNetCore.DataProtection/3.1.32).   The 3.0.x version line dates back to 2019 and several major versions have been added since.   

It would be good to investigate moving to the 6.0.x version line to align with the current LTS version of .NET.   It may be worth considering moving to the 7.0.x line if we wanted to, instead, move to the latest non-preview version.   These newer versions remove target support for `netcore3.0` and `netcoreapp3.1` which are no longer supported and cause some vulnerability scanners to generate false positives due to transitive dependencies with issues that exist only for those unsupported platforms.

# References and Related

- [CVE in System.Drawing.Common 4.7.0 dependency still there (#35693)](https://github.com/Azure/azure-sdk-for-net/pull/35693)
- [CVE in System.Drawing.Common 4.7.0 dependency (#32781)](https://github.com/Azure/azure-sdk-for-net/issues/32781)

**Comment by SymbioticKilla** [comment]
@jsquire Hi, is here any update on this issue? 
Thanks!

**Comment by jsquire** [comment]
> @jsquire Hi, is here any update on this issue? Thanks!

There is not.

**Comment by jsquire** [comment]
This work has been completed.   The latest releases of the Azure SDK data protection packages now reference Microsoft.AspNetCore.DataProtection 8.x.
