### ISSUE TITLE
[BUG] CloudBlobContainer.GetSharedAccessSignature returns invalid SAS token for bad URI

### ISSUE THREAD

**Issue by ashanhol** [Azure/azure-sdk-for-net#35710]
### Library name and version

Azure.Storage.Blobs 12.15.0

### Describe the bug

**Issue**: CloudBlobContainer.GetSharedAccessSignature returns invalid SAS token for URI including a trailing '/?'. 
Example of bad URI: https://[StorageAccount].blob.core.windows.net/[container]/?
It's probably a string validation issue, hopefully an easy fix.

### Expected behavior

Some sort of error, exception, or null token

### Actual behavior

An invalid SAS Token that gave authentication errors, specifically:
`Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.`

### Reproduction Steps

``` C#
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Microsoft.WindowsAzure.Storage.Auth;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;

// Grab SAS Token for container
const String Container = "";
const String StorageAccountName ="";
const String AccountKey = "";
const String Blob = "";

async Task<IEnumerable<string>> ListBlobsAsync()
{

var policy = new SharedAccessBlobPolicy();

// Malformed SAS string
var sasToken = new CloudBlobContainer(new($"https://{StorageAccountName}.blob.core.windows.net/{Container}/?"), new StorageCredentials(StorageAccountName, AccountKey)).GetSharedAccessSignature(policy, null, SharedAccessProtocol.HttpsOnly, null);
// Ok String
//var sasToken = new CloudBlobContainer(new($"https://{StorageAccountName}.blob.core.windows.net/{Container}"), new StorageCredentials(StorageAccountName, AccountKey)).GetSharedAccessSignature(policy, null, SharedAccessProtocol.HttpsOnly, null);

var directoryUri = $"https://{StorageAccountName}.blob.core.windows.net/{Container}/{Blob}?{sasToken}";

// Use URI to list blobs, running into authentication error
var blob = new CloudBlockBlob(new(directoryUri));
var directory = blob.Container.GetDirectoryReference(blob.Name);

BlobContinuationToken continuationToken = null;
var results = new List<string>();

do
{
  // Where we run into authentication error
  var response = await directory.ListBlobsSegmentedAsync(useFlatBlobListing: true, blobListingDetails: BlobListingDetails.None, maxResults: null, currentToken: continuationToken, options: null, operationContext: null);
  continuationToken = response.ContinuationToken;
  results.AddRange(response.Results.Cast<CloudBlob>().Select(b => b.Name));
}
while (continuationToken is not null);

return results;

}

var blobs = await ListBlobsAsync();
if(!blobs.Any()) throw new Exception("should have blobs");

```

**Comment by navba-MSFT** [comment]
@ashanhol Apologies for the late reply. Thanks for reaching out to us and reporting this issue. You seem to be using [Microsoft.Azure.Storage.Blob library](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/) which is deprecated. 

The Azure SDK team encourages you to upgrade to the replacement package, [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs).

This issue has been fixed in [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs). v12 SDK see the related PR here: https://github.com/Azure/azure-sdk-for-net/pull/34773 . More info [here](https://github.com/Azure/azure-sdk-for-net/issues/34591).

**Comment by ashanhol** [comment]
@navba-MSFT Your comment prompted me to do a bit of digging since our project was explicitly including Azure.Storage.Blobs v. 12.15 but not Microsoft.Azure.Storage.Blob. Turns out what's actually being referenced is actually the deprecated deprecated WindowsAzure.Storage package, because that's used by Microsoft.Azure.Management.Fluent. 

I haven't seen a lot of documentation around migrating from the deprecated packages to the newer ones. Our team is small and it seems like instigating the switch would open up a lot of unanticipated untangling. Is there a strong reason to switch outside of expected technical debt?

**Comment by navba-MSFT** [comment]
@ashanhol I had created an email chain with the Product Owners. Hope your questions are sorted. Here is the documentation to migrate to the new SDK Azure.Storage.Blobs : https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/AzureStorageNetMigrationV12.md
