### ISSUE TITLE
[QUERY] what's the recommended way to programmatically detect if a storage account is private or not?

### ISSUE THREAD

**Issue by heiaun-jack** [Azure/azure-sdk-for-net#35725]
### Library name and version

Azure.Storage.Blobs" Version="[12.13.1]

### Query/Question

The situation is: 
If we are given a Blob URL with a SAS token from a customer, we must first determine if it is a private endpoint from our side before performing any operations. 
To do this programmatically, there are a few possible methods we tried:
1. One approach is to check for the 'privateEndpointConnections' field in the storage account's JSON resource representation, but seems this is not currently available in SDK for .NET. 

2. Another option is to use the Dns.GetHostEntryAsync method to resolve the domain name 'xxx.blob.core.windows.net'; however, we found that even a VM outside of the storage account's VNET still received a result from DNS resolution. To handle this, we added a check for resolving 'xxx.privatelink.blob.core.windows.net'.

However, the best practice for determining whether a Blob URL is a private endpoint is currently unclear. Do you have any idea what is the recommended method for handling this case?"

**Comment by heiaun-jack** [comment]
for more details plz see the below link. Tanks!
https://stackoverflow.microsoft.com/questions/352153

**Comment by navba-MSFT** [comment]
@heiaun-jack Apologies for the late reply. Thanks for reaching out to us and reporting this issue. You can rely on either of the below properties of the Azure Storage account: 

properties.privateEndpointConnections | PrivateEndpointConnection[] | List of private endpoint connection associated with the specified storage account
-- | -- | --


properties.publicNetworkAccess | PublicNetworkAccess | Allow or disallow public network access to Storage Account. Value is optional but if passed in, must be 'Enabled' or 'Disabled'.
-- | -- | --


You need to use the [Azure.ResourceManager.Storage](https://www.nuget.org/packages/Azure.ResourceManager.Storage/) SDK package to fetch this. Refer [the sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.ResourceManager.Storage/samples/Sample1_ManagingStorageAccounts.md) which you can leverage.

**Comment by heiaun-jack** [comment]
Hi @navba-MSFT, thanks for your response!  

It needs to authenticate the client before using `ArmClient`. However, if we only have access to the SAS token and storage account endpoint provided by the customer, I couldn't find a way to authenticate the client. In addition, if only access the SAS token and storage account endpoint, is there any way to determine whether a storage account is private or not?

**Comment by heiaun-jack** [comment]
Another question:
Hi @navba-MSFT, Can I determine whether an Azure Blob storage account is private based on whether we can resolve the IP address associated with its domain name ('mystorageaccount.privatelink.blob.core.windows.net')?

**Comment by navba-MSFT** [comment]
@heiaun-jack Thanks for your reply.

> If only access the SAS token and storage account endpoint, is there any way to determine whether a storage account is private or not?

The [Storage Accounts - Get Properties](https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/get-properties?tabs=HTTP) call is required to fetch the PrivateEndpoint connection. This is a control plane (management plane)  operation and requires the Authorization using Azure Active Directory OAuth2. 


> Can I determine whether an Azure Blob storage account is private based on whether we can resolve the IP address associated with its domain name ('mystorageaccount.privatelink.blob.core.windows.net')?

Yes, you can determine whether an Azure Blob storage account is private by checking whether you can resolve the IP address associated with its domain name (mystorageaccount.privatelink.blob.core.windows.net). If the storage account is private, it will be accessible only through a private endpoint within a virtual network. The domain name for the storage account will be in the format <storage-account-name>.privatelink.blob.core.windows.net. When you try to resolve this domain name from outside the virtual network, you will not be able to get the IP address associated with it. 

On the other hand, if the storage account is public, it will be accessible from the public internet and you will be able to resolve the IP address associated with its domain name.
So, if you are able to resolve the IP address associated with the domain name mystorageaccount.privatelink.blob.core.windows.net, it means that the storage account is not private and is accessible from the public internet.

**Comment by heiaun-jack** [comment]
Hi @navba-MSFT,  

> On the other hand, if the storage account is public, it will be accessible from the public internet and you will be able to resolve the IP address associated with its domain name. So, if you are able to resolve the IP address associated with the domain name mystorageaccount.privatelink.blob.core.windows.net, it means that the storage account is not private and is accessible from the public internet.

could you elaborate more on this? 
why when we are able to resolve IP with `privatelink` it means that the storage account is not private and is accessible from the public internet? a typo?

**Comment by heiaun-jack** [comment]
Hi @navba-MSFT 

Even if a private link is set up for a storage account, we cannot get an IP address for the 'privatelink' domain name when the caller is not on the virtual network, right?

In this case, the caller is outside the virtual network, we got [NoData](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socketerror?view=net-7.0) response when accessing 'mystorageaccount.blob.core.windows.net' (not the 'privatelink' domain name).
whether we can use this to determine a private account when the caller is outside the virtual network?

**Comment by navba-MSFT** [comment]
@heiaun-jack 

> Hi @navba-MSFT
> 
> Even if a private link is set up for a storage account, we cannot get an IP address for the 'privatelink' domain name when the caller is not on the virtual network, right?
> 
> In this case, the caller is outside the virtual network, we got [NoData](https://learn.microsoft.com/en-us/dotnet/api/system.net.sockets.socketerror?view=net-7.0) response when accessing 'mystorageaccount.blob.core.windows.net' (not the 'privatelink' domain name). whether we can use this to determine a private account when the caller is outside the virtual network?

When a private endpoint is set up for a storage account and the caller is not on the associated virtual network, it is not possible to resolve the IP address for the 'privatelink' domain name.

When a storage account is configured with a private endpoint, the 'privatelink' domain name is resolved internally within the virtual network. The resolution of this domain name to an IP address is only possible when the caller is within the same virtual network where the private endpoint is configured.

If you are not on the virtual network associated with the storage account's private endpoint, you will not be able to resolve the 'privatelink' domain name to its IP address. This behavior ensures that the storage account remains inaccessible from outside the virtual network, enhancing its privacy and security.
