### ISSUE TITLE
Example header misrepresents activity - should be replaced with an actual Create/Update operation

### ISSUE THREAD

**Issue by WhitWaldo** [Azure/azure-sdk-for-net#35721]
The "Update a resource group" represents that an update is being applied to a resource group, suggesting that this is the approach taken to update other resources and this is incorrect (as there's not a generic UpdateProperty method available - rather, this mechanism for updates is exclusively available for tags and will confuse developers. I would instead suggest that this section header be instead modified to read "Update tags applied to resource group" and that a separate, more helpful example be provided that demonstrates a realistic update to a resource beyond just tags.

I tried to find some way of submitting this update inline as a PR, but this page doesn't appear to accept contributions, so I'll suggest via this issue instead. With regards to updating a resource how it would actually be performed, My suggestion is to use a more realistic resource operation such as changing the IP address associated with an A Record on an Azure DNS Zone.

As we are making changes to a DNS resource, we'll need to install the `Azure.ResourceManager.Dns` package from NuGet in addition to the other packages cited towards the top of this document.

A sample method for this is as follows:

```cs
    public async Task UpdateDnsARecordAsync(string subscriptionId, string resourceGroupName, string zoneName, string aRecordName, IPAddress ipv4Address)
    {
        //Check to see if the A record already exists on our zone. If it does, update the record. If not, create it.
        //Start by retrieving a reference to the DNS zone
        var dnsZone = _armClient.GetDnsZoneResource(DnsZoneResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, zoneName));
        
        //List the existing A records
        var aRecords = dnsZone.GetDnsARecords();

        //Determine if the record already exists
        var recordExists = await aRecords.ExistsAsync(aRecordName);

        if (recordExists.HasValue && recordExists.Value)
        {
            //Record already exists, so we'll apply an update to it. First we'll need to retrieve it so we have its associated data.
            var existingRecord = await aRecords.GetAsync(aRecordName);

            //We'll update the IP address to reflect our changes by first clearing the existing list and then adding our new record.
            existingRecord.Value.Data.DnsARecords.Clear();
            existingRecord.Value.Data.DnsARecords.Add(new DnsARecordInfo
            {
                IPv4Address = ipv4Address
            });

            //Apply our changed data back to the A record on our DNS zone - this is done against the record collection we previously retrieved
            await aRecords.CreateOrUpdateAsync(WaitUntil.Completed, aRecordName, existingRecord.Value.Data);
        }
        else
        {
            //Record does not yet exists, so we'll create it
            var aRecordData = new DnsARecordData
            {
                TtlInSeconds = 30,
                DnsARecords =
                {
                    new DnsARecordInfo
                    {
                        IPv4Address = ipv4Address
                    }
                }
            };
            //The create operation is applied to the collection of A records on the DNS zone we previously retrieved
            await aRecords.CreateOrUpdateAsync(WaitUntil.Completed, aRecordName, aRecordData);
        }
    }
```

Thank you for your consideration!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 82afd7d0-2457-2bf4-fec5-ebc5ddb2a7d7
* Version Independent ID: 23715b2d-c3c8-6198-8c17-5b0e691dc95f
* Content: [Microsoft Azure Resource Manager client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resourcemanager-readme?view=azure-dotnet&source=docs)
* Content Source: [api/overview/azure/latest/resourcemanager-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/resourcemanager-readme.md)
* Service: **resourcemanager**
* GitHub Login: @pallavit
* Microsoft Alias: **pallavit**

**Comment by HarveyLink** [comment]
Hi @WhitWaldo , Thanks you for using Azure SDK for .NET.
This sample only demonstrate one way to operate the resourcegroup by our SDK, for other resources, we could have other samples to cover, like: https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resourcemanager-readme?view=azure-dotnet&source=docs#update-genericresource.
