### ISSUE TITLE
Nuget Installation Failing

### ISSUE THREAD

**Issue by bezveza** [Azure/azure-sdk-for-net#3572]
In my project I have the latest Newtonsoft.Json (>= 10.0.3)
The nuget failed to install because of version conflict detected for Newtonsoft.Json.

Version conflict detected for Newtonsoft.Json. 
// -> Microsoft.Azure.Management.Cdn (>= 2.1.0) -> Microsoft.Rest.ClientRuntime (>= 2.3.1) -> Newtonsoft.Json (>= 9.0.1).
Installing NuGet package Microsoft.Azure.Management.Cdn 2.1.0.
Committing restore...

With Best Regards,

**Comment by Petermarcu** [comment]
Not sure if this is still an issue for you but its been a long time. We're removing our dependency on JSON.NET in future releases so we expect this problem to go away over time. Let us know if there still issues you are hitting by opening up a new issue. Thanks!
