### ISSUE TITLE
client.WebApps.GetAuthSettingsSlotWithHttpMessagesAsync returns null body

### ISSUE THREAD

**Issue by fbertilsson** [Azure/azure-sdk-for-net#3573]
It seems that GetAuthSettingsSlotWithHttpMessagesAsync always returns a body which is null.
Code used:
```           
       var currentSettings = await client.WebApps.GetAuthSettingsSlotWithHttpMessagesAsync(
                resourceGroup.Name,
                Name,
                stagingSlotName,
                null,
                cancel
            );
            var body = currentSettings?.Body;
            if (body != null)
            {
                ...
```

**Comment by shahabhijeet** [comment]
@fbertilsson can you provide the following information, also can you confirm if the status code 200 when you get the null body?
1) Version of the SDK you are using
2) Fiddler trace that shows the request and response

I have not seen any change in the swagger, the response is a complex object and it should return body with the response.

@ahmedelnably for visibility

**Comment by fbertilsson** [comment]
1. I'm using Microsoft.Azure.Management.Websites version **1.6.0-preview**
