### ISSUE TITLE
[QUERY] Azure Keyvault Key type RSA - size change

### ISSUE THREAD

**Issue by Basel78** [Azure/azure-sdk-for-net#35736]
### Library name and version

Azure.Security.KeyVault.Keys

### Query/Question

I have created KeyVault with key of Type RSA and size 2048 ,, later I wanted to change the size to 3072
and I used terraform to create the infra resources, I made the change in the terraform template and applied the changes.. that shows the message
` ~ key_size                = 2048 -> 3072 # forces replacement`
after applying passed successfully, I changed the key in azure portal and it still showing the old size 2048.

is there away to change keyvault key size from 2048 to 3072

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
This is more of a service request, but it is possible to create a new key version with a different key size:

```bash
az keyvault key create --vault-name {vault-name} -n rsa-test --kty RSA --size 2048
az keyvault key create --vault-name {vault-name} -n rsa-test --kty RSA --size 4096
```

The `n` (public key) is appropriately sized in each case. Key versions are each effectively new keys but associated by a name. If the Portal isn't showing a size change, I would refresh it to make sure the new key information was loaded. Also drill into the key versions to see if it was even pushed.

If not, please open a bug against Terraform. They don't use the Azure SDKs.
