### ISSUE TITLE
[QUERY] Updating an AKV Key in place

### ISSUE THREAD

**Issue by patilsnr** [Azure/azure-sdk-for-net#35768]
### Library name and version

Azure.Security.KeyVault.Keys

### Query/Question

Hi! I'm writing an application that requires an akv key to have its value updated. The current method that I've been using is to delete the key with `TryDeleteKeyFromKeyVaultAsync` and then creating a new key with the same name as the deleted one. Is there a way to update the value of the key in place? I see that `KeyClient` has an `UpdateKeyPropertiesAsync` method, but I'm not sure if that creates a new value for the key while keeping the same name, which is what I need.

Please let me know if this makes sense; I'm happy to clarify as needed. Happy Monday!

### Environment

VS 2022, .NET 7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Keys - along with secrets and certificates - are all versioned. If you just create a key with the same name, a new version is created as the latest version. This is what Key Vault recommends and it's vital to avoid getting crypto-locked. Consider that you encrypt data using key version 1 and later create a key version 2. If you deleted what would be version 1, you have no way to decrypt that data. By creating new versions of keys, you store the key ID - which contains the version e.g., "https://{vault-name}.vault.azure.net/keys/{key-name}/{key-version}" - along with the data so you can retrieve the appropriate key and decrypt the data.
