### ISSUE TITLE
Fluent: missing ability to create a disk from a platform image?

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#3576]
I can't seem to find any fluent API way to execute this REST API to create a new managed disk from an existing platform image:

```
PUT 
/subscriptions/{subscriptionId}/resourceGroupName/{resourceGroup}/providers/Microsoft.Compute/disks/{diskName}?api-version={api-version}
--
{ 
  "name": "myManagedDisk1", 
  "location": "West US", 
  "properties": { 
    "osType": "Windows", 
    "creationData": { 
      "createOption": "FromImage", 
      "imageReference": { 
        "id": "/Subscriptions/{subscriptionId}/Providers/Microsoft.Compute/Locations/uswest/Publishers/Microsoft/ArtifactTypes/VMImage/Offers/{offer}"  
      } 
    }
  }
}  
```

All I can see are options to create the disk from existing VHD, an existing managed disk, or an existing snapshot.

(feedback based on "Microsoft.Azure.Management.Compute.Fluent" version="1.1.3")

**Comment by anuchandy** [comment]
@TimLovellSmith 

Fluent layer intentionally hide this option. Once we create a managed disk using `FromImage` with a platform image as source, the only way to use that disk as OS Disk is via "Attach" option. When VM is created with "Attach" option platform will boot the VM as is, without specializing the VHD, this means user won't be able to set user credentials for the VM. At this point VM is un-usable. "FromImage" is used by compute resource provider internally as part of creation of VM with implicit managed disk.

Could you let us know the end-to-end scenario you are trying to achieve with this option?

**Comment by TimLovellSmith** [comment]
@anuchandy 
I see. I guess you're right that it could confuse people just trying to do the most basic thing (create a VM). FWIW, I was trying to implement a scenario where I would just download the nonspecialized VHD to see if I can manipulate it, and then turn it into a new image. Currently I am working around by just forming the HTTP request myself. So its no big deal for me.

**Comment by anuchandy** [comment]
@TimLovellSmith if the non-specialized (generalized) VHD is stored in a storage account then you can create a custom image by pointing to it (without downloading it). Something like:

```C#
var image = azure.VirtualMachineCustomImages.Define(`<image-name>`)
        .WithRegion(Region.USEast)
        .WithNewResourceGroup(`new-resource-group-name`)
        .WithLinuxFromVhd(`url-to-your-vhd`, OperatingSystemStateTypes.Generalized)
        .WithOSDiskCaching(CachingTypes.ReadWrite)
        .Create();
```

**Comment by TimLovellSmith** [comment]
@anuchandy manipulation being the key word :)
