### ISSUE TITLE
How can I find the state of a ContainerGroup with Azure.ResourceManager.ContainerInstance?

### ISSUE THREAD

**Issue by jaltin** [Azure/azure-sdk-for-net#35764]
### Library name and version

Azure.ResourceManager 1.4.0 and Azure.ResourceManager.ContainerInstance 1.0.1

### Query/Question

I need to find the current state of container instances in a resource group (e.g. Running/Terminated etc).

I am at loss on how to achieve this. I have tried looping through the container groups using the following approach (code sample is from a function app):

```
          private static async Task LogContainerGroupStatus(ILogger log)
        {
            TokenCredential credentials = new DefaultAzureCredential();
            ArmClient armClient = new ArmClient(credentials);

            var subscriptionId = "[subscription id]";
            var resourceGroupName = "[resource group name]";
            var resourceGroupResourceId = ResourceGroupResource.CreateResourceIdentifier(subscriptionId, resourceGroupName);
            var resourceGroupResource = armClient.GetResourceGroupResource(resourceGroupResourceId);

            // Get the existing container groups
            ContainerGroupCollection containerGroups = resourceGroupResource.GetContainerGroups();

            foreach (var containerGroup in containerGroups)
            {
                var state = containerGroup.Data.InstanceView.State;
                log.LogInformation($"ContainerGroup: {containerGroup.Data.Name}, ProvisioningState: {containerGroup.Data.ProvisioningState}, State: {state}");
            }
        }
```

However, containerGroup.Data.InstanceView is null so I can't get the state.

Is this due to a bug in the SDK (see https://github.com/Azure/azure-sdk-for-net/issues/31058)?

Or am I doing it the wrong way and this should be done differently?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by live1206** [comment]
@jaltin Please check this PR: https://github.com/Azure/azure-sdk-for-net/pull/36410, I just added a row to verify the state and it works.

You need to create a `ContainerGroup` before getting it like it does in the above test, from your code I can't see if any `ContainerGroup` already exists in your resource group. Please let me know if I am missing anything from your code.
