### ISSUE TITLE
Add validation to the download blob API.

### ISSUE THREAD

**Issue by pallavit** [Azure/azure-sdk-for-net#35771]
Given the download blob can redirect. We want to add the following validation to the download blob API

- [x] Do not validate docker-content-digest header for blob download (but keep validating requested digest vs content)
- [x] Do validate content-range header when downloading blob

> [ ] it must be present and have positive full length. throw exception otherwise
> [ ] only read up to this length

- [x] Validate manifest when downloading it:

> - [x] check docker-content-digest header (even if manifest is requested by digest)
> - [x] may add sanity check for manifest size - 4mb is unofficial, but justified [containerd] (https://github.com/containerd/containerd/blob/main/remotes/docker/resolver.go#L59) limit

Java PR - https://github.com/Azure/azure-sdk-for-java/pull/34737

**Comment by jsquire** [comment]
FYI - There's a very good possibility that the Core redirect policy is being removed in favor of allowing the transport to hold redirect responsibility. 

//cc: @christothes

**Comment by annelo-msft** [comment]
@pallavit, the .NET ACR client doesn't add any special policies to the pipeline, other than the `ContainerRegistryChallengeAuthenticationPolicy`.  Can you help me understand what ACR redirect policy you're referring to?

**Comment by pallavit** [comment]
Ahh my bad then. I created this bug since I saw one in Java and wanted to make sure we talk about it across languages in our FC - https://github.com/Azure/azure-sdk-for-java/issues/33183. Looks like this is a no-op for us.

**Comment by pallavit** [comment]
Yeah I just realized we had difference in behavior here across languages. Updating the description of the bug :)
