### ISSUE TITLE
[FEATURE REQ] Application Insights should support `db.system` attribute = `cosmosdb`

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-net#35793]
### Library name

Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

_I don't think this is the right repo for this issue but I did not find the right one._

When tracking Cosmos DB dependencies (feature available since [3.32.0-preview](https://github.com/Azure/azure-cosmos-dotnet-v3/releases/tag/3.32.0-preview) version of the .NET SDK for Azure Cosmos DB) with the Application Insights SDK, the type is recognized and the Cosmos DB icon is present.

![1](https://user-images.githubusercontent.com/131747753/234196945-41632137-4855-4b9c-ac14-5fb7463ce601.png)

However, when tracking Cosmos DB dependencies with OpenTelemetry (either with the Azure Monitor OTEL exporter or the OTEL protocol exporter + collector), the type does not seem to be properly recognized.

![2](https://user-images.githubusercontent.com/131747753/234197373-f5a3823d-9e80-4eb6-a6ce-fced4ef6e563.png)

The value `cosmosdb` comes from the `db.system` attribute and seems correct according to the OpenTelemetry specification (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#connection-level-attributes). It would be interesting if Application Insights could support it.

**Comment by cakescience** [comment]
I will test the nightly build and come back to you of course!
But I have a question: do we really need to fix in `Azure.Monitor.OpenTelemetry.Exporter`? Or App Insights should support `cosmosdb` value? Because using the [OpenTelemetry protocol exporter](https://www.nuget.org/packages/OpenTelemetry.Exporter.OpenTelemetryProtocol), the value will be `cosmosdb` (from `db.system` attribute) and if App Insights does not support it, we will probably have to use the [attributes processor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/attributesprocessor/README.md) to rename the attribute (or something similar).

**Comment by cakescience** [comment]
Basically, it is the same for SQL Server (when using OTEL protocol exporter):

![image](https://user-images.githubusercontent.com/131747753/234673903-e8119304-7f27-4f38-8e30-fdb4b537c303.png)

`mssql` is a well-known value from the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#connection-level-attributes) but not supported by App Insights (no icon and MSSQL uppercase instead).

**Comment by vishweshbankwar** [comment]
> Basically, it is the same for SQL Server (when using OTEL protocol exporter):
> 
> ![image](https://user-images.githubusercontent.com/131747753/234673903-e8119304-7f27-4f38-8e30-fdb4b537c303.png)
> 
> `mssql` is a well-known value from the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#connection-level-attributes) but not supported by App Insights (no icon and MSSQL uppercase instead).

@cakescience Could you clarify how you are using otlp exporter to send data to Application Insights resource?

**Comment by vishweshbankwar** [comment]
> @cakescience Do you mind trying the nightly build https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#nuget-package-dev-feed to see if it matches your expectation? There was a recent change that was done which is not released yet as beta package.

Also, did you try this out?

**Comment by cakescience** [comment]
> > Basically, it is the same for SQL Server (when using OTEL protocol exporter):
> > ![image](https://user-images.githubusercontent.com/131747753/234673903-e8119304-7f27-4f38-8e30-fdb4b537c303.png)
> > `mssql` is a well-known value from the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#connection-level-attributes) but not supported by App Insights (no icon and MSSQL uppercase instead).
> 
> @cakescience Could you clarify how you are using otlp exporter to send data to Application Insights resource?

This way:

```cs
services.AddOpenTelemetry()
    .ConfigureResource(builder =>
    {
        builder.AddEnvironmentVariableDetector();
    })
    .WithTracing(builder =>
    {
        builder
            .AddAspNetCoreInstrumentation(options =>
            {
                options.RecordException = true;
            })
            .AddEntityFrameworkCoreInstrumentation()
            .AddSource("Azure.Cosmos.Operation")
            .AddOtlpExporter(options => options.Endpoint = new Uri("http://localhost:4317/"));
    })
```

OpenTelemetry Collector configuration:
```yaml
receivers:
  otlp:
    protocols:
      grpc:

exporters:
  azuremonitor:
    instrumentation_key: xxx

processors:
  batch:

service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - azuremonitor
    metrics:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - azuremonitor
    logs:
      receivers: 
        - otlp
      processors:
        - batch
      exporters:
        - azuremonitor
````

**Comment by cakescience** [comment]
> > @cakescience Do you mind trying the nightly build https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#nuget-package-dev-feed to see if it matches your expectation? There was a recent change that was done which is not released yet as beta package.
> 
> Also, did you try this out?

Yes and the result is the same

**Comment by vishweshbankwar** [comment]
> > > @cakescience Do you mind trying the nightly build https://github.com/Azure/azure-sdk-for-net/blob/main/CONTRIBUTING.md#nuget-package-dev-feed to see if it matches your expectation? There was a recent change that was done which is not released yet as beta package.
> > 
> > 
> > Also, did you try this out?
> 
> Yes and the result is the same

What is the value of type field with nightly build?

**Comment by vishweshbankwar** [comment]
> Using `Azure.Monitor.OpenTelemetry.Exporter` from the nightly build:
> 
> ![image](https://user-images.githubusercontent.com/131747753/235738496-fa82aae0-b50d-438e-b667-e08cf20a0acd.png)
> 
> It is ok for SQL but not for Cosmos DB (the type is cosmosdb)
> 
> But using OTLP exporter:
> 
> ![image](https://user-images.githubusercontent.com/131747753/235739361-fa99125e-db8b-4eb5-b2fd-eba8319f1169.png)
> 
> Both SQL and Cosmos DB are not ok (but the value are correct according to the OpenTelemetry specification (https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#connection-level-attributes).
> 
> Is this really something that needs to be solved in the Azure Monitor exporter? Or in Application Insights directly, so the issue will be solved also when using the OTLP exporter?

Could you please share what version of nightly build you are using? type should be set to `Microsoft.DocumentDB`.

Regarding the otlp part, we do not support the solution that you are using so I cannot comment on that.

**Comment by cakescience** [comment]
I did a new test with the version 1.0.0-alpha.20230306.1 and the result is:

![image](https://user-images.githubusercontent.com/131747753/235786852-ee117b52-eba1-49b5-8cb7-591d7c7a5939.png)

type: `Other` for Cosmos DB and `SQL` for SQL Server

**Comment by vishweshbankwar** [comment]
> I did a new test with the version 1.0.0-alpha.20230306.1 and the result is:
> 
> ![image](https://user-images.githubusercontent.com/131747753/235786852-ee117b52-eba1-49b5-8cb7-591d7c7a5939.png)
> 
> type: `Other` for Cosmos DB and `SQL` for SQL Server

Try with `1.0.0-alpha.20230428.1` or later version. `1.0.0-alpha.20230306.1` is an old version and does not have the changes

**Comment by cakescience** [comment]
Indeed, it is working with a recent version, thank you.
Regarding OTLP, it's not a question of supporting the OTLP exporter itself, it's just that I think App Insights should support the types described in the OpenTelemetry specification.
