### ISSUE TITLE
[FEATURE REQ] Support for stream in ImageAnalysis v4

### ISSUE THREAD

**Issue by AndersMad** [Azure/azure-sdk-for-net#35795]
### Library name

Azure.AI.Vision.ImageAnalysis

### Please describe the feature.

`VisionSource` has no support for streams - only file and url. The `VisionSource.FromFrameSource` seems to require a codec to provide it with meta data.

A `VisionSource.FromStream` would be very usefull (or impossible to use ImageAnalysis without)

**Comment by jsquire** [comment]
Hi @AndersMad.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, the `Azure.AI.Vision.ImageAnalysis` library is not developed in this repository and the team that owns it would not see this issue.  

From what I've been able to find, that package is not open source and does not have a repository that we could transfer this to.  I was also unable to find any feedback or "contact us" resources in their documentation.    is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  The best suggestion that I can offer would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) - though that isn't normally the best path for feature requests, either.   

I apologize that we're not able to offer more assistance.
