### ISSUE TITLE
Unable to create API Operation with parameters

### ISSUE THREAD

**Issue by chrisll** [Azure/azure-sdk-for-net#35802]
When trying to create an operation with any parameters using the .net sdk a 400 is returned. 

Example code:
`ResourceIdentifier apiResourceId = ApiResource.CreateResourceIdentifier(configs.subscriptionId, configs.resourceGroupName, configs.serviceName, apiName);
            ApiResource api = client.GetApiResource(apiResourceId);
            ApiOperationCollection collection = api.GetApiOperations();
            ApiOperationData data = new ApiOperationData()
            {
                Description = operation.Description,
                DisplayName = operation.Name,
                Method = operation.HTTPType.ToString(),
                UriTemplate = operation.FrontendURITemplate,                
            };
            ArmOperation<ApiOperationResource> lro = await collection.CreateOrUpdateAsync(WaitUntil.Completed, operation.OperationId, data);`

Even if I use the Example URL "/customers/{cid}/orders/{oid}/?date={date}" I receive the following error

{"error":{"code":"ValidationError","message":"One or more fields contain incorrect values:","details":[{"code":"ValidationError","target":"","message":"All template parameters used in the UriTemplate must be defined in the Operation 'OperationName', and vice-versa."}]}}

This suggests I should be defining the parameters but as you can see ` public IList<ParameterContract> TemplateParameters { get; }` doesn't contain a setter

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @chshum , please use [IList.Add](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ilist.add) to add parameters.
