### ISSUE TITLE
[BUG] Trying to send email via Azure Communication Service and get a AADSTS65002 when using DefaultTokenCredentials.

### ISSUE THREAD

**Issue by erikrenaud** [Azure/azure-sdk-for-net#35816]
### Library name and version

Azure.Communication.Email 1.0.0

### Describe the bug

p.s. everything works if i use the connection string with key.

When trying to authenticate use DefaultTokenCredentials (which resolves to AZ CLI Auth), i get 
```
AuthenticationFailedException: Azure CLI authentication failed due to an unknown error. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/azclicredential/troubleshoot ERROR: AADSTS65002: Consent between first party application '04b07795-8ddb-461a-bbee-02f9e1bf7b46' and first party resource '632ec9eb-fad7-4cbd-993a-e72973ba2acc' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.

Trace ID: 04bbb4fb-50c8-4444-aac8-1c0068440500

Correlation ID: b9689670-8f28-4b3e-a96a-28781a3b6d03

Timestamp: 2023-04-25 19:59:32Z
To re-authenticate, please run:
az login --scope https://communication.azure.com//.default
```

My code is csharp:
``` cs
builder.Services.AddAzureClients(azureBuilder => {
  azureBuilder.UseCredential(new DefaultAzureCredential());
  azureBuilder.AddEmailClient(new Uri("https://resourceName.communication.azure.com/"));

});
```

I can prove that my account has access to the service as i get valid information (and can even get the keys if i try)
``
az communication show --resource-group "LocalDEV" --name "resourceName"
``

What am i doing wrong ? 
1 - I would like myself and devs to be able to work on their local development machines
2 - I want to ensure that i can deploy and that the ManagedIdentity will work correctly once hosed on Azure App Service.
3 - DefaultTokenCredential work correctly to integrate KeyVault and Azure App Conifugration using Managed Identities AND local development.

### Expected behavior

p.s. everything works if i use the connection string with key.

When trying to authenticate use DefaultTokenCredentials (which resolves to AZ CLI Auth), i get 
```
AuthenticationFailedException: Azure CLI authentication failed due to an unknown error. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/azclicredential/troubleshoot ERROR: AADSTS65002: Consent between first party application '04b07795-8ddb-461a-bbee-02f9e1bf7b46' and first party resource '632ec9eb-fad7-4cbd-993a-e72973ba2acc' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.

Trace ID: 04bbb4fb-50c8-4444-aac8-1c0068440500

Correlation ID: b9689670-8f28-4b3e-a96a-28781a3b6d03

Timestamp: 2023-04-25 19:59:32Z
To re-authenticate, please run:
az login --scope https://communication.azure.com//.default
```

My code is csharp:
```
builder.Services.AddAzureClients(azureBuilder => {
  azureBuilder.UseCredential(new DefaultAzureCredential());
  azureBuilder.AddEmailClient(new Uri("https://resourceName.communication.azure.com/"));

});
```

I can prove that my account has access to the service as i get valid information (and can even get the keys if i try)
``
az communication show --resource-group "LocalDEV" --name "resourceName"
``

What am i doing wrong ? 
1 - I would like myself and devs to be able to work on their local development machines
2 - I want to ensure that i can deploy and that the ManagedIdentity will work correctly once hosed on Azure App Service.
3 - DefaultTokenCredential work correctly to integrate KeyVault and Azure App Conifugration using Managed Identities AND local development.

### Actual behavior

DefaultTokenCredential works correctly on a local dev machine and hosted using Managed Identities.

### Reproduction Steps

``` cs
builder.Services.AddAzureClients(azureBuilder => {
  azureBuilder.UseCredential(new DefaultAzureCredential());
  azureBuilder.AddEmailClient(new Uri("https://modeloncommservices.communication.azure.com/"));
});

public class EmailSender : IEmailSender
{
  private readonly EmailClient EmailClient;
  private readonly ILogger Logger;

  public EmailSender(EmailClient emailClient, ILogger<EmailSender> logger)
  {
    this.EmailClient = emailClient;
    this.Logger = logger;
  }

  public async Task SendEmailAsync(string email, string subject, string htmlMessage)
  {
    EmailContent emailContent = new(subject)
    {
      Html = htmlMessage
    };

    EmailRecipients emailRecipients = new(
      new List<EmailAddress>()
      {
          new EmailAddress(email)
      });

    EmailMessage emailMessage = new("DoNotReply@ffffffffe.azurecomm.net", emailRecipients, emailContent);

    EmailSendOperation result = await EmailClient.SendAsync(Azure.WaitUntil.Completed, emailMessage);

    if (result.Value.Status != EmailSendStatus.Succeeded)
    {
      Logger.ErrorSendingEmail(email);
    }
  }
}
```

### Environment

Windows 11, dotnet 7

    <PackageReference Include="Azure.Communication.Email" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.6.3" />

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by erikrenaud** [comment]
> 

Hi @christothes,
I've modified the code to have only InteractiveBrowserCredential to have a proper test:
``` csharp
builder.Services.AddAzureClients(azureBuilder => {
  //azureBuilder.UseCredential(new DefaultAzureCredential());
  azureBuilder.UseCredential(new InteractiveBrowserCredential());
  azureBuilder.AddEmailClient(new Uri("https://asdf.communication.azure.com/"));
});
```

I get a similar answer from the browser tab that opens:
```
Authentication failed. You can return to the application. Feel free to close this browser tab.

Error details: error invalid_request error_description: AADSTS65002: Consent between first party application '04b07795-8ddb-461a-bbee-02f9e1bf7b46' and first party resource '632ec9eb-fad7-4cbd-993a-e72973ba2acc' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API. Trace ID: e4602311-460d-46fa-a352-b4980c542200 Correlation ID: 2b6a8c6c-e2da-4638-b6c0-7d4377172f51 Timestamp: 2023-04-26 15:14:34Z
```

Auth request was (client_id==04b07795-8ddb-461a-bbee-02f9e1bf7b46 same as Azure CLI):
```
https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?scope=https%3a%2f%2fcommunication.azure.com%2f%2f.default+openid+profile+offline_access&response_type=code&client_id=04b07795-8ddb-461a-bbee-02f9e1bf7b46&redirect_uri=http%3a%2f%2flocalhost%3a63134&claims=%7b%22access_token%22%3a%7b%22xms_cc%22%3a%7b%22values%22%3a%5b%22CP1%22%5d%7d%7d%7d&client-request-id=2b6a8c6c-e2da-4638-b6c0-7d4377172f51&x-client-SKU=MSAL.NetCore&x-client-Ver=4.53.0.0&x-client-CPU=x64&x-client-OS=Microsoft+Windows+10.0.22621&prompt=select_account&code_challenge=ucNX6FsPdo342cvmInGvQi7JubSvA70cjHZHphFqhsY&code_challenge_method=S256&state=78d6c490-1f75-4a55-b171-442bfe8c2485a372441a-f03e-460e-92a8-6dae954557cc&client_info=1&sso_nonce=AwABAAEAAAACAOz_BQD0_2HejS9RJkz6uy3vEAo6mK7Gy1PAsRXATZdilqo_bNiSBh0yc7lSjtVr3mKvVrdcHDs3GT6Mwm-4_1isa8hU-cUgAA&mscrid=2b6a8c6c-e2da-4638-b6c0-7d4377172f51
```


This is me trying to run this on my local dev box.
Would this happen also using managed identities ? i.e. If my AppService is requesting access to KeyVault, as long as I've given access to the Managed Identity in KeyVault, a token will be emitted. I haven't set any scopes like https://communication.azure.com for my access to KeyVault to function.

**Comment by christothes** [comment]
Oh, sorry I neglected to mention that you also need to disable Any of the other dev credential ahead of the interactive one using the options. A quick way to test it though is to just use the `InteractiveBrowerCredential` directly.

> Would this happen also using managed identities

It shouldn't

**Comment by erikrenaud** [comment]
> Oh, sorry I neglected to mention that you also need to disable Any of the other dev credential ahead of the interactive one using the options. A quick way to test it though is to just use the `InteractiveBrowerCredential` directly.

That's why i switched to InteractiveBrowserCredential instead of DefaultTokenCredential, ensuring only that code path works.
After github analysis though, the same ClientID is used (Azure CLI or InteractiveBrowserCredential)

![image](https://user-images.githubusercontent.com/1238378/234629886-690d2b2f-4d99-4594-a9bf-a3ac998fb988.png)

In InteractiveBrowserCredential:
![image](https://user-images.githubusercontent.com/1238378/234629995-73c0dcc7-e5ea-4666-9b52-8554f06457a4.png)


What i'll do to advance is "trust" this works with managed identities and use a connection string with key in dev...

**Comment by christothes** [comment]
Thanks for confirming. I had forgotten that we use the same ClientId there!

Another option, if you want to keep your code on `DefaultAzureCredential`, is to use a [service principal](https://learn.microsoft.com/en-us/azure/developer/java/sdk/identity-service-principal-auth). You can get the ClientSecretCredential via setting the [environment variables](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#environment-variables) for the `EnvironmentCredential`

**Comment by erikrenaud** [comment]
> Another option, if you want to keep your code on `DefaultAzureCredential`, is to use a [service principal](https://learn.microsoft.com/en-us/azure/developer/java/sdk/identity-service-principal-auth). You can get the ClientSecretCredential via setting the [environment variables](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#environment-variables) for the `EnvironmentCredential`

Yeah - i'd rather not get into service principals for devs doing their work if i can.

What are the next steps ? is the proper resolution to add the missing scope to the Azure CLI Client id ? or is modifying the docs so that the next person doesn't spend too much time on this ?

**Comment by erikrenaud** [comment]
> Another option, if you want to keep your code on `DefaultAzureCredential`, is to use a [service principal](https://learn.microsoft.com/en-us/azure/developer/java/sdk/identity-service-principal-auth). You can get the ClientSecretCredential via setting the [environment variables](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#environment-variables) for the `EnvironmentCredential`

Yeah - i'd rather not get into service principals for devs doing their work if i can.

What are the next steps ? is the proper resolution to add the missing scope to the Azure CLI CLient id ? or is modifying the docs so that the next person doesn't spend too much time on this ?

**Comment by christothes** [comment]
I think the best way to get this enabled for Azure CLI is to create an issue [here](https://github.com/Azure/azure-cli/issues) requesting that the CLI first party application adds Azure Communication Service to the list of pre-authorized resources.
