### ISSUE TITLE
[Text Translation] Add support for mocking models via a model factory

### ISSUE THREAD

**Issue by joseharriaga** [Azure/azure-sdk-for-net#35819]
I noticed that the client library currently does not have a model factory. Here is more information about what this is and the requirements involved as per our guidelines:
🔗 [.NET Azure SDK Design Guidelines | Azure SDKs](https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-mocking)

The expectation is that the model factory is automatically generated by the emitter, but I see that there is this open issue in the autorest.csharp repo:
🔗 [Generate ModelFactory for mocking, from Cadl · Issue #2461 · Azure/autorest.csharp (github.com)](https://github.com/Azure/autorest.csharp/issues/2461)

In other words, this is not specific to Text Translation; all the client libraries generated from TypeSpec (e.g. OpenAI) are on the same boat. So I talked with @m-nash, and we discussed the possibility of hand-writing the model factory versus auto-generating it once the issue mentioned above is resolved. His recommendation below:
> "I think we can hand write this but probably shouldn't GA with the model factory until the generator handles it so we don't accidentally end up with incorrect signatures.  The dependent issues linked in [issue #2461](https://github.com/Azure/autorest.csharp/issues/2461) deal with some consolidation work in model generation that is happening right now so that there are no differences for each library type.  Once this is done we will get model factory generation for free.  This work is changing the signatures which is where we could run into issues for GA."

**Comment by m-nash** [comment]
@ArcturusZhang I believe this is dependent on your consolidation work you are doing can you list what issues need to go in first and track this as closure once its all done?

**Comment by pallavit** [comment]
As part of this are we updating all current DPG SDKs too?

**Comment by m-nash** [comment]
@pallavit yes turning this on should be for everyone.  I believe only DPG is off right now due to the consolidation work will let @ArcturusZhang reply with details.

**Comment by ArcturusZhang** [comment]
@joseharriaga Hi sorry I just notice this issue.
Now `Azure.AI.Translation.Text` has a model factory. Therefore I believe this has been resolved.

**Comment by joseharriaga** [comment]
You're correct, @ArcturusZhang! Thank you!
