### ISSUE TITLE
[BUG] RequestUriBuilder is not escaping `:` when executing on net461

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-net#35828]
### Library name and version

Azure.Core

### Describe the bug

When I am using the following code:
```csharp
var uri = new RequestUriBuilder();
uri.Reset(_endpoint);
uri.AppendPath("something");
uri.AppendQuery("datetime", "2022-12-19T11:12:12.0000000Z", true);
```
and when it is running on net461 target, we will get this uri as a result:
```
http://localhost/something?datetime=2022-12-19T11:12:12.0000000Z
```
and when the same code running on net6, we will get the following:
```
http://localhost/something?datetime=2022-12-19T11%3A12%3A12.0000000Z
```

Test results could be check [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2729007&view=logs&j=b5cdfb1e-c180-561f-918e-a169e451719e&t=4ded98b8-54f4-593a-2473-d87ca78efa64) on the failure of `AppendQuery_DateTimeOffsetValue`

### Expected behavior

We should get the same uri for net6 and net461 with the `:` escaped.

### Actual behavior

The character `:` is not escaped.

### Reproduction Steps

Reproduction code included in the description above.

**Comment by jsquire** [comment]
@annelo-msft:  Would you please triage and cost this?

**Comment by annelo-msft** [comment]
Thanks for filing this, @ArcturusZhang!

Can you help us understand -- is this something you discovered in tests, or is it a known issue with an existing SDK?

**Comment by ArcturusZhang** [comment]
> Thanks for filing this, @ArcturusZhang!
> 
> Can you help us understand -- is this something you discovered in tests, or is it a known issue with an existing SDK?

It is something I discovered in tests. The tests are here: https://github.com/Azure/autorest.csharp/pull/3317

**Comment by jsquire** [comment]
The `net461` platform has reached end of life and is no longer supported.  As there has been no developer feedback or bug reports related to this issue, closing.
