### ISSUE TITLE
Deploy Using ARM Template in DF

### ISSUE THREAD

**Issue by sazeesha** [Azure/azure-sdk-for-net#3582]
I am using [this](https://github.com/Azure-Samples/resources-dotnet-deploy-using-arm-template-with-progress/blob/master/Program.cs) as a reference to execute ARM templates in DogFood

Here is my code snippet:

 var credentials = SdkContext.AzureCredentialsFactory.FromFile(Environment.GetEnvironmentVariable("AZURE_AUTH_LOCATION", EnvironmentVariableTarget.User));

 var groupName = "myFluentResourceGroup";
 var location = Region.USWest;
 var resourceGroup = azure.ResourceGroups.Define(groupName).WithRegion(location)
                .Create();

// this is my.azureauth
subscription=########-####-####-####-############
client=########-####-####-####-############
tenant=########-####-####-####-############
managementURI=https://management.core.windows.net/
baseURL=https://api-dogfood.resources.windows-int.net/
authURL=https://login.windows-ppe.net/
graphURL=https://graph.ppe.windows.net/

Exception: 
{"The access token has been obtained from wrong audience or resource 'https://api-dogfood.resources.windows-int.net/'. It should exactly match (including forward slash) with one of the allowed audiences 'https://management.core.windows.net/','https://management.azure.com/'."}

**Comment by hovsepm** [comment]
Fixed in Fluent v.1.2
