### ISSUE TITLE
[QUERY] AddServiceBusClient with managed identity

### ISSUE THREAD

**Issue by Dorus** [Azure/azure-sdk-for-net#35836]
### Library name and version

Azure.Messaging.ServiceBus 7.13.1

### Query/Question

I want to use ASP.NET Core dependency injection with a Managed Identity.

In the documentation there are two relevant examples:

> Then register the client in the Startup.ConfigureServices method:
> 
> ```CSharp
> public void ConfigureServices(IServiceCollection services)
> {
>     services.AddAzureClients(builder =>
>     {
>         builder.AddServiceBusClient(Configuration.GetConnectionString("ServiceBus"));
>     });
>   
>     services.AddControllers();
> }
> ```
And
> Authenticating with Azure.Identity
> The [Azure Identity library](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity/README.md) provides easy Azure Active Directory support for authentication.
> 
> ```CSharp
> // Create a ServiceBusClient that will authenticate through Active Directory
> string fullyQualifiedNamespace = "yournamespace.servicebus.windows.net";
> await using var client = new ServiceBusClient(fullyQualifiedNamespace, new DefaultAzureCredential());
> ```

However, `builder.AddServiceBusClient` does not take a fullyQualifiedNamespace, using one there gives

> System.FormatException: The connection string could not be parsed; either it was malformed or contains no well-known tokens.

This is how my code currently looks like:

```C#
      .AddAzureClients(builder => builder
        .AddServiceBusClient(fullyQualifiedNamespace)
        .WithCredential(new DefaultAzureCredential())
      );
```

### Environment

ASP.NET Core 6.0.15
Visual studio 17.5.3

**Comment by Dorus** [comment]
Ah, i got it working with config setting `ServiceBusConnection:fullyQualifiedNamespace` and `AddServiceBusClient(c.Configuration.GetSection("ServicebusConnection"))`.

```CSharp
      .AddAzureClients(builder => builder
        .AddServiceBusClient(c.Configuration.GetSection("ServicebusConnection"))
        .WithCredential(new DefaultAzureCredential())
      );
```

Possibly this could be documented better?
https://www.nuget.org/packages/Azure.Messaging.ServiceBus/

**Comment by jsquire** [comment]
Hi @Dorus.   Thank you for reaching out and we regret that you're experiencing difficulties.   The builder extension that you're looking for is `AddServiceBusClientWithNamespace`.   A full example looks like:

```csharp
var fullyQualifiedNamespace = "yournamespace.servicebus.windows.net";

public void ConfigureServices(IServiceCollection services)
{
    services.AddAzureClients(builder =>
    {
        // This will register the ServiceBusClient using the default credential.
        builder.AddServiceBusClientWithNamespace(fullyQualifiedNamespace);

        // By default, DefaultAzureCredential is used, which is likely desired for most
        // scenarios. If you need to restrict to a specific credential instance, you could
        // register that instance as the default credential instead.
        builder.UseCredential(new ManagedIdentityCredential());
    });
  
    services.AddControllers();
}
```

More information can be found in the [README](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/README.md#registering-with-aspnet-core-dependency-injection).   As this was recently added to the README, publishing to MS Docs hasn't taken place yet, but the same information should be available in the [Overview](https://learn.microsoft.com/dotnet/api/overview/azure/messaging.servicebus-readme?view=azure-dotnet) when the Service Bus package is next released.
