### ISSUE TITLE
[BUG] Custom Attributes on Metrics sent from Open Telemetry not appearing in App Insights

### ISSUE THREAD

**Issue by joebeernink** [Azure/azure-sdk-for-net#35844]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.10

### Describe the bug

Adding custom attributes to Metrics doesn't actually route the Attributes to Application Insights with the metrics
See github project here: https://github.com/joebeernink/DemoOpenTelemetry

``` csharp
                .WithMetrics(builder => builder
                    .AddAspNetCoreInstrumentation()
                    .AddHttpClientInstrumentation()
                    .AddConsoleExporter()
                    .AddAzureMonitorMetricExporter(o =>
                    {
                        o.ConnectionString = appInsightsConnection;
                    })
                    .ConfigureResource(resource =>
                    {
                        resource.AddService(DiagnosticsConfig.ServiceName);
                        resource.AddAttributes(customerInstanceConfig.Values);
                    }))
```                    
   where the customerInstanceConfig is:
  
``` csharp
       public class CustomerInstanceConfigurationOptions
    {
        public string EnvironmentShortName { get; set; } = string.Empty;

        public string RegionShortName { get; set; } = string.Empty;

        public string StampName { get; set; } = string.Empty;

        public string CustomerId { get; set; } = string.Empty;

        public string CustomerInstanceName { get; set; } = string.Empty;

        public string Name { get; set; } = string.Empty;

        public string DnsSubDomain { get; set; } = string.Empty;

        public IEnumerable<KeyValuePair<string, object>> Values
        {
            get
            {
                var kvps = new List<KeyValuePair<string, object>> {
                            new("EnvironmentShortName", EnvironmentShortName),
                            new("RegionShortName", RegionShortName),
                            new("StampName", StampName),
                            new("CustomerId", CustomerId.ToString()),
                            new("CustomerInstanceName", CustomerInstanceName),
                            new("Name", Name),
                            new("DnsSubDomain", DnsSubDomain)
                        };
                return kvps;
            }
```
     And the values loaded from the appsettings.json are:
  
``` json  
       "CustomerInstanceConfiguration": {
    "EnvironmentShortName": "dev",
    "RegionShortName": "wus2",
    "StampName": "01",
    "CustomerId": "joeb",
    "CustomerInstanceName": "001",
    "Name": "dev-wus2-01-joeb-001",
    "DnsSubDomain": "joeb001"
  }
```
In the values received by AI, cannot filter or group by these attributes:
![image](https://user-images.githubusercontent.com/3885965/234676225-22b52951-44a4-4381-a6a4-64e5baafdfd6.png)

### Expected behavior

The attributes should show up in Application insights as part of the OpenTelemetry.Instrumentation.AspNetCore metrics and OpenTelemetry.Instrumentation.Http metrics

### Actual behavior

Attributes are missing.

### Reproduction Steps

See github repo: https://github.com/joebeernink/DemoOpenTelemetry

### Environment

 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.201\

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  6.0.408 [C:\Program Files\dotnet\sdk]
  7.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by navba-MSFT** [comment]
@joebeernink This issue is a duplicate and the same ask is being tracked in https://github.com/Azure/azure-sdk-for-net/issues/35487 . Follow the PR https://github.com/Azure/azure-sdk-for-net/pull/36027 and https://github.com/Azure/azure-sdk-for-net/pull/36063

**Comment by joebeernink** [comment]
The work items seem to be closed, but the functionality still doesn’t work for metrics as of the 1.5.0-beta release of the OpenTelemetry SDK. So is there another version coming with the fix included?

 

Thanks
