### ISSUE TITLE
[QUERY] How can I include the IP in the trace?

### ISSUE THREAD

**Issue by Baltima** [Azure/azure-sdk-for-net#35845]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.10

### Query/Question

When setting the tag `http.client_ip`, I understand that it is not sent directly to Application Insights but the tag `ai.location.ip` is set on the `TelemetryItem`. In this case, the IP is not logged. Is there any way to use the tag `http.client_ip` and to have the IP in the final trace?

**Comment by vishweshbankwar** [comment]
https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-enable?tabs=net#set-the-user-ip

**Comment by Baltima** [comment]
Thank you @vishweshbankwar

I tried with the following enricher:

```cs
internal class Enricher : BaseProcessor<Activity>
{
    private readonly IHttpContextAccessor _httpContextAccessor;
 
    public Enricher(IHttpContextAccessor httpContextAccessor)
    {
        _httpContextAccessor = httpContextAccessor;
    }

    public override void OnEnd(Activity data)
    {
        if (data.Kind == ActivityKind.Server)
        {
            data.AddTag("http.client_ip", _httpContextAccessor.HttpContext!.Request.Headers["X -Forwarded-For"].ToString());
            data.AddTag("client_ip", _httpContextAccessor.HttpContext!.Request.Headers["X-Forwarded-For"].ToString());
        }
    }
}
```

And I set  `DisableIpMasking` = `true` for my Application Insights. Unfortunately, only `client_ip` is available as a custom property.

**Comment by vishweshbankwar** [comment]
@Baltima  `http.client_ip` should be populated on client_IP field on request table log, is it still showing 0.0.0.0?
