### ISSUE TITLE
[BUG] BlobClient trimming extra slashes, GetProperties() throws 404 due to trimmed slash

### ISSUE THREAD

**Issue by brethompson309** [Azure/azure-sdk-for-net#35868]
### Library name and version

Azure Storage Blob 12.15.1

### Describe the bug

When running the following:
var blob = container.GetBlobClient(blobName); 
blob.GetProperties(); 

We hit an exception on GetProperties();
The Uri created by GetBlobceClient is: 
"https://test.blob.core.windows.net/test/this/reg/11/111/111/22/33/test.txt"

When we really want due to our formatting:
"https://test.blob.core.windows.net/test//this/reg/11/111/111/22/33/test.txt"

the extra "/" gets trimmed off

Thanks in advance for looking into this! 

### Expected behavior

The created Blobclient with blobname should have the Uri with the extra slash "/". Making it possible for GetProperties to find the blob with correct amount of slashes. 

### Actual behavior

The Blobclient is trimming that extra slash, and when GetProperties is called the blob is not found even though it exists.

### Reproduction Steps

Have a blob with similar Uri of :"https://test.blob.core.windows.net//test/11/22/33/test.txt"
Do 
var blob =container.GetBlobClient(blobName);
blob.GetProperties();

try GetProperties and see if 404 is thrown. 

### Environment

Visual Studio 2022

**Comment by navba-MSFT** [comment]
@brethompson309 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@brethompson309 Firstly, Could you please confirm which of the below blob uri with // (double slash) are you using ?

Uri 1: "https://test.blob.core.windows.net//test/11/22/33/test.txt"
Uri 2: "https://test.blob.core.windows.net/test//11/22/33/test.txt"

If it is Uri 1, then I am unable to create a container name with "/" in it. See the [naming convention for containers](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names). Container name cannot start with a slash ( / ).

If it is Uri 2, then did you try using the `TrimBlobNameSlashes` ?

[TrimBlobNameSlashes ](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclientoptions.trimblobnameslashes?view=azure-dotnet#azure-storage-blobs-blobclientoptions-trimblobnameslashes)| Whether to trim leading and trailing slashes on a blob name when using GetBlobClient(String) and similar methods. Defaults to true for backwards compatibility.
-- | --

```
       // Create a BlobServiceClient object from the connection string
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString, new BlobClientOptions() { TrimBlobNameSlashes = false }); ;

            // Get a reference to the container
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);

            // Get a reference to the blob
            BlobClient blobClient = containerClient.GetBlobClient(blobName);

            // Retrieve the properties of the blob
            var blobProperties = blobClient.GetProperties();
```

**Comment by brethompson309** [comment]
Hi @navba-MSFT,

Thanks for looking into this. 

We are using Uri 1: "https://test.blob.core.windows.net//test/11/22/33/test.txt"

**Comment by navba-MSFT** [comment]
@brethompson309 If it is Uri 1, then I am unable to create a container name with "/" in it. See the [naming convention for containers](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names). Container name cannot start with a slash ( / ).

May I know how did you create a container with / in name ?

**Comment by brethompson309** [comment]
Hey @navba-MSFT please see updated Uri: We are using"https://test.blob.core.windows.net/test//this/reg/11/111/111/22/33/test.txt"

I am not sure how it was created, this is legacy.

**Comment by navba-MSFT** [comment]
@brethompson309 Thanks for clarifying. Did you try setting the TrimBlobNameSlashes as false ?

[TrimBlobNameSlashes](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclientoptions.trimblobnameslashes?view=azure-dotnet#azure-storage-blobs-blobclientoptions-trimblobnameslashes) | Whether to trim leading and trailing slashes on a blob name when using GetBlobClient(String) and similar methods. Defaults to true for backwards compatibility.
-- | --

```
    // Create a BlobServiceClient object from the connection string
            BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString, new BlobClientOptions() { TrimBlobNameSlashes = false }); ;

            // Get a reference to the container
            BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);

            // Get a reference to the blob
            BlobClient blobClient = containerClient.GetBlobClient(blobName);

            // Retrieve the properties of the blob
            var blobProperties = blobClient.GetProperties();</code></pre></div><!--EndFragment-->
```

**Comment by brethompson309** [comment]
Hey @navba-MSFT thanks for your help! 

I updated to the latest version of Azure.Storage.Blobs and set TrimBlobNameSlashes as false. it's working now! Thanks so much
