### ISSUE TITLE
[BUG] Unable to call GetRoleAssignments in Mooncake

### ISSUE THREAD

**Issue by 263613093** [Azure/azure-sdk-for-net#35890]
### Library name and version

1.0.1

### Describe the bug

Lib：Azure.ResourceManager.Authorization 
Version ：1.0.1
Class：RoleAssignmentCollection 
Method：CreateOrUpdateAsync
Arm Environment：AzureChina 

Exception：
Azure.RequestFailedException:“Service request failed.
Status: 405 (Method Not Allowed)

Content:
{"message":"The requested resource does not support http method 'PUT'."}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-request-id: fe407f1d-4848-47cb-951f-465a7a5961be
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
Set-Cookie: REDACTED
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Date: Fri, 28 Apr 2023 03:15:47 GMT
Allow: REDACTED
Content-Length: 72
Content-Type: application/json; charset=utf-8
Expires: -1

### Expected behavior

Can access the api success

### Actual behavior

can't work and throw an exception

### Reproduction Steps

1，set armClient environment to azureChina
2，GetRoleAssignments from a subscription
3，add a new role assignments
4，invoke createorupdate method

### Environment

AzureChina

**Comment by live1206** [comment]
@263613093
I tried it out in mooncake environment with below code, it worked fine for me. 
Could you verify you are still encountering the issue?
Please let me know if you think I am missing any information from your description.
```csharp
var client = new ArmClient(
    credential,
    subscriptionId, 
    new ArmClientOptions() 
    {
        Environment = ArmEnvironment.AzureChina,
    });
var defaultSub = await client.GetDefaultSubscriptionAsync();
var rg = (await defaultSub.GetResourceGroups().GetAsync(resourceGroupId)).Value;
var collection = rg.GetRoleAssignments();
var content = new RoleAssignmentCreateOrUpdateContent(ResourceIdentifier.Parse(roleId), Guid.Parse(userId))
{
    PrincipalType = RoleManagementPrincipalType.User,
};
var roleAssignmentName = Guid.NewGuid().ToString();
var roleAssignment = await collection.CreateOrUpdateAsync(WaitUntil.Completed, roleAssignmentName, content);
```
