### ISSUE TITLE
Event Grid Topic subscribed by azure function app c#

### ISSUE THREAD

**Issue by raiajithkumarr** [Azure/azure-sdk-for-net#35891]
### Library name and version

Latest version

### Query/Question

Here we want to understand behavior of Event grid topic >> when we subscribe Event grid topic with azure function app and while processing azure function app side unhandled exception thrown whether that message will be retired internally ?
if not what will happen to that message.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @raiajithkumarr,
Please see [this doc](https://github.com/Azure/azure-sdk-for-net/issues/35891) which describes the retry behavior when using Azure resources for the endpoint type.

**Comment by raiajithkumarr** [comment]
Could you please tell us here how to get at what delivery attempts it succeeded ?

For example while moving blob item due to too many requests it failed and after certain retries for at 5 or 6 th retry it succeeded

Now I want to get that delivery count please help here

**Comment by JoshLove-msft** [comment]
The deliveryAttempt should be included as a request header when the event is delivered. If you are using CloudEvent I believe it is in the CloudEvent itself. If you are using EventGridEvent schema, I don't think it is currently possible to access this property via the Function trigger - https://github.com/Azure/azure-sdk-for-net/issues/28658
