### ISSUE TITLE
Event Grid: Is there any viewer to view failed events for analysis

### ISSUE THREAD

**Issue by raiajithkumarr** [Azure/azure-sdk-for-net#35900]
### Library name and version

latest version

### Query/Question

Hi Team,
Is there any viewer to see failed events for further analysis purpose.
How to re-trigger dead letter events through azure function app ?

Like published events we can see by using this resource : https://learn.microsoft.com/en-us/samples/azure-samples/azure-event-grid-viewer/azure-event-grid-viewer/

**Comment by JoshLove-msft** [comment]
Deadlettered events will be delivered to your configured blob container. You can create an Event Grid Subscription on your storage account that listens for Blob Created events and deliver these events to either a webhook (as in the Event Grid Viewer example) or any other endpoint type. Here is a sample I found that shows how to [create Event Grid Subscription](https://github.com/Azure-Samples/event-grid-dotnet-handle-deadlettered-events/blob/master/event-subscription-with-dead-lettering/Program.cs) that use DeadLettering as well as demonstrating how to use the [EventGridTrigger in a webhook](https://github.com/Azure-Samples/event-grid-dotnet-handle-deadlettered-events/blob/master/function-app/ProcessDeadLetterFunction.cs) to listen to these events. Note you can also use the EventGridTrigger directly in an Azure Function which would mean you wouldn't need to handle the [handshake](https://github.com/Azure-Samples/event-grid-dotnet-handle-deadlettered-events/blob/master/function-app/WebhookSubscriptionFunction.cs) yourself.

**Comment by raiajithkumarr** [comment]
Hi Team,
Want to understand dead letter processing.
I have configured dead letter processing to azure blob storage account.
While doing analysis I observed that dead letter file content is look like below and it is array.

What is the meaning of array here is there any chance of multiple values exists inside array ?


[
    {
        "id": "ae961b92-d721-4912-9d1d-a7348f3219e7",
        "eventTime": "2023-04-28T11:07:54.9413090Z",
        "eventType": "Example.EventType",
        "dataVersion": "1.0",
        "metadataVersion": "1",
        "topic": "/subscriptions/XXXXX-XXXX-XXXXX/resourceGroups/TEST-RG/providers/Microsoft.EventGrid/topics/demoevntgrid",
        "subject": "ExampleEventSubject",
        "deadLetterReason": "MaxDeliveryAttemptsExceeded",
        "deliveryAttempts": 11,
        "lastDeliveryOutcome": "GenericError",
        "publishTime": "2023-04-28T11:07:57.0853461Z",
        "lastDeliveryAttemptTime": "2023-04-28T21:59:02.9106808Z",
        "data": "Running sample and this is the event data 28-04-2023 11:07:54"
    }
]

**Comment by JoshLove-msft** [comment]
Event Grid [defaults to sending one event in array](https://learn.microsoft.com/en-us/azure/event-grid/delivery-and-retry#output-batching), but can be configured to use batching.

Any events that you receive would represent events that have already moved to the DeadLetterQueue, so I'm not sure what you mean by there being a possibility of partial success.
