### ISSUE TITLE
Is it a fluent SDK bug? Or a doc bug? additionalUnattendContent

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#3591]
In Azure docs, at https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/virtualmachines-create-or-update , the example given is 

```
"additionalUnattendContent": {      
        "pass":"oobesystem",    
        "component":"Microsoft-Windows-Shell-Setup",    
        "settingName":"FirstLogonCommands|AutoLogon",    
        "content":"<XML unattend content>"    
      }    
```

that suggests the type of additionalUnattendContent property is 'object' but I find that the object model for the additionalUnattendContent is actually array in the SDK (i.e. `List<AdditionalUnattendContent>`)

Which is correct?

**Comment by TimLovellSmith** [comment]
Given the implementation of https://github.com/Azure/azure-powershell/blob/bbe5ee957de07032bcf7f9062bba91cceee62565/src/ResourceManager/Compute/Commands.Compute/VirtualMachine/Config/AddAzureVMAdditionalUnattendContentCommand.cs
I wonder if maybe it is the documentation which is in error, not really sure though.

**Comment by anuchandy** [comment]
`WindowsConfiguration.additionalUnattendedContent` is an array, refer the API spec [here](https://github.com/Azure/azure-rest-api-specs/blob/current/specification/compute/resource-manager/Microsoft.Compute/2017-03-30/compute.json#L4173). Probably it is either a doc error or it is based on older compute api version which supports only one config.
