### ISSUE TITLE
LRO for PATCH are unhandled under 201

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3592]
PATCH LRO that returns 201 (can have Async or Location header) are currently not supported.
We need to support this moving forward.

Cost: 2

**Comment by ScottHolden** [comment]
Looks like the EventGrid EventSubscription Update action is an example of this:

`Microsoft.Rest.Azure.CloudException: 'Unexpected polling status code from long running operation 'Created' for method 'PATCH'.'`

**Comment by ScottHolden** [comment]
Created https://github.com/Azure/azure-sdk-for-net/pull/3601

**Comment by shahabhijeet** [comment]
This change is available in 3.3.10 version of Microsoft.Rest.ClientRuntime.Azure
