### ISSUE TITLE
[FEATURE REQ] Microsoft.Azure.WebJobs - add more control to BlobTrigger

### ISSUE THREAD

**Issue by Radamonas** [Azure/azure-sdk-for-net#35938]
### Library name

Microsoft.Azure.WebJobs.Extensions.Storage.Blobs

### Please describe the feature.

I would like to ask to expand current BlobTrigger functionality. As this trigger creates queue and mechanism to publish messages once file is created in blob storage it would be useful to have control over:
* source queue name;
* message time to live, as currently it is set to default of 7 days.

Use case:
* currently we have two functions which share same business logic within one function app, both of those functions are using blob trigger (monitoring two different blob containers), but as those functions are within same function app they share same queue which is populated once the file is pushed to one of two blob containers, therefore we are not able to monitor the depth of the queue for each function. So it would be useful to have control over queue name per each blob trigger.
* as one of those two functions has lower priority in data processing, and it would be processing (reapplying historical data)  bigger data sets which can be processed within a longer period of time than seven days, so it would be useful to have control over message time to live setup for each blob trigger.

**Comment by PramodValavala-MSFT** [comment]
@Radamonas Thanks for the feedback! You can already achieve this today using [Event Grid](https://learn.microsoft.com/en-us/azure/azure-functions/event-grid-how-tos?tabs=v2%2Cportal), which even for regular Blob Trigger use cases might be a better approach as described [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-blob-trigger?tabs=python-v2%2Cin-process).

With this approach, you would have to set up the following
1. [Create an Event Subscription for your Storage Account](https://learn.microsoft.com/en-us/azure/event-grid/blob-event-quickstart-portal)
2. Route events to [Service Bus](https://learn.microsoft.com/en-us/azure/event-grid/handler-service-bus) or [Storage Queues](https://learn.microsoft.com/en-us/azure/event-grid/handler-storage-queues)
3. Your functions themselves would listen directly on [Service Bus](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-service-bus-trigger) or [Storage Queues](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue-trigger).

This approach gives you the benefit of decoupling the storage account details from your function app code, both allowing you to update storage account / container you are listening to and allowing you to subscribe to multiple storage accounts / containers.
