### ISSUE TITLE
So I have the following code from the PayPalIPN php file. When running a test submit in sandbox mode, with error reporting on, I get an error. IPN block of code:

### ISSUE THREAD

**Issue by foode222** [Azure/azure-sdk-for-net#35935]
So I have the following code from the PayPalIPN php file. When running a test submit in sandbox mode, with error reporting on, I get an error. IPN block of code:

`        $get_magic_quotes_exists = false;
        if (function_exists('get_magic_quotes_gpc')) {
            $get_magic_quotes_exists = true;
        }
        foreach ($myPost as $key => $value) {
            if ($get_magic_quotes_exists == true && get_magic_quotes_gpc() == 1) {
                $value = urlencode(stripslashes($value));
            } else {
                $value = urlencode($value);
            }
            $req .= "&$key=$value";
        }`

Error 
`Deprecated: Function get_magic_quotes_gpc() is deprecated` 

PHP version 7.4.0+ purely because that's when it got deprecated. Any suggestions?

_Originally posted by @Flinty916 in https://github.com/paypal/ipn-code-samples/issues/160_

**Comment by jsquire** [comment]
Closing as spam.
