### ISSUE TITLE
PolicyAssignmentData does not contain properties from the latest service version

### ISSUE THREAD

**Issue by aaggarwal1990** [Azure/azure-sdk-for-net#35949]
### Library name and version

Azure.ResourceManager.Resources 2022-06-01

### Describe the bug

I am seeing PolicyAssignmentData object is not updated with latest feature being supported in Azure. I checked latest PolicyAssignment provides "resource selectors"
https://learn.microsoft.com/en-us/rest/api/policy/policy-assignments/create?tabs=HTTP#create-or-update-a-policy-assignment-with-resource-selectors

But, Azure SDK does not incorporate this feature.

### Expected behavior

PolicyAssignmentData will support "resource selectors" feature.

### Actual behavior

Currently, it is not supported through azure sdk.

### Reproduction Steps

It is a missing feature and I believe it should be treated as a bug instead of a new feature.

**Comment by m-nash** [comment]
@ArthurMa1978 I believe this is because this class is custom so didn't pick up all the new properties that exist in 2022-06-01

**Comment by ArthurMa1978** [comment]
@m-nash you are right, will fix this issue in next release

**Comment by kvs1986** [comment]
Hi Team, Looks like this request is complete? can you please confirm?

Thank you for such a quick turnaround. Really appreciate your help here.

**Comment by ArthurMa1978** [comment]
Fixed in https://www.nuget.org/packages/Azure.ResourceManager/1.6.0
