### ISSUE TITLE
[QUERY] Support providers/Microsoft.Management/getEntities

### ISSUE THREAD

**Issue by ghost** [Azure/azure-sdk-for-net#35953]
### Library name and version

Azure.ResourceManager 1.5.0

### Query/Question

In the deprecated version Microsoft.Azure.Management.ManagementGroups there is a way to send requests to this [endpoint](https://learn.microsoft.com/en-us/rest/api/managementgroups/entities/list?tabs=HTTP)

I could not find any way to do this in the new sdk [Azure.ResourceManager](https://www.nuget.org/packages/Azure.ResourceManager/).

Am I missing something or this does not exist? if it doesn't is there a way to add this to the new version of the sdk?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
We're working on this features, will let you know once it's ready.
