### ISSUE TITLE
[QUERY] Samples for Azure.MixedReality.RemoteRendering?

### ISSUE THREAD

**Issue by rohitjadhavmsft** [Azure/azure-sdk-for-net#35965]
### Library name and version

1.0.0

### Query/Question

Based on [this](https://github.com/Azure/azure-sdk-for-net/tree/main/samples#getting-started-aka-hello-world-samples) Each package folder contains a subfolder called samples with additional code samples
I dont see sample folder under package[ Azure.MixedReality.RemoteRendering](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/remoterendering/Azure.MixedReality.RemoteRendering)

Can I get some samples on how to use remoterendering sdk?

**Comment by SaurabhSharma-MSFT** [comment]
@rohitjadhavmsft We are looking into it and get back to you for any additional information.

**Comment by rohitjadhavmsft** [comment]
Thank you.

**Comment by SaurabhSharma-MSFT** [comment]
@rohitjadhavmsft Can you please check [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/remoterendering/Azure.MixedReality.RemoteRendering/tests/Samples) for the remoterendering sample. Thanks

**Comment by rohitjadhavmsft** [comment]
Sounds good. Thans you.
