### ISSUE TITLE
[DataMovement] [Storage] Renable SingleTransfer Events Check

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#35976]
https://github.com/Azure/azure-sdk-for-net/pull/35975/files#r1184385881

This line is flaking due to the test returning back a completion state and the test checking if all the single transfer events have been raised. It's possible that the completion state is triggered before all the single transfer events have been raised.

**Comment by jalauzon-msft** [comment]
Fixed with #36983
