### ISSUE TITLE
[QUERY] Where is the documentation for Azure.ResourceManager.ServiceBus?

### ISSUE THREAD

**Issue by zane-woodard-drc** [Azure/azure-sdk-for-net#35977]
### Library name and version

Azure.ResourceManager.ServiceBus 1.0.0

### Query/Question

There is next to no discoverable documentation for how to use Azure.ResourceManager.ServiceBus to perform common actions like programmatically creating topics and subscriptions.

There are more discoverable examples for how to use the deprecated library. How are we meant to use Azure.ResourceManager.ServiceBus instead of the legacy library if there's no samples or documentation for Azure.ResourceManager.ServiceBus?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @zane-woodard-drc , here are the samples https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/servicebus/Azure.ResourceManager.ServiceBus/samples/Generated/Samples.
