### ISSUE TITLE
Bug in AzureUSGovernment environment for AzureCredentialsFactory

### ISSUE THREAD

**Issue by mphacker** [Azure/azure-sdk-for-net#3598]
When using the SdkContext.AzureCredentialsFactory.FromServicePrincipal to create a credential I noticed that the AuthenticationEndpoint is incorrect when the AzureUSGovernment environment parameter is passed in.

The AuthenticationEndpoint is being generated as https://login-us.crosoftonlinmie.com it should be https://login-us.microsoftonline.com.

**Comment by hovsepm** [comment]
this is fixed by this commit - https://github.com/Azure/azure-sdk-for-net/commit/0f9c3b222d0ecf1ea6c082f0533707b3be5c56b6 . Will be shipped with the next release due EOM.
