### ISSUE TITLE
how to set these values ForwardTo, ForwardDeadLetteredMessagesTo, EnableDeadLetteringOnFilterEvaluationExceptions, UserMetadata, EnableFilteringMessagesBeforePublishing, IsAnonymousAccessible

### ISSUE THREAD

**Issue by shahbarkha** [Azure/azure-sdk-for-net#3599]
The above options used to be part of the azure service bus subscription options. They are no longer avaialible with the new library. 
Can someone please tell me on how to set the above values in the management library?

**Comment by shahabhijeet** [comment]
@dsouzaarun can you answer to the customers questions as to what has changed in the latest version.
Is there a changelog you can point the customer to?

**Comment by alexeyzimarev** [comment]
It would be great to hear something. Properties disappear and it would be great to know why and what to do.

**Comment by alexeyzimarev** [comment]
`EnableBatchedOperations` is missing too

**Comment by alexeyzimarev** [comment]
Some of these properties are clearly not supported in the new API versions, it would be nice to have some docs on this.

```
      return (version >= ApiVersion.Four || !this.InternalAvailabilityStatus.HasValue) && (version >= ApiVersion.Eight || this.InternalForwardDeadLetteredMessagesTo == null);

```

**Comment by shahbarkha** [comment]
@dsouzaarun Is there any chance this is going to be fixed in 2.0 release?

**Comment by jfggdl** [comment]
GitHubs issues https://github.com/Azure/azure-service-bus/issues/88 referred in https://github.com/Azure/azure-service-bus-dotnet/issues/255 have been closed. Questions as to if the following settings can be set seem to remain pending:

ForwardDeadLetteredMessagesTo
UserMetadata
EnableDeadLetteringOnFilterEvaluationExceptions
IsAnonymousAccessible
EnableFilteringMessagesBeforePublishing
EnableBatchedOperations
SupportOrdering

**Comment by axisc** [comment]
@shahbarkha

The below operations are still supported 
- ForwardTo
- ForwardDeadLetteredMessagesTo
- EnableDeadLetteringOnFilterEvaluationExceptions

The below operations have been deprecated because they are no longer applicable
- IsAnonymousAccessible
- UserMetadata
- EnableFilteringMessagesBeforePublishing

Please let us know if you still have questions on the same.

**Comment by tudorsibiu90** [comment]
What property can I use to add a description to a subscription, if you deprecated userMetadata?

**Comment by tudorsibiu90** [comment]
> @shahbarkha
> 
> The below operations are still supported
> 
> * ForwardTo
> * ForwardDeadLetteredMessagesTo
> * EnableDeadLetteringOnFilterEvaluationExceptions
> 
> The below operations have been deprecated because they are no longer applicable
> 
> * IsAnonymousAccessible
> * UserMetadata
> * EnableFilteringMessagesBeforePublishing
> 
> Please let us know if you still have questions on the same.

What property can I use to add a description to a subscription, if you deprecated userMetadata?
