### ISSUE TITLE
Can not update Product Policy using the Azure.ResourceManager.ApiManagement SDK

### ISSUE THREAD

**Issue by cokosharp** [Azure/azure-sdk-for-net#35997]
Hi, I have a problem with the Azure.ResourceManager.ApiManagement SDK.
If I create a product in Azure APIM and then try to update the product policy, the policy is always null. My code looks similar to this:

```
ResourceIdentifier id = ApiManagementServiceResource.CreateResourceIdentifier(_subscriptionId, _resourceGroupName, _serviceName);
ClientSecretCredential credentials = new(_tenantId, _clientId, _clientSecret);

ArmClient client = new(credentials);
ApiManagementServiceResource apimService = await client.GetApiManagementServiceResource(id).GetAsync();


ApiManagementServiceResource apimService = await GetApiManagementServiceAsync();
Response<ApiManagementProductResource> productResponse = await apimService.GetApiManagementProductAsync(subscription.ResourceId);
ApiManagementProductPolicyResource? apimPolicy = productResponse.Value.GetApiManagementProductPolicies().FirstOrDefault();
```

Next I'd call the apimPolicy.UpdateAsync method, but apimPolicy is always null.

I'm not sure how to handle it because it doesn't seem to be a way to actually create a policy if it doesn't exist.
AND, it works if I go into the Azure Portal and click the default policy for the product and save it without any changes.
Then the apimPolicy object can be used to update the policy.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@cokosharp  Thank you for your feedback, we will address this.

**Comment by HarveyLink** [comment]
Hi @cokosharp , Thank you for using Azure SDK for .NET.
The scenario you requested, please refer to those policy test codes: https://github.com/Azure/azure-sdk-for-net/blob/cebc71413b04f14dac51ea124a28ef6de0cf8511/sdk/apimanagement/Azure.ResourceManager.ApiManagement/tests/Scenario/PolicyTests.cs#L95

**Comment by cokosharp** [comment]
Thank you, the test codes look promising.
