### ISSUE TITLE
[QUERY] Does this in fact update?

### ISSUE THREAD

**Issue by bretthacker** [Azure/azure-sdk-for-net#36006]
### Library name and version

Azure.ResourceManager.Media

### Query/Question

This document says this call is to create a live output, but the method name is "CreateOrUpdateAsync". Does it in fact, update a live output and if so, can the document address this?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@bretthacker Thank you for your feedback, we will address this.
