### ISSUE TITLE
Move Managed HSM testing to regions with more capacity

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#36007]
We should try these regions: Australia East, Brazil South, France Central, Japan West. Specifically, those which might be closer like France Central. My concern is about potential timeouts, so maybe we need to increase the timeouts for test runs against MHSMs.

/cc @pallavit @vcolin7

**Comment by pallavit** [comment]
Isn't capacity a non-constant and varies significantly based on time, customer spread etc.? I agree the farther we go from US the more significant would be the perf hit/ ARM cache concerns etc. Should we consider asking the service team where they usually have capacity and use that instead?

**Comment by heaths** [comment]
Time isn't really an issue here: Managed HSMs aren't typically ephemeral like Key Vaults may be during testing. The reason we have one SDK for Managed HSM and Key Vault is because the intent was for dev teams to develop on KV but switch to the more expensive, typically long-lived Managed HSMs for production.

**Comment by heaths** [comment]
Right now, all test resource ARM templates across the language repos are provisioning to `northcentralus`:

```pwsh
# Using https://gist.github.com/heaths/cfca59e08bba514e0ba4ffc8b65db48f
Get-AzsdkItem.ps1 sdk/keyvault/test-resources.json -AsJson -v | foreach { $_.parameters.hsmLocation.defaultValue }
```
```
VERBOSE: Fetching sdk/keyvault/test-resources.json from Azure/azure-sdk-for-cpp
northcentralus
VERBOSE: Fetching sdk/keyvault/test-resources.json from Azure/azure-sdk-for-go
northcentralus
VERBOSE: Fetching sdk/keyvault/test-resources.json from Azure/azure-sdk-for-java
northcentralus
VERBOSE: Fetching sdk/keyvault/test-resources.json from Azure/azure-sdk-for-js
northcentralus
VERBOSE: Fetching sdk/keyvault/test-resources.json from Azure/azure-sdk-for-net
northcentralus
VERBOSE: Fetching sdk/keyvault/test-resources.json from Azure/azure-sdk-for-python
```

**Comment by heaths** [comment]
Based on,

```bash
az account list-locations --query '[?displayName==`France Central`] | [0]'
```

We should probably try:

1. `francecentral`
2. `brazilsouth`
3. `australiaeast`
