### ISSUE TITLE
[BUG] GetFrontDoorsAsync does not list Azure Front Door Premium resources

### ISSUE THREAD

**Issue by tomaustin700** [Azure/azure-sdk-for-net#36045]
### Library name and version

Azure.ResourceManager.FrontDoor

### Describe the bug

None of the methods within Azure.ResourceManager.FrontDoor that are used to Get Front Door Resources do not seem to work with Azure Front Door Premium. 

### Expected behavior

Should be able to call any of the methods for getting FrontDoor and any Front Door Premium resource should be listed.

### Actual behavior

Methods fail to find any Front Doors.

### Reproduction Steps

Create an Azure Front Door Premium resource within a subscription. 
Attempt to use the following code to retrieve it:
```csharp

            string subscriptionId = "subid";
            ResourceIdentifier subscriptionResourceId = SubscriptionResource.CreateResourceIdentifier(subscriptionId);
            SubscriptionResource subscriptionResource = client.GetSubscriptionResource(subscriptionResourceId);

            // invoke the operation and iterate over the result
            await foreach (FrontDoorResource item in subscriptionResource.GetFrontDoorsAsync())
            {
                // the variable item is a resource, you could call other operations on this instance as well
                // but just for demo, we get its data from this resource instance
                FrontDoorData resourceData = item.Data;
                // for demo we just print out the id
                Console.WriteLine($"Succeeded on id: {resourceData.Id}");
            }
```

### Environment

Windows 11, .NET 6 (6.0.16), Visual Studio 17.5.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@tomaustin700 Thank you for your feedback, we will address this.

**Comment by HarveyLink** [comment]
Hi @tomaustin700 , Thank you for using Azure SDK for .NET.
For the question you asked, there two packages related to `Front Door and CDN profiles`.
`Azure.ResourceManager.FrontDoor` is for `Azure Front Door Classic`.
If you need to operate on `Azure Front Door Premium`, you should use `Azure.ResourceManager.Cdn` instead, the target resource is `Microsoft.Cdn/profiles`
