### ISSUE TITLE
Issues with FromServicePrincipal and FromUser in Azure Government

### ISSUE THREAD

**Issue by milope** [Azure/azure-sdk-for-net#3605]
There seems to be an issue when I'm creating AzureCredentials for an Azure Government tenant as so:

```
var creds = SdkContext.AzureCredentialsFactory.FromServicePrincipal(
                    ConfigurationManager.AppSettings["ClientID"],
                    ConfigurationManager.AppSettings["ClientSecret"],
                    ConfigurationManager.AppSettings["TenantID"],
                    AzureEnvironment.AzureUSGovernment);
```

or 

```
var creds = SdkContext.AzureCredentialsFactory.FromUser(
                    ConfigurationManager.AppSettings["Username"],
                    ConfigurationManager.AppSettings["Password"],
                    ConfigurationManager.AppSettings["ClientID"],
                    ConfigurationManager.AppSettings["TenantID"],
                    AzureEnvironment.AzureUSGovernment);
```

The exception states as follows:

`[AdalServiceException] authority_not_in_valid_list: 'authority' is not in the list of valid addresses`

This works fine when I use the SdkContext.AzureCredentialsFactory.FromFile variant.

So after capturing a Fiddler trace, I compared the working vs non-working requests:

Non-Working (Tenant Obfuscated):

```
GET https://login.windows.net/common/discovery/instance?api-version=1.0&authorization_endpoint=https://login-us.crosoftonlinmie.com/tenant_id/oauth2/authorize HTTP/1.1
client-request-id: 65ffd307-4e61-4024-8699-132d8439471e
return-client-request-id: true
x-client-SKU: .NET
x-client-Ver: 2.28.3.860
x-client-CPU: x64
x-client-OS: Microsoft Windows NT 6.2.9200.0
Host: login.windows.net
Connection: Keep-Alive
```

Working (Tenant Obfuscated):

```
GET https://login.windows.net/common/discovery/instance?api-version=1.0&authorization_endpoint=https://login.microsoftonline.us/tenant/oauth2/authorize HTTP/1.1
client-request-id: d9470339-57c0-4ec6-b4a6-f7af65b76c54
return-client-request-id: true
x-client-SKU: .NET
x-client-Ver: 2.28.3.860
x-client-CPU: x64
x-client-OS: Microsoft Windows NT 6.2.9200.0
Host: login.windows.net
Connection: Keep-Alive

```
---------------------------------------------------
Conclusion
---------------------------------------------------

It seems that when FromServicePrincipal or FromUser is used, it sends a bad authorization_endpoint to the tenant discovery "https://login-us.crosoftonlinmie.com/tenant_id/oauth2/authorize" this should be "https://login.microsoftonline.us/tenant_id/oauth2/authorize" instead.

**Comment by hovsepm** [comment]
This is fixed by https://github.com/Azure/azure-sdk-for-net/commit/0f9c3b222d0ecf1ea6c082f0533707b3be5c56b6 commit. Will be available in the next release.
