### ISSUE TITLE
[BUG] Failing test cases

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#36058]
### Library name and version

Azure.ResourceManager.DataShare

### Describe the bug

2 test cases are failing in main https://dev.azure.com/azure-sdk/public/_build/results?buildId=2753824&view=logs&j=5c1c6b8d-4c43-56d0-23a6-720b383b6e9d&t=c0689a97-7641-5aa2-9bbf-6a4650990a4c&l=406

### Expected behavior

expected that they don't fail :-)

### Actual behavior

They fail

### Reproduction Steps

See linked pipeline

**Comment by ArcturusZhang** [comment]
Same issue is happening here in automation: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2755940&view=logs&j=43780012-0f03-502d-9415-dae360b050f8&t=58b36873-ee18-54a8-1e91-f99aabccf378
