### ISSUE TITLE
Test `HronizationSettingApiTests` is failing Core, Management pipelines

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#36059]
The core and resourcemanager pipelines are failing because of a bad test:

```
Azure.Core.TestFramework.TestRecordingMismatchException : Unable to find a record for the request PUT https://management.azure.com/subscriptions/db1ab6f0-4769-4b27-930e-01e2ef9c123c/resourceGroups/testRG-6819/providers/Microsoft.DataShare/accounts/TestAccount-3010/shares/TestShare-3721/synchronizationSettings/TestHronization-4558?api-version=2021-08-01
Header differences:
Body differences:
Request and record bodies do not match at index 94:
request: "e":"2023-05-06T00:00:00.000000"
record:  "e":"2023-02-28T00:00:00.000000"
```

You should use `Recording.Now` whenever possible for dates so they always match. If, for some reason, that is not possible you can add JSONPath exemptions to [`RecordingTestBase.JsonPathSanitizers`](https://github.com/Azure/azure-sdk-for-net/blob/aa4642b2c26cc04d3b14c98c622d5e3e4747085c/sdk/core/Azure.Core.TestFramework/src/RecordedTestBase.cs#L55)

**Comment by ArthurMa1978** [comment]
This issue has been fixed.
