### ISSUE TITLE
Reference for a very old version of Newtonsoft Json

### ISSUE THREAD

**Issue by mss37** [Azure/azure-sdk-for-net#3606]
There is a very old reference of Newtonsoft.JSON, which makes it very difficult to use with newer versions of Newtonsoft Json

![image](https://user-images.githubusercontent.com/15035699/29499019-a8ac41d2-85ff-11e7-99be-05a9a3b2f851.png)

**Comment by shahabhijeet** [comment]
@mss37 we are in process in updating these dependencies.
Can you tell me what scenarios are blocked due to this?
This helps us to prioritize this work.

**Comment by mss37** [comment]
Resolved by dependency redirection, but it was blocking me from using this package with Newtonsoft JSON package itself, or even packages which use Newtonsoft JSON package.

**Comment by shahabhijeet** [comment]
@mss37 thanks for getting back to us.
Closing.
