### ISSUE TITLE
[EventHub] ProcessorClientCeasesProcessingWhenStopping failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#36077]
EventHub nightly test runs are failing with:

> Error message
> Processor Error Surfaced (TaskCanceledException):
> Azure.Messaging.EventHubs.EventHubsException(GeneralError): An error was encountered while executing developer-provided code to process events.  On most hosts, this will fault the task responsible for partition processing, causing it to be restarted from the last checkpoint.  On some hosts, it may crash the process.  It is very strongly advised that all developer-provided code include a try/catch wrapper and ensure that no exceptions are allowed to propagate up the stack.  Exception details can be found in the inner exception. (fakeEventHub).  For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot
> 
> 
> System.Threading.Tasks.TaskCanceledException: A task was canceled.
> at Azure.Messaging.EventHubs.Core.CancellationTokenExtensions.ThrowIfCancellationRequested[T](CancellationToken instance) in D:\a_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs.Shared\src\Core\CancellationTokenExtensions.cs:line 31
> at Azure.Messaging.EventHubs.EventProcessorClient.<OnProcessingEventBatchAsync>d__68.MoveNext() in D:\a_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs.Processor\src\EventProcessorClient.cs:line 1012
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Azure.Messaging.EventHubs.Primitives.EventProcessor1.&lt;ProcessEventBatchAsync&gt;d__69.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at Azure.Messaging.EventHubs.Primitives.EventProcessor1.<>c__DisplayClass70_0.<<CreatePartitionProcessor>g__performProcessing|1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at Azure.Messaging.EventHubs.Primitives.EventProcessor1.&lt;&gt;c__DisplayClass70_0.&lt;&lt;CreatePartitionProcessor&gt;g__performProcessing|1&gt;d.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at Azure.Messaging.EventHubs.Primitives.EventProcessor1.<>c__DisplayClass70_0.<<CreatePartitionProcessor>g__performProcessing|1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.<TryStopProcessingPartitionAsync>d__91.MoveNext()
> 
> 
> 
> Stack trace
>    at Azure.Messaging.EventHubs.Tests.EventProcessorClientLiveTests.&lt;&gt;c.&lt;CreateAssertingErrorHandler&gt;b__23_0(ProcessErrorEventArgs args) in D:\a\_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs.Processor\tests\Processor\EventProcessorClientLiveTests.cs:line 1200
>    at Azure.Messaging.EventHubs.EventProcessorClient.&lt;OnProcessingErrorAsync&gt;d__69.MoveNext() in D:\a\_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs.Processor\src\EventProcessorClient.cs:line 1129
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)
>    at Azure.Messaging.EventHubs.EventProcessorClient.OnProcessingErrorAsync(Exception exception, EventProcessorPartition partition, String operationDescription, CancellationToken cancellationToken)
>    at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.&lt;&gt;c__DisplayClass92_0.&lt;InvokeOnProcessingErrorAsync&gt;b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
> 
> 1)    at Azure.Messaging.EventHubs.Tests.EventProcessorClientLiveTests.&lt;&gt;c.&lt;CreateAssertingErrorHandler&gt;b__23_0(ProcessErrorEventArgs args) in D:\a\_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs.Processor\tests\Processor\EventProcessorClientLiveTests.cs:line 1200
>    at Azure.Messaging.EventHubs.EventProcessorClient.&lt;OnProcessingErrorAsync&gt;d__69.MoveNext() in D:\a\_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs.Processor\src\EventProcessorClient.cs:line 1129
>    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)
>    at Azure.Messaging.EventHubs.EventProcessorClient.OnProcessingErrorAsync(Exception exception, EventProcessorPartition partition, String operationDescription, CancellationToken cancellationToken)
>    at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.&lt;&gt;c__DisplayClass92_0.&lt;InvokeOnProcessingErrorAsync&gt;b__0()
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2752095&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Occasional timeouts.   Does not need to be tracked.
