### ISSUE TITLE
System.MissingMethodException: Method not found: 'Void Microsoft.Azure.Management.ServiceBus.ServiceBusManagementClient..ctor(Microsoft.Rest.ServiceClientCredentials, System.Net.Http.DelegatingHandler[])'.

### ISSUE THREAD

**Issue by sakher-sawan** [Azure/azure-sdk-for-net#3607]
Context:
.NETStandard + .NET47 class lib
.NET47 unit test application.

When running the unit test I get this exception
System.MissingMethodException: Method not found: 'Void Microsoft.Azure.Management.ServiceBus.ServiceBusManagementClient..ctor(Microsoft.Rest.ServiceClientCredentials, System.Net.Http.DelegatingHandler[])'.

Tried and didn't help:
Added System.Net.Http nuget package to the unit-test application.

**Comment by shahabhijeet** [comment]
@mss37 can you provide more details as to what version of ServiceBus client are you using?
The latest sdk has the appropriate ctor
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/ServiceBus/Management.ServiceBus/Generated/ServiceBusManagementClient.cs#L205

Would help if you can the following:
1) Repro code with the version of the SDK you are using
2) Or Upgrade to the latest version and let us know if the error still repros

@dsouzaarun for visibility

**Comment by mynkow** [comment]
I get exactly the same error. I am trying to run the code in net461. I am using version 1.0.3

**Comment by abkhan5** [comment]
I am using the latest version with .net471 and class libraries. and still get this issue.

**Comment by axisc** [comment]
@sakher-sawan

Thanks for raising this issue. We've introduced management client functionality to the [Service Bus .NET Data plane SDK](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus/)

Could you give that a try and reopen this issue if you see the same errors.

I'm closing this for now.
