### ISSUE TITLE
[FormRecognizer] OutputModelsTrainedWithLabels failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#36078]
FormRecognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Timeout on getting OCR result. Timeout on processing OCR request.
> Status: 200 (OK)
> ErrorCode: 3018
> 
> 
> Additional Information:
> error-0: 3018: Timeout on getting OCR result. Timeout on processing OCR request.
> 
> 
> Content:
> {"status":"failed","createdDateTime":"2023-05-06T04:50:31Z","lastUpdatedDateTime":"2023-05-06T04:50:41Z","analyzeResult":{"version":"2.1.0","errors":[{"code":"3018","message":"Timeout on getting OCR result. Timeout on processing OCR request."}]}}
> 
> 
> Headers:
> ms-azure-ai-errorcode: REDACTED
> x-envoy-upstream-service-time: 45
> apim-request-id: 1d6ba9e7-8eca-44ee-8a85-a2d4e8284964
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> x-content-type-options: nosniff
> x-ms-region: REDACTED
> Content-Length: 246
> Content-Type: application/json; charset=utf-8
> Date: Sat, 06 May 2023 04:50:42 GMT
> 
> 
> Data:
> error-0: 3018: Timeout on getting OCR result. Timeout on processing OCR request.
> 
> 
> 
> Stack trace
>    at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 285
>    at Azure.Core.OperationInternal`1.&lt;UpdateStatusAsync&gt;d__20.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 273
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternalBase.&lt;UpdateStatusAsync&gt;d__13.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 87
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationPoller.&lt;WaitForCompletionAsync&gt;d__11.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationPoller.cs:line 85
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternalBase.&lt;WaitForCompletionResponseAsync&gt;d__19.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 212
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternal`1.&lt;WaitForCompletionAsync&gt;d__19.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 237
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.Core.OperationInternal`1.&lt;WaitForCompletionAsync&gt;d__15.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 176
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.AI.FormRecognizer.Models.RecognizeCustomFormsOperation.&lt;WaitForCompletionAsync&gt;d__15.MoveNext() in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\src\FormRecognizerClient\RecognizeCustomFormsOperation.cs:line 77
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Threading.Tasks.ValueTask`1.get_Result()
>    at Azure.AI.FormRecognizer.OperationExtensions.&lt;WaitForCompletionAsync&gt;d__3.MoveNext() in D:\a\_work\1\s\sdk\formrecognizer\Azure.AI.FormRecognizer\src\OperationExtensions.cs:line 66
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2755584&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Transient issue. Closing this as we're not seeing it anymore.
