### ISSUE TITLE
Cannot get VM Status

### ISSUE THREAD

**Issue by garybushey** [Azure/azure-sdk-for-net#3608]
When getting a VM using azure.VirtualMachines.GetById({vmID}) it does not return the VM's status and there does not appear to be anyway to get it.  Is it possible to use the REST API call below or add a variable to tell it to use it?

https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Compute/virtualMachines/{vm}?$expand=instanceView&api-version={apiVersion}
--

**Comment by anuchandy** [comment]
@garybushey you can fetch the instance view (which wraps the VM status) using below code.

```C#
var vm = azure.VirtualMachines.GetById("<vm-resource-id>");
var instanceView = vm.RefreshInstanceView();
foreach (var status in instanceView.Statuses)
{
    Console.WriteLine(status.Code + ":" + status.DisplayStatus + ":" + status.Level + ":" + status.Message + status.Time);
}
```

**Comment by garybushey** [comment]
Thanks for the code. That works but it would be great to get the information with one call. Not anything I would consider a high priority.  Thanks again

**Comment by anuchandy** [comment]
@garybushey good to know it is working. yes, we will evaluate whether we can make this as default behavior. Closing this issue now.
