### ISSUE TITLE
[BUG] ClientOptions.Retry.NetworkTimeout is ignored

### ISSUE THREAD

**Issue by seagullua** [Azure/azure-sdk-for-net#36098]
### Library name and version

Azure.Identity 1.8.2

### Describe the bug

I am getting the next error:

```
info: Azure.Core[1]
      Request [1aba6828-8759-4d40-958d-3346d567b6e2] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED
      Metadata:REDACTED
      x-ms-client-request-id:1aba6828-8759-4d40-958d-3346d567b6e2
      x-ms-return-client-request-id:true
      User-Agent:azsdk-net-Identity/1.8.2 (.NET 7.0.3; Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64)
      client assembly: Azure.Identity
info: Azure.Core[18]
      Request [1aba6828-8759-4d40-958d-3346d567b6e2] exception System.Threading.Tasks.TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:00:01. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.

```

However, I explicitly specify the timeouts:

```
builder.Services.AddAzureClients(clientBuilder =>
{
    clientBuilder.ConfigureDefaults(options =>
    {
        //options.Retry.NetworkTimeout = TimeSpan.FromSeconds(10);
    });
    
    // Add a Storage account client
    clientBuilder.AddBlobServiceClient(builder.Configuration.GetSection("AzureBlobStorage")).ConfigureOptions(
        options =>
        {
            options.Retry.NetworkTimeout = TimeSpan.FromSeconds(15);
        }
    );

    // Use DefaultAzureCredential by default
    clientBuilder.UseCredential(new DefaultAzureCredential(new DefaultAzureCredentialOptions()
    {
        Retry = { NetworkTimeout = TimeSpan.FromSeconds(10) }
    }));
});
```

A brief investigation showed that the timeout is overridden in ResponseBodyPolicy

<img width="1064" alt="Screenshot 2023-05-08 at 10 58 21 AM" src="https://user-images.githubusercontent.com/759038/236872832-2f90c6e7-a474-42b7-8154-57c36532e35e.png">

### Expected behavior

The timeout should be the same as specified in the config

### Actual behavior

The timeout is overridden for some reason.

### Reproduction Steps

Configure the project as follows

```
builder.Services.AddAzureClients(clientBuilder =>
{
    clientBuilder.ConfigureDefaults(options =>
    {
        //options.Retry.NetworkTimeout = TimeSpan.FromSeconds(10);
    });
    
    // Add a Storage account client
    clientBuilder.AddBlobServiceClient(builder.Configuration.GetSection("AzureBlobStorage")).ConfigureOptions(
        options =>
        {
            options.Retry.NetworkTimeout = TimeSpan.FromSeconds(15);
        }
    );

    // Use DefaultAzureCredential by default
    clientBuilder.UseCredential(new DefaultAzureCredential(new DefaultAzureCredentialOptions()
    {
        Retry = { NetworkTimeout = TimeSpan.FromSeconds(10) }
    }));
});
```

Call

```
var blobContainerClient = _blobServiceClient.GetBlobContainerClient(containerName);
var blobClient = blobContainerClient.GetBlobClient(blobName);
var response = await blobClient.DownloadAsync(cancellationToken: cancellationToken);
```

### Environment

.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.201/

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @seagullua - 
You should only be seeing this behavior on the inital auth attempts while `DefaultAzureCredential` attempts to discover to the IMDS endpoint as part of the `ManagedIdentityCredential`. This behavior is normal and intended to fail fast when the endpoint does not respond.

If you are not using managed identity authentication and want to avoid these errors, you can disable this in the options here:
https://github.com/Azure/azure-sdk-for-net/blob/0dbe382cb2067f5f442f3f7142b499f28264bf37/sdk/identity/Azure.Identity/src/Credentials/DefaultAzureCredentialOptions.cs#L224
