### ISSUE TITLE
[BUG] Deserializing CosmosDBAccountData throws a System.Uri.FormatException

### ISSUE THREAD

**Issue by ukachiokoli** [Azure/azure-sdk-for-net#36104]
### Library name and version

Azure.ResourceManager.CosmosDB 1.3.0

### Describe the bug

System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.CosmosDB.CosmosDBAccountData.DeserializeCosmosDBAccountData(JsonElement element)
   at Azure.ResourceManager.CosmosDB.SubscriptionResourceExtensionClient.<GetCosmosDBAccountsAsync>b__22_1(JsonElement e)
   at Azure.Core.PageableHelpers.PageableImplementation`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.Core.PageableHelpers.PageableImplementation`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()

### Expected behavior

The only Uri field I see in the CosmosDBAccountData is KeyvaultUri which is Optional, an empty string should not throw an exception. The JsonElement in question is returned directly from the GetCosmosDBAccountAsync call

### Actual behavior

an empty string causes an exception when deserializing CosmosDBAccountData

### Reproduction Steps

                SubscriptionResource subscription = armClient.GetSubscriptionResource(SubscriptionResource.CreateResourceIdentifier(subscriptionId));

                AsyncPageable<CosmosDBAccountResource> cosmosDBAccounts = subscription.GetCosmosDBAccountsAsync(cancellationToken);

                try
                {
                    await foreach (CosmosDBAccountResource cosmosDBAccount in cosmosDBAccounts)
                    {
                        if (AccountIsInRegion(cosmosDBAccount, currentRegion))
                        {
                            // do some checks here using cosmosDBAccount Data
                        }
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex, "error scanning for orphaned DB");
                }

### Environment

net 6.0 exe , Service Fabric app running on an Azure cloud test environment

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@ukachiokoli Thank you for your feedback, we will address this.

**Comment by live1206** [comment]
Fixed in main branch, waiting for a new release.

**Comment by live1206** [comment]
Fixed in [Azure.ResourceManager.CosmosDB/1.4.0-beta.2](https://www.nuget.org/packages/Azure.ResourceManager.CosmosDB/1.4.0-beta.2)
