### ISSUE TITLE
[AppConfig] Add aka.ms links from SDK exception messages to anchors in the TSG

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-net#36113]
1, Create an aks link to represent the TROUBLESHOOTING(TSG) guide
2. Use the new aks link in the common Exception type, and add it to the message.
You will find an example in Identity:
https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity/src/main/java/com/azure/identity/implementation/IdentityClientBase.java#L479
Should be similar in .NET language.

**Comment by pallavit** [comment]
@mssfang - do we have specific instances of where we want to add these to AppConfig SDK?

**Comment by mssfang** [comment]
The reference link in the issue fails off in incorrect line number as it refers to main branch and main branch changes.
```
throw LOGGER.logExceptionAsError(
                new IllegalArgumentException("Must provide client secret or client certificate path."
                    +  " To mitigate this issue, please refer to the troubleshooting guidelines here at "
                    + "https://aka.ms/azsdk/java/identity/serviceprincipalauthentication/troubleshoot"));
```

This is example of using Identity Java troubleshoot aka link, and how to use the aka link in sdk-defined exception type that  are commonly see by the external users.

**Comment by pallavit** [comment]
Is the expectation to add TSG and have all exceptions route to it, or are there specific instances where we are trying to drive consistency?

**Comment by mssfang** [comment]
AppConfig .NET SDK already has a [TROUBLESHOOTING](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/appconfiguration/Azure.Data.AppConfiguration/TROUBLESHOOTING.md) guideline. 
The nice thing to add is to use it in the necessary exception messages.

**Comment by pallavit** [comment]
Makes sense, thanks!
