### ISSUE TITLE
[BUG] Application mode is not set when updating APNs credentials on an Azure notification hub

### ISSUE THREAD

**Issue by markmuniz** [Azure/azure-sdk-for-net#36120]
### Library name and version

Azure.ResourceManager.NotificationHubs 1.0.1

### Describe the bug

The application mode (production, sandbox) does not get set when updating the APNs credentials on an Azure Notification Hub with token-based authentication. According to the documentation, this should be accomplished by setting the `Endpoint` property on the `NotificationHubApnsCredential` object to `https://api.push.apple.com:443/3/device` or `https://api.development.push.apple.com:443/3/device`, depending on the application mode the notification hub should use.

The bug is likely due to the port being excluded when serialized to JSON, since `Uri.AbsoluteUri` is being used and does not include the port if it is the default for the scheme. `443` is the default port for the HTTPS scheme, but appears to be required to update the application mode.

### Expected behavior

The application mode is set on the Azure notification hub when setting the `Endpoint` property to one of the URLs mentioned above.

### Actual behavior

The application mode is not set on the Azure notification hub. The `Endpoint` value seems to be ignored.

### Reproduction Steps

The bug can be recreated with the snippet below. This snippet assumes you are accessing a notification hub from a notification hub namespace.
```
NotificationHubResource hubResource = await notificationHubNamespace.GetNotificationHubs().GetAsync(hub);
await hubResource.UpdateAsync(new NotificationHubPatch(location)
{
    ApnsCredential = new NotificationHubApnsCredential
    {
        AppId = appId,
        AppName = appName,
        Endpoint = new Uri("https://api.push.apple.com:443/3/device"),
        KeyId = keyId,
        Token = token
    }
});
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.3
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.402/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.402 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

IDE:
  JetBrains Rider 2023.1.1

**Comment by ArthurMa1978** [comment]
@markmuniz Thank you for your feedback, we will address this.

**Comment by m-nash** [comment]
@markmuniz when you call `hubResource.UpdateAsync` from above do you get an error or do you get a 200?

You are correct that `AbsoluteUri` does remove the port from the string when it's the default for the scheme, but this is because this `https://api.push.apple.com:443/3/device` and this `https://api.push.apple.com/3/device` are equivalent URIs.

**Comment by markmuniz** [comment]
Yes, the call is successful with a `200`. All of the other values are populated in the notification hub, except for the application mode.

**Comment by markmuniz** [comment]
I will note that the deprecated [Microsoft.Azure.Management.NotificationHubs](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/notificationhubs/Microsoft.Azure.Management.NotificationHubs) package used a `string` type for the `Endpoint` property instead of a `Uri`. Setting that to `https://api.push.apple.com/3/device` would not update the application mode. Including the port in the string did succeed, however.

**Comment by jsquire** [comment]
@m-nash / @markmuniz : Unfortunately, the service team does not monitor our GitHub repositories.  For a service issue, the best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

**Comment by markmuniz** [comment]
@jsquire I don't believe this is a service issue. I have confirmed that this is a regression that occurs when migrating from the deprecated [Microsoft.Azure.Management.NotificationHubs](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/notificationhubs/Microsoft.Azure.Management.NotificationHubs) to [Azure.ResourceManager.NotificationHubs](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/notificationhubs/Azure.ResourceManager.NotificationHubs). The port needs to be included in the request to the service.

**Comment by m-nash** [comment]
@markmuniz I don't know we have come to any conclusion yet, but https with 443 is equivalent to https without.  So if the service is not treating these as equivalent its potentially a service issue.

**Comment by ArthurMa1978** [comment]
This issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
