### ISSUE TITLE
[BUG] Azure.AI.OpenAI.OpenAIClient.GetCompletionsAsync() has no overload for specifying both options and prompt

### ISSUE THREAD

**Issue by MattMcL4475** [Azure/azure-sdk-for-net#36122]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.5

### Describe the bug

There is no way to specify BOTH `CompletionsOptions` and a prompt when using `OpenAIClient.GetCompletionsAsync()`.  As a result, there is no way to change any of the CompletionsOptions (such as `MaxTokens`).

```csharp
using Azure;
using Azure.AI.OpenAI;

namespace CompletionsOptionsBug
{
    internal class Program
    {
        public static async Task Main()
        {
            const string endpoint = "https://myaccount-openai-eastus.openai.azure.com/";
            var client = new OpenAIClient(new Uri(endpoint), new AzureKeyCredential("key_here"));

            var prompt = "Write a hello world program";
            var model = "text-davinci-003";
            var options = new CompletionsOptions();
            options.ChoicesPerPrompt = 1;
            options.MaxTokens = 1000;

            // 1.  This is not possible:
            //options.Prompts = new List<string> { prompt }; // CS0200: Property 'CompletionsOptions.Prompts' cannot be assigned to -- it is read only

            // 2.  This overload is meaningless, there is no way to specify the prompt!
            var result = await client.GetCompletionsAsync(model, options);

            // 3.  What we actually want:
            //var result = await client.GetCompletionsAsync(model, options, prompt);

            foreach (var choice in result.Value.Choices)
            {
                Console.WriteLine(choice.Text);
            }

            Console.ReadLine();
        }
    }
}
```

### Expected behavior

We should be able to specify the model, options, and prompt.  We need this method signature:

```
        public virtual Task<Response<Completions>> GetCompletionsAsync(
            string deploymentOrModelName,
		CompletionsOptions completionsOptions,
            string prompt,
            CancellationToken cancellationToken = default)
        {
```

### Actual behavior

You can only specify the model and the prompt.  If you specify the model and the options, then there is no way to specify the prompt.

### Reproduction Steps

See code in bug description.

### Environment

C# latest Visual Studio

**Comment by lirenhe** [comment]
@MattMcL4475,   could you follow this sample in your scenario?

https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/tests/Samples/Sample02_ChatbotWithKey.cs

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by MattMcL4475** [comment]
@joseharriaga that property is read-only:

https://github.com/Azure/azure-sdk-for-net/blob/dc1faafc465d35b303ce716098f6b703090331fe/sdk/openai/Azure.AI.OpenAI/src/Custom/CompletionsOptions.cs#L113

```csharp
options.Prompts = new List<string> { prompt }; // CS0200: Property 'CompletionsOptions.Prompts' cannot be assigned to -- it is read only
```

**Comment by MattMcL4475** [comment]
Oh, I see.  I had expected Prompts to be settable, or for the constructor to allow passing in `IEnumerable<string> prompts` .  Thank you for the clarification @joseharriaga  @lirenhe 

https://github.com/Azure/azure-sdk-for-net/blob/dc1faafc465d35b303ce716098f6b703090331fe/sdk/openai/Azure.AI.OpenAI/src/Custom/CompletionsOptions.cs#L113
