### ISSUE TITLE
KeyVaultClient.GetSecretsAsync Returns One More Item Than Requested

### ISSUE THREAD

**Issue by vfeier** [Azure/azure-sdk-for-net#3613]
Hi,

I'm using Microsoft.Azure.KeyVault v2.3.2 and I enumerate secrets from a KeyVault using `KeyVaultClient.GetSecretsAsync()`. This returns all the time _one more secret_ than I request with the maxResults parameter. If I ask for **10** items, i get **11**. I have to ask for **9** in order to get **10**.
It seems that the returned list of secrets spans from index **0** to index **maxResults**, thus returning **maxSecrets+1** items all the time.

**Comment by shahabhijeet** [comment]
@RandalliLama can you assign to the right folks, seems like the service is returning a zero based results.
Checked SDK, it validates and sends the query Parameters, has to be the service who is returning it.
Either we fix this or update the API to document the parameter documentation to include zero based index

**Comment by RandalliLama** [comment]
Checking...

**Comment by AlexGhiondea** [comment]
@vfeier does this continue to be an issue?
