### ISSUE TITLE
[BUG] BlobClient.ExistsAsync with URI throws exception in Blazor Webassembly

### ISSUE THREAD

**Issue by ttkaine** [Azure/azure-sdk-for-net#36142]
### Library name and version

Azure.Storate.Blobs 12.16.0

### Describe the bug

Calling blobClient.ExistsAsync() in a balzor web assembly application causes an exception.

This seems to be new behaivour with existing code - as this used to work fine - but possibly something in the azure side has changed?

### Expected behavior

Should return true if the blob exists and return false if it does not exist.

### Actual behavior

throws an exception:

TypeError: Cannot read properties of null (reading 'getReader')

### Reproduction Steps

Create a new blank webassembly application

add a reference to Azure.Storate.Blobs 12.16.0

on the index page add code::

```razor
@page "/"
@using Azure.Storage.Blobs
@using Azure.Storage.Sas

<h1>Hello, world!</h1>
<button @onclick="DoesItExist">Click</button>

exists @exists
message @message

@code
{
    string file = "FILENAME";
    string container = "CONTAINER_NAME";
    string connectionString = "CONNECTION_STRING";

    bool exists = false;
    string message = String.Empty;


    public async Task DoesItExist()

    {
        try
        {
            var serviceClient = new BlobServiceClient(connectionString);
            var containerClient = serviceClient.GetBlobContainerClient(container);
            var sasUri = GetServiceSasUriForContainer(containerClient, false);
            BlobContainerClient sasClient = new BlobContainerClient(sasUri);

            var blobClient = sasClient.GetBlobClient(file);

            if (await blobClient.ExistsAsync())
            {
                exists = true;
            }
            else
            {
                message = "is not there";
            }
        }
        catch (Exception ex)
        {
            message = ex.Message;
        }
    }


    private static Uri GetServiceSasUriForContainer(BlobContainerClient containerClient, bool asReadonly)
    {
        BlobSasBuilder sasBuilder = new BlobSasBuilder()
            {
                BlobContainerName = containerClient.Name,
                Resource = "c"
            };

        sasBuilder.ExpiresOn = DateTimeOffset.UtcNow.AddHours(1);
        if (asReadonly)
        {
            sasBuilder.SetPermissions(BlobContainerSasPermissions.List | BlobContainerSasPermissions.Read);
        }
        else
        {
            sasBuilder.SetPermissions(BlobContainerSasPermissions.All);
        }

        Uri sasUri = containerClient.GenerateSasUri(sasBuilder);
        return sasUri;
    }
}
```

### Environment

WIndows 10 OS on local maching and also on azure webpps

.Net 7 (also seems to happen on .Net 6)

**Comment by drualcman** [comment]
I have same issue, I am using a Connection string directly. Here my code just when try to get the BlobContent

`        try
        {
            BlobClient blobClient = GetBlogClient(container, fileName);
            BlobDownloadResult response = await blobClient.DownloadContentAsync();
            return response.Content.ToArray();
        }
        catch
        {
            return new byte[0];
        }`

I get a exception about max retry, I didn't modify defatul value about 6 retry.The exception also is fired if you try to request for

`if(await blobClient.ExistsAsync())
            {
                BlobDownloadResult response = await blobClient.DownloadContentAsync();
                return response.Content.ToArray();
            }`

But BlobClient get correctly the Blob Uri and I can request for the Uri directly like a link in my Blazoe WebAssembly App.

I want to recovery teh bytes to avoid cache issues I am having with the browsers when only use the Blob Uri.

**Comment by navba-MSFT** [comment]
Adding service attention label.

**Comment by amnguye** [comment]
Does this issue only occur in Blazor? Because `TypeError: Cannot read properties of null (reading 'getReader')` isn't an error we return?

**Comment by ttkaine** [comment]
I have only reproduced this error in Blazor WASM. 

The error started happening on a production site without any deployment or code change. As far as I'm aware nothing updated on the site, we just came in one morning to find the logs full of errors and traced it back to this issue. We have since patched the site to not bother checking the blob exists and just handling the not found error as needed.

I originally raised this with the Azure team on the assumption that something must have changed at a platform level which changed the response the blob store returned for this method, but they insisted it was a code error and nothing had changed on the azure platform - so unfortunately I don't have much information about quite where this bug might have been introduced.

**Comment by amnguye** [comment]
This repo handles Azure SDK issues. So I can't speak for Blazor WASM and any other azure platforms you may be using.

This doesn't sound like an Azure.Storage.Blobs issue since you didn't upgrade the version and it happened out of nowhere.

Is there more logs or stack traces behind this, that could help us narrow down if this is an Azure Storage SDK issue or not?

**Comment by ttkaine** [comment]
I have reloaded the demo code that I used to repro this issue and the issue seems to be resolved. So, again, the same code, the same data, nothing changed in the source, and the issue has gone away. This again, points to a problem somewhere in the Azure platform which is either intermittent or now resolved.

**Comment by acrigney** [comment]
I just tried this with the latest Azure.Storage.Blobs 12.19.0-beta and it gives the error.
