### ISSUE TITLE
WAM auth should default to silently picking the default logged in windows user with option to specify

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#36178]
We should default to a silent auth experience that does not show the account picker UX if a user is already logged in. 

[example](https://github.com/bgavrilMS/MSAL-SingleAccount-SSO/blob/f4c1a71b719250f8bdfb6dbe5d3bee6a48597bbb/SSO/Program.cs#LL182C1-L182C1)

**Comment by scottaddie** [comment]
This feature was supported with the addition of https://github.com/Azure/azure-sdk-for-net/blob/39986d6296be0f75a280389b0781447e8a7df0f1/sdk/identity/Azure.Identity.Broker/src/InteractiveBrowserCredentialBrokerOptions.cs#L26
