### ISSUE TITLE
[BUG] ValidateRestore (and TriggerRestore) does not work as expected

### ISSUE THREAD

**Issue by campionite** [Azure/azure-sdk-for-net#36177]
### Library name and version

Azure.ResourceManager.DataProtectionBackup 1.1.2

### Describe the bug

This may not seem to be a valid issue but I believe it is an issue with the sdk since a direct REST api call for the same operation works without any issues. 
I created a related issue to these libs and that was addressed - https://github.com/Azure/azure-sdk-for-net/issues/35526

Here is a code snippet that throws Azure.RequestFailedException 

 
 `             
               
                var dataSourceResourceId = DataProtectionBackupInstanceResource.CreateResourceIdentifier(
                               _subscriptionId,
                               _resourceGroupName,
                               _vaultName,
                               _backupInstanceName);
                var backupInstanceResource =
                    _armClient.GetDataProtectionBackupInstanceResource(dataSourceResourceId
                        );
                DataSourceInfo dataSourceInfo = new DataSourceInfo(dataSourceResourceId);
                RecoverySetting recoverySetting = new RecoverySetting("FailIfExists");
                IEnumerable<ItemLevelRestoreCriteria> restoreCriteria = new List<ItemLevelRestoreCriteria>
                {
                    new RangeBasedItemLevelRestoreCriteria
                    {
                        MinMatchingValue = "test3",
                        MaxMatchingValue = "test3-0"
                    }
                } 
                RestoreTargetInfoBase restoreTarget = new ItemLevelRestoreTargetInfo(recoverySetting, restoreCriteria, dataSourceInfo);
                SourceDataStoreType sourceDataStoreType = SourceDataStoreType.OperationalStore;
                var recoverOn = new DateTimeOffset(new DateTime(2023, 5, 2, 5, 21, 30, DateTimeKind.Utc));
                BackupRestoreContent backupRestoreContent = new BackupRecoveryTimeBasedRestoreContent(restoreTarget, sourceDataStoreType, recoverOn);
                BackupValidateRestoreContent backupValidateRestoreContent = new BackupValidateRestoreContent(backupRestoreContent);

                var backupInstance = await backupInstanceResource.GetAsync();
                var backupInstancetData = backupInstance.Value.Data;
               
               // this is Line#295 in the Stack trace added below that throws the exception.
                var operation = await backupInstance.Value.ValidateRestoreAsync(WaitUntil.Completed, backupValidateRestoreContent);
                var operationStatus = await operation.WaitForCompletionAsync();
`

More details on the exception - 
Azure.RequestFailedException : User input provided for the call is invalid
Status: 400 (Bad Request)
ErrorCode: BMSUserErrorInvalidInput

Content:
{"error":{"additionalInfo":[{"type":"UserFacingError","info":{"message":"User input provided for the call is invalid","recommendedAction":["Please check the required inputs"],"details":null,"code":"BMSUserErrorInvalidInput","target":"","innerError":null,"isRetryable":false,"isUserError":false,"properties":{"ActivityId":"635cf2d3-afd5-4624-b127-39c85fcf61c5"}}}],"code":"BMSUserErrorInvalidInput","message":"User input provided for the call is invalid","target":null,"details":null}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
Server: Kestrel
x-ms-ratelimit-remaining-subscription-writes: REDACTED
X-Content-Type-Options: REDACTED
x-ms-request-id: a43ba84e-8228-459e-9f14-c238be64e870
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
Date: Wed, 10 May 2023 15:00:06 GMT
Content-Length: 484
Content-Type: application/json; charset=utf-8
Expires: -1

  Stack Trace: 
BackupInstancesRestOperations.ValidateForRestoreAsync(String subscriptionId, String resourceGroupName, String vaultName, String backupInstanceName, BackupValidateRestoreContent content, CancellationToken cancellationToken)
DataProtectionBackupInstanceResource.ValidateRestoreAsync(WaitUntil waitUntil, BackupValidateRestoreContent content, CancellationToken cancellationToken)
AzureBlobStorageDemoTests.ValidateRestore() line 295
<>c.<ThrowAsync>b__128_0(Object state)

### Expected behavior

The method ValidateRestoreAsync should not throw an exception.

### Actual behavior

The method ValidateRestoreAsync throws an exception - 
 Azure.RequestFailedException : User input provided for the call is invalid
Status: 400 (Bad Request)
ErrorCode: BMSUserErrorInvalidInput

### Reproduction Steps

Run the code snippet attached in the description.

### Environment

![image](https://github.com/Azure/azure-sdk-for-net/assets/8433828/a6518dba-b46c-466a-b9dc-d0cbf4bd3c7e)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @campionite , Thank you for using Azure SDK for .NET.
I can't reproduce your error on my machine. Here's my code:
```
var resourceGroup = (await sub.GetResourceGroups().GetAsync("sdktest7894")).Value;
var vault = (await resourceGroup.GetDataProtectionBackupVaults().GetAsync("sdktest1234")).Value;
var name = "";
await foreach (var item in vault.GetDataProtectionBackupInstances().GetAllAsync())
{
    Console.WriteLine(item.Id);
    name = item.Data.Name;
}
var instance = (await vault.GetDataProtectionBackupInstances().GetAsync(name)).Value;

DataSourceInfo dataSourceInfo = instance.Data.Properties.DataSourceInfo;
RecoverySetting recoverySetting = new RecoverySetting("FailIfExists");
IEnumerable<ItemLevelRestoreCriteria> restoreCriteria = new List<ItemLevelRestoreCriteria>
            {
                new RangeBasedItemLevelRestoreCriteria
                {
                    MinMatchingValue = "test3",
                    MaxMatchingValue = "test3-0"
                }
            };
RestoreTargetInfoBase restoreTarget = new ItemLevelRestoreTargetInfo(recoverySetting, restoreCriteria, dataSourceInfo);
SourceDataStoreType sourceDataStoreType = SourceDataStoreType.OperationalStore;
var recoverOn = new DateTimeOffset(new DateTime(2023, 5, 11, 10, 59, 00, DateTimeKind.Local));
BackupRestoreContent backupRestoreContent = new BackupRecoveryTimeBasedRestoreContent(restoreTarget, sourceDataStoreType, recoverOn);
BackupValidateRestoreContent backupValidateRestoreContent = new BackupValidateRestoreContent(backupRestoreContent);

var backupInstance = await instance.GetAsync();
var backupInstancetData = backupInstance.Value.Data;

// this is Line#295 in the Stack trace added below that throws the exception.
var operation = await backupInstance.Value.ValidateRestoreAsync(WaitUntil.Completed, backupValidateRestoreContent);
var operationStatus = await operation.WaitForCompletionAsync();
```
I **create a backupvalut and a instance on the portal,** **backup blob data. Then validate it.** No error was reported.
![MicrosoftTeams-image](https://github.com/Azure/azure-sdk-for-net/assets/30464227/1acf6c07-7672-46c9-8036-4aaed9abd6c4)

Make sure you have the right backup instance created and datasource backuped.
What's your scenario on this case?

**Comment by campionite** [comment]
Thanks for responding to this. The user error does not appear any more. So, I think the Backupvault is the correct way to go about it.
But, I am getting the following authorization error - 

> Azure.RequestFailedException : The client 'guid1' with object id 'guid1'  does not have authorization to perform action 'Microsoft.DataProtection/locations/operationResults/read' over scope '/subscriptions/{subscriptionId}/providers/Microsoft.DataProtection/locations/westus/operationResults/MDY1YmFmZTUtNWM2Mi00MzQ1LWJlZmUtMDYyZWUzYmUyYTkyOzBlY2NjNzM3LTM3OTQtNGIyYS05ZjJlLWRiMWZjMzE5NDJkZQ==' or the scope is invalid. If access was recently granted, please refresh your credentials.
    Status: 403 (Forbidden)
    ErrorCode: AuthorizationFailed

The guid1 is NOT the clientId that I created. guid1 is nowhere to be found on the portal. 
What role/permission should I provide and to which clientId?

**Comment by HarveyLink** [comment]
> Thanks for responding to this. The user error does not appear any more. So, I think the Backupvault is the correct way to go about it. But, I am getting the following authorization error -
> 
> > Azure.RequestFailedException : The client 'guid1' with object id 'guid1'  does not have authorization to perform action 'Microsoft.DataProtection/locations/operationResults/read' over scope '/subscriptions/{subscriptionId}/providers/Microsoft.DataProtection/locations/westus/operationResults/MDY1YmFmZTUtNWM2Mi00MzQ1LWJlZmUtMDYyZWUzYmUyYTkyOzBlY2NjNzM3LTM3OTQtNGIyYS05ZjJlLWRiMWZjMzE5NDJkZQ==' or the scope is invalid. If access was recently granted, please refresh your credentials.
> > Status: 403 (Forbidden)
> > ErrorCode: AuthorizationFailed
> 
> The guid1 is NOT the clientId that I created. guid1 is nowhere to be found on the portal. What role/permission should I provide and to which clientId?

Usually, the client ID here are the same one you used in the authorization credential. Give it enough permission to operate the `resource` / `resource group` / `subscription`.
Also, in the DataProtection case, there will be a SystemAssigned Identity used to backup the datasource, which could also be the possible error ID.

**Comment by campionite** [comment]
Thank you for everyone's help here.
I have not yet figured out the permission issue. But I don’t think it is related to the library.
