### ISSUE TITLE
Missing list of values for AccessTier in Blob Properties

### ISSUE THREAD

**Issue by vainolo** [Azure/azure-sdk-for-net#36172]
Page is missing content. After the sentence "For general purpose v2 and blob storage account types, the valid values are:" there should be a list of values, but there isn't

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cdcaf6ce-d362-c9e2-cd6e-a6c1976f955d
* Version Independent ID: 6349f507-4d01-0712-65a3-940742308647
* Content: [BlobProperties.AccessTier Property (Azure.Storage.Blobs.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobproperties.accesstier?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Models/BlobProperties.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Models/BlobProperties.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by PramodValavala-MSFT** [comment]
@vainolo Thanks for the feedback! We will review and update accordingly.

**Comment by vainolo** [comment]
[like]  Arieh Bibliowicz reacted to your message:
________________________________
