### ISSUE TITLE
CheckNameAvailabilityResult has field IsAvailalbe instead of IsAvailable for Azure Storage

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-sdk-for-net#3618]
CheckNameAvailabilityResult for storage accounts has a field called `IsAvailalbe` instead of `IsAvailable`.

**Comment by hovsepm** [comment]
@tomkerkhove Thanks for catching this issue and for the fix!

**Comment by hovsepm** [comment]
Merged. Will be available from v1.2
