### ISSUE TITLE
Problem creating a new API in an existing APIM instance 

### ISSUE THREAD

**Issue by pfekrati** [Azure/azure-sdk-for-net#36189]
### Library name and version

Azure.ResourceManager.ApiManagement 1.0.1

### Query/Question

hi,

I'm trying to add a new API to an existing APIM instance and I'm getting this error:

Azure.RequestFailedException: 'One or more fields contain incorrect values:
Status: 400 (Bad Request)
ErrorCode: ValidationError

Content:
{"error":{"code":"ValidationError","message":"One or more fields contain incorrect values:","details":[{"code":"ValidationError","target":"protocols","message":"API must define at least one supported protocol"}]}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
x-ms-request-id: 31390054-6e8a-4b81-b551-1f4ca19f9fa5
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Date: Wed, 10 May 2023 19:56:20 GMT
Content-Length: 213
Content-Type: application/json; charset=utf-8
Expires: -1

Here is my code:

    public class AzureApimService : IAzureApimService
    {
        private readonly ArmClient _client;
        public AzureApimService(string tenantId, string clientId, string clientSecret)
        {
            //_client = new ArmClient(new DefaultAzureCredential());
            _client = new ArmClient(new Azure.Identity.ClientSecretCredential(tenantId, clientId, clientSecret));
        }

        public async Task CreateApi(string apiName, string apimName, string resourceGroupName, string revision, string apiPath, string backendUrl)
        {
            try
            {
                SubscriptionResource subscription = await _client.GetDefaultSubscriptionAsync();
                ResourceGroupCollection resourceGroups = subscription.GetResourceGroups();
                ResourceGroupResource resourceGroup = await resourceGroups.GetAsync(resourceGroupName);
                ApiManagementServiceResource apimResource = await resourceGroup.GetApiManagementServiceAsync(apimName);
                ApiCollection apiCollection = apimResource.GetApis();
                var protocols = new List<string>();
                protocols.Add("http");
                protocols.Add("https");
                var api = new ApiCreateOrUpdateContent
                {
                    ApiRevision = revision,
                    ApiType = ApiType.Http,
                    DisplayName = apiName,
                    Path = apiPath,
                    ServiceUri = new Uri(backendUrl),
                    IsSubscriptionRequired = false,
                    IsCurrent = true
                };

                await apiCollection.CreateOrUpdateAsync(Azure.WaitUntil.Completed, apiName.Trim().Replace(" ",""), api); ;
            }
            catch (Exception ex)
            {

                throw ex;
            }
        }
    }

Protocol property of the ApiCreateOrUpdateContent class is read only and I can't figure out how to populate the list.

### Environment

Visual Studio 2022
Windows 11 Enterprise 
.Net 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pfekrati** [comment]
any updates on this? It's not required to pass protocol when creating apis using cli and I wasn't able to find a way to do it in the c# code.

**Comment by RodgeFu** [comment]
@pfekrati , as @mhgames mentioned, you can have the protocols initialized when creating the ApiCreateOrUpdateContent like below
```
ApiCreateOrUpdateContent contentVar = new ApiCreateOrUpdateContent()
{
    ......
    Protocols = 
    {
        ApiOperationInvokableProtocol.Https,
        ApiOperationInvokableProtocol.Http,
    },
    ......
};
```
@mhgames , Is the ApiOperationCollection.CreateOrUpdate what you need? you can find related doc and sample about it at
- https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.apimanagement.apioperationcollection.createorupdate?view=azure-dotnet
- https://github.com/Azure/azure-sdk-for-net/blob/1ceb48d8fd964b432a050c6dc024cb76ddbf5cdf/sdk/apimanagement/Azure.ResourceManager.ApiManagement/samples/Generated/Samples/Sample_ApiOperationCollection.cs#L198
if it's not, pleaes file another issue with details so that we can follow up about it. thanks.

**Comment by mhgames** [comment]
> @mhgames , Is the ApiOperationCollection.CreateOrUpdate what you need? you can find related doc and sample about it at
Thank you, that helped, no idea why didn't I find it earlier, it's literally "api operation" even in the Azure Portal.
