### ISSUE TITLE
[Search] API changes suggestions for future Search release

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#36183]
Ref PR -https://github.com/Azure/azure-sdk-for-net/pull/36109

For future release, consider the following API changes:

- [x] [[Ref](https://github.com/Azure/azure-sdk-for-net/pull/36109#discussion_r1188009990)] We might consider grouping all these [semantic properties](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Generated/Models/SearchOptions.cs#L103) together into `options.SemanticSearch` (`public SemanticSearchOptions SemanticSearch { get; set; }`). Here's the list of semantic search properties which we can consider moving into semantic search options:
    -  [SearchOptions.SemanticFields](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L89)
    -  [SearchOptions.SemanticConfigurationName](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L181)
    -  [SearchOptions.QueryLanguage](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L185) 
    -  [SearchOptions.QuerySpeller](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L189) 
    -  [SearchOptions.QueryAnswer](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L192)
    -  [SearchOptions.QueryAnswerCount](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L195)
    -  [SearchOptions.QueryAnswerThreshold](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L198)
    - [SearchOptions.QueryCaption](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L274)
    -  [SearchOptions.QueryCaptionHighlightEnabled](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Options/SearchOptions.cs#L281) 
    -  [SearchOptions.SemanticMaxWaitInMilliseconds](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Generated/Models/SearchOptions.cs#L103) (and also make this a `TimeSpan`)
    -  [SearchOptions.Debug](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Generated/Models/SearchOptions.cs#L105)
    - [ SearchOptions.SemanticErrorHandling](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Generated/Models/SearchOptions.cs#L101)
 - [x] We might consider grouping all [these](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Models/SearchResults.cs#L62) semantic search results properties together so it'd just be `SearchResults.SemanticSearchResults.Captions`.
   -  [SearchResults<T>.Answers](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Models/SearchResults.cs#L58)
   -  [SearchResults<T>.SemanticPartialResponseReason](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Models/SearchResults.cs#L65)
   -  [SearchResults<T>.SemanticPartialResponseType](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Models/SearchResults.cs#L68)
- [x] We might consider grouping all [these](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Models/SearchResult.cs#L41) semantic search result properties together so it'd just be `SearchResult.SemanticSearchResult.Captions`.
   -  [SearchResult<T>.Captions](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Models/SearchResult.cs#L54)
- [x] We should consider to create a type for vector search configuration and bundle [those](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Generated/Models/SearchField.cs#L55-L57) properties together.
- [x] [[Ref](https://github.com/Azure/azure-sdk-for-net/pull/36109#discussion_r1188964576)]Consider renaming [HnswParameters.M](https://github.com/Azure/azure-sdk-for-net/blob/f6faaf325572b72426473469185530a0a7249b18/sdk/search/Azure.Search.Documents/src/Generated/Models/HnswParameters.cs#L32)(Maximum number of neighbors connected to each node in the graph).
   - [ ] MNeighborCount
   - [ ] NeighborCount
   - [ ] MaxConnections
   - [ ] MaxNeighborLinks

**Comment by ShivangiReja** [comment]
CC: @pallavit, @tg-msft

**Comment by dgetu** [comment]
Some bonus comments from the JS side:
Grouping semantic properties makes sense on our end too, we'd also like to group `SearchOptions.answers` fields into an object (we have a raw string at the moment, though it looks like .NET has `Answers` prefixing top-level fields)
`SearchOptions.debug` -> `SearchOptions.debugMode`
`SearchOptions.semanticErrorHandling` -> `SearchOptions.semanticErrorHandlingMode`

**Comment by ShivangiReja** [comment]
@dgetu There are bunch of other semantic search properties that we should consider moving into SemanticSearchOptions:
* SearchOptions.SemanticFields
* SearchOptions.SemanticConfigurationName 
* SearchOptions.QueryLanguage 
* SearchOptions.QuerySpeller 
* SearchOptions.QueryAnswer
* SearchOptions.QueryAnswerCount
* SearchOptions.QueryAnswerThreshold
* SearchOptions.QueryCaption
* SearchOptions.QueryCaptionHighlightEnabled

**Comment by ShivangiReja** [comment]
The GA version with all the updates is now available at https://www.nuget.org/packages/Azure.Search.Documents/11.5.1.
