### ISSUE TITLE
[DataMovement] [Storage] Make Single Chunk PageBlob and AppendBlob Sync Service To Service Copy work

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#36197]
Initially when SyncCopy for single chunk page and append blobs was implemented, it was assumed since the Sync Service Copy only works for source blobs only works for block blobs.

But technically it should work page blobs and append blobs if we don't call the single service copy call. If we do the Create, Copy Page From Uri (Or Append Block From Uri) it should just work.

**Comment by jalauzon-msft** [comment]
Fixed with #36951
