### ISSUE TITLE
imports

### ISSUE THREAD

**Issue by pgrek001** [Azure/azure-sdk-for-net#36215]
[Enter feedback here]

WHAT ARE THE IMPORTS THAT ARE NEEDED!?!?!?!?   THERE ARE LIKE 100 WAYS AND LIBRARIES AND MOST ARE DEPROICATED>?
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 577bf9ad-b1b2-f48d-88bf-425ef7f9004c
* Version Independent ID: 3fb63a45-2bc7-408e-7365-cb7f9fefc8c7
* Content: [Azure Tables client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/data.tables-readme?view=azure-dotnet#create-the-table-service-client)
* Content Source: [api/overview/azure/latest/data.tables-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/data.tables-readme.md)
* Service: **tables**
* GitHub Login: @christothes
* Microsoft Alias: **chriss**

**Comment by christothes** [comment]
Hi @pgrek001 - I'm sorry, but could you provide more context? If you are referring to which namespaces are required for basic table operations, it would be `using Azure.Data.Tables`.
