### ISSUE TITLE
[FEATURE REQ]  InvalidContentLength - 4MB limit

### ISSUE THREAD

**Issue by kachihro** [Azure/azure-sdk-for-net#36229]
### Library name

Azure.AI.FormRecognizer

### Please describe the feature.

_The input image is too large. Refer to documentation for the maximum file size._

This is an error when processing a file that is over 4MB in size.   My test PDF is 15 MB and 65 pages.
**AnalyzeDocumentFromUriAsync**

Is there any plan for increasing the image limit - or - perhaps a pagination ability ??

**Comment by jsquire** [comment]
Hi @kachihro.  Thank you for reaching out and we regret that you're experiencing difficulties.  The behavior that you're describing is a validation in the Form Recognizer service; the client library does not validate or limit image sizes in any way.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Your best path forward for this request would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
