### ISSUE TITLE
[QUERY] Azure.RequestFailedException: The image in container group is not accessible. Please check the image and registry credential.

### ISSUE THREAD

**Issue by stephenmichaelf** [Azure/azure-sdk-for-net#36227]
### Library name and version

Azure.ResourceManager.ContainerInstance 1.1.0

### Query/Question

I have a few questions. The code will be pasted below.

1. Does this code both create a Container Group and the Container Instance?
2. Does the Container Group specified need to already exist?
3. I want to use an image from Azure Container Registry using the credentials in my DefaultAzureCredential. When I try to run the code below, I get the following error:

```
Azure.RequestFailedException: 'The image 'http://*****.azurecr.io/*****:*****' in container group '*****' is not accessible. Please check the image and registry credential.
Status: 400 (Bad Request)
ErrorCode: InaccessibleImage
```

I tried to look at setting `ImageRegistryCredentials` but there is no way to set them as the `DefaultAzureCredential`. Is this setup wrong? What is the correct way to create an Azure Container Instance using an image from ACR? I saw [this answer](https://github.com/Azure/azure-sdk-for-net/issues/33390) but I'd like to transparently use the identity of where the code is running (e.g. - Local development or an Azure Function) without having to specifically input the identity. Thanks! 😸 

```
            var azureCredential = new DefaultAzureCredential(new DefaultAzureCredentialOptions
            {
                ExcludeEnvironmentCredential = true,
                ExcludeInteractiveBrowserCredential = true,
                ExcludeAzurePowerShellCredential = true,
                ExcludeSharedTokenCacheCredential = true,
                ExcludeVisualStudioCodeCredential = true,
                ExcludeVisualStudioCredential = true,
                // ExcludeAzureCliCredential = true,
                // ExcludeManagedIdentityCredential = true,
            });
            var client = new ArmClient(azureCredential);

            String subscriptionId = "*****************";
            String resourceGroupName = "*********************";

            String containerName = "mycontainer-1";
            String image = "http://*****.azurecr.io/*****:*****";
            String containerGroupName = "container-1";

            var subscription = await client.GetSubscriptions().GetAsync(subscriptionId);
            var resourceGroup = subscription.Value.GetResourceGroup(resourceGroupName);
            var containerGroupCollection = resourceGroup.Value.GetContainerGroups();

            //Int32 count = containerGroupCollection.Count();
            //foreach (var g in containerGroupCollection)
            //{
            //    // g.Id
            //}

            // Create Container Instance
            var reqs = new ContainerResourceRequirements(new ContainerResourceRequestsContent(memoryInGB: 1, cpu: 1));
            var container = new ContainerInstanceContainer(containerName, image, reqs);
            var containers = new List<ContainerInstanceContainer> { container };
            var data = new ContainerGroupData(AzureLocation.EastUS, containers, ContainerInstanceOperatingSystemType.Windows);
            data.ImageRegistryCredentials.Add(new ContainerGroupImageRegistryCredential("") { Identity = "" });
            ArmOperation<ContainerGroupResource> result = await containerGroupCollection.CreateOrUpdateAsync(WaitUntil.Completed, containerGroupName, data);
```

### Environment

Windows 11 Enterprise
Visual Studio 2022

**Comment by RodgeFu** [comment]
@stephenmichaelf , ContainerGroupCollection.CreateOrUpdate(...) will create a new container group with the defined containers started in it. As for using DefaultAzureCredential in the ContainerGroupImageRegistryCredential, I am afraid it's not supported. If you want to use different credential in different environment, 
for non-prod environment, you may consider define different Service Principal environment variable (AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET) in different environment and use them like the code below. DefaultAzureCredential are using the same environment variables too if they are defined. 
```
    ......
    ImageRegistryCredentials = 
    {
        new ContainerGroupImageRegistryCredential(@"xxxacr.azurecr.io")
        {
            Password = Environment.GetEnvironmentVariable("AZURE_CLIENT_SECRET"),
            Username = Environment.GetEnvironmentVariable("AZURE_CLIENT_ID")
        },
    }
    ......
```
for prod environment requiring higher security, you can consider storing the secrets in key vault and using different key vault in different environment, then you can retrieve different values in different environment without changing code. thanks.
