### ISSUE TITLE
Azure.Graph.Rbac is pinned to an old version of generator

### ISSUE THREAD

**Issue by pshao25** [Azure/azure-sdk-for-net#36235]
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/testcommon/Azure.Graph.Rbac/src/Azure.Graph.Rbac.csproj#L16

Azure.Graph.Rbac set to an old version so that @JoshLove-msft did this change https://github.com/Azure/azure-sdk-for-net/pull/36192. This makes our regen pipeline always has this change https://github.com/Azure/azure-sdk-for-net/pull/36206/files#diff-a076be848338a356eff6ca0db1f64dfb29bd595405264856797b6041c97e2ad2

**Comment by jsquire** [comment]
@ArthurMa1978, @m-nash:  Do you folks know anything about that library?   It doesn't seem to be a published package and lives in a test directory.   It looks to have snuck in with an initial merge for KeyVault and hasn't been worked on outside of fixing up breaks for Core/codegen changes.   If we don't know what this is, can we remove it?

**Comment by jsquire** [comment]
I would also really like to understand why we have a `testcommon` directory under `sdk` - if anyone knows.
