### ISSUE TITLE
[BUG]Azure WebPubSub Invalid api verision

### ISSUE THREAD

**Issue by CaidenKehrer** [Azure/azure-sdk-for-net#36243]
### Library name and version

 Azure.Messaging.WebPubSub

### Describe the bug

Calling the WebpuibsubClient.RemoveConnectionFromAllGroups results in an error The HTTP resource that matches the request URI '_____' does not support the API version '2021-10-01'.
Status: 400 (Bad Request)

### Expected behavior

It is expected that the connection passed in would be removed from all webpubsub groups.

### Actual behavior

Errors with a 400 and appears to have an invalid api version when compared to the api documentation. 

### Reproduction Steps

- Set up a webpubsub client
- Have a client join a group
- Call client.RemoveConnectionFromAllGroups

### Environment

C# net6.0 azure functions v4

Visual studio 2022 version 17.3.1

**Comment by navba-MSFT** [comment]
@CaidenKehrer Apologies for the late reply. Thanks for reaching out to us and reporting this issue. Could you please confirm if you are still facing this issue ? Please let us know the `Azure.Messaging.WebPubSub` library version you are using.

Do you get the same issue if you use the[ most recent version](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Messaging.WebPubSub_1.3.0/sdk/webpubsub/Azure.Messaging.WebPubSub/CHANGELOG.md#130-2022-11-20) of the library ?
