### ISSUE TITLE
[BUG] Azure.AI.OpenAI GetChatCompletions.Value.Choices[0].Message.Content Issue

### ISSUE THREAD

**Issue by kdowswell** [Azure/azure-sdk-for-net#36259]
### Library name and version

Azure.AI.OpenAI@1.0.0-beta.5

### Describe the bug

GetChatCompletions result.Value.Choices[0].Message.Content is not showing result from GetChatCompletions as string.

System.IO.MemoryStream is a class in the .NET framework that represents an in-memory stream of data. It allows you to read and write data to and from memory as if it were a file stream. You can use a MemoryStream to store and manipulate data in memory rather than on disk, which can be faster and more efficient in some scenarios. The class provides methods for reading and writing data, seeking to specific positions within the data, and for controlling the size of the buffer used for the stream. Overall, the MemoryStream class is useful when you need to perform operations on data that is not stored on disk, but rather in memory.

### Expected behavior

Expected string of Message Content to be returned. I've tried everything I can think of to get it to work and am stuck.

### Actual behavior

Message Content output is 
```
"`System.IO.MemoryStream` is a class in the .NET framework that represents a stream of data stored in memory, rather than in a file or other external storage. It allows you to read and write bytes to and from the in-memory stream, and provides various methods for working with the data. \n\nThis class is useful when you need to manipulate data that is not conveniently stored in a file, such as when dealing with data coming from a network stream or a database. You can create a `MemoryStream` object and pass it to methods that expect a `Stream` object, allowing you to treat the in-memory data as if it were being read from or written to a file. \n\nHere is an example code snippet showing how to use `MemoryStream` to read from a in-memory byte array:\n\n```\nbyte[] buffer = new byte[1024];  // create a byte array\nMemoryStream ms = new MemoryStream(buffer);  // create a MemoryStream from the byte array\n\n// read data from the MemoryStream\nint bytesRead = ms.Read(buffer, 0, buffer.Length);\n\n// do something with the data\n```\n\nIn this example, we create a `byte` array and use it to create a `MemoryStream` object. We then read from the `MemoryStream` using the `Read` method, which reads up to `buffer.Length` bytes from the stream into the `buffer` array. Finally, we process the data that was read."
```

### Reproduction Steps

- Create an C# Azure Function
```
using System;
using System.IO;
using System.Net;
using System.Threading.Tasks;
using Azure.AI.OpenAI;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Azure.Functions.Worker.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

public class ChatGPT
{
    [Function("ChatGPT")]
    public static async Task<HttpResponseData> Run(
        [HttpTrigger(AuthorizationLevel.Anonymous, "post", Route = null)] HttpRequestData req,
        ILogger log)
    {
        var response = req.CreateResponse(HttpStatusCode.OK);

        string message = req.Body.ToString();
        string requestBody = await new StreamReader(req.Body).ReadToEndAsync();
        dynamic data = JsonConvert.DeserializeObject(requestBody);
        message = message ?? data?.message;

        var client = new OpenAIClient("your-key-here");

        var options = new ChatCompletionsOptions()
        {
            ChoicesPerPrompt = 1,
            MaxTokens = 300,
            Temperature = (float?)0.8,
            Messages = {
                new ChatMessage(ChatRole.User, message)}
        };
        var chatresponse = client.GetChatCompletions("gpt-3.5-turbo", options);

        Console.WriteLine(chatresponse.Value.Choices[0].Message.Content);
        await response.WriteAsJsonAsync(chatresponse.Value.Choices[0].Message.Content);
        return response;
    }
}
```

### Environment

dotnet --info        
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.2
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.203/

Host:
  Version:      7.0.5
  Architecture: arm64
  Commit:       8042d61b17

.NET SDKs installed:
  6.0.408 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pallavit** [comment]
Looping in the openAI  team - /cc: @jpalvarezl, @trrwilson

**Comment by trrwilson** [comment]
Thank you for filing this and apologies for the glacial turnaround as we've worked to establish our process!

As near as I can tell, that bit about streams is deceptive in that it actually *is* the textual content response -- `gpt-3.5-turbo` can produce some very surprising (and sometimes nonsensical) responses without prompt data, which is why some more informative default responses have been added since this issue was originally filed. E.g. attempting an empty content message as a prompt now, I receive something like "I'm sorry, I cannot respond without further information regarding the question or topic. Please provide more details so that I may assist you."

I'm going to close this under the belief that this was a misleading, spurious response message when an empty prompt (message null or empty in the example code) was present and that the behavior should be more self-documenting now. If this is in error and it's doing it when you're sure a prompt is provided, please share as much of the raw response data (response.GetRawResponse().Content) as you can (including request id) so we can investigate further. Thanks again!
