### ISSUE TITLE
[FEATURE REQ] Ability to stop processing directly on the ProcessMessageEventArgs

### ISSUE THREAD

**Issue by danielmarbach** [Azure/azure-sdk-for-net#36254]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

Currently it is possible to stop processing within the `ProcessMessageAsync` event handler only by:

- Taking a closure of the processor
- Call `StopProcessingAsync` non `awaited` in order to avoid deadlocks

```csharp
                Task ProcessMessage(ProcessMessageEventArgs args)
                {
                    if (StopConditionReached)
                    {
                        // awaiting here would cause a deadlock
                        _ = processor.StopProcessingAsync();
                    }
                    return Task.CompletedTask;
                }
```

Given `ProcessMessageEventArgs` exposes functionality to interact with the currently received message but also the receive actions to retrieve more messages would it make sense to simplify things and allow stopping the processor directly on the event args? 

This method could take care of dropping the task and all the associated error handling if required. For example

```csharp
                Task ProcessMessage(ProcessMessageEventArgs args)
                {
                    if (StopConditionReached)
                    {
                        args.StopProcessing();
                    }
                    return Task.CompletedTask;
                }
```

**Comment by jsquire** [comment]
Hey @danielmarbach.   This is a scenario that we actively discourage; stopping the processor from the message handler is generally not a great idea.   Can you help me understand the scenario that you're thinking of where it would be desired, and where the calling application wouldn't be able to stop the processor?

**Comment by danielmarbach** [comment]
@jsquire while working on https://github.com/Azure/azure-sdk-for-net/pull/36253 I discovered that there are explicit tests for that scenario and I wondered why there are tests for scenarios that are very complicated to use. That's why I assumed it is an end user scenario and raised this feature request to explore simpler alternatives. Based on your input I see that it is "complex by design to avoid encouraging doing that" which is totally fine for me.
