### ISSUE TITLE
[BUG] Client Encryption Feature - If the key uri specified without version id, the decryption will fail to retrieve KEK.

### ISSUE THREAD

**Issue by jeromezliu** [Azure/azure-sdk-for-net#36269]
### Library name and version

Azure.Storage.Blobs 12.16.0

### Describe the bug

We setup the encryptionOption as below - specify the KEK URI without key version.

```
            // Resolve the KEK using key identifier without key version (basic identifier)
            key = await keyResolver.ResolveAsync("https://jrkeyvault.vault.azure.net/keys/storage-kek");
            Console.WriteLine("KEK key ID without key version: {0}", key.KeyId);

    
            // Create encryption options for uploading and downloading
            ClientSideEncryptionOptions encryptionOption = new ClientSideEncryptionOptions(ClientSideEncryptionVersion.V2_0)
            {
                KeyResolver = keyResolver,
                KeyEncryptionKey = key,         // the code may trigger a bad parameter error when downloading/decryption CEK after key rotation
                KeyWrapAlgorithm = "RSA-OAEP"
            };
```
When we rotate the key in KeyVault (the old key still enabled), the download\decryption will be failed with 400 BadParameter.

```
RequestFailedException: Error occurred while decoding OAEP padding.
Status: 400 (Bad Request)
ErrorCode: BadParameter

Content:
{"error":{"code":"BadParameter","message":"Error occurred while decoding OAEP padding."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-keyvault-region: eastasia
x-ms-client-request-id: 8b5074cc-45da-406b-842e-b4f38a9bfb17
x-ms-request-id: 25b98b11-643c-41c3-90ae-d7ada677b567
x-ms-keyvault-service-version: 1.9.787.1
x-ms-keyvault-network-info: conn_type=Ipv4;addr=167.220.255.18;act_addr_fam=InterNetwork;
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
Date: Mon, 15 May 2023 09:31:49 GMT
Content-Length: 89
Content-Type: application/json; charset=utf-8
Expires: -1 
```

### Expected behavior

The decryptor should fetch the correct key from keyvault to finish the decryption. This process should not rely on the encryptionOption.

### Actual behavior

400 Error - seems from KeyVault.

If we use a keyURI with key version, e.g. https://jrkeyvault.vault.azure.net/keys/storage-kek/xxxxxxxx
This issue will not happened.

### Reproduction Steps

1. Setup the blob client and encryptionOption with URI described above
2. Using the blobclient to upload a blob with client encryption.
3. Rotate the key in the key vault manually
4. Continue download the blob using the same blob client.

CODE
```
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Specialized;
using Azure.Storage.Blobs.Models;
using Azure.Storage;
using Azure.Identity;
using Azure.Core.Cryptography;
using Azure.Security.KeyVault.Keys.Cryptography;
using Azure.Security.KeyVault.Keys;
using System;

namespace StorageClientEncrptoin
{
    class Program
    {
        static async Task Main(String[] args)
        {
            Console.WriteLine("Hello Azure Blob Storage with client side encryption!");

            // Get token
            DefaultAzureCredential cred = new DefaultAzureCredential();
            Uri storageUri = new Uri("https://jr3.blob.core.windows.net");

            //var kvclient = new KeyClient(keyvaultUri, cred);


            // Create local test file
            string localPath = "data";
            Directory.CreateDirectory(localPath);
            string fileName = "quickstart" + Guid.NewGuid().ToString() + ".txt";
            string localFilePath = Path.Combine(localPath, fileName);
            await File.WriteAllTextAsync(localFilePath, "Hello World!");

            IKeyEncryptionKey key;
            IKeyEncryptionKeyResolver keyResolver;

            // Create key resolver to resolve key
            keyResolver = new KeyResolver(cred);

            // Resolve the KEK using key identifier without key version (basic identifier)
            key = await keyResolver.ResolveAsync("https://jrkeyvault.vault.azure.net/keys/storage-kek");
            Console.WriteLine("KEK key ID without key version: {0}", key.KeyId);

    
            // Create encryption options for uploading and downloading
            ClientSideEncryptionOptions encryptionOption = new ClientSideEncryptionOptions(ClientSideEncryptionVersion.V2_0)
            {
                KeyResolver = keyResolver,
                KeyEncryptionKey = key,         // the code may trigger a bad parameter error when downloading/decryption CEK after key rotation
                KeyWrapAlgorithm = "RSA-OAEP"
            };

            BlobClientOptions blobClientOption = new SpecializedBlobClientOptions()
            {
                ClientSideEncryption = encryptionOption
            };

            // Get blob service client and container client and blob client
            string containerName = "quickstartblobs" + Guid.NewGuid().ToString();
            BlobServiceClient blobServiceClient = new BlobServiceClient(storageUri, cred, blobClientOption);
            BlobContainerClient blobContainerClient = await blobServiceClient.CreateBlobContainerAsync(containerName);
            BlobClient blobClient = blobContainerClient.GetBlobClient(fileName);

            // Upload the test file to blob container
            Console.WriteLine("Uploading to Blob storage as blob:\n\t {0}\n", blobClient.Uri);
            await blobClient.UploadAsync(localFilePath, true);

            // List blobs in the container
            Console.WriteLine("Listening blobs...");
            await foreach (BlobItem blobItem in blobContainerClient.GetBlobsAsync())
            {
                Console.WriteLine("\t" + blobItem.Name);
            }
            Console.WriteLine("\n");

            // kvclient.RotateKey(key.KeyId);
            // Console.WriteLine("Rotating keys...");



            // Download a blob
            Console.WriteLine("Press any key to download blob...");
            Console.ReadLine();

            IKeyEncryptionKey newkey = await keyResolver.ResolveAsync(keyUri);
            Console.WriteLine("New KEK key ID: {0}", newkey.KeyId);

            string downloadFilePath = localFilePath.Replace(".txt", "DOWNLOADED.txt");
            Console.WriteLine("\nDownloading blob to\n\t{0}\n", downloadFilePath);
            try
            {
                await blobClient.DownloadToAsync(downloadFilePath);
            }
            catch (Azure.RequestFailedException e)
            {
                // RequestFailedException will be captured after key rotation
                Console.WriteLine("{0}: {1}", e.GetType().Name, e.Message);
            }

            // Delete a container
            Console.Write("Press any key to begin clean up...");
            Console.ReadLine();
            
            Console.WriteLine("Deleting blob container...");
            await blobContainerClient.DeleteAsync();

            // Clean up local file
            Console.WriteLine("Deleting the local source and downloaded files...");
            File.Delete(localFilePath);
            File.Delete(downloadFilePath);
            Console.WriteLine("Done.");
        }
    }

}
```

### Environment

Tested on both Azure AppServiace and local machine.

Local
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  7.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

**Comment by jeromezliu** [comment]
Thank you, team.
Here is an update after few tests:

The issue happens during the decryption process.
The issue only happens if we specify a **non-versioned key URI** in the encryptionOption and set it to the client. Leave it empty or specify a Key URL with version will not trigger this issue.

Let me know if you need more information.

p.s. I'm available on Teams jeromeliu@microsoft.com

**Comment by jaschrep-msft** [comment]
@jeromezliu apologies that this issue slipped through the cracks.

From the perspective of the Storage library, we consume an interface whose API contract gives us an ID to identify the correct key, as well as an interface that lets us look up the key from that ID. If the given ID is not enough to identify the key, there is nothing storage can do. It stores what it was given and doesn't know about the implementation behind the interface.

I believe this to be an issue with KeyVault instead of Storage, as the KeyVault client instance is not providing an ID specific enough to resolve the correct key with their own resolver.

In the meantime as a workaround, I believe a key resolver isn't needed to decrypt the blob if you already have the correct key stored in the options in the first place. In that case, you can manually load up the correct key for any blob you identify for these circumstances. If you wanted to proactively "fix" blobs with this insufficient KeyId, you could list blobs including metadata and scan for an encryption metadata field where the key ID is of a pattern you recognize as insufficient. That would ID every blob in this situation and allow you to key-rotate their KEK to one with the version specified in the ID. We provide an [extension method](https://github.com/Azure/azure-sdk-for-net/blob/d80851c1b8b9621ce0a72ddc1839b2fb3200e350/sdk/storage/Azure.Storage.Blobs/src/SpecializedBlobExtensions.ClientSideEncryption.cs#L74) to rotate KEK for you.

**Comment by heaths** [comment]
The key resolver resolves whatever key ID you pass, so if you pass a versionless key ID - not recommended - we'll fetch the latest. Regardless, the full key ID is always returned, so even if you want to use a versionless key, the key ID you should store with your data is the one returned - not the one you passed. There's no way the key resolve can figure out what version to use if it's not told.

```C#
using Azure.Identity;
using Azure.Security.KeyVault.Keys.Cryptography;

DefaultAzureCredential credential = new();
KeyResolver resolver = new(credential);

string keyId = Environment.ExpandEnvironmentVariables("%AZURE_KEYVAULT_URL%/keys/kek");
var kek = await resolver.ResolveAsync(new Uri(keyId));

Console.WriteLine(kek.KeyId);
```
```text
https://myvault.vault.azure.net/keys/kek/b2825f5b1afb4a059827df258a05ed8c
```
