### ISSUE TITLE
Data Lake Query Acceleration failing for tab separated file

### ISSUE THREAD

**Issue by rakeshthakur** [Azure/azure-sdk-for-net#36271]
I am trying to query a tab separated file using Data Lake Query Acceleration and the query is throwing exception "XML specified is not syntactically valid". The documentation does not mention whether how can we set the tab delimiter properly or whether the tab delimited files are supported or not. For Tab I am setting the ColumnSeperator as "\t" or "\\t" which is not working.
           `var blobQueryOptions = new BlobQueryOptions();

            blobQueryOptions.InputTextConfiguration = new BlobQueryCsvTextOptions()
            {
                HasHeaders = true,
                ColumnSeparator = "\\t", //"\t" also does not seem to work
                RecordSeparator = "\n",
                EscapeCharacter = '\\',
                QuotationCharacter = '"',
            };`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 70bd164c-41ae-e7ca-8fb8-63cb455890ae
* Version Independent ID: 264c350e-47ee-3125-4153-76f812e2afb8
* Content: [BlobQueryCsvTextOptions.ColumnSeparator Property (Azure.Storage.Blobs.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.models.blobquerycsvtextoptions.columnseparator?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Blobs.Models/BlobQueryCsvTextOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Models/BlobQueryCsvTextOptions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by SaurabhSharma-MSFT** [comment]
@rakeshthakur We are looking into it and get back to you for any additional information.

**Comment by SaurabhSharma-MSFT** [comment]
@rakeshthakur I am not seeing any issues accessing tab delimited csv file.  Please refer to the below screen shot.
![image](https://github.com/Azure/azure-sdk-for-net/assets/38112130/a951b7d2-e7b1-4002-bb5d-f74d044d8779)
I am using `Azure.Storage.Blobs = 12.11.0` version.  Can you please provide your nuget package version. Thanks

**Comment by SaurabhSharma-MSFT** [comment]
@rakeshthakur We will now proceed to close this thread. If there are further questions regarding this matter, please reopen it and we will gladly continue the discussion.
