### ISSUE TITLE
No mention what is "streaming" and no clear way in the examples on how to have a meaningful chat with a model by saving the current context.

### ISSUE THREAD

**Issue by kostas-kelgeorgiadis** [Azure/azure-sdk-for-net#36273]
There is no clear explanation on what "streaming" is.
Is it the same as non-streaming, but with more asynchrony when iterating on response-lists (aka `choices`)?
Azure OpenAI Studio generates C# code samples that refer to streaming as a notion too, but the code and the API makes it no clearer what it is.

Also, I find no clear way for re-using a model that will remember data I have fed it in the past.
No obvious way to save the current context, and no obvious way to continue in the same context after getting completions once. The `OpenAIClient` seems to keep no context inside of itself, and using its methods returns no context that one can hold on to.
Am I missing something or I will need to resend all the previous chat messages on every chat question I need to send?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 81e0efc8-d491-4425-7652-08dddb8e866d
* Version Independent ID: ed418ebd-a705-e133-d8e1-33e85db8fc60
* Content: [Azure OpenAI client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/ai.openai-readme?view=azure-dotnet-preview)
* Content Source: [api/overview/azure/preview/ai.openai-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/preview/ai.openai-readme.md)
* Service: **openai**
* GitHub Login: @jpalvarezl
* Microsoft Alias: **josealvar**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pallavit** [comment]
Looping in the openAI team - /cc: @jpalvarezl, @trrwilson

**Comment by jzhouw** [comment]
any gpt model is stateless, it never"remember" your prompt. you should implement session state by yourself e.g. provide conversation history in next completion api call

**Comment by kostas-kelgeorgiadis** [comment]
@jzhouw 
Hm. OK.
I thought this was wasting too many resources (network bandwidth, CPU usage, etc) and that there would be a better way.
I guess that after a point, when a chat becomes long, things will be less than optimal.

Is there any other model, aside GPT, that can keep its previous data?
Or maybe a way to store the history data on Azure and feed them from there, and at least avoid the bandwidth issues?
