### ISSUE TITLE
Thread-safety and memory leak bug in Fluent API Region class

### ISSUE THREAD

**Issue by Eldar1205** [Azure/azure-sdk-for-net#3628]
I looked in _fluent_ branch at source code of [Region](https://github.com/Azure/azure-sdk-for-net/blob/Fluent/src/ResourceManagement/ResourceManager/Region.cs) class and noticed a thread-safety bug and a memory leak bug due to usage of static regions dictionary. The thread-safety bug is that public _Create_ method can call private constructor which adds an item to the static dictionary - user can call _Create_ in parallel with different regions not already in the dictionary causing parallel mutation of the dictionary, which isn't a thread-safe operation. The second issue is that this same mutation of the dictionary can cause a memory leak if user has bug that constantly uses new unknown locations. I suggest to solve both by initializing the dictionary once in static constructor with all well-known regions, and when _Create_ calls the private constructor for unknown region the private constructor won't manipulate the static regions dictionary. The _Equals_ and _GetHashCode_ implementations already support that, they don't assume each region instance is in the dictionary.

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#46
