### ISSUE TITLE
No information on how to populate this object

### ISSUE THREAD

**Issue by tom-puckett** [Azure/azure-sdk-for-net#36293]
This documentation provides nothing useful about how to use the class.  There are no members in the visible implementation so no properties to even suggest how to make use of this type.  At least a link to something useful would be helpful. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b65878bc-2fcd-ec2f-a579-ff9765b375f2
* Version Independent ID: 3180c1a5-9866-ab22-cd87-adf5f4df2490
* Content: [ShareDeleteOptions.Conditions Property (Azure.Storage.Files.Shares.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.models.sharedeleteoptions.conditions?view=azure-dotnet)
* Content Source: [xml/Azure.Storage.Files.Shares.Models/ShareDeleteOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Files.Shares.Models/ShareDeleteOptions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@tom-puckett Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@tom-puckett You could leverage the below sample which explains how the[ ShareDeleteOptions.Conditions ](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.models.sharedeleteoptions.conditions?view=azure-dotnet)Property can be used. The sample uses the [ShareFileRequestConditions.LeaseId ](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.models.sharefilerequestconditions.leaseid?view=azure-dotnet#azure-storage-files-shares-models-sharefilerequestconditions-leaseid)Property which limit requests to resources with an active lease matching this Id.

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Azure.Storage.Files.Shares;
using Azure.Storage.Files.Shares.Models;
using Azure.Storage.Files.Shares.Specialized;

namespace ShareDeleteOptions
{
    internal class Program
    {
        static void Main(string[] args)
        {
            // Connection string to the Azure Storage account
            string connectionString = "XXXXXXXXXXXXXXXXXXXXXX";

            // Name of the share to be deleted
            string shareName = "myShareName";

            // Set the desired lease duration
            TimeSpan leaseDuration = TimeSpan.FromSeconds(60); 

            // Create an instance of ShareServiceClient using the connection string
            ShareServiceClient shareServiceClient = new ShareServiceClient(connectionString);

            // Get a reference to the share you want to delete
            ShareClient shareClient = shareServiceClient.GetShareClient(shareName);

            // Acquire the lease
            ShareLeaseClient leaseClient = shareClient.GetShareLeaseClient();
            var lease = leaseClient.Acquire(leaseDuration);

            // Print the lease ID of the acquired lease
            Console.WriteLine("Lease acquired successfully. Lease ID: " + lease.Value.LeaseId);


            // Create an instance of ShareDeleteOptions and set the conditions
            Azure.Storage.Files.Shares.Models.ShareDeleteOptions options = new Azure.Storage.Files.Shares.Models.ShareDeleteOptions
            {
                Conditions = new ShareFileRequestConditions
                {
                    
                    LeaseId = lease.Value.LeaseId.ToString()
                }
            };

            // Delete the share with the specified conditions
            shareClient.Delete(options);
        }
    }
}
```

Hope this helps.

**Comment by tom-puckett** [comment]
I appreciate the response and I will consider how to make use of it in my situation.  My comment was for the benefit of improving the online documentation.  A change to that page, maybe with more descriptive information or a link to the sample, would be a reasonable outcome.
