### ISSUE TITLE
Transaction limit on batches

### ISSUE THREAD

**Issue by ChuckWalters** [Azure/azure-sdk-for-net#36302]
[Enter feedback here]
No mention transaction limits.  Tried to use to upload 100's of documents and it errored out.  What is the limit?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c870bbb-ee69-9266-3d09-3f2e68ed4175
* Version Independent ID: 444850f9-9318-3b75-8b76-504ae37357e6
* Content: [Container.CreateTransactionalBatch(PartitionKey) Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createtransactionalbatch?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue was transferred to the repository where the `Microsoft.Azure.Cosmos` library is maintained as [#3853](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3853).
