### ISSUE TITLE
Access control (IAM)

### ISSUE THREAD

**Issue by mdsajidfaizan** [Azure/azure-sdk-for-net#3631]
Hello Everybody,
Can i assign a users email address to a subscription as an owner using ARM sdk?

This is same as Access control(IAM) in azure portal, where the subscription can be shared as an owner with multiple person.

**Comment by shahabhijeet** [comment]
@stefmilmsft can you help answer this question.

**Comment by shahabhijeet** [comment]
@mdsajidfaizan 
The RBAC model for role assignments expects the ObjectId of an AAD directory object (could be user, group or serviceprincipal). Thus, one cannot use an e-mail/upn for the PrincipalId property directly
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Authorization/Management.Authorization/Generated/Models/RoleAssignmentProperties.cs

The proper way to use the API is to first lookup the User object in AAD Graph by upn, get the ObjectId and set it as the PrincipalId on the role assignment. For lookups against Graph, the following code is a good starting point:
https://github.com/Azure/azure-sdk-for-net/blob/psSdkJson6/src/SDKs/Graph.RBAC/Graph.RBAC/Generated/UsersOperations.cs

Hopefully this answers your question and unblocks you.
