### ISSUE TITLE
Azure.Monitor.OpenTelemetry.AspNetCore - How do I enable Sql SetDbStatementForText?

### ISSUE THREAD

**Issue by michaelmcneilnet** [Azure/azure-sdk-for-net#36340]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0-beta.4

### Query/Question

When using the `OpenTelemetry.Instrumentation.SqlClient` directly, I was able to configure it to log the SQL command text.

```cs
.AddSqlClientInstrumentation(options =>
{
  options.SetDbStatementForText = true;
})
```

I have moved over to `Azure.Monitor.OpenTelemetry.AspNetCore` which I see has a dependency on `OpenTelemetry.Instrumentation.SqlClient`, but I am not clear on how I configure the SQL Client Instrumentation. 

Is it safe to continue to chain the call before UseAzureMonitor, as below, or will this result in unintended side effects?

```cs
services
.AddOpenTelemetry()
.WithTracing(x => x.AddSqlClientInstrumentation(x => x.SetDbStatementForText = true))
.UseAzureMonitor();
```

### Environment

.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  6.0.408 [C:\Program Files\dotnet\sdk]
  7.0.105 [C:\Program Files\dotnet\sdk]
  7.0.202 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by TimothyMothra** [comment]
Hi @michaelmcneilnet,
You won't need to call `AddSqlClientInstrumentation()`, because our `UseAzureMonitor()` does this step.

To configure that Instrumentation, you can use this api:
```
builder.Services.Configure<SqlClientInstrumentationOptions>(options =>
{
    options.SetDbStatementForText = true;
});
```

You can see this example on our readme:
https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore#customizing-sqlclientinstrumentationoptions

**Comment by michaelmcneilnet** [comment]
Perfect, thanks!
