### ISSUE TITLE
ServiceBus entities lack UserMetadata

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-sdk-for-net#3635]
`UserMetadata` on all entities ([queues](https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.queuedescription.usermetadata), [topics](https://docs.microsoft.com/en-ca/dotnet/api/microsoft.servicebus.messaging.topicdescription.usermetadata), and [subscriptions](https://docs.microsoft.com/en-ca/dotnet/api/microsoft.servicebus.messaging.subscriptiondescription.usermetadata)) is missing

**Comment by SeanFeldman** [comment]
@anuchandy is this scheduled for an update?

**Comment by anuchandy** [comment]
@seanFeldman the management SDK is based on the swagger specification from service team, in the spec I don't see `UserMetadata` property in messaging entities. For example here is the description of Queue entity https://github.com/Azure/azure-rest-api-specs/blob/current/specification/servicebus/resource-manager/Microsoft.ServiceBus/2017-04-01/servicebus.json#L2574

tagging @jtaubensee from service team.

**Comment by SeanFeldman** [comment]
Tagging @djrosanova

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#3

**Comment by SeanFeldman** [comment]
@hovsepm https://github.com/Azure/azure-libraries-for-java/issues/3 is resulting in 404.

**Comment by niemyjski** [comment]
@Sean is this missing in the .net client still?

**Comment by SeanFeldman** [comment]
@niemyjski the NETStandard client never had it as that client doesn't have `Description` object for entities.
