### ISSUE TITLE
Configuration of Pools with Managed Identities using Azure.ResourceManager.Batch client library

### ISSUE THREAD

**Issue by ccvaillant1992** [Azure/azure-sdk-for-net#36354]
### Library name and version

Azure.ResourceManager.Batch 1.1.1

### Query/Question

Can someone help me by providing me with any documentation about how to configure Pools with Managed Identities in Azure batch resources using  Azure.ResourceManager.Batch client library?

The actual documentation refers to Microsoft.Azure.Management.Batch sdk, but that package has been deprecated. 
![image](https://github.com/Azure/azure-sdk-for-net/assets/56896573/522a3fd2-43fa-41c3-9937-f667fd19ad9e)

![image](https://github.com/Azure/azure-sdk-for-net/assets/56896573/f3edc60b-bd8b-46fb-8a13-8c7e83fb646b)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dazfuller** [comment]
Is there any update on this as I have the same issue

**Comment by Methargus** [comment]
Have the same issue too.

**Comment by dazfuller** [comment]
Any news on this @jsquire @ArthurMa1978?

**Comment by HarveyLink** [comment]
I have translate the Track1 sample to our current Track2 sdk. Please take a look.
```
// Assmue you have a parent resource created
var batch = (await resourceGroup.GetBatchAccounts().GetAsync("batchAccountName")).Value;

// Create a Batch pool with user-assigned managed identities
var poolCollection = batch.GetBatchAccountPools();
var poolData = new BatchAccountPoolData()
{
    VmSize = "standard_d2_v3",
    ScaleSettings = new BatchAccountPoolScaleSettings
    {
        FixedScale = new BatchAccountFixedScaleSettings
        {
            TargetDedicatedNodes = 1
        }
    },
    DeploymentConfiguration = new BatchDeploymentConfiguration
    {
        VmConfiguration = new BatchVmConfiguration(
                new BatchImageReference()
                {
                    Offer = "Canonical",
                    Publisher = "0001-com-ubuntu-server-jammy",
                    Sku = "22_04-lts",
                    Version = "latest" },
                "batch.node.ubuntu 22.04")
    },
    Identity = new ManagedServiceIdentity(ManagedServiceIdentityType.UserAssigned)
    {
        UserAssignedIdentities = 
        {
            { new ResourceIdentifier("Your Identity Resource Id"), new UserAssignedIdentity() }
        }
    }
};
var pool = (await poolCollection.CreateOrUpdateAsync(WaitUntil.Completed, "poolName", poolData)).Value;
```
