### ISSUE TITLE
[QUERY] How to list subscriptions under a ManagementGroup?

### ISSUE THREAD

**Issue by SimonWahlin** [Azure/azure-sdk-for-net#36378]
### Library name and version

Azure.ResourceManager 1.6.0

### Query/Question

I have a need to list all subscriptions under a managementGroup. Using the REST API, I can use the endpoint [Get Subscriptions Under Management Group](https://learn.microsoft.com/en-us/rest/api/managementgroups/management-group-subscriptions/get-subscriptions-under-management-group?tabs=HTTP).

I seem to be able to do the same using the method [GetSubscriptionsUnderManagementGroupAsync](https://github.com/Azure/azure-sdk-for-net/blob/318d6ca1aae555641442a344eac3ea5c47c7a86b/sdk/managementgroups/Microsoft.Azure.Management.ManagementGroups/src/Generated/ManagementGroupSubscriptionsOperationsExtensions.cs#L217) from the deprecated library Microsoft.Azure.Management.ManagementGroups.

How do I do the same thing using Azure.ResourceManager? I've tried using both Azure.ResourceManager.Subscriptions and Azure.ResourceManager.Resources without any success.

### Environment

I don't think the environment matters here.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
Related (duplicate):  #41287

**Comment by jsquire** [comment]
@ArthurMa1978:   This looks as if it has been waiting for assistance for quite some time.   Can we please provide an update?

**Comment by HarveyLink** [comment]
> @ArthurMa1978: This looks as if it has been waiting for assistance for quite some time. Can we please provide an update?

PR is ready, in review process now: https://github.com/Azure/azure-sdk-for-net/pull/41173

**Comment by ArthurMa1978** [comment]
We're working on the testing as this operation need special permission which we currently don' have.

**Comment by HarveyLink** [comment]
Issue fixed, will ship in the next release.

**Comment by SimonWahlin** [comment]
Thank you!
