### ISSUE TITLE
Support for Appending to Avro Object Container Files

### ISSUE THREAD

**Issue by thebothead** [Azure/azure-sdk-for-net#3637]
Hello,

I would like to see support for appending to Avro Object Container files via the serializers in this SDK, similar to what is already provided in the Apache Avro Java serializer.

Per the Apache Avro Community:

> The Avro file format supports appends.  However some filesystems (e.g., HDFS and S3) may not support append, so applications generally avoid depending on it.  Also, it can complicate application semantics when the contents of files change after they are first created.
The Java API supports append:
https://avro.apache.org/docs/1.8.2/api/java/org/apache/avro/file/DataFileWriter.html#appendTo(java.io.File)
There is also an open feature request to extend the concat tool to support append:
https://issues.apache.org/jira/browse/AVRO-1856

Is it possible for this feature to be added to this SDK?

Thanks,
Matt

**Comment by shahabhijeet** [comment]
@thebothead see #3644 and provide some more details

**Comment by shahabhijeet** [comment]
@thebothead if you still encounter issue, please open a new issue.
