### ISSUE TITLE
Example code missing

### ISSUE THREAD

**Issue by InteXX** [Azure/azure-sdk-for-net#36377]
Note that the usage guidance for the `SitePatchInfo` parameter states "see example," where there is no actual example, nor is there a link to any example.

Example code for the SDK is frustratingly limited. Simple and common tasks, such as uploading and installing a third-party TLS certificate, aren't covered, leaving us to resort to guesswork and decompilation of the SDK binaries simply to try to figure out what's going on.

For example, I'm just now winding down my third full day of writing a mere few lines of code that should have taken only an hour or so.

Unfortunately, the state of usage guidance for the SDK is abysmal. Much improvement is sorely needed.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 86fed4a9-1099-d649-cb54-2537786300ac
* Version Independent ID: a74357e8-8731-116f-9b3e-c8eab6823a71
* Content: [WebSiteResource.Update(SitePatchInfo, CancellationToken) Method (Azure.ResourceManager.AppService) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.appservice.websiteresource.update?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Azure.ResourceManager.AppService.WebSiteResource.Update)%3Bk(SolutionItemsProject)%3Bk(DevLang-VB)%26rd%3Dtrue&view=azure-dotnet)
* Content Source: [xml/Azure.ResourceManager.AppService/WebSiteResource.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.ResourceManager.AppService/WebSiteResource.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by InteXX** [comment]
Very good, thank you.

**Comment by InteXX** [comment]
What is the SDK equivalent of [this REST API](https://learn.microsoft.com/en-us/rest/api/appservice/certificates/create-or-update)?

Unfortunately, the SDK is so poorly documented that—after two full days of digging—I finally have to ask.

**Comment by ArthurMa1978** [comment]
This need service team to fix the document.
