### ISSUE TITLE
Fluent: Samples need examples for running DSC extensions with external files and all

### ISSUE THREAD

**Issue by simon-michaud** [Azure/azure-sdk-for-net#3638]
I looked everywhere but did not find how to execute DSC extensions when creating a VM with the SDK.

If someone can start me off, I could PR working examples.

Thanks #

**Comment by hovsepm** [comment]
@simon-michaud please reopen this bug in https://github.com/Azure/azure-libraries-for-net repo if you still cannot find a good sample.
