### ISSUE TITLE
Can I use my guest user account to auth using DefaultAzureCredential when developing locally?

### ISSUE THREAD

**Issue by michalkrzych** [Azure/azure-sdk-for-net#36385]
### Library name and version

Azure.Identity 1.8.2

### Query/Question

Hello.

I'm following [Authenticate .NET apps to Azure services during local development using developer accounts](https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication-local-development-dev-accounts?tabs=azure-portal%2Csign-in-visual-studio%2Ccommand-line)

I am a guest user in a tenant and I am trying to use that account as a developer account in Visual Studio (signed in via Tools > Azure Service Authentication > Account Selection) with the code below 

```csharp
DefaultAzureCredential defaultAzureCredentialTokenProvider = new DefaultAzureCredential(new DefaultAzureCredentialOptions()
{
    ExcludeAzureCliCredential = true,
    ExcludeAzurePowerShellCredential = true,
    VisualStudioTenantId = "tenantGUID"
});
TokenRequestContext requestContext = new TokenRequestContext(new[] { scopeUrl });
AccessToken accessToken = await defaultAzureCredentialTokenProvider.GetTokenAsync(requestContext);
return accessToken.Token;
```

I am getting the following error message saying my account wasn't found in the tenant:

> Unhandled exception processing web service request : DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
[2023-05-19T10:53:30.290Z] - EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
[2023-05-19T10:53:30.291Z] - ManagedIdentityCredential authentication unavailable. Multiple attempts failed to obtain a token from the managed identity endpoint.
[2023-05-19T10:53:30.292Z] - Process "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS002: The account '_me@blablabla.com_' was not found in the tenant '_tenantGUID_'..

My guest user exists in the tenat 

![image](https://github.com/Azure/azure-sdk-for-net/assets/6545828/3249f0e1-18c8-43a4-9d63-3d11589662b7)

so I wonder if there is maybe a setting I haven't toggled or perhaps a limitation with guest users which I am unaware of?

### Environment

.NET 6 
Microsoft Visual Studio Enterprise 2022 Version 17.5.5 (VisualStudio.17.Release/17.5.5+33627.172)

**Comment by christothes** [comment]
Hi @michalkrzych 
A few questions:
- Could you clarify how you are signing into Visual Studio? 
- What happens if you sign in via `InteractiveBrowerCredential`?
- Are you able to sign in with that account to https://myapplications.microsoft.com/ ?

**Comment by michalkrzych** [comment]
Hi @christothes. Thanks for looking into this.

> Could you clarify how you are signing into Visual Studio?

I'm signed in VS via Tools > Azure Service Authentication as described in [here](https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication-local-development-dev-accounts?tabs=azure-portal%2Csign-in-visual-studio%2Ccommand-line#3---sign-in-to-azure-using-net-tooling).

> What happens if you sign in via `InteractiveBrowerCredential`?

Initially, I get the following error:

> Authentication failed. You can return to the application. Feel free to close this browser tab. 
Error details: error invalid_client error_description: AADSTS650057: Invalid resource. The client has requested access to a resource which is not listed in the requested permissions in the client's application registration. Client app ID: 04b07795-8ddb-461a-bbee-02f9e1bf7b46(Microsoft Azure CLI). Resource value from request: api://e01bec77-dbe3-4f86-bf76-56903438ac36. Resource app ID: e01bec77-dbe3-4f86-bf76-56903438ac36. List of valid resources from app registration: . Trace ID: fe77ed11-b129-4347-8b89-39887a5d0b00 Correlation ID: fabeef3e-6119-4e7c-a0ee-ea28f10a16db Timestamp: 2023-05-22 12:47:58Z

but I can get around it by adding the above client application to the Authorized client applications on the Expose an API blade of the app registration. However, unless I'm missing something, I don't think I can use the `InteractiveBrowserCredential` in my code because when my apps are deployed to azure I want them to authenticate using managed identities.

> Are you able to sign in with that account to https://myapplications.microsoft.com/ ?

Yes.

I hope this helps and please let me know if anything needs clarification. Thanks for your help.

**Comment by christothes** [comment]
> but I can get around it by adding the above client application to the Authorized client applications on the Expose an API blade of the app registration.

Have you tried adding the Client Id of your Managed Identity to the authorized client applications?

**Comment by michalkrzych** [comment]
> Have you tried adding the Client Id of your Managed Identity to the authorized client applications?

No, I haven't as I don't know where to find the Client Id of my managed identity? Just to confirm, are you referring to an ID linked to the user Im signed in with?

**Comment by christothes** [comment]
Go to the portal and select the Managed Identities blade. The client ID can be seen when you click on a specific identity. 

![image](https://github.com/Azure/azure-sdk-for-net/assets/1279263/40a07cd1-08a3-410d-bce7-c1d2ded3f115)

![image](https://github.com/Azure/azure-sdk-for-net/assets/1279263/c9c7e3c1-6ca6-4bb0-b6ab-ec626ff7a51b)

**Comment by michalkrzych** [comment]
> Go to the portal and select the Managed Identities blade. The client ID can be seen when you click on a specific identity.

Doesn't this list only User-Assigned Managed Identities? I don't have any user-assigned managed identities.

Can I just double check you are asking me to add the client ID of the managed identity of Visual Studio? My understanding is that VS is signing me in on my behalf so I have to add the VS client ID to the authorized client applications like this:

![image](https://github.com/Azure/azure-sdk-for-net/assets/6545828/51071137-1fcc-46bc-a401-19127b4fad0f)

**Comment by christothes** [comment]
> Doesn't this list only User-Assigned Managed Identities? I don't have any user-assigned managed identities.

Sorry, for system assigned identities, you would find them in the Enterprise Applications section of the Azure AD blade

> Can I just double check you are asking me to add the client ID of the managed identity of Visual Studio? My understanding is that VS is signing me in on my behalf so I have to add the VS client ID to the authorized client applications like this:

For authentication with VisualStudioCredential, yes.

**Comment by michalkrzych** [comment]
> Sorry, for system assigned identities, you would find them in the Enterprise Applications section of the Azure AD blade

No problem. I'm still confused as why I would need the system-assigned managed identity ID/clientID? When I deploy to Azure, the DefaultAzureCredential is working fine, I'm just struggling when developing locally and when I am signed in as an external/guest user.

> > Can I just double check you are asking me to add the client ID of the managed identity of Visual Studio? My understanding is that VS is signing me in on my behalf so I have to add the VS client ID to the authorized client applications like this:
> 
> For authentication with VisualStudioCredential, yes.

I have done that - unless we're talking something different than the screenshot in my previous reply?

**Comment by michalkrzych** [comment]
After playing around with this I found a way of signing in with the organization account for the correct tenant with VS (you do this when you are a guest in another tenant and want to request a token). For anyone facing this issue in the future, here are the steps to get a valid token:

1. Click on your signed in account in VS in the right top corner of VS and click on Account Selection.
2. Find your currently logged in account in the list of accounts and click Remove (on the right hand side of it (next to Apply filter...))
3. After you're logged out, in the same window click on **Sign In**
4. On the Sign In screen that pops up select **Use another account**
5. Now, select **Sign-in options**, and then **Sign in to an organisation** (if you notice the icon is different when signing in to an organisation account - it has a little ID badge)
6. Type in the domain name of the organisation, and then you proceed to sign in as you normally would.
