### ISSUE TITLE
Create or Update a Certificate

### ISSUE THREAD

**Issue by InteXX** [Azure/azure-sdk-for-net#36403]
### Library name and version

Azure.ResourceManager.*

### Query/Question

What is the SDK equivalent of [this REST API](https://learn.microsoft.com/en-us/rest/api/appservice/certificates/create-or-update)?

Unfortunately, the SDK is so poorly documented that—after two full days of digging—I finally have to ask.

### Environment

Win11 .NET 7
VS 17.5.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by InteXX** [comment]
Very good, thank you.

**Comment by HarveyLink** [comment]
Hi @InteXX , Thank you for using Azure SDK for .NET.
For the question you asked, you could use [Azure.ResourceManager.AppService](https://www.nuget.org/packages/Azure.ResourceManager.AppService/1.1.0-beta.1)
Some samples to refer: https://github.com/Azure/azure-sdk-for-net/blob/4ad03915537453b5b15b61b65ee2af74144e094d/sdk/websites/Azure.ResourceManager.AppService/tests/TestsCase/CertificatesCollectionTests.cs#L32
