### ISSUE TITLE
[QUERY] FindBlobsByTags not returning all tags but the tags specified in expression

### ISSUE THREAD

**Issue by a2741890** [Azure/azure-sdk-for-net#36406]
### Library name and version

Azure.Storage.Blobs 12.12.0

### Query/Question

When I first used the BlobContainerClient.FindBlobsByTagsAsync method, I was expecting to use one tag to retrieve all tags of the blob (Given that the TaggedBlobItem has the property _Tags_ in IDictionary<string, string> type). For example if the blob has tag1, tag2 and tag3, the expression to find the blob by tag is like:

`FindBlobsByTagsAsync("tag1 = 'value1' ")`

And then the returned TaggedBlobItem should have property _Tags_ that contains tag1, tag2 and tag3. But there's only tag1. 

In order to retrieving all tags of the blob, I need to modify the expression to 
`FindBlobsByTagsAsync("tag1 = 'value1' AND tag2 > '' AND tag3 > ''")`
 However I don't need to filter with the rest of the tags.

 I know the document mentions that "_The expression must evaluate to true for a blob to be returned in the result set."_ (source: [https://learn.microsoft.com/en-us/rest/api/storageservices/find-blobs-by-tags?tabs=azure-ad](url)). 
But would that be better to return all tags along with the blob found at the first place? 
(Besides, the maximum number of tags assigned to a blob is limited to 10 as well as the length of the tag value, so I assume that to return all tags would not be a big problem?)

**Comment by navba-MSFT** [comment]
@a2741890 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@a2741890 The FindBlobsByTagsAsync method in the Azure.Storage.Blobs library returns the blobs that match the specified tag expression, but it does not automatically return all the tags associated with those blobs.

> **The Filter Blobs operation enables callers to list blobs across all containers whose tags match a given search expression.**
More Info [here](https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.findblobsbytagsasync?view=azure-dotnet).

If you intention is to fetch all tags, you can leverage the below sample. Hope this helps.

```
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;

// Create a BlobServiceClient object
BlobServiceClient blobServiceClient = new BlobServiceClient(connectionString);

// Get a reference to a blob container
BlobContainerClient containerClient = blobServiceClient.GetBlobContainerClient(containerName);

// Get a reference to a blob
BlobClient blobClient = containerClient.GetBlobClient(blobName);

// Get all tags of the blob
BlobTags tags = await blobClient.GetTagsAsync();
```

**Comment by a2741890** [comment]
@navba-MSFT Thank you for explaining all of these and now I got it. Regarding the documentation 

> The Filter Blobs operation enables callers to list blobs across all containers whose tags match a given search expression.

For me it still not specifies if all the tags would be returned with blob or not. It just mentions the operation will list "blobs" whose tags match a given search expression. I think that might be better to improve the documentation a little bit, but it's just my opinion. (For example, _The Filter Blobs operation enables callers to list blobs across all containers whose tags match a given search expression, and only the tags appearing in the expression will be returned with blob_)

Thank you again for your time, feel free to close this query please.
