### ISSUE TITLE
Package for Azure DevOps repository management

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [Azure/azure-sdk-for-net#36407]
Hi there,
I could not find out if there is an Azure SDK package that provides functionality like in Azure REST API's `devops/git/pull-requests` or Azure CLI's `az repos`. Is there?

Best regards.

**Comment by jsquire** [comment]
Hi @georg-eckert-zeiss.  There is no package under the Azure SDK umbrella for DevOps.   However, it does look like there is a package developed by the DevOps team that may be what you're looking for.   You may want to take a look at [this article](https://learn.microsoft.com/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops) which points at the [Microsoft.VisualStudio.ServicesClient](https://www.nuget.org/packages/Microsoft.VisualStudio.Services.Client/19.221.0-preview) package and also details their REST API.

**Comment by georg-eckert-zeiss** [comment]
> Hi @georg-eckert-zeiss. There is no package under the Azure SDK umbrella for DevOps. However, it does look like there is a package developed by the DevOps team that may be what you're looking for. You may want to take a look at [this article](https://learn.microsoft.com/azure/devops/integrate/concepts/dotnet-client-libraries?view=azure-devops) which points at the [Microsoft.VisualStudio.ServicesClient](https://www.nuget.org/packages/Microsoft.VisualStudio.Services.Client/19.221.0-preview) package and also details their REST API.

Thanks for your reply. I know that package and it looked somehow abandoned (samples repo archived). So I thought it might have moved into the Azure SDK.

Thanks anyway. The package you mentioned works.
