### ISSUE TITLE
[Enhancement] CosmosDB: Add ability to enable automatic failover

### ISSUE THREAD

**Issue by Ky7m** [Azure/azure-sdk-for-net#3642]
Using Azure CLI it is possible to enable automatic failover on creation action. 
https://docs.microsoft.com/en-us/cli/azure/cosmosdb?view=azure-cli-latest#az_cosmosdb_create
`
az cosmosdb create ... --locations "Central US"=0 "West Central US"=1 "West Europe"=2 --enable-automatic-failover "West Central US"
`
Would be great to have this functionality in Azure SDK as well.

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#2
