### ISSUE TITLE
WebApp SSL binding bug

### ISSUE THREAD

**Issue by j055** [Azure/azure-sdk-for-net#3643]
#2935 - No update since June but this is still an issue in the latest release v1.2.

I've tested in a new web app with certificate installed. The certificate binding is not added.

```
           _webApp.Update()
                .WithClientCertEnabled(true)
                .DefineHostnameBinding()
                .WithThirdPartyDomain(domain)
                .WithSubDomain(subDomain)
                .WithDnsRecordType(CustomHostNameDnsRecordType.CName)
                .Attach()
                .Apply();
```
The API doesn't allow specifying IP or SNI and I have no idea why ```WithClientCertEnabled(true)``` is stuck there.

A better way might be:

```
            _webApp.Update()
                .DefineSslBinding()
                .ForHostname(domain)
                .WithExistingCertificate(thumbprint)
                .WithSniBasedSsl()
                .Attach()
                .Apply();
```

Thanks
Andrew

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#45
