### ISSUE TITLE
[QUERY] Filter inactive/leaved thread (if ACS Chat still developing?)

### ISSUE THREAD

**Issue by l2aelba** [Azure/azure-sdk-for-net#36436]
### Library name and version

Azure.Communication.Chat

### Query/Question

I'm not sure `Azure.Communication.Chat` still developing since the last API version is `2021-09-07`
And I still not see any changes or updates after that…

---

**1. Query just only active threads**

```
GET {endpoint}/chat/threads?api-version=2021-09-07
```
This should has some parameter to filter inactive / leaved threads, so very bad performance to checking by **Get List Chat Participants**

I know this will cause the problem with pagination, but please do something or flag something…

---

**2. Metadata on ChatThreadProperties**

Someone made an issue about this #24974 about a year, please think about this.

---

We want continue using Azure in our projects, but please take the feedbacks from us.

Many issues or feature requests still open, not even say "denied" or "in progress", just holding in the backlogs. (we just keep waiting and hope you guys will do something or not…)

`Azure.Communication.Chat` is much behind **getstream.io** and **rocket.chat** (I have to say sorry)

And also please list the **Roadmap** for ACS Chat if it still developing…

Thanks.

### Environment

.NET & JS SDK & all

**Comment by navba-MSFT** [comment]
@l2aelba Thanks for reaching out to us and reporting this issue. The recent update to` Azure.Communication.Chat `happened 8 months back. See here: https://www.nuget.org/packages/Azure.Communication.Chat/1.1.1

I am doing some research on your ask regarding `Metadata on ChatThreadProperties`. I had a follow-up question on `Query just only active threads`. Could you please elaborate on your ask ?

Are you referring to [List Chat Threads REST API ](https://learn.microsoft.com/en-us/rest/api/communication/chat/chat/list-chat-threads?tabs=HTTP) or the[ List Chat Participants ](https://learn.microsoft.com/en-us/rest/api/communication/chat/chat-thread/list-chat-participants?tabs=HTTP)? Also please explain your use case and the expected feature.

**Comment by l2aelba** [comment]
@navba-MSFT Thanks.

Example if I build 1-1 chat app and when user leaved the thread, it just should not be listed by [List Chat Threads](https://learn.microsoft.com/en-us/rest/api/communication/chat/chat/list-chat-threads?tabs=HTTP)

Think about a user had 100 threads and the app has to call 100 x [List Chat Participants](https://learn.microsoft.com/en-us/rest/api/communication/chat/chat-thread/list-chat-participants?tabs=HTTP) for just checking about "my user is inside or not" ? as I tested I will use about 7-20 secs to run the process and very lag with huge HTTP request for low-end devices or bad internet connections. (I know we can do lazy load but still not good performance for low-end devices)

We just need some every simple param to filter [List Chat Threads](https://learn.microsoft.com/en-us/rest/api/communication/chat/chat/list-chat-threads?tabs=HTTP) just showing the thread list just user only inside.

**Not just only me need this:**

https://learn.microsoft.com/en-us/answers/questions/554864/facing-issue-during-get-active-chat-threads
https://feedback.azure.com/d365community/idea/98be94dd-a1d6-ec11-a81b-0022484ee92d

**Comment by navba-MSFT** [comment]
@l2aelba Thanks for getting back. I am checking this internally with the Product Owners. I will get back to you once I have more details on this.

**Comment by l2aelba** [comment]
thanks @navba-MSFT

**Comment by navba-MSFT** [comment]
@l2aelba I am yet to hear back from Product Owners. I will update this chat once I have an update.

**Comment by l2aelba** [comment]
Still no luck ? @navba-MSFT

**Comment by navba-MSFT** [comment]
@l2aelba The Point of contact from Product Group is on leave. I should have an update in couple of days. I will keep you posted. I sincerely apologize for the delay due to this. We appreciate your patience.

**Comment by l2aelba** [comment]
@navba-MSFT Thanks for info, I hope we gonna get some good news after they came.

**Comment by navba-MSFT** [comment]
@l2aelba Thanks for your reply. I have got the update from the Product Owners. Please find below the reply in-line to your ask.



> **_Ask #1_** :
  **Can the [List Chat Threads API](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Frest%2Fapi%2Fcommunication%2Fchat%2Fchat%2Flist-chat-threads%3Ftabs%3DHTTP&data=05%7C01%7Cnavba%40microsoft.com%7C8491e401bbd04df8233508db62f3abc1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638212570969820440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LUF2lwy21Gsf8DUSbyNy79nFStP5DyRwiRZ4R7aTYwM%3D&reserved=0)  have a way to filter inactive / left threads ?** 

_**Reply:**  This is in our backlog, but we have some higher priority items at this time. So no ETA at the moment._



> **Ask #2:** **Being able to store metadata on the chat thread just like what's already possible with chat messages. Similar ask was reported here too [#24974](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-for-net%2Fissues%2F24974&data=05%7C01%7Cnavba%40microsoft.com%7C8491e401bbd04df8233508db62f3abc1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638212570969976666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oewJgEXowQfnHKs1C0AE4gZRE0GySRpthF9%2FCOgUSlg%3D&reserved=0).**

_**Reply:** Tentative timeline is CY23 Q3 ( End of September'23)_




>**Ask #3:** **Is there any active development release happening in Azure.Communication.Chat library ?** 

_**Reply:** We are working on other features that do not require SDK updates which is why the new versions are not seen for this library in the recent past._

**Comment by l2aelba** [comment]
Thanks so much @navba-MSFT
