### ISSUE TITLE
How does one provide an array for a string according to the instructions?

### ISSUE THREAD

**Issue by tvanriper** [Azure/azure-sdk-for-net#36441]
Instructions for 'Input' property claims one may pass an array of strings instead of a string if one wants to get embeddings for multiple inputs.

It isn't clear to me how one does that in a type-safe language when the type doesn't provide this as an option.  Are we meant to convert the array to a single string separated by some particular character?  Using "Convert.ToString()" doesn't seem to work, as one only gets a single embedding.  The compiler doesn't allow explicit casting (e.g. (string)embeddings) in this situation.  Nothing seems to work.

Or, perhaps, these instructions are meant for a different language?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f9cb424b-c8d1-9f2d-8e58-b9c75f67d969
* Version Independent ID: 22e955f5-bb14-ff56-9c67-92f07187321c
* Content: [EmbeddingsOptions Class (Azure.AI.OpenAI) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.ai.openai.embeddingsoptions?view=azure-dotnet-preview)
* Content Source: [xml/Azure.AI.OpenAI/EmbeddingsOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.AI.OpenAI/EmbeddingsOptions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by ashikns** [comment]
@PramodValavala-MSFT The non Azure version of OpenAI does support array as embeddings input, and is in fact quite necessary to not hit rate limits. Since this is also advertised as supporting normal OpenAI, any chance of adding array support to sdk?

**Comment by 3aIno** [comment]
@PramodValavala-MSFT - Is there an expectation as to when an updated NuGet will be released?

**Comment by PramodValavala-MSFT** [comment]
@trrwilson Do you have any insights about the next release that you can share here? Thanks!
