### ISSUE TITLE
[BUG] Failing authentication when using EventGrid triggered Azure Function with Blob input

### ISSUE THREAD

**Issue by HazNut** [Azure/azure-sdk-for-net#36477]
### Library name and version

Azure.Storage.Blobs 12.13.1 Azure.Identity 1.8.2 Microsoft.Azure.EventGrid 1.3.0 Microsoft.NET.Sdk.Functions 4.1.1

### Describe the bug

Hi,
Recently been having an issue when trying to trigger an EventGrid triggered Azure Function with a Blob input.

I'm triggering a function (.NET 6 / v4) running locally in Visual Studio using a payload from Postman, using a similar URL to http://localhost:7071/runtime/webhooks/EventGrid?functionName=FooBar. DefaultAzureCredential is invoked, which tries each authentication method.

For reference, I'm running this on an Azure Virtual Desktop, and I'm signed into an account where the default tenant is NOT the tenant we want to use, as we are doing work for another client that's on another tenant.

From checking the logs, EnvironmentCredential fails, then it moves onto ManagedIdentityCredential, which calls http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED to get a token. It apparently succeeds, the issue being that it's using the wrong tenant ID, and as far as we know there's no way to force it to use a different tenant ID. This step would normally fail, as it does for my coworker as he's not using a Virtual Desktop. but because I'm on an Azure Virtual Desktop it apparently has Managed Identity set up on it, so calls to that endpoint will succeed, but again it's using the wrong tenant ID so the token we get is invalid.

So after a lot of messing around we eventually blocked access to that IP address in Windows Defender to force it to move onto the next authentication method, that being VisualStudioCredential. This fails again because the default tenant being used on Visual Studio is not the one we want to use, and we don't seem to be able to change that, so it uses the wrong tenant ID again.

So then I just signed out of Visual Studio to force that authentication method to fail, and it moves onto AzureCliCredential, which does work because I can force the correct tenant there through the command line.

We think this is an issue with the Azure.Identity library, as with AppAuthentication you were able to override the authentication method using "AzureServicesAuthConnectionString": "RunAs=Developer; DeveloperTool=AzureCli", in local.settings.json. But in this case we're using Azure.Identity and this doesn't seem configurable anymore.

I will note that this token issue probably isn't specific to functions with a Blob input, we were having a similar issue with a regular endpoint that just takes in an EventGrid event. But in that case it was more an issue of being unable to raise another EventGrid event after triggering an endpoint, because of the token being invalid for the same reasons.

This was a lot of work just to be able to run a function locally, and I guess we do have a special set of circumstances here, being on an Azure Virtual Desktop and trying to use a different tenant. But it would be nice to be able to force a specific authentication mechanism, or to find some other resolution that doesn't involve having to block an IP address etc.

### Expected behavior

Be able to configure the authentication mechanism used.

### Actual behavior

(See description)

### Reproduction Steps

Call an EventGrid triggered Azure Function locally, with a Blob input, through Visual Studio, on an Azure Virtual Desktop while signed into an account with multiple tenants, where the relevant tenant is not the default one.

### Environment

Visual Studio Enterprise 2022 17.5.5
Azure Function app (v4, .NET 6)
Windows 11 Enterprise Version 10.0.22000 Build 22000

(dotnet --info output)
.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  6.0.311 [C:\Program Files\dotnet\sdk]
  7.0.203 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by jsquire** [comment]
Hi @HazNut.  Thank you for reaching out and we regret that you're experiencing difficulties.  To use a different tenant with Azure Functions, the most straightforward approach is to configure the desired TenantId in your settings.   Details and discussion on doing so can be found in the [Local development with identity-based connections](https://learn.microsoft.com/azure/azure-functions/functions-reference?tabs=queue#local-development-with-identity-based-connections) section of the Azure Functions developer guide.

If you have more extensive needs for customization - such as controlling which credential type or set of credential options is used - that can be done using [Dependency Injection for Azure Functions](https://learn.microsoft.com/azure/azure-functions/functions-dotnet-dependency-injection#register-services) and specifying the credential that you'd like to use by calling [UseCredential](https://learn.microsoft.com/dotnet/api/microsoft.extensions.azure.azureclientfactorybuilder.usecredential?view=azure-dotnet).  So long as no other credential is specified in your settings, the credential passed to `UseCredential` will be used for all Azure SDK types used by the bindings or passed to the Function invocation.
