### ISSUE TITLE
[BUG] Cannot remove all tags from a runbook resource

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#36472]
### Library name and version

Azure.ResourceManager.Automation 1.01, Azure.ResourceManager 1.5

### Describe the bug

Clearing the Tags property of the AutomationRunbookPatch class, does remove any tags when invoking the AutomationRunbookResource.UpdateAsync method. Note that it is possible to remove and replace one or more existing tags, so long as the tags property is not empty when calling the Patch method.

### Expected behavior

You should be able to remove all  tags from a runbook resource.

### Actual behavior

You cannot clear the tags from a runbook resource.

### Reproduction Steps

1. Create a runbook resource in Azure Automation and give it one or more tags (you could do this using either the Azure portal, or using the IAutomationRunboolCollectionClient.CreateOrUpdateAsync method.

2. Update the resource created in step 1 using the PatchAsync  method. The tags property of the AutomationRunbookPatch class instance should be empty.

3. Expected: the runbook should be updated and no longer have any tags. Actual: no tags were removed

### Environment

Windows 10
Visual Studio 2022 (17.4.4)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @davecader Thank you for using Azure SDK for .NET.
Our sdk will not serialize when the property value is empty. If the `Tag = {}` nothing will send to the server. It's by design.
Instead, you could use `RemoveTag` method to operate the tag value of a resource.
