### ISSUE TITLE
Mock .WithSnapshot(string snapshot) using Moq-framework

### ISSUE THREAD

**Issue by Fazer01** [Azure/azure-sdk-for-net#36505]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Query/Question

Hi, 

Is there a possibility to mock (using Moq framework) the `.WithSnapshot()` method on the BlobClient? Currently the `.WithSnapshot()` method is not defined as `virtual` so Moq cannot create an "override" for this specific method. Calls like `DeleteAsync()` or `UploadAsync()` can be mocked without any problem. 

In my testing code: 
```csharp   
_blobClientMock = new Mock<BlobClient>(MockBehavior.Strict);
_blobClientSnapshotMock = new Mock<BlobClient>(MockBehavior.Strict);
_blobClientMock.Setup(x => x.WithSnapshot(mockedBlobItemSnapShot1.Name)).Returns(_blobClientSnapshotMock.Object);
```

Error when I debug / run the test: 

```txt
System.NotSupportedException : Unsupported expression: x => x.WithSnapshot(mockedBlobItemSnapShot1.Name)
Non-overridable members (here: BlobClient.WithSnapshot) may not be used in setup / verification expressions.
```

I know we can do it the "hard" way by wrapping things etc. but I was wondering if we could avoid this and if there are any other solutions to do this.

Thanks in advance, 

Tom

### Environment

Azure Functions Runtime 4 and .NET6.0
Microsoft Visual Studio Enterprise 2022 (64-bit) - Preview
Version 17.7.0 Preview 1.0

**Comment by amnguye** [comment]
Let me look into this. I'm trying to figure out why the inherited class on the `BlobBaseClient.WithSnapshot` isn't being used over the `BlobClient.WithSnapshot` since they are both essentially the same thing, but the API looks a little different.

Sorry for the inconvenience. If possible I think you can still use the `BlobBaseClient.WithSnapshot` instead since that one is `virtual`, as a mitigation for now.

**Comment by Fazer01** [comment]
Using the following setup in combination with NSubstitute, works perfectly fine for me: 

```csharp
 BlobItem? mockedBlobItem = BlobsModelFactory.BlobItem("OriginalItem");
 BlobItem? mockedBlobItemSnapShot1 = BlobsModelFactory.BlobItem("OriginalItem", snapshot: DateTime.UtcNow.AddMonths(-10).ToString("O"));

 Page<BlobItem> page = Page<BlobItem>.FromValues(new List<BlobItem> { mockedBlobItem, mockedBlobItemSnapShot1 }, null, Substitute.For<Response>());
 AsyncPageable<BlobItem> pageable = AsyncPageable<BlobItem>.FromPages([page]);

 _blobContainerClientMock.GetBlobsAsync(BlobTraits.Metadata, BlobStates.Snapshots, $"{Constants.SomeConfigurationFolder}/", CancellationToken.None).Returns(pageable);

 _blobClientFactoryMock.CreateClient(Arg.Any<Guid>(), Arg.Any<string>()).Returns(_blobContainerClientMock);
```
