### ISSUE TITLE
Question on cyclic dependency in fluent packages

### ISSUE THREAD

**Issue by karataliu** [Azure/azure-sdk-for-net#3652]
To use any fluent package, it will get start with IAzure interface, which is in `Microsoft.Azure.Management.Fluent`
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.fluent.iazure?view=azure-dotnet

But `Microsoft.Azure.Management.Fluent` depends all other fluent component, that means if user only wants to operate with VM, he'll also need to install `Microsoft.Azure.Management.Fluent`, and thus all non-VM related packages.

If so, what's the value for splitting those packages? Why not provide a single package to include all, since user has to indeed install all?

Could someone please clarify the design? Please also guide the correct way for using the fluent SDK packages.

**Comment by martinsawicki** [comment]
You don't have to work with the entire Azure rollup package, if you just need a service-specific subset.
You'd authenticate via that service's specific Manager, e.g. 
```csharp
IComputeManager computeManager = ComputeManager.Authneticate(...);
```

The corresponding `I*Manager` exposes only its own subset of resource collections - much less than `IAzure`.

If you want to pick and choose which manager you want to work with, you need to authenticate with each explicitly, like above.

You can also see some more advanced examples in the [tests](https://github.com/Azure/azure-sdk-for-net/blob/Fluent/Tests/Fluent.Tests/Common/TestHelper.cs).  

(Note though that some more complex services, such as Compute, have a dependency on some other service packages as well, but far from all that is in the Azure rollup package)

**Comment by karataliu** [comment]
Yeah, that did the trick. Appreciate the help.

It would be nice to have a note in README, since most people will get start there. Current examples are all using IAzure.
