### ISSUE TITLE
[BUG] Interop Exception Hanging Up from ACS Call on UWP

### ISSUE THREAD

**Issue by miguelarcilla** [Azure/azure-sdk-for-net#36530]
### Library name and version

Azure.Communication.Calling 1.0.0-beta.36

### Describe the bug

I've tested the code sample in the following Microsoft documentation for adding video calling to a UWP app:
[https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-video-calling?pivots=platform-windows](url)

After completing a call and clicking the "Hang Up" button, the following exception is thrown:

```
System.Runtime.InteropServices.MissingInteropDataException
HResult=0x80131500
Message=System.Collections.Generic.IEnumerable`1[Azure.WinRT.Communication.ICommunicationIdentifier] is missing interop type marshalling data. To enable interop type marshalling data, add a MarshalObject directive to the application rd.xml file. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=393965
```

This occurs on Windows 11 as well as on HoloLens 2

### Expected behavior

Calls can be initiated and ended without exceptions being thrown, or more details added to the documentation on how to configure the application to prevent COM Interop errors from being thrown.

### Actual behavior

COM Exception is thrown with the following message:

```
System.Runtime.InteropServices.MissingInteropDataException
HResult=0x80131500
Message=System.Collections.Generic.IEnumerable`1[Azure.WinRT.Communication.ICommunicationIdentifier] is missing interop type marshalling data. To enable interop type marshalling data, add a MarshalObject directive to the application rd.xml file. For more information, please visit http://go.microsoft.com/fwlink/?LinkID=393965
```

### Reproduction Steps

- Complete the code sample provided in this link: [https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/voice-video-calling/get-started-with-video-calling?pivots=platform-windows](url)
- Run the application and initiate a call (Example user "8:echo123")
- Click the "Hang Up" button

### Environment

**Hosting platform or OS and .NET runtime version** Windows 11 (10.0; Build 22000), .NET Core UWP 6.2.14
**IDE and version :** Visual Studio 17.5.5

**Comment by navba-MSFT** [comment]
Adding service team to look into this.

**Comment by jowang-msft** [comment]
Yes, this issue was fixed in the GA SDK and more recent releases.

Azure.Communication.Calling 1.0.0-beta.36 was officially deprecated.
