### ISSUE TITLE
[BUG] The documentation doesn't document anything. Specifically Azure AD access.

### ISSUE THREAD

**Issue by Neutrino-Sunset** [Azure/azure-sdk-for-net#36546]
### Library name and version

Microsoft.Azure.Management.Graph.RBAC.Fluent 1.38.1

### Describe the bug

The Azure SDK document home page is here
https://learn.microsoft.com/en-us/dotnet/azure/sdk/azure-sdk-for-dotnet

Nothing in this entire documentation says anything about accessing the Azure AD. None of the samples linked from here do anything with the Azure AD apart from basic authentication.

The Azure SDK API reference is here
https://learn.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet&preserve-view=true

None of the overviews for any of the libraries provide any overview of what the library is actually for. The overview for Azure Graph RBAC literally just repeats the name of the library

![image](https://github.com/Azure/azure-sdk-for-net/assets/18445931/77df6891-d6f6-41d6-af08-67c670a8a04f)

The package link on the overview page links to a NuGet page that says "this package is being phased out, please see https://aka.ms/azsdk/dotnet/mgmt" and the link doesn't describe what it's being replaced with.

I want to access ServicePrincipal information in order to check for credentials that are near to expiring. Something that can be done using the PowerShell cmdlet `Get-MsolServicePrincipal`. How do I do this using the SDK? After two days of searching I haven't found anything remotely useful.

The documentation for this entire SDK is worse than anything I have ever seen.

### Expected behavior

I would expect the documentation to describe what the various libraries do and how to use them.

### Actual behavior

The documentation is just useless lists of package and method names.

### Reproduction Steps

Open the docuentation here https://learn.microsoft.com/en-us/dotnet/azure/sdk/azure-sdk-for-dotnet

Now try and work out how to get information about Identity Objects in the Azure Directory.

Good luck with that.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @Neutrino-Sunset this sdk is being deprecated, please to [Microsoft.Graph](https://www.nuget.org/packages/Microsoft.Graph) and here is document site for this SDK https://learn.microsoft.com/en-us/graph/sdks/sdks-overview
