### ISSUE TITLE
[BUG] Azure Batch may return 409 JobExists error when creating unique JobId

### ISSUE THREAD

**Issue by Chris-Johnston** [Azure/azure-sdk-for-net#36549]
### Library name and version

Microsoft.Azure.Batch 15.3.0

### Describe the bug

I'm using the Microsoft.Azure.Batch 15.3.0 library to create up to a few hundred Azure Batch Jobs from a Azure Functions, in parallel. Each of these Jobs has a unique and randomly-generated JobId. We intermittently run up against the ratelimits for the Azure Batch Service, but the client does a good job of handling retries.

Intermittently, the Batch Client throws an exception with the message: `Operation returned an invalid status code 'Conflict'` `Error Code = JobExists`. (The stack trace does not include the ClientRequestId field, seemingly because it was not provided in the response.)

Our workflow does the following:
1. Generate a unique JobId
2. Check that this JobId does not exist: `await batchClient.JobOperations.GetJobAsync(jobId) == null`
3. Create the new Job: `var job = this.batchClient.JobOperations.CreateJob(...);`
4. and Commit it: `await job.CommitAsync();`

When checking the `dependencies` table in App Insights, which logs all of the outgoing HTTP requests that are made, I see two related to this operation:

1. The first request, sent at time 0, goes to `POST /job` and receives a 429.
2. The second request, 60 ish seconds later, goes to `POST /job` and receives a 409.

I've also confirmed that nothing is running concurrently, and trying to create jobs with the same JobId. After checking in the Portal, the JobId I tried to create does get created, despite the error code response.

This seems to me more of an issue with the Batch API itself, and not the SDK.

As a workaround, I've done the following:

```cs
// ensure job doesn't already exist
if (await batchClient.JobOperations.GetJobAsync(jobId) != null) return;

try
{
  await job.CommitAsync();
}
catch (BatchException batchEx) when
  (batchEx.RequestInformation.HttpStatusCode == HttpStatusCode.Conflcit &&
   batchEx.RequestInformation.BatchError.Code == BatchErrorCodeStrings.JobExists)
{
  // log that we encountered a duplicate, but assume that JobId exists and continue with the rest of the workflow
}
```

### Expected behavior

The expected behavior is the following:

1. We check that the Job does not exist.
2. It doesn't, and so the API returns 404.
3. The SDK issues the request to create the job: `POST /job`
4. The API may ratelimit us, and return 429.
5. The SDK waits before retrying a new request some time later, with a new clientRequestId: `POST /job`
6. The API returns a successful status code that the job was created

### Actual behavior

The observed behavior is the following:

1. We check that the Job does not exist.
2. It doesn't, and so the API returns 404.
3. The SDK issues the request to create the job: `POST /job`
4. The API ratelimits us, and returns 429.
5. The SDK waits before retrying a new request some time later, with a new clientRequestId: `POST /job`
6. The API returns a 409 Conflict status code, and the SDK throws a BatchException:

```
Microsoft.Azure.Batch.Common.BatchException: Operation returned an invalid status code 'Conflict'
 ---> Microsoft.Azure.Batch.Protocol.Models.BatchErrorException: Operation returned an invalid status code 'Conflict'
   at Microsoft.Azure.Batch.Protocol.JobOperations.AddWithHttpMessagesAsync(JobAddParameter job, JobAddOptions jobAddOptions, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.ExecuteRequestWithCancellationAsync(Func`2 func)
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.ExecuteRequestAsync()
   --- End of inner exception stack trace ---
   at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.ExecuteRequestAsync()
   at Microsoft.Azure.Batch.ProtocolLayer.ProcessAndExecuteBatchRequest[TResponse](IBatchRequest`1 request, BehaviorManager bhMgr)
   at Microsoft.Azure.Batch.CloudJob.CommitAsync(IEnumerable`1 additionalBehaviors, CancellationToken cancellationToken)
[Redacted stacktrace]
Request Information
ClientRequestId:
RequestId:b661ec48-4282-433e-816f-ab547bbc859e
HttpStatusCode:Conflict
StatusMessage:The specified job already exists.


Error Code = JobExists, Lang=en-US, Message = The specified job already exists.
RequestId:b661ec48-4282-433e-816f-ab547bbc859e
Time:2023-05-20T14:41:53.3323206Z
Additional Values:
```

The issue is very intermittent, but not never. The most recent occurrence was on 5/20, and previously on 5/14.

The following screenshot shows the App Insights dependencies logs. We create 2 Jobs at the same time, "JobA" and "JobB". "JobA" doesn't exist, so we create it, add some tasks, and poll for it's completion. "JobB" doesn't exist, and so we attempt to create it, get a 429, wait, and try again and get a 409.

Both JobA and JobB are created succesfully, but we get an exception when JobB "already exists".

![Screenshot of outgoing requests to the Batch API](https://github.com/Azure/azure-sdk-for-net/assets/16418643/4d9e3188-f8b8-4cb1-a203-7890eccd88e8)

| Request Timestamp | Request description | ClientRequestId |
| - | - | - |
| 5/14/2023 7:31:52.5160 | First attempt to `POST /jobs` for JobB, which returned 429. | `123109a9-56f7-4064-b0f3-f71fa8022923` |
| 5/14/2023 7:32:54.170 | Second attempt to `POST /jobs` for JobB, which returned 409. | `6fa6f05d-9238-46e1-8409-673d443145d7` |

I have another example, with client requestIds, from 4/24:

| Request Timestamp | Request description | ClientRequestId |
| - | - | - |
| 4/24/2023 14:31:08.2520 | First attempt to `POST /jobs` for JobB, which returned 429. | `56a1864d-6cde-4242-b097-ddc5a94f75bd` |
| 4/24/2023 14:32:09.7250 | Second attempt to `POST /jobs` for JobB, which returned 409. | `2224562d-040d-4fbc-987c-d97eddbc1270` |

### Reproduction Steps

This issue only seems to happen at a large enough scale, where concurrent Tasks are running up against the Azure Batch rate limits.

```cs
var batchClient = BatchClient.Open(new BatchSharedKeyCredentials("batch url", "account name", "account key"));
var jobId = $"foo{Guid.NewGuid()}";

if (batchClient.JobOperations.GetJobAsync(jobId) != null) return;

// job does not exist at this point

var createJobOperation = batchClient.JobOperations.CreateJob(jobId, new PoolInformation { PoolId = "poolId" });
await createJobOperation.CommitAsync(); // exception is thrown upon 409 JobExists error returned
```

### Environment

- Azure Functions runtime v4
- Windows
- netcoreapp3.1
- Microsoft.Azure.Batch 15.3.0

This same code is deployed in a prod and test environment. The issue seems to only affect prod, despite them both running with the same scale.

I had to omit some internal details, like batch account name, job name, and internal logs for this Issue. I can be reached over email or Teams at chrijoh@microsoft.com . Please ping me, I'd be happy to share the extra context I couldn't include here.

**Comment by jsquire** [comment]
Hi @Chris-Johnston.  Thank you for reaching out and we regret that you're experiencing difficulties. The error code that you're seeing is returned by the Azure Batch service directly and isn't something that the client library can influence or control.  Unfortunately, this repository is focused on the Azure SDK for .NET and we're unable to assist with other Azure issues.  Your best path forward to report a service error would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.

**Comment by Chris-Johnston** [comment]
Thanks Jesse, I'll continue to follow up with Azure support.
