### ISSUE TITLE
[BUG] RecognizeEntitiesAsync returns error on documents exceeding 5120 text elements

### ISSUE THREAD

**Issue by bm3n** [Azure/azure-sdk-for-net#36551]
### Library name and version

Azure.AI.TextAnalytics 5.2.0

### Describe the bug

Per documentation, documents exceeding5120 text elements should be submitted via asynchronous method ` RecognizeEntitiesAsync`, however, even for relatively modest sized documents this results in an `InvalidDocument` error.

### Expected behavior

Should process document successfully and return a `CategorizedEntityCollection` results object.

Per [the data-limits documentation](https://learn.microsoft.com/en-us/azure/cognitive-services/language-service/concepts/data-limits) the maximum characters per document for the asynchronous API should be 125,000 text elements.

> All other pre-configured features (asynchronous) | 125,000 characters across all submitted documents, as measured by StringInfo.LengthInTextElements (maximum of 25 documents).

### Actual behavior

Returns the following error:

```
A document within the request was too large to be processed. Limit document size to: 5120 text elements. For additional details on the data limitations see https://aka.ms/text-analytics-data-limits
Status: 200 (OK)
ErrorCode: InvalidDocument

Content:


Headers:
x-envoy-upstream-service-time: 5
Set-Cookie: REDACTED
apim-request-id: c6678fe5-db6a-441c-a5c8-bb03063be43a
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
x-ms-region: REDACTED
Date: Fri, 26 May 2023 18:39:11 GMT
Content-Length: 438
Content-Type: application/json; charset=utf-8
```

### Reproduction Steps

```
string document = @"We love this trail and make the trip every year. The views are breathtaking and well
					worth the hike! Yesterday was foggy though, so we missed the spectacular views.
					We tried again today and it was amazing. Everyone in my family liked the trail although
					it was too challenging for the less athletic among us.
					Not necessarily recommended for small children.
					A hotel close to the trail offers services for childcare in case you want that.";

string longDocument = document;

while (longDocument.Length < 5120) { longDocument += "\r\n" + document; }

var documentInfo = new StringInfo(longDocument);
Console.WriteLine($"Document is {documentInfo.LengthInTextElements} text elements long.");

try
{
	Response<CategorizedEntityCollection> response = await client.RecognizeEntitiesAsync(longDocument);
	CategorizedEntityCollection entitiesInDocument = response.Value;

	Console.WriteLine($"Recognized {entitiesInDocument.Count} entities:");
	foreach (CategorizedEntity entity in entitiesInDocument)
	{
		Console.WriteLine($"    Text: {entity.Text}");
		Console.WriteLine($"    Offset: {entity.Offset}");
		Console.WriteLine($"  Length: {entity.Length}");
		Console.WriteLine($"    Category: {entity.Category}");
		if (!string.IsNullOrEmpty(entity.SubCategory))
			Console.WriteLine($"    SubCategory: {entity.SubCategory}");
		Console.WriteLine($"    Confidence score: {entity.ConfidenceScore}");
		Console.WriteLine("");
	}
}
catch (RequestFailedException exception)
{
	Console.WriteLine($"Error Code: {exception.ErrorCode}");
	Console.WriteLine($"Message: {exception.Message}");
}
```

### Environment

.NET 6 (LTS) console application running on Windows 10 Enterprise 22H2 (19045.2965) compiled in Visual Studio 2022 (17.6.2)

**Comment by jsquire** [comment]
Hi @bm3n.  Thank you for reaching out and we regret that you're experiencing difficulties. The error code that you're seeing is returned by the Text Analytics service directly and isn't something that the client library can influence or control.  Unfortunately, this repository is focused on the Azure SDK for .NET, we're unable to assist with other Azure issues.  Your best path forward to report a service error would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
