### ISSUE TITLE
Nested directories are very slow to download from ADLS

### ISSUE THREAD

**Issue by rsmith54** [Azure/azure-sdk-for-net#3660]
When downloading (smallish) nested directories recursively from an ADLS, downloads can be very, very slow.  Additionally, there is no verbosity flag to find out if *anything* is happening, which makes it very difficult to debug. I believe there might be some duplication of the index dictionary that is created, but it also would be great if this index creation could be multithreaded.  This could drastically increase download speed, since on these nested directories, the time to create the index dictionary dwarfs the actual network-limited download time.

**Comment by ro-joowan** [comment]
@rsmith54 Thanks for noting this.  Is trying out a new version of the .NET ADLS SDK an option for you?

Github: https://github.com/azure/azure-data-lake-store-net
Nuget: https://www.nuget.org/packages/Microsoft.Azure.DataLake.Store/

**Comment by rsmith54** [comment]
@ro-joowan Sure, is there was there any work on this specific issue? Thanks for your reply.

**Comment by ro-joowan** [comment]
@rsmith54 The hope is that the download speed will no longer be unbearable after the switch, since it's a completely new SDK.  Please report back here on what you find :)

If it's still slow, we can move forward from there.

**Comment by rsmith54** [comment]
Okay great, thanks for your help.
