### ISSUE TITLE
[BUG] Getting odata.error "InvalidInput" when using Azurite and oData syntax with 'and' filter expression

### ISSUE THREAD

**Issue by jk-85** [Azure/azure-sdk-for-net#36614]
### Library name and version

Azure.Data.Tables

### Describe the bug

I use Azurite for local development.

I run this query. The two variables userName and userPW came from a query string (e.g. http://192.168.1.54:7015/api/Command?Login&userName=Peter&userPW=abc). I'm using Azure functions.

The following code runs via "await Task.Run(() => [class-instance].[methodname]")

The weird is, when I hardcode the String "User eq 'Peter' and Password eq 'abc" it works fine and I got 1 result. But if I insert the variables, I'm getting the odata.error.
`
                Pageable<TableEntity> oDataQueryEntities =
                    tableClient.Query<TableEntity>
                    (filter: TableClient.CreateQueryFilter($"User eq '{userName}' and Password eq '{userPW}'"));
`

If I omit the second parameter, I'm also getting a result:

`                    (filter: TableClient.CreateQueryFilter($"User eq '{userName}'"));`

The table is there if I check it with the Storage Explorer.

### Expected behavior

See above

### Actual behavior

See above

### Reproduction Steps

See above

### Environment

Win10
Visual Studio Community 2022 17.6.2
Azure.Data.Tables 12.8.0
Azurite 3.22.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jk-85** [comment]
> Thank you for your feedback. Tagging and routing to the team member best able to assist.

**Comment by jk-85** [comment]
Am I right this being a bug? At the moment I didn't find a real good (simple) alternatives for my project. Have I to convert my both strings in some way?

**Comment by jk-85** [comment]
Sorry, I closed the issue (because I have no other options after writing a comment). The issue is still there.

**Comment by jk-85** [comment]
Please reopen the issue. Thanks!

**Comment by jk-85** [comment]
> `CreateQueryFilter` already does the odata escaping for you, so it would work if you removed the single quotes:
Thanks very much! For some strange reason (maybe the browser was the problem?) I tried it with and without escaping characters but in both cases I got multiple failed results back. I omit the escaping characters and it works now.
