### ISSUE TITLE
Documentation for the Microsoft.Azure.ServiceBus.Management assembly should indicate that this package is deprecated.

### ISSUE THREAD

**Issue by Jmorjsm** [Azure/azure-sdk-for-net#36622]
Documentation for the Microsoft.Azure.ServiceBus assembly should indicate that this package is deprecated.
Ideally it would also indicate where to look instead.

I found this while trying to figure out how to create a queue using servicebus sdk for .NET. I first found ManagementClient through a google search, but upon installing the nuget package, found that this is deprecated. 

Instead I am now using [this](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient?view=azure-dotnet), which appears to still be supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 62b5e848-a027-40ca-f6e0-3594b52e100c
* Version Independent ID: 085764ad-94ee-13ad-f7c5-7ce59ff33df8
* Content: [ManagementClient Class (Microsoft.Azure.ServiceBus.Management) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.management.managementclient?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.ServiceBus.Management/ManagementClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.ServiceBus.Management/ManagementClient.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
//cc: @EldertGrootenboer, @spelluru

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
