### ISSUE TITLE
Example link is broken

### ISSUE THREAD

**Issue by brandonh-msft** [Azure/azure-sdk-for-net#36626]
The link to the Client Example 404s

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ba64a2de-b490-e4f0-f056-4b215f7b48f2
* Version Independent ID: 18e628cd-bda9-0b0b-ce8a-c4a4f3062923
* Content: [Azure Data Lake Store libraries for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/data-lake-store?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/data-lake-store.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/data-lake-store.md)
* Service: **data-lake-store**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@brandonh-msft Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
The above PR has been filed and it is currently under review.
