### ISSUE TITLE
Libraries which target modern TFMs (.NETCoreApp, netstandard2.0, net461) bring in System.Net.Http package unnecessarily

### ISSUE THREAD

**Issue by ViktorHofer** [Azure/azure-sdk-for-net#36627]
Some of the libraries in this repository package reference System.Net.Http which then gets added as a dependency transitively in the consuming app. A package reference to System.Net.Http is undesireable as it brings in the entire netstandard1.x dependency graph and slows down restore. Additionally, potential future CVEs (and alerts surfaced by Component Governance) wouldn't impact libraries in this repository as the dependency would be avoided entirely.

The API exposed by System.Net.Http is already inbox in modern TFMs like .NETCoreApp, netstandard2.x and net461 and above and doesn't need to be brought in via a package reference.

If you accept a change in this domain, I would be happy to submit a PR. 

Related: https://github.com/dotnet/arcade/issues/13315

**Comment by jsquire** [comment]
//cc: @annelo-msft, @christothes, @JoshLove-msft, @AlexanderSher, @heaths, @KrzysztofCwalina, @tg-msft

**Comment by jsquire** [comment]
Hi @ViktorHofer.   Thank you for reaching out and for your offer to contribute updates.  I believe that we're interested in exploring this further, though I'm not sure whether or not there's a specific reason that we're including that reference.  There are also a number of deprecated packages in this repository on their way to retirement, which we'd want to avoid updating.

I've looped in some folks for awareness and thoughts.  Do you have a sense of which specific packages you're thinking of updating?

**Comment by ViktorHofer** [comment]
> Do you have a sense of which specific packages you're thinking of updating?

Most importantly for us, the .NET Team: Azure.Core. That said, based on my change, other libraries are also impacted as the PackageReference to System.Net.Http is defined globally in a common msbuild file.

Here's the change: https://github.com/Azure/azure-sdk-for-net/compare/main...ViktorHofer:RemoveSystemNetHttp?expand=1

**Comment by heaths** [comment]
Given this change, it seems it would only affect track 1 packages - the majority? of which are deprecated. You said you needed this for Azure.Core? It already targets netstandard2.0 and newer - some of which are explicit TFMs.

**Comment by ViktorHofer** [comment]
When referencing Azure.Core from a .NET Framework app, `System.Net.Http` is included as a transitive dependency:

<img width="404" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/7412651/db1d3497-a6b7-4257-9c0a-8910c9df1ad0">

It doesn't matter that Azure.Core also offers a .NET Standard TFM when consuming it from a .NET Framework application as the best compatible asset is chosen which is net461.

**Comment by ViktorHofer** [comment]
I'm OK with only updating Azure.Core as it sounds like that's the only affected library that's still actively supported and worked on.

**Comment by jsquire** [comment]
> @jsquire any update on the matter? Would you accept a PR to remove the Azure.Core System.Net.Http dependency?

Hi @ViktorHofer.  Based on the internal thread, it seems like we're safe to run this through some tests.  We'd be happy to accept a PR or will take a look at doing this internally once we've got some capacity to do so.

**Comment by ViktorHofer** [comment]
Cool. I just submitted https://github.com/Azure/azure-sdk-for-net/pull/36965 which removes the dependency from Azure.Core only.

**Comment by ViktorHofer** [comment]
Bot, the PR is ready and I'm waiting for a review. Please don't close this issue.
