### ISSUE TITLE
Include Azure SDK in Visual Studio Build Tools 2017 installer

### ISSUE THREAD

**Issue by HenrikR-Reviso** [Azure/azure-sdk-for-net#3670]
Azure SDK cannot be installed from the Visual Studio Build Tools 2017 installer, https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=15#

This in effect means that you need to install VS 2017 to use Azure SDK on a build server.

Please get Azure SDK included in the Visual Studio Build Tools 2017 installer.

The MSBuild team has asked that this issue is reported to the SDK team
see https://github.com/Microsoft/msbuild/issues/1888

Update:
Created a Uservoice issue for this

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/32217496-add-azure-sdk-component-to-vs-build-tools-2017

**Comment by HenrikR-Reviso** [comment]
Any comments / any plan to get the problem

**Comment by philwindsor** [comment]
+1 for this.

**Comment by zentby** [comment]
+1

**Comment by jensdotbruggeman** [comment]
Any news on this?  Visual Studio Build Tools 2017 works for nicely  , but I'm missing out on the Azure Tools / SDK part..

**Comment by shahabhijeet** [comment]
@HenrikR-Reviso this repo is for reporting issues related .NET SDK for azure services/resource providers.
I will find out the right location where this issue needs to be reported.
Thanks for your patience.

**Comment by HenrikR-Reviso** [comment]
@shahabhijeet Any news on where this issues should be reported?

**Comment by davemcuk** [comment]
+1

**Comment by HenrikRxn** [comment]
@rainersigwald Reporting to the SDK teams does not result in any progress. There ust be someone at Microsoft responsible for coordinating this kind of cross team issues....

**Comment by HenrikR-Reviso** [comment]
@rainersigwald Reporting to the SDK teams does not result in any progress.

Surely there must be someone at Microsoft responsible for coordinating this kind of cross team issues?

**Comment by HenrikR-Reviso** [comment]
Created a Uservoice issue for this

https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/32217496-add-azure-sdk-component-to-vs-build-tools-2017

**Comment by davemcuk** [comment]
50 votes ...

**Comment by nicolastakashi** [comment]
Any news?

**Comment by HenrikR-Reviso** [comment]
@shahabhijeet Please remove me as assigned as I have no way of fixing the issue or in any way moving this along

**Comment by shahabhijeet** [comment]
@HenrikR-Reviso I see you have created an entry in the uservoice, so closing this.
