### ISSUE TITLE
[QUERY] Models from Azure.ResourceManager.Compute and  Azure.ResourceManager.Network cannot be used in mocking

### ISSUE THREAD

**Issue by krizex** [Azure/azure-sdk-for-net#36705]
### Library name and version

Azure.ResourceManager.Compute
Azure.ResourceManager.Network

### Query/Question

I see there is a feature in https://github.com/Azure/autorest.csharp/issues/2112 that is closed, so I am assuming it is able to generate ModelFactory for Azure.ResourceManager.Compute and  Azure.ResourceManager.Network. Once it is done, we developer can use the ModelFactory to generate model instances for unittest. Can anyone on the team take the work and add the generated code into the repo?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @krizex , the model factory has been enabled in Network and Compute, please check the latest package.
