### ISSUE TITLE
Make build task .NET Core compatible

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3671]
Currently we have two separate build process, especially all the build tasks that are being used.
Making all the task .net core will help reduce various scripts that are being used to accommodate unix build.

**Comment by dpetillo** [comment]
Seems related to https://github.com/Azure/azure-sdk-for-net/issues/4692

I tried investigating the issue above but haven't found the build task source code.  Could you advise?

**Comment by pakrym** [comment]
The repo is building cross-plat.
