### ISSUE TITLE
[BUG] ChatThreadClient.AddParticipantAsync always returns forbidden

### ISSUE THREAD

**Issue by rdemace** [Azure/azure-sdk-for-net#36716]
### Library name and version

Azure.Communication.Chat

### Describe the bug

I'm trying to add a user to the chat thread whenever he enters an endpoint on my client application that triggers an api call that creates a record on a db saving his userid and token to be able to enters the room call and eventually the chat.

On client I'm using the UI library for ACS in React, but the problem triggers on backend.
Backend: NET CORE 7 + Entity Framework

classeVirtualeEntity.ChatThreadId = the threadId saved on the entity on my database

```
IEnumerable<CommunicationTokenScope> scopes = new List<CommunicationTokenScope>
{
  new CommunicationTokenScope("voip"),
  new CommunicationTokenScope("chat")
};

Response<CommunicationUserIdentifierAndToken> tokenResponse = await _identityClient.CreateUserAndTokenAsync(scopes);

CommunicationTokenCredential chatTokenCredentials = new(tokenResponse.Value.AccessToken.Token);

ChatClient chatClient = new(new Uri("https://xxxxxxxx.communication.azure.com/"), chatTokenCredentials);

ChatThreadClient chatThreadClient = chatClient.GetChatThreadClient(classeVirtualeEntity.ChatThreadId);

await chatThreadClient.AddParticipantAsync(new ChatParticipant(tokenResponse.Value.User));
```

### Expected behavior

await chatThreadClient.AddParticipantAsync(new ChatParticipant(tokenResponse.Value.User));

This line should add the partecipant and do no't trigger an Exception.

### Actual behavior

It won't go further and triggers an Exception that I catch but it doesn't specify anything else.

### Reproduction Steps

I create the scopes

I create the ACS user id and token with the CommunicationIdentityClient service injected:

```
private readonly CommunicationIdentityClient _identityClient;

public MyService(CommunicationIdentityClient  identityClient){
  _identityClient = identityClient;
}
```

I create the CommunicationTokenCredential with the token from the user

I create the ChatClient with that and the endpoint of my ACS Service from Azure Portal

I retrieve the ChatThreadClient from ChatClient

I launch the method AddParticipantAsync

It triggers an Exception
```

Service request failed.
Status: 403 (Forbidden)

Content:
{
  "CommunicationError": {
    "Code": "Forbidden",
    "Message": "The initiator doesn't have the permission to perform the requested operation.",
    "Details": []
  }
}

Headers:
Transfer-Encoding: chunked
MS-CV: ySHzUBvxeUKgw7cNRLTRVg.0
Strict-Transport-Security: REDACTED
api-supported-versions: REDACTED
X-Processing-Time: REDACTED
x-ms-client-request-id: ac3aa147-80cf-466c-9a5f-5fef7f268da1
X-Cache: REDACTED
X-Azure-Ref: REDACTED
Date: Wed, 31 May 2023 12:46:06 GMT
Content-Type: application/json

```

**Comment by navba-MSFT** [comment]
@rdemace Thanks for reaching out to us and reporting this issue. Could you please try granting **Contributor** RBAC permissions to your service principal and check if that helps ? Awaiting your reply.

**Comment by rdemace** [comment]
> @rdemace Thanks for reaching out to us and reporting this issue. Could you please try granting **Contributor** RBAC permissions to your service principal and check if that helps ? Awaiting your reply.

ChatPartecipant class gets as params in costructor just "CommunicationIdentifier identifier", there's no param for role 
And I got in RoleType Enum:

Attendee
Consumer
Presenter

I don't see any Contributor as value.

**Comment by rdemace** [comment]
If you meant Azure AD service principal - I'm not using that.
I'm using for authentication Identity Framework

**Comment by navba-MSFT** [comment]
@rdemace Thanks for clarifying. I am adding the service team to look into thus further.

**Comment by rdemace** [comment]
So, you got any news about that?

**Comment by mjafferi-msft** [comment]
Hi @rdemace, Could you please explain what authentication method have you used for initializing CommunicationIdentityClient 
(i.e., using connection string or using Managed Identity) and could you also confirm whether the token received in this object (Response<CommunicationUserIdentifierAndToken> tokenResponse)  has a valid expiration time.

**Comment by rdemace** [comment]
```

        private async Task<string> CreateChatThreadAsync(ClasseVirtuale classeVirtualeEntity)
        {
            CommunicationUserIdentifierAndToken communicationServiceUser = await CreateCommunicationServiceUserAsync(classeVirtualeEntity, RoleType.Presenter);
            CommunicationTokenCredential chatTokenCredentials = new(communicationServiceUser.AccessToken.Token);
            ChatClient chatClient = new(new Uri("https://classivirtuali-communicationservice.communication.azure.com/"), chatTokenCredentials);
            Response<CreateChatThreadResult> responseChatThread = await chatClient.CreateChatThreadAsync(classeVirtualeEntity.Nome, Array.Empty<ChatParticipant>());
            return responseChatThread.Value.ChatThread.Id;
        }

        private async Task<CommunicationUserIdentifierAndToken> CreateCommunicationServiceUserAsync(ClasseVirtuale classeVirtualeEntity, RoleType role)
        {
            IEnumerable<CommunicationTokenScope> scopes = new List<CommunicationTokenScope>
                {
                    CommunicationTokenScope.VoIP,
                    CommunicationTokenScope.Chat
                };

            Response<CommunicationUserIdentifierAndToken> tokenResponse = await _identityClient.CreateUserAndTokenAsync(scopes);

            List<RoomParticipant> roomParticipants = new()
            {
                new RoomParticipant(tokenResponse.Value.User, role)
            };

            _ = await _roomClient.AddParticipantsAsync(classeVirtualeEntity.RoomId, roomParticipants);

            return tokenResponse.Value;
        }
```

I do it like this. And I use the connection string from azure portal of the azure communication service

**Comment by mjafferi-msft** [comment]
Could you also verify token received in the object `Response<CommunicationUserIdentifierAndToken> tokenResponse` has a valid expiration time. If this object is populated correctly with user and token, then it means authentication is successful for the passed resource. 

Also, from the above snippet, I can see you are adding participant inside `CreateCommunicationServiceUserAsync` method using roomClient whereas in the issue description it's mentioned that participant is added using chatThreadClient `chatThreadClient.AddParticipantAsync`. The above snippet and one mentioned in the description seems to different.

**Comment by mjafferi-msft** [comment]
Okay, and did you also verified whether token received in the object Response<CommunicationUserIdentifierAndToken> tokenResponse has a valid expiration time. If this object is populated correctly with user and token, then it means authentication is successful for the passed resource.

Then, we might have to involve chat team to investigate why we are getting this forbidden error.

**Comment by rdemace** [comment]
![image](https://github.com/Azure/azure-sdk-for-net/assets/127743194/c28b2fee-6733-4c5c-9179-da5d9026733d)

I think this is the parameter and it is valid.

**Comment by mjafferi-msft** [comment]
@rdemace : So, there seems to be no issue with user and token creation. Since you are adding participant in the chat thread, can you try just for Chat scope.
**Replace** 
`IEnumerable<CommunicationTokenScope> scopes = new List<CommunicationTokenScope>
{ new CommunicationTokenScope("voip"), new CommunicationTokenScope("chat") };`
**with** 
`IEnumerable<CommunicationTokenScope> scopes = new[] { CommunicationTokenScope.Chat };`.

**Comment by rdemace** [comment]
It still gives error:

Service request failed. Status: 403 (Forbidden) Content: { "CommunicationError": { "Code": "Forbidden", "Message": "The initiator doesn't have the permission to perform the requested operation.", "Details": [] } } Headers: Transfer-Encoding: chunked MS-CV: IzO4UR2sekK80OdAzk3nyg.0 Strict-Transport-Security: REDACTED api-supported-versions: REDACTED X-Processing-Time: REDACTED x-ms-client-request-id: 03376c23-976a-434b-80e9-a3e7268781d4 X-Cache: REDACTED X-Azure-Ref: REDACTED Date: Fri, 23 Jun 2023 13:33:01 GMT Content-Type: application/json

**Comment by mjafferi-msft** [comment]
Transferring this issue to Azure Communication Services/Chat SDK team.
@juancamilor, @LuChen-Microsoft, Can someone from your team look into this issue ?

**Comment by rdemace** [comment]
It worked, Thank you very much
