### ISSUE TITLE
Fluent: would like to create/referencing NetworkSecurityGroup in VMSS definition API

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#3672]
With 1.1.3 I can't see any way to define the 'networkSecurityGroup' field for the VMSS network interface configuration part of the REST API!

From what I've seen of 1.2.0 release notes I am guessing that this functionality isn't yet added there either?

(This is what I'm talking about:

    "networkProfile": {
        "networkInterfaceConfigurations": [ {    
          "name": "nicconfig1",
          "properties": {
            "primary": true,
            "enableAcceleratedNetworking": false,
            "networkSecurityGroup": {
                "id": "/subscriptions/{subscription-id}/resourceGroups/myrg1/providers/Microsoft.Network/networkSecurityGroups/nsg1"
              },

I have heard that using this mechanism is functionally slightly different from just applying an NSG on your subnet, it gets applied on the NICS instead, hence the desire for it. Haven't been able to test it out yet though...)

**Comment by anuchandy** [comment]
It seems that IPConfig::NSG for VMSS introduced in 2017-03-30, fluent is not based on this version. In the next release we will be upgrading to 2017-03-30. Let us keep this issue open.

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-java#1
