### ISSUE TITLE
Fluent SDK: GenericResources: Is it possible to define 'sku' if you use GenericResources.Define()?

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#3673]
I tried to use the azureSub.GenericResources.Define(Name) API but I can't see what should be the way to define that it should have a _top-level_ property SKU like '  
  "sku": {    
    "name": "Standard_A1",    
    "tier": "Standard",    
    "capacity": 10          
  },  
' (as opposed to a property in its 'properties' bag? Or is this just a documentation issue that I am misunderstanding the usage of .WithProperties()?)

**Comment by hovsepm** [comment]
@TimLovellSmith What is the Fluent flow? VMSS?

**Comment by TimLovellSmith** [comment]
Yes, I was trying to work around one of the earlier issues I filed by creating VMSS as a generic resource.

**Comment by anuchandy** [comment]
`GenericResources` fluent flow does not expose `SKU` though inner has these properties. 

@TimLovellSmith will discuss within the team and prioritize this.

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#43
