### ISSUE TITLE
IAzure does not contain a definition for ActiveDirectoryApplications 

### ISSUE THREAD

**Issue by larsekman** [Azure/azure-sdk-for-net#3677]
I have code that references IAzure.ActiveDirectoryApplications to create applications in an Azure Active Directory.

After upgrading my NuGet packages it seems that the ActiveDirectoryApplications is gone or has moved. In which namespace/assembly can I find the ActiveDirectoryApplications functionality?

**Comment by anuchandy** [comment]
`IActiveDirectoryApplications` is under `Azure.IAuthenticated`.

```C#
var authenticated = Azure
    .Configure()
    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
    .Authenticate(credentials);

var activeDirectoryApplication = authenticated.ActiveDirectoryApplications
    .Define(name)
    ...
    .Create();

```

See this [sample](https://github.com/Azure/azure-sdk-for-net/blob/Fluent/Samples/GraphRbac/ManageServicePrincipal.cs) for more details.
