### ISSUE TITLE
[QUERY] Is there a way to access underlying TokenCache?

### ISSUE THREAD

**Issue by Kadeluxe** [Azure/azure-sdk-for-net#36783]
### Library name and version

Azure.Identity 1.9.0

### Query/Question

`ClientSecretCredential` internally creates `MsalConfidentialClient` which in turn creates and uses `TokenCache`.
Is there a way to access and manipulate cache entries, including persistent cache? 
For example, I want to remove specific entries from cache completely. Any options?
The use-case is that my app may receive tokens which miss roles (no admin consent) and in that case I need to force refresh them. Apparently it's not possible to do so?

### Environment

.NET

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @Kadeluxe 
Yes, you can participate in MSAL's cache callbacks by implementing [UnsafeTokenCacheOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/UnsafeTokenCacheOptions.cs) and passing that instance to the TokenCachePersistenceOptions https://github.com/Azure/azure-sdk-for-net/blob/9610a44a0405b0fa7093fad9f09f8aa4577d2fa5/sdk/identity/Azure.Identity/src/Credentials/ClientSecretCredentialOptions.cs#L16.

**Comment by Kadeluxe** [comment]
/unresolve
Yes, I can provide callbacks using [UnsafeTokenCacheOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/UnsafeTokenCacheOptions.cs) but these callbacks do not provide access to the token cache, apparently I can either receive serialized bytes or return serialized bytes using these callbacks?

I want to manipulate the cache entries because I don't want to cache **some** tokens, but I can't figure out how to actually get access to the underlying cache and methods of [ITokenCacheAccessor](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/a099f094d9a6be5f179125b5479b000cef1eafee/src/client/Microsoft.Identity.Client/Cache/ITokenCacheAccessor.cs#L11) interface. 

Do I need to invent my own cache for that? This looks complicated, I would assume that cache should be exposed somewhere, at least to allow to invalidate arbitrary tokens.

**Comment by christothes** [comment]
> /unresolve Yes, I can provide callbacks using [UnsafeTokenCacheOptions](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/UnsafeTokenCacheOptions.cs) but these callbacks do not provide access to the token cache, apparently I can either receive serialized bytes or return serialized bytes using these callbacks?

The bytes *are* the contents of the cache. If you wanted to manipulate the cache entries, you could de-serialize the bytes to json and serialize the json once you've made your changes.
