### ISSUE TITLE
Misleading documentation, parameter says deviceName however it requires a text id such as "{0.0.1.00000000}.{5f23ab69-6181-4f4a-81a4-45414013aac8}"

### ISSUE THREAD

**Issue by zanthous** [Azure/azure-sdk-for-net#36801]
I went to the c# example and it showed printing a device's friendly name and a device's id, I tried the friendlyname, and it didn't work however the id did work. It would be helpful if the parameter was named better

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 51ea0365-48aa-3375-53be-10cc52feb8ba
* Version Independent ID: 7c9abf92-cb7c-5e11-2604-9b9b2cd4d464
* Content: [AudioConfig.FromSpeakerOutput(String) Method (Microsoft.CognitiveServices.Speech.Audio) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.audio.audioconfig.fromspeakeroutput?view=azure-dotnet)
* Content Source: [xml/Microsoft.CognitiveServices.Speech.Audio/AudioConfig.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.CognitiveServices.Speech.Audio/AudioConfig.xml)
* Service: **cognitive-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@zanthous Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@zanthous The product owners have been notified and they have created an internal workitem to address and improvise this documentation issue.
