### ISSUE TITLE
[FEATURE REQ] BearerTokenAuthenticationPolicy is easy to be inherited from

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-for-net#36821]
### Library name

Azure.Core

### Please describe the feature.

The `BearerTokenAuthenticationPolicy` cannot statisfy our requirement, such as handling special responses, force refresh token. So we want to create a new policy to enhance it. However, we also want to use most of functionality in `BearerTokenAuthenticationPolicy`, so it's better to inherit from `BearerTokenAuthenticationPolicy`. Currently, there are many private method/field in it, and cannot be inherited from. So we hope these private method/field can be protected/public, and it will provide better user experience for us.

**Comment by christothes** [comment]
Hi @dw511214992 - Could you provide some specific example scenarios that require access to private or internal methods or fields?

**Comment by jsquire** [comment]
It has been multiple months and we do not have examples of the scenario where this would be useful.  Closing as unplanned.   If still needed, please reopen with the requested context.
