### ISSUE TITLE
ChatCompletionsOptions.Messages is ready-only?

### ISSUE THREAD

**Issue by Roop4Suzy** [Azure/azure-sdk-for-net#36826]
is "Messages" get only property? How one can pass messages if it's not accepting to pass list of messages?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c9396148-56dc-dd8a-2d51-7421ac29538a
* Version Independent ID: 64442318-ea9e-0811-2b36-20073c2343ca
* Content: [ChatCompletionsOptions.Messages Property (Azure.AI.OpenAI) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.ai.openai.chatcompletionsoptions.messages?view=azure-dotnet-preview#azure-ai-openai-chatcompletionsoptions-messages)
* Content Source: [xml/Azure.AI.OpenAI/ChatCompletionsOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.AI.OpenAI/ChatCompletionsOptions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by TalMcMahon** [comment]
If the change is not planned, can you fix the documentation to match, very frustrating to see Microsoft documentation say one thing and this to say another.
