### ISSUE TITLE
[BUG] Microsoft.Azure.Management.Websites 3.1.2 the resource group validation is not correct

### ISSUE THREAD

**Issue by xfz11** [Azure/azure-sdk-for-net#36843]
### Library name and version

Microsoft.Azure.Management.Websites 3.1.2

### Describe the bug

Microsoft.Rest.ValidationException: 'resourceGroupName' does not match expected pattern '^[-\w\._\(\)]+[^\.]$'.

The resource group such as `s` can be created on Azure but can't pass the validation and it throws error

### Expected behavior

The exception shouldn't be thrown for a valid resource group

### Actual behavior

Exception: Microsoft.Rest.ValidationException: 'resourceGroupName' does not match expected pattern '^[-\w\._\(\)]+[^\.]$'.
   at Microsoft.Azure.Management.WebSites.WebAppsOperations.***(String resourceGroupName, String name, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.ListApplicationSettingsAsync(IWebAppsOperations operations, String resourceGroupName, String name, CancellationToken cancellationToken)

### Reproduction Steps

create a resource group named s and a webapp in it,
then call `await this._appClient.WebApps.ListApplicationSettingsAsync(resourceGroup, webAppName).ConfigureAwait(false);` the error would be thrown

### Environment

.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.203\
global.json file:
  Not found

**Comment by jsquire** [comment]
Hi @xfz11.  Thank you for reaching out and we regret that you're experiencing difficulties.  The `Microsoft.Azure.Management.Websites` package has been deprecated and is currently receiving only critical security fixes.  We would strongly recommend migrating to the current package, [Azure.ResourceManager.AppService](https://www.nuget.org/packages/Azure.ResourceManager.AppService/).   Migration assistance can be found in the [management library migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md).
