### ISSUE TITLE
[Core] Migrate recordings to the assets repo

### ISSUE THREAD

**Issue by kinelski** [Azure/azure-sdk-for-net#36852]
Do the same process we did in https://github.com/Azure/azure-sdk-for-net/pull/36782 to the Core packages.

Some tests in the Test Framework test project fail after migrating. They could be trying to access the recordings directly instead of doing it through the framework. We should investigate and update the tests accordingly.

**Comment by pallavit** [comment]
@kinelski do we have the list of tests or a repro PR that we can use here?

**Comment by kinelski** [comment]
Affected tests are `RecordedVariableSanitized` and `RecordedOptionalVariableNotSanitizedIfMissing`, but I have a fix locally and will push a PR in a few minutes.
