### ISSUE TITLE
[QUERY] Is it possible to round-robin messages to Azure ServiceBus Topic's subscriptions?

### ISSUE THREAD

**Issue by arunprakashn** [Azure/azure-sdk-for-net#36874]
### Library name and version

Azure.Messaging.Servicebus 7.14.0

### Query/Question

I have a requirement where a topic contains 10 subscriptions. Is it possible to group them into two groups, let's say, Grp1 and Grp2 with each containing 5 subscriptions? When the message arrives at the topic, I want the messages to be round-robin between the subscriptions of a particular group.

I understand that I can add multiple consumers to a single subscription and get this load balancing. However, this is pertaining to some legacy code and cannot change certain things. I went through the Subscription filter rules but don't think this is possible. However, as a last resort, I thought I can ask the community.

**Comment by jsquire** [comment]
Hi @arunprakashn.  Thank you for reaching out and we regret that you're experiencing difficulties.  This can be done by applying filters and actions to the subscription and setting the specific rules by which you'd like to use for routing.   Please see [Topic filters and actions](https://learn.microsoft.com/azure/service-bus-messaging/topic-filters) for details.
