### ISSUE TITLE
[QUERY] Listing UsageDetails and Marketplaces by billing period

### ISSUE THREAD

**Issue by NovaWasTaKenn** [Azure/azure-sdk-for-net#36876]
### Library name and version

Azure.ResourceManager.Consumption v1.6

### Query/Question

I need a replacement for some function in Microsoft.Azure.Management.Consumption that are deprecated. 

The functions I need : 
ConsumptionManagementClient.UsageDetails.ListByPeriodAsync ConsumptionManagementClient.Marketplaces..ListByBillingPeriodAsync

I've looked into Azure.ResoureManager.Consumption that is listed as the replacement Microsoft.Azure.Management.Consumption, I also looked at CostManagement but I haven't been able to functions that return the same thing and work in the same way. I saw a ticket talking about Quota for Usage so I will look into that.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by NovaWasTaKenn** [comment]
I can see the functions I need in the github : 

ConsumptionExtensions.GetConsumptionUsageDetailsAsync and ConsumptionExtensions.GetConsumptionMarketPlacesAsync

But they are not visible in the documentation or the version 1.0.1 of the Azure.ResourceManager.Consumption NuGet package

**Comment by mcgallan** [comment]
Hi @NovaWasTaKenn, you can try browsing this documentation about [Usage details](https://learn.microsoft.com/en-us/rest/api/consumption/usage-details/list?tabs=HTTP#usagedetailslistforbillingperiod-legacy) and [marketplace](https://learn.microsoft.com/en-us/rest/api/consumption/marketplaces/list?tabs=HTTP#subscriptionmarketplaceslistforbillingperiod),or using the updated version of [NuGet Package](https://www.nuget.org/packages/Azure.ResourceManager.Consumption/1.1.0-beta.1) (version.1.1.0)

**Comment by NovaWasTaKenn** [comment]
Hello @mcgallan , I looked at the updated version of the package, the function I was looking for are here. The function listing usage details seems to work fine however, the funciton listing marketplaces details return the error below. The scope and clients are the same used for listing the usage details and worked fine.
![image](https://github.com/Azure/azure-sdk-for-net/assets/98171103/b964d015-06a4-4e77-b864-6d22aba6930e)

**Comment by NovaWasTaKenn** [comment]
Deleted the previous comment because I am interested in the Async version of the function.
However after testing ConsumptionExtensions.GetConsumptionMarketPlacesAsync in the beta version of the package I get this exception : 
![image](https://github.com/Azure/azure-sdk-for-net/assets/98171103/45266798-bcb7-4999-85d5-c5424a43a9a7)

With this stacktrace :  à System.Text.Json.JsonElement.GetGuid() 
à Azure.ResourceManager.Consumption.Models.ConsumptionMarketplace.DeserializeConsumptionMarketplace(JsonElement element)
à Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.MoveNext()
à Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
à System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
à Program.<>c__DisplayClass0_0.<<<Main>$>g__IterateWithAwaitForeachAsync|0>d.MoveNext()
à Program.<>c__DisplayClass0_0.<<<Main>$>g__IterateWithAwaitForeachAsync|0>d.MoveNext()
à Program.<<Main>$>d__0.MoveNext()

The code I use is from a microsoft article on iterating over pageable and it works for the functionConsumptionExtensions.GetConsumptionUsageDetailsAsync so I guess the problem comes from ConsumptionExtensions.GetConsumptionMarketPlacesAsync
Thanks in advance for the help !

**Comment by live1206** [comment]
> Deleted the previous comment because I am interested in the Async version of the function. The updated version of the package has the functions I'm looking for. The one one that lists the usageDetails works well. However, when using ConsumptionExtensions.GetConsumptionMarketPlacesAsync, that is the function I need to list the marketplaces, I get this exception : ![image](https://user-images.githubusercontent.com/98171103/247609106-85aa5838-9336-4caa-a572-6959186af754.png)
> 
> With this stacktrace : "at System.Text.Json.JsonElement.GetGuid() at Azure.ResourceManager.Consumption.Models.ConsumptionMarketplace.DeserializeConsumptionMarketplace(JsonElement element) at Azure.Core.PageableHelpers.PageableImplementation`1.CreatePage(Response response, String& nextLink) at Azure.Core.PageableHelpers.PageableImplementation`1.d__16.MoveNext() at Azure.Core.PageableHelpers.PageableImplementation`1.<AsPagesAsync>d__16.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token) at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult() at Program.<
> 
> $>d__0.MoveNext() in C:\Users\user\source\repos\ConsoleApp1\ConsoleApp1\Program.cs :ligne 29
> at Program.<$>d__0.MoveNext() in C:\Users\user\source\repos\ConsoleApp1\ConsoleApp1\Program.cs :ligne 29"
> The code I use is from a microsoft article on iterating over pageable and it works for the function ConsumptionExtensions.GetConsumptionUsageDetailsAsync so I guess the problem comes from ConsumptionExtensions.GetConsumptionMarketPlacesAsync Thanks in advance for the help !

@NovaWasTaKenn Could you help to log the service response of the API call while invoke `GetConsumptionMarketPlacesAsync ` to see if it is a valid Guid? Thanks!

**Comment by NovaWasTaKenn** [comment]
Hello @live1206, 

Sorry, I was on vacation last week, do you still need the information on the meterId and the subscriptionGuid ?

**Comment by live1206** [comment]
> Hello @live1206,
> 
> Sorry, I was on vacation last week, do you still need the information on the meterId and the subscriptionGuid ?

No worries. 
Yes, that would be very helpful for us to trouble-shoot this issue. Thanks!

**Comment by NovaWasTaKenn** [comment]
Hello @live1206, 
So subscriptionGuid has this format dddddddd-dddd-dddd-dddd-dddddddddddd and the meterId is just empty. 
This is the code I used with the scope for the request being the same as in my original message 
![image](https://github.com/Azure/azure-sdk-for-net/assets/98171103/50f99549-6f69-4c96-944c-7fc19eb5d459)

**Comment by live1206** [comment]
Thanks @NovaWasTaKenn for the information.

@HarveyLink Empty `meterId` is causing error during deserialization, please help to resolve it, thanks!

**Comment by NovaWasTaKenn** [comment]
Hello @live1206, 
So subscriptionGuid has this format dddddddd-dddd-dddd-dddd-dddddddddddd and the meterId is just empty. 
This is the code I used with the scope for the request being the same as in my original message 
![image](https://github.com/Azure/azure-sdk-for-net/assets/98171103/50f99549-6f69-4c96-944c-7fc19eb5d459)

**Comment by live1206** [comment]
Will be fixed in next version release.
