### ISSUE TITLE
[BUG] UnsupportedAccessTokenType when using the Azure.Monitor.Ingestion SDK

### ISSUE THREAD

**Issue by michaelhahn-doka** [Azure/azure-sdk-for-net#36884]
### Library name and version

Azure.Monitor.Ingestion, 1.0.0

### Describe the bug

I am encountering an error while uploading custom log events to a Log Ingestion Endpoint.

The error message I am receiving is as follows:
```json
{
  "error": {
    "code": "UnsupportedAccessTokenType",
    "message": "S2S17001: SAL was able to validate the protocol, but validation failed as none of the inbound policies were satisfied. Validation failures: '{redacted}': UnsupportedAccessTokenType."
  }
}
```

The code I have (shortened):
```csharp
var streamName = "some-stream-name";
var logs = new [] { new CustomLogEventWithSomeProperties { … }};
var logsIngestionClient = new LogsIngestionClient(_azureMonitorLogIngestionOptions.DataCollectionEndpointUrl, new DefaultAzureCredential());
var response = await _logsIngestionClient.UploadAsync(_azureMonitorLogIngestionOptions.DataCollectionRuleIdentifier, streamName, logs, cancellationToken: cancellationToken);
```

### Expected behavior

The logs are uploaded successfully without an issue.

### Actual behavior

I always receive the error mentioned above.
I also checked actual http request and both the token itself and the Authorization header look correct:
![Screenshot 2023-06-07 at 15 29 54](https://github.com/Azure/azure-sdk-for-net/assets/110385682/36d0707d-ab88-489b-ba37-7364544a31e5)

### Reproduction Steps

See the code above.

### Environment

.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.4
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.101/

Host:
  Version:      7.0.1
  Architecture: arm64
  Commit:       97203d38ba

IDE and version: Rider 2023.1

**Comment by janhavi13** [comment]
I am also facing the same issue while using the REST api as described this in this example - https://learn.microsoft.com/en-us/rest/api/monitor/metrics-custom/create?tabs=HTTP#post-azure-metrics-for-cows-sold-with-related-metadata-as-dimensions

**Comment by scottaddie** [comment]
@michaelhahn-doka Can you please try reproducing this problem with [logging enabled](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md)? We'll need those logs to determine the source of the problem.

**Comment by navba-MSFT** [comment]
Adding service team to look into this.

**Comment by scottaddie** [comment]
@michaelhahn-doka Thanks for your patience. There was a small code change in the service itself that caused this problem. The service team has implemented a code fix. That fix will be deployed to all Azure regions by tomorrow.

Marking this issue as resolved, but please reopen if the problem appears again.
