### ISSUE TITLE
[QUERY] How to convert the Json object to SearchDocument correctly?

### ISSUE THREAD

**Issue by youxu71** [Azure/azure-sdk-for-net#36896]
### Library name and version

Azure.Search.Documents

### Query/Question

In our current code which using Microsoft.Azure.Search library, we build the Document from pre-build fields dictionary: IDictionary<string, object> fields. The object in dictionary could be any Json object, like string, string array, complex type array.

e.g.:
fields["CatIds"] = { ["1", "2"] }
fields["Images"] = { [ {"Url":"https://aaa", "IsDefault": false}, {"Url":"https://bbb", "IsDefault": true} ] }

When build the azure search document, we just simply assign the field value to Document object.

var document = new Document();
foreach (var field in fields)
{
  document[field.Key] = document[field.Value]
}

And then send documents to index, that worked perfectly.

But now we cannot simply assign the value from fields to SearchDocument anymore using SDK v11 (Azure.Search.Documents), if the field value is a JArray value, otherwise we will get exception when sending documents to ACS:

Details: An unexpected 'StartArray' node was found when reading from the JSON reader. A 'PrimitiveValue' node was expecte
Seems have to manually convert the JArray<T> to List<T> before assign value to SearchDocument.

Do you have sample code to handle this conversion? Or guidance document?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
[@youxu71](https://github.com/youxu71) You can pass IDictionary<string, object> in [SearchDocument](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/api/Azure.Search.Documents.netstandard2.0.cs#L3223).

[Here's](https://github.com/ShivangiReja/azure-sdk-for-net/blob/b9d94af64ddc81068f38525ed530d593ebdd28c3/sdk/search/Azure.Search.Documents/tests/DocumentOperations/IndexingTests.cs#L713-L718C58) an example that demonstrates the usage of a json object as string array within a dictionary as one of the [field's value](https://github.com/ShivangiReja/azure-sdk-for-net/blob/b9d94af64ddc81068f38525ed530d593ebdd28c3/sdk/search/Azure.Search.Documents/tests/DocumentOperations/IndexingTests.cs#L716).

**Comment by ShivangiReja** [comment]
[@youxu71](https://github.com/youxu71) You can pass IDictionary<string, object> in [SearchDocument](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/api/Azure.Search.Documents.netstandard2.0.cs#L3223).

[Here's](https://github.com/ShivangiReja/azure-sdk-for-net/blob/b9d94af64ddc81068f38525ed530d593ebdd28c3/sdk/search/Azure.Search.Documents/tests/DocumentOperations/IndexingTests.cs#L713-L718C58) an example that demonstrates the usage of a json array as one of the [field's value](https://github.com/ShivangiReja/azure-sdk-for-net/blob/b9d94af64ddc81068f38525ed530d593ebdd28c3/sdk/search/Azure.Search.Documents/tests/DocumentOperations/IndexingTests.cs#L716) within a dictionary .

**Comment by ShivangiReja** [comment]
I see that you are using the `Newtonsoft.Json.Linq.JArray` library to create a JSON array. However, in the new .NET SDKs, we have moved away from using the `Newtonsoft.Json` library and now recommend using the `System.Text.Json` library.

`System.Text.Json` provides similar functionality to `Newtonsoft.Json` but is optimized for performance and integrates well with the .NET ecosystem. If you were previously using `Newtonsoft.Json` in your code with the new SDKs, you will need to update your code to use `System.Text.Json` instead.

To assist with the transition from `Newtonsoft.Json` to `System.Text.Json`, you can refer to the [migration guides](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-7-0). These guides provide detailed information and best practices for migrating your code and utilizing the features of `System.Text.Json` effectively.

[Here](https://github.com/ShivangiReja/azure-sdk-for-net/blob/b9d94af64ddc81068f38525ed530d593ebdd28c3/sdk/search/Azure.Search.Documents/tests/DocumentOperations/IndexingTests.cs#L716) my example uses `System.Text.Json.Nodes.JsonArray` to create json array.

Please let me know if you have any further questions!
