### ISSUE TITLE
[BUG] GetApiRevisionsByServiceAsync Throws Deserialization Error

### ISSUE THREAD

**Issue by adahlinvcrs** [Azure/azure-sdk-for-net#36914]
### Library name and version

Azure.ResourceManager.ApiManagement 1.0.1

### Describe the bug

When calling GetApiRevisionsByServiceAsync on an ApiResource it throws an exception during the deserialization. It seems as though it is trying to deserialize the privateUrl as a Url, which is not valid and thus throws.

The following was observed during debugging:

Executing the statement
`AsyncPageable<ApiRevisionContract> pages = api.Value.GetApiRevisionsByServiceAsync(cancellationToken: cancellationToken);
            await foreach (var page in pages)
            {
                // do something
            }`
Throws with the message "Invalid URI: The format of the URI could not be determined." and stack trace
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.ApiManagement.Models.ApiRevisionContract.DeserializeApiRevisionContract(JsonElement element)
   at Azure.Core.PageableHelpers.PageableImplementation`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.Core.PageableHelpers.PageableImplementation`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
...

From the model serialization available at https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Generated/Models/ApiRevisionContract.Serialization.cs, it gives the idea that the privateUrl is being used to create Uri objects.

Looking at the response of the REST API for apis/{api_name}/revisions, the privateUrl property is set in the form of "privateUrl": "/{producer}/{apiName}/v1", which when invoked in a new Uri statement would throw the error message Invalid URI: The format of the URI could not be determined.

### Expected behavior

An AsyncPageable that can be iterated and retrieved similar to other requests in the package, resulting in a list of ApiRevisionContracts.

### Actual behavior

Exception thrown with message Invalid URI: The format of the URI could not be determined.

### Reproduction Steps

Execute the following on an ApiResource object
`AsyncPageable<ApiRevisionContract> pages = api.Value.GetApiRevisionsByServiceAsync(cancellationToken: cancellationToken);
            await foreach (var page in pages)
            {
                // do something
            }`

### Environment

Windows 10
net6.0 project
Visual Studio 2022 17.4.2

**Comment by ArthurMa1978** [comment]
@HarveyLink please help to check if this issue has been fixed or not
