### ISSUE TITLE
[BUG] Request to fetch Traffic Manager Profile resource fails due to API version mismatch

### ISSUE THREAD

**Issue by peterbergman** [Azure/azure-sdk-for-net#36920]
### Library name and version

Azure.ResourceManager.Resources 1.6.0

### Describe the bug

Getting `400 BadRequest` when fetching Traffic Manager Profiles resource through `GetAsync()` on `GenericResource`.

Please note that I've submitted a [similar bug report](https://github.com/Azure/azure-sdk-for-net/issues/32327) before which was later on fixed, but now I seem to get the same behavior again.

### Expected behavior

Should fetch the resource by ID.

### Actual behavior

Request fails with `400 BadRequest` and response body:

```
{"error":{"code":"BadRequest","message":"'2022-12-01-preview' is not a supported API version. Supported version are 2015-04-28-preview, 2015-11-01, 2017-03-01, 2017-05-01, 2017-09-01-preview, 2018-02-01, 2018-03-01, 2018-04-01, 2018-08-01, 2020-12-01-preview, 2022-04-01, 2022-04-01-preview."}}
```

### Reproduction Steps

1. Create Traffic Manager Profile resource in subscription (below steps assumes single subscription and single resource within)

2. Create ARM client:
```csharp
var armClient = new ArmClient(new ClientSecretCredential("tenant", "clientID", "clientSecret"));
```

3. Fetch subscription:
```csharp
var subscription = armClient.GetSubscriptions().First();
```

4. Fetch resources:
```csharp
var resources = subscription.GetGenericResources().First();
```

5. Fetch Traffic Manager Profile resource:
```csharp
var resource = await genericResource.GetAsync();
```

### Environment

```` 
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  6.0.407 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by peterbergman** [comment]
@jsquire Any update on this one? Or is there a workaround where I can specify the the version through the client or something like that?

**Comment by jsquire** [comment]
@peterbergman:  Unfortunately, I don't have insight.  We'll need @ArthurMa1978's feedback to answer that.

**Comment by HarveyLink** [comment]
Hi @peterbergman , Thank you for using Azure SDK for . NET.
There is a work around for us to set the api version we want, please refer #35152 :
```
ArmClientOptions armClientOptions = new ArmClientOptions();
           ResourceType workspaceResourceType = new ResourceType("Microsoft.OperationalInsights/workspaces");
           armClientOptions.SetApiVersion(workspaceResourceType, "2022-10-01");
           ResourceType securityinsightsruleresource = new ResourceType("Microsoft.SecurityInsights/alertRules");
           armClientOptions.SetApiVersion(securityinsightsruleresource, "2023-04-01-preview");
           armClient = new ArmClient(credential,SI_SubscriptionId,armClientOptions );
```

**Comment by peterbergman** [comment]
> Hi @peterbergman , Thank you for using Azure SDK for . NET. There is a work around for us to set the api version we want, please refer #35152 :
> 
> ```
> ArmClientOptions armClientOptions = new ArmClientOptions();
>            ResourceType workspaceResourceType = new ResourceType("Microsoft.OperationalInsights/workspaces");
>            armClientOptions.SetApiVersion(workspaceResourceType, "2022-10-01");
>            ResourceType securityinsightsruleresource = new ResourceType("Microsoft.SecurityInsights/alertRules");
>            armClientOptions.SetApiVersion(securityinsightsruleresource, "2023-04-01-preview");
>            armClient = new ArmClient(credential,SI_SubscriptionId,armClientOptions );
> ```

Perfect, thanks!
