### ISSUE TITLE
[FEATURE REQ] Add a TryGetSecret method

### ISSUE THREAD

**Issue by Thiago-NovaesB** [Azure/azure-sdk-for-net#36942]
### Library name

Azure.Security.KeyVault.Secrets

### Please describe the feature.

Currently, to recover secrets, there are only methods that return an error if it is not possible. (GetSecret, GetSecretAsync...).
However, this ends up generating an unwanted error. It would be nice to have TryGetSecret and TryGetSecretAsync. Which would return a bool if it managed to recover the secret (returning the value with out).

All the problem start here:
```
private Response SendRequest(Request request, CancellationToken cancellationToken)
{
    Response response = _pipeline.SendRequest(request, cancellationToken);

    switch (response.Status)
    {
        case 200:
        case 201:
        case 202:
        case 204:
            return response;
        default:
            throw Diagnostics.CreateRequestFailedException(response);
    }
}
```
It would be another one like:
```
private bool TrySendRequest(Request request, CancellationToken cancellationToken, out Response response)
{
    Response response = _pipeline.SendRequest(request, cancellationToken);

    switch (response.Status)
    {
        case 200:
        case 201:
        case 202:
        case 204:
            return true;
        default:
            return false;
    }
}
```

With `TrySendRequest` it will be possible to build all the others Try'methods.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
Duplicate of #25125
