### ISSUE TITLE
Fluent SDK - Query deployment failure reason

### ISSUE THREAD

**Issue by abhi1509** [Azure/azure-sdk-for-net#3694]
Currently resourceManager.Deployments.GetByResourceGroup(...)
returns IDeployment

In case a deployment fails, I don't see a way to find out failure reason to log it

**Comment by martinsawicki** [comment]
@anuchandy is there a better answer to this than "by design"?

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#39
