### ISSUE TITLE
[BUG] VirtualMachineScaleSetResource.GetVirtualMachineScaleSetVms returns instances that have been deleted

### ISSUE THREAD

**Issue by kinnett** [Azure/azure-sdk-for-net#36946]
### Library name and version

Azure.ResourceManager.Compute 1.1.0

### Describe the bug

I am attempting to get a list of all the VM instances a Virtual Machine Scale set currently contains like this:

```
        var virtualMachineScaleSetResourceId = VirtualMachineScaleSetResource.CreateResourceIdentifier(_settings.SubscriptionId, _settings.ResourceGroupName, _settings.VirtualMachineScaleSetName);
        var virtualMachineScaleSet = _armClient.GetVirtualMachineScaleSetResource(virtualMachineScaleSetResourceId);

        
        var collection = virtualMachineScaleSet.GetVirtualMachineScaleSetVms();

        var pageableCollection = collection.GetAllAsync();

        var instanceCollection = new List<string>();
        await foreach (var virtualMachineScaleSetVmResource in pageableCollection)
            instanceCollection.Add(virtualMachineScaleSetVmResource.Data.InstanceId);
```
It will return instances that have been deleted and deleted for some time. For instance, now in my vm scale set resource there is only one instance, however query returns 9 instances. Meaning 8 have been deleted and have been for a while.

### Expected behavior

What I would expect it to return just the instance currently in the vm scale set azure resource. 

### Actual behavior

Returns the instances currently in vm scale set as well as deleted instances. There doesn't seem to be to be any indication in the data that would differentiate between the deleted and valid instances.

### Reproduction Steps

Run the above code against a vm scale set with some instances then delete the instances and run the same query and see if it returns the deleted instance along with the running instances. 

### Environment

dotnet core 7
VS 2022
Windows 10

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
@kinnett Thank you for your feedback. The bug you mentioned has been fixed in the latest version, you can use [the latest version](https://www.nuget.org/packages/Azure.ResourceManager.Compute/1.4.0-beta.1) to continue your work.”
