### ISSUE TITLE
[QUERY] C# how to add existing VM into host pool

### ISSUE THREAD

**Issue by nikammahesh01** [Azure/azure-sdk-for-net#36957]
### Library name and version

https://github.com/Azure/azure-sdk-for-net/tree/a9e03d83467941a7596aff060a5b3109d94d694a/sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization

### Query/Question

Please share class for HostPoolData.VmTemplate and also share how add/Create session host into host pool using C#

### Environment

C#  and Dot net

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nikammahesh01** [comment]
Thanks @jsquire , I am waiting for response.

**Comment by HarveyLink** [comment]
Hi @nikammahesh01 , Thank you for using Azure SDK for .NET.
For the sdk usage, you could refer to: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/desktopvirtualization/Azure.ResourceManager.DesktopVirtualization/samples/Generated/Samples/Sample_HostPoolCollection.cs.
About _how add/Create session host into host pool_, unfortunately, we don't have the domain knowledge. Found a similar ask for you to refer: https://learn.microsoft.com/en-us/answers/questions/110851/add-existing-azure-vm-to-session-host-pool-(azure
