### ISSUE TITLE
Please add an example for reusing credential instance

### ISSUE THREAD

**Issue by chitturs** [Azure/azure-sdk-for-net#36969]
There is a recommendation in GetTokenAsync() for caching credential instances. Good to have a reuse example showing locking, etc. so that people don't introduce bugs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 414d8832-9224-3bb5-2bf4-1197c41fdedf
* Version Independent ID: 02d95dd6-bf1b-5cef-bc94-ac187b133c45
* Content: [DefaultAzureCredential Class (Azure.Identity) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet#methods)
* Content Source: [xml/Azure.Identity/DefaultAzureCredential.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Identity/DefaultAzureCredential.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @chitturs -
Examples would vary per application - for example, this could be done via a singleton in your DI container of choice, or something as simple as a concurrent dictionary. Is there a specific scenario you had in mind?

**Comment by christothes** [comment]
I'm not sure what the idiomatic approach looks like to share state in service fabric, depending on what your specific service instance looks like - but assuming you are able to access a shared or static instance of a ConcurrentDictionary, you'd probably want to either use [GetOrAdd](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=net-7.0). The specific implementation would depend on how many credentials you need to maintain for your application.

**Comment by chitturs** [comment]
Can we publish a GetOrAdd example in docs?
