### ISSUE TITLE
Unable to Deploy Recovery Services Vault

### ISSUE THREAD

**Issue by thedancingfetus** [Azure/azure-sdk-for-net#3696]
I've been trying to deploy a recovery services vault using Microsoft.Azure.Management.RecoveryService v4.2.0-preview.  I keep getting an error, and I'm not sure why.  In the Azure portal I'm getting the Bad HTTP Request:

"statusCode": "BadRequest",

"statusMessage": "{\"error\":{\"code\":\"InvalidRestApiParameter\",\"message\":\"properties parameter is invalid.\\r\\nPlease provide a valid properties\",\"target\":null,\"details\":null,\"innerError\":null}}"

Below, I'm creating a RecoveryServices Client, a Vault, and then trying to create.  I'm using Microsoft.Rest.TokenCredential object when creating the Client.

RecoveryServicesClient recoveryClient = new RecoveryServicesClient(token)
{
   SubscriptionId = "MySubscriptionID
};
Vault thisVault = new Vault { Location = "eastus", Sku = new Microsoft.Azure.Management.RecoveryServices.Models.Sku { Name = "Standard" } };
recoveryClient.Vaults.CreateOrUpdate("MyResourceGroup", "MyVault", thisVault);

I noticed a similar issue on the Ruby SDK, but they seemed to resolve it by declaring the Sku, but I'm doing that and getting the same.

**Comment by shahabhijeet** [comment]
@DheerendraRathor are you the right person to look at this issue?

**Comment by DheerendraRathor** [comment]
Adding @sonathan from RecoveryServices. 
@thedancingfetus Can you print requestId (x-ms-request-id) or x-ms-client-request-id from request/response headers? RequestId is also a property of returned AzureOperationResponse or thrown exception.

**Comment by sonathan** [comment]
Hi @thedancingfetus,

As the error message suggests: please provide a valid "properties" field. 

You need to declare Properties in the request you are sending.

**Comment by thedancingfetus** [comment]
@sonathan , you nailed it.  I read the error message as my SKU Property was invalid.  I added this:

VaultProperties properties = new VaultProperties();
Vault thisVault = new Vault { Location = "eastus", Sku = new Microsoft.Azure.Management.RecoveryServices.Models.Sku { Name = "Standard" } , Properties = properties};

Deploys now without issue.  Thanks for your help.
