### ISSUE TITLE
[BUG] AzureKeyCredential could not be found  ,I have already imported and install using azure.Core in my project

### ISSUE THREAD

**Issue by usmanumar2010** [Azure/azure-sdk-for-net#36970]
### Library name and version

Azure.Core

### Describe the bug

 AzureKeyCredential could not be found  ,I have already imported and install  azure.Core in my project### 

### Expected behavior

should be able to use
AzureKeyCredential credential = new AzureKeyCredential("{api-key}");

### Actual behavior

The type or namespace name 'AzureKeyCredential' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\bserajelahi\Desktop\TD Engagement\MyConversationAnalysisApp\ 
MyConversationAnalysisApp.csproj]

### Reproduction Steps

using Azure.Core;
using Azure.AI.Language.Conversations;

Uri endpoint = new Uri("https://myaccount.cognitiveservices.azure.com");
AzureKeyCredential credential = new AzureKeyCredential("{api-key}");

ConversationAnalysisClient client = new ConversationAnalysisClient(endpoint, credential);

**Comment by usmanumar2010** [comment]
added the library 
using Azure;
which resolved the issue

**Comment by jsquire** [comment]
Marking as addressed, per the comment mentioning that adding the necessary using resolved the issue.
