### ISSUE TITLE
Refers to cognitive search instead of Azure Open AI

### ISSUE THREAD

**Issue by charlesRollandy** [Azure/azure-sdk-for-net#37011]
In the description of the parameter `endpoint` it is written: "Supported Cognitive Services endpoints"
It should be the "Supported Azure Open AI Services endpoints"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8e4ea643-9aab-d496-e681-77ee3b584d37
* Version Independent ID: b8e13806-f1b1-43b9-bed9-bb000eb06905
* Content: [AzureOpenAIClientBuilderExtensions.AddOpenAIClient Method (Microsoft.Extensions.Azure) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.azure.azureopenaiclientbuilderextensions.addopenaiclient?view=azure-dotnet-preview)
* Content Source: [xml/Microsoft.Extensions.Azure/AzureOpenAIClientBuilderExtensions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Extensions.Azure/AzureOpenAIClientBuilderExtensions.xml)
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@charlesRollandy   Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by trrwilson** [comment]
Thank you for catching this and filing the issue! As @navba-MSFT rightly pointed out, the problem stems from the language-independent specification having an overlooked copy/paste mistake in the code generation definition. I've filed the linked issue on that repository to ensure we update things on that side; once that's done, we'll pick up the updated comment on the individual SDKs.

https://github.com/Azure/azure-rest-api-specs/issues/24869
