### ISSUE TITLE
Fluent SDK: Issue with Azure Germany Environment

### ISSUE THREAD

**Issue by Kormyr** [Azure/azure-sdk-for-net#3701]
Hi,

I wanted to get resources from the Azure Germany cloud.
Manual calls to the REST API endpoints worked succesfully, but I had troubles with the Microsoft.Azure.Management.ResourceManager.Fluent package.

I did not find code samples of this library for the German cloud, so I don't know if I'm doing something wrong.
The only way I could get it to work was to update 2 properties of the built-in classes (in Microsoft.Azure.Management.ResourceManager.Fluent.dll).
- AzureEnvironment:
![azureenvironment](https://user-images.githubusercontent.com/4302131/30425512-be4d8d54-9949-11e7-97c4-5a4e9f38889c.png)
The "AzureEnvironment.AzureGermanCloud.ManagementEnpoint" seems to be invalid, so I updated it from "https://portal.microsoftazure.de" to "https://management.core.cloudapi.de"

- ResourceManagementClient:
![resourcemanagementclient](https://user-images.githubusercontent.com/4302131/30425804-96c5f02c-994a-11e7-8931-53886b28b166.png)
The BaseUri property is hardcoded to the Azure Global cloud instead of getting it from the ResourceManagerEndpoint property of the AzureEnvironment object passed in the AzureCredentials constructor, so I updated it from "https://management.azure.com" to "https://management.microsoftazure.de"

Is there a better way to achieve this with the current version?

**Comment by hovsepm** [comment]
@kormyr this issue has been recently fixed and will be shipped in v1.3. Please see here for a workaround - https://github.com/Azure/azure-sdk-for-net/issues/3656

**Comment by Kormyr** [comment]
Any idea when it will be released?
I don't know how the issues are managed in this repository but I don't consider it closed until the fix is released, plus I don't see any change related to the ResourceManagerClient part in the pull request mentioned (https://github.com/Azure/azure-sdk-for-net/pull/3658). Will this also be fixed?
I talked about the ResourceManagementClient but SubscriptionClient, FeatureClient (and maybe others?) are also concerned.

**Comment by Kormyr** [comment]
Just got my answer: https://github.com/Azure/azure-libraries-for-net/blob/0e725531319775e348c21540c9a2c25000106c32/src/ResourceManagement/ResourceManager/Generated/ResourceManagementClient.cs

Nothing changed... Should we re-open this issue or should I create another one and wait for it to be fixed in the 1.4 version of the SDK?
