### ISSUE TITLE
[FEATURE REQ] Add support for function-calling

### ISSUE THREAD

**Issue by vandenbergjp** [Azure/azure-sdk-for-net#37013]
### Library name

Azure.AI.OpenAI

### Please describe the feature.

OpenAI added `function calling` to the chat completion api. It would be nice if this was supported by the library. Any plans?

[Announcement](https://openai.com/blog/function-calling-and-other-api-updates)
[Documentation](https://platform.openai.com/docs/guides/gpt/function-calling)

**Comment by navba-MSFT** [comment]
@vandenbergjp Thanks for reaching out to us and raising this query. We are looking into this query and we will provide an update.

**Comment by navba-MSFT** [comment]
@vandenbergjp I had a discussion internally with the Product Owners and got a confirmation that we’re working on bringing the latest state of the art capabilities to market in our partnership with OpenAI. We currently cannot share any ETA at this moment on when this would be made available. 

Please let me know if you have any follow-up queries.

**Comment by vandenbergjp** [comment]
Ok thanks. Hope you can update the package soon, so we make use of the new options in the openai api.

**Comment by navba-MSFT** [comment]
@vandenbergjp Sure. This feedback has been shared with the respective Product Owners.

**Comment by onionhammer** [comment]
@navba-MSFT  I dont see support for this listed anywhere, what PR closed this issue?
