### ISSUE TITLE
[Storage][DataMovement] Add DEBUG logging in certain areas for better debugging

### ISSUE THREAD

**Issue by jalauzon-msft** [Azure/azure-sdk-for-net#37024]
We should consider adding some custom DEBUG logging for parts of DataMovement, like eventing, status changes, etc., which will enable us to better debug customer reported issues when the ultimately arise. As is, it is difficult to debug certain types of failures, like stuck transfers, etc. but having some logs to understand what state we are in will help.

Will need to investigate how to tie into Azure Cores logging ideally.

**Comment by amnguye** [comment]
Good failing flakey tests would be the E2E pause and resume tests
