### ISSUE TITLE
[BUG] compute-dotnet-manage-virtual-machine-scale-sets sample is still track1

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-net#37032]
### Library name and version

Azure.ResourceManager.Compute

### Describe the bug

The [sample](https://learn.microsoft.com/en-us/samples/azure-samples/compute-dotnet-manage-virtual-machine-scale-sets/getting-started-on-managing-virtual-machine-scale-sets-in-c/) and its [repo](https://github.com/azure-samples/compute-dotnet-manage-virtual-machine-scale-sets/tree/master/) still uses track1 mgmt SDK.

### Expected behavior

We should either have track2 sample in repo. Or we should archive the repo, so it won't show in sample browse.
https://github.com/azure-samples/compute-dotnet-manage-virtual-machine-scale-sets/tree/master/

### Actual behavior

Sample uses deprecated track1 SDK. And customer can find it via sample browse https://learn.microsoft.com/en-us/samples/browse/?terms=virtual%20machine%20scale%20set&products=azure&languages=csharp

### Reproduction Steps

https://learn.microsoft.com/en-us/samples/browse/?terms=virtual%20machine%20scale%20set&products=azure&languages=csharp
find "[Getting started on managing virtual machine scale sets in C#](https://learn.microsoft.com/en-us/samples/azure-samples/compute-dotnet-manage-virtual-machine-scale-sets/getting-started-on-managing-virtual-machine-scale-sets-in-c/)"

**Comment by jsquire** [comment]
The azure-samples repository, this sample, and the MS learn documentation are now owned by our team.   This should be reported via the MS learn feedback tool so that the appropriate content authors are notified.
