### ISSUE TITLE
[BUG] Identity ignores options tenant when environment var set

### ISSUE THREAD

**Issue by ilya-scale** [Azure/azure-sdk-for-net#37046]
### Library name and version

Azure.Identity 1.9.0

### Describe the bug

`TenantId` for `DefaultAzureCredentialOptions` does not seem to affect environment credential.

### Expected behavior

Explicit `TenantId` should override any TenantId by any other credential used behind the scenes. 

Now it does not affect the outcome, and if acquiring token happens with an explicit tenant (same as TenantId), it would still not work.

If this is meant to be like this, the documentation should be fixed as now it says this setting overrides any other.

### Actual behavior

`TenantId` is ignored if environment variables are used

### Reproduction Steps

1. Set up environment variables to connect to Tenant A

```csharp
_tokenCredential = new DefaultAzureCredential(new DefaultAzureCredentialOptions
        {
            TenantId = "Tenant B"
        });
```

2. Get token without explicitly specifying a tenant
3. It would be Tenant A

### Environment

dotnet 7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @ilya-scale 
Could you provide some additional details about which [credential in the DefaultAzureCredential chain](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#defaultazurecredential) you are targeting to reproduce this? If you are not sure, [logging](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md) will reveal which one is selected.

In my testing, the TenantId option is respected for everything but `EnvironmentCredential` and `ManagedIdentityCredential`

**Comment by ilya-scale** [comment]
It is exactly EnvironmentCredential that I use both locally and in production
