### ISSUE TITLE
Microsoft.Azure.Management.Scheduler GetJob looses Authentication properties of derived type.

### ISSUE THREAD

**Issue by sloveon** [Azure/azure-sdk-for-net#3707]
JobsOperationsExtensions/JobOperations classes has correspondent Get/GetWithHttpMessagesAsync methods that return JobDefinition object as a result. There is an **Authentication** property in object hierarchy(Properties.Request.Authentication) of **HttpAuthentication** type which is the base class for
ClientCertAuthentication, BasicAuthentication, OAuthAuthentication etc. types.
Assuming that the job was initially created with concrete authentication type, once the get request returns JobDefinition object, the properties of type derived  from **HttpAuthentication** get lost during deserialization.

Is there any way to get the information with properties of concrete Authentication type using an SDK or this feature not implemented yet?

**Comment by shahabhijeet** [comment]
Waiting to get the GitHub id for the right person this needs to be assigned.

**Comment by jaakhter** [comment]
This is by-design. The authentication details are not returned by the service as part of job definition.
