### ISSUE TITLE
[BUG] OpenAI chat completions API does not include finish_reason to detect truncation

### ISSUE THREAD

**Issue by kzu** [Azure/azure-sdk-for-net#37079]
### Library name and version

Azure.AI.OpenAI v1.0.0-beta.5

### Describe the bug

The payload clearly contains this data: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-03-15-preview/inference.json#L711-L713

But the [Choices](https://learn.microsoft.com/en-us/dotnet/api/azure.ai.openai.chatcompletions.choices?view=azure-dotnet-preview#azure-ai-openai-chatcompletions-choices) property is a simple readonly list with no such property.

This value should be included so that clients can detect whether a "Load more" kinda of UEX is appropriate if the response was truncated due to max_tokens being reached.

### Expected behavior

Expose a property (perhaps FinishReason in the Usage object?) to expose this value from the underlying JSON.

### Actual behavior

There is no way to detect whether the response choices were truncated.

### Reproduction Steps

Send a request with a very small `max_tokens` value and an open question, and try to detect the truncation via this API.

### Environment

Environment: .NET SDK: Version:   8.0.100-preview.5.23303.2

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by kzu** [comment]
Hey, I'm really really needing this. Looks like it could be just a matter of adding a `bool Truncated` property to the `ChatCompletions` object (which already has `id, created, usage` values). OpenAI serialization is a bit odd because the `finish_reason` is sent as part of the array, so the generated code might need some tweaking?

**Comment by kzu** [comment]
Seems like I can use the FinishReason available on each choice, and just assume that if any choice as a `stop` value, the whole response has been truncated
