### ISSUE TITLE
[QUERY] Large memory allocations when uploading a file with Azure.Storage.Blobs

### ISSUE THREAD

**Issue by danigian** [Azure/azure-sdk-for-net#37073]
### Library name and version

Azure.Storage.Blobs 12.16.0

### Query/Question

As per my understanding, when uploading a non-seekable stream, Azure.Storage.Blobs library allocates in memory a buffer whose size is equal to the MaximumTransferSize option set in the client (see [Performance tuning for uploads and downloads with the Azure Storage client library for .NET](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-tune-upload-download))

In case no custom value is set, there is a default of 8MiB for MaximumTransferSize.

Behind the scenes the SDK is using an ArrayPool.Shared instance to allocate the buffer byte arrays needed for the upload. ArrayPool.Shared is being used and it is making sure that you could reuse the ArrayPool only for byte arrays up to 1MiB, otherwise, [if size is too large for the pool it allocates an array of exactly the requested length](https://github.com/dotnet/runtime/blob/b3afe992253738208ccaaa058e726553889928de/src/libraries/System.Private.CoreLib/src/System/Buffers/TlsOverPerCoreLockedStacksArrayPool.cs#LL143C74-L143C74)

Assuming we have hundreds of small files to be uploaded, this means that for small file transfer, 8MiB are allocated on the [LOH](https://learn.microsoft.com/en-us/dotnet/standard/garbage-collection/large-object-heap) resulting in a big amount of allocations and a delayed collection.

Knowing that the guideline is to actually tweak accordingly the MaximumTransferSize, I am wondering why the default of 8MiB was chosen, knowing that it would have contradicted the ArrayPool.Shared choice.

Any idea/suggestion/feedback?

Thanks!

**Comment by navba-MSFT** [comment]
Adding service team to look into this.

**Comment by danigian** [comment]
>  I don't believe it's any worse than no array pool
I think this is exactly the issue. For non-seekable streams, with default settings, we are never capable of using the default array pool (as the 8MiB default is conflicting with the 1MiB size of the default array pool)

The problem I see is not about optimization, rather is about applications going to provoke out of memory exceptions for fast and subsequent uploads from non-seekable streams.

/cc @jaschrep-msft

**Comment by jaschrep-msft** [comment]
It seems this query has been resolved (partially by external chat) and there isn't an action item as a result.
