### ISSUE TITLE
[QUERY] TenantResource.GetSubscriptions() returning wrong subscriptions for me

### ISSUE THREAD

**Issue by EdAlexander** [Azure/azure-sdk-for-net#37087]
### Library name and version

Azure.ResourceManager 1.6.0

### Query/Question

I am attempting to list subscriptions of a specific tenant (not my default tenant) and my call is resulting in only subscriptions of my default tenant.

```
TenantResource tenant = SelectedTenantResource;
var credOptions = new DefaultAzureCredentialOptions();
credOptions.TenantId = tenant.Data.TenantId.ToString();
var creds = new DefaultAzureCredential(credOptions);
ArmClient client = new ArmClient(creds);

foreach (var sub in client.GetSubscriptions())
```
//only subs from default tenant...

Any hints as to what I am doing wrong?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @EdAlexander , Thank you for using Azure SDK for .Net.
We can't repro your issue. Would you please provide more detials?
Like: What kind of DefaultAzureCredential is used here? ClientSecret/InteractiveBrowser/VisualStudio?
Have you try to replace the credOptions.TenantId with the known string?

**Comment by EdAlexander** [comment]
Thanks for the response!  I am able to get things working in a console application with the following code:
`// See https://aka.ms/new-console-template for more information
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Compute;
using Azure.ResourceManager.Resources;

List<TenantResource> Tenants = new();

Console.WriteLine("Aquireing ARMClient...");
ArmClient client = new ArmClient(new DefaultAzureCredential(true));

Console.WriteLine("Getting Tenants...");
try
{
    Tenants = client.GetTenants().ToList<TenantResource>();
    Tenants.ForEach(tenant => Console.WriteLine("   " + tenant.Data.DisplayName));

}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString());
}
finally
{
    Console.WriteLine("Tenants listing complete.");
}

Console.WriteLine("Listing Tenant Subscriptions...");
try
{
    foreach (var tenant in Tenants)
    {
        DefaultAzureCredentialOptions credentialOptions = new DefaultAzureCredentialOptions
        {
            ExcludeInteractiveBrowserCredential = false,
            TenantId = tenant.Data.TenantId.ToString()
        };

        ArmClient clientTenant = new ArmClient(new DefaultAzureCredential(credentialOptions));
        clientTenant.GetSubscriptions().ToList().ForEach(subscription => Console.WriteLine(tenant.Data.DisplayName + ": " + subscription.Data.DisplayName));
    }
}
catch(Exception ex)
{
    Console.WriteLine(ex.ToString());
}
finally
{
    Console.WriteLine("Subscription listing complete");
}
Console.ReadLine();
`

Each time I read the subscriptions from a tenant I am prompted for an account in the browser.  Is there a way to keep this from happening when acquiring ArmClient for each tenant?  Also, if the application is running on a device that is AzureAD joined, is there a way to aquire the tenant without interaction?

**Comment by HarveyLink** [comment]
Add @schaabs for Azure.Identity questions.

**Comment by christothes** [comment]
Hi @EdAlexander - Did you explicitly want to use the `InteractiveBrowserCredential` or would any developer credential do? If not, you should be able to use `AzureCliCredential`, for example, which will never prompt for interactive login once `az login` has been successfully run.

If you do want to use `InteractiveBrowserCredential`, you should be able to do this as described in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md#persisting-user-authentication-data) so that prompting only occurs the first time.
