### ISSUE TITLE
Avro decoder gets System.ArgumentOutOfRangeException when reading events from an empty queue

### ISSUE THREAD

**Issue by adibalsa** [Azure/azure-sdk-for-net#3709]
Avro decoder gets the following exception when reading events from an empty queue. Much better to return an empty resultset rather than throwing an exception.

-	MESSAGE: An unhandled exception from user code has been reported when invoking the method 'Extract' on the user type 'Microsoft.Analytics.Samples.Formats.Avro.AvroExtractor'
-	DETAILS: ==== Caught exception System.ArgumentOutOfRangeException   at Microsoft.Hadoop.Avro.BinaryDecoder.DecodeFixed(Int32 size)
               at Microsoft.Hadoop.Avro.Container.StreamReader`1.MoveNext()
               at Microsoft.Hadoop.Avro.Container.SequentialReader`1.<get_Objects>d__0.MoveNext()
                at Microsoft.Analytics.Samples.Formats.Avro.AvroExtractor.<Extract>d__2.MoveNext()
               at ScopeEngine.SqlIpExtractor<ScopeEngine::CosmosInput,Extract_0_Data0>.GetNextRow(SqlIpExtractor<ScopeEngine::CosmosInput\,Extract_0_Data0>* , Extract_0_Data0* output) in d:\data\ccs\jobs\18401d7a-d28f-469a-bf89-153cf8ca7a00_v0\sqlmanaged.h:line 1924

**Comment by adibalsa** [comment]
I've found the problem in the following method of SequentialReader class:

        public bool MoveNext()
        {
            if (this.stream.Position == this.stream.Length)
            {
                return false;
            }

            int objectCount = this.decoder.DecodeInt();
            int blockSize = this.decoder.DecodeInt();
            this.current = new AvroBufferReaderBlock<T>(this.serializer, this.codec, this.decoder.DecodeFixed(blockSize), objectCount);
            var marker = this.decoder.DecodeFixed(this.header.SyncMarker.Length);
            if (!marker.SequenceEqual(this.header.SyncMarker))
            {
                throw new SerializationException("Synchronization marker defined in the header does not match the read one.");
            }
            return true;
        }

I propose to change it as following:

        public bool MoveNext()
        {
            if (this.stream.Position == this.stream.Length)
            {
                return false;
            }

            int objectCount = this.decoder.DecodeInt();
			if (objectCount == 0)
            {
                return false;
            }

            int blockSize = this.decoder.DecodeInt();
            this.current = new AvroBufferReaderBlock<T>(this.serializer, this.codec, this.decoder.DecodeFixed(blockSize), objectCount);
			
			if (this.header.SyncMarker.Length == 0)
            {
                return false;
            }

            var marker = this.decoder.DecodeFixed(this.header.SyncMarker.Length);
            if (!marker.SequenceEqual(this.header.SyncMarker))
            {
                throw new SerializationException("Synchronization marker defined in the header does not match the read one.");
            }
            return true;
        }

**Comment by shahabhijeet** [comment]
@adibalsa can you clarify this issue you are reporting is for which Azure SDK.
Provide full name of the nuget package you are reporting this issue on.

**Comment by adibalsa** [comment]
@shahabhijeet  the issue is affecting Hyak based SDK.  I've also provided a fix for that SDK (see #3710). I need my change to be merged in Hyak main stream.  Moreover I ask to verify if the new Auto REST SDK has the same problem reported here. If it does, the fix has to be ported also on the new Auto Rest SDK.

**Comment by adibalsa** [comment]
I closed it by mistake, sorry. Issue is still valid.

**Comment by m1nkeh** [comment]
assume still not fixed?

**Comment by razlani** [comment]
> assume still not fixed?

assumption correct

**Comment by m1nkeh** [comment]
ok, so reading between the lines slightly, i assume this manifests itself if the Avro files are empty, i.e. for me, no events are sent to an Event Hub capture output during the time window.. so an empty *.avro file is written to blob storage.

I just handled the Exception, and raised a warning that we had an empty *.avro file.. has this fix been raised as a PR pending, or only a suggestion in this defect?
