### ISSUE TITLE
[KeyVauly] Cannot mock `SignResult` in `Azure.Security.KeyVault.Keys` at UT

### ISSUE THREAD

**Issue by v-caxian** [Azure/azure-sdk-for-net#37092]
### Information

The method [CryptographyClient.SignAsync()](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Keys/src/Cryptography/CryptographyClient.cs#L754) return the [SignResult](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Keys/src/Cryptography/SignResult.cs#L17) object directly, which is only have an internal constructor that I cannot mock it in UT.

Is it possible to consider adding a public constructor to this object, or return an interface type in the `SignAsync` method? And I was wondering if there is someway to mock the return value of `SignAsync` in UT?

```cs
var cryptographyClient = Substitute.For<CryptographyClient>();
await cryptographyClient.SignAsync(Arg.Any<SignatureAlgorithm>(), Arg.Any<byte[]>(), Arg.Any<CancellationToken>()).ReturnsForAnyArgs(???);
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
For all our Azure SDKs named `Azure.*` you will find a factory class alongside the models typically you should use for mocking. In this case, use [`CryptographyModelFactory.SignResult`](https://learn.microsoft.com/dotnet/api/azure.security.keyvault.keys.cryptographymodelfactory.signresult)
