### ISSUE TITLE
Deserialize AnalyzeResult [FEATURE REQ]

### ISSUE THREAD

**Issue by minimalisticMe** [Azure/azure-sdk-for-net#37094]
I am using `Azure.AI.FormRecognizer` `v4.0.0` in `.NET 7` and want to cache a request from Form Recognizer.
The caching is necessary for internal regression and tests that I do not want to call the Azure Form Recognizer endpoint with the same file multiple times per second.

From `DocumentAnalysisClient` I am calling `AnalyzeDocumentAsync` and get a result of type `AnalyzeResult`.
This `AnalyzeResult` I save to my disk via
```
var jsonString = JsonSerializer.Serialize(analyzeResult);
await File.WriteAllTextAsync(filename, jsonString);
```
For tests or internal regression I then want to read the results with
```
var jsonString = await File.ReadAllTextAsync(filename);
JsonSerializer.Deserialize<AnalyzeResult>(jsonString);
```
The deserialize above fails with 
```
System.NotSupportedException : Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Azure.AI.FormRecognizer.DocumentAnalysis.AnalyzeResult'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
    ---- System.NotSupportedException : Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Azure.AI.FormRecognizer.DocumentAnalysis.AnalyzeResult'.
```

I would expect to deserialize `AnalyzeResult` into a working object.

**Comment by jsquire** [comment]
//cc: @m-nash, @pallavit

**Comment by dimitriskad** [comment]
This is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/27202.

@minimalisticMe For a workaround (for the time being), take a look at https://github.com/Azure/azure-sdk-for-net/issues/27202#issuecomment-1052800726.

**Comment by minimalisticMe** [comment]
Closing as it is a duplicate of https://github.com/Azure/azure-sdk-for-net/issues/27202 and the workaround mentioned by @dimitriskad (https://github.com/Azure/azure-sdk-for-net/issues/27202#issuecomment-1052800726) is working.
