### ISSUE TITLE
409 Conflict possible for a CreateContainerIfNotExistsAsync?

### ISSUE THREAD

**Issue by changov** [Azure/azure-sdk-for-net#37107]
What's the point of "IfNotExists" if a Conflict would be returned? Based on logs, it seems the client library first does a GET on the container, and if it is found, returns success. So, I guess this is a documentation error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e9e96ea8-0b8f-fde0-77a0-743baefcd6c3
* Version Independent ID: 01c62957-c210-85c7-3260-e81328d20a1d
* Content: [Database.CreateContainerIfNotExistsAsync Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.database.createcontainerifnotexistsasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Database.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Database.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` package is maintained as [#3927](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3927).
