### ISSUE TITLE
ServiceClient should dispose of root HttpClientHandler if it created it

### ISSUE THREAD

**Issue by kiwidev** [Azure/azure-sdk-for-net#3712]
ServiceClient creates a new root HttpClientHandler (WebRequestHandler or HttpClientHandler) when it is not passed into the constructor. This handler is never disposed.

This leads to the following behaviors when multiple serviceClients are created:
 - A connection leaks and is not disposed until the 120second timeout.
 - A this is limited to 200 connections by default, this leads to socket starvation and requests failing to be processed

See https://github.com/Azure/azure-sdk-for-net/issues/2225 and https://github.com/Azure/azure-sdk-for-net/issues/1234 for examples of this issue.

The standard recommendation is to use a singleton ServiceClient (although the guidance should more likely be to use a singleton HttpClientHandler), but in some environments (such as Azure Functions for small functions) this is not possible / practical.

Recommendation:
 - ServiceClient should store a flag saying whether it created / owns the HttpClientHandler
 - ServiceClient should dispose that as part of dispose

It is possible that this will be a breaking change for some users who are relying on this not being disposed / extracting the client. This could be resolved by a flag (similar to the one implemented in https://github.com/Azure/azure-sdk-for-net/pull/3547).

**Comment by shahabhijeet** [comment]
@kiwidev the behavior you are suggesting occurs when you call Dispose() on the client? or some other scenario?
Also are you suggesting rather than setting HttpClientHandler = null in the client dispose, call HttpClientHandler.Dispose()?

**Comment by kiwidev** [comment]
Apologies, I hadn't found time to issue a PR yet.

The scenario is when `Dispose()` is called on ServiceClient. This particularly comes up when customers are creating a large number of service clients (> 100 / minute).

None of the handlers are disposed by ServiceClient (`HttpClient` is constructed with `disposeHandler: false`). I think this is the correct behavior for user provided handlers as often they are reused across clients etc.
However, the problem is that the underlying root HttpClientHandler is never disposed, even though this is created and owned by the ServiceClient. The HttpClientHandler is an expensive and finite resource.

So yes, I would suggest that:
 - keep a reference to the RootClientHandler when it is created (not when it is passed in by user)
 - On `ServiceClient.Dispose` also dispose that handler (if set).

**Comment by Porges** [comment]
This is a pretty bad problem. Is anything being done about it?

**Comment by brjohnstmsft** [comment]
@shahabhijeet Is there a plan to fix this?

**Comment by shahabhijeet** [comment]
This has been fixed a while back. Sorry this opened issue has not been addressed for so long.
Let me know if you still see this issue with the current [client runtime](https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime/2.3.19)
Please specify the version you are currently using.

**Comment by shahabhijeet** [comment]
If you still see an issue with the latest ClientRuntime, please reopen this issue or open a new issue with details about the version of the SDK you are using.

**Comment by brjohnstmsft** [comment]
@shahabhijeet I saw some changes that might be related to this when we recently regenerated our SDK code with the latest version of AutoRest, so likely this will be fixed for us with the next release of our SDK.

**Comment by Obi-Dann** [comment]
Hey, sorry, was it ever fix? I am investigating the same issue and still see a TODO in your source code to dispose the handlers
https://github.com/Azure/azure-sdk-for-net/blob/bddc5ff0e8120db98f4e0943b4b2602767dc5463/sdk/mgmtcommon/ClientRuntime/ClientRuntime/ServiceClient.cs#L506-L508
cc @shahabhijeet  @kiwidev
