### ISSUE TITLE
Add links to mode descriptions on page: ReceiveMode Enum 

### ISSUE THREAD

**Issue by BA-AZ** [Azure/azure-sdk-for-net#37148]
Please add links to what modes the ReceiveMode Enums refer to. So that others can then read about what each of the modes will do. e.g. have links to https://learn.microsoft.com/en-us/azure/service-bus-messaging/message-transfers-locks-settlement#receiveanddelete

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f76fe8a7-501f-acbd-76cc-0201764173a4
* Version Independent ID: 35d05909-a780-d644-2838-10c77992f9d3
* Content: [ReceiveMode Enum (Microsoft.ServiceBus.Messaging) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.servicebus.messaging.receivemode?view=azure-dotnet#microsoft-servicebus-messaging-receivemode-peeklock)
* Content Source: [xml/Microsoft.ServiceBus.Messaging/ReceiveMode.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.ServiceBus.Messaging/ReceiveMode.xml)
* Service: **service-bus-messaging**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @BA-AZ.  Thank you for reaching out and we regret that you're experiencing difficulties.  Please be aware that the Service Bus functionality in the `WindowsAzure.ServiceBus` package has been superseded by `Azure.Messaging.ServiceBus` and is not recommended for new development.  Though `WindowsAzure.ServiceBus` has not yet been formally deprecated, it is only receiving critical bug and security fixes.  There are no planned enhancements to the existing documentation.
