### ISSUE TITLE
[BUG] AzureMaps - No way to correlate Matrix response summary to request geoposition

### ISSUE THREAD

**Issue by chassq** [Azure/azure-sdk-for-net#37146]
### Library name and version

Maps Route 1.0.0-beta1

### Describe the bug

You can see this is the example at (https://learn.microsoft.com/en-us/dotnet/api/overview/azure/Maps.Routing-readme?view=azure-dotnet-preview&preserve-view=true#route-matrix). Let's say you have 1 origin GeoPosition and 5 destination GeoPositions for which you want to see LengthInMeters. On our end we have a unique identifier for each GeoPosition (origin and destination). When we send the request based only on Lat/Long of the GeoPosition there seems no way to effectively correlate the summary for each RouteMatrix to the unique identifier we have for each GeoPosition in the request. I would ask you add some way to do this effectively (e.g., add an optional external id to the GeoPosition object and return the origin and destination GeoPosition external id int he summary OR at least return the EXACT origin/destination lat/long coords passed in the request that were used to build the summary). Not having this makes it impossible to correlate request GeoPositions to Summaries and means we have to make 1 request at-a-time. Ordinal correlation does not work in cases where you send in 5 destination GeoPositions (for example) and get back 4 summaries.

### Expected behavior

Be able to effectively correlate GeoPositions used to create matrix summaries.

### Actual behavior

No way to do this and makes you call the API one call at-a-time.

### Reproduction Steps

See example code at https://learn.microsoft.com/en-us/dotnet/api/overview/azure/Maps.Routing-readme?view=azure-dotnet-preview&preserve-view=true#route-matrix. Note that GeoPositions cannot be effectively correlated with returned matrix summaries.

### Environment

Windows 11 latest patches.

Azure Maps Route 1.0.0-beta1

Microsoft Visual Studio Enterprise 2022
Version 17.7.0 Preview 2.0
VisualStudio.17.Preview/17.7.0-pre.2.0+33808.371
Microsoft .NET Framework
Version 4.8.09032

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA741
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.7.160.18752
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.160.18752
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.7.160.18752
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.7.0-2.23280.4+66772aff549b2981094175a6f2f69600596c1913
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Extensibility Message Bus   1.4.33 (main@eea8cc7)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.7.20 (81efaa2)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.7.2.2330502+e0cf0b1121019f24d79b73d6d30f5870ca83c81d
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.1.0
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.20531.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-2.23280.4+66772aff549b2981094175a6f2f69600596c1913
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23272.3+96bfa24a5fee6722ed3e2b280d37e80b594bbcf4
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Xamarin   17.7.0.135 (main@f75253e)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.7.2.4 (remotes/origin/d17-7@105126fbf4)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.7.17 (95eb8d3)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.0.13 (d17-5/3f21639)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 73df89a
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.5 (191fe02ea)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by dubiety** [comment]
Hi @chassq , thank you for raising this feature request. We'll support the unique ID for each origin/destination pair in our new API version. 
For now, the returned result will be a 2D array, in the format:
```text
Matrix: [
    // Origin 1 to all destinations
    [
        { origin 1 to destination 1},
        { origin 1 to destination 2 },
        ...
    ]
    // Origin 2 to all destination
    [
        { origin 2 to destination 1},
        { origin 2 to destination 2 },
        ...
    ]
]
```
You can iterate through the 2D array (List) to get all the result in the order illustrate in the example above. 
Let me know if you have any question. Thank you so much!

**Comment by chassq** [comment]
Hey @dubiety , Great to hear! One question. If I were to send in say 1 origin and 5 destinations, would I always get back 5 route summaries or if one happed to failed, would it return say 4 summaries?

**Comment by dubiety** [comment]
Hi @chassq ,

In that case, it still returns 5 results, but for the failed route, the `statusCode`, `response` and `detailedError` may tell you the error reason. Usually, you'll receive statueCode = 400 for failed route. For example, I have 1 origin and 3 destinations and the third destination is an invalid route, you might see:

```json
{
    "matrix": [
        [
            {
                "statusCode": 200,
                "response": {
                    "routeSummary": { origin 1 to destination 1 }
                }
            },
            {
                "statusCode": 200,
                "response": {
                    "routeSummary": { origin 1 to destination 1 }
                }
            },
            {
                "statusCode": 400,
                "response": "Some error message here",
                "detailedError": {
                    "message": "Detailed Error message",
                    "code": "XXX"
                }
            }
        ]
    ],
    "summary": {
        "successfulRoutes": 2,
        "totalRoutes": 3
    }
}
```

**Comment by chassq** [comment]
Thanks @dubiety ! Much appreciated!
