### ISSUE TITLE
SDK request will timeout if backend service of RP returns 5xx

### ISSUE THREAD

**Issue by Zoe-ms** [Azure/azure-sdk-for-net#3714]
Here is the scenario:
a.	We have the backend service after RP, so the request will be called through “SDK => RP => Backend Service”.
b.	Backend service client and RP client are both based on Microsoft.Rest.ClientRuntime, generated by swagger through autorest.
c.	The ClientRuntime library will by default retry 3 times with ExponentialBackoffRetry on 5xx (RetryDelegatingHandler.cs), so we have cascade retry for every request
d.	And the ClientRuntime uses the default timeout 100s of HttpClient
e.	Then if 5xx occurs in backend service, there will be (1 + 3) * (1 + 3) = 16 (3 is retry times) requests sent to backend, and adding the BackOff time, the final response will be return after 100s, then the user will get a timeout error.

**Comment by shahabhijeet** [comment]
@Zoe-ms as we talked over skype. This is not a blocker for your team at this point.
The ask is, you want the CR to return 5xx status code and not retry it.
If we decide to support this, this will have to a rolled out where RPs can participate and opt for status code that would like not to be retried but returned back.

**Comment by AlexGhiondea** [comment]
Closing for now. Please reactivate if this continues to be an issue.
