### ISSUE TITLE
SDK behavior if AsyncOperation and Location header are both presents

### ISSUE THREAD

**Issue by Zoe-ms** [Azure/azure-sdk-for-net#3715]
Will need use AsyncOperation header for async 202 pattern, so would like to confirm the behavior of AsyncOperation and Location behavior in SDK. Thanks.

**Comment by shahabhijeet** [comment]
We have seen multiple RPs requesting for this change.
This change will be done in Nov. milestone

**Comment by shahabhijeet** [comment]
This has been checked in and now SDKs will process both headers.
