### ISSUE TITLE
[QUERY] Is there a way to call an unlisted resource action?

### ISSUE THREAD

**Issue by jovinson-ms** [Azure/azure-sdk-for-net#37180]
### Library name and version

all

### Query/Question

Is there a way to construct a custom url to reference a resource action that a resource provider exposes, but is not listed as part of the SDK? I wasn't able to find one by either extending the client or by using `GenericResource`.

**Comment by HarveyLink** [comment]
Hi @jovinson-ms , our SDK is auto generated based on service swagger files. If there is any operation in swagger you need is not added to SDK, you could open a issue to request it.
