### ISSUE TITLE
Azure.Monitor.OpenTelemetry.AspNetCore: How to set the log level.

### ISSUE THREAD

**Issue by v-iyamauchi** [Azure/azure-sdk-for-net#37218]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.0.0-beta.4

### Query/Question

How can we set the log level in appsettings.json or in code when emitting telemetry to an Azure Application Insights resource using Azure.Monitor.OpenTelemetry.AspNetCore package? Please let me know if you have any document about this.

Thank you,

### Environment

Environment: test
OS: Windows 11
.NET: 7.0.304
VS 2022: 4.8.09032

**Comment by navba-MSFT** [comment]
@v-iyamauchi Thanks for reaching out to us and reporting this issue. Could you please check if [this article](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore#enabling-azure-monitor-opentelemetry-in-your-application) helps ?

Awaiting your reply.

**Comment by v-iyamauchi** [comment]
Hi @navba-MSFT , yes, the article was helpful, but I am looking for an equivalent of this in Azure Monitor OpenTelemetry.

https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#how-filtering-rules-are-applied

**Comment by vishweshbankwar** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/logs/customizing-the-sdk/README.md#log-filtering

**Comment by navba-MSFT** [comment]
@v-iyamauchi Could you please check if the above article helps ?

**Comment by navba-MSFT** [comment]
@v-iyamauchi The action is currently pending on you to check if [the above article](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/logs/customizing-the-sdk/README.md#log-filtering) helped.  If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
