### ISSUE TITLE
[BUG] Resource Manager Automation exception

### ISSUE THREAD

**Issue by krishna85s** [Azure/azure-sdk-for-net#37214]
### Library name and version

Azure.ResourceManager.Automation 1.0.1.0

### Describe the bug

Azure.ResourceManager.Automation UpdateAsync throws invalid uri exception

### Expected behavior

I'm trying to update a webhooks' expiration date using the below code. But I get an exception on the UpdateAsync. This seems like a bug as passing a uri is impossible.

         foreach (var webhook in webhooks) //where webhook is AutomationWebhookResource
                    {
                        var difference = DateTimeOffset.Compare(webhook.Data.ExpireOn.Value, DateTimeOffset.Now);
                        if (difference <= 0)
                        {
                            webhook.Data.ExpireOn.Value.AddMonths(12);

                            var webhookResource =  await webhook.UpdateAsync(
                                patch: new AutomationWebhookPatch() { 
                                    Name = webhook.Data.Name, 
                                    Description = "Update expiry date."});
                       }
                   }

### Actual behavior

Below is the exception that gets thrown.

System.UriFormatException
  HResult=0x80131537
  Message=Invalid URI: The URI is empty.
  Source=System.Private.Uri
  StackTrace:
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.Automation.AutomationWebhookData.DeserializeAutomationWebhookData(JsonElement element)
   at Azure.ResourceManager.Automation.WebhookRestOperations.<UpdateAsync>d__18.MoveNext()
   at Azure.ResourceManager.Automation.AutomationWebhookResource.<UpdateAsync>d__18.MoveNext()
   at WebhookExpiryAlert.Function1.<Run>d__0.MoveNext() in C:\Users\Krishna\Desktop\vista-repos\webhook-expiry-alert\WebhookExpiryAlert\Function1.cs:line 73

  This exception was originally thrown at this call stack:
    [External Code]
    WebhookExpiryAlert.Function1.Run(Microsoft.Azure.WebJobs.TimerInfo, Microsoft.Extensions.Logging.ILogger) in Function1.cs

### Reproduction Steps

 var webhookResource =  await webhook.UpdateAsync(
                                patch: new AutomationWebhookPatch() { 
                                    Name = "Test", 
                                    Description = "Update expiry date."});

### Environment

**Hosting platform**
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64

**IDE and version**
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.4.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by krishna85s** [comment]
Hi @ArthurMa1978 cc @jsquire, could I please get some feedback on this issue?

**Comment by dvbb** [comment]
Hi @krishna85s,
sorry for the late reply, this issue has been [fixed](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/automation/Azure.ResourceManager.Automation/CHANGELOG.md#bugs-fixed-1) in the latest version `Azure.ResourceManager.Automation
 1.1.0-beta.1`

**Comment by krishna85s** [comment]
Thanks @dvbb, the issue has been resolved. Thanks again for the effort 👍.
