### ISSUE TITLE
Azure Search - Managed Identity

### ISSUE THREAD

**Issue by ThomasPe** [Azure/azure-sdk-for-net#37210]
```
All requests to a search service need an api-key that was generated specifically for your service. The api-key is the sole mechanism for authenticating access to your search service endpoint.
```

This doesn't seem right - Managed Identity should even be the preferred method imo - or am I missing something here?

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme?view=azure-dotnet#authenticate-the-client

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f60660a9-9a80-3259-8eeb-79d18bcf5d50
* Version Independent ID: 6f76c320-0f86-7013-a389-8aba5421706e
* Content: [Azure Cognitive Search client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme?view=azure-dotnet#authenticate-the-client)
* Content Source: [api/overview/azure/latest/search.documents-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/search.documents-readme.md)
* Service: **search**
* GitHub Login: @ShivangiReja
* Microsoft Alias: **shreja**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
