### ISSUE TITLE
[UserVote] Upgrade Microsoft.Rest.ClientRuntime.Azure.Authentication to ADAL 3.16+

### ISSUE THREAD

**Issue by shahabhijeet** [Azure/azure-sdk-for-net#3730]
Upgrade ADAL to 3.16+ to both .NET 452 and .NET Standard
Opened up for votes from customers.
Helps to prioritize our work items for next release.

**Comment by brijeshb** [comment]
It's frustrating when a SDK that's supposed to be the vnext / modern forces you to use the last major version of ADAL, please prioritize this work.
