### ISSUE TITLE
[BUG] EventHubProducerClient is leaking memory

### ISSUE THREAD

**Issue by AshwinChandlapur** [Azure/azure-sdk-for-net#37311]
### Library name and version

Azure.Messaging.EventHubs.Producer 5.9.2

### Describe the bug

Sending messages to event hub using EventHubProducerClient is leaking memory.

![image](https://github.com/Azure/azure-sdk-for-js/assets/11557234/44a04cca-55e5-43de-aff4-6a395dceacb4)

![image](https://github.com/Azure/azure-sdk-for-js/assets/11557234/7ae12054-8269-4221-84b2-122e3127f014)

### Expected behavior

The GC collector should ensure unused resources are released and memory should be more or less constant, should not increase.

### Actual behavior

The memory used by the application keeps increasing over time and the application eventually crashes. 

### Reproduction Steps

https://github.com/AshwinChandlapur/EventHubMessageProducer
This repo has sample code showing the way I am using EventHubProducerClient. 

1. https://github.com/AshwinChandlapur/EventHubMessageProducer/blob/master/Producer/QueueProcessor.cs
`QueuProcessor` has dependency injection from `EventHubHelper`.

In Line 25, I call the Send method that initiates event-hub message publish sequence. 

2. https://github.com/AshwinChandlapur/EventHubMessageProducer/blob/master/Producer/EventHubHelper.cs
The send method here uses EventHubProducerClient to push message to EventHub.

**Comment by jsquire** [comment]
Hi @AshwinChandlapur.  Thank you for reaching out and we regret that you're experiencing difficulties.  Would you please demonstrate how you're using the client and provide a small self-contained repro for the behavior that you're seeing?

**Comment by AshwinChandlapur** [comment]
@jsquire Thank you for the quick response. I have updated the description with sample code that I have used to push messages to EventHub.

**Comment by jsquire** [comment]
@AshwinChandlapur:  Did you close this intentionally, or did you find that the root cause was external to the SDK and are no longer in need of assistance?
