### ISSUE TITLE
What is the URI/URL for Embeddings with AzureOpenAI

### ISSUE THREAD

**Issue by securigy** [Azure/azure-sdk-for-net#37323]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.5

### Query/Question

In the examples 1 through 5:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/openai/Azure.AI.OpenAI/tests/Samples/Sample01_Chatbot.cs

URL is a placeholder: "https://myaccount.openai.azure.com/"
What is "myaccount"? Azure Resource Name? Subscription Name?

This Url is used for completions and chat. What would be URL for Embeddings? Is the following correct?
https://{resourceName}.openai.azure.com/openai/deployments/{deploymentId}/embeddings?api-version={apiVersion}
(It took it from somewhere on MS sites, and it might be for Semantic Kernel case, or HttpClient)
So what is Embeddings URL for AzureOpenAI?

 Is there any example for Embeddings?

### Environment

Win11
.NET 7
VS2022 17.5.4
Azure.AI.OpenAI 1.0.0-beta.5

**Comment by SaurabhSharma-MSFT** [comment]
@securigy "myaccount" will be the resource name of the Open AI service.  You can refer to [this](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/embeddings?tabs=csharp) document to get the embeddings using the Open AI Endpoint.
Thanks.
