### ISSUE TITLE
[BUG] Set up mapping between spec repo folder and SDK repo folder for SDK automation

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-for-net#37335]
### Library name and version

Azure.ResourceManager.Sql

### Describe the bug

Right now, in spec repo the folder is [sql](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/sql).
But, in azure-sdk-for-net the folder is [sqlmanagement](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/sqlmanagement).
This mismatching is causing failures of .NET SDK track 2 automation for swagger PRs of sql.

### Expected behavior

The folder names should align.

### Actual behavior

Folder names do not align.

### Reproduction Steps

https://github.com/Azure/azure-rest-api-specs/pull/24349#issuecomment-1583329294
.NET SDK Track 2 automation is failing.

**Comment by live1206** [comment]
After discussing with @m-nash, we can't guarantee to align the folder structure for all RPs. 
There are cases some RPs are sharing the same swagger folder, but they would like to release their SDKs separately, which end up into different SDK folders.

There is a [property](https://github.com/Azure/azure-rest-api-specs/blob/14a3cf043a4567366366f3d70829b4ef57711eb3/specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml#L3) specifying the SDK structure in TypeSpec, we can have something similar in .NET SDK generation to have the mapping between swagger folder to SDK folder.

**Comment by tdoshin** [comment]
Can this be closed? @live1206

**Comment by live1206** [comment]
@tdoshin Not really, this still needs to be fixed, renamed to repurpose.
