### ISSUE TITLE
[BUG] The param AdminGroupObjectIds defined in Azure.ResourceManager.ContainerService.ManagedClusterAadProfile is readonly.

### ISSUE THREAD

**Issue by lk668** [Azure/azure-sdk-for-net#37334]
### Library name and version

Azure.ResourceManager.ContainerService

### Describe the bug

The param `AdminGroupObjectIds` defined in `ManagedClusterAadProfile` is readonly. How do we set this value via sdk? Actually this param could be set via rest api.

### Expected behavior

We could set it.

### Actual behavior

It's readonly.

### Reproduction Steps

None

**Comment by jsquire** [comment]
Hi @lk668.  Thank you for reaching out and we regret that you're experiencing difficulties.  As a convention across libraries in the Azure SDK, collection types for models are intentionally read-only.   Their value can be set by mutating the existing collection.  This can be done by either adding members after the object has been constructed or using C#'s initializer syntax as part of construction.   

```csharp
// Example: adding items after construction.
var profile = new ManagedClusterAadProfile();
profile.AdminGroupObjectIds.Add(someGuid);
profile.AdminGroupObjectIds.Add(otherGuid);

// Example: initializer syntax
var profile = new ManagedClusterAadProfile
{
    AdminGroupObjectIds = { someGuid, otherGuid }
};
```

**Comment by lk668** [comment]
> Hi @lk668. Thank you for reaching out and we regret that you're experiencing difficulties. As a convention across libraries in the Azure SDK, collection types for models are intentionally read-only. Their value can be set by mutating the existing collection. This can be done by either adding members after the object has been constructed or using C#'s initializer syntax as part of construction.
> 
> ```cs
> // Example: adding items after construction.
> var profile = new ManagedClusterAadProfile();
> profile.AdminGroupObjectIds.Add(someGuid);
> profile.AdminGroupObjectIds.Add(otherGuid);
> 
> // Example: initializer syntax
> var profile = new ManagedClusterAadProfile
> {
>     AdminGroupObjectIds = { someGuid, otherGuid }
> };
> ```

Got it. Thanks a lot for your detailed comments! @jsquire .
