### ISSUE TITLE
[QUERY] Unit testing ResourceManager.TrafficManager

### ISSUE THREAD

**Issue by msspider117** [Azure/azure-sdk-for-net#37340]
### Library name and version

Azure.ResourceManager.TrafficManager 1.0.0

### Query/Question

I have code that needs to be tested that uses the traffic manager apis.
How does one go about writing unit tests for things that use these apis. I'm a bit stuck. 

To note: I want my test to **not** modify any cloud resource, I just want to test the logic of the code.
Is that even possible?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @msspider117 , Thank you for using Azure SDK for .NET.
There is model factory class you could use to mock the tests. Please check the latest packages.
