### ISSUE TITLE
[QUERY] How do I exclude a shared project reference from code coverage?

### ISSUE THREAD

**Issue by nikithauc** [Azure/azure-sdk-for-net#37367]
### Library name and version

Azure communications

### Query/Question

Hello,

I am trying to improve the code coverage for the Azure Communication Chat SDK. We are targeting 80%.  The code coverage reports coverage for the dependency `Azure.Communication.Identity` which is causing an inaccurate estimate. How do I exclude this dependency from the coverage? 

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2886679&view=codecoverage-tab

**Comment by nikithauc** [comment]
Related to #17066

**Comment by jsquire** [comment]
@nikithauc : I believe that this has been answered for ACS in the past and the recommended solution was to use `[ExcludeFromCodeCoverage]` as discussed in #17066 and #19567.

@heaths: Do you have any additional guidance to share?

**Comment by nikithauc** [comment]
@jsquire  Thank you for responding!
I tried using [ExcludeFromCodeCoverage] after adding new partials and excluding them did not work for me. I do. But that did not work could be because the partials cannot be in different assemblies. 

For example, Azure.Communication.Identity contains the following `internal partial` classes which is in a different project that I do not own.
<img width="923" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/23219007/109f3ea4-c2ad-4ee9-986f-13ef0f66f049">

How do I use it to exclude classes which are in other assembly?

**Comment by nikithauc** [comment]
Thank you @heaths for opening #37416! Closing this issue as my query has been responded to.

**Comment by heaths** [comment]
> How do I use it to exclude classes which are in other assembly?

@nikithauc it should exclude code from other assemblies already. If this is shared code that you reference within the .csproj, it's included as if it was part of the project. That's what most of our shared code in the repo is. That takes additional work to exclude.
