### ISSUE TITLE
[BUG] Internal Server Error with trivially simple code to send/receive message from queue (and missing messages)

### ISSUE THREAD

**Issue by cbailiss** [Azure/azure-sdk-for-net#37362]
### Library name and version

Azure.Storage.Queues 12.14.0.0

### Describe the bug

Simple code to create an Azure queue. add a message to the Azure queue then read it immediately again results in an "Internal Server Error".

Also the same problem is observed with an existing queue created an hour ago - and with a queue created in the Azure Portal, so I don't think the "creating the queue" step is significant.

### Expected behavior

Code should be able to create a new queue, add a message to the queue and then read the message from the queue.

Code is included in the "repro" box below.

### Actual behavior

Two variations are seen (both wrong behaviour).

**Actual behaviour 1**

This tends to happen when there are more messages in the queue, i.e. after the repro code has been run a few times.

Output to console:
```
Creating queue client...
Sending message...
Counting messages...
Approx message count = 8
Receiving message...
```

Code then hangs for about a minute then errors on the read line>
`await oQueueClient.ReceiveMessageAsync(cancellationToken: oCT)` 

An example of the error:

```
Azure.RequestFailedException: 'Server encountered an internal error. Please try again after some time.
RequestId:9201f1cb-5003-0042-0f05-ad2a7a000000
Time:2023-07-02T16:53:47.9975068Z
Status: 500 (Server encountered an internal error. Please try again after some time.)
ErrorCode: InternalError

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InternalError</Code><Message>Server encountered an internal error. Please try again after some time.
RequestId:9201f1cb-5003-0042-0f05-ad2a7a000000
Time:2023-07-02T16:53:47.9975068Z</Message></Error>

Headers:
x-ms-request-id: 9201f1cb-5003-0042-0f05-ad2a7a000000
x-ms-version: 2018-11-09
x-ms-error-code: InternalError
Connection: close
Content-Length: 253
Cache-Control: no-cache
Content-Type: application/xml
Date: Sun, 02 Jul 2023 16:53:47 GMT
Server: Windows-Azure-Queue/1.0 Microsoft-HTTPAPI/2.0
```

This has been happening for at least the last six hours, so "please try again after some time" doesn't seem all that good an answer.

It's worth nothing that when the code runs, the queue is created and the message is appended.

Interestingly, after the error above, the queue contents cannot be browsed in the Azure Portal (using the account key) or in Azure Storage Explorer.  In both cases the UIs hang then an error is displayed.  
However, the queue can be cleared using Azure Storage Explorer.  When the queue is cleared, the queue can be browsed in the Azure Portal and the Azure Storage Explorer.  However, if the code is run again to append a message, then both UIs can't read the queue again and error when attempting to browse the queue.

**Actual behaviour 2**

This tends to happen when the queue is empty or only has a couple of messages in it.

Output similar to the following is seen:

```
Creating queue client...
Sending message...
Counting messages...
Approx message count = 3
Receiving message...
No message received!
```

i.e. no message is received even though there are messages in the queue and no other client is running to receive messages.

### Reproduction Steps

Code is using a connection string with the account key of the form
`DefaultEndpointsProtocol=https;AccountName=--redacted--;AccountKey=--redacted--;EndpointSuffix=core.windows.net`

Code:
```
QueueClient oQueueClient = new QueueClient(sConStr, sQueueName);

Console.WriteLine("Creating queue client...");
await oQueueClient.CreateIfNotExistsAsync(cancellationToken: oCT);

Console.WriteLine("Sending message...");
BinaryData bData = new BinaryData(new byte[] { 1, 3, 5, 7 });
await oQueueClient.SendMessageAsync(bData, cancellationToken: oCT);

Console.WriteLine("Counting messages...");
QueueProperties oQueueProperties = await oQueueClient.GetPropertiesAsync(oCT);
Console.WriteLine($"Approx message count = {oQueueProperties.ApproximateMessagesCount}");

Console.WriteLine("Receiving message...");
QueueMessage oMessage = await oQueueClient.ReceiveMessageAsync(cancellationToken: oCT);
if (oMessage == null) Console.WriteLine($"No message received!");
else Console.WriteLine($"Message received, length = {oMessage.Body.ToArray().Length}");
Console.WriteLine("Press any key to exit.");
Console.ReadKey();
```

### Environment

Code is running locally in Visual Studio - Windows 10 - .NET Framework 4.8 Console App.

**Comment by navba-MSFT** [comment]
@cbailiss Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@cbailiss While I used the same above code you had shared, I encountered the same issue. So, I looked at the backend logs and found that the cause of the issue was the message you are sending to the queue.

> **If a message contains binary data, [Base64-encode](https://learn.microsoft.com/en-us/dotnet/api/system.convert.tobase64string) the message.**

While I updated the code to `await oQueueClient.SendMessageAsync("Hello world", cancellationToken: CancellationToken.None);` it worked just fine. Hope this helps.

**Comment by cbailiss** [comment]
Thank you very much for the feedback - very useful to understand that this is the problem.

I suggest that the platform should never return an "Internal Server Error".  It should return a more helpful error message.  So this still looks like a bug that needs fixing - i.e. provide a meaningful error - both in the .NET client and in the two UIs that I tested (Azure Portal and Azure Storage Explorer) - both of which errored in an unhelpful way.

**Comment by navba-MSFT** [comment]
@cbailiss For the Azure portal feedback you can post it [here](https://feedback.azure.com/d365community/forum/79b1327d-d925-ec11-b6e6-000d3a4f06a4). For the Azure Storage Explorer you can post it [here](https://github.com/microsoft/AzureStorageExplorer/issues).

Regarding the Queue Storage SDK's feedback to improve the error message instead of showing the `Internal Error`, I am tagging @amnguye to check if this ask is feasible ?

**Comment by amnguye** [comment]
I believe it's an Azure SDK standard not to be altering these error messages.

As for the 500 (Internal Server Error) the OP is receiving, that's the error message given by the storage service. It's not something the SDK is producing on it's own.

If you're attempting to figure out server side issues or throttling please open an Azure Support ticket instead.
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This doesn't seem like an SDK issue, seeing there seems to be problems occurring across multiple Azure products

**Comment by navba-MSFT** [comment]
Thanks @amnguye .

As mentioned above the Internal Error thrown by the service can't be modified from SDK. Since the actual issue reported in this issue is resolved, we will proceed with the closure of this thread.
