### ISSUE TITLE
[Service Bus]  "The link with identifier Receiver|LinkName|ContainerId has been closed due to link stealing." exceptions in Azure Service Bus triggered function

### ISSUE THREAD

**Issue by niki33** [Azure/azure-sdk-for-net#37368]
### Library name and version

Azure.Messaging.ServiceBus 7.5.1

### Describe the bug

<img width="646" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/22556067/2ba61046-acd0-47c8-be66-9b7eda6cc281">

### Expected behavior

If we can not prevent it, it should not be logged as an exception.

### Actual behavior

Thousands of exceptions getting logged in a few hours.

### Reproduction Steps

1. Set up an Azure Service Bus triggered function.
2. Configure the function to receive messages from a Service Bus entity.
3. Trigger the function by sending messages to the Service Bus entity.
4. Monitor the function's execution and observe if any "The link with identifier Receiver|LinkName|ContainerId has been closed due to link stealing." exceptions occur.

### Environment

Target Framework - net6.0
AzureFunctionVeriosn - v4

**Comment by jsquire** [comment]
Hi @niki33.  Thank you for reaching out and we regret that you're experiencing difficulty.  The error that you're seeing is triggered by the Service Bus service and is not something that the client has knowledge of nor can influence.  In this case, that's not a message that we've seen before don't have insight into the cause.  To investigate that further, you would need to engage the Service Bus service team.  The best path for doing so would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

Please be aware that you are using a version of the `Azure.Messaging.ServiceBus` package that is more than 1.5 years old.  There have been a number of enhancements and fixes in that time, including changes to move errors that have been successfully retried to the Verbose designation for Azure Functions.  It is strongly recommended that you upgrade to the latest `Microsoft.Azure.WebJobs.Extensions.ServiceBus` package and `Azure.Messaging.ServiceBus`, if you're using the Service Bus package directly.

From the client perspective, any unknown service error that occurs and potentially impacts operation is intentionally logged.  Though the trigger is highly resilient and able to recover from most errors, unexpected service exceptions are potentially signs of a problem that needs to be investigated and are likely to have impact on throughput performance.  These are intentionally logged and will continue to be.  If desired, Service Bus logs can be filtered by adjusting Log Level configuration for the "Azure.Messaging.ServiceBus" source as discussed in [Logging with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/logging#logging-with-client-registration).
