### ISSUE TITLE
[QUERY] Monitor Exporter: Trace format inquiry

### ISSUE THREAD

**Issue by makinsc** [Azure/azure-sdk-for-net#37371]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter

### Query/Question

I was wondering why this library doesn't send the traces to application insight with the format of the opentelementry properties (TraceId and SpanId) and does it with operationId. SpanId and TraceId are entered as custom properties in the application log traces, but HTTP dependencies do not include them.
Any help will be very welcome.

### Environment

OD: Win10
NetCore7
running in localhost
VS2022 17.5.4
package version :  
Azure.Monitor.OpenTelemetry.Exporter" Version="1.0.0-beta.12"
"OpenTelemetry.Instrumentation.Http" Version="1.5.0-beta.1" />

**Comment by navba-MSFT** [comment]
@makinsc Thanks for reaching out to us and reporting this issue. The Azure Monitor OpenTelemetry Exporter library uses the OperationId property to correlate telemetry items across different services and components. This is because the OperationId is a unique identifier that is generated for each operation and is propagated across different services and components.

However, if you want to include the TraceId and SpanId properties in your telemetry data, you can do so by adding them as custom properties to your telemetry items. Here's an example of how to do this in C#:

```
using System.Diagnostics;
using Azure;
using Azure.Monitor.OpenTelemetry.Exporter;
using OpenTelemetry;
using OpenTelemetry.Trace;

// Create an OpenTelemetry tracer provider
var tracerProvider = Sdk.CreateTracerProviderBuilder()
    .AddSource("MyApplication")
    .SetResourceBuilder(ResourceBuilder.CreateDefault().AddService("MyService"))
    .AddAzureMonitorTraceExporter(options =>
    {
        options.ConnectionString = "InstrumentationKey=<your_instrumentation_key>";
    })
    .Build();

// Create a tracer
var tracer = tracerProvider.GetTracer("MyApplication");

// Start a new span
using (var span = tracer.StartActiveSpan("MyOperation"))
{
    // Add custom properties to the span
    span.SetAttribute("TraceId", Activity.Current.TraceId.ToString());
    span.SetAttribute("SpanId", Activity.Current.SpanId.ToString());

    // Do some work
    // ...
}
```
This will add the TraceId and SpanId properties to your telemetry data as custom properties. Note that this will not affect the correlation of your telemetry items, as the OperationId property is still used for correlation.

**Comment by makinsc** [comment]
Hi @navba-MSFT, thanks for your quick response. 
The logs of my application are already being included with TraceId and SpanId in the custom properties, but in the traces of the external HTTP dependencies they are not being included. When I see the HTTP dependency trace with the Console Exporter I see the TraceId and SpanId properties of the activities of the HTTP calls, but in Application insight they do not appear.
Attached file of the console output and AI output.
![Console](https://github.com/Azure/azure-sdk-for-net/assets/2463319/7615add1-6281-4294-8a4d-b591a14700ff)
![AI](https://github.com/Azure/azure-sdk-for-net/assets/2463319/e68ea3dd-1827-4cd3-8f54-1310e3aa604c)
Any help will be great
Thanks

**Comment by navba-MSFT** [comment]
@makinsc Thanks for getting back. While I looked at our docs, I could see this.

> OpenCensus Python enables you to correlate logs by adding a **trace ID, a span ID, and a sampling flag to log records.** You add these attributes by installing OpenCensus [logging integration](https://pypi.org/project/opencensus-ext-logging/). The following attributes are added to Python LogRecord objects: traceId, spanId, and traceSampled (applicable only for loggers that are created after the integration).

Refer: https://learn.microsoft.com/en-us/azure/azure-monitor/app/distributed-tracing-telemetry-correlation#log-correlation

**Comment by vishweshbankwar** [comment]
@makinsc In Application Insights, traceId is exported as `Operation Id` and spanId as `Id`. This is as per Application Insights schema. You should be able to see them on `Dependency` record.

**Comment by navba-MSFT** [comment]
@makinsc Hope this answers. 

Thanks @vishweshbankwar .
