### ISSUE TITLE
[BUG] ApiManagement.ApiManagementServiceResource.CreateOrUpdateContentTypeAsync(..) does not allow to define body

### ISSUE THREAD

**Issue by kpietralik** [Azure/azure-sdk-for-net#37392]
### Library name and version

Azure.ResourceManager.ApiManagement 1.0.1

### Describe the bug

The documentation of PUT Content Type defines body with item properties. SDK method only allows ContentTypeId to be defined:
https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/content-type/create-or-update?tabs=HTTP#request-body

### Expected behavior

ContentType can be created with all properties (schema, name, version, description).

### Actual behavior

ContentType can be created with only Id property

### Reproduction Steps

Construct an ApiManagementServiceResource using Azure resource values for subscription, resourcegroup and servicename, then perform the call:

`await apiManagementClient.CreateOrUpdateContentTypeAsync(contentTypeId, Azure.ETag.All);`

The method does not allow to provide properties described by REST API

### Environment

Windows 10
.NET 6.0 project
Visual Studio 2022 17.4.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
Hi @kpietralik ,this issue has been noted and fixed by the service team, and we will complete the fix in subsequent releases, thank you for your feedback
