### ISSUE TITLE
[QUESTION] Does SDK support to get AuthorizationCode for AuthorizationCodeCredential?

### ISSUE THREAD

**Issue by MartinM85** [Azure/azure-sdk-for-net#37410]
### Library name and version

Azure.Identity 1.9.0

### Query/Question

Does Azure SDK support to get [authorization code](https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow#request-an-authorization-code)?

There is a class AuthorizationCodeCredential that expects authorization code as one of the parameter in the constructor.

As a developer I would expect that Azure SDK contains some class or helper method that will create the request, handle the response and return the authorization code. Unfortunately I cannot find anything in the Azure SDK.

**Comment by christothes** [comment]
Hi @MartinM85 
`Azure.Identity` does not handle acquiring the code for you as it would be dependent on your specific application. `InteractiveBrowserCredential` will do everything for you end to end without needing a code, however.
