### ISSUE TITLE
Code is unformatted in Example

### ISSUE THREAD

**Issue by Forthoney** [Azure/azure-sdk-for-net#37415]
Code in the example section is not formatted as a code block

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e02c19ec-2424-6359-a4cd-ad061f2c3180
* Version Independent ID: 5421a6b4-8c29-2143-1df5-7bd90375437f
* Content: [CosmosClientOptions Class (Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.cosmos.cosmosclientoptions?view=azure-dotnet-preview)
* Content Source: [xml/Azure.Cosmos/CosmosClientOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Cosmos/CosmosClientOptions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Azure.Cosmos` package is maintained as [#3965](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3965).
