### ISSUE TITLE
[QUERY] Advice on package choice for DataFactory Management

### ISSUE THREAD

**Issue by 3mb2d** [Azure/azure-sdk-for-net#37411]
### Library name and version

Microsoft.Azure.Management.DataFactory 9.3.0 | Azure.ResourceManager.DataFactory 1.0.0-beta.2

### Query/Question

I've just looked on nuget to find a package to manage DataFactories and originally found Microsoft.Azure.Management.DataFactory 9.3.0 which has been listed as deprecated but the replacement package, Azure.ResourceManager.DataFactory seems to still be in beta. Was wondering if a stable release was iminent for the beta package or whether it would be better for stability to use the deprecated package?
Many thanks for any insight

### Environment

The codebase in question is in .Net 6 and uses other projects from the ResourceManager family

**Comment by mcgallan** [comment]
Hi @3mb2d, In September,  Microsoft.Azure.Management.DataFactory will be completely out of maintenance, it is recommended to use the current Azure.ResourceManager.DataFactory, if the beta version is missing the interface you need, you can open an issue - feature request for help
