### ISSUE TITLE
PrivateEndpointConnectionCreateAndUpdate failing Key Vault SDK tests

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#37421]
`PrivateEndpointConnectionCreateAndUpdate` is failing with,

> System.InvalidOperationException : Unable to find environment variable KEYVAULT_OBJECT_ID or OBJECT_ID required by test.
Make sure the test environment was initialized using the eng/common/TestResources/New-TestResources.ps1 script.

**Comment by heaths** [comment]
@m-nash after digging into this, I see that mgmt tests are now mixed in with our data plane tests. This wasn't running before June 13th, but now is and always failing. Who can take a look? And should this even be running with data plane live tests?

/cc @benbp

**Comment by heaths** [comment]
@ArthurMa1978, @m-nash and I discussed offline. I'll separate out the mgmt plane tests from DP (seems many other SDKs have) and changed this from `[Ignore]` to `[PlaybackOnly]`, but it might still be worth looking into this failure. At face value, it seems like just a missing env var in your mgmt test environment and still worth fixing, perhaps.

**Comment by m-nash** [comment]
@heaths agreed we should keep a tracking issue to fix live tests in general for mgmt plane.  There will be some edge cases that aren't possible due to some constraints, but we should be able to enable this for the vast majority of our tests.

**Comment by HarveyLink** [comment]
Since we have separated the tests and private endpoint's create only available in Network, we could close this issue. If there are more issues with same error, feel free to reopen it.
