### ISSUE TITLE
What is deprecated mean?

### ISSUE THREAD

**Issue by fmokren** [Azure/azure-sdk-for-net#37424]
I wish this content would explain in more detail what is meant by "deprecated". Is the package going away? What is the migration path from these deprecated assemblies to the non-deprecated assemblies?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9ab8d7f4-622f-0c12-1981-e3ec66c3884b
* Version Independent ID: f37d65ee-a93d-0344-7c30-f0a80be94ddf
* Content: [Cosmos DB (deprecated) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/cosmosdb/cosmosdb(deprecated)?view=azure-dotnet)
* Content Source: []()
* Git Login: **rloutlaw**
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.DocumentDB` family of packages is maintained as [#968](https://github.com/Azure/azure-cosmos-dotnet-v2/issues/968).
