### ISSUE TITLE
[Get supported orchestrators]

### ISSUE THREAD

**Issue by sujithq** [Azure/azure-sdk-for-net#37451]
### Library name

Azure.ResourceManager.ContainerService

### Please describe the feature.

I think we are missing the functionality for getting the supported orchestrators like we have in Azure CLI:

```
az aks get-versions -l westeurope
```

Preferred
``` C#
var credential = new DefaultAzureCredential();
var client = new ArmClient(credential);

var orchestrators = client.GetManagedClusterSupportedOrchestrators("westeurope");
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @sujithq, thank you for your feedback.
Unlike the Cli, the SDK does not have an operation to GetManagedClusterSupportedOrchestrators because it is based on the swagger spec that does not define it. Therefore, the SDK does not offer such an API like the Cli does.
