### ISSUE TITLE
MQ: Automate Azure Identity SDK Manual/Vendor Tests

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-net#37471]
We should leverage @christothes 's work on https://github.com/Azure/azure-sdk-for-net/pull/33017/files to fully automate the list of manual/vendor test scenarios which are documented in the issues here: https://github.com/Azure/azure-sdk/issues?q=is%3Aopen+is%3Aissue+label%3AAzure.Identity

This includes:

- [ ] Automate Azure Arc testing
- [x] Automate Azure Identity multi tenant testing
- [x] Automate Azure Workload Identity on Kubernetes testing
- [x] Automate Azure WebJobs testing
- [ ] Automate Azure Service Fabric testing
- [x] Automate Azure Functions testing
- [x] Automate VM MSI testing
- [ ] Automate Cloudshell testing

**Comment by christothes** [comment]
The remaining items in the description are not worth the ROI, so closing this out.
