### ISSUE TITLE
System.Reflection.AmbiguousMatchException

### ISSUE THREAD

**Issue by KoditkarVedant** [Azure/azure-sdk-for-net#3748]
```
System.Reflection.AmbiguousMatchException
Multiple custom attributes of the same type found.
```

**StackTrace**:
```

System.Attribute.GetCustomAttribute
Microsoft.Rest.ServiceClient`1.get_FrameworkVersion
Microsoft.Rest.ServiceClient`1.get_DefaultUserAgentInfoList
Microsoft.Rest.ServiceClient`1.SetUserAgent
Microsoft.Rest.ServiceClient`1.InitializeHttpClient
Microsoft.Azure.Management.Sql.Fluent.SqlManagementClient..ctor

```

I'm using Microsoft.Azure.Management.Sql.Fluent for do some operations on the database. My Code works just fine on my local evironment but when I deploy it on Azure it gives me above error..

**Comment by hovsepm** [comment]
@KoditkarVedant please reopen this issue [here](https://github.com/Azure/azure-libraries-for-net/issues). Fluent code has been moved to a dedicated repository. Thanks!

**Comment by milismsft** [comment]
@KoditkarVedant could you pass in a sample of your code ? Also, could you provide me with a bit more details on what "deploying to Azure" means? Do you get the error above while running on an Azure virtual machine/ container and if yes what kind of environment you use? 
Add all these to a new issue in the new repo to be opened [here](https://github.com/Azure/azure-libraries-for-net/issues)
