### ISSUE TITLE
Support parsing ARM resource ID without start with `/`

### ISSUE THREAD

**Issue by ArthurMa1978** [Azure/azure-sdk-for-net#37481]
Some services use arm ids that do not start with `/`, like [this](https://github.com/Azure/azure-rest-api-specs/issues/23704).
After discussion, we decided to modify the parsing logic in Azure.Core to accommodate this format.

**Comment by pallavit** [comment]
> After discussion, we decided to modify the parsing logic in Azure.Core to accommodate this format.

Do we have a follow-up bug for Azure.Core? This one has been filed under Mgmt so want to make sure we are tracking the work on that too? I am assuming you mean DP Azure.Core SDK will have the fix for this.

**Comment by live1206** [comment]
This will be fixed on the service side, the id format is inconsistent within costmanagement itself.

**Comment by live1206** [comment]
ICM created for this.

**Comment by live1206** [comment]
Got confirmation from cost management team, this issue will be fixed in the new API version.
The ETA of the new release is the end of this year, close this issue in SDK.
