### ISSUE TITLE
[QUERY] Azure.Security.KeyVault.Secrets : NameResolutionFailure

### ISSUE THREAD

**Issue by yuvnith** [Azure/azure-sdk-for-net#37491]
### Library name and version

Azure.Security.KeyVault.Secrets 4.2.0

### Query/Question

Our team is using Azure.Security.KeyVault.Secrets Lib v4.2.0 since 2021, to fetch KeyVaultSecret. It was working smoothly since then without any issues. 
We are suddenly getting NameResolutionFailure errors. This is an intermittent issue now.
```

var client = new SecretClient(new Uri(" xyz.net "), new ClientSecretCredential("xyz", ClientID, ClientSecret));
var Password = client.GetSecretAsync("CertificatePassword").GetAwaiter().GetResult();
```

I've been getting the NameResolutionFailure error frequently lately when running the above code snippet.
Can anyone please help me in pointing the root cause and a possible solution 

### Environment

 Windows 10 .NET Framework 4.8

**Comment by jsquire** [comment]
Hi @yuvnith.  Thank you for reaching out and we regret that you're experiencing difficulties.  The exception type, `NameResolutionFailure`, indicates that the .NET network stack was unable to resolve DNS for the service.  This is not something that is under the control of the KeyVault client library.  It needs to be investigated in the application host and its network environment.  Unfortunately, there is nothing that the Azure SDK team can do to assist with this.

**Comment by yuvnith** [comment]
Hi @jsquire thank you for the response
