### ISSUE TITLE
[BUG] Dependency conflict with Azure.Security.KeyVault.Secrets

### ISSUE THREAD

**Issue by mtanml** [Azure/azure-sdk-for-net#37525]
### Library name and version

Azure.Identity 1.9.0

### Describe the bug

Azure.Identity 1.9.0 requires Azure.Core >=1.32, but Azure.Security.KeyVault.Secrets 4.5.0 throws the following exception if Azure.Core 1.30 is not installed:

_Could not load file or assembly 'Azure.Core, Version=1.30.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'_

How can we resolve this?

### Expected behavior

No exceptions

### Actual behavior

Exception is thrown

### Reproduction Steps

Install Azure.Identity 1.9.0 with Azure.Security.KeyVault.Secrets 4.5.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
The following test application compiled and ran for me:

```C#
using Azure.Identity;
using Azure.Security.KeyVault.Secrets;

Uri vaultUri = new(args.Length > 0 ? args[0] : throw new Exception("Key Vault URI argument expected"));
DefaultAzureCredential credential = new();
SecretClient client = new(vaultUri, credential);

await foreach (SecretProperties properties in client.GetPropertiesOfSecretsAsync())
{
    Console.WriteLine(properties.Id);
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.9.0" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.5.0" />
  </ItemGroup>

</Project>
```

No public types were removed between Azure.Core 1.30.0 and 1.32.0, but cc @JoshLove-msft @christothes in case they are aware of anything.

Can you post the full stack trace of the exception? Do you have any binding redirects configured? Also, please run [fuslogvw](https://learn.microsoft.com/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) and capture any binding logs so we can diagnose further.

**Comment by mtanml** [comment]
Hi @heaths, thank you so much for your quick response!   The issue occurs in a Windows Service project on .NET Framework 4.6.2.  For whatever reason, it works fine in a WPF project on .NET Framework 4.6.2 using the same packages.   Since I'm troubleshooting a service, I'm not sure how to get fuslogvw to work.   

Here is the full stack trace:

System.IO.FileLoadException: Could not load file or assembly 'Azure.Core, Version=1.30.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)  File name: 'Azure.Core, Version=1.30.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'     at ResWareUtilityService.Repositories.TitleCompanionRepository.<RunDatabaseMaintenance>d__10.MoveNext()     at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)     at ResWareUtilityService.Repositories.TitleCompanionRepository.RunDatabaseMaintenance(ServiceProcess serviceProcess, List`1 azureDatabases)     at ResWareUtilityService.Repositories.ServiceProcessRepository.RunServiceProcess() in C:\Workspace\Utility Service\ResWareUtilityService\Repositories\ServiceProcessRepository.cs:line 449    === Pre-bind state information ===  LOG: DisplayName = Azure.Core, Version=1.30.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8  (Fully-specified)  LOG: Appbase = file:///C:/Program Files/TitleTech/Utility Service/  LOG: Initial PrivatePath = NULL  Calling assembly : Azure.Security.KeyVault.Secrets, Version=4.5.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8.  ===  LOG: This bind starts in default load context.  LOG: Using application configuration file: C:\Program Files\TitleTech\Utility Service\ResWareUtilityService.exe.Config  LOG: Using host configuration file:   LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.  LOG: Post-policy reference: Azure.Core, Version=1.30.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8  LOG: Attempting download of new URL file:///C:/Program Files/TitleTech/Utility Service/Azure.Core.DLL.  WRN: Comparing the assembly name resulted in the mismatch: Minor Version  ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by heaths** [comment]
I can reproduce this if I don't have a binding configuration for it - something needed for .NET Framework where strict binding was default. Your service EXE should have a corresponding .config file e.g., if your service EXE is named _myservice.exe_, then you need to have a _myservice.exe.config_ with binding redirects including, but not limited to,
```xml
      <dependentAssembly>
        <assemblyIdentity name="Azure.Core" publicKeyToken="92742159e12e44c8" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-1.32.0.0" newVersion="1.32.0.0" />
      </dependentAssembly>
```
See <https://learn.microsoft.com/dotnet/framework/deployment/configuring-assembly-binding-redirection> for more information.

You can also auto-generate them (see bottom of that page, basically you add `    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
` to your _.csproj_) but you need to make sure that _.config_ file gets deployed with your service executable. That's probably what's happening with the WPF application. Since you likely created it anew for this repro, it had that (newer projects should add it), but if your service is older, it may not have had that.

**Comment by mtanml** [comment]
Hi @heaths, thanks again so much... I have learned a lot today.   I added <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects> and got past that initial error, but now the service is getting hung up on the error below, even though this is in the config file:

      <dependentAssembly>
        <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.3.0" />
      </dependentAssembly>

System.TypeInitializationException: The type initializer for 'Azure.Core.ClientOptions' threw an exception. ---> System.BadImageFormatException: Could not load file or assembly 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Cannot load a reference assembly for execution.     --- End of inner exception stack trace ---     at Azure.Core.ClientOptions..ctor(ClientOptions clientOptions, DiagnosticsOptions diagnostics)     at Azure.Core.DefaultClientOptions..ctor()     at Azure.Core.ClientOptions..cctor()     --- End of inner exception stack trace ---     at Azure.Core.ClientOptions.get_Default()     at Azure.Identity.CredentialPipeline.<>c.<.cctor>b__16_0()     at System.Lazy`1.CreateValue()     at System.Lazy`1.LazyInitValue()     at System.Lazy`1.get_Value()     at Azure.Identity.CredentialPipeline.GetInstance(TokenCredentialOptions options)     at Azure.Identity.DefaultAzureCredential..ctor(Boolean includeInteractiveCredentials)     at ResWareUtilityService.Repositories.TitleCompanionRepository.<RunDatabaseMaintenance>d__10.MoveNext() in C:\Workspace\Utility Service\ResWareUtilityService\Repositories\TitleCompanionRepository.cs:line 620

**Comment by heaths** [comment]
Seems your deployment is including .NET Framework reference assemblies instead of runtime assemblies. This is more of a .NET issue, though I can try to help. How are you even installing your service? If via script or traditional installer like Windows Installer, Nullsoft, etc., make sure you are packaging runtime assemblies - assemblies from nuget's _lib_ directories and not _ref_ directories. In this specific case, it's the System.ValueTuple assembly, but I imagine if you get past that you'll find others if you grabbed a bunch of ref assemblies in your installer.

**Comment by mtanml** [comment]
Thank you so much Heath, I'll figure it out from here.   Really appreciate all of your help!




​
Marc Tanberg
Senior Software Developer, Mother Lode Holding Company
t: 877.958.8485    
e: ***@***.***
a: 9085 Foothills Blvd. | 
Roseville, CA  
95747

​

**Comment by tsahi** [comment]
> I can reproduce this if I don't have a binding configuration for it - something needed for .NET Framework where strict binding was default. Your service EXE should have a corresponding .config file e.g., if your service EXE is named _myservice.exe_, then you need to have a _myservice.exe.config_ with binding redirects including, but not limited to,
> 
> ```xml
>       <dependentAssembly>
>         <assemblyIdentity name="Azure.Core" publicKeyToken="92742159e12e44c8" culture="neutral" />
>         <bindingRedirect oldVersion="0.0.0.0-1.32.0.0" newVersion="1.32.0.0" />
>       </dependentAssembly>
> ```
For future reference, this worked for me also when using Azure.Identity 1.10, which requires Azure.Core >= 1.34.

**Comment by mtanml** [comment]
Hi @tsahi,

Thanks so much for your reply.   I added the dependent assembly to my app.config, using Azure.Identity 1.10, and I'm still getting this:

System.IO.FileLoadException: 'Could not load file or assembly 'Azure.Core, Version=1.30.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies

Thanks,

**Comment by heaths** [comment]
@mtanml you still need to update your `Azure.Core` to 1.30 or newer. The binding redirect just makes sure that anything that requests older gets the new version instead.

**Comment by mtanml** [comment]
@heaths @tsahi thanks so much to both of you for following up.   I converted my project to .NET 6, and the issues are gone  :)

**Comment by heaths** [comment]
.NET (formerly "Core") projects automatically generate bindings, unlike .NET Framework projects.
