### ISSUE TITLE
Enable RDP while creating a VM using resource manager sdk

### ISSUE THREAD

**Issue by satyajit-behera** [Azure/azure-sdk-for-net#37522]
### Library name and version

Azure.ResourceManager.Compute 1.1.0

### Query/Question

How do I enable RDP while creating a VM using resource manager sdk.? Do you have an example for the same.

I am using VirtualMachineCollection.CreateOrUpdateAsync(...);

Thanks in advance.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @satyajit-behera , Thank you for using Azure SDK for .NET.
If you would like to enable RDP for a VM, which means you have to enable 3389 port for it.
You'll need another package: [Azure.ResourceManager.Network](https://www.nuget.org/packages/Azure.ResourceManager.Network)
When create the network interface, including the NSG with 3389 inbound rule.
You could refer to the following sample:
https://github.com/Azure/azure-sdk-for-net/blob/5e882cdcb682b17c6d5d5867343931abbaf3a667/sdk/network/Azure.ResourceManager.Network/samples/Generated/Samples/Sample_NetworkSecurityGroupCollection.cs#L192
https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-rdp-nsg-problem#solution
