### ISSUE TITLE
[BUG] File Version Not Updated For `Microsoft.Rest.ClientRuntime`

### ISSUE THREAD

**Issue by ajorians** [Azure/azure-sdk-for-net#37530]
### Library name and version

Microsoft.Rest.ClientRuntime 2.3.24

### Describe the bug

In this PR's line: https://github.com/Azure/azure-sdk-for-net/pull/28169/files#diff-9b89241acf4c57c70a05219c00b631de104db571a0652b44944676866cd96dc9R6 the version number was updated to `2.3.24`:
https://github.com/Azure/azure-sdk-for-net/blob/962dc632e0873bfe39fb11d488bd69aaf89be4b1/sdk/mgmtcommon/ClientRuntime/ClientRuntime/Microsoft.Rest.ClientRuntime.csproj#L6

But the file version was not updated here:
https://github.com/Azure/azure-sdk-for-net/blob/962dc632e0873bfe39fb11d488bd69aaf89be4b1/sdk/mgmtcommon/ClientRuntime/ClientRuntime/Properties/AssemblyInfo.cs#L12

Making this the properties:
<image src="https://github.com/Azure/azure-sdk-for-net/assets/3475163/e698978f-b16e-4d55-8306-4648769534ef" width="50%" />

This matters because how desktop software MSI upgrades work.  It will only replace a file if the version number has changed.  And because it hasn't upon doing an installation upgrade the original version is in the installation directory instead of the upgrade that has the security fix:
![image](https://github.com/Azure/azure-sdk-for-net/assets/3475163/4152f1bc-e70c-478c-9594-cd7b851252fc)

We might have a couple of short-term workarounds:
1. We could utilize a probing path; and install that file into a subdirectory.  Upgrades then would have same file as a fresh install.
2. I think it is possible to change your binaries file's version with a tool like `rcedit` (we won't because that probably violates license agreements).

### Expected behavior

The file version number matches the product version.  Basically update this line: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/mgmtcommon/ClientRuntime/ClientRuntime/Properties/AssemblyInfo.cs#L12

### Actual behavior

File version didn't get updated causing desktop upgrade to not update the file.  Which means security vulnerability that was fixed won't be picked up without a workaround.

### Reproduction Steps

Not easy to make reproduction steps; but holler if additional information is needed.

### Environment

I am using Visual Studio LTSC 17.4; but this isn't related to my environment.  Hope that helps!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
Also reported in:  #37687   _(closed as a duplicate)_

**Comment by ArthurMa1978** [comment]
Hi @ajorians , this package is an outdated management SDK that will no longer be supported after September. We recommend that you switch to our [new Track 2 SDK](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resourcemanager-readme?view=azure-dotnet) as soon as possible. You can find the [instructions](https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager_1.7.0/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md) for migrating to the new SDK here.

**Comment by ajorians** [comment]
> Hi @ajorians , this package is an outdated management SDK that will no longer be supported after September. We recommend that you switch to our [new Track 2 SDK](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resourcemanager-readme?view=azure-dotnet) as soon as possible. You can find the [instructions](https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager_1.7.0/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md) for migrating to the new SDK here.

Hi @ArthurMa1978 ,

Thanks for the information.  I wasn't aware but am now; and will discuss the transition with my team.  Thanks again :smiley:
