### ISSUE TITLE
Cannot build AzureStack Gallery Admin Client

### ISSUE THREAD

**Issue by deathly809** [Azure/azure-sdk-for-net#3756]
I am working on the AzureStack Gallery admin C# SDK and because of the way the ignore rules work anything with the word Gallery in it is ignored.  

I suggest a whitelist.

**Comment by shahabhijeet** [comment]
@deathly809 I will have a fix out for this soon. Sorry for the delay in triaging this issue.

**Comment by shahabhijeet** [comment]
This does not repros. You shuold be able to build without any issues.
If you still see the issue, reopen this issue and can you provide me a repro.
