### ISSUE TITLE
Getting ManagedIdentityCredential authentication failed: Service request failed. Status: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by swatirashmims** [Azure/azure-sdk-for-net#37635]
### Library name and version

Azure.Identity 1.8.1

### Query/Question

I am trying to call my webapp from Azure function using timer trigger, for which I am using DefaultAzureCredential. I have already enabled a system assigned managed identity for function app. The code for getting the token:

                TokenCredential azureCredential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { 
                           ManagedIdentityClientId = "<managed-identity-object(principal)-id" });
                var token = azureCredential.GetToken(new TokenRequestContext(new[] { "<scope>" }), CancellationToken.None);
                var result = await this.httpClientHelper.GetAsync("<api-url>", token.Token, null).ConfigureAwait(false);

This is the error which I am getting
ManagedIdentityCredential authentication failed: Service request failed.
Status: 500 (Internal Server Error)

Content:

Headers:
Date: Fri, 14 Jul 2023 00:25:08 GMT
Server: Kestrel
Transfer-Encoding: chunked
X-CORRELATION-ID: REDACTED
Content-Type: application/json; charset=utf-8

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot

The above code is working on my local with VisualStudioCredential. This error is not enough for me to debug the issue. Any kind of help is appreciated.

Edit: I have also added the client id as an environment variable. Does the web app need any extra settings?
### Environment

net 6.0
AzureFunctionsVersion - v4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by swatirashmims** [comment]
No, it does not. I have tried removing it from the code and adding AZURE_CLIENT_ID in the configuration for the function app. None of them works.

**Comment by christothes** [comment]
Please try removing AZURE_CLIENT_ID also as a test.

**Comment by christothes** [comment]
A permissions issue shouldn't result in a 500 error from the credential. 
Would you mind providing the logging output after reproducing this with [logging enabled](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md)?

**Comment by christothes** [comment]
Also, could you validate that this reproduces on the latest version of Azure.Identity?
