### ISSUE TITLE
[FEATURE REQ] Add Queue Permissions enum to represent `QueueAccessPolicy.Permissions`

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#37653]
### Library name

Azure.Storage.Queues

### Please describe the feature.

Add Queue Permissions enum to represent `string QueueAccessPolicy.Permissions`.

This is mainly used for `QueueClient.SetAccessPolicy` and `QueueClient.GetAccessPolicy`.

Can be similar to `QueueSasPermissions` where each permission has a bit.

We can't remove the current way that users are passing the permissions, e.g. `string QueueAccessPolicy.Permissions` because that'd be a breaking change. So we need to name it to something else.

**Comment by nickliu-msft** [comment]
This has been resolved via this PR: [#45234](https://github.com/Azure/azure-sdk-for-net/pull/45234)
