### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Issac-Nguyen** [Azure/azure-sdk-for-net#37687]
### Library name and version

Microsoft.Rest.ClientRuntime version 2.3.24

### Describe the bug

I installed version 2.3.24 but when I check the build in artifact the product version is 2.3.24 but file version is 2.3.23.

### Expected behavior

product version same with file version

### Actual behavior

I installed version 2.3.24 but when I check the build in artifact the product version is 2.3.24 but file version is 2.3.23.

### Reproduction Steps

install via nuget package

### Environment

.net core 3.1

**Comment by jsquire** [comment]
This is tracked in #37530.   Closing this issue out as a duplicate.
