### ISSUE TITLE
CloudException: Internal Server Error when Using ListMetricsAsync Method

### ISSUE THREAD

**Issue by AMoghrabi** [Azure/azure-sdk-for-net#3769]
I'm using `Microsoft.Azure.Management.AppService.Fluent` to collect information about my App Service Plans. The method I'm using is [ListMetricsAsync.](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.appservice.fluent.appserviceplansoperationsextensions.listmetricsasync?view=azure-dotnet#Microsoft_Azure_Management_AppService_Fluent_AppServicePlansOperationsExtensions_ListMetricsAsync_Microsoft_Azure_Management_AppService_Fluent_IAppServicePlansOperations_System_String_System_String_System_Nullable_System_Boolean__System_String_System_Threading_CancellationToken_)

My first problem is, the documentation says that the `filter` argument is optional. This is incorrect as the underlying web API throws an exception:

> Microsoft.Rest.Azure.CloudException : Operation returned an invalid status code 'BadRequest'
> Inner Exception: <Error xmlns:i=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"http://schemas.microsoft.com/windowsazure\"><Code>InvalidFilterValueParameter</Code><Message>Argument Null\r\nParameter name: $filter</Message></Error>

I've tried supplying an empty string but that does not work. 

It looks like I must supply a filter so I try that... However, supplying a filter seems to return `Microsoft.Rest.Azure.CloudException : Operation returned an invalid status code 'InternalServerError'`
Here is my code:

```c#
    var appServiceManager = AppServiceManager.Authenticate(credentials, subscriptionId);
    var filter = "(name.value eq 'CpuPercentage') and aggregationType eq 'Average' and timeGrain eq duration'PT1H' and startTime eq 2017-10-06T19:00:00Z and endTime eq 2017-10-06T20:00:00Z";
    var metrics = appServiceManager.AppServicePlans.Inner.ListMetricsAsync("MyResourceGroupName", "MyAppServiceName", null, filter).Result;
```

I assume that my filter has incorrect syntax. Can you please advise what I need to do to get this working?

Thanks!

**Comment by hovsepm** [comment]
@shahabhijeet this is not Fluent specific. @AMoghrabi was using Inner to make a call which means that it was auto generated code. This needs to be investigated with the AppService team.

**Comment by AMoghrabi** [comment]
Is there a different way to access that method without using inner?

**Comment by AMoghrabi** [comment]
Also, should I open my issue on a different repository?

**Comment by ttugates** [comment]
I am experiencing the same issue.  Any update?

**Comment by AMoghrabi** [comment]
Hey

Check out my SO post about this -- someone replied with a decent solution:

https://stackoverflow.com/questions/46639014/azure-fluent-api-appserviceplanoperations-listmetricswithhttpmessagesasync-ret

**Comment by ttugates** [comment]
@AMoghrabi  - Thank you!

**Comment by AMoghrabi** [comment]
You're welcome! Good luck. ☺️
