### ISSUE TITLE
Azure Data Lake Store SDK : FileStatusProperties.ChildrenNum Property always null

### ISSUE THREAD

**Issue by RudyCo** [Azure/azure-sdk-for-net#3770]
See on SOF : https://stackoverflow.com/questions/46608473/azure-data-lake-store-sdk-filestatusproperties-childrennum-property-always-nul/

**Comment by shahabhijeet** [comment]
@ro-joowan can you take a look at this issue.

**Comment by ro-joowan** [comment]
@RudyCo Thanks for noting this. 

1.  A member of my team noted that "GetContentSummary will give you the count for the whole recursive tree, not just the current directory."

2.  Did you try something like this?

// List all the contents in the folder
var listFolderResponse = commonData.DataLakeStoreFileSystemClient.FileSystem.ListFileStatus(
                                          commonData.DataLakeStoreFileSystemAccountName,
                                          folderPath);

// We know that this directory is brand new, so the contents should only be the one file.
var count = listFolderResponse.FileStatuses.FileStatus.Count);

**Comment by ro-joowan** [comment]
This has been addressed in this PR: https://github.com/Azure/azure-sdk-for-net/pull/4046
