### ISSUE TITLE
[QUERY] Upgrading to v12 client - need client-side ingress/egress logging in v9 library

### ISSUE THREAD

**Issue by ayeltsov** [Azure/azure-sdk-for-net#37716]
### Library name and version

WindowsAzure.Storage 9.3.3

### Query/Question

I realize I'm asking about ancient library, but please bear with me.

We (SQL) have a fine-tuned app that is running on WindowsAzure.Storage 9.3.3, and we want to upgrade it to Azure.Storage.Blobs 12.x. 
With 1M executions per day, we push about 4.5PB daily across our storage accounts. 

When we tried to update the app to later SDK, app started experiencing throttling, and we had to roll back. 

I could not figure out the access pattern change that caused throttling. So I want to retrofit the WindowsAzure.Storage 9.3.3 version to log client side ingress/egress/requests per each account it's hitting to compare patterns.

With v12, I think I can get to what I need with AzureEventSourceListener - it gives me requests with their targets and content-length. 

With v9, there's OperationContext.GlobalRequestCompleted (and OperationContext.GlobalResponseReceived), but they do not have byte counts. 

Anyone has enough history to advise how I can get byte counts per target for v9?

**Comment by jaschrep-msft** [comment]
Both old and new libraries support `IProgress<T>` on their transfers for progress reporting. You can use this to track content body bytes written/read.

**Comment by navba-MSFT** [comment]
@ayeltsov Thanks for reaching out to us and reporting this issue. I hope you had a chance to look at the above suggestion. Please let us know if you have any follow-up questions.
