### ISSUE TITLE
[QUERY] Role needed for billing data using ConsumptionExtensions.GetConsumptionUsageDetails

### ISSUE THREAD

**Issue by boomer84** [Azure/azure-sdk-for-net#37720]
### Library name and version

Azure.ResourceManager.Consumption

### Query/Question

I am using ConsumptionExtensions.GetConsumptionUsageDetails(ArmClient, ResourceIdentifier) to get the CostInBIllingCurrency detail.

When I am querying a subscription with which I have Owner/Contributor then I get the full results and all the relevant billing data

However, when I use an account that has Billing Reader access I get all the resources back for each day including the unit price, UnitOfMeasure and quantity but I do not get the cost in billing currency

Access is through lighthouse.

**Comment by jsquire** [comment]
Hi @boomer84.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, the behavior that you're asking about is that of the service itself.  The Azure SDK library does not evaluate permissions nor interpret the results of a query - it just passes through what the service returned.   The Azure SDK team that monitors this repository is unable to assist.  Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to engage the service team that would be able to help.

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
