### ISSUE TITLE
[BUG] BlockBlobclient.UploadAsync throws when options is null

### ISSUE THREAD

**Issue by thomas-hammond** [Azure/azure-sdk-for-net#37752]
### Library name and version

Azure.Storage.Blobs

### Describe the bug

The documentation for BlockBlobClient.UploadAsync says that the options parameter is "optional" parameters. And the code seems to use 'options?' so it can be passed in as null. However, there is an access to 'options.ProgressHandler' that causes it to throw a NullReferenceException.

### Expected behavior

We would expect the code to handle options being null since using that overload is required if you are passing in a CancellationToken.

### Actual behavior

Throws a NullReferenceException.

### Reproduction Steps

Pass options as null.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.
