### ISSUE TITLE
[OpenAI] Introduce `KeyCredential` as a base class of `AzureKeyCredential`

### ISSUE THREAD

**Issue by joseharriaga** [Azure/azure-sdk-for-net#37755]
The OpenAI library can interact with the Azure OpenAI service and the regular, non-Azure OpenAI service:

* Azure OpenAI has a *custom endpoint host* based on how you named your resource when you created it through ARM (e.g. "https://myAwesomeResource.openai.azure.com/*") and uses *either an API key or AAD for auth*.
* Non-Azure OpenAI has a *fixed endpoint host* ("https://api.openai.com/v1/*") and uses *an API key for auth*.

The user can specify which service they want to interact with by a using a different client constructor:

1. `public OpenAIClient(Uri endpoint, AzureKeyCredential keyCredential, OpenAIClientOptions options)`
2. `public OpenAIClient(Uri endpoint, TokenCredential tokenCredential, OpenAIClientOptions options)`
3. `public OpenAIClient(string openAIApiKey, OpenAIClientOptions options)`

\# 1 and  \# 2 connect to Azure OpenAI. \# 3 connects to non-Azure OpenAI. 

We don't like that \# 3 uses a plain string; we want to use a proper "credential" object. We can technically use an `AzureKeyCredential`, but the name of the class makes things unintuitive: The user is trying to connect to the non-Azure OpenAI service, but we're asking for an "AzureKeyCredential", which sounds like they need to go grab the API key from Azure somehow.

The solution that was agreed upon with the Architecture Board is to create a new `KeyCredential` class in Azure.Core. We can move all the logic of `AzureKeyCredential` over there, and then simply make `AzureKeyCredential` inherit from it. Thus, all our existing libraries would remain unaffected, but the OpenAI client class would now be able to have the following constructor instead:

 3. `public OpenAIClient(KeyCredential keyCredential, OpenAIClientOptions options)`

For reference, this is Java's implementation of `KeyCredential`:
🔗 https://github.com/Azure/azure-sdk-for-java/pull/35364

**Comment by annelo-msft** [comment]
@joseharriaga, is this satisfied by the new types in `System.ClientModel`?

**Comment by joseharriaga** [comment]
@annelo-msft, Yes! I will close this issue. Thank you!
