### ISSUE TITLE
[Core] Resolve Azure.Core AOT warnings impacting the AOT compatibility of Azure.Monitor.OpenTelemetry.Exporter

### ISSUE THREAD

**Issue by m-redding** [Azure/azure-sdk-for-net#37761]
### Library name

Azure.Core

### Please describe the feature.

This issue is tracking the work needed to resolve https://github.com/Azure/azure-sdk-for-net/issues/35572

- [x] Upgrade `System.Diagnostics.DiagnosticSource` to 6.0.1
    - https://github.com/Azure/azure-sdk-for-net/pull/37600
    - https://github.com/Azure/azure-sdk-for-net/pull/37597
    - https://github.com/Azure/azure-sdk-for-net/pull/37418
- [x] Remove reflection code for all non netcoreapp2.1 targets
    - https://github.com/Azure/azure-sdk-for-net/pull/37661
- [x] Disable tracing for netcoreapp2.1 and remove reflection code entirely
    - https://github.com/Azure/azure-sdk-for-net/pull/37763
- [x] Add attributes to various classes to resolve warnings
    - https://github.com/Azure/azure-sdk-for-net/pull/37734
- [x] Consider moving `RequestFailedException` to use source generation for deserialization.
- [x] https://github.com/Azure/azure-sdk-for-net/issues/37733 - adding this work to the PR
- [x] Investigate how to resolve warnings from DynamicData.Equals() and MutableJsonElement.ToString(). They cannot have the "RequiresUnreferencedCode" attribute because the attribute must exist on the method being overridden
   - [x] Marked relevant classes as `RequiresUnreferencedCode`
   - [x] Opened issue since `RequiresUnreferencedCode` cannot be applied to structs - currently no workaround
- [ ] https://github.com/Azure/azure-sdk-for-net/issues/38225
- [x] https://github.com/Azure/azure-sdk-for-net/issues/38226

**Comment by JeyJeyGao** [comment]
Hello @m-redding , looks like there is still a trim warning for Azure.Core when build with AOT enabled. 

Warnings:
```
/home/jj/.nuget/packages/azure.core/1.36.0/lib/net6.0/Azure.Core.dll : warning IL2104: Assembly 'Azure.Core' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [/home/jj/projects/junjie/notation-azure-kv/Notation.Plugin.AzureKeyVault/Notation.Plugin.AzureKeyVault.csproj]
/home/jj/.nuget/packages/azure.security.keyvault.keys/4.6.0-beta.2/lib/netstandard2.0/Azure.Security.KeyVault.Keys.dll : warning IL2104: Assembly 'Azure.Security.KeyVault.Keys' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [/home/jj/projects/junjie/notation-azure-kv/Notation.Plugin.AzureKeyVault/Notation.Plugin.AzureKeyVault.csproj]
```

Could you tell me have how to fix it? Dotnet 8 stable version was released and we are going to bump up to Dotnet 8 with AOT enabled.

**Comment by m-redding** [comment]
Hi @JeyJeyGao would it be possible for you to share the list of specific warnings you are seeing? There are a few warnings we have baselined in tests - namely ones surrounding DynamicData and MutableJsonDocument, but unless you're using those types somewhere in your code you shouldn't be seeing any warnings.

**Comment by m-redding** [comment]
Hey @JeyJeyGao I have been looking into this and I wanted to ask how you were testing this? Are you using a  \<TrimmerRootAssembly\> tag? If not, then I'm 90% sure this is an issue with keyvault not having a net6.0 target. The hope was to avoid adding one since the warnings are coming from code not on the path (when there is a TrimmerRootAssembly tag the trimmer is VERY generous with what it considers part of the assembly).

**Comment by m-redding** [comment]
There are a couple other warnings that need to be fixed which I will take care of.
