### ISSUE TITLE
[BUG] ResourceManager.Compute:  New service version causing error in existing code

### ISSUE THREAD

**Issue by chborl** [Azure/azure-sdk-for-net#37760]
### Library name and version

Azure.ResourceManager.Compute 1.1.0

### Describe the bug

The exact same code that worked in Azure.ResourceManager.Compute 1.0.1 gives an error in 1.1.0.  

Has the format for doing this changed the newer version? 

### Expected behavior

No error, since it worked in 1.0.1

### Actual behavior

This error:  
"The gallery artifact version source can only be specified either directly under storageProfile or within individual OS or data disks"

### Reproduction Steps

```csharp   
            var imageVersionData = new GalleryImageVersionData(new AzureLocation(galleryResourceGroupWithRegion.Region))
            {
                PublishingProfile = galleryImageVersionPublishingProfile,
                StorageProfile = new GalleryImageVersionStorageProfile()
                {
                    Source = new GalleryArtifactVersionSource()
                    {
                        Id = new ResourceIdentifier(replicationSourceResourceId),
                    }
                }
            };
            var imageVersion = await imageVersionsCollection.CreateOrUpdateAsync(WaitUntil.Started, imageVersionName, imageVersionData);
```

**Comment by ArthurMa1978** [comment]
This is a behavior change from service backend, loop service team for help.

**Comment by sandeepraichura** [comment]
@chborl - We are looking into it, will keep you posted on the status.

**Comment by sandeepraichura** [comment]
Apologies for the delay @chborl, we are still looking into it.

**Comment by Sandido** [comment]
@chborl , does this issue still reproduce? Can you provide the input gallery ARM Id that shows this issue?

**Comment by chborl** [comment]
Yes it does still repro. It repro'd today with package 1.0.3, but it runs fine with package 1.0.1.

We are creating the image from a VM. Do you want the ResourceId of that VM?

**Comment by apilosofms** [comment]
To clarify Cheryl's comment above: There was a typo; she means 1.3.0, not 1.0.3. It still reprod in 1.3.0.

**Comment by KshitijAgrawal** [comment]
Hey,

You need to modify your existing code to use GallerySource property under storageProfile instead of Source.

From

StorageProfile = new GalleryImageVersionStorageProfile()
                {
                    Source = new GalleryArtifactVersionSource()
                    {
                        Id = new ResourceIdentifier("source"),
                    }
                }

To

          {
                **GallerySource = new GalleryArtifactVersionFullSource()**
                {
                    Id = new ResourceIdentifier("source"),
                }
            },

**Comment by chborl** [comment]
Hi Kshitij,

Just checking... will we run into any problems if an image is created with the V1.0.1 sdk using our older code, and later is updated using the following code from the newer version sdk

var patch = new GalleryImageVersionPatch()
{
                PublishingProfile = publishingProfile
};

var updateVersionResult = await imageVersion.UpdateAsync(WaitUntil.Started, patch);

Thanks,
Cheryl

**Comment by chborl** [comment]
We have made the changes recommended above and updated to the latest build. All is working great now.

**Comment by sandeepraichura** [comment]
thanks for the confirmation, we will close this out. Please reopen if needed.
