### ISSUE TITLE
Unable to update Service Principals using Azure.ResourceManager.Models types

### ISSUE THREAD

**Issue by xximjasonxx** [Azure/azure-sdk-for-net#37781]
### Library name and version

Azure.ResourceManager.Authorization v1.0.1

### Describe the bug

I am trying to write a block that will allow me to assign a Service Principal to a specific role in Azure. This seems to work more consistently with Groups but still fails even there.

The code is such:
```chsarp
        var tcs = new TaskCompletionSource();
        Task.Run(() =>
        {
            try
            {
                var roleAssignmentResourceId = RoleAssignmentResource.CreateResourceIdentifier(assignPath, roleDefinitionId);
                var roleAssignmentResource = _armClient.GetRoleAssignmentResource(roleAssignmentResourceId);
                var operationContent = new RoleAssignmentCreateOrUpdateContent(roleAssignmentResource.Id, groupId)
                {
                    PrincipalType = RoleManagementPrincipalType.Group
                };

                var operationOutcome = roleAssignmentResource.Update(Azure.WaitUntil.Completed, operationContent);
                tcs.TrySetResult();
            }
            catch (Exception ex)
            {
                tcs.TrySetException(ex);
            }
        });

        return tcs.Task;
```

When this code is run, it will, almost always, fails with the following exception:
{"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\r\nStatus: 400 (Bad Request)\r\nErrorCode: RoleAssignmentUpdateNotPermitted\r\n\r\nContent:\r\n{\"error\":{\"code\":\"RoleAssignmentUpdateNotPermitted\",\"message\":\"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\"}}

### Expected behavior

I would expect the code to make the role assignment and ignore irrelevant fields

### Actual behavior

This fails pretty consistently with Service Prinicpals and sometimes with Group principles

### Reproduction Steps

Use the code above. Create any type of SPN, execute

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
This is a behavior change from service backend, loop service team for help.

**Comment by mcgallan** [comment]
Hi @xximjasonxx , I want to know if the parameter groupId in RoleAssignmentCreateOrUpdateContent() is principalId

**Comment by HarveyLink** [comment]
Here is a sample of assign permission, may it be helpful to you.
```
    // Assign permission
    var roleCollection = umi.GetRoleAssignments();
    var roleData = new RoleAssignmentCreateOrUpdateContent(
        new ResourceIdentifier("/subscriptions/<subid>/providers/Microsoft.Authorization/roleDefinitions/<roleid>"),
        (Guid)umi.Data.PrincipalId
        );
    var assign = (await roleCollection.CreateOrUpdateAsync(WaitUntil.Completed, Guid.NewGuid().ToString(), roleData)).Value;
```
