### ISSUE TITLE
[QUERY] ChatCompletionAsync Timeout / Internal server error

### ISSUE THREAD

**Issue by fatihyildizhan** [Azure/azure-sdk-for-net#37793]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.6

### Query/Question

Hi, ChatCompletionAsync waits for minutes without answering. 

The frequency increased with Azure Studio ChatGPT-35-turbo 0613 16K. 

Could we give `Timeout` to OpenAIClient init?

Sometimes, it gives "internal server error" after a few minutes.

**Comment by navba-MSFT** [comment]
@fatihyildizhan Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@fatihyildizhan You can use the workaround for now by using a custom policy to set a timeout on all requests as shown below.

You can use the below constructor:

<html>
<body>


OpenAIClient(Uri, TokenCredential, OpenAIClientOptions) | Initializes a instance of OpenAIClient for use with an Azure OpenAI resource.
-- | --



</body>
</html>

And use the [AddPolicy(HttpPipelinePolicy, HttpPipelinePosition) ](https://learn.microsoft.com/en-us/dotnet/api/azure.core.clientoptions.addpolicy?view=azure-dotnet-preview#azure-core-clientoptions-addpolicy(azure-core-pipeline-httppipelinepolicy-azure-core-httppipelineposition))Method of the **_OpenAIClientOptions Class_**.

Note: The below sample is for the **sdk for js**. You can tweak it for sdk for net.

```
this.openai = new OpenAIClient(process.env.AZURE_OPENAI_URL, new AzureKeyCredential(process.env.AZURE_API_KEY), {
            apiVersion: process.env.AZURE_DEPLOYMENT_VERSION,
            retryOptions: {
                maxRetries: 3
            },
          additionalPolicies: [
              {
                policy: {
                  name: "customTimeoutPolicy",
                  sendRequest(request, next) {
                    // example that sets a timeout of 10 seconds
                    request.timeout = 10 * 1000;
                    return next(request);
                  },
                },
                position: "perCall",
              }
            ]
        });
```
Hope this helps.

**Comment by fatihyildizhan** [comment]
Thanks a lot.

**Comment by navba-MSFT** [comment]
@fatihyildizhan Thanks for getting back. We will now proceed with closure of this GitHub issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
