### ISSUE TITLE
[BUG] Postgres Flexible server Create fails with invalid version exception.

### ISSUE THREAD

**Issue by subbarayudukamma** [Azure/azure-sdk-for-net#37792]
### Library name and version

Azure.ResourceManager.PostgreSql.FlexibleServers 1.1.1

### Describe the bug

I tried to create a PG server with the below code and got the RequestFailedException on CreateOrUpdateAsync call.

---- Code sample ------
ArmClient armClient = new ArmClient(new DefaultAzureCredential());
var subscription = await armClient.GetSubscriptions().GetAsync("aaaa");

var rg = await subscription.Value.GetResourceGroupAsync("Geoservers-EastUS");

PostgreSqlFlexibleServerData newServer = new PostgreSqlFlexibleServerData(AzureLocation.EastUS2)
{
    AdministratorLogin = "mdp_admin",
    AdministratorLoginPassword = "aaa",
    CreateMode = PostgreSqlFlexibleServerCreateMode.Create,
    Version = PostgreSqlFlexibleServerVersion.Ver14,
    Sku = new PostgreSqlFlexibleServerSku("Standard_D2ds_v4", PostgreSqlFlexibleServerSkuTier.GeneralPurpose),
};
PostgreSqlFlexibleServerCollection postgreSqlFlexibleServerResources = rg.Value.GetPostgreSqlFlexibleServers();
var r = await postgreSqlFlexibleServerResources.CreateOrUpdateAsync(Azure.WaitUntil.Completed, "new-flex-s-2-sk", newServer);

------------------------------------
Exception details :
----------------------------------------

Azure.RequestFailedException: 'The value of the 'Version' should be in: []. Verify that the specified parameter value is correct.
Status: 400 (Bad Request)
ErrorCode: ParameterOutOfRange

Content:
{"error":{"code":"ParameterOutOfRange","message":"The value of the 'Version' should be in: []. Verify that the specified parameter value is correct."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
X-Content-Type-Options: REDACTED
x-ms-request-id: c347f1ab-3add-42ab-8127-8220ea7c6562
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
Date: Sat, 22 Jul 2023 16:39:17 GMT
Content-Length: 151
Content-Type: application/json; charset=utf-8
Expires: -1
'

### Expected behavior

The exception should not have happened since I was passing a valid version to PGFlexServerData.
Even if that happens, it should tell the possible values. 

### Actual behavior

The possible values are empty in the exception message.

### Reproduction Steps

---- Code sample ------
ArmClient armClient = new ArmClient(new DefaultAzureCredential());
var subscription = await armClient.GetSubscriptions().GetAsync("aaaa");

var rg = await subscription.Value.GetResourceGroupAsync("Geoservers-EastUS");

PostgreSqlFlexibleServerData newServer = new PostgreSqlFlexibleServerData(AzureLocation.EastUS2)
{
    AdministratorLogin = "mdp_admin",
    AdministratorLoginPassword = "aaa",
    CreateMode = PostgreSqlFlexibleServerCreateMode.Create,
    Version = PostgreSqlFlexibleServerVersion.Ver14,
    Sku = new PostgreSqlFlexibleServerSku("Standard_D2ds_v4", PostgreSqlFlexibleServerSkuTier.GeneralPurpose),
};
PostgreSqlFlexibleServerCollection postgreSqlFlexibleServerResources = rg.Value.GetPostgreSqlFlexibleServers();
var r = await postgreSqlFlexibleServerResources.CreateOrUpdateAsync(Azure.WaitUntil.Completed, "new-flex-s-2-sk", newServer);

### Environment

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.9.0" />
    <PackageReference Include="Azure.ResourceManager" Version="1.7.0" />
    <PackageReference Include="Azure.ResourceManager.PostgreSql" Version="1.1.1" />
  </ItemGroup>

</Project>

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
Hi @subbarayudukamma , I tried to reproduce the bug using the following PostgreSqlFlexibleServerData property, but it was successful, and if you can, you can try using the latest package to circumvent the problem
![image](https://github.com/Azure/azure-sdk-for-net/assets/88413158/15b05053-6f74-49ac-8e0e-692017c3bc84)
