### ISSUE TITLE
[BUG]ResourceIdentifier allows whitespace?!

### ISSUE THREAD

**Issue by sebader** [Azure/azure-sdk-for-net#37801]
### Library name and version

Azure.Core 1.32.0

### Describe the bug

I'm using `ResourceIdentifier.TryParse()` to validate user input of a resource ID. Just noticed that this accepts resource IDs with whitespace in them. I believe this is a bug since those are not valid IDs?!

Samples which are not being caught by the validation:
```
"/subscriptions/7ddfffd7-9b32-40df-b352-828cbd55d6f4/resourceGroups/group-with spaces/providers/Microsoft.Network/publicIpAddresses/public-ip-nerd"

"/subscriptions/ 7ddfffd7-9b32-40df-b352-828cbd55d6f4/resourceGroups/group/providers/Microsoft.Network/publicIpAddresses/public-ip-nerd"

"/subscriptions/7ddfffd7-9b32-40df-b352-828cbd55d6f4/resourceGroups/groupwith\nnewline/providers/Microsoft.Network/publicIpAddresses/public-ip-nerd"
```

Was added in
https://github.com/Azure/azure-sdk-for-net/pull/32039 by @m-nash 

### Expected behavior

Resource IDs with spaces anywhere in them should not pass validation.

### Actual behavior

See above

### Reproduction Steps

```
ResourceIdentifier.TryParse("/subscriptions/7ddfffd7-9b32-40df-b352-828cbd55d6f4/resourceGroups/group-with spaces/providers/Microsoft.Network/publicIpAddresses/public-ip-nerd", out var _);
```

### Environment

dotnet 7

**Comment by jsquire** [comment]
//cc: @m-nash

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
No real case has been reported for this bug, so it’s not urgent. Put it on the backlog with low priority.

**Comment by sebader** [comment]
> No real case has been reported for this bug, so it’s not urgent. Put it on the backlog with low priority.

I am reporting a real case here ;)

**Comment by ArthurMa1978** [comment]
> > No real case has been reported for this bug, so it’s not urgent. Put it on the backlog with low priority.
> 
> I am reporting a real case here ;)

I meant service return an arm-id like this, but anyway this is definitely a bug, @live1206 will follow up with this issue.
