### ISSUE TITLE
[FEATURE REQ] Support for CosmosClient in AddAzureClients

### ISSUE THREAD

**Issue by Ponant** [Azure/azure-sdk-for-net#37816]
### Library name

Microsoft.Extensions.Azure

### Please describe the feature.

Coming from https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4002, I have been sent here.

The following extension is useful and neat, it would work like this for Blob Storage

```
builder.Services.AddAzureClients(options =>
        {
            //Add storage accounts
                options.AddBlobServiceClient(i"blabla").;
            // Use DefaultAzureCredential by default
            options.UseCredential(new DefaultAzureCredential());
        });
```
I wonder if we can add something like `AddCosmosServiceClient`?
I did not find it in the docs.

**Comment by jsquire** [comment]
Hi @Ponant.  This extension would need to be defined in the Cosmos package where the client is defined.  Unfortunately, as that means in the Cosmos repository where the original issue was opened.   I've responded to that issue directly to let the Cosmos team know.

**Comment by Ponant** [comment]
Thanks @jsquire 💯

**Comment by Ponant** [comment]
Should I close or later?

**Comment by jsquire** [comment]
@Ponant:  Thank you for asking; its entirely up to you.   Our automation will manage it if you'd prefer not to close immediately.

**Comment by Ponant** [comment]
See https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4002
