### ISSUE TITLE
Renew SasKey for BlobContainerClient

### ISSUE THREAD

**Issue by BeChaRem** [Azure/azure-sdk-for-net#37813]
### Library name

Azure.Storage.Blobs

### Please describe the feature.

Hi, 

We receive 1 hour write sas key and were wondering how to renew it once the BlobContainerClient is created.

For example:

```csharp

var containerclient = new BlobContainerClient(new Uri("https://storageaccount.blob.core.windows.net/containername?sig=something")
// Start upload
// 1 hour later, the sas key is expired and the upload fails.

```

How can we deal with this case? Is there a way to give a callback for new signature? Should I implement a custom `TokenCredential` or implement a custom `HttpClientTransport` and modify the Uri on the fly with a renewed signature? Or others method?

Please advise.

**Comment by navba-MSFT** [comment]
@BeChaRem Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@BeChaRem A shared access signature URI is associated with the account key that's used to create the signature. So, you need to have connection string or access key or the Relevant RBAC permissions to renew / regenerate the SAS key. You cannot renew / regenerate the SAS with ONLY existing sas token.

**Comment by BeChaRem** [comment]
Hi,

The saskey is received by a service with a 1 hour expiration to upload files on the container. As a user, I can request them at will to this service. 

The issue is that when I create a new `BlobContainerClient` object with the first sas key I only have 1 hour to upload with no way to tell the `BlobContainerClient` that if the current key is expired, I can gives it another one that is still valid.

The only way I can think to go around this issue, is to implement my own `HttpClientTransport` that intercept the query param and update them if they are expired.

Sample:
```csharp
internal sealed class CustomHttpPipeline : HttpClientTransport
{
    private readonly Func<Task<Uri>> _sharedSignatureCallback;

    public CustomHttpPipeline(Func<Task<Uri>> sharedSignatureCallback)
    {
        _sharedSignatureCallback = sharedSignatureCallback;
    }

    public override async ValueTask ProcessAsync(HttpMessage message)
    {
        var oriParam = HttpUtility.ParseQueryString(message.Request.Uri.Query);
        var expiration = DateTime.Parse(oriParam["se"]);
        if (expiration > DateTime.UtcNow)
        {
            var uri = await _sharedSignatureCallback.Invoke();
            var newParam = HttpUtility.ParseQueryString(uri.Query);
            oriParam["se"] = newParam["se"];
            oriParam["sig"] = newParam["sig"];
            message.Request.Uri.Query = oriParam.ToString();
        }
        await base.ProcessAsync(message);
    }
}

// And then use it
        using var pipeline = new CustomHttpPipeline(callback);
        var opt = new BlobClientOptions { Transport = pipeline };
        // Write a blob into container
        var container = new BlobContainerClient(sasUrl, opt);
        await container.UploadBlobAsync(blobName, memoryStream);
```
Callback being a function that return a newly requested SasKey from the service. 

This works, but I'm looking for a better way to do this than replace the query parameter on the fly.

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by amnguye** [comment]
Hi, you can use the `AzureSasCredential` instead when instantiating your client.

So it would something like 
```
AzureSasCredential credential = new AzureSasCredential(sas);
BlobContainerClient containerClient = new BlobContainerClient(uri, credential, options);
```
Then when your SAS expires you could do something like
```
// Wait 1 hour
credential.Update(newSas);
```

**Comment by BeChaRem** [comment]
Thanks for the answer, exactly what I was looking for.
