### ISSUE TITLE
[BUG] AppPlatformService invokes `AddTagAsync` method will throw InvalidOperationException error

### ISSUE THREAD

**Issue by dvbb** [Azure/azure-sdk-for-net#37823]
### Library name and version

Azure.ResourceManager.AppPlatform 1.1.0-beta.2

### Describe the bug

 
When I call `AddTagAsync()` method to update the tags of an AppPlatform service, the server returns an HTTP status code of 202. 202 is not a final state in the SDK, so it continues to request the location in the ResponseHeaders. 
However, the final request URI in the returned 200 is 
```
GET /subscriptions/**/resourceGroups/**/providers/Microsoft.AppPlatform/locations/eastus/operationResults/**/Spring/**?api-version=2022-12-01 HTTP/1.1
(id=/subscriptions/**/resourceGroups/**/providers/Microsoft.AppPlatform/Spring/**)
```
instead of the initial 
```
PUT /subscriptions/**/resourceGroups/**/providers/Microsoft.AppPlatform/Spring/**/providers/Microsoft.Resources/tags/default?api-version=2022-09-01
(id=/subscriptions/**/resourceGroups/**/providers/Microsoft.AppPlatform/Spring/**/providers/Microsoft.Resources/tags/default)
```
which will cause an error in ValidateResourceId(): 
System.ArgumentException: Invalid resource type `Microsoft.AppPlatform/Spring` expected `Microsoft.Resources/tags` (Parameter 'id'). 

### Expected behavior

service's tags updated and SDK doesn't throw exception

### Actual behavior

service's tags updated and SDK throws exception 

### Reproduction Steps

1. Add `Azure.ResourceManager` to project dependency 
2. Add `Azure.ResourceManager.AppPlatform` to project dependency or install `Azure.ResourceManager.AppPlatform 1.1.0-beta.2`
3.  
```
TokenCredential cred = new DefaultAzureCredential();
ArmClient client = new ArmClient(cred);
var rg  = await client.GetDefaultSubscription().GetResourceGroups().GetAsync("rgName");
AppPlatformServiceResource service = await rg.Value.GetAppPlatformServices().GetAsync("AzureSpringAppServiceName");
_ = await service.AddTagAsync("newkey","value");
```

**Comment by live1206** [comment]
@dvbb From the description, the location in the ResponseHeaders of the service response is pointing to operation status, which is wrong. This needs service attention to fix it.

**Comment by jsquire** [comment]
@ArthurMa1978 :  Given that the service teams do not monitor our repository, can we engage with them via IcM, Azure support request, or another process rather than leave this issue open?

**Comment by live1206** [comment]
```
"RequestUri": "https://management.azure.com/subscriptions/{subcriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.AppPlatform/Spring/{servicename}/providers/Microsoft.Resources/tags/default?api-version=2022-09-01",
"RequestMethod": "PUT"
```
While polling the status from service, the final 200 response contains the wrong `id`, expecting `Microsoft.Resources/tags` but received `Microsoft.AppPlatform/Spring `

**Comment by live1206** [comment]
Thanks to @weidongxu-microsoft, this scenario is written in [202-accepted-and-location-headers](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#202-accepted-and-location-headers). 
```
If the operation is complete, return the exact same response that would have been returned had the operation been executed synchronously.
```

**Comment by live1206** [comment]
ARM team is working on a fix for this.
