### ISSUE TITLE
[BUG] Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.13 creates ReadOnlyDictionary messages

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-for-net#37832]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.13

### Describe the bug

When I upgrade from 1.0.0-beta.12 to 1.0.0-beta.13 in this [internal PR](https://dev.azure.com/msazure/One/_git/Azure-Dedicated-AVS/pullrequest/8366415?path=/src/Directory.Build.props), a bunch of new traces show up with `System.Collections.ObjectModel.ReadOnlyDictionary\u00602[System.String,System.Object]` as the message.

In the VS output window while debugging, the json shows:
``` json
{"name":"Message","time":"2023-07-25T09:26:22.6228639Z","iKey":"6dd2e7ec-afc5-4231-8bce-075f266bf999","tags":{"ai.cloud.role":"unknown_service:func","ai.cloud.roleInstance":"CPC-catag-TL2L0","ai.internal.sdkVersion":"dotnet6.0.9:otel1.5.0:ext1.0.0-beta.13"},"data":{"baseType":"MessageData","baseData":{"message":"System.Collections.ObjectModel.ReadOnlyDictionary\u00602[System.String,System.Object]","severityLevel":"Information","properties":{"Name":"StartExpireTrials","Count":"1","Timestamp":"7/25/2023 9:25:56 AM \u002B02:00","AvgDurationMs":"00:00:00.5144233","MaxDurationMs":"00:00:00.5144233","MinDurationMs":"00:00:00.5144233","Successes":"1","Failures":"0","SuccessRate":"100"},"ver":2}}}
```

In the Azure Portal, the new entries look like this:
![image](https://github.com/Azure/azure-sdk-for-net/assets/87583576/71f3255c-58fc-4b9c-a6c6-c12d9abf90e8)

There is one for each Activity.

### Expected behavior

It behaves like 1.0.0-beta.12 and they do not get output.

### Actual behavior

It gets output.

### Reproduction Steps

I linked to the PR.

### Environment

Our [global.json](https://dev.azure.com/msazure/One/_git/Azure-Dedicated-AVS?path=/global.json):
``` json
{
  "sdk": {
    "version": "7.0.302",
    "rollForward": "latestMinor",
    "allowPrerelease": false
  }
}
```

We are using Azure Functions based on this [Dockerfile](https://dev.azure.com/msazure/One/_git/Azure-Dedicated-AVS?path=/src/conveyor/ConsumptionWorker/consumption-worker/Dockerfile) with:
```
FROM mcr.microsoft.com/azure-functions/dotnet:4.0.1.16816-dotnet6-appservice
```

**Comment by navba-MSFT** [comment]
Adding Service team to look into this.

**Comment by CodeBlanch** [comment]
It looks like Functions has some custom ILogger states which do not implement a template or a formatter which is causing the logs to look strange when captured by OpenTelemetry. I opened a PR to try and get that fixed upstream.

**Comment by cataggar** [comment]
The upstream PR was merged for Azure/azure-webjobs-sdk. It looks like a couple of different packages need to be updated. As far as I can tell, https://github.com/Azure/azure-functions-host/blob/dev/src/WebJobs.Script/WebJobs.Script.csproj has had Microsoft.Azure.WebJobs updated https://github.com/Azure/azure-functions-host/pull/9541, but still needs  Microsoft.Azure.WebJobs.Logging.ApplicationInsights released and updated. Is that correct?

**Comment by RohitRanjanMS** [comment]
Hi @cataggar we will plan for a release.

**Comment by cataggar** [comment]
@RohitRanjanMS, what is the plan for a release?

**Comment by RohitRanjanMS** [comment]
@cataggar , this will be part of the next release.

**Comment by cataggar** [comment]
Which release am I waiting for? Is it this one? https://github.com/Azure/azure-webjobs-sdk/releases/tag/appinsights-v3.0.38

**Comment by cataggar** [comment]
This is solved by updating to https://www.nuget.org/packages/Microsoft.Azure.WebJobs/3.0.39 .
