### ISSUE TITLE
This kind of page is no documentation at all

### ISSUE THREAD

**Issue by JumbaJookiba** [Azure/azure-sdk-for-net#37834]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 80ec2205-98c0-e9ba-6d31-f3581c19d177
* Version Independent ID: 4f8cda0c-0f0a-049f-ec14-e11c6cd8c022
* Content: [CloudBlobContainer.GetBlobReference Method (Microsoft.WindowsAzure.Storage.Blob) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.cloudblobcontainer.getblobreference?view=azure-dotnet&devlangs=csharp&f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.GetBlobReference)%3Bk(DevLang-csharp)%26rd%3Dtrue)
* Content Source: [xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobContainer.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.WindowsAzure.Storage.Blob/CloudBlobContainer.xml)
* Service: **storage**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @JumbaJookiba.  Thank you for reaching out and we regret that you're experiencing difficulties.  The `WindowsAzure.Storage` package reached end-of-life in March of 2023 and is no longer maintained or supported.   We would strongly recommend moving to the [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs) package.

Closing this out, as the `WindowsAzure.Storage` package is no longer receiving updates.

**Comment by JumbaJookiba** [comment]
I will do, thanks.
Now I wonder why you ship references to deprecated packages in Visual Studio templates.
I just started developing an Azure function, and the package was installed automatically, because others are using it, e.g. Microsoft.Azure.WebJobs.Host.Storage

I think that the templates should be verified for deprecated packages.

D A Galliano
Ingegnere

________________________________

**Comment by jsquire** [comment]
Thank you for letting us know, @JumbaJookiba.   Visual Studio templates are not something that the Azure SDK team owns.   If you can let us know which specific template you used, we can work with the owners to get those updated.
