### ISSUE TITLE
Can't deploy Azure Vm with ARM Template, error with "patchSettings"

### ISSUE THREAD

**Issue by AKowsigan** [Azure/azure-sdk-for-net#37855]
Hello,

I try to deploy an Azure VM with windows with ARM Template with this configuration : 

```
"osProfile": {
                    "computerName": "[parameters('virtualMachineName')]",
                    "adminUsername": "[parameters('adminUsername')]",
                    "adminPassword": "[parameters('adminPassword')]",
                    "windowsConfiguration": {
                        "ProvisionVMAgent": true,
                        "EnableAutomaticUpdates": true,
                        "PatchSettings": {
                            "patchMode": "AutomaticByPlatform",
                            "automaticByPlatformSettings": {
                                "bypassPlatformSafetyChecksOnUserSchedule": true
                            },
                            "assessmentMode": "AutomaticByPlatform"
                        },
                        "enableVMAgentPlatformUpdates": false
                    },
                    "secrets": []
                },
```

but i have this error in powerhsell and also on Azure portal 
Message : Could not find member 'patchSettings' on object of type 'WindowsConfiguration'. Path 'properties.osProfile.windowsConfiguration.patchSettings', line 1, position 355.
Error Code : BadRequest

I searched for a lot of time, but i didn't find the solution.
Thanks in advance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea17fd8b-0187-1723-b1df-0ab1e73c059f
* Version Independent ID: 9dc81c82-6fb7-e8b3-2760-a1b54122fe9e
* Content: [WindowsConfiguration Class (Microsoft.Azure.Management.Compute.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.compute.models.windowsconfiguration?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.Compute.Models/WindowsConfiguration.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.Compute.Models/WindowsConfiguration.xml)
* Service: **multiple**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @AKowsigan.  Thank you for reaching out and we regret that you're experiencing difficulties.  Can you please help us understand which Azure SDK package you're using so that we can loop in the right folks to assist?

**Comment by jsquire** [comment]
Hi @AKowsigan.  If I understand what you're looking for, it would be the schema for VMs, which appears to be [here](https://learn.microsoft.com/azure/templates/microsoft.compute/virtualmachines?pivots=deployment-language-bicep).

Unfortunately, there's no further help that we can provide.  This repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.   If further help is needed, your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
