### ISSUE TITLE
Keys mangement endpoints are not documented or exposed via Azure SDK for .NET consistently

### ISSUE THREAD

**Issue by thegrahamking** [Azure/azure-sdk-for-net#37862]
The _create/update_ and _delete_ host/functions or system key endpoints added to resolve Azure/azure-functions-host#3994 are not documented in Azure REST API reference (https://learn.microsoft.com/en-us/rest/api/azure/) or exposed via the Azure SDK for .NET (https://learn.microsoft.com/en-us/dotnet/api/overview/azure/?view=azure-dotnet), and I suspect other languages too but haven't verified this.

PUT `api/sites/{name}[/slots/{slot}]/host/default/{functionkeys|systemkeys}/{keyName}`
DELETE `api/sites/{name}[/slots/{slot}]/host/default/{functionkeys|systemkeys}/{keyName}`

The current version of the SDK `Azure.ResourceManager.AppService` does not expose the `HttpClient` it uses and so it's not possible (without creating _another_ `HttpClient` instance) to make requests to these endpoints.

There is inconsistency across other key management endpoints too:

The _list_ host keys endpoint is documented and exposed via the Azure SDK for .NET
POST `/host/default/listkeys`
https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list-host-keys
https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.appservice.websiteresource.gethostkeysasync?view=azure-dotnet

The _list_ function key endpoint is documented and exposed via the Azure SDK for .NET
POST `/functions/{functionName}/listkeys`
https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/list-function-keys
https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.appservice.sitefunctionresource.getfunctionkeysasync?view=azure-dotnet#azure-resourcemanager-appservice-sitefunctionresource-getfunctionkeysasync(system-threading-cancellationtoken)

The _create/update_ and _delete_ function key endpoint is _not_ document but _is_ exposed via the Azure SDK for .NET
PUT `/functions/{functionName}/keys/{keyName}`
https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.appservice.sitefunctionresource.createorupdatefunctionsecretasync?view=azure-dotnet#azure-resourcemanager-appservice-sitefunctionresource-createorupdatefunctionsecretasync(system-string-azure-resourcemanager-appservice-models-webappkeyinfo-system-threading-cancellationtoken)
https://learn.microsoft.com/en-us/dotnet/api/azure.resourcemanager.appservice.sitefunctionresource.deletefunctionsecretasync?view=azure-dotnet

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi, @thegrahamking , Thank you for using Azure SDK for .NET.
The APIs you mentioned has been updated into the REST APIs, as well as our SDK. 
But the content has some changes when applying, please check: 
https://github.com/Azure/azure-rest-api-specs/pull/7174
https://github.com/Azure/azure-rest-api-specs/pull/17653

**Comment by thegrahamking** [comment]
Hi @HarveyLink, with the age, length and depth of the issues you've linked to I'm struggling to see what you mean by "the content has some changes when applying", could you outline please?

I also can't see this change in the Azure SDK for .NET.  Could you point me to the relevant classes/methods in the docs please?

**Comment by HarveyLink** [comment]
> Hi @HarveyLink Minghao Chen (WICRESOFT NORTH AMERICA LTD) Vendor, with the age, length and depth of the issues you've linked to I'm struggling to see what you mean by "the content has some changes when applying", could you outline please?
> 
> I also can't see this change in the Azure SDK for .NET. Could you point me to the relevant classes/methods in the docs please?

PUT api/sites/{name}[/slots/{slot}]/host/default/{functionkeys|systemkeys}/{keyName}
DELETE api/sites/{name}[/slots/{slot}]/host/default/{functionkeys|systemkeys}/{keyName}
Applied as:
[/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{name}/slots/{slot}/host/default/{keyType}/{keyName}](https://github.com/Azure/azure-rest-api-specs/blob/f984ae525c5eaffa551075b27d87925f9f73c2d0/specification/web/resource-manager/Microsoft.Web/stable/2021-02-01/WebApps.json#L12979C6-L12979C155) with PUT and DELETE
SDK [PUT operation ](https://github.com/Azure/azure-sdk-for-net/blob/f250ca20db22bf123b3f0edea6481045e1877bcb/sdk/websites/Azure.ResourceManager.AppService/src/Generated/WebSiteSlotResource.cs#L4064) , [DELETE operation](https://github.com/Azure/azure-sdk-for-net/blob/f250ca20db22bf123b3f0edea6481045e1877bcb/sdk/websites/Azure.ResourceManager.AppService/src/Generated/WebSiteSlotResource.cs#L4167)

---

The create/update and delete function key endpoint is document at
https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/create-or-update-function-secret?view=rest-appservice-2022-03-01&viewFallbackFrom=rest-appservice-2021-02-01

**Comment by thegrahamking** [comment]
@HarveyLink thank you.

 I can't see any merged updates in the Azure SDK for .NET nor a PR for these changes.  Could you point me to the relevant docs for .NET or provide an ETA for when they will be available please?
