### ISSUE TITLE
GeneratevpnclientpackageWithHttpMessagesAsync returns Operation returned an invalid status code 'Accepted'

### ISSUE THREAD

**Issue by keschner** [Azure/azure-sdk-for-net#3786]
Hello together,

I'm using the Nuget-Package Microsoft.Azure.Management.Network in preview version 15.

If I call BeginGeneratevpnclientpackageWithHttpMessagesAsync or GeneratevpnclientpackageWithHttpMessagesAsync I get a invalid status code error, because of the status code is 202 and only 200 is valid.

To get around this I've changed the code to accept 202 by adding 202 to this if statement: https://github.com/Azure/azure-sdk-for-net/blob/37e273edd435392a4b1d26cbae5aa70f8d06d492/src/SDKs/Network/Management.Network/Generated/VirtualNetworkGatewaysOperations.cs#L1600

After that I'm getting a wrong result (it's only a success message) if the async generation takes a little bit longer and needs more than on request in GetLongRunningOperationResultAsync. This is caused by following the "Azure-AsyncOperation" header which is send at second try to get a result and this header is pointing to operation endpoint instead of operationresult (name could be a little bit different, I don't remember 100%).

So I've implemented my own GetLongRunningOperationResultAsync which follows only the "Location" header and not the "Azure-AsyncOperation" header and now it's working.

Do I have to do something magically to get it working out of the box or is it really a bug?

Well may be not an sdk issue but while digging deeper to find the error I've noticed that the integration of application insights intercepts the http requests and replaces the generated x-ms-client-request-id header by an other value and that causes the GetLongRunningOperationResultAsync to never get a valid result. Is this an configuration issue on my side or is it also a bug?

Thanks

**Comment by shahabhijeet** [comment]
@ritwikbasu can you take a look at this particular API that you have introduced in network package.
This might need your input as to what needs to be called.

**Comment by ritwikbasu** [comment]
We have introduced new APIs to extend the functionality of the VpnClientPackage operations.

There are two options you can use with the latest SDK:
1. GenerateGatewayVpnProfile(resourceGroupName, virtualNetworkGatewayName, vpnClientParameters);
This operation does all the async handling and returns a SAS URL to the generated VpnProfile - this is similar to the older operation you are trying to use except that it now returns VpnProfiles for all supported devices.

2. GenerateGatewayVpnProfileWithHttpMessagesAsync - This is the new method that is analogous to the operation that you are trying to use. This has the proper return code handling for a long running operation.

The above options that I mentioned provide that capability out of the box and if you use the first option, you will not need to have any custom handler for the operation.

However, I am not able to comment on the application insights issue that you mentioned.

**Comment by keschner** [comment]
@ritwikbasu sorry for the late reply and thanks for your answer.
I've tried CreateOrUpdateVnetConnectionWithHttpMessagesAsync first but if I use the returned uri to create a new VnetConnectionGateway I get a 502 Error from the scm endpoint of my web app (https://WEBAPPNAME.scm.azurewebsites.net). Therefore I cannot use the kudu console or deploy a new version.

My thought was, its a problem with the returned uri because the function I'm using (BeginGeneratevpnclientpackageWithHttpMessagesAsync) returns a uri of an executable file and the function you mentioned (GenerateGatewayVpnProfileWithHttpMessagesAsync) returns a zip file.

I've also tried to do not pass a VpnPackageUri at CreateOrUpdateVnetConnectionGatewayWithHttpMessagesAsync but then I don't get a valid connection.

Do you have a hint how to do this correctly?
Thanks in advance.

**Comment by keschner** [comment]
Hey @ritwikbasu,
I don't want to annoy you, but I hang on this issue and want to solve it correctly (not with an ugly workaround). So, could you please point me in an direction in which I can do further research?
Thanks in advance.

**Comment by AlexGhiondea** [comment]
@keschner apologies for the long wait. Do you still have this issue?

**Comment by keschner** [comment]
@AlexGhiondea: thanks for your reply. In the mean time the project I had this issue was discontinued, so I could not tell you if it's fix in a new version.
