### ISSUE TITLE
Microsoft Graph API Idempotency

### ISSUE THREAD

**Issue by Rookian** [Azure/azure-sdk-for-net#37877]
### Library name and version

Microsoft.Graph 5.19.0

### Query/Question

Is there any guidance on how to create an app registration and service principal and how to configure those in an **idempotent way**?

Why are the Microsoft Graph APIs itself not idempotent like all the Azure.ResourceManager.* libraries?

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Graph` library is maintained as [#2042](https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2042).
