### ISSUE TITLE
Typo in SearchDocument Example

### ISSUE THREAD

**Issue by ThatOrJohn** [Azure/azure-sdk-for-net#37907]
https://learn.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme?view=azure-dotnet#use-searchdocument-like-a-dictionary-for-search-results

This:

Console.WriteLine("{id}: {name}");

Should be:

Console.WriteLine($"{id}: {name}");

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f60660a9-9a80-3259-8eeb-79d18bcf5d50
* Version Independent ID: 6f76c320-0f86-7013-a389-8aba5421706e
* Content: [Azure Cognitive Search client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/search.documents-readme?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/search.documents-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/search.documents-readme.md)
* Service: **search**
* GitHub Login: @ShivangiReja
* Microsoft Alias: **shreja**

**Comment by ShivangiReja** [comment]
Thank you for bringing this issue to our attention. We will include a fix for it in the upcoming search preview release.
