### ISSUE TITLE
[BUG] AzureCliCredential does not correctly detect whether az cli is installed or not on non-english systems

### ISSUE THREAD

**Issue by jonathan-vogel-siemens** [Azure/azure-sdk-for-net#37902]
### Library name and version

Azure.Identity 1.9.0

### Describe the bug

When running on a non-english system and using AzureCliCredential, the error message returned by Azure CLI is not interpreted correctly. AzureCliCredential will throw `AuthenticationFailedException` instead of `CredentialUnavailableException` when Azure CLI is not installed.

It expects an error message like "'az' is not recognized" (as seen here: https://github.com/Azure/azure-sdk-for-net/blob/512832af4a8f435c7cd3ddb2fa751adcf09644ea/sdk/identity/Azure.Identity/src/Credentials/AzureCliCredential.cs#L25), but that error message is localized in Windows, which will make it fail to correctly determine that Azure CLI is not installed on non-english systems. Then, `WinAzureCLIError` is matched here: https://github.com/Azure/azure-sdk-for-net/blob/512832af4a8f435c7cd3ddb2fa751adcf09644ea/sdk/identity/Azure.Identity/src/Credentials/AzureCliCredential.cs#L148 but not able to detect that Azure CLI is not installed.

This breaks especially the functionality of `ChainedTokenCredential`, which could be used to try different token sources, but fails as soon as the condition described above is met. DefaultAzureCredential is not affected.

### Expected behavior

`AzureCliCredential` throws `CredentialUnavailableException` when Azure CLI is not installed.

### Actual behavior

`AzureCliCredential` throws `AuthenticationFailedException` when Azure CLI is not installed.

### Reproduction Steps

Use `AzureCliCredential` on a non-english system where Azure CLI is not installed

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jonathan-vogel-siemens** [comment]
Hi @christothes 

The error message in German is "Der Befehl "az" ist entweder falsch geschrieben oder
konnte nicht gefunden werden."

![image](https://github.com/Azure/azure-sdk-for-net/assets/64040537/9ab88715-cd43-40d0-9789-333ad5fb91a2)

**Comment by christothes** [comment]
this should be resolved now, as we default to `CredentialUnavailableException` whenever the credential is part of a chained credential such as DefaultAzureCredential.
