### ISSUE TITLE
[BUG] Script Update-Mgmt-CI.ps1 fails

### ISSUE THREAD

**Issue by azaslonov** [Azure/azure-sdk-for-net#37901]
### Library name and version

N/A

### Describe the bug

I'm trying to follow instructions described [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process#sdk-generation-from-scratch). The script referenced in step 6 of the instructions fails with the following error:

<img width="784" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/2320302/42728e43-42c5-447a-8d02-a9c19251bdd3">

### Expected behavior

Script should execute.

### Actual behavior

Script fails.

### Reproduction Steps

See screenshot above.

### Environment

.NET SDK:
 Version:   7.0.400-preview.23225.8
 Commit:    c63317749e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64

**Comment by azaslonov** [comment]
Thanks @jsquire. Is there a workaround for this? It kind of blocks us to move on with .NET SDK.

**Comment by jsquire** [comment]
@azaslonov:  We'll need @ArthurMa1978's perspective.   I do not have insight on the management tooling.

**Comment by azaslonov** [comment]
Got it. @ArthurMa1978, could you suggest anything?

**Comment by azaslonov** [comment]
@ArthurMa1978, it worked indeed! Thanks a lot!
