### ISSUE TITLE
Response is System.Null Reference while Update_RegisterAzureStorageProtectionContainers

### ISSUE THREAD

**Issue by pksouza23** [Azure/azure-sdk-for-net#37904]
### Library name and version

Azure.ResourceManager.RecoveryServicesBackup 1.0.0

### Describe the bug

I am registering storage container in the recovery service vault. But I am getting System Reference null error is throwing, storage container is successfully register. But problem is the response.

![image](https://github.com/Azure/azure-sdk-for-net/assets/140831732/bda3d332-245a-40b5-afaf-8411dfcc3a9c)

![image](https://github.com/Azure/azure-sdk-for-net/assets/140831732/2af4fb61-a7f0-445c-9374-02af17a52f0f)

### Expected behavior

Response should come properly without null reference issue. 

Response should be included status 202 and location path.

HTTP/1.1 202 Accepted
'Pragma': 'no-cache'
'Expires': '-1'
'Location': ‘https://management.azure.com/Subscriptions/00000000-0000-0000-0000-000000000000/ResourceGroups
/azurefiles/providers/Microsoft.RecoveryServices/vaults/azurefilesvault/backupFabrics/Azure/operationResults/
cca47745-12d2-42f9-b3a4-75335f18fdf6?api-version=2016-12-01’
'Retry-After': '60'
'X-Content-Type-Options': 'nosniff'
'x-ms-request-id': '6cc12ceb-90a2-430d-a1ec-9b6b6fdea92b'
'x-ms-client-request-id': ‘3da383a5-d66d-4b7c-982a-bc8d94798d61,3da383a5-d66d-4b7c-982a-bc8d94798d61’
'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
'X-Powered-By': 'ASP.NET'
'x-ms-ratelimit-remaining-subscription-reads': '11996'
'x-ms-correlation-request-id': '6cc12ceb-90a2-430d-a1ec-9b6b6fdea92b'
'x-ms-routing-request-id': CENTRALUSEUAP:20200203T091326Z:6cc12ceb-90a2-430d-a1ec-9b6b6fdea92b'
'Date': 'Mon, 03 Feb 2020 09:13:25 GMT'

### Actual behavior

![image](https://github.com/Azure/azure-sdk-for-net/assets/140831732/bda3d332-245a-40b5-afaf-8411dfcc3a9c)

![image](https://github.com/Azure/azure-sdk-for-net/assets/140831732/2af4fb61-a7f0-445c-9374-02af17a52f0f)

### Reproduction Steps

https://learn.microsoft.com/en-us/rest/api/backup/protection-containers/register?tabs=dotnet

using System;
using System.Threading.Tasks;
using Azure;
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.RecoveryServicesBackup;
using Azure.ResourceManager.RecoveryServicesBackup.Models;
using Azure.ResourceManager.Resources;

// Generated from example definition: specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2023-02-01/examples/AzureStorage/ProtectionContainers_Register.json
// this example is just showing the usage of "ProtectionContainers_Register" operation, for the dependent resources, they will have to be created separately.

// get your azure access token, for more details of how Azure SDK get your access token, please refer to https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication?tabs=command-line
TokenCredential cred = new DefaultAzureCredential();
// authenticate your client
ArmClient client = new ArmClient(cred);

// this example assumes you already have this BackupProtectionContainerResource created on azure
// for more information of creating BackupProtectionContainerResource, please refer to the document of BackupProtectionContainerResource
string subscriptionId = "00000000-0000-0000-0000-000000000000";
string resourceGroupName = "SwaggerTestRg";
string vaultName = "swaggertestvault";
string fabricName = "Azure";
string containerName = "StorageContainer;Storage;SwaggerTestRg;swaggertestsa";
ResourceIdentifier backupProtectionContainerResourceId = BackupProtectionContainerResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, vaultName, fabricName, containerName);
BackupProtectionContainerResource backupProtectionContainer = client.GetBackupProtectionContainerResource(backupProtectionContainerResourceId);

// invoke the operation
BackupProtectionContainerData data = new BackupProtectionContainerData(new AzureLocation("placeholder"))
{
    Properties = new StorageContainer()
    {
        SourceResourceId = new ResourceIdentifier("/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/SwaggerTestRg/providers/Microsoft.Storage/storageAccounts/swaggertestsa"),
        AcquireStorageAccountLock = AcquireStorageAccountLock.Acquire,
        FriendlyName = "swaggertestsa",
        BackupManagementType = BackupManagementType.AzureStorage,
    },
};
**ArmOperation<BackupProtectionContainerResource> lro = await backupProtectionContainer.UpdateAsync(WaitUntil.Completed, data);** // has problem in response
BackupProtectionContainerResource result = lro.Value;

// the variable result is a resource, you could call other operations on this instance as well
// but just for demo, we get its data from this resource instance
BackupProtectionContainerData resourceData = result.Data;
// for demo we just print out the id
Console.WriteLine($"Succeeded on id: {resourceData.Id}");

### Environment

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.6.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pksouza23** [comment]
Sure, Thank you

**Comment by pksouza23** [comment]
I have uploaded source code in the https://github.com/pksouza23/POCfilesharebackup

**Comment by pksouza23** [comment]
Is there any update on this issue?

**Comment by HarveyLink** [comment]
Hi @pksouza23 , we have repro you issue, working on a solution now.

**Comment by pksouza23** [comment]
Hi @HarveyLink , Please let us know once it is fixed, we are waiting for the resolution. Thank you.

**Comment by pksouza23** [comment]
Hi @HarveyLink , Any update on fix for the issue ?

Thanks in advance.

**Comment by pksouza23** [comment]
HI @HarveyLink  @jsquire ,

Any progress on this issue?

Thanks in advance.

**Comment by jsquire** [comment]
@pksouza23:  Unfortunately, I do not have insight.   We'll need an update from @HarveyLink or @ArthurMa1978.

**Comment by HarveyLink** [comment]
Hi @pksouza23 It's a service issue, we'll make a quick fix on the sdk to make it work first. Further fix would need service team's help.

**Comment by pksouza23** [comment]
Hi @HarveyLink, Thanks for the response. Once quick fix applied on the SDK let us know.

**Comment by YariMVSage** [comment]
Also waiting for a resolution. Any news on that would be grateful

**Comment by pksouza23** [comment]
Hi @YariMVSage , @HarveyLink , If this is fixed, please let me know if that is applied to SDK. So that I can test the issue using updated SDK.

Thanks,

**Comment by HarveyLink** [comment]
> Also waiting for a resolution. Same issue with BackupProtectedItems PUT, @HarveyLink Minghao Chen (WICRESOFT NORTH AMERICA LTD) Vendor I don't know if you are aware of it. Any news on that would be grateful

Opened issue to track the fix, have a PR now. Will let you know once we fixed that.

**Comment by YariMVSage** [comment]
Hi @HarveyLink  Thanks!!

**Comment by HarveyLink** [comment]
> Hi @HarveyLink Thanks!!

Issue fix was meged, will have a release for that. I will keep you posted.

**Comment by HarveyLink** [comment]
Released : https://www.nuget.org/packages/Azure.ResourceManager.RecoveryServicesBackup
