### ISSUE TITLE
[BUG] Call to SyncFunctionTriggersAsync() always fails

### ISSUE THREAD

**Issue by yuramag** [Azure/azure-sdk-for-net#37918]
### Library name and version

Azure.ResourceManager.AppService

### Describe the bug

Consider the following code:

```
var app = await myResourceGroup.GetWebSites().GetAsync("my-app-name", ct);
await app.SyncFunctionTriggersAsync(ct); // Always fails.
```

Call to `SyncFunctionTriggersAsync()` always fails even if `HTTP 200` was received. Seems like the implementation of it only expects `HTTP 204` as a valid return code.

### Expected behavior

Call to `SyncFunctionTriggersAsync()` should not fail.

### Actual behavior

Call to `SyncFunctionTriggersAsync()` always fails.

### Reproduction Steps

```
var app = await myResourceGroup.GetWebSites().GetAsync("my-app-name", ct);
await app.SyncFunctionTriggersAsync(ct); // Always fails.
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
