### ISSUE TITLE
[QUERY] How do I create a Function v4 using resource manager API?

### ISSUE THREAD

**Issue by yuramag** [Azure/azure-sdk-for-net#37919]
### Library name and version

Azure.ResourceManager.AppService

### Query/Question

Consider the following code that worked for function apps prior to `v4`:

```
var bindingsConfig = new
{
    bindings = new object[]
        {
            new
            {
                AuthLevel = "function",
                Type = "httpTrigger",
                Direction = "in",
                Name = "request",
                Methods = new[] {"post"}
            },
            new
            {
                Type = "http",
                Direction = "out",
                Name = "$return"
            }
        }
};

app = await myResourceGroup.GetWebSites().GetAsync("my-app-name", ct);
var func = await app.GetSiteFunctions().CreateOrUpdateAsync(WaitUntil.Completed, "my-func-name", new FunctionEnvelopeData
{
    Config = BinaryData.FromObjectAsJson(config)
}, ct);
```

Now according to [this doc](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-node?tabs=javascript%2Cwindows%2Cazure-cli&pivots=nodejs-model-v4), `function.json` is no longer used in `v4` programming model. My question is - does it mean I shouldn't be passing `bindingsConfig` into `CreateOrUpdateAsync()`? When I try it though I get the following error:

```
Azure.RequestFailedException: 'Error creating function. <my-func-name> is not a valid function name
Status: 400 (Bad Request)
ErrorCode: BadRequest
```

In general how should I call `CreateOrUpdateAsync()` to create a `v4` kind of function?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yuramag** [comment]
I'd greatly appreciate if someone can point me to an example of creating a `v4` function app using Resource Manager API.

**Comment by yuramag** [comment]
Well I can certainly open a ticket with Azure support, but I believe this is a problem of SDK. Azure allows creating a v4 function app  via deployment from VS Code. But what I need is to create one using SDK (`Azure.ResourceManager.AppService` lib). All I ask is for a working example of making a call to `CreateOrUpdateAsync()` described above that will create a v4 function app. Unfortunately there is no documentation that describes it or gives any examples.

Can you at least answer the question whether or not the creation of v4 function app is supported by `Azure.ResourceManager.AppService`? Have you ever tried/tested it internally on your end?
