### ISSUE TITLE
[QUERY] How to mock FirewallPolicyCollection and extension methods in unit test 

### ISSUE THREAD

**Issue by rguthriemsft** [Azure/azure-sdk-for-net#37911]
### Library name and version

Azure.ResourceManager.Network 1.3.0

### Query/Question

Given a method that  that looks like this:

        
```csharp
        public virtual async Task<NetworkProvisioningState> WaitForFirewallAsync(FirewallPolicyResource policy, ResourceGroupResource resourceGroup, CancellationToken cancellationToken)
        {
            if (policy.Data.ProvisioningState == NetworkProvisioningState.Updating)
            {
                int iterator = 0;
                FirewallPolicyCollection firewallPoliciesCollection;
                // wait for up to 10 min for policy to complete update
                do
                {
                    var timespan = TimeSpan.FromSeconds(60.0);
                    Task.Delay(timespan);

                    firewallPoliciesCollection = resourceGroupResource.GetFirewallPolicies();
                    policy = firewallPoliciesCollection.FirstOrDefault();

                    if (policy.Data.ProvisioningState == NetworkProvisioningState.Succeeded)
                    {
                        break;
                    }
                    iterator++;
                }
                while (policy.Data.ProvisioningState == NetworkProvisioningState.Updating || iterator <= 10);
            }
            return policy.Data.ProvisioningState.Value;
        }
```

What is the recommended way to mock the collection class FirewallPolicyCollection?  I tried mocking up the GetAll method with something like below:

```csharp
            mockFirewallPolicyCollection
                .Setup(x => x.GetAll(It.IsAny<CancellationToken>()))
                .Returns(mockPageable);
```

but this leads me down a rabbit hole of mocking Pageable and mocking the firewallpolicy resource when all I really want to do control the behavior of firewallpolicyresource like below:

```csharp
            mockFirewallPolicyResource
                .SetupSequence(f => f.Data)
                .Returns(ArmNetworkModelFactory.FirewallPolicyData(provisioningState: NetworkProvisioningState.Updating))
                .Returns(ArmNetworkModelFactory.FirewallPolicyData(provisioningState: NetworkProvisioningState.Succeeded));
```

What is the right pattern to create test using the collections in azure sdk?

### Environment

.net 6.0 on windows running in azure app services

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
We are working on a feature that enables mocking for extension methods, tracking here: https://github.com/Azure/autorest.csharp/issues/3493

**Comment by ArthurMa1978** [comment]
We have released this feature and please update libs to latest version and refer https://learn.microsoft.com/en-us/dotnet/azure/sdk/unit-testing-mocking?tabs=csharp#understand-azure-resource-manager-arm-clients to enable extension mock
