### ISSUE TITLE
[QUERY] Creating custom client with AddClient() in AddAzureClients() using ClientSecretCredential and ClientOptions

### ISSUE THREAD

**Issue by spiral-dev** [Azure/azure-sdk-for-net#37932]
### Library name and version

Azure.Identity 1.9.0

### Query/Question

What is the correct approach when calling a daemon when using a custom client. I would like to use the Azure.Identity package and use it's client builder. Because this will manage the lifetime of the token.

The thing is that the `AddClient` method **needs** a class that inherits `ClientOptions`, but what purpose does it have? In this use case. Or is there an alternative?

A few observations:

- If I provide a custom class it must inherit `ClientOptions` and must be registered in the DI, 
- The `AddClient` TOptions does not enforce it to be inherited by `ClientOptions` It will fail when not inherited with `ClientOptions` .  (Constructor on type 'MyCustomOptions' not found.)
- I could also use `SecretClientOptions`, which works, but it does not feel ok, because it could have side effects.

I use `MyTokenKeeper` in the DelegatingHandler of a HttpClient to fill the `Authorization` header. That's the only thing I need in this use case.

```
            services.AddAzureClients(clientBuilder =>
            {
                clientBuilder.UseCredential(serviceProvider =>
                {
                    var myOptions = serviceProvider.GetRequiredService<myOptions>();
                    return new ClientSecretCredential(myOptions.TenantId, myOptions.ClientId, myOptions.Secret);
                });
                clientBuilder.AddClient<MyTokenKeeper, MyTokenKeeperClientOptions>((options, tokenCredential, serviceProvider) =>
                {
                    var myOptions = serviceProvider.GetRequiredService<MyOptions>();
                    var token = tokenCredential.GetToken(new TokenRequestContext(new[] { myOptions.Scope }), CancellationToken.None);
                    return new MyTokenKeeper(token.Token);
                });
            });
```

**Comment by jsquire** [comment]
Glad that you're unblocked!
