### ISSUE TITLE
[FEATURE REQ] LogsQueryClient is not behind an interface and not easy to mock in unit tests

### ISSUE THREAD

**Issue by MarcoK80** [Azure/azure-sdk-for-net#37933]
### Library name

Azure.Monitor.Query

### Please describe the feature.

We used Microsoft.Azure.OperationalInsights before and could mock the returns of the queries.
Now with the LogsQueryClient this is not possible anymore. It is not behind an interface and not easy to mock in unit tests.

Please improve here so that we can start using this

**Comment by jsquire** [comment]
Hi @MarcoK80.  Thank you for your feedback.   Support for mocking and unit testing is one of the core goals of the new Azure SDKs, and the details of the approach that we use are discussed and demonstrated in [Unit testing and mocking with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/unit-testing-mocking?tabs=csharp).

To summarize the article:  All of the public members of the client types are `virtual` or settable, the class is not sealed, and a parameterless constructor is available to ensure that it is usable with a mocking framework such as Moq or FakeItEasy.  You should be able to mock any client using the same approach that you prefer for other types, whether with a mocking framework or inheriting from the class and creating your own mock type, using the model factory to simulate behavior.

For model types that are returned by service operations, a factory class exists to enable creating them for testing.  In this case, you'd use [MonitorQueryModelFactory](https://learn.microsoft.com/dotnet/api/azure.monitor.query.models.monitorquerymodelfactory?view=azure-dotnet) to create service-owned response models.

With respect to the lack of interfaces, the Azure SDKs have a goal of strict backwards compatibility with a very high bar for any breaking changes.  With that in mind, the use of an interface makes evolving over time difficult; any change to the public API surface represented in an interface becomes a breaking change for anyone who has implemented it - including when we want to add new members.  Adding more interfaces to define new members (much like native COM interfaces do in Windows) is possible but quickly becomes burdensome for developers using the SDK.  Our classes and their virtual members can still be mocked and do not have this problem.  As a result, we intentionally avoid using interfaces outside of special circumstances.

I'm going to mark this as addressed, but please feel free unresolve should you wish to discuss further.
