### ISSUE TITLE
[QUERY] How do I add BatchPoolIdentity to my CloudPool so that my nodes can have UserDefinedManagedIdentity?

### ISSUE THREAD

**Issue by kawaiifoxx** [Azure/azure-sdk-for-net#37937]
### Library name and version

Microsoft.Azure.Batch:16.0.0

### Query/Question

I want to have a UserdefinedManagedIdentity added to my cloudpool when I create my cloudpool using .NET Batch SDK Client, how do I acheive this?

I have tried this:
```CSharp
  var pool = batchClient.PoolOperations.CreatePool(
                poolId: _batchConfig.PoolConfig.PoolName,
                targetDedicatedComputeNodes: _batchConfig.PoolConfig.DedicatedNodeCount,
                targetLowPriorityComputeNodes: _batchConfig.PoolConfig.LowPriorityNodeCount,
                virtualMachineSize: _batchConfig.PoolConfig.PoolVmSize,
                virtualMachineConfiguration: vmConfig
            );

            pool.NetworkConfiguration = new NetworkConfiguration()
            {
                SubnetId = _batchConfig.NetworkConfiguration.SubnetId,
                EnableAcceleratedNetworking = _batchConfig.NetworkConfiguration.AcceleratedNetworking
            };


            var batchPoolIdentity = (BatchPoolIdentity?)Activator.CreateInstance(
                typeof(BatchPoolIdentity), true);

            if (batchPoolIdentity != null)
                batchPoolIdentity.Type = PoolIdentityType.UserAssigned;

            if (batchPoolIdentity != null)
                batchPoolIdentity.UserAssignedIdentities = new List<UserAssignedIdentity>
                {
                    new(_batchConfig.PoolConfig.UserDefinedManagedIdentityResourceId)
                };


            pool.TargetNodeCommunicationMode = NodeCommunicationMode.Simplified;
            pool.Identity = batchPoolIdentity;
            pool.TaskSlotsPerNode = _batchConfig.PoolConfig.TaskSlotsPerNode;

            pool.StartTask = await CreateStartTask();

            await pool.CommitAsync();
```

Above code, creates the batch pool but it does not add the UserdefinedManagedIdentity. 

### Environment

.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.304\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.309 [C:\Program Files\dotnet\sdk]
  6.0.315 [C:\Program Files\dotnet\sdk]
  7.0.101 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]
  7.0.109 [C:\Program Files\dotnet\sdk]
  7.0.304 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by navba-MSFT** [comment]
@kawaiifoxx Thanks for reaching out to us and reporting this issue. 

Please check if you can set the [Identity property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.cloudpool.identity?view=azure-dotnet) of the CloudPool object to a BatchPoolIdentity object that specifies the user-assigned identity.

See [**this**](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.batch.batchpoolidentity.userassignedidentities?view=azure-dotnet#microsoft-azure-batch-batchpoolidentity-userassignedidentities).

```
// Create a BatchPoolIdentity object with the user-assigned identity
BatchPoolIdentity identity = new BatchPoolIdentity
{
    Type = PoolIdentityType.UserAssigned,
    UserAssignedIdentities = new Dictionary<string, UserAssignedIdentity>
    {
        { "<user-assigned-identity-resource-id>", new UserAssignedIdentity() }
    }
};

// Create the pool with the identity
CloudPool pool = batchClient.PoolOperations.CreatePool(
    poolId: "<pool-id>",
    virtualMachineSize: "<vm-size>",
    targetDedicatedComputeNodes: <dedicated-node-count>,
    targetLowPriorityComputeNodes: <low-priority-node-count>,
    virtualMachineConfiguration: vmConfig,
    identity: identity);

// Commit the pool
await pool.CommitAsync();
```
In the above code, replace <user-assigned-identity-resource-id> with the resource ID of the user-assigned managed identity that you want to add to the pool, and replace <pool-id>, <vm-size>, <dedicated-node-count>, and <low-priority-node-count> with the appropriate values for your pool.

Note that the BatchPoolIdentity class is defined in the Microsoft.Azure.Batch.Protocol.Models namespace, so you may need to add a using directive for this namespace at the top of your code file.

**Comment by kawaiifoxx** [comment]
@navba-MSFT, thanks for the reply. Unfortunately, I cannot find any overload for `BatchClient.PoolOperations.CreatePool` which takes in `Microsoft.Azure.Batch.Protocol.Models.BatchPoolIdentity` as one of the parameters.

**Comment by kawaiifoxx** [comment]
Also, I tried another solution, what I do is first create the pool and then add managed identity to the pool, this adds the managed identity successfully but, the tasks that run in the vms cannot access it for some reason.

```C#
 var pool = batchClient.PoolOperations.CreatePool(
                poolId: _batchConfig.PoolConfig.PoolName,
                targetDedicatedComputeNodes: _batchConfig.PoolConfig.DedicatedNodeCount,
                targetLowPriorityComputeNodes: _batchConfig.PoolConfig.LowPriorityNodeCount,
                virtualMachineSize: _batchConfig.PoolConfig.PoolVmSize,
                virtualMachineConfiguration: vmConfig
            );

            pool.NetworkConfiguration = new NetworkConfiguration()
            {
                SubnetId = _batchConfig.NetworkConfiguration.SubnetId,
                EnableAcceleratedNetworking = _batchConfig.NetworkConfiguration.AcceleratedNetworking
            };
            
            pool.TaskSlotsPerNode = _batchConfig.PoolConfig.TaskSlotsPerNode;

            pool.StartTask = await CreateStartTask();

            await pool.CommitAsync();

            await AddManagedIdentity();
```

#### AddManagedIdentity() impl

```C#
 private async Task AddManagedIdentity()
    {
        var armClient = new ArmClient(new ClientSecretCredential(_azureAdConfig.TenantId, _azureAdConfig.ClientId,
            _azureAdConfig.ClientSecret));

        var pool = await armClient.GetBatchAccountResource(ResourceIdentifier.Parse(_batchConfig.Basic.BatchResourceId))
            .GetBatchAccountPoolAsync(_batchConfig.PoolConfig.PoolName);


        if (!pool.HasValue)
        {
            throw new InvalidOperationException(
                $"Unable to find batch pool for batch account: {_batchConfig.Basic.BatchResourceId}");
        }

        pool.Value.Data.Identity = new ManagedServiceIdentity(ManagedServiceIdentityType.UserAssigned)
        {
            UserAssignedIdentities =
            {
                [ResourceIdentifier.Parse(_batchConfig.PoolConfig.UserDefinedManagedIdentityResourceId)] = new()
            }
        };

        await pool.Value.UpdateAsync(pool.Value.Data);
    }
```

**Comment by navba-MSFT** [comment]
@kawaiifoxx Thanks for getting back. Could you please try to add the identity to the virtual machine's local administrators group? You can do this by using a startup task that runs a PowerShell script. So in short you can try to add a startup task to the Batch pool that configures the virtual machines to use the user-assigned managed identity.

You can try configuring the virtual machines to use the identity. I am guessing that after following this the tasks that run in the virtual machines should be able to access the identity.

Example:

```
private async Task AddStartupTask(string poolId)
{
    var startupTask = new StartTask()
    {
        CommandLine = "powershell -ExecutionPolicy Unrestricted -File configure-identity.ps1",
        ResourceFiles = new List<ResourceFile>()
        {
            new ResourceFile(
                fileUrl: "https://<storage-account-name>.blob.core.windows.net/scripts/configure-identity.ps1",
                blobPrefix: null,
                filePath: "configure-identity.ps1")
        },
        WaitForSuccess = true
    };

    var pool = await batchClient.PoolOperations.GetPoolAsync(poolId);

    pool.StartTask = startupTask;

    await pool.CommitAsync();
}
```

**Comment by kawaiifoxx** [comment]
@navba-MSFT could you pls let me know how I add user assigned managed identity to the local administrators group using powershell? I am not able to do it using 

```powershell
Add-LocalGroupMember -Group "Administrators" -Member $MANAGED_IDENTITY_OBJECT_ID
```

I have tried running same command with client id and name, nothing is working.

**Comment by kawaiifoxx** [comment]
So, I was finally able to resolve this issue using apis provided by `Azure.ResourceManeger.Batch:1.2.0`, main takeaway is that you need to attach managed identity while you are creating the Batch Pool, if you create the pool and then attach managed identity then the Pool VMs will not have those identities attached to them, in this case you need to resize the pool to 0 and back up to attach the managed identity to Pool VMs and this is a long process, so a better approach would be to do it when you are creating the pool and you can do it with `ArmClient` . Right now I don't think there is any way to create a batch pool with managed identity using `Microsoft.Azure.Batch:16.0.0` SDK, you will need to use `Azure.ResourceManeger.Batch:1.2.0` to achieve this. Here's how I did it.

```C#
    private async Task CreateBatchPoolIfNotExists()
    {
        var armClient = new ArmClient(new ClientSecretCredential(_azureAdConfig.TenantId, _azureAdConfig.ClientId,
            _azureAdConfig.ClientSecret));

        var batchAccountResource =
            armClient.GetBatchAccountResource(ResourceIdentifier.Parse(_batchConfig.Basic.BatchResourceId));

        batchAccountResource = await batchAccountResource.GetAsync();

        if (!batchAccountResource.HasData)
        {
            throw new InvalidOperationException(
                $"Batch account with resource id: {_batchConfig.Basic.BatchResourceId} is not present");
        }

        try
        {
            await batchAccountResource.GetBatchAccountPoolAsync(_batchConfig.PoolConfig.PoolName);
            _logger.LogInformation("Batch pool with id: {} already exists", _batchConfig.PoolConfig.PoolName);

            return;
        }
        catch (RequestFailedException e)
        {
            if (e.ErrorCode != BatchErrorCodeStrings.PoolNotFound) throw;
        }


        var batchAccountPoolData = new BatchAccountPoolData()
        {
            DisplayName = _batchConfig.PoolConfig.PoolName,

            DeploymentConfiguration = new BatchDeploymentConfiguration()
            {
                VmConfiguration = new BatchVmConfiguration(imageReference: new BatchImageReference()
                    {
                        Offer = _batchConfig.PoolConfig.VmConfiguration.ImageReference.Offer,
                        Publisher = _batchConfig.PoolConfig.VmConfiguration.ImageReference.Publisher,
                        Sku = _batchConfig.PoolConfig.VmConfiguration.ImageReference.Sku,
                        Version = _batchConfig.PoolConfig.VmConfiguration.ImageReference.Version
                    },
                    nodeAgentSkuId: _batchConfig.PoolConfig.VmConfiguration.NodeAgentSkuId)
            },

            TaskSlotsPerNode = _batchConfig.PoolConfig.TaskSlotsPerNode,

            NetworkConfiguration = new BatchNetworkConfiguration()
            {
                SubnetId = ResourceIdentifier.Parse(_batchConfig.NetworkConfiguration.SubnetId),
                EnableAcceleratedNetworking = _batchConfig.NetworkConfiguration.AcceleratedNetworking
            },

            StartTask = MapToBatchAccountStartTask(await CreateStartTask()),

            Identity = new ManagedServiceIdentity(ManagedServiceIdentityType.UserAssigned)
            {
                UserAssignedIdentities =
                    { [ResourceIdentifier.Parse(_batchConfig.PoolConfig.UserDefinedManagedIdentityResourceId)] = new() }
            },

            VmSize = _batchConfig.PoolConfig.PoolVmSize,
            TargetNodeCommunicationMode = NodeCommunicationMode.Classic,
            TaskSchedulingNodeFillType = BatchNodeFillType.Spread,

            ScaleSettings = new()
            {
                FixedScale = new()
                {
                    TargetDedicatedNodes = _batchConfig.PoolConfig.DedicatedNodeCount,
                    TargetLowPriorityNodes = _batchConfig.PoolConfig.LowPriorityNodeCount,
                    NodeDeallocationOption = BatchNodeDeallocationOption.Requeue
                }
            }
        };

        var batchAccountPoolCollection = batchAccountResource.GetBatchAccountPools();

        await (await batchAccountPoolCollection.CreateOrUpdateAsync(WaitUntil.Completed,
            batchAccountPoolData.DisplayName,
            batchAccountPoolData)).WaitForCompletionAsync();
    }

```

**Comment by navba-MSFT** [comment]
@kawaiifoxx Thanks for getting back. We will now proceed with closure of this GitHub issue.
