### ISSUE TITLE
[FEATURE REQ] Workload Identity Support for AzureComponentFactory

### ISSUE THREAD

**Issue by wsugarman** [Azure/azure-sdk-for-net#37943]
### Library name

Microsoft.Extensions.Azure

### Please describe the feature.

With the [deprecation of AAD Pod Identity](https://cloudblogs.microsoft.com/opensource/2022/01/18/announcing-azure-active-directory-azure-ad-workload-identity-for-kubernetes/), app developers working in Kubernetes have been migrating to [Azure Workload Identity](https://github.com/Azure/azure-workload-identity). The `Azure.Identity` library now supports a new `WorkloadIdentityCredential` as of version `1.9.0`, and it would great to take advantage of it using the `Microsoft.Extensions.Azure` library.

## Proposal
Add a new possible value for `credential` when creating credentials via `ClientFactory.CreateCredential` in addition to `"managedidentity"` called `"workloadidentity"`. This `credential` value reads settings from both the `IConfiguration` (or section) object as well as the [pre-defined environment variables](https://azure.github.io/azure-workload-identity/docs/quick-start.html#7-deploy-workload) to return a `WorkloadIdentityCredential` object.

## Workaround
Users can continue to use the existing `ManagedIdentityCredential` but instead use the environment variables to leverage the [token exchange](https://github.com/Azure/azure-sdk-for-net/blob/79fd982c0ef9944f113754ec9f17e393b2110f0e/sdk/identity/Azure.Identity/src/TokenExchangeManagedIdentitySource.cs#LL26C11-L26C11).

**Comment by jsquire** [comment]
Hi @wsugarman.  Thank you for reaching out and for your suggestion.  We generally try to keep the named list of config-driven credentials to a small subset of majority use cases.  That said, I don't have a good grasp of how our Identity team views `WorkloadIdentityCredential`, so I'd like to follow-up and have some conversations before we make a decision on this suggestion.  Once we have a sense of where we land, I'll provide an update.

In the meantime, any of the credentials from `Azure.Identity` can be used with the `Microsoft.Extensions.Azure` by calling `UseCredential` on the client builder when registering Azure clients.  For example:

```csharp
builder.Services.AddAzureClients(clientBuilder =>
{
    clientBuilder.AddSecretClient(
        builder.Configuration.GetSection("KeyVault"));

    clientBuilder.AddBlobServiceClient(
        builder.Configuration.GetSection("Storage"));

    clientBuilder.UseCredential(new WorkloadIdentityCredentiall());

    // Set up any default settings
    clientBuilder.ConfigureDefaults(
        builder.Configuration.GetSection("AzureDefaults"));
});
```

**Comment by jsquire** [comment]
//fyi: @christothes, @scottaddie, @JoshLove-msft

**Comment by jsquire** [comment]
Hi @wsugarman.  Thanks for your patience.   After discussion, we're in agreement that this serves a core scenario and is an enhancement that we'd like to include.   Many thanks for your kindness in opening a contribution to implement this.  I left one minor comment there; otherwise, we're good to get things merged in.

**Comment by scottaddie** [comment]
@wsugarman This feature is now documented at https://learn.microsoft.com/dotnet/azure/sdk/authentication/create-token-credentials-from-configuration.
