### ISSUE TITLE
Should indicate that it cannot be used in Isolated Process

### ISSUE THREAD

**Issue by TheCakeMonster** [Azure/azure-sdk-for-net#37957]
This document should perhaps say at the top that the package is not compatible with Azure Functions used in Isolated Process mode; this can only be used with an in-process Azure Functions app.

That might hopefully save people a little time, rather than them trying to use it in Azure Functions being written in, or in my case migrated to, Isolated Process mode.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c4483c61-5340-02ca-4668-9cb8a843cfb5
* Version Independent ID: c60433c0-0752-46b2-08d6-82f67561ccd6
* Content: [Azure WebJobs Storage Blobs client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.storage.blobs-readme?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/microsoft.azure.webjobs.extensions.storage.blobs-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/microsoft.azure.webjobs.extensions.storage.blobs-readme.md)
* Service: **storage**
* GitHub Login: @seanmcc-msft
* Microsoft Alias: **seanmcc**

**Comment by navba-MSFT** [comment]
@TheCakeMonster Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by julienFlexsoft** [comment]
Thank you for this, but what are we supposed to use if we use isolated process? This is the only way to use Azure Functions with .NET 7.
