### ISSUE TITLE
[FEATURE REQ] Async TokenFileCache

### ISSUE THREAD

**Issue by svrooij** [Azure/azure-sdk-for-net#37983]
### Library name

Azure.Identity

### Please describe the feature.

Implement suggestion already in the code as comment? Async file access would maybe give some speed improvement.
https://github.com/Azure/azure-sdk-for-net/blob/b69e9e4a6c437cd96b56a8a8c80a09de3c7f402e/sdk/identity/Azure.Identity/src/TokenExchangeManagedIdentitySource.cs#L50-L84 it specifies that MSAL does not support an async call for the client assertion.

The [linked issue](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2863
) is closed in september 2021. Maybe now is the time to make the entire caching thing asynchronous?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging the team members best able to consider this suggestion.
