### ISSUE TITLE
[BUG] Communication: Unable to query updated policy

### ISSUE THREAD

**Issue by sedashgh** [Azure/azure-sdk-for-net#37982]
### Library name and version

Azure.Communication.JobRouter Beta1

### Describe the bug

One can create a DistributionPolicy with an OfferTtl value in the options class input. However if you want to update an existing policy there is no way to read that value even though there is an options class that can supply that value . This makes it impossible to make a GUI to offer reasonable behavior. 

### Expected behavior

I would expect that the values in creation and update methods be supplied in the read operation

### Actual behavior

Only the Id, Name and DistributionMode are provider in the Get operation

### Reproduction Steps

      RouterAdministrationClient routerAdministrationClient = new RouterAdministrationClient("<CONNECTION STRING>");
      string distributionPolicyId = "my-distribution-policy";

            Response<DistributionPolicy> distributionPolicy = routerAdministrationClient.CreateDistributionPolicy(
                new CreateDistributionPolicyOptions(
                    distributionPolicyId: distributionPolicyId,
                    offerTtl: TimeSpan.FromMinutes(1),
                    mode: new LongestIdleMode())
                {
                    Name = "My distribution policy"
                }
            );

            Response<DistributionPolicy> queriedDistributionPolicy = routerAdministrationClient.GetDistributionPolicy(distributionPolicyId);

            // there is no OfferTtl in the DistributionPolicy returned the following gives a compiler error 
            // there was in previous versions from June 15 2023

### Environment

Visual Studio 2022 17.5.3

**Comment by navba-MSFT** [comment]
@sedashgh Thanks for reaching out to us and reporting this issue. Please refer[ this article](https://azuresdkdocs.blob.core.windows.net/$web/dotnet/Azure.Communication.JobRouter/1.0.0-beta.1/api/Azure.Communication.JobRouter/Azure.Communication.JobRouter.UpdateDistributionPolicyOptions.html) for the UpdateDistributionPolicy.

The [Distribution Policy](https://docs.microsoft.com/azure/communication-services/concepts/router/concepts#distribution-policy) helps to control how jobs are to be distributed to workers with associated queue.

For this example, we are going to create a Longest Idle policy with an **_offer TTL_** set to 1 day. This property specifies The amount of time before an offer expires.

```
Response<DistributionPolicy> distributionPolicy = routerAdministrationClient.CreateDistributionPolicy(
    new CreateDistributionPolicyOptions(
        distributionPolicyId: "distribution-policy-1",
        offerExpiresAfter: TimeSpan.FromDays(1),
        mode: new LongestIdleMode())
);
```
To update the offerExpiresAfter property of a distribution policy, you can modify the UpdateDistributionPolicyOptions object to include the new value for the property. 
```
Response<DistributionPolicy> updatedDistributionPolicy = routerAdministrationClient.UpdateDistributionPolicy(
    new UpdateDistributionPolicyOptions(distributionPolicyId)
    {
        // Update the offerExpiresAfter property to 5 minutes
        OfferExpiresAfter = TimeSpan.FromMinutes(5),
    });

Console.WriteLine($"Distribution policy successfully updated with new offerExpiresAfter value. Offer Expires After: {updatedDistributionPolicy.Value.OfferExpiresAfter}");
```
Could you please check if this helps ?

**Comment by sedashgh** [comment]
There is no problem with updating the time. The problem is writing an application that allows editing of the Distribution Policy. If you cannot read the previous value of the offerTtl the user does not know if they should change the update time. They can only know by looking at the logs of an offer which times out and make a calculation. This is hardly the desired behavior of an application used for managing policies/entities in JobRouter. This particular value was available in previous previews of Job Router. I have not checked the other entities for similar missing values in the Read/Query operation.

**Comment by navba-MSFT** [comment]
@sedashgh Thanks for getting back. Could you please check if you can use the **[ListDistributionPolicies](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/communication/Azure.Communication.JobRouter/samples/DistributionPolicyCrud.md#list-distribution-policies)** method to retrieve a list of all DistributionPolicy objects and their properties, including the OfferTtl value. You can then filter the list to find the DistributionPolicy object that you want to update and retrieve its OfferTtl value.


```
using Azure.Communication.JobRouter;
using Azure.Communication.JobRouter.Models;

RouterAdministrationClient routerAdministrationClient = new RouterAdministrationClient("<CONNECTION STRING>");

// Retrieve a list of all the existing DistributionPolicy objects
AsyncPageable<DistributionPolicy> distributionPolicies = routerAdministrationClient.ListDistributionPoliciesAsync();

// Iterate through the list to find the DistributionPolicy object with the matching Id
await foreach (DistributionPolicy distributionPolicy in distributionPolicies)
{
    if (distributionPolicy.Id == distributionPolicyId)
    {
        // Retrieve the OfferTtl value from the DistributionPolicy object
        TimeSpan offerTtl = distributionPolicy.OfferTtl;
        Console.WriteLine($"OfferTtl: {offerTtl}");
        break;
    }
}
```

**Comment by sedashgh** [comment]
Actually using Beta1 the code you have supplied is not supported. I have supplied the code that uses the correct functions below and the compile error is still the same on the line (TimeSpan offerTtl = distributionPolicyItem.DistributionPolicy.OfferTtl) 

async void Test(string distributionPolicyId)
{

    JobRouterAdministrationClient routerAdministrationClient = new JobRouterAdministrationClient("<CONNECTION STRING>");

    // Retrieve a list of all the existing DistributionPolicy objects
    AsyncPageable<DistributionPolicyItem> distributionPolicies = routerAdministrationClient.GetDistributionPoliciesAsync();

    // Iterate through the list to find the DistributionPolicy object with the matching Id
    await foreach (DistributionPolicyItem distributionPolicyItem in distributionPolicies)
    {
        if (distributionPolicyItem.DistributionPolicy.Id == distributionPolicyId)
        {
            // Retrieve the OfferTtl value from the DistributionPolicy object
            TimeSpan offerTtl = distributionPolicyItem.DistributionPolicy.OfferTtl;
            Console.WriteLine($"OfferTtl: {offerTtl}");
            break;
        }
    }

}

**Comment by navba-MSFT** [comment]
@sedashgh Thanks for getting back. Could you confirm if you are observing the same by using the `GetDistributionPolicyAsync `method instead of GetDistributionPolicy to retrieve the DistributionPolicy object asynchronously. This method returns a Response<DistributionPolicy> object that contains the OfferTtl property. 

```
async void Test(string distributionPolicyId)
{
    JobRouterAdministrationClient routerAdministrationClient = new JobRouterAdministrationClient("<CONNECTION STRING>");

    // Retrieve the DistributionPolicy object with the matching Id
    Response<DistributionPolicy> distributionPolicy = await routerAdministrationClient.GetDistributionPolicyAsync(distributionPolicyId);

    // Retrieve the OfferTtl value from the DistributionPolicy object
    TimeSpan offerTtl = distributionPolicy.Value.OfferTtl;
    Console.WriteLine($"OfferTtl: {offerTtl}");
}
```

**Comment by sedashgh** [comment]
I have tried that and it does not help. The problem is with the compiler error referring to DistributionPolicy class member. I have enclosed a screen shot of the compiler as well as the test project and code.
![CompilerError](https://github.com/Azure/azure-sdk-for-net/assets/62701063/5e5cf175-fe70-4cf6-955e-f3e884cf0958)
[DistributionPolicyProject.zip](https://github.com/Azure/azure-sdk-for-net/files/12259058/DistributionPolicyProject.zip)

**Comment by sedashgh** [comment]
I have tried some of the older versions of JobRouter and the problem was started in the pre-release version 1.0.0-alpha.20230619.1. The version before 1.0.0-alpha.20230615.1 does not have the problem.

**Comment by navba-MSFT** [comment]
@sedashgh Thanks for clarifying. I am checking this further. I will get back once I have an update.
