### ISSUE TITLE
[QUERY] How do you set Adaptive Sampling Off in Azure Monitor Trace Exporter

### ISSUE THREAD

**Issue by joebeernink** [Azure/azure-sdk-for-net#37991]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.13

### Query/Question

I'm trying to figure out how to turn off adaptive sampling in a .net core console application when using Azure.Monitor.OpenTelemetry.Exporter 1.0.0-beta.13.

I just don't see any kind of configuration option in the Diagnostics, or anywhere else in the trace exporter.				.WithTracing(builder => builder
					.AddConsoleExporter()
					.AddAzureMonitorTraceExporter(o =>
					{
						o.ConnectionString = appInsightsConnection;
						o.Diagnostics.IsDistributedTracingEnabled = true;
					}))

I tried setting it directly in the ApplicationInsights section of my config file, but that didn't work either

  "Logging": {
    "LogLevel": {
      "Default": "Information"
    },
    "ApplicationInsights": {
      "LogLevel": {
        "Default": "Information"
      },
      "EnableAdaptiveSampling": false,
    }
  },
  
  Any ideas?

### Environment

Visual Studio 2022.17.6.5 running on Windows 11

**Comment by vishweshbankwar** [comment]
@joebeernink Adaptive sampling is not supported in Azure Monitor exporter. Only fixed-rate sampling is supported. https://learn.microsoft.com/en-us/azure/azure-monitor/app/opentelemetry-configuration?tabs=aspnetcore#enable-sampling

**Comment by joebeernink** [comment]
So I've set my fixed-rate sample to 1.0F, but somewhere my traces are still being throttled:

				.WithTracing(builder => builder
					.AddConsoleExporter()
					.AddAzureMonitorTraceExporter(o =>
					{
						o.ConnectionString = appInsightsConnection;
						o.Diagnostics.IsDistributedTracingEnabled = true;
                        o.SamplingRatio = 1.0F;
					}))
					
My process is a batch process with a large burst over a few minutes every couple of hours. Need a way to get all the traces during each run.

**Comment by joebeernink** [comment]
I found the issue...

I was still using the ApplicationInsights SDK for metrics (TelemetryClient). Loading both the AzureMonitorOpenTelemetryExporter and the App Insights SDK forces Adaptive Sampling to kick in, even if you aren't using the SDK's tracing... Once I removed all references to the App Insights SDK by converting from TelemetryClient to System.Diagnostics.Meters, the throttling went away, and I could see all of my logs.
