### ISSUE TITLE
[FEATURE REQ] Request to add functionality to extend webhook expiry date

### ISSUE THREAD

**Issue by krishna85s** [Azure/azure-sdk-for-net#38028]
### Library name

Azure.ResourceManager.Automation

### Please describe the feature.

The request is to allow for an expiry date extension using the AutomationWebhookPatch class, as there's currently no option to update any other properties not on the AutomationWebhookPatch class. This would be very useful because a lot of our webhooks expire and they end up breaking some of our workflows. To be able to automate the extension would be really helpful. Thanks.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @krishna85s, this is a new feature ask for the Automation service, that we can't help as this repository is focused on the Azure SDK for .NET and we're unable to assist with Azure service issues.
Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). 
This issue will be closed now, but if you think that I’ve not addressed your problem correctly, please don’t hesitate to comment and we’ll be glad to assist you further.
