### ISSUE TITLE
[QUERY] Creating ContainerApp with link to Azure ContainerRegistry

### ISSUE THREAD

**Issue by Arcalise08** [Azure/azure-sdk-for-net#38033]
### Library name and version

Azure.ResourceManager.AppContainers 1.0.3 & Azure.ResourceManager.ContainerRegistry 1.1.0

### Query/Question

There seems to be a little confusion here on how `Azure.ResourceManager.AppContainers` and `Azure.ResourceManager.ContainerRegistry` work together. 

Heres some proto code to show what I'm talking about.

``` csharp
//so we load our container registry
var registries = await arm.GetContainerRegistriesAsync();
//then we select the first registry
var registry = registries.First();
//then create a new container app configuration
var appConfig = new ContainerAppConfiguration()
{
    Ingress =
        {
            AllowInsecure = false,
            TargetPort = service.dockerProfile.InternalPort,
            ExposedPort = service.dockerProfile.ExternalPort,
            Transport = Azure.ResourceManager.AppContainers.Models.ContainerAppIngressTransportMethod.Http,
            External = service.dockerProfile.ExternalPort is not null
        },
    Registries =
    {
        //It is unclear how to use the above registry here
    }
};

var container = await arm.CreateContainerApp(service.containerAppName, new(Azure.Core.AzureLocation.SouthCentralUS)
{
    EnvironmentId = environment.Id,
    Configuration = appConfig
});
```

If someone can answer this I'd be happy to throw up some documentation so its not asked again. I couldnt find any documentation on this.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@Juliehzl Please help on this question.

**Comment by Juliehzl** [comment]
Registries =
                        {
                            new ContainerAppRegistryCredentials
                            {
                                Server = <servername>,
                                Username = <username>,
                                PasswordSecretRef = <password>
                            }
                        }
