### ISSUE TITLE
[QUERY]

### ISSUE THREAD

**Issue by chkp-swapnil-dhage** [Azure/azure-sdk-for-net#38030]
### Library name and version

Azure.ResourceManager.Network

### Query/Question

Currently, I'm working on upgrading the Azure SDK from Microsoft.Azure.Management.Network to Azure.ResourceManager.Network.
I'm facing an issue finding replacements in the new SDK for the following two calls: 
•	[NetworkManagementClient.NetworkInterfaces.ListVirtualMachineScaleSetNetworkInterfacesAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.network.networkinterfacesoperationsextensions.listvirtualmachinescalesetnetworkinterfacesasync?view=azure-dotnet#microsoft-azure-management-network-networkinterfacesoperationsextensions-listvirtualmachinescalesetnetworkinterfacesasync(microsoft-azure-management-network-inetworkinterfacesoperations-system-string-system-string-system-threading-cancellationtoken)) 
•	[NetworkManagementClient.PublicIPAddresses.ListVirtualMachineScaleSetPublicIPAddressesAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.network.publicipaddressesoperationsextensions.listvirtualmachinescalesetpublicipaddressesasync?view=azure-dotnet#microsoft-azure-management-network-publicipaddressesoperationsextensions-listvirtualmachinescalesetpublicipaddressesasync(microsoft-azure-management-network-ipublicipaddressesoperations-system-string-system-string-system-threading-cancellationtoken))
 
Could you please assist me in figuring out the alternate implementation provided in the newer SDK for these

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @chkp-swapnil-dhage , we're working on these features, and you can track our progress on this https://github.com/Azure/azure-sdk-for-net/issues/35717 .

**Comment by chkp-swapnil-dhage** [comment]
Hello @ArthurMa1978,
So, we intend to tackle both, List VirtualMachineScaleSet's NetworkInterfacesAsync and PublicIPAddressesAsync, is that correct? Furthermore, could you provide a tentative timeline for this? We're currently in the midst of making changes to these affected methods.
Thank you.

**Comment by ArthurMa1978** [comment]
We have released new [version](https://www.nuget.org/packages/Azure.ResourceManager.Network/1.6.0-beta.1) for the VMSS.
