### ISSUE TITLE
[QUERY] Is it expected that WithCredential work when calling AddEventHubProducerClient?

### ISSUE THREAD

**Issue by drmohundro** [Azure/azure-sdk-for-net#38034]
### Library name and version

Azure.Messaging.EventHubs 5.9.2

### Query/Question

I'm attempting to use Azure Event Hubs like so:

```cs
    builder.Services.AddAzureClients(
        b =>
        {
            b.AddEventHubProducerClient(builder.Configuration.GetConnectionString("EventHub"))
                .WithCredential(new DefaultAzureCredential());
        }
    );
```

However, I'm getting an exception thrown from `EventHubsConnectionStringProperties.Parse` which is called from the `EventHubProducerClient` constructor that doesn't get a credential. It seems that the `EventHubsConnectionStringProperties.Parse` method isn't called if a credential is passed to the `EventHubProducerClient` constructor, though, but I'm not finding another way to specify a credential when using the `AddEventHubProducerClient` method. I just want to verify that I'm using it as expected. It seems that I'll have to register the `EventHubProducerClient` manually if I want to use identity instead of a shared access key or signature.

### Environment

```.NET SDK:
 Version:   7.0.302
 Commit:    990cf98a27

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.302/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  5.0.408 [/usr/local/share/dotnet/sdk]
  6.0.408 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.17 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by jsquire** [comment]
Hi @drmohundro.  Thanks for reaching out and we regret that you're experiencing difficulties.  To register a producer using a credential, you'd want to call the `AddEventHubProducerClientWithNamespace` method.   This would look something like:

```csharp
var fullyQualifiedNamespace = "<< FULLY-QUALIFIED EVENT HUBS NAMESPACE (like something.servicebus.windows.net) >>";

public void ConfigureServices(IServiceCollection services)
{
    services.AddAzureClients(builder =>
    {
        // This will register the EventHubProducerClient using the default credential.
        builder.AddEventHubProducerClientWithNamespace(fullyQualifiedNamespace);

        // By default, DefaultAzureCredential is used, which is likely desired for most
        // scenarios. If you need to restrict to a specific credential instance, you could
        // register that instance as the default credential instead.
        builder.UseCredential(new ManagedIdentityCredential());
    });
  
    services.AddControllers();
}
```

Some discussion and examples for registering the Event Hubs clients can be found on its [Overview](https://learn.microsoft.com/dotnet/api/overview/azure/messaging.eventhubs-readme?view=azure-dotnet#registering-with-aspnet-core-dependency-injection) page.  More in-depth discussion and examples can be found in [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection?tabs=web-app-builder).

**Comment by drmohundro** [comment]
Thanks @jsquire - I should have kept digging. I must have had tunnel vision, though, because I had even been on that page. Appreciate it!
