### ISSUE TITLE
[FEATURE REQ] Ability to get UniquiId  of a file share in the Storage Account

### ISSUE THREAD

**Issue by hoainam3003** [Azure/azure-sdk-for-net#38055]
### Library name

Azure.ResourceManager.Storage

### Please describe the feature.

For now, there is no way to get the UniqueId of file share in a storage account. I see the UniqueId is needed for the protected item name in the backup/restore functionality. Please make it available like xMsSnapshot in this function but with a new parameter named _**"x-ms-file-share-unique-identifier"**_
  
 public virtual async Task<Response<FileShareResource>> GetAsync(string shareName, string expand = null, string xMsSnapshot = null, CancellationToken cancellationToken = default)

and CreateGetRequest function should append it. 

internal HttpMessage CreateGetRequest(string subscriptionId, string resourceGroupName, string accountName, string shareName, string expand, string xMsSnapshot, **bool xMsFileShareUniqueIdentifier)**
        {
            var message = _pipeline.CreateMessage();
            var request = message.Request;
            request.Method = RequestMethod.Get;
            var uri = new RawRequestUriBuilder();
            uri.Reset(_endpoint);
            uri.AppendPath("/subscriptions/", false);
            uri.AppendPath(subscriptionId, true);
            uri.AppendPath("/resourceGroups/", false);
            uri.AppendPath(resourceGroupName, true);
            uri.AppendPath("/providers/Microsoft.Storage/storageAccounts/", false);
            uri.AppendPath(accountName, true);
            uri.AppendPath("/fileServices/default/shares/", false);
            uri.AppendPath(shareName, true);
            uri.AppendQuery("api-version", _apiVersion, true);
            if (expand != null)
            {
                uri.AppendQuery("$expand", expand, true);
            }
            request.Uri = uri;
            if (xMsSnapshot != null)
            {
                request.Headers.Add("x-ms-snapshot", xMsSnapshot);
            }
           _**if (xMsFileShareUniqueIdentifier== true)
            {
                request.Headers.Add("x-ms-include-file-share-unique-identifier", "true");
            }**_
            request.Headers.Add("Accept", "application/json");
            _userAgent.Apply(message);
            return message;
        }

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
