### ISSUE TITLE
[BUG] Azure.ResourceManager.OperationalInsights: FormatException when purging Log Analytics Workspace data

### ISSUE THREAD

**Issue by gastonmuijtjens** [Azure/azure-sdk-for-net#38051]
### Library name and version

Azure.ResourceManager.OperationalInsights 1.1.0 and 1.2.0-beta.1

### Describe the bug

In my .NET project I am using the `Azure.ResourceManager.OperationInsights` package to purge Log Analytics Workspace data:

```csharp
var armClient = new ArmClient(new DefaultAzureCredential());
var subscription = await armClient.GetDefaultSubscriptionAsync().ConfigureAwait(false);
var resourceGroupResponse = await subscription.GetResourceGroupAsync("<resource_group_name>").ConfigureAwait(false);
if (resourceGroupResponse.HasValue)
{
    var operationalInsightsWorkspaceResponse = await resourceGroupResponse.Value.GetOperationalInsightsWorkspaceAsync("<ai_workspace_name>").ConfigureAwait(false);
    if (operationalInsightsWorkspaceResponse.HasValue)
    {
        var operationalInsightsWorkspace = operationalInsightsWorkspaceResponse.Value;
        var retentionDate = DateTimeOffset.UtcNow;
        var purgeContent = new OperationalInsightsWorkspacePurgeContent("AppDependencies", new[]
        {
            new OperationalInsightsWorkspacePurgeFilter
            {
                Column = "TimeGenerated",
                Operator = "<",
                Value = BinaryData.FromObjectAsJson(retentionDate.ToString("s", CultureInfo.InvariantCulture))
            }
        });


       var purgeResponse = await operationalInsightsWorkspaceResource.PurgeAsync(purgeContent).ConfigureAwait(false);
       Console.WriteLine(purgeResponse.Value.OperationId);
    }
}
```

When executing this code, I get the following exception:

```
System.FormatException: One of the identified items was in an invalid format.
   at System.Text.Json.JsonElement.GetGuid()
   at Azure.ResourceManager.OperationalInsights.Models.OperationalInsightsWorkspacePurgeResult.DeserializeOperationalInsightsWorkspacePurgeResult(JsonElement element)
   at Azure.ResourceManager.OperationalInsights.WorkspacePurgeRestOperations.PurgeAsync(String subscriptionId, String resourceGroupName, String workspaceName, OperationalInsightsWorkspacePurgeContent content, CancellationToken cancellationToken)
   at Azure.ResourceManager.OperationalInsights.OperationalInsightsWorkspaceResource.PurgeAsync(OperationalInsightsWorkspacePurgeContent content, CancellationToken cancellationToken)
```

When debugging the internal library code, I can see that the purge request is successfully sent, but it goes wrong when parsing the JSON result of the Azure Resource API response. The library expects the `operationId` property to be a `Guid`, but instead it has the following format: `purge-d2b72997-e1ee-43f5-bb6d-cfe8f47a2f47`, hence it throws a `FormatException`.

### Expected behavior

The response returned by the `Purge` method does not throw an exception and returns the `operationId` which can be used in the request to retrieve the status.

### Actual behavior

A `System.FormatException` is thrown because the `operationId` on the Resource Manager API has a `purge` prefix appended to the Guid, which cannot be parsed in `OperationalInsightsWorkspacePurgeResult.DeserializeOperationalInsightsWorkspacePurgeResult`.

### Reproduction Steps

1. Install the `Azure.ResourceManager.OperationInsights` NuGet package
2. Initiate an `ArmClient`
3. Using the client, retrieve the `OperationalInsightsWorkspaceResource`
4. Call the `PurgeAsync` method on `OperationalInsightsWorkspaceResource`

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.412
 Commit:    ee124f7fe1

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  13.5
 OS Platform: Darwin
 RID:         osx.13-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.412/

Host:
  Version:      7.0.9
  Architecture: arm64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.412 [/usr/local/share/dotnet/sdk]
  7.0.306 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /<path>/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by gastonmuijtjens** [comment]
Any update on this? This bug unfortunately prevents us from using this NuGet package.
