### ISSUE TITLE
[BUG] Azure.ResourceManager.ApiManagement "Requested operation requires an element of type 'String', but the target element has type 'Number'" when using GetReportsByRequestAsync.

### ISSUE THREAD

**Issue by AndresZunigaU** [Azure/azure-sdk-for-net#38076]
### Library name and version

Azure.ResourceManager.ApiManagement 1.0.1

### Describe the bug

When trying to use the GetReportsByRequestAsync() function, the request fails and gives the error "Requested operation requires an element of type 'String', but the target element has type 'Number'".

After some investigation we were able to see that the "BackendResponseCode" property is returned as an int when calling the API:

![Example](https://github.com/Azure/azure-sdk-for-net/assets/71027035/0f573202-570b-48a1-ac1d-9d00583bb1ec)

But based on the code for the call, its expecting a string value:
https://github.com/Azure/azure-sdk-for-net/blob/2684d2c215c68f6cfa6c8992124eaf1b78826395/sdk/apimanagement/Azure.ResourceManager.ApiManagement/src/Generated/Models/RequestReportRecordContract.Serialization.cs#L30C13-L30C60

![Code](https://github.com/Azure/azure-sdk-for-net/assets/71027035/3933c302-1fd5-40bd-a320-a97bdd1942c2)

In this case, it should be configured to use an int, just like the "responseCode" property is configured.

### Expected behavior

Reports are returned based on the filter provided.

### Actual behavior

Program flow is halted and error is returned.

### Reproduction Steps

Using the following code:

`static async Task Main()
        {
            // get azure access token
            TokenCredential cred = new DefaultAzureCredential();
            // authenticate your client
            ArmClient client = new ArmClient(cred);

 

            //Resource information.
            string subscriptionId = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxx";
            string resourceGroupName = "xxxxxxx";
            string serviceName = "xxxxxxxxx";

 

            //Get resource
            ResourceIdentifier apiManagementServiceResourceId = ApiManagementServiceResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, serviceName);
            ApiManagementServiceResource apiManagementService = client.GetApiManagementServiceResource(apiManagementServiceResourceId);

 

            //Set filter and get reports.
            var filter = "timestamp ge datetime'2022-07-20T00:00:00.000Z' and timestamp le datetime'2023-07-20T23:59:59.999Z'";
            var records = await apiManagementService.GetReportsByRequestAsync(filter).ToListAsync();

 

            //Sample print
            Console.WriteLine(records);
        }`

Error returned:

![Error](https://github.com/Azure/azure-sdk-for-net/assets/71027035/4c51ec39-77b6-4bd8-a49c-d0854b611b1b)

### Environment

Visual Studio 2022
Console App

.NET SDK:
Version:   7.0.306
Commit:    f500069cb7

Runtime Environment:
OS Name:     Windows
OS Version:  10.0.19045
OS Platform: Windows
RID:         win10-x64
Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  5.0.201 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
https://aka.ms/dotnet/info

Download .NET:
https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
