### ISSUE TITLE
[FEATURE REQ] Secondary Subdivions should show up when Municipality cross secondary subdivision borders

### ISSUE THREAD

**Issue by chassq** [Azure/azure-sdk-for-net#38074]
### Library name

Azure.Maps.Search;

### Please describe the feature.

We are seeing some Municipalities coming back with no Country Secondary Subdivision in the Address part of the search results. For example, the town of Hickory, NC USA is in Catawba county primary although the towns borders do cross to other county borders. However, when we search Hickory, NC no country secondary subdivision is returned.

If, for example, we looked in geonames.org (e.g., go to the http://api.geonames.org website and use the following url in the browser address bar: http://api.geonames.org/hierarchy?geonameId=4470778&username=demo). The ADM2 value is Catawba county.

Not sure exactly why Azure Maps does not carry this properly, but it does seem wrong not to show country secondary subdivisions when the exists. Also, if there are multiple can you show a comma separated list?

Thanks!

**Comment by jsquire** [comment]
Hi @chassq.  Thank you for reaching out and for your feedback.  The Azure Maps client library has no influence nor control over the data that is returned for a search - it just presents what the service has given it.  The enhancements that you're suggesting would need to be applied to the service.  Unfortunately, this repository is focused on the Azure SDK for .NET and we're unable to assist with service feature suggestions.  Your best path forward would be to share your feedback in the [Azure Maps feedback forum](https://feedback.azure.com/d365community/forum/fc834083-0925-ec11-b6e6-000d3a4f09d0) or to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
