### ISSUE TITLE
[BUG] Monitor Query old service version causing error

### ISSUE THREAD

**Issue by daveyg1138** [Azure/azure-sdk-for-net#38082]
### Library name and version

Azure.Monitor.Query

### Describe the bug

The Azure Monitor client libraries have a ServiceVersion of '2018-01-01' and this results in an error when querying metrics for a resource provider that don't include this in their list of supported API versions

### Expected behavior

I suppose this is the expected behaviour when the resource provider's earliest API version is later than that of the client but I'd also expect the latest release of the client libraries to have a more up to date API version

### Actual behavior

I'm trying to query metrics of a DB Server using the Microsoft.DBforPostgreSQL resource provider but I get an error indicating that this isn't possible due to the API version hardcoded into the client libraries not being supported by that provider

    "No registered resource provider found for location 'northeurope' and API version '2018-01-01' for type 'flexibleServers'"

A listing of the API versions using Azure CLI follows

az provider show --namespace Microsoft.DBforPostgreSQL --query "resourceTypes[?resourceType=='operations'].apiVersions"
[
  [
    "2023-03-01-preview",
    "2022-12-01",
    "2022-11-01-preview",
    "2022-05-01-privatepreview",
    "2022-05-01-preview",
    "2022-03-08-preview",
    "2022-01-20-preview",
    "2021-06-01-preview",
    "2021-06-01"
  ]
]

Why is the ServiceVersion found at Azure.Monitor.Query.MetricsQueryClientOptions so old (2018-01-01)?

### Reproduction Steps

Try retrieving metrics using ".../providers/Microsoft.DBforPostgreSQL/flexibleServers..." using the Azure Monitor client libraries and you should get the message

### Environment

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.4.4
-------------------
Azure Monitor Query package 1.2.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ajuch** [comment]
I have the same problem when querying some AppInsights metrics:
```
{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'westeurope' and API version '2018-01-01' for type 'components'. The supported api-versions are '2014-04-01, 2014-08-01, 2014-12-01-preview, 2015-05-01, 2018-05-01-preview, 2020-02-02-preview, 2020-02-02'. The supported locations are 'eastus, southcentralus, northeurope, westeurope, southeastasia, westus2, uksouth, canadacentral, centralindia, japaneast, australiaeast, koreacentral, francecentral, centralus, eastus2, eastasia, westus, southafricanorth, northcentralus, brazilsouth, switzerlandnorth, norwayeast, norwaywest, australiasoutheast, australiacentral2, germanywestcentral, switzerlandwest, uaecentral, ukwest, japanwest, brazilsoutheast, uaenorth, australiacentral, francesouth, southindia, westus3, koreasouth, swedencentral, canadaeast, jioindiacentral, jioindiawest, qatarcentral, southafricawest, germanynorth, polandcentral, israelcentral, italynorth'."}}
```

Resource is ``/subscriptions/---/resourceGroups/---/providers/microsoft.insights/components/---/providers/microsoft.insights``

**Comment by daveyg1138** [comment]
I've recently tested this against Postgres using the latest Azure.Monitor.Query library 1.4 and it seems to be working. The ServiceVersion for MetricsQueryClientOptions still appears to be 2018-01-01 so perhaps this wasn't my issue after all. 

This command still returns the same result too

`az` provider show --namespace Microsoft.DBforPostgreSQL --query "resourceTypes[?resourceType=='operations'].apiVersions"`

The only differences are a later version of the Azure Monitor client libraries and connecting to a different Postgres resource.

Regardless, it's now working so I'm happy for this to be closed
