### ISSUE TITLE
[BUG] Azure Maps Pushpin Color not interpreted correctly

### ISSUE THREAD

**Issue by AlexanderTrusheim** [Azure/azure-sdk-for-net#38100]
### Library name and version

Azure.Maps.Rendering 1.0.0-beta.2

### Describe the bug

The SDK does not forward color information for pushpins correctly to Azure Maps. Pushpins appear in different colors than expected.

Currently, in azure-sdk-for-net/sdk/maps/Azure.Maps.Rendering/src/Models/ImagePushpinStyle.cs, the pushpin color information is extracted, but unfortunately the alpha value is also used for the blue component, instead of the blue value:

`sb.AppendFormat(CultureInfo.InvariantCulture, "|co{0:X2}{1:X2}{2:X2}",
                    PushpinColor?.R, PushpinColor?.G, **PushpinColor?.A**);`

### Expected behavior

A Pushpin should be rendered in the color (ARGB) that was assigned to it through the SDK.

### Actual behavior

Instead of using rendering the Pushpin using the A,R,G,B values, they are rendered as A,R,G,A. The blue value is lost and the alpha value is used twice.

### Reproduction Steps

There is a repro example in the actual documentation of the service. 
I'm just quoting it from there (azure-sdk-for-net/sdk/maps/Azure.Maps.Rendering/samples /MapsRenderingTilesImageriesImagesSamples.md):

```
// Prepare pushpin styles
ImagePushpinStyle pushpinSet1 = new ImagePushpinStyle(
    new List<PushpinPosition>()
    {
        new PushpinPosition(13.35, 52.577, "Label start"),
        new PushpinPosition(13.2988, 52.6, "Label end"),
    }
)
{
    PushpinScaleRatio = 0.9,
    PushpinColor = Color.Red,
    LabelColor = Color.Blue,
    LabelScaleRatio = 18
};
ImagePushpinStyle pushpinSet2 = new ImagePushpinStyle(
    new List<PushpinPosition>() {new PushpinPosition(13.495, 52.497, "Label 3")}
)
{
    PushpinScaleRatio = 1.2,
    PushpinColor = Color.Beige,
    LabelColor = Color.White,
    LabelScaleRatio = 18
};

// Prepare path styles
ImagePathStyle path1 = new ImagePathStyle(
    new List<GeoPosition>() {
        new GeoPosition(13.35, 52.577),
        new GeoPosition(13.2988, 52.6)
    }
)
{
    LineColor = Color.Beige,
    LineWidthInPixels = 5
};

// Prepare static image options
GetMapStaticImageOptions staticImageOptions = new GetMapStaticImageOptions(
    new GeoBoundingBox(13.228, 52.4559, 13.5794, 52.629),
    new List<ImagePushpinStyle>() { pushpinSet1, pushpinSet2 },
    new List<ImagePathStyle>() { path1 }
)
{
    MapImageLayer = MapImageLayer.Basic,
    MapImageStyle = MapImageStyle.Dark,
    ZoomLevel = 10,
    Language = RenderingLanguage.EnglishUsa
};

// Get static image
Response<Stream> image = client.GetMapStaticImage(staticImageOptions);

// Prepare a file stream to save the imagery
using (FileStream fileStream = File.Create(".\\BerlinStaticImageWithPinsAndPaths.png"))
{
    image.Value.CopyTo(fileStream);
}
```

In the example, the Pushpin colors are set to Color.Red, so (255, 255, 0, 0). 

You can see the result here: https://github.com/Azure/azure-sdk-for-net/raw/main/sdk/maps/Azure.Maps.Rendering/tests/BerlinStaticImageWithPinsAndPaths.png?raw=true

The Pushpins appear in pink, (255, 255, 0, 255), because the alpha value is taken as blue.

### Environment

The issue is independent of the environment, but I'm on a MacOS Ventura device, using the 8.0.100-preview.6.23330.14 .NET SDK and VS Code 1.80.2.

**Comment by dunxz** [comment]
+1

**Comment by DavidThielen** [comment]
I hit this problem too - [detailed here](https://stackoverflow.com/questions/77693777/azure-maps-pin-color-is-wrong?noredirect=1#comment136971655_77693777)

**Comment by dubiety** [comment]
Hi @AlexanderTrusheim  and @DavidThielen , We're looking into this issue and will get back to you soon! Thank you for reporting this issue.
