### ISSUE TITLE
[BUG] Azure migrating from old to new management SDK - Virtual Machine Scale Set missing functionality

### ISSUE THREAD

**Issue by hod-harush** [Azure/azure-sdk-for-net#38156]
### Library name and version

Azure.ResourceManager.Network 1.4.0

### Describe the bug

you are soon deprecate the Azure.Management.Network SDK and migrating to new SDK called: Azure.ResourceManager.Network SDK.
Based on my research, the new SDK doesn't support calls for "ListVirtualMachineScaleSetNetworkInterfaces" and "ListVirtualMachineScaleSetPublicIPAddresses". And not provide any equivalent functionality.
Attached pictures of the old sdk (Azure.Management.Network) that shows this functionality:
![aaaa](https://github.com/Azure/azure-sdk-for-net/assets/73786051/8cba1755-1388-4e40-9f08-5f3baa4d3812)
![bbbb](https://github.com/Azure/azure-sdk-for-net/assets/73786051/d744d8c8-805c-4ae9-a1d4-c0395e8b0c02)

### Expected behavior

we expect that the new SDK will provide this functionality or give us an alternative way to achieve this functionality in simple way until the old SDK will deprecated.

### Actual behavior

Right now, there is no alternative way to achieve this functionality in the new sdk - Azure.ResourceManager.Network

### Reproduction Steps

with Azure.Management.Network SDK:

var client = await GetAzureClient(); // NetworkManagementClient client - skip the initialization of the client) 
var response = await client.NetworkInterfaces.ListVirtualMachineScaleSetNetworkInterfacesAsync(resourceGroupName, scaleSetName);
// and even get the next page
while (!string.IsNullOrEmpty(response.NextPageLink))
{
                response = await client.NetworkInterfaces.ListVirtualMachineScaleSetNetworkInterfacesNextAsync(response.NextPageLink);
}

same with public ips of virtual machine scale set:
            var client = await GetAzureClient();
            var response = client.PublicIPAddresses.ListVirtualMachineScaleSetPublicIPAddressesAsync(resourceGroupName, scaleSetName);
// and even get the next page
            while (!string.IsNullOrEmpty(response.NextPageLink))
            {
                response = await client.PublicIPAddresses.ListVirtualMachineScaleSetPublicIPAddressesNextAsync(response.NextPageLink);
            }

With the Azure.ResourceManager.Network SDK we can't achieve this functionality

### Environment

.NET 5.0
Visual Studio Professional 2022

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@hod-harush, yes, all VMSS functsions are still in developing, here is https://github.com/Azure/azure-sdk-for-net/issues/35717 opened to track this feature.
I will let you know once it's done, thank you for your feedback.

**Comment by ArthurMa1978** [comment]
We have released new [version](https://www.nuget.org/packages/Azure.ResourceManager.Network/1.6.0-beta.1) for the VMSS.
