### ISSUE TITLE
[FEATURE REQ] MaxConcurrentCallsPerSession on Session Enabled ServiceBus Azure Function Triggers

### ISSUE THREAD

**Issue by gorillapower** [Azure/azure-sdk-for-net#38157]
### Library name

Microsoft.Azure.WebJobs.Extensions.ServiceBus

### Please describe the feature.

Our application requires the use of Servicebus Sessions and also the ability to process messages in parallel. 

After inspecting the `Microsoft.Azure.WebJobs.Extensions.ServiceBus` library, I can see that the `MaxConcurrentCallsPerSession` property is ignored for session enabled servicebus triggers and the default is 1.
https://github.com/Azure/azure-sdk-for-net/blob/8b00e33451e2dcd984de8213f5ef0ae8fa95399b/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Config/ServiceBusOptions.cs#L287

Would it be possible to open up this setting to allow the procesing of session based messages in parallel?

While it is possible to make use of the `ServiceBusReceiveActions` to pull additional messages, enabling this option would allow a much more optimal solution using azure functions with its scalability features and avoid us having to roll our own solution.

**Comment by JoshLove-msft** [comment]
I think we can potentially expose this option, but will need to think through how it should interact with Dynamic Concurrency - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Microsoft.Azure.WebJobs.Extensions.ServiceBus/src/Listeners/ServiceBusListener.cs#L924-L926.

/cc @mathewc

**Comment by gorillapower** [comment]
@JoshLove-msft just FYI as a work around, I'm currently running a modified version of the library that sets the `MaxConcurrentCallsPerSession` property to the configured `MaxConcurrentCalls` host.json setting. This will then flow through to the `SessionMessageProcessor`

Its working well so far.

![image](https://github.com/Azure/azure-sdk-for-net/assets/8879065/0cb88f5c-c863-4874-817b-27beeb666c75)
