### ISSUE TITLE
[QUERY] Limit responses to you data content not working 

### ISSUE THREAD

**Issue by JoacimWall** [Azure/azure-sdk-for-net#38152]
### Library name and version

Azure.Ai.OpenAi preview 6

### Query/Question

Hi
when I use the Azure Ai studio this works but if I use the Deployment from my app the responses is not limited to my data content. 

I use it like this. is there any flag or parameter that I missing. 
using Azure.AI.OpenAI;
OpenAIClient client = new OpenAIClient(new Uri("https://xxxxxx.liberoopenaitest.openai.azure.com/")

//Joacim

### Environment

Xamarin app iOS.

**Comment by trrwilson** [comment]
Hello! Thank you for contacting us. The Azure OpenAI client libraries don't yet support the new "with your data" feature, but that's under very active development and should arrive in a new version soon.

We'll be sure to update the readme file with example usage and get pages like the [quickstart on learn.microsoft.com](https://learn.microsoft.com/azure/ai-services/openai/use-your-data-quickstart) updated as soon as possible once we do release the next version, but there will be a bit of new request configuration needed -- the SDK will provide a bit of structure to replicate the fields you can see [in the curl queries on that above quickstart](https://learn.microsoft.com/en-us/azure/ai-services/openai/use-your-data-quickstart?pivots=rest-api&tabs=command-line#example-curl-commands) and look something like (pending finalization!)

```csharp
OpenAIClient client = new(myEndpointUri, myKeyCredential);
ChatCompletions chatCompletions = await client.GetChatCompletionsAsync(myModelDeploymentName, new ChatCompletionsOptions()
{
    Messages = { new(ChatRole.User, "What are the differences between Azure Machine Learning and Azure AI services?") },
    // Pending, non-finalized, coming soon
    AzureExtensionsOptions = new()
    {
        Extensions =
        {
            new AzureChatExtensionConfiguration()
            {
                Type = "AzureCognitiveSearch",
                Parameters = BinaryData.FromObjectAsJson(new
                {
                    Endpoint = mySearchEndpoint,
                    Key = mySearchKey,
                    IndexName = myIndexName,
                }), new JsonSerializerOptions() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase }),
            }
        }
    }
});
```
