### ISSUE TITLE
[BUG] ResourceManager raising the wrong exception

### ISSUE THREAD

**Issue by zhuwen25** [Azure/azure-sdk-for-net#38154]
### Library name and version

  Azure.ResourceManager 1.7.0 Azure.ResourceManager.Resource 1.6.0

### Describe the bug

When using Client.GetSubscriptionResource(ResourceIdentifier).GetAsync() to check a Subscription is exists or not, the interface get wrong exception which was cause by pervious query

### Expected behavior

Client.GetSubscriptionResource(ResourceIdentifier).GetAsync() should retrieve the correct query when query Subscription

### Actual behavior

Client.GetSubscriptionResource(ResourceIdentifier).GetAsync() use the cached ResourceProviderCollection to retrieve previous wrong exception. 

> 

### Reproduction Steps

1. Use correct credential to create correct Armclient,  and its subscription id is **A.**
2. Use var wrongSub=  SubscriptionResource.CreateResourceIdentifier("**A does not exist subscriptionId**");
3. Client.GetSubscriptionResource(wrongSub).GetAsync() will throw RequestionException with 404.
4. Cath the above exception and ignore it.
5. Use var correctSub= SubscriptionResource.CreateResourceIdentifier(" **A.**");
6. Client.GetSubscriptionResource(correctSub).GetAsync() will direct throw the previous exception. because   ResourceProviderCollection  is the cached instance. 

### Environment

Azure.ResourceManager.Resource 1.6.0  Azure.ResourceManager 1.7.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @zhuwen25 ,Thank you for using Azure SDK for .NET.
We can't repro your issue with the following code, please make sure you have thet correct subscription and have another try.
```
var client = new ArmClient(new DefaultAzureCredential());
try
{
    var wrongSub = SubscriptionResource.CreateResourceIdentifier("d4067c1e-8d0e-4c04-819e-28018c3518d5");
    var sub = await client.GetSubscriptionResource(wrongSub).GetAsync();
}
catch (Exception e)
{
    Console.WriteLine("Failed");
}
finally
{
    var correctSub = SubscriptionResource.CreateResourceIdentifier(subscription);
    var sub = await client.GetSubscriptionResource(correctSub).GetAsync();
    Console.WriteLine(sub.Value.Id);
}
```
If possible, you could send us the request/response log you have on this scenario, this may help us on identify the issue.

**Comment by zhuwen25** [comment]
@HarveyLink  my test code are like this.

![image](https://github.com/Azure/azure-sdk-for-net/assets/16134004/3a6ce14c-a560-47af-8c08-50da72e1ba24)

**Comment by zhuwen25** [comment]
@HarveyLink  my test codes are like below :

        public async Task TestGetSubscriptionDataAsync_Fail()
        {
            var wrondId = "04b4abae-a80a-47c2-8156-daa28145edd1";
            var wrongSub = SubscriptionResource.CreateResourceIdentifier(wrondId);
            
            try
            {
                await AzureArmClient.GetGenericResources().ExistsAsync(wrongSub).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Notfound wrong sub");
            }


            var correctIdentifier = SubscriptionResource.CreateResourceIdentifier(defatulSubscriptId);
            //var exist = ExistAsyn(wongRsgid);

            //AssertNotFound(async () => { await ExistAsyn(wongRsgid);});

            try
            {
                await AzureArmClient.GetGenericResources().ExistsAsync(correctIdentifier).ConfigureAwait(false);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Catch wrong exception when querey correct subscriptin ");
            }

        }
and output 
![image](https://github.com/Azure/azure-sdk-for-net/assets/16134004/6cee7b46-970a-4213-b5ac-ebf6c23b4031)

Then you can see, the correct query still got exception, and i don't know how to open azure requst log

**Comment by HarveyLink** [comment]
> @HarveyLink Minghao Chen (WICRESOFT NORTH AMERICA LTD) Vendor my test codes are like below :
> 
> ```
>     public async Task TestGetSubscriptionDataAsync_Fail()
>     {
>         var wrondId = "04b4abae-a80a-47c2-8156-daa28145edd1";
>         var wrongSub = SubscriptionResource.CreateResourceIdentifier(wrondId);
>         
>         try
>         {
>             await AzureArmClient.GetGenericResources().ExistsAsync(wrongSub).ConfigureAwait(false);
>         }
>         catch (Exception ex)
>         {
>             Console.WriteLine("Notfound wrong sub");
>         }
> 
> 
>         var correctIdentifier = SubscriptionResource.CreateResourceIdentifier(defatulSubscriptId);
>         //var exist = ExistAsyn(wongRsgid);
> 
>         //AssertNotFound(async () => { await ExistAsyn(wongRsgid);});
> 
>         try
>         {
>             await AzureArmClient.GetGenericResources().ExistsAsync(correctIdentifier).ConfigureAwait(false);
>         }
>         catch (Exception ex)
>         {
>             Console.WriteLine("Catch wrong exception when querey correct subscriptin ");
>         }
> 
>     }
> ```
> 
> and output ![image](https://user-images.githubusercontent.com/16134004/261891175-6cee7b46-970a-4213-b5ac-ebf6c23b4031.png)
> 
> Then you can see, the correct query still got exception, and i don't know how to open azure requst log

Just want to make sure that you could get the correct subscription without the wrong part and just using:
`await AzureArmClient.GetGenericResources().ExistsAsync(correctIdentifier).ConfigureAwait(false);`
Right?

**Comment by HarveyLink** [comment]
> 04b4abae-a80a-47c2-8156-daa28145edd1

Observed same behavior with your test code. Looking into the root cause now.
