### ISSUE TITLE
> This is related to 1

### ISSUE THREAD

**Issue by Nader1416669** [Azure/azure-sdk-for-net#38174]
> This is related to #3.
> interactive 
> 
> 
> Sometimes the user doesn't know the installation id to use so the interactive mode will list the available ids for them to pick one.
> 
> LLC
> 
> ```sh
> 
> -n | --interactive-mode  Enabled interactive mode to select installation id (Default= false)
> 
> ```

_Originally posted by @Nader1416669 in https://github.com/Link-/gh-token/issues/4#issuecomment-1676740528_

_Originally posted by @Nader1416669 in https://github.com/Azure/azure-sdk-for-net/issues/38173_

**Comment by jsquire** [comment]
Closing as spam.   Account has been reported.
