### ISSUE TITLE
`azure-search-documents` has a few areas where performance could be improved. They fall into two categories:

### ISSUE THREAD

**Issue by Nader1416669** [Azure/azure-sdk-for-net#38170]
`azure-search-documents` has a few areas where performance could be improved. They fall into two categories:

- [x] Reduce the number of classes that leverage the class translation layer.
- [x] Reduce the number of serialization and deserialization passes that happen when dealing with document requests and responses.

_Originally posted by @alzimmermsft in https://github.com/Azure/azure-sdk-for-java/issues/14754_

**Comment by Nader1416669** [comment]
Component Governance detected 1 security related alerts at or above 'High' severity. Microsoft’s Open Source policy requires that all high and critical security vulnerabilities found by this task be addressed by upgrading vulnerable components. Vulnerabilities in indirect dependencies should be addressed by upgrading the root dependency.

**Comment by jsquire** [comment]
Closing as spam;  this account has been reported to GitHub.
