### ISSUE TITLE
`azure-search-documents` has a few areas where performance could be improved. They fall into two categories:

### ISSUE THREAD

**Issue by Nader1416669** [Azure/azure-sdk-for-net#38171]
`azure-search-documents` has a few areas where performance could be improved. They fall into two categories:

- [x] Reduce the number of classes that leverage the class translation layer.
- [x] Reduce the number of serialization and deserialization passes that happen when dealing with document requests and responses.

_Originally posted by @alzimmermsft in https://github.com/Azure/azure-sdk-for-java/issues/14754_

_Originally posted by @Nader1416669 in https://github.com/Azure/azure-sdk-for-net/issues/38170_

**Comment by jsquire** [comment]
Closing as spam;  this account has been reported to GitHub.
