### ISSUE TITLE
[QUERY] Typo in ChatRole structure documentation

### ISSUE THREAD

**Issue by dmytrostruk** [Azure/azure-sdk-for-net#38183]
### Library name and version

Azure.AI.OpenAI latest

### Query/Question

There is small typo in `ChatRole` structure documentation in `Azure.AI.OpenAI` package:

https://learn.microsoft.com/en-us/dotnet/api/azure.ai.openai.chatrole?view=azure-dotnet-preview#properties
![image](https://github.com/Azure/azure-sdk-for-net/assets/13853051/41fd1102-73a8-48aa-b094-9143bafb02f9)

In code:
https://github.com/Azure/azure-sdk-for-net/blob/ea7dc0d229a404ba85285ec63fe533a94650f051/sdk/openai/Azure.AI.OpenAI/src/Generated/ChatRole.cs#L36

I was trying to create PR and fix it, but it looks like this `struct` is auto-generated, so it's not clear whether it's a right place to fix documentation.

**Comment by SaurabhSharma-MSFT** [comment]
@dmytrostruk We are looking into it and get back to you for any additional information.

**Comment by Petermarcu** [comment]
Thanks for the report. This looks like it was fixed here and will roll out in the next release. 

https://github.com/Azure/azure-rest-api-specs/commit/b646a42aa3b7a0ce488d05f1724827ea41d12cf1#diff-bdaaf0065769671d5eb95ada84650cd348f7ad27b97d31a04213e9ec65050abeL24
