### ISSUE TITLE
[BUG] Parameter values not being passed to RunCommandAsync and RunCommandInput via RunCommandInputParameter

### ISSUE THREAD

**Issue by jvu-parsec** [Azure/azure-sdk-for-net#38186]
### Library name and version

Azure.ResourceManager.Compute 1.10

### Describe the bug

I have a PowerShell setup script I need to run as part of the setup before each test in our testing pipeline, the tests run as part of a DevOps pipeline on an Azure VM

We are using this to run our PowerShell scripts on the Azure VM, running the scripts without `input.Parameters.Add(new RunCommandInputParameter(parameter, value));` works fine (we have another method to run scripts that is identical to this method but without the .Parameters.Add call)

    public async Task RunPsFileWithParamAsync(string relativeScriptFilePath, string parameter, string value)
    {
      if (!relativeScriptFilePath.EndsWith(".ps1", StringComparison.InvariantCultureIgnoreCase)) throw new Exception($"{relativeScriptFilePath} must be a valid PowerShell file!");
      string fullPath = Path.Combine(_scriptFileDirectory, relativeScriptFilePath);

      var input = new RunCommandInput("RunPowerShellScript");
      input.Parameters.Add(new RunCommandInputParameter(parameter, value));
      input.Script.Add(fullPath);

      foreach (var script in input.Script)
      {
        this._status.WriteLine($" - script file added: {script}");
      }

      foreach (var paramValuePair in input.Parameters)
      {
        this._status.WriteLine($" - parameter: {paramValuePair.Name} / {paramValuePair.Value}");
      }

      var result = await _vm.RunCommandAsync(WaitUntil.Completed, input);
      if (!result.HasCompleted) throw new Exception("Error running script!");

      this.HandleRunCommandOutput(result);
    }

### Expected behavior

When calling the method to run a script with params though, it'll say it added the param and value to my RunCommandInput but at runtime it doesn't look like any param values are actually being passed to the script

![image (1)](https://github.com/Azure/azure-sdk-for-net/assets/135384067/68e5e0d3-1a95-45bf-9d21-d72c3d3bae7b)

### Actual behavior

The script runs but no values are actually passed to the script (script should been passed a 'true' value and should have thrown and printed the exception message, not the regular message)

![image (2)](https://github.com/Azure/azure-sdk-for-net/assets/135384067/23f0d7ef-1946-4377-a653-02bb0a9d6135)

### Reproduction Steps

Initialize connection to Azure VirtualMachineResource / VM
Create new RunCommandInput to run PowerShell script
Add script to RunCommandInput
Add parameter name-value pair to RunCommandInput
Call RunCommandAsync with that RunCommandInput

Expected: Script should run w/ correct parameters

Actual: Script runs but no parameter values are passed to the script

### Environment

OS Windows 10
.NET 7

### Related
[issue #30640](https://github.com/Azure/azure-sdk-for-net/issues/30640) looks like someone else had an issue getting their parameters to pass too, I added my parameters like how they did aside from using the async version of RunCommand when they resolved their issue but haven't been able to get it to work yet

edit: also tried with the synchronous version of RunCommand, still not passing parameters to the script

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
@jvu-parsec ,Thank you for your feedback. The bug you mentioned has been fixed in the latest version. Regarding the issue you mentioned, I am not quite familiar with the role that the ‘throw’ statement plays in your script. I suggest that you optimize the script code and then continue your work on [the latest version](https://www.nuget.org/packages/Azure.ResourceManager.Compute/1.4.0-beta.1).
