### ISSUE TITLE
Too little information

### ISSUE THREAD

**Issue by cwalters-as** [Azure/azure-sdk-for-net#38203]
Needs more explanation.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9923c482-7052-694a-5f83-3ae3eaac35cb
* Version Independent ID: b8f20565-bbe3-ba0d-b680-650b743f4e57
* Content: [RequestOptions.IfNoneMatchEtag Property (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.requestoptions.ifnonematchetag?view=azure-dotnet#microsoft-azure-cosmos-requestoptions-ifnonematchetag)
* Content Source: [xml/Microsoft.Azure.Cosmos/RequestOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/RequestOptions.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` library is maintained as [#4038](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4038).
