### ISSUE TITLE
Grammar issue for CorrelationId description

### ISSUE THREAD

**Issue by edcsu** [Azure/azure-sdk-for-net#38209]
Hello Azure team,
Thanks for the wonderful and up to date documentation.
However, there is a grammar issue which is a bit misleading as seen below.
<img width="452" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/38857594/4bbbaa9a-3cc6-4560-8699-89dceed5bb91">
It should be **Gets or sets the correlation identifier**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1f6230cb-970e-7765-59a4-d0db58d0e8e2
* Version Independent ID: ecd4a582-cd6d-0976-0481-0a221065b095
* Content: [ServiceBusMessage Class (Azure.Messaging.ServiceBus) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusmessage?view=azure-dotnet)
* Content Source: [xml/Azure.Messaging.ServiceBus/ServiceBusMessage.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Messaging.ServiceBus/ServiceBusMessage.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Hi @edcsu.  Thanks very much for letting us know.   I've opened #38211 to address this in the source, and the docs will update with our next release.
