### ISSUE TITLE
authContext.AcquireTokenAsync throwing exceptions : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jrsurya** [Azure/azure-sdk-for-net#3821]
I am working on **Azure KeyValut Authenticate with a Certificate using (Framework .net core 2.0)** and  
below line throwing exceptions  

AssertionCert = new ClientAssertionCertificate(clientId, clientAssertionCertPfx);

public static async void GetConnectionString(string clientId, string thumbprint, string ContentRootPath)
		{

			// Configure Key Vault client
			var kvClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(async
				(authority, resource, scope) =>
			{
				var cert = CertificateHelper.FindCertificateByThumbprint(thumbprint);// Get certificate from local store/file/key vault etc. as needed
																					 // From the Microsoft.IdentityModel.Clients.ActiveDirectory pacakge
				var authContext = new AuthenticationContext(authority);
					//TokenCache.DefaultShared);
				var result = await authContext.AcquireTokenAsync(resource,
					// From the Microsoft.Rest.ClientRuntime.Azure.Authentication pacakge
					new ClientAssertionCertificate(clientId, cert));
				return result.AccessToken;
			}));

			//// Get configuration values from Key Vault
			//var builder = new ConfigurationBuilder()
			//	.SetBasePath(ContentRootPath)
			//	// Other configuration providers go here.
			//	.AddAzureKeyVault("{KeyValueUri}", kvClient,
			//	new DefaultKeyVaultSecretManager());

			var sec = await kvClient.GetSecretAsync(ContentRootPath);
	
		}

using below DDL:

![image](https://user-images.githubusercontent.com/30382496/32135137-98c5f5d0-bc17-11e7-8f2c-5554901946f0.png)

**Error Details:**

+		$exception	{System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate..ctor(String clientId, X509Certificate2 certificate)
   at HelpCentralIndexCreater.KeyVaultReader.GetCert() in C:\Users\Documents\Visual Studio 2017\Projects\HelpCentralIndexCreater\HelpCentralIndexCreater\Program.cs:line 81
   at HelpCentralIndexCreater.KeyVaultReader..ctor(String vaultUrl, String clientId, String secretKey) in

**Comment by AlexGhiondea** [comment]
@jrsurya we realize it's been a long time since you opened this issue. If you still require help, please reply to this issue.

**Comment by MathewsNyirongo** [comment]
Could this issue be reopened please. I'm facing the same problem. The exception is thrown when I use a self-signed certificate generated in keyvault. But when I use a certificate generated on my local machine the problem goes away. I, however want to use the keyvault-generated certificate because it offers me the auto-renew option which is very handy.
