### ISSUE TITLE
Need help in implementing Dependency Injection while invoking EventGridPublisherClient

### ISSUE THREAD

**Issue by kagexander** [Azure/azure-sdk-for-net#38212]
### Library name and version

Azure.Messaging.EventGrid 4.11.0

### Query/Question

Hi All,

I am able to invoke EventGridPublisherClient to publish messages to Event grid using Default Azure Credential.
                    Uri endpoint = new Uri(topicEndpoint);
                    EventGridPublisherClient client  = new EventGridPublisherClient(endpoint, new DefaultAzureCredential());

Now while trying to implemnet dependency Injection , I am not able to make it work. 

**StartUp.cs**

            services.AddAzureClients(clients =>
            {                
                 clients.AddEventGridPublisherClient(new Uri(Configuration.GetSection("EnvironmentVariables").GetValue<string>("TopicEndpoint")), new DefaultAzureCredential());
                clients.UseCredential(new DefaultAzureCredential());
            });
_Getting this error._
![image](https://github.com/Azure/azure-sdk-for-net/assets/22502297/ff917908-93e3-461f-94fc-1b995ea3f010)

Any ideas as to how to resolve this. Appreciate any suggestions !!!!

**Comment by kagexander** [comment]
Hi @JoshLove-msft , I have tried that earlier but it does not work out. Am i missing something?

![image](https://github.com/Azure/azure-sdk-for-net/assets/22502297/be1dafd9-df1d-44a4-babf-182cc008adf3)

**Comment by JoshLove-msft** [comment]
That looks correct to me. Have you tried rebuilding?

If you can provide an end to end repo (pasting the code), I can try it on my end.
