### ISSUE TITLE
[BUG] ObjectDisposedException when calling GetConfigurationSettingAsync / SetConfigurationSettingAsync

### ISSUE THREAD

**Issue by et13** [Azure/azure-sdk-for-net#38219]
### Library name and version

Azure.Data.AppConfiguration 1.3.0-beta.2

### Describe the bug

We have a `ConfigurationClient` set up with a non default transport and are seeing calls to `GetConfigurationSettingAsync` / `SetConfigurationSettingAsync` throw `ObjectDisposedException` when using 1.3.0-beta.2 and 1.3.0-beta.1.

Note: The calls succeed when using 1.2.0.

### Expected behavior

Calls to `GetConfigurationSettingAsync` / `SetConfigurationSettingAsync` succeed

### Actual behavior

Calls to `GetConfigurationSettingAsync` / `SetConfigurationSettingAsync` throw `ObjectDisposedException`

```
Unhandled exception. System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at System.Text.Json.JsonDocument.ReadToEndAsync(Stream stream, CancellationToken cancellationToken)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at Azure.Data.AppConfiguration.ConfigurationServiceSerializer.DeserializeSettingAsync(Stream content, CancellationToken cancellation)
   at Azure.Data.AppConfiguration.ConfigurationClient.CreateResponseAsync(Response response, CancellationToken cancellation)
   at Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingAsync(String key, String label, Nullable`1 acceptDateTime, MatchConditions conditions, CancellationToken cancellationToken)
   at Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSettingAsync(String key, String label, CancellationToken cancellationToken)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\ernestt\source\repos\ConsoleApp1\Program.cs:line 37
   at ConsoleApp1.Program.<Main>(String[] args)
```

### Reproduction Steps

Run the following code, replacing `<connection_string>` with any well formed connection string.

```
using Azure.Core.Pipeline;
using Azure.Data.AppConfiguration;
using System.Net;
using System.Text;

namespace ConsoleApp1
{
    class TestHttpMessageHandler : HttpMessageHandler
    {
        protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            return Task.FromResult(new HttpResponseMessage()
            {
                StatusCode = HttpStatusCode.OK,
                Content = new StringContent("{ \"key\": \"abc\", \"value\" :\"def\" }", Encoding.UTF8, "application/json")
            });
        }
    }

    internal class Program
    {
        static async Task Main(string[] args)
        {
            //
            // Use any well formed connection string
            string connectionString = "<connection_string>";

            var client = new ConfigurationClient(
                connectionString,
                new ConfigurationClientOptions
                {
                    Transport = new HttpClientTransport(new TestHttpMessageHandler())
                });

            var result = await client.GetConfigurationSettingAsync("abc");

            var result2 = await client.SetConfigurationSettingAsync("abc", "def");
        }
    }
}

```

### Environment

Windows 11
.NET 6

Visual Studio 17.8 Preview 1.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by annelo-msft** [comment]
Adding ARM - Core because of https://github.com/Azure/azure-sdk-for-net/issues/38505#issuecomment-1709207185

**Comment by jsquire** [comment]
The bug has been fixed specific to AppConfig and will appear in our October release.  The general form is more nuanced and will require deeper investigation to plan a fix that works in all scenarios.   Shifting this over fully to Azure.Core.

**Comment by snarkywolverine** [comment]
@jsquire Does your fix address #38505 as well, or does that require the general form fix?

**Comment by jsquire** [comment]
@snarkywolverine:  Unfortunately, it does not.   I was able to work around the specific implementation for AppConfig, but we'll still need to solve this in the general case to fix the resource manager packages.

That said, you should be able to work around this by returning a content stream that returns `false` for `IsSeekable` or which is not owned by the content type being returned.  That likely means that you'd need to avoid `StringContent` and implement a custom version, or use another means of returning response content.

**Comment by annelo-msft** [comment]
This was fixed in https://github.com/Azure/azure-sdk-for-net/commit/c7dbcdebeba5e9a11f0c3aa6e90c26b83b657426#diff-8820ebe47c628d19247979220b62335b2fca905fce27d416c50a0560947f1713
