### ISSUE TITLE
[QUERY] how do I provide a azure cognitive hybrid response to the Azure.OpenIA client?  

### ISSUE THREAD

**Issue by JoacimWall** [Azure/azure-sdk-for-net#38237]
### Library name and version

Azure.AI.OpenAi

### Query/Question

Hi I use the Azure.Search.Documents framework to do a hybrid search (Vector, text with semantic ) with Azure Search service on my one data for a chat question. 

What is the best way to provide this response to Azure.Ai.OpenAi to answer(summerice) the chat question?    

I have looked everywhere and there are no samples/video on this only on the search but not on how you provide the answer to the OpenAi.  

//Joacim

**Comment by navba-MSFT** [comment]
@JoacimWall Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@JoacimWall As far as I know, there is no way to accomplish your ask.

Alternatively, If you want to add azure search index as a datasource to your chat completion request SDK update will be released by end of Aug. Until then, please use REST API
: https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#completions-extensions

**Comment by mattmsft** [comment]
Hi @JoacimWall,

Check out our sample on how to combine Azure Cognitive Search with Open AI

https://github.com/Azure-Samples/azure-search-openai-demo

**Comment by navba-MSFT** [comment]
@JoacimWall I hope you had a chance to see the above comments. If you have any follow-up questions, please do let me know. I would be happy to help.
