### ISSUE TITLE
Error creating PnP context using VisualStudioCredential

### ISSUE THREAD

**Issue by milkyware** [Azure/azure-sdk-for-net#38236]
### Library name and version

Azure.Identity 1.9.0

### Query/Question

Hi,

I initially raised an [issue/query with the PnP Core team](https://github.com/pnp/pnpcore/issues/1246#issue-1841044793) but wanted to widen the audience. PnP have published an example of using Azure.Identity in a custom authentication provider to authenticate use managed identities. After further reading I noticed the [DefaultAzureCredential](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#defaultazurecredential) contained **[VisualStudioCredential](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#authenticate-via-visual-studio)** which (in theory) would simplify the local debugging process of PnP core by using the account I've logged into VS with. 

However, when I create a **ChainedTokenCredential** with **VisualStudioCredential** (even just by itself) I get the error below:

```
Process "C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS004: Unable to get access token.  'AADSTS65002: Consent between first party application '04f0c124-f2bc-4f59-8241-bf6df9866bbd' and first party resource '00000003-0000-0ff1-ce00-000000000000' must be configured via preauthorization - applications owned and operated by Microsoft must get approval from the API owner before requesting tokens for that API.
```

The question is, that first appid (which I'm assuming is for the ASAL token helper) doesn't exist in my tenancy and with both this VS token service extension and SharePoint being owned by Microsoft how would I go about resolving this? Any suggestions would be appreciated.

### Environment

.NET SDK:
 Version:   8.0.100-preview.7.23376.3
 Commit:    daebeea8ea

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.100-preview.7.23376.3\

.NET workloads installed:
Host:
  Version:      8.0.0-preview.7.23375.6
  Architecture: x64
  Commit:       65b696cf5e
  RID:          win-x64

.NET SDKs installed:
  7.0.400 [C:\Program Files\dotnet\sdk]
  8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.0-preview.7.23375.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.0-preview.7.23375.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.0-preview.7.23376.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

IDE: VS 2022 (17.7)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by crmann1** [comment]
We need to request authorization from the resource you are accessing. I will start that process now, can take a couple of weeks for the resource team to complete.

**Comment by crmann1** [comment]
Can you let me know you want to access in the sharepoint site debugging so we can request the correct permissions.  This has a good set of permission descriptions  https://stackoverflow.com/questions/38571840/office365-sharepoint-scopes

**Comment by milkyware** [comment]
Hi, for the purposes of debugging the idea would be that the token service of VS would be able to piggy back off the permissions of the person logged into VS. Therefore my understanding is that all of the delegated permissions in that post would be needed whereas the application permissions wouldn't be needed as the token service would be deployed as a standalone service anywhere. Hope that makes sense and please do shout if my understanding isn't correct

**Comment by jsquire** [comment]
Unsure why this was reopened;  closing.

**Comment by milkyware** [comment]
Hi @jsquire, still having issues with this. Interestingly I started using the Dataverse SDK recently, and using VisualStudioCredential with that seems to work fine. Any ideas?

**Comment by christothes** [comment]
@crmann1  - Is this authorization request still in progress?
