### ISSUE TITLE
[BUG] EventReceiveError: 'At least one receiver for the endpoint is created with epoch of '0''

### ISSUE THREAD

**Issue by ben-hamida** [Azure/azure-sdk-for-net#38240]
### Library name and version

Azure.Messaging.EventHubs 5.9.2

### Describe the bug

In the last couple of months, this error has started showing up in the logs:

'At least one receiver for the endpoint is created with epoch of '0', and so non-epoch receiver is not allowed. Either reconnect with a higher epoch, or make sure all epoch receivers are closed or disconnected.'

It first started on May 31 which exactly coincides with an update of the azurefunctions SDK from version 4.19.0.20414 to version 4.21.2.20699.

We get around 5000 of these error messages every day in the log. As a reference, we have around 100 million outgoing messages per day from the event hub.

We have a function app with several functions that use `EventHubTrigger` to consume events. In addition, we are explicitly using `EventProcessorClient` in one function. For that latter case, we create and reuse one `EventProcessorClient` throughout the app's lifetime. 

We have 18 consumer groups in the event hub, not counting the default one which we don't use. Each consumer group is only used in one place in the code.

The event hub has 6 partitions, but I noticed that the message is only reported on partition ID 0.

The error indicates we are trying to register a non-epoch receiver, but I have scanned the code and haven't found anything like that. 

The function app is allowed to scale out to 10 instances.

### Expected behavior

No exceptions of this type in the log

### Actual behavior

Around 5000 of these errors in the log every day.

### Reproduction Steps

Haven't been able to reproduce this locally.

### Environment

Azure functions v4 in-process
.NET 6

**Comment by jsquire** [comment]
Hi @ben-hamida.  The message that you're seeing indicates that there are multiple readers asserting exclusive access to a partition for a consumer group.  This is normal and expected when instances are scaling up/down for 1-3 minutes after the scaling activity triggers.  

In your scenario, if the `EventProcessorClient` that you're using uses the same consumer group and Event Hub that you've asked the trigger to use, you have very likely created contention for ownership.  Unless you're explicitly using the same exact Blob Storage container that the trigger is, your processor would not see the ones used by the trigger instances and would start claiming ownership and would be fighting with the trigger for exclusive access.

Generally, there's no good pattern for hosting `EventProcessorClient` directly in Functions and we would strongly recommend not doing so.   If you're looking to receive and process events in a Function, we would recommend using the trigger, which manages an event processor on your behalf and ensure.  Even if you create it as static, the instance of the Function that hosts it is ephemeral and will go idle or change hosts unless you're using a dedicated plan with "Always on" enabled.   You will either see either contention with fighting over ownership or delays in processing in other configurations or plans.  

Can you please let us know:

- Are you seeing these messages constantly or only as the Function is scaling?
- Are all of the Functions using a trigger and configured for the same Event Hub / consumer group pairing also pointed at the same storage account?
- Is the `EventProcessorClient` that you are managing directly using the same Event Hub / consumer group pairing as the triggers?
- Is your Function application that manages an `EventProcessorClient` running on a dedicated plan with "Always On" enabled?

**Comment by ben-hamida** [comment]
Hi @jsquire, That's what I would expect if the message was indicating that a receiver with an epoch smaller or equal to the current reader was created. In fact, we have filters in place to remove such messages from our logs. But this message, specifically the 'non-epoch receiver is not allowed' part, indicates that a non-epoch receiver is being created. How is this possible? Don't both `EventHubTrigger` and `EventProcessorClient` use epoch-receivers?

The reason we are using`EvenProcesserClient`: We have a function that is timer triggered that reads events from the event hub and writes to a Cosmos database based on those events. The reason for a timer trigger rather than the EventHubTrigger is that the latter scales out unpredictably, and we want to be able to control the write speed to Cosmos to avoid rate limiting where possible.

Answers to your questions:
* We are getting these messages constantly and I don't see a correlation to when the function is scaling.
* All of the functions are using different consumer groups. There is one function app with the majority of the functions, and there is one other function app with a single function. The two function apps point to different storage accounts, but as mentioned, none of the functions share consumer groups for their triggers.
* The `EvenProcessorClient` uses a different consumer group.
* No, "Always On" is not enabled.

**Comment by jsquire** [comment]
@ben-hamida:  The processor uses non-epoch readers to validate connectivity and permissions when first starting up (as part of the `StartProcessingAsync` call chain), they expect to be denied if something is already reading the partition - the error is handled internally and considered a successful validation.  This stage of validation is a single read operation, performed once, and generally takes between 125-250ms to complete.

If you're seeing these repeatedly and you're not scaling or having instances fight over partitions, then either a processor instance is being started as frequently as you're seeing the messages or there's another reader (which is not an event processor) attempting to use the consumer group.   Assuming you're inquiring about logs captured for your specific Functions application, the latter case seems unlikely.   That may be your static processor being started/stopped by the timer (or a new instance of the timer Function being created)  or may be the Functions runtime moving instances around or auto-scaling.

Are you seeing the names of the receiver in those error messages?   The processor itself can be assigned an identity and uses a GUID if none is provided.   The startup validation uses a reader with the pattern "SV-<< Processor Identifier >>".   If you assign your static processor a unique name that you can identify with a random component, that should help to identify whether its the startup spammer.

**Comment by ben-hamida** [comment]
@jsquire I did some deeper investigation and it seems that the error message occurrence is correlated with the function app scaling after all. I found a stretch of one hour where the function app wasn't scaling and there were no error messages logged during that time.

My outstanding questions are:
* Why did this start to happen on 31 May when the functionapp SDK version 4.21.2.20699 was deployed? Was this log message added then or was there some other behavioral change?
* Why is the log only reported on partition ID 0? (there is not a single instance with prop__partitionId != 0)
* Is it ok to just completely ignore these messages in the future?
* It seems like a bug that this message is logged at all since it's part of a valid workflow and not an error. Is it something that will be fixed?

If there are instances where this message represents a real error, it will be hard to detect with all the noise. It would be nice if the sdk stopped logging the messages when it's part of a valid workflow, or alternatively, if we had a way to distinguish them from real errors so that we don't accidentally filter out error messages that represent real issues.

**Comment by ben-hamida** [comment]
@jsquire Thank you for your support, this was very informative. We will go ahead and filter out those messages from our logs.

Looking forward to when that filtering infrastructure is in place. We've had several instances of unwanted/false positive logs from the core libraries.
