### ISSUE TITLE
[BUG] Impossible to stop deluge of Debug output when using Azure.Monitor.OpenTelemetry.Exporter

### ISSUE THREAD

**Issue by jakenuts** [Azure/azure-sdk-for-net#38246]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter

### Describe the bug

I've tried disabling the EventSource, changing every logging configuration setting I could find, but it appears as though as long as you are trying to debug code the AzureMonitorExporterEventListener will fill your output window with verbose output making everything else you'd hope to log practically unusable.

### Expected behavior

There must be some way to disable or limit the debug output while using this exporter.

### Actual behavior

All events sent to OpenTelemetry and exported are rendered in the output window of your debugger.

### Reproduction Steps

Use the package

### Environment

Windows 11, though anything I imagine

**Comment by insylogo** [comment]
Appears to me that https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/AzureMonitorExporterExtensions.cs shouldn't be setting the sampler, i.e. overriding anyone elses sampler settings. Adding a trace exporter should not affect sampler settings. Break this apart into two different calls, so you can adjust sampler settings or trace exporter settings separately. @TimothyMothra

**Comment by jakenuts** [comment]
I think the issue I'm seeing relates to [this utility class](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/Internals/Diagnostics/TelemetryDebugWriter.cs) TelemetryDebugWriter where all the events are rendered in the debug output window if a debugger is attached. 

I've tried disrupting the chain of EventSource and EventListeners that feed it, but I don't believe they are configurable (or at least not in any way I've discovered). 

Optimally, like in ApplicationInsights there should be a way to disable the TelemetryDebugWriter in code and it might even be disabled by default and only enabled to confirm that events are being exported.

**Comment by TimothyMothra** [comment]
> Appears to me that https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src/AzureMonitorExporterExtensions.cs shouldn't be setting the sampler, i.e. overriding anyone elses sampler settings. Adding a trace exporter should not affect sampler settings. Break this apart into two different calls, so you can adjust sampler settings or trace exporter settings separately. @TimothyMothra

@insylogo, Please open a new issue to discuss this. This is not related to the OP's issue.

**Comment by TimothyMothra** [comment]
Hi @jakenuts, sorry for the inconvenience. Currently this is not configurable.
We have this enabled while we're in beta and we're planning to change this to off by default when before we release 1.0.
I already have a Draft PR to address this: https://github.com/Azure/azure-sdk-for-net/pull/38016

**Comment by TimothyMothra** [comment]
The work for this is merged and will be in the Sept release.
