### ISSUE TITLE
Document System.MissingMethodException in ModelSerializer.Deserialize

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#38244]
ModelSerializer.Deserialize can throw if a model doesn't have an internal parameterless constructor, e.g.:

System.MissingMethodException : Cannot dynamically create an instance of type '<model-name>'. Reason: No parameterless constructor defined.

This exception should be added to the refdocs.

**Comment by pallavit** [comment]
@annelo-msft which ref-docs are we talking about here?

**Comment by annelo-msft** [comment]
> which ref-docs are we talking about here?

The ones for `ModelSerializer.Deserialize`.  Here:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Serialization/ModelSerializer.cs#L87-L90

We document several exceptions that the method can throw, but not `System.MissingMethodException`.
