### ISSUE TITLE
[BUG] If event count is less than minEventBatchSize the checkpoint is not updated

### ISSUE THREAD

**Issue by mikkovor** [Azure/azure-sdk-for-net#38254]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventHubs 5.5.0

### Describe the bug

We updated Microsoft.Azure.WebJobs.Extensions.EventHubs to latest version to put the new minEventBatchSize  and maxWaitTime to use. After some testing in dev environment we started noticing weird behaviour and found the reason.

https://github.com/Azure/azure-sdk-for-net/blob/f5c12658162459653924fbeaad5b2fd9241b93ff/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Listeners/EventHubListener.PartitionProcessor.cs#L166C1-L170C58

Here the allowPartialBatch is false as seen in the code above.

https://github.com/Azure/azure-sdk-for-net/blob/f5c12658162459653924fbeaad5b2fd9241b93ff/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Listeners/PartitionProcessorEventsManager.cs#L66C1-L70C14

It returns an empty array and then the checkpoint is never updated since it doesn't go to the if block

### Expected behavior

The checkpoint should be updated even if the minEventBatchSize is not met. If the minEventBatchSize is 500 and one partition keep getting 400 events then the checkpoint is never updated and those events will be processed again at some point.

### Actual behavior

Checkpoint is not updated if event count is less than the minEventBatchSize 

### Reproduction Steps

Look at the code in repo, not much else to it. That's how it works at the moment. I don't think this makes any sense or I hope someone explains it to me if it is done on purpose.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by m-redding** [comment]
Hi @mikkovor thank you for reporting this issue. I just opened a PR with the bug fix (linked below). The checkpoint method was being called with the events to checkpoint, but the flag indicating that the checkpoint should be actually written wasn't getting set to true in the small batch case.

**Comment by mikkovor** [comment]
> Hi @mikkovor thank you for reporting this issue. I just opened a PR with the bug fix (linked below). The checkpoint method was being called with the events to checkpoint, but the flag indicating that the checkpoint should be actually written wasn't getting set to true when a small (less than min size) batch is the first batch. Just as a note, the checkpoints were still being written correctly when minEventBatchSize was met, and in most cases when minEventBatchSize was not met, so you shouldn't be seeing symptoms of no checkpoints.

Cheers.  I see I got a big confused how it works but there was definitely a bug that I got right :)
We were definitely getting a lot of no checkpoints but I think that was a just a coincidence since in our dev environment the standard interval for new events is probably 1 minute and our maxWaitTime was set to 1 minute as well so there was a batch of less than the minEventBatchSize very often. 

I made changes to update the checkpoint manually in case the total count is less than the minEventBatchSize but maybe that can be scrapped once a new release is out.

**Comment by mikkovor** [comment]
@m-redding Just to clarify is this also the reason why Requests are not showing in Application Insights if the case happens that the event count < minEventBatchSize ? We are now running in to that problem... we do update the checkpoint but cannot see requests for those partitions which is a bummer

**Comment by klemmchr** [comment]
Has this fix already been released? I'm on 5.6.0 (released Aug 24) and still experiencing this issue.

**Comment by jsquire** [comment]
Yes, this fix is included in the latest release, v6.0.0.

**Comment by klemmchr** [comment]
Pardon my confusion, I totally missed that this issue is scoped to `Microsoft.Azure.WebJobs.Extensions.EventHubs` and does not cover `Microsoft.Azure.Functions.Worker.Extensions.EventHubs`.

I'm experiencing exactly the same issue using `Microsoft.Azure.Functions.Worker.Extensions.EventHubs` v5.6.0 (latest version). Should I create a new issue for that?

**Comment by jsquire** [comment]
> Pardon my confusion, I totally missed that this issue is scoped to `Microsoft.Azure.WebJobs.Extensions.EventHubs` and does not cover `Microsoft.Azure.Functions.Worker.Extensions.EventHubs`.

No worries, the implicit dependency between the two and need for multiple releases is not the most obvious of things.   The isolated worker package folks are working on a release that bundles v6.0.0 of the extensions, though I do not know the timeline.   Opening an issue in the Functions repository may help but let me also try pinging one of the folks that may know.

@lilyjma, @fabiocav:  Any chance that you can assist?
