### ISSUE TITLE
Feature Request: RoleEnvironment.DeploymentLabel

### ISSUE THREAD

**Issue by austvik** [Azure/azure-sdk-for-net#3826]
RoleEnvironment already has a method to get DeploymentId.
Please add another method to get DeploymentLabel.

UseCase: We put source code version in deployment label and would like to log/put it into performance counters to see which version were running where and when.

**Comment by hoyle1977** [comment]
Is it added or not?

**Comment by ifeoluwaokunoren** [comment]
Hello,
This is not a Resource Manager related issue. However, if this is still an issue, kindly raise a uservoice request [here](https://feedback.azure.com/forums/169386-cloud-services-web-and-worker-role)

**Comment by antsh85** [comment]
I would also like to have "deployment label" under RoleEnvironment
