### ISSUE TITLE
Use client's max buffer size for `AppendBlobWriteStream`

### ISSUE THREAD

**Issue by Arithmomaniac** [Azure/azure-sdk-for-net#38267]
https://github.com/Azure/azure-sdk-for-net/blob/5041d7c7d15e8581bb86db2e9ef40e598f8f366d/sdk/storage/Azure.Storage.Blobs/src/AppendBlobWriteStream.cs#L66-L69

This value should not be fixed, but determined by `_appendBlobClient.AppendBlobMaxAppendBlockBytes`. (Happy to submit a PR.)

**Comment by seanmcc-msft** [comment]
@Arithmomaniac, this is by-design.  The [Append Blob REST API](https://learn.microsoft.com/en-us/rest/api/storageservices/append-block?tabs=microsoft-entra-id#request-headers) has a max append size of 100 MB, which is the value of Constants.Blob.Append.MaxAppendBlockBytes.

**Comment by Arithmomaniac** [comment]
This does not account for the differing max values in different API versions, which is the whole point of `AppendBlobMaxAppendBlockBytes`:

https://github.com/Azure/azure-sdk-for-net/blob/61eee92ed094de7350f73f604c366c918fc4c643/sdk/storage/Azure.Storage.Blobs/src/AppendBlobClient.cs#L38-L44
