### ISSUE TITLE
[FEATURE REQ] How to set Application Insights Metrics Namespace in AzureMonitorOpenTelemetryExporter

### ISSUE THREAD

**Issue by joebeernink** [Azure/azure-sdk-for-net#38270]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter" Version="1.0.0-beta.14

### Query/Question

I'm working on getting open telemetry working (so very close). One question I hope someone can quickly help me with. When using System.Diagnostic.Meter, how do I set the namespace for the metrics in Azure Monitor / Application Insights? Or is that a field that is only kept for backwards compatibility and always set to azure.applicationinsights? Thanks!

### Environment

.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.413 [C:\Program Files\dotnet\sdk]
  7.0.306 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by joebeernink** [comment]
Hey all, any update on this one? Thanks!

**Comment by jsquire** [comment]
Hi @joebeernink.   Sorry that the support team failed to pick this up.  I shifted this over to the Monitor team directly.

**Comment by joebeernink** [comment]
Thanks!

**Comment by cijothomas** [comment]
It is currently hardcoded and not available for customization.

**Comment by joebeernink** [comment]
@cijothomas is there an open github issue somewhere for adding this capability? If not, can we turn this request into an issue please? Having all OT metrics forced into the same namespace for large projects is going to make it really difficult to manage large systems.

**Comment by cijothomas** [comment]
@mattmccleary Could you help where would user put this feature request? This is not .NET specific ask, so a more general place for feature request?

**Comment by mattmccleary** [comment]
We do have https://feedback.azure.com/d365community/forum/3887dc70-2025-ec11-b6e6-000d3a4f09d0. However, I want to bring this up in our next available PM/Engr sync as I think it should be higher pri to resolve this.

**Comment by joebeernink** [comment]
Hey @mattmccleary, any word on this? Thanks!

**Comment by mattmccleary** [comment]
Yes, the metrics team is working on a namespace concept in Azure Monitor Workspace, but it's still 6-18 months out (and we need customer feedback to understand how customers would want to use it). Can I understand your scenario better? 

> Having all OT metrics forced into the same namespace for large projects is going to make it really difficult to manage large systems.

How so? Are you trying to send all metrics to a single App Insights Resource? How would you like to use namespace? Is the issue of service being too big to understand also an issue in, for instance, the App Map?

**Comment by andrew-lis** [comment]
I second this. Right now we have many custom metrics and we were able to group them into namespaces per service since .net core 3.1:
![obraz](https://github.com/Azure/azure-sdk-for-net/assets/2116581/8a918acc-ae5f-474f-9ad2-9d3129570243)

But with .net 8 with the promoted OpenTelemetry api (UseAzureMonitor + IMeterFactory + CreateCounter()) all meters are pushed to default namespace, i.e. "azure.applicationinsights".

**Comment by TimothyMothra** [comment]
I'm consolidating all issues regarding overriding specific fields in the Application Insights schema into another issue to help with tracking. https://github.com/Azure/azure-sdk-for-net/issues/46021
