### ISSUE TITLE
[QUERY] retry policy of ResourceManagementClient.Resources.BeginUpdateByIdWithHttpMessagesAsync

### ISSUE THREAD

**Issue by wangcancan1996** [Azure/azure-sdk-for-net#38276]
### Library name and version

Microsoft.Azure.Management.ResourceManager.Fluent 1.37.1

### Query/Question

this is how we create a ResourceManagementClient:
new ResourceManagementClient(
               RestClient
               .Configure()
               .WithEnvironment(AzureGlobalCloud)
               .WithHttpClient(this.httpClientFactory.CreateClient())
               .WithCredentials(credentials)
               .Build()
);
then we call resourceManagementClient.Resources.BeginUpdateByIdWithHttpMessagesAsync to update a VMSS. The problem is, for some 4** and 5** error, we set retry-count to 3 in our service side and totally trigger 4 times BeginUpdateByIdWithHttpMessagesAsync, but there are all 16 Patch requests from VMSS activity-log side:
![image](https://github.com/Azure/azure-sdk-for-net/assets/44257910/accb7eae-d6d6-43e3-9c77-8a3cdddc0383)
per 4 Patch request shared the same clientRequestId. I guess probably it's the retry-policy of ResourceManagementClient SDK leads to those all 16 Patch requests.

 So I want to know, as we did not explicitly set retry-policy of resourceManagementClient, is there any retry-policy is configured to ResourceManagementClient by default? and how can we check/see its retry-policy in our service?

Thanks!

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @wangcancan1996 , thank you for reaching out to us.
The SDK you're using is the old one which has been deprecated, please follow this [migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md) and move to the new [Azure.ResourceManager](https://www.nuget.org/packages/Azure.ResourceManager/) SDK, in which you can customize the [retry policy](https://www.nuget.org/packages/Azure.ResourceManager/).
