### ISSUE TITLE
[BUG] No opentelemetry traces are exported 

### ISSUE THREAD

**Issue by scrocquesel-ml150** [Azure/azure-sdk-for-net#38283]
### Library name and version

Azure.Messaging.ServiceBus 7.16.1

### Describe the bug

Using the following configuration

```csharp
builder.Services.AddOpenTelemetry()
            .WithTracing(tracerProviderBuilder =>
            {
                tracerProviderBuilder
                    .AddSource("Azure.*")
                    .SetSampler(new AlwaysOnSampler())
                    .AddAzureMonitorTraceExporter()
                    .AddConsoleExporter();
            })
builder.Services.AddAzureClients(configure =>
        {
            configure.AddBlobServiceClient("");
            configure.AddServiceBusClient("");
        });
```

I cannot observe any traces from the ServiceBus client within both exporters. However, I am able to see traces from the blob client.

I have registered both an ActivityListener and a DiagnosticListener. For the ServiceBus, I receive notifications from the DiagnosticListener but not from the ActivityListener. In the case of the Blob client, I can see traces from both sources.

### Expected behavior

Traces/Span from ServiceBus are exported like with `AddApplicationInsightsTelemetry`.

### Actual behavior

No traces

### Reproduction Steps

Simple aspnet core application that send messages with the telemetry configuration above

### Environment

- TargetFramework: net6.0
- Platform: local linux env under wsl2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
OpenTelemetry support is still experimental so in order to enable it, you will need to set a flag as described [here](https://devblogs.microsoft.com/azure-sdk/introducing-experimental-opentelemetry-support-in-the-azure-sdk-for-net/#get-started). Can you let us know if you have already set this?

**Comment by scrocquesel-ml150** [comment]
> OpenTelemetry support is still experimental so in order to enable it, you will need to set a flag as described [here](https://devblogs.microsoft.com/azure-sdk/introducing-experimental-opentelemetry-support-in-the-azure-sdk-for-net/#get-started). Can you let us know if you have already set this?

Yes, That's why I think I can at least observe traces for blob clients. I see in the code that service bus and blob client doesn't use the same DiagnosticScope class hierachy. Service bus is using a Messaging wrapper while I guess blob client use a common implementation for all HTTP based clients. But it is not obvious as to why the Activity are not created in the case of Service Bus.

**Comment by JoshLove-msft** [comment]
@scrocquesel-ml150, thanks I was able to repro the issue and we are tracking down the root cause.
