### ISSUE TITLE
Documentation question

### ISSUE THREAD

**Issue by nitinthewiz** [Azure/azure-sdk-for-net#38287]
Is Riff16Khz16BitMonoPcm the default SpeechSynthesisOutputFormat?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5a995cd2-4e91-ff57-60d2-b45a9ae11c35
* Version Independent ID: 0d7f53df-acbf-bd8f-a615-43665ea7e89b
* Content: [SpeechConfig.SetSpeechSynthesisOutputFormat Method (Microsoft.CognitiveServices.Speech) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.cognitiveservices.speech.speechconfig.setspeechsynthesisoutputformat?view=azure-dotnet)
* Content Source: [xml/Microsoft.CognitiveServices.Speech/SpeechConfig.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.CognitiveServices.Speech/SpeechConfig.xml)
* Service: **cognitive-services**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by navba-MSFT** [comment]
@nitinthewiz Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@nitinthewiz The default output format is `Riff16Khz16BitMonoPcm`. You can change the output format by calling this method and passing in one of the SpeechSynthesisOutputFormat enumeration values. 

```
            // Creates an instance of a speech config with specified subscription key and service region.
            speechConfig = SpeechConfig.FromSubscription(SubscriptionKey, Region);

            // The default format is RIFF, which has a riff header.
            // We can set the format to raw (24KHz for better quality).
            speechConfig.SetSpeechSynthesisOutputFormat(SpeechSynthesisOutputFormat.Raw24Khz16BitMonoPcm);
```

Refer the available audio formats [**here**](https://github.com/microsoft/cognitive-services-speech-sdk-js/blob/master/src/sdk/Audio/AudioOutputFormat.ts). Sample code [**here**](https://github.com/Azure-Samples/cognitive-services-speech-sdk/blob/master/quickstart/csharp/unity/text-to-speech/Assets/Scripts/HelloWorld.cs#L99).
