### ISSUE TITLE
azure service request failed exception

### ISSUE THREAD

**Issue by dhanutpk** [Azure/azure-sdk-for-net#38297]
### Library name and version

Azure.ResourceManager.Automation 1.0.1

### Query/Question

I am failed trigger the automation runbook from c# using Azure.ResourceManager.Automation. getting Service request failed exception.
public void StartRunbook(RunbookCreateParameters runbookCreateParameters, IDictionary<string, string> parameters = null)
        {
            Validator.ArgumentNotNull(runbookCreateParameters, nameof(runbookCreateParameters));

            AzureRetryHelper.WaitAndRetry(
               () =>
                {
                    var automationManagementClient = new ArmClient(this.GetTokenCredentials(), this.configurationOptions.Automation.SubscriptionId);

                     ResourceIdentifier automationJobResourceId = AutomationJobResource.CreateResourceIdentifier(this.configurationOptions.Automation.SubscriptionId, runbookCreateParameters.ResourceGroupName, runbookCreateParameters.AutomationAccountName, runbookCreateParameters.RunbookName);

                    AutomationJobResource automationJob = automationManagementClient.GetAutomationJobResource(automationJobResourceId);

                    // invoke the operation
                    AutomationJobCreateOrUpdateContent content = new AutomationJobCreateOrUpdateContent()
                    {
                        RunbookName = runbookCreateParameters.RunbookName,

                        //Parameters = parameters, // build error - to be fixed 
                        RunOn = runbookCreateParameters.HybridWorkerName,
                    };
                    ArmOperation<AutomationJobResource> lro = automationJob.Update(WaitUntil.Completed, content);                    
                },
                this.logger);
        }

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi, @dhanutpk ,Thank you for using Azure SDK for .NET.
We can't repro your issues. If possilble, could provide more details like: error messages?
