### ISSUE TITLE
New addition to Exception list - 404

### ISSUE THREAD

**Issue by ShriHumrudha** [Azure/azure-sdk-for-net#38293]
Container.ReplaceItemAsync<T> Method returns 404 Cosmos exception when the item is not found. This status code needs to be captured in the exception table.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0286f791-878d-c285-c0d2-ebdfc02470be
* Version Independent ID: c8f1d594-e500-eb4b-50b5-8ec04724c482
* Content: [Container.ReplaceItemAsync&lt;T&gt; Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.replaceitemasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` package is maintained as [#4045](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4045).
