### ISSUE TITLE
[QUERY] Get SubscriptionId from SubscritionCreation before Operation Completes

### ISSUE THREAD

**Issue by MichaelTornackNerdware** [Azure/azure-sdk-for-net#38318]
### Library name and version

Azure.ResourceManager.Subscription 1.0.1

### Query/Question

**How do you get the suscriptionId from the Create Process?**

**Current Approach:** Wait until creation is Completed
```c#
var subscriptionOp= await tenant
      .GetSubscriptionAliases()
      .CreateOrUpdateAsync(
        WaitUntil.Completed,
        ...
      );

var subscriptionId = subscriptionOp.Value.Data.Properties.SubscriptionId
``` 

**Desired approach:** Early yielding of subscriptionId
In specific scenarios it is useful to get the subscriptionId as fast as possible in order to parallelize tasks.
A workflow such as the following would be used:
```c#
    var subscriptionOp= await tenant
      .GetSubscriptionAliases()
      .CreateOrUpdateAsync(
        WaitUntil.Started,
        ...
      );

    var subscriptionId = subscriptionOp.Value.Data.Properties.SubscriptionId ;
    // use subscriptionId in parallel tasks

   await subscriptionOpFirst.WaitForCompletionAsync();
``` 
We know that the Azure Server is returning the subscriptionId when the SDK is calling the endpoint. But the the SDK is not filling the value in the Operation Object.

Would it be possible to return the Id in an earlier step and not wait until completion of the operation?

### Environment

.NET SDK:
 Version:   7.0.110
 Commit:    ba920f88ac

Laufzeitumgebung:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.110\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

**Comment by HarveyLink** [comment]
Hi @MichaelTornackNerdware ,Thank you for using Azure SDK for .NET.
Unfortunately there is no way to get the resource properties until the long running operation is complete. It's by design.
