### ISSUE TITLE
[QUERY] Why ServiceBusClientOptions doesn't inherit from ClientOption?

### ISSUE THREAD

**Issue by IlSocio** [Azure/azure-sdk-for-net#38316]
### Library name and version

Microsoft.Extensions.Azure 1.7.0

### Query/Question

I noticed that most of sdk inherit from the abstract class [ClientOption](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/ClientOptions.cs) eg: [SearchClientOption](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/search/Azure.Search.Documents/src/SearchClientOptions.cs)

Is there any particular reason for [ServiceBusClientOptions ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Client/ServiceBusClientOptions.cs) to not inherit from ClientOption?

**Comment by jsquire** [comment]
Hi @IlSocio.  Thank you for your inquiry.  The `ClientOptions` type in Azure.Core was designed with HTTP and REST API conventions in mind.  It exposes several of these concepts as part of its public API surface.  Service Bus uses the AMQP protocol, which differs from HTTP in some major ways.  As a result, there are properties on `ClientOptions` that are not relevant to Service Bus and other AMQP services and others that would be applied differently than the doc comments describe them.  

The decision to not derive options for our AMQP-based clients was made avoid confusion in terminology and ensure that no properties were exposed on the options that would be ignored by the client.
