### ISSUE TITLE
[QUERY] We are not able to get the method to retrieve files or folders within the backed up recovery point ?

### ISSUE THREAD

**Issue by pksouza23** [Azure/azure-sdk-for-net#38358]
### Library name and version

Azure.ResourceManager.RecoveryServicesBackup 1.0.0

### Query/Question

We used below code to get the fileshare recovery point data, now we need to get **files or folders**  that are backed up within this fileshare recovery point.

**Could you please help us ?**

ResourceIdentifier backupProtectedItemResourceId = BackupProtectedItemResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, vaultName, fabricName, containerName, protectedItemName);
                BackupProtectedItemResource backupProtectedItem = client.GetBackupProtectedItemResource(backupProtectedItemResourceId);

 

                BackupRecoveryPointCollection collection = backupProtectedItem.GetBackupRecoveryPoints();

 

                await foreach (BackupRecoveryPointResource item in collection.GetAllAsync())
                {
                    FileShareRecoveryPoint resourceData = (FileShareRecoveryPoint)item.Data.Properties;
                }

![MicrosoftTeams-image (1)](https://github.com/Azure/azure-sdk-for-net/assets/140831732/95125fbd-d99c-4a36-8540-dee2200f8b01)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pksouza23** [comment]
Thanks

**Comment by pksouza23** [comment]
Hi @ArthurMa1978 @jsquire ,

Any update on this query ?

Thanks in advance.

**Comment by jsquire** [comment]
@pksouza23: Unfortunately, I have no insight.   We'll need an update from @ArthurMa1978 and team.

**Comment by HarveyLink** [comment]
Hi @pksouza23 , Thank you for using Azure SDK for .NET.
Looks like this is beyond our Mgmt SDK coverage, more like a Data operation, or the service team will know the API for this.
The best operation I could offer is try to catch the traffic of those portal operation.
I got one 
## Request:
`https://sdktest1113.file.core.windows.net/sdktest1113?restype=directory&comp=list&prefix=&sharesnapshot=2023-11-13T08%3A46%3A49.0000000Z&marker=&maxresults=30&_=1699867709194&sv=2022-11-02&ss=bqtf&srt=sco&sp=rwdlacuptfxy&se=2023-11-13T17:12:30Z&sig=<Sanitized>`
## Response:
![image](https://github.com/Azure/azure-sdk-for-net/assets/30464227/b7528766-3f25-4169-8c9f-9a6082f8f42f)

Looks like the request is conbine of FileShareSnapshotUri and access token.
And the response is a XML formatted file list you needed.
But how to use it in our SDK is out of my domain knowledge.

**Comment by Daya-Patil** [comment]
During the restore for AFS, portal uses storage API to browse snapshots. Please refer to API here https://learn.microsoft.com/en-us/rest/api/storageservices/list-directories-and-files

**Comment by HarveyLink** [comment]
Thank @Daya-Patil for the answer, based on the provided API, the corresponding method in Data SDK was found. @pksouza23  please check: https://learn.microsoft.com/en-us/dotnet/api/azure.storage.files.shares.sharedirectoryclient.getfilesanddirectories?view=azure-dotnet#azure-storage-files-shares-sharedirectoryclient-getfilesanddirectories(system-string-system-threading-cancellationtoken)
