### ISSUE TITLE
[BUG] CreateGetPropertiesRequest does not include "comp" query parameter.

### ISSUE THREAD

**Issue by aeslinger0** [Azure/azure-sdk-for-net#38368]
### Library name and version

Azure.Storage.Files.Shares 12.15.0

### Describe the bug

Trying to do a simple operation:

```
var share = new ShareClient(connstr, shareName);
var dir = share.GetDirectoryClient("/");
var file = dir.GetFileClient(fileName);
if (!await file.ExistsAsync())
{
    _logger.LogWarning($"Unable to find file in file share storage.");
    return false;
}
```
returns the error:
```
Value for one of the query parameters specified in the request URI is invalid.
RequestId:13858534-601a-002d-2e69-d7f4c3000000
Time:2023-08-25T15:36:22.1222352Z
Status: 400 (Value for one of the query parameters specified in the request URI is invalid.)
ErrorCode: InvalidQueryParameterValue

Additional Information:
QueryParameterName: comp
QueryParameterValue: 
Reason: 

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:13858534-601a-002d-2e69-d7f4c3000000
Time:2023-08-25T15:36:22.1222352Z</Message><QueryParameterName>comp</QueryParameterName><QueryParameterValue /><Reason /></Error>
```
[Looking at the documentation](https://learn.microsoft.com/en-us/rest/api/storageservices/get-file-properties#uri-parameters), it doesn't look like the "comp" query parameter is needed, but the endpoint throws the error anyway.

### Expected behavior

Either the [CreateGetPropertiesRequest ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Files.Shares/src/Generated/ShareRestClient.cs#L129) method should include the "comp" query parameter or the endpoint shouldn't expect it.

### Actual behavior

The client doesn't pass the expected "comp" query parameter and an error is thrown.

`Value for one of the query parameters specified in the request URI is invalid.`

### Reproduction Steps

Run the code above to try to retrieve the properties of a file.

### Environment

Azure Function App running Premium plan.

**Comment by aeslinger0** [comment]
What's even more odd is that it works when I run it locally through Visual Studio. Same code exists local and in Azure, both pointing to the same storage account.

**Comment by navba-MSFT** [comment]
@aeslinger0 Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@aeslinger0 When I looked at the backend logs for the above failing request ID, the failure seems to be for this request url  https://rsmXXXXat.file.core.windows.net:443/?restype=share during [Get Share properties](https://learn.microsoft.com/en-us/rest/api/storageservices/get-share-properties
) operation.

Could you please confirm if you have provided the right `shareName` in your above code ?

Note, The same sample is working fine at my end.

**Comment by aeslinger0** [comment]
Actually, you were right, the `shareName` was incorrect. It was getting retrieved from Azure App Configuration and the config key was wrong - which resulted in a blank value. I would have thought a blank value would have thrown an exception.

This can be closed, but to make it easier for everyone else, perhaps you could throw an exception if `shareName` is blank? Thanks

**Comment by navba-MSFT** [comment]
@aeslinger0 Thanks for getting back. I am glad that the issue is resolved. Regarding your ask about throwing an exception, I believe it's an Azure SDK standard not to be altering the below error messages and display it as is:

```
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:13858534-601a-002d-2e69-d7f4c3000000
Time:2023-08-25T15:36:22.1222352Z</Message><QueryParameterName>comp</QueryParameterName><QueryParameterValue /><Reason /></Error>
```
The expectation in case of above error is to check the REST API calls being done by the SDK underneath and check if the required parameters are passed. Like in your scenario it was [Get Share properties](https://learn.microsoft.com/en-us/rest/api/storageservices/get-share-properties) operation. Hope this answers.
