### ISSUE TITLE
Update documentation for DefaultAzureCredential using Service principal with certificate

### ISSUE THREAD

**Issue by kkazala** [Azure/azure-sdk-for-net#38383]
I believe that the documentation form [Service principal with certificate](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#service-principal-with-certificate) is incorrect:
| Variable name | Value|
|-|-|
|`AZURE_CLIENT_ID` |ID of an Azure AD application|
|`AZURE_TENANT_ID` |ID of the application's Azure AD tenant|
|`AZURE_CLIENT_CERTIFICATE_PATH` | 👉path to a **PFX or PEM**-encoded certificate file including **private key** 👈|
|`AZURE_CLIENT_CERTIFICATE_PASSWORD` |(optional) the password protecting the certificate file (currently only supported for PFX (PKCS12) certificates)|
|`AZURE_CLIENT_SEND_CERTIFICATE_CHAIN` |(optional) send certificate chain in x5c header to support subject name / issuer based authentication|

The [parseCertificate()](https://github.com/Azure/azure-sdk-for-js/blob/d8560f0557e614f1fde4616ea164f32a495378a3/sdk/identity/identity/src/msal/nodeFlows/msalClientCertificate.ts#L63C23-L63C39) ensures the `-----BEGIN CERTIFICATE----- ... -----END CERTIFICATE-----` is included in the certificate file and calculates the thumbprint based on it:
```ts
certificateParts.thumbprint = createHash("sha1")
    .update(Buffer.from(publicKeys[0], "base64"))
    .digest("hex")
    .toUpperCase();
```

But then it also retrieves the private key:
```ts
if (this.configuration.certificatePassword !== undefined) {
        const privateKeyObject = createPrivateKey({
          key: parts.certificateContents,
          passphrase: this.configuration.certificatePassword,
          format: "pem",
        });

        privateKey = privateKeyObject
          .export({
            format: "pem",
            type: "pkcs8",
          })
          .toString();
      } else {
        privateKey = parts.certificateContents;
      }
```
and the ` parts.certificateContents` is the `ClientCertificatePEMCertificate` or the contents of the `ClientCertificatePEMCertificatePath` file.

This means that the `AZURE_CLIENT_CERTIFICATE_PATH `certificate must be a PEM file and must contain both, the certificate and the private key. 
I described my analysis here: [AZURE_CLIENT_CERTIFICATE_PATH](https://dev.to/kkazala/defaultazurecredential-with-certificate-based-authentication-3l1) 
I also use it in my code, and the only way I made it work is with PEM file containing both.

Could you please look into it and if I'm correct, update the documentation?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 91f437c5-363b-f98a-f595-5fcb9bf39d2a
* Version Independent ID: c6232a65-a004-428e-1ddf-84f6049ce875
* Content: [Azure Identity client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#service-principal-with-certificate)
* Content Source: [api/overview/azure/latest/identity-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/identity-readme.md)
* Service: **identity**
* GitHub Login: @schaabs
* Microsoft Alias: **sschaab**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @kkazala - 
Unless I misunderstood, I believe the docs are correct. While it is correct that the PEM must contain the private key, the docs do specify that.

We also support pfx certificates files, which also contain the private key. You can see it demonstrated in [this test](https://github.com/Azure/azure-sdk-for-net/blob/9c006655d623c75dc17e630c8c49fac7c206f30d/sdk/identity/Azure.Identity/tests/ClientCertificateCredentialTests.cs#L24) and in the [code that loads the certificate from disk](https://github.com/Azure/azure-sdk-for-net/blob/9c006655d623c75dc17e630c8c49fac7c206f30d/sdk/identity/Azure.Identity/src/X509Certificate2FromFileProvider.cs#L43-L44)

**Comment by kkazala** [comment]
I think I opened this issue in the wrong repo- the problem is with node not .net
Sorry about that! 🙈
