### ISSUE TITLE
Azure Batch: How I can define VM extensions for a pool?

### ISSUE THREAD

**Issue by benjzh** [Azure/azure-sdk-for-net#3841]
Hello,

I am creating Azure Batch pools with Ubuntu via passing **VirtualMachineConfiguration** to  _client.**PoolOperations.CreatePool** API. However I seem to be unable to define VM extensions for the pool? I need **ManagedIdentityExtensionForLinux** extension for secrets management.

- Thanks

**Comment by matthchr** [comment]
hi @benjzh - Unfortunately Azure Batch doesn't support VM extensions for pools at this time.

I've filed this as a feature request [here](https://github.com/Azure/Batch/issues/16).

Since this is a service limitation and not an SDK specific limitation, @shahabhijeet can we close this issue?
