### ISSUE TITLE
[BUG] Authentication error when using AppendBlobClient and storage access keys

### ISSUE THREAD

**Issue by pilarodriguez** [Azure/azure-sdk-for-net#38412]
### Library name and version

Azure.Storage.Blobs Version 12.16.0

### Describe the bug

I get an authentication error when I use the access keys' connection string and perform an action with the `AppendBlobClient` (delete an existing blob, create a new blob...)

```
Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
```

With that access key, I'm able to create/delete the container, and I'm even able to delete the blob using the BlobClient class.

If instead of using the access key, I generate and use a sas connection string, I don't get any error

### Expected behavior

I would expect that the main connection string from the access key has full access to the storage account

### Actual behavior

I get an authentication error

### Reproduction Steps

```
[Test]
public async Task Working()
{
    var blobServiceClient = new BlobServiceClient("BlobEndpoint=https://StorageAccount.blob.core.windows.net/;SharedAccessSignature=SasToken");
    var blobContainer = blobServiceClient.GetBlobContainerClient("test-container");
    await blobContainer.CreateIfNotExistsAsync();
    var blobReference = blobContainer.GetBlobClient("TestBlob");
    var appendBlobClient = new AppendBlobClient(blobReference.Uri);
    await appendBlobClient.DeleteIfExistsAsync();
    await appendBlobClient.CreateAsync();

}

[Test]
public async Task NotWorking()
{
    var blobServiceClient = new BlobServiceClient("DefaultEndpointsProtocol=https;AccountName=StorageAccount;AccountKey=AccountKey;EndpointSuffix=core.windows.net");
    var blobContainer = blobServiceClient.GetBlobContainerClient("test-container");
    await blobContainer.CreateIfNotExistsAsync();
    var blobReference = blobContainer.GetBlobClient("TestBlob");
    var appendBlobClient = new AppendBlobClient(blobReference.Uri);
    await appendBlobClient.DeleteIfExistsAsync();
    await appendBlobClient.CreateAsync();
}
```
The account name, sas token and account key has been removed from the test

### Environment

Windows 10, Azure Function 4 with .Net 7
VS Version 17.5.1

**Comment by navba-MSFT** [comment]
@pilarodriguez Thanks for reaching out to us and reporting this issue. Could you please share the `x-ms-requestid` (Guid ending with 6 zero's) header from the error message, so that I can look at the backend logs for the cause of the issue. 

Awaiting your reply.

**Comment by pilarodriguez** [comment]
`x-ms-request-id: 0b35fd57-c01e-0050-02e0-db51aa000000`

Thanks for the response

**Comment by navba-MSFT** [comment]
@pilarodriguez While I looked at the backend logs for the above failing request, I could see the reason for status `401` is because the request somehow came as `Anonymous `request while performing the delete operation for the blob https://ba*****ple.blob.core.windows.net/test-container/TestBlob . 

Please Update the code as below to perform the delete operation:

```
    var blobServiceClient = new BlobServiceClient("DefaultEndpointsProtocol=https;AccountName=StorageAccount;AccountKey=AccountKey;EndpointSuffix=core.windows.net");
    var blobContainer = blobServiceClient.GetBlobContainerClient("test-container");
    await blobContainer.CreateIfNotExistsAsync();
    var blobReference = blobContainer.GetBlobClient("TestBlob");

    // Create the AppendBlobClient using the blobContainer and blob name
    var appendBlobClient = blobContainer.GetAppendBlobClient("TestBlob");

    await appendBlobClient.DeleteIfExistsAsync();
```

If you want to create an append blob you can see the same code [here](https://github.com/Azure/azure-sdk-for-net/issues/15349#issuecomment-698015387).

Hope this helps.

**Comment by pilarodriguez** [comment]
It works. Thanks a lot for your help

**Comment by navba-MSFT** [comment]
@pilarodriguez
