### ISSUE TITLE
Azure SDK operated limitation

### ISSUE THREAD

**Issue by IanLin419** [Azure/azure-sdk-for-net#3842]
We encountered a problem about Azure SDK.
No matter what operations(iot, keyvault, AAD, etc.) we attempt to though Azure SDK within program, we got a certain failed rate (30% successful).
However we used in localhost environment, there is no any problem. 
We wonder know whether there a limitation for using Azure SDK to reach operation within Azure resource.

The workaround is that we conduct those operation through REST Api instead of Azure SDK.
I do appreciate any information about it.

Regards,
Ian

**Comment by AlexGhiondea** [comment]
@IanLin419 please file a new issue if you are still experiencing issues.
