### ISSUE TITLE
WebSites SDK is missing tests for a large number of features

### ISSUE THREAD

**Issue by Nking92** [Azure/azure-sdk-for-net#3844]
The WebSites SDK is currently not very well-tested. Azure Web Apps has a large team and exposes a very large API surface that would take an enormous amount of work and research for one engineer to test thoroughly. We will divide up the testing between feature owners on our team to develop an acceptable test suite. The feature owners have the background knowledge necessary to create tests and debug them as problems are found.

**Comment by shahabhijeet** [comment]
@Nking92 Please plan this work before the next PR for websites.

**Comment by AlexGhiondea** [comment]
Closing this for now. Please reactivate if still relevant.
