### ISSUE TITLE
Monitor Readme Issue

### ISSUE THREAD

**Issue by zhangjiale-64** [Azure/azure-sdk-for-net#38444]
1. **Section**   [link](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Monitor.OpenTelemetry.AspNetCore_1.0.0-beta.5/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/README.md):
![image](https://github.com/Azure/azure-sdk-for-net/assets/141405558/5cb1068b-8b08-49c6-8c98-1c4500b19e82)

![image](https://github.com/Azure/azure-sdk-for-net/assets/141405558/3960288c-ab38-48e7-a2ad-78bd961dfbde)

**Reason**:
Error 404 after opening the link.

**Suggestion**:
Link change to: https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/logs/getting-started-console.

@scottaddie , @srnagar , @cijothomas and @jsquire to notification.

**Comment by SaurabhSharma-MSFT** [comment]
@zhangjiale-64 I believe this issue has been addressed through this [PR](https://github.com/Azure/azure-sdk-for-net/pull/38114) and default branch [Readme](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/monitor/Azure.Monitor.OpenTelemetry.AspNetCore/README.md) now have the correct link.
Thanks

**Comment by zhangjiale-64** [comment]
@SaurabhSharma-MSFT  This issues has been fixed, we will close this issue.
