### ISSUE TITLE
[FEATURE REQ] Increase the Azure Functions Event Hubs max batch size default to 100

### ISSUE THREAD

**Issue by nzthiago** [Azure/azure-sdk-for-net#38452]
### Library name

Microsoft.Azure.WebJobs.Extensions.EventHubs

### Please describe the feature.

I propose a change of the default `maxEventBatchSize` to `100` from the current default of `10` for the Azure Functions Event Hubs extension.

it is currently documented [in host.json](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-hubs?tabs=in-process%2Cextensionv5&pivots=programming-language-javascript#hostjson-settings) and [in Target Based Scaling](https://learn.microsoft.com/en-us/azure/azure-functions/functions-target-based-scaling?tabs=v5%2Ccsharp), and implemented [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Config/EventHubOptions.cs#L21), as `10`.

The reasons for this proposal are:
* This better matches the PrefetchCount setting that defaults to 300. The SDK itself uses 100/300 for the batch size-to-prefetch ratio as a default. See [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs.Processor/src/EventProcessorClientOptions.cs#L23) - CacheEventCount is the batch read size for the processor client
* This would be beneficial to the average scenario and help to improve performance and lower costs (due to fewer executions)
* We have received customer feedback that the default is too low and they had to change from the default to achieve acceptable throughput and scaling

Impact:
* This would be a behavioral breaking change. Customer code that was written to expect `10` as the batch size would start to receive `100` instead. That may cause some issues, such as consistent timeouts, less frequent checkpoints being written, or performance degradation – it all depends on the app and environment. 
* This would change the default scaling behavior of Target Based Scaling for apps with the Event Hubs trigger that use the updated package 
* 
Therefore, this is recommended as a **major version** change for the Microsoft.Azure.WebJobs.Extensions.EventHubs package.

**Comment by jsquire** [comment]
Addressed by #38456.
