### ISSUE TITLE
[BUG]usBatchset Blob access tier to archive will report BlobAccessTierNotSupportedForAccountType 400 error.

### ISSUE THREAD

**Issue by leoliudan** [Azure/azure-sdk-for-net#38465]
### Library name and version

Azure.Storage.Blobs.Batch      12.14.0

### Describe the bug

set Blob access tier to archive will report error.

https://learn.microsoft.com/en-us/dotnet/api/overview/azure/storage.blobs.batch-readme?view=azure-dotnet#setting-access-tiers
// Set the access tier for all three blobs at once
BlobBatchClient batch = service.GetBlobBatchClient();
batch.SetBlobsAccessTier(new Uri[] { foo.Uri, bar.Uri, baz.Uri }, AccessTier.Cool);
batch.SetBlobsAccessTier(new Uri[] { foo.Uri, bar.Uri, baz.Uri }, AccessTier.Cold);
batch.SetBlobsAccessTier(new Uri[] { foo.Uri, bar.Uri, baz.Uri }, AccessTier.Archive);

C:\Users\danliu1\MyApp>dotnet list package
Project 'MyApp' has the following package references
   [net7.0]:
   Top-level Package                Requested   Resolved
   > Azure.Storage.Blobs            12.17.0     12.17.0
   > Azure.Storage.Blobs.Batch      12.14.0     12.14.0

C:\Users\danliu1\MyApp>dotnet run
Unhandled exception. System.AggregateException: 1 batch operation(s) failed. (Blob access tier is not supported on this storage account type.
RequestId:c1fe1549-801e-0023-0fae-dcadba1eeca4
Time:2023-09-01T08:27:07.3660966Z
Status: 400 (Blob access tier is not supported on this storage account type.)
ErrorCode: BlobAccessTierNotSupportedForAccountType

Content:
?<?xml version="1.0" encoding="utf-8"?>
<Error><Code>BlobAccessTierNotSupportedForAccountType</Code><Message>Blob access tier is not supported on this storage account type.
RequestId:c1fe1549-801e-0023-0fae-dcadba1eeca4
Time:2023-09-01T08:27:07.3660966Z</Message></Error>

Headers:
x-ms-error-code: BlobAccessTierNotSupportedForAccountType
x-ms-request-id: c1fe1549-801e-0023-0fae-dcadba1eeca4
x-ms-version: 2023-01-03
x-ms-client-request-id: feb0496a-b162-4a7c-a328-f341a68996fb
Content-Length: 273
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0
)
 ---> Azure.RequestFailedException: Blob access tier is not supported on this storage account type.
RequestId:c1fe1549-801e-0023-0fae-dcadba1eeca4
Time:2023-09-01T08:27:07.3660966Z
Status: 400 (Blob access tier is not supported on this storage account type.)
ErrorCode: BlobAccessTierNotSupportedForAccountType

Content:
?<?xml version="1.0" encoding="utf-8"?>
<Error><Code>BlobAccessTierNotSupportedForAccountType</Code><Message>Blob access tier is not supported on this storage account type.
RequestId:c1fe1549-801e-0023-0fae-dcadba1eeca4
Time:2023-09-01T08:27:07.3660966Z</Message></Error>

Headers:
x-ms-error-code: BlobAccessTierNotSupportedForAccountType
x-ms-request-id: c1fe1549-801e-0023-0fae-dcadba1eeca4
x-ms-version: 2023-01-03
x-ms-client-request-id: feb0496a-b162-4a7c-a328-f341a68996fb
Content-Length: 273
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0

   at Azure.Storage.Blobs.Specialized.BlobBatch.<>c.<SetBlobAccessTier>b__26_0(Response response)
   at Azure.Storage.Blobs.Specialized.DelayedResponse.SetLiveResponse(Response live, Boolean throwOnFailure)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.UpdateOperationResponses(IList`1 messages, Response rawResponse, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.UpdateOperationResponses(IList`1 messages, Response rawResponse, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.SubmitBatchInternal(BlobBatch batch, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.SetBlobsAccessTierInteral(IEnumerable`1 blobUris, AccessTier accessTier, Nullable`1 rehydratePriority, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.SetBlobsAccessTier(IEnumerable`1 blobUris, AccessTier accessTier, Nullable`1 rehydratePriority, CancellationToken cancellationToken)
   at Program.Main(String[] args) in C:\Users\danliu1\MyApp\Program.cs:line 31

### Expected behavior

set access tier to archive by Azure.Storage.Blobs.Batch will be successful

### Actual behavior

Status: 400 (Blob access tier is not supported on this storage account type.)
ErrorCode: BlobAccessTierNotSupportedForAccountType

### Reproduction Steps

// Get a connection string to our Azure Storage account.
string connectionString = "<connection_string>";
string containerName = "sample-container";

// Get a reference to a container named "sample-container" and then create it
BlobServiceClient service = new BlobServiceClient(connectionString);
BlobContainerClient container = service.GetBlobContainerClient(containerName);
container.Create();
// Create three blobs named "foo", "bar", and "baz"
BlobClient foo = container.GetBlobClient("foo");
BlobClient bar = container.GetBlobClient("bar");
BlobClient baz = container.GetBlobClient("baz");
foo.Upload(BinaryData.FromString("Foo!"));
bar.Upload(BinaryData.FromString("Bar!"));
baz.Upload(BinaryData.FromString("Baz!"));

// Set the access tier for all three blobs at once
BlobBatchClient batch = service.GetBlobBatchClient();
batch.SetBlobsAccessTier(new Uri[] { foo.Uri, bar.Uri, baz.Uri }, AccessTier.Archive);

### Environment

C:\Users\danliu1\MyApp>dotnet list package
Project 'MyApp' has the following package references
   [net7.0]:
   Top-level Package                Requested   Resolved
   > Azure.Storage.Blobs            12.17.0     12.17.0
   > Azure.Storage.Blobs.Batch      12.14.0     12.14.0

C:\Users\danliu1\MyApp>dotnet --info      
.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  6.0.316 [C:\Program Files\dotnet\sdk]
  7.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by navba-MSFT** [comment]
@leoliudan Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by leoliudan** [comment]
@navba-MSFT 
I checked this issue this morning, it was fixed now, I don`t know what was changed on the Azure side.

**Comment by navba-MSFT** [comment]
@leoliudan The Access Tiers are supported for general-purpose v2 or Blob Storage account types. Please check the type of your storage account. I am guessing you might be using GpV1 storage account which doesn't support Access Tier.
