### ISSUE TITLE
[BUG] ScopedResolver Found IListener Container is disposed

### ISSUE THREAD

**Issue by p0onage** [Azure/azure-sdk-for-net#38466]
### Library name and version

Azure.storage.queues 12.14.0 

### Describe the bug

The host is disposed and cannot be used. Disposed object: 'Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedResolver'; Found IListener in stack trace: 'Microsoft.Azure.WebJobs.Extensions.Storage.Common.Listeners.QueueListener, Microsoft.Azure.WebJobs.Extensions.Storage.Queues, Version=5.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' Container is disposed and should not be used: Container is disposed.
You may include Dispose stack-trace into the message via:
container.With(rules => rules.WithCaptureContainerDisposeStackTrace()) 

I can see there is bug fixes in Azure.storage.queues 12.15.0 would upgrading resolve this issue? 

### Expected behavior

Not to have the container disposed, items on the queue are entering a poison queue when this is hit 

### Actual behavior

Not to throw exception

### Reproduction Steps

Happens occasionally under load

**Comment by navba-MSFT** [comment]
@p0onage Apologies for the late reply. Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@p0onage Could you please upgrade the `Microsoft.Azure.WebJobs.Extensions.Storage.Queues` package to the most recent version and check if that helps ?

https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/5.1.3

Awaiting your reply.
