### ISSUE TITLE
[QUERY] When is Azure.Monitor.OpenTelemetry.Exporter going GA?

### ISSUE THREAD

**Issue by valentincpopa** [Azure/azure-sdk-for-net#38474]
### Library name and version

Azure.Monitor.OpenTelemetry.Exporter

### Query/Question

As per this is [issue](https://github.com/Azure/azure-sdk-for-net/issues/32226), the exporter should be GA soon (_The tentative ETA is Apr23 – Sep23_). Are there any new updates regarding the tentative ETA?

What issues are in the way between the current BETA and GA?
What can the community do to move this along?

Thanks!

### Environment

.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Microsoft Visual Studio Enterprise 2022
Version 17.4.3
VisualStudio.17.Release/17.4.3+33205.214
Microsoft .NET Framework
Version 4.8.04084

**Comment by navba-MSFT** [comment]
@valentincpopa Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@valentincpopa We’re still targeting end of September. 

Are you using custom events? If so, how? 

Could you also let me know the importance for waiting for the library to get GA'd ? Is it stability, company policy, feature set, or something else? What is your use case ?

**Comment by valentincpopa** [comment]
Hi, thank you for your answer!

We're currently targeting a production release in December and it's company policy to not use any package that's currently in preview so we might not be able to start integrating open telemetry until the package goes GA. 

If by custom events you're referring to custom activity sources, we would like to integrate those throughout the application. If you're referring to custom events added on an activity, we might not need those just yet, but we will need to be able to export custom telemetry created by other libraries (e.g. MassTransit)

For now, the default behavior (`builder.Services.AddOpenTelemetry().UseAzureMonitor()`) is more than enough (assuming the custom activities, metrics, etc. will also be propagated to Azure Monitor, but from our tests it seems like everything is working out of the box - after configuring the sources with `ConfigureOpenTelemetryTracerProvider` and `ConfigureOpenTelemetryMeterProvider`).

One more question, the GA release would also include `Azure.Monitor.OpenTelemetry.AspNetCore`? I guess this includes some additional extensions alongside the base `Azure.Monitor.OpenTelemetry.Exporter` package? 

Thank you!

**Comment by navba-MSFT** [comment]
@valentincpopa Thanks for sharing the details. Please send an email to navba [ @ ] microsoft .(dot) com. I would require some more information.

**Comment by TimothyMothra** [comment]
Hi @valentincpopa, our Exporter has gone GA today :)

https://www.nuget.org/packages/Azure.Monitor.OpenTelemetry.Exporter/1.0.0

**Comment by valentincpopa** [comment]
This is great news, thank you!
