### ISSUE TITLE
"Managing EventHubs" Link Under "More Sample Code" is a Dead Link

### ISSUE THREAD

**Issue by StrawnSC** [Azure/azure-sdk-for-net#38481]
See Title.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab732946-2eb1-111d-5b9a-567204c84c68
* Version Independent ID: 7c061dd7-65b7-d7a0-da91-867264dd183f
* Content: [Azure Event Hubs Management client library for .NET - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/resourcemanager.eventhubs-readme?view=azure-dotnet)
* Content Source: [api/overview/azure/latest/resourcemanager.eventhubs-readme.md](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/api/overview/azure/latest/resourcemanager.eventhubs-readme.md)
* Service: **eventhub**
* GitHub Login: @serkantkaraca
* Microsoft Alias: **serkar**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
