### ISSUE TITLE
groups cannot be used in AllowedPrincipals 

### ISSUE THREAD

**Issue by mlooise** [Azure/azure-sdk-for-net#38485]
According to the page such as https://learn.microsoft.com/en-us/javascript/api/%40azure/arm-appservice/allowedprincipals?view=azure-node-latest you would expect that also a list of groups (Get-AzureADUserMembership) could be supplied next to a list of identities. This is however not the case. I could not get it to work. Would be a very nice addition however to allow people based on a group instead of there own ID's.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 20e6a633-c8ef-dc7d-daf3-792fea41918a
* Version Independent ID: 8b4d68dc-81ff-f947-9cca-d2b97968333a
* Content: [AllowedPrincipals Class (Microsoft.Azure.Management.WebSites.Models) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.allowedprincipals?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Management.WebSites.Models/AllowedPrincipals.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Management.WebSites.Models/AllowedPrincipals.xml)
* Service: **app-service**
* Sub-service: **web-apps**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Hey @mlooise, thank you for reaching out to us about the Azure SDK for .NET.  
Do you mean you want to have the group name here instead of the guid? If yes then SDK can't support it as the Service does provide such REST APIs.

**Comment by mlooise** [comment]
Hi @ArthurMa1978. Thanks for your reply. 

I did not specifically mean to use group names. It would be more user friendly but for me it's enough if I just can use group ObjectIds which I can retrieve by using something like Get-AzureADUserMembership -ObjectId myaccountobjectguid. 

However whatever I tried this easyAuth system did not respect or use the correct groups as a check in the Auth flow. Looking at the documentation you should be able to use either users or groups or Identities in the allowedPrincipals section as I mentioned above. Is this correct?

 Or Should I just use the objectId's of either groups or users directly in the allowedPrincipals section? And thus not nest an identities or groups section in it.  Could you maybe supply an example? 

maybe this?

`validation": {
        "allowedAudiences": [
          "api://esome"
        ],
        "defaultAuthorizationPolicy": {
          "allowedPrincipals": { xxx, yyy  }
        },
        "jwtClaimChecks": {}
      }`

or even this? 

`validation": {
        "allowedAudiences": [
          "api://esome"
        ],
        "defaultAuthorizationPolicy": {
          "allowedPrincipals": [ xxx, yyy  ]
        },
        "jwtClaimChecks": {}
      }`

**Comment by mlooise** [comment]
To add to this. This does work

`"defaultAuthorizationPolicy": {
          "allowedPrincipals": 
          { 
            "identities": ["xxx"]
          }
        },
`

But when I change it to either a) an objectid of a group or **b)** change 'identities' to 'groups' and pass in the groupid either an **a)** unautorised error happens (You do not have permission to view this directory or page.) or even **b)** internal server error occurs: The page cannot be displayed because an internal server error has occurred.

**Comment by pregress** [comment]
We experience the same, when we use the Rest API: https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/get-auth-settings-v2#allowedprincipals


- when `identities` is set to a single object_id of a user/service principal/managed identity this does work
- when `identities` is set to a list of object_id's of a user/service principal/managed identity this does work
- when we set `groups` to an object_id of an ad group this returns a 500. No logs in azure portal under web app => authentication => troubleshoot
- when set `groups` to the name of an ad group this returns a 500.  No logs in azure portal under web app =>  authentication => troubleshoot


When we receive a 500, there is no response content, no response headers.
The token being send in all scenarios always contains always the same claims & the user is part of the AD group.

Also the documentation could be improved both for jwt and allowed principals.

Sample content
```
"azureActiveDirectory": {
        "enabled": true,
        "login": {
          "disableWWWAuthenticate": false
        },
        "registration": {
          "clientId": "redacted guid",
          "clientSecretSettingName": "ClientSecret",
          "openIdIssuer": "https://sts.windows.net/redacted guid/v2.0"
        },
        "validation": {
          "defaultAuthorizationPolicy": {
            "allowedPrincipals": {
              "groups": [
                "redacted object_id of an ad group"
              ]
            }
          },
          "jwtClaimChecks": {}
        }
      },
```
The complete auth settings config: https://gist.github.com/pregress/44b8aaee7c275e9a1cd2c24bfee371bd

Only 401 errors reported (= which is ok), no 500 errors reported:
![image](https://github.com/Azure/azure-sdk-for-net/assets/1079843/61efdb48-189e-4845-abda-cf14f8adc70c)

I don't think this is an SDK issue, but an Azure issue, can this be forwarded to the correct team?

**Comment by MaxMommersteeg** [comment]
We're encountering a similar challenge when utilizing EasyAuth.

Ideally, we would like to configure either groups or, as a workaround, have a significantly increased character limit for identities.

It's worth noting that a GUID consists of 36 characters. In the context of a microservice architecture, this would limit us to configuring a maximum of 13 applications and users combined. Unfortunately, this falls short of meeting the demands of our environment, where multiple applications, developers, and testers require access to a single application.

**Comment by gambitanalytics** [comment]
I would like to add my voice to the chorus of folks requesting that we be able to use a group ObjectId to authorize groups of users rather than individual user ObjectIds.

**Comment by pregress** [comment]
@ArthurMa1978 could you forward this to the correct azure team? 
Multiple people/teams are hitting the same issue, we also contact Azure support about this, but we keep running in circles.

**Comment by gambitanalytics** [comment]
I've worked with Azure support and while it took about 2 weeks for them to get back to me, I have learned two things that I think will help folks here understand what is going on. **TLDR: I think we are correctly getting internal server errors because we do not have the correct Entra ID subscription level to allow group-based authorization.**

First, the helpful thing I learned. There appears to be a non-REST API way to assign user- and group-based authorization. This can be found in Azure Portal -> Entra ID -> Enterprise Applications -> Select the relevant application -> Users and Groups. I have played around with this and working here is equivalent to working with the allowedPrincipals section of the REST API. 

Now, in this same part of the Azure portal (Users and Groups of your Enterprise Application), you can add a group for authorization. But when I attempt to do so, I get this little warning:

![image](https://github.com/Azure/azure-sdk-for-net/assets/125092199/37f51942-058e-4f3a-8e58-8d5223ae8e0d)

Clicking that warning box tells me that I need either "Enterprise Mobility + Security E5" or "Microsoft Entra ID P2" service levels to use group-based authorization. I am not 100% sure that this is the cause of the internal server error I'm getting (neither is my support rep) and I'm not going to ship Microsoft $9/user to find out. But I would bet that this is the cause of the problem - not a bug.

**Comment by pregress** [comment]
I was able to retrieve the following error:

> An error occurred while checking group membership for 'pr PII': Unable to retrieve a token for Graph at https://graph.windows.net using the provided bearer token. 
 Using access token assertion to get bearer token from Graph API. 
 Unable to check group membership using AAD Graph. Exception: Microsoft.Azure.AppService.Middleware.HttpException: Exception of type 'Microsoft.Azure.AppService.Middleware.HttpException' was thrown.
	at Microsoft.Azure.AppService.Middleware.AzureActiveDirectoryProvider.GetGraphAccessTokenAsync(HttpRequestBase request, AuthenticatedPrincipal user, String graphScope) in /__w/1/s/src/EasyAuth/Microsoft.Azure.AppService.Middleware.Modules/IdentityProviders/AzureActiveDirectoryProvider.cs:line 1516
	at Microsoft.Azure.AppService.Middleware.AzureActiveDirectoryProvider.GetMatchingRequiredGroupsFromGraph(HttpRequestBase request, AuthenticatedPrincipal user, String principalName, String[] allowedGroups, String graphScope) in /__w/1/s/src/EasyAuth/Microsoft.Azure.AppService.Middleware.Modules/IdentityProviders/AzureActiveDirectoryProvider.cs:line 1386
	at Microsoft.Azure.AppService.Middleware.AzureActiveDirectoryProvider.<>c__DisplayClass59_0.<g__AadGraphCheck|0>d.MoveNext() in /__w/1/s/src/EasyAuth/Microsoft.Azure.AppService.Middleware.Modules/IdentityProviders/AzureActiveDirectoryProvider.cs:line 1313 


If it would be a license problem I would expect an error while setting groups property, and not at runtime.

**Comment by ArthurMa1978** [comment]
Hey @mlooise, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) which can find the right contact for your question.

**Comment by mlooise** [comment]
@ArthurMa1978 Why have you closed this issue? I was following this issue with interest and have seen that others also have this problem and could even contribute to the direction of the issue, so why now close it? Are you saying that this feature does work but needs other settings? Could you please elaborate a bit? 

What would opening a support request add to this discussion. I would rather have it more clarified in this thread

**Comment by pregress** [comment]
Here is the solution:

1. Go to Entra / Azure Ad
2. Go to app registrations
3. Search/ open your app registration thats configured for easy auth
4. Edit the manifest
5. Set `"groupMembershipClaims": null` to `"groupMembershipClaims": "SecurityGroup"` 
6. Wait (this took at least 10 minutes) 

https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-app-service-authentication-8211-aad-groups/ba-p/392368

**Comment by pregress** [comment]
I didn't need any custom code, We configured easy auth, removed the allowed principals , added the allowed groups through `az rest` and changed the `groupMembershipClaims` on the app registration thats configured for easy auth in the web app. 

Validated with the following code:
```
var credential = new AzureCliCredential();
var appId = "guid";
var scope = $"{appId}/.default";
var token = await credential.GetTokenAsync(new TokenRequestContext(new[] { scope }));

var httpClient = new HttpClient();
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token.Token);

var result = await httpClient.GetAsync("https://yourwebapp.azurewebsites.net/");
Console.WriteLine(await result.Content.ReadAsStringAsync());
Console.WriteLine(result.StatusCode);
```

Did return a 500 without the `groupMembershipClaims`. After changing  `groupMembershipClaims`, restarting the web app and a lot of patience, returns a 200.
If no auth header is passed => 401
If a user is used thats not in the group => 403 (this is a configurable status code for easy auth)
