### ISSUE TITLE
[BUG] GetSiteDetectors GetAll - json parsing throws error

### ISSUE THREAD

**Issue by ransht** [Azure/azure-sdk-for-net#38495]
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Describe the bug

    ResourceIdentifier webSiteResourceId =
        WebSiteResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, siteName);
    WebSiteResource webSite = client.GetWebSiteResource(webSiteResourceId);

    var collection = webSite.GetSiteDetectors();
    var all = collection.GetAll();

System.InvalidOperationException: The requested operation requires an element of type 'Array', but the target element has type 'String'.

this is the debug:
in DetectorInfo DeserializeDetectorInfo(JsonElement element):
ValueKind = Object : "{"id":"netcorestartupfailures","name":".NET Core Startup Failures","description":"Recognize common startup failures, get exception messages and stack traces from startup failure events for ASP.NET core apps.","author":"","category":null,"supportTopicList":[],"analysisType":"appDownAnalysis","typeId":"3c46bb93-6dff-4048-9904-8fcd535679e9","analysisTypes":["appDownAnalysis"],"type":"Detector","score":0}"

**property.Value = ValueKijnd = string ""analysisType":"appDownAnalysis""**

                if (property.NameEquals("analysisType"u8))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        continue;
                    }
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())

in enumerate array it goes to throw
        public ArrayEnumerator EnumerateArray()
        {
            CheckValidInstance();

            JsonTokenType tokenType = TokenType;

            if (tokenType != JsonTokenType.StartArray)
            {
                **throw ThrowHelper.GetJsonElementWrongTypeException(JsonTokenType.StartArray, tokenType);**
            }

            return new ArrayEnumerator(this);
        }

### Expected behavior

it shouldnt throw an error

### Actual behavior

Exception was thrown 
System.InvalidOperationException: The requested operation requires an element of type 'Array', but the target element has type 'String'.

### Reproduction Steps

    ResourceIdentifier webSiteResourceId =
        WebSiteResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, siteName);
    WebSiteResource webSite = client.GetWebSiteResource(webSiteResourceId);

    var collection = webSite.GetSiteDetectors();
    var all = collection.GetAll();

### Environment

NET6.0 using the latest sdk version 1.0.2 also tried the beta version 1.1.0-beta.1
still didn't work

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcgallan** [comment]
@ransht I have submitted a PR to fix the bug you mentioned. This bug will be fixed in the unreleased version 1.1.0-beta.5. Thank you for your feedback！
