### ISSUE TITLE
[BUG] Azure.ResourceManager.KubernetesConfiguration using Api version '2022-11-01,2022-11-01' twice and caused the create/update failure

### ISSUE THREAD

**Issue by iwangjintian** [Azure/azure-sdk-for-net#38492]
### Library name and version

Azure.ResourceManager.KubernetesConfiguration 1.0.0 and 1.1.0

### Describe the bug

Trying to create/update Microsoft.AzureKeyVaultSecretsProvider extension on a connected cluster. However, encountered this issue: 
Azure.RequestFailedException
  HResult=0x80131500
  Message=No registered resource provider found for location '**eastasia**' and API version '**2022-11-01,2022-11-01**' for type 'extensions'. The supported api-versions are '2020-07-01-preview, 2021-05-01-preview, 2021-09-01, 2022-03-01, 2022-04-02-preview, 2022-07-01, 2022-11-01, 2023-05-01, 2019-11-01-preview, 2020-10-01-preview, 2021-03-01'. The supported locations are 'eastus, westeurope, westcentralus, westus2, westus3, southcentralus, eastus2, northeurope, uksouth, southeastasia, australiaeast, francecentral, centralus, northcentralus, westus, koreacentral, eastasia, japaneast, canadaeast, canadacentral, norwayeast, germanywestcentral, swedencentral, switzerlandnorth, australiasoutheast, centralindia, southindia, japanwest, ukwest, francesouth, koreasouth, southafricanorth, brazilsouth, uaenorth, norwaywest, germanynorth, jioindiawest, eastus2euap, centraluseuap'.
Status: 400 (Bad Request)
ErrorCode: NoRegisteredProviderFound

Content:
{"error":{"code":"NoRegisteredProviderFound","message":"No registered resource provider found for location 'eastasia' and API version '2022-11-01,2022-11-01' for type 'extensions'. The supported api-versions are '2020-07-01-preview, 2021-05-01-preview, 2021-09-01, 2022-03-01, 2022-04-02-preview, 2022-07-01, 2022-11-01, 2023-05-01, 2019-11-01-preview, 2020-10-01-preview, 2021-03-01'. The supported locations are 'eastus, westeurope, westcentralus, westus2, westus3, southcentralus, eastus2, northeurope, uksouth, southeastasia, australiaeast, francecentral, centralus, northcentralus, westus, koreacentral, eastasia, japaneast, canadaeast, canadacentral, norwayeast, germanywestcentral, swedencentral, switzerlandnorth, australiasoutheast, centralindia, southindia, japanwest, ukwest, francesouth, koreasouth, southafricanorth, brazilsouth, uaenorth, norwaywest, germanynorth, jioindiawest, eastus2euap, centraluseuap'."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-request-id: c91bb804-e116-4d16-a180-c0c0243fda28
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Tue, 05 Sep 2023 05:52:57 GMT
Content-Type: application/json; charset=utf-8
Expires: -1
Content-Length: 924

  Source=Azure.ResourceManager.KubernetesConfiguration
  StackTrace:
   at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state)
   at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternalBase.<UpdateStatusAsync>d__13.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__19.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__15.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.ResourceManager.KubernetesConfiguration.KubernetesClusterExtensionCollection.<CreateOrUpdateAsync>d__8.MoveNext()
   at _202.ArcEnabledExtensionHelper.<CreateOrUpdate_CreateExtension>d__9.MoveNext() in D:\azurearc-samples\202\dotnet\src\ArcEnabledExtensionHelper.cs:line 114
   at _202.Program.Main(String[] args) in D:\azurearc-samples\202\dotnet\src\Program.cs:line 35

Looks like the sdk is doubling the api version 2022-11-01 here. 

### Expected behavior

No apiversion related error

### Actual behavior

api version and location related error.
The actuall api version and location is in the support list.

### Reproduction Steps

I think any extension type would cause this issue.

### Environment

<Project Sdk="Microsoft.NET.Sdk">
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by iwangjintian** [comment]
Any update here?

**Comment by iwangjintian** [comment]
Do we have any update here? It's been a month

**Comment by iwangjintian** [comment]
@jsquire @ArthurMa1978 @HarveyLink 
It's been more than a month and no updates has been made.
Do we have any progress here?

**Comment by HarveyLink** [comment]
Hi @iwangjintian , We have repro this issue, working on a solution now.

**Comment by iwangjintian** [comment]
Haven't heard from you for a while. Do we got any update on this?

**Comment by RodgeFu** [comment]
Service team is still working on a fix for it. will let you know when the fix is deployed. Sorry for the slow progress. thanks.

**Comment by RodgeFu** [comment]
@iwangjintian , the issue should have been fixed. Please give it a try and feel free to let us know if you have more questions. thanks.
