### ISSUE TITLE
Value of constant AUTH_RECORD_PATH not explained

### ISSUE THREAD

**Issue by MarkFD01** [Azure/azure-sdk-for-net#38517]
How is this value established? In order to check for existence of token at app start I need to know the path, on my dev system it's 

C:\Users\\[Windows User Name]\AppData\Local\\.IdentityService\O365_FSMail_TokenCache.nocae

So can it always be built from  [C:\Users\\[Windows User Name]\AppData\Local\\.IdentityService\][TokenCachePersistenceOptions.Name].nocae

E.g. for user "TestUser" and TokenCachePersistenceOptions.Name="TestToken" will it always be 
"C:\Users\TestUser\AppData\Local\\.IdentityService\TestToken.nocae"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 8b7f06c2-e869-c455-4b39-babf320bd343
* Version Independent ID: b99cd14e-64ff-7b0c-0538-1da1eca887b9
* Content: [TokenCachePersistenceOptions Class (Azure.Identity) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.tokencachepersistenceoptions?view=azure-dotnet)
* Content Source: [xml/Azure.Identity/TokenCachePersistenceOptions.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Identity/TokenCachePersistenceOptions.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @MarkFD01 
Your description of the behavior of the `Name` property of `TokenCachePersistenceOptions` is correct. The directory name is the default for MSAL and the provided name is used with a suffix. You also mention that your app checks for the existence of a cache file at startup - could you clarify why your app needs to do this?

Do you also have a question about the value of AUTH_RECORD_PATH (which is distinct from the cache file path)?

**Comment by MarkFD01** [comment]
Hi

My understanding is that the documention shows how to persist tokens between app startups, so when the app starts I need to check AUTH_RECORD_PATH to see if it exists and if it does deserialize the token and use that to create the apps InteractiveBrowserCredential by passing it using TokenCachePersistenceOptions.AuthenticationRecord. The InteractiveBrowserCredential will further update this cache during the app session which I pick up again at the next app start. This means the user will not be prompted fro their creds everytime they start the app.

My issue is the path to check (AUTH_RECORD_PATH) is not described and as all I'm passing is a cache name there appears to be no mechanism to establish AUTH_RECORD_PATH. If you are confirming the path will be 

 [C:\Users\[Windows User Name]\AppData\Local\\.IdentityService][TokenCachePersistenceOptions.Name].nocae

then that's what I was after.

Thanks

**Comment by christothes** [comment]
Ah, ok. The AuthenticationRecord and the cache are two different concepts. You can think of the AuthenticationRecord as the key to the cache entry living in the cache file. It contains account information, but no token information. Your application should never need to be concerned with the actual cache file on disk, other than its name is consistent as controlled by the `Name` property of `TokenCachePersistenceOptions`.

The path to check for AUTH_RECORD_PATH is not described because it is arbitrary and can be any path you choose. You can supply any path you like as long as it's consistent.
