### ISSUE TITLE
[BUG] Azure.ResourceManager.AppService.Models.SlotConfigNamesResource.CreateOrUpdateAsync deserialize issue.

### ISSUE THREAD

**Issue by tombrothers** [Azure/azure-sdk-for-net#38521]
### Library name and version

Azure.ResourceManager.AppService 1.0.2

### Describe the bug

SlotConfigNamesResource.CreateOrUpdateAsync fails due to SlotConfigNamesResourceData deserializing issue.

### Expected behavior

SlotConfigNamesResource.CreateOrUpdateAsync should work.

### Actual behavior

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null. (Parameter 'resourceId')
  Source=Azure.Core
  StackTrace:
   at Azure.Core.Argument.AssertNotNullOrEmpty(String value, String name)
   at Azure.Core.ResourceIdentifier..ctor(String resourceId)
   at Azure.ResourceManager.AppService.SlotConfigNamesResourceData.DeserializeSlotConfigNamesResourceData(JsonElement element)
   at Azure.ResourceManager.AppService.WebAppsRestOperations.<UpdateSlotConfigurationNamesAsync>d__141.MoveNext()
   at Azure.ResourceManager.AppService.SlotConfigNamesResource.<CreateOrUpdateAsync>d__16.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\TomBrothers\source\repos\AppServiceTest\AppServiceTest\Program.cs:line 51

### Reproduction Steps

```
using Azure;
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.AppService;
using Azure.ResourceManager.AppService.Models;
using Azure.ResourceManager.Resources;

var resourceGroupName = "csappplans";
var appServicePlanName = "csappplan0";
var armClient = new ArmClient(new DefaultAzureCredential(new DefaultAzureCredentialOptions
{
#if DEBUG
    ExcludeManagedIdentityCredential = true,
    ExcludeEnvironmentCredential = true,
#endif
}));
var resourceGroupResourceIdentifier = ResourceGroupResource.CreateResourceIdentifier(
    armClient.GetDefaultSubscription().Id.SubscriptionId,
    resourceGroupName
);
var appServicePlanResourceIdentifier = AppServicePlanResource.CreateResourceIdentifier(
    resourceGroupResourceIdentifier.SubscriptionId,
    resourceGroupResourceIdentifier.ResourceGroupName,
    appServicePlanName
);
var webSiteResourceIdentifier = WebSiteResource.CreateResourceIdentifier(
    resourceGroupResourceIdentifier.SubscriptionId,
    resourceGroupResourceIdentifier.ResourceGroupName,
    $"devtest{DateTime.Now:yyyyMMddHHmmss}"
);
var resourceGroupResource = armClient.GetResourceGroupResource(resourceGroupResourceIdentifier);
var webSiteCollection = resourceGroupResource.GetWebSites();
var newWebSiteData = new WebSiteData(AzureLocation.EastUS)
{
    AppServicePlanId = appServicePlanResourceIdentifier,
    SiteConfig = new SiteConfigProperties()
};
var webSiteOperation = await webSiteCollection.CreateOrUpdateAsync(
    WaitUntil.Completed,
    webSiteResourceIdentifier.Name,
    newWebSiteData
);
var webSiteData = webSiteOperation.Value.Data;
var slotConfigNamesResourceIdentifier = SlotConfigNamesResource.CreateResourceIdentifier(
    resourceGroupResourceIdentifier.SubscriptionId,
    resourceGroupResourceIdentifier.ResourceGroupName,
    webSiteResourceIdentifier.Name
);
var slotConfigNamesResource = armClient.GetSlotConfigNamesResource(slotConfigNamesResourceIdentifier);
var operation = await slotConfigNamesResource.CreateOrUpdateAsync(
    WaitUntil.Completed,
    new SlotConfigNamesResourceData {
        AppSettingNames = {
                "Example"
            }
    }
);


Console.ReadLine();
```

### Environment

.NET SDK:
Version: 7.0.307
Commit: 7b77e35a2b

Runtime Environment:
OS Name: Windows
OS Version: 10.0.22621
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\7.0.307\

Host:
Version: 7.0.10
Architecture: x64
Commit: a6dbb800a4

.NET SDKs installed:
7.0.307 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
Microsoft.AspNetCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
x86 [C:\Program Files (x86)\dotnet]
registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
Not set

global.json file:
Not found

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment]
This is a service side issue, it should not return  `id = null`

![image](https://github.com/Azure/azure-sdk-for-net/assets/61542202/e080812b-732f-4e7b-8af2-03f9c9f8d0bd)

**Comment by ArthurMa1978** [comment]
Hey @tombrothers , thank you for reaching out to us about the Azure SDK for .NET. Unfortunately, this issue is related to the service side and not the SDK side, so we are not able to help you with it. Therefore, we are closing this issue for now. If you need more assistance, please [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request). We apologize for any inconvenience this may cause you.

We value your feedback and we want to make sure that your problem is solved. If you think that we have misunderstood your issue or closed it incorrectly, please feel free to comment on this thread and reopen the issue. We will be happy to assist you further. Thank you for your understanding and cooperation.
