### ISSUE TITLE
[Feature Request] Add blob information to error messages

### ISSUE THREAD

**Issue by atsapura** [Azure/azure-sdk-for-net#38526]
### Library name and version

Azure.Storage.Blobs 12.17.0

### Describe the bug

Error response never contains the information about the Blob in question. E.g. when you get `404. Blob does not exist`, you don't get _the name_ of the requested blob. Or when uploading fails the exception says `409. The specified blob already exists`. 

But when I routinely do thousands of operations with blobs, how the hell am I supposed to know afterwards, which of my blob operations failed exactly?

### Expected behavior

The error response contains information about specific blob that failed.

### Actual behavior

The error response contains only generic information.

### Reproduction Steps

Request nonexisting blob via `BlobClient`.

**Comment by navba-MSFT** [comment]
@atsapura Thanks for reaching out to us and reporting this issue. Regarding your ask about showing additional information during an exception, I believe it's an Azure SDK standard not to be altering the below error messages and display it as is:

```
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob doesn't exist
RequestId:13858534-XXXX-XXXX-XXXX-d7f4c3000000
Time:2023-08-25T15:36:22.1222352Z</Message></Error>
```

Also note that the error message is coming directly from the service and **not SDK.** 

To find out the blob operation that failed and the blob name, you can leverage the Azure Storage diagnostic logs. The available fields and the logging format is explained [here](https://learn.microsoft.com/en-us/azure/storage/blobs/monitor-blob-storage-reference#resource-logs).

[This ](https://learn.microsoft.com/en-us/azure/storage/common/manage-storage-analytics-logs?tabs=azure-portal)and [this ](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings?tabs=portal#resource-logs)article talks about how to enable the diagnostic logs.


Once you have enabled the diagnostic logs, you can query it as shown below:
```
StorageBlobLogs
| where TimeGenerated > ago(3d) and StatusText !contains "Success"
| summarize count() by OperationName
| top 10 by count_ desc
```
This list the top 10 operations that caused the most errors over the last three days. Hope this helps.

**Comment by atsapura** [comment]
Well, while I appreciate the need for standardizing SDK responses, I don't think that 1 fixed absolute is the only way to solve that. For instance, you could extend the necessary standard part with helpful extra info. And even if the blob API itself doesn't include blob info, the SDK can very well handle it by just enriching the response with the bits of request data.

**Comment by navba-MSFT** [comment]
> Well, while I appreciate the need for standardizing SDK responses, I don't think that 1 fixed absolute is the only way to solve that. For instance, you could extend the necessary standard part with helpful extra info. And even if the blob API itself doesn't include blob info, the SDK can very well handle it by just enriching the response with the bits of request data.

@seanmcc-msft @amnguye Could you please check if it is possible for updating the error response of the service from SDK ?

**Comment by amnguye** [comment]
Could we get a code snippet about how you're catching this exception?

Since the blob name is already stored on the client, I just want to see how you're calling the blob and where the blob client information goes or how it's saved in memory when you're catching the exception. And maybe we can find a mitigation without having to change much for your scenario.

From the top of my head without knowing your code maybe something like
```
BlobClient blob = new(...);

try
{
  // Make a call to a blob that doesn't yet exist
  await blob.GetPropertiesAsync();
}
catch (RequestFailedException ex)
{
   Console.Print($"The following blob, {blob.Uri.AbsoluteUri) has failed with {ex.Message}");
}
```
If the code snippet above doesn't fit your scenario feel free to provide your own code snippet and we can see what we can do.

But like said before the SDK is not supposed to alter the message sent back from the service.

**Comment by navba-MSFT** [comment]
@atsapura I hope you had a chance to look at the above suggestion and test it at your end. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
