### ISSUE TITLE
TableServiceClient CreateTableIfNotExists bug or docs are wrong

### ISSUE THREAD

**Issue by longtimedeveloper** [Azure/azure-sdk-for-net#38522]
[Enter feedback here]

Returns
[Response]<[TableItem]>

If the table does not already exist, a [Response<T>]. If the table already exists, null.

### Problem

**If the table already exists, null.** this is the issue.  When they table does exist, it still returns the table name.  But the docs says it will return null.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 68e5eef1-c0c2-5f5f-1a39-f5d2cdbfd6bc
* Version Independent ID: 32218643-4125-6a6e-fa5f-3d4819f1302e
* Content: [TableServiceClient.CreateTableIfNotExists(String, CancellationToken) Method (Azure.Data.Tables) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/azure.data.tables.tableserviceclient.createtableifnotexists?view=azure-dotnet)
* Content Source: [xml/Azure.Data.Tables/TableServiceClient.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Data.Tables/TableServiceClient.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by pallavit** [comment]
Thank you for your feedback. Tagging and routing to the team member best able to assist.
/cc: @christothes
