### ISSUE TITLE
[BUG] GetSiteInstances throws Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by xieofxie** [Azure/azure-sdk-for-net#38548]
### Library name and version

Azure.ResourceManager.AppService 1.1.0-beta.2

### Describe the bug

When I use GetSiteInstances, the exception is thrown. 

Search for the issues, we have similar ones before and the solution is add a new one as string: https://github.com/Azure/azure-sdk-for-net/issues?q=is%3Aissue+Invalid+URI%3A+The+format+of+the+URI+could+not+be+determined.+is%3Aclosed

### Expected behavior

no exception

### Actual behavior

exception thrown.

### Reproduction Steps

- Set up `Health check`
- Then the `healthCheckUrl` becomes `/home` etc.
- The exception is thrown

**Comment by live1206** [comment]
@xieofxie Could you provide the stack trace of the error? So that we can take a look at it.

**Comment by live1206** [comment]
Thanks for the error info.
If we take a look at the Deserialize method, there are a few Uri fields involved.
Could you help to check the raw content of the service response? So that we know which one is not a valid Uri.
Please refer to [this](https://github.com/Azure/azure-rest-api-specs-examples/issues/3219#issuecomment-1670603247) about how to get raw response content. Thanks!

**Comment by xieofxie** [comment]
{
  "value": [
    {
      "id": "/subscriptions/a063fXXX",
      "name": "c8afdXXX",
      "type": "Microsoft.Web/sites/instances",
      "location": "UAE North",
      "properties": {
        "state": "READY",
        "name": "c8afdXXX",
        "siteInstanceName": "c8afd7XXX",
        "statusUrl": "",
        "detectorUrl": "https://bfs-XXX.scm.azurewebsites.net/detectors",
        "consoleUrl": "https://bfs-XXX.scm.azurewebsites.net/DebugConsole?instance=c8afdXXX",
        "healthCheckUrl": "/private",
        "machineName": "pd0sXXX",
        "containers": null
      }
    }]
}

I think the problem is `healthCheckUrl`

**Comment by live1206** [comment]
Will be fixed in the next release.
