### ISSUE TITLE
MaxSizeInMegabytes is ignored and always sets the queue to 16GB

### ISSUE THREAD

**Issue by brutaldev** [Azure/azure-sdk-for-net#3855]
It seems that no matter what value to provide to the `MaxSizeInMegabytes` property, the queue is always created with the max size of 16GB, is this expected?

The following simple code to create a queue highlights this problem.

```csharp
using (var managementClient = new ServiceBusManagementClient(new TokenCredentials(accessToken)))
{
    managementClient.SubscriptionId = "MySubsciptionId";        
    var queueParams = new SBQueue
    {
      EnablePartitioning = true,  // <-- Only when this is true
      MaxSizeInMegabytes = 2048  // <-- Get ignored, even if not setting the property at all, the default is 16GB not 1GB as stipulated by the documentation.
    };

    await managementClient.Queues.CreateOrUpdateAsync(Constants.ResourceGroupName, Constants.NamespaceName, "TwoGBQueue", queueParams);
}
```

The documentation claims the default it 1GB, but the queue is always created as a 16GB queue.

**Comment by brutaldev** [comment]
I've figured out that this only happens when you have `EnablePartitioning` switched on. Setting that to false honors the max size setting. Would certainly help having the documentation highlight this to avoid confusion.

**Comment by axisc** [comment]
@brutaldev - thanks for bringing this to our attention. This has already been documented [here](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning#enable-partitioning). 

I'm closing the issue for now, but please feel free to reopen if you still have questions.
