### ISSUE TITLE
ArgumentNullException "when either item is not set"

### ISSUE THREAD

**Issue by chaospixel** [Azure/azure-sdk-for-net#38569]
[Enter feedback here]

Does this mean that the exception is thrown when no item exists with the specified id?
It appears clear that it means that the exception will be thrown if no new item is supplied (i.e. null is the argument to the item parameter). I am just not clear on what other item is implied by the "either" in "either item"...

Please clarify.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0286f791-878d-c285-c0d2-ebdfc02470be
* Version Independent ID: c8f1d594-e500-eb4b-50b5-8ec04724c482
* Content: [Container.ReplaceItemAsync&lt;T&gt; Method (Microsoft.Azure.Cosmos) - Azure for .NET Developers](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.replaceitemasync?view=azure-dotnet)
* Content Source: [xml/Microsoft.Azure.Cosmos/Container.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Microsoft.Azure.Cosmos/Container.xml)
* Service: **cosmos-db**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by jsquire** [comment]
This issue has been transferred to the repository where the `Microsoft.Azure.Cosmos` library is maintained as [#4072](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4072).
